### ISSUE TITLE
Query: GroupBy Queryable does not use QueryableAdapter 

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#10023]
```
        [ConditionalFact]
        public virtual void GroupBy_anonymous_subquery()
        {
            AssertQuery<Customer>(
                cs =>
                    cs.Select(c => new { c.City, c.CustomerID })
                        .GroupBy(a => from c2 in cs select c2),
                assertOrder: true);
        }
```
Exception:
```
Test 'Microsoft.EntityFrameworkCore.Query.GroupByQuerySqlServerTest.GroupBy_anonymous_subquery' failed: System.AggregateException : One or more errors occurred.
---- System.ArgumentException : Expression of type 'System.Collections.Generic.IEnumerable`1[System.Linq.IGrouping`2[System.Collections.Generic.IEnumerable`1[Microsoft.EntityFrameworkCore.TestModels.Northwind.Customer],<>f__AnonymousType34`2[System.String,System.String]]]' cannot be used for return type 'System.Collections.Generic.IEnumerable`1[System.Linq.IGrouping`2[System.Linq.IQueryable`1[Microsoft.EntityFrameworkCore.TestModels.Northwind.Customer],<>f__AnonymousType34`2[System.String,System.String]]]'
	at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
	at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
	at System.Threading.Tasks.Task.Wait()
	D:\code\EntityFrameworkCore\src\EFCore.Specification.Tests\Query\QueryTestBase.cs(83,0): at Microsoft.EntityFrameworkCore.Query.QueryTestBase`1.AssertQuery[TItem1](Func`2 query, Func`2 elementSorter, Action`2 elementAsserter, Boolean assertOrder, Int32 entryCount)
	D:\code\EntityFrameworkCore\src\EFCore.Specification.Tests\Query\GroupByQueryTestBase.cs(919,0): at Microsoft.EntityFrameworkCore.Query.GroupByQueryTestBase`1.GroupBy_anonymous_subquery()
	D:\code\EntityFrameworkCore\test\EFCore.SqlServer.FunctionalTests\Query\GroupByQuerySqlServerTest.cs(875,0): at Microsoft.EntityFrameworkCore.Query.GroupByQuerySqlServerTest.GroupBy_anonymous_subquery()
	----- Inner Stack Trace -----
	at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters)
	at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
	at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, Boolean tailCall, IEnumerable`1 parameters)
	at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, ParameterExpression[] parameters)
	D:\code\EntityFrameworkCore\src\EFCore\Query\EntityQueryModelVisitor.cs(622,0): at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateExecutorLambda[TResults]()
	D:\code\EntityFrameworkCore\src\EFCore\Query\EntityQueryModelVisitor.cs(179,0): at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
	D:\code\EntityFrameworkCore\src\EFCore\Storage\Database.cs(70,0): at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs(164,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
	D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs(103,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_0`1.<Execute>b__0()
	D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\CompiledQueryCache.cs(69,0): at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
	D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\CompiledQueryCache.cs(44,0): at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
	D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs(99,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
	D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\EntityQueryProvider.cs(62,0): at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
	at Remotion.Linq.QueryableBase`1.GetEnumerator()
	at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
	at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
	D:\code\EntityFrameworkCore\src\EFCore.Specification.Tests\TestUtilities\QueryAsserter.cs(333,0): at Microsoft.EntityFrameworkCore.TestUtilities.QueryAsserter`1.<AssertQuery>d__18`1.MoveNext()
```
Mismatch here is IGrouping is on IQueryable but when we visit SubQueryExpression, it changes type to IEnumerable. We need to utilize `ProjectionExpressionVisitor.VisitSubQuery` method to introduce queryable adapter.

**Comment by smitpatel** [comment]
This is client side group by which is not supported as per #17068
