### ISSUE TITLE
Trying to run a query with a subquery but it throws NullReferenceException

### ISSUE THREAD

**Issue by HristoKolev** [dotnet/efcore#10128]
Describe what is not working as expected.

I'm trying to run a query with a subquery but it throws NullReferenceException

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: Object reference not set to an instance of an object.
Stack trace:   at lambda_method(Closure , QueryContext , ValueBuffer )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at TrackTv.Services.Data.EpisodeRepository.<GetEpisodesSummariesAsync>d__4.MoveNext() in C:\ncs\projects\SourceControl\TrackTV\src\TrackTv.Services\Data\EpisodeRepository.cs:line 26
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
    try
            {
                var s =  this.DbContext.Shows.Where(show => showIds.Contains(show.ShowId)).Select(show => new
                {
                    show.ShowId,
                    LastEpisodeId = show.Episodes.Where(e => e.FirstAired != null && e.FirstAired <= time).OrderByDescending(e => e.FirstAired)
                                        .Select(e => e.EpisodeId).FirstOrDefault(),
                    NextEpisodeId = show.Episodes.Where(e => e.FirstAired != null && e.FirstAired > time).OrderBy(e => e.FirstAired)
                                        .Select(e => e.EpisodeId).FirstOrDefault(),
                }).ToArray();

                Console.WriteLine();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }

```

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Enterprise
IDE: Visual Studio 2017

**Comment by KieranDevlinSycous** [comment]
My issue may be a sub set of this?
https://github.com/aspnet/EntityFrameworkCore/issues/10112

**Comment by smitpatel** [comment]
This is runtime error. We would need data which demonstrate this issue.

**Comment by maumar** [comment]
Was not able to reproduce this on current bits. 

Used the following repro code:

```cs
    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

                var e11 = new Episode { FirstAired = new DateTime(2000, 1, 1) };
                var e12 = new Episode { FirstAired = new DateTime(2000, 1, 7) };
                var e13 = new Episode { FirstAired = new DateTime(2000, 1, 14) };

                var e21 = new Episode { FirstAired = new DateTime(2010, 2, 4) };

                var s1 = new Show { Episodes = new List<Episode> { e11, e12, e13 } };
                var s2 = new Show { Episodes = new List<Episode> { e21 } };

                ctx.Episodes.AddRange(e11, e12, e13, e21);
                ctx.Shows.AddRange(s1, s2);
                ctx.SaveChanges();
            }

            using (var ctx = new MyContext())
            {
                var showIds = new List<int> { 1, };
                var time = new DateTime(2000, 1, 10);

                var query = ctx.Shows.Where(show => showIds.Contains(show.ShowId)).Select(show => new
                {
                    show.ShowId,
                    LastEpisodeId = show.Episodes.Where(e => e.FirstAired != null && e.FirstAired <= time).OrderByDescending(e => e.FirstAired)
                                                       .Select(e => e.EpisodeId).FirstOrDefault(),
                    NextEpisodeId = show.Episodes.Where(e => e.FirstAired != null && e.FirstAired > time).OrderBy(e => e.FirstAired)
                                                       .Select(e => e.EpisodeId).FirstOrDefault(),
                }).ToArray();


            }
        }
    }

    public class Show
    {
        public int ShowId { get; set; }
        public List<Episode> Episodes { get; set; }
    }

    public class Episode
    {
        public int EpisodeId { get; set; }
        public DateTime FirstAired { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<Show> Shows { get; set; }
        public DbSet<Episode> Episodes { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=.;Database=Repro10128;Trusted_Connection=True;MultipleActiveResultSets=True");
        }
    }
```

and got the following SQL generated:

```sql
SELECT [show].[ShowId], (
    SELECT TOP(1) [e].[EpisodeId]
    FROM [Episodes] AS [e]
    WHERE ([e].[FirstAired] IS NOT NULL AND ([e].[FirstAired] <= @__time_1)) AND ([show].[ShowId] = [e].[ShowId])
    ORDER BY [e].[FirstAired] DESC
) AS [LastEpisodeId], (
    SELECT TOP(1) [e0].[EpisodeId]
    FROM [Episodes] AS [e0]
    WHERE ([e0].[FirstAired] IS NOT NULL AND ([e0].[FirstAired] > @__time_2)) AND ([show].[ShowId] = [e0].[ShowId])
    ORDER BY [e0].[FirstAired]
) AS [NextEpisodeId]
FROM [Shows] AS [show]
WHERE [show].[ShowId] IN (1)
```

Note that the query is written in a way that, if there is no NextEpisode or LastEpisode, materialized value will be null and the compiler is expecting int, so the query will throw. This can be remedied by introducing cast to nullable value, just in case
