### ISSUE TITLE
Nested many-to-many relationships rise Tracking Exception?

### ISSUE THREAD

**Issue by scavarda** [dotnet/efcore#10129]
I searched around for this issue, but I didn't find anything.. I hope this is not a duplicate.
After a long debug I've simplified my Context to reproduce the issue with the smallest entities.
In NetCore 1.1 I didn't have any problem, but migrating to NetCore 2.0.0 something went wrong and I got all broken.
I have 2 many-to-many relationships nested with a one-to-many relationship in the middle.
If I create a single multi-level object with all the nested objects and add it to the context, when I call SaveChanges I see the following exception:

```
System.InvalidOperationException: The instance of entity type 'NetworkAddress' cannot be tracked because another instance with the key value 'NetworkAddressId:1' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.UpdateIdentityMap(InternalEntityEntry entry, IKey key)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IReadOnlyList`1 containingPrincipalKeys, IReadOnlyList`1 containingForeignKeys, Object oldValue, Object newValue)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IReadOnlyList`1 keys, IReadOnlyList`1 foreignKeys, Object oldValue, Object newValue)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectKeyChange(InternalEntityEntry entry, IProperty property)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.PropertyChanged(InternalEntityEntry entry, IPropertyBase propertyBase, Boolean setModified)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.PropertyChanged(InternalEntityEntry entry, IPropertyBase property, Boolean setModified)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean setModified)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.set_Item(IPropertyBase propertyBase, Object value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetCurrentValue(IPropertyBase propertyBase, Object value)
   at Microsoft.EntityFrameworkCore.Update.ColumnModification.set_Value(Object value)
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.PropagateResults(ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithPropagation(Int32 commandIndex, RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
```

### Steps to reproduce

My Context
```c#
namespace CrashTrackingContext
{
    public class CrashTrackingContext : DbContext
    {
        public CrashTrackingContext(DbContextOptions<CrashTrackingContext> options) : base(options)
        { }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<HostCluster>()
                .HasKey(hc => new { hc.HostId, hc.ClusterId })
            ;
            modelBuilder.Entity<HostCluster>()
                .HasOne(hc => hc.Host)
                .WithMany(h => h.Clusters)
                .HasForeignKey(hc => hc.HostId)
            ;
            modelBuilder.Entity<HostCluster>()
                .HasOne(hc => hc.Cluster)
                .WithMany(c => c.Hosts)
                .HasForeignKey(hc => hc.ClusterId)
            ;
            
            modelBuilder.Entity<NetworkAddressNetworkAddressRole>()
                .HasKey(nanar => new { nanar.NetworkAddressId, nanar.NetworkAddressRoleId })
            ;
            modelBuilder.Entity<NetworkAddressNetworkAddressRole>()
                .HasOne(nanar => nanar.NetworkAddress)
                .WithMany(na => na.NetworkAddressRoles)
                .HasForeignKey(nanar => nanar.NetworkAddressId)
            ;
            modelBuilder.Entity<NetworkAddressNetworkAddressRole>()
                .HasOne(nanar => nanar.NetworkAddressRole)
                .WithMany(nar => nar.NetworkAddresses)
                .HasForeignKey(nanar => nanar.NetworkAddressRoleId)
            ;
        }

        public DbSet<Cluster> Clusters { get; set; }
        public DbSet<Host> Hosts { get; set; }
        public DbSet<NetworkAddressRole> NetworkAddressRoles { get; set; }
    }

    public class Cluster
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ClusterId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public List<HostCluster> Hosts { get; set; } = new List<HostCluster> { };
    }

    public class Host
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int HostId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public List<HostCluster> Clusters { get; set; } = new List<HostCluster> { };
        public List<NetworkAddress> NetworkAddresses { get; set; } = new List<NetworkAddress> { };
    }

    public class HostCluster
    {
        public int HostId { get; set; }
        public Host Host { get; set; }
        public int ClusterId { get; set; }
        public Cluster Cluster { get; set; }
    }

    public class NetworkAddress
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int NetworkAddressId { get; set; }
        public Host Host { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public List<NetworkAddressNetworkAddressRole> NetworkAddressRoles { get; set; } = new List<NetworkAddressNetworkAddressRole> { };
    }

    public class NetworkAddressNetworkAddressRole
    {
        public int NetworkAddressId { get; set; }
        public NetworkAddress NetworkAddress { get; set; }
        public short NetworkAddressRoleId { get; set; }
        public NetworkAddressRole NetworkAddressRole { get; set; }
    }

    public class NetworkAddressRole
    {
        public const short Distribution = 1;
        public const short Contribution = 2;

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public short NetworkAddressRoleId { get; set; }

        public string Name { get; set; }
        public string Description { get; set; }
        public List<NetworkAddressNetworkAddressRole> NetworkAddresses { get; set; } = new List<NetworkAddressNetworkAddressRole> { };
    }
}
```

Here the calling Program.cs
```c#
var crashTrackingContext = new CrashTrackingContext.CrashTrackingContext(optionsBuilder.Options);
crashTrackingContext.Database.EnsureDeleted();
crashTrackingContext.Database.EnsureCreated();
crashTrackingContext.NetworkAddressRoles.AddRange(new NetworkAddressRole[]
{
    new NetworkAddressRole
    {
        NetworkAddressRoleId = NetworkAddressRole.Distribution,
    },
    new NetworkAddressRole
    {
        NetworkAddressRoleId = NetworkAddressRole.Contribution,
    },
});

var cluster = new Cluster
{
    Hosts = new List<HostCluster>
    {
        new HostCluster
        {
            Host = new Host
            {
                NetworkAddresses = new List<NetworkAddress>
                {
                    new NetworkAddress
                    {
                        NetworkAddressRoles = new List<NetworkAddressNetworkAddressRole>
                        {
                            new NetworkAddressNetworkAddressRole
                            {
                                NetworkAddressRoleId = NetworkAddressRole.Contribution,
                            },
                            new NetworkAddressNetworkAddressRole
                            {
                                NetworkAddressRoleId = NetworkAddressRole.Distribution,
                            },
                        },
                    },
                },
            },
        },
        new HostCluster
        {
            Host = new Host
            {
                NetworkAddresses = new List<NetworkAddress>
                {
                    new NetworkAddress
                    {
                        NetworkAddressRoles = new List<NetworkAddressNetworkAddressRole>
                        {
                            new NetworkAddressNetworkAddressRole
                            {
                                NetworkAddressRoleId = NetworkAddressRole.Contribution,
                            },
                            new NetworkAddressNetworkAddressRole
                            {
                                NetworkAddressRoleId = NetworkAddressRole.Distribution,
                            },
                        },
                    },
                },
            },
        },
    },
};

crashTrackingContext.Clusters.Add(cluster);
crashTrackingContext.SaveChanges();
```

The only way to make it works is to truncate the single object and make 2 different calls to SaveChanges. I think this is not a good practice and pattern to apply, the code is not so readable.

```c#
var cluster = new Cluster
{
    Hosts = new List<HostCluster>
    {
        new HostCluster
        {
            Host = new Host { },
        },
        new HostCluster
        {
            Host = new Host { },
        },
    },
};

crashTrackingContext.Clusters.Add(cluster);
crashTrackingContext.SaveChanges();

cluster.Hosts[0].Host.NetworkAddresses = new List<NetworkAddress>
{
    new NetworkAddress
    {
        NetworkAddressRoles = new List<NetworkAddressNetworkAddressRole>
        {
            new NetworkAddressNetworkAddressRole
            {
                NetworkAddressRoleId = NetworkAddressRole.Contribution,
            },
            new NetworkAddressNetworkAddressRole
            {
                NetworkAddressRoleId = NetworkAddressRole.Distribution,
            },
        },
    },
};
cluster.Hosts[1].Host.NetworkAddresses = new List<NetworkAddress>
{
    new NetworkAddress
    {
        NetworkAddressRoles = new List<NetworkAddressNetworkAddressRole>
        {
            new NetworkAddressNetworkAddressRole
            {
                NetworkAddressRoleId = NetworkAddressRole.Contribution,
            },
            new NetworkAddressNetworkAddressRole
            {
                NetworkAddressRoleId = NetworkAddressRole.Distribution,
            },
        },
    },
};
crashTrackingContext.SaveChanges();
```

### Further technical details
EF Core version: 2.0.0
Database Provider: Pomelo.EntityFrameworkCore.MySql 2.0.0
Operating system: Windows 10 64bit
IDE: (e.g. Visual Studio 2017)

**Comment by ajcvickers** [comment]
@scavarda This doesn't repro for me with SQL Server, so it looks like it could be an issue with the MySql provider. I would suggest filing an issue at https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql

**Comment by scavarda** [comment]
@ajcvickers Thanks I confirm that, with SQL Server it's all ok.

**Comment by scavarda** [comment]
I updated Pomelo package with the latest nightly build and it resolves. It's a recent patch. 
Pomelo.EntityFrameworkCore.MySql  2.0.1-preview-10070

Related issue
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/412
