### ISSUE TITLE
Connections from the pool are not reused when using async methods in parallel

### ISSUE THREAD

**Issue by wertzui** [dotnet/efcore#10169]
Whem I'm using async methods (like `FirstOrDefaultAsync`) to get a result from the Database inside a `Parallel.For`, the connections are not correctly reused from the connection pool.

The connections will rise to the configured `Max Pool Size` and after some time (around 1-2 minutes on my machine using localdb), exceptions will be thrown.

Using either async methods and a normal for-loop or non-async methods an a Parallel.For-loop, the connections are properly reused and I can observe that a normal for-loop uses 1 connection and a Parallel.For-loop uses 4 connections which corresponds to MaxDegreeOfParallelism.

```
Exception message:
System.InvalidOperationException occurred
  HResult=0x80131509
  Message=Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
Stack trace:
   at System.Data.Common.ADP.ExceptionWithStackTrace(Exception e)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenAsync>d__31.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<BufferlessMoveNext>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<ExecuteImplementationAsync>d__33`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<ExecuteImplementationAsync>d__33`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<MoveNext>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.<MoveNext>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.<_FirstOrDefault>d__82`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.<MoveNext>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at EfPoolingTest.UnitTest1.<>c.<NormalContextParallel>b__4_0(Int32 i) in C:\Users\xxx\documents\visual studio 2017\Projects\EfPoolingTest\EfPoolingTest\UnitTest1.cs:line 70
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
```

### Steps to reproduce
- Clone https://github.com/wertzui/EfPoolingTest and open the project
- Run the "ViewConnections.sql" script to see that there are no connections open (beside the 2 used for the script)
- Run the test "NormalContextParallelAsyncConfigureAwaitFalse" (I suggest running in Debug mode, so you can see the output)
- Run the "ViewConnections.sql" script multiple times to see the connections increase.
- After some time you will also get an exception
- Run the other tests and observe the connection count

### Further technical details
EF Core version: 2.0.0 (also tested with 1.1.3)
Database Provider: Microsoft.EntityFrameworkCore.SqlServer/localdb
Operating system: Windows 10 FCU
IDE: Visual Studio 2017 15.4.1

**Comment by wertzui** [comment]
I think, this is the same as #6357 but with repro code.

**Comment by ralmsdeveloper** [comment]
Hello @wertzui ,
By default SQL comes with the Maximum Connection Pool that is 100, which is occurring is Pool overflow, you can resolve this by disabling the Pool or Increasing to a greater Value.

using Microsoft.EntityFrameworkCore;
using System.Data.SqlClient;

```csharp
namespace EfCoreLongStringTest
{
    public class MyContext : DbContext
    {
        public DbSet<MyTable> MyTable { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                var conn = new SqlConnectionStringBuilder("Server=(localdb)\\mssqllocaldb;Initial Catalog=EfCorePoolingTest;Integrated Security=true;")
                {
                    ConnectRetryCount = 5, 
                    Pooling=false
                };
                optionsBuilder.UseSqlServer(conn.ToString(),
                    options => options.EnableRetryOnFailure());
            }
            base.OnConfiguring(optionsBuilder);
        }
    }
}
```
or

using Microsoft.EntityFrameworkCore;
using System.Data.SqlClient;

```csharp
namespace EfCoreLongStringTest
{
    public class MyContext : DbContext
    {
        public DbSet<MyTable> MyTable { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                var conn = new SqlConnectionStringBuilder("Server=(localdb)\\mssqllocaldb;Initial Catalog=EfCorePoolingTest;Integrated Security=true;")
                {
                    ConnectRetryCount = 5,
                    ConnectRetryInterval = 2,
                    MaxPoolSize = 600,
                    MinPoolSize = 5
                };
                optionsBuilder.UseSqlServer(conn.ToString(),
                    options => options.EnableRetryOnFailure());
            }
            base.OnConfiguring(optionsBuilder);
        }
    }
}
```

**That's just a small example!**

**Comment by wertzui** [comment]
Hi @ralmsdeveloper The problem is, that these 100 connections from the pool are sleeping according to the Database and not actively used.

And then there is still the question why this only when using async and parallel queries, not when using either one of them.

**Comment by ralmsdeveloper** [comment]
I understand, as I said, it was just a suggestion to solve this case.

More in fact what is happening is that internally it is not closing the connection.

If we use the example below we will realize that everything will go well!


 ```csharp
[TestMethod]
public void NormalContextParallelAsyncConfigureAwaitFalse()
{
    // Connection count max = 100 - MaxPoolSize
    // Throws System.InvalidOperationException Timeout expired.
    Parallel.For(1, count + 1, i =>
    {
        using (var context = new MyContext())
        {
            var myTable = context.Set<MyTable>().FirstOrDefaultAsync(m => m.Id == i).ConfigureAwait(false).GetAwaiter().GetResult();
            Debug.WriteLine("NormalContextParallelAsyncConfigureAwaitFalse " + myTable.MyColumn);
            context.Database.CloseConnection();
        }
    });
}
```

**Comment by wertzui** [comment]
I tried your example and the behavior does not change (100 connections and exception after some time). Afaik calling `context.Database.CloseConnection()` does not really close the connection, but returns it to the pool.

**Comment by ralmsdeveloper** [comment]
I'm not sure if EF really would have to discard these connections if there are still requests.

I think @ajcvickers  can help us.

**Comment by ralmsdeveloper** [comment]
Hello @wertzui,
Seeing better, I made this little change in the Context and it was more satisfying, until it reaches 100, but then reduce!

```csharp
using Microsoft.EntityFrameworkCore;
using System.Data.SqlClient;

namespace EfCoreLongStringTest
{
    public class MyContext : DbContext
    {
        public DbSet<MyTable> MyTable { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("Server=(localdb)\\mssqllocaldb;Initial Catalog=EfCorePoolingTest;Integrated Security=true;",
                    options => options.EnableRetryOnFailure());
            }
            base.OnConfiguring(optionsBuilder);
        }

        public override void Dispose()
        {
            SqlConnection.ClearPool((SqlConnection)Database.GetDbConnection());  
            base.Dispose(); 
        }
    }
}
```

If you can take a look at this it would be good, because the EF team would have a better direction!

**Comment by wertzui** [comment]
This will get rid of the Exception, but effectively disable connection pooling and therefor cripple the performance.
I did some tests on my machine and these are the requests per second that i came up with for the different methods:

Test | without ClearPool | with ClearPool
---- | ------------------- | ----------------
NormalContext | 257/s | 44/s
NormalContextAsync | 279/s | 26/s
NormalContextParallelAsyncConfigureAwaitFalse | 61/s | 43/s
NormalContextParallel | 289/s | 125/s

**Comment by ralmsdeveloper** [comment]
I understand, in tests I used ClearAllPools to mark the connections to be discarded and it was faster, what I am thinking is that this can not be something in EF Core, but in Sysmte.Data.SqlClient.

**Comment by ajcvickers** [comment]
@wertzui I ran your code and verified that EF is closing the connections correctly. Therefore, it looks like if there is an issue, then it is with the underlying ADO.NET code in SQLClient. I will move this issue to the appropriate repo.
