### ISSUE TITLE
If an entity is part of a hierarchy then I am unable to remove it by its PK only

### ISSUE THREAD

**Issue by silarmani** [dotnet/efcore#10182]
I am trying to remove all items of a hierarchy by deleting all base items by their PK however however when I try to remove any other entity which has a FK pointing to a derived type then I get an internal casting exception.

My sample entities

```c#
    public class Actor
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }

    public class User : Actor
    {
        public UserDetails Details { get; set; }
    }

    public class Group : Actor
    {
    }

    public class UserDetails
    {
        public int ActorId { get; set; }

        public User Actor { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Email { get; set; }
    }
```

The deletion

```c#
            var ctx = new MyDbContext();

            var toBeDeleted = ctx
                .Actors
                .AsNoTracking()
                .Select(e => new Actor
                {
                    Id = e.Id
                })
                .ToList();

            ctx.Actors.RemoveRange(toBeDeleted);

            var toBeDeletedDetails = ctx
                .UserDetails
                .AsNoTracking()
                .Select(e => new UserDetails
                {
                    ActorId = e.ActorId
                })
                .ToList();

            ctx.UserDetails.RemoveRange(toBeDeletedDetails);

            ctx.SaveChanges();
```

The exception

```
Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'EfTests3.Actor' to type 'EfTests3.User'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrPropertySetter`2.SetClrValue(Object instance, Object value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.WritePropertyValue(IPropertyBase propertyBase, Object value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean setModified)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.set_Item(IPropertyBase propertyBase, Object value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.SetNavigation(InternalEntityEntry entry, INavigation navigation, Object value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.InitialFixup(InternalEntityEntry entry, ISet`1 handledForeignKeys, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.StateChanged(InternalEntityEntry entry, EntityState oldState, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.StateChanged(InternalEntityEntry entry, EntityState oldState, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState entityState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.RemoveRange(IEnumerable`1 entities)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.RemoveRange(IEnumerable`1 entities)
   at EfTests3.Program.Main1(String[] args) in D:\code\tuxedo\Tests\EfBugTest3.cs:line 41
   at EfTests3.Program.Main(String[] args) in D:\code\tuxedo\Tests\EfBugTest3.cs:line 10
```

Workaround 1 is to swap the deletion around then it works however this is just small piece of a big puzzle involving maps, reflection, dynamics and etc so the order cannot be guaranteed for every base class and derived class

```c#
            var ctx = new MyDbContext();

            // entites depending upon a derived class first
            var toBeDeletedDetails = ctx
                .UserDetails
                .AsNoTracking()
                .Select(e => new UserDetails
                {
                    ActorId = e.ActorId
                })
                .ToList();

            ctx.UserDetails.RemoveRange(toBeDeletedDetails);

            // base entity
            var toBeDeleted = ctx
                .Actors
                .AsNoTracking()
                .Select(e => new Actor
                {
                    Id = e.Id
                })
                .ToList();

            ctx.Actors.RemoveRange(toBeDeleted);
```

Workaround 2 is to cast everything into derived entities first however some scenarios contains lots of derived entities so it is just a workaround if there isn't a fix

```
            var ctx = new MyDbContext();

            var toBeDeleted = ctx
                .Users
                .AsNoTracking()
                .Select(e => new User { Id = e.Id })
                .Cast<Actor>()
                .Union(ctx
                    .Groups
                    .AsNoTracking()
                    .Select(e => new Group { Id = e.Id })
                )
                .ToList();

            ctx.Actors.RemoveRange(toBeDeleted);

            var toBeDeletedDetails = ctx
                .UserDetails
                .AsNoTracking()
                .Select(e => new UserDetails
                {
                    ActorId = e.ActorId
                })
                .ToList();

            ctx.UserDetails.RemoveRange(toBeDeletedDetails);

            ctx.SaveChanges();
```

Full code

```c#
namespace EfTests3
{
    class Program
    {
        static int Main(string[] args)
        {
            //Main1(args);
            Main2(args);
            //Main3(args);

            return 0;
        }

        // This one breaks
        static int Main1(string[] args)
        {
            var ctx = new MyDbContext();

            var toBeDeleted = ctx
                .Actors
                .AsNoTracking()
                .Select(e => new Actor
                {
                    Id = e.Id
                })
                .ToList();

            ctx.Actors.RemoveRange(toBeDeleted);

            var toBeDeletedDetails = ctx
                .UserDetails
                .AsNoTracking()
                .Select(e => new UserDetails
                {
                    ActorId = e.ActorId
                })
                .ToList();

            ctx.UserDetails.RemoveRange(toBeDeletedDetails);

            ctx.SaveChanges();

            return 0;
        }

        // Swapping the deletion around works
        static int Main2(string[] args)
        {
            var ctx = new MyDbContext();

            // entites depending upon a derived class first
            var toBeDeletedDetails = ctx
                .UserDetails
                .AsNoTracking()
                .Select(e => new UserDetails
                {
                    ActorId = e.ActorId
                })
                .ToList();

            ctx.UserDetails.RemoveRange(toBeDeletedDetails);

            // base entity
            var toBeDeleted = ctx
                .Actors
                .AsNoTracking()
                .Select(e => new Actor
                {
                    Id = e.Id
                })
                .ToList();

            ctx.Actors.RemoveRange(toBeDeleted);

            ctx.SaveChanges();

            return 0;
        }

        // Forcing casting also works
        static int Main3(string[] args)
        {
            var ctx = new MyDbContext();

            var toBeDeleted = ctx
                .Users
                .AsNoTracking()
                .Select(e => new User { Id = e.Id })
                .Cast<Actor>()
                .Union(ctx
                    .Groups
                    .AsNoTracking()
                    .Select(e => new Group { Id = e.Id })
                )
                .ToList();

            ctx.Actors.RemoveRange(toBeDeleted);

            var toBeDeletedDetails = ctx
                .UserDetails
                .AsNoTracking()
                .Select(e => new UserDetails
                {
                    ActorId = e.ActorId
                })
                .ToList();

            ctx.UserDetails.RemoveRange(toBeDeletedDetails);

            ctx.SaveChanges();

            return 0;
        }
    }


    public class Actor
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }

    public class User : Actor
    {
        public UserDetails Details { get; set; }
    }

    public class Group : Actor
    {
    }

    public class UserDetails
    {
        public int ActorId { get; set; }

        public User Actor { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Email { get; set; }
    }

    public class MyDbContext : DbContext
    {
        public DbSet<Actor> Actors { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Group> Groups { get; set; }
        public DbSet<UserDetails> UserDetails { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=localhost,1433;Database=ipl_tux;Integrated Security=True;");            
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<UserDetails>()
                .HasKey(e => e.ActorId);

            base.OnModelCreating(modelBuilder);
        }
    }
}
```

To be sure to be sure, this issue isn't a duplicate of neither #10179 nor #10180 however they were all found during my attempt to dynamically purge an entire hierarchy of objects.

EF Core version: 2.0

**Comment by ajcvickers** [comment]
@silarmani Thanks for reporting this and also issues #10179 and #10180. There are some situations where EF currently uses more than just the key information for deletes. How much we want to allow stub entities like this to be used in these situations is something we will discuss as a team. Long term, these kinds of operations are probably best done with set-based operations, as tracked by #795. For now, one direction you could go is to use the FromSql method to write a set-based deletes manually.

**Comment by ajcvickers** [comment]
Notes from triage:
* Check that if the correct type of object is used, then the correct discriminator will be set, regardless of whether the entity is tracked with Add/Attach/Update/Remove
* Remove the need to have a discriminator value in TPH deletes so that the wrong type can be used

Note that for other mappings--such as TPT and TPC, when implemented--will need to be given the correct type, so in general attached a stub of the wrong type will not work.

**Comment by onzacoding** [comment]
HI all!
I've encountered with the same issue. The rare thing is that it happens only with one record in particular. There is no problem with the other 900.000  (in a production server).

Has this any workaround that I can use?

Thanks!

**Comment by ajcvickers** [comment]
@onzacoding Can you please open a new issue including a runnable project/code listing that reproduces what you are seeing?

**Comment by onzacoding** [comment]
@ajcvickers I will try, but I found what was going on.
At the scaffold, there was a unique index for some columns, but that was not present in the databse (the project is database first, someone must deleted the index). Removing the index from the scaffold solved the problem.

**Comment by silarmani** [comment]
Hi guys, just wondering why was this issue closed?

**Comment by AndriySvyryd** [comment]
@silarmani In general we don't want to encourage users to supply the wrong type as there might be more places that won't be able to handle it either now or in the future. Also we cannot make this work in all scenarios even now.
A more robust way of accomplishing this would be with Batch CUD https://github.com/aspnet/EntityFrameworkCore/issues/795
