### ISSUE TITLE
Query: OrderBy expression with select object and Includes throws exception

### ISSUE THREAD

**Issue by Tasteful** [dotnet/efcore#10192]
When dynamic create the expression for the query and using a subquery that selecting a column of any (`object`) type and usage of `.Include()` will throws exception.

If the `selectFieldExpression` in below code is returning `object` exception is thrown, if I change type to `string` the query is executed without problem.
```
using (var dbContext = scope.ServiceProvider.GetRequiredService<MyTestContext>())
{
    Expression<Func<MyTable2, object>> selectFieldExpression =
        x => x.Name;

    Expression<Func<MyTable1, object>> orderExpression =
        item => dbContext.MyTable2
                            .Where(x => x.Id == item.Id)
                            .Select(selectFieldExpression)
                            .FirstOrDefault();

    var items = dbContext.MyTable1
                            .Include(x => x.Table2)
                            .OrderBy(orderExpression)
                            .ToList();
}
```

Exception is only throw if the `.Include()` is included and does not need to be the table that is used in the subquery.
```
System.InvalidOperationException: Warning as error exception for warning 'Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning': The LINQ expression 'join AnonymousObject _x in {from MyTable1 x in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[MemoryUsage.MyTable1]) select new AnonymousObject(new [] {Convert(EF.Property(?[x]?, "Id"), Object), Convert({from MyTable2 x in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[MemoryUsage.MyTable2]) where ([x].Id == [x].Id) select [x].Name => FirstOrDefault()}, Object)})} on Property([x.Table2], "Id") equals Convert([_x].GetValue(0), Nullable`1)' could not be translated and will be evaluated locally. To suppress this Exception use the DbContextOptionsBuilder.ConfigureWarnings API. ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.
   at Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`1.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, TParam arg, Exception exception) in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore\Diagnostics\EventDefinition`.cs:line 71
   at Microsoft.EntityFrameworkCore.Internal.RelationalLoggerExtensions.QueryClientEvaluationWarning(IDiagnosticsLogger`1 diagnostics, QueryModel queryModel, Object queryModelElement) in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore.Relational\Internal\RelationalLoggerExtensions.cs:line 995
   at Remotion.Linq.Clauses.JoinClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel) in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore\Query\EntityQueryModelVisitor.cs:line 699
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel) in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore.Relational\Query\RelationalQueryModelVisitor.cs:line 268
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitSubQuery(SubQueryExpression expression) in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore.Relational\Query\ExpressionVisitors\RelationalEntityQueryableExpressionVisitor.cs:line 73
   at Remotion.Linq.Clauses.Expressions.SubQueryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.VisitLambda[T](Expression`1 node) in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore\Query\ExpressionVisitors\ExpressionVisitorBase.cs:line 58
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions(ExpressionVisitor visitor, BlockExpression block)
   at System.Linq.Expressions.ExpressionVisitor.VisitBlock(BlockExpression node)
   at System.Linq.Expressions.BlockExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.VisitLambda[T](Expression`1 node) in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore\Query\ExpressionVisitors\ExpressionVisitorBase.cs:line 58
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection) in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore\Query\EntityQueryModelVisitor.cs:line 1315
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel) in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore\Query\EntityQueryModelVisitor.cs:line 1031
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel) in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore.Relational\Query\RelationalQueryModelVisitor.cs:line 1053
   at Remotion.Linq.Clauses.SelectClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel) in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore\Query\EntityQueryModelVisitor.cs:line 699
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel) in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore.Relational\Query\RelationalQueryModelVisitor.cs:line 268
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel) in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore\Query\EntityQueryModelVisitor.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType) in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs:line 166
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_0`1.<Execute>b__0() in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs:line 103
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler) in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore\Query\Internal\CompiledQueryCache.cs:line 69
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MemoryUsage.Program.Execute() in C:\Git\bugs\MemoryUsage\Program.cs:line 99
   at MemoryUsage.Program.Main(String[] args) in C:\Git\bugs\MemoryUsage\Program.cs:line 23
```

When turning ignoring query client evaluation the following exception is thrown
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , AnonymousObject )
   at System.Linq.Lookup`2.CreateForJoin(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.<JoinIterator>d__81`4.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__3.MoveNext()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.IncludeCollection(Int32 includeId, INavigation navigation, INavigation inverseNavigation, IEntityType targetEntityType, IClrCollectionAccessor clrCollectionAccessor, IClrPropertySetter inverseClrPropertySetter, Boolean tracking, Object entity, Func`1 relatedEntitiesFactory) in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore\Query\Internal\QueryBuffer.cs:line 173
   at lambda_method(Closure , QueryContext , MyTable1 , Object[] )
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler._Include[TEntity](QueryContext queryContext, TEntity entity, Object[] included, Action`3 fixup) in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore\Query\Internal\IncludeCompiler.cs:line 257
   at lambda_method(Closure , MyTable1 )
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext() in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore\Query\Internal\LinqOperatorProvider.cs:line 173
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext() in C:\b\w\5ab5bfc195c9b71\modules\EntityFrameworkCore\src\EFCore\Query\Internal\LinqOperatorProvider.cs:line 137
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MemoryUsage.Program.Execute() in C:\Git\bugs\MemoryUsage\Program.cs:line 99
   at MemoryUsage.Program.Main(String[] args) in C:\Git\bugs\MemoryUsage\Program.cs:line 23
```

### Steps to reproduce
Code for reproduce the exception is found here https://github.com/Tasteful/bugs/blob/sortby-expression2

### Further technical details
EF Core version: 2.0.1-rtm-207 (also tested with 2.0.0, was working in 1.1.2)
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 10
IDE: Visual Studio 2017 (15.4.1)

**Comment by ajcvickers** [comment]
@Tasteful We had a long discussion about this in triage. The outcome was that, in general, when building expression trees directly they must match what the compiler would generate. This isn't so say that we don't support expression trees generated in other ways, but rather that we're not going to attempt to support any possible expression tree if it can be written in a different way that works. So based on this we're not going to try to fix the issue here.

All that being said, if this turns out to be something that can occur with compiler-generated expressions, or as part of some other EF construct such as EF.Property typed as object, then the priority of this would be higher--but we would want to see that scenario so we can access the impact.

So from our side we are closing this as won't fix for now, but we could well revise that with more information. Also, we would also likely consider a PR to fix this if someone from the community wanted to dig into it.

**Comment by Tasteful** [comment]
As a workaround I created an expression visitor that was rewriting the orderby-expression and got the dynamic queries ordered by queries to work.

Is the pattern in the `ObjectTypeFromSelectExpressionVisitor` a good way to solve this?
If I should make a PR for this, should I try to incorporate that in the expression visitor that transform the existing `OrderBy`-expression or should this live outside as an overload on the `OrderBy` that take the expression in as workaround?

```c#
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;

namespace ExpressionVisitors
{
    internal static class ObjectTypeFromSelectExpressionVisitor
    {
        public static LambdaExpression Visit(LambdaExpression expression)
        {
            return (LambdaExpression)new Visitor().Visit(expression);
        }

        private class Visitor : ExpressionVisitor
        {
            private Type _fieldType = typeof(object);

            protected override Expression VisitLambda<T>(Expression<T> node)
            {
                if (node?.ReturnType == typeof(object))
                {
                    var body = Visit(node.Body);
                    var returnType = typeof(Func<,>).MakeGenericType(node.Parameters[0].Type, _fieldType);
                    return Expression.Lambda(returnType, body, node.TailCall, node.Parameters);
                }
                return base.VisitLambda(node);
            }

            protected override Expression VisitMember(MemberExpression node)
            {
                var value = Evaluate(node);
                if (value is LambdaExpression lambdaExpression)
                {
                    _fieldType = lambdaExpression.Body.Type;
                    var returnType = typeof(Func<,>).MakeGenericType(lambdaExpression.Parameters[0].Type, _fieldType);
                    return Expression.Lambda(returnType, lambdaExpression.Body, lambdaExpression.Parameters[0]);
                }

                return base.VisitMember(node);
            }

            protected override Expression VisitMethodCall(MethodCallExpression node)
            {
                if (node.Type == typeof(object) || node.Type == typeof(IQueryable<object>))
                {
                    var args = node.Arguments.Select(x => Visit(x)).ToArray();
                    var methodInfo = node.Method
                        .GetGenericMethodDefinition()
                        .MakeGenericMethod(node.Method.GetGenericArguments()
                            .Select(x => x == typeof(object) ? _fieldType : x)
                            .ToArray());
                    return Expression.Call(node.Object, methodInfo, args);
                }

                return base.VisitMethodCall(node);
            }

            private object Evaluate(Expression expression)
            {
                if (expression == null)
                {
                    return null;
                }

                // ReSharper disable once SwitchStatementMissingSomeCases
                switch (expression.NodeType)
                {
                    case ExpressionType.MemberAccess:
                        {
                            var memberExpression = (MemberExpression)expression;
                            var @object = Evaluate(memberExpression.Expression);

                            if (memberExpression.Member is FieldInfo fieldInfo)
                            {
                                try
                                {
                                    return fieldInfo.GetValue(@object);
                                }
                                catch
                                {
                                    // Try again when we compile the delegate
                                }
                            }

                            if (memberExpression.Member is PropertyInfo propertyInfo)
                            {
                                try
                                {
                                    return propertyInfo.GetValue(@object);
                                }
                                catch
                                {
                                    // Try again when we compile the delegate
                                }
                            }

                            break;
                        }
                    case ExpressionType.Constant:
                        {
                            return ((ConstantExpression)expression).Value;
                        }
                }

                return null;
            }
        }
    }
}
```

and also an `OrderBy`/`OrderByDescending` extension that was taking an expression instead of the `Expression<Func<TSource, TResult>>`.
```c#
using System;
using System.Collections.Concurrent;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;

namespace ExpressionVisitors
{
    public static class ExpressionExtensions
    {
        private static readonly ConcurrentDictionary<Type, MethodInfo> _orderBy = new ConcurrentDictionary<Type, MethodInfo>();
        private static readonly ConcurrentDictionary<Type, MethodInfo> _orderByDescending = new ConcurrentDictionary<Type, MethodInfo>();

        public static IOrderedQueryable<TSource> OrderBy<TSource>(this IQueryable<TSource> source, LambdaExpression selector)
        {
            var selectMethodInfo = _orderBy.GetOrAdd(typeof(TSource), _ =>
                    new Func<IQueryable<TSource>, Expression<Func<TSource, object>>, IOrderedQueryable<TSource>>(System.Linq.Queryable.OrderBy)
                    .Method
                    .GetGenericMethodDefinition())
                .MakeGenericMethod(typeof(TSource), selector.ReturnType);

            return (IOrderedQueryable<TSource>)selectMethodInfo.Invoke(null, new object[] { source, selector });
        }

        public static IOrderedQueryable<TSource> OrderByDescending<TSource>(this IQueryable<TSource> source, LambdaExpression selector)
        {
            var selectMethodInfo = _orderByDescending.GetOrAdd(typeof(TSource), _ =>
                    new Func<IQueryable<TSource>, Expression<Func<TSource, object>>, IOrderedQueryable<TSource>>(System.Linq.Queryable.OrderByDescending)
                    .Method
                    .GetGenericMethodDefinition())
                .MakeGenericMethod(typeof(TSource), selector.ReturnType);

            return (IOrderedQueryable<TSource>)selectMethodInfo.Invoke(null, new object[] { source, selector });
        }
    }
}
```

Can probably rewrite the `ExpressionExtensions` methods to take the `Expression<Func<TSource, object>>` as parameter instead of `LambdaExpression` and inside that run the expression visitor to rewrite the query.

**Comment by ajcvickers** [comment]
@anpete @smitpatel @maumar Could one of you take a look at the above ideas on how to fix this in a PR?
