### ISSUE TITLE
HasColumnType with not null statement

### ISSUE THREAD

**Issue by mneundorfer** [dotnet/efcore#10314]
With EF Core 1.x, we used a statement like this to constraint a specific DB column on the ModelBuilder:

`HasColumnType("nvarchar(32) collate SQL_Latin1_General_CP1_CS_AS not null")`

After upgrading to EF Core 2, this statement seems to create issues on applying the generated migrations:

```
Exception message: 
System.Data.SqlClient.SqlException : Multiple NULL constraints were specified for column 'XXX', table 'YYY'.
Stack trace:
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
```

The issue goes away when removing the `not null` statement from `HasColumnType()` call and adding it via the modelBuilders `IsRequired()` method.

### Steps to reproduce
Create a simple basic POCO and attach this kind of constraint via the model builder on a string property. Then generate migrations and try to apply them.

``` Model.cs
public class MyEntity {
  public string Name { get; set; }
}
```

``` MyDbContext.cs
public class MyDbContext : DbContext {
  protected override void OnModelCreating(ModelBuilder modelBuilder) {
    modelBuilder.Entity<MyEntity>(builder => {
      builder.Property(e => e.Name).HasColumnType("nvarchar(32) collate SQL_Latin1_General_CP1_CS_AS not null");
    }
  }
}
```

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win10
IDE: Visual Studio 2017

**Comment by smitpatel** [comment]
Side-effect of https://github.com/aspnet/EntityFrameworkCore/issues/8146
Required behavior must be configured using `IsRequired` API otherwise EF Core will generate `NULL` after column name conflicting with column type specified

**Comment by ajcvickers** [comment]
@mneund The column type is intended to be _only_ the column type.  It should not also include constraints, such as "not null". Instead these should be configured using the `[Required]` attribute or by the `.IsRequired()` fluent API.
