### ISSUE TITLE
Unable to query with filter on an Owned Entity

### ISSUE THREAD

**Issue by fgheysels** [dotnet/efcore#10392]
I have a simple class with a property that is mapped as an owned entity.  
The class that is used as an owned entity has IEquatable implemented and has some overloaded equality operators.

When I issue a LINQ statement with a Where clause that filters on that owned entity, the following exception is thrown:

```
Exception message: System.InvalidOperationException: 'The EF.Property<T> method may only be used within LINQ queries.'
Stack trace:
   at Microsoft.EntityFrameworkCore.EF.Property[TProperty](Object entity, String propertyName)
   at lambda_method(Closure , TransparentIdentifier`2 )
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```
Looking at the stacktrace, I can see that the linq query is evaluated on an IEnumerable, whereas I'd expect it to execute on an IQueryable.

### Steps to reproduce
The issue can be reproduced by executing the code below:

```c#
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using Xunit;

namespace OwnedObjectsQueryTest
{
    /// <summary>
    /// Entity class
    /// </summary>
    public class Foo
    {
        public int Id { get; private set; }

        public Bar FooBar { get; set; }
    }

    /// <summary>
    /// Bar represents the Entity that is mapped as an owned entity of Foo
    /// </summary>
    public class Bar : IEquatable<Bar>, IEquatable<string>
    {
        private Bar() { }

        public Bar(string value)
        {
            this.Value = value;
        }

        public string Value { get; private set; }

        public bool Equals(Bar other)
        {
            return this.Value == other.Value;
        }

        public bool Equals(string other)
        {
            return this.Value == other;
        }

        public static bool operator ==(Bar left, Bar right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Bar left, Bar right)
        {
            return !Equals(left, right);
        }

        public static bool operator ==(Bar left, string right)
        {
            return left.Equals(right);
        }

        public static bool operator !=(Bar left, string right)
        {
            return !left.Equals(right);
        }

        public override bool Equals(object obj)
        {
            if (obj is Bar b)
            {
                return Equals(this, b);
            }
            return false;
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    public class FooContext : DbContext
    {
        public DbSet<Foo> Foos { get; set; }

        public FooContext() : base(GetDbContextOptions())
        {
        }

        private static DbContextOptions<FooContext> GetDbContextOptions()
        {
            var optionsBuilder = new DbContextOptionsBuilder<FooContext>();

            optionsBuilder.UseSqlServer(@"Server=.;Database=FooBar;Trusted_Connection=True;");
            return optionsBuilder.Options;
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Foo>().Property(f => f.Id).UseSqlServerIdentityColumn();
            var fooBarBuilder = modelBuilder.Entity<Foo>().OwnsOne(f => f.FooBar);
            fooBarBuilder.Property(fb => fb.Value).HasColumnName("Value");
            fooBarBuilder.HasIndex(fb => fb.Value);
        }
    }

    public class TestCases
    {
        public TestCases()
        {
            using (var context = new FooContext())
            {
                context.Database.EnsureCreated();
            }
        }

        [Fact]
        public void CanStoreAndRetrieveFoo()
        {
            using (var context = new FooContext())
            {
                var f = new Foo();
                f.FooBar = new Bar("something");
                context.Foos.Add(f);
                context.SaveChanges();
            }

            using (var context = new FooContext())
            {
                var b = new Bar("something");

                var result = context.Foos.FirstOrDefault(f => f.FooBar == b);
                Assert.NotNull(result);
            }
        }
    }
}

```
### Using Equals(Bar b)

Note that when I change the query in the testcase to:

`var result = context.Foos.FirstOrDefault(f => f.FooBar.Equals(b));`

Then a SQL statement is generated without a WHERE clause:
```
SELECT [f].[Id], [f].[Id], [f].[Value]
FROM [Foos] AS [f]
```

So the filtering happens in memory, which is not what you want ...  (Also note that f.Id appears twice in the select list).

### Using FooBar.Value == Bar.Value
When I change the query in the testcase to:

`var result = context.Foos.FirstOrDefault(f => f.FooBar.Value == b.Value);`

then the following SQL statement is generated:
```
exec sp_executesql N'SELECT TOP(1) [f].[Id], [f].[Id], [f].[Value]
FROM [Foos] AS [f]
WHERE [f].[Value] = @__b_Value_0',N'@__b_Value_0 nvarchar(450)',@__b_Value_0=N'something'
```

(Which I expected, but since I've overloaded Equals and the equality operators, I'd figure that the queries above should also work)

### Using Bar.Equals( string s )

When I change the query in the testcase to - and this is very striking -:

`var result = context.Foos.FirstOrDefault( f => f.FooBar.Equals("something"));`

then, an ArgumentException is thrown saying that I cannot pass an `Int32` to the `Equals(string)` method:

```
Method 'Boolean Equals(System.String)' declared on type 'OwnedObjectsQueryTest.Bar' cannot be called with instance of type 'System.Int32''

   at System.Linq.Expressions.Expression.ValidateCallInstanceType(Type instanceType, MethodInfo method)
   at System.Linq.Expressions.Expression.ValidateStaticOrInstanceMethod(Expression instance, MethodInfo method)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitWhereClause(WhereClause whereClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.Clauses.WhereClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
```

### Further technical details
EF Core version: 2.0.1.0  
Database Provider: Microsoft.EntityFrameworkCore.SqlServer 2.0.1.0
Operating system: Windows 10
IDE: VS.NET 2017

**Comment by fgheysels** [comment]
I've been playing around with this issue a little bit further and added some extra findings in my original message.

**Comment by smitpatel** [comment]
Overridden `Equals`, `==`, `!=` are methods on the user class. We cannot look into its implementation because it is not an Expression. Hence we cannot translate it to server. Due to this limitation it causes in-memory evaluation which is also costly operation. Further if you do not have override `==` then equality of entities in query would be reference equality which will not give correct results. Hence query arrived at that, when you do entity equality then we will make it equality on PK properties so that we can translate it to server and avoid costly client evaluation. Since 2 entity instance with same PK would resolve to same instance in changetracker this matches up how rest of stack works. For `Equals` we have left it out so that user can actually use custom equality if they want to.

First exception happens because you have navigation being compared to a parameter which will be written on PK equality. Since PK is shadow, we use EF.Property on parameter which causes the exception. It should do client evaluation. It is a bug.

Second case, you are using Equals. Since we cannot translate it, we evaluate on client so you don't see it in SQL. But it will return correct results. Once first case is fixed, it would do similar to what this does.

Third case works because you explicitly specified property comparison and we translated it to server.

Fourth case, we did navigation expansion on `f.FooBar`. Seems like it caused some issue. This is also a bug. But if fixed it will do client evaluation.

**Comment by fgheysels** [comment]
First of all, thanks for your reply.

An owned entity is typically used to represent some kind of Value-Type, and value-types do not have a primary key, since they're not entities.    So equality on PK doesn't work in this case.
I thought that by overriding Equals EF would be able to generate a clause based on that routine, but right now EF is actually 'stealing my identity'.

Isn't there any way that I can define how EF should translate a certain equality operation to sql ?

**Comment by ajcvickers** [comment]
@fgheysels We discussed this in triage and it seems like most of this issue is about using value object semantics with EF Core, which is covered by #9906. However, some things like implicit conversion operators may still not be recognized by EF. For now, closing as dup of #9906 and we can re-assess after that issue is implemented.
