### ISSUE TITLE
System.ValueTuple not found (Only on Azure hosting)

### ISSUE THREAD

**Issue by syedabdulaala** [dotnet/efcore#10477]
I am using Ef Core with .Net Framework v4.7. Everything is working fine when i am using my Web Api on localhost but when i publish it on Azure App Service it throws below exception.
I even tried to add System.ValueType library through nuget package manager and manually but it always show 'The referenced component System.ValueTuple could not be found' in visual studio warning and is marked yellow in references.

Below is then exception i am getting only when my Web Api is hosted on azure.
```
Exception message: System.IO.FileNotFoundException: Could not load file or assembly
'System.ValueTuple, Version=0.0.0.0, Culture=neutral,
PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The
system cannot find the file specified.
Stack trace: Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.SharedTableConvention.Apply(InternalModelBuilder
modelBuilder)
   at
Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder
modelBuilder)
   at
Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelBuilt(InternalModelBuilder
modelBuilder)
   at
Microsoft.EntityFrameworkCore.Metadata.Internal.Model.Validate()

at
Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Validate()

at
Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext
context, IConventionSetBuilder conventionSetBuilder, IModelValidator
validator)
   at
Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__0(Object
k)
   at
System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey
key, Func`2 valueFactory)
   at
Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext
context, IConventionSetBuilder conventionSetBuilder, IModelValidator
validator)
   at
Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()

at
Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()

at
Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_1(IServiceProvider
p)
   at
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite
factoryCallSite, ServiceProvider provider)
   at
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite
callSite, TArgument argument)
   at
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite
scopedCallSite, ServiceProvider provider)
   at
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite
callSite, TArgument argument)
   at
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite
constructorCallSite, ServiceProvider provider)
   at
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite
callSite, TArgument argument)
   at
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite
scopedCallSite, ServiceProvider provider)
   at
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite
callSite, TArgument argument)
   at
Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider
provider)
   at
Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type
serviceType)
   at
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider
provider, Type serviceType)
   at
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider
provider)
   at
Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()

at
Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()

at
Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()

at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at
SmartShopping.Access.Context.Table[T]() in E:\\Studies\\Final Year
Project Source Code\\Web Api\\SmartShopping.Access\\Context.cs:line
19
   at SmartShopping.Core.Api.Mart.Base.GetSession(String
tokenHash, String userAgent) in E:\\Studies\\Final Year Project Source
Code\\Web Api\\SmartShopping.Core\\Api\\Mart\\Base.cs:line 0
   at
SmartShopping.Core.Api.Mart.Base..ctor(RequestParam param) in
E:\\Studies\\Final Year Project Source Code\\Web
Api\\SmartShopping.Core\\Api\\Mart\\Base.cs:line 30
   at
SmartShopping.Security.Api.MartContext.Get[T]() in E:\\Studies\\Final
Year Project Source Code\\Web
Api\\SmartShopping.Security\\Api\\MartContext.cs:line 25
   at
SmartShopping.WebAPI.Areas.Mart.Controllers.AccountController.<Login>d__0.MoveNext()
in E:\\Studies\\Final Year Project Source Code\\Web
Api\\SmartShopping.Api\\Areas\\Mart\\Controllers\\AccountController.cs:line
0
--- End of stack trace from previous location where exception was
thrown ---
   at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at
System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
---
End of stack trace from previous location where exception was thrown
---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at
System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
---
End of stack trace from previous location where exception was thrown
---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at
System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
---
End of stack trace from previous location where exception was thrown
---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at
System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
---
End of stack trace from previous location where exception was thrown
---
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
---
End of stack trace from previous location where exception was thrown
---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at
System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()

```

### Further technical details
EF Core version: 2.0.1
.NET Framework: 4.7
Nuget Package Manager version: 4.4.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
IDE: Visual Studio 2017 15.4.3
System.ValueTuple: 4.4.0
![capture-1](https://user-images.githubusercontent.com/16648261/33566139-e1167fbc-d940-11e7-9417-ded6af12e528.PNG)
![capture-2](https://user-images.githubusercontent.com/16648261/33566140-e1476f1e-d940-11e7-9239-25014a805b58.PNG)

**Comment by ajcvickers** [comment]
@syedabdulaala You will likely need to add a binding redirect as described here: https://github.com/dotnet/standard/issues/481. However, note that things change if you are using 4.7.1 as described here: https://blogs.msdn.microsoft.com/dotnet/2017/09/28/net-framework-4-7-1-runtime-and-compiler-features/
