### ISSUE TITLE
Failing connections after multiple requests

### ISSUE THREAD

**Issue by sebastianrosch** [dotnet/efcore#10494]
I have an ASP.NET Core Web application using EF Core 2.0. When performing a bunch of requests that retrieve data from the database, EF Core throws an error after approx. 100 requests. The database is an Azure SQL database and firewall settings are correct. Retrieving data works 80-90% of the times.

This issue has occurred on MacOS and Linux, we did not see it on Windows yet. It happens both on my development machine (Mac) as well as online (Linux). Since our production services are running in Docker, this creates a problem for us.

This is the stack trace of the error:

```
fail: Microsoft.EntityFrameworkCore.Database.Connection[20004]
      An error occurred using the connection to database 'databasename' on server 'azure-database'.
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
ClientConnectionId:00000000-0000-0000-0000-000000000000
```

After a couple of these exceptions, the application crashes with the following error:

```
dotnet(66933,0x700003cf5000) malloc: *** error for object 0x7fd47fac86d0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```

The queries that are being performed before the error occurs look like this:

```
Microsoft.EntityFrameworkCore.Database.Command:Information: Executed DbCommand (27ms) [Parameters=[@___teamId_0='XXX' , @__p_1='X', @__p_2='X'], CommandType='Text', CommandTimeout='30']
SELECT [e.ProjectMembers].[Id], [e.ProjectMembers].[CreatedBy], [e.ProjectMembers].[CreatedOn], [e.ProjectMembers].[DeletedBy], [e.ProjectMembers].[DeletedOn], [e.ProjectMembers].[IsResponsible], [e.ProjectMembers].[ProjectId], [e.ProjectMembers].[ProjectRoleId], [e.ProjectMembers].[TeamId], [e.ProjectMembers].[UpdatedBy], [e.ProjectMembers].[UpdatedOn], [e.ProjectMembers].[UserId]
FROM [projects].[ProjectMembers] AS [e.ProjectMembers]
INNER JOIN (
    SELECT DISTINCT [t1].*
    FROM (
        SELECT [e1].[Id]
        FROM [projects].[Projects] AS [e1]
        LEFT JOIN [projects].[ProjectTypes] AS [e.ProjectType1] ON [e1].[ProjectTypeId] = [e.ProjectType1].[Id]
        LEFT JOIN [projects].[ProjectTypes] AS [e.SalesType1] ON [e1].[SalesTypeId] = [e.SalesType1].[Id]
        LEFT JOIN [projects].[ProjectStatuses] AS [e.ProjectStatus1] ON [e1].[ProjectStatusId] = [e.ProjectStatus1].[Id]
        WHERE ([e1].[TeamId] = @___teamId_0) AND [e1].[DeletedOn] IS NULL
        ORDER BY [e1].[Id]
        OFFSET @__p_1 ROWS FETCH NEXT @__p_2 ROWS ONLY
    ) AS [t1]
) AS [t2] ON [e.ProjectMembers].[ProjectId] = [t2].[Id]
ORDER BY [t2].[Id]
```

### Steps to reproduce
We use the new Context Pooling like this:

```c#
services.AddDbContextPool<TDbContext>(
                options => options.UseSqlServer(connectionString,
                    sqlOptions =>
                    {
                        sqlOptions.EnableRetryOnFailure(maxRetryCount: 5,
                        maxRetryDelay: TimeSpan.FromSeconds(3),
                        errorNumbersToAdd: null);
                    })
                    .EnableSensitiveDataLogging()
                );
```

The connection string looks like this (everything else is default):

```
Data Source=azure-database;Initial Catalog=databasename;Integrated Security=False;User ID=XXX;Password=XXX
```

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer, Azure SQL
Operating system: MacOS
IDE: VS Code 1.18.1

**Comment by ajcvickers** [comment]
This looks like an issue with SQLClient (or below) so moved to https://github.com/dotnet/corefx/issues/25761
