### ISSUE TITLE
EFCore is adding an invalid column (in the database and model) in INSERT statement

### ISSUE THREAD

**Issue by aldvsmaximvs** [dotnet/efcore#10576]
I'm trying to insert a data and execute the command context.SaveChanges() but this throw an error of a invalid column (StoreId). This is actually true, that column is not existing in the table or in my model. But why is it generating INSERT statement with that column.

My database structure
```sql
SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = N'StockReceivingDetail'

TABLE_CATALOG TABLE_SCHEMA TABLE_NAME COLUMN_NAME
isrs-data	dbo	StockReceivingDetail	Id
isrs-data	dbo	StockReceivingDetail	ExpectedDate
isrs-data	dbo	StockReceivingDetail	ExpectedQty
isrs-data	dbo	StockReceivingDetail	FulfillQty
isrs-data	dbo	StockReceivingDetail	ItemId
isrs-data	dbo	StockReceivingDetail	ItemUOMId
isrs-data	dbo	StockReceivingDetail	ReceivedDate
isrs-data	dbo	StockReceivingDetail	RowVersion
isrs-data	dbo	StockReceivingDetail	SourceStoreId
isrs-data	dbo	StockReceivingDetail	Status
isrs-data	dbo	StockReceivingDetail	StockReceivingId
isrs-data	dbo	StockReceivingDetail	StockRequestFulfillmentScheduleId
isrs-data	dbo	StockReceivingDetail	VendorId
isrs-data	dbo	StockReceivingDetail	WarehouseId
```
My Model
```C#
    public class StockReceiving : IDocumentHeader
    {
        public int Id { get; set; }
        public string DocumentNo { get; set; }
        public DateTime DocumentDate { get; set; }

        public int StoreId { get; set; }
        public Store Store { get; set; }
        /*
          StockRequestId is nullable. This is due to the fact
          that a store can received an item even if there are no
          request for that stock

          Create a dropdown of StockRequest.Id, StockRequest.DocumentNo for the
          ReferenceId
         */
        public int? StockRequestId { get; set; }
        public StockRequest StockRequest { get; set; }

        public TransactionStatus Status { get; set; }

        public ICollection<StockReceivingDetail> Details{ get; set; }

    }
    public class StockReceivingDetail : IEntityBase
    {
        public int Id { get; set; }

        public int StockReceivingId{ get; set; }
        public StockReceiving StockReceiving { get; set; }

        public int? StockRequestFulfillmentScheduleId { get; set; }
        public StockRequestFulfillmentSchedule FulfillmentSchedule { get; set; }

        public int? WarehouseId { get; set; }
        public Warehouse Warehouse { get; set; }
        public int? SourceStoreId { get; set; }
        public Store Store { get; set; }
        public int? VendorId { get; set; }
        public Vendor Vendor { get; set; }

        public int ItemId { get; set; }
        public Item Item { get; set; }
        public int ItemUOMId { get; set; }
        public ItemUOM UOM { get; set; }

        public DateTime ExpectedDate { get; set; }
        public decimal ExpectedQty { get; set; }
        public DateTime ReceivedDate { get; set; }
        decimal _fulfillQty;
        public decimal FulfillQty {
            get {
                return _fulfillQty;
            }
            set
            {
                _fulfillQty = value;
                FulfillmentSchedule.FulfillQty = _fulfillQty;
            }
        }

        public TransactionStatus Status { get; set; }

        public decimal BalanceQty()
        {
            return (ExpectedQty > FulfillQty) ? ExpectedQty - FulfillQty : 0;
        }

        private void UpdateStatus()
        {
            if (StockRequestFulfillmentScheduleId != null)
            {
                Status = (ExpectedQty == FulfillQty) ? TransactionStatus.Received :
                         (ExpectedQty >= FulfillQty) ? TransactionStatus.Partial :
                         (ExpectedQty < FulfillQty) ? TransactionStatus.Received_Over : TransactionStatus.Open;
            }
            else
                Status = TransactionStatus.Received_Not_Requested;
        }

        public void SetStatusToClose()
        {
            Status = (Status == TransactionStatus.Partial) ? TransactionStatus.Partial_Closed : TransactionStatus.Closed;
        }
    }
```
```
Exception message: fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (2ms) [Parameters=[@p27='?', @p28='?', @p29='?', @p30='?', @p31='?', @p32='?', @p33='?', @p34='?', @p35='?', @p36='?', @p37='?', @p38='?', @p39='?'], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [StockReceivingDetail] ([ExpectedDate], [ExpectedQty], [FulfillQty], [ItemId], [ItemUOMId], [ReceivedDate], [SourceStoreId], [Status], [StockReceivingId], [StockRequestFulfillmentScheduleId], [StoreId], [VendorId], [WarehouseId])
      VALUES (@p27, @p28, @p29, @p30, @p31, @p32, @p33, @p34, @p35, @p36, @p37, @p38, @p39);
      SELECT [Id]
      FROM [StockReceivingDetail]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'StoreId'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ClientConnectionId:b7117d07-2aca-4fe0-a5f6-f719a759fdf1
Error Number:207,State:1,Class:16
Stack trace: fail: Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type 'isrsdata.DbContexts.Inventory.StockReceivingDbContext'.
      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Invalid column name 'StoreId'.
         at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
         at System.Data.SqlClient.SqlDataReader.get_MetaData()
         at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
         at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
         at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
         at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
         at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
         at System.Data.Common.DbCommand.ExecuteReader()
         at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
         at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
         --- End of inner exception stack trace ---
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)
         at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
         at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
         at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Invalid column name 'StoreId'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
An error occurred while updating the entries. See the inner exception for details.
```

### Steps to reproduce

Calling _context.SaveChanges() is producing the issue

```c#
    [Produces("application/json")]
    [Route("api/[controller]")]
    public class StockReceivingController : Controller
    {
        [HttpPost]
        public IActionResult Post([FromBody] StockReceivingDto dto)
        {
            setDefaultValues(dto);
            if (ModelState.IsValid)
            {
                StockReceiving stockReceivingToAdd = Mapper.Map<StockReceivingDto, StockReceiving>(dto);
                _unitOfWork.StockReceivings.Add(stockReceivingToAdd);
                stockLedgerRecord(stockReceivingToAdd);
                stockCountRecord(stockReceivingToAdd);
                int result = _unitOfWork.Complete();
                if (result == -1)
                {
                    return new StatusCodeResult(500);
                }
                return CreatedAtRoute("GetSingleStockReceiving", new { id = stockReceivingToAdd.Id }, Mapper.Map<StockReceivingDto>(stockReceivingToAdd));
            }

            return BadRequest(ModelState);
        }
    }

    public class UnitOfWork : IUnitOfWork
    {
        private readonly DbContext _context;

        public UnitOfWork(DbContext context)
        {
            _context = context;
        }

        public int Complete()
        {
            /*error handling here*/
            int result;
            try
            {
                result = _context.SaveChanges();
            } catch(DbUpdateException ex)
            {
                Console.WriteLine(ex.Message);
                result = -1;
            }
            
            return result;
        }

        public void Dispose()
        {
            _context.Dispose();
        }
    }
```

### Further technical details
EF Core version: 2.0.01 
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Pro
IDE: Visual Studio 2017 15.4.5

**Comment by Tarig0** [comment]
Is there anything in the dbcontext's onmodelconfigure?

**Comment by Tarig0** [comment]
The following won't link up unless you use attributes or the fluent API

```c#
        public int? SourceStoreId { get; set; }
        public Store Store { get; set; }
```

**Comment by ajcvickers** [comment]
@aldvsmaximvs The relationship between Store and StockReceivingDetail needs to have an FK defined. EF has conventions when looking for a property to use as the FK--these are documented here: https://docs.microsoft.com/en-us/ef/core/modeling/relationships. In this case, "SourceStoreId" does not match these conventions and so is not found as the FK. EF therefore creates a "shadow" FK property called "StoreId", but since your app is mapping to an existing database the column that this property is mapped to is not found. The doc link above shows how to tell EF that the "SourceStoreId" should be used as the FK, which can be done with either the `[ForeignKey]` attribute or using the fluent API.

**Comment by aldvsmaximvs** [comment]
Hi @ajcvickers, @Tarig0 

Thanks for the reply.

Here is my entity configuration for StockReceivingDetail and call this on OnModelCreating
```
 public class StockReceivingDetailConfiguration : IEntityTypeConfiguration<StockReceivingDetail>
    {
        public void Configure(EntityTypeBuilder<StockReceivingDetail> builder)
        {
            /*table*/
            /*keys*/
            builder.HasKey(p => p.Id);
            /*properties*/
            //builder.Property(p => p.ExpectedDate)
            //    .HasColumnType("datetime");
            builder.Property(p => p.ExpectedQty)
                .HasColumnType("numeric(19,6)");
            //builder.Property(p => p.ReceivedDate)
            //    .HasColumnType("datetime");
            builder.Property<byte[]>("RowVersion")
                .IsRowVersion();
            /*relationships*/
            builder.HasOne(p => p.FulfillmentSchedule)
                .WithMany()
                .HasForeignKey(p => p.StockRequestFulfillmentScheduleId);
            builder.HasOne(p => p.Warehouse)
                .WithMany()
                .HasForeignKey(p => p.WarehouseId);
            builder.HasOne(p => p.Store)
                .WithMany()
                .HasForeignKey(p => p.SourceStoreId);
            builder.HasOne(p => p.Vendor)
                .WithMany()
                .HasForeignKey(p => p.VendorId);
            builder.HasOne(p => p.Item)
                .WithMany()
                .HasForeignKey(p => p.ItemId);
            builder.HasOne(p => p.UOM)
                .WithMany()
                .HasForeignKey(p => p.ItemUOMId)
                .Metadata.DeleteBehavior = DeleteBehavior.Restrict;

        }
    }
```
And here the migrations generated
```
    public partial class StockReceivingInitial : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "StockReceiving",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    DocumentDate = table.Column<DateTime>(type: "datetime", nullable: false),
                    DocumentNo = table.Column<string>(maxLength: 30, nullable: false),
                    RowVersion = table.Column<byte[]>(rowVersion: true, nullable: true),
                    Status = table.Column<int>(nullable: false),
                    StockRequestId = table.Column<int>(nullable: true),
                    StoreId = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_StockReceiving", x => x.Id);
                    table.UniqueConstraint("AK_StockReceiving_DocumentNo", x => x.DocumentNo);
                    table.ForeignKey(
                        name: "FK_StockReceiving_StockRequest_StockRequestId",
                        column: x => x.StockRequestId,
                        principalTable: "StockRequest",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_StockReceiving_Store_StoreId",
                        column: x => x.StoreId,
                        principalTable: "Store",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "StockReceivingDetail",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    ExpectedDate = table.Column<DateTime>(type: "datetime", nullable: false),
                    ExpectedQty = table.Column<decimal>(type: "numeric(19,6)", nullable: false),
                    FulfillQty = table.Column<decimal>(nullable: false),
                    ItemId = table.Column<int>(nullable: false),
                    ItemUOMId = table.Column<int>(nullable: false),
                    ReceivedDate = table.Column<DateTime>(type: "datetime", nullable: false),
                    RowVersion = table.Column<byte[]>(rowVersion: true, nullable: true),
                    SourceStoreId = table.Column<int>(nullable: true),
                    Status = table.Column<int>(nullable: false),
                    StockReceivingId = table.Column<int>(nullable: false),
                    StockRequestFulfillmentScheduleId = table.Column<int>(nullable: true),
                    VendorId = table.Column<int>(nullable: true),
                    WarehouseId = table.Column<int>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_StockReceivingDetail", x => x.Id);
                    table.ForeignKey(
                        name: "FK_StockReceivingDetail_Item_ItemId",
                        column: x => x.ItemId,
                        principalTable: "Item",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_StockReceivingDetail_ItemUOM_ItemUOMId",
                        column: x => x.ItemUOMId,
                        principalTable: "ItemUOM",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_StockReceivingDetail_Store_SourceStoreId",
                        column: x => x.SourceStoreId,
                        principalTable: "Store",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_StockReceivingDetail_StockReceiving_StockReceivingId",
                        column: x => x.StockReceivingId,
                        principalTable: "StockReceiving",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_StockReceivingDetail_StockRequestFulfillmentSchedule_StockRequestFulfillmentScheduleId",
                        column: x => x.StockRequestFulfillmentScheduleId,
                        principalTable: "StockRequestFulfillmentSchedule",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_StockReceivingDetail_Vendor_VendorId",
                        column: x => x.VendorId,
                        principalTable: "Vendor",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_StockReceivingDetail_Warehouse_WarehouseId",
                        column: x => x.WarehouseId,
                        principalTable: "Warehouse",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_StockReceiving_StockRequestId",
                table: "StockReceiving",
                column: "StockRequestId");

            migrationBuilder.CreateIndex(
                name: "IX_StockReceiving_StoreId",
                table: "StockReceiving",
                column: "StoreId");

            migrationBuilder.CreateIndex(
                name: "IX_StockReceivingDetail_ItemId",
                table: "StockReceivingDetail",
                column: "ItemId");

            migrationBuilder.CreateIndex(
                name: "IX_StockReceivingDetail_ItemUOMId",
                table: "StockReceivingDetail",
                column: "ItemUOMId");

            migrationBuilder.CreateIndex(
                name: "IX_StockReceivingDetail_SourceStoreId",
                table: "StockReceivingDetail",
                column: "SourceStoreId");

            migrationBuilder.CreateIndex(
                name: "IX_StockReceivingDetail_StockReceivingId",
                table: "StockReceivingDetail",
                column: "StockReceivingId");

            migrationBuilder.CreateIndex(
                name: "IX_StockReceivingDetail_StockRequestFulfillmentScheduleId",
                table: "StockReceivingDetail",
                column: "StockRequestFulfillmentScheduleId");

            migrationBuilder.CreateIndex(
                name: "IX_StockReceivingDetail_VendorId",
                table: "StockReceivingDetail",
                column: "VendorId");

            migrationBuilder.CreateIndex(
                name: "IX_StockReceivingDetail_WarehouseId",
                table: "StockReceivingDetail",
                column: "WarehouseId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "StockReceivingDetail");

            migrationBuilder.DropTable(
                name: "StockReceiving");
        }
    }
```
As you can see the foreignkey is properly generated
```
                    table.ForeignKey(
                        name: "FK_StockReceivingDetail_Store_SourceStoreId",
                        column: x => x.SourceStoreId,
                        principalTable: "Store",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
```
I'm just wondering now, if the convention is being applied forcefully here?

**Comment by ajcvickers** [comment]
@aldvsmaximvs I took your code and attempted to create a runnable project that would reproduce what you are seeing, but there are a lot of missing pieces and I was not able to make it fail. Could you either update the code below or post a runnablle project/solution or other full code listing that reproduces what you are seeing?
```C#
public class StockReceiving 
{
    public int Id { get; set; }
    public string DocumentNo { get; set; }
    public DateTime DocumentDate { get; set; }

    public int StoreId { get; set; }
    public Store Store { get; set; }

    public TransactionStatus Status { get; set; }

    public ICollection<StockReceivingDetail> Details { get; set; }

}

public class Store
{
    public int Id { get; set; }
}

public class StockReceivingDetail
{
    public int Id { get; set; }

    public int StockReceivingId { get; set; }
    public StockReceiving StockReceiving { get; set; }

    public int? StockRequestFulfillmentScheduleId { get; set; }

    public int? WarehouseId { get; set; }
    public int? SourceStoreId { get; set; }
    public Store Store { get; set; }
    public int? VendorId { get; set; }

    public int ItemId { get; set; }
    public int ItemUOMId { get; set; }

    public DateTime ExpectedDate { get; set; }
    public decimal ExpectedQty { get; set; }
    public DateTime ReceivedDate { get; set; }

    public TransactionStatus Status { get; set; }
}

public class TestDbContext : DbContext
{
    public DbSet<StockReceiving> StockReceiving { get; set; }
    public DbSet<StockReceivingDetail> StockReceivingDetails { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<StockReceivingDetail>(builder =>
        {
            builder.HasKey(p => p.Id);
            builder.Property(p => p.ExpectedQty).HasColumnType("numeric(19,6)");
            builder.Property<byte[]>("RowVersion").IsRowVersion();
            builder.HasOne(p => p.Store)
                .WithMany()
                .HasForeignKey(p => p.SourceStoreId);
        });
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(
            @"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
}

public class Program
{
    public static void Main()
    {
        using (var context = new TestDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var store = new Store();
            context.Add(
                new StockReceiving
                {
                    Details = new List<StockReceivingDetail>
                    {
                        new StockReceivingDetail
                        {
                            Store = store
                        }
                    },
                    Store = store
                });

            context.SaveChanges();
        }
    }
}
```

**Comment by aldvsmaximvs** [comment]
Hi @ajcvickers 
[testproj.zip](https://github.com/aspnet/EntityFrameworkCore/files/1577849/testproj.zip)

I tried to reproduce the error in a new project but I couldn't replicate it. see attached. 
On my main project I have rename the property SourceStoreId to StoreId and it is now working. 
Thanks for your time and reply
