### ISSUE TITLE
the same key value for xxx is already being tracked

### ISSUE THREAD

**Issue by eightHundreds** [dotnet/efcore#10595]
```C#
public class Foo
{
    public int Id { get; set; }
}
public class TempDbContext:DbContext
{
    public TempDbContext(DbContextOptions<TempDbContext> options):base(options)
    {
        
    }
    public DbSet<Foo> Foos { get; set; }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        var t= modelBuilder.Entity<Foo>();
        t.HasKey(n => n.Id);
        t.Property(o => o.Id).ValueGeneratedOnAdd();
       //If I remove the ValueGeneratedOnAdd, the problem still exists
    }
}

[Fact]
public void TempTest()
{
    var services=new ServiceCollection();
    services.AddDbContext<TempDbContext>(opt => { opt.UseInMemoryDatabase("temp"); });
    var provider = services.BuildServiceProvider();
    var db=provider.GetService<TempDbContext>();
   
    db.Add(new Foo(){Id=1});
    db.SaveChanges();
    db.Add(new Foo());
    db.SaveChanges();
}
```

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
System.InvalidOperationException : The instance of entity type 'Foo' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState entityState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.Add[TEntity](TEntity entity)
```

### Further technical details
EF Core version: 2.0
Database Provider: InMemory
Operating system: MacOs 10.13
IDE: Rider EAP

**Comment by ajcvickers** [comment]
@eightHundreds Integer keys get configured to generate values by convention, and the first key value generated is 1. Use `t.Property(o => o.Id).ValueGeneratedNever();` to stop getting generated key values.
