### ISSUE TITLE
Migrations: Error at Creation "ManyToOne" relation 

### ISSUE THREAD

**Issue by AWMKarlas** [dotnet/efcore#1059]
I tried to create database:

``` C#
public DbSet<Modificat> Modifications { get; set; }
public DbSet<ExerciseDb> Exercises { get; set; }
public DbSet<ExerciseModificationDb> ExerciseModifications { get; set; }

protected override void OnModelCreating(ModelBuilder builder)
{
       builder.Entity<ExerciseModificationDb>().Property(p => p.Id).GenerateValueOnAdd(false);
       builder.Entity<ExerciseModificationDb>().Property(p => p.ModificationId).GenerateValueOnAdd(false);
       builder.Entity<ExerciseModificationDb>().Property(p => p.ExerciseId).GenerateValueOnAdd(false);
       builder.Entity<ExerciseModificationDb>().Key(p => p.Id);
       builder.Entity<ExerciseModificationDb>()
                .ManyToOne(em => em.Exercise, m => m.ExerciseModifications)
                .ForeignKey(m => m.ExerciseId);
       builder.Entity<ExerciseModificationDb>()
                .ManyToOne(em => em.Modification, m => m.ExerciseModifications)
                .ForeignKey(m => m.ModificationId);

       builder.Entity<Modificat>().Property(p => p.Id).GenerateValueOnAdd(false);
       builder.Entity<ExerciseDb>().Property(p => p.Id).GenerateValueOnAdd(false);

       base.OnModelCreating(builder);
}

public class ExerciseDb : BaseDbObject
    {
        public ExerciseDb()
        {
            ExerciseModifications = new HashSet<ExerciseModificationDb>();
        }

        public ICollection<ExerciseModificationDb> ExerciseModifications { get; set; }
    }

public class ExerciseModificationDb : BaseDbObject
    {
        /// <summary>
        /// Описание
        /// </summary>
        public string Description { get; set; }

        public int ExerciseId { get; set; }
        public int ModificationId { get; set; }

        public ExerciseDb Exercise { get; set; }
        public Modificat Modification { get; set; }
    }

public class Modificat : BaseDbObject
    {
        public Modificat()
        {
            ExerciseModifications = new HashSet<ExerciseModificationDb>();
        }

        public ICollection<ExerciseModificationDb> ExerciseModifications { get; set; }
        public override void Update(BaseLocalStorageDataModel dataModel)
        {

        }
    }
```

And I got a error:

```
at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Data.Entity.Relational.Model.DatabaseModel.GetTable(SchemaQualifiedName tableName)
   at Microsoft.Data.Entity.Migrations.DatabaseModelModifier.Visit(AddForeignKeyOperation addForeignKeyOperation, DatabaseModel databaseModel)
   at Microsoft.Data.Entity.Migrations.Model.AddForeignKeyOperation.Accept[TVisitor,TContext](TVisitor visitor, TContext context)
   at Microsoft.Data.Entity.Migrations.DatabaseModelModifier.Modify(DatabaseModel databaseModel, MigrationOperation operation)
   at Microsoft.Data.Entity.Migrations.DatabaseModelModifier.Modify(DatabaseModel databaseModel, IEnumerable`1 migrationOperations)
   at Microsoft.Data.Entity.SQLite.SQLiteMigrationOperationPreProcessor.CreateTableHandler.<HandleOperations>d__1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__71`1.MoveNext()
   at Microsoft.Data.Entity.SQLite.SQLiteMigrationOperationPreProcessor.Context.HandlePendingOperations()
   at Microsoft.Data.Entity.SQLite.SQLiteMigrationOperationPreProcessor.Context.get_Statements()
   at Microsoft.Data.Entity.SQLite.SQLiteMigrationOperationSqlGenerator.Generate(IEnumerable`1 migrationOperations)
   at Microsoft.Data.Entity.SQLite.SQLiteDataStoreCreator.CreateTables(IModel model)
   at Microsoft.Data.Entity.Relational.RelationalDataStoreCreator.EnsureCreated(IModel model)
   at Microsoft.Data.Entity.Infrastructure.Database.EnsureCreated()
   at AWM.InteractiveTrainer.Clients.WindowsPhone.Infrastructure.Application.InitializeLocalStorage()
   at AWM.WindowsPhone.Core.Infrastructure.BaseApplication..ctor()
   at AWM.InteractiveTrainer.Clients.WindowsPhone.Infrastructure.Application..ctor()
   at AWM.InteractiveTrainer.Clients.WindowsPhone.App..ctor()
   at AWM.InteractiveTrainer.Clients.WindowsPhone.Program.<Main>b__0(ApplicationInitializationCallbackParams p)
```

I renamed "Modificat" to "AModificat" and everything became fine

**Comment by bricelam** [comment]
@AWMKarlas I'm not able to repro this on the latest nightly. Can you try again on your side?
