### ISSUE TITLE
MigrationsSqlGenerator.Generate model parameter ArgumentNullException calling provider on revert

### ISSUE THREAD

**Issue by rcollette** [dotnet/efcore#10702]
Exception while reverting a single index using the command:
`dotnet ef database update InitialMigration`

```
Exception message: System.ArgumentNullException: Value cannot be null. Parameter name: model
Stack trace:
MySql.Data.EntityFrameworkCore.Migrations.MySQLMigrationsSqlGenerator.Generate(DropIndexOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateDownSql(Migration migration, Migration previousMigration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

```c#
namespace PitneyBowes.SendPro.Locations.Migrations
{
    public partial class DefaultLocationUniqueness : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateIndex(
                name: "IX_locations_subscription_id_is_default",
                table: "locations",
                columns: new[] { "subscription_id", "is_default" },
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_locations_subscription_id_is_default",
                table: "locations");
        }
    }
}
```

### Further technical details
EF Core version: 2.0.1
Database Provider: MySql.Data.EntityFrameworkCore 6.10.5
Operating system: OSX
IDE: VSCode

**Comment by ajcvickers** [comment]
@rcollette  This looks like an issue with the MySQL provider. Can you please file an issue with [the provider](https://docs.microsoft.com/en-us/ef/core/providers/mysql/), or you might consider using a different MySQL provider--we most often see people using the [Pomelo provider](https://docs.microsoft.com/en-us/ef/core/providers/pomelo/).
