### ISSUE TITLE
Can not migrate EfCore in .net Core 2 class library

### ISSUE THREAD

**Issue by Timosis** [dotnet/efcore#10795]
My project designed as layered approached. My Dbcontext is a different class library that takes entities from a different class library. When i try to migrate  I'm getting following exception. How i can fix this ? Also i have already added  <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles> into my csproj.

```
Exception calling "SetData" with "2" argument(s): "Type 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject' in assembly 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation, Version=15.0.0.0,
 Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable."
At C:\Users\Tumer\.nuget\packages\entityframework\5.0.0\tools\EntityFramework.psm1:390 char:5
 $domain.SetData('project', $project)
    CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
   FullyQualifiedErrorId : SerializationException
 
Exception calling "SetData" with "2" argument(s): "Type 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject' in assembly 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation, Version=15.0.0.0,
 Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable."
At C:\Users\Tumer\.nuget\packages\entityframework\5.0.0\tools\EntityFramework.psm1:391 char:5
   $domain.SetData('startUpProject', $startUpProject)
  CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
   FullyQualifiedErrorId : SerializationException
 
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Data.Entity.Migrations.Extensions.ProjectExtensions.GetPropertyValue[T](Project project, String propertyName)
   at System.Data.Entity.Migrations.MigrationsDomainCommand.GetFacade(String configurationTypeName)
   at System.Data.Entity.Migrations.AddMigrationCommand.<>c__DisplayClass3.<.ctor>b__1()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
Object reference not set to an instance of an object.
```

**Comment by smitpatel** [comment]
> C:\Users\Tumer\.nuget\packages\entityframework\5.0.0\tools\EntityFramework.psm1

Is it EF 5.0? 😨

**Comment by ajcvickers** [comment]
@Timosis You will need to have the EF Core PMC tools installed--they are in the Microsoft.EntityFrameworkCore.Tools package. You'll likely also need to close and re-open VS after doing this so that PowerShell gets reset.
