### ISSUE TITLE
Sql Server DateTime Comparison Exception

### ISSUE THREAD

**Issue by jceddy** [dotnet/efcore#10876]
Query that returns result of a DateTime comparison is throwing an exception (when using SQL Server).

```
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'System.DateTime' to type 'System.TimeSpan'.
  Source=Microsoft.EntityFrameworkCore.Relational
  StackTrace:
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GetData.Execute(Dictionary`2 parameters) in D:\path-to\Programmability\StoredProcedures\GetData.cs:line 60
   at Namespace.DatabaseProgrammabilityBase.Execute(IDbDataParameter[] parameters) in D:\path-to\Programmability\DatabaseProgrammabilityBase.cs:line 36
   at Namesapce.IDatabaseContextManager.GetLinqFromProcedure[T](String procedureName, Func`2 mappingFunc, DbParameter[] parameters) in D:\path-to\DatabaseContextManager.cs:line 332
   at Namespace.SummaryController.SummaryData(String xtype) in D:\path-to\EndPoints\SummaryController.cs:line 111
   at Namespace.SummaryController.GetData(String xtype) in D:\path-to\EndPoints\SummaryController.cs:line 78
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
```

This happens when I try to fetch the results of a datetime comparison from SQL Server. My test query is below:

```c#
var testRecords = (from u in users
    select new
    {
        Idle = (DateTime.UtcNow - u.LastUserActionTimeStamp).Minutes
    }).ToList();
```

users.LastUserActionTimeStamp is a DateTime column in the database and has type DateTime in the EF model.

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows Server 2008 R2 Standard
IDE: Visual Studio 2017 Professional version 15.5.6

**Comment by pmiddleton** [comment]
Dup of #10656
