### ISSUE TITLE
Azure Functions cannot act as a startup project

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/efcore#10898]
### Steps to reproduce

I have three projects:

1. A .NET Core library
1. A .NET Core console app
1. A .NET Core Azure Functions (v1) app

If I try to add migrations to the library using the console app as the startup project, the migration is added as expected. However, if I try to the add the migrations using the Functions app, then I get an exception:

```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.EntityFrameworkCore.Design' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.EntityFrameworkCore.Design'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at Microsoft.EntityFrameworkCore.Tools.AppDomainOperationExecutor..ctor(String assembly, String startupAssembly, String projectDir, String contentRootPath, String dataDirectory, String rootNamespace, String environment)
   at Microsoft.EntityFrameworkCore.Tools.Commands.ProjectCommandBase.CreateExecutor()
   at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsAddCommand.Execute()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Could not load file or assembly 'Microsoft.EntityFrameworkCore.Design' or one of its dependencies. The system cannot find the file specified.

```

### Further technical details
TargetFramework: net461
EF Core version: 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer (1.1.1)
Operating system: Win10 v1511
IDE: Visual Studio 2017 15.5.4
Other packages installed
All projects have packages:
- Microsoft.EntityFrameworkCore.SqlServer: 1.1.1
- Microsoft.EntityFrameworkCore.Tools: 1.1.1

I also tried explicitly adding 
Microsoft.EntityFrameworkCore.Design: 1.1.2 (even though it's covered by Tools)
but that did not change the error message.

[EFCoreMigrations.zip](https://github.com/aspnet/EntityFrameworkCore/files/1701165/EFCoreMigrations.zip)

**Comment by MisinformedDNA** [comment]
I fully upgraded the EF Core packages to 2.0.1. Same error, different form:
```
Your startup project 'MyProject.FunctionApp' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again.
```

**Comment by bricelam** [comment]
It looks like the data we get from MSBuild is incorrect:

Property | Value
--- | ---
$(TargetDir) | C:\FunctionApp1\bin\Debug\net461\
$(TargetPath) | C:\FunctionApp1\bin\Debug\net461\FunctionApp1.dll

The actual assembly lives under <tt>bin\Debug\net461\\<strong>bin\\</strong>FunctionApp1.dll</tt>

We need to follow up with the Azure Functions Tools team.
