### ISSUE TITLE
Update only OwnedType fields of entity

### ISSUE THREAD

**Issue by uknickwilliams** [dotnet/efcore#10965]
I am trying to connect a disconnected entity and then mark only 1 property (which is an owned type) as changed.

Attempt to update only the properties of an owned type fails when using `context.Entity(e).Property(e => e.MyOwnedType).IsModified = true`. This works under EF6 using complex types.

Using `context.Entity(e).Reference(e => e.MyOwnedType).IsModified = true` does not save the modified value.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: The property 'MyOwnedType' on entity type 'MyEntity' is being accessed using the 'Property' method, but is defined in the model as a navigation property. Use either the 'Reference' or 'Collection' method to access navigation properties.'
Stack trace:
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityTypeExtensions.GetProperty(IEntityType entityType, String name)
   at Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry`1.Property[TProperty](Expression`1 propertyExpression)
   at PropertyUpdateTest.Program.UpdateEntity() in C:\Users\Nick.Williams\Desktop\PropertyUpdateTest\PropertyUpdateTest\Program.cs:line 46
   at PropertyUpdateTest.Program.Main(String[] args) in C:\Users\Nick.Williams\Desktop\PropertyUpdateTest\PropertyUpdateTest\Program.cs:line 14
```

### Steps to reproduce

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace PropertyUpdateTest
{
    class Program
    {
        static void Main(string[] args)
        {
            AddEntity();
            UpdateEntity();
        }

        private static void AddEntity()
        {
            using (var dbContext = CreateDbContext())
            {
                var entity = new MyEntity()
                {
                    MyOwnedType = new MyOwnedType()
                    {
                        Foo = "Bar"
                    }
                };

                dbContext.MyEntities.Add(entity);
                dbContext.SaveChanges();
            }
        }

        private static void UpdateEntity()
        {
            using (var dbContext = CreateDbContext())
            {
                var myEntitiy = dbContext.MyEntities.AsNoTracking().First();

                myEntitiy.MyOwnedType = new MyOwnedType()
                {
                    Foo = "Baz"
                };

                dbContext.Attach(myEntitiy);
                var entry = dbContext.Entry(myEntitiy);
                entry.Property(d => d.MyOwnedType).IsModified = true;
                dbContext.SaveChanges();
            }
        }

        private static MyDbContext CreateDbContext()
        {
            var options = new DbContextOptionsBuilder<MyDbContext>().UseInMemoryDatabase("MyDbContext").Options;
            return new MyDbContext(options);
        }
    }

    class MyDbContext : DbContext
    {
        public DbSet<MyEntity> MyEntities { get; set; }

        protected MyDbContext()
        {
        }

        public MyDbContext(DbContextOptions options) : base(options)
        {

        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<MyEntity>().OwnsOne(d => d.MyOwnedType);
        }
    }

    class MyEntity
    {
        public long Id { get; set; }
        public MyOwnedType MyOwnedType { get; set; }
    }

    class MyOwnedType
    {
        public string Foo { get; set; }
    }
}
```

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.InMemory
Operating system: Windows 10 (v. 1709)
IDE: Visual Studio 2017 15.4

**Comment by Tarig0** [comment]
Might be looking for 

```c#
context.Entity(e).Reference(e => e.MyOwnedType).EntityEntry.IsModified = true
```

**Comment by uknickwilliams** [comment]
I can't find that API using version 2.0.1

``` c#
//No Entity() method is available on type DbContext.
dbContext.Entity(e).Reference(e => e.MyOwnedType).EntityEntry.IsModified = true
```

If i use `Entry()` rather `Entity()` the `EntityEntry` property has not `IsModified` property.

``` c#
//IsModified not on type EntityEntry<>
dbContext.Entry(myEntitiy).Reference(e => e.MyOwnedType).EntityEntry.IsModified = true;
```

**Comment by Tarig0** [comment]
sorry here it is

```c#
_db.Entry(myEntitiy).Reference(m=>m.MyOwnedType).TargetEntry.State = EntityState.Modified
```

**Comment by ajcvickers** [comment]
@uknickwilliams The key thing to remember here is that an owned entity type is still an entity type, and even though it behaves differently in some cases, the code for setting the state to modified is the same as for any other entity. For example:
```C#
context.Entry(myEntitiy.MyOwnedType).State = EntityState.Modified;
```
Likewise, to set just a single property to modified, use something like:
```C#
context.Entry(myEntitiy.MyOwnedType).Property(e => e.Foo).IsModified = true;
```
