### ISSUE TITLE
Nullable Foreign Key set Negative Id value before SaveChanges

### ISSUE THREAD

**Issue by mburakerbay** [dotnet/efcore#11060]
Hi;

When i try to save relation table, EFCore set temporary id (int minvalue) to nullable foreign key and i got an exception.

```
Exception message: One or more errors occurred. (The property 'MemberId' on entity type 'MemberBookDiscount' has a temporary value. Either set a permanent value explicitly or ensure that the database is configured to generate values for this property.)
Stack trace:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at OrnekAkademiWeb.Program.Main(String[] args) in xxx\SampleEFCoreException\SampleEFCoreException\Program.cs:line 27

   -------------InnerException-----------------------------------------
   
	Exception message: The property 'MemberId' on entity type 'MemberBookDiscount' has a temporary value. Either set a permanent value explicitly or ensure that the database is configured to generate values for this property.
	Stack trace:          at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.Validate(ModificationCommand modificationCommand)
	   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.<BatchCommands>d__8.MoveNext()
	   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__10.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__61.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__59.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__48.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
	   at ModelEntity.Data.SampleContext.<SaveChangesAsync>d__5.MoveNext() in xxx\SampleEFCoreException\ModelEntity\Data\SampleContext.cs:line 60
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	   at ModelEntity.Data.DbInitializer.<InitializeAsync>d__0.MoveNext() in xxx\SampleEFCoreException\ModelEntity\Data\DbInitializer.cs:line 19
```
### Steps to reproduce

Sample Project Here:
[https://github.com/mburakerbay/SampleEFCoreException](https://github.com/mburakerbay/SampleEFCoreException)

You can see the exception in Program.cs line 27

```c#
try
{
	var context = services.GetRequiredService<SampleContext>();
	DbInitializer.InitializeAsync(context).Wait();
}
catch (Exception ex)
{
	Console.WriteLine(ex.Message);
}
```
DbInitializer.cs
```c#
if (!await context.MemberBookDiscounts.AnyAsync())
{
	var mbd = new MemberBookDiscount { MemberId = null, BookId = null, DiscountRate = 25 };
	await context.MemberBookDiscounts.AddAsync(mbd);
}

await context.SaveChangesAsync();
```

After opened the issue i saw model builder did not make this field nullable. Why?

```c#
migrationBuilder.CreateTable(
	name: "MemberBookDiscounts",
	columns: table => new
	{
		MemberId = table.Column<int>(type: "int", nullable: false),
		BookId = table.Column<int>(type: "int", nullable: false),
		DiscountRate = table.Column<decimal>(type: "decimal(18, 2)", nullable: false)
	},
	constraints: table =>
	{
		table.PrimaryKey("PK_MemberBookDiscounts", x => new { x.MemberId, x.BookId });
		table.ForeignKey(
			name: "FK_MemberBookDiscounts_Books_BookId",
			column: x => x.BookId,
			principalTable: "Books",
			principalColumn: "Id",
			onDelete: ReferentialAction.Cascade);
		table.ForeignKey(
			name: "FK_MemberBookDiscounts_Members_MemberId",
			column: x => x.MemberId,
			principalTable: "Members",
			principalColumn: "Id",
			onDelete: ReferentialAction.Cascade);
	});
```

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.5.7

**Comment by ajcvickers** [comment]
@mburakerbay `MemberId` and `BookId` are configured as the primary key for `MemberBookDiscount`. Primary keys cannot be nullable. Can you explain what the intention is in trying to make these members nullable?

**Comment by mburakerbay** [comment]
@ajcvickers I just want to do that;
if both `MemberId` and `BookId` empty, this is general discount for all Book for all Member.
if `MemberId` empty but `BookId` is not, this is Book1 discount for all Member.
if `BookId` empty but `MemberId` is not, this is general discount for all Book for Member1.
if both `MemberId` and `BookId` is not empty, this is Book1 discount for for Member1.

**Comment by ajcvickers** [comment]
@mburakerbay Then you will need to give MemberBookDiscount another property to act as the primary key.

**Comment by mburakerbay** [comment]
@ajcvickers I added `Id` property for key but still `MemberId` and `BookId` are configured as the primary key for `MemberBookDiscount` and the new property `Id` is configured as the unique column


```
public class MemberBookDiscount
{
    [Key]
    public int Id { get; set; }

    public int? MemberId { get; set; }
    public virtual Member Member { get; set; }

    public int? BookId { get; set; }
    public virtual Book Book { get; set; }

    [Required]
    [RegularExpression(@"^\d+(\.\d)?$")]
    [Range(0.1, 100)]
    public decimal DiscountRate { get; set; }
}
```

```
migrationBuilder.CreateTable(
	name: "MemberBookDiscounts",
	columns: table => new
	{
		MemberId = table.Column<int>(nullable: false),
		BookId = table.Column<int>(nullable: false),
		DiscountRate = table.Column<decimal>(nullable: false),
		Id = table.Column<int>(nullable: false)
	},
	constraints: table =>
	{
		table.PrimaryKey("PK_MemberBookDiscounts", x => new { x.MemberId, x.BookId });
		table.UniqueConstraint("AK_MemberBookDiscounts_Id", x => x.Id);
		table.ForeignKey(
			name: "FK_MemberBookDiscounts_Books_BookId",
			column: x => x.BookId,
			principalTable: "Books",
			principalColumn: "Id",
			onDelete: ReferentialAction.Cascade);
		table.ForeignKey(
			name: "FK_MemberBookDiscounts_Members_MemberId",
			column: x => x.MemberId,
			principalTable: "Members",
			principalColumn: "Id",
			onDelete: ReferentialAction.Cascade);
	});
```

**Comment by ajcvickers** [comment]
@mburakerbay Did you remove the HasKey call that was defining MemberId and BookId as the key? You might want to read through some of the model building docs: https://docs.microsoft.com/en-us/ef/core/modeling/
