### ISSUE TITLE
Array insertion broken after adding value comparer

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#11077]
@ajcvickers, after [my commit adding value comparers to arrays](https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/commit/dfdc3364911116012c8a19b93151637e544a81d7), inserting an entity with an array breaks with the following exception (I confirmed that right before this commit everything worked well):

```
Unhandled Exception: System.ArgumentException: Expression of type 'System.Collections.Generic.IList`1[System.Int32]' cannot be used for constructor parameter of type 'System.Int32[]'
Parameter name: arguments[2]
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Dynamic.Utils.ExpressionUtils.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments, String methodParamName)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.SnapshotFactoryFactory.CreateSnapshotExpression(Type entityType, ParameterExpression parameter, Type[] types, IList`1 propertyBases)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.SnapshotFactoryFactory.CreateConstructorExpression(IEntityType entityType, ParameterExpression parameter)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.SnapshotFactoryFactory`1.Create(IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.OriginalValues..ctor(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.EnsureOriginalValues()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntrySubscriber.SnapshotAndSubscribe(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node, Boolean force)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Object state, Func`3 handleNode)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at ConsoleTest.Program.Main(String[] args) in /home/roji/projects/EFCore.PG/ConsoleTest/Program.cs:line 20
```

**Comment by roji** [comment]
Note that doing the same with hstore (a PostgreSQL `Dictionary<string,string>` type) works just fine, this seems to be array-specific.

**Comment by roji** [comment]
I'll try to test again in the coming days, will let you know.

**Comment by ajcvickers** [comment]
@roji Marking this as fixed for now. Please comment if you find you are still hitting the issue and we can re-open.

**Comment by divega** [comment]
Reopening and removing milestone so we can triage.

**Comment by AndriySvyryd** [comment]
@roji Could you change the comparers to derive from `ValueComparer<TElem[]>` instead of `ValueComparer<IList<TElem>>` and use `TElem[]` in the static methods?

**Comment by roji** [comment]
@AndriySvyryd thanks for the suggestion, that does fix everything! Thanks!

For this is definitely fine, but I may want to also allow mapping `List<T>` in the future, in addition to `T[]`, I'm hoping this is going to work as well. But this isn't urgent in any way.

**Comment by roji** [comment]
@AndriySvyryd thanks, if `List<T>` should work then everything's OK, I don't have an issue with having a separate comparer for it.

Thanks again!
