### ISSUE TITLE
System.InvalidOperationException in query after 2.1 upgrade

### ISSUE THREAD

**Issue by stevejgordon** [dotnet/efcore#11092]
Since upgrading an application to ASP.NET Core and EF Core 2.1 I'm seeing a new exception from an existing EF query.

You can find the problem query at https://github.com/stevejgordon/allReady/blob/fa75bb76b9da3da2e71a4cc256799f07725e7bf8/AllReadyApp/Web-App/AllReady/Areas/Admin/Features/Itineraries/ItineraryDetailQueryHandler.cs#L28

Granted this is quite a complex an mucky approach to building up the ViewModel which in itself might need some refactoring. However, in 2.0 this worked and produced the expected object.

Running the code (in this 2.1 branch) now converted to 2.1 I get the following exception when the query is executed.

```
System.InvalidOperationException
  HResult=0x80131509
  Message=The query model's result type cannot be changed to 'System.Linq.IQueryable`1[Microsoft.EntityFrameworkCore.Query.Internal.MaterializedAnonymousObject]'. The result type may only be overridden and set to values compatible with the ResultOperators' current data type ('Microsoft.EntityFrameworkCore.Query.Internal.MaterializedAnonymousObject').
  Source=Remotion.Linq
  StackTrace:
   at Remotion.Linq.QueryModel.GetOutputDataInfo()
   at Remotion.Linq.Clauses.Expressions.SubQueryExpression..ctor(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryModelExtensions.PopulateQueryModelMapping(QueryModel queryModel, Dictionary`2 mapping)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.LiftSubQuery(IQuerySource querySource, SubQueryExpression subQueryExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.CompileJoinClauseInnerSequenceExpression(JoinClause joinClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitJoinClause(JoinClause joinClause, QueryModel queryModel, Int32 index)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitJoinClause(JoinClause joinClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.Clauses.JoinClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ProjectionExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
   at Remotion.Linq.Clauses.Expressions.SubQueryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ProjectionExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ProjectionExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ProjectionExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitAndConvert[T](ReadOnlyCollection`1 nodes, String callerName)
   at Remotion.Linq.Parsing.RelinqExpressionVisitor.VisitNew(NewExpression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.VisitNew(NewExpression newExpression)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.Clauses.SelectClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileAsyncQuery[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass22_0`1.<CompileAsyncQuery>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddAsyncQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQuery[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at AllReady.Areas.Admin.Features.Itineraries.ItineraryDetailQueryHandler.<Handle>d__4.MoveNext() in C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\Areas\Admin\Features\Itineraries\ItineraryDetailQueryHandler.cs:line 28

Inner Exception 1:
ArgumentException: 'System.Linq.IQueryable`1[Microsoft.EntityFrameworkCore.Query.Internal.MaterializedAnonymousObject]' cannot be used as the new data type for a value of type 'Microsoft.EntityFrameworkCore.Query.Internal.MaterializedAnonymousObject'.
```

My best guess this is due to the changes documented in the announcement post around "Optimization of correlated subqueries" since we're calling ToList() here to force these to populate our List property on the ViewModel.

In fact if I modify the ViewModel to change the List<RequestListViewModel> to an IEnumerable<RequestListViewModel> and then remove the ToList() call on the query, it no longer causes the exception.

### Further notes

Reducing the query to something smaller the following executes:

```
var itineraryDetails = await _context.Itineraries
	.AsNoTracking()
	.Include(x => x.Requests)
	.Select(i => new {
		Id = i.Id,
		RequestIds = i.Requests.Select(r => new
		{
			Id = r.Request.RequestId
		})
		.ToList()
	}).ToListAsync();
```

While changing to FirstOrDefaultAsync() causes the exception

```
var itineraryDetails = await _context.Itineraries
	.AsNoTracking()
	.Include(x => x.Requests)
	.Select(i => new {
		Id = i.Id,
		RequestIds = i.Requests.Select(r => new
		{
			Id = r.Request.RequestId
		})
		.ToList()
	}).FirstOrDefaultAsync();
```

In cases where the ToList is added when selecting the requests, is it expected that this cannot be used in combination with FirstOrDefaultAsync?

### Further technical details
EF Core version: 2.1-preview1-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows
IDE: Visual Studio 2017 15.6.0 Preview 6.0

**Comment by nukuuk** [comment]
I seem to be getting the same or similar problem:  https://github.com/aspnet/EntityFrameworkCore/issues/11098

**Comment by maumar** [comment]
@stevejgordon simplified case with FirstOrDefault is most likely due to #10813 - it's fixed currently but the fix didn't make it to preview1.

**Comment by stevejgordon** [comment]
@maumar Thanks. That looks likely. In fact, if I change the original more complex query to use ToListAsync() instead of SingleOrDefaultAsync() it works without error too.

A shame as that's a bit of show stopper from me really testing this application on preview 1 bits then!

**Comment by ajcvickers** [comment]
@stevejgordon Can you try with our nightly feed? It's listed on the repo home here: https://github.com/aspnet/EntityFrameworkCore

**Comment by maumar** [comment]
@stevejgordon you can also try the workaround for #10813, i.e. use

```cs
query.Take(2).ToList().SingleOrDefault();
```
