### ISSUE TITLE
mysql generate sql not recognized by mysql

### ISSUE THREAD

**Issue by rocketRobin** [dotnet/efcore#11090]
Code like this 

    var data = await list.AsNoTracking().OrderBy(x => x.Id).Skip((model.PageIndex - 1) * model.PageSize)
            .Take(model.PageSize)
            .Select(r => new RoleSummary
            {
                Id = r.Id,
                Name = r.Name,
                LastUpdateTime = r.LastUpdateTime,
                UsersCount = r.UserRoles.Count
            }).ToListAsync();

and the excption is :

	fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
		  Failed executing DbCommand (14ms) [Parameters=[@__p_1='?', @__p_0='?'], CommandType='Text', CommandTimeout='30']
		  SELECT `x`.`Id`, `x`.`Name`, `x`.`LastUpdateTime`, CAST((
			  SELECT COUNT(*)
			  FROM `UserRoles` AS `u`
			  WHERE `x`.`Id` = `u`.`RoleId`
		  ) AS bigint) AS `UsersCount`
		  FROM `Roles` AS `x`
		  ORDER BY `x`.`Id`
		  LIMIT @__p_1 OFFSET @__p_0
		  
	MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'bigint) AS `UsersCount`
	FROM `Roles` AS `x`
	ORDER BY `x`.`Id`
	LIMIT 1 OFFSET ' at line 5

	   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
	   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
	   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
	   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
	   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
	   at System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()

I tried in mysql workbanch, this seemed like mysql not support this sentence “cast as bigint”

### Further technical details
EF Core version: (2.0.1)
Database Provider: (MySql.Data.EntityFrameworkCore)6.10.5
Operating system:  Windows 7  both runtime and database server
IDE: ( Visual Studio 2017 15.5.5)

**Comment by ajcvickers** [comment]
@rocketRobin Please file an issue with the MySql provider: https://bugs.mysql.com/
