### ISSUE TITLE
Could not find file 'D:\xxx\bin\Debug\netcoreapp2.0\ef.xml'

### ISSUE THREAD

**Issue by Basil1991** [dotnet/efcore#11208]
System.IO.FileNotFoundException: Could not find file 'D:\xxx\bin\Debug\netcoreapp2.0\ef.xml'.
File name: 'D:\xxx\bin\Debug\netcoreapp2.0\ef.xml'
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.OpenUrl()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XPath.XPathDocument.LoadFromReader(XmlReader reader, XmlSpace space)
   at System.Xml.XPath.XPathDocument..ctor(String uri, XmlSpace space)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.<>c__DisplayClass27_0.<IncludeXmlComments>b__0()
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.CreateSwaggerProvider(IServiceProvider serviceProvider)
   at AspectCore.Injector.ServiceCallSiteResolver.<>c__DisplayClass4_0.<ResolvePropertyInject>b__0(IServiceResolver resolver)
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
An error occurred while calling method 'BuildWebHost' on class 'Program'. Continuing without the application service provider. Error: Could not find file 'D:\xxx\bin\Debug\netcoreapp2.0\ef.xml'.
Unable to create an object of type 'WikiDbContext'. Add an implementation of 'IDesignTimeDbContextFactory<WikiDbContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.

------------
        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();

------------
            services.AddDbContext<WikiDbContext>(options => {
                options.UseMySql(configuration.GetConnectionString("WebAppDb"));
            });

-----------

                public class WikiDbContext : DbContext {
                          public WikiDbContext(DbContextOptions options) : base(options) { }
                 }
         
When press Add-Migration or Update-Database.

**Comment by Basil1991** [comment]
The reason is  Assembly.GetEntryAssembly().

**Comment by akousmata** [comment]
@vetemi this was a result of him trying to use Swagger for API code generation along side the EF auto code generation tools.  The documentation for setting up Swagger recommends doing so in the ConfigureServices call like this:

`services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info { Title = "My API", Version = "v1" });

                // Set the comments path for the Swagger JSON and UI.
                var xmlFile = $"{**_Assembly.GetEntryAssembly()_**.GetName().Name}.xml";
                var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
                c.IncludeXmlComments(xmlPath);
            });`

I found this out the hard way and lost several hours to this.  Not sure if that helps you or not, but that is what he means when he says 

> The reason is Assembly.GetEntryAssembly().
