### ISSUE TITLE
[MySql Provider Question] 2.1.0-preview1 Upgrade 'GeneratedTime.CreatedTimestamp' could not be mapped

### ISSUE THREAD

**Issue by caleblloyd** [dotnet/efcore#11233]
I am working on the Pomelo MySql provider update to 2.1.0-preview1:

- Branch is [here](https://github.com/caleblloyd/Pomelo.EntityFrameworkCore.MySql/tree/f_2.1.0-preview)
- PR is https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/510

Presently everything is failing with this error and I can't figure out what is missing.  Could you point me in the right direction @ajcvickers @smitpatel 

```
[xUnit.net 00:00:03.3297454]       System.InvalidOperationException : The property 'GeneratedTime.CreatedTimestamp' could not be mapped, because it is of type 'DateTime' which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
[xUnit.net 00:00:03.3298187]       Stack Trace:
[xUnit.net 00:00:03.3298596]            at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyMappingValidationConvention.Apply(InternalModelBuilder modelBuilder)
[xUnit.net 00:00:03.3298985]            at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
[xUnit.net 00:00:03.3299433]            at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
[xUnit.net 00:00:03.3299740]            at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
[xUnit.net 00:00:03.3299972]            at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
[xUnit.net 00:00:03.3300151]            at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
[xUnit.net 00:00:03.3300331]            at lambda_method(Closure , ServiceProviderEngineScope )
[xUnit.net 00:00:03.3300568]            at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
[xUnit.net 00:00:03.3300821]            at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
[xUnit.net 00:00:03.3301011]            at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
[xUnit.net 00:00:03.3301269]            at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
[xUnit.net 00:00:03.3301454]            at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
[xUnit.net 00:00:03.3301660]            at Microsoft.EntityFrameworkCore.DbContext.EntryWithoutDetectChanges[TEntity](TEntity entity)
[xUnit.net 00:00:03.3301856]            at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
[xUnit.net 00:00:03.3302140]         /home/caleb/Projects/caleb/Pomelo.EntityFrameworkCore.Mysql/test/EFCore.MySql.FunctionalTests/Tests/Models/ExpressionTest.cs(32,0): at EFCore.MySql.FunctionalTests.Tests.Models.ExpressionTest..ctor()

```

**Comment by ajcvickers** [comment]
@caleblloyd That exception means that the the type mapper (ITypeMappingSource in 2.1) is not returning a mapping for DateTime. ITypeMappingSource calls into your implementation of IRelationalTypeMapper if you haven't implemented the new service shapes directly.

**Comment by caleblloyd** [comment]
We're still using IRelationalTypeMapper

The CLR Type Mapping for DateTime is here:

https://github.com/caleblloyd/Pomelo.EntityFrameworkCore.MySql/blob/f_2.1.0-preview/src/EFCore.MySql/Storage/Internal/MySqlTypeMapper.cs#L147

This method hasn't changed from 2.0.1 to 2.1.0-preview1

Anything else that could cause it?

**Comment by ajcvickers** [comment]
@caleblloyd I would suggest debugging to see why the type mapper is not returning a mapping on this code path.
