### ISSUE TITLE
issues when executing "Add-Migration" command

### ISSUE THREAD

**Issue by karimo3** [dotnet/efcore#11264]
Describe what is not working as expected.
I am following a tutorial on the Microsoft site --> https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model
I am up to the part where I need to "Add scaffold tooling and perform initial migration". I have installed the required NuGet package (microsoft.visualstudio.web.codegeneration.design) and attempted to run the "Add-Migration" command. Then I get this error --> Method not found: 'System.String Microsoft.EntityFrameworkCore.Metadata.Internal.Property.Format(System.Collections.Generic.IEnumerable`1<Microsoft.EntityFrameworkCore.Metadata.IProperty>, Boolean)'.
Assume all previous parts of the tutorial have been done correctly. 
If you are seeing an exception, include the full exceptions details (message and stack trace).
Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\kobaid\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
System.MissingMethodException: Method not found: 'System.String Microsoft.EntityFrameworkCore.Metadata.Internal.Property.Format(System.Collections.Generic.IEnumerable`1<Microsoft.EntityFrameworkCore.Metadata.IProperty>, Boolean)'.
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedTableCompatibility(IReadOnlyList`1 mappedTypes, String tableName)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedTableCompatibility(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Method not found: 'System.String Microsoft.EntityFrameworkCore.Metadata.Internal.Property.Format(System.Collections.Generic.IEnumerable`1<Microsoft.EntityFrameworkCore.Metadata.IProperty>, Boolean)'.
```
Exception message:
Stack trace:
```

### Further technical details
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.0-preview1-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational.Design" Version="1.1.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.2" />
    <PackageReference Include="microsoft.visualstudio.web.codegeneration.design" Version="2.0.3" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.2" />
  </ItemGroup>
</Project>
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017

Thank you,
Karim Obaid

**Comment by ajcvickers** [comment]
@karimo3 Looks like there are probably mis-matched package versions somewhere. Can you check that you are using consistent versions? If you still hit the issue, then please post a runnable project./solution that demonstrates what you are seeing so that we can investigate.

**Comment by karimo3** [comment]
What do you mean by mis-matched package versions? How would I go about doing fixing it?
The only reason I ask this is because I usually see that most packages are different versions anyway.

**Comment by ajcvickers** [comment]
@karimo3 Can you please post your project/solution so that we can look at the package versions and if needed attempt to reproduce the behavior you are seeing?

**Comment by karimo3** [comment]
[MicrosoftTutorial.zip](https://github.com/aspnet/EntityFrameworkCore/files/1841968/MicrosoftTutorial.zip)

**Comment by bricelam** [comment]
I think you need to update this line in your csproj to version 2.0.3. But this shouldn't have any impact on the [Add-Migration command](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell).

``` xml
<DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools"
                        Version="2.0.2" />
```

**Comment by bricelam** [comment]
Add-Migration is working for me on your project as you sent it.

**Comment by karimo3** [comment]
Hi,
So without making any changes, as you said, for some reason it is working now. 

I dont understand why I received that error, but I did restart my machine a few times during the week which may have helped. Not really sure. 

Thanks for your help.

**Comment by ajcvickers** [comment]
@bricelam Can this be closed?
