### ISSUE TITLE
String or binary data would be truncated

### ISSUE THREAD

**Issue by glararan** [dotnet/efcore#11346]
Hi,

I have Model for RAW SQL due performance and cause EF can't simply take in simple query 2 Max values and 1 Min value. Due to a lot of values in "IN" clause Im getting this error. I probably have to go for old commands :(

```
Exception message: String or binary data would be truncated
Stack trace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.<>c__DisplayClass190_0.<ReadAsync>b__1(Task t)
   at System.Data.SqlClient.SqlDataReader.InvokeRetryable[T](Func`2 moreFunc, TaskCompletionSource`1 source, IDisposable objectToDispose)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__12.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__11.MoveNext()
   at System.Linq.AsyncEnumerable.<SingleOrDefault_>d__381`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
```

### Steps to reproduce
1) Make FromSql query for some table where do you use "IN" clause with a lot of values

```c#
          public class ProductsStats
    {
        public decimal MaxPrice { get; set; }
        public decimal MinWeight { get; set; }
        public decimal MaxWeight { get; set; }
    }

           // Controller.cs
           ProductsStats result = null;

            try
            {
                string ins = string.Join(",", productIds.Select(x => $"'{x}'"));

                result = await db.Query<ProductsStats>().FromSql($"SELECT CEILING(MAX(BruttoPrice)) MaxPrice, FLOOR(MIN(Weight)) MinWeight, CEILING(MAX(Weight)) MaxWeight FROM Products WHERE Id IN ({ins})").SingleOrDefaultAsync();
            }
            catch(Exception ex)
            {
                Debug.WriteLine(ex.Message);
            }
```

### Further technical details
EF Core version: 2.1.0-preview1-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Pro x64
IDE: Visual Studio 2017 15.7 Preview

**Comment by popcatalin81** [comment]
@glararan check your stack trace, the error comes from inside SQL Data Reader:

>>    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader

This means you're trying to read a SQL value into some .Net type, but it doesn't fit. Double check your data types.

Also instead of a giant IN clause, you can use table valued parameters which generally work allot better.

**Comment by glararan** [comment]
Data types inside database for Price and Weight is decimal(18, 2) which should be okay.. I'm using code first and Product entity has also decimal for Weight and Price.

Giant IN: I hear this first time... is there any example how to use IN list?

**Comment by ajcvickers** [comment]
@glararan Because of the way string interpolation works with EF the result of this is a query with one large string parameter containing all the values concatenated together. This is probably what is causing the exception. If your intention is to not do parameterization here (and you're happy that this won't expose any security issue) then just stop using string interpolation inside the FromSql call.

**Comment by glararan** [comment]
Oh awesome.. so solution is to write SQL into string variable which should be passed into FromSql.. nice, thanks
