### ISSUE TITLE
Test fail with 2.1-preview1-final spec tests

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#11394]
```
Test 'Microsoft.EntityFrameworkCore.Query.IncludeAsyncSqlCeTest.Include_collection_when_projection' failed: System.InvalidOperationException : Warning as error exception for warning 'Microsoft.EntityFrameworkCore.Query.IncludeIgnoredWarning': The Include operation for navigation '[c].Orders' is unnecessary and was ignored because the navigation is not reachable in the final query results. See https://go.microsoft.com/fwlink/?linkid=850303 for more information. To suppress this Exception use the DbContextOptionsBuilder.ConfigureWarnings API. ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.
	at Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`1.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, WarningBehavior warningBehavior, TParam arg, Exception exception)
	at Microsoft.EntityFrameworkCore.Internal.CoreLoggerExtensions.IncludeIgnoredWarning(IDiagnosticsLogger`1 diagnostics, IncludeResultOperator includeResultOperator)
	at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.LogIgnoredIncludes()
	at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, Boolean asyncQuery)
	at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, Boolean asyncQuery)
	at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
	at Microsoft.EntityFrameworkCore.Storage.Database.CompileAsyncQuery[TResult](QueryModel queryModel)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass22_0`1.<CompileAsyncQuery>b__0()
	at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
	at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddAsyncQuery[TResult](Object cacheKey, Func`1 compiler)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQuery[TResult](Expression query)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)
	at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression)
	at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
	at System.Linq.AsyncEnumerable.<Aggregate_>d__6`3.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at Microsoft.EntityFrameworkCore.Query.IncludeAsyncTestBase`1.<Include_collection_when_projection>d__26.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

### Steps to reproduce
I inherit from IncludeAsyncTestBase - oddly, this is not run by the SQL Server provider tests
Also happens with tests from IncludeTestBase

### Further technical details
EF Core version: 2.1-preview1-final
Database Provider: SQLCE

**Comment by smitpatel** [comment]
You need to use Include specific fixture which converts Ignored includes to logs.
https://github.com/aspnet/EntityFrameworkCore/blob/28479da1f8986a88fc8a067ceab1b9ea45afb637/test/EFCore.SqlServer.FunctionalTests/Query/IncludeSqlServerFixture.cs#L9-L13

**Comment by ErikEJ** [comment]
I already do that for the non asynchronous tests ! Closed too quickly...

**Comment by smitpatel** [comment]
Using branch 2-1-preview1-prep
In EntityFramewrok.SqlServerCompact.FunctionalTests project
`AsyncIncludeSqlCeTest` passed successfully.
62 passed, 0 failed, 0 skipped, took 8.29 seconds (xUnit.net 2.3.1 build 3858).

Updating `IncludeSqlCeTest` to use `IncludeSqlCeFixture`, it fails in some tests but no error is due to above exception.

Which branch/project/test giving above issue?

**Comment by ErikEJ** [comment]
Odd, I will have another look. You are in the correct place.

**Comment by ErikEJ** [comment]
@smitpatel Thanks for you help!
