### ISSUE TITLE
Navigation List Property in Owned Entity occur Exception

### ISSUE THREAD

**Issue by altmann** [dotnet/efcore#11440]
Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: Message: System.InvalidOperationException : The relationship from 'HaushaltsgemeinschaftMitglied' to 'Antrag.Haushaltsgemeinschaft#Haushaltsgemeinschaft.ZusaetzlicheMitglieder' is not supported because the owned entity type 'Antrag.Haushaltsgemeinschaft#Haushaltsgemeinschaft' cannot be on the principal side.

Stack trace: 
at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateDefiningNavigations(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__0(Object k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_1(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.<AddRangeAsync>d__79.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Fsw.Vita.Antraege.Endpoints.UI.Web.QueryHandlers.Tests.EditAntragQueryHandlerTests.<>c__DisplayClass3_0.<<Setup>b__0>d.MoveNext() in C:\Vsts\Git\Fsw.Vita.Antraege\src\Endpoints.UI.Web.QueryHandlers.Tests\EditAntragQueryHandlerTests.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Fsw.Vita.Antraege.Domain.Repositories.Infrastructure.DbContextHandler.<Execute>d__5.MoveNext() in C:\Vsts\Git\Fsw.Vita.Antraege\src\Domain.Repositories\Infrastructure\DbContextHandler.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Fsw.Vita.Antraege.Endpoints.UI.Web.QueryHandlers.Tests.EditAntragQueryHandlerTests.<Setup>d__3.MoveNext() in C:\Vsts\Git\Fsw.Vita.Antraege\src\Endpoints.UI.Web.QueryHandlers.Tests\EditAntragQueryHandlerTests.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\AsyncInvocationRegion.cs:line 113
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunAsyncMethod(MethodInfo method, TestExecutionContext context) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Commands\SetUpTearDownItem.cs:line 116
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUp(TestExecutionContext context) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Commands\SetUpTearDownItem.cs:line 69
   at NUnit.Framework.Internal.Commands.SetUpTearDownCommand.<>c__DisplayClass0_0.<.ctor>b__0(TestExecutionContext context) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Commands\SetUpTearDownCommand.cs:line 53
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.Execute(TestExecutionContext context) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Commands\BeforeAndAfterTestCommand.cs:line 57
Result Message:	System.InvalidOperationException : The relationship from 'HaushaltsgemeinschaftMitglied' to 'Antrag.Haushaltsgemeinschaft#Haushaltsgemeinschaft.ZusaetzlicheMitglieder' is not supported because the owned entity type 'Antrag.Haushaltsgemeinschaft#Haushaltsgemeinschaft' cannot be on the principal side.
```

### Steps to reproduce
see https://stackoverflow.com/questions/48111747/relationship-on-owned-type

### Further technical details
EF Core version: 2.0.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.6.2

**Comment by ajcvickers** [comment]
@altmann As the exception says, this is not supported on owned types. We don't plan to implement this because it doesn't align with the concept of owned types--if you are expecting differently can you elucidate in greater detail what your expectation is and how it aligns with owned types?

**Comment by altmann** [comment]
@ajcvickers We use DDD and therefore also ValueObjects. ValueObjects are represented via Owned Entities. I can't understand why a 1:1 navigation property in a Owned Entity is working but a 1:n navigation property is not working. We want to bring our domain model into code so for us this is unfortunately a show stopper using EF Core in our project. As temporary workaround we convert the Owned Entity to a real Entity but this is not what we want. Do you have any better workarounds for that?

My expectation was that the 1:n relation use as principal key the primary key of InboundRequest (=property Id). (see example in the link above)
