### ISSUE TITLE
Unable to create a null constant value in collection assignments

### ISSUE THREAD

**Issue by TomWouters** [dotnet/efcore#11450]
I am currently developing a framework, with extendable tables/relations etc...
The way it is done is by creating classes, Having extension records (eg class 1 has an extra field named x ), compiling the combination of the 2 to a new class, and creating new relationship types, to those new extended classes.  Then compiling those as a definition for entity framework.  This works perfectly.
Now there is an edge case where I'm requesting  an iqueryable, which contains class x with a collection of Y, which contains a class x, with a collection of y, which contains a class x, ....

In order to avoid endless recursion I want to stop after the second iteration of the collection.  so basically:

X.Col[Y].X  where in the final x, col[y] would be null or an empty list (don't really care either way, but it should not be translated into a sql select query).

There is a prerequisite requirement to entity framework, which dictates that if you have a new X with property assignments, if there is another new x with a new definition, all the properties of the first initialization definition have to be present.

So for me this means I have to create an expression with:

New class X(), Y = Select (z over table y)

and the second time:
New class X(), Y = null.

This is where the issue lies.  Entity framework doesn't accept the y = ((List<Y>)null).

The solution would be to not have to repeat the variable assignments if the class has been instantiated before (so EF should set null values to properties which aren't set), or there should be a way to create an expression where you can say y =  ((List<Y>)null) or a similar expression which has the same result.

The "remarkable" part is that empty assignments work in the base table, but once you reach a collection, and try to do null assignments inside, entity framework doesn't want to create those empty types.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:

Unable to create a null constant value of type 'System.Collections.Generic.List`1[[dbasics.CompanyData.Model.DebtorOpenItem, dbasics.CompanyData.Model, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]'. Only entity types, enumeration types or primitive types are supported in this context.

Stack trace:

   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.ConstantTranslator.TypedTranslate(ExpressionConverter parent, ConstantExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MemberInitTranslator.TypedTranslate(ExpressionConverter parent, MemberInitExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.ConditionalTranslator.TypedTranslate(ExpressionConverter parent, ConditionalExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MemberInitTranslator.TypedTranslate(ExpressionConverter parent, MemberInitExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateLambda(LambdaExpression lambda, DbExpression input)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateLambda(LambdaExpression lambda, DbExpression input, DbExpressionBinding& binding)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.OneLambdaTranslator.Translate(ExpressionConverter parent, MethodCallExpression call, DbExpression& source, DbExpressionBinding& sourceBinding, DbExpression& lambda)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.SelectTranslator.Translate(ExpressionConverter parent, MethodCallExpression call)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.SequenceMethodTranslator.Translate(ExpressionConverter parent, MethodCallExpression call, SequenceMethod sequenceMethod)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.TypedTranslate(ExpressionConverter parent, MethodCallExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.UnarySequenceMethodTranslator.Translate(ExpressionConverter parent, MethodCallExpression call)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.SequenceMethodTranslator.Translate(ExpressionConverter parent, MethodCallExpression call, SequenceMethod sequenceMethod)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.TypedTranslate(ExpressionConverter parent, MethodCallExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MemberInitTranslator.TypedTranslate(ExpressionConverter parent, MemberInitExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateLambda(LambdaExpression lambda, DbExpression input)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateLambda(LambdaExpression lambda, DbExpression input, DbExpressionBinding& binding)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.OneLambdaTranslator.Translate(ExpressionConverter parent, MethodCallExpression call, DbExpression& source, DbExpressionBinding& sourceBinding, DbExpression& lambda)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.SelectTranslator.Translate(ExpressionConverter parent, MethodCallExpression call)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.SequenceMethodTranslator.Translate(ExpressionConverter parent, MethodCallExpression call, SequenceMethod sequenceMethod)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.TypedTranslate(ExpressionConverter parent, MethodCallExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.Convert()
   at System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at dbasics.UnitTest.Storage.Sqlite.DatabaseTest.IQueryableTestStorageTest() in D:\tfs\net\dev\src\dbasics.UnitTest.Storage.Sqlite\DatabaseTest.cs:line 274
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Because of the compilation system mentioned above, it is virtually impossible for me to easily reproduce the code, so instead I'll dump the expression tree in a simple form.

.Call System.Linq.Queryable.Select(
    .Call .Constant<System.Data.Entity.Core.Objects.ObjectQuery`1[ns_FullTypes_.Gen_Debtor]>(System.Data.Entity.Core.Objects.ObjectQuery`1[ns_FullTypes_.Gen_Debtor]).MergeAs(.Constant<System.Data.Entity.Core.Objects.MergeOption>(AppendOnly))
    ,
    '(.Lambda #Lambda1<System.Func`2[ns_FullTypes_.Gen_Debtor,dbasics.CompanyData.Model.Debtor]>))

.Lambda #Lambda1<System.Func`2[ns_FullTypes_.Gen_Debtor,dbasics.CompanyData.Model.Debtor]>(ns_FullTypes_.Gen_Debtor $item)
{
    .New dbasics.CompanyData.Model.Debtor(){
        Code = $item.Code,
        CodeOriginal = $item.CodeOriginal,
        CreatedByContextId = $item.CreatedByContextId,
        AddressVisit = .If ($item.AddressVisit == null) {
            null
        } .Else {
            .New dbasics.CompanyData.Model.DebtorAddress(){
                Code = ($item.AddressVisit).Code,
                CodeOriginal = ($item.AddressVisit).CodeOriginal,
                CreatedByContextId = ($item.AddressVisit).CreatedByContextId
            }
        },
        DebtorOpenItems = .Call System.Linq.Enumerable.ToList(.Call System.Linq.Enumerable.Select(
                $item.DebtorOpenItems,
                .Lambda #Lambda2<System.Func`2[ns_FullTypes_.Gen_DebtorOpenItem,dbasics.CompanyData.Model.DebtorOpenItem]>))
    }
}

.Lambda #Lambda2<System.Func`2[ns_FullTypes_.Gen_DebtorOpenItem,dbasics.CompanyData.Model.DebtorOpenItem]>(ns_FullTypes_.Gen_DebtorOpenItem $item)
{
    .New dbasics.CompanyData.Model.DebtorOpenItem(){
        Code = $item.Code,
        DocumentsReferenceCode = $item.DocumentsReferenceCode,
        ActualDeliveryDate = $item.ActualDeliveryDate,
        DocumentsFilesReferences = $item.DocumentsFilesReferences,
        CodeOriginal = $item.CodeOriginal,
        CreatedByContextId = $item.CreatedByContextId,
        Debtor = .If ($item.Debtor == null) {
            null
        } .Else {
            .New dbasics.CompanyData.Model.Debtor(){
                Code = ($item.Debtor).Code,
                CodeOriginal = ($item.Debtor).CodeOriginal,
                CreatedByContextId = ($item.Debtor).CreatedByContextId,
                AddressVisit = .If (($item.Debtor).AddressVisit == null) {
                    null
                } .Else {
                    .New dbasics.CompanyData.Model.DebtorAddress(){
                        Code = (($item.Debtor).AddressVisit).Code,
                        CodeOriginal = (($item.Debtor).AddressVisit).CodeOriginal,
                        CreatedByContextId = (($item.Debtor).AddressVisit).CreatedByContextId
                    }
                },
                DebtorOpenItems = (System.Collections.Generic.List`1[dbasics.CompanyData.Model.DebtorOpenItem])null
            }
        }
    }
}

the issue lies with the second assignment of debtoropenitems. (DebtorOpenItems = (System.Collections.Generic.List`1[dbasics.CompanyData.Model.DebtorOpenItem])null)

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

### Further technical details
EF version: 6.2.0
Database: Provider:System.Data.SQLite.EF6
Operating system:  Windoes 10
IDE: Visual Studio 2017 15.6

**Comment by smitpatel** [comment]
This issue was moved to aspnet/EntityFramework6#508
