### ISSUE TITLE
SqlException: The operation 'MERGE' is not supported with memory optimized tables.

### ISSUE THREAD

**Issue by sepehr1014** [dotnet/efcore#11515]
Using the preview release, I get the following exception when adding multiple entities to a DbSet:

```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: The operation 'MERGE' is not supported with memory optimized tables.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__121_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__32.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__73.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
...
```

### Steps to reproduce
Add entities in a loop and save changes:

```c#
                        foreach (...)
                        {
                            var eventMessage = new Message
                            {
                                ...
                            };
                            db.Messages.Add(eventMessage);
                        }

                        await db.SaveChangesAsync();
                        transaction.Commit();
```

### Further technical details
EF Core version: 2.1.0-preview1-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows Server 2016
**Using in-memory tables in SQL Server 2017**

**Comment by divega** [comment]
@sepehr1014 can you please share a repro project or at least the relevant parts of the model?

@AndriySvyryd to investigate if we are missing anything in reverse engineering or if the user needs to tell us that the table is memory optimized.

**Comment by sepehr1014** [comment]
@divega  Sorry for the delay, this seems to be solved when using `builder.Entity<Message>().ForSqlServerIsMemoryOptimized();`

And here's our model:
```C#
public class Message
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Int64 Id { get; set; }

        public Int64 Conversation_Id { get; set; }

        [Required]
        [MaxLength(128)]
        public string User_Id { get; set; }

        public MessageType Type { get; set; }

        public string Text { get; set; }

        [MaxLength(260)]
        public string AttachmentPath { get; set; }

        public float AttachmentRatio { get; set; }

        [MaxLength(128)]
        public string ExclusiveTo_Id { get; set; }

        public bool IsDeleted { get; set; }

        public Int64? InReplyTo_Id { get; set; }

        [MaxLength(128)]
        public string ForwardedFrom_Id { get; set; }

        [Column(TypeName = "datetime2")]
        public DateTime PostDTO { get; set; } = DateTime.Now;
    }
```

**Comment by AndriySvyryd** [comment]
@sepehr1014 Did you create the model using reverse engineering (Scaffold-DbContext) or did you create the database from the model?

**Comment by sepehr1014** [comment]
@AndriySvyryd Actually we had created the database using EF 6 code first. Then we ported to EF core and just emptied the initial migration ...

**Comment by AndriySvyryd** [comment]
@sepehr1014 I see, then there's not much we can improve for this scenario.

**Comment by sepehr1014** [comment]
@AndriySvyryd I see. So what's the difference between tables created by EF core vs our table?

**Comment by AndriySvyryd** [comment]
@sepehr1014 EF6 wasn't aware of memory-optimized tables, so you had to configure it manually. But EF Core is able to create one with the configuration you provided.
You could try reverse engineering your database into a new project and compare the models to see if there are any other things missing.
