### ISSUE TITLE
normal insert is throwing me an 'A first chance exception of type 'System.Data.SqlClient.SqlException' occurred in System.Data.dll''

### ISSUE THREAD

**Issue by lite1294** [dotnet/efcore#11514]
sir kindly help me with this as i m quite new to c# and doing this data insertion but its sending me this error..

**coding**: 
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.SqlClient;

namespace WindowsFormsApplication4
{

    public partial class Form1 : Form
    {
        SqlConnection conn = new SqlConnection(@"Data Source=OBSCURIOUS\SQLSERVER2012;Initial Catalog=justadded;Integrated Security=True");
        SqlDataAdapter sda;
        SqlCommandBuilder scb;

        public Form1()
        {
            InitializeComponent();
            conn.Open();
            String query = "INSERT INTO stu (name,roll,email_id,contact,dob,gender) VALUES('" + textBox1.Text + "'," + textBox2.Text + ",'" + textBox3.Text + "'," + textBox4.Text + ",'" +  dateTimePicker1.Text  +  "','" + comboBox1.Text + "') ";
            SqlCommand cmd = new SqlCommand("Select * from stu", conn);
            //SqlDataAdapter sda = new SqlDataAdapter(query, conn);
         //   sda.SelectCommand.ExecuteReader();
           // conn.Close();
        }

        private void Insert_click(object sender, EventArgs e)
        {
          /*  conn.Open();
            String query = @"INSERT INTO signin (name,roll,email_id,contact,dob,gender) VALUES('" + textBox1.Text + "," + textBox2.Text + "," + textBox3.Text + "," + textBox4.Text + "," +  dateTimePicker1.Text  +  "," + comboBox1.Text + " ";
            SqlCommand cmd = new SqlCommand("Select * from signup", conn);
            SqlDataAdapter sda = new SqlDataAdapter(query, conn);
            sda.SelectCommand.ExecuteNonQuery();
            conn.Close();
            */

          //  conn.Open();
            String query = "INSERT INTO stu (name,roll,email_id,contact,dob,gender) VALUES('" + textBox1.Text + "'," + textBox2.Text + ",'" + textBox3.Text + "'," + textBox4.Text + ",'" + dateTimePicker1.Text + "','" + comboBox1.Text + "') ";
            //SqlCommand cmd = new SqlCommand(query, conn);
            SqlDataAdapter sda = new SqlDataAdapter(query, conn);
            sda.SelectCommand.ExecuteReader();
            conn.Close();
        }

**error**:
System.Data.SqlClient.SqlException occurred
  HResult=-2146232060
  Message=Invalid column name 'email_id'.
  Source=.Net SqlClient Data Provider
  ErrorCode=-2146232060
  Class=16
  LineNumber=1
  Number=207
  Procedure=""
  Server=OBSCURIOUS\SQLSERVER2012
  State=1
  StackTrace:
       at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
       at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
       at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
       at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
       at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
       at System.Data.SqlClient.SqlDataReader.get_MetaData()
       at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
       at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
       at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
       at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
       at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
       at System.Data.SqlClient.SqlCommand.ExecuteReader()
       at WindowsFormsApplication4.Form1.Insert_click(Object sender, EventArgs e) in c:\Users\asus\Documents\Visual Studio 2013\Projects\WindowsFormsApplication4\WindowsFormsApplication4\Form1.cs:line 49
  InnerException: 

database: 
![siub jksab](https://user-images.githubusercontent.com/12054054/38175350-ed864f38-35f8-11e8-88e0-d494d04afe47.JPG)

**Comment by lite1294** [comment]
![siub jksab](https://user-images.githubusercontent.com/12054054/38175412-aec10d82-35f9-11e8-8172-3c9141c1d152.JPG)

**Comment by lite1294** [comment]
![kghbujkbuiphjohbk](https://user-images.githubusercontent.com/12054054/38175420-e44d9eac-35f9-11e8-8e8c-532671ae97e9.JPG)

**Comment by divega** [comment]
@lite1294 for future reference, this issue is not related to this repo. That said, I just took a look at the screenshots you included and I can see that in your CREATE TABLE statement there is a column named `email` but there isn't any column named `email_id`, therefore your INSERT statements are incorrect. Hence the error you can see in the screenshot above: "Additional information: Invalid column name 'email_id'".

Hope this helps.
