### ISSUE TITLE
OwnedType with same property name as primary key causes error on migration

### ISSUE THREAD

**Issue by todd-skelton** [dotnet/efcore#11544]
I cannot use owned types that have an Id property. It will trigger an error on migrations. This is using dotnet core 2.1 preview1. I'm not sure if it works on previous versions.

```
Exception message: The keys {'Id'} on 'OwnedType' and {'Id'} on 'Entity' are both mapped to 'Entity.PK_Entity' but with different columns ({'OwnedTypeId'} and {'Id'}).
Stack trace:System.InvalidOperationException: The keys {'Id'} on 'OwnedType' and {'Id'} on 'Entity' are both mapped to 'Entity.PK_Entity' but with different columns ({'OwnedTypeId'} and {'Id'}).
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedKeysCompatibility(IReadOnlyList`1 mappedTypes, String tableName)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedTableCompatibility(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The keys {'Id'} on 'OwnedType' and {'Id'} on 'Entity' are both mapped to 'Entity.PK_Entity' but with different columns ({'OwnedTypeId'} and {'Id'}).
```

### Steps to reproduce
Create new console app with the following code.
Run command `dotnet ef migrations add InitialCreate` from commandline

```c#
using Microsoft.EntityFrameworkCore;
using System;

namespace EfCore2_1MigrationError
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }

    public class ApplicationDbContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=(local);Database=EfCore2_1Error;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Entity>(builder =>
            {
                builder.HasKey(e => e.Id);

                builder.OwnsOne(e => e.OwnedType, o => 
                {
                    o.Property(e => e.Id).HasColumnName("OwnedTypeId");
                });
            });
        }
    }

    public class Entity
    {
        public Guid Id { get; set; }
        public OwnedType OwnedType { get; set; }
    }

    public class OwnedType
    {
        public Guid Id { get; set; }
    }
}
```
csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.0-preview1-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.0-preview1-final" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.1.0-preview1-final" />
  </ItemGroup>

</Project>
```

### Further technical details
EF Core version: 2.1.0-preview1-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Pro
IDE: Visual Studio 2017 15.7.0 Preview 2

**Comment by divega** [comment]
@xKloc the call to `o.Property(e => e.Id).HasColumnName("OwnedTypeId")` here is the problem. By specifying that the `Id` property on the owned type need to map to a different column from the owner's `Id` property you have broken the model. If the owner and owned types share the table then the `Id` column has to be shared for both.

**Comment by xKloc** [comment]
The owners Id property is completely different than the owned typed Id property. I would assume the default table structure to be Id and OwnedType_Id. Why is that not the case?

I have a value object called Subject and Performer in my model. Those value objects hold the Id and name of whatever type they represent. I have to use a different property other than Id for those value objects?

**Comment by xKloc** [comment]
I was able to solve my problem after looking at the output of the migration using another name for my `OwnedType.Id`. I have to create a shadow property and configure it as a foreign key to the owner.
```c#
using Microsoft.EntityFrameworkCore;
using System;

namespace EfCore2_1MigrationError
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }

    public class ApplicationDbContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=(local);Database=EfCore2_1Error;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Entity>(builder =>
            {
                builder.HasKey(e => e.Id);

                builder.OwnsOne(e => e.OwnedType, o => 
                {
                    o.Property<Guid?>("EntityId");

                    o.Property(e => e.Id).HasColumnName("OwnedTypeId");

                    o.HasOne("EfCore2_1MigrationError.Entity")
                        .WithOne("OwnedType")
                        .HasForeignKey("EfCore2_1MigrationError.OwnedType", "EntityId");
                });
            });
        }
    }

    public class Entity
    {
        public Guid Id { get; set; }
        public OwnedType OwnedType { get; set; }
    }

    public class OwnedType
    {
        public Guid Id { get; set; }
    }
}
```

**Comment by divega** [comment]
>  I would assume the default table structure to be Id and OwnedType_Id. Why is that not the case?

Because the property names match and hence by convention they are assumed to be the foreign key and primary key governing the relationship between the owner and the owned type.

If it is not intended, then yes, you have to explicitly configure a separate property as the foreign key. 

Re 

``` C#
o.HasOne("EfCore2_1MigrationError.Entity")
                        .WithOne("OwnedType")
                        .HasForeignKey("EfCore2_1MigrationError.OwnedType", "EntityId");
```` 

In case you missed it, you can simply chain `HasForeignKey` after the call to `OwnsOne`.

**Comment by xKloc** [comment]
@divega Thanks for pointing out that simplification.
