### ISSUE TITLE
Query: include collection with predicate-like-thingy that needs client evaluation throws NRE

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#11567]
Repro using GearsOfWar model:

```cs
ctx.Squads.Include(s => s.Members).OrderBy(s => new { Answer = 42 })
```

exception:

```
System.NullReferenceException : Object reference not set to an instance of an object.
	at Microsoft.EntityFrameworkCore.Query.Internal.AnonymousObject.GetValue(Int32 index)
	at lambda_method(Closure , AnonymousObject )
	at System.Linq.Lookup`2.CreateForJoin(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
	at System.Linq.Enumerable.<JoinIterator>d__38`4.MoveNext()
	at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
	at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
	at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.IncludeCollection[TEntity,TRelated,TElement](Int32 includeId, INavigation navigation, INavigation inverseNavigation, IEntityType targetEntityType, IClrCollectionAccessor clrCollectionAccessor, IClrPropertySetter inverseClrPropertySetter, Boolean tracking, TEntity entity, Func`1 relatedEntitiesFactory, Func`3 joinPredicate)
	at lambda_method(Closure , QueryContext , Squad , Object[] )
	at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler._Include[TEntity](QueryContext queryContext, TEntity entity, Object[] included, Action`3 fixup)
	at lambda_method(Closure , Squad )
	at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
	at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

**Comment by smitpatel** [comment]
Title :trollface:

**Comment by maumar** [comment]
related to https://github.com/aspnet/EntityFrameworkCore/issues/10736

**Comment by smitpatel** [comment]
Ordering by client object like that is not supported in 3.x
