### ISSUE TITLE
OwnsOne throws 'Unable to determine the relationship represented by navigation property'

### ISSUE THREAD

**Issue by digogid** [dotnet/efcore#11698]
The modelBuilder<Usuario>(p => { p.OwnsOne(x => x.EnderecoResidencial)}) was working great. 
EnderecoResidencial class is a Value Object.

I did the Add-Migration command and it generates the expected files to run with Upgrade-Database.

But when I checked the file, I noted that I forget some configurations. So I came back to my modelBuilder and added what was needed.

The part that was missing was on another entity's modelBuilder. But suddenly the .OwnsOne mentioned before starts to throw:

```

System.InvalidOperationException: Unable to determine the relationship represented by navigation property 'Usuario.EnderecoResidencial' of type 'Endereco'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyMappingValidationConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to determine the relationship represented by navigation property 'Usuario.EnderecoResidencial' of type 'Endereco'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
```

I have pushed both on Git here: https://github.com/digogid/eStore.Sample/

Master branch will work, but it isn't complete. Ownsone-error will throw exception but it is what I really need to do.

**Comment by ajcvickers** [comment]
@digogid It looks like there are two classes called "Usuario" and two classes called "Endereco", one in the "PedidoContext" namespace and one in the "UsuarioContext" namespace. The one in the "UsuarioContext" namespace uses OwnsOne and seems to be working fine. The one in "PedidoContext" is not explicitly configured and EF cannot figure out the relationship by convention. This can be fixed by adding an explicit call to configure it--for example:
```C#
modelBuilder.Entity<Domain.PedidoContext.Usuario>(p =>
{
    p.OwnsOne(x => x.EnderecoResidencial, o =>
    {
        o.OwnsOne(c => c.Cidade);
    });
});
```
However, this then reveals further errors related to the mapping of owned types. For example, because Pagamento and Pedio are setup as owned they will gave a 1:1 mapping using their PK values and there will be one PK column in the table. But then, this code:
```C#
p.OwnsOne(x => x.Pedido, o =>
{
    o.Property(x => x.Id).HasColumnName("PedidoId");
});
```
attempts to map the PK column on the owned type to a different PK column than the owner. This is the point where I'm not sure what you intention is, but removing these namings makes the model build.

**Comment by digogid** [comment]
Hello @ajcvickers , in this piece of code I am trying to add a FK to of PedidoId inside my Pagamento table. So, as I am seeing, that not the right way to do it. Maybe I misunderstood some EF concepts.

I'll try again in another way. Thanks for your support.
