### ISSUE TITLE
2.1 preview2 Lazy Loading Exception

### ISSUE THREAD

**Issue by csharper2010** [dotnet/efcore#11693]
Lazy loading with the method described in the docs does not work any more with ef core 2.1 preview2. It worked with 2.1 preview1.
https://docs.microsoft.com/en-us/ef/core/querying/related-data#lazy-loading-without-proxies
(I used the delegate version without any dependency to EF Core).

```
Error message:
 System.InvalidOperationException : A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
Stack trace:
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.Load[TSource](IQueryable`1 source)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.Load(INavigation navigation, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.Internal.LazyLoader.Load(Object entity, String navigationName)
   at Demo.Business.Model.PocoLazyLoader.InternalLoad[TRelated](Object entity, TRelated& navigationField, String navigationName) in c:\spielwiese\dotnet\Demo\src\Demo.Business\Model\PocoLazyLoader.cs:line 29
   at Demo.Business.Model.PocoLazyLoaderExtensions.Load[TRelated](PocoLazyLoader lazyLoader, Object entity, TRelated& navigationField, String navigationName) in c:\spielwiese\dotnet\Demo\src\Demo.Business\Model\PocoLazyLoader.cs:line 48
   at Demo.Business.Model.Entity1.get_Entity2() in c:\spielwiese\dotnet\Demo\src\Demo.Business\Model\Entity1.cs:line 17
   at lambda_method(Closure , InternalEntityEntry )
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.RelationshipsSnapshot..ctor(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.EnsureRelationshipSnapshot()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntrySubscriber.SnapshotAndSubscribe(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTrackingFromQuery(IEntityType baseEntityType, Object entity, ValueBuffer& valueBuffer, ISet`1 handledForeignKeys)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityTrackingInfo.StartTracking(IStateManager stateManager, Object entity, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.StartTracking(Object entity, EntityTrackingInfo entityTrackingInfo)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.<>c__DisplayClass18_0`2.<_TrackEntities>b__0(TOut result)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
   at Demo.Infrastructure.Repository.BaseRepository`2.GetById(TID id) in C:\spielwiese\dotnet\Demo\src\Demo.Infrastructure\Repository\BaseRepository.cs:line 39
   at Demo.Business.Tests.Entity1RepositoryShould.TrackChanges() in C:\spielwiese\dotnet\Demo\src\test\Demo.Business.Tests\Entity1RepositoryShould.cs:line 79
```

### Steps to reproduce
Load an entity with injected LazyLoader-delegate having a property enabling the lazy loading exactly as described in the Link from the docs.

### Further technical details
EF Core version: 2.1-preview2-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio Code

**Comment by ajcvickers** [comment]
@csharper2010 Here's a simple console app using code directly copy/pasted from that article. It works fine for me--can you look at this and see what is different about your code so we can root cause what is causing the issue?
```C#
public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(
                new Blog
                {
                    Name = "MyBlog",
                    Posts = new List<Post>
                    {
                        new Post { Title = "One", Content = "A post." },
                        new Post { Title = "Two", Content = "Another post."  }
                    }
                });

            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            foreach (var blog in context.Blogs)
            {
                Console.WriteLine($"Blog: {blog.Name}");

                foreach (var post in blog.Posts)
                {
                    Console.WriteLine($"  Post: {post.Title}");
                }
            }
        }
    }
}

public static class PocoLoadingExtensions
{
    public static TRelated Load<TRelated>(
        this Action<object, string> loader,
        object entity,
        ref TRelated navigationField,
        [CallerMemberName] string navigationName = null)
        where TRelated : class
    {
        loader?.Invoke(entity, navigationName);

        return navigationField;
    }
}

public class Blog
{
    private ICollection<Post> _posts;

    public Blog()
    {
    }

    private Blog(Action<object, string> lazyLoader)
    {
        LazyLoader = lazyLoader;
    }

    private Action<object, string> LazyLoader { get; set; }

    public int Id { get; set; }
    public string Name { get; set; }

    public ICollection<Post> Posts
    {
        get => LazyLoader?.Load(this, ref _posts);
        set => _posts = value;
    }
}

public class Post
{
    private Blog _blog;

    public Post()
    {
    }

    private Post(Action<object, string> lazyLoader)
    {
        LazyLoader = lazyLoader;
    }

    private Action<object, string> LazyLoader { get; set; }

    public int Id { get; set; }
    public string Title { get; set; }
    public string Content { get; set; }

    public Blog Blog
    {
        get => LazyLoader?.Load(this, ref _blog);
        set => _blog = value;
    }
}

public class BloggingContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }
    public DbSet<Post> Posts { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(
            @"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
}
```

**Comment by csharper2010** [comment]
The following Code reproduces the StackOverflowException of #11692 
I don't know if there's an error in my mapping but it worked in 2.1-preview1. It's a mapping with unidirectional HasOne in a class hierarchy (one child class references another one of the same hierarchy).

But I assume the problems are related so I post it here where you already gave your working example with OneToMany-mapping.

```
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace Issues
{
    public class Program
    {
        public static async Task Main()
        {
            using (var context = new BloggingContext())
            using (var otherContext = new BloggingContext())
            {
                var product = new SimpleProduct("Adelholzener Mineralwasser 0.7l");
                product.DepositID = 3;

                int initialProductID = product.ID;

                await context.RootClassSet.AddAsync(product);

                int savedProductID = product.ID;

                var productBeforeSaveChanges = await context.RootClassSet.SingleOrDefaultAsync(a => a.ID == savedProductID);

                context.SaveChanges();

                int flushedProductID = product.ID;

                var productFromSameContext = await context.RootClassSet.SingleOrDefaultAsync(a => a.ID == flushedProductID);

                // next line produces StackOverflowException
                var productFromOtherContext = await otherContext.RootClassSet.SingleOrDefaultAsync(a => a.ID == flushedProductID);
            }
        }
    }

    public static class PocoLoadingExtensions
    {
        public static TRelated Load<TRelated>(
            this Action<object, string> loader,
            object entity,
            ref TRelated navigationField,
            [CallerMemberName] string navigationName = null)
            where TRelated : class
        {
            loader?.Invoke(entity, navigationName);

            return navigationField;
        }
    }
    public interface IWithID<TID>
        where TID : IEquatable<TID>
    {
        TID ID { get; }
    }

    public abstract class RootClass : IWithID<int>
    {
        protected RootClass(Action<object, string> lazyLoader)
        {
            LazyLoader = lazyLoader;
        }
        protected RootClass(string name, int fixedId = 0)
        {
            Name = name;
            _id = fixedId;
        }
        private int _id;
        public int ID => _id;
        [StringLength(50)]
        public string Name { get; set; }
        protected Action<object, string> LazyLoader { get; }
    }
    public class Deposit : RootClass
    {
        private Deposit(Action<object, string> lazyLoader) : base(lazyLoader)
        { }
        public Deposit(string name, decimal amount, int fixedId = 0) : base(name, fixedId: fixedId)
        {
            this.Amount = amount;
        }
        public decimal Amount { get; private set; }
    }
    public abstract class Product : RootClass
    {
        protected Product(Action<object, string> lazyLoader) : base(lazyLoader)
        { }
        public Product(string productName) : base(productName)
        { }
        public int? DepositID { get; set; }
        private Deposit _deposit;
        public Deposit Deposit
        {
            get => LazyLoader.Load(this, ref _deposit);
            set => _deposit = value;
        }
    }
    public class SimpleProduct : Product
    {
        private SimpleProduct(Action<object, string> lazyLoader) : base(lazyLoader)
        { }
        public SimpleProduct(string productName) : base(productName)
        { }
    }

    public class BloggingContext : DbContext
    {
        public DbSet<RootClass> RootClassSet { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            => optionsBuilder.UseSqlServer("Data Source=STA-NB016\\PTSQL; Initial Catalog=Issues; Integrated Security=SSPI");

        protected override void OnModelCreating(ModelBuilder modelBuilder) {
            modelBuilder.Entity<RootClass>().Property(a => a.ID).HasField("_id");
            modelBuilder.Entity<RootClass>().Property<string>("discriminator").HasMaxLength(1);
            var rootClassDiscriminator = modelBuilder.Entity<RootClass>().ToTable("BASE_Product").HasDiscriminator<string>("discriminator");
            rootClassDiscriminator.HasValue<SimpleProduct>("A");
            rootClassDiscriminator.HasValue<Deposit>("P");
            modelBuilder.Entity<Product>().HasBaseType<RootClass>();
            modelBuilder.Entity<SimpleProduct>().HasBaseType<Product>();
            modelBuilder.Entity<Deposit>().HasBaseType<RootClass>();
            modelBuilder.Entity<Deposit>().Property(p => p.Amount);
            modelBuilder.Entity<Product>().Property(a => a.DepositID);
            modelBuilder.Entity<Product>().HasOne(a => a.Deposit);
            modelBuilder.Entity<Deposit>().HasData(
                new[] {
                    new { Name = "Deposit Special", Amount = 0.15m, ID = 3 },
                }.Select(v => new { v.Name, Amount = v.Amount, v.ID, discriminator = "P", Aktiv = true })
                .ToArray()
            );
        }
    }
}
```
