### ISSUE TITLE
Unable to cast object of type 'ConcreteTypeMapping' to type 'Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping'

### ISSUE THREAD

**Issue by Bo-Yee-Woods** [dotnet/efcore#11704]
public abstract class MultiLangEntity
    {        
        [StringLength(3)]
        public string LanguageCode { get; set; }
        
        [ForeignKey("LanguageCode")]        
        public virtual Language Language { get; set; }

        [StringLength(50)]
        public virtual string Content { get; set; }
    }
    
    public class CountryDescription : MultiLangEntity
    {
        [ForeignKey("CountryCode")]
        public virtual Country Country { get; set; }

        [StringLength(3)]
        public string CountryCode { get; set; }        
    }

Initially, I use EF Core 2.0. The above code works. Then I realized lazy load only supported by EF Core 2.1. When I swift to "EF core 2.1.0-preview2-final", I encounter following exceptions. 

System.InvalidCastException: Unable to cast object of type 'ConcreteTypeMapping' to type 'Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping'.
   at Microsoft.EntityFrameworkCore.Metadata.RelationalPropertyAnnotations.get_ColumnType()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerTypeMapper.GetColumnType(IProperty property)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapper.FindMapping(IProperty property)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationalTypeMappingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)

**Comment by mgolois** [comment]
+1 
I'm getting the same error. I worked of EF  Core 2.0, but not with "EF core 2.1.0-preview2-final"

**Comment by ajcvickers** [comment]
@Bo-Yee-Woods @mgolois Can you provide a runnable project/solution or complete code listing that demonstrates the behavior you are seeing? Also, what database provider and version are you using?

**Comment by mgolois** [comment]
@ajcvickers I created a repo at https://github.com/mgolois/EFCore-ConcreteTypeMapping-Bug 
The database is pretty simple:
DatabaseName: Database1 and TableName: Table1

USE [Database1]

CREATE TABLE [dbo].[Table1]
(
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](max) NULL,
	[NameId] [int] NULL,
)

**Comment by ajcvickers** [comment]
@mgolois When using ASP.NET Core, you need to update to the latest .NET Core SDK, as described in the [ASP.NET Core 2.1 preview2 announcement](https://blogs.msdn.microsoft.com/webdev/2018/04/12/asp-net-core-2-1-0-preview2-now-available/). Currently you still have .NET Core 2.0 and ASP.NET Core 2.0 referenced, with only some EF packages updated to the 2.1 versions. This configuration will not work. Updating all the EF packages may work, but is not recommended--the recommended path is to install the new SDK.

**Comment by mgolois** [comment]
gotcha! 
I also see that in order to update to the latest .NET Core SDK, I have first to install at least Visual Studio Visual Studio 2017 15.7 Preview 1

**Comment by Bo-Yee-Woods** [comment]
@ajcvickers Oh no! To make lazy loading using proxy to work, do I also need to use .net core 2.1 sdk? I follow tutorials and cannot work, very sad!

**Comment by ajcvickers** [comment]
@Bo-Yee-Woods If you are using ASP.NET Core, then yes, that's the recommended approach.

**Comment by ajcvickers** [comment]
@Bo-Yee-Woods Which tutorials were you attempting to follow?

**Comment by Bo-Yee-Woods** [comment]
@ajcvickers the tutorial is https://docs.microsoft.com/en-us/ef/core/querying/related-data . I hope .net core 2.1 and EF core 2.1 go production soon, lazy loading is important

**Comment by MoyaSoftInk** [comment]
hi guys, I updated my sdk, I currently have version **2.1.300-preview2-008533**, but the problem still persists, my version of vs is **15.6.6.** Is there any news about it?

**Comment by ajcvickers** [comment]
@MoyaSoftInk  Can you provide a runnable project/solution or complete code listing that demonstrates the behavior you are seeing? Also, what database provider and version are you using?

**Comment by ajcvickers** [comment]
@MoyaSoftInk Can you provide a runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

**Comment by fpiazza99** [comment]
I get these same error messages when trying to add-migration and also when debugging

**Comment by PavelPikat** [comment]
It worked for me after I updated all my projects where I previously had EFCore installed to 2.1.0-preview2-final prerelease

**Comment by ajcvickers** [comment]
For anyone reading this thread: if you are seeing these errors, then it likely means you have package version mismatch, as has been described in previous posts. If you are still seeing this after updating either SDK (for ASP.NET Core apps) or all EF package versions (for other apps) then please post a project/solution that exhibits the behavior you are seeing.

**Comment by yob171182** [comment]
Hi MoyaSoftInk,

Did it work for you without having to install version 15.7 preview of Visual Studio?

**Comment by MoyaSoftInk** [comment]
Hi @yob171182
I have the version **15.6.7** and work fine

**Comment by MoyaSoftInk** [comment]
just update all package Microsoft.EntityFrameworkCore.XXXX and Microsoft.AspNetCore.XXXX to prerelease versions (2.1.0-preview2-final

![image](https://user-images.githubusercontent.com/26491009/39577624-d9669812-4eaf-11e8-9fb3-67bf86d09dbe.png)

**Comment by yob171182** [comment]
Me too....Thanks

On May 3, 2018 8:50 AM, "José Moya" <notifications@github.com> wrote:

Hi @yob171182 <https://github.com/yob171182>
I have the version *15.6.7* and work fine

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/aspnet/EntityFrameworkCore/issues/11704#issuecomment-386284368>,
or mute the thread

**Comment by MoyaSoftInk** [comment]
@yob171182  work fine?

**Comment by danroot** [comment]
I resolved this by ensuring all the Microsoft.EntityFrameworkCore.XXXX were updated.  I left the ASP.NET Core 2.0.5 and SDK at 2.0.  It got rid of this error and everything seems to work.  Is there some gotcha here I'm missing?

**Comment by badcommandorfilename** [comment]
Hi, I'm still getting this error on v2.1.0 stable of Microsoft.EntityFrameworkCore (also v2.1.0-preview2-final, 2.0.3)

``` csharp
        private readonly DbContext _context;
        private readonly DbSet<T> _set;

        public EntityDataSource(DbContext context)
        {
            _context = context;
            _set = _context.Set<T>(); //Error here
        }
```

I'm using an InMemory database with Dependency Injection:

``` csharp
        public void ConfigureServices(IServiceCollection services)
        {
            var connectionString = @"Server=(localdb)\mssqllocaldb;Database=EFProviders.InMemory;Trusted_Connection=True;ConnectRetryCount=0";
            
            services.AddDbContext<ModelContext>(
                options => options.UseSqlServer(connectionString));
```

And if it helps, the model in question is:
``` csharp
    public class Giving
    {
        [Key]
        public Int64 Id { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTimeOffset CreatedUTC { get; set; }
        public override string ToString()
        {
            return $"{Id}";
        }
    }
```

This is a fairly new project, there aren't any other models declared.

**Comment by ajcvickers** [comment]
For anyone reading this thread: if you are seeing these errors, then it likely means you have package version mismatch, as has been described in previous posts. If you are still seeing this after updating either SDK (for ASP.NET Core apps) or all EF package versions (for other apps) then please post a project/solution that exhibits the behavior you are seeing.

**Comment by dskotha** [comment]
Problem with the mismatch in the Versions. Issue was fixed when Updated with same Versions.

**Comment by RobThree** [comment]
I'm experiencing the same problem. I create a project, add the `MySql.Data.EntityFrameworkCore` NuGet package (8.0.11) and add `Microsoft.EntityFrameworkCore.Proxies` (2.1.1). Even the most simple object (Id + name) causes this exception as soon as I try to use the DBSet.

Note that I'm using **MySQL** in this particular project.

Exception: `Unable to cast object of type 'ConcreteTypeMapping' to type 'Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping'`

I tried updating to pre-release (newer) versions of the packages but these seem to be the latest.

Stacktrace:

```
   at Microsoft.EntityFrameworkCore.Metadata.RelationalPropertyAnnotations.get_ColumnType()
   at MySql.Data.EntityFrameworkCore.Storage.Internal.MySQLTypeMapper.GetColumnType(IProperty property)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapper.FindMapping(IProperty property)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationalTypeMappingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.Validate()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_1(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(IServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.CheckState()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
   at TestApp.Program.Main(String[] args) in C:\Users\XXX\Desktop\TestApp\Program.cs:line 13
```
