### ISSUE TITLE
Scaffolding - There is already an object named 'entity_name' in the database.

### ISSUE THREAD

**Issue by kiran-mahadev** [dotnet/efcore#11719]
Hi,

I read though the documentation in https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/ and created a **code first initial migration** using PowerShell command (Add-Migration). This step generated three files - 
- TimeStamp_Initial.cs
- TimeStamp_Initial.Designer.cs
- DbContextModelSnapshot.cs

I was able to successfully apply the migration to the database. Then I added a new entity and tried generating another migration. This step updated the DbContextModelSnapshot.cs file and produced two new files -

- TimeStamp_Update.cs
- TimeStamp_Update.Designer.cs

I then tried to apply the migrations but received an error. When I looked at the **Up method in TimeStamp_Update.cs**, I see the newly added table along with existing (all) tables that we created in the initial migration. Is this the expected behavior? Should I be manually removing the tables that are already existing in the database from the Up method? May be I'm missing something, kindly guide...

```
Exception message: There is already an object named 'entity_name' in the database.
```
### Further technical details
```
EF Core version: 2.0.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.6.6
```

**Comment by raullermen** [comment]
I'm having the same problem. How do you solve it?

**Comment by arfrix** [comment]
i had same problem and after three hour struggling i find out what's going on

in my case when i wanted to migrate for the first time in up() method the default code wants to create the tables that already existed so i got same error as you

to solve it , just delete dose code and write want you want . for example i wanted to add a column so i just write

migrationBuilder.AddColumn( name: "fieldName", table: "tableName", nullable: true);

**Comment by sanzor** [comment]
Hello i am facing the same issue.I am issuing commands using the `.NET-CLI` and i keep getting the error "The table already exists".
I am running :
```
dotnet ef migrations add Initial
dotnet ef update-database Initial
```

**Comment by ajcvickers** [comment]
@sanzor This is SQL Server telling you that the Files table already exists in the database.

**Comment by Brian611** [comment]
i have the same problem i add a new field to table and add new migration just fine but as soon as i run update i get error "There is already an object named 'tableName' in the database". 

Everytime i add a new migration with some change the Up() function brings the whole dbcontext all over again. I am not sure why spent 3 days on this.

**Comment by TheMuyu** [comment]
How can i solve this. I need to work with existsting database. I dont want to drop any table. I scaffold db to entities. and when trying to database update it says There is already an object named

**Comment by ruwentos** [comment]
Any news on this? Is still not working as expected.

**Comment by ajcvickers** [comment]
@ruwentos This is a closed issue. If you're hitting an issue, then please open a _new issue_ and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by PDSCMIS** [comment]
how to did you solve this issue ? 
Thanks

**Comment by Bat-Sheva-Sh** [comment]
anytihng new?
having the same error-
Failed executing DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE [Permissions] (
    [Id] int NOT NULL IDENTITY,
    [Name] nvarchar(max) NULL,
    [Description] nvarchar(max) NULL,
    CONSTRAINT [PK_Permissions] PRIMARY KEY ([Id])
);
Microsoft.Data.SqlClient.SqlException (0x80131904): There is already an object named 'Permissions' in the database.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:6837e8dc-4f46-46b1-bfa6-6bf5bb75b839
Error Number:2714,State:6,Class:16
There is already an object named 'Permissions' in the database.




another error is
after migration and buils- succeeded i'm having this warning-
An error occurred while accessing the Microsoft.Extensions.Hosting services. Continuing without the application service provider. Error: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: MyProject.Services.Interfaces.IRoomService Lifetime: Scoped ImplementationType: MyProject.Services.Services.RoomService': Unable to resolve service for type 'MyProject.Repositories.Interfaces.IRoomRepository' while attempting to activate 'MyProject.Services.Services.RoomService'.)

**Comment by ajcvickers** [comment]
@kiran-mahadev Please open a _new_ issue and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by Bat-Sheva-Sh** [comment]
thank you
i was on the wrong db
then i went to the right one
deleted all the tables and the migration_history
and it was ok

another question
i get 204 error when deletint with swagger
it did delete
but gave that error
what does it mean?
