### ISSUE TITLE
Query with large WHERE clause causes timeout exception

### ISSUE THREAD

**Issue by sezaru** [dotnet/efcore#11734]
I have a query that looks something like this:

    private static IQueryable<MultiframeModule> WhereAllFramesProperties(this IQueryable<MultiframeModule> query, ICollection<Frame> frames)
    {
        return frames.Aggregate(query, (q, frame) =>
        {
            return q.Where(p => p.Frames.Any(i => i.FrameData.ShaHash == frame.FrameData.ShaHash));
        });
    }

`MultiframeModule` and `Frame` have an many-to-many relation.

With that query I want to find a `MultiframeModule` that contains all frames inside the `frames` collection I sent as a parameter, for that I check the `ShaHash` parameter.

If `frames` contains 2 frames, then the generated SQL would be something like that:

    SELECT
       "Extent1"."MultiframeModuleId",
       "Extent1"."FrameIncrementPointer",
       "Extent1"."PageNumberVector" 
    FROM
       "public"."MultiframeModule" AS "Extent1" 
    WHERE
       EXISTS 
       (
          SELECT
             1 AS "C1" 
          FROM
             "public"."Frame" AS "Extent2" 
             INNER JOIN
                "public"."FrameData" AS "Extent3" 
                ON "Extent2"."FrameData_FrameDataId" = "Extent3"."FrameDataId" 
          WHERE
             "Extent1"."MultiframeModuleId" = "Extent2"."MultiframeModule_MultiframeModuleId" 
             AND "Extent3"."ShaHash" = @p__linq__0
       )
       AND EXISTS 
       (
          SELECT
             1 AS "C1" 
          FROM
             "public"."Frame" AS "Extent4" 
             INNER JOIN
                "public"."FrameData" AS "Extent5" 
                ON "Extent4"."FrameData_FrameDataId" = "Extent5"."FrameDataId" 
          WHERE
             "Extent1"."MultiframeModuleId" = "Extent4"."MultiframeModule_MultiframeModuleId" 
             AND "Extent5"."ShaHash" = @p__linq__1
       )
       LIMIT 2
    
    -- p__linq__0: '0' (Type = Int32, IsNullable = false)
    
    -- p__linq__1: '0' (Type = Int32, IsNullable = false)

But, if I have more frames, say 200 for example, then the call would throw an exception:

    Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

With stacktrace:

       at Npgsql.ReadBuffer.<Ensure>d__27.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Npgsql.NpgsqlConnector.<DoReadMessage>d__157.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
       at Npgsql.NpgsqlConnector.<ReadMessage>d__156.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
       at Npgsql.NpgsqlConnector.<ReadExpecting>d__163`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
       at Npgsql.NpgsqlDataReader.<NextResult>d__32.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Npgsql.NpgsqlDataReader.NextResult()
       at Npgsql.NpgsqlCommand.<Execute>d__71.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
       at Npgsql.NpgsqlCommand.<ExecuteDbDataReader>d__92.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
       at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
       at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
       at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
       at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)

So, is there some obvious reason why my query is failing? And how can I improve it to be able to do the query successfully?

**Comment by smitpatel** [comment]
This issue was moved to aspnet/EntityFramework6#525
