### ISSUE TITLE
Can not insert Data to table with a foreign key to a IdentityColumn, in ef core 2

### ISSUE THREAD

**Issue by AlexGruebel** [dotnet/efcore#11778]
I am try to insert data to a sql table with a foreign key to a IdentityColumn, but is giving me following Exception:

I have already ensured that the database is configured to generate values for this property (see code below)

```
Exception message:
System.InvalidOperationException: The property 'MID' on entity type 'CourseMeetingParticipant' has a temporary value. Either set a permanent value explicitly or ensure that the database is configured to generate values for this property.
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.Validate(ModificationCommand modificationCommand)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.<BatchCommands>d__8.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CourseMeetingMVC.Controllers.CourseController.<SignInToCourseMeeting>d__5.MoveNext() in /home/alexander/Workspace/DotNet/CourseMeeting/CourseMeetingMVC/Controllers/CourseController.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

### Steps to reproduce
The complete Solution: https://github.com/AlexGruebel/CourseMeeting

The relevant Parts:

My two Entities:

```c#

using System;
using System.Collections.Generic;

namespace CourseMeetingEntitiesLib.dbo
{
    public class CourseMeeting
    {
        public int MID{ get; set; }
        public int CID { get; set; }
        public Course Course { get; set; }
        public DateTime DateOfTheMeeting { get; set; }  
        public int MaxParticipants { get; set; }
        public IList<CourseMeetingParticipant> CourseMeetingParticipants { get; set; }
    }
}

```
I map the classes to two SQL-Server tables with the Fluent API:

```c#

modelBuilder.Entity<CourseMeeting>(cm =>
 {
                cm.HasKey(k => k.MID);

                cm.Property(p => p.MID)
                    .UseSqlServerIdentityColumn();

                cm.HasMany(m => m.CourseMeetingParticipants).WithOne(m => m.CourseMeeting);
                
            });


            modelBuilder.Entity<CourseMeetingParticipant>(c =>
            {    
                c.HasKey(k => new {k.MID, k.SUID});
            });
```

The Tables:

```sql

CREATE TABLE [dbo].[CourseMeetingParticipants](
	[MID] [int] NOT NULL,
	[SUID] [varchar](100) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CourseMeetingParticipants] ADD  CONSTRAINT [PK_CP] PRIMARY KEY CLUSTERED 
(
	[MID] ASC,
	[SUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CourseMeetingParticipants]  WITH CHECK ADD FOREIGN KEY([MID])
REFERENCES [dbo].[CourseMeetings] ([MID])
GO

CREATE TABLE [dbo].[CourseMeetings](
	[MID] [int] IDENTITY(0,1) NOT NULL,
	[CID] [int] NULL,
	[DateOfTheMeeting] [datetime2](7) NOT NULL,
	[MaxParticipants] [int] NOT NULL
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[CourseMeetings] ADD PRIMARY KEY CLUSTERED 
(
	[MID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CourseMeetings]  WITH CHECK ADD FOREIGN KEY([CID])
REFERENCES [dbo].[Courses] ([CID])
GO

--Example Data
insert into [CourseMeetingDB].[dbo].[Courses]
values(2, 'CookingCourse','learn basic cooking', '607c793b-f142-4e49-a364-555d0ecafd88')
insert into [CourseMeetingDB].[dbo].[CourseMeetings]
values(2,'20180506', 50)

```
The method to insert the Data:

```c#

        [HttpPost]
        [Authorize(Roles = "Student")]
        public async Task<IActionResult> SignInToCourseMeeting(int id){
            var participant = new CourseMeetingParticipant{
                    MID = id,
                    SUID = await _UserManger.GetUserIdAsync(await _UserManger.GetUserAsync(User)),
                };
            _db.CourseMeetingParticipants.Add(participant);
            await _db.SaveChangesAsync();
            return Redirect("/Course/Courses");
        }
```

### Further technical details
EF Core version: 2.0.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 & Ubuntu Mate 16.04
IDE: Visual Studio 2017 15.4 & VSCode

**Comment by ajcvickers** [comment]
@AlexGruebel I am able to reproduce this when the "id" value passed to SignInToCourseMeeting is zero. Is zero intended to be a valid PK for MID on CourseMeeting?

**Comment by AlexGruebel** [comment]
@ajcvickers yes zero is intended to be a valid PK.

**Comment by ajcvickers** [comment]
@AlexGruebel I am not able to reproduce the issue with values other than zero. Are there specific steps that you go through to reproduce in this case?

For the zero case, the reason it is failing is that the PK for CourseMeeting is setup to use store-generated values. This means that when an entity has a value which is the CLR default (zero in this case), it will get a temporary value until saved, and then a value from the database after save. So then when a new CourseMeetingParticipant is added and the value of the FK is zero, this is also treated in the same way--that is, it will get the value of the real PK after save. (On the other hand, if the value is not zero, then it should not get a temporary value, and the exception above should not be thrown.)

There are two "easy" ways to deal with this:
* Don't use zero as a valid PK value
* If you must use zero, then don't use store-generated keys. (For example, `cm.Property(p => p.MID).ValueGeneratedNever();`

If you need both zero as a PK and store-generated keys, then things get more complicated. I won't go into this unless it is needed.

**Comment by AlexGruebel** [comment]
@ajcvickers sorry for the confusion, it works now fine with other values. Thank you very much!

**Comment by jeubank12** [comment]
Without opening a new question, can you go into the "more complicated"?

I have npgsql backend on EF Core 2.1.1.  Table "Container" has a serial key property "Id", but there is a manually inserted row with "Id" = 0.  Table "Description" has a many-to-many relationship with "Container", a relationship which is stored in the normalized "DescriptionToContainer" table ("ContainerId", "DescriptionId").  I am unable to use the foreign key 0 to "Container" on a new insert to "DescriptionToContainer" in EF Core - this worked fine in EF6.
