### ISSUE TITLE
Unhandled Exception: System.ArgumentNullException: Value cannot be null. Parameter name: source

### ISSUE THREAD

**Issue by mitchellmaler** [dotnet/efcore#11805]
Describe what is not working as expected.
Trying to get a max value of a SQL Server datetime column using Linq.

If I run the sql directly using SSMS it returns fine. 

SELECT MAX(TimestampUtc) FROM dbo.Models;

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Queryable.OrderByDescending[TSource,TKey](IQueryable`1 source, Expression`1 keySelector)
   at MYCLASS3.<GetLatestBuildTimestampAsync>d__4.MoveNext() in MYCLASS3.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MYCLASS2.<Run>d__11.MoveNext() in MYCLASS2.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MYCLASS1.<Main>d__1.MoveNext() in MYCLASS1.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MYPROGRAM.Program.<Main>(String[] args)
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

Example makeup of my classes to reproduce.
```c#
public class Model
{
     [Key]
     [DatabaseGenerated(DatabaseGeneratedOption.None)]
     public long Id { get; set; }
     public DateTime TimestampUtc { get; set; }
}

public class ModelRepo
{
    public async Task<DateTime?> GetLatestTimestampAsync()
    {            
        DateTime? dateTime = await _dbContext
            .Models
            .Select(x => x.TimestampUtc)
            .MaxAsync();
    
        return dateTime;
    }
}

public class AppDbContext : DbContext
{
     public AppDbContext(DbContextOptions options) : base(options)
     {
            
     }
     protected override void OnModelCreating(ModelBuilder modelBuilder)
     {
          modelBuilder.Entity<Model>()
                .HasIndex(b => b.TimestampUtc)
                .IsUnique();
     }
     public DbSet<Model> Models;
}
```

### Further technical details
EF Core version: 2.0.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: MacOS

**Comment by mitchellmaler** [comment]
I wasn't declaring my models as fields. That was the issue.
