### ISSUE TITLE
2.1.300-preview2-008530: dotnet ef migrations remove causes NULL exception while Remove-Migration in PMC Works

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#11810]
Moved from https://github.com/dotnet/cli/issues/9142 filed by @mjgebhard

## Steps to reproduce
```
PS C:\Users\mgebhard\Source\Repos\SchoolFinance\Dpi.SchoolFinance.Dal> dotnet --version
2.1.300-preview2-008530

PS C:\Users\mgebhard\Source\Repos\SchoolFinance\Dpi.SchoolFinance.Dal> dotnet ef migrations add InsertSeedEddieLeaLookup
Migration -c ApplicationDbContext -o Data/Migrations/ApplicationDb  --startup-project ../Dpi.SchoolFinance.Idp
info: Microsoft.EntityFrameworkCore.Model[10607]
      Relationship from 'UserProfile' to 'ApplicationUser' not configured because there are multiple properties on one e
ntity type {'ApprovedBy', 'User'} that could be matched with the properties on the other entity type {'UserProfile'}.
info: Microsoft.EntityFrameworkCore.Model[10607]
      Relationship from 'ApplicationUser' to 'UserProfile' not configured because there are multiple properties on one e
ntity type {'UserProfile'} that could be matched with the properties on the other entity type {'ApprovedBy', 'User'}.
info: Microsoft.EntityFrameworkCore.Model[10601]
      The index {'UserId'} was not created as the properties are already covered by the index {'UserId', 'LoginProvider'
, 'Name'}.
info: Microsoft.EntityFrameworkCore.Model[10601]
      The index {'UserId'} was not created as the properties are already covered by the index {'UserId', 'RoleId'}.
info: Microsoft.EntityFrameworkCore.Model[10607]
      Relationship from 'ApplicationUser' to 'UserProfile' not configured because there are multiple properties on one e
ntity type {'UserProfile'} that could be matched with the properties on the other entity type {'ApprovedBy', 'User'}.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.0-preview1-28290 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFram
eworkCore.SqlServer' with options: None
Done. To undo this action, use 'ef migrations remove'

PS C:\Users\mgebhard\Source\Repos\SchoolFinance\Dpi.SchoolFinance.Dal> dotnet ef migrations remove -c ApplicationDbConte
xt --startup-project ../Dpi.SchoolFinance.Idp
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullR
eferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.RemoveMigration..ctor(OperationExecutor executor, Object re
sultHandler, IDictionary args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boo
lean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, Cultu
reInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture,
 Object[] activationAttributes)
   at Microsoft.EntityFrameworkCore.Tools.ReflectionOperationExecutor.Execute(String operationName, Object resultHandler
, IDictionary arguments)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid4[T0,T1,T2,T3](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg
3)
   at Microsoft.EntityFrameworkCore.Tools.OperationExecutorBase.InvokeOperationImpl(String operationName, IDictionary ar
guments)
   at Microsoft.EntityFrameworkCore.Tools.OperationExecutorBase.RemoveMigration(String contextType, Boolean force)
   at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsRemoveCommand.Execute()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Exception has been thrown by the target of an invocation.
PS C:\Users\mgebhard\Source\Repos\SchoolFinance\Dpi.SchoolFinance.Dal>

## Expected  behavior
Not to throw an NULL exception when executing 
dotnet ef migrations remove -c ApplicationDbContext --startup-project ../Dpi.SchoolFinance.Idp


## Actual behavior
the following CLI  command; dotnet ef migrations remove -c ApplicationDbContext --startup-project ../Dpi.SchoolFinance.Idp throws an exception.  

The PMC command works
Update-Database -Context ApplicationDbContext


## Environment data
`dotnet --info` output:
PS C:\Users\mgebhard\Source\Repos\SchoolFinance\Dpi.SchoolFinance.Dal> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-preview2-008530
 Commit:    822ae6d43a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview2-008530\

Host (useful for support):
  Version: 2.1.0-preview2-26406-04
  Commit:  6833f3026b

.NET Core SDKs installed:
  1.0.3 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0-preview1-005051 [C:\Program Files\dotnet\sdk]
  1.1.0-preview1-005077 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.3 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.102 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200-preview-007474 [C:\Program Files\dotnet\sdk]
  2.1.200-preview-007517 [C:\Program Files\dotnet\sdk]
  2.1.200-preview-007576 [C:\Program Files\dotnet\sdk]
  2.1.300-preview1-008174 [C:\Program Files\dotnet\sdk]
  2.1.300-preview2-008530 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview1-26216-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26406-04 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by ajcvickers** [comment]
@bricelam Sorry to drop more stuff on you, but can you investigate this as well?

**Comment by bricelam** [comment]
@mjgebhard Could you provide a copy of your solution (or a simplified, self-contained repro) that I can use to dig into this?

**Comment by bricelam** [comment]
Also, does it work if you upgrade to EF Core 2.1.0-preview2-final?

**Comment by mjgebhard** [comment]
My fault, CLI is working as expected after updating project file references to 2.1.0-preview2-final.  

After making the 2.1.0-preview2-final update one of the project started throwing a CS2017 C# Cannot specify /main if building a module or library.  After an internet search I found recommendations to delete the StartupObject node within project file; <StartupObject>Dpi.SchoolFinance.Idp.Program</StartupObject> Anyway removing the node.  The project builds and, as far as I can tell, is working as expected.

Thanks
