### ISSUE TITLE
Stateful provider across connections

### ISSUE THREAD

**Issue by pdrhsm** [dotnet/efcore#11824]
Creating a context connecting to Oracle 12g, then creating a new context connecting to Oracle 11g causes EF to generate invalid SQL. In this case, it is caused by the SingleOrDefault it seems.

Tied to this [issue](https://forums.devart.com/viewtopic.php?f=1&t=34749) over in the Devart forums.

```
----- Inner Stack Trace -----
   at Devart.Data.Oracle.az.a()
   at Devart.Data.Oracle.am.g()
   at Devart.Data.Oracle.am.f()
   at Devart.Data.Oracle.an.a()
   at Devart.Data.Oracle.c6.a(am A_0, Int32 A_1)
   at Devart.Data.Oracle.c6.a(Int32 A_0, bh A_1)
   at Devart.Data.Oracle.OracleCommand.InternalExecute(CommandBehavior behavior, IDisposable disposable, Int32 startRecord, Int32 maxRecords, Boolean nonQuery)
   at Devart.Common.DbCommandBase.ExecuteDbDataReader(CommandBehavior behavior, Boolean nonQuery)
   at Devart.Data.Oracle.Entity.ak.a(CommandBehavior A_0)
   at Devart.Common.Entity.cs.d(CommandBehavior A_0)
   at Devart.Data.Oracle.Entity.ak.b(CommandBehavior A_0)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_1`1.<CompileQueryCore>b__0(QueryContext qc)
```

### Steps to reproduce
 * Create a simple context
 * Connect to Oracle 12g database
 * Issue a SingleOrDefault on a entity
 * Do repeat with Oracle 11g database

### Further technical details
EF Core version: 2.0.1
Database Provider: Devart.Data.Oracle.EFCore
Operating system: Windows 10
IDE: Visual Studio 2017 15.6.6

**Comment by ajcvickers** [comment]
@pdrhsm This looks like an issue with the Devart provider. I would suggest opening an issue with them.

**Comment by pdrhsm** [comment]
@ajcvickers and when I did I was told, as you can see in the link, that they told me it was an EF Core issue. It would be great if you could give me something to take back to Devart if you really mean that this is on their end.

[Link again](https://forums.devart.com/viewtopic.php?f=1&t=34749), to the issue.

**Comment by ajcvickers** [comment]
@pdrhsm The example they give for SQL Server is flawed. The SQL Server provider can generate different SQL based on options turned on or off in the configuration. For example:
```C#
var optionsBuilder = new DbContextOptionsBuilder();
optionsBuilder.UseSqlServer(@"server=dbmssqlx64\mssql2016;initial catalog=test;user id=sa;");
var context = new ModelContext(optionsBuilder.Options);
var result = context.Dept.Skip(1).FirstOrDefault(); // success

var optionsBuilder2 = new DbContextOptionsBuilder();
optionsBuilder2
    .UseSqlServer(@"server=dbmssql\mssql2008;initial catalog=test;user id=sa;")
    .UseRowNumberForPaging();
var context2 = new ModelContext(optionsBuilder2.Options);
var result2 = context2.Dept.Skip(1).FirstOrDefault(); // success
```
The Devart provider should do something similar for their case.
