### ISSUE TITLE
Migrations crash when altering default value from value to sql

### ISSUE THREAD

**Issue by Wozbo** [dotnet/efcore#11837]
Describe what is not working as expected.

It looks like the default column value is not getting dropped when converting over from a discrete value to a sql computed value.  We are seeding some data, and then populating the data based on some information in the session.  I'd expect that changing from a value to sql should drop the default constraint before adding the default sql constraint.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
System.Data.SqlClient.SqlException (0x80131904): Column already has a DEFAULT bound to it.
Could not create constraint or index. See previous errors.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
migrationBuilder.AddColumn<int>(
                name: "Column",
                table: "Table",
                nullable: false,
                defaultValue: 1);

            migrationBuilder.AlterColumn<int>(
                name: "Column",
                table: "Table",
                nullable: false,
                defaultValueSql: "(CONVERT([int],session_context(N'{{SESSION_VARIABLE_GOES_HERE}}')))");
```

### Further technical details
EF Core version: 2.0.1
SQL Server 13.0.5026
Operating system: 
VS2017 Enterprise Editioni

**Comment by Wozbo** [comment]
After looking at the sql generated and tracing it back; I see that a separate part of the codebase is adding in a default keyed off the column.  As far as I can tell, not a bug.  Sorry!
