### ISSUE TITLE
Migrations: changing key type from string to Guid results in broken migration

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#11832]
Original code:
```C#
public class Blog
{
    public string Id { get; set; }
}

public class Program
{
    public static void Main()
    {
    }
}

public class BloggingContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
}
```
Initial migration:
```C#
public partial class Initial : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "Blogs",
            columns: table => new
            {
                Id = table.Column<string>(nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Blogs", x => x.Id);
            });
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "Blogs");
    }
}
```
Change key type to Guid:
```C#
public class Blog
{
    public Guid Id { get; set; }
}
```
Key-change migration:
```C#
public partial class KeyChange : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AlterColumn<Guid>(
            name: "Id",
            table: "Blogs",
            nullable: false,
            oldClrType: typeof(string));
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AlterColumn<string>(
            name: "Id",
            table: "Blogs",
            nullable: false,
            oldClrType: typeof(Guid));
    }
}
```
Run update-database:
```
PM> update-database
Applying migration '20180427000202_Initial'.
Applying migration '20180427000334_KeyChange'.
Failed executing DbCommand (32ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
DECLARE @var0 sysname;
SELECT @var0 = [d].[name]
FROM [sys].[default_constraints] [d]
INNER JOIN [sys].[columns] [c] ON [d].[parent_column_id] = [c].[column_id] AND [d].[parent_object_id] = [c].[object_id]
WHERE ([d].[parent_object_id] = OBJECT_ID(N'[Blogs]') AND [c].[name] = N'Id');
IF @var0 IS NOT NULL EXEC(N'ALTER TABLE [Blogs] DROP CONSTRAINT [' + @var0 + '];');
ALTER TABLE [Blogs] ALTER COLUMN [Id] uniqueidentifier NOT NULL;
System.Data.SqlClient.SqlException (0x80131904): The object 'PK_Blogs' is dependent on column 'Id'.
ALTER TABLE ALTER COLUMN Id failed because one or more objects access this column.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:0f72d2ce-88d6-4245-8733-05b6aa1e21b9
Error Number:5074,State:1,Class:16
The object 'PK_Blogs' is dependent on column 'Id'.
ALTER TABLE ALTER COLUMN Id failed because one or more objects access this column.
```

**Comment by ajcvickers** [comment]
Note: this is a common scenario for people using the ASP.NET Core Identity model.

**Comment by bricelam** [comment]
I think we rebuild some indexes and default constraints for similar reasons. This would require rebuilding the primary key and any foreign keys referencing it.

**Comment by ajcvickers** [comment]
I think we should try to fix it in 2.1. It's a pretty common scenario for Identity.

**Comment by divega** [comment]
Is there something in Identity in 2.1 that makes it more common than it used to be? AFAIR it has always been a pain if you decide to change the type of a key after the database was created. Feels like a significant risk to try to get this enhancement in 2.1.

**Comment by ajcvickers** [comment]
@divega Because this is broken even if an attempt is made to change the key before the database has been created--see in the repro above. And so far I have not been able to come up with any reasonable workaround--I think you would have to handcraft the correct migration, which would be extremely difficult. Even if we did it and pasted the migration to the docs it would be fragile because it would rely on there being no other changes to the model otherwise the hand-crafted migration would be incorrect.

**Comment by divega** [comment]
Even if you change the key and then you create the initial migration?

**Comment by ajcvickers** [comment]
The initial migration is created for you.

**Comment by ajcvickers** [comment]
This is covered by table rebuilds #329

**Comment by neil-timmerman** [comment]
This is still a problem.
