### ISSUE TITLE
Value Conversion Guid to string with Sql Identity 

### ISSUE THREAD

**Issue by marleyg** [dotnet/efcore#11867]
I have a Db which uses uniqueidentifier and the identity column in Sql.  However, using generated Protobuf as the entity which does not support GUID/UUID requires that string be used for the Id.  Value Conversion:

```C#
var converter = new ValueConverter<string, Guid>(
                v => new Guid(v),
                v => v.ToString());
```
Works for Select or Query stored procedures.  But breaks on insert/add.  

Have tried a number of combinations:  `assign Id =Guid.NewGuid().ToString()` +  `IdentityInsert=true;`  

```
Exception message: Unrecognized Guid format
Stack trace:
System.FormatException: Unrecognized Guid format.
   at System.Guid.GuidResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String failureArgumentName, Exception innerException)
   at System.Guid.GuidResult.SetFailure(ParseFailureKind failure, String failureMessageID)
   at System.Guid.TryParseGuid(String g, GuidStyles flags, GuidResult& result)
   at System.Guid..ctor(String g)
   at lambda_method(Closure , String )
   at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.<>c__DisplayClass3_0`2.<SanitizeConverter>b__0(Object v)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping.CreateParameter(DbCommand command, String name, Object value, Nullable`1 nullable)
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypeMappedRelationalParameter.AddDbParameter(DbCommand command, Object value)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBase.AddDbParameter(DbCommand command, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.CreateCommand(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
```
AND With ValueGeneratedOnAdd with null value, or no ValueGeneratedOnX and null identity (which is the default if both types were Guid);

```
Value generation is not supported for property 'LedgerAddress.Id' because it has a 'ValueConverter<string, Guid>' converter configured. Configure the property to not use value generation using 'ValueGenerated.Never' or 'DatabaseGeneratedOption.None' and specify explict values instead.
```
### Steps to reproduce

```c#
public class TableEntry{
            public string Id {get; set;}
}

protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var converter = new ValueConverter<string, Guid>(
                v => new Guid(v),
                v => v.ToString());
            
            modelBuilder
                .Entity<TableEntry>()
                .Property(e => e.Id)
                .HasConversion(converter);

private static string RegisterOnLedger(TableEntry tableEntry)
{
            var context = new MyDbContext();
            using (context)
            {
                try
                {
                    var te = new TableEntry{Id = Guid.NewGuid().ToString()};
                    te.MergeFrom(tableEntry);
                        
                    context.EnableIdentityInsert<TableEntry>();
                    context.TableEntries.Add(te);
                    context.SaveChanges();
                }
                catch (Exception exception){}
```
or
```C#
private static string RegisterOnLedger(TableEntry tableEntry)
{
            var context = new MyDbContext();
            using (context)
            {
                try
                {
                    context.TableEntries.Add(tableEntry);
                    context.SaveChanges();
                }
                catch (Exception exception){}

```

### Further technical details
EF Core version: Microsoft.EntityFrameworkCore.SqlServer 2.1.0-preview2-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: OSX
IDE: Visual Studio and Rider

**Comment by ajcvickers** [comment]
@marleyg The use of value generation in the case is tracked by #11597. However, this can be worked around by specifying the value generator in the converter. For example:
```C#
public class TableEntry
{
    public string Id { get; set; }
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var tableEntry = new TableEntry();
            context.Add(tableEntry);
            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            var tableEntry = context.Set<TableEntry>().Single();
            Console.WriteLine(tableEntry.Id);
        }
    }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        var converter = new ValueConverter<string, Guid>(
            v => new Guid(v),
            v => v.ToString());
              new ConverterMappingHints(valueGeneratorFactory: (p, t) => new GuidStringGenerator()));

        modelBuilder
            .Entity<TableEntry>()
            .Property(e => e.Id)
            .HasConversion(converter);
    }
}

public class GuidStringGenerator : ValueGenerator<string>
{
    private readonly SequentialGuidValueGenerator _guidGenerator 
        = new SequentialGuidValueGenerator();

    public override string Next(EntityEntry entry) 
        => _guidGenerator.Next(entry).ToString();

    public override bool GeneratesTemporaryValues 
        => false;
}
```
The downside to this is that only client-generated values are supported--in the case above, the sequential GUID generator is being used which uses the same algorithm as newsequentialid on SQL Server.

I am unable to repro the issue for the case where no value generation is being used. Here's my test code--hopefully you can use this as a starting point in creating a repro for the behavior you are seeing?

```C#
public class TableEntry
{
    public string Id { get; set; }
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var tableEntry = new TableEntry { Id = Guid.NewGuid().ToString() };
            context.Add(tableEntry);
            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            var tableEntry = context.Set<TableEntry>().Single();

            Console.WriteLine(tableEntry.Id);
        }
    }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        var converter = new ValueConverter<string, Guid>(
            v => new Guid(v),
            v => v.ToString());

        modelBuilder
            .Entity<TableEntry>()
            .Property(e => e.Id)
            .HasConversion(converter);
    }
}
```

**Comment by marleyg** [comment]
Thanks, should the Converter above be this?
``csharp
            var converter = new ValueConverter<string, Guid>(
                v => new Guid(v),
                v => v.ToString(),
                new ConverterMappingHints(valueGeneratorFactory: (p, t) => new GuidStringGenerator()));
```

**Comment by ajcvickers** [comment]
@marleyg Not for the case where no value generation is being used.
