### ISSUE TITLE
Query: invalid query produced for GroupBy with OrderBy and FirstOrDefault for a table splitting scenario

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#11871]
Repro:

```cs
                    var query = (from e in context.Set<Entity11818>()
                                 join a in context.Set<AnotherEntity11818>()
                                   on e.Id equals a.Id into grouping
                                 from a in grouping.DefaultIfEmpty()
                                 join m in context.Set<MaumarEntity11818>()
                                   on e.Id equals m.Id into grouping2
                                 from m in grouping2.DefaultIfEmpty()
                                 select new { aname = a.Name, mname = m.Name })
                                  .OrderBy(g => g.aname)
                                  .GroupBy(g => new { g.aname, g.mname }).FirstOrDefault()
                                  .Select(g => new { MyKey = g.aname, cnt = g.mname })
                                  .ToList();

        public class MyContext11818 : DbContext
        {
            public MyContext11818(DbContextOptions options)
                : base(options)
            {
            }

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                modelBuilder.Entity<Entity11818>().ToTable("Table");
                modelBuilder.Entity<AnotherEntity11818>().ToTable("Table");
                modelBuilder.Entity<MaumarEntity11818>().ToTable("Table");

                modelBuilder.Entity<Entity11818>()
                    .HasOne<AnotherEntity11818>()
                    .WithOne()
                    .HasForeignKey<AnotherEntity11818>(b => b.Id);

                modelBuilder.Entity<Entity11818>()
                    .HasOne<MaumarEntity11818>()
                    .WithOne()
                    .HasForeignKey<MaumarEntity11818>(b => b.Id);
            }
        }

        public class Entity11818
        {
            public int Id { get; set; }
            public string Name { get; set; }
        }

        public class AnotherEntity11818
        {
            public int Id { get; set; }
            public string Name { get; set; }
        }

        public class MaumarEntity11818
        {
            public int Id { get; set; }
            public string Name { get; set; }
        }
```

exception:

```
System.Data.SqlClient.SqlException : A column has been specified more than once in the order by list. Columns in the order by list must be unique.
	at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
	at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
	at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
	at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
	at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
	at System.Data.SqlClient.SqlDataReader.get_MetaData()
	at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
	at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
	at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
	at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
	at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
	at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
	at System.Data.Common.DbCommand.ExecuteReader()
	at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
	at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
	at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
	at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_GroupBy>d__23`3.MoveNext()
	at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
	at lambda_method(Closure )
	at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
	at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
	at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
	at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
	at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
```

**Comment by maumar** [comment]
QM:

```
(from Entity11818 e in DbSet<Entity11818>
join AnotherEntity11818 a in DbSet<AnotherEntity11818>
on [e].Id equals [a].Id into grouping
from AnotherEntity11818 a in 
    (from AnotherEntity11818 <generated>_1 in [grouping]
    select [<generated>_1]).DefaultIfEmpty()
join MaumarEntity11818 m in DbSet<MaumarEntity11818>
on [e].Id equals [m].Id into grouping2
from MaumarEntity11818 m in 
    (from MaumarEntity11818 <generated>_1 in [grouping2]
    select [<generated>_1]).DefaultIfEmpty()
order by [a].Name asc
select new <>f__AnonymousType23<string, string>(
    [a].Name, 
    [m].Name
))
.GroupBy(new <>f__AnonymousType23<string, string>(
        [a].Name, 
        [m].Name
    ), new <>f__AnonymousType23<string, string>(
        [a].Name, 
        [m].Name
    ))
.FirstOrDefault()
```

QP:

```
(QueryContext queryContext) => IEnumerable<IGrouping<<>f__AnonymousType23<string, string>, <>f__AnonymousType23<string, string>>> _InterceptExceptions(
    source: IEnumerable<IGrouping<<>f__AnonymousType23<string, string>, <>f__AnonymousType23<string, string>>> _ToSequence(() => IGrouping<<>f__AnonymousType23<string, string>, <>f__AnonymousType23<string, string>> FirstOrDefault(IEnumerable<IGrouping<<>f__AnonymousType23<string, string>, <>f__AnonymousType23<string, string>>> _GroupBy(
                source: IEnumerable<TransparentIdentifier<TransparentIdentifier<ValueBuffer, ValueBuffer>, ValueBuffer>> _ShapedQuery(
                    queryContext: queryContext, 
                    shaperCommandContext: SelectExpression: 
                        SELECT [e].[Name] AS [aname], [e].[MaumarEntity11818_Name] AS [mname]
                        FROM [Table] AS [e]
                        ORDER BY [e].[Name], [e].[MaumarEntity11818_Name], [aname], 
                    shaper: TypedCompositeShaper<TypedCompositeShaper<ValueBufferShaper, ValueBuffer, ValueBufferShaper, ValueBuffer, TransparentIdentifier<ValueBuffer, ValueBuffer>>, TransparentIdentifier<ValueBuffer, ValueBuffer>, ValueBufferShaper, ValueBuffer, TransparentIdentifier<TransparentIdentifier<ValueBuffer, ValueBuffer>, ValueBuffer>>), 
                keySelector: (TransparentIdentifier<TransparentIdentifier<ValueBuffer, ValueBuffer>, ValueBuffer> t3) => new <>f__AnonymousType23<string, string>(
                    string TryReadValue(t3.Outer.Inner, 0, AnotherEntity11818.Name), 
                    string TryReadValue(t3.Inner, 1, MaumarEntity11818.Name)
                ), 
                elementSelector: (TransparentIdentifier<TransparentIdentifier<ValueBuffer, ValueBuffer>, ValueBuffer> t3) => new <>f__AnonymousType23<string, string>(
                    string TryReadValue(t3.Outer.Inner, 0, AnotherEntity11818.Name), 
                    string TryReadValue(t3.Inner, 1, MaumarEntity11818.Name)
                )))), 
    contextType: QueryBugsTest+MyContext11818, 
    logger: DiagnosticsLogger<Query>, 
    queryContext: queryContext)
```

**Comment by smitpatel** [comment]
Client side GroupBy (FirstOrDefault after GroupBy causes execution). Hence not supported as per #17068
