### ISSUE TITLE
Migrating Migrations from .NET Framework to NET Core

### ISSUE THREAD

**Issue by Ruud-cb** [dotnet/efcore#11906]
Describe what is not working as expected.

Let me start out by saying that migrating an existing application to .NET Core is a pain in the ass. The current documents suggest to retrieve the model from the database. That works but that also generates a lot of `OnModelCreating` items, which would be a pain in the ass to make new adjustments. What I try to have is get all the migrations migrated as well, so that it is nicely in sync with the current state the application is in and sync with the application. See stackoverflow question: https://stackoverflow.com/questions/50157585/migrate-ef-migrations-to-efcore

So, I am trying to re-generate every migration by retrieving old changes of the application. The first one already got me into trouble.

Model:
```c#
    public class AllowedProductCombination
    {
        public int allowedProductCombinationId { get; set; }
        public int product1Id { get; set; }
        public int product2Id { get; set; }
        public int? productVariant1Id { get; set; }
        public int? productVariant2Id { get; set; }
        public bool product1Priority { get; set; }

        public Product Product1 { get; set; }
        public Product Product2 { get; set; }
        public ProductVariant Product1Variant { get; set; }
        public ProductVariant Product2Variant { get; set; }

        public override string ToString()
        {
            return "allowedProductCombiId:" + allowedProductCombinationId + " product1Id:" + product1Id + " productVariant1Id:" + productVariant1Id 
                + " - product2Id:" + product2Id + " productVariant2Id:" + productVariant2Id;
        }
    }
```

EF6 working model relation binding:

```c#
modelBuilder.Entity<AllowedProductCombination>().HasRequired(p1 => p1.Product1).WithMany(p => p.AllowedProductCombinations1).HasForeignKey(p1 => p1.product1Id);
modelBuilder.Entity<AllowedProductCombination>().HasRequired(p2 => p2.Product2).WithMany(p => p.AllowedProductCombinations2).HasForeignKey(p2 => p2.product2Id);
modelBuilder.Entity<AllowedProductCombination>().HasOptional(pv1 => pv1.Product1Variant).WithMany(pv => pv.AllowedProductCombinations1).HasForeignKey(pv1 => pv1.productVariant1Id);
modelBuilder.Entity<AllowedProductCombination>().HasOptional(pv2 => pv2.Product2Variant).WithMany(pv => pv.AllowedProductCombinations2).HasForeignKey(pv2 => pv2.productVariant2Id);

```
Converted to EFCore
```c#
 modelBuilder.Entity<AllowedProductCombination>().HasOne(pv1 => pv1.Product1Variant).WithMany(pv => pv.AllowedProductCombinations1).HasForeignKey(pv1 => pv1.productVariant1Id).OnDelete(DeleteBehavior.ClientSetNull);
modelBuilder.Entity<AllowedProductCombination>().HasOne(pv2 => pv2.Product2Variant).WithMany(pv => pv.AllowedProductCombinations2).HasForeignKey(pv2 => pv2.productVariant2Id).OnDelete(DeleteBehavior.ClientSetNull);
modelBuilder.Entity<AllowedProductCombination>().HasOne(p1 => p1.Product1).WithMany(p => p.AllowedProductCombinations1).HasForeignKey(p1 => p1.product1Id).IsRequired().OnDelete(DeleteBehavior.Cascade);
modelBuilder.Entity<AllowedProductCombination>().HasOne(p2 => p2.Product2).WithMany(p => p.AllowedProductCombinations2).HasForeignKey(p2 => p2.product2Id).IsRequired().OnDelete(DeleteBehavior.Cascade);
```

When executing the command in PowerShell:

```
dotnet ef migrations add initital
````

It generates this in the file 20180504112409_initital.cs

````c#
//rest not important for this issue
                    table.ForeignKey(
                        name: "FK_AllowedProductCombinations_Products_product1Id",
                        column: x => x.product1Id,
                        principalTable: "Products",
                        principalColumn: "productId",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_AllowedProductCombinations_Products_product2Id",
                        column: x => x.product2Id,
                        principalTable: "Products",
                        principalColumn: "productId",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_AllowedProductCombinations_ProductVariants_productVariant1Id",
                        column: x => x.productVariant1Id,
                        principalTable: "ProductVariants",
                        principalColumn: "productVariantId",
                        onDelete: ReferentialAction.Restrict);//note this
                    table.ForeignKey(
                        name: "FK_AllowedProductCombinations_ProductVariants_productVariant2Id",
                        column: x => x.productVariant2Id,
                        principalTable: "ProductVariants",
                        principalColumn: "productVariantId",
                        onDelete: ReferentialAction.Restrict);//note this
````

So it does not do what I have told the OnModelCreating, the designer, which is for some reason next to it and not "within it":
![image](https://user-images.githubusercontent.com/10037514/39626046-aa5b1ac4-4fa0-11e8-99a5-2f492594e737.png)

Generates this:

```c#
                    b.HasOne("Babywatcher.Core.Data.Entities.ProductVariant", "Product1Variant")
                        .WithMany("AllowedProductCombinations1")
                        .HasForeignKey("productVariant1Id");

                    b.HasOne("Babywatcher.Core.Data.Entities.ProductVariant", "Product2Variant")
                        .WithMany("AllowedProductCombinations2")
                        .HasForeignKey("productVariant2Id");
````

So it is missing the `.OnDelete()`

when I execute ```dotnet ef database update``` it throws an error, even after inserting the OnDelete myself like so: ```.OnDelete(DeleteBehavior.ClientSetNull);``` it throws the same error.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```c#
Exception message: Failed executing DbCommand (20ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
CREATE TABLE [AllowedProductCombinations] (
    [allowedProductCombinationId] int NOT NULL IDENTITY,
    [product1Id] int NOT NULL,
    [product1Priority] bit NOT NULL,
    [product2Id] int NOT NULL,
    [productVariant1Id] int NULL,
    [productVariant2Id] int NULL,
    CONSTRAINT [PK_AllowedProductCombinations] PRIMARY KEY ([allowedProductCombinationId]),
    CONSTRAINT [FK_AllowedProductCombinations_Products_product1Id] FOREIGN KEY ([product1Id]) REFERENCES [Products] ([productId]) ON DELETE CASCADE,
    CONSTRAINT [FK_AllowedProductCombinations_Products_product2Id] FOREIGN KEY ([product2Id]) REFERENCES [Products] ([productId]) ON DELETE CASCADE,
    CONSTRAINT [FK_AllowedProductCombinations_ProductVariants_productVariant1Id] FOREIGN KEY ([productVariant1Id]) REFERENCES [ProductVariants] ([productVariantId]) ON DELETE SET NULL,
    CONSTRAINT [FK_AllowedProductCombinations_ProductVariants_productVariant2Id] FOREIGN KEY ([productVariant2Id]) REFERENCES [ProductVariants] ([productVariantId]) ON DELETE SET NULL
);
Stack trace:
System.Data.SqlClient.SqlException (0x80131904): Introducing FOREIGN KEY constraint 'FK_AllowedProductCombinations_Products_product2Id' on table 'AllowedProductCombinations' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.
Could not create constraint or index. See previous errors.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:6788fabb-a7b9-4ea5-a962-777d811e82df
Error Number:1785,State:0,Class:16
Introducing FOREIGN KEY constraint 'FK_AllowedProductCombinations_Products_product2Id' on table 'AllowedProductCombinations' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.
Could not create constraint or index. See previous errors.

```

### Steps to reproduce
Create a .NET Standard project.
Make it compatible for NETCore:
````
  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.0;netstandard2.0</TargetFrameworks>
  </PropertyGroup>
````
Installed packages:

```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="2.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.2" />
  </ItemGroup>
```
CLI added:
```
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.2" />
  </ItemGroup>
```

Then just insert model, the DatabaseContext that uses IdentityDbContext from Microsoft.AspNetCore.Identity.EntityFrameworkCore

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF Core version: 2.0.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10, Visual Studio 2017 Enterprise, MSSQLLocalDB v13
connection string, if important, in DatabaseContext:

```c#
  protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseSqlServer(@"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=newDatabase;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False", 
                    providerOptions => providerOptions.CommandTimeout(60))
                .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
            base.OnConfiguring(optionsBuilder);
        }
```

IDE: (e.g. Visual Studio 2017 15.4)

**Comment by ajcvickers** [comment]
@Ruud-cb A few questions:
* Why is it that you want to recreate all the migrations?
* When you say, "So it does not do what I have told the OnModelCreating" do you mean because the onDelete behavior is set to Restrict? If so, this is correct. The "client" part of ClientSetNull has no meaning on the database, so they get the normal behavior for optional relationships in the database, which is Restrict.
* When you sat, "So it is missing the .OnDelete()" it looks like you are referring to the model snapshot. It's possible that these should be there - @bricelam may be able to confirm. However, I don't see this actually causing any issues.
* With regard to the cascade cycles, this is an issue with SQL Server and was the same in EF6. What does the EF6 database look like with respect to these constraints?

**Comment by bricelam** [comment]
We could generate `.OnDelete(DeleteBehavior.ClientSetNull)`. 😏 We could also generate `.ValueGeneratedNever()` on every property...

lol, not sure if we should but it shouldn't be causing any functional issues since it's the default (without conventions)

**Comment by Ruud-cb** [comment]
Hi @ajcvickers 
- Today I will be testing if 1 single migration will work as well, but in some migrations manual adjustments have been made (like insert default values). So it would be the most ideal solution to automatically refactor the current migrations, which seems to be not possible.
- I would expect that the settings I've set in the `OnModelCreating` would also be included in the migrations, but apparently Restrict is a good representation of what I have put in OnModelCreating.

 Well, eventually this seems to much work, looks like the most easiest solution is to generate a new database and migrate all the data to the new database. Something not really convenient, but to much work to do it in any other way... -1's for starting out with an existing application/database in EFCore.
