### ISSUE TITLE
ToListAsync throws InvalidCastException

### ISSUE THREAD

**Issue by vladimirlapacek** [dotnet/efcore#11954]
I am using ASPNet Identity and trying to get a result set containing Users with their respective claims. While the data model is not leveraging navigational properties. I created a LINQ query to give me the desired result. Since upgrade to dotnet (EF) 2.1 (preview + rc1), the query started to throw an `InvalidCastException`.

```
Exception message: WhereSelectEnumerableAsyncIterator`2[<>f__AnonymousType41`2[Identity2.Models.ApplicationUser,Microsoft.AspNetCore.Identity.IdentityUserClaim`1[System.String]],System.Security.Claims.Claim]' to type 'System.Collections.Generic.IEnumerable`1[System.Security.Claims.Claim]

Stack trace:
   at lambda_method(Closure , IGrouping`2 )
   at System.Linq.AsyncEnumerable.<>c__DisplayClass354_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.Aggregate_[TSource,TAccumulate,TResult](IAsyncEnumerable`1 source, TAccumulate seed, Func`3 accumulator, Func`2 resultSelector, CancellationToken cancellationToken)
   at Identity2.Services.TimeAwareUserStore.GetUsersUpdatedSinceAsync(DateTime since) in /Users/vl185018/dev/meine/portal/idm/identity/Services/TimeAwareUserStore.cs:line 45
   at Identity2.Controllers.UsersController.Get(DateTime since) in /Users/vl185018/dev/meine/portal/idm/identity/Controllers/UsersController.cs:line 44
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 72
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Steps to reproduce
Following is the code snippet where the problem occurs. If necessary, I can create a stub project. This used to work with EF Core 2.0. When I replace `await query.ToListAsync()` with `query.ToList()` it works even with EF Core 2.1 RC1.

```c#
            var query = from user in Users
                        join claim in UserClaims on user.Id equals claim.UserId into UserClaims
                        from claim in UserClaims.DefaultIfEmpty()

                        where user.UpdatedAt > since
                        select new { User = user, Claim = claim } into userclaim
                        
                        group userclaim by userclaim.User into g
                        select new Tuple<ApplicationUser, IEnumerable<Claim>>(
                            g.Key,
                            g.Where(x => x.Claim != null).Select(x => x.Claim.ToClaim()));

            return await query.ToListAsync();
```

### Further technical details
EF Core version: 2.1.0-rc1-final
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL 2.1.0-rc1
Operating system: MacOS
IDE: VS Code 1.23.0

**Comment by anpete** [comment]
@vladimirlapacek It would be great if you can create a repro for this.

**Comment by ajcvickers** [comment]
Triage: punting this to 2.2 since the workaround of using a sync query seems reasonable in this case.

**Comment by smitpatel** [comment]
Client side GroupBy is not supported #17068
