### ISSUE TITLE
Scaffold-DbContext not correctly configuring auto incrementing primary key in from Sqlite database

### ISSUE THREAD

**Issue by DanNeely** [dotnet/efcore#11961]
I'm using EF.Core scaffold to create a datamodel for a DB with an auto increment primary key but the context is being generated with the key annotated with ValueGeneratedNever() instead of ValueGeneratedOnAdd().  As a result EF framework requires each record to have a primary key set instead of allowing the DB to set it.

### Steps to reproduce

Create an SQLite DB with this table:

```sql
CREATE TABLE "LastSyncTime" 
( 
    `ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, 
    `SyncTime` TEXT NOT NULL, 
    `TableUpdated` TEXT NOT NULL 
)
```

In the package manager console run:  

```
Scaffold-DbContext "DataSource=MyDatabase.sqlite;" Microsoft.EntityFrameworkCore.Sqlite -OutputDir Models -force
```

Examine the context class, it generates with:

```c#
modelBuilder.Entity<LastSyncTime>(entity =>
{
    entity.HasIndex(e => e.Id)
        .IsUnique();

    entity.Property(e => e.Id)
        .HasColumnName("ID")
        .ValueGeneratedNever();

    entity.Property(e => e.SyncTime).IsRequired();

    entity.Property(e => e.TableUpdated).IsRequired();
});
```

ValueGeneratedNever() should be ValueGeneratedOnAdd()

### Further technical details
EF Core version: (found in project.csproj or packages.config) 2.1.0-rc1-final  (also happens in 2.0.2)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.Sqlite)
Operating system:  Win 10 1709
IDE: (e.g. Visual Studio 2017 15.6.3)

**Comment by Joe4evr** [comment]
Possibly related, also in SQLite. I found out that with my entity:
```cs
public class Account
{
    [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    public int Balance { get; set; }
}
```
giving `Balance` a default value in `OnModelCreating`:
```cs
modelBuilder.Entity<Account>()
    .Property(ac => ac.Balance)
    .HasDefaultValue(1500);
```
scaffolds the following in a migration:
```cs
migrationBuilder.CreateTable(
    name: "Accounts",
    columns: table => new
    {
        Id = table.Column<int>(nullable: false)
            .Annotation("Sqlite:Autoincrement", true),
        Balance = table.Column<int>(nullable: false, defaultValue: 1500)
            .Annotation("Sqlite:Autoincrement", true) //WTF?
    });
```
Why does the scaffolding think that the second column needs auto-increment?

Commenting out the bit in `OnModelCreating` doesn't emit the annotation for the `Balance` column to the migration scaffold.

**Comment by jjung89** [comment]
I have the same problem with GUID.
`[Id]        UNIQUEIDENTIFIER NOT NULL`

**Comment by codenesium** [comment]
I'm seeing this as well but with the error AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY. My database looks right. It looks like whatever is generating the SQL is trying to put auto increment on the wrong field. 

```
Microsoft.EntityFrameworkCore.Database.Transaction:Debug: Beginning transaction with isolation level 'Serializable'.
Microsoft.EntityFrameworkCore.Database.Command:Debug: Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE "Device" (
    "id" INTEGER NOT NULL CONSTRAINT "PK_Device" PRIMARY KEY AUTOINCREMENT,
    "name" varchar(90) NULL,
    "publicId" uniqueidentifier NOT NULL
);
Microsoft.EntityFrameworkCore.Database.Command:Information: Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE "Device" (
    "id" INTEGER NOT NULL CONSTRAINT "PK_Device" PRIMARY KEY AUTOINCREMENT,
    "name" varchar(90) NULL,
    "publicId" uniqueidentifier NOT NULL
);
Microsoft.EntityFrameworkCore.Database.Command:Debug: Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE "DeviceAction" (
    "deviceId" INTEGER NOT NULL,
    "id" int NOT NULL CONSTRAINT "PK_DeviceAction" PRIMARY KEY AUTOINCREMENT,
    "name" varchar(90) NULL,
    "value" varchar(4000) NULL,
    CONSTRAINT "FK_DeviceAction_Device_deviceId" FOREIGN KEY ("deviceId") REFERENCES "Device" ("id") ON DELETE CASCADE
);
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.0\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.0\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.EntityFrameworkCore.Database.Command:Error: Failed executing DbCommand (28ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE "DeviceAction" (
    "deviceId" INTEGER NOT NULL,
    "id" int NOT NULL CONSTRAINT "PK_DeviceAction" PRIMARY KEY AUTOINCREMENT,
    "name" varchar(90) NULL,
    "value" varchar(4000) NULL,
    CONSTRAINT "FK_DeviceAction_Device_deviceId" FOREIGN KEY ("deviceId") REFERENCES "Device" ("id") ON DELETE CASCADE
);

Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.EntityFrameworkCore.Relational.dll
SQLite Error 1: 'AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY'.

The thread 0x59d4 has exited with code 0 (0x0).
An exception of type 'Microsoft.Data.Sqlite.SqliteException' occurred in Microsoft.EntityFrameworkCore.Relational.dll but was not handled in user code
SQLite Error 1: 'AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY'.

```

**Comment by chrisbecke** [comment]
Ran into the same issue with EFCore 2.1.2

    dotnet ef dbcontext scaffold ... -f -d -v

renders a PRIMARY KEY AUTOINCREMENT field as a ValueGeneratedNever in the generated DbContext, and the reverse operation

    dotnet ef migrations add ...

generates PRIMARY KEY AUTOINCREMENT columns in the SQLite db where the property either has no ValueGenerated... at all, or is explicitly ValueGeneratedNever().

Looking forward to 2.2.0 I guess.

**Comment by JeremyFerreira** [comment]
Still no fixes for this `ValueGeneratedNever()` problem ?

**Comment by Sina-Soltani** [comment]
I have a problem with Auto Increment when a table has more than one primary key column.

Model:

```csharp
public class Product
{
    public int Id { get; set; }
    public int Tr {get; set; }
}
```

Configuration:
```csharp
modelBuilder.Entity<Product>()
                .HasKey(model => new { model.Id, model.Tr });

modelBuilder.Entity<Product>()
                .Property(model => model.Id)
                .ValueGeneratedOnAdd();
```

which creates this:
```
CREATE TABLE "Products" (
    "Id" INTEGER NOT NULL,
    "Tr" INTEGER NOT NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id", "Tr")
)
```

As you see, the Id column is not AutoIncrement. But if I change the configuration to have only one primary key, then it works!

**Comment by IOrlandoni** [comment]
Problem also exists while using SQL Server, not just Sqlite.

**Comment by jsnells1** [comment]
Any updates on this?

**Comment by ErikEJ** [comment]
Willing to take a PR for this?

**Comment by bricelam** [comment]
@ErikEJ Of course! It might depend on #10228
