### ISSUE TITLE
NRE in IncludeLoadTreeNodeBase with Concat of different entities converted to a common interface

### ISSUE THREAD

**Issue by corruptmem** [dotnet/efcore#12065]
I have two entities that share a common interface. If I querying them then Concat/Cast them into a single queryable of the common interface, this causes various issues.

In particular, if I OrderBy, I get the following exception:
```
Exception message: System.NullReferenceException: Object reference not set to an instance of an object.
Stack trace:
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.IncludeLoadTreeNodeBase.Compile(QueryCompilationContext queryCompilationContext, QueryModel queryModel, Boolean trackingQuery, Boolean asyncQuery, Int32& collectionIncludeId, QuerySourceReferenceExpression targetQuerySourceReferenceExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.IncludeLoadTree.Compile(QueryCompilationContext queryCompilationContext, QueryModel queryModel, Boolean trackingQuery, Boolean asyncQuery, Int32& collectionIncludeId)
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.CompileIncludes(QueryModel queryModel, Boolean trackingQuery, Boolean asyncQuery)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, Boolean asyncQuery)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, Boolean asyncQuery)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
   at System.Linq.AsyncEnumerable.<Aggregate_>d__6`3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BugRepro.Program.<Main>d__0.MoveNext() in c:\users\cameron.harris\documents\visual studio 2017\Projects\BugRepro\BugRepro\Program.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BugRepro.Program.<Main>()
```

I am aware that I am using LINQ operators that are unsupported and will be evaluated locally, but should I expect it to either all be evaluated locally, or to get a sensible error message?

### Steps to reproduce
Code is in a gist here: https://gist.github.com/corruptmem/80c673a629dd3e0ce26a360ae1218d47

Note that trying various permutations of these operations will cause it to misbehave in various other ways:

* Cast to object instead of IThing, and removing OrderBy causes the program to run but to fail to fetch the Relation property for the foo query.
* Removing the Includes causes ``System.ArgumentException: Property 'Int32 Id' is not defined for type 'System.Object'``
* Removing the OrderBy causes ``System.ArgumentException: Expression of type 'System.Collections.Generic.IAsyncEnumerable`1[System.Object]' cannot be used for return type 'System.Collections.Generic.IAsyncEnumerable`1[BugRepro.IThing]'``

### Further technical details
EF Core version: 2.1.0-rc1-final
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL 2.1.0-rc1
Operating system: Windows 10 
IDE: Visual Studio 2017 15.5.1

**Comment by maumar** [comment]
Problem is that Include pipeline expects entity type in the final projection, from where the Includes are applied. @divega

**Comment by maumar** [comment]
Sending back to triage - we need to figure out how exactly include should behave

**Comment by divega** [comment]
@maumar, @smitpatel, @roji Looking at this issue again after triage it seems reasonable to suggest that casting to the interface needs to be evaluated on the client so switching with AsEnumerable() should happen first. 

If it is desirable that the Concat operation gets transalted to the server, would projecting the desired properties for foo band bar into a common DTO and then doing the Concat help? If yes, I am ok with closing this for now (after adding this information).

**Comment by roji** [comment]
In order to Concat on the server, both sides have to be entity types within the same type hierarchy, or simple column projections of the same type, or an anonymous type with a combination of the above. So a DTO wouldn't really help here - either the entities are in the same hierarchy, in which case no need for a DTO, or they're not, in which case putting them in a DTO wouldn't help either...

On what happens in client evaluation, I don't really have much to add, but I'd keep this issue to track that rather than server translation (which is in progress).

**Comment by divega** [comment]
> In order to Concat on the server, both sides have to be entity types within the same type hierarchy, or simple column projections of the same type, or an anonymous type with a combination of the above.

Interesting. The anonymous type option should provide a decent workaround, but curious why we would treat DTOs differently from anonymous types. I think we have discussed elsewhere to just trust that they work the same way.

Anyway, I am still not sure about keeping this issue open. If both sources where of the same type maybe we could ignore the interface casts. But if they are different, I cannot think of any way this could work without doing the concat on the client, and that would go against the new query design.

**Comment by roji** [comment]
> Interesting. The anonymous type option should provide a decent workaround, but curious why we would treat DTOs differently from anonymous types. I think we have discussed elsewhere to just trust that they work the same way.

I may have misunderstood - above I used anonymous type and DTO interchangeably, should have just written anonymous type.

By DTO do you mean some arbitrary user-defined class that is included in the query? If so do you mean we should assume that user classes behave as DTOs (i.e. that property setters/getters don't actually contain any code etc.)? Maybe we an discuss in next triage meeting to make sure we're talking about the same thing...

**Comment by smitpatel** [comment]
> If it is desirable that the Concat operation gets transalted to the server, would projecting the desired properties for foo and bar into a common DTO and then doing the Concat help? If yes, I am ok with closing this for now (after adding this information).

That should work in new pipeline.

**Comment by ajcvickers** [comment]
Note from triage: closing this as different queries shapes will not be supported, even if they happen to implement a common interface.
