### ISSUE TITLE
[provider][mysql]Migration failed for syntax error after rename table name from `Users` to `WebUsers`

### ISSUE THREAD

**Issue by dengyakui** [dotnet/efcore#12070]
After I rename table name  by fluent api, excute migration failed for syntax error
```

      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      ALTER TABLE `Users` DROP CONSTRAINT `PK_Users`;
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      ALTER TABLE `Users` DROP CONSTRAINT `PK_Users`;
MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CONSTRAINT `PK_Users`' at line 1
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
Failed executing DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE `Users` DROP CONSTRAINT `PK_Users`;
dbug: Microsoft.EntityFrameworkCore.Database.Transaction[20204]
      Disposing transaction.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20002]
      Closing connection to database 'MyUserDb' on server '127.0.0.1'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20003]
      Closed connection to database 'MyUserDb' on server '127.0.0.1'.
MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CONSTRAINT `PK_Users`' at line 1
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CONSTRAINT `PK_Users`' at line 1
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
    public class MyUser
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
    }

    public class MyUserContext:DbContext
    {
        public MyUserContext(DbContextOptions<MyUserContext> options):base(options)
        {
            
        }

        public DbSet<MyUser> Users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // when first init it named Users
            modelBuilder.Entity<MyUser>().ToTable("Users").HasKey(u => u.Id);

          // after data generated , rename to WebUsers
            modelBuilder.Entity<MyUser>().ToTable("WebUsers").HasKey(u => u.Id);
            base.OnModelCreating(modelBuilder);
        }
    }

// first init ,name is Users
public partial class init : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Users",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("MySQL:AutoIncrement", true),
                    Age = table.Column<int>(nullable: false),
                    Name = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Users", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Users");
        }
    }

// second migrate names to WebUsers, and failed when update-database
public partial class init2 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_Users",
                table: "Users");

            migrationBuilder.RenameTable(
                name: "Users",
                newName: "WebUsers");

            migrationBuilder.AddPrimaryKey(
                name: "PK_WebUsers",
                table: "WebUsers",
                column: "Id");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_WebUsers",
                table: "WebUsers");

            migrationBuilder.RenameTable(
                name: "WebUsers",
                newName: "Users");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Users",
                table: "Users",
                column: "Id");
        }
    }
```

### Further technical details
EF Core version: 2.0.3RTM
Database Provider: MySql.DataEntityFrameworkCore.SqlServer
Operating system: Win10
IDE:  Visual Studio 2017 15.7

**Comment by dengyakui** [comment]
Hopefully to know whether the problem is caused by EF Core or MySql.Data.EntityFrameworkCore

**Comment by smitpatel** [comment]
The syntax of dropping PK on MySQL is
`ALTER TABLE tbl_name DROP PRIMARY KEY`
Ref: https://dev.mysql.com/doc/refman/8.0/en/alter-table.html
This is issue in MySql provider. They need to override the SQL generation for DropPrimaryKey operation.
Can you file issue with the provider?

**Comment by dengyakui** [comment]
There is no labels for mysql or provider,please add on if you can

**Comment by ralmsdeveloper** [comment]
@dengyakui 
You can report here:
https://bugs.mysql.com/report.php

**Comment by dengyakui** [comment]
Thanks , I  had writen an report in above address,
https://bugs.mysql.com/bug.php?id=90958
