### ISSUE TITLE
Seed data cannot be added, no value provided for required property

### ISSUE THREAD

**Issue by GeorgeR** [dotnet/efcore#12080]
When providing seed data via .HasData in EF 2.1, i'm creating 3 entities with a Key property called Id. The error message is telling me i'm not setting this value.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
System.InvalidOperationException: The seed entity for entity type 'IdentityProvider' cannot be added because there was no value provided for the required property 'Id'.
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateData(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The seed entity for entity type 'IdentityProvider' cannot be added because there was no value provided for the required property 'Id'.
```

### Steps to reproduce
1. Open the project, ensure Frontier.Data.Deploy is the startup project and run.

https://www.dropbox.com/s/mkl6cvcb8f610n7/data.zip?dl=0

### Further technical details
EF Core version: 2.1.0-rc1-final
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL (2.0.2)
Operating system: Windows 10 Professional
IDE: (e.g. Visual Studio 2017 15.7.1)

**Comment by ralmsdeveloper** [comment]
`Npgsql.EntityFrameworkCore.PostgreSQL (2.0.2)` ?
It would not be the 2.1.0-rc1

**Comment by ajcvickers** [comment]
@GeorgeR As @ralmsdeveloper indicates, you will need to update your provider to the 2.1 version in order to use data seeding.

**Comment by GeorgeR** [comment]
As I suspected, this wasn't on the provider side. I updated to the latest (2.1 RC) and i still get the same callstack.
