### ISSUE TITLE
Query: Property access on complex expression is not translated

### ISSUE THREAD

**Issue by bradmarder** [dotnet/efcore#12148]
Edit - updated reproduction without AutoMapper

```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: querySource
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.FindEntityType(IQuerySource querySource)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.NullCheckRemovalTestingVisitor.<AnalyzeTestExpression>b__7_0(IProperty p, IQuerySource qs)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.<>c__DisplayClass95_0.<BindMethodCallExpression>b__0(IProperty property, IQuerySource querySource)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.<>c__DisplayClass92_0`1.<BindMethodCallExpression>b__0(IReadOnlyList`1 ps, IQuerySource qs)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindPropertyExpressionCore[TResult](Expression propertyExpression, IQuerySource querySource, Func`3 propertyBinder)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindMethodCallExpression[TResult](MethodCallExpression methodCallExpression, IQuerySource querySource, Func`3 methodCallBinder)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindMethodCallExpression(MethodCallExpression methodCallExpression, Action`2 methodCallBinder)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.NullCheckRemovalTestingVisitor.AnalyzeTestExpression(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.NullCheckRemovalTestingVisitor.CanRemoveNullCheck(Expression testExpression, Expression resultExpression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitConditional(ConditionalExpression expression)
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.Clauses.SelectClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileAsyncQuery[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass22_0`1.<CompileAsyncQuery>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddAsyncQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQuery[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
   at System.Linq.AsyncEnumerable.Aggregate_[TSource,TAccumulate,TResult](IAsyncEnumerable`1 source, TAccumulate seed, Func`3 accumulator, Func`2 resultSelector, CancellationToken cancellationToken)
```

```c#
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Console;

namespace EFCoreBugs
{
    class Program
    {
        static async Task Main(string[] args)
        {
            using (var db = new TestDb())
            {
                await db.Database.EnsureDeletedAsync();
                await db.Database.EnsureCreatedAsync();
            }
            using (var db = new TestDb())
            {
                await db.Blogs
                    .Select(dtoBlog => new BlogDto()
                    {
                        Post = (dtoBlog.Posts.Any() ? dtoBlog.Posts.FirstOrDefault() : null) == null ? null : new PostDto()
                    })
                    .ToListAsync();
            }

            Console.ReadLine();
        }
    }

    public class TestDb : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Post> Posts { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var log = new LoggerFactory(new[] { new ConsoleLoggerProvider((_, __) => true, true) });
            optionsBuilder.UseLoggerFactory(log);
            optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=master;Database=bugtest;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False");
        }
    }

    public class Blog
    {
        public Guid Id { get; set; }

        [InverseProperty(nameof(Post.Blog))]
        public virtual List<Post> Posts { get; } = new List<Post>();
    }
    public class Post
    {
        public Guid Id { get; set; }
        public Guid BlogId { get; set; }

        [ForeignKey(nameof(BlogId))]
        public virtual Blog Blog { get; private set; }
    }

    public class BlogDto
    {
        public PostDto Post { get; set; }
    }
    public class PostDto { }
}
```

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0" />
  </ItemGroup>
</Project>
```

### Further technical details
EF Core version: 2.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system:  win10 x64
IDE: Visual Studio 2017 Preview 15.8.0 Preview 1.1

**Comment by smitpatel** [comment]
@bradmarder - I am not able to reproduce this in the absence of AutoMapper. It is likely to be issue due to no mapping for Post to PostDto.

Further `y => y.Posts.Any() ? y.Posts.FirstOrDefault() : null` is redundant. If Posts is empty (Any being false) then FirstOrDefault returns null anyway.

**Comment by bradmarder** [comment]
@smitpatel I apologize for the AutoMapper stuff, here is the code that will trigger the error. 

```c#
await db.Blogs
    .Select(dtoBlog => new BlogDto()
    {
        Post = (dtoBlog.Posts.Any() ? dtoBlog.Posts.FirstOrDefault() : null) == null ? null : new PostDto()
    })
    .ToListAsync();
```

I understand the mapping is redundant, but I couldn't replicate the bug with a simplified expression.

**Comment by smitpatel** [comment]
```C#
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EFSampleApp
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var db = new MyContext())
            {
                // Recreate database
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                // Seed database


                db.SaveChanges();
            }

            using (var db = new MyContext())
            {
                // Run queries
                var query = db.Blogs
                    .Select(dtoBlog => new BlogDto()
                    {
                        Post = (dtoBlog.Posts.Any() ? dtoBlog.Posts.FirstOrDefault() : null) == null ? null : new PostDto()
                    }).ToList();
            }

            Console.WriteLine("Program finished.");
        }
    }


    public class MyContext : DbContext
    {
        private static ILoggerFactory LoggerFactory => new LoggerFactory().AddConsole(LogLevel.Trace);

        // Declare DBSets
        public DbSet<Blog> Blogs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // Select 1 provider
            optionsBuilder
                .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=_ModelApp;Trusted_Connection=True;Connect Timeout=5;ConnectRetryCount=0")
                //.UseSqlite("filename=_modelApp.db")
                //.UseInMemoryDatabase(databaseName: "_modelApp")
                .EnableSensitiveDataLogging()
                .UseLoggerFactory(LoggerFactory);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Configure model
        }
    }

    public class Blog
    {
        public int Id { get; set; }
        public List<Post> Posts { get; set; }
    }

    public class Post
    {
        public int Id { get; set; }
        public int BlogId { get; set; }
        public Blog Blog { get; set; }
    }

    public class BlogDto
    {
        public PostDto Post { get; set; }
    }
    public class PostDto { }

}
```

**Comment by smitpatel** [comment]
It appears because we started converting `ET == null` to entity equality where `ET` is a complex query (not just query source). So a later visitor fails to check if there could be null query source.

**Comment by ajcvickers** [comment]
@smitpatel Regression?

**Comment by smitpatel** [comment]
@ajcvickers - Not a regression. 2.0.2 failed with different exception message.

**Comment by ajcvickers** [comment]
@smitpatel to post workaround.

**Comment by myrup** [comment]
Getting this error on a similar expression, maybe the same bug:
```c#
db.Blogs.Select(b => new { Blog = b, Detail = GetDetail(b) })
              .Select(bd => new { bd.Blog, SubDetail = (Detail == null ? null : bd.Detail.SubDetail })
              .ToList();
```
Normally I would use a null propagating operator to do the above (e.g. ```bd.Detail?.SubDetail```) but the compiler tells me they cannot be used in expression trees. Hence the```?:```  workaround above (which results in runtime crash). My workaround for the runtime crash is calling a static method outside:
```c#
db.Blogs.Select(b => new { Blog = b, Detail = GetDetail(b) })
              .Select(bd => new { bd.Blog, SubDetail = GetSubDetail(bd.Detail) })
              .ToList();
```
Ideas to prettier workarounds appreciated :)

**Comment by ajcvickers** [comment]
@myrup Please open a new issue and include a runnable project/solution or complete code listing that demonstrates the behavior you are seeing,

**Comment by jcemoller** [comment]
@ajcvickers Just started hitting this bug as well. See https://github.com/AutoMapper/AutoMapper/issues/2784. I've created a gist that reproduces the error here: https://gist.github.com/jcemoller/51c2ecc07369f4c4b706df006be67633

The following code is what AutoMapper generates. Removing the null check works, but since the entity might be null it is not a feasible workaround.

```c#
context.Ads.Select(dtoAd => new AdDetails()
                {
                    Offers = dtoAd.Offers.Select(dtoOffer => new
                    {
                        __LastAction = dtoOffer.Actions.OrderByDescending(a => a.TimeCreatedUtc).FirstOrDefault(),
                        Id = dtoOffer.Id
                    })
                    .Select(dtoLet => new OfferDetails()
                    {
                        Id = dtoLet.Id,
                        LastAction = dtoLet.__LastAction == null ? null : new OfferActionDetails()
                        {
                            Action = dtoLet.__LastAction.Action,
                            TimeCreatedUtc = dtoLet.__LastAction.TimeCreatedUtc
                        }
                    })
                    .ToList()
                })
```

**Comment by smitpatel** [comment]
Subquery Member pushdown should expand the scope to apply member access on true/false both.
