### ISSUE TITLE
Operand type clash: datetime2 is incompatible with int

### ISSUE THREAD

**Issue by hanayashiki** [dotnet/efcore#12196]
I am new to EF and `Add-Migration` failed when I tried to alter the type of a column

the migration is automatically generated as follow:
```
using Microsoft.EntityFrameworkCore.Migrations;
using System;
using System.Collections.Generic;

namespace RazorPagesMovies.Migrations
{
    public partial class AlterDate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<int>(
                name: "ReleaseDate",
                table: "Movie",
                nullable: false,
                oldClrType: typeof(DateTime));
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<DateTime>(
                name: "ReleaseDate",
                table: "Movie",
                nullable: false,
                oldClrType: typeof(int));
        }
    }
}

```

when I enter 
```
Update-Database
```
It turned out to be
```
PM> Update-Database
Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\t-chwang\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.0.3-rtm-10026 initialized 'RazorPagesMoviesContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (21ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'__EFMigrationsHistory');
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'__EFMigrationsHistory');
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [MigrationId], [ProductVersion]
      FROM [__EFMigrationsHistory]
      ORDER BY [MigrationId];
Microsoft.EntityFrameworkCore.Migrations[20402]
      Applying migration '20180601044735_AlterDate'.
Applying migration '20180601044735_AlterDate'.
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (265ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      DECLARE @var0 sysname;
      SELECT @var0 = [d].[name]
      FROM [sys].[default_constraints] [d]
      INNER JOIN [sys].[columns] [c] ON [d].[parent_column_id] = [c].[column_id] AND [d].[parent_object_id] = [c].[object_id]
      WHERE ([d].[parent_object_id] = OBJECT_ID(N'Movie') AND [c].[name] = N'ReleaseDate');
      IF @var0 IS NOT NULL EXEC(N'ALTER TABLE [Movie] DROP CONSTRAINT [' + @var0 + '];');
      ALTER TABLE [Movie] ALTER COLUMN [ReleaseDate] int NOT NULL;
System.Data.SqlClient.SqlException (0x80131904): Operand type clash: datetime2 is incompatible with int
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ClientConnectionId:36e05f89-44f1-4069-bbc6-0bcd89336e0d
Error Number:206,State:2,Class:16
Failed executing DbCommand (265ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
DECLARE @var0 sysname;
SELECT @var0 = [d].[name]
FROM [sys].[default_constraints] [d]
INNER JOIN [sys].[columns] [c] ON [d].[parent_column_id] = [c].[column_id] AND [d].[parent_object_id] = [c].[object_id]
WHERE ([d].[parent_object_id] = OBJECT_ID(N'Movie') AND [c].[name] = N'ReleaseDate');
IF @var0 IS NOT NULL EXEC(N'ALTER TABLE [Movie] DROP CONSTRAINT [' + @var0 + '];');
ALTER TABLE [Movie] ALTER COLUMN [ReleaseDate] int NOT NULL;
System.Data.SqlClient.SqlException (0x80131904): Operand type clash: datetime2 is incompatible with int
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:36e05f89-44f1-4069-bbc6-0bcd89336e0d
Error Number:206,State:2,Class:16
Operand type clash: datetime2 is incompatible with int
```

### Further technical details
Microsoft Visual Studio Enterprise 2017 
版本 15.7.2
VisualStudio.15.Release/15.7.2+27703.2018
Microsoft .NET Framework
版本 4.7.03056

已安装的版本: Enterprise

Visual C++ 2017   00369-60000-00001-AA258
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio 包   8.12.10405.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40511.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.7.31476
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60419.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40424.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.3000.2
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   15.0.40424.0
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.3.3000.2
Microsoft Azure Stream Analytics Tools for Visual Studio

C# 工具   2.8.2-beta6-62916-08. Commit Hash: 2ad4aabc7a9dada097e54e544ebba48ab1c05074
在 IDE 中使用的 C# 组件。根据项目类型和设置，可能会使用不同版本的编译器。

Cookiecutter   15.7.18131.1
提供以 cookiecutter 格式查找、实例化和自定义模板的工具。

Fabric.DiagnosticEvents   1.0
Fabric 诊断事件

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP 项目系统   2.0
JavaScript UWP 项目系统

JavaScript 语言服务   2.0
JavaScript 语言服务

Microsoft Azure HDInsight Azure Node   2.3.3000.2
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.3000.2
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.3.3000.2
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10420.2

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ 向导   1.0
Microsoft Visual C++ 向导

Microsoft Visual Studio VC 软件包   1.0
Microsoft Visual Studio VC 软件包

Microsoft 用于 Visual Studio 的持续交付工具   0.3
自动化来自 Visual Studio IDE 内的持续生成集成和持续生成交付配置。

NuGet 包管理器   4.6.0
Visual Studio 中的 NuGet 包管理器。有关 NuGet 的详细信息，请访问 http://docs.nuget.org/。

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   15.7.18131.1
为 Python 开发人员提供 IntelliSense、项目、模板、调试、交互窗口和其他支持。

Python - Django 支持   15.7.18131.1
为 Django Web 框架提供模板和集成。

Python - IronPython 支持   15.7.18131.1
为基于 IronPython 的项目提供模板和集成。

Python - 分析支持   15.7.18131.1
对 Python 项目的分析支持。

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61804.210
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   15.7.20419.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic 工具   2.8.2-beta6-62916-08. Commit Hash: 2ad4aabc7a9dada097e54e544ebba48ab1c05074
在 IDE 中使用 Visual Basic 组件。根据项目类型和设置，可能会使用不同版本的编译器。

Visual F# Tools 10.1 for F# 4.1   15.7.0.0.  Commit Hash: 56f97a8dd4353d897336941f3e644423b87c794f.
Microsoft Visual F# Tools 10.1 for F# 4.1

Visual Studio Code 调试适配器主机包   1.0
用于在 Visual Studio 中托管 Visual Studio Code 调试适配器的互操作层

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Universal Windows Apps   15.0.27703.2018
Visual Studio Tools for Universal Windows Apps 让你能够构建一种通用的应用体验，运行 Windows 10 的每种设备都可以获得这种体验，如手机、平板电脑、PC 等。它包含 Microsoft Windows 10 软件开发工具包。

Windows Machine Learning Generator Extension   1.0
Windows Machine Learning Visual Studio Extension Detailed Info

快照调试扩展   1.0
快照调试 Visual Studio 扩展的详细信息

适用于 Google Test 的测试适配器   1.0
启用带有针对 Google Test 编写的单元测试的 Visual Studio 测试工具。扩展安装目录中提供了使用条款和第三方通知。

通用 Azure 工具   1.10
通过 Azure 移动服务和 Microsoft Azure Tools 提供通用服务。

用于 Visual Studio 的 Microsoft Azure Service Fabric 工具   2.1
用于 Visual Studio 的 Microsoft Azure Service Fabric 工具

用于容器的 Microsoft Visual Studio Tools   1.1
在目标环境中开发、运行、验证 ASP.NET Core 应用程序。按 F5，应用程序经调试后直接进入容器，或者按 Ctrl+F5 可编辑和刷新应用，无需重新生成容器。

**Comment by ajcvickers** [comment]
@hanayashiki What version of EF Core are you using?

**Comment by hanayashiki** [comment]
@ajcvickers From the issue content I think it is `Entity Framework Core 2.0.3`

**Comment by ajcvickers** [comment]
Note from triage: changing the type like this is not currently supported. We will look at this as part of table rebuilds (#329) and at least attempt a better error message.

**Comment by dauthleikr** [comment]
I am having pretty much the same issue on ef-core 5.0.0. The referenced issue didn't fix this problem. 

For me, this happened because:
* I have a `TimeSpan` in an Entity - however that causes ef-core to use time(7) as the database type, which doesn't work for some use cases because that limits the `TimeSpan` to one day.
* I added a `TimeSpanToTicksConverter` to my property to be able to store more than one day:
```c#
modelBuilder.Entity<Purchasable>()
	.Property(p => p.ServiceDuration) // ServiceDuration is a TimeSpan
	.HasConversion(new TimeSpanToTicksConverter());
```
* The generated migration looks like this:
```c#
public partial class TimeSpanToTicks : Migration
{
	protected override void Up(MigrationBuilder migrationBuilder)
	{
		migrationBuilder.AlterColumn<long>(
			name: "ServiceDuration",
			table: "Purchasables",
			type: "bigint",
			nullable: false,
			oldClrType: typeof(TimeSpan),
			oldType: "time");
	}

	protected override void Down(MigrationBuilder migrationBuilder)
	{
		migrationBuilder.AlterColumn<TimeSpan>(
			name: "ServiceDuration",
			table: "Purchasables",
			type: "time",
			nullable: false,
			oldClrType: typeof(long),
			oldType: "bigint");
	}
}
```
* When running `dotnet ef database update`:
`Operand type clash: time is incompatible with bigint`
Full output:
```
dotnet ef database update
Build started...
Build succeeded.
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (8ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      DECLARE @var2 sysname;
      SELECT @var2 = [d].[name]
      FROM [sys].[default_constraints] [d]
t_id] = [c].[object_id]
      WHERE ([d].[parent_object_id] = OBJECT_ID(N'[Purchasables]') AND [c].[name] = N'ServiceDuration');
      IF @var2 IS NOT NULL EXEC(N'ALTER TABLE [Purchasables] DROP CONSTRAINT [' + @var2 + '];');
      ALTER TABLE [Purchasables] ALTER COLUMN [ServiceDuration] bigint NOT NULL;
Failed executing DbCommand (8ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
DECLARE @var2 sysname;
SELECT @var2 = [d].[name]
FROM [sys].[default_constraints] [d]
INNER JOIN [sys].[columns] [c] ON [d].[parent_column_id] = [c].[column_id] AND [d].[parent_object_id] = [c].[object_id]
WHERE ([d].[parent_object_id] = OBJECT_ID(N'[Purchasables]') AND [c].[name] = N'ServiceDuration');
IF @var2 IS NOT NULL EXEC(N'ALTER TABLE [Purchasables] DROP CONSTRAINT [' + @var2 + '];');
ALTER TABLE [Purchasables] ALTER COLUMN [ServiceDuration] bigint NOT NULL;
Microsoft.Data.SqlClient.SqlException (0x80131904): Operand type clash: time is incompatible with bigint
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:8b4155cf-2c39-43f4-b551-1651a7513777
Error Number:206,State:2,Class:16
Operand type clash: time is incompatible with bigint
```

Other info:
* SQL Server 19
* .net 5
* ef-core 5.0.0

**Comment by roji** [comment]
@dauthleikr #329 is about doing table rebuilds in some scenarios on Sqlite (where basic table alterations aren't supported), whereas you seem to be using SqlServer.

More to the point, SQL Server does not support altering a column's type from time to bigint, and for good reason - how do you expect that conversion to happen? Unlike with, say, from GUID to string, where the conversion is straightforward and always possible, it's unknown how to perform the conversion in this case.

However, you can still do the conversion yourself by adding operations in the generated migration file; add a new column, copy the data across from the old to the new column using whatever conversion fits, then delete the old column and rename.

**Comment by theminer3746** [comment]
@dauthleikr I just had the same problem with you. The way I solved mine is by writing a migration like this

```
migrationBuilder.AddColumn<long>(
    name: "WorkHours_tmp",
    table: "tbTimesheet",
    type: "bigint",
    nullable: false,
    defaultValue: 0L);

migrationBuilder.Sql(@"UPDATE A SET A.WorkHours_tmp = (
    SELECT datediff(second, '00:00', B.WorkHours) * cast(10000000 as bigint) + right(B.WorkHours, 7)
    FROM tbTimesheet AS B WHERE A.TimesheetId = B.TimesheetId
) FROM tbTimesheet A");

migrationBuilder.DropColumn(
    name: "WorkHours",
    table: "tbTimesheet");

migrationBuilder.RenameColumn(
    name: "WorkHours_tmp",
    table: "tbTimesheet",
    newName: "WorkHours"
);
```

Basically

1. Create a new temporary column with the type of bigint
2. Copy the data from the old column over and convert them to Tick
3. Drop the old column
4. Rename the new column to remove `_tmp` from the name
