### ISSUE TITLE
SqlServer: Cannot use a clustered index without making PK non clustered explicitly

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#12193]
Model
```C#
    public class Blog
    {
        public int Id { get; set; }
        public int Value { get; set; }
    }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Configure model
            // Uncomment following line to make it work
            //modelBuilder.Entity<Blog>().HasKey(e => e.Id).ForSqlServerIsClustered(false);
            modelBuilder.Entity<Blog>().HasIndex(e => e.Value).ForSqlServerIsClustered();
        }
```
Using EnsureCreated/migrations
Exception message:
```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (8ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE [Blogs] (
          [Id] int NOT NULL IDENTITY,
          [Value] int NOT NULL,
          CONSTRAINT [PK_Blogs] PRIMARY KEY ([Id])
      );
dbug: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE CLUSTERED INDEX [IX_Blogs_Value] ON [Blogs] ([Value]);
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE CLUSTERED INDEX [IX_Blogs_Value] ON [Blogs] ([Value]);

System.Data.SqlClient.SqlException (0x80131904): Cannot create more than one clustered index on table 'Blogs'. Drop the existing clustered index 'PK_Blogs' before creating another.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
Unhandled Exception:   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boole an callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ClientConnectionId:c314f15b-88b6-477b-9520-282d4abe4497
```
Expectation:
If user configures index as clustered we should automatically add nonclustered to PK definition.

**Comment by ajcvickers** [comment]
Triage: we would consider a well-written PR to automatically un-cluster the PK when a different clustered index is created. However, we don't plan to implement this ourselves as the value seems quite low.
