### ISSUE TITLE
InMemoryProvider doesn't support attach for existing entities

### ISSUE THREAD

**Issue by cdarrigo** [dotnet/efcore#12204]
In my EF 2.1 code I make use of the attach operation to permit updates without selects.

```C#
var entity = new MyEntity{id=1}
var tracking = datacontext.MyEntities.Attach(entity);
entity.LastUpdateDT = DateTime.UtcNow();
await dataContext.SaveChangesAsync();
```

When I write unit tests to exercise this update logic, I use the InMemory provider. 
The test must fist populate the datacontext with the entity before it can be updated
```C#
dataContext.MyEntities.Add(new MyEntity{Id=1, Name="blah"});
datacontext.SaveChangesAsync();
var entity = new MyEntity{id=1}
var tracking = datacontext.MyEntities.Attach(entity); <-- Error happens here
entity.LastUpdateDT = DateTime.UtcNow();
await dataContext.SaveChangesAsync();
```
The InMemory provider is not happy because an entity with the Id =1 already exists. 
As a result, I cannot unit test my update code that implements this pattern.

```
Exception message:System.InvalidOperationException : The instance of entity type 'MyEntity' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node, Boolean force)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode node, TState state, Func`3 handleNode)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Blackbaud.TMS.DataManagement.Service.Data.Providers.ChargeDataProvider.<UpdateTransactionDistributionListAsync>d__19.MoveNext() in C:\Repo\tms-dmgmt-svc\src\Blackbaud.TMS.DataManagement.Service\Data\Providers\ChargeDataProvider.cs:line 684
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Blackbaud.TMS.DataManagement.Service.Data.Providers.ChargeDataProvider.<UpdateAsync>d__10.MoveNext() in C:\Repo\tms-dmgmt-svc\src\Blackbaud.TMS.DataManagement.Service\Data\Providers\ChargeDataProvider.cs:line 291
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Blackbaud.TMS.DataManagement.Service.UnitTests.Data.Providers.ChargeDataProviderTests.<Can_UpdateAsync_Success_FullGraph>d__18.MoveNext() in C:\Repo\tms-dmgmt-svc\test\Blackbaud.TMS.DataManagement.Service.UnitTests\Data\Providers\ChargeDataProviderTests.cs:line 346
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)



### Further technical details
EF Core version: 2.1.0
Database Provider: InMemoryDataProvider
Operating system:  Windows 10
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by ajcvickers** [comment]
@cdarrigo The code is attempting to attach to entity instances with the same ID to the same context instance. As the exception says, this is not allowed. Try using a different context instance to setup in-memory the database.

**Comment by cdarrigo** [comment]
@ajcvickers 

This relates to performing UPDATES, so the data must already exist in the in memory database instance.  If I change my database contexts, there will be no entity in the context instance when I go to perform the update. 

Before you close this issue, maybe you could provide a sample on how I can successfully implement a Update-Without-Select pattern using the In-Memory Database.

**Comment by ajcvickers** [comment]
@cdarrigo There is nothing different about the in-memory database. It's just that if you want to perform an update to something already in the in-memory database, then something needs to put it there. Your code uses the context instance to save an entity to the database in order to do this. However, you then use the same context instance, which is still tracking the entity used, and then attempt to create another object to represent the same entity. This would fail on any database.

This is what I meant by using a different context instance to setup the in-memory database:
```C#
using (var context = new BloggingContext())
{
    context.Add(new Blog { BlogId = 1 });

    context.SaveChanges();
}

using (var context = new BloggingContext())
{
    var entity = new Blog { BlogId = 1 };
    
    context.Attach(entity);

    entity.LastUpdateDT = DateTime.UtcNow;

    context.SaveChanges();
}
```
