### ISSUE TITLE
Where clause predicate exception: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by alirizaadiyahsi** [dotnet/efcore#12294]
### Unit test

```c#
public class UserApplicationServiceTests : ApplicationTestBase
{
    private readonly IUserAppService _userAppService;

    public UserApplicationServiceTests()
    {
        var userRepository = new Repository<User>(KodkodInMemoryContext);
        _userAppService = new UserAppService(userRepository);
    }

    [Fact]
    public async Task TestGetAllAsync()
    {
        // working
        var getUsersInput = new GetUsersInput();
        var usersList = await _userAppService.GetUsersAsync(getUsersInput);
        Assert.True(usersList.Items.Count >= 0);

        // not working
        getUsersInput.Filter = "qwerty";
        var usersListEmpty = await _userAppService.GetUsersAsync(getUsersInput);
        Assert.True(usersListEmpty.Items.Count == 0);
    }
}
```

### UserAppService

```c#
public class UserAppService : IUserAppService
{
    private readonly IRepository<User> _userRepository;

    public UserAppService(IRepository<User> userRepository)
    {
         _userRepository = userRepository;
    }

    public async Task<IPagedList<UserListDto>> GetUsersAsync(GetUsersInput input)
    {
          var query = _userRepository.GetAll(
                 !input.Filter.IsNullOrEmpty(),
                 predicate => predicate.UserName.Contains(input.Filter) ||
                              predicate.Email.Contains(input.Filter))
                .OrderBy(input.Sorting);

          var usersCount = await query.CountAsync();
          var users = query.PagedBy(input.PageIndex, input.PageSize).ToList();
          var userListDtos = Mapper.Map<List<UserListDto>>(users);

          return userListDtos.ToPagedList(usersCount);
    }
}
```

### Repository

```c#
public IQueryable<TEntity> GetAll(
    bool condition = false,
    Expression<Func<TEntity, bool>> predicate = null,
    bool disableTracking = false)
{
    IQueryable<TEntity> query = DbSet;
    if (disableTracking)
    {
        query = query.AsNoTracking();
    }

    if (condition && predicate != null)
    {
        // Exception thrown from here
        query = query.Where(predicate);
    }

    return query;
}
```

Exception is thrown from this line in repository

    if (condition && predicate != null)
    {
        // Exception thrown from here
        query = query.Where(predicate);
    }

**NOTE:** I am using EF Core in-memory db

```
Exception message: System.NullReferenceException : Object reference not set to an instance of an object.
Stack trace: at lambda_method(Closure , ValueBuffer )
   at System.Linq.Enumerable.WhereEnumerableIterator`1.GetCount(Boolean onlyIfCheap)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.AsyncEnumerable.AsyncEnumerableAdapter`1.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
   at Kodkod.Application.Users.UserAppService.GetUsersAsync(GetUsersInput input) in D:\GitHub\Kodkod\src\Kodkod.Application\Users\UserAppService.cs:line 34
   at Kodkod.Application.Tests.UserApplicationServiceTests.TestGetAllAsync() in D:\GitHub\Kodkod\test\Kodkod.Application.Tests\UserApplicationServiceTests.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
```

### Further technical details
EF Core version: 2.1
Database Provider: MSSQL Server 2016
Operating system: Windows 10 latest
IDE: Visual Studio 2017 v15.7.3

Related issue: https://github.com/alirizaadiyahsi/Kodkod/issues/4

**Comment by maumar** [comment]
@alirizaadiyahsi any of the User entities have their UserName or Email properties set to null? EFCore only applies null protection if the property is accessed thru navigation property. Otherwise you need to handle it yourself on InMemory:

```cs
var query = _userRepository.GetAll(
                 !input.Filter.IsNullOrEmpty(),
                 predicate => (predicate.UserName != null && predicate.UserName.Contains(input.Filter)) ||
                              (predicate.Email != null && predicate.Email.Contains(input.Filter)))
                .OrderBy(input.Sorting);
```

Otherwise, please provide a runnable repro so that we can investigate.

**Comment by alirizaadiyahsi** [comment]
> any of the User entities have their UserName or Email properties set to null?

Yes. And understand thanks
