### ISSUE TITLE
How to Migrate to use EF Core Seed Data

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/efcore#12324]
In EF Core 2.0 I had some custom code to insert seed data on app startup. I would like to migrate to use the Seed Data functionality in EF Core 2.1.

I switched over to use the EF Core 2.1 `HasData` method to add my seed data and added a migration. When I start the app, I get the following error:

```
2018-06-11 14:52:21 ERR Failed executing DbCommand ("62"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"\r\n""IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'CountryId', N'Alpha2Code', N'CreatedTimestamp', N'ModifiedTimestamp', N'Name', N'Phone_IsdCode', N'Phone_Length', N'TimeZone_Name', N'TimeZone_TzdbId', N'TimeZone_WindowsId') AND [object_id] = OBJECT_ID(N'[ten].[Country]'))\r\n    SET IDENTITY_INSERT [ten].[Country] ON;...........................Omitted..........................SET IDENTITY_INSERT [ten].[Country] OFF;"
System.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK_Country'. Cannot insert duplicate key in object 'ten.Country'. The duplicate key value is (1).
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
ClientConnectionId:196407e1-c330-4c9d-b95f-5d2a4d5c5787
Error Number:2627,State:1,Class:14
```

I guess, my scenario is not supported without some extra work (if at all). How can I migrate over completely?

**Comment by ajcvickers** [comment]
@RehanSaeed Are you using an enum as the primary key property?

**Comment by RehanSaeed** [comment]
No.

What is the expected behavior? The Docs are pretty basic on data seeding.

**Comment by ajcvickers** [comment]
@RehanSaeed We looked at this in triage but there isn't much to go on here. The exception seems to indicate that the database already contains the data. Was it seeded already in some other way? Beyond this, I don't think we'll be able to make much progress without a repro. Can you please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

**Comment by RehanSaeed** [comment]
Full repro steps here:

https://github.com/RehanSaeed/EFCoreSeedData

**Comment by ajcvickers** [comment]
@RehanSaeed So are you asking how to start using HasData _even though the database already contains the seed data_? If so, then after generating the first migration that contains seed data edit that migration to remove the code that will insert the new data--since it is already there. From that point on future migrations will then update the data as needed.

If you're instead asking something different, then can you be more specific about what you are trying to do?

**Comment by RehanSaeed** [comment]
Yes, removing the data from the migration for a database with existing seed data seems the way to go.

However, if I was to create a brand new database, I would like EF Core to seed the data for me. Is that also possible?

**Comment by ajcvickers** [comment]
Yes. That's the idea of seeding.

**Comment by virzak** [comment]
@ajcvickers,

How would an empty database be seeded if the insertion code has been removed?

The context is a WPF app, which could be either a new or an existing installation with data previously seeded some `SeedAsync` method, which has now been removed in favour of `.HasData`

**Comment by virzak** [comment]
I guess one way of dealing with this is to drop foreign keys, delete any existing data, insert entries, then recreate foreign keys. A bit complex, but should work?

**Comment by CleanCodeX** [comment]
Let me recap this: It is currently not possible to write a migration to seed data, apply it to the database **without** removing the seeding code afterwards which fed the migration? Is this correct?

Steps:
1. Create .HasData() code
2. Create a migration with "add-migration"
3. Delete .HasData() code
4. Run the app and apply the migration
5. Further ap pstarts without apply the migration again

So all of this is only possible when doing step 3, right? Is there any chance of success in not doing step 3?

**Comment by AndriySvyryd** [comment]
@CleanCodeX Correct. If you don't need to keep the seed data in the database updated with the data in the model then you shouldn't use .HasData().

If you delete the .HasData() calls after applying the migration then the next migration will delete the data.
