### ISSUE TITLE
Dependency Injection Error when using HasData

### ISSUE THREAD

**Issue by anorborg** [dotnet/efcore#12330]
I'm attempting to add a configuration option to use the new `HasData` on the model builder for seeding data.

The data seems to load successfully we initializing the DbContext and the HasData code runs without issue, but then receive an error initializing my data Repoistory:

**HasData Code (runs without Error)**
```csharp
Configure(EntityTypeBuilder<Registrant> builder)
{
   ...
   builder.HasData(GetTestData());
}

private static IEnumerable<Registrant> GetTestData()
{
    var registrations = new List<Registrant>();

    for(var i = 0; i < 100; i++)
    {
        registrations.Add(new Registrant {
              FirstName = $"First Name {i}",
              LastName = $"Last Name {i}",
              Email = $"first.last{i}@email.com",
              PhoneNumber = $"(916) 555-{i}"
         });
     }

     return registrations;
}
```
**Repo Code (Where Exception occurs)**
```csharp
public EFRepository(DbContext db)
{
    Db = db;
    Entities = db.Set<TEntity>(); // Exception here
```

**Exception Message**
```
An exception of type 'System.Reflection.TargetParameterCountException' 
occurred in System.Private.CoreLib.dll but was not handled in user code: 
'Parameter count mismatch.'
```

**Stack Trace:**
```
Exception has occurred: CLR/System.Reflection.TargetParameterCountException
An exception of type 'System.Reflection.TargetParameterCountException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Parameter count mismatch.'
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.GetData(Boolean providerValues)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateData(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_1(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at Company.Common.Infrastructure.Repositories.EFRepository`1..ctor(DbContext db) in /Users/local/Projects/company-test-all/company-common-dotnet/src/Common.Infrastructure/Repositories/EFRepository.cs:line 31
   at Company.Test.Infrastructure.Repositories.RegistrantRepository..ctor(TestContext db) in /Users/local/Projects/company-test-all/company-test-domain/src/Test.Infrastructure/Repositories/RegistrantRepository.cs:line 16
```

Removing the `HasData` code alone fixes the issue. The documentation on HasData is pretty sparse so not clear if there are limitations.

### Further technical details
EF Core version: 2.1.0
Database Provider: (e.g. Microsoft.EntityFrameworkCore.InMemory)
Operating system: macOS High Sierra
IDE: (e.g. Visual Studio Code 1.24)

**Comment by anorborg** [comment]
Looks like IEnumerable got me and not evaulating soon enough. Closing out.

**Comment by lecoque** [comment]
Also  https://github.com/aspnet/EntityFrameworkCore/issues/12321
