### ISSUE TITLE
The DataBuilder's HasData works incorrect with foreign keys

### ISSUE THREAD

**Issue by snys98** [dotnet/efcore#12339]
I'm trying to seed data(some infrastructure data of `IdentityServer4`) with foreign key, using `DataBuilder.HasData()`.

But when adding migrations, it fails with message `System.InvalidOperationException: The seed entity for entity type 'Client' with the key value 'Id:1' cannot be added because it has the navigation 'AllowedGrantTypes' set. To seed relationships you need to add the related entity seed to 'ClientGrantType' and specify the foreign key values {'ClientId'}.`

And I'm wondering if it is not allowed to set navigation propertities?

```
Exception message:
Stack trace:
at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateData(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_1(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The seed entity for entity type 'Client' with the key value 'Id:1' cannot be added because it has the navigation 'AllowedGrantTypes' set. To seed relationships you need to add the related entity seed to 'ClientGrantType' and specify the foreign key values {'ClientId'}.
```

### Steps to reproduce

```c#
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            var apigatewayClient = new ClientModel
            {
                ClientId = "ApiGateway",
                ClientName = "ApiGateway",
                AllowedGrantTypes = GrantTypes.Hybrid,

                AllowAccessTokensViaBrowser = true,
                RequireConsent = false,

                ClientSecrets =
                {
                    new SecretModel("ApiGateway".Sha256())
                },

                RedirectUris = {_configuration["ApiGateway:RedirectUri"]},
                PostLogoutRedirectUris = {_configuration["ApiGateway:PostLogoutRedirectUri"]},

                AllowedScopes =
                {
                    IdentityServerConstants.StandardScopes.OpenId,
                    IdentityServerConstants.StandardScopes.Profile,
                },
            }.ToEntity();
            apigatewayClient.Id = 1;
            var apigatewayClientGrantTypeEntities = apigatewayClient.AllowedGrantTypes.Select((x, i) => new 
            {
                ClientId = apigatewayClient.Id,
                GrantType = x,
                Id = i
            });
            builder.Entity<ClientGrantType>().HasData(apigatewayClientGrantTypeEntities);
            builder.Entity<Client>().HasData(apigatewayClient);
            // some other codes
        }
```

### Further technical details
EF Core version: 2.1.300
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: 
IDE: Visual Studio 2017 15.8.0 Preview2

Thanks! :)

**Comment by ajcvickers** [comment]
@snys98 Correct--as the message says, setting nav properties as part of seeding is not yet supported. This is tracked by #10000

**Comment by Soarc** [comment]
@snys98 I'm trying to do exactly same thing. Did you find any workaround to seed identity server data?

**Comment by 1996dylanriley** [comment]
I too am trying to do this, still no resolution?

**Comment by Laumania** [comment]
I had the exact same issue and the error message, indicates that I did something wrong, like:
"If you want to set X, you have to set X first"  :P

I can see now that it's not supported, so need to figure another way to seed my database :(

**Comment by master-still** [comment]
Same Here ! Sad to see no solution yet !!

**Comment by IkeRolfe** [comment]
I was able to workaround this issue by adding the foreign key explicitly, hasdata first on the parent with empty offending class member, then has data for the child property with the fk set manually to the previously called data.
`
    [Table("Carriers")]
    public class Carrier
    {
        [Key,ForeignKey("CarrierId")]
        public int Id { get; set; }
        [Required, MaxLength(35)]
        public string Name { get; set; }        
    }
    [Table("Services")]
    public class Service
    {
        [Key, ForeignKey("ServiceId")]
        public int Id { get; set; }
        [Required,MaxLength(50)]
        public string Name { get; set; }
        [Required]
        public Carrier Carrier { get; set;}
        public int CarrierId { get; set; }
    }
`
Seed Data
```
    public static class DefaultData
    {
        public static readonly List<Carrier> Carriers = new List<Carrier>
        {
            new Carrier {Id = 1, Name = "UPS"},
            new Carrier {Id = 2, Name = "USPS"}
        };

        public static readonly IEnumerable<Service> Services = new Service[]
        {
            new Service {CarrierId = 1, Id = 7, Name = "UPS® Ground"},
            new Service {CarrierId = 2, Id = 16, Name = "Priority Mail"}
        };
    }
```
ModelBuilder
```
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Carrier>()
                .HasData(DefaultData.Carriers);
            modelBuilder.Entity<Service>()
                .HasData(DefaultData.Services);
        }
```

**Comment by AndriySvyryd** [comment]
You can use anonymous types to specify values for shadow FKs, see https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding
