### ISSUE TITLE
Insert fails after model-based seeding an InMemoryDatabase

### ISSUE THREAD

**Issue by mihaimuraru** [dotnet/efcore#12371]
When unit testing DBContext using the in-memory provider and database initialized using context.Database.EnsureCreated() with the new model-based seeding with primary keys specified, I have the following error inserting new data in the DBSet already seeded:
**Message: System.ArgumentException : An item with the same key has already been added. Key: 1**

I don't have this error when using an SQL database provider for EFCore - a correct identity primary key is obtained.

The following error is received when the unit test runs in Visual Studio (with the attached archive):
```
Exception message: System.ArgumentException : An item with the same key has already been added. Key: 1
Stack trace:
at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryTable`1.Create(IUpdateEntry entry)
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryStore.ExecuteTransaction(IReadOnlyList`1 entries, IDiagnosticsLogger`1 updateLogger)
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryDatabase.SaveChangesAsync(IReadOnlyList`1 entries, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at EFCoreSeedUnitTestingIssue.UnitTest.InsertApplication(AppDBContext dbContext) in D:\EFCoreSeedUnitTestingIssue\DBContext.cs:line 61
   at EFCoreSeedUnitTestingIssue.UnitTest.InsertApplication_NewApplicationWithFeatures_ApplicationIdGreaterThanZero() in D:\EFCoreSeedUnitTestingIssue\DBContext.cs:line 73

```
[EFCoreSeedUnitTestingIssue.zip](https://github.com/aspnet/EntityFrameworkCore/files/2105189/EFCoreSeedUnitTestingIssue.zip)

### Further technical details
EF Core version: 2.1
Database Provider: Microsoft.EntityFrameworkCore.InMemory
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.3

**Comment by ajcvickers** [comment]
@mihaimuraru This is because the in-memory key generator is not very smart. Issue #6872 is tracking improvements, for which your case seems to be covered by https://github.com/aspnet/EntityFrameworkCore/issues/6872#issuecomment-327649022
