### ISSUE TITLE
SqliteRelationalConnection does not call BundleInitializer

### ISSUE THREAD

**Issue by dermeister0** [dotnet/efcore#12424]
SqliteRelationalConnection does not call BundleInitializer

[Static constructor](https://github.com/aspnet/Microsoft.Data.Sqlite/blob/d24c8d41a628b284973a866426f330f90dc43a9a/src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs#L29) of `SqliteConnection` is not called when `Context.Migrate()` is executed on SQLite DB. `BundleInitializer.Initialize()` is not called, I receive an exception.

```
Exception message: System.Exception: You need to call SQLitePCL.raw.SetProvider().  If you are using a bundle package, this is done by calling SQLitePCL.Batteries.Init().
Stack trace:
   at SQLitePCL.SQLite3Provider_bait.SQLitePCL.ISQLite3Provider.sqlite3_open_v2(String filename, IntPtr& db, Int32 flags, String vfs)
   at SQLitePCL.raw.sqlite3_open_v2(String filename, sqlite3& db, Int32 flags, String vfs)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
```

### Steps to reproduce

```c#
services.AddDbContext<MyDbContext>(options => options.UseSqlite(configuration.GetConnectionString("Default")));
```

```c#
var dbContext = app.ApplicationServices.GetService<MyDbContext>();
dbContext.Migrate();
```

### Further technical details
EF Core version: 1.1.2
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10 Pro
IDE: Visual Studio 2017 15.7.4

**Comment by ajcvickers** [comment]
@dermeister0 SQLitePCL.raw is not used by EF Core 1.0 or 1.1. You'll need to update to 2.0 or preferably 2.1 to get this functionality.

**Comment by dermeister0** [comment]
Works with EF Core 2.1.

**Comment by patsadow2** [comment]
Doesnt work 2.0.2
