### ISSUE TITLE
Batch insert with SQL_Variant fails when different variant types are present

### ISSUE THREAD

**Issue by koenbeuk** [dotnet/efcore#12482]
Batch inserts seem to fail when SQL_Variant is being used and within the batch, different types are being used as params for sql_variant.

e.g. EF core generates something like the following:

```
CREATE TABLE [dbo].[Foos](Value SQL_VARIANT) 

DECLARE @p1 INT = 1;
DECLARE @p2 VARCHAR  = 'two';

INSERT INTO Foos
VALUES (@p2), (@p1)
```

This will raise an error: `Conversion failed when converting the varchar value 't' to data type int.`.
When P2 and P1 are reversed, things will work but only because INT is convertible to VARCHAR. Otherwise declaring both parameters as SQL_VARIANT will also work; Casting like ```VALUES (CAST(@p2 AS SQL_VARIANT)....)``` also works.

### Steps to reproduce

```c#
// Given a model
public class Foo
{
    public int Id { get; set; }

    [Column(TypeName = "sql_variant")]
    public object Value { get; set; }
}

// the following will throw:
context.Foos.Add(new Foo { Id = 1, Value = "one" });
context.Foos.Add(new Foo { Id = 2, Value = 2 });
   
```

causes:

```
Microsoft.EntityFrameworkCore.DbUpdateException: 'An error occurred while updating the entries. See the inner exception for details.'
>> SqlException: Error converting data type nvarchar to int.

Stack:
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

Given the above code, I wonder why the insert statement does not respect the explicit TypeName when declaring the SQL parameters and instead seems to use the implicit CLR <-> SQL mapping?

### Further technical details
EF Core version: 2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 X64
IDE: (e.g. Visual Studio 2017 15.7)

**Comment by ajcvickers** [comment]
@kbekkenutte I have not been able to reproduce this. Could you take a look at my repro code below and figure out what is missing to make it demonstrate the behavior you are seeing?

```C#
public class Blog
{
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public int Id { get; set; }

    [Column(TypeName = "sql_variant")]
    public object Name { get; set; }
}

public class BloggingContext : DbContext
{
    private static readonly LoggerFactory _logger
        = new LoggerFactory(new[] { new ConsoleLoggerProvider((_, __) => true, true) });

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseLoggerFactory(_logger)
            .EnableSensitiveDataLogging()
            .UseSqlServer(
                @"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0",
                a => a.MinBatchSize(2));
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>();
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.AddRange(
                new Blog { Id = 1, Name = "Olive" },
                new Blog { Id = 2, Name = "Toast" });

            context.SaveChanges();
        }
    }
}
```
Relavent output:
```sql
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (13ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE [Blog] (
          [Id] int NOT NULL,
          [Name] sql_variant NULL,
          CONSTRAINT [PK_Blog] PRIMARY KEY ([Id])
      );

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (66ms) [Parameters=[@p0='1', @p1='Olive' (Size = 5), @p2='2', @p3='Toast' (Size = 5)], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [Blog] ([Id], [Name])
      VALUES (@p0, @p1),
      (@p2, @p3);

```

**Comment by kbekkenutte** [comment]
@ajcvickers You can reproduce the issue by providing different types for different names, e.g.
```csharp
 context.AddRange(
                    new Blog { Id = 1, Name = 1 },
                    new Blog { Id = 2, Name = "test" });
```

This generates the following SQL:

```
exec sp_executesql N'SET NOCOUNT ON;
INSERT INTO [Blog] ([Id], [Name])
VALUES (@p0, @p1),
(@p2, @p3);
',N'@p0 int,@p1 int,@p2 int,@p3 nvarchar(4)',@p0=1,@p1=1,@p2=2,@p3=N'test'
```
p1 and p3 (both representing the name column in the example) and are of a different type which SQL Server doesn't seem to like. Declaring these parameters as sql_variant or explicitly converting them as such solves this issue.

**Comment by ajcvickers** [comment]
@kbekkenutte Thanks!

**Comment by john1452** [comment]
Hi is there a workaround for this issue ?

**Comment by kbekkenutte** [comment]
@john1452 You can suppress batching of updates while waiting for a fix, something like:
`...UseSqlServer(..., options => options.MinBatchSize(1));`

**Comment by yesmey** [comment]
We experienced this same issue.

The following code:
```
context.Blogs.AddRange(
	new Blog { Id = 1, Value = 10.0999 },
	new Blog { Id = 2, Value = 1233 },
	new Blog { Id = 3, Value = "String" },
	new Blog { Id = 4, Value = DateTime.Now });
```
Is producing the following sql query:
```
exec sp_executesql N'SET NOCOUNT ON;
INSERT INTO [Blogs] ([Id], [Name])
VALUES (@p0, @p1),
(@p2, @p3),
(@p4, @p5),
(@p6, @p7);
',N'@p0 int,@p1 float,@p2 int,@p3 int,@p4 int,@p5 nvarchar(6),@p6 int,@p7 datetime',@p0=1,@p1=10.0999,@p2=2,@p3=1233,@p4=3,@p5=N'String',@p6=4,@p7='2019-05-15 13:19:33.733'
```

Since SQL Server doesn't allow this. It would possible to just cast all parameters to sql_variant before by doing: (@p0, CAST(@p1 AS sql_variant)) for each row. It's also possible to simply insert all parameters with the datatype set to sql_variant.

Following diff implements the second option by always forcing DbType.Object on sql_variant columns:
```
diff --git a/src/EFCore.SqlServer/Storage/Internal/SqlServerSqlVariantTypeMapping.cs b/src/EFCore.SqlServer/Storage/Internal/SqlServerSqlVariantTypeMapping.cs
index e73991240..f1bd74bda 100644
--- a/src/EFCore.SqlServer/Storage/Internal/SqlServerSqlVariantTypeMapping.cs
+++ b/src/EFCore.SqlServer/Storage/Internal/SqlServerSqlVariantTypeMapping.cs
@@ -3,6 +3,7 @@
 
 using JetBrains.Annotations;
 using Microsoft.EntityFrameworkCore.Storage;
+using System.Data;
 
 namespace Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal
 {
@@ -44,5 +45,10 @@ protected SqlServerSqlVariantTypeMapping(RelationalTypeMappingParameters paramet
         /// <returns> The newly created mapping. </returns>
         protected override RelationalTypeMapping Clone(RelationalTypeMappingParameters parameters)
             => new SqlServerSqlVariantTypeMapping(parameters);
+
+        /// <summary>
+        ///     Gets the <see cref="System.Data.DbType" /> to be used.
+        /// </summary>
+        public override DbType? DbType { get; } = System.Data.DbType.Object;
     }
 }
```

I'm not sure this is the best way forward, but it solves our problem by generating the following statement:
```
exec sp_executesql N'SET NOCOUNT ON;
INSERT INTO [Blogs] ([Id], [Name])
VALUES (@p0, @p1),
(@p2, @p3),
(@p4, @p5),
(@p6, @p7);
',N'@p0 int,@p1 sql_variant,@p2 int,@p3 sql_variant,@p4 int,@p5 sql_variant,@p6 int,@p7 sql_variant',@p0=1,@p1=10.0999,@p2=2,@p3=1233,@p4=3,@p5=N'String',@p6=4,@p7='2019-05-15 13:18:57.8830000'
```

Wish to hear your opinion on this. Thanks

**Comment by aleripe** [comment]
Any news about that issue?

**Comment by ajcvickers** [comment]
@aleripe This issue is in the Backlog milestone. This means that it is not planned for the next release (EF Core 5.0). We will [re-assess the backlog](https://docs.microsoft.com/ef/core/what-is-new/release-planning) following the this release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by jnm2** [comment]
@ajcvickers Would you accept a pull request with the one-line fix proposed by @yesmey?

**Comment by AndriySvyryd** [comment]
@jnm2 I'm not sure it will be a one-line fix, but if you manage to do it and include tests then we'll consider it.

**Comment by yesmey** [comment]
Thanks for your comment. I started a pull request including a test scenario. And changed the code from overriding the DbType getter to passeing it through the constructor instead

**Comment by knautilus** [comment]
Could you please add this fix to 5.* version of efcore?

**Comment by ajcvickers** [comment]
@knautilus We only patch released versions for high-impact issues, for which this doesn't meet the bar. See [release planning](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning) for more details.
