### ISSUE TITLE
Overiding GenerateOrdering

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#12514]
I am writing an (other) EF Core provider.

A number of tests fail due to GenerateOrdering adding "(SELECT 1)" to the generated SQL.

How do I override this, without pulling in large amount of private code?
@smitpatel  ?

### Further technical details
EF Core version: 2.1
Database Provider: VistaDB (in progress)

**Comment by ErikEJ** [comment]
`
Test 'Microsoft.EntityFrameworkCore.Query.SimpleQueryVistaDBTest.OrderBy_true' failed: VistaDB.Diagnostic.VistaDBSQLException : 
Error 567 (Provider v. 5.6.8.0): Column does not exist:  (
Line #: 3; Column #: 10
Error 509 (Provider v. 5.6.8.0): Invalid or incomplete statement:  SELECT
Line #: 1; Column #: 1

---- VistaDB.Diagnostic.VistaDBSQLException : 
Error 567 (Provider v. 5.6.8.0): Column does not exist:  (
Line #: 3; Column #: 10

	at VistaDB.Engine.SQL.Statement.Parse(LocalSQLConnection connection, SQLParser parser)
	at VistaDB.Engine.SQL.Statement..ctor(LocalSQLConnection connection, Statement parent, SQLParser parser, Int64 id)
	at VistaDB.Engine.SQL.SelectStatement..ctor(LocalSQLConnection connection, Statement parent, SQLParser parser, Int64 id)
	at VistaDB.Engine.SQL.SelectStatement.CreateSelectStatement(LocalSQLConnection connection, Statement parent, SQLParser parser, Int64 id)
	at VistaDB.Engine.SQL.SelectStatementDescr.CreateStatement(LocalSQLConnection conn, Statement parent, SQLParser parser, Int64 id)
	at VistaDB.Engine.Internal.LocalSQLConnection.ParseStatement(Statement parent, Int64 id)
	at VistaDB.Engine.Internal.LocalSQLConnection.ParseStatementBatch(Int64 id)
	at VistaDB.Engine.Internal.LocalSQLConnection.CreateBatchStatement(String text, Int64 id)
	at VistaDB.Engine.Internal.LocalSQLConnection.VistaDB.Engine.Internal.ILocalSQLConnection.CreateQuery(String commandText)
	at VistaDB.Provider.VistaDBConnection.CreateQuery(String commandText)
	at VistaDB.Provider.VistaDBCommand.CreateQuery()
	at VistaDB.Provider.VistaDBCommand.PrepareQuery()
	at VistaDB.Provider.VistaDBCommand.ExecuteReader(CommandBehavior behavior)
	at VistaDB.Provider.VistaDBCommand.ExecuteDbDataReader(CommandBehavior behavior)
	at System.Data.Common.DbCommand.ExecuteReader()
	at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
	at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
	at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
	at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
	at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
	at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
	at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
	at Microsoft.EntityFrameworkCore.TestUtilities.QueryAsserter`1.<AssertQuery>d__18`1.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at Microsoft.EntityFrameworkCore.Query.QueryTestBase`1.AssertQuery[TItem1](Func`2 query, Func`2 elementSorter, Action`2 elementAsserter, Boolean assertOrder, Int32 entryCount)
	at Microsoft.EntityFrameworkCore.Query.SimpleQueryTestBase`1.OrderBy_true()
	at Microsoft.EntityFrameworkCore.Query.SimpleQueryVistaDBTest.OrderBy_true()
	----- Inner Stack Trace -----
	at VistaDB.Engine.SQL.SelectStatement.ParseOrderByClause(SQLParser parser)
	at VistaDB.Engine.SQL.SelectStatement.OnParse(LocalSQLConnection connection, SQLParser parser)
	at VistaDB.Engine.SQL.Statement.Parse(LocalSQLConnection connection, SQLParser parser)

Output from Microsoft.EntityFrameworkCore.Query.SimpleQueryVistaDBTest.OrderBy_true:
  Entity Framework Core 2.1.0-rtm-30799 initialized 'NorthwindRelationalContext' using provider 'VistaDB.EFCore' with options: SensitiveDataLoggingEnabled
  
  Compiling query model: 
  'from Customer c in DbSet<Customer>
  order by True asc
  select [c]'
  
  Optimized query model: 
  'from Customer c in DbSet<Customer>
  order by True asc
  select [c]'
  
  (QueryContext queryContext) => IEnumerable<Customer> _InterceptExceptions(
      source: IEnumerable<Customer> _TrackEntities(
          results: IEnumerable<Customer> _ShapedQuery(
              queryContext: queryContext, 
              shaperCommandContext: SelectExpression: 
                  SELECT [c].[CustomerID], [c].[Address], [c].[City], [c].[CompanyName], [c].[ContactName], [c].[ContactTitle], [c].[Country], [c].[Fax], [c].[Phone], [c].[PostalCode], [c].[Region]
                  FROM [Customers] AS [c]
                  ORDER BY (SELECT 1), 
              shaper: UnbufferedEntityShaper<Customer>), 
          queryContext: queryContext, 
          entityTrackingInfos: { itemType: Customer }, 
          entityAccessors: List<Func<Customer, object>> 
          { 
              Func<Customer, Customer>, 
          }
      ), 
      contextType: TestModels.Northwind.NorthwindRelationalContext, 
      logger: DiagnosticsLogger<Query>, 
      queryContext: queryContext)
  
  Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
  SELECT [c].[CustomerID], [c].[Address], [c].[City], [c].[CompanyName], [c].[ContactName], [c].[ContactTitle], [c].[Country], [c].[Fax], [c].[Phone], [c].[PostalCode], [c].[Region]
  FROM [Customers] AS [c]
  ORDER BY (SELECT 1)
  
  Failed executing DbCommand (88ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
  SELECT [c].[CustomerID], [c].[Address], [c].[City], [c].[CompanyName], [c].[ContactName], [c].[ContactTitle], [c].[Country], [c].[Fax], [c].[Phone], [c].[PostalCode], [c].[Region]
  FROM [Customers] AS [c]
  ORDER BY (SELECT 1)
  
  An exception occurred in the database while iterating the results of a query for context type 'Microsoft.EntityFrameworkCore.TestModels.Northwind.NorthwindRelationalContext'.
  VistaDB.Diagnostic.VistaDBSQLException (0x000001FD): 
  Error 567 (Provider v. 5.6.8.0): Column does not exist:  (
  Line #: 3; Column #: 10
  Error 509 (Provider v. 5.6.8.0): Invalid or incomplete statement:  SELECT
  Line #: 1; Column #: 1
   ---> VistaDB.Diagnostic.VistaDBSQLException (0x00000237): 
  Error 567 (Provider v. 5.6.8.0): Column does not exist:  (
  Line #: 3; Column #: 10
  
     at VistaDB.Engine.SQL.SelectStatement.ParseOrderByClause(SQLParser parser)
     at VistaDB.Engine.SQL.SelectStatement.OnParse(LocalSQLConnection connection, SQLParser parser)
     at VistaDB.Engine.SQL.Statement.Parse(LocalSQLConnection connection, SQLParser parser)
     at VistaDB.Engine.SQL.Statement.Parse(LocalSQLConnection connection, SQLParser parser)
     at VistaDB.Engine.SQL.Statement..ctor(LocalSQLConnection connection, Statement parent, SQLParser parser, Int64 id)
     at VistaDB.Engine.SQL.SelectStatement..ctor(LocalSQLConnection connection, Statement parent, SQLParser parser, Int64 id)
     at VistaDB.Engine.SQL.SelectStatement.CreateSelectStatement(LocalSQLConnection connection, Statement parent, SQLParser parser, Int64 id)
     at VistaDB.Engine.SQL.SelectStatementDescr.CreateStatement(LocalSQLConnection conn, Statement parent, SQLParser parser, Int64 id)
     at VistaDB.Engine.Internal.LocalSQLConnection.ParseStatement(Statement parent, Int64 id)
     at VistaDB.Engine.Internal.LocalSQLConnection.ParseStatementBatch(Int64 id)
     at VistaDB.Engine.Internal.LocalSQLConnection.CreateBatchStatement(String text, Int64 id)
     at VistaDB.Engine.Internal.LocalSQLConnection.VistaDB.Engine.Internal.ILocalSQLConnection.CreateQuery(String commandText)
     at VistaDB.Provider.VistaDBConnection.CreateQuery(String commandText)
     at VistaDB.Provider.VistaDBCommand.CreateQuery()
     at VistaDB.Provider.VistaDBCommand.PrepareQuery()
     at VistaDB.Provider.VistaDBCommand.ExecuteReader(CommandBehavior behavior)
     at VistaDB.Provider.VistaDBCommand.ExecuteDbDataReader(CommandBehavior behavior)
     at System.Data.Common.DbCommand.ExecuteReader()
     at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
     at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
     at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
     at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
     at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
     at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
     at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
  
  'NorthwindRelationalContext' disposed.

0 passed, 1 failed, 0 skipped, took 43,98 seconds (xUnit.net 2.3.1 build 3858).

`

**Comment by ErikEJ** [comment]
Never mind! Found a fix in another provider! 😄 
`
        protected override void GenerateOrdering(Ordering ordering)
        {
            if (ordering.Expression is ParameterExpression
                || ordering.Expression is ConstantExpression)
            {
                Sql.Append("GETDATE()");
            }
            else
            {
                base.GenerateOrdering(ordering);
            }
        }
`

**Comment by pmiddleton** [comment]
You should be able to override GenerateOrdering in your provider.

**Comment by pmiddleton** [comment]
oh haha - beat me by a minute :)
