### ISSUE TITLE
.Net-Core 2.1 DTC Escalation from same context

### ISSUE THREAD

**Issue by granthoff1107** [dotnet/efcore#12555]
I'm running some tests and I'm getting an error:
>"Distributed Transactions are not supported by this platform"

```C#
        private TransactionScope scope;
        [TestCleanup]
        public void TestCleanup()
        {
            this.scope.Dispose();
        }

        [TestInitialize]
        public void VerifyUsersHaveBeenSeeded()
        {
            var transactionOptions = new TransactionOptions { IsolationLevel = IsolationLevel.ReadCommitted };
            this.scope = new TransactionScope(TransactionScopeOption.Required, transactionOptions, TransactionScopeAsyncFlowOption.Enabled);
        }

        [TestMethod]
        public async Task Verify_RestEzService_Get_From_DI()
        {
                IServiceCollection services = this.GetRegisteredRestEzServiceCollection();
                services.RegisterRestService<User, UserDTO>(c => { });

                var serviceProvider = services.BuildServiceProvider();
                var context = serviceProvider.GetService<CustomContext>();
                var expectedResult = await context.Users.FirstAsync();

                var restEzService = serviceProvider.GetService<IRestEzService<User, UserDTO>>();
                await VerifyGetMethod(expectedResult, restEzService);
          }
```
The cause is that I'm using:                 
```C#
    var context = serviceProvider.GetService<CustomContext>();
```
and my Services Requests from the Service Collection a DbContext instead of my CustomContext, but my services register a CustomContext with the DI for DbContext 
```C#
    services.AddScoped<DbContext, CustomContext>(); 
```
I thought DTC Escalation only occurs when makes requests to seperate contexts,  Is this a bug?

Here's my call stack:
   >at System.Transactions.Distributed.DistributedTransactionManager.GetDistributedTransactionFromTransmitterPropagationToken(Byte[] propagationToken)
   at System.Transactions.TransactionInterop.GetDistributedTransactionFromTransmitterPropagationToken(Byte[] propagationToken)
   at System.Transactions.TransactionStatePSPEOperation.PSPEPromote(InternalTransaction tx)
   at System.Transactions.TransactionStateDelegatedBase.EnterState(InternalTransaction tx)
   at System.Transactions.EnlistableStates.Promote(InternalTransaction tx)
   at System.Transactions.Transaction.Promote()
   at System.Transactions.TransactionInterop.ConvertToDistributedTransaction(Transaction transaction)
   at System.Transactions.TransactionInterop.GetExportCookie(Transaction transaction, Byte[] whereabouts)
   at System.Data.SqlClient.SqlInternalConnection.GetTransactionCookie(Transaction transaction, Byte[] whereAbouts)
   at System.Data.SqlClient.SqlInternalConnection.EnlistNonNull(Transaction tx)
   at System.Data.SqlClient.SqlInternalConnection.Enlist(Transaction tx)
   at System.Data.SqlClient.SqlInternalConnectionTds.Activate(Transaction transaction)
   at System.Data.ProviderBase.DbConnectionPool.PrepareConnection(DbConnection owningObject, DbConnectionInternal obj, Transaction transaction)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
   at RestEzCore.Services.BaseRestEzService`3.Get(Object[] id) in

**Comment by ajcvickers** [comment]
@granthoff1107 This:
```C#
 services.AddScoped<DbContext, CustomContext>();
```
means register the service defined by the type `DbContext` as implemented as an instance of `CustomContext`. It specifically does not mean that CustomContext should be resolved from D.I., even though its constructor arguments _are_ resolved. Yes, this is confusing, but not something that EF can change.

So, this means that `CustomContext` and `DbContext` resolved from the same service provider will be two different instances. To get a single instance you have to tell D.I. explicitly to resolve `DbContext` from the service provider like this:
```C#
services.AddScoped<DbContext>(p => p.GetService<CustomContext>());
```

**Comment by granthoff1107** [comment]
@ajvickers, oops I was more confused about this because I thought it only occurred for different databases, but it’s for nested as well

**Comment by apacurariu-lobster** [comment]
@ajcvickers My question is, even if there are two different instances of the same context, as long as they're connecting to the same DB, the transaction still shouldn't be escalated to a distributed transaction, right? In EF 6 I can use multiple instances of the same or different DbContext-derived classes without escalating to a distributed transaction as long as I'm connecting to the same DB.

**Comment by ajcvickers** [comment]
@apacurariu-lobster There should not be any difference in EF Core, but see #14218
