### ISSUE TITLE
Query:  runtime error for queries with row number paging projecting a constant

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#12570]
query using Northwind model:

```
ctx.Customers.OrderBy(c => c.ContactName).Skip(5).Take(10).Select(e => "Foo").ToList();
```

Query plan:

```
(QueryContext queryContext) => IEnumerable<string> _InterceptExceptions(
|__ source: IEnumerable<string> _ShapedQuery(
|   |__ queryContext: queryContext, 
|   |__ shaperCommandContext: SelectExpression: 
|   |       SELECT [t].*
|   |       FROM (
|   |           SELECT [c].*, ROW_NUMBER() OVER(ORDER BY [c].[ContactName]) AS [__RowNumber__]
|   |           FROM [Customers] AS [c]
|   |       ) AS [t]
|   |       WHERE ([t].[__RowNumber__] > @__p_0) AND ([t].[__RowNumber__] <= (@__p_0 + @__p_1)), 
|   |__ shaper: (QueryContext queryContext | ValueBuffer c) => "Foo"), 
|__ contextType: TestModels.Northwind.NorthwindRelationalContext, 
|__ logger: DiagnosticsLogger<Query>, 
|__ queryContext: Unhandled parameter: queryContext)
```

exception:

```
System.InvalidOperationException : An exception occurred while reading a database value. The expected type was 'System.Int64' but the actual value was of type 'System.String'.
---- System.InvalidCastException : Specified cast is not valid.
	at Microsoft.EntityFrameworkCore.Storage.TypedRelationalValueBufferFactoryFactory.ThrowReadValueException[TValue](Exception exception, Object value, IPropertyBase property)
	at lambda_method(Closure , DbDataReader )
	at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
	at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
	at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
	at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
	at Microsoft.EntityFrameworkCore.Query.SimpleQueryTestBase`1.Skip_Take(Boolean isAsync)
	at Microsoft.EntityFrameworkCore.Query.RowNumberPagingTest.<>n__2(Boolean isAsync)
	at Microsoft.EntityFrameworkCore.Query.RowNumberPagingTest.<Skip_Take>d__4.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	----- Inner Stack Trace -----
	at System.Data.SqlClient.SqlBuffer.get_Int64()
	at System.Data.SqlClient.SqlDataReader.GetInt64(Int32 i)
	at lambda_method(Closure , DbDataReader )
```

**Comment by smitpatel** [comment]
Blocked on #16400

**Comment by smitpatel** [comment]
Rownumber paging has been removed.
