### ISSUE TITLE
Query: compilation error for queries with correlated collection into DTO and projecting navigation property afterwards

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#12591]
query:
```cs
                var query = ctx.Tags.Where(t => t.Note != "K.I.A.").Select(
                        t => new Squad
                        {
                            Id = t.Gear.SquadId
                        }).Select(e => e.Members);

```

exception:

```
Value cannot be null.
Parameter name: parentQuerySource
	at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
	at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.RegisterCorrelatedSubqueryMetadata(MainFromClause mainFromClause, Boolean trackingQuery, INavigation firstNavigation, INavigation collectionNavigation, IQuerySource parentQuerySource)
	at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CorrelatedCollectionFindingExpressionVisitor.<>c__DisplayClass7_0.<TryMarkSubQuery>b__0(IReadOnlyList`1 properties, IQuerySource querySource)
	at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindPropertyExpressionCore[TResult](Expression propertyExpression, IQuerySource querySource, Func`3 propertyBinder)
	at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindNavigationPathPropertyExpression[TResult](Expression propertyExpression, Func`3 propertyBinder)
	at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CorrelatedCollectionFindingExpressionVisitor.TryMarkSubQuery(SubQueryExpression expression)
	at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CorrelatedCollectionFindingExpressionVisitor.VisitMethodCall(MethodCallExpression node)
	at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
	at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	at Remotion.Linq.Clauses.SelectClause.TransformExpressions(Func`2 transformation)
	at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, Boolean asyncQuery)
	at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, Boolean asyncQuery)
	at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
	at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
	at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
	at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
	at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
	at Remotion.Linq.QueryableBase`1.GetEnumerator()
	at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
	at Microsoft.EntityFrameworkCore.Query.GearsOfWarQueryTestBase`1.Optional_navigation_type_compensation_works_with_DTOs(Boolean isAsync)
	at Microsoft.EntityFrameworkCore.Query.GearsOfWarQuerySqlServerTest.<>n__137(Boolean isAsync)
	at Microsoft.EntityFrameworkCore.Query.GearsOfWarQuerySqlServerTest.<Optional_navigation_type_compensation_works_with_DTOs>d__149.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by bradmarder** [comment]
I'm hitting this exception frequently. I created a self-contained repo if it helps.

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Console;

namespace EFCoreBugs
{
    class Program
    {
        static async Task Main(string[] args)
        {
            using (var db = new TestDb())
            {
                await db.Database.EnsureDeletedAsync();
                await db.Database.EnsureCreatedAsync();
            }

            using (var db = new TestDb())
            {
                db.Blogs
                    .Select(blog => new
                    {
                        blog.BlogPosts
                            .Select(x => x.Post)
                            .FirstOrDefault()
                            .Images
                    })
                    .ToList();
            }
        }
    }

    public class TestDb : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var log = new LoggerFactory(new[] { new ConsoleLoggerProvider((_, __) => __ == LogLevel.Error, true) });
            optionsBuilder.UseLoggerFactory(log);
            optionsBuilder.UseInMemoryDatabase("Test");
        }
    }

    public class Blog
    {
        public int Id { get; set; }
        public virtual ICollection<BlogPosts> BlogPosts { get; } = new HashSet<BlogPosts>();
    }
    public class Post
    {
        public int Id { get; set; }
        public virtual ICollection<Image> Images { get; } = new HashSet<Image>();
    }
    public class Image
    {
        public int Id { get; set; }
        public int PostId { get; set; }
        public virtual Post Post { get; set; }
    }
    public class BlogPosts
    {
        public int Id { get; set; }
        public int BlogId { get; set; }
        public int PostId { get; set; }
        public virtual Post Post { get; set; }
        public virtual Blog Blog { get; set; }
    }
}
```

**Comment by smitpatel** [comment]
We should throw error for this. We don't expand navigations on entity constructed using new.

@maumar - thoughts?

**Comment by smitpatel** [comment]
In current master, we evaluate it without exception. Since both are select, we client eval `Members` which will be null or empty list whatever is default for new-ed up Squad. By design in 3.x pipeline we decided that any constructed type will be considered nominal type regardless of it being mapped as entity type in the model.

**Comment by smitpatel** [comment]
@bradmarder - The repo you posted works fine in 5.0 release 
Generated SQL
```SQL
      SELECT [t0].[c], [b].[Id], [t0].[Id], [t0].[Id0], [i].[Id], [i].[PostId]
      FROM [Blogs] AS [b]
      LEFT JOIN (
          SELECT [t].[c], [t].[Id], [t].[Id0], [t].[BlogId]
          FROM (
              SELECT 1 AS [c], [b0].[Id], [p].[Id] AS [Id0], [b0].[BlogId], ROW_NUMBER() OVER(PARTITION BY [b0].[BlogId] ORDER BY [b0].[Id], [p].[Id]) AS [row]
              FROM [BlogPosts] AS [b0]
              INNER JOIN [Post] AS [p] ON [b0].[PostId] = [p].[Id]
          ) AS [t]
          WHERE [t].[row] <= 1
      ) AS [t0] ON [b].[Id] = [t0].[BlogId]
      LEFT JOIN [Image] AS [i] ON [t0].[Id0] = [i].[PostId]
      ORDER BY [b].[Id], [t0].[Id], [t0].[Id0], [i].[Id]
```
