### ISSUE TITLE
EF Core 2.1.1 - GroupBy throws a NullReferenceException

### ISSUE THREAD

**Issue by brunolau** [dotnet/efcore#12711]
Calling GroupBy on IQueryable results in NullReferenceException when projecting to my model

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Object reference not set to an instance of an object.

Stack trace:
   at lambda_method(Closure , IGrouping`2 )
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EfCoreErrReproduction.Program.Main(String[] args) in c:\users\bruno\source\repos\EfCoreErrReproduction\EfCoreErrReproduction\Program.cs:line 28
```

### Steps to reproduce

[EfCoreErrReproduction.zip](https://github.com/aspnet/EntityFrameworkCore/files/2207591/EfCoreErrReproduction.zip)

```c#
using System.Linq;

namespace EfCoreErrReproduction
{
    class Program
    {
        static void Main(string[] args)
        {
            var db = new StrippedDownContext();
            var ticketNumbersQuery = db.TicketNumbers.Where(p => p.Id < 1000);
            var ticketDateQuery = ticketNumbersQuery.GroupBy(p => p.TicketDate).Select(p => new
            {
                Id = p.Key.Id,
                TicketId = p.Key.Ticket.Id,
                VAT = p.Key.Ticket.VAT,
                EventDateId = p.Key.EventDate.Id,
                StartTime = p.Key.EventDate.StartTime,
                EventName = p.Key.Ticket.Event.Name,
                EventId = p.Key.Ticket.Event.Id,
                InstanceId = p.Key.Ticket.Event.InstanceId,
                Count = p.Count()
            });

            var crash = ticketDateQuery.ToList();
        }
    }
}

using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

namespace EfCoreErrReproduction
{
    public class StrippedDownContext : DbContext
    {
        public StrippedDownContext()
        {
        }

        public StrippedDownContext(DbContextOptions<StrippedDownContext> options)
            : base(options)
        {
        }


        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventDate> EventDates { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<TicketDate> TicketDates { get; set; }
        public virtual DbSet<TicketNumber> TicketNumbers { get; set; }


        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("db conn string");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {


            modelBuilder.Entity<Event>(entity =>
            {
                entity.ToTable("Event");

                entity.HasIndex(e => e.InstanceId);
                entity.Property(e => e.Id).HasColumnName("ID");
                entity.Property(e => e.Name).IsRequired().HasMaxLength(75);
            });

            modelBuilder.Entity<EventDate>(entity =>
            {
                entity.ToTable("EventDate");

                entity.HasIndex(e => e.EventId).HasName("IX_EventDate");
                entity.Property(e => e.StartTime).HasColumnType("datetime");

                entity.HasOne(d => d.Event)
                    .WithMany(p => p.EventDates)
                    .HasForeignKey(d => d.EventId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_EventDate_Event");
            });

            modelBuilder.Entity<Ticket>(entity =>
            {
                entity.ToTable("Ticket");

                entity.HasIndex(e => e.EventId).HasName("IX_Ticket_EventID");

                entity.Property(e => e.Id).HasColumnName("ID");
                entity.Property(e => e.EventId).HasColumnName("EventID");
                entity.Property(e => e.VAT).HasColumnName("VAT");

                entity.HasOne(d => d.Event)
                    .WithMany(p => p.Tickets)
                    .HasForeignKey(d => d.EventId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Ticket_Event");
            });

            modelBuilder.Entity<TicketDate>(entity =>
            {
                entity.ToTable("TicketDate");

                entity.HasOne(d => d.EventDate)
                    .WithMany(p => p.TicketDates)
                    .HasForeignKey(d => d.EventDateId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_TicketDate_EventDate");

                entity.HasOne(d => d.Ticket)
                    .WithMany(p => p.TicketDates)
                    .HasForeignKey(d => d.TicketId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_TicketDate_Ticket");
            });

            modelBuilder.Entity<TicketNumber>(entity =>
            {
                entity.ToTable("TicketNumber");
                entity.HasOne(e => e.TicketDate)
                   .WithMany(e => e.TicketNumbers)
                   .HasForeignKey(e => e.TicketDateId);
            });
        }
    }

    public class Event
    {
        public int Id { get; set; }
        public int InstanceId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<EventDate> EventDates { get; set; } = new HashSet<EventDate>();
        public virtual ICollection<Ticket> Tickets { get; set; } = new HashSet<Ticket>();
    }

    public class EventDate
    {
        public int Id { get; set; }
        public DateTime StartTime { get; set; }
        public int EventId { get; set; }

        public virtual Event Event { get; set; }
        public virtual ICollection<TicketDate> TicketDates { get; set; } = new HashSet<TicketDate>();
    }

    public class Ticket
    {
        public int Id { get; set; }
        public double VAT { get; set; }
        public int EventId { get; set; }
        public virtual Event Event { get; set; }
        public virtual ICollection<TicketDate> TicketDates { get; set; } = new HashSet<TicketDate>();
    }

    public class TicketDate
    {
        public int Id { get; set; }
        public int TicketId { get; set; }
        public virtual Ticket Ticket { get; set; }

        public int EventDateId { get; set; }
        public virtual EventDate EventDate { get; set; }
        public virtual ICollection<TicketNumber> TicketNumbers { get; set; } = new HashSet<TicketNumber>();
    }

    public class TicketNumber
    {
        public int Id { get; set; }
        public int TicketDateId { get; set; }
        public virtual TicketDate TicketDate { get; set; }
    }
}

```

### Further technical details
EF Core version: 2.1.1, targetFramework="net461"
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Enterprise 64-Bit (10.0.17134 Build 17134)
IDE: (e.g. Visual Studio 2017 15.7.3)

**Comment by maumar** [comment]
Sample data that can be used to reproduce this:

```
                var tn1111 = new TicketNumber();
                var tn1112 = new TicketNumber();

                var tn1121 = new TicketNumber();
                var tn1122 = new TicketNumber();

                var td111 = new TicketDate { TicketNumbers = new List<TicketNumber> { tn1111, tn1112 } };
                var td112 = new TicketDate { TicketNumbers = new List<TicketNumber> { tn1121, tn1122 } };

                var t111 = new Ticket { VAT = 22, TicketDates = new List<TicketDate> { td111, td112 } };

                var ed11 = new EventDate { StartTime = DateTime.Now, TicketDates = new List<TicketDate> { td111, td112 } };

                var e1 = new Event { EventDates = new List<EventDate> { ed11 }, Name = "e1", Tickets = new List<Ticket> { t111 } };

                ctx.TicketNumbers.AddRange(tn1111, tn1112, tn1121, tn1122);
                ctx.TicketDates.AddRange(td111, td112);
                ctx.Tickets.AddRange(t111);
                ctx.EventDates.AddRange(ed11);
                ctx.Events.AddRange(e1);
                ctx.SaveChanges();
```

Query plan:

```
(QueryContext queryContext) => IEnumerable<<>f__AnonymousType0<int, int, double, int, DateTime, string, int, int, int>> _InterceptExceptions(
|__ source: IEnumerable<<>f__AnonymousType0<int, int, double, int, DateTime, string, int, int, int>> _Select(
|   |__ source: IEnumerable<IGrouping<TicketDate, ValueBuffer>> _GroupBy(
|   |   |__ source: IEnumerable<TransparentIdentifier<ValueBuffer, TicketDate>> _ShapedQuery(
|   |   |   |__ queryContext: queryContext, 
|   |   |   |__ shaperCommandContext: SelectExpression: 
|   |   |   |       SELECT [p.TicketDate].[Id], [p.TicketDate].[EventDateId], [p.TicketDate].[TicketId]
|   |   |   |       FROM [TicketNumber] AS [p]
|   |   |   |       INNER JOIN [TicketDate] AS [p.TicketDate] ON [p].[TicketDateId] = [p.TicketDate].[Id]
|   |   |   |       WHERE [p].[Id] < 1000
|   |   |   |       ORDER BY [p.TicketDate].[Id], 
|   |   |   |__ shaper: (ValueBuffer p | TicketDate p.TicketDate) => TransparentIdentifier<ValueBuffer, TicketDate> CreateTransparentIdentifier(
|   |   |       |__ outer: p, 
|   |   |       |__ inner: p.TicketDate)), 
|   |   |__ keySelector: (TransparentIdentifier<ValueBuffer, TicketDate> t0) => t0.Inner, 
|   |   |__ elementSelector: (TransparentIdentifier<ValueBuffer, TicketDate> t0) => t0.Outer), 
|   |__ selector: (IGrouping<TicketDate, ValueBuffer> p) => new { 
|           p.Key.Id, 
|           p.Key.Ticket.Id, 
|           p.Key.Ticket.VAT, 
|           p.Key.EventDate.Id, 
|           p.Key.EventDate.StartTime, 
|           p.Key.Ticket.Event.Name, 
|           p.Key.Ticket.Event.Id, 
|           p.Key.Ticket.Event.InstanceId, 
|           int Count(p)
|        }), 
|__ contextType: Repro12711.MyContext, 
|__ logger: DiagnosticsLogger<Query>, 
|__ queryContext: queryContext)
```

**Comment by maumar** [comment]
Workaround is to include the navigations and perform GroupBy operation on the client (EF will try to perform it on the client anyway), like so:

```cs

                var ticketNumbersQuery = ctx.TicketNumbers.Include(tn => tn.TicketDate.EventDate).Include(tn => tn.TicketDate.Ticket.Event).Where(p => p.Id < 1000).ToList();
                var ticketDateQuery = ticketNumbersQuery.GroupBy(p => p.TicketDate).Select(p => new
                {
                    Id = p.Key.Id,
                    TicketId = p.Key.Ticket.Id,
                    VAT = p.Key.Ticket.VAT,
                    EventDateId = p.Key.EventDate.Id,
                    StartTime = p.Key.EventDate.StartTime,
                    EventName = p.Key.Ticket.Event.Name,
                    EventId = p.Key.Ticket.Event.Id,
                    InstanceId = p.Key.Ticket.Event.InstanceId,
                    Count = p.Count()
                });

                var works = ticketDateQuery.ToList();
```

**Comment by maumar** [comment]
work tracked by https://github.com/aspnet/EntityFrameworkCore/issues/15938
