### ISSUE TITLE
System.InvalidOperationException: A second operation started on this context before a previous operation completed

### ISSUE THREAD

**Issue by hippiehunter** [dotnet/efcore#12730]
Ive built my own EF Core provider, Loosely based off the InMemory provider and I'm trying to get compiled queries to work. I've cut things down to the bare minimum and its not even doing a real query anymore but still it ends up failing trying to run the query. Is there some obvious reason in this log why I wouldn't be able to run a compiled query? Also, to clarify there are no other operations occurring and this happens the first time I try to compile and then run a query.

```
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.0-rtm-30799 initialized 'DbContext' using provider 'Harmony.Core.EF' with options: StoreName=
dbug: Microsoft.EntityFrameworkCore.Query[10101]
      => Harmony.Core.EF.Query.Internal.HarmonyQueryModelVisitor
      Compiling query model:
      '(from Customer entity in __queryable
      where [entity].CustKey == __keyValue
      select [entity]).FirstOrDefault()'
dbug: Microsoft.EntityFrameworkCore.Query[10104]
      => Harmony.Core.EF.Query.Internal.HarmonyQueryModelVisitor
      Optimized query model:
      '(from Customer entity in __queryable
      where [entity].CustKey == __keyValue
      select [entity]).FirstOrDefault()'
dbug: Microsoft.EntityFrameworkCore.Query[10107]
      => Harmony.Core.EF.Query.Internal.HarmonyQueryModelVisitor
      (QueryContext queryContext) => IEnumerable<Customer> _InterceptExceptions(
          source: IEnumerable<Customer> _ToSequence(() => Customer FirstOrDefault(IEnumerable<Customer> _Where(
                      source: IQueryable<Customer> GetParameterValue(
                          queryContext: queryContext,
                          parameterName: "__queryable"),
                      predicate: (Customer entity) => entity.CustKey == int GetParameterValue(
                          queryContext: queryContext,
                          parameterName: "__keyValue")))),
          contextType: SampleServices.DbContext,
          logger: DiagnosticsLogger<Query>,
          queryContext: queryContext)
dbug: Microsoft.EntityFrameworkCore.Query[10101]
      => Harmony.Core.EF.Query.Internal.HarmonyQueryModelVisitor
      Compiling query model:
      'from Customer <generated>_0 in DbSet<Customer>
      select [<generated>_0]'
dbug: Microsoft.EntityFrameworkCore.Query[10104]
      => Harmony.Core.EF.Query.Internal.HarmonyQueryModelVisitor
      Optimized query model:
      'from Customer <generated>_1 in DbSet<Customer>
      where
      {
          return Property([<generated>_1], "CustRtype") == 0
      }

      select [<generated>_1]'
dbug: Microsoft.EntityFrameworkCore.Query[10107]
      => Harmony.Core.EF.Query.Internal.HarmonyQueryModelVisitor
      (QueryContext queryContext) => IEnumerable<Customer> _InterceptExceptions(
          source: IEnumerable<Customer> _Where(
              source: IEnumerable<Customer> Empty(),
              predicate: (Customer <generated>_1) =>
              {
                  return int GetValueFromEntity(
                      clrPropertyGetter: ClrPropertyGetter<Customer, int>,
                      entity: <generated>_1) == 0
              }
          ),
          contextType: SampleServices.DbContext,
          logger: DiagnosticsLogger<Query>,
          queryContext: queryContext)
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred in the database while iterating the results of a query for context type 'SampleServices.DbContext'.
      System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
         at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
         at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
         at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
         at lambda_method(Closure )
         at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
         at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at lambda_method(Closure )
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()

Unhandled Exception: fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred in the database while iterating the results of a query for context type 'SampleServices.DbContext'.
      System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
         at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
         at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
         at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
         at lambda_method(Closure )
         at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
         at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
         at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
         at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safeSystem.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at lambda_method(Closure )
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryBase`2.ExecuteCore(TContext context, CancellationToken cancellationToken, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryBase`2.ExecuteCore(TContext context, Object[] parameters)
   at Harmony.Core.EF.Extensions.HarmonyDbSetExtensions.FindCompiled[C,K,T](DbSet`1 thisp, C context, K keyValue) in C:\Users\greenej\Source\Repos\HarmonyCore\HarmonyCoreEF\Extensions\HarmonyDbSetExtensions.cs:line 65
   at _NS_SampleServices_Test._CL.MAIN$UNITTESTENVIRONMENT(String[] args) in C:\Users\greenej\Source\Repos\HarmonyCore\SampleServices.Test\UnitTestEnvironment.dbl:line 81.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at lambda_method(Closure )
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetE
numerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
```

and here is the compiled query construction
```
public static T FindCompiled<C, K, T>(this DbSet<T> thisp, C context, K keyValue) 
            where T : class
            where C : DbContext
        {
            var entityType = context.Model.FindEntityType(typeof(T));
            var primaryKey = entityType.FindPrimaryKey();
            var primaryKeyName = primaryKey.Properties.First().Name;
            var compiledQueryLookup = _compiledFindQueryLookup.GetOrAdd(typeof(C), (ty) => new ConcurrentDictionary<Type, object>());
            var compiledQuery = compiledQueryLookup.GetOrAdd(typeof(T), (ty) =>
            {
                var keyParameter = Expression.Parameter(typeof(K), "keyValue");
                var contextParameter = Expression.Parameter(typeof(C), "context");
                var querableParameter = Expression.Parameter(typeof(IQueryable<T>), "queryable");
                var entityParameter = Expression.Parameter(typeof(T), "entity");
                Expression whereClause = Expression.Equal(
                        Expression.Property(entityParameter, primaryKeyName),
                        keyParameter);

                var whereLambda = Expression.Lambda<Func<T, bool>>(whereClause, entityParameter);
                var whereCall = Expression.Call(typeof(System.Linq.Queryable), "Where", new Type[] { typeof(T) }, querableParameter, whereLambda);
                var firstOrDefaultResult = Expression.Call(typeof(System.Linq.Queryable), "FirstOrDefault", new Type[] { typeof(T) }, whereCall);
                var resultLambda = Expression.Lambda<Func<C, K, IQueryable<T>, T>>(firstOrDefaultResult, contextParameter, keyParameter, querableParameter);
                return Microsoft.EntityFrameworkCore.EF.CompileQuery(resultLambda);
            }) as Func<C, K, IQueryable<T>, T>;

            if (context.ChangeTracker.QueryTrackingBehavior != QueryTrackingBehavior.NoTracking)
            {
                // Execute against the in-memory entities, which we get from ChangeTracker (but not filtering the state of the entities).
                var entries = context.ChangeTracker.Entries<T>().Select((EntityEntry e) => (T)e.Entity);
                T entity = compiledQuery(context, keyValue, entries.AsQueryable());

                // If found in memory then we're done.
                if (entity != null) { return entity; }
            }

            // Otherwise execute the query against the database.
            return compiledQuery(context, keyValue, thisp);
        }
```

### Further technical details
EF Core version: 2.1.0
Database Provider: HarmonyCore
Operating system: Windows 10 1803
IDE: Visual Studio 2017 15.8

**Comment by smitpatel** [comment]
Issue is this
```
'(from Customer entity in __queryable
      where [entity].CustKey == __keyValue
      select [entity]).FirstOrDefault()'
```
The IQueryable you are passing is not of type DbSet or EntityQueryable from EF Core so funcletizer generates parameter for it (It should not do that). Hence once the query is compiled and being executed, it will try to get the value of parameter `__queryable` which will trigger another query (while you are still executing first query), That's the exception you are getting.

If you look at the `CompileQuery` function EF Core provides you will realize that it works with DbContext level rather than taking IQueryable as a parameter to the func. Perhaps that is what causing the issue.
You need to investigate into `ParameterExtractingExpressionVisitor` to see why you are getting parameter for EntityQueryable and what is incorrect in generated ExpressionTree.
