### ISSUE TITLE
Code First with MySQL does not create tables

### ISSUE THREAD

**Issue by heldersepu** [dotnet/efcore#12847]
Trying to create a code first project using Entity Framework and MySQL.
When I use context.Database.EnsureCreated(); the tables are created correctly, but I would like to use migrations so the code changes to: context.Database.Migrate(); and that is when I get the error:

MySqlException: Table 'library.publishers' doesn't exist
I was told that I need to execute `Add-Migration InitialCreate` that did not work I was getting:
> Add-Migration : The term 'Add-Migration' is not recognized as the name of a cmdle

Found a way around that (running: .nuget\packages\microsoft.entityframeworkcore.tools\2.1.1\tools\init.ps1)
Then got one more error about a missing package: 

> Your startup project 'mySqlEFcore' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work

Added that package and now I get a new error:

```
System.MissingMethodException: Method not found: 'Void Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory..ctor(Microsoft.EntityFrameworkCore.Diagnostics.IDiagnosticsLogger`1<Command>, Microsoft.EntityFrameworkCore.Storage.IRelationalTypeMapper)'.
   at MySql.Data.EntityFrameworkCore.Storage.Internal.MySQLCommandBuilderFactory..ctor(IDiagnosticsLogger`1 logger, IRelationalTypeMapper typeMapper)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
...
```

### Steps to reproduce
I have project reproducing the issue here:
https://github.com/heldersepu/csharp-proj/tree/PreDocDB/mySqlEFcore

### Further technical details
EF Core version: `<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.1" />`
Database Provider: `<PackageReference Include="MySql.Data.EntityFrameworkCore" Version="8.0.12" />`
Operating system: Win 10
IDE:  Visual Studio 2017

**Comment by smitpatel** [comment]
This is an issue in MySQL package you are using. Please file an issue with them.

**Comment by ajcvickers** [comment]
@heldersepu Also, you might want to try a different MySQL provider. People seem to have success with the Pomelo open-source provider: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql It has been updated to work with 2.1.1.

**Comment by heldersepu** [comment]
Thanks @ajcvickers will try with that provider!
