### ISSUE TITLE
Navigation property NRE when accessed within same request entity was created

### ISSUE THREAD

**Issue by tstivers1990** [dotnet/efcore#12845]
Upon creating an entity and adding it to the database with EF Core 2.1, I would like to display the entity that was added. When attempting to access navigation properties on the entity that was created, a NullReferenceException is thrown. Navigation properties on entities that existed prior to the request work as expected, and navigation properties on the entity that was created work fine in the next request.

```
Exception message: Object reference not set to an instance of an object.
Stack trace:
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at MixTheJuice.Web.Pages.Admin.Pages_Admin_Vendors.ExecuteAsync() in C:\Users\tonys\Documents\Projects\MixTheJuice\MixTheJuice.Web\Pages\Admin\Vendors.cshtml:line 114
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Steps to reproduce

Create an entity.
Add the entity to the database with EF.
Call SaveChanges.
Load all entities from the table and put them in a List<TEntity>.
Iterate through the list, accessing a navigation property on the entity.
Observe NullReferenceException in your face when attempting to access the navigation property on the newly created entity.

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by tstivers1990** [comment]
It's also relevant that the navigation property in question is the many part of a one-to-many relationship. In this instance, there are no members of this relationship.

**Comment by tstivers1990** [comment]
#12389 Seems related. However, the major difference in my case is that I'm not directly accessing the created entity. IE: I'm **not** doing the following:

```cs
var entity = new SomeEntity { Id = 1 };
context.SomeEntities.Add(entity);
context.SaveChanges();

var t = entity.SomeNavigationProperty;
```

In my case, I'm adding the entity via `Add` and then afterwards I'm using `GetAll()` to load all entities from the table into a list, then iterating through that list. So, as far as I know, it should be able to return an entity with lazy loading proxies set up, but doesn't appear to be doing so.

**Comment by ajcvickers** [comment]
@tstivers1990 This is the same case as #12389. Once an instance of a given entity is tracked by the context, then that same instance is returned even if is part of query results from the database. As stated in the answer to that issue, the options are to not use proxy-less lazy loading or to create the instance as a proxy. You could also detach the entity after calling SaveChanges to force the query to create a new instance, or register you DbContext as transient so as to use different context instances for the Add and the query.
