### ISSUE TITLE
Query: compilation error (NRE) for queries with query types and join

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#12874]
query:

```cs
                var query = (from ov in ctx.Query<OrderQuery>()
                             where ov.CustomerID == "ALFKI"
                             select ov).Join(from ov in ctx.Query<OrderQuery>()
                                             where ov.CustomerID == "ALFKI"
                                             select ov, o => o, i => i, (o, i) => o);

                var result = query.ToList();

```

exception:

```
Object reference not set to an instance of an object.
	at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.EntityQsreToKeyAccessConvertingQueryModelVisitor.TryGetEntityPrimaryKeys(IQuerySource querySource, IReadOnlyList`1& keyProperties)
	at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.EntityQsreToKeyAccessConvertingQueryModelVisitor.VisitJoinClause(JoinClause joinClause, QueryModel queryModel, Int32 index)
	at Remotion.Linq.Clauses.JoinClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
	at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
	at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
	at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.EntityQsreToKeyAccessConvertingQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
	at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, Boolean asyncQuery)
	at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, Boolean asyncQuery)
	at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
	at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
	at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
	at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
	at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
	at Remotion.Linq.QueryableBase`1.System.Collections.IEnumerable.GetEnumerator()
```

When we VisitJoinClause calls into TryGetEntityPrimaryKeys which assumes that entity type will always have primary keys. This is not the case for query types, which show up as entity types but their FindPrimaryKey() method doesn't yield any results.

**Comment by maumar** [comment]
related to https://github.com/aspnet/EntityFrameworkCore/issues/12873
