### ISSUE TITLE
Value Conversion does not create the table relationship and setting it up explicit throws error

### ISSUE THREAD

**Issue by RCristiam** [dotnet/efcore#12983]
When I try to add a Conversion using EF Core 2.1, the migration created does not create the relationship between the desired tables.

If I try to add the relationship explicity, the migration is showing the following error: 

System.InvalidOperationException: The property or navigation 'InspectionDataType' cannot be added to the entity type 'InspectionType' because a property or navigation with the same name already exists on entity type 'InspectionType'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.AddNavigation(PropertyIdentity propertyIdentity, ForeignKey foreignKey, Boolean pointsToPrincipal)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKey.Navigation(Nullable`1 propertyIdentity, ConfigurationSource configurationSource, Boolean pointsToPrincipal)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKey.HasDependentToPrincipal(MemberInfo property, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.Navigations(Nullable`1 navigationToPrincipal, Nullable`1 navigationToDependent, EntityType principalEntityType, EntityType dependentEntityType, Nullable`1 configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.Navigations(Nullable`1 navigationToPrincipal, Nullable`1 navigationToDependent, Nullable`1 configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.DependentToPrincipal(MemberInfo property, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Relationship(InternalEntityTypeBuilder targetEntityTypeBuilder, Nullable`1 navigationToTarget, Nullable`1 inverseNavigation, Boolean setTargetAsPrincipal, ConfigurationSource configurationSource, Nullable`1 required)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Navigation(InternalEntityTypeBuilder targetEntityTypeBuilder, PropertyInfo navigationProperty, ConfigurationSource configurationSource, Boolean setTargetAsPrincipal)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.HasOne[TRelatedEntity](Expression`1 navigationExpression)
   at Pat.Model.Movement.Context.Extensions.MovementContextExtensions.ConfigureRelationships(ModelBuilder modelBuilder) in D:\Orbita\PatSuite_Model\Pat.Model.Movement.Context\Extensions\MovementContextExtensions.cs:line 262
   at Pat.Model.Movement.Context.MovementContext.OnModelCreating(ModelBuilder modelBuilder) in D:\Orbita\PatSuite_Model\Pat.Model.Movement.Context\MovementContext.cs:line 68
   at Pat.Model.Movement.Context.Tool.AppDbContext.OnModelCreating(ModelBuilder modelBuilder) in D:\Orbita\PatSuite_Model\Pat.Model.Movement.Context.Tool\AppDbContext.cs:line 41
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The property or navigation 'InspectionDataType' cannot be added to the entity type 'InspectionType' because a property or navigation with the same name already exists on entity type 'InspectionType'.

### Steps to reproduce
    
```C#
    public class InspectionType 
    {
        public InspectionDataType InspectionDataType { get; set; }
    }

    public sealed class InspectionDataType
    {

        public InspectionDataType()
        {

        }
        private InspectionDataType(int id, string description, string longDescription)
        {
             Id = id; 
            Description = description;
            LongDescription = longDescription;
        }
        public int Id { get; private set; }

        public string Description { get; private set; }

        public string LongDescription { get; private set; }

        public static readonly InspectionDataType Boolean = new InspectionDataType(1, "Boolean", "Boolean data type");
        public static readonly InspectionDataType String = new InspectionDataType(2, "String", "String data type");
        public static readonly InspectionDataType Int = new InspectionDataType(3, "Int", "Int data type");
        public static readonly InspectionDataType DateTime = new InspectionDataType(4, "DateTime", "DateTime data type");
        public static readonly InspectionDataType Float = new InspectionDataType(5, "Float", "Float data type");
        public static InspectionDataType Parse(int value)
        {
            switch (value)
            {
                case 1: return Boolean;
                case 2: return String;
                case 3: return Int;
                case 4: return DateTime;
                case 5: return Float;
                default:
                    throw new InvalidCastException($"The value {value} cannot be convert to {nameof(InspectionDataType)}");
            }
        }
    }
```
The ModelBuilderConfiguration:

```C#
    modelBuilder
                .Entity<InspectionType>()
                .Property(p => p.InspectionDataType)
                .HasConversion(
                    v => v.Id,
                    v => InspectionDataType.Parse(v)
                );

    modelBuilder.Entity<InspectionType>()
                .HasOne(it => it.InspectionDataType)
                .WithMany()
                .IsRequired(true);
```

### Further technical details
EF Core version: 2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: 
IDE: Visual Studio 2017 15.7.5

**Comment by ajcvickers** [comment]
@RCristiam Value conversions are used to convert a value of a simple property of an entity into a type/value that can be saved to a database column. `HasOne`/`WithMany` is used to define a relationship between two entity types. The code above attempts to both use a value conversion for the `InspectionDataType` property, implying that `InspectionDataType` is not an entity type, and setup `InspectionDataType` as a navigation property to `InspectionDataType`, implying that it is an entity type. This is not valid--it's one or the other.

Another way of putting this is, if you want to create a table for `InspectionDataType`, then don't setup a value converter for it. Instead define a relationship in the normal way. On the other hand, if you want to have a property of type `InspectionDataType` that results in a column in the database, then use a converter.
