### ISSUE TITLE
SaveChanges fails due to a foreign key constraint when using navigation properties.

### ISSUE THREAD

**Issue by JackSteel97** [dotnet/efcore#12995]
### Steps to reproduce
The SQL Server database is set up with foreign keys on `node_categories.node_id` and `node_categories.category_code` to their respective columns in `nodes` and `categories` that cascade on update and on delete.

From what I can tell this issue is occuring because Entity Framework tries to insert the data for `Node n` before it inserts the nodes navigation property `Categories`

```c#
// Database Model setup
public class Node{
    public List<NodeCategory> Categories { get; set; }
    public string NodeId { get; set; }
}

public class Category{
    public long RowId { get; set; } = 0
    public string Code { get; set; }
    public string Name{ get; set; }
    public List<NodeCategory> CategorisedNodes { get; set; }
}

public class NodeCategory{
    public string CategoryCode { get; set; }
    public string NodeId { get; set; }
    public Category Category { get; set; }
    public Node Node { get; set; }
}

// ... in OnModelCreating()
 modelBuilder.Entity<NodeCategory>(entity =>
            {
                entity.HasKey(e => e.RowId);
                entity.ToTable("node_categories");
                entity.HasOne(nc => nc.Node).WithMany(node => node.Categories).HasForeignKey(nc => nc.NodeId).HasConstraintName("FK_node_categories_nodes");
                entity.HasOne(nc => nc.Category).WithMany(category => category.CategorisedNodes).HasForeignKey(nc => nc.CategoryCode).HasConstraintName("FK_node_categories_categories");
                entity.Property(e => e.RowId).HasColumnName("row_id").UseSqlServerIdentityColumn();
                entity.Property(e => e.CategoryCode).HasColumnName("category_code").HasColumnType("varchar(50)");
                entity.Property(e => e.NodeId).HasColumnName("node_id").HasColumnType("varchar(50)");
            });

modelBuilder.Entity<Category>(entity =>
            {
                entity.HasKey(e => e.Code);
                entity.ToTable("categories");
                entity.Property(e => e.Code).HasColumnName("category_code").HasColumnType("varchar(50)");
                entity.Property(e => e.Name).HasColumnName("category_name").HasColumnType("varchar(50)");
            });

modelBuilder.Entity<Node>(entity =>
            {
                entity.HasKey(e => e.NodeId);
                entity.ToTable("nodes");
                entity.Property(e => e.NodeId).HasColumnName("node_id").HasColumnType("varchar(50)");
            });


// When running
// Create a node
Node n = new Node();
// Assign it's properties
n.NodeId = "test";
n.Categories = new List<NodeCategory>(1);
// Create and assign the navigation property, linked via foreign key in database
n.Categories.Add(new NodeCategory("testCategory", "test"));

dbContext.NodesSet.Add(n);

dbContext.SaveChanges(); // Fails here
```

### Exception:
```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: The MERGE statement conflicted with the FOREIGN KEY constraint "FK_node_categories_categories". 
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TrySetMetaData(_SqlMetaDataSet metaData, Boolean moreInfo)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
```

### Expected Behaviour

Insert data for the parent of a foreign key first. I realise this may not always be desired behaviour but setting some sort of flag to allow this would be very helpful. I may be missing something but I can't find anything from my googling, may not be googling the right thing but hopefully someone can help with this.

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.6

**Comment by ajcvickers** [comment]
@JackSteel97 I have not been able to reproduce the behavior you are seeing. The code posted did not compile, so I had to make some changes--see below. Also, it looks like this issue could depend on the database schema being used--could you post that too.

```C#
public class Node
{
    public List<NodeCategory> Categories { get; set; }
    public string NodeId { get; set; }
}

public class Category
{
    public long RowId { get; set; }
    public string Code { get; set; }
    public string Name { get; set; }
    public List<NodeCategory> CategorisedNodes { get; set; }
}

public class NodeCategory
{
    public long RowId { get; set; }
    public string CategoryCode { get; set; }
    public string NodeId { get; set; }
    public Category Category { get; set; }
    public Node Node { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");

    public DbSet<Node> NodesSet { get; set; }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.Entity<NodeCategory>(entity =>
        {
            entity.HasKey(e => e.RowId);
            entity.ToTable("node_categories");
            entity.HasOne(nc => nc.Node).WithMany(node => node.Categories).HasForeignKey(nc => nc.NodeId).HasConstraintName("FK_node_categories_nodes");
            entity.HasOne(nc => nc.Category).WithMany(category => category.CategorisedNodes).HasForeignKey(nc => nc.CategoryCode).HasConstraintName("FK_node_categories_categories");
            entity.Property(e => e.RowId).HasColumnName("row_id").UseSqlServerIdentityColumn();
            entity.Property(e => e.CategoryCode).HasColumnName("category_code").HasColumnType("varchar(50)");
            entity.Property(e => e.NodeId).HasColumnName("node_id").HasColumnType("varchar(50)");
        });

        builder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.Code);
            entity.ToTable("categories");
            entity.Property(e => e.Code).HasColumnName("category_code").HasColumnType("varchar(50)");
            entity.Property(e => e.Name).HasColumnName("category_name").HasColumnType("varchar(50)");
        });

        builder.Entity<Node>(entity =>
        {
            entity.HasKey(e => e.NodeId);
            entity.ToTable("nodes");
            entity.Property(e => e.NodeId).HasColumnName("node_id").HasColumnType("varchar(50)");
        });
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            // When running
            // Create a node
            Node n = new Node();
            // Assign it's properties
            n.NodeId = "test";
            n.Categories = new List<NodeCategory>(1);
            // Create and assign the navigation property, linked via foreign key in database
            n.Categories.Add(new NodeCategory());

            context.NodesSet.Add(n);

            context.SaveChanges(); // Fails here
        }
    }
}
```

**Comment by JackSteel97** [comment]
@ajcvickers See below for database table setup.

```sql
/****** Object:  Table [dbo].[categories]    Script Date: 15/08/2018 09:05:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[categories](
	[row_id] [bigint] IDENTITY(1,1) NOT NULL,
	[category_code] [varchar](50) NOT NULL,
	[category_name] [varchar](255) NOT NULL,
 CONSTRAINT [PK_categories_1] PRIMARY KEY CLUSTERED 
(
	[category_code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [IX_categories] UNIQUE NONCLUSTERED 
(
	[row_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
```

```sql
/****** Object:  Table [dbo].[node_categories]    Script Date: 15/08/2018 09:07:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[node_categories](
	[row_id] [bigint] IDENTITY(1,1) NOT NULL,
	[node_id] [varchar](50) NOT NULL,
	[category_code] [varchar](50) NOT NULL,
 CONSTRAINT [PK_node_categories] PRIMARY KEY CLUSTERED 
(
	[row_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[node_categories]  WITH CHECK ADD  CONSTRAINT [FK_node_categories_categories] FOREIGN KEY([category_code])
REFERENCES [dbo].[categories] ([category_code])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[node_categories] CHECK CONSTRAINT [FK_node_categories_categories]
GO

ALTER TABLE [dbo].[node_categories]  WITH CHECK ADD  CONSTRAINT [FK_node_categories_nodes] FOREIGN KEY([node_id])
REFERENCES [dbo].[nodes] ([node_id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[node_categories] CHECK CONSTRAINT [FK_node_categories_nodes]
GO
```

```sql
/****** Object:  Table [dbo].[nodes]    Script Date: 15/08/2018 09:08:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[nodes](
	[row_id] [bigint] IDENTITY(1,1) NOT NULL,
	[node_id] [varchar](50) NOT NULL,
 CONSTRAINT [PK_nodes] PRIMARY KEY CLUSTERED 
(
	[node_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [IX_nodes] UNIQUE NONCLUSTERED 
(
	[row_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
```

**Comment by JackSteel97** [comment]
My mistake, found some hidden bad data to be the cause of the problem - working now.
