### ISSUE TITLE
I got an exception when i try to update graph using AutoMapper 'The instance of entity type 'Order' cannot be tracked because another instance with the same key value for {'OrderId'} is already being tracked.'

### ISSUE THREAD

**Issue by ahmedtolba1984** [dotnet/efcore#13080]
Dears,
I got an exception when i try to update graph. I use **Automapper** to map Dtos to my entities, then i check if my object already exist in database before i do the update operation. When i call **dbContext.Update**, I got an exception **The instance of entity type 'Order' cannot be tracked because another instance with the same key value for {'OrderId'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.'**
Following exceptions details are from the code given below:
```
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node, Boolean force)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode node, TState state, Func`3 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState entityState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.Update[TEntity](TEntity entity)
   at EFCoreIssue.OrderRepository.<UpdateAsync>d__4.MoveNext() in C:\Users\a.tolbah\source\repos\EFCoreIssue\EFCoreIssue\OrderRepository.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at 
```
**Steps to reproduce**
Running the following code leads to the above exception:
Or you can get the code on this github repository
[https://github.com/ahmedtolba1984/EFCoreIssue](https://github.com/ahmedtolba1984/EFCoreIssue
)
```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using EFCoreIssue;
using EFCoreIssue.Dtos;
using EFCoreIssue.Models;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace EFCoreIssue_Tests
{
    public class OrdersTests
    {
        private readonly OrderRepository _orderRepository;

        public OrdersTests()
        {
            _orderRepository = new OrderRepository(new OrdersDbContext());
            Mapper.Initialize(cfg => cfg.CreateMap<OrderDto, Order>());
        }

        [Fact]
        public async void Should_Update_Customer_Successfully()
        {
            //Arrange
            var order = new Order
            {
                Description = "Test Order",
                OrderLines = new List<OrderLine>
                {
                    new OrderLine {ProductId = 1, Quantity = 1}
                }
            };
            using (var dbContext = new OrdersDbContext())
            {
                dbContext.Orders.Add(order);
                await dbContext.SaveChangesAsync();
            }

            //Act
            var orderDto = new OrderDto
            {
                Description = "Test Order 2",
                OrderLines = new List<OrderLineDto>
                {
                    new OrderLineDto {OrderLineId = order.OrderLines[0].OrderLineId, ProductId = 2, Quantity = 2}
                },
                OrderId = order.OrderId
            };


            await _orderRepository.UpdateAsync(Mapper.Map<Order>(orderDto));

            //Assert
            using (var dbContext = new OrdersDbContext())
            {
                var updatedOrder = await dbContext.Orders.Include(c => c.OrderLines)
                    .Where(c => c.OrderId == order.OrderId).SingleAsync();
                //updatedOrder.ShouldNotBeNull();
                //customerFetch.Id.ShouldNotBeNull();
                //customerFetch.Id.ShouldBe(customerDto.Id);
            }
        }
    }
}
```
and my order repository update method
```C#
        public async Task<Order> UpdateAsync(Order order)
        {
            var dbOrder = await GetOrderAsync(order.OrderId);
            if (dbOrder == null)
                throw new Exception($"Invalid Or Missing Order with Id {order.OrderId}");

            _dbContext.Update(order);
            await _dbContext.SaveChangesAsync();
            return order;
        }
```
**Further technical details**
EF Core version: Microsoft.EntityFrameworkCore v2.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer v2.1.2
Operating system: Windows 10
IDE: Visual Studio 2017 v15.8.1

**Comment by ahmedtolba1984** [comment]
@AndriySvyryd @ajcvickers @divega @bricelam

**Comment by ajcvickers** [comment]
@ahmedtolba1984 The code is creating a new Order instance and then attempting to track it in the same context instance that is already tracking the original Order instance. You should probably consider using a different context instance for each unit-of-work, and it also might be helpful to review the docs on [change tracking](https://docs.microsoft.com/en-us/ef/core/saving/basic) and [working with disconnected entities](https://docs.microsoft.com/en-us/ef/core/saving/disconnected-entities).
