### ISSUE TITLE
In memory DB seeding

### ISSUE THREAD

**Issue by domagojmedo** [dotnet/efcore#13126]
Calling EnsureCreated() with InMemoryDb will seed the database, but when you try to insert another row it will just reuse the Id and fail.

Also happens if you call EnsureCreated() twice

```
Exception message: System.ArgumentException: An item with the same key has already been added. Key: 1
Stack trace:
at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryTable`1.Create(IUpdateEntry entry)
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryStore.ExecuteTransaction(IReadOnlyList`1 entries, IDiagnosticsLogger`1 updateLogger)
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryStore.EnsureCreated(StateManagerDependencies stateManagerDependencies, IDiagnosticsLogger`1 updateLogger)
```

### Further technical details
EF Core version: 2.1.2
Database Provider: Microsoft.EntityFrameworkCore.InMemory
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.1

**Comment by domagojmedo** [comment]
I guess it's a duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/12950

**Comment by ajcvickers** [comment]
@domagojmedo It looks to me like you are hitting #6872, and then #12950 when calling EnsureCreated twice.
