### ISSUE TITLE
SqliteException when GroupJoin with Take

### ISSUE THREAD

**Issue by voronov-maxim** [dotnet/efcore#13187]
```
Exception message:
 Microsoft.Data.Sqlite.SqliteException: 'SQLite Error 1: 'no such column: o1.OrderId'.'
Stack trace:
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues) in D:\programming\EntityFrameworkCore\src\EFCore.Relational\Storage\Internal\RelationalCommand.cs:line 186
```

### Steps to reproduce
```c#
class Order
{
  public int Id { get; set; }
  public ICollection<OrderItem> Items { get; set; }
}
class OrderItem
{
  public int Id { get; set; }
  public Order Order { get;  set; }
  public int OrderId { get; set; }
}
dbContext.Orders.GroupJoin(dbContext.Orders.SelectMany(o => dbContext.OrderItems.Where(i => o.Id == i.OrderId).OrderBy(i => i.Id).Take(1)),
o => o.Id, i => i.OrderId, (o, i) => new { Order = o, Items = i }).ToArray();
```
All worked well with SqlServer provider.
If remove Take(1), the bug is not reproduced.

### Further technical details
EF Core version: 2.1.2
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.2

**Comment by smitpatel** [comment]
Won't fix as per #17068
