### ISSUE TITLE
Concurrency Error 

### ISSUE THREAD

**Issue by gitn00b1337** [dotnet/efcore#13230]
I am using EF Core 2.1.2 in my netcoreapp2.1 app. The below exception is being thrown on my local DB, and is the only request being sent at the time - therefore it cannot actually be a concurrency issue.

I have a system versioned table in sql server. It is very large and has many nullable foreign keys to other tables. One of which is UserId -> user table. The user is currently set to ID 7. I am calling the below EF code to remove the user link. 

```C#
            using (MyDataContext dataContext = _factory.Create())
            {
                var result = await dataContext.TblXXX
                    .Where(s => s.PrimaryKey== model.PrimaryKey)
                    .FirstOrDefaultAsync();

                if (result == null)
                    return false;

                if (result.UserId != userId)
                    throw new AuthorisationException("Invalid user requested unassign policy");

                slipDetails.UserId = null;
                dataContext.SaveChanges();
            }
```
In SQL I can set the user id to null and no error occurs, but with EF above i get:

{Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithPropagation(Int32 commandIndex, RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()

Please could you point me in the right direction?

**Comment by ajcvickers** [comment]
@gitn00b1337 There is nothing that immediately looks wrong in the code you posted. Could you please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
