### ISSUE TITLE
Allow DbContext.Query<T> called with an entity type

### ISSUE THREAD

**Issue by MikeJansen** [dotnet/efcore#13252]
Simply calling `DbContext.Query<T>()` with various entities (like `IdentityUser`) is throwing an `InvalidCastException`.

```
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1[Microsoft.AspNetCore.Identity.IdentityUser]' to type 'Microsoft.EntityFrameworkCore.DbQuery`1[Microsoft.AspNetCore.Identity.IdentityUser]'.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.DbContext.Query[TQuery]()
   at NetCore21WebTest.Controllers.HomeController.Index() in C:\devel\Sandbox\NetCore21WebTest\NetCore21WebTest\Controllers\HomeController.cs:line 24
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
```
### Steps to reproduce

Given:

```
public class MyClass
{
  public MyClass(ApplicationDbContext db)
  {
     var query = db.Query<IdentityUser>();
  }
}
```

Using ASP.NET Core 2.1, I am getting this exception on the `db.Query<IdentityUser>()` call:

```
System.InvalidCastException: 'Unable to cast object of type 'Microsoft.EntityFrameworkCore.Internal.InternalDbSet\`1[Microsoft.AspNetCore.Identity.IdentityUser]' to type 'Microsoft.EntityFrameworkCore.DbQuery\`1[Microsoft.AspNetCore.Identity.IdentityUser]'.'
```

I ran into this with my own entities and reproduced it with minimal code using the canned ApplicationDbContext/IdentityUser.

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Pro
IDE: Visual Studio 2017 15.8.2

**Comment by smitpatel** [comment]
You cannot call `Query<>` method for EntityTypes. You must use `Set<>` method.

**Comment by MikeJansen** [comment]
@smitpatel Thank you.  That fixed the problem.  Perhaps `DbContext.Query<TQuery>() could have a more constrained `where` clause for `TQuery` ?

Closing the issue.

**Comment by smitpatel** [comment]
For better exception msg.

**Comment by ajcvickers** [comment]
Better message for 2.2, backlog afterwards for making Query work for DbSets.

**Comment by ajcvickers** [comment]
No longer needed since query types and entity types have been collapsed.
