### ISSUE TITLE
Code-first TPH with multi-levelled inheritance throws exception

### ISSUE THREAD

**Issue by chrispickford** [dotnet/efcore#13277]
I'm trying to configure TPH given the following structure (2 tiers of inheritance on my concrete classes):
```
public abstract class EntityBase {
  public int Id { get; set; }
}
public abstract class LogicalParent : EntityBase {
  public string Name { get; set; }
}
public class EntityA : LogicalParent {
  public string PropA { get; set; }
}
public class EntityB : LogicalParent {
  public string PropB { get; set; }
}
```

My context OnModelCreating looks like this:
```
modelBuilder.Entity<EntityBase>().HasKey(x => x.Id);
modelBuilder.Entity<LogicalParent>().HasDiscriminator<string>("Type")
  .HasValue<EntityA>("A")
  .HasValue<EntityB>("B");
modelBuilder.Entity<EntityA>().HasBaseType<LogicalParent>();
modelBuilder.Entity<EntityB>().HasBaseType<LogicalParent>();
```

When trying to generate a migration the following exception is thrown:
```
System.InvalidOperationException: A discriminator property cannot be set for the entity type 'LogicalParent' because it is not the root of an inheritance hierarchy.
   at Microsoft.EntityFrameworkCore.Metadata.RelationalEntityTypeAnnotations.SetDiscriminatorProperty(IProperty value, Type oldDiscriminatorType)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalEntityTypeBuilderAnnotations.DiscriminatorBuilder(Func`2 createProperty, Type propertyType)
   at Microsoft.EntityFrameworkCore.RelationalEntityTypeBuilderExtensions.HasDiscriminator[TDiscriminator](EntityTypeBuilder entityTypeBuilder, String name)
   at EFCoreTphException.TestContext.OnModelCreating(ModelBuilder modelBuilder) in C:\SRC\GitHub\chrispickford\EFCoreTphException\TestContext.cs:line 26
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Steps to reproduce
VS2017 project here: https://github.com/chrispickford/EFCoreTphException

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 10 Pro (1803)
IDE: Visual Studio 2017 15.7.5

**Comment by ajcvickers** [comment]
@chrispickford It wasn't 100% clear when reading this what "2 tiers of inheritance" means. Assuming that it just means a normal inheritance hierarchy with multiple derived types from a single base, then there are a few ways to configure it. 

First, as the exception message indicates, the `HasDiscriminator` call can be made on the mapped type at the root of the hierarchy:
```C#
modelBuilder.Entity<EntityBase>()
    .HasDiscriminator<string>("Type")
    .HasValue<EntityA>("A")
    .HasValue<EntityB>("B");

modelBuilder.Entity<LogicalParent>();
```
```sql
CREATE TABLE [EntityBase] (
    [Id] int NOT NULL IDENTITY,
    [Type] nvarchar(max) NOT NULL,
    [Name] nvarchar(max) NULL,
    [PropA] nvarchar(max) NULL,
    [PropB] nvarchar(max) NULL,
    CONSTRAINT [PK_EntityBase] PRIMARY KEY ([Id])
);
```
Second, if the intention is to not map the base type, then don't call `Entity` on it, since this explicitly configures it as a mapped type:
```C#
modelBuilder.Entity<LogicalParent>().HasDiscriminator<string>("Type")
    .HasValue<EntityA>("A")
    .HasValue<EntityB>("B");
```
```sql
CREATE TABLE [LogicalParent] (
    [Id] int NOT NULL IDENTITY,
    [Name] nvarchar(max) NULL,
    [Type] nvarchar(max) NOT NULL,
    [PropA] nvarchar(max) NULL,
    [PropB] nvarchar(max) NULL,
    CONSTRAINT [PK_LogicalParent] PRIMARY KEY ([Id])
);
```
Note that in both the cases above I removed the HasKey call since it is not needed. If you want to add it back it's just a matter of defining in root _mapped_ type:
```C#
modelBuilder.Entity<LogicalParent>(b =>
{
    b.HasKey(e => e.Id);
    b.HasDiscriminator<string>("Type")
        .HasValue<EntityA>("A")
        .HasValue<EntityB>("B");
});
```
Third, if the default type/property for the discriminator can be used, then `HasDiscriminator` can be used anywhere in the hierarchy:
```C#
modelBuilder.Entity<EntityBase>();
modelBuilder.Entity<LogicalParent>().HasDiscriminator()
    .HasValue<EntityA>("A")
    .HasValue<EntityB>("B");
```
```sql
CREATE TABLE [EntityBase] (
    [Id] int NOT NULL IDENTITY,
    [Discriminator] nvarchar(max) NOT NULL,
    [Name] nvarchar(max) NULL,
    [PropA] nvarchar(max) NULL,
    [PropB] nvarchar(max) NULL,
    CONSTRAINT [PK_EntityBase] PRIMARY KEY ([Id])
);
```

Note that none of these cases require any calls to `HasBaseType` so I omitted these calls. You can add them if you want, but they won't change the configuration.

If you meant something different, or feel like there is still a need to be able to call `HasDiscriminator` on a derived type to specify the type and name of the discriminator property, then it would be great if you could provide details.

**Comment by chrispickford** [comment]
@ajcvickers Thanks for your response. The intention is to not map the base type `EntityBase` however in my real world scenario I have many other entities that inherit from this and benefit from the common mappings set up at this level, e.g. in addition to above I have:

    public abstract class EntityBase
    {
      public int Id { get; set; }
      public byte[] RowVersion { get; set; }
      public Guid UuId { get; set; }
    }
    
    public class EntityC : EntityBase {}
    public class EntityD : EntityBase {}
    
    modelBuilder.Entity<EntityBase>().HasKey(x => x.Id);
    modelBuilder.Entity<EntityBase>().Property(x => x.RowVersion).IsRowVersion();
    modelBuilder.Entity<EntityBase>().Property(x => x.UuId).HasDefaultValueSql("NEWID()");
    
    modelBuilder.Entity<EntityC>();
    modelBuilder.Entity<EntityD>();

Is there any way to configure the properties on `EntityBase` without calling `.Entity<>` on it?

Also, changing `.HasDiscriminator<string>("Type")` to just `.HasDiscriminator()` as you suggested does allow the migration to be created, however this lumps all the entities into a single `EntityBase` table.

**Comment by ajcvickers** [comment]
@chrispickford Issue #6787 is tracking bulk configuration for unmapped base types, and shows a way to do it before first class support is implemented.
