### ISSUE TITLE
ArgumentException on Left Outer Join LINQ with Contains

### ISSUE THREAD

**Issue by Forester-** [dotnet/efcore#13303]
The next LINQ causes ArgumentException:

```C#
from parent in db.ParentEntities.Include(parentRef => parentRef.ChildEntities)
let qryChildIds = from child in parent.ChildEntities select child.Id
let qryExtensions = from extension in db.ExtensionEntities
     where qryChildIds.Contains(extension.ChildEntityId)
     select extension
from extensions in qryExtensions.DefaultIfEmpty()
select new { Parent = parent, Extensions = extensions }
```

Exception:
```
System.ArgumentException: Property 'Int32 ChildEntityId' is not defined for type 'EFCoreLojErr.ChildEntity'
Parameter name: property
   at System.Linq.Expressions.Expression.Property(Expression expression, PropertyInfo property)
   at System.Linq.Expressions.Expression.MakeMemberAccess(Expression expression, MemberInfo member)
   at System.Linq.Expressions.MemberExpression.Update(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitMember(MemberExpression node)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Clauses.ExpressionVisitors.ReferenceReplacingExpressionVisitor.ReplaceClauseReferences(Expression expression, QuerySourceMapping querySourceMapping, Boolean throwOnUnmappedReferences)
   at Remotion.Linq.Clauses.ExpressionVisitors.ReferenceReplacingExpressionVisitor.<VisitSubQuery>b__5_0(Expression ex)
   at Remotion.Linq.Clauses.ResultOperators.ContainsResultOperator.TransformExpressions(Func`2 transformation)
   at Remotion.Linq.QueryModel.TransformExpressions(Func`2 transformation)
   at Remotion.Linq.Clauses.ExpressionVisitors.ReferenceReplacingExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
   at Remotion.Linq.Clauses.Expressions.SubQueryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Clauses.ExpressionVisitors.ReferenceReplacingExpressionVisitor.ReplaceClauseReferences(Expression expression, QuerySourceMapping querySourceMapping, Boolean throwOnUnmappedReferences)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.<>c__DisplayClass35_0.<RewriteNavigationIntoGroupJoin>b__0(Expression e)
   at Remotion.Linq.Clauses.WhereClause.TransformExpressions(Func`2 transformation)
   at Remotion.Linq.QueryModel.TransformExpressions(Func`2 transformation)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.RewriteNavigationIntoGroupJoin(JoinClause joinClause, INavigation navigation, IEntityType targetEntityType, QuerySourceReferenceExpression querySourceReferenceExpression, MainFromClause groupJoinSubqueryMainFromClause, ICollection`1 groupJoinSubqueryBodyClauses, ICollection`1 groupJoinSubqueryResultOperators, NavigationJoin& navigationJoin)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.RewriteSelectManyInsideSubqueryIntoJoins(SubQueryExpression fromSubqueryExpression, QuerySourceReferenceExpression outerQuerySourceReferenceExpression, ICollection`1 navigations, AdditionalFromClause additionalFromClauseBeingProcessed)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.RewriteNavigationProperties(IReadOnlyList`1 properties, IQuerySource querySource, Expression expression, Expression declaringExpression, String propertyName, Type propertyType, Func`2 propertyCreator, Func`2 conditionalAccessPropertyCreator)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.<>c__DisplayClass19_0.<VisitMember>b__0(IReadOnlyList`1 ps, IQuerySource qs)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindPropertyExpressionCore[TResult](Expression propertyExpression, IQuerySource querySource, Func`3 propertyBinder)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindNavigationPathPropertyExpression[TResult](Expression propertyExpression, Func`3 propertyBinder)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.VisitMember(MemberExpression node)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Clauses.FromClauseBase.TransformExpressions(Func`2 transformation)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ExpressionTransformingQueryModelVisitor`1.VisitMainFromClause(MainFromClause fromClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.NavigationRewritingQueryModelVisitor.VisitMainFromClause(MainFromClause fromClause, QueryModel queryModel)
   at Remotion.Linq.Clauses.MainFromClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.Rewrite(QueryModel queryModel, QueryModel parentQueryModel)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
   at Remotion.Linq.Clauses.Expressions.SubQueryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Clauses.WhereClause.TransformExpressions(Func`2 transformation)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ExpressionTransformingQueryModelVisitor`1.VisitWhereClause(WhereClause whereClause, QueryModel queryModel, Int32 index)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.NavigationRewritingQueryModelVisitor.VisitWhereClause(WhereClause whereClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.Clauses.WhereClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.Rewrite(QueryModel queryModel, QueryModel parentQueryModel)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
   at Remotion.Linq.Clauses.Expressions.SubQueryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Clauses.FromClauseBase.TransformExpressions(Func`2 transformation)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.NavigationRewritingQueryModelVisitor.VisitAdditionalFromClause(AdditionalFromClause fromClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.Clauses.AdditionalFromClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.Rewrite(QueryModel queryModel, QueryModel parentQueryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, Boolean asyncQuery)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, Boolean asyncQuery)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at EFCoreLojErr.Program.Main(String[] args) in C:\Projects\Mattina\Temp\1\EFCoreLojErr\EFCoreLojErr\EFCoreLojErr\Program.cs:line 27}	System.Exception {System.ArgumentException
```

Sampe source code is available at https://github.com/Forester-/EFCoreLojErr

### Further technical details
EF Core version: 2.1.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10, MS SqlServer 11.0.2100 at Windows Server 2008 R2
IDE: Visual Studio 2017 15.4.5

**Comment by smitpatel** [comment]
A different error now
```
--- Started ---
!!! ERROR !!!
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
--- Finished ---
```
Seems like incorrect inference about nullability.
Generated SQL
```SQL
SELECT [p].[Id], [p].[Value], [t].[ChildEntityId], [t].[Value], [t].[ChildEntityId], [c0].[Id], [c0].[ParentEntityId], [c0].[Value]
FROM [ParentEntity] AS [p]
OUTER APPLY (
    SELECT [e].[ChildEntityId], [e].[Value]
    FROM [ExtensionEntity] AS [e]
    WHERE [e].[ChildEntityId] IN (
        SELECT [c].[Id]
        FROM [ChildEntity] AS [c]
        WHERE [p].[Id] = [c].[ParentEntityId]
    )

) AS [t]
LEFT JOIN [ChildEntity] AS [c0] ON [p].[Id] = [c0].[ParentEntityId]
ORDER BY [p].[Id], [t].[ChildEntityId], [c0].[Id]
```

**Comment by smitpatel** [comment]
Generated SQL with 5.0 preview8
```SQL
SELECT [p].[Id], [p].[Value], [t].[ChildEntityId], [t].[Value], [c0].[Id], [c0].[ParentEntityId], [c0].[Value]
FROM [ParentEntity] AS [p]
OUTER APPLY (
    SELECT [e].[ChildEntityId], [e].[Value]
    FROM [ExtensionEntity] AS [e]
    WHERE EXISTS (
        SELECT 1
        FROM [ChildEntity] AS [c]
        WHERE ([p].[Id] = [c].[ParentEntityId]) AND ([c].[Id] = [e].[ChildEntityId]))
) AS [t]
LEFT JOIN [ChildEntity] AS [c0] ON [p].[Id] = [c0].[ParentEntityId]
ORDER BY [p].[Id], [t].[ChildEntityId], [c0].[Id]
```
