### ISSUE TITLE
InvalidCastException when trying to use FreeText with a local variable as the language argument

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/efcore#13315]
When I try to use a local variable for the `language` argument of the `FreeText` method, I get the following exception:

```
Exception message: System.InvalidCastException: Unable to cast object of type 'System.Linq.Expressions.PrimitiveParameterExpression`1[System.Int32]' to type 'System.Linq.Expressions.ConstantExpression'.
Stack trace:
   at Microsoft.EntityFrameworkCore.SqlServer.Query.ExpressionTranslators.Internal.SqlServerFreeTextMethodCallTranslator.Translate(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionTranslators.RelationalCompositeMethodCallTranslator.<>c__DisplayClass5_0.<Translate>b__0(IMethodCallTranslator translator)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.EntityFrameworkCore.Query.ExpressionTranslators.RelationalCompositeMethodCallTranslator.Translate(MethodCallExpression methodCallExpression, IModel model)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression expression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.ExpressionVisitors.Internal.SqlServerSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression expression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.ExpressionVisitors.Internal.SqlServerSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression expression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.ExpressionVisitors.Internal.SqlServerSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression expression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.ExpressionVisitors.Internal.SqlServerSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitWhereClause(WhereClause whereClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.Clauses.WhereClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileAsyncQuery[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass22_0`1.<CompileAsyncQuery>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddAsyncQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQuery[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
   at System.Linq.AsyncEnumerable.Aggregate_[TSource,TAccumulate,TResult](IAsyncEnumerable`1 source, TAccumulate seed, Func`3 accumulator, Func`2 resultSelector, CancellationToken cancellationToken)
   at MyProject.SomeClass.SomeMethod(string searchTerm) in C:\Projects\MyProject\SomeClass.cs:line 71
```

### Steps to reproduce
```c#
int lcid = CultureInfo.CurrentCulture.LCID;
var results = await _dbContext.Items
    .Where(i => EF.Functions.FreeText(i.Text, searchTerm, lcid))
    .ToListAsync();
```

Using a literal instead of the `lcid` variable works fine.

The problem seems to be on this line:

https://github.com/aspnet/EntityFrameworkCore/blob/7b11733e091e937ea6f616ecf56ebc6fcb11955f/src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerFreeTextMethodCallTranslator.cs#L66

The translator assumes the expression to be a `ConstantExpression`, which means it can only work with a hard-coded literal value.

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer (2.1.1)
Operating system: Windows 10 v1803
IDE: VS2017 v15.8.1

**Comment by thomaslevesque** [comment]
In the original expression, the argument is a `FieldExpression` (the `lcid` captured local variable) off a `ConstantExpression` (the object holding the captured locals). But by the time it reaches the `SqlServerFreeTextMethodCallTranslator` class, it has been changed to a `PrimitiveParameterExpression`, so I'm not sure if it's possible to retrieve the value...

**Comment by thomaslevesque** [comment]
Workaround: fixup the expression to replace references to a local variable with the value of that variable.

```csharp
static class Extensions
{
    public static IQueryable<TSource> FixupLocalInExpression<TSource, TValue>(this IQueryable<TSource> source, Expression<Func<TValue>> localExpression, TValue value)
    {
        if (localExpression.Body is MemberExpression memberExpr && memberExpr.Expression is ConstantExpression constant)
        {
            var visitor = new MemberReplacementVisitor<TValue>(constant.Value, memberExpr.Member, value);
            var newExpression = visitor.Visit(source.Expression);
            return source.Provider.CreateQuery<TSource>(newExpression);
        }

        throw new ArgumentException("Invalid local expression");
    }

    private class MemberReplacementVisitor<TValue> : ExpressionVisitor
    {
        private readonly object _instance;
        private readonly MemberInfo _member;
        private readonly TValue _replacementValue;

        public MemberReplacementVisitor(object instance, MemberInfo member, TValue replacementValue)
        {
            _instance = instance;
            _member = member;
            _replacementValue = replacementValue;
        }

        protected override Expression VisitMember(MemberExpression node)
        {
            if (node.Expression is ConstantExpression constant && Equals(constant.Value, _instance) && Equals(node.Member, _member))
                return Expression.Constant(_replacementValue, typeof(TValue));

            return base.VisitMember(node);
        }
    }
}
```

Usage:

```csharp
int lcid = CultureInfo.CurrentCulture.LCID;
var results = await _dbContext.Items
    .Where(i => EF.Functions.FreeText(m.Text, searchTerm, lcid))
    .ReplaceLocalWithItsValue(() => lcid, lcid)
    .ToListAsync();
```

**Comment by ajcvickers** [comment]
Triage: moving this to the backlog to look into a general way of allowing values like this to not be parameterized.

@smitpatel to link related issue.

**Comment by smitpatel** [comment]
We need to decorate FreeText method's argument as NotParameterizedAttribute to avoid having a parameter there.

**Comment by thomaslevesque** [comment]
@smitpatel I just sent a PR for this (#20308)

**Comment by shahzadq77** [comment]
@smitpatel @ajcvickers  August 2022 - I'm getting this error, using this code:

![image](https://user-images.githubusercontent.com/6401113/183311512-306b0f26-3ab5-4092-8376-2e20fc01ea07.png)

**Comment by roji** [comment]
@shahzadq77 this issue was about the use of the FreeText function with a parameter, but the code above doesn't seem to use FreeText. Please open a new issue with a runnable code sample and the full exception details.
