### ISSUE TITLE
Wrong filepath to LocalDB file with on Migrations (Update-Database) when user folder contains a space

### ISSUE THREAD

**Issue by theberserker** [dotnet/efcore#13330]
For a LocalDB (installed with Sql Server 2017) when Windows username contains a space character, the EF Core tool crashes on  `Update-Database`, due to wrongly concatenating user's folder and a database filename. The combined path becomes _'C:\Users\Name SurnameDatabaseName.mdf'_ instead of _'C:\Users\Name Surname\DatabaseName.mdf'_

Connection string used: `"Server=(localdb)\\mssqllocaldb;Database=DatabaseName;Trusted_Connection=True;MultipleActiveResultSets=true"`

Unfortunately I wasn't able to modify the location of the LocalDB files, following this suggestion: https://dba.stackexchange.com/a/61387 As I do get the values in the registry, they don't seem to be obeyed by the LocalDB. Any workaround suggestion here?

Error output (`Update-Database` and `dotnet ef database update`)
```
Failed executing DbCommand (13ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
CREATE DATABASE [DatabaseName];
System.Data.SqlClient.SqlException (0x80131904): CREATE FILE encountered operating system error 5(Access is denied.) while attempting to open or create the physical file 'C:\Users\Name SurnameDatabaseName.mdf'.
CREATE DATABASE failed. Some file names listed could not be created. Check related errors.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:717acb5c-b3e8-4ef7-b40f-6deb3e53fbbf
Error Number:5123,State:1,Class:16
CREATE FILE encountered operating system error 5(Access is denied.) while attempting to open or create the physical file 'C:\Users\Name SurnameDatabaseName.mdf'.
CREATE DATABASE failed. Some file names listed could not be created. Check related errors.
```

### Further technical details
EF Core version: 2.1.1 and 2.1.3 
EF Core Tools version: 2.1.1 and 2.1.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: 
IDE: Visual Studio 2017 15.8.4

I realize that having a space in username is very bad choice, but it is unfortunately something that Windows 10 creates out of an entered name field at the new laptop setup. Renaming it is another can of worms, but that's a another story.

**Comment by theberserker** [comment]
Thanks @ajcvickers. Yes, I can confirm that my assumption was wrong and this is indeed the issue. After installing _Cumulative Update Package 10 for SQL Server 2017 - KB4342123_, it works fine.
