### ISSUE TITLE
Parameter count mismatch while seeding generic data EF Core 2.1.3

### ISSUE THREAD

**Issue by redplane** [dotnet/efcore#13334]
Hi,

I'm making an application using `.Net core` and `EF Core` with `In-memory provider` to mocking my data.
My data is saved in json files.
For now, I just want to loop through the list, read the json file and add to `DbContext` automatically.
Here is what I done:

- Created a file `AddMockingRecords.cs` to read json files, and save to a `Dictionary<Type, string>` where **key** is entity type , **value** is the json content.

```C#
public static class AppMockingDbExtension
{
	public static void AddMockingRecords(this IServiceCollection serviceCollection, IHostingEnvironment env)
	{
		#region Read data from files

		var webRootPath = env.WebRootPath;
		var dbSeedRootPath = Path.Combine(webRootPath, "DbSeed");
		var entities = new []
			{typeof(User), typeof(CategoryGroup), typeof(Category), typeof(Topic), typeof(Reply)};

		// List of tasks that load content.
		var loadContentTasks = new Dictionary<Type, Task<string>>();

		foreach (var entity in entities)
		{
			var filePath = Path.Combine(dbSeedRootPath, $"{entity.Name}.json");
			if (!File.Exists(filePath))
				continue;

			var loadContentTask = File.ReadAllTextAsync(filePath);
			loadContentTasks.TryAdd(entity, loadContentTask);
		}

		Task.WhenAll(loadContentTasks.Values).Wait();

		#endregion

		#region Serialize object

		var columnRecords = new Dictionary<Type, string>();
		foreach (var key in loadContentTasks.Keys)
		{
			var originalContent = loadContentTasks[key].Result;
			columnRecords.Add(key, originalContent);
		}
		var dbSeedOption = new DbSeedOption();
		dbSeedOption.Columns = columnRecords;

		#endregion

		serviceCollection.AddSingleton(dbSeedOption);
	}
}
```

- `DbSeedOption.cs` to store the above Dictionary object:

```C#
public class DbSeedOption
{
	public IDictionary<Type, string> Columns { get; set; }
}
```

- `InMemoryRelationalDbContext.cs` to add mocking data to `ModelBuilder` instance base on the list obtained from json files.

```C#
public class InMemoryRelationalDbContext : RelationalDbContext
{
	#region Properties

	private readonly DbSeedOption _dbSeedOption;

	#endregion

	#region Constructor

	/// <summary>
	/// Initialize in-memory relational database context with injectors.
	/// </summary>
	/// <param name="dbContextOptions"></param>
	/// <param name="dbSeedOptions"></param>
	public InMemoryRelationalDbContext(DbContextOptions dbContextOptions, DbSeedOption dbSeedOptions) : base(dbContextOptions)
	{
		_dbSeedOption = dbSeedOptions;
	}

	#endregion

	#region Methods

	/// <summary>
	/// <inheritdoc/>
	/// </summary>
	/// <param name="modelBuilder"></param>
	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		base.OnModelCreating(modelBuilder);
		foreach (var type in _dbSeedOption.Columns.Keys)
		{
			var originalContent = _dbSeedOption.Columns[type];
			var i = Activator.CreateInstance(typeof(List<>).MakeGenericType(type)) as IList;
			var originalEntities = JsonConvert.DeserializeAnonymousType(originalContent, i);
			modelBuilder.Entity(type).HasData(originalEntities);
			
		}
	}
	
	#endregion
}
```

Everything seems to be fine with `HasData`:

![seem to be fine](https://user-images.githubusercontent.com/7974095/45598129-606c9180-ba09-11e8-89f1-fabb9fb3d65b.png)

But when I tried accessing the DbSet of that data type, app threw me an exception: **Parameter count mismatch.**

![exception](https://user-images.githubusercontent.com/7974095/45598153-be997480-ba09-11e8-95a5-b06614bc2705.png)

```
Exception message: **Parameter count mismatch.**
Stack trace:
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.GetData(Boolean providerValues)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateData(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_1(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at AppDb.Repositories.Repository`1..ctor(DbContext dbContext) in D:\Programming\iConfess (fix-missing-data)\A - SOURCE CODE\A - SERVICE\AppDb\Repositories\Repository.cs:line 27
   at AppDb.Services.UnitOfWork.get_Accounts() in D:\Programming\iConfess (fix-missing-data)\A - SOURCE CODE\A - SERVICE\AppDb\Services\UnitOfWork.cs:line 118
   at Main.Controllers.UserController.Login(LoginViewModel parameters) in D:\Programming\iConfess (fix-missing-data)\A - SOURCE CODE\A - SERVICE\Main\Controllers\UserController.cs:line 144
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
```

### Further technical details
EF Core version: (found in project.csproj or packages.config) : **2.1.3**
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer): **2.1.3**
Operating system: **Windows 10**
IDE: (e.g. Visual Studio 2017 15.4) **Visual Studio 2017 15.4**

**Comment by jdmallen** [comment]
I too am getting this same error trying to seed data, though I'm using EF Core 2.1.2.

```csharp
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
  modelBuilder.Model.AddEntityType(typeof(Feedback));
  modelBuilder.Entity<Feedback>(
    builder =>
    {
      builder.HasKey(f => f.Id);
      var env =
        Environment.GetEnvironmentVariable(
          "ASPNETCORE_ENVIRONMENT");
      if ("Development".Equals(
        env,
        StringComparison.InvariantCultureIgnoreCase))
      {
        builder.HasData(Feedback.SeedSampleFeedback());
      }

      builder.Ignore(f => f.ShortId);
    });
}
```
`Feedback` is an entity type and `SeedSampleFeedback` uses [GenFu](https://github.com/MisterJames/GenFu) to return a populated list of Feedback objects (which works fine):

```csharp
public static IEnumerable<Feedback> SeedSampleFeedback()
{
  A.Configure<Feedback>()
    .Fill(x => x.Comment)
    .AsLoremIpsumSentences();
  return A.ListOf<Feedback>(40);
}
```

This is all I get as an exception:
```
Exception thrown: 'System.Reflection.TargetParameterCountException' in System.Private.CoreLib.dll
An exception of type 'System.Reflection.TargetParameterCountException' occurred in System.Private.CoreLib.dll but was not handled in user code
Parameter count mismatch.
```

No idea how to address this.

**Comment by jdmallen** [comment]
Disregard, I added `ToArray()` to my call to `SeedSampleFeedback()` and that seems to have fixed it.

```csharp
builder.HasData(Feedback.SeedSampleFeedback().ToArray());
```

Makes sense, given that the parameter options are `params object[] data` or `params T[] data`, both arrays, and I was trying to feed it an IEnumerable. 

@redplane Try converting your `originalEntities` to an array before passing it to `HasData()`.

**Comment by redplane** [comment]
> Disregard, I added `ToArray()` to my call to `SeedSampleFeedback()` and that seems to have fixed it.
> 
> ```cs
> builder.HasData(Feedback.SeedSampleFeedback().ToArray());
> ```
> 
> Makes sense, given that the parameter options are `params object[] data` or `params T[] data`, both arrays, and I was trying to feed it an IEnumerable.
> 
> @redplane Try converting your `originalEntities` to an array before passing it to `HasData()`.

But converting a generic list wth generic type is not very easy.

**Comment by kalebpol** [comment]
Had the same issue, in the end, in order to dynamically add initial seed data i did this:
'''
dynamic json = JsonConvert.DeserializeObject(seedData);
var entityListType = typeof(IEnumerable<>).MakeGenericType(entityType);
var entityList = json[entityType.Name].ToObject(entityListType);
modelBuilder.Entity(entityType).HasData(entityList.ToArray()); // Warning! must convert to array otherwise you get "parameter count missmatch".
'''
