### ISSUE TITLE
smalldatetime type error

### ISSUE THREAD

**Issue by shupna** [dotnet/efcore#13345]
I have a query type that mapped to a view. The view selects a smalldatetime field from a table.
I got an exception when I make a query from linq with a condition, like 
DbContext.Vw_UnitStatus.Where(r=>r.TheDate < Datetime.Now)

EF issues sql command like:
SELECT [u].[ProjectId] AS [I1]
FROM [Vw_UnitStatus] AS [u]
WHERE ([u].[TheDate] >= '2018-09-13T00:00:00.0000000') AND ([u].[TheDate] < '2018-09-14T00:00:00.0000000')

It seems EF uses datetime2(7) instead of smalldatetime
```
Microsoft.EntityFrameworkCore.Query: Error: An exception occurred in the database while iterating the results of a query for context type 'Scanner.Models.RfIdScanContext'.
System.Data.SqlClient.SqlException (0x80131904): Conversion failed when converting date and/or time from character string.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.Read()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDataReader.Read()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
ClientConnectionId:b10d0a7b-158e-4536-8490-bc7938f5ce1f
Error Number:241,State:1,Class:16
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF Core version: (2.2.0-preview2-35157)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer-2.2.0-preview2-35157)
Operating system: Windows 10
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by smitpatel** [comment]
I am not able to reproduce this on 2.2.0-preview2 packages from NuGet. Please provide a full repro code (including csproj file) which demonstrate above issue.

**Comment by shupna** [comment]
Hi Smit,
Thank you for your quick reply. Here is the full repro code that reproduces the error.

1, Create view "Vw_Orders" on Northwind DB with following codes
SELECT  OrderID, CustomerID, OrderDate, Freight, ShipCountry, ShipRegion, ShipVia
FROM dbo.Orders

2, Open the solution
3, Set "Sample" as default project
4, Run Debug
5, Select a order date from the calender on data grid filter row
6, Get the exception.
[DevExtreme.AspNet.Data-master.zip](https://github.com/aspnet/EntityFrameworkCore/files/2393501/DevExtreme.AspNet.Data-master.zip)
![orders](https://user-images.githubusercontent.com/43355777/45700125-c22c1900-bb39-11e8-95f1-dea516a3355a.png)
![capture](https://user-images.githubusercontent.com/43355777/45700138-c821fa00-bb39-11e8-8471-7713e9ec92fc.PNG)

**Comment by smitpatel** [comment]
The issue is in your configuration of DbQuery of type `Vw_Orders`. In northwind database, Orders.OrderDate is of type `datetime`. Your view is using OrderDate column but not setting any column type on it so EF Core by convention maps it to `datetime2` type. Hence you get a SQL literal which fails during conversion. If you configure the column type of `Vw_Orders.OrderDate` to be of `datetime` everything works as expected. There is nothing related to `smalldatetime` in this issue. It would work with 2.1.x packages too.

P.S. your sample project references 2.2.0-preview1 packages rather than 2.2.0-preview2 packages as indicated in initial post.

**Comment by shupna** [comment]
I couldn't find the way to define the column data type for DbQuery after extensive google search. Could you please send me the sample codes? or send the working version of the repos codes back to me. Thank you so much!!

**Comment by smitpatel** [comment]
Ref: https://docs.microsoft.com/en-us/ef/core/modeling/relational/data-types
You can use `ColumnAttribute` or fluent API as described in the docs. The only difference in fluent API code is instead of calling `Entity<>` you need to call `Query<>` since you are configuring a query type rather than entity type.

**Comment by shupna** [comment]
It works!!! Thank you.
