### ISSUE TITLE
Linq function Aggregate within a VB Source compiles, but throws NotImplementedException at Runtime

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#13351]
From VS Feedback:
Linq function Aggregate within a VB Source compiles, but throws NotImplementedException at Runtime
View on Developer Community
I have a VB.Net program, that contains the following method:
Option Strict On : Option Explicit On : Option Infer On
```VB
    Function get_sbs_konto_list(dest As String, firma As Integer, user As String) As String Implements Isbc_Mgeneral.get_sbs_konto_list
        Dim dao = IocContainer.Resolve(Of ILionDbDao)
        Dim query = dao.GetRefnumRowsForBankDestAndUser(dest, user.Trim.ToUpper)
        Dim res = query.Aggregate(New StringBuilder, Function(total, row) total.Append((row.Dtaid & New String(" "c, 5)).Substring(0, 5) & (row.Bkonto & New String(" "c, 25)).Substring(0, 25)))
        Return res.ToString
    End Function
```
When executing this, it throws the following error:
```
System.NotImplementedException
  HResult=0x80004001
  Message=Remotion.Linq.Clauses.ResultOperators.AggregateFromSeedResultOperator
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Query.ResultOperatorHandler.HandleResultOperator(EntityQueryModelVisitor entityQueryModelVisitor, ResultOperatorBase resultOperator, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalResultOperatorHandler.HandlerContext.EvalOnClient(Boolean requiresClientResultOperator)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalResultOperatorHandler.HandleResultOperator(EntityQueryModelVisitor entityQueryModelVisitor, ResultOperatorBase resultOperator, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitResultOperators(ObservableCollection`1 resultOperators, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Aggregate[TSource,TAccumulate](IQueryable`1 source, TAccumulate seed, Expression`1 func)
   at SBC_timer_service_neu.sbc_Mgeneral.get_sbs_konto_list(String dest, Int32 firma, String user) in C:\Users\wg\source\Repos\Development\Applications\Archive\CurrentDriveQ\sunrise\timer\Service\WEB_COM_SVC.NET\mgeneral.vb:line 558
   at SBC_timer_service_neu.sbc_MgeneralTest.get_sbs_konto_listTest() in C:\Users\wg\source\Repos\Development\Applications\Archive\CurrentDriveQ\sunrise\timer\Service\WEB_COM_SVC.NET\mgeneralTest.vb:line 98
```

It runs fine however, if I change the routine slighty:
```VB
        Dim res = query.AggregateEx(New StringBuilder, Function(total, row) total.Append((row.Dtaid & New String(" "c, 5)).Substring(0, 5) & (row.Bkonto & New String(" "c, 25)).Substring(0, 25)))
        ''Dim res = query.Aggregate(New StringBuilder, Function(total, row) total.Append((row.Dtaid & New String(" "c, 5)).Substring(0, 5) & (row.Bkonto & New String(" "c, 25)).Substring(0, 25)))

Where AggregateEx is defined as (in C#):
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static TAccumulate AggregateEx<TSource, TAccumulate>(this IQueryable<TSource> self, TAccumulate seed, Func<TAccumulate, TSource, TAccumulate> func)
        {
            return self.Aggregate(seed, func);
        }
```

I am using VS2017 15.8.4, with the latest VB compiler and .Net Framework 4.6.2 .

The Database is Access 97.
Entity framework Core 2.0

**Comment by ajcvickers** [comment]
Note from triage. The query pipeline has been extensively changed since this issue was filed. It may be that this pattern now gets translated correctly. If not, then a new issue should be filed and we will look into whether or not it is a VB-specific issue.
