### ISSUE TITLE
2.1 Web publish to Azure does not see Data Contexts or support EF migrations

### ISSUE THREAD

**Issue by vijayrkn** [dotnet/efcore#13398]
_From @Eilon on September 10, 2018 18:21_

_From @dpedrelli on Saturday, 01 September 2018 00:21:26_

# Issue Title
2.1 Web publish to Azure does not see Data Contexts or support EF migrations

# General
I have MVC app that targets netcoreapp2.0 and publishes to Azure.  Opening the Publish -> Configure -> Settings, it searches for Data Contexts, finds them, and presents me the option to apply EF migrations, per Data Context, and supply the respective connection string.

I updated the app to target netcoreapp2.1.  I open Publish -> Configure and change the Target Framework to netcoreapp2.1.  Going to settings, it does not find any Data Contexts.  If I manually edit ... - Web Deploy.pubxml.user and add the previous <ItemGroup> with <EFMigrations>, the publish fails, with the following error:

System.AggregateException: One or more errors occurred. ---> System.Exception: Build failed. Check the Output window for more details.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Web.Publish.PublishService.VsWebProjectPublish.<>c__DisplayClass43_0.<PublishAsync>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ApplicationCapabilities.Publish.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__127.MoveNext()
---> (Inner Exception #0) System.Exception: Build failed. Check the Output window for more details.<---

===================

_Copied from original issue: dotnet/core#1911_

_Copied from original issue: aspnet/websdk#410_

**Comment by vijayrkn** [comment]
_From @Eilon on September 10, 2018 18:21_

_From @Eilon on Monday, 10 September 2018 17:38:21_

@vijayrkn - any idea where this issue should go?

**Comment by vijayrkn** [comment]
_From @Eilon on September 10, 2018 18:21_

_From @vijayrkn on Monday, 10 September 2018 18:18:59_

@Eilon - You can move this to aspnet/websdk and we will take a look.

**Comment by vijayrkn** [comment]
@dpedrelli  Could this be same as this issue? https://github.com/aspnet/Home/issues/3399#issuecomment-413274239

Can you please try running the below command and see if it lists the output?
> dotnet ef dbcontext list --json

**Comment by vijayrkn** [comment]
_From @dpedrelli on September 10, 2018 19:47_

From Package Manager Console
dotnet ef dbcontext list --json

Default Project = .NET Standard 2.0 ClassLib (Data Abstraction Layer project)
Result = No project was found. Change the current working directory or use the --project option.

Default Project = .NET Core 2.1 MVC
Result = No project was found. Change the current working directory or use the --project option.

dotnet ef dbcontext list --json --project SM.DAL --startup-project SM.Mvc
From the MVC .csproj
<PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.3" />
Result = 
dotnet.exe : It was not possible to find any compatible framework versionAt line:1 char:1
+ dotnet ef dbcontext list --json --project SM.DAL --startup-project SM ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (It was not poss...amework version:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
The specified framework 'Microsoft.AspNetCore.All', version '2.1.3' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.1.2 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]

**Comment by vijayrkn** [comment]
_From @dpedrelli on September 10, 2018 19:48_

It did not post my PackageReference line from the MVC .csproj.  Here it is without the opening and closing symbols:

PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.3"

**Comment by vijayrkn** [comment]
_From @dpedrelli on September 10, 2018 20:10_

I just ran the Visual Studio Installer.  I updated from 15.8.2 to 15.8.3 and tried again

PM> dotnet ef dbcontext list --json --project SM.DAL --startup-project SM.Mvc
dotnet.exe : It was not possible to find any compatible framework versionAt line:1 char:1
+ dotnet ef dbcontext list --json --project SM.DAL --startup-project SM ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (It was not poss...amework version:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
The specified framework '
M
icrosoft.Asp
NetCore.All', ve
rsion '2.
1.3' 
was not
 fou
nd.

  - Ch
eck applic
ation depe
nden
cies
 and
 target a framework version instal
led at
:
  
    
C:\P
rogram 
Files\d
otnet\

  - Inst
alling 
.NET C
ore prer
equisites might hel
p re
solve this 
problem:
      http://go.m
icro
soft.co
m/fwl
ink/?Li
nkID=7
98306&
clcid
=0x409

  - The .NET Core framework and SDK can be installed 
from:

      
https:
//aka.ms/dotnet-download
  - The following versions are installed:
      2.1.2 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]

**Comment by vijayrkn** [comment]
Looks like a version mis-match issue. Can you share a sample csproj ?

**Comment by vijayrkn** [comment]
_From @dpedrelli on September 10, 2018 20:59_

@vijayrkn 
Separately from the Visual Studio Installer, I downloaded and installed .NET Core 2.1.401 SDK.  Now, the Publish settings sees the data contexts.  As I noted an an earlier comment, I did just update the installer to the latest version, 15.8.3, but that did not resolve the problem.  It is only when I downloaded the actual SDK did it work.

**Comment by vijayrkn** [comment]
_From @dpedrelli on September 10, 2018 21:43_

@vijayrkn 
Separately from the Visual Studio Installer, I downloaded and installed .NET Core 2.1.401 SDK.  Now, the Publish settings sees the data contexts.  As I noted an an earlier comment, I did just update the installer to the latest version, 15.8.3, but that did not resolve the problem.  It is only when I downloaded the actual SDK did it work.

**Comment by vijayrkn** [comment]
_From @dpedrelli on September 10, 2018 21:46_

@vijayrkn 
Follow-up.  The previous comment fixed the problem of seeing the data contexts.  Now, I get an error that I cannot create the SQL script.  It says that it does not support 

Executing command: dotnet ef migrations script --idempotent --output "w:\documents\visual studio 2017\Projects\SelectMarketing\SM.Mvc\obj\Release\netcoreapp2.1\PubTmp\EFSQLScripts\SM.DAL.MigrationDbContext.sql" --context SM.DAL.MigrationDbContext 
The EF Core tools version '2.1.1-rtm-30846' is older than that of the runtime '2.1.2-rtm-30932'. Update the tools for the latest features and bug fixes.
System.InvalidOperationException: The property 'ShowSchedule.Time' is of type 'DateTime' which is not supported by current database provider. Either change the property CLR type or ignore the property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyMappingValidationConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.Validate()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_1(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.ScriptMigration(String fromMigration, String toMigration, Boolean idempotent, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScriptMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The property 'ShowSchedule.Time' is of type 'DateTime' which is not supported by current database provider. Either change the property CLR type or ignore the property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

C:\Program Files\dotnet\sdk\2.1.401\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\TransformTargets\Microsoft.NET.Sdk.Publish.TransformFiles.targets(96,5): Error : Entity framework SQL Script generation failed

**Comment by vijayrkn** [comment]
@dpedrelli - Do you have a reference to 'EF Core tools version '2.1.1-rtm-30846' in the csproj? if so, can you update it to '2.1.2-rtm-30932' as mentioned in the error.

/cc @bricelam

**Comment by vijayrkn** [comment]
_From @dpedrelli on September 11, 2018 16:3_

@vijayrkn 
The project has a PackageReference to Microsoft.EntityFrameworkCore.Tools 2.1.2. (There is a newer version 2.1.3).
It, also, has a DotNetCliToolReference to Microsoft.EntityFrameworkCore.Tools.DotNet 2.0.0.

I will try different versions of Microsoft.EntityFrameworkCore.Tools and report what I find.

**Comment by vijayrkn** [comment]
@dpedrelli - Let us know how the package update goes. Ideally once the right packages are installed, EF migrations should just work.

**Comment by vijayrkn** [comment]
_From @dpedrelli on September 11, 2018 20:6_

@vijayrkn 

The first thing I did was to remove, as per the 2.0 to 2.1 migration guide
```
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="2.0.0" />
```

With 
```
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.1.3" PrivateAssets="all">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
```
I get
1>------ Build started: Project: SM.Mvc, Configuration: Release Any CPU ------
1>SM.Mvc -> w:\documents\visual studio 2017\Projects\SelectMarketing\SM.Mvc\bin\Release\netcoreapp2.1\SM.Mvc.dll
1>SM.Mvc -> w:\documents\visual studio 2017\Projects\SelectMarketing\SM.Mvc\bin\Release\netcoreapp2.1\SM.Mvc.Views.dll
2>------ Publish started: Project: SM.Mvc, Configuration: Release Any CPU ------
SM.Mvc -> w:\documents\visual studio 2017\Projects\SelectMarketing\SM.Mvc\bin\Release\netcoreapp2.1\SM.Mvc.dll
SM.Mvc -> w:\documents\visual studio 2017\Projects\SelectMarketing\SM.Mvc\bin\Release\netcoreapp2.1\SM.Mvc.Views.dll
SM.Mvc -> w:\documents\visual studio 2017\Projects\SelectMarketing\SM.Mvc\obj\Release\netcoreapp2.1\PubTmp\Out\
Generating Entity framework SQL Scripts...
Executing command: dotnet ef migrations script --idempotent --output "w:\documents\visual studio 2017\Projects\SelectMarketing\SM.Mvc\obj\Release\netcoreapp2.1\PubTmp\EFSQLScripts\SM.DAL.MigrationDbContext.sql" --context SM.DAL.MigrationDbContext 
Build failed.

C:\Program Files\dotnet\sdk\2.1.401\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\TransformTargets\Microsoft.NET.Sdk.Publish.TransformFiles.targets(96,5): Error : Entity framework SQL Script generation failed

2>Build failed. Check the Output window for more details.
========== Build: 1 succeeded, 0 failed, 9 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========

With
```
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.1.3" PrivateAssets="all">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
```
I get
9/11/2018 3:34:35 PM
System.AggregateException: One or more errors occurred. ---> System.Exception: Build failed. Check the Output window for more details.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Web.Publish.PublishService.VsWebProjectPublish.<>c__DisplayClass43_0.<PublishAsync>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ApplicationCapabilities.Publish.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__127.MoveNext()
---> (Inner Exception #0) System.Exception: Build failed. Check the Output window for more details.<---

===================

With
```
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.1.2" PrivateAssets="all">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
```
I get
1>------ Build started: Project: SM.Entities, Configuration: Release Any CPU ------
1>SM.Entities -> w:\documents\visual studio 2017\Projects\SelectMarketing\SM.Entities\bin\Release\netstandard2.0\SM.Entities.dll
2>------ Build started: Project: SM.DataValidators, Configuration: Release Any CPU ------
3>------ Build started: Project: SM.SeedData, Configuration: Release Any CPU ------
4>------ Build started: Project: SM.DataUpdaters, Configuration: Release Any CPU ------
4>SM.DataUpdaters -> w:\documents\visual studio 2017\Projects\SelectMarketing\SM.DataUpdaters\bin\Release\netstandard2.0\SM.DataUpdaters.dll
3>SM.SeedData -> w:\documents\visual studio 2017\Projects\SelectMarketing\SM.SeedData\bin\Release\netstandard2.0\SM.SeedData.dll
2>SM.DataValidators -> w:\documents\visual studio 2017\Projects\SelectMarketing\SM.DataValidators\bin\Release\netstandard2.0\SM.DataValidators.dll
5>------ Build started: Project: SM.DAL, Configuration: Release Any CPU ------
5>SM.DAL -> w:\documents\visual studio 2017\Projects\SelectMarketing\SM.DAL\bin\Release\netstandard2.0\SM.DAL.dll
6>------ Build started: Project: SM.Mvc, Configuration: Release Any CPU ------
6>Views\Manage\ChangePassword.cshtml(8,7,8,58): warning MVC1000: Use of IHtmlHelper.Partial may result in application deadlocks. Consider using <partial> Tag Helper or IHtmlHelper.PartialAsync.
6>Views\Manage\ExternalLogins.cshtml(7,7,7,58): warning MVC1000: Use of IHtmlHelper.Partial may result in application deadlocks. Consider using <partial> Tag Helper or IHtmlHelper.PartialAsync.
6>Views\Manage\SetPassword.cshtml(8,7,8,58): warning MVC1000: Use of IHtmlHelper.Partial may result in application deadlocks. Consider using <partial> Tag Helper or IHtmlHelper.PartialAsync.
6>Views\Manage\Index.cshtml(8,7,8,58): warning MVC1000: Use of IHtmlHelper.Partial may result in application deadlocks. Consider using <partial> Tag Helper or IHtmlHelper.PartialAsync.
6>SM.Mvc -> w:\documents\visual studio 2017\Projects\SelectMarketing\SM.Mvc\bin\Release\netcoreapp2.1\SM.Mvc.dll
6>SM.Mvc -> w:\documents\visual studio 2017\Projects\SelectMarketing\SM.Mvc\bin\Release\netcoreapp2.1\SM.Mvc.Views.dll
6>Done building project "SM.Mvc.csproj".
7>------ Publish started: Project: SM.Mvc, Configuration: Release Any CPU ------
SM.Mvc -> w:\documents\visual studio 2017\Projects\SelectMarketing\SM.Mvc\bin\Release\netcoreapp2.1\SM.Mvc.dll
SM.Mvc -> w:\documents\visual studio 2017\Projects\SelectMarketing\SM.Mvc\bin\Release\netcoreapp2.1\SM.Mvc.Views.dll
SM.Mvc -> w:\documents\visual studio 2017\Projects\SelectMarketing\SM.Mvc\obj\Release\netcoreapp2.1\PubTmp\Out\
Generating Entity framework SQL Scripts...
Executing command: dotnet ef migrations script --idempotent --output "w:\documents\visual studio 2017\Projects\SelectMarketing\SM.Mvc\obj\Release\netcoreapp2.1\PubTmp\EFSQLScripts\SM.DAL.MigrationDbContext.sql" --context SM.DAL.MigrationDbContext 
The EF Core tools version '2.1.1-rtm-30846' is older than that of the runtime '2.1.2-rtm-30932'. Update the tools for the latest features and bug fixes.
System.InvalidOperationException: The property 'ShowSchedule.Time' is of type 'DateTime' which is not supported by current database provider. Either change the property CLR type or ignore the property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyMappingValidationConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.Validate()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_1(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.ScriptMigration(String fromMigration, String toMigration, Boolean idempotent, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScriptMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The property 'ShowSchedule.Time' is of type 'DateTime' which is not supported by current database provider. Either change the property CLR type or ignore the property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

C:\Program Files\dotnet\sdk\2.1.401\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\TransformTargets\Microsoft.NET.Sdk.Publish.TransformFiles.targets(96,5): Error : Entity framework SQL Script generation failed

**Comment by vijayrkn** [comment]
@bricelam - Can you please help with the EF tools versions that is compatible with the latest runtime?

**Comment by vijayrkn** [comment]
_From @bricelam on September 11, 2018 20:37_

> System.InvalidOperationException: The property 'ShowSchedule.Time' is of type 'DateTime' which is not supported by current database provider. Either change the property CLR type or ignore the property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

What database provider are you using? Is it compatible with EF Core 2.1?

**Comment by vijayrkn** [comment]
_From @bricelam on September 11, 2018 20:39_

Do you see the build errors using `dotnet build`?

**Comment by vijayrkn** [comment]
_From @dpedrelli on September 12, 2018 12:7_

@bricelam 
I am using SQL Server, hosting on Azure.  Calling dotnet build, from the Package Manager Console produced errors that I do not get from building any of the projects using the IDE.  Note, none of this was an issue, when I targeted Core 2.0.  It has only come up, trying to target 2.1.

Some of the .csproj files contained old references, to projects that no longer exist.  They produced errors, for the dotnet build.  I removed those references.

The solution contains a WPF, Prism application, which is divided into modules.  All of the remaining errors seem to be "...does not exist in the current context..."

`error CS0103: The name 'InitializeComponent' does not exist in the current context`
`error CS0103: The name 'btnOK' does not exist in the current context`

However they do exist and the projects compile fine.  It is only when calling dotnet build or trying to publish, under Core 2.1, is this an issue.

**Comment by vijayrkn** [comment]
_From @dpedrelli on September 12, 2018 12:48_

@bricelam 
An additional piece of info.  I have a second MVC app, in the same solution.  It has a data context that accesses the same database.  However, it does not apply any migrations.  It builds and publishes without any errors.  It is only the app that applies migrations that has a problem.

**Comment by vijayrkn** [comment]
_From @bricelam on September 12, 2018 16:31_

I think we're going to need your solution to dig into this one...

**Comment by vijayrkn** [comment]
_From @dpedrelli on September 13, 2018 17:57_

@bricelam 
The solution without any binaries is about 60MB.  Also, there are some proprietary Nuget packages.  Is there an E-Mail address where I can send this?

**Comment by vijayrkn** [comment]
@bricelam - Since this issue is with the script generation, moving to the EF repo.

**Comment by ajcvickers** [comment]
@vijayrkn Creating a minimal repro would be better than having us try to run all your code.

**Comment by vijayrkn** [comment]
@ajcvickers - The customer was waiting for @bricelam to provide an email address where they can send the repro -https://github.com/aspnet/EntityFrameworkCore/issues/13398#issuecomment-423872210.

**Comment by ajcvickers** [comment]
@dpedrelli Creating a minimal repro would be better than having us try to run all your code.

**Comment by dpedrelli** [comment]
@ajcvickers I tried to create two, simple solutions.  One using 2.0 and the other 2.1.  I can post them, but I think I found the problem.  I have one class with two properties.  One property is int and the other is DateTime.  In the ModelBuilder, I use FluentAPI to specify the SQL Server time datatype.  

When I call 
`dotnet ef migrations script`
on 2.0 the command completes successfully.  When I call it on 2.1, I get the following error:

The property 'Class1.Time' is of type 'DateTime' which is not supported by current database provider. Either change the property CLR type or ignore the property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

The project contains these packages:
`  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.3" />
  </ItemGroup>
`

**Comment by ajcvickers** [comment]
@dpedrelli Can you show this line of code: "I use FluentAPI to specify the SQL Server time datatype."

**Comment by dpedrelli** [comment]
@ajcvickers 

`namespace Core21Test.Dal.ModelBuilders
{
    public static class Class1ModelBuilder
    {
        public static void Build(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Class1>(entity =>
            {
                entity.ToTable("Class1", "shared");

                entity.HasKey(e => e.ID);
                entity.Property(e => e.ID).UseSqlServerIdentityColumn();

                entity.Property(e => e.Time)
                    .HasColumnType("time")
                    .IsRequired(true);
            });
        }
    }
}`

**Comment by ajcvickers** [comment]
@dpedrelli The C# `DateTime` class does not map to the SQL datatype `time`. It's possibly that this configuration was being ignored prior to 2.1. What is the actual SQL type of the column in the database?

**Comment by dpedrelli** [comment]
@ajcvickers  If I go into Management Studio and script the table creation:

`[Time] [time](7) NOT NULL,`

However, I just need to use a C# TimeSpan, instead of DateTime?

Thanks,

David
