### ISSUE TITLE
"No DbContext found in assembly" after migrating to EF 2(.1) and ASP.Net Identity Core 2(.1)

### ISSUE THREAD

**Issue by mduu** [dotnet/efcore#13404]
Describe what is not working as expected.

I'm working on a Mac with Visual Studio for Mac (and VSCode if needed).

I try to update my existing .Net Core 1.1, EF Core 1.1, ASP.Net MVC Core 1.1 and ASP.Net Identity Core 1.1 to all the latest versions. After applying lots of tutorials I'm stuck. I decided to restart the MVC app / assembly from scratch by using

    dotnet new webapp --auth individual

This template worked. I then tried to move my cheese over. Especially removing the existing migration and database and using my own `ApplicationDbContext` stored in my "Common" assembly. It introduces a new IdentityUser with IdentityRoles on default.

Now I'm stuck again as I always get the following error messages:

```
$ dotnet ef migrations add initial
No DbContext was found in assembly 'Tauchbolde.Web'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.

$ dotnet ef dbcontext info
No DbContext was found in assembly 'Tauchbolde.Web'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.

$ dotnet ef dbcontext list
No DbContext was found.
```

I have absolutely no clue anymore what this thing is missing. Any help would be really appreciated.

### Steps to reproduce

You can reproduce by cloning my repo from [GitHub](https://github.com/mduu/tauchbolde) and try to add an initial migration:

    dotnet ef migrations add initial

### Further technical details
EF Core version: 2.1 (2.1.3)
Database Provider: Previously SqlServer but now on SqlLite
Operating system: macOs High Sierra
IDE: latest Visual Studio for Mac / Latest VS Code

**Comment by ajcvickers** [comment]
@mduu Looks like the DbContext is not in the main project. The code you posted doesn't build for me, so I haven't been able to try it, but it looks like you need to specify the project on the command line as described here: https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#using-the-tools

**Comment by mduu** [comment]
@ajcvickers You are right - my context is in another assembly. I thought specifying it wasn't necessary in EF Core 1.x. Maybe I'm wrong - its a while ago already when I used EF Core. I'll try the CLI switches. Thanks for the link.

**Comment by mduu** [comment]
I've tried hard to get it work but still without success. I did decouple my custom User-Entity from the one that Identity provides. So this custom User-Entity setup is gone now. I also ensured the project builds using a Azure Pipeline CI build. It still builds on my machine (Mac).

I tried to add a migration from within the `/src/Tauchbolde.Web` directory using the following command:

    dotnet ef migrations add initial --project ../Tauchbolde.Common/Tauchbolde.Common.csproj

This results always in the error:

    Unable to create an object of type 'ApplicationDbContext'. Add an implementation of 'IDesignTimeDbContextFactory<ApplicationDbContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.

Even with your link and the one in the above error message I just could not figure what statement will work here. Tried the same statement without the csproj etc.

I then tried to add a migration from within the `/src/Tauchbolde.Common` directory as this one hosts the `ApplicationDbContext` that should be used.

    dotnet ef migrations add initial

Here I get the following error:

```
The specified framework version '2.1' could not be parsed
The specified framework 'Microsoft.NETCore.App', version '2.1' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/local/share/dotnet/
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      1.0.4 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
      1.1.1 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
      2.0.0 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
      2.0.3 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
      2.0.5 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
      2.1.2 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
      2.1.4 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```
As I understand EF Core needs a startup project (like `Tauchbolde.Web`) and a DbContext which in my solution does live in `Tauchbolde.Common`. So I tried to add the migration from `/src` and specify everything:

    dotnet ef migrations add initial --startup-project ./Tauchbolde.Web/ --project ./Tauchbolde.Common/ -c ApplicationDbContext

The error I get here is:

```
Unable to create an object of type 'ApplicationDbContext'. Add an implementation of 'IDesignTimeDbContextFactory<ApplicationDbContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.
```

The same happened for commands like:

    dotnet ef dbcontext info

As you see I'm really stuck here getting EF Core 2.1 to work and I really could need some help.

**Comment by mduu** [comment]
I just managed to add a `ApplicationDbContext` and not it seems that I got a step further. Now I get complains about the ASP.Net Identity-Entitiframework model:

```
$dotnet ef migrations add initial -s . -p ../Tauchbolde.Common/
System.InvalidOperationException: The entity type 'IdentityUserLogin<int>' requires a primary key to be defined.
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNonNullPrimaryKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqliteModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_1(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The entity type 'IdentityUserLogin<int>' requires a primary key to be defined.
```

**Comment by oswaldozapata** [comment]
I got resolved my issue by using the command this way: 
cd to your startup project root folder, from there execute all the commands
MyProject.MigrationApp/> dotnet ef dbcontext list --project ../MyProject.EFCoreSqlServer

MyProject.MigrationApp, this is my startup project
MyProject.EFCoreSqlServer, this is the project that contains the db context definitions.

Now in the same way you can run all the other commands

MyProject.MigrationApp/> dotnet ef database update --project ../MyProject.EFCoreSqlServer

**Comment by Nicole-Zessec** [comment]
@oswaldozapata Thank you so much for your solution ! It did the work for me.
