### ISSUE TITLE
Conversion issue with a query that calculates the difference between two date time offsets

### ISSUE THREAD

**Issue by Cyberboss** [dotnet/efcore#13449]
Also reporting this here (https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/691) because I'm not entirely sure where the problem is

I have a table `CompileJobs`

![image](https://user-images.githubusercontent.com/8171642/46249511-69416800-c3f8-11e8-8e94-85a066fd5b8c.png)

which is keyed to a table `Jobs`

![image](https://user-images.githubusercontent.com/8171642/46249502-37300600-c3f8-11e8-8be7-6dd4f579ef77.png)

The query generated by this statement:
```c#
			var compileJobsTask = databaseContext.CompileJobs
				.Where(x => x.Job.Instance.Id == metadata.Id)
				.OrderByDescending(x => x.Job.StoppedAt)
				.Select(x => x.Job.StoppedAt.Value - x.Job.StartedAt.Value)
				.Take(10)
				.ToListAsync(cancellationToken);
```
(`Job.StartedAt` and `Job.StoppedAt` are both nullable `DateTimeOffset` types)

ends up erroring like so:
```
System.InvalidOperationException: An exception occurred while reading a database value. The expected type was 'System.TimeSpan' but the actual value was of type 'System.Decimal'. ---> System.InvalidCastException: Unable to cast object of type 'System.Decimal' to type 'System.TimeSpan'.
   at MySql.Data.MySqlClient.MySqlDataReader.GetFieldValue[T](Int32 ordinal) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 256
   at lambda_method(Closure , DbDataReader )
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.ThrowReadValueException[TValue](Exception exception, Object value, IPropertyBase property)
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.Aggregate_[TSource,TAccumulate,TResult](IAsyncEnumerable`1 source, TAccumulate seed, Func`3 accumulator, Func`2 resultSelector, CancellationToken cancellationToken)
   at Tgstation.Server.Host.Components.Instance.CompileProcess(Job job, IDatabaseContext databaseContext, Action`1 progressReporter, CancellationToken cancellationToken) in /src/src/Tgstation.Server.Host/Components/Instance.cs:line 182
   at Tgstation.Server.Host.Core.JobManager.<>c__DisplayClass6_1.<<RunJob>g__RunJobInternal|2>d.MoveNext() in /src/src/Tgstation.Server.Host/Core/JobManager.cs:line 115
--- End of stack trace from previous location where exception was thrown ---
   at Tgstation.Server.Host.Core.JobManager.<>c__DisplayClass6_0.<<RunJob>g__HandleExceptions|1>d.MoveNext() in /src/src/Tgstation.Server.Host/Core/JobManager.cs:line 82
```
It can be worked around by changing the statement like so:
```c#
var compileJobsTask = databaseContext.CompileJobs
				.Where(x => x.Job.Instance.Id == metadata.Id)
				.OrderByDescending(x => x.Job.StoppedAt)
				.Select(x => new Job
				{
					StoppedAt = x.Job.StoppedAt,
					StartedAt = x.Job.StartedAt
				})
				.Take(10)
				.ToListAsync(cancellationToken);
```
And doing the math after the query finishes
Full patch here: https://github.com/tgstation/tgstation-server/pull/740/files

The exact line and revision of this error is here: https://github.com/tgstation/tgstation-server/blob/a3041dd7dfbc4a3261e88524d160798c25714431/src/Tgstation.Server.Host/Components/Instance.cs#L142

Sorry for the lack of a small repro. If it's really necessary, let me know and I'll try and draft something later this week.

Pomelo.EntityFrameworkCore.MySql version: Nuget 2.1.2
Microsoft.EntityFrameworkCore version: Nuget 2.1.3

**Comment by smitpatel** [comment]
This is issue in MySQL provider. Each provider needs to disable binary operators which are not supported in provider.
Like SqlServer does in this file, https://github.com/aspnet/EntityFrameworkCore/blob/release/2.2/src/EFCore.SqlServer/Query/ExpressionVisitors/Internal/SqlServerSqlTranslatingExpressionVisitor.cs

**Comment by ajcvickers** [comment]
Closing this as external per analysis above.
