### ISSUE TITLE
Relaxed check if something is tracked - duplicated key violation

### ISSUE THREAD

**Issue by ice1e0** [dotnet/efcore#13453]
### The short story
I need a easy, relaxed way where I can request from the DbContext if something is tracked to change.

### The long story
In my WPF application I use a SaveCommand with a `CanSave(..)` method to check if something can be saved. This method looks like the following:

``` csharp
private bool CanSave()
{
    return DbContext.ChangeTracker.Entries().Any(e => e.State == EntityState.Added ||
                                                      e.State == EntityState.Modified ||
                                                      e.State == EntityState.Deleted);
}
```

When a duplicate key violation occurs, the `.Entries()` method throws an `System.InvalidOperationException` exception. By this I am not anymore able to determine if a save would be possible or not.

I need here an relaxed way to find out if changes are available, independent of if a primary key / unique key constraint violation exist. When the user then will execute the command, I want to give a proper error to the user.

### Exception
```
Exception message: System.InvalidOperationException: "The instance of entity type '{EntryType}' cannot be tracked because another instance with the key value '{Primary key fields and values}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached."
Stack trace:
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NullableKeyIdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.UpdateIdentityMap(InternalEntityEntry entry, IKey key)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IReadOnlyList`1 containingPrincipalKeys, IReadOnlyList`1 containingForeignKeys, Object oldValue, Object newValue)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IReadOnlyList`1 keys, IReadOnlyList`1 foreignKeys, Object oldValue, Object newValue)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectKeyChange(InternalEntityEntry entry, IProperty property)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager)
   at Microsoft.EntityFrameworkCore.ChangeTracking.ChangeTracker.DetectChanges()
   at Microsoft.EntityFrameworkCore.ChangeTracking.ChangeTracker.Entries()
   at MyNamespace.MyClass.CanSave()
```

### Further technical details
EF Core version: 2.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows
IDE: Visual Studio 2017 15.6

**Comment by ajcvickers** [comment]
@ice1e0 The general answer to this is that EF exceptions should not be used as a means for your application to determine what to do. In other words, attempting to track two entity instances with the same key value is a program error, not a recoverable situation that can be corrected such that the program can continue. Instead of telling EF to do something it can't do, check beforehand in your app whether it is valid. For example, if there is a possibility that a duplicate key value might have been obtained, then check whether an entity with a given key value exists or not before attempting to track it .
