### ISSUE TITLE
EF Core exception when i send multiple requests

### ISSUE THREAD

**Issue by shakeri** [dotnet/efcore#13452]
I updated my project to ASP.NET Core 2.1 RTM.
When I send multiple requests, i get this exception:

```
Exception has occurred: CLR/System.Data.SqlClient.SqlException
An exception of type 'System.Data.SqlClient.SqlException' occurred in Microsoft.EntityFrameworkCore.dll but was not handled in user code: 'Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.ComponentModel.Win32Exception : Unknown error 258
```
In `MyContext` class:
```C#
public  class MyContext : DbContext, IUnitOfWork
{
    public MyContext(DbContextOptions<MyContext> options)
          : base(options) { }
    public virtual DbSet<MyEntity> MyEntity { get; set; }
}
```

In `TestService` class:
```C#
public class TestService : ITestService
    {
        private readonly IUnitOfWork _uow;
        private readonly DbSet<MyEntity> _myEntity;
        public LogRecentService(IUnitOfWork uow)
        {
            _uow = uow;
            _myEntity = _uow.Set<MyEntity>();
        }
        public void Add(MyEntity model)
        {
            _myEntity.Add(model);
            _uow.SaveChanges();
        }
    }
```

In `Startup` class:
```C#
services.AddScoped<IUnitOfWork, MyContext>();
services.AddEntityFrameworkSqlServer();
services.AddDbContextPool<MyContext>(options =>
            {
                string connectionString = Configuration.GetConnectionString("MyConnection");
                options.UseSqlServer(
                connectionString
                , serverDbContextOptionsBuilder =>
                {
                    var minutes = (int)TimeSpan.FromMinutes(3).TotalSeconds;
                    serverDbContextOptionsBuilder.CommandTimeout(minutes);
                    serverDbContextOptionsBuilder.EnableRetryOnFailure();
                });
            });
services.AddScoped<ITestService, TestService>();
```
### Further technical details
EF Core version: 2.1
Operating system: Ubuntu 18.04 LTS

**Comment by ajcvickers** [comment]
@shakeri Can you post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

**Comment by shakeri** [comment]
@ajcvickers I uploaded a sample code for this problem.
[SampleCode.zip](https://github.com/aspnet/EntityFrameworkCore/files/2436601/SampleCode.zip)

To test this example:
```
static void Main(string[] args)
{
	using (var client = new HttpClient())
	{
		client.BaseAddress = new Uri("http://localhost:50887/");
		var list = new List<Model>();
		for (int i = 1; i < 10001; i++)
		{
			list.Add(new Model{
				FirstName = $"FirstName{i}",
				LastName = $"LastName{i}",
				BirthDate = DateTime.Now
			});
		}
		Parallel.ForEach(list, (model) => {
		   var content =new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");
		   var result = client.PostAsync("api/v1/sample",content).Result;
		   if(result.IsSuccessStatusCode)
		   {
			   Console.WriteLine("done!");
		   }
		});
	}
}
```

This sample code works in Windows 10 without problems, but it fails in Ubuntu.

**Comment by ajcvickers** [comment]
@shakeri I have so far not been able to reproduce this. Can you post the full stack trace? Also, have you tried using raw ADO.NET commands to the database? Do you get timeouts with that mechanism too?

**Comment by shakeri** [comment]
> Can you post the full stack trace?

```
Exception has occurred: CLR/System.InvalidOperationException
An exception of type 'System.InvalidOperationException' occurred in Microsoft.EntityFrameworkCore.dll but was not handled in user code: 'Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.'
at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
 at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at Traffic.Services.Services.Implementations.WantedPlateService.GetWantedPlate(Int64 masterPlateNumber) in /home/shakeri/Desktop/TrafficServicesCore/src/Traffic.Services.Services/Implementaion/WantedPlateService.cs:line 37
   at Traffic.Services.Api.Receive.Controllers.TrafficController.GenerateResponse(TrafficViewModel model) in /home/shakeri/Desktop/TrafficServicesCore/src/Traffic.Services.Api.Receive/Controllers/TrafficController.cs:line 178
   at Traffic.Services.Api.Receive.Controllers.TrafficController.Post(TrafficViewModel viewModel) in /home/shakeri/Desktop/TrafficServicesCore/src/Traffic.Services.Api.Receive/Controllers/TrafficController.cs:line 110
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
 at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
```

> Also, have you tried using raw ADO.NET commands to the database? Do you get timeouts with that mechanism too?

@ajcvickers I tried with ADO.NET, but with ADO.NET it works without problems:
```
using (SqlConnection conn = new SqlConnection(_siteSetting.Value.ConnectionString))
                using (SqlCommand cmd = new SqlCommand("sp_Create", conn))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.Add("@FirstName",SqlDbType.VarChar).Value =  model.FirstName;
                    cmd.Parameters.Add("@LastName", SqlDbType.VarChar).Value = model.LastName;
                    cmd.Parameters.Add("@BirthDate", SqlDbType.DateTime).Value = model.BirthDate;
                    conn.Open();
                    cmd.ExecuteNonQuery();
                    conn.Close();
                }
```

**Comment by ajcvickers** [comment]
@smitpatel to investigate

**Comment by smitpatel** [comment]
I investigated this and got no error. I used same connection string properties as in sample project and ran server/client both on ubuntu 18.04 with dotnet SDK 2.1
Given that you are using max pool size, it is likely that server is choking on this.

**Comment by shakeri** [comment]
@smitpatel I removed `max pool size=50` from the connection string, but this time i get this error:
```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_0`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at MyApp.Services.Implementations.WantedPlateService.GetWantedPlate(Int64 masterPlateNumber)
   at MyApp.Api.Receive.Controllers.MyController.GenerateResponse(MyViewModel model)
   at MyApp.Api.Receive.Controllers.MyController.V1Post(MyViewModel viewModel)
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
ClientConnectionId:00000000-0000-0000-0000-000000000000
fail: Microsoft.EntityFrameworkCore.Query[100100]
      An exception occurred in the database while iterating the results of a query for context type 'MyApp.Data.Contexts.MyDbContext'.
      System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
         at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
         at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
         at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
         at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
         at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
         at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
         at System.Data.SqlClient.SqlConnection.Open()
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
         at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
         at lambda_method(Closure , QueryContext )
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_0`1.<CompileQueryCore>b__0(QueryContext qc)
      ClientConnectionId:00000000-0000-0000-0000-000000000000
```
I thought this error was about not having access to database server. i reviewed this issue but the server port was not closed.
```
telnet server ip address 1433
Trying server ip address...
Connected to server ip address.
```

**Comment by ajcvickers** [comment]
@shakeri Can you change your `Add` method from this:
```C#
public void Add(MyEntity model)
{
    _sample.Add(model);
    _uow.SaveChanges();
}
```
to this:
```C#
public void Add(MyEntity model)
{
    var connection = _sample.GetService<ICurrentDbContext>().Context.Database.GetDbConnection();

    using (var command = connection.CreateCommand())
    {
        command.CommandText = "INSERT INTO [MyEntity] ([BirthDate], [FirstName], [LastName]) VALUES(@p0, @p1, @p2) SELECT [Id] FROM[MyEntity] WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity()";

        var param1 = command.CreateParameter();
        param1.ParameterName = "@p0";
        param1.Value = DateTime.Now;
        command.Parameters.Add(param1);

        var param2 = command.CreateParameter();
        param2.ParameterName = "@p1";
        param2.Value = "A";
        command.Parameters.Add(param2);

        var param3 = command.CreateParameter();
        param3.ParameterName = "@p2";
        param3.Value = "U";
        command.Parameters.Add(param3);

        connection.Open();

        using (var reader = command.ExecuteReader())
        {
            reader.Read();
            var generatedId = reader.GetInt64(0);
        }

        connection.Close();
    }
}
```
And report back what happens?

**Comment by shakeri** [comment]
@ajcvickers I changed the `add` method with this code:
```
 public long Add(MyEntity model)
        {
            var connection = _uow.GetDBConnection();
            long id = 0;
            using (var command = connection.CreateCommand())
            {
                command.CommandText = "INSERT INTO [MyEntity] ([BirthDate], [FirstName], [LastName]) VALUES(@p0, @p1, @p2) SELECT [Id] FROM[MyEntity] WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity()";

                var param1 = command.CreateParameter();
                param1.ParameterName = "@p0";
                param1.Value = model.BirthDate;
                command.Parameters.Add(param1);

                var param2 = command.CreateParameter();
                param2.ParameterName = "@p1";
                param2.Value = model.FirstName;
                command.Parameters.Add(param2);

                var param3 = command.CreateParameter();
                param3.ParameterName = "@p2";
                param3.Value = model.LastName;
                command.Parameters.Add(param3);

                connection.Open();

                using (var reader = command.ExecuteReader())
                {
                    reader.Read();
                    id = reader.GetInt64(0);
                }
                connection.Close();
                return id;
            }
        }
```
When i call this method as parallel, it worked without problem.
Call :
```
 using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:50887");
                var list = new List<Model>();
                for (int i = 1; i < 10001; i++)
                {
                    list.Add(new Model
                    {
                        FirstName = $"FirstName{i}",
                        LastName = $"LastName{i}",
                        BirthDate = DateTime.Now
                    });
                }
                Parallel.ForEach(list, (model) =>
                {
                    var content = new StringContent(JsonConvert.SerializeObject(model));
                    var result = client.PostAsync("api/v1/sample", content).Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var returnModel = JsonConvert.DeserializeObject<long>(result.Content.ReadAsStringAsync().Result);
                        Console.WriteLine("Created with Id: {0}", returnModel);
                    }
                });
            }
```
Result: 
```
Created with Id: 24669
Created with Id: 24672
Created with Id: 24673
Created with Id: 24674
Created with Id: 24675
Created with Id: 24676
Created with Id: 24677
Created with Id: 24678
Created with Id: 24679
Created with Id: 24680
Created with Id: 24682
Created with Id: 24683
Created with Id: 24684
...
```

**Comment by ajcvickers** [comment]
@shakeri Thanks, but I specifically wanted you to use `_sample.GetService<ICurrentDbContext>().Context.Database.GetDbConnection();` to get the DbConnection so that it is EF Core that is supplying the connection.

**Comment by shakeri** [comment]
@ajcvickers I used Unit of Work pattern and in this pattern for get `DbConnection` i did this:
```
 public interface IUnitOfWork : IDisposable
    {
        ...
        DbConnection GetDBConnection(); 
        ...
    }
```

```
public partial class TestDBContext : DbContext, IUnitOfWork
    {
        ...
        public DbConnection GetDBConnection()
        {
           return Database.GetDbConnection();
        }
        ...
    }
```
I can't get `DbConnection` through `_sample.GetService<ICurrentDbContext().Context.Database.GetDbConnection();`

**Comment by ajcvickers** [comment]
@shakeri Can you explain a bit more what you mean by, "I can't get DbConnection through..." 

(Keep in mind we're not trying to make your application work here, we're trying to find if there is a bug in EF Core and if so how it manifests. Since the code I posted mirrors the way the context gets the connection it means if this is failing then it is a good clue as to what is going on.)

**Comment by shakeri** [comment]
> Can you explain a bit more what you mean by, "I can't get DbConnection through..."

@ajcvickers In the file i uploaded `_sample` is a entity model:

```
public class SampleService : ISampleService
    {
        private readonly IUnitOfWork _uow;
        private readonly DbSet<MyEntity> _sample;
        public SampleService(
            IUnitOfWork uow
            )
        {
            _uow = uow;
            _sample = _uow.Set<MyEntity>();
        }

        public void Add(MyEntity model)
        {
            _sample.Add(model);
            _uow.SaveChanges();
        }
    }
```
On the other hand, what is the problem of how to get `DbConnection` in my example?

**Comment by ajcvickers** [comment]
@shakeri `_sample` is of type `DbSet<MyEntity>`. The code I posted should work fine with any `DbSet` type. Is it not working for you? If so, what are the errors you see?

**Comment by shakeri** [comment]
Uhh, I'm so sorry.I thought `ICurrentDbContext` is a `DbContext` on your sample. :))
@ajcvickers I tested again with `_sample.GetService<ICurrentDbContext>().Context.Database.GetDbConnection();` and it work fine.

```
public long Add(MyEntity model)
        {
            var connection = _sample.GetService<ICurrentDbContext>().Context.Database.GetDbConnection();
            long id = 0;
            using (var command = connection.CreateCommand())
            {
                command.CommandText = "INSERT INTO [MyEntity] ([BirthDate], [FirstName], [LastName]) VALUES(@p0, @p1, @p2) SELECT [Id] FROM[MyEntity] WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity()";

                var param1 = command.CreateParameter();
                param1.ParameterName = "@p0";
                param1.Value = model.BirthDate;
                command.Parameters.Add(param1);

                var param2 = command.CreateParameter();
                param2.ParameterName = "@p1";
                param2.Value = model.FirstName;
                command.Parameters.Add(param2);

                var param3 = command.CreateParameter();
                param3.ParameterName = "@p2";
                param3.Value = model.LastName;
                command.Parameters.Add(param3);

                connection.Open();

                using (var reader = command.ExecuteReader())
                {
                    reader.Read();
                    id = reader.GetInt64(0);
                }
                connection.Close();
                return id;
            }
        }
```

**Comment by ajcvickers** [comment]
@shakeri Thanks for trying. I'll look into this some more next week.

**Comment by ajcvickers** [comment]
@shakeri I've had some more time to investigate this further and I'm out of ideas. I can't reproduce what you are seeing, and I don't know what might be different. I think at this point without being able to reproduce what is going on we're not going to get much further.

One more thought. Since this is essentially a perf issue, have you tried profiling and looking where the time is being spent?

**Comment by shakeri** [comment]
@ajcvickers I found problem.The SQL Server host has received two updates: [KB4338815](https://support.microsoft.com/en-us/help/4338815/windows-81-update-kb4338815), [KB4338824](https://support.microsoft.com/en-us/help/4338824/windows-81-update-kb4338824).

> Known issues in this update
> Restarting the SQL Server service may fail occasionally with the error, “Tcp port is already in use”.

When I removed these updates, my project worked without problem.
