### ISSUE TITLE
Allow services to be easily resolved from the application service provider from within EF Core

### ISSUE THREAD

**Issue by chernihiv** [dotnet/efcore#13540]
I try to resolve CustomMigrationsSqlGenerator with IMyCustomService but it throws an exception.

I have overridden partially logic inside SqlServerMigrationsSqlGenerator,  but for my goal I need to resolve extra service inside, e.g:
```C#
class CustomMigrationsSqlGenerator : SqlServerMigrationsSqlGenerator
{
    public CustomMigrationsSqlGenerator (
        IMyCustomService service,
        MigrationsSqlGeneratorDependencies dependencies,
        IMigrationsAnnotationProvider migrationsAnnotations)
        : base(dependencies, migrationsAnnotations)  { }

}
```
it throws an exception
`System.InvalidOperationException: Unable to resolve service for type 'IMyCustomService' while attempting to activate 'CustomMigrationsSqlGenerator'.`

_IMyCustomService_ is registered as:
```C#
...
services.AddScoped<IMyCustomService, MyCustomService>();
...
```

#### Further technical details
EF Core: Microsoft.EntityFrameworkCore 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer 2.1.4
Operating system: Windows 10 Pro 1803, 17134.285
IDE: Visual Studio 2017 15.8.6

**Comment by ajcvickers** [comment]
@chernihiv Could you show the code for setting up the service provider(s)?

**Comment by chernihiv** [comment]
@ajcvickers  Sure, I've built from scratch, empty solution.

Here is all configuration:

```
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddScoped<IMyCustomService, MyCustomService>();
            services.AddDbContext<InitContext>(item => item
                .UseSqlServer(@"Data Source=.\SQLEXPRESS;Initial Catalog=Test1;Integrated Security=True;Persist Security Info=False;MultipleActiveResultSets=True")
                .ReplaceService<IMigrationsSqlGenerator, CustomMigrationsSqlGenerator>());

            services.AddMvc();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseDeveloperExceptionPage();            
            app.UseMvc();
        }
    }

    public class InitContext : DbContext
    {
        public InitContext(DbContextOptions<InitContext> options) : base(options)
        {
        }
        public DbSet<User> Users { get; set; }
    }
    
    public class User
    {
        public int Id { get; set; }
    }

    internal class CustomMigrationsSqlGenerator : SqlServerMigrationsSqlGenerator
    {
        public CustomMigrationsSqlGenerator(
            IMyCustomService myCustomService,
            MigrationsSqlGeneratorDependencies dependencies,
            IMigrationsAnnotationProvider migrationsAnnotations)
            : base(dependencies, migrationsAnnotations) { }

    }

    internal class MyCustomService : IMyCustomService
    {
        public string Test()
        {
            return "test";
        }
    }

    public interface IMyCustomService
    {
        string Test();
    }
```
Here is controller for testing. Don't forget to create Init migration.
```

[Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
        private readonly InitContext _context;
        private readonly IMyCustomService _myCustomService;
        public ValuesController(InitContext context, IMyCustomService myCustomService)
        {
            _context = context;
            _myCustomService = myCustomService;
        }

        [HttpGet("/test/users")]
        public async Task<IEnumerable<User>> TestUsers()
        {
            return await _context.Users.ToListAsync();
        }

        [HttpGet("/migrate")]
        public async Task Migrate()
        {
            await _context.Database.MigrateAsync();
        }

        [HttpGet("/test/service")]
        public ActionResult<string> TestService()
        {
            return _myCustomService.Test();
        }
    }
```

Without IMyCustomService in CustomMigrationsSqlGenerator  you are able to Migrate and use all APIs, but with IMyCustomService service you should receive the following exception:

```
InvalidOperationException: Unable to resolve service for type 'WebApplication4.IMyCustomService' while attempting to activate 'WebApplication4.CustomMigrationsSqlGenerator'.

System.InvalidOperationException: Unable to resolve service for type 'WebApplication4.IMyCustomService' while attempting to activate 'WebApplication4.CustomMigrationsSqlGenerator'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetRelationalService[TService](IInfrastructure`1 databaseFacade)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.MigrateAsync(DatabaseFacade databaseFacade, CancellationToken cancellationToken)
   at WebApplication4.Controllers.ValuesController.Migrate() in C:\Users\Сергій\source\repos\WebApplication4\WebApplication4\Controllers\ValuesController.cs:line 29
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by ajcvickers** [comment]
Notes for triage: there are several things going on here:
* IMigrationsSqlGenerator is a singleton service and so cannot depend on a scoped custom service. This is the way D.I, works, so going forward I'm assuming the custom service is registered as a singleton.
* The custom service is registered in the application's service provider, but IMigrationsSqlGenerator is resolved from the internal service provider
* The normal pattern recommended here is to use the DbContext as a service locator since it has a bridge to the application service provider, but this pattern doesn't work for singleton services since the DbContext itself cannot be obtained in a singleton service

So this leaves taking over the internal service provider as the only solution, which is a bit drastic for just adding a singleton dependency to a singleton service.

**Comment by ajcvickers** [comment]
Notes from triage: we should consider allow registering an explicit bridge service in the internal service provider such that both singleton services can be registered and so that constructor injection can be used to resolve these in replaced services.

@chernihiv Overriding the MigrationsSqlGenerator is not the way to do this. It would allow different databases to be created, but would not allow them to be used with the underlying EF model. Instead consider dynamically building different models based on the tenant. Controlling when the different models are used can be done with a [ModelCacheKey](https://stackoverflow.com/questions/41979215/how-to-implement-imodelcachekeyfactory-in-ef-core)

**Comment by chernihiv** [comment]
@ajcvickers Sure, I do similar things in the same way, but instead schema I change table name. It works. 

But, what if there is new Tenant? Tenant could specify any DB Provider and Connection he wish. What I need is to apply migrations to this database and seed it with data.

I have common clear migrations, it knows nothing about tenant and I should dynamically change schema or tableprefix and migrate it for new Tenant. Therefore, I need to override IMigrationsSqlGenerator for all supported db providers and change on spot schema or table name.

**Comment by ajcvickers** [comment]
See also the scenarios and suggestions in #23559 when working on this issue.
