### ISSUE TITLE
Could not load file System.Interactive.Async

### ISSUE THREAD

**Issue by ravenboilinux** [dotnet/efcore#13619]
I get this error for a package that does not exists when i run a program
Could not load file or assembly 'System.Interactive.Async, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' or one of its dependencies. The system cannot find the file specified.
there is no version 3.0.3000.0 of System.Interactive.Async

Exception message:
Could not load file or assembly 'System.Interactive.Async, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' or one of its dependencies. The system cannot find the file specified.
there is no version 3.0.3000.0 of System.Interactive.Async
Stack trace:
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.TryAddCoreServices()
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.ApplyServices(IDbContextOptions options, ServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_0.<GetOrAdd>b__2(Int64 k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at MGF.MGFContext..ctor() in C:\Users\micha\source\repos\InnerSanctum\src\MGF.DataEntities\MGFContext.cs:line 13
   at Servers.Config.ServerType.GetServerType(Int32 serverType) in C:\Users\micha\source\repos\InnerSanctum\src\Servers\Config\ServerType.cs:line 20
   at MGF_Photon.Implementation.Handler.HandlerServerRegistration.OnHandleMessage(IMessage message, PhotonServerPeer serverPeer) in C:\Users\micha\source\repos\InnerSanctum\src\MGF.Photon\Implementation\Handler\HandlerServerRegistration.cs:line 96
   at MGF_Photon.Implementation.Handler.HandlerServerRegistration.OnHandleMessage(IMessage message, IServerPeer serverPeer) in C:\Users\micha\source\repos\InnerSanctum\src\MGF.Photon\Implementation\Handler\HandlerServerRegistration.cs:line 44
   at MultiplayerGameFramework.Implementation.Messaging.ServerHandler.HandleMessage(IMessage message, IServerPeer peer) in C:\Users\micha\source\repos\InnerSanctum\src\MultiplayerGameFramework\Implementation\Messaging\ServerHandler.cs:line 19
   at MultiplayerGameFramework.Implementation.Messaging.BaseHandlerList`1.HandleMessage(IMessage message, T peer) in C:\Users\micha\source\repos\InnerSanctum\src\MultiplayerGameFramework\Implementation\Messaging\BaseHandlerList.cs:line 58
   at MultiplayerGameFramework.Implementation.Messaging.ServerHandlerList.HandleMessage(IMessage message, IServerPeer peer) in C:\Users\micha\source\repos\InnerSanctum\src\MultiplayerGameFramework\Implementation\Messaging\ServerHandlerList.cs:line 36
   at MGF_Photon.Implementation.Server.PhotonServerPeer.HandleMessage(IMessage message) in C:\Users\micha\source\repos\InnerSanctum\src\MGF.Photon\Implementation\Server\PhotonServerPeer.cs:line 113
   at MGF_Photon.Implementation.Server.PhotonServerPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in C:\Users\micha\source\repos\InnerSanctum\src\MGF.Photon\Implementation\Server\PhotonServerPeer.cs:line 68
   at MGF_Photon.Implementation.Server.InboundPhotonPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in C:\Users\micha\source\repos\InnerSanctum\src\MGF.Photon\Implementation\Server\InboundPhotonPeer.cs:line 42
   at Photon.SocketServer.ServerToServer.S2SPeerBase.OnReceive(Byte[] data, SendParameters sendParameters) in h:\svncontent\photon-socketserver-sdk_cloud\src\Photon.SocketServer\ServerToServer\S2SPeerBase.cs:line 192
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures) in h:\svncontent\photon-socketserver-sdk_cloud\src\Photon.SocketServer\PeerBase.cs:line 988
```

### Steps to reproduce
here this the link to solution 
https://github.com/ravenboilinux/InnerSanctumServer.git
you have to download the Photon Server and unzip to 
C:\photonserverplugin\Photon-OnPremise-Server-Plugin-SDK_v4-0-29-11263
this will allow you to debug the project. 

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Window 10
IDE: Visual Studio 2017

**Comment by ravenboilinux** [comment]
I have executed both commands:
```
PM> Update-Package System.Interactive.Async -Reinstall
PM> Get-Project –All | Add-BindingRedirect
```
Unfortunately, I still get the same exception

all my bindingRedirect for all the config files that include that dll are:
```
      <dependentAssembly>
        <assemblyIdentity name="System.Interactive.Async" publicKeyToken="94bc3704cddfc263" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.2.0.0" newVersion="3.2.0.0" />
      </dependentAssembly>
```
which my file version is 3.2.702 and the product version 3.2.0+ge6549cefd7
 
I have check all the nuget version none the of version contain the version 3.0.3000.0 of the dll of the System.Interactive.Async
