### ISSUE TITLE
Self Referencing Entity (with join table) cannot determine navigation properties - models and fluent api are generated with scaffolding

### ISSUE THREAD

**Issue by S1r-Lanzelot** [dotnet/efcore#13644]
Describe what is not working as expected:

I have read a few postings about how to set up a self referencing m:m table in EF Core 2.1. I used the reverse-engineering scaffolding to generate the context (fluent-api) and models. The auto generated models and fluentapi setup looks perfect (as far as I can tell) except that I still get:

> Unable to determine the relationship represented by navigation property 'CustomGroups.CustomGroupsToCustomGroupsCustomGroup' of type 'ICollection<CustomGroupsToCustomGroups>'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
> 
> 
>    at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyMappingValidationConvention.Apply(InternalModelBuilder modelBuilder)
>    at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
>    at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
>    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
>    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
>    at System.Lazy`1.CreateValue()
>    at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
>    at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
>    at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
>    at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
>    at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
>    at Microsoft.EntityFrameworkCore.DbContext.get_Model()
>    at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
>    at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
>    at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
>    at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
>    at ConsoleTesterApp.Program.Main(String[] args) in {HOME}\source\repos\ConsoleTesterApp\Program.cs:line 34
> 

### Steps to reproduce
Models:
```
public partial class CustomGroups
    {
        public CustomGroups()
        {
            CustomGroupsToCustomGroupsCustomGroup = new HashSet<CustomGroupsToCustomGroups>();
            CustomGroupsToCustomGroupsReferencedGroup = new HashSet<CustomGroupsToCustomGroups>();
        }

        public int Id { get; set; }

        public ICollection<CustomGroupsToCustomGroups> CustomGroupsToCustomGroupsCustomGroup { get; set; }
        public ICollection<CustomGroupsToCustomGroups> CustomGroupsToCustomGroupsReferencedGroup { get; set; }
    }

    public partial class CustomGroupsToCustomGroups
    {
        public int CustomGroupId { get; set; }
        public int ReferencedGroupId { get; set; }

        public CustomGroups CustomGroup { get; set; }
        public CustomGroups ReferencedGroup { get; set; }
    }
```

FluentApi:
```
 modelBuilder.Entity<CustomGroups>(entity =>
            {
            });

            modelBuilder.Entity<CustomGroupsToCustomGroups>(entity =>
            {
                entity.HasKey(e => new { e.CustomGroupId, e.ReferencedGroupId });

                entity.HasOne(d => d.CustomGroup)
                    .WithMany(p => p.CustomGroupsToCustomGroupsCustomGroup)
                    .HasForeignKey(d => d.CustomGroupId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_CustomGroupsToCustomGroups_CustomGroups");

                entity.HasOne(d => d.ReferencedGroup)
                    .WithMany(p => p.CustomGroupsToCustomGroupsReferencedGroup)
                    .HasForeignKey(d => d.ReferencedGroupId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_CustomGroupsToCustomGroups_CustomGroups1");
            });
```

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
I have tried the stable releases as well:
```
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.0-preview2-35157" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.0-preview2-35157" />
```
Operating system: 
IDE: VS 2017 15.8.5

**Comment by S1r-Lanzelot** [comment]
I have repo setup over this, I believe the issue source is something with that. It's my code not yours.
