### ISSUE TITLE
ExpressionEqualityComparer throws NotImplementedException

### ISSUE THREAD

**Issue by austindrenski** [dotnet/efcore#13664]
[`ExpressionEqualityComparer`](https://github.com/aspnet/EntityFrameworkCore/blob/release/2.1/src/EFCore/Query/Internal/ExpressionEqualityComparer.cs#L405) throws a `NotImplementedException` when the compared node is of type `ExpressionType.Default`.

`ExpressionType.Default` nodes are handled in [`ExpressionEqualityComparer.GetHashCode`](https://github.com/aspnet/EntityFrameworkCore/blob/release/2.1/src/EFCore/Query/Internal/ExpressionEqualityComparer.cs#L263) but not in `ExpressionEqualityComparer.Equals`. 

Is this an oversight? Or is there a reason not to handle equality comparison for `DefaultExpression`?

## Additional info

For some background, this exception is thrown by an app that uses a value-tracing expression visitor to rewrite expression trees in order to remove non-integer constants from grouping operations prior to EF Core translation so that we can avoid PostgreSQL errors like: `non-integer constant in GROUP BY`.

This makes putting together a repro a bit challenging, since the exception is triggered by the `CompiledQueryCacheKeyGenerator` comparing one dynamically-rewritten tree with another.

I don't think that a repro would be of much help here, since it seems to be just a missing `case` statement, but I can put something together if requested.

```
System.NotImplementedException: The method or operation is not implemented.
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression a, Expression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareExpressionList(IReadOnlyList`1 a, IReadOnlyList`1 b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareMethodCall(MethodCallExpression a, MethodCallExpression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression a, Expression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareLambda(LambdaExpression a, LambdaExpression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression a, Expression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareExpressionList(IReadOnlyList`1 a, IReadOnlyList`1 b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareMethodCall(MethodCallExpression a, MethodCallExpression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression a, Expression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareLambda(LambdaExpression a, LambdaExpression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression a, Expression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareUnary(UnaryExpression a, UnaryExpression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression a, Expression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareExpressionList(IReadOnlyList`1 a, IReadOnlyList`1 b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareMethodCall(MethodCallExpression a, MethodCallExpression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression a, Expression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareExpressionList(IReadOnlyList`1 a, IReadOnlyList`1 b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareMethodCall(MethodCallExpression a, MethodCallExpression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression a, Expression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareExpressionList(IReadOnlyList`1 a, IReadOnlyList`1 b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareMethodCall(MethodCallExpression a, MethodCallExpression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression a, Expression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareExpressionList(IReadOnlyList`1 a, IReadOnlyList`1 b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareMethodCall(MethodCallExpression a, MethodCallExpression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression a, Expression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareExpressionList(IReadOnlyList`1 a, IReadOnlyList`1 b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareMethodCall(MethodCallExpression a, MethodCallExpression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression a, Expression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareExpressionList(IReadOnlyList`1 a, IReadOnlyList`1 b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareMethodCall(MethodCallExpression a, MethodCallExpression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression a, Expression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareExpressionList(IReadOnlyList`1 a, IReadOnlyList`1 b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareMethodCall(MethodCallExpression a, MethodCallExpression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression a, Expression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareExpressionList(IReadOnlyList`1 a, IReadOnlyList`1 b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareMethodCall(MethodCallExpression a, MethodCallExpression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression a, Expression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareExpressionList(IReadOnlyList`1 a, IReadOnlyList`1 b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareMethodCall(MethodCallExpression a, MethodCallExpression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression a, Expression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareExpressionList(IReadOnlyList`1 a, IReadOnlyList`1 b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.CompareMethodCall(MethodCallExpression a, MethodCallExpression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression a, Expression b)
  at at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.Equals(Expression x, Expression y)
  at at Microsoft.EntityFrameworkCore.Query.CompiledQueryCacheKeyGenerator.CompiledQueryCacheKey.Equals(Object obj)
  at at Microsoft.EntityFrameworkCore.Query.RelationalCompiledQueryCacheKeyGenerator.RelationalCompiledQueryCacheKey.Equals(RelationalCompiledQueryCacheKey other)
  at at Microsoft.EntityFrameworkCore.Query.RelationalCompiledQueryCacheKeyGenerator.RelationalCompiledQueryCacheKey.Equals(Object obj)
  at Npgsql.EntityFrameworkCore.PostgreSQL.Query.Internal.NpgsqlCompiledQueryCacheKeyGenerator.NpgsqlCompiledQueryCacheKey.Equals(NpgsqlCompiledQueryCacheKey other) in C:\projects\npgsql-entityframeworkcore-postgresql\src\EFCore.PG\Query\Internal\NpgsqlCompiledQueryCacheKeyGenerator.cs:63
  at Npgsql.EntityFrameworkCore.PostgreSQL.Query.Internal.NpgsqlCompiledQueryCacheKeyGenerator.NpgsqlCompiledQueryCacheKey.Equals(Object obj) in C:\projects\npgsql-entityframeworkcore-postgresql\src\EFCore.PG\Query\Internal\NpgsqlCompiledQueryCacheKeyGenerator.cs:58
  at at System.Collections.Generic.ObjectEqualityComparer`1.Equals(T x, T y)
  at at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValueInternal(TKey key, Int32 hashcode, TValue& value)
  at at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
  at at Microsoft.Extensions.Caching.Memory.MemoryCache.TryGetValue(Object key, Object& result)
  at at Microsoft.Extensions.Caching.Memory.CacheExtensions.TryGetValue[TItem](IMemoryCache cache, Object key, TItem& value)
  at at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
  at at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
  at at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
  at at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
  at at Remotion.Linq.QueryableBase`1.System.Collections.IEnumerable.GetEnumerator()
```

## Further technical details
EF Core version: 2.1.4
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL
Operating system: Windows 10

**Comment by austindrenski** [comment]
Whoops, clearly a duplicate of #12771. Closing.
