### ISSUE TITLE
Select Many throws an exception when creating an object with a value from both levels

### ISSUE THREAD

**Issue by ze1tgeist** [dotnet/efcore#13680]
Describe what is not working as expected.

When running a linq expression in EFCore, similar to the following
```
context.Parents
    .SelectMany(parent => parent.Children.Select(child => new
    {
        ParentName = parent.Name,
        ChildName = child.Name
    }))
```
An ArgumentException is thrown
```
Exception message: "must be reducible node"
Stack trace:
   at System.Linq.Expressions.Expression.ReduceAndCheck()
   at System.Linq.Expressions.Expression.ReduceExtensions()
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExtensionExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMemberExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteNewExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(Expression expression, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression`1 lambda)
   at System.Linq.Expressions.Expression`1.Accept(StackSpiller spiller)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteLambdaExpression(Expression expr)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(Expression expression, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression`1 lambda)
   at System.Linq.Expressions.Expression`1.Accept(StackSpiller spiller)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteLambdaExpression(Expression expr)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(Expression expression, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression`1 lambda)
   at System.Linq.Expressions.Expression`1.Accept(StackSpiller spiller)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at System.Linq.Expressions.Expression`1.Compile(Boolean preferInterpretation)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateExecutorLambda[TResults]()
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ReproForSelectManyEfBug.Program.Main(String[] args) in D:\Repos\ReproForSelectManyEfBug\ReproForSelectManyEfBug\Program.cs:line 20
```

### Steps to reproduce
- Clone the following solution:  https://github.com/ze1tgeist/ReproForSelectManyEfBug
- Open in Visual Studio 2017
- Ensure that SQL Server (tested on 2016) is available locally.  I have hardcoded connection string in the DbContext for the sake of the repro, to be use localhost.
- In the package manager console, type: `.\BuildDatabase.bat`
- Build and run the project. 
- Observe the error.
- Note that the master branch uses EFCore 2.2.  This errors.
- There are three branches for EF_2_0, EF_2_1 and EF_2_2.  The error occurs in EFCore 2.1 and EFCore 2.2. It **does not** occur in EFCore 2.0

### Further technical details
EF Core version: Error tested to occur in 2.2.0-preview3-35497 and 2.1.4. Error tested to **NOT** occur in 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows Server 2012 R2
IDE: Visual Studio 2017 15.8.2

**Comment by maumar** [comment]
query plan:
```
(QueryContext queryContext) => IEnumerable<<>f__AnonymousType0<string, string>> _InterceptExceptions(
|__ source: IEnumerable<<>f__AnonymousType0<string, string>> _Select(
|   |__ source: IEnumerable<TransparentIdentifier<ValueBuffer, <>f__AnonymousType0<string, string>>> _SelectMany(
|   |   |__ source: IEnumerable<ValueBuffer> _ShapedQuery(
|   |   |   |__ queryContext: queryContext, 
|   |   |   |__ shaperCommandContext: SelectExpression: 
|   |   |   |       SELECT [parent].[Id], [parent].[Name]
|   |   |   |       FROM [Parents] AS [parent], 
|   |   |   |__ shaper: ValueBufferShaper), 
|   |   |__ collectionSelector: (ValueBuffer parent) => IEnumerable<<>f__AnonymousType0<string, string>> _Select(
|   |   |   |__ source: IEnumerable<ValueBuffer> _ShapedQuery(
|   |   |   |   |__ queryContext: queryContext, 
|   |   |   |   |__ shaperCommandContext: SelectExpression: 
|   |   |   |   |       SELECT [t].[ParentName], [t].[ChildName]
|   |   |   |   |       FROM (
|   |   |   |   |           SELECT [parent].[Name] AS [ParentName], [child].[Name] AS [ChildName]
|   |   |   |   |           FROM [Children] AS [child]
|   |   |   |   |           WHERE [parent].[Id] = [child].[ParentId]
|   |   |   |   |       ) AS [t], 
|   |   |   |   |__ shaper: ValueBufferShaper), 
|   |   |   |__ selector: (ValueBuffer child) => new { 
|   |   |            ---> [parent{-1}] <--- .Name, 
|   |   |           string TryReadValue(child, 1, Child.Name)
|   |   |        }), 
|   |   |__ resultSelector: (ValueBuffer parent | <>f__AnonymousType0<string, string> <generated>_0) => TransparentIdentifier<ValueBuffer, <>f__AnonymousType0<string, string>> CreateTransparentIdentifier(
|   |       |__ outer: parent, 
|   |       |__ inner: <generated>_0)), 
|   |__ selector: (TransparentIdentifier<ValueBuffer, <>f__AnonymousType0<string, string>> t0) => t0.Inner), 
|__ contextType: Repro13680.MyContext, 
|__ logger: DiagnosticsLogger<Query>, 
|__ queryContext: queryContext)
```

**Comment by benm-eras** [comment]
I also ran into this issue, and have also created a [repro](https://github.com/benm-eras/ReducibleNodeDemo/tree/master/ReducibleNodeDemo)! 

I also posted it to [StackOverflow](https://stackoverflow.com/questions/52891920/how-do-you-query-a-many-to-many-relationship-using-entity-framework-core-2-1) and got pointed at a [work around](https://stackoverflow.com/a/52912946/723645) that takes minimal changes. I do still feel that this is an issue that needs fixing, especially as it wasn't a problem in previous versions of the entity framework (prior to core).

**Comment by smitpatel** [comment]
Generated SQL for repro in OP in 3.1
```SQL
SELECT [t].[Name] AS [ParentName], [t].[Name0] AS [ChildName]
FROM [Parents] AS [p]
CROSS APPLY (
    SELECT [p].[Name], [c].[Name] AS [Name0], [c].[Id], [c].[ParentId]
    FROM [Children] AS [c]
    WHERE [p].[Id] = [c].[ParentId]
) AS [t]
```

**Comment by smitpatel** [comment]
Generated SQL for 2nd case
```SQL
SELECT [t].[Id], [t].[Value]
FROM [Foos] AS [f]
CROSS APPLY (
    SELECT [f].[Id], [b].[Value], [f0].[FooId], [f0].[BarId], [b].[Id] AS [Id0]
    FROM [FooBars] AS [f0]
    INNER JOIN [Bars] AS [b] ON [f0].[BarId] = [b].[Id]
    WHERE [f].[Id] = [f0].[FooId]
) AS [t]
```
