### ISSUE TITLE
Select with total items count: unexpected behavior

### ISSUE THREAD

**Issue by BladeWise** [dotnet/efcore#13739]
I am trying to execute a query that retrieves a subset (page) of filtered items and  the total number of the items produced by the original query, while using EFCore against SQL Server 2017.

Ideally, I would like to produce a query like
```sql
SELECT COUNT(*) OVER () TotalCount,
             x.*
FROM dbo.Entities x
ORDER BY x.Id DESC OFFSET 20 ROWS FETCH NEXT 5 ROWS ONLY
```
or
```sql
SELECT (SELECT COUNT(*) FROM dbo.Entities x0) TotalCount,
             x.*
FROM dbo.Entities x
ORDER BY x.Id DESC OFFSET 20 ROWS FETCH NEXT 5 ROWS ONLY
```

Using previous a previous (pre-RTM) version of EFCore (see this [StackOverflow question](https://stackoverflow.com/questions/36478179/ef-core-paging-select-total-count-in-same-query)) it was possible using the following 'trick'
```c# 
 var query = context.Set<Entity>();
 var page = query.OrderBy(e => e.Id)
                 .Select(e => e)
                 .Skip(20).Take(5)
                 .GroupBy(e => new { Total = query.Count() })
                 .FirstOrDefault();

 if (page != null)
 {
      int total = page.Key.Total;
      List<Entity> events = page.ToList();
 }
```
but the same code with the current EFCore package produces the following SQL Profiler trace
```sql
SELECT [t].[Id], [t].[Name]
FROM (
    SELECT [e].[Id], [e].[Name]
    FROM [tests].[Entities] AS [e]
    ORDER BY [e].[Id]
    OFFSET 20 ROWS FETCH NEXT 5 ROWS ONLY
) AS [t]
ORDER BY (
    SELECT COUNT(*)
    FROM [tests].[Entities] AS [p0]
)

SELECT COUNT(*)
FROM [tests].[Entities] AS [p1]
SELECT COUNT(*)
FROM [tests].[Entities] AS [p1]
SELECT COUNT(*)
FROM [tests].[Entities] AS [p1]
SELECT COUNT(*)
FROM [tests].[Entities] AS [p1]
SELECT COUNT(*)
FROM [tests].[Entities] AS [p1]
```
Notice how the `SELECT COUNT(*) ...` is used for sorting the items in the page and is repeated for each item.

Considering that `GroupBy` has always been problematic, I tried with another approach:
```c# 
var query = dbContext.Set<Entity>();
var pagedQueryable = query.OrderBy(e => e.Id)
                          .Skip(20).Take(5)
                          .Select(e => new
                                       {
                                               Total = query.Count(),
                                               Item = e
                                       });

var page = pagedQueryable.ToList();

var total = page.First()
                .Total;
var items = page.Select(x => x.Item)
                .ToList();
```
obtaining the following result:
```sql
SELECT [e].[Id], [e].[Name]
FROM [tests].[Entities] AS [e]
ORDER BY [e].[Id]
OFFSET 20 ROWS FETCH NEXT 5 ROWS ONLY

SELECT COUNT(*)
FROM [tests].[Entities] AS [p0]
SELECT COUNT(*)
FROM [tests].[Entities] AS [p0]
SELECT COUNT(*)
FROM [tests].[Entities] AS [p0]
SELECT COUNT(*)
FROM [tests].[Entities] AS [p0]
SELECT COUNT(*)
FROM [tests].[Entities] AS [p0]
```
As far as I know, this approach should work properly... at least it worked in May 2018 as per [this other StackOverflow answer](https://stackoverflow.com/questions/50448167/how-i-can-get-record-count-matching-predicate-using-entity-framework/50449701#50449701).

Testing the same scenario with older packages, I noticed that version 1.0.6 produced the SQL I was expecting
```sql
SELECT [e].[Id], [e].[Name], (
    SELECT COUNT(*)
    FROM [tests].[Entities] AS [e1]
)
FROM [tests].[Entities] AS [e]
ORDER BY [e].[Id]
OFFSET 20 ROWS FETCH NEXT 5 ROWS ONLY

SELECT COUNT(*)
FROM [tests].[Entities] AS [e2]
SELECT COUNT(*)
FROM [tests].[Entities] AS [e2]
SELECT COUNT(*)
FROM [tests].[Entities] AS [e2]
SELECT COUNT(*)
FROM [tests].[Entities] AS [e2]
SELECT COUNT(*)
FROM [tests].[Entities] AS [e2]
```
but since 1.1.0 the sub-select is not present anymore.
As far as I can tell, every version produces as many `SELECT COUNT(*) ...` calls as the number of items in the page, which was not expected. 

Is calling `queryable.Count()` not supported by design anymore, is it a bug or there is a different way to specify what I want?

### Further technical details
EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.7

**Comment by divega** [comment]
A couple of additional issues I found while trying the repro:

If you write the query like this:

``` csharp
var query = db.Set<Entity>();
var pagedQueryable = query.OrderBy(e => e.Id)
                            .Skip(1).Take(5)
                            .Select(e => new
                            {
                                Total = query.ToList().Count(),
                                Item = e
                            });
                    
var page = pagedQueryable.ToList();
```
Exception:
``` 
System.NotSupportedException
  HResult=0x80131515
  Message=Could not parse expression 'value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Demos.Theme]).ToList()': This overload of the method 'System.Linq.Enumerable.ToList' is currently not supported.
  Source=Remotion.Linq
  StackTrace:
   at Remotion.Linq.Parsing.Structure.MethodCallExpressionParser.GetNodeType(MethodCallExpression expressionToParse)
   at Remotion.Linq.Parsing.Structure.MethodCallExpressionParser.Parse(String associatedIdentifier, IExpressionNode source, IEnumerable`1 arguments, MethodCallExpression expressionToParse)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)
   at Remotion.Linq.Parsing.Structure.QueryParser.GetParsedQuery(Expression expressionTreeRoot)
   at Remotion.Linq.Parsing.ExpressionVisitors.SubQueryFindingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitAndConvert[T](ReadOnlyCollection`1 nodes, String callerName)
   at Remotion.Linq.Parsing.RelinqExpressionVisitor.VisitNew(NewExpression expression)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Enumerable.SelectListPartitionIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Remotion.Linq.Parsing.Structure.MethodCallExpressionParser.Parse(String associatedIdentifier, IExpressionNode source, IEnumerable`1 arguments, MethodCallExpression expressionToParse)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)
   at Remotion.Linq.Parsing.Structure.QueryParser.GetParsedQuery(Expression expressionTreeRoot)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Demos.Program.Main() in C:\Users\divega\source\repos\EFDemos\data-seeding\Program.cs:line 27

```

If you write a query like this:
``` csharp

```
var query = db.Set<Entity>();
var pagedQueryable = query.OrderBy(e => e.Id)
                            .Skip(1).Take(5)
                            .Select(e => new
                            {
                                Total = query.ToList(), // also repros without the ToList()
                                Item = e
                            });
                    
var page = pagedQueryable.ToList();
```
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.FindEntityType(IQuerySource querySource)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitEntityQueryable(Type elementType)
   at System.Linq.Expressions.ConstantExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitAndConvert[T](ReadOnlyCollection`1 nodes, String callerName)
   at Remotion.Linq.Parsing.RelinqExpressionVisitor.VisitNew(NewExpression expression)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Demos.Program.Main() in C:\Users\divega\source\repos\EFDemos\data-seeding\Program.cs:line 27

```

**Comment by divega** [comment]
@BladeWise thanks for reporting this. 

> but since 1.1.0 the sub-select is not present anymore.

Do you mean that you get the query you want with only 1.0.x? or 1.1.x too?

We will investigate if this is something we can improve. I couldn't find any obvious workaround. Someone else may think of one, but in the meantime, I would recommend you just issue two separate queries to get the total count and the pages.

**Comment by BladeWise** [comment]
Only with 1.0.x, since 1.1.x until latest (at least using the latest minor versions) the SQL produced is the same.

I suppose QueryTypes and FromSql are the only reliable workaroundat the moment... ☹️

**Comment by sdanyliv** [comment]
Sorry EF guys if it is annoying. 
@BladeWise, it is Window Functions which are currently unsupported by EF.
If you need such queries we have implemented it in our extension for EF.
Just install our package 
https://www.nuget.org/packages/linq2db.EntityFrameworkCore
And then rewrite your query in the following way:
```cs
var page = query
    .Select(e => new { Total = Sql.Ext.Count().Over().ToValue(), Item = e })
    .Skip(20)
    .Take(5)
    .ToLinqToDB()
    .ToList();
```
Note, that eager loading (Includes) will not work in this case.

**Comment by ajcvickers** [comment]
@smitpatel to find dupe for original query with Select.

**Comment by ajcvickers** [comment]
@divega to file issues for the other two cases.

**Comment by BladeWise** [comment]
@sdanyliv Thanks for pointing out your extension, but in my case a sub-query outperforms `COUNT(*) OVER()` by a huge margin, so I am a bit more interested in th sub-query approach.

**Comment by divega** [comment]
> I suppose QueryTypes and FromSql are the only reliable workaround at the moment...

@BladeWise I think just issuing two separate queries for the total count and the page is a simpler workaround, but I may be missing something.

**Comment by BladeWise** [comment]
@divega It is simpler, but as I said it is not equivalent in terms of reliability and consistency, regarding the fact that [data could change between queries](https://stackoverflow.com/questions/4034976/difference-between-read-commit-and-repeatable-read/4036063#4036063).

**Comment by sdanyliv** [comment]
@BladeWise, sorry, i have lost of discussion point. What do you mean subquery approach? SQl is always SQL and it is the best way to talk with SQL servers.
You have mentioned best solution for your problem (in SQL) and i have proposed this approach.

Usually as an Architect, i will not approve such queries (not this one, which can use statistics even when extra data has been loaded), but there are a lot of cases when people query Count for every complex queries, because of generic “useful” paginators. We should pray for server cores and memory.

**Comment by BladeWise** [comment]
@sdanyliv I proposed two SQL solutions, one with `COUNT(*) OVER()`, the other using a sub-query used to compute the count (which is optimized by SQL Server to be computed once and be replicated over the rows). The latter was my main focus.
Generic paginators, as you define them, are reusable code that can be easily unit-tested and provide a good starting point to implement pagination logic. Of course, when deling with a database data size/indices/statistics matter,  so there are cases where ad-hoc optimization is needed. Nevertheless, the typical usage involves ~50/100 rows, and in such a case I doubt that having one more int/long field per row overcomes the benefits. Again, provided that they are not abused.

**Comment by sdanyliv** [comment]
@BladeWise, one point, even you have to get only 100 rows, SQL server has to complete query fully, perform all joins, apply predicate to count rows, which is a performance bottleneck if there are millions of records. Enterprise dictates it’s own rules, but usually it is better to get 101 rows and tell to the user that there are some records left and needs scrolling. This rule also applies to pagination - to skip 1000 rows, server has to do that by skipping them, and you may encourage performance lost after each next page. Thanks to modern SQL optimizators, they are trying to do it fast.
