### ISSUE TITLE
Random DI Exceptions for DbContextDependencies

### ISSUE THREAD

**Issue by WolfspiritM** [dotnet/efcore#13763]
Hi,

We're currently having troubles with random exceptions in DI for EF Core for our services.

We have an ASP.NET Service that gets TestDbContext via constructor DI.

It processes many requests per day but sometimes it randomly causes exceptions one or two times per day. We weren't able to debug the exceptions as we have no idea how to trigger them.
That's also why I can't provide a reproducable example. The code below works without issues but every few days after processing many messages and calls it randomly throws an exception.

Here is the exception we get:

```
Microsoft.Extensions.DependencyInjection: Object reference not set to an instance of an object.
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(IServiceCallSite callSite, ServiceProviderEngineScope scope)
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Any[TSource](IQueryable`1 source, Expression`1 predicate)
   at MyApp.HelperFunctions.CheckIfIdExists(String test, TestDbContext context)
   at MyApp.Controllers.TestController.Get(string id)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()   
```

Here is the code of that service:

``` c#
# <Startup.cs>
  services.AddDbContext<TestDbContext>(options =>
      options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"))
  );
# </Startup.cs>


  
  public class HelperFunctions
  {
    public static bool CheckIfIdExists(String test, TestDbContext context)
    {
        if (string.IsNullOrEmpty(test))
            return false;


        return context.TestData.Any(m => m.Id == test);
    }
  }
  
  public class TestController : Controller
  {
      private readonly TestDbContext context;


      public TestController(TestDbContext context)
      {
          this.context = context;        
      }
      
      
      [HttpGet("test/{*id}")]
      public async Task<IActionResult> Get(string id)
      {

          if (!HelperFunctions.CheckIfIdExists(id, context))
              return BadRequest("Id could not be found!");
          ...
      }        
  }  
  
```
 

We also have a console Service that handles many messages per day aswell (> 500.000) but it also ends up with a similar error every few days.
The DbContext gets injected via DI aswell and for each Process call we generate a new scope.

```
System.EntryPointNotFoundException: Entry point was not found.
at Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite.get_Kind()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.AsNoTracking[TEntity](IQueryable`1 source)
   at MyApp.Handler.Process(EventMessage message) in ...
```

``` c#
    public async Task<IEnumerable<EdiConnection>> Process(EventMessage message) {
     ...
            var connections = await context.Data.AsNoTracking()
                .Where(c => c.Active && (c.Id1 == message.Id || c.Id2 == message.Id))
                .ToListAsync();    
    
     ...
    }
```

It looks to me that at random times the DbContextDependencies can't be resolved cause of some kind of race condition. We thought, for the ASP.NET Service, maybe the user closed the connection and everything gets disposed, which might cause this. But for the Console Service that can't be the case.
The following request works again. We thought about adding Context pooling but we're not sure if that would actually help and would prefer to know the root cause of the issue.

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Linux Ubuntu / Docker Containers
IDE: Visual Studio 2017 / VSCode

**Comment by ajcvickers** [comment]
@WolfspiritM I moved the issue to https://github.com/aspnet/Extensions/issues/433 because from the description and traces it seems like something is failing in the D.I. code.
