### ISSUE TITLE
Query: GroupBy with nested navigation properties is executed locally

### ISSUE THREAD

**Issue by KLuuKer** [dotnet/efcore#13761]
I am attempting to group on a nested navigation property Zar.Bar.Foo results in the query being executed locally.
Worked just fine in ye olde EF6....

**Stacktrace**
```
Exception message: System.InvalidOperationException: 'Error generated for warning 'Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning: The LINQ expression 'GroupBy([z.Bar.Foo], [z])' could not be translated and will be evaluated locally.'. This exception can be suppressed or logged by passing event ID 'RelationalEventId.QueryClientEvaluationWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.'
Stack trace:    at Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`1.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, WarningBehavior warningBehavior, TParam arg, Exception exception)
   at Microsoft.EntityFrameworkCore.Internal.RelationalLoggerExtensions.QueryClientEvaluationWarning(IDiagnosticsLogger`1 diagnostics, QueryModel queryModel, Object queryModelElement)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.WarnClientEval(QueryModel queryModel, Object queryModelElement)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index)
   at Remotion.Linq.Clauses.ResultOperatorBase.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitResultOperators(ObservableCollection`1 resultOperators, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSubQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.LiftSubQuery(IQuerySource querySource, SubQueryExpression subQueryExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.CompileMainFromClauseExpression(MainFromClause mainFromClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitMainFromClause(MainFromClause fromClause, QueryModel queryModel)
   at Remotion.Linq.Clauses.MainFromClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at efcore_test_app.Program.Main(String[] args)
```

### Steps to reproduce
**Model**
```c#
class Zar {
// id etc....
public int BarId { get; set; }
public virtual Bar { get; set; }
}
class Bar {
// id etc....
public int FooId { get; set; }
public virtual Foo { get; set; }
}
class Foo {
public int Id { get; set; }
public string Name { get; set; }
}
```
**Query**
```c#
// grouping by other simple string properties on Bar does work but I need it on Foo :(
var results = ctx.Zars.GroupBy(z => z.Bar.Foo).Select(g => new 
{
 Something = g.Key.Name, // doesn't matter what we select here

 // would be very nice if I could then also do some Sum()'s and such
 // and maybe selecting some properties from Zar
}).ToList();
```

### Further technical details
EF Core version: 2.2.0-preview3-35497
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.0 Preview 4

**Comment by KLuuKer** [comment]
EF core is very very nice, in perf and query readability but damn allot of stuff isn't supported yet 😢 
I know I know i should just wait for v3.0...….

**Comment by maumar** [comment]
@KLuuKer you can do something like this:

```cs
var results = ctx.Zars.GroupBy(z => z.Bar.Foo.Id).Select(g => new
{
    Aggregate = g.Sum(e => e.BarId)
}).ToList();
```

SQL:

```sql
SELECT SUM([z].[BarId]) AS [Aggregate]
FROM [Zars] AS [z]
INNER JOIN [Bars] AS [z.Bar] ON [z].[BarId] = [z.Bar].[Id]
INNER JOIN [Foos] AS [z.Bar.Foo] ON [z.Bar].[FooId] = [z.Bar.Foo].[Id]
GROUP BY [z.Bar.Foo].[Id]
```

If you need to access property on the key, you can do:

```cs
var results = ctx.Zars.GroupBy(z => new { z.Bar.Foo.Id, z.Bar.Foo.Name }).Select(g => new
{
    Something = g.Key.Name,
   Aggregate = g.Sum(e => e.BarId)
}).ToList();
```

SQL:
```sql
SELECT [z.Bar.Foo].[Name] AS [Something], SUM([z].[BarId]) AS [Aggregate]
FROM [Zars] AS [z]
INNER JOIN [Bars] AS [z.Bar] ON [z].[BarId] = [z.Bar].[Id]
INNER JOIN [Foos] AS [z.Bar.Foo] ON [z.Bar].[FooId] = [z.Bar.Foo].[Id]
GROUP BY [z.Bar.Foo].[Id], [z.Bar.Foo].[Name]
```

**Comment by KLuuKer** [comment]
@maumar aha yes that works! but.... I won't be able to select things from Zars inside the select

```c#
var results = ctx.Zars.GroupBy(z => new { z.Bar.Foo.Id, z.Bar.Foo.Name }).Select(g => new
{
    Something = g.Key.Name,

    // this next line makes it crash again :(
    WhatAboutMe = g.Select(z => new { z.Id, z.Name }).ToList(),
}).ToList();
```

**Comment by paulovila** [comment]
Hi @ajcvickers, if there is a solution for GroupBy this I wouldn't mind to test it, let me know if there is a branch with this fix

**Comment by ajcvickers** [comment]
@paulovila This issue is in the Backlog milestone. This means that it is not going to happen for the 3.0 release. We will re-assess the backlog following the 3.0 release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by paulovila** [comment]
Thanks @ajcvickers looking forward for v 3+. Keep up the good work.

**Comment by maumar** [comment]
work tracked by https://github.com/aspnet/EntityFrameworkCore/issues/15938
