### ISSUE TITLE
The command Add-Migration with a project using Platform .net core (sdk 2.2.0-preview3-35497) x86 give an error

### ISSUE THREAD

**Issue by jobou363** [dotnet/efcore#13780]
When I call Add-Migration with a .net core project (sdk 2.2.0-preview3-35497) using Platform .net x86 I receive an error but when it's platform any cpu everythings works fine. 

```
Exception message:
Stack trace:
 Add-Migration
cmdlet Add-Migration at command pipeline position 1
Supply values for the following parameters:
Name: Test3
Could not load assembly 'CFDG_Core2.2'. Ensure it is referenced by the startup project 'CFDG_Core2.2'.
PM> Add-Migration -Verbose
cmdlet Add-Migration at command pipeline position 1
Supply values for the following parameters:
Name: Test3
Using project 'CFDG_Core2.2'.
Using startup project 'CFDG_Core2.2'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile D:\Freelancer\CFDGCore\CFDG_Core2.2\bin\Debug\netcoreapp2.2\CFDG_Core2.2.deps.json --additionalprobingpath C:\Users\Jonatan\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig D:\Freelancer\CFDGCore\CFDG_Core2.2\bin\Debug\netcoreapp2.2\CFDG_Core2.2.runtimeconfig.json "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.entityframeworkcore.tools\2.2.0-preview3-35497\tools\netcoreapp2.0\any\ef.dll" migrations add Test3 --json --verbose --no-color --prefix-output --assembly D:\Freelancer\CFDGCore\CFDG_Core2.2\bin\Debug\netcoreapp2.2\CFDG_Core2.2.dll --startup-assembly D:\Freelancer\CFDGCore\CFDG_Core2.2\bin\Debug\netcoreapp2.2\CFDG_Core2.2.dll --project-dir D:\Freelancer\CFDGCore\CFDG_Core2.2\ --language C# --working-dir D:\Freelancer\CFDGCore --root-namespace CFDG_Core2._2
Using assembly 'CFDG_Core2.2'.
Using startup assembly 'CFDG_Core2.2'.
Using application base 'D:\Freelancer\CFDGCore\CFDG_Core2.2\bin\Debug\netcoreapp2.2'.
Using working directory 'D:\Freelancer\CFDGCore\CFDG_Core2.2'.
Using root namespace 'CFDG_Core2._2'.
Using project directory 'D:\Freelancer\CFDGCore\CFDG_Core2.2\'.
Microsoft.EntityFrameworkCore.Design.OperationException: Could not load assembly 'CFDG_Core2.2'. Ensure it is referenced by the startup project 'CFDG_Core2.2'. ---> System.BadImageFormatException: Could not load file or assembly 'CFDG_Core2.2, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.<>c__DisplayClass4_0.<.ctor>b__1()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.<>c__DisplayClass4_0.<.ctor>b__1()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.<>c__DisplayClass4_0.<.ctor>b__4()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Could not load assembly 'CFDG_Core2.2'. Ensure it is referenced by the startup project 'CFDG_Core2.2'.
```

### Steps to reproduce
1) In Visual Studio 15.9 Preview 3 with .net core sdk 2.2.0-preview3-35497.
2) You can use the solution of the WebApplication1.zip file and skip to step 5 or create a new .net core 2.2 project (2.2.0-preview3-35497) and create a new entity framework context like the one in this tutorial : 
https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/new-db?tabs=visual-studio

[WebApplication1.zip](https://github.com/aspnet/EntityFrameworkCore/files/2520206/WebApplication1.zip)

3) do those changes
```c#
//Add a new class author to the context  :
public class Author
{
    public int AuthorId { get; set; }
    public string Name { get; set; }    
}

//Add the DBSet in the context : 
public DbSet<Author> Authors { get; set; }
```
4) Change the project propertie to build in x86 platform
5) Open nuget manager console and run the command and you will get the error

Add-Migration -Verbose 
name: AddNewTableAuthor

### Further technical details
EF Core version: 2.2.0-preview3-35497
Microsoft.EntityFrameworkCore.Tools: 2.2.0-preview3-35497
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Visual Studio 2017 15.9 Preview 3

**Comment by bricelam** [comment]
> An attempt was made to load a program with an incorrect format.

Are you trying to load an x64 assembly on a 32-bit version of Windows?

**Comment by bricelam** [comment]
Change your active platform to Any CPU or x86:
![image](https://user-images.githubusercontent.com/1226749/47589062-f7880b80-d91c-11e8-9463-e8e0039bb321.png)
