### ISSUE TITLE
InvalidOperationException during sql migration generation when combining owned and base-types

### ISSUE THREAD

**Issue by nphmuller** [dotnet/efcore#13944]
I believe the scenario I'm doing is not supported, but the exception should at least describe this. Currently it's a generic `System.InvalidOperationException: Sequence contains more than one matching element`.

Repro:
``` c#
    public class MyContext : DbContext
    {
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Friend>().OwnsOne(e => e.Address);
            modelBuilder.Entity<LessThanFriend>().OwnsOne(e => e.Address);
            modelBuilder.Entity<FullAddress>().HasBaseType<CityAddress>();
        }
    }

    public class Friend
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public FullAddress Address { get; set; }
    }

    public class LessThanFriend
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public CityAddress Address { get; set; }
    }

    public class CityAddress
    {
        public string Cap { get; set; }
        public string City { get; set; }
    }

    public class FullAddress : CityAddress
    {
        public string Street { get; set; }
    }
```
And run `dotnet ef migrations add Initial`.

Exception details:
```
Exception message: System.InvalidOperationException: Sequence contains more than one matching element
Stack trace:
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ConstraintNamer.GetDefaultName(IProperty property)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.SqlServer.Metadata.Conventions.Internal.SqlServerIndexConvention.CreateIndexFilter(IIndex index)
   at Microsoft.EntityFrameworkCore.SqlServer.Metadata.Conventions.Internal.SqlServerIndexConvention.SetIndexFilter(InternalIndexBuilder indexBuilder, Boolean columnNameChanged)
   at Microsoft.EntityFrameworkCore.SqlServer.Metadata.Conventions.Internal.SqlServerIndexConvention.Apply(InternalEntityTypeBuilder entityTypeBuilder, EntityType oldBaseType)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnBaseEntityTypeChanged(InternalEntityTypeBuilder entityTypeBuilder, EntityType previousBaseType)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.RunVisitor.VisitOnBaseEntityTypeChanged(OnBaseEntityTypeChangedNode node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.VisitConventionScope(ConventionScope node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Run()
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasBaseType(EntityType baseEntityType, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.HasBaseType(Type entityType)
   at ConsoleApp10.MyContext.OnModelCreating(ModelBuilder modelBuilder) in C:\Users\mulle\source\repos\ConsoleApp10\ConsoleApp10\Program.cs:line 26
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Further technical details
EF Core packages:
``` xml
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.4" />
```
Operating system: Windows 10 1809
IDE: Visual Studio 15.8.9 (but the exception is thrown in the CLI when creating a migration).

**Comment by nphmuller** [comment]
Also duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/9148
