### ISSUE TITLE
Projection Bug In Sql Generation

### ISSUE THREAD

**Issue by hovhanneskarapetyan** [dotnet/efcore#14003]
Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Nullable object must have a value.
Stack trace:
   at lambda_method(Closure , TransparentIdentifier`2 )
   at System.Linq.AsyncEnumerable.WhereSelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.Aggregate_[TSource,TAccumulate,TResult](IAsyncEnumerable`1 source, TAccumulate seed, Func`3 accumulator, Func`2 resultSelector, CancellationToken cancellationToken)
   at XXX.DAL.Repositories.MatchRepository.GetUserMatchesByFilterAsync(UserMatchFilter filter) in C:\Users\hovhannes.karapetyan\Source\Repos\XXX\XXX.DAL\Repositories\MatchRepository.cs:line 63
   at XXX.BLL.MatchBL.GetUserMatchesByFilterAsync(Int64 userId, UserMatchFilter filter) in C:\Users\hovhannes.karapetyan\Source\Repos\XXX\XXX.BLL\MatchBL.cs:line 160
   at XXX.BLL.Facades.MatchFacade.FillUserMatches(Int64 userId, Dictionary`2 partnerMatches) in C:\Users\hovhannes.karapetyan\Source\Repos\XXX\XXX.BLL\Facades\MatchFacade.cs:line 114
   at XXX.BLL.Facades.MatchFacade.GetByFilterAsync(Int64 userId, MatchFilter filter, PartnerMatchFilter partnerMatchFilter) in C:\Users\hovhannes.karapetyan\Source\Repos\XXX\XXX.BLL\Facades\MatchFacade.cs:line 101
   at XXX.API.Controllers.MatchController.GetByFilterAsync(Int64 competitionId, FilterBaseViewModel matchViewModel) in C:\Users\hovhannes.karapetyan\Source\Repos\XXX\XXX.API\Controllers\MatchController.cs:line 50
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at XXX.API.Middlewares.ExceptionHandlerMiddleware.InvokeAsync(HttpContext context) in C:\Users\hovhannes.karapetyan\Source\Repos\XXX\XXX.API\Middlewares\ExceptionHandlerMiddleware.cs:line 27
```
### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
 public class UserMatch:EntityBase
    {
        public long? TraderId { get; set; }
        public long MatchId { get; set; }
        public User Trader { get; set; }
        public Match Match { get; set; }
    }

 public class User : EntityBase
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public UserType Type { get; set; }
        public ICollection<UserMatch> AssignedTo { get; set; }
     }


result = Context.UserMatches.Select(x => new UserMatch()
            {
                TraderId = x.TraderId,
                Trader = new User()
                {
                    Id = x.Trader.Id,
                    FirstName = x.Trader.FirstName,
                },
                Id = x.Id,
                
            });
```
Generated SQL query is 
```sql
SELECT x."MatchId",
       x."TraderId",
       x."TraderId" AS "Id",
       "x.Trader"."FirstName",
       x."Id"       AS "Id0"
FROM   "UserMatches" AS x
       LEFT JOIN "Users" AS "x.Trader"
         ON x."TraderId" = "x.Trader"."Id"
```
problem comes from changing  "x.Trader.Id" to "x.TraderId" and because of it there accures 2 "x.TraderId",and EFCore changes one of them to "Id" (x."TraderId" AS "Id",).
After mapping it to UserMatch object "x.Trader.Id" cannot be found and exception was thrown.

### Further technical details
EF Core version: (found in project.csproj or packages.config)
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.3" />
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.1.2" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.Design" Version="1.1.1" />
Operating system: 
Windows 8.1
IDE: (e.g. Visual Studio 2017 15.4)
Visual Studio 2017 15.4

**Comment by smitpatel** [comment]
Generated SQL in 3.1, it does not throw any exception.
```SQL
      SELECT "u"."TraderId", "u0"."Id", "u0"."FirstName", "u"."Id"
      FROM "UserMatches" AS "u"
      LEFT JOIN "User" AS "u0" ON "u"."TraderId" = "u0"."Id"
```
