### ISSUE TITLE
NullException show when perform linq join with DbQuery entity

### ISSUE THREAD

**Issue by RudyWangCodes** [dotnet/efcore#14129]
Hello,

Any one has the same problem like my case?

I Have DbQuery entities
Ex:

DbQuery<EnA> EnAs { get; set; }
DbQuery<EnB> EnBs { get; set; }

when I perform linq query using join, the NullException show up.
Is DbQuery can't perform linq join query?

Note:
Try to set DbSet, it's work

**Comment by roji** [comment]
@RudyWangCodes there isn't enough detail in your issue, can you please post the actual query code you're trying to run?

**Comment by RudyWangCodes** [comment]
@roji Here are the details
Ex: I have 2 entities
```
    [Table("vw_trtick_h")]
    public class VwTicketTransHeader : BaseTransactionEntity
    {
        public long Id { get; set; }
        public string InvCode { get; set; }
        public string LgCode { get; set; }
        public string TourCode { get; set; }
        public short? TourQuoDetLineNo { get; set; }
        public bool OneWay { get; set; }
        public bool Dom { get; set; }
        public string TypeCode { get; set; }
        public string Type { get; set; }
        public string SupCode { get; set; }
        public string AirCode { get; set; }
        public DateTime BookDate { get; set; }
        public string BookBy { get; set; }
        public DateTime IssuedDate { get; set; }
        public string IssuedBy { get; set; }
        public string BookCode { get; set; }
        public string Route { get; set; }
        public DateTime? FlightDate { get; set; }
        public byte AdtQty { get; set; }
        public byte ChdQty { get; set; }
        public byte InfQty { get; set; }
        public string CurrCode { get; set; }
        public decimal PublishFare { get; set; }
        public decimal TotalNta { get; set; }
        public decimal TotalDisc { get; set; }
        public decimal TotalExtraDisc { get; set; }
        public decimal TotalSerFee { get; set; }
        public string DNCode { get; set; }
        public short PaxQty { get; set; }
        public decimal PaxPaid { get; set; }
        public string TypeName { get; set; }
        public string IssInitial { get; set; }
        public string SupName { get; set; }
        public string AirInitial { get; set; }
        public string LocName { get; set; }       
        public string ConfInvCode { get; set; }
        public string ChangedInitial { get; set; }
    }

    [Table("vw_trtick_d")]
    public class VwTicketTransDetail : BaseEntity
    {
        public long Id { get; set; }
        public short LineNo { get; set; }
        public string TickNo { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PaxType { get; set; }
        public DateTime? BirthDate { get; set; }
        public decimal BasicFare { get; set; }
        public decimal Ppn { get; set; }
        public decimal Iwjr { get; set; }
        public decimal Fs { get; set; }
        public decimal AirportTax { get; set; }
        public decimal Insurance { get; set; }
        public decimal AgentCom { get; set; }
        public decimal Incentive { get; set; }
        public decimal IssueFee { get; set; }
        public decimal Bsp { get; set; }
        public decimal Nta { get; set; }
        public decimal Publish { get; set; }
        public decimal Disc { get; set; }
        public decimal ExtraDisc { get; set; }
        public decimal SerFee { get; set; }
        public decimal PaxPaid { get; set; }
        public decimal Profit { get; set; }
    }
```

I set that entities as DbQuery in my DbContext
```
        public DbQuery<VwTicketTransHeader> VwTicketTransHeaders { get; set; }
        public DbQuery<VwTicketTransDetail> VwTicketTransDetails { get; set; }
```

When I perform this query, It will show an error that describe NullException
```
                       from c in Db.VwTicketTransHeaders
                       join c2 in Db.VwTicketTransDetails
                           on new { c.CompanyId, c.Id } equals new { c2.CompanyId, c2.Id } into j
                       where c.Status && c.CompanyId == compId && !(c.TourCode == null || c.TourCode == "")
                       from c3 in j.DefaultIfEmpty()
                       select new
                       {
                           c.CompanyId, Code = c.TourCode,
                           RefConfCode = c3.TickNo, RefLgCode = c.LgCode,
                           RefSearch1 = c3.FirstName + " " + c3.LastName, RefSearch2 = c.SupName,
                           Descr1 = c.Route, Descr2 = c.BookCode
                       }
```

But when I change DbQuery to DbSet and define the key.
The query not show the error

**Comment by smitpatel** [comment]
@RudyWangCodes - Can you also post the stack trace?

**Comment by RudyWangCodes** [comment]
```
   at lambda_method(Closure , MaterializationContext )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.UnbufferedEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.UnbufferedOffsetEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider._GroupJoin[TOuter,TInner,TKey,TResult](RelationalQueryContext queryContext, IEnumerable`1 source, IShaper`1 outerShaper, IShaper`1 innerShaper, Func`2 innerKeySelector, Func`3 resultSelector)+MoveNext()
   at System.Linq.Enumerable.SelectManyIterator[TSource,TCollection,TResult](IEnumerable`1 source, Func`2 collectionSelector, Func`3 resultSelector)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Domain.Concrete.Operational.Input.TourTransRepository.GetDatas(Int16 compId, Int32 roleId, String type, String search, Int32 take, Int32 skip, IEnumerable`1 sort, Filter filter) in D:\GTASS Repos\GtassOnlineIntern\src\Domain\Concrete\Operational\Input\TourTransRepository.cs:line 55
   at API.Controllers.Operational.Input.GeneralTourController.Listing(String search, Int32 take, Int32 skip, IEnumerable`1 sort, Filter filter) in D:\GTASS Repos\GtassOnlineIntern\src\API\Controllers\Operational\Input\GeneralTourController.cs:line 61
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
```

**Comment by smitpatel** [comment]
The query involves GroupJoin which is not immediately flattened. See #17068
