### ISSUE TITLE
ef core 2.1  has something  wrong to  use enum field to query 

### ISSUE THREAD

**Issue by dustdragonpzc** [dotnet/efcore#14156]
```
Exception message:
 at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.Sanitize[T](Object value)
   at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.<>c__DisplayClass3_0`2.<SanitizeConverter>b__0(Object v)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping.CreateParameter(DbCommand command, String name, Object value, Nullable`1 nullable)
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypeMappedRelationalParameter.AddDbParameter(DbCommand command, Object value)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBase.AddDbParameter(DbCommand command, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.CreateCommand(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MengXiangChengPlus.App.Order.OfflineOrderAppService.GetAll(GetAllOfflineOrderInput input) in C:\code\company\MengXiangChengPlus\src\MengXiangChengPlus.Application\App\Order\OfflineOrderAppService.cs:line 45
```
  
### Steps to reproduce

```c#
 public enum PayMethod
    {
    AliPay = 1,
   WechatPay = 2
    }
public virtual PayMethod PayMethod { get; set; }

  var a= _offlineOrderRepository.GetAll().Where(t => t.PayMethod == (PayMethod)Enum.ToObject(typeof(PayMethod),input.PayMethodFilter)).ToList();

var b = _offlineOrderRepository.GetAll().Where(t => t.PayMethod == (PayMethod)input.PayMethodFilter).ToList();
```
variable a Got a correct value,but when get variable b that throw a exception

### Further technical details
EF Core version: 2.1
Database Provider: Pomelo.EntityFrameworkCore.MySql)
Operating system: Visual Studio 2017 15.4

**Comment by ajcvickers** [comment]
@dustdragonpzc I have been unable to reproduce this with the SQL Server or SQLite provider (see my test code below) which indicates that it is likely an issue with the MySQL provider. I would suggest filing an issue with them including a runnable project/solution or complete code listing that demonstrates the behavior.

```C#
public class Card
{
    public int Id { get; set; }
    public virtual PayMethod PayMethod { get; set; }
}

public enum PayMethod
{
    AliPay = 1,
    WechatPay = 2
}

public class Input
{
    public int PayMethodFilter { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(
                @"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");

    public DbSet<Card> Cards { get; set; }
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.AddRange(
                new Card { PayMethod = PayMethod.AliPay },
                new Card { PayMethod = PayMethod.WechatPay });

            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            var input = new Input { PayMethodFilter = 1 };

            var a = context.Cards.Where(
                t => t.PayMethod == (PayMethod)Enum.ToObject(typeof(PayMethod), input.PayMethodFilter))
                .ToList();
            
            var b = context.Cards.Where(
                t => t.PayMethod == (PayMethod)input.PayMethodFilter)
                .ToList();
        }
    }
}
```
