### ISSUE TITLE
A column has been specified more than once in the order by list.

### ISSUE THREAD

**Issue by seroche** [dotnet/efcore#14155]
Hi,

We are following DDD principles to design our application. Thus we prefer to wrap primitive types and associated business logic inside value objects. Here we try to use the Email value object as a owned entity + a foreign key. Since we cannot use navigations as a foreign keys, we have to map the SQL column `Email` to a shadow property (string) and to a owned entity.

When we run the code below:
``` C#
    public class Email
    {
        public string Value { get; private set; }
    }

    public class User
    {
        public Guid Id { get; private set; }
        public Email Email { get; private set; }
        public List<Profile> Profiles { get; private set; }
    }

    public class Profile
    {
        public Guid Id { get; private set; }
        public string Email { get; private set; }
    }

    public class Context : DbContext
    {
        private readonly string _cnx;

        public Context(string cnx) => _cnx = cnx;

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
                optionsBuilder.UseSqlServer(_cnx);
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.Entity<User>(m =>
            {
                m.ToTable("User", "user");
                m.HasKey(x => x.Id);
                m.Property(x => x.Id)
                    .HasColumnName("UserId");

                m.Property<string>("FK_Email")
                    .HasColumnName("Email");

                m.OwnsOne(x => x.Email, nav =>
                {
                    nav.Property(x => x.Value)
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Email");
                });

                m.HasMany(x => x.Profiles)
                    .WithOne()
                    .HasForeignKey(x => x.Email)
                    .HasPrincipalKey("FK_Email");
            });

            builder.Entity<Profile>(m =>
            {
                m.ToTable("Profile", "user");
                m.HasKey(x => x.Id);
                m.Property(x => x.Id)
                    .HasColumnName("ProfileId");
            });
        }
    }

    internal class Program
    {
        private static async Task Main(string[] args)
        {
            using (var db = new Context("Server=.;Database=core;Trusted_Connection=True;"))
            {
                var user = await db
                    .Set<User>()
                    .Include(x => x.Profiles)
                    .OrderBy(x => x.Email.Value)
                    .FirstOrDefaultAsync();
            }
        }
    }
```

If you are seeing an exception, include the full exceptions details (message and stack trace).
```
System.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=A column has been specified more than once in the order by list. Columns in the order by list must be unique.
  Source=Core .Net SqlClient Data Provider
  StackTrace:
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.AsyncSelectEnumerable`2.AsyncSelectEnumerator.<MoveNext>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.<FirstOrDefault_>d__165`1.MoveNext() in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\First.cs:line 144
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext() in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Select.cs:line 106
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext() in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 98
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<ExecuteSingletonAsyncQuery>d__21`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EfCoreBugRepro.Program.<Main>d__0.MoveNext() in C:\Users\sebastien_roche\source\repos\EfCoreBugRepro\Program.cs:line 81
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EfCoreBugRepro.Program.<Main>(String[] args)
```

Since we are using the same column name would it be possible to distinct the column names used in the OrderBy? 

FYI, we need the owned entity so we can use it in .Where/.OrderBy clauses. In the past, we were using a private property + EF.Property<string> and it was not really developer friendly :)

### Further technical details
EF Core version: 2.2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Visual Studio 2017 15.9

**Comment by smitpatel** [comment]
Generated SQL in 3.1
```SQL
      SELECT [t0].[UserId], [t0].[Email], [t0].[UserId0], [t0].[Email0], [p].[ProfileId], [p].[Email]
      FROM (
          SELECT TOP(1) [u].[UserId], [u].[Email], [t].[UserId] AS [UserId0], [t].[Email] AS [Email0]
          FROM [user].[User] AS [u]
          LEFT JOIN (
              SELECT [u0].[UserId], [u0].[Email], [u1].[UserId] AS [UserId0]
              FROM [user].[User] AS [u0]
              INNER JOIN [user].[User] AS [u1] ON [u0].[UserId] = [u1].[UserId]
              WHERE [u0].[Email] IS NOT NULL
          ) AS [t] ON [u].[UserId] = [t].[UserId]
          ORDER BY [t].[Email]
      ) AS [t0]
      LEFT JOIN [user].[Profile] AS [p] ON [t0].[Email] = [p].[Email]
      ORDER BY [t0].[Email0], [t0].[UserId], [p].[ProfileId]
```
