### ISSUE TITLE
Find with LINQ expression that can't be translated

### ISSUE THREAD

**Issue by 0xced** [dotnet/efcore#14180]
I'm trying to use [`DbSet<TEntity>.Find(Object[])`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbset-1.find) with a key that can't be translated and it doesn't find the entity I'm searching.

Here is my code:
```C#
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EFCoreFind
{
    public class Wrapper<T>
    {
        public Wrapper(T value)
        {
            Value = value;
        }
        
        public T Value { get; }
    }
    
    public class MyEntity
    {
        public string Name { get; set; }
        public Wrapper<string> Version { get; set; }
    }
    
    public class MyContext : DbContext
    {
        public MyContext(DbContextOptions options) : base(options)
        {
        }
        
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var entityBuilder = modelBuilder.Entity<MyEntity>(); 
            entityBuilder.HasKey(e => new { e.Name, e.Version });
            entityBuilder.Property(e => e.Version).HasConversion
            (
                version => version.Value,
                version => new Wrapper<string>(version)
            );
        }
        
        public DbSet<MyEntity> Entities { get; set; }
    }
    
    class Program
    {
        static int Main()
        {
            try
            {
                var options = new DbContextOptionsBuilder()
                    .UseLoggerFactory(new LoggerFactory().AddConsole(LogLevel.Information))
                    .EnableSensitiveDataLogging()
                    .UseSqlite("DataSource=MyDatabase.sqlite3").Options;

                using (var context = new MyContext(options))
                {
                    context.Database.EnsureDeleted();
                    context.Database.EnsureCreated();
                    context.Entities.Add(new MyEntity {Name = "Test", Version = new Wrapper<string>("1.2")});
                    context.Entities.Add(new MyEntity {Name = "Test", Version = new Wrapper<string>("3.4")});
                    context.SaveChanges();
                }
                using (var context = new MyContext(options))
                {
                    const string name = "Test";
                    const string version = "1.2";
                    Console.WriteLine("*** Find ***");
                    var entity = context.Entities.Find(name, new Wrapper<string>(version));
                    if (entity == null)
                    {
                        Console.WriteLine("*** SingleOrDefault ***");
                        entity = context.Entities.SingleOrDefault(e => e.Name == name && e.Version.Value == version);
                        if (entity == null)
                            throw new Exception($"{name} {version} not found");
                        Console.WriteLine($"Found `{entity.Name} {entity.Version.Value}` with SingleOrDefault");
                    }
                    else
                    {
                        Console.WriteLine($"Found `{entity.Name} {entity.Version}` with Find");
                    }
                }
                return 0;
            }
            catch (Exception exception)
            {
                Console.Error.WriteLine(exception);
                return 1;
            }
        }
    }
}
```

And here are the relevant logs when executed with Entity Framework Core 2.2:
```
*** Find ***
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.2.0-rtm-35687 initialized 'MyContext' using provider 'Microsoft.EntityFrameworkCore.Sqlite' with options: SensitiveDataLoggingEnabled 
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'where (Property([e], "Version") == __get_Item_1)' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'FirstOrDefault()' could not be translated and will be evaluated locally.
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      PRAGMA foreign_keys=ON;
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[@__get_Item_0='Test' (Size = 4)], CommandType='Text', CommandTimeout='30']
      SELECT "e"."Name", "e"."Version"
      FROM "Entities" AS "e"
      WHERE "e"."Name" = @__get_Item_0
*** SingleOrDefault ***
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'where ([e].Version.Value == "1.2")' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'SingleOrDefault()' could not be translated and will be evaluated locally.
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      PRAGMA foreign_keys=ON;
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT "e"."Name", "e"."Version"
      FROM "Entities" AS "e"
      WHERE "e"."Name" = 'Test'
Found `Test 1.2` with SingleOrDefault
```

I'm expecting that `Find` returns the entity, even if some part of the query has to be evaluated locally, but it doesn't find my entity and returns null. I have to use `SingleOrDefault` instead which properly evaluates locally and returns the entity.

Am I doing something wrong or is this a bug/limitation of Entity Framework Core ?

Running on macOS 10.12.6 with this project:
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp2.2</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.2.0" />
      <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.2.0" />
    </ItemGroup>
</Project>
```

**Comment by ajcvickers** [comment]
@0xced The problem is that you are using a reference type (i.e. a class) to represent key values, but without overriding its equality members. This means that two instances of your key with the same value will not compare as equal, since by default reference types get reference equality. This is not to do with EF, but just C# behavior. For example:
```C#
var key1 = new Wrapper<string>("A");
var key2 = new Wrapper<string>("A");

// This will fail:
Debug.Assert(Equals(key1, key2));
```
Overriding the equality members such that they are consistent with how they are being used results in the code you posted working as expected:
```C#
public class Wrapper<T>
{
    public Wrapper(T value)
    {
        Value = value;
    }

    public T Value { get; }

    public override bool Equals(object obj)
    {
        if (ReferenceEquals(obj, this))
        {
            return true;
        }

        if (ReferenceEquals(obj, null)
            || obj.GetType() != GetType())
        {
            return false;
        }

        return Equals(Value, ((Wrapper<T>)obj).Value);
    }

    public override int GetHashCode() => Value.GetHashCode();
}
```

**Comment by 0xced** [comment]
Thanks for the explanation! Indeed it makes sense that if the `Find` query can't be translated, it will be evaluated locally by using the standard C# comparison behaviour.

But after adding the `Equals` and `GetHashCode` implementation that you provided, my sample code still doesn't find the entity with the `Find` method, it still has to go through the `FirstOrDefault` fallback implementation. I put a breakpoint at the first line of the `Equals` implementation and it's never hit. Do you know why ?

**Comment by ajcvickers** [comment]
@0xced Indeed--I missed that. This does seem to be a bug with Find and keys with value converters.

**Comment by 0xced** [comment]
Revisiting this post EF Core 3. The `Find` method works fine on EF Core 3.0.0, but the `SingleOrDefault` method now throws `System.InvalidCastException`.

Here's the slightly updated sample code:

```csharp
using System;
using System.Linq;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;

namespace EFCoreFind
{
    public class Wrapper<T>
    {
        public Wrapper(T value)
        {
            Value = value;
        }

        public T Value { get; }
    }

    public class MyEntity
    {
        public string Name { get; set; }
        public Wrapper<string> Version { get; set; }
    }

    public class MyContext : DbContext
    {
        public MyContext(DbContextOptions options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var entityBuilder = modelBuilder.Entity<MyEntity>();
            entityBuilder.HasKey(e => new { e.Name, e.Version });
            entityBuilder.Property(e => e.Version).HasConversion
            (
                version => version.Value,
                version => new Wrapper<string>(version)
            );
        }

        public DbSet<MyEntity> Entities { get; set; }
    }

    class Program
    {
        static int Main()
        {
            var connection = new SqliteConnection("DataSource=:memory:");
            try
            {
                connection.Open();
                var options = new DbContextOptionsBuilder()
                    //.UseLoggerFactory(LoggerFactory.Create(builder => builder.AddConsole())) // Add Microsoft.Extensions.Logging.Console for simple SQL logging
                    .EnableSensitiveDataLogging()
                    .UseSqlite(connection).Options;

                using (var context = new MyContext(options))
                {
                    context.Database.EnsureCreated();
                    context.Entities.Add(new MyEntity {Name = "Test", Version = new Wrapper<string>("1.2")});
                    context.Entities.Add(new MyEntity {Name = "Test", Version = new Wrapper<string>("3.4")});
                    context.SaveChanges();
                }

                using (var context = new MyContext(options))
                {
                    const string name = "Test";
                    const string version = "1.2";

                    LogResult(context.Entities.Find(name, new Wrapper<string>(version)), "Find");
                    LogResult(context.Entities.SingleOrDefault(e => e.Name == name && e.Version.Value == version), "SingleOrDefault");
                }
                return 0;
            }
            catch (Exception exception)
            {
                Console.Error.WriteLine(exception);
                return 1;
            }
            finally
            {
                connection.Close();
            }
        }

        private static void LogResult(MyEntity entity, string method)
        {
            if (entity == null)
                Console.WriteLine($"❌  The `{method}` method failed to retrieve the entity");
            else
                Console.WriteLine($"✅  Found `{entity.Name} {entity.Version.Value}` with `{method}`");
        }
    }
}
```

Result when run on Microsoft.EntityFrameworkCore.Sqlite 2.2.6:
```
❌  The `Find` method failed to retrieve the entity
✅  Found `Test 1.2` with `SingleOrDefault`
```

Result when run on Microsoft.EntityFrameworkCore.Sqlite 3.0.0:
```
✅  Found `Test 1.2` with `Find`
System.InvalidCastException: Invalid cast from 'System.String' to 'EFCoreFind.Wrapper`1[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.Sanitize[T](Object value)
   at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.<>c__DisplayClass3_0`2.<SanitizeConverter>b__0(Object v)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping.GenerateSqlLiteral(Object value)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.VisitSqlConstant(SqlConstantExpression sqlConstantExpression)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.VisitSqlBinary(SqlBinaryExpression sqlBinaryExpression)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.VisitSqlBinary(SqlBinaryExpression sqlBinaryExpression)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.VisitSelect(SelectExpression selectExpression)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.GetCommand(SelectExpression selectExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at EFCoreFind.Program.Main()
```

So, the original bug is fixed in 3.0.0, but a new one was introduced.

**Comment by smitpatel** [comment]
@0xced Equivalent query for Find would be this
```C#
context.Entities.SingleOrDefault(e => e.Name == name && e.Version== new Wrapper<string>(version))
```

Not what you wrote.
```C#
context.Entities.SingleOrDefault(e => e.Name == name && e.Version.Value == version)
```
Above query seems to be matching Nullable.Value (filed #18486) but once that is fixed, it should throw exception that we cannot translate it. If you map `Version` as a property in EF model using value converter, we cannot translate members on that as we don't know about it.

**Comment by smitpatel** [comment]
3.1 behavior (as expected)
```
System.InvalidOperationException: The LINQ expression 'DbSet<MyEntity>
    .Where(m => m.Name == "Test" && m.Version.Value == "1.2")' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```

**Comment by 0xced** [comment]
Indeed working as expected since EF Core 3.1 with the correct exception, thanks!
