### ISSUE TITLE
When saving blob or clob 32KB or larger: ORA-01460: unimplemented or unreasonable conversion requested

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#14190]
I have a `byte[]` property mapped to an Oracle blob and a `string` property mapped to an Oracle clob. Both the blob and the clob have the same problem. When the length is less than 32KB, it works correctly. When I try to save data that's 32KB or larger, I get this exception.

```
OracleException: External component has thrown an exception.
ORA-01460: unimplemented or unreasonable conversion requested

   at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck, Int32 isRecoverable, OracleLogicalTransaction m_OracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, String procedure, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, Boolean bCheck, OracleLogicalTransaction m_OracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
```
```
Microsoft.EntityFrameworkCore.DbUpdateException: 'An error occurred while updating the entries. See the inner exception for details.'

   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
   at Microsoft.EntityFrameworkCore.Oracle.Storage.Internal.OracleExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded) in D:\PI\Produkte\PIDotNetRoot\PI.Lib\EntityFrameworkCore.Oracle\Parallel.EFCore.Oracle\Storage\Internal\OracleExecutionStrategy.cs:line 40
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
```

EF Core version: 2.2.0
Database Provider: Microsoft.EntityFrameworkCore.Oracle
Operating system: Windows 10 Pro
IDE: Visual Studio Professional 2017 15.8.6

**Comment by ajcvickers** [comment]
@Wain123 This looks like an issue with the underlying ADO.NET provider for Oracle. Any reason to believe it is an EF issue?

**Comment by Wain123** [comment]
I modified `Microsoft.EntityFrameworkCore.Oracle.Storage.Internal.OracleByteArrayTypeMapping.ConfigureParameter` so it changes the `OracleDbType` from `Binary` to `Blob` (or from `Varchar2` to `Clob`) and sets the `Size` to the `byte[].Length`. After doing this, it works correctly. This workaround doesn't look too "workaroundy" to me, it looks like the way it was supposed to work in the first place. If that suspicion is correct, then it might be an EF issue.

**Comment by ajcvickers** [comment]
Putting this on the backlog to track as a known issue with the sample. We're currently not prioritizing any work to update the sample.

**Comment by iamshen** [comment]
> I modified `Microsoft.EntityFrameworkCore.Oracle.Storage.Internal.OracleByteArrayTypeMapping.ConfigureParameter` so it changes the `OracleDbType` from `Binary` to `Blob` (or from `Varchar2` to `Clob`) and sets the `Size` to the `byte[].Length` if the value is 32KB or larger. After doing this, it works correctly. This workaround doesn't look too "workaroundy" to me, it looks like the way it was supposed to work in the first place. If that suspicion is correct, then it might be an EF issue.

add  ` ((OracleParameter)parameter).OracleDbType = OracleDbType.Blob;`  to `ConfigureParameter  ` work for me

**Comment by czmirek** [comment]
For anyone looking for a quick, working solution:

- add a `[Column(TypeName = "blob")]` attribute to your byte[] property and it'll work.

**Comment by Wain123** [comment]
I'm using the fluent model builder, is your suggestion equivalent to `HasColumnType("blob")`?

If yes, it doesn't work for me.

**Comment by czmirek** [comment]
No, unfortunately, I'm not using the fluent model builder. I'd say that `HasColumnType` should be equivalent. Adding the attribute to the entity model worked for me.

**Comment by ajcvickers** [comment]
Closing old issue as this is no longer something we intend to implement.

**Comment by damon-e-drake** [comment]
This would be extremely nice to fix. The ContextSnapshot and the Fluent API aren't adhere'd to but yet a simple data attribute will fix it and come to find out the name is case sensitive. And in suspicion this is not an EF issue. This is a downright brazen lack of provider support. Let's not pass the buck here.

**Comment by 2GDev** [comment]
> For anyone looking for a quick, working solution:
> 
> * add a `[Column(TypeName = "blob")]` attribute to your byte[] property and it'll work.

Worked for me but TypeName must be Uppercase 
`[Column(TypeName = "BLOB")]`

Inspecting the code inside **Microsoft.EntityFrameworkCore.Oracle.Storage.Internal.OracleByteArrayTypeMapping** save me : 

`  if (parameter.Size == 0 || _storeType == "BLOB")
            {
                ((OracleParameter)parameter).OracleDbType = OracleDbType.Blob;
            }`

EfCore 5.0.3 
Oracle.ManagedDataAccess.Core 3.21.1
Oracle.EntityFrameworkCore 5.21.1

**Comment by Jincearanmula** [comment]
I am getting the same error "ORA-01460: unimplemented or unreasonable conversion requested", when i am trying to save string value which is more than 32kb in size, to a BLOB storage.

I have added below configuration, however i still get error while saving this from EF Core. we are using Oracle.EntityFrameworkCore version 6.21.61
                .HasColumnType("BLOB")
                .HasConversion<byte[]>(t => Encoding.UTF8.GetBytes(t), t => Convert.ToString(t))
                .HasMaxLength(1000000000)

**Comment by aminireza65** [comment]
> For anyone looking for a quick, working solution:
> 
> * add a `[Column(TypeName = "blob")]` attribute to your byte[] property and it'll work.

This worked for me as well.
