### ISSUE TITLE
The navigation property 'Role' cannot be added to the entity type 'User' because its CLR type 'Role' does not match the expected CLR type 'User'.

### ISSUE THREAD

**Issue by goldmont** [dotnet/efcore#14221]
Hi,

I'm facing issues while creating a migration in EF Core using **navigationName**, not **Expressions**. I think that EF does not get the real **Type** of the **navigationName** by returning the following exception:

```c#
Unhandled Exception: System.InvalidOperationException: The navigation property 'Role' cannot be added to the entity type 'User' because its CLR type 'Role' does not match the expected CLR type 'User'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Navigation.IsCompatible(MemberInfo navigationProperty, Type sourceClrType, Type targetClrType, Nullable`1 shouldBeCollection, Boolean shouldThrow)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Navigation.GetClrMember(String navigationName, EntityType sourceType, EntityType targetType, Boolean shouldThrow)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.Navigations(Nullable`1 navigationToPrincipal, Nullable`1 navigationToDependent, EntityType principalEntityType, EntityType dependentEntityType, Nullable`1 configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.Navigations(Nullable`1 navigationToPrincipal, Nullable`1 navigationToDependent, Nullable`1 configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.DependentToPrincipal(String name, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Relationship(InternalEntityTypeBuilder targetEntityTypeBuilder, Nullable`1 navigationToTarget, Nullable`1 inverseNavigation, Boolean setTargetAsPrincipal, ConfigurationSource configurationSource, Nullable`1 required)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Navigation(InternalEntityTypeBuilder targetEntityTypeBuilder, String navigationName, ConfigurationSource configurationSource, Boolean setTargetAsPrincipal)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder.HasOne(Type relatedType, String navigationName)
   at iTeslaMachine.Data.Model.Helpers.Structures.SetUsersStructure[T](EntityTypeBuilder`1 entity) in C:\Users\Developer_Acer\Documents\Visual Studio 2017\Projects\iTeslaMachine\iTeslaMachine.Data.Model\Helpers\TableUtils.cs:line 215
   at iTeslaMachine.Data.Model.TeslaContext.OnModelCreating(ModelBuilder modelBuilder) in C:\Users\Developer_Acer\Documents\Visual Studio 2017\Projects\iTeslaMachine\iTeslaMachine.Data.Model\TeslaContext.cs:line 108
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

This is my current scenario:

```c#
public abstract class EntityBase
{
    #region Columns
    public const string IDColumn            =   "id";
    public const string CreatedAtColumn     =   "created_at";
    #endregion

    [Column(IDColumn), Key]        
    public uint ID { get; set; }

    [Column(CreatedAtColumn)]
    public DateTime CreatedAt { get; set; }
}
```
```c#
public abstract class RoleBase : EntityBase
{
    #region Columns
    public const string CodeColumn              =   "code";
    public const string DescriptionColumn       =   "description";
    #endregion

    #region Roles
    protected const string UserRole             =   "user";
    protected const string StaffRole            =   "staff";
    #endregion

    [Column(CodeColumn)]
    public string Code { get; set; }

    [Column(DescriptionColumn)]
    public string Description { get; set; }
}
```
```c#
public abstract class UserBase : EntityBase
{
    #region Columns
    public const string UsernameColumn      =   "username";
    public const string RoleIDColumn        =   "role_id";
    #endregion

    [Column(UsernameColumn)]
    public string Username { get; set; }
}
```

```c#
#region Temporary
[Table(Tables.TemporaryRoles)]
public sealed class TemporaryRole : RoleBase { }
#endregion

[Table(Tables.Roles)]
public sealed class Role : RoleBase, IFeed<Role>
{
    public async Task<Role[]> GetFeed()
    {
        return await Task.FromResult(new[]
        {
            new Role { ID = 1,      Code = UserRole,        Description = "User-Level" },
            new Role { ID = 2,      Code = StaffRole,       Description = "Staff-Level" }
        });
    }
}
```

```c#
#region Temporary
[Table(Tables.TemporaryUsers)]
public sealed class TemporaryUser : UserBase
{
    [Column(RoleIDColumn)]
    public uint RoleID { get; set; }
    public TemporaryRole Role { get; set; }
}
#endregion

[Table(Tables.Users)]
public sealed class User : UserBase, IFeed<User>
{
    [Column(RoleIDColumn)]
    public uint RoleID { get; set; }
    public Role Role { get; set; }

    public async Task<User[]> GetFeed()
    {
        return await Task.FromResult(new[]
        {
            new User { ID = 1,      Username = "User_1",        RoleID = 1 },
            new User { ID = 2,      Username = "User_2",        RoleID = 2 },
            new User { ID = 3,      Username = "User_3",        RoleID = 2 },
        });
    }
}
```

```c#
public sealed class MyContext : DbContext
{
    public readonly RelationalDatabaseCreator Base;

    #region Ordinary DbSets
    public DbSet<Role>                                                  Roles                                                   { get; set; }
    public DbSet<User>                                                  Users                                                   { get; set; }
    #endregion

    #region Temporary DbSets
    public DbSet<TemporaryRole>                                         TemporaryRoles                                          { get; set; }
    public DbSet<TemporaryUser>                                         TemporaryUsers                                          { get; set; }
    #endregion

    public MyContext()
    {
        Base = this.GetService<IDatabaseCreator>() as RelationalDatabaseCreator;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlite($"Data Source=MyDatabase.db");
        }
    }

    protected override async void OnModelCreating(ModelBuilder modelBuilder)
    {
        #region Roles
        modelBuilder.Entity<Role>().SetRolesStructure();
        modelBuilder.Entity<TemporaryRole>().SetRolesStructure();
        #endregion

        #region Users
        modelBuilder.Entity<User>().SetUsersStructure();
        modelBuilder.Entity<TemporaryUser>().SetUsersStructure();
        #endregion

        await LoadDemoData(modelBuilder);

        base.OnModelCreating(modelBuilder);
    }

    async Task LoadDemoData(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Role>().HasData(await new Role().GetFeed());

        modelBuilder.Entity<User>().HasData(await new User().GetFeed());
    }
}
```

```c#
internal static class Structures
{
    static readonly Type
            EntityUser          =   typeof(User),
            EntityTemporaryUser =   typeof(TemporaryUser);

    #region Users
    public static void SetUsersStructure<T>(this EntityTypeBuilder<T> entity) where T : UserBase
    {
        bool temporary = typeof(T) == EntityTemporaryUser;

        entity
            .HasOne(temporary ? EntityTemporaryUser : EntityUser, "Role")
            .WithMany()
            .HasForeignKey("RoleID")
            .IsRequired();

        entity.SetCreateTimeRule();
    }
    #endregion

    #region Column Utils
    static void SetCreateTimeRule<T>(this EntityTypeBuilder<T> entity) where T : EntityBase
    {
        entity.Property((x) => x.CreatedAt).HasDefaultValueSql(ColumnDefaultValues.CurrentTimestamp);
    }
    #endregion
}
```

Is there a fix? Thanks.

**Comment by smitpatel** [comment]
```C#
entity
            .HasOne(temporary ? EntityTemporaryUser : EntityUser, "Role")
            .WithMany()
            .HasForeignKey("RoleID")
            .IsRequired();
```
Above code is cause of the error. You are working with entity type builder of User and trying to add navigation named "Role" but you are telling the type is `TemporaryUser` or `User` which is incorrect as exception message says. You need to pass in TemporaryRole or Role.

**Comment by goldmont** [comment]
Thanks, it worked perfectly.
