### ISSUE TITLE
System.InvalidCastException: Unable to cast object of type 'System.Int16' to type 'System.Nullable`1[System.Boolean]'.

### ISSUE THREAD

**Issue by solcada** [dotnet/efcore#14337]
Currently working with IBM.EntityFrameworkCore on .net 2.2 and getting Unable to cast object of type 'System.Int16' to type 'System.Nullable`1[System.Boolean]'.

It does not occur on the first call to the database.  It only occurs on the second call to the database.

Database field is a boolean generated entity is also a boolean.

```
Exception message:
Stack trace:  at lambda_method(Closure , MaterializationContext )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.UnbufferedEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at lambda_method(Closure )
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at Xyz.Infrastructure.Repository.XYZHandler.GetXYZ(Int32 conditionId) in C:\Xyz.Infrastructure\Repository\XYZRepository.cs:line 20
   at Xyz.Core.Application.Handler.XYZHandler.Handle(GetConditionQuery command) in C:\Xyz.Core\Application\Handler\XYZRepository.cs:line 22
```

### Steps to reproduce

Retrieve any value from a table that has a nullable boolean? the second time it will fail.

```c#
    public class TEST
    {
        public string ID { get; set; }
        public bool? TEST_BOOL { get; set; }
    }
```

### Further technical details
EF Core version: (2.2.0)
Database Provider: (e.g. IBM.EntityFrameworkCore 1.3.0.100)
Operating system: Windows
IDE: (Visual Studio 2017 15.4)

**Comment by ErikEJ** [comment]
Most likely a bug in IBM.EntityFrameworkCore 1.3.0.100...

**Comment by ajcvickers** [comment]
@solcada As @ErikEJ says, this is most likely a problem with the IBM provider, in which case you should report to them. However, it would likely be useful to provide them with a runnable project/solution or complete code listing so they can easily reproduce the issue you are seeing.
