### ISSUE TITLE
Constructor binding fails for type with read-only properties

### ISSUE THREAD

**Issue by davidbaxterbrowne** [dotnet/efcore#14336]
For types with read-only properties set through a constructor, constructor binding fails with

> : 'No suitable constructor found for entity type 'A'. The following constructors had parameters that could not be bound to properties of the entity type: cannot bind 'Id', 'Name' in 'A(int Id, string Name)'.'

This is important because
1) Constructor binding is the only way to set values for read-only properties without reflection. 
2) Anonymous Types follow this pattern and so this currently blocks using anonymous types as Query Types.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
'No suitable constructor found for entity type 'A'. The following constructors had parameters that could not be bound to properties of the entity type: cannot bind 'Id', 'Name' in 'A(int Id, string Name)'.'
Stack trace:

   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConstructorBindingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at EFCore2Test.Program.Main(String[] args) in C:\Users\dbrowne\documents\visual studio 2017\Projects\EFCore2Test\EFCore2Test\Program.cs:line 90
```

### Steps to reproduce

```c#
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;

using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
//using Microsoft.Samples.EFLogging;
using System.Data.SqlClient;
using System.Xml.Linq;
using System.Threading.Tasks;
using System.Data.Common;

namespace EFCore2Test
{


    public class A
    {
        public A(int Id, string Name)
        {
            this.Id = Id;
            this.Name = Name;
        }
        public int Id { get;  }
        public string Name { get;  }
    }

    public class Db : DbContext
    {
        DbConnection con;
        public Db() : base()
        {

        }
        Db(DbConnection con)
        {
            this.con = con;
        }
        public DbSet<A> As { get; set; }


        public Db GetChildContext()
        {
            this.Database.OpenConnection();
            return new Db(this.Database.GetDbConnection());
        }

        public void DetachAll()
        {
            foreach (var e in this.ChangeTracker.Entries().ToList())
            {
                e.State = EntityState.Detached;
            }
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
           // modelBuilder.Query<A>();

            base.OnModelCreating(modelBuilder);

        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (con == null)
                optionsBuilder.UseSqlServer("Server=(local);Database=EFCoreTest;Trusted_Connection=True;MultipleActiveResultSets=true");
            else
                optionsBuilder.UseSqlServer(con);
            base.OnConfiguring(optionsBuilder);
        }
    }


    class MyClass
    {
        public int LuckNumber { get; set; }
    }

    class Program
    {


   
        static void Main(string[] args)
        {

            using (var db = new Db())
            {
               var col = db.Set<A>().FirstOrDefault();
                //var col2 = db.SqlQuery(() => new { id =1, name=""},"select 1 id, 'joe' name").ToList();
            }


            Console.WriteLine("Hit any key to exit");
            Console.ReadKey();
        }
        
    }
}





```

### Further technical details
EF Core version: 2.2.0
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer (but won't matter)
Operating system: Windows
IDE: Visual Studio 2017 15.4

**Comment by ajcvickers** [comment]
@davidbaxterbrowne This is because read-only properties are not matched by convention, and hence there are no mapped properties that match the constructor. Mapping the properties like this should result in the constructor being used without error:
```C#
modelBuilder.Entity<A>(b =>
{
    b.Property(e => e.Id).ValueGeneratedNever();
    b.Property(e => e.Name);                
});
```
Note that I also made the primary key property not store-generated as well. This is because of issue #13237, which is fixed for 3.0, but for 2.2 and below means EF can't write to readonly fields directly.

**Comment by weitzhandler** [comment]
As of EF Core 3.1, is it possible to have a readonly `Id` property with an `id` constructor parameter, while still having it auto incremented on add?

**Comment by ajcvickers** [comment]
@weitzhandler Yes.
