### ISSUE TITLE
Seeding Nested Owned Types using HasData() throws exception on Add-Migration

### ISSUE THREAD

**Issue by JShawnLooney** [dotnet/efcore#14359]
Starting with the EFModeling.Samples.DataSeeding example code from the EF Core documentation, I am adding another owned type, Comment, to the Post entity.  And Comment itself has an owned type, User.  When I try to seed data into nested owned types and execute Add-Migration I get an exception during DataValidation, but the exception is on the parent entity, not the owned types.  I was able to add a migration without the HasData() seed calls and the migration is created and the ModelSnapshot is updated, seemingly correctly.  It is only when I try to add seed data into the modelBuilder that I get the exception.

```
PM> Add-Migration NestedOwnedSeedData
Exception message: 
System.InvalidOperationException: The seed entity for entity type 'Post' cannot be added because there was no value provided for the required property 'BlogId'.
Stack trace: 
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateData(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The seed entity for entity type 'Post' cannot be added because there was no value provided for the required property 'BlogId'.
```

### Steps to reproduce
Attached full project code.  
[DataSeeding.zip](https://github.com/aspnet/EntityFrameworkCore/files/2743965/DataSeeding.zip)
From Package Manager Console try to Add-Migration
```
PM> Add-Migration NestedOwnedSeedData
```
Here is a code snippet:
```c#
modelBuilder.Entity<Post>().OwnsOne(p => p.Comment, c =>
                {
                    c.OwnsOne(x => x.CommentUser).HasData(
                        new { CommentPostId = 1, UserLogin = "david_barnes", Region = "Asia" },
                        new { CommentPostId = 2, UserLogin = "helen_loomis", Region = "North America" });
                }).HasData(
                new { PostId = 1, Text = "Testing the nested owned type seeding" },
                new { PostId = 2, Text = "Will this work or not?" });
```

### Further technical details
EF Core version: 2.2.1 (upgraded from 2.1 after generating NestedOwned migration)
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.3

**Comment by JShawnLooney** [comment]
Okay, I've played around with this a bit more...if I break apart the nested, owned seeding statements as follows AND delete all the migrations and do a new Add-Migration Initial, it will work.
```c#
            modelBuilder.Entity<Post>().OwnsOne(p => p.Comment, c =>
            {
                c.OwnsOne(x => x.CommentUser)
                .HasData(
                new { CommentPostId = 1, UserLogin = "david_barnes", Region = "Asia" },
                new { CommentPostId = 2, UserLogin = "helen_loomis", Region = "North America" });
            });

            modelBuilder.Entity<Post>().OwnsOne(p => p.Comment)
            .HasData(
            new { PostId = 1, Text = "Testing the nested owned type seeding" },
            new { PostId = 2, Text = "Will this work or not?" });
```
In my sample project, I created the NestOwned migration under 2.1.  When I compare the ModelSnapshot files generated from the working code and this project, I see that the Owned Types are missing HasKey() statements.  This is probably also why I cannot Remove-Migration successfully after upgrade to 2.2.1.

**Comment by JShawnLooney** [comment]
Sory, didn't mean to close the issue.

**Comment by AndriySvyryd** [comment]
In your original code you are calling `HasData` on `Post`, it should look like this:
```C#
modelBuilder.Entity<Post>().OwnsOne(p => p.Comment, c =>
                {
                    c.OwnsOne(x => x.CommentUser).HasData(
                        new { CommentPostId = 1, UserLogin = "david_barnes", Region = "Asia" },
                        new { CommentPostId = 2, UserLogin = "helen_loomis", Region = "North America" });

                    c.HasData(
                        new { PostId = 1, Text = "Testing the nested owned type seeding" },
                        new { PostId = 2, Text = "Will this work or not?" })
                });
```
