### ISSUE TITLE
Wrong code generated when using ValueConverters on MySQL

### ISSUE THREAD

**Issue by facundofarias** [dotnet/efcore#14360]
Describe what is not working as expected.

When using the ValueConversions described here: https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions, the code generated for MySQL is not correct and leads to an exception. If we remove the default value, then we are allowed to continue, so I think it should not be placed there ever since the beginning.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
MySql.Data.MySqlClient.MySqlException (0x80004005): BLOB, TEXT, GEOMETRY or JSON column 'Type' can't have a default value ---> MySql.Data.MySqlClient.MySqlException (0x80004005): BLOB, TEXT, GEOMETRY or JSON column 'Type' can't have a default value
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 42
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 74
   at MySql.Data.MySqlClient.MySqlDataReader.ReadFirstResultSetAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 299
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(MySqlCommand command, CommandBehavior behavior, ResultSetProtocol resultSetProtocol, IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 284
   at MySqlConnector.Core.TextCommandExecutor.ExecuteReaderAsync(String commandText, MySqlParameterCollection parameterCollection, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\TextCommandExecutor.cs:line 37
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 261
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 62
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
BLOB, TEXT, GEOMETRY or JSON column 'Type' can't have a default value
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

ValueConverter used:
```c#
            modelBuilder
                .Entity<SomeObject>()
                .Property(m => m.Type)
                .HasConversion(new EnumToStringConverter<SomeObjectType>());
);
```

Generated code:
```c#
            migrationBuilder.AddColumn<string>(
                name: "Type",
                table: "Memberships",
                nullable: false,
                defaultValue: ""
);
```

### Further technical details
EF Core version: 2.1.4
Database Provider: Pomelo.EntityFrameworkCore.MySql
Operating system: macOS Mojave 10.14
IDE: Visual Studio for Mac 7.7.2 (build 21)

**Comment by smitpatel** [comment]
Interesting.
The `defaultValue: ""` is generated because a column is being added in existing table (hence need to provide default value for existing columns).
Perhaps MySQL provider needs to convert the default value of "" to something else in SQL?

**Comment by facundofarias** [comment]
@smitpatel Maybe.
But as stated in MySQL docs, these fields cannot have a default value:
> BLOB and TEXT columns cannot be assigned a default value. As of MySQL 5.0.2, if a column definition includes no explicit DEFAULT value, MySQL determines the default value as follows: If the column can take NULL as a value, the column is defined with an explicit DEFAULT NULL clause.

source: http://ftp.nchu.edu.tw/MySQL/doc/refman/5.0/en/data-type-defaults.html

**Comment by ajcvickers** [comment]
@facundofarias This is an issue with the MySQL provider--please report to https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql

The default value can be there for two reasons:
* It's been specified in the model
* The column needs a default value because it is a new required column in the database and existing columns need to have some value assigned.

The MySQL provider should do two things:
* Add a model building validation rule to throw (or at least warn) for default values explicitly configured on this type of column.
* Ignore any default value when generating the SQL for migrations for columns of these types.

For now, a workaround is to edit the migration and remove the default value.

**Comment by facundofarias** [comment]
Thanks @ajcvickers
