### ISSUE TITLE
Issue with multiple Foreign keys after migrating to EFCore 2.2

### ISSUE THREAD

**Issue by thivy** [dotnet/efcore#14412]
I get the the following error message when I start the API project. It works with EFCore 2.1 The issue appeared when I upgraded to netcoreapp 2.2.1 and EFCore 2.2.1 

```
There are multiple ForeignKeyAttributes which are pointing to same set of properties - '{'DamageId'}' on entity type 'SignoffModel'.
```

```
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ForeignKeyAttributeConvention.Apply(InternalRelationshipBuilder relationshipBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnForeignKeyAdded(InternalRelationshipBuilder relationshipBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.RunVisitor.VisitOnForeignKeyAdded(OnForeignKeyAddedNode node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnForeignKeyAddedNode.Accept(ConventionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.Visit(ConventionNode node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.VisitConventionScope(ConventionScope node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionScope.Accept(ConventionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.Visit(ConventionNode node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.VisitConventionScope(ConventionScope node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionScope.Accept(ConventionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.Visit(ConventionNode node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.VisitConventionScope(ConventionScope node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionScope.Accept(ConventionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.Visit(ConventionNode node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.VisitConventionScope(ConventionScope node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Run()
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Dispose()
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(TypeIdentity& type, ConfigurationSource configurationSource, Boolean allowOwned, Boolean throwOnQuery)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(Type type, ConfigurationSource configurationSource, Boolean allowOwned, Boolean throwOnQuery)
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity(Type type)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.FindSets(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelCustomizer.FindSets(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_2(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_TransactionManager()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.BeginTransaction()
   at ACTIS.Core.Infrastructure.Middlewares.DatabaseTransactionHandler.Invoke(HttpContext context, DatabaseContext databaseContext) in C:\Users\Thivy Ruthra\source\repos\ACTIS\src\ACTIS.Core\Infrastructure\Middlewares\DatabaseTransactionHandler.cs:line 23
   at ACTIS.Core.Infrastructure.Middlewares.GlobalExceptionHandler.Invoke(HttpContext context) in C:\Users\Thivy Ruthra\source\repos\ACTIS\src\ACTIS.Core\Infrastructure\Middlewares\GlobalExceptionHandler.cs:line 41
```

### Steps to reproduce
We took the database first approach to create the schema and we have many models that maps directly onto those tables.  

An example of a simple model is shown below.
```c#
public class SignoffModel : BaseMetadataModel
{
    public int? DamageId { get; set; }
    
    [ForeignKey("DamageId")]
    public DamageModel Damage { get; set; }

}
```

As soon as i run the project i get the multiple foreign key error. The exact same model is working with EFCore 2.1 and only happens with EFCore 2.2

### Further technical details
EF Core version: 2.2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE:  Visual Studio 2017 15.9.5

**Comment by AndriySvyryd** [comment]
@thivy In 2.1 duplicate attributes were ignored. We added this validation so users can see this and fix their models.

**Comment by vocko** [comment]
This should be optional as we are unable to upgrade due to tons of duplicate keys now and secondly, we even want to keep those duplicated definitions as they help developers to orient what is pointing where.
It is nice to have a feature to discover them if one wants to remove the duplicate definitions though.

**Comment by AndriySvyryd** [comment]
@vocko Can you show open a new issue with a small repro project that throws this exception and explain exactly how it would be useful not to throw besides saving the time to remove them?

**Comment by vocko** [comment]
Simply this case. As there are defined Table attributes, you are not allowed to have the ForeignKey one as it duplicates it (at least that's what I'm getting from the error I get). While I can click-through to a Company object, is is still nice to have that attribute on Person's property what gives me immediate visual hint where it points to and that it is related to some other table.

```
[Table("Person")]
public class Person
{
    [Key]
    public Guid Id {get; set;}

    [ForeignKey("Organisation")]
    public  Guid OrganisationId { get; set; }
    
    public virtual Company Organisation {get; set;}
}

[Table("Company")]
public class Company
{
    [Key]
    public Guid Id { get; set; }

    public  ICollection<Person> People { get; set; }
}
```
And also, as it was ignored up till 2.1, would be nice to have some option to keep it ignored by a flag or something as with the amount of duplicates we need at least a day of work to clean the whole solution and that blocks the upgrade.

Does it make sense?

**Comment by AndriySvyryd** [comment]
@vocko That example doesn't throw any exceptions.
> There are multiple ForeignKeyAttributes which are pointing to same set of properties - '{'DamageId'}' on entity type 'SignoffModel'.

Is only thrown when there are multiple `ForeignKeyAttribute` for the same property using different navigations.

**Comment by vocko** [comment]
Hmm, maybe I've missed something, I'm in the middle of something else right now, but I will take a look later to get the exact example we had problem with. I know that there were problems with Attributes where the same FK is defined in model builder, but I will try to bring the exact problem.

Thanks for responding Andriy!

**Comment by alexsorokoletov** [comment]
We got a similar error message with .NET Core 3 source code we migrated from .NET 4.5.
The reason was that the old EF required to have ForeignKey both on the navigational property and on the foreign key field (or maybe it was ignored just like in 2.2)

Thank you, this thread helped us.
