### ISSUE TITLE
Exception thrown when using a DbSet<> property that is an explicit interface implementation

### ISSUE THREAD

**Issue by samfozz** [dotnet/efcore#14453]
Since updating from 2.1.1 to 2.2.1, an Exception is thrown when using a DbSet<> property that is an explicit interface implementation in the DbContext class - example below. 

```
Exception message: The property 'ConsoleApp1.ITextContextInterface.Entities' of entity type 'TestContext' does not have a setter. Either make the property writable or use a different 'PropertyAccessMode'.
Stack trace:
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrAccessorFactory`1.Create(PropertyInfo propertyInfo, IPropertyBase propertyBase)
   at Microsoft.EntityFrameworkCore.Internal.DbSetFinder.<>c__DisplayClass2_0.<FindSets>b__2(PropertyInfo p)
   at System.Linq.Enumerable.SelectIPartitionIterator`2.LazyToArray()
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.DbSetInitializer.InitializeSets(DbContext context)
   at ConsoleApp1.TestContext..ctor()
   at ConsoleApp1.Program.Main(String[] args) in C:\CODE\ConsoleApp1\Program.cs:line 12
```

### Steps to reproduce

The Exception is thrown from the DbContext constructor. 

.csproj
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="2.2.1" />
  </ItemGroup>
</Project>
```

Program.cs
```c#
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            using (var db = new TestContext())
            {
                var things1 = ((ITextContext1) db).Things;

                things1.Add(new Thing(){ Name = "Things 1"});

                var things2 = ((ITestContext2) db).Things;

                things2.Add(new OtherThing() { OtherThingName = "Things 2" });


                db.SaveChanges();

            }

            using (var db = new TestContext())
            {
                var things1 = ((ITextContext1)db).Things; 

                var things2 = ((ITestContext2)db).Things; 

                Console.WriteLine($"Did it work? - things1 = '{String.Join(",", things1.Select(a => a.Name))}' " +
                                  $"- things2 = '{String.Join(",", things2.Select(a => a.OtherThingName))}'");

                Console.ReadKey();

            }
        }
    }


    public class Thing
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }

    public class OtherThing
    {
        public int Id { get; set; }

        public string OtherThingName { get; set; }
    }

    public interface ITextContext1
    {
        DbSet<Thing> Things { get; set; }
    }

    public interface ITestContext2
    {
        DbSet<OtherThing> Things { get; set; }
    }

    public class TestContext: DbContext, ITextContext1, ITestContext2
    {
        DbSet<Thing> ITextContext1.Things { get; set; }


        DbSet<OtherThing> ITestContext2.Things { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseInMemoryDatabase(databaseName: "Test");
            }
        }
    }
}

```

Note that this code works when using the 2.1.1 packages :

```
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="2.1.1" />
```

### Further technical details
EF Core version: 2.2.1
Database Provider: Microsoft.EntityFrameworkCore.InMemory
Operating system: Windows 10 
IDE: Visual Studio 15.9.5

**Comment by smitpatel** [comment]
@ajcvickers - The repro code above works fine in 3.1 release. I am not able to correlated exception message with the repro code provided.

**Comment by SimonCropp** [comment]
seems this issue should be closed?
