### ISSUE TITLE
Database Insert Error: "Cannot insert the value NULL into column" even if the value is not NULL

### ISSUE THREAD

**Issue by hankl** [dotnet/efcore#14476]
There is a database insert error occurred sometimes "Cannot insert the value NULL into column" even if the value is not null. The column is not primary key.  The error will gone after application restarted.

INSERT INTO [CustomClaims] ([Id], [Name], [UserId], [Value])
VALUES (@p2, @p3, @p4, @p5),
(@p6, @p7, @p8, @p9),
(@p10, @p11, @p12, @p13),
(@p14, @p15, @p16, @p17),
(@p18, @p19, @p20, @p21),
(@p22, @p23, @p24, @p25),
(@p26, @p27, @p28, @p29),
(@p30, @p31, @p32, @p33),
(@p34, @p35, @p36, @p37),
(@p38, @p39, @p40, @p41);"
2019-01-21 03:08:22.875 +00:00 [Debug] [Microsoft.EntityFrameworkCore.Database.Command] A data reader was disposed.
2019-01-21 03:08:22.961 +00:00 [Debug] [Microsoft.EntityFrameworkCore.Database.Transaction] Disposing transaction.
2019-01-21 03:08:22.963 +00:00 [Error] [Microsoft.EntityFrameworkCore.Update] An exception occurred in the database while saving changes for context type '"*****.AuthServer.Core.Contexts.AuthServerDbContext"'."
""Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Cannot insert the value NULL into column 'Value', table '****.dbo.CustomClaims'; column does not allow nulls. INSERT fails.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreResults(Boolean& moreResults)
   at System.Data.SqlClient.SqlDataReader.TryNextResult(Boolean& more)
   at System.Data.SqlClient.SqlDataReader.NextResult()
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)"
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Cannot insert the value NULL into column 'Value', table '******.dbo.CustomClaims'; column does not allow nulls. INSERT fails.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreResults(Boolean& moreResults)
   at System.Data.SqlClient.SqlDataReader.TryNextResult(Boolean& more)
   at System.Data.SqlClient.SqlDataReader.NextResult()
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)

### Steps to reproduce
It is hard to reproduce. It happens occasionally. It will disappear after restart and will come back again sometime later.

### Further technical details
EF Core version: (2.0.1)
Database Provider: (Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Azure China web app OR  Win10
IDE: (Visual Studio 2017 )

**Comment by hankl** [comment]
I debug it locally and saw the value is not null but throw the exception when inserting to DB.

**Comment by ajcvickers** [comment]
@hankl Please post a smmal, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by jomeno** [comment]
I have also just run into a similar issue:

"Cannot insert the value NULL into column 'Id', table 'zzz'; column does not allow nulls. INSERT fails."

 The "Id" property of the entity is a non-nullable long so it defaults to a zero (0) yet I get the error while trying to save a new table record.
