### ISSUE TITLE
Client evaluation when inline SQL contains a line break after SELECT that doesn't match platform

### ISSUE THREAD

**Issue by EricStG** [dotnet/efcore#14489]
We have this query that is forcing client-side evaluation, but this only happens if:
- Using a global filter on the entity type
- Using `FromSql` with inline SQL
- The inline SQL is a verbatim string that contains a line break between the `SELECT` statement and the first column (or `*`). Line breaks anywhere else are fine.
- The `.cs` file containing the inline SQL has line break not matching the platform (CRLF on Linux or LF on Windows)

The weirdest part is this seem to happen at compilation time. If we do a build on the linux machine with the Windows line ending, and run it on a Windows machine, it will throw an exception.

```
Exception message: System.InvalidOperationException: Error generated for warning 'Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning: The LINQ expression 'where [e].IsEnabled' could not be translated and will be evaluated locally.'. This exception can be suppressed or logged by passing event ID 'RelationalEventId.QueryClientEvaluationWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
Stack trace:
   at Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`1.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, WarningBehavior warningBehavior, TParam arg, Exception exception)
   at Microsoft.EntityFrameworkCore.Internal.RelationalLoggerExtensions.QueryClientEvaluationWarning(IDiagnosticsLogger`1 diagnostics, QueryModel queryModel, Object queryModelElement)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitWhereClause(WhereClause whereClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
   at System.Linq.AsyncEnumerable.Aggregate_[TSource,TAccumulate,TResult](IAsyncEnumerable`1 source, TAccumulate seed, Func`3 accumulator, Func`2 resultSelector, CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Aggregate.cs:line 118
   at LinuxEFIssue.Program.TestMe() in C:\Code\LinuxEFIssue\LinuxEFIssue\LinuxEFIssue\Program.cs:line 44
   at LinuxEFIssue.Program.Main() in C:\Code\LinuxEFIssue\LinuxEFIssue\LinuxEFIssue\Program.cs:line 17
```

### Steps to reproduce

Entire code has been attached to this ticket. `Program.cs` has been ran through `dos2unix` so this example will break on `Windows` (use `unix2dos Program.cs` if you want it to break on Linux)

[LinuxEFIssue.zip](https://github.com/aspnet/EntityFrameworkCore/files/2784954/LinuxEFIssue.zip)

The key parts are:

The Sql constant MUST have a line break between `SELECT` and `[Id]`
```c#
            const string Sql = @"SELECT
[Id], [IsEnabled] FROM [Entities]";
```

There must be a query filter on Entity:
```c#
entity.HasQueryFilter(e => e.IsEnabled);
```

Also enabled throw on client evaluation to make the issue pop a bit more.

### Further technical details
EF Core version: 2.2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer (Also happens using Npgsql.EntityFrameworkCore.PostgreSQL)
Operating system: Windows 10 Pro
IDE: Visual Studio 2017 15.9.5

**Comment by JabX** [comment]
Wow I was just confronted with the problem as I was inexplicably getting an error (client evaluation was failing) on my Linux testing environments that I couldn't reproduce on my local Windows machine... I definitely could have searched for a very long time for a proper solution (which is removing *one* line break...) if not for this issue.
