### ISSUE TITLE
Allow keyless types with owned types

### ISSUE THREAD

**Issue by yringler** [dotnet/efcore#14497]
I expect owned types to map when I'm calling a stored procedure via `context.Entity<T>.FromSql("")`
Even better, QueryTypeBuilder should support OwnsOne/OwnsMany methods.

Use case: I have a stored procedure which returns lots of data, such as phone number & extension, address & state & city & country, which should be grouped together into separate classes. I would like to be able to map the stored procedure results into nested objects.

```
Exception message: The Include operation is not supported when calling a stored procedure.
Stack trace: Test Name:	CanGetCenterDetail(117572)
Test FullName:	Api.Tests.Areas.ChabadOrg.Data.CentersRepositoryTests.CanGetCenterDetail(117572)
Test Source:	C:\Users\yehuda.ringler\Documents\Repository\EFCORE\Chabad.Data.Tests\SPAttempt\CentersRepositoryTests.cs : line 54
Test Outcome:	Failed
Test Duration:	0:00:01.102

Result StackTrace:	
at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitEntityQueryable(Type elementType)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.EntityQueryableExpressionVisitor.VisitConstant(ConstantExpression constantExpression)
   at System.Linq.Expressions.ConstantExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CompileMainFromClauseExpression(MainFromClause mainFromClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.CompileMainFromClauseExpression(MainFromClause mainFromClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitMainFromClause(MainFromClause fromClause, QueryModel queryModel)
   at Remotion.Linq.Clauses.MainFromClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at Api.Areas.ChabadOrg.Data.CentersRepository.GetCenter(Int32 articleId)
   at Api.Tests.Areas.ChabadOrg.Data.CentersRepositoryTests.CanGetCenterDetail(Int32 mosadId)
Result Message:	System.InvalidOperationException : The Include operation is not supported when calling a stored procedure.
```

### Steps to reproduce
I'm omitting a full reproduction because I think this is known behaviour, but here's a snippet of the `OnModelCreating` method. If a full, compilable program is wanted, let me know and I'll try to get back to you.
```c#
modelBuilder.Entity<Center>()
			.OwnsOne(
				center => center.CenterType,
				type =>
				{
					type.Property(t => t.Id).HasColumnName("mosadType_Id");
					type.Property(t => t.Name).HasColumnName("mosadtype");
				})
			.OwnsOne(
				center => center.MailingAddress,
				address =>
				{
					address.Property(a => a.AddressLine1).HasColumnName("mail_Address");
					address.Property(a => a.AddressLine2).HasColumnName("mail_Address2");
					address.Property(a => a.City).HasColumnName("mail_city");
					address.Property(a => a.Country).HasColumnName("mail_country");
					address.Property(a => a.State).HasColumnName("mail_state");
					address.Property(a => a.ZipCode).HasColumnName("mail_zipCode");

				}
			);

modelBuilder.Entity<Center>().OwnsOne(center => center.PhoneNumber);
modelBuilder.Entity<Center>().OwnsOne(center => center.Address);
```
This is called from a repository class with
```c#
var center = context.Entity<Center>().FromSql("...").FirstOrDefault();
```

### Further technical details
EF Core version: 2.2.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.0

**Comment by smitpatel** [comment]
This happens because owned types are brought in through Include pipeline. Which may change in 3.0 query pipeline.

**Comment by yringler** [comment]
> Which may change in 3.0 query pipeline.

If that happens would `QueryTypeBuilder` get it's very own [Owns(One|Many)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder.ownsone?view=efcore-2.1#Microsoft_EntityFrameworkCore_Metadata_Builders_EntityTypeBuilder_OwnsOne_System_String_System_String_) methods?

**Comment by ajcvickers** [comment]
@yringler Query types (that is, types that have no primary key defined) cannot contain owned types because owned types require the owner to have a key. This is unlikely to change.

**Comment by ajcvickers** [comment]
Notes from triage:
* FromSql in general should probably continue to work on a single entity. @divega to file an issue for an aggregate-friendly version.
  * Knowing the columns to expect together with order or aliases that should be used is non-trivial.
* For 3.0, this will continue to throw, although likely with a different error message.
* This is related to [load patterns](#2953)

**Comment by AndriySvyryd** [comment]
Related to https://github.com/aspnet/EntityFrameworkCore/issues/14497

**Comment by ajcvickers** [comment]
Closing as this is no longer something we intend to implement.
