### ISSUE TITLE
EF.exe migration script failed to load 'System.Interactive.Async"

### ISSUE THREAD

**Issue by e88z4** [dotnet/efcore#14603]
Hi, 

I am trying to generate migration script using ef.exe from Entity Framework Core 2.2.1 project targeting .net 4.6.1.

When invoking ef.exe, I got the following exception below.

Using assembly 'AnnuityDataProcessor'.
Using startup assembly 'AnnuityDataProcessor'.
Using application base 'C:\tfs\uk_sloc_annuitydataapplication\AnnuityDataProcessor\bin\Debug_Localhost'.
Using working directory 'C:\tfs\uk_sloc_annuitydataapplication\AnnuityDataProcessor'.
Using root namespace 'AnnuityDataProcessor'.
Using project directory 'C:\tfs\uk_sloc_annuitydataapplication\AnnuityDataProcessor'.
Using configuration file '.\bin\Debug_Localhost\AnnuityDataProcessor.exe.config'.
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider...
Finding IWebHost accessor...
No CreateWebHostBuilder(string[]) method was found on type 'AnnuityDataProcessor.Program'.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'AnnuityDataDatabaseContext'.

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.Fi
leLoadException: Could not load file or assembly 'System.Interactive.Async, Version=3.0.3000.0, Culture=neutral, PublicK
eyToken=94bc3704cddfc263' or one of its dependencies. The located assembly's manifest definition does not match the asse
mbly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.TryAddCoreServices()
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.ApplyServices(IDbContextOptions options, ServiceCollec
tion services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_0.<GetOrAdd>b__2(Int64 k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at AnnuityDataProcessor.Model.EntityFramework.AnnuityDataDatabaseContext..ctor() in C:\tfs\uk_sloc_annuitydataapplica
tion\AnnuityDataProcessor\Model\EntityFramework\AnnuityDataDatabaseContext.cs:line 24
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCache
d, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark
& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.ScriptMigration(String fromMigration, String to
Migration, Boolean idempotent, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScriptMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Exception has been thrown by the target of an invocation.
```

### Steps to reproduce
From powershell executed ef.exe by the following command:
PS C:\tfs\uk_sloc_annuitydataapplication\AnnuityDataProcessor> C:\tfs\uk_sloc_annuitydataapplication\packages\Microsoft.
EntityFrameworkCore.Tools.2.1.3\tools\net461\any\ef migrations script --assembly .\bin\Debug_Localhost\AnnuityDataProces
sor.exe --verbose -i

### Further technical details
I checked my app.config to ensure the dependent assembly is added with the correct version:

      <dependentAssembly>
        <assemblyIdentity name="System.Interactive.Async" publicKeyToken="94bc3704cddfc263" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.2.0.0" newVersion="3.2.0.0" />
      </dependentAssembly>

Can somebody help me with this issue? Did I do something wrong?

**Comment by ajcvickers** [comment]
@e88z4 Getting assembly conflicts like this is quite common when using .NET Framework and various "core" packages. Please follow up on the corefx repo where there is [an issue discussing the general problem](https://github.com/dotnet/corefx/issues/33643) and where there will hopefully be some guidance on good ways to deal with it.
