### ISSUE TITLE
Password containing " breaks Scaffold-DbContext

### ISSUE THREAD

**Issue by ITRasmus** [dotnet/efcore#14664]
During Scaffold-DbContext from package Manager Console, if the he password contains " it gives the below error. 
I removed the " and the error went away.

```
Exception message: Format of the initialization string does not conform to specification starting at index 83.
Stack trace:

The EF Core tools version '2.1.0-rtm-30799' is older than that of the runtime '2.2.1-servicing-10028'. Update the tools for the latest features and bug fixes.
System.ArgumentException: Format of the initialization string does not conform to specification starting at index 83.
   at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue)
   at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms)
   at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at Microsoft.EntityFrameworkCore.SqlServer.Scaffolding.Internal.SqlServerDatabaseModelFactory.Create(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, String namespace, String language, String contextDir, String contextName, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)

```

### Steps to reproduce

Adding a " to the password in the database connection.

Scaffold-DbContext 'Server=MyCloudDatabase.database.windows.net;Database=SecretDatabase;User ID=TheSecretUser;Password=SomeSecretPasswordContaining";Trusted_Connection=False;Encrypt=True;' Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models

### Further technical details
EF Core version: 2.2.1
Database Provider: ?
Operating system: Windows 10 Enterprise
IDE: Visual Studio 2017 15.8.9

**Comment by ErikEJ** [comment]
Have you tried to escape the " with ` ?

**Comment by ITRasmus** [comment]
It stills gives the same error.

**Comment by bricelam** [comment]
I think this requires [ADO.NET quoting or escaping](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/connection-strings) which may also require PowerShell escaping.

Try something like this:

    Scaffold-DbContext ‘Password=PasswordWith””’

**Comment by bricelam** [comment]
Or

    Scaffold-DbContext “Password=‘PasswordWith`”’”

**Comment by bricelam** [comment]
Or even

    $password = ‘PasswordWith”’
    Scaffold-DbContext “Password=‘$password’”

**Comment by bricelam** [comment]
Looks like that doc doesn’t say it, but you escape ADO.NET quotes by using two quotes (like SQL and VB)

**Comment by yaxum** [comment]
hmm!.. I tried to add quotes but I got this error..
I used the example: 'Password="PasswordWith"""'

Scaffold-DbContext : A positional parameter cannot be found that accepts argument 'Microsoft.EntityFrameworkCore.SqlServer'.
At line:1 char:1
