### ISSUE TITLE
Default date value fails for MySQL

### ISSUE THREAD

**Issue by rbluethl** [dotnet/efcore#14705]
Hey folks! We're using both SQL Server and MySQL (MariaDB) depending on the customer's preference. We reverse engineered our model from an SQL Server database, and a DATE column of a specific table was generated as follows: `entity.Property(e => e.Date).HasDefaultValueSql("(getdate())");`. This is set in the OnModelCreating method of our DbContext. Since `getdate()` is an SQL Server specific method, I wanted to ask if I can achieve the same thing in MySQL. It doesn't seem very reasonable to me to have implementation specific code in this method. When I try to call `Database.Migrate()` on the MySQL instance, it fails with the following exception:

```
Exception message: MySql.Data.MySqlClient.MySqlException: 'Function or expression '`getdate`()' cannot be used in the DEFAULT clause of `DATE`'
Stack trace:    at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet)
   at MySql.Data.MySqlClient.MySqlDataReader.<ReadFirstResultSetAsync>d__94.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<CreateAsync>d__93.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySqlConnector.Core.TextCommandExecutor.<ExecuteReaderAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.<ExecuteNonQueryAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at DataAccess.Common.EntityFrameworkDatabaseGateway.PerformMigration() in C:\Users\ronald.bluethl\Documents\dev\NETx.BMS.Platform\nxaToolbox\DataAccess\Common\EntityFrameworkDatabaseGateway.cs:line 21
   at DataAccess.Test.EntityFrameworkDatabaseGatewayTest.PerformMySqlMigration() in C:\Users\ronald.bluethl\Documents\dev\NETx.BMS.Platform\nxaToolbox\DataAccess.Test\EntityFrameworkDatabaseGatewayTest.cs:line 49
```

Now I know why this is happening, but I don't really understand why there are SQL Server specific details in this code above. Is there another approach to provide default values regardless of the underlying database connection? Isn't there an abstraction to achieve this?

### Further technical details
EF Core version: 2.2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer AND Pomelo.EntityFrameworkCore.MySql
Operating system: Windows 10 Pro 64bit
IDE: Visual Studio 2017 15.9.6

**Comment by ajcvickers** [comment]
@rbluethl The short answer is that migrations are provider-specific. Most of the code is the same, but where provider-specific features or syntax are used, then the migration is specific to the provider. There are [various ways of dealing with this outlined in the documentation](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers).

In general, EF Core does not attempt to fully abstract the data store from the application. It instead provides common patterns and abstractions that can be used with different stores while still providing access to underlying store-specific functionality.
