### ISSUE TITLE
If username contain Apostrophe, SQlite throws Syntax error

### ISSUE THREAD

**Issue by Shivashankar-N** [dotnet/efcore#14979]
Describe what is not working as expected.

While trying to initialize Sqlite connection from UWP application where the logged in user name contains Apostrophe (Ex O’Neil), SQLite throws an exception. This problem is noticed in SQlite 1.1.2 – 1.1.6. 
We can see the latest version of SQlite works as expected. But to consume this, the minimum windows build version should be 16299. Our UWP application should support older version of Windows, so our application is targeted to Windows build 14393. So, upgrading to newer version is not feasible for us.
Exception message:
Stack trace:
2018-10-23 12:12:53:6286    Type: Critical  Id: 500 'App Message : '', Message : 'SQLite Error 1: 'near "xxx": syntax error'.' InnerException : '', StackTrace : '   at Microsoft.Data.Sqlite.Interop.MarshalEx.ThrowExceptionForRC(Int32 rc, Data.Sqlite.Interop.Sqlite3Handle db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(Data.CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.Data.Sqlite.Utilities.DbConnectionExtensions.ExecuteNonQuery(Data.Common.DbConnection connection, String commandText, Int32 timeout)
   at Microsoft.Data.Sqlite.Interop.NativeMethods.OnLoad()
   at Microsoft.Data.Sqlite.Interop.NativeMethods.get_Sqlite3()
   at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(String filename, Data.Sqlite.Interop.Sqlite3Handle& ppDb, Int32 flags, String vfs)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.<>c.<OpenConnection>b__10_0(EntityFrameworkCore.Infrastructure.DatabaseFacade database)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__2<Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade>.<Execute>b__2_0(Action<Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade>,Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade> s)
   at System.Func<System.Object,System.Boolean>.Invoke(Object arg)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.OpenConnection(EntityFrameworkCore.Infrastructure.DatabaseFacade databaseFacade)

### Steps to reproduce
Two samples are attached to this ticket.
1.	EF_Test – UWP application using Sqlite 1.1.2. (Problem is noticed in this version)
2.	EF_V2.2_Test – UWP application using SQlite 2.2 (Work’s without error)

### Further technical details
EF Core version: 1.1.2
Database Provider: (e.g. Microsoft.EntityFrameworkCore.Sqlite)
Operating system: Windows 10.
IDE: (e.g. Visual Studio 2017 15.9)
[EF_Test.zip](https://github.com/aspnet/EntityFrameworkCore/files/2950845/EF_Test.zip)
[EF_V2.2_Test.zip](https://github.com/aspnet/EntityFrameworkCore/files/2950846/EF_V2.2_Test.zip)

**Comment by ajcvickers** [comment]
@Shivashankar-N This should no longer be an issue with newer versions of EF Crore. Please try with 2.1 or 2.2.

**Comment by Shivashankar-N** [comment]
@ajcvickers  You are right. This problem is not noticed in the new version. But like I mentioned in the issue, application supporting older Windows build versions like 14393 cannot upgrade to 2.1 . I think all version where the problem is not noticed starting from 2.0, supports minimum target version of 16299. Because of the support for customer running on older Windows build,we have to target our app to build 14393 and updating to latest EFCore.Sqlite is not a possible solution for us. 

Is there any work around of hotfix available for older version 1.1.2 which we use?

**Comment by ajcvickers** [comment]
@Shivashankar-N Unfortunately, no. All of this interaction with SQLite was changed between the 1.x releases and the 2.x releases.
