### ISSUE TITLE
Composite ForeignKey type validation doesn't take property conversions into account.

### ISSUE THREAD

**Issue by fmauNeko** [dotnet/efcore#15058]
Hello,

Relations using composite keys with different property types are throwing because of type mismatch even though correct conversions are defined on the properties themselves.

It would be great if defined conversions on composite key properties could be taken into account, in this case I'm joining a legacy table which has a `string` ID, with a new one with has an `int` ID.

```
Exception message: System.InvalidOperationException: The types of the properties specified for the foreign key {'RefAgence', 'Idlots'} on entity type 'LosTables' do not match the types of the properties in the principal key {'RefAgence', 'NoLot'} on entity type 'Lots'.
Stack trace:
Unhandled Exception: System.InvalidOperationException: The types of the properties specified for the foreign key {'RefAgence', 'Idlots'} on entity type 'LosTables' do not match the types of the properties in the principal key {'RefAgence', 'NoLot'} on entity type 'Lots'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKey.AreCompatible(IReadOnlyList`1 principalProperties, IReadOnlyList`1 dependentProperties, EntityType principalEntityType, EntityType dependentEntityType, Boolean shouldThrow)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKey.AreCompatible(EntityType principalEntityType, EntityType dependentEntityType, MemberInfo navigationToPrincipal, MemberInfo navigationToDependent, IReadOnlyList`1 dependentProperties, IReadOnlyList`1 principalProperties, Nullable`1 unique, Nullable`1 required, Boolean shouldThrow)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceReferenceBuilderBase..ctor(InternalRelationshipBuilder builder, ReferenceReferenceBuilderBase oldBuilder, Boolean inverted, Boolean foreignKeySet, Boolean principalKeySet, Boolean requiredSet)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceReferenceBuilder`2.HasForeignKey[TDependentEntity](Expression`1 foreignKeyExpression)
   at test.ACDVContext.<>c.<OnModelCreating>b__11_1(EntityTypeBuilder`1 entity) in /tmp/test/Program.cs:line 80
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity[TEntity](Action`1 buildAction)
   at test.ACDVContext.OnModelCreating(ModelBuilder modelBuilder) in /tmp/test/Program.cs:line 65
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.Include[TEntity,TProperty](IQueryable`1 source, Expression`1 navigationPropertyPath)
   at test.Program.Main(String[] args) in /tmp/test/Program.cs:line 94
```

### Steps to reproduce
```sql
CREATE TABLE `lots` (
  `RefAgence` varchar(10) NOT NULL DEFAULT '',
  `No_Lot` varchar(10) NOT NULL DEFAULT '',
  PRIMARY KEY (`RefAgence`,`No_Lot`),
  KEY `No_Lot` (`No_Lot`),
  KEY `lots_RefAgence_index` (`RefAgence`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='Liste des biens (Lots)'

CREATE TABLE `los_tables` (
  `RefAgence` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `IDLots` int(11) NOT NULL,
  PRIMARY KEY (`RefAgence`,`IDLots`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```

```c#
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace test
{
    [Table("lots")]
    public partial class Lots
    {
        [Column(TypeName = "varchar(10)")]
        public string RefAgence { get; set; }

        [Column("No_Lot", TypeName = "varchar(10)")]
        public string NoLot { get; set; }

        public LosTables LosTable { get; set; }
    }

    [Table("los_tables")]
    public partial class LosTables
    {
        [Column(TypeName = "varchar(10)")]
        public string RefAgence { get; set; }

        [Column("IDLots", TypeName = "int(11)")]
        public int Idlots { get; set; }
    }

    public partial class ACDVContext : DbContext
    {
        public ACDVContext()
        {
        }

        public ACDVContext(DbContextOptions<ACDVContext> options)
            : base(options)
        {
        }

        public virtual DbSet<LosTables> LosTables { get; set; }
        public virtual DbSet<Lots> Lots { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseMySql("xxx");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<LosTables>(entity =>
            {
                entity.HasKey(e => new { e.RefAgence, e.Idlots })
                    .HasName("PRIMARY");
                
                entity.Property(e => e.Idlots)
                    .HasConversion<string>();
            });

            modelBuilder.Entity<Lots>(entity =>
            {
                entity.HasKey(e => new { e.RefAgence, e.NoLot })
                    .HasName("PRIMARY");

                entity.HasIndex(e => e.NoLot)
                    .HasName("No_Lot");

                entity.HasIndex(e => e.RefAgence)
                    .HasName("lots_RefAgence_index");

                entity.Property(e => e.RefAgence).HasDefaultValueSql("''");

                entity.Property(e => e.NoLot).HasDefaultValueSql("''");

                entity.HasOne(l => l.LosTable)
                    .WithOne()
                    .HasPrincipalKey<Lots>(l => new { l.RefAgence, l.NoLot })
                    .HasForeignKey<LosTables>(lt => new { lt.RefAgence, lt.Idlots });
            });
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var context = new ACDVContext();

            var lot = context.Lots
                .Include(l => l.LosTable)
                .Where(l => l.RefAgence == "061810001" && l.NoLot == "12");
        }
    }
}
```

### Further technical details
EF Core version: 2.2.3
Database Provider: Pomelo.EntityFrameworkCore.MySql 2.2.0
Operating system: Arch Linux / Windows 10
IDE: Visual Studio Code 1.32.3

**Comment by ajcvickers** [comment]
@fmauNeko Currently, value conversions are not designed to compensate for differences in the types used in the .NET model. That is, foreign key types must still be compatible with principal key types in the model. Indeed, by convention we propagate the converter from the PK to the FK.

Leaving open to discuss in triage whether this is something we want to support in the future.

**Comment by ajcvickers** [comment]
Triage: We discussed this and it's not somewhere we're planning to take value conversions. Firstl, it doesn't seem like a great idea to have a domain model where the values don't match like this. Second, the implementation would have considerable complexity for a very corner case.
