### ISSUE TITLE
System.InvalidOperationException: Collection was modified; enumeration operation may not execute. at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()

### ISSUE THREAD

**Issue by MgSam** [dotnet/efcore#15061]
I'm occasionally getting the below exception. All my code is doing is the following:

```
using (var context = new DbContext())
{
     context.Update(entity); //entity is a disconnected entity 
     await context.SaveChangesAsync(token).ConfigureAwait(false);
}
```

This is happening in a multi-threaded environment, but each thread creates its own context independently. Is there some shared state between instances of DbContext?

```
Exception message:
System.InvalidOperationException: Collection was modified; enumeration operation may not execute
Stack trace:
at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.SnapshotFactoryFactory.SnapshotCollection(IEnumerable`1 collection)
at lambda_method(Closure , InternalEntityEntry )
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.RelationshipsSnapshot..ctor(InternalEntityEntry entry)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.EnsureRelationshipSnapshot()
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntrySubscriber.SnapshotAndSubscribe(InternalEntityEntry entry)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node, Boolean force)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode node, TState state, Func`3 handleNode)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode node, TState state, Func`3 handleNode)
at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)

```

### Further technical details
EF Core version: 2.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: VS 2017

**Comment by ajcvickers** [comment]
@MgSam This stack trace indicates that a collection on an entity is being modified while EF is iterating over it. Is it possible that the same entity instances are being shared by multiple threads, even though each of these is using a different context instance?

**Comment by MgSam** [comment]
Thanks. Yes, that is what is happening, though I'm attempting to use an `AsyncLock` from Nito.AsyncEx to guard against it happening concurrently. Seems something isn't working the way I'm expecting.

To give a little more background, imagine a class `Foo` which has many `Bar`s. Each `Bar` is getting updated in its own thread. I'm locking on `Foo` prior to doing the update I illustrated above.

Would making a clone of `Foo` for each thread resolve this? Or am I still going to run into trouble because each `Bar` on different threads has a `Foo` with the same PK?

**Comment by ajcvickers** [comment]
@MgSam It's hard to make concrete statements without knowing your domain model and application constraints, but some thoughts are:
* Locking for all the time that EF may be using the entity instance is going to be hard, especially without introducing the potential for deadlock.
* Cloning the object graph before using it with EF seems like a reasonable approach. This would also need locking, but the locking can be localized to the cloning, making it easier and safer to implement.
* It hard to know whether cloning will cause issues, but if it does, then it likely means that these are real issues of multiple conflicting updates, for which the application must have a plan regardless of whether EF is doing the updates or not.
* All of this would be simpler if the threads were not sharing the same object graphs. Of course, this is an architectural change, but I mention it because avoiding concurrent accesses in the first place though using different object instances in different units of work can be a lot cleaner than using locking further down the line.

Closing this since this is not fundamentally an EF issue.
