### ISSUE TITLE
SaveChangesAsync should not wrap OperationCancellationException with DbUpdateException

### ISSUE THREAD

**Issue by maxcherednik** [dotnet/efcore#15074]
Cancellation contract of async methods is broken.

If a method: `SaveChangesAsync(Boolean, CancellationToken)` is called and then cancelled, I would expect to catch an 'OperationCanceledException'. Instead, it throws `DbUpdateException` with the TaskCanceledException as an inner exception.

According to the [documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.savechangesasync?view=efcore-2.1) it was designed to be so. But is it a good design decision?

```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: A severe error occurred on the current command.  The results, if any, should be discarded.
Operation cancelled by user.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__32.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<ExecuteImplementationAsync>d__31`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<ExecuteImplementationAsync>d__31`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__79.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__77.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DbContext`2.<SaveChangesAsync>d__8.MoveNext()
```

**Comment by roji** [comment]
Note the same question at the ADO.NET/SqlClient level: https://github.com/dotnet/corefx/issues/9245. I do agree that in general cancellations should be raised as OperationCanceledExceptions rather than domain-specific DbUpdateException/DbException/whatever.

**Comment by roji** [comment]
Notes:
* SaveChangesAsync does throw TaskCanceledException when passed a canceled token - DbUpdateException is only thrown when the cancellation occurs later.
* Query and ExecuteSqlRawAsync simply bubble up the original ADO.NET provider exception, whatever that is. In SqlClient's case that's SqlException which is bad, but that's https://github.com/dotnet/SqlClient/issues/26
* Cosmos only wraps CosmosException with a DbUpdateException, as opposed to Relational which wraps everything. So it already bubbles up OperationCanceledException, but we may want to consider wrapping other exceptions as well, /cc @AndriySvyryd.

**Comment by AndriySvyryd** [comment]
>  but we may want to consider wrapping other exceptions as well

Makes sense

**Comment by roji** [comment]
Opened #25631 to track wrapping other exception types for Cosmos

**Comment by roji** [comment]
@AndriySvyryd @ajcvickers we may want to document this as a low-impact breaking change - if anyone's catching DbUpdateException with the expectation that cancellations are included there, that code would no longer work.

**Comment by janseris** [comment]
Hi, I am afraid that this issue is still there. 
When inserting items into database and calling SaveChangesAsync with cancellation token and the token is activated by user to cancel the request, SqlException with Class 11 is fired instead of OperationCancelledException.

This is also seen in this comment which shows how to properly catch the token cancellation:

https://github.com/dotnet/SqlClient/issues/26#issuecomment-723307003

I see it tracked also here: https://github.com/dotnet/SqlClient/issues/26 but there is no resolution of this issue.

Are there any plans for this small breaking change or do you suggest any solution, for example using this DbCommandInterceptor?
https://github.com/dotnet/SqlClient/issues/26#issuecomment-723508289 which looks nice but might have some unexpected drawbacks?

Thank you
