### ISSUE TITLE
NullReferenceException when using LINQ and a variable

### ISSUE THREAD

**Issue by gojanpaolo** [dotnet/efcore#15095]
Why does the following throw:
```
Blog blog = null;
ctx.Post.Where(p => p.Blog == blog).ToList();
```

but `ctx.Post.Where(p => p.Blog == null).ToList();` does not throw 

Thank you! :)

---

```
Exception: System.NullReferenceException : Object reference not set to an instance of an object.

StackTrace:
at lambda_method(Closure , Blog )
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrPropertyGetter`2.GetClrValue(Object instance)
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypeMappedPropertyRelationalParameter.AddDbParameter(DbCommand command, Object value)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBase.AddDbParameter(DbCommand command, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.CreateCommand(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

```c#
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using Xunit;

namespace TestLibrary
{
    public class Tests : IDisposable
    {
        private readonly SqliteConnection _connection;
        private readonly DbContextOptions _options;

        public Tests()
        {
            _connection = new SqliteConnection("datasource=:memory:");
            _connection.Open();

            _options = new DbContextOptionsBuilder()
                .UseSqlite(_connection)
                .Options;

            using (var ctx = new Context(_options))
            {
                ctx.Database.EnsureCreated();
                ctx.Add(new Post { Blog = new Blog() });
                ctx.SaveChanges();
            }
        }

        public void Dispose()
        {
            using (var ctx = new Context(_options))
                ctx.Database.EnsureDeleted();
            _connection.Dispose();
        }

        [Fact]
        public void Throws()
        {
            Blog blog = null;
            using (var ctx = new Context(_options))
                ctx.Post.Where(p => p.Blog == blog).ToList();
        }

        [Fact]
        public void Does_not_throw()
        {
            using (var ctx = new Context(_options))
                ctx.Post.Where(p => p.Blog == null).ToList();
        }
    }
    public class Context : DbContext
    {
        public Context(DbContextOptions options) : base(options) { }
        public DbSet<Post> Post { get; set; }
        public DbSet<Blog> Blog { get; set; }
    }
    public class Post
    {
        public int PostId { get; set; }
        public Blog Blog { get; set; }
    }
    public class Blog
    {
        public int BlogId { get; set; }
    }
}

```

### Further technical details
EF Core version: 2.2.3
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Win 10
IDE: Visual Studio 2019 16.0.0 RC2

**Comment by ajcvickers** [comment]
Note for triage: I was able to repro this.

**Comment by maumar** [comment]
work is tracked by https://github.com/aspnet/EntityFrameworkCore/issues/15855
