### ISSUE TITLE
 can't tranlate datetime.ticks on linq to sql

### ISSUE THREAD

**Issue by chenzhe014** [dotnet/efcore#15161]
I have a sort in my linq to sql 

```
 var list = await queryable.Include(p => p.RefundDetails).Skip((requestDto.PageIndex - 1) * 
                requestDto.PageSize).Take(requestDto.PageSize)
                   .OrderBy(r => (r.RefundStatus == 1 ? 1 : -1))
                   .ThenBy(r => r.SumbitTime.Ticks * (r.RefundStatus == 1 ? 1 : -1))
```
I tried this code on linq. it worked. but it can not worked on linq to sql.
then I replaced `r.SumbitTime.Ticks` with `r.Id`. it worked .

Exception

Object reference not set to an instance of an object.

StackTrace

`   at lambda_method(Closure , AnonymousObject )
   at System.Linq.Internal.Lookup`2.CreateForJoinAsync(IAsyncEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer, CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Lookup.cs:line 301
   at System.Linq.AsyncEnumerable.JoinAsyncIterator`4.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Join.cs:line 152
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 98
   at System.Linq.AsyncEnumerable.Aggregate_[TSource,TAccumulate,TResult](IAsyncEnumerable`1 source, TAccumulate seed, Func`3 accumulator, Func`2 resultSelector, CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Aggregate.cs:line 120
   at System.Linq.OrderedAsyncEnumerable`2.Initialize(CancellationToken cancellationToken)
   at System.Linq.OrderedAsyncEnumerable`2.Initialize(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\OrderedAsyncEnumerable.cs:line 110
   at System.Linq.OrderedAsyncEnumerable`2.Initialize(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\OrderedAsyncEnumerable.cs:line 110
   at System.Linq.OrderedAsyncEnumerable`2.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\OrderedAsyncEnumerable.cs:line 79
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 98
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Select.cs:line 106
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 98
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.IncludeCollectionAsync[TEntity,TRelated,TElement](Int32 includeId, INavigation navigation, INavigation inverseNavigation, IEntityType targetEntityType, IClrCollectionAccessor clrCollectionAccessor, IClrPropertySetter inverseClrPropertySetter, Boolean tracking, TEntity entity, Func`1 relatedEntitiesFactory, Func`3 joinPredicate, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler._IncludeAsync[TEntity](QueryContext queryContext, TEntity entity, Object[] included, Func`5 fixup, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.TaskLiftingExpressionVisitor._ExecuteAsync[T](IReadOnlyList`1 taskFactories, Func`2 selector)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.AsyncSelectEnumerable`2.AsyncSelectEnumerator.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.Aggregate_[TSource,TAccumulate,TResult](IAsyncEnumerable`1 source, TAccumulate seed, Func`3 accumulator, Func`2 resultSelector, CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Aggregate.cs:line 120
   at FanjiaPaymentsGroup.EFCore.Repository.RefundApplicationRepository.QueryAsync(RefundQueryRequestDto requestDto) in E:\Fanjiaworkspace\FanjiaPaymentsGroup\FanjiaPaymentsGroup.EFCore\Repository\RefundApplicationRepository.cs:line 57`

**Comment by smitpatel** [comment]
@chenzhe014 - Are you sure you want to do Skip/Take before OrderBy-ThenBy?

**Comment by chenzhe014** [comment]
> @chenzhe014 - Are you sure you want to do Skip/Take before OrderBy-ThenBy?

i'm so sorry . That's the problem.

**Comment by chenzhe014** [comment]
> @chenzhe014 - Are you sure you want to do Skip/Take before OrderBy-ThenBy?

i put Skip/Take after OrderBy-ThenBy ...problems still remain
