### ISSUE TITLE
Getting: Parameter or variable 'column' has invalid data type. when using ValueGeneratedOnAdd

### ISSUE THREAD

**Issue by ctodd1** [dotnet/efcore#15175]
I have a table with a nvarchar column that I want to update via a trigger after insert. I have a section of code that configures the column to be ValueGeneratedOnAdd. I get: 

> Parameter or variable 'column' has invalid data type

 when inserting more than 3 items at a time. I have attached sample code that illustrates the problem. The service base database included in the attached project contains 2 tables and 2 triggers. I was testing whether or not a composite key was a factor and it didn't appear to be. The triggers update a column in each table that I'm configuring to be ValueGeneratedOnAdd.

### Exception:
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Parameter or variable 'col1' has an invalid data type.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at issue_with_efcore_rodeo.Module1.Main() in D:\TFS01\Developer\ctodd\issue_with_efcore_rodeo\issue_with_efcore_rodeo\Module1.vb:line 24

### Steps to reproduce
Run the attached project. ModelExt.vb contains my ValueGeneratedOnAdd code. The code is pretty straight-forward. I would suggest changing the # of iterations of the inserts. If it has more than 3 inserted entities at once, it errors. 

Operating system: 
IDE: Visual Studio 2017 15.9.10
EF Core: 2.2.3

[issue_with_efcore_rodeo.zip](https://github.com/aspnet/EntityFrameworkCore/files/3013608/issue_with_efcore_rodeo.zip)

**Comment by ajcvickers** [comment]
Note for triage: This is interesting because the specified column name:
```VB
a.Property(Function(b) b.col1).HasColumnType("int(10, 0)").IsRequired()
```
is not something that is understood by SQL Server. However, this doesn't matter if EF isn't using it, which is the case for not batched updates. When batching happens, the name is used, and an exception is thrown. This isn't a very intuitive thing to happen.

@ctodd1 Any reason you are specifying types like `int(10, 0)` for SQL Server?

**Comment by ctodd1** [comment]
I have a tool I wrote that builds my ef core code and when it builds the code outlined above, it combines the data_type, numeric_precision and numeric_scale returned from SQL Server. I just didn't realize it was wrong until now. Thanks!

**Comment by ctodd1** [comment]
Everything is working great now, so I will close the ticket. @ajcvickers, thank you for your help!!
