### ISSUE TITLE
Migration for Xamarin project, unable to use FileSystem

### ISSUE THREAD

**Issue by Tristan-gu** [dotnet/efcore#15201]
I would like to use Xamarin.essentials.FileSystem to initialize insaide the DBContext class the database Path, and make a migration.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'TestDB.Connect.DataBase.DBContext.DBBaseTestDB' threw an exception. ---> Xamarin.Essentials.NotImplementedInReferenceAssemblyException: This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.
   at Xamarin.Essentials.FileSystem.get_PlatformAppDataDirectory() in D:\a\1\s\Xamarin.Essentials\FileSystem\FileSystem.netstandard.cs:line 12
   at TestDB.Connect.DataBase.DBContext.DBBaseTestDB..cctor() in D:\Xamarin\connect\TestDB.Connect\TestDB.Connect.DataBase\DBContext\Base\DBBaseTestDB.cs:line 22
   --- End of inner exception stack trace ---
   at TestDB.Connect.DataBase.DBContext.DBBaseTestDB..ctor() in D:\Xamarin\connect\TestDB.Connect\TestDB.Connect.DataBase\DBContext\Base\DBBaseTestDB.cs:line 30
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Exception has been thrown by the target of an invocation.
```

### Steps to reproduce
I just want to create a DBContext which affects the databasePath automatically with Xamarin.essentials FileSystem.AppDataDirectory.
But I have an error when I want to create the first migration with this command 
Add-Migration InitialCreate 

```c#
public static readonly string DB_PATH = FileSystem.AppDataDirectory;
```

### Further technical details
EF Core version: latest pre-release
Database Provider: Microsoft.EntityFrameworkCore.Sqlite.Core
Operating system: Windows
IDE: VS 2019

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment]
@Tristan-gu Moved to https://github.com/xamarin/Essentials/issues/754
