### ISSUE TITLE
SqLite : System.InvalidOperationException

### ISSUE THREAD

**Issue by Cataurus** [dotnet/efcore#15215]
II wanted to upgrade a working example project from EntityFrameworkCore version 2.0.0 to version 2.2.0 and got this error during execution.

```
System.InvalidOperationException
  HResult=0x80131509
  Nachricht = Must add values for the following parameters: @__a_0_ID, @__b_1_ID
  Quelle = Microsoft.Data.Sqlite
  Stapelüberwachung:
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Bsp1.Program.Main(String[] args) in D:\Programmierung\Projekte\C#\Datenbank\Abfrageprobleme\SampleSqLiteException\Program.cs:line 77
```

### Steps to reproduce

```c#
                Auto a = (from d in dbSQlite.Autos
                          where
                            d.ID == k
                          select
                            d).First();

                Auto b = (from d in dbSQlite.Autos
                          where
                            d.ID == k + 1
                          select
                            d).First();

                var equalQuery = (from 
                                    d in dbSQlite.EqualAutos
                                where
                                    (d.Auto == a &&
                                    d.AnotherAuto == b) ||
                                    (d.Auto == b &&
                                    d.AnotherAuto == a)
                                 select
                                    d).ToList();
```

[ProjectSolution.zip](https://github.com/aspnet/EntityFrameworkCore/files/3026435/ProjectSolution.zip)

### Further technical details
EF Core version: up 2.2.0
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: 
IDE: Visual Studio 2019 Preview 16.0.0 4.4

**Comment by divega** [comment]
@smitpatel to provide a workaround.

**Comment by smitpatel** [comment]
```C#
var equalQuery = (from 
                                    d in dbSQlite.EqualAutos
                                where
                                    (d.Auto.Id == a.Id &&
                                    d.AnotherAuto.Id == b.Id) ||
                                    (d.Auto.Id == b.Id &&
                                    d.AnotherAuto.Id == a.Id)
                                 select
                                    d).ToList();
```
