### ISSUE TITLE
System.MissingMethodException occurs on DbSet<T>#ToArray() or #ToList()

### ISSUE THREAD

**Issue by siketyan** [dotnet/efcore#15213]
When I try to call DbSet<T>#ToArray() or #ToList(), the exception below occured.
There is no ASP.NET Core configuration, only standalone .NET Core console application.
Also I found the method really existed until version 2.1.8, but since 2.2.0 it has been deleted.
This does not occur on #ToArrayAsync() or #ToListAsync().

```
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'System.Reflection.MethodInfo Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.get_SelectAsyncMethod()'.
  Source=Microsoft.EntityFrameworkCore.Relational
  StackTrace:
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at EFTest.Program.Main() in d:\Documents\Visual Studio 2017\Projects\EFTest\Program.cs:line 35
```

### Steps to reproduce
Type `dotnet run` to reproduce.

```c#
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace EFTest
{
    public class TestModel
    {
        [Key]
        public long Id { get; set; }

        public string Value { get; set; }
    }

    public class SqlContext : DbContext
    {
        public DbSet<TestModel> TestModels { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder options)
        {
            options.UseMySQL(
                "server=localhost;userid=modelized;password=modelized;database=modelized;"
            );

            base.OnConfiguring(options);
        }
    }

    public class Program
    {
        public static void Main()
        {
            using (var context = new SqlContext())
            {
                context.TestModels.ToArray();
            }
        }
    }
}
```

### Further technical details
.NET Core version: 2.2
EF Core version: 2.2.3 (This occurs on >= 2.2.0)
Database Provider: MySql.Data.EntityFrameworkCore 8.0.15
Operating system: Windows 10 Pro Version 1809 Build 17763.379 on x86_64
IDE: Visual Studio Enterprise 2017 Version 15.9.10

**Comment by Needleski** [comment]
I had this happen on an old project.  For me the issue was a reference to Microsoft.EntityFrameworkCore.Relational.  Make sure its updated to >= 2.2.0.

**Comment by Siketyan** [comment]
Thank you for the reply @Needleski .
I tried it out, then the problem was solved.

But isn't it a problem of NuGet dependency configuration?
The problem also can be reproduced after installed Microsoft.EntityFrameworkCore package newly.

**Comment by Siketyan** [comment]
I'm sorry, I found that is a problem of MySql.Data.EntityFrameworkCore package, not EFCore.

**Comment by sayoojt** [comment]
I had the same issue, but integration with Oracle, sorted out with what @Needleski .  added nuget for Microsoft.EntityFrameworkCore.Relational.
