### ISSUE TITLE
Filtering by owned entity attribute using SQLite is evaluated in memory

### ISSUE THREAD

**Issue by VictorIranzo** [dotnet/efcore#15255]
When a filter is applied to an attribute that belongs to an owned entity and the **QueryClientEvaluationWarning** is active, an error is thrown. This happens using as a provider an SQLite Database in memory. The issue is not reproduced using other providers as SQLServer or the InMemory provider. 
In the provided example, the exception that appears is:

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Error generated for warning 'Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning: The LINQ expression 'where ([se.MyOwnedEntity]?.Value > Convert(8, Nullable`1))' could not be translated and will be evaluated locally.'. This exception can be suppressed or logged by passing event ID 'RelationalEventId.QueryClientEvaluationWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`1.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, WarningBehavior warningBehavior, TParam arg, Exception exception)
   at Microsoft.EntityFrameworkCore.Internal.RelationalLoggerExtensions.QueryClientEvaluationWarning(IDiagnosticsLogger`1 diagnostics, QueryModel queryModel, Object queryModelElement)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitWhereClause(WhereClause whereClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at IssueEFCore.Program.Main(String[] args)

```

### Steps to reproduce
The issue can be reproduced by executing the following code:
Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
using System;
using System.Globalization;
using System.Linq;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace IssueEFCore
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            using (MyContext context = new MyContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                context.Entities.Add(new Entity()
                {
                    OwnedEntity = new OwnedEntity() { Value = 10M }
                });

                context.SaveChanges();

                Entity entity = context.Entities.Where(se => se.OwnedEntity.Value > 8M).FirstOrDefault();

                Console.WriteLine(entity);
            }
        }
    }

    public class Entity
    {
        public Guid Id { get; set; }
        public OwnedEntity OwnedEntity { get; set; }
    }

    public class OwnedEntity
    {
        public decimal Value { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<Entity> Entities { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // INCLUDE HERE THE CODE OF THE FOLLOWING OPTIONS.

            optionsBuilder.ConfigureWarnings(wacb => wacb.Throw(RelationalEventId.QueryClientEvaluationWarning));
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            EntityTypeBuilder<Entity> entityTypeBuilder = modelBuilder.Entity<Entity>();

            entityTypeBuilder.OwnsOne(e => e.OwnedEntity);
        }
    }
}
```

#### Option 1: 
Using a real SQL Server database providing its connection string:
```c#
optionsBuilder.UseSqlServer(@"Data Source=SERVER;Database=DATABASE;Integrated Security=True;User Id=ID;Password=PASSWORD.;Application Name=APP");
```
The expected behaviour occurs. No error appears because the query can be evaluated in the database.

#### Option 2:
```c#
optionsBuilder.UseInMemoryDatabase("Database");
```
The expected behavior occurs. No error appears because all the database is already in memory.

#### Option 3:
```c#
SqliteConnection connection = new SqliteConnection("Data Source=DATABASE;Mode=Memory;Cache=Shared");
connection.Open();
optionsBuilder.UseSqlite(connection);
```
The mentioned error appears.

### Further technical details
EF Core version: 2.2.3
Database Provider: Microsoft.EntityFrameworkCore.Sqlite 2.2.3
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.6

**Comment by ajcvickers** [comment]
Note for triage: SQLite decimal property.

**Comment by ajcvickers** [comment]
@VictorIranzo The issue here is that SQLite doesn't have a native data type for decimals, which means the values need to be converted to either ints, strings, or doubles to be stored by SQLite. None of these can satisfy both round tripping and ordering semantics. We optimized for round tripping (to preserve data integrity) but that means that ordering (such as the `>` in your query) cannot be evaluated on the server--see #11925.
