### ISSUE TITLE
Using Include will cause Not refrence object even in the new version

### ISSUE THREAD

**Issue by Foroughi** [dotnet/efcore#15274]
As i far as i know this issue has been fixed but by any reason im still getting this

Here is the details : 

`var list = await dbContext.Views.Include(rec => rec.ViewDetails).OrderBy(rec => rec.CreateDateTime).ToListAsync();`

By removing the include section all work fine

And here is the model

```
[Table("Views")]
    public class View : IEntity<Guid>
    {
        #region Properties        

        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        [Required]
        [RegularExpression(@"[0-9]{4}\/[0-9]{2}\/[0-9]{2}")]
        public string RegisterDate { get; set; }

        [Required]
        [RegularExpression(@"[0-9]{2}\:[0-9]{2}")]
        public string RegisterTime { get; set; }

        [Required]
        [RegularExpression(@"[0-9]{2}\:[0-9]{2}")]
        public string CorrectTime { get; set; }
        

        [NotMapped]
        public string RegisterDateTime
        {
            get
            {
                return string.Format("{0} , {1}", this.RegisterDate, this.RegisterTime);
            }
        }

        [Required]
        [RegularExpression(@"[0-9]{4}\/[0-9]{2}\/[0-9]{2}")]
        public string CreateDate { get; set; }

        [Required]
        [RegularExpression(@"[0-9]{2}\:[0-9]{2}")]
        public string CreateTime { get; set; }

        [NotMapped]
        public string CreateDateTime
        {
            get
            {
                return string.Format("{0} , {1}", this.CreateDate, this.CreateTime);
            }
        }

        [Required]
        public int VisitorId { get; set; }

        [Required]
        public Guid CarId { get; set; }

        [Required]
        public int ZoneId { get; set; }
        
        [Required]
        public int MemberShiftId { get; set; }

        #endregion

        #region Navigators

        [ForeignKey("CarId")]
        [InverseProperty("Views")]
        public Car Car { get; set; }

        [ForeignKey("ZoneId")]        
        public Zone Zone { get; set; }


        public virtual ICollection<ViewDetail> ViewDetails { get; set; }

        #endregion

    }

[Table("ViewDetails")]
    public class ViewDetail : IEntity<Guid>
    {
        #region Properties        

        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        [Required]
        public Guid ViewId { get; set; }

        [Required]
        [RegularExpression(@"[0-9]{2}\:[0-9]{2}")]
        public string EndTime { get; set; }

        [Required]
        public int TariffConditionId { get; set; }

        [Required]
        public int TariffConditionLevel { get; set; }

        [Required]
        public bool IsDelayed { get; set; }

        public int Price { get; set; }
        
        #endregion

        #region Navigators

        [ForeignKey("ViewId")]
        [InverseProperty("ViewDetails")]
        public View View { get; set; }
     

        #endregion

    }

```
```
An exception occurred while iterating over the results of a query for context type 'Elit.DAL.DbContexts.ElitDbContext'.
      System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Select.cs:line 106
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 98
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.IncludeCollectionAsync[TEntity,TRelated,TElement](Int32 includeId, INavigation navigation, INavigation inverseNavigation, IEntityType targetEntityType, IClrCollectionAccessor clrCollectionAccessor, IClrPropertySetter inverseClrPropertySetter, Boolean tracking, TEntity entity, Func`1 relatedEntitiesFactory, Func`3 joinPredicate, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler._IncludeAsync[TEntity](QueryContext queryContext, TEntity entity, Object[] included, Func`5 fixup, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.TaskLiftingExpressionVisitor._ExecuteAsync[T](IReadOnlyList`1 taskFactories, Func`2 selector)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.AsyncSelectEnumerable`2.AsyncSelectEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Select.cs:line 106
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 98
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
```

### Further technical details
EF Core version: 2.2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Debian 9
IDE: Vs Code

**Comment by Foroughi** [comment]
Same thing is happening for this code : 

`var list = dbContext.Views.Include(rec => rec.ViewDetails).ToList();`

**Comment by Foroughi** [comment]
Im gonna close this issue as the problem was with OrderBy method. I was trying to order the list based on a Not-Mapped column which seems is not correct. It was better if i got a better error than "Not refrence Object...."
