### ISSUE TITLE
Include :: Exception thrown for multi-level include dotting over one-one navigation into one to many deeper inside the include chain

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#1528]
```
namespace Repro1528
{
    public class Level1
    {
        public int Id1 { get; set; }
        public string Name { get; set; }

        public ICollection<Level2> OneToMany_Required { get; set; }
        public ICollection<Level2> OneToMany_Optional { get; set; }
    }

    public class Level2
    {
        public int Id2 { get; set; }
        public string Name { get; set; }

        public int Level1_Required_Id { get; set; }
        public int? Level1_Optional_Id { get; set; }

        public ICollection<Level3> OneToMany_Required { get; set; }
        public ICollection<Level3> OneToMany_Optional { get; set; }

        public Level1 OneToMany_Required_Inverse { get; set; }
        public Level1 OneToMany_Optional_Inverse { get; set; }
    }

    public class Level3
    {
        public int Id3 { get; set; }
        public string Name { get; set; }

        public int Level2_Required_Id { get; set; }
        public int? Level2_Optional_Id { get; set; }

        public Level2 OneToMany_Required_Inverse { get; set; }
        public Level2 OneToMany_Optional_Inverse { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<Level1> LevelOne { get; set; }
        public DbSet<Level2> LevelTwo { get; set; }
        public DbSet<Level3> LevelThree { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Level1>().Key(e => e.Id1);
            modelBuilder.Entity<Level2>().Key(e => e.Id2);
            modelBuilder.Entity<Level3>().Key(e => e.Id3);

            modelBuilder.Entity<Level1>().Property(e => e.Id1).GenerateValueOnAdd(false);
            modelBuilder.Entity<Level2>().Property(e => e.Id2).GenerateValueOnAdd(false);

            modelBuilder.Entity<Level1>().HasMany(e => e.OneToMany_Required).WithOne(e => e.OneToMany_Required_Inverse).Required(true);
            modelBuilder.Entity<Level1>().HasMany(e => e.OneToMany_Optional).WithOne(e => e.OneToMany_Optional_Inverse).Required(false);

            modelBuilder.Entity<Level2>().Property(e => e.Id2).GenerateValueOnAdd(false);
            modelBuilder.Entity<Level2>().Property(e => e.Id2).GenerateValueOnAdd(false);
            modelBuilder.Entity<Level2>().HasMany(e => e.OneToMany_Required).WithOne(e => e.OneToMany_Required_Inverse).Required(true);
            modelBuilder.Entity<Level2>().HasMany(e => e.OneToMany_Optional).WithOne(e => e.OneToMany_Optional_Inverse).Required(false);

            modelBuilder.Entity<Level3>().Property(e => e.Id3).GenerateValueOnAdd(false);
            modelBuilder.Entity<Level3>().Property(e => e.Id3).GenerateValueOnAdd(false);
        }

        protected override void OnConfiguring(DbContextOptions options)
        {
            options.UseSqlServer(new SqlConnectionStringBuilder { DataSource = ".", InitialCatalog = "Repro1528", MultipleActiveResultSets = true, IntegratedSecurity = true }.ToString());
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

                var l1_01 = new Level1 { Id1 = 1, Name = "L1 01", };
                var l1_02 = new Level1 { Id1 = 2, Name = "L1 02", };
                var l1_03 = new Level1 { Id1 = 3, Name = "L1 03", };
                var l1_04 = new Level1 { Id1 = 4, Name = "L1 04", };
                var l1_05 = new Level1 { Id1 = 5, Name = "L1 05", };
                var l1_06 = new Level1 { Id1 = 6, Name = "L1 06", };
                var l1_07 = new Level1 { Id1 = 7, Name = "L1 07", };
                var l1_08 = new Level1 { Id1 = 8, Name = "L1 08", };
                var l1_09 = new Level1 { Id1 = 9, Name = "L1 09", };
                var l1_10 = new Level1 { Id1 = 10, Name = "L1 10" };

                var l2_01 = new Level2 { Id2 = 1, Name = "L2 01", };
                var l2_02 = new Level2 { Id2 = 2, Name = "L2 02", };
                var l2_03 = new Level2 { Id2 = 3, Name = "L2 03", };
                var l2_04 = new Level2 { Id2 = 4, Name = "L2 04", };
                var l2_05 = new Level2 { Id2 = 5, Name = "L2 05", };
                var l2_06 = new Level2 { Id2 = 6, Name = "L2 06", };
                var l2_07 = new Level2 { Id2 = 7, Name = "L2 07", };
                var l2_08 = new Level2 { Id2 = 8, Name = "L2 08", };
                var l2_09 = new Level2 { Id2 = 9, Name = "L2 09", };
                var l2_10 = new Level2 { Id2 = 10, Name = "L2 10" };

                var l3_01 = new Level3 { Id3 = 1, Name = "L3 01", };
                var l3_02 = new Level3 { Id3 = 2, Name = "L3 02", };
                var l3_03 = new Level3 { Id3 = 3, Name = "L3 03", };
                var l3_04 = new Level3 { Id3 = 4, Name = "L3 04", };
                var l3_05 = new Level3 { Id3 = 5, Name = "L3 05", };
                var l3_06 = new Level3 { Id3 = 6, Name = "L3 06", };
                var l3_07 = new Level3 { Id3 = 7, Name = "L3 07", };
                var l3_08 = new Level3 { Id3 = 8, Name = "L3 08", };
                var l3_09 = new Level3 { Id3 = 9, Name = "L3 09", };
                var l3_10 = new Level3 { Id3 = 10, Name = "L3 10" };

                var l1s = new[] { l1_01, l1_02, l1_03, l1_04, l1_05, l1_06, l1_07, l1_08, l1_09, l1_10 }.ToArray();
                var l2s = new[] { l2_01, l2_02, l2_03, l2_04, l2_05, l2_06, l2_07, l2_08, l2_09, l2_10 }.ToArray();
                var l3s = new[] { l3_01, l3_02, l3_03, l3_04, l3_05, l3_06, l3_07, l3_08, l3_09, l3_10 }.ToArray();

                ctx.LevelOne.Add(l1s);
                ctx.LevelTwo.Add(l2s);
                ctx.LevelThree.Add(l3s);

                l1s[0].OneToMany_Required = new List<Level2> { l2s[0], l2s[1], l2s[2], l2s[3], l2s[4], l2s[5], l2s[6], l2s[7], l2s[8], l2s[9] };
                l2s[0].OneToMany_Required = new List<Level3> { l3s[0], l3s[1], l3s[2], l3s[3], l3s[4], l3s[5], l3s[6], l3s[7], l3s[8], l3s[9] };

                ctx.SaveChanges();

                l1s[0].OneToMany_Optional = new List<Level2> { l2s[1], l2s[3], l2s[5], l2s[7], l2s[9] };
                l2s[0].OneToMany_Optional = new List<Level3> { l3s[1], l3s[3], l3s[5], l3s[7], l3s[9] };

                ctx.SaveChanges();
            }

            using (var ctx = new MyContext())
            {
                ctx.LevelOne.Include(e => e.OneToMany_Optional).ThenInclude(e => e.OneToMany_Optional).ThenInclude(e => e.OneToMany_Required_Inverse.OneToMany_Optional).ToList();
            }
        }
    }
}

```

throws:

Unhandled Exception: System.ArgumentException: The properties expression 'e => e
.OneToMany_Required_Inverse.OneToMany_Optional' is not valid. The expression sho
uld represent a property access: 't => t.MyProperty'. When specifying multiple p
roperties use an anonymous type: 't => new { t.MyProperty1, t.MyProperty2 }'.
Parameter name: propertyAccessExpression
   at System.Linq.Expressions.ExpressionExtensions.GetPropertyAccessList(LambdaE
xpression propertyAccessExpression) in D:\k\EntityFramework\src\EntityFramework.
Core\Utilities\ExpressionExtensions.cs:line 47
   at Microsoft.Data.Entity.Query.ResultOperators.ThenIncludeExpressionNode.Appl
yNodeSpecificSemantics(QueryModel queryModel, ClauseGenerationContext clauseGene
rationContext) in D:\k\EntityFramework\src\EntityFramework.Core\Query\ResultOper
ators\ThenIncludeExpressionNode.cs:line 39
   at Remotion.Linq.Parsing.Structure.IntermediateModel.MethodCallExpressionNode
Base.Apply(QueryModel queryModel, ClauseGenerationContext clauseGenerationContex
t)
   at Remotion.Linq.Parsing.Structure.QueryParser.GetParsedQuery(Expression expr
essionTreeRoot)
   at Microsoft.Data.Entity.Query.EntityQueryParser.<>c.<GetParsedQuery>b__2_0(E
xpression e) in D:\k\EntityFramework\src\EntityFramework.Core\Query\EntityQueryP
arser.cs:line 67
   at Microsoft.Data.Entity.Utilities.ThreadSafeDictionaryCache`2.GetOrAdd(TKey
key, Func`2 factory) in D:\k\EntityFramework\src\EntityFramework.Core\Utilities\
ThreadSafeDictionaryCache.cs:line 37
   at Microsoft.Data.Entity.Query.EntityQueryParser.GetParsedQuery(Expression ex
pressionTreeRoot) in D:\k\EntityFramework\src\EntityFramework.Core\Query\EntityQ
ueryParser.cs:line 58
   at Remotion.Linq.QueryProviderBase.GenerateQueryModel(Expression expression)
   at Remotion.Linq.QueryProviderBase.Execute(Expression expression)
   at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult
](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Linq.QueryableExtensions.IncludableQueryable`2.GetEnumerator() in D
:\k\EntityFramework\src\EntityFramework.Core\Extensions\QueryableExtensions.cs:l
ine 1355
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Repro1528.Program.Main(String[] args) in D:\Projects\Repro1528\Repro1528\P
rogram.cs:line 143
Press any key to continue . . .

**Comment by maumar** [comment]
fixed in c12501a2d884d240f83de7a6b236c9a37af28db2
