### ISSUE TITLE
Pre-defined conversions from enum to string cause an exception for SQLite

### ISSUE THREAD

**Issue by snrnats** [dotnet/efcore#15433]
An exception is thrown when you save an object with an enum property. Exception only occurs if conversion to string is defined using [ColumnAttribute](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions#pre-defined-conversions), e.g. `[Column(TypeName = "nvarchar(24)")]`. If conversion is defined using `HasConversion<string>` all works fine. It is only reproducible for SQLite. If use SqlServer both options works fine.

```
Exception message: System.InvalidOperationException
  HResult=0x80131509
  No coercion operator is defined between types 'ConsoleApp2.Gender' and 'System.String'.
Stack trace:
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrAccessorFactory`1.Create(PropertyInfo propertyInfo, IPropertyBase propertyBase)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.ReadPropertyValue(IPropertyBase propertyBase)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at ConsoleApp2.Program.Main(String[] args) in D:\Trash\ConsoleApp2\ConsoleApp2\Program.cs:line 20
```

### Steps to reproduce

1. Open the solution [ConsoleApp2.zip](https://github.com/aspnet/EntityFrameworkCore/files/3101535/ConsoleApp2.zip)
2. Launch the project

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SQLite
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.11

**Comment by ajcvickers** [comment]
Note for triage, this also failed:
```C#
modelBuilder.Entity<Person>().Property(e => e.Gender).HasColumnType("nvarchar(24)");
```
but as stated above, this works:
```C#
modelBuilder.Entity<Person>().Property(e => e.Gender).HasConversion<string>();
```

**Comment by ajcvickers** [comment]
@snrnats It was pointed out in triage that this is SQLite and `nvarchar(24)` is not a type that SQLite understands. Basically, SQLite is limited to `TEXT`, `BLOB`, `INTEGER`, and `REAL` database types, so using one of those should work.
