### ISSUE TITLE
Could not load type AbstractionStrings

### ISSUE THREAD

**Issue by MohammedTawfik** [dotnet/efcore#15503]
when i try to add migration i got the following exception i am using Entity Framework Core 3.0.0-preview4.19216.3
```
Exception message:
System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Internal.AbstractionsStrings' from assembly 'Microsoft.EntityFrameworkCore.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotEmpty(String value, String parameterName)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Could not load type 'Microsoft.EntityFrameworkCore.Internal.AbstractionsStrings' from assembly 'Microsoft.EntityFrameworkCore.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
```

### Further technical details
EF Core version: 3.0.0-preview4.19216.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 16.0

**Comment by christiannagel** [comment]
I had the same error when using Blazor Components (server-side) with Entity Framework Core. However, for some reason I had preview 4 of Microsoft.EntityFrameworkCore and preview 3 of Microsoft.EntityFrameworkCore.SqlServer and Microsoft.EntityFrameworkCore.Tools referenced. Changing all to preview 4 fixed this issue.

**Comment by ajcvickers** [comment]
@MohammedTawfik As @christiannagel this is usually an indication of mixed versions. If this isn't the issue, then please post your `csproj` file so we can take a look.

**Comment by MohammedTawfik** [comment]
Thanks @ajcvickers  and @christiannagel it is working after downgrading all packages to preview 3
