### ISSUE TITLE
GroupBy FK_Id.HasValue on Sql Server generates invalid sql

### ISSUE THREAD

**Issue by lakeman** [dotnet/efcore#15641]
```
Context.Table
.GroupBy(s => new{ s.FKId.HasValue })
.Select(g => new{ g.Key.HasValue })
```
Generates invalid Sql;
```
SELECT CASE
   WHEN fk_id IS NOT NULL
   THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END AS [HasValue]
GROUP BY fk_id IS NOT NULL
```
And fails;
```
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near the keyword 'IS'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
```

Generating the same case statement in the group by would fix it.

EF Core version: 2.2.3
Database Provider: Sql Server

**Comment by lakeman** [comment]
While looking for a workaround I also hit this;
```
Context.Table
.GroupBy(s => new{ HasValue = s.FKId.HasValue ? 1 : 0 })
.Select(g => new{ HasValue = (g.Key.HasValue == 1)})
```

Which generated;
```
SELECT CASE
   WHEN CASE
       WHEN [FKId] IS NOT NULL
       THEN 1 ELSE 0
   END AS [HasValue] = 1
   THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END AS [HasValue]
...
```
Where the intermediate value shouldn't be named. And finally discovered that this does work;
```
Context.Table
.GroupBy(s => new{ HasValue = s.FKId.HasValue ? 1 : 0 })
.Select(g => new{ g.Key.HasValue })
```
And generates straight forward SQL. Though the result set is obviously an int instead of bool, I can live with that for now.

**Comment by smitpatel** [comment]
Generated SQL in 3.1
```SQL
      SELECT CASE
          WHEN [t].[FKId] IS NOT NULL THEN CAST(1 AS bit)
          ELSE CAST(0 AS bit)
      END AS [HasValue]
      FROM [Table] AS [t]
      GROUP BY CASE
          WHEN [t].[FKId] IS NOT NULL THEN CAST(1 AS bit)
          ELSE CAST(0 AS bit)
      END
```
2nd query gets
```SQL
      SELECT CASE
          WHEN CASE
              WHEN [t].[FKId] IS NOT NULL THEN 1
              ELSE 0
          END = 1 THEN CAST(1 AS bit)
          ELSE CAST(0 AS bit)
      END AS [HasValue]
      FROM [Table] AS [t]
      GROUP BY CASE
          WHEN [t].[FKId] IS NOT NULL THEN 1
          ELSE 0
      END
```
