### ISSUE TITLE
[QUESTION] One-way one-to-one mapping?

### ISSUE THREAD

**Issue by jzabroski** [dotnet/efcore#15666]
### Describe what is not working as expected.
Why can't I just map something one-way?  For example, my `FollowUpInteraction` entity wants to reference a `Counterparty` entity to follow up with, but I do not want my `Counterparty` entity to contain properties for every such entity in my system that could be linked to a counterparty, as that would mess up my domain model and is not really what I'm trying to achieve, anyway.
```csharp
builder.HasOne(x => x.InteractedWithCounterparty)
                .WithOne() // missing a relationship here ruins the mapping
                .HasForeignKey<Counterparty>("InteractedCounterPartyId");
```
Note: This issue does not occur if `Counterparty` has a navigation property back to `FollowUpInteraction`.  I also [spiced things up just a bit](https://abcnews.go.com/GMA/Recipes/video/thanksgiving-2010-emeril-lagasses-pumpkin-spice-cupcakes-recipe-12222422) by changing the shadow property foreign key name such that EFCore can't just take the `InteractedWithCounterparty` property and add an `Id` to the end.

### If you are seeing an exception, include the full exceptions details (message and stack trace).

```
System.Data.SqlClient.SqlException : Invalid column name 'InteractedCounterPartyId'.
Invalid column name 'InteractedCounterPartyId'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.Load[TSource](IQueryable`1 source)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.Load(INavigation navigation, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.Internal.LazyLoader.Load(Object entity, String navigationName)
   at Microsoft.EntityFrameworkCore.Proxies.Internal.LazyLoadingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.FollowUpInteractionProxy.get_InteractedWithCounterparty()

```

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Pro
IDE: Visual Studio 2017 15.9.11

**Comment by jzabroski** [comment]
Here is a dump of the DebugString
```
Model: 
  EntityType: Counterparty
    Properties: 
      Id (long) Required PK AfterSave:Throw ValueGenerated.OnAdd 0 0 0 -1 0
        Annotations: 
          Relational:ColumnName: CounterPartyId
          Relational:TypeMapping: Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerLongTypeMapping
          SqlServer:ValueGenerationStrategy: IdentityColumn
      DateCreated (DateTime) Required 1 1 -1 -1 -1
        Annotations: 
          Relational:ColumnName: CreatedDate
          Relational:TypeMapping: Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDateTimeTypeMapping
      DateModified (DateTime) Required 2 2 -1 -1 -1
        Annotations: 
          Relational:ColumnName: ModifiedDate
          Relational:TypeMapping: Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDateTimeTypeMapping
      Description (string) 3 3 -1 -1 -1
        Annotations: 
          Relational:ColumnName: Description
          Relational:TypeMapping: Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerStringTypeMapping
      Name (string) 4 4 -1 -1 -1
        Annotations: 
          Relational:ColumnName: Name
          Relational:TypeMapping: Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerStringTypeMapping
      Version (byte[]) Concurrency BeforeSave:Ignore AfterSave:Ignore ValueGenerated.OnAddOrUpdate 5 5 -1 -1 1
        Annotations: 
          Relational:ColumnName: Version
          Relational:TypeMapping: Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerByteArrayTypeMapping
      InteractedCounterPartyId (no field, Nullable<long>) Shadow FK Index 6 6 1 0 2
        Annotations: 
          Relational:TypeMapping: Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerLongTypeMapping
    Service properties: 
      LazyLoader (no field, ILazyLoader)
    Keys: 
      Id PK
    Foreign keys: 
      Counterparty {'InteractedCounterPartyId'} -> FollowUpInteraction {'Id'} Unique ToDependent: FollowUpInteraction
    Annotations: 
      ConstructorBinding: Microsoft.EntityFrameworkCore.Metadata.Internal.FactoryMethodConstructorBinding
      NavigationAccessMode: Field
      Relational:Schema: dbo
      Relational:TableName: Counterparty
  EntityType: FollowUpInteraction
    Properties: 
      Id (long) Required PK AfterSave:Throw ValueGenerated.OnAdd 0 0 0 -1 0
        Annotations: 
          Relational:ColumnName: FollowUpInteractionId
          Relational:TypeMapping: Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerLongTypeMapping
          SqlServer:ValueGenerationStrategy: IdentityColumn
      InteractedWithCounterpartyId (no field, Nullable<long>) Shadow FK Index 11 11 2 1 3
        Annotations: 
          Relational:TypeMapping: Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerLongTypeMapping
    Navigations: 
      InteractedWithCounterparty (<InteractedWithCounterparty>k__BackingField, Counterparty) ToDependent Counterparty PropertyAccessMode.Field 2 -1 4 -1 -1
        Annotations: 
          PropertyAccessMode: Field
    Service properties: 
      LazyLoader (no field, ILazyLoader)
    Keys: 
      Id PK
    Foreign keys: 
      FollowUpInteraction {'FollowOnOfferingId'} -> FollowOnOffering {'Id'} Unique ToDependent: FollowUpInteraction ToPrincipal: Offering
    Annotations: 
      ConstructorBinding: Microsoft.EntityFrameworkCore.Metadata.Internal.FactoryMethodConstructorBinding
      NavigationAccessMode: Field
      Relational:Schema: dbo
      Relational:TableName: FollowUpInteraction
```

**Comment by smitpatel** [comment]
Which table contains InteractedCounterPartyId column? Can you post whole sql? The model seem to be in sync with the configuration.

**Comment by jzabroski** [comment]
I put the wrong entity in the `HasForeignKey` relationship.
