### ISSUE TITLE
Failing to creation migration because of FK constraint on entity not in DbSets

### ISSUE THREAD

**Issue by WhitWaldo** [dotnet/efcore#15678]
**Describe what is not working as expected.**
I'm attempting to create and apply migrations of my code to my database. Unfortunately, I keep getting the error described below. Oddly, it's referring to an entity that I do use within a context, but not within the context for which I'm creating this migration. I've thoroughly checked all the entities I'm specifying across my DbSets in this context and there's no mention of X or Y in any of them, yet I keep getting these constraint errors.

Further, if I just add an ignore (e.g. modelBuilder.Entity<X().Ignore(a => a.Y)), it resolves the constraint error, but gives me another instead which is just another property on X or a whole other class altogether which is also not included anywhere in this context.

I wouldn't expect to see any constraint errors regarding classes and properties that aren't specified in the DbSets or in the properties thereof.

```
**Error:**
Introducing FOREIGN KEY constraint 'FK_X_Y_Z' on table 'X' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or  ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.

**Stack trace:**
 (0x80131904): Introducing FOREIGN KEY constraint 'FK_X_Y_Z' on table 'X' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.
Could not create constraint or index. See previous errors.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at xyz`1 options) in L:\...\X.cs:line 32
   at TenantContextFactory.CreateDbContext(String[] args) in L:\...\TenantContextFactory.cs:line 22
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:266887b5-3d26-4587-8e45-4b1ec6e39ec9
Error Number:1785,State:0,Class:16
```

### Steps to reproduce
Unable to provide a solution demonstrating this issue at this time, but here's a brief idea of what I'm seeing:

```c#
public class A {
  [Key]
  int Id {get;set;}
}

public class B {
  [Key]
  int Id {get;set;}
}

public class C {
  [Key]
  int Id {get;set;}
  List<D> Things {get;set;}
}

[Owned]
public class D {
  [Key]
  int Id {get;set;}
  int CId {get;set;}
}

//Within my context.cs

//...
public DbSet<A> A {get;set;}
public DbSet<B> B {get;set;}
```

Following this example I'm then seeing an error along the lines of the following:
```
Introducing FOREIGN KEY constraint 'FK_C_D_CId' on table 'C' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or  ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.
```

Of course this doesn't make any sense because I'm not actually using C or D anywhere in this context.

### Further technical details
EF Core version: 2.2.4
Microsoft.EntityFrameworkCore.Design: 2.2.4
Database Provider: 2.2.4
Operating system: Windows 10 Pro 64-bit
IDE: Visual Studio 2019 Pro

**Comment by ajcvickers** [comment]
@WhitWaldo Are you 100% certain that the entity types you're not expecting in the model are not referenced (through either collection or reference navigation properties) from entity types that are in the model? This is the only thing I can think of that would cause this, so I suspect if that's not the case then we're going to need more information to reproduce what you are seeing.

**Comment by WhitWaldo** [comment]
@ajcvickers You're right - there was a reference to the other properties 6 entities deep on one of the items. Thanks!
