### ISSUE TITLE
How to Support netcoreapp2.2 and 3.0 app using same library

### ISSUE THREAD

**Issue by muqeet-khan** [dotnet/efcore#15726]
Describe what is not working as expected.
I am trying to use our current NETStandard 2 library that we have been using for our NETCOREAPP2.2 apps and make it work for 3.0 previews? Is that possible? Whats the migration path like? Currently, this library calls: 
```
<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="2.2.4" />
```
I was assuming that using the following in an aspnet core 3.0 project would work. 
```
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0-preview5.19227.1" />
```
Could you point me to a document or direction of how can I use my NETSTANDARD2.0 assembly for both NETCOREAPP2.2 and NETCOREAPP3.0 apps as we have apps in production that are NETCOREAPP2.2.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:

System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Metadata.Builders.IndexBuilder Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.HasIndex(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Object>>)'.
   at OurApp.EntityFramework.AppDataDbContext.<>c.<OnModelCreating>b__1035_3(EntityTypeBuilder`1 entity)
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity[TEntity](Action`1 buildAction)
   at OurApp.EntityFramework.AppDataDbContext.OnModelCreating(ModelBuilder modelBuilder) in C:\Users\u3\Source\Repos\OurAppWeb\OurApp.EntityFramework\AppDataDbContext.cs:line 395
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator, DiagnosticsLoggers loggers)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator, DiagnosticsLoggers loggers)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.AsNoTracking[TEntity](IQueryable`1 source)
   at OurApp.EntityFramework.AppDataRepository.GetUnReadEmail(String repCode) in C:\Users\u3\Source\Repos\OurAppWeb\OurApp.EntityFramework\AppDataRepository.cs:line 167
   at OurApp.Web.Hubs.MessagesHub.OnConnectedAsync() in C:\Users\u3\Source\Repos\OurAppWeb\OurAppWeb\Hubs\MessagesHub.cs:line 65
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnConnectedAsync(HubConnectionContext connection)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnConnectedAsync(HubConnectionContext connection)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.RunHubAsync(HubConnectionContext connection)

```

and here is the relevant part of the DBContext:

```
            modelBuilder.Entity<SampleEntity>(entity =>
            {

                entity.HasIndex(e => e.SampleEntity1)
                    .HasName("IX_SampleEntity")
                    .IsUnique();

                entity.HasIndex(e => new { e.ShortName, e.SampleEntity1 })
                    .HasName("_dta_index_SampleEntity_15_1421404283__K2_3");

                entity.Property(e => e.Active).HasDefaultValueSql("((1))");

                entity.Property(e => e.SampleEntity1).IsUnicode(false);

                entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.CreatedRep)
                    .IsUnicode(false);

                entity.Property(e => e.DefaultNotes).IsUnicode(false);

                entity.Property(e => e.LongName).IsUnicode(false);

                entity.Property(e => e.ModifiedDate).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.ModifiedRep)
                    .IsUnicode(false);

                entity.Property(e => e.ModifiedSystemDate).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.ModifiedSystemRep)
                    .IsUnicode(false)
                    .HasDefaultValueSql("(suser_sname())");

                entity.Property(e => e.Status).IsUnicode(false);

            });
```

### Further technical details
EF Core version: 
```
<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="2.2.4" /> in the library and 
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0-preview5.19227.1" /> in the ASP.Net Core 3.0 app. 
```
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows Server 2016\Windows 10
IDE: Visual Studio 2019 16.1.0 Preview 3.0

**Comment by ajcvickers** [comment]
@muqeet-khan You will need the .NET Core 3.0 preview to use EF Core 3.0 preview; it won't work with 2.2.4. Also, make sure to update all the EF packages you reference to the same preview version.
