### ISSUE TITLE
Failing to create migration because of entity not used in DbContext or DbSets

### ISSUE THREAD

**Issue by WhitWaldo** [dotnet/efcore#15766]
Describe what is not working as expected.

I'm attempting to create a new migration in a C# solution in which I have three different contexts. Each context is in its own project but they all point to a shared domain project. 

My migration is consistently failing because of the exception provided later in this ticket. The issue here is that I am 100% certain that the referenced entity isn't used anywhere in that context. The name of the entity does not show up anywhere in the NotWorkingContext file, isn't in any of the configured DbSets and is not a property on any of the DbSet entities that are configured. It is used to enable the many-to-many relationship between EntityA and EntityB.

When doing a string search for the offending entity across my solution, I can confirm that it does exist within a separate context (as intended) and is not in any unintended entities and is properly set up within that other context.

I'm attempting to create the migration with the following command:

Add-Migration MyMigration -Project Data.NotWorking -StartupProject NotWorking -Verbose

Interestingly, the migration was able to build correctly in the context in which the entity is intended to be used in and without issue (despite the [Key] annotations on the entity and a supplementary fluent configuration (since it is used in a many-to-many relationship). 

This leads me to believe that it's not actually an issue with the annotations like the error suggests, but rather a bug involving something else, especially given that it shouldn't be including the entity in the context in the first place as it's not used anywhere. Of course, because I'm not intending to use this in my present context, I cannot simply add a fluent configuration as a workaround because I'm not otherwise using EntityA and EntityB.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: 
Entity type 'EntityAToEntityB' has composite primary key defined with data annotations. To set composite primary key, use fluent API.
Stack trace:
PM> Add-Migration MyMigration -StartupProject NotWorking -Project Data.NotWorking -Verbose
Using project 'Data\Data.NotWorking'.
Using startup project 'MigrationBuilder\NotWorking'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile xyz\NotWorking\bin\Debug\netcoreapp2.2\NotWorking.deps.json --additionalprobingpath wxy\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig xyz\NotWorking\bin\Debug\netcoreapp2.2\NotWorking.runtimeconfig.json wxy\.nuget\packages\microsoft.entityframeworkcore.tools\2.2.4\tools\netcoreapp2.0\any\ef.dll migrations add MyMigration --json --verbose --no-color --prefix-output --assembly xyz\NotWorking\bin\Debug\netcoreapp2.2\Data.NotWorking.dll --startup-assembly xyz\NotWorking\bin\Debug\netcoreapp2.2\NotWorking.dll --project-dir xyz\Data.NotWorking\ --language C# --working-dir xyz --root-namespace Data.NotWorking
Using assembly 'Data.NotWorking'.
Using startup assembly 'NotWorking'.
Using application base 'xyz\NotWorking\bin\Debug\netcoreapp2.2'.
Using working directory 'xyz\NotWorking'.
Using root namespace 'Data.NotWorking'.
Using project directory 'xyz\Data.NotWorking\'.
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Found IDesignTimeDbContextFactory implementation 'MyContextFactory'.
Found DbContext 'MyContext'.
Finding application service provider...
Finding IWebHost accessor...
No CreateWebHostBuilder(string[]) method was found on type 'NotWorking.Program'.
No application service provider was found.
Finding DbContext classes in the project...
Using DbContext factory 'MyContextFactory'.
System.InvalidOperationException: Entity type 'EntityAToEntityB' has composite primary key defined with data annotations. To set composite primary key, use fluent API.
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.KeyAttributeConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_DatabaseCreator()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.CanConnect()
   at Data.NotWorking.MyContext..ctor(DbContextOptions`1 options) in xyz\Data.NotWorking\MyContext.cs:line 31
   at NotWorking.MyContextFactory.CreateDbContext(String[] args) in xyz\NotWorking\MyContextFactory.cs:line 22
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Entity type 'EntityAToEntityB' has composite primary key defined with data annotations. To set composite primary key, use fluent API.
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Unfortunately, I'm unable to do this as this isn't an open source project. I'm not sure how to reproduce this except in the state the project is currently in or I'd mock up a demo. I'd be happy to jump on a screen share as necessary with someone from Microsoft to demonstrate what I'm seeing.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

### Further technical details
EF Core version: v2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer v2.2.4
Operating system: Windows 10 Pro x64
IDE: Visual Studio 2019 v16.1.0 (was able to reproduce in the latest VS 2019 Preview yesterday as well)

**Comment by WhitWaldo** [comment]
A relevant follow-up here. I've dug through the old migrations and this context has never before referenced this many-to-many entity historically nor either of the entities it's joining. So, why it's picking today to complain about it is beyond me.

**Comment by WhitWaldo** [comment]
If I add the following to my context, the migration works:

modelBuilder.Entity<EntityAToEntityB>().HasKey(a => new {a.EntityAId, a.EntityBId});

However, it also brings in just about the entire entity schema from the other context which is obviously not desirable. 



That said, I've now gone through and identified the issue. I'm guessing that convention is playing a role here in that I've got a property called EntityDId. Even though I don't actually reference EntityD in here, I'm guessing it must have been being a little too clever and making the distant leap from EntityD to EntityC to EntityA which was thus referencing the many-to-many here. I've added [Ignore] to the property and am no longer experiencing this issue.

It'd be nice if there was something in the error that indicated how to narrow this down. such as "A conventional foreign key relationship in File A points to this relationship where something appears to be wrong." At least I'd understand where and how the offending entities were being included.

**Comment by ajcvickers** [comment]
@WhitWaldo It certainly should not be the case that having a property named `EntityDId` will cause an `EntityD` type to be discovered. Would it be possible for you to post a runnable project/solution that demonstrates this behavior so that we can investigate further?

**Comment by WhitWaldo** [comment]
@ajcvickers I'll see if I can't reproduce it in a more succinct solution as I've got time.

**Comment by WhitWaldo** [comment]
@ajcvickers While recreating a solution here, I did find an EntityD that was hiding in one of the entities. I'd commented out that class while working through a solution to the migration issue, so the [NotMapped] ultimately didn't actually do the trick - commenting out the class with the offending property actually resolved this.

**Comment by ajcvickers** [comment]
@WhitWaldo Thanks for checking.
