### ISSUE TITLE
Using InMemoryDatabase and InternalServiceProvider the changes are not saved

### ISSUE THREAD

**Issue by Tbd19** [dotnet/efcore#15786]
I am using in-memory database to test my application and everything was working. However now I have a request to implement audit trail and I want to inject a service in order to do this. Because the DbContext can not have a constructor where the service is injected I have to use GetService to retrieve the dependency.

The in-memory database is constructed like this:

```
var serviceProvider = new Microsoft.Extensions.DependencyInjection.ServiceCollection()
   .AddEntityFrameworkInMemoryDatabase()
   .BuildServiceProvider();

var options = new DbContextOptionsBuilder<XXXContext>()
	.UseInMemoryDatabase(databaseName: "<AUniqueName>")
	////.UseInternalServiceProvider(serviceProvider)
	.Options;

return new XXXContext(options);

```
If I do not use the InternalServiceProvider everything works correctly, but once I use the InternalServiceProvider all the changes done on one instance of DbContext are not propagated to the other DbContext

The only way to reproduce this was to create a small console application at https://github.com/Tbd19/EFCoreServiceProviderIssue

And the result is:
The count with Service Provider is = 0
The count without Service Provider is = 1

**Comment by ajcvickers** [comment]
@Tbd19 A couple of things. First, `DbContext` can have services injected into its constructor in the normal way. I'm curious to understand why you're not finding this to be the case. 

Second, that being said, it's still not clear to me why this means you have to call `UseInternalServiceProvider`. Can you give some details on why you are calling this?

**Comment by Tbd19** [comment]
I can not use the constructor to inject the service because I am using code first and every time I am trying to add a new migration I get an exception. 
How can I over come this?

**Comment by ajcvickers** [comment]
@Tbd19 Can you post a small, runnable project/solution or complete code listing that demonstrates the issue you are seeing?

**Comment by Tbd19** [comment]
@ajcvickers I will try to provide a runnable project at the end of this week. Untill then here is the error I get when trying to add a new migration
PM> add-migration test
System.InvalidOperationException: The DbContext of type 'XXXContext' cannot be pooled because it does not have a single public constructor accepting a single parameter of type DbContextOptions.
   at Microsoft.EntityFrameworkCore.Internal.DbContextPool`1..ctor(DbContextOptions options)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__5`2.<AddDbContextPool>b__5_1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__5`2.<AddDbContextPool>b__5_2(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_2.<FindContextTypes>b__11()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The DbContext of type 'XXXContext' cannot be pooled because it does not have a single public constructor accepting a single parameter of type DbContextOptions.

The configuration is done in Startup.ConfigureServices like this:
services.AddSingleton<IInjectedService, InjectedServiceImplementation>();
service.AddDbContextPool<XXXContext>(options => options.UseSqlServer(connectionString));

As you can see from the error the add-migration does not allow for injecting services into the DbContext, this was the reason I tried to use UseInternalServiceProvider

**Comment by ajcvickers** [comment]
@Tbd19 The solution to that issue is to not use context pooling. If you find that doing so causes a significant change in performance, then please let us know.

**Comment by Tbd19** [comment]
@ajcvickers I tried to use
service.AddDbContext<XXXContext>(options => options.UseSqlServer(connectionString));

but I got an exception
System.InvalidOperationException: Unable to resolve service for type 'Schaeffler.Database.Context.IInjectedService' while attempting to activate 'Schaeffler.Database.Context.GVPiContext'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_2.<FindContextTypes>b__11()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
