### ISSUE TITLE
Add-migration throws nullrefexception

### ISSUE THREAD

**Issue by twenzel** [dotnet/efcore#15831]
```
PM> add-migration test
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Update.Internal.SharedTableEntryMap`1.GetMainEntry(IUpdateEntry entry)
   at Microsoft.EntityFrameworkCore.Update.Internal.SharedTableEntryMap`1.GetOrAddValue(IUpdateEntry entry)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.DiffData(TableMapping source, TableMapping target, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Diff(TableMapping source, TableMapping target, DiffContext diffContext)+MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.DiffCollection[T](IEnumerable`1 sources, IEnumerable`1 targets, DiffContext diffContext, Func`4 diff, Func`3 add, Func`3 remove, Func`4[] predicates)+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.
```

### Further technical details
EF Core version: 3.0.0-preview6.19274.4
Database Provider. Microsoft.EntityFrameworkCore.SqlServer
IDE: Visual Studio 2019 16.1.0

**Comment by ajcvickers** [comment]
@twenzel Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by twenzel** [comment]
[TestServer.zip](https://github.com/aspnet/EntityFrameworkCore/files/3258863/TestServer.zip)

**Comment by ajcvickers** [comment]
@twenzel Thanks for the repro. The project contains a model snapshot for what looks like a different model, and no associated migrations. The error went away when I removed this bogus model snapshot. Any ideas how the project got into this state? Did something you did with EF tooling leave the project like this?

**Comment by twenzel** [comment]
Thanks for the hint. No, I guess this was due to many code migrations and manually editing.
