### ISSUE TITLE
Cannot Configure Nested Discriminators

### ISSUE THREAD

**Issue by todd-skelton** [dotnet/efcore#15870]
I'm trying to configure entities that have discriminators at multiple levels. I can't seem to figure out how to do so. 

### Exception
```
Unhandled Exception: System.InvalidOperationException: A discriminator property cannot be set for the entity type 'NestedEntity' because it is not the root of an inheritance hierarchy.
   at Microsoft.EntityFrameworkCore.Metadata.RelationalEntityTypeAnnotations.SetDiscriminatorProperty(IProperty value, Type oldDiscriminatorType)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalEntityTypeBuilderAnnotations.DiscriminatorBuilder(Func`2 createProperty, Type propertyType)
   at Microsoft.EntityFrameworkCore.RelationalEntityTypeBuilderExtensions.HasDiscriminator[TDiscriminator](EntityTypeBuilder entityTypeBuilder, String name)
   at EfCoreNestedDiscriminators.MyContext.OnModelCreating(ModelBuilder modelBuilder) in C:\Users\admin\Source\Local\EfCoreNestedDiscriminators\Program.cs:line 57
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Collections.Generic.IEnumerable<TEntity>.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EfCoreNestedDiscriminators.Program.Main(String[] args) in C:\Users\admin\Source\Local\EfCoreNestedDiscriminators\Program.cs:line 13
```

### Steps to reproduce
```c#
    public abstract class BaseEntity
    {
        public int Id { get; set; }
        public BaseType Type { get; set; }
    }

    public enum BaseType
    {
        NestedEntity
    }

    public abstract class NestedEntity : BaseEntity
    {
        public NestedType NestedType { get; set; }
    }

    public class ConcreteEntity : NestedEntity
    {

    }

    public enum NestedType
    {
        ConcreteEntity
    }

    public class MyContext : DbContext
    {
        public DbSet<BaseEntity> Entities { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(
                @"Server=(localdb)\mssqllocaldb;Database=EfCoreNestedDiscriminators;Integrated Security=True");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<BaseEntity>().HasDiscriminator<BaseType>("Type").HasValue<NestedEntity>(BaseType.NestedEntity);

            modelBuilder.Entity<NestedEntity>().HasDiscriminator<NestedType>("NestedType").HasValue<ConcreteEntity>(NestedType.ConcreteEntity);
        }
    }
```

### Further technical details
EF Core version: 2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Visual Studio 2019

**Comment by ajcvickers** [comment]
@xKloc This is not a mapping that is supported by EF Core.  Also, the value of the feature when compared against the implementation cost makes it something that we have plans to implement any time soon, and possibly never, depending on the level of additional feedback we get indicating the importance of this kind of mapping.

**Comment by xKloc** [comment]
No problem, I ended up flattening my discriminators.

**Comment by AndriySvyryd** [comment]
Related to https://github.com/aspnet/EntityFrameworkCore/issues/10140

**Comment by ajcvickers** [comment]
Closing as this is no longer something we intend to implement.
