### ISSUE TITLE
SaveChangesAsync does not save changes made in the context to the database.

### ISSUE THREAD

**Issue by pfdsilva** [dotnet/efcore#15957]
SaveChangesAsync does not save changes made in the context to the database.

```
Exception message:
System.InvalidOperationException: The connection was not closed. The connection's current state is connecting.

Stack trace:
Exception thrown: 'System.InvalidOperationException' in System.Data.SqlClient.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.text.encoding.codepages\4.5.0\runtimes\win\lib\netcoreapp2.0\System.Text.Encoding.CodePages.dll'. Cannot find or open the PDB file.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.4\System.Diagnostics.StackTrace.dll'. Cannot find or open the PDB file.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.4\System.Reflection.Metadata.dll'. Cannot find or open the PDB file.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.4\System.IO.FileSystem.dll'. Cannot find or open the PDB file.
Microsoft.EntityFrameworkCore.Database.Connection:Debug: An error occurred using the connection to database 'mydb' on server 'xxxxxx'.

System.InvalidOperationException: The connection was not closed. The connection's current state is connecting.
   at System.Data.ProviderBase.DbConnectionClosedConnecting.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
Exception thrown: 'System.InvalidOperationException' in Microsoft.EntityFrameworkCore.Relational.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
```
[efcore_sqlserver_trace.txt](https://github.com/aspnet/EntityFrameworkCore/files/3255466/efcore_sqlserver_trace.txt)
I have attached the trace files.

### Steps to reproduce

```c#
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Debug;
using System;

namespace CodeFirstAsync
{
  class Program
  {
    static void Main(string[] args)
    {
      Console.WriteLine("Hello World!");
      Program p = new Program();
      p.Run();
    }

    public void Run()
    {
      try
      {
        using (var db = new BloggingContext())
        {
          db.Database.EnsureDeletedAsync();
          db.Database.EnsureCreatedAsync();
          var blog = new Instructor { Name = "async" };
          db.Instructors.Add(blog);
          db.SaveChangesAsync();
        }
      }
      catch (Exception error)
      {
        Console.WriteLine(error.ToString());
      }
    }
  }

  public class BloggingContext : DbContext
  {
    public static readonly LoggerFactory MyLoggerFactory
    = new LoggerFactory(new[] { new DebugLoggerProvider((_, __) => true) });


    public DbSet<Instructor> Instructors { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
      base.OnModelCreating(modelBuilder);
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseSqlServer(@"YOUR CONNECTION STRING").UseLoggerFactory(MyLoggerFactory);

      optionsBuilder.EnableSensitiveDataLogging();
    }
  }


  public class Instructor
  {
    public int Id { get; set; }
    public string Name { get; set; }
  }
}

```

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Microsoft Windows 10
IDE: Visual Studio 2017 15.9.11

**Comment by smitpatel** [comment]
You did not await the async call so DbConnection is closed before SaveChangesAsync finishes. Feel free to re-open issue if you hit error after awaiting the async method properly.

**Comment by pfdsilva** [comment]
@smitpatel , thanks for pointing out the issue with the test case. 

Now after adding the await keyword,I do not see any error's while executing the test case. However I am noticing that the table is NOT getting created in the database.

So I have created another github issue, since I am not able to re-open this one. #15961
