### ISSUE TITLE
Query: EF.Property using wrong generic type fails for InMemory

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#15952]
```C#
                Enum64? param12 = Enum64.SomeValue;
                Assert.Same(
                    entity,
                    set.Where(e => e.Id == 11 && EF.Property<Enum64>(e, nameof(BuiltInNullableDataTypes.Enum64)) == param12).ToList()
                        .Single());
```
The column type is `Enum64?` but generic type used is `Enum64`. This works for relational since everything is translated to server which does not differentiate in nulls. But for inmemory it throws since server side value is not the same as expected type.

```
 System.InvalidOperationException : Rewriting child expression from type 'Microsoft.EntityFrameworkCore.BuiltInDataTypesTestBase`1+Enum64[Microsoft.EntityFrameworkCore.BuiltInDataTypesInMemoryTest+BuiltInDataTypesInMemoryFixture]' to type 'System.Nullable`1[Microsoft.EntityFrameworkCore.BuiltInDataTypesTestBase`1+Enum64[Microsoft.EntityFrameworkCore.BuiltInDataTypesInMemoryTest+BuiltInDataTypesInMemoryFixture]]' is not allowed, because it would change the meaning of the operation. If this is intentional, override 'VisitUnary' and change it to allow this rewrite.
  Stack Trace: 
    at ExpressionVisitor.ValidateChildType(Type before, Type after, String methodName)
    at ExpressionVisitor.ValidateUnary(UnaryExpression before, UnaryExpression after)
    at ExpressionVisitor.VisitUnary(UnaryExpression node)
    at UnaryExpression.Accept(ExpressionVisitor visitor)
    at ExpressionVisitor.Visit(Expression node)
    at ExpressionVisitor.VisitBinary(BinaryExpression node)
    at BinaryExpression.Accept(ExpressionVisitor visitor)
    at ExpressionVisitor.Visit(Expression node)
    at ExpressionVisitor.VisitBinary(BinaryExpression node)
    at BinaryExpression.Accept(ExpressionVisitor visitor)
    at ExpressionVisitor.Visit(Expression node)
    at InMemoryExpressionTranslatingExpressionVisitor.Translate(InMemoryQueryExpression inMemoryQueryExpression, Expression expression) in Translator.cs line: 25
    at InMemoryQueryableMethodTranslatingExpressionVisitor.TranslateExpression(InMemoryQueryExpression inMemoryQueryExpression, Expression expression) in InMemoryQueryableMethodTranslatingExpressionVisitor.cs line: 340
    at InMemoryQueryableMethodTranslatingExpressionVisitor.TranslateLambdaExpression(ShapedQueryExpression shapedQueryExpression, LambdaExpression lambdaExpression) in InMemoryQueryableMethodTranslatingExpressionVisitor.cs line: 349
    at InMemoryQueryableMethodTranslatingExpressionVisitor.TranslateWhere(ShapedQueryExpression source, LambdaExpression predicate) in InMemoryQueryableMethodTranslatingExpressionVisitor.cs line: 326
    at QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in QueryableMethodTranslatingExpressionVisitor.cs line: 423
    at MethodCallExpression.Accept(ExpressionVisitor visitor)
    at ExpressionVisitor.Visit(Expression node)
    at QueryCompilationContext.CreateQueryExecutor[TResult](Expression query) in QueryCompilationContext2.cs line: 61
    at Database.CompileQuery2[TResult](Expression query, Boolean async) in Database.cs line: 72
    at QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async) in QueryCompiler.cs line: 108
    at <>c__DisplayClass9_0`1.<Execute>b__0() in QueryCompiler.cs line: 97
    at CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler) in CompiledQueryCache.cs line: 84
    at CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) in CompiledQueryCache.cs line: 59
    at QueryCompiler.Execute[TResult](Expression query) in QueryCompiler.cs line: 93
    at EntityQueryProvider.Execute[TResult](Expression expression) in EntityQueryProvider.cs line: 79
    at EntityQueryable`1.GetEnumerator() in EntityQueryable`.cs line: 94
    at List`1.ctor(IEnumerable`1 collection)
    at Enumerable.ToList[TSource](IEnumerable`1 source)
    at BuiltInDataTypesTestBase`1.QueryBuiltInNullableDataTypesTest[TEntity](EntityEntry`1 source) in BuiltInDataTypesTestBase.cs line: 697
    at BuiltInDataTypesTestBase`1.Can_query_using_any_nullable_data_type() in BuiltInDataTypesTestBase.cs line: 560
```

**Comment by ajcvickers** [comment]
@smitpatel I don't think the test did this intentionally; it's likely just a typo/copy/paste error.
