### ISSUE TITLE
Seeding entity with required shadow property throws exception even if the backing field is set

### ISSUE THREAD

**Issue by TrieBr** [dotnet/efcore#15985]
I'm trying to create a multitenant system using a query filter as described on [Query Filters](https://docs.microsoft.com/en-us/ef/core/querying/filters#example) page. I have an entity with a private property `_tenantId`. I require that every entity has a `tentantId` set, so I mark the shadow property as required:

```
builder.Entity<User>().Property<string>("TenantId").HasField("_tenantId");
builder.Entity<User>().Property<string>("TenantId").IsRequired();

```

Then I try seeding a user:
```
  var user= new  User("c19fe7f7-d039-4354-b7d9-f72dc434baca") // constructor sets _tenantId
            {
                Id = "a9a4c59a-d158-4d71-b7ad-f2cab2824ee0",
                FirstName = "First",
                LastName = "Last",
            };
            builder.Entity<User>().HasData(user);

```

But I get the following exception when trying to run `Add-Migration`

```
Exception message:
The seed entity for entity type 'User' cannot be added because there was no value provided for the required property 'TenantId'.

Stack trace:

   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateData(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```
Upon further investigation, this issue seems related to: https://github.com/aspnet/EntityFrameworkCore/issues/9999

When I Removed `IsRequired`, the `Add-Migration` works, but I don't see the `TenantId` in the migration for the seed. It seems like it is currently not possible to seed shadow properties. Is that correct?

### Steps to reproduce
```c#
public class Blog
    {
        public Blog(string tenantId)
        {
            _tenantId = tenantId;
        }
        public string Id { get; set; }
        private string _tenantId;
    }

    public class ApplicationDbContext : IdentityDbContext
    {
        private string _tenantId = "18ca9dd1-d4bc-48df-af6a-a9d1103a3d66"; // Hardcoded for demo purposes
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.Entity<Blog>().HasData(new Blog("ced767d0-b4fd-418a-99c9-0b419366d9b8"){ Id = "042ecd6b-f00a-41bd-9a2f-2af1eb63b21e" });
            builder.Entity<Blog>().Property<string>("TenantId").HasField("_tenantId");
            builder.Entity<Blog>().Property<string>("TenantId").IsRequired();
            builder.Entity<Blog>().HasQueryFilter(b => EF.Property<string>(b, "TenantId") == _tenantId);
            base.OnModelCreating(builder);
        }

    }
```

### Further technical details
EF Core version: 2.2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 16.1.1

**Comment by TrieBr** [comment]
I see the workaround in https://github.com/aspnet/EntityFrameworkCore/issues/9999 does work.
