### ISSUE TITLE
3.0.0-preview6.19304.10 Azure Cosmos DB Provider FindAsync Throws NotImplementedException

### ISSUE THREAD

**Issue by TheFanatr** [dotnet/efcore#16060]
When calling `FindAsync` on a `DbSet` that is part of a `DbContext`-derived class for an application being upgraded to use .NET Core Preview 6, a `NotImplementedException` was thrown. The exact code used is `await context.Sessions.FindAsync(new object[] { Session.ID }`, where `context` is an instance of the `DbContext`-derived class used to interact with Azure Cosmos DB for this application, and the `Sessions` property is a `DbSet<Session>` where `Session` is the model type, and `ID` is a `Guid`-type property representing the database object identifier on an instance of a `Session`-typed property which is also called "Session".

### Exception Message
```
System.NotImplementedException: The method or operation is not implemented.
```
### Stack Trace
```
System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.EntityFrameworkCore.Cosmos.Query.Pipeline.CosmosEntityQueryableTranslatorFactory.Create(QueryCompilationContext2 queryCompilationContext)
   at Microsoft.EntityFrameworkCore.Query.Pipeline.QueryCompilationContext2.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery2[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.FindAsync(Object[] keyValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.FindAsync(Object[] keyValues, CancellationToken cancellationToken)
   at UnnamedApplication.WebPlatform.Data.Interaction.Client.LoadStateAsync(LoadState state, CancellationToken cancellationToken) in C:\Users\alexf\Source\Repos\UnnamedApplication\UnnamedApplication.WebPlatform\Data\Interaction\Client.cs:line 28
```

### Steps to Produce Behavior
1. Create a new .NET Core 3 console application with .NET Core SDK 3.0.100-preview6-012264 installed on the machine.
2. Create a simple database context containing a `DbSet` for a certain model type that has a property for an instance's ID in the database.
3. In the `Program.Main` method, create an instance of the database context and use it to add an instance of the model to the database then note down the generated ID.
4. Attempt to query that specific object back out of the database using the `FindAsync` method on the `DbSet` for the specific model, using the ID noted in the previous step, as detailed at the top of this issue.

### Technical Details
EF Core version: 3.0.0-preview6.19304.10
Database Provider: Microsoft.EntityFrameworkCore.Cosmos
Operating system: Microsoft Windows 1809 Build 17763.503
IDE: Visual Studio 2019 16.2.0 Preview 2.0

### Note
I'm going to assume that while this is the latest Preview 6 release of the Cosmos DB provider, it is still not the version that is supposed to be used alongside other Preview 6 releases. The referenced version for the project that prompted this report has now been rolled back to the Preview 5 release that was in use previously.

**Comment by ajcvickers** [comment]
@TheFanatr This is a known limitation of the Cosmos provider in preview 6. The recommendation is to use preview 5 if you are using Cosmos. See [the announcement blog post](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-0-preview-6-and-entity-framework-6-3-preview-6/)

**Comment by ajcvickers** [comment]
@TheFanatr Many thanks for trying preview 6. If you haven't seen it already, there is some good information in the [preview announcement post](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-0-preview-6-and-entity-framework-6-3-preview-6/) about the changes that are happening to LINQ queries for EF Core 3.0. Preview 6 is the first release containing these changes, which means we are both expecting things to be broken, but at the same time very grateful for everyone who tries the release and generated feedback.
