### ISSUE TITLE
3.0.0-preview6.19304.10 `dotnet ef dbcontext scaffold` throw MissingMethodException when TargetFrameworks set to net4xx

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/efcore#16063]
Describe what is not working as expected.
> throw MissingMethodException when TargetFrameworks set to net4xx(.net framework)

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: System.MissingMethodException: The constructor on type "Microsoft.EntityFrameworkCore.Design.OperationExecutor" was not found.
Stack trace:
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at Microsoft.EntityFrameworkCore.Tools.AppDomainOperationExecutor..ctor(String assembly, String startupAssembly, String projectDir, String dataDirectory, String rootNamespace, String language)
   at Microsoft.EntityFrameworkCore.Tools.Commands.ProjectCommandBase.CreateExecutor()
   at Microsoft.EntityFrameworkCore.Tools.Commands.DbContextScaffoldCommand.Execute()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
```

### Steps to reproduce
1. Create an new csproj with no code, and set TargetFrameworks to net472(or any .net framework that support ns2.0), add reference to EFCore.
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.0.0-preview6.19304.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0-preview6.19304.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.0.0-preview6.19304.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```
2. Run `dotnet ef dbcontext scaffold xxx Microsoft.EntityFrameworkCore.SqlServer` with dotnet-sdk and dotnet-ef 3.0.0 preview6 installed.
```
dotnet ef --version
Entity Framework Core .NET Command-line Tools
3.0.0-preview6.19304.10

dotnet --version
3.0.100-preview6-012264
```

### Further technical details
EF Core version: 3.0.0-preview6.19304.10(not tested with old versions of 3.0.0)
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: win10-x64
IDE: not related

---

Debug see it expected an `Microsoft.EntityFrameworkCore.Design.IOperationReportHandler` but get an `System.Runtime.Remoting.Proxies.__TransparentProxy` here.
Is netfx still supported for dotnet-ef, I remember EFCore3.0 only support netcoreapp3.0(or ns2.1), or give an clear error message?

**Comment by yyjdelete** [comment]
See EFCore 3.0preview7 already remove support for ns2.0 and retarget to ns2.1 only .
And `dotnet-ef` 3.0preview6 also work well EFCore 2.2.4 with in net472, so it's no longer an issue for me.

**Comment by ajcvickers** [comment]
@yyjdelete Many thanks for trying preview 6. If you haven't seen it already, there is some good information in the [preview announcement post](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-0-preview-6-and-entity-framework-6-3-preview-6/) about the changes that are happening to LINQ queries for EF Core 3.0. Preview 6 is the first release containing these changes, which means we are both expecting things to be broken, but at the same time very grateful for everyone who tries the release and generated feedback.
