### ISSUE TITLE
Preview 6 - The data is NULL at ordinal 5

### ISSUE THREAD

**Issue by FeodorFitsner** [dotnet/efcore#16072]
Database provider: SQLite

Using `.Include()` causes **System.InvalidOperationException: The data is NULL at ordinal 5. This method can't be called on NULL values. Check using IsDBNull before calling.** exception.

This is the repro: https://github.com/FeodorFitsner/EFCorePreview6Bugs/blob/master/EFCorePreview6Bugs/Program.cs#L57-L68

Stack trace:

```
System.InvalidOperationException
  HResult=0x80131509
  Message=The data is NULL at ordinal 5. This method can't be called on NULL values. Check using IsDBNull before calling.
  Source=Microsoft.Data.Sqlite
  StackTrace:
   at Microsoft.Data.Sqlite.SqliteValueReader.GetInt64(Int32 ordinal)
   at Microsoft.Data.Sqlite.SqliteValueReader.GetInt32(Int32 ordinal)
   at Microsoft.Data.Sqlite.SqliteDataReader.GetInt32(Int32 ordinal)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalShapedQueryCompilingExpressionVisitor.IncludeCompilingExpressionVisitor.IncludeCollection[TEntity,TIncludedEntity](QueryContext queryContext, DbDataReader dbDataReader, TEntity entity, Func`3 outerKeySelector, Func`3 innerKeySelector, Func`4 innerShaper, INavigation navigation, INavigation inverseNavigation, Action`2 fixup, Boolean trackingQuery, ResultCoordinator resultCoordinator)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EFCorePreview6Bugs.Program.TheDataIsNull() in C:\Projects\Samples\EFCorePreview6Bugs\EFCorePreview6Bugs\Program.cs:line 62
   at EFCorePreview6Bugs.Program.Main(String[] args) in C:\Projects\Samples\EFCorePreview6Bugs\EFCorePreview6Bugs\Program.cs:line 40

```

The code works fine with EF Core Preview 5.

**Comment by ajcvickers** [comment]
@FeodorFitsner First, many thanks for trying preview 6. If you haven't seen it already, there is some good information in the [preview announcement post](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-0-preview-6-and-entity-framework-6-3-preview-6/) about the changes that are happening to LINQ queries for EF Core 3.0. Preview 6 is the first release containing these changes, which means we are both expecting things to be broken, but at the same time very grateful for everyone who tries the release and generated feedback.

We believe that this issue is already tracked by #15611, so closing this as a duplicate.
