### ISSUE TITLE
Preview 6 - No data exists for the row/column.

### ISSUE THREAD

**Issue by FeodorFitsner** [dotnet/efcore#16073]
Database provider: SQLite

EF Core version: 3.0 Preview 6

Using `.Include()` causes **System.InvalidOperationException: 'No data exists for the row/column.'** exception. Might be related to https://github.com/aspnet/EntityFrameworkCore/issues/16072

This is the repro: https://github.com/FeodorFitsner/EFCorePreview6Bugs/blob/master/EFCorePreview6Bugs/Program.cs#L70-L81

Stack trace:

```
System.InvalidOperationException
  HResult=0x80131509
  Message=No data exists for the row/column.
  Source=Microsoft.Data.Sqlite
  StackTrace:
   at Microsoft.Data.Sqlite.SqliteDataRecord.IsDBNull(Int32 ordinal)
   at Microsoft.Data.Sqlite.SqliteDataReader.IsDBNull(Int32 ordinal)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalShapedQueryCompilingExpressionVisitor.IncludeCompilingExpressionVisitor.IncludeCollection[TEntity,TIncludedEntity](QueryContext queryContext, DbDataReader dbDataReader, TEntity entity, Func`3 outerKeySelector, Func`3 innerKeySelector, Func`4 innerShaper, INavigation navigation, INavigation inverseNavigation, Action`2 fixup, Boolean trackingQuery, ResultCoordinator resultCoordinator)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EFCorePreview6Bugs.Program.NoDataExistsForRowColumn() in C:\Projects\Samples\EFCorePreview6Bugs\EFCorePreview6Bugs\Program.cs:line 75
   at EFCorePreview6Bugs.Program.Main(String[] args) in C:\Projects\Samples\EFCorePreview6Bugs\EFCorePreview6Bugs\Program.cs:line 41
```

The code works fine with EF Core Preview 5.

**Comment by ajcvickers** [comment]
@FeodorFitsner As I said on the other issue, many thanks for trying preview 6. If you haven't seen it already, there is some good information in the [preview announcement post](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-0-preview-6-and-entity-framework-6-3-preview-6/) about the changes that are happening to LINQ queries for EF Core 3.0. Preview 6 is the first release containing these changes, which means we are both expecting things to be broken, but at the same time very grateful for everyone who tries the release and generated feedback.

We believe that this issue is already tracked by #15611, so closing this as a duplicate.
