### ISSUE TITLE
Preview 6 - NotImplementedException on nullable query

### ISSUE THREAD

**Issue by BenjaminAbt** [dotnet/efcore#16087]
We query nullable information in our query, which works great in Preview 5.

```cs
var q = set.Select(m => new
            {
                m.Id,
                m.Subject,
                m.SentOn,
                SenderId = m.Sender == null ? (int?)null : m.Sender.Id,
                SenderUsername = m.Sender == null ? null : m.Sender.Username,
                RecipientId = m.Recipient == null ? (int?)null : m.Recipient.Id,
                RecipientUsername = m.Sender == null ? null : m.Recipient.Username,
            });
```
In Preview 6 we now get a NotImplemented Exception..
```
Exception message: NotImplementedException 
Stack trace:

Source: GetReceivedPrivateMessagesOfUserCommandHandlerTests.cs line: 40
   Duration: 884 ms
  Message: System.NotImplementedException : The method or operation is not implemented.
  Stack Trace: 
    at InMemoryQueryableMethodTranslatingExpressionVisitor.TranslateLeftJoin(ShapedQueryExpression outer, ShapedQueryExpression inner, LambdaExpression outerKeySelector, LambdaExpression innerKeySelector, LambdaExpression resultSelector)
    at QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    at MethodCallExpression.Accept(ExpressionVisitor visitor)
    at ExpressionVisitor.Visit(Expression node)
    at QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    at MethodCallExpression.Accept(ExpressionVisitor visitor)
    at ExpressionVisitor.Visit(Expression node)
    at QueryCompilationContext2.CreateQueryExecutor[TResult](Expression query)
    at <>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
    at CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
    at QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
    at EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
    at IAsyncEnumerable<TResult>.GetEnumerator()
    at AsyncEnumerable.Aggregate_[TSource,TAccumulate,TResult](IAsyncEnumerable`1 source, TAccumulate seed, Func`3 accumulator, Func`2 resultSelector, CancellationToken cancellationToken) in Aggregate.cs line: 118
    at GetReceivedPrivateMessagesOfUserCommandHandler.Handle(GetReceivedPrivateMessagesOfUserCommand request, CancellationToken cancellationToken) in GetReceivedPrivateMessagesOfUserCommandHandler.cs line: 58
    at GetReceivedPrivateMessagesOfUserCommandHandlerTests.Handle_Should_Return_Items_By_Skip_And_Take(Int32 expectedUserId) in GetReceivedPrivateMessagesOfUserCommandHandlerTests.cs line: 73
    at --- End of stack trace from previous location where exception was thrown ---
```

### Steps to reproduce

Works:

```c#
       var q = set.Select(m => new
            {
                m.Id,
                SenderId = 1,
            });
```

Fails:

```cs
       var q = set.Select(m => new
            {
                m.Id,
                SenderId = m.Sender == null ? (int?)null : m.Sender.Id,
            });
```

### Further technical details
EF Core version: 3.0.0-preview6.19304.10
Database Provider: `microsoft.entityframeworkcore.inmemory\3.0.0-preview6.19304.10` (Unit Test)
Operating system: Windows 10 with VS 2019 16.2 Pre 1

**Comment by BenjaminAbt** [comment]
It seems that this falls under the case described in the changelog that this is not supported (anymore)  with this preview.
Reason: working on LINQ.

**Comment by ajcvickers** [comment]
@BenjaminAbt First, many thanks for trying preview 6. If you haven't seen it already, there is some good information in the [preview announcement post](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-0-preview-6-and-entity-framework-6-3-preview-6/) about the changes that are happening to LINQ queries for EF Core 3.0. Preview 6 is the first release containing these changes, which means we are both expecting things to be broken, but at the same time very grateful for everyone who tries the release and generated feedback.

For the in-memory database, we believe this is covered by #15711, so closing as a duplicate.
