### ISSUE TITLE
Query source (from vwUserSearch <generated>_1 in [grouping1]) has already been associated with an expression.

### ISSUE THREAD

**Issue by MaryadaPurshottam** [dotnet/efcore#16220]
I have sql view which i query further using linq. I'm doing a group by as below. However when the last line executes it gives me the dreaded error. I have not been able to figure it out. Any help would be appreciated. Thanks!

```
Exception message: Query source (from vwUserSearch <generated>_1 in [grouping1]) has already been associated with an expression.
Stack trace:
   at Remotion.Linq.Clauses.QuerySourceMapping.AddMapping(IQuerySource querySource, Expression expression)
   at Remotion.Linq.Clauses.MainFromClause.Clone(CloneContext cloneContext)
   at Remotion.Linq.QueryModel.Clone(QuerySourceMapping querySourceMapping)
   at Remotion.Linq.QueryModel.CloningExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
   at Remotion.Linq.Clauses.Expressions.SubQueryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMember(MemberExpression node)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Clauses.SelectClause.TransformExpressions(Func`2 transformation)
   at Remotion.Linq.QueryModel.TransformExpressions(Func`2 transformation)
   at Remotion.Linq.QueryModel.Clone(QuerySourceMapping querySourceMapping)
   at Remotion.Linq.QueryModel.CloningExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
   at Remotion.Linq.Clauses.Expressions.SubQueryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMember(MemberExpression node)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Clauses.FromClauseBase.TransformExpressions(Func`2 transformation)
   at Remotion.Linq.QueryModel.TransformExpressions(Func`2 transformation)
   at Remotion.Linq.QueryModel.Clone(QuerySourceMapping querySourceMapping)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryOptimizer.FlattenSubQuery(SubQueryExpression subQueryExpression, IFromClause fromClause, QueryModel queryModel, Int32 destinationIndex)
   at Remotion.Linq.Transformations.SubQueryFromClauseFlattener.VisitMainFromClause(MainFromClause fromClause, QueryModel queryModel)
   at Remotion.Linq.Clauses.MainFromClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.TransformingQueryModelExpressionVisitor`1.VisitSubQuery(SubQueryExpression expression)
   at Remotion.Linq.Clauses.Expressions.SubQueryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Clauses.WhereClause.TransformExpressions(Func`2 transformation)
   at Remotion.Linq.QueryModel.TransformExpressions(Func`2 transformation)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryOptimizer.Optimize(QueryCompilationContext queryCompilationContext, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, Boolean asyncQuery)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, Boolean asyncQuery)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Linq.SystemCore_EnumerableDebugView`1.get_Items()
```

### Steps to reproduce
```c#
var userClientSignupClaims =
                view.GroupBy(ucc => ucc.AspNetUsersId).Select(grouping1 => new UserSearchResultDto.UserClientSignupClaims
                {
                    AspNetUsersId = grouping1.First().AspNetUsersId,
                    AspNetUser = new UserIdentityDto { UserName = grouping1.First().Username },
                    ClientSignupClaimses = grouping1.GroupBy(g => g.ClientId).Select(grouping2 => new UserSearchResultDto.ClientSignupClaims
                    {
                        ClientId = grouping2.First().ClientId,
                        Client = new ClientDto { Id = grouping2.First().ClientId },
                        SignupClaims = grouping2.Select(h => new { h.SignupClaim, h.SignupClaimValue }).Distinct().ToDictionary(z => z.SignupClaim, z => z.SignupClaimValue),
                        ApprovalGroups = grouping2.Select(z => z.ApprovalGroupId).Distinct(),
                        AspNetRoles = grouping2.Where(g => !string.IsNullOrEmpty(g.AspNetRolesId)).Select(s => s.AspNetRolesId).Distinct(),
                    }),
                });

 var query = userClientSignupClaims.Select(x => new UserSearchResultDto
            {
                Clients =
                    userClientSignupClaims
                        .Single(y => y.AspNetUsersId == x.AspNetUsersId)
                        .ClientSignupClaimses.Select(s => s.ClientId)
          });

 if (dto.SystemId.HasValue)
 **_Error at this line->_** query = query.Where(x => x.Clients.Any(y => y == dto.SystemId.Value));


```

### Further technical details
EF Core version: (2.2.3)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by MaryadaPurshottam** [comment]
It works if I changed Clients to be of type int[] and then did a ToArray when loading it. But i think doing toarray is just weird as it would brings stuff in memory which is inefficient. 

 var query = userClientSignupClaims.Select(x => new UserSearchResultDto
            {
                Clients =
                    userClientSignupClaims
                        .Single(y => y.AspNetUsersId == x.AspNetUsersId)
                        .ClientSignupClaimses.Select(s => s.ClientId)**.ToArray()**
          });

**Comment by smitpatel** [comment]
Nested groupbys are not supported. see #17068
