### ISSUE TITLE
EF generating invalid query - using pluralised table name, despite snapshot explicitly specifying (correctly)

### ISSUE THREAD

**Issue by gram197880** [dotnet/efcore#16241]
```
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Credentials'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source)
```

### Steps to reproduce
Relevant part of snapshot:

```c#

            modelBuilder.Entity("REDACTED.Storage.Model.Credential", b =>
                {
                    b.Property<string>("Key")
                        .ValueGeneratedOnAdd();
                    b.Property<string>("Json");
                    b.Property<Guid>("UserId");
                    b.HasKey("Key");
                    b.HasIndex("UserId");
                    b.ToTable("Credential");
                });
```

User code:

```c#
            var match = _context.Set<Credential>()
                .Where(c => c.Key == credentialKey)
                .Select(c => c.Json)
                .SingleOrDefault();
```

Generated SQL:

```sql
      SELECT TOP(2) [c].[Json]
      FROM [Credentials] AS [c]
      WHERE [c].[Key] = @__credentialKey_0
```

Note - the only reference to `"Credentials"` is the name of the navigation property pointing to the `Credential` entity:

```c#
            modelBuilder.Entity("REDACTED.Storage.Model.Credential", b =>
                {
                    b.HasOne("REDACTED.Storage.Model.User", "User")
                        .WithMany("Credentials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
```

### Further technical details
EF Core version: `Microsoft.EntityFrameworkCore, Version=2.2.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60`
Database Provider: `Microsoft.EntityFrameworkCore.SqlServer`
Operating system: `Azure App Service`

Weird things:

- The table was created successfully via migration, with the correct name
- This same process works fine locally (same code version, same deploy)
- Other tables and queries work fine immediately prior to this one

Is there anything I can do to diagnose?

**Comment by smitpatel** [comment]
Are you configuring `Credential` to use non-pluralized name in EF Core model building. (outside of model snapshot)? Did you edit model snapshot yourself?

**Comment by gram197880** [comment]
@smitpatel No to both of those questions.  I'm using the default table name and it's the generated snapshot.

```C#  
  public class CredentialConfiguration : EntityMappingConfiguration<Credential>
  {
      public override void Map(EntityTypeBuilder<Credential> b)
      {
          b.HasKey(c => c.Key);
      }
  }
```

**Comment by smitpatel** [comment]
If that is the case, then we need full repro code. If model is generating snapshot like that and it should also use the same thing in queries/update.

**Comment by gram197880** [comment]
I had an unused (no references)

```C#

        public DbSet<Credential> Credentials { get; set; }

```

in my Context.  

I've removed it and the query is now working as expected.
