### ISSUE TITLE
Insert: using a key-column with datatype: datetime2(3) fails - datetime2(7) works

### ISSUE THREAD

**Issue by Garios** [dotnet/efcore#16295]
```sql
MSSQL-Table:
Timestamp datetime2(3) [Primary-Key]
Description varchar(100)
```

```C#
public class Table{
 DateTime Timestamp {get;set;}
string Description{get;set;}
}

entity.Property(e => e.Timestamp)
                    .HasColumnType("datetime2(3)");

Table t = new Table {Timestamp=DateTime.Now, Description="test"};
db.Table.Add(t);
db.Table.SaveChanges();
```

> EF-Log:
> Insert: 1 row affected
> Select: 0 rows affected (Concurrency-Check)
> FAILS

If I change the database-type to datetime2(7), it works.

I assume, that the precision isn't used in the timestamp-parameter. So that the full .NET-DateTime-Value is passed.
Unfortunately, EF-Log doesn't show the real passed DateTime-Value. It prints only "yyyy-MM-ddTHH:mm:ss"

```
Exception
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithPropagationAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

### Further technical details
EF Core version: preview6
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by ajcvickers** [comment]
Unable to repro this; bringing back to triage.

Attempt:

```C#
public class Table
{
    public DateTime Timestamp { get; set; }
    public string Description { get; set; }
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(Your.ConnectionString)
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Table>(b =>
        {
            b.Property(e => e.Timestamp).HasColumnType("datetime2(3)");
            b.HasKey(e => e.Timestamp);

            b.Property(e => e.Description).HasColumnType("varchar(100)");
        });
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var t = new Table { Timestamp = DateTime.Now, Description = "test" };
            context.Add(t);

            Console.WriteLine(context.SaveChanges());
        }

        using(var context = new SomeDbContext())
        {
            var t = context.Set<Table>().Single();
            t.Description = "Changed";
            Console.WriteLine(context.SaveChanges());
        }
    }
}
```

```
warn: 9/12/2021 21:10:47.681 CoreEventId.SensitiveDataLoggingEnabledWarning[10400] (Microsoft.EntityFrameworkCore.Infrastructure)
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
info: 9/12/2021 21:10:47.762 CoreEventId.ContextInitialized[10403] (Microsoft.EntityFrameworkCore.Infrastructure)
      Entity Framework Core 5.0.9 initialized 'SomeDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: SensitiveDataLoggingEnabled
info: 9/12/2021 21:10:47.942 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (10ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
info: 9/12/2021 21:10:47.970 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
      IF SERVERPROPERTY('EngineEdition') <> 5
      BEGIN
          ALTER DATABASE [FiveOh] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
      END;
info: 9/12/2021 21:10:47.978 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (8ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
      DROP DATABASE [FiveOh];
info: 9/12/2021 21:10:48.108 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (123ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
      CREATE DATABASE [FiveOh];
info: 9/12/2021 21:10:48.147 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (38ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
      IF SERVERPROPERTY('EngineEdition') <> 5
      BEGIN
          ALTER DATABASE [FiveOh] SET READ_COMMITTED_SNAPSHOT ON;
      END;
info: 9/12/2021 21:10:48.150 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
info: 9/12/2021 21:10:48.206 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE [Table] (
          [Timestamp] datetime2(3) NOT NULL,
          [Description] varchar(100) NULL,
          CONSTRAINT [PK_Table] PRIMARY KEY ([Timestamp])
      );
info: 9/12/2021 21:10:48.348 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (22ms) [Parameters=[@p0='2021-09-12T21:10:48.2105500+01:00' (Precision = 3), @p1='test' (Size = 100) (DbType = AnsiString)], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [Table] ([Timestamp], [Description])
      VALUES (@p0, @p1);
1
info: 9/12/2021 21:10:48.359 CoreEventId.ContextInitialized[10403] (Microsoft.EntityFrameworkCore.Infrastructure)
      Entity Framework Core 5.0.9 initialized 'SomeDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: SensitiveDataLoggingEnabled
info: 9/12/2021 21:10:48.494 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT TOP(2) [t].[Timestamp], [t].[Description]
      FROM [Table] AS [t]
info: 9/12/2021 21:10:48.506 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (1ms) [Parameters=[@p1='2021-09-12T21:10:48.2110000' (Precision = 3), @p0='Changed' (Size = 100) (DbType = AnsiString)], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      UPDATE [Table] SET [Description] = @p0
      WHERE [Timestamp] = @p1;
      SELECT @@ROWCOUNT;
1
```

**Comment by AndriySvyryd** [comment]
Seems to have been fixed at some point
