### ISSUE TITLE
Could not load type Microsoft.EntityFrameworkCore.Internal.LazyRef

### ISSUE THREAD

**Issue by rlebowitz** [dotnet/efcore#16325]
Trying to reverse engineer a local db running on SQLExpress.  Running the Scaffold-DbContext command from the Package Manager Console.  Have tried many variations where I specify minimal parameters and sometimes all possible parameters.  Have run as admin and non-admin users.

Saw similar errors reported in earlier releases, the underlying issue may not yet be resolved.

Command example (have tried many other variations):
Scaffold-DbContext "Data Source=.\SQLExpress;Initial Catalog=MailTool;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models

Always results in following stack trace:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Internal.LazyRef`1' from assembly 'Microsoft.EntityFrameworkCore, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor..ctor(Object reportHandler, IDictionary args)
   --- End of inner exception stack trace ---
 at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Microsoft.EntityFrameworkCore.Tools.ReflectionOperationExecutor..ctor(String assembly, String startupAssembly, String projectDir, String dataDirectory, String rootNamespace, String language)
   at Microsoft.EntityFrameworkCore.Tools.Commands.ProjectCommandBase.CreateExecutor()
   at Microsoft.EntityFrameworkCore.Tools.Commands.DbContextScaffoldCommand.Execute()
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)

EF Core version: 3.0.0-preview6.19304.10
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Enterprise 10.0.17134 Build 17134
IDE: Visual Studio 2019 v. 16.2.0 Preview 3.0

**Comment by divega** [comment]
Sounds like it is a mix of an older version of Microsoft.EntityFrameworkCore.Design which still used LazyRef<T\> and the 3.0-preview6 version of Microsoft.EtnityFrameworkCore that doesn't define the type anymore.

**Comment by rlebowitz** [comment]
You were correct; I recently upgraded several things on my workstation, and the preview checkbox on the Nuget tab was unchecked such that I installed version 2.2.4 instead of the one for the preview version.  The models were constructed as expected.  Thank you
