### ISSUE TITLE
Query :: Bad sql generated for query with bool parameter in filter

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#1642]
Repro:

```
    public class Customer
    {
        public int Id { get; set; }
    }

    public class Order
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Order> Orders { get; set; }

        protected override void OnConfiguring(DbContextOptions options)
        {
            options.UseSqlServer(new SqlConnectionStringBuilder { DataSource = ".", InitialCatalog = "Repro1642", MultipleActiveResultSets = true, IntegratedSecurity = true }.ToString());
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();
            }

            using (var ctx = new MyContext())
            {
                ctx.Customers.OrderBy(o => ClientEvalSelectorStateless()).Where(o => ClientEvalPredicateStateless()).Count(c => ClientEvalPredicate(c));
            }
        }

        public static bool ClientEvalPredicateStateless()
        {
            return true;
        }

        protected static bool ClientEvalPredicate(Customer customer)
        {
            return customer.Id > 1;
        }

        private static int ClientEvalSelectorStateless()
        {
            return 42;
        }
    }
```

Exception:

Unhandled Exception: System.Data.SqlClient.SqlException: An expression of non-bo
olean type specified in a context where a condition is expected, near '@__Client
EvalPredicateStateless_1'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolea
n breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception
, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObj
ect stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand
 cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler,
TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, Run
Behavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBe
havior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 time
out, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehav
ior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletio
nSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehav
ior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, S
tring method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behav
ior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.Data.Entity.Relational.Query.QueryingEnumerable`1.Enumerator.Mov
eNext() in D:\k\EntityFramework\src\EntityFramework.Relational\Query\QueryingEnu
merable.cs:line 74
   at System.Linq.Enumerable.<SelectManyIterator>d__8`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at lambda_method(Closure )
   at Microsoft.Data.Entity.Query.LinqOperatorProvider.ExceptionInterceptor`1.En
umeratorExceptionInterceptor.MoveNext() in D:\k\EntityFramework\src\EntityFramew
ork.Core\Query\LinqOperatorProvider.cs:line 91
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.Query.CompiledQueryCache.Execute[TResult](Expression
 query, DataStore dataStore, QueryContext queryContext) in D:\k\EntityFramework\
src\EntityFramework.Core\Query\CompiledQueryCache.cs:line 75
   at Microsoft.Data.Entity.Query.EntityQueryProvider.Execute[TResult](Expressio
n expression) in D:\k\EntityFramework\src\EntityFramework.Core\Query\EntityQuery
Provider.cs:line 59
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source, Expression`1 pre
dicate)
   at Repro1642.Program.Main(String[] args) in D:\Projects\Repro1642\Repro1642\P
rogram.cs:line 41

**Comment by maumar** [comment]
fixed in ef46f6c295d50ac24c07a84e877ab76a42bfd8dc
