### ISSUE TITLE
In SQL UniqueIdentifier field type is nullable, but EF doesn't allow it? Why the inconsistency?

### ISSUE THREAD

**Issue by BrianMinister** [dotnet/efcore#16490]
When generating the DB via code first, I was expecting to be able to set my guids as nullable, since they are ref types, but EF doesn't allow that in migrations, even though if I build the DB first, I can make my UniqueIdentifiers nullable.

The field I want to make nullable is a foreign key, which is why it works so well in SQL.

### Stack trace
```
System.InvalidOperationException: The property 'ForOrganizationId' on entity type 'JwtRecords' cannot be marked as nullable/optional because the type of the property is 'Guid' which is not a nullable type. Any property can be marked as non-nullable/required, but only properties of nullable types and which are not part of primary key can be marked as nullable/optional.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Property.SetIsNullable(Nullable`1 nullable, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalPropertyBuilder.IsRequired(Nullable`1 required, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder.IsRequired(Boolean required)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder`1.IsRequired(Boolean required)
   at UserPortal.Server.Database.DefaultDBContext.OnModelCreating(ModelBuilder mb) in C:\PrivCode\UserPortal\UserPortal.Server\Database\DefaultContext.cs:line 74
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The property 'ForOrganizationId' on entity type 'JwtRecords' cannot be marked as nullable/optional because the type of the property is 'Guid' which is not a nullable type. Any property can be marked as non-nullable/required, but only properties of nullable types and which are not part of primary key can be marked as nullable/optional.
```

### Steps to reproduce

Models:
```
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.SqlServer;
using Microsoft.AspNetCore.Identity;


namespace UserPortal.Server.Database
{
    public class DefaultDBContext : IdentityDbContext<ApplicationUser, ApplicationRole, Guid>
    {
        public DefaultDBContext(DbContextOptions<DefaultDBContext> options) : base(options)
        {

        }

        public DbSet<ApplicationOrgURL> OrgUrls { get; set; }

        public DbSet<ApplicationOrganization> Organizations { get; set; }

        public DbSet<JwtRecords> JwtRecords { get; set; }

        protected override void OnModelCreating(ModelBuilder mb)
        {
            base.OnModelCreating(mb);

            mb.Entity<ApplicationOrganization>()
                .HasOne<ApplicationUser>(n=>n.Owner)
                .WithMany(n=>n.OwnedOrganizations)
                .HasForeignKey(n=>n.OwnedById)
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired(false);

            mb.Entity<ApplicationRole>()
                .HasOne<ApplicationRole>(n => n.ManagedBy)
                .WithMany()
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired(false);

            mb.Entity<ApplicationUser>()
                .HasMany<ApplicationUserInOrg>(n=>n.UserInOrganizations)
                .WithOne(n=>n.User)
                .HasForeignKey(n=>n.UserId)
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired(false);

            mb.Entity<ApplicationOrganization>()
                .HasMany<ApplicationUserInOrg>(n=>n.UserInOrgs)
                .WithOne(n=>n.Org)
                .HasForeignKey(n=>n.OrgId)
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired(false);

            mb.Entity<JwtRecords>()
                .HasOne<ApplicationOrganization>(n=>n.ForOrganization)
                .WithMany(n=>n.JwtRecs)
                .HasForeignKey(n => n.ForOrganizationId)
                .IsRequired(false);

            mb.Entity<JwtRecords>()
                .HasOne<ApplicationUser>(n => n.RequestedByUser)
                .WithMany(n => n.JwtRecs)
                .HasForeignKey(n => n.RequestedByUserId)
                .IsRequired(false);

            mb.Entity<JwtRecords>()
                .Property<Guid>(n => n.ForOrganizationId)
                .IsRequired(false);

            mb.Entity<JwtRecords>()
                .Property<Guid>(n => n.RequestedByUserId)
                .IsRequired(false);


        }
    }

    public class ApplicationUser : IdentityUser<Guid>
    {
        [StringLength(8, MinimumLength = 8, ErrorMessage = "Pin numbers must be 8 digits long.")]
        [RegularExpression("[0-9]*", ErrorMessage = "Pin number must be numeric digits only.")]
        [Required]
        public string PIN { get; set; }

        public List<ApplicationUserInOrg> UserInOrganizations { get; set; }
        public List<ApplicationOrganization> OwnedOrganizations { get; set; }

        public List<JwtRecords> JwtRecs { get; set; }

        [NotMapped]
        public List<ApplicationOrganization> Organizations => 
            UserInOrganizations.Select(n=>n.Org)
            .ToList();
    }

    public class ApplicationRole : IdentityRole<Guid>
    {
        public Guid OrganizationId { get; set; }
       
        public ApplicationOrganization Organization { get; set; }

        public ApplicationRole ManagedBy { get; set; }

    }

    public class ApplicationOrganization
    {
        [Key]
        public Guid Id { get; set; }
        
        [Required]
        [StringLength(255, MinimumLength =5, ErrorMessage ="Name must be between 5 and 255 characters")]
        public string OrgFullName { get; set; }

        [Required]
        [StringLength(255, MinimumLength = 5, ErrorMessage = "URL friendly Name must be between 5 and 255 characters")]
        [RegularExpression(@"[0-9a-zA-Z\-+%]", ErrorMessage ="Only alpha numeric characters, hyphen, plus, and percent, are allowed.")]
        public string OrgUrlFriendlyName { get; set; }

        public Guid OwnedById { get; set; }

        public ApplicationUser Owner { get; set; }

        public List<ApplicationOrgURL> Urls { get; set; }

        public List<ApplicationUserInOrg> UserInOrgs { get; set; }

        public List<ApplicationRole> Roles { get; set; }

        public List<JwtRecords> JwtRecs { get; set; }

        [NotMapped]
        public List<ApplicationUser> Users => UserInOrgs
            .Select(n => n.User)
            .ToList();
    }

    public class ApplicationOrgURL
    {
        [Key]

        public Guid Id { get; set; }

        public Guid ParentOrgId { get; set; }

        public Guid UrlExpression { get; set; }

        public ApplicationOrganization Organization { get; set; }
    }

    public class ApplicationUserInOrg
    {
        [Key]
        public Guid Id { get; set; }

        public Guid UserId { get; set; }

        public Guid OrgId { get; set; }

        public ApplicationUser User { get; set; }
        public ApplicationOrganization Org { get; set; }
    }

    public class JwtRecords
    {
        public Guid Id { get; set; }

        public Guid RequestedByUserId { get; set; }

        public ApplicationUser RequestedByUser { get; set; }

        public Guid ForOrganizationId { get; set; }

        public ApplicationOrganization ForOrganization { get; set; }
        [Required]
        public string SecurityKey { get; set; }

        [Required]
        public string Issuer { get; set; }

        [Required]
        [DefaultValue(14)]
        public int ExpirationInDays { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime DateRequested { get; set; }
    }
}

```

### Further technical details
EF Core version: 3.0 latest
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 10 64bit
IDE: Visual Studio 2019 Preview

**Comment by BrianMinister** [comment]
I found the fix, I changed `Guid` to `Nullable<Guid>`.

**Comment by IanYates** [comment]
Was gonna suggest that fix for you.
Issue is in first sentence... Guid is a value type, not a reference type. Hence the need for Guid? aka Nullable<Guid>.
