### ISSUE TITLE
Multiple Include collection causes SqlNullValueException

### ISSUE THREAD

**Issue by paviad** [dotnet/efcore#16516]
EF throws a:
```
    System.Data.SqlTypes.SqlNullValueException: Data is Null.
        This method or property cannot be called on Null values.
```
When running this code:
```C#
    var shipments = _dc.Shipments.Where(x => x.Id == 1141)
                       .Include(x => x.ShipmentAttachments)
                       .Include(x => x.ShipmentItems)
                       .ToList();
```
(If I remove either of the `Include` calls it works fine with no exceptions)

Against this database:
```sql
	CREATE TABLE [dbo].[Shipments] (
		[Id]             INT            NOT NULL,
		PRIMARY KEY CLUSTERED ([Id] ASC)
	);

    INSERT INTO [dbo].[Shipments] ([Id]) VALUES (1141);

	CREATE TABLE [dbo].[ShipmentItems] (
		[Id]             INT            NOT NULL,
		[ShipmentId]     INT            NOT NULL,
                [CatNo]          NVARCHAR (220) NOT NULL,
		PRIMARY KEY CLUSTERED ([Id] ASC),
	);

	INSERT INTO [dbo].[ShipmentItems] ([Id], [ShipmentId], [CatNo]) VALUES (726, 1141, N'R1')
	INSERT INTO [dbo].[ShipmentItems] ([Id], [ShipmentId], [CatNo]) VALUES (727, 1141, N'R2')
	INSERT INTO [dbo].[ShipmentItems] ([Id], [ShipmentId], [CatNo]) VALUES (728, 1141, N'R3')

	CREATE TABLE [dbo].[ShipmentAttachments] (
		[ShipmentId] INT NOT NULL,
		[DocumentId] INT NOT NULL,
		CONSTRAINT [PK_ShipmentAttachments] PRIMARY KEY
                CLUSTERED ([ShipmentId] ASC, [DocumentId] ASC),
	);
```
Using this `DbContext` model configuration:
```C#
    public class SmDataContext : DbContext {
        public SmDataContext(DbContextOptions options) : base(options) { }

        protected override void OnModelCreating(ModelBuilder modelBuilder) {
            modelBuilder.Entity<ShipmentAttachment>()
                .HasKey(x => new { x.DocumentId, x.ShipmentId });
        }

        public DbSet<Shipment> Shipments { get; set; }
        public DbSet<ShipmentItem> ShipmentItems { get; set; }
        public DbSet<ShipmentAttachment> ShipmentAttachments { get; set; }
    }

    public class Shipment {
        [Key]
        public int Id { get; set; }
        [ForeignKey("ShipmentId")]
        public IEnumerable<ShipmentItem> ShipmentItems { get; set; }
        [ForeignKey("ShipmentId")]
        public IEnumerable<ShipmentAttachment> ShipmentAttachments { get; set; }
    }

    public class ShipmentItem {
        [Key]
        public int Id { get; set; }
        public int ShipmentId { get; set; }
        public string CatNo { get; set; }
    }

    public class ShipmentAttachment {
        public int ShipmentId { get; set; }
        public int DocumentId { get; set; }
    }
```

Which results in the following SQL query:
```sql
      SELECT [s].[Id], [s0].[DocumentId], [s0].[ShipmentId], [s0].[DocumentId],
          [s0].[ShipmentId], [s1].[Id], [s1].[CatNo], [s1].[ShipmentId]
      FROM [Shipments] AS [s]
      LEFT JOIN [ShipmentAttachments] AS [s0] ON [s].[Id] = [s0].[ShipmentId]
      LEFT JOIN [ShipmentItems] AS [s1] ON [s].[Id] = [s1].[ShipmentId]
      WHERE [s].[Id] = 1141
      ORDER BY [s].[Id], [s0].[DocumentId], [s0].[ShipmentId]
```
This is the callstack of the exception:
```
    System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
       at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
       at Microsoft.Data.SqlClient.SqlBuffer.get_Int32()
       at Microsoft.Data.SqlClient.SqlDataReader.GetInt32(Int32 i)
       at lambda_method(Closure , QueryContext , DbDataReader )
       at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalShapedQueryCompilingExpressionVisitor.IncludeCompilingExpressionVisitor.IncludeCollection[TEntity,TIncludedEntity](QueryContext queryContext, DbDataReader dbDataReader, TEntity entity, Func`3 outerKeySelector, Func`3 innerKeySelector, Func`4 innerShaper, INavigation navigation, INavigation inverseNavigation, Action`2 fixup, Boolean trackingQuery, ResultCoordinator resultCoordinator)
       at lambda_method(Closure , QueryContext , DbDataReader , ResultCoordinator )
       at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
```
The most likely culprit is this:

https://github.com/aspnet/EntityFrameworkCore/blob/a71fcc98c0be2e688da55cd1c9975eb76aac9a45/src/EFCore.Relational/Query/Pipeline/IncludeCompilingExpressionVisitor.cs#L124

Running the query itself directly against the sql database causes no issues, the query runs successfully and returns a result set like this:

    Id   DocumentId ShipmentId DocumentId ShipmentId Id  CatNo ShipmentId
    1141 NULL       NULL       NULL       NULL       726 R1    1141
    1141 NULL       NULL       NULL       NULL       727 R2    1141
    1141 NULL       NULL       NULL       NULL       728 R3    1141

**Comment by ajcvickers** [comment]
@paviad What version of EF Core are you using?

**Comment by paviad** [comment]
These libraries are used:
Microsoft.EntityFrameworkCore 3.0.0-preview6.19304.10
Microsoft.EntityFrameworkCore.SqlServer 3.0.0-preview6.19304.10

**Comment by paviad** [comment]
TBH If I look at the tip of master it looks like this bug has already been addressed. Any estimate on when the next release is?

**Comment by ajcvickers** [comment]
First, many thanks for trying preview 6. We really appreciate people trying the previews and filing issues on what they find.

If you haven't seen it already, there is some good information in the [preview announcement post](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-0-preview-6-and-entity-framework-6-3-preview-6/) about the changes that are happening to LINQ queries for EF Core 3.0. Preview 6 is the first release containing these changes, which means we are both expecting things to be broken, but at the same time very grateful for everyone who tries the release and generated feedback.

As you say, this issue is fixed in the nightly build and will be fixed in preview 7, which is coming soon.
