### ISSUE TITLE
NullReferenceException on UserManager:CreateAsync using In-Memory provider

### ISSUE THREAD

**Issue by Elfocrash** [dotnet/efcore#16533]
I have the following line that creates a user in Identity with EF Core using SQL Server and .NET Core 2.2.
`var createdUser = await _userManager.CreateAsync(newUser, password);`

The user manager is Identity's `UserManager` class. I am using the default `IdentityUser` class and I am using the following lines for DI registration.

```
services.AddDefaultIdentity<IdentityUser>().AddEntityFrameworkStores<DataContext>();
```

Upon upgrading to `3.0.0-preview6.19304.10` and changing this to use the in-memory provider this line throws the `NullReferenceException` that can be found below. Note here that if i use the in-memory provider in 2.2 it works as intended.

```
Exception message: Object reference not set to an instance of an object.
Stack trace:    at Microsoft.EntityFrameworkCore.Storage.ValueBuffer.get_Item(Int32 index)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.TryReadValue[TValue](ValueBuffer& valueBuffer, Int32 index, IPropertyBase property)
   at lambda_method(Closure , QueryContext , IEnumerator`1 )
   at Microsoft.EntityFrameworkCore.InMemory.Query.Pipeline.InMemoryShapedQueryCompilingExpressionVisitor.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Pipeline.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByNameAsync(String userName)
   at Microsoft.AspNetCore.Identity.UserValidator`1.ValidateUserName(UserManager`1 manager, TUser user, ICollection`1 errors)
   at Microsoft.AspNetCore.Identity.UserValidator`1.ValidateAsync(UserManager`1 manager, TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.ValidateUserAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user, String password)
   at MyProject.Services.IdentityService.RegisterAsync(String email, String password) in C:\Users\myself\Rider\Projects\MyProject\Services\IdentityService.cs:line 49
```

### Further technical details
EF Core version: 3.0.0-preview6.19304.10
Database Provider: Microsoft.EntityFrameworkCore.InMemory
Operating system: Windows 10
IDE: Rider 2019.2

**Comment by Elfocrash** [comment]
I just saw the post here regarding the Ef core 3 preview 6: https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-0-preview-6-and-entity-framework-6-3-preview-6/

I am assuming this is the reason?

**Comment by ajcvickers** [comment]
@Elfocrash Correct; we are currently in the process of getting the in-memory provider functional again.
