### ISSUE TITLE
The type of navigation property on the entity type is for which it was not possible to create a concrete instance

### ISSUE THREAD

**Issue by svfaust** [dotnet/efcore#16567]
So, go on
it's work fine with relationship:
.Include(x=>x.Person)
.Include(x=>x.DocActType)
.Include(x=>x.DocActStateType)
.Include(x=>x.Vehicle)

But when i use this .Include("CompanyDelivery") or this .Include(x=>x.CompanyDelivery) i have exceptions.
It's a some magic, this relations look alike x.person, diference with 
that relation named by class, but CompanyDelivery do not like alike Company.

And i have bug alike this above when i try include DocActDetails - if it can help something

```
Exception message:
System.InvalidOperationException: The type of navigation property 'DeliveryDocActs' on the entity type 'Company' is 'IQueryable<DocAct>' for which it was not possible to create a concrete instance. Either initialize the property before use, add a public parameterless constructor to the type, or use a type which can be assigned a HashSet<> or List<>.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrICollectionAccessor`3.GetOrCreateCollection(Object instance)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrICollectionAccessor`3.Add(Object instance, Object value)
   at lambda_method(Closure , DocAct , Company )
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalShapedQueryCompilingExpressionVisitor.IncludeCompilingExpressionVisitor.IncludeReference[TEntity,TIncludedEntity](QueryContext queryContext, DbDataReader dbDataReader, TEntity entity, Func`4 innerShaper, INavigation navigation, INavigation inverseNavigation, Action`2 fixup, Boolean trackingQuery, ResultCoordinator resultCoordinator)
   at lambda_method(Closure , QueryContext , DbDataReader , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
Stack trace:
```

```c#
public IQueryable<DocAct> GetAll()
        {
            //return _dbContext.DocActs.Include(docAct => docAct.DocActDetails).AsNoTracking();
            return _dbContext.DocActs.Include(x=>x.Person)
                                    .Include(x=>x.DocActType)
                                    .Include(x=>x.DocActStateType)
                                    .Include(x=>x.Vehicle)
                                    .Include("CompanyDelivery")
                                    //.Include(x=>x.CompanyDelivery)
                                    //.Include(x=>x.CompanyRecipient)
                                    .AsNoTracking();
        }



public class DocAct : BaseEntity
    {
        public Guid DocActID { get; set; }

        public string DocActNumber { get; set; }

        public long DocActNumberBy { get; set; }

        public DateTime DocActDate { get; set; }

        public decimal DocActTotalSum { get; set; }


        #region Relation

        public Guid DocActTypeID { get; set; }
        public DocActType DocActType { get; set; }

        public Guid CompanyRecipientID { get; set; }
        public Company CompanyRecipient { get; set; }

        public Guid CompanyDeliveryID { get; set; }
        public Company CompanyDelivery { get; set; }

        public Guid DocActStateTypeID { get; set; }
        public DocActStateType DocActStateType { get; set; }

        public Guid VehicleID { get; set; }
        public Vehicle Vehicle { get; set; }

        public Guid PersonID { get; set; }
        public Person Person { get; set; }

        public IQueryable<DocActDetail> DocActDetails { get; set; }

        #endregion

        #region Not Mapped

        [NotMapped]
        public string DocActTypeName
        {
            get { return this.DocActType?.Name; }
        }

        [NotMapped]
        public string DocActPersonName
        {
            get { return this.Person?.PersonName; }
        }

        [NotMapped]
        public string DocActCompanyRecipientName
        {
            get { return this.CompanyRecipient?.CompanyShortName; }
        }

        [NotMapped]
        public string DocActCompanyDeliveryName
        {
            get { return this.CompanyDelivery?.CompanyShortName; }
        }

        [NotMapped]
        public string DocActPaymentState
        {
            get { return "Реализовать"; }
        }

        [NotMapped]
        public string DocActVehicleName
        {
            get { return this.Vehicle?.VehicleFullName; }
        }

        #endregion
    }
```

### Further technical details
EF Core version: 3.0.0-preview6.19307.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: windows 10 x64
IDE: Visual Studio 2019

**Comment by ajcvickers** [comment]
@svfaust What is the intention behind defining the navigation property as `IQueryable`?
```C#
 public IQueryable<DocActDetail> DocActDetails { get; set; }
```

**Comment by svfaust** [comment]
Sorry. I check itSorry. I get it.
It thing very clever.
when it get class Company Recipient or Company Delivery, it is no stopping.
it go deeper and it try to resolving Company and catching 
```
public class Company
{
....
public HashSet<DocAct> RecipientDocActs { get; set; } 
}
```
so i do this and it worked
```
    public class Company : BaseEntity
    {

        public Company()
        {
            RecipientDocActs = new HashSet<DocAct>();
            DeliveryDocActs = new HashSet<DocAct>();
        }
...
}
```
