### ISSUE TITLE
Can EF Core track entities in non topmost projections?

### ISSUE THREAD

**Issue by mnissl** [dotnet/efcore#16636]
I have to to load entities (which feature a user_id column) alongside a field of a related table (the name of the user) and I would like my entities to be tracked. Hence I use a projection that encapuslates my entity and that features a property which I assign that field of the related table ... which works as described in the EF Core documentation: <https://docs.microsoft.com/en-us/ef/core/querying/tracking#tracking-and-projections>.

Now my entity is involved in a 1:n relationship. I need to load the related entities and I also would like to use the same approach as above; alas those entities are not tracked by EF Core.

When I read #12761, it gave me the clue that tracking only works for topmost projections, not for projections of related entities.

In the example below, products are tracked, but components are not:
```c#
      var entities = context.Products.Select(p =>
          new ProductWrapper
          {
            Entity = p,
            UserName = p.UserNavigation.Name,
            Components = p.Components.Select(c => new ComponentWrapper
            {
              Entity = c,
              UserName = c.UserNavigation.Name
            })
          });
```

Is this a bug? A missing feature? Any workarounds or better solutions?

In this specific case, I could go for eager loading (via `Include()`), but that loads the whole `User` entity (which I don't need). But I'm more interested in an approach that allows me to add any kind of data (like an aggregate value) to my entity: the entity itself is editable by the user (therefore I need tracking), the extra data is read-only.

  [1]: https://github.com/aspnet/EntityFrameworkCore/issues/12761

#### Further technical details
EF Core version: 2.2.6
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 1903
IDE: Visual Studio 2019 16.6

**Comment by ajcvickers** [comment]
@mnissl The expectation, at least for 3.0, is that both `p` and `c` will be tracked.

Triage: in 2.2, only `p` is tracked. With current nightlies it throws:

```
Unhandled exception. System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalProjectionBindingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.Pipeline.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Pipeline.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.Main() in C:\Stuff\InterceptorsDemo\InterceptorsDemo\InterceptorsDemo\Program.cs:line 103
```

**Comment by mnissl** [comment]
I asked this question on [StackOverflow](https://stackoverflow.com/questions/57058982/can-ef-core-track-entities-in-non-topmost-projections) where I was given the advice to manually `Include()` the related entities and that did work. With this workaround, surprisingly I didn't have to expose the `Entity` property with a public setter anymore; passing the entity to the contructors of the projection types made EF track them. Will this also be the case in version 3.0 then?

**Comment by ajcvickers** [comment]
@mnissl Please post the code for the new query.

**Comment by mnissl** [comment]
Here's my workaround that works with EF Core 2.2.6 where both p and c get tracked:

```cs
        var entities = context.Products
          .Include(p => p.Components)
          .Select(p => new ProductWrapper(p)
          {
            UserName = p.UserNavigation.Name,
            Components = p.Components.Select(c => new ComponentWrapper(c)
            {
              UserName = c.UserNavigation.Name
            })
          });
```

**Comment by ajcvickers** [comment]
@mnissl I just tried with EF Core 3 preview 7 and all entities were tracked.
