### ISSUE TITLE
Relationship from entity to query fails

### ISSUE THREAD

**Issue by paillave** [dotnet/efcore#16650]
I am not able to create a navigation property from an entity to a query.
I get the following error:
`The query type 'View1' cannot be added to the model because an entity type with the same name already exists.`

# This fails

```bash
dotnet new classlib -f netcoreapp2.2 -o PbEf
dotnet add package Microsoft.EntityFrameworkCore.Design
dotnet add package Microsoft.EntityFrameworkCore.SqlServer
```
Use this code:

```c#
/// <summary>
/// This is actually what I really would like to have working
/// </summary>
using Microsoft.EntityFrameworkCore;

namespace PbEf
{
    public class Table1
    {
        public int Id { get; set; }
        public View1 View1 { get; set; }
    }
    public class View1
    {
        public int Table1Id { get; set; }
    }
    public class MyContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("a connection string");
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var table1Entity = modelBuilder.Entity<Table1>();
            table1Entity.ToTable(nameof(Table1));
            table1Entity.HasKey(i => i.Id);
            table1Entity.Property(i => i.Id).UseSqlServerIdentityColumn();
            table1Entity.HasOne(i => i.View1).WithOne().HasForeignKey<View1>(i => i.Table1Id);
            var view1Query = modelBuilder.Query<View1>(); // we assume this view already exists in the DB
            view1Query.ToView(nameof(View1));
        }
    }
}
```

or this code:

```c#
/// <summary>
/// This is not exactly what I would like, but I could easily deal with it
/// </summary>
using Microsoft.EntityFrameworkCore;

namespace PbEf
{
    public class Table1
    {
        public int Id { get; set; }
        public List<View1> View1s { get; set; }
    }
    public class View1
    {
        public int Table1Id { get; set; }
    }
    public class MyContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("a connection string");
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var table1Entity = modelBuilder.Entity<Table1>();
            table1Entity.ToTable(nameof(Table1));
            table1Entity.HasKey(i => i.Id);
            table1Entity.Property(i => i.Id).UseSqlServerIdentityColumn();
            table1Entity.HasMany(i => i.View1s).WithOne().HasForeignKey(i => i.Table1Id);
            var view1Query = modelBuilder.Query<View1>(); // we assume this view already exists in the DB
            view1Query.ToView(nameof(View1));
        }
    }
}
```

```bash
dotnet ef migrations add Initial
```

```
System.InvalidOperationException: The query type 'View1' cannot be added to the model because an entity type with the same name already exists.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(EntityType entityType)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Query(TypeIdentity& type, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Query(Type clrType, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.ModelBuilder.Query[TQuery]()
   at PbEf.MyContext.OnModelCreating(ModelBuilder modelBuilder) in /home/stephane/Documents/Sources/PbEf/Class1.cs:line 30
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

# Strangely, with this code it works

But that's not at all what I'd like to deal with

```c#
/// <summary>
/// This is far less convenient as I can't get a table1 instance to send to automapper with computations coming from a view
/// </summary>
using Microsoft.EntityFrameworkCore;

namespace PbEf
{
    public class Table1
    {
        public int Id { get; set; }
    }
    public class View1
    {
        public int Table1Id { get; set; }
        public Table1 Table1 { get; set; }
    }
    public class MyContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("a connection string");
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var table1Entity = modelBuilder.Entity<Table1>();
            table1Entity.ToTable(nameof(Table1));
            table1Entity.HasKey(i => i.Id);
            table1Entity.Property(i => i.Id).UseSqlServerIdentityColumn();
            var view1Query = modelBuilder.Query<View1>(); // we assume this view already exists in the DB
            view1Query.ToView(nameof(View1));
            view1Query.HasOne(i => i.Table1).WithMany().HasForeignKey(i => i.Table1Id);
        }
    }
}
```

**Comment by smitpatel** [comment]
QueryTypes can have navigation to entity types but EntityTypes cannot contain navigation to query type.
Please review differences between EntityType and QueryType in our docs https://docs.microsoft.com/en-us/ef/core/modeling/query-types#compare-query-types-to-entity-types

**Comment by paillave** [comment]
Ok I see... 

> Entities cannot contain navigation properties to query types

Is there any plan to permit this in the future? Because it is a **very** severe restriction for the usage of query types!
