### ISSUE TITLE
Cannot build latest master

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#16656]
Running command line build of latest master fails with:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "Microsoft.Build.Tasks.Git.LocateRepository" task failed unexpectedly.
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.Build.Tasks.Git.GitEnvironment.FindSystemDirectory() in /_/src/Microsoft.Build.Tasks.Git/GitDataReader/GitEnvironment.cs:line 88
   at Microsoft.Build.Tasks.Git.GitEnvironment.CreateFromProcessEnvironment() in /_/src/Microsoft.Build.Tasks.Git/GitDataReader/GitEnvironment.cs:line 79
   at Microsoft.Build.Tasks.Git.GitEnvironment.Create(String configurationScope) in /_/src/Microsoft.Build.Tasks.Git/GitDataReader/GitEnvironment.cs:line 64
   at Microsoft.Build.Tasks.Git.RepositoryTask.GetOrCreateRepositoryInstance() in /_/src/Microsoft.Build.Tasks.Git/RepositoryTask.cs:line 112
   at Microsoft.Build.Tasks.Git.RepositoryTask.ExecuteImpl() in /_/src/Microsoft.Build.Tasks.Git/RepositoryTask.cs:line 65
   at Microsoft.Build.Tasks.Git.RepositoryTask.Execute() in /_/src/Microsoft.Build.Tasks.Git/RepositoryTask.cs:line 43
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	EFCore.Analyzers	C:\Users\Erik\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta2-19351-01\build\Microsoft.Build.Tasks.Git.targets	24	

```

**Comment by smitpatel** [comment]
Running fine for me. Can you do all the cleaning rituals and try again?

**Comment by ajcvickers** [comment]
@ErikEJ Are you still having issues? Anything we can help with?

**Comment by ErikEJ** [comment]
I had similar issue on a second machine, and it was because I did not have the latest preview 6 SDK installed (from June 12), but an earlier one. I will close this, wising there was a way to have a check of some sort at the start of the build process, it took me a few attempts to figure out. But I guess it is all a point in time issue.

**Comment by ErikEJ** [comment]
Did all the cleaning, installed the correct SDK, build still failing with same error !?

**Comment by ErikEJ** [comment]
I a running from a fork and has a origin and upstream remotes (unlike you guys do) - I wonder if this is related to this recent bug fix, which is not in the package currently used by EF Core build: https://github.com/dotnet/sourcelink/commit/855afb5af9ea79e63dd9c051a7cfe0941bbb5ced 

(EF Core build uses the previous package version: 1.0.0-beta2-19351-01 )

**Comment by ErikEJ** [comment]
OK, it turns out this piece of code assumes that git.exe is in the PATH - and of course that is not the case on either of my machines! 

https://github.com/dotnet/sourcelink/blob/master/src/Microsoft.Build.Tasks.Git/GitDataReader/GitEnvironment.cs#L125 

It seems like a steep requirement for a build to succeed - but at least a more helpful error message would be useful!

**Comment by ErikEJ** [comment]
I have created an issue in the sourcelink repo

**Comment by ajcvickers** [comment]
Thanks for getting to the bottom of this @ErikEJ!

**Comment by ErikEJ** [comment]
Is this something that should be added to the wiki? (Building the code wiki page)

**Comment by tmat** [comment]
This is a bug. Source Link does not require git.exe isntalled on the machine. It's already been fixed: https://github.com/dotnet/sourcelink/issues/337, included in Arcade via https://github.com/dotnet/arcade/pull/3302.
