### ISSUE TITLE
Multiple DB Context In One Solution

### ISSUE THREAD

**Issue by DaGrisa** [dotnet/efcore#16663]
We have a solution with multiple DB Contexts (in different projects), but all on the same database (but one DB Context per schema). When i now choose one of these projects in the "Package Manager Console" an run "update-database" it runs the migrations for some random DB Contexts, not only the one from the project I have chosen (even if I select the project's context explicitly with update-database -Context DbContext).
The funny thing is, that it creates the other DB Context randomly, not all of them. So when i run the update-database for one project multiple times on an empty DB, it then has creates all schemas for all DB context.

The same problem occurs when I start the program: I have to start it multiple times so that all schemas are created. As seen in the exception below, EF tries to create the DB that already exists.

```
Exception message: 
CREATE DATABASE [XXX]; System.Data.SqlClient.SqlException (0x80131904): Database 'XXX' already exists. Choose a different database name.

Stack trace:
CREATE DATABASE [XXX]; System.Data.SqlClient.SqlException (0x80131904): Database 'XXX' already exists. Choose a different database name.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
ClientConnectionId:c03d6cdf-d7fc-435c-ab92-38536efe3a09
Error Number:1801,State:3,Class:16|url: |action:
```

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.11

**Comment by ajcvickers** [comment]
@DaGrisa Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing so that we can investigate.

**Comment by DaGrisa** [comment]
Here is a small exmaple which behaves the same way: 
https://github.com/DaGrisa/ef-core-multiple-dbcontexts
When you start it for the first time, only one schema is created. When you start the second time, the other two are created.

**Comment by ajcvickers** [comment]
@DaGrisa At a first glance, this:
```C#
dbContext.Database.MigrateAsync();
```
is certainly an issue since the async call is not being awaited. If there are still issues after that is fixed, then I'll look some more.

**Comment by DaGrisa** [comment]
Thank you very much, now it works!
