### ISSUE TITLE
TargetInvocationException thrown when reading row from table

### ISSUE THREAD

**Issue by shravan2x** [dotnet/efcore#16683]
I use the `MySql.Data.EntityFrameworkCore` package version version `8.0.16` to interact with a MySql 8.0 database. I encounter the following error when fetching a row from the table (simply reading the `COUNT` of the table works fine). I'm creating an issue here since the stack trace shows the issue arising from EF, not the MySql package.

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'System.Func`3[System.Int64,System.Int64,System.Boolean]' to type 'System.Func`3[System.UInt32,System.UInt32,System.Boolean]'.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.SimplePrincipalKeyValueFactory`1.NoNullsCustomEqualityComparer..ctor(ValueComparer comparer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.SimplePrincipalKeyValueFactory`1..ctor(IProperty property)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.KeyValueFactoryFactory.CreateSimpleFactory[TKey](IKey key)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.KeyValueFactoryFactory.Create[TKey](IKey key)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Key.GetPrincipalKeyValueFactory[TKey]()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMapFactoryFactory.CreateFactory[TKey](IKey key)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMapFactoryFactory.Create(IKey key)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetOrCreateIdentityMap(IKey key)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.TryGetEntry(IKey key, ValueBuffer& valueBuffer, Boolean throwOnNullKey)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.UnbufferedEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at System.Linq.Queryable.First[TSource](IQueryable`1 source)
   at TestLabCore.Program.<Main>(String[] args)
```

### Steps to reproduce

Create a schema `test` using the code below:
```sql
CREATE DATABASE `test` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

CREATE TABLE `accounts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `server` varchar(45) NOT NULL,
  `username` varchar(45) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `test`.`accounts` (`server`, `username`) VALUES ('testserver', 'testusername');
```

Create a C# context class:
```c#
public class TestContext : DbContext
{
    public DbSet<Account> Accounts { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseMySQL("server=localhost;database=test;user=root;password=<your_password>");
    }

    public class Account
    {
        public uint Id { get; set; }
        public string Server { get; set; }
        public string Username { get; set; }
    }
}
```

Then run this code:
```c#
TestContext tc = new TestContext();
Console.WriteLine(tc.Accounts.Count());
Console.WriteLine(JsonConvert.SerializeObject(tc.Accounts.First()));
```

### Further technical details
EF Core version: `2.2.6`
Database Provider: `MySql.Data.EntityFrameworkCore`
Operating system: `Windows 10`
IDE: `Visual Studio 2019`

**Comment by ajcvickers** [comment]
@shravan2x This looks like an issue with type mapping in the MySql provider. Please [follow up with Oracle](https://dev.mysql.com/) on the issue. You might also give the [open-source Pomelo MySql](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql) provider a try.

**Comment by shravan2x** [comment]
@ajcvickers Oracle's tracking system is too slow and inconvenient for me, and I've had bad experiences there in the past, but the Pomelo provider works like a charm. Thanks for the recommendation!
