### ISSUE TITLE
.NET Core Tracking bug

### ISSUE THREAD

**Issue by cj748s16** [dotnet/efcore#16774]
Welcome !

I have 2 tables: Document, Customer. The document is referencing to the customer via CustomerId field.

When I want to update a document, I loaded it from the DB via the the following LINQ command:

```C#
_var documents = await this.documentService
	.Query(d => string.Equals(d.Barcode, doc.Barcode, StringComparison.InvariantCultureIgnoreCase))
	.Include(d => d.Customer)
	.Take(2)
	.ToArrayAsync().ConfigureAwait(false);_

Here are the "this.documentService.Query(...)" implementation:
        _public virtual IQueryable<TEntity> Query(Expression<Func<TEntity, bool>> predicate = null)
        {
            var result = this.Repository.Entities.AsNoTracking();
            if (predicate != null)
            {
                result = result.Where(predicate);
            }
            return result;
        }_
```
and the "this.Repository.Entities":  _... = this.dbSet.AsQueryable();_

When I got back only 1 document, I do the required checks and modifications, and executes the dbContext.Documents.Update command.

In this case, I get the following exception:
**(The instance of entity type 'Document' cannot be tracked because another instance with the key value '{Id: 17203}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.)**

After spending couple of hours to investigate this, I got the following conclusion:
the `.Include(d => d.Customer)` cause the exception, but I don't know why.

1) the exception doesn't mention to this property, entity, ...
2) why does it cause error when updating an entity which has a filled navigation property via EFCore?, I checked it, the program didn't do anything with this (now, I removed the .Include(), currently isn't necessary).
2) In the other case, when I executes the DbSet.Add command, the EFCore wanna insert the Customer too, not just use the existing one's Id value.

Exception message:
The instance of entity type 'Document' cannot be tracked because another instance with the key value '{Id: 17208}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.

Stack trace:
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NullableKeyIdentityMap`1.Add(InternalEntityEntry entry)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node, Boolean force)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode node, TState state, Func`3 handleNode)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode node, TState state, Func`3 handleNode)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode node, TState state, Func`3 handleNode)
at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
at ....RepositoryBase`1.Update(TEntity entity) in ...
at ....LogicServiceBase`1.<UpdateAsync>d__27.MoveNext() in ...
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
at DocuDepo.BusinessLogic.Services.Document.DocumentService.<UpdateAsync>d__2.MoveNext() in ...
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
at DocuDepo.BusinessLogic.Services.Transaction.EntryDemand.EntryDemandService.<GetDocumentAsync>d__17.MoveNext() in ...
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
at DocuDepo.BusinessLogic.Services.Transaction.EntryDemand.EntryDemandService.<AddOrUpdateDocumentsAndDocumentBoxesAsync>d__14.MoveNext() in ...
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
at DocuDepo.BusinessLogic.Services.Transaction.EntryDemand.EntryDemandService.<AddOrUpdateNewAsync>d__13.MoveNext() in ...
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
at DocuDepo.BusinessLogic.Services.Transaction.EntryDemand.EntryDemandService.<UpdateAsync>d__10.MoveNext() in ...

### Steps to reproduce
Created a demo application, which is available from GDrive: https://drive.google.com/open?id=1EotkvU7zsQXYVVHxTgwiYGN-ZOgxPySk

The program is working perfectly, if I comment the DemoExecuter.cs's 57th line.
```

### Further technical details
EF Core version: 2.2.4
Database Provider: .SqlServer 2.2.4
Operating system: Microsoft Windows [Version 10.0.18362.266]
IDE: Visual Studio 2019 Preview 16.3.0 Preview 1.0

**Comment by ajcvickers** [comment]
@cj748s16 The exception is being thrown because the graph being attached to the context has two different `Document` instances with the same ID:

![image](https://user-images.githubusercontent.com/1430078/68906743-30e31300-06fa-11ea-83e0-c37c0c9fb74e.png)
