### ISSUE TITLE
migration apply incorrect syntax near ')'

### ISSUE THREAD

**Issue by asoet** [dotnet/efcore#1677]
Beta4-12325,
When I try to apply a migration.

Below my stacktrace:

k ef migration apply
Using context 'calContext'.
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ')'.
Incorrect syntax near ')'.
Incorrect syntax near ')'.
Incorrect syntax near ')'.
Incorrect syntax near ')'.
Incorrect syntax near ')'.
Incorrect syntax near ')'.
Incorrect syntax near ')'.
Incorrect syntax near ')'.
Incorrect syntax near ')'.
Incorrect syntax near ')'.
Incorrect syntax near ')'.
Incorrect syntax near ')'.
Incorrect syntax near ')'.
Incorrect syntax near ')'.
Incorrect syntax near ')'.
Incorrect syntax near ')'.
Incorrect syntax near ')'.
Incorrect syntax near ')'.
Incorrect syntax near ')'.
Incorrect syntax near ')'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.Data.Entity.Relational.SqlStatementExecutor.<>c__DisplayClass7_0.<ExecuteNonQuery>b__0()
   at Microsoft.Data.Entity.Relational.SqlStatementExecutor.Execute(RelationalConnection connection, Func1 action)
   at Microsoft.Data.Entity.Relational.SqlStatementExecutor.ExecuteNonQuery(RelationalConnection connection, DbTransaction transaction, IEnumerable1 sqlBatches)
   at Microsoft.Data.Entity.Relational.Migrations.Migrator.Execute(IEnumerable1 sqlBatches, Boolean first)
   at Microsoft.Data.Entity.Relational.Migrations.Migrator.ApplyMigrations(String targetMigration)
   at Microsoft.Data.Entity.Commands.MigrationTool.ApplyMigration(String migrationName, String contextTypeName)
   at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass11_0.<ApplyMigration>b__0()
   at Microsoft.Data.Entity.Commands.Program.ExecuteInDirectory(String startupProject, Func1 invoke)
   at Microsoft.Data.Entity.Commands.Program.ApplyMigration(String migration, String context, String startupProject)
   at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass8_2.<Main>b__8()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Data.Entity.Commands.Program.Main(String[] args)
ClientConnectionId:ddf40d5d-a3df-489e-a979-439d8c1e7a33
Error Number:102,State:1,Class:15

**Comment by swaggerloaf** [comment]
Take a look at #1612
Maybe due to FK scripting?

**Comment by asoet** [comment]
Yes the same problem.
