### ISSUE TITLE
Allow DefaultValueSql when using ForSqlServerUseSequenceHiLo

### ISSUE THREAD

**Issue by LeroyK** [dotnet/efcore#16814]
With EF Core 3.0, setting ``DefaultValueSql`` when ``ForSqlServerUseSequenceHiLo`` is used on a property (or vice versa) throws an exception. In 2.2.6 this worked fine and I was using it to set ``DefaultValueSql`` to ``"NEXT VALUE FOR [Schema].[SequenceName]"``.

```
Exception message:
   SqlServerValueGenerationStrategy cannot be set for 'Id' at the same time as DefaultValueSql. Remove one of these values.

Stack trace:
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.SqlServerStoreGenerationConvention.Validate(IConventionProperty property)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.StoreGenerationConvention.ProcessModelFinalized(IConventionModelBuilder modelBuilder, IConventionContext`1 context)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelFinalized(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelFinalized(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FinalizeModel()
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_ChangeTracker()
```

### Steps to reproduce
```c#
    class Program
    {
        public static string ConnectionString = "Server=.\\SQLEXPRESS;Database=ExampleDb;MultipleActiveResultSets=true;Integrated Security=true";

        static void Main(string[] args)
        {
            var options = new DbContextOptionsBuilder()
                .UseSqlServer(ConnectionString)
                .Options;

            var db = new ExampleContext1(options);
            db.ChangeTracker.Entries();
        }
    }

    public class ExampleContext1 : DbContext
    {
        public DbSet<Example> Examples { get; set; }

        public ExampleContext1(DbContextOptions options) : base(options) { }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder
                .Entity<Example>()
                .Property(x => x.Id)
                .HasDefaultValueSql("NEXT VALUE FOR [Example_Id]")
                .ForSqlServerUseSequenceHiLo("Example_Id");

            base.OnModelCreating(modelBuilder);
        }
    }

    public class Example
    {
        public long Id { get; set; }
    }
```

### Further technical details
EF Core version: 3.0.0-preview7.19362.6
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 1903
IDE: Visual Studio 2019 16.3.0. Preview 1

**Comment by ajcvickers** [comment]
@LeroyK I can't really see any meaningful way they can be used together. Is your expectation that values should be obtained using the hi-lo pattern? Or that they should be generated on insert using `NEXT VALUE FOR [Example_Id]`? Or am I missing something?

**Comment by LeroyK** [comment]
Yes, it should be obtained using the hi-lo pattern when using EF. If I recall correctly that uses the sequence.

What I want to accomplish is that whenever someone adds a record to the database without using EF, a new Id will be generated using that sequence.

**Comment by ajcvickers** [comment]
@LeroyK Interesting. And what is your motivation for using the hi-lo pattern as opposed to having EF use the same mechanism for inserting that other insertions will use?

**Comment by LeroyK** [comment]
@ajcvickers Using hi-lo allows me to assign an Id beforehand using ``DbSet<>.AddAsync()``

**Comment by ajcvickers** [comment]
@LeroyK Thanks for the info; we will discuss.

**Comment by ajcvickers** [comment]
Note from triage: we should change this to a warning, set to throw by default, since its still much more common to see people getting this wrong--that is, thinking that they are using hi-lo when they are not, or thinking that they are using a normal sequence, when they are using one setup with an increment suitable for hi-lo.

**Comment by maleu1** [comment]
I apologize in advance for the spam, but is this going to translated into a warning soon? I kind of have the same situation as @LeroyK. Editing the migrations is not exactly suitable to be a longterm solution.

**Comment by lajones** [comment]
@ajcvickers Presume you would like the same "warning which by default throws" action to apply to `DefaultValue` and `ComputedColumnSql` which use the same error?

**Comment by lajones** [comment]
Note: "yes" is answer to above. Plus we will also do the same thing for the `Identity` strategy that we were planning for the `HiLo` strategy.
