### ISSUE TITLE
Weird issue with C# generated SQL command

### ISSUE THREAD

**Issue by TehWardy** [dotnet/efcore#17009]
So I have this C# ...

```
log.Debug($"Dropping folder {folderId} with script:\n{fileScript}\n{folderScript}");
await Database.ExecuteSqlCommandAsync($"{fileScript}\n{folderScript}");
log.Debug($"Folder {folderId} Drop complete!");
```

When i run this I get this in my log ...

```
2019-08-07 14:23:50,802 [7] DEBUG  Core.Data.CoreDataContext - Dropping folder 6eabb3a1-846e-4456-ef7c-08d71b33e6ac with script:

DELETE FROM [DMS].[Folders] WHERE Id = '6eabb3a1-846e-4456-ef7c-08d71b33e6ac' 

2019-08-07 14:23:50,851 [9] ERROR  Api.Startup - The name '' is not a valid identifier.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlCommandAsync(DatabaseFacade databaseFacade, RawSqlString sql, IEnumerable`1 parameters, CancellationToken cancellationToken)
   at Core.Data.CoreDataContext.DeleteFolder(Guid folderId) in D:\Core Prototype\Everything\Core\Data\CoreDataContext.cs:line 264
   at Core.Services.Core.FolderService.DeleteAsync(Guid id) in D:\Core Prototype\Everything\Core\Services\Core\FolderService.cs:line 56
   at Core.Api.EntityODataController`3.Delete(TKey key) in D:\Core Prototype\Everything\Core.API\Controllers\EntityODataController.cs:line 160
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context) 
```
It hasn't performed the operation and as you can see it's thrown an exception which i've caught globally in the app startup class.
If I take the SQL script from the log and run it on the db it runs fine.

So is there some magical thing about running Sql commands I need to know about EFCore as this ran fine in EF6? 

Essentially what i'm trying to do is a recursive deletion of tree structure rows from multiple tables in the DB but because this is a new DB and a fresh rebuild from EF6 to EFCore I'm testing with literally just 1 row in the "DMS.Folders" table so that the script generated is as simple as it can be.

I'm running on the latest version of EF core (excluding betas) under .Net Core 2.2

Any ideas?

**Comment by TehWardy** [comment]
hmmm ... so apparently i've discovered that I can't give it a string in this situation but instead i have to give it a RawSqlString which I guess it considers "safer" and thus won't tamper with it ...

await Database.ExecuteSqlCommandAsync(new RawSqlString($"{fileScript}\n{folderScript}"));

... This is however giving me a warning baout potential Sql injection ... the only "user input" this whole method accepts is a guid so i'm not worried about it.

This is a sort of edge case that I wouldn't expect to be repeated much if at all that requires a bit of recursion so i figured it best to generate a flat script manually.

Is there a best practice method to having EF handle recursion scenarios that doesn't take this "not advised" manual path?

Essentially the data in question is data about virtual files and folders for a DMS implementation.

**Comment by ajcvickers** [comment]
@TehWardy See the discussion in #10996 and the other issues linked from it. You are running into bad API design around interpolated strings in 2.2. We made significant changes in 3.0 to (hopefully) make this less confusing and safer.
