### ISSUE TITLE
System.InvalidOperationException is thrown when accessing data from a DB view from scaffolded DbContext

### ISSUE THREAD

**Issue by djcrawford** [dotnet/efcore#17030]
System.InvalidOperationException is thrown when accessing data from a DB view from scaffolded DbContext

```
Exception message:
System.InvalidOperationException: 'A tracking query contains entityType without key in final result.'
Stack trace:
   at Microsoft.EntityFrameworkCore.Query.Pipeline.ShapedQueryCompilingExpressionVisitor.EntityMaterializerInjectingExpressionVisitor.ProcessEntityShaper(EntityShaperExpression entityShaperExpression)
   at Microsoft.EntityFrameworkCore.Query.Pipeline.ShapedQueryCompilingExpressionVisitor.EntityMaterializerInjectingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Pipeline.ShapedQueryCompilingExpressionVisitor.EntityMaterializerInjectingExpressionVisitor.Inject(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Pipeline.ShapedQueryCompilingExpressionVisitor.InjectEntityMaterializer(Expression expression)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalShapedQueryCompilingExpressionVisitor.VisitShapedQueryExpression(ShapedQueryExpression shapedQueryExpression)
   at Microsoft.EntityFrameworkCore.Query.Pipeline.ShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Pipeline.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Collections.Generic.IEnumerable<TEntity>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EfCoreTest.Program.Main(String[] args) in <path_to_projects_parent_folder>\EfCoreTest\EfCoreTest\Program.cs:line 12
```

### Steps to reproduce
1. Create a view in your DB.
2. Scaffold-DbContext "<your_connection_string_here>" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models
3. Try to access the data from the view. The code I am using is shown below:
```c#
new <your_scaffolded_context>().<dbset_representing_your_view>.ToList();
```

### Further technical details
EF Core version: 3.0.0-preview7.19362.6
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Enterprise 16299.1268
IDE: Visual Studio 2019 16.2.0

**Comment by ErikEJ** [comment]
Have you tried with AsNoTracking() ?

**Comment by crawforddj** [comment]
Thank you for your response. It will work if you explicitly call  "AsNoTracking" on the DbSet every time you call it. That is my current workaround on the project.

The behavior I was expecting was that the "HasNoKey" on the entity would have established the entity as a read-only entity and the framework would know not to track it.

**Comment by ajcvickers** [comment]
Notes from triage: current design for 3.0 is that AsNoTracking needs to be called because we don't do it automatically for keyless entity types. However, having to call `AsNoTracking` every time is a bit of a pain--would be nice if there was something that could be done in the model that would mark the entity type as always no-tracking.

**Comment by ajcvickers** [comment]
Filed #17030 to make the 3.0 experience better here.
