### ISSUE TITLE
Can not add EntityId to Child OwnedType

### ISSUE THREAD

**Issue by hitaspdotnet** [dotnet/efcore#17096]
```C#
    public class Listing : Entity<Guid>
    {
        public BuildingDetails BuildingDetails { get; set; }
    }

    [Owned]
    public class BuildingDetails : ValueObject<BuildingDetails>
    {
        public List<Room> Rooms { get; set; }
    }

    [Owned]
    public class Room : ValueObject<Room>
    {
       public int RoomNumber { get; set; }  // object index + 1 

        public bool IsMaster { get; set; }

        public double Area {  get; set; }
    }

    modelBuilder.Entity<Listing>( x => {
        x.OwnsOne(x => x.BuildingDetails, y => {
              y.OwnsMany(z => z.Rooms, room => {
                     room.HasForeignKey("ListingId");
                     room.Property<int>("RoomNumber");
                     room.HasKey("ListingId", "RoomNumber");
                     room.ToTable("RealEstateBuldingDetailsRooms");
              });
             y.ToTable("RealEstateBuldingDetails");
       });
       x.ToTable("RealEstateListing");
    });
```
### Further technical details
EF Core version: Version="2.2.6"
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by ajcvickers** [comment]
@hitaspdotnet Please post the exception message and stack trace.

**Comment by hitaspdotnet** [comment]
@ajcvickers issue was fixed when I removed `[Owned]` attribute from `Room` & `BuildingDetails` classes.
**ST:**
```
PM> add-migration Test_1
System.InvalidOperationException: The property 'ListingId' cannot be added to the type 'BuildingDetails' because there was no property type specified and there is no corresponding CLR property or field. To add a shadow state property the property type must be specified.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.AddProperty(String name, Type propertyType, MemberInfo memberInfo, ConfigurationSource configurationSource, Nullable`1 typeConfigurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.AddProperty(String name, Type propertyType, ConfigurationSource configurationSource, Nullable`1 typeConfigurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(Property existingProperty, String propertyName, Type propertyType, MemberInfo clrProperty, Nullable`1 configurationSource, Nullable`1 typeConfigurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(String propertyName, Type propertyType, MemberInfo memberInfo, Nullable`1 configurationSource, Nullable`1 typeConfigurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.GetActualProperties(IReadOnlyList`1 properties, Nullable`1 configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.Attach(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.RelationshipSnapshot.Attach(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.OwnedTypesConvention.Apply(InternalModelBuilder modelBuilder, EntityType type)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnEntityTypeRemoved(InternalModelBuilder modelBuilder, EntityType type)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.RunVisitor.VisitOnEntityTypeRemoved(OnEntityTypeRemovedNode node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.VisitConventionScope(ConventionScope node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.VisitConventionScope(ConventionScope node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Run()
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.RemoveEntityTypesUnreachableByNavigations(ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ModelCleanupConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The property 'ListingId' cannot be added to the type 'BuildingDetails' because there was no property type specified and there is no corresponding CLR property or field. To add a shadow state property the property type must be specified.
```

**Comment by AndriySvyryd** [comment]
@hitaspdotnet You need to call `room.Property<int>("ListingId");` first.

**Comment by hitaspdotnet** [comment]
Solved when I removed the `[Owned]` from `Room` class
