### ISSUE TITLE
Sqlite Migration throws MissingMethodException

### ISSUE THREAD

**Issue by OnurGumus** [dotnet/efcore#17124]
Unfortunately, it is hard for me to narrow down the issue. Basically, I am generating migration form an RCL by using Sqlite
with below command 
Update-database --context VotingModelContext
Then the below exception occurs.
```
System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Migrations.Operations.Builders.CreateTableBuilder`1<!!0> Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder.CreateTable(System.String, System.Func`2<Microsoft.EntityFrameworkCore.Migrations.Operations.Builders.ColumnsBuilder,!!0>, System.String, System.Action`1<Microsoft.EntityFrameworkCore.Migrations.Operations.Builders.CreateTableBuilder`1<!!0>>)'.
   at GatesVoting.Admin.Migrations.InitialCreate.Up(MigrationBuilder migrationBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Migration.BuildOperations(Action`1 buildAction)
   at Microsoft.EntityFrameworkCore.Migrations.Migration.get_UpOperations()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass15_2.<GetMigrationCommandLists>b__2()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Method not found: 'Microsoft.EntityFrameworkCore.Migrations.Operations.Builders.CreateTableBuilder`1<!!0> Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder.CreateTable(System.String, System.Func`2<Microsoft.EntityFrameworkCore.Migrations.Operations.Builders.ColumnsBuilder,!!0>, System.String, System.Action`1<Microsoft.EntityFrameworkCore.Migrations.Operations.Builders.CreateTableBuilder`1<!!0>>)'.
```

### Further technical details
EF Core version: 2.2.6
Database Provider:  Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10 64 bit pro latest RTM
IDE:  Visual Studio 2019 16.3 Preview 1

**Comment by OnurGumus** [comment]
Ok My bad I should have used latest version of entity framework as preview.
