### ISSUE TITLE
Ordering columns at MS SQL, Unable to evaluate

### ISSUE THREAD

**Issue by blahblehblah** [dotnet/efcore#17249]
After ef core 3.0 breaking change i am unable to order columns directly from sql server.

`return query.Where(x=>!x.IsDeleted).OrderByDescending(x => x.Id).Skip(pageSize.Value * (pageNumber.Value - 1)).Take(pageSize.Value)
                         .ToList();`

After updating to .net core 3.0, i am getting an error Unable to evaluate.

**Comment by smitpatel** [comment]
Can you post full repro code, exception message and stacktrace?

**Comment by blahblehblah** [comment]
Please note that this gives me an exception

`public IEnumerable<RiskyReports> GetRiskyReports(int? pageNumber = null, int? pageSize = null)
        {
            var query = Context.Set<RiskyReports>().AsQueryable();
            if (pageNumber.HasValue && pageSize.HasValue)
            {
return query.Where(x=>!x.IsDeleted).OrderByDescending(x => x.Id).Skip(pageSize.Value * (pageNumber.Value - 1)).Take(pageSize.Value) .ToList();
            }
return query.Where(x=>!x.IsDeleted).OrderByDescending(x => x.Id) .ToList();
        }`


Error

`System.InvalidOperationException: 'Operation is not valid due to the current state of the object.'`
`   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)

   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)

   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)

   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)

   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)

   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)

   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)

   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)

   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)

   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)

   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)

   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)

   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)

   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)

   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)

   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)

   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)

   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)

   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()

   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)

   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)

   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)

   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)

   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()

   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)`

**Comment by smitpatel** [comment]
Suspect is AsQueryable. Probably the one without generic type is getting picked up.

**Comment by blahblehblah** [comment]
> Suspect is AsQueryable. Probably the one without generic type is getting picked up.

Unfortunately, that is not the issue. I removed the AsQueryable, yet still getting that error

**Comment by smitpatel** [comment]
Please try daily builds as if would give you better exception message which would point out what is failing to translate. In any case, we will need full repro code with model & db context to investigate this.
