### ISSUE TITLE
Migration name cannot be the same as the DbContext class name

### ISSUE THREAD

**Issue by JNickVA1** [dotnet/efcore#17509]
I have an ASP.NET Core Razor app that I was working on when I downloaded and installed the latest SDK in order to use updated NuGet packages. Since then I get the same error when attempting to perform migrations. My project already had one migration added, and the database successfully updated, for the Identity classes. When I then tried to add a new migration created by the scaffolder I got the following error:
System.ArgumentException: GenericArguments[0], 'Agency.Migrations.AgencyContext1', on 'Microsoft.EntityFrameworkCore.Design.IDesignTimeDbContextFactory`1[TContext]' violates the constraint of type 'TContext'. ---&gt; System.TypeLoadException: GenericArguments[0], 'Agency.Migrations.AgencyContext1', on 'Microsoft.EntityFrameworkCore.Design.IDesignTimeDbContextFactory`1[TContext]' violates the constraint of type parameter 'TContext'.
   at System.RuntimeTypeHandle.Instantiate(RuntimeTypeHandle handle, IntPtr* pInst, Int32 numGenericArgs, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.Instantiate(Type[] inst)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   --- End of inner exception stack trace ---
   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextFactory(Type contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextTypes()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextType(String name)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.&lt;&gt;c__DisplayClass0_1.&lt;.ctor&gt;b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.&lt;&gt;c__DisplayClass3_0`1.&lt;Execute&gt;b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
GenericArguments[0], 'Agency.Migrations.AgencyContext1', on 'Microsoft.EntityFrameworkCore.Design.IDesignTimeDbContextFactory`1[TContext]' violates the constraint of type 'TContext'.

I then attempted to start over and deleted the database, removed the migration files for the Identity, and tried to add that migration. I received the same error.  The command line I used for the initial (Identity) migration is:
Add-Migration Initial -Context:ApplicationContext1
I then attempted to add a NEW migration whose DbContext was generated as a result of me scaffolding new CRUD pages and I get the same error when I try to add that migration

I seriously need to resolve this soon! Help!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e28b0a8-b7e4-4c07-9e60-0df403bbee28
* Version Independent ID: 12300b31-6f7b-b75c-970d-693365e77013
* Content: [Migrations - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/)
* Content Source: [entity-framework/core/managing-schemas/migrations/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/index.md)
* Product: **entity-framework**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by lajones** [comment]
With above fix we now throw an exception if the migration name is the same as the context and ask the user to use a different migration name.
