### ISSUE TITLE
`InvalidOperationException: Include has been used on non entity queryable.`  for >= `3.0.0-preview9.19401.4`

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/efcore#17552]
#### Describe what is not working as expected.
The below code works on `3.0.0-preview8.19405.11` and <=`3.0.0-preview9.19401.2`, but not works on >=`3.0.0-preview9.19401.4`, `3.0.0-rc1.19431.3` and `5.0.0-alpha1.19431.2`.

Not sure if it's an issue or something by design(The code can be simply fixed by using `.Include(t => t.Table2.Table2)` before `Select` instead).

#### If you are seeing an exception, include the full exceptions details (message and stack trace).

```
System.InvalidOperationException: Include has been used on non entity queryable.
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ProcessInclude(NavigationExpansionExpression source, Expression expression, Boolean thenInclude)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ExpandAndReduce(Expression query, Boolean applyInclude)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

<details>

```c#
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

namespace EFCore_Test1
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Tested with EFCore: " + (typeof(DbContext).Assembly.GetCustomAttributes(typeof(System.Reflection.AssemblyInformationalVersionAttribute), false).FirstOrDefault() as System.Reflection.AssemblyInformationalVersionAttribute)?.InformationalVersion);
            using (var ctx = new MyDbContext())
            {
                ctx.Database.EnsureCreated();
                try
                {
                    //The Where, Select, Include can also use 3 different entities to do the test.
                    ctx.Table_1.Where(t => t.Id > 0).Select(t => t.Table2).Include(t => t.Table2).ToList();
                }
                catch (Exception ex)
                {
                    Console.Error.WriteLine(ex);
                }
            }
        }

        public class MyDbContext : DbContext
        {
            public DbSet<Table1> Table_1 { get; set; }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseSqlServer(@"Server=(localdb)\MSSQLLocalDB;Database=Test_Database016;Trusted_Connection=True;");
            }

            public class Table1
            {
                public int Id { get; set; }

                //public string Text { get; set; }
                public Table1 Table2 { get; set; }
            }
        }
    }
}
```
</details>

### Further technical details
EF Core version: `3.0.0-rc1.19431.3`
Database Provider: `Microsoft.EntityFrameworkCore.SqlServer`
Operating system: -
IDE: -

**Comment by smitpatel** [comment]
It is by design. See #12737 for breaking change
See #16752 if we decide to enable this in future.
