### ISSUE TITLE
In-Memory DB provider throws InvalidOperationException

### ISSUE THREAD

**Issue by SIkebe** [dotnet/efcore#17645]
Microsoft.EntityFrameworkCore.InMemory 3.0.0-preview9.19423.6 throws `InvalidOperationException`. Latest daily builds (rc-1) throws, too.
Same code in 2.2.X does not throw any exception.

### Steps to reproduce
```
git clone -b inmemory-error https://github.com/SIkebe/gitbucket-utility.git
cd gitbucket-utility
dotnet test .\src\GitBucket.Service.Tests\
.
.
.
A total of 1 test s
  X GitBucket.Service.Tests.ReleaseServiceTest.Should_Create_PullRequest [591ms]
  エラー メッセージ:
   System.InvalidOperationException : The instance of entity type 'Priority' cannot be tracked because another instance with the same key value for {'PriorityId'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
  スタック トレース:
     at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityStates(IEnumerable`1 entities, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.AddRange(IEnumerable`1 entities)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.AddRange(IEnumerable`1 entities)
   at GitBucket.Service.Tests.ReleaseServiceTest.EnsureDbCreated(ReleaseOptions options) in C:\GitHub\test\gitbucket-utility\src\GitBucket.Service.Tests\ReleaseServicetest.cs:line 340
   at GitBucket.Service.Tests.ReleaseServiceTest.Should_Create_PullRequest() in C:\GitHub\test\gitbucket-utility\src\GitBucket.Service.Tests\ReleaseServicetest.cs:line 176
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)

テストの実行に失敗しました。
テストの合計数: 21
     成功: 13
     失敗: 1
    スキップ: 7
合計時間: 2.6554 秒
```

### Further technical details
EF Core version: 3.0.0-preview9.19423.6
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL
Operating system: Windows 10 pro 64bit

**Comment by ajcvickers** [comment]
In 2.2, there was a bug (see #15645) which would cause an added graph to not correctly add an entities when an existing entity had the same key. In this case, the test code was hitting this and silently ignoring an entity instance rather than throwing that it could not be tracked--hence with the fix in place, the exception is now thrown.

In this case, the reason there are two entities with the same key is that an entity using an in-memory generated key is added and gets a key value of 1. Then an entity with key value explicitly set to 1 is added.

**Comment by BrianMinister** [comment]
I'm having the same problem, but I should be getting null ref.
Here is my unit test:

            try
            {
                _ = _ctx.GetAllApplicationUserByClaim(invalidClaim, invalidValue);
            }
            catch (System.InvalidOperationException ex)  //Added as a result of this bug reported on GitHub efcore 17645
            {
                System.Diagnostics.Debug.WriteLine("Cannot complete test, due to model not being seeded.");
                Assert.IsTrue(true);
            }
            catch (Exception ex)
            {
                Assert.AreEqual(expectedExceptionString, ex.Message, $"Expected error was '{expectedExceptionString}', but instead recorded '{ex.Message}'");
            }

And here is the function that the unit test is calling:
        public static List<ApplicationUser> GetAllApplicationUserByClaim(this ApplicationDbContext ctx, string claim, string value)
        {

            if (ctx.UserClaims.Count() == 0) throw new NullReferenceException("No user claims recorded");
            if (ctx.Users.Count() == 0) throw new NullReferenceException("No users recorded");

            if (string.IsNullOrEmpty(claim)) throw new ArgumentNullException($"Claim Type cannot be null or empty.");
            
            var rec = ctx.UserClaims.Where(n => n.ClaimType == claim && n.ClaimValue == value);
            if (rec.Count() == 0) throw new RecordNotFoundException($"Claim: {claim} / Value: {value} not Found");

            var recs = ctx.Users.Where(n => rec.Where(m => m.UserId == n.Id).Count() > 0).ToList();
            if (recs == null) throw new RecordNotFoundException($"Claim: {claim} / Value: {value} not Found");

            return recs;
        }
I ended up putting in: `catch (System.InvalidOperationException ex)` 

which invalidates my test, but passes it, so I can keep working. 

The setup for my data context is InMemory, and the tables purposely have no data for these negative tests.

Trying to reload does not help.

I cannot say when this code stopped working, but I suspect it may have been around mid-summer when we switched from 2.1 to 2.2. We found out about this now only because we are moving to CICD, and executing the unit tests from the CI process.
