### ISSUE TITLE
Average_on_nav_subquery_in_projection is flaky

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#17775]
>Microsoft.Data.SqlClient.SqlException : The incoming tabular data stream (TDS) protocol stream is incorrect. The MARS TDS header contained errors.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken) in /_/src/EFCore.Relational/Storage/RelationalCommand.cs:line 543
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken) in /_/src/EFCore.Relational/Storage/RelationalCommand.cs:line 543
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken) in /_/src/EFCore.Relational/Storage/RelationalCommand.cs:line 543
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync() in /_/src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.AsyncQueryingEnumerable.cs:line 99
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken) in /_/src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs:line 2019
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken) in /_/src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs:line 2019
   at Microsoft.EntityFrameworkCore.Query.AsyncSimpleQueryTestBase`1.Average_on_nav_subquery_in_projection() in /_/test/EFCore.Specification.Tests/Query/AsyncSimpleQueryTestBase.cs:line 143
--- End of stack trace from previous location where exception was thrown ---

**Comment by AndriySvyryd** [comment]
Blocked by https://github.com/dotnet/SqlClient/issues/85
