### ISSUE TITLE
[USER ERROR] Method not found: 'IntPtr SQLitePCL.sqlite3.get_ptr()' when running Preview9 version of tools

### ISSUE THREAD

**Issue by drk-mtr** [dotnet/efcore#17771]
### Version Information

EF Core: `3.0.0-preview8.19405.11` or `3.0.0-preview9.19423.6`
Dotnet: `3.0.100-preview9-014004`
Target framework: `netcoreapp3.0`
IDE: vscode
OS: Windows 10 1903
Provider: Microsoft.EntityFrameworkCore.Sqlite

### Steps to reproduce

- Follow the instructions on this page: https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-2.2
- The initial migration is created successfully
- Run `dotnet ef database update`
- Receive error as below

```
System.MissingMethodException: Method not found: 'IntPtr SQLitePCL.sqlite3.get_ptr()'.
   at Microsoft.Data.Sqlite.SqliteConnection.Close()
   at Microsoft.Data.Sqlite.SqliteConnection.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
   at Microsoft.EntityFrameworkCore.DbContext.Dispose()
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Method not found: 'IntPtr SQLitePCL.sqlite3.get_ptr()'.
```

### Additional Information

The really frustrating thing here is that:
- If I roll back to 2.2 version of the tools I receive the error: `The application to execute does not exist: 'C:\Users\{username}\.dotnet\tools\.store\dotnet-ef\2.2.6-servicing-10079\dotnet-ef\2.2.6-servicing-10079\tools\netcoreapp2.2\any\dotnet-ef.dll'.`
- If I roll back to an earlier preview e.g. `3.0.0-preview4.19216.3` I get: 
```
System.MissingMethodException: Method not found: 'System.Text.Json.JsonDocument System.Text.Json.JsonDocument.Parse(System.IO.Stream, System.Text.Json.JsonReaderOptions)'.
   at Microsoft.EntityFrameworkCore.Tools.RootCommand.Execute()
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Method not found: 'System.Text.Json.JsonDocument System.Text.Json.JsonDocument.Parse(System.IO.Stream, System.Text.Json.JsonReaderOptions)'.
```

So it's fairly consistent in terms of not working :D 

I had this working last night on a different PC with Preview8, so it is potentially a local environmental issue and I'll do some more digging here. However I'd really appreciate any pointers (no pun intended) on where to look in the meantime.

EDIT: I'll try this with a different provider and record any findings here... don't know why I didn't think of this BEFORE raising the issue!

**Comment by drk-mtr** [comment]
UPDATE: This only occurs when using the `paket` package manager. It's fine when using just the dotnet tools / nuget package manager. Closing the issue and will pick up with the `paket` creators to see whether I can work out what's going on.
