### ISSUE TITLE
Contains overload which takes StringComparison throwing for client eval

### ISSUE THREAD

**Issue by BrankoIlic** [dotnet/efcore#17789]
### Steps to reproduce
for:

if (!string.IsNullOrEmpty(request.FirstName))
                var identities = _context.Identities..Where(a => a.FirstName.Contains(request.FirstName, StringComparison.OrdinalIgnoreCase));

I get:
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateWhere(ShapedQueryExpression source, LambdaExpression predicate)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
   at GSEC.FIM.Service.Data.IdentityData.Query.GetiIdentities.GetIdentitiesQueryHandler.Handle(GetIdentitiesQuery request, CancellationToken cancellationToken) in D:\Projekti\GSECFIM\src\GSEC.FIM.Service\Data\IdentityData\Query\GetiIdentities\GetIdentitiesQueryHandler.cs:line 86
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at GSEC.FIM.Service.Controllers.V1.IdentitiesController.GetSearchResults(GetIdentitiesQuery query) in D:\Projekti\GSECFIM\src\GSEC.FIM.Service\Controllers\V1\IdentitiesController.cs:line 75
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.SetRoutingAndContinue(HttpContext httpContext)
   at GSec.Microservice.Web.Middlewares.RestAuthenticationStoreMiddleware.Invoke(HttpContext httpContext, IRestAuthenticationStore restAuthenticationStore)
   at GSec.Microservice.Web.Middlewares.CorrelationMiddleware.Invoke(HttpContext httpContext, CorrelationContext correlationContext, IOptions`1 hostOptions, ICorrelationService correlationService)
   at GSec.Microservice.Web.Middlewares.FailDeprecatedMiddleware.Invoke(HttpContext httpContext)
   at GSec.Microservice.Web.Middlewares.ValidationMiddleware.InvokeAsync(HttpContext context, OutputFormatterSelector formatterSelector, IOptions`1 mvcOptions, IHttpResponseStreamWriterFactory writerFactory, IMediator mediator)
   at GSec.Microservice.Web.Middlewares.ValidationMiddleware.<>c__DisplayClass2_1.<InvokeAsync>b__1()
   at GSec.Microservice.Web.Middlewares.ValidationMiddleware.InvokeAsync(HttpContext context, OutputFormatterSelector formatterSelector, IOptions`1 mvcOptions, IHttpResponseStreamWriterFactory writerFactory, IMediator mediator)
   at GSec.Microservice.Web.Middlewares.ReadinessMiddleware.Invoke(HttpContext httpContext, IReadinessCheckerService readinessCheckerService)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

when I remove 
, StringComparison.OrdinalIgnoreCase
to
var identities = _context.Identities..Where(a => a.FirstName.Contains(request.FirstName));
there is no exception

### Further technical details

EF Core version: Microsoft.EntityFrameworkCore (3.0.0-preview8.19405.11)
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL 3.0.0-preview8
Target framework:  .NET Core 3.0.0-preview8
Operating system: win 10
IDE: Visual Studio 2019 16.2.3

**Comment by roji** [comment]
In PostgreSQL the closest thing would be to use [ILIKE](https://www.postgresql.org/docs/current/functions-matching.html), although you have to be careful with escape characters (%, _):

```c#
_context.Identities.Where(a => EF.Functions.ILike(a.FirstName, "%" + request.FirstName + "%"));
```

Can you please open an issue on https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL to translate `string.Contains(s, StringComparison.OrdinalIgnoreCase)`?

Other options include lower-casing both strings before the Contains, or on PostgreSQL using the `citext` data type (great solution if *all* comparisons need to be lowercase on a column).

Am closing this as a general EF Core issue.
