### ISSUE TITLE
Query: chaining multiple collections of weak entities throws during compilation

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#17803]
query:

```cs
ctx.LevelOnes.Select(
l1 => l1.OneToMany_Optional1    
    .OrderBy(l2=>l2.Id)
    .FirstOrDefault().OneToMany_Optional2
        .OrderBy(l3 => l3.Id)
        .FirstOrDefault().Name)
```

qp before queryable translation:

```
Select<Level1, string>(
    source: DbSet<Level1>, 
    selector: (l) => FirstOrDefault<string>(Select<Level3, string>(
        source: OrderBy<Level3, int>(
            source: AsQueryable<Level3>(Property<ICollection<Level3>>(FirstOrDefault<Level2>(OrderBy<Level2, int>(
                source: AsQueryable<Level2>(Property<ICollection<Level2>>(l, "OneToMany_Optional1")), 
                keySelector: (o) => o.Id)), "OneToMany_Optional2")), 
            keySelector: (o0) => o0.Id), 
        selector: (o0) => o0.Name)))
```

exception:

```
Message: 
    System.InvalidOperationException : EF.Property called with wrong property name.
  Stack Trace: 
    at RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in RelationalSqlTranslatingExpressionVisitor.cs line: 301
    at MethodCallExpression.Accept(ExpressionVisitor visitor)
    at ExpressionVisitor.Visit(Expression node)
    at RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in RelationalSqlTranslatingExpressionVisitor.cs line: 384
    at MethodCallExpression.Accept(ExpressionVisitor visitor)
    at ExpressionVisitor.Visit(Expression node)
    at RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in RelationalSqlTranslatingExpressionVisitor.cs line: 384
    at MethodCallExpression.Accept(ExpressionVisitor visitor)
    at ExpressionVisitor.Visit(Expression node)
    at RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in RelationalSqlTranslatingExpressionVisitor.cs line: 384
    at MethodCallExpression.Accept(ExpressionVisitor visitor)
    at ExpressionVisitor.Visit(Expression node)
    at RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in RelationalSqlTranslatingExpressionVisitor.cs line: 384
    at MethodCallExpression.Accept(ExpressionVisitor visitor)
    at ExpressionVisitor.Visit(Expression node)
    at RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression) in RelationalSqlTranslatingExpressionVisitor.cs line: 42
    at RelationalProjectionBindingExpressionVisitor.Visit(Expression expression) in RelationalProjectionBindingExpressionVisitor.cs line: 163
    at RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression) in RelationalProjectionBindingExpressionVisitor.cs line: 45
    at RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector) in RelationalQueryableMethodTranslatingExpressionVisitor.cs line: 746
    at QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in QueryableMethodTranslatingExpressionVisitor.cs line: 343
    at RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in RelationalQueryableMethodTranslatingExpressionVisitor.cs line: 72
    at MethodCallExpression.Accept(ExpressionVisitor visitor)
    at ExpressionVisitor.Visit(Expression node)
    at QueryCompilationContext.CreateQueryExecutor[TResult](Expression query) in QueryCompilationContext.cs line: 68
    at Database.CompileQuery[TResult](Expression query, Boolean async) in Database.cs line: 71
    at QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async) in QueryCompiler.cs line: 106
    at <>c__DisplayClass9_0`1.<Execute>b__0() in QueryCompiler.cs line: 96
    at CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler) in CompiledQueryCache.cs line: 84
    at CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) in CompiledQueryCache.cs line: 59
    at QueryCompiler.Execute[TResult](Expression query) in QueryCompiler.cs line: 92
    at EntityQueryProvider.Execute[TResult](Expression expression) in EntityQueryProvider.cs line: 79
    at EntityQueryable`1.GetEnumerator() in EntityQueryable`.cs line: 94
    at LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
    at EnumerableHelpers.ToArray[T](IEnumerable`1 source)
    at Enumerable.ToArray[TSource](IEnumerable`1 source)
```

**Comment by maumar** [comment]
still repros on current bits

**Comment by smitpatel** [comment]
Same error?
