### ISSUE TITLE
Include throws when not called from DbSet

### ISSUE THREAD

**Issue by lukewaters** [dotnet/efcore#1793]
This test throws: 

```
        [Fact]
        public virtual void Include_expression()
        {
            AssertQuery<Order>(order => order
                .Include(o => o.OrderDetails),
                entryCount: 91);
        }
```

And this test passes:

```

        [Fact]
        public virtual void Include_expression()
        {
            using (var context = CreateContext())
            {
                context.Set<Order>()
                    .Include(o => o.OrderDetails)
                    .ToList();
            }
        }
```

Throws this exception:

```
Test 'Microsoft.Data.Entity.SqlServer.FunctionalTests.QuerySqlServerTest.Include_expression' failed: System.InvalidOperationException : There is no method 'Include' on type 'System.Linq.EntityFrameworkQueryableExtensions' that matches the specified arguments
    at System.Linq.EnumerableRewriter.FindMethod(Type type, String name, ReadOnlyCollection`1 args, Type[] typeArgs, BindingFlags flags)
    at System.Linq.EnumerableRewriter.VisitMethodCall(MethodCallExpression m)
    at System.Linq.Expressions.OldExpressionVisitor.Visit(Expression exp)
    at System.Linq.EnumerableQuery`1.GetEnumerator()
    at System.Linq.EnumerableQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
    Extensions\EntityFrameworkQueryableExtensions.cs(2222,0): at System.Linq.EntityFrameworkQueryableExtensions.IncludableQueryable`2.GetEnumerator()
    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
    QueryTestBase.cs(2715,0): at Microsoft.Data.Entity.FunctionalTests.QueryTestBase`1.AssertQuery[TItem](Func`2 efQuery, Func`2 l2oQuery, Boolean assertOrder, Int32 entryCount)
    QueryTestBase.cs(2644,0): at Microsoft.Data.Entity.FunctionalTests.QueryTestBase`1.AssertQuery[TItem](Func`2 query, Boolean assertOrder, Int32 entryCount)
    QueryTestBase.cs(2529,0): at Microsoft.Data.Entity.FunctionalTests.QueryTestBase`1.Include_expression_orderby()
    QuerySqlServerTest.cs(1973,0): at Microsoft.Data.Entity.SqlServer.FunctionalTests.QuerySqlServerTest.Include_expression_orderby()
```

**Comment by anpete** [comment]
It's not the DbSet, it's AssertQuery - It has magic to do result diffing with L2O, which doesn't understand Include.

Don't mix AssertQuery and Include.
