### ISSUE TITLE
Entity with string Id in InMemory DB throws null exeption when added

### ISSUE THREAD

**Issue by dave-hillier** [dotnet/efcore#17971]
Swapping for int works as expected. This is a change in behavior from 2.2

### Steps to reproduce

``` C#
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace repro
{
    public class Issue
    {
        public string Id { get; set; }
        public string Description { get; set; }
    }

    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions options) : base(options) { }
        public DbSet<Issue> Issues { get; set; }
    }

    public class UnitTest1
    {
        [Fact]
        public async void Test1()
        {
            var optionsBuilder = new DbContextOptionsBuilder<ApplicationDbContext>();
            optionsBuilder.UseInMemoryDatabase("x");
            using (var context = new ApplicationDbContext(optionsBuilder.Options))
            {
                context.Add(new Issue
                {
                    Description = "Description1"
                });
                context.Add(new Issue
                {
                    Description = "Description2"
                });
                context.SaveChanges();
                Assert.Equal(2, await context.Issues.CountAsync());
            }
        }
    }
}

```

Got Exceptions? Include both the message and the stack trace
```
 System.InvalidOperationException : Unable to track an entity of type 'Issue' because primary key property 'Id' is null.
  Stack Trace:
     at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NullableKeyIdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.Add[TEntity](TEntity entity)
```

### Further technical details

EF Core version: NET Core 3.0 Preview 9
Database provider: InMemory
Target framework: NET Core 3.0 Preview 9
Operating system: macos

**Comment by smitpatel** [comment]
@dave-hillier - You have string PK defined. You need to provide value of Id property explicitly. `Id` property of type int which are generally mapped to identity column on relational database has value generation attached to it so server can generate a value when adding new entity. InMemory also has value generation for int properties. No such thing exist for string property. Above code would throw error in any other provider same way.

**Comment by dave-hillier** [comment]
Nevermind, I found the change in behaviour buried in the release notes! 

https://github.com/aspnet/EntityFrameworkCore/issues/14617
