### ISSUE TITLE
 Globalization Invariant Mode is not supported.

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/efcore#18025]
```
Application startup exception: System.NotSupportedException: Globalization Invariant Mode is not supported.
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists(Boolean retryOnNotExists)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
```

### Additional context

Microsoft.EntityFrameworkCore.SqlServer 3.0.0
Microsoft.Data.Sqlite version: 1.0.19249.1
Target framework: (.NET Core 3.0)
Operating system: Docker Alpine

**Comment by WeihanLi** [comment]
fixed with

``` dockerfile
RUN apk add icu-libs
# https://www.abhith.net/blog/docker-sql-error-on-aspnet-core-alpine/
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
```

more details: https://www.abhith.net/blog/docker-sql-error-on-aspnet-core-alpine/
reference sample project: https://github.com/WeihanLi/ActivityReservation

**Comment by 80dB** [comment]
We just ran into the same issue with a container that was converted from .NET Core v2.2 with EntityFrameworkCore v2.2.6. Now running .NET Core 3 + EFCore v3 and we get this error after deploying a container.

As such it seems something changed. For now I'll add the above fix.

**Comment by bricelam** [comment]
Ouch, can you submit an issue on [dotnet/SqlClient](https://github.com/dotnet/SqlClient/issues/new/choose) to see if there's anything they can do to relax this limitation? Being broken on the docker image by default sounds like a pretty bad experience.
