### ISSUE TITLE
Can't concatenate string inside query

### ISSUE THREAD

**Issue by btecu** [dotnet/efcore#18132]
This query works in 2.2 but not in 3.0:

```C#
myDbContext.Orders
    .Where(x => x.Id == 9527)
    .Select(x => new {
        x.Id,
        x.Created,
        OrderService = myDbContext.OrderServices
            .Where(y => y.OrderId == x.Id)
            .Select(y => y.OrderId + "-" + y.ServiceId)
            .ToList()
        })
    .ToArray()
```

Based on my findings, if I change the `.Select(y => y.OrderId + "-" + y.ServiceId)` to be anything other than the string concatenation it works: `.Select(y => new { y.OrderId, y.ServiceId })`.

There's a many-to-many relationship between `Orders` and `Services` via `OrderServices`.

The error is: **Null TypeMapping in Sql Tree**

```
System.InvalidOperationException: Null TypeMapping in Sql Tree
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.SqlTypeMappingVerifyingExpressionVisitor.VisitExtension(Expression node)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.TranslateSubquery(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberAssignment(MemberAssignment memberAssignment)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
```

I'm also using Npgsql so I'm not sure what the issue might be:
![image](https://user-images.githubusercontent.com/7517745/65835900-170c7e80-e2ba-11e9-9474-c7e775a77578.png)

### Further technical details

EF Core version:
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL 3.0.0
Target framework: .NET Core 3.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.3

cc @roji

**Comment by roji** [comment]
Reproed this with SqlServer:

```c#
class Program
{
    static void Main(string[] args)
    {
        using var ctx = new BlogContext();
        ctx.Database.EnsureDeleted();
        ctx.Database.EnsureCreated();

        ctx.Orders
            .Where(x => x.Id == 9527)
            .Select(x => new
            {
                x.Id,
                x.Created,
                OrderService = ctx.OrderServices
                    .Where(y => y.OrderId == x.Id)
                    .Select(y => y.OrderId + "-" + y.ServiceId)
                    .ToList()
            })
            .ToArray();
    }
}

public class BlogContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(...);
    }

    public DbSet<Orders> Orders { get; set; }
    public DbSet<OrderService> OrderServices { get; set; }
}

public class Orders
{
    public int Id { get; set; }
    public DateTime Created { get; set; }
    public List<OrderService> OrderServices { get; set; }
}

public class OrderService
{
    public int Id { get; set; }
    public int OrderId { get; set; }
    public int ServiceId { get; set; }
}
```

**Comment by btecu** [comment]
Also appears to fail:
```C#
OrderServices
    .Where(x => x.OrderId == 9527 && x.ServiceId == 22)
    .Select(x => x.OrderId + "-" + x.ServiceId)
    .First()
```

However, other tables seem to work fine. The main difference is `OrderServices` has a composite key:
```C#
modelBuilder.Entity<OrderService>()
    .HasKey(x => new { x.OrderId, x.ServiceId });
```

While the other tables have their own key (not a foreign key composition).

**Comment by smitpatel** [comment]
The add operation is adding object converts, we are missing probably some case of that only.

**Comment by btecu** [comment]
@smitpatel, is there a workaround until this gets fixed (might take a while to get released)?

**Comment by smitpatel** [comment]
```C#
OrderServices
    .Where(x => x.OrderId == 9527 && x.ServiceId == 22)
    .Select(x => x.OrderId.ToString() + "-" + x.ServiceId.ToString())
    .First()
```
Also works if provider supports ToString translation.

**Comment by btecu** [comment]
@ajcvickers @smitpatel is this fixed in 3.1 preview?

**Comment by ajcvickers** [comment]
@btecu This issue is in the Backlog milestone. This means that it is not going to happen for the 3.1 release. We will re-assess the backlog following the 3.1 release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by Muppets** [comment]
From my testing using @roji example, this looks fixed in the latest master as of this week. Testing on latest released 3.1.1 it still fails. I had a look through closed issues but I couldn't find what might have fixed it.

**Comment by ajcvickers** [comment]
@Muppets Thanks for investigating. We discussed this and we think all that is needed here is to add a regression test. A PR for that, if you're interested, would be great. Otherwise we'll put it back on the backlog for now.

**Comment by Muppets** [comment]
@ajcvickers Yep, let me whip something together for that.
