### ISSUE TITLE
OrderBy on projection

### ISSUE THREAD

**Issue by kakone** [dotnet/efcore#18162]
I didn't succeed in doing a simple OrderBy on a computed field in projection with EF Core 3.0. 
This is the code :
```csharp
var test = DbContext.Set<TRequest>()
    .Select(r => new { r.Id, r.Number, EllapsedDays = (DateTime.Today - r.RequestDate.Date).Days })
    .ToList();

var test2 = DbContext.Set<TRequest>()
    .Select(r => new { r.Id, r.Number, EllapsedDays = (DateTime.Today - r.RequestDate.Date).Days })
    .OrderByDescending(r => r.EllapsedDays)
    .ToList();

var test3 = DbContext.Set<TRequest>()
    .Select(r => new { r.Id, r.Number, EllapsedDays = (DateTime.Today - r.RequestDate.Date).Days })
    .Skip(0)
    .OrderByDescending(r => r.EllapsedDays).ToList();
```

The first test works well, I get my requests with ellapsed days in the test variable.
The second test fails because EF try to do an OrderBy with the complex expression for ellapsed days. I was thinking that a subquery would be generated but it is not the case. So, I tried to add a .Skip(0) to force a subquery. But, in this third case, I've got a System.ArgumentNullException: 'Value cannot be null. (Parameter 'key')'.

<details>
<summary>Stacktrace</summary>
Value cannot be null. (Parameter 'key')

   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.GetMappedProjection(ProjectionMember projectionMember)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMember(MemberExpression memberExpression)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateExpression(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateLambdaExpression(ShapedQueryExpression shapedQueryExpression, LambdaExpression lambdaExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateOrderBy(ShapedQueryExpression source, LambdaExpression keySelector, Boolean ascending)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
</details>

How can I do this OrderBy server side ?

**Comment by smitpatel** [comment]
Your projection contains Client evaluation hence we cannot translate order by to server. We have improved error message to throw proper error post 3.0.

Without knowing which provider you are using, I cannot say how to make the projection server evaluated.

**Comment by kakone** [comment]
I use the Microsoft.EntityFrameworkCore.SqlServer provider. 
Thanks for the explanation, I rewrote my query with EF.Functions.DateDiffDay and it works well now :
```csharp
var test2 = DbContext.Set<TRequest>()
    .Select(r => new { r.Id, r.Number, EllapsedDays = EF.Functions.DateDiffDay(r.RequestDate, DateTime.Today) })
    .OrderByDescending(r => r.EllapsedDays)
    .ToList();
```
