### ISSUE TITLE
NetTopologySuite: InvalidOperationException

### ISSUE THREAD

**Issue by bdebaere** [dotnet/efcore#18172]
### Steps to reproduce

I followed the tutorial at https://docs.microsoft.com/en-us/ef/core/modeling/spatial to implement geospatial queries.

I then received a MissingMethodException.
System.MissingMethodException: Method not found: 'GeoAPI.IGeometryServices NetTopologySuite.NtsGeometryServices.get_Instance()'.

```
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite" Version="2.2.6" />
    <PackageReference Include="NetTopologySuite" Version="2.0.0" />
    <PackageReference Include="NetTopologySuite.Core" Version="1.15.3" />
```

I then followed the guidance on the StackOverflow post below. I removed the reference to NetTopologySuite.
https://stackoverflow.com/questions/57718842/why-am-i-getting-this-error-when-trying-to-implement-usenettopologysuite-in-my-a

```
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite" Version="2.2.6" />
    <PackageReference Include="NetTopologySuite.Core" Version="1.15.3" />
```

I then received the exception below. What am I missing?

```
No suitable constructor found for entity type 'CoordinateSystem'. The following constructors had parameters that could not be bound to properties of the entity type: cannot bind 'epsgId', 'topology' in 'CoordinateSystem(int epsgId, string name, Topology topology)'.


System.InvalidOperationException


at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConstructorBindingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
```

### Further technical details

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 2.2
Operating system: Win10
IDE: Visual Studio 2019 16.3

**Comment by roji** [comment]
You can't use NetTopologySuite 2.0.0 with EF Core 2.2, as it has breaking changes (opened #18180 to make this more clear).

Your 2nd sample should work, it's likely you need to clean, restore and rebuild your project. The following works:

```c#
public class Program
{
    static void Main(string[] args)
    {
        using var ctx = new BlogContext();
        ctx.Database.EnsureDeleted();
        ctx.Database.EnsureCreated();
    }
}

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer("...", x => x.UseNetTopologySuite());
    }
}

public class Blog
{
    public int Id { get; set; }
    public Point Location { get; set; }
}
```

csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite" Version="2.2.6" />
    <PackageReference Include="NetTopologySuite.Core" Version="1.15.3" />
  </ItemGroup>

</Project>
```

**Comment by IanKemp** [comment]
> What am I missing?

After you installed [`Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite` 2.2.6](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite/2.2.6), you manually went and updated your EF Core-related NuGet packages to the latest versions. **Don't do that**.
