### ISSUE TITLE
Timestamp-based Concurrency Token is not updated during transaction -> causes DbUpdateConcurrencyException

### ISSUE THREAD

**Issue by HSchwichtenberg** [dotnet/efcore#18212]
During a transaction, EF Core reads the new timestamp using UPDATE  … + SELECT [timestamp]…

However, the read timestamp is not used.

If this is by design there should be at least a documentation telling the users that in transaction the timestamps are not updated.

When removing the transaction, the code works. While the transaction is not necessary in this simple case described below, it is necessary in other cases involving more and other objects.

The workaround we are using is updating the timestamp manually.

### Steps to reproduce

- A context with a simple class with a timestamp column:  .IsConcurrencyToken().ValueGeneratedOnAddOrUpdate()
- I start a transaction: ctx.Database.BeginTransaction()
- I change two objects 
- Object 2 contains too much letters in a string
- SaveChanges() fails (DbUpdateException, which is OK of course, as we have too much letters)
- I reduce the letters in the string to fit the max string length.
- SaveChanges() fails again with a DbUpdateConcurrencyException for object 1 
- The DbUpdateConcurrencyException is not ok as there was definitely no concurrent access to the database!
- Same problem with every subsequent call of SaveChanges()
- Changing the isolation level of the transaction makes no difference. 

The reason for DbUpdateConcurrencyException can be seen in the following screenshot:

- In the first try of SaveChanges() there is an UPDATE followed by a SELECT [Timestamp]… for object 1, see green arrow
- However, the new timestamp  (…808) is not copied to the entity object in RAM. This object still continues to use the old timestamp (…806), see red arrow. The screenshot proves that EF Core can read the correct timestamp using ctx.Entry(p).GetDatabaseValues().GetValue<byte[]>("Timestamp"), but not uses it.
- With this wrong timestamp all subsequent tries to persist the object cannot succeed.

![Screenshot](https://user-images.githubusercontent.com/3673169/66165079-3b5ab900-e634-11e9-92b5-c75aa3574b9d.jpg)

### Code:
```CS
using ITVisions; // simple helper lib for colored outputs and conversion of byte[] to string
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;
 
namespace ConcurrencyTransactionProblem
{
 
 /// <summary>
 /// Repro for Bug
 /// 
 /// </summary>
 class Program
 {
 
  static async Task Main(string[] args)
  {
   var ctx = new Context();
   Console.WriteLine("Start...");
   ctx.Database.EnsureCreated();
   ctx.Database.ExecuteSqlRaw("delete from person");
   #region Insert Testdata
   var p1 = new Person
   {
    ID = 1,
    Name = "Meier",
    Age = 50
   };
   await ctx.AddAsync(p1);
 
   var p2 = new Person
   {
    ID = 2,
    Name = "Schulze",
    Age = 20
   };
   await ctx.AddAsync(p2);
   await ctx.SaveChangesAsync();
   #endregion
 
   using (var trans = ctx.Database.BeginTransaction())
   {
    p1.Age = 51;
    p2.Name = "too much text - too much text - too much text";
 
    // -------------------------------------------------------------------------------
    CUI.H1("1. SaveChanges");
    CUI.Print("S1 P#1 Timestamp before save: " + GetTimeStamp(ctx), ConsoleColor.White);
 
    try
    {
     ctx.SaveChanges();
    }
    catch (Exception ex)
    {
     CUI.PrintError(ex.GetType().Name + ": " + ex.Message);
    }
 
    CUI.Print("S1 P#1 Timestamp after save: " + GetTimeStamp(ctx), ConsoleColor.White);
 
    CUI.Info("Fixing the problem in object #2:");
    p2.Name = "Mueller";
 
    // -------------------------------------------------------------------------------
    CUI.H1("2. SaveChanges");
    CUI.Print("S2 P#1 Timestamp before save: " + GetTimeStamp(ctx), ConsoleColor.White);
    try
    {
     ctx.SaveChanges();
    }
    catch (Exception ex)
    {
     CUI.PrintError(ex.GetType().Name + ": " + ex.Message);
    }
    CUI.Print("S2 P#1 Timestamp after save: " + GetTimeStamp(ctx), ConsoleColor.White);
 
    // -------------------------------------------------------------------------------
    CUI.H1("3. SaveChanges");
    CUI.Print("S3 P#1 Timestamp before save: " + GetTimeStamp(ctx), ConsoleColor.White);
    try
    {
     ctx.SaveChanges();
    }
    catch (Exception ex)
    {
     CUI.PrintError(ex.GetType().Name + ": " + ex.Message);
    }
    CUI.Print("S3 P#1 Timestamp after save: " + GetTimeStamp(ctx), ConsoleColor.White);
 
    trans.Commit();
   }
 
   static string GetTimeStamp(Context ctx)
   {
    var p = ctx.Person.Local.SingleOrDefault(x => x.ID == 1);
    var local = p.Timestamp?.ByteArrayToHexString();
    var dbValue = ctx.Entry(p).GetDatabaseValues().GetValue<byte[]>("Timestamp").ByteArrayToHexString();
    var dbUncommited = GetPersonUncommited().Timestamp.ByteArrayToHexString();
    return $"local: {local} dbValue {dbValue} dbUncommited { dbUncommited}";
   }
   
   static Person GetPersonUncommited()
   {
    Context ctx2 = new Context();
    return ctx2.Person.FromSqlRaw("SELECT * FROM Person with (nolock) where id = 1").ToList()[0];
   }
  }
 }
}
```

I attached the simple project that produced the screenshot.
[ConcurrencyTransactionProblem_Github.zip](https://github.com/aspnet/EntityFrameworkCore/files/3687916/ConcurrencyTransactionProblem_Github.zip)

### Further technical details

EF Core version: 2.2 and 3.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 2.2 und 3.0
Operating system: Windows 10 x64
IDE: Visual Studio 2019 16.3

**Comment by quan01994** [comment]
I met the same mistake.
[https://github.com/quan01994/MiniProgram](https://github.com/quan01994/MiniProgram)
````csharp

    public class BaseEntity
    {
        public int Id { get; set; }

        public DateTime CreateTime { get; set; }

        public bool IsDelete { get; set; }

        public DateTime UpdateTime { get; set; }

        [ConcurrencyCheck]
        public DateTime Version { get; set; }
    }

    builder.Property(p => p.Version).IsRowVersion().IsConcurrencyToken().ValueGeneratedOnAddOrUpdate().HasComputedColumnSql("GETDATE()");

    public class WebAppConfigEntity : BaseEntity
    {
        public string AppId { get; set; }

        public string Secret { get; set; }

        public string AccessToken { get; set; }


        public DateTime? AccessTokenRefreshTime { get; set; }
    }


        public async Task<IActionResult> Put()
        {
            var webAppConfigEntity = await _context.WebAppConfigEntities.FirstOrDefaultAsync();
            webAppConfigEntity.AccessTokenRefreshTime = DateTime.Now;
            await _context.SaveChangesAsync();
            return Ok();
        }
````
when i update ,
````log

2019-10-09 12:55:38.265 +08:00 [INF] Route matched with {action = "Put", controller = "Init"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Put() on controller MiniProgram.Api.Controllers.InitController (MiniProgram.Api).
2019-10-09 12:55:38.292 +08:00 [INF] Entity Framework Core 3.0.0 initialized 'MiniProgramDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: RowNumberPaging 
2019-10-09 12:55:38.424 +08:00 [INF] Executing DbCommand [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT TOP(1) [w].[Id], [w].[AccessToken], [w].[AccessTokenRefreshTime], [w].[AppId], [w].[CreateTime], [w].[IsDelete], [w].[Secret], [w].[UpdateTime], [w].[Version]
FROM [WebAppConfigEntities] AS [w]
2019-10-09 12:55:38.440 +08:00 [INF] Executing DbCommand [Parameters=[@p1='?' (DbType = Int32), @p0='?' (DbType = DateTime2), @p2='?' (DbType = DateTime2)], CommandType='"Text"', CommandTimeout='30']
SET NOCOUNT ON;
UPDATE [WebAppConfigEntities] SET [AccessTokenRefreshTime] = @p0
WHERE [Id] = @p1 AND [Version] = @p2;
SELECT [UpdateTime], [Version]
FROM [WebAppConfigEntities]
WHERE @@ROWCOUNT = 1 AND [Id] = @p1;
2019-10-09 12:55:38.455 +08:00 [INF] Executed action MiniProgram.Api.Controllers.InitController.Put (MiniProgram.Api) in 189.64950000000002ms
2019-10-09 12:55:38.455 +08:00 [INF] Executed endpoint 'MiniProgram.Api.Controllers.InitController.Put (MiniProgram.Api)'
2019-10-09 12:55:38.458 +08:00 [ERR] An unhandled exception has occurred while executing the request.
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithPropagationAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at MiniProgram.Api.Controllers.InitController.Put() in D:\RiderProjects\MiniProgram\MiniProgram.Api\Controllers\InitController.cs:line 50
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2019-10-09 12:55:38.481 +08:00 [INF] Request finished in 220.47920000000002ms 500 text/plain
````

**Comment by ajcvickers** [comment]
Note for triage: this is what is happening:
* The row for the first entity updates correctly and the timestamp column is updated in the database
* The update for the second row fails and an exception in thrown
* This means `AcceptChanges` is not called, and hence the tracked value is not updated for the timestamp on the first row, even though the database (at least inside this transaction) has been updated.

I think what needs to happen here is that if something in the transaction failed, then it needs to be rolled back before trying again. However, I'm not sure if this can be done automatically or not.
/cc @AndriySvyryd

**Comment by AndriySvyryd** [comment]
When the transaction is not controlled by EF I don't think we should do anything to compensate for this. We probably should expand the Concurrency Conflicts docs page to also cover how to deal with this.

**Comment by ajcvickers** [comment]
Filed https://github.com/aspnet/EntityFramework.Docs/issues/1857
