### ISSUE TITLE
Allow running tool against assemblies (as earlier), not only projects, as now

### ISSUE THREAD

**Issue by kreskiyan-clearscale** [dotnet/efcore#18292]
The problem is in running dotnet-ef inside Docker to handle migrations.

Most of the suggestions related migrating DB are focused on:
- either calling `Database.Migrate()` in startup (really don't like this idea due to possibilities limited only to migrate up and being called on every run, but it's handy) 
- or generating scripts with `dotnet ef migrations script` (requiring one to copy/paste scripts and run them manually)

Seeing, how useful is `dotnet ef database update` in local development, I've tried to use it in deployment scenarios.
Prior to recent changes in 3.0, it was possible with copying local ef.dll from dotnet installation root to container and launching with additional `--deps` and `--runtimeconfig`.

As of now, it requires me to publish source code in separate image and container, cause, likely, `--project` and `--start-project` flags require, at least, project files to make things happen.

Even though it's not expected use case for a design-time oriented tool, it would be really cool to allow running `dotnet-ef` tool in runtime-class Docker image against DLLs, not source code.
Thanks!

**Comment by bricelam** [comment]
> Prior to recent changes in 3.0, it was possible with copying local ef.dll from dotnet installation root to container and launching with additional --deps and --runtimeconfig.

This hasn't really changed. You just need to copy the files from `%USERPROFILE%\.dotnet\tools\.store\dotnet-ef` instead (after `dotnet tool install -g dotnet-ef`)

**Comment by kreskiyan-clearscale** [comment]
Not working still.

Dockerfile for testing is:
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.0-alpine as builder
COPY . /code
WORKDIR /app
RUN dotnet publish -c release -o /app /code/src/Project.Api && \
    EF_VERSION=3.0.0 && \
    dotnet tool install -g dotnet-ef --version $EF_VERSION && \
    mkdir -p .store/dotnet-ef && \
    cp -r ~/.dotnet/tools/.store/dotnet-ef/$EF_VERSION .store/dotnet-ef/ && \
    cp ~/.dotnet/tools/dotnet-ef ef

FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-alpine
WORKDIR /app
COPY --from=builder /app /app
VOLUME [ "/app/configuration" ]
CMD ["/bin/sh"]
```

Result of running command:
```
$ ./ef migrations list -p ./Project.Db.dll -s ./Project.Api.dll -c Context --verbose
sing project './Annium.Id.Db.dll'.
Using startup project './Annium.Id.Api.dll'.
Writing './obj/Annium.Id.Db.dll.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=/tmp/tmpjMOjmM.tmp /verbosity:quiet /nologo ./Annium.Id.Db.dll
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
Microsoft.EntityFrameworkCore.Tools.CommandException: Unable to retrieve project metadata. Ensure it's an MSBuild-based .NET Core project. If you're using custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option.
   at Microsoft.EntityFrameworkCore.Tools.Project.FromFile(String file, String buildExtensionsDir, String framework, String configuration, String runtime)
   at Microsoft.EntityFrameworkCore.Tools.RootCommand.Execute()
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Unable to retrieve project metadata. Ensure it's an MSBuild-based .NET Core project. If you're using custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option.
```

**Comment by ajcvickers** [comment]
@kreskiyan-clearscale Just calling the `dotnet-ef` command like that won't work. Instead look at the output of running `dotnet-ef migrations list -v` and use that as the basic of the command that needs to be built to run this without the SDK being installed. For example:
```
C:\Stuff\ThreeOhP7P\ThreeOhP7P>dotnet-ef migrations list -v
Using project 'C:\Stuff\ThreeOhP7P\ThreeOhP7P\ThreeOhP7P.csproj'.
Using startup project 'C:\Stuff\ThreeOhP7P\ThreeOhP7P\ThreeOhP7P.csproj'.
Writing 'C:\Stuff\ThreeOhP7P\ThreeOhP7P\obj\ThreeOhP7P.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\avickers\AppData\Local\Temp\tmpA8AC.tmp /verbosity:quiet /nologo C:\Stuff\ThreeOhP7P\ThreeOhP7P\ThreeOhP7P.csproj

Welcome to .NET Core 3.0!
---------------------
SDK Version: 3.0.100

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Find out what's new: https://aka.ms/dotnet-whats-new
Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
Write your first app: https://aka.ms/first-net-core-app
--------------------------------------------------------------------------------------
Writing 'C:\Stuff\ThreeOhP7P\ThreeOhP7P\obj\ThreeOhP7P.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\avickers\AppData\Local\Temp\tmpAFB2.tmp /verbosity:quiet /nologo C:\Stuff\ThreeOhP7P\ThreeOhP7P\ThreeOhP7P.csproj
dotnet build C:\Stuff\ThreeOhP7P\ThreeOhP7P\ThreeOhP7P.csproj /verbosity:quiet /nologo

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:04.95
dotnet exec --depsfile C:\Stuff\ThreeOhP7P\ThreeOhP7P\bin\Debug\netcoreapp3.0\ThreeOhP7P.deps.json --additionalprobingpath C:\Users\avickers\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig C:\Stuff\ThreeOhP7P\ThreeOhP7P\bin\Debug\netcoreapp3.0\ThreeOhP7P.runtimeconfig.json C:\Users\avickers\.dotnet\tools\.store\dotnet-ef\3.0.0-preview3.19153.1\dotnet-ef\3.0.0-preview3.19153.1\tools\netcoreapp3.0\any\tools\netcoreapp2.0\any\ef.dll migrations list --assembly C:\Stuff\ThreeOhP7P\ThreeOhP7P\bin\Debug\netcoreapp3.0\ThreeOhP7P.dll --startup-assembly C:\Stuff\ThreeOhP7P\ThreeOhP7P\bin\Debug\netcoreapp3.0\ThreeOhP7P.dll --project-dir C:\Stuff\ThreeOhP7P\ThreeOhP7P\ --language C# --working-dir C:\Stuff\ThreeOhP7P\ThreeOhP7P --verbose --root-namespace ThreeOhP7P
Using assembly 'ThreeOhP7P'.
Using startup assembly 'ThreeOhP7P'.
Using application base 'C:\Stuff\ThreeOhP7P\ThreeOhP7P\bin\Debug\netcoreapp3.0'.
Using working directory 'C:\Stuff\ThreeOhP7P\ThreeOhP7P'.
Using root namespace 'ThreeOhP7P'.
Using project directory 'C:\Stuff\ThreeOhP7P\ThreeOhP7P\'.
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'BloggingContext'.
Using context 'BloggingContext'.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.0.0 initialized 'BloggingContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding design-time services referenced by assembly 'ThreeOhP7P'.
No referenced design-time services were found.
Finding IDesignTimeServices implementations in assembly 'ThreeOhP7P'...
No design-time services were found.
20191014192616_One
20191014193128_Two

C:\Stuff\ThreeOhP7P\ThreeOhP7P>
```
Specifically, the line like this (with some formatting added):
```
dotnet exec
  --depsfile C:\Stuff\ThreeOhP7P\ThreeOhP7P\bin\Debug\netcoreapp3.0\ThreeOhP7P.deps.json
  --additionalprobingpath C:\Users\avickers\.nuget\packages 
  --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder"
  --runtimeconfig C:\Stuff\ThreeOhP7P\ThreeOhP7P\bin\Debug\netcoreapp3.0\ThreeOhP7P.runtimeconfig.json
  C:\Users\avickers\.dotnet\tools\.store\dotnet-ef\3.0.0-preview3.19153.1\dotnet-ef\3.0.0-preview3.19153.1\tools\netcoreapp3.0\any\tools\netcoreapp2.0\any\ef.dll migrations list 
  --assembly C:\Stuff\ThreeOhP7P\ThreeOhP7P\bin\Debug\netcoreapp3.0\ThreeOhP7P.dll 
  --startup-assembly C:\Stuff\ThreeOhP7P\ThreeOhP7P\bin\Debug\netcoreapp3.0\ThreeOhP7P.dll 
  --project-dir C:\Stuff\ThreeOhP7P\ThreeOhP7P\
  --language C# 
  --working-dir C:\Stuff\ThreeOhP7P\ThreeOhP7P
  --verbose
  --root-namespace ThreeOhP7P
```
should be the starting point for what you'll need to create.
