### ISSUE TITLE
EF Core hangs on keyless views in async/await ToListAsync()

### ISSUE THREAD

**Issue by the-black-wolf** [dotnet/efcore#18378]
I made a mistake in model builder, I (but this is just one example) added a keyless view and  marked a field as `DateTime`, while the SqlClient provided `DateTimeOffset`. But it is irrelevant, I think any error due to mismatch between model and database would cause this as long as it causes an exception between provider and EF. 

When I use async await and execute, no exception is thrown back and the program freezes (blocks the calling thread):
`return await dbContext.SsisMessage.ToListAsync();`

No exception is registered anywhere, neither in logging, nor in intellisense.

If instead I use `dbContext.SsisMessage.ToList();`

it properly throws:
```
Unable to cast object of type 'System.DateTimeOffset' to type 'System.DateTime'.
   at Microsoft.Data.SqlClient.SqlBuffer.get_DateTime()
   at Microsoft.Data.SqlClient.SqlDataReader.GetDateTime(Int32 i)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   ...
```

***UPDATE***
Even when model is fixed, the code hangs. So this might be a double issue (exception swallowing and some sort of deadlock). 

### Steps to reproduce

1. Add a keyless view to model builder, introduce a schema mismatch
2. Run async retrieval enclosed in try/catch
3. Exception never comes
4. Fix the model
5. Run async retrieval 
6. Calling thread hangs. 

### Further technical details
This might be some context issue, but I did not have the time to go through it thoroughly. But this should definitely not act as Task.Run(void Task) :) 

View signature:
![image](https://user-images.githubusercontent.com/15175507/66835083-31538700-ef5f-11e9-8cc6-a7dd87a107b0.png)

Model part:
``` C#
            modelBuilder.Entity<SsisMessage>(entity =>
            {
                entity.HasNoKey().ToView("SSISMessageLog");
                entity.Property(e => e.OperationMessageId).HasColumnName("operation_message_id");
                entity.Property(e => e.OperationId).HasColumnName("operation_id");
                entity.Property(e => e.MessageTime).HasColumnName("message_time");
                entity.Property(e => e.MessageType).HasColumnName("message_type");
                entity.Property(e => e.MessageSourceType).HasColumnName("message_source_type");
                entity.Property(e => e.Message).HasColumnName("message");
            });
```

poco class:
``` C#
    public class SsisMessage
    {
        public long OperationMessageId { get; set; }
        public long OperationId { get; set; }
        public DateTimeOffset MessageTime { get; set; }
        public string MessageType { get; set; }
        public string MessageSourceType { get; set; }
        public string Message { get; set; }
    }
```

calling methods:
``` C# 
        public async Task<IEnumerable<SsisMessage>> GetOperationLog(int operationId)
        {
            // returns data ok, but sync
            var ff = (from m in dbContext.SsisMessage.AsNoTracking()
                where m.OperationId == operationId
                orderby m.OperationMessageId descending
                select m).ToList();

            // async, but hangs
            return await (from m in dbContext.SsisMessage.AsNoTracking()
                    where m.OperationId == operationId
                    orderby m.OperationMessageId descending
                    select m
                ).ToListAsync();
        }
```

EF Core version: 3.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: netcoreapp3.0
Operating system: Windows 2019
IDE: Visual Studio 2019 16.4 Preview 1

**Comment by the-black-wolf** [comment]
This is actually much worse than initially seemed. Even when I corrected the model, the code hangs in calling thread. I will udpate my issue with more code.

**Comment by the-black-wolf** [comment]
Ok, this is definitely something context sync related. When I await the async Task involving EF operation it works ok. When I just `.Wait()` or `.Result()` it, then it hangs indefinitely. 

That is rather weird, maybe I do not understand async Tasks, but `.Wait()` should start it and then wait for it to be completed, no? And the exceptions should be collected in Task and thrown in calling context, no?

But this async task, it never starts. When I break the program, main thread is in WaitHelper, which is ok, but the task is still WaitingForActivation?!?

![image](https://user-images.githubusercontent.com/15175507/66844315-6ddaaf00-ef6e-11e9-98ab-25d8c56ad575.png)

Could this be related to the fact this is a WPF application? Does its UI thread context differ in such a way to cause deadlock?

**Comment by the-black-wolf** [comment]
Never mind, this is actually not related to EF at all, its about context in WPF applications, I will create a new issue there. Closing.
