### ISSUE TITLE
No coercion operator is defined between types 'EnumName' and 'System.String'.

### ISSUE THREAD

**Issue by cspwizard** [dotnet/efcore#18402]
There is InvalidOperationException ('No coercion operator is defined between types 'EnumName' and 'System.String'.') when try to insert entity with enum property. This property is described via fluent api:

``` C#
modelBuilder.Entity<MyEntity>().Property(e => e.EnumField).IsFixedLength().HasMaxLength(3)
                .HasConversion<string>(v => v.ToString(), v => Enum.Parse<MyEnum>(v));
```

Almost same code (without `IsFixedLength()`) works fine
``` C#
modelBuilder.Entity<MyEntity>().Property(e => e.EnumField).IsFixedLength().HasMaxLength(3)
                .HasConversion<string>(v => v.ToString(), v => Enum.Parse<MyEnum>(v));
```

### Steps to reproduce

Create entity with Enum field and describe it via fluent:

``` C#
modelBuilder.Entity<MyEntity>().Property(e => e.EnumField).IsFixedLength().HasMaxLength(3)
                .HasConversion<string>(v => v.ToString(), v => Enum.Parse<MyEnum>(v));
```
run migration (create db). And try to insert value in the table via EF Core.

### Further technical details

EF Core version: 3.0.0
Database provider: PostgreSQL (Npgsql.EntityFrameworkCore.PostgreSQL  Version=3.0.1)
Target framework: .NET Core 3.0
Operating system: windows 10

Stack trace:
```
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrAccessorFactory`1.Create(MemberInfo memberInfo, IPropertyBase propertyBase)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrPropertyGetterFactory.Create(IPropertyBase property)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyBase.<>c.<get_Getter>b__33_0(PropertyBase p)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyBase.get_Getter()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.ReadPropertyValue(IPropertyBase propertyBase)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.get_Item(IPropertyBase propertyBase)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.LocalDetectChanges(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager)
   at Microsoft.EntityFrameworkCore.ChangeTracking.ChangeTracker.DetectChanges()
   at Microsoft.EntityFrameworkCore.DbContext.TryDetectChanges()
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at DBScaffold.Program.<Main>d__0.MoveNext() in \\DBScaffold\Program.cs:line 44
```

**Comment by ajcvickers** [comment]
@cspwizard I attempted to reproduce this with the SQL Server provider and did not run into any issues--see my code below. This means either that:
* It's a Postgres issue
* Something else is going on in your code that I am not reproducing. Please try running my code against a Postgres database and check that the issue reproduces. If not, please investigate what conditions are required for us the reprodcuce the issue and post a small, runnable project/solution or complete code listing that demonstrates the issue.

/cc @roji 

```C#
public class MyEntity
{
    public int Id { get; set; }

    public MyEnum EnumField { get; set; }
}

public enum MyEnum
{
    One,
    Two
}

public class CurrentUserNameGenerator : ValueGenerator<string>
{
    public override bool GeneratesTemporaryValues => false;

    public override string Next(EntityEntry entry) => "FooBarUser";
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .Entity<MyEntity>()
            .Property(e => e.EnumField)
            .IsFixedLength()
            .HasMaxLength(3)
            .HasConversion(v => v.ToString(), v => Enum.Parse<MyEnum>(v));
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new MyEntity { EnumField = MyEnum.Two });
            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            var value = context.Set<MyEntity>().Single();
        }
    }
}
```

**Comment by cspwizard** [comment]
Hi @ajcvickers just tested with your example, it doesn't work with Postgres. So looks like the Postgres driver ussue.

**Comment by roji** [comment]
Note: this was opened for Npgsql as https://github.com/npgsql/efcore.pg/issues/920 and was confirmed as an Npgsql bug.
