### ISSUE TITLE
IComparable lamda-expression and dynamic call to OrderBy (Expression.Call) cannot be translated

### ISSUE THREAD

**Issue by toralux** [dotnet/efcore#18636]
Building IComparable lamda-expression to sort using dynamic call to OrderBy (Expression.Call) fails with "could not be translated"-error. This used to work in EF Core 2.0 (without any client evaluation), but now throws exception.

### Steps to reproduce
A small example that is able to reproduce this bug.

``` C#
    public static class Helper
    {
        public static LambdaExpression GetComparableSelector<T>(this IQueryable<T> queryable, Expression<Func<T, IComparable>> comparableSelector)
        {
            return comparableSelector;
        }

        public static IQueryable<T> AddSorting<T>(this IQueryable<T> queryable, LambdaExpression lambda)
        {
            var methodCall = Expression.Call(
                typeof(Queryable), "OrderBy", new[] { queryable.ElementType, typeof(IComparable) },
                queryable.Expression, lambda);

            return queryable.Provider.CreateQuery<T>(methodCall);
        }
    }

    using (var provider = services.BuildServiceProvider())
    {
        var ctx = provider.GetService<SomeDbContext>();

        var dbSet = ctx.SomeDbSet

        // Example 1
        // Working
        var obj1 = dbSet.OrderBy(x => x.CreatedDate).FirstOrDefault();

        // Example 2
        var lambda = dbSet.GetComparableSelector(x => x.CreatedDate);
        var query = dbSet.AddSorting(lambda);

        // Not working
        var obj2 = query.FirstOrDefault();
    };
```
Error message:
The LINQ expression 'OrderBy<SomeEntity, IComparable>(
    source: DbSet<SomeEntity>, 
    keySelector: (c) => (IComparable)(c.CreatedDate))' could not be translated. 

Full exception log:
System.InvalidOperationException
  HResult=0x80131509
  Message=The LINQ expression 'OrderBy<SomeEntity, IComparable>(
    source: DbSet<SomeEntity>, 
    keySelector: (c) => (IComparable)c.CreatedDate)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|8_0(ShapedQueryExpression translated, <>c__DisplayClass8_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at EfCoreTestConsoleApp.Program.Main(String[] args) in C:\Users\toraj\source\repos\temp\EfCoreTestConsoleApp\Program.cs:line 69

### Further technical details

EF Core version: 3.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.0

**Comment by ajcvickers** [comment]
@smitpatel to show different way to write query.

**Comment by smitpatel** [comment]
```C#
 public static class Helper
    {
        public static LambdaExpression GetComparableSelector<T>(this IQueryable<T> queryable, Expression<Func<T, object>> comparableSelector)
        {
            return comparableSelector;
        }

        public static IQueryable<T> AddSorting<T>(this IQueryable<T> queryable, LambdaExpression lambda)
        {
            var methodCall = Expression.Call(
                typeof(Queryable), "OrderBy", new[] { queryable.ElementType, typeof(object) },
                queryable.Expression, lambda);

            return queryable.Provider.CreateQuery<T>(methodCall);
        }
    }

    using (var provider = services.BuildServiceProvider())
    {
        var ctx = provider.GetService<SomeDbContext>();

        var dbSet = ctx.SomeDbSet

        // Example 1
        // Working
        var obj1 = dbSet.OrderBy(x => x.CreatedDate).FirstOrDefault();

        // Example 2
        var lambda = dbSet.GetComparableSelector(x => x.CreatedDate);
        var query = dbSet.AddSorting(lambda);

        // Not working
        var obj2 = query.FirstOrDefault();
    };

**Comment by toralux** [comment]
@smitpatel Thanks, now it's working after changing my code as described.

My example used to work in EF Core 2.x. You can close this issue if backward-compatibility in this situation is not required. Thanks a lot! :)
