### ISSUE TITLE
Using HasOperators() on PostgreSQL lead to exception on megration creating

### ISSUE THREAD

**Issue by Vick-edit** [dotnet/efcore#18678]
We have database based on PortgreSQL. Resently we migrate from .net core 2.2 to 3.0 and now we cannot creating migration by "add-migration". We tryed use scaffolding to create entities and maping and create Initial migration after that and got same exception every time.

We use varchar feld  based index with option "varchar_pattern_ops". And we use .HasOperators("varchar_pattern_ops") call on index maping, that's lead to exception:
"Unable to cast object of type 'System.String[]' to type 'System.String'." If migration will be created withot using HasOperators threre is will no error.

### Steps to reproduce
1. Create index on varchar feld with call .HasOperators("varchar_pattern_ops") 
2. Call "add-migration" to create migration 
3. Got exception

Entity example:
``` C#
    public class ExampleEntity
    {
        public int Id { get; set; }
        public int Name { get; set; }
    }
```

Maping example:
``` C#
    public static  class ExampleEntityMap
    {
        public static void Register(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ExampleEntity>(entity =>
            {
                entity.ToTable("ExampleTable");

                entity.HasKey(e => e.Id);

                entity.Property(e => e.Id)
                    .HasColumnName("id");                
                
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasColumnName("name");

                entity.HasIndex(e => e.Name)
                    .HasOperators("varchar_pattern_ops")
                    .HasName("NI_ExampleTable_Name");
            });
        }
    }
```

DbContext example:
``` C#
    public class ExampleDbContext : DbContext
    {
        public ExampleDbContext(){}

        public ExampleDbContext(DbContextOptions<ExampleDbContext> options)
            : base(options){}

        public virtual DbSet<ExampleEntity> TransactionModuleTransactionToAsset { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                var connectionString = "put_connection_string_here";
                optionsBuilder.UseNpgsql(connectionString);
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            ExampleEntityMap.Register(modelBuilder);
        }
    }
```

Exception:
```
PM> add-migration EF_CORE_v3.0 -Context ExampleDbContext
System.InvalidCastException: Unable to cast object of type 'System.String[]' to type 'System.String'.
   at Microsoft.EntityFrameworkCore.NpgsqlIndexExtensions.GetMethod(IIndex index) in C:\projects\npgsql-entityframeworkcore-postgresql\src\EFCore.PG\Extensions\NpgsqlIndexExtensions.cs:line 26
   at Npgsql.EntityFrameworkCore.PostgreSQL.Migrations.Internal.NpgsqlMigrationsAnnotationProvider.For(IIndex index)+MoveNext() in C:\projects\npgsql-entityframeworkcore-postgresql\src\EFCore.PG\Migrations\Internal\NpgsqlMigrationsAnnotationProvider.cs:line 52
   at Microsoft.EntityFrameworkCore.MutableAnnotatableExtensions.AddAnnotations(IMutableAnnotatable annotatable, IEnumerable`1 annotations)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Add(IIndex target, DiffContext diffContext)+MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Add(TableMapping target, DiffContext diffContext)+MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IModel source, IModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to cast object of type 'System.String[]' to type 'System.String'.
```
-->

### Further technical details

Target framework: .NET Core 3.0
EF Core version: 3.0.0
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL v.3.0.1
Database: PostgreSQL v.9.5.17
Operating system: Windows 10
IDE: Visual Studio 2019 16.3.7

**Comment by roji** [comment]
Npgsql issue, already filed as https://github.com/npgsql/efcore.pg/issues/1104.
