### ISSUE TITLE
Insert after Migration from EF 2 to 3 no longer working

### ISSUE THREAD

**Issue by dh-connect** [dotnet/efcore#18735]
My inserts are failing with SqlException: 
Cannot insert the value NULL into column 'REQ_NO', table 'PRD.dbo.TBL_REQ'; column does not allow nulls. INSERT fails. The statement has been terminated.

after migration with no code change, code worked in EF 2.
Using EF Core v 3.0.0

I debugged and REQ_NO is filled, before sending Add record request.

Failing Code Statement:

```
TblReq newReq = _mapper.Map<TblReq>(vm.ReqView);
_db.TblReq.Add(newReq);
```

I created a view model based on db entity:
```
public partial class TblReq
{
        public TblReq()
   
        public int ReqId { get; set; }
        public virtual string ReqNo { get; set; }
}

```
extended in view model with annotations:

```
public class ReqView : TblReq
{
        [Required]
        [Display(Name = "ReqNo*")]
        [MinLength(7, ErrorMessage = "...")]
        [MaxLength(20, ErrorMessage = "...")]
        public override string ReqNo  { get; set;  }
}
```

ReqView is filled in View and translated back into TblReq using AutoMapper 7 (AutoMapper.Extensions.Microsoft.DependencyInjection)

```
using AutoMapper;
TblReq newReq = _mapper.Map<TblReq>(vm.ReqView);
```

with domain profile
```

public class DomainProfile : Profile
{
        public DomainProfile()
        {
            CreateMap<TblReq, ReqView>();
        }
}
```

with db context:

```
 modelBuilder.Entity<TblReq>(entity =>
{
                entity.HasKey(e => e.ReqId);

                entity.ToTable("TBL_REQ");

                entity.Property(e => e.ReqId).HasColumnName("REQ_ID");

                entity.Property(e => e.ReqNo)
                    .IsRequired()
                    .HasColumnName("REQ_NO")
                    .HasMaxLength(255);
};
```

full stack trace

Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'REQ_NO', table 'REPO_PRD.dbo.TBL_REQ'; column does not allow nulls. INSERT fails.

The statement has been terminated.

   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)

   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)

   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()

   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()

   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)

   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)

   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)

   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)

   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)

   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)

ClientConnectionId:xxx

Error Number:515,State:2,Class:16

**Comment by AndriySvyryd** [comment]
@dh-connect Could you create a small runnable project that exhibits this issue? Preferably without using AutoMapper

**Comment by dh-connect** [comment]
I did a test bypassing the AutoMapper and mapping it manually.

```
 TblReq newReq = new TblReq();
 newReq.ReqNo = vm.ReqView.ReqNo;
_db.TblReq.Add(newReq);
```
The error went away.

So it is the mapped object which is not working any longer. (worked in EF 2)

I have a very large model and don't want to map it all manually, any advice where to go from here?

**Comment by AndriySvyryd** [comment]
@dh-connect Try adding the AutoMapper back now to your test and see what output it actually produces and how is it different from the manual object. Perhaps this can be fixed through some changes to the AutoMapper configuration.
