### ISSUE TITLE
[2.2.7] SingleOrDefault() throws exception while database contains only one row

### ISSUE THREAD

**Issue by glararan** [dotnet/efcore#18781]
I have table Categories. Some category pages thows exception "Sequence contains more than one..." even if database table contains just one row.

### Steps to reproduce
- Well I dont know how to simple reproduce it for this issue. I dont know why 99% categories works. But few ones not. I mean I dont know what to write for reproducing.

``` C#
var categories = await db.Categories.Include(c => c.Parent).Include(x => x.Childs).ThenInclude(x => x.Image).Include(x => x.Childs).ThenInclude(x => x.SEO).Include(x => x.Products).Include(x => x.SEO).AsNoTracking().Where(m => m.Id == id).ToListAsync(); // checking via watch if there are two items

Category category = await db.Categories.Include(c => c.Parent).Include(x => x.Childs).ThenInclude(x => x.Image).Include(x => x.Childs).ThenInclude(x => x.SEO).Include(x => x.Products).Include(x => x.SEO).AsNoTracking().SingleOrDefaultAsync(m => m.Id == id); // <---- using this code

// watch categories[0] == categories[1] // **true!!!**
```

**Got Exceptions? Include both the message and the stack trace**
```
Microsoft.EntityFrameworkCore.Query:Error: An exception occurred while iterating over the results of a query for context type 'Data.DatabaseContext'.
System.InvalidOperationException: Source sequence contains more than one element.
   at System.Linq.AsyncEnumerable.SingleOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Single.cs:line 154
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
```

### Further technical details
.NET Core Version: Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
EF Core version: 2.2.6
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 2.2)
Operating system: Windows 10 x64 Pro 1903
IDE: Visual Studio 2019 16.3

---------------------------------------

Can you say how to make it easier for you to reproduce it?

EDIT: Testing rows count return for EF vs Database => 4526 / 4524 (What the hell? How)

OnModelCreating
```
builder.Entity<Category>().HasOne(x => x.SEO).WithOne(x => x.Category).HasForeignKey<SEO>(x => x.CategoryId).OnDelete(DeleteBehavior.Cascade);
builder.Entity<SEO>().HasOne(x => x.Category).WithOne(x => x.SEO).OnDelete(DeleteBehavior.SetNull);
builder.Entity<Category>().HasMany(x => x.Products).WithOne(x => x.Category).OnDelete(DeleteBehavior.Cascade);
```

Category
```
    public class Category
    {
        public int Id { get; set; }
        [Required]
        public bool Enabled { get; set; }
        [Required]
        public bool Hidden { get; set; }
        [Required]
        public string Name { get; set; }
        public string Description { get; set; }
        [Required]
        public int DisplayOrder { get; set; }
        public int? ImageId { get; set; }
        public int? ParentId { get; set; }

        [ForeignKey("ImageId")]
        [Display(Name = "Obrázek")]
        public ImageFile Image { get; set; }
        [ForeignKey("ParentId")]
        public Category Parent { get; set; }
        public SEO SEO { get; set; }

        public ICollection<Category> Childs { get; set; }
        public ICollection<CategoryProduct> Products { get; set; }

        [NotMapped]
        public IFormFile ImageFile { get; set; }

        [NotMapped]
        public bool Checked { get; set; } // Products/Create or Edit
    }
```

SEO
```
    public class SEO
    {
        public int Id { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeywords { get; set; }
        public string FriendlyUrl { get; set; }

        public int? CategoryId { get; set; }
        public int? ProductId { get; set; }
        public int? PageId { get; set; }

        [ForeignKey("CategoryId")]
        public Category Category { get; set; }
        [ForeignKey("ProductId")]
        public Product Product { get; set; }
        [ForeignKey("PageId")]
        public Page Page { get; set; }
    }
```

**Comment by ajcvickers** [comment]
@glararan A lot of code here was changed for the 3.0 release. Please test this with EF Core 3.0, or better still, the latest 3.1 [daily build](https://github.com/aspnet/AspNetCore/blob/master/docs/DailyBuilds.md). If the error is happening, then please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by glararan** [comment]
@ajcvickers I am trying to stick at 2.2.7 because as you mentioned.. a lot of code was change on EF 3.0. I would had to change a lot of code :(

Anyway thanks. I have to wait till I upgrade whole project to 3.1
