### ISSUE TITLE
InvalidCastException on custom types used as keys

### ISSUE THREAD

**Issue by QuantumToasted** [dotnet/efcore#18821]
*(Disclaimer: I am unsure if this is a limitation of EF Core, a bug, or a problem in my own code. But I did as much testing as I could and determined that it something is amiss here.)*

I am working on a [Discord bot](https://github.com/QuantumToasted/Administrator/tree/rewrite/Administrator), which uses EF Core with PostgreSQL as its database provider, porting from one internal library to another, which replaces all `ulong`s on its models with a custom type, `Snowflake`. The long and short of __why__ I'm doing this at all is because I wanted to try to change all `ulong` properties in my database models to their respective `Snowflake` counterpart.

However, attempting to use `FirstOrDefaultAsync` to find models with a `Snowflake` as their key, or part of it, causes a `System.InvalidCastException` to be thrown:
```
System.InvalidCastException: Invalid cast from 'System.UInt64' to 'Disqord.Snowflake'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.UInt64.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.Sanitize[T](Object value)
   at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.<>c__DisplayClass3_0`2.<SanitizeConverter>b__0(Object v)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping.CreateParameter(DbCommand command, String name, Object value, Nullable`1 nullable)
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypeMappedRelationalParameter.AddDbParameter(DbCommand command, Object value)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBase.AddDbParameter(DbCommand command, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.CreateCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Administrator.Database.AdminDatabaseContext.GetOrCreateGuildAsync(Snowflake guildId) in C:\Users\Daniel Jarski\source\repos\Administrator\Administrator\Database\AdminDatabaseContext.cs:line 64
```
(The code in question: https://github.com/QuantumToasted/Administrator/blob/36bd6f3c6e86c126428eaafe86623319f8f19461/Administrator/Database/AdminDatabaseContext.cs#L62-L71)

I was originally unsure as to the cause of the issue, so after much asking around, testing, changing small pieces of code, all to no avail, I broke the problem down into the smallest possible pieces to investigate. I was able to pinpoint the source of the issue: **Steps to reproduce** will have a better explanation of the source of the issue and how to prevent the exception from happening.

### Steps to reproduce
1). Create a simple `Snowflake` struct and a class to contain it as the key. You MUST define the `==` and `!=` methods.
*(Note: The real struct used in the library I am using has many more properties and methods which did not seem to affect this reproduction.)*
```cs
public readonly struct Snowflake
{
    public Snowflake(ulong rawValue)
    {
        RawValue = rawValue;
    }

    public ulong RawValue { get; }

    public static implicit operator Snowflake(ulong value)
        => new Snowflake(value);

    public static implicit operator ulong(Snowflake value)
        => value.RawValue;

    public static bool operator ==(Snowflake left, ulong right)
        => (ulong) left == right;

    public static bool operator !=(Snowflake left, ulong right)
        => (ulong) left != right;
}
```
```cs
public sealed class SnowflakeAsKey
{
    public Snowflake Key { get; set; }

    public int Value { get; set; }
}
```
2). Create an extremely simple `DbContext` that was able to contain this simple model:
*(Note: Defining a custom `ValueConverter<Snowflake, ulong>` instead of the simple example here did not affect this reproduction.)*
```cs
public sealed class SnowflakeDbContext : DbContext
{
    private const string CONNECTION_STRING = "YOUR_CONNECTION_STRING";

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseNpgsql(CONNECTION_STRING);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<SnowflakeAsKey>(model =>
        {
            model.HasKey(x => x.Key);
            model.Property(x => x.Key)
                .HasConversion(x => x.RawValue, x => new Snowflake(x));
        });
    }

    public DbSet<SnowflakeAsKey> SnowflakesAsKeys { get; set; }
}
```

3). Create a migration, update the database, however you might go about setting up the tables on your database. They should succeed. 
4). Add sample data to the table: A model with Key `167452465317281793` and Value `1` was what I used for testing.
5). Create the `DbContext` and attempt to perform the following query (using my example data):
```cs
var key = 167452465317281793ul;
var ctx = new SnowflakeDbContext();

// This line throws.
var model = await ctx.SnowflakesAsKeys.FirstOrDefaultAsync(x => x.Key == key);
```

If you did everything correctly, the last line of the above code snippet should throw an `InvalidCastException`. 
Removing the `==` and `!=` methods prevents this issue from occurring, and I cannot seem to explain why or how this occurs.

I cannot impose upon the maintainer of this library to remove these operators, so any advice or suggestions on how to avoid or prevent this error would be appreciated.

### Further technical details

EF Core version: `3.0.0`
Database provider: `Npgsql.EntityFrameworkCore.PostgreSQL`
Target framework: `.NET Core 3.0`
Operating system: `Windows 10 x64`
IDE: `Visual Studio 2019 16.3.7`

**Comment by ajcvickers** [comment]
Note for triage: reproduced on SQL Server with 3.1 daily build.

```C#
public readonly struct Snowflake
{
    public Snowflake(ulong rawValue)
    {
        RawValue = rawValue;
    }

    public ulong RawValue { get; }

    public static implicit operator Snowflake(ulong value)
        => new Snowflake(value);

    public static implicit operator ulong(Snowflake value)
        => value.RawValue;

    public static bool operator ==(Snowflake left, ulong right)
        => (ulong) left == right;

    public static bool operator !=(Snowflake left, ulong right)
        => (ulong) left != right;
}

public sealed class SnowflakeAsKey
{
    public Snowflake Key { get; set; }

    public int Value { get; set; }
}

public class BloggingContext : DbContext
{
    private static readonly ILoggerFactory Logger = LoggerFactory.Create(x => x.AddConsole());

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<SnowflakeAsKey>(b =>
        {
            b.HasKey(x => x.Key);
            b.Property(e => e.Key).HasConversion(x => x.RawValue, x => new Snowflake(x));
        });
    }
    
    public DbSet<SnowflakeAsKey> SnowflakesAsKeys { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseLoggerFactory(Logger)
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
}

public class Program
{
    public static async Task Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new SnowflakeAsKey());

            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            Snowflake key = 167452465317281793ul;

            var model = await context.SnowflakesAsKeys.FirstOrDefaultAsync(x => x.Key == key);
        }
    }
}
```

**Comment by ajcvickers** [comment]
Notes for triage:

When both implicit conversions and equality operators are defined as in the repro, the expression tree (for similar query using `Where`) is:

```
.Call System.Linq.Queryable.Where(
    .Constant<Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[SnowflakeAsKey]>(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[SnowflakeAsKey]),
    '(.Lambda #Lambda1<System.Func`2[SnowflakeAsKey,System.Boolean]>))

.Lambda #Lambda1<System.Func`2[SnowflakeAsKey,System.Boolean]>(SnowflakeAsKey $x) {
    $x.Key == (System.UInt64).Constant<Program+<>c__DisplayClass0_0>(Program+<>c__DisplayClass0_0).key
}
```

When the equality operators are removed everything works. The implicit conversions kick in to use equality as defined between two uints: 

```
.Call System.Linq.Queryable.Where(
    .Constant<Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[SnowflakeAsKey]>(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[SnowflakeAsKey]),
    '(.Lambda #Lambda1<System.Func`2[SnowflakeAsKey,System.Boolean]>))

.Lambda #Lambda1<System.Func`2[SnowflakeAsKey,System.Boolean]>(SnowflakeAsKey $x) {
    (System.UInt64)$x.Key == (System.UInt64).Constant<Program+<>c__DisplayClass0_0>(Program+<>c__DisplayClass0_0).key
}
```
The code won’t compile if both implicit conversion and operators removed.

Adding in equality operators that don’t use conversion works again, even if the other operators and conversions are left in place. Code:

```C#
public static bool operator ==(Snowflake left, Snowflake right)
    => left.RawValue == right.RawValue;

public static bool operator !=(Snowflake left, Snowflake right)
    => left.RawValue != right.RawValue;
```
Expression:
```
.Call System.Linq.Queryable.Where(
    .Constant<Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[SnowflakeAsKey]>(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[SnowflakeAsKey]),
    '(.Lambda #Lambda1<System.Func`2[SnowflakeAsKey,System.Boolean]>))

.Lambda #Lambda1<System.Func`2[SnowflakeAsKey,System.Boolean]>(SnowflakeAsKey $x) {
    $x.Key == .Constant<Program+<>c__DisplayClass0_0>(Program+<>c__DisplayClass0_0).key
}
```

**Comment by ajcvickers** [comment]
We discussed this in triage and decided that it is not unreasonable to include operators that do not require implicit conversions to work. For example:

```C#
public readonly struct Snowflake
{
    public Snowflake(ulong rawValue)
    {
        RawValue = rawValue;
    }

    public ulong RawValue { get; }

    public static implicit operator Snowflake(ulong value)
        => new Snowflake(value);

    public static implicit operator ulong(Snowflake value)
        => value.RawValue;

    public static bool operator ==(Snowflake left, ulong right)
        => (ulong) left == right;

    public static bool operator !=(Snowflake left, ulong right)
        => (ulong) left != right;

    public static bool operator ==(Snowflake left, Snowflake right)
        => left.RawValue == right.RawValue;

    public static bool operator !=(Snowflake left, Snowflake right)
        => left.RawValue != right.RawValue;
}
```
