### ISSUE TITLE
FirstOrDefault of Navigation property nested in Select statement

### ISSUE THREAD

**Issue by prodenx** [dotnet/efcore#18858]
Hi,

I have entity with children navigation property. Each child has children property too. I need access to second level children property, get FirstOrDefault entry according condition and take value of property. The code is below:

Query:

    _repository.Where(product => product.Date >= startDate).Include(product => product.Shift).ThenInclude(shift => shift.Translations)
                      .GroupBy(product => product.Shift)
                      .OrderBy(pg => pg.Key.Id)
                      .Select(pg =>
                          new TupleDto<string, double>()
                          {
                              Item1 = pg.Key.Translations.FirstOrDefault(t => t.Language == "en").Title
                          }).ToListAsync();

Entities:

    public class Product
    {        
        [Column(TypeName = "date")]
        public DateTime Date { get; set; }
        
        public int ShiftId { get; set; }

        [ForeignKey("ShiftId")]
        public Shift Shift { get; set; }
    }

    [Table("Shifts")]
    public class Shift: FullAuditedEntity<int>, IMultiLingualEntity<ShiftTranslation>
    {
        public ICollection<ShiftTranslation> Translations { get; set; }
    }

    [Table("ShiftTranslations")]
    public class ShiftTranslation : Entity, IEntityTranslation<Shift>
    {
        [Required]
        [Column(TypeName = "nvarchar(16)")]
        public string Title { get; set; }

        [Column(TypeName = "varchar(16)")]
        public string Language { get; set; }
        public Shift Core { get; set; }
        public int CoreId { get; set; }
    }

I get exception:

    Processing of the LINQ expression 'AsQueryable<ShiftTranslation>(NavigationTreeExpression
        Value: default(IGrouping<Shift, ShoePair>)
        Expression: (Unhandled parameter: e).Key.Translations)' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.
    System.InvalidOperationException: Processing of the LINQ expression 'AsQueryable<ShiftTranslation>(NavigationTreeExpression
        Value: default(IGrouping<Shift, ShoePair>)
        Expression: (Unhandled parameter: e).Key.Translations)' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.
       at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
       at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
       at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
       at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
       at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
       at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
       at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
       at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
       at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
       at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ExpandNavigationsInExpression(NavigationExpansionExpression source, Expression expression)
       at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ExpandNavigationsInLambdaExpression(NavigationExpansionExpression source, LambdaExpression lambdaExpression)
       at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ProcessSelect(NavigationExpansionExpression source, LambdaExpression selector)
       at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
       at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ExpandAndReduce(Expression query, Boolean applyInclude)
       at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(Expression query)
       at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
       at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
       at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
       at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
       at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
       at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
       at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
       at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
       at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
       at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
       at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
       at DigitalFactory.Ftt.Report.ReportAppService.GetFttByShift(DateTime startDate, DateTime endDate, String factoryId, String productionLineId) in D:\work\DigitalFactory\DigitalFactory\aspnet-core\DigitalFactory\FTT\DigitalFactory.Ftt.Application\Report\ReportAppService.cs:line 104
       at lambda_method(Closure , Object )
       at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
       at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

As I guess it is caused by breaking changes in EF Core 3.0. Is it bug or it is correct behaviour?
Is it possible to refactor the query to make it working on SQL server side without processing data partly on client side?

### Further technical details

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.3

**Comment by ajcvickers** [comment]
@prodenx Thanks for filing this issue. We will discuss in our next triage meeting.

**Comment by ajcvickers** [comment]
Duplicate of #17068

**Comment by smitpatel** [comment]
https://docs.microsoft.com/en-us/ef/core/querying/complex-query-operators#groupby

**Comment by prodenx** [comment]
Thanks for info

**Comment by prodenx** [comment]
Btw, are you going to add support of COUNT with predicate in grouping? Are there any workaround now?

**Comment by smitpatel** [comment]
@prodenx - #11711
