### ISSUE TITLE
EF Migrations do not work when the HostBuilder is called something different

### ISSUE THREAD

**Issue by tidusjar** [dotnet/efcore#18860]
In the startup project, when the HostBuilder method is called something different e.g. 
```
     public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
```

EF Migrations will not migrate

### Steps to reproduce

1. Create a new .net core API project
1. Add EF Core
1. Setup some code first models ready to create migrations for
1. Rename the `CreateWebHostBuilder` in `Program.cs` to a different method name
1. run `dotnet ef migrations add TestMigration --verbose`

### Exception Information
```
--
-- Build success info
--
Time Elapsed 00:00:13.35
dotnet exec --depsfile C:\_work\Saltash\Airops.Authorization.API\bin\Debug\netcoreapp2.2\Airops.Authorization.API.deps.json --additionalprobingpath C:\Users\jrees\.nuget\packages --additionalprobingpath C:\Microsoft\Xamarin\NuGet --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig C:\_work\Saltash\Airops.Authorization.API\bin\Debug\netcoreapp2.2\Airops.Authorization.API.runtimeconfig.json C:\Users\jrees\.dotnet\tools\.store\dotnet-ef\3.0.0-preview6.19304.10\dotnet-ef\3.0.0-preview6.19304.10\tools\netcoreapp3.0\any\tools\netcoreapp2.0\any\ef.dll migrations add UserLocking --assembly C:\_work\Saltash\Airops.Authorization.API\bin\Debug\netcoreapp2.2\Airops.Authorization.Store.dll --startup-assembly C:\_work\Saltash\Airops.Authorization.API\bin\Debug\netcoreapp2.2\Airops.Authorization.API.dll --project-dir C:\_work\Saltash\Airops.Authorization.Store\ --language C# --working-dir C:\_work\Saltash\Airops.Authorization.Store --verbose --root-namespace Airops.Authorization.Store
Using assembly 'Airops.Authorization.Store'.
Using startup assembly 'Airops.Authorization.API'.
Using application base 'C:\_work\Saltash\Airops.Authorization.API\bin\Debug\netcoreapp2.2'.
Using working directory 'C:\_work\Saltash\Airops.Authorization.API'.
Using root namespace 'Airops.Authorization.Store'.
Using project directory 'C:\_work\Saltash\Airops.Authorization.Store\'.
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider...
Finding IWebHost accessor...
No CreateWebHostBuilder(string[]) method was found on type 'Airops.Authorization.API.Program'.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'AuthorizationDbContext'.
Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create an object of type 'AuthorizationDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728 ---> System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to create an object of type 'AuthorizationDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
```

### Further technical details

EF Core version: Microsoft.AspNetCore.Identity.EntityFrameworkCore 2.2.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .Net Core 2.2
Operating system: Windows 10
IDE: Powershell

**Comment by ajcvickers** [comment]
@tidusjar ASP.NET defines the well-known name pattern here; EF just uses it. https://github.com/aspnet/Extensions is likely the correctly place to suggest changes to that pattern.

Beyond this, see [the documentation](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dbcontext-creation) for other ways to use Migrations without opting in to the ASP.NET pattern.
