### ISSUE TITLE
efCore won't consider backing field type when initializing IEnumerable property

### ISSUE THREAD

**Issue by MHDuke** [dotnet/efcore#18898]
this issue is closely related to #15506, if not the same. Please read and run tests attached.
i have a private `HashSet` backing field for public `IEnumerable`. if i didnt initialize the hashset myself (on the field declaration). ef core would initialize it with some `ICollection` type.

```
private HashSet<VehicleFeature> _features;
public IEnumerable<VehicleFeature> Features 
        { 
            get => _features; 
            private set => _features = new HashSet<VehicleFeature>(value); 
        }
```
with above code, when `ef` initializes the entity. The HashSet `_features` would gladly add duplicate values.  `_features` is no longer a `hashSet`! But if `_features` initialization be: 
`private HashSet<VehicleFeature> _features = new HashSet<VehicleFeature>();`
it works just fine.

More over, i created a test entity to make sure it's not something that i am missing.

```
private HashSet<string> _strings;
public IEnumerable<string> Strings 
        { 
            get => _strings;
            private set => _strings = new HashSet<string>(value); 
        }
```
But this time i initialize the `_strings` or not, i receive

> System.InvalidCastException
>   HResult=0x80004002
>   Message=Unable to cast object of type 'System.Collections.Generic.List`1[System.String]' to type 'System.Collections.Generic.HashSet`1[System.String]'.
>   Source=Microsoft.EntityFrameworkCore.Relational
>   StackTrace:
>    at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
>    at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
>    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
>    at System.Linq.Queryable.First[TSource](IQueryable`1 source)
>    at EF.Tests.StringsTest.Can_EfCore_Initialize_The_Strings_IEnumerable_Properly()
[efHashsetIssue.zip](https://github.com/aspnet/EntityFrameworkCore/files/3846519/efHashsetIssue.zip)

//cc @ajcvickers
ef 3 with Sqlite 3
.netstandard 2.1

**Comment by ajcvickers** [comment]
@MHDuke EF Core can only track a single entity instance with a given type and ID. Therefore, when EF creates collections for you it does so using a reference equality comparer whenever possible. This helps ensure that two instances representing the same entity aren't confused with each other. See https://github.com/aspnet/EntityFrameworkCore/issues/15687#issuecomment-492280606 for some additional comments.

**Comment by MHDuke** [comment]
@ajcvickers sorry for reopening, but what do you suggest when it comes to utilizing `HashSet` for maintaining unique objects in collection having their equality operators overridden. because it is more than a month now and i am unable to get to a conclusion. Shall i not use HashSets altogether? Use `List` and always check before adding new objects to a collection instead. 

I also want to thank you Arthur and your team. you guys are doing great job. Thank you.

**Comment by ajcvickers** [comment]
@MHDuke EF cannot handle multiple instances of the same entity type that have the same key values. If that's what you have, then you'll need to resolve them down to a single instance before giving them to EF to track.

**Comment by MHDuke** [comment]
@ajcvickers 
> Therefore, when EF creates collections for you it does so using a reference equality comparer whenever possible.

Can i override this "create collection using reference equality" behavior  by configuration?
I can override it by initializing the HashSet at field declarations `private HashSet<> _mySet = new HashSet<>;` is there other way to do it?

**Comment by ajcvickers** [comment]
@MHDuke There isn't a way to override this because, as explained above, in general EF won't work correctly when using collections defined like this.
