### ISSUE TITLE
Value generators that use the store should trigger database initialization

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#1889]
Running the code below results in this exception:

```
Unhandled Exception: System.Data.SqlClient.SqlException: Invalid object name 'De
faultSequence'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolea
n breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception
, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObj
ect stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand
 cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler,
TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, Run
Behavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBe
havior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 time
out, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameter
EncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehav
ior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletio
nSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehav
ior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at Microsoft.Data.Entity.Relational.SqlStatementExecutor.<>c__DisplayClass8_0
.<ExecuteScalar>b__0() in C:\enlistments\Universe\EntityFramework\src\EntityFram
ework.Relational\SqlStatementExecutor.cs:line 146
   at Microsoft.Data.Entity.Relational.SqlStatementExecutor.Execute(IRelationalC
onnection connection, Func`1 action) in C:\enlistments\Universe\EntityFramework\
src\EntityFramework.Relational\SqlStatementExecutor.cs:line 168
   at Microsoft.Data.Entity.Relational.SqlStatementExecutor.ExecuteScalar(IRelat
ionalConnection connection, DbTransaction transaction, String sql) in C:\enlistm
ents\Universe\EntityFramework\src\EntityFramework.Relational\SqlStatementExecuto
r.cs:line 139
   at Microsoft.Data.Entity.SqlServer.SqlServerSequenceValueGenerator`1.GetNewLo
wValue() in C:\enlistments\Universe\EntityFramework\src\EntityFramework.SqlServe
r\SqlServerSequenceValueGenerator.cs:line 38
   at Microsoft.Data.Entity.ValueGeneration.HiLoValueGeneratorState.Next[TValue]
(Func`1 getNewLowValue) in C:\enlistments\Universe\EntityFramework\src\EntityFra
mework.Core\ValueGeneration\HiLoValueGeneratorState.cs:line 51
   at Microsoft.Data.Entity.ValueGeneration.HiLoValueGenerator`1.Next() in C:\en
listments\Universe\EntityFramework\src\EntityFramework.Core\ValueGeneration\HiLo
ValueGenerator.cs:line 25
   at Microsoft.Data.Entity.ValueGeneration.ValueGenerator`1.NextValue() in C:\e
nlistments\Universe\EntityFramework\src\EntityFramework.Core\ValueGeneration\Val
ueGenerator`.cs:line 10
   at Microsoft.Data.Entity.ValueGeneration.ValueGenerator.Next() in C:\enlistme
nts\Universe\EntityFramework\src\EntityFramework.Core\ValueGeneration\ValueGener
ator.cs:line 8
   at Microsoft.Data.Entity.ChangeTracking.Internal.ValueGenerationManager.Gener
ate(InternalEntityEntry entry) in C:\enlistments\Universe\EntityFramework\src\En
tityFramework.Core\ChangeTracking\Internal\ValueGenerationManager.cs:line 42
   at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntry.SetEntit
yState(EntityState entityState, Boolean acceptChanges) in C:\enlistments\Univers
e\EntityFramework\src\EntityFramework.Core\ChangeTracking\Internal\InternalEntit
yEntry.cs:line 103
   at Microsoft.Data.Entity.ChangeTracking.EntityEntry.set_State(EntityState val
ue) in C:\enlistments\Universe\EntityFramework\src\EntityFramework.Core\ChangeTr
acking\EntityEntry.cs:line 66
   at Microsoft.Data.Entity.DbContext.SetEntityState[TEntity](TEntity entity, En
tityState entityState) in C:\enlistments\Universe\EntityFramework\src\EntityFram
ework.Core\DbContext.cs:line 527
   at Microsoft.Data.Entity.DbContext.Add[TEntity](TEntity entity) in C:\enlistm
ents\Universe\EntityFramework\src\EntityFramework.Core\DbContext.cs:line 444
   at Transactions.Program.Main(String[] args) in C:\Users\ansvyryd\Documents\Vi
sual Studio 2015\Projects\Transactions\Transactions\Program.cs:line 20
```

```
using (var context = new MyContext())
{
    context.Add(new User());
    context.SaveChanges();
}

public class MyContext : DbContext
{
    public DbSet<User> Users { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);

        optionsBuilder.UseSqlServer(new SqlConnectionStringBuilder
        {
            DataSource = ".",
            InitialCatalog = "MyContext",
            IntegratedSecurity = true
        }.ToString());
    }
}

public class User
{
    public int Id { get; set; }
}
```

**Comment by AndriySvyryd** [comment]
Forgot that there is no automatic database initialization in EF7.
