### ISSUE TITLE
EF Core 3.0 Integration Tests Access Db From In Memory Provider

### ISSUE THREAD

**Issue by aherrick** [dotnet/efcore#18901]
I'm pulling the exact sample shown here:
https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.0

I'm trying to pull back out the Db Context inside a Test so I can add/delete some records.

```
[Fact]
        public async Task Post_DeleteAllMessagesHandler_ReturnsRedirectToRoot()
        {
 // this bombs
            var db = _factory.Services.GetService(typeof(ApplicationDbContext)) as ApplicationDbContext;
        }
```

Attached is the code sample:

[IntegrationTestsSample.zip](https://github.com/aspnet/EntityFrameworkCore/files/3847173/IntegrationTestsSample.zip)

**Comment by smitpatel** [comment]
@aherrick - Can you also describe what you is the error you are getting.

**Comment by aherrick** [comment]
picture is a 1000 words!
![11-14-2019 8-07-55 PM](https://user-images.githubusercontent.com/586671/68908898-a8c13580-071a-11ea-87f8-77086bbdbdbb.png)

**Comment by aherrick** [comment]
it'll work the same when when you run it

**Comment by ajcvickers** [comment]
@aherrick Please post the full stack trace.

**Comment by aherrick** [comment]
```
System.InvalidOperationException: Cannot resolve scoped service 'RazorPagesProject.Data.ApplicationDbContext' from root provider.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceProviderEngineCallback.OnResolve(Type serviceType, IServiceScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at RazorPagesProject.Tests.IndexPageTests.Post_DeleteAllMessagesHandler_ReturnsRedirectToRoot() in C:\Users\aherrick\Desktop\3.x\IntegrationTestsSample\IntegrationTestsSample\tests\RazorPagesProject.Tests\IntegrationTests\IndexPageTests.cs:line 47
```

**Comment by smitpatel** [comment]
From my understanding this error in DI happens when you do not create scope and try to resolve a scoped service from root. DbContext is generally scoped service, are you creating a proper service scope before calling `GetService`?

**Comment by aherrick** [comment]
not sure I follow - I'm calling the exact code posted above. Is there a different way to do it?

**Comment by smitpatel** [comment]
Follow https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.0#call-services-from-main to create service scope to get scoped services from DI.

**Comment by ajcvickers** [comment]
@aherrick If you are following the exact steps from a walkthrough and it does't work, then please file an issue on that walkthrough. There is a button on the bottom of the walkthrough page to do this.

The stack trace you posted does not contain any EF code. It looks to me, as @smitpatel said, that the D.I. container is not setup correctly or is being used correctly. How D.I. is intended to be used for this walkthrough is something that should at least initially be addressed by the author of the walkthrough.
