### ISSUE TITLE
Ef Core 3.0 Data Seeding does not work for 'object' type

### ISSUE THREAD

**Issue by danisss9** [dotnet/efcore#18907]
Hello,

I am trying to make a tool that reads seeds data from embedded resources into the DB. Everything was looking good except for when I use the HasData().

### Steps to reproduce

This is the code inside my Ef Core context class:

``` C#
partial void OnModelCreated(ModelBuilder modelBuilder) {
	var assembly = Assembly.GetExecutingAssembly();
	var types = assembly.GetTypes().Where(t => t.IsClass && t.Namespace == typeof(EfModel).Namespace);
	var filesToSeed = assembly.GetManifestResourceNames().Where(res => res.StartsWith("DataSeed.") && res.EndsWith(".json"));
	foreach (var fileName in filesToSeed)
	{
		using var reader = new StreamReader(assembly.GetManifestResourceStream(fileName), Encoding.UTF8);
		var seedData = JsonConvert.DeserializeObject<SeedData>(reader.ReadToEnd());
		var type = types.FirstOrDefault(t => t.Name == seedData.ModelTypeName);
		Console.WriteLine("Data seeded for type: " + seedData.ModelTypeName);
		Console.WriteLine(JsonConvert.SerializeObject(seedData.Data.First()));
		if (type == null)
			Console.Error.WriteLine("Could not find model type: " + seedData.ModelTypeName);
		else
			modelBuilder.Entity(type).HasData(seedData.Data);
	}
}
```

The classes needed for this code:

``` C#
private class SeedData
{
	public string ModelTypeName { get; set; }
	public IEnumerable<object> Data { get; set; }
}

private class Language
{
	public string Id { get; set; }
        public string Name { get; set; }
	public bool Enabled { get; set; }
}
```

The JSON file is in the "DataSeed" folder in project and has "Build Action: Embedded resource":

``` JavaScript
{
  "ModelTypeName":  "Language",
  "Data": [
    {
      "Id": "ps-AF",
      "Name": "Pashto (Afghanistan)",
      "Enabled": false
    },
    {
      "Id": "uz-Arab-AF",
      "Name": "Uzbek (Perso-Arabic, Afghanistan)",
      "Enabled": false
    },
    {
      "Id": "sv-AX",
      "Name": "Swedish (\u00C5land Islands)",
      "Enabled": false
    }
  ]
}

```

The Prints and Exception I get from executing "Add-Migration somename" on Package Console.

``` C#

Data seeded for type: Language
{"Id":"ps-AF","Name":"Pashto (Afghanistan)","Enabled":false}
System.InvalidOperationException: The seed entity for entity type 'Language' cannot be added because there was no value provided for the required property 'Id'.
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateData(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.SqlServer.Internal.SqlServerModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.ValidatingConvention.ProcessModelFinalized(IConventionModelBuilder modelBuilder, IConventionContext`1 context)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelFinalized(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelFinalized(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FinalizeModel()
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The seed entity for entity type 'Language' cannot be added because there was no value provided for the required property 'Id'.
```

### Further technical details

EF Core version: EF Core 3.0
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.3.7

**Comment by ajcvickers** [comment]
@danisss9 I have not been able to reproduce this--see my code below. Are you sure that your JSON deserialization code is working correctly? (I didn't attempt to debug that code since it doesn't involve EF.)

```C#
public class SeedData
{
    public string ModelTypeName { get; set; }
    public IEnumerable<object> Data { get; set; }
}

public class Language
{
    public string Id { get; set; }
    public string Name { get; set; }
    public bool Enabled { get; set; }
}

public class BloggingContext : DbContext
{
    private static readonly ILoggerFactory Logger = LoggerFactory.Create(x => x.AddConsole().SetMinimumLevel(LogLevel.Debug));

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        var seedData = new SeedData
        {
            Data = new List<Language>
            {
                new Language
                {
                    Id = "ps-AF",
                    Name = "Pashto (Afghanistan)",
                    Enabled = false
                },
                new Language
                {
                    Id = "uz-Arab-AF",
                    Name = "Uzbek (Perso-Arabic, Afghanistan)",
                    Enabled = false
                },
                new Language
                {
                    Id = "sv-AX",
                    Name = "Swedish (\u00C5land Islands)",
                    Enabled = false
                }
            } 
        };
        
        modelBuilder.Entity(typeof(Language)).HasData(seedData.Data);
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseLoggerFactory(Logger)
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
}

public class Program
{
    public static async Task Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();
        }

        using (var context = new BloggingContext())
        {
            var data = context.Set<Language>().ToList();
        }
    }
}
```

**Comment by danisss9** [comment]
@ajcvickers Thank you for looking into this. 

Indeed it was a serialize problem. The serializer was serializing to jObject instead of Object like I was expecting. So all I had to do was convert jObject to object.
