### ISSUE TITLE
dotnet ef migrations add throws exception

### ISSUE THREAD

**Issue by jozefizso** [dotnet/efcore#18932]
I have a ASP.NET Core 3 project with database context using EF Core 3 and SQL Server. When I add a new migration, it fails with **NullReferenceException** error.

### Steps to reproduce

``` C#
dotnet ef migrations add UpdateDatabase1 -c ApplicationDbContext
```

Verbose log: https://gist.github.com/jozefizso/b932c31b5b78f3558468ea605aadb505

Exception reported to console:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.OnAnnotationSet(String name, IConventionAnnotation annotation, IConventionAnnotation oldAnnotation)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ConventionAnnotatable.OnAnnotationSet(String name, Annotation annotation, Annotation oldAnnotation)
   at Microsoft.EntityFrameworkCore.Infrastructure.Annotatable.RemoveAnnotation(String name)
   at Microsoft.EntityFrameworkCore.Infrastructure.Annotatable.Microsoft.EntityFrameworkCore.Metadata.IMutableAnnotatable.RemoveAnnotation(String name)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.SnapshotModelProcessor.ProcessElement(IAnnotatable metadata, String version)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.SnapshotModelProcessor.ProcessElement(IEntityType entityType, String version)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.SnapshotModelProcessor.Process(IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.
```

### Further technical details

EF Core version: 3.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.3

**Comment by ajcvickers** [comment]
@jozefizso Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by jozefizso** [comment]
Unfortunately this is a private project.

**Comment by jozefizso** [comment]
WTF?

**Comment by ajcvickers** [comment]
@jozefizso Sorry, I read your message as meaning that you cannot post code that reproduces this issue. Did you mean something different?

**Comment by msrrajsan** [comment]
Ran into same issue when trying to add a migration. Any update on this?

**Comment by msrrajsan** [comment]
Ok, this worked for me.

Had to change the version in the ApplicationDbContextModelSnapshot

` modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")`

This was for a project which was previously in EF Core 1.1.5 version to EF Core 3.0.0

>
