### ISSUE TITLE
EFCore 2.2.6 DBQuery.FromSql.Select error (Object reference not set to an instance of an object)

### ISSUE THREAD

**Issue by vbond007** [dotnet/efcore#18933]
I made tests using BDQuery and had issues when mapping the result of a FromSql() request in a Select().
I have an error: Object reference not set to an instance of an object.
Here is an example:

DBContext class:

```
public class MyDbContext : DbContext
{
    public MyDbContext(DbContextOptions<MyDbContext> options)
        : base(options) { }

    public DbQuery<MyEntity> MyEntities { get; set; }
}
```
Here is the MyEntity class definition:

```
public class MyEntity
{
    public int Id { get; set;}
}
```
If in my code I make the following call, it works fine (_dbContext is of type MyDbContext of course):

```
var result = await _dbContext.MyEntities
   .FromSql("Exec MyStoredProc")
   .Select(s => new { s.Id })
   .ToListAsync()
```
The MyStoreProc returns a column with name Id.

But if I declare a class MyDTO like this :

```
public class MyDTO
{
    public int MyId { get; set;}
}
```
And then make a call like this :

```
var result = await _dbContext.MyEntities
   .FromSql("Exec MyStoredProc")
   .Select(s => new MyDTO {MyId = s.Id })
   .ToListAsync()
```
Then an exception is raised: Object reference not set to an instance of an object

If I rename the field `MyId ` by `Id` in the MyDTO Class definition, it works fine again. Any idea regarding this behavior? Why when the field name doesn't map with the SQL column name an error occurs?

Here is the stack trace when the exception occurs:
   at Microsoft.EntityFrameworkCore.Storage.TypedRelationalValueBufferFactoryFactory.CacheKey.<>c.<GetHashCode>b__6_0(Int32 t, TypeMaterializationInfo v)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at System.Collections.Generic.ObjectEqualityComparer`1.GetHashCode(T obj)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Query.Sql.Internal.FromSqlNonComposedQuerySqlGenerator.CreateValueBufferFactory(IRelationalValueBufferFactoryFactory relationalValueBufferFactoryFactory, DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Query.Internal.ShaperCommandContext.NotifyReaderCreated(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.<Aggregate_>d__6`3.MoveNext() in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Aggregate.cs:line 120
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ants.Services.CampaignService.<GetSmsStatusesAsync>d__14.MoveNext() in C:\Repositories\Professional Services\Gouv\ants\ants\Services\CampaignService.cs:line 546
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ants.Controllers.SmsController.<GetStatuses>d__5.MoveNext() in C:\Repositories\Professional Services\Gouv\ants\ants\Controllers\SmsController.cs:line 91

EF Core version: 2.2.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
.NET Core 2.2
Operating system: Windows 10
IDE: Visual Studio 2019 16.2.5

**Comment by ajcvickers** [comment]
@vbond007 EF does not compose SQL after execution of a stored procedure, so this would be evaluated on the client in EF Core 2.2.x. EF Core 3.0 doesn't support automatic client evaluation, so there is nothing to fix in 3.0. Instead be explicit about the client evaluation. For example:
```C#
var result = (await _dbContext.MyEntities
   .FromSql("Exec MyStoredProc")
   .ToListAsync())
   .Select(s => new MyDTO {MyId = s.Id })
   .ToList()
```
