### ISSUE TITLE
Max with 0 result give error Sequence contains no elements when using .Max() or .MaxAsync() 

### ISSUE THREAD

**Issue by Anderman** [dotnet/efcore#18955]
When the result of max is 0 a error message is generated

### Steps to reproduce

``` C#
_ctx.ChapterQuestions.Where(x => x.SurveyChapterId == surveyChapterId).Max(x => x.SequenceNumber+0) // produce error

_ctx.ChapterQuestions.Where(x => x.SurveyChapterId == surveyChapterId).Max(x => x.SequenceNumber+1) // is allowed
```
sql data
```
SELECT id,SequenceNumber FROM [ChapterQuestions] AS [c] WHERE [c].[SurveyChapterId] = 702
---
Id	SequenceNumber	
2293	0	
```
stack trace
```
dbug: Microsoft.EntityFrameworkCore.Query[10107]
      (queryContext) => Single<int>(new QueryingEnumerable<int>(
          (RelationalQueryContext)queryContext,
          SqlServerQuerySqlGeneratorFactory,
          SqlExpressionFactory,
          ParameterNameGeneratorFactory,
          Projection Mapping:
              EmptyProjectionMember -> 0
          SELECT MAX(c.SequenceNumber + 0)
          FROM ChapterQuestions AS c
          WHERE (c.SurveyChapterId == @__surveyChapterId_0) && NotEqual(@__surveyChapterId_0),
          Func<QueryContext, DbDataReader, ResultContext, int[], ResultCoordinator, int>,
          Survey.Entities.Context.SurveyContext,
          DiagnosticsLogger<Query>
      ))
dbug: Microsoft.EntityFrameworkCore.Database.Command[20103]
      Creating DbCommand for 'ExecuteReader'.
dbug: Microsoft.EntityFrameworkCore.Database.Command[20104]
      Created DbCommand for 'ExecuteReader' (0ms).
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20000]
      Opening connection to database 'survey' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20001]
      Opened connection to database 'survey' on server '(localdb)\mssqllocaldb'.
info: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[@__surveyChapterId_0='702'], CommandType='Text', CommandTimeout='30']
      SELECT MAX([c].[SequenceNumber] + 0)
      FROM [ChapterQuestions] AS [c]
      WHERE ([c].[SurveyChapterId] = @__surveyChapterId_0) AND @__surveyChapterId_0 IS NOT NULL
dbug: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (3ms) [Parameters=[@__surveyChapterId_0='702'], CommandType='Text', CommandTimeout='30']
      SELECT MAX([c].[SequenceNumber] + 0)
      FROM [ChapterQuestions] AS [c]
      WHERE ([c].[SurveyChapterId] = @__surveyChapterId_0) AND @__surveyChapterId_0 IS NOT NULL
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'Survey.Entities.Context.SurveyContext'.
      System.InvalidOperationException: Sequence contains no elements.
         at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
         at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
System.InvalidOperationException: Sequence contains no elements.
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
dbug: Microsoft.EntityFrameworkCore.Database.Command[20300]
      A data reader was disposed.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20002]
      Closing connection to database 'survey' on server '(localdb)\mssqllocaldb'.
dbug: Microsoft.EntityFrameworkCore.Database.Connection[20003]
      Closed connection to database 'survey' on server '(localdb)\mssqllocaldb'.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action Survey.WebApi.Survey.ManageSurveys.Controllers.SurveyManagementController.InsertChapterQuestion (Survey.WebApi) in 39.4262ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Survey.WebApi.Survey.ManageSurveys.Controllers.SurveyManagementController.InsertChapterQuestion (Survey.WebApi)'
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Sequence contains no elements.
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Max[TSource,TResult](IQueryable`1 source, Expression`1 selector)
   at Survey.WebApi.Survey.ManageSurveys.DbServices.ManageSurveyQuestionProvider.InsertChapterQuestion(Int32 surveyId, Int32 surveyChapterId, Int32 questionId) in C:\git\mijnzorgpeiler\Survey\Survey.WebApi\Survey\ManageSurveys\DbServices\ManageSurveyQuestionProvider.cs:line 50
   at Survey.WebApi.Survey.ManageSurveys.Services.ManageSurveyService.InsertChapterQuestion(Int32 surveyId, Int32 surveyChapterId, Int32 questionId) in C:\git\mijnzorgpeiler\Survey\Survey.WebApi\Survey\ManageSurveys\Services\ManageSurveyService.cs:line 69
   at Survey.WebApi.Survey.ManageSurveys.Controllers.SurveyManagementController.InsertChapterQuestion(Int32 surveyId, Int32 surveyChapterId, Int32 questionId) in C:\git\mijnzorgpeiler\Survey\Survey.WebApi\Survey\ManageSurveys\Controllers\SurveyManagementController.cs:line 59
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
```

### Further technical details

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.1)
Operating system:
IDE: (e.g. Visual Studio 2019 16.4)

**Comment by myesn** [comment]
May I ask when version 3.1.1 can be released, I also encountered the same problem.

**Comment by Pyrdacor** [comment]
I see this bug still in Microsoft.EntityFrameworkCore 5.0.5.

```cs
int itemId = dbContext.Items.Max(i => Convert.ToInt32(i.SomeIdAsString)) + 1;
```

If the whole table "Items" has null in the column "SomeIdAsString" (and there are rows), this will throw the mentioned exception. But `Convert.ToInt32` outputs a 0 if the string is null, so I would expect that the Max method would return just 0 in this case. The stack trace shows that a call to the Single method is involved which looks strange:

```
System.InvalidOperationException: Sequence contains no elements.
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Max[TSource,TResult](IQueryable`1 source, Expression`1 selector)
```

I consider this a bug or am I missing something here?

**Comment by Pyrdacor** [comment]
Why is this closed without any reply? And why is it assigned to the 3.1.1 milestone when it is obviously a problem in 5.0.5?

**Comment by ajcvickers** [comment]
Note from triage: the "Convert.ToInt32" is surprising in that null is not the same as zero, so converting null to zero is a from of data corruption. It's unlikely that this will be changed in the BCL, but it's not a behavior we believe makes sense to replicate in translated queries.

**Comment by Pyrdacor** [comment]
This is a well-documented behavior for Convert. The user knows what he can expect from the function's output. It is much more surprising that a query behaves  differently and even throws something which isn't understandable in this context.

**Comment by roji** [comment]
@Pyrdacor we have various cases where we don't match the .NET behavior - a good example is string equality, which on some databases is case-insensitive whereas it's case-sensitive in .NET. The team was unanimous that there's more danger in mimicking the (problematic) .NET behavior (data corruption) than there is in the current behavior.

As to this being understandable or not, that's quite subjective - it seems pretty clear to me that Max is saying it has no values. In any case, better an exception that the user can investigate in understand, than silent bad data because of an implicit conversion from null string to zero.

**Comment by Pyrdacor** [comment]
I get your point but calling the Max extension on a non-empty collection should not throw an exception which states that there are no elements. Null is often a valid value. Maybe you could at least throw something more specific. We spent hours to track the issue down because this looks totally valid in .NET.

I have to accept your decision but this is really dangerous imho. We are lucky to detect the behavior on a test system. If this would have been deployed on the production system that would have been really bad.
