### ISSUE TITLE
InvalidOperationException when trying to access one-to-many collection

### ISSUE THREAD

**Issue by MakiseKurisu** [dotnet/efcore#18968]
### Steps to reproduce
``` C#
using InvalidOperationException.Models;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace InvalidOperationException
{
    class Program
    {
        // Scaffold-DbContext "Data Source=localhost;Initial Catalog=InvalidOperationException;Integrated Security=SSPI;" Microsoft.EntityFrameworkCore.SqlServer -Force -OutputDir Models
        static void Main(string[] args)
        {
            var ob1 = new DbContextOptionsBuilder<InvalidOperationExceptionContext>();
            ob1.UseSqlServer(@"Data Source=localhost;Initial Catalog=InvalidOperationException;Integrated Security=SSPI;",
                opt => opt.EnableRetryOnFailure())
                .UseLazyLoadingProxies();

            using (var fc = new InvalidOperationExceptionContext(ob1.Options))
            {
                var test = fc.Customer.FirstOrDefault();
                foreach (var c in fc.Customer)
                {
                    var test2 = c.Order;
                }
            }
        }
    }
}
```

``` SQL
CREATE TABLE [dbo].[Customer]
(
	[Id] INT NOT NULL PRIMARY KEY
)
GO

CREATE TABLE [dbo].[Order]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[CustomerId] INT NOT NULL
)
GO

ALTER TABLE [dbo].[Order]  WITH CHECK ADD  CONSTRAINT [FK_Order_Customer] FOREIGN KEY([CustomerId])
REFERENCES [dbo].[Customer] ([Id])
ON UPDATE CASCADE
GO

INSERT INTO [dbo].[Customer] VALUES (1)
GO

INSERT INTO [dbo].[Order] VALUES (1, 1)
GO

INSERT INTO [dbo].[Order] VALUES (2, 1)
GO
```

```
Unhandled exception. System.InvalidOperationException: There is already an open DataReader associated with this Command which must be closed first.
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.ValidateConnectionForExecute(SqlCommand command)
   at Microsoft.Data.SqlClient.SqlConnection.ValidateConnectionForExecute(String method, SqlCommand command)
   at Microsoft.Data.SqlClient.SqlCommand.ValidateCommand(Boolean isAsync, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.Load[TSource](IQueryable`1 source)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.Load(INavigation navigation, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.NavigationEntry.Load()
   at Microsoft.EntityFrameworkCore.ChangeTracking.CollectionEntry.Load()
   at Microsoft.EntityFrameworkCore.Internal.LazyLoader.Load(Object entity, String navigationName)
   at Microsoft.EntityFrameworkCore.Proxies.Internal.LazyLoadingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.CustomerProxy.get_Order()
   at InvalidOperationException.Program.Main(String[] args) in Program.cs:line 22 -> var test2 = c.Order;
```
The program requires adding "MultipleActiveResultSets=true;" to the connection string to avoid this issue, which is unnecessary when using latest .NET Core 2.2 + latest EF Core 2.2.6 with the same code.

The first `var test` is for checking whether one-to-many mapping & lazy loading is working (which it is working). Removing that line didn't change the outcome.

This happens when I use a real SQL Server 2014 / latest 2019. Using LocalDB this behavior is not observed.

### Further technical details

EF Core version: 3.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer 3.0.0
Target framework: .NET Core 3.0
Operating system: Windows 10 1903
IDE: Visual Studio 2019 16.3.9
Database: Microsoft SQL Server 12.0.6293.0 & 15.0.2000.5

**Comment by ajcvickers** [comment]
@MakiseKurisu Yes, `MultipleActiveResultSets=true` is currently required for this to work with EF Core 3. Is there an issue with doing that?

**Comment by MakiseKurisu** [comment]
I just thought this was an unintended change as it breaks the old working code. If this is how the life will be then I'm fine with it. Any reason for this change?

**Comment by ajcvickers** [comment]
@MakiseKurisu Yes. The query code was extensively re-written for 3.0, which changed the underlying buffering mechanism. This is something we could consider bringing back.

**Comment by ajcvickers** [comment]
Note from triage: we don't currently plan to bring this back, but as always we could revisit this with more feedback.

**Comment by yeahe83** [comment]
it do waste me a week to find what happened... no docs, no upgrading tips
