### ISSUE TITLE
Working join table code in Core 2.2 causes need for migration

### ISSUE THREAD

**Issue by neilmulhy** [dotnet/efcore#18984]
I've migrated my web application from asp.net Core v2.2 to v3.0.

I have a couple of join tables off my ApplicationUser model:
```C#
ApplicationUser : IdentityUser<string>, IIdentityModel

public ICollection<UserProfileFoo1> UserProfileFoo1s { get; } = new List<UserProfileFoo1>();
public ICollection<UserProfileFoo2> UserProfileFoo2s { get; } = new List<UserProfileFoo2>();
```
The mappings are configured in the ApplicationIdentityDbContext:

```C#
protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

           builder.Entity<UserProfileFoo1>()
           .HasKey(t => new { t.UserProfileId, t.Foo1Key });

           builder.Entity<UserProfileFoo2>()
           .HasKey(t => new { t.UserProfileId, t.Foo2Key });
        }

```

When I try to view a page that uses join tables, it generates an error in the UI:

```
A database operation failed while processing the request.
SqlException: Invalid column name 'Foo1Key1'. Invalid column name 'Foo1Key1'. Invalid column name 'Foo2Key1'.
```

With the corresponding errors in the back end:

```C#
An exception occurred while iterating over the results of a query for context type 'DataIdentity.AccessLayer.ApplicationIdentityDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Foo1Key1'.
Invalid column name 'Foo1Key1'.
Invalid column name 'Foo2Key1'.
at Microsoft.Data.SqlClient.SqlCommand.<>c.b__164_0(Task`1 result)
at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:xxx
```

```C#
Failed executing DbCommand (2ms) [Parameters=[@__clUser_Identity_Name_0='?' (Size = 256)], CommandType='Text', CommandTimeout='30']
SELECT [t].[Id], [t].[AccessFailedCount], [t].[ConcurrencyStamp], [t].[DateRegistered], [t].[EmailAddress], [t].[EmailConfirmed], [t].[FirstName], [t].[LastName], [t].[LockoutEnabled], [t].[LockoutEnd], [t].[NormalizedEmail], [t].[NormalizedUserName], [t].[PasswordHash], [t].[PhoneNumber], [t].[PhoneNumberConfirmed], [t].[SecurityStamp], [t].[TwoFactorEnabled], [t].[UserName], [t0].[UserProfileId], [t0].[Foo1Key], [t0].[Foo1Key1], [t0].[Foo1Key0], [t0].[Foo1Name], [u0].[UserProfileId], [u0].[Foo2Key], [u0].[Foo2Key1]
FROM (
SELECT TOP(2) [a].[Id], [a].[AccessFailedCount], [a].[ConcurrencyStamp], [a].[DateRegistered], [a].[EmailAddress], [a].[EmailConfirmed], [a].[FirstName], [a].[LastName], [a].[LockoutEnabled], [a].[LockoutEnd], [a].[NormalizedEmail], [a].[NormalizedUserName], [a].[PasswordHash], [a].[PhoneNumber], [a].[PhoneNumberConfirmed], [a].[SecurityStamp], [a].[TwoFactorEnabled], [a].[UserName]
FROM [AspNetUsers] AS [a]
WHERE (([a].[NormalizedUserName] = @__clUser_Identity_Name_0) AND ([a].[NormalizedUserName] IS NOT NULL AND @__clUser_Identity_Name_0 IS NOT NULL)) OR ([a].[NormalizedUserName] IS NULL AND @__clUser_Identity_Name_0 IS NULL)
) AS [t]
LEFT JOIN (
SELECT [u].[UserProfileId], [u].[Foo1Key], [u].[Foo1Key1], [j].[Foo1Key] AS [Foo1Key0], [j].[Foo1Name]
FROM [UserProfileFoo1] AS [u]
LEFT JOIN [Foo1] AS [j] ON [u].[Foo1Key1] = [j].[Foo1Key]
) AS [t0] ON [t].[Id] = [t0].[UserProfileId]
LEFT JOIN [UserProfileFoo2] AS [u0] ON [t].[Id] = [u0].[UserProfileId]
ORDER BY [t].[Id], [t0].[UserProfileId], [t0].[Foo1Key], [u0].[UserProfileId], [u0].[Foo2Key]
```

When I try to create a new migration, it outputs the following which appears to be adding columns to the join tables to have a 1 suffix when they've been defined in the ApplicationIdentityContext without a 1 suffix:

```C#
			migrationBuilder.DropForeignKey(
                name: "FK_UserProfileFoo1_Foo1_Foo1Key",
                table: "UserProfileFoo1");

            migrationBuilder.DropForeignKey(
                name: "FK_UserProfileFoo2_Foo2_Foo2Key",
                table: "UserProfileFoo2");

            migrationBuilder.DropIndex(
                name: "IX_UserProfileFoo2_Foo2Key",
                table: "UserProfileFoo2");

            migrationBuilder.DropIndex(
                name: "IX_UserProfileFoo1_Foo1Key",
                table: "UserProfileFoo1");

            **migrationBuilder.AddColumn<string>(
                name: "Foo2Key1",
                table: "UserProfileFoo2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Foo1Key1",
                table: "UserProfileFoo1",
                nullable: true);**

            migrationBuilder.CreateIndex(
                name: "IX_UserProfileFoo2_Foo2Key1",
                table: "UserProfileFoo2",
                column: "Foo2Key1");

            migrationBuilder.CreateIndex(
                name: "IX_UserProfileFoo1_Foo1Key1",
                table: "UserProfileFoo1",
                column: "Foo1Key1");

            migrationBuilder.AddForeignKey(
                name: "FK_UserProfileFoo1_Foo1_Foo1Key1",
                table: "UserProfileFoo1",
                column: "Foo1Key1",
                principalTable: "Foo1",
                principalColumn: "Foo1Key",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_UserProfileFoo2_Foo2_Foo2Key1",
                table: "UserProfileFoo2",
                column: "Foo2Key1",
                principalTable: "Foo2",
                principalColumn: "Foo2Key",
                onDelete: ReferentialAction.Restrict);
```

Any ideas?

### Further technical details

EF Core version: v3.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10 Pro
IDE: Visual Studio Community 2019 16.3.9

**Comment by AndriySvyryd** [comment]
You are hitting https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#fkp
Call `.HasForeignKey(e => e.UserProfileId)`,  `.HasForeignKey(e => e.Foo1Key)`, etc. to configure the FKs

**Comment by neilmulhy** [comment]
Thank you @AndriySvyryd.

In case this may help anyone else, my OnModelCreating code ended up being:

```C#
protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            //Foo1 table
            builder.Entity<UserProfileFoo1>(upFoo1 =>
            {
            	upFoo1.HasKey(js => new { js.Foo1Key, js.UserProfileId });

            	upFoo1.HasOne(js => js.Foo1)
            				.WithMany(up => up.UserProfileFoo1s)
            				.HasForeignKey(js => js.Foo1Key)
            				.IsRequired();

            	upFoo1.HasOne(up => up.UserProfile)
            				.WithMany(js => js.UserProfileFoo1s)
            				.HasForeignKey(js => js.UserProfileId)
            				.IsRequired();
            });

            //Foo2 table
            builder.Entity<UserProfileFoo2>(upFoo2 =>
            {
            	upFoo2.HasKey(jt => new { jt.Foo2Key, jt.UserProfileId });

            	upFoo2.HasOne(jt => jt.Foo2)
            				.WithMany(up => up.UserProfileFoo2s)
            				.HasForeignKey(jt => jt.Foo2Key)
            				.IsRequired();

            	upFoo2.HasOne(up => up.UserProfile)
            				.WithMany(jt => jt.UserProfileFoo2s)
            				.HasForeignKey(jt => jt.UserProfileId)
            				.IsRequired();
            });
       }
```

Instead of:

```C#
protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

           builder.Entity<UserProfileFoo1>()
           .HasKey(t => new { t.UserProfileId, t.Foo1Key });

           builder.Entity<UserProfileFoo2>()
           .HasKey(t => new { t.UserProfileId, t.Foo2Key });
        }
```
