### ISSUE TITLE
Throwing exception when call command Add-Migration in NuGet Package Manager Console in Visual Studio

### ISSUE THREAD

**Issue by CoreDX9** [dotnet/efcore#18983]
EF Core 3.0.1
Microsoft.EntityFrameworkCore.Tools 3.0.1

Add-Migration command throw exception：
Object reference not set to an instance of an object.

### Steps to reproduce

[solution link](https://github.com/CoreDX9/IdentityServerDemo/tree/chonggou) 

download solution and call command in NuGet Package Manager Console in Visual Studio
```
Add-Migration InitialApplicationDbMigration -Context ApplicationDbContext -Project CoreDX.Application.DbMigration -StartupProject IdentityServer -OutputDir Application
```
or
```
Add-Migration InitialApplicationIdentityDbMigration -Context ApplicationIdentityDbContext -Project CoreDX.Application.DbMigration -StartupProject IdentityServer -OutputDir Identity
```

then console will print exception info

```
Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.0.1 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: MigrationsAssembly=CoreDX.Application.DbMigration 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.Literal(String value)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationOperationGenerator.Generate(CreateTableOperation operation, IndentedStringBuilder builder)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationOperationGenerator.Generate(String builderName, IReadOnlyList`1 operations, IndentedStringBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationsGenerator.GenerateMigration(String migrationNamespace, String migrationName, IReadOnlyList`1 upOperations, IReadOnlyList`1 downOperations)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.
```

### Further technical details

EF Core version:3.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: Core 3.0
Operating system: Windows 10 1809
IDE: Visual Studio 2019 16.3.9

**Comment by ajcvickers** [comment]
@CoreDX9 Looks like you're using EF Core three packages with ASP.NET Core 2.x packages. This is very unlikely to work; you'll need to update all your packages to be 3.0 versions.
