### ISSUE TITLE
Queries with SelectMany + aggregate can't be translated (regression)

### ISSUE THREAD

**Issue by bradmarder** [dotnet/efcore#19205]
Without the `(IEnumerable<Post>)`, this query works fine. The reason I include it is to replicate the exception I receive when decompiling the `PostCount` property with DelegateDecompiler. This worked fine in EFCore pre 3.0. 

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using DelegateDecompiler;
using DelegateDecompiler.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EFCoreBugs
{
    class Program
    {
        static async Task Main(string[] args)
        {
            using (var db = new TestDb())
            {
                await db.Database.EnsureDeletedAsync();
                await db.Database.EnsureCreatedAsync();
            }
            using (var db = new TestDb())
            {
                await db.Accounts
                    //.Select(x => x.PostCount)
                    .Select(x => new
                    {
                        PostCount = x.Blogs.SelectMany(y => (IEnumerable<Post>) y.Posts).Count()
                    })
                    .DecompileAsync()
                    .ToListAsync();
            }
        }
    }

    public class TestDb : DbContext
    {
        public DbSet<Account> Accounts { get; set; }
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Post> Posts { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var fact = LoggerFactory.Create(x => x.SetMinimumLevel(LogLevel.Information));
            optionsBuilder.UseLoggerFactory(fact);
            optionsBuilder.EnableDetailedErrors();
            optionsBuilder.EnableSensitiveDataLogging();
            optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=master;Database=bugtest;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False");
        }
    }

    public class Account
    {
        public int Id { get; set; }
        public virtual ICollection<Blog> Blogs { get; } = new HashSet<Blog>();

        [Computed]
        public virtual int PostCount =>
            Blogs
                .SelectMany(x => x.Posts)
                .Count();
    }
    public class Blog
    {
        public int Id { get; set; }
        public int AccountId { get; set; }

        public virtual ICollection<Post> Posts { get; } = new HashSet<Post>();
    }
    public class Post
    {
        public int Id { get; set; }
        public int BlogId { get; set; }
    }
}
```

```
Unhandled exception. System.InvalidOperationException: Processing of the LINQ expression 'y => (IEnumerable<Post>)y.Posts' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ProcessSelectMany(NavigationExpansionExpression source, LambdaExpression collectionSelector, LambdaExpression resultSelector)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitNew(NewExpression node)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.PendingSelectorExpandingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at lambda_method(Closure , IAsyncQueryProvider , Expression , CancellationToken )
   at DelegateDecompiler.EntityFrameworkCore.AsyncDecompiledQueryProviderBase.MethodCache`1.ExecuteAsync(IAsyncQueryProvider asyncQueryProvider, Expression expression, CancellationToken cancellationToken)
   at DelegateDecompiler.EntityFrameworkCore.AsyncDecompiledQueryProviderBase.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
```

**Comment by ajcvickers** [comment]
We discussed this again in triage. This seems to be a corner case resulting from code generated from another tool. Unless we get more feedback on the importance we are likely not going to fix this.
