### ISSUE TITLE
Interpolated string in orderby not working since upgrade

### ISSUE THREAD

**Issue by stap123** [dotnet/efcore#19292]
We're upgrading from 2.2 to 3.1 at the moment. When upgrading a simple query we're getting an error from a simple query and it seems like it's probably a bug.

I've narrowed it down to specifically be related to the projection and order by of a property to a new anonymous object. See below for the whole query.

This worked fine on 2.2 but on 3.1 throws the exception below.

```
var users = await _commonDbContext.Users
  .AsNoTracking()
  .Where(m =>
    _commonDbContext.UserRoles.Any(n => m.Id == n.UserId && n.Role.Name == UserRoleName.Staff)
  )
  .Select(m => new
  {
    Id = m.Id,
    Name = $"{m.Information.Forename} {m.Information.Surname}"
  })
  .OrderBy(m => m.Name)
  .ToListAsync();
```

Changing the Select portion to the below does make it work.

```
.Select(m => new
{
  Id = m.Id,
  Name = m.Information.Forename + " " + m.Information.Surname
})
.OrderBy(m => m.Name)
```

Changing the query to switch to client side eval also works like this.

```
.Select(m => new
{
  Id = m.Id,
  Name = $"{m.Information.Forename} {m.Information.Surname}"
})
.ToListAsync())
.OrderBy(m => m.Name)
.ToList()
```

Is that an intended behaviour or is it a bug? 

It's pretty annoying to have to change this all over our code base where interpolated strings are used so I just thought I'd ask?

----

```
System.InvalidOperationException: The LINQ expression 'DbSet<User>
    .Where(u => DbSet<UserRole>
        .Join(
            outer: DbSet<Role>,
            inner: u0 => EF.Property<Nullable<int>>(u0, "RoleId"),
            outerKeySelector: r => EF.Property<Nullable<int>>(r, "Id"),
            innerKeySelector: (o, i) => new TransparentIdentifier<UserRole, Role>(
                Outer = o,
                Inner = i
            ))
        .Any(u0 => u.Id == u0.Outer.UserId && u0.Inner.Name == "Staff"))
    .LeftJoin(
        outer: DbSet<UserInformation>,
        inner: u => EF.Property<Nullable<int>>(u, "Id"),
        outerKeySelector: u1 => EF.Property<Nullable<int>>(u1, "Id"),
        innerKeySelector: (o, i) => new TransparentIdentifier<User, UserInformation>(
            Outer = o,
            Inner = i
        ))
    .OrderBy(u => string.Format(
        format: "{0} {1}",
        arg0: u.Inner.Forename,
        arg1: u.Inner.Surname))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|8_0(ShapedQueryExpression translated, <>c__DisplayClass8_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
```

### Further technical details

EF Core version:3.1.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10 
IDE: Visual Studio 2019 16.4.1

**Comment by smitpatel** [comment]
While the interpolated string is written in projection, it is also being used in OrderBy afterwards. Hence it is OrderBy which involves client side evaluation which is not supported in EF Core 3.0
Either provide an ordering which can be translated to server or Use `AsEnumerable` before OrderBy to perform ordering on client side.
