### ISSUE TITLE
Value Conversion throws SqlException The conversion of a nvarchar data type to a datetime data type resulted in an out-of-range value

### ISSUE THREAD

**Issue by gojanpaolo** [dotnet/efcore#19341]
We have a legacy database with a `string` column that contains a year and month. We'd like to create a model for it but define `DateTime` property instead and use Value Conversion. 

The following sample code reproduces the issue (also attached is a [sample project](https://github.com/aspnet/EntityFrameworkCore/files/3975097/XUnitTestProject1.zip)):

```c#
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

void Run()
{
    var options = new DbContextOptionsBuilder()
        .UseSqlServer("server=(localdb)\\mssqllocaldb;database=db")
        .Options;

    using (var ctx = new LegacyContext(options))
    {
        ctx.Database.EnsureCreated();
        ctx.Add(new LegacyFoo { YearMonth = "202001" });
        ctx.SaveChanges();
    }

    using (var ctx = new NewContext(options))
    {
        ctx.Set<NewFoo>().Where(f => f.YearMonth > DateTime.Now).ToList();
    }
}

public class LegacyContext : DbContext
{
    public LegacyContext(DbContextOptions options) : base(options) { }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<LegacyFoo>(b =>
        {
            b.ToTable("Foo");
        });
    }
}

public class LegacyFoo
{
    public int Id { get; set; }
    public string YearMonth { get; set; }
}

public class NewContext : DbContext
{
    public NewContext(DbContextOptions options) : base(options) { }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<NewFoo>(b =>
        {
            b.ToTable("Foo");

            b.Property(f => f.YearMonth)
            .HasConversion(
                v => v.ToString("yyyyMM"),
                v => DateTime.ParseExact(v, "yyyyMM", default));
        });
    }
}

public class NewFoo
{
    public int Id { get; set; }
    public DateTime YearMonth { get; set; }
}
```

The generated sql statement is:

```sql
SELECT [f].[Id], [f].[YearMonth]
FROM [Foo] AS [f]
WHERE [f].[YearMonth] > GETDATE()
```

That code throws the following exception:

```c#
Microsoft.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=The conversion of a nvarchar data type to a datetime data type resulted in an out-of-range value.
  Source=Core Microsoft SqlClient Data Provider
  StackTrace:
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at Microsoft.Data.SqlClient.SqlDataReader.Read()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDataReader.Read()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

### Further technical details

EF Core version: 3.1.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Win 10 Enterprise 64 bit
IDE: Visual Studio 2019 16.3.5

**Comment by ajcvickers** [comment]
@gojanpaolo This requires #10434. We are going to discuss whether we can do any of this for the 5.0 release.
