### ISSUE TITLE
Unable to migration apply on SQL Azure

### ISSUE THREAD

**Issue by jsacapdev** [dotnet/efcore#1960]
On the local development server, do a:

dnx . ef migration add initial

When attempting a db publish locally, on a local SQL Server 2012 instance, the following command works OK.

dnx . ef migration apply

However, when attempting to do a publish to SQL Azure, the same command fails with the error:

System.Data.SqlClient.SqlException (0x80131904): Keyword or statement option 'sequence' is not supported in this version of SQL Server.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserS
tateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite
)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.Data.Entity.Relational.SqlStatementExecutor.<>c__DisplayClass7_0.<ExecuteNonQuery>b__0()
   at Microsoft.Data.Entity.Relational.SqlStatementExecutor.Execute(IRelationalConnection connection, Func1 action)
   at Microsoft.Data.Entity.Relational.SqlStatementExecutor.ExecuteNonQuery(IRelationalConnection connection, DbTransaction transaction, IEnumerable`1 sqlBatches)
   at Microsoft.Data.Entity.Relational.Migrations.Migrator.Execute(IEnumerable1 sqlBatches, Boolean ensureDatabase)
   at Microsoft.Data.Entity.Relational.Migrations.Migrator.ApplyMigrations(String targetMigration)
   at Microsoft.Data.Entity.Commands.MigrationTool.ApplyMigration(String migrationName, String contextTypeName)
   at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass10_0.<ApplyMigration>b__0()
   at Microsoft.Data.Entity.Commands.Program.ExecuteInDirectory(String startupProject, Func1 invoke)
   at Microsoft.Data.Entity.Commands.Program.ApplyMigration(String migration, String context, String startupProject)
   at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass7_2.<Main>b__8()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Data.Entity.Commands.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List1 args)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)
ClientConnectionId:20af395f-8d0d-491b-a7a4-81907242ae2c
Error Number:40517,State:1,Class:16

I am raising because I believe I was able to execute this command successfully on a previous EF build. Please close if this is not supported on SQL Azure.

**Comment by popcatalin81** [comment]
"Keyword or statement option 'sequence' is not supported in this version of SQL Server." For SQL Azure you need to use Identity for your key generation strategy: ".ForSqlServer().UseIdentity()"

This functional is a good example: 

https://github.com/aspnet/EntityFramework/blob/7f7045665f1ed9f42b346f1e0d71efca79c4a6fb/test/EntityFramework.SqlServer.FunctionalTests/MonsterFixupSqlServerTest.cs

**Comment by jsacapdev** [comment]
OK, so here is my (updated) dbcontext:

***
    public class RegistrationDbContext : DbContext
    {
        public DbSet<Course> Courses { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder options)
        {
            options.UseSqlServer(Startup.Configuration.Get("Data:DefaultConnection:ConnectionString"));
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            builder.Entity<Course>().Property(typeof(int), "Id").ForSqlServer().UseIdentity();
        }
    }
***
	
...and just for completness, here is my model:

***
    public class Course
    {
        public int Id { get; set; }
        [Required]
        [StringLength(100, MinimumLength = 5)]
        public string Name { get; set; }
        public int Credits { get; set; }
    }
***

...but when I attempt to run:

***
dnx . ef migration add initial
dnx . ef migration apply
***

...i still see the same error. Is my approach incorrect?

**Comment by jsacapdev** [comment]
UPDATE:

if i (manually) remove the following:

***
            migration.CreateSequence(
                name: "DefaultSequence",
                type: "bigint",
                startWith: 1L,
                incrementBy: 10);
***
				
...from the method:

***
			public override void Up(MigrationBuilder migration)
***
It now works. But I cant see anything in:

***
dnx . ef migration --help
***

...to stop the sequence generation. Might anyone know how the sequence in disabled when attempting to add the migration?

**Comment by bricelam** [comment]
Add the following to your OnModelCreating method.
```C#
modelBuilder.ForSqlServer().UseIdentity();
```

**Comment by jsacapdev** [comment]
resolved

**Comment by bricelam** [comment]
Re-opening. We need to revisit our decision to make sequences the default behavior given that they're not supported on SQL Azure.

**Comment by npnelson** [comment]
Although I couldn't find any documentation to support it, it appears that sequences are supported in the V12 version of SQL Azure which is now generally available.  

The following statements worked for me in SQL Azure V12, but not V11

```
create sequence mainseq as bigint start with 1 increment by 1

create table mytable (
    id      bigint not null constraint DF_mytblid default next value for mainseq,
    code    varchar(20) not null
)
```
I prefer sequences over identity.

**Comment by rowanmiller** [comment]
Tracking the decision to swap back to identity by default or not https://github.com/aspnet/EntityFramework/issues/2175

**Comment by iamasim** [comment]
HI #rowanmiller 
I've watched your tutorials please tell me also I'm also having the same problem migrations apply doesn't work for me as I'm using VS2015 Asp.net 5.0 
dnx ef

**Comment by rowanmiller** [comment]
Hey, this particular issue was about us using sequences by default - which are not supported on Azure. This has since been changed (we now use IDENTITY instead). Can you open a new issue with specific details about the issue you are seeing.
