### ISSUE TITLE
Query: query compilation error for query projecting collection_of_entities.Contains(null)

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#19702]
query:

```cs
context.Orders.Where(o => context.Orders.Where(o => o.CustomerID == "VINET")
                    .Contains(null)).ToList()
```

exception:

```
{"Expression of type 'Microsoft.EntityFrameworkCore.TestModels.Northwind.Order' cannot be used for parameter of type 'System.Nullable`1[System.Int32]' of method 'Boolean Contains[Nullable`1](System.Linq.IQueryable`1[System.Nullable`1[System.Int32]], System.Nullable`1[System.Int32])' (Parameter 'arg1')"}

   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0, Expression arg1)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.VisitContainsMethodCall(MethodCallExpression methodCallExpression) in D:\git\efcore\src\EFCore\Query\Internal\EntityEqualityRewritingExpressionVisitor.cs:line 503
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in D:\git\efcore\src\EFCore\Query\Internal\EntityEqualityRewritingExpressionVisitor.cs:line 305
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.RewriteAndVisitLambda(LambdaExpression lambda, EntityReferenceExpression source) in D:\git\efcore\src\EFCore\Query\Internal\EntityEqualityRewritingExpressionVisitor.cs:line 771
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in D:\git\efcore\src\EFCore\Query\Internal\EntityEqualityRewritingExpressionVisitor.cs:line 375
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.Rewrite(Expression expression) in D:\git\efcore\src\EFCore\Query\Internal\EntityEqualityRewritingExpressionVisitor.cs:line 52
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query) in D:\git\efcore\src\EFCore\Query\QueryTranslationPreprocessor.cs:line 38
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query) in D:\git\efcore\src\EFCore\Query\QueryCompilationContext.cs:line 74
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async) in D:\git\efcore\src\EFCore\Storage\Database.cs:line 71
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async) in D:\git\efcore\src\EFCore\Query\Internal\QueryCompiler.cs:line 112
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0() in D:\git\efcore\src\EFCore\Query\Internal\QueryCompiler.cs:line 96
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler) in D:\git\efcore\src\EFCore\Query\Internal\CompiledQueryCache.cs:line 84
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) in D:\git\efcore\src\EFCore\Query\Internal\CompiledQueryCache.cs:line 59
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query) in D:\git\efcore\src\EFCore\Query\Internal\QueryCompiler.cs:line 92
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression) in D:\git\efcore\src\EFCore\Query\Internal\EntityQueryProvider.cs:line 79
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator() in D:\git\efcore\src\EFCore\Query\Internal\EntityQueryable`.cs:line 95
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

**Comment by maumar** [comment]
@roji
