### ISSUE TITLE
NRE in shaper on untranslated indexer property

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#19727]
Did not investigate this all the way, but to reproduce: comment out SqlServerGeometryCollectionMethodTranslator in SqlServerNetTopologySuiteMethodCallTranslatorPlugin (which makes the indexer on geometry instances untranslatable), and then run SpatialQuerySqlServerGeometryTest.Item.

Stack trace:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext() in /home/roji/projects/efcore/src/EFCore.Relational/Query/Internal/QueryingEnumerable.cs:line 197
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.TestUtilities.QueryAsserter`1.AssertQuery[TResult](Func`2 actualQuery, Func`2 expectedQuery, Func`2 elementSorter, Action`2 elementAsserter, Boolean assertOrder, Int32 entryCount, Boolean async, String testMethodName) in /home/roji/projects/efcore/test/EFCore.Specification.Tests/TestUtilities/QueryAsserter.cs:line 91
   at Microsoft.EntityFrameworkCore.Query.SpatialQuerySqlServerGeometryTest.Item(Boolean async) in /home/roji/projects/efcore/test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeometryTest.cs:line 533
```

/cc @smitpatel

**Comment by smitpatel** [comment]
Client eval, I would call it expected behavior. We could special case "Item" and make it null safe but value of doing so is very low given it is in negative case only.

Similar NRE can develop in any code which is being evaluated on client side on parts of database coming from server. (Navigation access does not throw it since it is translated to a SqlExpression but unmapped property access over an entity which could be null can throw exception).

**Comment by roji** [comment]
Makes sense, feel free to close if you think we should just leave as-is.

**Comment by ajcvickers** [comment]
Consider doing some null propagation in some parts of the client projection.
Discuss with @smitpatel.

**Comment by smitpatel** [comment]
Please @ajcvickers

**Comment by ajcvickers** [comment]
@smitpatel Discuss with @roji and @maumar. :trollface:
