### ISSUE TITLE
SQL client tests fail on downlevel

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/efcore#1973]
Win 7 and win 2008, dev branch, both fail. Looks like the SQL client got broken again. This happened between the moment we branched for `beta4` release and now because these tests pass on the release branch.

https://aspnet-ci.cloudapp.net/viewLog.html?buildId=272&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win2008r2_Universe
https://aspnet-ci.cloudapp.net/viewLog.html?buildId=274&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win7_Universe

```
AsyncQuerySqlServerTest.Distinct_Count 

System.AggregateException : One or more errors occurred.
 ---- System.EntryPointNotFoundException : Unable to find an entry point named 'CreateSemaphore' in DLL 'api-ms-win-core-kernel32-legacy-l1-1-0.dll'.
 ---- The following constructor parameters did not have matching fixture data: NorthwindQuerySqlServerFixture fixture

 ----- Inner Stack Trace #1 (System.EntryPointNotFoundException) -----
   at Interop.mincore.CreateSemaphore(SECURITY_ATTRIBUTES lpSecurityAttributes, Int32 initialCount, Int32 maximumCount, String name)
    at System.Threading.Semaphore..ctor(Int32 initialCount, Int32 maximumCount, String name)
    at System.Data.ProviderBase.DbConnectionPool.PoolWaitHandles..ctor()
    at System.Data.ProviderBase.DbConnectionPool..ctor(DbConnectionFactory connectionFactory, DbConnectionPoolGroup connectionPoolGroup, DbConnectionPoolIdentity identity, DbConnectionPoolProviderInfo connectionPoolProviderInfo)
    at System.Data.ProviderBase.DbConnectionPoolGroup.GetConnectionPool(DbConnectionFactory connectionFactory)
    at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPool(DbConnection owningObject, DbConnectionPoolGroup connectionPoolGroup)
    at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
    at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
    at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
    at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
    at System.Data.SqlClient.SqlConnection.Open()
    at Microsoft.Data.Entity.SqlServer.FunctionalTests.SqlServerTestStore.CreateDatabaseIfNotExists(String name, String scriptPath)
    at Microsoft.Data.Entity.SqlServer.FunctionalTests.TestModels.SqlServerNorthwindContext.<>c.<GetSharedStore>b__4_0()
    at Microsoft.Data.Entity.FunctionalTests.TestStore.CreateShared(String name, Action initializeDatabase)
    at Microsoft.Data.Entity.SqlServer.FunctionalTests.SqlServerTestStore.CreateShared(Action initializeDatabase)
    at Microsoft.Data.Entity.SqlServer.FunctionalTests.SqlServerTestStore.GetOrCreateShared(String name, Action initializeDatabase)
    at Microsoft.Data.Entity.SqlServer.FunctionalTests.TestModels.SqlServerNorthwindContext.GetSharedStore()
    at Microsoft.Data.Entity.SqlServer.FunctionalTests.NorthwindQuerySqlServerFixture..ctor()
 ----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) ----- 
```

**Comment by divega** [comment]
@victorhurdugaci was this fixed?

**Comment by victorhurdugaci** [comment]
Yes, it seems to be fixed
