### ISSUE TITLE
Regression casting to base class

### ISSUE THREAD

**Issue by Levi--G** [dotnet/efcore#19746]
When migrating we noticed an issue with queries giving a Exception that worked before:
"'System.InvalidOperationException' in Microsoft.EntityFrameworkCore.Relational.dll
Additional information: EF.Property called with wrong property name."
The issue arises when selecting a base class of a entity regarless of its content.
This code works when downgrading to EF Core 2.2.6

### Steps to reproduce

``` C#
static void Main(string[] args)
        {
            TWAContext db = new TWAContext();
            db.Database.EnsureDeleted();
            db.Database.Migrate();
            db.Add(new B() { As = new List<A>() { new A() } });
            db.SaveChanges();
            var full = db.Bs
                .Select(b => new C() { ABase = b.As.FirstOrDefault() })
                .Where(c => c.ABase != null).ToList();
        }

        public class TWAContext : DbContext
        {
            public TWAContext():this(@"insert CS here") { }
            public TWAContext(string ConnectionString)
                : base(new DbContextOptionsBuilder().UseSqlServer(ConnectionString).Options)
            {
            }
            public virtual DbSet<A> As { get; set; }
            public virtual DbSet<B> Bs { get; set; }
        }
        public class A : ABase
        {
        }
        public class ABase
        {
            [Key]
            [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
            public long ID { get; set; }
            public B B { get; set; }
        }
        public class B
        {
            [Key]
            [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
            public long ID { get; set; }
            public List<A> As { get; set; }
        }
        public class C
        {
            public ABase ABase { get; set; }
        }
```
Stacktrace:
```
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateWhere(ShapedQueryExpression source, LambdaExpression predicate)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Test.Program.Main(String[] args) in D:\Projects\Test\Program.cs:line 28
```
### Further technical details

EF Core version: 3.1.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10 1703 (yes i know...)
IDE: Visual Studio 2019 16.4.3

**Comment by ajcvickers** [comment]
@maumar to take a look.

**Comment by maumar** [comment]
repros on current master.
Workaround: don't use Typed projection in the middle of the query, use anonymous type instead and only apply typed projection at the end:

```cs
var full = db.Bs
    .Select(b => new { ABase = b.As.FirstOrDefault() })
    .Where(x => x.ABase != null)
    .Select(x => new C { ABase = x.ABase })
    .ToList();

```

**Comment by smitpatel** [comment]
Using 5.0-preview7
Generated SQL 
```C#
      SELECT [t0].[ID], [t0].[BID]
      FROM [Bs] AS [b]
      LEFT JOIN (
          SELECT [t].[ID], [t].[BID]
          FROM (
              SELECT [a].[ID], [a].[BID], ROW_NUMBER() OVER(PARTITION BY [a].[BID] ORDER BY [a].[ID]) AS [row]
              FROM [As] AS [a]
          ) AS [t]
          WHERE [t].[row] <= 1
      ) AS [t0] ON [b].[ID] = [t0].[BID]
      WHERE (
          SELECT TOP(1) [a0].[ID]
          FROM [As] AS [a0]
          WHERE [b].[ID] = [a0].[BID]) IS NOT NULL
```
