### ISSUE TITLE
Chained options for GenerateProviderOptions() throws error

### ISSUE THREAD

**Issue by archanasoni** [dotnet/efcore#19780]
Hi, 

For DB2 servers, we have to generate chained or multiple provider option. For example:

```c#
optionsBuilder.UseDb2(connectionString,  p => { p.SetServerInfo(IBMDBServerType.AS400); p.UseRowNumberForPaging(); });
```

To achieve it, we implemented GenerateProviderOptions() method of  IProviderCodeGeneratorPlugin
Now if we implement method like:

```c#
 public override MethodCallCodeFragment GenerateProviderOptions()
           => new MethodCallCodeFragment(nameof(Db2DbContextOptionsBuilder.SetServerInfo),
                               Db2DatabaseModelFactory.serverType);
```

All works well, but when we make it cahined call. like below:

```c#
public override MethodCallCodeFragment GenerateProviderOptions()
            => new MethodCallCodeFragment(nameof(Db2DbContextOptionsBuilder.SetServerInfo),
                             Db2DatabaseModelFactory.serverType, new MethodCallCodeFragment(nameof(Db2DbContextOptionsBuilder.UseRowNumberForPaging)));
```

it compiles perfectly, but during generation of model we are getting error:

```
System.InvalidOperationException: The current CSharpHelper cannot scaffold literals of type 'Microsoft.EntityFrameworkCore.Design.MethodCallCodeFragment'. Configure your services to use one that can.**
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.UnknownLiteral(Object value) in C:\Users\asoni\Downloads\EntityFrameworkCore-3.1.0\EntityFrameworkCore-3.1.0\src\EFCore.Design\Design\Internal\CSharpHelper.cs:line 824
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.Fragment(MethodCallCodeFragment fragment) in C:\Users\asoni\Downloads\EntityFrameworkCore-3.1.0\EntityFrameworkCore-3.1.0\src\EFCore.Design\Design\Internal\CSharpHelper.cs:line 974
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.Fragment(NestedClosureCodeFragment fragment) in C:\Users\asoni\Downloads\EntityFrameworkCore-3.1.0\EntityFrameworkCore-3.1.0\src\EFCore.Design\Design\Internal\CSharpHelper.cs:line 986
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.<>c.<.cctor>b__47_12(CSharpHelper c, Object v) in C:\Users\asoni\Downloads\EntityFrameworkCore-3.1.0\EntityFrameworkCore-3.1.0\src\EFCore.Design\Design\Internal\CSharpHelper.cs:line 161
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.UnknownLiteral(Object value) in C:\Users\asoni\Downloads\EntityFrameworkCore-3.1.0\EntityFrameworkCore-3.1.0\src\EFCore.Design\Design\Internal\CSharpHelper.cs:line 792
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.Fragment(MethodCallCodeFragment fragment) in C:\Users\asoni\Downloads\EntityFrameworkCore-3.1.0\EntityFrameworkCore-3.1.0\src\EFCore.Design\Design\Internal\CSharpHelper.cs:line 974
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpDbContextGenerator.GenerateOnConfiguring(String connectionString, Boolean suppressConnectionStringWarning) in C:\Users\asoni\Downloads\EntityFrameworkCore-3.1.0\EntityFrameworkCore-3.1.0\src\EFCore.Design\Scaffolding\Internal\CSharpDbContextGenerator.cs:line 235
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpDbContextGenerator.GenerateClass(IModel model, String contextName, String connectionString, Boolean useDataAnnotations, Boolean suppressConnectionStringWarning) in C:\Users\asoni\Downloads\EntityFrameworkCore-3.1.0\EntityFrameworkCore-3.1.0\src\EFCore.Design\Scaffolding\Internal\CSharpDbContextGenerator.cs:line 132
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpDbContextGenerator.WriteCode(IModel model, String contextName, String connectionString, String contextNamespace, String modelNamespace, Boolean useDataAnnotations, Boolean suppressConnectionStringWarning) in C:\Users\asoni\Downloads\EntityFrameworkCore-3.1.0\EntityFrameworkCore-3.1.0\src\EFCore.Design\Scaffolding\Internal\CSharpDbContextGenerator.cs:line 94
   at IBM.EntityFrameworkCore.Scaffolding.Internal.Db2CSharpDbContextGenerator.WriteCode(IModel model, String contextName, String connectionString, String contextNamespace, String modelNamespace, Boolean useDataAnnotations, Boolean suppressConnectionStringWarning) in C:\DBCTSource\Arch_Core30_TolSup_3FebRevEng\CoreDrivers\src\IBM.EntityFrameworkCore\Scaffolding\Internal\Db2CSharpDbContextGenerator.cs:line 61
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpModelGenerator.GenerateModel(IModel model, ModelCodeGenerationOptions options) in C:\Users\asoni\Downloads\EntityFrameworkCore-3.1.0\EntityFrameworkCore-3.1.0\src\EFCore.Design\Scaffolding\Internal\CSharpModelGenerator.cs:line 79
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions) in C:\Users\asoni\Downloads\EntityFrameworkCore-3.1.0\EntityFrameworkCore-3.1.0\src\EFCore.Design\Scaffolding\Internal\ReverseEngineerScaffolder.cs:line 127
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames) in C:\Users\asoni\Downloads\EntityFrameworkCore-3.1.0\EntityFrameworkCore-3.1.0\src\EFCore.Design\Design\Internal\DatabaseOperations.cs:line 96
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames) in C:\Users\asoni\Downloads\EntityFrameworkCore-3.1.0\EntityFrameworkCore-3.1.0\src\EFCore.Design\Design\OperationExecutor.cs:line 491
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_1.<.ctor>b__0() in C:\Users\asoni\Downloads\EntityFrameworkCore-3.1.0\EntityFrameworkCore-3.1.0\src\EFCore.Design\Design\OperationExecutor.cs:line 468
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0() in C:\Users\asoni\Downloads\EntityFrameworkCore-3.1.0\EntityFrameworkCore-3.1.0\src\EFCore.Design\Design\OperationExecutor.cs:line 605
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action) in C:\Users\asoni\Downloads\EntityFrameworkCore-3.1.0\EntityFrameworkCore-3.1.0\src\EFCore.Design\Design\OperationExecutor.cs:line 588
The current CSharpHelper cannot scaffold literals of type 'Microsoft.EntityFrameworkCore.Design.MethodCallCodeFragment'. Configure your services to use one that can.
```

**Comment by roji** [comment]
You are very likely unintentionally calling the MethodCallCodeFragment constructor which accepts only arguments:

```c#
public MethodCallCodeFragment(string method, params object?[] arguments)
```

... and mistakenly passing in the chained call as a parameter, instead of calling the constructor overload which accepts a chained call:

```c#
public MethodCallCodeFragment(MethodInfo methodInfo, object?[] arguments, MethodCallCodeFragment chainedCall)
```

Specifying named parameters in the invocation should resolve this:

```c#
public override MethodCallCodeFragment GenerateProviderOptions()
    => new MethodCallCodeFragment(
        nameof(Db2DbContextOptionsBuilder.SetServerInfo),
        arguments: new object[] { Db2DatabaseModelFactory.serverType },
        chainedCall: new MethodCallCodeFragment(nameof(Db2DbContextOptionsBuilder.UseRowNumberForPaging)));
```

You can also use the Chain method instead, which makes things simpler. Note that you should also be calling base.GenerateProviderOptions, which takes care of plugins, so your GenerateProviderOptions can look at follows:

```c#
public override MethodCallCodeFragment GenerateProviderOptions()
{
    var providerOptions = base.GenerateProviderOptions();

    var chainedCall = new MethodCallCodeFragment(nameof(SqlServerDbContextOptionsBuilder.EnableRetryOnFailure), 3)
        .Chain(new MethodCallCodeFragment(nameof(SqlServerDbContextOptionsBuilder.CommandTimeout), 40));

    return providerOptions?.Chain(chainedCall) ?? chainedCall;
}
```

(finally, note that the constructors accepting them method name as a string have been obsoleted - you should pass in a MethodInfo instead).

Note for triage: as we've already obsoleted these APIs for 6.0 (to accept MethodInfo instead of string), we should consider not adding back the constructor overload that accepts a MethodCallCodeFragment - this is quite a pit of failure next to a `params object[]` parameter. The Chain instance method already seems more than sufficient.
