### ISSUE TITLE
Cast<>() from DateTime to Nullable<DateTime>: No coercion operator is defined between types 'System.Int32' and 'System.DateTime'

### ISSUE THREAD

**Issue by Kloizdena** [dotnet/efcore#19820]
I get an error (No coercion operator is defined ...) when trying to run the following query:

```c#
                var query = context.As.Select(a => new
                {
                    a.Id,
                    LastDate = a.Bs
                        .OrderByDescending(b => b.Id)
                        .Select(b => b.CreatedAt)
                        .Cast<DateTime?>()
                        .FirstOrDefault()
                });
```

I tried it with different types instead of `DateTime`. If I omit the Cast<> operator, or if I use `string`, the following SQL is generated, which is OK:
```sql
SELECT [a].[Id], (
    SELECT TOP(1) [b].[CreatedAt]
    FROM [Bs] AS [b]
    WHERE [a].[Id] = [b].[AId]
    ORDER BY [b].[Id] DESC) AS [LastDate]
FROM [As] AS [a]
```
But when I use a numeric type (int, byte, decimal, double) instead of `DateTime`, and Cast<> to the corresponding Nullable<T>, the following SQL is generated, which does not contain the CreatedAt column, only a constant `1` value:
```sql
SELECT [a].[Id], [t0].[c]
FROM [As] AS [a]
LEFT JOIN (
    SELECT [t].[c], [t].[Id], [t].[AId]
    FROM (
        SELECT 1 AS [c], [b].[Id], [b].[AId], ROW_NUMBER() OVER(PARTITION BY [b].[AId] ORDER BY [b].[Id] DESC) AS [row]
        FROM [Bs] AS [b]
    ) AS [t]
    WHERE [t].[row] <= 1
) AS [t0] ON [a].[Id] = [t0].[AId]
```

### Steps to reproduce

The following code produces the first error (No coercion operator ...). Replace `DateTime` with any numeric type to produce the second issue (CreatedAt column not generated in the query).

```c#
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;

namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {
            var options = new DbContextOptionsBuilder().UseSqlServer("Data Source=.;Initial Catalog=Test;Integrated Security=True").Options;
            using (var context = new MyContext(options))
            {
                var query = context.As.Select(a => new
                {
                    a.Id,
                    LastDate = a.Bs
                        .OrderByDescending(b => b.Id)
                        .Select(b => b.CreatedAt)
                        .Cast<DateTime?>()
                        .FirstOrDefault()
                });
                query.ToList();
            }
        }

        class MyContext : DbContext
        {
            public MyContext([NotNullAttribute] DbContextOptions options) : base(options)
            {
            }

            public DbSet<A> As { get; set; }
            public DbSet<B> Bs { get; set; }
        }

        class A
        {
            public int Id { get; set; }
            public ICollection<B> Bs { get; set; } = new List<B>();
        }

        class B
        {
            public int Id { get; set; }
            public DateTime CreatedAt { get; set; }
            public A A { get; set; }
        }
    }
}

```

Result:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=No coercion operator is defined between types 'System.Int32' and 'System.DateTime'.
  Source=System.Linq.Expressions
  StackTrace:
   at System.Linq.Expressions.Expression.GetUserDefinedCoercionOrThrow(ExpressionType coercionType, Expression expression, Type convertToType)
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type, MethodInfo method)
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.RelationalProjectionBindingRemovingExpressionVisitor.CreateGetValueExpression(ParameterExpression dbDataReader, Int32 index, Boolean nullable, RelationalTypeMapping typeMapping, Type clrType)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.RelationalProjectionBindingRemovingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.RelationalProjectionBindingRemovingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions(ExpressionVisitor visitor, BlockExpression block)
   at System.Linq.Expressions.ExpressionVisitor.VisitBlock(BlockExpression node)
   at System.Linq.Expressions.BlockExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.RelationalProjectionBindingRemovingExpressionVisitor.Visit(Expression node, IReadOnlyList`1& projectionColumns)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.VisitShapedQueryExpression(ShapedQueryExpression shapedQueryExpression)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Test.Program.Main(String[] args) in d:\src\EFBug\Test\Test\Program.cs:line 21


```

### Further technical details

EF Core version: 3.1.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10.0.18363.592
IDE: Visual Studio 2019 16.4.3

**Comment by maumar** [comment]
works on current master. We generate the following:

```sql
SELECT [a].[Id], (
    SELECT TOP(1) [b].[CreatedAt]
    FROM [Bs] AS [b]
    WHERE [a].[Id] = [b].[AId]
    ORDER BY [b].[Id] DESC) AS [LastDate]
FROM [As] AS [a]
```

**Comment by Kloizdena** [comment]
@maumar Are you sure you tried with the Cast<DateTime?>() operator? I'm still getting the same issue with EF Core v3.1.2 if I use Cast<>(). Or is this operator not supported?

**Comment by maumar** [comment]
@Kloizdena yes. I tried the exact repro you provided - works on current master branch. Also verified that it indeed fails on 3.1.2. 3.1.2 is essentially the same as 3.1.1. We only going to port some fixes into the next patch.

**Comment by Kloizdena** [comment]
@maumar OK, thanks for looking into it.
