### ISSUE TITLE
Using a Geography (NetTopologySuite) in an owned type causes a SQL error

### ISSUE THREAD

**Issue by jochenjonc** [dotnet/efcore#19907]
If an entity has an owned type that contains a property of type Geography (for example NetTopologySuite.Geometries.Point) it results in a query that does a UNION on that owned type but that isn't allowed in SQL Server. The following error is returned:

```
Msg 5335, Level 16, State 1, Line 1
The data type geography cannot be used as an operand to the UNION, INTERSECT or EXCEPT operators because it is not comparable.
 ```

I think the problem is related to #18299

### Steps to reproduce

I have the following entities and owned types:

``` C#
public class Contact : Entity
{
	protected Contact()
	{
		Location = new Location();
	}

	public string Name { get; set; }
	public Location Location { get; protected set; }
}

public class Location
{
	private Address _address = new Address();

	public Address Address
	{
		get => _address;
		set => _address = value ?? throw new ArgumentNullException(nameof(Address));
	}

	public Point Coordinates { get; set; }
}

public class Address
{
	public string Street { get; set; }
	public string Number { get; set; }
	public string ZipCode { get; set; }
	public string City { get; set; }
	public string Country { get; set; }
}
```

The EntityTypeConfiguration is as follows:

``` C#
public class ContactEntityTypeConfiguration : IEntityTypeConfiguration<Contact>
{
	public void Configure(EntityTypeBuilder<Contact> builder)
	{
		builder.Property(c => c.Id)
			.UseHiLo("ContactHiLoSequence");

		builder.Property(c => c.Name)
			.IsUnicode()
			.HasMaxLength(150);

		builder.OwnsOne(c => c.Location,  l =>
		{
			l.OwnsOne(la => la.Address, la =>
			{
				la.Property(a => a.Street).HasColumnName("Street");
				la.Property(a => a.Number).HasColumnName("Number");
				la.Property(a => a.ZipCode).HasColumnName("ZipCode");
				la.Property(a => a.City).HasColumnName("City");
				la.Property(a => a.Country).HasColumnName("Country");
			}).WithOwner();

			l.Property(lc => lc.Coordinates).HasColumnName("Coordinates");
		});
	}
}
```

When fetching the Contact entity in EF Core 3.1 I get the following SQL and as result the error mentioned above.

``` sql
SELECT [c].[Id], [c].[Name], [t2].[Id], [t2].[Coordinates], [t7].[Id], [t7].[City], [t7].[Country], [t7].[Number], [t7].[Street], [t7].[ZipCode]
FROM [Contact] AS [c]
LEFT JOIN (
    SELECT [t0].[Id], [t0].[Coordinates], [t1].[Id] AS [Id0]
    FROM (
        SELECT [c0].[Id], [c0].[Coordinates]
        FROM [Contact] AS [c0]
        WHERE [c0].[Coordinates] IS NOT NULL
        UNION
        SELECT [c1].[Id], [c1].[Coordinates]
        FROM [Contact] AS [c1]
        INNER JOIN (
            SELECT [c2].[Id], [c2].[City], [c2].[Country], [c2].[Number], [c2].[Street], [c2].[ZipCode]
            FROM [Contact] AS [c2]
            WHERE [c2].[ZipCode] IS NOT NULL OR ([c2].[Street] IS NOT NULL OR ([c2].[Number] IS NOT NULL OR ([c2].[Country] IS NOT NULL OR [c2].[City] IS NOT NULL)))
        ) AS [t] ON [c1].[Id] = [t].[Id]
    ) AS [t0]
    INNER JOIN (
        SELECT [c3].[Id], [c3].[Name]
        FROM [Contact] AS [c3]
        WHERE [c3].[Type] IN (N'Customer', N'Plant', N'Supplier')
    ) AS [t1] ON [t0].[Id] = [t1].[Id]
) AS [t2] ON [c].[Id] = [t2].[Id]
LEFT JOIN (
    SELECT [c4].[Id], [c4].[City], [c4].[Country], [c4].[Number], [c4].[Street], [c4].[ZipCode], [t6].[Id] AS [Id0], [t6].[Id0] AS [Id00]
    FROM [Contact] AS [c4]
    INNER JOIN (
        SELECT [t4].[Id], [t4].[Coordinates], [t5].[Id] AS [Id0]
        FROM (
            SELECT [c5].[Id], [c5].[Coordinates]
            FROM [Contact] AS [c5]
            WHERE [c5].[Coordinates] IS NOT NULL
            UNION
            SELECT [c6].[Id], [c6].[Coordinates]
            FROM [Contact] AS [c6]
            INNER JOIN (
                SELECT [c7].[Id], [c7].[City], [c7].[Country], [c7].[Number], [c7].[Street], [c7].[ZipCode]
                FROM [Contact] AS [c7]
                WHERE [c7].[ZipCode] IS NOT NULL OR ([c7].[Street] IS NOT NULL OR ([c7].[Number] IS NOT NULL OR ([c7].[Country] IS NOT NULL OR [c7].[City] IS NOT NULL)))
            ) AS [t3] ON [c6].[Id] = [t3].[Id]
        ) AS [t4]
        INNER JOIN (
            SELECT [c8].[Id], [c8].[Name]
            FROM [Contact] AS [c8]
            WHERE [c8].[Type] IN (N'Customer', N'Plant', N'Supplier')
        ) AS [t5] ON [t4].[Id] = [t5].[Id]
    ) AS [t6] ON [c4].[Id] = [t6].[Id]
    WHERE [c4].[ZipCode] IS NOT NULL OR ([c4].[Street] IS NOT NULL OR ([c4].[Number] IS NOT NULL OR ([c4].[Country] IS NOT NULL OR [c4].[City] IS NOT NULL)))
) AS [t7] ON [t2].[Id] = [t7].[Id]
WHERE [c].[Type] IN (N'Customer', N'Plant', N'Supplier')
```

If I do the same in EF Core 2.2, then I get the following query and a correct result:

``` sql
SELECT [c].[Id], [c].[Name], [t].[Id], [t].[Coordinates], [t0].[Id], [t0].[City], [t0].[Country], [t0].[Number], [t0].[Street], [t0].[ZipCode]
FROM [Contact] AS [c]
LEFT JOIN (
    SELECT [c.Location].*
    FROM [Contact] AS [c.Location]
) AS [t] ON [c].[Id] = [t].[Id]
LEFT JOIN (
    SELECT [c.Location.Address].*
    FROM [Contact] AS [c.Location.Address]
) AS [t0] ON [t].[Id] = [t0].[Id]
```

So the problem is the UNION that is being generated in EF Core 3.1 and a UNION is not possible for Geography types.

### Further technical details

EF Core version: 3.1.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.4

**Comment by ajcvickers** [comment]
@jochenjonc This looks like it has the same root cause as #18299. Can you please post the C# code that runs the query, so we can see what it looks like from the .NET side. Also, can you post the full stack trace.

**Comment by jochenjonc** [comment]
@ajcvickers below you can find the code I'm executing, just a simple ToListAsync on the DbSet (no filtering).

``` c#
context.Contacts..AsNoTracking().ToListAsync(cancellationToken);
```

This is the stack trace.

```
Microsoft.Data.SqlClient.SqlException (0x80131904): The data type geography cannot be used as an operand to the UNION, INTERSECT or EXCEPT operators because it is not comparable.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
```
