### ISSUE TITLE
SQLite RevEng: Error when minimal foreign key specified

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#19920]
``` sql
create table test (
    id integer primary key,
    parentId integer references test
);
```
```
InvalidOperationException: The data is NULL at ordinal 1. This method can't be called on NULL values. Check using IsDBNull before calling.
   at Microsoft.Data.Sqlite.SqliteValueReader.GetString(Int32 ordinal)
   at Microsoft.Data.Sqlite.SqliteDataReader.GetString(Int32 ordinal)
   at Microsoft.EntityFrameworkCore.Sqlite.Scaffolding.Internal.SqliteDatabaseModelFactory.GetForeignKeys(DbConnection connection, DatabaseTable table, IList`1 tables)+MoveNext()
   at Microsoft.EntityFrameworkCore.Sqlite.Scaffolding.Internal.SqliteDatabaseModelFactory.Create(DbConnection connection, DatabaseModelFactoryOptions options)
   at Microsoft.EntityFrameworkCore.Sqlite.Scaffolding.Internal.SqliteDatabaseModelFactory.Create(String connectionString, DatabaseModelFactoryOptions options)
```

EF Core version: 3.1.2

**Comment by bricelam** [comment]
Looks like it stems from the columns not being specified. This works:
```sql
parentId integer references test (id)
```
