### ISSUE TITLE
efcore and odata: the EDM instance of type [some-type] is missing the property [some-property]

### ISSUE THREAD

**Issue by noant** [dotnet/efcore#19927]
I use EF Core with OData in web api application and i found that if i have request to OData controller with expand of property [Country] the exception is thrown:
"The EDM instance of type '[OnboardingReadModel.CountryDto Nullable=True]' is missing the property 'id'"

Classes:
`
public abstract class CompanyDto
{
	public Guid Id { get; set; }
	public CountryDto Country { get; set; }	
	// Other properties
}

public class BuyerDto : CompanyDto
{
	// Properties
}
`

The expressions tree before controller responded looks like this:
`
EntityQueryable<BuyerDto>.Select(
    buyerDto => new SelectExpandBinder.SelectAllAndExpand<BuyerDto>
    {
        ModelID = TypedProperty,
        Instance = buyerDto,
        UseInstanceForProperties = true,
        Container = new PropertyContainer.SingleExpandedProperty<SelectExpandBinder.SelectAll<CountryDto>>
        {
            Name = "country",
            Value = new SelectExpandBinder.SelectAll<CountryDto>
            {
                ModelID = TypedProperty,
                Instance = (buyerDto as CompanyDto).Country,  // <------
                UseInstanceForProperties = true
            },
            IsNull = (buyerDto as CompanyDto).Country == null // <------
        }
    })
`

I thought the bug is in [(buyerDto as CompanyDto).Country] and i wrote code to modify expression tree before controller responded. After modification expression tree looks like this:

`
EntityQueryable<BuyerDto>.Select(
    buyerDto => new SelectExpandBinder.SelectAllAndExpand<BuyerDto>
    {
        ModelID = TypedProperty,
        Instance = buyerDto,
        UseInstanceForProperties = true,
        Container = new PropertyContainer.SingleExpandedProperty<SelectExpandBinder.SelectAll<CountryDto>>
        {
            Name = "country",
            Value = new SelectExpandBinder.SelectAll<CountryDto>
            {
                ModelID = TypedProperty,
                Instance = buyerDto.Country, // <------
                UseInstanceForProperties = true
            },
            IsNull = buyerDto.Country == null // <------
        }
    })
`
And it works fine!

I can attach mapping configurations and code that modifies the expression tree if necessary.
I tried to reproduce bug in efcore 2.2.6 and 3.1.1 and an exception is thrown in both cases.

Exception details:
`
System.InvalidOperationException: The EDM instance of type '[OnboardingReadModel.CountryDto Nullable=True]' is missing the property 'id'.
   at Microsoft.AspNet.OData.ResourceContext.GetPropertyValue(String propertyName)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.CreateStructuralProperty(IEdmStructuralProperty structuralProperty, ResourceContext resourceContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.CreateStructuralPropertyBag(SelectExpandNode selectExpandNode, ResourceContext resourceContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.CreateResource(SelectExpandNode selectExpandNode, ResourceContext resourceContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteResource(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteExpandedNavigationProperties(SelectExpandNode selectExpandNode, ResourceContext resourceContext, ODataWriter writer)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteResource(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSet(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.ODataOutputFormatterHelper.WriteToStream(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, IWebApiUrlHelper internaUrlHelper, IWebApiRequestMessage internalRequest, IWebApiHeaders internalRequestHeaders, Func`2 getODataMessageWrapper, Func`2 getEdmTypeSerializer, Func`2 getODataPayloadSerializer, Func`1 getODataSerializerContext)
   at Microsoft.AspNet.OData.Formatter.ODataOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Seedwork.UnitOfWork.ExceptionHandlerMiddleware.Invoke(HttpContext context) in C:\Projects\Stenn\src\v2\Seedwork\Seedwork.UnitOfWork\ExceptionHandlerMiddleware.cs:line 37
   at Seedwork.UnitOfWork.ExceptionHandlerMiddleware.Invoke(HttpContext context) in C:\Projects\Stenn\src\v2\Seedwork\Seedwork.UnitOfWork\ExceptionHandlerMiddleware.cs:line 69
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
`

EF Core version:3.1.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 2.2
Operating system:
IDE: Visual Studio 2019 16.4.2

**Comment by ajcvickers** [comment]
@noant It looks like OData is generating the query, and the exception here is coming from OData code. Is there something that EF can do differently here?

**Comment by noant** [comment]
@ajcvickers When i create query by myself, without odata, the result is already bad:
`var buyers = dbContext.Set<BuyerDto>().Select(
                    buyerDto => new
                    {
                        Instance = buyerDto,
                        UseInstanceForProperties = true,
                        Container = new
                        {
                            Name = "country",
                            Value = new
                            {
                                Instance = (buyerDto as CompanyDto).Country,  // <------
                                UseInstanceForProperties = true
                            },
                            IsNull = (buyerDto as CompanyDto).Country == null // <------
                        }
                    });
`
buyers[0].Container.Value.Instance must be not null, but it is null.
![image](https://user-images.githubusercontent.com/15931000/74918318-f7493480-53d9-11ea-924a-186095c4ceef.png)

But when i replace (buyerDto as CompanyDto) with buyerDto...:
`var buyers = dbContext.Set<BuyerDto>().Select(
                    buyerDto => new
                    {
                        Instance = buyerDto,
                        UseInstanceForProperties = true,
                        Container = new
                        {
                            Name = "country",
                            Value = new
                            {
                                Instance = buyerDto.Country,  // <------
                                UseInstanceForProperties = true
                            },
                            IsNull = buyerDto.Country == null // <------
                        }
                    });
`
result is ok, buyers[0].Container.Value.Instance is not null.
![image](https://user-images.githubusercontent.com/15931000/74918677-7a6a8a80-53da-11ea-9d85-9ee98061483a.png)

I think this is not odata bug.

**Comment by smitpatel** [comment]
@noant - Can you provide a full repro code, especially with seed data.

**Comment by smitpatel** [comment]
Scratch that.
Fixed in #19377.

What is happening is,
We did not unwrap 'as' operator. So the navigation was not expanded and remained as member access. We went through the same code during translation also which ended up as client eval (since it is top level projection). Now since there is no Include, when evaluating code on client the navigation was set to null hence it returned null.
When modifying the tree to do direct member access, it expands navigation and translate it to server correctly giving correct results.

Can you test out that it is working using nightly builds?

**Comment by Truetotosse** [comment]
Hello,
I got this issue repropduced when instance is patched by security rules from property to `Expression.Default(DesiredObject)`. Same happens with `Expression.Convert(Expression.Constant(null), typeof(DesiredObject))`, seems like these type of expressions are mishadled in this scenario in the same way, as Expression.TypeAs is.
