### ISSUE TITLE
PropertyValues.SetValues fails to convert boxed values

### ISSUE THREAD

**Issue by MigratoryCoconuts** [dotnet/efcore#19985]
When passing an `IDictionary<string, object>` into `PropertyValues.SetValues`, Entity Framework crashes when the boxed type doesn't exactly match the PropertyValue type. I would expect EF Core to support both unboxing of values and converting to the PropertValue type

### Steps to reproduce

Entity:
``` C#
public class Entity {
    public long EntityId { get; set; }
    public int SomeValue { get;set; }
}
```
Code:
``` C#
var entity = _entityContext.Entities.SingleOrDefault(x => x.EntityId == 0);
var newValues = JsonConvert.DeserializeObject<IDictionary<string, object>>("{\"SomeValue\"=13}");
_db.Entry(entity ).CurrentValues.SetValues(newValues);
```
As JSON Converters take a "best guess" approach when deserializing to objects, the boxed type of newValues["SomeValue"] is Int64, not Int32. Although in my case I am using Newtonsoft.Json, this issue is the same with System.Text.Json. This results in the following error stack trace:

``` None
System.InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.Int32'.
   at Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer`1.Equals(Object left, Object right)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.<>c__DisplayClass86_0.<ValuesEqualFunc>b__0(Object l, Object r)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean isMaterialization, Boolean setModified, Boolean isCascadeDelete, CurrentValueType valueType)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean isMaterialization, Boolean setModified, Boolean isCascadeDelete)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.set_Item(IPropertyBase propertyBase, Object value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.CurrentPropertyValues.SetValueInternal(IProperty property, Object value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntryPropertyValues.set_Item(IProperty property, Object value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.PropertyValues.SetValues(IDictionary`2 values)
```

### Further technical details

EF Core version: v3.1.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer v3.1.1
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.0

**Comment by ajcvickers** [comment]
Note for team: we could introduce conversions here, but we may end up truncating data if it doesn't fit after the conversion. We should discuss.

**Comment by ajcvickers** [comment]
@MigratoryCoconuts We discussed this, but we're reluctant to introduce conversions that could lose data. Is it not possible to have the JSON serializer generate objects of the type you need?

**Comment by MigratoryCoconuts** [comment]
hey, I ended up working around it with the following code:
``` CSharp
var entity = _entityContext.Entities.SingleOrDefault(x => x.EntityId == 0);
var newValues = JsonConvert.DeserializeObject<IDictionary<string, object>>("{\"SomeValue\"=13}");
var currentValues = _db.Entry(entity).CurrentValues;

foreach (var property in currentValues.Properties)
{
	if (newValues.ContainsKey(property.Name))
		currentValues[property] = Convert.ChangeType(newValues[property.Name], property.ClrType, System.Globalization.CultureInfo.InvariantCulture);
}
```
I'm posting it here in case anyone in the future has the same problem. 
As the JSON serializer was deserializing into an `IDictionary <string, object>`, I could not instruct it to generate specific types. I do not think there is an issue with data loss, as the database is the place where the data is actually stored - at the end of the day, data coming into the database that is longer than the database field is going to be truncated anyway

**Comment by ajcvickers** [comment]
> I do not think there is an issue with data loss, as the database is the place where the data is actually stored

Except that the dictionary may have been populated by data that has not come from the database, or has been manipulated since it was obtained.
