### ISSUE TITLE
Invalid SQL generated with nested .Sum() and .Count()

### ISSUE THREAD

**Issue by novsstation** [dotnet/efcore#20099]
The following SQL is generated by EF.

```sql
SELECT 
	COUNT(*) AS [I0], 
	SUM((SELECT SUM([r].[RejectedAmount]) 
		FROM [InspectionCase] AS [i]
		INNER JOIN [RejectedCase] AS [r] ON [i].[Id] = [r].[InspectionCaseId]
		WHERE [i0].[Id] = [i].[InspectionId])) AS [I1]
FROM [Inspection] AS [i0]

```

Steps to reproduce:
1) Create test database:
```sql
create table Inspection (
	Id int primary key identity(1, 1),
	Code nvarchar(max)
);

insert into Inspection (Code) values ('test1');
insert into Inspection (Code) values ('test2');
insert into Inspection (Code) values ('test3');
insert into Inspection (Code) values ('test4');
insert into Inspection (Code) values ('test5');


create table InspectionCase (
	Id int primary key identity(1, 1),
	InspectionId int
);

create table RejectedCase (
	Id int primary key identity(1, 1),
	RejectedAmount decimal(20, 6),
	InspectionCaseId int,
);


alter table InspectionCase
ADD CONSTRAINT FK_Inspection_InspectionId FOREIGN KEY (InspectionId)     
    REFERENCES [dbo].[Inspection] (Id)     
    ON DELETE CASCADE    
    ON UPDATE CASCADE 
	
alter table RejectedCase
ADD CONSTRAINT FK_RejectedCase_InspectionCaseId FOREIGN KEY (InspectionCaseId)     
    REFERENCES [dbo].[InspectionCase] (Id)     
    ON DELETE CASCADE    
    ON UPDATE CASCADE 	 

insert into InspectionCase (InspectionId) values (1);
insert into RejectedCase (InspectionCaseId, RejectedAmount) values (1, 10);
insert into RejectedCase (InspectionCaseId, RejectedAmount) values (1, 5);
```

2) Create entities:
```cs
    public class Inspection {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(35)]
        public string Code { get; set; }

        public ICollection<InspectionCase> Cases { get; set; }
    }

    public class InspectionCase {
        [Key]
        public int Id { get; set; }

        [Required]
        public int InspectionId { get; set; }
        public Inspection Inspection { get; set; }

        public ICollection<RejectedCase> RejectedCases { get; set; }
    }

    public class RejectedCase {
        [Key]
        public int Id { get; set; }

        [Required]
        public int InspectionCaseId { get; set; }
        public InspectionCase InspectionCase { get; set; }

        [Required]
        public decimal RejectedAmount { get; set; }
    }
```
3) Try to calculate summary statistics by this code:
```cs
            using (var context = new TestDbContext()) {
                var data = context.Inspections
                    .AsNoTracking()
                    .Select(i => new {
                        i.Id,
                        i.Code,
                        CaseCount = i.Cases.Count,
                        RejectedAmount = i.Cases.SelectMany(c => c.RejectedCases).Sum(r => r.RejectedAmount),
                    });

                var groupedData = data
                    .GroupBy(obj => 1)
                    .Select(g => new {
                        I0 = g.Count(),
                        I1 = g.Sum(obj => obj.RejectedAmount)
                    })
                    .ToArray();
            }
```

```
[11:56:19 ERR] Failed executing DbCommand (5ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT COUNT(*) AS [I0], SUM((
    SELECT SUM([r].[RejectedAmount])
    FROM [InspectionCases] AS [i]
    INNER JOIN [RejectedCases] AS [r] ON [i].[Id] = [r].[InspectionCaseId]
    WHERE [i0].[Id] = [i].[InspectionId])) AS [I1]
FROM [Inspections] AS [i0]
INNER JOIN [MedCompanyTypes] AS [m] ON [i0].[MedCompanyTypeId] = [m].[Id]
INNER JOIN [InspectionTypes] AS [i1] ON [i0].[InspectionTypeId] = [i1].[Id]
[11:56:19 DBG] Closing connection to database 'ExpertProJournal' on server '(localdb)\mssqllocaldb'.
[11:56:19 DBG] Closed connection to database 'ExpertProJournal' on server '(localdb)\mssqllocaldb'.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.2\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[11:56:19 ERR] An exception occurred while iterating over the results of a query for context type 'ExpertProJournal.db.ExpertProJournalDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot perform an aggregate function on an expression containing an aggregate or a subquery.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:1dd0c0d6-7110-4890-b390-ce09ba1e6794
Error Number:130,State:1,Class:15
```

I think it is more complex case or regression of
https://github.com/dotnet/efcore/issues/11922

### Further technical details
EF Core version: 3.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: win 10 x64
IDE: Visual Studio 2019

**Comment by ajcvickers** [comment]
@smitpatel to respond.

**Comment by smitpatel** [comment]
The exception is SqlServer limitation. There is no other translation possible for the given LINQ query. Even if we captured it, it would still be client eval exception. You would need to force explicit client eval using AsEnumerable or rewrite the query differently to get desired results.
