### ISSUE TITLE
Problem with inherited owned type

### ISSUE THREAD

**Issue by lenraven** [dotnet/efcore#20220]
I have a problem with mapping of a complex domain model.
The problem is the generated mapping of Owned type.
When I created a migration step, then there will be two compiler error in the code.

### Model what I want to map

``` C#
    public class Entity
    {
        public int Id { get; set; }
        public BookingInterval Interval { get; set; }
        public DateRange Range { get; set; }
    }

    public class DateRange
    {
        public DateTime From { get; set; }
        public DateTime To { get; set; }
    }

    public class BookingInterval : DateRange
    {
        public DateTime CheckIn { get; set; }
        public DateTime CheckOut { get; set; }
    }
```

### The Context file with mapping
``` C#
    public class POCContext : DbContext
    {
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var entityBuilder = modelBuilder.Entity<Entity>();
            entityBuilder.OwnsOne(p => p.Interval, ob =>
            {
                ob.Property(p => p.CheckIn).IsRequired();
                ob.Property(p => p.CheckOut).IsRequired();
                ob.Ignore(p => p.From);
                ob.Ignore(p => p.To);
            });
            entityBuilder.Ignore(p => p.Range);
            modelBuilder.Ignore<DateRange>();
            base.OnModelCreating(modelBuilder);
        }
    }
```

### The problem
When I call the Add-Migration command, then the following Snapshot will be generated.
``` C#
    [DbContext(typeof(POCContext))]
    partial class POCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCoreMigrationProblem1.Model.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Entity");
                });

            modelBuilder.Entity("EFCoreMigrationProblem1.Model.Entity", b =>
                {
                    b.OwnsOne("EFCoreMigrationProblem1.Model.BookingInterval", "Interval", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<DateTime>("CheckIn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("CheckOut")
                                .HasColumnType("datetime2");

                            b1.HasKey("EntityId");

                            b1.ToTable("Entity");

                            // The problem is here!
                            b1.HasDiscriminator();

                            b1.WithOwner()
                                .HasForeignKey("EntityId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
```
So the problem is that, the `b1.HasDiscriminator();` method case compiler error.
And same problem is in Designer file of migration step.

### Workaround
I found a workaround to this problem, but it is not fitting well with my domain model.
The model of workaround:
``` C#
    public class Entity
    {
        public int Id { get; set; }
        public BookingInterval Interval { get; set; }
        public DateRange Range { get; set; }
    }
    public class DateRangeBase
    {
        public DateTime From { get; set; }
        public DateTime To { get; set; }
    }
    public class DateRange : DateRangeBase
    {
        public DateTime From { get; set; }
        public DateTime To { get; set; }
    }
    public class BookingInterval : DateRangeBase
    {
        public DateTime CheckIn { get; set; }
        public DateTime CheckOut { get; set; }
    }
```

### Further technical details

EF Core version: 3.1.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: All traget
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.5

**Comment by ajcvickers** [comment]
Note for team: This still repros even when both types are mapped as owned entities and nothing is ignored in the model.

**Comment by lenraven** [comment]
@ajcvickers Yes, the mapping, what I created, do it.

But I checked it again, and the problem will be occurred, only when the DateRange, and the BookingInterval are on same Entity and not depends on it is ignored or not.

The following model will **NOT** occur the problem:
```
    public class Entity1
    {
        public int Id { get; set; }
        public BookingInterval Interval { get; set; }
    }

    public class Entity2
    {
        public int Id { get; set; }
        public DateRange Range { get; set; }
    }

    public class POCContext : DbContext
    {
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var entityBuilder1 = modelBuilder.Entity<Entity1>();
            entityBuilder1.OwnsOne(p => p.Interval, ob =>
            {
                ob.Property(p => p.CheckIn).IsRequired();
                ob.Property(p => p.CheckOut).IsRequired();
                ob.Ignore(p => p.From);
                ob.Ignore(p => p.To);
            });
           var entityBuilder2 = modelBuilder.Entity<Entity2>();
            entityBuilder2.OwnsOne(p => p.Range, ob =>
            {
                ob.Property(p => p.From).IsRequired();
                ob.Property(p => p.From).IsRequired();
            });
            base.OnModelCreating(modelBuilder);
        }
    }
```

**Comment by ajcvickers** [comment]
@lenraven Thanks for the additional info.

@bricelam @AndriySvyryd Tried this on recent daily build and it now throws when adding the migration:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.Literal(String value)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateEntityTypeAnnotations(String builderName, IEntityType entityType, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateEntityType(String builderName, IEntityType entityType, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateOwnedType(String builderName, IForeignKey ownership, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateOwnedTypes(String builderName, IEnumerable`1 ownerships, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateRelationships(String builderName, IEntityType entityType, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateEntityTypeRelationships(String builderName, IEntityType entityType, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateEntityTypes(String builderName, IReadOnlyList`1 entityTypes, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.Generate(String builderName, IModel model, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationsGenerator.GenerateMetadata(String migrationNamespace, Type contextType, String migrationName, String migrationId, IModel targetModel)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

**Comment by AndriySvyryd** [comment]
@lenraven Try adding this line as a workaround:
```C#
            entityBuilder.OwnsOne(p => p.Interval, ob =>
            {
                ob.GetInfrastructure().HasNoDeclaredDiscriminator(ConfigurationSource.Explicit);
            });
```

**Comment by lenraven** [comment]
@AndriySvyryd Unfortunately this solution did not solve the problem.

**Comment by AndriySvyryd** [comment]
Possibly a symptom of https://github.com/dotnet/efcore/issues/19311
