### ISSUE TITLE
Linq queries not working...

### ISSUE THREAD

**Issue by pauldalyii** [dotnet/efcore#2023]
I'm currently using:
- 7.0.0-beta5-12927 nuget package for EntityFramework.Core and
- 2.0.0-alpha-003 nuget package for Remotion.Linq
  from https://www.myget.org/F/aspnetvnext/.

I started getting the following exception on all Linq queries within the past week...  

System.MissingMethodException was unhandled by user code
  HResult=-2146233069
  Message=Method not found: 'Remotion.Linq.Parsing.Structure.NodeTypeProviders.MethodInfoBasedNodeTypeRegistry Remotion.Linq.Parsing.Structure.NodeTypeProviders.MethodInfoBasedNodeTypeRegistry.CreateFromTypes(System.Collections.Generic.IEnumerable`1<System.Type>)'.
  Source=EntityFramework.Core
  StackTrace:
       at Microsoft.Data.Entity.Query.CompiledQueryCache.CreateNodeTypeProvider()
       at Microsoft.Data.Entity.Query.CompiledQueryCache.CreateQueryParser()
       at Microsoft.Data.Entity.Query.CompiledQueryCache.<>c__4`1.<Execute>b__4_0(Expression q, IDataStore ds)
       at Microsoft.Data.Entity.Query.CompiledQueryCache.<>c__DisplayClass7_0.<GetOrAdd>b__0(ICacheSetContext c)
       at Microsoft.Framework.Caching.Memory.CacheExtensions.<>c__DisplayClass7_0`1.<Set>b__0(ICacheSetContext context)
       at Microsoft.Framework.Caching.Memory.MemoryCache.Set(String key, IEntryLink link, Object state, Func`2 create)
       at Microsoft.Framework.Caching.Memory.CacheExtensions.Set(IMemoryCache cache, String key, Object state, Func`2 create)
       at Microsoft.Framework.Caching.Memory.CacheExtensions.Set[T](IMemoryCache cache, String key, Object state, Func`2 create)
       at Microsoft.Framework.Caching.Memory.CacheExtensions.GetOrSet[T](IMemoryCache cache, String key, Object state, Func`2 create)
       at Microsoft.Data.Entity.Query.CompiledQueryCache.GetOrAdd(Expression query, QueryContext queryContext, IDataStore dataStore, Boolean isAsync, Func`3 compiler)
       at Microsoft.Data.Entity.Query.CompiledQueryCache.Execute[TResult](Expression query, IDataStore dataStore, QueryContext queryContext)
       at Microsoft.Data.Entity.Query.EntityQueryProvider.Execute[TResult](Expression expression)
       at Remotion.Linq.QueryableBase`1.GetEnumerator()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)...

Not sure if this is related to #1617

**Comment by MichaelKetting** [comment]
Hi Paul!

Thanks for mentioning the versions :) EntityFramework is still linked against Remotion.Linq 2.0.0-alpha-002. There are some API changes in alpha-3, so upgrading to the next alpha isn't possible on the consumer side of things.

Is there a specific reason you updated your project to the latest alpha of Remotion.Linq?

Best regards, Michael

**Comment by paul-daly** [comment]
Interesting.  Some of my projects reference 2.0.0-alpha-003 and others 2.0.0-alpha-002.  Not exactly sure how I got in this state.  I'll put everything back to 002 now and verify.

Thank you!

**Comment by paul-daly** [comment]
Thanks again Michael... that worked.

**Comment by divega** [comment]
@MichaelKetting Thanks for helping! Would you recommend upgrading EF7 to use alpha3 now or waiting for another milestone? cc @anpete

**Comment by MichaelKetting** [comment]
@divega  You're welcome! Don't think in apha-3 is anything you guys have actually been waiting for so there's no benefit in an immediate upgrade and I'd recommend waiting a bit longer till alpha-4 is done. Don't want to highjack the thread, so the ideas for alpha 4 can be found on our mailing list (https://groups.google.com/d/msg/re-motion-users/7S_39cM0de0/oM_Zz7VHlBgJ) 

Best regards, Michael

cc@anpete

**Comment by julielerman** [comment]
I'm having this problem with the beta4 from nuget. Thanks to this thread, I noticed that in updating an older project from beta3 to beta4, I ended up with the alpha3 of remotion linq. I've spent about the last hour trying to change the version of remotion linq via nuget and have had nothing but problems. What version should I target? The stable 1.15.15? An early pre-release.

**Comment by julielerman** [comment]
I finally got this resolved. I needed to revert to 2.0.0-alpha.002. That installed quickly (rather than hanging for eons when I targetted the stable version) and my linq queries are working.
So the working combo is EF7 beta 4 from nuget using Remotion.LINQ alpha002 from nuget.
