### ISSUE TITLE
System.FormatException: The input is not a valid Base-64 string as it containUnhandled exception

### ISSUE THREAD

**Issue by archanasoni** [dotnet/efcore#20297]
Hi,
We are working to have support for Core 3.1 with IBM Entity Framework Core provider.
With Core 3.1 we are facing strange behavior for 2 scenarios:
Scenario#1: We have table with 2 column:

```sql
CREATE TABLE BYTETAB.DB2ADMIN2 (
          ID int NOT NULL,
          BYTECOL char(255) for bit data,
          CONSTRAINT PK_DB2ADMIN2 PRIMARY KEY (ID)
      );
```
Model Classes are:
```C#
public class BYTETAB
    {
        public int ID { get; set; }

        public byte[] BYTECOL { get; set; }
    }
```
Configuration in context class:
```C#
 protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<BYTETAB>().ToTable("DB2ADMIN2", "BYTETAB");
            modelBuilder.Entity<BYTETAB>(e =>
            {
                e.HasKey(i => i.ID);
                e.Property(i => i.ID).ValueGeneratedNever();
               e.Property(i => i.BYTECOL)
                .HasColumnType("char(255) for bit data");
            });
        }
```
Now from our program.cs we are trying to insert 
1 record
```C#
 int key = 2;
            Console.WriteLine("Hello World!");
            BYTETAB t = new BYTETAB
            {
                ID=key,
                BYTECOL = new byte[] { 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 1, 2, 3, 4, 5, 6, 7, 8 },
                //BYTECOL = new byte[] { 97, 98 }                
            };

            var context = new MyContext();
            context.BYTETABs.Add(t);
            context.SaveChanges();
            Console.WriteLine("Record inserted");
```

Next step is to delete record:

```C#
var context1 = new MyContext();
            var entity1 = context1.Set<BYTETAB>().Single(e => e.ID == key);
            context1.BYTETABs.Remove(entity1);

            context1.SaveChanges();

            Console.WriteLine("record deleted");
```

Here we get error:
```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (55ms) [Parameters=[@__key_0='?' (Size = 4) (DbType = Int32)], CommandType='Text', CommandTimeout='30']
      SELECT d.ID, d.BYTECOL
      FROM BYTETAB.DB2ADMIN2 AS d
      WHERE d.ID = @__key_0 FETCH FIRST 2 ROWS ONLY
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'ByteDataIssueWithAlpha1.MyContext'.
      System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
         at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
         at System.Convert.FromBase64String(String s)
         at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64StrUnhandled exception. ing(String s)
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Single[TSource](IQueryable`1 source, Expression`1 predicate)
   at ByteDataIssueWithAlpha1.Program.Main(String[] args) in C:\Users\asoni\source\repos\ByteDataIssueWithAlpha1\ByteDataIssueWithAlpha1\Program.cs:line 37
```
Our Observations:
1. If we create column with char(254) for bit data it works perfectly fine.
```sql
CREATE TABLE BYTETAB.DB2ADMIN2 (
          ID int NOT NULL,
          BYTECOL char(254) for bit data,
          CONSTRAINT PK_DB2ADMIN2 PRIMARY KEY (ID)
      );
```

2. If perform insert and delete using single or same context we don't see this issue. Even after suing length of char(255) for bit data

Scenario#2: In this scenario we have table with varchar(255) for bit data. For example:
```sql
CREATE TABLE BYTETAB.DB2ADMIN2 (
          ID int NOT NULL,
          BYTECOL varchar(255) for bit data,
          CONSTRAINT PK_DB2ADMIN2 PRIMARY KEY (ID)
      );
```
Model Classes are:

```C#
public class BYTETAB
    {
        public int ID { get; set; }

        public byte[] BYTECOL { get; set; }
    }
```
Configuration in context class:
```C#
 protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<BYTETAB>().ToTable("DB2ADMIN2", "BYTETAB");
            modelBuilder.Entity<BYTETAB>(e =>
            {
                e.HasKey(i => i.ID);
                e.Property(i => i.ID).ValueGeneratedNever();
               e.Property(i => i.BYTECOL)
                .HasColumnType("varchar(255) for bit data");
            });
        }
```
Now from our program.cs we are trying to insert 
1 record
```C#
 int key = 2;
            Console.WriteLine("Hello World!");
            BYTETAB t = new BYTETAB
            {
                ID=key,                
                BYTECOL = new byte[] { 97, 98, 99 }                
            };

            var context = new MyContext();
            context.BYTETABs.Add(t);
            context.SaveChanges();
            Console.WriteLine("Record inserted");
```
Next step is to delete record:
```C#
var context1 = new MyContext();
            var entity1 = context1.Set<BYTETAB>().Single(e => e.ID == key);
            context1.BYTETABs.Remove(entity1);

            context1.SaveChanges();

            Console.WriteLine("record deleted");
```
Here we get error:
```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (57ms) [Parameters=[@__key_0='?' (Size = 4) (DbType = Int32)], CommandType='Text', CommandTimeout='30']
      SELECT d.ID, d.BYTECOL
      FROM BYTETAB.DB2ADMIN2 AS d
      WHERE d.ID = @__key_0 FETCH FIRST 2 ROWS ONLY
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'ByteDataIssueWithAlpha1.MyContext'.
      System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
         at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
         at System.Convert.FromBase64String(String s)
         at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
Unhandled exception. System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Single[TSource](IQueryable`1 source, Expression`1 predicate)
   at ByteDataIssueWithAlpha1.Program.Main(String[] args) in C:\Users\asoni\source\repos\ByteDataIssueWithAlpha1\ByteDataIssueWithAlpha1\Program.cs:line 37
```

Our Observations:
1. IF input is reduced to 2 digit For example:
  `BYTECOL = new byte[] { 97, 98 }`     
It works.
2.  If perform insert and delete using single or same context we don't see this issue.

So far these worked without any issue only from 3.1 on words we are facing it. Have no clue why based on length of column and input it has different behavior.  And in same context things works smoothly.

Would you please suggest,guide what is wrong here ?

Thanks,
Archana

**Comment by ajcvickers** [comment]
@archanasoni This looks like an issue with type mapping, but it's hard to be sure without having the code. Can you share you type mapper implementation?

**Comment by archanasoni** [comment]
Thanks @ajcvickers  for looking into the issue.. it's really hard for us also to know the real cause..
Our type mapping is same as Core 2.1 except here n there minor changes..
code first, scaffolding works perfectly. Even char(254) for bit data works.. the issue is with char(255) for bit data..
char (..) for bit data gets mapped to byteArray and insertion works perfectly. Only for delete when we select record using different context it has issue.

**Comment by archanasoni** [comment]
Finally we figured out issue is length is coming inbetween, that is char(255) for bit data
if specify length using HasMaxLength, mapping works perfectly.
Then we identified 3.1 has change in this area and after implementing ParseStoreTypeName(..) our issue is resolved. Thanks for the hint..
