### ISSUE TITLE
EFCore 3.1, CodeFirst- DbUpdateException "INSERT statement conflicted with the FOREIGN KEY constraint"

### ISSUE THREAD

**Issue by shvmgpt116** [dotnet/efcore#20346]
I am trying to run a simple code first test application that is trying to create the tables and then insert some data into it.
### Class Definitions
Here are the definitions of the class.

```C#
public class Barcode
  {
    public byte[] Code { get; set; }
    public int ProductId { get; set; }
    public virtual Product Product { get; set; }
    public virtual BarcodeDetail Detail { get; set; }
  }
public class BarcodeDetail
  {
    public byte[] Code { get; set; }
  }
public class Product
  {
    public int ProductId { get; set; }
    public string Description { get; set; }
    public virtual ProductDetail Detail { get; set; }
    public virtual ICollection<Barcode> Barcodes { get; set; }
  }
public class ProductDetail
  {
    public int ProductId { get; set; }
    public virtual Product Product { get; set; }
  }
```
Here is my Context class:-
```C#
class MyContext : DbContext
  {
    public DbSet<Barcode> Barcode { get; set; }
    public DbSet<BarcodeDetail> BarcodeDetail { get; set; }
    public DbSet<Product> Product { get; set; }
    public DbSet<ProductDetail> ProductDetail { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseSqlServer(@"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=MySqlServerDB1;Integrated Security=True").UseLoggerFactory(_myLoggerFactory);
    }
    public static readonly LoggerFactory _myLoggerFactory = new LoggerFactory(new[] { new Microsoft.Extensions.Logging.Debug.DebugLoggerProvider() });
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
      modelBuilder.Entity<BarcodeDetail>().HasKey(e => e.Code);

      modelBuilder.Entity<ProductDetail>().HasKey(e => e.ProductId);

      modelBuilder.Entity<Product>(
          b =>
          {
            b.HasMany(e => (IEnumerable<Barcode>)e.Barcodes).WithOne(e => (Product)e.Product);
            b.HasOne(e => (ProductDetail)e.Detail).WithOne(e => (Product)e.Product)
                      .HasForeignKey<ProductDetail>(e => e.ProductId);
          });

      modelBuilder.Entity<Barcode>(
          b =>
          {
            b.HasKey(e => e.Code);
            b.HasOne(e => (BarcodeDetail)e.Detail).WithOne()
                .HasForeignKey<BarcodeDetail>(e => e.Code);
          });
    }
    public void SeedUsingFKs()
    {
      var product1 = Add(
          new Product
          {
            Description = "Chocolate Donuts"
          }).Entity;

      var barcode1 = Add(
          new Barcode
          {
            Code = new byte[] { 1, 2, 3, 4 },
            ProductId = product1.ProductId
          }).Entity;
      SaveChanges();
    }
  }
```

And here is my main function:-

```C#
using (var db = new MyContext())
      {
        try
        {
          db.Database.EnsureDeleted();
          db.Database.EnsureCreated();
          db.SeedUsingFKs();
        }
        catch(Exception e)
        {
          Console.WriteLine(e);
        }
      }
```

Upon execution of SeedUsingFKs(), it is giving below error-
```
**"The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Barcode_Product_ProductId". The conflict occurred in database "MySqlServerDB1", table "dbo.Product", column 'ProductId'."**
```

### Create Table Sql
Here are the CreateTable sql that are generated when EnsureCreated() is called.

```sql
CREATE TABLE [Product] (
    [ProductId] int NOT NULL IDENTITY,
    [Description] nvarchar(max) NULL,
    CONSTRAINT [PK_Product] PRIMARY KEY ([ProductId])
);

CREATE TABLE [Barcode] (
    [Code] varbinary(900) NOT NULL,
    [ProductId] int NOT NULL,
    CONSTRAINT [PK_Barcode] PRIMARY KEY ([Code]),
    CONSTRAINT [FK_Barcode_Product_ProductId] FOREIGN KEY ([ProductId]) REFERENCES [Product] ([ProductId]) ON DELETE CASCADE
);

CREATE TABLE [ProductDetail] (
    [ProductId] int NOT NULL,
    CONSTRAINT [PK_ProductDetail] PRIMARY KEY ([ProductId]),
    CONSTRAINT [FK_ProductDetail_Product_ProductId] FOREIGN KEY ([ProductId]) REFERENCES [Product] ([ProductId]) ON DELETE CASCADE
);

CREATE TABLE [BarcodeDetail] (
    [Code] varbinary(900) NOT NULL,
    CONSTRAINT [PK_BarcodeDetail] PRIMARY KEY ([Code]),
    CONSTRAINT [FK_BarcodeDetail_Barcode_Code] FOREIGN KEY ([Code]) REFERENCES [Barcode] ([Code]) ON DELETE CASCADE
);

CREATE INDEX [IX_Barcode_ProductId] ON [Barcode] ([ProductId]);
```

And here is the first statement that is executed when SeedUsingFKs() is called.

```sql
SET NOCOUNT ON;
INSERT INTO [Barcode] ([Code], [ProductId])
VALUES (@p0, @p1);
```

And that's where it gets the exception.

I am thinking that the error is because it is trying to insert data into Barcode table before inserting data into Product table. The error is because it is trying to insert data into ProductId column which is a foreign key. But the referenced table (Product) for the ProductId column does not have any data yet. Hence the issue.

If the sequence is correct then it is not clear to me why it is trying to insert data into BarCode table first even though I am adding data for Product table first in the SeedUsingFKs() method.

### Stacktrace
```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Barcode_Product_ProductId". The conflict occurred in database "MySqlServerDB1", table "dbo.Product", column 'ProductId'.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
ClientConnectionId:1c66d475-45b4-4789-839a-ff684d7e1342
Error Number:547,State:0,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
```

### Further technical details

EF Core version: Microsoft.EntityFrameworkCore 3.1.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.1
Operating system: Windows
IDE: Visual Studio 2019 16.4.2

**Comment by AndriySvyryd** [comment]
@shvmgpt116 You are hitting [the temporary values breaking change](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#tkv)
