### ISSUE TITLE
Adding a foreign Key (Id) to Navigation property  throws an exceptions

### ISSUE THREAD

**Issue by zahialajori** [dotnet/efcore#20349]
Hi , 
I have this issue when trying to assign a foreign key to the entity it throws an exception as follow : 
Key (ItemId)=(0) is not present in table "Items".
Full exception details : 

```
Microsoft.EntityFrameworkCore.DbUpdateException
  HResult=0x80131500
  Message=An error occurred while updating the entries. See the inner exception for details.
  Source=Npgsql.EntityFrameworkCore.PostgreSQL
  StackTrace:
   at Npgsql.EntityFrameworkCore.PostgreSQL.Update.Internal.NpgsqlModificationCommandBatch.Consume(RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at ConsoleApp25.Program.Main(String[] args) in C:\Users\Zahi\source\repos\ConsoleApp25\ConsoleApp25\Program.cs:line 24
```
  This exception was originally thrown at this call stack:

```	Npgsql.NpgsqlConnector.DoReadMessage.__ReadMessageLong|0(Npgsql.DataRowLoadingMode, bool, bool)
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	Npgsql.NpgsqlConnector.DoReadMessage.__ReadMessageLong|0(Npgsql.DataRowLoadingMode, bool, bool)
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	Npgsql.NpgsqlDataReader.NextResult(bool, bool)
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter<TResult>.GetResult()
    ...
    [Call Stack Truncated]
Inner Exception 1:
PostgresException: 23503: insert or update on table "Orders" violates foreign key constraint "FK_Orders_Items_ItemId"
```

### Steps to reproduce

```C#
   public class Order
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Item Item { get; set; }
        public int ItemId { get; set; }
    }
    public class Item
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class ApplicationDbContext : DbContext
    {
        public DbSet<Order> Orders { get; set; }
        public DbSet<Item> Items { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseNpgsql("{connectionstring}");
        }
    }

// Code : 
  using (var context = new ApplicationDbContext())
            {
                Item item = new Item()
                {
                    Name = "Item1"
                };
                Order order = new Order()
                {
                    ItemId = item.Id,
                    Name = "Order1",
                    //Item = item
                };

                context.Add(item);
                context.Add(order);
                var result = context.SaveChanges();

                Console.WriteLine(result);

            }
```

### Further technical details

EF Core version:
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL , Version="3.1.2"
 <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="3.1.2" />
Target framework: (e.g. .NET Core 3.1)
Operating system: Windows 10
IDE: Microsoft Visual Studio Enterprise 2019 ,Version 16.4.5

**Comment by ajcvickers** [comment]
@zahialajori `ItemId = item.Id` is setting the FK to zero, since `item` doesn't have a key value yet. EF fixes up FK values for you when using navigation properties to relate entities. Is there a reason you need to use FK values directly here?

**Comment by zahialajori** [comment]
The issue that the old EF Core 1.1 is supported this approach . Why this not working on EF Core 3.1?

**Comment by ajcvickers** [comment]
@zahialajori As far as I know, the behavior has been like this for every version of EF Core. That being said, 1.1 was a very early release and a lot has changed. It was never intended to work.
