### ISSUE TITLE
It's not a bug. Find a solution. About global query filter

### ISSUE THREAD

**Issue by remeWdm** [dotnet/efcore#20370]
Hello, I used to use efcore 2.2. Now I upgrade efcore 3.1. I have encountered one problem. I know that the problem comes from：LINQ queries are no longer evaluated on the client

I read a lot of issue but didn't solve the problem

### Host 

> [Table("Host")]
 public partial class Host
{
    [Key]
    public int Id{ get; set; }
    public string Name{ get; set; }
}

### UserDataPermissions 

>  [Table("UserDataPermissions")]
 public class UserDataPermissions
 {
[key]
 public int Id { get; set; }
public long BeyondId { get; set; }
public long DataId { get; set; }
}

### AppDbContext

> public virtual DbSet<UserDataPermissions> UserDataPermissions { get; set; }
 public virtual DbSet<Host> Host { get; set; }

>  protected override void OnModelCreating(ModelBuilder modelBuilder)
{
var userDataPermissionsIds = UserDataPermissions.Where(r =>r.BeyondId==AbpSession.UserId).Select(r => r.DataId).ToList();
modelBuilder.Query< H o s t>().HasQueryFilter(e=> userDataPermissionsIds.Contains(e.Id));
base.OnModelCreating(modelBuilder);
}

use efcore2.2 userDataPermissionsIds  result evaluated on the client
but efcore3.1 throw exception，result evaluated on the client is not support
Official solution

> If a query can't be fully translated, then either rewrite the query in a form that can be translated, or use AsEnumerable(), ToList(), or similar to explicitly bring data back to the client where it can then be further processed using LINQ-to-Objects.

I know there are two solutions：
1、Write correct and translatable expressions
2、get ‘userDataPermissionsIds’ result data in AppDbContext

I have tried many ways to write the two methods above. It took three days to solve the problem. but it still hasn't been solved.
I can't write the right executable expression and I don't get ‘userDataPermissionsIds’ result data in AppDbContext

Can you help me,Thank you very much

Form：a rookie programmer

### Further technical details

EF Core version:ef core 3.1.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.1
Operating system:win 10 enterprise
IDE: (e.g. Visual Studio 2019 16.4.6

**Comment by remeWdm** [comment]
No people knows how to solve it？

**Comment by remeWdm** [comment]
public virtual DbSet UserDataPermissions { get; set; }

public virtual DbSet Host { get; set; }

protected List<int> HostDataPermissionIdsQueryResult => UserDataPermissions.Where(r => r.BeyondId == AbpSession.UserId).Select(r => r.DataId).ToList();

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
modelBuilder.Query< H o s t >().HasQueryFilter(e=> HostDataPermissionIdsQueryResult.Contains(e.Id));
base.OnModelCreating(modelBuilder);
}

**Comment by remeWdm** [comment]
In fact, it's written in the above way, but it doesn't work

**Comment by remeWdm** [comment]
I find my problem is the same as this one, but I can't find out how to solve it
https://github.com/dotnet/efcore/issues/17253

**Comment by remeWdm** [comment]
I Use

> protected List HostDataPermissionIdsQueryResult => **Set< UserDataPermissions >()**.Where(r => r.BeyondId == AbpSession.UserId).Select(r => r.DataId).ToList();

Still wrong

> System.InvalidOperationException: The LINQ expression 'DbSet<Host>
    .Where(h => __ef_filter__HostDataPermissionIds_0.Contains(((IHostData)h).HostId))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|8_0(ShapedQueryExpression translated, <>c__DisplayClass8_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFun...

Can you tell me how to solve it
@maumar   @taisbak
Thank you very much

**Comment by remeWdm** [comment]
https://github.com/dotnet/efcore/commit/d0b21edfe706c094fb631e640841d7822eeaff49

I don't know how to use it to solve my problems
