### ISSUE TITLE
dotnet ef scaffold does not include all columns of view

### ISSUE THREAD

**Issue by digitalsigi** [dotnet/efcore#20430]
I am scaffolding views from database first and found, that not all columns are included in OnModelBuilder, actually from 7 columns only 3 are scaffolded.

The followin code snippet from Unit Test produces an exception:
```

            var sassen = context.vwWerdegangForIdentity
                .GroupBy(g => new { g.RNr, g.SassenNrId })
                .Select(x => new { Group = x.Key, Anzahl = x.Count() })
                .Where(w => w.Anzahl > 1).ToList();
                ;
```

```
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at avsweb.DAL.Tests.DBContentTest.VwWerdegangForIdentityTests.WerdegangCountReychPerSasseTest() in C:\GITatUHU\rvsweb\UnitTests\avsweb.DAL.Tests\DBContentTest\vwWerdegangForIdentityTests.cs:line 58
```

### Steps to reproduce
1. Create Database from attached schema
2. create asp net core project and include entityframework
3. scaffold database
4. Inspect result in context and compare to view in database for view vwWerdegangforIdentity
5. or create unit test with code snippet above
6. run unit test
7. Exception
[script.zip](https://github.com/dotnet/efcore/files/4392875/script.zip)

### Further technical details

EF Core version: 3.1
Micrsoft.EntityFrameworkCore.SqlServer: 3.1.2 
Target framework: (e.g. .NET Core 3.0)
Operating system: Development: Windows 10; SQL Server 2017 Express on Ubuntu 18.04
IDE: (e.g. Visual Studio 2019 16.3) VS 2019 16.5.1

**Comment by ErikEJ** [comment]
Error message??

**Comment by digitalsigi** [comment]
Head at desk, (several times)
Thank you for looking into it.
Its my fault. I have different environments for plain develoment and unit testing and so on.
You guess it -> wrong connection string.
