### ISSUE TITLE
Owned Attribute and Owned Fluent API have different behaviors

### ISSUE THREAD

**Issue by vflame** [dotnet/efcore#20446]
Fluent API configuration of owned entities results in errors, whereas decorating with the `[Owned]` attribute results in correct migration code. This is bad for DDD where domain entities should not be taking a dependency on EF core to use the `[Owned]` attribute.

Entities/Owned Entities
```c#
    public class Wallet
        {
            public string Id { get; private set; }
            public Money OnHand { get; private set; }
            public Money OnLoan { get; private set; }

            public ExchangeRate ExchangeRate { get; private set; }

        }
        //[Owned]
        public class ExchangeRate
        {
            public Currency OriginalCurrency { get; private set; }
            public Currency NewCurrency { get; private set; }
        }

        //[Owned] 
        public class Money
        {
            public decimal Amount { get; private set; }
            public Currency Currency { get; private set; }
        }
        //[Owned]
        public class Currency
        {
            public string Name { get; private set; }
            public string Symbol { get; private set; }

        }
```

The following fluent API configuration
```c#
  protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.Entity<Wallet>();
            builder.Owned<Currency>();
            builder.Owned<ExchangeRate>();
            builder.Owned<Money>();
            base.OnModelCreating(builder);
        }
```

results in:

```c#
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.RelationshipDiscoveryConvention.ProcessNavigationRemoved(IConventionEntityTypeBuilder sourceEntityTypeBuilder, IConventionEntityTypeBuilder targetEntityTypeBuilder, String navigationName, MemberInfo memberInfo, IConventionContext`1 context)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnNavigationRemoved(IConventionEntityTypeBuilder sourceEntityTypeBuilder, IConventionEntityTypeBuilder targetEntityTypeBuilder, String navigationName, MemberInfo memberInfo)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnNavigationRemoved(IConventionEntityTypeBuilder sourceEntityTypeBuilder, IConventionEntityTypeBuilder targetEntityTypeBuilder, String navigationName, MemberInfo memberInfo)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.RemoveForeignKey(ForeignKey foreignKey)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasNoRelationship(ForeignKey foreignKey, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.RemoveNonOwnershipRelationships(ForeignKey ownership, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Owned(Type type, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.ModelBuilder.Owned[T]()
   at OwnedEntityAttributeVsFluent.Data.ApplicationDbContext.OnModelCreating(ModelBuilder builder) in C:\Users\t\source\repos\OwnedEntityAttributeVsFluent\OwnedEntityAttributeVsFluent\Data\ApplicationDbContext.cs:line 21
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.
```

### Further technical details

EF Core version: 3.1.3
Database provider: mssqllocaldb
Target framework: .NET core 3.1
Operating system: WIN10
IDE: VS 2019

**Comment by bcallaghan-et** [comment]
@vflame I have noticed similar behavior in my own code, and I found a workaround that might help you. If I register the Entity types before the Owned types, as you have in your sample, I get the same NRE. If I register the Owned types first, everything is fine. However, this workaround prevents me from using DbSet<TEntity> properties, as they get registered before OnModelCreating is executed, causing the same problem.

This causes a NRE:
```cs
protected override void OnModelCreating(ModelBuilder builder)
{
    builder.Entity<Wallet>();
    builder.Owned<Currency>();
    builder.Owned<ExchangeRate>();
    builder.Owned<Money>();
    base.OnModelCreating(builder);
}
```

This works:
```cs
protected override void OnModelCreating(ModelBuilder builder)
{
    builder.Owned<Currency>();
    builder.Owned<ExchangeRate>();
    builder.Owned<Money>();
    builder.Entity<Wallet>();
    base.OnModelCreating(builder);
}
```

**Comment by bcallaghan-et** [comment]
Another way in which I have seen that the Owned attribute and Fluent API have different behaviors is how they apply property configurations. With the Owned attribute, you can apply data annotations to the properties, and those annotations will apply to all instances of the owned type. However, the Owned Fluent API as shown in the above samples has no overload or return value that can be used to configure the entity. With the Fluent API, each instance of an owned entity must be configured separately. This leads to a lot of duplication when a single type is reused in many entities.

For example, let's say I have the following model:
```cs
[Owned]
public class Currency
{
    [Required]
    public string Name { get; private set; }
    [MaxLength(3)]
    public string Symbol { get; private set; }
}
```
There is no way to create the same result using the Fluent API. I propose that the Owned Fluent API is extended to match the existing Entity Fluent API, allowing code such as the following:
```cs
protected override void OnModelCreating(ModelBuilder builder)
{
    builder.Owned<Currency>().Property(c => c.Name).IsRequired();
    builder.Owned<Currency>(owned => owned.Property(c => c.Symbol).HasMaxLength(3));
}
```

I would also like to see an interface `IOwnedTypeConfiguration<TOwned>` that is similar to the existing `IEntityTypeConfiguration<TEntity>` interface.

**Comment by ajcvickers** [comment]
@bcallaghan-et This is tracked by #14047

**Comment by ajcvickers** [comment]
@AndriySvyryd Poachable by @lajones?

**Comment by AndriySvyryd** [comment]
@ajcvickers Yes, might be already fixed in master

**Comment by lajones** [comment]
Poached.

**Comment by lajones** [comment]
Note for self: I get a different exception (see below). Continuing to investigate.

```C#
Unhandled exception. System.Exception: Check.DebugAssert failed: removed is false
   at Microsoft.EntityFrameworkCore.Utilities.Check.DebugAssert(Boolean condition, String message)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.OnForeignKeyUpdating(ForeignKey foreignKey)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.RemoveForeignKey(ForeignKey foreignKey)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasNoRelationship(ForeignKey foreignKey, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.RemoveNonOwnershipRelationships(ForeignKey ownership, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Owned(Type type, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.ModelBuilder.Owned[T]()
   at Test20200414_Issue20446_01.Issue20446Context01.OnModelCreating(ModelBuilder builder)
```

**Comment by AndriySvyryd** [comment]
@lajones That's because you are running on a Debug build

**Comment by lajones** [comment]
@AndriySvyryd Yes - I just phrased it badly. Should have said - this exception (in a debug build) causes the later exception that the user is seeing.

**Comment by AndriySvyryd** [comment]
@lajones Ok. You should also timebox the investigation as model building issues might be far removed from the place where it actually throws.

**Comment by lajones** [comment]
Another note for self:
- At [InternalEntityTypeBuilder.cs#L3130](https://github.com/dotnet/efcore/blob/922f2905413f4837051857fcc084d0865e02b0ad/src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs#L3130) it's looping over a list of incompatibleRelationships.
- In this case, when you call `Owned<>` on the EntityType `Currency` above, there are 2 such relationships (i.e. FKs) which were set up earlier by the `Entity<Wallet>` call.
- It calls `Builder.HasNoRelationship(...)` on the first one, but this can end up removing and replacing the 2nd FK.
- Hence when you've finished doing all the processing for the 1st FK, the 2nd FK is no longer what's in that EntityType's `_foreignKeys` variable.
- So, when we try to remove that FK it fails (with the `Check.DebugAssert()` exception I mentioned above), but in a Release build that check is skipped over and the code goes on as if it had succeeded which later causes the exception the customer is seeing.
