### ISSUE TITLE
Unable to cast object of type 'System.Int64' to type 'System.String'

### ISSUE THREAD

**Issue by haskaan** [dotnet/efcore#20537]
"Unable to cast object of type 'System.Int64' to type 'System.String'" error in two cross apply operations from the same table.

It does not receive an error when I remove any cross apply.

Full Code: 
https://gist.github.com/haskaan/c701ea362ff962191b865a188cb8b65f

```
from invParty in (from party0 in _dbContext.OrderPartyDetails
				 where party0.OrderId == ord.Id
					  && party0.AddressTypeId == (long)AddressTypeEnum.FaturaAdresi
				 orderby party0.Id ascending
				 select new
				 {
					 party0.Name,
					 party0.Surname,
					 party0.MobilePhone,
					 party0.TaxNumber
				 }).Take(1).DefaultIfEmpty()

from delParty in (from party1 in _dbContext.OrderPartyDetails
				 join c0 in _dbContext.Cities on party1.CityId equals c0.Id into c0s
				 from c0 in c0s.DefaultIfEmpty()
				 join t0 in _dbContext.Towns on party1.TownId equals t0.Id into t0s
				 from t0 in t0s.DefaultIfEmpty()
				 join z0 in _dbContext.ZipCodes on party1.ZipCodeId equals z0.Id into z0s
				 from z0 in z0s.DefaultIfEmpty()
				 where party1.OrderId == ord.Id
					  && party1.AddressTypeId == (long)AddressTypeEnum.TeslimAdresi
				 orderby party1.Id ascending
				 select new
				 {
					 party1.Name,
					 party1.Surname,
					 party1.MobilePhone,
					 party1.AddressText,
					 party1.TaxNumber,
					 CityDesc = (c0 != null) ? c0.Description : "",
					 TownDesc = (t0 != null) ? t0.Description : "",
					 ZipCode = (z0 != null) ? z0.Code : "",
				 }).Take(1).DefaultIfEmpty()
```

ExMessage: Unable to cast object of type 'System.Int64' to type 'System.String'
Exceptions:
```
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CompositeShaper.TypedCompositeShaper`5.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SLOT.Infrastructure.DataLibrary.OutboundOperations.PackingManagement.PackingManagementUnitOfWork.GetWayBillWithOrder(GetWayBillWithOrderAndTemplateRequestModel model) in D:\Repos\slot_1\Infrastructure\SLOT.Infrastructure.DataLibrary\OutboundOperations\PackingManagement\PackingManagementUnitOfWork.cs:line 1712
   at SLOT.Modules.WMS.OutboundOperations.Workflows.PackingWorkFlow.GetWayBillWithOrder(GetWayBillWithOrderAndTemplateRequestModel model) in D:\Repos\slot_1\Modules\WMS\SLOT.Modules.WMS.OutboundOperations\Workflows\PackingWorkFlow.cs:line 460
   at SLOT.Services.ApiService.Controllers.WMS.OutboundOperations.PackingController.GetWayBillWithOrder(GetWayBillWithOrderAndTemplateRequestModel model) in D:\Repos\slot_1\Services\SLOT.Services.ApiService\Controllers\WMS\OutboundOperations\PackingController.cs:line 290
```

### Further technical details

EF Core version: 2.2.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 2.2.1
Operating system: Windows 10 Pro - 1909 - 18363.752
IDE: Visual Studio 2019 16.5.2

**Comment by ajcvickers** [comment]
@haskaan EF Core 2.2 is now [out-of-support](https://docs.microsoft.com/en-us/ef/core/what-is-new/). Please update to 3.1 and report back if you're still running into this issue.

**Comment by haskaan** [comment]
Omg! It will be very difficult to update the entire solution. I will temporarily try the 3.1 update.

**Comment by haskaan** [comment]
It works smoothly on "EF.Core 3.1.3".
