### ISSUE TITLE
SetValues() exceptions in randomised testing (EF Core 5 Preview 2)

### ISSUE THREAD

**Issue by markm77** [dotnet/efcore#20673]
Hi there,

I'm doing randomised testing of my DB interface (using in-memory SQLite) which includes the line

```
_db.Entry(existingValue).CurrentValues.SetValues(instance);
```

and where existing value and instance have the same ID.

Randomly (and not always) this produces the error

System.InvalidOperationException: 'The property 'Id' on entity type 'SoftwareStatementProfile' is part of a key and so cannot be modified or marked as modified. To change the principal of an existing entity with an identifying foreign key first delete the dependent and invoke 'SaveChanges' then associate the dependent with the new principal.'

when instance.Id and existingValue.Id are the same!

Here's example values I just captured which triggered the exception (exception details below):

instance.Id
"4\0\"\u0018]\u007fKA\u0006(tj\fQ\u001d\u00135zp<^#\u0019e"

existingValue.Id
"4\0\"\u0018]\u007fKA\u0006(tj\fQ\u001d\u00135zp<^#\u0019e"

My question is really this - am I breaking some rule with my exotic Ids (produced by FsCheck.Xunit as it happens) or does this look like a bug?

I am using EF Core 5 Preview 2 with all latest packages. I reproduced this on Windows (VS) and macOS (Rider), latest versions.

Any tips appreciated and I can supply more info if further investigation is warranted.

BR,
Mark

System.InvalidOperationException
  HResult=0x80131509
  Message=The property 'Id' on entity type 'SoftwareStatementProfile' is part of a key and so cannot be modified or marked as modified. To change the principal of an existing entity with an identifying foreign key first delete the dependent and invoke 'SaveChanges' then associate the dependent with the new principal.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetPropertyModified(IProperty property, Boolean changeState, Boolean isModified, Boolean isConceptualNull, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.PropertyChanged(InternalEntityEntry entry, IPropertyBase propertyBase, Boolean setModified)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.PropertyChanged(InternalEntityEntry entry, IPropertyBase property, Boolean setModified)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean isMaterialization, Boolean setModified, Boolean isCascadeDelete, CurrentValueType valueType)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean isMaterialization, Boolean setModified, Boolean isCascadeDelete)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.set_Item(IPropertyBase propertyBase, Object value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.CurrentPropertyValues.SetValueInternal(IProperty property, Object value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntryPropertyValues.SetValues(Object obj)
   at FinnovationLabs.OpenBanking.Library.Connector.Persistence.DbEntityRepository`1.Set(TEntity instance) in C:\Repos\GitHub\markm77\open-banking-connector-csharp\src\OpenBanking.Library.Connector\Persistence\DbEntityRepository.cs:line 91
   at FinnovationLabs.OpenBanking.Library.Connector.IntegrationTests.Persistence.MemorySoftwareStatementProfileProfileRepositoryTests.<>c__DisplayClass4_0.<GetAsync_KnownId_ReturnsItem>b__0() in C:\Repos\GitHub\markm77\open-banking-connector-csharp\test\integration-tests\OpenBanking.Library.Connector.IntegrationTests\Persistence\MemorySoftwareStatementProfileProfileRepositoryTests.cs:line 45
   at FsCheck.Testable.evaluate[a,b](FSharpFunc`2 body, a a)

**Comment by markm77** [comment]
Okay, I decided to do a lot more debug on this today. I created a sync method to debug the issue more easily. It includes a check to see if instance.Id and existingValue.Id are the same when the exception is triggered. (Obviously they should be as a consequence of the Find() method call.)

```csharp
public TEntity Set(TEntity instance)
{
    instance.ArgNotNull(nameof(instance));

    // Input should be detached (untracked)
    if (_db.Entry(instance).State != EntityState.Detached)
    {
        throw new InvalidOperationException("Entity is tracked, no need to use set (upsert).");
    }

    var existingValue = _db.Set<TEntity>()
        .Find(instance.Id);
    if (existingValue is null)
    {
        _db.Add(instance);
        return instance;
    }
    else
    {
        if (instance.Id != existingValue.Id)
        {
            Console.WriteLine("Not equal");
        }
        _db.Entry(existingValue).CurrentValues.SetValues(instance);
        return existingValue;
    }
}
```

I found that for every case I ran instance.Id and existingValue.Id are in fact not the same when the exception is triggered! So sorry if the example values above from yesterday were wrong (??).
Here is a selection of values that trigger the exception from today's testing:

```
+		instance	Id = "W#E\n\0Ln3)u\u0017\\Rt@6{\u001di_$F\u0012\bMoe1S\u0018\u000eZ|A7\u0003%j`\u0002ND", DefaultFragmentRedirectUrl = null	FinnovationLabs.OpenBanking.Library.Connector.Models.Persistent.SoftwareStatementProfile
+		existingValue	Id = "W#E\n", DefaultFragmentRedirectUrl = null	FinnovationLabs.OpenBanking.Library.Connector.Models.Persistent.SoftwareStatementProfile

+		instance	Id = "\0\"/<wD$m5\u0012$pf\b", DefaultFragmentRedirectUrl = null	FinnovationLabs.OpenBanking.Library.Connector.Models.Persistent.SoftwareStatementProfile
+		existingValue	Id = "", DefaultFragmentRedirectUrl = null	FinnovationLabs.OpenBanking.Library.Connector.Models.Persistent.SoftwareStatementProfile

+		instance	Id = "\0q]\r\u0017<rE5F*6", DefaultFragmentRedirectUrl = null	FinnovationLabs.OpenBanking.Library.Connector.Models.Persistent.SoftwareStatementProfile
+		existingValue	Id = "", DefaultFragmentRedirectUrl = null	FinnovationLabs.OpenBanking.Library.Connector.Models.Persistent.SoftwareStatementProfile

+		instance	Id = "\0)Mt_a\u0013Y\u001ca\u0003yph<\u007f\u0018:\u007fu\u0017c(\u001e@\f\u0002Gi5+p\u0012\b~", DefaultFragmentRedirectUrl = null	FinnovationLabs.OpenBanking.Library.Connector.Models.Persistent.SoftwareStatementProfile
+		existingValue	Id = "", DefaultFragmentRedirectUrl = null	FinnovationLabs.OpenBanking.Library.Connector.Models.Persistent.SoftwareStatementProfile

+		instance	Id = "\0z\u001aA<\bxt\rl%.IH_H6\u0002JKQL", DefaultFragmentRedirectUrl = null	FinnovationLabs.OpenBanking.Library.Connector.Models.Persistent.SoftwareStatementProfile
+		existingValue	Id = "", DefaultFragmentRedirectUrl = null	FinnovationLabs.OpenBanking.Library.Connector.Models.Persistent.SoftwareStatementProfile
```

So it seems the real issue is that Find() produces an entity where if the Id contains ```\0``` the Id is trucated.... I guess this is because of C code somewhere (perhaps in SQLite?).

Not sure if I should close this.... does anyone from the EF Core team have any comment? Should Find() produce an exception where the Id will be truncated?

BR,
Mark

**Comment by ajcvickers** [comment]
@markm77 Nulls in strings are not properly supported by many database providers--SQLite and Npgsql being two I know about.

**Comment by markm77** [comment]
Okay, thanks for the comment @ajcvickers , makes sense.
