### ISSUE TITLE
HasConversion combined with some Expressions returns null

### ISSUE THREAD

**Issue by arielmoraes** [dotnet/efcore#20776]
When using the SqlServer Provider, properties inherited from base classes won't have their values converted when querying a entity configured to use ValueConversion. Using the InMemoryProvider the results are correct.

![image](https://user-images.githubusercontent.com/6741634/80558294-41d5c700-89b0-11ea-97e1-e0d4ce87c558.png)

A reproducible test project is attached below.
[ValueConversionTests.zip](https://github.com/dotnet/efcore/files/4549663/ValueConversionTests.zip)

EF Core version: 3.1.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1.201
Operating system: Windows
IDE: Visual Studio 2019 16.5.4

**Comment by ajcvickers** [comment]
@arielmoraes Thanks for filing this. It's a very interesting bug! With the value conversion defined like this:
```C#
.HasConversion(type => type.FullName, name => Type.GetType(name));
```
EF takes the expression for `Type.GetType(name)` and compiles it directly into the materialization delegate that creates entity instances. When called in this context a null value is being returned.

Pulling this into a method so that a call to the method is instead compiled into the expression tree makes it work!

```C#
.HasConversion(type => type.FullName, name => ToType(name));
```
```C#
private static Type ToType(string name) => Type.GetType(name);
```

So this also means that extracting a method like this is a good workaround.

**Comment by arielmoraes** [comment]
@ajcvickers interesting, so it's not related to the inheritance at all, should I edit the issue title to descibe the problem more accurately?

**Comment by ajcvickers** [comment]
@arielmoraes Sure--that would be very helpful. Thanks!

**Comment by ajcvickers** [comment]
The issue here is external to EF and is a limitation of `Type.GetType()`. GetType can only load types from system assemblies or are resolvable from the calling assembly. This means if GetType is compiled into the materialization expression, then it may not be able to resolve types that it would be able to when called from the application assembly. This can be demonstrated by calling the overload that throws errors:

```
System.TypeLoadException : Could not load type 'Microsoft.EntityFrameworkCore.CustomConvertersTestBase`1+EyeHazTypes' from assembly 'Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMarkHandle stackMark, ObjectHandleOnStack assemblyLoadContext, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at lambda_method789(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext() in /home/ajcvickers/efcore/src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs:line 157
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.CustomConvertersTestBase`1.Can_query_and_update_with_converter_for_Type_when_GetType_can_load_it() in /home/ajcvickers/efcore/test/EFCore.Specification.Tests/CustomConvertersTestBase.cs:line 133
```

There is no action on the EF side. Calling GetType from the application assembly (as shown) is the correct way to deal with this.
