### ISSUE TITLE
Issue with multiple owned types

### ISSUE THREAD

**Issue by tdolgyras** [dotnet/efcore#20789]
We upgraded our project in Ef core 3.1 with Npgsql.EntityFrameworkCore.PostgreSQL 3.1.3 and we have a weird issue. We use [multiple owned types](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities#sharing-the-same-net-type-among-multiple-owned-types) in our code.
When we try to run migrations we get this error.

```
System.InvalidOperationException: The keys {'MasterMasterId'} on 'Master.OwnedEntity1#OwnedEntity' and {'MasterId'} on 'Master' are both mapped to 'master.pk_master' but with different columns ({'master_master_id'} and {'master_id'}).
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedKeysCompatibility(IReadOnlyList`1 mappedTypes, String tableName, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedTableCompatibility(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Infrastructure.NpgsqlModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.ValidatingConvention.ProcessModelFinalized(IConventionModelBuilder modelBuilder, IConventionContext`1 context)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelFinalized(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelFinalized(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FinalizeModel()
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
```

thank you

**Comment by roji** [comment]
Can you please post a minimal model which triggers this issue?

**Comment by tdolgyras** [comment]
Removing completely
 UseSnakeCaseNamingConvention  and 
its package     
`<PackageReference Include="EFCore.NamingConventions" Version="1.1.0" />`
from project solved the problem.

Thank you a lot for your help!

**Comment by roji** [comment]
@tdolgyras can you please check if your problem is described in https://github.com/efcore/EFCore.NamingConventions/issues/17?

If not, can you please open a new issue on https://github.com/efcore/EFCore.NamingConventions with a small repro so this can be fixed?
