### ISSUE TITLE
EF Is breaking inserts by hooking things up that it shouldn't

### ISSUE THREAD

**Issue by TehWardy** [dotnet/efcore#20825]
I initially reported this https://github.com/dotnet/efcore/issues/20200 Obviously this was closed because for some reason you guys couldn't reproduce it.

Is there a way to tell EF ... "DON'T mess with this, insert it and sets it's PK, DO NOTHING ELSE", when I have other stuff in the change tracker in an unchanged state?

Now i'm hitting a very similar situation where I have done something like this ...

```cs
var appId = 123;
var pageId = 456;

// the "false" in each of these GetAll<T>() calls tells the context to add .AsNoTracking() to the query 
// so I shouldn't be tracking changes to any of this as i'm not expecting this call to write any of this back later.
var app = Db.GetAll<App>(false).FirstOrDefault(a => a.Id == appId);
app.Layouts = Db.GetAll<Layout>(false).Where(t => t.AppId == app.Id).ToArray();
app.Templates = Db.GetAll<Template>(false).Where(t => t.AppId == app.Id).ToArray();
app.Components = Db.GetAll<Component>(false).Where(t => t.AppId == app.Id).ToArray();
app.Resources = Db.GetAll<Resource>(false).Where(t => t.AppId == app.Id).ToArray();
app.Pages = Db.GetAll<Page>(false).Where(t => t.AppId == app.Id).Include(p => p.PageInfo).ToArray();

var result = app.Pages.First(p => p.Id == pageId);
return result.Render();
```
during the render process I replace resources with their localised versions from tags found in the content blocks as part of the page construction.
This all works fine and is my concern.

Where it all goes to hell is when I identify that a resource is missing so i drop in to here ...

```cs
private static async Task AddMissingResources(string key, PageRenderParams p, IEnumerable<string> missing)
{
    var r = missing.Select(m => new Resource
    {
        AppId = p.App.Id,
        App = null,
        Key = key,
        Name = m,
        DisplayName = m,
        ShortDisplayName = m,
        Description = m,
        Culture = string.Empty
    }).ToArray();

    try
    {
        await p.Db.AddAllAsync(r);

        log.Info($"New default resources generated:\n" + missing.Select(m => new { Key = key, Name = m }).ToArray().ToJson());
    }
    catch (Exception ex)
    {
        log.Info($"Resources could not be added due to exception:\n{ex.Message}\n{ex.StackTrace}");
        log.Warn($"Please manually add and translate to {p.Culture} the following resources:\n{string.Join("\n", r.Select(i => i.ToJson()))}");
    }
}
```

The add call for some reason triggers EF to set negative primary key values on the resources i'm trying to insert and then it sets the "App" property to the entity it has in memory and goes about attempting to insert the entire entity graph again where I then get the exception stack below.

Long story short, I have no control over this and it seems if the Context has an entity and I set an ID it will do what I told it explicitly not to do then break it's own insert operation.

In this case there is no entity graph to work on, this is a flat set of "Resource" entity rows I want to insert and then continue on my way with.

The primary keys for Resource are integer keys that are seeded by and computed in the DB, if EF can't manage that there is nothing I can do to resolve it.

```
2020-05-03 10:14:37,139 [4] ERROR  Core.Data.EFDataContext`1[[Core.Objects.Entities.User, Core.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] - Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> System.Data.SqlClient.SqlException (0x80131904): Cannot insert explicit value for identity column in table 'Apps' when IDENTITY_INSERT is set to OFF.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:d7189c5d-40b9-4bf2-8d85-d27563166ef7
Error Number:544,State:1,Class:16
ClientConnectionId before routing:0691c0ce-ce36-4881-816b-bc0c9f246e2f
Routing Destination:my-azure-sql-Instance
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Core.Data.EFDataContext`1.SaveChangesAsync(Boolean andAudit) in D:\a\24\s\Back End\Framework\Core\Data\EFDataContext.cs:line 191 
2020-05-03 10:14:37,143 [4] ERROR  Core.Data.EFDataContext`1[[Core.Objects.Entities.User, Core.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] - System.Data.SqlClient.SqlException (0x80131904): Cannot insert explicit value for identity column in table 'Apps' when IDENTITY_INSERT is set to OFF.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:d7189c5d-40b9-4bf2-8d85-d27563166ef7
Error Number:544,State:1,Class:16
ClientConnectionId before routing:0691c0ce-ce36-4881-816b-bc0c9f246e2f
Routing Destination:my-azure-sql-Instance 
2020-05-03 10:14:37,144 [4] INFO   Core.Objects.ContentHelper - Resources could not be added due to exception:
The property 'Id' on entity type 'Resource' has a temporary value while attempting to change the entity's state to 'Unchanged'. Either set a permanent value explicitly or ensure that the database is configured to generate values for this property.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.AcceptChanges()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.AcceptAllChanges(IReadOnlyList`1 changedEntries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.AcceptAllChanges()
   at Microsoft.EntityFrameworkCore.ChangeTracking.ChangeTracker.AcceptAllChanges()
   at Core.Data.EFDataContext`1.SaveChangesAsync(Boolean andAudit) in D:\a\24\s\Back End\Framework\Core\Data\EFDataContext.cs:line 227
```

**Comment by ajcvickers** [comment]
@TehWardy The problem here is that again I can't run this code to reproduce what you are seeing. I would love to be able to fully understand what you are trying to do, but unfortunately I am not able to do so from the descriptions you provide. If you can in some way provide us with code that allows us to reproduce what you are seeing, then I would be happy to investigate and try to help.

**Comment by TehWardy** [comment]
@ajcvickers Regardless of what I have in the contexts change tracking should EF only do what I asked in the second code sample or is there something that would trigger it to wire up stuff?

For example: setting the entity object values on the entity prior to insert?

My issue is understanding the behaviour that EF exhibits, I can't seem to figure out it's rules.

**Comment by roji** [comment]
@TehWardy the easiest way for us to understand what exactly you're asking (i.e. which of its rules you can't figure out) is for us to see a runnable code sample, and for you to tell us where it's doing something you don't understand. It's very hard for us to understand from textual descriptions and partial code samples exactly what you're trying to do.

Try to put together a small console application and we'll definitely look at it and help you out.

**Comment by TehWardy** [comment]
Would you guys be willing to jump on webex or some sort of screen share / conference call ?
Building out a new solution could take time, and sending you my complete solution is going to raise all sorts of NDA issues.

**Comment by roji** [comment]
@TehWardy we definitely don't need to see your complete solution - that would again require a lot of diving in.

Isn't is possible for you create a small console program with a dummy context and a couple operations that demonstrate what isn't working as expected?

**Comment by TehWardy** [comment]
Ok Leave it with me and i'll see if I can throw together a gist with the parts or something from a separate reproduction of the issue.

**Comment by roji** [comment]
Thanks for understanding @TehWardy! From experience that really is the most efficient way to help you out, both for us and for you.

**Comment by TehWardy** [comment]
I spending a lot of time here doing what I think should be a done deal ...
Do you guys have a "contoso" or similar console app that just spins up a fully populated complex db that I could start from?

I think if I re-produce it in a structure you're used to it might be more helpful.
that said I think I have most of this in place, there's just more than I expected of it.

**Comment by roji** [comment]
@TehWardy if it's helpful, here's [the SQL script](https://github.com/dotnet/efcore/blob/master/test/EFCore.SqlServer.FunctionalTests/Northwind.sql) we use to initialize the Northwind database for our tests. Hopefully that helps.

However, when we work internally, we typically start with an empty DbContext and add exactly the entities and data necessary to reproduce the bug. [Here's a good example](https://github.com/dotnet/efcore/issues/20449#issuecomment-606259157) of the kind of repro we ideally look for; you're the one with the bug, so you know best what the context and entities need to look like to reproduce it.

**Comment by TehWardy** [comment]
Yeh, that makes sense.
Probably best that I keep at it and trim it down once I get it up and running.

I'm trying to pull apart complex entities though, I tend not to treat them like dumb POCO's in my stack so there's a ton of business logic in the entities themselves I'm having to rip out as it's broken without the full codebase.

None of it is relevant to the issue I have though so it shouldn't matter but I think the problem I have  only occurs when the context lifecycle is something like ...

 - create context
 - get some entity
 - get some child entity set and assign to previous entity
     - repeat a couple times
 - some business logic on my part (no EF interaction)
 - insert some new entities in to db that happen to be related to the first entity I pulled from the db.

My issue boils down to the wiring up I think EF is doing "on my behalf" when I don't want / need it to as it causes what I think @ajcvickers pointed to in the other ticket as a new "broken scenario" according to the changes in the latest version.

That said, I'm not using the latest version either, i'm running on 2.2.6 but the same thing happens in the latest version so this isn't a 3.x only thing.
