### ISSUE TITLE
"no such column" exception querying a view with navigation property

### ISSUE THREAD

**Issue by Asier-Villanueva** [dotnet/efcore#20833]
When I try to query a view which model has a navigation property, the query isn't properly created and result in an exception.

The shortest example to reproduce it that I have been able to create:

**The model**

```C#
    public class Customer
    {
        [Key]
        public int CustomerId { get; set; }

        public ICollection<Token> Tokens { get; set; }
    }

    public class Token
    {
        [Key]
        public int CustomerId { get; set; }
        [Key]
        public int TokenId { get; set; }
    }


    public class CustomerView
    {
        public int CustomerId { get; set; }
        public int TokenId { get; set; }

        public Token Token { get; set; }
    }
```
**The database context:**

```C#
    public class DatabaseContext: DbContext
    {
        public DbSet<Customer> Customers { get; set; }
        public DbSet<CustomerView> CustomerView { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite("Data Source=blogging.db");
            optionsBuilder.UseLoggerFactory(LoggerFactory.Create(builder => builder.AddDebug()));
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Token>()
                .HasKey(c => new { c.CustomerId, c.TokenId });

            modelBuilder.Entity<CustomerView>()
                .HasNoKey().ToView("CustomerView");

            base.OnModelCreating(modelBuilder);
        }
    }
```
**Generated migration:**

```C#
    public partial class InitialCreate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Customers",
                columns: table => new
                {
                    CustomerId = table.Column<int>(nullable: false)
                        .Annotation("Sqlite:Autoincrement", true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Customers", x => x.CustomerId);
                });

            migrationBuilder.CreateTable(
                name: "Token",
                columns: table => new
                {
                    CustomerId = table.Column<int>(nullable: false),
                    TokenId = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Token", x => new { x.CustomerId, x.TokenId });
                    table.ForeignKey(
                        name: "FK_Token_Customers_CustomerId",
                        column: x => x.CustomerId,
                        principalTable: "Customers",
                        principalColumn: "CustomerId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.Sql(@"CREATE VIEW customerview AS 
                        SELECT CustomerId, 1 AS TokenId
                        FROM customers;");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Token");

            migrationBuilder.DropTable(
                name: "Customers");

            migrationBuilder.Sql("FROP VIEW customerview;");
        }
    }
```
**And the code to execute:**

```C#
            using var db = new DatabaseContext();

            var DataQuery = db.CustomerView
                .Include(c => c.Token)
                .Select(c => c.Token.CustomerId);

            _ = DataQuery.ToList();
```

**The generated query is:**

```sql
SELECT "t"."CustomerId"
FROM "CustomerView" AS "c"
LEFT JOIN "Token" AS "t" ON ("c"."TokenCustomerId" = "t"."CustomerId") AND ("c"."TokenId1" = "t"."TokenId")
```
With unknown fields _TokenCustomerId_ and _TokenId1_.

**And the returned exception:**

```
Microsoft.EntityFrameworkCore.Query: Error: An exception occurred while iterating over the results of a query for context type 'EFCoreIssue.DatabaseContext'.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: c.TokenCustomerId'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()

Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.EntityFrameworkCore.Relational.dll
An unhandled exception of type 'Microsoft.Data.Sqlite.SqliteException' occurred in Microsoft.EntityFrameworkCore.Relational.dll
SQLite Error 1: 'no such column: c.TokenCustomerId'.
```

### Further technical details

Used packages:
Microsoft.EntityFrameworkCore.Sqlite 3.1.3
Microsoft.EntityFrameworkCore.Design 3.1.3

Target framework: NET Core 3.1
Database provider: Microsoft.EntityFrameworkCore.Sqlite
The same result is obtained with Pomelo.EntityFrameworkCore.MySql

**Comment by smitpatel** [comment]
Since Token uses composite key, EF Core conventions did not identify correct FK values for `Token` navigation and create navigation properties in shadow state which did not match the view in database. Configure the relationship manually in OnModelCreating like this to match the model with database.
```C#
modelBuilder.Entity<CustomerView>().HasOne(e => e.Token).WithOne().HasForeignKey<CustomerView>(e => new { e.CustomerId, e.TokenId });
```

**Comment by Asier-Villanueva** [comment]
> Since Token uses composite key, EF Core conventions did not identify correct FK values for `Token` navigation and create navigation properties in shadow state which did not match the view in database. Configure the relationship manually in OnModelCreating like this to match the model with database.
> 
> ```cs
> modelBuilder.Entity<CustomerView>().HasOne(e => e.Token).WithOne().HasForeignKey<CustomerView>(e => new { e.CustomerId, e.TokenId });
> ```

Ok. Thanks. It works well.
