### ISSUE TITLE
Can't identify problem

### ISSUE THREAD

**Issue by TehWardy** [dotnet/efcore#20872]
Is there any way this can be improved?

```
System.InvalidOperationException: A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext, however instance members are not guaranteed to be thread safe. This could also be caused by a nested query being evaluated on the client, if this is the case rewrite the query avoiding nested invocations.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
Exception thrown: 'System.InvalidOperationException' in Microsoft.EntityFrameworkCore.dll
```

I'm more than happy to accept that this is my problem to solve but I can't figure out where to be gin looking from this information.

Do you guys have any recommendations on this one?

**Comment by TehWardy** [comment]
Ok I figured it out.
