### ISSUE TITLE
GroupBy causes exception

### ISSUE THREAD

**Issue by DenisMayorko** [dotnet/efcore#20887]
"Group" operation throws error with list preselect. It happends both at anonymous type or created dto. 

We have library that handled entities after our select operation to dto by applying its own pagination, group, sort and select, but now group causes error.

I don't see any explanation why it can't be translated to sql and didn't find any same created issues.

### Steps to reproduce

``` C#
namespace Test
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var context = new ModuleDbContext(new DbContextOptionsBuilder<ModuleDbContext>()
               .UseNpgsql("Host=localhost;Port=5432;Database=sandBox")
               .Options);
            var users = context.Entities.Include(x => x.List)
                .Select(x => new { x.Id, x.List }) //List causes error
                .GroupBy(x => x.Id, (x, y) => new { x })
                .ToList(); //error throws here
        }
    }

    public class ModuleDbContext : DbContext
    {
        public ModuleDbContext(DbContextOptions<ModuleDbContext> options) : base(options)
        {
        }

        public DbSet<Entity> Entities { get; set; }
        public DbSet<ListEntity> ListEntities { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ListEntity>().HasOne(x => x.Entity).WithMany(x => x.List);
        }
    }

    public class Entity
    {
        [Key]
        public int Id { get; set; }
        public List<ListEntity> List { get; set; }
    }
    public class ListEntity
    {
        [Key]
        public int Id { get; set; }
        public Entity Entity { get; set; }
    }
}
```
### Exception

- Npgsql

```
System.InvalidCastException
  HResult=0x80004002
  Сообщение = Unable to cast object of type 'Microsoft.EntityFrameworkCore.Query.SqlExpressions.ColumnExpression' to type 'System.Linq.Expressions.ConstantExpression'.
  Источник = Microsoft.EntityFrameworkCore.Relational
  Трассировка стека:
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.RelationalProjectionBindingRemovingExpressionVisitor.GetProjectionIndex(ProjectionBindingExpression projectionBindingExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.RelationalProjectionBindingRemovingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.RelationalProjectionBindingRemovingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions(ExpressionVisitor visitor, BlockExpression block)
   at System.Linq.Expressions.ExpressionVisitor.VisitBlock(BlockExpression node)
   at System.Linq.Expressions.BlockExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.RelationalProjectionBindingRemovingExpressionVisitor.Visit(Expression node, IReadOnlyList`1& projectionColumns)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.VisitShapedQueryExpression(ShapedQueryExpression shapedQueryExpression)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Test.Program.<Main>d__0.MoveNext() in E:\repos\Athena.Test\Test\Test\Program.cs:line 21
```

- InMemory
```
System.InvalidCastException
  HResult=0x80004002
  Сообщение = Unable to cast object of type 'System.Linq.Expressions.MethodCallExpression3' to type 'System.Linq.Expressions.ConstantExpression'.
  Источник = Microsoft.EntityFrameworkCore.InMemory
  Трассировка стека:
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.InMemoryProjectionBindingRemovingExpressionVisitor.GetProjectionIndex(InMemoryQueryExpression queryExpression, ProjectionBindingExpression projectionBindingExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.InMemoryProjectionBindingRemovingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.InMemoryProjectionBindingRemovingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions(ExpressionVisitor visitor, BlockExpression block)
   at System.Linq.Expressions.ExpressionVisitor.VisitBlock(BlockExpression node)
   at System.Linq.Expressions.BlockExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.VisitShapedQueryExpression(ShapedQueryExpression shapedQueryExpression)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Test.Program.<Main>d__0.MoveNext() in E:\repos\Athena.Test\Test\Test\Program.cs:line 21
```

### Further technical details

EF Core version: 3.0+ (also tested with 5.0 preview)
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL (also Microsoft.EntityFrameworkCore.InMemory, but another exception)
Target framework: .NET Core 3.1 (also tested with 5.0 preview)
Operating system: Windows 10
IDE: Visual Studio Community 2019 16.5.4, 16.6.6 Preview 6

**Comment by DenisMayorko** [comment]
[Test project](https://github.com/DenisMayorko/efcoregroupissue) to reproduce

**Comment by smitpatel** [comment]
Duplicate of #19929

**Comment by powermetal63** [comment]
@smitpatel Here

    .GroupBy(x => x.Id, (x, y) => new { x })

`x` in the projection `new { x }` is the grouping `Key`, hence I don't think this falls into #19929 ("Support GroupBy when it is final operator"), but translation bug - `GroupBy` selecting key / aggregates is supposed to be supported. There are no navigation properties or correlated collections involved in the grouping result projection, just the grouping source contains correlated collection projection.

There is similar (same) issue posted on StackOverflow - [GroupBy with after projection to domain model without .ToList()](https://stackoverflow.com/questions/61821437/groupby-with-after-projection-to-domain-model-without-tolist).

I'm not sure if resolving #19929 will resolve this or not, so consider reopening this as a bug.

**Comment by smitpatel** [comment]
`x.List` introduces client eval causing binding error during GroupBy. Easy work-around would be to remove `x.List` from query which is not used in GroupBy or final result.

**Comment by DenisMayorko** [comment]
> `x.List` introduces client eval causing binding error during GroupBy. Easy work-around would be to remove `x.List` from query which is not used in GroupBy or final result.

"GroupBy" may be used or not. It depending on parameters coming to the controller and handles with library DevExtreme. 

The current workaround is the creation of two methods: with and without group.  But I think it is obviously that it should be just ignored without manual handling

**Comment by snieking** [comment]
I ran into a very similar issue, and here is a sample app that reproduces it:
https://github.com/snieking/DevExpress-DataSourceLoader-issue
