### ISSUE TITLE
LINQ to SQL Query Type casting error

### ISSUE THREAD

**Issue by lano-lee** [dotnet/efcore#20942]
ex1 )
```
data.create_dt.AddDays(data.period)
```
to Sql Query
```
DATE_ADD(`s`.`create_dt`, INTERVAL CAST(CAST(`s`.`period` AS double) AS int) day)
```

ex2 ) 
```
var source = from a in context.TableA
                         join b in context.TableB
                         on a.key equals b.key into table
                         from view in table.DefaultIfEmpty()
                         select new
                         {
                             value1= (view == null) ? 1 : view.value1,
                             value2 = (view == null) ? 0 : view.value2
                         };
```

to Sql Query
```
CASE
    WHEN `t`.`value1` IS NULL THEN 1
    ELSE CAST(`t`.`value1` AS int)
END AS `value1`, CASE
    WHEN `t`.`value2` IS NULL THEN 0
    ELSE CAST(`t`.`value2` AS int)
END AS `value2`, CASE
```

mysql 5.7.28 version not supported cast as int, double
I want cast as signed and cast as decimal

Question1) This is efcore bug? database provider bug?
Question2) If efcore bug, How to translate type setting?

I am not good at English, so it is a poor sentence, but please understand it.

Further technical details
EF Core version: 3.1.4
Database provider: ( MySql.Data.EntityFrameworkCore)
Target framework: ( .NET Core 3.1)
Operating system: Windows
IDE: ( Visual Studio 2019 )

**Comment by roji** [comment]
What exactly isn't working, is it your first code sample or your second? What is the type of value1 and value2 in the second example? Can you post the actual error message?

Note that we do not maintain MySql.Data.EntityFrameworkCore - there's a good chance this will have to be reported to that project.

**Comment by lano-lee** [comment]
> What exactly isn't working, is it your first code sample or your second? What is the type of value1 and value2 in the second example? Can you post the actual error message?
> 
> Note that we do not maintain MySql.Data.EntityFrameworkCore - there's a good chance this will have to be reported to that project.

Both not working
value1, value2 type byte

Error Message
```
exception: MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'double) AS int) day) > '2020-05-13 07:52:11.296805')) OR (`s`.`period` <= 0)) AN' at line 8
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at MySql.Data.EntityFrameworkCore.Storage.Internal.MySQLExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
```

**Comment by roji** [comment]
Yeah, you will have to file these issues with MySql.Data.EntityFrameworkCore - this is an issue with their specific translation.

**Comment by ajcvickers** [comment]
@lano-lee Another option is the [Pomelo MySQL provider](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql)--many people have had good experiences with it.
