### ISSUE TITLE
Unable to open database file for WPF Autostart app

### ISSUE THREAD

**Issue by VarunSaiTeja** [dotnet/efcore#20998]
When AutoStart with windows feature enabled for my wpf app.
App was crashing on windows start, If I manually open app everything working fine.
The error I am facing was **Unable to open Database File** 
SqliteErrorCode:14

Got Exceptions? Include both the message and the stack trace
```

Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at ProSyncer.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e) in C:\Users\Varun\Coding\Work\Rishav\ProSyncer\ProSyncer\MainWindow.xaml.cs:line 215
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Microsoft.Data.Sqlite.Core.3.1.3
Target framework: .NET Framework 4.7.8
Operating system: Windows 10 (1909)

**Comment by ajcvickers** [comment]
@VarunSaiTeja What is your connection string?

**Comment by VarunSaiTeja** [comment]
`protected override void OnConfiguring(DbContextOptionsBuilder options) => options.UseSqlite($"Filename={"UserData.db"}");
`

**Comment by VarunSaiTeja** [comment]
> @VarunSaiTeja What is your connection string?

`protected override void OnConfiguring(DbContextOptionsBuilder options) => options.UseSqlite($"Filename={"UserData.db"}");
`

**Comment by ajcvickers** [comment]
@VarunSaiTeja By default, SQLite will try to open the file "UserData.db" in the current working directory. My guess is that working directory is different when using this mechanism to start the application. You'll probably need to find out what the working directory is when your app starts and then use an appropriate path to the file in the connection string.

**Comment by VarunSaiTeja** [comment]
The working directory when our app starts is system32 folder. That's why I am getting an error.
Now I had specified full path of the database, so no problem.

**Issue resolved now**
