### ISSUE TITLE
A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.

### ISSUE THREAD

**Issue by ibneajmal77** [dotnet/efcore#21027]
The error is in the EF Core Cosmos package
When i register the Cosmos Db instance as singleton in startup class. I am receiving the bellow error. 
This error happens when simultaneous requests are send to the query to the Cosmos DB.
I have tried it by registering the Cosmos Db instance as Scoped. But the error is same. Can anyone give some idea about it.

**A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.**

**Comment by ibneajmal77** [comment]
Stack Trace  

 at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()\r\n   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()\r\n   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)\r\n   at Aepistle.Repositories.GenericRepository.Repository`1.GetFirstAsync(Expression`1 filter, Func`2 orderBy, String includeProperties) in D:\\UPWORK\\Upwork2020\\aepistle\\Aepistle.Repositories\\GenericRepository\\Repository.cs:line 210\r\n   at Aepistle.Service.Identity.CustomUserStore.FindByEmailAsync(String normalizedEmail, CancellationToken cancellationToken) in D:\\UPWORK\\Upwork2020\\aepistle\\Aepistle.Service\\Identity\\CustomUserStore.cs:line 541\r\n   at Microsoft.AspNetCore.Identity.UserManager`1.FindByEmailAsync(String email)\r\n   at Aepistle.API.Controllers.MessageController.LoadFriends() in D:\\UPWORK\\Upwork2020\\aepistle\\Aepistle.API\\Controllers\\MessageController.cs:line 78

**Comment by ibneajmal77** [comment]
Stack trace

   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()\r\n   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()\r\n   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)\r\n   at App.Repositories.GenericRepository.Repository`1.GetFirstAsync(Expression`1 filter, Func`2 orderBy, String includeProperties) in D:\\App.API\\App.Repositories\\GenericRepository\\Repository.cs:line 209\r\n   at App.API.Identity.CustomUserStore.FindByEmailAsync(String normalizedEmail, CancellationToken cancellationToken) in D:\\App.API\\Identity\\CustomUserStore.cs:line 497\r\n   at Microsoft.AspNetCore.Identity.UserManager`1.FindByEmailAsync(String email)\r\n   at App.API.Controllers.MessageController.LoadFriends() in D:\\App.API\\Controllers\\MessageController.cs:line 67

**Comment by roji** [comment]
> When i register the Cosmos Db instance as singleton in startup class

That does not look like a good idea - by design, a DbContext instance cannot be used concurrently, which is why it's registered as Scoped by default. Take a look [at the docs around DbContext thread-safety](https://docs.microsoft.com/en-us/ef/core/miscellaneous/configuring-dbcontext#avoiding-dbcontext-threading-issues).

Even when a DbContext is registered as Scoped, it's still possible to accidentally use the same instance from multiple threads; take a careful look at your code and make sure you're not saving a DbContext and possibly unintentionally reusing it later in a concurrent manner. To help any further, we're going to need to see a runnable, small code sample which produces the error.

**Comment by ibneajmal77** [comment]
Hi,
This solves my issue. Thanks for explanation.
