### ISSUE TITLE
DbContext.Database.Migrate does not create a database if the connection-string is to LocalDB.

### ISSUE THREAD

**Issue by HansKindberg** [dotnet/efcore#21237]
DbContext.Database.Migrate does not create a database if the connection-string is to LocalDB.

**To reproduce**

No database or database-file exists before running the code.

```
<PackageReference Include="Microsoft.Data.SqlClient" Version="1.1.3" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.5" />
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.5" />
```

DbContext
```C#
public class DatabaseContext : DbContext
{
	public DatabaseContext(DbContextOptions<DatabaseContext> options) : base(options) { }
}
```

```C#
const string dataDirectoryPath = @"C:\ad52fa9b-0a55-4b75-ae12-158efe91ab4a\";
const string databaseServer = "DB-SERVER";
AppDomain.CurrentDomain.SetData("DataDirectory", dataDirectoryPath);

// This works
var services = new ServiceCollection();
services.AddDbContext<DatabaseContext>(builder => builder.UseSqlite("Data Source=|DataDirectory|SQLite-1.db"));
using(var scope = services.BuildServiceProvider().CreateScope())
{
	var databaseContext = scope.ServiceProvider.GetRequiredService<DatabaseContext>();
	databaseContext.Database.Migrate();
}

// This works
services = new ServiceCollection();
services.AddDbContext<DatabaseContext>(builder => builder.UseSqlite($"Data Source={dataDirectoryPath}SQLite-2.db"));
using (var scope = services.BuildServiceProvider().CreateScope())
{
	var databaseContext = scope.ServiceProvider.GetRequiredService<DatabaseContext>();
	databaseContext.Database.Migrate();
}

// This works if you have access on the DB-SERVER, eg "sysadmin".
services = new ServiceCollection();
services.AddDbContext<DatabaseContext>(builder => builder.UseSqlServer($"Server={databaseServer};Database=My-Database;Integrated Security=True;MultipleActiveResultSets=True"));
using (var scope = services.BuildServiceProvider().CreateScope())
{
	var databaseContext = scope.ServiceProvider.GetRequiredService<DatabaseContext>();
	databaseContext.Database.Migrate();
}

// This does NOT work
services = new ServiceCollection();
services.AddDbContext<DatabaseContext>(builder => builder.UseSqlServer("Server=(LocalDB)\\MSSQLLocalDB;AttachDbFileName=|DataDirectory|My-Database-1.mdf;Integrated Security=True;MultipleActiveResultSets=True"));
using (var scope = services.BuildServiceProvider().CreateScope())
{
	var databaseContext = scope.ServiceProvider.GetRequiredService<DatabaseContext>();
	databaseContext.Database.Migrate();
}

// This does NOT work
services = new ServiceCollection();
services.AddDbContext<DatabaseContext>(builder => builder.UseSqlServer($"Server=(LocalDB)\\MSSQLLocalDB;AttachDbFileName={dataDirectoryPath}My-Database-2.mdf;Integrated Security=True;MultipleActiveResultSets=True"));
using (var scope = services.BuildServiceProvider().CreateScope())
{
	var databaseContext = scope.ServiceProvider.GetRequiredService<DatabaseContext>();
	databaseContext.Database.Migrate();
}
```

**Comment by ajcvickers** [comment]
@HansKindberg Can you be more specific by what you mean, "does not create a database?" Is an exception thrown? Also, what OS are you on and what version of LocalDb are you using?

**Comment by HansKindberg** [comment]
Hi

Thank you for your answer. My environment:

- Windows 10 Enterprise version 1903
- Visual Studio Enterprise 2019 version 16.6.2
- SQL Server Data Tools 16.0.62006.03190
- LocalDB version 13.0.1601.5 (ran the sqllocaldb command at a command-prompt)

When I run DbContext.Database.Migrate an exception is thrown:

```
Microsoft.Data.SqlClient.SqlException: An attempt to attach an auto-named database for file C:\dotnet-efcore-issue-21237\Test\Data\LocalDB-1.mdf failed. A database with the same name exists, or specified file cannot be opened, or it is located on UNC share.
    at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation, Func`2 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists(Boolean retryOnNotExists)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
```

The same exception is thrown if I run DbContext.Database.EnsureCreated.

Have setup a small test-project for it: https://github.com/HansKindberg-Lab/dotnet-efcore-issue-21237/

I expect it to behave like Sqlite. Migrate/EnsureCreated should create the database-file (mdf) if it does not exist.

Regards Hans

**Comment by HansKindberg** [comment]
Hi again

After reflecting over the exception-message: "An attempt to attach an **auto-named**..."

I realized, maybe I need "Database" or "Initial Catalog" in my connection-string? If I add "Database" or "Initial Catalog" in my connection-strings it works. https://github.com/HansKindberg-Lab/dotnet-efcore-issue-21237/blob/Fix/Test/Test.cs#L137

Sorry for bothering you :)

Sometimes when you must start to explain things you come up to the answer yourself.

If this is the way to do it you can close this issue.

Regards Hans
