### ISSUE TITLE
The entities are saved to database in alphabetical order, which should NOT happen!

### ISSUE THREAD

**Issue by vivekkhatri** [dotnet/efcore#21365]
I have a parent table and a child table (defined foreign key in SQL Server database).
When I try to insert a record, first in the parent table and then in the child table and then in the end, I call `context.SaveChanges()`.

EF Core will insert the list of entities (parent and child) according to the alphabetical order of the entities' names. So if the child entity's name comes BEFORE the parent entity alphabetically, then it will try to insert the child record first and since I have foreign key is implemented in SQL Server, it will fail because the parent record does not exist yet.

### Steps to reproduce
``` C#
BonnieContext context = new BonnieContext();

// Case 1:
// This works perfectly because alphabetically,
// the parent table comes BEFORE the child table

AParent aParent = new AParent();
aParent.AParentId = Guid.NewGuid();
aParent.Title = "AParent Title";
context.AParent.Add(aParent);

BChild bChild = new BChild();
bChild.BChildId = Guid.NewGuid();
bChild.AParentId = aParent.AParentId;
bChild.Title = "BChild Title";
context.BChild.Add(bChild);

context.SaveChanges();


// Case 2:
// This WON'T work because alphabetically,
// the parent table comes AFTER the child table

BParent bParent = new BParent();
bParent.BParentId = Guid.NewGuid();
bParent.Title = "BParent Title";
context.BParent.Add(bParent);

AChild aChild = new AChild();
aChild.AChildId = Guid.NewGuid();
aChild.BParentId = bParent.BParentId;
aChild.Title = "AChild Title";
context.AChild.Add(aChild);

context.SaveChanges();

// Case 2 will work only if I call the context.SaveChanges()
// right after inserting a record in the parent table
// and THEN insert a record in the child table
```

Exceptions Message:
The INSERT statement conflicted with the FOREIGN KEY constraint "FK_AChild_BParent". The conflict occurred in database "bonnie_dev", table "dbo.BParent", column 'BParentId'.
The statement has been terminated.

Exception StackTrace: 
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)

### Further technical details
EF Core version: Microsoft.EntityFrameworkCore 3.1.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10 Home
IDE: Visual Studio 2019 Community Edition 16.6.2

**Comment by AndriySvyryd** [comment]
Did you configure the "FK_AChild_BParent" foreign ket in `OnModelCreating`?

Can you provide a small runnable project that shows the issue?

**Comment by vivekkhatri** [comment]
Hey, I just noticed the `OnModelCreating()` was removed from the project. After adding it, it worked as expected.
