### ISSUE TITLE
Exception when executing split query: "There is already an open DataReader associated with this Connection which must be closed first."

### ISSUE THREAD

**Issue by jorgestg** [dotnet/efcore#21417]
I get a `System.InvalidOperationException` when executing a rather simple looking split query. I only get this exception when using SQL Server, it works just fine on SQLite

### Steps to reproduce
Executing this query:
```C#
return _context.Set<Order>()
    .Include(o => o.Items)
    .AsSplitQuery()
    .FirstOrDefaultAsync(o => o.Id == orderId);
```
with the following schema

```C#
    public class Order
    {
        private readonly List<StatusChange> _statusChanges = new List<StatusChange>();
        private readonly List<OrderItem> _items = new List<OrderItem>();

        private Order()
        {
            // Required by EF
        }

       // Other constructors...

        public int Id { get; private set; }
        public DateTimeOffset CreatedOn { get; private set; }
        public OrderCustomerInfo CustomerInfo { get; private set; }
        public OrderStatus CurrentStatus { get; private set; }
        public string Provider { get; }
        public int Total { get; private set; }
        public string Notes { get; set; }
        public string AttachmentUrl { get; set; }

        public IEnumerable<OrderItem> Items => _items;
        public IEnumerable<StatusChange> StatusChanges => _statusChanges;

        // Collection manipulation-related methods...
    }
```
Note: `Order` owns `OrderCustomerInfo`
```C#
    public class OrderCustomerInfo
    {
        private OrderCustomerInfo()
        {
            // Required by EF
        }

       // Other constructors...

        public string Name { get; private set; }
        public string PhoneNumber { get; private set; }
        public string Address { get; private set; }
        public double Latitude { get; private set; }
        public double Longitude { get; private set; }
        public string BusinessName { get; private set; }
        public string Ruc { get; private set; }
    }
```
```C#
    public class OrderItem
    {   
        private OrderItem()
        {
            // Required by EF
        }
        
       // Other constructors...

        public int Id { get; private set; }
        public string Name { get; set; }
        public double Quantity { get; set; }
    }
```

Logger output:
```
Executed DbCommand (204ms) [Parameters=[@__orderId_0='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
      SELECT [t].[Id], [t].[AttachmentUrl], [t].[CreatedOn], [t].[CurrentStatus], [t].[Notes], [t].[Provider], [t].[Total], [t].[CustomerInfo_Address], [t].[CustomerInfo_BusinessName], [t].[CustomerInfo_Latitude], [t].[CustomerInfo_Longitude
], [t].[CustomerInfo_Name], [t].[CustomerInfo_PhoneNumber], [t].[CustomerInfo_Ruc]
      FROM (
          SELECT TOP(1) [o].[Id], [o].[AttachmentUrl], [o].[CreatedOn], [o].[CurrentStatus], [o].[Notes], [o].[Provider], [o].[Total], [o].[CustomerInfo_Address], [o].[CustomerInfo_BusinessName], [o].[CustomerInfo_Latitude], [o].[CustomerInf
o_Longitude], [o].[CustomerInfo_Name], [o].[CustomerInfo_PhoneNumber], [o].[CustomerInfo_Ruc]
          FROM [Order] AS [o]
          WHERE [o].[Id] = @__orderId_0
      ) AS [t]
      ORDER BY [t].[Id]
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (1ms) [Parameters=[@__orderId_0='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
      SELECT [o0].[Id], [o0].[Name], [o0].[OrderId], [o0].[Quantity], [t].[Id]
      FROM (
          SELECT TOP(1) [o].[Id], [o].[AttachmentUrl], [o].[CreatedOn], [o].[CurrentStatus], [o].[Notes], [o].[Provider], [o].[Total]
          FROM [Order] AS [o]
          WHERE [o].[Id] = @__orderId_0
      ) AS [t]
      INNER JOIN [OrderItem] AS [o0] ON [t].[Id] = [o0].[OrderId]
      ORDER BY [t].[Id]
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'Core.Data.AppDbContext'.
      System.InvalidOperationException: There is already an open DataReader associated with this Connection which must be closed first.
         at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
         at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
         at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location where exception was thrown ---
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.<>c__DisplayClass62_0`2.<<PopulateSplitIncludeCollectionAsync>g__InitializeReaderAsync|0>d.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.PopulateSplitIncludeCollectionAsync[TIncludingEntity,TIncludedEntity](Int32 collectionId, RelationalQueryContex
t queryContext, IExecutionStrategy executionStrategy, SplitQueryResultCoordinator resultCoordinator, RelationalCommandCache relationalCommandCache, Func`3 childIdentifier, IReadOnlyList`1 identifierValueComparers, Func`5 innerShaper, Func`4
relatedDataLoaders, INavigation inverseNavigation, Action`2 fixup, Boolean trackingQuery)
         at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.TaskAwaiter(Task[] tasks)
         at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
System.InvalidOperationException: There is already an open DataReader associated with this Connection which must be closed first.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.<>c__DisplayClass62_0`2.<<PopulateSplitIncludeCollectionAsync>g__InitializeReaderAsync|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.PopulateSplitIncludeCollectionAsync[TIncludingEntity,TIncludedEntity](Int32 collectionId, RelationalQueryContext quer
yContext, IExecutionStrategy executionStrategy, SplitQueryResultCoordinator resultCoordinator, RelationalCommandCache relationalCommandCache, Func`3 childIdentifier, IReadOnlyList`1 identifierValueComparers, Func`5 innerShaper, Func`4 relate
dDataLoaders, INavigation inverseNavigation, Action`2 fixup, Boolean trackingQuery)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.TaskAwaiter(Task[] tasks)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

```

### Further technical details

EF Core version: 5.0.0-preview.6.20312.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: 3.1.300
Operating system: Windows 10 Pro
IDE: Running on the Terminal

**Comment by smitpatel** [comment]
Since you are trying to run multiple queries at the same time, you must enable MARS in SqlServer.

**Comment by jorgestg** [comment]
Well, that was easy. Thank you so much! :)

**Comment by smitpatel** [comment]
Filed #21420 to provide user hook to let us know if MARS is on or off.

**Comment by jorgestg** [comment]
FWIW I just appended `;MultipleActiveResultSets=true` to my connection string and it just worked (on Azure SQL)

**Comment by smitpatel** [comment]
In preview8, we had added automatic detection of MARS in SqlServer provider. So if MARS is not enabled then query will buffer the DataReader before opening another one to give results without MARS too.
