### ISSUE TITLE
[EF Core 3.1.4 migrations] ALTER TABLE DROP COLUMN failed because [column name] is the only data column in table [table name]

### ISSUE THREAD

**Issue by quantranld** [dotnet/efcore#21410]
Hi team,

I have a following table which has only two columns
``` c#
public class CustomerVendorBase
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
    }
```
I got error when tried to add more columns to the above table
``` c#
public abstract class CustomerVendorBase
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string FullName { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public bool IsDeleted { get; set; }
        public CustomerVendorType CVType { get; set; }
    }
```

``` bash
Applying migration '20200625033949_CustomerVendorSetup'.
Failed executing DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
DECLARE @var1 sysname;
SELECT @var1 = [d].[name]
FROM [sys].[default_constraints] [d]
INNER JOIN [sys].[columns] [c] ON [d].[parent_column_id] = [c].[column_id] AND [d].[parent_object_id] = [c].[object_id]
WHERE ([d].[parent_object_id] = OBJECT_ID(N'[Customers]') AND [c].[name] = N'Name');
IF @var1 IS NOT NULL EXEC(N'ALTER TABLE [Customers] DROP CONSTRAINT [' + @var1 + '];');
ALTER TABLE [Customers] DROP COLUMN [Name];
Microsoft.Data.SqlClient.SqlException (0x80131904): ALTER TABLE DROP COLUMN failed because 'Name' is the only data column in table 'Customers'. A table must have at least one data column.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:618f82b2-ac13-4f7c-a708-b28f03d0c264
Error Number:4923,State:1,Class:16
ALTER TABLE DROP COLUMN failed because 'Name' is the only data column in table 'Customers'. A table must have at least one data column.
```

### what I got from the error
Because EF Core dropped 2 existing columns, then it tried to created the columns, but turned out after removing the 2 columns made the empty table (table without any columns), please find the generated code below:

``` c#
protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_Customers",
                table: "Customers");

            migrationBuilder.DropColumn(
                name: "CustomerId",
                table: "Customers");

            migrationBuilder.DropColumn(
                name: "Name",
                table: "Customers");

            migrationBuilder.RenameTable(
                name: "Customers",
                newName: "CustomersVendors");

            migrationBuilder.AddColumn<int>(
                name: "Id",
                table: "CustomersVendors",
                nullable: false,
                defaultValue: 0)
                .Annotation("SqlServer:Identity", "1, 1");

            migrationBuilder.AddColumn<string>(
                name: "Address",
                table: "CustomersVendors",
                nullable: true);

            migrationBuilder.AddColumn<byte>(
                name: "CVType",
                table: "CustomersVendors",
                nullable: false,
                defaultValue: (byte)0);

            migrationBuilder.AddColumn<string>(
                name: "FullName",
                table: "CustomersVendors",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "CustomersVendors",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<string>(
                name: "PhoneNumber",
                table: "CustomersVendors",
                nullable: true);

            migrationBuilder.AddPrimaryKey(
                name: "PK_CustomersVendors",
                table: "CustomersVendors",
                column: "Id");
        }
```

It's expected that EF Core can handle this case (It's very likely that it might happen in the very first steps of the development)
I could work around this issue by manually adding 1 more column to the table.

### Further technical details

EF Core version: 3.1.4
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.1)
Operating system:
IDE: (e.g. Visual Studio 2019 16.6.2)

Thanks for your amazing work on EF Core, I'm looking forward to hearing from the team soon,
Quan Tran

**Comment by ajcvickers** [comment]
@quantranld What version of SQL Server are you using?

**Comment by quantranld** [comment]
@ajcvickers Hi thanks for your response.
I was using MSSQL 2012 - 11.0.2100.60
Windows Version	10.0.19041 Build 19041

**Comment by ajcvickers** [comment]
After some investigation, it seems this is a limitation of SQL Server. Tables with a single key column are allowed...but not when it is the result of ALTER TABLE. 🤷 This should probably be filed as a bug against SQL Server. The workaround here is to re-order the generated migration code to not drop the old column until after the new columns have been created.

**Comment by roji** [comment]
Another one for my little black book...

**Comment by quantranld** [comment]
Thanks @ajcvickers. Agree with you that this is SQL Server's limitation. It's really great if EF Core can do the thing and make it transparent to the developer/user, maybe it does the deletion as the last thing in the Up process.

**Comment by apostnov** [comment]
Stucked with this also. Consider to reopen please.
