### ISSUE TITLE
Navigation Field Not Showing up In Model - could this cause a "read only" exception?

### ISSUE THREAD

**Issue by mlenart1010** [dotnet/efcore#21432]
I have the following code:

```
    public class ArticleBank : Entity, IAggregateRoot
    {
        private readonly List<ArticleTag> _articleTags;
        public IEnumerable<ArticleTag> ArticleTags => _articleTags.AsReadOnly();
        private readonly List<Article> _articles;
        public IEnumerable<Article> Articles => _articles.AsReadOnly();
        private readonly List<ArticleSource> _articleSources;

        public IEnumerable<ArticleSource> Sources => _articleSources.AsReadOnly();
        public ArticleBank()
        {
            _articles = new List<Article>();
            _articleTags = new List<ArticleTag>();
            _articleSources = new List<ArticleSource>();
        }
   }

```
In my DBContext.OnModelCreating() I have:

```
            modelBuilder.Entity<ArticleBank>(ab =>
            {
                ab.OwnsMany(ab => ab.ArticleTags, at =>
                {
                    at.WithOwner();
                    at.Property<DateTime>("CreatedDate");
                    at.Property<DateTime>("UpdatedDate");
                    at.ToTable("ArticleBankTags");
                });
            });

            modelBuilder.Entity<ArticleBank>(ab =>
            {
                ab.OwnsMany(ab => ab.Sources, s =>
                {
                    s.WithOwner();
                    s.Property<DateTime>("CreatedDate");
                    s.Property<DateTime>("UpdatedDate");
                    s.ToTable("ArticleBankSources");
                });
            });
```

I have a console application that attempts to query:
            var bank = articleBankContext.ArticleBanks.FirstOrDefault();

This throws an exception of:
```
System.NotSupportedException
  HResult=0x80131515
  Message=Collection is read-only.
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowNotSupportedException(ExceptionResource resource)
   at System.Collections.ObjectModel.ReadOnlyCollection`1.System.Collections.Generic.ICollection<T>.Add(T value)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrICollectionAccessor`3.Add(Object entity, Object value, Boolean forMaterialization)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.AddToCollection(INavigation navigation, InternalEntityEntry value, Boolean forMaterialization)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalMixedEntityEntry.AddToCollection(INavigation navigation, InternalEntityEntry value, Boolean forMaterialization)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.AddToCollection(InternalEntityEntry entry, INavigation navigation, InternalEntityEntry value, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.SetReferenceOrAddToCollection(InternalEntityEntry entry, INavigation navigation, InternalEntityEntry value, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.ToDependentFixup(InternalEntityEntry dependentEntry, InternalEntityEntry principalEntry, IForeignKey foreignKey, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.InitialFixup(InternalEntityEntry entry, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.TrackedFromQuery(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.TrackedFromQuery(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.MarkUnchangedFromQuery()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTrackingFromQuery(IEntityType baseEntityType, Object entity, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.QueryContext.StartTracking(IEntityType entityType, Object entity, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.CustomShaperCompilingExpressionVisitor.<PopulateIncludeCollection>g__ProcessCurrentElementRow|9_0[TIncludingEntity,TIncludedEntity](<>c__DisplayClass9_0`2& )
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.CustomShaperCompilingExpressionVisitor.PopulateIncludeCollection[TIncludingEntity,TIncludedEntity](Int32 collectionId, QueryContext queryContext, DbDataReader dbDataReader, ResultCoordinator resultCoordinator, Func`3 parentIdentifier, Func`3 outerIdentifier, Func`3 selfIdentifier, Func`5 innerShaper, INavigation inverseNavigation, Action`2 fixup, Boolean trackingQuery)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at ArticleBankMgmt.Infrastructure.Program.QueryArticleBank() in C:\Users\m_len\source\repos\JobAssist\src\Services\ArticleBankMgmt\ArticleBankMgmt.Infrastructure\Program.cs:line 74
   at ArticleBankMgmt.Infrastructure.Program.Main(String[] args) in C:\Users\m_len\source\repos\JobAssist\src\Services\ArticleBankMgmt\ArticleBankMgmt.Infrastructure\Program.cs:line 22

  This exception was originally thrown at this call stack:
    [External Code]
    ArticleBankMgmt.Infrastructure.Program.QueryArticleBank() in Program.cs
    ArticleBankMgmt.Infrastructure.Program.Main(string[]) in Program.cs
```

When I look at the DBContext.Model for ArticleBank.Navigations I see during execution:

```
EntityType: ArticleBank\r\n
    Navigations: \r\n
      Articles (_articles, IEnumerable<Article>) Collection ToDependent Article\r\n
      ArticleTags (_articleTags, IEnumerable<ArticleTag>) Collection ToDependent ArticleBank.ArticleTags#ArticleTag\r\n
        Annotations: \r\n
          EagerLoaded: True\r\n
      **Sources (no field,** IEnumerable<ArticleSource>) Collection ToDependent ArticleBank.Sources#ArticleSource\r\n
        Annotations: \r\n
          EagerLoaded: True\r\n
    Keys: \r\n
      Id PK\r\n
    Annotations: \r\n
      ConstructorBinding: Microsoft.EntityFrameworkCore.Metadata.ConstructorBinding\r\n
      Relational:TableName: ArticleBanks\r\n
```

The question is: For Sources there is no "field" however in my code configures it the same way as Tags.  Could this be the cause of the exception?

### Further technical details

EF Core version: 3.1.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NetCore 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.3

**Comment by smitpatel** [comment]
Other field `_articles` is same as the navigation property name `Articles` lower cased and prefixed with "_".
`Sources` and `_articleSources` does not match that convention.

**Comment by mlenart1010** [comment]
Oh  my gosh! I spent two hours looking and debugging that! It solved the problem.  Thank you so much.
