### ISSUE TITLE
Query: DataReader leaking with split query

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#21441]
I changed the initial loading methods used by the GraphUpdateTests to use split queries since they perform a lot of collection Includes. Initially I got MARS errors, but after forcing MARS on for the connection I start seeing many tests failing with:

```
Microsoft.EntityFrameworkCore.GraphUpdatesSqlServerTest+Identity.Optional_One_to_one_relationships_are_one_to_one(deleteOrphansTiming: Never)

Microsoft.Data.SqlClient.SqlException : New transaction is not allowed because there are other threads running in the session.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.TdsParser.TdsExecuteTransactionManagerRequest(Byte[] buffer, TransactionManagerRequestType request, String transactionName, TransactionManagerIsolationLevel isoLevel, Int32 timeout, SqlInternalTransaction transaction, TdsParserStateObject stateObj, Boolean isDelegateControlRequest)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.ExecuteTransactionYukon(TransactionRequest transactionRequest, String transactionName, IsolationLevel iso, SqlInternalTransaction internalTransaction, Boolean isDelegateControlRequest)
   at Microsoft.Data.SqlClient.SqlInternalConnection.BeginSqlTransaction(IsolationLevel iso, String transactionName, Boolean shouldReconnect)
   at Microsoft.Data.SqlClient.SqlConnection.BeginTransaction(IsolationLevel iso, String transactionName)
   at Microsoft.Data.SqlClient.SqlConnection.BeginDbTransaction(IsolationLevel isolationLevel)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction(IsolationLevel isolationLevel) in C:\dotnet\efcore\src\EFCore.Relational\Storage\RelationalConnection.cs:line 300
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction() in C:\dotnet\efcore\src\EFCore.Relational\Storage\RelationalConnection.cs:line 264
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.BeginTransaction() in C:\dotnet\efcore\src\EFCore\Infrastructure\DatabaseFacade.cs:line 158
   at Microsoft.EntityFrameworkCore.TestUtilities.TestHelpers.<>c__DisplayClass36_0`1.<ExecuteWithStrategyInTransaction>b__0(TContext context) in C:\dotnet\efcore\test\EFCore.Specification.Tests\TestUtilities\TestHelpers.cs:line 254
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__2`1.<Execute>b__2_0(<>f__AnonymousType0`2 s) in C:\dotnet\efcore\src\EFCore\Storage\ExecutionStrategyExtensions.cs:line 73
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s) in C:\dotnet\efcore\src\EFCore\Storage\ExecutionStrategyExtensions.cs:line 338
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state) in C:\dotnet\efcore\src\EFCore\Storage\ExecutionStrategy.cs:line 172
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded) in C:\dotnet\efcore\src\EFCore\Storage\ExecutionStrategy.cs:line 159
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation, Func`2 verifySucceeded) in C:\dotnet\efcore\src\EFCore\Storage\ExecutionStrategyExtensions.cs:line 336
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation) in C:\dotnet\efcore\src\EFCore\Storage\ExecutionStrategyExtensions.cs:line 286
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState](IExecutionStrategy strategy, TState state, Action`1 operation) in C:\dotnet\efcore\src\EFCore\Storage\ExecutionStrategyExtensions.cs:line 70
   at Microsoft.EntityFrameworkCore.TestUtilities.TestHelpers.ExecuteWithStrategyInTransaction[TContext](Func`1 createContext, Action`2 useTransaction, Action`1 testOperation, Action`1 nestedTestOperation1, Action`1 nestedTestOperation2, Action`1 nestedTestOperation3) in C:\dotnet\efcore\test\EFCore.Specification.Tests\TestUtilities\TestHelpers.cs:line 251
   at Microsoft.EntityFrameworkCore.GraphUpdatesTestBase`1.ExecuteWithStrategyInTransaction(Action`1 testOperation, Action`1 nestedTestOperation1, Action`1 nestedTestOperation2, Action`1 nestedTestOperation3) in C:\dotnet\efcore\test\EFCore.Specification.Tests\GraphUpdates\GraphUpdatesTestBase.cs:line 2934
   at Microsoft.EntityFrameworkCore.GraphUpdatesTestBase`1.Optional_One_to_one_relationships_are_one_to_one(Nullable`1 deleteOrphansTiming) in C:\dotnet\efcore\test\EFCore.Specification.Tests\GraphUpdates\GraphUpdatesTestBaseOneToOne.cs:line 27
```

**Comment by ajcvickers** [comment]
SQLite tests still work with split queries.

**Comment by smitpatel** [comment]
MARS is required because it does not use retrying execution strategy.
cc: @AndriySvyryd

**Comment by smitpatel** [comment]
I filed #21463 for MARS & GraphUpdates test. I am closing this issue as leaking data readers so that customers can find it if they run into the issue using preview.
