### ISSUE TITLE
Processing of the LINQ expression 'GroupByShaperExpression ... RelationalProjectionBindingExpressionVisitor' failed

### ISSUE THREAD

**Issue by GSPP** [dotnet/efcore#21446]
In EF Core 5 preview 6, I receive the following exception:

```
System.InvalidOperationException: Processing of the LINQ expression 'GroupByShaperExpression:
KeySelector: t.Name, 
ElementSelector:EntityShaperExpression: 
    EntityType: TestChild
    ValueBufferExpression: 
        ProjectionBindingExpression: EmptyProjectionMember
    IsNullable: False
' by 'RelationalProjectionBindingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.
    at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitNew(NewExpression newExpression)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

Model and test code:

```C#
        [TestMethod]
        public void Test()
        {
            using (var ctx = new Context())
            {
                    _ = (from c in ctx.TestChildren
                         group c by c.Name into g
                         let id = g.Min(x => x.ID) //Try to pick the first TestChild from each group
                         from c in ctx.TestChildren
                         where c.ID == id
                         select c).ToList();
                }
            }
        }

    public partial class TestChild
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }

    public partial class Context : DbContext
    {
        public Context()
        {
        }

        public Context(DbContextOptions<Context> options)
            : base(options)
        {
        }

        public virtual DbSet<TestChild> TestChildren { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("...");
            }
        }
    }
```

With this query I am trying to pick the first (or any) `TestChild` per `Name` group. I don't see a specific reason why this would not be supported. Picking the `Min(child => child.ID)` value from a grouping is supported. In the remainder of the query, only this aggregated min ID value is being used. The grouping is no longer being used. This is my attempt to work around https://github.com/dotnet/efcore/issues/12088 not having landed yet.

**Comment by TehWardy** [comment]
Seems related ...
   https://github.com/OData/WebApi/issues/2254

I don't think aggregation functions work anywhere in the Microsoft stack at the moment.
At least I can't see how.

**Comment by iozcelik** [comment]
This is an important issue. Any group by and aggregation must be work ef core 5.

**Comment by smitpatel** [comment]
Many of the aggregation patterns already work in EF Core 5.0. Even query posted in above example can be rewritten to remove let and use Select instead and it works with EF Core 5.0

**Comment by iozcelik** [comment]
I try lots of combination at ef core 5. Even simple group by not working.

**Comment by komdil** [comment]
any progress or workarround?

**Comment by smitpatel** [comment]
Generated tree
```
DbSet<Order>()
    .GroupBy(o => o.CustomerID)
    .Select(g => new { 
        g = g, 
        id = g
            .AsQueryable()
            .Min(x => x.OrderID)
     })
    .SelectMany(
        collectionSelector: <>h__TransparentIdentifier0 => DbSet<Order>(), 
        resultSelector: (<>h__TransparentIdentifier0, o) => new { 
            <>h__TransparentIdentifier0 = <>h__TransparentIdentifier0, 
            o = o
         })
    .Where(<>h__TransparentIdentifier1 => <>h__TransparentIdentifier1.o.OrderID == <>h__TransparentIdentifier1.<>h__TransparentIdentifier0.id)
    .Select(<>h__TransparentIdentifier1 => <>h__TransparentIdentifier1.o)
```
The issue in the query is that, it doesn't condense grouping out of the equation till very last operation. a grouping parameter (`g` in above case, cannot be represented in SQL and cannot be translated.

Since the query doesn't really using grouping and purpose of group by is just to get min id, query can be written following way
```C#
                    _ = (from id in (from c in ctx.TestChildren
                                             group c by c.Name into g
                                             select g.Min(x => x.ID)) //Try to pick the first TestChild from each group
                         from c in ctx.TestChildren
                         where c.ID == id
                         select c).ToList();
```

Starting from 6.0, the query can rewritten using GroupBy-FirstOrDefault pattern too
```C#
from c in ctx.TestChildren
group c by c.Name into g
select g.OrderBy(e => e.ID).FirstOrDefault()
```
Making fix to throw a better exception message.

**Comment by GSPP** [comment]
Would it be possible to detect that the grouping parameter is unused and delete it from parts of the query? That would seem like a useful transformation that could enable a whole range of scenarios to work that previously were blocked.

**Comment by TehWardy** [comment]
That's not how it works.
If the grouping clause exists it's applied to the query else nothing happens.
