### ISSUE TITLE
Null owned type with required properties cannot be added later

### ISSUE THREAD

**Issue by ItsSmiffy** [dotnet/efcore#21465]
Given an Entity with a null owned type, where the owned type is configured with a required property; when populating the parent entity property (which was previously null) with a new owned type an exception is thrown.

Given the example below, the line ``` cfg.Property(x => x.Number).IsRequired() ``` to setup the owned type's property as required seems to be the issue. Without that line the example runs without exceptions.

``` C#
namespace efcore.ownedentities
{
    using Microsoft.EntityFrameworkCore;
    using System;
    using System.Linq;

    class Program
    {
        static void Main(string[] args)
        {
            var id = Guid.NewGuid();

            using (var db = new Ctx())
            {
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                var p = new User(id){ Mobile = null };
                db.Entities.Add(p);
                db.SaveChanges();
            }

            using (var db = new Ctx())
            {
                var entity = db.Find<User>(id);
                entity.Mobile = new MobileNumber() { Number = "Test "};
                db.SaveChanges();
            }
        }

        public class User // parent entity
        {
            private Guid _id;

            public User(Guid id)
            {
                _id = id;
            }

            public Guid Id => _id;

            public MobileNumber Mobile { get; set; }

            public byte[] RowVersion { get; set; }
        }

        public class MobileNumber // value object
        {
            public string Number { get; set; }
        }

        public class Ctx : DbContext
        {
            public DbSet<User> Entities { get; set; }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseMySql("Server = localhost; Database = efownedentities; User = root; Password = admin; ");
            }

            protected override void OnModelCreating(ModelBuilder mb)
            {
                var parentEntityBuilder = mb.Entity<User>();

                parentEntityBuilder.HasKey(x => x.Id);

                parentEntityBuilder.Property(x => x.Id)
                    .HasField("_id")
                    .UsePropertyAccessMode(PropertyAccessMode.Field)
                    .IsRequired();

                parentEntityBuilder.Property(x => x.Id).ValueGeneratedNever();

                parentEntityBuilder
                    .Property<byte[]>(x => x.RowVersion)
                    .HasColumnType("TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP")
                    .IsRowVersion()
                    .IsRequired()
                    .HasColumnName("RowVersion");

                parentEntityBuilder
                    .OwnsOne(o => o.Mobile, cfg =>
                    {
                        cfg.Property(x => x.Number)
                            .IsRequired() // this line is the issue
                            .HasMaxLength(30);

                        cfg.Property<byte[]>("RowVersion")
                            .IsRowVersion()
                            .IsRequired()
                            .HasColumnType("TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP")
                            .HasColumnName("RowVersion");
                    });
            }
        }
    }
}
```

Exception Message:
System.InvalidOperationException: 'An instance of entity type 'User' and an instance of entity type 'MobileNumber' are mapped to the same row, but have different original property values for the properties {'RowVersion'} and {'RowVersion'} mapped to {'RowVersion'}. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting values.'

Stack Trace:
``` C#
   at Microsoft.EntityFrameworkCore.Update.ColumnModification.AddSharedColumnModification(ColumnModification modification)
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.GenerateColumnModifications()
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.<>c.<get_ColumnModifications>b__20_0(ModificationCommand command)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.get_ColumnModifications()
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.<>c.<CreateModificationCommands>b__13_0(ModificationCommand c)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at Microsoft.EntityFrameworkCore.Internal.Multigraph`2.AddVertices(IEnumerable`1 vertices)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.TopologicalSort(IEnumerable`1 commands)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.<BatchCommands>d__11.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at efcore.ownedentities.Program.Main(String[] args) in C:\WF\efcore.ownedentities\efcore.ownedentities\Program.cs:line 29
```

### Further technical details

EF Core version: 3.1.2
Database provider: Pomelo 3.1.1

**Comment by ajcvickers** [comment]
@AndriySvyryd I am able to reproduce this, but it's not clear to me why making the string property required changes the behavior here.

**Comment by AndriySvyryd** [comment]
There are two issues here. When `Number` is not required then `entity.Mobile` should be null when queried, but it isn't. I split this off to https://github.com/dotnet/efcore/issues/22054
