### ISSUE TITLE
EF core errors to add entities

### ISSUE THREAD

**Issue by HectorDZJ** [dotnet/efcore#21503]
I have been dealing with some EF core issues that I cannot identify the source and although I can get around them it's resulting in inefficient code in my opinion. Let me explain, I am calling the below procedure within a cycle after a POST form submission:

```C#
if (form.Inventory != null && form.Inventory.Any())
            {
                foreach (var pi in form.Inventory)
                {
                    var b = await _branchesActions.GetBranchesByIdNoTrackingAsync(pi.Branchesid).ConfigureAwait(false);
                    await _productActions.ModifyProductInventory(product, user, b, pi.ProductQty, "Producto agregado a sistema",
                        product.Productsid, "Create", "Alta de producto").ConfigureAwait(false);
                }
            }
```

this is the below code for the functions it is calling:

```C#
public async Task<Branches> GetBranchesByIdNoTrackingAsync(int id)
    {
        return await db.Branches.Where(b => b.IsActive && b.Branchesid == id)
            .AsNoTracking()
            .SingleOrDefaultAsync()
            .ConfigureAwait(false);
    }
```

ModifyProductInventory:

```C#
public async Task<bool> ModifyProductInventory(Products product, Users user, Branches branch, int qty, string action, int relid, string actionname, string actiontype)
    {
        try
        {
            var inventory = await db.BranchesInventory
                .Where(bi => bi.Branch.Branchesid == branch.Branchesid
                && bi.Product.Productsid == product.Productsid)
                .SingleOrDefaultAsync()
                .ConfigureAwait(false);
            if (inventory == null)
            {
                await InsertBranchInventory(qty, branch, product).ConfigureAwait(false);
            }
            else
            {
                if (!product.IsService)
                {
                    db.BranchesInventory.Update(inventory);
                    inventory.ProductQty += qty;
                    await db.SaveChangesAsync().ConfigureAwait(false);
                    db.Entry(inventory).State = EntityState.Detached;
                    db.Entry(branch).State = EntityState.Detached;
                }
            }
            await AddAuditLogEntry(action, qty, relid, actionname, actiontype, user, branch, product).ConfigureAwait(false);
            return true;
        }
        catch (Exception e)
        {
            await _sewebUtilities.LogError(e, "Error al modificar inventario para producto: " + product.ProductCode).ConfigureAwait(false);
            throw;
        }
    }
```

This second one is basically where I started having issues with EF core, the same code was on Framework with no issues so I ended up separating the problematic sections into its own functions for InsertBranchInventory:

```C#
public async Task InsertBranchInventory(int qty, Branches branch, Products product)
    {
        try
        {
            var inventory = new BranchesInventory
            {
                ProductQty = qty
            };
            await db.BranchesInventory.AddAsync(inventory).ConfigureAwait(false);
            await db.SaveChangesAsync().ConfigureAwait(false);
            //This works the first time the cycle runs but the second time but the second time the cycle runs it needs this code otherwise the id is 0 and I get error 1
            if (inventory.BranchesInventoryid <= 0)
            {
                inventory = await db.BranchesInventory
                    .OrderByDescending(i => i.BranchesInventoryid)
                    .Take(1)
                    .SingleOrDefaultAsync()
                    .ConfigureAwait(false);
            }
            db.BranchesInventory.Update(inventory);
            //if I do the below within the inventory declaration I get the error 2
            inventory.Branch = branch;
            inventory.Product = product;
            await db.SaveChangesAsync().ConfigureAwait(false);
            //I tried detaching the entities after the insertion was complete but it does not seem to help
            db.Entry(inventory).State = EntityState.Detached;
            db.Entry(branch).State = EntityState.Detached;
        }
        catch(Exception e)
        {
            await _sewebUtilities.LogError(e, "Error al agregar entrada de inventario para producto: " + product.ProductCode).ConfigureAwait(false);
            throw;
        }
    }
}
```

and for AddAuditLogEntry:

```C#
        public async Task AddAuditLogEntry(string actionPerformed, int qty, int relid, string actionname, string actiontype, Users user, Branches branch, Products product)
    {
        try
        {
            var actionTime = _sewebUtilities.GetCurrentTime();
            var audit = new AuditLog
            {
                ActionPerformed = actionPerformed,
                ItemType = "Products",
                Quantity = qty,
                EventDateTime = actionTime,
                Relatedid = relid,
                ActionName = actionname,
                ActionType = actiontype
            };
            await db.AuditLog.AddAsync(audit);
            await db.SaveChangesAsync().ConfigureAwait(false);
            //I'll have to replace the below as in the InsertBranchInventory function as I started getting error 2 on this after the second cycle run
            await db.Entry(audit).GetDatabaseValuesAsync().ConfigureAwait(false);
            db.AuditLog.Update(audit);
            //if I do the below within the inventory declaration I get the error 2, also for branches
            audit.Users = user;
            audit.Branches = branch;
            audit.Products = product;
            await db.SaveChangesAsync().ConfigureAwait(false);
            db.Entry(audit).State = EntityState.Detached;
            db.Entry(branch).State = EntityState.Detached;
        }
        catch (Exception e)
        {
            await _sewebUtilities.LogError(e, "Error al agregar entrada al log de productos");
        }
    }
```

for the errors I get they are as follow, Error 1:

```
System.InvalidOperationException: The property 'BranchesInventoryid' on entity type 'BranchesInventory' has a temporary value while attempting to change the entity's state to 'Modified'. Either set a permanent value explicitly or ensure that the database is configured to generate values for this property.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.Update[TEntity](TEntity entity)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Update(TEntity entity)
   at SeWebERP.Infrastructure.ProductActions.InsertBranchInventory(Int32 qty, Branches branch, Products product) in Infrastructure\ProductActions.cs:line 386
   at SeWebERP.Infrastructure.ProductActions.ModifyProductInventory(Products product, Users user, Branches branch, Int32 qty, String action, Int32 relid, String actionname, String actiontype) in Infrastructure\ProductActions.cs:line 326 Error al modificar inventario para producto: test001
```

Error 2:

```
    Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert explicit value for identity column in table 'Branches' when IDENTITY_INSERT is set to OFF.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:ebeb98ae-7c1a-498d-846f-63373ede3b86
Error Number:544,State:1,Class:16 
```

and no matter all of this patching even after I use the the if to get the last inventory record added it fails on the second cycle run with error:

```
System.InvalidOperationException: The instance of entity type 'Branches' cannot be tracked because another instance with the key value '{Branchesid: 1}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.NavigationReferenceChanged(InternalEntityEntry entry, INavigation navigation, Object oldValue, Object newValue)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.NavigationReferenceChanged(InternalEntityEntry entry, INavigation navigation, Object oldValue, Object newValue)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectNavigationChange(InternalEntityEntry entry, INavigation navigation)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.LocalDetectChanges(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager)
   at Microsoft.EntityFrameworkCore.ChangeTracking.ChangeTracker.DetectChanges()
   at Microsoft.EntityFrameworkCore.DbContext.TryDetectChanges()
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at SeWebERP.Infrastructure.ProductActions.AddAuditLogEntry(String actionPerformed, Int32 qty, Int32 relid, String actionname, String actiontype, Users user, Branches branch, Products product) in Infrastructure\ProductActions.cs:line 372 Error al agregar entrada al log de productos
```

and the inventory table end ups as such:

inventory table
![image](https://user-images.githubusercontent.com/38546386/86413472-e7decf80-bc86-11ea-9d88-d13bc4f353cf.png)

my models are not complicated, for the id I just use the key tag as below:

```
    public class BranchesInventory
{
    [Key]
    public int BranchesInventoryid { get; set; }

    public Branches Branch { get; set; }

    public Products Product { get; set; }

    public int ProductQty { get; set; }

    [MaxLength(200)]
    public string ProductLocation { get; set; }

}
```

but the documentation for ef core does not suggest to use anything else, I hope everything that is included here is enough information and someone can provide some guidance, or let me know if you would like me to include more information.

In order to advance I ended up changing the process to use a SQL query:

```
    public async Task InsertBranchInventory(int qty, Branches branch, Products product)
    {
        try
        {
            var p0 = branch.Branchesid;
            var p1 = qty;
            var p2 = product.Productsid;
            await db.Database.ExecuteSqlInterpolatedAsync($"INSERT INTO[BranchesInventory]([Branchesid], [ProductQty], [Productsid]) VALUES({p0}, {p1}, {p2});");
        }
        catch(Exception e)
        {
            await _sewebUtilities.LogError(e, "Error al agregar entrada de inventario para producto: " + product.ProductCode).ConfigureAwait(false);
            throw;
        }
    }
```

I did this last bit just to continue to progress with my projects which as mentioned actually works on "classic" .NET framework so I am migrating to .NET core, this is using version 3.1

**Comment by ajcvickers** [comment]
@HectorDZJ There's a lot of code here, but going right back to the beginning it seems that you are doing a no-tracking query and then attempting to manage all state manually. Why not just use a tracking query? See https://blog.oneunicorn.com/2020/01/17/dontcallupdate/ and docs for [basic saves](https://docs.microsoft.com/en-us/ef/core/saving/basic) and [disconnected entities](https://docs.microsoft.com/en-us/ef/core/saving/disconnected-entities).

**Comment by HectorDZJ** [comment]
I have changed that first query from a tracking query but when I started having problems I included the AsNoTracking to see if it made a difference, but it's pretty much the same the inventory record gets added but when the code goes to add the audit record it gets the problem that the branch entiry is already being tracked, and no matter what I do to dettach it I still get the error.

**Comment by ajcvickers** [comment]
Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by HectorDZJ** [comment]
Attached is a zip file with the project, I removed a lot of things but left everything the application does up to the point of the failure

[Issue21503.zip](https://github.com/dotnet/efcore/files/4920759/Issue21503.zip)

on launch you will see just the product create form and the first picture has the sample on how I am filling it

![image](https://user-images.githubusercontent.com/38546386/87463947-e80c9280-c5d7-11ea-8f3f-e40ff57c50c2.png)

after saving you should see the error on the second picture

![image](https://user-images.githubusercontent.com/38546386/87463999-01154380-c5d8-11ea-88b3-011d3e0fb868.png)

Let me know if you have any questions.

**Comment by ajcvickers** [comment]
@HectorDZJ The issue here is that Branch referenced from Users:
![image](https://user-images.githubusercontent.com/1430078/88428684-2d844900-cdaa-11ea-96eb-27aae5a07411.png)
is a different instance from the Branch that is being used at the top level:
![image](https://user-images.githubusercontent.com/1430078/88428704-3b39ce80-cdaa-11ea-9a24-2bc73a40c88b.png)

Going beyond this, there is a lot of code here for which I don't have enough context to know what it is supposed to be doing. From an EF perspective, it doesn't seem like most of this code should be needed. Finally, I see you're using a static context instance--this is not recommended. A new, short-lived context instance should be used for each unit-of-work.

**Comment by HectorDZJ** [comment]
I was afraid of something like that, so if it isn't too much of a problem could you explain to me why is it having knowledge of a branch in users if I am using AsNoTracking to get that object as well, I see your point but then I feel the code is still tracking something it shouldn't.

**Comment by ajcvickers** [comment]
@HectorDZJ At some point the entity is being attached to the context. You'll need to debug your application to find out where this is happening.
