### ISSUE TITLE
Invalid object name 'DefaultSequence'.

### ISSUE THREAD

**Issue by chassq** [dotnet/efcore#2158]
After upgrading my project from VS 2015 CTP 6 to RC I am running into an error when trying to add a record to a table. This worked fine in CTP 6 but now I get the error Invalid object name 'DefaultSequence'. Here is the stack:

   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at Microsoft.Data.Entity.Relational.SqlStatementExecutor.<>c__DisplayClass8_0.<ExecuteScalar>b__0()
   at Microsoft.Data.Entity.Relational.SqlStatementExecutor.Execute(IRelationalConnection connection, Func`1 action)
   at Microsoft.Data.Entity.Relational.SqlStatementExecutor.ExecuteScalar(IRelationalConnection connection, DbTransaction transaction, String sql)
   at Microsoft.Data.Entity.SqlServer.SqlServerSequenceValueGenerator`1.GetNewLowValue()
   at Microsoft.Data.Entity.ValueGeneration.HiLoValueGeneratorState.Next[TValue](Func`1 getNewLowValue)
   at Microsoft.Data.Entity.ValueGeneration.HiLoValueGenerator`1.Next()
   at Microsoft.Data.Entity.ValueGeneration.ValueGenerator`1.NextValue()
   at Microsoft.Data.Entity.ValueGeneration.ValueGenerator.Next()
   at Microsoft.Data.Entity.ChangeTracking.Internal.ValueGenerationManager.Generate(InternalEntityEntry entry)
   at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges)
   at Microsoft.Data.Entity.ChangeTracking.EntityEntry.set_State(EntityState value)
   at Microsoft.Data.Entity.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Microsoft.Data.Entity.DbContext.Add[TEntity](TEntity entity)
   at Microsoft.Data.Entity.Internal.InternalDbSet`1.Add(TEntity entity)
   at lib.factory.party.PartyPerson.<Create>d__5.MoveNext() in C:\Source\Workspaces\CRA360\Resource360\Resource360\lib.factory\party\PartyPerson.cs:line 164

**Comment by ajcvickers** [comment]
Database mappings have changed between the two pre-release versions. In general you can use Migrations to re-generate/update your database, or manually make updates to the mappings. In this particular case you may just need `modelBuilder.ForSqlServer().UseIdentity();` because we made a change to use Sequence objections instead of Identity columns by default.
