### ISSUE TITLE
Bad Sql request generated for Select

### ISSUE THREAD

**Issue by YeskaNova** [dotnet/efcore#21666]
I have a complex application built on top of EF Core, for a readonly operation that only needs to fetch data, the generated SQL command is weird : 

![image](https://user-images.githubusercontent.com/4983925/87791354-63717c80-c842-11ea-8e30-d96fbd08d652.png)

It's like it's merging an Update command with a Select command, obviously this does not run in SQL server.

### Steps to reproduce

I have here another example that I managed to log, it's not the same that in the screenshot but it has that weird  = True in the Case When.

It's only reproduced when I launch a stress test which does a lot of queries in parallel. No DbContext is shared across the threads. It's complicated to isolate the issue in a simple reproducible code, there is a generic layer built on top of EF core and lot of things happen before triggering that query. 

Debug Expression view : 
```
DbSet<List>()
    .Where(deletable => !(deletable.IsDeleted))
    .Where(list => <>c__DisplayClass4_0.lists
        .Contains(list.Id) || Invoke(lastModifiedBy => (Convert(lastModifiedBy.LastModifiedById, Int32) == Convert(value(Backapp.Data.Entities.LastModifiedBy.LastModifiedByEntityFilter+<>c__DisplayClass4_0).currentUserId, Int32)), list)
    )
    .Where(e => <>c__DisplayClass6_0.state.Ids
        .Contains(e.Id))
```
Debug Query : 
```SQL
DECLARE @__currentUserId_1 smallint = CAST(201 AS smallint);

SELECT [l].[Id], [l].[IsDeleted], [l].[LastModifiedById], [l].[LastModifiedOn], [l].[Version], [l].[Name_lng1], [l].[Name_lng2], [l0].[Id], [l0].[ChildId], [l0].[IsDirectParent], [l0].[ParentId]
FROM [List] AS [l]
LEFT JOIN [List_Parents] AS [l0] ON [l].[Id] = [l0].[ChildId]
WHERE (([l].[IsDeleted] <> CAST(1 AS bit)) AND ([l].[LastModifiedById] = @__currentUserId_1)) AND ([l].[Id] = 208)
ORDER BY [l].[Id], [l0].[Id]
```

Sql Query : 

```SQL
exec sp_executesql N'SELECT [l].[Id], [l].[IsDeleted], [l].[LastModifiedById], [l].[LastModifiedOn], [l].[Version], [l].[Name_lng1], [l].[Name_lng2], [l0].[Id], [l0].[ChildId], [l0].[IsDirectParent], [l0].[ParentId]
FROM [List] AS [l]
LEFT JOIN [List_Parents] AS [l0] ON [l].[Id] = [l0].[ChildId]
WHERE (([l].[IsDeleted] <> CAST(1 AS bit)) AND ([l].[LastModifiedById] = (@__currentUserId_1 = CAST(True AS smallint)))) AND CASE
    WHEN [l].[Id] = (202 = True) THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END
ORDER BY [l].[Id], [l0].[Id]',N'@__currentUserId_1 smallint',@__currentUserId_1=201
```

```
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteReaderAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteReaderAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteReaderAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.<InitializeReaderAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.<MoveNextAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__65`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__65`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToArrayAsync>d__66`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MyApp.Data.EntityManagerPipeline.Steps.Get.GetProcessPipelineStepExecutor`2.<Execute>d__3.MoveNext() in 

Microsoft.Data.SqlClient.SqlException (0x80131904): An expression of non-boolean type specified in a context where a condition is expected, near 'ORDER'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at MyApp.Data.EntityManagerPipeline.Steps.Get.GetProcessPipelineStepExecutor`2.Execute(EntityManagerPipelineState`2 state, CancellationToken cancellationToken) in E:\QualetechProject\src\MyApp\Data\EntityManagerPipeline\Steps\Get\GetProcessPipelineStepExecutor.cs:line 16
   at MyApp.Pipelines.Pipeline`1.Execute(Object state, CancellationToken cancellationToken) in E:\QualetechProject\src\MyApp\Pipelines\Pipeline.cs:line 20
   at MyApp.Data.EntityManager`2.GetAsync(String id, String order, String filter, Nullable`1 version, IBaseDbContext dbContext, ICurrentUserIdGetter currentUser, CancellationToken cancellationToken) in E:\QualetechProject\src\MyApp\Data\EntityManager.cs:line 31
   at Sample.Web.Core.DbEntityController`2.GetAsync(String id, String order, String filter, Nullable`1 version, CancellationToken cancellationToken) in E:\QualetechProject\src\Sample.Web\Core\DbEntityController.cs:line 21
   at lambda_method5183(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Sample.Web.Core.SecurityMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in E:\QualetechProject\src\Sample.Web\Core\SecurityMiddleware.cs:line 37
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Sample.Web.Core.RetryMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in E:\QualetechProject\src\Sample.Web\Core\RetryMiddleware.cs:line 30
ClientConnectionId:121f5f4c-fb31-4234-9889-e3223f4cddeb
Error Number:4145,State:1,Class:15
```

### Further technical details

EF Core version: 5.0.0-rc.1.20366.1
Database provider: Sql Server
Target framework: .NET 5
Operating system: Windows 10
IDE: VS 2019

**Comment by smitpatel** [comment]
We will need a stand-alone runnable repro code to investigate this issue.

**Comment by YeskaNova** [comment]
While trying to create a simple project that reproduces the issue I found that it was my generated expressions that was too complicated for what it was intended to do, I fixed it by simplifing those expressions. I think we can close the issue.

**Comment by YeskaNova** [comment]
I managed to reproduce the issue, I'm happy I did because it seemed very random. I can reproduce it on my Ryzen CPU ( 16physical/32logical cores ) and not on my laptop : 

```
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;

public class User
{
    public short Id { get; set; }
}


    public class List
    {
        public int Id { get; set; }
        public bool IsDeleted { get; set; }
        public User LastModifiedBy { get; set; }
        public virtual ICollection<List_Parents> Parents { get; set; }
    }
    public class List_Parents
    {
        public int Id { get; set; }
        public int ChildId { get; set; }
        public virtual List Child { get; set; }
        public int ParentId { get; set; }
        public virtual List Parent { get; set; }
    }
public class AppDbContext : DbContext
{
    public ISet<List> Lists { get; set; }

    public AppDbContext(DbContextOptions options) : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<List>().OwnsMany(typeof(List_Parents), nameof(List.Parents), ob =>
        {
            ob.HasKey(nameof(List_Parents.Id));
            ob.WithOwner(nameof(List_Parents.Child));
            ob.HasOne(nameof(List_Parents.Parent)).WithMany().OnDelete(DeleteBehavior.ClientCascade);
        });
        modelBuilder.Entity<User>();
    }
}

class Program
{

    static void Main(string[] args)
    {
        var sc = new ServiceCollection();
        var guid = Guid.NewGuid();
        sc.AddDbContext<AppDbContext>(op => op.UseSqlServer(@"Server=(localdb)\MSSQLLocalDB;Integrated Security=true;DataBase=" + guid));
        using (var provider = sc.BuildServiceProvider())
        {
            var lists = Enumerable.Range(0, 1000).Select(_ => new List()).ToArray();
            using (var scope = provider.CreateScope())
            using (var dbcontext = scope.ServiceProvider.GetService<AppDbContext>())
            {
                dbcontext.Database.EnsureCreated();
                dbcontext.AddRange(lists);
                dbcontext.SaveChanges();
            }

            var pCount = Environment.ProcessorCount;




            {
                short currentUser = 1;
                var fil = new[] {1, 2, 3};

                Parallel.For(0, pCount, p =>
                {
                    for (var i = 0; i < 100; ++i)
                        using (var scope = provider.CreateScope())
                        using (var dbcontext = scope.ServiceProvider.GetService<AppDbContext>())
                        {
                            var query = dbcontext.Set<List>().Where(x => !x.IsDeleted)
                                .Where(x => fil.Contains(x.Id) || x.LastModifiedBy.Id == currentUser);

                            query.ToArrayAsync().GetAwaiter().GetResult();
                        }
                });

            }
            
            {
                Parallel.For(0, pCount, p =>
                {
                    for (var i = 0; i < 100; ++i)
                        using (var scope = provider.CreateScope())
                        using (var dbcontext = scope.ServiceProvider.GetService<AppDbContext>())
                        {
                            short currentUser2 = 1;
                            var fil2 = new[] { 1, 2, 3 };

                            var query = dbcontext.Set<List>().Where(x => !x.IsDeleted)
                                .Where(x => fil2.Contains(x.Id) || x.LastModifiedBy.Id == currentUser2);

                            query.ToArrayAsync().GetAwaiter().GetResult();
                        }
                });
            }
        }
    }

}
```

**Comment by maumar** [comment]
Looks like a thread safety problem in search condition. Examples of invalid queries that we sometimes generate:

```sql
SELECT [l].[Id], [l].[IsDeleted] = CAST(1 AS bit) AS [IsDeleted], [l].[LastModifiedById] = CAST(True AS smallint) AS [LastModifiedById], [u].[Id], [l0].[Id], [l0].[ChildId] = True AS [ChildId], [l0].[ParentId]
    FROM [List] AS [l]
    LEFT JOIN [User] AS [u] ON [l].[LastModifiedById] = [u].[Id]
    LEFT JOIN [List_Parents] AS [l0] ON [l].[Id] = [l0].[ChildId]
    WHERE ([l].[IsDeleted] <> CAST(1 AS bit)) AND ([l].[Id] IN (1, 2, 3) OR ([u].[Id] = @__currentUser_1))
    ORDER BY [l].[Id], [u].[Id], [l0].[Id]
```

```sql
SELECT [l].[Id], [l].[IsDeleted], [l].[LastModifiedById], [u].[Id], [l0].[Id], [l0].[ChildId], [l0].[ParentId]
    FROM [List] AS [l]
    LEFT JOIN [User] AS [u] ON [l].[LastModifiedById] = [u].[Id]
    LEFT JOIN [List_Parents] AS [l0] ON [l].[Id] = [l0].[ChildId]
    WHERE ([l].[IsDeleted] <> CAST(1 AS bit)) AND CASE
        WHEN [l].[Id] IN (1, 2, 3) OR ([u].[Id] = @__currentUser_1) THEN CAST(1 AS bit)
        ELSE CAST(0 AS bit)
    END
    ORDER BY [l].[Id], [u].[Id], [l0].[Id]
```

**Comment by smitpatel** [comment]
This would also be in SqlNullabilityProcessor and others.

**Comment by smitpatel** [comment]
Regression caused by https://github.com/dotnet/efcore/pull/21124
