### ISSUE TITLE
Wrong Alias Name in Dynamic Generated Query in Entity Framework Core - Identity Server4 

### ISSUE THREAD

**Issue by sayoojt** [dotnet/efcore#21696]
Generated the wrong query, check the bold alias name for is_clients it should have being x5, somehow m1 overwrote that.

```sql
SELECT "x.Claims"."ID", "x.Claims"."CLIENTID", "x.Claims"."TYPE", "x.Claims"."VALUE"
FROM "IS_CLIENT_CLAIMS" "x.Claims"
INNER JOIN (
    Select 
     K0 "ID" from(
    SELECT "x5"."ID" K0
    FROM "IS_CLIENTS" "**m1**"
    WHERE ("x5"."CLIENTID" = :clientId_0)
    ORDER BY "x5"."ID" NULLS FIRST
    ) "m1"
    where rownum <= 1
) "t4" ON ("x.Claims"."CLIENTID" = "t4"."ID")
ORDER BY "t4"."ID" NULLS FIRST;
```
**Expected Query**

```sql
SELECT "x.Claims"."ID", "x.Claims"."CLIENTID", "x.Claims"."TYPE", "x.Claims"."VALUE"
FROM "IS_CLIENT_CLAIMS" "x.Claims"
INNER JOIN (
    Select 
     K0 "ID" from(
    SELECT "x5"."ID" K0
    **FROM "IS_CLIENTS" "x5"**
    WHERE ("x5"."CLIENTID" = :clientId_0)
    ORDER BY "x5"."ID" NULLS FIRST
    ) "m1"
    where rownum <= 1
) "t4" ON ("x.Claims"."CLIENTID" = "t4"."ID")
ORDER BY "t4"."ID" NULLS FIRST" 
```

### Steps to reproduce

This alias name has gone wrong for the entire application for this table IS_CLIENTS and got resolved only by doing IIS App pool recycle. So any query with this table was failing.

```
 An unhandled exception was thrown by the application. Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00904: "x5"."ID": invalid identifier
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.IncludeCollection[TEntity,TRelated,TElement](Int32 includeId, INavigation navigation, INavigation inverseNavigation, IEntityType targetEntityType, IClrCollectionAccessor clrCollectionAccessor, IClrPropertySetter inverseClrPropertySetter, Boolean tracking, TEntity entity, Func`1 relatedEntitiesFactory, Func`3 joinPredicate)
   at lambda_method(Closure , QueryContext , Client , Object[] )
   at lambda_method(Closure , Client )
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at lambda_method(Closure )
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at IdentityServer4.EntityFramework.Stores.ClientStore.FindClientByIdAsync(String clientId)
   at IdentityServer4.Stores.ValidatingClientStore`1.FindClientByIdAsync(String clientId)
   at IdentityServer4.Stores.IClientStoreExtensions.FindEnabledClientByIdAsync(IClientStore store, String clientId)
   at IdentityServer4.Validation.ClientSecretValidator.ValidateAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
   at IdentityServer4.Hosting.MutualTlsTokenEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at IdentityServer.Startup.<>c.<<Configure>b__9_0>d.MoveNext() in C:\Agent2\_work\265\s\src\WebUI\Startup.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
```

### Further technical details

EF Core version:
Database provider: Oracle.EntityFrameworkCore - 2.19.60
Target framework:  .NET Core 3.1
Operating system: Windows
IDE: Visual Studio 2019 16.3, IIS 10

**Comment by ErikEJ** [comment]
EF Core 2.2 is no longer supported - have you tried the EF Core 3 beta provider?

**Comment by ajcvickers** [comment]
@sayoojt This looks like an issue with the Oracle provider which should be reported to Oracle if it still repros on the 3.0 beta.

**Comment by sayoojt** [comment]
> EF Core 2.2 is no longer supported - have you tried the EF Core 3 beta provider?

ORACLE integration not supported was 3.x , is it supported in EFCore beta?

**Comment by sayoojt** [comment]
> @sayoojt This looks like an issue with the Oracle provider which should be reported to Oracle if it still repros on the 3.0 beta.

dynamic query is generated by efcore, not oracle. please check the screen shot i had put. check the below bold m1 it should be **x5**

SELECT "x.Claims"."ID", "x.Claims"."CLIENTID", "x.Claims"."TYPE", "x.Claims"."VALUE"
FROM "IS_CLIENT_CLAIMS" "x.Claims"
INNER JOIN (
    Select 
     K0 "ID" from(
    SELECT "x5"."ID" K0
    FROM "IS_CLIENTS" **"m1"**
    WHERE ("x5"."CLIENTID" = :clientId_0)
    ORDER BY "x5"."ID" NULLS FIRST
    ) "m1"
    where rownum <= 1
) "t4" ON ("x.Claims"."CLIENTID" = "t4"."ID")
ORDER BY "t4"."ID"

**Comment by ajcvickers** [comment]
@sayoojt EF Core calls into the Oracle provider when translating queries, which is why we believe this to be a provider issue.
