### ISSUE TITLE
ShowHelp throws NRE 

### ISSUE THREAD

**Issue by moozzyk** [dotnet/efcore#2178]
`dnx . ef help add`

throws

```
                     _/\__
               ---==/    \\
         ___  ___   |.    \|\
        | __|| __|  |  )   \\\
        | _| | _|   \_/ |  //|\\
        |___||_|       /   \\\/\\

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.ShowHelp(String commandName)
   at Microsoft.Data.Entity.Commands.Program.ShowHelp(String command)
   at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass7_8.<Main>b__19()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Data.Entity.Commands.Program.Main(String[] args)
```

on
     \*    1.0.0-beta4 clr     x86

**Comment by bricelam** [comment]
One of the many bugs in the CommandLineUtils helpers. Could you file this on the dnx repo?

**Comment by moozzyk** [comment]
https://github.com/aspnet/dnx/issues/1859
