### ISSUE TITLE
EF Core Preview 7 - Add-Migration Initial Result in wrong Migration

### ISSUE THREAD

**Issue by marafiq** [dotnet/efcore#21792]
Add-Migration & Update-Database commands does not execute successfully. It results in following error
Microsoft.Data.SqlClient.SqlException (0x80131904): The option 'CASCADE' is not supported with memory optimized tables.

### Steps to reproduce
- Create a model which has primary & foreign key relationship. 
- Execute Add-Migration in Package Manager Console
- Execute Update-Database in Package Manager Console

It will result in following exceptions

~~~
Failed executing DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE [Invoices] (
    [Id] int NOT NULL IDENTITY,
    [Date] datetime2 NOT NULL,
    [CustomerId] int NOT NULL,
    CONSTRAINT [PK_Invoices] PRIMARY KEY NONCLUSTERED ([Id]),
    CONSTRAINT [FK_Invoices_Customers_CustomerId] FOREIGN KEY ([CustomerId]) REFERENCES [Customers] ([CustomerId]) ON DELETE CASCADE
)
    WITH
        (MEMORY_OPTIMIZED = ON);
Microsoft.Data.SqlClient.SqlException (0x80131904): The option 'CASCADE' is not supported with memory optimized tables.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
~~~

Use below model to reproduce this. 
Note: When table is Memory Optimized it should fail to create migration for not-supported types like nvarchar(max) which is default for `string`

``` C#
public class Customer
    {
        public int CustomerId { get; set; }
        [MaxLength(50)]
        public string FirstName { get; set; }
        [MaxLength(50)]
        public string LastName { get; set; }
        [MaxLength(200)]
        public string Address { get; set; }
        public virtual List<Invoice> Invoices { get; set; }
    }

    public class Invoice
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }

        public int CustomerId { get; set; }

        [ForeignKey("CustomerId")]
        public virtual Customer Customer { get; set; }
        public virtual List<InvoiceItem> Items { get; set; }
    }

    public class InvoiceItem
    {
        public int InvoiceItemId { get; set; }
        public int InvoiceId { get; set; }

        [MaxLength(50)]
        public string Code { get; set; }

        [ForeignKey("InvoiceId")]
        public virtual Invoice Invoice { get; set; }
    }

 public class DatabaseContext : DbContext
    {
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Invoice> Invoices { get; set; }
        public DbSet<InvoiceItem> InvoiceItems { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseSqlServer(@"Data Source=SQLSERVERINSTANCE;Initial Catalog=DBNAME;Integrated Security=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Customer>().IsMemoryOptimized();
            modelBuilder.Entity<Invoice>().IsMemoryOptimized();
            modelBuilder.Entity<InvoiceItem>().IsMemoryOptimized();
        }
    }

```

### Further technical details
~~~ XML
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.0-preview.7.20365.15" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.0-preview.7.20365.15">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
~~~
EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: .Net5 Preview 7
Operating system:
IDE: Version 16.7.0 Preview 5.0

**Comment by ajcvickers** [comment]
@marafiq SQL Server [memory-optimized tables](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/introduction-to-memory-optimized-tables?view=sql-server-ver15) have several limitations. One of them is that cascades are not allowed. To use memory-optimized tables with EF, it's best to first fully understand the limitations and implications of this from the SQL Server docs I linked, and then if they still make sense configure the EF model appropriately--for example, set the cascade delete behavior to something that is supported.

**Comment by marafiq** [comment]
Thanks @ajcvickers  that is acceptable workaround to set the cascade to NoAction. 
I reported because Migration command should generate migration with NoAction rather than Cascade if Entity is configured to InMemory table.

**Comment by ajcvickers** [comment]
@marafiq Changing the conventions to automatically do something different for memory-optimized tables (or other similar features) is not something we typically do because you may not be aware that restrictions exist and that EF therefore behaves differently. This can then be quite confusing. So on the balance of whether or not to do something by convention, this is an example where we err on the side of forcing the developer to be explicit about opting out of behaviors.
