### ISSUE TITLE
FK constraint failed when re-adding entity

### ISSUE THREAD

**Issue by alex-tomkeiev** [dotnet/efcore#21949]
Entities are being saved in the wrong order, which causes parent entity getting saved with temporary foreign key.

**Logged query:**
`Failed executing DbCommand (6ms) [Parameters=[@p0='-9223372036854774807' (Nullable = true) (DbType = String), @p1='http://myblog.net' (Size = 17)], CommandType='Text', CommandTimeout='30']
      INSERT INTO "Blogs" ("LatestPostId", "Url")
      VALUES (@p0, @p1);
      SELECT "Id"
      FROM "Blogs"
      WHERE changes() = 1 AND "rowid" = last_insert_rowid();`

**Exception:**
`Unhandled exception. Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)`

### Steps to reproduce

``` C#
namespace EFQuickStart
{
    public class Entity
    {
        [Key] public long Id { get; set; }
    }

    public class Blog : Entity
    {
        public string Url { get; set; }
        public Post LatestPost { get; set; }
    }

    public class Post : Entity
    {
        public string Title { get; set; }
    }

    public class BloggingContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Post> Posts { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder options)
            => options.UseSqlite("Data Source=blogging.db")
                .UseLoggerFactory(MyLoggerFactory)
                .EnableSensitiveDataLogging();
        
        private static readonly ILoggerFactory MyLoggerFactory
            = LoggerFactory.Create(builder => { builder.AddConsole().SetMinimumLevel(LogLevel.Trace); });

        static void Main(string[] args)
        {
            using var db = new BloggingContext();
            db.Database.EnsureCreated();

            var blog = new Blog {Url = "http://myblog.net"};
            var post = new Post {Title = "Hello World"};
            blog.LatestPost = post;
            db.AddRange(blog, post);

            db.Entry(post).State = EntityState.Detached;
            db.Add(post);

            db.SaveChanges();
        }
    }
}
```

### Further technical details

EF Core version: 3.1.6
Database provider: Microsoft.EntityFrameworkCore.SQLite
Target framework: .NET Core 3.1
Operating system: MacOS 10.15.15
IDE: Rider

**Comment by ajcvickers** [comment]
@alex-tomkeiev Why are you adding the post entity, detaching it, and then adding it again?

Note for team: the shadow FK is not modified even though the navigation now points to the same instance but with a different temp ID.

State before detaching post:
```
Blog {Id: -9223372036854774807} Added
  Id: -9223372036854774807 PK Temporary
  LatestPostId: -9223372036854774807 FK Temporary
  Url: 'http://myblog.net'
  LatestPost: {Id: -9223372036854774807}
Post {Id: -9223372036854774807} Added
  Id: -9223372036854774807 PK Temporary
  Title: 'Hello World'
```
State after detaching post:
```
Blog {Id: -9223372036854774807} Added
  Id: -9223372036854774807 PK Temporary
  LatestPostId: -9223372036854774807 FK Temporary
  Url: 'http://myblog.net'
  LatestPost: <not found>
```
State after re-adding post:
```
Blog {Id: -9223372036854774807} Added
  Id: -9223372036854774807 PK Temporary
  LatestPostId: -9223372036854774807 FK Temporary
  Url: 'http://myblog.net'
  LatestPost: {Id: -9223372036854774806}
Post {Id: -9223372036854774806} Added
  Id: -9223372036854774806 PK Temporary
  Title: 'Hello World'
```

**Comment by alex-tomkeiev** [comment]
Thanks for a speedy response!
I'm refactoring our existing code base and I believe that detaching entities was a workaround for [#19137](https://github.com/dotnet/efcore/issues/19137) which we had to use when resolving circular dependencies. It works fine without detaching in 3.1.6.
Btw, is there a reason why simple circular dependencies are not resolved automatically? It seems that the cycle breaking code is there, but it is not being called.

**Comment by ajcvickers** [comment]
@alex-tomkeiev 

> Is there a reason why simple circular dependencies are not resolved automatically?

Can you give an example of what you mean by this?

**Comment by alex-tomkeiev** [comment]
Sure thing. Here is a slightly modified example from the above with Blog -> Post -> PostDetails -> Blog references which throws an exception when saved.

    public class Entity {
        [Key] public long Id { get; set; }
    }

    public class Blog : Entity {
        public string Url { get; set; }
        public Post LatestPost { get; set; }
    }

    public class Post : Entity {
        public PostDetails Details { get; set; }
        public string Title { get; set; }
    }

    public class PostDetails : Entity {
        public Blog Blog { get; set; }
    }

    public class BloggingContext : DbContext {
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Post> Posts { get; set; }
        public DbSet<PostDetails> PostDetails { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder options)
            => options.UseSqlite("Data Source=blogging.db");

        static void Main() {
            using var db = new BloggingContext();
            db.Database.EnsureCreated();

            var blog = new Blog {Url = "http://myblog.net"};
            var post = new Post {Title = "Hello World"};
            blog.LatestPost = post;
            post.Details = new PostDetails() {Blog = blog};

            db.Add(blog);
            // System.InvalidOperationException: Unable to save changes because a circular dependency was detected in the data to be saved
            db.SaveChanges();
        }
    }

Unless I'm missing something, EF should be able to break one of the links while doing TopologicalSort() and detecting these cycles. This is a simple scenario, but it also happens in collection references and self-referencing entities, e.g. A->A. 

For now, we are having to repeat the work EF does and resolve these cycles manually before saving data.

**Comment by alex-tomkeiev** [comment]
OK, I've found [this old ticket #1699](https://github.com/dotnet/efcore/issues/1699) and looks like it's just not implemented.
