### ISSUE TITLE
Owned entity without owner can be attached to context

### ISSUE THREAD

**Issue by mnver1** [dotnet/efcore#21954]
I don't know if this is by-design or it, but it doesn't make sense to me so I thought I report it.

``` C#
    class Owner
    {
        public Guid Id { get; set; }

        public Owned Owned { get; set; }
    }

    [Owned]
    class Owned
    {
        public int Foo { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            Test_InMemoryDb();

            Test_Postgres();
        }

        static void Test_InMemoryDb()
        {
            var optionsBuilder = new DbContextOptionsBuilder();

            optionsBuilder.UseInMemoryDatabase("Test_OwnedEntityWithoutOwner");

            var context = new Context(optionsBuilder.Options);

            context.Database.EnsureDeleted();

            context.Database.EnsureCreated();

            var owned = new Owned();

            var entry = context.Entry(owned);                       // expected: exception

            entry.State = EntityState.Added;

            Assert.True(entry.State == EntityState.Added);

            var writtenEntitiesCount = context.SaveChanges();       // expected: exception

            Assert.True(writtenEntitiesCount == 1);                 // excepted: 0

            Assert.True(entry.State == EntityState.Unchanged);

            owned.Foo = 1;

            context.ChangeTracker.DetectChanges();

            Assert.True(entry.State == EntityState.Modified);   

            writtenEntitiesCount = context.SaveChanges();           // expected: exception

            Assert.True(writtenEntitiesCount == 1);                 // excepted: 0
        }

        static void Test_Postgres()
        {
            var optionsBuilder = new DbContextOptionsBuilder();

            optionsBuilder.UseNpgsql("Server = 127.0.0.1; Port = 5432; Database = Test_OwnedEntityWithoutOwner; User Id = postgres; Password = 123;");

            var context = new Context(optionsBuilder.Options);

            context.Database.EnsureDeleted();

            context.Database.EnsureCreated();

            var owned = new Owned();

            var entry = context.Entry(owned);                       // expected: exception

            entry.State = EntityState.Added;

            Assert.True(entry.State == EntityState.Added);

            var writtenEntitiesCount = context.SaveChanges();       // expected: exception

            Assert.True(writtenEntitiesCount == 0);

            Assert.True(entry.State == EntityState.Unchanged);

            owned.Foo = 1;

            context.ChangeTracker.DetectChanges();

            Assert.True(entry.State == EntityState.Modified);

            Assert.Throws<DbUpdateConcurrencyException>(() => context.SaveChanges());             // expected: a meaningful exception
                                                                                                  // Exception message: 'Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. 
        }

    }
```

### Further technical details

EF Core version: 3.1.6
Database provider: Several
Target framework: .NET Core 3.0

**Comment by ajcvickers** [comment]
Note for triage: Repros on 3.1.6, throws when calling SaveChanges in latest daily:

```
/usr/share/dotnet/dotnet /home/ajcvickers/Repros/Test/Test/bin/Debug/netcoreapp3.0/Test.dll
Unhandled exception. System.InvalidOperationException: The value of 'Owned.OwnerId' is unknown when attempting to save changes. This is because the property is also part of a foreign key for which the principal entity in the relationship is not known.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.PrepareToSave()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetEntriesToSave(Boolean cascadeChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Test.Program.Test_InMemoryDb() in /home/ajcvickers/Repros/Test/Test/Program.cs:line 49
   at Test.Program.Main(String[] args) in /home/ajcvickers/Repros/Test/Test/Program.cs:line 24
```

**Comment by ajcvickers** [comment]
Note from triage: this was a bug in 3.1, however putting this on the backlog to throw a better exception message for this case.

**Comment by EmpeRoar** [comment]
any progress on this issue?

**Comment by ajcvickers** [comment]
@EmpeRoar No, but the issue here is only tracking throwing with a more helpful exception message. An owned entity without an owner cannot be tracked.

**Comment by EmpeRoar** [comment]
we redesign our database relationships since we are using database-first. and it fixed it,

**Comment by ethembynkr** [comment]
I get same error when primary key is 0 (zero).

`   public class User
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Id { get; set; }
        public LocalizedEntity NationalityName { get; set; }
    }

    [Owned]
    public class LocalizedEntity
    {
        public string Primary { get; set; }
        public string Secondary { get; set; }
    }
`

EF Core version: 5.0.0
