### ISSUE TITLE
AsSplitQuery not implemented on EF Core InMemory

### ISSUE THREAD

**Issue by marianosz** [dotnet/efcore#22034]
Queries using the new 'AsSplitQuery' fail when using Memory Provider
Error: System.NotImplementedException : Unhandled method 'AsSplitQuery'.
I understand that this will have no effect on the memory " query ", but maybe there is a way to at least do nothing but don't throw an exception. (Like the AsNoTracking method) on Memory Provider

### Steps to reproduce
Run any query using In Memory Context (EF Core InMemory) that contains a ' AsSplitQuery' method call.

 System.NotImplementedException : Unhandled method 'AsSplitQuery'.
ERROR:
 System.NotImplementedException : Unhandled method 'AsSplitQuery'.
STACK:
      at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
    at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
    at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
    at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
    at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
    at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
    at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
    at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
### Further technical details

EF Core version: 5.0.0-preview.7.20364.11
Database provider: Microsoft.EntityFrameworkCore.InMemory
Target framework: .NET Core 3.1
Operating system: Windows 10 / Ubuntu 20
IDE: Visual Studio 2019 16.3 / VS Code

**Comment by smitpatel** [comment]
AsNoTracking actually has effect on InMemory provider. AsSplitQuery is plain wrong. Note if you are using only one provider in your code, (e.g. InMemory) then you won't even get method `AsSplitQuery` since it is defined only for relational providers.
If you are having multiple providers in your project then you need to conditionally do things which are provider specific, which applies to building model, query operators, database specific functions.

**Comment by roji** [comment]
Better exception and message? NotImplementedException should generally not be exposed by any of our APIs...

**Comment by marianosz** [comment]
Yeah I got it, but I have a business layer that I need to test, and all the test are having exceptions because of this... Looks really complicated and inadequate to add conditional logic related the providers in something that can be implemented to do nothing on the memory provider, that is something a lot of devs use to create unit tests.... If you have any other suggestion to use this without the need to inform the business layer about the provider that we are using, that will be awesome!

**Comment by smitpatel** [comment]
> Better exception and message? NotImplementedException should generally not be exposed by any of our APIs...

Can throw InvalidOperationException instead. More than that, we can identify across provider if you used method from other provider. Same error would happen if you used `EF.Functions.Collate` or `EF.Functions.DateTimeFromDateParts`

**Comment by marianosz** [comment]
yeah but EF.Functions.Collate or EF.Functions.DateTimeFromDateParts are really specific and it is fine to throw an error on memory provider, but AsSplitQuery is a global query modifier method to have the same behavior on the queries that we have on EF Core 2, an it will be common scenario to try to test code that will have this method to run common queries...

**Comment by ajcvickers** [comment]
I think we should look at what we can do to make this better. Its conceptually similar to what we did to allow transactions to be a no-op when using the in-memory provider.

**Comment by marianosz** [comment]
@ajcvickers that would be awesome, I understand that in memory provider that method will do nothing, but will be great for the Unit Test context! Thanks!

**Comment by ajcvickers** [comment]
Decision from triage: no-op for the in-memory provider.

**Comment by marianosz** [comment]
@ajcvickers awesome! Thanks!
