### ISSUE TITLE
TargetInvocationException in loading collection property (OwnsMany)

### ISSUE THREAD

**Issue by m-khooryani** [dotnet/efcore#22084]
.Query() on collection property that configured to its owner by OwnsMany function throws TargetInvocationException.

### Steps to reproduce

``` C#
class Program
{
    static void Main(string[] args)
    {
        using var context = new BloggingContext();
        context.Database.OpenConnection();
        context.Database.EnsureCreated();

        context.Blogs.Add(sampleBlog);
        context.SaveChanges();

        var blog = context.Blogs.Single(b => b.BlogId == 1);

        var goodPosts = context.Entry(blog)
            .Collection(b => b.Posts)
            .Query();
    }
}

public class Post
{
    public int Id { get; set; }
    public string Title { get; set; }
}
public class Blog
{
    public int BlogId { get; set; }
    public string Url { get; set; }

    public List<Post> Posts { get; set; }
}

public class BloggingContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>().OwnsMany(x => x.Posts, post =>
        {
            post.ToTable("Posts");
            post.HasKey("Id");

            post.Property(x => x.Title);
        });
        modelBuilder.Entity<Blog>()
            .ToTable("Blogs");
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        var connection = new SqliteConnection("Data Source=:memory:");
        optionsBuilder.UseSqlite(connection);
    }
}
```

Got Exceptions? 
System.Reflection.TargetInvocationException
HResult=0x80131604
Message=Exception has been thrown by the target of an invocation.
Source=System.Private.CoreLib
StackTrace:
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
at Microsoft.EntityFrameworkCore.Internal.EntityFinder1.BuildQueryRoot(IEntityType ownerOrDefiningEntityType, IEntityType entityType, String navigationName) at Microsoft.EntityFrameworkCore.Internal.EntityFinder1.BuildQueryRoot(IEntityType entityType)
at Microsoft.EntityFrameworkCore.Internal.EntityFinder1..ctor(IStateManager stateManager, IDbSetSource setSource, IDbSetCache setCache, IEntityType entityType) at Microsoft.EntityFrameworkCore.Internal.EntityFinderSource.<>c__31.b__3_0(IStateManager s, IDbSetSource src, IDbSetCache c, IEntityType t)
at Microsoft.EntityFrameworkCore.Internal.EntityFinderSource.Create(IStateManager stateManager, IDbSetSource setSource, IDbSetCache setCache, IEntityType type)
at Microsoft.EntityFrameworkCore.Internal.EntityFinderFactory.Create(IEntityType type)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.CreateEntityFinder(IEntityType entityType)
at Microsoft.EntityFrameworkCore.ChangeTracking.NavigationEntry.get_TargetFinder()
at Microsoft.EntityFrameworkCore.ChangeTracking.NavigationEntry.Query()
at Microsoft.EntityFrameworkCore.ChangeTracking.CollectionEntry.Query()
at Microsoft.EntityFrameworkCore.ChangeTracking.CollectionEntry`2.Query()
at RelatedEntitiesLoading.Program.Main(String[] args) in \Program.cs:line 46

This exception was originally thrown at this call stack:
System.Linq.Expressions.Expression.ValidateLambdaArgs(System.Type, ref System.Linq.Expressions.Expression, System.Collections.ObjectModel.ReadOnlyCollection<System.Linq.Expressions.ParameterExpression>, string)
System.Linq.Expressions.Expression.Lambda(System.Linq.Expressions.Expression, string, bool, System.Collections.Generic.IEnumerable<System.Linq.Expressions.ParameterExpression>)
System.Linq.Expressions.Expression.Lambda(System.Linq.Expressions.Expression, bool, System.Collections.Generic.IEnumerable<System.Linq.Expressions.ParameterExpression>)
System.Linq.Expressions.Expression.Lambda(System.Linq.Expressions.Expression, System.Linq.Expressions.ParameterExpression[])
Microsoft.EntityFrameworkCore.Internal.EntityFinder.Select<TSource, TResult>(System.Linq.IQueryable, string)

Inner Exception 1:
ArgumentException: Expression of type 'System.Collections.Generic.List`1[Post]' cannot be used for return type 'Post'

### Further technical details

EF Core version:
Database provider: ( Microsoft.EntityFrameworkCore.Sqlite)
Target framework: (e.g. .NET Core 3.1+)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by m-khooryani** [comment]
Exception Detail: 
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.BuildQueryRoot(IEntityType ownerOrDefiningEntityType, IEntityType entityType, String navigationName)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.BuildQueryRoot(IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1..ctor(IStateManager stateManager, IDbSetSource setSource, IDbSetCache setCache, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinderSource.<>c__3`1.<CreateConstructor>b__3_0(IStateManager s, IDbSetSource src, IDbSetCache c, IEntityType t)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinderSource.Create(IStateManager stateManager, IDbSetSource setSource, IDbSetCache setCache, IEntityType type)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinderFactory.Create(IEntityType type)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.CreateEntityFinder(IEntityType entityType)
   at Microsoft.EntityFrameworkCore.ChangeTracking.NavigationEntry.get_TargetFinder()
   at Microsoft.EntityFrameworkCore.ChangeTracking.NavigationEntry.Query()
   at Microsoft.EntityFrameworkCore.ChangeTracking.CollectionEntry.Query()
   at Microsoft.EntityFrameworkCore.ChangeTracking.CollectionEntry`2.Query()
   at RelatedEntitiesLoading.Program.Main(String[] args) in C:\Users\Mojtaba\Documents\Visual Studio 2019\projects\EFCore_InMemoryTest\RelatedEntitiesLoading\Program.cs:line 46

  This exception was originally thrown at this call stack:
    System.Linq.Expressions.Expression.ValidateLambdaArgs(System.Type, ref System.Linq.Expressions.Expression, System.Collections.ObjectModel.ReadOnlyCollection<System.Linq.Expressions.ParameterExpression>, string)
    System.Linq.Expressions.Expression.Lambda<TDelegate>(System.Linq.Expressions.Expression, string, bool, System.Collections.Generic.IEnumerable<System.Linq.Expressions.ParameterExpression>)
    System.Linq.Expressions.Expression.Lambda<TDelegate>(System.Linq.Expressions.Expression, bool, System.Collections.Generic.IEnumerable<System.Linq.Expressions.ParameterExpression>)
    System.Linq.Expressions.Expression.Lambda<TDelegate>(System.Linq.Expressions.Expression, System.Linq.Expressions.ParameterExpression[])
    Microsoft.EntityFrameworkCore.Internal.EntityFinder<TEntity>.Select<TSource, TResult>(System.Linq.IQueryable<TSource>, string)

Inner Exception 1:
ArgumentException: Expression of type 'System.Collections.Generic.List`1[RelatedEntitiesLoading.Post]' cannot be used for return type 'RelatedEntitiesLoading.Post'

**Comment by ajcvickers** [comment]
Note for team: repros on latest daily.

**Comment by ajcvickers** [comment]
@SierraNL This issue hasn't met the bar for being fixed in a patch release. See the [planning process](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning) for more information.
