### ISSUE TITLE
SqLite shadow discriminator property thrown NullReferenceException

### ISSUE THREAD

**Issue by voronov-maxim** [dotnet/efcore#22119]
EF Core 5.0 Shadow discriminator property thrown NullReferenceException  when HasData.
EF Core 3.1 Works without exception.

### Steps to reproduce
``` C#
public abstract class BaseEntity
{
    public int Id { get; set; }
}

public class Derive1Entity : BaseEntity
{
    public string Name { get; set; }
}

public class Derive2Entity : BaseEntity
{
    public string Name { get; set; }
}

public class DescrinminatorContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite("DataSource=:memory:");
        base.OnConfiguring(optionsBuilder);
    }
    protected override void OnModelCreating(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BaseEntity>()
            .HasDiscriminator<int>("ClassType")
            .HasValue<Derive1Entity>(1)
            .HasValue<Derive2Entity>(2);
        modelBuilder.Entity<Derive1Entity>().HasData(
            new Derive1Entity()
            {
                Id = 1,
                Name = "Derive1Entity"
            });
        base.OnModelCreating(modelBuilder);
    }
}

private static void DescriminatorTest()
{
    using var context = new DescrinminatorContext();
    context.Database.EnsureCreated();
}
```
Thrown exception:
System.NullReferenceException: 'Object reference not set to an instance of an object.'

```
Stack trace:
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalMixedEntityEntry..ctor(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryFactory.NewInternalEntityEntry(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryFactory.Create(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.CreateEntry(IDictionary`2 values, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Update.Internal.UpdateAdapter.CreateEntry(IDictionary`2 values, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.TrackData(IRelationalModel source, IRelationalModel target, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.<GetDataOperations>d__75.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IRelationalModel source, IRelationalModel target)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.GetCreateTablesCommands(MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.CreateTables()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
   at OdataToEntity.Test.GraphQL.Program.DescriminatorTest() in D:\vorona\OdataToEntity\test\OdataToEntity.Test.GraphQL\Program.cs:line 107
```

### Further technical details
EF Core version: 5.0.0-rc.1.20417.7
Database provider: SqLite
Target framework: .NET Core 5.0 Preview 8
Operating system: Windows 10 Pro 2004 
IDE: Visual Studio 2019 16.8.0 Preview 1.0

**Comment by groege** [comment]
Is this possibly connected?
https://github.com/dotnet/efcore/issues/22189

**Comment by voronov-maxim** [comment]
> Is this possibly connected?
> #22189

This error is caused by null value in discriminator, when method HasValue create derived entity.
