### ISSUE TITLE
join is translated to SQL incorrectly

### ISSUE THREAD

**Issue by tnovacik** [dotnet/efcore#22142]
We have made an upgrade EF from 2.2 to version 3.1 and we are facing a breaking functionality.
The demo program is attached.
[JoinOnToCastProblem.zip](https://github.com/dotnet/efcore/files/5104011/JoinOnToCastProblem.zip)

### Steps to reproduce

Problematic LINQ query is:
``` C#
                int? input = null; // this is result of previous query, result can be null!
                
                var entities  = from a in context.Entities
                    join b in context.Entities
                        on new
                        {
                            a = a.Id,
                            b = input // b = (int?)null is working, but we need pass input as parameter
                        }
                        equals new
                        {
                            a = b.Id,
                            b = (int?)b.FkId
                        }
                    select new
                    {
                        a.Id
                    };
```

When you run it under EF 2.2 it generates query:
``` SQL
SELECT [a].[Id]
FROM [Entities] AS [a]
INNER JOIN [Entities] AS [b] ON ([a].[Id] = [b].[Id]) AND [b].[FkId] IS NULL
```
Under version 3.1.x it generates syntactically incorrect query:
``` SQL
SELECT [e].[Id]
FROM [Entities] AS [e]
INNER JOIN [Entities] AS [e0] ON CAST(0 AS bit)
``` 
And program throws the exception:

Unhandled exception. Microsoft.Data.SqlClient.SqlException (0x80131904): An expression of non-boolean type specified in a context where a condition is expected, near ')'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at JoinOnToCastProblem.Program.Main(String[] args) in C:\Work\JoinOnToCastProblem\Program.cs:line 98

### Further technical details

EF Core version: 3.1.7
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.1)
Operating system: Windows, OSX
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by smitpatel** [comment]
Generated SQL in 5.0 preview7
```SQL
      SELECT [e].[Id]
      FROM [Entities] AS [e]
      INNER JOIN [Entities] AS [e0] ON 0 = 1
```
So we no longer generate invalid SQL.
The translation is correct since `b.FkId` is of type `int` so it cannot take null values ever. So comparing it to null in join predicate will return false always. This is the optimization not applied in 2.2 query. Join condition in 2.2 query is 
`([a].[Id] = [b].[Id]) AND [b].[FkId] IS NULL` but `[b].[FkId]` is never null so whole condition becomes false.

**Comment by martin-hronsky** [comment]
> _firstOrDefault.FirstOrDefault() does not use the range variable in the query and can be evaluated independently from the query so it got evaluated before the query. If you inline it, it will evaluate whole thing as one query.

Is this aproach correct? Most of the people does not bother with writting all those LINQ expressions as one complex expression just have it then automatically separated into many DB calls. Why there is such automatism implemented? Why EF3 does not let developer decide if he wants to have separate DB call (and he will call FirstOrDefault in advance) or he wants to have number of DB calls as low as possible (and translate LINQ query into DB query as he written it if possible).
