### ISSUE TITLE
Incorrect SQL Being Generated for Add Days and MySql

### ISSUE THREAD

**Issue by rolesvillesoftware** [dotnet/efcore#22199]
### Error Details

Connector: MySql.Data.EntityFrameworkCore
EntityFrameWork Core Version: 3.1.6
DotNet Core Framework: 3.1.401
MySql Version: 8.0.19 (Percona)

Translated SQL for using AddDays in the Where clause is causing a SQL Syntax error... 

C#:
```
this.queryable.Where(item => (item.StartAt ?? DateTime.MinValue) < DateTime.Now.AddDays(request.AllowFutureDays.Value));
```

Translated SQL:
```
WHERE COALESCE(`c`.`StartAt`, '0001-01-01 00:00:00.000000') < DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL CAST(@__p_1 AS int) day)
```

The error is in the CAST statement - int is not a valid cast option. ([MySql Dev Docs](https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_cast)). The correct value looks like it should be SIGNED in this instance. 

Here is the full error stack:
```
System.Exception : Error processing command: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'int) day)' at line 13
  ----> MySql.Data.MySqlClient.MySqlException : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'int) day)' at line 13
Data:
  Server Error Code: 1064


   at TiberQueryLibrary.QueryBase`2.RunQuery(Func`1 action, Boolean throwException) in /Users/bryanlenihan/TiberProjects/TiberDWContext/TiberQueryLibrary/QueryBase.cs:line 271
   at TiberQueryLibrary.QueryBase`4.Run() in /Users/bryanlenihan/TiberProjects/TiberDWContext/TiberQueryLibrary/QueryBase.cs:line 305
   at TiberQueryLibrary.QueryBase`4.Query(TRequest request) in /Users/bryanlenihan/TiberProjects/TiberDWContext/TiberQueryLibrary/QueryBase.cs:line 295
   at TiberQueryLibrary.CanvasDw.Services.CanvasDwService.Query(ICanvasCourseListRequest request) in /Users/bryanlenihan/TiberProjects/TiberDWContext/TiberQueryLibrary/CanvasDw/Services/CanvasDwService.cs:line 22
   at TiberQueryTests.CanvasDwTests.TestGetPartnerCoursesActiveIn() in /Users/bryanlenihan/TiberProjects/TiberDWContext/TiberQueryTests/CanvasDwTests.cs:line 78
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
--MySqlException
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at MySql.Data.EntityFrameworkCore.Storage.Internal.MySQLExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at TiberQueryLibrary.QueryBase`2.Process() in /Users/bryanlenihan/TiberProjects/TiberDWContext/TiberQueryLibrary/QueryBase.cs:line 230
   at TiberQueryLibrary.QueryBase`2.Process(Func`2 converter) in /Users/bryanlenihan/TiberProjects/TiberDWContext/TiberQueryLibrary/QueryBase.cs:line 235
   at TiberQueryLibrary.QueryBase`2.RunQuery(Func`1 action, Boolean throwException) in /Users/bryanlenihan/TiberProjects/TiberDWContext/TiberQueryLibrary/QueryBase.cs:line 
```

### Further technical details

EF Core version: 3.1.6
Database provider: MySql.Data.EntityFrameworkCore
Target framework: 3.1
Operating system: Mac
IDE: Visual Studio for Mac

### Side Notes:
Pomelo is not an option for us due to compatibility issues with our monitoring software.

**Comment by ajcvickers** [comment]
@rolesvillesoftware This is an issue with the MySQL provider which is owned by Oracle. You will need to report the issue to them.
