### ISSUE TITLE
Add-Migration NullReferenceException using App.config. Failing to find config

### ISSUE THREAD

**Issue by TimMcGilly** [dotnet/efcore#22205]
I have 3 projects: a DataAccess(.net standard) with dbcontext, a UI project (wpf .net core startup project) and model project (.net standard).
I have a file called App.config in both UI and DataAccess projects with this code
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <connectionStrings>
    <add name="ScreenTimeTrackerDb"
         connectionString="Server=.\SQLExpress;Database=ScreenTimeTracker;Trusted_Connection=True;" />
  </connectionStrings>
</configuration>
```

I am loading the configuration with `System.Configuration` and this override
```
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(ConfigurationManager.ConnectionStrings["ScreenTimeTrackerDb"].ConnectionString);
        }
```

When running Add-Migration it throws a null-reference exception due to not finding configuration.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ScreenTimeTracker.DataAccess.ScreenTimeTrackerDbContex.OnConfiguring(DbContextOptionsBuilder optionsBuilder) in C:\Users\timmc\source\repos\ScreenTimeTracker\ScreenTimeTracker.DataAccess\ScreenTimeTrackerDbContex.cs:line 13
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

This is run from within visual studio from the Package Managed Console with Default project set to DataAccess and the startup project set to UI.

Using
```
var configfile = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.None);
            var path = configfile.FilePath;
            throw new System.Exception(path);
```
it appears it is attempting to open 
```
System.Exception: C:\Users\timmc\source\repos\ScreenTimeTracker\ScreenTimeTracker.UI\bin\Debug\netcoreapp3.1\ef.dll.config` 
whereas the configuration files produced my project are
`ScreenTimeTracker.DataAccess.dll.config`
`ScreenTimeTracker.UI.dll.config`.
```

Changing the `App.config` Copy to Output to Copy Always does not resolve the issue. 

### Further technical details

EF Core version: 3.1.7
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET Core 3.1, .Net Standard 2.1
Operating system:
IDE: Visual Studio 2019 16.7.2

**Comment by ajcvickers** [comment]
@bricelam to find dupe.

**Comment by bricelam** [comment]
Blocked on https://github.com/dotnet/runtime/issues/931

**Comment by walter-tudorin-ross-rlb** [comment]
Experiencing the same issue as described by TimMcGilly. Any progress on this?

**Comment by skrabbe001** [comment]
What is the status on this, i.e. is there a deadline for when this will be fixed? I have had the same problem for approximately a year, but didn't report it.

**Comment by ajcvickers** [comment]
@skrabbe001 This is currently planned for EF Core 7.0, as indicated by the milestone. This will be released with .NET 7. See the [planning process](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning) for more information on how we plan what gets fixed in a release.
