### ISSUE TITLE
ef migration fails on coreclr (FileNotFoundException)

### ISSUE THREAD

**Issue by jsacapdev** [dotnet/efcore#2228]
project.json:

```
{
  "version": "1.0.0-*",
  "dependencies": {
    "CoreUtil.Common": "1.0.0.1",
    "EntityFramework": "7.0.0-*",
    "EntityFramework.SqlServer": "7.0.0-*",
    "EntityFramework.Commands": "7.0.0-*",
    "Microsoft.AspNet.Mvc": "6.0.0-*",
    "Microsoft.AspNet.Diagnostics": "1.0.0-*",
    "Microsoft.Framework.ConfigurationModel.Json": "1.0.0-*",
    "Kestrel": "1.0.0-*"
  },
  "commands": {
    "ef": "EntityFramework.Commands",
    "kestrel": "Microsoft.AspNet.Hosting --server Kestrel --server.urls http://localhost:5001"
  },
  "frameworks": {
    "dnx451": { },
    "dnxcore50": {
      "dependencies": {
      }
    }
  },
}
```

using unstable coreclr:

```
dnvm upgrade -u -r coreclr -arch x64 -a default
```

output from command line (with DNX_TRACE=1):

```
C:\Git\loggingservice\src\LoggingService>dnx . ef migration add initial
Loaded Module: dnx.coreclr.dll
Found DLL Export: CallApplicationMain
Information: [LoaderContainer]: Load name=Microsoft.Framework.ApplicationHost
Information: [PathBasedAssemblyLoader]: Loaded name=Microsoft.Framework.ApplicationHost in 1ms
Information: [LoaderContainer]: Load name=Microsoft.Framework.Runtime
Information: [PathBasedAssemblyLoader]: Loaded name=Microsoft.Framework.Runtime in 1ms
Information: [LoaderContainer]: Load name=Microsoft.Framework.Runtime.Caching
Information: [PathBasedAssemblyLoader]: Loaded name=Microsoft.Framework.Runtime.Caching in 0ms
Information: [DefaultHost]: Project path: C:\Git\loggingservice\src\LoggingService
Information: [DefaultHost]: Project root: C:\Git\loggingservice
Information: [DefaultHost]: Packages path: C:\Users\tdu\.dnx\packages
Information: [DependencyWalker]: Walking dependency graph for 'LoggingService DNXCore,Version=v5.0'.
Information: [WalkContext]: Graph walk stage 1 took in 21ms
Information: [DependencyWalker]: Graph walk took 27ms.
Information: [ServicingIndex]: Servicing index not found at C:\Program Files (x86)\DNX\Servicing\index.txt
Information: [WalkContext]: Populate took 33ms
Information: [DependencyWalker]: Resolved dependencies for LoggingService in 63ms
Information: [LoaderContainer]: Load name=EntityFramework.Commands
Information: [NuGetAssemblyLoader]: Loaded name=EntityFramework.Commands in 0ms
Information: [LoaderContainer]: Load name=Microsoft.Framework.Logging.Abstractions
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.Framework.Logging.Abstractions in 0ms
Information: [LoaderContainer]: Load name=System.Interactive.Async
Information: [NuGetAssemblyLoader]: Loaded name=System.Interactive.Async in 4ms
Information: [LoaderContainer]: Load name=LoggingService
Information: [ProjectLibraryExportProvider]: GetLibraryExport(LoggingService, DNXCore,Version=v5.0, Debug, )
Information: [LoaderContainer]: Load name=Microsoft.Framework.Runtime.Roslyn
Information: [PathBasedAssemblyLoader]: Loaded name=Microsoft.Framework.Runtime.Roslyn in 0ms
Information: [Microsoft.Framework.Runtime.Roslyn.RoslynProjectCompiler]: GetProjectReference(LoggingService, DNXCore,Version=v5.0, Debug, )
Information: [LoaderContainer]: Load name=Microsoft.Framework.Runtime.Roslyn.Abstractions
Information: [PathBasedAssemblyLoader]: Loaded name=Microsoft.Framework.Runtime.Roslyn.Abstractions in 0ms
Information: [DependencyWalker]: Walking dependency graph for 'LoggingService DNXCore,Version=v5.0'.
Information: [WalkContext]: Graph walk stage 1 took in 23ms
Information: [DependencyWalker]: Graph walk took 25ms.
Information: [WalkContext]: Populate took 6ms
Information: [DependencyWalker]: Resolved dependencies for LoggingService in 34ms
Information: [ProjectExportProviderHelper]: Resolving references for 'LoggingService'
Information: [ProjectExportProviderHelper]: Resolved 124 references for 'LoggingService' in 11ms
Information: [LoaderContainer]: Load name=Microsoft.CodeAnalysis
Information: [PathBasedAssemblyLoader]: Loaded name=Microsoft.CodeAnalysis in 76ms
Information: [LoaderContainer]: Load name=Microsoft.CodeAnalysis.CSharp
Information: [PathBasedAssemblyLoader]: Loaded name=Microsoft.CodeAnalysis.CSharp in 159ms
Information: [LoaderContainer]: Load name=Microsoft.Framework.Runtime.Roslyn.Common
Information: [PathBasedAssemblyLoader]: Loaded name=Microsoft.Framework.Runtime.Roslyn.Common in 0ms
Information: [RoslynCompiler]: Compiling 'LoggingService'
Information: [LoaderContainer]: Load name=System.Collections.Immutable
Information: [PathBasedAssemblyLoader]: Loaded name=System.Collections.Immutable in 1ms
Information: [LoaderContainer]: Load name=System.Security.Cryptography.Hashing
Information: [PathBasedAssemblyLoader]: Loaded name=System.Security.Cryptography.Hashing in 0ms
Information: [LoaderContainer]: Load name=System.Security.Cryptography.Hashing.Algorithms
Information: [PathBasedAssemblyLoader]: Loaded name=System.Security.Cryptography.Hashing.Algorithms in 0ms
Information: [LoaderContainer]: Load name=System.Security.Cryptography.Encryption
Information: [PathBasedAssemblyLoader]: Loaded name=System.Security.Cryptography.Encryption in 0ms
Information: [LoaderContainer]: Load name=System.Reflection.Metadata
Information: [PathBasedAssemblyLoader]: Loaded name=System.Reflection.Metadata in 1ms
Information: [RoslynCompiler]: Compiled 'LoggingService' in 264ms
Information: [RoslynProjectReference]: Emitting assembly for LoggingService
Information: [LoaderContainer]: Load name=System.Threading.Tasks.Parallel
Information: [PathBasedAssemblyLoader]: Loaded name=System.Threading.Tasks.Parallel in 0ms
Information: [LoaderContainer]: Load name=Microsoft.CodeAnalysis.CSharp.resources
Information: [LoaderContainer]: Load name=Microsoft.CodeAnalysis.CSharp.resources
Information: [CompilationContext]: Generating resources for LoggingService
Information: [CompilationContext]: Generated resources for LoggingService in 19ms
Information: [RoslynProjectReference]: Emitted LoggingService in 343ms
Information: [ProjectAssemblyLoader]: Loaded name=LoggingService in 934ms
Information: [LoaderContainer]: Load name=Microsoft.Framework.Logging
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.Framework.Logging in 0ms
Information: [LoaderContainer]: Load name=EntityFramework.Core
Information: [NuGetAssemblyLoader]: Loaded name=EntityFramework.Core in 1ms
Information: [LoaderContainer]: Load name=EntityFramework.Relational.Design
Information: [NuGetAssemblyLoader]: Loaded name=EntityFramework.Relational.Design in 0ms
Information: [LoaderContainer]: Load name=EntityFramework.Relational
Information: [NuGetAssemblyLoader]: Loaded name=EntityFramework.Relational in 1ms
Information: [LoaderContainer]: Load name=System.IO.MemoryMappedFiles
Information: [LoaderContainer]: Load name=System.Core
Information: [LoaderContainer]: Load name=System.IO.MemoryMappedFiles
Information: [LoaderContainer]: Load name=System.Core
Information: [LoaderContainer]: Load name=System
System.IO.FileNotFoundException: Could not load file or assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. T
he system cannot find the file specified.
File name: 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' ---> System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark,
 IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMa
rk, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.Data.Entity.Relational.Design.Templating.Compilation.MetadataReferencesProvider.AddDefaultReferences()
   at Microsoft.Data.Entity.Commands.DatabaseTool..ctor(IServiceProvider serviceProvider, ILoggerProvider loggerProvider)
   at Microsoft.Data.Entity.Commands.Program..ctor(IServiceProvider serviceProvider, IApplicationEnvironment appEnv, ILibraryManager libraryManager, IRuntimeEnvironment r
untimeEnv)
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)

C:\Git\loggingservice\src\LoggingService>
```

switch to clr:

```
dnvm upgrade -u -r clr -arch x64 -a default
```

...and works as expected:

```
C:\Git\loggingservice\src\LoggingService>dnx . ef migration add initial
Loaded Module: dnx.clr.dll
Found DLL Export: CallApplicationMain
Information: [DefaultHost]: Project path: C:\Git\loggingservice\src\LoggingService
Information: [DefaultHost]: Project root: C:\Git\loggingservice
Information: [DefaultHost]: Packages path: C:\Users\tdu\.dnx\packages
Information: [DependencyWalker]: Walking dependency graph for 'LoggingService DNX,Version=v4.5.1'.
Information: [WalkContext]: Graph walk stage 1 took in 130ms
Information: [DependencyWalker]: Graph walk took 135ms.
Information: [ServicingIndex]: Servicing index not found at C:\Program Files (x86)\DNX\Servicing\index.txt
Information: [WalkContext]: Populate took 55ms
Information: [DependencyWalker]: Resolved dependencies for LoggingService in 195ms
Information: [LoaderContainer]: Load name=EntityFramework.Commands
Information: [NuGetAssemblyLoader]: Loaded name=EntityFramework.Commands in 121ms
Information: [LoaderContainer]: Load name=Microsoft.Framework.Logging.Abstractions
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.Framework.Logging.Abstractions in 5ms
Information: [LoaderContainer]: Load name=System.Interactive.Async
Information: [NuGetAssemblyLoader]: Loaded name=System.Interactive.Async in 6ms
Information: [LoaderContainer]: Load name=LoggingService
Information: [ProjectLibraryExportProvider]: GetLibraryExport(LoggingService, DNX,Version=v4.5.1, Debug, )
Information: [Microsoft.Framework.Runtime.Roslyn.RoslynProjectCompiler]: GetProjectReference(LoggingService, DNX,Version=v4.5.1, Debug, )
Information: [DependencyWalker]: Walking dependency graph for 'LoggingService DNX,Version=v4.5.1'.
Information: [WalkContext]: Graph walk stage 1 took in 3ms
Information: [DependencyWalker]: Graph walk took 3ms.
Information: [WalkContext]: Populate took 7ms
Information: [DependencyWalker]: Resolved dependencies for LoggingService in 11ms
Information: [ProjectExportProviderHelper]: Resolving references for 'LoggingService'
Information: [ProjectExportProviderHelper]: Resolved 95 references for 'LoggingService' in 40ms
Information: [RoslynCompiler]: Compiling 'LoggingService'
Information: [LoaderContainer]: Load name=System.Security.Cryptography.Hashing
Information: [LoaderContainer]: Load name=System.Security.Cryptography.Hashing
Information: [LoaderContainer]: Load name=System.Security.Cryptography.Hashing.Algorithms
Information: [LoaderContainer]: Load name=System.Security.Cryptography.Hashing.Algorithms
Information: [LoaderContainer]: Load name=System.IO.FileSystem
Information: [LoaderContainer]: Load name=System.IO.FileSystem
Information: [RoslynCompiler]: Compiled 'LoggingService' in 499ms
Information: [RoslynProjectReference]: Emitting assembly for LoggingService
Information: [CompilationContext]: Generating resources for LoggingService
Information: [CompilationContext]: Generated resources for LoggingService in 15ms
Information: [RoslynProjectReference]: Emitted LoggingService in 780ms
Information: [ProjectAssemblyLoader]: Loaded name=LoggingService in 1448ms
Information: [LoaderContainer]: Load name=Microsoft.Framework.Logging
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.Framework.Logging in 1ms
Information: [LoaderContainer]: Load name=EntityFramework.Core
Information: [NuGetAssemblyLoader]: Loaded name=EntityFramework.Core in 2ms
Information: [LoaderContainer]: Load name=EntityFramework.Relational.Design
Information: [NuGetAssemblyLoader]: Loaded name=EntityFramework.Relational.Design in 2ms
Information: [LoaderContainer]: Load name=EntityFramework.Relational
Information: [NuGetAssemblyLoader]: Loaded name=EntityFramework.Relational in 6ms
Information: [LoaderContainer]: Load name=System.IO.FileSystem
Information: [LoaderContainer]: Load name=System.IO.FileSystem
Information: [LoaderContainer]: Load name=System.IO.MemoryMappedFiles
Information: [LoaderContainer]: Load name=System.IO.MemoryMappedFiles
Information: [LoaderContainer]: Load name=System.IO.MemoryMappedFiles
Information: [LoaderContainer]: Load name=System.IO.MemoryMappedFiles
Information: [LoaderContainer]: Load name=System.IO.MemoryMappedFiles
Information: [LoaderContainer]: Load name=System.IO.MemoryMappedFiles
Information: [LoaderContainer]: Load name=System.IO.MemoryMappedFiles
Information: [LoaderContainer]: Load name=System.IO.MemoryMappedFiles
Information: [LoaderContainer]: Load name=Microsoft.Framework.DependencyInjection.Abstractions
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.Framework.DependencyInjection.Abstractions in 5ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Mvc.Core
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.AspNet.Mvc.Core in 7ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Mvc.Abstractions
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.AspNet.Mvc.Abstractions in 1ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Hosting.Abstractions
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.AspNet.Hosting.Abstractions in 1ms
Using context 'LoggingDbContext'.
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Hosting
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.AspNet.Hosting in 1ms
Information: [LoaderContainer]: Load name=Microsoft.Framework.ConfigurationModel.Abstractions
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.Framework.ConfigurationModel.Abstractions in 1ms
Information: [LoaderContainer]: Load name=Microsoft.Framework.ConfigurationModel
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.Framework.ConfigurationModel in 5ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.FileProviders.Abstractions
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.AspNet.FileProviders.Abstractions in 1ms
Information: [LoaderContainer]: Load name=Microsoft.Framework.DependencyInjection
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.Framework.DependencyInjection in 1ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Hosting.Server.Abstractions
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.AspNet.Hosting.Server.Abstractions in 1ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Http.Abstractions
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.AspNet.Http.Abstractions in 5ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.FileProviders.Physical
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.AspNet.FileProviders.Physical in 1ms
Information: [LoaderContainer]: Load name=Microsoft.Framework.Caching.Abstractions
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.Framework.Caching.Abstractions in 1ms
Information: [LoaderContainer]: Load name=Newtonsoft.Json
Information: [NuGetAssemblyLoader]: Loaded name=Newtonsoft.Json in 6ms
Information: [LoaderContainer]: Load name=CoreUtil.Common
Information: [NuGetAssemblyLoader]: Loaded name=CoreUtil.Common in 5ms
Information: [LoaderContainer]: Load name=Microsoft.Framework.ConfigurationModel.Json
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.Framework.ConfigurationModel.Json in 1ms
Information: [LoaderContainer]: Load name=EntityFramework.SqlServer
Information: [NuGetAssemblyLoader]: Loaded name=EntityFramework.SqlServer in 1ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Mvc
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.AspNet.Mvc in 1ms
Information: [LoaderContainer]: Load name=Microsoft.Framework.Caching.Memory
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.Framework.Caching.Memory in 1ms
Information: [LoaderContainer]: Load name=Microsoft.Framework.OptionsModel
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.Framework.OptionsModel in 1ms
Information: [LoaderContainer]: Load name=Remotion.Linq
Information: [NuGetAssemblyLoader]: Loaded name=Remotion.Linq in 6ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Mvc.Razor
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.AspNet.Mvc.Razor in 2ms
Information: [LoaderContainer]: Load name=Microsoft.Net.Http.Headers
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.Net.Http.Headers in 1ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Mvc.Razor.Host
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.AspNet.Mvc.Razor.Host in 1ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Razor
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.AspNet.Razor in 1ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Razor.Runtime
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.AspNet.Razor.Runtime in 2ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Mvc.ApiExplorer
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.AspNet.Mvc.ApiExplorer in 1ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.DataProtection
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.AspNet.DataProtection in 6ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Routing
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.AspNet.Routing in 1ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Cors.Core
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.AspNet.Cors.Core in 1ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Authorization
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.AspNet.Authorization in 1ms
Information: [LoaderContainer]: Load name=Microsoft.Framework.WebEncoders
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.Framework.WebEncoders in 1ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Cryptography.Internal
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.AspNet.Cryptography.Internal in 1ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.DataProtection.Abstractions
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.AspNet.DataProtection.Abstractions in 1ms
Information: [LoaderContainer]: Load name=Microsoft.Framework.WebEncoders.Core
Information: [NuGetAssemblyLoader]: Loaded name=Microsoft.Framework.WebEncoders.Core in 1ms
Writing migration to 'C:\Git\loggingservice\src\LoggingService\Migrations\20150519102611_initial.cs'.
Writing model snapshot to 'C:\Git\loggingservice\src\LoggingService\Migrations\LoggingDbContextModelSnapshot.cs'.
Done. To undo this action, use 'ef migration remove'.

C:\Git\loggingservice\src\LoggingService>
```

**Comment by jsacapdev** [comment]
Possibly related to (also using coreclr):

https://github.com/aspnet/EntityFramework/issues/2153

**Comment by bricelam** [comment]
Yes, this is the same issue.
