### ISSUE TITLE
Can not use Entity Framework Core 3.1 when set ENV LC_ALL and LANG in docker container

### ISSUE THREAD

**Issue by uopeydel** [dotnet/efcore#22386]
Now i use efcore v 3.1.7 in dotnet core  TargetFramework netcoreapp3.1 
I try to add this 2 line below into my docker file

```
    ENV LANG th_TH.UTF-8  
    ENV LANGUAGE th_TH:th 
```

These 2 line of config make my report can generate correctly language in dotnetcore v 2.1
With lib ReportServer ( Microsoft.VisualStudio.ConnectedService.Wcf  v15.0.40203.910)

But when i migrate to dotnetcore 3.1 and set that 2 env it make i can not query entity framework core 2.1 with this code 

`    
    var userLogedIn = await _uow.User.Where(w => w.empNo == dataEmpNo).AsNoTracking().FirstOrDefaultAsync();
`
It alway show error message like this 

```

    {
        "ex": {
            "ClassName": "Microsoft.Data.SqlClient.SqlException",
            "Message": "Invalid column name '__dataEmpNo_0'.",
            "Data": {
                "HelpLink.ProdName": "Microsoft SQL Server",
                "HelpLink.ProdVer": "14.00.1000",
                "HelpLink.EvtSrc": "MSSQLServer",
                "HelpLink.EvtID": "207",
                "HelpLink.BaseHelpUrl": "http://go.microsoft.com/fwlink",
                "HelpLink.LinkId": "20476",
                "SqlError 1": "Microsoft.Data.SqlClient.SqlError: Invalid column name '__dataEmpNo_0'."
            },
            "InnerException": null,
            "HelpURL": null,
            "StackTraceString": "   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()\n   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)\n   at ****.Services.UserService.Token(RequestUserLoginModel usermodel) in /*******/Services/UserService.cs:line 256\n   at ****.Controllers.UsersController.Token(RequestUserLoginModel userParam, String q) in /*******/Controllers/UsersController.cs:line 82",
            "RemoteStackTraceString": null,
            "RemoteStackIndex": 0,
            "ExceptionMethod": null,
            "HResult": -2146232060,
            "Source": "Core Microsoft SqlClient Data Provider",
            "WatsonBuckets": null,
            "Errors": null,
            "ClientConnectionId": "5206c80f-d8f8-4b12-81e7-b9c51539b6af"
        }
    }

```

And when I try to change var dataEmpNo into other name it will change error message

>  "Message": "Invalid column name '__dataEmpNo_0'."  

follow my variable name too. Same variable name is i use to query.
But when i remove config ENV LC_ALL and LANG    entity framework it work fine.
 
### Further technical details
 
Database provider:  Microsoft.EntityFrameworkCore.SqlServer  3.1.7 
Target framework: netcoreapp3.1
LangVersion 7.1
Microsoft.NET.Sdk.Web
Operating system: docker   mcr.microsoft.com/dotnet/core/sdk:3.1-buster
IDE:  . Visual Studio 2019 16.6.0
Microsoft.VisualStudio.ConnectedService.Wcf 15.0.40203.910

**Comment by smitpatel** [comment]
This issue is lacking enough information for us to effectively reproduce. Please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by uopeydel** [comment]
https://github.com/uopeydel/testdb

use this project step test is run command 

docker build --pull --rm -f "dockerfile" -t testdb:latest "."

docker run  -d -p 1144:443/tcp -p 1188:80/tcp   testdb:latest

and go to url 

 http://localhost:1188/api/Values/GetData


It will show you error message 

```
An unhandled exception occurred while processing the request.
SqlException: Invalid column name '__data_0'.
Microsoft.Data.SqlClient.SqlCommand+<>c.<ExecuteDbDataReaderAsync>b__164_0(Task<SqlDataReader> result)
```

Then comment line 

# ENV LANG th_TH.UTF-8  
# ENV LC_ALL th_TH.UTF-8 

in docker file 

then try to build docker and run again it will be work fine.

**Comment by uopeydel** [comment]
Any ideas update?

For now i think this is not relate just with **Entity Framework Core**

May be it happen because .netcore 3.1 sdk

I tried to create new docker file pushed today name  "dockerfile.v2"

You can run it by command 

`docker build --pull --rm -f "dockerfile.v2" -t testdb:latest "."`

If i have 2 line of this code 

`
ENV LC_ALL th_TH.UTF-8   
ENV LANG th_TH.UTF-8   
`

And run this command 

`
docker run  -p 1144:443/tcp -p 1188:80/tcp   testdb:latest
`

It will show this error message

`
docker run  -p 1144:443/tcp -p 1188:80/tcp   testdb:latest
watch : Polling file watcher is enabled
watch : Started
watch : System.ArgumentException: An item with the same key has already been added. Key: /app/FirstCodeDb/Controllers/
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.DotNet.Watcher.Internal.FileWatcher.AddDirectoryWatcher(String directory)
   at Microsoft.DotNet.Watcher.Internal.FileSetWatcher.GetChangedFileAsync(CancellationToken cancellationToken, Action startedWatching)
   at Microsoft.DotNet.Watcher.DotNetWatcher.WatchAsync(ProcessSpec processSpec, IFileSetFactory fileSetFactory, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Program.MainInternalAsync(IReporter reporter, String project, ICollection`1 args, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Program.RunAsync(String[] args)
watch : An unexpected error occurred
`

If i remove this 2 line 

`
ENV LC_ALL th_TH.UTF-8   
ENV LANG th_TH.UTF-8   
`

It will work fine.

**Comment by smitpatel** [comment]
@uopeydel - The error is certainly not in EF Core as we don't try to use those variables. It is likely limitation in SqlClient. Does your Sql Server installation has same locale settings as the one you are trying to use?

**Comment by uopeydel** [comment]
No , i just want to use it in backend server. Thoes variables  i set it for some lib can work fine with my language with out problem aboute a size and font.

**Comment by ajcvickers** [comment]
@uopeydel I'm transferring this to the dotnet runtime repo since the stack trace doesn't show anything data related.
