### ISSUE TITLE
[Tools] Add-Migration fails with "System.Runtime" not found

### ISSUE THREAD

**Issue by Skyppid** [dotnet/efcore#22388]
It's been a while since we last added a migration. We're running on the latest 2.2.6 version of EF Core. So far it worked splendidly but as I just tried to add a new migration, I always get this exception:

> Add-Migration TestXX
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly.GetEntryPoint(RuntimeAssembly assembly, ObjectHandleOnStack retMethod)
   at System.Reflection.RuntimeAssembly.get_EntryPoint()
   at Microsoft.AspNetCore.Hosting.WebHostBuilderFactory.WebHostFactoryResolver.ResolveWebHostBuilderFactory[TWebhost,TWebhostBuilder](Assembly assembly)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderFactory.WebHostFactoryResolver.ResolveWebHostFactory[TWebhost,TWebhostBuilder](Assembly assembly)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.CreateFromBuildWebHost(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.Create(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextTypes()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextType(String name)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
> === Pre-bind state information ===
LOG: DisplayName = System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///E:/Projekte/***
LOG: Initial PrivatePath = NULL
Calling assembly : *APPNAME*, Version=2021.0.56.23605, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: E:\Projekte\***.exe.config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: The same bind was seen before, and was failed with hr = 0x80070002.
Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
PM> 

### Steps to reproduce

I initially tried to fix issues when we had to update merge back into a stale branch from April since we had no time to work on the feature ever since. Back then I already created a migration which is older than the newest we have. Since this was work in progress I figured deleting it and recreating it ontop of the latest would likely fix this.

It doesn't work a single time. I tried several times and it's always the same error. I then switched back to the latest develop branch and tried adding a migration (the one mentioned above in the error output) and it turned out to be the same issue. I don't know what changed and since it's an `FileNotFoundException` I don't really know where to look.

### Further technical details

EF Core version: 2.2.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .Net Standard 2.0 (Project is mixed: .Net 4.7.2 WPF App and .Net Standard 2 libraries)
Operating system: Windows 10 x64
IDE: Visual Studio 2019.7.* (latest)

**Comment by bricelam** [comment]
Are you using user secrets? This look similar to the issue caused by not calling the generic version of `AddUserSecrets`.

`Assembly.EntryPoint()` is the bane of all tooling.

**Comment by Skyppid** [comment]
@bricelam No not really. I specified the credentials in code using the `SqlConnectionStringBuilder` but that's it. It worked previously anyway. My wild guess would be that something's not set up right (the tools). I switched to my colleague's computer and there it worked seamlessly. It only happens on my machine. I already tried reinstalling the EF tools and also tried installing them using CLI but it just didn't work (couldn't even use the tools via CLI).

**Comment by ajcvickers** [comment]
@Skyppid EF Core 2.2 and .NET Core 2.2 are [out-of-support](https://docs.microsoft.com/en-us/ef/core/what-is-new/). Please try with 3.1 or a 5.0 preview and report back if you're still running into issues.

**Comment by ajcvickers** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
