### ISSUE TITLE
Exception thrown while trying to retrieve `CollectionEntry` with new Many-to-Many configuration.

### ISSUE THREAD

**Issue by atiyar** [dotnet/efcore#22477]
Exception thrown while trying to retrieve `CollectionEntry` with `EntityEntry.Collection()` method in new many-to-many configuration.

### Steps to reproduce
Models -
```c#
public class Movie
{
    public int Id { get; set; }
    public string Title { get; set; }

    public IList<Genre> Genres { get; set; }
}

public class Genre
{
    public int Id { get; set; }
    public string Name { get; set; }

    public IList<Movie> Movies { get; set; }
}

public class MovieGenre
{
    public int MovieId { get; set; }
    public int GenreId { get; set; }

    public Movie Movie { get; set; }
    public Genre Genre { get; set; }
}
```
Configurartion -
```c#
public class MovieConfig : IEntityTypeConfiguration<Movie>
{
    public void Configure(EntityTypeBuilder<Movie> builder)
    {
	builder.ToTable("Movie");
	builder.HasKey(p => p.Id);
	builder.Property(p => p.Title).IsRequired(true).HasColumnType("nvarchar(64)");
    }
}

public class GenreConfig : IEntityTypeConfiguration<Genre>
{
    public void Configure(EntityTypeBuilder<Genre> builder)
    {
	builder.ToTable("Genre");
	builder.HasKey(p => p.Id);
	builder.Property(p => p.Name).IsRequired(true).HasColumnType("nvarchar(64)");

	builder.HasMany(p => p.Movies)
		.WithMany(p => p.Genres)
		.UsingEntity<MovieGenre>(
		mg => mg
		.HasOne(p => p.Movie)
		.WithMany()
		.HasForeignKey(e => e.MovieId)
		.OnDelete(DeleteBehavior.Cascade),
		mg => mg
		.HasOne(p => p.Genre)
		.WithMany()
		.HasForeignKey(p => p.GenreId)
		.OnDelete(DeleteBehavior.Cascade))
		.HasKey(p => new { p.MovieId, p.GenreId });
    }
}
```
Code that throws exception -
```c#
    var dbEntity = await context.Movies.FindAsync(id);
    var entry = context.Entry(dbEntity);
    var collection = entry.Collection(p => p.Genres);   // Or, var collection = entry.Collection("Genres"); 
```

**Exception:**  
The property 'Genres' on entity type 'Movie' could not be found. Ensure that the property exists and has been included in the model.

**StackTrace**
   at Microsoft.EntityFrameworkCore.ChangeTracking.NavigationEntry.GetNavigation(InternalEntityEntry internalEntry, String name, Boolean collection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.NavigationEntry..ctor(InternalEntityEntry internalEntry, String name, Boolean collection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.CollectionEntry..ctor(InternalEntityEntry internalEntry, String name)
   at Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry.Collection(String propertyName)
   at EF5.Service.MovieService.<UpdateAsync>d__5.MoveNext() in E:\Code\CoreEF\EF5.Xplore\EF5.Service\MovieService.cs:line 91
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EF5.Client.CrudOps.<Update_WithClientModel>d__5.MoveNext() in E:\Code\CoreEF\EF5.Xplore\EF5.Client\CrudOps.cs:line 72

### Further technical details

EF Core version: 5.0.0-preview.8.20407.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: <TargetFramework>net5.0</TargetFramework>
Operating system: Windows 10 Version 2004 (Build 19041.450)
IDE: Visual Studio 2019 16.7

**Comment by ajcvickers** [comment]
@atiyar This part of many-to-many was not complete in preview 8. This is working in the daily builds and the fix will be included in RC1.

**Comment by atiyar** [comment]
@ajcvickers Just tested using daily build. Thank you.
