### ISSUE TITLE
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Storage.IRelationalTypeMappingSource' ...

### ISSUE THREAD

**Issue by deokershesh** [dotnet/efcore#22473]
I am trying to run, "dotnet ef dbcontext **scaffold** "Database=sheshefcoredb1; server=lo_informix1410;UID=informix; PWD=xxxx" Informix.EntityFramework.Core -o Models --project MyApp.csproj -v ", command to create model from the database tables.

I am attaching the MyApp.csproj used as MyApp.csproj.txt file.

[MyApp.csproj.txt](https://github.com/dotnet/efcore/files/5199614/MyApp.csproj.txt)

Below is the output of the above command. What mistake I might be doing?
=====================================
D:\shesh\EntityFrameworkCore\scaffold>dotnet ef dbcontext scaffold "Database=sheshefcoredb1; server=lo_informix1410;UID=informix; PWD=xxxx" Informix.EntityFramework.Core -o Models --project MyApp.csproj -v
Using project 'MyApp.csproj'.
Using startup project 'D:\shesh\EntityFrameworkCore\scaffold\MyApp.csproj'.
Writing 'obj\MyApp.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\sheshnarayan.a\AppData\Local\Temp\tmp956C.tmp /verbosity:quiet /nologo MyApp.csproj
Writing 'D:\shesh\EntityFrameworkCore\scaffold\obj\MyApp.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\sheshnarayan.a\AppData\Local\Temp\tmp99E2.tmp /verbosity:quiet /nologo D:\shesh\EntityFrameworkCore\scaffold\MyApp.csproj
Build started...
dotnet build D:\shesh\EntityFrameworkCore\scaffold\MyApp.csproj /verbosity:quiet /nologo

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:14.39
Build succeeded.
dotnet exec --depsfile D:\shesh\EntityFrameworkCore\scaffold\bin\x64\Debug\netcoreapp3.1\MyApp.deps.json --additionalprobingpath C:\Users\sheshnarayan.a\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig D:\shesh\EntityFrameworkCore\scaffold\bin\x64\Debug\netcoreapp3.1\MyApp.runtimeconfig.json C:\Users\sheshnarayan.a\.dotnet\tools\.store\dotnet-ef\3.1.5\dotnet-ef\3.1.5\tools\netcoreapp3.1\any\tools\netcoreapp2.0\any\ef.dll dbcontext scaffold "Database=sheshefcoredb1; server=lo_informix1410;UID=informix; PWD=xxxx" Informix.EntityFramework.Core -o Models --assembly D:\shesh\EntityFrameworkCore\scaffold\bin\x64\Debug\netcoreapp3.1\MyApp.dll --startup-assembly D:\shesh\EntityFrameworkCore\scaffold\bin\x64\Debug\netcoreapp3.1\MyApp.dll --project-dir D:\shesh\EntityFrameworkCore\scaffold\ --language C# --working-dir D:\shesh\EntityFrameworkCore\scaffold --verbose --root-namespace MyApp
Using assembly 'MyApp'.
Using startup assembly 'MyApp'.
Using application base 'D:\shesh\EntityFrameworkCore\scaffold\bin\x64\Debug\netcoreapp3.1'.
Using working directory 'D:\shesh\EntityFrameworkCore\scaffold'.
Using root namespace 'MyApp'.
Using project directory 'D:\shesh\EntityFrameworkCore\scaffold\'.
The EF Core tools version '3.1.5' is older than that of the runtime '5.0.0-preview.5.20278.2'. Update the tools for the latest features and bug fixes.
Finding design-time services for provider 'Informix.EntityFramework.Core'...
Using design-time services from provider 'Informix.EntityFramework.Core'.
Finding design-time services referenced by assembly 'MyApp'.
No referenced design-time services were found.
Finding IDesignTimeServices implementations in assembly 'MyApp'...
No design-time services were found.
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Storage.IRelationalTypeMappingSource' while attempting to activate 'Microsoft.EntityFrameworkCore.Scaffolding.Internal.ScaffoldingTypeMapper'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Storage.IRelationalTypeMappingSource' while attempting to activate 'Microsoft.EntityFrameworkCore.Scaffolding.Internal.ScaffoldingTypeMapper'.

D:\shesh\EntityFrameworkCore\scaffold>

**Comment by deokershesh** [comment]
Never mind, it was issue at my end, which I have fixed. Now, I am getting different error which is related to database side, which I should be able to resolve differently. Closing....
