### ISSUE TITLE
Error when running ef migrations script in 5.0.0-rc.1.20451.13

### ISSUE THREAD

**Issue by kevbite** [dotnet/efcore#22541]
When running `ef migrations script` the following exception is thrown

```text
dotnet ef migrations script --output c:/temp/x.Data/SQLMigrations.sql --context XxxContext --idempotent --project x.Data --startup-project x.Api
Build started...
Build succeeded.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Internal.SemanticVersionComparer' from assembly 'Microsoft.EntityFrameworkCore, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor..ctor(IOperationReportHandler reportHandler, IDictionary args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Microsoft.EntityFrameworkCore.Tools.ReflectionOperationExecutor..ctor(String assembly, String startupAssembly, String projectDir, String dataDirectory, String rootNamespace, String language, String[] remainingArguments)
   at Microsoft.EntityFrameworkCore.Tools.Commands.ProjectCommandBase.CreateExecutor(String[] remainingArguments)
   at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsScriptCommand.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0(String[] args)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
```

Packages used in projects
```xml
<Project>
  <ItemGroup>
    <PackageReference Update="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.0-rc.1.20451.13" />
    <PackageReference Update="Microsoft.EntityFrameworkCore.Design" Version="5.0.0-rc.1.20451.13" />
    <PackageReference Update="Microsoft.EntityFrameworkCore.Tools" Version="5.0.0-rc.1.20451.13" />
    <PackageReference Update="Microsoft.EntityFrameworkCore.InMemory" Version="5.0.0-rc.1.20451.13" />
  </ItemGroup>
</Project>
```

dotnet-tools.json:
```json
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "dotnet-ef": {
      "version": "5.0.0-rc.1.20451.13",
      "commands": [
        "dotnet-ef"
      ]
    }
  }
}
```

### Further technical details

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:
```text
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20452.10
 Commit:    473d1b592e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\

Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935
```

**Comment by ajcvickers** [comment]
@kevbite I have not been able to reproduce this. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by kevbite** [comment]
Think I've figured it out... seems we needed to add a Package Reference for `Microsoft.EntityFrameworkCore.Design` to our startup project too.

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.10.8" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.0-rc.1.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\xxx.Data\xxx.Data.csproj" />
  </ItemGroup>
</Project>
```

**Comment by kevbite** [comment]
I'm going to close this issue as it seems to be working alright now 👍 Thanks

**Comment by ajcvickers** [comment]
@kevbite Did you still end up having to reference `Microsoft.EntityFrameworkCore.Design` from your startup project?

**Comment by kevbite** [comment]
Yep, throws that exception if I don't include it.

**Comment by ajcvickers** [comment]
@kevbite That reference shouldn't be needed. It would be great if you could post a project/solution that reproduces this so that we can investigate.

**Comment by kevbite** [comment]
[xxx.api.zip](https://github.com/dotnet/efcore/files/5297493/xxx.api.zip)

**Comment by ajcvickers** [comment]
@bricelam This repros for me when the design package is added as:

```
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
```

Which is the default when using VS to add the package. If I add it as a regular package it works. Is this expected?

**Comment by bricelam** [comment]
> Your startup project 'xxx.Api' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again.

This is the correct error. Do we have a repro for the `TargetInvocationException`?

> Is this expected?

Yes, making the `runtime` assets private prevents it from flowing into the startup project. This is why we recommend installing Design directly into your startup project. You can also make it work by removing the `<PrivateAssets>` element.

Unfortunately, NuGet doesn't give us a way (from the package) to exclude the compile assets but still keep the runtime assets non-private. `developmentDependency` is too coarse-grained.

**Comment by ajcvickers** [comment]
@bricelam So since most people will probably add the package like this, I think it means we should document that it is expected that you get this error unless you reference the package from your startup. (In other words, when I asked the question in triage whether this was expected, I think the answer should have been "yes".)

**Comment by bricelam** [comment]
The `TargetInvocationException` wasn't expected--it should give a friendly error message telling you to install it into the startup project (as the repro does)

**Comment by ajcvickers** [comment]
Ah, okay. That makes sense.

**Comment by Oluwatobilobaoke** [comment]
Hello, I'm having this exact same issues

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Internal.SemanticVersionComparer' from assembly 'Microsoft.EntityFrameworkCore, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor..ctor(IOperationReportHandler reportHandler, IDictionary args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Microsoft.EntityFrameworkCore.Tools.ReflectionOperationExecutor..ctor(String assembly, String startupAssembly, String projectDir, String dataDirectory, String rootNamespace, String language)
   at Microsoft.EntityFrameworkCore.Tools.Commands.ProjectCommandBase.CreateExecutor()
   at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsAddCommand.Execute()
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Exception has been thrown by the target of an invocation.

**Comment by Oluwatobilobaoke** [comment]
fixed i had to install recent core.design and sqlserver

**Comment by berabulut** [comment]
I removed all packages and reinstalled them and build the project. It fixed my issue.

**Comment by ozkan15** [comment]
I have also encountered this same issue and It turned out that my Startup project was not referencing  EF core Version 5.0.0, I installed and  It worked.

**Comment by JoeWarwick** [comment]
I was getting this similarly. 
I had to just clean the solution, rebuild and then the right error message appeared:
'Install the latest EF tools' 
So 
dotnet tool update --global dotnet-ef --version 5.0.3

and it updated them from 5.0.2 to 5.0.3 which fixed that confusing error.
