### ISSUE TITLE
NET 5.0 RC1 Table-per-type (TPT): ArgumentNullException: "Value cannot be null. (Parameter 'second')" when using an Owned Entity Type in the sub class

### ISSUE THREAD

**Issue by tivtag** [dotnet/efcore#22576]
Trying out the new Table-per-type (TPT) mapping feature, I get the following ArgumentNullException: "Value cannot be null. (Parameter 'second')" in DbContextServices.CreateModel when:

- I create a type hierachy Animal > Pet > Cat/Dog
- Pet references Cat (see property CatFriend)
- Cat has an owned enitity type (see type OwnedTestType, property OwnedTest)

When I remove the OwnedTestType the ArgumentNullException does not get thrown anymore.

The exception occurs in 5.0.0-rc.1.20451.13 and 6.0.0-alpha.1.20465.1.
All works (including the OwnedTestType) fine with 5.0.0-preview.8.20407.4!

### Exception:

```
System.ArgumentNullException: Value cannot be null. (Parameter 'second')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.SequenceEqual[TSource](IEnumerable`1 first, IEnumerable`1 second, IEqualityComparer`1 comparer)
   at Microsoft.EntityFrameworkCore.RelationalForeignKeyExtensions.GetDefaultName(IForeignKey foreignKey, StoreObjectIdentifier& storeObject, StoreObjectIdentifier& principalStoreObject)
   at Microsoft.EntityFrameworkCore.RelationalForeignKeyExtensions.GetConstraintName(IForeignKey foreignKey, StoreObjectIdentifier& storeObject, StoreObjectIdentifier& principalStoreObject)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedForeignKeysCompatibility(IReadOnlyList`1 mappedTypes, StoreObjectIdentifier& storeObject, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedTableCompatibility(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.SqlServer.Internal.SqlServerModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.ValidatingConvention.ProcessModelFinalized(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelFinalized(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelFinalized(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FinalizeModel()
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_Dependencies()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
   at EfcBug.Program.Main(String[] _) in C:\Users\paule\Downloads\EFC_Bug\EFC_Bug\Program.cs:line 80
```

### Steps to reproduce:

``` C#

namespace EfcBug
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using Microsoft.EntityFrameworkCore;

    [Table( "Animals" )]
    public class Animal
    {
        [Key]
        [DatabaseGenerated( DatabaseGeneratedOption.Identity )]
        public int Id { get; set; }
        public string Species { get; set; }
    }

    [Table( "Pets" )]
    public class Pet : Animal
    {
        public string Name { get; set; }

        [Column( "CatFriend_Id" )]
        [ForeignKey( nameof( CatFriend ) )]
        public int? CatFriendId { get; set; }
        public Cat CatFriend { get; set; }
    }

    [Table( "Cats" )]
    public sealed class Cat : Pet
    {
        public string EdcuationLevel { get; set; }

        [Required]
        public OwnedTestType OwnedTest { get; set; }
    }

    [Table( "Dogs" )]
    public sealed class Dog : Pet
    {
        public string FavoriteToy { get; set; }
    }

    [Owned]
    public sealed class OwnedTestType
    {
        [Required]
        public uint SomeField { get; set; }
    }

    public class EfBugDbContext : DbContext
    {  
        protected override void OnConfiguring( DbContextOptionsBuilder options )
        {
            options
                .UseSqlServer(
                    "Data Source=localhost;Initial Catalog=TestDB_EfBug_TPT_OwnedType;Persist Security Info=True;User ID=User;Password=Pass",
                    providerOptions => providerOptions.EnableRetryOnFailure() )
                .EnableDetailedErrors()
                .EnableSensitiveDataLogging();
        }

        protected override void OnModelCreating( ModelBuilder modelBuilder )
        {
            modelBuilder.Entity<Animal>().ToTable( "Animals" );
            modelBuilder.Entity<Pet>().ToTable( "Pets" ).HasOne( x => x.CatFriend );
            modelBuilder.Entity<Cat>().ToTable( "Cats" );
            modelBuilder.Entity<Dog>().ToTable( "Dogs" );
        }
    }

    public class Program
    {
        static void Main( string[] _ )
        {
            try
            {
                using( EfBugDbContext db = new EfBugDbContext() )
                {
                    db.Database.EnsureCreated();
                }

                using( EfBugDbContext db = new EfBugDbContext() )
                {
                    var catA = new Cat() { Name = "Meow A", EdcuationLevel = "2a", OwnedTest = new OwnedTestType() { SomeField = 5 } };
                    var catB = new Cat() { Name = "Meow B", EdcuationLevel = "2b", OwnedTest = new OwnedTestType() { SomeField = 10 }, CatFriend = catA };

                    db.Add( catA );
                    db.Add( catB );

                    db.SaveChanges();
                }

                Console.WriteLine( "OK" );
            }
            catch( Exception ex )
            {
                Console.WriteLine( ex.ToString() );
            }

            Console.ReadLine();
        }
    }
}
```

``` XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <Configurations>Debug;Release;TestRelease;ReleaseKundeProd;ReleaseKundeTest</Configurations>
  </PropertyGroup>
  
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>EfcBug</RootNamespace>
    <AssemblyName>EfcBug</AssemblyName>
  </PropertyGroup>

  <PropertyGroup>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Prefer32Bit>false</Prefer32Bit>
    <StartupObject>EfcBug.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.0-alpha.1.20465.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.0-alpha.1.20465.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="6.0.0-alpha.1.20465.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.0-alpha.1.20465.1" />
  </ItemGroup>

  <!--<ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.0-rc.1.20451.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.0-rc.1.20451.13">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="5.0.0-rc.1.20451.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.0-rc.1.20451.13" />
  </ItemGroup>-->

  <!--<ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.0-preview.8.20407.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.0-preview.8.20407.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="5.0.0-preview.8.20407.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.0-preview.8.20407.4" />    
  </ItemGroup>-->

</Project>
```

### Further technical details

EF Core version:  5.0.0-rc.1.20451.13 (doesn't work), 6.0.0-alpha.1.20465.1  (doesn't work), 5.0.0-preview.8.20407.4 (works fine!)
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1.8
Operating system: Windows 10 2004
SQL Server 15.0.4063.15
IDE: Visual Studio 2019 16.7.3

**Comment by smitpatel** [comment]
At the very least, GetColumnNames can return null and code does not check for nulls. There can be more bugs.
