### ISSUE TITLE
Tests now fail - what am I missing?

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#2259]
Have just updated my provider to latest daily build (13266 packages) - was on 13022.

Now tests fail, because the wrong table name is chosen. They passed with the previious daily and yhey also pass with the current SQLIte provider, so I must be doing something wrong, but what?

System.Data.SqlServerCe.SqlCeException : The specified table does not exist. [ Customer 
(The table name is actually Customers)

I also see these errors which I assume are related:
Result Message: Microsoft.Data.Entity.Metadata.ModelItemNotFoundException : The entity type 'Microsoft.Data.Entity.FunctionalTests.TestModels.Northwind.OrderDetail' requires a key to be defined.

Code changes here: https://github.com/ErikEJ/EntityFramework.SqlServerCompact/compare/issue-47?expand=1 

Test Name:  ErikEJ.Data.Entity.SqlServerCe.FunctionalTests.AsNoTrackingSqlServerCeTest.Applied_to_body_clause
Test FullName:  ErikEJ.Data.Entity.SqlServerCe.FunctionalTests.AsNoTrackingSqlServerCeTest.Applied_to_body_clause
Test Source:     : line 0
Test Outcome:   Failed
Test Duration:  0:00:03.291

Result StackTrace:  
at System.Data.SqlServerCe.SqlCeCommand.ProcessResults(Int32 hr)
   at System.Data.SqlServerCe.SqlCeCommand.CompileQueryPlan()
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommand(CommandBehavior behavior, String method, ResultSetOptions options)
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.Data.Entity.Relational.Query.QueryingEnumerable.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__1`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.Data.Entity.Query.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.FunctionalTests.AsNoTrackingTestBase`1.Applied_to_body_clause()
Result Message: System.Data.SqlServerCe.SqlCeException : The specified table does not exist. [ Customer ]

**Comment by ErikEJ** [comment]
Some debugging: The test model is not properly created, and therefore the table name annotation is never added

I can see that this call just returns when debugging, and :

     public static Func<IServiceProvider, IModelSource> GetFactory(Action<ModelBuilder> onModelCreating) =>
            p => new TestSqlServerCeModelSource(
                onModelCreating,
                p.GetRequiredService<IDbSetFinder>(),

And the constructor:

        public TestSqlServerCeModelSource
                p.GetRequiredService<IModelValidator>());

Causing the model Building to fail.

**Comment by ErikEJ** [comment]
Doh - nailed it:

    public static Func<IServiceProvider, **SqlServerCeModelSource**>

Small but important change not caught in the hailstorm of code changes
