### ISSUE TITLE
"Format of the initialization string does not conform to specification starting at index 0." error while removing migration for .NET 5.0-preview7 project with dotnet ef 5.0-rc1

### ISSUE THREAD

**Issue by bairog** [dotnet/efcore#22595]
Hello.
I have simple class library project with a EF Core 5.0-rc1 DbContext that targets .NET 5.0-preview7 and is build in **AnyCPU** configuration. I'm using **.NET 5-preview7** because according to [info on download page](https://dotnet.microsoft.com/download/dotnet/5.0) it is the latest one that supports Visual Studio 2019 v**16.7 Release**. I use only stable IDE builds in my project and cannot use preview IDE versions.
I've installed latest Entity Framework Core .NET Command-line Tools 5.0.0-rc.1.20451.13
When I'm trying to add migration via **dotnet ef migrations add InitialCreate** command - it is working correctly.
But when I'm trying to remove migration via **dotnet ef migrations remove --verbose** command I get an error:
```
Format of the initialization string does not conform to specification starting at index 0.
```
Can be ralated to https://github.com/dotnet/efcore/issues/22594

### Steps to reproduce

1. Download test project - https://yadi.sk/d/T6MXHQEFScnKbQ
2. Install latest Entity Framework Core .NET Command-line Tools 5.0.0-rc.1.20451.13
3. Run **dotnet ef migrations add InitialCreate** command in test project folder and after that run **dotnet ef migrations remove --verbose** command in test project folder .

### dotnet ef migrations remove --verbose output:

```
D:\Test\Test>dotnet ef migrations remove --verbose
Using project 'D:\Test\Test\Test.csproj'.
Using startup project 'D:\Test\Test\Test.csproj'.
Writing 'D:\Test\Test\obj\Test.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\Leo.TOPAZ1\AppData\Local\Temp\tmp4B6D.tmp /verbosity:quiet /nologo D:\Test\Test\Test.csproj
Writing 'D:\Test\Test\obj\Test.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\Leo.TOPAZ1\AppData\Local\Temp\tmp4D53.tmp /verbosity:quiet /nologo D:\Test\Test\Test.csproj
Build started...
dotnet build D:\Test\Test\Test.csproj /verbosity:quiet /nologo

Сборка успешно завершена.
    Предупреждений: 0
    Ошибок: 0

Прошло времени 00:00:00.85
Build succeeded.
dotnet exec --depsfile D:\Test\Test\bin\Debug\net5.0\Test.deps.json --additionalprobingpath C:\Users\Leo.TOPAZ1\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig D:\Test\Test\bin\Debug\net5.0\Test.runtimeconfig.json C:\Users\Leo.TOPAZ1\.dotnet\tools\.store\dotnet-ef\5.0.0-rc.1.20451.13\dotnet-ef\5.0.0-rc.1.20451.13\tools\netcoreapp3.1\any\tools\netcoreapp2.0\any\ef.dll migrations remove --assembly D:\Test\Test\bin\Debug\net5.0\Test.dll --startup-assembly D:\Test\Test\bin\Debug\net5.0\Test.dll --project-dir D:\Test\Test\ --language C# --working-dir D:\Test\Test --verbose --root-namespace Test
Using assembly 'Test'.
Using startup assembly 'Test'.
Using application base 'D:\Test\Test\bin\Debug\net5.0'.
Using working directory 'D:\Test\Test'.
Using root namespace 'Test'.
Using project directory 'D:\Test\Test\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'UserDBContext'.
Using context 'UserDBContext'.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.Sqlite'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.Sqlite'.
Finding design-time services referenced by assembly 'Test'.
No referenced design-time services were found.
Finding IDesignTimeServices implementations in assembly 'Test'...
No design-time services were found.
DetectChanges starting for 'UserDBContext'.
DetectChanges completed for 'UserDBContext'.
DetectChanges starting for 'UserDBContext'.
DetectChanges completed for 'UserDBContext'.
'UserDBContext' disposed.
System.ArgumentException: Format of the initialization string does not conform to specification starting at index 0.
   at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue)
   at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms, Boolean useOdbcRules)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.GetAppliedMigrations()
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.RemoveMigration(String projectDir, String rootNamespace, Boolean force, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.RemoveMigration(String contextType, Boolean force)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.RemoveMigrationImpl(String contextType, Boolean force)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.RemoveMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Format of the initialization string does not conform to specification starting at index 0.
```

### Further technical details

EF Core version: **5.0-rc1**
Database provider: **Microsoft.EntityFrameworkCore.Sqlite 5.0-rc1**
Target framework: **.NET 5.0-preview7**
Operating system: **Windows 10 2004 x64**
IDE: **Visual Studio 2019 16.7.3 Professional**

**Comment by ajcvickers** [comment]
See also #22593

**Comment by ajcvickers** [comment]
@bairog This is not a valid SQLite connection string:

```C#
optionsBuilder.UseSqlite(@"d:\test.db");
```

A typical connection string might be, "Data Source = d:\test.db".

**Comment by bairog** [comment]
> This is not a valid SQLite connection string:
> 
> ```cs
> optionsBuilder.UseSqlite(@"d:\test.db");
> ```
> 
> A typical connection string might be, "Data Source = d:\test.db".
Oh, my mistake. I've corrected connection string and the error has gone.
P.S. Strange that adding migrations performs successfully and only removing migration fails..
