### ISSUE TITLE
IBM.Data.DB2.Core.DB2DataReader.GetInt16(Int32 i)

### ISSUE THREAD

**Issue by Hokutosei** [dotnet/efcore#22623]
I maybe in the wrong repo, but I am using IBM Db2, and experiencing an error of a bool type attribute

```
$ curl -XGET https://localhost:5005/bills/get -s -k
System.InvalidCastException: Specified cast is not valid.
   at IBM.Data.DB2.Core.DB2DataWrapper.get_Int16Value()
   at IBM.Data.DB2.Core.DB2DataReader.GetInt16(Int32 i)
   at lambda_method13(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at HomeAudit2A.Controllers.BillsController.GetBills() in D:\Developer\react\HomeAudit2A\Controllers\BillsController.cs:line 38
   at lambda_method6(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Steps to reproduce

here is the class that I am using
```
    [Table("bills")]
    // [PrimaryKey("bill_id", "month_id")]
    public class Bills
    {
        [Key]
        [Column("bill_id")]
        [JsonPropertyName("bill_id")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int BillID { get; set; }

        [Column("salary_id")]
        [ForeignKey("salary_id")]
        [JsonPropertyName("salary_id")]
        [NotMapped]
        public int? SalaryID { get; set; }

        [Column("amount")]
        [JsonPropertyName("amount")]
        public int Amount { get; set; }

        [Column("name", TypeName = "nvarchar(1000)")]
        public string? Name { get; set; }

        [Column("as_template")]
        [JsonPropertyName("as_template")]
        public bool? UseAsTemplate { get; set; }

        [Column("paid")]
        public bool? Paid { get; set; }
```

and this is the controller that use this model

```
        public async Task<ActionResult<Bills>> GetBills()
        {
            using var transaction = await _context.Database.BeginTransactionAsync();
            var bills = await _context.Bills.FromSqlRaw($"SELECT * FROM bills ORDER BY created_at DESC").ToListAsync();
            await transaction.CommitAsync();

            return CreatedAtAction("getBills", bills);
        }
```

the onmodelCreating

```
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var bills = modelBuilder.Entity<Bills>();
            bills.Property(d => d.CreatedAt).HasDefaultValueSql("CURRENT_TIMESTAMP");
            bills.Property(d => d.UpdatedAt).HasDefaultValueSql("CURRENT_TIMESTAMP");
```

I already tried, but still same problem
```
            var boolToInt = new ValueConverter<bool, int>(x => x ? 1 : 0, x => x == 1);
            bills.Property(d => d.UseAsTemplate).HasConversion(boolToInt);
            bills.Property(d => d.Paid).HasConversion(boolToInt);
```

### Further technical details

EF Core version: 3.1.8
Database provider: IBM.EntityFrameworkCore" Version="3.1.0.300"
Target framework: 5.0.100-rc.1.20452.10
Operating system: MINGW64_NT-10.0-17763
IDE: VS Code 1.49.1

any help please? I wanted to try ibm db2 to my new project. I usually use sql server, or mariadb2. thank you

**Comment by ErikEJ** [comment]
You most likely need to contact IBM

**Comment by Hokutosei** [comment]
@ErikEJ right, I think so. thank you!

**Comment by ajcvickers** [comment]
@Hokutosei As Erik says. this looks like an issue with the IBM provider which will need to be reported to them.

**Comment by Hokutosei** [comment]
@ajcvickers yes, I am finding now where to ask for. I will update here back again for the progress! thank you!
