### ISSUE TITLE
Query: NRE when trying to project count of navigation typed as ICollection<T>

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#22701]
query:

```cs
ss.Set<Customer>()
    .OrderBy(c => c.CustomerID)
    .Select(c => ((ICollection<Order>)c.Orders).Count)
```

exception:

```
 Object reference not set to an instance of an object.
  Stack Trace: 
    SelectExpression.ApplyCollectionJoin(Int32 collectionIndex, Int32 collectionId, Expression innerShaper, INavigationBase navigation, Type elementType, Boolean splitQuery) line 1373
    CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression) line 74
    CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression) line 95
    RelationalQueryTranslationPostprocessor.Process(Expression query) line 43
    QueryCompilationContext.CreateQueryExecutor[TResult](Expression query) line 175
    Database.CompileQuery[TResult](Expression query, Boolean async) line 72
    QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async) line 112
    <>c__DisplayClass12_0`1.<ExecuteAsync>b__0() line 149
    CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) line 76
    QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken) line 145
    EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken) line 98
    EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken) line 109
    ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
```

**Comment by smitpatel** [comment]
Note: This should be handled in preprocessing visitor (probably in nav expansion) to remove redundant cast and convert Count to Queryable.Count().

**Comment by JonPSmith** [comment]
One of my previous clients has just updated to EF Core 5 and this bug has hit them.  They can get around it by using `Count()` rather than `Count`, but it is a (small) breaking change. I have confirmed this on the code I am using for my book.

The client's code uses DDD-styled entity classes, with collections held in a backing fields and a  `IReadOnlyCollection<TEntity>` property to read. 

I haven't built a complete example as you already have some simple code that fails, but here is a bare-bones example

### Entity class (bare-bones)

This is my code. The client uses `List<T>` for backing field and `IReadOnlyCollection<T>` for the read-only property.

```c#
public class Book : EventsAndCreatedUpdated, ISoftDelete
{
    //-----------------------------------------------
    //relationships backing fields

    private HashSet<Review> _reviews;
    private HashSet<BookAuthor> _authorsLink;
    private HashSet<Tag> _tags;

    //scalar properties

    public int BookId { get; private set; }
   //... rest of code left out

    //---------------------------------------
    //relationships

    public IReadOnlyCollection<Review> Reviews => _reviews?.ToList();
    public IReadOnlyCollection<BookAuthor> AuthorsLink => _authorsLink?.ToList();
    public IReadOnlyCollection<Tag> Tags => _tags?.ToList();

   //... rest of code left out
}
```

### My test

I wrote this to check that `Count()` fixed the problem in my setup (I don't currently have access the client's code)

```c#
[Theory]
[InlineData(false)]
[InlineData(true)]
public void TestCountOfCollectionWithTypeChanged(bool countNoBrackets)
{
    //SETUP
    var options = SqliteInMemory.CreateOptions<BookDbContext>();
    using (var context = new BookDbContext(options))
    {
        context.Database.EnsureCreated();
        var bookId = context.SeedDatabaseFourBooks().Last().BookId;

        context.ChangeTracker.Clear();

        var query1 = context.Books
            .Where(b => b.BookId == bookId);
        var query2 = countNoBrackets
            ? query1.Select(b => b.Reviews.Count)
            : query1.Select(b => b.Reviews.Count());

        //ATTEMPT
        int reviewCount;
        try
        {
            reviewCount = query2.Single();
        }
        catch
        {
            countNoBrackets.ShouldBeTrue();
            return;
        }

        //VERIFY
        countNoBrackets.ShouldBeFalse();
        _output.WriteLine(query2.ToQueryString());
        reviewCount.ShouldEqual(2);
    }
}
```

The stacktrace is similar to the one shown (that's how my client found this issue)
```text
System.NullReferenceException
Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ApplyCollectionJoin(Int32 collectionIndex, Int32 collectionId, Expression innerShaper, INavigationBase navigation, Type elementType, Boolean splitQuery)
   at Microsoft.EntityFrameworkCore.Query.Internal.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMember(MemberExpression node)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitConditional(ConditionalExpression node)
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPostprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Sqlite.Query.Internal.SqliteQueryTranslationPostprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Single[TSource](IQueryable`1 source)
   at Test.UnitTests.TestPersistenceSqlBooks.TestBookDbContext.TestCountOfCollectionWithTypeChanged(Boolean countNoBrackets) in C:\Users\JonPSmith\source\repos\EfCoreinAction-SecondEdition\Test\UnitTests\TestPersistenceSqlBooks\TestBookDbContext.cs:line 111
```

My test, and my client tests, are using EF Core 5.0.1

**Comment by V0ldek** [comment]
Just hit the exact same issue.

> The client's code uses DDD-styled entity classes, with collections held in a backing fields and a IReadOnlyCollection<TEntity> property to read.

My codebase is the same.

Can confirm that the `Count()` workaround works, however the number of analyser warnings I had to suppress to write that made me sick. This is also a very hard bug to locate since you don't exactly expect a framework to throw an NRE.

**Comment by JonPSmith** [comment]
Could this be fixed in EF Core 6? This is a regression from EF Core 3.1 and keeps causing problems for people updating from the last LTS version.

**Comment by smitpatel** [comment]
Could be fixed in #25577
