### ISSUE TITLE
LINQ query works in 3.1 and fails in 5.0 rc1: ArgumentException: Argument types do not match

### ISSUE THREAD

**Issue by kevinkoenig** [dotnet/efcore#22758]
I have the following query that works in 3.1 and fails in 5.0 rc1. I have simplified the query to only project the item that causes the error. In 5.0 rc1 it throws the error ArgumentException: Argument types do not match. I cannot understand what the issue is.

```
var roles = await (
    from o in ProjectRoles
    join p in QuoteRoles.Include(m => m.RoleQuantities).Where(m => m.QuoteId == quoteId) on
        o.Id equals p.ProjectRoleId 
    into q
    from r in q.DefaultIfEmpty()
    select new 
    {
        kkk = r != null ? o.Id : r.Id,
    }).AsNoTracking().ToListAsync().ConfigureAwait(false);

```

The following is the call stack.  I removed the ASP.NET stuff from the bottom of the stack.

System.ArgumentException: Argument types do not match
   at System.Linq.Expressions.Expression.Condition(Expression test, Expression ifTrue, Expression ifFalse, Type type)
   at System.Linq.Expressions.ConditionalExpression.Update(Expression test, Expression ifTrue, Expression ifFalse)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitConditional(ConditionalExpression conditionalExpression)
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberAssignment(MemberAssignment memberAssignment)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at AurigoQuote2Cash.Utility.RolesAndPhasesHelper.GetRolesAndPhases(IAurigoPricingCalculatorContext db, Int32 quoteId) in

**Comment by smitpatel** [comment]
Work-around
```
var roles = await (
    from o in ProjectRoles
    join p in QuoteRoles.Include(m => m.RoleQuantities).Where(m => m.QuoteId == quoteId) on
        o.Id equals p.ProjectRoleId 
    into q
    from r in q.DefaultIfEmpty()
    select new 
    {
        kkk = r.ProjectRoleId != null ? o.Id : r.Id,
    }).AsNoTracking().ToListAsync().ConfigureAwait(false);
```

**Comment by kevinkoenig** [comment]
I tried that and now I get an error InvalidOperationException: Nullable object must have a value.  ProjectRoleId is not nullable so I assume this won't work.

BTW I am now using LINQPad to test

**Comment by smitpatel** [comment]
Try casting `r.ProjectRoleId` to nullable type before comparing to null.

**Comment by kevinkoenig** [comment]
Tried as below with same stack
 ```
   from o in ProjectRoles
    join p in QuoteRoles.Include(m => m.RoleQuantities).Where(m => m.QuoteId == quoteId) on
        o.Id equals p.ProjectRoleId 
	into q
    from r in q.DefaultIfEmpty()
    select new 
    {
		kkk = ((Nullable<int>)r.ProjectRoleId) != null ? o.Id : r.Id,
	}).AsNoTracking().ToListAsync().ConfigureAwait(false);

```

**Comment by smitpatel** [comment]
If `r.ProjectRoleId` is null (when condition is false), r is null so accessing `r.Id` will give you back null result. Query is destined to fail at runtime.

**Comment by smitpatel** [comment]
Another work-around:
```C#
var roles = await (
    from o in ProjectRoles
    join p in QuoteRoles.Where(m => m.QuoteId == quoteId) on
        o.Id equals p.ProjectRoleId 
    into q
    from r in q.DefaultIfEmpty()
    select new 
    {
        kkk = r != null ? o.Id : r.Id,
    }).AsNoTracking().ToListAsync().ConfigureAwait(false);
```
Included is not needed because final result does not project any entity.

**Comment by kevinkoenig** [comment]
Sorry for the confusion, when i simplified the query to the one item that fails, I inadvertently reversed the results.  The original query is

```
var rolesOriginal = await(
	from o in ProjectRoles
	join p in QuoteRoles.Include(m => m.RoleQuantities).Where(m => m.QuoteId == quoteId) on
		o.Id equals p.ProjectRoleId into q
	from r in q.DefaultIfEmpty()
	select new 
	{
	InUse = r != null,
	Id = o.Id,
	Name = o.Name,
	UnitPrice = r != null ? r.UnitPrice : o.UnitPrice,
	MonthQuantities =
			from s in r.RoleQuantities
	orderby s.Ordinal
	select new 
	{
		Ordinal = s.Ordinal,
		Quantity = s.Quantity
	}
}).AsNoTracking().ToListAsync().ConfigureAwait(false);

```
and it still fails.  If I remove the Include as you suggested it works but obviously MonthQuantites does not get initialized with any values.

**Comment by smitpatel** [comment]
Include is not required for `MonthQuantities` to be populated. Please share a full runnable code which demonstrate the issue.

**Comment by kevinkoenig** [comment]
you are correct.  I do not need to have the Include() and it works when there is data in RoleQuantities.  thank you for your help.  Can you explain why the Include() statement causes it to fail.  That will help me understand. 

Thanks for all of your help

**Comment by smitpatel** [comment]
For `r != null ? r.UnitPrice : o.UnitPrice` fragment `r` contains special include node since in `r != null` whole entity is being selected. This makes `r != null` to be client evaluated where true and false result of conditions have different types.

Yet another work-around.
```
var roles = await (
    from o in ProjectRoles
    join p in QuoteRoles.Include(m => m.RoleQuantities).Where(m => m.QuoteId == quoteId) on
        o.Id equals p.ProjectRoleId 
    into q
    from r in q.DefaultIfEmpty()
    select new 
    {
        kkk = r != null ? (type)o.Id : (type)r.Id, //use the same type in casting
    }).AsNoTracking().ToListAsync().ConfigureAwait(false);
```

**Comment by kevinkoenig** [comment]
Thank you, that helps me alot!

**Comment by smitpatel** [comment]
Could be fixed in https://github.com/dotnet/efcore/issues/23309
