### ISSUE TITLE
PropertyEntryXxx Test failing  

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#2283]
https://github.com/ErikEJ/EntityFramework.SqlServerCompact/tree/property-entry-fail

Using daily build 33301 - initially fails with 

Microsoft.Data.Entity.Update.DbUpdateException : An error occurred while updating the entries. See the inner exception for details.
---- System.Data.SqlServerCe.SqlCeException : The column cannot contain null values. [ Column name = Id,Table name = EngineSuppliers ]

Looking at the seed code, I can see that it expects "generated keys" - so changing fixture to:

```
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ForSqlCe().UseIdentity();
    }
```

(There is no "sequence" in the database engine in use). Now I get this error, and have no idea what the issue is - can anyone help?

Result Message: System.InvalidOperationException : **The key {'TempId'} on entity type 'Microsoft.Data.Entity.FunctionalTests.TestModels.ConcurrencyModel.Location' contains properties in shadow state - {'TempId'} and it is referenced by the foreign key {'StorageLocationTempId'} from entity type 'Microsoft.Data.Entity.FunctionalTests.TestModels.ConcurrencyModel.Engine'."**

Result StackTrace:  
at Microsoft.Data.Entity.FunctionalTests.TestModelSource.ThrowingModelValidator.ShowWarning(String message)
   at Microsoft.Data.Entity.Internal.ModelValidator.EnsureNoShadowKeys(IModel model)
   at Microsoft.Data.Entity.Internal.ModelValidator.Validate(IModel model)
   at Microsoft.Data.Entity.FunctionalTests.TestModelSource.CreateModel(DbContext context, IModelBuilderFactory modelBuilderFactory)
   at Microsoft.Data.Entity.Internal.ModelSource.<>c__DisplayClass8_0.<GetModel>b__0(Type k)
   at Microsoft.Data.Entity.Utilities.ThreadSafeDictionaryCache`2.GetOrAdd(TKey key, Func`2 factory)
   at Microsoft.Data.Entity.Internal.ModelSource.GetModel(DbContext context, IModelBuilderFactory modelBuilderFactory)
   at ErikEJ.Data.Entity.SqlServerCe.FunctionalTests.TestSqlCeModelSource.GetModel(DbContext context, IModelBuilderFactory modelBuilderFactory) in C:\Code\EntityFramework.SqlServerCompact\test\EntityFramework.SqlServerCompact.FunctionalTests\TestSqlCeModelSource.cs:line 28
   at Microsoft.Data.Entity.Internal.DbContextServices.CreateModel()
   at Microsoft.Data.Entity.Utilities.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.Internal.DbContextServices.get_Model()
   at Microsoft.Framework.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_5(IServiceProvider p)
   at Microsoft.Framework.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceLookup.Service.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceLookup.Service.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.<>c__DisplayClass8_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Data.Entity.Storage.DataStoreServices.GetService[TService]()
   at Microsoft.Data.Entity.Relational.RelationalDataStoreServices.get_DatabaseFactory()
   at Microsoft.Framework.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_11(IServiceProvider p)
   at Microsoft.Framework.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.<>c__DisplayClass8_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Data.Entity.DbContext.<Initialize>b__12_2()
   at Microsoft.Data.Entity.Utilities.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.DbContext.get_Database()
   at ErikEJ.Data.Entity.SqlServerCe.FunctionalTests.F1SqlCeFixture.<CreateTestStore>b__4_0() in C:\Code\EntityFramework.SqlServerCompact\test\EntityFramework.SqlServerCompact.FunctionalTests\F1SqlCeFixture.cs:line 40
   at Microsoft.Data.Entity.FunctionalTests.TestStore.CreateShared(String name, Action initializeDatabase)
   at ErikEJ.Data.Entity.SqlServerCe.FunctionalTests.SqlCeTestStore.CreateShared(Action initializeDatabase) in C:\Code\EntityFramework.SqlServerCompact\test\EntityFramework.SqlServerCompact.FunctionalTests\SqlCeTestStore.cs:line 34
   at ErikEJ.Data.Entity.SqlServerCe.FunctionalTests.SqlCeTestStore.GetOrCreateShared(String name, Action initializeDatabase) in C:\Code\EntityFramework.SqlServerCompact\test\EntityFramework.SqlServerCompact.FunctionalTests\SqlCeTestStore.cs:line 17
   at ErikEJ.Data.Entity.SqlServerCe.FunctionalTests.F1SqlCeFixture.CreateTestStore() in C:\Code\EntityFramework.SqlServerCompact\test\EntityFramework.SqlServerCompact.FunctionalTests\F1SqlCeFixture.cs:line 32
   at Microsoft.Data.Entity.Relational.FunctionalTests.PropertyEntryTestBase`2..ctor(TFixture fixture)
   at ErikEJ.Data.Entity.SqlServerCe.FunctionalTests.PropertyEntrySqlCeTest..ctor(F1SqlCeFixture fixture) in C:\Code\EntityFramework.SqlServerCompact\test\EntityFramework.SqlServerCompact.FunctionalTests\PropertyEntrySqlCeTest.cs:line 9

**Comment by ErikEJ** [comment]
:blush:  Was missing:
      base.OnModelCreating(modelBuilder);

**Comment by ErikEJ** [comment]
OK, got a bit further:
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {            
            base.OnModelCreating(modelBuilder);
            modelBuilder.ForSqlCe().UseIdentity();
            modelBuilder.Entity<Team>(b =>
            {
                b.Property(t => t.Id).ForSqlCe().UseNoValueGeneration();                    
            });
        }

Now getting error:

Result Message:	**System.InvalidOperationException : The property 'Id' on entity type 'Team' does not have value generation on add enabled and it is principal by at least one foreign key. Properties referenced by foreign keys should have value generation on add enabled.**

Result StackTrace:	
at Microsoft.Data.Entity.Internal.ModelValidator.ShowError(String message)
   at Microsoft.Data.Entity.Internal.ModelValidator.VerifyRootPrincipal(IProperty principalProperty, Dictionary`2 verifiedProperties, ImmutableList`1 visitedForeignKeys, String& errorMessage)
   at Microsoft.Data.Entity.Internal.ModelValidator.VerifyRootPrincipal(IProperty principalProperty, Dictionary`2 verifiedProperties, ImmutableList`1 visitedForeignKeys, String& errorMessage)
   at Microsoft.Data.Entity.Internal.ModelValidator.EnsureValidForeignKeyChains(IModel model)
   at Microsoft.Data.Entity.Internal.ModelValidator.Validate(IModel model)
   at Microsoft.Data.Entity.FunctionalTests.TestModelSource.CreateModel(DbContext context, IModelBuilderFactory modelBuilderFactory)
   at Microsoft.Data.Entity.Internal.ModelSource.<>c__DisplayClass8_0.<GetModel>b__0(Type k)
   at Microsoft.Data.Entity.Utilities.ThreadSafeDictionaryCache`2.GetOrAdd(TKey key, Func`2 factory)
   at Microsoft.Data.Entity.Internal.ModelSource.GetModel(DbContext context, IModelBuilderFactory modelBuilderFactory)
   at ErikEJ.Data.Entity.SqlServerCe.FunctionalTests.TestSqlCeModelSource.GetModel(DbContext context, IModelBuilderFactory modelBuilderFactory) in C:\Code\EntityFramework.SqlServerCompact\test\EntityFramework.SqlServerCompact.FunctionalTests\TestSqlCeModelSource.cs:line 28
   at Microsoft.Data.Entity.Internal.DbContextServices.CreateModel()
   at Microsoft.Data.Entity.Utilities.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.Internal.DbContextServices.get_Model()
   at Microsoft.Framework.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_5(IServiceProvider p)
   at Microsoft.Framework.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceLookup.Service.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceLookup.Service.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.<>c__DisplayClass8_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Data.Entity.Storage.DataStoreServices.GetService[TService]()
   at Microsoft.Data.Entity.Relational.RelationalDataStoreServices.get_DatabaseFactory()
   at Microsoft.Framework.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_11(IServiceProvider p)
   at Microsoft.Framework.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.<>c__DisplayClass8_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Data.Entity.DbContext.<Initialize>b__12_2()
   at Microsoft.Data.Entity.Utilities.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.DbContext.get_Database()
   at ErikEJ.Data.Entity.SqlServerCe.FunctionalTests.F1SqlCeFixture.<CreateTestStore>b__4_0() in C:\Code\EntityFramework.SqlServerCompact\test\EntityFramework.SqlServerCompact.FunctionalTests\F1SqlCeFixture.cs:line 40
   at Microsoft.Data.Entity.FunctionalTests.TestStore.CreateShared(String name, Action initializeDatabase)
   at ErikEJ.Data.Entity.SqlServerCe.FunctionalTests.SqlCeTestStore.CreateShared(Action initializeDatabase) in C:\Code\EntityFramework.SqlServerCompact\test\EntityFramework.SqlServerCompact.FunctionalTests\SqlCeTestStore.cs:line 34
   at ErikEJ.Data.Entity.SqlServerCe.FunctionalTests.SqlCeTestStore.GetOrCreateShared(String name, Action initializeDatabase) in C:\Code\EntityFramework.SqlServerCompact\test\EntityFramework.SqlServerCompact.FunctionalTests\SqlCeTestStore.cs:line 17
   at ErikEJ.Data.Entity.SqlServerCe.FunctionalTests.F1SqlCeFixture.CreateTestStore() in C:\Code\EntityFramework.SqlServerCompact\test\EntityFramework.SqlServerCompact.FunctionalTests\F1SqlCeFixture.cs:line 32
   at Microsoft.Data.Entity.Relational.FunctionalTests.PropertyEntryTestBase`2..ctor(TFixture fixture)
   at ErikEJ.Data.Entity.SqlServerCe.FunctionalTests.PropertyEntrySqlCeTest..ctor(F1SqlCeFixture fixture) in C:\Code\EntityFramework.SqlServerCompact\test\EntityFramework.SqlServerCompact.FunctionalTests\PropertyEntrySqlCeTest.cs:line 9

**Comment by ErikEJ** [comment]
Fixed by adding:
             modelBuilder.Entity<Team>(b => 
             { 
                 b.Property(t => t.Id) 
                     .StoreGeneratedPattern(Microsoft.Data.Entity.Metadata.StoreGeneratedPattern.None); 
                 b.Property(t => t.Id) 
                     .GenerateValueOnAdd(true);                   
             });
