### ISSUE TITLE
No translation for IEnumerable<int>.AsQueryable() as source for Contains query

### ISSUE THREAD

**Issue by joakimriedel** [dotnet/efcore#22881]
## Background ##

I would like to be able to write a query that sometimes uses a list of IDs directly queried from the database, and sometimes uses a hard coded list of IDs, based on a condition. The hard coded list is cast to `IQueryable<int>` using `AsQueryable()` to be able to send it as a parameter to a method which accepts an `IQueryable<int>`

Something like this trivial example, but in real life obviously the queries are more complex.

```C#
    bool condition = true;
    IQueryable<int> offerIds = condition ? new[] {1}.AsQueryable() : context.Offers.Select(o => o.Id);
    var offers = await context.Offers.Where(o => offerIds.Contains(o.Id)).ToListAsync();
```

This query executes successfully if condition is `false`, but not if condition is `true`.

## Workaround ##

This workaround allows both conditions. It tests if `offerIds` is `IEnumerable<int>` and then use `AsEnumerable()` to convert it back.

```C#
    var offers = await context.Offers
        .Where(o => (offerIds is IEnumerable<int> ? offerIds.AsEnumerable() : offerIds).Contains(o.Id))
        .ToListAsync();
```

### SQL output for condition = true ###

`WHERE [o].[Id] = 1`

### SQL output for condition = false ###

```
WHERE [o].[Id] IN (
          SELECT [o0].[Id]
          FROM [Offers] AS [o0]
      )
```

I was actually surprised it would parse the expression but it works like a charm for both condition values! 👍

## Bug/feature request/question ##

Is this a bug or feature request? Not sure, but I _would be happy to be able to do this without the workaround_ since it's easy to forget when building queries potentially causing the application to crash during runtime based on the actual underlying type of the `IQueryable<int>`. It does not seem to be a regression in 5.0 rc1, have tested this code (without workaround) as far back as 2.1.

If this already supported somehow but I am missing something obvious here - then please accept this as a question.

## Stack trace ##

```
An exception of type 'System.InvalidOperationException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'The LINQ expression 'EnumerableQuery<int> { 1, }
    .Contains(NavigationTreeExpression
        Value: EntityReference: Offer
        Expression: o.Id)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.'
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ExpandNavigationsForSource(NavigationExpansionExpression source, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ProcessLambdaExpression(NavigationExpansionExpression source, LambdaExpression lambdaExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ProcessWhere(NavigationExpansionExpression source, LambdaExpression predicate)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__65`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EfCoreBug.Program.<Main>d__1.MoveNext()
```

EF Core version: 5.0 rc1 
Database provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by Seabizkit** [comment]
this was working and its not now, Ef core 5, I am sure this was working in a version of 3.1,
```
if (!string.IsNullOrWhiteSpace(searchString))
  {
      // break down the search terms in to individual keywords
      string[] searchTerms = searchString.Split(' ');
      //q.All(val => i.OriginalFilename.ToLower().Contains(val.ToLower()

      files = files.Where(x => searchTerms.All(y => x.OriginalFilename.Contains(y))); //failing on this
  }
```

**Comment by smitpatel** [comment]
@Seabizkit - It was not working in EF Core 3.1 either if searchstring is non-empty. See #19070. Your query is not related to this issue.

**Comment by joakimriedel** [comment]
@ajcvickers friendly bump - would this be considered a candidate to move from backlog anytime soon?

**Comment by ajcvickers** [comment]
@joakimriedel This issue has no votes. I don't see us working on this any time soon.

**Comment by joakimriedel** [comment]
Ok thanks I'll see if I can do something about it myself.
