### ISSUE TITLE
SQLite: "misuse of aggregate: COUNT()"

### ISSUE THREAD

**Issue by stevendarby** [dotnet/efcore#22911]
Using a Where clause on a count can sometimes produce the error `misuse of aggregate: COUNT()`
I have not checked other providers like SQL Server yet

### Code

This is a much simplified version to reproduce the issue

```C#
public class Program
{
    public static async Task Main(string[] args)
    {
        await using var connection = new SqliteConnection("Data Source=:memory:");
        connection.Open();

        var loggerFactory = new LoggerFactory();
        loggerFactory.AddProvider(new DebugLoggerProvider());

        var options = new DbContextOptionsBuilder()
            .UseSqlite(connection)
            .UseLoggerFactory(loggerFactory)
            .Options;

        await using var context = new MyDbContext(options);
        await context.Database.EnsureCreatedAsync();

        // First example which works
        var unionQuery = context.MyEntities
            .Select(x => new {x.Id, Name = "MyEntities"})
            .Union(
                context.MyEntities2
                    .Select(x => new {x.Id, Name = "MyEntities2"}));

        _ = await unionQuery
            .GroupBy(x => x.Name)
            .Select(x => new {Name = x.Key, Count = x.Count()})
            .Where(x => x.Count > 0)
            .ToListAsync();


        // Second example which breaks. Suppose I'm building the unionQuery dynamically and there happens to be
        // only one set to include. No actual union occurs but the shape of the query selector is still the same
        unionQuery = context.MyEntities
            .Select(x => new {x.Id, Name = "MyEntities"});

        // So should be able to repeat the below the same as the first example, but this is when I get the error
        _ = await unionQuery
            .GroupBy(x => x.Name)
            .Select(x => new {Name = x.Key, Count = x.Count()})
            .Where(x => x.Count > 0)
            .ToListAsync();
    }
}

public class MyDbContext : DbContext
{
    public DbSet<MyEntity> MyEntities { get; set; }
    public DbSet<MyEntity2> MyEntities2 { get; set; }

    public MyDbContext(DbContextOptions options) : base(options)
    {
    }
}

public class MyEntity
{
    public int Id { get; set; }
}

public class MyEntity2
{
    public int Id { get; set; }
}
```

First example produces:

```SQL
SELECT "t"."Name", COUNT(*) AS "Count"
FROM (
    SELECT "m"."Id", 'MyEntities' AS "Name"
    FROM "MyEntities" AS "m"
    UNION
    SELECT "m0"."Id", 'MyEntities2' AS "Name"
    FROM "MyEntities2" AS "m0"
) AS "t"
GROUP BY "t"."Name"
HAVING COUNT(*) > 0
```
Second (breaking) example produces
```SQL
SELECT 'MyEntities' AS "Name", COUNT(*) AS "Count"
FROM "MyEntities" AS "m"
WHERE COUNT(*) > 0
```
### Stack trace

```
Microsoft.EntityFrameworkCore.Query: Error: An exception occurred while iterating over the results of a query for context type 'EfCoreIssues.MyDbContext'.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'misuse of aggregate: COUNT()'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

```

### Provider and version information

EF Core version: 3.1.8
Database provider: Microsoft.EntityFrameworkCore.Sqlite 3.1.8
Target framework: .NET 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.7.2

**Comment by smitpatel** [comment]
Same root cause as #19027

**Comment by smitpatel** [comment]
Added regression test in #25552
