### ISSUE TITLE
RC1: Inconsistent error while Update-Database if FK wasn't defined correctly

### ISSUE THREAD

**Issue by Saibamen** [dotnet/efcore#22912]
## File a bug

Errors from Update-Database are IMHO inconsistents and hard to fix by reading them if FKeys was defined incorrectly.

### Code, steps and errors

My entity configuration:

```C#
public void Configure(EntityTypeBuilder<MyEntity> entity)
{
    entity.HasIndex(e => e.BelegPositionId).HasDatabaseName("IX_BelegPositionId");
    entity.HasIndex(e => e.MandantId).HasDatabaseName("IX_MandantId");
    entity.Property(e => e.BelegPositionSonderwuschId).ValueGeneratedOnAdd().UseIdentityColumn().Metadata.SetBeforeSaveBehavior(PropertySaveBehavior.Ignore);
    entity.HasKey(e => new { e.BelegPositionSonderwuschId, e.BelegPositionId }).HasName("PK_dbo.MyEntity");

    // TODO: Fix - migration creates BelegPositionId1 column
    entity.HasOne(d => d.BelegPosition)
        .WithMany()
        .HasForeignKey(d => d.BelegPositionId)
        .HasConstraintName("FK_dbo.MyEntity_dbo.BelegPosition_BelegPositionId");

    // TODO: Fix MandantId FK. Error for Update-Database command: Foreign key 'FK_dbo.MyEntity_dbo.Mandant_MandantId' references invalid table 'Mandant'
    entity.HasOne(d => d.Mandant)
        .WithMany()
        .HasForeignKey(d => d.MandantId)
        .HasConstraintName("FK_dbo.MyEntity_dbo.Mandant_MandantId");
}
```

While I wanted to `dotnet ef database update --connection "MyConnStr"` I had **error**: `Foreign key 'FK_dbo.MyEntity_dbo.Mandant_MandantId' references invalid table 'Mandant'.`

**I spend a lot of time to trying to fix this `Mandant` error!**

Then I give up and commented-out this `Mandant` FK configuration:
```
/*entity.HasOne(d => d.Mandant)
    .WithMany()
    .HasForeignKey(d => d.MandantId)
    .HasConstraintName("FK_dbo.MyEntity_dbo.Mandant_MandantId");*/
```

And the migration applies without any error, but in my database I see **additional column**: `BelegPositionId1`:
![image](https://user-images.githubusercontent.com/905878/95324897-b5a1c700-08a0-11eb-9eb8-5dbc892b9dd2.png)
`BelegPositionId` is also there:
![image](https://user-images.githubusercontent.com/905878/95324944-c81c0080-08a0-11eb-8406-1c8ced54ca48.png)

** There is no error for this additional columns (with numbers at the end of name) while creating migration or applying it **

But I fixed it by adding `p => p.SonderWuensche` to `WithMany()`:

```
entity.HasOne(d => d.BelegPosition)
    .WithMany(p => p.SonderWuensche)
    .HasForeignKey(d => d.BelegPositionId)
    .HasConstraintName("FK_dbo.MyEntity_dbo.BelegPosition_BelegPositionId");
```

Now my DB doesn't have additional `BelegPositionId1` column 👍 

Then I uncommented this FK setup for `Mandant` (**without any code changes**) and... ** this `Foreign key 'FK_dbo.MyEntity_dbo.Mandant_MandantId' references invalid table 'Mandant'.` error magically disappears... **

### Suggestions

Additional checks in code for creating migration/applying it + new errors to display.

Stop throwing error for Foreign Keyx that are correct - for example: throw it for `FK_dbo.MyEntity_dbo.BelegPosition_BelegPositionId`, not for `FK_dbo.MyEntity_dbo.Mandant_MandantId`...

Or maybe adding more text to currect errors will be just enough...

### Include stack traces

Stack trace for database update (`Mandant`):

```
Microsoft.Data.SqlClient.SqlException (0x80131904): Foreign key 'FK_dbo.MyEntity.Mandant_MandantId' references invalid table 'Mandant'.
Could not create constraint or index. See previous errors.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) in H:\tsaagent1\_work\21\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlConnection.cs:line 1782
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) in H:\tsaagent1\_work\21\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlInternalConnection.cs:line 614
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) in H:\tsaagent1\_work\21\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\TdsParser.cs:line 1302
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) in H:\tsaagent1\_work\21\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\TdsParser.cs:line 1876
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite) in H:\tsaagent1\_work\21\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 3043
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName) in H:\tsaagent1\_work\21\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 1483
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery() in H:\tsaagent1\_work\21\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 1041
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:d279c1f1-6176-45d9-a6af-cdec0a5e9492
Error Number:1767,State:0,Class:16
Foreign key 'FK_dbo.MyEntity.Mandant_MandantId' references invalid table 'Mandant'.
Could not create constraint or index. See previous errors
```

### Include provider and version information

EF Core version: 5.0.0-rc.1.20451.13
Database provider: Microsoft.EntityFrameworkCore.SqlServer 
Target framework: .NET Core 3.1 (SDK: 3.1.402)
Operating system: Windows 10.0.18363.1082
IDE: 16.7.5

**Comment by AndriySvyryd** [comment]
@Saibamen Please provide a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so we can investigate this.

**Comment by Saibamen** [comment]
Sorry, I can't create repro project - I tried, but there's too many configurations to change to make it possible to upload as public project.

**Comment by AndriySvyryd** [comment]
@bricelam

**Comment by bricelam** [comment]
Given that this error is coming from SQL Server, there's not much we can do about it. If SQL Server could return the malformed FK to EF, it can (and does) provide a better error message.
