### ISSUE TITLE
Check commands[i] is not null for avoid NPE on Dispose command

### ISSUE THREAD

**Issue by eklimanov** [dotnet/efcore#22921]
@bricelam FYI

Sometimes in inner collection _commands can be null value
![image](https://user-images.githubusercontent.com/4698787/95443071-cd428380-0964-11eb-8423-b58e61775f10.png)

```
internal void RemoveCommand(SqliteCommand command)
        {
            for (var i = _commands.Count - 1; i >= 0; i--)
            {
               //Could you check _commands[i] on null value here and delete this broken value?
                if (_commands[i].TryGetTarget(out var item)
                    && item == command)
                {
                    _commands.RemoveAt(i);
                }
            }
        }
```

**Comment by bricelam** [comment]
I expect all this code will change as part of #14044, but feel free to submit a PR in the meantime.

**Comment by lilith** [comment]
Is there any workaround to this? I'm hitting this even in development.

**Comment by eklimanov** [comment]
Also we face  with next Exception. We can't any Commit or Rollback transaction. Could you help me with any workaround?
```
Message: OnException Exception Message: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Data.Sqlite.SqliteConnection.RemoveCommand(SqliteCommand) + 0x3e
   at Microsoft.Data.Sqlite.SqliteCommand.Dispose(Boolean) + 0x21
   at System.ComponentModel.Component.Dispose() + 0xc
   at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection, String, SqliteParameter[]) + 0x22b
   at Microsoft.Data.Sqlite.SqliteTransaction.RollbackInternal() + 0x5c
   at Microsoft.Data.Sqlite.SqliteTransaction.Rollback()
```

**Comment by bricelam** [comment]
Are you using the same connection on multiple threads? ADO.NET objects are generally not thread safe.

**Comment by ajcvickers** [comment]
Just saw this on a local run of the EF tests:

```
 Microsoft.EntityFrameworkCore.Query.AdHocQuerySplittingQuerySqliteTest.Can_query_with_nav_collection_in_projection_with_split_query_in_parallel_sync
System.AggregateException : One or more errors occurred. (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.)\r\n---- System.NullReferenceException : Object reference not set to an instance of an object.\r\n---- System.NullReferenceException : Object reference not set to an instance of an object.
----- Inner Stack Trace #1 (System.NullReferenceException) -----
   at Microsoft.Data.Sqlite.SqliteConnection.RemoveCommand(SqliteCommand command) in C:\local\code\efcore\src\Microsoft.Data.Sqlite.Core\SqliteConnection.cs:line 451
   at Microsoft.Data.Sqlite.SqliteCommand.Dispose(Boolean disposing) in C:\local\code\efcore\src\Microsoft.Data.Sqlite.Core\SqliteCommand.cs:line 225
   at System.ComponentModel.Component.Dispose()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDataReader.Dispose() in C:\local\code\efcore\src\EFCore.Relational\Storage\RelationalDataReader.cs:line 182
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.Enumerator.Dispose() in C:\local\code\efcore\src\EFCore.Relational\Query\Internal\SplitQueryingEnumerable.cs:line 258
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at lambda_method408828(Closure, QueryContext)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query) in C:\local\code\efcore\src\EFCore\Query\Internal\QueryCompiler.cs:line 68
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression) in C:\local\code\efcore\src\EFCore\Query\Internal\EntityQueryProvider.cs:line 64
   at Microsoft.EntityFrameworkCore.Query.AdHocQuerySplittingQueryTestBase.<>c__DisplayClass15_0.<Can_query_with_nav_collection_in_projection_with_split_query_in_parallel_sync>g__Query|2(Guid parentId, Guid collectionId) in C:\local\code\efcore\test\EFCore.Relational.Specification.Tests\Query\AdHocQuerySplittingQueryTestBase.cs:line 216
   at Microsoft.EntityFrameworkCore.Query.AdHocQuerySplittingQueryTestBase.<>c__DisplayClass15_0.<Can_query_with_nav_collection_in_projection_with_split_query_in_parallel_sync>b__0() in C:\local\code\efcore\test\EFCore.Relational.Specification.Tests\Query\AdHocQuerySplittingQueryTestBase.cs:line 206
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Query.AdHocQuerySplittingQueryTestBase.Can_query_with_nav_collection_in_projection_with_split_query_in_parallel_sync() in C:\local\code\efcore\test\EFCore.Relational.Specification.Tests\Query\AdHocQuerySplittingQueryTestBase.cs:line 208
--- End of stack trace from previous location ---
----- Inner Stack Trace #2 (System.NullReferenceException) -----
   at Microsoft.Data.Sqlite.SqliteConnection.Close() in C:\local\code\efcore\src\Microsoft.Data.Sqlite.Core\SqliteConnection.cs:line 344
   at Microsoft.Data.Sqlite.SqliteConnection.Dispose(Boolean disposing) in C:\local\code\efcore\src\Microsoft.Data.Sqlite.Core\SqliteConnection.cs:line 415
   at System.ComponentModel.Component.Dispose()
   at Microsoft.EntityFrameworkCore.TestUtilities.RelationalTestStore.Dispose() in C:\local\code\efcore\test\EFCore.Relational.Specification.Tests\TestUtilities\RelationalTestStore.cs:line 52
   at Microsoft.EntityFrameworkCore.TestUtilities.TestStore.DisposeAsync() in C:\local\code\efcore\test\EFCore.Specification.Tests\TestUtilities\TestStore.cs:line 97
   at Microsoft.EntityFrameworkCore.NonSharedModelTestBase.DisposeAsync() in C:\local\code\efcore\test\EFCore.Specification.Tests\NonSharedModelTestBase.cs:line 148
```

**Comment by ajcvickers** [comment]
Note that this is because the test is re-using the same connection on multiple threads concurrently.
