### ISSUE TITLE
Error in EF 5.0.0-rc.2.20475.6: Could not load type 'Microsoft.EntityFrameworkCore.DbQuery`1'...

### ISSUE THREAD

**Issue by ageiter** [dotnet/efcore#22996]
I just loaded the latest version 5.0.0-rc.2.20475.6 (previously I had version 3.8.1) and I get the following error when running my unit tests or starting the application.

In UnitTest (using Microsoft.EntityFrameworkCore.InMemory):
```
  Message: 
    System.TypeLoadException : Could not load type 'Microsoft.EntityFrameworkCore.DbQuery`1' from assembly 'Microsoft.EntityFrameworkCore, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
  Stack Trace: 
    <>c.<GetEntityTypeInfos>b__0_0(PropertyInfo property)
    WhereSelectArrayIterator`2.MoveNext()
    EfGenericRepositoryRegistrar.RegisterForDbContext(Type dbContextType, IIocManager iocManager, Type repositoryInterface, Type repositoryInterfaceWithPrimaryKey, Type repositoryImplementation, Type repositoryImplementationWithPrimaryKey)
    EfGenericRepositoryRegistrar.RegisterForDbContext(Type dbContextType, IIocManager iocManager, AutoRepositoryTypesAttribute defaultAutoRepositoryTypesAttribute)
    AbpEntityFrameworkCoreModule.RegisterGenericRepositoriesAndMatchDbContexes()
    AbpEntityFrameworkCoreModule.Initialize()
    <>c.<StartModules>b__15_1(AbpModuleInfo module)
    List`1.ForEach(Action`1 action)
    AbpModuleManager.StartModules()
    AbpBootstrapper.Initialize()
    AbpIntegratedTestBase`1.InitializeAbp()
    AbpIntegratedTestBase`1.ctor(Boolean initializeAbp, IIocManager localIocManager)
    DataTestBase.ctor() line 9
    TagRepositoryTest.ctor()
```

At application startup (using Microsoft.EntityFrameworkCore.SqlServer):
```
Microsoft.AspNetCore.Hosting.WebHost: Critical: Application startup exception

System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.DbQuery`1' from assembly 'Microsoft.EntityFrameworkCore, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Abp.EntityFrameworkCore.EfCoreDbContextEntityFinder.<>c.<GetEntityTypeInfos>b__0_0(PropertyInfo property)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at Abp.EntityFramework.Repositories.EfGenericRepositoryRegistrar.RegisterForDbContext(Type dbContextType, IIocManager iocManager, Type repositoryInterface, Type repositoryInterfaceWithPrimaryKey, Type repositoryImplementation, Type repositoryImplementationWithPrimaryKey)
   at Abp.EntityFramework.Repositories.EfGenericRepositoryRegistrar.RegisterForDbContext(Type dbContextType, IIocManager iocManager, AutoRepositoryTypesAttribute defaultAutoRepositoryTypesAttribute)
   at Abp.EntityFrameworkCore.AbpEntityFrameworkCoreModule.RegisterGenericRepositoriesAndMatchDbContexes()
   at Abp.EntityFrameworkCore.AbpEntityFrameworkCoreModule.Initialize()
   at Abp.Modules.AbpModuleManager.<>c.<StartModules>b__15_1(AbpModuleInfo module)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Abp.Modules.AbpModuleManager.StartModules()
   at Abp.AbpBootstrapper.Initialize()
   at Abp.AspNetCore.AbpApplicationBuilderExtensions.InitializeAbp(IApplicationBuilder app)
   at Abp.AspNetCore.AbpApplicationBuilderExtensions.UseAbp(IApplicationBuilder app, Action`1 optionsAction)
   at Abp.AspNetCore.AbpApplicationBuilderExtensions.UseAbp(IApplicationBuilder app)
   at Funstats.Web.BlazorApp.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in D:\projekte_git\Funstats\FS_Funstats\Source\Funstats\Funstats.Web.BlazorApp\Startup.cs:line 47
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
Exception thrown: 'System.TypeLoadException' in Microsoft.AspNetCore.Hosting.dll
Exception thrown: 'System.TypeLoadException' in System.Private.CoreLib.dll
Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll
The thread 0x297c has exited with code 0 (0x0).
Exception thrown: 'System.TypeLoadException' in System.Private.CoreLib.dll
Exception thrown: 'System.TypeLoadException' in System.Private.CoreLib.dll
Exception thrown: 'System.TypeLoadException' in System.Private.CoreLib.dll
An unhandled exception of type 'System.TypeLoadException' occurred in System.Private.CoreLib.dll
Could not load type 'Microsoft.EntityFrameworkCore.DbQuery`1' from assembly 'Microsoft.EntityFrameworkCore, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
```

### Note
* Add-Migration worked
* All EF packages have same version

### Version information

EF Core version: 5.0.0-rc.2.20475.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer / Microsoft.EntityFrameworkCore.InMemory
Target framework: 3.1
Operating system: Windows 10.0.18362
IDE: Visual Studio 2019 16.7.6

```
PM> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.403
 Commit:    9e895200cd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.403\

Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9
```

**Comment by ageiter** [comment]
The problem is due to ASP.NET Boilerplate... is not yet compatible with EF Core 5.
