### ISSUE TITLE
[5.0 RC2] Migration broken after upgrade from 3.1 to 5.0

### ISSUE THREAD

**Issue by mareklinka** [dotnet/efcore#23045]
Hello all. I seem to have found either a regression or a breaking change after I tried to migrate our solution from EF Core 3.1 to 5.0 RC2. We are using SQL Server.

## Situation
I have a set of migrations that work just fine under 3.1. I have a table called `Wheres` with a string column `Code`. Up until a certain point, this column was declared as `nvarchar(max)`. In the problematic migration, we added a new index to that table that contains the `Code` column. The following was scaffolded:

``` csharp
migrationBuilder.AlterColumn<string>(
    name: "Code",
    table: "Wheres",
    nullable: true,
    oldClrType: typeof(string),
    oldNullable: true);

migrationBuilder.CreateIndex(
    name: "IX_Wheres_VersionId_Code",
    table: "Wheres",
    columns: new[] { "VersionId", "Code" },
    unique: true,
    filter: "[Code] IS NOT NULL");
```

I am aware that to participate in an index, a string column must have a maximum length set. This seems to have worked automatically in 3.1 as this migration passed without issues (and is in fact deployed in production).

However, this fails under 5.0 RC2:

```
Failed executing DbCommand (12ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE UNIQUE INDEX [IX_Wheres_VersionId_Code] ON [Wheres] ([VersionId], [Code]) WHERE [Code] IS NOT NULL;
Microsoft.Data.SqlClient.SqlException (0x80131904): Column 'Code' in table 'Wheres' is of a type that is invalid for use as a key column in an index.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)        
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:e300beba-f685-4062-940d-6b063540fc89
Error Number:1919,State:1,Class:16
Column 'Code' in table 'Wheres' is of a type that is invalid for use as a key column in an index.
```

Is this behavior expected? If so, what would be the recommended procedure for upgrading to 5.0 here?

### Version info

EF Core version: 5.0.0-rc.2.20475.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10 (2004)
IDE: Visual Studio Code 1.50.1

**Comment by ajcvickers** [comment]
@mareklinka Ideally, a runnable project would make this a lot easier to investigate. Some other questions:
* What does the database table look like before applying the migration?
* What is the SQL generated from the problematic migration? (Use the --verbose option.)
* For the problematic migration, how does the SQL generated when using 5.0 differ from the SQL generated using 3.1?

**Comment by mareklinka** [comment]
After playing around with the problem a bit, I managed to trace it down. The migration in question is relatively old and was created by EF Core 3.0.0 (verified in `.Designer.cs`). When I tried to create a minimal repro for you, I created a single entity:

``` csharp
public class Entity
{
    public int Id { get; set; }

    public string Code { get; set; }
}
```

The initial migration just creates this table and `Code` is `nvarchar(max)`:

![01_InitialMigration](https://user-images.githubusercontent.com/7479226/96622433-38e40380-130a-11eb-806e-4d2ca349f03a.png)

Then I added an index on the (`Id`, `Code`) columns. The **current** tooling (3.1.9) scaffolded the following migration:

``` csharp
migrationBuilder.AlterColumn<string>(
    name: "Code",
    table: "Entities",
    nullable: true,
    oldClrType: typeof(string),
    oldType: "nvarchar(max)",
    oldNullable: true);

migrationBuilder.CreateIndex(
    name: "IX_Entities_Id_Code",
    table: "Entities",
    columns: new[] { "Id", "Code" });
```

This migration works correctly both under 3.1 and 5.0 RC2. However, I noticed one major difference between this migration and the failing one, namely the `oldType: "nvarchar(max)"` parameter. This is NOT present on the migration that fails. So I removed it and tried again. 3.1 accepts such a migration without issues, 5.0 RC2 fails with the following varbose output:

```
dotnet exec --depsfile C:\Source\Personal\ef-repro\bin\Debug\net5.0\ef-repro.deps.json --additionalprobingpath C:\Users\Marek\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig C:\Source\Personal\ef-repro\bin\Debug\net5.0\ef-repro.runtimeconfig.json C:\Users\Marek\.dotnet\tools\.store\dotnet-ef\3.1.8\dotnet-ef\3.1.8\tools\netcoreapp3.1\any\tools\netcoreapp2.0\any\ef.dll database update --assembly C:\Source\Personal\ef-repro\bin\Debug\net5.0\ef-repro.dll 
--startup-assembly C:\Source\Personal\ef-repro\bin\Debug\net5.0\ef-repro.dll --project-dir C:\Source\Personal\ef-repro\ --language C# --working-dir C:\Source\Personal\ef-repro --verbose --root-namespace ef_repro
Using assembly 'ef-repro'.
Using startup assembly 'ef-repro'.
Using application base 'C:\Source\Personal\ef-repro\bin\Debug\net5.0'.
Using working directory 'C:\Source\Personal\ef-repro'.
Using root namespace 'ef_repro'.
Using project directory 'C:\Source\Personal\ef-repro\'.
The Entity Framework tools version '3.1.8' is older than that of the runtime '5.0.0-rc.2.20475.6'. Update the tools for the latest features and bug fixes.
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'ef-repro'...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'DatabaseContext'.
Using context 'DatabaseContext'.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding design-time services referenced by assembly 'ef-repro'...
Finding design-time services referenced by assembly 'ef-repro'...
No referenced design-time services were found.
Finding IDesignTimeServices implementations in assembly 'ef-repro'...
No design-time services were found.
Migrating using database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Opening connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Opened connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Creating DbCommand for 'ExecuteNonQuery'.
Created DbCommand for 'ExecuteNonQuery' (3ms).
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
Executed DbCommand (14ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
Closing connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Closed connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Creating DbCommand for 'ExecuteScalar'.
Created DbCommand for 'ExecuteScalar' (1ms).
Opening connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Opened connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Executed DbCommand (13ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Closing connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Closed connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Opening connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Opened connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Creating DbCommand for 'ExecuteNonQuery'.
Created DbCommand for 'ExecuteNonQuery' (1ms).
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
Executed DbCommand (7ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
Closing connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Closed connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Creating DbCommand for 'ExecuteScalar'.
Created DbCommand for 'ExecuteScalar' (1ms).
Opening connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Opened connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Closing connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Closed connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Creating DbCommand for 'ExecuteReader'.
Created DbCommand for 'ExecuteReader' (4ms).
Opening connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Opened connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [MigrationId], [ProductVersion]
FROM [__EFMigrationsHistory]
ORDER BY [MigrationId];
Executed DbCommand (12ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [MigrationId], [ProductVersion]
FROM [__EFMigrationsHistory]
ORDER BY [MigrationId];
A data reader was disposed.
Closing connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Closed connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Applying migration '20201020170307_AddIndexMigration'.
Opening connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Opened connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Beginning transaction with isolation level 'Unspecified'.
Began transaction with isolation level 'ReadCommitted'.
Creating DbCommand for 'ExecuteNonQuery'.
Created DbCommand for 'ExecuteNonQuery' (4ms).
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE INDEX [IX_Entities_Id_Code] ON [Entities] ([Id], [Code]);
Failed executing DbCommand (8ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE INDEX [IX_Entities_Id_Code] ON [Entities] ([Id], [Code]);
Disposing transaction.
Closing connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Closed connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
'DatabaseContext' disposed.
Microsoft.Data.SqlClient.SqlException (0x80131904): Column 'Code' in table 'Entities' is of a type that is invalid for use as a key column in an index.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:4ffeec41-1f40-4086-a885-6f6afbf5d405
Error Number:1919,State:1,Class:16
Column 'Code' in table 'Entities' is of a type that is invalid for use as a key column in an index.
```

Compared with the exact same migration with EF 3.1.9:

```
dotnet exec --depsfile C:\Source\Personal\ef-repro\bin\Debug\net5.0\ef-repro.deps.json --additionalprobingpath C:\Users\Marek\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig C:\Source\Personal\ef-repro\bin\Debug\net5.0\ef-repro.runtimeconfig.json C:\Users\Marek\.dotnet\tools\.store\dotnet-ef\3.1.8\dotnet-ef\3.1.8\tools\netcoreapp3.1\any\tools\netcoreapp2.0\any\ef.dll database update --assembly C:\Source\Personal\ef-repro\bin\Debug\net5.0\ef-repro.dll 
--startup-assembly C:\Source\Personal\ef-repro\bin\Debug\net5.0\ef-repro.dll --project-dir C:\Source\Personal\ef-repro\ --language C# --working-dir C:\Source\Personal\ef-repro --verbose --root-namespace ef_repro
Using assembly 'ef-repro'.
Using startup assembly 'ef-repro'.
Using application base 'C:\Source\Personal\ef-repro\bin\Debug\net5.0'.
Using working directory 'C:\Source\Personal\ef-repro'.
Using root namespace 'ef_repro'.
Using project directory 'C:\Source\Personal\ef-repro\'.
The EF Core tools version '3.1.8' is older than that of the runtime '3.1.9'. Update the tools for the latest features and bug fixes.
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'DatabaseContext'.
Using context 'DatabaseContext'.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding design-time services referenced by assembly 'ef-repro'.
No referenced design-time services were found.
Finding IDesignTimeServices implementations in assembly 'ef-repro'...
No design-time services were found.
Migrating using database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Opening connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Opened connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Creating DbCommand for 'ExecuteNonQuery'.
Created DbCommand for 'ExecuteNonQuery' (3ms).
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
Executed DbCommand (17ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
Closing connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Closed connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Creating DbCommand for 'ExecuteScalar'.
Created DbCommand for 'ExecuteScalar' (6ms).
Opening connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Opened connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Executed DbCommand (17ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Closing connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Closed connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Opening connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Opened connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Creating DbCommand for 'ExecuteNonQuery'.
Created DbCommand for 'ExecuteNonQuery' (0ms).
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
Closing connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Closed connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Creating DbCommand for 'ExecuteScalar'.
Created DbCommand for 'ExecuteScalar' (4ms).
Opening connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Opened connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Closing connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Closed connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Creating DbCommand for 'ExecuteReader'.
Created DbCommand for 'ExecuteReader' (2ms).
Opening connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Opened connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [MigrationId], [ProductVersion]
FROM [__EFMigrationsHistory]
ORDER BY [MigrationId];
Executed DbCommand (8ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [MigrationId], [ProductVersion]
FROM [__EFMigrationsHistory]
ORDER BY [MigrationId];
A data reader was disposed.
Closing connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Closed connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Applying migration '20201020170307_AddIndexMigration'.
Opening connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Opened connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Beginning transaction with isolation level 'Unspecified'.
Began transaction with isolation level 'ReadCommitted'.
Creating DbCommand for 'ExecuteNonQuery'.
Created DbCommand for 'ExecuteNonQuery' (5ms).
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
DECLARE @var0 sysname;
SELECT @var0 = [d].[name]
FROM [sys].[default_constraints] [d]
INNER JOIN [sys].[columns] [c] ON [d].[parent_column_id] = [c].[column_id] AND [d].[parent_object_id] = [c].[object_id]
WHERE ([d].[parent_object_id] = OBJECT_ID(N'[Entities]') AND [c].[name] = N'Code');
IF @var0 IS NOT NULL EXEC(N'ALTER TABLE [Entities] DROP CONSTRAINT [' + @var0 + '];');
ALTER TABLE [Entities] ALTER COLUMN [Code] nvarchar(450) NULL;
Executed DbCommand (22ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
DECLARE @var0 sysname;
SELECT @var0 = [d].[name]
FROM [sys].[default_constraints] [d]
INNER JOIN [sys].[columns] [c] ON [d].[parent_column_id] = [c].[column_id] AND [d].[parent_object_id] = [c].[object_id]
WHERE ([d].[parent_object_id] = OBJECT_ID(N'[Entities]') AND [c].[name] = N'Code');
IF @var0 IS NOT NULL EXEC(N'ALTER TABLE [Entities] DROP CONSTRAINT [' + @var0 + '];');
ALTER TABLE [Entities] ALTER COLUMN [Code] nvarchar(450) NULL;
Creating DbCommand for 'ExecuteNonQuery'.
Created DbCommand for 'ExecuteNonQuery' (2ms).
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE INDEX [IX_Entities_Id_Code] ON [Entities] ([Id], [Code]);
Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE INDEX [IX_Entities_Id_Code] ON [Entities] ([Id], [Code]);
Creating DbCommand for 'ExecuteNonQuery'.
Created DbCommand for 'ExecuteNonQuery' (0ms).
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20201020170307_AddIndexMigration', N'3.1.9');
Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20201020170307_AddIndexMigration', N'3.1.9');
Committing transaction.
Committing transaction.
Disposing transaction.
Closing connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
Closed connection to database 'Repro23045' on server '(localdb)\mssqllocaldb'.
'DatabaseContext' disposed.
Done.
```

The repro I used is here: [ef-repro.zip](https://github.com/dotnet/efcore/files/5410461/ef-repro.zip)

Out of the box it's set up to fail - targeting EF Core 5.0.0-rc.2.20475.6 and with the `oldType` parameter commented out. Uncommenting the parameter or switching to EF Core 3.1.9 nugets will make the migration pass. The code uses SQL Server localDb for storage.

If you need any more details, let me know and I'll try to get them for you. Thanks for looking into this!

**Comment by ajcvickers** [comment]
@mareklinka Thanks!

@bricelam This does seem like a regression in 5.0. Can we investigate if there is anything we can do? If not, we should likely document how to edit existing migrations for this.

/cc @AndriySvyryd @roji
