### ISSUE TITLE
EF Core 5.0.0-rc2 has TypeLoadException with dotnet-ef

### ISSUE THREAD

**Issue by bryanboettcher** [dotnet/efcore#23075]
Tooling installed with:
```
dotnet tool install dotnet-ef --version 5.0.0-rc.2.20475.6
```

Tooling JSON:
```
C:\Users\bryan\source\repos\web-app\.config>type dotnet-tools.json
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "dotnet-ef": {
      "version": "5.0.0-rc.2.20475.6",
      "commands": [
        "dotnet-ef"
      ]
    }
  }
}
```

When trying to create the initial migration file:

```
C:\Users\bryan\source\repos\web-app>dotnet ef migrations add init
Build started...
Build succeeded.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Internal.SemanticVersionComparer' from assembly 'Microsoft.EntityFrameworkCore, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor..ctor(IOperationReportHandler reportHandler, IDictionary args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Microsoft.EntityFrameworkCore.Tools.ReflectionOperationExecutor..ctor(String assembly, String startupAssembly, String projectDir, String dataDirectory, String rootNamespace, String language, String[] remainingArguments)
   at Microsoft.EntityFrameworkCore.Tools.Commands.ProjectCommandBase.CreateExecutor(String[] remainingArguments)
   at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsAddCommand.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0(String[] args)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Exception has been thrown by the target of an invocation.
```

Version:
```
C:\Users\bryan\source\repos\web-app\.config>dotnet --version
3.1.401
```

**Comment by ajcvickers** [comment]
@bryanboettcher Can you post your csproj file?

/cc @bricelam

**Comment by bryanboettcher** [comment]
.... no, because then it will clearly show that I left Microsoft.EntityFramework.Tools as version 3.1.9.  We can probably close this...

**Comment by bricelam** [comment]
Well that explains the message! I’ve been wondering about this one ever since it was first reported. Mixing assembly versions in your project would definitely cause it.
