### ISSUE TITLE
DB functions not supported on SQL Server (InvalidOperationException: Query has switched to client-evaluation)

### ISSUE THREAD

**Issue by mikeroque** [dotnet/efcore#23081]
Pseudocode:
```
int value = EFModel.RelatedCollection.Sum(m => EF.Functions.DateDiffDay(m.DateField1, m.DateField2) + 1);
```
Error:
```
System.InvalidOperationException: The 'DateDiffDay' method is not supported because the query has switched to client-evaluation. This usually happens when the arguments to the method cannot be translated to server. Rewrite the query to avoid client evaluation of arguments so that method can be translated to server.
   at Microsoft.EntityFrameworkCore.SqlServerDbFunctionsExtensions.DateDiffDay(DbFunctions _, DateTime startDate, DateTime endDate)
   at SqlServerDbFunctionsExtensionsClientEvaluation.Controllers.HomeController.<>c.<Index>b__3_1(RelatedEFModel m) in C:\Users\Mike\source\repos\SqlServerDbFunctionsExtensionsClientEvaluation\Controllers\HomeController.cs:line 27
   at System.Linq.Enumerable.Sum[TSource](IEnumerable`1 source, Func`2 selector)
   at SqlServerDbFunctionsExtensionsClientEvaluation.Controllers.HomeController.Index() in C:\Users\Mike\source\repos\SqlServerDbFunctionsExtensionsClientEvaluation\Controllers\HomeController.cs:line 27
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Runnable repro project attached.

EF Core version: 5.0.0-rc.2.20475.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer 5.0.0-rc.2.20475.6
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Microsoft Visual Studio Enterprise 2019 Version 16.7.5
[SqlServerDbFunctionsExtensionsClientEvaluation.zip](https://github.com/dotnet/efcore/files/5430980/SqlServerDbFunctionsExtensionsClientEvaluation.zip)

**Comment by smitpatel** [comment]
`EFModel` is client side object, hence query is running as LINQ query using enumerable methods rather than running as EF Core query. Using DbFunctions outside of EF Core query is not supported.

**Comment by mikeroque** [comment]
OK. Thanks for the quick response.

**Comment by aquacat123** [comment]
@smitpatel and @ajcvickers  I am having a similar issue after upgrading from 3.1 to 5.0.  

This portion of my query produces the error: The 'DateDiffHour' method is not supported because the query has switched to client-evaluation. 
`let promisedTime = deliveries.DeliveryDate.HasValue && deliveries.PromisedTime.HasValue ? DateTime.Parse(deliveries.DeliveryDate.Value.ToShortDateString() + " " + deliveries.PromisedTime.Value.ToString()) : DateTime.Now.AddDays(1)
`
` PromisedTimeHourDiff = EF.Functions.DateDiffHour(DateTime.Now, promisedTime),` 

Can you tell me how to resolve this issue?
