### ISSUE TITLE
EF Core3.1 Relevant data filtering

### ISSUE THREAD

**Issue by hwl962589950** [dotnet/efcore#23187]
## File a bug
 
When using navigation attributes, when using related data, use:Where (s=>s.Shop.Count(d=>d.Id==1) > 0) is ok, but it will report an error in the splice mode
### Include your code

The code and methods used example:

```C#
var testLinq = dbContext.OrderDetaileds.AsNoTracking()
				.Include(s => s.OrderComments)
				.AsQueryable();
			var where = new Func<OrderComment, bool>(comment => comment.Id > 1); 
			var isOkLinq = testLinq.Where(s=>s.OrderComments.Count(comment => comment.Id > 1) > 0); // Is Ok
			var isErrorLinq = testLinq.Where(s=>s.OrderComments.Count(where) > 0); // Is Error
			isOkLinq.ToList();
			isErrorLinq.ToList();
```

### Include stack traces

Include the full exception message and stack trace for any exception you encounter.

Use triple-tick fences for stack traces. For example:

```
System.ArgumentException: Expression of type 'System.Func`2[AilExpress.Model.Models.OrderComment,System.Boolean]' cannot be used for parameter of type 'System.Linq.Expressions.Expression`1[System.Func`2[AilExpress.Model.Models.OrderComment,System.Boolean]]' of method 'Int32 Count[OrderComment](System.Linq.IQueryable`1[AilExpress.Model.Models.OrderComment], System.Linq.Expressions.Expression`1[System.Func`2[AilExpress.Model.Models.OrderComment,System.Boolean]])' (Parameter 'arg1')
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0, Expression arg1)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at Microsoft.EntityFrameworkCore.Query.Internal.EnumerableToQueryableMethodConvertingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AilExpress.Service.Services.OrderCommentService.GetSellerOrderCommentAsync(String sellerId, GetSellerOrderComment_Queny_Dto parameters) in C:\Users\hwl\Documents\Tencent Files\962589950\FileRecv\新速卖通\新建文件夹\AilExpress.Service\Services\OrderCommentService.cs:line 209
   at AilExpressCore.Areas.AilSeller.Controllers.TransactionController.GetOrderComment(GetSellerOrderComment_Queny_Dto queny) in C:\Users\hwl\Documents\Tencent Files\962589950\FileRecv\新速卖通\新建文件夹\AilExpressCore\Areas\AilSeller\Controllers\TransactionController.cs:line 480
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

### Include provider and version information

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer )
EF Core version: Microsoft.EntityFrameworkCore3.1.6
Target framework: (e.g. .NET Core3.1)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by smitpatel** [comment]
You need `Expression<Func<,>>` for it to work correctly with queryables.

**Comment by hwl962589950** [comment]
> 
> 
> You need `Expression<Func<,>>` for it to work correctly with queryables.

The navigation property has the parameter Func<,> instead of 'Expression,>'. I Compile it using the method 'Expression,>'

**public static int Count<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate);**

**Comment by smitpatel** [comment]
The major difference between both is that `Func<>` will create a delegate which is opaque to anyone whereas `Expression<Func<>>` will create a `LambdaExpression` which EF Core can inspect and translate correctly. Regardless of the type inferred inside the Count in `isOkLinq` since it is inside a lambda of larger queryable `Where` it preserve the `Func<>` in lambda expression form rather than compiling it to a delegate. Hence that query works correctly whereas other fails.

If you want to write lambdas outside of the queryable then you must use `Expression<Func<>>` A proper way to write above code would be
```C#
var testLinq = dbContext.OrderDetaileds.AsNoTracking()
				.Include(s => s.OrderComments)
				.AsQueryable();
			Expression<Func<OrderComment,bool>> where = comment => comment.Id > 1; 
			var workingLinq = testLinq.Where(s=>s.OrderComments.AsQueryable().Count(where) > 0);
```

**Comment by hwl962589950** [comment]
> 
> 
> The major difference between both is that `Func<>` will create a delegate which is opaque to anyone whereas `Expression<Func<>>` will create a `LambdaExpression` which EF Core can inspect and translate correctly. Regardless of the type inferred inside the Count in `isOkLinq` since it is inside a lambda of larger queryable `Where` it preserve the `Func<>` in lambda expression form rather than compiling it to a delegate. Hence that query works correctly whereas other fails.
> 
> If you want to write lambdas outside of the queryable then you must use `Expression<Func<>>` A proper way to write above code would be
> 
> ```cs
> var testLinq = dbContext.OrderDetaileds.AsNoTracking()
> 				.Include(s => s.OrderComments)
> 				.AsQueryable();
> 			Expression<Func<OrderComment,bool>> where = comment => comment.Id > 1; 
> 			var workingLinq = testLinq.Where(s=>s.OrderComments.AsQueryable().Count(where) > 0);
> ```

First of all, thank you very much for providing the method, and the method has been successfully solved, but I spliced the SQL statement generated by the lambda seems to have a problem. I think I wrote the splice. Is there a better way to put it together?

```cs
var where =await w.Where(s => s.OrderComments.AsQueryable().Count(d => d.Id > 1 && d.IsAnonymous == 0) > 0).ToArrayAsync();
```
The generated SQL statement:
 SELECT [o].[Id]
      FROM [OrderDetaileds] AS [o]
      LEFT JOIN [OrderComments] AS [o0] ON [o].[Id] = [o0].[OrderDetailId]
      WHERE (
          SELECT COUNT(*)
          FROM [OrderComments] AS [o1]
          WHERE ([o].[Id] = [o1].[OrderDetailId]) AND (([o1].[Id] > 1) AND ([o1].[IsAnonymous] = 0))) > 0
      ORDER BY [o].[Id], [o0].[Id]
```cs
Expression<Func<OrderComment,bool>> funcWhere = t => t.Id>1;
funcWhere=funcWhere.And(s => s.IsAnonymous == 0);
var whereFunc = await w.Where(s => s.OrderComments.AsQueryable().Count(funcWhere) > 0).ToArrayAsync();
```
 SELECT [o].[Id]
      FROM [OrderDetaileds] AS [o]
      LEFT JOIN [OrderComments] AS [o0] ON [o].[Id] = [o0].[OrderDetailId]
      WHERE (
          SELECT COUNT(*)
          FROM [OrderComments] AS [o1]
          WHERE ([o].[Id] = [o1].[OrderDetailId]) AND ((CASE
              WHEN [o1].[Id] > 1 THEN CAST(1 AS bit)
              ELSE CAST(0 AS bit)
          END & CASE
              WHEN [o1].[IsAnonymous] = 0 THEN CAST(1 AS bit)
              ELSE CAST(0 AS bit)
          END) = CAST(1 AS bit))) > 0
      ORDER BY [o].[Id], [o0].[Id]

Expression.And Implementation method:
```cs
public static Expression<Func<T, bool>> And<T>(this Expression<Func<T, bool>> expression1, Expression<Func<T, bool>> expression2)
{
	var invokedExpression = Expression.Invoke(expression2, expression1.Parameters.Cast<Expression>());
	return Expression.Lambda<Func<T, bool>>(Expression.And(expression1.Body, invokedExpression), expression1.Parameters);
}
```

**Comment by smitpatel** [comment]
> Expression.And

`Expression.And` generates a bitwise & operation. What you are looking for is `Expression.AndAlso` which generates bool conditional &&. If you use that in your `And` method then both queries will generate the same expression tree and would translate the same.

**Comment by hwl962589950** [comment]
> 
> 
> > Expression.And
> 
> `Expression.And` generates a bitwise & operation. What you are looking for is `Expression.AndAlso` which generates bool conditional &&. If you use that in your `And` method then both queries will generate the same expression tree and would translate the same.

The problem has been completely solved. Thank you very much
