### ISSUE TITLE
OrderBy inside Select broken from 2.2.4 -> 3.1.9

### ISSUE THREAD

**Issue by yousiftouma** [dotnet/efcore#23199]
## File a bug
Update: Updated the entity and the query to be less confusing (added ForeignKeyId)

I'm not sure if this is intended due to changes with client side evaluation. The exception does not mention it so I figure I'll post an issue. I'm not sure either if this is a good query to actually write but I want to understand if I can't do it at all.

### Include your code

Given an entity `Entity` with the following properties
```
public Guid Id { get; set; }
public Guid ForeignKeyId { get; set; }
public int PropertyOne { get; set; }
public int PropertyTwo { get; set; }
public int PropertyThree { get; set; }
```

This query worked in 2.2.4 but throws an exception now in 3.1.9, is this expected?

```
var test = await _context.Entity
  .GroupBy(x => x.ForeignKeyId)
  .Select(
    y => 
      y.OrderByDescending(x => x.PropertyOne)
        .ThenByDescending(x => x.PropertyTwo)
        .ThenByDescending(x => x.PropertyThree)
        .First()
    ).ToListAsync();
```

### Include stack traces

```
System.ArgumentException: Expression of type 'System.Linq.IQueryable`1[Data.Models.Entity]' cannot be used for parameter of type 'System.Linq.IOrderedQueryable`1[Data.Models.Entity]' of method 'System.Linq.IOrderedQueryable`1[Data.Models.Entity] ThenByDescending[Entity,Int32](System.Linq.IOrderedQueryable`1[Data.Models.Entity], System.Linq.Expressions.Expression`1[System.Func`2[Data.Models.Entity,System.Int32]])' (Parameter 'arg0')
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0, Expression arg1)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at Microsoft.EntityFrameworkCore.Query.Internal.EnumerableToQueryableMethodConvertingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitAndConvert[T](ReadOnlyCollection`1 nodes, String callerName)
   at Microsoft.EntityFrameworkCore.Query.Internal.EnumerableToQueryableMethodConvertingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitAndConvert[T](ReadOnlyCollection`1 nodes, String callerName)
   at Microsoft.EntityFrameworkCore.Query.Internal.EnumerableToQueryableMethodConvertingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

### Include provider and version information

EF Core version: 3.1.9
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: netcore3.1
Operating system: Windows 7
IDE: Visual Studio 2019 16.6.2

**Comment by ajcvickers** [comment]
@smitpatel to de-dupe.

**Comment by smitpatel** [comment]
#12088
