### ISSUE TITLE
QueryRootExpression is not a reducible node?

### ISSUE THREAD

**Issue by gnilsson** [dotnet/efcore#23197]
When merging to ef core 5 one of my expression tree queries broke and my suspicous for the culprit of this is that the expression property return type have changed.
When calling:
```C#
DbContext.Set<TEntity>().AsNoTracking().Expression
```
i get this:
```C#
{[Microsoft.EntityFrameworkCore.Query.QueryRootExpression] ..
```
instead of:
```C#
{value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[TContext.TEntity]) ..
```
and this breaks one of my queries, specifically my Include & ThenInclude expression tree when I compile the lambda delegate. I might have built it so that it worked by coincidence earlier or I might've stumbled upon some issue. Whichever it is i'd be glad to get some insight into this, thanks in advance.

I'll post specific methods if needed
stack:
```
System.ArgumentException: must be reducible node
   at System.Linq.Expressions.Expression.ReduceAndCheck()
   at System.Linq.Expressions.Expression.ReduceExtensions()
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExtensionExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(Expression expression, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression`1 lambda)
   at System.Linq.Expressions.Expression`1.Accept(StackSpiller spiller)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at System.Linq.Expressions.Expression`1.Compile(Boolean preferInterpretation)
   at System.Linq.Expressions.Expression`1.Compile()
   at Rapier.Internal.Utility.ExpressionUtility.IncludeBy[TEntity](IQueryable`1 source, ICollection`1 details)
```

**Comment by roji** [comment]
Note that you were using an internal API (EntityQueryable), we don't provide stability guarantees to those; it's better to stick to the public types (not in Internal namespaces).

Aside from that, we'd need to see your actual IncludeBy extension source in order to help with porting it to 5.0.

**Comment by gnilsson** [comment]
Thanks for the quick reply, ah alright I see. I also noticed this new auto include feature, that might change how I approach this problem. This solution to dynamic include probably wasn't perfect but it did the trick for the cases I encountered. 

```C#
        public static IIncludableQueryable<TEntity, object> IncludeBy<TEntity>(
                this IQueryable<TEntity> source,
                ICollection<string[]> details)
        {
            var type = typeof(TEntity);
            var body = source.Expression;
            foreach (var detail in details)
            {
                var parameter = Expression.Parameter(type, "p");
                var property = Expression.Property(parameter, detail[0]);
                body = CallInclude(
                    body, parameter, property, Methods.Include, 
                    new Type[] { type, property.Type });

                foreach (var then in detail.Skip(1))
                {
                    var previousType = property.Type.IsEnumerableType() ?
                        property.Type.GetGenericArguments()[0] :
                        property.Type;

                    parameter = Expression.Parameter(previousType, then[0].ToString().ToLower());
                    property = Expression.Property(parameter, then);
                    body = CallInclude(
                        body, parameter, property, Methods.ThenInclude,
                        new Type[] { type, previousType, property.Type });
                }
            }
            return Expression.Lambda<Func<IQueryable<TEntity>,
                IIncludableQueryable<TEntity, object>>>(
                body,
                Expression.Parameter(typeof(IQueryable<TEntity>)))
                .Compile()(source);
        }

        private static Expression CallInclude(
            Expression body, ParameterExpression parameter,
            MemberExpression property, string methodName,
            Type[] types)
        {
            var lambda = Expression.Lambda(
                Expression.MakeMemberAccess(
                    parameter, property.Member), parameter);
            return Expression.Call(
                typeof(EntityFrameworkQueryableExtensions),
                methodName, types, body,
                Expression.Quote(lambda));
        }
```

**Comment by roji** [comment]
Assuming I'm parsing your code correctly, I think you're looking for the string-based [`Include` method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.entityframeworkqueryableextensions.include?view=efcore-3.1#Microsoft_EntityFrameworkCore_EntityFrameworkQueryableExtensions_Include__1_System_Linq_IQueryable___0__System_String_) - note that it supports nested includes (ThenInclude) via the dot syntax. So your extension should be rewritable to something like the following:

```c#
public static IQueryable<TEntity> IncludeBy<TEntity>(
    this IQueryable<TEntity> source,
    ICollection<string[]> details)
    where TEntity : class
{
    foreach (var detail in details)
        source = source.Include(string.Join(".", detail));
    return source;
}
```

**Comment by gnilsson** [comment]
Aha :D 
had no clue that method supported ThenInclude too. Well solving it expression way was fun enough anyway ;)
Thanks alot.
