### ISSUE TITLE
Entity inheritance with owned property

### ISSUE THREAD

**Issue by hgGeorg** [dotnet/efcore#23285]
Using owned properties within class inheritance hierarchies causes columns/properties to be mapped incorrctly, or causes various exception to be thrown when trying to read something from DbContext.

#### Setup
```cs
[Owned]
public class OwnedClass
{
    public string A { get; set; }
    public string B { get; set; }
}

public class Root
{
    public int Id { get; set; }
    public OwnedClass OwnedProp { get; set; }

    public Root()
    {
        OwnedProp = new OwnedClass();
    }
}

public class ChildA : Root
{
    public bool Prop { get; set; }
}

public class ChildB : Root
{
    public double Prop { get; set; }
}

public class TestContext : DbContext
{
    public DbSet<Root> Table { get; set; }

    public TestContext(DbContextOptions options)
        : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ChildA>().HasBaseType<Root>();
        modelBuilder.Entity<ChildB>().HasBaseType<Root>();
        base.OnModelCreating(modelBuilder);
    }
}
```

#### Testcase
```cs
var options = new DbContextOptionsBuilder<TestContext>()
    .UseInMemoryDatabase("Test")
    .Options;
var context = new TestContext(options);

context.Table.Add(new ChildA());
context.SaveChanges();
context.ChangeTracker.Clear();
context.Table.ToList();
```

What exactly happens depends on the class setup. In this example a `InvalidCastException` is thrown.
If `ChildB.Prop` is a nullable property, a `NullReferenceException` is thrown.
If Prop of both child classes are nullable, then null is always returned regardless what has been saved.

Might be related to #23211 and/or #23276

EF Core version: 5.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer/Microsoft.EntityFrameworkCore.InMemory
Target framework: NET 5.0
Operating system: Windows 10, 2004
IDE: Visual Studio 2019 16.8

**Comment by ajcvickers** [comment]
@smitpatel @maumar This is a regression in 5.0. Stack trace:

```
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'TestContext'.
      System.InvalidCastException: Unable to cast object of type 'System.Double' to type 'System.Boolean'.
         at lambda_method(Closure , ValueBuffer )
         at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
         at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNextHelper()
         at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
      System.InvalidCastException: Unable to cast object of type 'System.Double' to type 'System.Boolean'.
         at lambda_method(Closure , ValueBuffer )
         at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
         at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNextHelper()
         at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'System.Double' to type 'System.Boolean'.
   at lambda_method(Closure , ValueBuffer )
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNextHelper()
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.Main() in /home/ajcvickers/AllTogetherNow/FiveOh/Program.cs:line 95
```

**Comment by smitpatel** [comment]
Note: error only happens in InMemory. Works for SqlServer correctly.

**Comment by smitpatel** [comment]
Meanwhile, initializing reference navigations in the ctor causes errors. See https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes#nonnullreferences

**Comment by ajcvickers** [comment]
@smitpatel I missed ` OwnedProp = new OwnedClass();` Is that the root cause?

**Comment by smitpatel** [comment]
No that is not the root cause. There is a bug in InMemory but once that is fixed, the reference navigation can have side-effects.

**Comment by hgGeorg** [comment]
> Note: error only happens in InMemory. Works for SqlServer correctly.

Correct, I mixed that up with another minor issue: Inheritance hierarchies with the same property names have different column names implicitly generated compared to efcore3.1. So changing ef core from 3.1 to 5.0 causes columns and properties to mapped incorrectly in some cases. But there is an easy workaround of just assigning an explicit column name.
