### ISSUE TITLE
Incorrect result for Distinct with Include

### ISSUE THREAD

**Issue by jahav** [dotnet/efcore#23284]
## File a bug

I have a query that returns incorrect results (doesn't return all Intermediaries it should and all Targets no matter the Intermediary are on the very last item in the list).

I am not sure what exactly is the bug, just that combination Distinct with Include doesn't play nice. The query returns the result with AsNoTracking and without (both of them wrong). 

Note: perhaps related Include design notes (https://github.com/dotnet/efcore/issues/12737#issuecomment-480029788). If this behaviors disallowed, the EF Core should return an exception/error instead of incorrect results.

### Include your code
The query
```C#
Source
	.AsNoTracking()
	.Include(i => i.Intermediary.Targets)
	.Where(x => x.Intermediary != null)
	.Select(x => x.Intermediary)
	.Distinct()
	.ToList();
```

Data to seed the table:
```sql
CREATE TABLE [dbo].[Intermediary](
	[IntermediaryId] [int] NOT NULL PRIMARY KEY
);
CREATE TABLE [dbo].[Source](
	[SourceId] [int] NOT NULL PRIMARY KEY,
	[IntermediaryId] [int] NULL FOREIGN KEY([IntermediaryId]) REFERENCES [dbo].[Intermediary] ([IntermediaryId])
);

CREATE TABLE [dbo].[Target] (
	[TargetId] [int] NOT NULL PRIMARY KEY,
	[IntermediaryId] [int] NOT NULL REFERENCES [dbo].[Intermediary] ([IntermediaryId])
);
INSERT [dbo].[Intermediary] ([IntermediaryId]) VALUES (1), (2), (3);
INSERT [dbo].[Source] ([SourceId], [IntermediaryId]) VALUES (1, 1), (2, 2), (3, 3);
INSERT [dbo].[Target] ([TargetId], [IntermediaryId]) VALUES (2, 2), (3, 3);
```

Expected Result

IntermediaryId  | TargetIds
-------------- | ---------
1 | 
2 |  2
3 |  3

Actual result:

IntermediaryId  | TargetIds
-------------- | ---------
1 | 
2 |  2, 3

```C#
class Source
{
	public int SourceId { get; set; }
	public int? IntermediaryId { get; set; }
	public Intermediary? Intermediary { get; set; }
}

class Intermediary
{
	public int IntermediaryId { get; set; }
	public ICollection<Target> Targets { get; set; }
}

class Target
{
	public int TargetId { get; set; }
}

class TestContext : DbContext
{

	public DbSet<Source> Source { get; set; }

	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	{
		base.OnConfiguring(optionsBuilder);
		optionsBuilder.UseSqlServer(@"Data Source=.\SQL2016;Initial Catalog=test;Integrated Security = SSPI");
	}
}

```
### Include provider and version information

EF Core version: 3.1.10
Database provider: Microsoft.EntityFrameworkCore.SqlServer 
Target framework: .NET Core 3.1.8
Operating system: Windows 10
IDE: LinqPad 6 x64 / Visual Studio 2019 16.7

**Comment by smitpatel** [comment]
Behavior in 5.0
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Unable to translate collection subquery in projection since the parent query doesn't project key columns of all of it's tables which are required to generate results on client side. This can happen when trying to correlate on keyless entity or when using 'Distinct' or 'GroupBy' operations without projecting all of the key columns.
  Source=Microsoft.EntityFrameworkCore.Relational
  StackTrace:
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ApplyCollectionJoin(Int32 collectionIndex, Int32 collectionId, Expression innerShaper, INavigationBase navigation, Type elementType, Boolean splitQuery)
   at Microsoft.EntityFrameworkCore.Query.Internal.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitExtension(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPostprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EFSampleApp.Program.<Main>d__0.MoveNext() in D:\code\EFSampleApp\EFSampleApp\Program.cs:line 30
```

See https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes#collection-distinct-groupby
