### ISSUE TITLE
Owned type used as primary key

### ISSUE THREAD

**Issue by mortenaslo** [dotnet/efcore#23310]
Owned type can't be used as primary key in EF Core 5.0, it worked in EF Core 3.1 (with a workaround). 

In EF Core 3.1, adding a model with a custom type as primary key worked fine. This worked by mapping the property from the owned type as a shadow key or as a property with same name, and then mapping the keys column names with HasKey method (see code examples below). 
It might be a bit of a workaround, but it worked. 

In EF Core 5.0, when mapping the property from the owned type, the column name can't be set to the same as the shadow key (name of the owned type are automatically prepended, if the column name already exists). 
Without shadow keys or properties with same naming in entity, the HasKey method fails:
```
The property 'FirstId' cannot be added to the type 'MyCoolModel' because there was no property type specified and there is no corresponding CLR property or field. To add a shadow state property the property type must be specified. 
```

Code examples (github repo also linked below): 

```C#
    [Table("my_cools", Schema = "cool_stuff")]
    public class MyCoolModel
    {
        public MyCoolModel() => Id = new MyCoolKey();

        // Optional, works with or without due to 'entityBuilder.Property(propertyType, property.Name);' in model builder
        //public int FirstId { get => Id.FirstId; set => Id.FirstId = value; }

        //public int SecondId { get => Id.SecondId; set => Id.SecondId = value; }

        public MyCoolKey Id { get; set; }

        public string SomeText { get; set; }
    }

    public class MyCoolKey
    {
        public int FirstId { get; set; }
        public int SecondId { get; set; }
    }
```

```C#
    public class MyDbContext : DbContext
    {
        public MyDbContext(DbContextOptions<MyDbContext> dbContextOptions) : base(dbContextOptions) { }
        public DbSet<MyCoolModel> MyCoolModels { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var entityBuilder = modelBuilder.Entity<MyCoolModel>();

            entityBuilder.OwnsOne(record => record.Id, p =>
            {
                var properties = p.OwnedEntityType.ClrType.GetProperties();
                foreach (var property in properties)
                {
                    var propertyType = property.PropertyType;

                    // Set column name for owned type to name of property
                    // This is ignored and/or prefixed with the owned type name, when the column already exists from another property. 
                    p.Property(propertyType, property.Name).HasColumnName(property.Name);

                    // Include property as a shadow property (if not already in model) in entity. 
                    // If not added, HasKey fails. 
                    entityBuilder.Property(propertyType, property.Name);
                }

                entityBuilder.HasKey(properties.Select(x => x.Name).ToArray());
            });

            base.OnModelCreating(modelBuilder);
        }
    }
```

```C#
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "cool_stuff");

            migrationBuilder.CreateTable(
                name: "my_cools",
                schema: "cool_stuff",
                columns: table => new
                {
                    MyCoolModel_FirstId = table.Column<int>(type: "int", nullable: false),
                    MyCoolModel_SecondId = table.Column<int>(type: "int", nullable: false),
                    FirstId = table.Column<int>(type: "int", nullable: true),
                    SecondId = table.Column<int>(type: "int", nullable: true),
                    SomeText = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_my_cools", x => new { x.MyCoolModel_FirstId, x.MyCoolModel_SecondId });
                });
        }
```

In EF Core 3.1 this would result in a migration looking like this (note the owned types are not added twice):
```C#
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "cool_stuff");

            migrationBuilder.CreateTable(
                name: "my_cools",
                schema: "cool_stuff",
                columns: table => new
                {
                    FirstId = table.Column<int>(nullable: false),
                    SecondId = table.Column<int>(nullable: false),
                    SomeText = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_my_cools", x => new { x.FirstId, x.SecondId });
                });
        }
```

Full example here, with branch for working 3.1 version: 
https://github.com/mortenaslo/EfCore5_OwnedTypesBug 

EF Core version: 5.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer (same result with Npgsql.EntityFrameworkCore.PostgreSQL)
Target framework: .NET 5.0
Operating system: Windows 10 Pro
IDE:  Visual Studio 2019 16.8.1

**Comment by ajcvickers** [comment]
@mortenaslo I am not able to reproduce this. When I run the code in your repro I don't see model building errors. Instead I see this:

```
fail: Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type 'EfCore5Test.Db.MyDbContext'.
      System.InvalidOperationException: The value of 'MyCoolKey.MyCoolModelSecondId' is unknown when attempting to save changes. This is because the property is also part of a foreign key for which the principal entity in the relationship is not known.
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.PrepareToSave()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetEntriesToSave(Boolean cascadeChanges)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
      System.InvalidOperationException: The value of 'MyCoolKey.MyCoolModelSecondId' is unknown when attempting to save changes. This is because the property is also part of a foreign key for which the principal entity in the relationship is not known.
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.PrepareToSave()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetEntriesToSave(Boolean cascadeChanges)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

**Comment by mortenaslo** [comment]
@ajcvickers I updated the examples with code running, but the issue is not running the code nor building it. The issue is with the mapping of the properties to columns in the migrations (and after). 
If you compare the migrations, EF Core 3.1 only had 3 columns for the model while EF Core 5.0 adds a duplicate column for each of the indexes resulting in 5 columns. I want to avoid the duplicate columns. 
Does that makes sense?

**Comment by mortenaslo** [comment]
Fixed it, I updated the repo with how to fix this workaround. I simply ignored the owned model that acts as key, then there is no duplicate columns and the properties still maps correctly. 
Basically, the issue was that it's no longer possible to map one column to multiple properties. And that is probably a good idea.

**Comment by emaborsa** [comment]
@mortenaslo Nice workaround. Suppose `FirstId` is a foreign key, is there a way to map `MyCoolModel`'s property `public virtual First First { get; set; }`?

**Comment by Blackclaws** [comment]
For those coming to this issue because they are facing a similar situation there are two things you can do:

1. If you are using table splitting and want to use properties of the owned type together with the foreign key as a composite key for the owned type table (In order to save an identity column there) you would do the following:

```
builder.OwnsMany(x => OwnedTypeList, navigationBuilder => {
    navigationBuilder.Property<KeyTypeOfOwningEntity>("ForeignKeyColumn");
    navigationBuilder.WithOwner().HasForeignKey("ForeignKeyColumn");
    navigationBuilder.HasKey("PropertyOfOwnedType", "MoreProperties", "ForeignKeyColumn");
}
```

2. If you want to use properties of an owned type without table splitting as parts of the primary key you can do the following:

```
builder.OwnsOne(x => x.OwnedProperty, ownedBuilder => {
   ownedBuilder.Property(x => x.AnyProperty).HasColumnName("FixedNameHere");
}
builder.Property(typeof(TypeOfTheAnyPropertyHere), "PropertyNameCanBeAnything").HasColumnName("FixedNameHere');
builder.HasKey("PropertyNameCanBeAnything", "MoreKeyParts");
```

This way you avoid duplicate columns and coerce the owned types properties onto the same column as the shadow properties on the owning type.

**Comment by windofny1** [comment]
> For those coming to this issue because they are facing a similar situation there are two things you can do:
> 
> 1. If you are using table splitting and want to use properties of the owned type together with the foreign key as a composite key for the owned type table (In order to save an identity column there) you would do the following:
> 
> ```
> builder.OwnsMany(x => OwnedTypeList, navigationBuilder => {
>     navigationBuilder.Property<KeyTypeOfOwningEntity>("ForeignKeyColumn");
>     navigationBuilder.WithOwner().HasForeignKey("ForeignKeyColumn");
>     navigationBuilder.HasKey("PropertyOfOwnedType", "MoreProperties", "ForeignKeyColumn");
> }
> ```
> 
> 2. If you want to use properties of an owned type without table splitting as parts of the primary key you can do the following:
> 
> ```
> builder.OwnsOne(x => x.OwnedProperty, ownedBuilder => {
>    ownedBuilder.Property(x => x.AnyProperty).HasColumnName("FixedNameHere");
> }
> builder.Property(typeof(TypeOfTheAnyPropertyHere), "PropertyNameCanBeAnything").HasColumnName("FixedNameHere');
> builder.HasKey("PropertyNameCanBeAnything", "MoreKeyParts");
> ```
> 
> This way you avoid duplicate columns and coerce the owned types properties onto the same column as the shadow properties on the owning type.

[Blackclaws](https://github.com/Blackclaws) Thanks for Yours solution. In my project there are classes for Entity, AggregateRoot and for ValueObject (in terms of DDD). And in Entity and Aggregate root there is property Id as ValueObject. And there are in my domain model exists some Entities with ValueObject as representation of Temporal row and it used as Primary Key. So here it is for example:
### Ordinary Value object (with one key =  Value as Guid)
``` csharp
public class OrdinaryValueObject : ValueObject, IOrdinaryValueObject
{
   public Guid Value { get; protected set; } 
  protected OrdinaryValueObject() : base()
    {

    }
    protected OrdinaryValueObject(Guid value)
    {
        Value = value;
    }
    protected OrdinaryValueObject(OrdinaryValueObject ordinaryValueObject)
    {
        Value = ordinaryValueObject.Value;
    }
    protected static OrdinaryValueObject CreateUniqueBase() 
    {
        return (new OrdinaryValueObject(Guid.NewGuid()));
    }
    public override IEnumerable<object> GetEqualityComponents()
    {
        yield return Value;
    }
}
```
### Temoral Value object (with two keys =  Value as Guid and SnapShotDate as DateTime)
``` csharp
public class TemporalValueObject : OrdinaryValueObject, ITemporalValueObject
    {
        public DateTime SnapShotDate { get; protected set; }

        protected TemporalValueObject():base() { }
        protected TemporalValueObject(Guid value, DateTime snapShotDate):base(value)
        { 
            SnapShotDate = snapShotDate;
        }
        protected TemporalValueObject(TemporalValueObject temporalValueObject):base(temporalValueObject.Value)
        { 
            SnapShotDate = temporalValueObject.SnapShotDate;
        }
        protected static TemporalValueObject CreateUniqueBase() 
        { 
            return new TemporalValueObject(Guid.NewGuid(), DateTime.UtcNow);
        }

        public override IEnumerable<object> GetEqualityComponents()
        {
            yield return Value;
            yield return SnapShotDate;
        }
    }
```
### Entity base class
``` csharp
public abstract class Entity<TId>:IEquatable<TId>, IEntity<TId>
        where TId : notnull 
    {
        
        public TId Id { get;  }
        protected Entity()
        {
           
        }
        protected Entity(TId id)
        {
            Id = id;
        }
        public override bool Equals(object? obj)
        {
            if (obj is null && Id is null)
            {
                return true;
            }            
            return obj is Entity<TId> entity && Id.Equals(entity.Id);
        }

        public bool Equals(TId? other)
        {
            return Equals((object?)other);
        }

        public static bool operator ==(Entity<TId> left, Entity<TId> right)
        {
            return Equals(left, right);
        }
        public static bool operator !=(Entity<TId> left, Entity<TId> right)
        {
            return !Equals(left, right);
        }
        public override int GetHashCode()
        {
            if (Id is null)
            {
                return 0;
            }
            return Id.GetHashCode();
        }
    }
```
### UserDataId temporal value object 
``` csharp
 public class UserDataId : TemporalValueObject
{
    private UserDataId() : base() { }
    private UserDataId(Guid value, DateTime snapShotDate) : base(value, snapShotDate)
    {

    }
    private UserDataId(TemporalValueObject temporalValueObject) : base(temporalValueObject) { }
    public static UserDataId CreateUnique()
    {
        return new(CreateUniqueBase());
    }

}
```
### UserData with temporal Id as UserId 
``` csharp
 
   public class UserData:Entity<UserDataId>
    {
         private UserData():base()
        {

        }
         private UserData(UserDataId userDataId, 
            string firstName,string middleName,string lastName, Email email, Phone phone,
            WorkingHoursEnum workingHours = WorkingHoursEnum.Normal, bool preventUpdate=false, DateTime? firedAt = null, DateTime? updatedDate=null,
            DivisionId? divisionId=null,PostId? postId=null, EmployeeNumber? employeeNumber=null, DateTime? dateOfBirth=null) :
            base(userDataId ?? UserDataId.CreateUnique())
        {
            PreventUpdate = preventUpdate;
            FiredAt = firedAt;
            FirstName = firstName;
            MiddleName = middleName;
            LastName = lastName;
            Email = email;
            Phone = phone;
            WorkingHours = workingHours;
            DivisionId = divisionId;
            PostId = postId;
            EmployeeNumber = employeeNumber;
            DateOfBirth = dateOfBirth;
            UpdatedDate = updatedDate;


        }
      
        public string FirstName { get;private set; }
        public string? MiddleName { get; private set; }
        public string LastName { get; private set; }

        public bool PreventUpdate { get; private set; }
        public DateTime? FiredAt { get; private set; }
        public DateTime? UpdatedDate { get; private set; }

        public Email Email { get; private set; }
        public Phone Phone { get; private set; }

      
        public DivisionId? DivisionId { get; private set; } = null;

        public PostId? PostId { get; private set; } = null;

        public EmployeeNumber? EmployeeNumber { get; private set; } = null;

        public DateTime? DateOfBirth { get; private set; } = null;
        public WorkingHoursEnum WorkingHours { get; set; } = WorkingHoursEnum.Normal;
     

        public static UserData Create(
            string firstName, string middleName, string lastName, Email email, Phone phone,
            WorkingHoursEnum workingHours=WorkingHoursEnum.Normal, bool preventUpdate=false, DateTime? firedAt=null, DateTime? updatedDate = null,
            DivisionId? divisionId = null, PostId? postId = null, EmployeeNumber? employeeNumber = null, 
            DateTime? dateOfBirth = null)
        {
            return new(UserDataId.CreateUnique(),  firstName, middleName, lastName,
                email, phone, workingHours, preventUpdate, firedAt, updatedDate, divisionId, postId, employeeNumber, dateOfBirth);
        }


    }

 
```
Also there is AggregateRoot (let's  omit description, we just need to know about is - it's contains User)
### User with entity - UserData
``` csharp
 public class User : AggregateRoot<UserId>
    {

        private User() : base(UserId.CreateUnique())
        {



        }

        public string UserName { get; private set; } = "";
        public string Password { get; private set; } = "";

        public DateTime CreatedDate { get; private set; }
        public DateTime? UpdatedDate { get; private set; }
        public DateTime? BlockedAt { get; private set; } = null;

        private readonly List<UserData> _userData = new();
        public IReadOnlyList<UserData> UserData => _userData.OrderByDescending(m => m.Id.SnapShotDate).ToList().AsReadOnly();
        public UserData? CurrentActualData => UserData.FirstOrDefault();

        private User(UserId userId, string userName, string password, List<UserData> userData, DateTime createdDate,
            DateTime? updatedDate = null, DateTime? blockedAt = null) : base(userId ?? UserId.CreateUnique())
        {
            UserName = userName;
            Password = password;
            BlockedAt = blockedAt;
            CreatedDate = createdDate;
            UpdatedDate = updatedDate;
            _userData = new List<UserData>(userData);
        }
        public static User Create(string userName, string password, List<UserData> userData, DateTime createdDate, DateTime? updatedDate = null, DateTime? blockedAt = null)
        {
            return new(UserId.CreateUnique(), userName, password, userData, createdDate, updatedDate, blockedAt);
        }
    }
```
Then was created extension methods for entity core configuration:

### Extensions 
``` csharp
  public static class ConfigurationsExtensions
    {
        public static string CreateForeignKey<T>(string Prefix="Id")
            where T:class
        {
            return $"{typeof(T).Name}{Prefix}";
        }
//When AggregateRoot contains Entity, that contains ValueObject as TemporalKey
        public static void OwnsOneAggregateToEntityKey<T, Y, TId, YId>(OwnedNavigationBuilder<T, Y> builder)
          where T : AggregateRoot<TId>
          where Y : Entity<YId>
          where TId : OrdinaryValueObject
          where YId : TemporalValueObject
        {
            
            builder.OwnsOne(x => x.Id, ownedBuilder => {
                ownedBuilder.Property(m => m.Value).HasColumnName("Id_Value");
                ownedBuilder.Property(m => m.SnapShotDate).HasColumnName("Id_SnapShotDate");
            });
            builder.Property(typeof(Guid), "Id_value").HasColumnName("Id_Value");
            builder.Property(typeof(DateTime), "Id_SnapShotDate").HasColumnName("Id_SnapShotDate");
            builder.HasKey("Id_value", "Id_SnapShotDate");
        }
//When AggregateRoot contains Entity, that contains ValueObject as default key (Guid value)
        public static void OwnsOneAggregateToValueObjectKey<T, TId>(EntityTypeBuilder<T> builder)
         where T : AggregateRoot<TId>
         where TId : OrdinaryValueObject

        {
            builder.OwnsOne(x => x.Id, ownedBuilder => {
                ownedBuilder.Property(x => x.Value).HasColumnName("Id_Value");
            });
            builder.Property(typeof(Guid), "Id_Value").HasColumnName("Id_Value");
            builder.HasKey("Id_Value");
        } 
    }
```
And then when use configuration:
``` csharpcsharp
  public class UserConfiguration : IEntityTypeConfiguration<User>
    {
        public void Configure(EntityTypeBuilder<User> builder)
        {
            ConfigureUserTable(builder);
            ConfigurationUserDataTable(builder);
        }

       
        private void ConfigurationUserDataTable(EntityTypeBuilder<User> builder)
        {
            builder.OwnsMany(m => m.UserData, ud =>
            {
              
                ud.ToTable("UserData"); 
        //extension methods used
                ud.WithOwner().HasForeignKey(ConfigurationsExtensions.CreateForeignKey<User>()); 
                ConfigurationsExtensions.OwnsOneAggregateToEntityKey<User,UserData, UserId, UserDataId>(ud);


                ud.Property(m => m.FirstName).HasMaxLength(255);
                ud.Property(m => m.MiddleName).HasMaxLength(255);
                ud.Property(m => m.LastName).HasMaxLength(255);

                ud.OwnsOne(m => m.Email);
                ud.OwnsOne(m => m.Phone);  
                ud.OwnsOne(m => m.EmployeeNumber);

            });
            builder.Metadata.FindNavigation(nameof(User.UserData))!.SetPropertyAccessMode(PropertyAccessMode.Field);
        }
        private void ConfigureUserTable(EntityTypeBuilder<User> builder)
        {
            builder.ToTable("Users"); 
 //extension methods used
            ConfigurationsExtensions.OwnsOneAggregateToValueObjectKey<User,UserId>(builder); 
            builder.Property(m => m.UserName).HasMaxLength(255);
            builder.Property(m => m.Password).HasMaxLength(50);
            builder.Ignore(m => m.CurrentActualData); 
        }
    }
```
But I think that created extension methods not clear, too many arguments for template methods OwnsOneAggregateToEntityKey. Maybe there is exists more clear way to implement generate PrimaryKey when we get key with two properties (like TemporalValueObject) ?

**Comment by savaladaojr** [comment]
awesome thank you so mucj @windofny1.
