### ISSUE TITLE
Building SQLite provider from source

### ISSUE THREAD

**Issue by kimimaru4000** [dotnet/efcore#23330]
I'm building EF Core from source to test a fix in my application. However, I cannot get EF Core's SQLite provider to load when applying migrations with DbContext.Migrate(). The NuGet package release has no issues, and none of my own code has changed at all.

I'm including the following projects into my own code:

- EFCore.Sqlite.Core
- EFCore.Design.csproj
- EFCore.Proxies.csproj

Exception:
```
System.Exception: You need to call SQLitePCL.raw.SetProvider().  If you are using a bundle package, this is done by calling SQLitePCL.Batteries.Init().
   at SQLitePCL.raw.get_Provider()
   at SQLitePCL.raw.sqlite3_open_v2(utf8z filename, sqlite3& db, Int32 flags, utf8z vfs)
   at Microsoft.Data.Sqlite.SqliteConnection.Open() in Microsoft.Data.Sqlite.Core/SqliteConnection.cs:line 240
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected) in EFCore.Relational/Storage/RelationalConnection.cs:line 662
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected) in EFCore.Relational/Storage/RelationalConnection.cs:line 641
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected) in EFCore.Relational/Storage/RelationalConnection.cs:line 557
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Exists() in EFCore.Sqlite.Core/Storage/Internal/SqliteDatabaseCreator.cs:line 92
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists() in EFCore.Relational/Migrations/HistoryRepository.cs:line 134
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration) in EFCore.Relational/Migrations/Internal/Migrator.cs:line 112
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade) in EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs:line 40
```

Here is how I'm configuring it:
```
protected override void OnConfiguring(DbContextOptionsBuilder options)
{
    options.UseLazyLoadingProxies().UseSqlite($"Filename={Datasource}", ContextBuilder);
    base.OnConfiguring(options);
}

private void ContextBuilder(SqliteDbContextOptionsBuilder optionsBuilder)
{
    optionsBuilder.MigrationsAssembly(System.Reflection.Assembly.GetExecutingAssembly().FullName);
}
```
Building EFCore.Sqlite does not produce a DLL and it complains about this when I include the project into my application. The output is only a "EFCore.Sqlite.deps.json" file, and I don't see any code in the EFCore.Sqlite project after cloning.

When I build, I get `dotnet_install: Warning: Unable to locate zlib. Probable prerequisite missing; install zlib`, but I'm not sure if this is related. I have several zlib packages installed (zlib1g, zlib1g-dev, zlib1g:i386, and zlibc) so I'm not sure what it's looking for here.

### Include provider and version information

EF Core version: [Issue23180](https://github.com/dotnet/efcore/tree/Issue23180) - sometime after 5.0.0-rc.2.20475.6
Database provider: System.Data.SQLite
Target framework: .NET Core 3.1
Operating system: Linux Mint 20 Ulyana
IDE: CLI

**Comment by tdeeb** [comment]
@ajcvickers @bricelam Any updates on this information?

**Comment by bricelam** [comment]
In addition to referencing EFCore.Sqlite.Core.csproj, you also need to install a SQLitePCLRaw bundle:

```xml
<ItemGroup>
  <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.0.4" />
</ItemGroup>
```

**Comment by tdeeb** [comment]
Worked like a charm; thank you!
