### ISSUE TITLE
Tests in parallel break, sequential works, how?

### ISSUE THREAD

**Issue by andrejohansson** [dotnet/efcore#23351]
## Ask a question

I am trying to create some manual classes to seed my database upon start. There is nothing fancy what I can see. I have an interface  ``IDatabaseSeed`` with a method ``Seed``. 

Then I create a number of seed classes:

- UserSeed
- LanguageSeed
- TranslationSeed
- etc

And finally I run them in order from my Xunit datbase fixture. This fixture is implemented in the same way as: https://docs.microsoft.com/en-us/ef/core/testing/sharing-databases#the-fixture

Seeding works well if tests are run one by one, but if I execute my tests in parallel, I get instance cannot be tracked errors. 

I dont understand why...I've even tried to get related entities directly from the ChangeTracker.Entities but still I get collisions!

## SharedDatabaseFixture - Should prevent double initialization?
```C#
namespace BokaMera.Api.IntegrationTest.Fixtures
{
    using System;
    using System.Data.Common;
    using System.IO;
    using System.Threading;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.Extensions.Logging;
    using Model.DbContext;
    using Model.Seed;
    using Seed;
    using Xunit.Abstractions;
    using Xunit.Sdk;

    // From: https://docs.microsoft.com/en-us/ef/core/testing/sharing-databases
    public class SharedDatabaseFixture : IDisposable
    {
        private static readonly object @lock = new object();
        private static bool databaseInitialized;

        public SharedDatabaseFixture()
        {
            var tempDatabasePath = Path.Combine(Path.GetTempPath(), "bokamera_integrationtest.sqlite");
            this.Connection = new SqliteConnection($"Data Source={tempDatabasePath};Foreign Keys=false");
            this.Seed();
            this.Connection.Open();
        }

        public DbConnection Connection { get; }

        protected BokaMeraContext CreateContext(DbTransaction transaction = null, bool enableQueryFilters = true,
            ILoggerFactory loggerFactory = null)
        {
            var optionsBuilder = new DbContextOptionsBuilder<BokaMeraContext>()
                .UseLoggerFactory(loggerFactory)
                // Log parameters etc
                .EnableSensitiveDataLogging()
                .UseLazyLoadingProxies()
                .UseSqlite(this.Connection, x => x.MigrationsAssembly("BokaMera.Api.Host"));

            var logger = loggerFactory?.CreateLogger<SharedDatabaseFixture>();
            var context = new BokaMeraContext(optionsBuilder.Options, enableQueryFilters, logger);

            if (transaction != null)
            {
                context.Database.UseTransaction(transaction);
            }

            return context;
        }

        private void Seed()
        {
            lock (@lock) // Shouldnt this prevent double seeding?
            {
                if (!databaseInitialized)
                {
                    using (var context = this.CreateContext())
                    {
                        context.Database.EnsureDeleted();
                        context.Database.Migrate();

                        var seeder = new BokaMeraTestSeeder(context, null);
                        seeder.Seed();

                        context.SaveChanges();
                    }

                    databaseInitialized = true;
                }
            }
        }

        protected virtual void Dispose(bool disposing)
        {
            if (disposing)
            {
                this.Connection?.Dispose();

                // Do NOT delete the db here!
                // See https://docs.microsoft.com/en-us/ef/core/testing/sharing-databases
            }
        }

        public void Dispose()
        {
            this.Dispose(true);
            GC.SuppressFinalize(this);
        }
    }
}
```

### Sample Seed file
```C#
public class PaymentTermsSeed : DatabaseSeed<PaymentTerm>
    {
        public PaymentTermsSeed(BokaMeraContext db) : base(db)
        {
        }

       // Only seed if we have no data in the table yet
        public bool DataExists() => this.Set
            .IgnoreQueryFilters()
            .AsNoTracking()
            .Any();

        protected override IEnumerable<PaymentTerm> EntitiesToSeed { get; } = new[]
        {
            new PaymentTerm
            {
                Id = UnattachedDataConstants.PaymentTerm15DaysId,
                OwnerId = UnattachedDataConstants.SystemDefaultBookingSupplierId,
                PenaltyInterest = 0.15M,
                PenaltyFee = 50M,
                Period = TimeSpan.FromDays(15),
                Created = UnattachedDataConstants.CreationDate,
                Updated = UnattachedDataConstants.CreationDate
            },
            new PaymentTerm
            {
                Id = UnattachedDataConstants.PaymentTerm30DaysId,
                OwnerId = UnattachedDataConstants.SystemDefaultBookingSupplierId,
                PenaltyInterest = 0.15M,
                PenaltyFee = 50M,
                Period = TimeSpan.FromDays(30),
                Created = UnattachedDataConstants.CreationDate,
                Updated = UnattachedDataConstants.CreationDate
            }
        };

    }
```

### Include verbose output

```
One or more errors occurred. (The instance of entity type 'MessageTemplate' cannot be tracked because another instance with the key value '{Id: 1fd94821-3c3e-4bf9-b95e-4ade12dd219a}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.) (The following constructor parameters did not have matching fixture data: SharedDatabaseFixture databaseFixture)
  Exception doesn't have a stacktrace
```

### Result

When running tests sequentially, or when parallel-within-the-same-classfixture tests run, all is fine!
![image](https://user-images.githubusercontent.com/2828428/99317070-b47f9480-2865-11eb-8aa5-4a10961c6f6c.png)

When letting everything run in parallell, everything breaks down and the changetracker gets really confused:

![image](https://user-images.githubusercontent.com/2828428/99317151-d8db7100-2865-11eb-96eb-d6273d77ffa1.png)

### Include provider and version information

EF Core version: 3.1.8
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: netcoreapp3.1
Operating system: Windows 10
IDE:  JetBrains Rider

**Comment by ajcvickers** [comment]
@andrejohansson Can you post the full stack trace?

**Comment by andrejohansson** [comment]
I tried to recreate our structure as much as possible and have attached a repro project here. In this repro, it doesn´t even work to run sequentually and I can´t understand why its complaining about duplicate entries. But I do strongly suspect the lazy loading proxies and my (mis)use of things is the culprit.

[issue-23351-andrejohansson.zip](https://github.com/dotnet/efcore/files/5570401/issue-23351-andrejohansson.zip)

```csharp
Issue.Xunit.Efcore.Parallel.Tests.ClassFixtureTests1.CanCreatePostsInParallel.CanCreatePostsInParallel(index: 10)

System.InvalidOperationException: The instance of entity type 'Blog' cannot be tracked because another instance with the same key value for {'Id'} is ...

System.InvalidOperationException
The instance of entity type 'Blog' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.Attach[TEntity](TEntity entity)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Attach(TEntity entity)
   at Issue.Xunit.Efcore.Parallel.Tests.ClassFixtureTests1.CanCreatePostsInParallel(Int32 index) in D:\lab\src\xunit-efcore-parallel\Tests\ClassFixtureTests1.cs:line 48



ManagedThreadId: 13
```

**Comment by ajcvickers** [comment]
@andrejohansson The code is attempting to re-use the same static `Person` instance. For example, here:

```C#
var post = new Post
{
    Id = Guid.NewGuid(),
    Blog = blog,
    Title = $"Post {index}",
    Content = "Dummy",
    Owner = PersonEntitySeed.DefaultPerson // <-- Here
};
```

This static instance is configured to be related to Blog instances during seeding, and then these instances end up being attached in every test, leading to duplicates.

**Comment by andrejohansson** [comment]
@ajcvickers I see, thank you, works for me now!

**Comment by Thullner** [comment]
I've run into the same problem. What would be the best way to stop the code from reusing the same static instance?

**Comment by Thullner** [comment]
@andrejohansson @ajcvickers I've run into the same problem. What would be the best way to stop the code from reusing the same static instance?

**Comment by ajcvickers** [comment]
@Thullner By not using a static instance in the first place.
