### ISSUE TITLE
Many-to-Many with bespoke CLR causes recursion/object cycle exception

### ISSUE THREAD

**Issue by JLunda** [dotnet/efcore#23372]
I am working with EF Core 5, trying to get a many-to-many relationship working with the newest methodology, following the documentation [here](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#many-to-many) and [here](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew#many-to-many), but every time I try to implement load the related entity, it enters a recursion loop and throws and exception because it detects an object cycle.

I have gone through the code multiple times, trying variations where I do not include the join List on the Offering or Technology objects, or in the `WithMany()` method in the DbContext.

For my purposes, Offerings can have many Technologies, and a single Technology can be used across many Offerings. Here's the code.

## Offering Class

```
public class Offering
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public ICollection<Technology> Technologies { get; set; }
        
        //Sometimes included, sometimes not, depending on what I use in the WithMany() method of the DbContext.
        public List<OfferingTechnology> OfferingTechnologies { get; set; }
    }
}
```

## Technology Class
```
    public class Technology
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public ICollection<Offering> Offerings { get; set; }

        //Sometimes included, sometimes not, depending on what I use in the WithMany() method of the DbContext.
        public List<OfferingTechnology> OfferingTechnologies { get; set; }
    }
```

## OfferingTechnology Class
```
    public class OfferingTechnology
    {
        //sometimes included, sometimes not, depending on what HasKey I use in the DbContext.
        //public int Id { get; set; }
        public int OfferingId { get; set; }
        public Offering Offering { get; set; }
        public int TechnologyId { get; set; }
        public Technology Technology { get; set; }
    }
```

## DbContext OnModelCreating
```
protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema("Atlas");

            modelBuilder.Entity<Offering>()
            .HasMany(o => o.Technologies)
            .WithMany(t => t.Offerings)
            .UsingEntity<OfferingTechnology>(
                ot => ot.HasOne(ot => ot.Technology)
                    .WithMany(t => t.OfferingTechnologies)
                    .HasForeignKey(ot => ot.TechnologyId),
                ot => ot.HasOne(ot => ot.Offering)
                    .WithMany(o => o.OfferingTechnologies)
                    .HasForeignKey(ot => ot.OfferingId),
                ot =>
                {
                    ot.HasKey(ot => new { ot.OfferingId, ot.TechnologyId });
                    ot.HasData(new List<OfferingTechnology> {
                        new OfferingTechnology {
                            OfferingId = 1,
                            TechnologyId = 1
                        },
                        new OfferingTechnology {
                            OfferingId = 1,
                            TechnologyId = 2
                        }
                    });
                    ot.ToTable("OfferingTechnologies");
                })
            .HasData(new List<Offering> {
                new Offering{
                    Id = 1,
                    Name = "Offering 1"
                }
            });

            modelBuilder.Entity<Technology>().HasData(new List<Technology> {
                new Technology {
                    Id = 1,
                    Name = ".NET Core"
                },
                new Technology {
                    Id = 2,
                    Name = "C#"
                },
                new Technology {
                    Id = 3,
                    Name = "Angular"
                }
            });

            base.OnModelCreating(modelBuilder);
        }
```

## Call to Offerings list from OfferingsController.cs
```
        // GET: Offerings
        [HttpGet]
        public IEnumerable<Offering> GetOfferings()
        {
            return _context.Offerings.Include(o => o.OfferingTechnologies).ToList();
        }
```

From debugging, I can tell that the problem is caused when I try to get a list of the Technologies that are related to a particular Offering. When populating the Offerings object, EF Core attempts to populate the Technologies collection, and since each Technology itself has an Offerings collection, this causes an infinite, recursive loop. I have followed the documentation as exactly as I know how, but EF Core seems to ignore my explicit configuration. In the meantime, I can obviously use the old mappings as a workaround, but I thought I should bring this potential bug to your attention. And if it's not a bug, maybe someone can show me where I'm going wrong.

Thanks,
Jordan

### Include stack traces

Include the full exception message and stack trace for any exception you encounter.

Use triple-tick fences for stack traces. For example:

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.Text.Json.JsonException: A possible object cycle was detected which is not supported. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 32.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializerCycleDetected(Int32 maxDepth)
   at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteAsyncCore(Stream utf8Json, Object value, Type inputType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
```

### Include provider and version information

EF Core version: 5.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer 5.0.0
Target framework: netcoreapp3.1 or net5.0 (with launch.json changed to reflect proper path)
Operating system: Windows 10 x64 10.0.18363
IDE: VS Code 1.50.1

**Comment by AndriySvyryd** [comment]
@JLunda Cycles in the relationship is expected. Note that the exception comes from Mvc, not EF.
Try configuring the serializer to ignore cycles:

```C#
services.AddMvc()
         .AddJsonOptions(
             options => options.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
         ); 
```

**Comment by JLunda** [comment]
Thank you for the solution. Of course, I see now that I shouldn't be passing the data model through the API controller anyway. I should be using a view model to perform proper code architecture.
