### ISSUE TITLE
Projection fails with "Argument types do not match" error when entity has owned type property

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/efcore#23397]
When
- InheritedEntity is inherited from BaseEntity
- InheritedEntity has owned type property
- InheritedEntity has bool property `IsActive`

The following query fails with "Argument types do not match" error.
```csharp
            var testResults = await context.Entities
                .Select(e => new
                {
                    IsActive = e is InheritedEntity ? ((InheritedEntity)e).IsActive : false
                })
                .ToListAsync();
```

Same query works perfectly fine with EF 3.1. It also works fine if there is no owned type property.
See attached repro project.

<details>
<summary>Stack trace</summary>

```
   at System.Linq.Expressions.Expression.Condition(Expression test, Expression ifTrue, Expression ifFalse, Type type)
   at System.Linq.Expressions.ConditionalExpression.Update(Expression test, Expression ifTrue, Expression ifFalse)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitConditional(ConditionalExpression conditionalExpression)
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitNew(NewExpression newExpression)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__65`1.MoveNext()
```

</details>

[EfRepro.zip](https://github.com/dotnet/efcore/files/5566540/EfRepro.zip)

**Comment by Dreamescaper** [comment]
Error seems to be similar to https://github.com/dotnet/efcore/issues/22758, but I'm not sure whether it is same issue.

**Comment by smitpatel** [comment]
Could be fixed in https://github.com/dotnet/efcore/issues/23309

**Comment by ajcvickers** [comment]
@smitpatel Output from 6.0 daily build. (Haven't been able to get a 5.0.1 daily.)

```
/home/ajcvickers/.dotnet/dotnet /home/ajcvickers/AllTogetherNow/Daily/bin/Debug/net5.0/Daily.dll
{ IsActive = False },{ IsActive = False },{ IsActive = True },{ IsActive = False }
```

**Comment by Dreamescaper** [comment]
As far as I understand, issue that fixed issue was specifically about client evaluation, right?
But why would client evaluation happen here at all?
(Probably caused by owned entity, but still why?)

**Comment by smitpatel** [comment]
e is Type pattern is getting nav expansion to add include around e for eager loaded navigations which eventually not used.
