### ISSUE TITLE
NRE when trying to configure parameter on TVF in the ToFunction call during model configuration

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#23406]
function:

```cs
            public IQueryable<Post> PostsTaggedWith(string tag)
                => FromExpression(() => PostsTaggedWith(tag));
```

model builder call:

```cs
                modelBuilder.Entity<Post>().ToFunction("PostsTaggedWith", b => b.HasParameter("tag"));
```

exception:

```
   at Microsoft.EntityFrameworkCore.Internal.MethodInfoExtensions.DisplayName(MethodInfo methodInfo) in D:\git\efcore\src\EFCore.Relational\Extensions\Internal\MethodInfoExtensions.cs:line 25
   at Microsoft.EntityFrameworkCore.Metadata.Builders.Internal.InternalDbFunctionBuilder.HasParameter(String name, ConfigurationSource configurationSource) in D:\git\efcore\src\EFCore.Relational\Metadata\Internal\InternalDbFunctionBuilder.cs:line 244
   at Microsoft.EntityFrameworkCore.Metadata.Builders.DbFunctionBuilderBase.HasParameter(String name) in D:\git\efcore\src\EFCore.Relational\Metadata\Builders\DbFunctionBuilderBase.cs:line 97
   at Microsoft.EntityFrameworkCore.Query.QueryBugsTest.BloggingContext.<>c.<OnModelCreating>b__16_8(TableValuedFunctionBuilder b) in D:\git\efcore\test\EFCore.SqlServer.FunctionalTests\Query\QueryBugsTest.cs:line 9540
   at Microsoft.EntityFrameworkCore.RelationalEntityTypeBuilderExtensions.ToFunction(EntityTypeBuilder entityTypeBuilder, String name, Action`1 configureFunction) in D:\git\efcore\src\EFCore.Relational\Extensions\RelationalEntityTypeBuilderExtensions.cs:line 752
   at Microsoft.EntityFrameworkCore.RelationalEntityTypeBuilderExtensions.ToFunction[TEntity](EntityTypeBuilder`1 entityTypeBuilder, String name, Action`1 configureFunction) in D:\git\efcore\src\EFCore.Relational\Extensions\RelationalEntityTypeBuilderExtensions.cs:line 783
   at Microsoft.EntityFrameworkCore.Query.QueryBugsTest.BloggingContext.OnModelCreating(ModelBuilder modelBuilder) in D:\git\efcore\test\EFCore.SqlServer.FunctionalTests\Query\QueryBugsTest.cs:line 9540
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context) in D:\git\efcore\src\EFCore\Infrastructure\ModelCustomizer.cs:line 56
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies) in D:\git\efcore\src\EFCore\Infrastructure\ModelSource.cs:line 145
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies) in D:\git\efcore\src\EFCore\Infrastructure\ModelSource.cs:line 100
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel() in D:\git\efcore\src\EFCore\Internal\DbContextServices.cs:line 85
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model() in D:\git\efcore\src\EFCore\Internal\DbContextServices.cs:line 112
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p) in D:\git\efcore\src\EFCore\Infrastructure\EntityFrameworkServicesBuilder.cs:line 256
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies() in D:\git\efcore\src\EFCore\DbContext.cs:line 394
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider() in D:\git\efcore\src\EFCore\DbContext.cs:line 376
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance() in D:\git\efcore\src\EFCore\DbContext.cs:line 1787
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor) in D:\git\efcore\src\EFCore\Infrastructure\Internal\InfrastructureExtensions.cs:line 33
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor) in D:\git\efcore\src\EFCore\Infrastructure\AccessorExtensions.cs:line 46
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_Dependencies() in D:\git\efcore\src\EFCore\Infrastructure\DatabaseFacade.cs:line 40
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureDeleted() in D:\git\efcore\src\EFCore\Infrastructure\DatabaseFacade.cs:line 143
```

**Comment by maumar** [comment]
note: 

```cs
modelBuilder.HasDbFunction(typeof(BloggingContext).GetMethod(nameof(PostsTaggedWith), new[] { typeof(string) }));
```

works fine

**Comment by smitpatel** [comment]
Fixed in https://github.com/dotnet/efcore/commit/e45256e6166c548c7db6c54e3e8996b33996659a
We could improve exception further by coalescing with function name or pointing out that we don't know method info on it.
