### ISSUE TITLE
modelBuilder.HasDbFunction on queryable function (of entities) overrides implicit ToTable for that entity

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#23408]
When trying to map tvf using `modelBuilder.HasDbFunction`, we strip the (by convention) `ToTable` call.
It makes sense if you use 
`modelBuilder.Entity<Foo>().ToFunction(...)`. but is a bit unintuitive when using
modelBuilder.HasDbFunction. *especially* when the function has some arguments (which would indicate it's just a helper of some sort)

exception:

```
'The entity type 'Post' is not mapped to a table, therefore the entities cannot be persisted to the database. Call 'ToTable' in 'OnModelCreating' to map it to a table.'

   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.CreateModificationCommands(IList`1 entries, IUpdateAdapter updateAdapter, Func`1 generateParameterName) in D:\git\efcore\src\EFCore.Relational\Update\Internal\CommandBatchPreparer.cs:line 226
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.<BatchCommands>d__10.MoveNext() in D:\git\efcore\src\EFCore.Relational\Update\Internal\CommandBatchPreparer.cs:line 77
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.<GetDataOperations>d__76.MoveNext() in D:\git\efcore\src\EFCore.Relational\Migrations\Internal\MigrationsModelDiffer.cs:line 2174
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.<GetDataOperations>d__75.MoveNext() in D:\git\efcore\src\EFCore.Relational\Migrations\Internal\MigrationsModelDiffer.cs:line 2144
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext) in D:\git\efcore\src\EFCore.Relational\Migrations\Internal\MigrationsModelDiffer.cs:line 199
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IRelationalModel source, IRelationalModel target) in D:\git\efcore\src\EFCore.Relational\Migrations\Internal\MigrationsModelDiffer.cs:line 164
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.GetCreateTablesCommands(MigrationsSqlGenerationOptions options) in D:\git\efcore\src\EFCore.Relational\Storage\RelationalDatabaseCreator.cs:line 144
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.CreateTables() in D:\git\efcore\src\EFCore.Relational\Storage\RelationalDatabaseCreator.cs:line 123
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated() in D:\git\efcore\src\EFCore.Relational\Storage\RelationalDatabaseCreator.cs:line 236
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated() in D:\git\efcore\src\EFCore\Infrastructure\DatabaseFacade.cs:line 80
```

**Comment by ajcvickers** [comment]
Note from triage: consider when to map to table automatically, or not, based on how the TVF and return type is used elsewhere.

**Comment by n0099** [comment]
The caution addressed in [ef core document](https://docs.microsoft.com/en-us/ef/core/querying/user-defined-function-mapping#mapping-a-queryable-function-to-a-table-valued-function) is still linking to this issue, should it be update with mentions to changes in ef core 6.0?
