### ISSUE TITLE
Is it safe to ignore ForeignKeyPropertiesMappedToUnrelatedTables?

### ISSUE THREAD

**Issue by andrejohansson** [dotnet/efcore#23462]
## Ask a question

I am trying to use the table-per-type hierarchy that came with efcore 5 I got a warning that I don´t really understand if it´s safe to ignore (see stacktrace below). 

```
The foreign key {'OwnerId'} on the entity type 'PaymentMethodCard' targeting 'BookingSupplier' cannot be represented 
in the database. Either the properties {'OwnerId'} aren't mapped to table 'PaymentMethodCard' or the principal 
properties {'Id'} aren't mapped to table 'BookingSupplier'. All foreign key properties must map to the table that the 
dependent type is mapped to and all principal properties must map to a single table that the principal type is mapped 
to. This exception can be suppressed or logged by passing event ID 
'RelationalEventId.ForeignKeyPropertiesMappedToUnrelatedTables' to the 'ConfigureWarnings' method in 
'DbContext.OnConfiguring' or 'AddDbContext'.
```

Given the sample hierarchy below, with a reference to an owner in the base, I get warnings that the descendants foreign keys cannot be represented in the database. But when I check, It seems to me that the generated tables in the database gets all their relations generated just fine?

### Code

Sample entity hierarchy 

```C#

[Table(nameof(MyBase))]
public abstract class MyBase 
{
  public virtual Company Owner { get; set;)
}

[Table(nameof(MyInheritedA))]
public class MyInheritedA : MyBase
{
}

[Table(nameof(MyInheritedB))]
public class MyInheritedB: MyBase
{
}

```

While I can ignore it with the following code:

```csharp
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            => optionsBuilder
                .ConfigureWarnings(wa => wa.Ignore(RelationalEventId.ForeignKeyPropertiesMappedToUnrelatedTables));
```

I do not quite understand the implications, can someone please clarify them for me, can I safely ignore this warning?

### Include stack traces

```
System.InvalidOperationException
An error was generated for warning 'Microsoft.EntityFrameworkCore.Model.Validation.ForeignKeyPropertiesMappedToUnrelatedTables': The foreign key {'OwnerId'} on the entity type 'PaymentMethodCard' targeting 'BookingSupplier' cannot be represented in the database. Either the properties {'OwnerId'} aren't mapped to table 'PaymentMethodCard' or the principal properties {'Id'} aren't mapped to table 'BookingSupplier'. All foreign key properties must map to the table that the dependent type is mapped to and all principal properties must map to a single table that the principal type is mapped to. This exception can be suppressed or logged by passing event ID 'RelationalEventId.ForeignKeyPropertiesMappedToUnrelatedTables' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
   at Microsoft.EntityFrameworkCore.Diagnostics.FallbackEventDefinition.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, Action`1 logAction)
   at Microsoft.EntityFrameworkCore.Diagnostics.RelationalLoggerExtensions.ForeignKeyPropertiesMappedToUnrelatedTables(IDiagnosticsLogger`1 diagnostics, IForeignKey foreignKey)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedForeignKeysCompatibility(IReadOnlyList`1 mappedTypes, StoreObjectIdentifier& storeObject, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedTableCompatibility(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Sqlite.Internal.SqliteModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.ValidatingConvention.ProcessModelFinalized(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelFinalized(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelFinalized(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FinalizeModel()
```

### Include provider and version information

EF Core version: 5.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10 Pro
IDE: Rider 2020.4 EAP 8

**Comment by AndriySvyryd** [comment]
As long as you are ok with the generated database then it's ok to ignore. In this situation EF isn't sure that the generated constraints are enough. And this would only be a problem if you insert data without using EF.

**Comment by rezasparrow** [comment]
@andrejohansson do you find any solution for your problem?
I have the same issue in ef 7

**Comment by andrejohansson** [comment]
@rezasparrow Not anything more than ignoring as per @AndriySvyryd ´s comment since we were happy with the resulting db and we are only inserting using efcore.
