### ISSUE TITLE
Cannot delete an entity with one-to-many and one-to-one relations of same type when one-to-one relation is loaded

### ISSUE THREAD

**Issue by DumpsterDoofus** [dotnet/efcore#23460]
## How to reproduce

A [minimal working example using SQL Server is here](https://github.com/DumpsterDoofus/EfCoreDelete).

Given an entity (`Parent`) with both a one-to-many and one-to-one relation with another entity (`Child`), deleting the principal entity (`Parent`) fails if the one-to-one relation has been loaded, but succeeds if the one-to-one relation has not been loaded.

Here's the models:

```C#
public class Parent : Entity
{
    public List<Child> Children { get; set; } = null!;

    public Child SpecialChild { get; set; } = null!;
    public int SpecialChildId { get; set; }
}

public class Child : Entity
{
    public Parent? Parent { get; set; }
}

public class Entity
{
    [Key]
    public int Id { get; set; }
}
```

This deletion works fine (ie, deletes the parent and its children):

```C#
var parent = dbContext.Parents
    .Single(p => p.Id == parentId);
dbContext.Remove(parent);
dbContext.SaveChanges();
```

This throws an exception:

```C#
var parent = dbContext.Parents
    .Include(p => p.SpecialChild)
    .Single(p => p.Id == parentId);
dbContext.Remove(parent);
dbContext.SaveChanges();
```

The only difference is `.Include(p => p.SpecialChild)`.

Stack trace:

```
System.InvalidOperationException: Unable to save changes because a circular dependency was detected in the data to be saved: 'Parent [Deleted] SpecialChild { 'SpecialChildId' } <-
Child [Deleted] Parent Children { 'ParentId' } <-
Parent [Deleted]To show additional information call 'DbContextOptionsBuilder.EnableSensitiveDataLogging'.'.
   at Microsoft.EntityFrameworkCore.Utilities.Multigraph`2.ThrowCycle(List`1 cycle, Func`2 formatCycle)
   at Microsoft.EntityFrameworkCore.Utilities.Multigraph`2.BatchingTopologicalSort(Func`2 formatCycle)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.TopologicalSort(IEnumerable`1 commands)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.BatchCommands(IList`1 entries, IUpdateAdapter updateAdapter)+MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at EfCoreDeleteBug.Program.SadPathThatThrows() in C:\Users\source\repos\EfCoreDeleteBug\EfCoreDeleteBug\Program.cs:line 43
   at EfCoreDeleteBug.Program.Main() in C:\Users\source\repos\EfCoreDeleteBug\EfCoreDeleteBug\Program.cs:line 13
```

## Why this seems like a bug

The only difference between the two examples is a load of related data with `.Include(p => p.SpecialChild)`. This is a read operation. It's surprising that a read operation would affect the outcome of a subsequent write operation (the delete of the parent).

In my use case, `SpecialChild` must be loaded prior to the delete, but this causes the delete to fail.

## Workaround attempts

Haven't found a workaround yet. Based on [a similar issue](https://github.com/dotnet/efcore/issues/22391#issuecomment-691730451) I tried setting `ChangeTracker.CascadeDeleteTiming = CascadeTiming.OnSaveChanges` and `ChangeTracker.DeleteOrphansTiming = CascadeTiming.OnSaveChanges`, but neither had any effect.

Is there a way to explicitly unload data from the change tracker? Maybe that could fix it?

### Provider and version information

EF Core version: 5.0.0 (minimal working example link uses this), 3.1.9, possibly older versions too
Database provider: `Microsoft.EntityFrameworkCore.SqlServer`
Target framework: `netcoreapp3.1`
Operating system: Windows
IDE: Visual Studio 2019 16.7.5

**Comment by ajcvickers** [comment]
Note for triage: this is a circular dependency that the database gets around by cascading the delete.

State manager for case that succeeds:

```
Parent {Id: 1} Deleted
  Id: 1 PK
  SpecialChildId: 1 FK
  Children: <null>
  SpecialChild: <null>
```

State manager for case that fails:

```
Child {Id: 3} Deleted
  Id: 3 PK
  ParentId: 2 FK
  Parent: {Id: 2}
Parent {Id: 2} Deleted
  Id: 2 PK
  SpecialChildId: 3 FK
  Children: [{Id: 3}]
  SpecialChild: {Id: 3}
```

```
Model: 
  EntityType: Child
    Properties: 
      Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd
      ParentId (no field, Nullable<int>) Shadow FK Index
    Navigations: 
      Parent (Parent) ToPrincipal Parent Inverse: Children
    Keys: 
      Id PK
    Foreign keys: 
      Child {'ParentId'} -> Parent {'Id'} ToDependent: Children ToPrincipal: Parent Cascade
    Indexes: 
      ParentId 
  EntityType: Parent
    Properties: 
      Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd
      SpecialChildId (int) Required FK Index
    Navigations: 
      Children (List<Child>) Collection ToDependent Child Inverse: Parent
      SpecialChild (Child) ToPrincipal Child
    Keys: 
      Id PK
    Foreign keys: 
      Parent {'SpecialChildId'} -> Child {'Id'} Unique ToPrincipal: SpecialChild
    Indexes: 
      SpecialChildId  Unique
```

**Comment by ajcvickers** [comment]
Notes from triage: for optional relationships, this is covered by #1699. However, we currently don't have any plans to support this for required relationships where it is not possible to first update the FK to null. Doing so would require disabling or delaying constraint checking, which is a very database-specific behavior.
