### ISSUE TITLE
TPH where derived entities each have Required Owned Entities with Required / Non-Nullable Properties throws SqlException

### ISSUE THREAD

**Issue by tgandersen** [dotnet/efcore#23479]
EF Core version: 5.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.8.0

I'm not able to find any information on a particular scenario I ran into while working through enabling Nullable Reference Types in my EF Core 5.0 project / making certain props of Owned Entities Required / Non-Nullable.  I suspect it's just a case of "you can't do that" but wanted to confirm 100% that's what's going on.

See below for a boiled-down working example of my actual use-case, but a summary would be that I have a TPH scenario where there are Contact and Account types derived from a BaseBusinessEntity.  Each sub-type has an Owned Entity "MailingAddress" property that I want to make required / not nullable, as well as make all the mailing address parts (street address, city, state, etc.) required / not nullable.  These MailingAddress properties are not named the same (i.e., property names are Contact.HomeAddress and Account.CompanyAddress).  

Under this scenario, EF Core ends up creating the SQL table with NOT NULL columns for both HomeAddress and CompanyAddress properties, which I suppose makes sense.  However, this leads to an impossible situation in that you can't create a Contact because the "CompanyAddress" fields will always be null, and a similar situation for creating an Account where "HomeAddress" will always be null.

Below is a demo of this scenario.  I can see running into similar TPH-related cases where you might want non-nullable props for one sub-type or another.  Am I missing something that would allow this scenario to work, or is it just not supported?

**Note that Nullable is enabled for this .csproj!**
```C#
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace TphWithRequiredOwnedEntities
{
    class Program
    {
        // Nullable is enabled for this project!
        static void Main(string[] args)
        {
            var sc = new ServiceCollection();
            sc.AddDbContext<MyDbContext>(opts => opts.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=TphWithRequiredOwnedEntities;Trusted_Connection=True;ConnectRetryCount=0"));
            using (var sp = sc.BuildServiceProvider())
            using (var context = sp.GetRequiredService<MyDbContext>())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                Contact contact = new Contact("John Doe", new MailingAddress("1234 Main St", "Smallville", 
                    "KS", "12345", "USA"));
                context.Contacts.Add(contact);
                context.SaveChanges();
                // SqlException: Cannot insert the value NULL into column 'CompanyAddress_StreetAddress', table 
                // 'TphWithRequiredOwnedEntities.dbo.BaseBusinessEntities'; column does not allow nulls. INSERT fails.
                // 
                // Workarounds:
                //   - Rename Contact.HomeAddress and Account.CompanyAddress to the same name such as 
                //     "Address".  Then EF Core will use the same fields for both Contact and Account.  Not a great 
                //     solution since it compromises the domain model language, though.
                //   - Make MailingAddress properties nullable and just ensure model enforces this domain requirement.  
                //     Not a great solution, either, but if there's no other way...
            }
        }
    }


    public class MyDbContext : DbContext
    {
        public MyDbContext(DbContextOptions opts) : base(opts) { }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Contact>()
                .OwnsOne(c => c.HomeAddress)
                .WithOwner();
            modelBuilder.Entity<Account>()
                .OwnsOne(c => c.CompanyAddress)
                .WithOwner();
        }

        public DbSet<BaseBusinessEntity> BaseBusinessEntities { get; set; } = null!;
        public DbSet<Contact> Contacts { get; set; } = null!;
        public DbSet<Account> Accounts { get; set; } = null!;
    }


    public class BaseBusinessEntity
    {
        public Guid Id { get; set; }
        // Other common props here...
    }

    public class Contact : BaseBusinessEntity
    {
        public Contact(string fullName, MailingAddress homeAddress)
        {
            Id = Guid.NewGuid();
            FullName = fullName;
            HomeAddress = homeAddress;
        }

#pragma warning disable CS8618
        private Contact() { }
#pragma warning restore CS8618


        public string FullName { get; set; }

        // Mailing address is required
        public MailingAddress HomeAddress { get; set; }
    }


    public class Account : BaseBusinessEntity
    {
        public Account(string companyName, MailingAddress companyAddress)
        {
            Id = Guid.NewGuid();
            CompanyName = companyName;
            CompanyAddress = companyAddress;
        }

#pragma warning disable CS8618
        private Account() { }
#pragma warning restore CS8618

        public string CompanyName { get; set; }
        public MailingAddress CompanyAddress { get; set; }
    }

    public class MailingAddress
    {
        public MailingAddress(string streetAddress, string city, string state, string zip, string country)
        {
            StreetAddress = streetAddress;
            City = city;
            State = state;
            Zip = zip;
            Country = country;
        }

        private MailingAddress() { }

        public string StreetAddress { get; set; } = "";
        public string City { get; set; } = "";
        public string State { get; set; } = "";
        public string Zip { get; set; } = "";
        public string Country { get; set; } = "";
    }
}
```

Stack Trace:
```
Cannot insert the value NULL into column 'CompanyAddress_StreetAddress', table 'TphWithRequiredOwnedEntities.dbo.BaseBusinessEntities'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
```

**Comment by smitpatel** [comment]
The columns for owned type owned by a derived type in TPH should be nullable regardless of nullability. My guess is nullable enable is causing an issue here.

**Comment by tgandersen** [comment]
Thanks for the quick reply @smitpatel.

So it sounds like I might need to define these Owned Entity props as nullable (i.e., `public string? StreetAddress { get; set; }`, etc.) and then enforce the "not null" requirement in my own business logic (my real-world project already does this), as EF Core won't be able to enforce it in this particular case (where database columns cannot be null for Owned Entity properties that are part of a derived type in TPH)?

Or will an update / fix on EF Core eventually let me keep the "not-nullable" declaration for these properties, but perhaps with the caveat that it cannot be enforced at the database level?

**Comment by smitpatel** [comment]
You don't need to define them as nullable. It should be working. Probably combination of owned type + derived type + NRT is throwing something off. If you disable NRT, then does it generate expected schema?

**Comment by tgandersen** [comment]
Only disabling NRT in the *.csproj in the example code (no other changes) generates a schema will nullable columns for the corresponding MailingAddress Owned Entity properties, which I think is what you are expecting, correct?

I'd like to try test changing the MyDbContext's ModelBuilder to mark the Owned Entity HomeAddress / CompanyAddress props with IsRequired() and / or the individual properties under MailingAddress with IsRequired() as well (with NRT disabled), but am out of time to do so before the long Thanksgiving weekend, so I'll have to pick this up on Monday most likely.

**Comment by smitpatel** [comment]
Yes, I was expecting NRT is doing something odd to cause errors, it could be bug in EF Core related to NRT also. Mainly what you want is valid scenario, non-nullable properties in C# classes but columns are nullable in database.

> am out of time to do so before the long Thanksgiving weekend, so I'll have to pick this up on Monday most likely.

Same! 😄
