### ISSUE TITLE
Scaffolding w/ C#9's new Program file

### ISSUE THREAD

**Issue by glenn2223** [dotnet/efcore#23471]
## Bug

Scaffolding doesn't work with C#9's simplified `Program.cs` file layout. Reverting to the previous code doesn't result in the exception.

As you can see in the verbose output it states  
`No static method 'CreateHostBuilder(string[])' was found on class 'Program'.`

### Code

In the terminal:
```console
dotnet ef dbcontext scaffold name=SiteDataConnection  Microsoft.EntityFrameworkCore.SqlServer -t Product --no-build
```

Program.cs
```C#
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;

CreateWebHostBuilder(args).Build().Run();

static IHostBuilder CreateWebHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStartup<Startup>();
        });
```

### Stack trace from the console

```
System.InvalidOperationException: A named connection string was used, but the name 'SiteDataConnection' was not found in the application's configuration. Note that named connection strings are only supported when using 'IConfiguration' and a service provider, such as in a typical ASP.NET Core application. See https://go.microsoft.com/fwlink/?linkid=850912 for more information.
   at Microsoft.EntityFrameworkCore.Storage.Internal.NamedConnectionStringResolverBase.ResolveConnectionString(String connectionString)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluarlize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
A named connection string was used, but the name 'SiteDataConnection' was not found in the application's configuration. Note that named connection strings are only supported when using 'IConfiguration' and a service provider, such as in a typical ASP.NET Core application. See https://go.microsoft.com/fwlink/?linkid=850912 for more information.
```

### Verbose output

```
Using project 'D:\Sites\MySiteInDotNet\MySiteInDotNet.csproj'.
Using startup project 'D:\Sites\MySiteInDotNet\MySiteInDotNet.csproj'.
Writing 'D:\Sites\MySiteInDotNet\obj\MySiteInDotNet.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\graphite.rack\AppData\Local\Temp\3\tmp7512.tmp /verbosity:quiet /nologo D:\Sites\MySiteInDotNet\MySiteInDotNet.csproj
Writing 'D:\Sites\MySiteInDotNet\obj\MySiteInDotNet.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\graphite.rack\AppData\Local\Temp\3\tmp788E.tmp /verbosity:quiet /nologo D:\Sites\MySiteInDotNet\MySiteInDotNet.csproj
dotnet exec --depsfile D:\Sites\MySiteInDotNet\bin\Debug\net5.0\MySiteInDotNet.deps.json --additionalprobingpath C:\Users\graphite.rack\.nuget\packages --additionalprobingpath C:\Microsoft\Xamarin\NuGet --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig D:\Sites\MySiteInDotNet\bin\Debug\net5.0\MySiteInDotNet.runtimeconfig.json C:\Users\graphite.rack\.dotnet\tools\.store\dotnet-ef\5.0.0-rc.2.20475.6\dotnet-ef\5.0.0-rc.2.20475.6\tools\netcoreapp3.1\any\tools\netcoreapp2.0\any\ef.dll dbcontext scaffold name=SiteDataConnection Microsoft.EntityFrameworkCore.SqlServer -t Products --assembly D:\Sites\MySiteInDotNet\bin\Debug\net5.0\MySiteInDotNet.dll --startup-assembly D:\Sites\MySiteInDotNet\bin\Debug\net5.0\MySiteInDotNet.dll --project-dir D:\Sites\MySiteInDotNet\ --language C# --working-dir D:\Sites\MySiteInDotNet --verbose --root-namespace MySiteInDotNet
Using assembly 'MySiteInDotNet'.
Using startup assembly 'MySiteInDotNet'.
Using application base 'D:\Sites\MySiteInDotNet\bin\Debug\net5.0'.
Using working directory 'D:\Sites\MySiteInDotNet'.
Using root namespace 'MySiteInDotNet'.
Using project directory 'D:\Sites\MySiteInDotNet\'.
Remaining arguments: .
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding design-time services referenced by assembly 'MySiteInDotNet'...
Finding design-time services referenced by assembly 'MySiteInDotNet'...
No referenced design-time services were found.
Finding IDesignTimeServices implementations in assembly 'MySiteInDotNet'...
No design-time services were found.
Finding application service provider in assembly 'MySiteInDotNet'...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
System.InvalidOperationException: A named connection string was used, but the name 'SiteDataConnection' was not found in the application's configuration. Note that named connection strings are only supported when using 'IConfiguration' and a service provider, such as in a typical ASP.NET Core application. See https://go.microsoft.com/fwlink/?linkid=850912 for more information.
   at Microsoft.EntityFrameworkCore.Storage.Internal.NamedConnectionStringResolverBase.ResolveConnectionString(String connectionString)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluarlize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
A named connection string was used, but the name 'SiteDataConnection' was not found in the application's configuration. Note that named connection strings are only supported when using 'IConfiguration' and a service provider, such as in a typical ASP.NET Core application. See https://go.microsoft.com/fwlink/?linkid=850912 for more information.
```

### Include provider and version information

EF Core version: 5.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer)
Target framework: .NET 5.0
Operating system: Windows Server 2016
IDE: VS Code

###Packages

```XML
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.0"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.0"/>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="5.0.0"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.0"/>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="5.0.0"/>
```

**Comment by ajcvickers** [comment]
@glenn2223 Please vote for this issue: https://github.com/dotnet/aspnetcore/issues/27923
