### ISSUE TITLE
Async queries not releasing pooled connections

### ISSUE THREAD

**Issue by mikary** [dotnet/efcore#2347]
``` cs
for (var index = 0; index<int.MaxValue; index++)
{
    using (var context = new NorthwindQuerySqlServerFixture().CreateContext())
    {
        var result = await context.Set<Customer>().ToArrayAsync();
    }
}
```

After 100 iterations of the preceding code, an `AggregateException` with an inner `System.InvalidOperationException` is thrown.

```
Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.

   at System.Data.Common.ADP.ExceptionWithStackTrace(Exception e)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Data.Entity.Relational.RelationalConnection.<OpenAsync>d__29.MoveNext() in C:\src\aspnet\EntityFramework\src\EntityFramework.Relational\RelationalConnection.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Data.Entity.Relational.Query.AsyncQueryingEnumerable.AsyncEnumerator.<MoveNext>d__5.MoveNext() in C:\src\aspnet\EntityFramework\src\EntityFramework.Relational\Query\AsyncQueryingEnumerable.cs:line 66
```

**Comment by divega** [comment]
Curious, is it possible to repro this without EF?

**Comment by mikary** [comment]
It appears to repro in the synchronous case as well as async.

**Comment by mikary** [comment]
Made a mistake in the test case, ```NorthwindQuerySqlServerFixture``` is not being disposed, does not repro when the fixture is disposed.

**Comment by divega** [comment]
Phew!
