### ISSUE TITLE
Multiple attempts to add SelectExpression for a single query source

### ISSUE THREAD

**Issue by mikary** [dotnet/efcore#2348]
The following query results in an exception being thrown by a `Dictionary` in the `RelationalQueryModelVisitor` which maps `QuerySource` instances to `SelectExpression` instances. (`System.ArgumentException` "An item with the same key has already been added.")

``` cs
var result = await context.Set<Customer>()
    .Where(c => context.Set<Order>().AnyAsync(CancellationToken.None).Result)
    .ToArrayAsync();
```

**Comment by divega** [comment]
@mikary do you think this could be related to https://github.com/Reactive-Extensions/Rx.NET/issues/106?

**Comment by mikary** [comment]
I don't believe so, this error was happening in query compilation, before Ix-Async would even be involved.

**Comment by anpete** [comment]
Yep, this is happening in compilation.

**Comment by divega** [comment]
Thanks!

**Comment by rowanmiller** [comment]
Note this is only when you try to use AnyAsync in the second query. We also now throw a different exception.

```c#
using Microsoft.Data.Entity;
using System;
using System.Linq;
using System.Threading;

namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var context = new BloggingContext())
            {
                context.Blogs.Add(new Blog { Url = "aaa" });
                context.Blogs.Add(new Blog { Url = "bbb" });
                context.SaveChanges();
            }

            using (var context = new BloggingContext())
            {
                var query = context.Set<Blog>()
                        .Where(c => context.Set<Blog>().AnyAsync(CancellationToken.None).Result)
                        .ToArrayAsync();

                foreach (var item in query.Result)
                {
                    Console.WriteLine(item.Url);
                }
            }
        }
    }

    public class BloggingContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=Blogging;Trusted_Connection=True;");
        }

    }

    public class Blog
    {
        public int Id { get; set; }
        public string Url { get; set; }
    }
}
```

```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: querySource
   at Microsoft.Data.Entity.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.AddQuery(IQuerySource querySource, SelectExpression selectExpression)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitEntityQueryable(Type elementType)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.EntityQueryableExpressionVisitor.VisitConstant(ConstantExpression constantExpression)
   at System.Linq.Expressions.ConstantExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMember(MemberExpression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitMember(MemberExpression node)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression node)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitWhereClause(WhereClause whereClause, QueryModel queryModel, Int32 index)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitWhereClause(WhereClause whereClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.Clauses.WhereClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.Internal.SqlServerQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.Storage.Database.CompileAsyncQuery[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass20_0`1.<CompileAsyncQuery>b__0()
   at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddAsyncQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.CompileAsyncQuery[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression)
   at Microsoft.Data.Entity.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
   at System.Linq.AsyncEnumerable.Aggregate[TSource,TAccumulate,TResult](IAsyncEnumerable`1 source, TAccumulate seed, Func`3 accumulator, Func`2 resultSelector, CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.ToArray[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.Data.Entity.EntityFrameworkQueryableExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\rowmil\Documents\Visual Studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\Program.cs:line 21
```

If you change the query to non-async, then everything works.

```c#
var query = context.Set<Blog>()
        .Where(c => context.Set<Blog>().Any())
        .ToArrayAsync();
```

**Comment by rowanmiller** [comment]
Clearing for re-triage as I'm not sure this is worth fixing

**Comment by rowanmiller** [comment]
Triage: Agreed, this is a negative case and not worth spending time on
