### ISSUE TITLE
Read the DataReader result set, the same column gets different types

### ISSUE THREAD

**Issue by netnr** [dotnet/efcore#23490]
Read the DataReader result set, the same column gets different types

```C#
var ds = new DataSet();
var reader = cmd.ExecuteReader();
table.Load(reader); // ERROR
```

```sql
PRAGMA table_info('SysUser');PRAGMA table_info('SysRole')

-- When the default value of the field is set, the return type of "dflt_value" column is different
```

```
<PackageReference Include="Microsoft.Data.Sqlite.Core" Version="5.0.0" />
ERROR, returns different types

<PackageReference Include="System.Data.SQLite.Core" Version="1.0.113.6" />
OK
```

### stack traces
```
System.ArgumentException: Type of value has a mismatch with column typeCouldn't store <0> in dflt_value Column.  Expected type is Byte[].
 ---> System.ArgumentException: Type of value has a mismatch with column type
   at System.Data.Common.ObjectStorage.Set(Int32 recordNo, Object value)
   at System.Data.DataColumn.set_Item(Int32 record, Object value)
   --- End of inner exception stack trace ---
   at System.Data.DataColumn.set_Item(Int32 record, Object value)
   at System.Data.DataTable.NewRecordFromArray(Object[] value)
   at System.Data.DataTable.LoadRow(Object[] values, LoadOption loadOption, Index searchIndex)
   at System.Data.DataTable.LoadDataRow(Object[] values, LoadOption loadOption)
   at System.Data.ProviderBase.SchemaMapping.LoadDataRow()
   at System.Data.Common.DataAdapter.FillLoadDataRow(SchemaMapping mapping)
   at System.Data.Common.DataAdapter.FillFromReader(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 startRecord, Int32 maxRecords, DataColumn parentChapterColumn, Object parentChapterValue)
   at System.Data.Common.DataAdapter.Fill(DataTable[] dataTables, IDataReader dataReader, Int32 startRecord, Int32 maxRecords)
   at System.Data.DataTable.Load(IDataReader reader, LoadOption loadOption, FillErrorEventHandler errorHandler)
   at System.Data.DataTable.Load(IDataReader reader)
```

![image](https://user-images.githubusercontent.com/10579621/100325260-55f3ac80-3003-11eb-907b-ff15ff399d28.png)

[Demo DR.zip](https://github.com/dotnet/efcore/files/5601375/DR.zip)

**Comment by bricelam** [comment]
There's a lot going on here, so I'll start by saying that this is probably the query you're looking for:

```sql
SELECT 'SysUser' AS "table", * FROM pragma_table_info('SysUser')
UNION
SELECT 'SysRole', * FROM pragma_table_info('SysRole')
```

(Technical details:)

I'm actually surprised that DataAdapter tries to put both result sets into the same DataTable, throwing and encouraging the use of UNION instead would probably have been a better design.

The column type is different in each result set because SQLite's [dynamic type system](https://sqlite.org/datatype3.html) doesn't always play well with ADO.NET's DataSet APIs. Microsoft.Data.Sqlite tries to determine the column type based on 1) the actual values in the column and, when there is no data 2) the column type name as defined on by the table, and finally 3) if falls back to byte[].

In the case when there are no default value constraints on a table, all the values for the dflt_value column are NULL and it tries to look at the column type name instead. But unfortunately, `PRAGMA table_info` doesn't specify type names (you can observe this by executing `PRAGMA table_info('pragma_table_info')`) so it falls back to `byte[]`.

In the case when there are default value constraints, it can see that there is an INTEGER value in the column so it uses that.

**Comment by netnr** [comment]
> 
> ```sql
> SELECT 'SysUser' AS "table", * FROM pragma_table_info('SysUser')
> UNION
> SELECT 'SysRole' AS "table", * FROM pragma_table_info('SysRole')
> ```

System.Data.SQLite.Core OK

Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table column: pragma_table_info.cid'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.GetSchemaTable()
   at System.Data.ProviderBase.SchemaMapping..ctor(DataAdapter adapter, DataSet dataset, DataTable datatable, DataReaderContainer dataReader, Boolean keyInfo, SchemaType schemaType, String sourceTableName, Boolean gettingData, DataColumn parentChapterColumn, Object parentChapterValue)
   at System.Data.Common.DataAdapter.FillMappingInternal(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 schemaCount, DataColumn parentChapterColumn, Object parentChapterValue)
   at System.Data.Common.DataAdapter.FillMapping(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 schemaCount, DataColumn parentChapterColumn, Object parentChapterValue)
   at System.Data.Common.DataAdapter.FillFromReader(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 startRecord, Int32 maxRecords, DataColumn parentChapterColumn, Object parentChapterValue)
   at System.Data.Common.DataAdapter.Fill(DataTable[] dataTables, IDataReader dataReader, Int32 startRecord, Int32 maxRecords)
   at System.Data.DataTable.Load(IDataReader reader, LoadOption loadOption, FillErrorEventHandler errorHandler)
   at DR.Program.QueryForMicrosoftSqliteDataReader() in C:\Users\Administrator\source\repos\DR\DR\Program.cs:line 121

**Comment by bricelam** [comment]
Now you’re hitting https://github.com/dotnet/efcore/issues/21239 🤦‍♂️

**Comment by netnr** [comment]
The current solution is to manually set the table column type to object

```
public static DataSet ExecuteDataSet(this DbCommand dbCommand)
{
    var ds = new DataSet();
    var reader = dbCommand.ExecuteReader();

    var isSQLite = dbCommand.Connection.GetType().FullName.ToLower().Contains("sqlite");
    // https://github.com/dotnet/efcore/issues/23490
    if (isSQLite)
    {
        do
        {
            var table = new DataTable
            {
                TableName = "table" + (ds.Tables.Count + 1).ToString()
            };

            var readerSt = reader.GetSchemaTable();
            var ctype = typeof(object);
            for (int i = 0; i < readerSt.Rows.Count; i++)
            {
                table.Columns.Add(new DataColumn(readerSt.Rows[i]["ColumnName"].ToString(), ctype));
            }

            while (reader.Read())
            {
                var dr = table.NewRow();
                for (int i = 0; i < reader.FieldCount; i++)
                {
                    dr[i] = reader.GetValue(i);
                }
                table.Rows.Add(dr.ItemArray);
            }
            ds.Tables.Add(table);

        } while (reader.NextResult());
    }
    else
    {
        do
        {
            var table = new DataTable
            {
                TableName = "table" + (ds.Tables.Count + 1).ToString()
            };
            table.Load(reader);
            ds.Tables.Add(table);
        } while (!reader.IsClosed);
    }

    return ds;
}
```

**Comment by bricelam** [comment]
Re-opening this. `dflt_value` is truly a variant column.

Our current SqliteDataReader.GetSchemaTable() logic picks the most used type. Even with the UNION, if the column contains, multiple types, DataTable.Load will still fail.

We should look into using `object` as the column type when multiple types are found.

**Comment by bricelam** [comment]
I take it back. `dflt_value` is a TEXT column. There should be no problems with the UNION.
