### ISSUE TITLE
EfCore 5 update breaks behaviour of RowVersion with Conversions for InMemory database

### ISSUE THREAD

**Issue by dg-marbl** [dotnet/efcore#23527]
## Problem

There seems to be a new issue when upgrading from EfCore 3.x to 5.0 and using an Entity that contains a Property that uses a ValueConverter as well as a RowVersion. This issue affects the InMemory database provider.

### Example

The following Code works in EfCore 3.1.10 but not in EfCore 5.0: [full example](https://github.com/dg-marbl/efcorebug/blob/master/EfCoreBug/Program.cs)

```C#
var serviceCollection = new ServiceCollection();
serviceCollection.AddDbContext<TestDbContext>(builder => CreateInMemoryDbContextOptions(builder));

var serviceProvider = serviceCollection.BuildServiceProvider();
var context = serviceProvider.GetRequiredService<TestDbContext>();
            
var dbModel = new DbModel{Value = "Test"};
context.Add(dbModel);
context.SaveChanges();

var model = context.Set<DbModel>().Single();
model.Value += "2";
context.SaveChanges();
            
var models = context.Set<DbModel>().ToImmutableList();
Console.WriteLine($"Value is {model.Value}");
```

where the model is

```C#
    public class DbModel
    {
        public long Id { get; set; }

        public ulong RowVersion { get; set; }
        
        public string Value { get; set; }
    }
    
    public class DbModelEntityTypeConfiguration : IEntityTypeConfiguration<DbModel>
    {
        public void Configure(EntityTypeBuilder<DbModel> builder)
        {
            builder.ToTable(name: nameof(DbModel), schema: "test");
            builder.Property(po => po.RowVersion).HasConversion(new NumberToBytesConverter<ulong>()).IsRowVersion();
        }
    }
```

### Stacktrace

```
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'System.Byte[]' to type 'System.UInt64'.
   at Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer`1.Equals(Object left, Object right)
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryTable`1.IsConcurrencyConflict(IUpdateEntry entry, IProperty property, Object rowValue, Dictionary`2 concurrencyConflicts)
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryTable`1.Update(IUpdateEntry entry)
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryStore.ExecuteTransaction(IList`1 entries, IDiagnosticsLogger`1 updateLogger)
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()

```

### Provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.InMemory 5.0.0 (works with 3.1.10)
Target framework: NET 5.0
Operating system: Windows 10

**Comment by ajcvickers** [comment]
Note for triage: the optimistic concurrency code in the in-memory provider assumes no value conversion. This was not an issue before 5.0 because value conversions were ignored in the in-memory database.
