### ISSUE TITLE
Error building entity model with inheritance and covariant properties when using generic builder helper classes

### ISSUE THREAD

**Issue by nkAlex** [dotnet/efcore#23596]
Consider we have the following Entity model with inheritance and C#9's covariant return property types as IDs:

```C#
public abstract class Identifier
{
    private readonly Guid _value;

    protected Identifier(Guid value)
    {
        _value = value;
    }
}

public class EntityId : Identifier
{
    public EntityId(Guid value) : base(value)
    {
    }
}

public abstract class EntityBase
{
    public virtual Identifier Id { get; }

    public EntityBase(Identifier id)
    {
        Id = id;
    }
}

public abstract class DerivedEntityBase<T> : EntityBase where T : EntityBase
{
    public HashSet<T>? Collection { get; set; }

    protected DerivedEntityBase(Identifier id) : base(id)
    {
    }
}

public class FirstEntity : EntityBase
{
    public override EntityId Id { get; }

    public FirstEntity(EntityId id) : base(id)
    {
        Id = id;
    }
}

public class SecondEntity : DerivedEntityBase<FirstEntity>
{
    public override EntityId Id { get; }

    public SecondEntity(EntityId id) : base(id)
    {
        Id = id;
    }
}
```

And we use the following Configuration to build EF Core model:
```C#
public class FirstEntityConfiguration : IEntityTypeConfiguration<FirstEntity>
{
    public void Configure(EntityTypeBuilder<FirstEntity> builder)
    {
        builder.ToTable("FirstEntities");

        builder.Property(p => p.Id);

        builder.HasKey(k => k.Id);
    }
}

public class SecondEntityConfiguration : IEntityTypeConfiguration<SecondEntity>
{
    public void Configure(EntityTypeBuilder<SecondEntity> builder)
    {
        builder.ToTable("SecondEntities");

        builder.Property(p => p.Id);

        builder.HasMany(p => p.Collection)
               .WithOne()
               .HasForeignKey(k => k.Id);

        builder.HasKey(k => k.Id);
    }
}
```
This works fine. However, if we try using a more generic approach, like this:
```C#
public class FirstEntityConfiguration : IEntityTypeConfiguration<FirstEntity>
{
    public void Configure(EntityTypeBuilder<FirstEntity> builder)
    {
        builder.ToTable("FirstEntities");
        builder.ConfigureFirst();
    }
}

public class SecondEntityConfiguration : IEntityTypeConfiguration<SecondEntity>
{
    public void Configure(EntityTypeBuilder<SecondEntity> builder)
    {
        builder.ToTable("SecondEntities");
        builder.ConfigureSecond<SecondEntity, FirstEntity>();
    }
}

public static class Helpers
{
    public static void ConfigureFirst<T>(this EntityTypeBuilder<T> builder)
        where T : EntityBase
    {
        builder.Property(p => p.Id);

        builder.HasKey(k => k.Id);
    }

    public static void ConfigureSecond<T0, T1>(this EntityTypeBuilder<T0> builder)
        where T0 : DerivedEntityBase<T1>
        where T1 : EntityBase
    {
        builder.Property(p => p.Id);

        builder.HasMany(p => p.Collection)
               .WithOne()
               .HasForeignKey(k => k.Id);

        builder.HasKey(k => k.Id);
    }
}
```
— it will throw an exception:
```
System.InvalidOperationException: No suitable constructor was found for entity type 'FirstEntity'. The following constructors had parameters that could not be bound to properties of the entity type: cannot bind 'id' in 'FirstEntity(EntityId id)'.
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.ConstructorBindingConvention.ProcessModelFinalizing(IConventionModelBuilder modelBuilder, IConventionContext`1 context)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelFinalizing(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelFinalizing(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FinalizeModel()
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
No suitable constructor was found for entity type 'FirstEntity'. The following constructors had parameters that could not be bound to properties of the entity type: cannot bind 'id' in 'FirstEntity(EntityId id)'.
```
However, the model will build fine if we remove all covariant properties (i.e. replace all `Identifier` with `EntityId`) or move all builder operations involving keys (`builder.HasKey(...)`, `builder.HasMany(...)`) back to the `Configuration` classes. `builder.Property(...)` may still stay in the `Helper` class and it will build fine.

My wild guess will be that model builder won't traverse up the inheritance tree for property overrides when called from generic methods like that. Not really sure if this is a bug, by design, or a limitation in either EF Core or .NET itself.

**Comment by ajcvickers** [comment]
@nkAlex We looked at this and don't see anything obviously wrong. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by nkAlex** [comment]
Done :)
https://github.com/nkAlex/EFCoreCovariantPropertyIssue

**Comment by AndriySvyryd** [comment]
<details>
  <summary>Minimal repro</summary>
```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    ConfigureCovariantEntity(modelBuilder.Entity<CovariantEntity>());
}

public static void ConfigureCovariantEntity<T>(EntityTypeBuilder<T> builder)
    where T : CovariantEntityBase
{
    builder.Property(p => p.Id);
}

public class CovariantEntity : CovariantEntityBase
{
    public override EntityId Id { get; }

    public CovariantEntity(EntityId id) : base(id)
    {
        Id = id;
    }
}

public class CovariantEntityBase
{
    public virtual Identifier Id { get; }

    public CovariantEntityBase(Identifier id)
    {
        Id = id;
    }
}

public abstract class Identifier
{
    private readonly Guid _value;

    protected Identifier(Guid value)
    {
        _value = value;
    }

    public static implicit operator Guid(Identifier identifier)
    {
        return identifier._value;
    }
}

public class EntityId : Identifier
{
    public EntityId(Guid value) : base(value)
    {
    }
}
```
</details>

The main issue is that when configuring `Id` on `CovariantEntity` through `CovariantEntityBase` EF ends up using `CovariantEntityBase.Id`, even though `CovariantEntityBase` is not mapped.

However if `CovariantEntityBase` were to be mapped this behavior would be by design as `Identifier` cannot be assigned to `EntityId`

**Comment by AndriySvyryd** [comment]
Related: https://github.com/dotnet/efcore/issues/22219
