### ISSUE TITLE
Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions'

### ISSUE THREAD

**Issue by akshayKhot** [dotnet/efcore#23716]
I am trying to access the databse using EF Core 5.0 on an ASP.NET Core project. For the first migration, I overrode the `OnConfiguring()` method on the DBContext and updated the database successfully. 

For the second migration, I decided to use the dependency injection in ASP.NET Core following the [guidelines](https://docs.microsoft.com/en-gb/ef/core/cli/dbcontext-creation?tabs=dotnet-core-cli#from-application-services). Here are the changes I made. 

1. Added `services.AddDbContext` in my `Startup.cs`. 
2. Removed the `OnConfiguring()` method from `DBContext`. 

After running `dotnet ef migrations add Posts`, I get following error: 

    Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create an object of type 'BlogContext'. 
    For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

If I add the --verbose flag, I get this output:

    Build started...
    dotnet build blog/app/app.csproj /verbosity:quiet /nologo
    
    Build succeeded.
        0 Warning(s)
        0 Error(s)
    
    Time Elapsed 00:00:02.50
    Build succeeded.
    dotnet exec --depsfile /Users/akshay/Dev/dotnet/blog/app/bin/Debug/net5.0/app.deps.json --additionalprobingpath /Users/akshay/.nuget/packages --runtimeconfig /Users/akshay/Dev/dotnet/blog/app/bin/Debug/net5.0/app.runtimeconfig.json /Users/akshay/.dotnet/tools/.store/dotnet-ef/5.0.1/dotnet-ef/5.0.1/tools/netcoreapp3.1/any/tools/netcoreapp2.0/any/ef.dll migrations add Page --assembly /Users/akshay/Dev/dotnet/blog/app/bin/Debug/net5.0/app.dll --startup-assembly /Users/akshay/Dev/dotnet/blog/app/bin/Debug/net5.0/app.dll --project-dir /Users/akshay/Dev/dotnet/blog/app/ --language C# --working-dir /Users/akshay/Dev/dotnet/blog/app --verbose --root-namespace app
    Using assembly 'app'.
    Using startup assembly 'app'.
    Using application base '/Users/akshay/Dev/dotnet/blog/app/bin/Debug/net5.0'.
    Using working directory '/Users/akshay/Dev/dotnet/blog/app'.
    Using root namespace 'app'.
    Using project directory '/Users/akshay/Dev/dotnet/blog/app/'.
    Remaining arguments: .
    Finding DbContext classes...
    Finding IDesignTimeDbContextFactory implementations...
    Finding application service provider in assembly 'app'...
    Finding Microsoft.Extensions.Hosting service provider...
    No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
    No application service provider was found.
    Finding DbContext classes in the project...
    Found DbContext 'BlogContext'.
    Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create an object of type 'BlogContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
     ---> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[app.Data.BlogContext]' while attempting to activate 'app.Data.BlogContext'.
       at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
       at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
       at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass13_4.<FindContextTypes>b__13()
       --- End of inner exception stack trace ---
       at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass13_4.<FindContextTypes>b__13()
       at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
       at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
       at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
       at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
       at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
       at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
       at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
    Unable to create an object of type 'BlogContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
     
However, the code works as expected when I run the web application, as in the `BlogContext` is created and injected into my classes by the DI layer, and I can access the database.

Hence, I am guessing the DI layer is not running as expected when running the `dotnet ef migrations add` command. 

Here's my code.

    // BlogContext

    using app.Models;
    using Microsoft.EntityFrameworkCore;

    namespace app.Data
    {
        public class BlogContext : DbContext
        {
            public DbSet<Post> Posts { get; set; }
    
            public DbSet<Comment> Comments { get; set; }
    
            public BlogContext(DbContextOptions<BlogContext> options) : base(options)
            {
    
            }
        }
    }

    // Startup.cs

    using Microsoft.EntityFrameworkCore;
    using Microsoft.Extensions.DependencyInjection;

    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
             Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        public string ConnectionString => Configuration.GetConnectionString("Blog");

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<BlogContext>(opt => { opt.UseSqlite(ConnectionString); });
        }
    }

    // Program.cs

    public class Program
    {
        public static void Main(string[] args)
        {
            IHostBuilder builder = Host.CreateDefaultBuilder(args)
                                            .UseSerilog()
                                            .ConfigureWebHostDefaults(webBuilder =>
                                            {
                                                webBuilder.UseStartup<Startup>();
                                            });

            IHost host = builder.Build();

            host.Run();
        }
    }

Both the `Startup` and `BlogContext` live in the same project. 

### Include provider and version information

- EF Core version: 5.0
- Database provider: Microsoft.EntityFrameworkCore.Sqlite --version 5.0.1
- Target framework: NET 5.0
- Operating system: Mac OSX
- IDE: VS Code

**Comment by akshayKhot** [comment]
Turned out I was not following the correct pattern in `Program.cs`

After modifying the `Program.cs` to following it works as expected. However, I don't understand why it would fail with my Program class. Isn't this the same code, just refactored differently? 

Any explanation is really appreciated. 

```
public class Program
{
    public static void Main(string[] args)
        => CreateHostBuilder(args).Build().Run();

    // EF Core uses this method at design time to access the DbContext
    public static IHostBuilder CreateHostBuilder(string[] args)
        => Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(
                webBuilder => webBuilder.UseStartup<Startup>());
}
```
