### ISSUE TITLE
How to remove a navigation property from an entity type?

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/efcore#23741]
I'm trying to remove from the model a navigation property that was implicitly added by EF Core.
However, there's no `RemoveNavigation` method on `IMutableEntityType`, and `RemoveProperty` doesn't accept a `IMutableNavigation`. How can I remove that navigation? It's preventing me from adding the property as a scalar property.

EF Core version: 5.0
Database provider: Not specific to any DB provider
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.8

**Comment by anranruye** [comment]
Look at https://docs.microsoft.com/en-us/ef/core/modeling/entity-properties?tabs=data-annotations%2Cwithout-nrt

Use [NotMapped] attribute or EntityTypeBuilder<TEntity>.Ignore()

Or Use IMutableTypeBase.AddIgnored() and configure the relationship explicitly

Notice that unidirectional many-to-many relationships is not supported in the current version. See #23735

**Comment by thomaslevesque** [comment]
@anranruye thanks, but I can't use `[NotMapped]` or `Ignore`, because that property should be mapped, just not as a navigation property. I also don't want to do it explicitly with `builder.Property(e => e.Id)`, because I have many entities and I'd like a way to do it for all entities.

Basically, I have something like this:

```
public record ProductId(int Value);

public class Product
{
    public ProductId Id { get; set; }
    ...
}
```

`ProductId` is conceptually a scalar value, but since it's not a built-in type, EF Core sees it as an entity, which it isn't. So I need to tell EF Core how to map it (using a converter), but when I enumerate the entities in the model and their properties, `Id` isn't returned, because it's seen as a navigation property. If I try to explicitly add `Id` as a property, I get an error because there's already a navigation property with the same name.

**Comment by anranruye** [comment]
@thomaslevesque  If you use [NotMapped] attribute, then you can explicitly add `Id` as a property.

```C#
modelBuilder.Model.GetEntityTypes().Where(x => x.GetIgnoredMembers().Contains("Id"))
                .ToList().ForEach(x =>
                {                    
                    x.AddProperty("Id").SetValueConverter(new ValueConverter<ProductId, int>(pid => pid.Value, id => new ProductId { Value = id }));
                    x.RemoveIgnored("Id");
                });
```

I found another problem with this model. When add a new product entity, ef core cannot track it.

```C#
db.Products.Add(new Product { Name = "NewProduct" + Guid.NewGuid() });
```
throws
```
System.InvalidOperationException: Unable to track an entity of type 'Product' because its primary key property 'Id' is null.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NullableKeyIdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Add(TEntity entity)
```

```C#
db.Products.Add(new Product { Id = new ProductId(), Name = "NewProduct" + Guid.NewGuid() });
db.SaveChanges();
```
throws
```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert explicit value for identity column in table 'Products' when IDENTITY_INSERT is set to OFF.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
ClientConnectionId:402983a6-5797-4518-9ad3-760d521b74da
Error Number:544,State:1,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
```

**Comment by anranruye** [comment]
I build another model without using value converter and I use owned entity.

```C#
    //entity types
    [Owned]
    public record ProductId
    {
        [Column("Id")]
        public int Value { get; set; }
    }

    public class Product
    {
        [Column("Id")]
        private int id;

        public ProductId Id { get; set; }

        public string Name { get; set; }
    }

    //model configuration
    modelBuilder.Model.GetEntityTypes()
                .Where(x => x.IsOwned() == false && x.GetKeys().Where(k => k.IsPrimaryKey()).FirstOrDefault() == null)
                .ToList().ForEach(x => x.AddProperty("id"));
```

I don't like this model, but it doesn't has problem with adding new entities.

**Comment by thomaslevesque** [comment]
@anranruye adding [NotMapped] seems to work fine for me, I'm not seeing the issue you mention. It's not ideal though, because my entities are defined in a separate assembly that doesn't reference EF Core, and I'd rather keep it that way. But it's better than nothing, I guess. Thanks for your suggestions!

**Comment by anranruye** [comment]
@thomaslevesque 
If [NotMapped] works, then you can just use it in the separate assembly without ef core. [NotMapped] is from data annotation library,  not ef core. 

I think there are some ways to remove navigations without using attribute,  but it seems that ef core hides them and only uses them inside.

**Comment by thomaslevesque** [comment]
Actually, I found a better solution. *Before* the call to `base.OnModelCreating`, I ignore the `ProductId` type and other similar types:

```csharp
foreach (var type in typeof(ProductId).Assembly.ExportedTypes)
{
    if (some_condition(type))
    {
        modelBuilder.Ignore(type);
    }
}
```

And *after* the call to `base.OnModelCreating`, I add the missing keys:

```csharp
foreach (var entityType in modelBuilder.Model.GetEntityTypes())
{
    var key = entityType.GetKeys().FirstOrDefault();
    if (key is null)
    {
        var idClrProp = entityType.ClrType.GetProperty("Id");
        if (idClrProp is not null)
        {
            var idProp = entityType.FindProperty(idClrProp) ?? entityType.AddProperty(idClrProp);
            entityType.SetPrimaryKey(idProp);
        }
    }
}
```

**Comment by thomaslevesque** [comment]
> [NotMapped] is from data annotation library, not ef core.

Good point!

**Comment by anranruye** [comment]
@thomaslevesque 
Does the place of base.OnModelCreating matters? In my memory, it seems that original DbContext.OnModelCreating method just does nothing(I haven't dig deep into the source code, just a feeling). At least ProductId type is not brought in by base.OnModelCreating, since ProductId entity type already exsists when you remove it from the model metadata. 

Can you tell me how do you add a new Product entity by ef core tracking system? As I mentioned above,  I can't do it with sql server database. 

Also have a look at #23700 if you prepare to use owned entity(complex type in ef core).

**Comment by thomaslevesque** [comment]
> Does the place of base.OnModelCreating matters? In my memory, it seems that original DbContext.OnModelCreating method just does nothing

Actually, you're right. I thought the initial model (based on conventions) was created in `base.OnModelCreating`, but in fact it must be done before that; the base implementation [is empty](https://github.com/dotnet/efcore/blob/68d54dd79a798ff85f91778897087aa85de00c0e/src/EFCore/DbContext.cs#L437).

> Can you tell me how do you add a new Product entity by ef core tracking system? As I mentioned above, I can't do it with sql server database.

I just do `dbContext.Products.Add(product)`. I tried it with SQLite, but I don't think the DB provider matters.

**Comment by anranruye** [comment]
@thomaslevesque 
Do you explicitly specify a primary key for the new product entity?

**Comment by ajcvickers** [comment]
@thomaslevesque When deciding how to interpret a CLR property while building the model, the CLR property is mapped as an EF property rather than a navigation if it refers to a type that can be mapped by the database provider. Specifically: 

* If the property has a value converter defined
* If the property type can be mapped natively by the database provider in use
* If the property type can be automatically converted to something that can be mapped by the provider in use

If none of these mappings are possible, and the type is a reference type, then the property is assumed to be a navigation.

So, if a property is mapped as a navigation instead of as a regular property, you need to make sure it fulfills one of the conditions above. Usually that means configuring a value converter. This will become easier once #10784 is implemented. For now, it will require explicitly specifying the value converter for every property of a given type.

**Comment by thomaslevesque** [comment]
@ajcvickers thanks, but there's a problem with that:

> - If the property has a value converter defined
> ...
> Usually that means configuring a value converter

The problem is that I don't have an opportunity to configure a converter before it's "too late". Well, that's not exactly true: I can do it with `modelBuilder.Entity<Product>(builder => builder.Property(p => p.Id).HasConversion(...))`, but then I have to do it explicitly for each property of each entity.

What I want is to do it dynamically, without knowing all the entities and properties in advance. But when I enumerate `entityType.GetProperties()`, `Id` is not returned, because it's a navigation property, so I can't add a conversion to it.

I guess that what I need is some kind of mechanism to customize the conventions used by EF Core to build the model. https://github.com/dotnet/efcore/issues/10784 will help, but something less specific would probably be quite useful as well.

**Comment by ajcvickers** [comment]
> Well, that's not exactly true: I can do it with modelBuilder.Entity<Product>(builder => builder.Property(p => p.Id).HasConversion(...)), but then I have to do it explicitly for each property of each entity.

Yes, this is what you need to do until #10784 is implemented.

> but something less specific would probably be quite useful as well.

Can you explain what you mean by this?

**Comment by smitpatel** [comment]
Something less specific would be to explore properties on actual CLR type of the entity type rather than using `GetProperties()` from EF Core since EF Core does not discover it as property. It is a property on C# class and should be detected that way if needed to be done dynamically.

**Comment by ajcvickers** [comment]
@smitpatel I considered suggesting that, but I think in practice it would be hard to implement without knowing the full list of entity types up front, since EF model discovery cannot be used to discover the correct graph of entity types if it doesn't know which types are entity types.

**Comment by thomaslevesque** [comment]
> > but something less specific would probably be quite useful as well.
> 
> Can you explain what you mean by this?

Sorry, I realize I wasn't very clear. I mean that allowing to set conversions for any property of a given type is nice, but a more general customization mechanism would be even better. Ideally, a simple way to customize model conventions.

**Comment by thomaslevesque** [comment]
> Something less specific would be to explore properties on actual CLR type of the entity type rather than using `GetProperties()` from EF Core since EF Core does not discover it as property. It is a property on C# class and should be detected that way if needed to be done dynamically.

Unfortunately that doesn't really help in my case. I can detect the `Id` CLR property, but I can't add it as a scalar property, because there's already a navigation property of the same name.

**Comment by smitpatel** [comment]
>  I can detect the Id CLR property, but I can't add it as a scalar property, because there's already a navigation property of the same name.

If you add it as a property using fluent API methods then it will automatically remove the navigation property.

**Comment by thomaslevesque** [comment]
> If you add it as a property using fluent API methods then it will automatically remove the navigation property.

Doh! It didn't even cross my mind that I could mix the `IMutableEntityType` API and the fluent API... Thanks for the suggestion!

**Comment by kYann** [comment]
You could also add a Convention (`IEntityTypeAddedConvention`) before any other conventions (using .Insert(0, ) on the conventionset).
That Convention would add any of the Type Property that match your type as a EF Property.

```csharp
public void ProcessEntityTypeAdded(IConventionEntityTypeBuilder entityTypeBuilder, IConventionContext<IConventionEntityTypeBuilder> context)
{
	if (entityTypeBuilder.Metadata.ClrType is null)
		return;

	var properties = entityTypeBuilder.Metadata.ClrType.GetProperties()
		.Where(p => p.PropertyType == typeof(YourType))
		.ToList();

	if (entityTypeBuilder.Metadata is IMutableEntityType entityType)
	{
		foreach (var property in properties)
		{
			entityType.AddProperty(property.Name, property.PropertyType, property);
		}
	}
}
```
