### ISSUE TITLE
Adding to nav prop of M2M tries to insert in 2nd table not in M2M link table

### ISSUE THREAD

**Issue by LucaGabi** [dotnet/efcore#23772]
## Ask a question

Trying to add new book with a M2M relation of authors dose insert in the authors table not in the M2M table why ?

### Include your code

Usually the best way to ask a clear question and get a quick response is to show your code. Preferably, attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing.

Use triple-tick code fences for any posted code. For example:

```C#
    public abstract class BaseEntity
    {
        public BaseEntity()
        {
            CreatedOn = DateTime.Now;
        }

        
        public DateTime CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
    }

public class Book: BaseEntity
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string CoverImagePath { get; set; }


        public virtual ICollection<Author> Authors { get; set; }
        //public virtual ICollection<AuthorBook> AuthorBooks { get; set; }

    }

public class Author : BaseEntity
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Book> Books { get; set; }
        //public virtual ICollection<AuthorBook> AuthorBooks { get; set; }
    }

public partial class BookArchiveDataContext
    {
        public DbSet<Book> Books { get; set; }
        public DbSet<Author> Authors { get; set; }
    }
```

### Include stack traces

Include the full exception message and stack trace for any exception you encounter.

```
info: 28/12/2020 16:21:13.300 CoreEventId.ContextInitialized[10403] (Microsoft.EntityFrameworkCore.Infrastructure)
      Entity Framework Core 5.0.0 initialized 'BookArchiveDataContext' using provider 'Microsoft.EntityFrameworkCore.Sqlite' with options: SensitiveDataLoggingEnabled DetailedErrorsEnabled
dbug: 28/12/2020 16:21:13.305 RelationalEventId.CommandCreating[20103] (Microsoft.EntityFrameworkCore.Database.Command)
      Creating DbCommand for 'ExecuteReader'.
dbug: 28/12/2020 16:21:13.305 RelationalEventId.CommandCreated[20104] (Microsoft.EntityFrameworkCore.Database.Command)
      Created DbCommand for 'ExecuteReader' (0ms).
dbug: 28/12/2020 16:21:13.305 RelationalEventId.ConnectionOpening[20000] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opening connection to database 'main' on server 'books-archive.db'.
dbug: 28/12/2020 16:21:13.307 RelationalEventId.ConnectionOpened[20001] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opened connection to database 'main' on server 'C:\Work\rawweb\BookArchive\API\books-archive.db'.
dbug: 28/12/2020 16:21:13.307 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[@__id_0='0' (DbType = String)], CommandType='Text', CommandTimeout='30']
      SELECT "t"."Id", "t"."CoverImagePath", "t"."CreatedOn", "t"."Description", "t"."Title", "t"."UpdatedOn", "t0"."Id", "t0"."CreatedOn", "t0"."Name", "t0"."UpdatedOn", "t0"."AuthorsId", "t0"."BooksId"
      FROM (
          SELECT "b"."Id", "b"."CoverImagePath", "b"."CreatedOn", "b"."Description", "b"."Title", "b"."UpdatedOn"
          FROM "Books" AS "b"
          WHERE "b"."Id" = @__id_0
          LIMIT 1
      ) AS "t"
      LEFT JOIN (
          SELECT "a0"."Id", "a0"."CreatedOn", "a0"."Name", "a0"."UpdatedOn", "a"."AuthorsId", "a"."BooksId"
          FROM "AuthorBook" AS "a"
          INNER JOIN "Authors" AS "a0" ON "a"."AuthorsId" = "a0"."Id"
      ) AS "t0" ON "t"."Id" = "t0"."BooksId"
      ORDER BY "t"."Id", "t0"."AuthorsId", "t0"."BooksId", "t0"."Id"
info: 28/12/2020 16:21:13.311 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (4ms) [Parameters=[@__id_0='0' (DbType = String)], CommandType='Text', CommandTimeout='30']
      SELECT "t"."Id", "t"."CoverImagePath", "t"."CreatedOn", "t"."Description", "t"."Title", "t"."UpdatedOn", "t0"."Id", "t0"."CreatedOn", "t0"."Name", "t0"."UpdatedOn", "t0"."AuthorsId", "t0"."BooksId"
      FROM (
          SELECT "b"."Id", "b"."CoverImagePath", "b"."CreatedOn", "b"."Description", "b"."Title", "b"."UpdatedOn"
          FROM "Books" AS "b"
          WHERE "b"."Id" = @__id_0
          LIMIT 1
      ) AS "t"
      LEFT JOIN (
          SELECT "a0"."Id", "a0"."CreatedOn", "a0"."Name", "a0"."UpdatedOn", "a"."AuthorsId", "a"."BooksId"
          FROM "AuthorBook" AS "a"
          INNER JOIN "Authors" AS "a0" ON "a"."AuthorsId" = "a0"."Id"
      ) AS "t0" ON "t"."Id" = "t0"."BooksId"
      ORDER BY "t"."Id", "t0"."AuthorsId", "t0"."BooksId", "t0"."Id"
dbug: 28/12/2020 16:21:13.325 RelationalEventId.DataReaderDisposing[20300] (Microsoft.EntityFrameworkCore.Database.Command)
      A data reader was disposed.
dbug: 28/12/2020 16:21:13.326 RelationalEventId.ConnectionClosing[20002] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closing connection to database 'main' on server 'C:\Work\rawweb\BookArchive\API\books-archive.db'.
dbug: 28/12/2020 16:21:13.327 RelationalEventId.ConnectionClosed[20003] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closed connection to database 'main' on server 'books-archive.db'.
dbug: 28/12/2020 16:21:13.328 CoreEventId.ValueGenerated[10808] (Microsoft.EntityFrameworkCore.ChangeTracking)
      'BookArchiveDataContext' generated temporary value '-2147482646' for the property 'Id.Book'.
dbug: 28/12/2020 16:21:13.329 CoreEventId.StartedTracking[10806] (Microsoft.EntityFrameworkCore.ChangeTracking)
      Context 'BookArchiveDataContext' started tracking 'Book' entity with key '{Id: -2147482646}'.
dbug: 28/12/2020 16:21:13.331 CoreEventId.StartedTracking[10806] (Microsoft.EntityFrameworkCore.ChangeTracking)
      Context 'BookArchiveDataContext' started tracking 'AuthorBook' entity with key '{AuthorsId: 1, BooksId: -2147482646}'.
dbug: 28/12/2020 16:21:13.331 CoreEventId.StartedTracking[10806] (Microsoft.EntityFrameworkCore.ChangeTracking)
      Context 'BookArchiveDataContext' started tracking 'Author' entity with key '{Id: 1}'.
dbug: 28/12/2020 16:21:13.333 CoreEventId.StartedTracking[10806] (Microsoft.EntityFrameworkCore.ChangeTracking)
      Context 'BookArchiveDataContext' started tracking 'AuthorBook' entity with key '{AuthorsId: 2, BooksId: -2147482646}'.
dbug: 28/12/2020 16:21:13.333 CoreEventId.StartedTracking[10806] (Microsoft.EntityFrameworkCore.ChangeTracking)
      Context 'BookArchiveDataContext' started tracking 'Author' entity with key '{Id: 2}'.
dbug: 28/12/2020 16:21:13.335 CoreEventId.SaveChangesStarting[10004] (Microsoft.EntityFrameworkCore.Update)
      SaveChanges starting for 'BookArchiveDataContext'.
dbug: 28/12/2020 16:21:13.335 CoreEventId.DetectChangesStarting[10800] (Microsoft.EntityFrameworkCore.ChangeTracking)
      DetectChanges starting for 'BookArchiveDataContext'.
dbug: 28/12/2020 16:21:13.336 CoreEventId.SkipCollectionChangeDetected[10809] (Microsoft.EntityFrameworkCore.ChangeTracking)
      2 entities were added and 0 entities were removed from skip navigation 'Book.Authors' on entity with key '{Id: -2147482646}'.
dbug: 28/12/2020 16:21:13.338 CoreEventId.DetectChangesCompleted[10801] (Microsoft.EntityFrameworkCore.ChangeTracking)
      DetectChanges completed for 'BookArchiveDataContext'.
dbug: 28/12/2020 16:21:13.338 RelationalEventId.ConnectionOpening[20000] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opening connection to database 'main' on server 'books-archive.db'.
dbug: 28/12/2020 16:21:13.339 RelationalEventId.ConnectionOpened[20001] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opened connection to database 'main' on server 'C:\Work\rawweb\BookArchive\API\books-archive.db'.
dbug: 28/12/2020 16:21:13.340 RelationalEventId.TransactionStarting[20209] (Microsoft.EntityFrameworkCore.Database.Transaction)
      Beginning transaction with isolation level 'Unspecified'.
dbug: 28/12/2020 16:21:13.341 RelationalEventId.TransactionStarted[20200] (Microsoft.EntityFrameworkCore.Database.Transaction)
      Began transaction with isolation level 'Serializable'.
dbug: 28/12/2020 16:21:13.342 RelationalEventId.CommandCreating[20103] (Microsoft.EntityFrameworkCore.Database.Command)
      Creating DbCommand for 'ExecuteReader'.
dbug: 28/12/2020 16:21:13.342 RelationalEventId.CommandCreated[20104] (Microsoft.EntityFrameworkCore.Database.Command)
      Created DbCommand for 'ExecuteReader' (0ms).
dbug: 28/12/2020 16:21:13.344 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[@p0='1' (DbType = String), @p1='2020-12-28T16:06:39.7657781+02:00' (DbType = String), @p2=NULL], CommandType='Text', CommandTimeout='30']
      INSERT INTO "Authors" ("Id", "CreatedOn", "Name")
      VALUES (@p0, @p1, @p2);
      SELECT "UpdatedOn"
      FROM "Authors"
      WHERE changes() = 1 AND "Id" = @p0;
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (7ms) [Parameters=[@p0='1' (DbType = String), @p1='2020-12-28T16:06:39.7657781+02:00' (DbType = String), @p2=NULL], CommandType='Text', CommandTimeout='30']
      INSERT INTO "Authors" ("Id", "CreatedOn", "Name")
      VALUES (@p0, @p1, @p2);
      SELECT "UpdatedOn"
      FROM "Authors"
      WHERE changes() = 1 AND "Id" = @p0;
fail: 28/12/2020 16:21:13.354 RelationalEventId.CommandError[20102] (Microsoft.EntityFrameworkCore.Database.Command)
      Failed executing DbCommand (7ms) [Parameters=[@p0='1' (DbType = String), @p1='2020-12-28T16:06:39.7657781+02:00' (DbType = String), @p2=NULL], CommandType='Text', CommandTimeout='30']
      INSERT INTO "Authors" ("Id", "CreatedOn", "Name")
      VALUES (@p0, @p1, @p2);
      SELECT "UpdatedOn"
      FROM "Authors"
      WHERE changes() = 1 AND "Id" = @p0;
dbug: 28/12/2020 16:21:13.358 RelationalEventId.TransactionDisposed[20204] (Microsoft.EntityFrameworkCore.Database.Transaction)
      Disposing transaction.
dbug: 28/12/2020 16:21:13.361 RelationalEventId.ConnectionClosing[20002] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closing connection to database 'main' on server 'C:\Work\rawweb\BookArchive\API\books-archive.db'.
dbug: 28/12/2020 16:21:13.362 RelationalEventId.ConnectionClosed[20003] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closed connection to database 'main' on server 'books-archive.db'.
fail: Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type 'BookArchive.DAL.BookArchiveDataContext'.
      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
       ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: Authors.Id'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: Authors.Id'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
fail: 28/12/2020 16:21:13.376 CoreEventId.SaveChangesFailed[10000] (Microsoft.EntityFrameworkCore.Update)
      An exception occurred in the database while saving changes for context type 'BookArchive.DAL.BookArchiveDataContext'.
      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
       ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: Authors.Id'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
dbug: 28/12/2020 16:21:13.564 CoreEventId.ContextDisposed[10407] (Microsoft.EntityFrameworkCore.Infrastructure)
      'BookArchiveDataContext' disposed.
```

### Include provider and version information

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 5.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by anranruye** [comment]
It seems that you add untracked author entity to the author collection of a book.  If so,  load these authors from database first before add them to the authors nav property.

**Comment by LucaGabi** [comment]
Thank you ... but if I attach them the data is not complete and will overwrite values in db.

Can we also use the m2m link table as a DbSet and preform ops directly on that in EF5 ?

**Comment by anranruye** [comment]
@LucaGabi 
No,  an attach operation is not expected to override values in db,  if it does,  then this is a bug. 

Yes,  you can do that. I'm not sure if the link entity can be discovered automatically.  But you can explicitly configure this by fluent api.

**Comment by LucaGabi** [comment]
I was not able to map m2m as DbSet. Updating the m2m relation is only possible by loading the parent entity .. or I'm missing a point ..

**Comment by anranruye** [comment]
@LucaGabi 

see at https://docs.microsoft.com/en-us/ef/core/modeling/relationships 

you can get all you need in the official documentation.

**Comment by LucaGabi** [comment]
The tow methods mentioned exclude each other. Why can't we have a dbset of the m2m table also when not using a third join table ?? ..

**Comment by anranruye** [comment]
@LucaGabi 

I don't understand how you can make a many to many relationship without a third join table. 

can you explain what it means?

**Comment by LucaGabi** [comment]
In EF Core there are 2 ways of creating m2m relations: one with explicit entity one without join entity. In the second case I see it's not possible to access the m2m table as a dbset why ?

**Comment by LucaGabi** [comment]
I never said m2m can exist without link table (assoc table) in db ..

**Comment by anranruye** [comment]
@LucaGabi 

I'm upset because you just believe in what you believe and never listen to me. 

Before ef core 5,  it's true that you can not skip the link entity when you configure a many-to-many relationship.  But things are changed with ef core 5. Please read the new documentation and sample code carefully before you comment. 

If you read,  you should notice that in the sample code,  the `Post` entity has a collection of `Tag` named `Tags`,  also the `Tag` entity has a collection of `Post` named `Posts`(they are both required in the current version).  And you can omit the two `PostTags` properties in both entities,  they are optional.  Also you can add a DbSet property for the join entity in the DbContext class. 

So the code can be changed to:
```C#
class MyContext : DbContext
{
    public MyContext(DbContextOptions<MyContext> options)
        : base(options)
    {
    }

    public DbSet<Post> Posts { get; set; }
    public DbSet<Tag> Tags { get; set; }
    public DbSet<PostTag> PostTags {get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Post>()
            .HasMany(p => p.Tags)
            .WithMany(p => p.Posts)
            .UsingEntity<PostTag>(
                j => j
                    .HasOne(pt => pt.Tag)
                    .WithMany(/*t => t.PostTags*/)
                    .HasForeignKey(pt => pt.TagId),
                j => j
                    .HasOne(pt => pt.Post)
                    .WithMany(/*p => p.PostTags*/)
                    .HasForeignKey(pt => pt.PostId),
                j =>
                {
                    j.Property(pt => pt.PublicationDate).HasDefaultValueSql("CURRENT_TIMESTAMP");
                    j.HasKey(t => new { t.PostId, t.TagId });
                });
    }
}

public class Post
{
    public int PostId { get; set; }
    public string Title { get; set; }
    public string Content { get; set; }

    public ICollection<Tag> Tags { get; set; }
    //public List<PostTag> PostTags { get; set; }
}

public class Tag
{
    public string TagId { get; set; }

    public ICollection<Post> Posts { get; set; }
    //public List<PostTag> PostTags { get; set; }
}

public class PostTag
{
    public DateTime PublicationDate { get; set; }

    public int PostId { get; set; }
    public Post Post { get; set; }

    public string TagId { get; set; }
    public Tag Tag { get; set; }
}
```

Is this clear enough?  I didn't think I should explain this question to this point. I think you should find the answer yourself! If you still don't understand,  I can not explain it further.

**Comment by LucaGabi** [comment]
I think you don't understand what I'm asking ... I can post a sample project here ...

The Authors update dose not work ... 

Thanks for your answers and time.

[DBBook.zip](https://github.com/dotnet/efcore/files/5751363/DBBook.zip)

**Comment by anranruye** [comment]
@LucaGabi 

Yes,  I don't know what you are really asking. And I  think nobody knows it except yourself. If you don't 
clearly tell us what you need,  then we cannot help you!

Also I read your code, sometimes I just can't understand what you are doing. 
```C#
private async Task<CQRSResult<BookDTO>> addOrUpdate(BookUpdateCommand req)
            {
                using (var t = uow.CreateTransaction())
                {
try
                    {
                        var dbLinks = req.Authors != null
                            ? uow.BooksRepository.GetById(req.Id).Authors.ToList()
                            : new List<Author>();
                        var reqLinks = req.Authors.ToList();

                        dbLinks.ForEach(x => uow.AuthorsRepository.Delete(x));
                        reqLinks.ForEach(x => uow.AuthorsRepository.Add(x));

                        uow.BooksRepository.Update(req);

                        await uow.Save(default);

                        t.Commit();
                        return mapper.Map<BookDTO>(req);
                    }
                    catch (DbException)
                    {
                        t.Rollback();
                        return mapper.Map<BookDTO>(req).AsCQRSResult(code: 400, "Database operation error");
                    }
                    catch (Exception e)
                    {
                        t.Rollback();
                        throw e;
                    }
                }
           }
```

**Comment by LucaGabi** [comment]
I posted an old version with the code from ef 3.1 .. with a bug that I fixed ... sorry 
About your question that should update the links .. to Authors .. :) ..

The thing is I was trying to do update on a book and change the .. authors association ...

**Comment by anranruye** [comment]
@LucaGabi 

Certainly it doesn't work!

If you do not understand the mechanism how ef core track entities and relations,  you can not write right code. 

see at https://docs.microsoft.com/en-us/ef/core/saving/related-data

Notice the key word "tracked",  you should not use AsNoTracking in this case. 

using AsNoTracking results in unattached/untracked entity object. it's not bad to work with unattached entity in order to improve performance.  but you should know how tracked entities work before work with untracked ones.

**Comment by LucaGabi** [comment]
You mean this code has no effect ?

```c#

dbContext.Set<T>().Attach(entity);
entry.State = EntityState.Modified;

```

**Comment by LucaGabi** [comment]
I changed my Update method and it still dose not work:

```c#
public override void Update(Author entity)
        {
            var dbo = dcx.Authors.First(x => x.Id == entity.Id);
            dbo.Name = entity.Name;
            if (dbo.AuthorBooks==null)
            {
                dbo.AuthorBooks = new List<AuthorBook>();
            }
            dbo.AuthorBooks.Clear();
            entity.AuthorBooks.ToList()
                .ForEach(x => entity.AuthorBooks.Add(x));
        }
```

**Comment by LucaGabi** [comment]
There is an exceptiom now:

```
dbug: 30/12/2020 05:51:15.457 CoreEventId.StartedTracking[10806] (Microsoft.EntityFrameworkCore.ChangeTracking)
      Context 'BookArchiveDataContext' started tracking 'Author' entity with key '{Id: 1}'.
dbug: 30/12/2020 05:51:15.499 RelationalEventId.DataReaderDisposing[20300] (Microsoft.EntityFrameworkCore.Database.Command)
      A data reader was disposed.
dbug: 30/12/2020 05:51:15.499 RelationalEventId.ConnectionClosing[20002] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closing connection to database 'main' on server 'C:\Work\rawweb\BookArchive\API\books-archive.db'.
dbug: 30/12/2020 05:51:15.503 RelationalEventId.ConnectionClosed[20003] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closed connection to database 'main' on server 'books-archive.db'.
dbug: 30/12/2020 05:51:20.075 CoreEventId.SaveChangesStarting[10004] (Microsoft.EntityFrameworkCore.Update)
      SaveChanges starting for 'BookArchiveDataContext'.
dbug: 30/12/2020 05:51:20.078 CoreEventId.DetectChangesStarting[10800] (Microsoft.EntityFrameworkCore.ChangeTracking)
      DetectChanges starting for 'BookArchiveDataContext'.
dbug: 30/12/2020 05:51:20.097 CoreEventId.CollectionChangeDetected[10804] (Microsoft.EntityFrameworkCore.ChangeTracking)
      2 entities were added and 0 entities were removed from navigation 'Author.AuthorBooks' on entity with key '{Id: 1}'.
dbug: 30/12/2020 05:51:20.180 CoreEventId.StartedTracking[10806] (Microsoft.EntityFrameworkCore.ChangeTracking)
      Context 'BookArchiveDataContext' started tracking 'AuthorBook' entity with key '{AuthorId: 1, BookId: -2147482647}'.
dbug: 30/12/2020 05:51:20.182 CoreEventId.StartedTracking[10806] (Microsoft.EntityFrameworkCore.ChangeTracking)
      Context 'BookArchiveDataContext' started tracking 'AuthorBook' entity with key '{AuthorId: 1, BookId: -2147482646}'.
dbug: 30/12/2020 05:51:20.187 CoreEventId.DetectChangesCompleted[10801] (Microsoft.EntityFrameworkCore.ChangeTracking)
      DetectChanges completed for 'BookArchiveDataContext'.
fail: Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type 'BookArchive.DAL.BookArchiveDataContext'.
      System.InvalidOperationException: The value of 'AuthorBook.BookId' is unknown when attempting to save changes. This is because the property is also part of a foreign key for which the principal entity in the relationship is not known.         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.PrepareToSave()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetEntriesToSave(Boolean cascadeChanges)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
System.InvalidOperationException: The value of 'AuthorBook.BookId' is unknown when attempting to save changes. This is because the property is also part of a foreign key for which the principal entity in the relationship is not known.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.PrepareToSave()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetEntriesToSave(Boolean cascadeChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
fail: 30/12/2020 05:51:20.249 CoreEventId.SaveChangesFailed[10000] (Microsoft.EntityFrameworkCore.Update)
      An exception occurred in the database while saving changes for context type 'BookArchive.DAL.BookArchiveDataContext'.
      System.InvalidOperationException: The value of 'AuthorBook.BookId' is unknown when attempting to save changes. This is because the property is also part of a foreign key for which the principal entity in the relationship is not known.         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.PrepareToSave()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetEntriesToSave(Boolean cascadeChanges)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
dbug: 30/12/2020 05:51:24.600 CoreEventId.ContextDisposed[10407] (Microsoft.EntityFrameworkCore.Infrastructure)
      'BookArchiveDataContext' disposed.
```
