### ISSUE TITLE
ValueConverter stops working when moving a class to a different assembly

### ISSUE THREAD

**Issue by opinionmachine** [dotnet/efcore#23785]
## Ask a question
I have two guids being passed around in code everywhere, and to disambiguate them I created separate types that both wrap System.Guid (let's call them AGuid and BGuid) whilst making sure they cannot be mistaken for each other and create subtle bugs.

I have one website that is EfCore for now, but because I'm exporting some data into an API I need to put the entity classes in a classlibrary that can be reached from the API project. 

I move the classes, and change all references. The DbContext class remains in the original website, but now defines  DbSet<Acme.ClassLibrary.Models.EntityA> EntityAs {get; set; }  rather than DbSet<Acme.Admin.Features.EntityA> EntityAs { get; set; } 

Up top in OnModelCreating(ModelBuilder modelBuilder), I have all along had ValueConverters for my pimped Guids:
```csharp
    var aGuidConverter = new ValueConverter<AGuid, Guid>(
                v => v.Value,
                v => (AGuid)v);
    var bGuidConverter = new ValueConverter<BGuid, Guid>(
                v => v.Value,
                v => (BGuid)v);
```
Further down I map the converter to the entities that have the pimped guids:
```csharp
           modelBuilder.Entity<Acme.Admin.Features.EntityA>().Property(e => e.BGuid).HasConversion(bGuidConverter);
```
Which I then change to: 
```csharp
           modelBuilder.Entity<Acme.ClassLibrary.Models.EntityA>().Property(e => e.BGuid).HasConversion(bGuidConverter);
```
The previous version when the entities lived in the web project was working flawlessly. AGuid and BGuid have lived in the class library all throughout. 

When I do the first call to get data from the context, I get a validation exception. Since then I have created an xUnit test that validates the DbContext that recreates the exception faster:

```
System.InvalidOperationException
No suitable constructor was found for entity type 'BGuid'. The following constructors had parameters that could not be bound to properties of the entity type: cannot bind 'guid' in 'BGuid(Guid guid)'.
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.ConstructorBindingConvention.ProcessModelFinalizing(IConventionModelBuilder modelBuilder, IConventionContext`1 context)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelFinalizing(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelFinalizing(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FinalizeModel()
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Acme.API.DbUp.Tests.IntegrationTests.AcmeDbContextValidation.Can_be_validated() in D:\code\Acme.Web\test\Acme.API.DbUp.Tests\IntegrationTests\AcmeDbContextValidation.cs:line 47
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90

Microsoft.EntityFrameworkCore.Infrastructure [Microsoft.EntityFrameworkCore.Infrastructure.ServiceProviderCreated] An 'IServiceProvider' was created for internal use by Entity Framework.

```

EF Core version: 5.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: net5
Operating system: Windows 10 Pro
IDE:  Visual Studio 2019 16.3

**Comment by ajcvickers** [comment]
@opinionmachine I am not able to reproduce this--see my code. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

App:
```C#
public class SomeDbContext : DbContext
{
    private static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole()); //.SetMinimumLevel(LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(Your.ConnectionString)
            .UseLoggerFactory(ContextLoggerFactory)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        var aGuidConverter = new ValueConverter<AGuid, Guid>(v => v.Value, v => new AGuid { Value = v });
        var bGuidConverter = new ValueConverter<BGuid, Guid>(v => v.Value, v => new BGuid { Value = v });
        
        modelBuilder.Entity<EntityA>().Property(e => e.BGuid).HasConversion(bGuidConverter);
        modelBuilder.Entity<EntityB>().Property(e => e.AGuid).HasConversion(aGuidConverter);
    }
}    

public class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();
        }
    }
}
```

Class library:
```C#
public class EntityA
{
    public int Id { get; set; }

    public BGuid BGuid { get; set; }
}

public class EntityB
{
    public int Id { get; set; }
    
    public AGuid AGuid { get; set; }
}

public class AGuid
{
    public Guid Value { get; set; }
}

public class BGuid
{
    public Guid Value { get; set; }
}
```

**Comment by opinionmachine** [comment]
Hey, Happy New Year first of all!

Second - I did that yesterday, I e created an empty web project with my custom types as keys on two entities that have an FK relationship BUT it was ludicrously smooth and problem free. I e it’s not a bug or anything, so thanks for spending the time on my problem.

It seems in my proper site AGuid is registered as an entity, not a value type. Is there any way I can correct that? I thought the value converters should take care of that? Loads of shadow properties everywhere as well so if I try to just delete AGuid from the array of entities it gives me an error that there are constraints against the “entity”, which I find odd.

**Comment by ajcvickers** [comment]
> It seems in my proper site AGuid is registered as an entity, not a value type. 

This should not happen if a call is being made to `.Property` in the model builder. Make sure you're not missing mapping the property and setting the converter in any place. Check your OnModelCreating and/or EntityConfiguration instances are actually being used.

**Comment by opinionmachine** [comment]
Thanks, I will double check!

**Comment by opinionmachine** [comment]
Yeah, it turned out I had gone a bit crazy, removing a DbSet<T> without removing the key definition from OnModelCreating, After cleaning that stuff up, it all started working.

Thank you so much for your help!
