### ISSUE TITLE
Apply migration using MySQL provider with DropForeign key generate error 

### ISSUE THREAD

**Issue by linkprada** [dotnet/efcore#23855]
## File a bug

Issue : Any operation involving drop foreign key results in a bad generated mysql query
exemple:
```mysql
ALTER TABLE `table_name` DROP CONSTRAINT `id_name_fk`
```
should be :
```mysql
ALTER TABLE `table_name` DROP FOREIGN KEY `id_name_fk`;
```

### Including small project 
[DropForeignKeyIssueMysql.zip](https://github.com/dotnet/efcore/files/5799422/DropForeignKeyIssueMysql.zip)

Steps to reproduce the error :

1 - Apply initial migration (already generated in attached project)
```console
dotnet-ef database update
```
2 - Make an operation that will drop foreign keys for exemple : changing ondelete behavior
### Persistance/AppDbContext.cs
```C#
public class AppDbContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Post> Posts { get; set; }
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
        {

        }
        protected override void OnModelCreating(ModelBuilder builder)
        {
            // UNCOMMENT TO MODIFY FOREIGN KEY ONDELETE BEHAVIOR ==> DROP FOREIGN KEYS AND RECREATING THEM
            // foreach (var foreignKey in builder.Model.GetEntityTypes().SelectMany(e => e.GetForeignKeys()))
            // {
            //     foreignKey.DeleteBehavior = DeleteBehavior.Restrict;
            // }
        }
    }
```
3 - Generate a new migration
```console
dotnet-ef migrations add Modifying_DeleteBehavior_To_Restrict
```

4 - Apply the generated migration 
```console
dotnet-ef database update
```

### Stack traces

```
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      ALTER TABLE `Posts` DROP CONSTRAINT `FK_Posts_Blogs_BlogId`;
Failed executing DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE `Posts` DROP CONSTRAINT `FK_Posts_Blogs_BlogId`;
MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CONSTRAINT `FK_Posts_Blogs_BlogId`' at line 1
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)        
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CONSTRAINT `FK_Posts_Blogs_BlogId`' at line 1
```

### Include verbose output

Please include `--verbose` output when filing bugs about the `dotnet ef` or Package Manager Console tools.

Use triple-tick fences for tool output. For example:

```
Using project 'C:\Users\Riven\Desktop\test\VSCode_Workspace\DropForeignKeyIssueMysql\DropForeignKeyIssueMysql.csproj'.
Using startup project 'C:\Users\Riven\Desktop\test\VSCode_Workspace\DropForeignKeyIssueMysql\DropForeignKeyIssueMysql.csproj'.
Writing 'C:\Users\Riven\Desktop\test\VSCode_Workspace\DropForeignKeyIssueMysql\obj\DropForeignKeyIssueMysql.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\Riven\AppData\Local\Temp\tmp49BD.tmp /verbosity:quiet /nologo C:\Users\Riven\Desktop\test\VSCode_Workspace\DropForeignKeyIssueMysql\DropForeignKeyIssueMysql.csproj
Writing 'C:\Users\Riven\Desktop\test\VSCode_Workspace\DropForeignKeyIssueMysql\obj\DropForeignKeyIssueMysql.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\Riven\AppData\Local\Temp\tmp4EDF.tmp /verbosity:quiet /nologo C:\Users\Riven\Desktop\test\VSCode_Workspace\DropForeignKeyIssueMysql\DropForeignKeyIssueMysql.csproj
Build started...
dotnet build C:\Users\Riven\Desktop\test\VSCode_Workspace\DropForeignKeyIssueMysql\DropForeignKeyIssueMysql.csproj /verbosity:quiet /nologo

La génération a réussi.
    0 Avertissement(s)
    0 Erreur(s)

Temps écoulé 00:00:02.90
Build succeeded.
dotnet exec --depsfile C:\Users\Riven\Desktop\test\VSCode_Workspace\DropForeignKeyIssueMysql\bin\Debug\netcoreapp3.1\DropForeignKeyIssueMysql.deps.json --additionalprobingpath C:\Users\Riven\.nuget\packages --runtimeconfig C:\Users\Riven\Desktop\test\VSCode_Workspace\DropForeignKeyIssueMysql\bin\Debug\netcoreapp3.1\DropForeignKeyIssueMysql.runtimeconfig.json C:\Users\Riven\.dotnet\tools\.store\dotnet-ef\3.1.5\dotnet-ef\3.1.5\tools\netcoreapp3.1\any\tools\netcoreapp2.0\any\ef.dll database update --assembly C:\Users\Riven\Desktop\test\VSCode_Workspace\DropForeignKeyIssueMysql\bin\Debug\netcoreapp3.1\DropForeignKeyIssueMysql.dll --startup-assembly C:\Users\Riven\Desktop\test\VSCode_Workspace\DropForeignKeyIssueMysql\bin\Debug\netcoreapp3.1\DropForeignKeyIssueMysql.dll --project-dir C:\Users\Riven\Desktop\test\VSCode_Workspace\DropForeignKeyIssueMysql\ --language C# --working-dir C:\Users\Riven\Desktop\test\VSCode_Workspace\DropForeignKeyIssueMysql --verbose --root-namespace DropForeignKeyIssueMysql
Using assembly 'DropForeignKeyIssueMysql'.
Using startup assembly 'DropForeignKeyIssueMysql'.
Using application base 'C:\Users\Riven\Desktop\test\VSCode_Workspace\DropForeignKeyIssueMysql\bin\Debug\netcoreapp3.1'.
Using working directory 'C:\Users\Riven\Desktop\test\VSCode_Workspace\DropForeignKeyIssueMysql'.
Using root namespace 'DropForeignKeyIssueMysql'.
Using project directory 'C:\Users\Riven\Desktop\test\VSCode_Workspace\DropForeignKeyIssueMysql\'.
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider...
Finding Microsoft.Extensions.Hosting service provider...
Using environment 'Development'.
Using application service provider from Microsoft.Extensions.Hosting.
Found DbContext 'AppDbContext'.
Finding DbContext classes in the project...
Using context 'AppDbContext'.
Finding design-time services for provider 'MySql.Data.EntityFrameworkCore'...
Using design-time services from provider 'MySql.Data.EntityFrameworkCore'.
Finding design-time services referenced by assembly 'DropForeignKeyIssueMysql'.
No referenced design-time services were found.
Finding IDesignTimeServices implementations in assembly 'DropForeignKeyIssueMysql'...
No design-time services were found.
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      ALTER TABLE `Posts` DROP CONSTRAINT `FK_Posts_Blogs_BlogId`;
Failed executing DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE `Posts` DROP CONSTRAINT `FK_Posts_Blogs_BlogId`;
MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CONSTRAINT `FK_Posts_Blogs_BlogId`' at line 1
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)        
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CONSTRAINT `FK_Posts_Blogs_BlogId`' at line 1
```

### Include provider and version information

EF Core version: 3.1.5
Database provider: MySql.Data.EntityFrameworkCore
Target framework: .NET Core 3.1
Operating system: window 10
IDE:

**Comment by roji** [comment]
@linkprada this looks like a bug in [the Oracle MySQL provider](https://dev.mysql.com/doc/connector-net/en/connector-net-entityframework-core.html), which isn't maintained here - please flag this with them.

**Comment by linkprada** [comment]
Thank you for taking time to review the issue (first time posting one😄 )

**Comment by roji** [comment]
No problem @linkprada, welcome to Github :)
