### ISSUE TITLE
How do I model multiple cascade paths?

### ISSUE THREAD

**Issue by andrejohansson** [dotnet/efcore#23857]
## Ask a question

I have trouble wrapping my head around why I'm not allowed to have multiple cascade paths in sql server. Can someone please explain why?

In my example I have the following:

- An Invoice entity
- And Address entity
- The invoice have one required customer address (with cascade delete) and one supplier address (with cascade delete)

Then

- Building and running the model in sql lite works fine
- Generating my migration works fine
- Applying the migration to an sql server fails

### Include your code

Invoice
```csharp
public class Invoice : OwnedEntity<BookingSupplier>
    {
        // Properties

        /// <summary>
        /// Invoice reference "number".
        /// <example>#001, or CUST-A-001, or similar</example>
        /// </summary>
        public string Number { get; set; }
        [Column(TypeName = "decimal(18,4)")] public decimal TotalAmount { get; set; }
        [NotMapped] public DateTimeOffset DueDate => this.Created.Add(this.Term.Period);

        // Navigation
        public virtual Address CustomerAddress { get; set; }
        public Guid CustomerAddressId {get; set; }
        public virtual Address SupplierAddress { get; set; }
        public Guid SupplierAddressId {get; set; }
        public virtual Currency Currency { get; set; }
        public Guid CurrencyId {get; set; }
        public virtual PaymentTerm Term { get; set; }
        public Guid TermId {get; set; }

        public Guid? CustomerId {get; set; }

        // One to many
        public virtual List<InvoiceLine> Lines { get; set; }
    }
```

Address
```csharp
public class Address : BaseEntity
    {
        // Property
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string Building { get; set; }
        public string City { get; set; }
        public string CountryRegion { get; set; }
        public string FloorLevel { get; set; }
        public string PostalCode { get; set; }
        public string StateProvince { get; set; }

        // Navigation
        public virtual Country Country { get; set; }
        public Guid? CountryId { get; set; }
        public Guid? PersonId { get; set; }
    }
```

**Relevant part of Invoice entity configuration**
```csharp
            modelBuilder.Entity<Invoice>()
                .HasOne(o => o.CustomerAddress)
                .WithOne()
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            modelBuilder.Entity<Invoice>()
                .HasOne(o => o.SupplierAddress)
                .WithOne()
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
```

### Include verbose output

```
Applying migration '20210112112010_InitialCreate'.
Failed executing DbCommand (39ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE [Invoice] (
    [Id] uniqueidentifier NOT NULL,
    [Number] nvarchar(max) NOT NULL,
    [TotalAmount] decimal(18,4) NOT NULL,
    [CustomerAddressId] uniqueidentifier NOT NULL,
    [SupplierAddressId] uniqueidentifier NOT NULL,
    [CurrencyId] uniqueidentifier NOT NULL,
    [TermId] uniqueidentifier NOT NULL,
    [CustomerId] uniqueidentifier NULL,
    [Created] datetimeoffset NOT NULL,
    [Updated] datetimeoffset NOT NULL,
    [OwnerId] uniqueidentifier NOT NULL,
    CONSTRAINT [PK_Invoice] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_Invoice_Address_CustomerAddressId] FOREIGN KEY ([CustomerAddressId]) REFERENCES [Address] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_Invoice_Address_SupplierAddressId] FOREIGN KEY ([SupplierAddressId]) REFERENCES [Address] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_Invoice_Currency_CurrencyId] FOREIGN KEY ([CurrencyId]) REFERENCES [Currency] ([Id]),
    CONSTRAINT [FK_Invoice_Customer_CustomerId] FOREIGN KEY ([CustomerId]) REFERENCES [Customer] ([Id]) ON DELETE SET NULL
);
Microsoft.Data.SqlClient.SqlException (0x80131904): Introducing FOREIGN KEY constraint 'FK_Invoice_Address_SupplierAddressId' on table 'Invoice' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.
Could not create constraint or index. See previous errors.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:651f0c44-5d2d-41f1-805f-593d26dcb00b
Error Number:1785,State:0,Class:16
Introducing FOREIGN KEY constraint 'FK_Invoice_Address_SupplierAddressId' on table 'Invoice' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.
Could not create constraint or index. See previous errors.

```

### Include provider and version information

EF Core version: 5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0

**Comment by anranruye** [comment]
This is because the two AddressId can be the same and point to one `Address` entity. 

When you delete the Address entity,  both foreign key constraints will cause the Invoice entity to be  cascade deleted, which is not allowed by Sql Server(it only allows one fk constraint to do that).

**Comment by ajcvickers** [comment]
@andrejohansson This is SQL Server behavior, which is not something that EF Core can change. It's been this way for as long as I have been using SQL Server. I would suggest you contact the SQL Server team to understand why this limitation exists, although I suspect it will be hard to get an answer on a behavior this old. I think the chance that this will ever change is extremely small.

**Comment by andrejohansson** [comment]
I was hoping for the behavior "if an invoice is deleted then delete both the customer address and the supplier address".

@anranruye, your comment suggests that i have inverted this behaviour

Reading [this](https://dba.stackexchange.com/questions/44956/good-explanation-of-cascade-on-delete-update-behavior) suggests that the cascade definition should be placed on the child/dependant table (which aligns well with your comment).

I took another look at my configuration and noticed that I didn´t specify dependant and I changed it to:

```csharp
            modelBuilder.Entity<Invoice>()
                .HasOne(o => o.CustomerAddress)
                .WithOne()
                .HasForeignKey<Address>(a => a.InvoiceId)  // <-- added to specify address as dependant
                .OnDelete(OwnedRequiredChildDeleteBehavior)
                .IsRequired();

            modelBuilder.Entity<Invoice>()
                .HasOne(o => o.SupplierAddress)
                .WithOne()
                .HasForeignKey<Address>(a => a.InvoiceId) // <-- added to specify address as dependant
                .OnDelete(OwnedRequiredChildDeleteBehavior)
                .IsRequired();
```

This seems to work for me.

@ajcvickers It makes sense that the limitation exists, I think I was just stomped by the dependant order, I find one to one relationship almost the hardest to deal with due to their ambiguity.

**Comment by anranruye** [comment]
@andrejohansson  
It seems that you are using **one** foreign key column for **both relationships**, which will cause `CustomerAddress` and `SupplierAddress` to be always same. I don't think this is what you expect.

If the `Address`es always appear with `Invoice`s, I suggest that you use owned entity for this scenario. See https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities to learn more.
