### ISSUE TITLE
Cosmos WithPartitionKey call vs Where clause partitionKey InvalidOperationException

### ISSUE THREAD

**Issue by stack111** [dotnet/efcore#23902]
## File a bug
Referencing [Cosmos Provider PartitionKey section](https://docs.microsoft.com/en-us/ef/core/providers/cosmos/?tabs=dotnet-core-cli#partition-keys)

I have service which is using OData and returns back IAsyncEnumerable, Request url was:
```
https://***.com/odata/accounts?$filter=partitionKey%20eq%20'9942d181-7ef6-43bb-a6ba-9d57cf587242'%20and%20resourceGroup%20eq%20'***'%20and%20resourceName%20eq%20'***'
```

Note partitionkey: 9942d181-7ef6-43bb-a6ba-9d57cf587242

Exception thrown:
> System.InvalidOperationException,Partition key specified in the WithPartitionKey call '9942d181-7ef6-43bb-a6ba-9d57cf587242' and the partition key specified in the Where predicate '6c0630f1-fbf7-4ce6-8669-e67c78b63da8' must be identical. Remove one of them .

How did the `Where predicate` get propagated with with `6c0630f1-fbf7-4ce6-8669-e67c78b63da8`? This is not a consistent repro though. 

Expected: 
The partitionKey provided in the query should be picked for Cosmos.

Controller Code:

```csharp
    [Route("odata/accounts")]
    [ODataRoutePrefix("accounts")]
    [ApiController]
    [Authorize]
    public class AccountsODataController : ODataController
    {
        private readonly AccountsContext accountsContext;

        public AccountsODataController(AccountsContext accountsContext)
        {
            this.accountsContext = accountsContext;
        }

        [HttpGet("")]
        [EnableQuery(
            AllowedQueryOptions =
            AllowedQueryOptions.Select |
            AllowedQueryOptions.Count |
            AllowedQueryOptions.Filter |
            AllowedQueryOptions.OrderBy |
            AllowedQueryOptions.Top |
            AllowedQueryOptions.Skip)]
        [ApiVersion(ApiVersions.V1)]
        public IQueryable<DocumentAccount> QueryAccounts(ODataQueryOptions queryOptions)
        {
            accountsContext.ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;
            var baseQuery = this.accountsContext.Accounts.Where(a => a.ResourceType == ModelConstants.AccountResourceType);

            if (queryOptions.TryExtractFilter(nameof(ModelConstants.PartitionKey), out string partitionKey))
            {
                baseQuery = baseQuery.WithPartitionKey(partitionKey);
            }
            else if (queryOptions.TryExtractFilter(ModelConstants.SubscriptionId, out partitionKey))
            {
                baseQuery = baseQuery.WithPartitionKey(partitionKey);
            }

            return baseQuery;
        }

```

Full CSV trace statements (redacted), you can find package version and other details:
```csv CategoryName,Level,OriginalFormat,ParentId,RequestId,SpanId,assembly,innermostAssembly,innermostMethod,message,operation_Name,operation_ParentId,operation_SyntheticSource,outerAssembly,outerMessage,sdkVersion,sequence,session_Id,severityLevel,source,stackTrace,type,RequestHeaders,name,resultCode,url,EventId,EventName,CandidateCount,Endpoint,RoutePattern,MethodInfo,RouteData,0,ActionResult,ElapsedMilliseconds,AcceptHeader,OutputFormatter,Type
***.ExceptionHandler,2,"Unexpected exception with 5xx error response, Request id:""0HM5OO9VJD2HC:00000015"" statusCode:""500""",0,0HM5OO9VJD2HC:00000015,c83a59fe9c351349,"Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosShapedQueryCompilingExpressionVisitor+QueryingEnumerable`1, Microsoft.EntityFrameworkCore.Cosmos, Version=5.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60",System.InvalidOperationException,.ctor,Partition key specified in the WithPartitionKey call '9942d181-7ef6-43bb-a6ba-9d57cf587242' and the partition key specified in the Where predicate '6c0630f1-fbf7-4ce6-8669-e67c78b63da8' must be identical. Remove one of them .,GET AccountsOData/QueryAccounts,c83a59fe9c351349,,System.InvalidOperationException,Partition key specified in the WithPartitionKey call '9942d181-7ef6-43bb-a6ba-9d57cf587242' and the partition key specified in the Where predicate '6c0630f1-fbf7-4ce6-8669-e67c78b63da8' must be identical. Remove one of them .,il:2.16.0-18277,,,3,Microsoft.EntityFrameworkCore.Cosmos,"   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1..ctor(CosmosQueryContext cosmosQueryContext, ISqlExpressionFactory sqlExpressionFactory, IQuerySqlGeneratorFactory querySqlGeneratorFactory, SelectExpression selectExpression, Func`3 shaper, Type contextType, String partitionKeyFromExtension, Boolean standAloneStateManager)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Infrastructure.AsyncEnumerableReader.ReadInternal[T](Object value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncEnumerable(ActionContext context, ObjectResult result, Object asyncEnumerable, Func`2 reader)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
,,,,,,,,,,,,,,,,,
,0,,,,,,,,,,GET AccountsOData/QueryAccounts,,,,,aspnet5c:2.16.0+4d6ef1104436a5df0cc0d3eafed1691b5ed56f79,,,0,,,,Accept: application/json",,,,,,,,,,,,,,,,,,
Authorization: ***WEw,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
",GET AccountsOData/QueryAccounts,500,https://***.com/odata/accounts?$filter=partitionKey eq '***' and resourceGroup eq '***' and resourceName eq '***',,,,,,,,,,,,,
Microsoft.AspNetCore.Hosting.Diagnostics,4,,0,0HM5OO9VJD2HC:00000015,/odata/accounts,c83a59fe9c351349,,,,Request starting HTTP/1.1 GET https://***.com/odata/accounts?$filter=partitionKey%20eq%20'9942d181-7ef6-43bb-a6ba-9d57cf587242'%20and%20resourceGroup%20eq%20'***'%20and%20resourceName%20eq%20'***'  ,GET /odata/accounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,1,,,,,,,,1,,,,,,,,,,,,
Microsoft.AspNetCore.Routing.Matching.DfaMatcher,5,{CandidateCount} candidate(s) found for the request path '{Path}',0,0HM5OO9VJD2HC:00000015,/odata/accounts,c83a59fe9c351349,,,,2 candidate(s) found for the request path '/odata/accounts',GET /odata/accounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,0,,,,,,,,1001,CandidatesFound,2,,,,,,,,,,
Microsoft.AspNetCore.Routing.Matching.DfaMatcher,5,Endpoint '{Endpoint}' with route pattern '{RoutePattern}' is valid for the request path '{Path}',0,0HM5OO9VJD2HC:00000015,/odata/accounts,c83a59fe9c351349,,,,Endpoint '***Controller.QueryAccounts (***)' with route pattern 'odata/accounts' is valid for the request path '/odata/accounts',GET /odata/accounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,0,,,,,,,,1005,CandiateValid,,***Controller.QueryAccounts (***),odata/accounts,,,,,,,,
Microsoft.AspNetCore.Routing.Matching.DfaMatcher,5,Endpoint '{Endpoint}' with route pattern '{RoutePattern}' is valid for the request path '{Path}',0,0HM5OO9VJD2HC:00000015,/odata/accounts,c83a59fe9c351349,,,,Endpoint 'odata/{**ODataEndpointPath_accounts}' with route pattern 'odata/{**ODataEndpointPath_accounts}' is valid for the request path '/odata/accounts',GET /odata/accounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,0,,,,,,,,1005,CandiateValid,,odata/{**ODataEndpointPath_accounts},odata/{**ODataEndpointPath_accounts},,,,,,,,
Microsoft.AspNetCore.Mvc.Infrastructure.ActionSelector,5,No actions matched the current request. Route values: {RouteValues},0,0HM5OO9VJD2HC:00000015,/odata/accounts,c83a59fe9c351349,,,,No actions matched the current request. Route values: ,GET /odata/accounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,0,,,,,,,,3,NoActionsMatched,,,,,,,,,,,
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware,5,Request matched endpoint '{EndpointName}',0,0HM5OO9VJD2HC:00000015,/odata/accounts,c83a59fe9c351349,,,,Request matched endpoint '***Controller.QueryAccounts (***)',GET /odata/accounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,0,,,,,,,,1,MatchSuccess,,,,,,,,,,,
***.AzureADAuthenticationHandler,5,Authenticated,0,0HM5OO9VJD2HC:00000015,/odata/accounts,c83a59fe9c351349,,,,Authenticated:,GET /odata/accounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,0,,,,,,,,,,,,,,,,,,,,
***.AzureADAuthenticationHandler,5,AuthenticationScheme: {AuthenticationScheme} was successfully authenticated.,0,0HM5OO9VJD2HC:00000015,/odata/accounts,c83a59fe9c351349,,,,AuthenticationScheme: AzureADv2 was successfully authenticated.,GET /odata/accounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,0,,,,,,,,8,AuthenticationSchemeAuthenticated,,,,,,,,,,,
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService,4,Authorization was successful.,0,0HM5OO9VJD2HC:00000015,/odata/accounts,c83a59fe9c351349,,,,Authorization was successful.,GET /odata/accounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,1,,,,,,,,1,UserAuthorizationSucceeded,,,,,,,,,,,
Microsoft.AspNetCore.Routing.EndpointMiddleware,4,Executing endpoint '{EndpointName}',0,0HM5OO9VJD2HC:00000015,/odata/accounts,c83a59fe9c351349,,,,Executing endpoint '***Controller.QueryAccounts (***)',GET /odata/accounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,1,,,,,,,,,ExecutingEndpoint,,,,,,,,,,,
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker,4,Route matched with {RouteData}. Executing controller action with signature {MethodInfo} on controller {Controller} ({AssemblyName}).,0,0HM5OO9VJD2HC:00000015,/odata/accounts,c83a59fe9c351349,,,,Route matched with {action = """"QueryAccounts"""""," controller = """"AccountsOData""""}. Executing controller action with signature System.Linq.IQueryable`1[***.DocumentAccount] QueryAccounts(Microsoft.AspNet.OData.Query.ODataQueryOptions) on controller ***Controller (***).""",GET AccountsOData/QueryAccounts,c83a59fe9c351349,,,il:2.16.0-18277,,,1,,,,,,,,3,ControllerActionExecuting,,,,System.Linq.IQueryable`1[***.DocumentAccount] QueryAccounts(Microsoft.AspNet.OData.Query.ODataQueryOptions),"{action = ""QueryAccounts"", controller = ""AccountsOData""}",,,,,,,,,,,,,,,
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker,5,Execution plan of {FilterType} filters (in the following order): {Filters},0,0HM5OO9VJD2HC:00000015,c83a59fe9c351349,,,,Execution plan of authorization filters (in the following order): None,GET AccountsOData/QueryAccounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,0,,,,,,,,1,FilterExecutionPlan,,,,,,,,,,,
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker,5,Execution plan of {FilterType} filters (in the following order): {Filters},0,0HM5OO9VJD2HC:00000015,c83a59fe9c351349,,,,Execution plan of resource filters (in the following order): None,GET AccountsOData/QueryAccounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,0,,,,,,,,1,FilterExecutionPlan,,,,,,,,,,,
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker,5,Execution plan of {FilterType} filters (in the following order): {Filters},0,0HM5OO9VJD2HC:00000015,c83a59fe9c351349,,,,"Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Infrastructure.ModelStateInvalidFilter (Order: -2000), Microsoft.AspNet.OData.EnableQueryAttribute (Order: 0)",GET AccountsOData/QueryAccounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,0,,,,,,,,1,FilterExecutionPlan,,,,,,,,,,,
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker,5,Execution plan of {FilterType} filters (in the following order): {Filters},0,0HM5OO9VJD2HC:00000015,c83a59fe9c351349,,,,Execution plan of exception filters (in the following order): None,GET AccountsOData/QueryAccounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,0,,,,,,,,1,FilterExecutionPlan,,,,,,,,,,,
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker,5,Execution plan of {FilterType} filters (in the following order): {Filters},0,0HM5OO9VJD2HC:00000015,c83a59fe9c351349,,,,"Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.Infrastructure.ClientErrorResultFilter (Order: -2000), Microsoft.AspNet.OData.EnableQueryAttribute (Order: 0)",GET AccountsOData/QueryAccounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,0,,,,,,,,1,FilterExecutionPlan,,,,,,,,,,,
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker,5,Executing controller factory for controller {Controller} ({AssemblyName}),0,0HM5OO9VJD2HC:00000015,c83a59fe9c351349,,,,Executing controller factory for controller ***Controller (***),GET AccountsOData/QueryAccounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,0,,,,,,,,1,ControllerFactoryExecuting,,,,,,,,,,,
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker,5,Executed controller factory for controller {Controller} ({AssemblyName}),0,0HM5OO9VJD2HC:00000015,c83a59fe9c351349,,,,Executed controller factory for controller ***Controller (***),GET AccountsOData/QueryAccounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,0,,,,,,,,2,ControllerFactoryExecuted,,,,,,,,,,,
Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder,5,Attempting to bind parameter '{ParameterName}' of type '{ModelType}' ...,0,0HM5OO9VJD2HC:00000015,c83a59fe9c351349,,,,Attempting to bind parameter 'queryOptions' of type 'Microsoft.AspNet.OData.Query.ODataQueryOptions' ...,GET AccountsOData/QueryAccounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,0,,,,,,,,22,AttemptingToBindParameter,,,,,,,,,,,
Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder,5,Done attempting to bind parameter '{ParameterName}' of type '{ModelType}'.,0,0HM5OO9VJD2HC:00000015,c83a59fe9c351349,,,,Done attempting to bind parameter 'queryOptions' of type 'Microsoft.AspNet.OData.Query.ODataQueryOptions'.,GET AccountsOData/QueryAccounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,0,,,,,,,,23,DoneAttemptingToBindParameter,,,,,,,,,,,
Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder,5,Attempting to validate the bound parameter '{ParameterName}' of type '{ModelType}' ...,0,0HM5OO9VJD2HC:00000015,c83a59fe9c351349,,,,Attempting to validate the bound parameter 'queryOptions' of type 'Microsoft.AspNet.OData.Query.ODataQueryOptions' ...,GET AccountsOData/QueryAccounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,0,,,,,,,,26,AttemptingToValidateParameter,,,,,,,,,,,
Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder,5,Done attempting to validate the bound parameter '{ParameterName}' of type '{ModelType}'.,0,0HM5OO9VJD2HC:00000015,c83a59fe9c351349,,,,Done attempting to validate the bound parameter 'queryOptions' of type 'Microsoft.AspNet.OData.Query.ODataQueryOptions'.,GET AccountsOData/QueryAccounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,0,,,,,,,,27,DoneAttemptingToValidateParameter,,,,,,,,,,,
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker,4,Executing action method {ActionName} - Validation state: {ValidationState},0,0HM5OO9VJD2HC:00000015,c83a59fe9c351349,,,,Executing action method ***Controller.QueryAccounts (***) - Validation state: Valid,GET AccountsOData/QueryAccounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,1,,,,,,,,1,ActionMethodExecuting,,,,,,,,,,,
Microsoft.EntityFrameworkCore.Infrastructure,4,Entity Framework Core {version} initialized '{contextType}' using provider '{provider}' with options: {options},0,0HM5OO9VJD2HC:00000015,c83a59fe9c351349,,,,Entity Framework Core 5.0.1 initialized 'AccountsContext' using provider 'Microsoft.EntityFrameworkCore.Cosmos' with options: ServiceEndPoint=https://p-azmaps-idsvc.documents.azure.com Database=ResourceTypes ,GET AccountsOData/QueryAccounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,1,,,,,,,,10403,Microsoft.EntityFrameworkCore.Infrastructure.ContextInitialized,,,,,,,,,,,
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker,4,"Executed action method {ActionName}, returned result {ActionResult} in {ElapsedMilliseconds}ms.",0,0HM5OO9VJD2HC:00000015,c83a59fe9c351349,,,,"Executed action method ***Controller.QueryAccounts (***), returned result Microsoft.AspNetCore.Mvc.ObjectResult in 0.4602ms.",GET AccountsOData/QueryAccounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,1,,,,,,,,2,ActionMethodExecuted,,,,,,,Microsoft.AspNetCore.Mvc.ObjectResult,0.4602,,,
Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor,5,Buffering IAsyncEnumerable instance of type '{Type}'.,0,0HM5OO9VJD2HC:00000015,c83a59fe9c351349,,,,"Buffering IAsyncEnumerable instance of type 'Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[[***.DocumentAccount, ***, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]'.",GET AccountsOData/QueryAccounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,0,,,,,,,,1,BufferingAsyncEnumerable,,,,,,,,,,,"Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[[***.DocumentAccount, ***, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]"
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker,4,Executed action {ActionName} in {ElapsedMilliseconds}ms,0,0HM5OO9VJD2HC:00000015,c83a59fe9c351349,,,,Executed action ***Controller.QueryAccounts (***) in 3.0672ms,GET AccountsOData/QueryAccounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,1,,,,,,,,2,ActionExecuted,,,,,,,,3.0672,,,
Microsoft.AspNetCore.Routing.EndpointMiddleware,4,Executed endpoint '{EndpointName}',0,0HM5OO9VJD2HC:00000015,c83a59fe9c351349,,,,Executed endpoint '***Controller.QueryAccounts (***)',GET AccountsOData/QueryAccounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,1,,,,,,,,1,ExecutedEndpoint,,,,,,,,,,,
Microsoft.AspNetCore.Server.Kestrel,5,"Connection id ""{ConnectionId}"" completed keep alive response.",0,0HM5OO9VJD2HC:00000015,c83a59fe9c351349,,,,"Connection id ""0HM5OO9VJD2HC"" completed keep alive response.",GET AccountsOData/QueryAccounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,0,,,,,,,,9,ConnectionKeepAlive,,,,,,,,,,,
Microsoft.EntityFrameworkCore.Infrastructure,5,'{contextType}' disposed.,0,0HM5OO9VJD2HC:00000015,c83a59fe9c351349,,,,'AccountsContext' disposed.,GET AccountsOData/QueryAccounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,0,,,,,,,,10407,Microsoft.EntityFrameworkCore.Infrastructure.ContextDisposed,,,,,,,,,,,
Microsoft.AspNetCore.Hosting.Diagnostics,4,,0,0HM5OO9VJD2HC:00000015,c83a59fe9c351349,,,,Request finished in 8.9941ms 500 application/json,GET AccountsOData/QueryAccounts,c83a59fe9c351349,,,,il:2.16.0-18277,,,1,,,,,,,,2,,,,,,,,,8.9941,,,
```

### Include provider and version information

EF Core version: 5.0.1.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.Cosmos)
Target framework: NetCore 3.1
Operating system: Windows
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by smitpatel** [comment]
```C#
if (queryOptions.TryExtractFilter(nameof(ModelConstants.PartitionKey), out string partitionKey))
            {
                baseQuery = baseQuery.WithPartitionKey(partitionKey);
            }
            else if (queryOptions.TryExtractFilter(ModelConstants.SubscriptionId, out partitionKey))
            {
                baseQuery = baseQuery.WithPartitionKey(partitionKey);
            }
```
Above code is setting partition key conditionally, when that code sets partition key and you also specify in where then you will run into the error if they are not the same. Cosmos cannot run a query in 2 partitions in single query.

**Comment by stack111** [comment]
> Above code is setting partition key conditionally, when that code sets partition key and you also specify in where then you will run into the error if they are not the same. Cosmos cannot run a query in 2 partitions in single query.

Sure, I know that you can't run queries against to 2 partition keys at the same time. The problem I am demonstrating with the code is that the initial query for the partitionkey was different than what was being selected in the EFCore library. Essentially, the code in the controller or where clause should did not select partitionKey `6c0630f1-fbf7-4ce6-8669-e67c78b63da8` (given by the odata query string above).

In other words the execution steps seem to be:
1. Parse odata filters
2. Apply first .Where(resourceType == "accounts")
3. Apply Constant with specific partitionKey 9942d181-7ef6-43bb-a6ba-9d57cf587242
4. OData applies addition where clause in middleware
5. Select different partitionKey and materialize (toList or other) the query in middleware 

My guess (not sure if it's possible) is there is something in the linq query translation that selects the first partitionkey which matches by performing cross-partition query first. I would think it should apply the partitionKey first and then applying to the other criteria as part of query text. The reason I think so, is based on queries which succeed, the trace statement for the DB 
 command execution is:
 
```
Executing Sql Query [Parameters=[@__TypedProperty_1=?, @__TypedProperty_2=?]]
SELECT c
FROM root c
WHERE ((c["resourceType"] = "...") AND ((c["resourceGroup"] = @__TypedProperty_1) AND (c["resourceName"] = @__TypedProperty_2)))
```

This type of query doesn't include partitionkey as a where clause, but maybe there are other trace statements under Verbose which I don't have access to enable at the moment. Locally, I can see debug statement for the following, but I can't find it in production logs.

```
Microsoft.EntityFrameworkCore.Query[10107]
      Generated query execution expression:
      'queryContext => new QueryingEnumerable<DocumentAccount>(
          (CosmosQueryContext)queryContext,
          SqlExpressionFactory,
          QuerySqlGeneratorFactory,
          [Cosmos.Query.Internal.SelectExpression],
          Func<QueryContext, JObject, DocumentAccount>,
          ***.AccountsContext,
          "e58ec759-cdd4-42d9-af7b-807214f4a456", // <--- partition key value.
          False
      )'
```

For additional information, the DbConnect is running under scoped lifetime.

**Comment by smitpatel** [comment]
Apply where predicate to filter on particular partition key in a cross partition query is same as running query without that specific filter in a particular partition key. Running cross partition query is a lot more expensive than a single partition query. If you run a query with partition filter in a partition with a different value than what is being filtered then it will fetch no results.
Can you share a stand-alone repro which demonstrate the error? Can you run the same query yourself against CosmosClient which is a single partition query and also has partition filter in SQL with different partition key value and show that it still gives some result?

**Comment by stack111** [comment]
> Apply where predicate to filter on particular partition key in a cross partition query is same as running query without that specific filter in a particular partition key. Running cross partition query is a lot more expensive than a single partition query

I think the problem I had was that I could not figure out how to run a single partition query instead of cross partition query with EFCore. 

- `.WithPartitionKey(partitionKey)`
- `.Where(entity => entity.Partitionkey == partitionKey)`

> Can you share a stand-alone repro which demonstrate the error?

Can't share a public repo, that would take too long, but you can see the [code]https://msazure.visualstudio.com/One/_git/Azure-IoT-LocationBasedServices?version=GCa45b9a8a2ae221fe51e5b6afda8809a7f78e5745&path=%2Fsrc%2FIdentityService%2FStatelessIdentityService%2FControllers%2FAccountsODataController.cs).

>  Can you run the same query yourself against CosmosClient which is a single partition query and also has partition filter in SQL with different partition key value and show that it still gives some result?

We made a change to use Cosmos DB Client (V3) directly so you can see the intended behavior. [Controller](https://msazure.visualstudio.com/One/_git/Azure-IoT-LocationBasedServices?path=%2Fsrc%2FIdentityService%2FStatelessIdentityService%2FControllers%2FAccountsODataController.cs&version=GBmaster&_a=contents) and [Repository](https://msazure.visualstudio.com/One/_git/Azure-IoT-LocationBasedServices?path=%2Fsrc%2FIdentityService%2FStatelessIdentityService%2FCosmosDb%2FCosmosContainerRepository.cs&version=GBmaster&line=103&lineEnd=104&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents), I don't have the data to query on since it's production. But the following difference is using `CosmosDBRequestOptions` with a partitionKey specified.

**Comment by ajcvickers** [comment]
@stack111 Are you expecting that using **both** `WithPartitionKey` **and** a `Where` clause with different partition keys will result in a cross-partition query? Including both those partitions?

**Comment by stack111** [comment]
No actually, I was expecting a single partition query if I added `.WithPartitionKey(partitionKey)` or `.Where(entity => entity.Partitionkey == partitionKey)`. For the case of adding both and the queries are not the same partitionKey value, I think that should result in an error. 

I think the question is: what is the correct way to specify a single partition query?

**Comment by ajcvickers** [comment]
@stack111 Either way is correct.
