### ISSUE TITLE
Public service property on a base type fails model validation

### ISSUE THREAD

**Issue by mythjuha** [dotnet/efcore#23968]
I'm currently migrating an application from Telerik DataAccess to EF Core. In my project every entity inherits from a base class which has a property 'DbContext'. The DB context uses existing Telerik static classes to get the DbContext of an entity instance without the need to pass it around through your methods as a parameter. 

```
public DbContext DbContext
{
  get
  {
      return Telerik.OpenAccess.OpenAccessContextBase.GetContext(this)
  }
}
```

Is this possible with EF Core as well?

**Comment by roji** [comment]
@mythjuha it's difficult to understand exactly what your code is architected like... In EF Core, entity classes don't typically reference a DbContext instance; while it's probably possible to have all loaded entities from the database be injected with the DbContext that loaded them, this isn't the standard pattern for EF Core programming and probably result in various complications. I'd advise reading up on EF Core best practices and taking those into account when porting.

If you provide more details, with some more substantial code samples, we'd probably be able to provide more assistance.

**Comment by mythjuha** [comment]
hi @roji,

My code is using lots of triggers and events to chain actions and reactions. Certain changes for example should trigger a new Log entry to be created. As to not needing to hold or pass the DbContext in every event/trigger or being able to launch triggers from inside property setters, this approach was helpful as it meant i could access the dbcontext in my event handlers without issues.

I did see the option to inject the context during instance creation. Will need more management during new object creation then though.

**Comment by roji** [comment]
@mythjuha you should be able to inject your DbContext into all materialized entities via the [Tracked event](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/events) (for tracking queries) - @ajcvickers may have another suggestion.

**Comment by ajcvickers** [comment]
@mythjuha Following on from what @roji said, you can actually declare a `DbContext` property on your entity type:

```C#
public class Blog
{
    public int Id { get; set; }
    
    private DbContext Context { get; set; }
}
```

EF Core will the inject the context into this property whenever the entity is created from a query or whenever it is tracked by the context using `Add`, `Attach`, etc.

EF Core will never provider a static reference to a single DbContext since that would imply there is a single instance in the system, which goes against the philosophy of using a new DbContext instance for each unit of work.

**Comment by mythjuha** [comment]
> 
> 
> @mythjuha Following on from what @roji said, you can actually declare a `DbContext` property on your entity type:
> 
> ```cs
> public class Blog
> {
>     public int Id { get; set; }
>     
>     private DbContext Context { get; set; }
> }
> ```
> 
> EF Core will the inject the context into this property whenever the entity is created from a query or whenever it is tracked by the context using `Add`, `Attach`, etc.
> 
> EF Core will never provider a static reference to a single DbContext since that would imply there is a single instance in the system, which goes against the philosophy of using a new DbContext instance for each unit of work.

So just creating a property will make it managed by EF Core? No need to inject it into the constructor, etc... ? I see you've made it private. Is this a must? In any case this sounds really good, especially if it's also managed using Add/Remove/Attach/Detach.

I'll drop a message if I got it working.

**Comment by roji** [comment]
Closing this as answered, but if you run into any problems post back here and we'll reopen if necessary.

**Comment by mythjuha** [comment]
@roji This fails when using inheritance:

```
The service property 'DbContext' of type 'DbContext' cannot be added to the entity type 'SuperBlog' because there is another property of the same type. Ignore one of the properties using the [NotMapped] attribute or 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
```

Using the [NotMapped] or Ignore method makes the DbContext to be null.

**Comment by mythjuha** [comment]
@ajcvickers @roji 

My apologies if sounding pushy or rude. Past weeks experience just shows that you guys usually respond next day or next 2 at most (respect!). So because there's been no response yet, I'm thinking my previous response might be overlooked/missed due to the 'closed' status of the ticket. Hence i'm trying another 'highlight' of your names. Again, apologies if sounding impatient and you guys just been too busy.

**Comment by ajcvickers** [comment]
@mythjuha This looks like a bug.

Minimal repro:

```C#
public class BloggingContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }
    public DbSet<SuperBlog> SuperBlogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder options)
        => options.UseSqlite("Data Source=blogging.db");
}

public class Blog
{
    public int Id { get; set; }
    public int Value { get; set; }
     
    public DbContext DbContext { get; set; }
}
    
public class SuperBlog : Blog
{
    public string SuperInfo { get; set; }
}

public class Program
{
    public static void Main(string[] args)
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();
        }
    }
}
```

Exception:
```
System.InvalidOperationException: The service property 'DbContext' of type 'DbContext' cannot be added to the entity type 'SuperBlog' because there is another property of the same type. Ignore one of the properties using the [NotMapped] attribute or 'EntityTypeBuilder.Ignore' in 'OnM
odelCreating'.
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.ServicePropertyDiscoveryConvention.ProcessModelFinalizing(IConventionModelBuilder modelBuilder, IConventionContext`1 context)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelFinalizing(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelFinalizing(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FinalizeModel()
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_Dependencies()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureDeleted()
   at Program.Main(String[] args) in C:\Stuff\AllTogetherNow\FiveOh\Program.cs:line 57
```

**Comment by henrikdahl8240** [comment]
I suppose that Lazy loading without proxies should work with inheritance because otherwise it's obviously quite useless. Do you have an example of how to do it when entity types use intehitance?

**Comment by ajcvickers** [comment]
Turns out this is only a problem for _public_ service properties in a hierarchy, which are less common than private service properties. The workaround is to make the property private. If the property must be public, then a `[NotMapped]` public property can be used to reference the mapped private property.
