### ISSUE TITLE
EF tries to update a non-existing navigation property instead of inserting it

### ISSUE THREAD

**Issue by PawelGerr** [dotnet/efcore#23967]
EF tries to update a new instance of a navigation property instead of inserting it. This issue occurs if the navigation property is added to the collection of the parent entity only, i.e. the navigation property is not added to `DbContext` explicitly.

The issue is reproducible with SqlServer and Sqlite.

EF Core version: 5.0.2
Database provider:  Microsoft.EntityFrameworkCore.SqlServer 5.0.2
Target framework: .NET 5.0
Operating system: Win10 x64
IDE: Rider 2020.3

### Repro

Program.cs
```C#
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace NavPropsIssue
{
   class Program
   {
      static async Task Main(string[] args)
      {
         var options = new DbContextOptionsBuilder<DemoDbContext>()
                       .UseSqlServer("server=localhost;database=NavPropsIssue;integrated security=true")
                       .UseLoggerFactory(LoggerFactory.Create(b => b.AddConsole()))
                       .Options;

         await using var ctx = new DemoDbContext(options);
         await ctx.Database.EnsureCreatedAsync();

         var customer = new Customer { Id = Guid.NewGuid() };
         ctx.Add(customer);

         // Console.WriteLine(ctx.Entry(customer).State); // customer state: Added

         var order = new Order { Id = Guid.NewGuid() };
         customer.Orders.Add(order);

         // Console.WriteLine(ctx.Entry(order).State); // customer order: Detached
         // ctx.ChangeTracker.DetectChanges();
         // Console.WriteLine(ctx.Entry(order).State); // customer order: Modified

         // 2 last SQL statements:
         /*
            info: Microsoft.EntityFrameworkCore.Database.Command[20101]
                  Executed DbCommand (14ms) [Parameters=[@p0='?' (DbType = Guid)], CommandType='Text', CommandTimeout='30']
                  SET NOCOUNT ON;
                  INSERT INTO [Customers] ([Id])
                  VALUES (@p0);

            info: Microsoft.EntityFrameworkCore.Database.Command[20101]
                  Executed DbCommand (4ms) [Parameters=[@p2='?' (DbType = Guid), @p1='?' (DbType = Guid)], CommandType='Text', CommandTimeout='30']
                  SET NOCOUNT ON;
                  UPDATE [Orders] SET [CustomerId] = @p1
                  WHERE [Id] = @p2;
                  SELECT @@ROWCOUNT;
          */
         await ctx.SaveChangesAsync();
      }
   }

   public class DemoDbContext : DbContext
   {
      public DbSet<Customer> Customers { get; set; }
      public DbSet<Order> Orders { get; set; }

      public DemoDbContext(DbContextOptions<DemoDbContext> options)
         : base(options)
      {
      }
   }

   public class Customer
   {
      public Guid Id { get; set; }
      public List<Order> Orders { get; set; } = new();
   }

   public class Order
   {
      public Guid Id { get; set; }
   }
}
```

proj-file
```C#
<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
      <OutputType>Exe</OutputType>
      <TargetFramework>net5.0</TargetFramework>
   </PropertyGroup>

   <ItemGroup>
     <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.2" />
     <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
   </ItemGroup>

</Project>
```

### Exception

```
Unhandled exception. Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurre
ncy exceptions.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithoutPropagationAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at NavPropsIssue.Program.Main(String[] args) in E:\NavPropsUpdatedInsteadAdded\NavPropsIssue\Program.cs:line 48
   at NavPropsIssue.Program.Main(String[] args) in E:\NavPropsUpdatedInsteadAdded\NavPropsIssue\Program.cs:line 48
   at NavPropsIssue.Program.<Main>(String[] args)
```

**Comment by ajcvickers** [comment]
@PawelGerr This is because the entity is configured to use a generated key (the default for GUIDs) and yet you are setting an explicit key value. See https://docs.microsoft.com/en-us/ef/core/change-tracking/explicit-tracking for information about generated versus explicit keys, and https://docs.microsoft.com/en-us/ef/core/change-tracking/change-detection for how this impacts detecting changes.
