### ISSUE TITLE
Incorrect behavior of classes with the same name

### ISSUE THREAD

**Issue by AR1ES** [dotnet/efcore#23981]
I have two classes (keyless entities) with same names but different namespaces. Classes have the same properties with different signatures.

```C#
namespace ns1
{
  public class TestQuery
  {
    public int? MyValue { get; set; }
  }
}

namespace ns2
{
  public class TestQuery
  {
    public int MyValue { get; set; }
  }
}
```

DbContext:

```C#
  public class TestContext : DbContext
  {
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {

      var connectionString = "....";
      optionsBuilder.UseSqlServer(connectionString);
      optionsBuilder.EnableSensitiveDataLogging(true);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder) {
      base.OnModelCreating(modelBuilder);
      var mb = modelBuilder.Entity(typeof(ns1.TestQuery));

      mb.HasBaseType((Type)null);
      mb.HasNoKey();
      mb.ToTable(null);

      mb = modelBuilder.Entity(typeof(ns2.TestQuery));

      mb.HasBaseType((Type)null);
      mb.HasNoKey();
      mb.ToTable(null);
    }
  }
```

Running the example

```C#
  class Program
  {
    static void Main(string[] args) {
      using var db = new TestContext();
      var good1 = db.Set<ns1.TestQuery>().FromSqlRaw(@"SELECT 1 AS MyValue").ToList(); // OK
      var good2 = db.Set<ns2.TestQuery>().FromSqlRaw(@"SELECT 1 AS MyValue").ToList(); // OK
      var bad = db.Set<ns1.TestQuery>().FromSqlRaw(@"SELECT cast(null as int) AS MyValue").ToList(); // Exception
    }
  }
```

At the last statement I get exception:
```
Data is Null. This method or property cannot be called on Null values.

   at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
   at Microsoft.Data.SqlClient.SqlBuffer.get_Int32()
   at Microsoft.Data.SqlClient.SqlDataReader.GetInt32(Int32 i)
   at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ConsoleApp4.Program.<Main>d__0.MoveNext() in D:\Projects\ConsoleApp2\ConsoleApp4\Program.cs:line 18
```

`ns1.TestQuery.MyValue` is nullable, but exception says that Null is not allowed. As I suppose, there is some kind of cache that works by the name of the class without namespace.

EF Core version: 5.0.2
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10 Version	10.0.19042 Build 19042
IDE: Visual Studio 2019 16.8.3

**Comment by ajcvickers** [comment]
@smitpatel @AndriySvyryd I am able to reproduce this. The exception only happens when both entity types are included in the model.

**Comment by smitpatel** [comment]
If you have repro handy, can you print model also? That would help in narrowing down if model building is running into issue or query. Wrong type is getting picked up it seems which shouldn't happen in type based lookup.

**Comment by ajcvickers** [comment]
@smitpatel 

```
Model: 
  EntityType: TestQuery Keyless
    Properties: 
      MyValue (Nullable<int>)
        Annotations: 
          Relational:DefaultColumnMappings: System.Collections.Generic.SortedSet`1[Microsoft.EntityFrameworkCore.Metadata.Internal.ColumnMappingBase]
    Annotations: 
      ConstructorBinding: Microsoft.EntityFrameworkCore.Metadata.ConstructorBinding
      Relational:DefaultMappings: System.Collections.Generic.List`1[Microsoft.EntityFrameworkCore.Metadata.Internal.TableMappingBase]
      Relational:Schema: 
      Relational:TableName: 
      ServiceOnlyConstructorBinding: Microsoft.EntityFrameworkCore.Metadata.ConstructorBinding
  EntityType: TestQuery Keyless
    Properties: 
      MyValue (int) Required
        Annotations: 
          Relational:DefaultColumnMappings: System.Collections.Generic.SortedSet`1[Microsoft.EntityFrameworkCore.Metadata.Internal.ColumnMappingBase]
    Annotations: 
      ConstructorBinding: Microsoft.EntityFrameworkCore.Metadata.ConstructorBinding
      Relational:DefaultMappings: System.Collections.Generic.List`1[Microsoft.EntityFrameworkCore.Metadata.Internal.TableMappingBase]
      Relational:Schema: 
      Relational:TableName: 
      ServiceOnlyConstructorBinding: Microsoft.EntityFrameworkCore.Metadata.ConstructorBinding
Annotations: 
  ProductVersion: 5.0.2
  Relational:MaxIdentifierLength: 128
  Relational:RelationalModel: Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalModel
  SqlServer:ValueGenerationStrategy: IdentityColumn
```

![image](https://user-images.githubusercontent.com/1430078/105918221-6f57ab80-5fe8-11eb-989f-bcf7d88fbea3.png)
