### ISSUE TITLE
Invalid sql generated when combine paging and further subquery in a subquery

### ISSUE THREAD

**Issue by anranruye** [dotnet/efcore#24057]
Entities:
```C#
    public class Editor
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }

    public class Book
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public double Rating { get; set; }

        public int AuthorId { get; set; }

        [ForeignKey(nameof(AuthorId))]
        public Writer Author { get; set; }
    }

    public class Writer
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public double Rating { get; set; }

        public int OrganizationId { get; set; }

        public WriterOrganization Organization { get; set; }

        public List<Book> Books { get; set; }

        public int EditorId { get; set; }

        public Editor Editor { get; set; }
    }

    public class WriterOrganization
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public List<Writer> Writers { get; set; }
    }
```
Query:
```C#
            db.WriterOrganizations.Where(o => o.Id == 1).Select(o => new
            {
                o.Id,
                o.Name,
                Top5Writers = o.Writers.OrderByDescending(w => w.Rating).Take(5).Select(w => new
                {
                    w.Id,
                    w.Name,
                    Editor = w.Editor.Name
                }),
                Top10Books = o.Writers.SelectMany(w => w.Books).OrderByDescending(b => b.Rating).Take(10).Select(b => new
                {
                    b.Id,
                    b.Name,
                    Arthor = b.Author.Name,
                }),
                WriterCount = o.Writers.Count,
                BookCount = o.Writers.SelectMany(x => x.Books).Count()
            })/*.ToList()*/.FirstOrDefault();
```
Simplified query:
```C#
            db.WriterOrganizations.Where(o => o.Id == 1).Select(o => new
            {
                Top5Writers = o.Writers.OrderByDescending(w => w.Rating).Take(5).Select(w => new
                {
                    w.Id,
                    w.Name,
                    Editor = w.Editor.Name
                })
            }).FirstOrDefault();
```
or
```C#
            db.WriterOrganizations.Where(o => o.Id == 1).Select(o => new
            {
                Top10Books = o.Writers.SelectMany(w => w.Books).OrderByDescending(b => b.Rating).Take(10).Select(b => new
                {
                    b.Id,
                    b.Name,
                    Arthor = b.Author.Name,
                })
            }).FirstOrDefault();
```
Expected result:
EF Core should generate valid sql or can not generate any sql.

Actual result:
```
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'EditorId'.
Invalid column name 'Name'.
Invalid column name 'Rating'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
```

Reproduce conditions:
1. Use paging in the subquery, in this case, `.OrderByDescending(w => w.Rating).Take(5)` or `.OrderByDescending(b => b.Rating).Take(10)`
2. Further subquery for a single related entity, in this case, `Editor = w.Editor.Name` or `Arthor = b.Author.Name`
3. Call FirstOrDefault()/First()/Single()/SingleOrDefault() or async versions at last

Invalid sql generated by ef core:
```SQL
      SELECT [t].[Id], [t1].[Id], [t1].[Name], [t1].[Editor], [t1].[Id0]
      FROM (
          SELECT TOP(1) [w].[Id]
          FROM [WriterOrganizations] AS [w]
          WHERE [w].[Id] = 1
      ) AS [t]
      OUTER APPLY (
          SELECT [t].[Id], [t].[Name], [e].[Name] AS [Editor], [e].[Id] AS [Id0], [t].[Rating]
          FROM (
              SELECT TOP(5) [w0].[Id], [w0].[EditorId], [w0].[Name], [w0].[OrganizationId], [w0].[Rating]
              FROM [Writer] AS [w0]
              WHERE [t].[Id] = [w0].[OrganizationId]
              ORDER BY [w0].[Rating] DESC
          ) AS [t0]
          INNER JOIN [Editor] AS [e] ON [t].[EditorId] = [e].[Id]
      ) AS [t1]
      ORDER BY [t].[Id], [t1].[Rating] DESC, [t1].[Id], [t1].[Id0]
```

Workaround:
Uncomment `.ToList()` in the original query

EF Core version: 3.1.11/5.0.2/6.0 
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.8

**Comment by anranruye** [comment]
duplicate of #23720
