### ISSUE TITLE
Sql server: Wrong translation for default(DateTime)/default(Guid)/default(TimeSpan) in linq projection

### ISSUE THREAD

**Issue by anranruye** [dotnet/efcore#24075]
How to reproduce:
```C#
    dbContext.Set<AnyEntityType>().Select(x => new
    { 
        DateTime = default(DateTime), 
        x.SomeProperty 
    }).ToList();
```

Excepted result:
One of:
1. Can not translate linq query to sql command
2. Parameterize `default(DateTime)` like other variables
3. Client evaluate `default(DateTime)`
4. Convert returned string value to `DateTime` type

Actual result:
```
System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.DateTime'.
   at Microsoft.Data.SqlClient.SqlBuffer.get_DateTime()
   at Microsoft.Data.SqlClient.SqlDataReader.GetDateTime(Int32 i)
   at lambda_method5(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

Generated sql:
```SQL
      SELECT '0001-01-01T00:00:00.0000000' AS [DateTime], [x].[SomeProperty]
      FROM [TableName] AS [x]
```

EF Core version: 5.0.2
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.8

**Comment by ajcvickers** [comment]
Note from triage: we may be able to do something similar to what we do for spatial types. Then again, we may not. Brice to take a look.

**Comment by anranruye** [comment]
Here is a workaround:
```C#
    bool currentUserCanAccessBirthdayProperty = true; // or false
    DateTime defaultDateTime = default(DateTime);
    var persons = db.People.Select(x => new Person
    {
        Id = x.Id,
        Birthday = currentUserCanAccessBirthdayProperty ? x.Birthday : defaultDateTime 
    })
```
In fact, I already mentioned this in the original post:
> Parameterize default(DateTime) like a variable

**Comment by roji** [comment]
This has come up again for the SQL Server bool/bit mapping - the literal representation `CAST(1 AS BIT)` can cause an inferior query plan in some scenarios (#27150).

Stepping back...

* This isn't a SQL Server-specific problem; it can happen anywhere where the bare SQL literal representation of a type, when evaluated, yields a different type by default - I've run into this several times in PostgreSQL.
* Our approach for dealing with this up to now has been to add explicit CAST in the SQL literal generation (e.g. in numeric types, bool). We could continue handling the problem in a similar way for DateTime/Guid/TimeSpan/bool, but there are some drawbacks:
  * This produces needlessly verbose SQL: the CAST is necessary for literal projections, but isn't necessary in other contexts (e.g. when compared to a column).
  * #27150 shows that the extra cast can cause performance issues.
* We could add a flag on RelationalTypeMapping, which allows provider writers to specify whether the literal representation roundtrips back to the same type (e.g. for int), or whether it doesn't (for bit).
* In the query pipeline, we'd check that flag for literal projections and add the CAST for that case, but not for other cases. This may even be usable in other cases where a literal's type mapping cannot be inferred (e.g. a parameter to a database function which accepts any parameter type, and therefore doesn't assign a specific typem apping?).

**Comment by smitpatel** [comment]
> This produces needlessly verbose SQL: the CAST is necessary for literal projections, but isn't necessary in other contexts (e.g. when compared to a column).

Cast is not unnecessary for all non-projection cases. When types are not implicitly convertible without loss, explicit cast is needed. So #15586 is unavoidable.

**Comment by roji** [comment]
@smitpatel which scenario do you have in mind (can you give an example)?

**Comment by roji** [comment]
Note this "interesting" case on SQL Server:

```sql
-- The following works fine:
SELECT CAST('2020-01-01 12:00' AS datetime2) AT TIME ZONE 'W. Europe Standard Time';

-- The following errors: Argument data type varchar is invalid for argument 1 of AT TIME ZONE function
SELECT '2020-01-01 12:00' AT TIME ZONE 'W. Europe Standard Time';
```

So this is another (odd) scenario where explicit SQL typing needs to be added. At this point I'm just doing it in the method translator in #27168.

**Comment by Suchiman** [comment]
I've also just run into this. For anyone else looking for a workaround, adding `(DateTime)(object)` yields the desired SQL, e.g.:
```csharp
    dbContext.Set<AnyEntityType>().Select(x => new
    { 
        DateTime = (DateTime)(object)DateTime.MinValue, 
        x.SomeProperty 
    }).ToList();
```
SQL
```sql
      SELECT CAST('0001-01-01T00:00:00.0000000' AS datetime2) AS [DateTime], [x].[SomeProperty]
      FROM [TableName] AS [x]
```

**Comment by Elanis** [comment]
Same things happens when you configure a DateTime class field to be mapped to a column on SQL Server with type `datetime` .
It uses DateTime.MinValue as a default value, which is invalid for SQL `datetime` type (min value is 1783-01-01).

When applying a migration that would create that column and set default values, you would have an error message about invalid casting from varchar to datetime.

**Comment by Tragetaschen** [comment]
I saw this issue too late and created another reproduction, this time with Guids:

https://github.com/Tragetaschen/efcore-nullable-guid-string

**Comment by jdaigle** [comment]
Still reproduces on **EF Core 10 / SQL Server**.

Minimal repro:

```csharp
public class Widget
{
    public int Id { get; set; }
}

public class Dto
{
    public int Id { get; set; }
    public DateTime From { get; set; }
    public DateTime To { get; set; }
}

// ...
db.Widgets.Add(new Widget());   // must have at least one row
await db.SaveChangesAsync();

var rows = await db.Widgets
    .Select(w => new Dto
    {
        Id = w.Id,
        From = DateTime.MinValue,   // == default(DateTime)
        To = DateTime.MaxValue,
    })
    .ToListAsync();
```

Generated SQL — the constants are inlined as bare string literals rather than typed/parameterized values:

```sql
SELECT [w].[Id], '0001-01-01T00:00:00.0000000' AS [From], '9999-12-31T23:59:59.9999999' AS [To]
FROM [Widgets] AS [w]
```

Throws on materialization:

```
System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.DateTime'.
   at Microsoft.Data.SqlClient.SqlBuffer.get_DateTime()
   at Microsoft.Data.SqlClient.SqlDataReader.GetDateTime(Int32 i)
```

Same behavior for `DateTime.MaxValue` and other `DateTime`/`Guid`/`TimeSpan` constants. EF6 parameterized these, so this is a translation regression for code ported from EF6.
