### ISSUE TITLE
How to add migrations for Entity Framework in a Xamarin Forms project?

### ISSUE THREAD

**Issue by SzabKel** [dotnet/efcore#24083]
I am reacting to [this](https://stackoverflow.com/a/60657099/840315).

I am trying to get the EF migrations to work in a Xamarin Forms project. I have a DbContext for a SQLite database:
```
    public class TestDbContext : DbContext
    {
        public DbSet<Item> Items { get; set; }

        public TestDbContext()
        {
            SQLitePCL.Batteries_V2.Init();

            this.Database.EnsureCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            string dbPath = Path.Combine(FileSystem.AppDataDirectory, "testDb.db3");

            optionsBuilder
                .UseSqlite($"Filename={dbPath}");
        }
    }
```

I installed the `Microsoft.EntityFrameworkCore.Tools` nuget for the standard library, but it did not work. Starting from [this][1], I added a [Dummy][2] .NET Core project.

 1. I referenced the .NET Standard library (2.1) in the Dummy (Xamarin Forms project)
 2. I installed the `Microsoft.EntityFrameworkCore.Sqlite` and `Microsoft.EntityFrameworkCore.Tools` nuget packages into the dummy project as well
 3. I implemented an `IDesignTimeDbContextFactory` in the .net standard library like this:
```C#
    public class DesignTimeFactory : IDesignTimeDbContextFactory<TestDbContext>
    {
        public TestDbContext CreateDbContext(string[] args)
        {
            return new TestDbContext();
        }
    }
```

When I run the command `PM> Add-Migration InitialCreate -P XamarinEFTest -S EFDummy` I get an exception:
```
Build started...
Build succeeded.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Xamarin.Essentials.NotImplementedInReferenceAssemblyException: This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.
   at Xamarin.Essentials.FileSystem.get_PlatformAppDataDirectory()
   at Xamarin.Essentials.FileSystem.get_AppDataDirectory()
   at XamarinEFTest.TestDbContext.OnConfiguring(DbContextOptionsBuilder optionsBuilder) in C:\Users\szabk\source\repos\XamarinEFTest\XamarinEFTest\XamarinEFTest\TestDbContext.cs:line 24
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_Dependencies()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
   at XamarinEFTest.TestDbContext..ctor() in C:\Users\szabk\source\repos\XamarinEFTest\XamarinEFTest\XamarinEFTest\TestDbContext.cs:line 19
   at XamarinEFTest.DesignTimeFactory.CreateDbContext(String[] args) in C:\Users\szabk\source\repos\XamarinEFTest\XamarinEFTest\XamarinEFTest\DesignTimeFactory.cs:line 12
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContextFromFactory(Type factory, Type contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass16_0.<FindContextFactory>b__1()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Exception has been thrown by the target of an invocation.
```

I have VS 2019 16.8.4, I created the test xamarin project from the layout template with the slider menu.

What do I need to do?

Maybe I need to setup the Core project with a different SQLite driver and with a different DesignTimeFactory? But how would this work? I need the migrations to work in the phone in the end.

  [1]: https://stackoverflow.com/a/60657099/840315
  [2]: https://docs.microsoft.com/en-us/ef/core/cli/powershell#other-target-frameworks

### Include provider and version information

EF Core version: 3.1
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: Xamarin Forms .NET Standard 2.1
Operating system: Windows 10
IDE: VS 2019 16.8.4

**Comment by SzabKel** [comment]
Thanks to this [answer](https://stackoverflow.com/a/66100100/840315), I could implement a different connection string when I am generating migrations.

```
    public class TestDbContext : DbContext
    {
        private readonly string _connectionString;

        public DbSet<Item> Items { get; set; }

        public TestDbContext(string connectionString)
        {
            _connectionString = connectionString;
            SQLitePCL.Batteries_V2.Init();

            Database.EnsureCreated();

            Database.Migrate();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlite(_connectionString);
            }
        }
    }

And use the DesignTimeFactory like this:
```
    public class DesignTimeFactory : IDesignTimeDbContextFactory<TestDbContext>
    {
        /// <summary>
        ///  Used to generate migrations
        /// </summary>
        /// <param name="args"></param>
        /// <returns></returns>
        public TestDbContext CreateDbContext(string[] args)
        {
            return new TestDbContext("Data Source=migrations.db3");
        }
    }
```

And in the services I just use the android/iOS connection string:
```
        private TestDbContext CreateContext()
        {
            var envPath = FileSystem.AppDataDirectory;
            string dbPath = Path.Combine(envPath, "testDb.db3");
            return new TestDbContext($"Filename={dbPath}");
        }
```
