### ISSUE TITLE
Unable to cast object of type 'System.Int64' to type 'System.Int32'.

### ISSUE THREAD

**Issue by wangengzheng** [dotnet/efcore#24081]
## File a bug

[Similar, but not all](https://github.com/dotnet/efcore/issues/7558)

#### in my linqpad 
```C#

async Task Main()
{
	var db = new TestDbContext();
	//await db.Database.EnsureDeletedAsync();
	try
	{
		await db.Database.EnsureCreatedAsync();
	}
	catch (InvalidCastException ex) {
		//Unable to cast object of type 'System.Int64' to type 'System.Int32'.
		Console.WriteLine("in exception");
	}
	
	db.Database.EnsureCreated().Dump();
	
	
	db.Stores.Dump();
}

public class TestDbContext : DbContext
{
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	{
		optionsBuilder.UseMySQL("server=localhost;Database=test_specification;userid=root;password=123456;pooling=true;CharSet=utf8;port=3306;sslmode=Required");
		//optionsBuilder.UseLoggerFactory(LoggerFactoryProvider.LoggerFactoryInstance);
		base.OnConfiguring(optionsBuilder);
	}

protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		base.OnModelCreating(modelBuilder);
		
		modelBuilder.Entity<Product>().HasData(ProductSeed.Get());
	}
}


public class Product
{
	public int Id { get; set; }
	public string? Name { get; set; }
}

public class ProductSeed
{
	public static List<Product> Get()
	{
		var products = new List<Product>();

		for (int i = 1; i < 100; i = i + 2)
		{
			products.Add(new Product()
			{
				Id = i,
				Name = $"Product {i}",				
			});
			products.Add(new Product()
			{
				Id = i + 1,
				Name = $"Product {i + 1}",				
			});
		}

		return products;
	}
}
```

### Include stack traces

```

StackTrace | at MySql.Data.EntityFrameworkCore.MySQLDatabaseCreator.<HasTablesAsync>b__24_0(MySQLServerConnection connection, CancellationToken ct)   at MySql.Data.EntityFrameworkCore.Storage.Internal.MySQLExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreatedAsync(CancellationToken cancellationToken)   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreatedAsync(CancellationToken cancellationToken)   at UserQuery.Main(), line 8

Message |Unable to cast object of type 'System.Int64' to type 'System.Int32'.

Source | MySql.Data.EntityFrameworkCore

```

### Include verbose output

Please include `--verbose` output when filing bugs about the `dotnet ef` or Package Manager Console tools.

Use triple-tick fences for tool output. For example:

```
output (database is created)
in exception
False
```

### Include provider and version information

EF Core version: 3.1.1
Database provider: Microsoft.EntityFrameworkCore.Mysql   mysql.data.entityframework8.0.21
Target framework: .NetCore3.1
Operating system: windows 
IDE: (e.g. linqpad 6.11.11)

**Comment by wangengzheng** [comment]
![image](https://user-images.githubusercontent.com/12171338/107170854-37e8e780-6976-11eb-974d-26be1227b614.png)
mysql general log

**Comment by ajcvickers** [comment]
@wangengzheng Can you please post the full stack trace of the exception thrown?

**Comment by wangengzheng** [comment]
@ajcvickers  I'm so sorry I'm late

**this is full stack trace**

System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'System.Int64' to type 'System.Int32'.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.CompilerServices.CastHelpers.Unbox(Void* toTypeHnd, Object obj)
   at MySql.Data.EntityFrameworkCore.MySQLDatabaseCreator.<<HasTablesAsync>b__24_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MySql.Data.EntityFrameworkCore.Storage.Internal.MySQLExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.<EnsureCreatedAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.<EnsureCreatedAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at dotnetefcoreissues24081.Program.<Main>d__0.MoveNext() in D:\github\test\dotnetefcoreissues24081\Program.cs:line 14

**Comment by wangengzheng** [comment]
![image](https://user-images.githubusercontent.com/12171338/108299392-375d0780-7153-11eb-9808-a7969cc3fd5b.png)

**Comment by wangengzheng** [comment]
When the database already exists, an error will be reported

**Comment by ajcvickers** [comment]
@wangengzheng The error is coming from `MySql.Data.EntityFrameworkCore.MySQLDatabaseCreator`, which is the EF Core provider for MySQL from Oracle. This issue should be reported to Oracle. You may want to give the open-source [Pomelo MySQL provider](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/) which can be a better experience than the provider from Oracle.
