### ISSUE TITLE
InvalidOperationException when projection is used with OData

### ISSUE THREAD

**Issue by mhamri** [dotnet/efcore#24092]
here is the repo: https://github.com/mhamri/ef-int32-bug

this setup was working on ef 3.x but now I'm trying to update to ef 5 but had no luck bcs of this bug

I also provide the setting to swap between the ef3 and ef5 to test that the same code was working on ef3.

related bugs:
#24047
#24079

### code

I am writing the copy from repo here, but better check it there

**please note these codes are from this folder `src/Axceligent.Research.Dotnet5AndOdata`**
**please ignore the `console` project**

Entities:

```C#
public class BookStore
    {
        public int StoreId { get; set; }
        public int BookId { get; set; }

        public Store Store { get; set; }
        public Book Book { get; set; }
    }

    public class Book
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int AuthorId { get; set; }
        public Person Author { get; set; }

        public ICollection<BookStore> BookStore { get; set; }
    }

    public class Person
    {
        public int Id { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public ICollection<Store> Stores { get; set; }
        public ICollection<Book> Books { get; set; }

    }

    public class Store
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public int OwnerId { get; set; }
        public Person Owner { get; set; }

        public ICollection<Book> Books { get; set; }
        public ICollection<BookStore> BookStore { get; set; }

    }
```

context: 
```C#
public class MyContext : DbContext
    {
        public MyContext(DbContextOptions<MyContext> options)
            : base(options)
        {
        }
        public DbSet<Person> People { get; set; }
        public DbSet<Store> Stores { get; set; }
        public DbSet<Book> Books { get; set; }
        public DbSet<BookStore> BooksStores { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Person>(b =>
            {
                b.HasKey(p => p.Id);
                b.Property(p => p.FirstName).HasMaxLength(50);
                b.Property(p => p.LastName).HasMaxLength(50);

                b.HasMany(p=>p.Stores).WithOne(p => p.Owner).HasForeignKey(p => p.OwnerId).OnDelete(DeleteBehavior.Cascade);
                b.HasMany(p=>p.Books).WithOne(p => p.Author).HasForeignKey(p => p.AuthorId).OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity<Store>(b =>
            {
                b.HasKey(p => p.Id);
                b.Property(p => p.Name).HasMaxLength(50);
            });

            modelBuilder.Entity<Book>(b =>
            {
                b.HasKey(p => p.Id);
                b.Property(p => p.Name).HasMaxLength(50);
            });

            modelBuilder.Entity<BookStore>(b =>
            {
                b.HasKey(p => new {p.BookId, p.StoreId});

                b.HasOne(pt => pt.Book)
                    .WithMany(p => p.BookStore)
                    .HasForeignKey(pt => pt.BookId);

                b.HasOne(pt => pt.Store)
                    .WithMany(t => t.BookStore)
                    .HasForeignKey(pt => pt.StoreId).OnDelete(DeleteBehavior.ClientNoAction);
            });
           
        }
    }
```

StoresProjectedController.cs
```C#

...
        [HttpGet]
        [EnableQuery]
        [ProducesResponseType(typeof(IQueryable<Store>), StatusCodes.Status200OK)]
        public IActionResult Get()
        {
            AddSampleDataToDb();
            var result = _context.Stores.AsQueryable();

            var resultModel = _mapper.ProjectTo<StoreModel>(result);

            Console.WriteLine(resultModel.Expression.ToReadableString());

            return Ok(resultModel);
        }
...

```

Query failes : 

`http://localhost:63273/odata/StoresSimple?$select=Id&$expand=owner($select=id)`

### stack traces

Include the full exception message and stack trace for any exception you encounter.

Use triple-tick fences for stack traces. For example:

```
System.InvalidOperationException: Rewriting child expression from type 'System.Int32' to type 'System.Nullable`1[System.Int32]' is not allowed, because it would change the meaning of the operation. If this is intentional, override 'VisitUnary' and change it to allow this rewrite.
   at System.Linq.Expressions.ExpressionVisitor.ValidateChildType(Type before, Type after, String methodName)
   at System.Linq.Expressions.ExpressionVisitor.ValidateUnary(UnaryExpression before, UnaryExpression after)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryOptimizingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Infrastructure.AsyncEnumerableReader.ReadInternal[T](Object value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncEnumerable(ActionContext context, ObjectResult result, Object asyncEnumerable, Func`2 reader)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### provider and version information

EF Core version: 5.0.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows
IDE: Visual Studio 2019 16.8.4

**Comment by trojanmartin** [comment]
Is there any workaround for this issue in EF Core 5.0?

**Comment by Krnlsoft** [comment]
Damn... It works with Microsoft.EntityFrameworkCore 6.0.0-preview.7.21378.4

**Comment by edelCustodio** [comment]
same for me, I'm using the `5.0.5` version of EF Core and I'm getting the same issue like @mhamri

**Comment by maumar** [comment]
depends on https://github.com/dotnet/efcore/issues/25262, moving to MQ

**Comment by maumar** [comment]
Verified this works on current bits (as has already been reported by a customer). Problem was that EF wasn't correctly compensating for nullability change of a non-nullable property projected from a left join (after expand). Workaround is to make that property nullable.
