### ISSUE TITLE
The type 'City' cannot be configured as non-owned because an owned entity type with the same name already exists.

### ISSUE THREAD

**Issue by pantonis** [dotnet/efcore#24105]
Based on this excellent example from Vladimir Khorikov https://enterprisecraftsmanship.com/posts/nesting-value-object-inside-entity where he covers a very frequent scenario I am getting an error when I am trying to create migration in EF Core 5. 

```C#
    public class User : Entity
    {
        public string Name { get; protected set; }
        public int Age { get; set; }

        private readonly IList<CityInUser> cities = new List<CityInUser>();
        public IReadOnlyList<City> Cities => cities.Select(x => x.City).ToList();

        public User()
        {
        }

        public User(string name, int age)
        {
            Name = name;
            Age = age;
        }

        public void AddCity(City city)
        {
            cities.Add(new CityInUser(city, this));
        }
    }

    public sealed class City : ValueObject<City>
    {
        public string Name { get; }
        public bool IsEnabled { get; }

        public City()
        {
        }

        public City(string name, bool isEnabled)
        {
            Name = name;
            IsEnabled = isEnabled;
        }

        protected override bool EqualsCore(City other)
        {
            return Name == other.Name && IsEnabled == other.IsEnabled;
        }

        protected override int GetHashCodeCore()
        {
            return Name.GetHashCode() ^ IsEnabled.GetHashCode();
        }
    }

    public class CityInUser : Entity
    {
        public City City { get; protected set; }
        public User User { get; protected set; }

        public CityInUser()
        {
        }

        public CityInUser(City city, User user)
        {
            City = city;
            User = user;
        }
    }

    public class MyDbContext : DbContext
    {
        public MyDbContext(DbContextOptions options)
            : base(options)
        {
		
        }

        public virtual DbSet<User> User { get; set; }


        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<User>(x =>
            {
                x.ToTable("User");
                x.HasKey(k => k.Id);

                x.Property(p => p.Name).IsRequired().HasMaxLength(128);
                x.Property(p => p.Age);

                x.OwnsMany(p => p.Cities, a =>
                {
                    a.ToTable("City");
                    a.WithOwner().HasForeignKey("UserId");
                    a.Property<long>("Id");
                    a.HasKey("Id");
                });
            });

            modelBuilder.Entity<CityInUser>(x =>
            {
                x.HasOne(p=> p.User).WithMany();
                x.HasOne(p=> p.City).WithMany();
            });
        }
    }
}

```

### Include stack traces

```
C:\Program Files\dotnet\dotnet.exe exec --depsfile "C:\Users\devpc\Documents\Visual Studio 2019\Projects\ValueEntity\ValueEntity\ValueEntity.Console\bin\Debug\net5\ValueEntity.Console.deps.json" --additionalprobingpath C:\Users\devpc\.nuget\packages --runtimeconfig "C:\Users\devpc\Documents\Visual Studio 2019\Projects\ValueEntity\ValueEntity\ValueEntity.Console\bin\Debug\net5\ValueEntity.Console.runtimeconfig.json" C:\Users\devpc\.nuget\packages\microsoft.entityframeworkcore.tools\5.0.3\tools\netcoreapp2.0\any\ef.dll migrations add InitialCreate --json --verbose --no-color --prefix-output --assembly "C:\Users\devpc\Documents\Visual Studio 2019\Projects\ValueEntity\ValueEntity\ValueEntity.Console\bin\Debug\net5\ValueEntity.dll" --startup-assembly "C:\Users\devpc\Documents\Visual Studio 2019\Projects\ValueEntity\ValueEntity\ValueEntity.Console\bin\Debug\net5\ValueEntity.Console.dll" --project-dir "C:\Users\devpc\Documents\Visual Studio 2019\Projects\ValueEntity\ValueEntity\ValueEntity\\" --language C# --working-dir "C:\Users\devpc\Documents\Visual Studio 2019\Projects\ValueEntity" --root-namespace ValueEntity
Using assembly 'ValueEntity'.
Using startup assembly 'ValueEntity.Console'.
Using application base 'C:\Users\devpc\Documents\Visual Studio 2019\Projects\ValueEntity\ValueEntity\ValueEntity.Console\bin\Debug\net5'.
Using working directory 'C:\Users\devpc\Documents\Visual Studio 2019\Projects\ValueEntity\ValueEntity\ValueEntity.Console'.
Using root namespace 'ValueEntity'.
Using project directory 'C:\Users\devpc\Documents\Visual Studio 2019\Projects\ValueEntity\ValueEntity\ValueEntity\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Found IDesignTimeDbContextFactory implementation 'MyDbContextFactory'.
Found DbContext 'MyDbContext'.
Finding application service provider in assembly 'ValueEntity.Console'...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Using DbContext factory 'MyDbContextFactory'.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: The type 'City' cannot be configured as non-owned because an owned entity type with the same name already exists.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(TypeIdentity& type, ConfigurationSource configurationSource, Nullable`1 shouldBeOwned)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(Type type, ConfigurationSource configurationSource, Nullable`1 shouldBeOwned)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder.FindRelatedEntityType(Type relatedType, String navigationName)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.HasOne[TRelatedEntity](Expression`1 navigationExpression)
   at ValueEntity.Infrastructure.EntityFramework.MyDbContext.<>c.<OnModelCreating>b__6_1(EntityTypeBuilder`1 x) in C:\Users\devpc\Documents\Visual Studio 2019\Projects\ValueEntity\ValueEntity\ValueEntity\Infrastructure\EntityFramework\MyDbContext.cs:line 51
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity[TEntity](Action`1 buildAction)
   at ValueEntity.Infrastructure.EntityFramework.MyDbContext.OnModelCreating(ModelBuilder modelBuilder) in C:\Users\devpc\Documents\Visual Studio 2019\Projects\ValueEntity\ValueEntity\ValueEntity\Infrastructure\EntityFramework\MyDbContext.cs:line 48
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetRelationalService[TService](IInfrastructure`1 databaseFacade)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at ValueEntity.Infrastructure.EntityFramework.MyDbContext..ctor(DbContextOptions options) in C:\Users\devpc\Documents\Visual Studio 2019\Projects\ValueEntity\ValueEntity\ValueEntity\Infrastructure\EntityFramework\MyDbContext.cs:line 13
   at ValueEntity.Console.EntityFramework.MyDbContextFactory.CreateDbContext(String[] args) in C:\Users\devpc\Documents\Visual Studio 2019\Projects\ValueEntity\ValueEntity\ValueEntity.Console\EntityFramework\MyDbContextFactory.cs:line 30
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContextFromFactory(Type factory, Type contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass13_2.<FindContextTypes>b__9()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Exception has been thrown by the target of an invocation.
```

### Include provider and version information

EF Core version: EF Core 5.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: ..NET 5.0
Operating system: Win10
IDE: Visual Studio 2019 16.8.2

**Comment by pantonis** [comment]
@ajcvickers @smitpatel Any update on this one?

**Comment by smitpatel** [comment]
```
modelBuilder.Entity<CityInUser>(x =>
            {
                x.HasOne(p=> p.User).WithMany();
                x.HasOne(p=> p.City).WithMany();
            });
```
In above code you are configuring navigation to `City` as if it is regular entity but in `User` class you are configuring it as owned entity. You cannot configure same CLR type as owned/non-owned entity in same model. Exception message also indicates that. You need to determine how do you want to use `City` in your model and change your model configuration accordingly.

**Comment by pantonis** [comment]
@smitpatel I found no other way of setting the relationship between City and User. City is a value object and is owned by User. How can I set the relationship between City and User?

**Comment by smitpatel** [comment]
```C#
modelBuilder.Entity<User>().HasMany<CityInUser>("cities").WithOne(e => e.User);
modelBuilder.Entity<CityInUser>().OwnsOne(e => e.City);
```

City is a value object owned by `CityInUser` and CityInUser has one-to-many relationship with `User`.

**Comment by pantonis** [comment]
@smitpatel I changed it as you suggested
```
modelBuilder.Entity<User>(x =>
            {
                x.ToTable("User");
                x.HasKey(k => k.Id);

                x.Property(p => p.Name).IsRequired().HasMaxLength(128);
                x.Property(p => p.Age);

                x.HasMany<CityInUser>("cities").WithOne(e => e.User);
            });

            modelBuilder.Entity<CityInUser>(x =>
            {
                x.OwnsOne(e => e.City);
            });
```

 and I'm getting the following error:

```
 ---> System.InvalidOperationException: Unable to determine the relationship represented by navigation 'User.Cities' of type 'IReadOnlyList<City>'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidatePropertyMapping(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.SqlServer.Internal.SqlServerModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.ValidatingConvention.ProcessModelFinalized(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelFinalized(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelFinalized(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FinalizeModel()
```

**Comment by smitpatel** [comment]
You need to ignore that navigation as indicated in error message. That property exists only in your domain since you added another wrapper entity in between.

**Comment by pantonis** [comment]
But if I skip that navigation then there is not way to access cities of the user. I have been trying to make this work for the last week. Cost me lots of hours and money. Didn't find a way or even an example of how this works in EF Core 5 using DDD. I mean it is about a very frequent scenario with many to many (if you didn't understand the requirement here please check the below example which is more clear.

```
public class Order : Entity
{
    private IList<LineInOrder> _lines;
 
    public IReadOnlyList<OrderLine> Lines =>
        _lines
            .OrderBy(x => x.Position)
            .Select(x => x.Line)
            .ToList();
}
 
internal class LineInOrder : Entity
{
    public int Position { get; set; }
    public Order Order { get; private set; }
    public OrderLine Line { get; private set; }
}
 
public sealed class OrderLine : ValueObject<OrderLine>
{
    public int Quantity { get; }
    public Product Product { get; }
    public decimal Price { get; }
}
```
If only one could give the full implemenation of the ORM here. I am sure that other people have the same issue.
I am disappointed and tired.

**Comment by anranruye** [comment]
@pantonis For your model, you should use:
```C#
            modelBuilder.Entity<User>(x =>
            {
                x.OwnsMany<CityInUser>("cities", a =>
                {
                    a.ToTable("City");
                    a.WithOwner().HasForeignKey("UserId");
                    a.Property<long>("Id");
                    a.HasKey("Id");
           
                    a.OwnsOne(e => e.City);
                });
                x.Ignore(u => u.Cities)
            });
```

However, there are simpler ways to acheive you goal with ef core. You don't need `CityInUser` class, you can use `City` class directly:
```C#
    public class User : Entity
    {
        public string Name { get; protected set; }
        public int Age { get; set; }

        public List<City> Cities { get; set; }

        public User()
        {
        }

        public User(string name, int age)
        {
            Name = name;
            Age = age;
        }

        public void AddCity(City city)
        {
            Cities.Add(city);
        }
    }

    public sealed class City : ValueObject<City>
    {
        public string Name { get; }
        public bool IsEnabled { get; }

        public City()
        {
        }

        public City(string name, bool isEnabled)
        {
            Name = name;
            IsEnabled = isEnabled;
        }

        protected override bool EqualsCore(City other)
        {
            return Name == other.Name && IsEnabled == other.IsEnabled;
        }

        protected override int GetHashCodeCore()
        {
            return Name.GetHashCode() ^ IsEnabled.GetHashCode();
        }
    }

    public class MyDbContext : DbContext
    {
        public MyDbContext(DbContextOptions options)
            : base(options)
        {
		
        }

        public virtual DbSet<User> User { get; set; }


        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<User>(x =>
            {
                x.ToTable("User");
                x.HasKey(k => k.Id);

                x.Property(p => p.Name).IsRequired().HasMaxLength(128);
                x.Property(p => p.Age);

                x.OwnsMany(p => p.Cities, a =>
                {
                    a.ToTable("City");
                    a.WithOwner().HasForeignKey("UserId");
                    a.Property<long>("Id");
                    a.HasKey("Id");
                });
            });
        }
    }
}
```

**Comment by pantonis** [comment]
@anranruye Thanks for your suggestion. The first part of your code does not produce the result I need. It creates City table with Id, UserId1 and UserId columns only and the User table with Id, Name and Age.

I cannot use the second suggestion because cities are used by other users. as well.

**Comment by anranruye** [comment]
@pantonis 

It seems what you are looking for is different from the post you reference. In that post, the author introduced a one-to-many relationship, not a many-to-many relationship. Notice that you need three tables for a many-to-many relationship.

If you really need many-to-many relationship, you should use regular entities rather than owned entities. You can use field only property(private field or property which has no corresponding public member) or shadow property to hide primary key property and foriegn key property outside the entities which have value object semantics. 

A digression, you can also take advantages of new C# 9 record type if you use .NET 5. 

See https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key
https://docs.microsoft.com/en-us/ef/core/modeling/shadow-properties
https://docs.microsoft.com/en-us/ef/core/modeling/backing-field?tabs=data-annotations#field-only-properties
