### ISSUE TITLE
"Argument types do not match" when using ternary operator on int in Select statement

### ISSUE THREAD

**Issue by Erythnul** [dotnet/efcore#24119]
## File a bug

Similar but potentially different to #23802, this is on 5.0.3. 

In this case we use an extra check to structure our objects better while we select them, our legacy Database is badly structured, so I use OwnsOne to add a layer that should've been a different table within the entity. Other checks in the system validate that the database can not be brought into a state where the filter field is filled and the rest of the data is missing, so the actual null assignment never happens (but is ugly).

Problem occurs when returning from TryOptimizeMemberAccessOverConditional in Microsoft.EntityFrameworkCore.Query.Internal.QueryOptimizingExpressionVisitor,
What I believe is part of the issue here:
TryOptimizeMemberAccessOverConditional converts the non-nullable value type to a nullable value type, changing the argument types when returning to VisitUnary

Example below is a simplification and abstraction but should reproduce the issue well.
Also see https://github.com/Erythnul/EFCoreIssueReproduction for a fully runnable reproduction with database migrations etc.

### Entities

```C#
public class Order
{
    public Guid Id { get; set; }

    public Address? ShippingAddress { get; set; }
}

public class Address
{
    public Guid OrderId { get; set; }

    public string? Street { get; set; }
    public int HouseNumber { get; set; }
    public string? City { get; set; }
    public string? Country { get; set; }
}

public class OrderConfiguration : IEntityTypeConfiguration<Order>
{
    public void Configure(EntityTypeBuilder<Order> builder)
    {
        builder.HasKey(x => x.Id);

        builder.HasData(new Order
        {
            Id = Guid.Parse("00000000-0000-0000-0000-000000000001")
        });

        builder.OwnsOne(o => o.ShippingAddress, o => o.HasData(new Address
        {
            OrderId = Guid.Parse("00000000-0000-0000-0000-000000000001"),
            Street = "TestStreet",
            HouseNumber = 3,
            City = "TestCity",
            Country = "TestCountry"
        }));
    }
}
```

### Executing code

```C#
//None of these below work:
var orderQuery = mapper.ProjectTo<OrderModel>(ctx.Orders);
var test0 = orderQuery.ToList();

//As generated by AutoMapper with usual null checks not disabled (default behaviour)
var ordersWithNormalNullChecks = ctx.Orders.Select(dtoOrder => new OrderModel
{
    ShippingAddress = (((dtoOrder.ShippingAddress.Country != null) ? dtoOrder.ShippingAddress : null) == null)
        ? null
        : new AddressModel
        {
            City = ((dtoOrder.ShippingAddress.Country != null) ? dtoOrder.ShippingAddress : null).City,
            Country = ((dtoOrder.ShippingAddress.Country != null) ? dtoOrder.ShippingAddress : null).Country,
            HouseNumber = ((dtoOrder.ShippingAddress.Country != null) ? dtoOrder.ShippingAddress : null).HouseNumber,
            Street = ((dtoOrder.ShippingAddress.Country != null) ? dtoOrder.ShippingAddress : null).Street
        }
});
var test1 = ordersWithNormalNullChecks.ToList();

//As generated by AutoMapper with usual null checks disabled
var ordersWithLessNullChecks = ctx.Orders.Select(dtoOrder => new OrderModel
{
    ShippingAddress = new AddressModel
    {
        City = ((dtoOrder.ShippingAddress.Country != null) ? dtoOrder.ShippingAddress : null).City,
        HouseNumber = ((dtoOrder.ShippingAddress.Country != null) ? dtoOrder.ShippingAddress : null).HouseNumber,
        Street = ((dtoOrder.ShippingAddress.Country != null) ? dtoOrder.ShippingAddress : null).Street
    }
});
var test2 = ordersWithLessNullChecks.ToList();
```

### Include stack traces

```
System.ArgumentException: 'Argument types do not match'
   at System.Linq.Expressions.Expression.Bind(MemberInfo member, Expression expression)
   at System.Linq.Expressions.MemberAssignment.Update(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitConditional(ConditionalExpression node)
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryOptimizingExpressionVisitor.VisitUnary(UnaryExpression unaryExpression)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryOptimizingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EfCoreRepro.Program.Main(String[] args) in C:\Source\Git\EFCoreIssueReproduction\EFCore5\Program.cs:line 25
```

### Include provider and version information

EF Core version: 5.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0

**Comment by maumar** [comment]
related/duplicate: https://github.com/dotnet/efcore/issues/23877

**Comment by Erythnul** [comment]
Ah, good to see, I've left a comment over there. Thanks @maumar!
