### ISSUE TITLE
Unable to create FK as field in an entity

### ISSUE THREAD

**Issue by msschl** [dotnet/efcore#24150]
In our entity we want to store the FK id in an field, so that it's not public accessible and we can insert entities efficiently without fetching the parent entity and setting it in the navigation property.

Child entity:
```cs
// Domain model
public class MonthDegreeDay
{
    // NOTE: Our fields are not prefixed with _ or m_
    private int stationId;

    public MonthDegreeDay(int stationId, DateTime month, int daysOfMonth, int heatingDays, double value,
        double averageValue10Years)
    {
        this.stationId = stationId;
        this.Month = month;
        this.DaysOfMonth = daysOfMonth;
        this.HeatingDays = heatingDays;
        this.Value = value;
        this.AverageValue10Years = averageValue10Years;
    }

    public DateTime Month { get; }

    public int DaysOfMonth { get; }

    public int HeatingDays { get; }

    public double Value { get; }

    public double AverageValue10Years { get; }

    public virtual Station Station { get; }
}
```

Entity configuration:
```cs
public class MonthDegreeDayEntityTypeConfiguration : IEntityTypeConfiguration<MonthDegreeDay>
{
    private const string PRIVATE_PRIMARY_KEY = "Increment";

    private const string PRIVATE_DB_PRIMARY_KEY = "Increment";

    public void Configure(EntityTypeBuilder<MonthDegreeDay> builder)
    {
        // Shadow property is not included in the domain model
        builder.Property<int>(PRIVATE_PRIMARY_KEY)
            .IsRequired()
            .UseIdentityColumn()
            .HasColumnName(PRIVATE_DB_PRIMARY_KEY);

        // Property for StationId
        builder.Property<int>("StationId")
            .IsRequired()
            .HasField("stationId") // NOTE: Our fields are not prefixed with _ or m_
            .UsePropertyAccessMode(PropertyAccessMode.Field)
            .HasColumnName("StationId");

        builder.Property(x => x.Month)
            .IsRequired()
            .HasColumnType("DATE")
            .HasColumnName("Monat");

        builder.Property(x => x.DaysOfMonth)
            .IsRequired()
            .HasColumnName("AnzahlTage");

        builder.Property(x => x.HeatingDays)
            .IsRequired()
            .HasColumnName("AnzahlHeiztage");

        builder.Property(x => x.Value)
            .IsRequired()
            .HasColumnName("Wert");

        builder.Property(x => x.AverageValue10Years)
            .IsRequired()
            .HasColumnName("10JahresMittelwert");

        // NOTE(markus): primary key
        builder.HasKey(PRIVATE_PRIMARY_KEY);

        builder.HasOne(x => x.Station)
            .WithMany(x => x.MonthDegreeDays)
            .HasForeignKey("StationId")
            .IsRequired();

        builder.ToTable("Monatsgradtage");
    }
}
```

### Include stack traces

```
[20:49:05 ERR] Error while creating model...
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: The specified field 'stationId' cannot be used for the property 'MonthDegreeDay.StationId' because it does not match the property name.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyBase.SetFieldInfo(FieldInfo fieldInfo, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyBase.SetField(String fieldName, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalPropertyBaseBuilder`1.HasField(String fieldName, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalPropertyBuilder.HasField(String fieldName, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder.HasField(String fieldName)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder`1.HasField(String fieldName)
   at DWD.Service.Importer.DegreeDays.Persistence.Configuration.MonthDegreeDayEntityTypeConfiguration.Configure(EntityTypeBuilder`1 builder) in W:\service\DWD\src\Importer\DegreeDays\src\DWD.Service.Importer.DegreeDays\Persistence\Configuration\MonthDegreeDayEntityTypeConfiguration.cs:line 22
   at Microsoft.EntityFrameworkCore.ModelBuilder.ApplyConfiguration[TEntity](IEntityTypeConfiguration`1 configuration)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.EntityFrameworkCore.ModelBuilder.ApplyConfigurationsFromAssembly(Assembly assembly, Func`2 predicate)
   at DWD.Service.Importer.DegreeDays.Persistence.Internal.DegreeDaysDbContext.OnModelCreating(ModelBuilder modelBuilder) in W:\service\asapi\src\Importer\DegreeDays\src\DWD.Service.Importer.DegreeDays\Persistence\Internal\DegreeDaysDbContext.cs:line 21
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_Dependencies()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.BeginTransactionAsync(CancellationToken cancellationToken)
   at DWD.Service.Importer.DegreeDays.Persistence.Internal.MonthDegreeDayRepository.BeginTransactionAsync(CancellationToken cancellationToken) in W:\service\asapi\src\Importer\DegreeDays\src\DWD.Service.Importer.DegreeDays\Persistence\Internal\MonthDegreeDayRepository.cs:line 21
   at DWD.Service.Importer.DegreeDays.DegreeDaysImporter.ImportMonthlyDegreeDays(CancellationToken cancellationToken) in W:\service\asapi\src\Importer\DegreeDays\src\DWD.Service.Importer.DegreeDays\DegreeDaysImporter.cs:line 128
   at DWD.Service.Importer.DegreeDays.DegreeDaysImporter.ExecuteAsync(CancellationToken stoppingToken) in W:\service\asapi\src\Importer\DegreeDays\src\DWD.Service.Importer.DegreeDays\DegreeDaysImporter.cs:line 72
```

### Include provider and version information

EF Core version: v5.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer v5.0.3
Target framework: .NET 5.0
Operating system: Win-10 x64
IDE: Visual Studio Code

**Comment by anranruye** [comment]
try
```C#
        // Property for StationId
        builder.Property("stationId")
            .IsRequired()
            //.HasField("stationId") // NOTE: Our fields are not prefixed with _ or m_
            //.UsePropertyAccessMode(PropertyAccessMode.Field)
            .HasColumnName("StationId");

       builder.HasOne(x => x.Station)
            .WithMany(x => x.MonthDegreeDays)
            .HasForeignKey("stationId") // StationId => stationId
            .IsRequired();
```

**Comment by msschl** [comment]
This results in two `StationId` columns:

```sql
IF OBJECT_ID(N'[__EFMigrationsHistory]') IS NULL
BEGIN
    CREATE TABLE [__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END;
GO

BEGIN TRANSACTION;
GO

CREATE TABLE [WetterStation] (
    [Id] int NOT NULL,
    [Code] nvarchar(5) NOT NULL,
    [Name] nvarchar(40) NOT NULL,
    [Latitude] float NOT NULL,
    [Longitude] float NOT NULL,
    [Hoehe] int NOT NULL,
    [BundeslandCode] nvarchar(2) NOT NULL,
    [GueltigVon] DATE NOT NULL,
    [GueltigBis] DATE NOT NULL,
    [CreatedAt] datetime2 NOT NULL DEFAULT (getdate()),
    [LastModifiedAt] datetime2 NULL,
    CONSTRAINT [PK_WetterStation] PRIMARY KEY ([Id])
);
GO

CREATE TABLE [Monatsgradtage] (
    [Increment] int NOT NULL IDENTITY,
    [Monat] DATE NOT NULL,
    [AnzahlTage] int NOT NULL,
    [AnzahlHeiztage] int NOT NULL,
    [Wert] float NOT NULL,
    [10JahresMittelwert] float NOT NULL,
    [StationId1] int NOT NULL,
    [StationId] int NOT NULL,
    CONSTRAINT [PK_Monatsgradtage] PRIMARY KEY ([Increment]),
    CONSTRAINT [FK_Monatsgradtage_WetterStation_StationId1] FOREIGN KEY ([StationId1]) REFERENCES [WetterStation] ([Id]) ON DELETE CASCADE
);
GO

CREATE INDEX [IX_Monatsgradtage_StationId1] ON [Monatsgradtage] ([StationId1]);
GO

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20210215102410_InitialCreate', N'5.0.3');
GO

COMMIT;
GO
```

**Comment by anranruye** [comment]
@msschl 
try remove
```C#
.HasForeignKey("stationId")
```

**Comment by msschl** [comment]
Still the same result

**Comment by anranruye** [comment]
@msschl  Do you use lower case 's' for `.HasForeignKey("stationId")` ?

**Comment by msschl** [comment]
Yes like you've suggested.

> try
> 
> ```C#
> 
>         // Property for StationId
> 
>         builder.Property("stationId")
> 
>             .IsRequired()
> 
>             //.HasField("stationId") // NOTE: Our fields are not prefixed with _ or m_
> 
>             //.UsePropertyAccessMode(PropertyAccessMode.Field)
> 
>             .HasColumnName("StationId");
> 
> 
> 
>        builder.HasOne(x => x.Station)
> 
>             .WithMany(x => x.MonthDegreeDays)
> 
>             .HasForeignKey("stationId") // StationId => stationId
> 
>             .IsRequired();
> 
> ```

**Comment by anranruye** [comment]
@msschl Well, I can not reproduce this.

Can you check your migration ModelSnapshot file?

**Comment by msschl** [comment]
I have removed all migrations and created a new `InitialCreate` migration using `dotnet ef -p src\XYZ.Service.Importer.DegreeDays\XYZ.Service.Importer.DegreeDays.csproj migrations add -c DegreeDaysDbContext -o Persistence\Migrations\ InitialCreate`

dotnet-ef v5.0.3

**Comment by msschl** [comment]
Here is the snapshot:

```cs
modelBuilder
    .UseIdentityColumns()
    .HasAnnotation("Relational:MaxIdentifierLength", 128)
    .HasAnnotation("ProductVersion", "5.0.3");

modelBuilder.Entity("XYZ.Service.Importer.DegreeDays.Entities.MonthDegreeDay", b =>
    {
        b.Property<int>("Increment")
            .ValueGeneratedOnAdd()
            .HasColumnType("int")
            .HasColumnName("Increment")
            .UseIdentityColumn();

        b.Property<double>("AverageValue10Years")
            .HasColumnType("float")
            .HasColumnName("10JahresMittelwert");

        b.Property<int>("DaysOfMonth")
            .HasColumnType("int")
            .HasColumnName("AnzahlTage");

        b.Property<int>("HeatingDays")
            .HasColumnType("int")
            .HasColumnName("AnzahlHeiztage");

        b.Property<DateTime>("Month")
            .HasColumnType("DATE")
            .HasColumnName("Monat");

        b.Property<int>("StationId")
            .HasColumnType("int")
            .HasColumnName("StationId1");

        b.Property<double>("Value")
            .HasColumnType("float")
            .HasColumnName("Wert");

        b.Property<int>("stationId")
            .HasColumnType("int")
            .HasColumnName("StationId");

        b.HasKey("Increment");

        b.HasIndex("StationId");

        b.ToTable("Monatsgradtage");
    });

modelBuilder.Entity("XYZ.Service.Importer.DegreeDays.Entities.Station", b =>
    {
        b.Property<int>("Id")
            .HasColumnType("int");

        b.Property<int>("Altitude")
            .HasColumnType("int")
            .HasColumnName("Hoehe");

        b.Property<string>("Code")
            .IsRequired()
            .HasMaxLength(5)
            .HasColumnType("nvarchar(5)");

        b.Property<DateTime>("CreatedAt")
            .ValueGeneratedOnAdd()
            .HasColumnType("datetime2")
            .HasDefaultValueSql("getdate()");

        b.Property<string>("FederalStateCode")
            .IsRequired()
            .HasMaxLength(2)
            .HasColumnType("nvarchar(2)")
            .HasColumnName("BundeslandCode");

        b.Property<DateTime?>("LastModifiedAt")
            .HasColumnType("datetime2");

        b.Property<double>("Latitude")
            .HasColumnType("float");

        b.Property<double>("Longitude")
            .HasColumnType("float");

        b.Property<string>("Name")
            .IsRequired()
            .HasMaxLength(40)
            .HasColumnType("nvarchar(40)");

        b.Property<DateTime>("ValidFrom")
            .HasColumnType("DATE")
            .HasColumnName("GueltigVon");

        b.Property<DateTime>("ValidTo")
            .HasColumnType("DATE")
            .HasColumnName("GueltigBis");

        b.HasKey("Id");

        b.ToTable("WetterStation");
    });

modelBuilder.Entity("XYZ.Service.Importer.DegreeDays.Entities.MonthDegreeDay", b =>
    {
        b.HasOne("ASGmbH.Service.Importer.DegreeDays.Entities.Station", "Station")
            .WithMany("MonthDegreeDays")
            .HasForeignKey("StationId")
            .OnDelete(DeleteBehavior.Cascade)
            .IsRequired();

        b.Navigation("Station");
    });

modelBuilder.Entity("XYZ.Service.Importer.DegreeDays.Entities.Station", b =>
    {
        b.Navigation("MonthDegreeDays");
    });
```

and for completion again the entity type configuration and model:
```cs
private const string PRIVATE_PRIMARY_KEY = "Increment";

private const string PRIVATE_DB_PRIMARY_KEY = "Increment";

public void Configure(EntityTypeBuilder<MonthDegreeDay> builder)
{
    builder.Property<int>(PRIVATE_PRIMARY_KEY)
        .IsRequired()
        .UseIdentityColumn()
        .HasColumnName(PRIVATE_DB_PRIMARY_KEY);

    // Property for StationId
    builder.Property("stationId")
        .IsRequired()
    //     .HasField("stationId")
    //     .UsePropertyAccessMode(PropertyAccessMode.Field)
        .HasColumnName("StationId");

    builder.Property(x => x.Month)
        .IsRequired()
        .HasColumnType("DATE")
        .HasColumnName("Monat");

    builder.Property(x => x.DaysOfMonth)
        .IsRequired()
        .HasColumnName("AnzahlTage");

    builder.Property(x => x.HeatingDays)
        .IsRequired()
        .HasColumnName("AnzahlHeiztage");

    builder.Property(x => x.Value)
        .IsRequired()
        .HasColumnName("Wert");

    builder.Property(x => x.AverageValue10Years)
        .IsRequired()
        .HasColumnName("10JahresMittelwert");

    // NOTE(markus): primary key
    builder.HasKey(PRIVATE_PRIMARY_KEY);

    builder.HasOne(x => x.Station)
        .WithMany(x => x.MonthDegreeDays)
        .HasForeignKey("stationId") // tested with this line and without...
        .IsRequired();

    builder.ToTable("Monatsgradtage");
}
```

```cs
public class MonthDegreeDay
{
    private int stationId;

    public MonthDegreeDay(int stationId, DateTime month, int daysOfMonth, int heatingDays, double value,
        double averageValue10Years)
    {
        this.stationId = stationId;
        this.Month = month;
        this.DaysOfMonth = daysOfMonth;
        this.HeatingDays = heatingDays;
        this.Value = value;
        this.AverageValue10Years = averageValue10Years;
    }

    public DateTime Month { get; }

    public int DaysOfMonth { get; }

    public int HeatingDays { get; }

    public double Value { get; }

    public double AverageValue10Years { get; }

    public virtual Station Station { get; }
}
```

**Comment by anranruye** [comment]
Then you can see here:
```C#
modelBuilder.Entity("XYZ.Service.Importer.DegreeDays.Entities.MonthDegreeDay", b =>
    {
        b.HasOne("ASGmbH.Service.Importer.DegreeDays.Entities.Station", "Station")
            .WithMany("MonthDegreeDays")
            .HasForeignKey("StationId")       // should be "stationId"
            .OnDelete(DeleteBehavior.Cascade)
            .IsRequired();

        b.Navigation("Station");
    });
```
and your `Station` configration:
```C#
        builder.HasMany(x => x.MonthDegreeDays)
            .WithOne(x => x.Station)
            .HasForeignKey("StationId")   // should be "stationId"
            .IsRequired();
```

**Comment by msschl** [comment]
Oh yes, sure. I totally forgot about the foreign key configuration in the Station... 🤦🏽 
Closing as it works now.

Thanks @anranruye 👍🏽
