### ISSUE TITLE
The instance of SQL Server you attempted to connect to requires encryption but this machine does not support it.

### ISSUE THREAD

**Issue by mstfgueclue** [dotnet/efcore#24185]
I'm currently facing an Azure SQL connectivity issue - I assume so - with the following stack (see down below) and running into the error, which is also pasted down below. 

This behaviour isn't happening when I  use .NET Core 3.1 and EF Core 3.1 

### Provider and version information:

**EF Core**: v5.0.3
**Database provider**: Microsoft.EntityFrameworkCore.SqlServer v5.0.3
**Target framework:** NET 5.0
**IDE**: Visual Studio 2019 16.8.5
- The database is running in Azure SQL Server
- Service is running in a **Docker Container** 

### InnerException
```
"The instance of SQL Server you attempted to connect to requires encryption but this machine does not support it."
```

### Source
```
"Microsoft.EntityFrameworkCore.SqlServer"
```

### StackTrace
```
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.<MoveNextAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.<SingleOrDefaultAsync>d__15`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.<SingleOrDefaultAsync>d__15`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Contakt.Services.User.Data.Repositories.UserRepository.<GetUserByIdAsync>d__4.MoveNext() in 
```

**Comment by ErikEJ** [comment]
Not really an EF Core issue, see: https://github.com/dotnet/SqlClient/issues/714

**Comment by ajcvickers** [comment]
Closing as external per @ErikEJ's comment.

**Comment by kakalot2504** [comment]
viết 1 chương trình bằng C#. Sau khi đóng gói và cài đặt ở máy tính khác thì xuất hiện lỗi này: The instance of SQL Server you attempted to connect to requires encryption but this machine does not support it. #24185
