### ISSUE TITLE
NRE in SplitQueryingEnumerable.Enumerator.Dispose() hides actual DbCommand failures

### ISSUE THREAD

**Issue by Obi-Dann** [dotnet/efcore#24181]
Getting NullReferenceExceptions on any SQL failure, eg. timeout or invalid sql, instead of actual SQL exceptions.

Given I am trying to run that sql:
```C#
dbContext.Items
    .FromSqlRaw("incorrect sql")
    .AsSplitQuery()
    .ToList();
```

I get this exception:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.Enumerator.Dispose()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EfIssue22921.Program.Main(String[] args) in /Users/dannci/projects/EfIssue22921/EfIssue22921/Program.cs:line 19
```

Instead of getting 
```
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'near "incorrect": syntax error'.
```

We were getting that issue in prod and it required some specific config to replicate it in a sample project:
- It should a `SplitQuery`
- Entity should have a query filter

I couldn't replicate it with any other config, here's the sample console app code:

<details>

```C#
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace EfIssue
{
    class Program
    {
        static void Main(string[] args)
        {
            var optionsBuilder = new DbContextOptionsBuilder<DbContext>();
            optionsBuilder.UseSqlite("DataSource=:memory:");
            
            var dbContext = new MyDbContext(optionsBuilder.Options);
            dbContext.Database.EnsureCreated();
            
            try
            {
                dbContext.Items
                    .FromSqlRaw("incorrect sql")
                    .AsSplitQuery()
                    .ToList(); // throws NullReferenceException

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }

        }
    }

    public class MyDbContext : DbContext
    {
        public MyDbContext(DbContextOptions options) : base(options)
        {
        }
        
        public DbSet<Item> Items { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Item>()
                .HasQueryFilter(x => x.IsDeleted == false);
        }
    }

    public class Item
    {
        public long Id { get; set; }

        public bool IsDeleted { get; set; }
    }
}
```

</details>

It seems to be somewhat related to #22921, even though stacktraces are different.

EF Core version: 5.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer and Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 5.0 and .NET Core 3.1
Operating system: macOS and Windows 10

**Comment by smitpatel** [comment]
Fixed in https://github.com/dotnet/efcore/pull/23185

**Comment by Obi-Dann** [comment]
Thanks @smitpatel! 
This issue is a duplicate of #23157, closing this issue.
