### ISSUE TITLE
Unable to find an entry point named 'DllBidEntryPoint' in DLL 'System.Data.dll' in  EFCore 3.1.3

### ISSUE THREAD

**Issue by ArvindMaurya1996** [dotnet/efcore#24255]
## Why does EFCore 3.1.3 throws System.Data.dll exception? Unable to find an entry point named 'DllBidEntryPoint' in DLL 'System.Data.dll'.

My project uses `EFCore 3.1.3` that target to target to `.NetFramework 4.7.2`
Code snippet to reproduce issue.
e.g: 
```
var myAnimals = DbContext.animalTable;
foreach(var animal in myAnimals){
   console.writeLine($"my {animal.Name}");
}
```
**Note**: **_To generate below exception you need to set System.data copy local true._**
**Question**: Why I am setting System.data.dll to copy local true.
**Answer**:  On  build server I get below mentioned exception every time when we build and run Unit-Test. By setting System.Data  
                     copy  local true  I am able to reproduce issue locally on my dev machine.

![image](https://user-images.githubusercontent.com/30270652/109007667-67b42100-76d2-11eb-9745-62c31b93ae08.png)
![image](https://user-images.githubusercontent.com/30270652/109007910-ac3fbc80-76d2-11eb-8e96-6994ccbb2f89.png)

I get below exception when i try to iterate on  myAnimals object.
**Exception**: 
![image](https://user-images.githubusercontent.com/30270652/109008866-d3e35480-76d3-11eb-8176-0bec2136a249.png)

**StackTrace**:
```
   at Bid.get_TraceOn() in E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netfx\src\BID\INC\CS\BidPrivateBase.cs:line 103
   at Microsoft.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key) in E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\ProviderBase\SqlConnectionHelper.cs:line 113
   at Microsoft.Data.SqlClient.SqlConnection.set_ConnectionString(String value) in E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlConnection.cs:line 614
   at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString, SqlCredential credential) in E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlConnection.cs:line 311
   at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString) in E:\agent1\_work\34\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlConnection.cs:line 307
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.CreateCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
```

**More Findings**
https://github.com/dotnet/SqlClient/blob/297500426e15f8b9f9f836fc818bb509f30ba856/src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/ProviderBase/SqlConnectionHelper.cs#L113
As per code here it  it throws  Exception

### Include provider and version information

EF Core version: 3.1.3
Database provider:  ` Microsoft.EntityFrameworkCore.SqlServer 3.1.3.0`,  `Microsoft.Data.SqlClient  v1.0.19269.1`
Target framework:    .NetFramework 4.7.2
Operating system: Win 10
IDE: (e.g. Visual Studio 2017 15.9.13)

**Comment by ajcvickers** [comment]
@ArvindMaurya1996 `System.Data` is part of the .NET Base Class Library (BCL) and hence is expected to be resolved from the .NET platform you are using. Using "copy local" could very well result in .NET attempting to use the incorrect assembly. Therefore, it seems that the root cause here is that you're getting an exception when trying to use SqlClient. I see you are using an old version of `Microsoft.Data.SqlClient`. Can you update to that latest and try again?

**Comment by ArvindMaurya1996** [comment]
@ajcvickers  Unintentionally some of our libraries had copy local set to true for `System.Data`. By setting it to false resolved our issue. Thanks and much appreciated for a quick response.
