### ISSUE TITLE
"The LINQ expression could not be translated" with in-memory provider

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/efcore#24318]
The following query fails to translate using the in-memory provider

```csharp
return await _dbContext.Affaires
    .Include(a => a.Tiers).ThenInclude(t => t.Tiers)
    .Include(a => a.Nature)
    .SingleAsync(a => a.Id == affaire.Id, cancellationToken);
```

I get the following exception:

```
The LINQ expression 'DbSet<Affaire>()
    .Where(a => EF.Property<TenantId>((object)a, "TenantId") == 3921751e-f1af-4fa3-b3cf-1605b898b928)
    .Where(a => a.Id == __affaire_Id_0)
    .Join(
        inner: DbSet<NatureAffaire>(), 
        outerKeySelector: a => EF.Property<NatureAffaireId>(a, "NatureId"), 
        innerKeySelector: n => EF.Property<NatureAffaireId>(n, "Id"), 
        resultSelector: (o, i) => new TransparentIdentifier<Affaire, NatureAffaire>(
            Outer = o, 
            Inner = i
        ))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```

Stack trace:

```
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.SingleAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   (redacted)
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90

```

I'm not sure what it should be "translated" to (does the in-memory provider use its own query language?), but it's a pretty basic query, and it's failing miserably.

The same query works fine with the SQL Server provider.
The same query without the `Include`s works with the in-memory provider.

It's worth noting that there's something unusual in my DbContext: I use strongly-typed ids. In other words, for each entity `Foo`, there's a `FooId` record that wraps a GUID. I suspect it's what causing the issue. Unless it's because the in-memory provider doesn't support `Include`s, but I'd be very surprised if it didn't.

EF Core version: 5.0.3
Database provider: in-memory
Target framework: .NET 5.0
Operating system: Windows 10
IDE: JetBrains Rider

**Comment by villanyibalint** [comment]
We experienced the same exact issue.
* We also use strongly typed IDs
* It only happens with the in-memory provider and not SQL Server
* For us the issue came up with a many-to-many relationship

I tried to assemble the smallest reproduction I could:
```csharp
internal class Program
{
  private static void Main(string[] args)
  {
    SqlServer();
    InMemory();
  }

  /// <summary>
  /// Run the query on an in-memory DbContext
  /// </summary>
  private static void InMemory()
  {
    var options = new DbContextOptionsBuilder<ExampleContext>()
        .UseInMemoryDatabase("db")
        .Options;

    using var ctx = new ExampleContext(options);

    Query(ctx);
  }

  /// <summary>
  /// Run the query on an SQLServer DbContext
  /// </summary>
  private static void SqlServer()
  {
    var options = new DbContextOptionsBuilder<ExampleContext>()
        .UseSqlServer("Server=.\\SQLEXPRESS01;Database=EFInMemoryQueryIssue;Trusted_Connection=True;")
        .Options;

    using var ctx = new ExampleContext(options);

    ctx.Database.EnsureDeleted();
    ctx.Database.EnsureCreated();

    Query(ctx);
  }

  /// <summary>
  /// Actual query to run
  /// </summary>
  private static void Query(ExampleContext ctx)
  {
    try
    {
      var owner = ctx
        .Owners
        .Include(o => o.OwnedEntities)
        .FirstOrDefault();
      Console.WriteLine("Query successful.");
    }
    catch (Exception e)
    {
      Console.WriteLine(e.Message);
    }
  }
}

/// <summary>
/// Example DbContext
/// </summary>
internal class ExampleContext : DbContext
{
  public ExampleContext(DbContextOptions<ExampleContext> dbContextOptions) : base(dbContextOptions)
  {
  }

  public DbSet<OwnerEntity> Owners => Set<OwnerEntity>();

  protected override void OnModelCreating(ModelBuilder modelBuilder)
  {
    // strongly typed ID conversion setup
    modelBuilder.Entity<OwnedEntity>().Property(o => o.Id)
      .HasConversion(id => id.Id, id => new(id));

    // many-to-many relationship
    modelBuilder.Entity<OwnerEntity>()
      .HasMany(o => o.OwnedEntities)
      .WithMany(s => s.Owners);
  }
}

record StronglyTypedId(Guid Id);

internal class OwnedEntity
{
  public StronglyTypedId Id { get; set; } = new(Guid.NewGuid());

  public ICollection<OwnerEntity> Owners { get; set; }
}

internal class OwnerEntity
{
  public Guid Id { get; set; } = Guid.NewGuid();

  public List<OwnedEntity> OwnedEntities { get; set; }
}
```

Additionally, based on my observation, it is enough if the joined table has an ID with a conversion.

Exception message:
```
The LINQ expression 'DbSet<Dictionary<string, object>>("OwnedEntityOwnerEntity")
    .Where(o0 => EF.Property<Nullable<Guid>>(EntityShaperExpression:
        EntityType: OwnerEntity
        ValueBufferExpression:
            ProjectionBindingExpression: EmptyProjectionMember
        IsNullable: False
    , "Id") != null && object.Equals(
        objA: (object)EF.Property<Nullable<Guid>>(EntityShaperExpression:
            EntityType: OwnerEntity
            ValueBufferExpression:
                ProjectionBindingExpression: EmptyProjectionMember
            IsNullable: False
        , "Id"),
        objB: (object)EF.Property<Nullable<Guid>>(o0, "OwnersId")))
    .Join(
        inner: DbSet<OwnedEntity>(),
        outerKeySelector: o0 => EF.Property<StronglyTypedId>(o0, "OwnedEntitiesId"),
        innerKeySelector: o1 => EF.Property<StronglyTypedId>(o1, "Id"),
        resultSelector: (o0, o1) => new TransparentIdentifier<Dictionary<string, object>, OwnedEntity>(
            Outer = o0,
            Inner = o1
        ))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```

**Comment by wallymathieu** [comment]
Can be reproduced in https://github.com/wallymathieu/entity-framework-studies/
Perhaps related to if you use structs or classes? 
https://github.com/wallymathieu/entity-framework-studies/pull/25/files#diff-fa3edc1bb0762de14e28751b83fa81bf5880d9069e98e126d6f5972ab382b5a3

**Comment by JssDWt** [comment]
I'm facing the same issue with `byte[]` keys.

```
    class Program
    {
        static async Task Main(string[] args)
        {
            var rootKey = new byte[8];
            new Random().NextBytes(rootKey);

            using var dbContext = new MyDbContext();
            await dbContext.Database.EnsureCreatedAsync();
            dbContext.Roots.Add(new RootEntity
            {
                Name = "Root",
                Key = rootKey
            });

            dbContext.Children.Add(new ChildEntity
            {
                RootKey = rootKey,
                Name = "Child"
            });
            await dbContext.SaveChangesAsync();
            var child = await dbContext.Children
                .Where(a => a.RootKey == rootKey)
                .Include(a => a.Root)
                .FirstOrDefaultAsync();
        }
    }

    public class RootEntity
    {
        public RootEntity()
        {
            Children = new HashSet<ChildEntity>();
        }

        public byte[] Key { get; set; }
        public string Name { get; set; }
        public virtual ICollection<ChildEntity> Children { get; set; }
    }

    public class ChildEntity
    {
        public Guid Id { get; set; }
        public byte[] RootKey { get; set; }
        public virtual RootEntity Root { get; set; }
        public string Name { get; set; }
    }

    public class MyDbContext : DbContext
    {
        public DbSet<RootEntity> Roots { get; set; }
        public DbSet<ChildEntity> Children { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseInMemoryDatabase("testdatabase");
            base.OnConfiguring(optionsBuilder);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ChildEntity>(channelArc =>
            {
                channelArc.HasOne(a => a.Root)
                    .WithMany(n => n.Children)
                    .HasForeignKey(a => a.RootKey);
            });

            modelBuilder.Entity<RootEntity>(node =>
            {
                node.HasKey(n => n.Key);
            });
        }
    }
```

This throws the following Exception:

```
An exception of type 'System.InvalidOperationException' occurred in Microsoft.EntityFrameworkCore.dll but was not handled in user code: 'The LINQ expression 'DbSet<ChildEntity>()
    .Where(c => c.RootKey == __rootKey_0)
    .LeftJoin(
        inner: DbSet<RootEntity>(), 
        outerKeySelector: c => EF.Property<byte[]>(c, "RootKey"), 
        innerKeySelector: r => EF.Property<byte[]>(r, "Key"), 
        resultSelector: (o, i) => new TransparentIdentifier<ChildEntity, RootEntity>(
            Outer = o, 
            Inner = i
        ))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.'
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Program.<Main>d__0.MoveNext() in /Path/To/Project/Program.cs:line 34
```

**Comment by fallingsappy** [comment]
Using structs as PK is fine, the problem appears only if you use class as PK.

**Comment by willisd2** [comment]
I seem to be running into this same issue, or a similar one. In my situation I have the Include and am using the AsSplitQuery() extension method. The main query is also doing an explicit Join() to another table, so the Select() part of the query is receiving an anonymous object. This seemed to all work fine with the Sql Server provider, but my unit tests are failing using the InMemory provider. When I comment out the Join() and the areas out of the Select that were using the joined table, then the unit tests start passing.

**Comment by ajcvickers** [comment]
We recommend against using the in-memory provider for testing--see [Testing EF Core Applications](https://learn.microsoft.com/en-us/ef/core/testing/). While we have [no plans to remove the in-memory provider](https://github.com/dotnet/efcore/issues/18457), we will not be adding any new features to this provider because we believe valuable development time is better spent in other areas. When feasible, we plan to still fix regressions in existing behavior.

**Comment by NickStrupat** [comment]
As far as I could tell, the docs linked here currently do not recommend against the in-memory provider.

> We recommend against using the in-memory provider for testing--see [Testing EF Core Applications](https://learn.microsoft.com/en-us/ef/core/testing/). While we have [no plans to remove the in-memory provider](https://github.com/dotnet/efcore/issues/18457), we will not be adding any new features to this provider because we believe valuable development time is better spent in other areas. When feasible, we plan to still fix regressions in existing behavior.

**Comment by roji** [comment]
@NickStrupat we do recommend against using the in-memory provider. See the [Choosing a testing strategy](https://learn.microsoft.com/en-us/ef/core/testing/choosing-a-testing-strategy) page, and specifically [this section](https://learn.microsoft.com/en-us/ef/core/testing/choosing-a-testing-strategy#in-memory-as-a-database-fake).

**Comment by yuominae** [comment]
It's worth noting that using Sqlite instead of the in-memory provider is only shifting the problem. My unit tests were implemented using sqlite from the beginning because of the guidance in the docs. It works fine if you enable foreign keys, which the in-memory provider can;t do, but it also cannot translate all linq queries properly (notably String.Contains()). And now switching the strongly typed ids just destroyed all the sqlite tests as sqlite, event though the integration tests with SQL Server work just fine.

**Comment by thomaslevesque** [comment]
Yeah. At this point, the only reliable approach is to test against the real DB engine. You can easily spin up a SQL Server container using [TestContainers](https://dotnet.testcontainers.org/).

**Comment by roji** [comment]
@yuominae what @thomaslevesque said. Testing against a fake database (in-memory, sqlite...) used to make more sense, but in today's world of easy containerization and testcontainers, you really should be testing against SQL Server.

**Comment by yuominae** [comment]
Thanks to both of you for confirming. I wish the guidance on tests would use stronger wording there. It's definitely something I will take into account in the future, but wanted to document the problems here for anybody who'll stumble across this issue :)

**Comment by platter-testng-eclipse50** [comment]
> We experienced the same exact issue.
> 
> * We also use strongly typed IDs
> * It only happens with the in-memory provider and not SQL Server
> * For us the issue came up with a many-to-many relationship
> 
> I tried to assemble the smallest reproduction I could:
> 
> internal class Program
> {
>   private static void Main(string[] args)
>   {
>     SqlServer();
>     InMemory();
>   }
> 
>   /// <summary>
>   /// Run the query on an in-memory DbContext
>   /// </summary>
>   private static void InMemory()
>   {
>     var options = new DbContextOptionsBuilder<ExampleContext>()
>         .UseInMemoryDatabase("db")
>         .Options;
> 
>     using var ctx = new ExampleContext(options);
> 
>     Query(ctx);
>   }
> 
>   /// <summary>
>   /// Run the query on an SQLServer DbContext
>   /// </summary>
>   private static void SqlServer()
>   {
>     var options = new DbContextOptionsBuilder<ExampleContext>()
>         .UseSqlServer("Server=.\\SQLEXPRESS01;Database=EFInMemoryQueryIssue;Trusted_Connection=True;")
>         .Options;
> 
>     using var ctx = new ExampleContext(options);
> 
>     ctx.Database.EnsureDeleted();
>     ctx.Database.EnsureCreated();
> 
>     Query(ctx);
>   }
> 
>   /// <summary>
>   /// Actual query to run
>   /// </summary>
>   private static void Query(ExampleContext ctx)
>   {
>     try
>     {
>       var owner = ctx
>         .Owners
>         .Include(o => o.OwnedEntities)
>         .FirstOrDefault();
>       Console.WriteLine("Query successful.");
>     }
>     catch (Exception e)
>     {
>       Console.WriteLine(e.Message);
>     }
>   }
> }
> 
> /// <summary>
> /// Example DbContext
> /// </summary>
> internal class ExampleContext : DbContext
> {
>   public ExampleContext(DbContextOptions<ExampleContext> dbContextOptions) : base(dbContextOptions)
>   {
>   }
> 
>   public DbSet<OwnerEntity> Owners => Set<OwnerEntity>();
> 
>   protected override void OnModelCreating(ModelBuilder modelBuilder)
>   {
>     // strongly typed ID conversion setup
>     modelBuilder.Entity<OwnedEntity>().Property(o => o.Id)
>       .HasConversion(id => id.Id, id => new(id));
> 
>     // many-to-many relationship
>     modelBuilder.Entity<OwnerEntity>()
>       .HasMany(o => o.OwnedEntities)
>       .WithMany(s => s.Owners);
>   }
> }
> 
> record StronglyTypedId(Guid Id);
> 
> internal class OwnedEntity
> {
>   public StronglyTypedId Id { get; set; } = new(Guid.NewGuid());
> 
>   public ICollection<OwnerEntity> Owners { get; set; }
> }
> 
> internal class OwnerEntity
> {
>   public Guid Id { get; set; } = Guid.NewGuid();
> 
>   public List<OwnedEntity> OwnedEntities { get; set; }
> }
> Additionally, based on my observation, it is enough if the joined table has an ID with a conversion.
> 
> Exception message:
> 
> ```
> The LINQ expression 'DbSet<Dictionary<string, object>>("OwnedEntityOwnerEntity")
>     .Where(o0 => EF.Property<Nullable<Guid>>(EntityShaperExpression:
>         EntityType: OwnerEntity
>         ValueBufferExpression:
>             ProjectionBindingExpression: EmptyProjectionMember
>         IsNullable: False
>     , "Id") != null && object.Equals(
>         objA: (object)EF.Property<Nullable<Guid>>(EntityShaperExpression:
>             EntityType: OwnerEntity
>             ValueBufferExpression:
>                 ProjectionBindingExpression: EmptyProjectionMember
>             IsNullable: False
>         , "Id"),
>         objB: (object)EF.Property<Nullable<Guid>>(o0, "OwnersId")))
>     .Join(
>         inner: DbSet<OwnedEntity>(),
>         outerKeySelector: o0 => EF.Property<StronglyTypedId>(o0, "OwnedEntitiesId"),
>         innerKeySelector: o1 => EF.Property<StronglyTypedId>(o1, "Id"),
>         resultSelector: (o0, o1) => new TransparentIdentifier<Dictionary<string, object>, OwnedEntity>(
>             Outer = o0,
>             Inner = o1
>         ))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
> ```





https://stackdev.space/questions/what-are-the-steps-for-utilizing-the-predicate-method-in-a-many-to-many-relationship-within-entity-framework-using-linq-lambda-expressions
