### ISSUE TITLE
Add in NavigationProperty makes an update in database instead of an insert

### ISSUE THREAD

**Issue by julesduroux** [dotnet/efcore#24383]
## Bug

When I try to create an entity via an Add on navigation property, EF makes an update instead of an insert in database.

### Code to reproduce
Ef5CoreTests.csproj
```XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.4" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
  </ItemGroup>
</Project>
```

Ef5CoreTests.cs
```C#
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

namespace EfCore5Test
{
    public class Entreprise
    {
        public Entreprise(Guid id, Guid etablissementId)
        {
            Id = id;
            EtablissementId = etablissementId;
        }

        public Guid Id { get; private set; }
        public Guid EtablissementId { get; private set; }
        public Etablissement Etablissement { get; private set; } = null!;

    }
    public class Etablissement
    {
        public Etablissement(Guid id)
        {
            Id = id;
        }

        public Guid Id { get; }
        public List<Entreprise> EntrepriseUtilisatrice { get; set; } = new List<Entreprise>();
    }


    public sealed class ApplicationDbContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            optionsBuilder.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=aspnet-WebApplication-accde85f-6a02-4048-a440-28f58017a91c;Trusted_Connection=True;MultipleActiveResultSets=true");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Entreprise>(builder =>
            {
                builder.HasKey(e => e.Id);
            });

            modelBuilder.Entity<Etablissement>(builder =>
            {
                builder.HasKey(e => e.Id);
                builder.HasMany(eu => eu.EntrepriseUtilisatrice)
                .WithOne(eue => eue.Etablissement)
                .HasForeignKey(x => x.EtablissementId);
            });
        }

        public DbSet<Etablissement> Etablissements => Set<Etablissement>();
    }

    class Program
    {
        static async System.Threading.Tasks.Task Main(string[] args)
        {
            using (var context = new ApplicationDbContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                //Create an etablissement in database
                var id = Guid.NewGuid();
                var etab = new Etablissement(id);
                context.Add(etab);

                //Add entreprise on etablissement
                var entreprise = new Entreprise(Guid.NewGuid(), etab.Id);
                etab.EntrepriseUtilisatrice.Add(entreprise);

                //Expected to add entreprise in database
                await context.SaveChangesAsync();
            }
        }
    }
}
```

### stack trace

```
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: '
Database operation expected to affect 1 row(s) but actually affected 0 row(s). 
Data may have been modified or deleted since entities were loaded. 
See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.'

   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.<ConsumeResultSetWithoutPropagationAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.<ConsumeAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__29.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__29.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__100.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__104.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__56.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__56.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EfCore5Test.Program.<Main>d__0.MoveNext() in C:\Users\Reverb\Documents\repos\Ef5CoreTests\Ef5CoreTests.cs:line 80
```

### verbose output

Insertion is ok
```
Executed DbCommand (26ms) [Parameters=[@p0='2d00c059-cecc-4e1e-abe6-7bcd4c346b32'], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [Etablissements] ([Id])
VALUES (@p0);
```

but then creation of entity via navigation property does an update instead of an insert in database
```
Executed DbCommand (2ms) [Parameters=[@p2='c80e3d79-8eaf-4ac6-afee-fe493b667583', @p1='2d00c059-cecc-4e1e-abe6-7bcd4c346b32'], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
UPDATE [Entreprise] SET [EtablissementId] = @p1
WHERE [Id] = @p2;
SELECT @@ROWCOUNT;
```

### Provider and version information

EF Core version: 5.0.4
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: .NET 5.0
Operating system:
IDE: (e.g. Visual Studio 2019 16.9.0)

**Comment by julesduroux** [comment]
I tried different versions :
It works for .EntityFrameworkCore.SqlServerin version 2.2.6 but it breaks from version 3.0 and forward

**Comment by julesduroux** [comment]
The solution was to add 
```
builder.Property(e => e.Id).ValueGeneratedNever();
```
https://docs.microsoft.com/fr-fr/ef/core/modeling/generated-properties?tabs=fluent-api

**Primary keys**
By convention, non-composite primary keys of type short, int, long, or Guid are set up to have values generated for inserted entities if a value isn't provided by the application. Your database provider typically takes care of the necessary configuration; for example, a numeric primary key in SQL Server is automatically set up to be an IDENTITY column.
