### ISSUE TITLE
Anonymous objects properties order matters for composite keys definition

### ISSUE THREAD

**Issue by uladz-zubrycki** [dotnet/efcore#24455]
## Issue

Even though it may have pretty reasonable explanation, it's pretty counterintuitive and very unexpected, that properties order matters, when defining composite keys with use of anonymous objects.

This 
```
HasForeignKey<OrderAdmin>(a => new {a.OrderId, a.AdminId})
```
Is not equal to this
```
HasForeignKey<OrderAdmin>(a => new { a.AdminId, a.OrderId})
```
And will fail in runtime, when attempt to insert entity is made. I believe this should either work automatically or be detected upon model validation, thus fail faster.

### Description

Model to reproduce this issue could be simpler, but I just used existing db and removed irrelevant details, sorry for that.

Here are entity types:
```c#
public class User
{
	public int Id { get; set; }
}

public class Admin
{
	public int Id { get; set; }

	public User User { get; set; }
}

public class Order
{
	public int Id { get; set; }
}

public class OrderOwner
{
	public int OrderId { get; set; }
	public int UserId { get; set; }

	public Order Order { get; set; }
	public User User { get; set; }
	public OrderAdmin OrderAdmin { get; set; }
}

public class OrderAdmin
{
	public int OrderId { get; set; }
	public int AdminId { get; set; }

	public Admin Admin { get; set; }
	public Order Order { get; set; }
	public OrderOwner OrderOwner { get; set; }
}
```

Imagine that we have admin with id 1 and order with id 100 after executing this code
```c#
var admin = dbContext.Admins.Add(new Admin() {User = new User()}).Entity;
var order = dbContext.Orders.Add(new Order()).Entity;
dbContext.SaveChanges();
```

Then attempt to insert `OrderAdmin` will use those ids in invalid order (see related configuration for the root cause).
```C#
var orderAdmin = new OrderAdmin
{
	Admin = admin,
	OrderOwner = new OrderOwner
	{
		Order = order,
		User = admin.User,
	}
};
dbContext.OrderAdmins.Add(orderAdmin);
dbContext.SaveChanges();
```

#### Generated sql is

```sql
exec sp_executesql N'SET NOCOUNT ON;
INSERT INTO [dbo].[OrderOwner] ([UserId], [OrderId])
VALUES (@p0, @p1);
',N'@p0 int,@p1 int',@p0=1,@p1=100

exec sp_executesql N'SET NOCOUNT ON;
INSERT INTO [dbo].[OrderAdmin] ([OrderId], [AdminId])
VALUES (@p2, @p3);
',N'@p2 int,@p3 int',@p2=1,@p3=100
```

Configuration is
```c#
internal sealed class OrderConfiguration : IEntityTypeConfiguration<Order>
{
	public void Configure(EntityTypeBuilder<Order> _)
	{
		_.HasKey(x => x.Id);
		_.Property(x => x.Id).UseIdentityColumn();
	}
}

internal sealed class UserConfiguration : IEntityTypeConfiguration<User>
{
	public void Configure(EntityTypeBuilder<User> _)
	{
		_.HasKey(x => x.Id);
		_.Property(x => x.Id).UseIdentityColumn();
	}
}

internal sealed class AdminConfiguration : IEntityTypeConfiguration<Admin>
{
	public void Configure(EntityTypeBuilder<Admin> _)
	{
		_.HasKey(x => x.Id);
		_.Property(x => x.Id).ValueGeneratedNever();

		_.HasOne(x => x.User)
		    .WithOne()
		    .IsRequired()
		    .HasForeignKey<Admin>(x => x.Id)
		    .OnDelete(DeleteBehavior.SetNull);
	}
}

internal sealed class OrderOwnerConfiguration : IEntityTypeConfiguration<OrderOwner>
{
	public void Configure(EntityTypeBuilder<OrderOwner> _)
	{
		_.HasKey(x => new {x.UserId, x.OrderId});
		_.Property(x => x.OrderId).ValueGeneratedNever();
		_.Property(x => x.UserId).ValueGeneratedNever();
		_.HasOne(a => a.Order)
			.WithMany()
			.IsRequired()
			.HasForeignKey(a => a.OrderId)
			.OnDelete(DeleteBehavior.SetNull);

		_.HasOne(a => a.User)
			.WithMany()
			.IsRequired()
			.HasForeignKey(a => a.UserId)
			.OnDelete(DeleteBehavior.SetNull);

		_.HasOne(a => a.OrderAdmin)
			.WithOne(b => b.OrderOwner)
			.IsRequired()
			.HasForeignKey<OrderAdmin>(a => new {a.OrderId, a.AdminId})
			.OnDelete(DeleteBehavior.SetNull);
	}
}

internal sealed class OrderAdminConfiguration : IEntityTypeConfiguration<OrderAdmin>
{
	public void Configure(EntityTypeBuilder<OrderAdmin> _)
	{
		_.HasKey(e => new {e.OrderId, e.AdminId});
		_.Property(x => x.OrderId).ValueGeneratedNever();
		_.Property(x => x.AdminId).ValueGeneratedNever();

		_.HasOne(a => a.Order)
			.WithMany()
			.IsRequired()
			.HasForeignKey(a => a.OrderId)
			.OnDelete(DeleteBehavior.SetNull);

		_.HasOne(a => a.Admin)
			.WithMany()
			.IsRequired()
			.HasForeignKey(a => a.AdminId)
			.OnDelete(DeleteBehavior.SetNull);
	}
}
```

Attaching the listing to reproduce it
[Repro.zip](https://github.com/dotnet/efcore/files/6173160/Repro.zip)

### Error is
```
An error occurred while updating the entries. See the inner exception for details.
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Repro.Program.Main(String[] args) in D:\dev\Repro\Program.cs:line 30
   
The INSERT statement conflicted with the FOREIGN KEY constraint "FK_OrderAdmin_OrderOwner". The conflict occurred in database "", table "dbo.OrderOwner". The statement has been terminated.
      at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
```

### Provider and version information

EF Core version: 3.1.12
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 4.8
Operating system: Windows 10
IDE: Visual Studio 2019 16.3

**Comment by ajcvickers** [comment]
@v-zubritsky The order of the parts in a composite key is significant. What would you suggest we do differently here?

**Comment by v-zubritsky** [comment]
@ajcvickers Order is significant for sure, and it works well with attributes, where you have Order property, if I'm not mistaken. But this is not obvious in case of anonymous objects, where order of properties doesn't usually matter. So as I said this should either work automatically (not sure if it's possible though) or fail upon model validation.

Otherwise this api is too easy to misuse and could probably be considered for deprecation. `nameof` and explicit order as  arguments will be a better alternative.

Mentioning this nuance in the docs is the least possible improvement here :)

**Comment by ajcvickers** [comment]
@v-zubritsky Key ordering for composite keys with attributes was/is fundamentally broken in EF6, and is not yet implemented for EF Core.

The fluent API for keys had been this way since EF 4.1 in 2011 and I haven't heard until now of people being confused by it, so I don't think we're going to change this.
