### ISSUE TITLE
Many-to-many with surrogate key and change tracker causes FK violation

### ISSUE THREAD

**Issue by Marsellus47** [dotnet/efcore#24466]
## File a bug

I have many-to-many relation with an explicit join table containing a surrogate key. I override SaveChangesAsync in my DB context to fill the fields of the interface, that my entities implement, based on the changes in ChangeTracker. Saving changes fails on foreign key violation when I try to insert or edit an entity with the related entity(ies).

### Include your code
```C#
// Entities
public interface IMyInterface<T>
{
    public T Id { get; set: }
    public string MyField { get; set; }
}

public class Foo : IMyInterface<Guid>
{
    public string Name { get; set; }
    public ICollection<Bar> Bars { get; set; } = new List<Bar>();
}

public class Bar : IMyInterface<int>
{
    public string Name { get; set; }
    public ICollection<Foo> Foos { get; set; } = new List<Foo>();
}

public class Baz : IMyInterface<int>
{
    public Guid FooId { get; set; }
    public int BarId { get; set; }
    public Foo Foo { get; set; }
    public Bar Bar { get; set; }
}

// DbContext
public class MyDbContext : Microsoft.EntityFrameworkCore.DbContext
{
    public MyDbContext(DbContextOptions<TestDbContext> options) : base(options) { }

    public DbSet<Foo> Foo { get; set; }

    public DbSet<Bar> Bar { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Foo>(entity =>
        {
            entity.HasKey(foo => foo.Id);
            entity.Property(foo => foo.Name).IsRequired();

            entity
                .HasMany(foo => foo.Bars)
                .WithMany(bar => bar.Foos)
                .UsingEntity<Baz>(
                    builder => builder
                        .HasOne(baz => baz.Bar)
                        .WithMany()
                        .HasForeignKey(baz => baz.BarId)
                        .OnDelete(DeleteBehavior.Cascade),
                    builder => builder
                        .HasOne(baz => baz.Foo)
                        .WithMany()
                        .HasForeignKey(baz => baz.FooId)
                        .OnDelete(DeleteBehavior.Cascade));
        });

        modelBuilder.Entity<Bar>(entity =>
        {
            entity.HasKey(bar => bar.Id);
            entity.Property(bar => bar.Name).IsRequired();
        });
    }

    public override Task<int> SaveChangesAsync(CancellationToken cancellationToken = new CancellationToken())
    {
        var entries = ChangeTracker.Entries<IMyInterface>().Where(e => e.State == EntityState.Added || e.State == EntityState.Modified);
        foreach (var entry in entries)
        {
            var entity = entry.Entity;
            if(entry.State == EntityState.Added)
            {
                entity.MyField = "added";
            }
            else
            {
                entity.MyField = "edited";
            }
        }
        
        return base.SaveChangesAsync(cancellationToken);
    }
}

// business layer
// MyDbContext dbContext from constructor injection
var foo = new Foo
{
    Name = "foo",
    Bars = new List<Bar>
    {
        new Bar
        {
            Name = "bar 1"
        },
        new Bar
        {
            Name = "bar 2"
        }
    }
}

dbContext.Add(foo);
await dbContext.SaveChangesAsync();  // throws

```
### Include stack traces

```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Baz_Bar_BarId". The conflict occurred in database "Test", table "dbo.Bar", column 'Id'.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:3d9a5d08-58c2-4c2a-b4ea-2b6098f17e67
Error Number:547,State:0,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

My overridden SaveChangesAsync works only when:
- there's no surrogate key in Baz table => I need it because I have a nested table below Baz and I don't want FK point to composite PK
- or I don't use ChangeTracker => I need it because of my custom logic to fill column(s) of IMyInterface<T> in a generic way. I found out that ChangeTracker causes the exception also when it doesn't find anything by calling ChangeTracker.Entries<IMyInterface>().ToList(). When I call just ChangeTracker.Entries().ToList(); it correctly finds out which entities have been changed, it just applies the changes in an incorrect order. I assume that it wants to insert Baz before Bar.
- or I don't use a new many-to-many feature of Entity Framework

### Include provider and version information

EF Core version: 5.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.9.1

**Comment by ajcvickers** [comment]
Minimal repro:

```C#
public class Foo
{
    public Guid Id { get; set; }
    public ICollection<Bar> Bars { get; set; } = new List<Bar>();
}

public class Bar
{
    public int Id { get; set; }
    public ICollection<Foo> Foos { get; set; } = new List<Foo>();
}

public class Baz
{
    public int Id { get; set; }
    public Guid FooId { get; set; }
    public int BarId { get; set; }
    public Foo Foo { get; set; }
    public Bar Bar { get; set; }
}

public class MyDbContext : DbContext
{
    public DbSet<Foo> Foo { get; set; }
    public DbSet<Bar> Bar { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(Your.ConnectionString)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Foo>(entity =>
        {
            entity
                .HasMany(foo => foo.Bars)
                .WithMany(bar => bar.Foos)
                .UsingEntity<Baz>(
                    builder => builder
                        .HasOne(baz => baz.Bar)
                        .WithMany()
                        .HasForeignKey(baz => baz.BarId)
                        .OnDelete(DeleteBehavior.Cascade),
                    builder => builder
                        .HasOne(baz => baz.Foo)
                        .WithMany()
                        .HasForeignKey(baz => baz.FooId)
                        .OnDelete(DeleteBehavior.Cascade));
        });

        modelBuilder.Entity<Bar>();
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new MyDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();
            var foo = new Foo
            {
                Bars = new List<Bar>
                {
                    new Bar
                    {
                    },
                    new Bar
                    {
                    }
                }
            };

            context.Add(foo);
            context.SaveChanges();
        }
    
        using (var context = new SomeDbContext())
        {
        }
    }
}
```

**Comment by ajcvickers** [comment]
@AndriySvyryd This looks like an issue with propagation of values in the update pipeline. Before saving, the state manager looks like this:

```
Bar {Id: -2147482647} Added
  Id: -2147482647 PK Temporary
  Foos: [{Id: f8e051b8-f00e-47ac-7af2-08d8efa89601}]
Bar {Id: -2147482646} Added
  Id: -2147482646 PK Temporary
  Foos: [{Id: f8e051b8-f00e-47ac-7af2-08d8efa89601}]
Baz {Id: -2147482647} Added
  Id: -2147482647 PK Temporary
  BarId: -2147482647 FK Temporary
  FooId: 'f8e051b8-f00e-47ac-7af2-08d8efa89601' FK
  Bar: {Id: -2147482647}
  Foo: {Id: f8e051b8-f00e-47ac-7af2-08d8efa89601}
Baz {Id: -2147482646} Added
  Id: -2147482646 PK Temporary
  BarId: -2147482646 FK Temporary
  FooId: 'f8e051b8-f00e-47ac-7af2-08d8efa89601' FK
  Bar: {Id: -2147482646}
  Foo: {Id: f8e051b8-f00e-47ac-7af2-08d8efa89601}
Foo {Id: f8e051b8-f00e-47ac-7af2-08d8efa89601} Added
  Id: 'f8e051b8-f00e-47ac-7af2-08d8efa89601' PK
  Bars: [{Id: -2147482647}, {Id: -2147482646}]
```

The update pipeline saves the non-join entities, but then fails to use the generated keys when saving the join entity:

```
info: 3/25/2021 09:09:50.155 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [Bar]
      DEFAULT VALUES;
      SELECT [Id]
      FROM [Bar]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
info: 3/25/2021 09:09:50.171 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [Bar]
      DEFAULT VALUES;
      SELECT [Id]
      FROM [Bar]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
info: 3/25/2021 09:09:50.189 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (12ms) [Parameters=[@p0='9d17880a-c367-41a6-f538-08d8efa86aee'], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [Foo] ([Id])
      VALUES (@p0);
fail: 3/25/2021 09:09:50.193 RelationalEventId.CommandError[20102] (Microsoft.EntityFrameworkCore.Database.Command)
      Failed executing DbCommand (2ms) [Parameters=[@p0='-2147482647', @p1='9d17880a-c367-41a6-f538-08d8efa86aee'], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [Baz] ([BarId], [FooId])
      VALUES (@p0, @p1);
      SELECT [Id]
      FROM [Baz]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
fail: 3/25/2021 09:09:50.210 CoreEventId.SaveChangesFailed[10000] (Microsoft.EntityFrameworkCore.Update)
      An exception occurred in the database while saving changes for context type 'MyDbContext'.
      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
       ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Baz_Bar_BarId". The conflict occurred in database "Blogs", table "dbo.Bar", column 'Id'.
      The statement has been terminated.
         at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
         at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
         at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
         at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
         at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
         at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
         at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
         at System.Data.Common.DbCommand.ExecuteReader()
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
      ClientConnectionId:43b9f005-7198-4b7e-a5e3-f63e350ba88d
      Error Number:547,State:0,Class:16
         --- End of inner exception stack trace ---
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
         at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Unhandled exception. Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Baz_Bar_BarId". The conflict occurred in database "Blogs", table "dbo.Bar", column 'Id'.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
ClientConnectionId:43b9f005-7198-4b7e-a5e3-f63e350ba88d
Error Number:547,State:0,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Program.Main() in C:\Stuff\AllTogetherNow\FiveOh\Program.cs:line 111
```

Compare this to the case where there is no surrogate key:

```
info: 3/25/2021 09:04:19.354 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [Bar]
      DEFAULT VALUES;
      SELECT [Id]
      FROM [Bar]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
info: 3/25/2021 09:04:19.377 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [Bar]
      DEFAULT VALUES;
      SELECT [Id]
      FROM [Bar]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
info: 3/25/2021 09:04:19.394 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (12ms) [Parameters=[@p0='8941bf43-1f28-4314-f041-08d8efa7a5c2'], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [Foo] ([Id])
      VALUES (@p0);
info: 3/25/2021 09:04:19.395 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (1ms) [Parameters=[@p0='1', @p1='8941bf43-1f28-4314-f041-08d8efa7a5c2'], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [Baz] ([BarId], [FooId])
      VALUES (@p0, @p1);
info: 3/25/2021 09:04:19.396 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (0ms) [Parameters=[@p0='2', @p1='8941bf43-1f28-4314-f041-08d8efa7a5c2'], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [Baz] ([BarId], [FooId])
      VALUES (@p0, @p1);
```

**Comment by denisstepanenko** [comment]
Is there a workaround for this issue? Thanks..

**Comment by AndriySvyryd** [comment]
This no longer repros in 6.0

@denisstepanenko You can add the entities without setting the many-to-many navigations, call `SaveChanges`, then set the navigations and call `SaveChanges` again
