### ISSUE TITLE
Exception occurs when running AsSplitQuery on IQueryable retrieved using reflection using In Memory provider

### ISSUE THREAD

**Issue by rmallinson** [dotnet/efcore#24481]
Queries using the new 'AsSplitQuery' fail when using Memory Provider
Error: System.InvalidOperationException: 
Possibly related to: [22034](https://github.com/dotnet/efcore/issues/22034) 

Exception details

```
Unhandled exception. System.InvalidOperationException: The LINQ expression 'DbSet<MyEntity>()
    .Include("MyChildEntities")
    .AsSplitQuery()
    .FirstOrDefault()' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', 
or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at SplitQuery.Program.Main(String[] args) 
```

### Provider and version information

EF Core version: 5.0.4
Database provider: Microsoft.EntityFrameworkCore.InMemory
Target framework: NET5.0
Operating system: Windows 10 19042.867
IDE: vs code 1.54.3

Sample Project demonstrating issue:
[SplitQuery.zip](https://github.com/dotnet/efcore/files/6184693/SplitQuery.zip)

**Comment by smitpatel** [comment]
Looking at the Program.cs file, the issue is in your custom `GetQueryable` method rather than EF Core. Likely cause that it is not generating same expression tree as what EF Core query would generate. The missing info is that DbSet in EF Core query normally generates a `QueryRootExpression` rather than `DbSet<T>` inside the tree.

**Comment by ajcvickers** [comment]
@rmallinson  After removing the reflection code this is the equivalent of what you are doing:

```
            var dbSet1 = (IQueryable<MyEntity>)context.MyEntities;
            var results1 = dbSet1.Include("MyChildEntities").AsSplitQuery().FirstOrDefault();

            var dbSet2 = (IQueryable<MyBaseEntity>)context.MyEntities;
            var results2 = dbSet2.Include("MyChildEntities").AsSplitQuery().FirstOrDefault();
```

Changing the generic type of the IQueryable causes EF to attempt to create a query for that type, which then fails since the DbSet has not been created for the base entity, which in this case isn't even a mapped entity type.

**Comment by rmallinson** [comment]
@ajcvickers @smitpatel Thanks for the reply!
I'm a bit confused here though, because if I'm understanding you correctly, the query for the variable `failsForSomeUnknownReason` shouldn't work at all since EF is trying to create the query for the base type `MyBaseEntity`, but if I remove the `.AsSplitQuery()` it runs as expected.
Updated query for `failsForSomeUnknownReason` which runs successfully:
```
            var failsForSomeUnknownReason = context
                .GetQueryable<MyBaseEntity>(nameof(MyEntity))
                .Include(nameof(MyEntity.MyChildEntities))
                .FirstOrDefault();
```
