### ISSUE TITLE
Cannot load polymorphic many-to-many with include but can check with any

### ISSUE THREAD

**Issue by royberris** [dotnet/efcore#24566]
## Ask a question

I have a structure where I can implemented a many-to-many relationship to my entities dynamically. On the other side is a item filter, so we can dynamically filter items. I will include examples of this below. 

I read on issue https://github.com/dotnet/efcore/issues/23362 that this is not supported. But why am I able to do checks in my where clause on the relationship but not include it. Or is there something I am doing wrong? How can I make this work?

### Include your code

```C#
public interface IFilteredEntity
{
  public int Id { get; set }
  
   public ICollection<ItemFilter> Filters { get; set; }
}

public class Item : IFilteredEntity
{
  public int Id { get; set; }

  public string Name { get; set; }  

  public ICollection<ItemFilter Filters { get; set; }
}

public class ItemFilter
{
  public int Id { get; set; }
  
  public string Key { get; set }

  // filter logic implementation...
  // not important for example
}

// to configure many-to-many
public class ItemItemFilterPivot
{
  public Item Item { get; set }
  public int ItemId { get; set; }

  public ItemFilter ItemFilter { get; set; }
  public int ItemFilterId { get; set }
}
```

In my `OnModelCreating`

```C#
modelBuilder.Entity<Item>()
  .HasMany(p => p.Filters)
  .WithMany("Entities")
  .UsingEntity<ItemItemFilterPivot>(
      pivot => pivot.HasOne(p => p.ItemFilter)
          .WithMany()
          .HasForeignKey(p => p.ItemFilterId)
          .IsRequired(),
      pivot => pivot.HasOne(p => p.Item)
          .WithMany()
          .HasForeignKey(p => p.ItemId)
          .IsRequired());
```

I have a method so I can dynamically get a list of item filters (as a dto) that states if the item filter is enabled for that item. This has to be a generic so that we can parse in whatever we want (as long as it implements `IFilteredEntity`)

```C#
public class ItemFilterDto
{
  public int Id { get; set }

  public string Key { get; set; }

  public bool Enabled { get; set }
}
```

In a repository:

```C#
private Task<bool> IsEnabledFor<TEntity>(int entityId, int filterId)
    where TEntity : class, IFilteredEntity
{
    var entityDbSet = Context.Set<TEntity>();

    return entityDbSet.AsQueryable()
        .Where(i => i.Id == entityId)
        .AnyAsync(i => i.Filters.Any(j => j.Id == filterId));
}

public async Task<IEnumerable<ItemFilterSummary>> GetAsync<TEntity>(int entityId, params string[] filterKeys)
    where TEntity : class, IFilteredEntity
{
    var filters = // get list of filters and put it in the dto;

    foreach (var filter in filters)
    {
        filter.Enabled = await IsEnabledFor<TEntity>(entityId, filter.Id);
    }

    return filters;
}
```

Above code works. I can check my filters with the `AnyAsync(i => i.Filters.Any(...))`. So I am using the polymorphic many-to-many collection to check if any items have the key. 

Now I want to enable / disable a item filter for a item, and this is where it goes wrong.

```C#
private Task<TEntity> GetEntityAsync<TEntity>(int entityId)
    where TEntity : class, IFilteredEntity
{
    var entityDbSet = Context.Set<TEntity>();

    return entityDbSet.AsQueryable()
        .Include(i => i.Filters) // exception thrown here
        .FirstOrDefaultAsync(i => i.Id == entityId);
}

public async Task EnableFilterAsync<TEntity>(int entityId, string key)
    where TEntity : class, IFilteredEntity
{
    var filter = ;// get filter by key

    if (await IsEnabledFor<TEntity>(entityId, filter.Id))
    {
        return;
    }

    var entity = await GetEntityAsync<TEntity>(entityId);

    entity.Filters.Add(filter);

    await Context.SaveChangesAsync();
}
```

At the `Include` my exception is thrown. Why can I check the collection with a `Any` or `All` or whatever, but not include it query.
And how can I maintain this abstracted logic without having to specify the many-to-many pivot class. Because that takes away the complete abstraction with a `IFilteredEntity`. 

### Include stack traces

```
System.ArgumentException: Method 'Boolean Add(System.Object, System.Object, Boolean)' declared on type 'Microsoft.EntityFrameworkCore.Metadata.IClrCollectionAccessor' cannot be called with instance of type 'System.Object'
         at System.Linq.Expressions.Expression.ValidateCallInstanceType(Type instanceType, MethodInfo method)
         at System.Linq.Expressions.Expression.ValidateMethodAndGetParameters(Expression instance, MethodInfo method)
         at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0, Expression arg1, Expression arg2)
         at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.AddToCollectionNavigation(ParameterExpression entity, ParameterExpression relatedEntity, INavigationBase navigation)
         at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.GenerateFixup(Type entityType, Type relatedEntityType, INavigationBase navigation, INavigationBase inverseNavigation)
         at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.VisitExtension(Expression extensionExpression)
         at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.ProcessShaper(Expression shaperExpression, RelationalCommandCache& relationalCommandCache, LambdaExpression& relatedDataLoaders)
         at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.VisitShapedQuery(ShapedQueryExpression shapedQueryExpression)
         at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
         at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
         at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
         at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
         at Focus.Common.Infrastructure.ItemFilter.ItemFilterRepository.GetEntityAsync[TEntity](Int32 entityId) in D:\Appec\FOCUS\Focus-Backend\Focus.Common\Infrastructure\ItemFilter\ItemFilterRepository.cs:line 50
         at Focus.Common.Infrastructure.ItemFilter.ItemFilterRepository.DisableFilterAsync[TEntity](Int32 entityId, String key) in D:\Appec\FOCUS\Focus-Backend\Focus.Common\Infrastructure\ItemFilter\ItemFilterRepository.cs:line 95
         at Focus.CMS.Components.Feed.FilterComponent.FilterChange(ItemFilterSummary filter) in D:\Appec\FOCUS\Focus-Backend\Focus.CMS\Components\Feed\FilterComponent.razor:line 50
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

### Include provider and version information

EF Core version: 5.0.0
Database provider: SqlServer
Target framework: `net5.0`
Operating system: Windows 10
IDE: Visual Studio 2019 16.9.3

**Comment by ajcvickers** [comment]
@royberris There is not enough here for me to be able to reproduce this. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by royberris** [comment]
@ajcvickers after some research (lots of research) I came across issue https://github.com/dotnet/efcore/issues/23717. The workaround you mentioned there worked for me. Making a private property that resembles the `.WithMany("Entities")`. 

I honestly found it very hard to find a solution. This is not common code which I am working with here but the error messages are sometimes very unclear, the included stack trace did not point me in any right direction. Anyway thanks for replying, I will close this issue.
