### ISSUE TITLE
TableValuedFunctionExpression does not take the IsBuiltIn option into account (DbFunctions)

### ISSUE THREAD

**Issue by jgveire** [dotnet/efcore#24569]
The TableValuedFunctionExpression does not take IsBuiltIn option into account. This results in brackets being added to my DbFunction.

EF Core 5 generates the following SQL:
```SQL
SELECT [c].[Id], [c].[Data]
FROM [Cars] AS [c]
CROSS APPLY [OPENJSON]([c].[Data], N'$.items') AS [o]
WHERE JSON_VALUE([o].[Value], N'$.id') = 1
```
The OPENJSON function should not have backets because the IsBuiltIn option is set to true.
```C#
[DbFunction("OPENJSON", IsBuiltIn = true, Schema = "", IsNullable = false)]
public static IQueryable<JsonResult> OpenJson(string column, string jsonPath) { ... }
```
The expected result is:
```SQL
SELECT [c].[Id], [c].[Data]
FROM [Cars] AS [c]
CROSS APPLY OPENJSON([c].[Data], N'$.items') AS [o]
WHERE JSON_VALUE([o].[Value], N'$.id') = 1
```
## Solution
The following code should be changed in the QuerySqlGenerator.cs in the EFCore.Relational project to solve this issue:

```C#
protected override Expression VisitTableValuedFunction(TableValuedFunctionExpression tableValuedFunctionExpression)
{
    Check.NotNull(tableValuedFunctionExpression, nameof(tableValuedFunctionExpression));

    if (!string.IsNullOrEmpty(tableValuedFunctionExpression.StoreFunction.Schema))
    {
        _relationalCommandBuilder
            .Append(_sqlGenerationHelper.DelimitIdentifier(tableValuedFunctionExpression.StoreFunction.Schema))
            .Append(".");
    }

    // OLD CODE
    //_relationalCommandBuilder
    //    .Append(_sqlGenerationHelper.DelimitIdentifier(tableValuedFunctionExpression.StoreFunction.Name))
    //    .Append("(");
  
    // NEW CODE
    var name = tableValuedFunctionExpression.StoreFunction.IsBuiltIn
        ? tableValuedFunctionExpression.StoreFunction.Name
        : _sqlGenerationHelper.DelimitIdentifier(tableValuedFunctionExpression.StoreFunction.Name);
    _relationalCommandBuilder
        .Append(name)
        .Append("(");

    GenerateList(tableValuedFunctionExpression.Arguments, e => Visit(e));

    _relationalCommandBuilder
        .Append(")")
        .Append(AliasSeparator)
        .Append(_sqlGenerationHelper.DelimitIdentifier(tableValuedFunctionExpression.Alias));

    return tableValuedFunctionExpression;
}
```

## Steps to reproduce
Run the unit test below or download the test solution below.

```C#
namespace UnitTestProject
{
    using Microsoft.EntityFrameworkCore;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;


    [TestClass]
    public class OpenJsonTest
    {
        private static readonly Guid CarId = new Guid("A7623A15-BB2A-4C0E-BE92-242D2F43FC6F");

        [TestMethod]
        public void When_open_json_method_is_called_then_no_exception_should_be_thrown()
        {
            // Arrange
            var builder = new DbContextOptionsBuilder();
            builder.UseSqlServer(@"Server=.;Database=TestDB;Trusted_Connection=True;MultipleActiveResultSets=true;");
            using (var dbContext = new TestDbContext(builder.Options))
            {
                InitDatabase(dbContext);

                // Act
                var query = from car in dbContext.Cars
                            from data in CustommDbFunctions.OpenJson(car.Json, "$.items")
                            where car.Id == CarId
                                && CustommDbFunctions.JsonValue(data.Value, "$.id") == 1
                            select car;
                var items = query.ToList();

                // Assert
                Assert.AreEqual(1, items.Count);
            }
        }

        private static void InitDatabase(TestDbContext dbContext)
        {
            dbContext.Database.EnsureCreated();
            if (!dbContext.Cars.Any())
            {
                var json = "{ \"name\": \"test\", \"items\": [{\"id\": 1},{\"id\": 2}] }";
                dbContext.Cars.Add(new Car(CarId, json));
                dbContext.SaveChanges();
            }
        }
    }

    public static class CustommDbFunctions
    {
        [DbFunction("JSON_VALUE", IsBuiltIn = true, IsNullable = false)]
        public static int JsonValue(string column, string jsonPath)
        {
            throw new NotSupportedException();
        }

        [DbFunction("OPENJSON", IsBuiltIn = true, Schema = "", IsNullable = false)]
        public static IQueryable<JsonResult> OpenJson(string column, string jsonPath)
        {
            throw new NotSupportedException();
        }

        [Keyless]
        public class JsonResult
        {
            public string Value { get; set; }
        }
    }

    public class Car
    {
        public Car()
        {
        }

        public Car(Guid id, string json)
        {
            Id = id;
            Json = json ?? throw new ArgumentNullException(nameof(json));
        }

        [Key]
        public Guid Id { get; set; } = Guid.NewGuid();

        public string Json { get; set; } = "{}";
    }

    public class TestDbContext : DbContext
    {
        public TestDbContext(DbContextOptions options)
            : base(options)
        {
        }

        public DbSet<Car> Cars { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.HasDbFunction(() => CustommDbFunctions.JsonValue(string.Empty, string.Empty));
            modelBuilder.HasDbFunction(() => CustommDbFunctions.OpenJson(string.Empty, string.Empty)).HasStoreType("nvarchar(max)");

        }
    }
}
```

## Provider and version information

EF Core version: 5.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:.NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.8.2

## Exception message
```
Invalid object name 'OPENJSON'.
```

## Stack trace
```
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at UnitTestProject1.OpenJsonTest.When_open_json_method_is_called_no_exception_should_be_thrown() in c:\Git\OpenJson\OpenJson\UnitTestProject1\UnitTest1.cs:line 31
```

**Comment by jgveire** [comment]
[UnitTestProject1.zip](https://github.com/dotnet/efcore/files/6249878/UnitTestProject1.zip)

**Comment by jgveire** [comment]
Created pull request for the issue #24570

**Comment by jgveire** [comment]
I found a workaround by making use of the DbCommandInterceptor.

```C#
public class OpenJsonQueryCommandInterceptor : DbCommandInterceptor
{
    public override InterceptionResult<DbDataReader> ReaderExecuting(
        DbCommand command,
        CommandEventData eventData,
        InterceptionResult<DbDataReader> result)
    {
        ManipulateCommand(command);

        return result;
    }

    public override ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(
        DbCommand command,
        CommandEventData eventData,
        InterceptionResult<DbDataReader> result,
        CancellationToken cancellationToken = default)
    {
        ManipulateCommand(command);

        return new ValueTask<InterceptionResult<DbDataReader>>(result);
    }

    private static void ManipulateCommand(DbCommand command)
    {
        if (command.CommandText.Contains("[OPENJSON](", StringComparison.Ordinal))
        {
            command.CommandText = command.CommandText.Replace("[OPENJSON](", "OPENJSON(");
        }
    }
}

public sealed class ExampleDbContext : DbContext, IWerkprogrammaGemakDbContext
{
    private static readonly OpenJsonQueryCommandInterceptor Interceptor = new OpenJsonQueryCommandInterceptor();

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);
        optionsBuilder.AddInterceptors(Interceptor);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.HasDbFunction(() => JsonFunctions.OpenJson(string.Empty, string.Empty))
            .HasStoreType("nvarchar(max)")
            .HasParameter("column").HasStoreType("nvarchar(max)");
    }
}

public static partial class JsonFunctions

    [DbFunction("OPENJSON", IsBuiltIn = true, Schema = "", IsNullable = false)]
    public static IQueryable<JsonResult> OpenJson(object column, string jsonPath)
    {
        throw new NotSupportedException();
    }
}

```
