### ISSUE TITLE
InvalidOperationException when navigating two nullable references in a query

### ISSUE THREAD

**Issue by nikonthethird** [dotnet/efcore#24673]
EF Core raises `InvalidOperationException: Nullable object must have a value.` when navigating two nullable references in a query.

[A reproduction can be found here.](https://github.com/nikonthethird/ef-core-nullable-object)

```c#
await context.As
.Select(a => new HashSet<Int32>(from b in a.Bs select b.C!.D!.Id))
.ToArrayAsync();
```
The error occurs at the line containing `b.C!.D!.Id`.

Exception:

```
An exception of type 'System.InvalidOperationException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Nullable object must have a value.'
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_NoValue()
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.<PopulateCollection>g__ProcessCurrentElementRow|65_1[TCollection,TElement,TRelatedEntity](<>c__DisplayClass65_0`3& )
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.PopulateCollection[TCollection,TElement,TRelatedEntity](Int32 collectionId, QueryContext queryContext, DbDataReader dbDataReader, SingleQueryResultCoordinator resultCoordinator, Func`3 parentIdentifier, Func`3 outerIdentifier, Func`3 selfIdentifier, IReadOnlyList`1 parentIdentifierValueComparers, IReadOnlyList`1 outerIdentifierValueComparers, IReadOnlyList`1 selfIdentifierValueComparers, Func`5 innerShaper)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.<MoveNextAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__65`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__65`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToArrayAsync>d__66`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EfTest.Program.<Main>d__0.MoveNext() in /home/nikon/Documents/Programming/Tests/EfTest/Program.cs:line 49
```

EF Core version: 5.0.5
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 5
Operating system: Ubuntu 20.04
IDE: Visual Studio Code 1.55.2

**Comment by nikonthethird** [comment]
I found a workaround. The problem seems to be that the sequence `from b in a.Bs select b.C!.D!.Id` is strictly `Int32`, so if we change it to yield `Int32?` instead, the exception goes away. I introduced a helper function that can create a `HashSet` from `Int32?`:

```c#
static class Program {
    static HashSet<T> CreateFromNullable<T>(IEnumerable<T?> items) where T : struct =>
        new(from item in items where item.HasValue select item.Value);
        
    static async Task Main() {
        var context = new MyContext();
        await context.Database.MigrateAsync();

        await context.Bs.AddAsync(new B { A = new() });
        await context.SaveChangesAsync();

        await context.As
        .Select(a => CreateFromNullable(from b in a.Bs select (Int32?)b.C!.D!.Id))
        .ToArrayAsync();
    }
}
```

This seems to work. I wonder if this is a good way to solve it though?

**Comment by smitpatel** [comment]
`b.C.D.Id` returns null from database because `b.C` is null so exception is valid. If you want to filter out values when it is not null then you can write `from b in a.Bs where b.C!.D!.Id.HasValue select b.C!.D!.Id`

**Comment by nikonthethird** [comment]
I tried that too, but since `D.Id` is of type `Int32` and not `Int32?`, I get this:
![image](https://user-images.githubusercontent.com/15893812/115080481-1b7fa300-9f03-11eb-9783-e5b935b4205a.png)

So is the workaround with the cast to `(Int32?)` an acceptable solution?

**Comment by smitpatel** [comment]
What is acceptable depends on what you want to write?
Since the issue here is that C & D are nullable navigations if you are going to put `!` on it to remove nullable error then you need to cast resulting type to nullable (EF Core will make it null-safe path) or you need to check for those navigations not being null else filter out from result if navigations are null.
