### ISSUE TITLE
Offset is not preserved when saving DateTimeOffset to Cosmos

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#24684]
Failed tests

```
Microsoft.EntityFrameworkCore.Cosmos.BuiltInDataTypesCosmosTest.Can_query_using_any_data_type
Assert.Equal() Failure\r\nExpected: 0001-01-01T00:00:00.0000000+00:00\r\nActual:   0001-01-01T00:00:00.0000000-08:00
   at Microsoft.EntityFrameworkCore.BuiltInDataTypesTestBase`1.QueryBuiltInDataTypesTest[TEntity](EntityEntry`1 source) in C:\dotnet\efcore\test\EFCore.Specification.Tests\BuiltInDataTypesTestBase.cs:line 475
   at Microsoft.EntityFrameworkCore.BuiltInDataTypesTestBase`1.Can_query_using_any_data_type() in C:\dotnet\efcore\test\EFCore.Specification.Tests\BuiltInDataTypesTestBase.cs:line 183

Microsoft.EntityFrameworkCore.Cosmos.BuiltInDataTypesCosmosTest.Can_query_using_any_data_type_shadow
Assert.Equal() Failure\r\nExpected: 0001-01-01T00:00:00.0000000+00:00\r\nActual:   0001-01-01T00:00:00.0000000-08:00
   at Microsoft.EntityFrameworkCore.BuiltInDataTypesTestBase`1.QueryBuiltInDataTypesTest[TEntity](EntityEntry`1 source) in C:\dotnet\efcore\test\EFCore.Specification.Tests\BuiltInDataTypesTestBase.cs:line 475
   at Microsoft.EntityFrameworkCore.BuiltInDataTypesTestBase`1.Can_query_using_any_data_type_shadow() in C:\dotnet\efcore\test\EFCore.Specification.Tests\BuiltInDataTypesTestBase.cs:line 194
```

**Comment by AndriySvyryd** [comment]
Consider adding a warning
