### ISSUE TITLE
`DbContext.Attach` throws if entity exists in different navigation properties.

### ISSUE THREAD

**Issue by lucent-sea** [dotnet/efcore#24720]
I'm not sure if this behavior is by design, so figured I'd post this as a question.

Consider the below query.  `Schedule.Creator` is a navigation property to a `User` entity.  `Schedule.Devices[0].DeviceGroup.Users[0]` is a navigation to the same `User` entity.

When attempting to attach the detached entity, it throws the following error: 

```
System.InvalidOperationException: The instance of entity type 'User' cannot be tracked because another instance with the key value '{Id}' is already being tracked.
```

I understand the error, but it seems like the ChangeTracker should be able to handle this.  Especially since the documentation states:

> A recursive search of the navigation properties will be performed to find reachable entities that are not already being tracked by the context. All entities found will be tracked by the context.

It seems logical to me that the same entity might appear in different navigation properties.

If I remove `AsNoTracking`, make changes to the `mySchedule.Creator`, and save changes, it doesn't have a problem.  The entity gets updated in both places.

```C#

private async Task<Schedule> GetSchedule(int id)
{
    using var dbContext = _dbFactory.CreateDbContext();
    
    return await dbContext.Schedules
        .Include(x => x.Creator)
        .Include(x => x.Devices)
        .ThenInclude(x => x.DeviceGroup)
        .ThenInclude(x => x.Users)
        .FirstOrDefaultAsync(x => x.Id == id);
}

private async Task UpdateSchedule(Schedule schedule)
{
    using var dbContext = _dbFactory.CreateDbContext();

    // Throws exception here.
    dbContext.Attach(mySchedule);

    // ...
}

```

Is this by design?  Is it a case of "Just don't do that"?

### Include stack traces

```
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'kOFQu9nMDgqCADPGbVvLKbl_YOwrdaWWD0j1Zq5FoDc'.
      System.InvalidOperationException: The instance of entity type 'User' cannot be tracked because another instance with the key value '{Id}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NullableKeyIdentityMap`1.Add(InternalEntityEntry entry)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
         at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
         at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
         at Microsoft.EntityFrameworkCore.DbContext.Attach[TEntity](TEntity entity)
```

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: NET 5.0
Operating system: Win 10 Pro
IDE:  Visual Studio 2019 Version 16.9.4

**Comment by skyflyer** [comment]
I believe this is by design... see my report here: #24697.

Also see this part from the documentation: https://docs.microsoft.com/en-us/ef/core/change-tracking/identity-resolution

I assume that this is happening here: EF Core will throw an exception because the entity is already tracked and when you `Attach` a graph, EF Core will find a `User` instance in the graph which is not yet tracked (it uses object instance reference comparison to detect whether an instance is already tracked[1]). When trying to track it, it finds out that it already tracks a a `User` entity with the given "key" value (which you've queried before and is therefore tracked) and so throws.

It is debatable whether this is the right thing to do, but in normal circumstances, you wouldn't have different object instances (representing the _same_ DB object). It is possible to attach a graph using a special callback and resolve "duplicates" to other instances there: https://docs.microsoft.com/en-us/ef/core/change-tracking/identity-resolution#resolve-duplicates

Also, the EF core docs explicitly [state](https://docs.microsoft.com/en-us/ef/core/change-tracking/identity-resolution#identity-resolution-and-queries):

> Do not routinely perform a no-tracking query and then attach the returned entities to the same context. This will be both slower and harder to get right than using a tracking query.

[1]: EF core change tracker check if entity is tracked by using reference equality, but throws on the same key for an instance type

**Comment by lucent-sea** [comment]
Thank you for the detailed response, @skyflyer .  Much appreciated.  :)

I've updated my original comment to more closely match the scenario where I noticed this.

I'm following the guidance here for using EF Core in a Blazor Server app:  https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-5.0

Since `Scoped` services persist for the lifetime of the SignalR connection, I'm using the `DbContextFactory` to create a new instance of the context that's immediately disposed after every query.  So the entities coming back in are always detached, and always from a different (disposed) context.

I was trying to see if I could take a shortcut and simply `Attach` or `Update` it on the new context, and have everything recursively start tracking.  But it looks like it's not supposed to work like that.  :)

**Comment by lucent-sea** [comment]
Closing since this is apparently by design.

**Comment by jmichas** [comment]
I would just like to say that after struggling with the change tracker stuff using a complex object graph it would be very nice to have the db exception include a link to https://docs.microsoft.com/en-us/ef/core/change-tracking/identity-resolution. I was able to fix my problem by writing a custom identity resolution handler. But it took me so long to find this thread and then get to the relevant documentation. If the link was in the exception I could have short cut the wrong direction I started with which took me down many a rabbit hole.

**Comment by Mattnificent** [comment]
Many thanks to @skyflyer for linking me to an actual workable, easy to understand solution to the non-idempotency of the recursive "Attach" functions provided by the EF Core public API.  That link was https://docs.microsoft.com/en-us/ef/core/change-tracking/identity-resolution#resolve-duplicates

I added this method to my context class, and it appears to safely handle the duplicates encountered by the recursive traversal of the entity/related entity graph:

    public void SafeAttach<EntityType>(EntityType entity)
    {
        ChangeTracker.TrackGraph(
            entity, node =>
            {
                var keyValue = node.Entry.Property("Id").CurrentValue;
                var entityType = node.Entry.Metadata;

                var existingEntity = node.Entry.Context.ChangeTracker.Entries()
                    .FirstOrDefault(
                        e => Equals(e.Metadata, entityType)
                                && Equals(e.Property("Id").CurrentValue, keyValue));

                if (existingEntity == null)
                {
                    Console.WriteLine($"Tracking {entityType.DisplayName()} entity with key value {keyValue}");

                    if ((long)keyValue == 0)
                    {
                        node.Entry.State = EntityState.Added;
                    }
                    else
                    {
                        node.Entry.State = EntityState.Modified;
                    }
                }
                else
                {
                    Console.WriteLine($"Discarding duplicate {entityType.DisplayName()} entity with key value {keyValue}");
                }
            });
    }

The caveats for this do not apply for any scenarios the way I use EF, and is a candidate for best practice in my book.
