### ISSUE TITLE
DbContext in ASP.NET Core throws System.ObjectDisposedException

### ISSUE THREAD

**Issue by Prajwal-Jadhav** [dotnet/efcore#24792]
I am saving a Todo model to database using EF Core in ASP.NET Core app.
But when I try to print the success message using ```Console.Writeline``` it throws ```System.ObjectDisposedException```
Here's full application code [github code link](https://github.com/Prajwal-Jadhav/ASP-To-Do) go to localhost:44308/ToDo/Create

Here's ToDo model:
``` C#
public class Todo
{
    public int Id { get; set; }

    [Required]
    [MaxLength(10)]
    public string Title { get; set; }

    public bool IsCompleted { get; set; } = false;
}
```

Here's the business logic that throws exception.

``` C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ToDoApp.Models;
using ToDoApp.Data;

namespace ToDoApp
{
    public class ToDoService
    {
        readonly ToDoContext _context;

        public ToDoService(ToDoContext context)
        {
            _context = context;
        }

        public async Task<int> CreateToDo(CreateToDoBindingModel input)
        {
            Todo todo = new()
            {
                Title = input.Title,
                IsCompleted = input.IsCompleted
            };

            _context.Add(todo);
            await _context.SaveChangesAsync();
            Console.WriteLine("Successfully saved todo.");
            return task.Id;
        }
    }
}
```
Exception Details: 

``` C#
System.ObjectDisposedException
  HResult=0x80131622
  Message=Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'ToDoContext'.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__56.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

  This exception was originally thrown at this call stack:
    Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
    Microsoft.EntityFrameworkCore.DbContext.DbContextDependencies.get()
    Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(bool, System.Threading.CancellationToken)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

```

Here's ToDoContext:
``` C#
    public class ToDoContext: DbContext
    {
        public ToDoContext(DbContextOptions<ToDoContext> options)
        : base(options)
        { }

        public DbSet<Todo> Todos { get; set; }
    }
```

Here's how it is registered in Startup.cs:
``` C#
public void ConfigureServices(IServiceCollection services)
        {
            services.AddRazorPages();

            var connectionString = Configuration["ConnectionString"];
            services.AddDbContext<ToDoContext>(options => options.UseNpgsql(connectionString));

            services.AddScoped<ToDoService>();
        }
```

Here's full application code [github code link](https://github.com/Prajwal-Jadhav/ASP-To-Do)

### Include provider and version information

EF Core version: 5.0.5
Database provider: (e.g. Npgsql.EntityFrameworkCore.PostgreSQL)
Target framework: (e.g. .NET 5.0)
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.3)

Here's full application code [github code link](https://github.com/Prajwal-Jadhav/ASP-To-Do)

**Comment by davidfowl** [comment]
This is your bug https://github.com/Prajwal-Jadhav/ASP-To-Do/blob/f72c4a151936392efad756975bed48606cb4f509/Pages/ToDo/Create.cshtml.cs#L34. There's no await here. It should look like this:

```C#
public async Task<IActionResult> OnPostAsync()
{
    if (!ModelState.IsValid)
    {
        return Page();
    }
    int id =  await _service.CreateTask(Input);
    return RedirectToPage("Index");
}
```

**Comment by Prajwal-Jadhav** [comment]
Got it, Thank you.
As you can see, I am pretty weak at asynchronous programming. Can you suggest me some learning resources so that I don't repeat the same mistake.
