### ISSUE TITLE
Unable to insert entity with view navigation property

### ISSUE THREAD

**Issue by Pzixel** [dotnet/efcore#24831]
Consider following schema: one Document table and one RoutePerformerView view, relating many-one.

Here are models that model this relationship:

```cs
    public class RoutePerformerViewEntry : IEntity<RoutePerformerViewEntry>
    {
        public Guid Id { get; init; } = null!;
        public string? Name { get; init; }
        public string? Address { get; init; }
        public string? Phone { get; init; }
        public virtual ICollection<Document> Documents { get; init; } = null!;
    }

    public class Document : IEntity<Document>
    {
        public Guid> Id { get; init; } = null!;
        public RoutePerformerViewEntry Performer { get; init; } = null!;
        public string SomeData { get; init; }
    }

...

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Document>();          
            modelBuilder.Entity<RoutePerformerViewEntry>()
                .ToView("RoutePerformersView");
        }
```

Now when I'm trying to save it:

```cs
var document = new Document
{
	Performer = new()
	{
		Id = someIdFetchedFromExternalSource
	},
	SomeData = "example"
};
_dataContext.Documents.Add(document);
await _dataContext.SaveChangesAsync();
```

I'm getting an exception:

```
[18:08:23 ERR] An exception occurred in the database while saving changes for context type 'Atlas.Documents.Storage.DataContext'.
System.InvalidOperationException: The entity type 'RoutePerformerViewEntry' is not mapped to a table, therefore the entities cannot be persisted to the database.
Use 'ToTable' in 'OnModelCreating' to map it.
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.CreateModificationCommands(IList`1 entries, IUpdateAdapter updateAdapter, Func`1 generate
ParameterName)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.BatchCommands(IList`1 entries, IUpdateAdapter updateAdapter)+MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken c
ancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken c
ancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken c
ancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancel
lationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySuc
ceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
System.InvalidOperationException: The entity type 'RoutePerformerViewEntry' is not mapped to a table, therefore the entities cannot be persisted to the database.
Use 'ToTable' in 'OnModelCreating' to map it.
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.CreateModificationCommands(IList`1 entries, IUpdateAdapter updateAdapter, Func`1 generate
ParameterName)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.BatchCommands(IList`1 entries, IUpdateAdapter updateAdapter)+MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken c
ancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken c
ancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken c
ancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancel
lationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySuc
ceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

It tries to update view but it's not nessessary - it just needs to insert a document which points to the view. View should be left untouched. 

### Include provider and version information

EF Core version: 5.0.5
Database provider: Npgsql
Target framework: NET 5.0
Operating system: Win 10 x64

**Comment by ArminShoeibi** [comment]
Hello use this code.

With EF Core 5 it is now possible to map an entity to a view when querying (or to a function or defining query), but to a table when updating:
```
modelBuilder.Entity<RoutePerformerViewEntry>().ToTable("DesiredName") .ToView("RoutePerformersView");
```

**Comment by Pzixel** [comment]
Thanks for reply. Unfortunately it doesn't work: it still tries to insert values when it shouldn't. You can see him trying to insert values:

```
[19:19:34 VRB] Executing DbCommand [Parameters=[@p0='5bb5a03c-8269-4bdc-abb1-28336ad911d9', @p1=NULL, @p2=NULL, @p3=NULL, @p4=NULL], CommandType='Text', CommandT
imeout='30']
INSERT INTO dbo."AbsolutelyMissingTableToFoolEF" ("Id", "Address", "Inn", "Name", "Phone")
VALUES (@p0, @p1, @p2, @p3, @p4);
```

However I finally figured out how to make it work:

```cs
var routePerformerViewEntry = new RoutePerformerViewEntry()
{
	Id = documentModel.PerformerId.AsIdOf<RoutePerformerViewEntry>()
};
_dataContext.Attach(routePerformerViewEntry);
var document = new Document
{
	Performer = routePerformerViewEntry,
	OwnershipType = documentModel.OwnershipType,
	EntityId = documentModel.EntityId
};
_dataContext.Documents.Add(document);
await _dataContext.SaveChangesAsync();
```

And now it works properly.

I'm feeling so dumb since I didn't figure it out myself and had to create an issue. Thanks for the hint, it helped me a lot.
