### ISSUE TITLE
Expected DELETE followed by INSERT generated in SQL, but result was UPDATE; which violates constraint of DB

### ISSUE THREAD

**Issue by karimSeghirAllPhi** [dotnet/efcore#24939]
## Expected DELETE followed by INSERT generated in SQL, but result was UPDATE; which violates constraint of DB

We have a method that inserts new records with priorities into the table. This contains indexes starting from 1.

When this method is run, the SQL generated converts this to an UPDATE query for each record that needs to be altered, even though we remove and add an entity. 

When there are separate updates for the records, at a certain point there are two of the same values inserted. This violates the constraint, which only allows unique priorities.

```C#
    public class Customer : Entity<string>, IAggregateRoot
    {
        private readonly IList<CustomerProductLocation> _customerProductLocations = new List<CustomerProductLocation>();

        private void UpdatePriorityList(List<CustomerProductLocation> prioritiesToInsert)
        {
            //Add or Update productLocations
            foreach (var productLocation in prioritiesToInsert)
            {
                var existingProductLocation = CustomerProductLocations?.SingleOrDefault(pl => pl.LocationId == productLocation.LocationId);

                // We cannot update an entity, we need to remove and add it again, this to avoid violation of a constraint
                if (existingProductLocation != null)
                {
                    CustomerProductLocation productLocationToAdd;

                    productLocationToAdd = new CustomerProductLocation() { CustomerId = CustomerId, CompanyCode = CompanyCode, LocationId = existingProductLocation.LocationId, Priority = productLocation.Priority };

                    _customerProductLocations.Add(productLocationToAdd);
                    _customerProductLocations.Remove(existingProductLocation);
                }
                else
                {
                    var productLocationToAdd = new CustomerProductLocation() { CustomerId = CustomerId, CompanyCode = CompanyCode, LocationId = productLocation.LocationId, Priority = productLocation.Priority };

                    _customerProductLocations.Add(productLocationToAdd);
                }
            }
        }

```

### Generated SQL

```
[Parameters=[:p1='AV' (Nullable = false) (Size = 2) (DbType = AnsiString), :p2='36', :p3='56', :p0='4', :cur1=NULL (Nullable = false) (Direction = Output) (DbType = Object)], CommandType='Text', CommandTimeout='0']
DECLARE
v_RowCount INTEGER;
BEGIN
UPDATE "KLA_LKNR_PROD" SET "PRIORITY" = :p0
WHERE "KLBEDRIKOD" = :p1 AND "AFLADRES" = :p2 AND "LKNR" = :p3;
v_RowCount := SQL%ROWCOUNT;
OPEN :cur1 FOR SELECT v_RowCount FROM DUAL;
END;
``` 
### Output

```
[15:39:18 ERR] Failed executing DbCommand (106ms) 
[15:39:18 ERR] An error occurred using a transaction.
[15:39:18 ERR] 2021-05-19 15:39:18.970006 ThreadID:5   (ERROR)   OracleExecutionStrategy.ExecuteAsync() :  Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00001: unique constraint (RA.KLA_LKNR_PROD_UN) violated
ORA-06512: at line 4
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.VerifyExecution(OracleConnectionImpl connectionImpl, Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, Int64 internalInitialJSONFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
[15:39:19 ERR] An exception occurred in the database while saving changes for context type '****'.
```

### Include provider and version information

EF Core version: 5.0.5
Database provider: Oracle.EntityFrameworkCore v5.21.1
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019

**Comment by HSchwichtenberg** [comment]
How do you load and save the _customerProductLocations to the database? I can't see that in your code. 
_customerProductLocations is just I list in memory. How do you let EF Core know you removed und added the entity? 
if you just do that on any list not connected to the context, EF Core cannot know.

**Comment by HSchwichtenberg** [comment]
Also, doing this on the context is by design and update operation, as the entity has been updated **compared to the original one in the context**:

```
    var f = ctx.FlightSet.SingleOrDefault(x => x.FlightNo == ID);
    ctx.Remove(f);
    var fNew = f.CopyTo<Flight>(); // creates a 1:1 copy of object
    fNew.FreeSeats--;
    ctx.Add(fNew);
    var c = ctx.SaveChanges();
```

-->
UPDATE [WWWings].[Flight] SET [FreeSeats] = @p0
WHERE [FlightNo] = @p2

**Comment by karimSeghirAllPhi** [comment]
The _customerProductLocations is an owned entity type on the customer, below is the EntityTypeConfig

```
  builder.OwnsMany(c => c.CustomerProductLocations, pl =>
  {
      pl.ToTable("KLA_LKNR_PROD");

      pl.Ignore(e => e.Id);

      pl.HasKey(e => new { CompanyId = e.CompanyCode, e.CustomerId, e.LocationId })
          .HasName("KLA_LKNR_PROD_PK");

      pl.HasIndex(e => new { e.CompanyCode, e.CustomerId, e.Priority })
          .HasDatabaseName("KLA_LKNR_PROD_UN")
          .IsUnique();

      pl.Property(e => e.CompanyCode)
          .HasColumnName("KLBEDRIKOD")
          .HasMaxLength(2)
          .IsUnicode(false)
          .IsRequired();

      pl.Property(e => e.CustomerId)
          .HasColumnName("AFLADRES")
          .HasPrecision(20)
          .IsRequired();

      pl.Property(e => e.LocationId)
          .HasColumnName("LKNR")
          .HasPrecision(20)
          .IsRequired();

      pl.Property(e => e.Priority)
          .HasColumnName("PRIORITY")
          .HasPrecision(4)
          .IsRequired();
  });
```

**Comment by AndriySvyryd** [comment]
@karimSeghirAllPhi As @HSchwichtenberg said EF Core will convert a Remove and Add on the same entity to an update. You'd need to call `SaveChanges` after the `Remove` and then again after `Add` to get the expected behavior.

**Comment by jochenjonc** [comment]
@AndriySvyryd in NHibernate there is a mapping type that is called Bag and there each time an element in the list changes the whole list is deleted and inserted again on the datebase.
Do you know if something like that exists in EF Core?

**Comment by AndriySvyryd** [comment]
@jochenjonc No, there nothing like that currently or in the Backlog. Perhaps the closest would be https://github.com/dotnet/efcore/issues/9067
