### ISSUE TITLE
Replace the link of the "The LINQ expression could not be translated" exception

### ISSUE THREAD

**Issue by sdudnic** [dotnet/efcore#24996]
The **first link** ("https://go.microsoft.com/fwlink/?linkid=2129535") of the "The LINQ expression xxx could not be translated" _Exception Message_ is obsolete (points to nowhere, or generic page), and should be replaced with a more detailed documentation article link.

```
System.InvalidOperationException
  HResult=0x80131509
  Message=The LINQ expression 'DbSet<Place>()
    .Any(e => string.Equals(
        a: e.Nom, 
        b: __nom_0, 
        comparisonType: OrdinalIgnoreCase) && e.AreaId == __areaId_1 && e.Id != __excludeId_2)' could not be translated. 
Additional information: Translation of the 'string.Equals' overload with a 'StringComparison' parameter is not supported. 
See https://go.microsoft.com/fwlink/?linkid=2129535 for more information. 
Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'.
See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Any[TSource](IQueryable`1 source, Expression`1 predicate)
   at MyProject.Web.Services.PlaceService.KeyExist(String nom, Int32 excludeId) in C:\proj\MyProject\src\MyProject.Web\Services\PlaceService.cs:line 240
   at MyProject.Web.Controllers.PlacesController.KeyExist(String key, Int32 id) in C:\proj\MyProject\src\MyProject.Web\Controllers\PlacesController.cs:line 175
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<<InvokeActionMethodAsync>g__Logged|12_1>d.MoveNext()
```
Should it be this one, the correct link?
https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings

* **EF Core Version**: 5.0.5
* **.NET version** : 5.0.202

**Comment by smitpatel** [comment]
@ajcvickers @JeremyLikness - You are owner of the link in the portal, can you update it to point to https://docs.microsoft.com/en-us/ef/core/querying/client-eval

**Comment by ajcvickers** [comment]
Updated the link, but it's not clear to me that it isn't supposed to point to a more specific page.

**Comment by ajcvickers** [comment]
Triage: first link should point to string comparison handling page.
