### ISSUE TITLE
Unable to pass a Func<T, bool> to the Where method of an IEnumerable or IQueryable in the Include method.

### ISSUE THREAD

**Issue by wendellestradairely** [dotnet/efcore#24994]
I need to build a dynamic filters for related/child entities so I have to build it in a variable and pass it to the `Where` method. However, it only works when the lambda is done directly in the `Where` method.

```csharp
Func<tblEMEntityLocation, bool> condition = e => e.Country == "United States"; // Assuming this the predicate that was returned by some function that builds an expression tree

var data = await Context.Set<Vendor>()
  .AsNoTracking()
  .Include(e => e.Locations.Where(condition)) // Passing a func from a variable does not work
  .Include(e => e.Locations.Where(g => g.Country == "United States"))  // This works perfectly fine
  .ToListAsync(cancellationToken);
```

Stacktrace:
```
{System.ArgumentException: Expression of type 'System.Func`2[i21RESTfulApi.Models.tblEMEntityLocation,System.Boolean]' cannot be used for parameter of type 'System.Linq.Expressions.Expression`1[System.Func`2[i21RESTfulApi.Models.tblEMEntityLocation,System.Boolean]]' of method 'System.Linq.IQueryable`1[i21RESTfulApi.Models.tblEMEntityLocation] Where[tblEMEntityLocation](System.Linq.IQueryable`1[i21RESTfulApi.Models.tblEMEntityLocation], System.Linq.Expressions.Expression`1[System.Func`2[i21RESTfulApi.Models.tblEMEntityLocation,System.Boolean]])' (Parameter 'arg1')
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0, Expression arg1)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryableMethodNormalizingExpressionVisitor.TryConvertEnumerableToQueryable(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryableMethodNormalizingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryableMethodNormalizingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryableMethodNormalizingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.NormalizeQueryableMethod(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPreprocessor.NormalizeQueryableMethod(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.IncludableQueryable`2.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at i21RESTfulApi.Repositories.VendorRepository.ListVendorsAsync(SearchParams parameter, CancellationToken cancellationToken) in C:\Projects\i21RESTfulApi\Repositories\VendorRepository.cs:line 90}
```
### Include provider and version information

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 5.0)
Operating system: Windows 10
IDE: (e.g. VS Code)

**Comment by smitpatel** [comment]
You need variable of type `Expression<Func<tblEMEntityLocation, bool>>` a func is not an expression tree. You must have expression tree to be used like that.

**Comment by wendellestradairely** [comment]
@smitpatel I also tried `Expression<Func<tblEMEntityLocation, bool>>` previously but it didn't worked either. It turned out that I need to call the .AsQueryable so it can accept an expression tree.
```csharp
var data = await Context.Set<Vendor>()
  .AsNoTracking()
  .Include(e => e.Locations.AsQueryable().Where(predicate))
  .ToListAsync(cancellationToken);
```

Thanks!
