### ISSUE TITLE
OverflowException: Unsigned integers not handled properly

### ISSUE THREAD

**Issue by InzeNL** [dotnet/efcore#25081]
### Code

Complete runnable source can be found [here](https://github.com/inzenl/ef-testapplication)

I have a table with an `smallint unsigned` column, and the class that represents this table
```csharp
public partial class ATable
{
    public ushort? SomeNumber { get; set; }
}
```
Along with that I have a context set up, both created by the `dotnet ef dbcontext scaffold` command.

With that, I have a simple index page set up
```razor
@page "/"
@using Microsoft.EntityFrameworkCore

@code
{
    protected override Task OnInitializedAsync()
    {
        var context = new ef_testContext();
        return context.ATables.ToListAsync();
    }
}
```

Once I enter a value in the table that is higher than `32767` (Max `int16`, vs `65535` as max `uint16`), the error occurs

### Stack trace
```
System.OverflowException: Value was either too large or too small for an Int16.
   at System.Convert.ThrowInt16OverflowException()
   at System.UInt16.System.IConvertible.ToInt16(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at MySql.Data.MySqlClient.MySqlDataReader.ChangeType(IMySqlValue value, Int32 fieldIndex, Type newType)
   at MySql.Data.MySqlClient.MySqlDataReader.GetInt16(Int32 i)
   at lambda_method62(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToPendingTasks(Task task)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToPendingTasks(Task task)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.CreateInitialRenderAsync(Type componentType, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.RenderComponentAsync(Type componentType, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c__11`1.<<InvokeAsync>b__11_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.ViewFeatures.StaticComponentRenderer.PrerenderComponentAsync(ParameterView parameters, HttpContext httpContext, Type componentType)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.PrerenderedServerComponentAsync(HttpContext context, ServerComponentInvocationSequence invocationId, Type type, ParameterView parametersCollection)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.RenderComponentAsync(ViewContext viewContext, Type componentType, RenderMode renderMode, Object parameters)
   at Microsoft.AspNetCore.Mvc.TagHelpers.ComponentTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at TestApplication.Pages.Pages__Host.<ExecuteAsync>b__14_1() in D:\Rider\TestApplication\TestApplication\Pages\_Host.cshtml:line 20
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at TestApplication.Pages.Pages__Host.ExecuteAsync() in D:\Rider\TestApplication\TestApplication\Pages\_Host.cshtml:line 5
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Verbose output

```
PS D:\Rider\TestApplication\TestApplication> dotnet ef dbcontext list --verbose
Using project 'D:\Rider\TestApplication\TestApplication\TestApplication.csproj'.
Using startup project 'D:\Rider\TestApplication\TestApplication\TestApplication.csproj'.
Writing 'D:\Rider\TestApplication\TestApplication\obj\TestApplication.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\inze\AppData\Local\Temp\tmpA5A9.tmp /verbosity:quiet /nologo D:\Rider\TestApplication\TestApplication\TestApplication.csproj
Writing 'D:\Rider\TestApplication\TestApplication\obj\TestApplication.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\inze\AppData\Local\Temp\tmpA8E7.tmp /verbosity:quiet /nologo D:\Rider\TestApplication\TestApplication\TestApplication.csproj
Build started...
dotnet build D:\Rider\TestApplication\TestApplication\TestApplication.csproj /verbosity:quiet /nologo
D:\Rider\TestApplication\TestApplication\EF\ef_testContext.cs(24,10): warning CS1030: #warning: 'To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.' [D:\Rider\TestApplication\TestApplication\TestApplication.csproj]

Build succeeded.

D:\Rider\TestApplication\TestApplication\EF\ef_testContext.cs(24,10): warning CS1030: #warning: 'To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.' [D:\Rider\TestApplication\TestApplication\TestApplication.csproj]
    1 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.37
Build succeeded.
dotnet exec --depsfile D:\Rider\TestApplication\TestApplication\bin\Debug\net5.0\TestApplication.deps.json --additionalprobingpath C:\Users\inze\.nuget\packages --runtimeconfig D:\Rider\TestApplication\TestApplication\bin\Debug\net5.0\TestApplication.runtimeconfig.json C:\Users\inze\.dotnet\tools\.store\dotnet-ef\5.0.7\dotnet-ef\5.0.7\tools\netcoreapp3.1\any\tools\netcoreapp2.0\any\ef.dll dbcontext list --assembly D:\Rider\TestApplication\TestApplication\bin\Debug\net5.0\TestApplication.dll --startup-assembly D:\Rider\TestApplication\TestApplication\bin\Debug\net5.0\TestApplication.dll --project-dir D:\Rider\TestApplication\TestApplication\ --language C# --working-dir D:\Rider\TestApplication\TestApplication --verbose --root-namespace TestApplication
Using assembly 'TestApplication'.
Using startup assembly 'TestApplication'.
Using application base 'D:\Rider\TestApplication\TestApplication\bin\Debug\net5.0'.
Using working directory 'D:\Rider\TestApplication\TestApplication'.
Using root namespace 'TestApplication'.
Using project directory 'D:\Rider\TestApplication\TestApplication\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'TestApplication'...
Finding Microsoft.Extensions.Hosting service provider...
Using environment 'Development'.
Using application service provider from Microsoft.Extensions.Hosting.
Finding DbContext classes in the project...
Found DbContext 'ef_testContext'.
TestApplication.ef_testContext
```

### Provider and version information

**EF Core version:** `5.0.7`
**Database provider:** MySql.EntityFrameworkCore `5.0.3.1`
**Target framework:** .NET 5.0
**Operating system:** Windows 10 Home 64-bit `Build 19024`
**IDE:** Visual Studio 2019 `16.9.1

**Comment by AndriySvyryd** [comment]
This is likely an issue in the MySql provider. Please contact Oracle.

Alternatively consider using https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql

**Comment by InzeNL** [comment]
Referencing the bug-report on Oracle here, simply for completeness

[https://bugs.mysql.com/bug.php?id=103990](https://bugs.mysql.com/bug.php?id=103990)
