### ISSUE TITLE
EF Core 3.1 Unable to mark alternate key optional

### ISSUE THREAD

**Issue by ourdark** [dotnet/efcore#25107]
## Error

> Error: The property 'UserId' on entity type 'Staff' cannot be marked as nullable/optional because it has been included in a key {'UserId'}.

### Include your code

```
public class Staff
{
    public string Id { get; set; }
    public string Name{ get; set; }
    public string UserId { get; set; } // the UserId is nullable
}

builder.Property(e => e.UserId).HasColumnName("user_id").HasMaxLength(32).IsFixedLength(true).IsRequired(false);

public class Manufacturer
{
    public string Id { get; set; }
    public string CreatedBy { get; set; } // the CreatedBy is required
    public virtual Staff CreatorStaff { get; set; }
}

builder.HasOne(p => p.CreatorStaff).WithMany().HasForeignKey(p => p.CreatedBy).HasPrincipalKey(p => p.UserId);

var result = dbContext.Manufacturers
    .Where(p => p.TenantId == tenantId)
    .Where(criteria.Filters)
    .OrderBy(criteria.OrderBys)
    .Skip(criteria.Pager.Start)
    .Take(criteria.Pager.Count)
    .Select(p => new Manufacturer(p) { Creator = p.CreatorStaff == null ? null : p.CreatorStaff.Name })
    .AsNoTracking()
    .ToList();

```

### Include stack traces

```
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalPropertyBuilder.IsRequired(Nullable`1 required, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder.IsRequired(Boolean required)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder`1.IsRequired(Boolean required)
   at StaffConfiguration.Configure(EntityTypeBuilder`1 builder) in 
   StaffConfiguration.cs:line 25
   at Microsoft.EntityFrameworkCore.ModelBuilder.ApplyConfiguration[TEntity](IEntityTypeConfiguration`1 configuration)
```

### Include verbose output

```

```

### Include provider and version information

EF Core version: 3.1.4
Database provider: PostgreSQL 12.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit
Target framework: netcoreapp3.1
Operating system: Windows 10(19043.1052)
IDE: Visual Studio Enterprise  2019(16.9.6)

**Comment by smitpatel** [comment]
Since `UserId` is target of a relationship, EF Core makes it alternate key. Key properties in EF Core cannot be marked as required. Probably there is a tracking issue to relax this constraint.

**Comment by ourdark** [comment]
duplicates of https://github.com/dotnet/efcore/issues/4415
