### ISSUE TITLE
Cosmos Provider - Date in Primary Key cannot be later deleted

### ISSUE THREAD

**Issue by cmeyertons** [dotnet/efcore#25100]
When a date is included in the primary key, the cosmos backing `id` field does not ISO format the date, inside the document, it does.  Adding and subsequently removing an item with a date in the primary key is not possible by default.

![image](https://user-images.githubusercontent.com/19917677/122041599-bdeec200-cd9e-11eb-8245-0144f7d68e50.png)

Model:

```csharp
public class TestObject
{
    public static readonly TestObject First = new TestObject() { CoinId = "1", Date = new DateTime(2020, 01, 01) };
    public static readonly TestObject Second = new TestObject() { CoinId = "2", Date = new DateTime(2020, 06, 01) };

    public string CoinId { get; set; }
    public DateTime Date { get; set; }
}
```

DbContext:

```csharp
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    base.OnModelCreating(modelBuilder);

    modelBuilder.HasDefaultContainer(CosmosConstants.DefaultContainer);

    var testBuilder = modelBuilder.Entity<TestObject>().HasPartitionKey(x => x.CoinId).HasKey(x => new { x.CoinId, x.Date });
}

public virtual DbSet<TestObject> TestObjects { get; set; }
```

Business Logic:
```csharp
public async Task DeleteAllAsync(string? coinId = null)
{
    _context.TestObjects.AddRange(TestObject.First, TestObject.Second);

    await _context.SaveChangesAsync();

    var toRemove = await _context.TestObjects.ToListAsync();

    _context.RemoveRange(toRemove);

    await _context.SaveChangesAsync();
}
```

![image](https://user-images.githubusercontent.com/19917677/122042420-bed42380-cd9f-11eb-91bf-607be84ee9b3.png)

```log
Microsoft.Azure.Cosmos.CosmosException
  HResult=0x80131500
  Message=Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: aa085616-7bed-4428-8e8e-6da49f619a8f; Reason: (The value 'dbs/Print/colls/PrintData/docs/TestObject%7C1/1/2020%2012:00:00%20AM' specified  for query '$resolveFor' is invalid.
ActivityId: aa085616-7bed-4428-8e8e-6da49f619a8f, Windows/10.0.19042 cosmos-netstandard-sdk/3.11.4);
  Source=Microsoft.Azure.Cosmos.Client
  StackTrace:
   at Microsoft.Azure.Documents.DocumentServiceRequest..ctor(OperationType operationType, ResourceType resourceType, String path, Stream body, AuthorizationTokenType authorizationTokenType, INameValueCollection headers)
   at Microsoft.Azure.Cosmos.RequestMessage.ToDocumentServiceRequest()
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.ProcessMessageAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
   ```
   
If I remove the Date column from the PK, it works fine.

```csharp
var testBuilder = modelBuilder.Entity<TestObject>().HasPartitionKey(x => x.CoinId).HasKey(x => new { x.CoinId });
```

Is there any guidance here?  Do I need to use a value converter as a workaround?

EF Core version: 5.0.7
Database provider: Microsoft.EntityFrameworkCore.Cosmos 5.0.7
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.10

**Comment by AndriySvyryd** [comment]
@cmeyertons The `Date` property formatting is consistent with docs.microsoft.com/en-us/azure/cosmos-db/working-with-dates

I think the issue is in how the `id` value is created by EF

**Comment by cmeyertons** [comment]
@AndriySvyryd  - yes I agree, I highlighted both in my screencap to illustrate how the underlying data is correct but the generated id is incorrect and does not adhere to guidance.

Items created with slashes in the resource id are not very usable (I cannot interact with them in the Cosmos Emulator Data Explorer nor can i delete them) - so I'm not sure how much of a breaking change this is to change the default behavior.

My workaround right now is to implement a custom ValueConverter in the property's model builder to conform the date to ISO-format.
