### ISSUE TITLE
Cosmos: Find / FindAsync missing key throws exception instead of returning null

### ISSUE THREAD

**Issue by cmeyertons** [dotnet/efcore#25115]
## File a bug

invoking `FindAsync` on a missing value is throwing a 404 exception instead of returning null, as the XML documentation on `FindAsync` states.

```csharp
_context.ApiResponses.FindAsync(key)
```

documentation:
```c#
// Summary:
//     Finds an entity with the given primary key values. If an entity with the given
//     primary key values is being tracked by the context, then it is returned immediately
//     without making a request to the database. Otherwise, a query is made to the database
//     for an entity with the given primary key values and this entity, if found, is
//     attached to the context and returned. If no entity is found, then null is returned.
//
// Parameters:
//   keyValues:
//     The values of the primary key for the entity to be found.
//
// Returns:
//     The entity found, or null.
public virtual ValueTask<TEntity> FindAsync([CanBeNullAttribute] params object[] keyValues);
```

exception:

```log
Microsoft.Azure.Cosmos.CosmosException
  HResult=0x80131500
  Message=Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: 7e0e73f0-cb8a-4517-99a8-8ce8be3cd797; Reason: ({
  "Errors": [
    "Resource Not Found. Learn more: https://aka.ms/cosmosdb-tsg-not-found"
  ]
});
  Source=Microsoft.Azure.Cosmos.Client
  StackTrace:
   at Microsoft.Azure.Cosmos.ResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.EntityFrameworkCore.Cosmos.Storage.Internal.CosmosClientWrapper.JObjectFromReadItemResponseMessage(ResponseMessage responseMessage)
   at Microsoft.EntityFrameworkCore.Cosmos.Storage.Internal.CosmosClientWrapper.<ExecuteReadItemAsync>d__40.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosShapedQueryCompilingExpressionVisitor.ReadItemQueryingEnumerable`1.Enumerator.<MoveNextAsync>d__18.MoveNext()
...
```

EF Core version: 5.0.7
Database provider: Microsoft.EntityFrameworkCore.Cosmos
Target framework: (e.g. .NET 5.0)
Operating system: Windows 10
IDE: Visual Studio 2019 16.10

**Comment by roji** [comment]
Poaching
