### ISSUE TITLE
Entity created by table splitting is not executed when inserting data

### ISSUE THREAD

**Issue by hjkl950217** [dotnet/efcore#25132]
## File a bug

Remember:

I follow the official document to configure the table splitting, the query can work normally, but the writing does not work normally, and no error is reported.And no SQL output is observed in the log [Who is out of the queried SQL].

doc: https://docs.microsoft.com/en-us/ef/core/modeling/table-splitting

Where should I start the investigation or is this a bug?

### Include your code

The table does not have any foreign keys, and there are no additional attributes in the entity configuration. I am a single table.

I omitted other fields here

```C#
   // first
    [Table("eform_vms_projectaction")]
    public partial class ProjectAction
 {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(IVMSDbAuditEntity.CLOLUMN_NAME_ID)]
        public string Id { get; set; }

        public EvaluationAction EvaluationAction { get; set; }
         //...
}
   // two
    [Table("eform_vms_projectaction")]
    public partial class EvaluationAction 
 {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(IVMSDbAuditEntity.CLOLUMN_NAME_ID)]
        public string Id { get; set; }

         //...
}


```

for DbContextConfig:
```C#
            EntityTypeBuilder<ProjectAction> tempBuilder = modelBuilder.Entity<ProjectAction>();
            tempBuilder
                .HasOne(o => o.EvaluationAction).WithOne()
                .HasForeignKey<EvaluationAction>(o => o.Id);
```

for logic code:
```C#
                EvaluationAction evaluationAction = new EvaluationAction()
                {
                    Id = Guid.NewGuid().ToString(),
                   //..
                };
                db.EvaluationActions.Add(evaluationAction);
                db.SaveChanges();
```

### Include stack traces

no error! No Insert SQL Show!;

### Include verbose output

none

### Include provider and version information

EF Core version:3.1.14
Database provider: Pomelo.EntityFrameworkCore.MySql
Target framework: .net core 3.1
Operating system:
IDE: e.g. Visual Studio 2019 16.9.6

**Comment by AndriySvyryd** [comment]
The snippets look correct, try upgrading to 5.0

If you are still facing the same issue post a small self-contained project that shows it.

**Comment by hjkl950217** [comment]
The problem persists after upgrading to 5.0, but I found the following:
[PS: I updated code snippets to better express the situation]
1.  add first entity, OK.
2.  add two entity ,NO,no error,no log.

But after the one-to-one navigation properties and model configuration are modified to the second entity：

1.  add first entity, NO,no error,no log.
2.  add two entity ,OK.


According to these, adding data is valid for the entity configuring the navigation properties, but invalid for other entities

**Comment by hjkl950217** [comment]
for two-way navigation properties:
[PS: Based on the second test above ]

code:
```C#
   // first
    [Table("eform_vms_projectaction")]
    public partial class ProjectAction
 {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(IVMSDbAuditEntity.CLOLUMN_NAME_ID)]
        public string Id { get; set; }

        public EvaluationAction EvaluationAction { get; set; }
         //...
}
   // two
    [Table("eform_vms_projectaction")]
    public partial class EvaluationAction 
 {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(IVMSDbAuditEntity.CLOLUMN_NAME_ID)]
        public string Id { get; set; }

         public EvaluationAction ProjectAction { get; set; }
         //...
}


```

for DbContextConfig:
```C#
            EntityTypeBuilder<ProjectAction> tempBuilder = modelBuilder.Entity<ProjectAction>();
            tempBuilder
                .HasOne(o => o.EvaluationAction).WithOne()
                .HasForeignKey<EvaluationAction>(o => o.Id);
            EntityTypeBuilder<EvaluationAction> tempBuilder2 = modelBuilder.Entity<EvaluationAction>();
            tempBuilder2
                .HasOne(o => o.ProjectAction).WithOne()
                .HasForeignKey<ProjectAction>(o => o.Id);
```

Then add 2 kinds of entities in one method and save。


This will cause an exception at runtime:
```C#
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM9L4PQ5874S", Request id "0HM9L4PQ5874S:00000002": An unhandled exception was thrown by the application.
      System.InvalidOperationException: A relationship cycle involving the primary keys of the following enitity types was detected: 'EvaluationAction -> ProjectAction'. This would prevent any entity to be inserted without violating the store constraints. Review the foreign keys defined on the primary keys and either remove or use other properties for at least one of them.
         at EfTest.Controllers.ProjectController.Get(VMSDataContext vMSDataContext) in C:\Users\2A023\Desktop\EfTest\EfTest\Controllers\ProjectController.cs:line 68
         at lambda_method1(Closure , Object , Object[] )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
```


but change DataContext Config to:
```C#
            EntityTypeBuilder<ProjectAction> tempBuilder = modelBuilder.Entity<ProjectAction>();
            tempBuilder
                .HasOne(o => o.EvaluationAction).WithOne()
                .HasForeignKey<ProjectAction>(o => o.Id);  // change there
            EntityTypeBuilder<EvaluationAction> tempBuilder2 = modelBuilder.Entity<EvaluationAction>();
            tempBuilder2
                .HasOne(o => o.ProjectAction).WithOne()
                .HasForeignKey<ProjectAction>(o => o.Id);
```

There will be no errors or exceptions.

To open it in a comprehensive way, only the entity that is configured with 1 to 1 can be added. But in this case, only one entity can be configured 1-to-1.

**Comment by AndriySvyryd** [comment]
You need to specify both navigations in the same call chain:
```C#
            modelBuilder.Entity<ProjectAction>()
                .HasOne(o => o.EvaluationAction).WithOne(o => o.ProjectAction)
                .HasForeignKey<ProjectAction>(o => o.Id);
```

**Comment by hjkl950217** [comment]
Unfortunately, the problem remains.

cod:
```C#
           //config
            EntityTypeBuilder<ProjectAction> tempBuilder = modelBuilder.Entity<ProjectAction>();
            tempBuilder
                .HasOne(o => o.EvaluationAction).WithOne(t => t.ProjectAction)
                .HasForeignKey<EvaluationAction>(o => o.Id);
     
            EntityTypeBuilder<EvaluationAction> tempBuilder2 = modelBuilder.Entity<EvaluationAction>();
            tempBuilder2
                .HasOne(o => o.ProjectAction).WithOne(t => t.EvaluationAction)
                .HasForeignKey<ProjectAction>(o => o.Id);

           //logic code
                VMSDataContext db = vMSDataContext;

                ProjectAction projectAction = new ProjectAction()
                {
                    Id = Guid.NewGuid().ToString(),
                    CreateId = "1",
                    UpdateId = "1",
                    Name = "123123123123"
                };
                db.ProjectActions.Add(projectAction);
                db.SaveChanges();

                EvaluationAction evaluationAction = new EvaluationAction()
                {
                    Id = Guid.NewGuid().ToString(),
                    CompanyId = "111",
                    CreateId = "1",
                    UpdateId = "1",
                    CreateTime = DateTime.Now,
                    ModifiedTime = DateTime.Now,

                    ProjectId = "123",
                    StatusEnum = ProjectActionStatus.WaritExecute,
                    SubStatusEnum = ProjectActionSubStatus.Changing
                };
                db.EvaluationActions.Add(evaluationAction);
                db.SaveChanges();

```
Run at the same time or run only the first or only the second have the same effect: only  EvaluationActions save success，On failure no error no log
