### ISSUE TITLE
Migrating Large EF 6 Context to EF Core 5

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#25144]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Migrating-Large-EF-6-Context-to-EF-Core-/1450581)._

---
Many Services in Visual Studio are Crashing

1. Semantic classification (internal error)
```
System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'Microsoft.ServiceHub.Framework.ServiceBrokerClient'.
   at Microsoft.Verify.NotDisposed(IDisposableObservable disposedValue,String message)
   at async Microsoft.ServiceHub.Framework.ServiceBrokerClient.GetProxyAsync[T](<Unknown Parameters>)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at async Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.RentServiceAsync[TService](<Unknown Parameters>)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at async Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.TryInvokeAsync[TService,TResult](<Unknown Parameters>)
```
2. Global notification delivery
```
System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'Microsoft.ServiceHub.Framework.ServiceBrokerClient'.
   at Microsoft.Verify.NotDisposed(IDisposableObservable disposedValue,String message)
   at async Microsoft.ServiceHub.Framework.ServiceBrokerClient.GetProxyAsync[T](<Unknown Parameters>)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at async Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.RentServiceAsync[TService](<Unknown Parameters>)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at async Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.TryInvokeAsync[TService](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

---
#### Feedback Bot on 6/16/2021, 01:19 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AndriySvyryd** [comment]
This doesn't appear to be related to EF, the failures are in language services. We need a repro project to investigate or transfer this issue to a relevant team.

**Comment by AndriySvyryd** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce

Ideally include a complete code listing that we can run to reproduce the issue.

Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
