### ISSUE TITLE
Error running EnsureCreated(). What am I doing wrong?

### ISSUE THREAD

**Issue by joelmandell** [dotnet/efcore#25154]
Hello!
I tried to use EnsureCreated in my Startup.cs, Configure()-method.
```
using var scope = app.ApplicationServices.CreateScope();
using var context = scope.ServiceProvider.GetService<WPContext>();
context.Database.EnsureDeleted();            
context.Database.EnsureCreated();
```

Throws this exception:
```
System.InvalidOperationException: 'The requested configuration is not stored in the read-optimized model, please use 'DbContext.DesignTimeModel'.'
```
### Stack trace
```
   at Microsoft.EntityFrameworkCore.Metadata.SlimEntityType.Microsoft.EntityFrameworkCore.Metadata.IReadOnlyEntityType.GetSeedData(Boolean providerValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.TrackData(IRelationalModel source, IRelationalModel target, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.<GetDataOperations>d__74.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IRelationalModel source, IRelationalModel target)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.GetCreateTablesCommands(MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.CreateTables()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
   at WorkPartnerLib.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IHubContext`1 baseHub, IDistributedCache cache, IHttpContextAccessor httpContextAccessor) in C:\Users\utvec\Programmering\WorkPartnerLib\WorkPartnerLib\Startup.cs:line 187
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__34.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at WorkPartnerLib.Program.Main(String[] args) in C:\Users\utvec\Programmering\WorkPartnerLib\WorkPartnerLib\Program.cs:line 17
```

### Version

EF Core version: 6.0 preview4 (tried with preview5 also).
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Visual Studio 2022 Preview

**Comment by joelmandell** [comment]
Seems to be something stupid I did. Have to go through my git commits. Sorry for this. Reopening if else.

**Comment by AndriySvyryd** [comment]
If you have a custom `IModelCacheKeyFactory` implementation make sure to implement the new overload.

**Comment by joelmandell** [comment]
@AndriySvyryd   That is what I use actually. Need to check that one out.

**Comment by joelmandell** [comment]
I am not really sure how it should be implemented, using the new overload but I am getting that same exception. I am probably doing it the wrong way....

**Comment by AndriySvyryd** [comment]
Just include the `designTime` value in the cache key. If you can create a small repro project I can give more concrete advice.

**Comment by joelmandell** [comment]
I figured it out now. Thanks @AndriySvyryd

**Comment by ajcvickers** [comment]
Should we add an example to the docs? (If it's not there already.)

**Comment by Saibamen** [comment]
New `IModelCacheKeyFactory` implementation: https://github.com/dotnet/EntityFramework.Docs/blob/3963f34b4a24971c305f274f29d3ae497aec529c/samples/core/Modeling/DynamicModel/DynamicModelCacheKeyFactoryDesignTimeSupport.cs

**Comment by hounddog22030** [comment]
I am experiencing this problem.  I have reviewed the "New IModelCacheKeyFactory implementation", but frankly I don't understand what it is doing or why....

Our exception is:

    Message: 
    System.InvalidOperationException : The requested configuration is not stored in the read-optimized model, please use 'DbContext.GetService&lt;IDesignTimeModel&gt;().Model'.

      Stack Trace: 
    IReadOnlyEntityType.GetSeedData(Boolean providerValues)
    InMemoryStore.EnsureCreated(IUpdateAdapterFactory updateAdapterFactory, IModel designModel, IDiagnosticsLogger`1 updateLogger)
    InMemoryDatabase.EnsureDatabaseCreated()
    InMemoryDatabaseCreator.EnsureCreated()
    DatabaseFacade.EnsureCreated()
    DataContextHelper.GetTestAutoPartsContext(String tenantId) line 44
    MakeInfoHelperTest.SimpleTest() line 20
    <>c.<ThrowAsync>b__128_0(Object state)

We are using the in memory database via 

    optionsBuilder.UseInMemoryDatabase(Guid.NewGuid().ToString())

Our `IModelCacheKeyFactory ` is as follows:

    public class ClaimsPrincipalModelKeyFactory : IModelCacheKeyFactory
    {
        public object Create(DbContext context) => Create(context, false);
        public object Create(DbContext context, bool designTime)
        {
            var claims = ((ContextBase) context).Claims;
            string returnValue = string.Empty;

        var enumerable = claims as Claim[] ?? claims.ToArray();
        if (enumerable.TryGetNameTenantId(out Guid tenantId))
        {
            returnValue += tenantId.ToString();
        }
        if (enumerable.TryGetAmazonSellerId(out string sellerId))
        {
            returnValue += sellerId;
        }
        if (enumerable.TryGetNameIdentifier(out string nameIdentifier))
        {
            returnValue += nameIdentifier;
        }

        if (string.IsNullOrEmpty(returnValue))
        {
            throw new InvalidOperationException($"Unable to determine {nameof(ClaimsPrincipalModelKeyFactory)}");
        }

        return returnValue;
    }
}

Everything is updated to latest (6.0.2)

What should I be looking @?

**Comment by AndriySvyryd** [comment]
@hounddog22030 The important part of the new overload is that the value of `designTime` must be used as part of the cache key (`returnValue`)

**Comment by hounddog22030** [comment]
> @hounddog22030 The important part of the new overload is that the value of `designTime` must be used as part of the cache key (`returnValue`)

Wow!  Thanks.  

I'd like to restate that for anyone else coming across this thread: **_The VERY important part_**

**Comment by lucianbrezaiu** [comment]
> 

Hello. Can you give us an explicit example of how the returned value should look like ? It could be a touple which to contains the designTime, among other values ?

**Comment by AndriySvyryd** [comment]
@lucianbrezaiu The easiest is a tuple `(context.GetType(), designTime)`. But otherwise any type that uses the values of `context.GetType()`  (if you use more than one DbContext type in the application) and `designTime` in `Equals` and `GetHashCode` should work.

As @hounddog22030 showed a string value can also be constructed, but this is less recommended as it causes additional allocations.

**Comment by sjb-sjb** [comment]
There seem to be other method calls that also result in the same exception, see [#3851](https://github.com/dotnet/EntityFramework.Docs/issues/3851)

**Comment by hounddog22030** [comment]
> As @hounddog22030 showed a string value can also be constructed, but this is less recommended as it causes additional allocations.

What specifically do you mean by "additional allocations"?

So ours is a concatenation of Claims?  Is there a more performant method to return a key where the possible values are Guid,string,string?

Should we just return (tenantId,sellerId,nameIdentifier,designTime)?

**Comment by AndriySvyryd** [comment]
@hounddog22030 

> What specifically do you mean by "additional allocations"?

Concatenation allocates a new string.

> So ours is a concatenation of Claims? Is there a more performant method to return a key where the possible values are Guid,string,string?
> Should we just return (tenantId,sellerId,nameIdentifier,designTime)?

Yes
