### ISSUE TITLE
Shadow property on class with children

### ISSUE THREAD

**Issue by maxkoshevoi** [dotnet/efcore#25177]
## Ask a question

I have an abstract base class `P` with two child classes `C1` and `C2`. I use `HasDiscriminator` when configuring base class so that both child classes could be stored in the same database table.

`P` has some property that is the key to that table.

```cs
builder.HasKey(nameof(P.Prop1));
```

Issue is, `C2` has another property that should be included in the key, but `C1` doesn't have it.
My initial solution was to create a shadow property in `P` with the same name, and with some default value, and then add it to the key.

```cs
builder.Property<int>(nameof(C2.Prop2))
                .HasDefaultValue(-1);

builder.HasKey(nameof(P.Prop1), nameof(C2.Prop2));
```

Migration completed without issues, but unit tests with in memory database had failed with `InvalidOperationException` (details bellow) when I tried to query C1 or C2 entities.

Currently I just added `Prop2` to the base class `P`. Not ideal solution, since it doesn't make sense for `C1`.

PS: Exception occurs even if shadow property is not added to the key.

### Include stack traces

```cs
Unhandled exception. System.InvalidOperationException: 'No backing field could be found for property 'P.Prop2' and the property does not have a getter.'
   at Microsoft.EntityFrameworkCore.PropertyBaseExtensions.GetMemberInfo(IPropertyBase propertyBase, Boolean forMaterialization, Boolean forSet)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrPropertyGetterFactory.Create(IPropertyBase property)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyBase.<>c.<get_Getter>b__38_0(PropertyBase p)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyBase.get_Getter()
   at Microsoft.EntityFrameworkCore.PropertyBaseExtensions.GetGetter(IPropertyBase propertyBase)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryExpressionTranslatingExpressionVisitor.ParameterValueExtractor[T](QueryContext context, String baseParameterName, IProperty property)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Any[TSource](IQueryable`1 source, Expression`1 predicate)
```

### Include provider and version information

EF Core version: 5.0.7
Database provider: Microsoft.EntityFrameworkCore.InMemory
Target framework: .NET 5.0
Operating system: Windows
IDE: Visual Studio 2019 16.10.1

**Comment by AndriySvyryd** [comment]
You cannot add a shadow property that has the same name as a non-shadow property on a derived type.

If the two derived classes have different keys consider treating them as separate hierarchies and not mapping the abstract base.

**Comment by maxkoshevoi** [comment]
> You cannot add a shadow property that has the same name as a non-shadow property on a derived type.

Why not? For base class it won't be mapped, and for child class it will be. Seems like a relatively easy thing to handle.

> If the two derived classes have different keys consider treating them as separate hierarchies and not mapping the abstract base.

In my case `C1` has the same keys as `P` and `C2` has same keys as `P` plus another two. 
I often need to retrieve information from all classes inherited from `P` for some business logic.

**Comment by AndriySvyryd** [comment]
> Why not? For base class it won't be mapped, and for child class it will be. Seems like a relatively easy thing to handle.

Currently it's not supported and we don't have plans to add support in the future.

> In my case C1 has the same keys as P and C2 has same keys as P plus another two.

With https://github.com/dotnet/efcore/issues/2611 you would be able to add an alternate key on C2
