### ISSUE TITLE
EF 5.0.7 when passing Func<T,bool> as argument throws error

### ISSUE THREAD

**Issue by peirens-bart** [dotnet/efcore#25184]
This method was working on 2.2.0 when updating to 5.0.7 the filter can't be translated anymore.
```C#
public static async Task<bool> UniqueForAsync<T>(this DbSet<T> set, Func<T, bool> filter, int teamId) where T : Aggregate
        {
            return await set.AnyAsync(x => filter(x) && x.CreatedForTeam == teamId && x.Deleted == false);
        }
```

### stack traces
System.InvalidOperationException: The LINQ expression 'DbSet<Band>()
    .Any(b => Invoke(__filter_0, b)
     && b.CreatedForTeam == __teamId_1 && b.Deleted == (Nullable<bool>)False)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.AnyAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   at BookerTools.Business.DbSetExtensions.UniqueForAsync[T](DbSet`1 set, Func`2 filter, Int32 teamId) in D:\Code\BookerTools\dotnet\backend\BookerTools.Business\Utils\DbSetExtensions.cs:line 14
   at BookerTools.Business.Managers.BandManager.ValidateBand(Band band, Boolean isInsert, Int32 id) in D:\Code\BookerTools\dotnet\backend\BookerTools.Business\Managers\Band\BandManager.cs:line 307
   at BookerTools.Business.Managers.BandManager.UpdateBand(Int32 id, Band band) in D:\Code\BookerTools\dotnet\backend\BookerTools.Business\Managers\Band\BandManager.cs:line 150
   at BookerTools.Web.Logic.BandService.Update(Int32 id, BandEditModel model) in D:\Code\BookerTools\dotnet\backend\BookerTools.Web.Logic\Api Services\Band\BandService.cs:line 96
   at BookerTools.Web.Api.Controllers.BandController.Update(Int32 id, BandEditModel model) in D:\Code\BookerTools\dotnet\backend\BookerTools.Web.Api\Controllers\Bookers\BandController.cs:line 57
   at lambda_method167(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at BookerTools.Web.Middelware.AccountInfoMiddleware.Invoke(HttpContext httpContext) in D:\Code\BookerTools\dotnet\backend\BookerTools.Web.Shared\Middelware\AccountInfoMiddleware.cs:line 45
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
'BookerTools.Web.Api.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\5.0.7\Microsoft.AspNetCore.Http.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0x3d24 has exited with code 0 (0x0).
The thread 0x9de8 has exited with code 0 (0x0).
The thread 0x9904 has exited with code 0 (0x0).
Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: 1 candidate(s) found for the request path '/api/band/462'
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware: Debug: Request matched endpoint '405 HTTP Method Not Supported'
Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: 1 candidate(s) found for the request path '/api/band/462'
Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: Endpoint 'BookerTools.Web.Api.Controllers.BandController.Update (BookerTools.Web.Api)' with route pattern 'api/band/{id}' is valid for the request path '/api/band/462'
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware: Debug: Request matched endpoint 'BookerTools.Web.Api.Controllers.BandController.Update (BookerTools.Web.Api)'
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint 'BookerTools.Web.Api.Controllers.BandController.Update (BookerTools.Web.Api)'
'BookerTools.Web.Api.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\Remote Debugger\x64\Runtime\Microsoft.VisualStudio.Debugger.Runtime.NetCoreApp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.

### provider and version information

EF Core version : 5.0.7
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 5.0
Operating system: Windows
IDE: Visual Studio 2019 16.3

**Comment by ErikEJ** [comment]
Did you disable client evaluation in 2.2?

**Comment by peirens-bart** [comment]
I didn't change anything in de dbcontext setup. Do I need to add anything?

```
services.AddDbContext<BookerToolsContext>(options =>
            {
                options.UseSqlServer(connection, providerOptions =>
                {
                    providerOptions.EnableRetryOnFailure(3);
                    providerOptions.UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery);
                });
            });
```

```
protected override void OnConfiguring(DbContextOptionsBuilder options)
        {
            if (!options.IsConfigured)
            {
                options.UseSqlServer(_devconnectionstring);

            }
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            foreach (var entity in builder.Model.GetEntityTypes())
            {
                entity.SetTableName(entity.DisplayName());
            }
            builder.Ignore<VwTourApi>();

            HelperModelMapper.Map(builder);
            SecurityModelMapper.Map(builder);
            SupportModelMapper.Map(builder);
            LocalizationModelMapper.Map(builder);
            BlobDocumentModelMapper.Map(builder);
            BandModelMapper.Map(builder);
            VenueModelMapper.Map(builder);
            FestivalMapper.Map(builder);
            ContactMapper.Map(builder);
            CompanyMapper.Map(builder);
            PressModelMapper.Map(builder);
            ShowModelMapper.Map(builder);
            ShowDraftModelMapper.Map(builder);
            TourModelMapper.Map(builder);
            HotelModelMapper.Map(builder);
            ParkingModelMapper.Map(builder);
            ContractMapper.Map(builder);
            InvoiceMapper.Map(builder);
            ICalFeedInfoMapper.Map(builder);
            ExpenseMapper.Map(builder);
        }
```

**Comment by sdanyliv** [comment]
If you don't want client side evaluation, change filter to Expression:
```cs
public static async Task<bool> UniqueForAsync<T>(this DbSet<T> set, Expression<Func<T, bool>> filter, int teamId) where T : Aggregate
{
    return await set.Where(filter).AnyAsync(x => x.CreatedForTeam == teamId && x.Deleted == false);
}
```
But if your filter is not translatable to the SQL:
```cs
public static async Task<bool> UniqueForAsync<T>(this DbSet<T> set, Func<T, bool> filter, int teamId) where T : Aggregate
{
    return (await set.Where(x => x.CreatedForTeam == teamId && x.Deleted == false)
        .ToListAsync()).Any(filter);
}
```

**Comment by smitpatel** [comment]
EF Core disabled client evaluation other than top level projection in version 3.0 onwards. See https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/breaking-changes#linq-queries-are-no-longer-evaluated-on-the-client

**Comment by peirens-bart** [comment]
I changed the code to

```
 public static Task<bool> UniqueForAsync<T>(this DbSet<T> set, Func<T, bool> filter, int teamId) where T : Aggregate
        {
            return set.Where(x => filter(x))
                .AnyAsync(x => x.CreatedForTeam == teamId && x.Deleted == false);
        }
```

And I have the same exception, I do want the filter to be included in the query since the potentional lines can be to big otherwise.

```
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: The LINQ expression 'DbSet<Band>()
          .Where(b => Invoke(__filter_0, b)
          )' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
         at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0& )
         at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
         at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
         at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
         at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
         at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.AnyAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
         at BookerTools.Business.DbSetExtensions.UniqueForAsync[T](DbSet`1 set, Func`2 filter, Int32 teamId) in C:\Code\BookerTools\dotnet\backend\BookerTools.Business\Utils\DbSetExtensions.cs:line 13
```

If I change my code to then it is working. I also have other code that is broking when I pass a Func  for a Linq expression used insde another method.  I don't see any difference in terms of logic why the extension method is throwen an exception and teh inline where not

```
await _context.Bands
                        .Where(x => x.Name.ToLower() == band.Name.ToLower() && x.Id != id)
                        .AnyAsync(x => x.CreatedForTeam == _accountInfo.TeamId && x.Deleted == false)
                        //.UniqueForAsync(x => x.Name.ToLower() == band.Name.ToLower() && x.Id != id, _accountInfo.TeamId)
```
