### ISSUE TITLE
EF Code First Migrations failure

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#25191]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/EF-Code-First-Migrations-failure/1461046)._

---
[severity:I'm unable to use this version] [regression] [worked-in:16.10.2]
I'm unable to enable-migrations, add-migration, update-database in vs 2022 v17.0.0 P1. 
My project is asp.net based, running entity framework, code first migration.

All three of these commands return the following error...

```
System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at System.Data.Entity.Migrations.Extensions.ProjectExtensions.GetProjectTypes(Project project, Int32 shellVersion)
   at System.Data.Entity.Migrations.Extensions.ProjectExtensions.IsWebSiteProject(Project project)
   at System.Data.Entity.Migrations.Extensions.ProjectExtensions.GetTargetDir(Project project)
   at System.Data.Entity.Migrations.MigrationsDomainCommand.GetFacade(String configurationTypeName, Boolean useContextWorkingDirectory)
   at System.Data.Entity.Migrations.UpdateDatabaseCommand.<>c__DisplayClass2. <.ctor>b__0()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
Value cannot be null.
Parameter name: type``
```

---
#### Feedback Bot on 6/27/2021, 06:55 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by bricelam** [comment]
This is EF6
