### ISSUE TITLE
InvalidCastException when querying with date parameter

### ISSUE THREAD

**Issue by natehitze** [dotnet/efcore#25226]
### Include your code

Query:
```C#
LocalDate startSearchDate = ...;
LocalDate endSearchDate = ...;
var configurationEvents = await Context.Events
				.AsNoTracking()
				.Where(e => e.IsPublic)
				.Where(e => e.StartDate > startSearchDate && e.EndDate < endSearchDate)
				.ToListAsync();
```

Model:
```C#
public class Event 
{
    public LocalDate? StartDate { get; set; }
    public LocalDate? EndDate { get; set; }
    public bool IsPublic { get; set; }
}
```

We use a value converter to translate NodaTime types to DateTime:
```C#
// Based on code from https://andrewlock.net/strongly-typed-ids-in-ef-core-using-strongly-typed-entity-ids-to-avoid-primitive-obsession-part-4
public class MyValueConverterSelector : ValueConverterSelector
    {
        // The dictionary in the base type is private, so we need our own one here.
        private readonly ConcurrentDictionary<(Type ModelClrType, Type ProviderClrType), ValueConverterInfo> _converters
            = new ConcurrentDictionary<(Type ModelClrType, Type ProviderClrType), ValueConverterInfo>();

        public MyValueConverterSelector([NotNull] ValueConverterSelectorDependencies dependencies) : base(dependencies) { }

        public override IEnumerable<ValueConverterInfo> Select(Type modelClrType, Type providerClrType = null)
        {
            var baseConverters = base.Select(modelClrType, providerClrType);
            foreach (var converter in baseConverters)
            {
                yield return converter;
            }

            // Extract the "real" type T from Nullable<T> if required
            var underlyingModelType = UnwrapNullableType(modelClrType);
            var underlyingProviderType = UnwrapNullableType(providerClrType);

            if (underlyingModelType == typeof(Instant))
            {
                if (underlyingProviderType == null || underlyingProviderType == typeof(DateTime))
                {
                    yield return _converters.GetOrAdd((underlyingModelType, typeof(DateTime)), k => NodaTimeInstantValueConverter.DefaultInfo);
                }
            }

            if (underlyingModelType == typeof(LocalDate))
            {
                if (underlyingProviderType == null || underlyingProviderType == typeof(DateTime))
                {
                    yield return _converters.GetOrAdd((underlyingModelType, typeof(DateTime)), k => NodaTimeLocalDateValueConverter.DefaultInfo);
                }
            }

            if (underlyingModelType == typeof(LocalTime))
            {
                if (underlyingProviderType == null || underlyingProviderType == typeof(DateTime))
                {
                    yield return _converters.GetOrAdd((underlyingModelType, typeof(DateTime)), k => NodaTimeLocalTimeValueConverter.DefaultInfo);
                }
            }

            if (underlyingModelType == typeof(DateTimeZone))
            {
                if (underlyingProviderType == null || underlyingProviderType == typeof(string))
                {
                    yield return _converters.GetOrAdd((underlyingModelType, typeof(string)), k => NodaTimeDateTimeZoneValueConverter.DefaultInfo);
                }
            }
        }

        private static Type UnwrapNullableType(Type type)
        {
            if (type is null) { return null; }

            return Nullable.GetUnderlyingType(type) ?? type;
        }
    }
```

### Include stack traces

```
System.InvalidCastException: Unable to cast object of type 'System.Data.SqlClient.SqlParameter' to type 'Microsoft.Data.SqlClient.SqlParameter'.
Traceback (most recent call last):
  File "System.Runtime.CompilerServices.CastHelpers", line 19, in System.Runtime.CompilerServices.CastHelpers.ChkCast_Helper(System.Void* toTypeHnd, System.Object obj)
  File "Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDateTimeTypeMapping", line 36, in Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDateTimeTypeMapping.ConfigureParameter(System.Data.Common.DbParameter parameter)
  File "Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping", line 143, in Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping.CreateParameter(System.Data.Common.DbCommand command, System.String name, System.Object value, System.Nullable`1[System.Boolean] nullable)
  File "Microsoft.EntityFrameworkCore.Storage.Internal.TypeMappedRelationalParameter", line unknown, in Microsoft.EntityFrameworkCore.Storage.Internal.TypeMappedRelationalParameter.AddDbParameter(System.Data.Common.DbCommand command, System.Object value)
  File "Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBase", line 40, in Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBase.AddDbParameter(System.Data.Common.DbCommand command, System.Collections.Generic.IReadOnlyDictionary`2[System.String,System.Object] parameterValues)
  File "Microsoft.EntityFrameworkCore.Storage.RelationalCommand", line 297, in Microsoft.EntityFrameworkCore.Storage.RelationalCommand.CreateDbCommand(Microsoft.EntityFrameworkCore.Storage.RelationalCommandParameterObject parameterObject, System.Guid commandId, Microsoft.EntityFrameworkCore.Diagnostics.DbCommandMethod commandMethod)
  File "Microsoft.EntityFrameworkCore.Storage.RelationalCommand+<ExecuteReaderAsync>d__19", line 240, in Microsoft.EntityFrameworkCore.Storage.RelationalCommand+<ExecuteReaderAsync>d__19.MoveNext()
  File "System.Runtime.ExceptionServices.ExceptionDispatchInfo", line 17, in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  File "System.Runtime.CompilerServices.TaskAwaiter", line 55, in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task)
  File "System.Runtime.CompilerServices.TaskAwaiter", line 40, in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task)
  File "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter", line unknown, in System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult()
  File "Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1+AsyncEnumerator+<InitializeReaderAsync>d__19", line 310, in Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1+AsyncEnumerator+<InitializeReaderAsync>d__19.MoveNext()
  File "System.Runtime.ExceptionServices.ExceptionDispatchInfo", line 17, in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  File "System.Runtime.CompilerServices.TaskAwaiter", line 55, in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task)
  File "System.Runtime.CompilerServices.TaskAwaiter", line 40, in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task)
  File "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter", line unknown, in System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult()
  File "Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy+<ExecuteAsync>d__7`2", line 147, in Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy+<ExecuteAsync>d__7`2.MoveNext()
  File "System.Runtime.ExceptionServices.ExceptionDispatchInfo", line 17, in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  File "System.Runtime.CompilerServices.TaskAwaiter", line 55, in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task)
  File "System.Runtime.CompilerServices.TaskAwaiter", line 40, in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task)
  File "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter", line unknown, in System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult()
  File "Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1+AsyncEnumerator+<MoveNextAsync>d__18", line 219, in Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1+AsyncEnumerator+<MoveNextAsync>d__18.MoveNext()
  File "System.Runtime.ExceptionServices.ExceptionDispatchInfo", line 17, in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  File "System.Runtime.CompilerServices.TaskAwaiter", line 55, in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task)
  File "System.Runtime.CompilerServices.TaskAwaiter", line 40, in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task)
  File "System.Threading.Tasks.ValueTask`1", line 27, in System.Threading.Tasks.ValueTask`1.get_Result()
  File "Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions+<ToListAsync>d__65`1", line 204, in Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions+<ToListAsync>d__65`1.MoveNext()
  File "System.Runtime.ExceptionServices.ExceptionDispatchInfo", line 17, in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  File "Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions+<ToListAsync>d__65`1", line 345, in Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions+<ToListAsync>d__65`1.MoveNext()
  File "System.Runtime.ExceptionServices.ExceptionDispatchInfo", line 17, in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  File "System.Runtime.CompilerServices.TaskAwaiter", line 55, in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task)
  File "System.Runtime.CompilerServices.TaskAwaiter", line 40, in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task)
  File "System.Runtime.CompilerServices.TaskAwaiter`1", line unknown, in System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

  ... my code truncated
```

### Include provider and version information

EF Core version: 6.0.0-preview.5.21301.9
Database provider: Microsoft.EntityFrameworkCore.SqlServer, 6.0.0-preview.5.21301.9
Target framework: .NET 6 preview 5, self-contained deploy
Operating system: Windows (Azure App Service)

**Comment by natehitze** [comment]
I believe this is the cast that failed: https://github.com/dotnet/efcore/blob/release/6.0-preview5/src/EFCore.SqlServer/Storage/Internal/SqlServerDateTimeTypeMapping.cs#L81

**Comment by ErikEJ** [comment]
You are having a reference to System.Data.SqlClient somewhere?

**Comment by natehitze** [comment]
Yes, the bulk of this project's query code uses System.Data.SqlClient, including the DB context setup:

```csharp
public static DbContext MakeBridge(System.Data.Common.DbConnection connection, System.Data.Common.DbTransaction currentTransaction)
{
    var options = new DbContextOptionsBuilder<DbContext>()
                  .UseSqlServer(connection, sqlOpt => 
                  { 
                      sqlOpt.UseNetTopologySuite();
                      //sqlOpt.EnableRetryOnFailure(); Can't do this because it doesn't support external transactions
                  })
                  .ReplaceService<IValueConverterSelector, MyValueConverterSelector>()
                  .Options;

    var context = new DbContext(options);

    if (currentTransaction != null)
    {
        context.Database.UseTransaction(currentTransaction);
    }

    return context;
}
```

**Comment by ErikEJ** [comment]
I cannot see a reference to System.Data.SqlClient in your code fragment, but EF Core uses Microsoft.Data.SqlClient exclusively!

**Comment by natehitze** [comment]
The connection that gets passed to that method is a System.Data.SqlClient.SqlConnection, sorry I didn't make that clear.

Does that mean EF Core doesn't support using this connection in the way that I'm using it? Other queries are working fine and they are setup the same way, though they don't use date parameters.

Should I convert my code to use Microsoft.Data.SqlClient? Or is this something I can just wait on a fix for?

**Comment by ErikEJ** [comment]
I think you should start using m.d.s. there is no fix to wait for, it is by design.

MDS is the only .net SQL client getting any new features, and is not tied to .net Cord or 
Net Framework releases.

**Comment by roji** [comment]
@natehitze as @ErikEJ wrote above, the EF Core SQL Server provider uses Microsoft.Data.SqlClient since version 3.0. You can use both Microsoft.Data.SqlClient and System.Data.SqlClient in the same application, but you cannot mix usage - so all EF Core usage must use Microsoft.Data.SqlClient.

Incidentally, if you're using NodaTime, you may want to try out [SimplerSoftware.EntityFrameworkCore.SqlServer.NodaTime](https://docs.microsoft.com/en-us/ef/core/extensions/#simplersoftwareentityframeworkcoresqlservernodatime) instead of writing your own value conversions (that plugin also translates some NodaTime query operations, which a pure value converter cannot do).

**Comment by natehitze** [comment]
Thanks @roji and @ErikEJ for your help! Dropping in Microsoft.Data.SqlClient was mostly painless and fixed my issue.
