### ISSUE TITLE
"Invalid column name" when saving, but the columns were removed several migrations ago

### ISSUE THREAD

**Issue by MrYossu** [dotnet/efcore#25243]
I have an ASP.NET Core 3.1 Razor Pages site, using EF Core 3.1.8 against SQL Server.

One of the models is named `Global`, and is used to store user-configurable site settings. There is only one row in this table.

The code that modifies this looks like this...

```c#
    public async Task OnPost(Global global) {
      Global g = await _appDbContext.Globals.SingleAsync();
      // Modify the properties on g
      await _appDbContext.SaveChangesAsync();
      Response.Redirect("/Office");
    }
```

Up until a week or so ago, the `Global` model had these two properties...

```c#
    [Column(TypeName = "decimal(18,2)")]
    public decimal DeliveryCharge { get; set; }
    [Column(TypeName = "decimal(18,2)")]
    public decimal FreeDeliveryOver { get; set; }
```

However, these were removed, and a new model added that included these two properties and some others. The database has been updated with three migrations snice then, and we haven't seen any problems.

Yesterday, I did another update (database migration and code update), and now when the `Global` is updated (see code above), we get an exception...

```
Microsoft.EntityFrameworkCore.Update - An exception occurred in the database while saving changes for context type 'MyWebSite.Models.AppDbContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'DeliveryCharge'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreResults(Boolean& moreResults)
   at Microsoft.Data.SqlClient.SqlDataReader.TryNextResult(Boolean& more)
   at Microsoft.Data.SqlClient.SqlDataReader.<>c__DisplayClass193_0.<NextResultAsync>b__1(Task t)
   at Microsoft.Data.SqlClient.SqlDataReader.InvokeRetryable[T](Func`2 moreFunc, TaskCompletionSource`1 source, IDisposable objectToDispose)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
ClientConnectionId:6b7267ea-2786-43db-85ef-3ccda25b305f
Error Number:207,State:1,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

I have checked and double-checked, and the code does not contain any reference to `DeliveryCharge` anywhere (other than in the migration files where it was added, and subsequently removed), so I have no idea why EF thinks it should be there. If I add the `DeliveryCharge` property back in, then I get the same exception on the (missing) `FreeDeliveryOver` property.

The code works fine when run locally, and also against the test database. However, if I change the connection string of my local code (in Visual Studio) to point at the live database, I get the same exception. This is all using the same code. I've re-applied the migration and restarted the site, but nothing helped.

If I add the two properties back to `Global` and update, then the code runs fine on the live site. However, I don't want to leave them in, as they shouldn't be there. More to the point, I would like to know why this exception is being raised, when the code doesn't have any reference to them.

Thanks for any help you can give.

EF Core version: 3.1.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 3.1
Operating system: Locally Windows 10, latest updates. The server is running latest version of Windows Server (not sure exactly)
IDE: Visual Studio 2019 16.10

**Comment by roji** [comment]
If EF is generating SQL which contains DeliveryCharge on the table for Global, that means that somewhere in your model that property is still being configured on that entity type... [You can turn on logging](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/) to see the exact SQL containing the property, to make sure things are as they seem. At that point, you'll have to search your DbContext's OnModelCreating - as well as any [IEntityTypeConfiguration](https://docs.microsoft.com/en-us/ef/core/modeling/#grouping-configuration) for that entity type - to find where the property is being configured.

If you can't find anything, try to produce a minimal code sample which reproduces the problem - chances are that will help you locate the issue. If not, post that code sample and we'll try to help.

**Comment by MrYossu** [comment]
@roji Thanks for the reply. Please see below...

> If EF is generating SQL which contains DeliveryCharge on the table for Global, that means that somewhere in your model that property is still being configured on that entity type... [You can turn on logging](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/) to see the exact SQL containing the property, to make sure things are as they seem.

I'm trying to get logging working (and failing at the moment), but thought I'd answer the other points in the meantime, see if it helps.

> At that point, you'll have to search your DbContext's OnModelCreating - as well as any [IEntityTypeConfiguration](https://docs.microsoft.com/en-us/ef/core/modeling/#grouping-configuration) for that entity type - to find where the property is being configured.

My `OnModelCreating` method looks like this...

```c#
protected override void OnModelCreating(ModelBuilder modelBuilder) {
  base.OnModelCreating(modelBuilder);
  modelBuilder.Entity<Global>().HasData(new List<Global> {
    new Global { ID = 1, HomePageContent = "", SideBarContent = "", Css = "" }
  });
}
```

That's the whole thing, no mention of either of those two properties. I don't have any mention of `IEntityTypeConfiguration` anywhere in my code base.

I used my text editor to search for `DeliveryCharge` in the entire project folder, and other than the references in the migration files, and the actual property that I added back into `Global` to get the site working again, it just isn't mentioned anywhere. Moreover, the exact same code, running in VS behaves differently when pointed at my local database  or the test database (where it works) and the live database (where it throws the exception).

So, it looks like it's some issue with the database, but I can't see what or why.

> If you can't find anything, try to produce a minimal code sample which reproduces the problem - chances are that will help you locate the issue. If not, post that code sample and we'll try to help.

The problem is that it doesn't seem to be the code. I know that doesn't help, but it's the way it is. As I said, the same code works fine against my local database and the test database, but not the live one. All have the exact same migrations applied, and the test and live ones are running in the same instance of SQL Server.

Does any of that help? Thanks again.

**Comment by roji** [comment]
> So, it looks like it's some issue with the database, but I can't see what or why.

From what I'm understanding above, when calling SaveChangesAsync, EF is generating SQL which contains the column "DeliveryCharge"; if so, then that cannot be an issue with the database; EF doesn't look at the database to know which columns to generate in its SQL, only at the model.

It sounds like maybe in some databases (the local/test), the columns are still there, e.g. because the migrations haven't been applied (or have been rolled back, or similar), and this is why the code works well against them. Once again, logging could help make sure exactly which SQL is being sent to each database, and whether it contains DeliveryCharge or not. I would also inspect the actual database schema for the databases (e.g. with SSMS) to see whether the columns are there or not.

**Comment by MrYossu** [comment]
@roji Duh, the reason I was getting the exception on that one database was because I had a trigger on it which added a row to a corresponding audit table. I had updated `Global`, but forgotten to update the audit trigger, which was still trying to find the two removed columns.

Thanks anyway.
