### ISSUE TITLE
SnapshotFactoryFactory assumes wrong type for snapshot expression body

### ISSUE THREAD

**Issue by 0x0309** [dotnet/efcore#25259]
Using the following value comparer results in an exception being thrown.
```c#
new ValueComparer<IEnumerable<int>>(
    (a, b) => a.SequenceEqual(b),
    a => a.Aggregate(0, (h, i) => HashCode.Combine(h, i.GetHashCode())),
    a => a.ToArray() // <--
  );
```
```
System.ArgumentException: Argument types do not match
  at System.Linq.Expressions.Expression.Condition(Expression test, Expression ifTrue, Expression ifFalse)
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.SnapshotFactoryFactory.CreateSnapshotValueExpression(Expression expression, IPropertyBase propertyBase)
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.SnapshotFactoryFactory.CreateSnapshotExpression(Type entityType, ParameterExpression parameter, Type[] types, IList`1 propertyBases)
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.SnapshotFactoryFactory.CreateConstructorExpression(IEntityType entityType, ParameterExpression parameter)
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.SnapshotFactoryFactory`1.Create(IEntityType entityType)
  at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.<>c.<get_OriginalValuesFactory>b__184_0(EntityType entityType)
  at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
  at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.get_OriginalValuesFactory()
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.OriginalValues..ctor(InternalEntityEntry entry)
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.EnsureOriginalValues()
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntrySubscriber.SnapshotAndSubscribe(InternalEntityEntry entry)
  at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTrackingFromQuery(IEntityType baseEntityType, Object entity, ValueBuffer& valueBuffer)
  at Microsoft.EntityFrameworkCore.Query.QueryContext.StartTracking(IEntityType entityType, Object entity, ValueBuffer valueBuffer)
  at lambda_method45(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
  at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```

The bug is [here](https://github.com/dotnet/efcore/blob/4b25a8871355ae44846b173a02915b01ec469bc9/src/EFCore/ChangeTracking/Internal/SnapshotFactoryFactory.cs#L195)

The bug is that `snapshotExpression.Type` is actually `int[]` rather than the assumed `IEnumerable<int>`. This is because `LambdaExpression` can have an *implicit* conversion from the type of the body expression to the delegate return type.

The logical fix would be wrapping the body expression in an explicit cast if the types don't match, like this: 1ead7ef36a9f39a572b99d2f42ec74c619b84247

Issue #11077 seems to have been caused by this same kind of bug, but the real bug was not identified there and fixed, and instead a work-around was suggested.

It is not at all clear that the return value must be explicitly cast to the exact same type as the type parameter of the `ValueComparer`, as this is not normally required in C# code. This should be fixed so it "just works" rather than telling people they need to cast explicitly, and hoping they manage to find that advice somewhere.

An alternative fix if this affects multiple code locations would be to fix the snapshot expression in the `ValueComparer` constructor so that it is automatically correct for all usages.

**Comment by 0x0309** [comment]
Can submit a PR, but will need some guidance on how and where to create a unit test for this situation.
