### ISSUE TITLE
System.InvalidOperationException: The property 'Intcol1' cannot be added to the type 'T1' because there was no property type specified and there is no corresponding CLR property or field. To add a shadow state property the property type must be specified.

### ISSUE THREAD

**Issue by deokershesh** [dotnet/efcore#25275]
In my database I have following single table with single column primary key (PK) column.

create table t1 (intcol int, charcol char(20), primary key(intcol));

Running following scaffold command results in error which says "Intcol1", note : here column name is "intcol", how/why its getting suffixed with "1"? This is causing above error (in the title). OneDB.EntityFramework.Core is provider name.

dotnet ef dbcontext scaffold "Database=mydb; server=myserver; UID=user; PWD=password" OneDB.EntityFramework.Core -o Models --project MyApp.csproj -v

c:\>dotnet ef core --version
Entity Framework Core .NET Command-line Tools
3.1.5

c:\>dotnet --version
3.1.401

Below is stack trace:
==============
System.InvalidOperationException: The property 'Intcol1' cannot be added to the type 'T1' because there was no property type specified and there is no corresponding CLR property or field. To add a shadow state property the property type must be specified.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(Type propertyType, String propertyName, MemberInfo memberInfo, Nullable`1 typeConfigurationSource, Nullable`1 configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(Type propertyType, String propertyName, Nullable`1 typeConfigurationSource, Nullable`1 configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.GetOrCreateProperties(IReadOnlyList`1 propertyNames, Nullable`1 configurationSource, IReadOnlyList`1 referencedProperties, Boolean required, Boolean useDefaultType)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.PrimaryKey(IReadOnlyList`1 propertyNames, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder.HasKey(String[] propertyNames)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitPrimaryKey(EntityTypeBuilder builder, DatabaseTable table)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitTable(ModelBuilder modelBuilder, DatabaseTable table)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitTables(ModelBuilder modelBuilder, ICollection`1 tables)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluarlize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The property 'Intcol1' cannot be added to the type 'T1' because there was no property type specified and there is no corresponding CLR property or field. To add a shadow state property the property type must be specified.

**Comment by ajcvickers** [comment]
@deokershesh This is likely a problem with the  OneDB.EntityFramework.Core provider. You should contact the provider author for help.

Alternately, if this happens with other providers as well, then please post the full database schema that results in this error so that we can investigate.

**Comment by deokershesh** [comment]
Hi Arthur,

It would be great help, if you could provide any hint on possible issue to
be looked into OneDB.EntityFramework.Core provider. I am part of team for
provider development of OneDB.EntityFramework.Core.

What is puzzling is where "1" is getting suffixed with column name.

**Comment by ajcvickers** [comment]
@deokershesh This happens when a property name is "uniquified" because it conflicts with an existing property that has incompatible configuration. This often happens when the name of a shadow property generated for a foreign key conflicts with an existing property that is not the FK. In this case, the generated property has a number added so that it does not clash with the existing property.
