### ISSUE TITLE
Add-Migration crashes with NullReferenceException when changing the schema for Microsoft.Identity tables

### ISSUE THREAD

**Issue by fededim** [dotnet/efcore#25293]
Hi,

I am using Microsoft.AspNetCore.Identity.EntityFrameworkCore 5.0.8. If I try to customize in the DbContext the schema name for the AspNet* tables e.g.

```
            mb.Entity<User>().ToTable("AspNetUsers", "User");
            mb.Entity<Role>().ToTable("AspNetRoles", "User");
            mb.Entity<UserClaim>().ToTable("AspNetUserClaims", "User");
            mb.Entity<UserRole>().ToTable("AspNetUserRoles", "User");
            mb.Entity<UserLogin>().ToTable("AspNetUserLogins", "User");
            mb.Entity<RoleClaim>().ToTable("AspNetRoleClaims", "User");
            mb.Entity<UserToken>().ToTable("AspNetUserTokens", "User");
```

the Add-Migration fails with this exception

```
Add-Migration MSIdentity -Verbose
Using project 'SincroADR_DB'.
Using startup project 'SincroADR_DB'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile C:\Users\dimarco\source\repos\SincroADR\SincroADR_DB\bin\Debug\net5.0\SincroADR_DB.deps.json --additionalprobingpath C:\Users\dimarco\.nuget\packages --additionalprobingpath "C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages" --additionalprobingpath "C:\Program Files (x86)\Microsoft\Xamarin\NuGet" --runtimeconfig C:\Users\dimarco\source\repos\SincroADR\SincroADR_DB\bin\Debug\net5.0\SincroADR_DB.runtimeconfig.json C:\Users\dimarco\.nuget\packages\microsoft.entityframeworkcore.tools\5.0.8\tools\netcoreapp2.0\any\ef.dll migrations add MSIdentity --json --verbose --no-color --prefix-output --assembly C:\Users\dimarco\source\repos\SincroADR\SincroADR_DB\bin\Debug\net5.0\SincroADR_DB.dll --startup-assembly C:\Users\dimarco\source\repos\SincroADR\SincroADR_DB\bin\Debug\net5.0\SincroADR_DB.dll --project-dir C:\Users\dimarco\source\repos\SincroADR\SincroADR_DB\ --language C# --working-dir C:\Users\dimarco\source\repos\SincroADR --root-namespace SincroADR_DB
Using assembly 'SincroADR_DB'.
Using startup assembly 'SincroADR_DB'.
Using application base 'C:\Users\dimarco\source\repos\SincroADR\SincroADR_DB\bin\Debug\net5.0'.
Using working directory 'C:\Users\dimarco\source\repos\SincroADR\SincroADR_DB'.
Using root namespace 'SincroADR_DB'.
Using project directory 'C:\Users\dimarco\source\repos\SincroADR\SincroADR_DB\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'SincroADR_DB'...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'SincroADRContext'.
Using context 'SincroADRContext'.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding design-time services referenced by assembly 'SincroADR_DB'...
Finding design-time services referenced by assembly 'SincroADR_DB'...
Using design-time services from assembly 'Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite'.
Finding IDesignTimeServices implementations in assembly 'SincroADR_DB'...
No design-time services were found.
'SincroADRContext' disposed.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Initialize(ColumnOperation columnOperation, IColumn column, RelationalTypeMapping typeMapping, Boolean isNullable, IEnumerable`1 migrationsAnnotations, Boolean inline)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Add(IColumn target, DiffContext diffContext, Boolean inline)+MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Add(ITable target, DiffContext diffContext)+MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.DiffCollection[T](IEnumerable`1 sources, IEnumerable`1 targets, DiffContext diffContext, Func`4 diff, Func`3 add, Func`3 remove, Func`4[] predicates)+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IRelationalModel source, IRelationalModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.
```

If I comment the lines above in the DbContext, the migration is instead created successfully.

**Comment by fededim** [comment]
I performed some testing and I discovered that a strange behaviour: if I comment the User virtual navigation property inside UserClaim, UserLogin and UserToken, e.g.

```
    public class UserClaim:IdentityUserClaim<Int64>
    {
        //public virtual User User { get; set; }
    }

    public class UserLogin: IdentityUserLogin<Int64>
    {
        //public virtual User User { get; set; }
    }

    public class UserToken: IdentityUserToken<Int64>
    {
        //public virtual User User { get; set; }
    }

    public class User : IdentityUser<Int64>
    {
        public virtual ICollection<UserClaim> Claims { get; set; }
        public virtual ICollection<UserLogin> Logins { get; set; }
        public virtual ICollection<UserToken> Tokens { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }

    public class Role:IdentityRole<Int64>
    {
        public virtual ICollection<UserRole> UserRoles { get; set; }
        public virtual ICollection<RoleClaim> RoleClaims { get; set; }
    }

    public class UserRole: IdentityUserRole<Int64>
    {
        public virtual User User { get; set; }
        public virtual Role Role { get; set; }
    }

    public class RoleClaim:IdentityRoleClaim<Int64>
    {
        public virtual Role Role { get; set; }
    }
```

the migration is created successfully. As soon as I uncomment one of the User property from any of the 3 above classes the Add-Migration crashes. I do not know if this helps.

**Comment by fededim** [comment]
Please forgive I managed to make it work. The error was raising because I was deriving DbContext  only from 
```
public class SincroADRContext : IdentityDbContext<User, Role, Int64>
```

instead I need to use 
```
public class SincroADRContext : IdentityDbContext<User, Role, Int64, UserClaim, UserRole, UserLogin, RoleClaim, UserToken>
```

I close the ticket.
