### ISSUE TITLE
Failure to migrate sqlite database after added HasSrid annotation to my model

### ISSUE THREAD

**Issue by d79ima** [dotnet/efcore#25325]
I have a simple table with 2 geometry columns.
My initial migration does not have the SRID annotation on these spatial columns.
My second migration does, which causes the exception below.
Attached the small example app to reproduce the issue.

The second migration was generated after adding the following code to my DbContext
```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
  {
      modelBuilder.Entity<Table>()
          .Property(p => p.WGS84Position)
          .HasColumnType("GEOMETRY")
          .HasSrid(4326);

      modelBuilder.Entity<Table>()
          .Property(p => p.WGS84Position2)
          .HasColumnType("GEOMETRY")
          .HasSrid(4326);

      base.OnModelCreating(modelBuilder);
  }
```

```
Microsoft.Data.Sqlite.SqliteException
  HResult=0x80004005
  Message=SQLite Error 1: 'near "Table": syntax error'.
  Source=Microsoft.Data.Sqlite
  StackTrace:
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.<PrepareAndEnumerateStatements>d__64.MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.<GetStatements>d__54.MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at TestNetTopologySuite.Program.Main(String[] args) in C:\Users\dgrinbla\Downloads\TestNetTopologySuite\ProgramSimple.cs:line 22

  This exception was originally thrown at this call stack:
    [External Code]
    TestNetTopologySuite.Program.Main(string[]) in ProgramSimple.cs
```

Microsoft.EntityFrameworkCore.Sqlite.NetTopologySuite: 5.0.1
EF Core version: 5.0.1
Database provider: SQLite
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.10

**Comment by ajcvickers** [comment]
Note for triage/@bricelam: I am able to reproduce this on 5.0.8.

**Comment by bricelam** [comment]
Possibly related to #25116 (but maybe not). I suspect this'll require a very fancy table rebuild...
