### ISSUE TITLE
Error message content prevents expansion of logger template

### ISSUE THREAD

**Issue by jprimke** [dotnet/efcore#25333]
Hello 

I got an error like this "The instance of entity type 'Type' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.".

I would expand this via logger template (SeriLog) 

```
logger.LogError(exception, $"{exception.Message} {{@paket}} {{ownerId}}", paket, ownerId)
```

and received an exception 

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Extensions.Logging.LogValuesFormatter.GetValue(Object[] values, Int32 index)
   at Microsoft.Extensions.Logging.FormattedLogValues.get_Item(Int32 index)
   at Microsoft.Extensions.Logging.FormattedLogValues.GetEnumerator()+MoveNext()
   at Serilog.Extensions.Logging.SerilogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogError(ILogger logger, Exception exception, String message, Object[] args)
```

It occures beause you use {} to separate the field name from text around but this result is a exception if we are using a logging framework with templates. 

Could you check that please.

.net core version is .NET 5.0.8

Regards

Joerg

**Comment by roji** [comment]
@jprimke AFAIK, in Serilog, you typically avoid using C# string interpolation (`$"..."`), and instead allow Serilog to perform its own interpolation. In other words, try doing the following:

```c#
logger.LogError(exception, "{message} {@paket} {ownerId}", exception.Message, paket, ownerId)
```

This should provide the exception message to Serilog as a separate parameter (rather than interpolate it into the format string), at which point it should treat it as pure text and ignore any curly braces within.
