### ISSUE TITLE
Table Splitting throws an exception in multi-table environment update

### ISSUE THREAD

**Issue by Loongle** [dotnet/efcore#25388]
I think EF Core allows to map two or more entities to a single row. This is called table splitting or table sharing. 
but now i created three entity on demo, it throw exception. 
`The property 'Metric.Status' cannot be assigned a value generated by the database. Store-generated values can only be assigned to properties configured to use store-generated values.`

I use tutorial by https://docs.microsoft.com/en-us/ef/core/modeling/table-splitting

 
detail see demo code
[demo.zip](https://github.com/dotnet/efcore/files/6917463/demo.zip)

**Comment by ajcvickers** [comment]
Notes for triage:

Model building code:

```C#
modelBuilder.Entity<DetailedOrder>(
    dob =>
    {
        dob.ToTable("Orders");
        dob.Property(o => o.Status).HasColumnName("Status");
        dob.Property(o => o.TenantId).HasColumnName("TenantId");
    });

modelBuilder.Entity<Order>(
    ob =>
    {
        ob.ToTable("Orders");
        ob.Property(o => o.Status).HasColumnName("Status");
        ob.Property(o => o.TenantId).HasColumnName("TenantId");
        ob.HasOne(o => o.DetailedOrder).WithOne()
            .HasForeignKey<DetailedOrder>(o => o.Id);
        ob.HasOne(o => o.Metrc).WithOne().HasForeignKey<Metric>(o => o.Id);
    });

modelBuilder.Entity<Metric>(
    ob =>
    {
        ob.ToTable("Orders");
        ob.Property(o => o.Status).HasColumnName("Status");
        //ob.Property(o => o.TenantId).HasColumnName("TenantId");  
    });
```

Generates model:
(Notice that `Metric.Status` is not marked as `ValueGenerated.OnUpdateSometimes`.)

```
Model: 
  EntityType: DetailedOrder
    Properties: 
      Id (int) Required PK FK AfterSave:Throw
      BillingAddress (string)
      ShippingAddress (string)
      Status (Nullable<OrderStatus>) ValueGenerated.OnUpdateSometimes
      TenantId (Nullable<Guid>) ValueGenerated.OnUpdateSometimes
      Version (byte[]) Concurrency BeforeSave:Ignore AfterSave:Ignore ValueGenerated.OnAddOrUpdate
    Keys: 
      Id PK
    Foreign keys: 
      DetailedOrder {'Id'} -> Order {'Id'} Unique ToDependent: DetailedOrder Cascade
  EntityType: Metric
    Properties: 
      Id (int) Required PK FK AfterSave:Throw
      Code (string)
      Key (string)
      Status (Nullable<OrderStatus>)
      Version (no field, byte[]) Shadow Concurrency BeforeSave:Ignore AfterSave:Ignore ValueGenerated.OnAddOrUpdate
    Keys: 
      Id PK
    Foreign keys: 
      Metric {'Id'} -> Order {'Id'} Unique ToDependent: Metrc Cascade
  EntityType: Order
    Properties: 
      Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd
      Status (Nullable<OrderStatus>) ValueGenerated.OnUpdateSometimes
      TenantId (Nullable<Guid>) ValueGenerated.OnUpdateSometimes
      Version (no field, byte[]) Shadow Concurrency BeforeSave:Ignore AfterSave:Ignore ValueGenerated.OnAddOrUpdate
    Navigations: 
      DetailedOrder (DetailedOrder) ToDependent DetailedOrder
      Metrc (Metric) ToDependent Metric
    Keys: 
      Id PK
```

Update marks only the Order entity as modified:
(Note that if all three entities are marked as modified, then SaveChanges succeeds.)

```
DetailedOrder {Id: 1} Unchanged
  Id: 1 PK FK
  BillingAddress: '11 Wall Street, New York'
  ShippingAddress: '221 B Baker St, London'
  Status: 'Pending'
  TenantId: '8172fa1b-e6ad-409c-9531-c98dbafde3f8'
  Version: <null>
Metric {Id: 1} Unchanged
  Id: 1 PK FK
  Code: '1'
  Key: '1'
  Status: 'Pending'
  Version: <null>
Order {Id: 1} Modified
  Id: 1 PK
  Status: 'Pending' Modified
  TenantId: '8172fa1b-e6ad-409c-9531-c98dbafde3f8' Modified
  Version: <null>
  DetailedOrder: {Id: 1}
  Metrc: {Id: 1}
```

Exception:

```
Unhandled exception. System.InvalidOperationException: The property 'Metric.Status' cannot be assigned a value generated by the database. Store-generated values can only be assigned to properties configured to use store-generated values.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetStoreGeneratedValue(IProperty property, Object value)
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.ColumnValuePropagator.TryPropagate(IProperty property, IUpdateEntry entry)
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.GenerateColumnModifications()
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.<>c.<get_ColumnModifications>b__20_0(ModificationCommand command)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.get_ColumnModifications()
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.BatchCommands(IList`1 entries, IUpdateAdapter updateAdapter)+MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at test_demo.Program.Test2() in C:\local\repros\demo\Program.cs:line 56
   at test_demo.Program.Main(String[] args) in C:\local\repros\demo\Program.cs:line 11
```
