### ISSUE TITLE
Two instances get created with QueryTrackingBehavior = NoTracking

### ISSUE THREAD

**Issue by ThomasMader** [dotnet/efcore#25400]
I realized that two instances of the SettingsStorage class get created for a simple query like below if there is only one entity in the DB and the QueryTrackingBehavior is set to NoTracking.

```
			return Context.Set<SettingsStorage>()
				.Where(t => t.DomainIdentifier == identifier.Key)
				.FirstOrDefault();
```

With NoTrackingWithIdentityResolution on the other hand only one instance is being created which would be the outcome I would assume also with the NoTracking setting.
To me it looks like a bug but as I don't know the internals I thought it's best to first ask what is the reason for that behavior.
Thanks in advance.

EF Core version: 5.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10

**Comment by ajcvickers** [comment]
@ThomasMader While creation of multiple instances is a consequence of using no-tracking queries without identity resolution, we don't think this should be happening for the specific case you show above. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ThomasMader** [comment]
With the following code I can reproduce the problem:

```
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Intro
{
    internal class Program
    {
        private const string TableName = "Test";
        private const string ValueColumnName = "Value";

        private static void Main()
        {
            var optionsBuilder = new DbContextOptionsBuilder<TestDbContext>();
            var connectionString = @"Server = (localdb)\mssqllocaldb; Database = " + $"{TableName}" + @"; Integrated Security=true;";
            optionsBuilder.UseSqlServer(connectionString, b => b.UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery));

            using (var db = new TestDbContext(optionsBuilder.Options))
            {
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();
            }
            using (var db = new TestDbContext(optionsBuilder.Options))
            {
                Test test = new(15);
                db.Add(test);
                db.SaveChanges();

            }
            using (var db = new TestDbContext(optionsBuilder.Options))
            {
                var test = db.Set<Test>()
                .FirstOrDefault();
            }
        }

        private class TestConfig : IEntityTypeConfiguration<Test>
        {
            public void Configure(EntityTypeBuilder<Test> builder)
            {
                builder.ToTable(TableName);

                builder.Property(p => p.Id)
                    .HasColumnName("Id")
                    .ValueGeneratedOnAdd();

                builder.Property(p => p.Value)
                       .HasColumnName(ValueColumnName)
                       .ValueGeneratedNever().HasColumnType("int");

                builder.HasKey(p => p.Id);
            }
        }

        private sealed record Test
        {
            private static int constructorCallCount = 0;

            internal Test()
            {
                Console.WriteLine($"Constructor got called {++constructorCallCount} times.");
            }

            internal Test(int value)
            {
                Value = value;
            }

            internal int Value { get; init; }
            internal int Id { get; init; }

        }

        private class TestDbContext : DbContext
        {
            internal TestDbContext(DbContextOptions<TestDbContext> options)
                : base(options)
            {
                // With 'NoTracking' we get a 'constructorCallCount' of 2 whereas with 'NoTrackingWithIdentityResolution'
                // we get 1 because the constructor is only called once.
                //ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTrackingWithIdentityResolution;
                ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;
            }

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                modelBuilder.UsePropertyAccessMode(PropertyAccessMode.Property);
                modelBuilder.ApplyConfiguration(new TestConfig());
            }

        }
    }
}

```

**Comment by ajcvickers** [comment]
@ThomasMader Thanks; that isn't expected. We will investigate.

For triage: two stack traces:

```
Call 1
   at System.Environment.get_StackTrace()
   at Intro.Program.Test..ctor() in C:\local\AllTogetherNow\FiveOh\Program.cs:line 187
   at lambda_method29(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at Intro.Program.Main() in C:\local\AllTogetherNow\FiveOh\Program.cs:line 157
Call 2
   at System.Environment.get_StackTrace()
   at Intro.Program.Test..ctor() in C:\local\AllTogetherNow\FiveOh\Program.cs:line 187
   at lambda_method29(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at Intro.Program.Main() in C:\local\AllTogetherNow\FiveOh\Program.cs:line 157
```

**Comment by smitpatel** [comment]
This happens only when split query + no tracking is used and the query doesn't have any related collections to load.
Work-around: Use `AsSingleQuery` operator on the particular query and it will work correctly.
