### ISSUE TITLE
One-to-many add/remove fails foreign key constraint

### ISSUE THREAD

**Issue by timmi-on-rails** [dotnet/efcore#25436]
The following program raises a foreign key constraint failed exception on `SaveChanges()`.
I would expect it to work and `SaveChanges()` should execute no queries.
I checked with Sqlite and MariaDb.

### Example

```C#
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

Blog blog = new Blog
{
    Posts = new List<Post>
    {
        new Post()
    }
};

using var dbContext = new AppDbContext();
dbContext.Database.EnsureDeleted();
dbContext.Database.EnsureCreated();

dbContext.Blogs.Add(blog);
blog.Posts.Clear(); // <- without this line, everything works as expected
dbContext.Blogs.Remove(blog);

dbContext.SaveChanges(); // <- exception happens here

class AppDbContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    public DbSet<Post> Posts { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlite("data source=test.db");
}

class Blog
{
    public int Id { get; set; }

    public IList<Post> Posts { get; set; }
}

class Post
{
    public int Id { get; set; }

    public int BlogId { get; set; }

    public Blog Blog { get; set; }
}
```

### Logs

```
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (4ms) [Parameters=[@p0='-2147482647' (DbType = String)], CommandType='Text', CommandTimeout='30']
      INSERT INTO "Posts" ("BlogId")
      VALUES (@p0);
      SELECT "Id"
      FROM "Posts"
      WHERE changes() = 1 AND "rowid" = last_insert_rowid();
fail: Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type 'AppDbContext'.
      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
       ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
         at System.Data.Common.DbCommand.ExecuteReader()
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
         --- End of inner exception stack trace ---
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
         at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
         at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
```

### Environment

EF Core version: 5.0.8
Database provider: Microsoft.EntityFrameworkCore.Sqlite and Pomelo.EntityFrameworkCore.MySql
Target framework: .NET 5.0
Operating system: Win 10
IDE: Visual Studio 2019

**Comment by ajcvickers** [comment]
@timmi-on-rails This currently requires a call to `DetectChanges` after clearing the collection:

```C#
dbContext.Blogs.Add(blog);
blog.Posts.Clear(); // <- without this line, everything works as expected
dbContext.ChangeTracker.DetectChanges();
dbContext.Blogs.Remove(blog);

dbContext.SaveChanges(); // <- exception happens here
```

See [Change Detection and Notifications](https://docs.microsoft.com/en-us/ef/core/change-tracking/change-detection) for information on DetectChanges.

Note for triage: We should look into making a local DetectChanges from Remove handle this.

**Comment by timmi-on-rails** [comment]
@ajcvickers Thank you for your fast response.
First of all it is good, that there is a workaround.

However, including this workaround in my project basically means, that I would have to preemptively call `DetectChanges()` everywhere before removing an entity from the database context.

To me this behaviour seems unintuitive that I have to remember calling some method in this special situation.
I understand, that using EF Core correctly requires knowledge about the entity tracking idea and that there is a change detection mechanism, but this seems like an implementation detail to me.

For example, if I call `SaveChanges()` right after `dbContext.Blogs.Add(blog);`, then the `DetectChanges()` is not necessary anymore. I don't understand why?
Is it a performance decision or can the implementation be improved? Because basically EF Core knows everything to fix this situation.

I guess if there are more special cases like this, then I have to design my future projects with EF Core differently.
Currently I am using/modifying database entities in many places of the software. 
To have better control I would need to map the database entities to different classes and encapsulate the db entities.
But this would introduce more bloat, as I already have data transfer objects for communication.

**Comment by ajcvickers** [comment]
@timmi-on-rails As the documentation Says, "Detection of changes is needed when a property or navigation has been changed _without using EF Core to make this change._"  No EF code runs when you clear the collection of Posts on the blog object--it's just a normal .NET collection. Contrast this with calling `DbSet.Add`, which is an EF method.

**Comment by timmi-on-rails** [comment]
I get, that EF does not know about the change at the point I call `Remove()`, but that does not explain:

- Why can't EF properly remove the orphaned `Post` instances on `SaveChanges()`, although the relation has `DeleteBehavior.Cascade`. So if the blog is gone, the already tracked posts should be gone as well no matter what the navigation property of the blog contains.
- Why does it work, if I call `SaveChanges()` after `Add()`

To me it still looks inconsistent or atleast unintuitive.

**Comment by ajcvickers** [comment]
Note: potential improvement to local detect changes. Related to #26831.
