### ISSUE TITLE
SQLite: ValueGeneratedOnAdd doesn't work on GUID column that is not a key

### ISSUE THREAD

**Issue by RdJNL** [dotnet/efcore#25847]
When applying _ValueGeneratedOnAdd_ to a GUID column that is not in a primary or alternate key, a value is not generated.

```C#
using System;
using Microsoft.EntityFrameworkCore;

namespace SomeProgram
{
    public static class Program
    {
        public class MyDbContext : DbContext
        {
            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseSqlite("Data Source=test.db");
            }

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                modelBuilder.Entity<A>().Property(a => a.Guid).ValueGeneratedOnAdd();
            }
        }

        public class A
        {
            public int Id { get; set; }
            public Guid Guid { get; set; }
            public string Name { get; set; } = "";
        }

        public static void Main(string[] args)
        {
            using( var context = new MyDbContext() )
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                context.Set<A>().Add(new A
                {
                    Name = "abcd",
                });

                context.SaveChanges();
            }
        }
    }
}
```

This code throws the following exception when calling _SaveChanges_:
```
Microsoft.EntityFrameworkCore.DbUpdateException
  HResult=0x80131500
  Message=An error occurred while saving the entity changes. See the inner exception for details.
  Source=Microsoft.EntityFrameworkCore.Relational
  StackTrace:
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__103_0(DbContext _, ValueTuple`2 t)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at SomeProgram.Program.Main(String[] args) in ***\Program.cs:line 40

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
SqliteException: SQLite Error 19: 'NOT NULL constraint failed: A.Guid'.
```

Stack trace for the inner exception:
```
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
```

Adding _A.Guid_ as alternate key works:
```C#
modelBuilder.Entity<A>().HasAlternateKey(a => a.Guid);
```

Manually settings the value generator also works:
```C#
modelBuilder.Entity<A>().Property(a => a.Guid).HasValueGenerator<Microsoft.EntityFrameworkCore.ValueGeneration.GuidValueGenerator>();
```

### Provider and version information

EF Core version: 6.0.0-preview.7.21378.4
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 6
Operating system: Windows 10
IDE: Visual Studio 2022 17.0.0 Preview 3.1

**Comment by ajcvickers** [comment]
@RdJNL EF Core only supplies value generators for keys. To use a generated value on a different column, either configure the database column with a default expression, or explicitly configure an EF value generator. For example:

```C#
modelBuilder.Entity<A>().Property(a => a.Guid).HasValueGenerator<GuidValueGenerator>();
```

**Comment by RdJNL** [comment]
Yeah, that's one of the workarounds I had already found.

Is there a reason EF Core doesn't supply value generators for non-keys?

**Comment by ajcvickers** [comment]
@RdJNL It does, but the value generator needs to be configured explicitly. This is because value for keys have a specific purpose--to act as a key. Values generated can be generated for other properties for any number of reasons. Even in the GUID case above, you probably don't want sequential GUIDs for non-keys, but you probably do, if possible, for keys.

**Comment by RdJNL** [comment]
@ajcvickers Thanks for the clarification :)
