### ISSUE TITLE
Migrate Collation Fails

### ISSUE THREAD

**Issue by zmhh** [dotnet/efcore#26092]
## Bug

Migrating a collation fails with exception:

`System.Data.SqlClient.SqlException (0x80131904): The database [database] could not be exclusively locked to perform the operation.`

Where [database] is the database to be migrated.

## Attempt to workaround

It seems like the way to fix this is to perform before the alter database command:

`ALTER DATABASE [database] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;`

and after the command:

`ALTER DATABASE [database] SET MULTI_USER;`

But trying to do this as a workaround using `migrationBuilder.Sql` to do the command before and after the `migrationBuilder.AlterDatabase` method results in the error:

`System.Data.SqlClient.SqlException (0x80131904): ALTER DATABASE statement not allowed within multi-statement transaction.`

### Stack trace

```
System.Data.SqlClient.SqlException (0x80131904): The database [database] could not be exclusively locked to perform the operation.
ALTER DATABASE failed. The default collation of database '[database]' cannot be set to Latin1_General_100_CI_AI_SC_UTF8.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
```

### Include provider and version information

EF Core version: 5.0.9
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 3.1
Operating system: Windows

**Comment by zmhh** [comment]
Adding `suppressTransaction: true` to the single/multi-user mode commands seems to fix the error reported here. Like so:

```
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER DATABASE CURRENT SET SINGLE_USER WITH ROLLBACK IMMEDIATE;", suppressTransaction: true);

            migrationBuilder.AlterDatabase(
                collation: "Latin1_General_100_CI_AI_SC_UTF8");

            migrationBuilder.Sql("ALTER DATABASE CURRENT SET MULTI_USER;", suppressTransaction: true);
        }
```

Unfortunately I get a different error "(0x80131904): The operation cannot be performed on database "[database]" because it is involved in a database mirroring session or an availability group. Some operations are not allowed on a database that is participating in a database mirroring session or in an availability group", but I think that is unrelated.

**Comment by roji** [comment]
The original error (`The database ... could not be exclusively locked to perform the operation`) does not reproduce for me on my local SQL Server - I can alter the database collation just fine without switching the database to single-user mode. Some thoughts:

* @zmhh it's likely that you have some other active connection to your SQL Server database while attempting to perform this operation. Can you please try again, making sure that no other connection is in progress?
* This might be some sort of Azure SQL limitation

**Comment by zmhh** [comment]
Yes, the problem is due to concurrent connections to the server, so it is arguable whether this is a bug. It does seem like a potentially common scenario, in which case maybe an enhancement to add a param for single user mode when doing alter database commands would be more appropriate that reporting this as a bug.

**Comment by zmhh** [comment]
The second error, regarding “mirroring session”, is definitely related to Azure SQL specifically - it turns out that it doesn’t support `alter database` commands.

**Comment by roji** [comment]
Yeah, it's generally discouraged to perform migrations while applications are connected to the database (and especially ALTER DATABASE ones which have such a large impact).

Reopening to discuss add switching to single-user mode and back whenever any ALTER DATABASE migrations are present.

**Comment by ajcvickers** [comment]
Note from triage: we switched to single user mode sometimes in EF6. Backlogging to consider doing the same in Core.

**Comment by xaviergxf** [comment]
I've hit this issue when using Aspire and it's SQL Server resource on dotnet 8 latest sdk.

I have a migrationProject, just like documented on https://learn.microsoft.com/en-us/dotnet/aspire/database/ef-core-migrations?tabs=dotnet-cli%2Cdotnet-cli-2#create-the-migration-service with WaitForCompletion, meaning, no-one else is trying to concurrently use the same connection.

I've tried to apply the the solution provided by @zmhh but hit another issue after the next migration executes:
```
Resetting the connection results in a different state than the initial login. The login fails.
Login failed for user 'sa'.
Cannot continue the execution because the session is in the kill state.
```
