### ISSUE TITLE
EF Core Scaffold-DbContext error Invalid column name 'has_filter'. Invalid column name 'filter_definition'.

### ISSUE THREAD

**Issue by isgori3** [dotnet/efcore#26165]
Hello everybody I have a problem when I try to create my classes withe command:

**Scaffold-DbContext "ConnectionString" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models**

They gave me the next error:

```
Security Warning: The negotiated TLS 1.0 is an insecure protocol and is supported for backward compatibility only. The recommended protocol version is TLS 1.2 and later.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'has_filter'.
Invalid column name 'filter_definition'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) in H:\tsaagent1\_work\21\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlConnection.cs:line 1777
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) in H:\tsaagent1\_work\21\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlInternalConnection.cs:line 606
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) in H:\tsaagent1\_work\21\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\TdsParser.cs:line 1302
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) in H:\tsaagent1\_work\21\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\TdsParser.cs:line 2523
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData() in H:\tsaagent1\_work\21\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlDataReader.cs:line 1139
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData() in H:\tsaagent1\_work\21\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlDataReader.cs:line 265
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted) in H:\tsaagent1\_work\21\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 4683
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest) in H:\tsaagent1\_work\21\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 4499
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method) in H:\tsaagent1\_work\21\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 4182
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) in H:\tsaagent1\_work\21\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 4054
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior) in H:\tsaagent1\_work\21\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 1856
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in H:\tsaagent1\_work\21\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 1819
   at Microsoft.EntityFrameworkCore.SqlServer.Scaffolding.Internal.SqlServerDatabaseModelFactory.GetIndexes(DbConnection connection, IReadOnlyList`1 tables, String tableFilter)
   at Microsoft.EntityFrameworkCore.SqlServer.Scaffolding.Internal.SqlServerDatabaseModelFactory.GetTables(DbConnection connection, DatabaseModel databaseModel, Func`3 tableFilter, IReadOnlyDictionary`2 typeAliases)
   at Microsoft.EntityFrameworkCore.SqlServer.Scaffolding.Internal.SqlServerDatabaseModelFactory.Create(DbConnection connection, DatabaseModelFactoryOptions options)
   at Microsoft.EntityFrameworkCore.SqlServer.Scaffolding.Internal.SqlServerDatabaseModelFactory.Create(String connectionString, DatabaseModelFactoryOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluarlize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:cb0537cd-bf21-49f5-ac79-9a621b191a62
Error Number:207,State:1,Class:16
Invalid column name 'has_filter'.
Invalid column name 'filter_definition'.
```

I saw a post with the same error but this is different with the database and framework 

**Further technical details**
SQL Server Management Studio 18.9.2
Microsoft.EntityFrameworkCore 5.0.10
Microsoft.EntityFrameworkCore.SqlServer 5.0.10
Microsoft.EntityFrameworkCore.Tools 5.0.10
Visual Studio 2019 16.11.3
Framework 5

**Comment by ErikEJ** [comment]
Which SQL Server version?

**Comment by isgori3** [comment]
> Which SQL Server version?

It's 2019 Server Express

**Comment by ajcvickers** [comment]
@isgori3 We don't think you should be seeing this with SQL Server 2019. Some things you can check:
* Are you running SQL Server with a compatibility mode that makes it behave like and earlier version?
* Do you have restricted permissions which might be preventing you from looking at system tables?

**Comment by isgori3** [comment]
> @isgori3 We don't think you should be seeing this with SQL Server 2019. Some things you can check:
> 
> * Are you running SQL Server with a compatibility mode that makes it behave like and earlier version?
> * Do you have restricted permissions which might be preventing you from looking at system tables?

Not my SQL Server is run normal
What means about restricted permissions ? User on Windows or User on SQL Server, in SQL Server has all the permissions for connect, select, delete, update and alter, and I'm using windows authentication

**Comment by ErikEJ** [comment]
Can you try to run this SQL when connected to your database (replace name with the actual name)

```
USE YourDatabase;  
GO  
SELECT compatibility_level  
FROM sys.databases WHERE name = 'YourDatabase';  
GO  

```

**Comment by ErikEJ** [comment]
@isgori3 Compatibility level 90 (SQL Server 2005) is not supported by EF Core, you must be at least at 110 (SQL Server 2012), which is the oldest SQL Server version still in support.

**Comment by ErikEJ** [comment]
Restore from a backup?

**Comment by isgori3** [comment]
> Restore from a backup?

Not this database is new, I installed the SQL Server 2019,  created database and tables and gave me that error maybe in the installation I missed something?

**Comment by ErikEJ** [comment]
Restore from a backup?

**Comment by ErikEJ** [comment]
Some script or user set the compability level to 90...

**Comment by isgori3** [comment]
> Some script or user set the compability level to 90...

![image](https://user-images.githubusercontent.com/83226165/135106748-1eaf6590-6b21-4dac-b2b7-f360ca4546c8.png)

I checked, and I only have the access to modify to these versions, so I don't know

**Comment by ErikEJ** [comment]
I am guessing you are not running SQL Server 2019 then!

SELECT @@Serverversion

**Comment by isgori3** [comment]
> I am guessing you are not running SQL Server 2019 then!
> 
> SELECT @@Serverversion

You are right, I need to check the installer I have, thank you!!

**Comment by ajcvickers** [comment]
Thanks for helping here, @ErikEJ.

**Comment by ErikEJ** [comment]
I had to make it make sense 😹
