### ISSUE TITLE
Why is AsNoTrackingWithIdentityResolution() different to .AsTracking(QueryTrackingBehavior.NoTrackingWithIdentityResolution)?

### ISSUE THREAD

**Issue by TAGC** [dotnet/efcore#26227]
## Ask a question

I'm trying to resolve an issue in which I need EF Core to be able to resolve a recursive one-to-many relationship: 

![](https://yuml.me/da14cde5.svg)

I've set up this simple test:

```csharp
[Test]
public async Task Temp()
{
    var productTypes = await Query(context => context.ProductTypes
        //.AsTracking(QueryTrackingBehavior.NoTrackingWithIdentityResolution)
        .AsNoTrackingWithIdentityResolution()
        .Include(pt => pt.Group)
        .ThenInclude(x => x.Variants.Where(v => v.IsAvailable))
        .Where(pt => pt.IsAvailable)
        .ToListAsync());

    var trackerGroup = productTypes.Single(x => x.Key == "Tracker");
    trackerGroup.Variants.Count.ShouldBe(3);
    trackerGroup.Variants.ShouldContain(x => x.Key == "TrackerRetrieveThreeYear");
    trackerGroup.Variants.ShouldContain(x => x.Key == "TrackerMonitorThreeYear");
    trackerGroup.Variants.ShouldContain(x => x.Key == "TrackerLocateThreeYear");
}
```

If I run that, then the query executes fine and the test passes.

If instead I run:

```csharp
[Test]
public async Task Temp()
{
    var productTypes = await Query(context => context.ProductTypes
        .AsTracking(QueryTrackingBehavior.NoTrackingWithIdentityResolution)
        //.AsNoTrackingWithIdentityResolution()
        .Include(pt => pt.Group)
        .ThenInclude(x => x.Variants.Where(v => v.IsAvailable))
        .Where(pt => pt.IsAvailable)
        .ToListAsync());

    var trackerGroup = productTypes.Single(x => x.Key == "Tracker");
    trackerGroup.Variants.Count.ShouldBe(3);
    trackerGroup.Variants.ShouldContain(x => x.Key == "TrackerRetrieveThreeYear");
    trackerGroup.Variants.ShouldContain(x => x.Key == "TrackerMonitorThreeYear");
    trackerGroup.Variants.ShouldContain(x => x.Key == "TrackerLocateThreeYear");
}
```

Then the test fails with this exception:

```
System.InvalidOperationException
  HResult=0x80131509
  Message=The Include path 'Group->Variants' results in a cycle. Cycles are not allowed in no-tracking queries; either use a tracking query or remove the cycle.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.IncludeExpandingExpressionVisitor.VerifyNoCycles(IncludeTreeNode includeTreeNode)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.IncludeExpandingExpressionVisitor.ExpandInclude(Expression root, EntityReference entityReference)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.IncludeExpandingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ExpandingExpressionVisitor.Expand(Expression expression, Boolean applyIncludes)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.PendingSelectorExpandingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__65`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ArnoldClark.Sales.Commissions.ApplicationServices.Tests.ApplicationTesting.<>c__DisplayClass14_0`1.<<Query>b__0>d.MoveNext() in C:\Projects\sales-commissions\tests\ArnoldClark.Sales.Commissions.ApplicationServices.Tests\ApplicationTesting.cs:line 139

  This exception was originally thrown at this call stack:
    [External Code]
    ArnoldClark.Sales.Commissions.ApplicationServices.Tests.ApplicationTesting.Query.AnonymousMethod__0(ArnoldClark.Sales.Commissions.Infrastructure.Data.CommissionsContext) in ApplicationTesting.cs
```

This is very unexpected behaviour as I assumed `AsNoTrackingWithIdentityResolution()` was just a helpful shortcut for `AsTracking(QueryTrackingBehavior.NoTrackingWithIdentityResolution)`.

EF Core version: 5.0.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.11.3

**Comment by TAGC** [comment]
I've updated to EF Core 5.0.10 and I still observe the same behaviour.

**Comment by Wazner** [comment]
It seems the `AsTracking` method only supports `QueryTrackingBehavior.TrackAll` and `QueryTrackingBehavior.TrackNone)`

From the source code:
https://github.com/dotnet/efcore/blob/289e7a69b0c02f5569bbaf0ac353c21afde5e397/src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs#L2982-L2988
