### ISSUE TITLE
Sequence contains no elements running in-memory query with class key

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#26238]
See skipped tests in KeysWithConvertersInMemoryTest

**Comment by ajcvickers** [comment]
Example of test that fails:

```C#
        [ConditionalFact]
        public virtual void Can_query_and_update_owned_entity_with_int_bare_class_key()
        {
            using (var context = CreateContext())
            {
                context.Add(new OwnerBareIntClassKey(new(1), new(77)));
                context.SaveChanges();
            }

            using (var context = CreateContext())
            {
                var owner = context.Set<OwnerBareIntClassKey>().Single(o => o.Id.Equals(new BareIntClassKey(1)));
                Assert.Equal(77, owner.Owned.Position);

                owner.Owned = new(88);
                context.SaveChanges();
            }

            using (var context = CreateContext())
            {
                var owner = context.Set<OwnerBareIntClassKey>().Find(new BareIntClassKey(1));
                Assert.Equal(88, owner.Owned.Position);
            }
        }
```

Exception thrown:

```C#
System.InvalidOperationException
Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at lambda_method140(Closure )
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryExpression.ResultEnumerable.GetEnumerator() in C:\dotnet\efcore\src\EFCore.InMemory\Query\Internal\InMemoryQueryExpression.Helper.cs:line 28
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNextHelper() in C:\dotnet\efcore\src\EFCore.InMemory\Query\Internal\InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable.cs:line 153
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext() in C:\dotnet\efcore\src\EFCore.InMemory\Query\Internal\InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable.cs:line 107
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at lambda_method139(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query) in C:\dotnet\efcore\src\EFCore\Query\Internal\QueryCompiler.cs:line 97
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression) in C:\dotnet\efcore\src\EFCore\Query\Internal\EntityQueryProvider.cs:line 78
   at System.Linq.Queryable.Single[TSource](IQueryable`1 source, Expression`1 predicate)
   at Microsoft.EntityFrameworkCore.KeysWithConvertersTestBase`1.Can_query_and_update_owned_entity_with_int_bare_class_key() in C:\dotnet\efcore\test\EFCore.Specification.Tests\KeysWithConvertersTestBase.cs:line 2223
   at Microsoft.EntityFrameworkCore.KeysWithConvertersInMemoryTest.Can_query_and_update_owned_entity_with_int_bare_class_key() in C:\dotnet\efcore\test\EFCore.InMemory.FunctionalTests\KeysWithConvertersInMemoryTest.cs:line 50
```

Types used:

```C#
protected class OwnerBareIntClassKey
{
    public OwnerBareIntClassKey(BareIntClassKey id)
    {
        Id = id;
    }

    public OwnerBareIntClassKey(BareIntClassKey id, OwnedBareIntClassKey owned)
    {
        Id = id;
        Owned = owned;
    }

    public BareIntClassKey Id { get; set; }
    public OwnedBareIntClassKey Owned { get; set; }
}

protected class OwnedBareIntClassKey
{
    public OwnedBareIntClassKey(int position)
    {
        Position = position;
    }
    
    public int Position { get; set; }
}

protected class BareIntClassKey
{
    public static ValueConverter<BareIntClassKey, int> Converter
        = new(v => v.Id, v => new BareIntClassKey(v));

    public static ValueComparer<BareIntClassKey> Comparer
        = new ValueComparer<BareIntClassKey>(
            (l, r) => l.Id == r.Id,
            v => v.Id.GetHashCode(),
            v => new(v.Id));
    
    public BareIntClassKey(int id)
    {
        Id = id;
    }

    public int Id { get; set; }
}
```

**Comment by ankitmatrix08** [comment]
Hi @ajcvickers @smitpatel I yesterday upgraded to the latest [preview-5](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/7.0.0-preview.5.22302.2) - all of a sudden many of my entities started throwing this weird exception. 
![image](https://user-images.githubusercontent.com/18023679/173838875-4501da96-c1ab-4231-b74f-a38813034df3.png)


```
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at Microsoft.EntityFrameworkCore.Query.RelationalEntityShaperExpression.GenerateMaterializationCondition(IEntityType entityType, Boolean nullable)
   at Microsoft.EntityFrameworkCore.Query.EntityShaperExpression..ctor(IEntityType entityType, Expression valueBufferExpression, Boolean nullable, LambdaExpression materializationCondition)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.SharedTypeEntityExpandingExpressionVisitor.TryExpand(Expression source, MemberIdentity member)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.SharedTypeEntityExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.SharedTypeEntityExpandingExpressionVisitor.Expand(SelectExpression selectExpression, Expression lambdaBody)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.RemapLambdaBody(ShapedQueryExpression shapedQueryExpression, LambdaExpression lambdaExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Linq.SystemCore_EnumerableDebugView`1.get_Items()
```
When I reverted the package back to [preview-4](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/7.0.0-preview.4.22229.2) all of the exceptions vanished.

Is the latest preview release buggy?

**Comment by ajcvickers** [comment]
We recommend against using the in-memory provider for testing--see [Testing EF Core Applications](https://learn.microsoft.com/en-us/ef/core/testing/). While we have [no plans to remove the in-memory provider](https://github.com/dotnet/efcore/issues/18457), we will not be adding any new features to this provider because we believe valuable development time is better spent in other areas. When feasible, we plan to still fix regressions in existing behavior.
