### ISSUE TITLE
Nested projection fails to translate to query

### ISSUE THREAD

**Issue by markovana** [dotnet/efcore#26352]
Hi.
I am trying exposing entities as projected dto-s and I have additional middleware which applies final projections to dto-s to select only specific data. Currently it fails to translate query when trying to access projected collection.

```C#
var queryable = dbContext.ClaimCases.Select(c => new ClaimDto
{
    ClaimNumber = c.ClaimNumber,
    Policy = c.Policy == null
        ? null
        : new PolicyDto
        {
            PolicyNumber = c.Policy.PolicyNumber,
            TermsAndConditions = c.Policy.TermsAndConditions.Select(tc =>
                new TermsAndConditionsDto
                {
                    Label = tc.Label,
                    Code = tc.Code
                }).ToList()
        }
});

var dto = queryable.Select(c => new ClaimDto
    {
        ClaimNumber = c.ClaimNumber,
        Policy = c.Policy != null
            ? new PolicyDto
            {
                PolicyNumber = c.Policy.PolicyNumber,
                TermsAndConditions = c.Policy.TermsAndConditions.Select(t => // if this is included it will cause exception
                    new TermsAndConditionsDto
                    {
                        Code = t.Code
                    }).ToList()
            }
            : null
    })
    .ToList();
```
Small reproducible project: https://github.com/markovana/ef-projection-issue/tree/master/projection

### Stack trace

```
Compiling query expression:
      'DbSet<Claim>()
          .Select(c => new ClaimDto{
              ClaimNumber = c.ClaimNumber,
              Policy = c.Policy == null ? null : new PolicyDto{
                  PolicyNumber = c.Policy.PolicyNumber,
                  TermsAndConditions = c.Policy.TermsAndConditions
                      .Select(tc => new TermsAndConditionsDto{
                          Label = tc.Label,
                          Code = tc.Code
                      }
                      )
                      .ToList()
              }

          }
          )
          .Select(c => new ClaimDto{
              ClaimNumber = c.ClaimNumber,
              Policy = c.Policy != null ? new PolicyDto{
                  PolicyNumber = c.Policy.PolicyNumber,
                  TermsAndConditions = c.Policy.TermsAndConditions
                      .Select(t => new TermsAndConditionsDto{ Code = t.Code }
                      )
                      .ToList()
              }
               : null
          }
          )'
Unhandled exception. System.InvalidOperationException: The LINQ expression 't' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerab
le', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMember(MemberExpression memberExpression)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberAssignment(MemberAssignment memberAssignment)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberAssignment(MemberAssignment memberAssignment)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitConditional(ConditionalExpression conditionalExpression)
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberAssignment(MemberAssignment memberAssignment)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at projection.Program.Main(String[] args) in C:\repos\github\ef-projection-issue\projection\Program.cs:line 31

```

### Provider and version information

EF Core version: 5.0.11
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1

**Comment by maumar** [comment]
updated stack trace

```
Message: 
System.InvalidOperationException : The LINQ expression 't => new TermsAndConditionsDto{ Code = t.Code }
' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

  Stack Trace: 
RelationalSqlTranslatingExpressionVisitor.VisitLambda[T](Expression`1 lambdaExpression) line 625
RelationalSqlTranslatingExpressionVisitor.TranslateInternal(Expression expression, Boolean applyDefaultTypeMapping) line 153
RelationalSqlTranslatingExpressionVisitor.TranslateProjection(Expression expression, Boolean applyDefaultTypeMapping) line 135
RelationalProjectionBindingExpressionVisitor.Visit(Expression expression) line 178
RelationalProjectionBindingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) line 532
RelationalProjectionBindingExpressionVisitor.Visit(Expression expression) line 228
RelationalProjectionBindingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) line 532
RelationalProjectionBindingExpressionVisitor.Visit(Expression expression) line 228
RelationalProjectionBindingExpressionVisitor.VisitMemberAssignment(MemberAssignment memberAssignment) line 465
ExpressionVisitor.VisitMemberBinding(MemberBinding node)
RelationalProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression) line 508
RelationalProjectionBindingExpressionVisitor.Visit(Expression expression) line 102
RelationalProjectionBindingExpressionVisitor.VisitConditional(ConditionalExpression conditionalExpression) line 278
RelationalProjectionBindingExpressionVisitor.Visit(Expression expression) line 228
RelationalProjectionBindingExpressionVisitor.VisitNew(NewExpression newExpression) line 584
RelationalProjectionBindingExpressionVisitor.Visit(Expression expression) line 102
RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression) line 71
RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector) line 1112
QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) line 498
RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) line 234
QueryableMethodTranslatingExpressionVisitor.Translate(Expression expression) line 63
QueryCompilationContext.CreateQueryExecutorExpression[TResult](Expression query) line 207
QueryCompilationContext.CreateQueryExecutor[TResult](Expression query) line 174
Database.CompileQuery[TResult](Expression query, Boolean async) line 66
QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async) line 127
<>c__DisplayClass11_0`1.<ExecuteCore>b__0() line 83
CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) line 64
QueryCompiler.ExecuteCore[TResult](Expression query, Boolean async, CancellationToken cancellationToken) line 79
QueryCompiler.Execute[TResult](Expression query) line 60
EntityQueryProvider.Execute[TResult](Expression expression) line 62
EntityQueryable`1.GetEnumerator() line 78
```
