### ISSUE TITLE
Bug occurs when one-to-one with optional navigation property

### ISSUE THREAD

**Issue by yangzhongke** [dotnet/efcore#26489]
## File a bug
When using one-to-one with optional navigation  property, the following exception is thrown:"The database operation was expected to affect 1 row(s), but actually affected 0 row(s); "

### Include your code

```C#
    class A
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public B? B { get; set; }
        public Guid? BId { get; set; }
    }
    class B
    {
        public Guid Id { get; set; }
        public int Age { get; set; }
        public A A { get; set; }
        public Guid AId { get; set; }
    }
    class MyDbContext:DbContext
    {
        public DbSet<A> A { get; set; }
        public DbSet<B> B { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            optionsBuilder.UseSqlServer("Server=.;Database=testbug;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<A>().HasOne(x => x.B).WithOne(x => x.A)
                //.IsRequired(false)
                .HasForeignKey<B>(x => x.AId);//.HasPrincipalKey<A>(x=>x.BId);
        }
    }

```
```
using MyDbContext ctx = new MyDbContext();
A a1 = new A() { Id=Guid.NewGuid(),Name="ABC"};
ctx.A.Add(a1);
ctx.SaveChanges();
A a2 = ctx.A.Include(x=>x.B).Single(x=>x.Id==a1.Id);
a1.B = new B() { Id = Guid.NewGuid(), Age = 18 };
ctx.SaveChanges();
```

### Include stack traces
I inspected the generated SQL, it generated Update statement instead of Insert one.
```sql
SET NOCOUNT ON;
      UPDATE [B] SET [AId] = @p0, [Age] = @p1
      WHERE [Id] = @p2;
      SELECT @@ROWCOUNT;
```
The following exception was thrown on the last SaveChanges().
```
Microsoft.EntityFrameworkCore.Update)
      Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
         at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
         at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithoutPropagation(Int32 commandIndex, RelationalDataReader reader)
         at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
         at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__104_0(DbContext _, ValueTuple`2 t)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)

```

### Include provider and version information

EF Core version: 6.0.0-rc.2.21480.5
Database provider:Microsoft.EntityFrameworkCore.SqlServer 
Target framework:net6.0
Operating system: Win 10 X64
IDE:VS 2022 RC3

**Comment by ajcvickers** [comment]
@yangzhongke The `Id` properties of your entities are configured as automatically generated (the default) but you are setting the values explicitly. See [Generated versus explicit key values](https://docs.microsoft.com/en-us/ef/core/change-tracking/explicit-tracking#generated-versus-explicit-key-values) for more information.

**Comment by yangzhongke** [comment]
It works.
Thanks.
