### ISSUE TITLE
Irrelevant value in the shadow property leads to an wrong state of the nested entity in the StateManager

### ISSUE THREAD

**Issue by EmptyBucket** [dotnet/efcore#26499]
## File a bug

InternalEntityEntry.SetEntityState() is not selecting the correct state for the nested entity. This is because ValueGenerationManager.Propagate() does not correctly select the principal entry. This is due to the fact that the shadow property FK is irrelevant(default). If we abandon the shadow property and explicitly specify FK, then everything works as expected, since FK has the correct value. 

See screenshots(wrong nested item principal - Another, state - Modified):
https://imgur.com/a/CFDmpBw

An wrong state results in an error:
```
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Npgsql.EntityFrameworkCore.PostgreSQL.Update.Internal.NpgsqlModificationCommandBatch.Consume(RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at ConsoleApp27.Program.Main(String[] args) in /home/strix/RiderProjects/ConsoleApp27/ConsoleApp27/Program.cs:line 18
```

Workaround(correct nested item principal - Item, state - Added):
https://imgur.com/a/W6PX1Ot

Project:
https://github.com/EmptyBucket/Tmp

### Include provider and version information

EF Core version: 5.0.11
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: netcoreapp3.1
Operating system: manjaro linux
IDE: jetbrains rider 2021.2.2

**Comment by ajcvickers** [comment]
@EmptyBucket The repro project referenced appears to assume the database already contains some data. Can you update the project to put the database in the expected state when starting with an empty database so that we can investigate?

**Comment by EmptyBucket** [comment]
> @EmptyBucket The repro project referenced appears to assume the database already contains some data. Can you update the project to put the database in the expected state when starting with an empty database so that we can investigate?

I did, pushed

**Comment by ajcvickers** [comment]
@roji Can you take a look at this. It has some PostgreSQL specific stuff in it.

**Comment by roji** [comment]
@ajcvickers below is a cleaned-up repro for SQL Server. Note that with EF Core 5.0 I get `Database operation expected to affect 1 row(s) but actually affected 0 row(s)` as above, but with EF Core 6.0 I get `The value of shadow key property 'NestedItem.Id' is unknown when attempting to save changes.`.

Am leaving this to you for now (mainly because it's very late!) but if you'd like me to continue investigating just say so.

<details>
<summary>Simplified SQL Server repro</summary>

```c#
using var ctx = new MyDbContext();
ctx.Database.EnsureDeleted();
ctx.Database.EnsureCreated();
ctx.Database.ExecuteSqlRaw(@"
INSERT INTO ""AnotherRoot"" (""Id"", ""Name"") VALUES ('546df14f-2cbf-47fe-a5db-f105929546a2', 'first');
INSERT INTO ""Root"" (""Id"") VALUES ('c729fae1-4c57-4b86-a7a8-61cf786435f8');
INSERT INTO ""Item"" (""Id"", ""RootId"") VALUES ('cc692879-19e5-4cd2-ad70-626d371b011f', 'c729fae1-4c57-4b86-a7a8-61cf786435f8');
INSERT INTO ""NestedItem"" (""Id"", ""AnotherId"", ""Name"", ""ChangeNumber"", ""ItemId"") VALUES
('afb3fc33-ad86-4a86-9872-9d8752286079', '546df14f-2cbf-47fe-a5db-f105929546a2', 'first', 1, 'cc692879-19e5-4cd2-ad70-626d371b011f'),
('2da4168c-a442-4902-bc5e-affb7f5fe93f', '546df14f-2cbf-47fe-a5db-f105929546a2', 'second', 2, 'cc692879-19e5-4cd2-ad70-626d371b011f');");

var another = ctx.Set<AnotherRoot>().First(a => a.Id == new Guid("546df14f-2cbf-47fe-a5db-f105929546a2"));
var root = ctx.Set<Root>()
	.Include(a => a.Collection)
	.ThenInclude(i => i.NestedCollection)
	.ThenInclude(n => n.Another)
	.First();

var existNestedItem1 = root.Collection.First().NestedCollection.First();
var newNestedItem3 = new NestedItem("third", another);
root.Collection = new List<Item>
{
	new() { NestedCollection = new List<NestedItem> {existNestedItem1, newNestedItem3 }}
};
ctx.UpdateRange(root.Collection);
ctx.Update(root);

ctx.SaveChanges();

public class MyDbContext : DbContext
{
	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		=> optionsBuilder
			.UseSqlServer("Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Trust Server Certificate=true")
			// .UseNpgsql("Host=localhost;Username=test;Password=test")
			.LogTo(Console.WriteLine, LogLevel.Information);

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.HasSequence<int>("ChangeNumbers");

		modelBuilder.Entity<AnotherRoot>().HasKey(a => a.Id);
		modelBuilder.Entity<AnotherRoot>().Property(a => a.Id).ValueGeneratedNever();
		modelBuilder.Entity<AnotherRoot>().Property(n => n.Name).IsRequired();

		modelBuilder.Entity<Root>().HasKey(a => a.Id);
		modelBuilder.Entity<Root>().Property(a => a.Id).ValueGeneratedNever();
		modelBuilder.Entity<Root>().OwnsMany(a => a.Collection, ib =>
		{
			ib.Property<Guid>("Id").ValueGeneratedOnAdd();
			ib.HasKey("Id");
			ib.OwnsMany(i => i.NestedCollection, nd =>
			{
				nd.Property<Guid>("Id").ValueGeneratedOnAdd();
				nd.HasKey("Id");

				// PG:
				// nd.Property(n => n.ChangeNumber).ValueGeneratedOnAdd().UseSerialColumn();
				// SQL Server:
				nd.Property(n => n.ChangeNumber).HasDefaultValueSql("NEXT VALUE FOR ChangeNumbers");

				nd.Property(n => n.Name).IsRequired();
				nd.HasOne<AnotherRoot>(nameof(NestedItem.Another)).WithMany().HasForeignKey("AnotherId").IsRequired();
			});
		});
	}
}

public interface IAnother
{
	Guid Id { get; }

	string Name { get; }
}

public class AnotherRoot : IAnother
{
	public Guid Id { get; set; }

	public string Name { get; set; }
}

public class Root
{
	public Guid Id { get; set; }

	public List<Item> Collection { get; set; }
}

public class Item
{
	public List<NestedItem> NestedCollection { get; set; }
}

public class NestedItem
{
	private NestedItem(string name) => Name = name;

	public NestedItem(string name, IAnother another) : this(name)
	{
		Another = another;
		// AnotherId = another.Id;
	}

	public IAnother Another { get; }

	// ReSharper disable once UnusedAutoPropertyAccessor.Global
	// public Guid AnotherId { get; }

	public string Name { get; set; }

	// ReSharper disable once UnassignedGetOnlyAutoProperty
	public long ChangeNumber { get; }
}
```

</details>

**Comment by ajcvickers** [comment]
@roji The SQL Server error is what I would expect for this code. As the message says, the ID value is not known because it is in shadow state and the entity was attached. We have no idea if this is a new entity instance or an existing instance. The general solution to this is to not put PKs in shadow state; it's a pit of failure.

Do you know why this behaves differently with Npgsql?

**Comment by ajcvickers** [comment]
Closing as by-design. See comment above.
