### ISSUE TITLE
Scaffolder throws error if junction table foreign key columns have identical names

### ISSUE THREAD

**Issue by aboondeviant** [dotnet/efcore#26496]
In the new EF Core 6 Scaffolder junction tables are generated as many-to-many relationships and not as separate entities.

The scaffolder seems to be using the column names in the junction table to generate names of the navigation properties.
This will cause issues if you have multiple junction tables using the same column name (this can be quite common if a table has multiple junction tables to it self)

### Expected behaviour:

It would be preferable if the scaffolder didn't fail but had a fallback for duplicate names (eg. `Products` and `Products1`).
This behavious is already used if scaffolded tables have identical names.

### Stack trace:

```
System.InvalidOperationException: The property or navigation 'Products' cannot be added to the entity type 'Product (Dictionary<string, object>)' because a property or navigation with the same name already exists on entity type 'Pro
duct (Dictionary<string, object>)'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.AddSkipNavigation(String name, MemberInfo memberInfo, EntityType targetEntityType, Boolean collection, Boolean onDependent, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.Microsoft.EntityFrameworkCore.Metadata.IMutableEntityType.AddSkipNavigation(String name, MemberInfo memberInfo, IMutableEntityType targetEntityType, Boolean collection
, Boolean onDependent)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitForeignKeys(ModelBuilder modelBuilder, IList`1 foreignKeys)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOpti
ons codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerabl
e`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumera
ble`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluarlize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Reproduction:

This works with any table that has 2 junction tables connected to it where the junction tables are using the same column names.

Repo with SQL script to create a database that generates an error.
https://github.com/aboondeviant/ef-core-junction-table-issue

### Include provider and version information

EF Core version: 6.0.0-rtm.21519.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 6.0.0-rc2

**Comment by smitpatel** [comment]
https://github.com/dotnet/efcore/blob/ce751dc07f0a5f40f61dcb320e37e12ef02c2d39/src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs#L945

Need to add SkipNav names in identifiers list too.

**Comment by ajcvickers** [comment]
FYI for those impacted by this issue: EF Core 6.0.1 is now [available from NuGet](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/6.0.1).
