### ISSUE TITLE
Regression in .NET 6 and/or EF Core 6.0: file based Sqlite database file is blocked after use.

### ISSUE THREAD

**Issue by DerAlbertCom** [dotnet/efcore#26605]
### Description

I think I found a regression in `Microsoft.EntityFrameworkCore.Sqlite` Version 6.0.0 under Windows 10. It works find with 5.0.x, and also it works without a problem under Mac OS 11/12.

For "Unit test" we needed a database, so we used Sqlite for that. For one test  we needed per persistent Db File for this. After the Test we manually deleted the Database with `File.Delete()` so that everything I clean after the test. We didn't use `DbContext.Database.EnsureDeleted()` because we have no easy access to the DbContext. In the sample project I tested it also with `EnsureDeleted()` and that worked. 

Here is the code and a sample project (minimal) for 

#### The Test

https://github.com/DerAlbertCom/EfCore6Regression/blob/2046cc5d11d63e4b0ccf7589dbfab2d2dc34fe86/Regression/TheNet6RegressionTest.cs#L11-L56

#### The Project

https://github.com/DerAlbertCom/EfCore6Regression/

The test works fine with .NET 5 und fails with .NET 6 on Windows.

`dotnet test` will run the test on both frameworks.

### stack trace
This exceptions is thrown with .NET 6 on Windows 10.

```
System.IO.IOException: The process cannot access the file 'C:\src\private\EFCore6Regression\EFCore6Regression\Regression\bin\Debug\net6.0\cb3011cf-c2a...

System.IO.IOException
The process cannot access the file 'C:\src\private\EFCore6Regression\EFCore6Regression\Regression\bin\Debug\net6.0\cb3011cf-c2ac-4308-8cda-452ce83c0d4b.db' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Regression.TheNet6RegressionTest.Dispose() in C:\src\private\EFCore6Regression\EFCore6Regression\Regression\TheNet6RegressionTest.cs:line 53
   at Xunit.Sdk.ExecutionTimer.Aggregate(Action action) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 31
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 79
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass47_0.<RunAsync>b__1() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 216
   at Xunit.Sdk.ExceptionAggregator.Run(Action code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 73
```

### Include provider and version information

EF Core version: 6.0
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 6.0
Operating system: Windows 10
IDE: dotnet test

**Comment by ajcvickers** [comment]
From #26580 yesterday, posted by @roji:

This is by design, [see breaking change note for 6.0](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/breaking-changes#connection-pool).

The SQLite provider now pools connections, improving connection speed significantly but keeping connections open. You can disable pooling by adding `Pooling=false` to the connection string or calling `SqliteConnection.ClearAllPools()` at the point where you want them to be closed.

**Comment by DerAlbertCom** [comment]
Thank you. Didn't thought about looking up the Breaking Changes.
