### ISSUE TITLE
[6.0][CosmosDB] System.ArgumentException: value must not be null, empty, or whitespace.

### ISSUE THREAD

**Issue by XzaR90** [dotnet/efcore#26627]
## File a bug
I get this error but only when hosted on Azure with Linux App Service Plan. It is working locally with Windows 10 targeting same database using VS2022.

### Include your code
Cannot reproduce locally.

### Include stack traces
```
System.ArgumentException: value must not be null, empty, or whitespace.
   at Microsoft.Azure.Cosmos.SqlObjects.SqlPropertyName..ctor(String value)
   at Microsoft.Azure.Cosmos.SqlObjects.SqlPropertyName.Create(String value)
   at Microsoft.Azure.Cosmos.Query.Core.Parser.CstToAstVisitor.VisitObject_property(Object_propertyContext context)
   at Microsoft.Azure.Cosmos.Query.Core.Parser.CstToAstVisitor.VisitObjectCreateScalarExpression(ObjectCreateScalarExpressionContext context)
   at sqlParser.ObjectCreateScalarExpressionContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Microsoft.Azure.Cosmos.Query.Core.Parser.CstToAstVisitor.VisitUnary_scalar_expression(Unary_scalar_expressionContext context)
   at Microsoft.Azure.Cosmos.Query.Core.Parser.CstToAstVisitor.VisitBinary_scalar_expression(Binary_scalar_expressionContext context)
   at Microsoft.Azure.Cosmos.Query.Core.Parser.CstToAstVisitor.VisitLogical_scalar_expression(Logical_scalar_expressionContext context)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.VisitChildren(IRuleNode node)
   at Microsoft.Azure.Cosmos.Query.Core.Parser.CstToAstVisitor.VisitSelect_value_spec(Select_value_specContext context)
   at sqlParser.Select_value_specContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.VisitChildren(IRuleNode node)
   at Microsoft.Azure.Cosmos.Query.Core.Parser.CstToAstVisitor.VisitSelect_clause(Select_clauseContext context)
   at Microsoft.Azure.Cosmos.Query.Core.Parser.CstToAstVisitor.VisitSql_query(Sql_queryContext context)
   at Microsoft.Azure.Cosmos.Query.Core.Parser.SqlQueryParser.Monadic.Parse(String text)
   at Microsoft.Azure.Cosmos.Query.Core.Parser.SqlQueryParser.TryParse(String text, SqlQuery& sqlQuery)
   at Microsoft.Azure.Cosmos.Query.Core.ExecutionContext.CosmosQueryExecutionContextFactory.TryCreateCoreContextAsync(DocumentContainer documentContainer, CosmosQueryContext cosmosQueryContext, InputParameters inputParameters, ITrace trace, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.Core.AsyncLazy`1.GetValueAsync(ITrace trace, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.LazyQueryPipelineStage.MoveNextAsync(ITrace trace)
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.NameCacheStaleRetryQueryPipelineStage.MoveNextAsync(ITrace trace)
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.CatchAllQueryPipelineStage.MoveNextAsync(ITrace trace)
   at Microsoft.Azure.Cosmos.Query.QueryIterator.ReadNextAsync(ITrace trace, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ClientContextCore.RunWithDiagnosticsHelperAsync[TResult](ITrace trace, Func`2 task)
   at Microsoft.Azure.Cosmos.ClientContextCore.OperationHelperWithRootTraceAsync[TResult](String operationName, RequestOptions requestOptions, Func`2 task, TraceComponent traceComponent, TraceLevel traceLevel)
   at Microsoft.EntityFrameworkCore.Cosmos.Storage.Internal.CosmosClientWrapper.DocumentAsyncEnumerable.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```
### Include verbose output
```
sqlParser+ObjectCreateScalarExpressionContext.Accept
An exception occurred while iterating over the results of a query for context type '{contextType}'.{newline}{error}
Microsoft.EntityFrameworkCore.Query.QueryIterationFailed
An exception occurred while iterating over the results of a query for context type
```

### Include provider and version information

EF Core version: 6.0.0
Database provider: Microsoft.EntityFrameworkCore.Cosmos
Target framework: NET 6.0
Operating system:
App Service, Linux

**Comment by roji** [comment]
@XzaR90 can you provide some sort of minimal code sample which reproduces the above error, including the query and the model? It's very hard to investigate something given only an exception.

**Comment by XzaR90** [comment]
I don't know exactly where the error is because I only have information for Application Insights currently with no debug build.

```C#
    public class ApplicationAuditEntry
    {
        public static string CreatePartitionKey(string transactionId) => $"{transactionId}_audit";
        public ApplicationAuditEntry() : base()
        {
        }

        public string Id { get; set; }
        public AuditType AuditType { get; set; }
        public string CreatedBy { get; set; }
        public string TableName { get; set; }
        public string KeyValues { get; set; }
        public string OldValues { get; set; }
        public string NewValues { get; set; }
        public string ChangedColumns { get; set; }
        public bool Confirmed { get; set; }
        public string OldConcurrencyToken { get; set; }
    }

        public async IAsyncEnumerable<ApplicationAuditEntry> GetTransactionAsync(string transactionId)
        {
            string partitionKey = ApplicationAuditEntry.CreatePartitionKey(transactionId);
            var entries = await AuditEntries.Where(entry => entry.PartitionKey == partitionKey)
                .ToArrayAsync();

            foreach (var entry in entries)
            {
                await Entry(entry).ReloadAsync();
                yield return entry;
            }
        }

       public async Task AddTransactionIfNotExistsAsync(AuditTransactionEntry entry)
        {
            var existingEntry = await FindTransactionEntryAsync(entry);
            if (existingEntry == null)
            {
                this.AuditTransactions.Add(entry);
            }
        }

        private async Task<AuditTransactionEntry> FindTransactionEntryAsync(AuditTransactionEntry entry)
        {
            try
            {
                return await this.AuditTransactions.FindAsync(AuditTransactionEntry.CreateKey(entry.Id));
            }
            catch (CosmosException ex) when (ex.StatusCode == System.Net.HttpStatusCode.NotFound)
            {
                return null;
            }
        }
        
        //The ApplicationAuditEntry does have a base class that I removed but from the posted model, in this configuration you can see the some of the  base properties, but they should work as most of the stuffs on the application is working including the base configurations.
        /*
           public abstract class ConfigurationBase<T, TKey> : ConfigurationBase<T> where T : class, IBaseEntity<TKey>
    {
        public override void Configure(EntityTypeBuilder<T> builder)
        {
            builder.HasKey(e => new { e.PartitionKey, e.Id });
            base.Configure(builder);
        }
    }

    public abstract class ConfigurationBase<T> : IEntityTypeConfiguration<T> where T : class, IBaseEntity
    {
        public virtual void Configure(EntityTypeBuilder<T> builder)
        {
            builder.Property(e => e.ETag).IsETagConcurrency();
            builder.HasPartitionKey(e => e.PartitionKey);
            builder.Property(e => e.Updated)
                .HasConversion(UnixDateTimeConverter.Converter)
                .ToJsonProperty("_ts");
            builder.Property(e => e.TimeToLive)
                .ToJsonProperty("_ttl");
        }
    }
    */
    
```
   Here is part of the code.
   
   I have two DBContexts, AppDbContext and AuditDbContext.
   
   The contexts are very simple, no custom configuration on the connection.

Add some new ApplicationAuditEntry to the db set and then save the changes.
I think that you can just add some random entries with the Property `Confirmed` to false.
What I did is that I loop the changetracking from the AppDbContext and set the entries with Confirmed to false.
Then when the AppDbContext is saved I have to fetch the entries again using the GetTransactionAsync and save it with Confirmed to true. I do a reload here because I need the new ETag.

AuditEntries is the DBSet.

Sorry for not providing better source code but I don't have time right now to get a working solution.

**Comment by XzaR90** [comment]
I made a working example, I tested on a Azure with a Linux App Service, free tier and same issue.
Serverless cosmo database.

```C#
using Microsoft.EntityFrameworkCore;

    public class TestEntry
    {
        public static string CreatePartitionKey(string transactionId) => $"{transactionId}_test";
        public TestEntry() : base()
        {
            Id = Guid.NewGuid().ToString();
        }

        public string Id { get; set; }
        public string PartitionKey { get; set; }
        public string ETag { get; set; }
        public string CreatedBy { get; set; }
        public string TableName { get; set; }
        public string KeyValues { get; set; }
        public string OldValues { get; set; }
        public string NewValues { get; set; }
        public string ChangedColumns { get; set; }
        public bool Confirmed { get; set; }
        public string OldConcurrencyToken { get; set; }
    }

    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
        {
        }

        public DbSet<TestEntry> TestEntries { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var testEntryBuilder = modelBuilder.Entity<TestEntry>();
            testEntryBuilder.HasKey(e => new { e.PartitionKey, e.Id });
            testEntryBuilder.Property(e => e.ETag).IsETagConcurrency();
            testEntryBuilder.HasPartitionKey(e => e.PartitionKey);
        }
    }

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddApplicationInsightsTelemetry();
builder.Services.AddDbContext<AppDbContext>(opt =>
{
    opt.UseCosmos(builder.Configuration.GetConnectionString("DefaultConnection"), "WebTests");
});

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}

app.UseSwagger();
app.MapGet("/", context =>
{
    context.Response.Redirect("./swagger/index.html", permanent: false);
    return Task.FromResult(0);
});

app.MapGet("/hello", () => "Hello World!");

app.MapGet("/test", async (HttpContext context, AppDbContext db) =>
{
    await db.Database.EnsureCreatedAsync();
    var currentTime = DateTime.UtcNow.ToString("o");
    for (int i = 0; i < 10; i++)
    {
        db.Add(new TestEntry() { PartitionKey = TestEntry.CreatePartitionKey(currentTime) });
    }

    await db.SaveChangesAsync();

    async IAsyncEnumerable<TestEntry> GetTransactionAsync(string currentTime)
    {
        string partitionKey = TestEntry.CreatePartitionKey(currentTime);
        var entries = await db.TestEntries.Where(entry => entry.PartitionKey == partitionKey)
            .ToArrayAsync();

        foreach (var entry in entries)
        {
            await db.Entry(entry).ReloadAsync();
            yield return entry;
        }
    }

    await foreach (var item in GetTransactionAsync(currentTime))
    {
        item.Confirmed = true;
    }

    await db.SaveChangesAsync();

    return "Tested!";
});

app.UseSwaggerUI();
await app.RunAsync();

```

`
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.19.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Cosmos" Version="6.0.0" />
  </ItemGroup>
`

**Comment by XzaR90** [comment]
@ajcvickers and @AndriySvyryd Could you reproduce the bug?

**Comment by AndriySvyryd** [comment]
I get `System.Net.Http.HttpRequestException: Connection refused (localhost:8081)`  when I try this on WSL2

@roji Can you try this locally on Linux? This might be an issue in Microsoft.Azure.Cosmos 3.21.0

**Comment by AndriySvyryd** [comment]
Filed https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2879
