### ISSUE TITLE
Why is EFCore6 throwing NullReferenceException when adding entity/entities? It is working in EFCore5. 

### ISSUE THREAD

**Issue by frankfajardo** [dotnet/efcore#26644]
## Question: What is causing the NullReferenceException?

We have an active project which was started on ASP.NET 5 and EFCore 5.0. I'm investigating the move/migration to ASP.NET 6 and EFCore 6.0. The move to ASP.NET 6 (with EFCore 5.0) appears to be okay; the app is building and our tests are all passing still. But the move to EFCore 6.0 seems to be more challenging. II understand there are breaking changes between EFCore 5 and EFCore 6. However, I'm encountering this runtime error which I could not figure out the cause of. If only it gives me more info.

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.InitialFixup(InternalEntityEntry entry, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.StateChanged(InternalEntityEntry entry, EntityState oldState, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.StateChanged(InternalEntityEntry entry, EntityState oldState, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.FireStateChanged(EntityState oldState)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.SetEntityStates(IEnumerable`1 entities, EntityState entityState)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.AddRange(IEnumerable`1 entities)
   at XXX.Application.UnitTests.Products.ListProductsUnitTests.<ListProducts_GivenMultipleSimulatorFilters_ShouldReturnProductsWithAnyOfTheSimulators>d__18.MoveNext() in C:\Users\...\XXX.Application.UnitTests\Products\ListProductsUnitTests.cs:line 279
```

It is failing at this:

```
dbContext.Products.AddRange(products); // dbContext is a in-memory db
```

The entity model `Product` is this:

```
    public class Product : AuditableEntity
    {
        public Guid OrganizationId { get; set; }

        public Organization? Organization { get; set; }

        public Guid ProductFamilyId { get; set; }

        public ProductFamily? ProductFamily { get; set; }

        public string Name { get; set; } = null!;

        public string Slug { get; set; } = null!;

        public string? Description { get; set; }

        public ProductType Type { get; set; }

        public bool IsSubscription { get; set; }

        public ICollection<Discount> Discounts { get; set; } = new List<Discount>();

        public ICollection<Bundle> Bundles { get; set; } = new List<Bundle>();

        public ICollection<Price> Prices { get; set; } = new List<Price>();

        public ICollection<Tag> Tags { get; set; } = new List<Tag>();

        public ICollection<Tag> Simulators { get; set; } = new List<Tag>();

        public ICollection<ProductAccess>? ProductAccesses { get; set; }

        public ICollection<Component>? Components { get; set; }
    }
```

Running the test in debug mode, the data being saved has this (minimal) test data:
![image](https://user-images.githubusercontent.com/13171352/141414557-ad5c07f5-6b54-4146-8cd8-87a3b039e67b.png)

What is causing the NullReferenceException?
I already tried to assign values to all nullable properties of the `Product` entity but it still complains. 
I was only running one specific test so I don't think a shared dbContext is an issue. Besides, the unit test class creates its own instance of the dbContext.

The same test runs without failure on EFCore 5. 

I have re-generated our migration scripts using the `dotnet-ef 6.0.0` but I get same results.

EF Core version: 6.0
Database provider: InMemory, Postgresql
Target framework:  .NET 6.0
Operating system: Windows 11
IDE: Visual Studio 2022

**Comment by ajcvickers** [comment]
@frankfajardo Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by frankfajardo** [comment]
Hi @ajcvickers , I will close this issue. We have multiple relationships between our two entities (Product and Tag entities) similar to [this SO question](https://stackoverflow.com/questions/66865640/multiple-relations-between-entities-in-ef-core) which was okay with EFCore5 but not with EFCore6.. So we have added configuration in our `OnModelCreating()`.  We can live with that.

**Comment by PeterVanVogelpoel** [comment]
Hi, I have something simular. I had no issues in NET5. After upgrading to NET6 with no further changes in the entities and the DBContext I'm getting errors when updating ( _context.Attach(right).State = EntityState.Modified;) one specific entity. I will paste down here the error and the entity and the relevant piece from the DBcontext. Could somebody advise?

The error:
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: System.ArgumentNullException: Value cannot be null. (Parameter 'key')
         at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityReferenceMap.TryGet(Object entity, IEntityType entityType, InternalEntityEntry& entry, Boolean throwOnNonUniqueness)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.TryGetEntry(Object entity, IEntityType entityType, Boolean throwOnTypeMismatch)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.InitialFixup(InternalEntityEntry entry, Boolean fromQuery)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.StateChanged(InternalEntityEntry entry, EntityState oldState, Boolean fromQuery)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.StateChanged(InternalEntityEntry entry, EntityState oldState, Boolean fromQuery)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.FireStateChanged(EntityState oldState)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
         at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
         at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
         at Microsoft.EntityFrameworkCore.DbContext.Attach[TEntity](TEntity entity)
         at Filmbooking.Server.Controllers.RightsController.Put(Right right) in C:\Users\peter\OneDrive\Documenten\Filmgenie\Code\Current\Filmbooking211125NET6test\Filmbooking\Server\Controllers\RightsController.cs:line 773
         at lambda_method4452(Closure , Object )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0

The entity:
public partial class Right
    {
        public Right()
        {
            Booking = new HashSet<Booking>();
        }

        public Guid Rightid { get; set; }
        public int Territoryid { get; set; }
        public int Filmglobalid { get; set; }
        public DateTime Datestart { get { return DateTime.Parse(DatestartString); } }
        public DateTime Dateend { get { return DateTime.Parse(DateendString); } }
        public string DatestartString { get; set; }
        public string DateendString { get; set; }
        public Guid Rightownerid { get; set; }
        public decimal? Filmbookingrevenueshare { get; set; }
        public int? Stage { get; set; }
        public string Titlelocal { get; set; }
        public string Synopsisshortlocal { get; set; }
        public string Synopsislonglocal { get; set; }
        public int? Runningminuteslocal { get; set; }
        public string Trailerlocal { get; set; }
        public string Posterlocal { get; set; }
        public string Languagespokenlocal { get; set; }
        public string Languagesubtitleslocal { get; set; }
        public string Quoteslocal { get; set; }
        public Guid Licensorid { get; set; }
        public bool Allowaccesstolicensor { get; set; }
        public bool Sublicensed { get; set; }
        public Guid Licenseeid { get; set; }
        public DateTime ChangedDateTime { get; set; }
        public DateTime CreatedDateTime { get; set; }


        public virtual Filmglobal Filmglobal { get; set; }
        public virtual Rightowner Rightowner { get; set; }
        public virtual Territory Territory { get; set; }

        public virtual ICollection<Booking> Booking { get; set; }
    }

DBContext:
modelBuilder.Entity<Right>(entity =>
            {
                entity.ToTable("right");
                entity.Property(e => e.Rightid).HasColumnName("rightid");
                entity.Property(e => e.DatestartString).HasColumnName("datestartstring");
                entity.Property(e => e.DateendString).HasColumnName("dateendstring");
                entity.Property(e => e.Filmglobalid).HasColumnName("filmglobalid");
                entity.Property(e => e.Rightownerid).HasColumnName("rightownerid");
                entity.Property(e => e.Filmbookingrevenueshare).HasColumnName("filmbookingrevenueshare");
                entity.Property(e => e.Territoryid).HasColumnName("territoryid");
                entity.Property(e => e.Stage).HasColumnName("stage");
                entity.Property(e => e.Titlelocal).HasColumnName("titlelocal");
                entity.Property(e => e.Synopsisshortlocal).HasColumnName("synopsisshortlocal");
                entity.Property(e => e.Synopsislonglocal).HasColumnName("synopsislonglocal");
                entity.Property(e => e.Runningminuteslocal).HasColumnName("runningminuteslocal");
                entity.Property(e => e.Trailerlocal).HasColumnName("trailerlocal");
                entity.Property(e => e.Posterlocal).HasColumnName("posterlocal");
                entity.Property(e => e.Languagespokenlocal).HasColumnName("languagespokenlocal");
                entity.Property(e => e.Languagesubtitleslocal).HasColumnName("languagesubtitleslocal");
                entity.Property(e => e.Quoteslocal).HasColumnName("quoteslocal");
                entity.Property(e => e.Licensorid).HasColumnName("licensorid");
                entity.Property(e => e.Allowaccesstolicensor).HasColumnName("allowaccesstolicensor");
                entity.Property(e => e.Sublicensed).HasColumnName("sublicensed");
                entity.Property(e => e.Licenseeid).HasColumnName("licenseeid");
                entity.Property(e => e.ChangedDateTime).HasColumnName("changeddatetime");
                entity.Property(e => e.CreatedDateTime).HasColumnName("createddatetime");

                entity.HasOne(d => d.Filmglobal)
                    .WithMany(p => p.Right)
                    .HasForeignKey(d => d.Filmglobalid)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_right_filmglobal");

                entity.HasOne(d => d.Rightowner)
                    .WithMany(p => p.Right)
                    .HasForeignKey(d => d.Rightownerid)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_right_rightowner");

                entity.HasOne(d => d.Territory)
                    .WithMany(p => p.Right)
                    .HasForeignKey(d => d.Territoryid)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_right_territory");
            });
