### ISSUE TITLE
Migrations bundle: connection string is null

### ISSUE THREAD

**Issue by marcusturewicz** [dotnet/efcore#26664]
## Issue

When running the bundle executable, I am getting the following error:

```
System.ArgumentNullException: Value cannot be null. (Parameter 'connectionString')
```

which can be seen here:

https://github.com/GigLocal/gig-local-backend/runs/4197150115?check_suite_focus=true

### Include your code

I'm running the following command:

```
./publish-artifacts/migrations/bundle --connection "Server=tcp:sqlservergiglocaldevtophd3322gdmu.database.windows.net,1433;Initial Catalog=GigLocal;Persist Security Info=False;User ID=***;***;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;" -v
```

The bundle was created with:

```
dotnet ef migrations bundle --configuration Release -p src -o publish-artifacts/migrations/bundle --self-contained --no-build
```

### Include stack traces

```
System.ArgumentNullException: Value cannot be null. (Parameter 'connectionString')
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotEmpty(String value, String parameterName)
   at Microsoft.EntityFrameworkCore.SqlServerDbContextOptionsExtensions.UseSqlServer(DbContextOptionsBuilder optionsBuilder, String connectionString, Action`1 sqlServerOptionsAction)
   at Program.<>c__DisplayClass0_0.<<Main>$>b__1(DbContextOptionsBuilder options)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass1_0`2.<AddDbContext>b__0(IServiceProvider p, DbContextOptionsBuilder b)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass17_0`1.<AddCoreServices>b__0(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__17`1.<AddCoreServices>b__17_1(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextTypes()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextType(String name)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsBundle.ExecuteInternal(String[] args)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsBundle.<>c__DisplayClass6_0.<Configure>b__0(String[] args)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsBundle.Execute(String context, Assembly assembly, Assembly startupAssembly, String[] args)
```

### Include verbose output

```
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'GigLocal'...
Finding Microsoft.Extensions.Hosting service provider...
Using environment 'Development'.
Using application service provider from Microsoft.Extensions.Hosting.
```

### Include provider and version information

EF Core version: 6.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Ubuntu, GitHub Actions

**Comment by marcusturewicz** [comment]
I've got this working now, https://github.com/GigLocal/gig-local-backend/commit/4d778cdf64e24f8f094f56d79a318b85fda46710

It seems the issue was possibly two fold:
- The bundle couldn't see appsettings.json, so I moved it to the app publish directory
- I was running the bundle from outside its directory

Additionally, I also had an error as the bundle didn't have execution permissions on GitHub Actions runner, so I needed to:

```
chmod +x bundle
```

If true, maybe the documentation could be updated to mention these things.

**Comment by bricelam** [comment]
> the bundle didn't have execution permissions

Shouldn't `dotnet publish` be taking care of that?

Maybe it gets removed when the file is moved...

https://github.com/dotnet/efcore/blob/0cb702834e120e3b750ae343ed92fb6380eeecab/src/ef/Commands/MigrationsBundleCommand.cs#L202-L204

**Comment by m-x-shokhzod** [comment]
Did some empirical investigation today. On the .NET 9 SDK Linux container (arm64), I could not reproduce the missing executable bit in any of the scenarios that mirror what `MigrationsBundleCommand.Execute` does:

| `dotnet publish` args | output mode | after `File.Move` |
|---|---|---|
| `--runtime linux-arm64 --self-contained --output /tmp/publish` | `755`, exec ✅ | `755`, exec ✅ |
| same + `/p:PublishSingleFile=true` | `755`, exec ✅ | `755`, exec ✅ |
| `--runtime linux-arm64 --no-self-contained --output /tmp/publish` | `755`, exec ✅ | `755`, exec ✅ |
| `--self-contained /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true` | `755`, exec ✅ | `755`, exec ✅ |

I also wrote a focused diagnostic that exercises only `File.Move` on Linux:

```csharp
File.WriteAllText(src, "...");
File.SetUnixFileMode(src, /* rwxr-xr-x */);
File.Move(src, dst);
// File.GetUnixFileMode(dst) == File.GetUnixFileMode(src)  ← preserved
```

`File.Move` preserves the Unix file mode reliably on .NET 9 Linux.

The original report was running on a GitHub Actions runner, and the OP's follow-up (`chmod +x bundle` was needed) is consistent with GHA artifact upload/download stripping Unix permissions, rather than `MigrationsBundleCommand` itself producing a non-executable bundle. Looking at @bricelam's [2025-07-19 comment](https://github.com/dotnet/efcore/issues/26664#issuecomment-3088895912), I started out trying to add a `File.SetUnixFileMode` call after the `File.Move`, but my verification doesn't show a missing bit anywhere in the path — so the fix would have been a no-op on current .NET.

If anyone has a current repro on a recent .NET version, happy to dig further. Otherwise this might be a candidate to close as outdated, or to narrow the scope to "make the bundle command robust against environments that strip permissions" (which would be a defensive `chmod +x` after the move, with a clear comment that it's a guard, not a fix to a current EF Core bug).
