### ISSUE TITLE
Cannot add new migrations in .NET 6 EF Core

### ISSUE THREAD

**Issue by hellfirehd** [dotnet/efcore#26673]
I've been upgrading .NET 5 to .NET 6. After upgrading all package to the latest 6.0.0 versions, I can no longer add new migrations.

The following worked fine in .NET 5:
```powershell
dotnet ef migrations add Test_Migration --project C:\Source\CPCAv4\source\CPCA.Infrastructure.SqlServer\CPCA.Infrastructure.SqlServer.csproj --context ApplicationDbContext --output-dir Infrastructure\SqlServer\Application --verbose
```

This is the exception being produced when running the above command:

```log
Build started...
dotnet build C:\Source\CPCAv4\source\CPCA.Infrastructure.SqlServer\CPCA.Infrastructure.SqlServer.csproj /verbosity:quiet /nologo
/snip/
Build succeeded.
dotnet exec --depsfile C:\Source\CPCAv4\source\CPCA.Infrastructure.SqlServer\bin\Debug\net6.0\CPCA.Infrastructure.SqlServer.deps.json --additionalprobingpath C:\Users\dougw\.nuget\packages --runtimeconfig C:\Source\CPCAv4\source\CPCA.Infrastructure.SqlServer\bin\Debug\net6.0\CPCA.Infrastructure.SqlServer.runtimeconfig.json C:\Users\dougw\.dotnet\tools\.store\dotnet-ef\6.0.0\dotnet-ef\6.0.0\tools\netcoreapp3.1\any\tools\netcoreapp2.0\any\ef.dll migrations add Just_Checking --context ApplicationDbContext --output-dir Infrastructure\SqlServer\Application --assembly C:\Source\CPCAv4\source\CPCA.Infrastructure.SqlServer\bin\Debug\net6.0\CPCA.Infrastructure.SqlServer.dll --project C:\Source\CPCAv4\source\CPCA.Infrastructure.SqlServer\CPCA.Infrastructure.SqlServer.csproj --startup-assembly C:\Source\CPCAv4\source\CPCA.Infrastructure.SqlServer\bin\Debug\net6.0\CPCA.Infrastructure.SqlServer.dll --startup-project C:\Source\CPCAv4\source\CPCA.Infrastructure.SqlServer\CPCA.Infrastructure.SqlServer.csproj --project-dir C:\Source\CPCAv4\source\CPCA.Infrastructure.SqlServer\ --root-namespace CPCA --language C# --framework net6.0 --nullable --working-dir C:\Source\CPCAv4 --verbose
Using assembly 'CPCA.Infrastructure.SqlServer'.
Using startup assembly 'CPCA.Infrastructure.SqlServer'.
Using application base 'C:\Source\CPCAv4\source\CPCA.Infrastructure.SqlServer\bin\Debug\net6.0'.
Using working directory 'C:\Source\CPCAv4\source\CPCA.Infrastructure.SqlServer'.
Using root namespace 'CPCA'.
Using project directory 'C:\Source\CPCAv4\source\CPCA.Infrastructure.SqlServer\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Found IDesignTimeDbContextFactory implementation 'SqlServerApplicationDbContextFactory'.
Found DbContext 'ApplicationDbContext'.
Finding application service provider in assembly 'CPCA.Infrastructure.SqlServer'...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Using DbContext factory 'SqlServerApplicationDbContextFactory'.
Using context 'ApplicationDbContext'.
Finding design-time services referenced by assembly 'CPCA.Infrastructure.SqlServer'...
Finding design-time services referenced by assembly 'CPCA.Infrastructure.SqlServer'...
No referenced design-time services were found.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding IDesignTimeServices implementations in assembly 'CPCA.Infrastructure.SqlServer'...
No design-time services were found.
'ApplicationDbContext' disposed.
System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.Nullable`1[Microsoft.EntityFrameworkCore.Metadata.SqlServerValueGenerationStrategy]'.
   at Microsoft.EntityFrameworkCore.SqlServerPropertyExtensions.GetValueGenerationStrategy(IReadOnlyProperty property, StoreObjectIdentifier& storeObject, ITypeMappingSource typeMappingSource)
   at Microsoft.EntityFrameworkCore.SqlServerPropertyExtensions.GetValueGenerationStrategy(IReadOnlyProperty property, StoreObjectIdentifier& storeObject)
   at Microsoft.EntityFrameworkCore.SqlServer.Metadata.Internal.SqlServerAnnotationProvider.<>c__DisplayClass5_0.<For>b__2(IProperty p)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.EntityFrameworkCore.SqlServer.Metadata.Internal.SqlServerAnnotationProvider.For(IColumn column, Boolean designTime)+MoveNext()
   at Microsoft.EntityFrameworkCore.Infrastructure.AnnotatableBase.AddAnnotations(AnnotatableBase annotatable, IEnumerable`1 annotations)
   at Microsoft.EntityFrameworkCore.Infrastructure.AnnotatableBase.AddAnnotations(IEnumerable`1 annotations)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalModel.Create(IModel model, IRelationalAnnotationProvider relationalAnnotationProvider, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalModel.Add(IModel model, IRelationalAnnotationProvider relationalAnnotationProvider, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelRuntimeInitializer.InitializeModel(IModel model, Boolean designTime, Boolean prevalidation)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to cast object of type 'System.Int32' to type 'System.Nullable`1[Microsoft.EntityFrameworkCore.Metadata.SqlServerValueGenerationStrategy]'.
```

### Provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer 6.0.0
Target framework: NET6.0
Operating system: Windows 10 Pro 21H1
IDE: Microsoft Visual Studio Professional 2022 (64-bit) - Current Version 17.0.0

**Comment by roji** [comment]
@hellfirehd any chance you can provider a code sample for before the migration, and the changes you made before attempting to add the migration (if that's important)? Some sort of repro/code sample would be helpful in order to investigate this.

**Comment by hellfirehd** [comment]
@roji Sent you an invite.

**Comment by Larsico** [comment]
i´m in the same situation

**Comment by roji** [comment]
@hellfirehd I've accepted your invitation, but the repo contains a lots of projects and it is unclear how to reproduce this. Could you please provide step-by-step instructions of what needs to be done after a clean clone of the repo in order to reach the exception?

@Larsico if you could do the same that would be helpful - I need to see the error occurring in order to investigate it.

**Comment by hellfirehd** [comment]
@roji I've overwritten the NET6 branch with a new one. You can ignore everything else.

The following steps repro the issue.

```powershell
git clone https://github.com/hellfirehd/repro_efcore_26673.git
cd .\repro_efcore_26673\
git checkout 4f05d3
.\tools\add-migrations.ps1 Test_Migration
```

The above should have succeeded and produced an empty migration.

```powershell
git reset --hard && git clean -f -d
git checkout 128367
.\tools\add-migrations.ps1 Test_Migration
```

That will have failed.

Those two commits are sequential. It should be easy to see the differences which boil down to changing from .NET 5.0 package references to .NET 6.0 package references.

**Comment by hellfirehd** [comment]
I'm wondering if it has something to do with this:

```csharp
...
  modelBuilder.Entity("HostedWasmApp.Model.AuditEntry", b =>
  {
    b.Property<int>("Id")
        .ValueGeneratedOnAdd()
        .HasColumnType("int");

    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

    b.Property<int>("Action")
        .HasColumnType("int");
...
```

None of the NET5.0 migrations have the `SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);` line.

I get that we're 40 days from 2022, so why am I still using Int32 as IDs?  Two Words: Legacy Database.  It started out as an Access database around ~2009 and has been brought kicking and screaming to SQL Server. I'm lucky I was able to use EF Core Migrations at all!

**Comment by roji** [comment]
@hellfirehd your DbYear.cs file contains an `EntityConfiguration<DbYear>` with the following:

```c#
entity.Property(e => e.Id).HasColumnName("Year")
    .HasAnnotation("SqlServer:Identity", $"{CpcaConsts.YearMin}, 1")
    .HasAnnotation("SqlServer:ValueGenerationStrategy", /*SqlServerValueGenerationStrategy.IdentityColumn*/ 2)
    .IsRequired(true);
```

I'm guessing this was maybe done in order to avoid taking a reference on Microsoft.EntityFramework.SqlServer in the project, but this is not supported - SqlServer:ValueGenerationStrategy must contains the proper enum, and not an int value:

```c#
entity.Property(e => e.Id)
    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)
```

Note that there are various migration files in under CPCA.Infrastructure.SqlServer/Infrastructure/SqlServer/Application that have the "2" value baked in. You're going to have to search-and-replace from `.HasAnnotation("SqlServer:ValueGenerationStrategy", 2)` to `.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn))`.

This happened to work in 5.0, and intentional changes for 6.0 made this start failing.

**Comment by hellfirehd** [comment]
That solved it. Thank you so much!

**Comment by roji** [comment]
@hellfirehd one last note - using HasAnnotation directly as above is generally not the right way to do things: EF Core has dedicated APIs for configuring what you want. HasAnnotation is a low-level API that isn't meant to be used by users, and even after the fix above it may theoretically fail in some way.

Here's the above using the Fluent API, which is the recommended way:

```c#
entity.Property(e => e.Id)
    .HasColumnName("Year")
    .UseIdentityColumn(seed: CpcaConsts.YearMin, increment: 10);
    .IsRequired(true);
```

(or similar). It's a good idea to follow [the documentation on this stuff](https://docs.microsoft.com/en-us/ef/core/providers/sql-server/value-generation).
