### ISSUE TITLE
Error in dotnet ef migrations add IdentityMigrations

### ISSUE THREAD

**Issue by rgbetanco** [dotnet/efcore#26681]
I am getting the following issue
```bash
➜  NombreDelProyecto git:(master) ✗ dotnet ef migrations add IdentityMigrations
Build started...
Build succeeded.
An error occurred while accessing the Microsoft.Extensions.Hosting services. Continuing without the application service provider. Error: Could not load type 'System.Runtime.CompilerServices.DefaultInterpolatedStringHandler' from assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
System.TypeInitializationException: The type initializer for 'System.SharedTypeExtensions' threw an exception.
 ---> System.TypeLoadException: Could not load type 'System.DateOnly' from assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   --- End of inner exception stack trace ---
   at System.SharedTypeExtensions.ProcessType(StringBuilder builder, Type type, Boolean fullName, Boolean compilable)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextTypes()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextType(String name)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The type initializer for 'System.SharedTypeExtensions' threw an exception.
```
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="4.1.1-dev-00229" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.1-dev-00947" />
  </ItemGroup>

</Project>
```

My DbContext class looks as follow:
```csharp
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using NombreDelProyecto.Models;
using Microsoft.AspNetCore.DataProtection;

namespace NombreDelProyecto.Data
{
    public class DataContext: IdentityDbContext
    {
        private readonly IDataProtector _protector;
        public DataContext(DbContextOptions<DataContext> options, IDataProtectionProvider provider) : base(options){
            _protector = provider.CreateProtector("Protect.Email");
        }
        public virtual DbSet<ContactUsModel> ContactUs { get; set; }
        protected override void OnModelCreating(ModelBuilder modelBuilder){
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<ContactUsModel>()
            .HasData(new ContactUsModel
                {
                    Name = "Robert Deniro",
                    Email = _protector.Protect("robert@gmail.com"),
                    Phone = "0909090909"
                },
                new ContactUsModel {
                    Name = "Maria Smith",
                    Email = _protector.Protect("msmith@hotmail.com"),
                    Phone = "0808080808"
                }
            );
        }
    }
}
```
My current SDK and runtime versions are 
```bash
6.0.100-preview.3.21202.5 [/usr/local/share/dotnet/sdk]
```
```bash
Microsoft.NETCore.App 6.0.0-preview.3.21201.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by ajcvickers** [comment]
@rgbetanco Looks like you are using preview 3 or .NET 6.0 and the SDK. Please install the final (GA) release of the SDK and report back if you are still seeing this issue.

**Comment by rgbetanco** [comment]
@ajcvickers It worked, all I did was install the .net 6.0. Thanks
