### ISSUE TITLE
Scaffold-DbContext incorrectly maps a view column that is of type (datetime2(7), null) to C# DateTime instead of DateTime?

### ISSUE THREAD

**Issue by awhig** [dotnet/efcore#26727]
Using EF Core version 5.0.12

The generated View class contains a field mapped from the DB as a non-nullable DateTime object. The DB allows NULL.  

We  got the exceptions below when we return a set of rows from the view.

I believe the bug is in the interpreting the view columns. The View returns columns that another entity contains, and in that entity class that was generated, it properly mapped the column to a  DateTime? type.

I was using 5.0.11 of EF Core when we hit this snag. I updated to 5.0.12 to see if this would fix it, but the same mapping occurred when I regenerated the classes.

Is there any workaround, besides manually changing the datatype every time we regen the classes?

Thanks,
Rich

`Microsoft.EntityFrameworkCore.Query: Error: An exception occurred while iterating over the results of a query for context type 'LogisticsBOL.Models.mlogisticsdContext'.
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
at Microsoft.Data.SqlClient.SqlBuffer.get_DateTime()
at Microsoft.Data.SqlClient.SqlDataReader.GetDateTime(Int32 i)
at lambda_method351(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()

System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
at Microsoft.Data.SqlClient.SqlBuffer.get_DateTime()
at Microsoft.Data.SqlClient.SqlDataReader.GetDateTime(Int32 i)
at lambda_method351(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
Exception thrown: 'System.Data.SqlTypes.SqlNullValueException' in Microsoft.EntityFrameworkCore.Relational.dll`

**Comment by ErikEJ** [comment]
A repro with the CREATE statements for the table and view would be helpful

**Comment by awhig** [comment]
During our investigation of this issue, we ended up switching the view column, to a different one that happens to be a datetime field that is not null. The issue then was sidestepped.

I tried creating a simplified version of the table and view, and could not reproduce the bug with the 5.0.12 generator. Please close this bug.
