### ISSUE TITLE
TypeLoadException on Update-Database with EFCore 6.0.0

### ISSUE THREAD

**Issue by AshleyMedway** [dotnet/efcore#26749]
System.TypeLoadException occurs running update database after updating to 6.0.0 was fine in 5.0.0

Unfortunately I haven't been able to reproduce this outside of our applications.

### Include your code

Cannot reproduce in a minimal example using a console app but this error happens on all our .net 6 apis

### Include verbose output

```
PM> Update-Database -Verbose
Using project 'Data\Inspections.Data'.
Using startup project 'Web\Inspections.Web.InternalApi'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile C:\Dev\project\Inspections\Inspections.Web.InternalApi\bin\Debug\net6.0\win-x64\Inspections.Web.InternalApi.deps.json --additionalprobingpath C:\Users\ashley.medway\.nuget\packages --additionalprobingpath "C:\Program Files (x86)\DevExpress 21.1\Components\Offline Packages" --additionalprobingpath "C:\Program Files (x86)\DevExpress 21.2\Components\Offline Packages" --runtimeconfig C:\Dev\project\Inspections\Inspections.Web.InternalApi\bin\Debug\net6.0\win-x64\Inspections.Web.InternalApi.runtimeconfig.json C:\Users\ashley.medway\.nuget\packages\microsoft.entityframeworkcore.tools\6.0.0\tools\netcoreapp2.0\any\ef.dll database update --verbose --no-color --prefix-output --assembly C:\Dev\project\Inspections\Inspections.Web.InternalApi\bin\Debug\net6.0\win-x64\Inspections.Data.dll --project C:\Dev\project\Inspections\Inspections.Data\Inspections.Data.csproj --startup-assembly C:\Dev\project\Inspections\Inspections.Web.InternalApi\bin\Debug\net6.0\win-x64\Inspections.Web.InternalApi.dll --startup-project C:\Dev\project\Inspections\Inspections.Web.InternalApi\Inspections.Web.InternalApi.csproj --project-dir C:\Dev\project\Inspections\Inspections.Data\ --language C# --configuration Debug --working-dir C:\Dev\project\Inspections --root-namespace Inspections.Data
Using assembly 'Inspections.Data'.
Using startup assembly 'Inspections.Web.InternalApi'.
Using application base 'C:\Dev\project\Inspections\Inspections.Web.InternalApi\bin\Debug\net6.0\win-x64'.
Using working directory 'C:\Dev\project\Inspections\Inspections.Web.InternalApi'.
Using root namespace 'Inspections.Data'.
Using project directory 'C:\Dev\project\Inspections\Inspections.Data\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'Inspections.Web.InternalApi'...
Finding Microsoft.Extensions.Hosting service provider...
Using environment 'Development'.
Using application service provider from Microsoft.Extensions.Hosting.
Finding DbContext classes in the project...
Found DbContext 'InspectionsDbContext'.
Using DbContext factory 'InspectionsDbContextFactory'.
Using context 'InspectionsDbContext'.
'InspectionsDbContext' disposed.
System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Internal.DiagnosticsLogger`1' from assembly 'Microsoft.EntityFrameworkCore, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.EntityFrameworkCore.Design.DesignTimeServiceCollectionExtensions.AddEntityFrameworkDesignTimeServices(IServiceCollection services, IOperationReporter reporter, Func`1 applicationServiceProviderAccessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.Build(DbContext context)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Could not load type 'Microsoft.EntityFrameworkCore.Internal.DiagnosticsLogger`1' from assembly 'Microsoft.EntityFrameworkCore, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
```

### Include provider and version information

EF Core version: 6.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .net 6
Operating system: Windows 10
IDE: Visual Studio 2022 17.0.1

**Comment by ajcvickers** [comment]
@AshleyMedway Make everywhere the project is using the 6.0.0 version everywhere an EF package is referenced. This includes checking transitive dependencies brought in by other packages.

**Comment by AshleyMedway** [comment]
@ajcvickers Genius! 

AspNetCore.HealthChecks.UI was the culprit. There is no released .net 6 version. Updated to the pre-release 6.0.1-rc2.4 solved the issue.
