### ISSUE TITLE
Operations on IQueryable after GroupBy.Select

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [dotnet/efcore#26748]
I'm able to create distinct groupings no problem like:
`GroupBy(p=> p.MyField).Select(p=> p.First)`

I'm also able to Order the data:
`GroupBy(p=> p.MyField).Select(p=> p.First).OrderBy(p=> p.MyField)`

---

But if I try to Count:
`GroupBy(p=> p.MyField).Select(p=> p.First).Count()`

Or shape the return data:
`GroupBy(p=> p.MyField).Select(p=> p.First).Select(p=>p.MyField)` 

I get an error like:
```
System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ClientProjectionRemappingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ClientProjectionRemappingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ApplyProjection(Expression shaperExpression, ResultCardinality resultCardinality, QuerySplittingBehavior querySplittingBehavior)
   at Microsoft.EntityFrameworkCore.Query.Internal.SelectExpressionProjectionApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPostprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.CountAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)

```

I've seen the error come up in other threads related to Navigation properties, but for test case, the table has none.

Any help appreciated!

-----

EF Core 6
Microsoft.EntityFrameworkCore.SqlServer
.NET 6.0
Win 11
VS 22

**Comment by smitpatel** [comment]
Not a regression since grouping.First didn't work in previous release.
Queries with OrderBy/Select after grouping+Select throws client eval error for me since we couldn't translate `p=> p.MyField` Filed #26753 

Count is failing with exception like above.
Work-around would be do Count after grouping directly as the result will be the same.

**Comment by smitpatel** [comment]
Same issue exist for Any. (kind for All also)
None of this works if it contains a predicate (which All always has) it will run into #26753

**Comment by OpenSpacesAndPlaces** [comment]
@ajcvickers Any chance this could make it into the next minor release or is a big push needed to fix this?

**Comment by ajcvickers** [comment]
@OpenSpacesAndPlaces If by minor release you mean a 6.x minor release, then current plans are for no such releases before 7.0. If you mean a 6.0.x patch release, then we don't typically add new functionality in patch releases.

**Comment by OpenSpacesAndPlaces** [comment]
@ajcvickers Ok - I didn't realize there were no minors this cycle - I was reacting to the next major being 11/2022.

Well then, yeah, it's probably a stretch to say this would be in a patch only cycle since the features section doesn't talk about anonymous support.
https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/whatsnew#improved-groupby-support

Thanks for the dialog on this!

**Comment by SoftCircuits** [comment]
I have the same error.

So is there any workaround for code like this?

```cs
var query = DbContext.TripSegments
    .Where(ts => ts.RailcarTrip.WaybillRailcar.Waybill.CompanyCode == companyCode &&
        ts.IsLoaded && ts.EndDate == null &&
        ts.DestinationCity == city && ts.DestinationState == state);

query = query
    .GroupBy(ts => ts.RailcarTrip.WaybillRailcar.RailcarNumber)
    .Select(x => x.First());

int count = await query.CountAsync();
```

*Note 1: I realize I could pull the results to the client and filter them there. But aside from performance concerns, I'm implementing paging. If I request a page and then filter the results on the client side, that will mess up my pages.*

*Note 2: The count above is for paging. If I could get this code working, I was going to follow it up with a significant SELECT clause. I assume that will cause problems too?*

**Comment by SoftCircuits** [comment]
> If you can skip the projection into a new type at the end it should work. At least in our travels, projecting or layering too much over the group by will cause this.

Thanks, that didn't seem to be an option for me because the SELECT clause uses a lot of navigation properties to get the data I need.

However, I appear to have it working by actually doing the projection *before* the GROUPBY. And then grouping the results of that. To be honest, I was a little surprised this worked.

> Other thing I will note, unless you're paging results, there isn't going to be a huge difference for client siding most things unless your column and/or row count is massive.

Yes, especially in my case as there were very few duplicates. But removing anything on the client side would definitely mess up my paging.

**Comment by vlad-bil** [comment]
Other example (please see fiddle [https://dotnetfiddle.net/zBSsa1](https://dotnetfiddle.net/zBSsa1))

Pre condition:
entities are grouped by some field by GroupBy(...), then first item is taken from each group via Select(x => x.FirstOrDefault(...)).
The query itself may be compiled, but if we try to call Count it is failed

**Comment by wilari932** [comment]
My solution was to do it like this 
var result = await someQuery.GroupBy(p => p.Id).Select(x => x.Key).CountAsync();
it seems that is bad support for this specially when you are left joining data

**Comment by pvg8v6g** [comment]
I can confirm this is STILL an issue in .NET 6.

**Comment by neobenedict** [comment]
Please for the love of C# fix this already.

**Comment by dophuquan1998** [comment]
![image](https://github.com/dotnet/efcore/assets/42272508/f03e3914-7cd1-475d-96b0-e7464846ff0a)

I get the error: "cannot be translated"

**Comment by fl1k** [comment]
> ![image](https://private-user-images.githubusercontent.com/42272508/317669585-f03e3914-7cd1-475d-96b0-e7464846ff0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MTYxOTAsIm5iZiI6MTcxMTcxNTg5MCwicGF0aCI6Ii80MjI3MjUwOC8zMTc2Njk1ODUtZjAzZTM5MTQtN2NkMS00NzVkLTk2YjAtZTc0NjQ4NDZmZjBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDEyMzgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliNTU1OWM2OTFkMWRmY2NlOTA5OTg5YzNhMjk1YThjODQ1MGZjODQ1NjRjMjQyMWNkNWM4NzE2NWVlOWExZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L98fuB3YIB1DM0WfXA9bvPsqeU4Al66xUSOSEmJFe-g)
> 
> I get the error after executing the query : "cannot be translated .OrderByDescending after Group "

Same issue, Can't run .Select before .GroupBy

**Comment by Kebechet** [comment]
Doesn't work in .NET 8 as well. This is a very basic use case, please consider prioritizing it more.

**Comment by NiSHoW** [comment]
consider giving priority to all "ef-parity"...

**Comment by DushyantSinghChouhan** [comment]
Still getting this issue in .Net 8.0, with ef core 8.0.8.

System.InvalidOperationException: The LINQ expression 'DbSet()
.SelectMany(
collectionSelector: x => DbSetTableB()
.Where(y => (int?)y.Id == x.MatchId)
.DefaultIfEmpty(),
resultSelector: (a, b) => new {
entity = a,
vendor = b
})
.Select(x => new QueueDataModel{
QueueId = x.entity.Id,
QueueType = x.entity.Type,
Name = x.entity.Name,
Status = x.entity.Status,
TINLast4 = ContextExtensions.JsonValue(
expression: x.entity.EntityJson,
path: "$.TINLast4"),
MetaData = ContextExtensions.JsonQuery(
expression: x.entity.EntityJson,
path: "$.MetaData"),
PersonFlag = ContextExtensions.JsonValue(
expression: x.entity.EntityJson,
path: "$.PersonFlag"),
ClientContact = ContextExtensions.JsonQuery(
expression: x.entity.EntityJson,
path: "$.Contact"),
ClientLocation = ContextExtensions.JsonQuery(
expression: x.entity.EntityJson,
path: "$.Location"),
SelectedVendor = x.vendor != null ? new MatchedVendor{
Id = x.vendor.Id,
Name = x.vendor.Name
}
: null,
MatchesCount = x.entity.Matches
.AsQueryable()
.Join(
inner: DbSet(),
outerKeySelector: match => match.Id,
innerKeySelector: matchResult => matchResult.MatchId,
resultSelector: (match, matchResult) => matchResult.MatchId)
.Distinct()
.Count(),
MatchedVendors = x.entity.Matches
.AsQueryable()
.Join(
inner: DbSet(),
outerKeySelector: match => match.Id,
innerKeySelector: matchResult => matchResult.MatchId,
resultSelector: (match, matchResult) => new {
matchResult = matchResult,
MatchAlgorithmTypeEnum = match.MatchAlgorithmTypeEnum
})
.Join(
inner: DbSetTableB(),
outerKeySelector: result => result.matchResult.MatchId,
innerKeySelector: vendor => vendor.Id,
resultSelector: (result, vendor) => new MatchedVendor{
Id = vendor.Id,
Confidence = result.matchResult.Confidence,
Name = vendor.Name,
AlgorithmTypeEnum = result.MatchTypeEnum
}
)
.ToList(),
Client = x.entity.JobMatch.Client.Name,
Job = x.entity.JobMatch.Name,
JobId = x.entity.JobMatchId,
DateAdded = x.entity.CreatedUTC
}
)
.Where(item => item.Status == Review)
.OrderBy(item => item.Name)
.Skip(__p_0)
.Take(__p_1)
.GroupBy(item => item.Name)
.OrderBy(group51285273 => group51285273.Key)
.Select(group51285273 => new AggregateFunctionsGroup{
Key = group51285273.Key,
ItemCount = group51285273
.AsQueryable()
.Count(),
HasSubgroups = False,
Member = "Name",
Items = group51285273
}
)' could not be translated. Additional information: Translation of 'Select' which contains grouping parameter without composition is not supported. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

**Comment by roji** [comment]
Everyone, I hope we'll do a general push for improved GroupBy support for EF 10 - stay tuned.

**Comment by hima-Megahed** [comment]
In my case I had the exact same error: `InvalidOperationException: Nullable object must have value`

After around an hour of investigation I found out that I'm using Z.EntityFramework.Plus and applying some global filters which using null property which led to the error.

I enabled **DbContextOptionsBuilder.EnableSensitiveDataLogging** to help me troubleshooting the issue.

I hope it helps someone

**Comment by regisbsb** [comment]
For future me and others:
to work around this you need to join instead of group by:

```
var statementsQueryable = _dbContext.Statements.AsQueryable();

var latestVersions = _dbContext.Statements
    .GroupBy(e => e.Key)
    .Select(g => new
    {
        g.Key,
        Version = g.Max(e => e.Version)
    });

statementsQueryable = statementsQueryable
    .Join(latestVersions,
        statement => new { statement.Key, statement.Version },
        latest => latest,
        (statement, latest) => statement);
```
then you can do all operations without worry

**Comment by jnavarrete777** [comment]
Hi
When will you have a definitive solution? We need to work with groupings, and right now we simply cannot use the tool. These are priorities.

**Comment by roji** [comment]
@jnavarrete777 there were other higher priorities so this won't make it to EF 10, and I can't say when we'll tackle it. I suggest reading the above comments for possible workarounds.
