### ISSUE TITLE
Invalid operation exception while connecting database

### ISSUE THREAD

**Issue by Gopal-y5** [dotnet/efcore#26979]
## File a bug
When we are trying to connect to database we are observing Invalid operation exception. Its occurring only during more number of requests approximately 2.5K/minute are trying to get connect to database and fetch data. We've added stack trace of it below.
Remember:

### Include your code
Due to privacy constraints we cannot share code.

### Include stack traces

Include the full exception message and stack trace for any exception you encounter.

Use triple-tick fences for stack traces. 
```
Unhandled exception. System.InvalidOperationException: Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool. This may have occurred because all pooled connections were in use and max pool size was reached.
at Microsoft.Data.Common.ADP.ExceptionWithStackTrace(Exception e)
--- End of stack trace from previous location ---
at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```

### Include provider and version information

EF Core version: 5.0.9
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: 5.0
Operating system: Windows
IDE: Visual Studio 2019

**Comment by DirkBoer** [comment]
Hi @ajcvickers , is there a specific reason why this is not a specific Exception or is this planned to be fixed?

We need in our application to differentiate between transient errors that will resolve after a certain time and logic errors where you can expect InvalidOperationExceptions.

We had just a critical outage because an issue that seems that it should be transient is actually reusing a very generic Exception that we can't capture.

 Are you even sure this is tackled by connection EnableRetryOnFailure?

**Comment by ajcvickers** [comment]
@ajcvickers We're not planning to change anything here. If there is an issue you think we should address, then please open a new issue and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
