### ISSUE TITLE
EFCore 6 - Model is not getting validated when multiple columns have ValueGeneratedOnAdd()

### ISSUE THREAD

**Issue by shvmgpt116** [dotnet/efcore#27016]
I have a sample application which used to work with EFCore 5 sql server provider without any issue. But with EFCore 6.0.1, I am getting following exception when executing BeginTransaction().
"**System.InvalidOperationException**: 'The properties 'TErpInterface.Id', 'TErpInterface.InterfaceHeaderId' are configured to use 'Identity' value generation and are mapped to the same table 'T_ERP_INTERFACE', but only one column per table can be configured as 'Identity'. Call 'ValueGeneratedNever' in 'OnModelCreating' for properties that should not use 'Identity'."

### Here is the sample application

```C#
using System;
using Microsoft.EntityFrameworkCore;

namespace ConsoleApp76
{
  class Program
  {
    static void Main(string[] args)
    {
      Console.WriteLine("Hello World!");
      using (var db = new ModelContext())
      {
        var txn = db.Database.BeginTransaction();
      }
    }
  }

  public partial class TErpInterface
  {
    public decimal Id { get; set; }
    public decimal? InterfaceHeaderId { get; set; }
  }

  public partial class ModelContext : DbContext
  {
    public ModelContext()
    {
    }

    public ModelContext(DbContextOptions<ModelContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TErpInterface> TErpInterfaces { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      if (!optionsBuilder.IsConfigured)
      {
        optionsBuilder.UseSqlServer(<connection string>);
      }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
      modelBuilder.Entity<TErpInterface>(entity =>
      {
        entity.HasNoKey();

        entity.ToTable("T_ERP_INTERFACE");

        entity.Property(e => e.Id)
            .HasColumnName("ID").ValueGeneratedOnAdd();

        entity.Property(e => e.InterfaceHeaderId)
            .HasColumnName("INTERFACE_HEADER_ID").ValueGeneratedOnAdd();
      });

      OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
  }
}

```

### Include stack traces

```
System.InvalidOperationException
  HResult=0x80131509
  Message=The properties 'TErpInterface.Id', 'TErpInterface.InterfaceHeaderId' are configured to use 'Identity' value generation and are mapped to the same table 'T_ERP_INTERFACE', but only one column per table can be configured as 'Identity'. Call 'ValueGeneratedNever' in 'OnModelCreating' for properties that should not use 'Identity'.
  Source=Microsoft.EntityFrameworkCore.SqlServer
  StackTrace:
   at Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal.SqlServerModelValidator.ValidateSharedColumnsCompatibility(IReadOnlyList`1 mappedTypes, StoreObjectIdentifier& storeObject, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedTableCompatibility(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal.SqlServerModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_Dependencies()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.BeginTransaction()
   at ConsoleApp76.Program.Main(String[] args) in C:\Users\shivamg\source\repos\ConsoleApp77\ConsoleApp77\Program.cs:line 13
```
Please could someone tell me what has changed. Is this a regression or an expected behavior?

### Provider and version information

EF Core version: 6.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Visual Studio 2022 preview

**Comment by ajcvickers** [comment]
@shvmgpt116 This is by-design; SQL Server doesn't allow multiple columns to be marked as `IDENTITY`, which is the default when using `ValueGeneratedOnAdd`. However, there was a bug in 5.0 where this was not being detected for `decimal` properties.

The fix is to explicitly specify some other way that one of the columns will get its generated value. This could be by specifying a value generator, or from a default value in the database. For example:

```C#
entity.Property(e => e.InterfaceHeaderId)
    .HasColumnName("INTERFACE_HEADER_ID")
    .HasDefaultValue(0m)
    .ValueGeneratedOnAdd();
```

**Comment by tomasfil** [comment]
@ajcvickers Hello, I would like to ask why this was closed. How can be "be by design" Scaffold-DbContext, which generates code, which wont even launch? Thanks.

**Comment by ErikEJ** [comment]
Please share a CREATE TABLE statement, that causes the invalid mapping to be generated.

**Comment by tomasfil** [comment]
Hello, I have issue going on oracle provider with all the information: https://github.com/oracle/dotnet-db-samples/issues/222
Where it is pending to wait for this issue resolution.

**Comment by ErikEJ** [comment]
@tomasfil That issue should not wait for this one to be resolved!

**Comment by tomasfil** [comment]
@ErikEJ Thanks for direction. I will now wait for alexkeh to respond. Thank you.

**Comment by ajcvickers** [comment]
@tomasfil SQL Server doesn't allow more than one Identity column in a database. If we are reverse engineering this from SQL Server, then that could be a bug in the scaffolding code. As @ErikEJ says, we would need the schema for this.

The validation here is coming from `SqlServerModelValidator`--i.e. it is SQL Server specific. If Oracle is not allowing this when it is valid for Oracle, then it seems like an issue with the Oracle model validator, or potentially the Oracle reverse engineering scaffolder.

**Comment by shvmgpt116** [comment]
> @shvmgpt116 This is by-design; SQL Server doesn't allow multiple columns to be marked as `IDENTITY`, which is the default when using `ValueGeneratedOnAdd`. However, there was a bug in 5.0 where this was not being detected for `decimal` properties.
> 
> The fix is to explicitly specify some other way that one of the columns will get its generated value. This could be by specifying a value generator, or from a default value in the database. For example:
> 
> ```cs
> entity.Property(e => e.InterfaceHeaderId)
>     .HasColumnName("INTERFACE_HEADER_ID")
>     .HasDefaultValue(0m)
>     .ValueGeneratedOnAdd();
> ```

@ajcvickers ValueGenerator is a client side value generator. Is there a way to use a server side value generator (like triggers)?

**Comment by ajcvickers** [comment]
@shvmgpt116 You can use `HasDefaultValueSql`, which, like `HasDefaultValue`, will tell EF that the value is being generated on the server. I'm not 100% sure how this interreacts with triggers that run on inserts in SQL Server. Maybe @ErikEJ knows?

**Comment by ErikEJ** [comment]
Default are better than AFTER INSERT triggers  and triggers can cause unexpected data changes.
