### ISSUE TITLE
Website cannot load Microsoft.EntityFrameworkCore

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/efcore#27029]
I have an API-only site (no pages) that is terminating as soon as it starts.

I found the following errors in Event Viewer.

```
Application: w3wp.exe
CoreCLR Version: 6.0.21.52210
.NET Version: 6.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=6.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.EntityFrameworkCore, Version=6.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Program.<Main>$(String[] args)
```

And...

```
Application '/LM/W3SVC/18/ROOT' with physical root 'C:\inetpub\wwwroot\tt.railtrax.com\' hit unexpected managed exception, exception code = '0xe0434352'. First 30KB characters of captured stdout and stderr logs:
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=6.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.EntityFrameworkCore, Version=6.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Program.<Main>$(String[] args)
```

When I look at *Microsoft.EntityFrameworkCore.dll* in my deploy folder, it appears to be version 6.0.21.

[![Microsoft.EntityFrameworkCore.dll][1]][1]

Package Manager says I have 6.0.1 installed. So I don't know why I have 6.0.21, or if it should work with that version.

[![Microsoft.EntityFrameworkCore Package][2]][2]

The project runs fine on my own computer. I very recently upgraded all the suggested packages in Package Manager. I assume it happened as a result of that. Do these version discrepancies matter? What else I could try to resolve this?

  [1]: https://i.stack.imgur.com/GxmQl.png
  [2]: https://i.stack.imgur.com/pFgHn.png

**Comment by roji** [comment]
@SoftCircuits this looks like some sort of deployment issue. There's very little info on how your website is hosted or how you're deploying your application to the production server, but the exception says that the Entity Framework Core assembly (DLL) is missing. There's not much we can do to help with that, but if you manage to reproduce the problem with a code sample, we can investigate further.

**Comment by roji** [comment]
Another note (thanks @ajcvickers) - nuget versions (6.0.1 above) don't necessarily correspond to assembly versions (6.0.21), so that discrepancy is probably normal. Also, the exception says "The system cannot find the file specified"; had this been a versioning mismatch, the exception message which have been different.

**Comment by SoftCircuits** [comment]
@roji Everything runs fine on my local computer, so it absolutely is not something that can be reproduced with a code sample.

I'm deploying to a local folder and then manually copying those files to the server. This has been working fine. May be related to upgrading all the suggested NuGet packages recently.

I know it's not much to go on. Can you suggest anything else to try in order to shed any light on what might be happening?

**Comment by SoftCircuits** [comment]
Can anyone explain why Package Manager says I have version 6.0.1 installed, but the actual file versions are 6.0.0 for the product version and 6.021.52301 for the file version? Is this what version 6.0.1 should look like?

**Comment by ErikEJ** [comment]
You should Publish, not copy files manually.

Please share your csproj.

For the version, you are looking at productversion and fileversion, but you cannot see assembly version in that dialogue.

**Comment by SoftCircuits** [comment]
@ErikEJ As explained, I am publishing to a local folder, and then copying those files to the server. So the files I'm copying were all created by the Publish command. This has been working until I upgraded NuGet packages.

As you can see from my screenshots, I have several projects. Here is the project file for my main project that is not running (*TTRailtrax).

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <UserSecretsId>838ad821-3be6-430c-9faa-a5851387030b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TTRailtraxBusinessLayer\TTRailtraxBusinessLayer.csproj" />
    <ProjectReference Include="..\TTRailtraxEntities\TTRailtraxEntities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Attributes\" />
  </ItemGroup>

</Project>
```

Here is the project file for *RailtraxCore*. This is a class library that *Microsoft.EntityFrameworkCore* is installed on and is referenced by *TTRailtrax*.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="6.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Razor" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="6.0.0" />
    <PackageReference Include="SoftCircuits.CsvParser" Version="3.5.0" />
  </ItemGroup>

</Project>
```

*Note: Since Microsoft.EntityFrameworkCore is installed to RailtraxCore, and this assembly is referenced by all my other projects, I uninstalled Microsoft.EntityFrameworkCore from the RailtraxEntities project. So now RailtraxCore is the only project that has Microsoft.EntityFrameworkCore. And all other projects reference RailtraxCore.*

**Comment by GoodBoyAlex** [comment]
Hello! The same problem!
Here my project file:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <UserSecretsId>aspnet-rnrmm_ru-6B529B80-88C9-4339-A2EE-BEFA73D451B8</UserSecretsId>
    <CopyRefAssembliesToPublishDirectory>false</CopyRefAssembliesToPublishDirectory>
    <RootNamespace>rnrmm</RootNamespace>
    <StartupObject />
    <ApplicationIcon>favicon.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;2254</NoWarn>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;2254</NoWarn>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\forum\Data\**" />
    <Compile Remove="Models\StaticModels\**" />
    <Content Remove="Areas\forum\Data\**" />
    <Content Remove="Models\StaticModels\**" />
    <EmbeddedResource Remove="Areas\forum\Data\**" />
    <EmbeddedResource Remove="Models\StaticModels\**" />
    <None Remove="Areas\forum\Data\**" />
    <None Remove="Models\StaticModels\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ANBSoftware.ComponentsPack" Version="1.2021.1215" />
    <PackageReference Include="HtmlSanitizer" Version="6.0.453" />
    <PackageReference Include="JetBrains.Annotations" Version="2021.3.0" />
    <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="8.5.0" />
    <PackageReference Include="Magick.NET.Core" Version="8.5.0" />
    <PackageReference Include="MailKit" Version="3.0.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.20.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="6.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="6.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="6.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.1" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="6.0.1" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="6.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\forum\Views\Shared\Partials\" />
    <Folder Include="Migrations\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Config\sc_email.bin">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties /></VisualStudio></ProjectExtensions>

</Project>
```
My connection string (with hidden user and password)
```
"rnrmm_ru_db": "Data Source=localhost;Database=rnrmm_data;Integrated Security=False;User ID=<USER>;Password=<PASSWORD>",
"users_db": "Data Source=localhost;Database=rnrmm_ui;Integrated Security=False;User ID=<USER>;Password=<PASSWORD>",
"rnrmm_ru_forum": "Data Source=localhost;Database=rnrmm_forum;Integrated Security=False;User ID=<USER>;Password=<PASSWORD>"
```
And as result error log on server (on my PC works fine):
```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=6.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Не удается найти указанный файл.
File name: 'Microsoft.EntityFrameworkCore, Version=6.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at rnrmm.Startup.ConfigureServices(IServiceCollection services)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at rnrmm.Program.Main(String[] args)
```

**Comment by SoftCircuits** [comment]
@GoodBoyAlex I've just discovered that in my *bin\Release\net6.0* folder, *Microsoft.EntityFrameworkCore.dll* has product version 6.0.1. But in my deployment folder, it has product version 6.0.0. Somehow, the correct file is not being copied from my project to the deployment folder. Can you check this on your system?

**Comment by GoodBoyAlex** [comment]
In my folder was 6.0.1. And its work fine when I do IIS Publish

**Comment by SoftCircuits** [comment]
@GoodBoyAlex  Were you able to resolve your issue? I just figured it out here. I just deleted the *bin* and *obj* folders for all projects involved and rebuilt everything. Now it works.
