### ISSUE TITLE
Do not map annotation to database during migrations

### ISSUE THREAD

**Issue by lonix1** [dotnet/efcore#27048]
## Ask a question
*I've read the docs, searched StackOverflow and tried my best to dig into past issues. The best I could find was [this](https://github.com/dotnet/efcore/issues/10258#issuecomment-343605538) but the method signatures seem to have changed since then.*

I am trying to understand the "annotations" feature but it is undocumented.

When building a model I use this:
````cs
MyAnnotation value = GetSomeComplexObjectToUseAsAnnotation();
entityTypeBuilder
  .Property(x => x.Name)
  .HasAnnotation("SomeKey", value);
````

And later I can retrieve it using something like this:
````cs
context
  .Model
  .GetEntityTypes()
  .SelectMany(x => x.GetProperties())
  .Select(x => x.FindAnnotation("SomeKey")?.Value)
  .Where(x => x is MyAnnotation);
````

I use it as a way to pass around info concerning the model, which I can use for various purposes. **That works!**

But `dotnet ef migrations add` throws:

> System.InvalidOperationException: Cannot scaffold C# literals of type 'MyAnnotation'. The provider should implement CoreTypeMapping.GenerateCodeLiteral to support using it at design time.
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.UnknownLiteral(Object value)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateAnnotation(IAnnotation annotation, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateAnnotations(IEnumerable`1 annotations, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GeneratePropertyAnnotations(IProperty property, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateProperty(String builderName, IProperty property, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateProperties(String builderName, IEnumerable`1 properties, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateEntityType(String builderName, IEntityType entityType, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateEntityTypes(String builderName, IReadOnlyList`1 entityTypes, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.Generate(String builderName, IModel model, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationsGenerator.GenerateMetadata(String migrationNamespace, Type contextType, String migrationName, String migrationId, IModel targetModel)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)

I assume the problem is the migration system is expecting a primitive type, but it gets an instance of `MyAnnotation` and doesn't know how to map that to the database - but I don't want it in the database.

In the post I linked above ajcvickers said:
> since many annotations only affect runtime behavior, not the database schema.

So I assume (?) I can use the annotation system this way. How do I tell migrations to not map that annotation?

## Include provider and version information

EF Core version: 5.0.11
Database provider: sqlite, postgres
Target framework: dotnet5
Operating system: linux
IDE: vscode 1.63.0

Thank you!

**Comment by ajcvickers** [comment]
@bricelam @roji Is there a public/application-facing way to exclude annotations from the migrations snapshot?

**Comment by bricelam** [comment]
Looks like you should be able to override [AnnotationCodeGenerator.FilterIgnoredAnnotations](https://github.com/dotnet/efcore/blob/b39ca7f24c96df9aec977a29f35b1c0c70b54f5f/src/EFCore.Relational/Design/AnnotationCodeGenerator.cs#L127-L130) to add exclusions.

**Comment by lonix1** [comment]
Thank you!

I couldn't get it to work (same exception), so I probably misunderstood.

1. I created a custom service as you suggested:
````cs
public class MyAnnotationCodeGenerator : AnnotationCodeGenerator
{

  public MyAnnotationCodeGenerator(AnnotationCodeGeneratorDependencies dependencies) : base(dependencies) { }

  // this method is never executed:
  public override IEnumerable<IAnnotation> FilterIgnoredAnnotations(IEnumerable<IAnnotation> annotations) =>
    base.FilterIgnoredAnnotations(annotations)
    .Where(a => a.Value.GetType() != typeof(MyAnnotation));

}
````

2. I used it to create a context in design-time:
````cs
public class MyDesignTimeContextFactory : IDesignTimeDbContextFactory<MyContext>
{

  public Context CreateDbContext(string[] args) {
    // ...
    optionsBuilder.ReplaceService<IAnnotationCodeGenerator, MyAnnotationCodeGenerator>();
    return new Context(optionsBuilder.Options);
  }

}
````

That is all I do when replacing other services.

Is there anything extra to be done? (If not then the problem is on my side and I'll deal with, feel free to close!)

**Comment by bricelam** [comment]
Hmm, that's exactly what I had in mind. Ah, looks like it's a [design-time service](https://docs.microsoft.com/ef/core/cli/services) so ReplaceService won't work. Instead, you'll need to add a class that implements IDesignTimeServices:

```cs
class MyDesignTimeServices : IDesignTimeServices
{
    public void ConfigureDesignTimeServices(IServiceCollection services)
        => services.AddSingleton<IAnnotationCodeGenerator, MyAnnotationCodeGenerator>();
}
```

**Comment by lonix1** [comment]
Thanks now it triggers the custom behaviour (I assume it finds it via assembly scanning because I didn't even register it).

However the overriden method
````cs
public override IEnumerable<IAnnotation> FilterIgnoredAnnotations(IEnumerable<IAnnotation> annotations) =>
    base.FilterIgnoredAnnotations(annotations)
    .Where(a => a.Value.GetType() != typeof(MyAnnotation));
````

...is receiving an empty `annotations` collection. Is that expected?

**Comment by bricelam** [comment]
> I assume it finds it via assembly scanning

Correct.

> ...an empty annotations argument. Is that expected?

Expected. We could avoid calling it if it's empty, but just calling it keeps the code simpler.

**Comment by lonix1** [comment]
I don't follow - if `annotations` is empty, how does one filter out the unwanted annotation?

I assumed the trick was
````cs
return annotations.Where(a => a.Value.GetType() != typeof(MyAnnotation));
````

**Comment by bricelam** [comment]
> that does nothing when `annotations` is empty

Whis is the correct behavior for an entity type without any annotations, right?

**Comment by lonix1** [comment]
LOL you schooled me!

The docs say
> This implementation returns false for all 'IsHandledByConvention' methods and null for all 'GenerateFluentApi' methods. Providers should override for the annotations that they understand.

So I fiddled with those and presumably that was the problem. I've since learned I don't need to change anything other than the filter method, as you explained.

This very simple code works, for anyone who needs it:
````cs
public class MyDesignTimeServices : IDesignTimeServices
{
  public void ConfigureDesignTimeServices(IServiceCollection services)
    => services.AddSingleton<IAnnotationCodeGenerator, MyAnnotationCodeGenerator>();
}

public class MyAnnotationCodeGenerator : AnnotationCodeGenerator
{
  public MyAnnotationCodeGenerator(AnnotationCodeGeneratorDependencies dependencies) : base(dependencies) { }
  public override IEnumerable<IAnnotation> FilterIgnoredAnnotations(IEnumerable<IAnnotation> annotations) => 
    base.FilterIgnoredAnnotations(annotations).Where(a => a.Name != "SomeKey");
}
````

Thanks guys!
