### ISSUE TITLE
InputObject `GeometryOverlaySortInput` has no fields declared

### ISSUE THREAD

**Issue by edihasaj** [dotnet/efcore#27042]
Graphql with Hotchocolate does not start because GeometryOverlaySortInput of NetTopologySuite package has no fields declared.

I upgraded the Hotchocolate Graphql packages and EntityFramework Core packages, and now the application starts but graphql is not working. I tried downgrading the versions one by one, but it seems that reversing to ef core packages version 5.0.13 and lower this error doesn't happen. Maybe you can show me how can I contribute to fix this issue and I will do a PR.

```
1. InputObject `GeometryOverlaySortInput` has no fields declared. (HotChocolate.Data.Sorting.SortInputType<NetTopologySuite.Geometries.GeometryOverlay>)
2. InputObject `CoordinateEqualityComparerSortInput` has no fields declared. (HotChocolate.Data.Sorting.SortInputType<NetTopologySuite.Geometries.CoordinateEqualityComparer>)

   at HotChocolate.Configuration.TypeInitializer.EnsureNoErrors()
   at HotChocolate.Configuration.TypeInitializer.CompleteTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize()
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types, LazySchema lazySchema)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.HttpPostMiddleware.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
   at HotChocolate.AspNetCore.HttpPostMiddleware.InvokeAsync(HttpContext context)
   at HotChocolate.AspNetCore.WebSocketSubscriptionMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass13_0.<<UseCancellation>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Thanks a lot

### Include provider and version information

EF Core version: 6.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows
IDE: JetBrains Rider

**Comment by roji** [comment]
@edihasaj have you discussed this with the HotChocolate folks? It really seems to be more in their area than in EF Core's - we just take the dependency on the NetTopologySuite package.

**Comment by edihasaj** [comment]
@roji no I haven't because I thought there was a property that is missing in NetTopologySuite package. Anyways I'm opening an issue there and if the problem is there, I will close this.

Thank you for your fast response, appreciate it.

**Comment by edihasaj** [comment]
I'm closing this issue as I'm tracing it in the HotChocolate library (It looks that there is a bug in the new version of their library).
I'm putting a [link ](https://github.com/dotnet/efcore/issues/27042#issue-1084176022) here for anyone having the same issue.

Thank you for your support.
