### ISSUE TITLE
Deployment is copying the wrong DLL version?

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/efcore#27049]
*Note: I'm not sure if this is the correct place to post this. It is about an issue with deploying Microsoft.EntityFrameworkCore.dll.*

I am deploying my website to a local folder, and then manually copying those files to the server. This has been working fine until I recently upgraded all the recommended NuGet packages.

Now, the project runs fine on my local computer. But I get an error about loading *Microsoft.EntityFrameworkCore* 6.0.1 when I run the project on the server.

After investigating this further, I can see *Microsoft.EntityFrameworkCore.dll* in my *bin\Release\net6.0 folder* folder has product version 6.0.1. But the same file in my deployment folder has product version 6.0.0.

It seems that the deployment command is somehow not copying the right file. How can this be?

Here is my *.pubxml* file.

```xml
<?xml version="1.0" encoding="utf-8"?>
<!--
https://go.microsoft.com/fwlink/?LinkID=208121. 
-->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <DeleteExistingFiles>True</DeleteExistingFiles>
    <ExcludeApp_Data>False</ExcludeApp_Data>
    <LaunchSiteAfterPublish>True</LaunchSiteAfterPublish>
    <LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>
    <LastUsedPlatform>Any CPU</LastUsedPlatform>
    <PublishProvider>FileSystem</PublishProvider>
    <PublishUrl>D:\Users\jwood\Desktop\Railtrax Projects\tt.railtrax</PublishUrl>
    <WebPublishMethod>FileSystem</WebPublishMethod>
    <SiteUrlToLaunchAfterPublish />
    <TargetFramework>net6.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishReadyToRun>True</PublishReadyToRun>
    <ProjectGuid>6c4edd36-b499-42c0-84c5-e009498c42d8</ProjectGuid>
    <SelfContained>false</SelfContained>
  </PropertyGroup>
</Project>
```

Is this a bug?

### Include provider and version information

Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 11
IDE: 17.0.4

**Comment by ajcvickers** [comment]
@SoftCircuits

> This has been working fine until I recently upgraded all the recommended NuGet packages.

Are you saying this was working differently when using 5.0.0 and 5.0.x patches?

**Comment by SoftCircuits** [comment]
@ajcvickers It had been working with .NET 5.0, and later 6.0. NuGet Package Manager recommended I upgrade a bunch of packages to 6.0.1. That's when I noticed this issue.

It's important to emphasize that it runs fine in my lab. The DLLs themselves seem fine. But it seems like it confused the deployment code.

**Comment by SoftCircuits** [comment]
So, I just found out I'm having the same issue with another DLL in another project in this same solution.

```
Application: w3wp.exe
CoreCLR Version: 6.0.21.52210
.NET Version: 6.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Identity.UI, Version=6.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.AspNetCore.Identity.UI, Version=6.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Transload.Railtrax.Startup.ConfigureServices(IServiceCollection services)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Transload.Railtrax.Program.Main(String[] args) in D:\Users\jwood\source\repos\Railtrax\Transload.Railtrax\Program.cs:line 16
```

As with *Microsoft.EntityFrameworkCore.dll* in the other project, the version of *Microsoft.AspNetCore.Identity.UI* in *bin\Release\net6.0* is 6.0.1. But this same file in the deployment folder is 6.0.0.

What on Earth is happening here? I don't know what else to try.

**Comment by SoftCircuits** [comment]
I finally resolved these issues by deleting the *bin* and *obj* folders for all projects involved. Hard to know exactly what the issue was but doesn't seem like package updates should be this brittle.
