### ISSUE TITLE
EF 6.0.0 and 6.0.1: sub-lists are no longer loaded

### ISSUE THREAD

**Issue by MarcDrexler** [dotnet/efcore#27105]
# Description

After upgrading from 5.0.13 to 6.0.0 or 6.0.1, I can no longer load sublists and instead get an exception.

<img width="494" alt="image" src="https://user-images.githubusercontent.com/16029585/148037861-5e033862-27e7-4516-a890-4457e56cbc0e.png">

# Exception Details
```
System.ArgumentException
  HResult=0x80070057
  Message=GenericArguments[2], 'System.Collections.Generic.List`1[<>f__AnonymousType1`2[System.Guid,System.String]]', on 'Void PopulateCollection[TCollection,TElement,TRelatedEntity](Int32, Microsoft.EntityFrameworkCore.Query.QueryContext, System.Data.Common.DbDataReader, Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryResultCoordinator, System.Func`3[Microsoft.EntityFrameworkCore.Query.QueryContext,System.Data.Common.DbDataReader,System.Object[]], System.Func`3[Microsoft.EntityFrameworkCore.Query.QueryContext,System.Data.Common.DbDataReader,System.Object[]], System.Func`3[Microsoft.EntityFrameworkCore.Query.QueryContext,System.Data.Common.DbDataReader,System.Object[]], System.Collections.Generic.IReadOnlyList`1[Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer], System.Collections.Generic.IReadOnlyList`1[Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer], System.Collections.Generic.IReadOnlyList`1[Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer], System.Func`5[Microsoft.EntityFrameworkCore.Query.QueryContext,System.Data.Common.DbDataReader,Microsoft.EntityFrameworkCore.Query.Internal.ResultContext,Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryResultCoordinator,TRelatedEntity])' violates the constraint of type 'TRelatedEntity'.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitNew(NewExpression node)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.ProcessShaper(Expression shaperExpression, RelationalCommandCache& relationalCommandCache, LambdaExpression& relatedDataLoaders, Int32& collectionId)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.VisitShapedQuery(ShapedQueryExpression shapedQueryExpression)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EfCorePopulateCollectionProblem.Program.Main(String[] args) in C:\Users\MarcDrexler\source\repos\EfCore\EfCorePopulateCollectionProblem\Program.cs:line 11

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
VerificationException: Method Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor+ShaperProcessingExpressionVisitor.PopulateCollection: type argument 'System.Collections.Generic.List`1[<>f__AnonymousType1`2[System.Guid,System.String]]' violates the constraint of type parameter 'TRelatedEntity'.
```

# Code
A repository to demonstrate the bug can be found here:
https://github.com/MarcDrexler/EfCorePopulateCollectionProblem

To verify the problem, simply press F5 and it will throw the exception.
Connection string and database is not needed.

# Provider and version information
EF Core version: tested in 6.0.0 + 6.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 6.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.1

**Comment by ajcvickers** [comment]
@smitpatel Confirmed regression on 6.0. SQL generated in 5.0:

```sql
      SELECT [e].[Id], [t].[Id], [t].[Id0], [t].[Prop]
      FROM [EntityOnes] AS [e]
      LEFT JOIN (
          SELECT [e0].[Id], [e1].[Id] AS [Id0], [e1].[Prop], [e0].[EntityOneId]
          FROM [EntityTwo] AS [e0]
          LEFT JOIN [EntityThree] AS [e1] ON [e0].[Id] = [e1].[EntityTwoId]
      ) AS [t] ON [e].[Id] = [t].[EntityOneId]
      ORDER BY [e].[Id], [t].[Id], [t].[Id0]
```

Code:

```C#
public class EntityOne
{
    public Guid Id { get; set; }

    public List<EntityTwo> ListA { get; set; }
}

public class EntityTwo
{
    public Guid Id { get; set; }

    public List<EntityThree> ListB { get; set; }
}

public class EntityThree
{
    public Guid Id { get; set; }

    public string Prop { get; set; }
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(Your.ConnectionString)
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    public DbSet<EntityOne> EntityOnes { get; set; }
    public DbSet<EntityTwo> EntityTwos { get; set; }
    public DbSet<EntityTwo> EntityThrees { get; set; }
}

public class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var result = context.Set<EntityOne>()
                .Select(x =>
                    new
                    {
                        x.Id,
                        ListWithSubList = x.ListA.Select(b =>
                            b.ListB.Select(o => new
                            {
                                o.Id, o.Prop
                            }))
                    })
                .ToList();
        }
    }
}
```

**Comment by smitpatel** [comment]
We will discuss in triage if we want to patch this. Created PR against 6.0 for now.
