### ISSUE TITLE
Migrator throwing "The migration was not found."

### ISSUE THREAD

**Issue by bramve-fenetre** [dotnet/efcore#27115]
### The bug
So in a project of mine we want to run migrations on startup. In the case of a failure in one of the migrations in startup we want to log which migration has failed and what has failed in the migration. So to achieve this i want to run each pending migration one by one, so if one fails i know which migration is failing and i can log this.

To achieve this i saw that the IMigrator offers the possibility to run migrations until a specified migration which is perfect. However when i tried this it throws the error "The migration was not found".

My code is extremely simple:

```
var migrator = dbContext.Database.GetService<IMigrator>();
var pendingMigrations = dbContext.Database.GetPendingMigrations();
foreach(var pendingMigration in pendingMigrations)
{
    try
    {
        migrator.Migrate(pendingMigration);
    }
    catch (Exception e)
    {
        var someException = e;
    }
}
```

Here i have setup an example project of my exact scenario which is not working:
https://github.com/bramve-fenetre/DemoMigratorIssue

### Include provider and version information

EF Core version: 3.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: 3.1
Operating system: Windows 10
IDE: Visual Studio 2019

**Comment by ajcvickers** [comment]
@bricelam I investigated this and the problem appears to be that the migration is included inline with the code, like this:

```C#
[DbContext(typeof(TestContext))]
[Migration("InitialMigration")]
public class InitialMigration : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "Car",
            columns: table => new
            {
                Id = table.Column<int>(nullable: false)
                    .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                Name = table.Column<string>(nullable: true),
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Cars", x => x.Id);
            });
    }
}
```

There is no code-behind or model snapshot. This is found by `GetPendingMigrations`, but results in the following exception when calling `Migrate` for it:

```
Unhandled exception. System.InvalidOperationException: The migration 'InitialMigration' was not found.
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsAssemblyExtensions.GetMigrationId(IMigrationsAssembly assembly, String nameOrId)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.PopulateMigrations(IEnumerable`1 appliedMigrationEntries, String targetMigration, IReadOnlyList`1& migrationsToApply, IReadOnlyList`1& migrationsToRevert, Migration& actualTargetMigration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GetMigrationCommandLists(IReadOnlyList`1 appliedMigrationEntries, String targetMigration)+MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at MigratorBugTest.Program.Main(String[] args) in C:\local\code\repros\DemoMigratorIssue-main\DemoMigratorIssue-main\MigratorBugTest\Program.cs:line 23
```

If I instead create a migration using the tooling in the normal way, then it works as expected.

**Comment by bramve-fenetre** [comment]
@ajcvickers But the problem is, in the project i work in we do not have a snapshot as we do not work with the code first generation tools, but instead create migrations manually. And since dbContext.Database.Migrate works just fine so it seems the underlying code doesn't need a snapshot at all.

So the question remains, can this still be fixed?

**Comment by ajcvickers** [comment]
@bramve-fenetre Agreed; the question remains. This is why I wrote down the results of my investigation for @bricelam to take a look at.

**Comment by bricelam** [comment]
This needs to be a *full* migration ID; not just the name:

```diff
- [Migration("InitialMigration")]
+ [Migration("00000000000000_InitialMigration")]
```

**Comment by bramve-fenetre** [comment]
That does work indeed, but in our project we have our own naming convention which doesn't have this ID in the name of the migration. Can this be supported?

**Comment by bramve-fenetre** [comment]
Looked into the source code, if this check is removed then everything works like i expect, and then the behavior between the migrator and dbContext.Database.Migrate is the same :)

![image](https://user-images.githubusercontent.com/62645369/148913432-798ce765-bb2c-49cc-8f4b-5fab03a7ed2a.png)

**Comment by bricelam** [comment]
The time stamp is there to preserve the order the migrations. Without it, migrations would be applied in alphabetical order regardless of the order you created them.

**Comment by bricelam** [comment]
Note, the class name can be anything, but the ID in that attitude has a defined format.

**Comment by bramve-fenetre** [comment]
Yea i understand. The thing is we have our own naming convention, which still makes sure that the order of migrations is correct, for example 000_000_000_my_migration, 001_000_000_my_migration_2.

Which again works fine using dbContext.Database.Migrate(), just not with the Migrator because of the additional validation it has

**Comment by bricelam** [comment]
Ah, in that case, you just need to replace the [IMigrationsIdGenerator](https://github.com/dotnet/efcore/blob/main/src/EFCore.Relational/Migrations/Internal/MigrationsIdGenerator.cs) service with an implementation for your format.

**Comment by ajcvickers** [comment]
Note from triage: we should do better validation of migration IDs.

**Comment by bramve-fenetre** [comment]
> Ah, in that case, you just need to replace the [IMigrationsIdGenerator](https://github.com/dotnet/efcore/blob/main/src/EFCore.Relational/Migrations/Internal/MigrationsIdGenerator.cs) service with an implementation for your format.

Didn't realize I could replace that. Thanks for the tip with that i could workaround the issue 👍
