### ISSUE TITLE
TPH Issue with navigation property when class not in same assembly

### ISSUE THREAD

**Issue by kYann** [dotnet/efcore#27122]
Hello,

I'm trying to use TPH with type in different assemblies (using convention mapping). When having the configuration shown below I get an error : 

> 'Property ''NetworkCompanyDepartment' on entity type 'JobTitle' is mapped without a CLR property. 'UseChangeTrackingProxies' requires all entity types ...

```C#
// in Assembly "Networks"
public class NetworkCompanyDepartment : CompanyDepartment
{
}

// in Assembly "Users"
public class DefaultCompanyDepartment : CompanyDepartment
{
}

public abstract class CompanyDepartment
{
   public virtual int Id { get; set; }

   public virtual ICollection<JobTitle> JobTitles { get; set; }
}

public class JobTitle {
 public virtual int Id { get; set; }
 
 public virtual CompanyDepartment CompanyDepartment  { get;set; }
}
```

When moving the NetworkCompanyDepartment in the same assembly, it works !

### Stack traces

```
   at Microsoft.EntityFrameworkCore.Proxies.Internal.ProxyBindingRewriter.ProcessModelFinalizing(IConventionModelBuilder modelBuilder, IConventionContext`1 context)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelFinalizing(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelFinalizing(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FinalizeModel()
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
```

### Include provider and version information

EF Core version: 5.0.10
Database provider: Npgsql
Target framework: .NET 5.0
Operating system:
IDE: Visual Studio 2022

**Comment by ajcvickers** [comment]
@kYann Please post your `DbContext` code.

**Comment by kYann** [comment]
Hello Arthur,

Here is the code :
```csharp
public class PeeringContext : DbContext
{
	private readonly DbContextOptions<PeeringContext> options;

	public PeeringContext(DbContextOptions<PeeringContext> options)
	: base(options)
	{
		this.options = options;
	}
	
	private bool ShouldMap(Type type) => true; // Return true to make it simpler

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		var assemblies = options.GetScannerAssemblies(); // Return list of assemblies to scan
		foreach (var assembly in assemblies)
		{
			modelBuilder.ApplyConfigurationsFromAssembly(assembly);
			foreach (var type in assembly.GetTypes())
			{
				if (ShouldMap(type)) // Check if inherit from special interface in real case
					modelBuilder.Entity(type);
			}
		}
		base.OnModelCreating(modelBuilder);
	}
}
```

Have a nice day,

**Comment by ajcvickers** [comment]
@kYann That will teach me not to ask for a full repro. :-) Given that code, can you also post all your EntityTypeConfigurations? Also, are you sure that `GetScannerAssemblies` is returning all the assemblies containing entity types?

Ideally, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by kYann** [comment]
Hi @ajcvickers !

While doing the repro case I found out a external convention that was setting the relation to many to many.
Sorry for wasting your time ! 🙏
