### ISSUE TITLE
check keyless entity for null server side evaluation

### ISSUE THREAD

**Issue by NormanGiHu** [dotnet/efcore#27242]
Hello,

given this example linq query:

```C#
from position in Orderpositions.Where(
position => position.OrderNr == 12345
         && position.MaterialId == 677)

//left join
join amount in VIEW_Orders_Delivered_Amounts
on new
{
    ordernr = position.OrderNr,
    position = position.MaterialId
} equals new
{
    ordernr = amount.OrderNr
                           .GetValueOrDefault(),
    position = Convert.ToInt16(
        amount.OrderPosition
                   .GetValueOrDefault())
}
into deliveredGroup
 from delivery in deliveredGroup.DefaultIfEmpty(
     )

       select
	   new 
       {
           MaterialId = position.Material_ID,
		   Amount= delivery.Amount
}
```

If join with VIEW_Orders_Delivered_Amounts is not possible, then left join produces null for delivery.

"delivery" is a keyless entity, because its based on a database view.

Problem is here because of delivery is null : 
![image](https://user-images.githubusercontent.com/71928731/150523963-a2da3799-407e-4bb6-8366-8bd423e4e004.png)

I try it to solve with null check, but also problem:
![image](https://user-images.githubusercontent.com/71928731/150525290-7a2b8c70-fd16-409d-aebc-b1664da77eb4.png)

This seems to comes from 
[https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.diagnostics.corestrings.entityequalityonkeylessentitynotsupported?view=efcore-5.0](url)

But my goal is not to compare, i need to check for null.
Is there a way to do handle the null value of keyless entities and use ef core server side evaluation ?

StackTrace of "Compare" -exception:

>    at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TryRewriteEntityEquality(ExpressionType nodeType, Expression left, Expression right, Boolean equalsMethod, Expression& result)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitConditional(ConditionalExpression conditionalExpression)
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TranslateInternal(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitNew(NewExpression newExpression)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.IEnumerable.GetEnumerator()
   at LINQPad.Extensions.Dump[T](T o, String description, Nullable`1 depth, Nullable`1 collapseTo, Boolean toDataGrid, String exclude, String include, Nullable`1 alpha, Boolean noTotals, Nullable`1 repeatHeadersAt, Boolean includePrivate)
   at LINQPad.Extensions.Dump[T](T o)
   at UserQuery.Main(), line 1000030

EF Core version: 5.0.
Database provider: Microsoft.EntityFrameworkCore.SqlServer 
Target framework:  .NET 5.0
Operating system: Windows 10

``

**Comment by smitpatel** [comment]
```C#
select
new 
 {
           MaterialId = position.Material_ID,
	   Amount= delivery.Amount ?? 0
}
```

**Comment by NormanGiHu** [comment]
No.
Because delivery is null and not only Amount.
And if Amount is a not nullable type ?? would not even be allowed.

**Comment by smitpatel** [comment]
```C#
select
new 
 {
           MaterialId = position.Material_ID,
	   Amount= ((int?)delivery.Amount) ?? 0
}
```

**Comment by NormanGiHu** [comment]
Thank you very much!
This is working (unexpected for me).

I had expected an exception, because delivery must be null, but that seems not the case here. :)

**Comment by NormanGiHu** [comment]
Yes, it's a very helpful and detailed explanation.
All possible questions in this issue are fully answered. :)

Thank you very much again!
