### ISSUE TITLE
TemporalAsOf in temporal tables with non-temporal child entity throws InvalidOperationException when used with Include

### ISSUE THREAD

**Issue by dragos-durlut** [dotnet/efcore#27259]
I would have not raised this bug, but according to this exchange between @ajcvickers and @iSatishYadav ~~this~~ the possibility of using `Include()` and `ThenInclude()` with non-temporal child entities when using the `TemporalAsOf` query, should have been supported.
More details about the bug and how to reproduce it are found below.

> @iSatishYadav The problem with the temporal operators that return multiple instances of the same entity is that the referential constraints of the model are broken. There can be many instances of one entity referring to many instances of another entity. (Note this is different from many instances which are different entities.) This is essentially why SQL Server also removes all constraints from the history tables. So we have no plan to enable Include or other navigation expansions for the temporal operators that return many instances. 
 **Contrast this with `TemporalAsOf`**, which uses a specific point in time. In this case, the model constraints are preserved and all entity associations are in a valid state. This is why **Include and other navigation expansions are supported with AsOf**.

_Originally posted by @ajcvickers in https://github.com/dotnet/efcore/issues/26704#issuecomment-970112997_

I have managed to **reproduce this bug** in this forked repository [here](https://github.com/dragos-durlut/TemporalTables).
This was the repository @ajcvickers used to showcase the features in efcore 6.

You can see the added code and schema update in this commit [here](https://github.com/dragos-durlut/TemporalTables/commit/4ea21c7733605b3fa0b3c83fd6530a65fbb04f74)

The query that raises the error is the following:

```C#
private static void QueryEverythingTemporalAsOf()
{
	using var context = new OrdersContext(log: true);

	var query = context.Products.TemporalAsOf(DateTime.UtcNow)
		.Include(p => p.Orders).ThenInclude(o => o.Customer)
		.Include(p => p.ProductType).ThenInclude(pt => pt.ProductClass);

	var list = query.ToList();
}
```

Two new tables have been added: `ProductType` and `ProductClass`.
These are basically child tables to the `Products` table.
These are obviously **non-temporal**.

This, in theory should never or seldom change. But these are needed in retrieving the entities from the DB.

The error is the following:
```
System.InvalidOperationException
HResult=0x80131509
Message=Temporal query is trying to use navigation to an entity 'ProductType' which itself doesn't map to temporal table. Either map the entity to temporal table or use join manually to access it.
```

It says I have 2 options: `Either map the entity to temporal table or use join manually to access it.` The first is not feasible and the second raises some questions:
- where am I supposed to place the join for this to work ? Will the join automatically populate the resulting entity with `ProductType` and `ProductClass` ?
- what if I need a left join ?
- what do I do in case of a really large query that has multiple include statements (something to the tune of 20 Includes) ?

The stack trace is the following:
```
System.InvalidOperationException
HResult=0x80131509
Message=Temporal query is trying to use navigation to an entity 'ProductType' which itself doesn't map to temporal table. Either map the entity to temporal table or use join manually to access it.
Source=Microsoft.EntityFrameworkCore.SqlServer
StackTrace:
at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerNavigationExpansionExtensibilityHelper.CreateQueryRoot(IEntityType entityType, QueryRootExpression source)
at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ExpandingExpressionVisitor.ExpandForeignKey(Expression root, EntityReference entityReference, IForeignKey foreignKey, Boolean onDependent, Boolean derivedTypeConversion)
at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ExpandingExpressionVisitor.ExpandNavigation(Expression root, EntityReference entityReference, INavigation navigation, Boolean derivedTypeConversion)
at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.IncludeExpandingExpressionVisitor.ExpandIncludesHelper(Expression root, EntityReference entityReference, INavigationBase previousNavigation)
at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.IncludeExpandingExpressionVisitor.ExpandInclude(Expression root, EntityReference entityReference)
at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.IncludeExpandingExpressionVisitor.VisitExtension(Expression extensionExpression)
at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ExpandingExpressionVisitor.Expand(Expression expression, Boolean applyIncludes)
at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.PendingSelectorExpandingExpressionVisitor.Visit(Expression expression)
at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(Expression query)
at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.IncludableQueryable`2.GetEnumerator()
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at Program.QueryEverythingTemporalAsOf() in D:\Repos\GitHub\TemporalTables\Program.cs:line 182
at Program.Main() in D:\Repos\GitHub\TemporalTables\Program.cs:line 27
```

After looking at the stack trace, I took a look at the source code of efcore [here](https://github.com/dotnet/efcore/blob/v6.0.1/src/EFCore.SqlServer/Query/Internal/SqlServerNavigationExpansionExtensibilityHelper.cs) and searched for where the error message seemed to have originated from.
 I can see that it is looking only for temporal entities.

```C#
public override QueryRootExpression CreateQueryRoot(IEntityType entityType, QueryRootExpression? source)
{
	if (source is TemporalQueryRootExpression)
	{
		if (!entityType.GetRootType().IsTemporal())
		{
			throw new InvalidOperationException(
				SqlServerStrings.TemporalNavigationExpansionBetweenTemporalAndNonTemporal(entityType.DisplayName()));
		}

		if (source is TemporalAsOfQueryRootExpression asOf)
		{
			return source.QueryProvider != null
				? new TemporalAsOfQueryRootExpression(source.QueryProvider, entityType, asOf.PointInTime)
				: new TemporalAsOfQueryRootExpression(entityType, asOf.PointInTime);
		}

		throw new InvalidOperationException(SqlServerStrings.TemporalNavigationExpansionOnlySupportedForAsOf("AsOf"));
	}

	return base.CreateQueryRoot(entityType, source);
}
```

**Comment by ajcvickers** [comment]
@dragos-durlut 

> this should have been supported.

What is it, specifically, that you are saying should be supported?

**Comment by dragos-durlut** [comment]
@ajcvickers 
> What is it, specifically, that you are saying should be supported?

The possibility of using `Include()` and `ThenInclude()` with non-temporal entities when using the `TemporalAsOf` query.

By running my example you should be able to see what I am talking about.

**Comment by ajcvickers** [comment]
@dragos-durlut The exception message is not clear here. I believe it means _all_ the entity types involved need to be mapped to normal (non-termporal) tables.

/cc @maumar

**Comment by dragos-durlut** [comment]
@ajcvickers @maumar 
is there a possibility of replacing `SqlServerNavigationExpansionExtensibilityHelper` with a custom one like below ?
Would someplace else need to be modified ?

```C#
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
	optionsBuilder.ReplaceService<INavigationExpansionExtensibilityHelper, CustomSqlServerNavigationExpansionExtensibilityHelper>();
	base.OnConfiguring(optionsBuilder);
}
```

**Comment by dragos-durlut** [comment]
@ajcvickers @maumar 
I seem to have found a workaround for the time being. This is not fully tested and has not been used in a full production application.

I created the workaround [here] (https://github.com/dragos-durlut/TemporalTables/tree/custom-include) (custom-include branch)
You can see the changes [here](https://github.com/dragos-durlut/TemporalTables/commit/9cb8c2947a9e07f3bdbeacc6acdf79ec5dfc91c0) (commit)


Basically, what I did, was create a custom `SqlServerNavigationExpansionExtensibilityHelper` and replaced the service in the `DbContext`.

It only works if you are using an `AsOf` query.

The generated SQL looks like this:
```SQL
      SELECT [p].[Id], [p].[Name], [p].[PeriodEnd], [p].[PeriodStart], [p].[Price], [p].[ProductTypeId], [p0].[Id], [p1].[Id], [t].[Id], [t].[CustomerId], [t].[OrderDate], [t].[PeriodEnd], [t].[PeriodStart], [t].[ProductId], [t].[Id0], [t].[Name], [t].[PeriodEnd0], [t].[PeriodStart0], [p0].[Name], [p0].[ProductClassId], [p1].[Name]
      FROM [Products] FOR SYSTEM_TIME AS OF '2022-01-24T14:24:27.9295635Z' AS [p]
      INNER JOIN [ProductTypes] AS [p0] ON [p].[ProductTypeId] = [p0].[Id]
      INNER JOIN [ProductClasses] AS [p1] ON [p0].[ProductClassId] = [p1].[Id]
      LEFT JOIN (
          SELECT [o].[Id], [o].[CustomerId], [o].[OrderDate], [o].[PeriodEnd], [o].[PeriodStart], [o].[ProductId], [c].[Id] AS [Id0], [c].[Name], [c].[PeriodEnd] AS [PeriodEnd0], [c].[PeriodStart] AS [PeriodStart0]
          FROM [Orders] FOR SYSTEM_TIME AS OF '2022-01-24T14:24:27.9295635Z' AS [o]
          LEFT JOIN [Customers] FOR SYSTEM_TIME AS OF '2022-01-24T14:24:27.9295635Z' AS [c] ON [o].[CustomerId] = [c].[Id]
      ) AS [t] ON [p].[Id] = [t].[ProductId]
      ORDER BY [p].[Id], [p0].[Id], [p1].[Id], [t].[Id]
```

The custom `SqlServerNavigationExpansionExtensibilityHelper`  has the following changed method:

```C#
public override QueryRootExpression CreateQueryRoot(IEntityType entityType, QueryRootExpression? source)
{
	if (source is TemporalQueryRootExpression)
	{
		if (!entityType.GetRootType().IsTemporal())
		{
			if (source is TemporalAsOfQueryRootExpression asOf1)
			{
#pragma warning disable CS8604 // Possible null reference argument.
				return source.QueryProvider != null ? new QueryRootExpression(source.QueryProvider, entityType) : new QueryRootExpression(entityType);
#pragma warning restore CS8604 // Possible null reference argument.
			}
			throw new InvalidOperationException(
				SqlServerStrings.TemporalNavigationExpansionBetweenTemporalAndNonTemporal(entityType.DisplayName()));
		}

		if (source is TemporalAsOfQueryRootExpression asOf)
		{
			return source.QueryProvider != null
				? new TemporalAsOfQueryRootExpression(source.QueryProvider, entityType, asOf.PointInTime)
				: new TemporalAsOfQueryRootExpression(entityType, asOf.PointInTime);
		}

		throw new InvalidOperationException(SqlServerStrings.TemporalNavigationExpansionOnlySupportedForAsOf("AsOf"));
	}

	return base.CreateQueryRoot(entityType, source);
}
```

**Comment by dragos-durlut** [comment]
I've developed some "test cases" to see if the query holds up to multiple types of queries.

You can see the changes [here](https://github.com/ajcvickers/TemporalTables/commit/67fc200eb3df66d8464fd0b9f67d0a2ae3ed3cc9)

---
```C#
private static void QueryEverythingTemporalAsOf_StartingFromProduct()
{
	using var context = new OrdersContext(log: true);

	var query = context.Products.TemporalAsOf(DateTime.UtcNow)
		.Include(p => p.Orders).ThenInclude(o => o.Customer)
		.Include(p => p.ProductType).ThenInclude(pt => pt.ProductClass);

	var list = query.ToList();
}
```
Generates SQL:
```SQL
SELECT [p].[Id], [p].[Name], [p].[PeriodEnd], [p].[PeriodStart], [p].[Price], [p].[ProductTypeId], [p0].[Id], [p1].[Id], [t].[Id], [t].[CustomerId], [t].[OrderDate], [t].[PeriodEnd], [t].[PeriodStart], [t].[ProductId], [t].[Id0], [t].[Name], [t].[PeriodEnd0], [t].[PeriodStart0], [p0].[Name], [p0].[ProductClassId], [p1].[Name]
FROM [Products] FOR SYSTEM_TIME AS OF '2022-01-24T14:44:44.8974932Z' AS [p]
INNER JOIN [ProductTypes] AS [p0] ON [p].[ProductTypeId] = [p0].[Id]
INNER JOIN [ProductClasses] AS [p1] ON [p0].[ProductClassId] = [p1].[Id]
LEFT JOIN (
  SELECT [o].[Id], [o].[CustomerId], [o].[OrderDate], [o].[PeriodEnd], [o].[PeriodStart], [o].[ProductId], [c].[Id] AS [Id0], [c].[Name], [c].[PeriodEnd] AS [PeriodEnd0], [c].[PeriodStart] AS [PeriodStart0]
  FROM [Orders] FOR SYSTEM_TIME AS OF '2022-01-24T14:44:44.8974932Z' AS [o]
  LEFT JOIN [Customers] FOR SYSTEM_TIME AS OF '2022-01-24T14:44:44.8974932Z' AS [c] ON [o].[CustomerId] = [c].[Id]
) AS [t] ON [p].[Id] = [t].[ProductId]
ORDER BY [p].[Id], [p0].[Id], [p1].[Id], [t].[Id]
```
---
```C#
private static void QueryEverythingTemporalAsOf_StartingFromOrder()
{
	using var context = new OrdersContext(log: true);

	var query = context.Orders.TemporalAsOf(DateTime.UtcNow)
		.Include(o => o.Customer)
		.Include(o=>o.Product).ThenInclude(p => p.ProductType).ThenInclude(pt => pt.ProductClass);

	var list = query.ToList();
}
```
Generates SQL
```SQL
  SELECT [o].[Id], [o].[CustomerId], [o].[OrderDate], [o].[PeriodEnd], [o].[PeriodStart], [o].[ProductId], [c].[Id], [c].[Name], [c].[PeriodEnd], [c].[PeriodStart], [p].[Id], [p].[Name], [p].[PeriodEnd], [p].[PeriodStart], [p].[Price], [p].[ProductTypeId], [p0].[Id], [p0].[Name], [p0].[ProductClassId], [p1].[Id], [p1].[Name]
FROM [Orders] FOR SYSTEM_TIME AS OF '2022-01-24T14:41:52.6179984Z' AS [o]
LEFT JOIN [Customers] FOR SYSTEM_TIME AS OF '2022-01-24T14:41:52.6179984Z' AS [c] ON [o].[CustomerId] = [c].[Id]
LEFT JOIN [Products] FOR SYSTEM_TIME AS OF '2022-01-24T14:41:52.6179984Z' AS [p] ON [o].[ProductId] = [p].[Id]
LEFT JOIN [ProductTypes] AS [p0] ON [p].[ProductTypeId] = [p0].[Id]
LEFT JOIN [ProductClasses] AS [p1] ON [p0].[ProductClassId] = [p1].[Id]
```
---
```C#
private static void QueryEverythingTemporalAsOf_StartingFromCustomer()
{
	using var context = new OrdersContext(log: true);

	var query = context.Customers.TemporalAsOf(DateTime.UtcNow)
		.Include(c => c.Orders).ThenInclude(o => o.Product).ThenInclude(p => p.ProductType).ThenInclude(pt => pt.ProductClass);
	var list = query.ToList();
}
```
Generates SQL
```SQL
SELECT [c].[Id], [c].[Name], [c].[PeriodEnd], [c].[PeriodStart], [t].[Id], [t].[CustomerId], [t].[OrderDate], [t].[PeriodEnd], [t].[PeriodStart], [t].[ProductId], [t].[Id0], [t].[Name], [t].[PeriodEnd0], [t].[PeriodStart0], [t].[Price], [t].[ProductTypeId], [t].[Id1], [t].[Name0], [t].[ProductClassId], [t].[Id2], [t].[Name1]
FROM [Customers] FOR SYSTEM_TIME AS OF '2022-01-24T14:44:44.9528535Z' AS [c]
LEFT JOIN (
  SELECT [o].[Id], [o].[CustomerId], [o].[OrderDate], [o].[PeriodEnd], [o].[PeriodStart], [o].[ProductId], [p].[Id] AS [Id0], [p].[Name], [p].[PeriodEnd] AS [PeriodEnd0], [p].[PeriodStart] AS [PeriodStart0], [p].[Price], [p].[ProductTypeId], [p0].[Id] AS [Id1], [p0].[Name] AS [Name0], [p0].[ProductClassId], [p1].[Id] AS [Id2], [p1].[Name] AS [Name1]
  FROM [Orders] FOR SYSTEM_TIME AS OF '2022-01-24T14:44:44.9528535Z' AS [o]
  LEFT JOIN [Products] FOR SYSTEM_TIME AS OF '2022-01-24T14:44:44.9528535Z' AS [p] ON [o].[ProductId] = [p].[Id]
  LEFT JOIN [ProductTypes] AS [p0] ON [p].[ProductTypeId] = [p0].[Id]
  LEFT JOIN [ProductClasses] AS [p1] ON [p0].[ProductClassId] = [p1].[Id]
) AS [t] ON [c].[Id] = [t].[CustomerId]
ORDER BY [c].[Id], [t].[Id], [t].[Id0], [t].[Id1]
```

**Comment by dragos-durlut** [comment]
Just tested this solution on an enterprise solution and generated 100+ SQL lines with `SingleQuery` enabled and 300+ SQL lines with `SplitQuery` enabled.

**Comment by dragos-durlut** [comment]
I want to leave this open until I get a reply from either @ajcvickers or @maumar.
Not sure if this is working as intended.
The fix seems super simple.

**Comment by maumar** [comment]
should be doable for AsOf operation

**Comment by dragos-durlut** [comment]
> I used the fix ([#27259 (comment)](https://github.com/dotnet/efcore/issues/27259#issuecomment-1020167204)) of @dragos-durlut for more than a year in a large solution (which also runs in production). Now I am migrating from EF6 to EF7 and because of commit [1ca6380](https://github.com/dotnet/efcore/commit/1ca63809296063c7e771cfdb6c61c57b9c28aa93) the orignal fix doesn't work anymore.
> 
> I changed the code of the custom `SqlServerNavigationExpansionExtensibilityHelper` and [created a gist for it](https://gist.github.com/ArnaudB88/e0b2b18d92cc8d8f8f5cde77e0a03e42). I also added support for expanding FromTo temporal queries to non-temporal entities.
> 
> This gist should work with EF7 (and possibly with EF8). I hope this will help some people untill it is added to the code of EfCore.

I will migrate to EfCore 8 in about a month.

I will keep you posted regarding this issue.

Thank you for your help!

**Comment by dragos-durlut** [comment]
> I used the fix ([#27259 (comment)](https://github.com/dotnet/efcore/issues/27259#issuecomment-1020167204)) of @dragos-durlut for more than a year in a large solution (which also runs in production). Now I am migrating from EF6 to EF7 and because of commit [1ca6380](https://github.com/dotnet/efcore/commit/1ca63809296063c7e771cfdb6c61c57b9c28aa93) the orignal fix doesn't work anymore.
> 
> I changed the code of the custom `SqlServerNavigationExpansionExtensibilityHelper` and [created a gist for it](https://gist.github.com/ArnaudB88/e0b2b18d92cc8d8f8f5cde77e0a03e42). I also added support for expanding FromTo temporal queries to non-temporal entities.
> 
> This gist should work with EF7 (and possibly with EF8). I hope this will help some people until it is added to the code of EfCore.

@ArnaudB88 I have begun upgrading to EFCore 8.0.1

At first glance, your code works on my test repo, branch `custom-include`
https://github.com/dragos-durlut/TemporalTables/commits/custom-include/

I will keep you posted as I move my code into the main application.

**Comment by ArnaudB88** [comment]
Hi @roji , are there any plans on implementing this?
The needed code can be found in the gist (mentioned above).

Thanks!

**Comment by dragos-durlut** [comment]
This workaround still works in **NET10.0**.

I have done a small upgrade [here](https://github.com/dragos-durlut/TemporalTables/commit/986ffacac574474f8bac357c64850e85863bba76)
