### ISSUE TITLE
EF Core 6.0 cannot traslate DateTime .Date to SQL

### ISSUE THREAD

**Issue by harmankaurflynn** [dotnet/efcore#27448]
```C# code
var results =  _context.ResultTable.Where(ea => ea.CrtdDateTime.Date == crtdDateTime.Date ).ToList();;
```
throws exception 
```
Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.ProcessNullNotNull(SqlUnaryExpression sqlUnaryExpression, Boolean operandNullable)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.RewriteNullSemantics(SqlBinaryExpression sqlBinaryExpression, SqlExpression left, SqlExpression right, Boolean leftNullable, Boolean rightNullable, Boolean optimize, Boolean& nullable)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.VisitSqlBinary(SqlBinaryExpression sqlBinaryExpression, Boolean allowOptimizedExpansion, Boolean& nullable)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.Visit(SqlExpression sqlExpression, Boolean allowOptimizedExpansion, Boolean preserveColumnNullabilityInformation, Boolean& nullable)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.VisitSqlBinary(SqlBinaryExpression sqlBinaryExpression, Boolean allowOptimizedExpansion, Boolean& nullable)

The where clause (ea.CrtdDateTime.Date == crtdDateTime.Date) causes this exception.
It doesn't convert this query to SQL. Same issue occurs with DateTime .Month, .Year.
I couldn't find any equivalent method in EF.Functions.
Anything else I try like adding DatePartt equivalent etc gives error Unable to cast object of type 'NotTranslatedExpressionType' to type 'Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlExpression'.



EF Core version: EF Core 6.0.2
Database provider:  MySQL.EntityFrameworkCore
Target framework:  .NET 6.0
Operating system:
IDE: (e.g. Visual Studio 2022 16.3)

**Comment by roji** [comment]
@harmankaurflynn I can see this working fine with the simple code sample below - please take a look. Can you please either submit a runnable code sample, or tweak the below so that it fails as above?

<details>
<summary>Attempted repro</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

var crtdDateTime = new DateTime(2022, 1, 1);
_ =  ctx.ResultTable.Where(ea => ea.CrtdDateTime.Date == crtdDateTime.Date ).ToList();;

public class BlogContext : DbContext
{
    public DbSet<ResultTable> ResultTable { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class ResultTable
{
    public int Id { get; set; }
    public DateTime CrtdDateTime { get; set; }
}
```

</details>

**Comment by harmankaurflynn** [comment]
@roji  sorry, i Just updated description. Backend is MySQL Version 5.6.10

**Comment by roji** [comment]
@harmankaurflynn this is something you should report to the maintainers of the MySQL provider - it's most likely a bug in the provider (as you can see, this works fine on SQL Server).

**Comment by jack-liew** [comment]
> @harmankaurflynn这是您应该向 MySQL 提供程序的维护人员报告的内容 - 这很可能是提供程序中的一个错误（如您所见，这在 SQL Server 上运行良好）。

you wrong, This problem is caused by EFcore, not mysql itself or the driver

**Comment by roji** [comment]
@jack-liew can you provide more details on why you think so? Note that your code above does work fine on SQL Server (see code below).

Translation of methods and members (such as DateTime.Date) inside LINQ queries are the responsibility of each EF Core provider, since translations are different across databases. It's likely that the MySQL EF provider you're using has some translation bug.

<details>
<summary>Working code with SQL Server</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

var crtdDateTime = DateTime.Now;
var results = ctx.ResultTable.Where(ea => ea.CrtdDateTime.Date == crtdDateTime.Date ).ToList();;

public class BlogContext : DbContext
{
    public DbSet<ResultTable> ResultTable { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class ResultTable
{
    public int Id { get; set; }
    public DateTime CrtdDateTime { get; set; }
}
```

</details.

**Comment by ErikEJ** [comment]
Many users seem happy with the Pomelo provider
