### ISSUE TITLE
Regression in Compiled-Query-Cache

### ISSUE THREAD

**Issue by flensrocker** [dotnet/efcore#27443]
I have a `WhereAny` extension, which builds an expression to combine multiple clauses with `OR`.

```c#
public static class QueryableExtensions
{
  public static IQueryable<TEntity> WhereAny<TEntity, TValue>(
    this IQueryable<TEntity> source,
    IEnumerable<TValue> values,
    Expression<Func<TEntity, TValue, bool>> match)
  {
    var parameter = match.Parameters[0];
    var body = values
      .Select(value => Expression.Constant(value, typeof(TValue)))
      .Select(value => Expression.Invoke(match, parameter, value))
      .Aggregate<Expression>(Expression.OrElse);
    var predicate = Expression.Lambda<Func<TEntity, bool>>(body, parameter);
    return source.Where(predicate);
  }
}
```

This works on the first time it gets called, but throws on the second query.

This used to work with EF Core 3.1.22, but throws on 6.0.2 (and 5.0.14)

A full code sample is at the end of this issue.

```
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: e
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Microsoft.EntityFrameworkCore.Query.ExpressionEqualityComparer.ExpressionComparer.CompareLambda(LambdaExpression a, LambdaExpression b)
   at Microsoft.EntityFrameworkCore.Query.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression left, Expression right)
   at Microsoft.EntityFrameworkCore.Query.ExpressionEqualityComparer.ExpressionComparer.CompareInvocation(InvocationExpression a, InvocationExpression b)
   at Microsoft.EntityFrameworkCore.Query.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression left, Expression right)
   at Microsoft.EntityFrameworkCore.Query.ExpressionEqualityComparer.ExpressionComparer.CompareBinary(BinaryExpression a, BinaryExpression b)
   at Microsoft.EntityFrameworkCore.Query.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression left, Expression right)
   at Microsoft.EntityFrameworkCore.Query.ExpressionEqualityComparer.ExpressionComparer.CompareBinary(BinaryExpression a, BinaryExpression b)
   at Microsoft.EntityFrameworkCore.Query.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression left, Expression right)
   at Microsoft.EntityFrameworkCore.Query.ExpressionEqualityComparer.ExpressionComparer.CompareLambda(LambdaExpression a, LambdaExpression b)
   at Microsoft.EntityFrameworkCore.Query.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression left, Expression right)
   at Microsoft.EntityFrameworkCore.Query.ExpressionEqualityComparer.ExpressionComparer.CompareUnary(UnaryExpression a, UnaryExpression b)
   at Microsoft.EntityFrameworkCore.Query.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression left, Expression right)
   at Microsoft.EntityFrameworkCore.Query.ExpressionEqualityComparer.ExpressionComparer.CompareExpressionList(IReadOnlyList`1 a, IReadOnlyList`1 b)
   at Microsoft.EntityFrameworkCore.Query.ExpressionEqualityComparer.ExpressionComparer.CompareMethodCall(MethodCallExpression a, MethodCallExpression b)
   at Microsoft.EntityFrameworkCore.Query.ExpressionEqualityComparer.ExpressionComparer.Compare(Expression left, Expression right)
   at Microsoft.EntityFrameworkCore.Query.ExpressionEqualityComparer.Equals(Expression x, Expression y)
   at Microsoft.EntityFrameworkCore.Query.CompiledQueryCacheKeyGenerator.CompiledQueryCacheKey.Equals(CompiledQueryCacheKey other)
   at Microsoft.EntityFrameworkCore.Query.RelationalCompiledQueryCacheKeyGenerator.RelationalCompiledQueryCacheKey.Equals(RelationalCompiledQueryCacheKey other)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerCompiledQueryCacheKeyGenerator.SqlServerCompiledQueryCacheKey.Equals(SqlServerCompiledQueryCacheKey other)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerCompiledQueryCacheKeyGenerator.SqlServerCompiledQueryCacheKey.Equals(Object obj)
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.Extensions.Caching.Memory.MemoryCache.TryGetValue(Object key, Object& result)
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.TryGetValue[TItem](IMemoryCache cache, Object key, TItem& value)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\src\xtern\efcore-issue\Program.cs:line 24
   at Program.<Main>(String[] args)
```

### Include provider and version information

EF Core version: 6.0.2 (and 5.0.14)
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0 (and .NET 5.0)
Operating system: Windows
IDE: Visual Studio 2022 17.0.6 and dotnet commandline

```c#
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;

var theDbOptions = new DbContextOptionsBuilder<TheDbContext>()
  .UseSqlServer("Server=(localdb)\\MSSQLLocalDB;Database=EFCoreIssue27443")
  .Options;

Console.WriteLine("re-create database");

using (var dbContext = new TheDbContext(theDbOptions))
{
  await dbContext.Database.EnsureDeletedAsync();
  await dbContext.Database.EnsureCreatedAsync();
}

var searchTerms = new[] { "one%", "two%", "three%" };

for (var i = 1; i <= 2; i++)
{
  Console.WriteLine($"{i}. query starts");

  using (var dbContext = new TheDbContext(theDbOptions))
  {
    var result = await dbContext.TheEntity
      .WhereAny(searchTerms, (e, s) => EF.Functions.Like(e.Name, s))
      .ToArrayAsync();
  }

  Console.WriteLine($"{i}. query ends");
}

public class TheEntity
{
  public Guid Id { get; set; }
  public string Name { get; set; } = null!;
}

public class TheDbContext : DbContext
{
  public DbSet<TheEntity> TheEntity { get; set; } = null!;

  public TheDbContext(DbContextOptions<TheDbContext> dbOptions)
    : base(dbOptions)
  {
  }
}

public static class QueryableExtensions
{
  public static IQueryable<TEntity> WhereAny<TEntity, TValue>(
    this IQueryable<TEntity> source,
    IEnumerable<TValue> values,
    Expression<Func<TEntity, TValue, bool>> match)
  {
    var parameter = match.Parameters[0];
    var body = values
      .Select(value => Expression.Constant(value, typeof(TValue)))
      .Select(value => Expression.Invoke(match, parameter, value))
      .Aggregate<Expression>(Expression.OrElse);
    var predicate = Expression.Lambda<Func<TEntity, bool>>(body, parameter);
    return source.Where(predicate);
  }
}
```

The project file:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>efcore_issue_27443</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.2" />
  </ItemGroup>

</Project>
```

**Comment by roji** [comment]
@flensrocker this happens because you are using the same ParameterExpression instance both in each of the lambdas you imbed in the Where clause, and as the parameter for the Where lambda itself - AFAIK this is an incorrect expression tree structure. You can make the code work by creating a new parameter for the Where lambda:

```c#
var parameter = Expression.Parameter(match.Parameters[0].Type);
```

This still leaves the same parameter instance being used by the included lambdas; this doesn't trigger a problem, but is probably not a good idea.

To create a fully correct expression tree, identical to what the compiler itself would produce, you can extract the MethodCallExpression out of the match function, and use a visitor to replace the parameter expression with the provided constant (each time different). This would be more verbose, but probably safer/more correct.

Will leave open for @smitpatel/@maumar to decide whether we need to make any changes in our ExpressionEqualityComparer to accomodate for this problematic structure (or throw a clearer exception).

**Comment by flensrocker** [comment]
Thank you! I will try to wrap my head around this "expression magic", so I get a valid expression tree.

**Comment by flensrocker** [comment]
This is the way I generate the expression and that works. Thank you!

```c#
public static class QueryableExtensions
{
  private class WhereAnyVisitor<TEntity, TValue> : ExpressionVisitor
  {
    private readonly ParameterExpression _parameter;
    private readonly TValue _value;

    internal WhereAnyVisitor(ParameterExpression parameter, TValue value)
    {
      _parameter = parameter;
      _value = value;
    }

    protected override Expression VisitParameter(ParameterExpression node)
    {
      if (node.Type == typeof(TEntity))
        return _parameter;

      if (node.Type == typeof(TValue))
        return Expression.Constant(_value, typeof(TValue));

      return base.VisitParameter(node);
    }
  }

  public static IQueryable<TEntity> WhereAny<TEntity, TValue>(
    this IQueryable<TEntity> source,
    IEnumerable<TValue> values,
    Expression<Func<TEntity, TValue, bool>> match)
  {
    var whereParameter = Expression.Parameter(match.Parameters[0].Type);
    var body = values
      .Select(value =>
      {
        var parameter = Expression.Parameter(match.Parameters[0].Type);
        var matchValueBody = new WhereAnyVisitor<TEntity, TValue>(parameter, value).Visit(match.Body);
        var matchValue = Expression.Lambda<Func<TEntity, bool>>(matchValueBody, parameter);
        return Expression.Invoke(matchValue, whereParameter);
      })
      .Aggregate<Expression>(Expression.OrElse);
    var predicate = Expression.Lambda<Func<TEntity, bool>>(body, whereParameter);
    return source.Where(predicate);
  }
}
```

**Comment by roji** [comment]
@flensrocker great that you could make it work.

Note that there's no need to integrate Lambda and Invoke in your Where predicate - you can simply embed the contained MethodCallExpressions directly, which is how the simple expression tree would look like if the compiler generated it. It's a good idea to look at actual expression trees generated by the compiler when working on expression trees.

**Comment by flensrocker** [comment]
Thank you for your input. I will give it a try tomorrow!

And yes, expression trees are weird and fascinating, but documentation is a bit sparse, when you really want to dig deeper. A lot of trial and error.

**Comment by flensrocker** [comment]
@roji Thanks again, I was able to trim it down to what I think you meant:

```c#
public static class QueryableExtensions
{
  private class WhereAnyVisitor<TEntity, TValue> : ExpressionVisitor
  {
    private readonly ParameterExpression _parameter;
    private readonly TValue _value;

    internal WhereAnyVisitor(ParameterExpression parameter, TValue value)
    {
      _parameter = parameter;
      _value = value;
    }

    protected override Expression VisitParameter(ParameterExpression node)
    {
      if (node.Type == typeof(TEntity))
        return _parameter;

      if (node.Type == typeof(TValue))
        return Expression.Constant(_value, typeof(TValue));

      return base.VisitParameter(node);
    }
  }

  public static IQueryable<TEntity> WhereAny<TEntity, TValue>(
    this IQueryable<TEntity> source,
    IEnumerable<TValue> values,
    Expression<Func<TEntity, TValue, bool>> match)
  {
    var whereParameter = Expression.Parameter(match.Parameters[0].Type);
    var body = values
      .Select(value => new WhereAnyVisitor<TEntity, TValue>(whereParameter, value).Visit(match.Body))
      .Aggregate(Expression.OrElse);
    var predicate = Expression.Lambda<Func<TEntity, bool>>(body, whereParameter);
    return source.Where(predicate);
  }
}
```

At least this is what makes sense to me and expressions have lost another seal for me... 😎

**Comment by roji** [comment]
For triage: leaving open for @smitpatel / @maumar to decide whether we need to make any changes in our ExpressionEqualityComparer to accomodate for this problematic structure (or throw a clearer exception).

**Comment by ajcvickers** [comment]
Note from triage: since this is not a compiler-generated structure we are not going to add specific support for it.
