### ISSUE TITLE
Errormessages already contain the exception with the stacktrace.

### ISSUE THREAD

**Issue by qsdfplkj** [dotnet/efcore#27465]
I find my logs to be logging the exception twice. Once as the exception and once inside the message that contains the same exception. This pollutes our logging.

This looks similar as to calling _logger.LogError(ex, $"Something went wrong.{NewLine}{ex}");   // NOTE: the extra {ex}

Where I would suggest to log it like _logger.LogError(ex, "Something went wrong."); and let the loggers decide how to log the exception with or without nested messages and stacktrace.

In think the root of my question is Microsoft.EntityFrameworkCore.Diagnostics.Corestrings where the errors that are logged already contain the exception as a string. 

The message of the exception looks like where the first line should be the message and the exception should be logged independent of the message. Is there any way to change this behavior? Maybe DbContextLoggerOptions using a flag OnlyMessageNoException (but I'm still using ef 5.0 though...):

```
An exception occurred in the database while saving changes for context type 'DbContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert explicit value for identity column in table 'ImportedFiles' when IDENTITY_INSERT is set to OFF.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
ClientConnectionId:36e475ef-b7fd-4b6e-9c7c-67b99e636b6c
Error Number:544,State:1,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
```

**Comment by roji** [comment]
@qsdfplkj that particular message does not include the exception in its message ([source for 5.0](https://github.com/dotnet/efcore/blob/v5.0.14/src/EFCore.Relational/Properties/RelationalStrings.resx#L779)); it's likely your logger who's outputting the exception.

Can you please double-check this, and if you still think there's a problem, submit a minimal code sample showing the exception getting outputted in the message (or twice)?

**Comment by qsdfplkj** [comment]
I intercepted it in a custom loggerfactory. I'm pretty sure it's not other errors are logged correctly only efcore errors have this issue.
From the state variable in the ILogger that I intercepted I see: An exception occurred in the database while saving changes for context type '{contextType}'.{newline}{error}
![image](https://user-images.githubusercontent.com/35060463/154518493-af1f3c22-5a44-4565-bc02-b3caa56b0d05.png)

**Comment by roji** [comment]
@qsdfplkj my bad, I looked at the wrong resource - yes, [LogExceptionDuringSaveChanges](https://github.com/dotnet/efcore/blob/v5.0.14/src/EFCore/Properties/CoreStrings.resx#L735) indeed includes the exception in the message.

I know we've discussed this before several times but no longer remember the guiding principles - @ajcvickers?
