### ISSUE TITLE
Projection of entity with nullable struct fails on ternary operator (efcore 6 breaking change)

### ISSUE THREAD

**Issue by OndrejVrsan** [dotnet/efcore#27561]
_This is breaking change between efcore 5 and efcore 6._

I have following entity model with nullable decimal with following mapping projection expression to business model.

When mapping expression has condition `NullableDecimal != null`, the query fails with `System.InvalidOperationException: Nullable object must have a value.`

When mapping expression has condition `NullableDecimal.HasValue`, the query works as expected.

### Entity Model
```C#
public class FooEntity
{
    public int Id { get; set; }
    public List<BarEntity> Bars { get; set; } = new();
}

public class BarEntity
{
    public int Id { get; set; }
    public decimal? NullableDecimal { get; set; }
}
```

### Business Model
```C#
public class BarModel
{
    public int Id { get; }
    public ValueWrapper? Wrapper { get; }

    public BarModel(int id, ValueWrapper? wrapper)
    {
        Id = id;
        Wrapper = wrapper;
    }
}

public class ValueWrapper
{
    public decimal Value { get; }

    public ValueWrapper(decimal value)
    {
        Value = value;
    }
}
```

### Mapper
```C#
public static class Mapper
{
    public static Expression<Func<BarEntity, BarModel>> MapToModel
        => efEntity
            => new BarModel(
                efEntity.Id,
                //efEntity.NullableDecimal.HasValue // works in both EF Core 5 and EF Core 6
                efEntity.NullableDecimal != null    // works in EF Core 5; DOES NOT WORK in EF Core 6
                    ? new ValueWrapper(efEntity.NullableDecimal.Value)
                    : null);
}
```

### DbContext
```C#
public class MyDbContext : DbContext
{
    public DbSet<FooEntity> Foos { get; set; } = null!;
    public DbSet<BarEntity> Bars { get; set; } = null!;

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Server=(LocalDB)\MSSqlLocalDb;Database=EFCoreTest;Trusted_Connection=True");
    }
}
```

### Program
```C#
await using (var db = new MyDbContext())
{
    // Cleanup
    db.Bars.RemoveRange(db.Bars);
    db.Foos.RemoveRange(db.Foos);
    await db.SaveChangesAsync();

    // Add test data
    db.Foos.Add(new FooEntity { Bars = { new BarEntity() } });
    db.Foos.Add(new FooEntity { Bars = { new BarEntity() { NullableDecimal = 1M } } });
    await db.SaveChangesAsync();
}

await using (var db = new MyDbContext())
{
    var bars = await db.Foos
        .Select(x => x.Bars.First())
        .Select(Mapper.MapToModel)
        .ToListAsync();

    foreach (var bar in bars)
    {
        Console.WriteLine($"Bar Id={bar.Id} ValueWrapper={bar.Wrapper?.Value.ToString() ?? "(null)"}");
    }
}
```

### Run Program - query fails on projection

```
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'EfCore6.HasValueVsNotNull.MyDbContext'.
      System.InvalidOperationException: Nullable object must have a value.
         at lambda_method70(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
      System.InvalidOperationException: Nullable object must have a value.
         at lambda_method70(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
Unhandled exception. System.InvalidOperationException: Nullable object must have a value.
   at lambda_method70(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\git\sandbox\EfCore6.HasValueVsNotNull\Program.cs:line 19
   at Program.<Main>$(String[] args) in C:\git\sandbox\EfCore6.HasValueVsNotNull\Program.cs:line 28
   at Program.<Main>(String[] args)
```

# Produced EF Core 5 & EF Core 6 queries with different projection conditions
Below are produced queries, hope it helps to find the root cause why EF Core 6 with `NullableDecimal != null` fails...

### ✅ EF Core 5 query with `efEntity.NullableDecimal.HasValue` condition
```sql
info: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT (
          SELECT TOP(1) [b].[Id]
          FROM [Bars] AS [b]
          WHERE [f].[Id] = [b].[FooEntityId]), (
          SELECT TOP(1) CASE
              WHEN [b0].[NullableDecimal] IS NOT NULL THEN CAST(1 AS bit)
              ELSE CAST(0 AS bit)
          END
          FROM [Bars] AS [b0]
          WHERE [f].[Id] = [b0].[FooEntityId]), (
          SELECT TOP(1) [b1].[NullableDecimal]
          FROM [Bars] AS [b1]
          WHERE [f].[Id] = [b1].[FooEntityId])
      FROM [Foos] AS [f]
```

### ✅ EF Core 5 query with `efEntity.NullableDecimal != null` condition
```sql
info: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT (
          SELECT TOP(1) [b].[Id]
          FROM [Bars] AS [b]
          WHERE [f].[Id] = [b].[FooEntityId]), CASE
          WHEN (
              SELECT TOP(1) [b0].[NullableDecimal]
              FROM [Bars] AS [b0]
              WHERE [f].[Id] = [b0].[FooEntityId]) IS NOT NULL THEN CAST(1 AS bit)
          ELSE CAST(0 AS bit)
      END, (
          SELECT TOP(1) [b1].[NullableDecimal]
          FROM [Bars] AS [b1]
          WHERE [f].[Id] = [b1].[FooEntityId])
      FROM [Foos] AS [f]
```

### ✅ EF Core 6 query with `efEntity.NullableDecimal.HasValue` condition
```sql
info: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT (
          SELECT TOP(1) [b].[Id]
          FROM [Bars] AS [b]
          WHERE [f].[Id] = [b].[FooEntityId]), (
          SELECT TOP(1) CASE
              WHEN [b0].[NullableDecimal] IS NOT NULL THEN CAST(1 AS bit)
              ELSE CAST(0 AS bit)
          END
          FROM [Bars] AS [b0]
          WHERE [f].[Id] = [b0].[FooEntityId]), (
          SELECT TOP(1) [b1].[NullableDecimal]
          FROM [Bars] AS [b1]
          WHERE [f].[Id] = [b1].[FooEntityId])
      FROM [Foos] AS [f]
```

### ⛔ EF Core 6 query with `efEntity.NullableDecimal != null` condition
_Projection fails with `System.InvalidOperationException: Nullable object must have a value.` described above._
```sql
info: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT (
          SELECT TOP(1) [b].[Id]
          FROM [Bars] AS [b]
          WHERE [f].[Id] = [b].[FooEntityId]), CASE
          WHEN EXISTS (
              SELECT 1
              FROM [Bars] AS [b0]
              WHERE [f].[Id] = [b0].[FooEntityId]) THEN CAST(1 AS bit)
          ELSE CAST(0 AS bit)
      END, (
          SELECT TOP(1) [b1].[NullableDecimal]
          FROM [Bars] AS [b1]
          WHERE [f].[Id] = [b1].[FooEntityId])
      FROM [Foos] AS [f]
```
### Provider and version information
EF Core version: 6.0.2 
Database provider: Microsoft.EntityFrameworkCore.SqlServer 
Target framework: .NET 6.0 
Nullability: enabled 
Operating system: Win11 21H2 22000.493
IDE: Visual Studio 2022 17.1 Preview 6.0

**Comment by maumar** [comment]
works in current main

**Comment by maumar** [comment]
@OndrejVrsan this should start working in next patch (6.0.3)
