### ISSUE TITLE
Proper way to seed test data in EF Core 6.0.2

### ISSUE THREAD

**Issue by Stadzior** [dotnet/efcore#27599]
Hi,
I'm developing an WPF desktop app in .NET6 and I'm using EFCore 6.x to deal with ORM to our MSSQL database.
In my previous project I've used EF6 and I was using "update-database" command to both regenerate the model (db scheme) and seed test data like so:

MyDbContext.cs
```C#
    public class MyDbContext : DbContext
    {
        public MyDbContext(string nameOrConnectionString)
            : base(nameOrConnectionString)
        {        
            Database.SetInitializer(new CreateDatabaseIfNotExists<MyDbContext>());
            Database.CommandTimeout = 900;
        }

        public virtual IDbSet<Foo> Foos { get; set; }
        public virtual IDbSet<Bar> Bars { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Configurations.Add(new FooConfiguration());
            modelBuilder.Configurations.Add(new BarConfiguration());
        }
```

Foo.cs
```C#
    public class Foo
    {         
        public int Id { get; set; }
        public string Name { get; set; }
        public int BarId { get; set; }
        public Bar Bar { get; set; }
    }
```

FooConfiguration.cs
```C#
    public class FooConfiguration : EntityTypeConfiguration<Foo>
    {
        public AddressConfiguration()
        {
            ToTable("Foo");

            HasKey(e => e.Id);

            Property(e => e.Name)
                .HasMaxLength(50);

            HasRequired(e => e.Bar)
                .WithMany(e => e.Foos)
                .HasForeignKey(e => e.BarId)
                .WillCascadeOnDelete(false);
        }
    }
```

Bar.cs
```C#
    public class Bar
    {         
        public int Id { get; set; }
        public string Name { get; set; }
        public IEnumerable<Foo> Foos { get; set; }
    }
```

BarConfiguration.cs
```C#
    public class BarConfiguration : EntityTypeConfiguration<Bar>
    {
        public AddressConfiguration()
        {
            ToTable("Bar");

            HasKey(e => e.Id);

            Property(e => e.Name)
                .HasMaxLength(50);
        }
    }
```

Configuration.cs
```C#
    public class Configuration : DbMigrationsConfiguration<MyDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
            ContextKey = "MyDbContext";
        }

        protected override void Seed(MyDbContext context)
        { 
            context.Bars.Add(new Bar { Id = 1, Name = "Bar1" });         
            context.Foos.Add(new Foo { Id = 1, Name = "Foo1", BarId = 1 });
            context.Foos.Add(new Foo { Id = 2, Name = "Foo2", BarId = 1 });
            context.SaveChanges();
        }
```

I am struggling to get the similar thing in EFCore. I know "update-database" is likewise usable in EFCore but the main problem is that the model creating and data seeding from OnModelCreating method is triggered also everytime I start my app which I personally find as a burden.
I'd like to use it just like in EF6 the "update-database" method to do the model generation and data seeding. 

I've tried the following approaches (I'll skip the code for EF Core, it is implemented just as in the docs article, nothing really gives the context here):
1. Used .HasData() in OnModelCreating approach described in the [documentation](https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding).
2. [Custom Initialization Logic](https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding#custom-initialization-logic) in App.xaml.cs (which is considered a "Startup.cs" for the WPF app in our approach, all DI registrations goes there etc.).
3. Creating an external MSSQL script to seed the data and place it in OnModelCreating (honestly that was a desperate measure, not very different from option 1).

The only thing that is now possibly working is to execute an external MSSQL script from option 3 and execute it externally by itself which sounds really inconvenient.
Please let me know if there is a way to recreate model & seed the data on demand with the use of "update-database" and prevent it from happening on every app start, and if that is somehow considered an anti-pattern and there is a better way please give me some guidance on that.

Thanks a lot,
Kamil

EF Core version: 6.0.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Visual Studio 2022

**Comment by roji** [comment]
@Stadzior HasData should indeed work fine for seeding data in EF Core (though make sure to understand the [limitations](https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding#limitations-of-model-seed-data)). 

> the main problem is that the model creating and data seeding from OnModelCreating method is triggered also everytime I start my app which I personally find as a burden.

What exactly is the problem you're seeing here? EF Core indeed generally builds the model on app startup, but that in itself  doesn't do anything to the database; it's just a pure in-memory process. Can you elaborate on your reason for not wanting to use HasData?

**Comment by Stadzior** [comment]
@roji thanks for your question. 
The main reason is that I need to inject also many to many relations in seeds hence ".HasData" is unusable.
But even if I'd skip the many to many relations (as in the example given in the question) and use ".HasData" it will still be invoked everytime I open my app because it is used in OnModelCreating method like this in EFCore:

MyDbContext.cs
```C#
    public class MyDbContext : DbContext
    {
        public virtual IDbSet<Foo> Foos { get; set; }
        public virtual IDbSet<Bar> Bars { get; set; }
        
        public MyDbContext(DbContextOptions<MyDbContext> options) : base(options) { }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Configurations.Add(new FooConfiguration());
            modelBuilder.Configurations.Add(new BarConfiguration());
            Configuration.Seed();
        }
    }
```

Configuration.cs
```C#
public static class Configuration
{
    public static void Seed(ModelBuilder modelBuilder)
    {
        modelBuilder
            .Entity<Bar>()
            .HasData(
                new Bar { Id = 1, Name = "Bar1" }
            );   
        modelBuilder
            .Entity<Bar>()
            .HasData(
                new Foo { Id = 1, Name = "Foo1", BarId = 1 },
                new Foo { Id = 2, Name = "Foo2", BarId = 1 }
            );   
    }
}
```

And as soon as MyDbContext is used this OnModelCreating is invoked. I want to prevent it and invoke "Configuration.Seed()" ONLY when I execute "update-database" command.

**Comment by roji** [comment]
> The main reason is that I need to inject also many to many relations in seeds hence ".HasData" is unusable.

It's true that HasData has some limitations; if you model many-to-many relations with an explicit join entity, you can explicitly specify the foreign keys and make this work (see #10000). But it indeed isn't ideal.

For cases where HasData doesn't work well, we do recommend doing your own custom seeding - [see the docs](https://github.com/dotnet/efcore/issues/10000https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding#custom-initialization-logic) (this is also much better if you're managing large amounts of data). At that point you control exactly when seeding is invoked etc.

> But even if I'd skip the many to many relations (as in the example given in the question) and use ".HasData" it will still be invoked everytime I open my app because it is used in OnModelCreating method like this in EFCore:

I still don't understand what the problem is... Yes, Configuration.Seed() gets called every time your application starts, but all it does is configure your model with the seeding data - nothing is done to the database. HasData() is no different from any other configuration you may have in your OnModelCreating, e.g. when you configure some property in some way. The configuration done by HasData() only comes into play when you generate a new migration (with Add-Migration), and then apply that migration to a datbase (with Update-Database).

So your code above looks fine to me. If you see something problematic happen when you start your application, you may have some other code you're not posting here; in that case, please post a full, runnable console program which demonstrates the problem you're having.

**Comment by Stadzior** [comment]
Ok, I'll prepare the runnable demo for you. Stay put.

**Comment by Stadzior** [comment]
Ok @roji so there you have the code of the demo:
https://github.com/Stadzior/EFCoreDemo

Repro steps on VS2022:
1. Make sure that you have a working MSSQL database instance (you can manipulate the conn string in appsettings.json as you see fit).
2. Open Package Manager Console in VS.
3. Type in "update-database" and hit enter.
4. Now you should have the scheme created and seeds produced and inserted into the "FooBar" database.
5. Now place the breakpoint in EFCoreDemo.Data.Migration.Configuration like so: ![obraz](https://user-images.githubusercontent.com/7207461/158156836-bac56404-9233-49e8-a261-f176c76998c7.png)
6. Debug the App.
7. As you can see EFCore is trying to seed the data one more time which is not desireable. 

I'd prefer to seed them on demand ONLY via using "update-database" command. I know I can check if the table is empty or if the app is running is Debug vs Release mode and then decide to seed or not but this is something that I need to develop and maintain. Is it really mandatory to run seeds everytime the app is launched?

I hope the issue is now crystal clear and I'm looking forward for any guidance. Thanks a lot once again for your commitment.

**Comment by ajcvickers** [comment]
@Stadzior As @roji said above, the seed data is being included into the model, but that doesn't mean anything is being done to the database.

**Comment by Stadzior** [comment]
@ajcvickers ok I get your point. Let's then take one step further. As I stated in the original question I need to seed many-to-many relationships hence .HasData approach is not an option because of the following error:

```
PM> update-database
Build started...
Build succeeded.
System.InvalidOperationException: An attempt was made to use the model while it was being created. A DbContext instance cannot be used inside 'OnModelCreating' in any way that makes use of the model that is being created.
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Internal.IDbContextDependencies.get_StateManager()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.EntryWithoutDetectChanges(TEntity entity)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Add(TEntity entity)
   at EFCoreDemo.Data.Migration.Configuration.Seed(MyDbContext context) in C:\Users\stadryniakk\Source\Repos\EFCoreDemo\Data\Migration\Configuration.cs:line 17
   at EFCoreDemo.Data.MyDbContext.OnModelCreating(ModelBuilder modelBuilder) in C:\Users\stadryniakk\Source\Repos\EFCoreDemo\Data\MyDbContext.cs:line 18
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
An attempt was made to use the model while it was being created. A DbContext instance cannot be used inside 'OnModelCreating' in any way that makes use of the model that is being created.
```
Please review the [EFCoreDemo](https://github.com/Stadzior/EFCoreDemo) once again and see the second approach that is described in [Custom Initialization Logic](https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding#custom-initialization-logic) article in docs. Then the seeds are called everytime on the launch of the app but is not launched when "update-database" command is invoked.
I'd like to achieve exactly the opposite and I don't know where to place the Seed method.

**Comment by roji** [comment]
@Stadzior there seem to be multiple things being conflated in this discussion.

First, it seems you're saying that you've abandoned HasData because of an exception (`An attempt was made to use the model while it was being created`). While HasData indeed has drawbacks and it's fine not to use it, the exception above likely stems from an error in your own code. If you're interested in getting HasData to work, please post a minimal code sample with HasData, that triggers the exception (the current "EFCoreDemo" which you posted does not call HasData).

Second, because you're not using HasData, you're trying to implement [custom initialization logic](https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding#custom-initialization-logic); I can see this in your demo: the Configuration.Seed method saves new entities.

I think the issue is in your expectation for your **custom** seeding code to get invoked only when doing Update-Database, and not on every app startup; things don't work like that. Update-Database only applies migrations to your database, and HasData seeding is a part of that; so if you implement HasData, things will automatically work that way. If you do your own custom seeding, then it's just code which you need to manage and call yourself, just like any other code which uses EF. It doesn't magically get called when you do Update-Database; since you're calling it from the App constructor, it gets called every single time you startup your application, and continuously adds rows.

There are various ways to manage this. You could simply check if seed data has already been added to the database (e.g. is Bar1 already present?), and only seed if not (but that wouldn't work well if you add seed data later). So you could also remove all seed data before adding it back. Or you could make it an explicit gesture in your application, e.g. triggered when the user clicks some button or passes some command-line parameter. Exactly what to do is up to you.

**Comment by Stadzior** [comment]
@roji  I was afraid of such answer. In EF6 there is a type called [DbMigrationConfiguration<TContext>](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.migrations.dbmigrationsconfiguration-1?view=entity-framework-6.2.0) and has a Seed method. I guess this is the part which makes the "magic" happen and runs the Seeds on "update-database" invocation.

I guess if this is not the case in EFCore I'll then create a separate mssql script that will be invoked separately. It is a little bit cumbersome but still better than running seeds on every app launch or developing some more sophisticated solution to avoid multiple inserts.

**Comment by Stadzior** [comment]
Just fyi I have created an empty migration on the top of the already existing migrations and put sql script execution there and not in OnModelCreating method. In that way I can use "update-database" just as before and it works as expected.

Thanks again for your involvement in this ticket.
Regards,
Kamil
