### ISSUE TITLE
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 15: 'locking protocol'.

### ISSUE THREAD

**Issue by GeroL** [dotnet/efcore#27603]
The DBContext is created with new () instead of DI in a using statement.
It loops through a set of sqlite db files and gets some information out of them.
The error seems to happen every time. Documentation for sqlite indicated that this should happen very rare.

The statement 
```C#
if (!await context.Database.GetService<IRelationalDatabaseCreator>().ExistsAsync(cancellationToken))
```
Was necessary because otherwise it would fail already on await context.Database.EnsureCreatedAsync(cancellationToken);
with the same error.

The using is embedded in a foreach loop.
In the first round when there is no DB for a specific file it works.
Beginning with the second an hour later the error occurs.
Maybe there has be done a manual cleanup I forgot?

### Code

```C#
            using (var context = new LogDataDBContext(file.First().Filename))
            {
                try
                {
                    context.Database.AutoTransactionsEnabled = false;

                    if (!await context.Database.GetService<IRelationalDatabaseCreator>().ExistsAsync(cancellationToken))
                    {
                        await context.Database.EnsureCreatedAsync(cancellationToken);
                    }

                    foreach (var f in file)
                    {
                        var oldest = await context.Set<Logs>()
                            .AsNoTracking()
                            .Where(x => x.Category == f.Filename)
                            .OrderBy(x => x.DateTime)
                            .Select(x => x.DateTime)
                            .FirstOrDefaultAsync(cancellationToken);

                        var newest = await context.Set<Logs>()
                            .AsNoTracking()
                            .Where(x => x.Category == f.Filename)
                            .OrderBy(x => x.DateTime)
                            .Select(x => x.DateTime)
                            .LastOrDefaultAsync(cancellationToken);

                        f.OldestEntryDate = oldest;
                        f.NewestEntryDate = newest;
                        filesToUpdate.Add(f);
                    }
                }
                catch (Exception e)
                {
                    _logger.LogError(e, "Error examining data for {File}", file.Key);
                }
            }
```

### Stacktrace:

```
LogService.Updater[0]
      Error examining data 
      Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 15: 'locking protocol'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
         at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
         at LogService.Updater.WriteData(CancellationToken cancellationToken) in /home/main/myagent/_work/1/s/src/LogService/Updater.cs:line 146
```

### DBContext
```C#
public class LogDataDBContext : DbContext
    {
        private readonly string _fileName;

        public LogDataDBContext(string fileName) : base()
        {
            _fileName = fileName;
        }

        public LogDataDBContext(DbContextOptions<LogDataDBContext> options) : base(options)
        {
            _fileName = "";
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (optionsBuilder.IsConfigured)
                return;

            var builder = new SqliteConnectionStringBuilder
            {
                DataSource = new FileInfo(_fileName).FullName
            };
            builder.Pooling = false;
            builder.Mode = SqliteOpenMode.ReadWriteCreate;

            optionsBuilder.UseSqlite(builder.ConnectionString);
            base.OnConfiguring(optionsBuilder);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.ApplyConfigurationsFromAssembly(typeof(LogDataDBContext).Assembly);
        }
    }

    public class Logs
    {
        public long Id { get; set; }
        
        public DateTime DateTime { get; set; }
        public string Category { get; set; } = default!;

        public string Message { get; set; }
    }


    public class LogsConfiguration : IEntityTypeConfiguration<Logs>
    {
        public void Configure(EntityTypeBuilder<Logs> builder)
        {
            builder.HasKey(x => x.Id);
            builder.Property(x => x.Category).HasMaxLength(10);

            builder.HasIndex(x => new { x.Category, x.DateTime }).IsUnique();
        }
    }
``` 

### version information

Microsoft.Data.Sqlite version: 6.0.1
Target framework: .Net 6.0.1
Operating system: Kubernetes on Ubuntu

**Comment by ajcvickers** [comment]
@GeroL Are other processes accessing these files concurrently?

**Comment by GeroL** [comment]
No, it currently is only one producer and many readers but the readers do run on demand only. The producer enumerates the files and creates a DBContext and writes some data to it. 
The first round of the loop everything works. It creates the DBs and writes initial data into them. The second round every statement crashes with this error. I already tried to implement work-arounds but I guess there is something left behind or not really disposed. The connection pooling is disabled. I close the connection before leaving the using statement manually. Restarting the pod does not help either. I now will try to use the sync version and will write my findings here. The storage were I save the data is provisioned by [longhorn](https://github.com/longhorn/longhorn) but it should't matter.
If I cannot workaround it I will try to create a test project for it here on github.

**Comment by GeroL** [comment]
I switch every call to sqlite to sync now this happens:
```
	Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 10: 'disk I/O error'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
         at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText, SqliteParameter[] parameters)
         at Microsoft.Data.Sqlite.SqliteTransaction..ctor(SqliteConnection connection, IsolationLevel isolationLevel, Boolean deferred)
         at Microsoft.Data.Sqlite.SqliteConnection.BeginTransaction(IsolationLevel isolationLevel, Boolean deferred)
         at Microsoft.Data.Sqlite.SqliteConnection.BeginTransaction(IsolationLevel isolationLevel)
         at Microsoft.Data.Sqlite.SqliteConnection.BeginDbTransaction(IsolationLevel isolationLevel)
         at System.Data.Common.DbConnection.BeginTransaction(IsolationLevel isolationLevel)
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.ConnectionBeginTransaction(IsolationLevel isolationLevel)
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction(IsolationLevel isolationLevel)
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction()
         at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.BeginTransaction()
         at LogService.Updater.WriteData(CancellationToken cancellationToken) in /home/main/myagent/_work/1/s/src/LogService/Updater.cs:line 250
         at LogService.Updater.ExecuteAsync(CancellationToken stoppingToken) in /home/main/myagent/_work/1/s/src/LogService/Updater.cs:line 497
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
```

Something is really messed up. I will create a hostPath version of the storage and take longhorn out of the equation.

**Comment by GeroL** [comment]
The problem was: Disk full 🤦‍♂️
After deleting some old files and resizing the volume everything works again as expected.
So no issue for sqlite here.
