### ISSUE TITLE
Entity type with navigation mapped to a sql query not supported?

### ISSUE THREAD

**Issue by deadcativan** [dotnet/efcore#27629]
I'm using EF Core 6.0

I have mapped a "keyed" entity type a sql query which selects rows from a indexed view with "noexpand" hint and everything works fine.

But after I added a navigation(one-way or bi-direction) to a "parent" entity type, a System.NotSupportedException with message "SqlQuery" was thrown when execute a query.

As I know, mapping a "keyless" entity type to a sql query works with one-way navigation.

So if mapping a "keyed" entity type to a sql query is supported, why with navigation is not supported? neither one-way nor bi-direction.

Here is my code:

```C#
using Microsoft.EntityFrameworkCore;

namespace MyApp1
{
    public class Author
    {
        public long Id { get; set; }

        public string Name { get; set; }

        public List<Post> Posts { get; set; }

        public PostStat PostStat { get; set; }
    }

    public class Post
    {
        public long Id { get; set; }

        public long AuthorId { get; set; }

        public Author Author { get; set; }

        public string Title { get; set; }

        public string Content { get; set; }
    }

    public class PostStat
    {
        public long AuthorId { get; set; }

        public Author Author { get; set; }

        public long? Count { get; set; }

    }
    public class MyDbContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("server=.;database=MyAppDb;user=myuser;password=123456");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Author>(builder =>
            {
                builder.ToTable("Author").HasKey(o => o.Id);

                builder.Property(o => o.Id).IsRequired();

                builder.Property(o => o.Name).HasMaxLength(50).IsRequired();
            });

            modelBuilder.Entity<Post>(builder =>
            {
                builder.ToTable("Post").HasKey(o => o.Id);

                builder.Property(o => o.Id).IsRequired();

                builder.Property(o => o.Title).HasMaxLength(50).IsRequired();

                builder.Property(o => o.Content).HasMaxLength(500).IsRequired();

                builder.Property(o => o.AuthorId).IsRequired();

                builder.HasOne(o => o.Author).WithMany(o => o.Posts).HasForeignKey(o => o.AuthorId).IsRequired();

            });

            modelBuilder.Entity<PostStat>(builder =>
            {
                builder.ToSqlQuery("SELECT * FROM [dbo].[PostStat] WITH (NOEXPAND)").HasKey(o => o.AuthorId);

                builder.Property(o => o.Count);

                builder.HasOne(o => o.Author).WithOne().HasForeignKey<PostStat>(o => o.AuthorId).IsRequired();

            });

        }

        public DbSet<Author> Authors { get; set; }

        public DbSet<Post> Posts { get; set; }

        public DbSet<PostStat> PostStats { get; set; }
    }

    public class Program
    {
        public static async Task Main(string[] args)
        {
            using var context = new MyDbContext();

            var author = await
                (from o in context.Authors
                 select new
                 {
                     Author = o,
                     PostCount = o.PostStat.Count
                 }).FirstOrDefaultAsync();

        }
    }
}


```

```SQL
CREATE TABLE [dbo].[Author]
(
	[Id] [bigint] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	CONSTRAINT [PK_Author] PRIMARY KEY CLUSTERED
	([Id])
)
GO

CREATE TABLE [dbo].[Post]
(
	[Id] [bigint] NOT NULL,
	[AuthorId] [bigint] NOT NULL,
	[Topic] [nvarchar](50) NOT NULL,
	[Content] [nvarchar](500) NOT NULL,
	CONSTRAINT [PK_Post] PRIMARY KEY CLUSTERED
	([Id])
)
GO

SET NUMERIC_ROUNDABORT OFF;
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT,
   QUOTED_IDENTIFIER, ANSI_NULLS ON;
GO

CREATE VIEW [dbo].[PostStat]
WITH SCHEMABINDING
AS
SELECT [AuthorId], COUNT_BIG(*) AS [Count]
FROM [dbo].[Post]
GROUP BY [AuthorId]
GO

CREATE UNIQUE CLUSTERED INDEX [PK_PostStat] ON [dbo].[PostStat]
(
	[AuthorId] ASC
)
GO
```

Stack Trace
```
System.NotSupportedException : SqlQuery
   at Microsoft.EntityFrameworkCore.RelationalEntityTypeExtensions.<FindRowInternalForeignKeys>d__57.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at Microsoft.EntityFrameworkCore.RelationalPropertyExtensions.FindSharedObjectRootPrimaryKeyProperty(IReadOnlyProperty property, StoreObjectIdentifier& storeObject)
   at Microsoft.EntityFrameworkCore.RelationalPropertyExtensions.GetDefaultColumnName(IReadOnlyProperty property, StoreObjectIdentifier& storeObject)
   at Microsoft.EntityFrameworkCore.RelationalPropertyExtensions.GetColumnName(IReadOnlyProperty property, StoreObjectIdentifier& storeObject)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalModel.AddSqlQueries(RelationalModel databaseModel, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalModel.Create(IModel model, IRelationalAnnotationProvider relationalAnnotationProvider, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalModel.Add(IModel model, IRelationalAnnotationProvider relationalAnnotationProvider, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelRuntimeInitializer.InitializeModel(IModel model, Boolean designTime, Boolean prevalidation)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.CheckState()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Select[TSource,TResult](IQueryable`1 source, Expression`1 selector)
   at MyApp1.Program.<Main>d__0.MoveNext() at C:\Users\Ivan\source\repos\MyApp1\MyApp1\Program.cs : line 100
```

**Comment by Liero** [comment]
**+1**

I've just hit the same problem too:

```c#
public class MaterialInfoConfiguration : IEntityTypeConfiguration<MaterialInfo>
{
    public void Configure(EntityTypeBuilder<MaterialInfo> entity)
    {
        entity.ToTable("Material");
        entity.HasNoKey();
        entity.HasKey(e => e.MaterialCode);                
        entity.Property(e => e.Id).HasColumnName("ID");
   
        entity.HasOne(e => e.Stocks)
           .WithMany()
           .IsRequired(false)
           .HasForeignKey(e => e.MaterialCode)
           .HasPrincipalKey(e => e.MaterialCode);
    }   
}
```

**Comment by CreativeTrager** [comment]
+1, exactly the same problem

**Comment by ajcvickers** [comment]
Verified fixed on latest daily build.
