### ISSUE TITLE
Loading derived entity

### ISSUE THREAD

**Issue by enterprisebug** [dotnet/efcore#27633]
### Minimal reproducible example

please see [minimal reproducible example](https://github.com/enterprisebug/EfCoreMinimalReproducibleExample)

### Stacktrace

```
System.ArgumentNullException: 'Value cannot be null. (Parameter 'start')'
   at OperatingHourRange..ctor(OperatingHours start, OperatingHours end) in C:\Source\Repos\EfCoreMinimalReproducibleExample\EfCoreMinimalReproducibleExample\DemoDbContext.cs:line 117
   at Castle.Proxies.OperatingHourRangeProxy..ctor(IInterceptor[] , OperatingHours start, OperatingHours end)
```

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: net6.0
Operating system: Windows 21H2 (OS Build 19044.1526)
IDE: Visual Studio 2022 17.0.4

**Comment by ajcvickers** [comment]
Note for triage: Minimal repro below. One derived type (ServiceContractCalculationInformation in the example) has an owned entity (OperatingHourRange). An instance of this owned entity is materialized and tracked when including or loading a _different_ derived type (MaintenanceCalculationInformation) that does not reference this owned entity.

```C#
using Microsoft.EntityFrameworkCore;

using (var context = new DemoDbContext())
{
    context.Database.EnsureDeleted();
    context.Database.EnsureCreated();

    context.Add(new RootEntity {BaseEntity = new MaintenanceCalculationInformation()});
    context.SaveChanges();
}

using (var context = new DemoDbContext())
{
    var loaded = context.RootEntities.Include(e => e.BaseEntity).First();

    Console.WriteLine(context.ChangeTracker.DebugView.LongView);
}

public class DemoDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            //.LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging()
            .UseSqlServer(@"Data Source=(LocalDb)\MSSQLLocalDB;Database=SixOh");
    }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .Entity<ServiceContractCalculationInformation>()
            .OwnsOne(x => x.OperatingHourRange);
    }

    public DbSet<CalculationInformation> CalculationInformations => Set<CalculationInformation>();
    public DbSet<ServiceContractCalculationInformation> DerivedEntity1s => Set<ServiceContractCalculationInformation>();
    public DbSet<MaintenanceCalculationInformation> MaintenanceCalculationInformations => Set<MaintenanceCalculationInformation>();
    public DbSet<RootEntity> RootEntities => Set<RootEntity>();
}

public class RootEntity {

    public Guid Id { get; set; }
    public virtual CalculationInformation BaseEntity { get; set; }
}

public abstract class CalculationInformation
{
    protected CalculationInformation() { }
    public Guid Id { get; private  set; }
}

public class ServiceContractCalculationInformation : CalculationInformation
{
    public OperatingHourRange OperatingHourRange { get; set; }
}

public class MaintenanceCalculationInformation : CalculationInformation
{
}

public class OperatingHourRange
{
}
```

Output:
```
MaintenanceCalculationInformation {Id: ee9668ea-a571-4f5c-1e34-08da066d1d32} Unchanged
  Id: 'ee9668ea-a571-4f5c-1e34-08da066d1d32' PK
  Discriminator: 'MaintenanceCalculationInformation'
OperatingHourRange {ServiceContractCalculationInformationId: ee9668ea-a571-4f5c-1e34-08da066d1d32} Unchanged
  ServiceContractCalculationInformationId: 'ee9668ea-a571-4f5c-1e34-08da066d1d32' PK FK
RootEntity {Id: 9dcd5c92-1428-4174-b2ba-08da066d1d2c} Unchanged
  Id: '9dcd5c92-1428-4174-b2ba-08da066d1d2c' PK
  BaseEntityId: 'ee9668ea-a571-4f5c-1e34-08da066d1d32' FK
  BaseEntity: {Id: ee9668ea-a571-4f5c-1e34-08da066d1d32}
```

**Comment by smitpatel** [comment]
Implementation note: Materialize included entity inside IncludeReference method call

**Comment by zacharyj-crezco** [comment]
Just a note, because I've just run up against this problem. You don't need navigation expressions to hit this issue. See the below code. Though in our actual use case it's proving gross to work around because of the use of Fody and the RuntimeNullables weaver and we can't really modify the MoneyType either 😅

I was surprised to see it trying to materialize properties not relevant based on the discriminator, but I guess that's my lack of understanding of the internals.
```
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace EFCoreTest;

sealed class Program
{
    static async Task Main(string[] args)
    {
        const string connectionString = @"Server=(localdb)\mssqllocaldb;Database=EFCoreTest;Trusted_Connection=True;ConnectRetryCount=0";
        var sc = new ServiceCollection();
        sc.AddDbContext<MyDbContext>(opts => opts.UseSqlServer(connectionString));
        await using var sp = sc.BuildServiceProvider();
        await using var context = sp.GetRequiredService<MyDbContext>();
        await context.Database.EnsureDeletedAsync();
        await context.Database.EnsureCreatedAsync();

        var routingEntity = RoutingBasedEntity.Create(Guid.NewGuid(), null);
        context.BaseBusinessEntities.Add(routingEntity);
        await context.SaveChangesAsync();
        Console.WriteLine($"Routing Entity: {routingEntity.Id}");

        try
        {
            var storedEntities = await context.BaseBusinessEntities.ToListAsync();
            Console.Write($"{storedEntities.Count} Entities stored");
        }
#pragma warning disable CA1031
        catch (Exception e)
#pragma warning restore CA1031
        {
            Console.WriteLine(e);
        }
    }
}

public class MyDbContext : DbContext
{
    public MyDbContext(DbContextOptions opts) : base(opts) { }

    public DbSet<BaseBusinessEntity> BaseBusinessEntities { get; set; } = null!;

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BaseBusinessEntity>(b =>
        {
            b.ToTable("BaseBusinessEntity");
            b.HasKey(t => t.Id);

            b.UseTphMappingStrategy();
            b.HasDiscriminator<BusinessEntityType>("EntityType")
                .HasValue<RoutingBasedEntity>(BusinessEntityType.Routing)
                .HasValue<MonetaryEntity>(BusinessEntityType.Monetary);

        });

        modelBuilder.Entity<RoutingBasedEntity>(b =>
        {
            b.Property(s => s.TransferId)
                .HasColumnName("Routing_TransferId")
                .IsRequired();
            b.Property(s => s.ScheduledDate)
                .HasColumnName("Routing_ScheduledDate");
        });

        modelBuilder.Entity<MonetaryEntity>(b =>
        {
            b.OwnsOne(s => s.InAmount, builder =>
            {
                builder.Property(p => p.AmountInMinorUnits)
                    .HasColumnName("Monetary_InAmountInMinorUnits")
                    .IsRequired();

                builder.Property(p => p.CurrencyCode)
                    .HasColumnName("Monetary_InAmountCurrencyCode")
                    .IsRequired();
            });
            b.OwnsOne(s => s.OutAmount, builder =>
            {
                builder.Property(p => p.AmountInMinorUnits)
                    .HasColumnName("Monetary_OutAmountInMinorUnits")
                    .IsRequired();

                builder.Property(p => p.CurrencyCode)
                    .HasColumnName("Monetary_OutAmountCurrencyCode")
                    .IsRequired();
            });
        });
    }
}

public enum BusinessEntityType
{
    Routing,
    Monetary
}


public abstract class BaseBusinessEntity
{
    public Guid Id { get; init; }
    // Other common props here...
}

public class RoutingBasedEntity : BaseBusinessEntity
{
    public Guid TransferId { get; init; }

    public DateTime? ScheduledDate { get; init; }

    public static RoutingBasedEntity Create(Guid transferId, DateTime? scheduledDate)
    {
        return new RoutingBasedEntity
        {
            Id = Guid.NewGuid(),
            TransferId = transferId,
            ScheduledDate = scheduledDate
        };
    }
}


public class MonetaryEntity : BaseBusinessEntity
{
    public MoneyValue InAmount { get; private set; } = null!;
    public MoneyValue OutAmount { get; private set; } = null!;

    private MonetaryEntity() { }

    public static MonetaryEntity Create(MoneyValue inAmount, MoneyValue outAmount)
    {
        return new MonetaryEntity
        {
            Id = Guid.NewGuid(),
            InAmount = inAmount,
            OutAmount = outAmount
        };
    }
}

public record MoneyValue
{
    public required string CurrencyCode { get; init; }

    public long AmountInMinorUnits { get; init; }

    private MoneyValue(long amountInMinorUnits, string? currencyCode)
    {
        AmountInMinorUnits = amountInMinorUnits;
        CurrencyCode = currencyCode ?? throw new ArgumentNullException(nameof(currencyCode));
    }
}
```

Output:
```
Routing Entity: d612c252-b3e3-4fec-8d81-c56ae8a923da
System.ArgumentNullException: Value cannot be null. (Parameter 'currencyCode')
   at EFCoreTest.MoneyValue..ctor(Int64 amountInMinorUnits, String currencyCode) in C:\dev\Tools\EF Core Tester\EFCoreTest.Console\Program.cs:line 154
   at lambda_method60(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at EFCoreTest.Program.Main(String[] args) in C:\dev\Tools\EF Core Tester\EFCoreTest.Console\Program.cs:line 29
```
