### ISSUE TITLE
Sequence contains more than one element - 2 joins between entities using stored procedure mappings

### ISSUE THREAD

**Issue by johncollinson2001** [dotnet/efcore#2769]
Hi,

I get the error "Sequence contains more than one element" when joining the same 2 entities twice and using MapToStoredProcedures(). See the code below. If you remove the MapToStoredProcedure() calls in the configuration classes, then the code runs.

```
public class TableOne
{
    public int TableOneId { get; set; }
    public virtual TableTwo TableTwo_1 { get; set; }
    public virtual TableTwo TableTwo_2 { get; set; }
}

public class TableTwo
{
    public int TableTwoId { get; set; }
}

public class TableOneMap : EntityTypeConfiguration<TableOne>
{
    public TableOneMap()
    {
        // Primary Key
        HasKey(t => t.TableOneId);

        // Relationships
        HasRequired(t => t.TableTwo_1)
            .WithMany()
            .Map(d => d.MapKey("TableTwoId_1"))
            .WillCascadeOnDelete(false);

        HasRequired(t => t.TableTwo_2)
            .WithMany()
            .Map(d => d.MapKey("TableTwoId_2"))
            .WillCascadeOnDelete(false);

        MapToStoredProcedures();
    }
}

public class TableTwoMap : EntityTypeConfiguration<TableTwo>
{
    public TableTwoMap()
    {
        // Primary Key
        HasKey(t => t.TableTwoId);

        MapToStoredProcedures();
    }
}

public class EFTestContextSeedIntialiser : DropCreateDatabaseAlways<EFTestContext>
{
    protected override void Seed(EFTestContext context)
    {
        var table2_1 = new TableTwo();
        var table2_2 = new TableTwo();

        var table1 = new TableOne()
        {
            TableTwo_1 = table2_1,
            TableTwo_2 = table2_2
        };

        context.Set<TableOne>().Add(table1);
        context.SaveChanges();
    }
}

public class EFTestContext : DbContext
{
    public EFTestContext()
        : base("Name=EFTestContext")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        modelBuilder.Configurations.Add(new TableOneMap());
        modelBuilder.Configurations.Add(new TableTwoMap());
    }
}


class Program
{
    static void Main(string[] args)
    {
        Database.SetInitializer(new EFTestContextSeedIntialiser());
        var context = new EFTestContext();
        context.Database.Initialize(true);

        System.Console.WriteLine("First Join: " + context.Set<TableOne>().First().TableTwo_1.TableTwoId);
        System.Console.WriteLine("Second Join: " + context.Set<TableOne>().First().TableTwo_2.TableTwoId);

        System.Console.ReadLine();
    }
}
```

A first chance exception of type 'System.InvalidOperationException' occurred in EntityFramework.dll
System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>Console.vshost.exe</AppDomain><Exception><ExceptionType>System.InvalidOperationException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Sequence contains more than one element</Message><StackTrace>   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at System.Data.Entity.Migrations.Infrastructure.ModificationCommandTreeGenerator.ChangeRelationshipStates(DbContext context, EntityType entityType, Object entity, EntityState state)
   at System.Data.Entity.Migrations.Infrastructure.ModificationCommandTreeGenerator.&amp;lt;Generate&amp;gt;d__14.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.&amp;lt;CastIterator&amp;gt;d__b1`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Data.Entity.Migrations.Infrastructure.EdmModelDiffer.GenerateFunctionBody[TCommandTree](EntityTypeModificationFunctionMapping modificationFunctionMapping, Func`3 treeGenerator, Lazy`1 modificationCommandTreeGenerator, MigrationSqlGenerator migrationSqlGenerator, String functionName, String rowsAffectedParameterName)
   at System.Data.Entity.Migrations.Infrastructure.EdmModelDiffer.GenerateUpdateFunctionBody(EntityTypeModificationFunctionMapping modificationFunctionMapping, Lazy`1 modificationCommandTreeGenerator, MigrationSqlGenerator migrationSqlGenerator)
   at System.Data.Entity.Migrations.Infrastructure.EdmModelDiffer.&amp;lt;BuildCreateProcedureOperations&amp;gt;d__15f.MoveNext()
   at System.Linq.Enumerable.&amp;lt;SelectManyIterator&amp;gt;d__31`3.MoveNext()
   at System.Linq.Enumerable.&amp;lt;ConcatIterator&amp;gt;d__71`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at System.Data.Entity.Migrations.Infrastructure.EdmModelDiffer.Diff(ModelMetadata source, ModelMetadata target, Lazy`1 modificationCommandTreeGenerator, MigrationSqlGenerator migrationSqlGenerator, String sourceModelVersion, String targetModelVersion)
   at System.Data.Entity.Migrations.Infrastructure.EdmModelDiffer.Diff(XDocument sourceModel, XDocument targetModel, Lazy`1 modificationCommandTreeGenerator, MigrationSqlGenerator migrationSqlGenerator, String sourceModelVersion, String targetModelVersion)
   at System.Data.Entity.Migrations.DbMigrator.AutoMigrate(String migrationId, VersionedModel sourceModel, VersionedModel targetModel, Boolean downgrading)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.AutoMigrate(String migrationId, VersionedModel sourceModel, VersionedModel targetModel, Boolean downgrading)
   at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration)
   at System.Data.Entity.Migrations.DbMigrator.&amp;lt;&amp;gt;c__DisplayClassc.&amp;lt;Update&amp;gt;b__b()
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.Update()
   at System.Data.Entity.Internal.DatabaseCreator.CreateDatabase(InternalContext internalContext, Func`3 createMigrator, ObjectContext objectContext)
   at System.Data.Entity.Internal.InternalContext.CreateDatabase(ObjectContext objectContext, DatabaseExistenceState existenceState)
   at System.Data.Entity.Database.Create(DatabaseExistenceState existenceState)
   at System.Data.Entity.DropCreateDatabaseAlways`1.InitializeDatabase(TContext context)
   at System.Data.Entity.Internal.InternalContext.&amp;lt;&amp;gt;c__DisplayClassf`1.&amp;lt;CreateInitializationAction&amp;gt;b__e()
   at System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
   at System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
   at System.Data.Entity.Database.Initialize(Boolean force)
   at Console.Program.Main(String[] args) in c:\Users\ajohnc\Documents\Visual Studio 2013\Projects\EFPowerToolsTest\Console\Program.cs:line 91
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()</StackTrace><ExceptionString>System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at System.Data.Entity.Migrations.Infrastructure.ModificationCommandTreeGenerator.ChangeRelationshipStates(DbContext context, EntityType entityType, Object entity, EntityState state)
   at System.Data.Entity.Migrations.Infrastructure.ModificationCommandTreeGenerator.&amp;lt;Generate&amp;gt;d__14.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.&amp;lt;CastIterator&amp;gt;d__b1`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Data.Entity.Migrations.Infrastructure.EdmModelDiffer.GenerateFunctionBody[TCommandTree](EntityTypeModificationFunctionMapping modificationFunctionMapping, Func`3 treeGenerator, Lazy`1 modificationCommandTreeGenerator, MigrationSqlGenerator migrationSqlGenerator, String functionName, String rowsAffectedParameterName)
   at System.Data.Entity.Migrations.Infrastructure.EdmModelDiffer.GenerateUpdateFunctionBody(EntityTypeModificationFunctionMapping modificationFunctionMapping, Lazy`1 modificationCommandTreeGenerator, MigrationSqlGenerator migrationSqlGenerator)
   at System.Data.Entity.Migrations.Infrastructure.EdmModelDiffer.&amp;lt;BuildCreateProcedureOperations&amp;gt;d__15f.MoveNext()
   at System.Linq.Enumerable.&amp;lt;SelectManyIterator&amp;gt;d__31`3.MoveNext()
   at System.Linq.Enumerable.&amp;lt;ConcatIterator&amp;gt;d__71`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at System.Data.Entity.Migrations.Infrastructure.EdmModelDiffer.Diff(ModelMetadata source, ModelMetadata target, Lazy`1 modificationCommandTreeGenerator, MigrationSqlGenerator migrationSqlGenerator, String sourceModelVersion, String targetModelVersion)
   at System.Data.Entity.Migrations.Infrastructure.EdmModelDiffer.Diff(XDocument sourceModel, XDocument targetModel, Lazy`1 modificationCommandTreeGenerator, MigrationSqlGenerator migrationSqlGenerator, String sourceModelVersion, String targetModelVersion)
   at System.Data.Entity.Migrations.DbMigrator.AutoMigrate(String migrationId, VersionedModel sourceModel, VersionedModel targetModel, Boolean downgrading)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.AutoMigrate(String migrationId, VersionedModel sourceModel, VersionedModel targetModel, Boolean downgrading)
   at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration)
   at System.Data.Entity.Migrations.DbMigrator.&amp;lt;&amp;gt;c__DisplayClassc.&amp;lt;Update&amp;gt;b__b()
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.Update()
   at System.Data.Entity.Internal.DatabaseCreator.CreateDatabase(InternalContext internalContext, Func`3 createMigrator, ObjectContext objectContext)
   at System.Data.Entity.Internal.InternalContext.CreateDatabase(ObjectContext objectContext, DatabaseExistenceState existenceState)
   at System.Data.Entity.Database.Create(DatabaseExistenceState existenceState)
   at System.Data.Entity.DropCreateDatabaseAlways`1.InitializeDatabase(TContext context)
   at System.Data.Entity.Internal.InternalContext.&amp;lt;&amp;gt;c__DisplayClassf`1.&amp;lt;CreateInitializationAction&amp;gt;b__e()
   at System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
   at System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
   at System.Data.Entity.Database.Initialize(Boolean force)
   at Console.Program.Main(String[] args) in c:\Users\ajohnc\Documents\Visual Studio 2013\Projects\EFPowerToolsTest\Console\Program.cs:line 91
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by ErikEJ** [comment]
That looks like EF6, this is the EF7 site

**Comment by johncollinson2001** [comment]
The code is using EF6.

However not sure where this site states it's EF7 only?!

Either way, an issue that needs to be looked at.

**Comment by johncollinson2001** [comment]
Re-raised on EF6 codeplex site.

**Comment by rowanmiller** [comment]
Closing out since this is EF6. EF6 issue is at https://entityframework.codeplex.com/workitem/2791
