### ISSUE TITLE
Specified cast is not valid: GetFieldValue<string>

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#2778]
When retrieving a string from a NULL string column, `GetFieldValue<string>` should return null. Instead it throws.

>    System.InvalidCastException : Specified cast is not valid.
>     at Microsoft.Data.Sqlite.SqliteDataReader.GetString(Int32 ordinal)
>     at Microsoft.Data.Sqlite.SqliteDataReader.GetFieldValue[T](Int32 ordinal)

**Comment by natemcmaster** [comment]
Oops, wrong repo. :dunce_cap:
