### ISSUE TITLE
HasConversion Fails for Property of OwnedEntity

### ISSUE THREAD

**Issue by mgraf1** [dotnet/efcore#27788]
## File a bug
When trying to call `HasConversion` for the property of an owned entity a System.InvalidOperationException is thrown which states

```
The entity type 'MyOwnedEntity' cannot be configured as non-owned because it has already been configured as a owned. Use the nested builder in `OwnsOne` or `OwnsMany` on the owner entity type builder to further configure this type. If you want to override previous configuration first remove the entity type from the model by calling 'Ignore'. See https://aka.ms/efcore-docs-owned for more information.'
```

This only seems to occur when `HasConversion` is called after the owned entity has previously been configured. If `HasConversion` is called within the `OwnsOne` block for the owned entity, no exception is thrown. For example, this throws no error

```C#
var valueConverter = new MyValueObjectConverter();
modelBuilder.Entity<ParentClass>()
    .OwnsOne(
        e => e.MyOwnedEntity,
        myOwnedEntity =>
        {
            myOwnedEntity.WithOwner();

            myOwnedEntity.Property(o => o.ValueObject)
                .HasConversion(valueConverter)
                .IsRequired();
        });
```

The reason this is an issue is that the application is using a library that calls `modelBuilder.Model.GetEntityTypes()` and provides conversions for certain types, that call needs to happen either before or after other EF classes are configured. An example would be the `Ardalis.SmartEnum` library that provides a `ModelBuilder` extension method `modelBuilder.ConfigureSmartEnum()` which provides a default ValueConverter for any class that extends `SmartEnum`.

### Include your code
```C#
namespace EfTest
{
    class Program
    {
        static async Task Main(string[] args)
        {
            using (var context = new MyContext())
            {
                var parent = new ParentClass
                {
                    MyOwnedEntity = new MyOwnedEntity
                    {
                        Name = "A",
                        ValueObject = new MyValueObject(1)
                    }
                };

                context.Parents.Add(parent);

                await context.SaveChangesAsync();
            }
        }
    }

    public class MyContext : DbContext
    {
        public DbSet<ParentClass> Parents { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder options)
            => options.UseSqlServer(@"Data Source=localhost;Initial Catalog=EfTest;MultipleActiveResultSets=true;Integrated Security=SSPI;");

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ParentClass>()
                .HasKey(b => b.Id);

            modelBuilder.Entity<ParentClass>()
                .OwnsOne(
                    e => e.MyOwnedEntity,
                    myOwnedEntity =>
                    {
                        myOwnedEntity.WithOwner();

                        myOwnedEntity.Property(o => o.ValueObject)
                            .IsRequired();
                    });

            modelBuilder.Entity<ParentClass>()
                .Navigation(p => p.MyOwnedEntity).IsRequired();

            var valueConverter = new MyValueObjectConverter();
            modelBuilder.Entity<MyOwnedEntity>().Property(o => o.ValueObject).HasConversion(valueConverter);
        }
    }

    public class ParentClass
    {
        public int Id { get; set; }

        public MyOwnedEntity MyOwnedEntity { get; set; }
    }

    public class MyOwnedEntity
    {
        public string Name { get; set; }

        public MyValueObject ValueObject { get; set; }
    }

    public record MyValueObject(int Id);

    public class MyValueObjectConverter : ValueConverter<MyValueObject, int>
    {
        public MyValueObjectConverter()
        : base(
            v => v.Id,
            v => new MyValueObject(v))
        {
        }
    }
}
```

### Include stack traces

```
Microsoft.EntityFrameworkCore
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.CanSetIsOwned(Boolean owned, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.IsOwned(Boolean owned, ConfigurationSource configurationSource, ForeignKey futureOwnership)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(TypeIdentity& type, ConfigurationSource configurationSource, Nullable`1 shouldBeOwned)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(Type type, ConfigurationSource configurationSource, Nullable`1 shouldBeOwned)
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity[TEntity]()
   at EfTest.MyContext.OnModelCreating(ModelBuilder modelBuilder) in C:\dev\projects\Experiments\EfTest\EfTest\Program.cs:line 146
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Internal.IDbContextDependencies.get_StateManager()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.EntryWithoutDetectChanges(TEntity entity)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Add(TEntity entity)
   at EfTest.Program.<Main>d__0.MoveNext() in C:\dev\projects\Experiments\EfTest\EfTest\Program.cs:line 22
```

### Include provider and version information

EF Core version: 6.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE:  Visual Studio 2022 17.1.3

**Comment by ajcvickers** [comment]
@mgraf1 Doing, `modelBuilder.Entity<MyOwnedEntity>()` will attempt to configure the entity as non-owned, hence the error message you are seeing.

> The reason this is an issue is that the application is using a library that calls modelBuilder.Model.GetEntityTypes() and provides conversions for certain types.

For this approach to work it must special-case owned types, or configure all converters using the lower-level metadata APIs that don't result in attempting to reconfigure an owned type as non-owned.

**Comment by mgraf1** [comment]
Hi @ajcvickers, thanks for the help here. That makes sense to me.

>For this approach to work it must special-case owned types, or configure all converters using the lower-level metadata APIs that don't result in attempting to reconfigure an owned type as non-owned.

Could you point me towards which APIs you are referring to?

**Comment by ajcvickers** [comment]
@mgraf1 I mean, not using the model builder, but instead using the APIs on `IModel`, `IEntityType`, etc. directly.
