### ISSUE TITLE
How to add a Postgres concurrency shadow property when using `IMutableEntityType`

### ISSUE THREAD

**Issue by JonPSmith** [dotnet/efcore#27781]
## Ask a question

I want to make a single DbContext to work with both SQL Server and Postgres using the approach described in the [EF Core documentation](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers?tabs=vs#using-one-context-type). I also want a concurrency token on all of my entities, so I use the `modelBuilder.Model.GetEntityTypes()`. This works for SQL Server but doesn't work for Postgres.

### Include your code

The code below comes from the DbContext I am trying to support SQL Server and Postgres

```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.HasDefaultSchema("authp");
    
    //Add concurrency token to every entity 
    foreach (IMutableEntityType entityType in modelBuilder.Model.GetEntityTypes())
    {
        if (Database.IsSqlServer())
        {
            entityType.AddProperty("ConcurrencyToken", typeof(byte[]))
                .SetColumnType("ROWVERSION");
            entityType.FindProperty("ConcurrencyToken")
                .ValueGenerated = ValueGenerated.OnAddOrUpdate;
            entityType.FindProperty("ConcurrencyToken")
                .IsConcurrencyToken = true;
        }
        else if (Database.IsNpgsql())
        {
            //see https://www.npgsql.org/efcore/modeling/concurrency.html
            entityType.AddProperty("xmin", typeof(uint))
                .SetColumnType("uint");
            entityType.FindProperty("xmin")
                .IsShadowProperty();
        }
    }
   // ... other configurable left out 
```

This works with SQL Server but I get a inner exception of Npgsql.PostgresException 42703: column "xmin" of relation "RoleToPermissions" does not exist. Here is the full stacktrace.

```
Microsoft.EntityFrameworkCore.DbUpdateException
An error occurred while saving the entity changes. See the inner exception for details.
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__104_0(DbContext _, ValueTuple`2 t)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at EntityFramework.Exceptions.Common.ExceptionProcessorStateManager`1.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Test.UnitTests.TestEfCoreCodePostgres.TestConcurrency.TestUpdateRolePostgres() in C:\Users\JonPSmith\source\repos\AuthPermissions.AspNetCore\Test\UnitTests\TestEfCoreCodePostgres\TestConcurrency.cs:line 44

Npgsql.PostgresException
42703: column "xmin" of relation "RoleToPermissions" does not exist

POSITION: 106
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|213_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)


```

Here is long DebugView of one of the entities 

```
EntityType: AuthUser
  Properties: 
    UserId (string) Required PK AfterSave:Throw MaxLength(256)
      Annotations: 
        MaxLength: 256
        Npgsql:ValueGenerationStrategy: None
    Email (string) Index MaxLength(256)
      Annotations: 
        MaxLength: 256
        Npgsql:ValueGenerationStrategy: None
    IsDisabled (bool) Required
      Annotations: 
        Npgsql:ValueGenerationStrategy: None
    TenantId (int?) FK Index
      Annotations: 
        Npgsql:ValueGenerationStrategy: None
    UserName (string) Index MaxLength(128)
      Annotations: 
        MaxLength: 128
        Npgsql:ValueGenerationStrategy: None
    xmin (no field, uint) Shadow Required
      Annotations: 
        Npgsql:ValueGenerationStrategy: None
        Relational:ColumnType: uint
  Navigations: 
    UserRoles (_userRoles, IReadOnlyCollection<UserToRole>) Collection ToDependent UserToRole
    UserTenant (Tenant) ToPrincipal Tenant
  Keys: 
    UserId PK
  Foreign keys: 
    AuthUser {'TenantId'} -> Tenant {'TenantId'} ToPrincipal: UserTenant ClientSetNull
  Indexes: 
    Email  Unique
    TenantId 
    UserName  Unique
  Annotations: 
    DiscriminatorProperty: 
    Relational:FunctionName: 
    Relational:Schema: authp
    Relational:SqlQuery: 
    Relational:TableName: AuthUsers
    Relational:ViewName: 
    Relational:ViewSchema: 
```

### Include provider and version information

EF Core version: 6.0.0
Database provider: (e.g. Npgsql.EntityFrameworkCore.PostgreSQL)
Target framework: (e.g. .NET 6.0)
Operating system: Windows
IDE: (e.g. Visual Studio 2022 19)

**Comment by JonPSmith** [comment]
A bit more information. I am putting the migrations in different projects and I noticed that the xmin is defined as a `long` type on the software side. Here is a section from the Postgres migration.

```c#
migrationBuilder.CreateTable(
    name: "AuthUsers",
    schema: "authp",
    columns: table => new
    {
        UserId = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: false),
        Email = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
        UserName = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: true),
        IsDisabled = table.Column<bool>(type: "boolean", nullable: false),
        TenantId = table.Column<int>(type: "integer", nullable: true),
        xmin = table.Column<long>(type: "uint", nullable: false)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_AuthUsers", x => x.UserId);
        table.ForeignKey(
            name: "FK_AuthUsers_Tenants_TenantId",
            column: x => x.TenantId,
            principalSchema: "authp",
            principalTable: "Tenants",
            principalColumn: "TenantId");
    });
```

**Comment by JonPSmith** [comment]
I fixed it - I found [this solution](https://github.com/npgsql/efcore.pg/issues/19#issuecomment-253346255) from @roji which told me what I needed.

**Comment by roji** [comment]
Great that you figured it out @JonPSmith!

**Comment by halllo** [comment]
> I fixed it - I found [this solution](https://github.com/npgsql/efcore.pg/issues/19#issuecomment-253346255) from @roji which told me what I needed.

Are you sure it fixes it for you? In my experiment it does not actually prevent the multi user conflict:

```
var entity = db.Entities.FirstOrDefault(u => u.Name == "...");
entity.Value += "!";
await db.SaveChangesAsync();

try
{
	entity.Value += "?";
	await db.SaveChangesAsync();
	throw new System.Exception("DbUpdateConcurrencyException expected");
}
catch (DbUpdateConcurrencyException)
{
}
```

**Comment by halllo** [comment]
Nevermind, `db.SaveChangesAsync()` updated the RowVersion property. I had to try with two db contexts to verify the DbUpdateConcurrencyException is thrown.
