### ISSUE TITLE
GroupBy generates invalid SQL when using null/default values

### ISSUE THREAD

**Issue by ripebananas** [dotnet/efcore#27801]
EF Core version: `6.0.3`
Database provider: `Microsoft.EntityFrameworkCore.SqlServer`
Target framework: `.NET 6.0`
Operating system: Windows 11
IDE: Visual Studio 2022

Greetings,
I have the following entity:
```C#
public class UserAction
{
    public int Id { get; set; }
    public int UserId { get; set; }
    public int Action { get; set; }
}
```
I am trying to pull some records from the database, with a `GroupBy` statement, where the grouped-by columns are sort-of dynamic.
This is achieved by another helper class:
```C#
public class UserActionsQuery
{
    public bool GroupByAction { get; set; }
    public bool GroupByUser { get; set; }
}
```
When both `GroupByAction` and `GroupByUser` properties are `true`, there are no issues.
When `GroupByUser` property, for example, is `false` - EF Core seems to generate invalid SQL.
Here is the code that pulls the aggregated records:
```C#
var query = new UserActionsQuery { GroupByAction = true };
context.UserActions.AsNoTracking()
    .GroupBy(
        x => new
        {
            UserId = query.GroupByUser ? (int?)x.UserId : null,
            Action = query.GroupByAction ? (int?)x.Action : null,
        },
        x => x,
        (key, items) => new { UserId = key.UserId, Action = key.Action, Count = items.Count() }
    ).ToArray();
```

The exception that is received is:
```
Microsoft.Data.SqlClient.SqlException (0x80131904): The multi-part identifier "u.Action" could not be bound.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
```
The SQL that EF Core generates is as follows (clearly invalid because of `[u].[Action]`):
```SQL
-- net 6 + ef core 6
SELECT NULL AS [UserId], [u].[Action], COUNT(*) AS [Count]
FROM (
    SELECT [u].[Action], NULL AS [UserId0]
    FROM [UserActions] AS [u]
) AS [t]
GROUP BY [t].[UserId0], [t].[Action]
```
On a side note, the same code run under `.NET 5.0` with `EF Core 5.0.0`, produces this SQL, which seems to be fine:
```SQL
-- net 5 + ef core 5
SELECT NULL AS UserId, u.Action, COUNT(*) AS Count
FROM UserActions AS u
GROUP BY u.Action
```

Please excuse me if this is a duplicate, or if I'm doing something wrong, thank you.

**Comment by ajcvickers** [comment]
@smitpatel to look for duplicate
