### ISSUE TITLE
.ToArrayAsync() calls .Max() on an empty result set from FromSqlRaw, throwing Sequence Does Not Contain Elements exception

### ISSUE THREAD

**Issue by teknofobia** [dotnet/efcore#27817]
I am having an issue in EF Core 6.0.3 where I wrote an extension method in order to execute stored procedures.  This works fine if results are returned, but when the stored procedure returns 0 results, the .ToArrayAsync() call is throwing an exception: Sequence Does Not Contain Elements.

For my code, I'm going to include 2 pieces.  The first is the extension method off the DBContext.  This creates a temporary context for executing raw SQL which in my actual usage is just the SQL for executing a stored procedure along with any params.

```
public static async Task<IEnumerable<TResult>> SqlQueryAsync<TResult>(this DbContext db, string sql, DbConnectionInterceptor interceptor = null, CancellationToken cancellationToken = default, params object[] parameters) where TResult : class
{
    await using var context = new ContextForQuery<TResult>(db.Database.GetDbConnection(), db.Database.CurrentTransaction, interceptor);

    return await context.Set<TResult>().FromSqlRaw(sql, parameters).ToArrayAsync(cancellationToken);
}
```

The line that is erroring is the return statement in the extension method.  Dividing it up into multiple lines revealed it is the .ToArrayAsync() that is throwing the exception.  If I switch to .FirstOrDefaultAsync(), I get no error but I want all results or an empty array.

The second piece is the temporary context I'm creating for the sproc execution, just incase something here is causing the error when the resultset is empty.

```
    public class ContextForQuery<T> : DbContext where T : class
    {
        private readonly DbConnection _connection;
        private readonly IDbContextTransaction _transaction;
        private readonly DbConnectionInterceptor _interceptor;

        public ContextForQuery(DbConnection connection, IDbContextTransaction tran, DbConnectionInterceptor interceptor = null)
        {
            _connection = connection;
            _transaction = tran;
            _interceptor = interceptor;

            if (tran != null)
            {
                Database.UseTransaction((tran as IInfrastructure<DbTransaction>).Instance);
            }
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (_transaction != null)
            {
                optionsBuilder.UseSqlServer(_connection);
            }
            else
            {
                optionsBuilder.UseSqlServer(_connection, options => options.EnableRetryOnFailure());
            }

            if (_interceptor != null)
            {
                optionsBuilder.AddInterceptors(_interceptor);
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<T>().HasNoKey().ToView(null);
        }
    }
```

When results come back from the stored procedure, everything seems to work fine.  However, when the sproc would return 0 results, I always get the following error when trying to use .AnyAsync(), .ToArrayAsync(), and .ToListAsync()

```
System.InvalidOperationException : Sequence contains no elements

at System.Linq.ThrowHelper.ThrowNoElementsException()
at System.Linq.Enumerable.Max(IEnumerable`1 source)
at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)

```

It appears to be running .Max() on an empty collection under the hood.

As a temporary work around, I can catch this particular exception in my extension method until a fix is found.

EF Core version: 6.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.0.5

**Comment by teknofobia** [comment]
This only appears to be a problem if I try to use a dynamic as the return type.  Using a strongly typed model seems to have fixed the error.
