### ISSUE TITLE
EF Core throws Exception when saving changes to objects that were included with `.Include()`

### ISSUE THREAD

**Issue by baltermia** [dotnet/efcore#27890]
## Describe the Problem

I have a repository object that is called from a controller which should update some data on my sqlserver database. I receive the object as a `DTO` class and then find the corresponding item on the database and update the values on that object. 
The database item contains a list of translations. I have to include those translations with a `.Include` (see code below). When I use this, entityframework throws an exception (see stack traces below). When I don't include the `.Include`, no exception is thrown.
You see the type `CommandItem` and `ActionItem` below. Action is a abstract class and holds some properties. Command is one of many deriving classes, all of these derived objects are stored in a single database table and in the contexts list `ActionItems`.

I've already looked at the stack trace for way too long and can't find a hint on what the problem could be.

I only see one solution to this, which would also be very ugly IMO. I could simply access `_context.ActionTranslation` and update the translation from there, but is there no other way?

## Code

```csharp
private readonly IMyDBContext _context;

public CommandRepository(IMyDBContext context) { _context = context; }

public async Task UpdateAsync(CommandDto commandDto)
{
    // First I get the existing CommandItem from the Database context using the ID
    CommandItem command = _context
        .Set<ActionItem>()
        .OfType<CommandItem>()
        
        // This is the problematic line of code:
        // When I don't include this line, the commands ActionTranslations list is empty
        // So I need to include it with this statement to update existing translations
        // If I don't include it, all existing translations are added to the database and duplicate values are generated
        .Include(e => e.ActionTranslations)
        .FirstOrDefault(e => e.ID == commandDto.id);

    // This is a Mapping method on the DTO class, it simply updates the properties (no lists) of the existing CommandItem
    command = CommandDto.MapToEntityModel(commandDto, command);

    // The foreach will check whether a Trnaslation with the Language already exists
    // If it exists, the Text of that Translation is updated
    // Otherwise a new Translation is added to command.ActionTranslations
    foreach (KeyValuePair<string, string> pair in commandDto.Translations)
    {
        // Initialize the List if it's empty (yes this is possible)
        command.ActionTranslations ??= new List<ActionTranslations>();
        
        // Get the commands ActionTranslation with the same Language as the current translation form the foreach pair
        ActionTranslation translation = command.ActionTranslations.FirstOrDefault(e => e.Language == pair.Key);
        
        if (translation == default(ActionTranslation))
        {
            command.ActionTranslations.Add(new()
            {
                Language = pair.Key,
                Text = pair.Value
            }
        }
        else
        {
            translation.Langauge = pair.Value;
        }
    }

    // The Exception is thrown here
    await _context.SaveChangesAsync();
}
```

## Stack Traces

<details>
	<summary>Open to show Exception(s)</summary>
	
	Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition 6.Log	"Failed executing DbCommand (5ms) [Parameters=[@p1='?' (DbType = Int32), @p0='?' (Size = 4000)], CommandType='Text', CommandTimeout='30']
	SET NOCOUNT ON;
	UPDATE [ActionTranslations] SET [Language] = @p0
	WHERE [ID] = @p1;
	SELECT @@ROWCOUNT;"	
	Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition 3.Log	"An exception occurred in the database while saving changes for context type 'FabGuide.Shared.Models.FabGuideContext'.
	Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
	---> Microsoft.Data.SqlClient.SqlException (0x80131904): String or binary data would be truncated.
	The statement has been terminated.
	at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task 1 result)
	at System.Threading.Tasks.ContinuationResultTaskFromResultTask 2.InnerInvoke()
	at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
	--- End of stack trace from previous location ---
	at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
	ClientConnectionId:d1c9bf1d-948b-4b01-9562-5bc904153f44
	Error Number:8152,State:30,Class:16
	--- End of inner exception stack trace ---
	at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable 1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable 1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable 1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList 1 entriesToSave, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func 4 operation, Func 4 verifySucceeded, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)"	"Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
	---> Microsoft.Data.SqlClient.SqlException (0x80131904): String or binary data would be truncated.
	The statement has been terminated.
	at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task 1 result)
	at System.Threading.Tasks.ContinuationResultTaskFromResultTask 2.InnerInvoke()
	at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
	--- End of stack trace from previous location ---
	at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
	ClientConnectionId:d1c9bf1d-948b-4b01-9562-5bc904153f44
	Error Number:8152,State:30,Class:16
	--- End of inner exception stack trace ---
	at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable 1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable 1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable 1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList 1 entriesToSave, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func 4 operation, Func 4 verifySucceeded, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)"
	Error while updating Action	"Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
	---> Microsoft.Data.SqlClient.SqlException (0x80131904): String or binary data would be truncated.
	The statement has been terminated.
	at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task 1 result)
	at System.Threading.Tasks.ContinuationResultTaskFromResultTask 2.InnerInvoke()
	at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
	--- End of stack trace from previous location ---
	at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
	ClientConnectionId:d1c9bf1d-948b-4b01-9562-5bc904153f44
	Error Number:8152,State:30,Class:16
	--- End of inner exception stack trace ---
	at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable 1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable 1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable 1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList 1 entriesToSave, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func 4 operation, Func 4 verifySucceeded, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
	at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
	at FabGuide.Server.Repositories.CommandRepository.UpdateAsync(CommandDto commandDto) in C:\_Locations\_locations\TCH\1083_FabGuide\main\FabGuide\FabGuide\Server\Repositories\CommandRepository.cs:line 117
	at FabGuide.Server.Repositories.ActionRepository.UpdateAsync(ActionDto actionDto) in C:\_Locations\_locations\TCH\1083_FabGuide\main\FabGuide\FabGuide\Server\Repositories\ActionRepository.cs:line 59
	at FabGuide.Server.Controllers.ActionsController.Put(Int32 id, ActionDto actionDto) in C:\_Locations\_locations\TCH\1083_FabGuide\main\FabGuide\FabGuide\Server\Controllers\ActionsController.cs:line 129"
	
</details>

## Additional information

EF Core version: 5.0.10
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10.0.19042
IDE: Visual Studio 2019 16.11.10

**Comment by baltermia** [comment]
This exception is thrown when a string you want to save to the database is longer than you defined it. Let's say you have model like this:
```csharp
public class TestModel 
{
    [StringLength(2)]
    public string SomeString { get; set; }
}
```
and you want to save the string `hello` to the database like this:
```csharp
testModel.SomeString = "hello";

context.Update(testModel);

await context.SaveChangesAsync();
```
The string now is 5 characters long, so the length exceeds the length set by the `StringLength` attribute. So the entity framework will not proceed.
