### ISSUE TITLE
DatabaseGeneratedOption.Identity not working on Guid property

### ISSUE THREAD

**Issue by danielniccoli** [dotnet/efcore#28024]
The [docs](https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties) state that

> […] on SQL Server, when a GUID property is configured as value generated on add, the provider automatically performs value generation client-side, using an algorithm to generate optimal sequential GUID values. 

I have not found this to be true. Decorating a `Guid` with either `[DatabaseGenerated(DatabaseGeneratedOption.Identity)]` or `[DatabaseGenerated(DatabaseGeneratedOption.Compute)]` initialized an instance of an entity with a GUID `00000000-0000-0000-0000-000000000000`. My understanding is that this is a temporary value and will get replaced by a true GUID somewhere during the persist operation. But when attempting to persist the entity to a databaseby calling `SaveChanges()`, EF attempts to persist `NULL`.

> Cannot insert the value NULL into column 'GuidIdentity', table 'DbGenerated.dbo.MyEntities'; column does not allow nulls.

### Demo Project

Run the following commands to create a demo project.

```
dotnet new console -o DbGenerated
cd DbGenerated
dotnet add package Microsoft.EntityFrameworkCore.Design
dotnet add package Microsoft.EntityFrameworkCore.SqlServer
```

Add **Models.cs** and overwrite **Program.cs** with the following code:

**Models.cs**
```cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations.Schema;

public class MyContext : DbContext
{
    public DbSet<MyEntity> MyEntities { get; set; } = default!;

    protected override void OnConfiguring(DbContextOptionsBuilder options)
        => options.UseSqlServer("Server=(localdb)\\MSSQLLocalDB;Database=DbGenerated;Trusted_Connection=True;MultipleActiveResultSets=true");
}

public class MyEntity
{
    public int Id { get; set; }

    public string? Name { get; set; }

    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid GuidIdentity { get; set; }

    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public Guid GuidComputed { get; set; }

}
```

**Program.cs**
```cs
using var db = new MyContext();

MyEntity e = new() { };

Console.WriteLine($"Type of 'e.Id' is '{e.Id.GetType()}' and has value '{e.Id}'.");
Console.WriteLine($"Type of 'e.GuidIdentity' is '{e.GuidIdentity.GetType()}' and has value '{e.GuidIdentity}'.");
Console.WriteLine($"Type of 'e.GuidIdentity' is '{e.GuidIdentity.GetType()}' and has value '{e.GuidIdentity}'.");

db.Add(e);
db.SaveChanges(); // throws exception
```

Add migration, update database and run the project.

```
dotnet ef migrations add InitialCreate
dotnet ef database update
dotnet run
```

### Demo Project Output

```
PS C:\DbGenerated> dotnet run
Type of 'e.Id' is 'System.Int32' and has value '0'.
Type of 'e.GuidIdentity' is 'System.Guid' and has value '00000000-0000-0000-0000-000000000000'.
Type of 'e.GuidIdentity' is 'System.Guid' and has value '00000000-0000-0000-0000-000000000000'.
Unhandled exception. Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'GuidIdentity', table 'DbGenerated.dbo.MyEntities'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
ClientConnectionId:77966582-8f8e-47c6-b66d-bf9394749b00
Error Number:515,State:2,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__104_0(DbContext _, ValueTuple`2 t)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Program.<Main>$(String[] args) in C:\DbGenerated\Program.cs:line 10
PS C:\DbGenerated>
```

### Include provider and version information

EF Core version: 6.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 6
Operating system: Windows 11
IDE: Visual Studio 2022 Community Preview 17.2

**Comment by ErikEJ** [comment]
It should be ValueGeneratedOnAdd (as per the docs) : smile:

**Comment by danielniccoli** [comment]
> It should be ValueGeneratedOnAdd (as per the docs) 😄

It's the same thing, no? One is Data Annotation, the other is Fluent API.

![grafik](https://user-images.githubusercontent.com/2971735/168442897-cab2f324-887c-4cd8-99a3-f80fa2e60b0b.png)
![grafik](https://user-images.githubusercontent.com/2971735/168442899-a8d79d6d-2dfc-43dc-9126-7b37410a4dbd.png)

**Comment by roji** [comment]
You're right that this works only for key properties - the docs are incorrect.

You can set up client-side GUID generation by setting a value generation factory explicitly as following:

```c#
modelBuilder.Entity<Blog>().Property(b => b.Guid)
    .Metadata
    .SetValueGeneratorFactory((_, _) => new SequentialGuidValueGenerator());
```

Keeping open so we can discuss in triage.

**Comment by roji** [comment]
We'll keep this open for now to discuss whether we want to allow GUID client-side value generation for non-key ValueGeneratedOnAdd properties.

**Comment by ajcvickers** [comment]
Closed as by-design. Value generators are only selected by convention for key properties, where the semantics of the generated value (i.e. unique) are more fully understood than for an arbitrary property. Even for the GUID case, just because a value is marked as `ValueGeneratedOnAdd` does not mean that a new GUID should be used in every case--for example, we have seen sceanrios where people have a database default on an FK that gets a well-known GUID value if non is set when a new entity is inserted into the database.
