### ISSUE TITLE
EF Core 6 fails to detect specified discriminator

### ISSUE THREAD

**Issue by bgoodearl** [dotnet/efcore#28069]
## File a bug

Added new models with inheritance using Table-per-hierarchy and discriminator.

Ran migration via Package Manager Console and got error "The entity type 'LookupBaseWith10cKey' is part of a hierarchy, but does not have a discriminator value configured." 

### Include your code

Full code for sample can be found in the repo "https://github.com/bgoodearl/EFCore6_Test01" in the "b2_10c_lookups" branch: [EF Core 6 Migrations Test Platform #1 - b2_10c_lookups branch](https://github.com/bgoodearl/EFCore6_Test01/tree/b2_10c_lookups)

The relevant code is in OnModelCreating:
```c#
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            #region School Entities

            modelBuilder.Entity<Course>(e =>
            {
                e.HasKey(c => c.CourseID);
                e.Property(c => c.CourseID).ValueGeneratedNever();
                e.ToTable("Course");

                e.HasMany(e => e.CoursePresentationTypes).WithMany(p => p.Courses)
                    .UsingEntity(
                        join => join.ToTable("_coursesPresentationTypes")
                            .Property<int>("CoursesCourseId").HasColumnName("CourseID")
                    );

                e.HasMany(e => e.CourseTopics).WithMany(t => t.Courses)
                    .UsingEntity(
                        join => join.ToTable("_coursesTopics")
                            .Property<int>("CoursesCourseId").HasColumnName("CourseID")
                    );
            });
            #endregion School Entities


            //*******************************************
            #region LookupBaseWith2cKey Subclass Mappings

            modelBuilder.Entity<LookupType>(e =>
            {
                e.HasKey(x => x.Id);
                e.ToTable("xLookupTypes");
            });

            modelBuilder.Entity<LookupBaseWith2cKey>(e =>
            {
                e.HasKey(l => new { l.LookupTypeId, l.Code });
                e.ToTable("xLookups2cKey");

                e.Property(x => x.Code).HasMaxLength(2).IsRequired();
                e.Property(x => x.Name).HasMaxLength(100).IsRequired();

                e.HasIndex(l => new { l.LookupTypeId, l.Name }).IsUnique(true)
                    .HasDatabaseName("LookupTypeAndName");

                e.Property(l => l.SubType).HasColumnName("_SubType");

                e.HasDiscriminator<short>(x => x.SubType)
                    .HasValue<CoursePresentationType>((short)CULookupTypes.CoursePresentationType)
                    .HasValue<RandomLookupType>((short)CULookupTypes.RandomLookupType)
                ;

            });

            #endregion LookupBaseWith2cKey Subclass Mappings


            //********************************************
            #region LookupBaseWith10cKey Subclass Mappings

            modelBuilder.Entity<LookupBaseWith10cKey>(e =>
            {
                e.HasKey(l => new { l.LookupTypeId, l.Code });
                e.ToTable("xLookups10cKey");

                e.Property(x => x.Code).HasMaxLength(10);
                e.Property(x => x.Name).HasMaxLength(100);

                e.HasIndex(l => new { l.LookupTypeId, l.Name }).IsUnique(true)
                    .HasDatabaseName("LookupTypeAndName");

                e.Property(l => l.SubType).HasColumnName("_SubType");

                e.HasDiscriminator(x => x.SubType)
                    .HasValue<CourseTopicType>((short)CULookupTypes.CourseTopicType)
                    .HasValue<RandomLookupType10c>((short)CULookupTypes.RandomLookupType10c)
                ;
            });

            #endregion LookupBaseWith10cKey Subclass Mappings
        }
```
The discriminator is specified for LookupBaseWith10cKey as it is for LookupBaseWith2cKey, which works.

### Include verbose output

```powershell
Add-Migration -Project CU.Infrastructure -StartupProject CU.EFDataApp CU6_M04_AddCourseTopicLookupPlus -verbose
Using project 'src\CU.Infrastructure'.
Using startup project 'src\CU.EFDataApp'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile D:\_dev\GitHub\bgoodearl\EF\EFCore6_Test01\src\CU.EFDataApp\bin\Debug\net6.0\CU.EFDataApp.deps.json --additionalprobingpath C:\Users\bobg\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig D:\_dev\GitHub\bgoodearl\EF\EFCore6_Test01\src\CU.EFDataApp\bin\Debug\net6.0\CU.EFDataApp.runtimeconfig.json C:\Users\bobg\.nuget\packages\microsoft.entityframeworkcore.tools\6.0.2\tools\netcoreapp2.0\any\ef.dll migrations add CU6_M04_AddCourseTopicLookupPlus --json --verbose --no-color --prefix-output --assembly D:\_dev\GitHub\bgoodearl\EF\EFCore6_Test01\src\CU.EFDataApp\bin\Debug\net6.0\CU.Infrastructure.dll --project D:\_dev\GitHub\bgoodearl\EF\EFCore6_Test01\src\CU.Infrastructure\CU.Infrastructure.csproj --startup-assembly D:\_dev\GitHub\bgoodearl\EF\EFCore6_Test01\src\CU.EFDataApp\bin\Debug\net6.0\CU.EFDataApp.dll --startup-project D:\_dev\GitHub\bgoodearl\EF\EFCore6_Test01\src\CU.EFDataApp\CU.EFDataApp.csproj --project-dir D:\_dev\GitHub\bgoodearl\EF\EFCore6_Test01\src\CU.Infrastructure\ --language C# --configuration Debug --working-dir D:\_dev\GitHub\bgoodearl\EF\EFCore6_Test01 --root-namespace CU.Infrastructure --nullable
Using assembly 'CU.Infrastructure'.
Using startup assembly 'CU.EFDataApp'.
Using application base 'D:\_dev\GitHub\bgoodearl\EF\EFCore6_Test01\src\CU.EFDataApp\bin\Debug\net6.0'.
Using working directory 'D:\_dev\GitHub\bgoodearl\EF\EFCore6_Test01\src\CU.EFDataApp'.
Using root namespace 'CU.Infrastructure'.
Using project directory 'D:\_dev\GitHub\bgoodearl\EF\EFCore6_Test01\src\CU.Infrastructure\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Found IDesignTimeDbContextFactory implementation 'SchoolContextFactory'.
Found DbContext 'SchoolDbContext'.
Finding application service provider in assembly 'CU.EFDataApp'...
Finding Microsoft.Extensions.Hosting service provider...
Using environment 'Development'.
Using application service provider from Microsoft.Extensions.Hosting.
Finding DbContext classes in the project...
Using DbContext factory 'SchoolContextFactory'.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: The entity type 'LookupBaseWith10cKey' is part of a hierarchy, but does not have a discriminator value configured.
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateDiscriminatorValues(IEntityType rootEntityType)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateInheritanceMapping(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal.SqlServerModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at CU.Infrastructure.Persistence.SchoolDbContext.InitializeDbSets() in D:\_dev\GitHub\bgoodearl\EF\EFCore6_Test01\src\CU.Infrastructure\Persistence\SchoolDbContext.cs:line 24
   at CU.Infrastructure.Persistence.SchoolDbContext..ctor(DbContextOptions options) in D:\_dev\GitHub\bgoodearl\EF\EFCore6_Test01\src\CU.Infrastructure\Persistence\SchoolDbContext.cs:line 12
   at CU.EFDataApp.Data.SchoolContextFactory.CreateDbContext(String[] args) in D:\_dev\GitHub\bgoodearl\EF\EFCore6_Test01\src\CU.EFDataApp\Data\SchoolContextFactory.cs:line 16
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContextFromFactory(Type factory, Type contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass21_2.<FindContextTypes>b__9()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Include provider and version information

EF Core version: 6.0.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.0.10

**Comment by ajcvickers** [comment]
@bgoodearl In the code snippet above, there is no `HasValue<LookupBaseWith10cKey>` , so as far as I can see the error is expected.

**Comment by bgoodearl** [comment]
Here's the full code from OnModelCreating:

```C#
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            #region School Entities

            modelBuilder.Entity<Course>(e =>
            {
                e.HasKey(c => c.CourseID);
                e.Property(c => c.CourseID).ValueGeneratedNever();
                e.ToTable("Course");

                e.HasMany(e => e.CoursePresentationTypes).WithMany(p => p.Courses)
                    .UsingEntity(
                        join => join.ToTable("_coursesPresentationTypes")
                            .Property<int>("CoursesCourseId").HasColumnName("CourseID")
                    );

                e.HasMany(e => e.CourseTopics).WithMany(t => t.Courses)
                    .UsingEntity(
                        join => join.ToTable("_coursesTopics")
                            .Property<int>("CoursesCourseId").HasColumnName("CourseID")
                    );
            });
            #endregion School Entities


            //*******************************************
            #region LookupBaseWith2cKey Subclass Mappings

            modelBuilder.Entity<LookupType>(e =>
            {
                e.HasKey(x => x.Id);
                e.ToTable("xLookupTypes");
            });

            modelBuilder.Entity<LookupBaseWith2cKey>(e =>
            {
                e.HasKey(l => new { l.LookupTypeId, l.Code });
                e.ToTable("xLookups2cKey");

                e.Property(x => x.Code).HasMaxLength(2).IsRequired();
                e.Property(x => x.Name).HasMaxLength(100).IsRequired();

                e.HasIndex(l => new { l.LookupTypeId, l.Name }).IsUnique(true)
                    .HasDatabaseName("LookupTypeAndName");

                e.Property(l => l.SubType).HasColumnName("_SubType");

                e.HasDiscriminator<short>(x => x.SubType)
                    .HasValue<CoursePresentationType>((short)CULookupTypes.CoursePresentationType)
                    .HasValue<RandomLookupType>((short)CULookupTypes.RandomLookupType)
                ;

            });

            #endregion LookupBaseWith2cKey Subclass Mappings


            //********************************************
            #region LookupBaseWith10cKey Subclass Mappings

            modelBuilder.Entity<LookupBaseWith10cKey>(e =>
            {
                e.HasKey(l => new { l.LookupTypeId, l.Code });
                e.ToTable("xLookups10cKey");

                e.Property(x => x.Code).HasMaxLength(10);
                e.Property(x => x.Name).HasMaxLength(100);

                e.HasIndex(l => new { l.LookupTypeId, l.Name }).IsUnique(true)
                    .HasDatabaseName("LookupTypeAndName");

                e.Property(l => l.SubType).HasColumnName("_SubType");

                e.HasDiscriminator(x => x.SubType)
                    .HasValue<CourseTopicType>((short)CULookupTypes.CourseTopicType)
                    .HasValue<RandomLookupType10c>((short)CULookupTypes.RandomLookupType10c)
                ;
            });

            #endregion LookupBaseWith10cKey Subclass Mappings
        }
```

Both LookupBaseWith2cKey and LookupBaseWith10cKey are base classes.  I don't understand why (or how) there would be a discriminator for the base class.  Why does the code for LookupBaseWith2cKey work and the code for LookupBaseWith10cKey  fail?

**Comment by ajcvickers** [comment]
@bgoodearl `LookupBaseWith2cKey` is abstract. `LookupBaseWith10cKey` is not.

**Comment by bgoodearl** [comment]
Thanks!  The lookup base classes come from a project that started life with EF 6 on .NET Framework, was migrated to EF 6 on .NET Core 3.1 and is now being migrated to .NET 6.  EF 6 didn't complain about the lack of a discriminator with the base class that wasn't abstract.
