### ISSUE TITLE
dnx . ef migration add MyFirstMigration, error

### ISSUE THREAD

**Issue by lovemory** [dotnet/efcore#2806]
I Learn EF7 from the url:
http://ef.readthedocs.org/en/latest/getting-started/aspnet5.html

when i run the commonad :dnx . ef migration add MyFirstMigration
it output errors,   as below:

```
dnx : System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':

+ dnx .ef
+ ~~~~~~~
    + CategoryInfo          : NotSpecified: (System.InvalidO...ersion=v4.5.1'::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

   EntityFramework.Commands 7.0.0-beta6
   EntityFramework.SqlServer 7.0.0-beta6
   Microsoft.AspNet.Authentication.Cookies 1.0.0-b
eta6
   Microsoft.AspNet.Authentication.Facebook 1.0.0-beta6
   Microsoft.AspNet.Authentication.Google 1.0.0-beta6
   Microsoft.AspNet.Authentication.MicrosoftAccount 1.0.0-beta6
   Microsoft.AspNet.Authentication.Twitter 1.0.0-beta6
   Microsoft.AspNet.Diagnostics 1.0.0-beta6
   Microsoft.AspNet.Diagnostics.Entity 7.0.0-beta6
   Microsoft.AspNet.Identity.EntityFramework 3.0.0-beta6
   Microsoft.AspNet.Mvc 6.0.0-beta6
   Microsoft.AspNet.Mvc.TagHelpers 6.0.0-beta6
   Microsoft.AspNet.Server.IIS 1.0.0-beta6
   Microsoft.AspNet.Server.WebListener 1.0.0-beta6
   Microsoft.AspNet.StaticFiles 1.0.0-beta6
   Microsoft.AspNet.Tooling.Razor 1.0.0-beta6
   Microsoft.Framework.Configuration.Abstractions 1.0.0-beta6
   Microsoft.Framework.Configuration.Json 1.0.0-beta6
   Microsoft.Framework.Configuration.UserSecrets 1.0.0-beta6
   Microsoft.Framework.Logging 1.0.0-beta6
   Microsoft.Framework.Logging.Console 1.0.0-beta6
   Microsoft.VisualStudio.Web.BrowserLink.Loader 14.0.0-beta6

C:\Users\Administrator\Documents\Visual Studio 2015\Projects\WebApplication3\src\WebApplication3\project.lock.json(1,0): error: The expected lock file doesn't exist. Please run "dnu restore" to gen
erate a new lock file.
Current runtime target framework: 'DNX,Version=v4.5.1 (dnx451)'
 Version:      1.0.0-beta7-12302
 Type:         CLR
 Architecture: x64
 OS Name:      Windows
 OS Version:   6.1.7601.65536

   on Microsoft.Dnx.Runtime.DefaultHost.GetEntryPoint(String applicationName)
   on Microsoft.Dnx.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   on  Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)


   on System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   on Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   on Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   on Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   on Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)

PM> 
```

**Comment by BrennanConroy** [comment]
In the error message it says:
```C:\Users\Administrator\Documents\Visual Studio 2015\Projects\WebApplication3\src\WebApplication3\project.lock.json(1,0): error: The expected lock file doesn't exist. Please run "dnu restore" to generate a new lock file.```

Did you try this?

**Comment by paulvanbladel** [comment]
VS 2015 community edition --> same problem.
The lock file is in the exact location, but still giving the error.

**Comment by Exerlol** [comment]
1 more here! I'm having the exact same problem....Any ideas?

**Comment by paulvanbladel** [comment]
Well, in mean time, i solved the issue by making sure i am in e project folder abd not solution folder.

**Comment by clivingston2** [comment]
Since the initial post is a little old, can you post the error that you are seeing?

**Comment by Exerlol** [comment]
Sure, im using dnx 1.0.0-beta7 clr x86, using cmd and im inside project folder (src/projectName) if i try dnx . ef im getting this:
```javascript

System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
   EntityFramework.Commands 7.0.0-beta5
   EntityFramework.SqlServer 7.0.0-beta5
   Microsoft.AspNet.Authentication.Cookies 1.0.0-beta5
   Microsoft.AspNet.Authentication.Facebook 1.0.0-beta5
   Microsoft.AspNet.Authentication.Google 1.0.0-beta5
   Microsoft.AspNet.Authentication.MicrosoftAccount 1.0.0-beta5
   Microsoft.AspNet.Authentication.Twitter 1.0.0-beta5
   Microsoft.AspNet.Diagnostics 1.0.0-beta5
   Microsoft.AspNet.Diagnostics.Entity 7.0.0-beta5
   Microsoft.AspNet.Identity.EntityFramework 3.0.0-beta5
   Microsoft.AspNet.Mvc 6.0.0-beta5
   Microsoft.AspNet.Mvc.TagHelpers 6.0.0-beta5
   Microsoft.AspNet.Server.IIS 1.0.0-beta5
   Microsoft.AspNet.Server.WebListener 1.0.0-beta5
   Microsoft.AspNet.StaticFiles 1.0.0-beta5
   Microsoft.AspNet.Tooling.Razor 1.0.0-beta5
   Microsoft.Framework.Configuration.Abstractions 1.0.0-beta5
   Microsoft.Framework.Configuration.Json 1.0.0-beta5
   Microsoft.Framework.Configuration.UserSecrets 1.0.0-beta5
   Microsoft.Framework.Logging 1.0.0-beta5
   Microsoft.Framework.Logging.Console 1.0.0-beta5
   Microsoft.VisualStudio.Web.BrowserLink.Loader 14.0.0-beta5

file parth - \src\SoundBoard\project.lock.json(1,0): error: The expected lock file version does not match the actual version. Please run "dnu restore" to generate a new lock file.
Current runtime target framework: 'DNX,Version=v4.5.1 (dnx451)'
 Version:      1.0.0-beta7-15532
 Type:         CLR
 Architecture: x86
 OS Name:      Windows
 OS Version:   6.2.9200.0

   at Microsoft.Dnx.Runtime.DefaultHost.GetEntryPoint(String applicationName)
   at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)
```
if i however change dnx to 1.0.0-beta5 coreclr x86 and run same command (dnx . ef) im getting what i should in first place...
```javascript
dnx . ef

                     _/\__
               ---==/    \\
         ___  ___   |.    \|\
        | __|| __|  |  )   \\\
        | _| | _|   \_/ |  //|\\
        |___||_|       /   \\\/\\

 7.0.0-beta5-13549

Usage: ef [options] [command]

Options:
  -v|--version  Show version information
  -h|--help     Show help information

Commands:
  context    Commands to manage your DbContext
  migration  Commands to manage your Code First Migrations
  revEng     Command to reverse engineer code from a database
  help       Show help information

Use "ef help [command]" for more information about a command.

```

**Comment by clivingston2** [comment]
I believe it is because originally you are attempting to target two different frameworks.  Since beta7 is released, i would change all of the references for `beta5` in the project.json and global.json files to `beta7`.  Once that is done, target `dnx 1.0.0-beta7 clr x86` again and run `dnu restore`.  Then you should be able to run `dnx ef` and get...
```cmd
                     _/\__
               ---==/    \\
         ___  ___   |.    \|\
        | __|| __|  |  )   \\\
        | _| | _|   \_/ |  //|\\
        |___||_|       /   \\\/\\

Entity Framework Commands 7.0.0-beta7-15540

Usage: ef [options] [command]

Options:
  --version     Show version information
  -?|-h|--help  Show help information

Commands:
  database    Commands to manage your database
  dbcontext   Commands to manage your DbContext types
  migrations  Commands to manage your migrations

Use "ef [command] --help" for more information about a command.
```

**Comment by Exerlol** [comment]
Yep m8, you might be right, ill try that bit later and will write results...thanks for your help!

**Comment by Exerlol** [comment]
hmmm, its weird, if i try to update dependencies either with manage nuget packages or manually inside  project.json from beta5 to beta7 i get ~70 errors after rebuild...

**Comment by rowanmiller** [comment]
Welcome to the world of v1 pre-releases :exclamation: (especially when a lot of teams are doing API reviews). @danroth27 I thought we had some guidance on upgrading ASP.NET apps for the last few betas?

**Comment by danroth27** [comment]
Major breaking changes are announced here: https://github.com/aspnet/announcements/issues. You can filter the announcements by milestone.

**Comment by Exerlol** [comment]
Ok, so in case any1 else need solution for migrating to new beta version, I used this [link.](http://www.expertdebugger.com/tag/asp-net5/) 

So what you need to do is basically install add-ons for VS2015 to support beta7, and then in package manager console run "dnu restore" command (make sure ur positioned inside src\projectName folder and make sure ur using latest beta7 DNX). 

After that i could use dnx ef migrations.

**Comment by gabrielgreen** [comment]
The solution worked for me.  Thanks.  FYI, the problem only happened after I moved the project from one location to another in order to place it under source control.
