### ISSUE TITLE
NavigationBaseIncludeIgnored exception raised when a class and its navigational property are of the same type.

### ISSUE THREAD

**Issue by adhamankar** [dotnet/efcore#28093]
I have a class

```C#
  public class LookupValue 
  {
      public int Id { get; set; }
      public string Title { get; set; }
      public virtual List<LookupValueAttribute>? Attributes { get; set; }
  }
  public class LookupValueAttribute 
  {
      public int LookupValueId { get; set; }  
      public int Id { get; set; }
      public string Title { get; set; }
      public int? MeasurementUnitId { get; set; }
      public virtual LookupValue? MeasurementUnit { get; set; }
  }
```
Query
```C#
await _context.LookupValues.Include(p => p.Attributes)
                                                  .ThenInclude(p => p.MeasurementUnit)
                                            .OrderBy(p => p.Title)
                                            .Select(p => _mapper.Map<LookupValueDto>(p))
                                            .ToListAsync(cancellationToken)
```

On executing the query following error is thrown

*An error was generated for warning 'Microsoft.EntityFrameworkCore.Query.NavigationBaseIncludeIgnored': The navigation 'LookupValueAttribute.MeasurementUnit' was ignored from 'Include' in the query since the fix-up will automatically populate it. If any further navigations are specified in 'Include' afterwards then they will be ignored. Walking back include tree is not allowed.*

```
 An error was generated for warning 'Microsoft.EntityFrameworkCore.Query.NavigationBaseIncludeIgnored': The navigation 'LookupValueAttribute.MeasurementUnit' was ignored from 'Include' in the query since the fix-up will automatically populate it. If any further navigations are specified in 'Include' afterwards then they will be ignored. Walking back include tree is not allowed. This exception can be suppressed or logged by passing event ID 'CoreEventId.NavigationBaseIncludeIgnored' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
System.InvalidOperationException: An error was generated for warning 'Microsoft.EntityFrameworkCore.Query.NavigationBaseIncludeIgnored': The navigation 'LookupValueAttribute.MeasurementUnit' was ignored from 'Include' in the query since the fix-up will automatically populate it. If any further navigations are specified in 'Include' afterwards then they will be ignored. Walking back include tree is not allowed. This exception can be suppressed or logged by passing event ID 'CoreEventId.NavigationBaseIncludeIgnored' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
   at Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`1.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, TParam arg)
   at Microsoft.EntityFrameworkCore.Diagnostics.CoreLoggerExtensions.NavigationBaseIncludeIgnored(IDiagnosticsLogger`1 diagnostics, INavigationBase navigation)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.IncludeExpandingExpressionVisitor.ExpandIncludesHelper(Expression root, EntityReference entityReference, INavigationBase previousNavigation)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.IncludeExpandingExpressionVisitor.ExpandInclude(Expression root, EntityReference entityReference)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.IncludeExpandingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.IncludeExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ExpandingExpressionVisitor.Expand(Expression expression, Boolean applyIncludes)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.PendingSelectorExpandingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at AssetManager.Apis.Requests.CommonRequests.GetLookupValuesHandler.Handle(GetLookupValuesRequest request, CancellationToken cancellationToken) in C:\ManufacturingExcellence\assetmanager-api\Requests\CommonRequests\GetLookupValues.cs:line 35
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at AssetManager.Apis.Controllers.LookupGroupsController.GetAllLookupValues(Int32 lgId, GetLookupValuesRequest request) in C:\ManufacturingExcellence\assetmanager-api\Controllers\LookupGroupsController.cs:line 59
   at lambda_method779(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Common.Framework.ErrorHandlingMiddleware.Invoke(HttpContext context) in
```
EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 6.0)
Operating system: Windows 11
IDE: Microsoft Visual Studio Community 2022 (64-bit). Version 17.1.2

**Comment by ajcvickers** [comment]
@adhamankar What are you trying to achieve with this query?

```C#
await _context.LookupValues.Include(p => p.Attributes)
                                                  .ThenInclude(p => p.MeasurementUnit)
                                            .OrderBy(p => p.Title)
                                            .Select(p => _mapper.Map<LookupValueDto>(p))
                                            .ToListAsync(cancellationToken)
```

**Comment by adhamankar** [comment]
Hello @ajcvickers, 

In my case most of the master tables are simply a list of id-code-title so I have created a common class named LookupValue.
I intend to reuse this class for below case - both for the actual object - Pump as well as for attribute's property MeasurementUnit.


Lets say I have following json data structure

```
var measurementUnits = [              //list of LookupValue
{  id: 1000, code: "pa", Title: "Pascal"},
{ id: 1001, code: "ft", Title: "Foot"},
....
];

var pump = {                                 //object of the type LookupValue
  id: 1, 
  code: "PUMP", 
  Title: "Pump", 
  attributes: [
         { id: 100, Title: "Pressure", MeasurementUnit: {  id: 1000, code: "pa," Title: "Pascal"} },
         { id: 101, Title: "Height", MeasurementUnit: {  id: 1001, code: "ft," Title: "Foot"} },
         ...
  ];
```

This does not seem to work and raises above exception

**Comment by ajcvickers** [comment]
@adhamankar What I mean is, why are you doing `.Include(p => p.Attributes)` and then `.ThenInclude(p => p.MeasurementUnit)` which goes back to the entity you just included? Why do you need the `.ThenInclude` call?

**Comment by adhamankar** [comment]
the exception occurs even without the ```.ThenInclude(p=>p.MeasurementUnit)```
Merely adding ```.Include(p=>p.Attributes)``` causes the above exception.

**Comment by ajcvickers** [comment]
@adhamankar In that case, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by adhamankar** [comment]
Hello @ajcvickers I have updated the code to https://github.com/adhamankar/NavigationBaseIncludeIgnored

see [line# 51](https://github.com/adhamankar/NavigationBaseIncludeIgnored/blob/main/NavigationBaseIncludeIgnored/Program.cs#L51)

**Comment by ajcvickers** [comment]
@adhamankar There is only one relationship between `LookupValue` and `LookupValueAttribute`, represented by the `MeasurementUnitId` foreign key, which is associated with navigations `MeasurementUnit` and `Attributes`. The foreign key can only contain a single value, so if that value changes, then both sides of the relationship will reflect this. This means that when after the change to add "Pump", the FKs are updated accordingly, and both `MeasurementUnit` navigations point back to "Pump". The data in the database is consistent with this, so loading again from the database would not change the outcome here.

I suspect that a single relationship is not appropriate here, but it's hard to tell what would be appropriate without knowing more about the domain model.

**Comment by adhamankar** [comment]
I can achieve the results with a sql query and multiple joins to LookupValue table but I guess this must be difficult to reflect back from linq. Nevermind, I might end up making 2 separate calls to get the desired result.

Thank you for your effort on this @ajcvickers
