### ISSUE TITLE
EFCore 7.0-preview.4 with precompiled Model: The binary operator Equal is not defined for the types 'System.Int64' and 'System.Nullable`1[System.Int64]'

### ISSUE THREAD

**Issue by schuettecarsten** [dotnet/efcore#28108]
I have a very simple model that has two tables with a 1:n relationship and an Int64 key value type. Database is SqlServer. Querying both tables without any additional Where Linq filters works fine, but when I try to use a precompiled model, I get the following exception. If I uncomment the UseModel line in my code, it works again. Also, it worked without problems with preview.3.

```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.RuntimeMethodInfo.InvokeNonEmitUnsafe(Object obj, IntPtr* arguments, Span`1 argsForTemporaryMonoSupport, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMapFactoryFactory.Create(IKey key)
   at Microsoft.EntityFrameworkCore.Metadata.RuntimeKey.<>c.<Microsoft.EntityFrameworkCore.Metadata.Internal.IRuntimeKey.GetIdentityMapFactory>b__25_0(RuntimeKey key)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Metadata.RuntimeKey.Microsoft.EntityFrameworkCore.Metadata.Internal.IRuntimeKey.GetIdentityMapFactory()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetOrCreateIdentityMap(IKey key)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.TryGetEntry(IKey key, Object[] keyValues, Boolean throwOnNullKey, Boolean& hasNullKey)
   at Microsoft.EntityFrameworkCore.Query.QueryContext.TryGetEntry(IKey key, Object[] keyValues, Boolean throwOnNullKey, Boolean& hasNullKey)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.<MoveNextAsync>d__19.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__65`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__65`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 2:
InvalidOperationException: The binary operator Equal is not defined for the types 'System.Int64' and 'System.Nullable`1[System.Int64]'.
```

### Include provider and version information

EF Core version: 7.0.0-preview.4.22229.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 7.0-preview.4
Operating system: Windows 11
IDE: Visual Studio 2022

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by sergeyshaykhullin** [comment]
@ajcvickers I got same issue, it is happening inside expression visitor. All relations with nullable FK and not nullable PK are broken in preview 4 because no Guid? == Guid operator defined. Seems like ef need to cast both to Guid? first

```cs
class A
{
  // Nullable FK
  Guid? BId;
  B? B;
}

class B
{
  // PK
  Guid Id;
}
```

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
       ---> System.InvalidOperationException: The binary operator Equal is not defined for the types 'System.Guid' and 'System.N
ullable`1[System.Guid]'.
         at System.Linq.Expressions.Expression.GetEqualityComparisonOperator(ExpressionType binaryType, String opName, Expressio
n left, Expression right, Boolean liftToNull)
         at System.Linq.Expressions.Expression.Equal(Expression left, Expression right, Boolean liftToNull, MethodInfo method)
         at Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer.DefaultValueComparer`1.ExtractEqualsBody(Expression leftE
xpression, Expression rightExpression)
         at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyAccessorsFactory.CreateCurrentValueGetter[TProperty](IProper
tyBase propertyBase, Boolean useStoreGeneratedValues)
         at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyAccessorsFactory.CreateGeneric[TProperty](IPropertyBase prop
ertyBase)
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
         at System.Reflection.RuntimeMethodInfo.InvokeNonEmitUnsafe(Object obj, IntPtr* arguments, Span`1 argsForTemporaryMonoSu
pport, BindingFlags invokeAttr)
         --- End of inner exception stack trace ---
         at System.Reflection.RuntimeMethodInfo.InvokeNonEmitUnsafe(Object obj, IntPtr* arguments, Span`1 argsForTemporaryMonoSu
pport, BindingFlags invokeAttr)
         at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters,
CultureInfo culture)
         at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
         at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyAccessorsFactory.Create(IPropertyBase propertyBase)
         at Microsoft.EntityFrameworkCore.Metadata.RuntimePropertyBase.<>c.<Microsoft.EntityFrameworkCore.Metadata.Internal.IRun
timePropertyBase.get_Accessors>b__29_0(RuntimePropertyBase property)
         at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target,
TParam param, Func`2 valueFactory)
         at Microsoft.EntityFrameworkCore.Metadata.RuntimePropertyBase.Microsoft.EntityFrameworkCore.Metadata.Internal.IRuntimeP
ropertyBase.get_Accessors()
         at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyBaseExtensions.GetPropertyAccessors(IPropertyBase propertyBa
se)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.GetCurrentValue[TProperty](IPropertyBase p
ropertyBase)
         at lambda_method348(Closure, InternalEntityEntry)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.OriginalValues..ctor(InternalEntityEntry e
ntry)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.EnsureOriginalValues()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntrySubscriber.SnapshotAndSubscribe(InternalEnt
ityEntry entry)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, Entit
yState newState, Boolean acceptChanges, Boolean modifyProperties)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityStateAsync(EntityState entityStat
e, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintActionAsync(EntityEntryGraphNode`1 no
de, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraphAsync[TState](EntityEntr
yGraphNode`1 node, Func`3 handleNode, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraphAsync(InternalEntityEntry rootE
ntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey, CancellationTo
ken cancellationToken)
         at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.AddAsync(TEntity entity, CancellationToken cancellationToken)
```

**Comment by jamesgurung** [comment]
I'm getting the same error with nullable types and a precompiled model. Seems like a regression in Preview 4.

I have created a minimal repro: https://github.com/jamesgurung/EFCoreEqualNotDefinedDemo

```c#
using Microsoft.EntityFrameworkCore;

using var db = new BloggingContext();

db.Add(new Blog { Id = 1 }); // InvalidOperationException: The binary operator Equal is not defined for the types 'System.Int32' and 'System.Nullable`1[System.Int32]'.


public class BloggingContext : DbContext
{
  public DbSet<Blog> Blogs { get; set; }

  public BloggingContext()
  {
    Database.OpenConnection();
    Database.EnsureDeleted();
    Database.EnsureCreated();
  }
  
  protected override void OnConfiguring(DbContextOptionsBuilder options) =>
    options
      .UseSqlite("DataSource=file::memory:")
      .UseModel(EFCoreEqualNotDefinedDemo.BloggingContextModel.Instance); // Comment this line to fix the error.
  
  public override void Dispose()
  {
    Database.CloseConnection();
    base.Dispose();
  }
}

public class Blog
{
  public int? Id { get; set; }
}
```

**Comment by ajcvickers** [comment]
Note for triage: looks like the issue is in `PropertyAccessorFactory`:

```C#
            var comparer = (propertyBase as IProperty)?.GetValueComparer()
                ?? ValueComparer.CreateDefault(propertyBase.ClrType, favorStructuralComparisons: true);
```

In the non-compiled model, the property has the value comparer that was set when building the metadata, but in the compiled model this is not being used and instead the default comparer is being created, which no longer works because nullable FK properties now need the comparer created during model building.

/cc @AndriySvyryd

**Comment by schuettecarsten** [comment]
This issue is still in preview.6
