### ISSUE TITLE
SetBeforeSaveBehavior(PropertySaveBehavior.Ignore) not working when inserting parent with child entity with automatic linking

### ISSUE THREAD

**Issue by adolfo1981** [dotnet/efcore#28122]
## Bug description

I'm migrating a system from Linq-to-sql to Entity Framework Core 3.1 and running into an issue when inserting an new entity which contains another child new entity when both ID (int Identity Specification PK) are set to -1 even after setting the `BeforeSaveBehavior` to Ignore. Our system defaults ID's to -1 so we want to always ignore this on Insert. This works well when inserting single entities but not when inserting entities which relate to other entities.

When I comment out `Id = -1` for my new Company entity and leave the `Id = -1` for the child Employee entity it works but this would be problematic because setting new entity id's to -1 is widespread through our current solution.

### Code

Code below can be found in GitHub: https://github.com/adolfo1981/EFCoreAddNestedIssue

This is a simplified version of the code to reproduce the problem:

**Company Entity:**

``` c#
    public partial class Company
    {
        public Company()
        {
            Employees = new HashSet<Employee>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Employee> Employees { get; set; }
    }
```
**Employee Entity:**

``` c#
    public partial class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int? CompanyId { get; set; }

        public virtual Company Company { get; set; }
    }
```
**Company Configuration:**
``` c#
    public partial class CompanyConfiguration : IEntityTypeConfiguration<Company>
    {
        public void Configure(EntityTypeBuilder<Company> entity)
        {
            entity.HasKey(t => t.Id);
            
            entity.Property(p => p.Id)
                .UseIdentityColumn();

            entity.Property(p => p.Id)
                .ValueGeneratedOnAdd()
                .Metadata.SetBeforeSaveBehavior(PropertySaveBehavior.Ignore);

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Company> entity);
    }
```
**Employee Configuration:**
``` c#
public partial class EmployeeConfiguration : IEntityTypeConfiguration<Employee>
    {
        public void Configure(EntityTypeBuilder<Employee> entity)
        {
            entity.HasKey(t => t.Id);

            entity.Property(p => p.Id)
                .UseIdentityColumn();

            entity.Property(p => p.Id)
                .ValueGeneratedOnAdd()
                .Metadata.SetBeforeSaveBehavior(PropertySaveBehavior.Ignore);

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.Company)
                .WithMany(p => p.Employees)
                .HasForeignKey(d => d.CompanyId)
                .HasConstraintName("FK_Employee_Company");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Employee> entity);
    }
```
**Sample program:**
``` c#
    internal class Program
    {
        static void Main(string[] args)
        {
            AddCompanyWithEmployeeTest();
        }

        private static void AddCompanyWithEmployeeTest()
        {
            using (var context = new EFCoreTestContext())
            {
                var company = new Company
                {
                    Id = -1, //Our presentation layer sets Id to -1 for new entities
                    Name = "Tesla",
                    Employees = new List<Employee> {
                        new Employee {
                            Id = -1, //Our presentation layer sets Id to -1 for new entities
                            Name = "Bob Ross" }
                    }
                };

                context.Company.Add(company);
                context.SaveChanges();
            }
        }
    }
```
### Exception Details:

**Exception:**
```
The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Employee_Company". The conflict occurred in database "EFCoreTest", table "dbo.Company", column 'Id'.
The statement has been terminated.
```

**StackTrace:**
```
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
```

### Provider and version information

EF Core version:  3.1.25
Database provider:  Microsoft.EntityFrameworkCore.SqlServer v 3.1.25
Target framework:  .Net Framework 4.8
Operating system: Windows 11 Pro
IDE: Visual Studio 2022 17.1.4

**Comment by ajcvickers** [comment]
@adolfo1981 I ran your code on EF Core 6.0 and the issue is fixed there--see logs below. This means you will need to update to .NET 6 and EF Core 6.0 to make this scenario work. Note that 3.1 [goes out-of-support in December this year](https://docs.microsoft.com/en-us/ef/core/what-is-new/) and it is [extremely unlikely](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning) that we will patch 3.1 for this.

```
info: 5/31/2022 12:46:21.614 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (25ms) [Parameters=[@p0='Tesla' (Nullable = false) (Size = 150)], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [Company] ([Name])
      VALUES (@p0);
      SELECT [Id]
      FROM [Company]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
dbug: 5/31/2022 12:46:21.638 CoreEventId.ForeignKeyChangeDetected[10803] (Microsoft.EntityFrameworkCore.ChangeTracking)
      The foreign key property 'Company.Id' was detected as changed from '-1' to '1' for entity with key '{Id: 1}'.
dbug: 5/31/2022 12:46:21.646 CoreEventId.ForeignKeyChangeDetected[10803] (Microsoft.EntityFrameworkCore.ChangeTracking)
      The foreign key property 'Employee.CompanyId' was detected as changed from '-1' to '1' for entity with key '{Id: -1}'.
info: 5/31/2022 12:46:21.661 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (4ms) [Parameters=[@p1='1' (Nullable = true), @p2='Bob Ross' (Nullable = false) (Size = 200)], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [Employee] ([CompanyId], [Name])
      VALUES (@p1, @p2);
      SELECT [Id]
      FROM [Employee]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
dbug: 5/31/2022 12:46:21.663 CoreEventId.ForeignKeyChangeDetected[10803] (Microsoft.EntityFrameworkCore.ChangeTracking)
      The foreign key property 'Employee.Id' was detected as changed from '-1' to '1' for entity with key '{Id: 1}'.
dbug: 5/31/2022 12:46:21.674 CoreEventId.StateChanged[10807] (Microsoft.EntityFrameworkCore.ChangeTracking)
      The 'Company' entity with key '{Id: 1}' tracked by 'EFCoreTestContext' changed state from 'Added' to 'Unchanged'.
dbug: 5/31/2022 12:46:21.675 CoreEventId.StateChanged[10807] (Microsoft.EntityFrameworkCore.ChangeTracking)
      The 'Employee' entity with key '{Id: 1}' tracked by 'EFCoreTestContext' changed state from 'Added' to 'Unchanged'.
dbug: 5/31/2022 12:46:21.675 CoreEventId.SaveChangesCompleted[10005] (Microsoft.EntityFrameworkCore.Update)
      SaveChanges completed for 'EFCoreTestContext' with 2 entities written to the database.
```

**Comment by adolfo1981** [comment]
Ok thank you @ajcvickers.

**Comment by erikakerfeldt** [comment]
# Problem back in EF Core 7 and 8?

We have recently migrated from .NET Framework and EF 6.3 to .NET Core and EF Core 8. We are experiencing the same problem. Like @adolfo1981, our presentation layer currently forces us to use negative temporary ids for new entities.

I have recreated the example in this ticket, basically with identical code.

When using EF Core **8.0.2** we get the same error as reported above:

```
The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Employee_Company". The conflict occurred in database "EFCoreTest", table "dbo.Company", column 'Id'.
```

On the other hand, when downgrading to EF Core **6.0.27**, it works fine, just as @ajcvickers has concluded.

## EF Core 6

Here's the slightly edited log for EF Core 6:

```
dbug: 2024-02-27 16:37:18.756 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[@p0='Volvo' (Nullable = false) (Size = 150)], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [Company] ([Name])
      VALUES (@p0);
      SELECT [Id]
      FROM [Company]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();

dbug: 2024-02-27 16:37:18.796 CoreEventId.ForeignKeyChangeDetected[10803] (Microsoft.EntityFrameworkCore.ChangeTracking)
      The foreign key property 'Company.Id' was detected as changed from '-1' to '16' for entity with key '{Id: 16}'.
dbug: 2024-02-27 16:37:18.801 CoreEventId.ForeignKeyChangeDetected[10803] (Microsoft.EntityFrameworkCore.ChangeTracking)
      The foreign key property 'Employee.CompanyId' was detected as changed from '-1' to '16' for entity with key '{Id: -1}'.

dbug: 2024-02-27 16:37:18.810 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[@p1='16', @p2='PG Goldenhammer' (Nullable = false) (Size = 200)], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [Employee] ([CompanyId], [Name])
      VALUES (@p1, @p2);
      SELECT [Id]
      FROM [Employee]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();

dbug: 2024-02-27 16:37:18.813 CoreEventId.ForeignKeyChangeDetected[10803] (Microsoft.EntityFrameworkCore.ChangeTracking)
      The foreign key property 'Employee.Id' was detected as changed from '-1' to '16' for entity with key '{Id: 16}'.

dbug: 2024-02-27 16:37:18.828 CoreEventId.StateChanged[10807] (Microsoft.EntityFrameworkCore.ChangeTracking)
      The 'Company' entity with key '{Id: 16}' tracked by 'EFCoreTestContext' changed state from 'Added' to 'Unchanged'.dbug: 2024-02-27 16:37:18.828 
CoreEventId.StateChanged[10807] (Microsoft.EntityFrameworkCore.ChangeTracking)
      The 'Employee' entity with key '{Id: 16}' tracked by 'EFCoreTestContext' changed state from 'Added' to 'Unchanged'.

dbug: 2024-02-27 16:37:18.829 CoreEventId.SaveChangesCompleted[10005] (Microsoft.EntityFrameworkCore.Update)
      SaveChanges completed for 'EFCoreTestContext' with 2 entities written to the database.
```

The line

```
The foreign key property 'Employee.CompanyId' was detected as changed from '-1' to '16' for entity with key '{Id: -1}'.
```

appears before the SQL is executed, and the `@p1` parameter holding the new `Employee.CompanyId` value is `16`, which was the identity generated by the database.

## EF Core 8

Here's the log for EF Core 8:

```
dbug: 2024-02-27 16:33:35.619 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[@p0='Volvo' (Nullable = false) (Size = 150), @p1='-1' (Nullable = true), @p2='PG Goldenhammer' (Nullable = false) (Size = 200)], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [Company] ([Name])
      VALUES (@p0);
      SELECT [Id]
      FROM [Company]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();

      INSERT INTO [Employee] ([CompanyId], [Name])
      VALUES (@p1, @p2);
      SELECT [Id]
      FROM [Employee]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();

dbug: 2024-02-27 16:33:35.669 CoreEventId.ForeignKeyChangeDetected[10803] (Microsoft.EntityFrameworkCore.ChangeTracking)
      The foreign key property 'Company.Id' was detected as changed from '-1' to '15' for entity with key '{Id: 15}'.
dbug: 2024-02-27 16:33:35.674 CoreEventId.ForeignKeyChangeDetected[10803] (Microsoft.EntityFrameworkCore.ChangeTracking)
      The foreign key property 'Employee.CompanyId' was detected as changed from '-1' to '15' for entity with key '{Id: -1}'.

fail: 2024-02-27 16:33:35.710 CoreEventId.SaveChangesFailed[10000] (Microsoft.EntityFrameworkCore.Update)
      An exception occurred in the database while saving changes for context type 'IdentityInsertTest.EFCoreTestContext'.
      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
       ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Employee_Company". The conflict occurred in database "EFCoreTest", table "dbo.Company", column 'Id'.
```

Now, the line

```
The foreign key property 'Employee.CompanyId' was detected as changed from '-1' to '15' for entity with key '{Id: -1}'.
```

appears after the SQL execution and, effectively, the SQL generated uses `-1` for the `@p1` param, causing the error.

## More Info

I've also tried this with EF Core 7, with the same failure as in version 8. Something seems to have changed between 6 and 7.

I don't know if this is supposed to work, or supposed to be used this way. Should we configure differently? The best option would probably be to stop using non-default values for the ids, but that has rather severe implications on our app in it's current state.

The full example, copied from @adolfo1981 and minimally modified, is [here](https://github.com/erikakerfeldt/IdentityInsertTest).

Just in case, we've also tried to configure the tables with triggers (even if they don't have any), to force EF Core to fall back on the old, less effective INSERT syntax ([docs](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes?tabs=v7#sql-server-tables-with-triggers-or-certain-computed-columns-now-require-special-ef-core-configuration)). This does change the SQL emitted, but does not remove the problem.
