### ISSUE TITLE
Set operations for shared type entities are not working

### ISSUE THREAD

**Issue by momvart** [dotnet/efcore#28146]
## Description
(It seems that it is under development in #16298 and also quite similar to #27695, but I didn't see any reference to shared type entities so I opened this issue.)

When using set operations on two `DbSet`s with a shared entity type, EF Core throws an `InvalidOperationException`.

### Code
Consider this simple case:

DbContext:
```C#
public DbSet<TestEntity> Tests => Set<TestEntity>("Tests");

public DbSet<TestEntity> SpecialTests => Set<TestEntity>("SpecialTests");
```

Query:
```C#
context.Tests.Union(context.SpecialTests).ToListAsync()
```

### Stack Trace
```
Unhandled exception. System.InvalidOperationException: Incompatible sources used for set operation.
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ValidateExpressionCompatibility(Expression outer, Expression inner)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ProcessSetOperation(NavigationExpansionExpression outerSource, MethodInfo genericMethod, NavigationExpansionExpression innerSource)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
```

### Provider and version information

EF Core version: 6.0.5
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 6.0

**Comment by momt99** [comment]
@smitpatel Can you give more information on why it is a by-design?

**Comment by smitpatel** [comment]
While the sources which are being union-ed (or any other set operation) have same CLR backing type and it allows LINQ to generate such a query, the query is basically invalid from EF Core or any database perspective in many respects. 

- EF Core generate code to materialize each entity type. While CLR type is the same the code to generate entity type could be different. e.g. using field/property to initialize (or different ctor though currently we don't allow configuring a ctor which could change in future). This affect both tracking/non-tracking query.
- Even if materialization path is the same, in tracking query, EF Core would also need to track entity instances along with their shadow property values.

Both of above would require EF Core to know which entity is coming from which part of set operation source. Once we perform set operation on server side, we lose that information and there is no way for us to know how to materialize the results. One way would be to inject an extra column in both side as discriminator which tells which source generated the row (first or second), that would also fall apart in the case when set operation with distinct is used (`UNION` vs `UNION ALL` where former removes duplicates). If duplicates are removed how would one determine if first materialization should be used or second one.

So server evaluating set operation is not really feasible, client evaluating them is same as user doing themselves by calling `AsEnumerable` API. In this case, each side can materialize something before performing the operation client so none of above issues would happen.

A very straight-fwd way to look at it is, you cannot perform set operation between 2 different entity types which are not in same hierarchy as they would 2 totally unrelated entity types. You can write set operation between 2 arbitrary entity types by just using object as generic type of set operation. Even though it is valid in LINQ, it is invalid from database perspective and serves no purpose.

**Comment by momt99** [comment]
Thanks for the explanation.
The tracking seems to be infeasible. And for simple non-tracking cases, we can project it to the entity itself.
