### ISSUE TITLE
Cannot save changes for an entity of type 'ExternalObject' in state 'Unchanged'.

### ISSUE THREAD

**Issue by Zarokhan** [dotnet/efcore#28152]
## File a bug

Have a problem in production environment. The error message tells me to open an issue here.
Will update EF to 6.0.5 and try to reproduce in Test project.

```
Result: An exception occurred in the database while saving changes for context type 'WeHUB.DataLayer.Enteties.WeHUBContext'.
System.InvalidOperationException: Cannot save changes for an entity of type 'ExternalObject' in state 'Unchanged'. This may indicate a bug in Entity Framework, please open an issue at https://go.microsoft.com/fwlink/?linkid=2142044. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the key values of the entity.
```

### Include your code

Code is not open source and can't send all of it here. :(

Beginning of UpsertWorkplace
```C#
            bool cpNew = false;
            ExternalObject cpObject;

            lock (_workplaceLock)
            {
                cpObject = customer.ExternalObjects.SingleOrDefault(x => x.ExternalConnectionId == CpConstants.CpExternalConnectionId);
                if (cpObject == null)
                {
                    cpObject = CreateExternalObject(customer, null);
                    _context.ExternalObjects.Add(cpObject);
                    _context.SaveChanges();
                    cpNew = true;
                }
            }
```

CreateExternalObject
```C#
        private ExternalObject CreateExternalObject(Customer customer, CpWorkplace workplace)
        {
            var now = DateTime.UtcNow;
            return new ExternalObject
            {
                Id = Guid.NewGuid(),
                CustomerId = customer.Id,
                ExternalObjectId = workplace == null ? CpConstants.TempExId : workplace.id.ToString(),
                ExternalConnectionId = CpConstants.CpExternalConnectionId,
                CreatedUtc = now,
                SyncedDate = now,
                Name = customer.Name,
            };
        }
```

### Include stack traces

```
Exception while executing function: Functions.CheckProofMachineSubscriber Result: Failure
Exception: System.AggregateException: One or more errors occurred. (Cannot save changes for an entity of type 'ExternalObject' in state 'Unchanged'. This may indicate a bug in Entity Framework, please open an issue at https://go.microsoft.com/fwlink/?linkid=2142044. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the key values of the entity.)
 ---> System.InvalidOperationException: Cannot save changes for an entity of type 'ExternalObject' in state 'Unchanged'. This may indicate a bug in Entity Framework, please open an issue at https://go.microsoft.com/fwlink/?linkid=2142044. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the key values of the entity.
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.AddEntry(IUpdateEntry entry, Boolean mainEntry)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.CreateModificationCommands(IList`1 entries, IUpdateAdapter updateAdapter, Func`1 generateParameterName)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.BatchCommands(IList`1 entries, IUpdateAdapter updateAdapter)+MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__104_0(DbContext _, ValueTuple`2 t)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at WeHUB.Func.Infrastructure.Logic.SyncCheckProof.SyncCheckProofLogic.UpsertWorkplace(Customer customer, Boolean runUpdate, DateTime syncStart) in D:\a\1\s\WeHUB.Func\Infrastructure\Logic\SyncCheckProof\SyncCheckProofLogic.cs:line 662
   at WeHUB.Func.Infrastructure.Logic.SyncCheckProof.SyncCheckProofLogic.SyncUnit(Machine machine, Boolean update, DateTime syncStart) in D:\a\1\s\WeHUB.Func\Infrastructure\Logic\SyncCheckProof\SyncCheckProofLogic.cs:line 0
   at WeHUB.Func.Functions.CheckProofMachineSubscriber.Run(EventGridEvent input, FunctionContext context) in D:\a\1\s\WeHUB.Func\Functions\CheckProofMachineSubscriber.cs:line 51
   at Microsoft.Azure.Functions.Worker.Invocation.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in D:\a\1\s\src\DotNetWorker.Core\Invocation\VoidTaskMethodInvoker.cs:line 24
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
   at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 167
Stack:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
   at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 167 
```

### Include provider and version information

EF Core version: 6.0.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 6.0)
Operating system: Windows 10
IDE: (e.g. Visual Studio 2022 17.1.1)

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by Zarokhan** [comment]
It works in test and qa environment. Can only reproduce in prod environment. 

It might be concurrent issue. Altough our concurrent tests pass. May be DI lifetime issue, noticed dbcontext was injected in singleton service. Might be solvable by IServiceScopeFactory.

Will try get back with runnable project in time. This code is running from azure function event grid.
