### ISSUE TITLE
Cannot convert to nullable types when underlaying type is different in Indexer Properties

### ISSUE THREAD

**Issue by YeskaNova** [dotnet/efcore#28222]
Json serializers will often convert the numbers in a dictionary<string,object> to the smallest type, "90" will be converted to byte. When this dictionary has indexerProperty, it will work as long as the indexerProperty is not nullable, but if we want the column in the database to be nullable, we must set the indexerProperty type to nullable and in this situation the conversion will fail if the deserialized value has not exactly the same type as the underlaying type of the indexerProperty type ( even if there is an implicit conversion like int=>long? ).

### Code
```C#
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

public class User
{
    public int Id { get; set; }
    public Dictionary<string, object> Data { get; set; }
    public long? Number { get; set; }
}

public class SqlServerDbContext : DbContext
{
    public SqlServerDbContext(DbContextOptions options) : base(options)
    { }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        var etb = modelBuilder.Entity<User>();
        etb.HasKey(x => x.Id);
        etb.Property(x => x.Number);
        etb.OwnsOne(x => x.Data, x =>
        {
            x.IndexerProperty(typeof(long?), "Number");
        });
    }
}

class Program
{
    static void Main(string[] args)
    {
        var sc = new ServiceCollection();
        var guid = Guid.NewGuid();
        sc.AddDbContext<SqlServerDbContext>(op => op.UseSqlServer(@"Server=(localdb)\MSSQLLocalDB;Integrated Security=true;DataBase=" + guid));
        using (var provider = sc.BuildServiceProvider())
        {
            using (var scope = provider.CreateScope())
            using (var dbcontext = scope.ServiceProvider.GetService<SqlServerDbContext>())
            {
                dbcontext.Database.EnsureCreated();
            }
            var user = new User()
            {
                Number = 5
            };
            using (var scope = provider.CreateScope())
            using (var dbcontext = scope.ServiceProvider.GetService<SqlServerDbContext>())
            {
                dbcontext.Set<User>().Add(user);
                dbcontext.SaveChanges();
            }
            var user2 = new User()
            {
                Data = new Dictionary<string, object>() { { "Number", 5 } }
            };
            using (var scope = provider.CreateScope())
            using (var dbcontext = scope.ServiceProvider.GetService<SqlServerDbContext>())
            {
                dbcontext.Set<User>().Add(user2);
                dbcontext.SaveChanges();
            }
        }
    }
}
```

### Stack traces
```
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'System.Int32' to type 'System.Nullable`1[System.Int64]'.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.OriginalValues..ctor(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.EnsureOriginalValues()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntrySubscriber.SnapshotAndSubscribe(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Add(TEntity entity)
   at Program.Main(String[] args)

  This exception was originally thrown at this call stack:
    Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.OriginalValues.OriginalValues(Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry)
    Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.EnsureOriginalValues()
    Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntrySubscriber.SnapshotAndSubscribe(Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry)
    Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry)
    Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(Microsoft.EntityFrameworkCore.EntityState, Microsoft.EntityFrameworkCore.EntityState, bool, bool)
    Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(Microsoft.EntityFrameworkCore.EntityState, bool, bool, Microsoft.EntityFrameworkCore.EntityState?)
    Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntryGraphNode<(Microsoft.EntityFrameworkCore.EntityState TargetState, Microsoft.EntityFrameworkCore.EntityState StoreGenTargetState, bool Force)>)
    Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph<TState>(Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntryGraphNode<TState>, System.Func<Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntryGraphNode<TState>, bool>)
    Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph<TState>(Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntryGraphNode<TState>, System.Func<Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntryGraphNode<TState>, bool>)
    Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry, Microsoft.EntityFrameworkCore.EntityState, Microsoft.EntityFrameworkCore.EntityState, bool)
    ...
    [Call Stack Truncated]
```

### Provider and version information

EF Core version: 6.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0

**Comment by ajcvickers** [comment]
@YeskaNova I can't reproduce the nullable aspect of this. When the indexer property is `x.IndexerProperty(typeof(long), "Number")`, I get `System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.Int64'`

**Comment by YeskaNova** [comment]
@ajcvickers I confirm, It seems more general. That means that we will need to rework any deserialized IDictionary to exactly match the mapped types. If EF Core were tolerent when implicit cast exists that would help a lot.
