### ISSUE TITLE
Attempting to view ExportedTypes throws not found exception

### ISSUE THREAD

**Issue by Jetski5822** [dotnet/efcore#2824]
Hey All,

When trying to load EntityFramework.Core from code (just as an example) using:

```
var assem = Assembly.LoadFrom("C:\\Users\\Nicholas\\.dnx\\packages\\EntityFramework.Core\\7.0.0-beta7-13922\\lib\\dnx451\\EntityFramework.Core.dll")
```

examining Exported types throws a 'System.IO.FileNotFoundException' on System.Interactive.Async

```
assem.ExportedTypes
'assem.ExportedTypes' threw an exception of type 'System.IO.FileNotFoundException'
    Data: {System.Collections.ListDictionaryInternal}
    FileName: "System.Interactive.Async, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
    FusionLog: "=== Pre-bind state information ===\r\nLOG: DisplayName = System.Interactive.Async, Version=1.2.0.0, Culture=neutral,
 PublicKeyToken=31bf3856ad364e35\n (Fully-specified)\r\nLOG: 
Appbase = file:///C:/Users/Nicholas/.dnx/runtimes/dnx-clr-win-x86.1.0.0-beta7-12335/bin/\r\nLOG: Initial PrivatePath = NULL\r\nCalling assembly : EntityFramework.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null.\r\n===\r\nLOG: This bind starts in LoadFrom load context.\r\nWRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().\r\nLOG: No application configuration file found.\r\nLOG: Using host configuration file: \r\nLOG: Using machine configuration file from C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\config\\machine.config.\r\nLOG: The same bind was seen before, and was failed with hr = 0x80070002.\r\n"
    HResult: -2147024894
    HelpLink: null
    InnerException: null
    Message: "Could not load file or assembly 'System.Interactive.Async, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified."
    Source: "mscorlib"
    StackTrace: "   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)\r\n   at System.Reflection.RuntimeAssembly.GetExportedTypes()\r\n   at System.Reflection.Assembly.get_ExportedTypes()"
    TargetSite: {Void GetExportedTypes(System.Reflection.RuntimeAssembly, System.Runtime.CompilerServices.ObjectHandleOnStack)}
```

Any ideas on how I can get the exported types stuff to work?

**Comment by davidfowl** [comment]
Don't use LoadFrom. Why are you using that?

**Comment by Jetski5822** [comment]
That was just an example of the shortest way I could repro.

I am using the RoslynProjectCompiler to compile my project and then using the metadata reference to load it. The Assembly gets loaded, but throws a not found exception looking at ExportedTypes saying..

```
System.IO.FileNotFoundException: Could not load file or assembly 'EntityFramework.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'EntityFramework.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at OrchardVNext.Environment.Extensions.Loaders.DynamicExtensionLoader.Load(ExtensionDescriptor descriptor) in D:\Brochard\src\OrchardVNext\Environment\Extensions\Loaders\DynamicExtensionLoader.cs:line 57
   at OrchardVNext.Environment.Extensions.ExtensionManager.BuildEntry(ExtensionDescriptor descriptor) in D:\Brochard\src\OrchardVNext\Environment\Extensions\ExtensionManager.cs:line 132
   at OrchardVNext.Environment.Extensions.ExtensionManager.LoadFeature(FeatureDescriptor featureDescriptor) in D:\Brochard\src\OrchardVNext\Environment\Extensions\ExtensionManager.cs:line 91
```

I then tried to load EntityFramework.Core directly, and it threw the exception to do with System.Interactive.Async.

**Comment by natemcmaster** [comment]
I'm guessing this error is because you haven't given the compiler all of EntityFramework.Core's [dependencies](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Core/project.json).

**Comment by Jetski5822** [comment]
Yeah, I thought the same, but when I viewed what gets passed to the Roslyn compiler it all looked good. Infact System.Interactive.Async was top of the list.

**Comment by rowanmiller** [comment]
@bricelam doesn't look like an EF issue but can you help route it where it needs to go

**Comment by Jetski5822** [comment]
You were right, this is not an EF issue afterall, but more down to the way I was resolving dependencies. Cheers,. N
