### ISSUE TITLE
SET Operations with client side collection Failing - Value cannot be null. (Parameter 'body')

### ISSUE THREAD

**Issue by ankitmatrix08** [dotnet/efcore#28285]
I am a bit surprised with the below failures, not sure if it has been raised already.
None of the below SET operations work:

**Query:**

```
var someMoreIds = "50,51,52".ConvertCSVToLong();

var q1 = from u in context.Users
               select u.Id;
var q2 = q1.Union(someMoreIds);
var q3 = q1.Except(someMoreIds);
var q4 = q1.Intersect(someMoreIds);

```

**Exception & Stack Trace:**

```
Value cannot be null. (Parameter 'body')

Source: System.Linq.Expressions
Param Name: body

   at System.Dynamic.Utils.ContractUtils.RequiresNotNull(Object value, String paramName, Int32 index)
   at System.Dynamic.Utils.ExpressionUtils.RequiresCanRead(Expression expression, String paramName, Int32 idx)
   at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters, String paramName)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, ParameterExpression[] parameters)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.SystemCore_EnumerableDebugView`1.get_Items()
```

**Models:**

```
public partial interface IUser
	{
                long Id { get; }
		long CreatedById { get; }
	}

public partial interface IUserSiteAccess
	{
                long Id { get; }
		long? UserId { get; }
                long CreatedById { get; }
	}

public partial class BananaContext : AbstractDbContext
    {
        public BananaContext()
        {
            ChangeTracker.AutoDetectChangesEnabled = false;
        }

        public BananaContext(DbContextOptions<BananaContext> options)
        {
        }
       public virtual DbSet<EUser> Users { get; set; }
   }

 public static IEnumerable<long> ConvertCSVToLong(this string idsInCSV)
        {
            return idsInCSV.IsBlank() ? new List<long>() : idsInCSV.Split(',').Select(id => Convert.ToInt64(id));
        }

```

EF Core version: 7.0.0-preview.4.22229.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Win 10 Pro
IDE: Visual Studio 2022 v17.0.4

**Comment by smitpatel** [comment]
Same as #17031

**Comment by ajcvickers** [comment]
@ankitmatrix08 The [release planning process](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning) covers how we decide what to work on for each release. Given that #17031 has no votes, its priority is currently quite low and I wouldn't expect to see it worked on very soon.
