### ISSUE TITLE
dotnet ef dbcontext scaffold works fine when executed from command line, but not when executed from code

### ISSUE THREAD

**Issue by pgmariotti** [dotnet/efcore#28333]
## Ask a question

Remember:

* Please make your question as clear and specific as possible.
* Please check that the [documentation](https://docs.microsoft.com/ef/) does not answer your question.
* Please search in both [open](https://github.com/dotnet/efcore/issues) and [closed](https://github.com/dotnet/efcore/issues?q=is%3Aissue+is%3Aclosed) issues to check that your question has not already been answered.

### Include your code

Usually the best way to ask a clear question and get a quick response is to show your code. Preferably, attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing.

Use triple-tick code fences for any posted code. For example:

```C#
Console.WriteLine("Hello, World!");
```

### Include stack traces

Include the full exception message and stack trace for any exception you encounter.

Use triple-tick fences for stack traces. For example:

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at SixFour.Sub() in C:\Stuff\AllTogetherNow\SixFour\SixFour.cs:line 49
   at SixFour.Main() in C:\Stuff\AllTogetherNow\SixFour\SixFour.cs:line 54
```

### Include verbose output

Please include verbose output when asking questions about the `dotnet ef` or Package Manager Console tools.

Use triple-tick fences for tool output. For example:

```
C:\Stuff\AllTogetherNow\FiveOh>dotnet ef dbcontext list --verbose
Using project 'C:\Stuff\AllTogetherNow\FiveOh\FiveOh.csproj'.
...
Finding DbContext classes in the project...
Found DbContext 'BlogContext'.
BlogContext
```

### Include provider and version information

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 5.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by pgmariotti** [comment]
I have attached a project that shows the problem.
Compile and run, then choose either SqlServer or MySql. This will fill the necessary connection string daya in the form.
Click on ShowDatabaseNames button.
The result has been restricted to showing only one database.
Click on the database name, and its tables will be shown.
Click on the Generate button.
The project creates its working folder the Temp folder for the user, with a name equal to the chosen database name.
The generated code is in a subfolder called "Model".
On completion of the code generation, the Model folder only contains the DBContext, and no classes have been generated for the tables.
When exactly the same statements run from a command line, the whole model mis generated correctly in the target folder, for the chosen database.
The project works the same way for both SqlServer and MySql databases.
The project is a NetMaui project, using the Net6.0 version of the libraries.

[ApiWizard.zip](https://github.com/dotnet/efcore/files/9017109/ApiWizard.zip)
