### ISSUE TITLE
Trying to insert a new entity with childs throws DbUpdateException

### ISSUE THREAD

**Issue by nicbourgoin** [dotnet/efcore#2844]
This has been an issue for a long time: You cannot insert an entity if it has new instances of relationships there are two issues:

```
using System.Collections.Generic;
using Microsoft.Data.Entity;

namespace EfNestedInsertTest
{
    #region Entities

    public class JobType
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public IList<Person> People { get; set; }
    }

    public class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public int JobType_Id { get; set; }
        public JobType JobType { get; set; }

        public IList<Pet> Pets { get; set; }
    }

    public class Pet
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public int Person_Id { get; set; }
        public Person Person { get; set; }
    }

    #endregion

    public class MyContext : DbContext
    {
        public DbSet<Person> People { get; set; }
        public DbSet<JobType> JobTypes { get; set; }
        public DbSet<Pet> Pets { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(
                "Data Source=localhost\\SQLEXPRESS;Initial Catalog=EfTest;Password=yourpass;user id=sa;MultipleActiveResultSets=true;");


            base.OnConfiguring(optionsBuilder);
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.UseSqlServerIdentityColumns();

            builder.Entity<Person>().ToTable("Person");
            builder.Entity<Person>().Key(p => p.Id);


            builder.Entity<Person>()
                .Reference(p => p.JobType)
                .InverseCollection(x => x.People)
                .ForeignKey(c => c.JobType_Id);
            builder.Entity<Person>()
                .Collection(p => p.Pets)
                .InverseReference(p => p.Person)
                .ForeignKey(p => p.Person_Id);

            builder.Entity<JobType>().ToTable("JobTypes");
            builder.Entity<JobType>().Key(jt => jt.Id);

            builder.Entity<Pet>().ToTable("Pets");
            builder.Entity<Pet>().Key(p => p.Id);
        }
    }

    public class Program
    {
        public void Main(string[] args)
        {
            var context = new MyContext();
            var nick = new Person
            {
                Name = "Nick",
                JobType = new JobType
                {
                    Name = "LeadDev"
                },
                Pets = new List<Pet>
                {
                    new Pet {Name = "Peanut"},
                    new Pet {Name = "Gypsy"},
                    new Pet {Name = "Daisy"},
                    new Pet {Name = "Shooter"},
                }
            };

            context.People.Add(nick);
            context.SaveChanges();
        }
    }
}
```

This occurs in many-to-one relationships.

> The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Person_JobType_JobType_Id". The conflict occurred in database "EfTest", table "dbo.JobTypes", column 'Id'.

No exception is thrown if the foreign key is not present in the model. However, the jobtype still doesn't get persisted.

StackTrace:

```  
   at Microsoft.Data.Entity.Update.ReaderModificationCommandBatch.Execute(IRelationalTransaction transaction, IRelationalTypeMapper typeMapper, DbContext context, ILogger logger)
   at Microsoft.Data.Entity.Update.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.Data.Entity.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.Data.Entity.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.Data.Entity.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.Data.Entity.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.Data.Entity.DbContext.SaveChanges()
   at EfNestedInsertTest.Program.Main(String[] args) in C:\WS\ef7\src\EfNestedInsertTest\Program.cs:line 100
```

If I use an existing jobtype instead:

```
var context = new MyContext();
            var nick = new Person
            {
                Name = "Nick",
                JobType_Id = 1,
                Pets = new List<Pet>
                {
                    new Pet {Name = "Peanut"},
                    new Pet {Name = "Gypsy"},
                    new Pet {Name = "Daisy"},
                    new Pet {Name = "Shooter"},
                }
            };

            context.People.Add(nick);
            context.SaveChanges();
```

No exception is thrown, however no pets are persisted and the pets' generated Person_Id stays at "-1" while nick's Id got updated to it's identity value.

I wasn't sure If I needed to create 2 different issues.

**Comment by rowanmiller** [comment]
Hey,

Currently in EF7 `Add()` only adds the single object and does not traverse related objects - so you need to add each object individually or use the `TrackGraph` method. We have https://github.com/aspnet/EntityFramework/issues/2726 to track working out how we best support the "add this graph of objects" scenario.

~Rowan

**Comment by nicbourgoin** [comment]
You just gave a new meaning to my entire life. :smile:
