### ISSUE TITLE
EF 7.0.0-preview.6.22329.4: Method not found: 'Void CoreTypeMappingParameters..ctor...

### ISSUE THREAD

**Issue by barruka** [dotnet/efcore#28496]
I tried to use EF 7.0.0-preview.6.22329.4 just changing the package reference in a current running and tested project, from 
```
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.7" />
```
to 
```
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.0-preview.6.22329.4" />
```

EF Core version: 7.0.0-preview.6.22329.4
Database provider: MySql.EntityFrameworkCore, Version 6.0.1
Target framework: net 7.0
Operating system: Windows 10
IDE: VSCode

```
[08:44:56 ERR] Method not found: 'Void CoreTypeMappingParameters..ctor(System.Type, Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, System.Func`3<Microsoft.EntityFrameworkCore.Metadata.IProperty,Microsoft.EntityFrameworkCore.Metadata.IEntityType,Microsoft.EntityFrameworkCore.ValueGeneration.ValueGenerator>)'.
[08:44:56 INF] Executing ConflictObjectResult, writing value of type 'System.Collections.Generic.KeyNotFoundException'.
[08:44:56 INF] Executed action Shop.Catalog.Infrastructure.Api.BrandController.GetAll (Shop.Catalog.Infrastructure.Api) in 553.4159ms
[08:44:56 INF] Executed endpoint 'Shop.Catalog.Infrastructure.Api.BrandController.GetAll (Shop.Catalog.Infrastructure.Api)'
```

```
An unhandled exception has occurred while executing the request.
System.NotSupportedException: Serialization and deserialization of 'System.IntPtr' instances are not supported. Path: $.TargetSite.MethodHandle.Value.
 ---> System.NotSupportedException: Serialization and deserialization of 'System.IntPtr' instances are not supported.
   at System.Text.Json.Serialization.Converters.UnsupportedTypeConverter`1.Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(WriteStack& state, NotSupportedException ex)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Entity Brand:
```C#
using Shop.Catalog.Contracts;
using Shop.XCommon.Contracts;

namespace Shop.Catalog.Application;

public class Brand : AggregateRoot
{
    public int StatusId { get; private set; } = (int)Status.Active;

    public bool AllowDiscounts { get; private set; } = true;

    private Brand()
    {
    }

    public Brand(string id, string name, bool? allowDiscounts = false)
    {
        CreatedAt = DateTime.Now;
        UpdatedAt = CreatedAt;

        Id = id ?? throw new ArgumentNullException(nameof(id));
        Name = String.IsNullOrWhiteSpace(name) ? throw new ArgumentNullException(nameof(name)) : name;
        StatusId = (int)Status.Active;
        AllowDiscounts = allowDiscounts ?? true;
    }

    public void Update(BrandUpdateDto dto)
    {
        if (!String.IsNullOrWhiteSpace(dto.Name)) Name = dto.Name;
        if (dto.StatusId != null) StatusId = Convert.ToInt32(dto.StatusId);
        if (dto.AllowDiscounts != null) AllowDiscounts = Convert.ToBoolean(dto.AllowDiscounts);
        if (dto.StatusId != null) StatusId = Convert.ToInt32(dto.StatusId);

        UpdatedAt = DateTime.Now;
    }
}
```

Repository (simplified after removing irrevelant methods to reproduce the bug):
```C#
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.Extensions.Logging;

using Shop.XCommon.Contracts;

namespace Shop.Catalog.Infrastructure.EF;

public class Repository<T> : IRepository<T> where T : EntityBase
{
    private readonly AppDbContext _dbContext;
    private readonly ILogger<Repository<T>> _logger;

    public Repository(AppDbContext dbContext,
                      ILogger<Repository<T>> logger)
    {
        _dbContext = dbContext;
        _logger = logger;
    }

    public async Task<IEnumerable<T>> GetAll()
    {
        try
        {
            return await _dbContext.Set<T>().ToListAsync();
        }
        catch (Exception ex)
        {
            _logger.LogError((ex.InnerException ?? ex).Message);
            return await Task.FromException<IEnumerable<T>>(new KeyNotFoundException((ex.InnerException ?? ex).Message));
        }
    }

}
```

DbContext
```C#

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using Shop.Catalog.Application;
using Shop.XCommon.Contracts;

namespace Shop.Catalog.Infrastructure.EF;

public class AppDbContext : DbContext
{
    private string _connectionString = String.Empty;

    public DbSet<Brand> Brands { get; set; }


    public AppDbContext(string connectionString)
    {
        _connectionString = connectionString;
    }

    public AppDbContext(DbContextOptions options)
    : base(options)
    {
    }

}
```

**Comment by ErikEJ** [comment]
You cannot mix version 6 and 7 like that, you must wait for a version 7 provider for MySql.EntityFrameworkCore
