### ISSUE TITLE
System.AccessViolationException in Add-Migration

### ISSUE THREAD

**Issue by iuridosanjos** [dotnet/efcore#28497]
I get a "System.AccessViolationException" when trying to create a migration with Entity Framework Core.

I already tested inside Visual Studio Package Manager Console and from PowerShell using CLI, both result in the same error.

Here is the CLI example and the result:

```
PS dotnet ef migrations add [migration-name] --project [project-name] --startup-project [project-name]
Build started...
Build succeeded.
```
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

at System.Diagnostics.StackTrace.GetStackFramesInternal(System.Diagnostics.StackFrameHelper, Int32, Boolean, System.Exception)
at System.Diagnostics.StackFrameHelper.InitializeSourceInfo(Int32, Boolean, System.Exception)
at System.Diagnostics.StackTrace.CaptureStackTrace(Int32, Boolean, System.Exception)
at System.Diagnostics.StackTrace..ctor(System.Exception, Boolean)
at System.Exception.get_StackTrace()
at System.Exception.ToString()
at System.Exception.ToString()
at Microsoft.EntityFrameworkCore.Design.OperationExecutor+OperationBase.Execute(System.Action)
at Microsoft.EntityFrameworkCore.Design.OperationExecutor+OperationBase.Execute[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]
at Microsoft.EntityFrameworkCore.Design.OperationExecutor+AddMigration..ctor(Microsoft.EntityFrameworkCore.Design.OperationExecutor, Microsoft.EntityFrameworkCore.Design.IOperationResultHandler, System.Collections.IDictionary)
at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean, Boolean)
at System.Reflection.RuntimeConstructorInfo.Invoke(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
at System.RuntimeType.CreateInstanceImpl(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
at System.Activator.CreateInstance(System.Type, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[])
at System.Activator.CreateInstance(System.Type, System.Object[])
at Microsoft.EntityFrameworkCore.Tools.ReflectionOperationExecutor.Execute(System.String, System.Object, System.Collections.IDictionary)
at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid4[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Runtime.CompilerServices.CallSite, System.__Canon, System.__Canon, System.__Canon, System.__Canon)
at Microsoft.EntityFrameworkCore.Tools.OperationExecutorBase.InvokeOperationImpl(System.String, System.Collections.IDictionary)
at Microsoft.EntityFrameworkCore.Tools.OperationExecutorBase.InvokeOperation[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.String, System.Collections.IDictionary)
at Microsoft.EntityFrameworkCore.Tools.OperationExecutorBase.AddMigration(System.String, System.String, System.String)
at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsAddCommand.Execute()
at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase+<>c__DisplayClass0_0.b__0()
at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(System.String[])
at Microsoft.EntityFrameworkCore.Tools.Program.Main(System.String[])
```

I've also tried things like restarting the PC and Windows Memory Diagnostic tests, but nothing.

Guess it's important to say that I was successfully creating migrations a couple days ago, but this specifically migration is not working. And also the migration is quite simple: just a new property on a class (new column on a table).

I probably can't replicate this in an empty project, but I still wanted to know if someone has some clue about this problem.

Do anyone got any clue about what is happening?

**Comment by ajcvickers** [comment]
@iuridosanjos What versions of .NET, EF Core, VS, and Windows are you using?

**Comment by iuridosanjos** [comment]
@ajcvickers 
.NET 4.8.04084
VS 16.8.3
Windows 10 10.0.19044

**Comment by iuridosanjos** [comment]
I've asked a teammate to get my branch and try to add the migration. It showed another error. It was just a field that should be a property.

The problem was that the "real" exception was being overrided by the AccessViolationException. As I can see, something in my environment/pc is making exception rethows to make an AccessViolationException instead. Don't know why. It already happened in other 2 exceptions that I got testing/running my system, but on those cases I was able to debug and find the first exception and solve it. On this case (EF Core, Add-Migration), I couldn't debug.

Well, I know that this answer don't solve the AccessViolationException, but at least shows what I've experienced, so I guess it was better to share and choose it as an answer for the sake of EF Core.

If someone knows why the AccessViolationException is being throw instead of the original exception, I'll appreciate.

**Comment by ajcvickers** [comment]
@iuridosanjos Are you using EF Core? If so, what version?

**Comment by iuridosanjos** [comment]
> @iuridosanjos Are you using EF Core? If so, what version?

EF Core 3.1.2

I've commented that, in fact, it was not a problem of EF Core, so I guess this issue can be closed.
For some reason, I'm having this "AccessViolationException" when some other exceptions are rethrow.
It's probably something on my environment, don't know what yet. I'll probably try to update .NET SDK and other things to see if it still happens.
