### ISSUE TITLE
System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed

### ISSUE THREAD

**Issue by OldManMeta** [dotnet/efcore#28589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Developing in net6.0

I see this exception multiple times on the deployed solution in Azure, but see no issues in local development machines.

Searching for days - it looks like a previous issue in the way async calls were handled, means that the AWAIT statement almost doesn't work correctly anymore?

Compared with Core3.1 - I could call async methods from my constructors by appending the ConfigureAwait(false) flag to run - but that has absolutely no effect in Core6 - logically it makes sense why that was a poor design choice.

After redesigning every constructor - code in each class now calls the methods that were once executed in the constructor.

The error here states that "A second operation was started on this context instance before a previous operation completed" - if AWAIT is working correctly - I am telling you that this is quite literarily impossible in my code base.

All of the methods are async - so they should have no issues - every single async call is an awaited statement through all of my code bodies.

Async methods that do not return from further async calls return in this type of syntax:
`return await Task.FromResult<SortedDictionary<int, List<BaseNavigationItem>>>(Structure);`

This error(s) shows in my azure logs are intermittent:

`Category: Microsoft.EntityFrameworkCore.Query
EventId: 10100
SpanId: c5781d15ac6fcdc4
TraceId: 389ccc891ca0ad905436cfb87a2223b8
ParentId: 0000000000000000
RequestId: 80001daf-0000-d000-b63f-84710c7967bb
RequestPath: /domains/v1/domainsearch/domains/search
ActionId: bc4d2d7e-a479-4a35-a7ec-557821266d25
ActionName: IMP.Portal.Controllers.Domains.v1.DomainsController.domainsearch (IMP.Portal)

An exception occurred while iterating over the results of a query for context type 'IMP.Data.Account.Data.AccountDbContext'.
System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

Exception: 
System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()`

Perhaps my understanding is wrong, or the usage is changed - I would be thrilled if the answer is simple and it is my mistake.
Many thanks any guidance here.

 

### Expected Behavior

My expectation is that async methods called with the AWAIT keyword, execute the method completely, before returning the execution of the calling thread.

### Exceptions (if any)

Category: Microsoft.EntityFrameworkCore.Query
EventId: 10100
SpanId: 26c5a189456f3711
TraceId: 24da3e85238ce5b0366fd47433180986
ParentId: 0000000000000000
RequestId: 80003890-0000-da00-b63f-84710c7967bb
RequestPath: /
ActionId: 0eea45ff-d3ec-4e82-a1ba-3a5bec8a6bf4
ActionName: IMP.Portal.Controllers.IMZone.v1.IMZoneController.IMZoneHome (IMP.Portal)

An exception occurred while iterating over the results of a query for context type 'IMP.Data.Account.Data.AccountDbContext'.
System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

Exception: 
System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

### .NET Version

6.0

### Anything else?

.NET SDK (reflecting any global.json):
 Version:   6.0.302
 Commit:    c857713418

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.302\

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  3.1.421 [C:\Program Files\dotnet\sdk]
  5.0.407 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.107 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by OldManMeta** [comment]
@javiercn thank you very much for the support.

**Comment by OldManMeta** [comment]
Hi @ajcvickers - if we take the diagram above as the basis - I only use a single injected instance through the controller, pulling connection from KeyVault:

`    builder.Services.AddDbContext<AccountDbContext>(options =>
        options.UseSqlServer(connectionStringAccount));`

Careful to ensure that I don't hit threading issues, the context is passed down through a series of async methods - all return Task or Task<t>, all are awaited at source.

Any non async methods calls to libraries for example, where an async method is not exposed, I wrap the returns in, for example:
`return await Task.FromResult<T>(result);`


As depicted, and by my understanding of "enclosed async method completion" - I do not believe I have an opportunity to call anything with the context at the same time. The methods either complete or they don't. The context is never used in a primary method e.g. as in the diagram, method 1 & 2 never use the context directly, they are passed down to child async methods.
Error handling and try/catch on every single method - nothing in that flow uses any context at all.

The really interesting thing here is that in this particular solution, there are only lookups with EF linq - no saves, updates etc. Nothing complex in terms of join statements from Include/TheInclude etc

When, and if I need to do that, an external call is made to an API, that uses the exact same pattern and creates its own instance of the context, because it's an entirely different solution, on an entirely different server etc. That solution does not show any errors.

I have just reviewed the logs - I am not seeing any errors now for 16 hours.

There are no source changes between the two deployments - just broke my head for a few days.

My take on it is this - I think 3.1 was possibly more forgiving of things, in particular, return statements - which I also believe the changes made to 6 - have ultimately made me design my constructors better, and really consider the flow of method calls.

I don't have any scenarios where two methods on the same controller are in play, such as an Ajax calls back to a serving controller, and my Null handling is now in a robust state.

The evidence suggest, that this is more than likely some bump in the deployment road - a confused nuget version, or some how a stale reference to something. I actually wish it was something in my code that I could point to and say - yes, I am the idiot here. This was the problem.

This has been extremely painful - I'm talking about a product launch, not just an update. But actually, I think my code is all the better because of it.

Thank you everyone for the support, making me think about stuff and making me quadruple check stuff.

If I see it again - perhaps we can go full crazy on logs etc, and I'll replicate the code in a repo for comparison etc.

I'll close it out - reopen if it comes back.

Have a great day everyone. Cheers
