### ISSUE TITLE
Query: Allow use of navigations in ExecuteUpdate set values

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#28627]
```C#
context.Customers.ExecuteUpdate(s => s.SetProperty(c => c.Property, c => c.Navigation.Value));
```
Nav expansion needs to expand `c.Navigation` but it is inside doubly nested lambda hence it doesn't recognize implicitly and requires relational to influence. Scoped out of 7.0 release.
Work-around is to expand navigations in advance.
```C#
context.Customers.Select(c => new { c, c.Navigation }).ExecuteUpdate(s => s.SetProperty(c => c.c.Property, c => c.Navigation.Value));
// or
context.Customers.Select(c => new { c, FirstOrder = c.Orders.OrderBy(o => o.OrderID).FirstOrDefault() })
    .ExecuteUpdate(s => s.SetProperty(c => c.c.Property, c => c.FirstOrder.Date));
```

**Comment by anoordover** [comment]
@smitpatel you mention a work-around. Should this work-around also work for:
var query = Context.Set<Crediteringsregel>()
                .Where(c => c.CrediteringId == id)
                .Select(c => new 
                {
                    c,
                    D = Context.Set<Declaratie>().FirstOrDefault(d => d.KenmerkNl == c.KenmerkDeclaratieNl &&
                                                                      d.VorderingId == vorderingId)
                })
                .ExecuteUpdate(c => c.SetProperty(x => x.c.DeclaratieId, x => x.D.Id));

I have Owned properties in both entities.
Currently I get the error:
System.InvalidOperationException: The LINQ expression 'DbSet<Crediteringsregel>()
    .Where(c => c.CrediteringId == __id_0)
    .Select(c => new { 
        c = IncludeExpression(
            EntityExpression:
            IncludeExpression(
                EntityExpression:
                IncludeExpression(
                    EntityExpression:
                    c, 
                    NavigationExpression:
                    EF.Property<Organisatie>(c, "Debiteur"), Debiteur)
                , 
                NavigationExpression:
                EF.Property<Persoon>(c, "Persoon"), Persoon)
            , 
            NavigationExpression:
            EF.Property<Periode>(c, "Uitkeringsperiode"), Uitkeringsperiode)
        , 
        D = DbSet<Declaratie>()
            .Where(d => d.KenmerkNl == c.KenmerkDeclaratieNl && d.VorderingId == __vorderingId_1)
            .Select(d => IncludeExpression(
                EntityExpression:
                IncludeExpression(
                    EntityExpression:
                    IncludeExpression(
                        EntityExpression:
                        d, 
                        NavigationExpression:
                        EF.Property<Organisatie>(d, "Debiteur"), Debiteur)
                    , 
                    NavigationExpression:
                    EF.Property<Persoon>(d, "Persoon"), Persoon)
                , 
                NavigationExpression:
                EF.Property<Periode>(d, "Uitkeringsperiode"), Uitkeringsperiode)
            )
            .FirstOrDefault()
     })
    .ExecuteUpdate(c => c.SetProperty<long?>(
        propertyExpression: x => x.c.DeclaratieId, 
        valueExpression: x => (long?)x.D.Id))' could not be translated. Additional information: The following lambda argument to 'SetProperty' does not represent a valid property to be set: 'x => x.c.DeclaratieId'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.RelationalQueryableExtensions.ExecuteUpdate[TSource](IQueryable`1 source, Expression`1 setPropertyCalls)
   at HetCak.Vbo.Infrastructure.Repositories.Wuvo.CrediteringsregelRepository.KoppelDeclaratiesAanCrediteringRegels(Int64 vorderingId, Nullable`1 crediteringId) in /home/arno/RiderProjects/VBO_NET/source/VboServices/Infrastructure/HetCak.Vbo.Infrastructure.Repositories/Wuvo/CrediteringsregelRepository.cs:line 110
   at HetCak.Vbo.EventHandler.Api.Controllers.EventHandlerController.Stop() in /home/arno/RiderProjects/VBO_NET/source/VboServices/Apis/EventHandler/HetCak.Vbo.EventHandel.Api/Controllers/EventHandlerController.cs:line 34
   at lambda_method3(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()

**Comment by roji** [comment]
@anoordover can you confirm that this works for you if no owned entities are involved? If so, see #28727 which is specifically about owned entities in ExecuteUpdate and has nothing to do with navigations.

**Comment by anoordover** [comment]
@roji I will try to create a simple project containing two tables and try executing an update like this. But for now:
I debugged the code and saw that inside IsValidPropertyAccess in RelationalQueryableMethodTranslatingExpressionVisitor the statement x.c.DeclaratieId is a Microsoft.EntityFrameworkCore.Query.IncludeExpression

**Comment by roji** [comment]
That sounds like #28727. You may simply try running with the latest [daily build](https://github.com/dotnet/efcore/blob/main/docs/DailyBuilds.md) of EF, where this has already been fixed.

**Comment by anoordover** [comment]
Using version 8.0.0-alpha.1.22620.2 (is this the latest?) I get the exception:

```
System.InvalidOperationException: The LINQ expression 'DbSet<Crediteringsregel>()
    .Where(c => c.CrediteringId == __id_0 && DbSet<Declaratie>()
        .Any(d => d.VorderingId == __vorderingId_1 && d.KenmerkNl == c.KenmerkDeclaratieNl))
    .Select(c => new { 
        c = IncludeExpression(
            EntityExpression:
            IncludeExpression(
                EntityExpression:
                IncludeExpression(
                    EntityExpression:
                    c, 
                    NavigationExpression:
                    EF.Property<Organisatie>(c, "Debiteur"), Debiteur)
                , 
                NavigationExpression:
                EF.Property<Persoon>(c, "Persoon"), Persoon)
            , 
            NavigationExpression:
            EF.Property<Periode>(c, "Uitkeringsperiode"), Uitkeringsperiode)
        , 
        D = DbSet<Declaratie>()
            .Where(d0 => d0.KenmerkNl == c.KenmerkDeclaratieNl && d0.VorderingId == __vorderingId_1)
            .Select(d0 => IncludeExpression(
                EntityExpression:
                IncludeExpression(
                    EntityExpression:
                    IncludeExpression(
                        EntityExpression:
                        d0, 
                        NavigationExpression:
                        EF.Property<Organisatie>(d0, "Debiteur"), Debiteur)
                    , 
                    NavigationExpression:
                    EF.Property<Persoon>(d0, "Persoon"), Persoon)
                , 
                NavigationExpression:
                EF.Property<Periode>(d0, "Uitkeringsperiode"), Uitkeringsperiode)
            )
            .FirstOrDefault()
     })
    .ExecuteUpdate(c => c.SetProperty<long?>(
        propertyExpression: x => x.c.DeclaratieId, 
        valueExpression: x => (long?)x.D.Id))' could not be translated. Additional information: The following 'SetProperty' failed to translate: 'SetProperty(x => x.c.DeclaratieId, x => (long?)x.D.Id)'.  See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.RelationalQueryableExtensions.ExecuteUpdate[TSource](IQueryable`1 source, Expression`1 setPropertyCalls)
   at HetCak.Vbo.Infrastructure.Repositories.Wuvo.CrediteringsregelRepository.KoppelDeclaratiesAanCrediteringRegels(Int64 vorderingId, Nullable`1 crediteringId) in /home/arno/RiderProjects/VBO_NET/source/VboServices/Infrastructure/HetCak.Vbo.Infrastructure.Repositories/Wuvo/CrediteringsregelRepository.cs:line 106
   at HetCak.Vbo.EventHandler.Api.Controllers.EventHandlerController.Stop() in /home/arno/RiderProjects/VBO_NET/source/VboServices/Apis/EventHandler/HetCak.Vbo.EventHandel.Api/Controllers/EventHandlerController.cs:line 34
   at lambda_method3(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
```

**Comment by anoordover** [comment]
Btw I'm using an Oracle database. Is this Oracle related?

**Comment by anoordover** [comment]
With sqlserver using ef core 7 everything seems to work OK (see attached git repo).
Is this a bug in the Oracle implementation?

**Comment by anoordover** [comment]
I've got more information about the problems. In my production code the target and source table both had "Owned" properties. I added a new branch to my project (https://github.com/anoordover/ExecuteUpdate/tree/feature/AddOwnedPropertyPreReleaseTest2) to reproduce the errors.
The first two statements in https://github.com/anoordover/ExecuteUpdate/blob/feature/AddOwnedPropertyPreReleaseTest2/ExecuteUpdateDemo/Program.cs fail. The last one runs correctly.

The first two fail with the message:
The following 'SetProperty' failed to translate: 'SetProperty(c => c.credit.DeclarationId, c => (long?)c.declaration.Id)'

@roji can you look at this as well?

**Comment by anoordover** [comment]
To summarize when using ExecuteUpdate with a target and source table:

- The pre-release solved the issue with Owned properties in the target table;
- When the source-table contains an Owned property you need to select the fields that are used in the ExecuteUpdate statement. I suppose you cannot use an Owned property from the source table.

**Comment by anoordover** [comment]
@roji about your question about the Oracle issue see https://github.com/oracle/dotnet-db-samples/issues/270

**Comment by roji** [comment]
Thanks. So it seems like an issue specifically with some patterns of using Join/navigations, rather than a general incompatibility of the Oracle provider with ExecuteUpdate. If that issue is basically the same as this one (i.e. not specific to Oracle), I'll try to take a look at it, though it might be some time before I'm able to...

**Comment by anoordover** [comment]
I have tested this with SQL Server and I don't have this problem with SQL Server, see https://github.com/anoordover/ExecuteUpdate/tree/feature/AddOwnedPropertyPreReleaseTest2/ExecuteUpdateDemo
