### ISSUE TITLE
EF Core / Autogenerated Many-To-Many / gRPC / Blazor WASM - Error when trying to add a record

### ISSUE THREAD

**Issue by JeepNL** [dotnet/efcore#28670]
### I'm using

 - **Visual Studio version:** 17.4.0 Preview 1.0
 - **.NET SDK / EF Core Version:** 7 preview 7
 - **Project:** (_Hosted_) Blazor WASM Client with a gRPC/Kestrel (Web)Server, and a Shared project for the `.proto` file.
 - **SQLite Database config:** 2 manual gRPC (_[proto file](https://github.com/JeepNL/Blazor_WASM_gRPC_EFCore/blob/master/Blazor_WASM_gRPC_EFCore/Shared/Protos/blog.proto)_) code first configured tables: `Posts` & `Tags`, plus an autogenerated (_by EF Core_) many-to-many table `PostsTags`.

**For reference:** see also this EF Core / gRPC (_solved_) issue: https://github.com/dotnet/efcore/issues/23703 "_Understand why EF Core thinks it needs a setter for `TagsInPostsData` in gRPC model_"

### The problem

Seeding the empty database with Posts & Tags works. See: [Server/Data/SeedData.cs](https://github.com/JeepNL/Blazor_WASM_gRPC_EFCore/blob/master/Blazor_WASM_gRPC_EFCore/Server/Data/SeedData.cs). Getting the Posts with related tags with gRPC is also not a problem.

But when when trying to add a Blog Post with one or more Tags via the client web interface through the [gRPC service](https://github.com/JeepNL/Blazor_WASM_gRPC_EFCore/blob/master/Blazor_WASM_gRPC_EFCore/Server/Services/BlogService.cs) to the database, EF Core tries to add the tags added to the blog post to the `Tags` table instead of the by EF Core autogenerated many-to-many `PostsTags` table. It's the wrong table and so it results in an `UNIQUE constraint failed: Tags.TagId`

### To Reproduce:
 I've created a very simple [GitHub Repo](https://github.com/JeepNL/Blazor_WASM_gRPC_EFCore) which has everything to run locally (_with Kestrel_) on localhost (_with a local https dev certificate_). Download and run to reproduce. Click the 'Add Post' button to add a [preconfigured record](https://github.com/JeepNL/Blazor_WASM_gRPC_EFCore/blob/master/Blazor_WASM_gRPC_EFCore/Client/Pages/Index.razor#L50) to the database and watch the Kestrel server console output.

**Notable source files (_see below also_):**
 - (Client) [Pages/Index.razor](https://github.com/JeepNL/Blazor_WASM_gRPC_EFCore/blob/master/Blazor_WASM_gRPC_EFCore/Client/Pages/Index.razor)
 - (Server) [Data/ApplicationDbContext.cs](https://github.com/JeepNL/Blazor_WASM_gRPC_EFCore/blob/master/Blazor_WASM_gRPC_EFCore/Server/Data/ApplicationDbContext.cs)
 - (Server) [Data/SeedData.cs](https://github.com/JeepNL/Blazor_WASM_gRPC_EFCore/blob/master/Blazor_WASM_gRPC_EFCore/Server/Data/SeedData.cs)
 - (Server) [Services/BlogService.cs](https://github.com/JeepNL/Blazor_WASM_gRPC_EFCore/blob/master/Blazor_WASM_gRPC_EFCore/Server/Services/BlogService.cs)
- (Shared) [Proto/blog.proto](https://github.com/JeepNL/Blazor_WASM_gRPC_EFCore/blob/master/Blazor_WASM_gRPC_EFCore/Shared/Protos/blog.proto)

### Kestrel Server Console Output:
_see `INSERT INTO "Tags" ("TagId")` & `SQLite Error 19: 'UNIQUE constraint failed: Tags.TagId'`_
```
info: 11-8-2022 10:57:09.069 CoreEventId.ContextInitialized[10403] (Microsoft.EntityFrameworkCore.Infrastructure)
      Entity Framework Core 7.0.0-preview.7.22376.2 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.Sqlite:7.0.0-preview.7.22376.2' with options: SensitiveDataLoggingEnabled
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 7.0.0-preview.7.22376.2 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.Sqlite:7.0.0-preview.7.22376.2' with options: SensitiveDataLoggingEnabled
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (2ms) [Parameters=[@p0='Post Content 5' (Size = 14), @p1='637958050290180000', @p2='Post Title 5' (Size = 12)], CommandType='Text', CommandTimeout='30']
      INSERT INTO "Posts" ("Content", "CreatedUtcTicks", "Title")
      VALUES (@p0, @p1, @p2)
      RETURNING "PostId";
info: 11-8-2022 10:57:09.184 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (2ms) [Parameters=[@p0='Post Content 5' (Size = 14), @p1='637958050290180000', @p2='Post Title 5' (Size = 12)], CommandType='Text', CommandTimeout='30']
      INSERT INTO "Posts" ("Content", "CreatedUtcTicks", "Title")
      VALUES (@p0, @p1, @p2)
      RETURNING "PostId";
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (1ms) [Parameters=[@p0='Tag One' (Nullable = false) (Size = 7)], CommandType='Text', CommandTimeout='30']
      INSERT INTO "Tags" ("TagId")
      VALUES (@p0);
fail: 11-8-2022 10:57:09.199 RelationalEventId.CommandError[20102] (Microsoft.EntityFrameworkCore.Database.Command)
      Failed executing DbCommand (1ms) [Parameters=[@p0='Tag One' (Nullable = false) (Size = 7)], CommandType='Text', CommandTimeout='30']
      INSERT INTO "Tags" ("TagId")
      VALUES (@p0);
fail: Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type 'Blazor_WASM_gRPC_EFCore.Server.Data.ApplicationDbContext'.
      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
       ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: Tags.TagId'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
       ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: Tags.TagId'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

**(Client) [Pages/Index.razor](https://github.com/JeepNL/Blazor_WASM_gRPC_EFCore/blob/master/Blazor_WASM_gRPC_EFCore/Client/Pages/Index.razor)**
```
@page "/"
@using Grpc.Net.Client
@using Google.Protobuf.WellKnownTypes;
@using Blazor_WASM_gRPC_EFCore.Shared.Protos
@inject GrpcChannel Channel

<PageTitle>Index</PageTitle>

<h1>Blog Posts</h1>

@if (posts == null)
{
    <p>Loading ...</p>
}
else
{
    foreach (var post in posts)
    {
        <div>(@post.PostId) - <b>@post.Title</b></div>
        <div>@post.Content</div>
        <div class="mb-3">
            <small>-- <b>Tags: </b></small>
            @foreach (Tag tag in post.TagsInPostRepeated)
            {
                <small>[@tag.TagId] </small>
            }
        </div>

    }

    <div>
        <i>
            Add a new preconfigured blog post (5), see source.
            <br />And see server console output for error ...
        </i>
    </div>
    <button class="my-2" @onclick="SubmitNewPost">Add Post</button>
}

@code {
    private BlogProto.BlogProtoClient? client;
    private List<Post>? posts;

    protected override async Task OnInitializedAsync()
    {
        client = new BlogProto.BlogProtoClient(Channel);
        posts = (await client.GetPostsAsync(new Empty())).PostsRepeated.ToList();
    }

    private async Task SubmitNewPost()
    {
        // add post
        Post addPost = new()
            {
                Title = "Post Title 5",
                Content = "Post Content 5",
                CreatedUtcTicks = DateTime.UtcNow.Ticks
            };

        // add 3 existing tags to post
        Tag tag1 = new Tag { TagId = "Tag One" };
        Tag tag2 = new Tag { TagId = "Tag Two" };
        Tag tag3 = new Tag { TagId = "Tag Three" };
        addPost.TagsInPostRepeated.AddRange(new[] { tag1, tag2, tag3 });


        await client!.AddPostAsync(addPost);
    }
}

```

**(Server) [Data/ApplicationDbContext.cs](https://github.com/JeepNL/Blazor_WASM_gRPC_EFCore/blob/master/Blazor_WASM_gRPC_EFCore/Server/Data/ApplicationDbContext.cs)**
```
using Blazor_WASM_gRPC_EFCore.Shared.Protos;
using Microsoft.EntityFrameworkCore;

namespace Blazor_WASM_gRPC_EFCore.Server.Data
{
	public class ApplicationDbContext : DbContext
	{
		public ApplicationDbContext(DbContextOptions options) : base(options)
		{
		}

		public DbSet<Post>? Posts { get; set; }
		public DbSet<Tag>? Tags { get; set; }

		public override int SaveChanges()
		{
			return base.SaveChanges();
		}

		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) => optionsBuilder
				.LogTo(Console.WriteLine, LogLevel.Information) // LogLevel.Warning for production
				.EnableSensitiveDataLogging(); // for debugging only

		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			base.OnModelCreating(modelBuilder);

			modelBuilder
				.Entity<Post>()
				.HasMany(e => e.TagsInPostRepeated)
				.WithMany(e => e.PostsInTagRepeated)
				.UsingEntity<Dictionary<string, object>>(
					// (Join) Table Name. Renames EF Core autogenerated 'PostTag' table to 'PostsTags' table
					"PostsTags",
					p => p
						.HasOne<Tag>()
						.WithMany()
						.HasForeignKey("TagId")
					, t => t // watch the comma :)
						.HasOne<Post>()
						.WithMany()
						.HasForeignKey("PostId")
				);
		}
	}
}

```

**(Server) [Data/SeedData.cs](https://github.com/JeepNL/Blazor_WASM_gRPC_EFCore/blob/master/Blazor_WASM_gRPC_EFCore/Server/Data/SeedData.cs)**
```
using Blazor_WASM_gRPC_EFCore.Shared.Protos;
using Microsoft.EntityFrameworkCore;

namespace Blazor_WASM_gRPC_EFCore.Server.Data
{
	public static class SeedData
	{
		public static void Initialize(IServiceProvider serviceProvider)
		{
			using (var ctx = new ApplicationDbContext(
				serviceProvider.GetRequiredService<DbContextOptions<ApplicationDbContext>>()))
			{
				// Look for any posts.
				if (ctx.Posts is not null)
				{
					if (ctx.Posts.Any())
						return;   // DB has been seeded
				}
				else
					throw new Exception("ctx.Posts is null");

				long utcNowTicks = DateTime.UtcNow.Ticks;

				// Post Records
				Post post1 = new Post { PostId = 1, Title = "Post Title 1", Content = "Post Content I", CreatedUtcTicks = utcNowTicks };
				Post post2 = new Post { PostId = 2, Title = "Post Title 2", Content = "Post Content II", CreatedUtcTicks = utcNowTicks };
				Post post3 = new Post { PostId = 3, Title = "Post Title 3", Content = "Post Content III", CreatedUtcTicks = utcNowTicks };
				Post post4 = new Post { PostId = 4, Title = "Post Title 4", Content = "Post Content IV", CreatedUtcTicks = utcNowTicks };

				// Tag Records
				Tag tag1 = new Tag { TagId = "Tag One" };
				Tag tag2 = new Tag { TagId = "Tag Two" };
				Tag tag3 = new Tag { TagId = "Tag Three" };
				Tag tag4 = new Tag { TagId = "Tag Four" };
				Tag tag5 = new Tag { TagId = "Tag Five" };
				Tag tag6 = new Tag { TagId = "Tag Six" };

				// Add Multiple Tags to Posts, many to many
				post1.TagsInPostRepeated.AddRange(new[] { tag1, tag2, tag3, tag4, tag5, tag6 });
				post2.TagsInPostRepeated.AddRange(new[] { tag3, tag4, tag6 });
				post3.TagsInPostRepeated.AddRange(new[] { tag4 });
				// post 4 without tags

				// Add records to DB
				ctx.AddRange(post1, post2, post3, post4);
				ctx.AddRange(tag1, tag2, tag3, tag4, tag5, tag6);

				ctx.SaveChanges();
			}
		}
	}
}
```

**(Server) [Services/BlogService.cs](https://github.com/JeepNL/Blazor_WASM_gRPC_EFCore/blob/master/Blazor_WASM_gRPC_EFCore/Server/Services/BlogService.cs)**
```
using Blazor_WASM_gRPC_EFCore.Server.Data;
using Blazor_WASM_gRPC_EFCore.Shared.Protos;
using Google.Protobuf.WellKnownTypes;
using Grpc.Core;
using Microsoft.EntityFrameworkCore;

namespace Blazor_WASM_gRPC_EFCore.Server.Services
{
	public class BlogService : BlogProto.BlogProtoBase
	{
		private readonly ApplicationDbContext dbContext;
		public BlogService(ApplicationDbContext dataContext)
		{
			dbContext = dataContext;
		}

		public override async Task<Posts> GetPosts(Empty request, ServerCallContext context)
		{
			List<Post> postsQuery = await dbContext.Posts!
				.Include(tipd => tipd.TagsInPostRepeated)
				.OrderByDescending(dc => dc.CreatedUtcTicks)
				.AsNoTracking()
				.ToListAsync();

			// The Protobuf serializer doesn't support reference loops
			// see: https://github.com/grpc/grpc-dotnet/issues/1177#issuecomment-763910215
			//var posts = new Posts();
			//posts.PostsData.AddRange(postsQuery); // so this doesn't work

			Posts posts = new();
			foreach (var p in postsQuery)
			{
				Post post = new()
				{
					PostId = p.PostId,
					Title = p.Title,
					Content = p.Content,
					CreatedUtcTicks = p.CreatedUtcTicks,
				};

				// Just add all the tags to each post, this isn't a reference loop (many to many posts/tags).
				List<Tag> tags = p.TagsInPostRepeated.Select(t => new Tag { TagId = t.TagId }).ToList();
				post.TagsInPostRepeated.AddRange(tags);

				// Add post (now with tags) to posts
				posts.PostsRepeated.Add(post);
			}
			return posts;
		}

		public override async Task<AddPostResult> AddPost(Post postRequest, ServerCallContext context)
		{
			AddPostResult addPostResult = new();

			// postRequest console output
			Console.WriteLine("\n\n***** Post");
			Console.WriteLine($"***** postRequest.Title: {postRequest.Title}");
			Console.WriteLine($"***** postRequest.Content: {postRequest.Content}");
			Console.WriteLine("\n***** Tags in Post");
			foreach (Tag tag in postRequest.TagsInPostRepeated)
			{
				Console.WriteLine($"***** tag.TagId: {tag.TagId}");
			}
			Console.WriteLine("\n");

			// no error checking, sample.
			dbContext.Posts!.Add(postRequest);
			await dbContext.SaveChangesAsync();

			addPostResult.PostId = postRequest.PostId; // record id
			return addPostResult;
		}
	}
}

```

**(Shared) [Proto/blog.proto](https://github.com/JeepNL/Blazor_WASM_gRPC_EFCore/blob/master/Blazor_WASM_gRPC_EFCore/Shared/Protos/blog.proto)**
```
syntax = "proto3";
option csharp_namespace = "Blazor_WASM_gRPC_EFCore.Shared.Protos";
import "google/protobuf/empty.proto";
package blogproto;

service BlogProto{
	rpc GetPosts(google.protobuf.Empty) returns (Posts);
	rpc AddPost(Post) returns (AddPostResult);
}

message Post {
	int32 post_id = 1;
	string title = 2;
	string content = 3;
	int64 created_utc_ticks = 4;
	repeated Tag tags_in_post_repeated = 5; // Post with many Tags
}
message Posts {
	repeated Post posts_repeated = 1;
}
message AddPostResult {
	int32 post_id = 1;
}

message Tag {
	string tag_id = 1; // Tag itself: string
	repeated Post posts_in_tag_repeated = 2; // Tag with many Posts
}
message Tags {
	repeated Tag tags_repeated = 1;
}
```

**Comment by ajcvickers** [comment]
@JeepNL This line:

```C#
dbContext.Posts!.Add(postRequest);
```

Starts tracking all the entities as `Added`; that is, as new entities that have not yet been saved to the database. If instead the `Post` and `Tag` entities already exist, and you're trying to associate them, then the entities will need to be in the `Unchanged` state before making the association. There are various ways to do this--[Explicitly Tracking Entities](https://docs.microsoft.com/en-us/ef/core/change-tracking/explicit-tracking) in the docs goes over this and shows the general approaches that can be used.

**Comment by JeepNL** [comment]
@ajcvickers Okay, thank you! 

So, this is **not a bug** but a '_Jaap Error_'.  (Which is often the case ...)

I'll study that Docs page and let you know when I got it working, and I'll update that GitHub repo then as well.

**Comment by JeepNL** [comment]
Oh help!

 I just changed `dbContext.Posts!.Add(postRequest);`
To `dbContext.Posts!.Attach(postRequest);`

And now it works 😳

And I learned how to use `dbContext.ChangeTracker.DebugView.LongView`,

Updated my repo with the code below.

Closing this issue, thank you for pointing me into the right direction.

----

(Server) [Services/BlogService.cs](https://github.com/JeepNL/Blazor_WASM_gRPC_EFCore/blob/master/Blazor_WASM_gRPC_EFCore/Server/Services/BlogService.cs)
```
public override async Task<AddPostResult> AddPost(Post postRequest, ServerCallContext context)
{
	dbContext.ChangeTracker.DetectChanges();

	dbContext.Posts!.Attach(postRequest);

	Console.WriteLine("\n\n***** dbContext.ChangeTracker.DebugView.LongView");
	Console.WriteLine(dbContext.ChangeTracker.DebugView.LongView);
	Console.WriteLine("\n");

	await dbContext.SaveChangesAsync();

	return new() { PostId = postRequest.PostId };
}

```

**Server Console Output:**
```
***** dbContext.ChangeTracker.DebugView.LongView
Post {PostId: -2147482647} Added
  PostId: -2147482647 PK Temporary
  Content: 'Post Content 5'
  CreatedUtcTicks: 637958432207880000
  Title: 'Post Title 5'
  TagsInPostRepeated: [{TagId: Tag One}, {TagId: Tag Two}, {TagId: Tag Three}]
Tag {TagId: Tag One} Unchanged
  TagId: 'Tag One' PK
  PostsInTagRepeated: [{PostId: -2147482647}]
Tag {TagId: Tag Three} Unchanged
  TagId: 'Tag Three' PK
  PostsInTagRepeated: [{PostId: -2147482647}]
Tag {TagId: Tag Two} Unchanged
  TagId: 'Tag Two' PK
  PostsInTagRepeated: [{PostId: -2147482647}]
PostsTags (Dictionary<string, object>) {PostId: -2147482647, TagId: Tag One} Added
  PostId: -2147482647 PK FK Temporary
  TagId: 'Tag One' PK FK
PostsTags (Dictionary<string, object>) {PostId: -2147482647, TagId: Tag Three} Added
  PostId: -2147482647 PK FK Temporary
  TagId: 'Tag Three' PK FK
PostsTags (Dictionary<string, object>) {PostId: -2147482647, TagId: Tag Two} Added
  PostId: -2147482647 PK FK Temporary
  TagId: 'Tag Two' PK FK
```
