### ISSUE TITLE
Microsoft.EntityFrameworkCore.Sqlite 7 crash on iOS

### ISSUE THREAD

**Issue by RobertoGFilho** [dotnet/efcore#28773]
EfCore 7 crash on iOS MAUI app. Please you can reproduce this erro on this demo : https://github.com/RobertoGFilho/EFCore

- Windows ok
- Android ok
- iOS crash

![image](https://user-images.githubusercontent.com/68563526/185379750-4f477d5d-0862-4f05-b0b2-3c32595acb3d.png)

Visual studio 17.3.1
Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.0-preview.7.22376.2"

**Comment by eerhardt** [comment]
I don't believe this is a NullabilityInfoContextSupport issue. When I ran your app I see the following exception being thrown:

![image](https://user-images.githubusercontent.com/8291187/185513536-3e432500-f87d-458f-b0f2-63c309611ef8.png)

**Comment by RobertoGFilho** [comment]
@eerhardt thanks for you attention!

 I'm using Visual Studio 17.3.1 for Windows 11 and real device iPhone 7plus with hotrestart. Only iOS this error happen! I have already worked with EFCore 3.1 and Xamarin for three plataforms  and works well.

On Xamarin configuration iOS is:

        public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {
            SQLitePCL.Batteries_V2.Init();
            global::Xamarin.Forms.Forms.Init();

            var libPath = Path.Combine(
                System.Environment.GetFolderPath(System.Environment.SpecialFolder.MyDocuments),
                "..", "Library", "data");

            if (!Directory.Exists(libPath))
            {
                Directory.CreateDirectory(libPath);
            }

            var dbPath = Path.Combine(libPath, "core.sqlite");
            LoadApplication(new App(dbPath));
            return base.FinishedLaunching(app, options);
        }

let me show what is happen on MAUI:

https://user-images.githubusercontent.com/68563526/185615877-596c4c60-209c-4172-bb74-cae70752732b.mp4

I've already add : NullabilityInfoContextSupport = true on project file but it doesn't work

![image](https://user-images.githubusercontent.com/68563526/185616004-2e34d261-d84d-4ccc-bd2d-1f89271ce341.png)

do you have any idea?

**Comment by eerhardt** [comment]
Can you list what version of `dotnet` and the MAUI workload you are using?

`dotnet --info`
`dotnet workload list`

I'm using a mac with `6.0.400` of the dotnet SDK and `6.0.486/6.0.400` of the maui workload.

When running the app on an iPad simulator in Debug mode, the app works fine. When running with `-c Release`, I get the above exception.

**Comment by RobertoGFilho** [comment]
@eerhardt 

I'm using 6.0.8

![image](https://user-images.githubusercontent.com/68563526/185703037-00f84831-9af5-470a-b841-6919479903f6.png)

I'm using a real device "iPhone 7" plus iSO version 15 .. in debug mode .. and hotrestar enable

**Comment by eerhardt** [comment]
What is the output of `dotnet workload list`?

**Comment by RobertoGFilho** [comment]
PS C:\Users\rober\source\repos\EFCore\EFCore> dotnet workload list

Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.400

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------

Installed Workload Ids      Manifest Version                              Installation Source
---------------------------------------------------------------------------------------------
maui-android                6.0.486/6.0.400                               VS 17.3.32811.315
android                     32.0.448/6.0.400                              VS 17.3.32811.315
maui-windows                6.0.486/6.0.400                               VS 17.3.32811.315
maui-maccatalyst            6.0.486/6.0.400                               VS 17.3.32811.315
maccatalyst                 15.4.446-ci.-release-6-0-4xx.446/6.0.400      VS 17.3.32811.315
maui-ios                    6.0.486/6.0.400                               VS 17.3.32811.315
ios                         15.4.446-ci.-release-6-0-4xx.446/6.0.400      VS 17.3.32811.315

Use `dotnet workload search` to find additional workloads to install.

**Comment by eerhardt** [comment]
Unfortunately, I can't repro this behavior.

If I launch the app on a physical phone using VS for Mac, it works correctly. I don't see an exception being thrown.

I'm not able to deploy any Maui app to a physical phone from VS on Windows for some reason, and I spent too much time trying to get it to work. I've given up.

My suggestions for debugging this would be to get a [binlog](https://msbuildlog.com/) of the build and inspect the `ILLink` task to see what parameters are getting passed to the linker. I don't know why these would be different for iOS vs. Android. Maybe something on your machine is telling it to use different settings.

If a binlog doesn't help, inspecting the .dlls in something like ILSpy may help give a clue. Look for the code using this switch:

https://github.com/dotnet/runtime/blob/e71a9583b4d6c9bd97edd87cda7f98f232f63530/src/libraries/System.Private.CoreLib/src/System/Reflection/NullabilityInfoContext.cs#L20-L21

**Comment by eerhardt** [comment]
Another thing to look for is in the "Build" output (on a fresh build/install), look for the string `System.Reflection.NullabilityInfoContext.IsSupported`. This should be set to `true`. If you see it set to false, that's the issue.

Here's a snippet of my build output:

```
1>/Users/eerhardt/Library/Caches/Xamarin/XMA/SDKs/dotnet/dotnet "/Users/eerhardt/Library/Caches/Xamarin/XMA/SDKs/dotnet/sdk/6.0.400/Sdks/Microsoft.NET.ILLink.Tasks/build/../tools/net6.0/illink.dll" -a "obj/Debug/net6.0-ios/ios-arm64/EFCore.dll"
1>-a "obj/Debug/net6.0-ios/ios-arm64/EFCore.dll"
1>-reference "C:/Users/eerhardt/.nuget/packages/microsoft.data.sqlite.core/7.0.0-preview.7.22376.2/lib/net6.0/Microsoft.Data.Sqlite.dll"
1>-reference "C:/Users/eerhardt/.nuget/packages/microsoft.entityframeworkcore/7.0.0-preview.7.22376.2/lib/net6.0/Microsoft.EntityFrameworkCore.dll"
...
1>--warn "5"
1>--warnaserror- --warnaserror ";NU1605"
1>--feature Microsoft.Extensions.DependencyInjection.VerifyOpenGenericServiceTrimmability true
1>--feature System.AggressiveAttributeTrimming true
1>--feature System.ComponentModel.TypeConverter.EnableUnsafeBinaryFormatterInDesigntimeLicenseContextSerialization false
1>--feature System.Diagnostics.Debugger.IsSupported true
1>--feature System.Diagnostics.Tracing.EventSource.IsSupported false
1>--feature System.Globalization.Invariant false
1>--feature System.Net.Http.EnableActivityPropagation false
1>--feature System.Net.Http.UseNativeHttpHandler true
1>--feature System.Reflection.NullabilityInfoContext.IsSupported true
```

**Comment by RobertoGFilho** [comment]
hey @eerhardt ! something very crazy is happen! When I use iOS emulator error disappear, but if i try real device "iPhone 7 Plus" happens error . see:

https://user-images.githubusercontent.com/68563526/186660898-c8a54d15-2687-4eab-a449-b6dc2ad142e4.mp4

**Comment by RobertoGFilho** [comment]
I have tryed to change : System.Reflection.NullabilityInfoContext.IsSupported = true or false.. but error happens

**Comment by eerhardt** [comment]
>  but if i try real device "iPhone 7 Plus" happens error .

I've run the EFCore app both from VS for Mac preview on my mac, and from VS for Windows paired with my mac, to a physical iPhone 6S and can't repro this behavior.

Can you try running the app on a different development machine? My guess is that there is something specific about your dev machine that is causing this.

**Comment by eerhardt** [comment]
One idea to try to figure this out:

1. Delete the app from the physical device. and "Clean" the project.  Delete the `bin` and `obj` folders to ensure everything is clean.
2. Follow the steps in https://docs.microsoft.com/en-us/visualstudio/ide/msbuild-logs?view=vs-2022#create-a-binary-msbuild-log-by-using-the-project-system-tools-extension to get a binlog of the build that happens when you deploy to the physical phone.
3. Attach the binlogs here. 

The only thing I can guess is that somehow the `System.Reflection.NullabilityInfoContext.IsSupported` switch is getting set to `false` by something, but I'm not sure what. The binlog would tell us who/what is setting it.

**Comment by RobertoGFilho** [comment]
hi folks! 
the trouble is string properties on Model! see:

WORKS:

public class Person : ObservableObject
{
	[Key]
	public Guid Id { get; set; }
	public int Age { get; set; }	
	//public string Name { get; set; }
}

DOESN'T WORK

public class Person : ObservableObject
{
	[Key]
	public Guid Id { get; set; }
	public int Age { get; set; }	
	public string Name { get; set; }
}

**Comment by ErikEJ** [comment]
What is ObservableObject?

**Comment by RobertoGFilho** [comment]
hi @ErikEJ , 

ObservableObject is from MVVMHelpers, you can remove this, but the same error will show up! This error happen only string properties on Model. Only iOS plataform. 

Please you can reproduce this erro on this demo : https://github.com/RobertoGFilho/EFCore

**Comment by RobertoGFilho** [comment]
[0:] NullabilityInfoContext is not supported in the current application because 'System.Reflection.NullabilityInfoContext.IsSupported' is set to false. Set the MSBuild Property 'NullabilityInfoContextSupport' to true in order to enable it.
[0:] An error occurred: 'NullabilityInfoContext is not supported in the current application because 'System.Reflection.NullabilityInfoContext.IsSupported' is set to false. Set the MSBuild Property 'NullabilityInfoContextSupport' to true in order to enable it.'. Callstack: '   at System.Reflection.NullabilityInfoContext.EnsureIsSupported()
   at System.Reflection.NullabilityInfoContext.Create(PropertyInfo propertyInfo)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.NonNullableConventionBase.IsNonNullableReferenceType(IConventionModelBuilder modelBuilder, MemberInfo memberInfo)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.NonNullableReferencePropertyConvention.Process(IConventionPropertyBuilder propertyBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.NonNullableReferencePropertyConvention.ProcessPropertyAdded(IConventionPropertyBuilder propertyBuilder, IConventionContext`1 context)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnPropertyAdded(IConventionPropertyBuilder propertyBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnPropertyAddedNode.Run(ConventionDispatcher dispatcher)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.DelayedConventionScope.Run(ConventionDispatcher dispatcher)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Run()
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Dispose()
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelInitialized(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelInitialized(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model..ctor(ConventionSet conventions, ModelDependencies modelDependencies, ModelConfiguration modelConfiguration)
   at Microsoft.EntityFrameworkCore.ModelBuilder..ctor(ConventionSet conventions, ModelDependencies modelDependencies, ModelConfiguration modelConfiguration)
   at Microsoft.EntityFrameworkCore.ModelConfigurationBuilder.CreateModelBuilder(ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeServiceProviderEngine.<>c__DisplayClass4_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[IDbContextDependencies](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[IDatabaseFacadeDependencies](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[IDatabaseFacadeDependencies](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_Dependencies()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
   at EFCore.MainPage.OnCounterClicked(Object sender, EventArgs e) in C:\Users\rober\source\repos\EFCore\EFCore\MainPage.xaml.cs:line 31
   at Microsoft.Maui.Controls.Button.Microsoft.Maui.Controls.Internals.IButtonElement.PropagateUpClicked()
   at Microsoft.Maui.Controls.ButtonElement.ElementClicked(VisualElement visualElement, IButtonElement ButtonElementManager)
   at Microsoft.Maui.Controls.Button.SendClicked()
   at Microsoft.Maui.Controls.Button.Microsoft.Maui.IButton.Clicked()
   at Microsoft.Maui.Handlers.ButtonHandler.OnButtonTouchUpInside(Object sender, EventArgs e)
   at UIKit.UIControlEventProxy.Activated()
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at EFCore.Program.Main(String[] args) in C:\Users\rober\source\repos\EFCore\EFCore\Platforms\iOS\Program.cs:line 13
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)'
The app has been terminated.

**Comment by RobertoGFilho** [comment]
Hi @eerhardt !

I have done in different machine, the same error shows up!

**Comment by eerhardt** [comment]
Are you able to get a binlog? See https://github.com/dotnet/efcore/issues/28773#issuecomment-1227359062

**Comment by RobertoGFilho** [comment]
Hi @eerhardt binlog files are bellow:

[binlog files.zip](https://github.com/dotnet/efcore/files/9639144/binlog.files.zip)

**Comment by eerhardt** [comment]
Hmm, unfortunately those logs don't contain much information. One thing I was able to confirm was that `NullabilityInfoContextSupport` was getting set to `true`. But I wasn't able to see any compiler or linker steps happen in the logs.

Did you delete the `bin` and `obj` folders to ensure everything is clean before capturing the logs?

**Comment by RobertoGFilho** [comment]
Hi @eerhardt 

this binlog wore created after: delete the bin and obj folders to ensure everything is clean.
[binlog.zip](https://github.com/dotnet/efcore/files/9649444/binlog.zip)

the problem is when we have a string property on Model. if i remove this property everythings works see:

![image](https://user-images.githubusercontent.com/68563526/192373462-ac0af076-7594-433b-8c9c-4a5a0c8764f8.png)

![image](https://user-images.githubusercontent.com/68563526/192373535-79ef4001-da33-487e-8bbc-a5ab3b068605.png)

**Comment by eerhardt** [comment]
I don't see why `NullabilityInfoContextSupport=true` is not getting flown to the final app. Maybe there is something in the iOS tooling that doing this? @rolfbjarne do you have any ideas? In the attached binlogs, NullabilityInfoContextSupport is set to `true`. However, at runtime, the exception @RobertoGFilho is getting leads me to believe it is not being set to `true`:

```
[0:] An error occurred: 'NullabilityInfoContext is not supported in the current application because 'System.Reflection.NullabilityInfoContext.IsSupported' is set to false. Set the MSBuild Property 'NullabilityInfoContextSupport' to true in order to enable it.'. Callstack: '   at System.Reflection.NullabilityInfoContext.EnsureIsSupported()
   at System.Reflection.NullabilityInfoContext.Create(PropertyInfo propertyInfo)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.NonNullableConventionBase.IsNonNullableReferenceType(IConventionModelBuilder modelBuilder, MemberInfo memberInfo)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.NonNullableReferencePropertyConvention.Process(IConventionPropertyBuilder propertyBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.NonNullableReferencePropertyConvention.ProcessPropertyAdded(IConventionPropertyBuilder propertyBuilder, IConventionContext`1 context)
```

**Comment by rolfbjarne** [comment]
@RobertoGFilho just in order to narrow things down: do you get the same behavior if you use Visual Studio for Mac (on the Mac)?

**Comment by RobertoGFilho** [comment]
hi @rolfbjarne !

I just work on Visual Studio for Windows! 

![image](https://user-images.githubusercontent.com/68563526/192518107-0fa189b3-f021-4562-b8cb-61c3f74f9bf6.png)

i have shared this demo : https://github.com/RobertoGFilho/EFCore

**Comment by rolfbjarne** [comment]
The test project from the initial description works fine when I run it on a Mac.

The two binlogs (https://github.com/dotnet/efcore/issues/28773#issuecomment-1257008305, https://github.com/dotnet/efcore/issues/28773#issuecomment-1258592532) come from a build that wasn't connected to the Mac, and thus only a very simple build was done.

@RobertoGFilho, please connect to a mac, build again and get the binlog, or try directly on the Mac (using Visual Studio for Mac) to see if that works for you.

**Comment by RobertoGFilho** [comment]
hi @rolfbjarne @eerhardt   binlogs connected to a mac: [binlog.zip](https://github.com/dotnet/efcore/files/9691452/binlog.zip)

**Comment by rolfbjarne** [comment]
@RobertoGFilho those builds are still not connected to a mac.

See: https://learn.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/connecting-to-mac/

**Comment by RobertoGFilho** [comment]
@rolfbjarne, @ajcvickers @ErikEJ @jsuarezruiz  @eerhardt @Eilon @mattleibow   i connected to a MAC, but my envioment doesn't use MAC to build a app. See:

**My Envioroment:**

- Windows 11;
- Visual Studio 2022 for Windows 11;
- Devices : Iphone 7 Plus and Iphone 6 plus;

**Thecnologies:**

- Hot Restart;
- Hot Reload;

I understand that you test on MAC is ok, But the problem here is working on Windows without a MAC. I've been working this way with Xamarin Forms and EF Core 3.1 without problem. But when i started working MAUI and EF 7.xx i not able to work on iOS, because string property on model trigger this error.

public class Person
{
    [Key]
    public Guid Id { get; set; }
    public int Age { get; set; }
    **_public string Name { get; set; }_**
}

On Android and Windows works perfectly.

**Conclusion**
We need to fix this on Windows envioroment, becaouse will impact many developers that want to work with MAUI and EF 7.xxx.

**Comment by rolfbjarne** [comment]
This is unlikely to be a problem in EFCore if it only occurs in certain build environments, so I'm moving this issue.

**Comment by rolfbjarne** [comment]
This issue was moved to xamarin/xamarin-macios#16228

**Comment by taublast** [comment]
> I don't believe this is a NullabilityInfoContextSupport issue. When I ran your app I see the following exception being thrown:
> 
> ![image](https://user-images.githubusercontent.com/8291187/185513536-3e432500-f87d-458f-b0f2-63c309611ef8.png)

this is can be worked around this way: https://stackoverflow.com/a/74786481/7149454
