### ISSUE TITLE
Migration Problem With  ColumnType Set In Owned Entity 

### ISSUE THREAD

**Issue by guncer** [dotnet/efcore#28868]
## Owned Entity  ColumnType Set Migration Error
We have a owned entity in the project,when we trying to set  property column type attribute   in modelcreating , initial migration  gives an error. If we don't set it, we don't get an error.

### Migration text:
 add-migration initial -OutputDir "Migrations" -Context OwnedEntityContext

### Error message:
```
The entity type 'SprintOverview' has been marked as owned and must be referenced from another entity type via a navigation. Add a navigation to an entity type that points at 'SprintOverview' or don't configure it as owned.
```

 If below line is removed, everything is ok , intial migration success. if this line is stayed and  string property removed   in owned entity ("Goal"), migration is success again. I could not finf the problem , Could you please examine this situation?
```C#
     SetColumnType(modelBuilder,typeof(string), "varchar");
```

### Code
Attached runnable project :
[OwnedEntities.zip](https://github.com/dotnet/efcore/files/9416840/OwnedEntities.zip)

```C#

    [Owned()]
    public class SprintOverview
    {
      
        [Required]
        public  long ScrumMasterId { get; set; }

        [Required]
        [MaxLength(100)]
        public string Goal { get; set; }
        public decimal PlannedStoryPoint { get; set; }
     
        public decimal SuccessPoint { get; set; }

     
    }
  [Table("Sprints")]
    public class Sprint 
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public long JiraId { get; set; }
        [Required]
        public long BoardId { get; set; }
        
        [Required]
        [MaxLength(255)]
        public  string Name { get; set; }
        [MaxLength(4000)]
        public  string ConfluenceUrl { get; set; }
        public  DateTime StartDate { get; set; }
        public  DateTime? EndDate { get; set; }
             
        public  SprintOverview SprintOverview { get; set; }

    }
 [Table("JiraUsers")]
    public class JiraUser
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Code { get; set; }
        [Required]

        public string Name { get; set; }
        [Required]

        public string DisplayName { get; set; }
  
    }

  [Table("SprintProductOwnerUsers")]
    public class SprintProductOwnerUser 
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public long UserId { get; set; }

        [Required]
        public long SprintId { get; set; }
           
        public virtual Sprint Sprint { get; set; }
       
        public virtual JiraUser User { get; set; }

    }

public class OwnedEntityContext : DbContext
{
    public DbSet<JiraUser> Users { get; set; }
    public DbSet<SprintProductOwnerUser> SprintProductOwnerUsers { get; set; }
    public DbSet<Sprint> Sprints { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=EFOwnedEntity;Trusted_Connection=True");
   
 
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        //if this line is removed, everything is ok , intiial migration success. if this line is stayed and  string property removed   in owned entity, migration is success again. 
        SetColumnType(modelBuilder,typeof(string), "varchar");

    }
 public  void SetColumnType( ModelBuilder modelBuilder, Type type, string columnType)
    {
        foreach (var entity in modelBuilder.Model.GetEntityTypes())
        {
            var properties = entity.GetProperties().Where(p => p.PropertyInfo?.PropertyType == type);

            foreach (var property in properties)
            {
                
                modelBuilder.Entity(entity.Name).Property(property.Name).HasColumnType(columnType);
           
            }
        }
    }
}
```

### Include verbose output

```
add-migration initial -OutputDir "Migrations" -Context OwnedEntityContext -verbose
Using project 'Modeling\OwnedEntities'.
Using startup project 'Modeling\OwnedEntities'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile D:\Collection\EntityFramework.Docs-main\samples\core\Modeling\OwnedEntities\bin\Debug\net6.0\EFModeling.OwnedEntities.deps.json --additionalprobingpath C:\Users\secakir\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig D:\Collection\EntityFramework.Docs-main\samples\core\Modeling\OwnedEntities\bin\Debug\net6.0\EFModeling.OwnedEntities.runtimeconfig.json C:\Users\secakir\.nuget\packages\microsoft.entityframeworkcore.tools\6.0.0\tools\netcoreapp2.0\any\ef.dll migrations add initial --json --output-dir Migrations --context OwnedEntityContext --verbose --no-color --prefix-output --assembly D:\Collection\EntityFramework.Docs-main\samples\core\Modeling\OwnedEntities\bin\Debug\net6.0\EFModeling.OwnedEntities.dll --project D:\Collection\EntityFramework.Docs-main\samples\core\Modeling\OwnedEntities\OwnedEntities.csproj --startup-assembly D:\Collection\EntityFramework.Docs-main\samples\core\Modeling\OwnedEntities\bin\Debug\net6.0\EFModeling.OwnedEntities.dll --startup-project D:\Collection\EntityFramework.Docs-main\samples\core\Modeling\OwnedEntities\OwnedEntities.csproj --project-dir D:\Collection\EntityFramework.Docs-main\samples\core\Modeling\OwnedEntities\ --language C# --configuration Debug --working-dir D:\Collection\EntityFramework.Docs-main\samples\core --root-namespace EFModeling.OwnedEntities
Using assembly 'EFModeling.OwnedEntities'.
Using startup assembly 'EFModeling.OwnedEntities'.
Using application base 'D:\Collection\EntityFramework.Docs-main\samples\core\Modeling\OwnedEntities\bin\Debug\net6.0'.
Using working directory 'D:\Collection\EntityFramework.Docs-main\samples\core\Modeling\OwnedEntities'.
Using root namespace 'EFModeling.OwnedEntities'.
Using project directory 'D:\Collection\EntityFramework.Docs-main\samples\core\Modeling\OwnedEntities\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'EFModeling.OwnedEntities'...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'OwnedEntityContext'.
Using context 'OwnedEntityContext'.
System.InvalidOperationException: The entity type 'SprintOverview' has been marked as owned and must be referenced from another entity type via a navigation. Add a navigation to an entity type that points at 'SprintOverview' or don't configure it as owned.
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateOwnership(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal.SqlServerModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The entity type 'SprintOverview' has been marked as owned and must be referenced from another entity type via a navigation. Add a navigation to an entity type that points at 'SprintOverview' or don't configure it as owned.
```

### Include provider and version information

EF Core version: EF 6.0 also EF 5.0 (I tryed in both of them)
Database provider: ( Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (NET 6.0 And NET 5.0 )
Operating system:
IDE: (Visual Studio 2022 17.1.1)

**Comment by smitpatel** [comment]
You cannot use `modelBuilder.Entity` API on owned entity. By doing so, you made the entity type non-owned but you have attribute which says otherwise so validation fails. If you are trying to set certain columnType based on clr type consider using https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/whatsnew#pre-convention-model-configuration
