### ISSUE TITLE
## Owned Entity  Collection Property Migration Error

### ISSUE THREAD

**Issue by guncer** [dotnet/efcore#28869]
## Owned Entity  Collection Property Migration Error
We have a owned entity (same as fluent nhibernate components ) in the project. This owned  class  has collection property ("SprintProductOwnerUsers"). this  property class is mapped with parent entity("Sprint") .Our purpose of using the owned class , parent class  look more readable. because otherwise Parent class("Sprints") looks crowded. It has a lots of property but we tried create initial migration , it  gives an error. Could you please help us? we can not determine the problem.

### Migration text:
 add-migration initial -OutputDir "Migrations" -Context OwnedEntityContext

### Error message:
```
Unable to determine the relationship represented by navigation 'SprintOverview.SprintProductOwnerUsers' of type 'ISet<SprintProductOwnerUser>'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
```

### Include your code
Attached runnable project :

[OwnedEntities.zip](https://github.com/dotnet/efcore/files/9417110/OwnedEntities.zip)

```C#

    [Owned()]
    public class SprintOverview
    {
      
        [Required]
        public  long ScrumMasterId { get; set; }

        [Required]
        [MaxLength(100)]
        public string Goal { get; set; }
        public decimal PlannedStoryPoint { get; set; }
     
        public decimal SuccessPoint { get; set; }
    
       public virtual ISet<SprintProductOwnerUser> SprintProductOwnerUsers { get; set; }
     
    }
  [Table("Sprints")]
    public class Sprint 
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public long JiraId { get; set; }
        [Required]
        public long BoardId { get; set; }
        
        [Required]
        [MaxLength(255)]
        public  string Name { get; set; }
        [MaxLength(4000)]
        public  string ConfluenceUrl { get; set; }
        public  DateTime StartDate { get; set; }
        public  DateTime? EndDate { get; set; }
             
        public  SprintOverview SprintOverview { get; set; }

    }


  [Table("SprintProductOwnerUsers")]
    public class SprintProductOwnerUser 
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public long UserId { get; set; }

        [Required]
        public long SprintId { get; set; }
           
        public virtual Sprint Sprint { get; set; }
       
        public virtual JiraUser User { get; set; }

    }
 [Table("JiraUsers")]
    public class JiraUser
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Code { get; set; }
        [Required]

        public string Name { get; set; }
        [Required]

        public string DisplayName { get; set; }
  
    }
public class OwnedEntityContext : DbContext
{
    public DbSet<JiraUser> Users { get; set; }
    public DbSet<SprintProductOwnerUser> SprintProductOwnerUsers { get; set; }
    public DbSet<Sprint> Sprints { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=EFOwnedEntity;Trusted_Connection=True");
   
 
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
 
    }
 
}
```

### Include verbose output

```
  PM> add-migration initial -OutputDir "Migrations" -Context OwnedEntityContext -verbose
Using project 'Modeling\OwnedEntities'.
Using startup project 'Modeling\OwnedEntities'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile D:\Collection\EntityFramework.Docs-main\samples\core\Modeling\OwnedEntities\bin\Debug\net6.0\EFModeling.OwnedEntities.deps.json --additionalprobingpath C:\Users\secakir\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig D:\Collection\EntityFramework.Docs-main\samples\core\Modeling\OwnedEntities\bin\Debug\net6.0\EFModeling.OwnedEntities.runtimeconfig.json C:\Users\secakir\.nuget\packages\microsoft.entityframeworkcore.tools\6.0.0\tools\netcoreapp2.0\any\ef.dll migrations add initial --json --output-dir Migrations --context OwnedEntityContext --verbose --no-color --prefix-output --assembly D:\Collection\EntityFramework.Docs-main\samples\core\Modeling\OwnedEntities\bin\Debug\net6.0\EFModeling.OwnedEntities.dll --project D:\Collection\EntityFramework.Docs-main\samples\core\Modeling\OwnedEntities\OwnedEntities.csproj --startup-assembly D:\Collection\EntityFramework.Docs-main\samples\core\Modeling\OwnedEntities\bin\Debug\net6.0\EFModeling.OwnedEntities.dll --startup-project D:\Collection\EntityFramework.Docs-main\samples\core\Modeling\OwnedEntities\OwnedEntities.csproj --project-dir D:\Collection\EntityFramework.Docs-main\samples\core\Modeling\OwnedEntities\ --language C# --configuration Debug --working-dir D:\Collection\EntityFramework.Docs-main\samples\core --root-namespace EFModeling.OwnedEntities
Using assembly 'EFModeling.OwnedEntities'.
Using startup assembly 'EFModeling.OwnedEntities'.
Using application base 'D:\Collection\EntityFramework.Docs-main\samples\core\Modeling\OwnedEntities\bin\Debug\net6.0'.
Using working directory 'D:\Collection\EntityFramework.Docs-main\samples\core\Modeling\OwnedEntities'.
Using root namespace 'EFModeling.OwnedEntities'.
Using project directory 'D:\Collection\EntityFramework.Docs-main\samples\core\Modeling\OwnedEntities\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'EFModeling.OwnedEntities'...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'OwnedEntityContext'.
Using context 'OwnedEntityContext'.
System.InvalidOperationException: Unable to determine the relationship represented by navigation 'SprintOverview.SprintProductOwnerUsers' of type 'ISet<SprintProductOwnerUser>'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidatePropertyMapping(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal.SqlServerModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to determine the relationship represented by navigation 'SprintOverview.SprintProductOwnerUsers' of type 'ISet<SprintProductOwnerUser>'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
```

### Include provider and version information

EF Core version: EF 6.0 also EF 5.0 (I tryed in both of them)
Database provider: ( Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (NET 6.0 And NET 5.0 )
Operating system:
IDE: (Visual Studio 2022 17.1.1)

**Comment by smitpatel** [comment]
An owned entity cannot have a collection navigation of a non-owned type. Owned entities can be principal only if they are owning the target type of the relationship else they have to be dependent. A collection navigation cannot be present on dependent side of a relationship.
