### ISSUE TITLE
Seeding no longer takes max batch size into account

### ISSUE THREAD

**Issue by kccsf** [dotnet/efcore#28876]
Adding >1000 rows of seed data to a single entity generates a migration that fails. Should the resulting migration be splitting inserts into batches of 1000 records?:
```using Microsoft.EntityFrameworkCore;

using var test = new BloggingContext();
await test.Database.MigrateAsync();

class BloggingContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; } = null!;

    protected override void OnConfiguring(DbContextOptionsBuilder options)
        => options.UseSqlServer(@"Server=localhost,53133;Database=EFTest;Trusted_Connection=True;Encrypt=false;MultipleActiveResultSets=true;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        var blogs = Enumerable.Range(1, 1001)
            .Select(x => new Blog(x));

        modelBuilder.Entity<Blog>()
            .HasData(blogs);
    }
}

record Blog(int BlogId);
```

```
Unhandled exception. Microsoft.Data.SqlClient.SqlException (0x80131904): The number of row value expressions in the INSERT statement exceeds the maximum allowed number of 1000 row values.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\Users\xxxxx\source\repos\EFTest\Program.cs:line 4
   at Program.<Main>(String[] args)
ClientConnectionId:
Error Number:10738,State:1,Class:15
```

EF Core version: 7.0.0-preview.7.22376.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: Windows
IDE: None (command line)

**Comment by roji** [comment]
Confirmed, we no longer apply the SQL Server 42-commands-per-batch limit in seeding. 

In 6.0, MigrationsModelDiffer.GetDataOperations [has the following](https://github.com/dotnet/efcore/blob/v6.0.8/src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs#L2224):

```c#
var model = updateAdapter.Model.GetRelationalModel();
var commandBatches = new CommandBatchPreparer(CommandBatchPreparerDependencies)
    .BatchCommands(entries, updateAdapter);
```

In 7.0, [we just have this](https://github.com/dotnet/efcore/blob/release/7.0/src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs#L2205):

```c#
var commandSets = new CommandBatchPreparer(CommandBatchPreparerDependencies)
    .TopologicalSort(commands);
```

@AndriySvyryd this change was part of #27903 ([here's the code](https://github.com/dotnet/efcore/commit/0dc7cadca42#diff-61230962b4a1d0cd88337523544ae46181e41f589bd4af21fc3dc19f5ceb0e77R2162)).
