### ISSUE TITLE
ObjectDisposedException when DbContext.ChangeTracker is accessed immediately after the DbContext construction.

### ISSUE THREAD

**Issue by OndrejUzovic** [dotnet/efcore#28935]
After few days (almost two weeks) of running without any problems our application started to throw a very strange ObjectDisposedException. The exception occurs when the DbContext is instantiated and then ChangeTracker.QueryTrackingBehavior is set.

The code looks like this:

```
var dbContext = new DbContext(myOptions);

// This call throws the ObjectDisposedException
dbContext.ChangeTracker.QueryTrackingBehavior = false;

```

Any idea what could be wrong? 

Here is the exception call-stack:

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Diagnostics.Internal.ScopedLoggerFactory.Create(IServiceProvider internalServiceProvider, IDbContextOptions contextOptions)
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_0(IServiceProvider p)
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_ChangeTracker()
   at Semafor.Domain.SemaforDbContext.CreateNewDbContext(Boolean isAutomatedTracking) in C:\Repos\Semafor\Semafor.Domain\SemaforDbContext.cs:line 241

```

### Include provider and version information

EF Core version: 6.0.8
Database provider: MS SQL Server
Target framework: .NET 6.0
Operating system: Microsoft Windows 10.0.14393
IDE: Visual Studion Community 2022

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by OndrejUzovic** [comment]
Thanks for the response.
The issue occurred after several days of running without any problems. Then users started to complain about freezing/crashing of the web application. When I investigated the issue I found a lot of these exceptions in the log file.
So currently I do not have details how to reproduce it. So I will investigate further and try to provide more information.
