### ISSUE TITLE
a question about DbContext's Lifetime

### ISSUE THREAD

**Issue by QianYS** [dotnet/efcore#28951]
when API access more
some access has error
An unhandled exception was thrown by the application.
System.InvalidOperationException: A second operation was started on this context before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
some access is success

when I restart service   it's will be ok;

webapi:

```C#
        [HttpPut("{id}")]
        [DisplayName("PutProduct")]
        public async Task<Response<bool>> PutProduct(long id, [FromBody] UpdateChProductModel data)
        {
            var temp = await _context.ChProducts.FirstOrDefaultAsync(x => x.Id == id);
            if (temp == null)
                return ResultBuilder.FailResult(false, "product is not exist");

            temp.Status = data.Status;
            temp.PurPrice = data.PurPrice;
            temp.LastUpdate = DateTime.Now;

            await _context.SaveChangesAsync();

            await _operateLogSvr.SaveLog(_curUserHelp.UserInfo.Id, LogType.ChProd,
                _curUserHelp.UserInfo.Name + "PutProduct:" + JsonSerializer.Serialize(temp));

            return ResultBuilder.SuccessResult(true, "success");
        }
```

injection:
```C#
        private readonly QYSDbContext_context;
        private readonly IOperateLogService _operateLogSvr;
        private readonly CurUserHelp _curUserHelp;

        /// <summary>
        /// Product
        /// </summary>
        /// <param name="context"></param>
        /// <param name="operateLogSvr"></param>
        /// <param name="curUserHelp"></param>
        public ProductController(QYSDbContext context, IOperateLogService operateLogSvr, CurUserHelp curUserHelp)
        {
            _context = context;
            _operateLogSvr = operateLogSvr;
            _curUserHelp = curUserHelp;
        }
```
IOperateLogService's info:

```C#
    public class OperateLogService : IOperateLogService
    {

        private readonly IServiceScopeFactory _serviceScopeFactory;
        private readonly CommLogNo _commLogNo;

        public OperateLogService(IServiceScopeFactory serviceScopeFactory, CommLogNo commLogNo)
        {
            _serviceScopeFactory = serviceScopeFactory;
            _commLogNo = commLogNo;

        }

        /// <summary>
        /// add
        /// </summary>
        /// <param name="userId"></param>
        /// <param name="type"></param>
        /// <param name="remark"></param>
        /// <returns></returns>
        public async Task SaveLog(long userId, LogType type, string remark)
        {
            var operateLog = new OperateLog
            {
                Id = _commLogNo.NewId(),
                Type = type,
                UserId = userId,
                Remark = remark,
                CreateTime = DateTime.Now,
            };

            using var scope = _serviceScopeFactory.CreateScope();
            var context = scope.ServiceProvider.GetRequiredService<QYSDbContext>();
            await context.OperateLogs.AddAsync(operateLog);
            await context.SaveChangesAsync();
        }
     }
```

AddDbContext:

```C#
                services.AddDbContextPool<QYSDbContext>((p, options) =>
                {
                    var svr = p.GetService<SaveChangeTrigger>();
                    options.AddInterceptors(svr);

                    options.UseMySql(_configuration.GetValue<string>("ConnectionStrings:cgmysql"),
                        ServerVersion.AutoDetect(_configuration.GetValue<string>("ConnectionStrings:cgmysql")));
                });
```

why this error is happened
in OperateLogService， I use IServiceScopeFactory 

how can I fixed it

change AddDbContextPool to AddDbContext  and set ServiceLifetime  to ServiceLifetime.Transient
or set  scope.ServiceProvider.GetRequiredService  to  scope.ServiceProvider.GetService  ?

**Comment by ajcvickers** [comment]
@QianYS Can you post the full stack trace from the exception?

**Comment by QianYS** [comment]
I'm not recorded the full stack trace

**Comment by QianYS** [comment]
if need,   when this question happend again, I try to find and provide

**Comment by roji** [comment]
Closing for now, can reopen if the details are provided.

**Comment by QianYS** [comment]
2022-09-01 15:10:57.318 +08:00 [ERR] Connection id "0HMK9FQDN9BSE", Request id "0HMK9FQDN9BSE:00000002": An unhandled exception was thrown by the application.
System.InvalidOperationException: A second operation was started on this context before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at ZR.Charge.Service.Services.OperateLogService.SaveLog(Int64 userId, LogType type, String remark) in /var/lib/jenkins/workspace/CG_Mng/ZrCharge/ZR.Charge.Service/Services/OperateLogService.cs:line 45
   at ZR.Charge.Mng.Api.Controllers.Mng.ChProductController.Put(Int64 id, UpdateChProductModel data) in /var/lib/jenkins/workspace/CG_Mng/ZrCharge/ZR.Charge.Mng.Api/Controllers/Mng/ChProductController.cs:line 176
   at lambda_method2644(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
