### ISSUE TITLE
Is there anyway to debug Add-Migrations?

### ISSUE THREAD

**Issue by huang-tianwen** [dotnet/efcore#29090]
I refactor my code to inherit my entities from an abstract generic type.
If I Add-Migrations from Existing migrations it give me error.   
But, If I delete all previous Migrations and run Add-Migrations. It will create a new successful migration file.
The error is the following:

```
System.ArgumentException: An item with the same key has already been added. Key: System.Object Item [System.String]
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetSortedProperties(IEntityType entityType, ITable table)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetSortedColumns(ITable table)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Add(ITable target, DiffContext diffContext)+MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.DiffCollection[T](IEnumerable`1 sources, IEnumerable`1 targets, DiffContext diffContext, Func`4 diff, Func`3 add, Func`3 remove, Func`4[] predicates)+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IRelationalModel source, IRelationalModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
 ```

Is there anyway to debug the Add-Migrations process? because the error message with "Key: System.Object Item [System.String]" is not helpful. I cannot know which part of my code might have conflicted key.

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 6.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.3.4)

**Comment by qsdfplkj** [comment]
I add `if (!Debugger.IsAttached) Debugger.Launch();` in my IDesignTimeDbContextFactory so I only have to attach a debugger when working with the migrations.
But any other point that runs before it's configuring the model (like ConfigureServices or in OnConfiguring as the first line or just the constructor of the dbContext will enable you to attach the debugger.

**Comment by ajcvickers** [comment]
@huang-tianwen The suggestion by @qsdfplkj is good.

**Comment by huang-tianwen** [comment]
Ok, will try it

**Comment by huang-tianwen** [comment]
@qsdfplkj @ajcvickers  thanks for help

**Comment by roji** [comment]
Here's a snippet I sometimes use to add a migration from a console program, in order to debug issues:

```c#
using var ctx = new BlogContext();

var services = new ServiceCollection()
    .AddEntityFrameworkDesignTimeServices()
    .AddDbContextDesignTimeServices(ctx);

var npgsqlDesignTimeServices = new NpgsqlDesignTimeServices();
npgsqlDesignTimeServices.ConfigureDesignTimeServices(services);

var serviceProvider = services.BuildServiceProvider();
var scaffolder = serviceProvider.GetRequiredService<IMigrationsScaffolder>();
var migration = scaffolder.ScaffoldMigration(
    "MyMigration",
    "MyApp.Data");

Console.WriteLine(migration.MigrationCode);
```

**Comment by jinzaz** [comment]
> 这是我有时用来从控制台程序添加迁移的代码片段，以便调试问题：
> 
> using var ctx = new BlogContext();
> 
> var services = new ServiceCollection()
>     .AddEntityFrameworkDesignTimeServices()
>     .AddDbContextDesignTimeServices(ctx);
> 
> var npgsqlDesignTimeServices = new NpgsqlDesignTimeServices();
> npgsqlDesignTimeServices.ConfigureDesignTimeServices(services);
> 
> var serviceProvider = services.BuildServiceProvider();
> var scaffolder = serviceProvider.GetRequiredService<IMigrationsScaffolder>();
> var migration = scaffolder.ScaffoldMigration(
>     "MyMigration",
>     "MyApp.Data");
> 
> Console.WriteLine(migration.MigrationCode);
this ways can i replace  `IMigrationsSqlGenerator` to apply  ScaffoldMigration ?  i try it is not effetive.  i wish to apply this way or my package CLI "Add-Migration" cmd
