### ISSUE TITLE
Can't get DbFunction to work with DateOnly

### ISSUE THREAD

**Issue by lara-ec** [dotnet/efcore#29187]
Hi,

I'm currently migrating to .NET 6, and given the introduction of `DateOnly`, I want to create a variation of an existing DbFunction, `UtcToBerlinTimeZone()`, that returns `DateOnly` instead of `DateTime`, called `UtcToBerlinDate()`. But I can't get it to work, it always throws an exception.

I have an implementation for both SQLite (Unit Tests) and MySQL (normal operation), and both fail in the same way.

Any help in understanding the issue would be much appreciated :)

### Function declaration
```C#
public static DateTime UtcToBerlinTimeZone(DateTime datetime)
{
    throw new NotImplementedException("Only use in LINQ2SQL");
}

public static DateOnly UtcToBerlinDate(DateTime datetime)
{
    throw new NotImplementedException("Only use in LINQ2SQL");
}
```

### Old function, that still works
```C#
if (Database.IsSqlite())
{
    modelBuilder
        .HasDbFunction(
            typeof(Functions.Functions).GetMethod(
                nameof(Functions.Functions.UtcToBerlinTimeZone)
            )!
        )
        .HasName(nameof(Functions.Functions.UtcToBerlinTimeZone))
        .HasTranslation(
            args =>
                new SqlFunctionExpression(
                    "utc_to_berlin_time",
                    new[] { args[0] },
                    true,
                    new[] { true },
                    typeof(DateTime),
                    new DateTimeTypeMapping("datetime", DbType.DateTime)
                )
        );
}
else
{
    modelBuilder
        .HasDbFunction(
            typeof(Functions.Functions).GetMethod(
                nameof(Functions.Functions.UtcToBerlinTimeZone)
            )!
        )
        .HasName(nameof(Functions.Functions.UtcToBerlinTimeZone))
        .HasTranslation(
            args =>
                new SqlFunctionExpression(
                    "CONVERT_TZ",
                    new[]
                    {
                        args[0],
                        new SqlConstantExpression(
                            Expression.Constant("UTC"),
                            new StringTypeMapping("varchar", DbType.String)
                        ),
                        new SqlConstantExpression(
                            Expression.Constant("Europe/Berlin"),
                            new StringTypeMapping("varchar", DbType.String)
                        ),
                    },
                    true,
                    new[] { true, false, false },
                    typeof(DateTime),
                    new DateTimeTypeMapping("datetime", DbType.DateTime)
                )
        );
}
```

### New modification, that doesn't work
```C#
if (Database.IsSqlite())
{
    modelBuilder
        .HasDbFunction(
            typeof(Functions.Functions).GetMethod(
                nameof(Functions.Functions.UtcToBerlinDate)
            )!
        )
        .HasName(nameof(Functions.Functions.UtcToBerlinDate))
        .HasTranslation(
            args =>
                new SqlFunctionExpression(
                    "date",
                    new[]
                    {
                        new SqlFunctionExpression(
                            "utc_to_berlin_time",
                            new[] { args[0] },
                            true,
                            new[] { true },
                            typeof(DateTime),
                            new DateTimeTypeMapping("datetime", DbType.DateTime)
                        ),
                    },
                    true,
                    new[] { true },
                    typeof(DateOnly),
                    new DateTimeTypeMapping("date", DbType.Date)
                )
        );
}
else
{
    modelBuilder
        .HasDbFunction(
            typeof(Functions.Functions).GetMethod(
                nameof(Functions.Functions.UtcToBerlinDate)
            )!
        )
        .HasName(nameof(Functions.Functions.UtcToBerlinDate))
        .HasTranslation(
            args =>
                new SqlFunctionExpression(
                    "DATE",
                    new[]
                    {
                        new SqlFunctionExpression(
                            "CONVERT_TZ",
                            new[]
                            {
                                args[0],
                                new SqlConstantExpression(
                                    Expression.Constant("UTC"),
                                    new StringTypeMapping("varchar", DbType.String)
                                ),
                                new SqlConstantExpression(
                                    Expression.Constant("Europe/Berlin"),
                                    new StringTypeMapping("varchar", DbType.String)
                                ),
                            },
                            true,
                            new[] { true, false, false },
                            typeof(DateTime),
                            new DateTimeTypeMapping("datetime", DbType.DateTime)
                        ),
                    },
                    true,
                    new[] { true },
                    typeof(DateOnly),
                    new DateTimeTypeMapping("date", DbType.Date)
                )
        );
}
```

### This is the error I always get
```
System.InvalidOperationException: No coercion operator is defined between types 'System.DateTime' and 'System.Nullable`1[System.DateOnly]'.
   at System.Linq.Expressions.Expression.GetUserDefinedCoercionOrThrow(ExpressionType coercionType, Expression expression, Type convertToType)
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type, MethodInfo method)
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.CreateGetValueExpression(ParameterExpression dbDataReader, Int32 index, Boolean nullable, RelationalTypeMapping typeMapping, Type type, IPropertyBase property)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitNew(NewExpression node)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.ProcessShaper(Expression shaperExpression, RelationalCommandCache& relationalCommandCache, LambdaExpression& relatedDataLoaders, Int32& collectionId)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.VisitShapedQuery(ShapedQueryExpression shapedQueryExpression)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Startup.Program.Main(String[] args) in Startup/Program.cs:line 52
```

### Include provider and version information

EF Core version: 6.0.9
Database provider: Pomelo.EntityFrameworkCore.MySql 6.0.2 and Microsoft.EntityFrameworkCore.Sqlite 6.0.9
Target framework: .NET 6.0
Operating system: Ubuntu 22.04
IDE: JetBrains Rider 2022.2.3

**Comment by roji** [comment]
The type mapping of the `date` function probably needs to be a DateOnlyTypeMapping and not a DateTimeTypeMapping, since you want it to return a DateOnly.

If that still doesn't work, please send a runnable, minimal code sample for Sqlite, including your actual function - just a single Program.cs which we can execute to see the error happening.

**Comment by lara-ec** [comment]
Ah, thank you! That was the issue :)

now I feel a bit silly x)
