### ISSUE TITLE
FromSqlInterpolated does not set query parameters correctly for update statement

### ISSUE THREAD

**Issue by zornwal** [dotnet/efcore#29241]
When using ```FromSqlInterpolated``` to execute an update query and output the resulting row, I run into an issue with the way EF Core generates the query parameters for the statement.

I have compared what should be equivalent (in function) versions of the query using ```FromRawSql``` and ```FromSqlInterpolated``` which shows that the interpolated method does not define query parameters correctly.

### Datacontext setup
```C#
[...]
        public virtual DbSet<Issuer> Issuers { get; set; }
        public virtual DbSet<StanSequence> StanSequences { get; set; }
[...]
    modelBuilder.Entity<StanSequence>(e =>
            {
                e.ToTable("StanSequences", "Issuer");

                e.HasKey(e => e.IssuerId);
                e.HasOne(e => e.Issuer).WithMany().HasForeignKey(e => e.IssuerId);
            });
```

### Entity 
```C#
public class StanSequence
{
    public int IssuerId { get; set; }
    public Issuer Issuer { get; set; }

    public int STAN { get; set; }
}
```

### FromSqlRaw
Using ```FromSqlRaw()``` works fine, confirming that the query is valid and that EF Core is able to map the output to the entity type.
```C#  
 var stan = await _dataContext.StanSequences
    .FromSqlRaw( 
        "UPDATE " + schema.GetSchemaQualifiedTableName() + " SET STAN = STAN + 1 OUTPUT inserted.* where IssuerId = " + issuerId
    ).ToListAsync();      
```
### FromSqlInterpolated
When using ```FromSqlInterpolated()``` EF Core does not generate the query parameter SQL correctly, and consequently the query fails.
```C#
  var stan = await _dataContext.StanSequences
    .FromSqlInterpolated(
            $"UPDATE {schema.GetSchemaQualifiedTableName()} SET STAN = STAN + 1 OUTPUT inserted.* where IssuerId = {issuerId}"
    ).ToListAsync();
```
It fails with the following error message and stack trace:
```
30-09-2022 10:13:04 [ERR] Failed executing DbCommand ("21"ms) [Parameters=["p0='?' (Size = 4000), p1='?' (DbType = Int32)"], CommandType='Text', CommandTimeout='30']"\r\n""UPDATE @p0 SET STAN = STAN + 1 OUTPUT inserted.* where IssuerId = @p1"

```
```
Microsoft.Data.SqlClient.SqlException (0x80131904): Must declare the table variable "@p0".
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__188_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```
And calling ```ToQueryString()``` on the ```FromSqlInterpolated()``` query yields the following query:
```SQL
DECLARE p0 nvarchar(4000) = N'Issuer.StanSequences';
DECLARE p1 int = 107;

UPDATE @p0 SET STAN = STAN + 1 OUTPUT inserted.* where IssuerId = @p1

```

### Version info

EF Core version: 6.0.9
Database provider:  Microsoft.EntityFrameworkCore.SqlServer 6.0.9
Target framework: .NET 6.0

**Comment by roji** [comment]
@zornwal you probably want to give [this section of the docs](https://learn.microsoft.com/en-us/ef/core/querying/sql-queries#dynamic-sql-and-parameters) a good read.

FromSqlInterpolated parameterizes values you provide it; that means that it wraps the value in a DbParameter and integrates a placeholder into the SQL (that's the `@p0` you're seeing above). This is the right thing to do in the vast majority of cases - it protects against SQL injection attacks and ensures the query executes efficiently.

However, databases don't support parameterizing tables names: that's a "dynamic SQL" scenario which doesn't work with  FromSqlInterpolated. You should be using FromSqlRaw in this case, but be aware that it's your responsibility to protect against SQL injection attacks; in the above code you're integrating a table name from the EF model, which should generally be fine - but if any user-provided value is given, you must sanitize it first.

**Comment by zornwal** [comment]
Ah okay, It's been a while since I've been writing my own SQL ;) thanks for the quick response.
