### ISSUE TITLE
`ExecuteUpdate` with `Dictionary<string, object?>` update condition

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/efcore#29247]
## Ask a question

I'm trying to migrate some `update`/`delete` from efcore6 to ef7 to adopt the batch update/delete, when I migrated, the `Dictionary<string, object?>` condition not works so well, so I'm here looking for some help

### Include your code

Sample code:

```C#
var services = new ServiceCollection();
services.AddDbContext<TestDbContext>(options =>
{
    options.UseSqlite("Data Source=Test.db");
});
using var serviceProvider = services.BuildServiceProvider();
using var scope = serviceProvider.CreateScope();
var dbContext = scope.ServiceProvider.GetRequiredService<TestDbContext>();
var repo = new EFRepository<TestEntity>(dbContext);
repo.Update(x => x.Extra != null, new Dictionary<string, object?>()
{
    { "Extra", "12345"}
});

public class EFRepository<TEntity>
{
    public TestDbContext DbContext { get; }

    public EFRepository(TestDbContext dbContext)
    {
        DbContext = dbContext;
    }

    public virtual int Update(Expression<Func<TEntity, bool>> whereExpression, IDictionary<string, object?>? propertyValues)
    {
        if (propertyValues.IsNullOrEmpty())
        {
            return 0;
        }
    
        Expression<Func<SetPropertyCalls<TEntity>, SetPropertyCalls<TEntity>>> setExpression = _ => _;
        foreach (var propertyValue in propertyValues)
        {
            var propertyExp = GetPropertyExpression(propertyValue.Key);
            setExpression = c => c.SetProperty(propertyExp, _ => propertyValue.Value);
        }    
        return DbContext.Set<TEntity>().Where(whereExpression).ExecuteUpdate(setExpression);
    }
    
    private Expression<Func<TEntity, object?>> GetPropertyExpression(string propertyName)
    {
        var parameterExpression = Expression.Parameter(typeof(TEntity), "x");
        var memberExpression = Expression.Property(parameterExpression, propertyName);
        var lambda = Expression.Lambda<Func<TEntity, object?>>(memberExpression, parameterExpression);
        return lambda;
    }
}
```

For detailed sample, see <https://github.com/WeihanLi/WeihanLi.EntityFramework/blob/5d231d7a0aad4fbdadf7e537cb32e7e170e10f57/samples/WeihanLi.EntityFramework.Sample/Program.cs>

### Include stack traces

![image](https://user-images.githubusercontent.com/7604648/193433532-81483b43-3be0-4a4f-a261-e788567cf4ca.png)

```
System.InvalidOperationException: Expression '@__8__locals1_propertyValue_Value_0' in the SQL tree does not have a type mapping assigned.
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.SqlTypeMappingVerifyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlUnaryExpression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitExtension(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.SqlTypeMappingVerifyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlBinaryExpression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitExtension(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.SqlTypeMappingVerifyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TranslateInternal(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.<TranslateExecuteUpdate>g__TranslateSetPropertyExpressions|57_0(RelationalQueryableMethodTranslatingExpressionVisitor visitor, ShapedQueryExpression source, SelectExpression selectExpression, TableExpression tableExpression, List`1 propertyValueLambdaExpressions, List`1 leftExpressions)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateExecuteUpdate(ShapedQueryExpression source, LambdaExpression setPropertyCalls)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.RelationalQueryableExtensions.ExecuteUpdate[TSource](IQueryable`1 source, Expression`1 setPropertyCalls)
   at WeihanLi.EntityFramework.EFRepository`2.Update(Expression`1 whereExpression, IDictionary`2 propertyValues)
```

### Include provider and version information

EF Core version: 7.0.0-rc1
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework:  .NET 6.0
Operating system: Windows

---- edit ib Oct 5, update sample code ---

**Comment by ajcvickers** [comment]
This call `repo.Update(x => x.Extra != null, x => x.Extra ,  new{ Date= DateTimeOffset.Now }.ToJson());` doesn't match the signature `Update(Expression<Func<TEntity, bool>> whereExpression, IDictionary<string, object?>? propertyValues)` of your Update method.

**Comment by WeihanLi** [comment]
@ajcvickers , sorry for the incorrect sample, I had updated the sample code, it should like follows:

``` c#
repo.Update(x => x.Extra != null, new Dictionary<string, object?>()
{
    { "Extra", "12345"}
});
```

**Comment by ajcvickers** [comment]
@WeihanLi To investigate this I'm going to need to take your code and turn it into something I can run. Could you do that instead? You know more about what the missing pieces are supposed to do than I do.

**Comment by smitpatel** [comment]
The most likely cause of the error here too many object converts. When writing compiler generated construct, `SetProperty` calls are generic-typed on actual property type. In above construction, it is using object type rather than actual property type. Further, dictionary is also defined as having object value but storing int value. A properly generated tree which satisfies generic types correctly rather than bypassing it using object should be working fine.
