### ISSUE TITLE
Use custom converter results in duplicate resulting column names

### ISSUE THREAD

**Issue by Der-Kraken** [dotnet/efcore#29265]
### My code to reproduce the error

``` csharp
public abstract class KeyBase<T>
    where T : struct
{
    public KeyBase(T key)
    {
        Key = key;
    }

    public T Key { get; }

    public override string ToString()
    {
        return Key.ToString();
    }

    public override bool Equals(object obj)
    {
        return Key.Equals(obj);
    }

    public override int GetHashCode()
    {
        return Key.GetHashCode();
    }
}

public class ParentId : KeyBase<int>
{
    public ParentId(int key) : base(key)
    {
    }

    public static implicit operator int(ParentId d) => d.Key;
}

public class Parent
{
    public ParentId ParentId { get; set; }
    public string Name { get; set; }

    public IList<Child> Childs { get; set; }
}

public class Child
{
    public int ChildId { get; set; }
    public int ParentId { get; set; }
    public string Name { get; set; }

    public Parent Parent { get; set; }
}

public class TestDbContext : DbContext
{
    public TestDbContext()
    {
    }

    public TestDbContext(DbContextOptions<TestDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Parent> Parents { get; set; }
    public virtual DbSet<Child> Child { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        const string schema = "dbo";

        modelBuilder.Entity<Parent>(entity =>
        {
            entity.ToTable(nameof(Parent), schema);
            entity.HasKey(o => o.ParentId);
            entity.Property(o => o.ParentId)
                    .HasConversion(
                    o => o.Key,
                    o => new ParentId(o))
                ;
        });

        modelBuilder.Entity<Child>(entity =>
        {
            entity.ToTable(nameof(Child), schema);
            entity.HasKey(o => o.ChildId);
            entity.Property(o => o.ChildId);

            entity.HasOne(o => o.Parent)
                .WithMany(o => o.Childs)
                .OnDelete(DeleteBehavior.Cascade)
                ;
        });

        base.OnModelCreating(modelBuilder);
    }
}
```

``` csharp
public class MyClass
{
    private readonly TestDbContext _testDbContext;

    public MyClass(TestDbContext testDbContext)
    {
        _testDbContext = testDbContext ?? throw new ArgumentNullException(nameof(testDbContext));
    }

    public void Get()
    {
        _testDbContext.Parents.FirstOrDefault(); // <- This is working.
        _testDbContext.Parents.Include(o => o.Childs).FirstOrDefault(); // <- This is not working.
    }
}
```

## Below is the sql part to create the required tables
``` sql
CREATE TABLE [dbo].[Parent](
	[ParentId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Parent] PRIMARY KEY CLUSTERED 
(
	[ParentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[Child](
	[ChildId] [int] IDENTITY(1,1) NOT NULL,
	[ParentId] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Child] PRIMARY KEY CLUSTERED 
(
	[ChildId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Child]  WITH CHECK ADD  CONSTRAINT [FK_Child_Parent] FOREIGN KEY([ParentId])
REFERENCES [dbo].[Parent] ([ParentId])
GO

ALTER TABLE [dbo].[Child] CHECK CONSTRAINT [FK_Child_Parent]
```

## The Problem

I tried to use a typed primary key for **Parent**. The concept itself is working if I not load the childs. So the convert itself is working.
If the childs should be included then the generated sql (see code below) will have duplicate column names (ParentId).
Entity Framework cannot read the correct column.

If I remove the custom code for converting or typed primary key then all is working fine.

Is there something wrong in configuration? It seems like a bug to me.

### The generated SQLfrom Entity Framework Core
``` sql
SELECT [t].[ParentId], [t].[Name], [c].[ChildId], [c].[Name], [c].[ParentId], [c].[ParentId1]
FROM (
    SELECT TOP(1) [p].[ParentId], [p].[Name]
    FROM [dbo].[Parent] AS [p]
) AS [t]
LEFT JOIN [dbo].[Child] AS [c] ON [t].[ParentId] = [c].[ParentId1]
ORDER BY [t].[ParentId], [c].[ChildId]
```

### The error Message and StackTrace

I got 2 different messages for the same problem:

First one:
```
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Ungültiger Spaltenname "ParentId1".
Ungültiger Spaltenname "ParentId1".
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.First[TSource](IQueryable`1 source)
   ...
```

Second one: 
```
 ---> System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   ...
```

### Include provider and version information

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 5.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment]
@Der-Kraken EF Core requires that foreign key property types match the primary key property type. If the PK is `ParentId `, then the FK must also be `ParentId `.

**Comment by smitpatel** [comment]
Since PK is using custom converter, it may also require to be configured to use a custom key comparer. That could be one potential issue if it is failing FirstOrDefault only with Include.

**Comment by Der-Kraken** [comment]
> @Der-Kraken The implementation of `Equals` on your key type is wrong. It is comparing the `Key` property (and int) to the passed in object (a `KeyBase<T>` in any case where the objects can be equal.) Consider having your IDE generate the equality methods for you. For example, my IDE generates this:
> 
> ```cs
>     protected bool Equals(KeyBase<T> other)
>         => Key.Equals(other.Key);
> 
>     public override bool Equals(object? obj)
>     {
>         if (ReferenceEquals(null, obj))
>         {
>             return false;
>         }
> 
>         if (ReferenceEquals(this, obj))
>         {
>             return true;
>         }
> 
>         if (obj.GetType() != this.GetType())
>         {
>             return false;
>         }
> 
>         return Equals((KeyBase<T>)obj);
>     }
> 
>     public override int GetHashCode()
>         => Key.GetHashCode();
> ```

Thank you. The error was indeed in the equals method. EFCore is working well. So this issue can be closed.

```  csharp
        public override bool Equals(object obj)
        {
            if (obj is IKey key)
            {
                return Key.Equals(key.Key);
            }

            return Key.Equals(obj);
        }
``` 

Now all is working fine, except create new objects. But this is the next part for me.
Thank you very much!
