### ISSUE TITLE
Recursive CTE call in FromSqlRaw always fails with InvalidOperationException (was called with non-composable SQL and with a query composing over it)

### ISSUE THREAD

**Issue by marc-mueller** [dotnet/efcore#29266]
## Ask a question

I'm trying to run a SQL query to provide a flat list of entities queried by a recursive CTE query. The call always ends in an InvalidOperationException stating that is was called with non-composable SQL and with a query composing over it. There is no additional composing and calling AsEnumerable() does not help either. I also tried to wrap it in a StoredProcedure returning the same fields as the original table, same error. 

Why is this SQL execution failing?

### Include your code

```C#
var sql = @"
    with cte as (
        select gu.[CreatedOn]  ,gu.[CreatedBy]   ,gu.[ModifiedOn]    ,gu.[ModifiedBy]      ,gu.[InstanceId], gu.[Id] ,gu.[Name] from [Group] as gu
        join [UserToGroupMapping] ug on gu.Id = ug.MemberOfGroupsId
        where ug.MemberUsersId = {0}
        union all
        select gm.[CreatedOn]  ,gm.[CreatedBy]   ,gm.[ModifiedOn]    ,gm.[ModifiedBy]      ,gm.[InstanceId], gm.[Id] ,gm.[Name] from [Group] as gm
        join [GroupToGroupMapping] gg on gm.Id = gg.ParentGroupsId
        join cte on cte.Id = gg.MemberGroupsId
    )
    select * from cte
    ";
return dbset.FromSqlRaw(sql, userId).AsEnumerable().ToList();
```

or
```C#
var sql = "Exec dbo.GetAllGroupMembershipFromUser {0}";
return dbset.FromSqlRaw(sql, userId).AsEnumerable().ToList();
```
### Include provider and version information

EF Core version: 6.0.9
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 11 Enterprise 22621.521
IDE: Visual Studio 2022

**Comment by roji** [comment]
I can't reproduce this, see below for a runnable, minimal repro that works with a CTE SQL query. Can you please submit a similar, fully runnable sample which fails (or tweak the below to make it fail)?

BTW there's no real sense in putting AsEnumerable and then ToList; if you want is a List (buffer all query results), simply put a ToList without AsEnumerable. If you want to compose additional LINQ operators to execute client-side in .NET (without translation to SQL), put an AsEnumerable followed by those operators (without ToList).

<details>
<summary>Attempted repro</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

var sql = @"
WITH cte AS (
    SELECT * FROM Blogs WHERE id = {0}
)
SELECT * FROM cte";

_ = await ctx.Blogs.FromSqlRaw(sql, 8).ToListAsync();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
    }
}

public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

</details>?

**Comment by marc-mueller** [comment]
Hi Roji

Thank you for your fast feedback. It tried to repro the error in a much simpler application as you suggested and it worked as expected. With the real application (the entities are a little bit more complex and there are a couple of abstraction layers in between, but the Group entity is 1:1 the same in the repro attempt) it fails constantly with the above error.

Exception: {System.InvalidOperationException: 'FromSqlRaw' or 'FromSqlInterpolated' was called with non-composable SQL and with a query composing over it. Consider calling 'AsEnumerable' after the method to perform the composition on the client side.
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.CheckComposableSql(String sql)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.VisitFromSql(FromSqlExpression fromSqlExpression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerQuerySqlGenerator.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.<VisitSelect>b__19_1(TableExpressionBase e)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.GenerateList[T](IReadOnlyList`1 items, Action`1 generationAction, Action`1 joinAction)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.VisitSelect(SelectExpression selectExpression)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.GetCommand(SelectExpression selectExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalCommandCache.GetRelationalCommandTemplate(IReadOnlyDictionary`2 parameters)
   at Microsoft.EntityFrameworkCore.Internal.RelationCommandCacheExtensions.RentAndPopulateRelationalCommand(RelationalCommandCache relationalCommandCache, RelationalQueryContext queryContext)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at ProAuth.IdpModules.UserStore.Repositories.GroupRepository.GetAllGroupMembershipFromUser(Guid userId) in C:\Repos\Work\ProAuth.Core\IdpModules\ProAuth.IdpModules.UserStore\Repositories\GroupRepository.cs:line 167
   at ProAuth.IdpModules.UserStore.Services.GroupService.GetAllGroupMembershipFromUser(Guid userId, QueryFilter`1 filter) in C:\Repos\Work\ProAuth.Core\IdpModules\ProAuth.IdpModules.UserStore\Services\GroupService.cs:line 122
   at ProAuth.IdpModules.UserStore.Generators.ClaimGeneratorService.GenerateClaims(Guid userId) in C:\Repos\Work\ProAuth.Core\IdpModules\ProAuth.IdpModules.UserStore\Generators\ClaimGeneratorService.cs:line 67
   at ProAuth.IdpModules.UserStore.Services.ValidationService.GenerateUserClaims(Guid userId) in C:\Repos\Work\ProAuth.Core\IdpModules\ProAuth.IdpModules.UserStore\Services\ValidationService.cs:line 47
   at ProAuth.IdpModules.UserStore.Middleware.UserStoreHandler.HandleRemoteAuthenticateAsync() in C:\Repos\Work\ProAuth.Core\IdpModules\ProAuth.IdpModules.UserStore\Middleware\UserStoreHandler.cs:line 129
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()}
Stacktrace:
```
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.CheckComposableSql(String sql)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.VisitFromSql(FromSqlExpression fromSqlExpression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerQuerySqlGenerator.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.<VisitSelect>b__19_1(TableExpressionBase e)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.GenerateList[T](IReadOnlyList`1 items, Action`1 generationAction, Action`1 joinAction)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.VisitSelect(SelectExpression selectExpression)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.GetCommand(SelectExpression selectExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalCommandCache.GetRelationalCommandTemplate(IReadOnlyDictionary`2 parameters)
   at Microsoft.EntityFrameworkCore.Internal.RelationCommandCacheExtensions.RentAndPopulateRelationalCommand(RelationalCommandCache relationalCommandCache, RelationalQueryContext queryContext)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MyApp.GroupRepository.GetAllGroupMembershipFromUser(Guid userId) 
```

I currently have no clue what could cause that since the database and the query is the same. Event though there are more layers in between, the repository call FromSqlRaw directly on the DBSet. So there is nothing compose on that. Any suggestion how to isolate the potential cause of this?

**Comment by marc-mueller** [comment]
I finally found the cause of the issue. Took me quite some time. As I told you, the application is pretty complex and there are a couple of layers and this is also the the for the entity type hierarchy. The database is ready to be used in a multi-tenancy environment and therefore there is a default filter configured for every entity to filter the tenant id. 

So during OnModelCreating the EntityTypeBuilder  is called with entitytypebuilder.HasQueryFilter(xxxx). So therefore, there is always a where condition inserted before I can call AsEnumerable() or ToListAsync() on the IQueryable return from FromSqlRaw.  This is why is it constantly failing in the real application. 

Is there a way to disable the HasQueryFilter just for the FromSqlRaw() calls?

**Comment by anarahmadov** [comment]
Hey, I did this, but still, get this error. Any solution please?

**Comment by roji** [comment]
@anarahmadov that doesn't supply enough information for us to answer. Please open a new issue with a minimal, runnable repro.

**Comment by neistow** [comment]
@roji I've stumbled upon a similar problem in a similar query on the production project. However, when I tried preparing a minimal, runnable repro, it worked fine in the bare project:

```cs
var result = await ctx.Items.FromSql(
    $"""
          with query as (select * 
                         from Items 
                         where ParentId = {item.Id}
                         union all
                         select item.*
                         from Items item
                         join query q on q.Id = item.ParentId)
          select * from query
     """
).IgnoreQueryFilters().AsNoTracking().ToListAsync();
```

Is there anything I could be missing in the production project that I didn't include in repro that makes EF throw an invalid operation exception? 

We use TPH with column discriminators, so I've added that too.
We use global query filters. I've added that to repro.
Ensured the package Microsoft.EntityFrameworkCore.SqlServer is the same version (9.0.4) as in production project.

Yet still repro behaves fine when production code throws.


UPD: did some more debugging and an exception is thrown in the [SqlServerQueryGenerator](https://github.com/dotnet/efcore/blob/8a8e7581559f35e7d397be89ecc1c21a5782a2ba/src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs#L694) in `sql.StartsWith("WITH"...` check. Tried setting a breakpoint in the repro project on that line and it debugger doesn't hit it. What can cause production code to hit that check while repro doesn't?

**Comment by roji** [comment]
> Is there anything I could be missing in the production project that I didn't include in repro that makes EF throw an invalid operation exception?

That's not really possible for me to know: this is precisely why we need a repro. There's some sort of crucial difference between your production code - where the problem occurs - and your attempted repro - where it doesn't. Since only you have access to your production code, you're the only one in a position to find out what that difference is. You can try starting from the production app and simplifying it, stripping away unnecessary things until you arrive at the minimal repro. I'd advise starting by lifting out the EF model and - importantly - all of its configuration, and going from there.

> Tried setting a breakpoint in the repro project on that line and it debugger doesn't hit it. 

The CheckComposableSqlTrimmed method should be invoked any time you are using FromSql in EF - if you set a breakpoint in it but aren't hitting it, you're likely not calling FromSql. Another idea is that you're putting the breakpoint in the SQL Server override of CheckComposableSqlTrimmed - does your attempted repro use SQL Server?

**Comment by neistow** [comment]
@roji Took me a while, but here's [repo](https://github.com/neistow/efcore-composite-query-bug).

In the summary, the following query is considered uncomposable; however, it should be able to execute, since no additional clauses are present afterwards and ef core shouldn't try to convert it to `select * from (subquery)` syntax
```cs
var items = await ctx.BaseEntities.FromSql(
    $"""
        with query as (select *
                       from BaseEntities
                       where GuidProperty = {guidProperty}
                         and ParentId = {a1.Id}
                       union all
                       select entity.*
                       from BaseEntities entity
                                join query q on q.Id = entity.ParentId)
        select * from query
     """).IgnoreQueryFilters().AsNoTracking().ToListAsync();
```

**Comment by roji** [comment]
@neistow thanks for the repro - after narrowing it down a bit I managed to find the root of the problem: there's indeed a bug in EF which currently makes FromSql incompatible with scenarios where there's an owned JSON entity type. As this issue has been here for a while and may have been opened to deal with other trouble, I've opened another issue to track this specifically: #36282.

**Comment by neistow** [comment]
@roji So, after EF10, we basically can replace owned entity with a complex type serialized to JSON, and this sort of query will work?The reason why we used owned entity is because complex types don't support json yet.

**Comment by roji** [comment]
@neistow that's the plan, yes.

**Comment by neistow** [comment]
@roji, Unfortunately, there is an issue with querying complex types via `FromSql` in .NET 10. I've created a separate issue (#37222) for that and updated repro
