### ISSUE TITLE
Seeding issue with JSON columns in EF Core 7

### ISSUE THREAD

**Issue by ChristopherVR** [dotnet/efcore#29297]
I'm unable to add migration data for an entity containing a JSON column.

Here is the test code I used:
```C#
    public class Disability
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public List<JsonTest> Test { get; set; }
    }

    public class JsonTest
    {
        public string Value { get; set; }
        public string Type { get; set; }

        public JsonTest(string value, string type)
        {
            Value = value;
            Type = type;
        }
    }

    public void Configure(EntityTypeBuilder<Disability> builder)
    {
        builder.ToTable("Disabilities");

        builder.HasData(new
        {
            Id = 1,
            Name = "testMigration",
        });

        builder.OwnsMany(y => y.Test, option =>
        {
            option.ToJson();

            option.HasData(new
            {
                DisabilityId = 1,
                Value = "someValue",
                Type = "someType",
            });
        });
    }
```

The exception thrown:

```
System.InvalidOperationException: The seed entity for entity type 'JsonTest' cannot be added because no value was provided for the required property 'Id'.
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateData(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal.SqlServerModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```
When you do add a value for this shadow primary key you get the following error, however.

Updated migration code:
```
public void Configure(EntityTypeBuilder<Disability> builder)
    {
        builder.ToTable("Disabilities");

        builder.HasData(new
        {
            Id = 1,
            Name = "testMigration",
        });

        builder.OwnsMany(y => y.Test, option =>
        {
            option.ToJson();

            option.HasData(new
            {
                Id = 1,
                DisabilityId = 1,
                Value = "someValue",
                Type = "someType",
            });
        });
    }
```
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.AddSeedData(IEntityType entityType, Dictionary`2 identityMaps, EntityState initialState)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.TrackData(IRelationalModel source, IRelationalModel target, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDataOperations(IRelationalModel source, IRelationalModel target, DiffContext diffContext)+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IRelationalModel source, IRelationalModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.
```

Really can't see if I am missing something here.

Provider and version information
EF Core version: EF Core 7.0.0-rc.1.22426.7
Database provider:Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET 7.0
Operating system: Windows 11
IDE:  Visual Studio 2022 Preview

**Comment by kbaley** [comment]
I'm having a similar problem with `InsertData` in a migration. Here's [a reproduction](https://github.com/kbaley/EFCore7JsonIssue). When I include a JSON column in an `InsertData` call, I get the following error with `dotnet ef database update --verbose`:

```
dotnet exec --depsfile /Users/kylebaley/Documents/workspace/code/EFCore7JsonIssue/bin/Debug/net6.0/EFGetStarted.deps.json --additionalprobingpath /Users/kylebaley/.nuget/packages --additionalprobingpath /usr/local/share/dotnet/sdk/NuGetFallbackFolder --runtimeconfig /Users/kylebaley/Documents/workspace/code/EFCore7JsonIssue/bin/Debug/net6.0/EFGetStarted.runtimeconfig.json /Users/kylebaley/.dotnet/tools/.store/dotnet-ef/7.0.0-rc.2.22472.11/dotnet-ef/7.0.0-rc.2.22472.11/tools/net6.0/any/tools/netcoreapp2.0/any/ef.dll database update --assembly /Users/kylebaley/Documents/workspace/code/EFCore7JsonIssue/bin/Debug/net6.0/EFGetStarted.dll --project /Users/kylebaley/Documents/workspace/code/EFCore7JsonIssue/EFGetStarted.csproj --startup-assembly /Users/kylebaley/Documents/workspace/code/EFCore7JsonIssue/bin/Debug/net6.0/EFGetStarted.dll --startup-project /Users/kylebaley/Documents/workspace/code/EFCore7JsonIssue/EFGetStarted.csproj --project-dir /Users/kylebaley/Documents/workspace/code/EFCore7JsonIssue/ --root-namespace EFGetStarted --language C# --framework net6.0 --nullable --working-dir /Users/kylebaley/Documents/workspace/code/EFCore7JsonIssue --verbose
Using assembly 'EFGetStarted'.
Using startup assembly 'EFGetStarted'.
Using application base '/Users/kylebaley/Documents/workspace/code/EFCore7JsonIssue/bin/Debug/net6.0'.
Using working directory '/Users/kylebaley/Documents/workspace/code/EFCore7JsonIssue'.
Using root namespace 'EFGetStarted'.
Using project directory '/Users/kylebaley/Documents/workspace/code/EFCore7JsonIssue/'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'EFGetStarted'...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'BloggingContext'.
Using context 'BloggingContext'.
Finding design-time services referenced by assembly 'EFGetStarted'...
Finding design-time services referenced by assembly 'EFGetStarted'...
No referenced design-time services were found.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding IDesignTimeServices implementations in assembly 'EFGetStarted'...
No design-time services were found.
Creating DbConnection.
Created DbConnection. (45ms).
Migrating using database 'Moo' on server 'localhost'.
Opening connection to database 'Moo' on server 'localhost'.
Opened connection to database 'Moo' on server 'localhost'.
Creating DbCommand for 'ExecuteNonQuery'.
Created DbCommand for 'ExecuteNonQuery' (3ms).
Initialized DbCommand for 'ExecuteNonQuery' (7ms).
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
Executed DbCommand (21ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
Closing connection to database 'Moo' on server 'localhost'.
Closed connection to database 'Moo' on server 'localhost' (3ms).
Creating DbCommand for 'ExecuteScalar'.
Created DbCommand for 'ExecuteScalar' (0ms).
Initialized DbCommand for 'ExecuteScalar' (0ms).
Opening connection to database 'Moo' on server 'localhost'.
Opened connection to database 'Moo' on server 'localhost'.
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Executed DbCommand (18ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Closing connection to database 'Moo' on server 'localhost'.
Closed connection to database 'Moo' on server 'localhost' (0ms).
Opening connection to database 'Moo' on server 'localhost'.
Opened connection to database 'Moo' on server 'localhost'.
Creating DbCommand for 'ExecuteNonQuery'.
Created DbCommand for 'ExecuteNonQuery' (0ms).
Initialized DbCommand for 'ExecuteNonQuery' (0ms).
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
Closing connection to database 'Moo' on server 'localhost'.
Closed connection to database 'Moo' on server 'localhost' (0ms).
Creating DbCommand for 'ExecuteScalar'.
Created DbCommand for 'ExecuteScalar' (0ms).
Initialized DbCommand for 'ExecuteScalar' (0ms).
Opening connection to database 'Moo' on server 'localhost'.
Opened connection to database 'Moo' on server 'localhost'.
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Closing connection to database 'Moo' on server 'localhost'.
Closed connection to database 'Moo' on server 'localhost' (0ms).
Creating DbCommand for 'ExecuteReader'.
Created DbCommand for 'ExecuteReader' (0ms).
Initialized DbCommand for 'ExecuteReader' (0ms).
Opening connection to database 'Moo' on server 'localhost'.
Opened connection to database 'Moo' on server 'localhost'.
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [MigrationId], [ProductVersion]
FROM [__EFMigrationsHistory]
ORDER BY [MigrationId];
Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [MigrationId], [ProductVersion]
FROM [__EFMigrationsHistory]
ORDER BY [MigrationId];
Closing data reader to 'Moo' on server 'localhost'.
A data reader for 'Moo' on server 'localhost' is being disposed after spending 1ms reading results.
Closing connection to database 'Moo' on server 'localhost'.
Closed connection to database 'Moo' on server 'localhost' (0ms).
Applying migration '20221105201416_Comment'.
'BloggingContext' disposed.
Disposing connection to database 'Moo' on server 'localhost'.
Disposed connection to database '' on server '' (0ms).
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.GetPropertyMappings(String[] names, String tableName, String schema, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.GenerateModificationCommands(InsertDataOperation operation, IModel model)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(InsertDataOperation operation, IModel model, MigrationCommandListBuilder builder, Boolean terminate)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__82_28(MigrationsSqlGenerator g, MigrationOperation o, IModel m, MigrationCommandListBuilder b)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass16_2.<GetMigrationCommandLists>b__2()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Sequence contains no elements```

### Include provider and version information

EF Core version: 7.0.0-rc.2.22472.11
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: MacOS Monterrey
IDE: VS Code
```

**Comment by wh1sp3r** [comment]
I have same problem with the json column seed.

if I add 
`builder.Entity<WorkNode>().OwnsOne(c => c.Configuration,  nav => nav.HasData(new { WorkNodeId = 6, IsPlanner = true, Line = Entities.Places.Enums.Line.ManualLine }));`

Migration says: 
`System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.AddSeedData(IEntityType entityType, Dictionary`2 identityMaps, EntityState initialState)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.TrackData(IRelationalModel source, IRelationalModel target, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDataOperations(IRelationalModel source, IRelationalModel target, DiffContext diffContext)+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IRelationalModel source, IRelationalModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.`

I just need to seed the Json object, what should I do?

**Comment by Dzivo** [comment]
@kbaley i am having the same problem have you been able to find a solution ?

**Comment by kbaley** [comment]
@Dzivo I wasn't involved past the initial investigation but I believe the ultimate solution was to deserialize the data to strings and insert it into the tables with direct SQL

**Comment by Dzivo** [comment]
@kbaley that is ok but I am still getting "Sequence contains no elements" when trying to create basic `  ownedNavigationBuilder.ToJson();` mapping. I still cannot reproduce this in basic project when I remove hasData in the basic project problem is fixed. As a workaround i will use valueConverter for now but I think some more work on this needs to be done this is a basic example it is not working out of the box maybe in the simplest of projects but ours really big.

**Comment by Dzivo** [comment]
> @Dzivo I wasn't involved past the initial investigation but I believe the ultimate solution was to deserialize the data to strings and insert it into the tables with direct SQL

@kbaley good solution for now but that means i use HasData to seed other columns in my data and that i have to do everything manually for each table that has json columns

**Comment by SSlinky** [comment]
I'm having the same issue trying to seed with `.HasData()`.

```{ .c-sharp }
public void Configure(EntityTypeBuilder<MyDataModel> builder)
    {
        builder.OwnsMany(e => e.MyListPoco, ownedNavigationBuilder =>
        {
            ownedNavigationBuilder.ToJson();
        });
    }
```

The table is created as you'd expect with a field called MyListPoco of type nvarchar(max). I've tried the following:

``` { .c-sharp }
// On MyDataModel as an object.
builder.HasData( new { Key = 1, MyListPoco = new List<Foo> { new() { bar = 1, baz = "test" }});

// On MyDataModel as a string
builder.HasData( new { Key = 1, MyListPoco = "{\"bar\": 1, \"baz\": \"test\"}" });

// In a config of its own
builder.HasData( new { bar = 1, baz = "test",  MyDataModelKey = 1 });
```

Just for fun, I also tried adding Foo as a DbSet but no luck anywhere.

**Comment by ivanpolish5** [comment]
I think 8.0 is way to long to wait for a critical error fix but hey thats just me

**Comment by navjotminhas-triparc** [comment]
Facing the same issue. +1

**Comment by DominikTher** [comment]
I'm having the same issue. It works if the column is not in JSON. But I would like to use JSON.

**Comment by 1002527441** [comment]
same issue I met,  once you used a json column in a table, then you can not seed data any more on EFcore 7.

**Comment by blanks88** [comment]
With `Microsoft.EntityFrameworkCore 7.0.10` I am getting this error:
```c#
public class Person
{
    public string FirstName { get; set; }
    public string LastName { get; set; }

    [Column(TypeName = "jsonb")] 
    public List<Contact> Contacts { get; set; } = new();
}

public class Contact
{
    public string Type { get; set; }
    public string ValueType { get; set; }
    public string Value { get; set; } = null!;
}
```


```shell
System.InvalidOperationException: Cannot scaffold C# literals of type 'Contact'. The provider should implement CoreTypeMapping.GenerateCodeLiteral to support using it at design time.
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.UnknownLiteral(Object value)
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.<>c__DisplayClass39_0.<List>b__0(Object value)
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.HandleEnumerable(IndentedStringBuilder builder, Boolean vertical, IEnumerable values, Action`1 handleValue)
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.List(Type type, IEnumerable values, Boolean vertical)
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.UnknownLiteral(Object value)
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.Literal(Object[,] values)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationOperationGenerator.Generate(InsertDataOperation operation, IndentedStringBuilder builder)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationOperationGenerator.Generate(String builderName, IReadOnlyList`1 operations, IndentedStringBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationsGenerator.GenerateMigration(String migrationNamespace, String migrationName, IReadOnlyList`1 upOperations, IReadOnlyList`1 downOperations)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Cannot scaffold C# literals of type 'Contact'. The provider should implement CoreTypeMapping.GenerateCodeLiteral to support using it at design time.

```

**Comment by ajcvickers** [comment]
Note from triage: throw a better message in 8.

**Comment by flostellbrink** [comment]
Are there any plans on actually supporting HasData for JSON columns?
Was kinda hoping for a bit more than a different error message here.
