### ISSUE TITLE
SqlNullabilityProcessor throwing NullReferenceException on one server in cluster

### ISSUE THREAD

**Issue by davidkeaveny** [dotnet/efcore#29340]
I have a bug that I am seeing in production that is proving to be really hard to track down. I am running an ASP.NET Core 6 API with EF Core 6, hosted in AWS ECS and querying a SQL Server 2019 database running on AWS RDS. The application is a single database multi-tenanted design, and I use a global filter on the appropriate tables to ensure that the DbContext only interacts with records that have the appropriate tenant ID, which is retrieved from a custom claim in a JWT provided by OAuth (this means that my DbContext is registered with the Scoped lifetime, since each request will require a new instance with the correct tenant ID).

Everything is fine after application startup, until after a while (usually at least a few hours), I start to see `500 Internal Server Error` responses coming back from the API. This occurs not just on one single API endpoint, but any API endpoint. The underlying exception is a `NullReferenceException` being thrown by EF's `SqlNullabilityProcessor`:

```
Object reference not set to an instance of an object.
System.NullReferenceException
at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.<VisitIn>g__ProcessInExpressionValues|29_0(SqlExpression valuesExpression, Boolean extractNullValues)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.VisitIn(InExpression inExpression, Boolean allowOptimizedExpansion, Boolean& nullable)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.Visit(SqlExpression sqlExpression, Boolean allowOptimizedExpansion, Boolean preserveColumnNullabilityInformation, Boolean& nullable)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.VisitSqlBinary(SqlBinaryExpression sqlBinaryExpression, Boolean allowOptimizedExpansion, Boolean& nullable)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.Visit(SqlExpression sqlExpression, Boolean allowOptimizedExpansion, Boolean preserveColumnNullabilityInformation, Boolean& nullable)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.Visit(SelectExpression selectExpression)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.Process(SelectExpression selectExpression, IReadOnlyDictionary`2 parameterValues, Boolean& canCache)
   at Microsoft.EntityFrameworkCore.Query.RelationalParameterBasedSqlProcessor.Optimize(SelectExpression selectExpression, IReadOnlyDictionary`2 parametersValues, Boolean& canCache)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerParameterBasedSqlProcessor.Optimize(SelectExpression selectExpression, IReadOnlyDictionary`2 parametersValues, Boolean& canCache)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalCommandCache.GetRelationalCommandTemplate(IReadOnlyDictionary`2 parameters)
   at Microsoft.EntityFrameworkCore.Internal.RelationCommandCacheExtensions.RentAndPopulateRelationalCommand(RelationalCommandCache relationalCommandCache, RelationalQueryContext queryContext)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at MyApi.Data.Stores.ClientsSqlDataStore.Select(Specification`1 specification, CancellationToken cancellationToken) in /src/MyApi.Data/Stores/ClientsSqlDataStore.cs:line 47
   at MyApi.Core.QueryHandlers.ClientsBySearchQueryHandler.Handle(ClientsBySearchQuery query, CancellationToken cancellationToken) in /src/MyApi.Core/QueryHandlers/ClientsBySearchQueryHandler.cs:line 71
   at MyApi.Core.Cqrs.Decorators.LoggingQueryHandlerDecorator`2.Handle(TQuery query, CancellationToken cancellationToken) in /src/MyApi.Core/Cqrs/Decorators/LoggingQueryHandlerDecorator.cs:line 74
   at MyApi.Core.Cqrs.CqrsDispatcher.Query[TResult](IQuery`1 query, CancellationToken cancellationToken) in /src/MyApi.Core/Cqrs/CqrsDispatcher.cs:line 47
   at MyApi.Application.Controllers.CqrsApiController.Query[TResult](IQuery`1 query, CancellationToken cancellationToken) in /src/MyApi.Application/Controllers/CqrsApiController.cs:line 55
   at MyApi.Application.Controllers.ClientsController.GetClients(ClientsBySearchQuery query, CancellationToken cancellationToken) in /src/MyApi.Application/Controllers/ClientsController.cs:line 46
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

If I copy the failing request and replay it when running locally, the error does not occur. Observation has also led to the conclusion that it is always only one container instance in the AWS ECS service that fails - i.e. if I have 8 tasks running, then if I run the same query 8 times, I will get 7 successes and 1 failure. If I add another 8 tasks to the service, I will get 15 successes and 1 failure. The load balancer is configured with a round-robin strategy, so it will always be predictable when the next failure will occur, once the first failure has occurred (remember it is not manifested immediately).

So far, the only solution has been to redeploy the service - same image, just blow away the current tasks and deploy new ones.

Can anyone think of any reason why this would happen? It's happening on any query that uses a global filter.

### Implementation

The multi-tenancy by global filter is implemented as:

```
public class MultiTenantedDbContext : DbContext
{
    private readonly string _tenantId;
    
    public MultiTenantedDbContext(DbContextOptions<MultiTenantedDbContext> options, ClaimsPrincipal principal) : base(options)
    {
        _tenantId = principal.FindFirstValue("http://myproject/tenantId") ?? string.Empty;
    }
    
    public DbSet<Client> Clients { get; set; }
    public DbSet<PayrollEventRequest> PayrollEvents { get; set; }
    
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfigurationsFromAssembly(GetType().Assembly);
        modelBuilder.Entity<Client>().HasQueryFilter(t => t.TenantId == _tenantId);
    }
}

public class Client
{
  public int Id { get; set; }
  public string Name { get; set; }
  public string TenantId { get; set; }
}

public class PayrollEventRequest
{
  public int Id { get; set; }
  public DateTimeOffset Executed { get; set; }
  public Client Client { get; set; }
  public int ClientId { get; set; }
}
```

`Client` is a navigation property on `PayrollEventRequest`, and EF is quite happy to apply the query filter to `_dbContext.PayrollEvents` queries.

### Provider and version information

EF Core version: 6.0.9
Database provider: Microsoft.EntityFrameworkCore.SqlServer
SQL Server version: 15.0.4073.23
Target framework: .NET 6.0.9
Image base: mcr.microsoft.com/dotnet/aspnet:6.0
IDE: Rider 2022.2.3

**Comment by ajcvickers** [comment]
@davidkeaveny From the stack trace, it looks like this is happening when a `Contains` query is being executed on a null `_tenantId`.

**Comment by davidkeaveny** [comment]
@ajcvickers thanks for your response. It certainly feels like that should be the case; however there are two things working against that hypothesis:

1. if I replay a failed API call in Postman just by hitting the Send button again, then the next call will pass, and the next, until the load balancer sends the call back to the one failing instance;
2. we use an `IAuthorizationRequirement` to ensure that the value passed to `_tenantId` is present in the JWT (and to fail with a 401 if not)

Are you aware of any other instrumentation that I can attach to EF to get more information as to what's causing it to throw a NullReferenceException?

**Comment by smitpatel** [comment]
Verify that all the query filters defined in the model are not calling `Contains` method over something which could be null at any point.

**Comment by davidkeaveny** [comment]
I've yet to find any such queries; but the puzzling fact still remains that if I repeat the _exact_ same API call (i.e. create a cURL request and then just repeat it on a loop), it will pass every time until it hits a particular container instance then it will fail, then subsequent calls will pass again until the round-robin load balancer strategy hits that container instance again. So if I have four containers in my deployment, I will get a pattern of pass-pass-pass-fail-pass-pass-pass-fail.

That to me suggests that it's not anything specific in the query itself, otherwise it would fail every time.

**Comment by ajcvickers** [comment]
@davidkeaveny Note that the context having a null `_tenantId` is not specific to the query, but rather associated with a given context instance, which in turn could easily be related to the environment on the container that fails.

**Comment by davidkeaveny** [comment]
@ajcvickers surely `_tenantId` will never be null, regardless of the context, because a) this is a .NET 6 application and `_tenantId` is defined as `string` rather than `string?`, and b) its value is set with a null-coalescing operation so that even if the principal does not contain the expected claim (or the claim exists but with a null value) then it will be set to `string.Empty` instead?

**Comment by ajcvickers** [comment]
@smitpatel My understand (@smitpatel correct me if I am wrong) is that the stack trace indicates that `Contains` is being called on something that is null. That's all we have to go right now without being able to reproduce this ourselves.
