### ISSUE TITLE
Database already exists error with localdb when Running uniitests

### ISSUE THREAD

**Issue by JanEggers** [dotnet/efcore#29354]
## File a bug

Im having touble with my tests running on the buildserver. the same tests are running fine locally. I use localdb for my tests. so I assume something is wrong with my environment. but anyway how is it possible that im not able to call EnsureCreated after calling EnsureDeleted? 

Is there any way to generate more debug output why ef thinks the db does not exist / does not have to be deleted but still is there?

Every tests tries to cleanup the database in its initialization but since yesterday for some reason every test fails on my buildsystem. (was running fine for weeks)

### Include your code

```C#

new DbContextOptionsBuilderDbContext>()
                .UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=db;Trusted_Connection=True;MultipleActiveResultSets=true", sql => sql.EnableRetryOnFailure())

                    _outputHelper.WriteLine("before delete");
                    var result = ctx.Database.EnsureDeleted();
                    _outputHelper.WriteLine($"after delete {result}");
                    result = ctx.Database.EnsureCreated();
                    _outputHelper.WriteLine($"after create {result}");
```

sometimes i get 
```
 [2022-10-14 08:47:25Z] info: Syf.Entities.UnitTest.SqlServerDbContextFactory[0]
       before delete
 [2022-10-14 08:47:25Z] info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
       Entity Framework Core 6.0.8 initialized 'SkyFallDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer:6.0.8' with options: None
 [2022-10-14 08:47:25Z] info: Syf.Entities.UnitTest.SqlServerDbContextFactory[0]
       after delete False
 [2022-10-14 08:47:25Z] fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
       Failed executing DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
       CREATE DATABASE [Skyfalldb];
Microsoft.Data.SqlClient.SqlException : Database 'db' already exists. Choose a different database name.
at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Create()
at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
```

sometimes i get 
```
 [2022-10-14 08:47:20Z] info: Syf.Entities.UnitTest.SqlServerDbContextFactory[0]
       before delete
 [2022-10-14 08:47:21Z] info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
       Entity Framework Core 6.0.8 initialized 'SkyFallDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer:6.0.8' with options: None
 [2022-10-14 08:47:21Z] info: Microsoft.EntityFrameworkCore.Database.Command[20101]
       Executed DbCommand (42ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
       SELECT 1
 [2022-10-14 08:47:24Z] info: Microsoft.EntityFrameworkCore.Database.Command[20101]
       Executed DbCommand (3,015ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
       IF SERVERPROPERTY('EngineEdition') <> 5
       BEGIN
           ALTER DATABASE [Skyfalldb] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
       END;
 [2022-10-14 08:47:25Z] info: Microsoft.EntityFrameworkCore.Database.Command[20101]
       Executed DbCommand (22ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
       DROP DATABASE [Skyfalldb];
 [2022-10-14 08:47:25Z] info: Syf.Entities.UnitTest.SqlServerDbContextFactory[0]
       after delete True
 [2022-10-14 08:47:25Z] fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
       Failed executing DbCommand (135ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
       CREATE DATABASE [Skyfalldb];
Microsoft.Data.SqlClient.SqlException : Database 'db' already exists. Choose a different database name.
at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Create()
at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
```

### Include provider and version information

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 6.0)
Operating system:
IDE: (e.g. Visual Studio 2022)

**Comment by ajcvickers** [comment]
@JanEggers A few things:

If you can, don't use localdb. It's known to be flaky, especially around dropping and creating databases. (My suspicion is that it's the name-pipes communication which is flaky.) SQL Server Developer edition is more reliable.

Even when not using localdb, there can still be reliability issues with SQL Server/SqlClient when creating and deleting databases frequently--SQL Server just isn't built for this. Consider using an execution strategy to do automatic re-tries. For example, see https://github.com/dotnet/efcore/blob/main/test/EFCore.Specification.Tests/TestUtilities/DatabaseFacadeExtensions.cs

Finally, consider cleaning and re-using a database rather than dropping it and re-creating it. This is generally much faster as well as being more reliable. See https://learn.microsoft.com/en-us/ef/core/testing/testing-with-the-database#efficient-database-creation for some guidance.

**Comment by JanEggers** [comment]
thx for the advice i added respawn to clear db and now it is less shaky

**Comment by JanEggers** [comment]
for anyone stumbling over this I found more details.

1. make sure you call dotnet test with -m=1 otherwise multiple testprojects will be executed in parallel resulting in issues if they use the same localdb for testing

2. EnsureDeletedAsync seems not reliable so i created my own version of it:

```csharp
 public static async Task DeleteDatabaseForReal(this DbContext ctx)
        {
            var connectionString = ctx.Database.GetConnectionString();
            var connectionStringBuilder = new SqlConnectionStringBuilder(connectionString);

            var dbName = connectionStringBuilder.InitialCatalog;

            connectionStringBuilder.InitialCatalog = "master";

            using var masterConn = new SqlConnection(connectionStringBuilder.ConnectionString);

            await masterConn.OpenAsync();

            using var cmd1 = masterConn.CreateCommand();
            cmd1.CommandText = "select * from sysdatabases";
            var reader = await cmd1.ExecuteReaderAsync();
            var dt = new DataTable();
            dt.Load(reader);
            if (dt.Rows.OfType<DataRow>().All(x => x["name"].ToString() != dbName))
            {
                return;
            }

            using var cmd2 = masterConn.CreateCommand();
            cmd2.CommandText = $" drop database {dbName}";
            await cmd2.ExecuteNonQueryAsync();
        }
```

**Comment by roji** [comment]
@JanEggers you should ideally not reduce test parallalism, but rather use different databases via different test fixtures; this allows test to run in parallel, which makes them much, much faster. This is covered on [this page of the docs](https://learn.microsoft.com/en-us/ef/core/testing/testing-with-the-database).
