### ISSUE TITLE
Cannot run `dotnet ef migrations script --no-build` simultaneously.

### ISSUE THREAD

**Issue by foriequal0** [dotnet/efcore#29352]
## File a bug

I generate migrations for all DbContexts in CI, so I've tried to generate them concurrently to reduce total time.

### Include your code
You have a DbContext A, B, C, D in a project X. Then run the following code

```shell
dotnet build

mkdir migrations/X
for CONTEXT in A B C D
do
  dotnet ef migrations script \
    --project X --context "$CONTEXT" \
    --output "migrations/X/$CONTEXT.sql" \
    --no-build &
done

wait
```

### Include stack traces

Sometimes it succeed, sometimes it fails without any error message, sometimes it emits a following 
```
System.IO.IOException: The process cannot access the file '<solution-path>/X/obj/X.csproj.EntityFrameworkCore.targets' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.OpenWrite(String path)
   at Microsoft.EntityFrameworkCore.Tools.Project.FromFile(String file, String buildExtensionsDir, String framework, String configuration, String runtime)
   at Microsoft.EntityFrameworkCore.Tools.RootCommand.Execute(String[] _)
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0(String[] args)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
The process cannot access the file '<solution-path>/X/obj/X.csproj.EntityFrameworkCore.targets' because it is being used by another process.
```

### Include provider and version information

EF Core version: 6.0.5
Database provider: (e.g. Npgsql)
Target framework: (e.g. .NET 6.0)
Operating system: Ubuntu-22.04
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment]
Executing the commands concurrently is not supported.
