### ISSUE TITLE
No migration possible on EFCore 3.1 for .Net Framework 4.8

### ISSUE THREAD

**Issue by T1m0th33** [dotnet/efcore#29382]
Hello,

I am using the latest version of EFCore compatible with .Net Standard 2.0 (the version 3.1.30) as my project is using the .Net Framework 4.8.
When adding a migration to my project, I am getting the following error message:
```
System.MissingMethodException: Constructor on type 'Microsoft.EntityFrameworkCore.Design.OperationExecutor' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at Microsoft.EntityFrameworkCore.Tools.AppDomainOperationExecutor..ctor(String assembly, String startupAssembly, String projectDir, String dataDirectory, String rootNamespace, String language)
   at Microsoft.EntityFrameworkCore.Tools.Commands.ProjectCommandBase.CreateExecutor()
   at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsAddCommand.Execute()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Constructor on type 'Microsoft.EntityFrameworkCore.Design.OperationExecutor' not found.
```
This looks similar to the issue describe [here](https://github.com/dotnet/efcore/issues/16074#issuecomment-501841284), in the version 3.0.0 and which has been fixed in this version.

**Comment by ajcvickers** [comment]
@T1m0th33 Please post your csproj file and the `--verbose` output from running the command.

**Comment by T1m0th33** [comment]
[ConsoleApp1.zip](https://github.com/dotnet/efcore/files/9808686/ConsoleApp1.zip)
In the package manager, execute the command line `dotnet ef  migrations add xxx --project ConsoleApp1` to get the error mentioned.

**Comment by roji** [comment]
@T1m0th33 can you also please post the output of `dotnet tool list -g`?

**Comment by T1m0th33** [comment]
```
PM> dotnet tool list -g
Package Id      Version      Commands 
--------------------------------------
dotnet-ef       3.0.0        dotnet-ef
```

**Comment by roji** [comment]
To be on the safe side, can you try upgrading your dotnet-ef tool to the latest 3.1.30, so that it corresponds with the version of EF you're using?

**Comment by T1m0th33** [comment]
@roji, it seems to work, thanks.
```
PM> dotnet tool update -g dotnet-ef --version 3.1.30
Tool 'dotnet-ef' was successfully updated from version '3.0.0' to version '3.1.30'.
PM> dotnet ef migrations add xxx --project ConsoleApp1
Build started...
Build succeeded.
```
