### ISSUE TITLE
Does InsertData work in migrations with JSON columns?

### ISSUE THREAD

**Issue by kbaley** [dotnet/efcore#29487]
I'm trying to insert some data into a table during a migration but it fails when I include a JSON column in the list of columns to insert. When I exclude the column (assuming the column is nullable), it works. I've tried inserting both a JSON string and a domain object with the same result.

This is on SQL Server. I haven't tried other databases.

### Include your code

Reproduction here: https://github.com/kbaley/EFCore7JsonIssue

Error occurs with `dotnet ef database update`

### Include stack traces

```
Applying migration '20221105201416_Comment'.
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.GetPropertyMappings(String[] names, String tableName, String schema, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.GenerateModificationCommands(InsertDataOperation operation, IModel model)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(InsertDataOperation operation, IModel model, MigrationCommandListBuilder builder, Boolean terminate)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__82_28(MigrationsSqlGenerator g, MigrationOperation o, IModel m, MigrationCommandListBuilder b)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass16_2.<GetMigrationCommandLists>b__2()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Sequence contains no elements
```

### Include verbose output

```
dotnet exec --depsfile /Users/kylebaley/Documents/workspace/code/EFCore7JsonIssue/bin/Debug/net6.0/EFGetStarted.deps.json --additionalprobingpath /Users/kylebaley/.nuget/packages --additionalprobingpath /usr/local/share/dotnet/sdk/NuGetFallbackFolder --runtimeconfig /Users/kylebaley/Documents/workspace/code/EFCore7JsonIssue/bin/Debug/net6.0/EFGetStarted.runtimeconfig.json /Users/kylebaley/.dotnet/tools/.store/dotnet-ef/7.0.0-rc.2.22472.11/dotnet-ef/7.0.0-rc.2.22472.11/tools/net6.0/any/tools/netcoreapp2.0/any/ef.dll database update --assembly /Users/kylebaley/Documents/workspace/code/EFCore7JsonIssue/bin/Debug/net6.0/EFGetStarted.dll --project /Users/kylebaley/Documents/workspace/code/EFCore7JsonIssue/EFGetStarted.csproj --startup-assembly /Users/kylebaley/Documents/workspace/code/EFCore7JsonIssue/bin/Debug/net6.0/EFGetStarted.dll --startup-project /Users/kylebaley/Documents/workspace/code/EFCore7JsonIssue/EFGetStarted.csproj --project-dir /Users/kylebaley/Documents/workspace/code/EFCore7JsonIssue/ --root-namespace EFGetStarted --language C# --framework net6.0 --nullable --working-dir /Users/kylebaley/Documents/workspace/code/EFCore7JsonIssue --verbose
Using assembly 'EFGetStarted'.
Using startup assembly 'EFGetStarted'.
Using application base '/Users/kylebaley/Documents/workspace/code/EFCore7JsonIssue/bin/Debug/net6.0'.
Using working directory '/Users/kylebaley/Documents/workspace/code/EFCore7JsonIssue'.
Using root namespace 'EFGetStarted'.
Using project directory '/Users/kylebaley/Documents/workspace/code/EFCore7JsonIssue/'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'EFGetStarted'...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'BloggingContext'.
Using context 'BloggingContext'.
Finding design-time services referenced by assembly 'EFGetStarted'...
Finding design-time services referenced by assembly 'EFGetStarted'...
No referenced design-time services were found.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding IDesignTimeServices implementations in assembly 'EFGetStarted'...
No design-time services were found.
Creating DbConnection.
Created DbConnection. (45ms).
Migrating using database 'Moo' on server 'localhost'.
Opening connection to database 'Moo' on server 'localhost'.
Opened connection to database 'Moo' on server 'localhost'.
Creating DbCommand for 'ExecuteNonQuery'.
Created DbCommand for 'ExecuteNonQuery' (3ms).
Initialized DbCommand for 'ExecuteNonQuery' (7ms).
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
Executed DbCommand (21ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
Closing connection to database 'Moo' on server 'localhost'.
Closed connection to database 'Moo' on server 'localhost' (3ms).
Creating DbCommand for 'ExecuteScalar'.
Created DbCommand for 'ExecuteScalar' (0ms).
Initialized DbCommand for 'ExecuteScalar' (0ms).
Opening connection to database 'Moo' on server 'localhost'.
Opened connection to database 'Moo' on server 'localhost'.
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Executed DbCommand (18ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Closing connection to database 'Moo' on server 'localhost'.
Closed connection to database 'Moo' on server 'localhost' (0ms).
Opening connection to database 'Moo' on server 'localhost'.
Opened connection to database 'Moo' on server 'localhost'.
Creating DbCommand for 'ExecuteNonQuery'.
Created DbCommand for 'ExecuteNonQuery' (0ms).
Initialized DbCommand for 'ExecuteNonQuery' (0ms).
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
Closing connection to database 'Moo' on server 'localhost'.
Closed connection to database 'Moo' on server 'localhost' (0ms).
Creating DbCommand for 'ExecuteScalar'.
Created DbCommand for 'ExecuteScalar' (0ms).
Initialized DbCommand for 'ExecuteScalar' (0ms).
Opening connection to database 'Moo' on server 'localhost'.
Opened connection to database 'Moo' on server 'localhost'.
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Closing connection to database 'Moo' on server 'localhost'.
Closed connection to database 'Moo' on server 'localhost' (0ms).
Creating DbCommand for 'ExecuteReader'.
Created DbCommand for 'ExecuteReader' (0ms).
Initialized DbCommand for 'ExecuteReader' (0ms).
Opening connection to database 'Moo' on server 'localhost'.
Opened connection to database 'Moo' on server 'localhost'.
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [MigrationId], [ProductVersion]
FROM [__EFMigrationsHistory]
ORDER BY [MigrationId];
Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [MigrationId], [ProductVersion]
FROM [__EFMigrationsHistory]
ORDER BY [MigrationId];
Closing data reader to 'Moo' on server 'localhost'.
A data reader for 'Moo' on server 'localhost' is being disposed after spending 1ms reading results.
Closing connection to database 'Moo' on server 'localhost'.
Closed connection to database 'Moo' on server 'localhost' (0ms).
Applying migration '20221105201416_Comment'.
'BloggingContext' disposed.
Disposing connection to database 'Moo' on server 'localhost'.
Disposed connection to database '' on server '' (0ms).
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.GetPropertyMappings(String[] names, String tableName, String schema, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.GenerateModificationCommands(InsertDataOperation operation, IModel model)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(InsertDataOperation operation, IModel model, MigrationCommandListBuilder builder, Boolean terminate)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__82_28(MigrationsSqlGenerator g, MigrationOperation o, IModel m, MigrationCommandListBuilder b)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass16_2.<GetMigrationCommandLists>b__2()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Sequence contains no elements```

### Include provider and version information

EF Core version: 7.0.0-rc.2.22472.11
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: MacOS Monterrey
IDE: VS Code

**Comment by ajcvickers** [comment]
Duplicate of #29297.

**Comment by kbaley** [comment]
Agreed. I'll add a comment there
