### ISSUE TITLE
ManyToMany not working if the joint entity is explicitly set

### ISSUE THREAD

**Issue by YeskaNova** [dotnet/efcore#29493]
I want to have a many-to-many relationship while setting explicitly the joint entity because I can have many ManyToMany properties of the same type and each should be on a different jointEntity ( different table ). This does not work even if it seems to be a simple use case.

### Include your code

```C#
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Reflection.Emit;
using System.Security.Cryptography.X509Certificates;

public class User
{
    public int Id { get; set; }
    public IList<Article> Articles { get; set; }
}


public class Article
{
    public int Id { get; set; }
    public IList<User> Users { get; set; }
}

public class UserArticle
{
    public int Id { get; set; }
    public User User { get; set; }
    public Article Article { get; set; }
}
public class UserArticleLegacy
{
    public int Id { get; set; }
    public User User { get; set; }
    public Article Article { get; set; }
}


public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions options) : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Article>();
        modelBuilder.Entity<User>()
            .HasMany(x => x.Articles)
            .WithMany(x => x.Users)
            .UsingEntity<UserArticle>();
    }
}

class Program
{
    static void Main(string[] args)
    {
        var sc = new ServiceCollection();
        var guid = Guid.NewGuid();
        sc.AddDbContext<AppDbContext>(op => op.UseSqlServer(@"Server=(localdb)\MSSQLLocalDB;Integrated Security=true;DataBase=" + guid));
        using (var provider = sc.BuildServiceProvider())
        {
            using (var scope = provider.CreateScope())
            using (var dbcontext = scope.ServiceProvider.GetService<AppDbContext>())
            {
                dbcontext.Database.EnsureCreated();
            }

            using (var scope = provider.CreateScope())
            using (var dbcontext = scope.ServiceProvider.GetService<AppDbContext>())
            {
                dbcontext.Add(new User() { Articles = new List<Article>() { new Article() } });
                dbcontext.SaveChanges();
            }
        }

    }
}
```
### Include stack traces

```
Introducing FOREIGN KEY constraint 'FK_UserArticle_Article_ArticlesId' on table 'UserArticle' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.
Could not create constraint or index. See previous errors.

   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.CreateTables()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
```

### Include provider and version information

EF Core version: 7.0.0-rc.2.22472.11
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET 7.0
Operating system: Win10
IDE: Visual Studio 2022

**Comment by ajcvickers** [comment]
@YeskaNova The code you posted does not generate the exception shown. Are you missing configuration of the second many-to-many relationship?

**Comment by YeskaNova** [comment]
It's the exception I'm having on my environment:

![image](https://user-images.githubusercontent.com/4983925/200375807-f6ec5d63-7a35-4ec6-bec5-c0082ad212ee.png)

**Comment by ajcvickers** [comment]
I'm running exactly the code you posted and it doesn't throw for me.

**Comment by YeskaNova** [comment]
Hi @ajcvickers , you can try it here https://dotnetfiddle.net/m2l0X3 
( if it times out, please give it a second try )

![image](https://user-images.githubusercontent.com/4983925/200380951-1851d295-6281-49fe-b334-a2144d58dea8.png)

**Comment by ajcvickers** [comment]
@YeskaNova The difference was I didn't have NRTs enabled. I am able to reproduce now. The navigation properties in the `UserArticle` need to be configured as part of the same many-to-many relationship that is used by the skip navigations. For example:

```C#
modelBuilder.Entity<User>()
    .HasMany(x => x.Articles)
    .WithMany(x => x.Users)
    .UsingEntity<UserArticle>(
        b => b.HasOne(e => e.Article).WithMany(),
        b => b.HasOne(e => e.User).WithMany());
```

Without this they are configured as separate, independent relationships, just like any other navigation properties would be.

**Comment by YeskaNova** [comment]
Awsome, thank you!
