### ISSUE TITLE
SQLite: Exception when using enum on entity

### ISSUE THREAD

**Issue by StringEpsilon** [dotnet/efcore#29521]
## File a bug

When upgrading to efcore 7, the SQLite Database provider fails to save entities with enums. Instead, an Exception of type "System.InvalidOperationException" with a message like this is thrown: ` The binary operator Equal is not defined for the types 'System.Int64' and 'Profession'.`.

 This is breaking one of my projects where I relied on int64 <-> Enum mapping for quite a few entities. 

I have verified that the issue is not reproducible with Microsoft.EntityFrameworkCore.Sqlite version 6.0.10.
I have also verified that the issue is not present when using the InMemory Database provider (Microsoft.EntityFrameworkCore.InMemory, version 7.0.0).

### Include your code
A full reproduction code can be found here:

https://github.com/StringEpsilon/efcore_regression/tree/main 

I also have added branches that show that the issue does not exist on version 6.0.10 (https://github.com/StringEpsilon/efcore_regression/tree/efcore_6)  and the InMemory provider (https://github.com/StringEpsilon/efcore_regression/tree/memory-db) 

Minimal reproduction:

```cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

var dbContext = new TestContext();
dbContext.Database.EnsureCreated();

dbContext.Accounts.Add(new Account() { Profession = Profession.None});
dbContext.SaveChanges();

public partial class TestContext : DbContext
{
	public virtual DbSet<Account> Accounts { get; set; }

	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	{
		optionsBuilder.UseSqlite($"Data Source=test.db");
	}

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<Account>(entity =>
		{
			entity.Property(e => e.Profession)
				.HasColumnType("integer")
				.HasColumnName("profession")
				.HasDefaultValueSql("'0'");
		}
		);
	}
}

public enum Profession : long {
	None = 0,
	GUARD = 1,
}

[Table("accounts")]
public partial class Account {
	[Key]
	[Column("id", TypeName = "integer")]
	public long Id { get; set; }

	public Profession Profession { get; set; }
}
```

### Include stack traces

```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: The binary operator Equal is not defined for the types 'System.Int64' and 'Profession'.
   at System.Linq.Expressions.Expression.GetEqualityComparisonOperator(ExpressionType binaryType, String opName, Expression left, Expression right, Boolean liftToNull)
   at System.Linq.Expressions.Expression.Equal(Expression left, Expression right, Boolean liftToNull, MethodInfo method)
   at Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer.DefaultValueComparer`1.ExtractEqualsBody(Expression leftExpression, Expression rightExpression)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyAccessorsFactory.CreateCurrentValueGetter[TProperty](IPropertyBase propertyBase, Boolean useStoreGeneratedValues)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyAccessorsFactory.CreateGeneric[TProperty](IPropertyBase propertyBase)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyAccessorsFactory.Create(IPropertyBase propertyBase)
   at Microsoft.EntityFrameworkCore.Metadata.RuntimePropertyBase.<>c.<Microsoft.EntityFrameworkCore.Metadata.Internal.IRuntimePropertyBase.get_Accessors>b__29_0(RuntimePropertyBase property)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Metadata.RuntimePropertyBase.Microsoft.EntityFrameworkCore.Metadata.Internal.IRuntimePropertyBase.get_Accessors()
   at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyBaseExtensions.GetPropertyAccessors(IPropertyBase propertyBase)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.GetCurrentValue[TProperty](IPropertyBase propertyBase)
   at lambda_method18(Closure, InternalEntityEntry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.OriginalValues..ctor(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntrySubscriber.SnapshotAndSubscribe(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
lbackState)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
nknownKey)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Add(TEntity entity)
```

### Include version information

Microsoft.Data.Sqlite version: `7.0.0`
Target framework:  `net7.0`
Operating system: Windows 10

**Comment by ajcvickers** [comment]
It's a bug; it should not make a difference.
