### ISSUE TITLE
EF Core 7 no longer logs errors from database commands

### ISSUE THREAD

**Issue by mattjohnsonpint** [dotnet/efcore#29543]
When using Microsoft.Extensions.Logging in EF Core 6 (per [docs](https://learn.microsoft.com/ef/core/logging-events-diagnostics/extensions-logging)), an error in the database command will be logged with the logging category `Microsoft.EntityFrameworkCore.Database.Command[20102]` which includes the query that caused the error.  An aggregate exception is also logged under `Microsoft.EntityFrameworkCore.Update[10000]`, but it doesn't send the offending query to the logger.  This is working fine with EF Core 6.

After upgrading to EF Core 7, `Microsoft.EntityFrameworkCore.Database.Command[20102]` failures are no longer logged.  Only the ` `Microsoft.EntityFrameworkCore.Update[10000]` failures appear in the log output.

### Full Reproduction

- On a Windows machine, install the latest .NET 6 and .NET 7 SDKs
- Clone the repository at: https://github.com/mattjohnsonpint/ef7-logging-issue-repro
- Run `dotnet run -f net6.0` to see the log output when running on .NET 6 with EF Core 6
- Run `dotnet run -f net7.0` to see the log output when running on .NET 7 with EF Core 7

This app creates a new SQL LocalDB instance when it is run.  It adds a table with an entity that has a unique index.  It adds an item to the table, then violates the index by adding another item with the same name.  That should be in the logs.

On the EF Core 6 version, you will see in the logs:
```
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (2ms) [Parameters=[@p0='Value' (Nullable = false) (Size = 450)], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [TestEntities] ([Property])
      VALUES (@p0);
      SELECT [Id]
      FROM [TestEntities]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
```

That entry is missing from the EF Core 7 version.

This is super important.  I believe it will affect anyone using any logging provider with EF Core 7 to log errors.  Thanks in advance for your prompt attention.

<details>
  <summary>Full Log Output - EF Core 6</summary>

```
warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 6.0.11 initialized 'TestDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer:6.0.11' with options: SensitiveDataLoggingEnabled DetailedErrorsEnabled
LocalDb: Start `(LocalDb)\TestDbContext` 314ms.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 6.0.11 initialized 'TestDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer:6.0.11' with options: SensitiveDataLoggingEnabled DetailedErrorsEnabled
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (7ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (36ms) [Parameters=[], CommandType='Text', CommandTimeout='30']

      IF EXISTS
          (SELECT *
           FROM [sys].[objects] o
           WHERE [o].[type] = 'U'
           AND [o].[is_ms_shipped] = 0
           AND NOT EXISTS (SELECT *
               FROM [sys].[extended_properties] AS [ep]
               WHERE [ep].[major_id] = [o].[object_id]
                   AND [ep].[minor_id] = 0
                   AND [ep].[class] = 1
                   AND [ep].[name] = N'microsoft_database_tools_support'
          )
      )
      SELECT 1 ELSE SELECT 0
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE [TestEntities] (
          [Id] int NOT NULL IDENTITY,
          [Property] nvarchar(450) NOT NULL,
          CONSTRAINT [PK_TestEntities] PRIMARY KEY ([Id])
      );
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE UNIQUE INDEX [IX_TestEntities_Property] ON [TestEntities] ([Property]);
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 6.0.11 initialized 'TestDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer:6.0.11' with options: SensitiveDataLoggingEnabled DetailedErrorsEnabled
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 6.0.11 initialized 'TestDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer:6.0.11' with options: SensitiveDataLoggingEnabled DetailedErrorsEnabled
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (40ms) [Parameters=[@p0='Value' (Nullable = false) (Size = 450)], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [TestEntities] ([Property])
      VALUES (@p0);
      SELECT [Id]
      FROM [TestEntities]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (2ms) [Parameters=[@p0='Value' (Nullable = false) (Size = 450)], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [TestEntities] ([Property])
      VALUES (@p0);
      SELECT [Id]
      FROM [TestEntities]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
fail: Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type 'EFCoreBugDemo.TestDbContext'.
      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
       ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.TestEntities' with unique index 'IX_TestEntities_Property'. The duplicate key value is (Value).
      The statement has been terminated.
         at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__208_0(Task`1 result)
         at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
      ClientConnectionId:42695bd1-979c-4e65-8fb4-f68213c4c266
      Error Number:2601,State:1,Class:14
         --- End of inner exception stack trace ---
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
       ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.TestEntities' with unique index 'IX_TestEntities_Property'. The duplicate key value is (Value).
      The statement has been terminated.
         at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__208_0(Task`1 result)
         at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
      ClientConnectionId:42695bd1-979c-4e65-8fb4-f68213c4c266
      Error Number:2601,State:1,Class:14
         --- End of inner exception stack trace ---
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)

Process finished with exit code 0.
```
</details>

<details>
  <summary>Full Log Output - EF Core 7</summary>

```
warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
LocalDb: Start `(LocalDb)\TestDbContext` 322ms.
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (6ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (35ms) [Parameters=[], CommandType='Text', CommandTimeout='30']

      IF EXISTS
          (SELECT *
           FROM [sys].[objects] o
           WHERE [o].[type] = 'U'
           AND [o].[is_ms_shipped] = 0
           AND NOT EXISTS (SELECT *
               FROM [sys].[extended_properties] AS [ep]
               WHERE [ep].[major_id] = [o].[object_id]
                   AND [ep].[minor_id] = 0
                   AND [ep].[class] = 1
                   AND [ep].[name] = N'microsoft_database_tools_support'
          )
      )
      SELECT 1 ELSE SELECT 0
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE [TestEntities] (
          [Id] int NOT NULL IDENTITY,
          [Property] nvarchar(450) NOT NULL,
          CONSTRAINT [PK_TestEntities] PRIMARY KEY ([Id])
      );
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE UNIQUE INDEX [IX_TestEntities_Property] ON [TestEntities] ([Property]);
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (50ms) [Parameters=[@p0='Value' (Nullable = false) (Size = 450)], CommandType='Text', CommandTimeout='30']
      SET IMPLICIT_TRANSACTIONS OFF;
      SET NOCOUNT ON;
      INSERT INTO [TestEntities] ([Property])
      OUTPUT INSERTED.[Id]
      VALUES (@p0);
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[@p0='Value' (Nullable = false) (Size = 450)], CommandType='Text', CommandTimeout='30']
      SET IMPLICIT_TRANSACTIONS OFF;
      SET NOCOUNT ON;
      INSERT INTO [TestEntities] ([Property])
      OUTPUT INSERTED.[Id]
      VALUES (@p0);
fail: Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type 'EFCoreBugDemo.TestDbContext'.
      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
       ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.TestEntities' with unique index 'IX_TestEntities_Property'. The duplicate key value is (Value).
         at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
         at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
         at Microsoft.Data.SqlClient.SqlDataReader.ReadAsyncExecute(Task task, Object state)
         at Microsoft.Data.SqlClient.SqlDataReader.InvokeAsyncCall[T](SqlDataReaderAsyncCallContext`1 context)
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetAsync(Int32 startCommandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
      ClientConnectionId:eb16f019-db75-47c3-9f1b-1bbdf0bfae68
      Error Number:2601,State:1,Class:14
         --- End of inner exception stack trace ---
         at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
       ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.TestEntities' with unique index 'IX_TestEntities_Property'. The duplicate key value is (Value).
         at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
         at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
         at Microsoft.Data.SqlClient.SqlDataReader.ReadAsyncExecute(Task task, Object state)
         at Microsoft.Data.SqlClient.SqlDataReader.InvokeAsyncCall[T](SqlDataReaderAsyncCallContext`1 context)
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetAsync(Int32 startCommandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
      ClientConnectionId:eb16f019-db75-47c3-9f1b-1bbdf0bfae68
      Error Number:2601,State:1,Class:14
         --- End of inner exception stack trace ---
         at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)

Process finished with exit code 0.
```

</details>

**Comment by ajcvickers** [comment]
@roji Could this be an unintended impact of the changes to logging for cancellations?

**Comment by roji** [comment]
This is a result of EF Core 7.0 using a single statement with OUTPUT when inserting, which is more efficient.

EF Core 7.0 SQL:

```sql
SET IMPLICIT_TRANSACTIONS OFF;
SET NOCOUNT ON;
INSERT INTO [TestEntities] ([Property])
OUTPUT INSERTED.[Id]
VALUES (@p0);
```

EF Core 6.0 SQL:

```sql
SET NOCOUNT ON;
INSERT INTO [TestEntities] ([Property])
VALUES (@p0);
SELECT [Id]
FROM [TestEntities]
WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
```

In EF Core 7.0, ExecuteReaderAsync succeeds, and the error is only raised later, when ReadAsync is called; this is why there's a successful (Info-level) Executed DbCommand in the logs. You can reproduce the 6.0 behavior on 7.0 by telling EF that there's a trigger on the table ([docs](https://learn.microsoft.com/en-us/ef/core/providers/sql-server/misc#savechanges-and-database-triggers)), which causes it to generate the 2 separate SQLs - this causes ExecuteReaderAsync to fail.

Although this is a behavior change, it isn't clear that the 7.0 behavior is incorrect (or even worse than the 6.0 behavior): to reliably know whether an update failed, you should be looking at the higher-level Update log event, and not at the lower-level ExecuteReader event. For example, even in EF Core 6.0, if you happen to batch two inserts together, and the *second* one generates a unique constraint violation, it's very likely the ExecuteReader succeeded, much like how 7.0 handles a single insert failure.

Is there a particular reason why you feel this is super important?

**Comment by mattjohnsonpint** [comment]
I understand the difference in the two commands, and I agree that having a single query is more efficient.  But the result is that we no longer capture failures from such commands via logging alone.  The only log that comes through is for the update, which doesn't emit the failed query to the logs.

Additionally, we no longer get informed about failed updates via [diagnostic listeners](https://learn.microsoft.com/en-us/ef/core/logging-events-diagnostics/diagnostic-listeners) either.

This is important from our perspective (speaking for [Sentry](https://sentry.io) and our shared customers), because we have long offered [automatic instrumentation of EF Core](https://docs.sentry.io/platforms/dotnet/performance/instrumentation/automatic-instrumentation/#entity-framework-core-integration) as part of our .NET SDK.  With the update to EF Core 7, the lack of error output from makes it appear as if transactions are succeeding when they are not.

Please take a glance at the diff in our draft PR: https://github.com/getsentry/sentry-dotnet/pull/2051, which updates our integration tests to use EF Core 7.  We use a snapshot testing approach for these tests, which records exactly what we capture and send to Sentry.  You can see in the diffs that we have two tests with different results on EF Core 7 due to  the query change (which unto itself is fine).  But you can also see that one of the tests used to record the failing query with `Failed executing DbCommand` (along with breadcrumbs of the successful queries leading up to then), and then it marks the transaction with our status `InternalError`.  After updating to EF Core 7, it no longer captures the failed query, and the transaction is marked `Ok` (success).

So, from the customer's perspective - everything looks fine except for that it is not.

In our integration test (and the simplified repro I provided), we swallow exceptions thrown by `SaveChangesAsync`, such that we can look specifically for the desired logging + DiagnosticSource outputs.  Of course in a real app, the customer would likely not do that, and thus an exception would be thrown.  The Sentry SDK can capture that exception, which will show the error:

> Cannot insert duplicate key row in object 'dbo.TestEntities' with unique index 'IX_TestEntities_Property'. The duplicate key value is (Value)

... but it does not contain the offending SQL query that caused the error and thus the customer is left wondering which SQL query actually caused it.  It's especially difficult if `SaveChangesAsync` generated a large number of queries. 

One way or another, we need to be able to get the specific query that failed.  If there's a workaround we can incorporate into the Sentry SDK, I'm happy to do that and open to suggestions.  Though, I don't believe modifying their schema to tell EF that there's a trigger would be an appropriate solution.

Thanks.

**Comment by roji** [comment]
> I understand the difference in the two commands, and I agree that having a single query is more efficient. But the result is that we no longer capture failures from such commands via logging alone. The only log that comes through is for the update, which doesn't emit the failed query to the logs.
>
> Additionally, we no longer get informed about failed db commands via [diagnostic listeners](https://learn.microsoft.com/en-us/ef/core/logging-events-diagnostics/diagnostic-listeners) either.

I understand, but it's important to understand that the above already wasn't working in batched cases, as I indicated above. In other words, 7.0 only *extends* the cases where ExecuteReader doesn't fail in SaveChanges. I understand that your library was doing things this way and was possibly succeeding, but attempting to detect failed SaveChanges by looking at ExecuteReader was already an incorrect way to do things before - have you tested detection of failures in batched scenarios, with more than one operation in SaveChanges?

But I understand the problem you're expressing. If the requirement here is to detect the failure via logging (as opposed to by catching exceptions), then the Update event is the right way to do that; at that point, it should be possible to correlate the command execution event in order to get the SQL. We can also start a conversation about including the SQL with the Update event, which may help out.

> Though, I don't believe modifying their schema to tell EF that there's a trigger would be an appropriate solution.

Note that no schema modifications are required, only an EF model modification. This has no impact on the database in any way, and just changes what SQL EF sends when SaveChanges is invoked. At the very least, this can be a temporary workaround.

**Comment by mattjohnsonpint** [comment]
Thanks for the feedback.  I'll discuss with my team to see how we want to proceed.

**Comment by mattjohnsonpint** [comment]
I'm still unclear about one point.  Why does `ExecuteReaderAsync` with only the one statement?  The failure should have been caused by the `INSERT` statement, not the `SELECT`.

Digging deeper, I'm not convinced this is an EF issue, but perhaps an issue with SQL Client.  If I take logging out completely, and only subscribe to DiagnosticSource events from SQL Client (and not from EF at all), then I don't get any `"Microsoft.Data.SqlClient.WriteCommandError"` messages with the `OUTPUT INSERTED.[Id]` version of the query, and I always do with the `scope_identity()` version.  Regardless of what EF Core does, shouldn't SQL Client still emit the error event?

(Adding the trigger on the model did indeed revert the query in EF Core 7, and matched the behavior of EF Core 6.)

**Comment by mattjohnsonpint** [comment]
Playing around with SqlClient by itself (no EF Core), I can see that the `WriteCommandError` from DiagnosticListener is absent only when an `OUTPUT` clause is present in the query *and* the query is invoked with `ExecuteReader` (or `ExecuteReaderAsync`) - even when followed by a `Read`.

If the query doesn't contain an `OUTPUT` clause, then the error comes through fine - even if it doesn't contain the `SELECT` with  `scope_identity()`.

Also if the query is invoked with `ExecuteScalar`, then the error comes through fine, with or without the `OUTPUT` clause.

I think I should raise this as a bug with SqlClient.

I guess EF Core invokes using `ExecuteReader` so that it can return multiple values if there are multiple insertions in the same batch?

**Comment by mattjohnsonpint** [comment]
FYI - I put another clean demo together and raised an issue at https://github.com/dotnet/SqlClient/issues/1839

**Comment by roji** [comment]
@mattjohnsonpint this very likely has something to do with the way the wire protocol (TSQL) works around these two different statements. INSERT with OUTPUT has a resultset (whereas the other syntax does not), which changes things considerably. Note also that this kind of thing is very provider-dependent, i.e. a different database with a different database driver may do things differently, based on how the wire protocol works in their case.

But in any case, I do agree that it would be good if SqlClient did log this from ExecuteReader (for single-statement commands) - let's see what the SqlClient maintainers say about this.

**Comment by roji** [comment]
FYI opened https://github.com/npgsql/npgsql/issues/1323 to look into better failure diagnostics for batched commands in Npgsql.
