### ISSUE TITLE
EF Core 7 InMemory database - An issue during invoking method AddRange/UpdateRange with strongly typed ids

### ISSUE THREAD

**Issue by Vecna0905** [dotnet/efcore#29636]
### Description

Hi All,

I noticed an issue using InMemoryDatabase in our Unit Tests while invoking the AddRange/UpdateRange methods. I suppose the issue is caused by strongly typed ids that were introduced here https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#value-generation-for-ddd-guarded-types. A production code works fine, but unit tests failing due to impossibility to find appropriate ValueGenerator.

### Code

```C#
  public sealed class ProductIdConverter : ValueConverter<ProductId, int>
  {
      public ProductIdConverter() : base(
          value => value.Value,
          value => new ProductId(value))
      {
      }
  }

  protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
  {
      configurationBuilder.Properties<ProductId>().HaveConversion<ProductIdConverter>();
      base.ConfigureConventions(configurationBuilder);
  }

  public readonly record struct ProductId(int Value);
  
  public class Product
  {
      public ProductId ProductId { get; private set; }
      public string Name { get; private set; }
  
      public Product(string name)
      {
          Name = name;
      }
  }

public class ProductEntityConfiguration : IEntityTypeConfiguration<Product>
{
    public void Configure(EntityTypeBuilder<Product> builder)
    {
        builder.ToTable("Products");
        
        builder.HasKey(x => x.ProductId);
        builder.Property(x => x.ProductId).ValueGeneratedOnAdd();
    }
}

  var products = new[]
  {
      new Product("A"),
      new Product("B"),
      new Product("C")
  };

  await _dbContext.AddRangeAsync(products);

  await _unitOfWork.SaveChanges();
```

### Stack traces

Include the full exception message and stack trace for any exception you encounter.

Use triple-tick fences for stack traces. For example:

```
System.NotSupportedException : The property 'Product.Id' does not have a value set and no value generator is available for properties of...

System.NotSupportedException : The property 'Product.Id' does not have a value set and no value generator is available for properties of type 'Product'. Either set a value for the property before adding the entity or configure a value generator for properties of type 'Product' in 'OnModelCreating'.
   at Microsoft.EntityFrameworkCore.ValueGeneration.ValueGeneratorSelector.Create(IProperty property, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.ValueGeneration.ValueGeneratorSelector.<Select>b__6_0(IProperty p, IEntityType t)
   at Microsoft.EntityFrameworkCore.ValueGeneration.ValueGeneratorCache.<>c.<GetOrAdd>b__6_0(CacheKey ck, Func`3 f)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.EntityFrameworkCore.ValueGeneration.ValueGeneratorCache.GetOrAdd(IProperty property, IEntityType entityType, Func`3 factory)
   at Microsoft.EntityFrameworkCore.ValueGeneration.ValueGeneratorSelector.Select(IProperty property, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.InMemory.ValueGeneration.Internal.InMemoryValueGeneratorSelector.Select(IProperty property, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ValueGenerationManager.GetValueGenerator(IProperty property)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ValueGenerationManager.Generate(InternalEntityEntry entry, Boolean includePrimaryKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey, Nullable`1 fallbackState)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityStates(IEnumerable`1 entities, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.AddRange(IEnumerable`1 entities)
   at Microsoft.EntityFrameworkCore.DbContext.AddRange(Object[] entities)

```
### Provider and version information

EF Core version: 7.0.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.InMemory)
Target framework: (e.g. .NET 7.0.100)

**Comment by Vecna0905** [comment]
Good Morning @ajcvickers,

Could you tell me when the bugfix will be released?
