### ISSUE TITLE
SQLite Error 11: database disk image is malformed

### ISSUE THREAD

**Issue by davejitsu** [dotnet/efcore#29630]
Hi, we're intermittently experiencing the error **SQLite Error 11: database disk image is malformed** when querying SQLite. We already tried adding a retry policy but it still fails intermittently. We also tried downloading the file and running <code>PRAGMA integrity_check</code> but the result is OK. Would anyone know what's the cause and how to fix it?

Microsoft.Data.Sqlite - 6.0.4
Dapper - 2.0.123
Target framework: .NET 6.0
Environment: Kubernetes
Container Image: Alpine 3:14

Connection String:
- Mode: SqliteOpenMode.ReadWrite
- Cache: SqliteCacheMode.Shared
- Pooling: false
- SQLite file is located in Azure File Share and mounted to k8s pod

```C#
var connectionString = GetConnectionString(clientId, surveyId, versionId);
using (var connection = new SqliteConnection(connectionString))
{
    var sql = "SELECT Bitset FROM OverallBitset;";

    return await connection.QueryAsync<OverallBitsetByteArray>(sql);
}
```

Stack trace:
```
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
```

**Comment by ErikEJ** [comment]
Sqlite is a file based database and not designed for access through layers of inderection over a sometimes unstable / changing network. Use a proper TCP based database engine instead.

**Comment by ajcvickers** [comment]
@davejitsu Does this fail when not running on a remote file system?

**Comment by davejitsu** [comment]
Hi @ajcvickers - apologies for the late reply. I tried mounting the azure file share locally but I was not able to replicate it.
