### ISSUE TITLE
OSX/coreclr DLL Not found exception with SQLite

### ISSUE THREAD

**Issue by balneaves** [dotnet/efcore#2964]
Running my ASPNET5 app on the coreclr on OSX fails to start up when using the SQLite provider.  SQLServer provider seems fine (at least it gets further...but I dont have a SQLServer instance to test fully with).

DNVM : `*    1.0.0-beta8-15542    coreclr x64  darwin          default`
DNX : `Microsoft .NET Execution environment CoreCLR-x64-1.0.0-beta8-15542`
EF Deps : 

```
  EntityFramework.Core 7.0.0-beta8-15538
  EntityFramework.Relational 7.0.0-beta8-15538
* EntityFramework.SqlServer 7.0.0-beta8-15538
* EntityFramework.Sqlite 7.0.0-beta8-15538
```

```
System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.Interop.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-libraryloader-l1-1-0': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Microsoft.Framework.Internal.NativeLibraryLoader.GetModuleHandle(String lpModuleName)
   at Microsoft.Framework.Internal.NativeLibraryLoader.IsLoaded(String dllName)
   at Microsoft.Framework.Internal.NativeLibraryLoader.TryLoad(String dllName, String applicationBase)
   at Microsoft.Data.Sqlite.Interop.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(String filename, Sqlite3Handle& ppDb, Int32 flags, String vfs)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.Data.Entity.Storage.RelationalConnection.Open()
   at Microsoft.Data.Entity.Sqlite.SqliteDatabaseConnection.Open()
   at Microsoft.Data.Entity.Storage.SqlStatementExecutor.Execute[T](IRelationalConnection connection, RelationalCommand command, Func`2 action)
   at Microsoft.Data.Entity.Sqlite.SqliteDatabaseCreator.HasTables()
   at Microsoft.Data.Entity.Storage.RelationalDatabaseCreator.HasTablesAsync(CancellationToken cancellationToken)
   at Microsoft.Data.Entity.Storage.RelationalDatabaseCreator.<EnsureCreatedAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Kraken.Models.SampleData.<InitializeDatabaseAsync>d__0.MoveNext()
System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-libraryloader-l1-1-0': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Microsoft.Framework.Internal.NativeLibraryLoader.GetModuleHandle(String lpModuleName)
   at Microsoft.Framework.Internal.NativeLibraryLoader.IsLoaded(String dllName)
   at Microsoft.Framework.Internal.NativeLibraryLoader.TryLoad(String dllName, String applicationBase)
   at Microsoft.Data.Sqlite.Interop.NativeMethods..cctor()
```

**Comment by natemcmaster** [comment]
This is a problem should have been fixed with https://github.com/aspnet/Microsoft.Data.Sqlite/pull/113. Can you run `dnu list --details` and report which version of `Microsoft.Data.Sqlite` you have installed?

**Comment by salerth** [comment]
Microsoft.Data.Sqlite 1.0.0-beta8-15514

**Comment by natemcmaster** [comment]
Confirmed. Moving to https://github.com/aspnet/Microsoft.Data.Sqlite/issues/121
