### ISSUE TITLE
Entity Configuration using IsRowVersion.HasConversion<byte[]> for Sql Server fails if derived entity uses OwnsOne config

### ISSUE THREAD

**Issue by nhwilly** [dotnet/efcore#29689]
I became interested in the conversion of the SQL Server row version from a `byte[]` into a `ulong` after reading [the docs here](https://learn.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations#use-ulong-for-timestamprowversion) 

Everything worked great except for a TPH that had a base class `NotificationChannelBase` and three derived types:
- `EmailChannel`
- `PushChannel`
- `SmsChannel`

The base class contains this:
```csharp
public ulong Version { get; init; }
```

and the configuration class contains this:
```csharp
builder
  .Property(e => e.Version)
  .IsRowVersion()
  .HasConversion<byte[]>();
```

An error occurs when doing a save changes - _but only for PushChannel and SmsChannel as they contain value objects as owned properties._

The error is: `Unable to cast object of type 'System.UInt64' to type 'System.Byte[]'`

The `EmailChannel` works fine.  I simulated what was happening with another class to confirm it.  `OwnsOne` seems to throw it off.

I subsequently modified `NotificationChannelBase` to use a `byte[] Version`, removed the conversion inside the configuration and it's all back to working.

This approach worked for all my other objects.  It would be great if I could use a single approach within my entities.

HTH

Only the PushChannel and SMS Channel have owned types,
EF Core version:  7.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system:  Windows 11 (latest)
IDE: Visual Studio 2022 17.4.0 Preview 6.0

**Comment by ajcvickers** [comment]
Works in 6.0. Stack trace and repro:

```
Unhandled exception. Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> System.InvalidCastException: Unable to cast object of type 'System.UInt64' to type 'System.Byte[]'.
   at Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer`1.Snapshot(Object instance)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SidecarValues.SnapshotValue(IProperty property, Object value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SidecarValues.SetValue(IProperty property, Object value, Int32 index)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean isMaterialization, Boolean setModified, Boolean isCascadeDelete, CurrentValueType valueType)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetStoreGeneratedValue(IProperty property, Object value, Boolean setModified)
   at Microsoft.EntityFrameworkCore.Update.ColumnModification.set_Value(Object value)
   at Microsoft.EntityFrameworkCore.Update.ColumnModification.set_Value(Object value)
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.PropagateResults(RelationalDataReader relationalReader)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSet(Int32 startCommandIndex, RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__107_0(DbContext _, ValueTuple`2 t)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Program.Main() in C:\local\code\AllTogetherNow\Daily\Daily.cs:line 104
```

```C#
public static class Your
{
    public static string ConnectionString = @"Data Source=(LocalDb)\MSSQLLocalDB;Database=AllTogetherNow";
}

public abstract class Channel
{
    public int Id { get; set; }
    public ulong Version { get; init; }
}

public class EmailChannel : Channel
{
}

public class PushChannel : Channel
{
    public Foo Foo { get; set; }
}

public class SmsChannel : Channel
{
    public Foo Foo { get; set; }
}

[Owned]
public class Foo
{
    public int X { get; set; }
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(Your.ConnectionString)
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    public DbSet<Channel> Channels => Set<Channel>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Channel>()
            .Property(e => e.Version)
            .IsRowVersion()
            .HasConversion<byte[]>();

        modelBuilder.Entity<EmailChannel>();
        modelBuilder.Entity<PushChannel>();
        modelBuilder.Entity<SmsChannel>();
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.AddRange(new SmsChannel { Foo = new Foo() }, new EmailChannel(), new PushChannel { Foo = new Foo() });
            context.SaveChanges();
        }
    }
}
```

**Comment by nhwilly** [comment]
Wow.  A response, a reproduction and bug assignment in less than 14 hours.  This is why I love you guys.  Thanks!
