### ISSUE TITLE
The instance of entity type 'Domain' cannot be tracked because another instance with the key value '{Id: 2}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.

### ISSUE THREAD

**Issue by Rombersoft** [dotnet/efcore#29749]
I have such context class:
```
public class PgContext : DbContext
 {
        if (_logger == null)
            {
                using ILoggerFactory loggerFactory = LoggerFactory.Create(loggingBuilder => loggingBuilder.SetMinimumLevel(LogLevel.Trace).AddConsole());
                _logger = loggerFactory.CreateLogger<Application>();
            }
            string host = Environment.GetEnvironmentVariable("DbHost");
            string port = Environment.GetEnvironmentVariable("DbPort");
            string dbName = Environment.GetEnvironmentVariable("DbName");
            string user = Environment.GetEnvironmentVariable("DbUser");
            string password = Environment.GetEnvironmentVariable("DbPassword");
            optionsBuilder.UseNpgsql($"Host={host};Port={port};Database={dbName};Username={user};Password={password};Timeout=300;Pooling=true;MinPoolSize=1;" +
                                     $"MaxPoolSize=30;ConnectionLifeTime=15;IncludeErrorDetail=true").EnableSensitiveDataLogging();
            optionsBuilder.LogTo(text =>
            {
                _logger.ApplicationError(new Exception(), text, null);
            }, LogLevel.Critical);
        
            optionsBuilder.LogTo(text =>
            {
                _logger.ApplicationError(new Exception(), text);
            }, LogLevel.Error);
}
```
I have such classes for mapping to database
```
[Index("Id", "Name")]
    public class Domain
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }
        [Required]
        [Column(TypeName = "varchar(100)")]
        public string Name { get; set; }
        public DateTime? LastScanned { get; set; }
        public int PagesCount { get; set; }
        [Required]
        public bool RobotsExists { get; set; }
        [Required]
        public int DelayBetweenPages { get; set; }
        public List<Sitemap> Sitemaps { get; set; }
        public List<WebPage> Pages { get; set; }

        public Domain(string name)
        {
            Name = name;
        }
    }

[Index("Id", "URL")]
public class Sitemap
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public long Id { get; set; }
    //[Required]
    //public long DomainId { get; set; }
    [Required]
    [Column(TypeName = "varchar(120)")]
    public string URL { get; set; }
    public DateTime? LastScanned { get; set; }
    [ForeignKey("DomainId")]
    public Domain Domain { get; set; }
}

[Index("Id", "URL")]
public class WebPage
{
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public long Id { get; set; }
    [Required]
    [Column(TypeName = "text")]
    public string URL { get; set; }
    public bool? Disallowed { get; set; }
    public bool? NoFollow { get; set; }
    public bool? NoIndex { get; set; }
    [DefaultValue("0000-00-00")]
    public DateTime? LastScanned { get; set; }
    [ForeignKey("DomainId")]
    public Domain Domain { get; set; }
}
```

I've do operation in new created context:
```C#
using (PgContext context = new PgContext())
        {
            context.ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking; 
            try
            {
                int count = pages.Count;
                List<WebPage> newPages = new List<WebPage>(count);
                List<WebPage> oldPages = new List<WebPage>(count);
                WebPage[] pagesFromDb = context.WebPages.AsQueryable().AsNoTracking().ToArray();
                HashSet<long> attachedDomainIds = new(count / 4);
                for (int i = 0; i < count; i++)
                {
                    WebPage pageFromDb = pagesFromDb.FirstOrDefault(x => x.URL == pages[i].URL);
                    if (pageFromDb == null)
                    {
                        if (!newPages.Contains(pages[i]))
                            newPages.Add(pages[i]);
                    }
                    else
                    {
                        pageFromDb.Disallowed = pages[i].Disallowed;
                        if (!oldPages.Contains(pageFromDb))
                            oldPages.Add(pageFromDb);
                    }
                    context.Entry(pages[i].Domain).State = EntityState.Detached;  //this I added later, thought that it could resolve problem
                }
                context.ChangeTracker.Clear();  //this I added later, thought that it could resolve problem
                context.SaveChanges();   //this I added later, thought that it could resolve problem
                if (newPages.Any())
                    context.WebPages.AddRange(newPages);      //here throws InvalidOperationException
                if (oldPages.Any())
                    context.WebPages.UpdateRange(oldPages);
                context.SaveChanges();
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }
        }

```

Exception message:
```
The instance of entity type 'Domain' cannot be tracked because another instance with the key value '{Id: 2}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.
```
StackTrace:
```
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.SetEntityStates(IEnumerable`1 entities, EntityState entityState)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.AddRange(IEnumerable`1 entities)
   at Web.Api.PostgreSQL.PageDataStorage.AddRange(List`1 pages) in /media/Projects/Core.Web.Api/Storage/Providers/PostgreSQL/DataBase/PageDataStorage.cs:line 72
```

EF Core version: 6.0.7
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: (e.g. .NET 6.0)
Operating system: Debian 11
IDE: Jet Brains Rider

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
