### ISSUE TITLE
dotnet ef migrations bundle fails with `error NETSDK1083: The specified RuntimeIdentifier 'amzn.2-x64' is not recognized`  on some AWS Linux machines

### ISSUE THREAD

**Issue by krylatij** [dotnet/efcore#29774]
## Issue
`dotnet ef migrations bundle ...` fails with `error NETSDK1083: The specified RuntimeIdentifier 'amzn.2-x64' is not recognized` 
on some AWS Linux machines.

## Possible reasons:
CLI constructs runtime identifier as `"<OS Name>"."<OS Version>"-"<Architecture>"` instead of using "RID" runtime variable (see output of `dotnet --info` below).

### Run
```
    dotnet ef migrations bundle 
            --project /opt/adops-agent/_work/120/s/backend/src/XXXXX.Data/XXXXX.Data.csproj \
            --startup-project /opt/adops-agent/_work/120/s/backend/src/XXXXX.Api/XXXXX.Api.csproj \
            --output efbundle \
            --configuration github.com.dotnet.efcore.issues.25555 --self-contained --force
```

### Dotnet info
```
Starting: Dotnet info
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.201.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
Script contents:
dotnet --info
========================== Starting Command Output ===========================
/bin/bash /opt/adops-agent/_work/_temp/a013366d-7613-45ce-bea9-d0b070f2d3fa.sh
.NET SDK (reflecting any global.json):
 Version:   6.0.403
 Commit:    2bc18bf292

Runtime Environment:
 OS Name:     amzn
 OS Version:  2
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /opt/adops-agent/_work/_tool/dotnet/sdk/6.0.403/

global.json file:
  Not found

Host:
  Version:      6.0.11
  Architecture: x64
  Commit:       943474ca16

.NET SDKs installed:
  5.0.408 [/opt/adops-agent/_work/_tool/dotnet/sdk]
  6.0.403 [/opt/adops-agent/_work/_tool/dotnet/sdk]

```
### Installing ef-tools
```
dotnet tool install dotnet-ef
========================== Starting Command Output ===========================
/bin/bash /opt/adops-agent/_work/_temp/cf396164-bc9b-49ce-b539-a5c1be167cc7.sh
You can invoke the tool from this directory using the following commands: 'dotnet tool run dotnet-ef' or 'dotnet dotnet-ef'.
Tool 'dotnet-ef' (version '7.0.0') was successfully installed. Entry is added to the manifest file /opt/adops-agent/_work/120/s/backend/.config/dotnet-tools.json.
```

### Verbose output
```
2022-12-05T14:37:43.1463986Z ##[section]Starting: Build migration bundle
2022-12-05T14:37:43.1533690Z ==============================================================================
2022-12-05T14:37:43.1534220Z Task         : Bash
2022-12-05T14:37:43.1534581Z Description  : Run a Bash script on macOS, Linux, or Windows
2022-12-05T14:37:43.1534980Z Version      : 3.201.1
2022-12-05T14:37:43.1535323Z Author       : Microsoft Corporation
2022-12-05T14:37:43.1535803Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
2022-12-05T14:37:43.1536356Z ==============================================================================
2022-12-05T14:37:44.5386341Z Generating script.
2022-12-05T14:37:44.5434201Z ========================== Starting Command Output ===========================
2022-12-05T14:37:44.5468842Z [command]/bin/bash /opt/adops-agent/_work/_temp/4e08651a-c1fb-4b89-b351-cd452417ed6c.sh
2022-12-05T14:37:44.9353190Z Using project '/opt/adops-agent/_work/120/s/backend/src/XXXXX.Data/XXXXX.Data.csproj'.
2022-12-05T14:37:44.9355516Z Using startup project '/opt/adops-agent/_work/120/s/backend/src/XXXXX.Api/XXXXX.Api.csproj'.
2022-12-05T14:37:44.9367650Z Writing '/opt/adops-agent/_work/120/s/backend/src/XXXXX.Data/obj/XXXXX.Data.csproj.EntityFrameworkCore.targets'...
2022-12-05T14:37:44.9391541Z dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=/tmp/tmpM3rIId.tmp /verbosity:quiet /nologo /opt/adops-agent/_work/120/s/backend/src/XXXXX.Data/XXXXX.Data.csproj
2022-12-05T14:37:45.7298003Z Writing '/opt/adops-agent/_work/120/s/backend/src/XXXXX.Api/obj/XXXXX.Api.csproj.EntityFrameworkCore.targets'...
2022-12-05T14:37:45.7301898Z dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=/tmp/tmpMO6r4e.tmp;Configuration=github.com.dotnet.efcore.issues.25555 /verbosity:quiet /nologo /opt/adops-agent/_work/120/s/backend/src/XXXXX.Api/XXXXX.Api.csproj
2022-12-05T14:37:46.3643464Z Build started...
2022-12-05T14:37:46.3645882Z dotnet build /opt/adops-agent/_work/120/s/backend/src/XXXXX.Api/XXXXX.Api.csproj --configuration github.com.dotnet.efcore.issues.25555 /verbosity:quiet /nologo
... skipped ...
2022-12-05T14:37:51.6921181Z 
2022-12-05T14:37:51.6921951Z Build succeeded.
2022-12-05T14:37:51.6922130Z 
... skipped ...
2022-12-05T14:37:51.7270036Z Build succeeded.
2022-12-05T14:37:51.7396412Z dotnet exec --depsfile /opt/adops-agent/_work/120/s/backend/src/XXXXX.Api/bin/github.com.dotnet.efcore.issues.25555/net6.0/XXXXX.Api.deps.json --additionalprobingpath /home/adops-user/.nuget/packages --runtimeconfig /opt/adops-agent/_work/120/s/backend/src/XXXXX.Api/bin/github.com.dotnet.efcore.issues.25555/net6.0/XXXXX.Api.runtimeconfig.json /home/adops-user/.nuget/packages/dotnet-ef/7.0.0/tools/net6.0/any/tools/netcoreapp2.0/any/ef.dll migrations bundle --output /opt/adops-agent/_work/120/a/efbundle --self-contained --force --assembly /opt/adops-agent/_work/120/s/backend/src/XXXXX.Api/bin/github.com.dotnet.efcore.issues.25555/net6.0/XXXXX.Data.dll --project /opt/adops-agent/_work/120/s/backend/src/XXXXX.Data/XXXXX.Data.csproj --startup-assembly /opt/adops-agent/_work/120/s/backend/src/XXXXX.Api/bin/github.com.dotnet.efcore.issues.25555/net6.0/XXXXX.Api.dll --startup-project /opt/adops-agent/_work/120/s/backend/src/XXXXX.Api/XXXXX.Api.csproj --project-dir /opt/adops-agent/_work/120/s/backend/src/XXXXX.Data/ --root-namespace XXXXX.Data --language C# --framework net6.0 --configuration github.com.dotnet.efcore.issues.25555 --nullable --working-dir /opt/adops-agent/_work/120/s/backend --verbose
2022-12-05T14:37:51.8331622Z Using assembly 'XXXXX.Data'.
2022-12-05T14:37:51.8334608Z Using startup assembly 'XXXXX.Api'.
2022-12-05T14:37:51.8337725Z Using application base '/opt/adops-agent/_work/120/s/backend/src/XXXXX.Api/bin/github.com.dotnet.efcore.issues.25555/net6.0'.
2022-12-05T14:37:51.8339259Z Using working directory '/opt/adops-agent/_work/120/s/backend/src/XXXXX.Api'.
2022-12-05T14:37:51.8342226Z Using root namespace 'XXXXX.Data'.
2022-12-05T14:37:51.8343980Z Using project directory '/opt/adops-agent/_work/120/s/backend/src/XXXXX.Data/'.
2022-12-05T14:37:51.8352629Z Remaining arguments: .
2022-12-05T14:37:51.9256788Z Finding DbContext classes...
2022-12-05T14:37:51.9258053Z Finding IDesignTimeDbContextFactory implementations...
2022-12-05T14:37:51.9380090Z Finding application service provider in assembly 'XXXXX.Api'...
2022-12-05T14:37:51.9385173Z Finding Microsoft.Extensions.Hosting service provider...
2022-12-05T14:37:51.9412310Z Using environment 'Development'.
2022-12-05T14:37:52.5200031Z [14:37:52 INF] Starting web host.
2022-12-05T14:37:52.6079942Z [14:37:52 INF] Stopped web host.
2022-12-05T14:37:52.6081260Z Using application service provider from Microsoft.Extensions.Hosting.
2022-12-05T14:37:52.6448225Z Found DbContext 'XXXXXContext'.
2022-12-05T14:37:52.6454348Z Finding DbContext classes in the project...
2022-12-05T14:37:52.7246895Z Using context 'XXXXXContext'.
2022-12-05T14:37:53.5034454Z [40m[32minfo[39m[22m[49m: Microsoft.EntityFrameworkCore.Infrastructure[10403]
2022-12-05T14:37:53.5040878Z       Entity Framework Core 6.0.9 initialized 'XXXXXContext' using provider 'Npgsql.EntityFrameworkCore.PostgreSQL:6.0.7+5b98e4b74de93b590b44aef8dd7967c03acc433c' with options: None
2022-12-05T14:37:53.5588254Z Building bundle...
2022-12-05T14:37:53.5639373Z dotnet publish --runtime amzn.2-x64 --output /tmp/iz5nixnm.oyg/publish --self-contained
2022-12-05T14:37:53.7023942Z MSBuild version 17.3.2+561848881 for .NET
2022-12-05T14:37:54.4042991Z   Determining projects to restore...
2022-12-05T14:37:54.7308310Z /opt/adops-agent/_work/_tool/dotnet/sdk/6.0.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1083: The specified RuntimeIdentifier 'amzn.2-x64' is not recognized. [/opt/adops-agent/_work/120/s/backend/src/XXXXX.Data/XXXXX.Data.csproj]
2022-12-05T14:37:54.7612600Z /opt/adops-agent/_work/_tool/dotnet/sdk/6.0.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1083: The specified RuntimeIdentifier 'amzn.2-x64' is not recognized. [/opt/adops-agent/_work/120/s/backend/src/XXXXX.Shared/XXXXX.Shared.csproj]
2022-12-05T14:37:54.9750674Z /opt/adops-agent/_work/_tool/dotnet/sdk/6.0.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1083: The specified RuntimeIdentifier 'amzn.2-x64' is not recognized. [/opt/adops-agent/_work/120/s/backend/src/XXXXX.Api/XXXXX.Api.csproj]
2022-12-05T14:37:54.9835298Z /opt/adops-agent/_work/_tool/dotnet/sdk/6.0.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1083: The specified RuntimeIdentifier 'amzn.2-x64' is not recognized. [/opt/adops-agent/_work/120/s/backend/src/XXXXX.Services/XXXXX.Services.csproj]
2022-12-05T14:37:54.9913280Z /opt/adops-agent/_work/_tool/dotnet/sdk/6.0.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1083: The specified RuntimeIdentifier 'amzn.2-x64' is not recognized. [/tmp/iz5nixnm.oyg/efbundle.csproj]
2022-12-05T14:37:55.0939528Z Microsoft.EntityFrameworkCore.Tools.CommandException: Build failed. Use --verbose to see errors.
2022-12-05T14:37:55.0940724Z    at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsBundleCommand.Execute(String[] args)
2022-12-05T14:37:55.0941885Z    at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0(String[] args)
2022-12-05T14:37:55.0942802Z    at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
2022-12-05T14:37:55.0943737Z    at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
2022-12-05T14:37:55.0950969Z Build failed. Use --verbose to see errors.
2022-12-05T14:37:55.1396755Z ##[error]Bash exited with code '1'.
2022-12-05T14:37:55.1422488Z ##[section]Finishing: Build migration bundle
```

### Workaround 
You can provide runtime identifier explicitly by setting --target-runtime = 'linux-x64':
```
    dotnet ef migrations bundle 
            --project /opt/adops-agent/_work/120/s/backend/src/XXXXX.Data/XXXXX.Data.csproj \
            --startup-project /opt/adops-agent/_work/120/s/backend/src/XXXXX.Api/XXXXX.Api.csproj \
            --output efbundle \
            --target-runtime linux-x64 \
            --configuration github.com.dotnet.efcore.issues.25555 --self-contained --force
```

**Comment by bricelam** [comment]
EF Core uses `AppContext.GetData("RUNTIME_IDENTIFIER")` to get the default RID. I wonder if AWS is overriding it. If so, they also need to update the [RID catalog](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.NETCore.Platforms/src/runtime.json).

**Comment by bricelam** [comment]
Can you follow up with AWS? I suspect this breaks more than just EF.

Your workaround to use `--target-runtime` is the same one I'd recommend.

**Comment by krylatij** [comment]
I think dotnet tools should have consistent behavior on the same environment.
Why `dotnet publish` works without specifying environment but `dotnet ef bundle` fails?  
In addition to that, RID has valid value "linux-x64" but it is ignored by the tool for some reason.
`
Runtime Environment:
 OS Name:     amzn
 OS Version:  2
 OS Platform: Linux
 RID:         linux-x64
`
