### ISSUE TITLE
InvalidOperationException on "Sub"-Including on keyless entities

### ISSUE THREAD

**Issue by angelaki** [dotnet/efcore#29788]
Right now it doesn't seam possible to do a quite simple _sub-include_, if the containing entity doesn't own a primary key:

```C#
using Microsoft.EntityFrameworkCore;

var dbContext = new DbContext();

Console.WriteLine(dbContext.Set<KeyedTable>().Include(p => p.User).ThenInclude(u => u.Properties).ToQueryString());

// _Unneccessary_ `System.InvalidOperationException` here!
Console.WriteLine(dbContext.Set<KeylessTable>().Include(p => p.User).ThenInclude(u => u.Properties).ToQueryString());

class KeyedTable
{
    public Guid Id { get; set; }
    public Guid UserId { get; set; }
    public User User { get; set; }
}

class KeylessTable
{
    public Guid UserId { get; set; }
    public User User { get; set; }
}

class User
{
    public Guid Id { get; set; }
    public ICollection<UserProperty> Properties { get; set; }
}

class UserProperty
{
    public Guid Id { get; set; }
    public Guid UserId { get; set; }
    public User User { get; set; }
}

class DbContext : Microsoft.EntityFrameworkCore.DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);
        optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=YourDatabase");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<User>(u =>
        {
            u.HasMany(p => p.Properties).WithOne(p => p.User).HasForeignKey(p => p.UserId);
        });

        modelBuilder.Entity<KeyedTable>(u =>
        {
            u.HasOne(p => p.User).WithMany().HasForeignKey(p => p.UserId);
        });

        modelBuilder.Entity<KeylessTable>(u =>
        {
            u.HasNoKey();
            u.HasOne(p => p.User).WithMany().HasForeignKey(p => p.UserId);
        });
    }
}
```

Imho this should be pretty easy using SQL?

**Comment by ajcvickers** [comment]
@angelaki What SQL to you expect?

**Comment by angelaki** [comment]
The exact same query. Why would it change?

**Comment by ajcvickers** [comment]
Notes for triage:

SQL for first query:

```sql
      SELECT [k].[Id], [k].[UserId], [u].[Id], [u0].[Id], [u0].[UserId]
      FROM [KeyedTable] AS [k]
      INNER JOIN [User] AS [u] ON [k].[UserId] = [u].[Id]
      LEFT JOIN [UserProperty] AS [u0] ON [u].[Id] = [u0].[UserId]
      ORDER BY [k].[Id], [u].[Id]
```

Exception for second query:

```
Unhandled exception. System.InvalidOperationException: Unable to translate a collection subquery in a projection since either parent or the subquery doesn't project necessary information required to uniquely identify it and correctly generate results on the client side. This can happen when trying to correlate
on keyless entity type. This can also happen for some cases of projection before 'Distinct' or some shapes of grouping key in case of 'GroupBy'. These should either contain all key properties of the entity that the operation is applied on, or only contain simple property access expressions.
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ApplyProjection(Expression shaperExpression, ResultCardinality resultCardinality, QuerySplittingBehavior querySplittingBehavior)
   at Microsoft.EntityFrameworkCore.Query.Internal.SelectExpressionProjectionApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPostprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerQueryTranslationPostprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.IncludableQueryable`2.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.<Main>$(String[] args) in C:\local\code\AllTogetherNow\Daily\Daily.cs:line 15
```

SQL for third query:

```sql
      SELECT [k].[UserId], [u].[Id]
      FROM [KeylessTable] AS [k]
      INNER JOIN [User] AS [u] ON [k].[UserId] = [u].[Id]
```

Model:

```
Model:
  EntityType: KeyedTable
    Properties:
      Id (Guid) Required PK AfterSave:Throw ValueGenerated.OnAdd
      UserId (Guid) Required FK Index
    Navigations:
      User (User) ToPrincipal User
    Keys:
      Id PK
    Foreign keys:
      KeyedTable {'UserId'} -> User {'Id'} ToPrincipal: User Cascade
    Indexes:
      UserId
  EntityType: KeylessTable Keyless
    Properties:
      UserId (Guid) Required FK Index
    Navigations:
      User (User) ToPrincipal User
    Foreign keys:
      KeylessTable {'UserId'} -> User {'Id'} ToPrincipal: User Cascade
    Indexes:
      UserId
  EntityType: User
    Properties:
      Id (Guid) Required PK AfterSave:Throw ValueGenerated.OnAdd
    Navigations:
      Properties (ICollection<UserProperty>) Collection ToDependent UserProperty Inverse: User
    Keys:
      Id PK
  EntityType: UserProperty
    Properties:
      Id (Guid) Required PK AfterSave:Throw ValueGenerated.OnAdd
      UserId (Guid) Required FK Index
    Navigations:
      User (User) ToPrincipal User Inverse: Properties
    Keys:
      Id PK
    Foreign keys:
      UserProperty {'UserId'} -> User {'Id'} ToDependent: Properties ToPrincipal: User Cascade
    Indexes:
      UserId
```

**Comment by ajcvickers** [comment]
Note from triage: this could be translated. This might only require relaxing the validator, although that might not be trivial, or it may also require additional work in translation.

**Comment by roji** [comment]
Note #36738, which seems to suggest that the problem is with the collection include, rather than it being a ThenInclude ("sub"  include).
