### ISSUE TITLE
dotnet ef dbcontext scaffold with user secret

### ISSUE THREAD

**Issue by maxisam** [dotnet/efcore#29809]
## File a bug

when using 

`dotnet ef dbcontext scaffold`

if I use "Name=ConnectionStrings:DatabaseName", it throws exception during build. 

```
[00:39:04 FTL] {EnvironmentName="Development", ExceptionDetail={["HResult"]=-2146233088, ["Message"]="The host was aborted.", ["Source"]="Microsoft.EntityFrameworkCore.Design", ["Stt System.Diagnostics.DiagnosticListener.Write(String name, Object value)\r\n   at Microsoft.Extensions.Hosting.HostBuilder.ResolveHost(IServiceProvider serviceProvider, DiagnosticListener diagnosticListener)\r\n t System.Diagnostics.DiagnosticListener.Write(String name, Object value)\r\n   at Microsoft.Extensions.Hosting.HostBuilder.ResolveHost(IServiceProvider serviceProvider, DiagnosticListener diagnosticListener)\r\n   at Microsoft.Extensions.Hosting.HostApplicationBuilder.Build()\r\n   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()\r\n   at Program.<Main>$(String[] args) in D:\\Program.cs:line 36", ["TargetSite"]="Void ThrowHostAborted()", ["Type"]="Microsoft.Extensions.Hosting.HostAbortedException"}} An unhandled exception occurred during bootstrapping !!!
Microsoft.Extensions.Hosting.HostAbortedException: The host was aborted.
   at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.ThrowHostAborted()
   at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.OnNext(KeyValuePair`2 value)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)   at Microsoft.Extensions.Hosting.HostBuilder.ResolveHost(IServiceProvider serviceProvider, DiagnosticListener diagnosticListener)   at Microsoft.Extensions.Hosting.HostApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at Program.<Main>$(String[] args) in D:\Program.cs:line 36  

```

However, it still generates the code just fine. And I can run the project with "dotnet run ." just fine as well

If I use connection directly, it works perfectly fine too.

### Include provider and version information

EF Core version: 7.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: dotnet 7
Operating system: window 11
IDE: vscode with dotnet tool 7
ps: My application is a webapp (` WebApplication.CreateBuilder(arg)`)

**Comment by ajcvickers** [comment]
@maxisam This exception is expected in some situations, since the app is started and then aborted. However, it should be caught and handled. Are you seeing this escape the build? Or is something logging the exception before it is caught?

/cc @davidfowl

**Comment by davidfowl** [comment]
Yes this is expected, you should be able to catch and ignore `HostAbortedException` in your application code if you're catching and logging all startup exceptions.
