### ISSUE TITLE
Invalid mapping when changing column name of child entity

### ISSUE THREAD

**Issue by klinki** [dotnet/efcore#29837]
Hello,

I have one more bug with my favorite model :)

short description:

Following code should change column names for tables of Dividend and Coupon entity, but it doesn't.
Instead, it changes the column name of parent InvestmentYield entity.

```cs
        modelBuilder.Entity<InvestmentYield>().UseTptMappingStrategy();

        modelBuilder.Entity<Dividend>().Property(d => d.InvestmentId)
            .HasColumnName("stock_id");

        modelBuilder.Entity<Coupon>().Property(c => c.InvestmentId)
            .HasColumnName("bond_id");
```

Code for full repro

```cs
using Microsoft.EntityFrameworkCore;

public class Bond : Investment
{
    public virtual ICollection<Coupon> Coupons { get; set; }
}

public class Coupon : InvestmentYield
{
}

public class Dividend : InvestmentYield
{
}

public abstract class Investment
{
    public int Id { get; set; }
}

public abstract class InvestmentYield
{
    public int Id { get; set; }

    public Investment Investment { get; set; }
    public int InvestmentId { get; set; }
}

public class Stock : Investment
{
    public virtual ICollection<Dividend> Dividends { get; set; }
}

public class SomeDbContext : DbContext
{
    public DbSet<Investment> Investments { get; set; }
    public DbSet<Stock> Stocks { get; set; }
    public DbSet<Bond> Bonds { get; set; }
    public DbSet<InvestmentYield> Yields { get; set; }
    public DbSet<Dividend> Dividends { get; set; }
    public DbSet<Coupon> Coupons { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlite(@"Data Source=database.dat")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<InvestmentYield>().UseTptMappingStrategy();

        modelBuilder.Entity<Dividend>().Property(d => d.InvestmentId)
            .HasColumnName("stock_id");

        modelBuilder.Entity<Coupon>().Property(c => c.InvestmentId)
            .HasColumnName("bond_id");
    }
}

public class Program
{
    public static async Task Main()
    {
        using (var context = new SomeDbContext())
        {
            Console.WriteLine("Building model...");
            var model = context.Model;

            var yields = context.Yields.Include(x => x.Investment)
                .ToList();
            
            Console.WriteLine("Model built.");
        }
    }
}

```

This creates following table structure

```
Yields
---
Id
**bond_id**

Dividends
---
Id
StockId

Coupons
---
Id
BondId


Investments
---
Id

Stocks
---
Id

Bonds
---
Id
```

Problem is the column `bond_id` in Yields table. The idea was to change name of columns in Coupons/Dividends tables (see mapping), but that didn't happen and instead of that, it renamed column in Yields table. I guess it used `bond_id` since it was the last statement.  

### Include provider and version information
EF Core version: 7.0.0 
Database provider: Microsoft.EntityFrameworkCore.SqlServer (same happens also for Microsoft.EntityFrameworkCore.Sqlite, maybe it is provider independent issue) 
Target framework: .NET 7
Operating system: Windows 10
IDE: Visual Studio 2022 17.4

**Comment by ajcvickers** [comment]
@klinki See [Properties mapped to different column names](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#properties-mapped-to-different-column-names)/

**Comment by klinki** [comment]
Thanks for hint, I tried this:

```csharp
        modelBuilder.Entity<Dividend>()
            .ToTable("dividend", builder =>
            {
                builder.Property(d => d.InvestmentId)
                    .HasColumnName("stock_id");
            });

        modelBuilder.Entity<Coupon>()
            .ToTable("coupon", builder =>
            {
                builder.Property(c => c.InvestmentId)
                    .HasColumnName("bond_id");
            });
```

and now I'm getting error 

> System.InvalidOperationException: The property 'InvestmentYield.InvestmentId' has specific configuration for the table 'coupon', but isn't mapped to a column on that table. Remove the specif
ic configuration, or map an entity type that contains this property to 'coupon'.
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidatePropertyOverrides(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Sqlite.Infrastructure.Internal.SqliteModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope servicePr
oviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope servicePr
oviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope servicePr
oviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope servicePr
oviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope servicePr
oviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope servicePr
oviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
The property 'InvestmentYield.InvestmentId' has specific configuration for the table 'coupon', but isn't mapped to a column on that table. Remove the specific configuration, or map an entity
 type that contains this property to 'coupon'.

**Comment by ajcvickers** [comment]
@klinki Clarifying question: are you trying to rename the `StockId` and `BondId` columns in the table structure you show? Note that these columns are not mapped to the `InvestmentId` property in your model.

**Comment by klinki** [comment]
Yes, that's what I'd like to achieve. 

What do you mean by these columns not being mapped to `InvestmentId` ? Isn't the code in the post above supposed to do the mapping? Or the code in the first post?

I also tried to combine both and it still doesn't work.

```csharp

        modelBuilder.Entity<Dividend>().Property(d => d.InvestmentId);
        modelBuilder.Entity<Coupon>().Property(c => c.InvestmentId);

        modelBuilder.Entity<Dividend>()
            .ToTable("dividend", builder =>
            {
                builder.Property(d => d.InvestmentId)
                    .HasColumnName("stock_id");
            });

        modelBuilder.Entity<Coupon>()
            .ToTable("coupon", builder =>
            {
                builder.Property(c => c.InvestmentId)
                    .HasColumnName("bond_id");
            });
```

**Comment by ajcvickers** [comment]
@klinki The model creates two different relationships with two different foreign keys for `Coupons` -> `Investement` and `Dividends` -> `Investment`. If these should both use the `InvestmentId` property as the FK, then this needs to be explicitly configured:

```C#
modelBuilder
    .Entity<Stock>()
    .HasMany(e => e.Dividends)
    .WithOne(e => (Stock)e.Investment)
    .HasForeignKey(e => e.InvestmentId);

modelBuilder
    .Entity<Bond>()
    .HasMany(e => e.Coupons)
    .WithOne(e => (Bond)e.Investment)
    .HasForeignKey(e => e.InvestmentId);
```

This maps to the following table structure:

```sql
CREATE TABLE "Yields" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_Yields" PRIMARY KEY AUTOINCREMENT,
    "InvestmentId" INTEGER NOT NULL);

CREATE TABLE "Coupons" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_Coupons" PRIMARY KEY AUTOINCREMENT,
    CONSTRAINT "FK_Coupons_Yields_Id" FOREIGN KEY ("Id") REFERENCES "Yields" ("Id") ON DELETE CASCADE);

CREATE TABLE "Dividends" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_Dividends" PRIMARY KEY AUTOINCREMENT,
    CONSTRAINT "FK_Dividends_Yields_Id" FOREIGN KEY ("Id") REFERENCES "Yields" ("Id") ON DELETE CASCADE);

```

EF will generate a warning-as-error by default for this since the FK constraint cannot be created in the database. This warning can be suppressed if you're okay with this.

Note that this is not the table structure you are asking for since that structure takes the `InvestmendId` property from the base table and maps it to two different tables, which does not conform to the TPT mapping strategy. You could use the TPC mapping strategy instead, which would generate the following tables"

```sql
CREATE TABLE "Coupons" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_Coupons" PRIMARY KEY,
    "InvestmentId" INTEGER NOT NULL,
    CONSTRAINT "FK_Coupons_Investments_InvestmentId" FOREIGN KEY ("InvestmentId") REFERENCES "Investments" ("Id") ON DELETE CASCADE);

CREATE TABLE "Dividends" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_Dividends" PRIMARY KEY,
    "InvestmentId" INTEGER NOT NULL,
    CONSTRAINT "FK_Dividends_Investments_InvestmentId" FOREIGN KEY ("InvestmentId") REFERENCES "Investments" ("Id") ON DELETE CASCADE);
```

Or, with the table/column renaming also:

```sql
CREATE TABLE "coupon" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_coupon" PRIMARY KEY,
    "bond_id" INTEGER NOT NULL,
    CONSTRAINT "FK_coupon_Investments_bond_id" FOREIGN KEY ("bond_id") REFERENCES "Investments" ("Id") ON DELETE CASCADE);

CREATE TABLE "dividend" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_dividend" PRIMARY KEY,
    "stock_id" INTEGER NOT NULL,
    CONSTRAINT "FK_dividend_Investments_stock_id" FOREIGN KEY ("stock_id") REFERENCES "Investments" ("Id") ON DELETE CASCADE);
```

**Comment by klinki** [comment]
Thanks!

This did the trick

```csharp
        modelBuilder.Entity<InvestmentYield>().UseTpcMappingStrategy();
        modelBuilder.Entity<Investment>().UseTpcMappingStrategy();

        modelBuilder
            .Entity<Stock>()
            .HasMany(e => e.Dividends)
            .WithOne(e => (Stock)e.Investment)
            .HasForeignKey(e => e.InvestmentId);

        modelBuilder
            .Entity<Bond>()
            .HasMany(e => e.Coupons)
            .WithOne(e => (Bond)e.Investment)
            .HasForeignKey(e => e.InvestmentId);

        modelBuilder.Entity<Dividend>()
            .ToTable("dividend", builder =>
            {
                builder.Property(d => d.InvestmentId)
                    .HasColumnName("stock_id");
            });

        modelBuilder.Entity<Coupon>()
            .ToTable("coupon", builder =>
            {
                builder.Property(c => c.InvestmentId)
                    .HasColumnName("bond_id");
            });
```
I guess it is possible to achieve it only with TPC, right?

Now, little bit off-topic question, but is it possible to get InvestmentYield with Investment?

I tried this:

```csharp
        var yields = context
            .Yields.Include(x => x.Investment)
            .ToList();
```

and I got this exception:

<details>
<summary>Error</summary>

```
Unhandled exception. System.InvalidOperationException: The expression 'x.Investment' is invalid inside an 'Include' operation, since it does not represent a property access: 't => t.MyProperty'. To target navigations declared on derived types, use casting ('t => ((Derived)t).MyProperty') or the 'as' operator ('t => (t as Derived).MyProperty'). Collection navigation access can be filtered by composing Where, OrderBy
(Descending), ThenBy(Descending), Skip or Take operations. For more information on including related data, see http://go.microsoft.com/fwlink/?LinkID=746393.
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.PopulateIncludeTree(IncludeTreeNode includeTreeNode, Expression expression, Boolean setLoaded)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ProcessInclude(NavigationExpansionExpression source, Expression expression, Boolean thenInclude, Boolean setLoaded)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.IncludableQueryable`2.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

```
</details>

**Comment by ajcvickers** [comment]
@klinki Since there are two relationships configured, one for each subtype, you'll need to cast and Include twice:

```C#
            var yields = context.Yields
                .Include(x => ((Coupon)x).Investment)
                .Include(x => ((Dividend)x).Investment)
                .ToList();
```

Note from triage: we could possibly make this not necessary in cases like this.

**Comment by klinki** [comment]
Thanks! I already do that in my app, but I was hoping there is a better way. It is quite annoying if there are lot of child entities and it is not very future-proof (adding new entity type would require modification of all existing queries).

Anyway, I can live with that for now and wait if you implement the automatic way to include all relationship.


Thanks for help and have a nice Christmas! :)
