### ISSUE TITLE
Relations in ef c not mapped in sqlite provider

### ISSUE THREAD

**Issue by Erik8309** [dotnet/efcore#29844]
When using the sqlite provider the navigation properties for related entities are not populated in queries. It will work using a join operation since the ids work, but that is more cumbersome, creates more code and less readable. Depending on how you add the entities sometimes the navigation properties are there (I have not yet found the logic behind it), but mostly not. 

### Code to reproduce
[ConsoleApp1.zip](https://github.com/dotnet/efcore/files/10219796/ConsoleApp1.zip)
```
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System.Security.Cryptography.X509Certificates;
namespace ConsoleApp1
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var dbContext = new UserContext();
            dbContext.Database.EnsureCreated();
            dbContext.Users.Add(new User
            {
                Name = "Test",
                UserId = Guid.NewGuid(),
                UserRoles = new List<UserRole>
                {
                    new UserRole
                    {
                        Role=new Role
                        {
                            RoleId= Guid.NewGuid(),
                            RoleName="Test role",

                        }
                    }

                }
            });
            dbContext.SaveChanges();
            var newDbContext = new UserContext();
            var joinedRoleNames = newDbContext.Users.Join(newDbContext.UserRoles, x => x.UserId, x => x.UserId, (user, role) =>
                new
                {
                    RoleId = role.RoleId,
                }).Join(newDbContext.Roles, x => x.RoleId, x => x.RoleId, (x, role) => role.RoleName).ToList();

            var roleName = newDbContext.Users.First().UserRoles.Select(x => x.Role.RoleName).ToList(); //This will throw an exception since the role is null. 
        }
    }
    public class Role
    {
        public string? RoleName { get; set; }

        public Guid RoleId { get; set; }

        public List<UserRole>? UserRoles { get; set; }
    }
    public class RoleConfiguration : IEntityTypeConfiguration<Role>
    {
        public void Configure(EntityTypeBuilder<Role> builder)
        {
            builder.HasKey(x => x.RoleId);
        }
    }
    public class User
    {
        public Guid UserId { get; set; }



        public string? Name { get; set; }

        public List<UserRole>? UserRoles { get; set; }
    }
    public class UserConfiguration : IEntityTypeConfiguration<User>
    {
        public void Configure(EntityTypeBuilder<User> builder)
        {
            builder.HasKey(x => x.UserId);

        }
    }
    public class UserRole
    {
        public Guid UserId { get; set; }

        public Guid RoleId { get; set; }

        public User? User { get; set; }

        public Role? Role { get; set; }

        public int Id { get; set; }
    }
    public class UserRoleConfiguration : IEntityTypeConfiguration<UserRole>
    {
        public void Configure(EntityTypeBuilder<UserRole> builder)
        {
            builder.HasKey(x => x.Id);
            builder.HasOne(x => x.Role)
                .WithMany(x => x.UserRoles);
            builder.HasOne(x => x.User)
                .WithMany(x => x.UserRoles);
        }
    }
}

```
### Include provider and version information

EF Core version: 6.0.11
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: NET 6.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.4

### Stacktrace

```
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at ConsoleApp1.Program.Main(String[] args) in C:\Repos\Tester\ConsoleApp1\ConsoleApp1\Program.cs:line 43
```

**Comment by ajcvickers** [comment]
@Erik8309 `newDbContext.Users.First()` cause the first User to be queried from the database and returned. Anything that happens after that (e.g. `.UserRoles.Select(x => x.Role.RoleName).ToList();` is executed using LINQ to Objects in your application, and does not involve the database at all. I suspect what you really want to do is execute the query on the server, although I'm not sure exactly what the query is trying to do. If you really want to just bring back the related entities, then use `Include` on your database query. For example, `newDbContext.Users.Include(e => e.UserRoles).ThenInclude(e => e.Role).First()...`.
