### ISSUE TITLE
Using same type as nested owned property cause "Attempted to update or delete an entity that does not exist in the store" in disconnected state.

### ISSUE THREAD

**Issue by fp-jcorriveau** [dotnet/efcore#29877]
I'm having trouble with a nested type when working in a disconnected state.
I want to be sure I'm doing things the right way.

This is a demo project I have created to show the behavior.
[nestedtype.zip](https://github.com/dotnet/efcore/files/10249976/nestedtype.zip)

```c#
// this works when tracked by EF
// >> 
// var book = dbContext.Books.First();
// book.Title.SetValue("Hyperion");
// dbContext.SaveChanges();
// <<


// this not works (simulating disconnected state)
// >>
var book = dbContext.Books.AsNoTracking().First();
book.Title.SetValue("Hyperion");

using var serviceScope = host.Services.GetRequiredService<IServiceScopeFactory>().CreateScope();
var context = serviceScope.ServiceProvider.GetRequiredService<AppDbContext>();

context.Books.Update(book);
context.SaveChanges();
// <<
```

```
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: Attempted to update or delete an entity that does not exist in the store.
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryTable`1.Update(IUpdateEntry entry, IDiagnosticsLogger`1 updateLogger)
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryStore.ExecuteTransaction(IList`1 entries, IDiagnosticsLogger`1 updateLogger)
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__107_0(DbContext _, ValueTuple`2 t)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Program.<Main>$(String[] args) in C:\Users\jcorriveau\RiderProjects\nestedtype\nestedtype\Program.cs:line 40
```

**Comment by ajcvickers** [comment]
@fp-jcorriveau The `Book` saved to the database has no `User` associated with it:

<img width="242" alt="image" src="https://user-images.githubusercontent.com/1430078/208401473-58fe3404-5b63-4899-ba06-3019c8650033.png">

However, when `Update` is called on the `Book`, it does have an associated `User`:

<img width="363" alt="image" src="https://user-images.githubusercontent.com/1430078/208401737-8980a8a0-3dba-429c-bb8c-376e6d22eb47.png">

Since `Update` is called, that `User` is marked as Modified:

```
Book {Id: 1} Modified
  Id: 1 PK
  Isbn: {BookId: 1}
  Title: {BookId: 1}
Editable<Isbn> {BookId: 1} Modified
  BookId: 1 PK FK
  ModifiedOn: <null> Modified
  Value: '0553283685' Modified
  ModifiedBy: <null>
Editable<string> {BookId: 1} Modified
  BookId: 1 PK FK
  ModifiedOn: '12/19/2022 10:09:19 AM +00:00' Modified
  Value: 'Hyperion' Modified
  ModifiedBy: {EditableBookId: 1}
Editable<string>.ModifiedBy#User {EditableBookId: 1} Modified
  EditableBookId: 1 PK FK
  Id: 'test123' Modified
  Name: 'Testing User' Modified
```

EF thus attempts to update `User` in the database, but it doesn't exist.

The code is doing some strange things with owned entities, and I'm not sure what the intention is, but if `User` is supposed to be inserted, then it needs to be marked as Added.

**Comment by fp-jcorriveau** [comment]
Thanks, I see things are not done correctly on our side then... This User is just a kind of value object that need to be saved in 2 columns, it should not be considered as an entity with an Id, but as 2 properties of the table.

**Comment by ajcvickers** [comment]
@fp-jcorriveau 

> This User is just a kind of value object that needs to be saved in 2 columns, it should not be considered as an entity with an Id, but as 2 properties of the table.

This is why owned types should not be used to represent value objects. See [https://learn.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations#examples](https://learn.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations#examples) and #9906.

**Comment by fp-jcorriveau** [comment]
Being able to map a type to multiple columns is really what we are looking for!
