### ISSUE TITLE
FirstOrDefault on DateTime column projection throws SqlException "The conversion of a varchar data type to a datetime data type resulted in an out-of-range valued" when sequence contains 0 items

### ISSUE THREAD

**Issue by janseris** [dotnet/efcore#29893]
Bug: EF Core generates SQL which cannot be processed by SQL Server when `.FirstOrDefault()` is used on `DateTime`.

The query fails when the subquery sequence contains no items (thus `.FirstOrDefault()` results in C# `default(DateTime)` is used to generate SQL).

`SELECT CONVERT(DATETIME, '0001-01-01T00:00:00.000') result;`

SQL Server Express 2019 collation `SQL_Latin1_General_CP1_CI_AS` result: error
SQL Server Express 2019 collation `Czech_CI_AS` result: error
SQL Server 2012 collation `SQL_Latin1_General_CP1_CI_AS` result: error

This query corresponds to a part of the SQL query generated by EF:
`COALESCE(sql subquery, '0001-01-01T00:00:00.000')`

`SELECT CONVERT(DATETIME, '0001-01-01T00:00:00.000') result;`

SQL Server Express 2019 collation `SQL_Latin1_General_CP1_CI_AS` result: error
SQL Server Express 2019 collation `Czech_CI_AS` result: error
SQL Server 2012 collation `SQL_Latin1_General_CP1_CI_AS` result: error

I think that the issue is that SQL Server supports only DateTime January 1, 1753 and higher.
This means that default(DateTime) from C# produces an error (out of range).
https://learn.microsoft.com/en-us/sql/t-sql/data-types/datetime-transact-sql?redirectedfrom=MSDN&view=sql-server-ver16

Result in EF Core 6:
`SqlException  The conversion of a varchar data type to a datetime data type resulted in an out-of-range value.`

------------------

My SQL Server details:

SQL Server 2012
- version: `11.0.7507.2` (latest patch - patch date 2021-01-12).
- collation: `Czech_CI_AS`
- database collation: `SQL_Latin1_General_CP1_CI_AS`

SQL Server Express 2019:
- version: `15.0.2095.3`
- collation:  `Czech_CI_AS`
- database collation: `Czech_CI_AS` (and also tested when changed collation to `SQL_Latin1_General_CP1_CI_AS`)

EF Core Power tools generates this code in DbContext when generated from SQL Server 2012 connection string:
`modelBuilder.UseCollation("SQL_Latin1_General_CP1_CI_AS");`
This line, however, does not affect the issue.

Code (C#):
[EF Core report.zip](https://github.com/dotnet/efcore/files/10262039/EF.Core.report.zip)

Affected code (function `GetAll` class `Tempus.RSD.Data.DAOs.BOZP.ZaznamBOZPDAO`):

```
var view = db.ZAZNAM
                    .Include(z => z.Typ)
                    .Include(z => z.ZAZNAM_KONTROLY_BOZP).ThenInclude(z => z.VyhodnoceniKontrolyBOZP)
                    .Include(z => z.User)
                    .Include(z => z.ZAZNAM_KONTROLY_BOZP).ThenInclude(z => z.Workflowable).ThenInclude(w => w.Stav) //název stavu
                    .Include(z => z.ZAZNAM_KONTROLY_BOZP).ThenInclude(z => z.Workflowable).ThenInclude(w => w.ZAZNAM_ZMENY_STAVU).ThenInclude(z => z.StavDo).ThenInclude(s => s.STAV_ZAZNAMU_BOZP) //datum odstranění
                    .Include(z => z.ZAZNAM_KONTROLY_BOZP.Stavba)
                    .Include(z => z.ZAZNAM_KONTROLY_BOZP.StavebniObjekt)
                    .Include(z => z.Fotoable)
                    .Include(z => z.Prilohable)
                    .Include(z => z.InverseParent);
                var query =
                    from z in view
                    where z.Deleted == false
                    where stavbyIDs.Contains(z.ZAZNAM_KONTROLY_BOZP.StavbaID)
                    select new ZaznamBOZPGridRow
                    {
                        ID = z.ID,
                        Typ = z.Typ.Nazev,
                        Autor = z.User.PERSONNAME,
                        Datum = z.Datum,
                        Popis = z.Popis,
                        ParentID = z.ParentID,
                        ChildrenID = (from c in z.InverseParent
                                      select c.ID).ToList(),
                        FotoableID = z.FotoableID,
                        PrilohableID = z.PrilohableID,
                        PocetFotek = z.Fotoable.FOTO.Count(),
                        PocetPriloh = z.Prilohable.PRILOHA.Count(),

                        Stav = z.ZAZNAM_KONTROLY_BOZP.Workflowable.Stav.Nazev,
                        WorkflowableID = z.ZAZNAM_KONTROLY_BOZP.WorkflowableID,

                        Stavba = z.ZAZNAM_KONTROLY_BOZP.Stavba.Name,
                        StavebniObjekt = z.ZAZNAM_KONTROLY_BOZP.StavebniObjekt.NAME,
                        VlastniNazevStavby = z.ZAZNAM_KONTROLY_BOZP.VlastniNazevStavby,
                        Ucastnici = z.ZAZNAM_KONTROLY_BOZP.Ucastnici,
                        PozadovaneDatumOdstraneni = z.ZAZNAM_KONTROLY_BOZP.PozadovaneDatumOdstraneni,
                        ProducentNeshody = z.ZAZNAM_KONTROLY_BOZP.ProducentNeshody,
                        **DatumOdstraneni = (from zaznamZmenyStavu in z.ZAZNAM_KONTROLY_BOZP.Workflowable.ZAZNAM_ZMENY_STAVU
                                           where zaznamZmenyStavu.StavDo.STAV_ZAZNAMU_BOZP.UrcujeDatumVyporadani == true
                                           select zaznamZmenyStavu.Datum).FirstOrDefault(),**
                        DatumKontroly = z.ZAZNAM_KONTROLY_BOZP.DatumKontroly,
                        Vyhodnoceni = z.ZAZNAM_KONTROLY_BOZP.VyhodnoceniKontrolyBOZP.Nazev
                    };
                return query.ToList();
```

The query fails with the error (the error code is actually executed) in the following situation:
- table `ZAZNAM` contains some rows and at least one of them contains zero items in the collection z.ZAZNAM_KONTROLY_BOZP.Workflowable.ZAZNAM_ZMENY_STAVU
  - this situation makes the `COALESCE` with `default(DateTime)` to be actually executed

Generated SQL:
```
SELECT [z].[ID], [c].[Nazev], [p].[PERSONNAME], [z].[Datum], [z].[Popis], [z].[ParentID], [z0].[ZaznamID], [c].[ID], [p].[PERSONID], [f].[ID], [p0].[ID], [w].[ID], [s].[ID], [c0].[ID], [c1].[ID], [v].[ID], [z1].[ID], [z].[FotoableID], [z].[PrilohableID], (
          SELECT COUNT(*)
          FROM [new].[FOTO] AS [f0]
          WHERE [f].[ID] = [f0].[FotoableID]), (
          SELECT COUNT(*)
          FROM [new].[PRILOHA] AS [p1]
          WHERE [p0].[ID] = [p1].[PrilohableID]), [s].[Nazev], [z0].[WorkflowableID], [c0].[Name], [c1].[NAME], [z0].[VlastniNazevStavby], [z0].[Ucastnici], [z0].[PozadovaneDatumOdstraneni], [z0].[ProducentNeshody], COALESCE((
          SELECT TOP(1) [z2].[Datum]
          FROM [new].[ZAZNAM_ZMENY_STAVU] AS [z2]
          INNER JOIN [new].[STAV] AS [s0] ON [z2].[StavDoID] = [s0].[ID]
          LEFT JOIN [new].[STAV_ZAZNAMU_BOZP] AS [s1] ON [s0].[ID] = [s1].[StavID]
          WHERE ([w].[ID] IS NOT NULL) AND [w].[ID] = [z2].[WorkflowableID] AND [s1].[UrcujeDatumVyporadani] = CAST(1 AS bit)), '0001-01-01T00:00:00.000'), [z0].[DatumKontroly], [v].[Nazev]
      FROM [new].[ZAZNAM] AS [z]
      LEFT JOIN [new].[ZAZNAM_KONTROLY_BOZP] AS [z0] ON [z].[ID] = [z0].[ZaznamID]
      INNER JOIN [new].[C_TYP_ZAZNAMU] AS [c] ON [z].[TypID] = [c].[ID]
      INNER JOIN [PERSONAL] AS [p] ON [z].[UserID] = [p].[PERSONID]
      INNER JOIN [new].[FOTOABLE] AS [f] ON [z].[FotoableID] = [f].[ID]
      INNER JOIN [new].[PRILOHABLE] AS [p0] ON [z].[PrilohableID] = [p0].[ID]
      LEFT JOIN [new].[WORKFLOWABLE] AS [w] ON [z0].[WorkflowableID] = [w].[ID]
      LEFT JOIN [new].[STAV] AS [s] ON [w].[StavID] = [s].[ID]
      LEFT JOIN [C_STAVBA] AS [c0] ON [z0].[StavbaID] = [c0].[ID]
      LEFT JOIN [C_SO] AS [c1] ON [z0].[StavebniObjektID] = [c1].[ID]
      LEFT JOIN [new].[VYHODNOCENI_KONTROLY_BOZP] AS [v] ON [z0].[VyhodnoceniKontrolyBOZPID] = [v].[ID]
      LEFT JOIN [new].[ZAZNAM] AS [z1] ON [z].[ID] = [z1].[ParentID]
      WHERE [z].[Deleted] = CAST(0 AS bit) AND [z0].[StavbaID] IN (1, 11, 13, 29, 31)
      ORDER BY [z].[ID], [z0].[ZaznamID], [c].[ID], [p].[PERSONID], [f].[ID], [p0].[ID], [w].[ID], [s].[ID], [c0].[ID], [c1].[ID], [v].[ID]
```

Without the date subquery (does not produce the error because the COALESCE datetime part is not present):
![generated SQL without date](https://user-images.githubusercontent.com/64279914/208501463-d2e0fbb2-a0a5-4909-8ef4-84b3f5ab4f06.png)

### Stack traces

```
 Microsoft.Data.SqlClient.SqlException (0x80131904): The conversion of a varchar data type to a datetime data type resulted in an out-of-range value.
         at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
         at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
         at Microsoft.Data.SqlClient.SqlDataReader.Read()
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
         at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
         at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
         at Tempus.RSD.Data.DAOs.BOZP.ZaznamBOZPDAO.GetAll(List`1 stavbyIDs) in C:\Users\janse\Desktop\prace\Tempus.RSD.Backend\Tempus.RSD.Data\DAOs\BOZP\ZaznamBOZPDAO.cs:line 164
Error Number:242,State:3,Class:16
```

### Provider and version information

EF Core version: 
Entity Framework Core Power Tools   2.5
Microsoft.EntityFrameworkCore.SqlServer 7.0.0
Database provider: (Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (.NET 6.0)
Operating system: Windows 10 Home 22H2 build 19045.2364
IDE: Visual Studio 2022 17.4.2

**Comment by ErikEJ** [comment]
Different schemas between the two databases?

**Comment by janseris** [comment]
> Different schemas between the two databases?

No. The schema is identical.

**Comment by janseris** [comment]
Changing the local database collation to SQL_Latin1_General_CP1_CI_AS did not create the error with the local database.

**Comment by janseris** [comment]
A workaround exists for the issue - avoid using the default(DateTime) which is converted to `'0001-01-01T00:00:00.000'` which then unsuccessfully parsed to `datetime` by the SQL Server 2012.

```
 DatumOdstraneni = (from zaznamZmenyStavu in z.ZAZNAM_KONTROLY_BOZP.Workflowable.ZAZNAM_ZMENY_STAVU
                                           where zaznamZmenyStavu.StavDo.STAV_ZAZNAMU_BOZP.UrcujeDatumVyporadani == true
                                           select new { Datum = zaznamZmenyStavu.Datum }).FirstOrDefault().Datum,
```

**Comment by ajcvickers** [comment]
@janseris If possible `datetime2` should be used. Otherwise this has the same root cause as #27684 and several other issues, for which #17783 is tracking a possible solution.
