### ISSUE TITLE
Getting an error when building bundle in Dockerfile

### ISSUE THREAD

**Issue by aradalvand** [dotnet/efcore#29927]
Using EF Core version 7.0.1, I have the following Dockerfile that's used to create the EF migration bundle:
```dockerfile
FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine AS builder
WORKDIR /app
COPY .config/dotnet-tools.json .config/
RUN dotnet tool restore
COPY *.csproj .
RUN dotnet restore -v n
COPY . .
RUN dotnet ef migrations bundle -o out -v

FROM mcr.microsoft.com/dotnet/runtime:7.0-alpine
WORKDIR /app
COPY --from=builder /app/out/efbundle .
CMD exec ./efbundle --connection $CONNECTION_STRING
```

When the `RUN dotnet ef migrations bundle -o out -v` instruction is being run, I get the following error:

```
#15 11.13 Building bundle...
#15 11.14 dotnet publish --runtime alpine.3.16-x64 --output /tmp/rdhr45rd.dri/publish --no-self-contained
#15 11.95 MSBuild version 17.4.0+18d5aef85 for .NET
#15 12.55   Determining projects to restore...
#15 13.54   Restored /app/backend.csproj (in 411 ms).
#15 13.55   Restored /tmp/rdhr45rd.dri/out.csproj (in 411 ms).
#15 14.26 /usr/share/dotnet/sdk/7.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1136,5): warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used. [/app/backend.csproj]
#15 14.32 /usr/share/dotnet/sdk/7.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(448,5): error NETSDK1112: The runtime pack for Microsoft.NETCore.App.Runtime.linux-musl-x64 was not downloaded. Try running a NuGet restore with the RuntimeIdentifier 'linux-musl-x64'. [/app/backend.csproj]
#15 14.32 /usr/share/dotnet/sdk/7.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(448,5): error NETSDK1112: The runtime pack for Microsoft.AspNetCore.App.Runtime.linux-musl-x64 was not downloaded. Try running a NuGet restore with the RuntimeIdentifier 'linux-musl-x64'. [/app/backend.csproj]
#15 14.38 Microsoft.EntityFrameworkCore.Tools.CommandException: Build failed. Use --verbose to see errors.
#15 14.38    at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsBundleCommand.Execute(String[] args)
#15 14.38    at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0(String[] args)
#15 14.38    at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
#15 14.38    at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
#15 14.38 Build failed. Use --verbose to see errors.
```

I'm assuming this is a bug in the bundle builder? I have no idea what it means or what I should do.

Thank you.

**Comment by aradalvand** [comment]
It seems as though the problem would go away if I set the`--use-current-runtime` flag for the `dotnet-restore` command.
But isn't that the default? This sounds strange to me, why would that flag be necessary in this case?

Thanks.

**Comment by aradalvand** [comment]
One other little question I had is why does the bundle need the `aspnet` runtime? If the final stage in the Dockerfile is based on `mcr.microsoft.com/dotnet/runtime:7.0-alpine` (instead of `mcr.microsoft.com/dotnet/aspnet:7.0-alpine`), it wouldn't actually work, if you try to run the executable it will yield the following error:
```
You must install or update .NET to run this application.

App: /app/efbundle
Architecture: x64
Framework: 'Microsoft.AspNetCore.App', version '7.0.0' (x64)
.NET location: /usr/share/dotnet

No frameworks were found.

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=7.0.0&arch=x64&rid=alpine.3.16-x64
```

Does the migrator always need the ASP.NET runtime or only when the original application is an ASP.NET Core one?

**Comment by aradalvand** [comment]
Know you guys are busy but I'd appreciate a pointer, thank you.

**Comment by bricelam** [comment]
Hmm, this part looks suspicious in the output: `--runtime alpine.3.16-x64`

Does it work if you specify `--target-runtime linux-musl-x64` on `dotnet ef migrations bundle`?

**Comment by ajcvickers** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by aradalvand** [comment]
Sorry I missed this.

> Does it work if you specify --target-runtime linux-musl-x64 on dotnet ef migrations bundle?

@bricelam Yes it does seem to work.
