### ISSUE TITLE
ArgumentOutOfRangeException in SqliteConnectionFactory.PruneCallback

### ISSUE THREAD

**Issue by BioTurboNick** [dotnet/efcore#29952]
This was reported by Microsoft AppCenter on a running device in the wild, but the stack trace does not contain any of my user code.

```C#
Xamarin Exception Stack:
System.ArgumentOutOfRangeException: ArgumentOutOfRange_IndexMustBeLess Arg_ParamName_Name, index
  at System.Collections.Generic.List`1[[Microsoft.Data.Sqlite.SqliteConnectionPoolGroup, Microsoft.Data.Sqlite, Version=7.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].get_Item(Int32 )
  at Microsoft.Data.Sqlite.SqliteConnectionFactory.PruneCallback(Object _)
  at System.Threading.TimerQueueTimer.<>c.<.cctor>b__27_0(Object )
  at System.Threading.ExecutionContext.RunInternal(ExecutionContext , ContextCallback , Object )
  at System.Threading.ExecutionContext.RunInternal(ExecutionContext , ContextCallback , Object )
  at System.Threading.TimerQueueTimer.CallCallback(Boolean )
  at System.Threading.TimerQueueTimer.Fire(Boolean )
  at System.Threading.TimerQueue.FireNextTimers()
  at System.Threading.TimerQueue.System.Threading.IThreadPoolWorkItem.Execute()
  at System.Threading.ThreadPoolWorkQueue.Dispatch()
  at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
  at System.Threading.Thread.StartCallback()
```
Microsoft.Data.Sqlite version: 7.0.1
Target framework: .NET 7.0
Operating system: Android 12

I'm guessing there needs to be a lock around `_idlePoolGroups` usage?

**Comment by FM1973** [comment]
I got the same exception from time to time.
Android 11+ as well as IOS 14+

**Comment by FM1973** [comment]
Is there anything we can do as a workaround? Our testers (app) get this exception at least once or twice a day which crashes the app.

**Comment by ErikEJ** [comment]
@FM1973 maybe disable connection pooling?

**Comment by FM1973** [comment]
@ErikEJ 
Thanks for your suggestion.
How can I disable pooling when using "UseSqlite" like this:
`builder.Services.AddDbContext<LocalDbContext>(o => o.UseSqlite($"Filename={databasePath}", sqlLiteOptions => { sqlLiteOptions.CommandTimeout(120);}));`

I can´t find a property for disabling pooling on the options builder.

I´m sure this can be easily done, but I´m too dumb finding it :)

**Comment by ErikEJ** [comment]
@FM1973  Just read the manual: https://learn.microsoft.com/en-us/dotnet/standard/data/sqlite/connection-strings#pooling 

     o.UseSqlite($"Filename={databasePath};Pooling=false"

**Comment by FM1973** [comment]
@ErikEJ 
Heck... I´m sorry. Thanks a lot!

**Comment by FM1973** [comment]
Ok, disabling the connection pool doesn´t help.
The same error still occurs.

**Comment by symbiogenesis** [comment]
I'm seeing this as well. Also using 7.0.1 on Android. 

Maybe rolling back to 7.0.0 is the workaround.

**Comment by ajcvickers** [comment]
Note from triage: bring to Tactics for servicing.
