### ISSUE TITLE
EFCore migration for encrypted sqlite throws exception

### ISSUE THREAD

**Issue by iplusMario** [dotnet/efcore#30179]
After upgrading entity framework to a version >= 6.0.11 using migration with encrypted sqlite throws unhandled exception. 

```Attempted to read or write protected memory. This is often an indication that other memory is corrupt.``` 

### Include provider and version information

EF Core version: > 6.0.10 
Database provider: Microsoft.EntityFrameworkCore.Sqlite.Core >= 6.0.11 and SQLitePCLRaw.bundle_e_sqlcipher >= 2.1.0
Target framework: (e.g. .NET 6.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.4)

Simple test project
[EFCoreEncryptionTest.zip](https://github.com/dotnet/efcore/files/10544306/EFCoreEncryptionTest.zip)

Possible related to #28774 #28966

**Comment by ajcvickers** [comment]
Note for triage: still repros on latest daily build.

/cc @bricelam

**Comment by ajcvickers** [comment]
Note for triage: only throws when `context.Database.Migrate()` is called from application code. Minimal repro:

```C#
using var dbContext = new TestDbContext();

dbContext.Database.EnsureDeleted();
//dbContext.Database.EnsureCreated();
dbContext.Database.Migrate();

for (int i = 0; i < 3; i++)
{
    dbContext.TestModels.Add(new TestModel());
    await dbContext.SaveChangesAsync();
}

public class TestDbContext : DbContext
{
    public DbSet<TestModel> TestModels { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .LogTo(Console.WriteLine, LogLevel.Trace)
            .UseSqlite(@"Data Source=C:\local\TestDatabase2.db;Cache=Shared;Password=TestTest;");
}

public class TestModel
{
    public long Id { get; set; }
}
```

Logs:
```
C:\Users\ajcvi\AppData\Local\JetBrains\Toolbox\apps\Rider\ch-0\223.8617.53\plugins\dpa\DotFiles\JetBrains.DPA.Runner.exe --handle=15744 --backend-pid=21712 --etw-collect-flags=3 --detach-event-name=dpa.detach.15744 C:/local/code/repros/EFCoreEncryptionTest/EFCoreEncryptionTest/bin/Debug/net6.0/EFCoreEncryptionTest.exe
dbug: 2/3/2023 17:16:11.906 CoreEventId.ContextInitialized[10403] (Microsoft.EntityFrameworkCore.Infrastructure)
      Entity Framework Core 8.0.0-preview.2.23081.2 initialized 'TestDbContext' using provider 'Microsoft.EntityFrameworkCore.Sqlite:8.0.0-preview.2.23081.2' with options: None
dbug: 2/3/2023 17:16:11.931 RelationalEventId.ConnectionCreating[20005] (Microsoft.EntityFrameworkCore.Database.Connection)
      Creating DbConnection.
dbug: 2/3/2023 17:16:11.938 RelationalEventId.ConnectionCreated[20006] (Microsoft.EntityFrameworkCore.Database.Connection)
      Created DbConnection. (7ms).
dbug: 2/3/2023 17:16:11.942 RelationalEventId.ConnectionOpening[20000] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opening connection to database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:11.950 RelationalEventId.ConnectionError[20004] (Microsoft.EntityFrameworkCore.Database.Connection)
      An error occurred using the connection to database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:11.952 RelationalEventId.ConnectionDisposing[20007] (Microsoft.EntityFrameworkCore.Database.Connection)
      Disposing connection to database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:11.954 RelationalEventId.ConnectionDisposed[20008] (Microsoft.EntityFrameworkCore.Database.Connection)
      Disposed connection to database 'main' on server 'C:\local\TestDatabase2.db' (0ms).
dbug: 2/3/2023 17:16:11.958 RelationalEventId.ConnectionCreating[20005] (Microsoft.EntityFrameworkCore.Database.Connection)
      Creating DbConnection.
dbug: 2/3/2023 17:16:11.958 RelationalEventId.ConnectionCreated[20006] (Microsoft.EntityFrameworkCore.Database.Connection)
      Created DbConnection. (0ms).
dbug: 2/3/2023 17:16:11.958 RelationalEventId.MigrateUsingConnection[20400] (Microsoft.EntityFrameworkCore.Migrations)
      Migrating using database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:11.958 RelationalEventId.ConnectionCreating[20005] (Microsoft.EntityFrameworkCore.Database.Connection)
      Creating DbConnection.
dbug: 2/3/2023 17:16:11.959 RelationalEventId.ConnectionCreated[20006] (Microsoft.EntityFrameworkCore.Database.Connection)
      Created DbConnection. (0ms).
dbug: 2/3/2023 17:16:11.960 RelationalEventId.ConnectionOpening[20000] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opening connection to database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:11.961 RelationalEventId.ConnectionError[20004] (Microsoft.EntityFrameworkCore.Database.Connection)
      An error occurred using the connection to database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:11.961 RelationalEventId.ConnectionDisposing[20007] (Microsoft.EntityFrameworkCore.Database.Connection)
      Disposing connection to database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:11.962 RelationalEventId.ConnectionDisposed[20008] (Microsoft.EntityFrameworkCore.Database.Connection)
      Disposed connection to database 'main' on server 'C:\local\TestDatabase2.db' (0ms).
dbug: 2/3/2023 17:16:11.963 RelationalEventId.ConnectionCreating[20005] (Microsoft.EntityFrameworkCore.Database.Connection)
      Creating DbConnection.
dbug: 2/3/2023 17:16:11.963 RelationalEventId.ConnectionCreated[20006] (Microsoft.EntityFrameworkCore.Database.Connection)
      Created DbConnection. (0ms).
dbug: 2/3/2023 17:16:11.964 RelationalEventId.ConnectionOpening[20000] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opening connection to database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:11.965 RelationalEventId.ConnectionError[20004] (Microsoft.EntityFrameworkCore.Database.Connection)
      An error occurred using the connection to database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:11.965 RelationalEventId.ConnectionDisposing[20007] (Microsoft.EntityFrameworkCore.Database.Connection)
      Disposing connection to database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:11.966 RelationalEventId.ConnectionDisposed[20008] (Microsoft.EntityFrameworkCore.Database.Connection)
      Disposed connection to database 'main' on server 'C:\local\TestDatabase2.db' (0ms).
dbug: 2/3/2023 17:16:11.967 RelationalEventId.ConnectionOpening[20000] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opening connection to database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:11.985 RelationalEventId.ConnectionOpened[20001] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opened connection to database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:11.991 RelationalEventId.CommandCreating[20103] (Microsoft.EntityFrameworkCore.Database.Command)
      Creating DbCommand for 'ExecuteNonQuery'.
dbug: 2/3/2023 17:16:11.996 RelationalEventId.CommandCreated[20104] (Microsoft.EntityFrameworkCore.Database.Command)
      Created DbCommand for 'ExecuteNonQuery' (4ms).
dbug: 2/3/2023 17:16:11.997 RelationalEventId.CommandInitialized[20106] (Microsoft.EntityFrameworkCore.Database.Command)
      Initialized DbCommand for 'ExecuteNonQuery' (7ms).
dbug: 2/3/2023 17:16:12.001 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      PRAGMA journal_mode = 'wal';
info: 2/3/2023 17:16:12.430 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (429ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      PRAGMA journal_mode = 'wal';
dbug: 2/3/2023 17:16:12.432 RelationalEventId.ConnectionClosing[20002] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closing connection to database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:12.435 RelationalEventId.ConnectionClosed[20003] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closed connection to database 'main' on server 'C:\local\TestDatabase2.db' (2ms).
dbug: 2/3/2023 17:16:12.531 RelationalEventId.CommandCreating[20103] (Microsoft.EntityFrameworkCore.Database.Command)
      Creating DbCommand for 'ExecuteNonQuery'.
dbug: 2/3/2023 17:16:12.531 RelationalEventId.CommandCreated[20104] (Microsoft.EntityFrameworkCore.Database.Command)
      Created DbCommand for 'ExecuteNonQuery' (0ms).
dbug: 2/3/2023 17:16:12.531 RelationalEventId.CommandInitialized[20106] (Microsoft.EntityFrameworkCore.Database.Command)
      Initialized DbCommand for 'ExecuteNonQuery' (0ms).
dbug: 2/3/2023 17:16:12.532 RelationalEventId.ConnectionOpening[20000] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opening connection to database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:12.533 RelationalEventId.ConnectionOpened[20001] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opened connection to database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:12.534 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE "__EFMigrationsHistory" (
          "MigrationId" TEXT NOT NULL CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY,
          "ProductVersion" TEXT NOT NULL
      );
info: 2/3/2023 17:16:12.538 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE "__EFMigrationsHistory" (
          "MigrationId" TEXT NOT NULL CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY,
          "ProductVersion" TEXT NOT NULL
      );
dbug: 2/3/2023 17:16:12.539 RelationalEventId.ConnectionClosing[20002] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closing connection to database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:12.540 RelationalEventId.ConnectionClosed[20003] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closed connection to database 'main' on server 'C:\local\TestDatabase2.db' (0ms).
dbug: 2/3/2023 17:16:12.541 RelationalEventId.ConnectionCreating[20005] (Microsoft.EntityFrameworkCore.Database.Connection)
      Creating DbConnection.
dbug: 2/3/2023 17:16:12.541 RelationalEventId.ConnectionCreated[20006] (Microsoft.EntityFrameworkCore.Database.Connection)
      Created DbConnection. (0ms).
dbug: 2/3/2023 17:16:12.542 RelationalEventId.ConnectionOpening[20000] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opening connection to database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:12.543 RelationalEventId.ConnectionOpened[20001] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opened connection to database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:12.544 RelationalEventId.ConnectionDisposing[20007] (Microsoft.EntityFrameworkCore.Database.Connection)
      Disposing connection to database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:12.544 RelationalEventId.ConnectionDisposed[20008] (Microsoft.EntityFrameworkCore.Database.Connection)
      Disposed connection to database 'main' on server 'C:\local\TestDatabase2.db' (0ms).
dbug: 2/3/2023 17:16:12.549 RelationalEventId.CommandCreating[20103] (Microsoft.EntityFrameworkCore.Database.Command)
      Creating DbCommand for 'ExecuteScalar'.
dbug: 2/3/2023 17:16:12.549 RelationalEventId.CommandCreated[20104] (Microsoft.EntityFrameworkCore.Database.Command)
      Created DbCommand for 'ExecuteScalar' (0ms).
dbug: 2/3/2023 17:16:12.550 RelationalEventId.CommandInitialized[20106] (Microsoft.EntityFrameworkCore.Database.Command)
      Initialized DbCommand for 'ExecuteScalar' (0ms).
dbug: 2/3/2023 17:16:12.551 RelationalEventId.ConnectionOpening[20000] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opening connection to database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:12.551 RelationalEventId.ConnectionOpened[20001] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opened connection to database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:12.552 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT COUNT(*) FROM "sqlite_master" WHERE "name" = '__EFMigrationsHistory' AND "type" = 'table';
info: 2/3/2023 17:16:12.555 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT COUNT(*) FROM "sqlite_master" WHERE "name" = '__EFMigrationsHistory' AND "type" = 'table';
dbug: 2/3/2023 17:16:12.555 RelationalEventId.ConnectionClosing[20002] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closing connection to database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:12.556 RelationalEventId.ConnectionClosed[20003] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closed connection to database 'main' on server 'C:\local\TestDatabase2.db' (0ms).
dbug: 2/3/2023 17:16:12.558 RelationalEventId.CommandCreating[20103] (Microsoft.EntityFrameworkCore.Database.Command)
      Creating DbCommand for 'ExecuteReader'.
dbug: 2/3/2023 17:16:12.558 RelationalEventId.CommandCreated[20104] (Microsoft.EntityFrameworkCore.Database.Command)
      Created DbCommand for 'ExecuteReader' (0ms).
dbug: 2/3/2023 17:16:12.559 RelationalEventId.CommandInitialized[20106] (Microsoft.EntityFrameworkCore.Database.Command)
      Initialized DbCommand for 'ExecuteReader' (0ms).
dbug: 2/3/2023 17:16:12.559 RelationalEventId.ConnectionOpening[20000] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opening connection to database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:12.560 RelationalEventId.ConnectionOpened[20001] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opened connection to database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:12.561 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT "MigrationId", "ProductVersion"
      FROM "__EFMigrationsHistory"
      ORDER BY "MigrationId";
info: 2/3/2023 17:16:12.562 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT "MigrationId", "ProductVersion"
      FROM "__EFMigrationsHistory"
      ORDER BY "MigrationId";
dbug: 2/3/2023 17:16:12.564 RelationalEventId.DataReaderClosing[20301] (Microsoft.EntityFrameworkCore.Database.Command)
      Closing data reader to 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:12.566 RelationalEventId.DataReaderDisposing[20300] (Microsoft.EntityFrameworkCore.Database.Command)
      A data reader for 'main' on server 'C:\local\TestDatabase2.db' is being disposed after spending 1ms reading results.
dbug: 2/3/2023 17:16:12.567 RelationalEventId.ConnectionClosing[20002] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closing connection to database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:12.567 RelationalEventId.ConnectionClosed[20003] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closed connection to database 'main' on server 'C:\local\TestDatabase2.db' (0ms).
info: 2/3/2023 17:16:12.578 RelationalEventId.MigrationApplying[20402] (Microsoft.EntityFrameworkCore.Migrations)
      Applying migration '20230203170919_One'.
dbug: 2/3/2023 17:16:12.591 RelationalEventId.ConnectionOpening[20000] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opening connection to database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:12.591 RelationalEventId.ConnectionOpened[20001] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opened connection to database 'main' on server 'C:\local\TestDatabase2.db'.
dbug: 2/3/2023 17:16:12.593 RelationalEventId.TransactionStarting[20209] (Microsoft.EntityFrameworkCore.Database.Transaction)
      Beginning transaction with isolation level 'Unspecified'.
dbug: 2/3/2023 17:16:12.597 RelationalEventId.TransactionStarted[20200] (Microsoft.EntityFrameworkCore.Database.Transaction)
      Began transaction with isolation level 'Serializable'.
dbug: 2/3/2023 17:16:12.598 RelationalEventId.CommandCreating[20103] (Microsoft.EntityFrameworkCore.Database.Command)
      Creating DbCommand for 'ExecuteNonQuery'.
dbug: 2/3/2023 17:16:12.598 RelationalEventId.CommandCreated[20104] (Microsoft.EntityFrameworkCore.Database.Command)
      Created DbCommand for 'ExecuteNonQuery' (0ms).
dbug: 2/3/2023 17:16:12.599 RelationalEventId.CommandInitialized[20106] (Microsoft.EntityFrameworkCore.Database.Command)
      Initialized DbCommand for 'ExecuteNonQuery' (1ms).
dbug: 2/3/2023 17:16:12.599 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE "TestModels" (
          "Id" INTEGER NOT NULL CONSTRAINT "PK_TestModels" PRIMARY KEY AUTOINCREMENT
      );
info: 2/3/2023 17:16:12.601 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE "TestModels" (
          "Id" INTEGER NOT NULL CONSTRAINT "PK_TestModels" PRIMARY KEY AUTOINCREMENT
      );
dbug: 2/3/2023 17:16:12.602 RelationalEventId.CommandCreating[20103] (Microsoft.EntityFrameworkCore.Database.Command)
      Creating DbCommand for 'ExecuteNonQuery'.
dbug: 2/3/2023 17:16:12.602 RelationalEventId.CommandCreated[20104] (Microsoft.EntityFrameworkCore.Database.Command)
      Created DbCommand for 'ExecuteNonQuery' (0ms).
dbug: 2/3/2023 17:16:12.603 RelationalEventId.CommandInitialized[20106] (Microsoft.EntityFrameworkCore.Database.Command)
      Initialized DbCommand for 'ExecuteNonQuery' (1ms).
dbug: 2/3/2023 17:16:12.604 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
      VALUES ('20230203170919_One', '8.0.0-preview.2.23081.2');
info: 2/3/2023 17:16:12.605 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
      VALUES ('20230203170919_One', '8.0.0-preview.2.23081.2');
dbug: 2/3/2023 17:16:12.608 RelationalEventId.TransactionCommitting[20210] (Microsoft.EntityFrameworkCore.Database.Transaction)
      Committing transaction.
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at SQLitePCL.SQLite3Provider_e_sqlcipher+NativeMethods.sqlite3_step(SQLitePCL.sqlite3_stmt)
--------------------------------
   at SQLitePCL.SQLite3Provider_e_sqlcipher.SQLitePCL.ISQLite3Provider.sqlite3_step(SQLitePCL.sqlite3_stmt)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(System.Data.CommandBehavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(Microsoft.Data.Sqlite.SqliteConnection, System.String, Microsoft.Data.Sqlite.SqliteParameter[])
   at Microsoft.Data.Sqlite.SqliteTransaction.Commit()
   at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.Commit()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(System.Collections.Generic.IEnumerable`1<Microsoft.EntityFrameworkCore.Migrations.MigrationCommand>, Microsoft.EntityFrameworkCore.Storage.IRelationalConnection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(System.String)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade)
   at Program+<<Main>$>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at Program.<Main>$(System.String[])
   at Program.<Main>(System.String[])

Process finished with exit code -1,073,741,819.
```

**Comment by ajcvickers** [comment]
@iplusMario On further investigation, the behavior here is erratic, and is looking more and more like a problem with the native code. Given that "SQLitePCLRaw.bundle_e_sqlcipher " is [unofficial and unsupported](https://github.com/ericsink/SQLitePCL.raw#included-providers), this probably should be tested with the official [Zetetic](https://www.zetetic.net/) code, which is a commercial product, but is supported by them.

/cc @EricSink

**Comment by samirchakour-crossover** [comment]
I faced the same issue and spent many hours trying to understand the issue, it turned out that applying migration while using  a shared cache cause the native library to crash

if you remove the `Cache=Shared` or set the cache to default while applying the migration this should fix it even with the free version of sqlcipher.

**Comment by cheindel** [comment]
@samirchakour-crossover Thank you! After also wasting a few hours, your comment saved my day (or night). Removing "Cache=Shared" made it work with encrypted sqlite db.
