### ISSUE TITLE
PreProcess query BEFORE extracting query parameters

### ISSUE THREAD

**Issue by dotlogix** [dotnet/efcore#30208]
Hey there with the addition of the IQueryExpressionInterceptor interface I thought I can finally get rid of my custom query compiler to intercept expression trees. However the interceptor is not a real benefit at all.

I still have the problem that I want to partially rewrite the query to translate method calls to calls understandable by EF.
Consider this example:

``` csharp
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Query;
using Microsoft.EntityFrameworkCore.Query.Internal;
using Microsoft.EntityFrameworkCore.Storage;


using var dbContext = new SimpleDbContext();
var term = new SearchTerm();

dbContext
   .Set<SimpleEntity>()
   .Where(e => term.Matches(e.Name))
   .ToListAsync();

// Output:
// QueryCompiler: MemberAccess with type SearchTerm
// Interceptor: Parameter with type SearchTerm


public class SimpleEntity
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class SimpleDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);
        optionsBuilder.UseInMemoryDatabase(Guid.NewGuid().ToString());
        // Interceptor runs AFTER extracting parameters
        optionsBuilder.AddInterceptors(new Interceptor());
        
        // QueryCompiler runs BEFORE extracting parameters
        optionsBuilder.ReplaceService<IQueryCompiler, InterceptingQueryCompiler>();
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<SimpleEntity>();
    }
}

public class Interceptor : IQueryExpressionInterceptor
{
    public Expression QueryCompilationStarting(Expression queryExpression, QueryExpressionEventData eventData)
    {
        return new Visitor("Interceptor").Visit(queryExpression);
    }
}

public class InterceptingQueryCompiler : QueryCompiler
{
    public InterceptingQueryCompiler(IQueryContextFactory queryContextFactory, ICompiledQueryCache compiledQueryCache, ICompiledQueryCacheKeyGenerator compiledQueryCacheKeyGenerator, IDatabase database, IDiagnosticsLogger<DbLoggerCategory.Query> logger, ICurrentDbContext currentContext, IEvaluatableExpressionFilter evaluatableExpressionFilter, IModel model) : base(queryContextFactory, compiledQueryCache, compiledQueryCacheKeyGenerator, database, logger, currentContext, evaluatableExpressionFilter, model)
    {
    }

    public override Expression ExtractParameters(Expression query, IParameterValues parameterValues, IDiagnosticsLogger<DbLoggerCategory.Query> logger, bool parameterize = true, bool generateContextAccessors = false)
    {
        query = new Visitor("QueryCompiler").Visit(query);
        return base.ExtractParameters(query, parameterValues, logger, parameterize, generateContextAccessors);
    }
}

public class Visitor : ExpressionVisitor
{
    private readonly string _source;

    public Visitor(string source)
    {
        _source = source;
    }

    protected override Expression VisitMethodCall(MethodCallExpression node)
    {
        if (node.Method.Name != "Matches") return base.VisitMethodCall(node);

        var searchTermExpression = node.Arguments[0];
        Console.WriteLine($"{_source}: {searchTermExpression.NodeType} with type {searchTermExpression.Type}");
        return base.VisitMethodCall(node);
    }
}

public static class SearchTermExtensions
{
    public static bool Matches(this SearchTerm term, string str) => true;
}

public class SearchTerm
{
    public string Pattern { get; set; }
    public bool IgnoreCase { get; set; }
}
```

This is a very simplified example of my use case, in reality "SearchTerm" and the extension class is not under my control, so modifying them is no option. I also have many other examples where this would be incredibly useful.

What I want to do now is to translate the call to SearchTermExtensions.Matches to sth like string.Contains whcih EF CAN translate easily. Basically I want to rewrite the expression instead of translating them manually to SQL which in most use cases is not needed and far more work than just converting the call like in this case.
The problem here is that I need access to the SearchTerm to rewrite it, but what happens is, that EF extracts it as a parameter so I can't access the instance anymore.

What I need to do atm is to create my own IQueryCompiler and overwrite ExtractParameters because this is the only common entry point for query translation where you have access to the RAW unmodified query before EF does anything whith it.

It would be nice if there is a hook I could use to intercept the query BEFORE EF does anything with it. I guess this was the intended use-case for the new interface, however you still can't do anything because you can't access parameter data.

I am using EF Core 7 with an InMemoryDb for this example.
In reality I use Postgres

**Comment by dotlogix** [comment]
Btw the approach using the QueryCompiler also allows EF to still parameterize all parameters. Using the [NotParameterized] attribute would put this in the query instead which is slower and vulnerable

**Comment by roji** [comment]
> It would be nice if there is a hook I could use to intercept the query BEFORE EF does anything with it. I guess this was the intended use-case for the new interface, however you still can't do anything because you can't access parameter data.

Manipulating the query tree before parameter extraction is problematic from a performance point of view; EF's internal query cache kicks in directly after parameter extraction (so that queries with different parameter values are considered identical), and so anything happening before that would have to run for each query execution. Exposing a hook to do that would be a performance pit of failure, and we haven't really seen specific user requests or needs for that.

Regardless... Your problem seems to be that your custom Matches function accepts a custom SearchTerm, which - if I understand correctly - you need to transform into a string somehow. Rather than doing your manipulation before parameter extraction (which again is problematic perf-wise), I'd introduce a new post-processing visitor which can access the parameter on QueryContext, and do any manipulation there. That would allow your query to be cached and be much more efficient. 

Let me know if that's clear and if you need guidance on how to do this.

**Comment by dotlogix** [comment]
Hey there thanks for taking your time to answer me.

I checked this option out and I guess it could work, at least I get the original parameters with their values. However I can't really figure out how to do much with this Expression Tree. How would I attempt creating new SqlParameters and remove the one for the SearchTerm?
It would be really helpful if you could provide an example how to do this, because I guess even if I rewrite the query at that point the object would still be treated as a SqlParameter or not.

The only "NO" I have with this approach is that it is provider dependent. The Pre- and PostProcessors have factories and are not extensible atm so in each project I need to know which Provider I am using and replace it with the correct PostProcessor and Factory with the correct basetype.

And even if this is the more intended/correct way, the ExtractParameters method also runs BEFORE eahc execution of a query, so I guess it is not good but sufficient :D. Obviously I will have a performance loss, but this way I can also use the default logic of EF to parameterize and rearrange rewritten calls ;) which is also really nice.

But if you could provide me with a small example I will definetly check out if I could use this approach instead.

Thanks for your comment.

**Comment by dotlogix** [comment]
I adjusted my code to use Npgsql instead there I get this exception:

```
Unhandled exception. System.InvalidOperationException: The LINQ expression 'DbSet<SimpleEntity>()
    .Where(s => SearchTerm
        .Matches(s.Name))' could not be translated. Additional information: Translation of method 'SearchTermExtensions.Matches' failed. If this method can be mapped to your custom func
tion, see https://go.microsoft.com/fwlink/?linkid=2132413 for more information. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by i
nserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0&)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\Users\alexa\source\git\c-sharp\Projects\ConsoleApp18\ConsoleApp18\Program.cs:line 15
   at Program.<Main>$(String[] args) in C:\Users\alexa\source\git\c-sharp\Projects\ConsoleApp18\ConsoleApp18\Program.cs:line 15
   at Program.<Main>(String[] args)
```

It seams the check for unsupported methods throws before the post processor would have a chance to rewrite this correctly

**Comment by dotlogix** [comment]
And here is also the updated code to use Npgsql and all 3 ways logging to the console :)
```
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Query;
using Microsoft.EntityFrameworkCore.Query.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Npgsql.EntityFrameworkCore.PostgreSQL.Query.Internal;


await using var dbContext = new SimpleDbContext();
var term = new SearchTerm();

_ = await dbContext
   .Set<SimpleEntity>()
   .Where(e => term.Matches(e.Name))
   .ToListAsync();

// Output:
// QueryCompiler: MemberAccess with type SearchTerm
// Interceptor: Parameter with type SearchTerm


public class SimpleEntity
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class SimpleDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);
        optionsBuilder.UseNpgsql("server=localhost;database=asdf;uid=root");
        // Interceptor runs AFTER extracting parameters
        optionsBuilder.AddInterceptors(new Interceptor());
        
        // QueryCompiler runs BEFORE extracting parameters
        optionsBuilder.ReplaceService<IQueryCompiler, InterceptingQueryCompiler>();
        optionsBuilder.ReplaceService<IQueryTranslationPostprocessorFactory, QueryTranslationPostprocessorFactory>();
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<SimpleEntity>();
    }
}

public class Interceptor : IQueryExpressionInterceptor
{
    public Expression QueryCompilationStarting(Expression queryExpression, QueryExpressionEventData eventData)
    {
        return new Visitor("Interceptor").Visit(queryExpression);
    }
}

public class InterceptingQueryCompiler : QueryCompiler
{
    public InterceptingQueryCompiler(IQueryContextFactory queryContextFactory, ICompiledQueryCache compiledQueryCache, ICompiledQueryCacheKeyGenerator compiledQueryCacheKeyGenerator, IDatabase database, IDiagnosticsLogger<DbLoggerCategory.Query> logger, ICurrentDbContext currentContext, IEvaluatableExpressionFilter evaluatableExpressionFilter, IModel model) : base(queryContextFactory, compiledQueryCache, compiledQueryCacheKeyGenerator, database, logger, currentContext, evaluatableExpressionFilter, model)
    {
    }

    public override Expression ExtractParameters(Expression query, IParameterValues parameterValues, IDiagnosticsLogger<DbLoggerCategory.Query> logger, bool parameterize = true, bool generateContextAccessors = false)
    {
        query = new Visitor("QueryCompiler").Visit(query);
        return base.ExtractParameters(query, parameterValues, logger, parameterize, generateContextAccessors);
    }
}

public class Visitor : ExpressionVisitor
{
    private readonly string _source;

    public Visitor(string source)
    {
        _source = source;
    }

    protected override Expression VisitMethodCall(MethodCallExpression node)
    {
        if (node.Method.Name != "Matches") return base.VisitMethodCall(node);

        var searchTermExpression = node.Arguments[0];
        Console.WriteLine($"{_source}: {searchTermExpression.NodeType} with type {searchTermExpression.Type}");
        return base.VisitMethodCall(node);
    }
}


public class QueryTranslationPostprocessorFactory : IQueryTranslationPostprocessorFactory
{
    private readonly QueryTranslationPostprocessorDependencies _dependencies;
    private readonly RelationalQueryTranslationPostprocessorDependencies _relationalDependencies;

    public QueryTranslationPostprocessorFactory(QueryTranslationPostprocessorDependencies dependencies, RelationalQueryTranslationPostprocessorDependencies relationalDependencies)
    {
        _dependencies = dependencies;
        _relationalDependencies = relationalDependencies;
    }

    public QueryTranslationPostprocessor Create(QueryCompilationContext queryCompilationContext)
    {
        return new PostProcessor(_dependencies, _relationalDependencies, queryCompilationContext);
    }
}

public class PostProcessor : NpgsqlQueryTranslationPostprocessor {
    public PostProcessor(
        QueryTranslationPostprocessorDependencies dependencies, 
        RelationalQueryTranslationPostprocessorDependencies relationalDependencies, 
        QueryCompilationContext queryCompilationContext
    ) : base(dependencies, relationalDependencies, queryCompilationContext)
    {
    }

    public override Expression Process(Expression query) {
        query = new Visitor("PostProcessor").Visit(query);
        return base.Process(query);
    }
}

public static class SearchTermExtensions
{
    public static bool Matches([NotParameterized]this SearchTerm term, [NotParameterized]string str) => true;
}

public class SearchTerm
{
    public string Pattern { get; set; }
    public bool IgnoreCase { get; set; }
}
```

**Comment by ajcvickers** [comment]
Note from triage: we don't plan to add a hook like this, beyond what is already possible with a visitor. Changing parametrization is likely to be very difficult whatever we do, and in general it's not something we would advise applications attempt.
