### ISSUE TITLE
RazorPagesMovie Migration Fails

### ISSUE THREAD

**Issue by Suzibandit** [dotnet/efcore#30200]
## File a bug

Remember:

* Please check that the [documentation](https://docs.microsoft.com/ef/) does not explain the behavior you are seeing.
* Please search in both [open](https://github.com/dotnet/efcore/issues) and [closed](https://github.com/dotnet/efcore/issues?q=is%3Aissue+is%3Aclosed) issues to check that your bug has not already been filed.

### Include your code

To fix any bug we must first reproduce it. To make this possible, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing.

It is often impossible for us to reproduce a bug when working with only code snippets since we have to guess at the missing code. 

Use triple-tick code fences for any posted code. For example:

```C#
Console.WriteLine("Hello, World!");
```

### Include stack traces

Include the full exception message and stack trace for any exception you encounter.

Use triple-tick fences for stack traces. For example:

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at SixFour.Sub() in C:\Stuff\AllTogetherNow\SixFour\SixFour.cs:line 49
   at SixFour.Main() in C:\Stuff\AllTogetherNow\SixFour\SixFour.cs:line 54
```

### Include verbose output

Please include `--verbose` output when filing bugs about the `dotnet ef` or Package Manager Console tools.

Use triple-tick fences for tool output. For example:

```
C:\Stuff\AllTogetherNow\FiveOh>dotnet ef dbcontext list --verbose
Using project 'C:\Stuff\AllTogetherNow\FiveOh\FiveOh.csproj'.
...
Finding DbContext classes in the project...
Found DbContext 'BlogContext'.
BlogContext
```

### Include provider and version information

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 6.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by ajcvickers** [comment]
@Suzibandit Can you post the -Verbose output from running the commands?

**Comment by Suzibandit** [comment]
Hi,

Here is the output from the Add-Migration step.

PM> Add-Migration InitialCreate -verbose
Using project 'RazorPagesMovie2'.
Using startup project 'RazorPagesMovie2'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile "\\\\<server>\<share>\Users\<user>\My Documents\Development\C#\RazorPagesMovie2\RazorPagesMovie2\bin\Debug\net7.0\RazorPagesMovie2.deps.json" --additionalprobingpath C:\Users\sblpn\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig "\\\\<server>\<share>\Users\<user>\My Documents\Development\C#\RazorPagesMovie2\RazorPagesMovie2\bin\Debug\net7.0\RazorPagesMovie2.runtimeconfig.json" C:\Users\sblpn\.nuget\packages\microsoft.entityframeworkcore.tools\7.0.2\tools\netcoreapp2.0\any\ef.dll migrations add InitialCreate --json --verbose --no-color --prefix-output --assembly "\\\\<server>\<share>\Users\<user>\My Documents\Development\C#\RazorPagesMovie2\RazorPagesMovie2\bin\Debug\net7.0\RazorPagesMovie2.dll" --project "\\\\<server>\<share>\Users\<user>\My Documents\Development\C#\RazorPagesMovie2\RazorPagesMovie2\RazorPagesMovie2.csproj" --startup-assembly "\\\\<server>\<share>\Users\<user>\My Documents\Development\C#\RazorPagesMovie2\RazorPagesMovie2\bin\Debug\net7.0\RazorPagesMovie2.dll" --startup-project "\\\\<server>\<share>\Users\<user>\My Documents\Development\C#\RazorPagesMovie2\RazorPagesMovie2\RazorPagesMovie2.csproj" --project-dir "\\\\<server>\<share>\Users\<user>\My Documents\Development\C#\RazorPagesMovie2\RazorPagesMovie2\\" --language C# --configuration Debug --working-dir "Microsoft.PowerShell.Core\FileSystem::\\\\<server>\<share>\Users\<user>\My Documents\Development\C#\RazorPagesMovie2" --root-namespace RazorPagesMovie2 --nullable
The specified deps.json [\\\\<server>\<share>\Users\<user>\My Documents\Development\C#\RazorPagesMovie2\RazorPagesMovie2\bin\Debug\net7.0\RazorPagesMovie2.deps.json] does not exist
PM>

The file does exist.

I think

"\\\\<server>\<share>\Users\<user>\My Documents\Development\C#\RazorPagesMovie2\RazorPagesMovie2\bin\Debug\net7.0\RazorPagesMovie2.deps.json"

should be

“\\<server>\<share>\Users\<user>\My Documents\Development\C#\RazorPagesMovie2\RazorPagesMovie2\bin\Debug\net7.0\RazorPagesMovie2.deps.json”


If I run the dotnet command with \\\\ changed to \\ then I get this sensible looking output

verbose: Using assembly 'RazorPagesMovie2'.
verbose: Using startup assembly 'RazorPagesMovie2'.
verbose: Using application base '\\SLD-NAS-001\FIS-D\Users\sblpn\My Documents\Development\C#\RazorPagesMovie2\RazorPagesMovie2\bin\Debug\net7.0'.
verbose: Using working directory 'C:\WINDOWS\system32'.
verbose: Using root namespace 'RazorPagesMovie2'.
verbose: Using project directory '\\SLD-NAS-001\FIS-D\Users\sblpn\My Documents\Development\C#\RazorPagesMovie2\RazorPagesMovie2\'.
verbose: Remaining arguments: .
verbose: Finding DbContext classes...
verbose: Finding IDesignTimeDbContextFactory implementations...
verbose: Finding application service provider in assembly 'RazorPagesMovie2'...
verbose: Finding Microsoft.Extensions.Hosting service provider...
verbose: Using environment 'Development'.
verbose: Using application service provider from Microsoft.Extensions.Hosting.
verbose: Found DbContext 'RazorPagesMovie2Context'.
verbose: Finding DbContext classes in the project...
verbose: Using context 'RazorPagesMovie2Context'.
warn: Microsoft.EntityFrameworkCore.Model.Validation[30000]
      No store type was specified for the decimal property 'Price' on entity type 'Movie'. This will cause values to be silently truncated if they do not fit in the default precision and scale. Explicitly specify the SQL server column type that can accommodate all the values in 'OnModelCreating' using 'HasColumnType', specify precision and scale using 'HasPrecision', or configure a value converter using 'HasConversion'.
verbose: Finding design-time services referenced by assembly 'RazorPagesMovie2'...
verbose: Finding design-time services referenced by assembly 'RazorPagesMovie2'...
verbose: No referenced design-time services were found.
verbose: Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
verbose: Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
verbose: Finding IDesignTimeServices implementations in assembly 'RazorPagesMovie2'...
verbose: No design-time services were found.
warn: Microsoft.EntityFrameworkCore.Model.Validation[30000]
      No store type was specified for the decimal property 'Price' on entity type 'Movie'. This will cause values to be silently truncated if they do not fit in the default precision and scale. Explicitly specify the SQL server column type that can accommodate all the values in 'OnModelCreating' using 'HasColumnType', specify precision and scale using 'HasPrecision', or configure a value converter using 'HasConversion'.
warn:    No store type was specified for the decimal property 'Price' on entity type 'Movie'. This will cause values to be silently truncated if they do not fit in the default precision and scale. Explicitly specify the SQL server column type that can accommodate all the values in 'OnModelCreating' using 'HasColumnType', specify precision and scale using 'HasPrecision', or configure a value converter using 'HasConversion'.
verbose: Writing migration to '\\SLD-NAS-001\FIS-D\Users\sblpn\My Documents\Development\C#\RazorPagesMovie2\RazorPagesMovie2\Migrations\20230209124504_InitialCreate.cs'.
verbose: Writing model snapshot to '\\SLD-NAS-001\FIS-D\Users\sblpn\My Documents\Development\C#\RazorPagesMovie2\RazorPagesMovie2\Migrations\RazorPagesMovie2ContextModelSnapshot.cs'.
data:    {
data:      "migrationFile": "\\\\SLD-NAS-001\\FIS-D\\Users\\sblpn\\My Documents\\Development\\C#\\RazorPagesMovie2\\RazorPagesMovie2\\Migrations\\20230209124504_InitialCreate.cs",
data:      "metadataFile": "\\\\SLD-NAS-001\\FIS-D\\Users\\sblpn\\My Documents\\Development\\C#\\RazorPagesMovie2\\RazorPagesMovie2\\Migrations\\20230209124504_InitialCreate.Designer.cs",
data:      "snapshotFile": "\\\\SLD-NAS-001\\FIS-D\\Users\\sblpn\\My Documents\\Development\\C#\\RazorPagesMovie2\\RazorPagesMovie2\\Migrations\\RazorPagesMovie2ContextModelSnapshot.cs"
data:    }


So I think the problem is dealing with a “My Documents” folder that has been redirected to a network share.

Rgds/Pete

**Comment by ajcvickers** [comment]
Note from triage: this seems like a bug. Workaround is to map the network path to a drive letter.
