### ISSUE TITLE
The path params of EF.Functions.JsonExtract cannot use variable.

### ISSUE THREAD

**Issue by qslcna** [dotnet/efcore#30235]
I want build a dynamic query while the path params seem only support literal.

```C#
 public async Task<Paginated<JournalVM>> GetJournals(int productId, Dictionary<string, int> sku, int pageSize, int pageIndex)
        {
            var root = _context.Set<Journal>().Where(x => x.ProductId == productId);

            foreach (var item in sku)
            {
                var path = $"$.{item.Key}";
                root = root.Where(x => EF.Functions.JsonExtract<int>(x.SKU, path) == item.Value);   // -> throw exception
                //root = root.Where(x => EF.Functions.JsonExtract<int>(x.SKU, "$.Caliber") == item.Value);   -> this works
            }

            var totalItems = await root.LongCountAsync();

            var itemsOnPage = await root.OrderByDescending(x => x.Date)
                                        .ProjectTo<JournalVM>(_mapper.ConfigurationProvider)
                                        .Skip((pageIndex - 1) * pageSize)
                                        .Take(pageSize)
                                        .ToListAsync();

            var balance = await root.OrderByDescending(x => x.Date).Skip(pageIndex * pageSize).SumAsync(x => x.Count);

            itemsOnPage.Reverse();

            foreach (var item in itemsOnPage)
            {
                item.Balance = balance += item.Count;
            }

            return new Paginated<JournalVM>(pageIndex, pageSize, totalItems, itemsOnPage);
        }
```

```
[02:28:57 DBG 51] <Microsoft.EntityFrameworkCore.Query> Compiling query expression: 
'DbSet<Journal>()
    .Where(x => x.ProductId == __productId_0)
    .Where(x => __Functions_1
        .JsonExtract(
            json: x.SKU, 
            paths: __p_2) == __8__locals1_item_Value_3)
    .LongCount()' 
引发的异常:“System.InvalidOperationException”(位于 Microsoft.EntityFrameworkCore.Relational.dll 中)
6
引发的异常:“System.InvalidOperationException”(位于 System.Private.CoreLib.dll 中)
[02:28:57 ERR 51] <Web.Infrastructure.Filters.HttpGlobalExceptionFilter> Expression '@__p_2' in SQL tree does not have type mapping assigned. 
System.InvalidOperationException: Expression '@__p_2' in SQL tree does not have type mapping assigned.
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.SqlTypeMappingVerifyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlFunctionExpression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitExtension(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.SqlTypeMappingVerifyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlBinaryExpression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitExtension(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.SqlTypeMappingVerifyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TranslateInternal(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateExpression(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateLambdaExpression(ShapedQueryExpression shapedQueryExpression, LambdaExpression lambdaExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateWhere(ShapedQueryExpression source, LambdaExpression predicate)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)

```

EF Core version:6.0.13
Database provider: Pomelo.EntityFrameworkCore.MySql
Target framework: NET 6.0
Operating system: wsl2.0 
IDE: vs code 1.750

**Comment by roji** [comment]
This is probably something you need to raise with the maintainer of the Pomelo MySql driver [on the right repo](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql) - we don't maintain it (/cc @lauxjpn).
