### ISSUE TITLE
Auto insert for a related entity may insert duplicated rows with a `one-to-one` relationship

### ISSUE THREAD

**Issue by n0099** [dotnet/efcore#30236]
## Ask a question
EF has a great feature in that it will be able to insert entities that don't exist in the change tracker into DB when the instance of an entity is the value of a navigation property:
https://stackoverflow.com/questions/5212751/how-can-i-retrieve-id-of-inserted-entity-using-entity-framework/41146434#41146434

Suppose we have multiple entities with a one-to-one relationship to other entities(so the set of entities on each side should contain no duplicated ones): `A<->B`.
If there are any instance of entities in `B` that is duplicated(having the same identity by unique constraint), and they have no generated value(leaving the default value) for the primary key prop, EF will still try to insert these duplicated entities that lead to database-side errors.

### Include your code

```c#
public class A
{
    [Key] public int Id { get; set; }
    public int BId { get; set; }
    public B B { get; set; }
}
[Index(nameof(Value), IsUnique = true)]
public class B
{
    [Key] public int Id { get; set; }
    public string Value { get; set; }
}
```
```c#
protected override void OnModelCreating(ModelBuilder b)
{
    builder.Entity<A>().HasOne(e => e.B).WithOne();
}
```
```c#
var b1 = new B {Value = "b"};
var b2 = new B {Value = "b"};
var a1 = new A {B = b1}; // remove this entity will prevent duplicated insert
var a2 = new A {B = b2};
var a3 = new A {B = b2};
dbContext.AddRange(new List<A> {a1, a2, a3});
```
```sql
INSERT INTO `testB` (`value`) VALUES ('b');
SELECT `id` FROM `testB` WHERE ROW_COUNT() = 1 AND `id` = LAST_INSERT_ID();
INSERT INTO `testB` (`value`) VALUES ('b'); -- duplicated
```
and after removing the entity `a1` it will only insert one row:
```sql
INSERT INTO `testB` (`value`) VALUES ('b');
SELECT `id` FROM `testB` WHERE ROW_COUNT() = 1 AND `id` = LAST_INSERT_ID();
INSERT INTO `testA` (`bId`) VALUES (1);
SELECT `id` FROM `testA` WHERE ROW_COUNT() = 1 AND `id` = LAST_INSERT_ID();
```

### Include stack traces

```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> MySqlConnector.MySqlException (0x80004005): Duplicate entry 'b' for key 'testB.value'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 175
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 133
   at MySqlConnector.MySqlDataReader.NextResultAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 107
   at MySqlConnector.MySqlDataReader.NextResult() in /_/src/MySqlConnector/MySqlDataReader.cs:line 22
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__107_0(DbContext _, ValueTuple`2 t)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Program.Main() in /src/Program.cs:line 63
```

### Include provider and version information

EF Core version: 7.0
Database provider: Pomelo.EntityFrameworkCore.MySql 7.0.0
Target framework: .NET 7.0
Operating system: Windows 8.1
IDE: Visual Studio 2022 17.4.4

**Comment by ajcvickers** [comment]
@n0099 Are you asking for EF to throw instead of the database?

**Comment by n0099** [comment]
I want to know why the change tracker is allowing me to add two entities with the same key into it, shouldn't it merge the latter one(`b2`) into the previously added one(`b1`)?

**Comment by ajcvickers** [comment]
EF doesn't allow tracking multiple instances with the same primary or alternate key value, and it also doesn't attempt to merge such entities automatically, since that is a hard problem to solve in the general case. See [Identity Resolution in EF Core](https://learn.microsoft.com/en-us/ef/core/change-tracking/identity-resolution) for more information.

However, a unique foreign key is not identifying in the same way as a primary or alternate key, and so the same restriction does not apply at the EF level. If we were to add such a restriction, then the result would be EF throwing, but only when EF knows there is a conflict, which it often will not because it only sees a partial view of the data. So the value here is limited.

**Comment by n0099** [comment]
> only when EF knows there is a conflict, which it often will not

But in this sense EF should see there are two instances of `B` with the same value of the unique field, why not throw an `InvalidOperationException`?

**Comment by ajcvickers** [comment]
It could in this case, but not in many cases where both the entities are not loaded at the same time. So the value is minimal. And there is overhead in maintaining and detecting this.

**Comment by ajcvickers** [comment]
In general, relying on EF (or database) exceptions to control business logic is not a good idea. These exceptions are designed to tell you that your code did something it shouldn't. In other words, there is a bug in your program. Your business logic should ensure that such duplicates do not exist in what ever way makes sense for your application.
