### ISSUE TITLE
Why Efcore doesn't automatically track existence of navigational property in the database?

### ISSUE THREAD

**Issue by Unicodist** [dotnet/efcore#30249]
## Assigning navigational property seems to insert it as a new row, instead of using it as a foreign entity

I have relationship in my entities between "Book" and "Author".

```C#
public class Book{

 public int Id {get;set;}
 public string Name {get;set;}
 public int AuthorId {get;set;}

 public virtual Author Author {get;set;}

}

public class Author{

 public int Id {get;set;}
 public string Name {get;set;}

}
```
Then when I try to assign an instance of Author in a new instance of Book, it throws an Exception that the Author with the same primary key already exist in the database.

```C#

var author = await _authorRepository.FindAsync(authorId);
book.Author = author;
await _bookRepository.AddAsync(book);

```

Then I am greeted with this exception: 

```

Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "PK_authors"

DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|225_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
  Exception data:
    Severity: ERROR
    SqlState: 23505
    MessageText: duplicate key value violates unique constraint "PK_authors"
    Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
    SchemaName: public
    TableName: authors
    ConstraintName: PK_authors
    File: nbtinsert.c
    Line: 563
    Routine: _bt_check_unique
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at /.../BookController`1.Save() in /.../BookController.cs:line 59
   at /.../BookController`1.Add(T entity) in /.../BookController.cs:line 23

```

EF Core version: 7.0.2
Database provider: (NpgSql)
Target framework: (.NET 6.0)
Operating system: Ubuntu
IDE: (Rider)

**Comment by davidroth** [comment]
Did you load the book from another dbcontext instance?
That would explain it.
If not you should add a fully reproducable sample code including model configuration.

**Comment by ajcvickers** [comment]
See [Change Tracking in EF Core](https://learn.microsoft.com/en-us/ef/core/change-tracking/) for an overview of this.

**Comment by Unicodist** [comment]
Thank you both @davidroth and @ajcvickers , it was caused because I loaded and added them with different dbcontexts. Can't believe I missed such detail.
