### ISSUE TITLE
Update-Database command uses incorrect path

### ISSUE THREAD

**Issue by wstaelens** [dotnet/efcore#30298]
same as https://github.com/dotnet/efcore/issues/18632 and https://github.com/dotnet/efcore/issues/23625 but both tickets seems to be closed without a fix? So opened a new one.

I'm having the same problem EF Core 7.0.3, Blazor Server + Identity, localdb

It tries something in `'C:\Users\wst.CONTOSOaspnet-Foo.Bar-45153c7b-4568-43a7-b744-9c98efd2dfd5.mdf'.`  --> `C:\Users\wst.CONTOSO` is my username.  A slash seems to be missing (or maybe more?)

**how to fix this?** bug? can't create/update database now...

```
PM> Add-Migration Initial -OutputDir "Data/Migrations"
Build started...
Build succeeded.
To undo this action, use Remove-Migration.
PM> Update-Database
Build started...
Build succeeded.
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (18ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
      CREATE DATABASE [aspnet-Foo.Bar-45153c7b-4568-43a7-b744-9c98efd2dfd5];
Failed executing DbCommand (18ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
CREATE DATABASE [aspnet-Foo.Bar-45153c7b-4568-43a7-b744-9c98efd2dfd5];
Microsoft.Data.SqlClient.SqlException (0x80131904): CREATE FILE encountered operating system error 5(Access is denied.) while attempting to open or create the physical file 'C:\Users\wst.CONTOSOaspnet-Foo.Bar-45153c7b-4568-43a7-b744-9c98efd2dfd5.mdf'.
CREATE DATABASE failed. Some file names listed could not be created. Check related errors.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:c7217961-7672-479d-be5f-104b920d4bb7
Error Number:5123,State:1,Class:16
CREATE FILE encountered operating system error 5(Access is denied.) while attempting to open or create the physical file 'C:\Users\wst.CONTOSOaspnet-Foo.Bar-45153c7b-4568-43a7-b744-9c98efd2dfd5.mdf'.
CREATE DATABASE failed. Some file names listed could not be created. Check related errors.
PM> 
``` 

### Include provider and version information

EF Core version: 7.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: Windows 10 x64
IDE: Visual Studio 2022 17.4.5

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by wstaelens** [comment]
1. I've created a new .net 7.0 blazor server application with identity. (call it "Foo")
2. added a new project called (.net 7.0 class library) (call it "Foo.Core")
3. I wanted to move the EF Core stuff and migrations to the "Foo.Core" project. I've opened Package Manager Console in VS2022 and set the Default project to "Foo.Core"
4. Created a folder Data/Migrations in "Foo.Core" and typed in "Add-Migration -OutputDir "Data/Migrations"
5. I've tuped Update-Database
6. Next whenever You do something with ApplicationDbContext which requires the database, it fails to create the database. and it looks like the path is missing a slash or something. See the error message I've received.

To quickly test the code that triggers it:

```csharp

var builder = WebApplication.CreateBuilder(args);
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection") ?? throw new InvalidOperationException("Connection string 'DefaultConnection' not found.");
builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseSqlServer(connectionString), ServiceLifetime.Singleton);
#if DEBUG
builder.Services.AddDbContextFactory<ApplicationDbContext>(opt => opt.UseSqlServer(connectionString).EnableSensitiveDataLogging(true));
#else 
builder.Services.AddDbContextFactory<ApplicationDbContext>(opt => opt.UseSqlServer(connectionString));
#endif
builder.Services.AddDatabaseDeveloperPageExceptionFilter();
builder.Services.AddDefaultIdentity<IdentityUser>(options => options.SignIn.RequireConfirmedAccount = true)
    .AddEntityFrameworkStores<ApplicationDbContext>();
builder.Services.AddRazorPages();
builder.Services.AddServerSideBlazor();
builder.Services.AddDevExpressBlazor();
builder.Services.AddScoped<AuthenticationStateProvider, RevalidatingIdentityAuthenticationStateProvider<IdentityUser>>();
builder.Services.Configure<DevExpress.Blazor.Configuration.GlobalOptions>(options =>
{
    options.BootstrapVersion = DevExpress.Blazor.BootstrapVersion.v5;
});
builder.WebHost.UseWebRoot("wwwroot");
builder.WebHost.UseStaticWebAssets();
var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseMigrationsEndPoint();
}
else
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();

app.UseStaticFiles();

app.UseRouting();

app.UseAuthorization();

app.MapControllers();
app.MapBlazorHub();
app.MapFallbackToPage("/_Host");

// some code that triggers the dbcontext and db creation
using (var context = app.Services.GetService<IDbContextFactory<ApplicationDbContext>>().CreateDbContext())
{
    context.Database.EnsureCreated(); // <-- boom!
}

app.Run();
```

You can also trigger it quickly instead of in program.cs in a razor page:

```
@code {
    protected override Task OnInitializedAsync()
    {
        using var context = DbFactory.CreateDbContext();

        if (context.Tags is not null)
        {
            var cnt = context.Tags.Count(); // <-- BOOM error
        }

        return base.OnInitializedAsync();
    }
}
```

The other two tickets I've mentioned (that were closed without a fix) describe the same problem I've experienced.

**Comment by ajcvickers** [comment]
@wstaelens What is the content of your appsettings.json and appsettings.Development.json?

**Comment by wstaelens** [comment]
My solution is called: Company.Foo.Bar

It has projects: Company.Foo.Bar and Company.Foo.Bar.Core .

appsettings.json is located in the default Blazor Server web project (Company.Foo.Bar)  and i've moved my migrations, models and ApplicationDbContext to Company.Foo.Bar.Core class library.

```
{
  "ConnectionStrings": {
    "DefaultConnection": "Server=(localdb)\\mssqllocaldb;Database=aspnet-Foo.Bar-45153c7b-4568-43a7-b744-9c98efd2dfd5;Trusted_Connection=True;MultipleActiveResultSets=true"
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*"
}

```

Development:

```
{
  "DetailedErrors": true,
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  }
}

```

Hope this helps.

**Comment by ajcvickers** [comment]
No idea what is going on here. I will discuss with the team.

**Comment by ErikEJ** [comment]
@wstaelens Update your localDb to a newer, bug free version: https://dba.stackexchange.com/questions/191393/localdb-v14-creates-wrong-path-for-mdf-files

**Comment by wstaelens** [comment]
@ErikEJ ok great. 

``` 
C:\Program Files\Microsoft Visual Studio\2022\Professional>sqllocaldb.exe versions
Microsoft SQL Server 2014 (12.0.4237.0)
Windows API call "RegGetValueW" returned error code: 0.
```

I'll move some projects over to a different machine (which require 2014 and see if I can upgrade that. 
Hopefully this "error" / "bug" gets properly documented :-)

**Comment by ErikEJ** [comment]
@wstaelens It is "properly dcumented"! https://support.microsoft.com/en-us/topic/kb4096875-fix-access-is-denied-error-when-you-try-to-create-a-database-in-sql-server-2017-express-localdb-d9b44eb5-3d6f-ba8c-ab71-c40726d86519

**Comment by wstaelens** [comment]
> @wstaelens It is "properly documented"! https://support.microsoft.com/en-us/topic/kb4096875-fix-access-is-denied-error-when-you-try-to-create-a-database-in-sql-server-2017-express-localdb-d9b44eb5-3d6f-ba8c-ab71-c40726d86519

Looks like it was well hidden, (looking at the tickets/forums it was not only hiding for me ;-) ).
You can close this ticket 👍 Thanks!
