### ISSUE TITLE
System.InvalidOperationException: No coercion operator is defined between types 'System.DateTime' and 'System.Nullable`1[System.Int32]'.

### ISSUE THREAD

**Issue by archanasoni** [dotnet/efcore#30327]
Hi All,

We are working to have support for IBM EF Provider with NET 7.0.

We've following query which was working till NET 6.0 but with NET 7.0 it throws error:
var q = ctx.Orders.Where(o => o.OrderDate != null)
                    .Select(o => o.OrderDate.Value.Year)
                    .Distinct()
                    .Where(x => x < 2017);

Console.WriteLine(q.ToArray().Count());

Error with NET 7.0:

```
warn: 2/23/2023 04:53:29.718 CoreEventId.SensitiveDataLoggingEnabledWarning[10400] (Microsoft.EntityFrameworkCore.Infrastructure)
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
dbug: 2/23/2023 04:53:30.112 CoreEventId.ContextInitialized[10403] (Microsoft.EntityFrameworkCore.Infrastructure)
      Entity Framework Core 7.0.1 initialized 'NorthwindContext' using provider 'IBM.EntityFrameworkCore:6.0.0.300' with options: SensitiveDataLoggingEnabled
dbug: 2/23/2023 04:53:30.189 CoreEventId.QueryCompilationStarting[10111] (Microsoft.EntityFrameworkCore.Query)
      Compiling query expression:
      'DbSet<Order>()
          .Where(o => o.OrderDate != null)
          .Select(o => o.OrderDate.Value.Year)
          .Distinct()
          .Where(x => x < 2017)'
Unhandled exception. System.InvalidOperationException: No coercion operator is defined between types 'System.DateTime' and 'System.Nullable`1[System.Int32]'.
   at System.Linq.Expressions.Expression.GetUserDefinedCoercionOrThrow(ExpressionType coercionType, Expression expression, Type convertToType)
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type, MethodInfo method)
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.CreateGetValueExpression(ParameterExpression dbDataReader, Int32 index, Boolean nullable, RelationalTypeMapping typeMapping, Type type, IPropertyBase property)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.ProcessShaper(Expression shaperExpression, RelationalCommandCache& relationalCommandCache, IReadOnlyList`1& readerColumns, LambdaExpression& relatedDataLoaders, Int32& collectionId)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.VisitShapedQuery(ShapedQueryExpression shapedQueryExpression)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Program.<Main>$(String[] args) in C:\Users\asoni\source\repos\NET7DebugAppDBF1\NET7DebugAppDBF1\Program.cs:line 57
```

By looking at the error, we understood problem is   with selecting Select(o => o.OrderDate.Value.Year) but what is changed bcoz of that we are hitting this exception. Do we require to implement something which is newly introduced ?

Thanks,
Archana

**Comment by roji** [comment]
@archanasoni the query above seems to work fine in other providers (e.g. SQL Server), which indicates that the problem is probably in some customization you're doing in your own provider... I'd recommend following the query pipeline progress in your provider and comparing that to e.g. SQL Server's to see exactly where the divergence occurs.

**Comment by archanasoni** [comment]
@roji we did not change except targets to higher version of EF Core relational.. and it looks to be broken for us. We did try to debug SQL Server code but so far 0 success in finding the divergence..

**Comment by roji** [comment]
I'm not sure how I could help you further, given that I can't even see the error happening or debug it... The typical way I debug these issues is to step through query compilation starting in [QueryCompilationContext](https://github.com/dotnet/efcore/blob/main/src/EFCore/Query/QueryCompilationContext.cs#L164) and comparing the expression tree after each step (e.g. between your provider and SQL Server). Once you see where a divergence occured, you can step into individual steps/visitors (likely in translation, or possibly post-processing).

**Comment by archanasoni** [comment]
Thanks @roji for your help and support, we are able to identify the issue. hence closing it.
