### ISSUE TITLE
Error on build: Could not load file or assembly 'xunit.execution.dnx, Version=0.0.0.0'

### ISSUE THREAD

**Issue by felipepessoto** [dotnet/efcore#3032]
This error happens when I execute the build command.

Also. Unit Tests doesn't work. I already tried to clean my TEMP folder.

info: Target compile
info: Target test-compile
info: Target xunit-test
info: Exec
info:   program: cmd
info:   commandline: /C dnx test
info:   workingdir: test\EntityFramework.Commands.FunctionalTests
xUnit.net DNX Runner (32-bit DNX 4.5.1)
  Discovering: EntityFramework.Commands.FunctionalTests
System.IO.FileNotFoundException: Could not load file or assembly 'xunit.execution.dnx, Version=0.0.0.0' or one of its dependencies. The system cannot find the file specified.
warn: Exit code 1 from cmd
verbose: Stack trace: 
   at View0af0878dbd52486781c8ef1c6662917a.K(String command, String workingdir, String dnvmUse) in c:\Users\felip\AppData\Local\Temp\9546b2cfde444cd9941bb6c5124e17c5-1.cs:line 1232
   at View0af0878dbd52486781c8ef1c6662917a.DnxTest(String projectFile, Boolean testParallel) in c:\Users\felip\AppData\Local\Temp\9546b2cfde444cd9941bb6c5124e17c5-1.cs:line 441
   at View0af0878dbd52486781c8ef1c6662917a.<RenderViewLevel0>b__6b(String projectFile) in c:\Users\felip\AppData\Local\Temp\9546b2cfde444cd9941bb6c5124e17c5-1.cs:line 8576
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at View0af0878dbd52486781c8ef1c6662917a.<RenderViewLevel0>b__69() in c:\Users\felip\AppData\Local\Temp\9546b2cfde444cd9941bb6c5124e17c5-1.cs:line 8576
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View0af0878dbd52486781c8ef1c6662917a.<RenderViewLevel0>b__4a() in c:\Users\felip\AppData\Local\Temp\9546b2cfde444cd9941bb6c5124e17c5-1.cs:line 2727
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at View0af0878dbd52486781c8ef1c6662917a.<RenderViewLevel0>b__42() in c:\Users\felip\AppData\Local\Temp\9546b2cfde444cd9941bb6c5124e17c5-1.cs:line 2583
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)

**Comment by rowanmiller** [comment]
Can you delete everything from the .dnx folder in your user profile and try again

**Comment by fujiy** [comment]
Great, worked!
