### ISSUE TITLE
Optionally map property if column exists, otherwise silently ignore

### ISSUE THREAD

**Issue by bjorkstromm** [dotnet/efcore#30322]
## Ask a question

We have a use case where entity is queried via TVF and Table. When querying via TVF we can calculate an additional column (due to recursive CTE) which can be mapped. If the additional column is *not* present in the Table, we will get an exception when accessing the entity directly via DbSet instead of the mapped function. To workaround this, we've added the "missing" column, which is always `null`, to the table.

Is there currently a better workaround than adding the "missing" column to the table? I've tried inheritance (using TPH), but that will AFAIK require a discriminator column, which is not optimal.

Probably related (or duplicate of) #14121 and #24692

### Include your code

Full repro can be found here https://github.com/bjorkstromm/efcore-repro

Below is a summary:

We create a table called `Path`. 
```sql
CREATE TABLE [Repro].[Path]
(
    [Id]            INT                 IDENTITY(1,1),
    [ParentId]      INT                 NULL,
    [Name]          NVARCHAR(32)        NULL,

    CONSTRAINT PK_Repro_Path PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT FK_Repro_Path FOREIGN KEY ([ParentId]) REFERENCES [Repro].[Path]([Id])
)
```

And a TVF called `GetPaths`. This will return a column called `FullName` which can be computed because of the recursive CTE.
```sql
CREATE FUNCTION [Repro].[GetPaths]
(
    @Id INT = null
)
RETURNS TABLE
AS
RETURN
(
    WITH CTE AS
    (
        SELECT P.[Id],
            P.[ParentId],
            P.[Name],
            CAST(P.[Name] AS NVARCHAR(MAX)) AS [FullName]
        FROM [Repro].[Path] AS P
        WHERE
            (@Id is null AND P.ParentId is null)
            OR (P.Id = @Id)

        UNION ALL

        SELECT P.[Id],
            P.[ParentId],
            P.[Name],
            CAST(CONCAT(C.[FullName], ' / ', P.[Name]) AS NVARCHAR(MAX)) AS [FullName]
        FROM [Repro].[Path] AS P
        INNER JOIN CTE AS C ON C.Id = P.ParentId
    )

    SELECT * FROM CTE
)
```

We define the entity
```csharp
public class Path
{
    public int Id { get; set; }
    public string? Name { get; set; }
    public Path? Parent { get; set; }
    public ICollection<Path> Children { get; set; } = new List<Path>();
    public ICollection<Item> Items { get; set; } = new List<Item>();

    // How to make this optional?
    // Adding [NotMapped] will cause it to be removed when using GetPaths() function
    public string? FullName { get; set;}
}
```

And the DbContext
```csharp
public class ReproContext : DbContext
{
    public ReproContext(DbContextOptions<ReproContext> options) : base(options)
    {
    }

    public DbSet<Path> Paths { get; set; }
    public DbSet<Path> Items { get; set; }
    public IQueryable<Path> GetPaths(int? id) => FromExpression(() => GetPaths(id));

    override protected void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Path>()
            .ToTable("Path", "Repro")
            .HasMany(p => p.Children)
            .WithOne(p => p.Parent)
            .HasForeignKey("ParentId");

        modelBuilder.Entity<Item>()
            .ToTable("Item", "Repro")
            .HasOne(i => i.Path)
            .WithMany(p => p.Items)
            .HasForeignKey("PathId");

        modelBuilder
            .HasDbFunction(typeof(ReproContext).GetMethod(nameof(GetPaths), new[] { typeof(int?) })!)
            .HasName("GetPaths")
            .HasSchema("Repro");
    }
}
```

Executing the following code will result in a exception on the last part, because column is not available when accessing directly via table. The first part works ok, because `FullName` is exposed when querying using TVF.

```csharp
using var ctx = new ReproContext(optionsBuilder.Options);

var names = await ctx.GetPaths(null)
    .SelectMany(p => p.Items, (p, i) => p.FullName + " / " +  i.Name )
    .ToListAsync();

foreach (var item in names)
{
    Console.WriteLine(item);
}

// This will cause runtime error
// because the FullName column is not present in the table
var paths = await ctx.Paths.ToListAsync();
```

### Include stack traces

Following stack trace, which is expected 😄 

```
Unhandled exception. Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'FullName'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__208_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\Users\martin\src\gh\efcore-repro\Repro\Program.cs:line 22
   at Program.<Main>(String[] args)
ClientConnectionId:e1b53f24-a74c-4821-ac59-02d1b9df0b4e
Error Number:207,State:1,Class:16
```

### Include provider and version information

EF Core version: 7.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: N/A
IDE: N/A

**Comment by bjorkstromm** [comment]
Best workaround so far was to create a separate [keyless type](https://learn.microsoft.com/en-us/ef/core/modeling/keyless-entity-types?tabs=data-annotations)

```csharp
public class Path
{
    public int Id { get; set; }
    public string? Name { get; set; }
    public Path? Parent { get; set; }
    public ICollection<Path> Children { get; set; } = new List<Path>();
    public ICollection<Item> Items { get; set; } = new List<Item>();
}

// Create separate keyless type without any navigation
public class PathWithFullName
{
    public int Id { get; set; }
    public string? Name { get; set; }
    public int? ParentId { get; set; }
    public string? FullName { get; set;}
}
```

And then configure to model like
```csharp
public IQueryable<PathWithFullName> GetPaths(int? id) => FromExpression(() => GetPaths(id));

override protected void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Path>()
        .ToTable("Path", "Repro")
        .HasMany(p => p.Children)
        .WithOne(p => p.Parent)
        .HasForeignKey("ParentId");

    modelBuilder.Entity<Item>()
        .ToTable("Item", "Repro")
        .HasOne(i => i.Path)
        .WithMany(p => p.Items)
        .HasForeignKey("PathId");

    // Unfortunately we can't map the TVF here, because mapped TVF's must be parameterless
    // I don't really know where to map this? I could create a separate view or a parameterless TVF, I guess.
    modelBuilder.Entity<PathWithFullName>()
        .HasNoKey();

    modelBuilder
        .HasDbFunction(typeof(ReproContext).GetMethod(nameof(GetPaths), new[] { typeof(int?) })!)
        .HasName("GetPaths")
        .HasSchema("Repro");
}
```

Unfortunately navigation breaks with this approach, so any queries which needs to join `Items`, `Children` or `Parent` needs to manually use `Join()`. I could probably map a view or a parameterless TVF in order to get navigation. But this workaround is good enough.

**Comment by ajcvickers** [comment]
Note for triage: I was able to map this using shared-type entity types, but only when using `FromSql` to call the function, since I couldn't figure out how to map a `DbFunction` to return a shared-type entity type.

@bjorkstromm Not sure if this is useful to you; I don't know how important it is to have a `DbFunction` mapping.

```C#
using var ctx = new ReproContext();

var names = await ctx.Set<Path>("FunctionPath").FromSqlInterpolated(@$"SELECT * FROM [Repro].[GetPaths](NULL)")
    .SelectMany(p => p.Items, (p, i) => p.FullName + " / " +  i.Name )
    .ToListAsync();

foreach (var item in names)
{
    Console.WriteLine(item);
}

var paths = await ctx.Set<Path>("TablePath").ToListAsync();

foreach (var path in paths)
{
    Console.WriteLine(path);
}

public class Path
{
    public int Id { get; set; }
    public string? Name { get; set; }
    public Path? Parent { get; set; }
    public ICollection<Path> Children { get; set; } = new List<Path>();
    public ICollection<Item> Items { get; set; } = new List<Item>();
    public string? FullName { get; set;}
}

public class Item
{
    public int Id { get; set; }
    public string? Name { get; set; }
    public Path? Path { get; set; }
}

public class ReproContext : DbContext
{
     protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
     {
         optionsBuilder
             .UseSqlServer(@"Data Source=(LocalDb)\MSSQLLocalDB;Database=AllTogetherNow")
             .LogTo(Console.WriteLine, LogLevel.Information)
             .EnableSensitiveDataLogging();
     }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.SharedTypeEntity<Path>("TablePath", b =>
        {
            b.ToTable("Path", "Repro");
            b.HasMany("TablePath", "Children").WithOne("Parent").HasForeignKey("ParentId");
            b.Ignore(e => e.FullName);
        });

        modelBuilder.SharedTypeEntity<Path>("FunctionPath")
            .HasMany("FunctionPath", "Children")
            .WithOne("Parent")
            .HasForeignKey("ParentId");

        modelBuilder.Entity<Item>()
            .ToTable("Item", "Repro")
            .HasOne("FunctionPath", "Path")
            .WithMany("Items")
            .HasForeignKey("PathId");
    }
}
```

Output:
```
info: 2/25/2023 20:38:00.730 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (35ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT (COALESCE([f].[FullName], N'') + N' / ') + COALESCE([i].[Name], N'')
      FROM (
          SELECT * FROM [Repro].[GetPaths](NULL)
      ) AS [f]
      INNER JOIN [Repro].[Item] AS [i] ON [f].[Id] = [i].[PathId]
info: 2/25/2023 20:38:00.781 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [p].[Id], [p].[Name], [p].[ParentId]
      FROM [Repro].[Path] AS [p]
```

**Comment by ajcvickers** [comment]
Note from triage: #21569 covers this missing part.
