### ISSUE TITLE
How can i customize the dbcontext by adding arguments to its constructors, using adddbcontextpool registration

### ISSUE THREAD

**Issue by Su-s** [dotnet/efcore#30350]
## How can I customize the ctor of the dbcontext, if I'm using the adddbcontextpool to register the db service

Hi, I'm working on an asp.net core project, where I want to give arguments to the dbcontext. I found that for production purposes, we should have to use the **AddDbContextPool** instead of **AddDbContext**. I was able to run the application successfully until the below modification was applied. 

I followed the this link https://digitaldrummerj.me/ef-core-audit-columns/, to setup arguments to log the contents in the dbcontext. But I used the  **AddDbContextPool** instead of **AddDbContext**, and this is the only change in my code.  

Also, I'm using the npgsql instead of the sqlserver. Apart from these two changes, the code is exactly as mentioned in the link. 
 
Please guide me to resolve this issue @ajcvickers 

### Code

```
public class DatabaseContext :
    IdentityDbContext<IdentityUser, IdentityRole, string>
{
    private readonly ILogger<DatabaseContext> _logger;
private readonly MyService1  myserv1;

    public DatabaseContext(DbContextOptions<DatabaseContext> options, ILogger<DatabaseContext> logger,MyService1 myserv1)
        : base(options)
    {
        _logger= logger;
_myserv1=myserv1;
    }
}

//Program.cs
  builder.Services
            .AddDbContextPool<DatabaseContext>(opt =>
                configuration.GetConnectionString("PostgresConnection"));
```

### Stack traces
```
System.InvalidOperationException: The DbContext of type 'DatabaseContext' cannot be pooled because it does not have a public constructor accepting a single parameter of type DbContextOptions or has more than one constructor.
   at Microsoft.EntityFrameworkCore.Internal.DbContextPool`1.CreateActivator(DbContextOptions`1 options)
   at Microsoft.EntityFrameworkCore.Internal.DbContextPool`1..ctor(DbContextOptions`1 options)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__5`2.<AddDbContextPool>b__5_0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
```

### Provider and version information

EF Core version: 7.0
Database provider: Npgsql.Entityframeworkcore.Postgresql
Target framework: NET 7.0
Operating system: Windows 10
IDE: JetBrains Rider 2022.3.2

**Comment by ajcvickers** [comment]
@Su-s You will likely need to create your own context factory for this. If the services you are injecting are singletons, then this should be relatively simple. On the other hand, if the services are scoped, then a context instance is going to need to have its dependencies changed when it comes out of the pool. (At this point I would question whether you really should use context pooling.) You can find more info in the docs: https://learn.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-di%2Cwith-constant#dbcontext-pooling

**Comment by Su-s** [comment]
@ajcvickers, I want to implement change tracking and auditing inside the **DbContext**. To do this, the DbContext needs to access the current user context for the request. While I can exclude the logging inside the **DbContext**, I'm currently writing audit code wherever I access an entity from the database. I found an article that describes how to implement auditing using audit columns and override the **SaveChanges** method in the **DbContext**. Here's the link to the article: https://digitaldrummerj.me/ef-core-audit-columns/.

Also, I decided to use **DbContextPool** instead of **DbContext** because I learned that pools reduce overhead in production. I don't want to mess with the **DbContext** on every request, and I believe **DbContextPool** is more efficient in a production environment.
