### ISSUE TITLE
EF Core and DDD --> .OwnsMany() call on other aggregate root ids (in value object form) throws 'Object reference not set to an instance of an object' when aggregate performing the .OwnsMany() call has its own ids referenced by another aggregate root

### ISSUE THREAD

**Issue by kcindric** [dotnet/efcore#30373]
I'm building an app following the DDD principles and using Aggregates, Entities and Value objects. These are my two aggregate roots for which I wrote configurations which are then used for building EF Core migrations:

`Office.cs` which has a list of `DepartmentId`'s for referencing the other aggregate:
```c#
public class Office : AggregateRoot<OfficeId>
{
    private readonly List<DepartmentId> _departmentIds = new();

    public string Name { get; private set; }
    public DateTime CreatedDateTime { get; private set; }
    public DateTime UpdatedDateTime { get; private set; }

    public IReadOnlyList<DepartmentId> DepartmentIds => _departmentIds.AsReadOnly();

    private Office(OfficeId officeId, string name, DateTime createdDateTime, DateTime updatedDateTime) :
        base(officeId)
    {
        Name = name;
        CreatedDateTime = createdDateTime;
        UpdatedDateTime = updatedDateTime;
    }

    public static Office Create(int officeId, string name)
    {
        return new Office(OfficeId.Create(officeId), name, DateTime.UtcNow, DateTime.UtcNow);
    }

    private Office(){}
}
```

`Department.cs` which has a list of `MunicipalityId`'s for referencing `Municipality` aggregate, which is not shown here.
```c#
public class Department : AggregateRoot<DepartmentId>
{
    private readonly List<MunicipalityId> _municipalityIds = new();

    public string Name { get; private set; }
    public OfficeId OfficeId { get; private set; }
    public DateTime CreatedDateTime { get; private set; }
    public DateTime UpdatedDateTime { get; private set; }

    public IReadOnlyList<MunicipalityId> MunicipalityIds => _municipalityIds.AsReadOnly();

    private Department(DepartmentId departmentId, string name, OfficeId officeId, DateTime createdDateTime, DateTime updatedDateTime) :
        base(departmentId)
    {
        Id = departmentId;
        Name = name;
        OfficeId = officeId;
        CreatedDateTime = createdDateTime;
        UpdatedDateTime = updatedDateTime;
    }

    public static Department Create(DepartmentId departmentId, string name, OfficeId officeId)
    {
        return new Department(departmentId, name, officeId,DateTime.UtcNow, DateTime.UtcNow);
    }

    private Department(){}
}
```

Now the entity builder configurations which are then used in the `OnModelCreating(ModelBuilder modelBuilder)` to create migrations.

`OfficeConfigurations`
```c#
public class OfficeConfigurations : IEntityTypeConfiguration<Office>
{
    public void Configure(EntityTypeBuilder<Office> builder)
    {
        ConfigureOfficeTable(builder);
        ConfigureDepartmentIdTable(builder);
    }

    private void ConfigureOfficeTable(EntityTypeBuilder<Office> builder)
    {
        builder.ToTable(nameof(Office), nameof(Office));
        
        builder.HasKey(o => o.Id);
        
        builder.Property(o => o.Id)
            .ValueGeneratedNever()
            .HasConversion(
                id => id.Value,
                value => OfficeId.Create(value));
    }

    private void ConfigureDepartmentIdTable(EntityTypeBuilder<Office> builder)
    {
        builder.OwnsMany(o => o.DepartmentIds, departmentIdBuilder =>
        {
            departmentIdBuilder.ToTable(nameof(DepartmentId), nameof(Office));
            
            departmentIdBuilder.WithOwner().HasForeignKey(nameof(OfficeId));
            
            departmentIdBuilder.HasKey("Id"); // shadow id property
            
            departmentIdBuilder.Property(did => did.Value)
                .HasColumnName(nameof(DepartmentId))
                .ValueGeneratedNever();
        });
        
        builder.Metadata.FindNavigation(nameof(Office.DepartmentIds))!
            .SetPropertyAccessMode(PropertyAccessMode.Field);
    }
}
```

`DepartmentConfigurations`
```c#
public class DepartmentConfigurations : IEntityTypeConfiguration<Department>
{
    public void Configure(EntityTypeBuilder<Department> builder)
    {
        ConfigureDepartmentTable(builder);
        ConfigureMunicipalityIdTable(builder);
    }

    private void ConfigureDepartmentTable(EntityTypeBuilder<Department> builder)
    {
        builder.ToTable(nameof(Department), nameof(Department));

        builder.HasKey(d => d.Id);

        builder.Property(d => d.Id)
            .ValueGeneratedNever()
            .HasConversion(
                id => id.Value,
                value => DepartmentId.Create(value));

        builder.Property(d => d.OfficeId)
            .ValueGeneratedNever()
            .HasConversion(
                id => id.Value,
                value => OfficeId.Create(value));
    }

    private void ConfigureMunicipalityIdTable(EntityTypeBuilder<Department> builder)
    {
        builder.OwnsMany(d => d.MunicipalityIds, municipalityIdBuilder =>
        {
            municipalityIdBuilder.ToTable(nameof(MunicipalityId), nameof(Department));
        
            municipalityIdBuilder.WithOwner().HasForeignKey(nameof(DepartmentId));
        
            municipalityIdBuilder.HasKey("Id"); // shadow id property
        
            municipalityIdBuilder.Property(mid => mid.Value)
                .HasColumnName(nameof(MunicipalityId))
                .ValueGeneratedNever();
        });

        builder.Metadata.FindNavigation(nameof(Department.MunicipalityIds))!
            .SetPropertyAccessMode(PropertyAccessMode.Field);
    }
}
```

Example of Id value objects (`OfficeId`, `DepartmentId`, `MunicipalityId`) which all follow the same pattern:

```c#
public class OfficeId : ValueObject
{
    public int Value { get; }

    private OfficeId(int value)
    {
        Value = value;
    }

    public static OfficeId Create(int value)
    {
        return new OfficeId(value);
    }
    
    public override IEnumerable<object?> GetEqualityComponents()
    {
        yield return Value;
    }
}
```

`DbContext` configuration, the rest of

```c#
public class MyDbContext : DbContext
{
    public MyDbContext(DbContextOptions<MyDbContext> options) : base(options){}

    public DbSet<Office> Offices { get; set; } = null!;
    public DbSet<Department> Departments { get; set; } = null!;
    public DbSet<Municipality> Municipalities { get; set; } = null!;
    
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {

        modelBuilder.ApplyConfiguration(new OfficeConfigurations());
        modelBuilder.ApplyConfiguration(new DepartmentConfigurations());
        modelBuilder.ApplyConfiguration(new MunicipalityConfigurations());
        base.OnModelCreating(modelBuilder);
    }
}
```

When I try to add a migration using `dotnet ef migrations add InitialMigration` using just one of these configuration (either `OfficeConfigurations` or `DepartmentConfigurations`) the migration is successfully created. The problem is when I try to create a migration using both configurations, or the rest of other configurations I didn't show here I get a strange `Object reference not set to an instance of an object.` error. When running the two shown configurations the stack trace is the following:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionBatchExtensions.Run(IConventionBatch batch, InternalForeignKeyBuilder relationshipBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalForeignKeyBuilder.ReuniquifyImplicitProperties(Boolean force)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.ForeignKeyPropertyDiscoveryConvention.DiscoverProperties(IConventionForeignKeyBuilder relationshipBuilder, IConventionContext c
ontext)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.ForeignKeyPropertyDiscoveryConvention.ProcessForeignKeyRequirednessChanged(IConventionForeignKeyBuilder relationshipBuilder, IC
onventionContext`1 context)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnForeignKeyRequirednessChanged(IConventionForeignKeyBuilder relationshi
pBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnForeignKeyRequirednessChangedNode.Run(ConventionDispatcher dispatcher)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.DelayedConventionScope.Run(ConventionDispatcher dispatcher)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Run()
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Run(IConventionForeignKey foreignKey)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.OwnsManyBuilder[TRelatedEntity](TypeIdentity ownedType, MemberIdentity navigation)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.OwnsMany[TRelatedEntity](Expression`1 navigationExpression, Action`1 buildAction)
   at Ratsatak.Infrastructure.Persistence.Configurations.DepartmentConfigurations.ConfigureMunicipalityIdTable(EntityTypeBuilder`1 builder) in D:\DevCollections\Ratsatak\Ratsatak.Infra
structure\Persistence\Configurations\DepartmentConfigurations.cs:line 39
   at Ratsatak.Infrastructure.Persistence.Configurations.DepartmentConfigurations.Configure(EntityTypeBuilder`1 builder) in D:\DevCollections\Ratsatak\Ratsatak.Infrastructure\Persisten
ce\Configurations\DepartmentConfigurations.cs:line 15
   at Microsoft.EntityFrameworkCore.ModelBuilder.ApplyConfiguration[TEntity](IEntityTypeConfiguration`1 configuration)
   at Ratsatak.Infrastructure.Persistence.RatsatakDbContext.OnModelCreating(ModelBuilder modelBuilder) in D:\DevCollections\Ratsatak\Ratsatak.Infrastructure\Persistence\RatsatakDbConte
xt.cs:line 33
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope ser
viceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope ser
viceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope ser
viceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope ser
viceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope ser
viceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope ser
viceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.
```

Which points out to the line `builder.OwnsMany(d => d.MunicipalityIds, municipalityIdBuilder => {...});` in `DepartmentConfigurations`.

I'm clueless why when I run just one configuration, the migration succedes but the opposite is true when two configurations are involved, and the error appears to happen when defining a `.OwnsMany()` relationship which is not tied to the preceeding aggregate. It seems that when the preceeding aggregate, in this case `Office` has a list of Id value objects of the following aggregate `Department`, the `.OwnsMany()` method fails with the next in line aggregate ids (`MunicipalityId`). This happens even if I include the `MunicipalityConfigurations`.

Am I missing something here or is it a EF Core bug?

EF Core version:
Microsoft.EntityFrameworkCore 7.0.3
Microsoft.EntityFrameworkCore.Design 7.0.3.
Microsoft.EntityFrameworkCore.SqlServer 7.0.3.

**Comment by kcindric** [comment]
it seems there is another issue ([#30295](https://github.com/dotnet/efcore/issues/30295)) opened with a similar problem. I'm happy to provide a runable project throwing the same error if it makes it easier to debug.

**Comment by ajcvickers** [comment]
@kcindric A runnable project for this would be very helpful!

**Comment by kcindric** [comment]
> @kcindric A runnable project for this would be very helpful!

Here you go!
https://github.com/kcindric/EF-DDD-problem

**Comment by ajcvickers** [comment]
Note for triage: this is another case (e.g. like #30107) where a CLR type is first configured as a non-entity type (`builder.Property(m => m.DepartmentId)`), and then later configured again as an entity type (`builder.OwnsMany(o => o.DepartmentIds, ...`). We should handle this better, either with an eager exception with a better message, or in model validation.

@kcindric A given CLR type cannot be used as both an entity type and as the type of a normally mapped property.

**Comment by stephtr** [comment]
Just for your information, I also ran into this error with the following code and SqLite:
`modelBuilder.Entity<Parent>().OwnsMany(q => q.ChildItem, options => options.ToJson());`
If I just use `modelBuilder.Entity<Parent>().OwnsMany(q => q.ChildItem);` it worked.
I could also provide a sample project, if that would help.

**Comment by NikolaVranes** [comment]
@kcindric Is this fixed?

**Comment by jorgecardoso220** [comment]
Any ideas on how to resolve this?

**Comment by kcindric** [comment]
@NikolaVranes & @jorgecardoso220 I "fixed" this by not using strongly typed IDs and using plain int IDs instead.

Example of my Domain and EF Configuration files:

```c#
public class Department : AggregateRoot<int>
{
    private Department(int departmentId, string name, int officeId, DateTime createdDateTime,
        DateTime updatedDateTime) :
        base(departmentId)
    {
        Id = departmentId;
        Name = name;
        OfficeId = officeId;
        CreatedDateTime = createdDateTime;
        UpdatedDateTime = updatedDateTime;
    }

    private Department()
    {
    }

    public string Name { get; private set; }
    public int OfficeId { get; private set; }
    public DateTime CreatedDateTime { get; private set; }
    public DateTime UpdatedDateTime { get; private set; }

    public static Department Create(int departmentId, string name, int officeId)
    {
        return new Department(departmentId, name, officeId, DateTime.UtcNow, DateTime.UtcNow);
    }
}
```

```c#
public class DepartmentConfigurations : IEntityTypeConfiguration<Department>
{
    public void Configure(EntityTypeBuilder<Department> builder)
    {
        ConfigureDepartmentTable(builder);
    }

    private void ConfigureDepartmentTable(EntityTypeBuilder<Department> builder)
    {
        builder.ToTable(nameof(Department), nameof(Department));

        builder.HasKey(d => d.Id);
        
        builder.Property(d => d.Id)
            .ValueGeneratedNever();

        builder.HasOne<Office>()
            .WithMany()
            .HasForeignKey(d => d.OfficeId);
    }
}
```

There's a workaround that Amichai mentioned in his video but I find that approach too complicated:
https://www.youtube.com/watch?v=B3Iq346KwUQ

Hope it helps!

**Comment by jorgecardoso220** [comment]
Thank you @kcindric. I found that workaround too and i am testing it when i can
