### ISSUE TITLE
How to remove all previous migrations and create a new "Initial" migration from existing stable DB?

### ISSUE THREAD

**Issue by khteh** [dotnet/efcore#30381]
## Ask a question
As the number of migrations grow overtime, I would like to remove all the previous migration files from `Migrations` folder and create a new "Initial" migration from existing DB after the schema has firmed up - without any impact to the production DB. I am thinking of using the following steps:

(1) Backup
(2) `DELETE FROM public."__EFMigrationsHistory";`
(3) `rm -rf migrations`
(4) `dotnet-ef migrations add initial -c <context>`
(5) `dotnet-ef update database -c <context>`

Would this work?

Remember:

* Please make your question as clear and specific as possible.
* Please check that the [documentation](https://docs.microsoft.com/ef/) does not answer your question.
* Please search in both [open](https://github.com/dotnet/efcore/issues) and [closed](https://github.com/dotnet/efcore/issues?q=is%3Aissue+is%3Aclosed) issues to check that your question has not already been answered.

### Include your code

Usually the best way to ask a clear question and get a quick response is to show your code. Preferably, attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing.

Use triple-tick code fences for any posted code. For example:

```C#
Console.WriteLine("Hello, World!");
```

### Include stack traces

Include the full exception message and stack trace for any exception you encounter.

Use triple-tick fences for stack traces. For example:

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at SixFour.Sub() in C:\Stuff\AllTogetherNow\SixFour\SixFour.cs:line 49
   at SixFour.Main() in C:\Stuff\AllTogetherNow\SixFour\SixFour.cs:line 54
```

### Include verbose output

Please include verbose output when asking questions about the `dotnet ef` or Package Manager Console tools.

Use triple-tick fences for tool output. For example:

```
C:\Stuff\AllTogetherNow\FiveOh>dotnet ef dbcontext list --verbose
Using project 'C:\Stuff\AllTogetherNow\FiveOh\FiveOh.csproj'.
...
Finding DbContext classes in the project...
Found DbContext 'BlogContext'.
BlogContext
```

### Include provider and version information

EF Core version: 7.0.103
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer) PostgreSQL
Target framework: (e.g. .NET 6.0) .NET 7.0
Operating system: Ubuntu 22.10
IDE: (e.g. Visual Studio 2022 17.4) VSCode

**Comment by roji** [comment]
@khteh not quite; that last `dotnet update` would see an empty `__EFMigrationsHistory` table in your database, and would therefore try to apply that new initial migration; but all the schema is already there, so that would fail.

To do this, follow the instructions [in our docs](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli).

**Comment by khteh** [comment]
I suppose I should be following https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli#resetting-all-migrations but kind of data to insert to the single row into the migrations history table? Thanks.
