### ISSUE TITLE
Running il formed ef tool command does not yield helpful output

### ISSUE THREAD

**Issue by cxleb** [dotnet/efcore#30487]
## Running il formed ef tool command does not yield helpful output

Using ef core tools on the command line I run this command, while i am aware this is probably il formed this is not a good error message. This seems to happen irrespective of the project.

```batch
> dotnet ef database update --msbuildprojectextensionspath
```

### Include stack traces

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.ParseOption(Boolean isLongOption, CommandLineApplication command, String[] args, Int32& index, CommandOption& option)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Index was outside the bounds of the array.
```

EF Core version: tools version 7.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: net6.0
Operating system: Windows 11
IDE: none

**Comment by ajcvickers** [comment]
Note for triage: I can't find any existing issue about updating the command line parsing.

**Comment by ajcvickers** [comment]
Note for triage: #6850. We closed it last year.
