### ISSUE TITLE
Regression in v7.0.4: "Unable to cast object of type..." when using nullable primary key

### ISSUE THREAD

**Issue by bkoelman** [dotnet/efcore#30489]
After updating to EF Core v7.0.4, several of our tests are failing. What they have in common is a nullable private key. I suspect this is caused by #30219.

### Include your code

The code below throws during `SaveChanges()`. Uncommenting the AppContext switch makes it print "Game:Id=0", which is the expected behavior.

```C#
using Microsoft.EntityFrameworkCore;

// AppContext.SetSwitch("Microsoft.EntityFrameworkCore.Issue29985", true);

using (var dbContext = new ZeroKeyDbContext())
{
    dbContext.Database.EnsureDeleted();
    dbContext.Database.EnsureCreated();

    dbContext.Games.Add(new Game { Id = 0 });
    dbContext.SaveChanges();
}

using (var dbContext = new ZeroKeyDbContext())
{
    var game = dbContext.Games.First();
    Console.WriteLine($"Game:Id={game.Id}");
}

public sealed class Game
{
    public int? Id { get; set; }
}

public sealed class ZeroKeyDbContext : DbContext
{
    public DbSet<Game> Games => Set<Game>();

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseNpgsql(
            "Host=localhost;Port=5432;Database=Example;User ID=postgres;Password=postgres;Include Error Detail=true");
    }
}
```

### Include stack traces

```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.EntityFrameworkCore.Update.Internal.RowKeyValueFactoryFactory.Create(IUniqueConstraint key)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.UniqueConstraint.GetRowKeyValueFactory()
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.AddUniqueValueEdges()
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.TopologicalSort(IEnumerable`1 commands)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.<BatchCommands>d__9.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Program.<Main>$(String[] args) in D:\Bart\Source\Projects\EFCoreBug29985\EFCoreBug29985\Program.cs:line 11

  This exception was originally thrown at this call stack:

Inner Exception 1:
InvalidCastException: Unable to cast object of type 'System.Func`3[System.Nullable`1[System.Int32],System.Nullable`1[System.Int32],System.Boolean]' to type 'System.Func`3[System.Int32,System.Int32,System.Boolean]'.
```

### Include provider and version information

EF Core version: 6.0.4
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET 6.0
Operating system: Windows 11 Pro 22H2
IDE: Visual Studio 2022 17.4.5

**Comment by ajcvickers** [comment]
@bkoelman I'm not able to reproduce this. Can you post the csproj file you are using? I have:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace />
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="7.0.4" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="7.0.3" />
  </ItemGroup>

</Project>
```

**Comment by bkoelman** [comment]
```xml
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.*" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="7.0.*" />
	</ItemGroup>
</Project>
```

![image](https://user-images.githubusercontent.com/10324372/225331912-8fa772aa-e1cf-429c-b3ad-63173bcac3cf.png)

```bash
D:\Bart\Source\Repos> dotnet --list-sdks
6.0.407 [C:\Program Files\dotnet\sdk]
7.0.101 [C:\Program Files\dotnet\sdk]
7.0.102 [C:\Program Files\dotnet\sdk]
7.0.104 [C:\Program Files\dotnet\sdk]
7.0.202 [C:\Program Files\dotnet\sdk]
D:\Bart\Source\Repos> dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by ajcvickers** [comment]
@bkoelman I am able to reproduce this only when version 7.0.3 of `Microsoft.EntityFrameworkCore.Relational` is being used. Make sure that 7.0.4 is being used. For example:

```xml
<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="7.0.4" />
```

**Comment by bkoelman** [comment]
Yes, that solves the problem. I was pretty surprised by this. Without the extra package reference, the next snippet:
```c#
Console.WriteLine(typeof(QuerySplittingBehavior).Assembly);
```
prints:
```
Microsoft.EntityFrameworkCore.Relational, Version=7.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
```
The reason is that Npgsql.EntityFrameworkCore.PostgreSQL imports the older (incompatible) version.

![image](https://user-images.githubusercontent.com/10324372/225462672-d447f259-2ec3-4842-aed8-eaec6e8aea8e.png)



Our actual project setup is a lot more complicated (I'll spare you the details), but now I understand what's going on and can adapt it accordingly. Our assumption that Microsoft.EntityFrameworkCore imports Microsoft.EntityFrameworkCore.Relational turns out to be wrong; it's the other way around and that makes perfect sense.

I don't think there's anything wrong with the Microsoft.EntityFrameworkCore or Npgsql.EntityFrameworkCore.PostgreSQL packages, so I'm closing this.

Thanks for helping out!
