### ISSUE TITLE
ef dbcontext scaffold pass argument file to avoid argument limit exceeded errors

### ISSUE THREAD

**Issue by JanKotschenreuther** [dotnet/efcore#30532]
## What problem are you trying to solve?

We got a large database schema with 986 tables/views which is continiously growing.
Because the database is our source of truth, we are using the database-first method to rescaffold our application models each time using `dotnet ef dbcontext scaffold ...`.
Each of our model projects therefore contains a Scaffold-DbContext.ps1 script which also helps tracking changes with Git or any other source control.
This approach allows us to automate the model updates with our db-updates in our CI/CD-Pipeline.

An example script may look like this:

```ps1
dotnet `
ef `
dbcontext `
scaffold `
'MyConnectionString' `
Microsoft.EntityFrameworkCore.SqlServer `
--no-onconfiguring `
--no-pluralize `
--use-database-names `
--data-annotations `
--project MyProject.csproj `
--namespace My.Project `
--context MyDbContext `
--context-namespace My.Project `
--context-dir MyDbContext `
--output-dir MyDbContext\Models `
 `
--table Article `
--table ArticleItem `
--table ArticleItemDetail `
...
... (lots more tables/views)
...
--table WebShop `
--table WebShopOrder `
--table WebShopOrderDetail `
 `
--force

```

As soon as those commands grow to long, meaning there are to many arguments, the command line will no longer start the process.

![image](https://user-images.githubusercontent.com/20000282/226354901-b2b835df-83e0-467f-99b3-5490469cf423.png)

This happens due to the [command-line-string-limitation](https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation).

## Describe the solution you'd like

As a solution i suggest that the tool 'dotnet ef dbcontext scaffold' or 'dotnet ef dbcontext' or 'dotnet ef' learns to accept a file which can contain more arguments.

The file could be passed as an argument which could be introduced with an "@".
For example:
```ps1
dotnet ef dbcontext scaffold @my-argument-file.txt
```

The file could contain an argument/option on each line or on a single line.
For example:

```txt
'MyConnectionString'
Microsoft.EntityFrameworkCore.SqlServer
--no-onconfiguring
--no-pluralize
--use-database-names
--data-annotations
--project MyProject.csproj
--namespace My.Project
--context MyDbContext
--context-namespace My.Project
--context-dir MyDbContext
--output-dir MyDbContext\Models

--table Article
--table ArticleItem
--table ArticleItemDetail
...
... (lots more tables/views)
...
--table WebShop
--table WebShopOrder
--table WebShopOrderDetail

--force

```

The MSBuild command line supports similar solutions with rsp files:
- [https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-response-files?view=vs-2022](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-response-files?view=vs-2022)

**Comment by ErikEJ** [comment]
You can use -t instead of --table

**Comment by JanKotschenreuther** [comment]
Thanks for the hint @ErikEJ , this option can for sure reduce the length and move the problem to a much later point of time. But as I mentioned, our database schema is constantly growing and I am sure sooner or later we will get back to that problem and need a solution.

**Comment by ajcvickers** [comment]
Note for triage: even when using the arguments file, the same error is generated:

```
PS C:\local\code\AllTogetherNow\Daily> dotnet ef dbcontext scaffold `@arguments.txt
Build started...
Build succeeded.
System.ComponentModel.Win32Exception (206): An error occurred trying to start process 'dotnet' with working directory 'C:\local\code\AllTogetherNow\Daily\'. The filename or extension is too long.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.EntityFrameworkCore.Tools.Exe.Run(String executable, IReadOnlyList`1 args, String workingDirectory, Boolean interceptOutput)
   at Microsoft.EntityFrameworkCore.Tools.RootCommand.Execute(String[] _)
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0(String[] args)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
An error occurred trying to start process 'dotnet' with working directory 'C:\local\code\AllTogetherNow\Daily\'. The filename or extension is too long.
PS C:\local\code\AllTogetherNow\Daily>
```

**Comment by ajcvickers** [comment]
@JanKotschenreuther Would an [exclude list](https://github.com/dotnet/efcore/issues/6182) help in your case? That is, do you want to include most tables, and only exclude some?

**Comment by JanKotschenreuther** [comment]
@ajcvickers that solution does not sound very appealing.
I would prefer a solution with argument files.

- Using excludes instead of includes may still cause the argument limit to be reached. Imagine a model which includes half of the db-objects in the database, switching to exclude would still require the other half to be excluded. I am sure that can still happen sooner or later.
- Monitoring changes on those scripts in Git can be pretty important, switching between includes/excludes because of add/removed db-objects may decrease a good overview of changes happening.
- We would need to teach our custom tooling the excludes and to update the scripts accordingly, switching between includes/excludes, depending on the string length of arguments to pass. Which itself depends on the length of db-object-names and option-keys.

**Comment by boggye** [comment]
I would like to see this done as well. We have a database first implementation, and more than one developer works on this project.  The EF Core tools don't support adding deltas, i.e. running the command to add a table to an existing db context. Then the next best thing would be to be able to specify a list of tables that can be modified, merged via git and so on. But it is not possible for bigger databases when you have lots of tables due to the command line limitations

**Comment by boggye** [comment]
Hello - sorry to bug you about this, but are there any plans to modify the scaffold cmd cli to accept basically command line parameters from a text file? I think @JanKotschenreuther idea is the best because it allows us to circumvent the command line length limitations.

I am working on a sql server database that has lots of tables and views, all under the dbo schema. I need to add the tables to the EF context but I don't need the vast majority of the views. The views and the tables are are also used by other parts of the system, such as reporting and an MS Access application. My hands are tied because I have to maintain backwards compatibility with these legacy parts of the system that cannot be changed. I thought of using synonyms but whatever I do I hit some obstacle somewhere, such as MS Access not supporting synonyms (i.e. attaching tables by synonyms). And all this because the scaffold tool doesn't allow us to specify a fine grained filter of the sql objects that one wants to add to the DbContext.

Other ideas: allow us to include sql objects by specifying a wildcard pattern or a regular expression pattern. 

If you cannot implement this request in the next couple of weeks, what other options do I have to make it work? I am thinking of modifying the tool myself. Is it doable? Where can I find the source code?

**Comment by ErikEJ** [comment]
@boggye why not just use EF Core Power Tools?

**Comment by boggye** [comment]
I kind of like the command line utilities, they are simple, predictable and work well when it comes to code merges (more than one person works on the project). Usually the devil is in the details, I don't know how the EF Core Power Tools work exactly, how it keeps track of the sql objects selection, and honestly, I don't need another diagram tool. I already use Power Designer for database design.

**Comment by ErikEJ** [comment]
EF core Power Tools is available as a command line tool - think EF dbcontext scaffold on steriods

**Comment by boggye** [comment]
@ErikEJ  thank you. Is it possible to install only the EF Power Tools command line utility? I am not using VS 2022 for development. I use Rider.Net. 
Update: I found the instructions here: https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/Core/efcpt.8/readme.md

I will give it a try. Thank you again

**Comment by boggye** [comment]
@ErikEJ - I managed to switch the EF entities generation to the EF Core Power Tools cli! All good, it works as expected. One question though, when including tables or views, is it possible to select all tables that belong to a schema, without having to specify them one by one?

**Comment by ErikEJ** [comment]
@boggye Not at the moment, no
