### ISSUE TITLE
 The value of '<key>' is unknown - property is part of a foreign key for which the principal entity in the relationship is not known

### ISSUE THREAD

**Issue by ZeroSkill1** [dotnet/efcore#30623]
I'm trying to define a many-many relationship as per the [documentation](https://learn.microsoft.com/en-us/ef/core/modeling/relationships/many-to-many#basic-many-to-many), using the below code:

```C#
public class Left
{
	[Key] public long Id { get; set; }
	public string Name { get; set; }

	public List<Right> Rights { get; set; }
}
public class Right
{
	[Key] public long Id { get; set; }
	public string Name { get; set; }

	public List<Left> Lefts { get; set; }
}

public class TestDbCtx : DbContext
{
	public TestDbCtx(DbContextOptions<TestDbCtx> options) : base(options) { }

	public DbSet<Left> Lefts { get; set; }
	public DbSet<Right> Rights { get; set; }

	public static TestDbCtx Create(string dbHost, ushort port, string username, string password, string dbName, ILoggerFactory loggerFactory)
	{
		string connStr = string.Format(
			"User ID={0};Password={1};Host={2};Port={3};Database={4};",
			username,
			password,
			dbHost,
			port,
			dbName
		);

		DbContextOptionsBuilder<TestDbCtx> options = new DbContextOptionsBuilder<TestDbCtx>();

		options.UseLoggerFactory(loggerFactory);
		options.UseNpgsql(connStr);
		options.EnableSensitiveDataLogging(true);

		return new TestDbCtx(options.Options);
	}

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		base.OnModelCreating(modelBuilder);

		modelBuilder.Entity<Right>();
		modelBuilder.Entity<Left>(entity =>
		{
			entity
				.HasMany(t => t.Rights)
				.WithMany(t => t.Lefts);
		});
	}
}
```

```c#
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Serilog;

namespace Test;

public static class Program
{
	public static ILoggerFactory LogFactory { get; set; } = null!;

	public static void InitLogger(LoggerConfiguration? config = null)
	{
		Log.Logger = (config ??
			new LoggerConfiguration()
				.WriteTo
					.Console())
			.CreateLogger();

		LogFactory = new LoggerFactory()
			.AddSerilog();
	}

	public static void DeinitLogger()
	{
		Log.CloseAndFlush();
		LogFactory = null!;
	}

	public static async Task<int> Main(string[] args)
	{
		InitLogger();

		try
		{
			await using (TestDbCtx ctx = TestDbCtx.Create("127.0.0.1", 5432, "postgres", "password", "testdb", LogFactory))
			{
				var lefts = await ctx.Lefts.ToListAsync();
				List<Right> rights = await ctx.Rights.ToListAsync();

				if (lefts.Count == 0 || rights.Count == 0)
				{
					Log.Information("no entries");
				}
				else
				{
					foreach (var x in rights)
					{
						if (x.Lefts is null) x.Lefts = new List<Left>();
						x.Lefts.Add(lefts[0]);
					}

					await ctx.SaveChangesAsync();
				}
			}
		}
		catch (Exception ex)
		{
			Log.Error(ex.Message);
		}

		DeinitLogger();

		return 0;
	}
}
```

This should be working, however, the following exception is thrown:
```
[14:17:19 ERR] An exception occurred in the database while saving changes for context type 'Test.TestDbCtx'.
System.InvalidOperationException: The value of 'LeftRight (Dictionary<string, object>).LeftsId' is unknown when attempting to save changes. This is because the property is also part of a foreign key for which the principal entity in the relationship is not known.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.PrepareToSave()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetEntriesToSave(Boolean cascadeChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

This is a test project I made to make sure it isn't related to me using unconventional table/column names (same code, just with the `Column` and `Table` attributes applied to the classes and properties). The following schema is created when using `ctx.Database.EnsureCreated()`:
```SQL
CREATE DATABASE testdb;

CREATE TABLE "Lefts" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    CONSTRAINT "PK_Lefts" PRIMARY KEY ("Id")
);

CREATE TABLE "Rights" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    CONSTRAINT "PK_Rights" PRIMARY KEY ("Id")
);

CREATE TABLE "LeftRight" (
    "LeftsId" bigint NOT NULL,
    "RightsId" bigint NOT NULL,
    CONSTRAINT "PK_LeftRight" PRIMARY KEY ("LeftsId", "RightsId"),
    CONSTRAINT "FK_LeftRight_Lefts_LeftsId" FOREIGN KEY ("LeftsId") REFERENCES "Lefts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_LeftRight_Rights_RightsId" FOREIGN KEY ("RightsId") REFERENCES "Rights" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_LeftRight_RightsId" ON "LeftRight" ("RightsId");
```

From what I've read in the docs, this should be working as-is, without further configuration.

EF Core version: 7.0.4
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL 7.0.3
Target framework: .NET 7.0
Operating system: Ubuntu 22.04.2 LTS
IDE: Visual Studio Code 1.76.2

**Comment by ZeroSkill1** [comment]
Logging the changes from the change tracker, the following is revealed:
```
[22:27:03 INF] LeftRight (Dictionary<string, object>) {LeftsId: -2147482647, RightsId: -2147482647} Added
  LeftsId: -2147482647 PK FK Temporary Unknown
  RightsId: -2147482647 PK FK Temporary Unknown
LeftRight (Dictionary<string, object>) {LeftsId: -2147482646, RightsId: 1} Added
  LeftsId: -2147482646 PK FK Temporary Unknown
  RightsId: 1 PK FK
Left {Id: 0} Unchanged
  Id: 0 PK
  Name: 'l1'
  Rights: [{Id: 0}, {Id: 1}]
Left {Id: 1} Unchanged
  Id: 1 PK
  Name: 'l2'
  Rights: <null>
Right {Id: 0} Unchanged
  Id: 0 PK
  Name: 'r1'
  Lefts: [{Id: 0}]
Right {Id: 1} Unchanged
  Id: 1 PK
  Name: 'r2'
  Lefts: [{Id: 0}]
  ```
  
  I use this small set of commands to add some test data:
  ```SQL
  INSERT INTO "Lefts" VALUES(0, 'l1');
INSERT INTO "Lefts" VALUES(1, 'l2');
INSERT INTO "Rights" VALUES(0, 'r1');
INSERT INTO "Rights" VALUES(1, 'r2');
```
  
  I'm not quite sure what this means.

**Comment by ZeroSkill1** [comment]
Okay, after some further investigation and reading through #25077, I tried adding a pair to `LeftRight` such that the ID of `Left` and the ID of `Right` are nonzero (1,1). This did the trick and the query succeeded:
```
LeftRight {LeftsId: 1, RightsId: 1} Added
  LeftsId: 1 PK FK
  RightsId: 1 PK FK

[22:51:57 INF] Executed DbCommand (16ms) [Parameters=[@p0='1', @p1='1'], CommandType='Text', CommandTimeout='30']
INSERT INTO "LeftRight" ("LeftsId", "RightsId")
VALUES (@p0, @p1);
```

**Comment by ajcvickers** [comment]
@ZeroSkill1 When using generated key values, the CLR default (zero in this case) indicates that the key value has not been set. EE [
Generated versus explicit key values](https://learn.microsoft.com/en-us/ef/core/change-tracking/explicit-tracking#generated-versus-explicit-key-values).
