### ISSUE TITLE
SQL View HasNoKey overwrite with a Key not working when not overwriting OnModelCreating

### ISSUE THREAD

**Issue by xutbest** [dotnet/efcore#30652]
## SQL View HasNoKey overwrite with a Key not working when not overwriting OnModelCreating

I know there is an issue in EFCore 5 that is closed but I get the same problem in EFCore 7.0.4 but I try the same thing with 7.0

Linked to this issue: https://github.com/dotnet/efcore/issues/24789

Steps: 
- You need two tables, one with a foreign key linked on the other. Create both as views.
- Run this command:

```
Scaffold-DbContext -UseDatabaseNames "Server=(Server);Database=(Database);Trusted_Connection=True;encrypt=false" Microsoft.EntityFrameworkCore.SqlServer -OutputDir "Models" -Force -NoOnConfiguring -ContextDir ExampleDBContext -Context ExampleDBContext -Tables dbo.Tenant, dbo.Unit
```
- The command should look like this in OnModelCreating:
```C#
modelBuilder.Entity<Tenant>(entity =>
        {
             entity
                .HasNoKey()
                .ToView("Tenant");

            ...
        });

        modelBuilder.Entity<Unit>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("Unit");
            ...
        });
```
- Add object to both partial class Unit and Tenant (by creating a new partial class)
```C#
public partial class Unit
{
    public IList<Tenant> Tenants { get; set; } = new List<Tenant>();
}

public partial class Tenant
{
    [NotMapped]
    [JsonIgnore]
    public Unit? UnitNavigation { get; set; }
}
```
- Create this partial class
```C#
public partial class ExampleDBContext : DbContext
    {

        public ExampleDBContext()
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("ConnectionString");
            }
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
        {

            modelBuilder.Entity<Tenant>(entity =>
            {
                entity.ToTable(nameof(Tenant));
                entity.HasKey(e => e.Id);

            });


            modelBuilder.Entity<Unit>(entity =>
            {
                entity.ToTable(nameof(Unit));
                entity.HasKey(e => e.Id);

            });
        }
    }
```
- I'm getting the stack trace below if the code looks like this
- If I change the auto-generated ExampleDbContext from .HasNoKey() to .HasKey(x => x.Id), I get no error.

**I don't want to change the auto-generated because the partial class is supposed to overwrite the no key but it is clear that it is not making any thing. I try to add  entity.Metadata.IsKeyless = false; in the overwrite partial class ExampleDBContext, this is not working as well.**

### Result when getting error
```
Unhandled exception. System.InvalidOperationException: Unable to determine the relationship represented by navigation 'Unit.Tenants' of type 'IList<Tenant>'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidatePropertyMapping(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal.SqlServerModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Collections.Generic.IAsyncEnumerable<TEntity>.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in D:\Documents\Project\ConsoleTest\Program.cs:line 5
   at Program.<Main>(String[] args)
```

I'm waiting to know if there is a solution ou if it is a bug.

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 6.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.5.3

**Comment by ajcvickers** [comment]
@xutbest You can explicitly configure the relationship in the partial class. For example:

```C#
partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Tenant>(entity =>
    {
        entity.ToTable(nameof(Tenant));
        entity.HasKey(e => e.Id);
    });

    modelBuilder.Entity<Unit>(entity =>
    {
        entity.ToTable(nameof(Unit));
        entity.HasKey(e => e.Id);
        entity.HasMany(e => e.Tenants).WithOne();
    });
}
```

Note for triage: full repro:

```C#
using (var context = new SomeDbContext())
{
    context.Database.EnsureDeleted();
    context.Database.EnsureCreated();
}

public partial class Unit
{
    public int Id { get; set; }
}

public partial class Tenant
{
    public int Id { get; set; }
}

public partial class Unit
{
    public IList<Tenant> Tenants { get; set; } = new List<Tenant>();
}

public partial class Tenant
{
    [NotMapped]
    [JsonIgnore]
    public Unit? UnitNavigation { get; set; }
}

public partial class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer(@"Data Source=(LocalDb)\MSSQLLocalDB;Database=AllTogetherNow")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Tenant>(entity =>
        {
            entity.HasNoKey().ToView("Tenant");
        });

        modelBuilder.Entity<Unit>(entity =>
        {
            entity.HasNoKey().ToView("Unit");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
    {
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

public partial class SomeDbContext
{
    partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Tenant>(entity =>
        {
            entity.ToTable(nameof(Tenant));
            entity.HasKey(e => e.Id);
        });

        modelBuilder.Entity<Unit>(entity =>
        {
            entity.ToTable(nameof(Unit));
            entity.HasKey(e => e.Id);
            // entity.HasMany(e => e.Tenants).WithOne();
        });
    }
}
```

**Comment by xutbest** [comment]
@ajcvickers I just want to know why I need to specify the relationship if I don't directly put the HasKey regenerated from command line?

If I put HasKey directly in auto-generated file, everything works the same way without specify the relationship between views. Why is that?

**Comment by ajcvickers** [comment]
Yes, that's probably a bug/limitation of the current conventions.

**Comment by xutbest** [comment]
Can it be fixed in the near future?

**Comment by ajcvickers** [comment]
Likely, yes--we will discuss in the normal triage process. However, the priority is low, since, as I indicated above, there is a very simple workaround that can be used in the non-generated part of the partial class.

**Comment by saurabhm19781** [comment]
This workaround for defining key in "partial void OnModelCreatingPartial(ModelBuilder modelBuilder)" do not work with OData. As soon as you run the solution, you get the same exception. A fix for this issue will be highly appreciated.

**Comment by jtlowe** [comment]
Do the entity configurations have to be explicitly defined in `OnModelCreatingPartial` for them to override the generated configurations?

When I use `modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());` in `OnModelCreatingPartial()` to configure a key for a keyless table, the configuration isn't used when configuring the relationships. This results in error "The navigation 'Unit' cannot be added because it targets the keyless entity type 'Unit'. Navigations can only target entity types with keys."

```cs
public partial class SomeDbContext : DbContext
{
    ...
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Unit>(entity =>
        {
            entity.HasNoKey();
        });
        OnModelCreatingPartial(modelBuilder);
    }
    ...
}

public partial class SomeDbContext
{
    partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
    {
     modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());
    }
}


internal class UnitConfiguration: IEntityTypeConfiguration<Unit>
{
    public void Configure(EntityTypeBuilder<Unit> entity)
    {
        entity.HasKey(e => new { e.Code1, e.Code2, e.Code3 });
    }
}

```

**Comment by ajcvickers** [comment]
@jtlowe If you are having an issue with this, then please open a _new_ issue and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
