### ISSUE TITLE
Executing efbundle leads to failure in loading Microsoft.Extensions.Configuration.FileExtensions file/nuget

### ISSUE THREAD

**Issue by acpsa** [dotnet/efcore#30656]
## What could be the cause of this error 

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileNotFoundException:
File name: 'Microsoft.Extensions.Configuration.FileExtensions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at DataAccess.Dbcontexts.DesignTimeDbContextFactory.CreateDbContext(String[] args)
...
```

What I am trying to do:

My solution has different projects (all dotnet 7):
1. Core
2. DataAccess (DbContext source project)
3. Service
4. UI

I am able to run my solution just fine from the Visual-studio and also via hosting on IIS.

I am using the code first approach for Database migrations using **dotnet ef version 7.0.4**
My `CreateDbContext` method looks like this:
```
        public MyContext CreateDbContext(string[] args)
        {
            IConfigurationRoot configuration = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).
                AddJsonFile(@Directory.GetCurrentDirectory() + ".<UI project path>.//appsettings.json").Build();

            var connectionString = configuration.GetConnectionString("MyAppConnection");
...
```
**Everything works fine when I am doing migrations manually and updating the database using dotnet ef CLI commands.**

I started working with [dotnet ef migrations bundles](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli#bundles) for migrations from release pipelines. 
When I create a bundle using `dotnet ef migrations bundle -f -v --self-contained` the `efbundle.exe` is generated

But when executing the `efbudle.exe`, there is an error as follows:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileNotFoundException:
File name: 'Microsoft.Extensions.Configuration.FileExtensions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at DataAccess.Dbcontexts.DesignTimeDbContextFactory.CreateDbContext(String[] args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContextFromFactory(Type factory, Type contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass21_2.<FindContextTypes>b__9()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsBundle.ExecuteInternal(String[] args)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsBundle.<>c__DisplayClass6_0.<Configure>b__0(String[] args)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsBundle.Execute(String context, Assembly assembly, Assembly startupAssembly, String[] args)
Exception has been thrown by the target of an invocation.
```
I've tried using different options for generating the bundle:
```
dotnet ef migrations bundle -f -v
dotnet ef migrations bundle --self-contained --startup-project "<Path To UI Project>\UI.csproj" -f -v
dotnet ef migrations bundle --self-contained --context MyContext --project "<Path To DataAccess Project>\DataAccess.csproj" --startup-project "<Path To UI Project>\UI.csproj" -f -v
```
And executing the efbundle:
```
.\efbundle.exe --connection 'MyConnectionString'
.\efbundle.exe
```
Each time the Configuration nuget/file fails to be loaded.

Is this an error with `efbundle `or nuget packages?
I even searched the nuget package folders and the respective dll files were present there

### Provider and version information

EF Core version:  7.0.4
Database provider: Pomelo.EntityFrameworkCore.MySql (7.0.0)
Target framework: NET 7.0
Operating system: Win 10 Enterprise x64
IDE: Visual Studio 2022 (x64) 17.5.3

**Comment by acpsa** [comment]
It was a package dependency problem (and not efcore problem) as some dependencies were not loading due to `PrivateAssets` property selectively enabled for the dependency: `Microsoft.EntityFrameworkCore.Design`.

Changing the property `PrivateAssets` to `none` in the `DataAccess.csproj` file resolved the problem and now the `efbundle.exe` works as expected.

After the change the PackageReference entry of `Microsoft.EntityFrameworkCore.Design` looks like this:
```
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.4">
    <PrivateAssets>none</PrivateAssets>
</PackageReference>
```

Also, the `appsettings.json` file is also needed with the `efbundle.exe` to work (same folder).
