### ISSUE TITLE
SetCommandTimeout seems like it is not working

### ISSUE THREAD

**Issue by eSPiYa** [dotnet/efcore#30688]
We're using .NET 6.0.16 and noticed that it seems like SetCommandTimeout is not working for migration when using the `update-database` command or when running the application under IIS Express(we have automatic migration when running the application). But have no issue when we run it as a standalone application.

In the Program.cs, we call this Seed method and pass the DB Context from the injected in the Services:
```C#
public class AppContextSeed
    {
        public static void Seed(AppDbContext appContext, int migrationsTimeout)
        {
            appContext.Database.SetCommandTimeout(migrationsTimeout);
            appContext.Database.Migrate();
        }
    }
```
It times out after several seconds even if I pass a massive number or even hardcoded the value with `TimeSpan.FromHours(1)`.

I tried to set the command timeout within the constructor of the DB Context for an hour and was able to finish the data migration and seeding. But I think it is not good idea to set the timeout within the constructor of `AppContextSeed`. I have a hunch that this is a bug.

EF Core version: 6.0.16
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows
IDE: Visual Studio 2022 17.5.4

**Comment by ajcvickers** [comment]
@eSPiYa I am not able to reproduce this. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by eSPiYa** [comment]
> @eSPiYa I am not able to reproduce this. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

I tried to recreate the structure of the code as much as possible. I checked the original sql script file and found out that it is inserting 21,320 records so I just created a loop of similar insert statement I found in there.

Here's the file:
[SetCommandTimeout.zip](https://github.com/dotnet/efcore/files/11256927/SetCommandTimeout.zip)

**Comment by ajcvickers** [comment]
@eSPiYa Still doesn't repro for me. It took ~96 seconds to seed the data and never timed out. Can you post the log output you see?

```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (95,751ms) [Parameters=[], CommandType='Text', CommandTimeout='3600']
      DECLARE
        @Counter INT = 1,
        @Count INT = 21320,
        @Property1 nvarchar(MAX),
        @Property2 nvarchar(MAX),
        @Property3 nvarchar(MAX),
        @Property4 nvarchar(MAX),
        @SearchCode nvarchar(MAX),
        @Value decimal(18, 2);

      WHILE (@Counter <= @Count)
        BEGIN
                SELECT @Property1 = CONVERT(varchar(255), NEWID());
                SELECT @Property2 = CONVERT(varchar(255), NEWID());
                SELECT @Property3 = CONVERT(varchar(255), NEWID());
                SELECT @Property4 = CONVERT(varchar(255), NEWID());
                SELECT @SearchCode = CONVERT(varchar(255), NEWID());
                SELECT @Value = RAND();

                IF NOT EXISTS(SELECT TOP 1 1 FROM Factors WHERE SearchCode = @SearchCode) BEGIN INSERT INTO Factors(Property1, Property2, Property3, Property4, SearchCode, Value) VALUES(@Property1, @Property2, @Property3, @Property4, @SearchCode, @Value) END;

                SET @Counter = @Counter + 1;
        END
```

**Comment by eSPiYa** [comment]
@ajcvickers It works fine if you run the application directly. But it will timeout immediately when you apply the migration using `update-database`.

Here's the complete log output:
```
PM> update-database
Build started...
Build succeeded.
Microsoft.EntityFrameworkCore.Model.Validation[30000]
      No store type was specified for the decimal property 'Value' on entity type 'Factor'. This will cause values to be silently truncated if they do not fit in the default precision and scale. Explicitly specify the SQL server column type that can accommodate all the values in 'OnModelCreating' using 'HasColumnType', specify precision and scale using 'HasPrecision', or configure a value converter using 'HasConversion'.
Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 6.0.16 initialized 'AppDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer:6.0.16' with options: None
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (17ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (17ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (11ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [MigrationId], [ProductVersion]
      FROM [__EFMigrationsHistory]
      ORDER BY [MigrationId];
Microsoft.EntityFrameworkCore.Migrations[20402]
      Applying migration '20230418003927_addfactors'.
Applying migration '20230418003927_addfactors'.
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (30,026ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      DECLARE 
      	@Counter INT = 1, 
      	@Count INT = 21320,
      	@Property1 nvarchar(MAX),
      	@Property2 nvarchar(MAX),
      	@Property3 nvarchar(MAX),
      	@Property4 nvarchar(MAX),
      	@SearchCode nvarchar(MAX),
      	@Value decimal(18, 2);
      
      WHILE (@Counter <= @Count)
      	BEGIN
      		SELECT @Property1 = CONVERT(varchar(255), NEWID());
      		SELECT @Property2 = CONVERT(varchar(255), NEWID());
      		SELECT @Property3 = CONVERT(varchar(255), NEWID());
      		SELECT @Property4 = CONVERT(varchar(255), NEWID());
      		SELECT @SearchCode = CONVERT(varchar(255), NEWID());
      		SELECT @Value = RAND();
      
      		IF NOT EXISTS(SELECT TOP 1 1 FROM Factors WHERE SearchCode = @SearchCode) BEGIN INSERT INTO Factors(Property1, Property2, Property3, Property4, SearchCode, Value) VALUES(@Property1, @Property2, @Property3, @Property4, @SearchCode, @Value) END;
      
      		SET @Counter = @Counter + 1;
      	END
Failed executing DbCommand (30,026ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
DECLARE 
	@Counter INT = 1, 
	@Count INT = 21320,
	@Property1 nvarchar(MAX),
	@Property2 nvarchar(MAX),
	@Property3 nvarchar(MAX),
	@Property4 nvarchar(MAX),
	@SearchCode nvarchar(MAX),
	@Value decimal(18, 2);

WHILE (@Counter <= @Count)
	BEGIN
		SELECT @Property1 = CONVERT(varchar(255), NEWID());
		SELECT @Property2 = CONVERT(varchar(255), NEWID());
		SELECT @Property3 = CONVERT(varchar(255), NEWID());
		SELECT @Property4 = CONVERT(varchar(255), NEWID());
		SELECT @SearchCode = CONVERT(varchar(255), NEWID());
		SELECT @Value = RAND();

		IF NOT EXISTS(SELECT TOP 1 1 FROM Factors WHERE SearchCode = @SearchCode) BEGIN INSERT INTO Factors(Property1, Property2, Property3, Property4, SearchCode, Value) VALUES(@Property1, @Property2, @Property3, @Property4, @SearchCode, @Value) END;

		SET @Counter = @Counter + 1;
	END
Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
Operation cancelled by user.
 ---> System.ComponentModel.Win32Exception (258): The wait operation timed out.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:d9c8ba29-9b28-47ba-9658-9fb224770ac5
Error Number:-2,State:0,Class:11
Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
Operation cancelled by user.
```

**Comment by felaray** [comment]
Using .NET Core CLI produces the same result as PMC.

`dotnet ef database update --connection "Server=tcp:******.database.windows.net,1433;Initial Catalog=******;Persist Security Info=False;User ID=******;Password=******;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=180"`

Build started...
Build succeeded.
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (30,317ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      DECLARE @var1 sysname;
      SELECT @var1 = [d].[name]
      FROM [sys].[default_constraints] [d]
      INNER JOIN [sys].[columns] [c] ON [d].[parent_column_id] = [c].[column_id] AND [d].[parent_object_id] = [c].[object_id]
      WHERE ([d].[parent_object_id] = OBJECT_ID(N'[**********************]') AND [c].[name] = N'Name');
      IF @var1 IS NOT NULL EXEC(N'ALTER TABLE [**********************] DROP CONSTRAINT [' + @var1 + '];');
      ALTER TABLE [**********************] ALTER COLUMN [Name] nvarchar(450) NOT NULL;
Failed executing DbCommand (30,317ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
DECLARE @var1 sysname;
SELECT @var1 = [d].[name]
FROM [sys].[default_constraints] [d]
INNER JOIN [sys].[columns] [c] ON [d].[parent_column_id] = [c].[column_id] AND [d].[parent_object_id] = [c].[object_id]
WHERE ([d].[parent_object_id] = OBJECT_ID(N'[**********************]') AND [c].[name] = N'Name');
IF @var1 IS NOT NULL EXEC(N'ALTER TABLE [**********************] DROP CONSTRAINT [' + @var1 + '];');
ALTER TABLE [**********************] ALTER COLUMN [Name] nvarchar(450) NOT NULL;
fail: 2023/4/18 10:56:21.414 RelationalEventId.CommandError[20102] (Microsoft.EntityFrameworkCore.Database.Command)
      Failed executing DbCommand (30,317ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      DECLARE @var1 sysname;
      SELECT @var1 = [d].[name]
      FROM [sys].[default_constraints] [d]
      INNER JOIN [sys].[columns] [c] ON [d].[parent_column_id] = [c].[column_id] AND [d].[parent_object_id] = [c].[object_id]
      WHERE ([d].[parent_object_id] = OBJECT_ID(N'[**********************]') AND [c].[name] = N'Name');
      IF @var1 IS NOT NULL EXEC(N'ALTER TABLE [**********************] DROP CONSTRAINT [' + @var1 + '];');
      ALTER TABLE [**********************] ALTER COLUMN [Name] nvarchar(450) NOT NULL;
Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
 ---> System.ComponentModel.Win32Exception (258): 等候操作已逾時。
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:59dd5e58-a5db-4bbc-9ab3-361464ea56f4
Error Number:-2,State:0,Class:11
Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.

**Comment by ErikEJ** [comment]
ID=******;Password=******;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=180

You are setting the Connection Timeout, not Command Timeout.

If you use a newer version of SqlClient you can  set the "Command Timeout" in the connection string.

**Comment by felaray** [comment]
> ID=**;Password=**;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=180
> 
> You are setting the Connection Timeout, not Command Timeout.
> 
> If you use a newer version of SqlClient you can set the "Command Timeout" in the connection string.

@ErikEJ Thank you for pointing out the error. It's useful.

Here are my steps:

1. Modify the connection string to "Command Timeout=180;Connect Timeout=30".
2. Upgrade the Microsoft.Data.SqlClient package in the project from 2.0.0 to 5.1.1.
3. Run "update-database" in PMC.

**Comment by felaray** [comment]
> @felaray So it works for you now?

Yes.Thank for your help .The problem has been solved. It had been bothering me for a few days.

**Comment by eSPiYa** [comment]
> ID=**;Password=**;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=180
> 
> You are setting the Connection Timeout, not Command Timeout.
> 
> If you use a newer version of SqlClient you can set the "Command Timeout" in the connection string.

This worked. Thanks!
