### ISSUE TITLE
Occasional TextTemplatingModelGeneratorTest failure

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#30682]
```
Failed tests
1.2646856s✘ Microsoft.EntityFrameworkCore.Scaffolding.Internal.TextTemplatingModelGeneratorTest.GenerateModel_uses_templates
System.IO.IOException : Cannot create 'C:\\Users\\ajcvi\\AppData\\Local\\Temp\\tmpC122.tmp' because a file or directory with the same name already exists.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Mono.TextTemplating.TemplatingEngine.CompileCode(IEnumerable`1 references, TemplateSettings settings, CodeCompileUnit ccu)
   at Mono.TextTemplating.TemplatingEngine.CompileTemplateInternal(ParsedTemplate pt, String content, ITextTemplatingEngineHost host, TemplateSettings settings)
   at Mono.TextTemplating.TemplatingEngine.CompileTemplate(String content, ITextTemplatingEngineHost host)
   at Mono.TextTemplating.TemplatingEngine.ProcessTemplate(String content, ITextTemplatingEngineHost host)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.TextTemplatingModelGenerator.GenerateModel(IModel model, ModelCodeGenerationOptions options) in C:\github\efcore\src\EFCore.Design\Scaffolding\Internal\TextTemplatingModelGenerator.cs:line 110
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.TextTemplatingModelGeneratorTest.GenerateModel_uses_templates() in C:\github\efcore\test\EFCore.Design.Tests\Scaffolding\Internal\TextTemplatingModelGeneratorTest.cs:line 82
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by ajcvickers** [comment]
Note from triage: no way to request a unique temp directory, so we may need to use our own naming (e.g. GUID-based) or do additional checks before using the directory.

**Comment by ajcvickers** [comment]
Closing; haven't seen this for a long time.
