### ISSUE TITLE
Internal EF Exception Not Visible in Controller Resulting in Ambiguous 500 Return

### ISSUE THREAD

**Issue by TonyLugg** [dotnet/efcore#30736]
I have a WASM app hosted in Core.  I'm using EF Core for database access.  My catches are working in the API controllers but when I execute a stored procedure with dbSet.FromSqlRaw and there is an error (such as misspelled name), a 500 http result is retured to the client but the try catch does not trap the exception thrown by EF.  How can I trap the EF exceptions on the server (so that I can return a proper message to the client and/or log the exception)?

The internal exception shows up in the VS Output window:

```
Microsoft.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'dbo.GetReportList'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__208_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at System.Text.Json.Serialization.Converters.IAsyncEnumerableOfTConverter`2.OnWriteResume(Utf8JsonWriter writer, TAsyncEnumerable value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at AccessibleNB.Server.AuthenticationMiddleware.InvokeAsync(HttpContext httpContext, ServiceManager serviceManager, Audit audit) in C:\Dev\AbilityNB\AccessibleNB\AccessibleNB\Server\AuthenticationMiddleware.cs:line 38
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
ClientConnectionId:9974b9f9-a564-4619-9b10-ee6646968c58
Error Number:2812,State:62,Class:16
```

Obviously, this error should not normally occur, but it is intentionally created to test the exception handling.  If I force an exception in the controller with , say, divide by zero, it is caught by the Try/Catch.  The exception thrown by EF is not caught and the client receives a 500 with no details.

EF Core version:  NuGet Microsoft.EntityFrameworkCore.SqlServer 7.0.4
Target framework: .NET 7
Operating system:  Windows 11
IDE: Visual Studio 2022 17.5.4

**Comment by roji** [comment]
@TonyLugg EF just bubbles the SqlException up - it doesn't swallow the exception or anything of the sort. If you simply use SqlClient directly at the same place in your code and produce the exception, things should work exactly the same regardless of whether EF is being used or not.

**Comment by TonyLugg** [comment]
@roji If I wrap the call to FromSqlRaw in Try/Catch and put Console.WriteLine entries on either side, the exception is not caught.  I think it used to work as expected, but now the exception does not bubble up, which is the whole problem.

**Comment by roji** [comment]
Are you saying you're seeing the Console.WriteLine *after* FromSqlRaw, i.e. that EF is swallowing the exception internally? Or that you're only seeing the Console.WriteLine before?

**Comment by TonyLugg** [comment]
@roji I'm saying I'm seeing the Console.Writeline both before and after FromSqlRaw.  EF is swallowing the exception internally.  My code continues executing like nothing happened, but the client receives a 500 status code with no explanation.

**Comment by roji** [comment]
Can you submit a minimal, runnable code sample that shows this happening?

**Comment by TonyLugg** [comment]
OK, it may be a few days from now...

**Comment by stevendarby** [comment]
Are you returning an IQueryable? This would leave ASP.NET Core to execute and materialise the query after your action has returned. Maybe you want to execute it in your action by calling ToList or similar on it first.

**Comment by TonyLugg** [comment]
@stevendarby It works perfectly when there is no DB exception.  It returns iQueryable which is put into an ObjectResult and returned in the ActionResult (as JSON array).  All this works as expected.  I renamed a stored procedure to test the exception handling in the Try/Catch of the controller, which is when I discovered the exception was not bubbling up.

Perhaps it is the middleware handling the request pipe asynchronously, but I wouldn't think so because an error directly in the controller is caught in the Try/Catch.

**Comment by stevendarby** [comment]
If returning an IQueryable then the query is not actually executed in your try, that's why nothing is caught there.

**Comment by TonyLugg** [comment]
I put .ToList() on it but it still didn't catch the exception.

**Comment by TonyLugg** [comment]
If it wasn't executed, how would I get the results?

**Comment by TonyLugg** [comment]
`            string lcSpName = $"{schema}.{name}";
            var loSqlBuilder = new StringBuilder($"EXECUTE {lcSpName}");
            var laMethodParams = methodInfo.GetParameters();
            var lcolSqlParameters = new SqlParameter[laMethodParams.Length];
            for (var i = 0; i < laMethodParams.Length; i++)
            {
                lcolSqlParameters[i] = new SqlParameter(laMethodParams[i].Name, paramValues[i] == null ? DBNull.Value : paramValues[i]);
                if (i > 0)
                {
                    loSqlBuilder.Append(",");
                }
                loSqlBuilder.Append($" {{{i}}}");
            }
            var dbSet = Set<TEntity>();
            var loResult = dbSet.FromSqlRaw(loSqlBuilder.ToString(), lcolSqlParameters).AsEnumerable();
            return loResult;
`

**Comment by TonyLugg** [comment]
@stevendarby My apologies, I misread and mistyped the response.  It is NOT iQueryable, it is IEnumerable.

**Comment by stevendarby** [comment]
> If it wasn't executed, how would I get the results?

If the controller returns an IQueryable - or even IEnumerable - then its execution may be delayed until ASP.NET Core writes the response later in the pipeline. So it would still be executed, just not in your action, which might have explained why your try/catch doesn't catch it. As @roji said though, a minimal repro would be best - was just hoping to rule out one possibility.

**Comment by TonyLugg** [comment]
OK, but I am reliably aways getting my results from my queries.  And changing asEnumerable to ToList didn't change anything.

**Comment by TonyLugg** [comment]
Well, I restarted my system and changed AsEnumerable to ToList and it is now working.  Not sure why that change did not work yesterday, but it was as you stated, it required ToList to get it to execute.  Please consider this closed.
