### ISSUE TITLE
Missing table column name information in Exceptions

### ISSUE THREAD

**Issue by fairking** [dotnet/efcore#30741]
**Microsoft.EntityFrameworkCore v7.0.4**

Having an error: `Data is Null. This method or property cannot be called on Null values`.
I could not determine which column had an issue.

```
ERROR|System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at lambda_method116(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)

```

Could you please add table / column name to the error message.
Otherwise the debugging process is a nightmare.
Thanks.

Related issue: https://github.com/dotnet/efcore/issues/30397

**Comment by ErikEJ** [comment]
Do your database schema match the nullability of your DbContext model columns?
