### ISSUE TITLE
Dynamically generated expression predicates throw InvalidOperationException

### ISSUE THREAD

**Issue by petarpetrovt** [dotnet/efcore#30799]
Simple dynamically generated expression tree predicates are unable to be evaluated and will result in an exception being thrown. However, if the same expression is already cached through a regular `Where` expression, it works fine.

Expression
```csharp
x => x.Date > <>c__DisplayClass0_0.dateA && x.Date < <>c__DisplayClass0_0.dateB
```

## Example code
```csharp
using Microsoft.EntityFrameworkCore;
using System.Linq.Expressions;

using var context = new TestDbContext();

DateTime dateA = DateTime.Now.AddDays(-1);
DateTime dateB = DateTime.Now;

// TODO: Uncommenting this line caches correct expression translation and stops the second one from throwing an exception.
//Console.WriteLine(context.Tests.Where(x => x.Date > dateA && x.Date < dateB).ToQueryString());
Console.WriteLine();

Expression<Func<Test, bool>> predicate = null;

predicate = CombinePredicates(predicate, x => x.Date > dateA, ExpressionType.AndAlso);
predicate = CombinePredicates(predicate, x => x.Date < dateB, ExpressionType.AndAlso);

Console.WriteLine(context.Tests.Where(predicate).ToQueryString());

static Expression<Func<T, bool>> CombinePredicates<T>(
  Expression<Func<T, bool>> predicate1 = null,
  Expression<Func<T, bool>> predicate2 = null,
  ExpressionType operation = default)
{
	if (predicate1 is null)
	{
		return predicate2;
	}

	if (predicate2 is null)
	{
		return predicate1;
	}

	return Expression.Lambda<Func<T, bool>>(
		Expression.MakeBinary(operation, predicate1.Body, predicate2.Body),
		predicate1.Parameters[0]);
}

class TestDbContext : DbContext
{
	public virtual DbSet<Test> Tests { get; set; }

	protected override void OnConfiguring(DbContextOptionsBuilder builder)
		=> builder.UseSqlServer(string.Empty);

	protected override void OnModelCreating(ModelBuilder builder)
		=> builder.Entity<Test>(entity =>
		{
			entity.Property(e => e.Id).ValueGeneratedOnAdd().IsRequired();
			entity.Property(e => e.Date).IsRequired();
			entity.HasKey(e => e.Id);
		});
}

class Test
{
	public int Id { get; set; }

	public DateTime Date { get; set; }
}
```

## csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net7.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.5" />
	</ItemGroup>
</Project>

```

## Exception

```
Unhandled exception. System.InvalidOperationException: The LINQ expression 'x' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitParameter(ParameterExpression parameterExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMember(MemberExpression memberExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TranslateInternal(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateExpression(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateLambdaExpression(ShapedQueryExpression shapedQueryExpression, LambdaExpression lambdaExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateWhere(ShapedQueryExpression source, LambdaExpression predicate)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToQueryString(IQueryable source)
```

Expected query:
```SQL
SELECT [t].[Id], [t].[Date]
FROM [Tests] AS [t]
WHERE [t].[Date] > @__dateA_0 AND [t].[Date] < @__dateB_1
```

### Further technical details

EF Core version: 6, 7 and 8-preview
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: ne6.0, net7.0
Operating system: Windows 10
IDE: Visual Studio 2022

**Comment by maumar** [comment]
to make this work, in `CombinePredicates` you need to remap the parameter used in the second predicate (to use `predicate1.Parameters[0]`, rather than the original parameter created by the compiler) . EF relies on parameters to have the same reference when it reasons about it. As it stands, EF recognizes parameter from the first predicate and correctly translates it, but the parameter from second predicate looks like external variable and that's the failed translation you see.

**Comment by maumar** [comment]
There is a bug here, however. `ExpressionEqualityComparer` uses regular LINQ rules (name + scoping) to determine whether parameters are equal. That's why the query "works" when similar query with consistent parameter references across the board yields a cache hit. 

We could try to use LINQ parameter matching semantics across the board, but maybe that's too much effort compared to the benefit?

**Comment by petarpetrovt** [comment]
I am pleased to confirm that remapping the parameter works. Thank you for your help. Regarding its benefits, I cannot definitively say if there will be other use cases. However, I can provide an example of how we are currently using it. Essentially, our web application includes a filter that is stored in the database for each user. This filter consists of a list of criteria that are combined using OR logic, and each criterion has multiple properties that are combined using AND logic. We generate a predicate from the custom user filter and apply it to the IQueryable<TEntity> object.

## Example code

```csharp
internal class ParameterRemapper : ExpressionVisitor
{
	private readonly ParameterExpression _a;
	private readonly ParameterExpression _b;

	public ParameterRemapper(ParameterExpression a, ParameterExpression b)
	{
		_a = a ?? throw new ArgumentNullException(nameof(a));
		_b = b ?? throw new ArgumentNullException(nameof(b));
	}

	protected override Expression VisitParameter(ParameterExpression node)
		=> _a.Equals(node)
			? _b
			: base.VisitParameter(node);

	public static Expression<Func<T, bool>> CombinePredicates<T>(
		Expression<Func<T, bool>> predicate1 = null,
		Expression<Func<T, bool>> predicate2 = null,
		ExpressionType operation = default)
	{
		if (predicate1 is null)
		{
			return predicate2;
		}

		if (predicate2 is null)
		{
			return predicate1;
		}

		var remapper = new ParameterRemapper(predicate2.Parameters[0], predicate1.Parameters[0]);

		Expression expression = remapper.Visit(Expression.MakeBinary(operation, predicate1.Body, predicate2.Body));

		return Expression.Lambda<Func<T, bool>>(
			expression,
			predicate1.Parameters[0]);
	}
}

```

**Comment by roji** [comment]
> We could try to use LINQ parameter matching semantics across the board, but maybe that's too much effort compared to the benefit?

Yeah, I'd vote against investing the effort for this...

**Comment by ajcvickers** [comment]
Note from triage: we will stick with the plan that expression trees generated manually must follow the same rules as those generated by the compiler.
