### ISSUE TITLE
Where() after Select() sometimes fails to translate

### ISSUE THREAD

**Issue by billybraga** [dotnet/efcore#30819]
Applying a where that uses a collection inside a nav prop fails when preceeded by a Select that uses a ternary `if x null ? null : x`.

It looks related to #30479 and/or #17782.

This is particularly annoying since in my case the query is generated by AutoMapper ProjectTo, so I can't change it.

```C#
using Microsoft.EntityFrameworkCore;

await using var db = new AppDbContext();
await db.Database.EnsureDeletedAsync();
await db.Database.EnsureCreatedAsync();

db.Parents.Add(new Parent
{
    Name = "Parent",
    Child = new Child
    {
        Name = "Child",
        GrandChildren = new GrandChild[]
        {
            new()
            {
                Name = "grand child",
            },
        },
    },
});

await db.SaveChangesAsync();

var queryable = db
    .Parents
    .Select(x => new
    {
        x.Id,
        x.Name,
        Child =
            // Comment-out the line below to avoid bug 
            x.Child == null ? null :
                new
                {
                    x.Child.Id,
                    x.Child.Name,
                    GrandChildren = x
                        .Child
                        .GrandChildren
                        .Select(g => new
                        {
                            g.Id, g.Name,
                        })
                        .ToList(),
                }
    })
    .Where(x => x.Child.GrandChildren.Any(g => g.Name == "grand child"));

foreach (var parentDto in queryable)
{
    Console.WriteLine(parentDto.Name);
}

public class Parent
{
    public int Id { get; set; }
    public string Name { get; set; }
    public Child? Child { get; set; }
}

public class Child
{
    public int Id { get; set; }
    public string Name { get; set; }
    public IReadOnlyCollection<GrandChild> GrandChildren { get; set; }
}

public class GrandChild
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class AppDbContext : DbContext
{
    public DbSet<Parent> Parents { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseInMemoryDatabase("test");
    }
}
```

```
Unhandled exception. System.InvalidOperationException: The LINQ expression 'DbSet<Parent>()
    .LeftJoin(
        inner: DbSet<Child>(),
        outerKeySelector: p => EF.Property<int?>(p, "ChildId"),
        innerKeySelector: c => EF.Property<int?>(c, "Id"),
        resultSelector: (o, i) => new TransparentIdentifier<Parent, Child>(
            Outer = o,
            Inner = i
        ))
    .Where(p => p.Inner == null ? null : DbSet<GrandChild>()
        .Where(g => EF.Property<int?>(p.Inner, "Id") != null && object.Equals(
            objA: (object)EF.Property<int?>(p.Inner, "Id"),
            objB: (object)EF.Property<int?>(g, "ChildId")))
        .Select(g => new {
            Id = g.Id,
            Name = g.Name
         })
        .ToList()
        .Any(g => g.Name == "grand child"))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for mo
re information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0&)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at Program.<Main>$(String[] args) in ...\Program.cs:line 50
   at Program.<Main>$(String[] args) in ...\Program.cs:line 50
   at Program.<Main>(String[] args)
```

EF Core version: 7.0.5
Database provider: Any (seems to happen with at least memory, sqlserver and sqlite)
Target framework: (e.g. .NET 7.0)
Operating system: Windows

**Comment by ajcvickers** [comment]
Duplicate (same root cause/pending selector issue) as #30479.
