### ISSUE TITLE
Unable to use `ExecuteUpdate` or `ExecuteDelete` with properties of owned entities

### ISSUE THREAD

**Issue by wsimf** [dotnet/efcore#30833]
EF Core throws a `System.InvalidOperation` when trying to bulk update (with `RelationalQueryableExtensions.ExecuteUpdate<TSource>` ([link](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationalqueryableextensions.executeupdate?view=efcore-7.0)) (or delete) property of an owned entity through the owner. 

### Schema

Owned Entity:
```C#
public class EntityChangeTime
{
    public DateTime Created { get; set; }
    public DateTime? Modified { get; set; }
    public DateTime? Deleted { get; set; }
}
```

Owners:
```C#
public class File
{
    public long FileId { get; set; 
    public EntityChangeTime Date { get; set; } = new(); // owned entity
    public ulong RowVersion { get; set; }

    public ICollection<FileVersion> Versions = new HashSet<FileVersion>();
}

public class FileVersion
{
    public long FileId { get; set; }
    public int Version { get; set; }
    public EntityChangeTime Date { get; set; } = new(); // owned entity
    public ulong RowVersion { get; set; }

    public File File { get; set; } = null!;
}
```

Entity Configuration:
```C#
public class FileConfiguration : IEntityTypeConfiguration<File>
{
    public void Configure(EntityTypeBuilder<File> builder)
    {
        builder.HasKey(e => e.FileId);
        builder.Property(e => e.FileId).ValueGeneratedOnAdd();
        builder.Property(e => e.RowVersion)
            .IsRowVersion()
            .HasConversion<byte[]>();

        builder.HasMany(e => e.Versions)
            .WithOne(e => e.File)
            .HasForeignKey(e => e.FileId)
            .IsRequired();

        builder.OwnsOne(f => f.Date); // owned entity config
    }
}

public class FileVersionConfiguration : IEntityTypeConfiguration<FileVersion>
{
    public void Configure(EntityTypeBuilder<FileVersion> builder)
    {
        builder.HasKey(e => new { e.Version, e.FileId });
        builder.Property(e => e.RowVersion)
            .IsRowVersion()
            .HasConversion<byte[]>();

        builder.OwnsOne(v => v.Date); // owned entity config
    }
}
```

Generated Migration:
```C#
public partial class Initial : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.EnsureSchema(
            name: "DOC_MANAGER");

        migrationBuilder.CreateTable(
            name: "Files",
            schema: "DOC_MANAGER",
            columns: table => new
            {
                FileId = table.Column<long>(type: "bigint", nullable: false)
                    .Annotation("SqlServer:Identity", "1, 1"),
                Date_Created = table.Column<DateTime>(type: "datetime2", nullable: false),
                Date_Modified = table.Column<DateTime>(type: "datetime2", nullable: true),
                Date_Deleted = table.Column<DateTime>(type: "datetime2", nullable: true),
                RowVersion = table.Column<byte[]>(type: "rowversion", rowVersion: true, nullable: false)
            },
            constraints: table => { table.PrimaryKey("PK_Files", x => x.FileId); });

        migrationBuilder.CreateTable(
            name: "FileVersions",
            schema: "DOC_MANAGER",
            columns: table => new
            {
                FileId = table.Column<long>(type: "bigint", nullable: false),
                Version = table.Column<int>(type: "int", nullable: false),
                Date_Created = table.Column<DateTime>(type: "datetime2", nullable: false),
                Date_Modified = table.Column<DateTime>(type: "datetime2", nullable: true),
                Date_Deleted = table.Column<DateTime>(type: "datetime2", nullable: true),
                RowVersion = table.Column<byte[]>(type: "rowversion", rowVersion: true, nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_FileVersions", x => new { x.Version, x.FileId });
                table.ForeignKey(
                    name: "FK_FileVersions_Files_FileId",
                    column: x => x.FileId,
                    principalSchema: "DOC_MANAGER",
                    principalTable: "Files",
                    principalColumn: "FileId",
                    onDelete: ReferentialAction.Cascade);
            });

        migrationBuilder.CreateIndex(
            name: "IX_FileVersions_FileId",
            schema: "DOC_MANAGER",
            table: "FileVersions",
            column: "FileId");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "FileVersions",
            schema: "DOC_MANAGER");

        migrationBuilder.DropTable(
            name: "Files",
            schema: "DOC_MANAGER");
    }
}
```

Repository class where `ExecuteUpdate` is used:
```C#
public class FileRepository
{
    private readonly IFileEntityProvider _context;

    public FileRepository(IFileEntityProvider context)
    {
        _context = context;
    }

    public async Task DeleteFile(long fileId)
    {
        File? file = await _context.Files.FindAsync(fileId).ConfigureAwait(false);
        FileDataNotFoundException.ThrowIfNull(file, fileId);

        DateTime deleted = DateTime.UtcNow;
        file.Date.Deleted = deleted;

        await using IDbContextTransaction transaction =
            await _context.Database.BeginTransactionAsync(IsolationLevel.Snapshot);

        try
        {
            _context.Files.Update(file);
            await _context.SaveChangesAsync();

            await _context.FileVersions
                .Where(v => v.FileId == fileId)
                .ExecuteUpdateAsync(conf =>
                    conf.SetProperty(v => v.Date.Deleted, deleted)); // <- Exception here

            await transaction.CommitAsync().ConfigureAwait(false);
        }
        catch (Exception)
        {
            await transaction.RollbackAsync().ConfigureAwait(false);
            throw;
        }
    }
}
```
### Stack trace

```
System.InvalidOperationException : The LINQ expression 'DbSet<FileVersion>()
    .Where(f => f.FileId == __request_FileId_0)
    .Select(f => IncludeExpression(
        EntityExpression:
        IncludeExpression(
            EntityExpression:
            f, 
            NavigationExpression:
            EF.Property<EntityChangeTime>(f, "Date"), Date)
        , 
        NavigationExpression:
        EF.Property<EntityChangeUser>(f, "User"), User)
    )
    .ExecuteUpdate(conf => conf.SetProperty<DateTime?>(
        propertyExpression: v => v.Date.Deleted, 
        valueExpression: __request_DeletedTime_1))' could not be translated. Additional information: The following lambda argument to 'SetProperty' does not represent a valid property to be set: 'v => v.Date.Deleted'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.RelationalQueryableExtensions.ExecuteUpdateAsync[TSource](IQueryable`1 source, Expression`1 setPropertyCalls, CancellationToken cancellationToken)
   at DocumentManager.Data.Core.Repository.Default.FileRepository.<>c__DisplayClass7_0.<<DeleteFile>b__0>d.MoveNext() in /Users/sudara/Developer/DocumentManager/Data/DocumentManager.Data.Core/Repository/Default/FileRepository.cs:line 110
```

### Pprovider and version information

EF Core version: 7.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: macOS 13.3.1 (a)
IDE: Jet Brains Rider 2023.1.1

**Comment by roji** [comment]
This is a likely duplicate of #30528.

Can you please try to the latest [daily build](https://github.com/dotnet/efcore/blob/main/docs/DailyBuilds.md) and confirm that the bug is gone there?

**Comment by wsimf** [comment]
Yes tried a daily build and it has been fixed.

**Comment by roji** [comment]
Thanks for confirming!

**Comment by roji** [comment]
Duplicate of #30528
