### ISSUE TITLE
LINQ Expression (JsonQueryExpression) could not be translated

### ISSUE THREAD

**Issue by adammankowski1** [dotnet/efcore#30830]
## LINQ Expression (JsonQueryExpression) could not be translated

I started to use `ToJson()` feature to store some kind of object array as JSON column in SQL Server database. It worked well during updates or simple reads without casting directly to DTO.

When I tried to cast my JSON collection to the DTO before executing the query, I got an error: LINQ Expression (JsonQueryExpression) could not be translated.

Is this known bug or am I doing mistake? I haven't found 100% matching issue in opened / closed issues.

### Reproduce steps

1.  Create new Console project in Visual Studio 2022 (target NET 7.0).
2. Add libraries via nuget ([access daily builds](https://github.com/dotnet/efcore/blob/main/docs/DailyBuilds.md)):
- Microsoft.EntityFrameworkCore (8.0.0-preview.5.23253.4)
- Microsoft.EntityFrameworkCore.Design (8.0.0-preview.5.23253.4)
- Microsoft.EntityFrameworkCore.SqlServer (8.0.0-preview.5.23253.4)
3. Paste the code below into `Program.cs` file.
4. Create local SQL Server database and fill `Program.cs:34` line with connection string.
5. Add migration via console: `dotnet ef migrations add AddAxisModelTable --project ProjectName`.
6. Run migration update via console: `dotnet ef database update --project ProjectName`.
7. Debug the project, it breaks on `Program.cs:14` line.

or

Clone / Fork [EfCore30830](https://github.com/adammankowski1/EfCore30830) project reproducing the issue.

### Code

```C#
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace AxisTest
{
    internal class Program
    {
        static void Main(string[] args)
        {
            using (var context = new AxisContext())
            {
                var axesCollection = context
                    .AxisModels.SelectMany(x => x.AxesCollection
                        .Select(axes => new AxesDto()
                        {
                            X = axes.X,
                            Y = axes.Y,
                            Z = axes.Z
                        })
                    )
                    .AsNoTracking()
                    .ToList();
            }
        }

        public class AxisContext : DbContext
        {
            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                if (!optionsBuilder.IsConfigured)
                {
                    var connectionString = "" //SQL Server connection string to fill;
                    optionsBuilder.UseSqlServer(connectionString);
                }
            }

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                modelBuilder.ApplyConfiguration(new AxisModelConfiguration());
            }

            public virtual DbSet<AxisModel> AxisModels { get; set;}
        }

        public class AxisModel
        {
            public int Id { get; set; }

            public ICollection<Axes> AxesCollection { get; set; }
        }

        public class Axes
        {
            [Column("x", TypeName = "decimal(10,8)")]
            public decimal? X { get; set; }

            [Column("y", TypeName = "decimal(10,8)")]
            public decimal? Y { get; set; }

            [Column("z", TypeName = "decimal(10,8)")]
            public decimal? Z { get; set; }
        }

        public class AxesDto
        {
            public decimal? X { get; set; }

            public decimal? Y { get; set; }

            public decimal? Z { get; set; }
        }

        public class AxisModelConfiguration : IEntityTypeConfiguration<AxisModel>
        {
            public void Configure(EntityTypeBuilder<AxisModel> builder)
            {
                builder.ToTable(nameof(AxisModel));
                builder.OwnsMany(a => a.AxesCollection, options =>
                {
                    options.ToJson();
                });
            }
        }
    }
}
```

### Stack trace

```
System.InvalidOperationException: 'The LINQ expression 'JsonQueryExpression(a.AxesCollection, "")
    .AsQueryable()' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.'
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelectMany(ShapedQueryExpression source, LambdaExpression collectionSelector, LambdaExpression resultSelector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AxisTest.Program.Main(String[] args) in Program.cs:line 14
```

### Provider and version information

EF Core version: 8.0.0-preview.2.23128.3 and 8.0.0-preview.5.23253.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: 7.0
Operating system: Windows 11 @ 10.0.22621.1555
IDE: Visual Studio 2022 17.5.4

**Comment by maumar** [comment]
works fine in current bits and produces the following SQL:


```sql
SELECT [a0].[X], [a0].[Y], [a0].[Z]
FROM [AxisModel] AS [a]
CROSS APPLY OPENJSON([a].[AxesCollection], '$') WITH (
    [X] decimal(10,8) '$.X',
    [Y] decimal(10,8) '$.Y',
    [Z] decimal(10,8) '$.Z'
) AS [a0]
```
