### ISSUE TITLE
GroupBy with unused intermediate null field: ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by ArneMancofi** [dotnet/efcore#30855]
## File a bug

When using `.GroupBy(...)` with `.Max(...)` over an intermediate box type that includes an unused field with a null value, LINQ-to-SQL translation throws  an index out of range exception.

If the unused field is assigned a non-null value, it works.

### Include your code

```C#
context.Items
    .GroupBy(item => new { item.CustomerId })
    .Select(items => new Box
        {
            Min = items.Min(item => item.Cost),
            Dummy = null // Dummy field with null value
        })
    .GroupBy(box => true)
    .Select(boxes => new { MaxOfMin = boxes.Max(box => box.Min) })
    .ToList();

public class SoldItem // EF Core entity
{
    public int Id { get; set; }
    public double Cost { get; set; }
    public int CustomerId { get; set; }
}

public class Box // Not EF Core entity
{
    public double? Min { get; set; }
    public object? Dummy { get; set; }
}
```

A [full Gist](https://gist.github.com/ArneMancofi/810a2c199f4704594f90c2c87c2c202c) is available on GitHub.

### Include stack traces

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.GetProjection(ProjectionBindingExpression projectionBindingExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TranslateInternal(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateExpression(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateAggregateWithSelector(ShapedQueryExpression source, LambdaExpression selector, Func`2 aggregateTranslator, Boolean throwWhenEmpty, Type resultType)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateMax(ShapedQueryExpression source, LambdaExpression selector, Type resultType)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.TranslateSubquery(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TranslateInternal(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitNew(NewExpression newExpression)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.<Main>$(String[] args) in EFCoreGroupByGroupBy\EFCoreGroupByGroupBy\Program.cs:line 15
```

### Include provider and version information

EF Core version: 6.0.16
Database provider: Microsoft.EntityFrameworkCore.SqlServer 6.0.16
Target framework: .NET 6.0
Operating system: Windows Version 10.0.19044 Build 19044
IDE: JetBrains Rider 2023.1.1

**Comment by maumar** [comment]
problem here is that dummy value is typed as object? and we can't translate constant of type object. This forces client projection in the middle of the query and throws the whole thing off. Query works when the dummy null value is typed as some translatable type, e.g.:

```cs
        var maxOfMinCosts =
            context.Items
                .GroupBy(item => new { item.CustomerId })
                .Select(items => new Box
                {
                    Min = items.Min(item => item.Cost),
                    Dummy = (int?)null // Dummy field with null value
                })
                .GroupBy(box => true)
                .Select(boxes => new { MaxOfMin = boxes.Max(box => box.Min) })
                .ToList();
```

we should at least fix the exception (eventually) - it's even worse in 7 than it was in 6:

```
System.InvalidOperationException : Operation is not valid due to the current state of the object.

  Stack Trace: 
ExpressionExtensions.GetConstantValue[T](Expression expression) line 56
ShaperProcessingExpressionVisitor.GetProjectionIndex(ProjectionBindingExpression projectionBindingExpression) line 1628
```

**Comment by ArneMancofi** [comment]
> problem here is that dummy value is typed as object? and we can't translate constant of type object.

But ... `Box` cannot be translated either, I suppose? So why isn't `Box` a problem, when `Dummy` is a problem?
