### ISSUE TITLE
MAUI Android app crash with Microsoft.EntityFrameworkCore.Sqlite >= 6.0.12

### ISSUE THREAD

**Issue by kalpasrl** [dotnet/efcore#30867]
Hi,
in my app developed in MAUI, if I use any version of EF Core equal or higher than 6.0.12 compiled in release mode with AOT on Android, the app crashes. Using versions earlier than 6.0.12 everything works fine.
I haven't checked in iOS

``` this is log
05-10 09:19:09.072 19695 19695 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x20 in tid 19695 (m.came.myaccess), pid 19695 (m.came.myaccess)
05-10 09:19:09.124 19719 19719 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstoneProto
05-10 09:19:09.125   290   290 I tombstoned: received crash request for pid 19695
05-10 09:19:09.127 19719 19719 I crash_dump64: performing dump of process 19695 (target tid = 19695)
05-10 09:19:09.282     0     0 I logd    : logdr: UID=10159 GID=10159 PID=19719 n tail=0 logMask=8 pid=19695 start=0ns deadline=0ns
05-10 09:19:09.289     0     0 I logd    : logdr: UID=10159 GID=10159 PID=19719 n tail=0 logMask=1 pid=19695 start=0ns deadline=0ns
05-10 09:19:09.328 19719 19719 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-10 09:19:09.330 19719 19719 F DEBUG   : Build fingerprint: 'google/sdk_gphone64_x86_64/emu64x:13/TE1A.220922.012/9302419:userdebug/dev-keys'
05-10 09:19:09.330 19719 19719 F DEBUG   : Revision: '0'
05-10 09:19:09.330 19719 19719 F DEBUG   : ABI: 'x86_64'
05-10 09:19:09.330 19719 19719 F DEBUG   : Timestamp: 2023-05-10 09:19:09.134088300+0000
05-10 09:19:09.330 19719 19719 F DEBUG   : Process uptime: 3s
05-10 09:19:09.330 19719 19719 F DEBUG   : Cmdline: com.companyname.myapp
05-10 09:19:09.331 19719 19719 F DEBUG   : pid: 19695, tid: 19695, name: m.came.myaccess  >>> com.companyname.myapp <<<
05-10 09:19:09.332 19719 19719 F DEBUG   : uid: 10159
05-10 09:19:09.332 19719 19719 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000020
05-10 09:19:09.333 19719 19719 F DEBUG   : Cause: null pointer dereference
05-10 09:19:09.333 19719 19719 F DEBUG   :     rax 0000000000000000  rbx 0000000000000000  rcx 0000000000000000  rdx 0000000000000008
05-10 09:19:09.334 19719 19719 F DEBUG   :     r8  0000000000000018  r9  00007b52e08fb1c0  r10 00000000000000ba  r11 000000000000000c
05-10 09:19:09.334 19719 19719 F DEBUG   :     r12 0000000000000000  r13 00007ffc9fbabfa8  r14 0000000000000000  r15 0000000041a8ff00
05-10 09:19:09.335 19719 19719 F DEBUG   :     rdi 0000000000000000  rsi 0000000000000001
05-10 09:19:09.335 19719 19719 F DEBUG   :     rbp 00007b52e0901ba8  rsp 00007ffc9fbabea0  rip 00007b513c148244
05-10 09:19:09.336 19719 19719 F DEBUG   : backtrace:
05-10 09:19:09.336 19719 19719 F DEBUG   :       #00 pc 00000000000db244  /data/app/~~FQebNOOF4whRpMsC-AmgWA==/com.companyname.myapp-BG9C2XumhmrqlE5XvCPDtg==/split_config.x86_64.apk!libmonosgen-2.0.so (BuildId: 77802b2a2ff6c0f805ac02eae799d88922bb0d71)
05-10 09:19:09.336 19719 19719 F DEBUG   :       #01 pc 00000000002a2667  /data/app/~~FQebNOOF4whRpMsC-AmgWA==/com.companyname.myapp-BG9C2XumhmrqlE5XvCPDtg==/split_config.x86_64.apk!libmonosgen-2.0.so (BuildId: 77802b2a2ff6c0f805ac02eae799d88922bb0d71)
05-10 09:19:09.337 19719 19719 F DEBUG   :       #02 pc 000000000029899d  /data/app/~~FQebNOOF4whRpMsC-AmgWA==/com.companyname.myapp-BG9C2XumhmrqlE5XvCPDtg==/split_config.x86_64.apk!libmonosgen-2.0.so (BuildId: 77802b2a2ff6c0f805ac02eae799d88922bb0d71)
05-10 09:19:09.337 19719 19719 F DEBUG   :       #03 pc 000000000029984e  /data/app/~~FQebNOOF4whRpMsC-AmgWA==/com.companyname.myapp-BG9C2XumhmrqlE5XvCPDtg==/split_config.x86_64.apk!libmonosgen-2.0.so (BuildId: 77802b2a2ff6c0f805ac02eae799d88922bb0d71)
05-10 09:19:09.337 19719 19719 F DEBUG   :       #04 pc 0000000000001295  <anonymous:41b3f000>
05-10 09:19:09.351   290   290 E tombstoned: Tombstone written to: tombstone_12
05-10 09:19:09.356   629 19725 I DropBoxManagerService: add tag=data_app_native_crash isTagEnabled=true flags=0x2
05-10 09:19:09.357   629 19724 W ActivityTaskManager:   Force finishing activity com.companyname.myapp/crc6495777461f7321b54.MainActivity
05-10 09:19:09.361   629   730 I BootReceiver: Copying /data/tombstones/tombstone_12 to DropBox (SYSTEM_TOMBSTONE)
05-10 09:19:09.362   629   730 I DropBoxManagerService: add tag=SYSTEM_TOMBSTONE isTagEnabled=true flags=0x6
05-10 09:19:09.364   409   442 D goldfish-address-space: claimShared: Ask to claim region [0x3f1cec000 0x3f2318000]
05-10 09:19:09.382   629   657 I ActivityManager: Showing crash dialog for package com.companyname.myapp u0
05-10 09:19:09.394   629   730 I DropBoxManagerService: add tag=SYSTEM_TOMBSTONE_PROTO isTagEnabled=true flags=0x4
05-10 09:19:09.405   629   669 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
05-10 09:19:09.386     0     0 I init    : Untracked pid 19719 exited with status 0
05-10 09:19:09.392     0     0 I init    : Untracked pid 19719 did not have an associated service entry and will not be reaped
05-10 09:19:09.417   387   387 I Zygote  : Process 19695 exited due to signal 11 (Segmentation fault)
05-10 09:19:09.434   629   669 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
05-10 09:19:09.435   629  1668 I ActivityManager: Process com.companyname.myapp (pid 19695) has died: fg  TOP
05-10 09:19:09.418     0     0 I init    : Untracked pid 19721 exited with status 0
05-10 09:19:09.430     0     0 I init    : Untracked pid 19721 did not have an associated service entry and will not be reaped
05-10 09:19:09.485   409   442 D goldfish-address-space: claimShared: Ask to claim region [0x3f2318000 0x3f2cbc000]
05-10 09:19:09.488   409 10399 D goldfish-address-space: claimShared: Ask to claim region [0x3f2cbc000 0x3f3660000]
05-10 09:19:09.496   409 10399 D goldfish-address-space: claimShared: Ask to claim region [0x3f0000000 0x3f09a4000]
05-10 09:19:09.499   409   442 D goldfish-address-space: claimShared: Ask to claim region [0x3f09a4000 0x3f1348000]
05-10 09:19:09.509   409   442 D goldfish-address-space: claimShared: Ask to claim region [0x3f68d8000 0x3f727c000]
05-10 09:19:09.519   629   669 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
05-10 09:19:09.525   629   669 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
05-10 09:19:09.537   629  1663 W InputManager-JNI: Input channel object 'd9e17c1 Splash Screen com.companyname.myapp (client)' was disposed without first being removed with the input manager!
05-10 09:19:09.537   629  1025 W ActivityManager: Unable to start service Intent { act=android.service.smartspace.SmartspaceService cmp=com.google.android.as/com.google.android.apps.miphone.aiai.app.AiAiSmartspaceService } U=0: not found
05-10 09:19:09.540   629  1025 W RemoteSmartspaceService: could not bind to Intent { act=android.service.smartspace.SmartspaceService cmp=com.google.android.as/com.google.android.apps.miphone.aiai.app.AiAiSmartspaceService } using flags 67112961
05-10 09:19:09.549   629  2484 W WindowManager: Failed looking up window session=Session{e5ee0f0 853:u0a10142} callers=com.android.server.wm.WindowManagerService.windowForClientLocked:5972 com.android.server.wm.Session.setOnBackInvokedCallbackInfo:943 android.view.IWindowSession$Stub.onTransact:1180
05-10 09:19:09.550   629  2484 E WindowManager: setOnBackInvokedCallback(): No window state for package:com.android.systemui
05-10 09:19:09.555   466   476 W TransactionTracing: Could not find layer handle 0x735305f98330
05-10 09:19:09.557  1590  1590 I GsaVoiceInteractionSrv: Handling ACTION_START_HOTWORD
05-10 09:19:09.559   466   476 W TransactionTracing: Could not find layer handle 0x735305f97d30
05-10 09:19:09.564  1590  2349 I GsaVoiceInteractionSrv: disregardVoiceMatch: false
05-10 09:19:09.565  1590  2349 I GsaVoiceInteractionSrv: Cannot start hotword, hotword has been explicitly disabled.
05-10 09:19:09.567  1828  1828 W A       : Can't get WAA status for Mavatar!
05-10 09:19:09.567  1828  1828 W A       : java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
05-10 09:19:09.567  1828  1828 W A       :      at com.google.apps.tiktok.dataservice.z.b(PG:1)
05-10 09:19:09.567  1828  1828 W A       :      at com.google.apps.tiktok.dataservice.at.a(PG:1)
05-10 09:19:09.567  1828  1828 W A       :      at com.google.apps.tiktok.tracing.ec.a(PG:2)
05-10 09:19:09.567  1828  1828 W A       :      at com.google.common.util.concurrent.aj.a(PG:2)
05-10 09:19:09.567  1828  1828 W A       :      at com.google.common.util.concurrent.ac.apply(PG:1)
05-10 09:19:09.567  1828  1828 W A       :      at com.google.common.util.concurrent.h.e(PG:2)
05-10 09:19:09.567  1828  1828 W A       :      at com.google.common.util.concurrent.j.run(PG:9)
05-10 09:19:09.567  1828  1828 W A       :      at com.google.common.util.concurrent.bf.execute(PG:1)
05-10 09:19:09.567  1828  1828 W A       :      at com.google.common.util.concurrent.d.i(PG:1)
05-10 09:19:09.567  1828  1828 W A       :      at com.google.common.util.concurrent.d.l(PG:12)
05-10 09:19:09.567  1828  1828 W A       :      at com.google.common.util.concurrent.d.n(PG:2)
05-10 09:19:09.567  1828  1828 W A       :      at com.google.common.util.concurrent.i.f(PG:1)
05-10 09:19:09.567  1828  1828 W A       :      at com.google.common.util.concurrent.j.run(PG:12)
05-10 09:19:09.567  1828  1828 W A       :      at com.google.android.libraries.i.ae.run(PG:1)
05-10 09:19:09.567  1828  1828 W A       :      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
05-10 09:19:09.567  1828  1828 W A       :      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
05-10 09:19:09.567  1828  1828 W A       :      at com.google.android.libraries.i.k.run(PG:2)
05-10 09:19:09.567  1828  1828 W A       :      at com.google.android.libraries.i.p.run(PG:4)
05-10 09:19:09.567  1828  1828 W A       :      at java.lang.Thread.run(Thread.java:1012)
05-10 09:19:09.576   629  1025 W ActivityManager: Unable to start service Intent { act=android.service.smartspace.SmartspaceService cmp=com.google.android.as/com.google.android.apps.miphone.aiai.app.AiAiSmartspaceService } U=0: not found
05-10 09:19:09.576   629  1025 W RemoteSmartspaceService: could not bind to Intent { act=android.service.smartspace.SmartspaceService cmp=com.google.android.as/com.google.android.apps.miphone.aiai.app.AiAiSmartspaceService } using flags 67112961
05-10 09:19:09.576   629   629 W ActivityManager: Unbind failed: could not find connection for android.app.LoadedApk$ServiceDispatcher$InnerConnection@9a1f603
05-10 09:19:09.588   629   629 W ActivityManager: Unbind failed: could not find connection for android.app.LoadedApk$ServiceDispatcher$InnerConnection@6a84bfe
05-10 09:19:09.598   629   657 D CompatibilityChangeReporter: Compat change id reported: 161145287; UID 1000; state: DISABLED
05-10 09:19:09.613   629   657 D CompatibilityChangeReporter: Compat change id reported: 168419799; UID 1000; state: DISABLED
05-10 09:19:09.617   411   486 I RanchuHwc: validateDisplay: layer 173 CompositionType 1, fallback to client
05-10 09:19:09.617   411   486 I RanchuHwc: validateDisplay: layer 174 CompositionType 1, fallback to client
05-10 09:19:09.623   629   657 D CoreBackPreview: Window{f47dcd6 u0 Application Error: com.companyname.myapp}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper@1fc1529, mPriority=0}
05-10 09:19:09.623   629   657 W Looper  : Slow dispatch took 198ms android.ui h=com.android.server.am.ActivityManagerService$UiHandler c=com.android.server.am.ErrorDialogController$$ExternalSyntheticLambda3@397dae5 m=0
05-10 09:19:09.631   411   486 I RanchuHwc: validateDisplay: layer 173 CompositionType 1, fallback to client
05-10 09:19:09.631   411   486 I RanchuHwc: validateDisplay: layer 174 CompositionType 1, fallback to client
05-10 09:19:09.643   629   657 D CoreBackPreview: Window{f47dcd6 u0 Application Error: com.companyname.myapp}: Setting back callback null
05-10 09:19:09.649   411   486 I RanchuHwc: validateDisplay: layer 173 CompositionType 1, fallback to client
05-10 09:19:09.649   411   486 I RanchuHwc: validateDisplay: layer 174 CompositionType 1, fallback to client
05-10 09:19:09.650   466   476 W TransactionTracing: Could not find layer handle 0x735305f963b0
05-10 09:19:09.651   466   476 W TransactionTracing: Could not find layer handle 0x735305f97b50
05-10 09:19:09.652  1493  1493 I GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3220
05-10 09:19:09.653   629 19724 W ActivityManager: Ignoring remove of inactive process: ProcessRecord{2fa9f9a 0:com.companyname.myapp/u0a159}
05-10 09:19:09.660   629   657 W InputManager-JNI: Input channel object 'f47dcd6 Application Error: com.companyname.myapp (client)' was disposed without first being removed with the input manager!

```

EF Core version: 7.0.5
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 7.0/MAUI
Operating system: Android 13
IDE: Visual Studio 2022 17.4

Thank you
Stefano

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by AndriySvyryd** [comment]
cc @roji, @bricelam

**Comment by bricelam** [comment]
This may have been fixed by PR https://github.com/dotnet/runtime/pull/79963. Not sure when that change will bubble up into the MAUI SDK...

**Comment by kalpasrl** [comment]
I recreated the project from scratch with the same structure and now it works, it's a mystery.

Thank you all the same
