### ISSUE TITLE
Why can't I override SqliteRelationalConnection?

### ISSUE THREAD

**Issue by suatsuphi** [dotnet/efcore#30889]
Hi,
Why can't I override SqliteSmartRelationalConnection ?

it is not working on my hosting ? asp.net core 7.0.5 

```
namespace Smartstore.Data.Sqlite
{
    [SuppressMessage("Usage", "EF1001:Internal EF Core API usage.", Justification = "Pending")]
    internal class SqliteSmartRelationalConnection : SqliteRelationalConnection
    {
        public SqliteSmartRelationalConnection(
            RelationalConnectionDependencies dependencies,
            IRawSqlCommandBuilder rawSqlCommandBuilder,
            IDiagnosticsLogger<DbLoggerCategory.Infrastructure> logger)
            : base(dependencies, rawSqlCommandBuilder, logger)
        {
        }

        protected override DbConnection CreateDbConnection()
        {
            var connection = base.CreateDbConnection();
            InitializeDbConnection(connection);

            return connection;
        }

        private static void InitializeDbConnection(DbConnection connection)
        {
            if (connection is SqliteConnection sqliteConnection)
            {
                sqliteConnection.CreateCollation(
                    "NOCASE",
                    static (string left, string right) => 
                    {
                        // Override equality check (Sqlite cannot compare non-ascii chars uncased)
                        return string.Compare(left, right, ignoreCase: true);
                    });

                sqliteConnection.CreateFunction(
                    "lower",
                    static (string input) =>
                    {
                        // Override lower function (Sqlite ignores non-ascii chars)
                        return input?.ToLower();
                    },
                    isDeterministic: true);

                sqliteConnection.CreateFunction(
                    "upper",
                    static (string input) =>
                    {
                        // Override upper function (Sqlite ignores non-ascii chars)
                        return input?.ToUpper();
                    },
                    isDeterministic: true);

                sqliteConnection.CreateFunction<string, string, int?>(
                    "instr",
                    static (string input, string substr) =>
                    {
                        // Override instr function (Sqlite cannot compare non-ascii chars uncased)
                        if (input == null || substr == null)
                        {
                            return null;
                        }

                        var index = input.IndexOf(substr, StringComparison.CurrentCultureIgnoreCase);

                        // Sqlite instr is 1-based.
                        return index + 1;
                    },
                    isDeterministic: true);
            }
        }
    }
}

```

**Comment by suatsuphi** [comment]
Could you explain? It is working on local IIS but not working on hosting.

**Comment by roji** [comment]
> It is working on local IIS but not working on hosting. IIS freezes and gives 503 error

This is very unlikely to be related to EF Core, but rather something to do with your hosting or application configuration there.

**Comment by suatsuphi** [comment]
> 

@roji 

when i remove this partition it works.
```
        protected override DbConnection CreateDbConnection()
        {
            var connection = base.CreateDbConnection();
            InitializeDbConnection(connection);

            return connection;
        }
```

I'm contacting the hosting company, I want the log records... waiting for them
but I can't get error details... freezing and just HTTP Error 503. The service is unavailable.

**Comment by roji** [comment]
@suatsuphi there's nothing we can do to help really - the error report doesn't even contain an exception with a stack trace (HTTP error 503 could mean anything, and isn't necessarily related to EF in any way).

**Comment by suatsuphi** [comment]
The hosting company has just sent the log


Application: w3wp.exe
CoreCLR Version: 7.0.523.17405
.NET Version: 7.0.5
Description: The process was terminated due to an unhandled exception.
Stack:
   at SQLitePCL.SQLite3Provider_e_sqlite3+NativeMethods.sqlite3_step(SQLitePCL.sqlite3_stmt)
   at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_step(SQLitePCL.sqlite3_stmt)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(System.Data.CommandBehavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(System.Data.CommandBehavior, System.Threading.CancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand+<ExecuteDbDataReaderAsync>d__60.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.Data.Sqlite.SqliteCommand+<ExecuteDbDataReaderAsync>d__60, Microsoft.Data.Sqlite, Version=7.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<ExecuteDbDataReaderAsync>d__60 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Microsoft.Data.Sqlite.SqliteCommand+<ExecuteDbDataReaderAsync>d__60, Microsoft.Data.Sqlite, Version=7.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<ExecuteDbDataReaderAsync>d__60 ByRef)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(System.Data.CommandBehavior, System.Threading.CancellationToken)
   at System.Data.Common.DbCommand.ExecuteReaderAsync(System.Threading.CancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand+<ExecuteReaderAsync>d__19.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.EntityFrameworkCore.Storage.RelationalCommand+<ExecuteReaderAsync>d__19, Microsoft.EntityFrameworkCore.Relational, Version=7.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<ExecuteReaderAsync>d__19 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Microsoft.EntityFrameworkCore.Storage.RelationalCommand+<ExecuteReaderAsync>d__19, Microsoft.EntityFrameworkCore.Relational, Version=7.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<ExecuteReaderAsync>d__19 ByRef)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(Microsoft.EntityFrameworkCore.Storage.RelationalCommandParameterObject, System.Threading.CancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch+<ExecuteAsync>d__50.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch+<ExecuteAsync>d__50, Microsoft.EntityFrameworkCore.Relational, Version=7.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<ExecuteAsync>d__50 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch+<ExecuteAsync>d__50, Microsoft.EntityFrameworkCore.Relational, Version=7.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<ExecuteAsync>d__50 ByRef)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(Microsoft.EntityFrameworkCore.Storage.IRelationalConnection, System.Threading.CancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor+<ExecuteAsync>d__9.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor+<ExecuteAsync>d__9, Microsoft.EntityFrameworkCore.Relational, Version=7.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<ExecuteAsync>d__9 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor+<ExecuteAsync>d__9, Microsoft.EntityFrameworkCore.Relational, Version=7.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<ExecuteAsync>d__9 ByRef)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(System.Collections.Generic.IEnumerable`1<Microsoft.EntityFrameworkCore.Update.ModificationCommandBatch>, Microsoft.EntityFrameworkCore.Storage.IRelationalConnection, System.Threading.CancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChangesAsync(System.Collections.Generic.IList`1<Microsoft.EntityFrameworkCore.Update.IUpdateEntry>, System.Threading.CancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager+<SaveChangesAsync>d__106.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager+<SaveChangesAsync>d__106, Microsoft.EntityFrameworkCore, Version=7.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<SaveChangesAsync>d__106 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager+<SaveChangesAsync>d__106, Microsoft.EntityFrameworkCore, Version=7.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<SaveChangesAsync>d__106 ByRef)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(System.Collections.Generic.IList`1<Microsoft.EntityFrameworkCore.Update.IUpdateEntry>, System.Threading.CancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager+<SaveChangesAsync>d__110.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager+<SaveChangesAsync>d__110, Microsoft.EntityFrameworkCore, Version=7.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<SaveChangesAsync>d__110 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager+<SaveChangesAsync>d__110, Microsoft.EntityFrameworkCore, Version=7.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<SaveChangesAsync>d__110 ByRef)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager, Boolean, System.Threading.CancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager+<>c.<SaveChangesAsync>b__109_0(Microsoft.EntityFrameworkCore.DbContext, System.ValueTuple`2<Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager,Boolean>, System.Threading.CancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.ExecuteAsync[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Boolean, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.ValueTuple`2<System.__Canon,Boolean>, System.Func`4<Microsoft.EntityFrameworkCore.DbContext,System.ValueTuple`2<System.__Canon,Boolean>,System.Threading.CancellationToken,System.Threading.Tasks.Task`1<Int32>>, System.Func`4<Microsoft.EntityFrameworkCore.DbContext,System.ValueTuple`2<System.__Canon,Boolean>,System.Threading.CancellationToken,System.Threading.Tasks.Task`1<Microsoft.EntityFrameworkCore.Storage.ExecutionResult`1<Int32>>>, System.Threading.CancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean, System.Threading.CancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext+<SaveChangesAsync>d__64.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.EntityFrameworkCore.DbContext+<SaveChangesAsync>d__64, Microsoft.EntityFrameworkCore, Version=7.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<SaveChangesAsync>d__64 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Microsoft.EntityFrameworkCore.DbContext+<SaveChangesAsync>d__64, Microsoft.EntityFrameworkCore, Version=7.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<SaveChangesAsync>d__64 ByRef)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean, System.Threading.CancellationToken)
   at Smartstore.Data.HookingDbContext.SaveChangesCoreAsync(Boolean, System.Threading.CancellationToken)
   at Smartstore.Data.DbSaveChangesOperation+<ExecuteInternal>d__17.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at Smartstore.Data.DbSaveChangesOperation.ExecuteInternal(Boolean, Boolean, System.Threading.CancellationToken)
   at Smartstore.Data.DbSaveChangesOperation.ExecuteAsync(Boolean, System.Threading.CancellationToken)
   at Smartstore.Data.HookingDbContext+<SaveChangesInternal>d__39.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at Smartstore.Data.HookingDbContext.SaveChangesInternal(Boolean, Boolean, System.Threading.CancellationToken)
   at Smartstore.Data.HookingDbContext.SaveChangesAsync(Boolean, System.Threading.CancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(System.Threading.CancellationToken)
   at Smartstore.Core.Data.Migrations.LocaleResourcesMigrator+<MigrateAsync>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at Smartstore.Core.Data.Migrations.LocaleResourcesMigrator.MigrateAsync(System.Collections.Generic.IEnumerable`1<Smartstore.Core.Data.Migrations.LocaleResourceEntry>, Boolean)
   at Smartstore.Core.Data.Migrations.MigrationBuilderDbContextExtensions.MigrateLocaleResourcesAsync(Smartstore.Core.Data.SmartDbContext, System.Action`1<Smartstore.Core.Data.Migrations.LocaleResourcesBuilder>, Boolean)
   at Smartstore.Core.Data.Migrations.SmartDbContextDataSeeder+<SeedAsync>d__2.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at Smartstore.Core.Data.Migrations.SmartDbContextDataSeeder.SeedAsync(Smartstore.Core.Data.SmartDbContext, System.Threading.CancellationToken)
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, Void**, System.Signature, Boolean)
   at System.Reflection.MethodInvoker.Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Reflection.MethodBase.Invoke(System.Object, System.Object[])
   at Smartstore.Core.Data.Migrations.DatabaseInitializer+<RunGlobalSeeders>d__8.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at Smartstore.Core.Data.Migrations.DatabaseInitializer.RunGlobalSeeders(Smartstore.Data.HookingDbContext, System.Threading.CancellationToken)
   at Smartstore.Core.Data.Migrations.DatabaseInitializer+<InitializeDatabaseAsync>d__7.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at Smartstore.Core.Data.Migrations.DatabaseInitializer.InitializeDatabaseAsync(Smartstore.Core.Data.Migrations.DbMigrator, System.Threading.CancellationToken)
   at Smartstore.Core.Data.Migrations.DatabaseInitializer.InitializeDatabaseAsync(System.Type, System.Threading.CancellationToken)
   at Smartstore.Core.Data.Migrations.DatabaseInitializer+<InitializeDatabasesAsync>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at Smartstore.Core.Data.Migrations.DatabaseInitializer.InitializeDatabasesAsync(System.Threading.CancellationToken)
   at Smartstore.Core.Bootstrapping.ApplicationDatabasesInitializer.InitializeAsync(Microsoft.AspNetCore.Http.HttpContext)
   at Smartstore.Engine.Initialization.ApplicationInitializerMiddleware+<InitializeAsync>d__13.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at Smartstore.Engine.Initialization.ApplicationInitializerMiddleware.InitializeAsync(Microsoft.AspNetCore.Http.HttpContext)
   at Smartstore.Engine.Initialization.ApplicationInitializerMiddleware+<Invoke>d__12.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at Smartstore.Engine.Initialization.ApplicationInitializerMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware+<Invoke>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware+<Invoke>d__3, Microsoft.AspNetCore.Diagnostics, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<Invoke>d__3 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware+<Invoke>d__3, Microsoft.AspNetCore.Diagnostics, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<Invoke>d__3 ByRef)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext)
   at Microsoft.AspNetCore.HttpsPolicy.HstsMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.Invoke(Microsoft.AspNetCore.Http.HttpContext)
   at Microsoft.AspNetCore.Builder.UseExtensions+<>c__DisplayClass0_2.<Use>b__2()
   at Smartstore.Bootstrapping.ThreadingBootstrappingExtensions+<>c+<<UseContextState>b__0_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at Smartstore.Bootstrapping.ThreadingBootstrappingExtensions+<>c.<UseContextState>b__0_0(Microsoft.AspNetCore.Http.HttpContext, System.Func`1<System.Threading.Tasks.Task>)
   at Microsoft.AspNetCore.Builder.UseExtensions+<>c__DisplayClass0_1.<Use>b__1(Microsoft.AspNetCore.Http.HttpContext)
   at Microsoft.AspNetCore.HttpOverrides.ForwardedHeadersMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext)
   at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext)
   at Microsoft.AspNetCore.Hosting.HostingApplication.ProcessRequestAsync(Context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1+<ProcessRequestAsync>d__2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1+<ProcessRequestAsync>d__2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.AspNetCore.Server.IIS, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<ProcessRequestAsync>d__2<System.__Canon> ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Boolean, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1+<ProcessRequestAsync>d__2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.AspNetCore.Server.IIS, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<ProcessRequestAsync>d__2<System.__Canon> ByRef)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ProcessRequestAsync()
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext+<HandleRequest>d__185.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext+<HandleRequest>d__185, Microsoft.AspNetCore.Server.IIS, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<HandleRequest>d__185 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext+<HandleRequest>d__185, Microsoft.AspNetCore.Server.IIS, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<HandleRequest>d__185 ByRef)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.HandleRequest()
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

**Comment by suatsuphi** [comment]
I figured it out.  If 'Enable 32-Bit Applications' is set to true in IIS it gives this error.

https://ibb.co/X3fBBxH
