### ISSUE TITLE
Concatenating multiple IQueryable<T>'s causes "EmptyProjectionMember" exception on the InMemory database

### ISSUE THREAD

**Issue by NinovanderMark** [dotnet/efcore#30905]
When concatenating multiple `IQueryable<T>`'s, where one refers to a `DbSet<T>` and the other simply projects to a compatible `IQueryable<T>`, I get a `KeyNotFoundException` stating that `The given key 'EmptyProjectionMember' was not present in the dictionary`.

I'm unable to determine what part of my query is the issue, either query works fine separately. The reason I want to concatenate them as such, is so that I can apply paging, sorting and filtering on the combined set, as though they were the same entity.

This may not actually be a supported operation, I noticed that using a different provider (for our SQL server) causes the problems as well (`Unable to translate set operation after client projection has been applied`).

I've searched for similar issues, but found only these issues for older EF Core versions, which are already closed, and may not be related.
https://github.com/dotnet/efcore/issues/20277
https://github.com/dotnet/efcore/issues/22089

### Minimal example code

Here's a simple example project that reproduces the issue I'm seeing:
https://github.com/NinovanderMark/EmptyProjectionMember-Reproduction

My guess is that there's something about combining these queries that doesn't quite work out.
```csharp
// Running queries on the data
var carList = dbContext.Set<Car>().AsQueryable();
var oldCarList = from car in dbContext.Set<OldCar>()
				 .Include(c => c.Driver)
				 select new Car
				 {
					 Id = car.Id,
					 Brand = car.CarBrand,
					 DriverName = car.Driver.Name
				 };

var combinedList = carList.Concat(oldCarList);
var result = combinedList.ToList(); // <= Exception occurs here
```

### Stacktrace

```
The given key 'EmptyProjectionMember' was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException[T](T key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryExpression.GetProjection(ProjectionBindingExpression projectionBindingExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.ShaperExpressionProcessingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions(ExpressionVisitor visitor, BlockExpression block)
   at System.Linq.Expressions.ExpressionVisitor.VisitBlock(BlockExpression node)
   at System.Linq.Expressions.BlockExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.ShaperExpressionProcessingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.ShaperExpressionProcessingExpressionVisitor.ProcessShaper(Expression shaperExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.VisitShapedQuery(ShapedQueryExpression shapedQueryExpression)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EmptyProjectionMember_Reproduction.Program.Main(String[] args) in D:\Code\GitHub\EmptyProjectionMember-Reproduction\Program.cs:line 39
```

### Provider and version information

EF Core version: 6.0.16
Database provider: Microsoft.EntityFrameworkCore.InMemory
Target framework: .NET 6.0
Operating system: Windows 10 22H2
IDE: Visual Studio 2022 17.5.3

**Comment by NinovanderMark** [comment]
We've been trying to work around this issue and found that doing `AsEnumerable()` for both queries, and concatenating those instead, works as intended.

**Comment by sam-wheat** [comment]
Here is another data point for this issue.  I hope this is the right place for this since this ticket is tagged  as "area-in-memory" and the code below should run on the server although we never quite get there.

	<Project Sdk="Microsoft.NET.Sdk">
	  <PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net7.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	  </PropertyGroup>
		<ItemGroup>
			<PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.5" />
			<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.5" />
		</ItemGroup>
	</Project>




	using Microsoft.EntityFrameworkCore;

	namespace EmptyProjectionMemberTest;

	internal class Program
	{
		static async Task Main(string[] args)
		{
			DbContextOptionsBuilder builder = new();
			builder.UseSqlServer("Data Source=.;Initial Catalog=EmptyProjectionMemberTest;Integrated Security=True;MultipleActiveResultSets=True;Encrypt=false");
			Db db = new(builder.Options);
			await db.Database.EnsureDeletedAsync();
			await db.Database.EnsureCreatedAsync();

			try
			{
				var query = db.ReleaseDates
					.GroupBy(x => new { x.ReleaseID, x.DateReleased })
					.Select(x => x.First())
					.GroupBy(x => x.ReleaseID);

				string sql = query.ToQueryString(); // fails here

				var stuff = query.ToListAsync();
			}
			catch(Exception ex) 
			{
				Console.WriteLine(ex.ToString()); // The given key 'EmptyProjectionMember' was not present in the dictionary.
			}
		}
	}


	public class Db : DbContext
	{
		public Db(DbContextOptions options) : base(options) { }

		public DbSet<ReleaseDate> ReleaseDates { get; set; }
	}

	public class ReleaseDate
	{
		public int ID { get; set; }
		public string ReleaseID { get; set; }
		public DateTime DateReleased { get; set; }
	}

**Comment by roji** [comment]
@sam-wheat can you please open this as a separate issue? This one is specifically about Concat support in InMemory.
