### ISSUE TITLE
Microsoft.Data.Sqlite Get System.OverflowException When read uint type data from sqlite

### ISSUE THREAD

**Issue by CwjXFH** [dotnet/efcore#30910]
I read some data from SQLite will throwing System.OverflowException when the column value is greater than `int.MaxValue`  (e.g. 2950121986), column type in SQLite is INTEGER.
```c#
await using var conn = new SqliteConnection(connStr);
var entity = await conn.QueryAsync<InfoEntity>("SELECT Vol FROM Daily_Bargain WHERE ROWID=291397");
```

```c#
public class InfoEntity
{
    public uint Vol { set; get; }
}
```

I change the Vol type to ulong, which will be ok.

|package|version|
|---|---|
|Dapper|2.0.123|
|Microsoft.Data.Sqlite|7.0.5|
|.NET|7|

**Comment by CwjXFH** [comment]
@roji I use uint type in my application, and store the uint type value in SQLite, but when read it from SQLite, get an overflow exception.

**Comment by ajcvickers** [comment]
@CwjXFH This should be reported to `Dapper` since the stack trace indicates it is an issue in Dapper's mapping.

```
Unhandled exception. System.Data.DataException: Error parsing column 1 (Vol=2147483648 - Int64)
 ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at Deserializef173a26d-c8fa-4a16-8150-de553f84efa5(IDataReader)
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3706
   at Deserializef173a26d-c8fa-4a16-8150-de553f84efa5(IDataReader)
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command)
   at Program.<Main>$(String[] args)
   at Program.<Main>$(String[] args)
   at Program.<Main>(String[] args)
```

```C#
await using var conn = new SqliteConnection("Data Source=test.db");
var entity = (await conn.QueryAsync<InfoEntity>("SELECT Id, Vol FROM InfoEntity WHERE ROWID=1")).Single();
Console.WriteLine(entity.Vol);

// using (var context = new SomeDbContext())
// {
//      // context.Database.EnsureDeleted();
//      // context.Database.EnsureCreated();
//      //
//      // context.Add(new InfoEntity { Vol = (uint)int.MaxValue + 1 });
//      // context.SaveChanges();
// }
//
// using (var context = new SomeDbContext())
// {
//     Console.WriteLine(context.Set<InfoEntity>().Single().Vol);
// }

public class InfoEntity
{
    public int Id { get; set; }
    public uint Vol { set; get; }
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlite("Data Source=test.db")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<InfoEntity>();
    }
}
```
