### ISSUE TITLE
Error when querying using collection of custom ids with value converters

### ISSUE THREAD

**Issue by jose8789** [dotnet/efcore#30935]
## I'm having an error since I upgrade to last preview of ef (EF 8 preview 4), when I try to use a collection of custom ids that have value converter ef is giving an error. Isn't there a way not to disable the new behavior just by this query? I know I can set compatibility in ef configuration to have the old behavior but i would like to just disable for this particular query as it seems to not be supported yet.

```C#
public class StudentIdConverter : ValueConverter<StudentId, int>
{
    public StudentIdConverter() : base(c => c.Value, value => StudentId.CreateDb(value))
    {
    }
}

public class Student : Entity<Student, StudentId>, IAggregateRoot<StudentId>
{
    private readonly List<Enrollment> _enrollments = new();
    public Student(FullName fullName, Gender gender, DateOnly birthDate, StudentId id) : base(id)
    {
        FullName = fullName;
        Gender = gender;
        BirthDate = birthDate;
    }
    public FullName FullName { get; private set; }
    public Gender Gender { get; private set; }
    public DateOnly BirthDate { get; set; }
    public IEnumerable<Enrollment> Enrollments => _enrollments.AsReadOnly();
}


and in my repository I have a method like 
 public async Task<List<T>> FindByIds<TProperty>(IEnumerable<TId> ids, Expression<Func<T, TProperty>> includeNavigationParameterPath) {
        return await Table.Include(includeNavigationParameterPath).Where(x => ids.Contains(x.Id)).ToListAsync();
  }

When I call the method like 

var students = await _studentRepository.FindByIds(studentIds, x => x.Enrollments);
```

### Include stack traces

Include the full exception message and stack trace for any exception you encounter.

Use triple-tick fences for stack traces. For example:

```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (6ms) [Parameters=[@__ids_0='?' (Size = 4000)], CommandType='Text', CommandTimeout='30']
      SELECT [s].[Id], [s].[BirthDate], [s].[FullName], [s].[Gender], [e].[Id], [e].[CourseId], [e].[Date], [e].[Grade], [e].[SchoolYear], [e].[StudentId]
      FROM [Student] AS [s]
      LEFT JOIN [Enrollment] AS [e] ON [s].[Id] = [e].[StudentId]
      WHERE EXISTS (
          SELECT 1
          FROM OpenJson(@__ids_0) AS [i]
          WHERE CAST([i].[value] AS int) = [s].[Id])
      ORDER BY [s].[Id]
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'Classrooms.API.Cqrs.Commands.Infrastructure.ClassroomContext'.
      Microsoft.Data.SqlClient.SqlException (0x80131904): Falha ao converter o nvarchar valor '{"Value":182}' para o tipo de dados int.
         at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
         at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
         at Microsoft.Data.SqlClient.SqlDataReader.ReadAsyncExecute(Task task, Object state)
         at Microsoft.Data.SqlClient.SqlDataReader.InvokeAsyncCall[T](SqlDataReaderBaseAsyncCallContext`1 context)
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
      ClientConnectionId:a2652e71-80c6-4a51-8307-0b5fef7a5a69
      Error Number:245,State:1,Class:16
      Microsoft.Data.SqlClient.SqlException (0x80131904): Falha ao converter o nvarchar valor '{"Value":182}' para o tipo de dados int.
         at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
         at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
         at Microsoft.Data.SqlClient.SqlDataReader.ReadAsyncExecute(Task task, Object state)
         at Microsoft.Data.SqlClient.SqlDataReader.InvokeAsyncCall[T](SqlDataReaderBaseAsyncCallContext`1 context)

```

### Include provider and version information

EF Core version: EF8 Preview 4
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 8.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.7)

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
