### ISSUE TITLE
EF.Functions.Contains cannot correctly translate search condition of multiple words with boolean operators

### ISSUE THREAD

**Issue by sgjsakura** [dotnet/efcore#30986]
## Problem 

I want to generate a full-text search with multiple keywords, the SQL is just like:

```SQL
SELECT * FROM [Topics] WHERE CONTAINS([Title], N'hello AND world')
```
that means I want to search for all topics whose title contains both "hello" and "world".

I want to use EF Core to produce the query just like
```C#
var result = 
  from i in dbContext.Topics
  where EF.Functions.Contains(i.Title, 'hello AND world')
  orderby i.CreationTime descending
  select i;
```

When the above code is executed, the application raises a `Microsoft.Data.SqlClient.SqlException` with message `There's a syntax error near 'world' in the full-text search condition 'hello world`.

It seems the boolean operator is be incorrectly removed when translating the LINQ  statement,

Please fix this issue or provide additional documentation about how to perform such kind SQL query if there's already a walkaround. Many thanks!

## Output and Stacktrace:
```
Microsoft.Data.SqlClient.SqlException (0x80131904): There's a syntax error near 'world' in the full-text search condition 'hello world'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__208_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

Microsoft.EntityFrameworkCore.Database.Command: Error: Failed executing DbCommand (186ms) [Parameters=[@__keyword_1='?' (Size = 250), CommandType='Text', CommandTimeout='30']
SELECT [t].[Id], [t].[BoardId], [t].[CreationTime], [t].[PostUserId], [t].[PostUserName], [t].[ReplyCount], [t].[State], [t].[Title]
FROM [Topic] AS [t]
WHERE CONTAINS([t].[Title], @__keyword_1)
ORDER BY [t].[CreationTime] DESC
```

## Provider Information:

EF Core version: 7.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7
Operating system: Windows 11 Professional
IDE: Visual Studio 2022 17.6.2

**Comment by roji** [comment]
I cannot reproduce this - see the below minimal code sample which uses Contains with AND successfully. Please tweak that code sample to show the failure, or submit a similar one so we can reproduce the problem. Note that EF doesn't actually do anything to the string argument that you pass to EF.Functions.Contains - it simply embeds it into the SQL query as-is.

<details>
<summary>Attempted repro</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

await ctx.Database.ExecuteSqlAsync($"""
CREATE FULLTEXT CATALOG [Blogs_FTC] AS DEFAULT;
CREATE FULLTEXT INDEX ON [Blogs] ([Name]) KEY INDEX [PK_Blogs];
""");

_ = await ctx.Blogs.Where(b => EF.Functions.Contains(b.Name, "foo AND bar")).ToArrayAsync();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class Blog
{
    public int Id { get; set; }
    public string? Name { get; set; }
}
```

</details>

**Comment by sgjsakura** [comment]
Sorry this problem is caused by a code issue and it now be fixed.  I'm closing this issue and many thanks to your help :-)
