### ISSUE TITLE
When using SqlServerRetryingExecutionStrategy, on retry exception thrown

### ISSUE THREAD

**Issue by dekenless** [dotnet/efcore#31000]
## File a bug

When using SqlServerRetryingExecutionStrategy and the command,  db.Set<T>().FromSqlRaw(sql, parameters).ToList() is executed, then retried automatically the exception below is thrown. 

The command being executed is a stored procedure with parameters.

I seem to recall a similar issue if EF6 https://github.com/dotnet/ef6/issues/81

### Include stack traces

Include the full exception message and stack trace for any exception you encounter.

Use triple-tick fences for stack traces. For example:

```
System.ArgumentException: The SqlParameter is already contained by another SqlParameterCollection.
   at Microsoft.Data.SqlClient.SqlParameterCollection.Validate(Int32 index, Object value)
   at Microsoft.Data.SqlClient.SqlParameterCollection.Add(Object value)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RawRelationalParameter.AddDbParameter(DbCommand command, Object value)
   at Microsoft.EntityFrameworkCore.Storage.Internal.CompositeRelationalParameter.AddDbParameter(DbCommand command, Object value)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBase.AddDbParameter(DbCommand command, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.CreateDbCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass28_0`2.<Execute>b__0(DbContext context, TState state)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.Enumerator.MoveNext()
```

### Include provider and version information

EF Core version: 7.0.5
Database provider: . Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET 7.0
Operating system: Windows
IDE:  Visual Studio 2022 17.5

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by dekenless** [comment]
> This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

[EfCoreSample.zip](https://github.com/dotnet/efcore/files/11625617/EfCoreSample.zip)
Attached is a sample application demonstrating the issue. To force the retry, I am pausing the SQL Server--though that is not required, but just a simple way to force the issue.
