### ISSUE TITLE
Duplicate entries in join table when updating entity with many-to-many property/ies

### ISSUE THREAD

**Issue by sultan** [dotnet/efcore#31033]
## fix: Add support for easily updating many-to-many property/ies

Remember:
* [x] Please check that the [documentation](https://docs.microsoft.com/ef/) does not explain the behavior you are seeing.
* [x] Please search in both [open](https://github.com/dotnet/efcore/issues) and [closed](https://github.com/dotnet/efcore/issues?q=is%3Aissue+is%3Aclosed) issues to check that your bug has not already been filed.

### code

```C#
// Copyright (c) 2023 the original author or authors.

namespace Pizzas.Models;

[ Table( "pizza" ) ]
public class Pizza
{
	public int Id { get; set; }
	public string Nom { get; set; }

	// associations -to-one

	[ Required ]
	public virtual Pate? Pate { get; set; }

	// associations -to-many

	[ MinLength(1) ]
	public virtual List<Ingredient> Ingredients { get; set; } = new();

	public override string ToString()
	{
		return $"{GetType().Name} {{ {Id}, {Nom}, {Pate}, {string.Join(", ", Ingredients)} }}";
	}
}
```

```C#
if ( pizza.Id == default )
{
	_context.Add(pizza);
	await _context.SaveChangesAsync();
}
else
{
	_context.Update(pizza);
	await _context.SaveChangesAsync();
}
```

### stack traces

```
2023-06-05 14:18:44.274 +02:00  fail: Microsoft.EntityFrameworkCore.Update[10000] An exception occurred in the database while saving changes for context type 'Pizzas.Data.PizzasDbContext'. Microsoft.EntityFrameworkCore.DbUpdateE
xception: Could not save changes. Please configure your entity type accordingly.
  ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Duplicate entry '14-1' for key 'PRIMARY'
    at MySql.Data.MySqlClient.MySqlStream.ReadPacketAsync(Boolean execAsync)
    at MySql.Data.MySqlClient.NativeDriver.GetResultAsync(Int32 affectedRow, Int64 insertedId, Boolean execAsync)
    at MySql.Data.MySqlClient.Driver.GetResultAsync(Int32 statementId, Int32 affectedRows, Int64 insertedId, Boolean execAsync)
    at MySql.Data.MySqlClient.Driver.NextResultAsync(Int32 statementId, Boolean force, Boolean execAsync)
    at MySql.Data.MySqlClient.MySqlDataReader.NextResultAsync(Boolean execAsync, CancellationToken cancellationToken)
    at MySql.Data.MySqlClient.MySqlDataReader.NextResultAsync(Boolean execAsync, CancellationToken cancellationToken)
    at MySql.Data.MySqlClient.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean execAsync, CancellationToken cancellationToken)
    at MySql.Data.MySqlClient.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean execAsync, CancellationToken cancellationToken)
    at MySql.Data.MySqlClient.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean execAsync, CancellationToken cancellationToken)
    at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
    --- End of inner exception stack trace ---
    at MySql.EntityFrameworkCore.Update.MySQLModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
    at MySql.EntityFrameworkCore.Storage.Internal.MySQLExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken) Microsoft.EntityFrameworkCore.DbUpdateException: Could not save changes. Please configure your entity type accordingly.
  ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Duplicate entry '14-1' for key 'PRIMARY'
    at MySql.Data.MySqlClient.MySqlStream.ReadPacketAsync(Boolean execAsync)
    at MySql.Data.MySqlClient.NativeDriver.GetResultAsync(Int32 affectedRow, Int64 insertedId, Boolean execAsync)
    at MySql.Data.MySqlClient.Driver.GetResultAsync(Int32 statementId, Int32 affectedRows, Int64 insertedId, Boolean execAsync)
    at MySql.Data.MySqlClient.Driver.NextResultAsync(Int32 statementId, Boolean force, Boolean execAsync)
    at MySql.Data.MySqlClient.MySqlDataReader.NextResultAsync(Boolean execAsync, CancellationToken cancellationToken)
    at MySql.Data.MySqlClient.MySqlDataReader.NextResultAsync(Boolean execAsync, CancellationToken cancellationToken)
    at MySql.Data.MySqlClient.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean execAsync, CancellationToken cancellationToken)
    at MySql.Data.MySqlClient.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean execAsync, CancellationToken cancellationToken)
    at MySql.Data.MySqlClient.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean execAsync, CancellationToken cancellationToken)
    at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
    --- End of inner exception stack trace ---
    at MySql.EntityFrameworkCore.Update.MySQLModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
    at MySql.EntityFrameworkCore.Storage.Internal.MySQLExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

### provider and version information

EF Core version: 7.0.+
Database provider: mysql OR inmemory OR sqlserver (any will fail into bug)
Target framework: .NET 7.0
Operating system: Windows
IDE: Rider

### workaround

this bug can be fixed if the orm would be kind enough to delete the duplicate entries before adding the new entries

```C#
// Copyright (c) 2023 the original author or authors.

if ( pizza.Id == default )
{
	_context.Add(pizza);
	await _context.SaveChangesAsync();
}
else
{
	// begin many-to-many update //
	var old = await _context.Pizzas.FindAsync(pizza.Id);
	if ( old != default )
	{
		await using var transaction = await _context.Database.BeginTransactionAsync();
		try
		{
			// prepare: clean all many-to-many properties to avoid duplicate (and remove old) entries in join tables
			// this is necessary with current orm, even if the many-to-many properties were untouched
			old.Ingredients.Clear();

			// act: delete duplicate and old entries in join tables
			_context.Update(old);
			await _context.SaveChangesAsync();
			_context.Entry(old).State = EntityState.Detached;

			// act: update with new values including current/new entries in join tables
			// when orm will support many-to-many, this will be the only necessary code
			_context.Update(pizza);
			await _context.SaveChangesAsync();

			await transaction.CommitAsync();
		}
		catch ( Exception )
		{
			await transaction.RollbackAsync();
			throw;
		}
	} // else TODO warn that pizza does not exist anymore ? or just save back ?
	// end many-to-many update //
}
```

**Comment by sultan** [comment]
in memory stack trace
```
2023-06-05 15:45:29.011 +02:00 fail: Microsoft.EntityFrameworkCore.Update[10000] An exception occurred in the database while saving changes for context type 'Pizzas.Data.PizzasDbContext'.
 System.ArgumentException: An item with the same key has already been added. Key: System.Object[]
    at System.Collections.Generic.Dictionary2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
    at System.Collections.Generic.Dictionary2.Add(TKey key, TValue value)
    at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryTable1.Create(IUpdateEntry entry, IDiagnosticsLogger1 updateLogger)
    at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryStore.ExecuteTransaction(IList1 entries, IDiagnosticsLogger1 updateLogger)
    at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryDatabase.SaveChangesAsync(IList1 entries, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList1 entriesToSave, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

**Comment by sultan** [comment]
sql server stack trace
```
2023-06-05 16:51:16.460 +02:00 fail: Microsoft.EntityFrameworkCore.Update[10000] An exception occurred in the database while saving changes for context type 'Pizzas.Data.PizzasDbContext'.
 Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'pk_pizza_ingredient'.
 Cannot insert duplicate key in object 'dbo.pizza_ingredient'. The duplicate key value is (1, 1).
    at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action1 wrapCloseInAction)
    at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action1 wrapCloseInAction)
    at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
    at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
    at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
    at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreResults(Boolean& moreResults)
    at Microsoft.Data.SqlClient.SqlDataReader.TryNextResult(Boolean& more)
    at Microsoft.Data.SqlClient.SqlDataReader.NextResultAsyncExecute(Task task, Object state)
    at Microsoft.Data.SqlClient.SqlDataReader.InvokeAsyncCall[T](SqlDataReaderAsyncCallContext1 context)
    --- End of stack trace from previous location ---
    at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
 ClientConnectionId:a23e40aa-db6b-4822-ab94-f4609fed4dda Error Number:2627,State:1,Class:14
    --- End of inner exception stack trace ---
    at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList1 entriesToSave, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func4 operation, Func4 verifySucceeded, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by sultan** [comment]
> This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

ok sending two files

```xml
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="EFCore.NamingConventions" Version="7.0.*" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0-preview.4.*" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.0-preview.4.*" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="8.0.0-preview.4.*" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0-preview.4.*" />
		<PackageReference Include="MySql.EntityFrameworkCore" Version="7.0.*" />
	</ItemGroup>

</Project>
```

```cs
//

using Microsoft.EntityFrameworkCore;

internal class Program
{
	public static void Main(string[] args)
	{

// the database is created and seeded
		{
			using var context = new DemoDbContext();
			context.Database.EnsureDeleted();
			context.Database.EnsureCreated();
			var tomato = new Topping { Name = "Tomato" };
			var cheese = new Topping { Name = "Cheese" };
			var ham = new Topping { Name = "Ham" };
			var regina = new Pizza { Name = "Regina" , Toppings = { tomato } };
			context.AddRange( tomato, cheese, ham, regina );
			context.SaveChanges();
		}

// a user wants to update a pizza, remove a topping and add another one,
// but the update is incorrect and the pizza ends up with 2 toppings instead of 1
		{
			using var context = new DemoDbContext();
			var tomato = new Topping { Id = 1 , Name = "Tomato" };
			var cheese = new Topping { Id = 2 , Name = "Cheese" };
			var ham = new Topping { Id = 3 , Name = "Ham" };
			var regina = new Pizza { Id = 1 , Name = "Regina" , Toppings = { cheese } };

			// simple wanted behavior, fails (has 2 toppings instead of 1)
			context.Update( regina );
			context.SaveChanges();
		}

		{
			// proof of failure
			using var context = new DemoDbContext();
			var regina = context.Find( typeof(Pizza) , 1 ) as Pizza;
			Console.WriteLine( "Pizza has " + regina.Toppings.Count + " toppings instead of 1" );
		}

// a user wants to update a pizza, remove a topping and add another one,
// the update works (but the solution is complex and unwanted)
		{
			using var context = new DemoDbContext();
			var tomato = new Topping { Id = 1 , Name = "Tomato" };
			var cheese = new Topping { Id = 2 , Name = "Cheese" };
			var ham = new Topping { Id = 3 , Name = "Ham" };
			var regina = new Pizza { Id = 1 , Name = "Regina" , Toppings = { ham } };

			// complex unwanted solution, works
			var old = context.Find( typeof(Pizza) , 1 ) as Pizza;
			if ( old is not null )
			{
				old.Toppings.Clear();
				context.Update( old );
				context.SaveChanges();
				context.Entry(old).State = EntityState.Detached;

				context.Update( regina );
				context.SaveChanges();
			}
		}

		{
			// proof of success
			using var context = new DemoDbContext();
			var regina = context.Find( typeof(Pizza) , 1 ) as Pizza;
			Console.WriteLine( "Pizza has " + regina.Toppings.Count + " topping(s) (1 is good)" );
		}

// a user wants to update a pizza, without changing its toppings,
// but the update fails in error
		{
			using var context = new DemoDbContext();
			var tomato = new Topping { Id = 1 , Name = "Tomato" };
			var cheese = new Topping { Id = 2 , Name = "Cheese" };
			var ham = new Topping { Id = 3 , Name = "Ham" };
			var regina = new Pizza { Id = 1 , Name = "Super Regina" , Toppings = { ham } };

			// simple wanted behavior, fails in error
			context.Update( regina );
			context.SaveChanges();
		}
	}
}
// Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: System.Object[]
// problem is join table already has a row with key (1, 3) (= Regina, Ham) and the update tries to add them again
// using a database with no PK results in the table having 2 rows with key (1, 3).
// which proves that the update is trying to add the toppings again
// a workaround is to delete the toppings from the pizza before updating it

// JPA has a @ManyToMany annotation that works fine by deleting the toppings from the pizza before updating it
// with JPA the keys are not duplicated in the join table and ordered by pizza_id, topping_id like it would have if inserted for the first time

// please consider a solution that would have a similar result in database
// where old toppings are not there anymore
// where toppings are not duplicated
// where record order is as if inserted for the first time (and proximity of keys in the table for read performance)

public class DemoDbContext : DbContext
{
	public DemoDbContext() : base()
	{
	}
	protected override void OnConfiguring( DbContextOptionsBuilder builder )
	{
		base.OnConfiguring(builder);
		builder
			.UseInMemoryDatabase("demo")
			.UseSnakeCaseNamingConvention()
			.UseLazyLoadingProxies();
	}
	protected override void OnModelCreating( ModelBuilder builder )
	{
		base.OnModelCreating(builder);
		builder
			.Entity<Pizza>()
			.HasMany<Topping>( p => p.Toppings )
			.WithMany();
	}
}

public class Pizza
{
	public override string ToString() => $"{GetType().Name} {Id} {Name}";

	public int Id { get; set; }
	public string Name { get; set; } = string.Empty;
	public virtual List<Topping> Toppings { get; set; } = new();
}

public class Topping
{
	public override string ToString() => $"{GetType().Name} {Id} {Name}";

	public int Id { get; set; }
	public string Name { get; set; } = string.Empty;
}
```

**Comment by sultan** [comment]
an alternative workaround is 

```cs
{
	using var context = new DemoDbContext();
	var tomato = context.Find( typeof(Topping) , 1 ) as Topping;
	var cheese = context.Find( typeof(Topping) , 2 ) as Topping;
	var ham = context.Find( typeof(Topping) , 3 ) as Topping;
	var regina = new Pizza { Id = 1 , Name = "Regina" , Toppings = { tomato, cheese, ham } };

	// complex unwanted solution, works
	var old = context.Find( typeof(Pizza) , 1 ) as Pizza;
	if ( old is not null )
	{
		old.Toppings.Clear();
		old.Toppings.AddRange( regina.Toppings );
		context.Update( old );
		context.SaveChanges();
		context.Entry(old).State = EntityState.Detached;

		regina.Toppings.Clear();
		context.Update( regina );
		context.SaveChanges();
	}
}

```

**Comment by sultan** [comment]
this may be caused by how non-attached lists are treated differently from attached ones.

**Comment by sultan** [comment]
a solution could be to have a way to tell if the list is an original read from db or instantiated by user
* use list read from db to track changes (already works)
* in case of list not read from db, then compute delta by comparing data from db vs list from user

**Comment by ajcvickers** [comment]
Duplicate of #28005 and #27677

**Comment by sultan** [comment]
if you can point me to some class that evaluates the state before acting i will gladely help coding and test cases

**Comment by sultan** [comment]
if you can point me to some class that evaluates the state before acting i will gladely help coding and test cases

**Comment by ajcvickers** [comment]
@sultan What, specifically, are you suggesting doing?

**Comment by ajcvickers** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by sultan** [comment]
reproducible from versions 5.0 to 10 included.

stateManager.GetEntriesForState detects that Cheese has been added to Regina Pizza but fails to see that Tomato was removed

<img width="1919" height="1031" alt="Image" src="https://github.com/user-attachments/assets/0fb4c97d-3816-429d-958e-b5aa03b96d2d" />

<img width="725" height="570" alt="Image" src="https://github.com/user-attachments/assets/e3834762-cd39-4f0c-bb9c-a8dcff2eae80" />

**Comment by sultan** [comment]
and this is because the Update method does not look into database to check the existing relations :
* the root entity Pizza (detached, id 1 Regina) is moved from Detached to Modified, though only toppings where added, the Pizza did not have its simple properties modified.
* the Topping entity (detached, id 2 Cheese) is moved from Detached to Modified, though this Topping did not have its simple properties modified.
* the CLR Type PizzaTopping is generated by EF core (ok)
* the list of Toppings of the Regina Pizza is browsed, only the new relation (1,2) is found but the existing unwanted relation (1,1) is not in this list anymore, not found here nor searched in the DB to be detected nor removed

EF Core is lacking some features and if time allows on both our sides i will re open the issue as feature request
