### ISSUE TITLE
The given key 'EmptyProjectionMember' was not present in the dictionary

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/efcore#31209]
Possibly related to:

https://github.com/dotnet/efcore/issues/20277

https://github.com/dotnet/efcore/issues/22089

https://github.com/dotnet/efcore/issues/20929

https://github.com/dotnet/efcore/issues/30905

Exception:

	   System.Collections.Generic.KeyNotFoundException: The given key 'EmptyProjectionMember' was not present in the dictionary.
	   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
	   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ProjectionMemberToIndexConvertingExpressionVisitor.Visit(Expression expression)
	   at Microsoft.EntityFrameworkCore.Query.EntityShaperExpression.VisitChildren(ExpressionVisitor visitor)
	   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ProjectionMemberToIndexConvertingExpressionVisitor.Visit(Expression expression)
	   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ApplyProjection(Expression shaperExpression, ResultCardinality resultCardinality, QuerySplittingBehavior querySplittingBehavior)
	   at Microsoft.EntityFrameworkCore.Query.Internal.SelectExpressionProjectionApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
	   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPostprocessor.Process(Expression query)
	   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerQueryTranslationPostprocessor.Process(Expression query)
	   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
	   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
	   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
	   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
	   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
	   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
	   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
	   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToQueryString(IQueryable source)
	   at EmptyProjectionMemberTest.Program.Main(String[] args) in C:\Projects\EmptyProjectionMemberTest\EmptyProjectionMemberTest\Program.cs:line 26

Reproduce:

	<Project Sdk="Microsoft.NET.Sdk">
	  <PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net7.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	  </PropertyGroup>
		<ItemGroup>
			<PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.5" />
			<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.5" />
		</ItemGroup>
	</Project>

	using Microsoft.EntityFrameworkCore;

	namespace EmptyProjectionMemberTest;

	internal class Program
	{
		static async Task Main(string[] args)
		{
			DbContextOptionsBuilder builder = new();
			builder.UseSqlServer("Data Source=.;Initial Catalog=EmptyProjectionMemberTest;Integrated Security=True;MultipleActiveResultSets=True;Encrypt=false");
			Db db = new(builder.Options);
			await db.Database.EnsureDeletedAsync();
			await db.Database.EnsureCreatedAsync();

			try
			{
				var query = db.ReleaseDates
					.GroupBy(x => new { x.ReleaseID, x.DateReleased })
					.Select(x => x.First())
					.GroupBy(x => x.ReleaseID);

				string sql = query.ToQueryString(); // fails here

				var stuff = query.ToListAsync();
			}
			catch(Exception ex) 
			{
				Console.WriteLine(ex.ToString()); // The given key 'EmptyProjectionMember' was not present in the dictionary.
			}
		}
	}

	public class Db : DbContext
	{
		public Db(DbContextOptions options) : base(options) { }

		public DbSet<ReleaseDate> ReleaseDates { get; set; }
	}

	public class ReleaseDate
	{
		public int ID { get; set; }
		public string ReleaseID { get; set; }
		public DateTime DateReleased { get; set; }
	}

**Comment by hahn-kev** [comment]
I'm also seeing this, my query is a little different though.
```C#
queryable.GroupBy(s => s.EntityId)
.Select(g => g.OrderByDescending(s => s.Commit.DateTime).First())
.Select(s => s.Id)
.ToArray()
```

the second Select breaks everything, without the second select it works fine. This is a simplification but it has the same issue.

**Comment by ZoySoy** [comment]
Hello. I also could reproduce "The given key 'EmptyProjectionMember' was not present in the dictionary" exception but on the little bit different example. I faced with this problem during migration from EntityFramework 6.4.4 to EF core. On EF 6.4.4 this query worked well. I have prepared similar repro example based on [https://learn.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=visual-studio](default blog/post example). There is failed query example:

`using var db = new BloggingContext();`
`var posts = db.Posts`
`    .GroupBy(`
`        p => p.BlogId, `
`        (id, list) => list.OrderByDescending(x => x.PostId).First())`
`    .Where(p => p.Title != null)`
`   .ToList();`

For this particular case the problem can be solved by moving Where(...) method before GroupBy(...), but maybe this case will help you to find initial problem anyway because, as I mentioned, it worked previously and I don't think that it is such an unusual query which shouldn't work.

Frameworks:
net6.0
EntityFrameworkCore - 7.0.13

Thanks in advance.

**Comment by lucasbode** [comment]
I encountered a similar error with a query like this...

```
var results = Context.TruckModel
            .GroupBy(v => v.TruckModelId)
            .Select(g => g.OrderByDescending(x => x.Version).FirstOrDefault())
            .Where(t => t.Name == truckModelName)
            .ToList();
```
           

It looks silly, but we were able to work around it by doing this...

```
var groupedQuery = Context.TruckModel
            .GroupBy(v => v.TruckModelId)
            .Select(g => g.OrderByDescending(x => x.Version).FirstOrDefault());

var results = Context.TruckModel.FromSqlRaw(groupedQuery.ToQueryString())
            .Where(t => t.Name == truckModelName)
            .ToList();
```

**Comment by lvyyln** [comment]
Any updates on this one?

**Comment by roji** [comment]
This issue is in the Backlog milestone. This means that it is not planned for the next release (EF Core 8.0). We will [re-assess the backlog](https://docs.microsoft.com/ef/core/what-is-new/release-planning) following the this release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources. Make sure to vote (👍) for this issue if it is important to you.

**Comment by kwakubiney** [comment]
Facing similar issue with this:
```
     _dbContext.Crashes
                .Where(x => x.ShopId == partnerId)
                .OrderByDescending(x => x.CreatedAt)
                .GroupBy(t => t.SerialNumber)
                .Select(g => g.First())
                .AsNoTracking();
```

**Comment by TimFeldmann-Patriot** [comment]
I am also running into this exact issue and spent the past 5 hours trying to find a workaround with no success.

**Comment by TimFeldmann-Patriot** [comment]
Using your sample:

```csharp
var results = await _dbContext.Crashes
    .GroupBy(
      v => new {v.Name, v.Color, v.Make },
      // Retrieve only the latest crash per Name / Color / Make group.
      (key, group) => group.OrderByDescending(v => v.Year).First())
    // This is where it breaks.
    // I want to order the final result set by year.
    // If I remove this OrderByDescending, the query works fine.
    .OrderByDescending(g => g.OrderByDescending(x => x.Year).ToListAsync());
```

I continued to troubleshoot this after I made my last post desperate for any kind of a solution.

It's been a total of 10 hours today and I settled on the worst code I've written in 3 years:

I'm using `IQueryable.TagWith("X")` to add a query hint to the final SQL. Then, I registered an interceptor to check for the tag and manually append a raw SQL order by clause depending on which tag I added.

This is in my opinion a very dirty solution to this problem, but I wasn't able to find an alternative solution. The proposed `.ToQueryString()` workaround does not work for me because my `GroupBy` clause contains parameters and I was not able to locate a way to return both the SQL string as well as the parameters.

I had the horrible thought of parsing out the SQL string returned by `ToQueryString()` with its parameters at the top and manually reconstructing them in code, but that was one step too far into degeneracy for me.

I understand fully that translating all forms of LINQ to SQL is an astronomical task. However, it would be great if there was a way to manually append any arbitrary SQL to the end of whatever SQL Entity Framework generates so I don't have to rely on application-wide interceptors which run for *all* SQL commands. 

A simple `IQueryable.AppendSql(sql, parameters)` method would be amazing for these types of scenarios. This workaround would still not have been preferred, however it would have been better than my interceptor.

Considering this issue has been open for over a year, I'm assuming it's not a high priority, however my job relies on this functionality as the base `IQueryable` is dynamically generated from a bunch of parameters and it works great, except for this part.

You could make the argument that I could just use raw SQL for this, however the SQL my application works with is highly dynamic depending on a wide and dynamic set of parameters and I wasn't looking to build out a flaky type-unsafe SQL builder for this.

I've been working with EF Core for close to 6 years almost non-stop as my basis for building internal developer frameworks. This is the first time I've run into a problem requiring such a major hack like this.

**Comment by TimFeldmann-Patriot** [comment]
Yeah, I completely sympathize with the EF team, however a "catch all" solution for manually appending SQL to the end of an `IQueryable` would be great as a short / medium-term hacks until more translations are supported.

For now, I'll tuck my interceptor away into some dark corner of my project with a hand-written apology note to whoever comes across it lol.

**Comment by roji** [comment]
Everyone, this issue is on my radar; we have quite a few issues with the current GroupBy implementation (see the area-groupby label), and I hope to make a concentrated push on the whole area for EF 10. GroupBy translation is unfortunately a particularly tricky area in LINQ to SQL translation.

I fully understand the frustration here, and EF should indeed be translating these queries correctly (or at least throwing a clear exception where a translation really isn't possible).

In the meantime, EF does provide escape-hatch workarounds - interceptors can be used to add SQL, and SQL queries can allow you to specify the exact SQL you want, and then compose additional LINQ operators on top and use EF to materialize the results. These are imperfect workarounds until we solve the real problems here.

**Comment by TimFeldmann-Patriot** [comment]
Thank you @roji, it's very much appreciated!

Regarding the workarounds, I spent a few hours trying to use SQL + LINQ composition, however I was looking for a way to start with LINQ and then compose SQL over the LINQ expressions, instead of starting with SQL and then composing LINQ on top of the SQL which I don't think is possible unless I'm mistaken.

On a side / off-topic note, I've been building a Rebus competitor for the past 3 years using EF + jsonb and dynamic DBSets as the basis for managing Sagas and it's been an absolute pleasure. I've been reading your comments along with Aj's on various GitHub issues on a weekly basis for several years and you guys have been absolutely incredible, I'm always astonished by what you guys do.

I know it's corny, but thank you for building this incredible technology including the Npgsql implementation, it's an engineering marvel in my opinion.

**Comment by roji** [comment]
> I was looking for a way to start with LINQ and then compose SQL over the LINQ expressions, instead of starting with SQL and then composing LINQ on top of the SQL which I don't think is possible unless I'm mistaken.

That's indeed not possible, there are various complications around the integration of the LINQ expression inside user-provided SQL that have made this unfeasible, at least so far.

And thanks for all the kind words, they are much appreciated!

**Comment by curious-navigator2** [comment]
I also encountered this issue while using dotnet 8, ef core 8.0.11.

my query is similar to this:
```
var query = Context.Buyers
          .Where(x => x.IsActive &&
                      unitList.Contains(x.Unit.ToLower().Trim()))
          .GroupBy(x => x.BuyerId.TrimStart('0').ToLower().Trim())
          .Select(g => g.OrderBy(x => x.CreatedDate).Select(x => x).First());

// then the query will be processed with paging, e.g. filter, sorting, and end up like this

var list = await Task.FromResult(query.Skip(offset.Value).Take(limit.Value).ToList());
```

I ended up change the query as ToList first, then AsQueryable.

```
var query = Context.Buyers
          .Where(x => x.IsActive &&
                      unitList.Contains(x.Unit.ToLower().Trim()))
          .GroupBy(x => x.BuyerId.TrimStart('0').ToLower().Trim())
          .Select(g => g.OrderBy(x => x.CreatedDate).Select(x => x).First())
          .ToList()
          .AsQueryable();
```

I know it's not a good option but my pj has some considerations and I need to do it this way.

**Comment by trejjam** [comment]
It's not the subject of this issue, but please don't do:
`var list = await Task.FromResult(query.Skip(offset.Value).Take(limit.Value).ToList());`
It's nonsense, do this:
`var list = await query.Skip(offset.Value).Take(limit.Value).ToListAsync();`

```cs
.GroupBy(x => x.BuyerId.TrimStart('0').ToLower().Trim())
          .Select(g => g.OrderBy(x => x.CreatedDate).Select(x => x).First())
          .ToList()
          .AsQueryable()
```
is also really bad; it loads all data from the database and then applies filters (in your .NET app, not in the database).
Try to use this workaround instead https://github.com/dotnet/efcore/issues/31209#issuecomment-2093263276

**Comment by RichardD2** [comment]
I've just hit the same issue with EF Core 9.0.5 (`Microsoft.EntityFrameworkCore.SqlServer`) with the query:

```
var limits = await context.ActivityLimits
    .Where(l => l.StartDate <= forDay)
    .GroupBy(l => l.ActivityId, (_, items) => items.OrderByDescending(l => l.StartDate).First())
    .Select(l => new { l.ActivityId, l.StartDate, ... })
    .ToListAsync();
```

```
System.Collections.Generic.KeyNotFoundException: The given key 'EmptyProjectionMember' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.GetProjection(ProjectionBindingExpression projectionBindingExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.BindProperty(StructuralTypeReferenceExpression typeReference, IProperty property)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TryBindMember(Expression source, MemberIdentity member, Expression& expression, IPropertyBase& property)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TryBindMember(Expression source, MemberIdentity member, Expression& expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMember(MemberExpression memberExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TranslateInternal(Expression expression, Boolean applyDefaultTypeMapping)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TranslateProjection(Expression expression, Boolean applyDefaultTypeMapping)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberAssignment(MemberAssignment memberAssignment)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutorExpression[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass11_0`1.<ExecuteCore>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteCore[TResult](Expression query, Boolean async, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
```

No matter how simple I make the projection, I still get the same error.

In this case, the workaround was to move the projection before the `GroupBy`:

```
var limits = await context.ActivityLimits
    .Where(l => l.StartDate <= forDay)
    .Select(l => new { l.ActivityId, l.StartDate, ... })
    .GroupBy(l => l.ActivityId, (_, items) => items.OrderByDescending(l => l.StartDate).First())
    .ToListAsync();
```

**Comment by RichardD2** [comment]
Scratch that workaround - I've just discovered that it actually breaks the projection!

My projection loads the value of navigation properties from related entities. But when it's followed by the `GroupBy`, those properties are not included in the generated query, and are set to `null`.

Eg:

```
var limits = await context.ActivityLimits
    .Where(l => l.StartDate <= forDay)
    .Select(l => new { l.ActivityId, l.StartDate, ActivityName = l.Activity.Name })
    .GroupBy(l => l.ActivityId, (_, items) => items.OrderByDescending(l => l.StartDate).First())
    .ToListAsync();
```

uses the query:

```
SELECT [a3].[StartDate], [a3].[ActivityId], [a3].[Id], [a3].[CreatedBy], [a3].[CreatedDate], ..., [a3].[c]
FROM (
    SELECT [a].[ActivityId]
    FROM [dbo].[ActivityLimits] AS [a]
    WHERE [a].[StartDate] <= @__forDay_0
    GROUP BY [a].[ActivityId]
) AS [a1]
LEFT JOIN (
    SELECT [a2].[StartDate], [a2].[ActivityId], [a2].[Id], [a2].[CreatedBy], [a2].[CreatedDate], ..., [a2].[c]
    FROM (
        SELECT [a0].[StartDate], [a0].[ActivityId], [a0].[Id], [a0].[CreatedBy], [a0].[CreatedDate], ..., 1 AS [c], ROW_NUMBER() OVER(PARTITION BY [a0].[ActivityId] ORDER BY [a0].[StartDate] DESC) AS [row]
        FROM [dbo].[ActivityLimits] AS [a0]
        WHERE [a0].[StartDate] <= @__forDay_0
    ) AS [a2]
    WHERE [a2].[row] <= 1
) AS [a3] ON [a1].[ActivityId] = [a3].[ActivityId]
```

This query includes all of the columns from the `ActivityLimit` entity, and none of the columns from the projection! The `ActivityName` on the projection is `null` for every row.

---

It seems the *real* workaround is to rewrite the query as:

```
var groupedLimits = context.ActivityLimits
    .Where(l => l.StartDate <= forDay)
    .GroupBy(l => l.ActivityId, (_, items) => items.OrderByDescending(l => l.StartDate).First());

var projectedLimits = await context.ActivityLimits
    .Where(l => groupedLimits.Contains(l))
    .Select(l => new { l.ActivityId, l.StartDate, ActivityName = l.Activity.Name })
    .ToListAsync();
```

This uses the query:

```
SELECT [a].[StartDate], [a].[ActivityId], [a2].[Name] AS [ActivityName]
FROM [dbo].[ActivityLimits] AS [a]
INNER JOIN [dbo].[Activities] AS [a2] ON [a].[ActivityId] = [a2].[Id]
WHERE [a].[Id] IN (
    SELECT (
        SELECT TOP(1) [a1].[Id]
        FROM [dbo].[ActivityLimits] AS [a1]
        WHERE [a1].[StartDate] <= @__forDay_0 AND [a0].[ActivityId] = [a1].[ActivityId]
        ORDER BY [a1].[StartDate] DESC)
    FROM [dbo].[ActivityLimits] AS [a0]
    WHERE [a0].[StartDate] <= @__forDay_0
    GROUP BY [a0].[ActivityId]
)
```

which correctly populates the projection.

**Comment by dec123ac** [comment]
I am seeing what appears to be a variation on this defect. I receive this error message for an 'EmptyProjectionMember' even though I'm not expressly using a GroupBy() or OrderBy.

I put together three examples.  The first two work as expected by selecting the object directly and putting it in a list or selecting the object then putting it into an anonymous object and then tolist.

The third LINQ gives the error.  All it is doing differently is checking to see if the query's selected object is null but it should not be and there is not a null pointer exception along with it.

> var objone = (from att in _dbContext.ATTACHMENT
			  let mtr = (from g in _dbContext.ATTACHMENT
						 join a in _dbContext.A on g.ATTACHMENT_KEY equals a.ATTACHMENT_KEY
						 join m in _dbContext.S on a.SERIAL_CODE equals m.SerialCode
						 join n in _dbContext.M on m.SerialCode equals n.StationSerialCode
						 where g.ATTACHMENT_KEY == att.ATTACHMENT_KEY
						 select m
					  ).FirstOrDefault()
			  where att.ATTACHMENT_KEY == 56
			  select new { result = mtr }
			).ToList();

> var objtwo = (from att in _dbContext.ATTACHMENT
			  let mtr = (from g in _dbContext.ATTACHMENT
						 join a in _dbContext.A on g.ATTACHMENT_KEY equals a.ATTACHMENT_KEY
						 join m in _dbContext.S on a.SERIAL_CODE equals m.SerialCode
						 join n in _dbContext.M on m.SerialCode equals n.StationSerialCode
						 where g.ATTACHMENT_KEY == att.ATTACHMENT_KEY
						 select m
					  ).FirstOrDefault()
			  where att.ATTACHMENT_KEY == 56
			  select mtr
			   ).ToList();

> var error = (from att in _dbContext.ATTACHMENT
			  let mtr = (from g in _dbContext.ATTACHMENT
						 join a in _dbContext.A on g.ATTACHMENT_KEY equals a.ATTACHMENT_KEY
						 join m in _dbContext.S on a.SERIAL_CODE equals m.SerialCode
						 join n in _dbContext.M on m.SerialCode equals n.StationSerialCode
						 where g.ATTACHMENT_KEY == att.ATTACHMENT_KEY
						 select m
					  ).FirstOrDefault()
				where att.ATTACHMENT_KEY == 56
				select
					new
					{
						result= !Equals(mtr, null) ? mtr : new THING(),
					}
				 ).ToList();

**Comment by roji** [comment]
@dec123ac please open a new issue with a runnable, minimal repro - a query fragment such as what you posted above isn't sufficient, and it's likely your error is unrelated due to the lack of GroupBy.

**Comment by henriquewr** [comment]
For everyone hitting this issue or any issue related to GroupBy (at least in the cases that came to mind right now) I found a workaround:

`dbSet.GroupBy(x => x.GroupByKey)`

can be rewritten as

```
dbSet.Select(x => x.GroupByKey)
    .Distinct()
    .Select(x => new
    {
        Key = x,
        Group = dbSet.Where(d => d.GroupByKey == x).ToList()
    })
```

Example:

```
dbSet.GroupBy(x => x.Key)
    .Select(x => x.First())
    .Select(x => x.Something)
```

becomes

```
dbSet.Select(x => x.Key)
    .Distinct()
    .Select(x => 
        dbSet.Where(d => d.Key == x)
            .Select(d => d.Something)
            .First()
    )
```
