### ISSUE TITLE
Regression: EF Core attempts to insert explicit value for identity column

### ISSUE THREAD

**Issue by jamesgurung** [dotnet/efcore#31231]
When inserting an entity, the latest previews of EF Core 8 attempt to explicitly set the value of the identity column, and this fails with:

> **SqlException: Cannot insert explicit value for identity column in table 'Objectives' when IDENTITY_INSERT is set to OFF.**

I'm afraid I don't have a minimal repro, but the simplest example in my code is this entity:

```c#
public partial class Objective
{
  public int Id { get; set; }
  public string Title { get; set; } = null!;
  /* ... */
}
```

The `Id` column in the database is set as an auto-incrementing `IDENTITY(1,1)`.

I attempt to insert a new entity:

```c#
var obj = new Objective { ParentId = data.Parent, Title = data.Text.Trim(), SchoolId = schoolId };
Db.Objectives.Add(obj);
await Db.SaveChangesAsync();
```

In EF Core 8 Preview 4 (and previous versions), this works correctly.

However, in EF Core 8 Previews 5 and 6, it fails because the generated SQL tries to manually specify an `Id`.

```text
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (54ms) [Parameters=[@p0='0', @p1='False', @p2='9795' (Nullable = true), @p3='4270' (Nullable = true), @p4='New node' (Nullable = false) (Size = 255) (DbType = AnsiString)], CommandType='Text', CommandTimeout='30']
      SET IMPLICIT_TRANSACTIONS OFF;
      SET NOCOUNT ON;
      INSERT INTO [Objectives] ([Id], [IsHidden], [ParentId], [SchoolId], [Title])
      VALUES (@p0, @p1, @p2, @p3, @p4);
fail: Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type 'MyProject.Entities.Database'.
      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
       ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert explicit value for identity column in table 'Objectives' when IDENTITY_INSERT is set to OFF.
         at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__209_0(Task`1 result)
         at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
      ClientConnectionId:41b29c35-00b7-4d24-8a05-29d9ff24e01d
      Error Number:544,State:1,Class:16
         --- End of inner exception stack trace ---
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

EF Core version: 8.0.0-preview.6.23329.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8 Preview 6
Operating system: Windows 10
IDE: Visual Studio 2022 17.7 Preview 3

**Comment by roji** [comment]
@jamesgurung are you really unable to put together a small program to show this? If it's too complicated, I'm not sure how we would...

**Comment by jamesgurung** [comment]
@roji Fair enough, I just made a minimal repro and no issues... so it turns out the problem was using a compiled model.

I re-ran `dotnet ef dbcontext optimize` with the latest tool version, and it added a load of "sentinel" values to the generated code. This fixes the issue. Not sure if it counts as a breaking change, but it might be worth documenting in the release notes when EF Core 8 releases - just a reminder to regenerate compiled models in case people (like me!) don't realise.

**Comment by Kashif-datamagnetics** [comment]
@jamesgurung thank you, you saved my day
