### ISSUE TITLE
SQLite not supported on win-x64-coreclr

### ISSUE THREAD

**Issue by mfilippov** [dotnet/efcore#3128]
I try build example with EF7 and sqlite on coreclr all beta7. I got error:

```
dnx ef database update
Using context 'BloggingContext'.
Using database 'main' on server 'C:\Users\mfilippov\Projects\ImmutableEntityWithEf7\src\ImmutableEntityWithEf7/blog.db'.
System.DllNotFoundException: Unable to load DLL 'sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(IntPtr filename, Sqlite3Handle& ppDb, Int32 flags, IntPtr vfs)
   at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(String filename, Sqlite3Handle& ppDb, Int32 flags, String vfs)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.Data.Entity.Storage.RelationalConnection.Open()
   at Microsoft.Data.Entity.Sqlite.SqliteDatabaseConnection.Open()
   at Microsoft.Data.Entity.Storage.SqlStatementExecutor.Execute[T](IRelationalConnection connection, Func`1 action)
   at Microsoft.Data.Entity.Migrations.HistoryRepository.Exists()
   at Microsoft.Data.Entity.Migrations.HistoryRepository.GetAppliedMigrations()
   at Microsoft.Data.Entity.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.Data.Entity.Commands.MigrationTool.ApplyMigration(String migrationName, String contextTypeName, String startupAssemblyName)
   at Microsoft.Data.Entity.Commands.Program.Execute(String startupProject, Action invoke)
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineUtilsExtensions.<>c__DisplayClass0_0.<OnExecute>b__0()
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)
```

``` c#
using System;
using System.Collections.Generic;
using Microsoft.Data.Entity;
using Microsoft.Dnx.Runtime;
using Microsoft.Dnx.Runtime.Infrastructure;
using Microsoft.Framework.DependencyInjection;

namespace ImmutableEntityWithEf7
{
    public class Program
    {
        public void Main(string[] args)
        {
            using (var db = new BloggingContext())
            {
                db.Blogs.Add(new Blog { Url = "http://blogs.msdn.com/adonet" });
                var count = db.SaveChanges();
                Console.WriteLine("{0} records saved to database", count);

                Console.WriteLine();
                Console.WriteLine("All blogs in database:");
                foreach (var blog in db.Blogs)
                {
                    Console.WriteLine(" - {0}", blog.Url);
                }
            }
        }
    }
    public class BloggingContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Post> Posts { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var appEnv = CallContextServiceLocator.Locator.ServiceProvider
                            .GetRequiredService<IApplicationEnvironment>();
            optionsBuilder.UseSqlite($"Data Source={ appEnv.ApplicationBasePath }/blog.db");
        }
    }
    public class Post
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }

        public int BlogId { get; set; }
        public Blog Blog { get; set; }
    }
    public class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }
        public string Name { get; set; }

        public List<Post> Posts { get; set; }
    }

    public class Startup
    {
        public void Configure() { }
    }
}
```

``` json
{
    "version": "1.0.0-*",
    "description": "ImmutableEntityWithEf7 Console Application",
    "authors": [ "mfilippov" ],
    "tags": [ "" ],
    "projectUrl": "",
    "licenseUrl": "",

    "dependencies": {
    },

    "commands": {
        "run": "ImmutableEntityWithEf7",
        "ef": "EntityFramework.Commands"
    },

    "frameworks": {
        "dnxcore50": {
            "dependencies": {
                "EntityFramework.Sqlite": "7.0.0-beta7",
                "EntityFramework.Commands": "7.0.0-beta7",
                "Microsoft.Dnx.Runtime.Abstractions": "1.0.0-beta7",
                "Microsoft.CSharp": "4.0.1-beta-23225",
                "System.Collections": "4.0.11-beta-23225",
                "System.Console": "4.0.0-beta-23225",
                "System.Linq": "4.0.1-beta-23225",
                "System.Threading": "4.0.11-beta-23225"
            }
        }
    }
}
```

**Comment by natemcmaster** [comment]
What version of DNX?
Run ```dnx --version``` to check.

**Comment by mfilippov** [comment]
dnx --version
Microsoft .NET Execution environment
 Version:      1.0.0-beta7-15532
 Type:         CoreCLR
 Architecture: x64
 OS Name:      Windows
 OS Version:   6.2

**Comment by natemcmaster** [comment]
Microsoft.Data.Sqlite does not currently work on coreclr-x64. It should work on x86. 

```
dnvm install 1.0.0-beta7 -r coreclr -a x86 
dnvm use 1.0.0-beta7 -r coreclr -a x86
```

**Comment by natemcmaster** [comment]
See https://github.com/aspnet/Microsoft.Data.Sqlite/issues/31#issue-34793843.

**Comment by mfilippov** [comment]
Yes with x86 it works. I'll wait x64 in future.

**Comment by natemcmaster** [comment]
May be easy to fix. https://github.com/aspnet/Microsoft.Data.Sqlite/issues/138

**Comment by guidefreitas** [comment]
Similar problem here

Microsoft .NET Execution environment
 Version:      1.0.0-rc1-16609
 Type:         CoreClr
 Architecture: x64
 OS Name:      Linux
 OS Version:   7 debian
 Runtime Id:   ubuntu.14.04-x64


I tryed to install the x86 version without success
root@e369f14d116f:/app/src/DefesaCivil.Web# dnvm install -r coreclr -arch x86
Core CLR doesn't currently have a 32 bit build. You must use x64.
