### ISSUE TITLE
[Q]: Why? `InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.String'.`

### ISSUE THREAD

**Issue by glenn2223** [dotnet/efcore#31293]
Got to #21286 as they had the same issue line. However, although the navigable class does have an `Enum=>string converter`, I am just trying to return a single value with the same issue

# Ask a question
"What am I doing wrong" is basically my question (as it's usually me, not the package 😁)

I am trying to return a set of values into a record and kept getting the above error. I took it back to an overly simplified query and even returning just that one property has the same issue.

## Code

```C#
var test =
    await _context.Containers
        .OrderByDescending(x => x.Expected)
        .Select(x =>
            new 
            {
                x.SupplierId
            }
        )
        .ToListAsync();

// The proper code segment which first errored
Results = 
    await _context.Containers
        .OrderByDescending(x => x.Expected)
        .Select(x =>
            new MyContainerSummary(
                x.Id,
                x.Reference,
                x.Expected,
                x.SupplierId,
                x.Supplier == null
                    ? "UNKNOWN"
                    : x.Supplier.Name,
                x.ContainerProducts.Sum(x => x.Quantity)
            )
        )
        .ToListAsync();
```

**This is the output in the debug console**
```SQL
-- Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [c].[SupplierId]
FROM [Container] AS [c]
ORDER BY [c].[Expected] DESC
```

**Here is my table in SQL SMS**
![image](https://github.com/dotnet/efcore/assets/33450392/95c52f83-da13-4c18-a14c-3679d936250f)

**EF's migration class**
```c#
using System;
using System.Collections.Generic;
using MySite.Helpers.EntityFramework;
using Microsoft.EntityFrameworkCore;

namespace MySite.Models;

public partial class Container
{
    public int Id { get; set; }

    public string Reference { get; set; } = null!;

    public DateTime Expected { get; set; }

    public int? SupplierId { get; set; }

    public virtual ICollection<ContainerProduct> ContainerProducts { get; set; } = new List<ContainerProduct>();

    public virtual Supplier? Supplier { get; set; }
}

public class ContainerEntityBuilder : IEntityBuilder
{
    public void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Container>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Containe__3214EC07ECE9C9E3");

            entity.ToTable("Container");

            entity.Property(e => e.Id).HasColumnName("Id");
            entity.Property(e => e.SupplierId);
            //     .HasColumnName("SupplierId")
            //     .HasColumnType("int?");
            entity.Property(e => e.Expected).HasColumnType("date");
            entity.Property(e => e.Reference).HasMaxLength(50);

            entity.HasOne(d => d.Supplier).WithMany(p => p.Containers)
                .HasForeignKey(d => d.SupplierId)
                .HasPrincipalKey(c => c.Id)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK__Container__Suppl__1C3005F6");
        });
    }
}
```

## Stack traces
```
System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.String'.
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at lambda_method755(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at MySite.Areas.AdminnyBit.Pages.Orders.Suppliers.Forecasting.Containers.IndexModel.Init() in D:\Sites\MySite\Areas\AdminnyBit\Pages\Orders\Suppliers\Forecasting\Containers\Index.cshtml.cs:line 58
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.NonGenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at MyMiddleware.SessionStoreMiddleware.Invoke(HttpContext context) in D:\Sites\MySite\App_Code\Middleware\SessionStore.cs:line 27
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

## Debug console output

```
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [c].[SupplierId]
FROM [Container] AS [c]
ORDER BY [c].[Expected] DESC
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [c].[SupplierId]
      FROM [Container] AS [c]
      ORDER BY [c].[Expected] DESC
Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
Microsoft.EntityFrameworkCore.Query: Error: An exception occurred while iterating over the results of a query for context type 'MySite.Models.SiteContext'.
System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.String'.
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at lambda_method755(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.String'.
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at lambda_method755(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'MySite.Models.SiteContext'.
      System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.String'.
         at Microsoft.Data.SqlClient.SqlBuffer.get_String()
         at lambda_method755(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
      System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.String'.
         at Microsoft.Data.SqlClient.SqlBuffer.get_String()
         at lambda_method755(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
Exception thrown: 'System.InvalidCastException' in Microsoft.EntityFrameworkCore.Relational.dll
Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
```

## Provider and version information

EF Core version: 7.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: Windows Server 2019
IDE: VS Code

**Comment by ajcvickers** [comment]
@glenn2223 I am not able to reproduce this--see my code below. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

```C#
using (var context = new SomeDbContext())
{
    await context.Database.EnsureDeletedAsync();
    await context.Database.EnsureCreatedAsync();

    context.AddRange(
        new Container
        {
            ContainerProducts = { new(), new() },
            Expected = DateTime.Now,
            Reference = "ref",
            Supplier = new Supplier { Name = "X" }
        }, new Container
        {
            ContainerProducts = { new(), new() },
            Expected = DateTime.Now,
            Reference = "ref",
            Supplier = new Supplier { Name = "X" }
        });

    await context.SaveChangesAsync();
}

using (var context = new SomeDbContext())
{
    var test =
        await context.Containers
            .OrderByDescending(x => x.Expected)
            .Select(x =>
                new
                {
                    x.SupplierId
                }
            )
            .ToListAsync();


    // The proper code segment which first errored
    var results = await context.Containers
            .OrderByDescending(x => x.Expected)
            .Select(x =>
                new MyContainerSummary(
                    x.Id,
                    x.Reference,
                    x.Expected,
                    x.SupplierId,
                    x.Supplier == null
                        ? "UNKNOWN"
                        : x.Supplier.Name,
                    x.ContainerProducts.Sum(x => x.Quantity)
                )
            )
            .ToListAsync();
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Data Source=(LocalDb)\MSSQLLocalDB;Database=AllTogetherNow")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    public DbSet<Container> Containers => Set<Container>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Container>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Containe__3214EC07ECE9C9E3");

            entity.ToTable("Container");

            entity.Property(e => e.Id).HasColumnName("Id");
            entity.Property(e => e.SupplierId);
            //     .HasColumnName("SupplierId")
            //     .HasColumnType("int?");
            entity.Property(e => e.Expected).HasColumnType("date");
            entity.Property(e => e.Reference).HasMaxLength(50);

            entity.HasOne(d => d.Supplier).WithMany(p => p.Containers)
                .HasForeignKey(d => d.SupplierId)
                .HasPrincipalKey(c => c.Id)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK__Container__Suppl__1C3005F6");
        });    }
}

public partial class Container
{
    public int Id { get; set; }

    public string Reference { get; set; } = null!;

    public DateTime Expected { get; set; }

    public int? SupplierId { get; set; }

    public virtual ICollection<ContainerProduct> ContainerProducts { get; set; } = new List<ContainerProduct>();

    public virtual Supplier? Supplier { get; set; }
}

public class Supplier
{
    public int Id { get; set; }

    public virtual ICollection<Container> Containers { get; set; } = new List<Container>();
    public string Name { get; set; }
}

public class ContainerProduct
{
    public int Id { get; set; }
    public int Quantity { get; set; }
}

public class MyContainerSummary
{
    public MyContainerSummary(int xId, string xReference, DateTime xExpected, int? xSupplierId, string unknown, int sum)
    {
    }
}
```

**Comment by glenn2223** [comment]
Thanks for taking the time to look at this for me @ajcvickers 

Below is a very small repo. I added a file to create the SQL tables (sorry for the bloat - old columns and whatnot) and also included a JSON file to show you the connection string I'm using (with the credentials changed)

[EFCore-Test.zip](https://github.com/dotnet/efcore/files/12098249/EFCore-Test.zip)

Removing the `Supplier` (and its builder) from the context has a successful run but why is it trying to convert an `int` to a `string`, even when I only want to return this single `SupplierId`  property - and with nothing in the logs to say it's querying that table?

**Comment by ajcvickers** [comment]
@glenn2223 In the Suppliers table, the `sID` column is an integer:

```sql
CREATE TABLE [dbo].[Suppliers](
	[sID] [int] IDENTITY(1,1) NOT NULL,
```

But in your EF configuration, the column is configured as a string:

```C#
entity.Property(e => e.Id).HasColumnName("sID").HasConversion<string>();
```

**Comment by glenn2223** [comment]
ARGH! FFS, how did I miss that?! Thanks for your help, I've been racking my brain. I'd switched another property to have an `enum=>string` conversion and must have got that one tied up in it too somehow.

Thanks again and sorry for wasting your time 🤦‍♂️😍
