### ISSUE TITLE
`System.InvalidOperationException` thrown when adding a `ISingletonInterceptor`

### ISSUE THREAD

**Issue by codelovercc** [dotnet/efcore#31311]
## Question

`System.InvalidOperationException` thrown when adding a `ISingletonInterceptor`, use `AddDbContextPool` extension method.

### Code

```C#
services.AddEntityFrameworkSqlite();
services.TryAddSingleton<ISettingValueCrypter>(provider => 
     new EnvironmentSettingValueCrypter(key: "123123123", iv: "123123123"));
// MyDbContext is the DbContext, and it does not override the OnConfiguration method
services.AddDbContextPool<MyDbContext>((serviceProvider, optionsBuilder) =>
{
    
    var connection = serviceProvider.GetRequiredService<DbConnection>();

    var crypter = serviceProvider.GetRequiredService<ISettingValueCrypter>();
    // SettingSaveChangesInterceptor is a SaveChangesInterceptor and it works well
    // SettingMaterializationInterceptor is a IMaterializationInterceptor 
    // System.InvalidOperationException thrown when adding SettingMaterializationInterceptor 
    optionsBuilder.AddInterceptors(new SettingSaveChangesInterceptor(crypter),
        new SettingMaterializationInterceptor(crypter));

    optionsBuilder.UseInternalServiceProvider(serviceProvider);
    optionsBuilder.EnableSensitiveDataLogging();
    optionsBuilder.UseSqlite(connection);
}, poolSize: 1024);

public class SettingMaterializationInterceptor : IMaterializationInterceptor
{
    private readonly ISettingValueCrypter _crypter;

    public SettingMaterializationInterceptor(ISettingValueCrypter crypter)
    {
        _crypter = crypter;
    }

    public object InitializedInstance(MaterializationInterceptionData materializationData, object entity)
    {
        if (entity is not Setting { Encrypted: true } setting)
        {
            return entity;
        }

        _crypter.Decrypt(setting);

        var entries = materializationData.Context.ChangeTracker.Entries<Setting>().ToList();
        foreach (var entry in entries)
        {
            var prop = entry.Property(s => s.Value);
            prop.CurrentValue = setting.Value;
            prop.OriginalValue = setting.Value;
            // Set modified status and detect the changes
            prop.IsModified = false;
        }

        return setting;
    }
}

```

### Stack traces

```C#

System.InvalidOperationException: A call was made to 'AddInterceptors', but Entity Framework is not building its own internal service provider. Either allow Entity Framework to build the service provider by removing the call to 'UseInternalServiceProvider', or build the 'ISingletonInterceptor' services to use into the service provider before passing it to 'UseInternalServiceProvider'.
   at Microsoft.EntityFrameworkCore.Infrastructure.CoreOptionsExtension.Validate(IDbContextOptions options)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.ValidateOptions(IDbContextOptions options)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityUserContext`5..ctor(DbContextOptions options)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityDbContext`8..ctor(DbContextOptions options)


```

### What I tried

Change the services.AddDbContextPool<MyDbContext> call, add the SettingMaterializationInterceptor to the DI, but it's still not working.

```C#
services.AddEntityFrameworkSqlite();
services.TryAddSingleton<ISettingValueCrypter>(provider => 
     new EnvironmentSettingValueCrypter(key: "123123123", iv: "123123123"));
// Add it to the DI 
services.AddSingleton<IMaterializationInterceptor, SettingMaterializationInterceptor>();
// Or
// services.AddSingleton<SettingMaterializationInterceptor>();
services.AddDbContextPool<MyDbContext>((serviceProvider, optionsBuilder) =>
{
    var connection = serviceProvider.GetRequiredService<DbConnection>();
    var crypter = serviceProvider.GetRequiredService<ISettingValueCrypter>();
    optionsBuilder.AddInterceptors(new SettingSaveChangesInterceptor(crypter),
        serviceProvider.GetRequiredService<IMaterializationInterceptor>()
        // Or 
        // ,serviceProvider.GetRequiredService<SettingMaterializationInterceptor>()
    );

    optionsBuilder.UseInternalServiceProvider(serviceProvider);
    optionsBuilder.EnableSensitiveDataLogging();
    optionsBuilder.UseSqlite(connection);
}, poolSize: 1024);


```

### Include provider and version information

EF Core version: 7.0.5
Database provider:  Microsoft.EntityFrameworkCore.Sqlite
Target framework: .Net 7.0
Operating system: macOs Big Sur 11.7.7
IDE: JetBrains Rider 2023.1.3

**Comment by ajcvickers** [comment]
@codelovercc Yes--you can configure the singleton interceptor service in the internal service provider. That's what you take on when you manage the internal service provider.

Which services are you replacing?

**Comment by codelovercc** [comment]
> Yes--you can configure the singleton interceptor service in the internal service provider. That's what you take on when you manage the internal service provider.

I don't know how to do it. 

I added it to the service provider. but it's not work. What is going wrong? Have I missed something?

```C#
services.AddEntityFrameworkSqlite();
services.TryAddSingleton<ISettingValueCrypter>(provider => 
     new EnvironmentSettingValueCrypter(key: "123123123", iv: "123123123"));
// Add it to the DI 
services.AddSingleton<IMaterializationInterceptor, SettingMaterializationInterceptor>();
// Or
// services.AddSingleton<SettingMaterializationInterceptor>();
services.AddDbContextPool<MyDbContext>((serviceProvider, optionsBuilder) =>
{
    var connection = serviceProvider.GetRequiredService<DbConnection>();
    var crypter = serviceProvider.GetRequiredService<ISettingValueCrypter>();
    optionsBuilder.AddInterceptors(new SettingSaveChangesInterceptor(crypter),
        serviceProvider.GetRequiredService<IMaterializationInterceptor>()
        // Or 
        // ,serviceProvider.GetRequiredService<SettingMaterializationInterceptor>()
    );

    optionsBuilder.UseInternalServiceProvider(serviceProvider);
    optionsBuilder.EnableSensitiveDataLogging();
    optionsBuilder.UseSqlite(connection);
}, poolSize: 1024);

```

> Which services are you replacing?

I not sure for now, I'll check the code and find out which services are replaced.
