### ISSUE TITLE
Could not load type 'System.Runtime.CompilerServices.NullableContextAttribute'

### ISSUE THREAD

**Issue by fedor700** [dotnet/efcore#31427]
Seems like a .NET issue, but it's affecting Entity Framework Core.

### Code

```C#
using Microsoft.EntityFrameworkCore;

namespace Test
{
    public class MyContext : DbContext { }

    class Program
    {
        static void Main(string[] args)
        {
            new MyContext(); // exception
        }
    }
}

```

### Stack trace
```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Microsoft.Extensions.DependencyInjection.DependencyInjectionEventSource' threw an exception.
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<GetOrAdd>g__BuildServiceProvider|4_1(IDbContextOptions _, ValueTuple`2 arguments)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c.<GetOrAdd>b__4_0(IDbContextOptions contextOptions, ValueTuple`2 tuples)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at Microsoft.EntityFrameworkCore.DbContext..ctor()
   at Test.MyContext..ctor()
   at Test.Program.Main(String[] args) in D:\*\Program.cs:line 11

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
TypeLoadException: Could not load type 'System.Runtime.CompilerServices.NullableContextAttribute' from assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

### Provider and version information
EF Core version:  8.0.0-preview.7.23375.4
Target framework: .NET 8.0
Operating system: Windows 10
IDE: Visual Studio 17.7.0 Preview 6.0

**Comment by fedor700** [comment]
Oh I think it's because I'm using .NET SDK 8.0.100-preview.6.23330.14 (preview 7 is not public yet)
