### ISSUE TITLE
Problem assigning a role to a user (Oracle 11 database)

### ISSUE THREAD

**Issue by ekremsaydam** [dotnet/efcore#31432]
![image](https://github.com/dotnet/efcore/assets/30255407/c10cbe78-3494-4d18-b779-b6a7719991a3)

![image](https://github.com/dotnet/efcore/assets/30255407/c70f330c-6c58-4d46-9fc6-a5efb9bd5a6d)
```
services.AddDbContext<AppDbContext>(options =>
	options.UseOracle(configuration.GetConnectionString("Oracle"), oracleoptions =>
	{
		oracleoptions.MigrationsAssembly("AspNetCoreIdentity.Repository");
		// select banner from v$version where rownum = 1
		oracleoptions.UseOracleSQLCompatibility("11");
	}));
```

![image](https://github.com/dotnet/efcore/assets/30255407/2e498eca-d5d3-4823-b797-5b0d73df4db1)

```
public class AppDbContext : IdentityDbContext<AppUser, AppRole, string>
{
	public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		// Oracle connect error: ORA - 00972: identifier is too long
		//modelBuilder.Model.SetMaxIdentifierLength(30);

		// The entity type 'IdentityUserLogin<string>' requires a primary key to be defined.
		// If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'
		modelBuilder.Entity<IdentityUserLogin<string>>().HasNoKey();

		// The entity type 'IdentityUserRole<string>' requires a primary key to be defined.
		// If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'
		modelBuilder.Entity<IdentityUserRole<string>>().HasNoKey();

		// The entity type 'IdentityUserToken<string>' requires a primary key to be defined.
		// If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'
		modelBuilder.Entity<IdentityUserToken<string>>().HasNoKey();
	}
}
```

![image](https://github.com/dotnet/efcore/assets/30255407/060c5734-49d4-4f83-9804-69f1c89cdce4)

```
using (var scope = app.Services.CreateScope())
{
    var roleManager = scope.ServiceProvider.GetRequiredService<RoleManager<AppRole>>();
    await PermisionSeed.Seed(roleManager);

    var signManager = scope.ServiceProvider.GetRequiredService<SignInManager<AppUser>>();
    var userManager = scope.ServiceProvider.GetRequiredService<UserManager<AppUser>>();
    await AdminSeed.Seed(signManager, userManager, roleManager);
}
```

![image](https://github.com/dotnet/efcore/assets/30255407/409177ec-0888-4198-b6c0-624dc826273a)
```
public static class AdminSeed
{
	public static async Task Seed(SignInManager<AppUser> signInManager, 
		UserManager<AppUser> userManager, 
		RoleManager<AppRole> roleManager)
	{
		var hasAdminUser = await signInManager.PasswordSignInAsync("admin", "P@ssw0rd1", true, false);

		if (!hasAdminUser.Succeeded)
		{
			var adminUser = new AppUser { UserName = "admin", Email = "admin@localhost" };
			await userManager.CreateAsync(adminUser, "P@ssw0rd1");

			var roleAdmin = await roleManager.FindByNameAsync("Admin");


			if (roleAdmin != null)
			{
				await signInManager.UserManager.AddToRoleAsync(adminUser, roleAdmin!.Name!);
			}
		}
	}
}
```
![image](https://github.com/dotnet/efcore/assets/30255407/bef80da4-3408-43a3-acdf-3f60a61acea4)
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.ValidateKeyPropertiesAndExtractCancellationToken(Object[] keyValues, Boolean async, CancellationToken cancellationToken) in /_/src/EFCore/Internal/EntityFinder.cs:line 280
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.FindAsync(Object[] keyValues, CancellationToken cancellationToken) in /_/src/EFCore/Internal/EntityFinder.cs:line 85
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.FindAsync(Object[] keyValues, CancellationToken cancellationToken) in /_/src/EFCore/Internal/InternalDbSet.cs:line 179
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.FindUserRoleAsync(TKey userId, TKey roleId, CancellationToken cancellationToken) in /_/src/Identity/EntityFrameworkCore/src/UserStore.cs:line 283
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.<IsInRoleAsync>d__37.MoveNext() in /_/src/Identity/EntityFrameworkCore/src/UserStore.cs:line 424
   at Microsoft.AspNetCore.Identity.UserManager`1.<AddToRoleAsync>d__105.MoveNext() in /_/src/Identity/Extensions.Core/src/UserManager.cs:line 1219

  This exception was originally thrown at this call stack:
    Microsoft.EntityFrameworkCore.Internal.EntityFinder<TEntity>.ValidateKeyPropertiesAndExtractCancellationToken(object[], bool, System.Threading.CancellationToken) in EntityFinder.cs
    Microsoft.EntityFrameworkCore.Internal.EntityFinder<TEntity>.FindAsync(object[], System.Threading.CancellationToken) in EntityFinder.cs
    Microsoft.EntityFrameworkCore.Internal.InternalDbSet<TEntity>.FindAsync(object[], System.Threading.CancellationToken) in InternalDbSet.cs
    Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore<TUser, TRole, TContext, TKey, TUserClaim, TUserRole, TUserLogin, TUserToken, TRoleClaim>.FindUserRoleAsync(TKey, TKey, System.Threading.CancellationToken) in UserStore.cs
    Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore<TUser, TRole, TContext, TKey, TUserClaim, TUserRole, TUserLogin, TUserToken, TRoleClaim>.IsInRoleAsync(TUser, string, System.Threading.CancellationToken) in UserStore.cs
    Microsoft.AspNetCore.Identity.UserManager<TUser>.AddToRoleAsync(TUser, string) in UserManager.cs
```
![image](https://github.com/dotnet/efcore/assets/30255407/8af068f0-773c-4775-85b3-32de3820fc1d)

For a solution, this situation can be solved with a function that can assign roles via roleid and userid.

Thank you for the EF Core platform you provide for us developers.

**Comment by ekremsaydam** [comment]
![image](https://github.com/dotnet/efcore/assets/30255407/7913fd2c-d1e6-4343-9e62-5399a7547f6a)

base.OnModelCreating(modelBuilder);

code change as above is the solution to the problem.
