### ISSUE TITLE
EF Core 7.0.10 - 'Invalid Object Name' error when using DbFunction

### ISSUE THREAD

**Issue by marqdouj-spartan** [dotnet/efcore#31456]
## File a bug

SQL Server 2016

I have defined a table function named [portal].[GetUserAtlasMenu]

I can run this TSQL without error in SSMS:

SELECT *
FROM [portal].[GetUserAtlasMenu]('USER') AS [g]
ORDER BY [g].[MENUORDER]

The function is defined in my DbContext (generated by EF Core Power Tools):

```C#
    public partial class AtlasContext
    {

        [DbFunction("GetUserAtlasMenu", "portal")]
        public IQueryable<GetUserAtlasMenuResult> GetUserAtlasMenu(string logon)
        {
            return FromExpression(() => GetUserAtlasMenu(logon));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GetUserAtlasMenuResult>().HasNoKey();
        }
    }
```

I try to load the results like this:

```C#
var menus = await db.GetUserAtlasMenu(logonId).OrderBy(e => e.MENUORDER).ToListAsync();
```
### Include stack traces

NOTE: I can copy and paste the SQL from the log below into SSMS and it runs without error.

```
2023-08-12 12:48:59.629 -06:00 [6] [ERR] Failed executing DbCommand (71ms) [Parameters=[@__logon_1='DAR' (Size = 4000)], CommandType='"Text"', CommandTimeout='30']
SELECT [g].[APP], [g].[CHILDMENU], [g].[LOGON], [g].[MENUORDER], [g].[MENU_ID], [g].[NAME], [g].[NETURI], [g].[PARENTMENU], [g].[URL]
FROM [portal].[GetUserAtlasMenu](@__logon_1) AS [g]
ORDER BY [g].[MENUORDER]
2023-08-12 12:48:59.657 -06:00 [6] [ERR] An exception occurred while iterating over the results of a query for context type 'AtlasPortal.Web.Data.Models.AtlasContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'portal.GetUserAtlasMenu'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__208_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:3597bb4a-8266-4fe0-9a8a-60d069389b3b
Error Number:208,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'portal.GetUserAtlasMenu'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__208_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:3597bb4a-8266-4fe0-9a8a-60d069389b3b
Error Number:208,State:1,Class:16

```
### Include provider and version information

EF Core version: 7.0.10
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 8.0
Operating system: Windows 11
IDE: VS 2022 Enterprise Version 17.8.0 Preview 1.0

**Comment by marqdouj-spartan** [comment]
Doh!

My bad; didn't set the Catalog in the connection string.
