### ISSUE TITLE
Error when executing efbundle on Bitbucket Pipelines - System.IO.DirectoryNotFoundException: /opt/atlassian/pipelines/agent/build/Migrations/

### ISSUE THREAD

**Issue by nauticalcoder** [dotnet/efcore#31466]
## File a bug

Remember:
We are running `efbundle` in our Bitbucket Pipelines build and deployment.  When executing the bundle created in an earlier step (and stored as an artifact), we get the following error:
_System.IO.DirectoryNotFoundException: /opt/atlassian/pipelines/agent/build/Migrations/_
We have the exact same code running in a different project and it is successfully executing the migrations using `efbundle` with no issue so this leads me to believe it isn' strictly an issue with Pipelines.

### Include your code

Create bundle:
```
   - step:
              name: Build Database Migrations Bundle
              caches:
                - dotnetcore
              script:
                - dotnet tool restore
                - mkdir -p $BITBUCKET_CLONE_DIR/artifacts
                - cd src/XXX.Domain
                - dotnet ef migrations bundle --context AppDbContext --output $BITBUCKET_CLONE_DIR/artifacts/efbundle --self-contained --verbose
              artifacts:
                - artifacts/efbundle 
```
Execute bundle:
```
    - step:
                name: Apply Database Migrations
                caches:
                  - dotnetcore
                script:
                  - ./artifacts/efbundle --connection "$AZURE_DB_CONNECTION_STRING_INTEGRATION" -v
```

### Include stack traces

```
+ ./artifacts/efbundle --connection "$AZURE_DB_CONNECTION_STRING_INTEGRATION"
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.DirectoryNotFoundException: /opt/atlassian/pipelines/agent/build/Migrations/
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.Extensions.Configuration.FileConfigurationExtensions.SetBasePath(IConfigurationBuilder builder, String basePath)
   at XXX.Domain.Features.Configuration.AppConfiguration.ConfigureBuilder(IConfigurationBuilder configurationBuilder, AppConfigurationOptions options)
   at XXX.Domain.Features.Configuration.AppConfiguration.Build(AppConfigurationOptions options)
   at XXX.Domain.Migrations.MigrationsDbContextFactory.CreateDbContext(String[] args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContextFromFactory(Type factory, Type contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass21_2.<FindContextTypes>b__9()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsBundle.ExecuteInternal(String[] args)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsBundle.<>c__DisplayClass6_0.<Configure>b__0(String[] args)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsBundle.Execute(String context, Assembly assembly, Assembly startupAssembly, String[] args)
Exception has been thrown by the target of an invocation.
```

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET 7 (EFCore 7.0.5)

**Comment by nauticalcoder** [comment]
It turns out there was some custom code in our `MigrationsDbContextFactory` that was inherited from another project that changed the base path to something that looked like this:
``` BasePath = Path.Combine(Directory.GetCurrentDirectory(), "Migrations"),```
and this was interfering with the `efbundle` command.
