### ISSUE TITLE
Specifying enum typed discriminator on an entity type results in opaque ArgumentExceptions at query time

### ISSUE THREAD

**Issue by ZTonks** [dotnet/efcore#31547]
## File a bug

[x] Please check that the documentation does not explain the behavior you are seeing.
[x] Please search in both open and closed issues to check that your bug has not already been filed.

### Description

When specifying a discriminator on an enum typed value for a model, a fairly opaque `ArgumentException` is thrown at runtime when querying the `DbSet` referencing the model. This was found using the CosmosDb provider.

The exception is resolved if removing the discriminator or specifying a string typed discriminator.

I believe the bottom of the stack trace is [in this class](https://github.com/dotnet/efcore/blob/cf9391b184ffa61593e3253e7fc364e4ffa5f316/src/EFCore.Relational/Query/RelationalStructuralTypeShaperExpression.cs#L79C17-L79C110) but cannot be more specific without codemaps. `typeof(string)` is used fairly liberally throughout within the `Constant`s which leads me to believe only string typed discriminators are supported.

Should targeting an enum type with an enum type discriminator be supported?

If it shouldn't be supported (at least with the Cosmos provider):
1. Could we exclude enum types from being targeted as discriminator at compile time?
2. If this isn't possible, could we throw a less opaque runtime error?
3. Could this be done at model building time rather than at query time?

### Include your code

Minimal non working example follows:

```C#
// MyAppContext.cs
public class MyAppContext : DbContext
{
   public MyAppContext(
      DbContextOptions<MyAppContext> dbContextOptions)
         : base(dbContextOptions)
   {
   }

   public virtual DbSet<Model> MyModels => Set<Model>();

   protected override void OnModelCreating(ModelBuilder modelBuilder)
   {
      modelBuilder.Entity<Model>()
            .ToContainer(nameof(Model))
            .HasDiscriminator(m => m.MyEnum); // Apparently wrong

      base.OnModelCreating(modelBuilder);
   }
}

// MyEnum.cs
public enum MyEnum
{
   Foo,
   Bar,
}

// Model.cs
public class Model
{
   public string Id { get; set; } = string.Empty;

   public MyEnum MyEnum { get; set; } // I am chosen as the EF discriminator
}

// Program.cs
var services = Host.CreateDefaultBuilder(args)
    .ConfigureServices(o =>
        o.AddDbContext<MyAppContext>(j => j.UseCosmos(
            "https://localhost:8081",
            { accountkey },
            "MyTest"),
        ServiceLifetime.Singleton))
    .Build()
    .Services;

var appContext = services.GetRequiredService<MyAppContext>();

await appContext.Database.EnsureCreatedAsync();

var model = new Model
{
    Id = Guid.NewGuid().ToString(),
    MyEnum = MyEnum.Foo,
};

appContext.MyModels.Add(model);

await appContext.SaveChangesAsync();

var myModels = await appContext.MyModels.ToListAsync(); // Throws

```

### Include stack traces

```
System.ArgumentException: 'Argument types do not match'
   at System.Linq.Expressions.Expression.Constant(Object value, Type type)
   at Microsoft.EntityFrameworkCore.Query.EntityShaperExpression.GenerateMaterializationCondition(IEntityType entityType, Boolean nullable)
   at Microsoft.EntityFrameworkCore.Query.EntityShaperExpression..ctor(IEntityType entityType, Expression valueBufferExpression, Boolean nullable, LambdaExpression materializationCondition)
   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosQueryableMethodTranslatingExpressionVisitor.CreateShapedQueryExpression(IEntityType entityType, Expression queryExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosQueryableMethodTranslatingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Collections.Generic.IAsyncEnumerable<TEntity>.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__65`1.MoveNext()
   at Program.<<Main>$>d__0.MoveNext() in C:\Projects\ef-bug-mwe\Program.cs:line 30
```

### Include provider and version information

EF Core version: 6.0.21
Database provider: Microsoft.EntityFrameworkCore.Cosmos
Target framework: .NET 6.0
Operating system: Windows
IDE: Visual Studio 2022 17.4

**Comment by ajcvickers** [comment]
Note for triage: still repros on latest daily build.

```C#
var appContext = new MyAppContext();

await appContext.Database.EnsureCreatedAsync();

var model = new Model
{
    Id = Guid.NewGuid().ToString(),
    MyEnum = MyEnum.Foo,
};

appContext.MyModels.Add(model);

await appContext.SaveChangesAsync();

var myModels = await appContext.MyModels.ToListAsync(); // Throws

public class MyAppContext : DbContext
{
    public virtual DbSet<Model> MyModels => Set<Model>();

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseCosmos(
                     "https://localhost:8081",
                     "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==",
                     "AT3")
             .LogTo(Console.WriteLine, LogLevel.Information)
             .EnableSensitiveDataLogging();
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Model>()
            .ToContainer(nameof(Model))
            .HasDiscriminator(m => m.MyEnum); // Apparently wrong
    }
}

public enum MyEnum
{
    Foo,
    Bar,
}

public class Model
{
    public string Id { get; set; } = string.Empty;

    public MyEnum MyEnum { get; set; } // I am chosen as the EF discriminator
}
```

**Comment by AndriySvyryd** [comment]
The issue here is that the discriminator value is not specified. Should be:
```C#
        modelBuilder.Entity<Model>()
            .ToContainer(nameof(Model))
            .HasDiscriminator(m => m.MyEnum)
            .HasValue(MyEnum.Foo);
```
