### ISSUE TITLE
"Operation is not valid due to the current state of the object." when published the code

### ISSUE THREAD

**Issue by jwu-dharmo** [dotnet/efcore#31553]
**Background:**
The code attached worked with EF 6.X **and** locally with Visual Studio 2022
The problem only occurs from the published code running on the server.

```C#
PortalUserAccessView result =
       context.PortalUserAccess
               .AsNoTracking()
               .SingleOrDefault(row => row.Login.ToLower() == userLogin.ToLower() 
                                    && row.AppName.ToLower() == appName.ToLower()
                                    && row.AppKey == appKey
                                );
```

### Include stack traces

```
System.TypeInitializationException: The type initializer for 'Oracle.EntityFrameworkCore.Query.Internal.OracleMathTranslator' threw an exception.
 ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at System.SharedTypeExtensions.GetRequiredRuntimeMethod(Type type, String name, Type[] parameters)
   at Oracle.EntityFrameworkCore.Query.Internal.OracleMathTranslator..cctor()
   --- End of inner exception stack trace ---
   at Oracle.EntityFrameworkCore.Query.Internal.OracleMathTranslator.Translate(SqlExpression instance, MethodInfo method, IReadOnlyList`1 arguments, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Query.RelationalMethodCallTranslatorProvider.<>c__DisplayClass7_0.<Translate>b__0(IMethodCallTranslator t)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.EntityFrameworkCore.Query.RelationalMethodCallTranslatorProvider.Translate(IModel model, SqlExpression instance, MethodInfo method, IReadOnlyList`1 arguments, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at Oracle.EntityFrameworkCore.Query.Internal.OracleSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at Oracle.EntityFrameworkCore.Query.Internal.OracleSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at Oracle.EntityFrameworkCore.Query.Internal.OracleSqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TranslateInternal(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateExpression(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateLambdaExpression(ShapedQueryExpression shapedQueryExpression, LambdaExpression lambdaExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateWhere(ShapedQueryExpression source, LambdaExpression predicate)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at com.corning.canton.sharedresourceef.data.DataProvider.IsUserInApp(String appKey, String appName, String userLogin) in C:\Users\WuJ22\source\Workspaces\C5CG2133PXF\gRPC\Shared\SharedResourceEF\data\DataProvider-Security.cs:line 377
   at com.corning.canton.sharedresourceef.data.DataProvider.AuthorizeUser(String appKey, String appName, String userLogin) in C:\Users\WuJ22\source\Workspaces\C5CG2133PXF\gRPC\Shared\SharedResourceEF\data\DataProvider-Security.cs:line 153
   at com.corning.canton.sharedgrpc.services.util.AuthorizationHandler.AuthorizeUser(String appKey, String appName, String userLogin) in C:\Users\WuJ22\source\Workspaces\C5CG2133PXF\gRPC\Shared\Shared\SharedGrpc\services\util\AuthorizationHandler.cs:line 109
   at com.corning.canton.sharedgrpc.services.AuthGrpcService.AuthorizeUser(AuthorizeUserRequest request, ServerCallContext context) in C:\Users\WuJ22\source\Workspaces\C5CG2133PXF\gRPC\Shared\Shared\SharedGrpc\services\AuthGrpcService.cs:line 72
   at Grpc.Shared.Server.UnaryServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest, ServerCallContext)
   at Grpc.Shared.Server.UnaryServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest, ServerCallContext)
   at com.corning.canton.sharedgrpc.services.grpc.GrpcInterceptor.UnaryServerHandler[TRequest,TResponse](TRequest request, ServerCallContext context, UnaryServerMethod`2 continuation) in C:\Users\WuJ22\source\Workspaces\C5CG2133PXF\gRPC\Shared\Shared\SharedGrpc\services\grpc\GrpcInterceptor.cs:line 75
   at Grpc.Shared.Server.InterceptorPipelineBuilder`2.<>c__DisplayClass5_0.<<UnaryPipeline>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Grpc.Shared.Server.InterceptorPipelineBuilder`2.<>c__DisplayClass5_0.<<UnaryPipeline>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext, HttpContextServerCallContext)
   at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext, Method`2, Task)
```

### Include provider and version information

EF Core version: 7.0.10
Oracle.EntityFrameworkCore: (7.21.11)
Database provider: Oracle 11g (ODAC)
Target framework: .NET 7.0
Operating system: Windows (2016)
IDE: Visual Studio 2022 17.6.5

**Comment by roji** [comment]
@jwu-dharmo this looks like a bug in the Oracle provider, please report it to its maintainers (the Oracle provider isn't part of this repo).
