### ISSUE TITLE
Generated SQL has syntax issue when doing GroupJoin with Union constructed and ordered query

### ISSUE THREAD

**Issue by ArMeN-git** [dotnet/efcore#31580]
Issue happens when joining 2 queries with GroupJoin on IQueryable, in case of one query is ordered and has unions in it.

Example:
```C#
var clientsQuery = _unitOfWork.Set<Client>().Where(c => c.ClientAgents.Any(ac => ac.AgentUserId == _userId));
var firstQuery = _unitOfWork.Set<HomeTour>()
                .Where(c => c.Type == HomeTourType.InPersonTour)
                .Select(c => new ListingAction
                {
                    UserId = c.Client.UserId,
                    Action = ClientListingAction.AddedHomeTour,
                    CreateDate = c.CreateDate
                });
var secondQuery = _unitOfWork.Set<UserView>()
                .Select(c => new ListingAction
                {
                    UserId = c.UserId,
                    Action = ClientListingAction.Viewed,
                    CreateDate = c.CreateDate
                });
var unionedQuery = firstQuery.Union(secondQuery);
var orderedQuery = unionedQuery.OrderByDescending(c => c.CreateDate);
var joinedQuery = clientsQuery.GroupJoin(orderedQuery, c => c.UserId, la => la.UserId, (c, la) => new { Client = c, Actions = la })
                                  .SelectMany(a => a.Actions.DefaultIfEmpty(), (a, la) => new
                                  {
                                      a.Client.UserId,
                                      a.Client.Type,
                                      Weight = 1 // just other value, doesn't matter
                                  });
```
Generated SQL (with incorrect syntax):
```sql
DECLARE @___userId_0 int = 1081685;

SELECT [c].[UserId], [c].[Type], 1 AS [Weight]
FROM [Clients] AS [c]
LEFT JOIN SELECT [t].[UserId], 5 AS [Action], [h].[CreateDate]
FROM [HomeTours] AS [h]
INNER JOIN (
    SELECT [c0].[Id], [c0].[CreateDate], [c0].[DeletionDate], [c0].[InvitationData], [c0].[IsActive], [c0].[IsDeleted], [c0].[Notes], [c0].[Type], [c0].[UserId]
    FROM [Clients] AS [c0]
    WHERE [c0].[IsDeleted] = CAST(0 AS bit)
) AS [t] ON [h].[ClientId] = [t].[Id]
WHERE ([t].[IsDeleted] = CAST(0 AS bit)) AND ([h].[Type] = 1)
UNION
SELECT [u].[UserId], 2 AS [Action], [u].[CreateDate]
FROM [UserViews] AS [u] ON [c].[UserId] = [t1].[UserId]
WHERE ([c].[IsDeleted] = CAST(0 AS bit)) AND EXISTS (
    SELECT 1
    FROM [AgentClients] AS [a]
    WHERE ([c].[Id] = [a].[ClientId]) AND ([a].[AgentUserId] = @___userId_0))
```

Executing query:
```C#
var result = await joinedQuery.ToListAsync(cancellationToken);
```

SqlException:
```
Microsoft.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near the keyword 'SELECT'.
Incorrect syntax near the keyword 'ON'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__209_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at MC.ApplicationCore.Clients.ClientManager.FilterAsync(ClientFilter filter, CancellationToken cancellationToken) in C:\Users\Armen\Desktop\Purlin\mission-control-server\src\MC.ApplicationCore\Clients\ClientManager.cs:line 74
   at MC.API.Controllers.v1.ClientsController.Get(ClientFilter filter, CancellationToken cancellationToken) in C:\Users\Armen\Desktop\Purlin\mission-control-server\src\MC.API\Controllers\v1\ClientsController.cs:line 134
   at lambda_method44(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at MC.API.Middleware.ExceptionHandlerMiddleware.Invoke(HttpContext context) in C:\Users\Armen\Desktop\Purlin\mission-control-server\src\MC.API\Middleware\ExceptionHandlerMiddleware.cs:line 38
ClientConnectionId:3cebbfcb-fcca-47cd-9d67-245366ec7c49
Error Number:156,State:1,Class:15
```
As visible from SQL query, there is syntax issue near 'LEFT JOIN SELECT' part, and at the end, near 'ON [c].[UserId]'. Parentheses are missing before SELECT keyword, also [t1] alias isn't declared before ON, but is used here: '[c].[UserId] = [t1].[UserId]'. After fixing syntax, query is executed normally.

Fixed query to compare with generated:
```sql
DECLARE @___userId_0 int = 1081685;

SELECT [c].[UserId], [c].[Type], 1 AS [Weight]
FROM [Clients] AS [c]
LEFT JOIN (SELECT [t].[UserId], 5 AS [Action], [h].[CreateDate]
FROM [HomeTours] AS [h]
INNER JOIN (
    SELECT [c0].[Id], [c0].[CreateDate], [c0].[DeletionDate], [c0].[InvitationData], [c0].[IsActive], [c0].[IsDeleted], [c0].[Notes], [c0].[Type], [c0].[UserId]
    FROM [Clients] AS [c0]
    WHERE [c0].[IsDeleted] = CAST(0 AS bit)
) AS [t] ON [h].[ClientId] = [t].[Id]
WHERE ([t].[IsDeleted] = CAST(0 AS bit)) AND ([h].[Type] = 1)
UNION
SELECT [u].[UserId], 2 AS [Action], [u].[CreateDate]
FROM [UserViews] AS [u]) as [t1] ON [c].[UserId] = [t1].[UserId]
WHERE ([c].[IsDeleted] = CAST(0 AS bit)) AND EXISTS (
    SELECT 1
    FROM [AgentClients] AS [a]
    WHERE ([c].[Id] = [a].[ClientId]) AND ([a].[AgentUserId] = @___userId_0))
```

Summary:
I tried many different ways to modify the query and get the root cause, and found that issue happens when second query has UNION s in it.

EF Core version: 6.0.12
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 11
IDE: Visual Studio Community 2022 (17.5.2)

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ArMeN-git** [comment]
@ajcvickers The issue is actually happening when doing OrderBy/OrderByDescending on unioned query.
Please refer to this small console application where I reproduced the issue by using the same instructions and versions I mentioned here. https://github.com/ArMeN-git/MiniEFCoreApp
Steps:
1. Clone app
2. Create mssql db
3. Change connection string in DemoContext.cs -> OnConfiguring method
4. Apply migrations to db
5. Uncomment the data insertion part in Program.cs for the first run
6. Run and you will get Sql Exception: "Incorrect syntax near keyword select.."

**Comment by ajcvickers** [comment]
Note for triage: verified that this is fixed in EF Core 7.

@ArMeN-git Please update to EF Core 7.

**Comment by ArMeN-git** [comment]
@ajcvickers tested on EF Core 7. Looks correct!
