### ISSUE TITLE
Cannot generate compiled model with an enum using RC1

### ISSUE THREAD

**Issue by andygjp** [dotnet/efcore#31821]
I cannot generate a compiled model after updating tooling and packages to RC1.

I get the following error:

```
System.InvalidOperationException: The type mapping used is incompatible with a compiled model. The mapping type must have a 'public static readonly SqliteStringTypeMapping SqliteStringTypeMapping.Default' property.
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpRuntimeAnnotationCodeGenerator.CreateDefaultTypeMapping(CoreTypeMapping typeMapping, CSharpRuntimeAnnotationCodeGeneratorParameters parameters)
   at Microsoft.EntityFrameworkCore.Design.Internal.RelationalCSharpRuntimeAnnotationCodeGenerator.Create(CoreTypeMapping typeMapping, CSharpRuntimeAnnotationCodeGeneratorParameters parameters, ValueComparer valueComparer, ValueComparer keyValueComparer, ValueComparer providerValueComparer)
   at Microsoft.EntityFrameworkCore.Design.Internal.ICSharpRuntimeAnnotationCodeGenerator.Create(CoreTypeMapping typeMapping, IProperty property, CSharpRuntimeAnnotationCodeGeneratorParameters parameters)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpRuntimeModelCodeGenerator.Create(IProperty property, String variableName, Dictionary`2 propertyVariables, CSharpRuntimeAnnotationCodeGeneratorParameters parameters)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpRuntimeModelCodeGenerator.Create(IProperty property, Dictionary`2 propertyVariables, CSharpRuntimeAnnotationCodeGeneratorParameters parameters)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpRuntimeModelCodeGenerator.CreateEntityType(IEntityType entityType, IndentedStringBuilder mainBuilder, IndentedStringBuilder methodBuilder, SortedSet`1 namespaces, String className, Boolean nullable)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpRuntimeModelCodeGenerator.GenerateEntityType(IEntityType entityType, String namespace, String className, Boolean nullable)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpRuntimeModelCodeGenerator.GenerateModel(IModel model, CompiledModelCodeGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CompiledModelScaffolder.ScaffoldModel(IModel model, String outputDir, CompiledModelCodeGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.Optimize(String outputDir, String modelNamespace, String contextTypeName)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OptimizeContextImpl(String outputDir, String modelNamespace, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OptimizeContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The type mapping used is incompatible with a compiled model. The mapping type must have a 'public static readonly SqliteStringTypeMapping SqliteStringTypeMapping.Default' property.
```

I've recreated the issue here: https://github.com/andygjp/CompiledModelMissingMapping.

If you checkout the [previous commit](https://github.com/andygjp/CompiledModelMissingMapping/tree/a5725ad89945d9fff915978dd782f9e01b585d5f), you'll see that you generate the compiled model without any issue.

Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: NET 8.0
Operating system: macOS Ventura 13.5.2
IDE: Rider 2023.2.1

**Comment by ajcvickers** [comment]
Duplicate of #31727. Please try with the latest [daily build](https://github.com/dotnet/efcore/blob/release/8.0/docs/DailyBuilds.md) and make sure your issue is fixed.

**Comment by andygjp** [comment]
I updated to v8.0.0-rtm.23470.3 and I didn't get that error.

However, I did get a different one (the original issue I wanted to raise before I discovered this one):

![Screenshot 2023-09-20 at 23 32 14](https://github.com/dotnet/efcore/assets/1445933/71cda572-82e0-4404-8409-e0a3288cd90e)

Would you like me to raise a separate issue?

**Comment by andygjp** [comment]
I created a separate issue: https://github.com/dotnet/efcore/issues/31827
