### ISSUE TITLE
Generate migrations bundle EF core 7 in Dockerfile : ArgumentOutOfRangeException: Length cannot be less than zero

### ISSUE THREAD

**Issue by CedricSogetrel** [dotnet/efcore#31864]
Hi,

I'm trying to generate the migration bundle while building my docker image.
The purpose is to provide in the image all necessary to run my api : binaries and database migration.

But when the migration is built, i get an ArgumentOutOfRangeException: Length cannot be less than zero.
```
Building bundle...
System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsBundleCommand.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0(String[] args)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Length cannot be less than zero. (Parameter 'length')
```

My guess was there was a problem with the connection string, but it seems all is ok.
If somebody could priovide me a hint about which parameter is missing ?

Thanks in advance

Ced

Some information :

My startup.cs AddDbContext :
```C#
 private void AddDataAccessLayer(IServiceCollection services)
 {
      services.AddDbContext<SqlServerDbContext>(options =>
                {
                    options.UseSqlServer(
                        _configuration["ConnectionString"],
                        sqlOptions => sqlOptions.MigrationsAssembly("Dal.Migrations"));

                    if (_currentEnvironment.IsDevelopment())
                        options.LogTo(Console.WriteLine).EnableSensitiveDataLogging();
                },
                ServiceLifetime.Scoped);
}
```

My Dockerfile
```
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
ENV ASPNETCORE_URLS=http://+:5000
EXPOSE 5000

FROM  mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app/sources
COPY ["NuGet.config", "."]
COPY ["global.json", "."]
COPY ["Directory.Build.props", "."]
COPY ["src", "src"]
RUN dotnet tool install --global dotnet-ef --ignore-failed-sources
ENV PATH="$PATH:/root/.dotnet/tools"

ARG PAT
ENV PAT $PAT
ARG CONFIG=Release
RUN rm -f src/WebApp/appsettings.Development.json \
    && dotnet restore --configfile NuGet.config --locked-mode "src/WebApp" \
    && dotnet build --nologo -c "${CONFIG}" --no-restore "src/WebApp" \
    && dotnet publish --nologo -c "${CONFIG}" --no-build --no-restore -o /app/publish "src/WebApp" 
 RUN dotnet ef migrations bundle --self-contained --target-runtime alpine  \
   --output /app/publish/so-field-api-migration \
   --project ./src/Dal.Migrations/Dal.Migrations.csproj \
   --startup-project ./src/WebApp/WebApp.csproj \
   --context sqlServerDbContext 
   --configuration Bundle 
#System.ArgumentOutOfRangeException: Length cannot be less than zero

```

The appsettings.json in the container when the migration bundle is generated
```
{
  
  "ConnectionString": "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=sofield;Integrated Security=True;Connect Timeout=30;TrustServerCertificate=False;",
}
```

### Include provider and version information
EF Core version: 7.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: 7.0.306
Operating system: alpine image

**Comment by CedricSogetrel** [comment]
Hi,

I got some news: 
If i change 
```RUN dotnet ef migrations bundle --self-contained --target-runtime alpine ``` 
to
 ```RUN dotnet ef migrations bundle --self-contained --target-runtime alpine-x64``` 
the generation is successfull. I don't understand the link between the target-runtime and the ArgumentOutOfRangeException 

 If i try to run the generated bundle i got a lot of errors :
```Error relocating ./so-field-api-migration2: _ZTVN10__cxxabiv117__class_type_infoE: symbol not found```

the ldd check seems ok :
```
# ldd ./so-field-api-migration
        linux-vdso.so.1 (0x00007ffd6d363000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa6fa66e000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa6fa654000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa6fa487000)
        libc.musl-x86_64.so.1 => /lib/libc.musl-x86_64.so.1 (0x00007fa6fa3d1000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa6fa1fd000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa6fa0b9000)
        /lib/ld-musl-x86_64.so.1 => /lib64/ld-linux-x86-64.so.2 (0x00007fa6fb109000)
```
