### ISSUE TITLE
Convert.ToString(SomeProp, CultureInfo.InvariantCulture) throws when used in a Union

### ISSUE THREAD

**Issue by virzak** [dotnet/efcore#31910]
### Include your code

```C#
using Microsoft.EntityFrameworkCore;
using System.Globalization;

using var context = new MyDbContext();

await context.Database.EnsureDeletedAsync();
await context.Database.EnsureCreatedAsync();

context.Add(new Post() { Id = Guid.NewGuid(), Title = "My Title" });
await context.SaveChangesAsync();

var zz = context.Posts.Select(z => Convert.ToString(z.Title, CultureInfo.InvariantCulture))
    // Having at least one of the lines below uncommented results in exception
    .Union(context.Posts.Select(z => Convert.ToString(z.Title)))
    //.Union(context.Posts.Select(z => Convert.ToString(z.Title, CultureInfo.InvariantCulture)))
    ;

var list = await zz.ToListAsync();

public class MyDbContext : DbContext
{
    public DbSet<Post> Posts { get; set; } = default!;

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    => optionsBuilder
        //.UseSqlServer(FiddleHelper.GetConnectionStringSqlServer()).LogTo(Console.WriteLine);
        .UseSqlServer($@"Server=(localdb)\mssqllocaldb;Database={GetType().Assembly.GetName().Name};Trusted_Connection=True").LogTo(Console.WriteLine);
}

public class Post
{
    public Guid Id { get; set; }
    public string Title { get; set; }
}
```

### Include stack traces

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Unable to translate set operation after client projection has been applied. Consider moving the set operation before the last 'Select' call.
  Source=Microsoft.EntityFrameworkCore.Relational
  StackTrace:
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ApplySetOperation(SetOperationType setOperationType, SelectExpression select2, Boolean distinct)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ApplyUnion(SelectExpression source2, Boolean distinct)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateUnion(ShapedQueryExpression source1, ShapedQueryExpression source2)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__67`1.MoveNext()
   at Program.<<Main>$>d__0.MoveNext() in Q:\Code\Issues\dotnet\efcore\Convert-ToString-CA1305\Convert-ToString-CA1305\Program.cs:line 18
```

### Include verbose output

<details>

```
dbug: 2023-09-29 13:41:00.810 CoreEventId.ContextInitialized[10403] (Microsoft.EntityFrameworkCore.Infrastructure)
      Entity Framework Core 8.0.0-rc.1.23419.6 initialized 'MyDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer:8.0.0-rc.1.23419.6' with options: None
dbug: 2023-09-29 13:41:00.916 RelationalEventId.ConnectionCreating[20005] (Microsoft.EntityFrameworkCore.Database.Connection)
      Creating DbConnection.
dbug: 2023-09-29 13:41:00.985 RelationalEventId.ConnectionCreated[20006] (Microsoft.EntityFrameworkCore.Database.Connection)
      Created DbConnection. (70ms).
dbug: 2023-09-29 13:41:00.994 RelationalEventId.ConnectionOpening[20000] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opening connection to database 'Convert-ToString-CA1305' on server '(localdb)\mssqllocaldb'.
dbug: 2023-09-29 13:41:02.793 RelationalEventId.ConnectionOpened[20001] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opened connection to database 'Convert-ToString-CA1305' on server '(localdb)\mssqllocaldb'.
dbug: 2023-09-29 13:41:02.800 RelationalEventId.CommandCreating[20103] (Microsoft.EntityFrameworkCore.Database.Command)
      Creating DbCommand for 'ExecuteNonQuery'.
dbug: 2023-09-29 13:41:02.806 RelationalEventId.CommandCreated[20104] (Microsoft.EntityFrameworkCore.Database.Command)
      Created DbCommand for 'ExecuteNonQuery' (4ms).
dbug: 2023-09-29 13:41:02.808 RelationalEventId.CommandInitialized[20106] (Microsoft.EntityFrameworkCore.Database.Command)
      Initialized DbCommand for 'ExecuteNonQuery' (9ms).
dbug: 2023-09-29 13:41:02.813 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
info: 2023-09-29 13:41:02.845 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (31ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
dbug: 2023-09-29 13:41:02.848 RelationalEventId.ConnectionClosing[20002] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closing connection to database 'Convert-ToString-CA1305' on server '(localdb)\mssqllocaldb'.
dbug: 2023-09-29 13:41:02.854 RelationalEventId.ConnectionClosed[20003] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closed connection to database 'Convert-ToString-CA1305' on server '(localdb)\mssqllocaldb' (4ms).
dbug: 2023-09-29 13:41:02.882 RelationalEventId.ConnectionCreating[20005] (Microsoft.EntityFrameworkCore.Database.Connection)
      Creating DbConnection.
dbug: 2023-09-29 13:41:02.883 RelationalEventId.ConnectionCreated[20006] (Microsoft.EntityFrameworkCore.Database.Connection)
      Created DbConnection. (0ms).
dbug: 2023-09-29 13:41:02.883 RelationalEventId.ConnectionOpening[20000] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opening connection to database 'master' on server '(localdb)\mssqllocaldb'.
dbug: 2023-09-29 13:41:02.892 RelationalEventId.ConnectionOpened[20001] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opened connection to database 'master' on server '(localdb)\mssqllocaldb'.
dbug: 2023-09-29 13:41:02.894 RelationalEventId.CommandCreating[20103] (Microsoft.EntityFrameworkCore.Database.Command)
      Creating DbCommand for 'ExecuteNonQuery'.
dbug: 2023-09-29 13:41:02.895 RelationalEventId.CommandCreated[20104] (Microsoft.EntityFrameworkCore.Database.Command)
      Created DbCommand for 'ExecuteNonQuery' (0ms).
dbug: 2023-09-29 13:41:02.895 RelationalEventId.CommandInitialized[20106] (Microsoft.EntityFrameworkCore.Database.Command)
      Initialized DbCommand for 'ExecuteNonQuery' (0ms).
dbug: 2023-09-29 13:41:02.896 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='60']
      IF SERVERPROPERTY('EngineEdition') <> 5
      BEGIN
          ALTER DATABASE [Convert-ToString-CA1305] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
      END;
info: 2023-09-29 13:41:02.903 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (7ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
      IF SERVERPROPERTY('EngineEdition') <> 5
      BEGIN
          ALTER DATABASE [Convert-ToString-CA1305] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
      END;
dbug: 2023-09-29 13:41:02.903 RelationalEventId.CommandCreating[20103] (Microsoft.EntityFrameworkCore.Database.Command)
      Creating DbCommand for 'ExecuteNonQuery'.
dbug: 2023-09-29 13:41:02.904 RelationalEventId.CommandCreated[20104] (Microsoft.EntityFrameworkCore.Database.Command)
      Created DbCommand for 'ExecuteNonQuery' (0ms).
dbug: 2023-09-29 13:41:02.904 RelationalEventId.CommandInitialized[20106] (Microsoft.EntityFrameworkCore.Database.Command)
      Initialized DbCommand for 'ExecuteNonQuery' (0ms).
dbug: 2023-09-29 13:41:02.905 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='60']
      DROP DATABASE [Convert-ToString-CA1305];
info: 2023-09-29 13:41:02.923 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (18ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
      DROP DATABASE [Convert-ToString-CA1305];
dbug: 2023-09-29 13:41:02.925 RelationalEventId.ConnectionClosing[20002] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closing connection to database 'master' on server '(localdb)\mssqllocaldb'.
dbug: 2023-09-29 13:41:02.925 RelationalEventId.ConnectionClosed[20003] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closed connection to database 'master' on server '(localdb)\mssqllocaldb' (0ms).
dbug: 2023-09-29 13:41:02.929 RelationalEventId.ConnectionDisposing[20007] (Microsoft.EntityFrameworkCore.Database.Connection)
      Disposing connection to database 'master' on server '(localdb)\mssqllocaldb'.
dbug: 2023-09-29 13:41:02.930 RelationalEventId.ConnectionDisposed[20008] (Microsoft.EntityFrameworkCore.Database.Connection)
      Disposed connection to database '' on server '' (1ms).
dbug: 2023-09-29 13:41:02.932 RelationalEventId.ConnectionOpening[20000] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opening connection to database 'Convert-ToString-CA1305' on server '(localdb)\mssqllocaldb'.
dbug: 2023-09-29 13:41:02.949 RelationalEventId.ConnectionError[20004] (Microsoft.EntityFrameworkCore.Database.Connection)
      An error occurred using the connection to database 'Convert-ToString-CA1305' on server '(localdb)\mssqllocaldb'.
dbug: 2023-09-29 13:41:02.961 RelationalEventId.ConnectionCreating[20005] (Microsoft.EntityFrameworkCore.Database.Connection)
      Creating DbConnection.
dbug: 2023-09-29 13:41:02.962 RelationalEventId.ConnectionCreated[20006] (Microsoft.EntityFrameworkCore.Database.Connection)
      Created DbConnection. (0ms).
dbug: 2023-09-29 13:41:02.962 RelationalEventId.ConnectionOpening[20000] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opening connection to database 'master' on server '(localdb)\mssqllocaldb'.
dbug: 2023-09-29 13:41:02.963 RelationalEventId.ConnectionOpened[20001] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opened connection to database 'master' on server '(localdb)\mssqllocaldb'.
dbug: 2023-09-29 13:41:02.964 RelationalEventId.CommandCreating[20103] (Microsoft.EntityFrameworkCore.Database.Command)
      Creating DbCommand for 'ExecuteNonQuery'.
dbug: 2023-09-29 13:41:02.964 RelationalEventId.CommandCreated[20104] (Microsoft.EntityFrameworkCore.Database.Command)
      Created DbCommand for 'ExecuteNonQuery' (0ms).
dbug: 2023-09-29 13:41:02.965 RelationalEventId.CommandInitialized[20106] (Microsoft.EntityFrameworkCore.Database.Command)
      Initialized DbCommand for 'ExecuteNonQuery' (1ms).
dbug: 2023-09-29 13:41:02.966 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='60']
      CREATE DATABASE [Convert-ToString-CA1305];
info: 2023-09-29 13:41:03.144 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (179ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
      CREATE DATABASE [Convert-ToString-CA1305];
dbug: 2023-09-29 13:41:03.145 RelationalEventId.CommandCreating[20103] (Microsoft.EntityFrameworkCore.Database.Command)
      Creating DbCommand for 'ExecuteNonQuery'.
dbug: 2023-09-29 13:41:03.146 RelationalEventId.CommandCreated[20104] (Microsoft.EntityFrameworkCore.Database.Command)
      Created DbCommand for 'ExecuteNonQuery' (0ms).
dbug: 2023-09-29 13:41:03.146 RelationalEventId.CommandInitialized[20106] (Microsoft.EntityFrameworkCore.Database.Command)
      Initialized DbCommand for 'ExecuteNonQuery' (0ms).
dbug: 2023-09-29 13:41:03.147 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='60']
      IF SERVERPROPERTY('EngineEdition') <> 5
      BEGIN
          ALTER DATABASE [Convert-ToString-CA1305] SET READ_COMMITTED_SNAPSHOT ON;
      END;
info: 2023-09-29 13:41:03.192 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (45ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
      IF SERVERPROPERTY('EngineEdition') <> 5
      BEGIN
          ALTER DATABASE [Convert-ToString-CA1305] SET READ_COMMITTED_SNAPSHOT ON;
      END;
dbug: 2023-09-29 13:41:03.193 RelationalEventId.ConnectionClosing[20002] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closing connection to database 'master' on server '(localdb)\mssqllocaldb'.
dbug: 2023-09-29 13:41:03.194 RelationalEventId.ConnectionClosed[20003] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closed connection to database 'master' on server '(localdb)\mssqllocaldb' (0ms).
dbug: 2023-09-29 13:41:03.195 RelationalEventId.ConnectionDisposing[20007] (Microsoft.EntityFrameworkCore.Database.Connection)
      Disposing connection to database 'master' on server '(localdb)\mssqllocaldb'.
dbug: 2023-09-29 13:41:03.195 RelationalEventId.ConnectionDisposed[20008] (Microsoft.EntityFrameworkCore.Database.Connection)
      Disposed connection to database '' on server '' (0ms).
dbug: 2023-09-29 13:41:03.196 RelationalEventId.ConnectionOpening[20000] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opening connection to database 'Convert-ToString-CA1305' on server '(localdb)\mssqllocaldb'.
dbug: 2023-09-29 13:41:03.205 RelationalEventId.ConnectionOpened[20001] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opened connection to database 'Convert-ToString-CA1305' on server '(localdb)\mssqllocaldb'.
dbug: 2023-09-29 13:41:03.207 RelationalEventId.CommandCreating[20103] (Microsoft.EntityFrameworkCore.Database.Command)
      Creating DbCommand for 'ExecuteNonQuery'.
dbug: 2023-09-29 13:41:03.207 RelationalEventId.CommandCreated[20104] (Microsoft.EntityFrameworkCore.Database.Command)
      Created DbCommand for 'ExecuteNonQuery' (0ms).
dbug: 2023-09-29 13:41:03.208 RelationalEventId.CommandInitialized[20106] (Microsoft.EntityFrameworkCore.Database.Command)
      Initialized DbCommand for 'ExecuteNonQuery' (1ms).
dbug: 2023-09-29 13:41:03.208 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
info: 2023-09-29 13:41:03.210 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
dbug: 2023-09-29 13:41:03.212 RelationalEventId.ConnectionClosing[20002] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closing connection to database 'Convert-ToString-CA1305' on server '(localdb)\mssqllocaldb'.
dbug: 2023-09-29 13:41:03.213 RelationalEventId.ConnectionClosed[20003] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closed connection to database 'Convert-ToString-CA1305' on server '(localdb)\mssqllocaldb' (0ms).
dbug: 2023-09-29 13:41:03.264 RelationalEventId.ConnectionOpening[20000] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opening connection to database 'Convert-ToString-CA1305' on server '(localdb)\mssqllocaldb'.
dbug: 2023-09-29 13:41:03.264 RelationalEventId.ConnectionOpened[20001] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opened connection to database 'Convert-ToString-CA1305' on server '(localdb)\mssqllocaldb'.
dbug: 2023-09-29 13:41:03.269 RelationalEventId.TransactionStarting[20209] (Microsoft.EntityFrameworkCore.Database.Transaction)
      Beginning transaction with isolation level 'Unspecified'.
dbug: 2023-09-29 13:41:03.275 RelationalEventId.TransactionStarted[20200] (Microsoft.EntityFrameworkCore.Database.Transaction)
      Began transaction with isolation level 'ReadCommitted'.
dbug: 2023-09-29 13:41:03.276 RelationalEventId.CommandCreating[20103] (Microsoft.EntityFrameworkCore.Database.Command)
      Creating DbCommand for 'ExecuteNonQuery'.
dbug: 2023-09-29 13:41:03.277 RelationalEventId.CommandCreated[20104] (Microsoft.EntityFrameworkCore.Database.Command)
      Created DbCommand for 'ExecuteNonQuery' (0ms).
dbug: 2023-09-29 13:41:03.278 RelationalEventId.CommandInitialized[20106] (Microsoft.EntityFrameworkCore.Database.Command)
      Initialized DbCommand for 'ExecuteNonQuery' (1ms).
dbug: 2023-09-29 13:41:03.278 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE [Posts] (
          [Id] uniqueidentifier NOT NULL,
          [Title] nvarchar(max) NOT NULL,
          CONSTRAINT [PK_Posts] PRIMARY KEY ([Id])
      );
info: 2023-09-29 13:41:03.286 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (8ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE [Posts] (
          [Id] uniqueidentifier NOT NULL,
          [Title] nvarchar(max) NOT NULL,
          CONSTRAINT [PK_Posts] PRIMARY KEY ([Id])
      );
dbug: 2023-09-29 13:41:03.291 RelationalEventId.TransactionCommitting[20210] (Microsoft.EntityFrameworkCore.Database.Transaction)
      Committing transaction.
dbug: 2023-09-29 13:41:03.295 RelationalEventId.TransactionCommitted[20202] (Microsoft.EntityFrameworkCore.Database.Transaction)
      Committed transaction.
dbug: 2023-09-29 13:41:03.299 RelationalEventId.TransactionDisposed[20204] (Microsoft.EntityFrameworkCore.Database.Transaction)
      Disposing transaction.
dbug: 2023-09-29 13:41:03.299 RelationalEventId.ConnectionClosing[20002] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closing connection to database 'Convert-ToString-CA1305' on server '(localdb)\mssqllocaldb'.
dbug: 2023-09-29 13:41:03.300 RelationalEventId.ConnectionClosed[20003] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closed connection to database 'Convert-ToString-CA1305' on server '(localdb)\mssqllocaldb' (0ms).
dbug: 2023-09-29 13:41:03.363 CoreEventId.StartedTracking[10806] (Microsoft.EntityFrameworkCore.ChangeTracking)
      Context 'MyDbContext' started tracking 'Post' entity. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see key values.
dbug: 2023-09-29 13:41:03.368 CoreEventId.SaveChangesStarting[10004] (Microsoft.EntityFrameworkCore.Update)
      SaveChanges starting for 'MyDbContext'.
dbug: 2023-09-29 13:41:03.370 CoreEventId.DetectChangesStarting[10800] (Microsoft.EntityFrameworkCore.ChangeTracking)
      DetectChanges starting for 'MyDbContext'.
dbug: 2023-09-29 13:41:03.377 CoreEventId.DetectChangesCompleted[10801] (Microsoft.EntityFrameworkCore.ChangeTracking)
      DetectChanges completed for 'MyDbContext'.
dbug: 2023-09-29 13:41:03.419 RelationalEventId.ConnectionOpening[20000] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opening connection to database 'Convert-ToString-CA1305' on server '(localdb)\mssqllocaldb'.
dbug: 2023-09-29 13:41:03.419 RelationalEventId.ConnectionOpened[20001] (Microsoft.EntityFrameworkCore.Database.Connection)
      Opened connection to database 'Convert-ToString-CA1305' on server '(localdb)\mssqllocaldb'.
dbug: 2023-09-29 13:41:03.423 RelationalEventId.CommandCreating[20103] (Microsoft.EntityFrameworkCore.Database.Command)
      Creating DbCommand for 'ExecuteReader'.
dbug: 2023-09-29 13:41:03.423 RelationalEventId.CommandCreated[20104] (Microsoft.EntityFrameworkCore.Database.Command)
      Created DbCommand for 'ExecuteReader' (0ms).
dbug: 2023-09-29 13:41:03.427 RelationalEventId.CommandInitialized[20106] (Microsoft.EntityFrameworkCore.Database.Command)
      Initialized DbCommand for 'ExecuteReader' (3ms).
dbug: 2023-09-29 13:41:03.429 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[@p0='?' (DbType = Guid), @p1='?' (Size = 4000)], CommandType='Text', CommandTimeout='30']
      SET IMPLICIT_TRANSACTIONS OFF;
      SET NOCOUNT ON;
      INSERT INTO [Posts] ([Id], [Title])
      VALUES (@p0, @p1);
info: 2023-09-29 13:41:03.463 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (36ms) [Parameters=[@p0='?' (DbType = Guid), @p1='?' (Size = 4000)], CommandType='Text', CommandTimeout='30']
      SET IMPLICIT_TRANSACTIONS OFF;
      SET NOCOUNT ON;
      INSERT INTO [Posts] ([Id], [Title])
      VALUES (@p0, @p1);
dbug: 2023-09-29 13:41:03.467 RelationalEventId.DataReaderClosing[20301] (Microsoft.EntityFrameworkCore.Database.Command)
      Closing data reader to 'Convert-ToString-CA1305' on server '(localdb)\mssqllocaldb'.
dbug: 2023-09-29 13:41:03.471 RelationalEventId.DataReaderDisposing[20300] (Microsoft.EntityFrameworkCore.Database.Command)
      A data reader for 'Convert-ToString-CA1305' on server '(localdb)\mssqllocaldb' is being disposed after spending 6ms reading results.
dbug: 2023-09-29 13:41:03.473 RelationalEventId.ConnectionClosing[20002] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closing connection to database 'Convert-ToString-CA1305' on server '(localdb)\mssqllocaldb'.
dbug: 2023-09-29 13:41:03.473 RelationalEventId.ConnectionClosed[20003] (Microsoft.EntityFrameworkCore.Database.Connection)
      Closed connection to database 'Convert-ToString-CA1305' on server '(localdb)\mssqllocaldb' (0ms).
dbug: 2023-09-29 13:41:03.478 CoreEventId.StateChanged[10807] (Microsoft.EntityFrameworkCore.ChangeTracking)
      An entity of type 'Post' tracked by 'MyDbContext' changed state from 'Added' to 'Unchanged'. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see key values.
dbug: 2023-09-29 13:41:03.481 CoreEventId.SaveChangesCompleted[10005] (Microsoft.EntityFrameworkCore.Update)
      SaveChanges completed for 'MyDbContext' with 1 entities written to the database.
dbug: 2023-09-29 13:41:03.509 CoreEventId.QueryCompilationStarting[10111] (Microsoft.EntityFrameworkCore.Query)
      Compiling query expression:
      'DbSet<Post>()
          .Select(z => Convert.ToString(
              value: z.Title,
              provider: __InvariantCulture_0))
          .Union(DbSet<Post>()
              .Select(z => Convert.ToString(z.Title)))'
```

</details>

### Include provider and version information

EF Core version: 8 rc1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: 8 rc1
Operating system: Windows

**Comment by ajcvickers** [comment]
@virzak EF cannot currently translate `Convert.ToString(z.Title, CultureInfo.InvariantCulture)` to SQL--I will discuss with the team whether or not it should. However, in the query above that works, this conversion can be applied on the client in the final projection without pulling any additional data back or changing the semantics of the results. This is no longer possible when `Union` is used because now the call to `Convert` is not just in the final projection.

**Comment by virzak** [comment]
Not having `CultureInfo.InvariantCulture` causes CA1305. That's the reason for inserting it there in the first place.

**Comment by roji** [comment]
@virzak what's the intention behind calling `Convert.ToString(z.Title, CultureInfo.InvariantCulture)`, what does that achieve and what would expect it to get translated to (in SQL)?

**Comment by virzak** [comment]
@roji The main intention was to get rid of the warning. The translation should remain the same. You recently discussed suppressing a similar warning in #31431.
