### ISSUE TITLE
Insert trigger breaks SaveChanges

### ISSUE THREAD

**Issue by pjpmccarthy** [dotnet/efcore#31985]
## Ask a question

I have the setting to tell EF Core 7.0 to be aware of a trigger on my table 
It's an Insert Trigger that does nothing (I've removed all the previous code)

'''
modelBuilder.Entity<Ntu>().ToTable(tb => tb.HasTrigger("InsertTrigger"));
'''

I'm inserting a record and the Insert fails.
If I disable the trigger, the Insert works.

The error is below and indicates that the the key (NtuId) field is null.
Obviously it is not null (because then how could it work when the trigger is disabled)

The field is an identity column so I suspect that whatever EF core is doing to save the record when there's a trigger is causing it to lose the value in the field. Note the value is zero for inserting a new record.

An error occurred while saving the entity changes. See the inner exception for details.
2023-10-06 12:39:40.760 +01:00 [ERR] An error occurred while reading a database value for property 'Ntu.NtuId'. The expected type was 'System.Int32' but the actual value was null.
2023-10-06 12:39:40.767 +01:00 [ERR]    at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__107_0(DbContext _, ValueTuple`2 t)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()

Using EF core 6.0 with the same code I get this error:
Index was outside the bounds of the array.

I've output the value of the field in the 'Inserted' table in the trigger and verified that it has the new value that should end up in the field, i.e. no longer zero, has the correct new value. 

Neither error makes any sense so it looks like a bug in EF core.

(very disappointing - we've enough trigger problems without EF core adding more)

**Comment by ErikEJ** [comment]
Please share a full repro...

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by pjpmccarthy** [comment]
'''
DECLARE @Command NVARCHAR(1000);
SET @Command = 'echo "Hello World" >> C:\TriggerLog\TriggerLog.txt'
EXEC xp_cmdshell @Command
'''

The code above is what EF core does not like. It's used to log that the trigger fired.
It gives no error, and updates the file but magically causes EF Core to not save the record!

**Comment by pjpmccarthy** [comment]
Hopefully someone else on here will have seen the issue and be able to help.
Given that I can disable the trigger and then save the record without even stopping my application suggests that there is a problem.
I'd guess that some of the "new" code that won't save when a trigger is present has accidentally got into the code that runs when a trigger is present.

**Comment by roji** [comment]
@pjpmccarthy are you not able to put together a small console program that shows this?

We generally don't keep issues open which haven't been confirmed to represent a bug, so unless you're able to provide some sort of repro we'll have to close this.

**Comment by pjpmccarthy** [comment]
If you close and I later find a solution then nobody else will get to know
about it.

**Comment by roji** [comment]
@pjpmccarthy you can post your solution back here later even if I close the issue. Regardless, the best thing for you to do - as I wrote several times - is to provide a minimal repro, as is standard when opening issues.

**Comment by pjpmccarthy** [comment]
You appear to be more interested in closing the ticket than investigating
the problem. Do you get a bonus for closing tickets?

**Comment by roji** [comment]
@pjpmccarthy please submit a minimal repro as I've requested several times.

**Comment by pjpmccarthy** [comment]
I found a workaround where I can call a procedure instead of xp_cmdshell, when I do this EF core does not fail to save.

**Comment by roji** [comment]
@pjpmccarthy OK, should we close this issue then? Or would you like to submit a repro so we can investigate?

**Comment by pjpmccarthy** [comment]
If you add a call to xp_cmdshell to one of your existing triggers and it prevents the EF core SaveChanges from saving (as it does for me) then you have soemthing to investigate. I'd prefer that you leave the issue open, so that if other people have it they know that the workaround is to avoid xp_cmdshell

**Comment by roji** [comment]
@pjpmccarthy we only leave issues open which represent a verified work item in EF itself; otherwise it's impossible for us to track our own work. People can find this issue regardless of whether it's open or closed.
