### ISSUE TITLE
Microsoft.Data.Sqlite with nhibernate - update Schema not working

### ISSUE THREAD

**Issue by PriyankaChandrabose** [dotnet/efcore#31998]
when connecting Microsoft.data.sqlite with nhibernate - we are unable to do schema update - Exception thrown 
deep diving we found - nhibernate calls getschema method with 2nd arg value-- which is throwing exception as Microsoft.Data.Sqlite has their implementation  as throw exception

ERROR NHibernate.Tool.hbm2ddl.SchemaUpdate - could not complete schema update
System.ArgumentException: More restrictions were provided than the collection 'Tables' supports.
   **at Microsoft.Data.Sqlite.SqliteConnection.GetSchema(String collectionName, String[] restrictionValues)**
   at NHibernate.Dialect.Schema.AbstractDataBaseSchema.GetTables(String catalog, String schemaPattern, String tableNamePattern, String[] types)
   at NHibernate.Dialect.Schema.SQLiteDataBaseMetaData.GetTables(String catalog, String schemaPattern, String tableNamePattern, String[] types)
   at NHibernate.Tool.hbm2ddl.DatabaseMetadata.GetTableMetadata(String name, String schema, String catalog, Boolean isQuoted)
   at NHibernate.Cfg.Configuration.GenerateSchemaUpdateScript(Dialect dialect, IDatabaseMetadata databaseMetadata)
   at NHibernate.Tool.hbm2ddl.SchemaUpdate.Execute(Action`1 scriptAction, Boolean doUpdate)

Version used:
FluentNHibernate -  Version="3.3.0"
Microsoft.Data.Sqlite - Version="6.0.22"

[UnitOfWork.txt](https://github.com/dotnet/SqlClient/files/12844567/UnitOfWork.txt)
![GetTables](https://github.com/dotnet/SqlClient/assets/68009852/df49c694-c4b1-4cf0-bdbb-621dd60a01d2)
![MethodCall](https://github.com/dotnet/SqlClient/assets/68009852/e54f463d-35a6-4b24-8334-866ba62ea60c)
![GetSchema](https://github.com/dotnet/SqlClient/assets/68009852/81b1295a-b649-40ab-8504-5f275de8fedb)

**Comment by 5pHiNxX** [comment]
This is how System.Data.SQLite handles this. NHibernate Schema Update and Validation work like a charm with it.

```csharp
/// <summary>
/// Retrieves schema information using the specified constraint(s) for the specified collection
/// </summary>
/// <param name="collectionName">The collection to retrieve</param>
/// <param name="restrictionValues">The restrictions to impose</param>
/// <returns>A DataTable of the specified collection</returns>
public override DataTable GetSchema(string collectionName, string[] restrictionValues)
{
  if (_connectionState != ConnectionState.Open)
    throw new InvalidOperationException();

  string[] parms = new string[5];

  if (restrictionValues == null) restrictionValues = new string[0];
  restrictionValues.CopyTo(parms, 0);

  switch (collectionName.ToUpper(CultureInfo.InvariantCulture))
  {
    case "METADATACOLLECTIONS":
      return Schema_MetaDataCollections();
    case "DATASOURCEINFORMATION":
      return Schema_DataSourceInformation();
    case "DATATYPES":
      return Schema_DataTypes();
    case "COLUMNS":
    case "TABLECOLUMNS":
      return Schema_Columns(parms[0], parms[2], parms[3]);
    case "INDEXES":
      return Schema_Indexes(parms[0], parms[2], parms[3]);
    case "TRIGGERS":
      return Schema_Triggers(parms[0], parms[2], parms[3]);
    case "INDEXCOLUMNS":
      return Schema_IndexColumns(parms[0], parms[2], parms[3], parms[4]);
    case "TABLES":
      return Schema_Tables(parms[0], parms[2], parms[3]);
    case "VIEWS":
      return Schema_Views(parms[0], parms[2]);
    case "VIEWCOLUMNS":
      return Schema_ViewColumns(parms[0], parms[2], parms[3]);
    case "FOREIGNKEYS":
      return Schema_ForeignKeys(parms[0], parms[2], parms[3]);
    case "CATALOGS":
      return Schema_Catalogs(parms[0]);
    case "RESERVEDWORDS":
      return Schema_ReservedWords();
  }
  throw new NotSupportedException();
}```

**Comment by pp-mluthi** [comment]
We got the same error here, any update on this ?

**Comment by bricelam** [comment]
Currently, only the METADATACOLLECTIONS and RESERVEDWORDS collections are implemented. These APIs are neither strongly typed nor well defined and, thus, are not very useful from the perspective of polymorphism.

If you want to wrap the Microsoft.Data.Sqlite provider and implement them yourself, the [SqliteObjectSelector](https://github.com/bricelam/VS.Data.Sqlite/blob/main/VS.Data.Sqlite/SqliteObjectSelector.cs) class in my VS.Data.Sqlite project provides a good starting point.

**Comment by roji** [comment]
I've opened #35917 to specifically track improving SqliteConnection.GetSchema() support, which is what this issue is mostly about (that could help not just NHibernate). It's unlikely we'll get around to doing work on this any time soon, but I do believe it could make sense to improve things in this area. Will close this issue as a duplicate of that.
