### ISSUE TITLE
Case expressions may only be nested to level 10 when using SplitQuery() or ToList() inside projection.

### ISSUE THREAD

**Issue by Ben555555** [dotnet/efcore#32023]
## File a bug

When using the following code I get the exception "Case expressions may only be nested to level 10". I read that this should already be solved so I played around with the code a bit. It seems that if I either remove "SplitQuery()" or the "ToList()" [LanguageCodes in the example] inside the projection, the exception does not appear anymore. I think removing ToList() in my example results in the same as removing SplitQuery() because there are no queries to split anymore. So the problem seems to be the query splitting somehow.

### Include your code

```
await query
    .Select(documentTemplate => new DocumentTemplateListModel()
    {
        Id = documentTemplate.Id,
        LanguageCodes = documentTemplate.DocumentTemplateFiles
            .Select(documentTemplateFile => documentTemplateFile.LanguageCode)
            .ToList(),
        DocumentCategory = documentTemplate.DocumentCategory == (DocumentCategory)0 ? "1" :
            documentTemplate.DocumentCategory == (DocumentCategory)1 ? "2" :
            documentTemplate.DocumentCategory == (DocumentCategory)2 ? "3" :
            documentTemplate.DocumentCategory == (DocumentCategory)3 ? "4" :
            documentTemplate.DocumentCategory == (DocumentCategory)4 ? "5" :
            documentTemplate.DocumentCategory == (DocumentCategory)5 ? "6" :
            documentTemplate.DocumentCategory == (DocumentCategory)6 ? "7" :
            documentTemplate.DocumentCategory == (DocumentCategory)7 ? "8" :
            documentTemplate.DocumentCategory == (DocumentCategory)8 ? "9" :
            documentTemplate.DocumentCategory == (DocumentCategory)9 ? "10" :
            documentTemplate.DocumentCategory == (DocumentCategory)10 ? "11" :
            documentTemplate.DocumentCategory == (DocumentCategory)11 ? "12" :
            documentTemplate.DocumentCategory == (DocumentCategory)12 ? "13" :
            documentTemplate.DocumentCategory == (DocumentCategory)13 ? "14" : null!,
    })
    .OrderBy(documentTemplate => documentTemplate.DocumentCategory)
    .AsSplitQuery()
    .ToListAsync();
```

### Include stack traces

> Microsoft.Data.SqlClient.SqlException (0x80131904): Case expressions may only be nested to level 10.
>    at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__188_0(Task`1 result)
>    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
>    at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> 

### Include provider and version information

EF Core version: 6.0.11
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.6.6

**Comment by ajcvickers** [comment]
@maumar Is this a dupe?

**Comment by maumar** [comment]
we had issues for case nesting optimization (fixed before 6.0), this one supposedly happens with SplitQuery - will take a look

**Comment by maumar** [comment]
I'm able to reproduce this on current bits. Problem is that our query simplifier that unnest case expression only runs on `QueryExpression` part of `ShapedQueryExpression`. In case of split query, there is sqlexpression in the `ShaperExpression` also, which never runs through the visitor.

**Comment by maumar** [comment]
query before optimization (somewhat simplified):

```cs
ShapedQueryExpression: 
    QueryExpression: 
        Client Projections:
            0 -> 0
            1 -> 1
        SELECT c.CustomerID, CASE
            WHEN c.CustomerID == N'1' THEN N'01'
            ELSE CASE
                WHEN c.CustomerID == N'2' THEN N'02'
                ELSE CASE
                    WHEN c.CustomerID == N'3' THEN N'03'
                    ELSE NULL
                END
            END
        END
        FROM Customers AS c
        WHERE CASE
            WHEN c.CustomerID == N'1' THEN N'01'
            ELSE CASE
                WHEN c.CustomerID == N'2' THEN N'02'
                ELSE CASE
                    WHEN c.CustomerID == N'3' THEN N'03'
                    ELSE NULL
                END
            END
        END != N'Fubar'
        ORDER BY c.CustomerID ASC
    ShaperExpression: new { 
            Foo = RelationalSplitCollectionShaperExpression:
                ParentIdentifier:new object[]{ ProjectionBindingExpression: 0 }
                ChildIdentifier:new object[]{ ProjectionBindingExpression: 1 }
                SelectExpression:Client Projections:
                    0 -> 0
                    1 -> 1
                SELECT o.CustomerID, c.CustomerID
                FROM Customers AS c
                INNER JOIN Orders AS o ON c.CustomerID == o.CustomerID
                WHERE CASE
                    WHEN c.CustomerID == N'1' THEN N'01'
                    ELSE CASE
                        WHEN c.CustomerID == N'2' THEN N'02'
                        ELSE CASE
                            WHEN c.CustomerID == N'3' THEN N'03'
                            ELSE NULL
                        END
                    END
                END != N'Fubar'
                ORDER BY c.CustomerID ASC
                InnerShaper:ProjectionBindingExpression: 0
                Navigation: 
            , 
            Bar = ProjectionBindingExpression: 1
         }
```

query after:

```cs
ShapedQueryExpression: 
    QueryExpression: 
        Client Projections:
            0 -> 0
            1 -> 1
        SELECT c.CustomerID, CASE
            WHEN c.CustomerID == N'1' THEN N'01'
            WHEN c.CustomerID == N'2' THEN N'02'
            WHEN c.CustomerID == N'3' THEN N'03'
            ELSE NULL
        END
        FROM Customers AS c
        WHERE CASE
            WHEN c.CustomerID == N'1' THEN N'01'
            WHEN c.CustomerID == N'2' THEN N'02'
            WHEN c.CustomerID == N'3' THEN N'03'
            ELSE NULL
        END != N'Fubar'
        ORDER BY c.CustomerID ASC
    ShaperExpression: new { 
            Foo = RelationalSplitCollectionShaperExpression:
                ParentIdentifier:new object[]{ ProjectionBindingExpression: 0 }
                ChildIdentifier:new object[]{ ProjectionBindingExpression: 1 }
                SelectExpression:Client Projections:
                    0 -> 0
                    1 -> 1
                SELECT o.CustomerID, c.CustomerID
                FROM Customers AS c
                INNER JOIN Orders AS o ON c.CustomerID == o.CustomerID
                WHERE CASE
                    WHEN c.CustomerID == N'1' THEN N'01'
                    ELSE CASE
                        WHEN c.CustomerID == N'2' THEN N'02'
                        ELSE CASE
                            WHEN c.CustomerID == N'3' THEN N'03'
                            ELSE NULL
                        END
                    END
                END != N'Fubar'
                ORDER BY c.CustomerID ASC
                InnerShaper:ProjectionBindingExpression: 0
                Navigation: 
            , 
            Bar = ProjectionBindingExpression: 1
         }
```
