### ISSUE TITLE
Object must implement IConvertible when used strongly typed keys 

### ISSUE THREAD

**Issue by montella1507** [dotnet/efcore#32030]
Hey, i have the following:
```C#
// Strongly typed key
public record DbUserId(Guid Value)
{
    public DbUserId() : this(Guid.NewGuid())
    {
    }
    
    public static implicit operator Guid(DbUserId id) => id.Value;
    public static implicit operator Guid?(DbUserId? id) => id != null ? id.Value : null;

    public static bool operator ==(DbUserId id, Guid guid)
    {
        return id.Value == guid;
    }

    public static bool operator !=(DbUserId id, Guid guid)
    {
        return !(id == guid);
    }

    public static bool operator ==(DbUserId? id, Guid? guid)
    {
        if (id == null || guid == null) return false;
        return id.Value == guid;
    }

    public static bool operator !=(DbUserId? id, Guid? guid)
    {
        return !(id == guid);
    }
}

// entity 
public class DbUser {
   public DbUserId Id { get; set; } 
    // .. other relations
}

// Configuration
        builder
            .Property(x => x.Id)
            .HasColumnName("Id")
            .HasConversion<Guid>(
                x => x.Value,
                a => new DbUserId(a)
            );
```

The problem is, this works:

```C#
        this._dbUser = await _db.Users
            .Where(x => x.Id == new DbUserId(id))
           .ToList();
```

But this code throws the exception
```C#
        this._dbUser = await _db.Users
            .Where(x => x.Id ==id)
           .ToList();
```

`System.InvalidCastException: Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.Sanitize[T](Object value)
   at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.<>c__DisplayClass4_0`2.<SanitizeConverter>b__1(Object v)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping.CreateParameter(DbCommand command, String name, Object value, Nullable`1 nullable, ParameterDirection direction)
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypeMappedRelationalParameter.AddDbParameter(DbCommand command, Object value)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBase.AddDbParameter(DbCommand command, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.CreateDbCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Phoenix.API.Features.Users.UsersController.GetById(Guid id) in .........

`
<img width="619" alt="image" src="https://github.com/dotnet/efcore/assets/10418323/5cf11ce5-64e8-4b78-80ce-587d2c6096ef">

macOS, .NET 7+, MS Sql server

**Comment by ajcvickers** [comment]
@montella1507 Generally speaking, EF Core doesn't support translations for custom operator overloading.

**Comment by montella1507** [comment]
So... the problem is "GUID" and not "DbUserId" in that compare operator inside Where clause? 

.Where(x => x.Id ==  >>>> GUID<<<) 
? 

TBH i thought EF Core "visitor" will get 2 instances od DbUserId Record value objects as operands to build the query...

If he gets GUID and DbUserId then it is nothing surprising :-/

**Comment by montella1507** [comment]
> @montella1507 Generally speaking, EF Core doesn't support translations for custom operator overloading.

BTW it works when i add implicit conversion to GUID. So implicit conversions work as expected?
