### ISSUE TITLE
Microsoft.EntityFrameworkCore.Design 8.0.0-rc.2.23480.1 requires Microsoft.CodeAnalysis.CSharp.Workspaces = 4.5.0

### ISSUE THREAD

**Issue by ronymeyer** [dotnet/efcore#32070]
Microsoft.EntityFrameworkCore.Design 8.0.0-rc.2.23480.1 lists as dependency Microsoft.CodeAnalysis.CSharp.Workspaces >= 4.5.0

However I have referenced Microsoft.CodeAnalysis.CSharp.Workspaces 4.7.0 in a project and getting errors that Microsoft.EntityFrameworkCore.Design requires Microsoft.CodeAnalysis.Common 4.5.0.

MyMVC -> MyBusiness -> Microsoft.CodeAnalysis.CSharp.Scripting 4.7.0 -> Microsoft.CodeAnalysis.Common (= 4.7.0) 
MyMVC -> Microsoft.EntityFrameworkCore.Design 8.0.0-rc.2.23480.1 -> Microsoft.CodeAnalysis.CSharp.Workspaces 4.5.0 -> Microsoft.CodeAnalysis.Common (= 4.5.0).

Downgrading Microsoft.CodeAnalysis.CSharp.Workspaces from 4.7.0 to 4.5.0 works, but as the dependency is listed as >= 4.5.0 I would expect 4.7.0 to work as well.

**Comment by roji** [comment]
Try referencing Microsoft.CodeAnalysis.CSharp.Workspaces 4.7.0 directly in your project. This will upgrade the version for EF, but EF is compatible also with newer versions of Microsoft.CodeAnalysis.CSharp.Workspaces (it requires 4.5.0 as the minimum).

**Comment by ronymeyer** [comment]
Thank you. My issue was that I interpreted the error message and instructions wrong. I didn't directly reference Microsoft.CodeAnalysis.Common in the project where I referenced Microsoft.CodeAnalysis.CSharp.Scripting but in the project which used this project. Once directly referenced in the correct project (MyBusiness in the example above) the build worked.

**Comment by pocki** [comment]
I have a similar Issue, but Nuget upgrading to Microsoft.PowerShell.SDK 7.4.0 in same App is failing because of the pinned version in Microsoft.EntityFrameworkCore.Tools.

Normally I don't need to reference dependencies, as Nuget is resolving it if the packages are correct defined. 
Please fix the Nuget definition.

`NU1107: Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 4.8.0-2.final directly to project MyProject to resolve this issue. 
 MyProject -> Microsoft.PowerShell.SDK 7.4.0 -> Microsoft.PowerShell.Commands.Utility 7.4.0 -> Microsoft.CodeAnalysis.CSharp 4.8.0-2.final -> Microsoft.CodeAnalysis.Common (= 4.8.0-2.final) 
 MyProject -> Microsoft.EntityFrameworkCore.Tools 8.0.0 -> Microsoft.EntityFrameworkCore.Design 8.0.0 -> Microsoft.CodeAnalysis.CSharp.Workspaces 4.5.0 -> Microsoft.CodeAnalysis.Common (= 4.5.0).`

**Comment by sc-starman** [comment]
I have a similar issue in which I need to host EF core and Orleans together but Orleans packages use Microsoft.CodeAnalysis.Common v4.8.0 and EF tools (and Design) still use v4.5.0 where I encounter this exception even if I installed Microsoft.CodeAnalysis.Common  v4.8.0 directly to the project:

```
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'GetCollectionInitializerSymbolInfo' in type 'Microsoft.CodeAnalysis.CSharp.CSharpSemanticFacts' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'TryGetDisposeMethod' in type 'Microsoft.CodeAnalysis.CSharp.CSharpSemanticFactsService' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'get_Language' in type 'Microsoft.CodeAnalysis.CSharp.AddImport.CSharpAddImportsService' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'Convert' in type 'Microsoft.CodeAnalysis.CSharp.LanguageService.CSharpSyntaxKinds' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'SupportsTupleDeconstruction' in type 'Microsoft.CodeAnalysis.CSharp.LanguageService.CSharpSyntaxFacts' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'GetSimplifierOptions' in type 'Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'GetSimplifierOptions' in type 'Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplification' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Could not load type 'Microsoft.CodeAnalysis.Recommendations.AbstractRecommendationService`1' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=4.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
Could not load type 'Microsoft.CodeAnalysis.Options.Providers.IOptionProvider' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=4.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
Method 'GetFormattingOptions' in type 'Microsoft.CodeAnalysis.CSharp.Formatting.CSharpSyntaxFormatting' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'GetFormattingOptions' in type 'Microsoft.CodeAnalysis.CSharp.Formatting.CSharpSyntaxFormatting' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Could not load type 'Microsoft.CodeAnalysis.Options.Providers.IOptionProvider' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=4.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
Method 'GetIdeCodeStyleOptions' in type 'Microsoft.CodeAnalysis.CSharp.CodeStyle.CSharpCodeStyleService' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'get_GeneratorImpl' in type 'Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpCodeGenerationContextInfo' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'GetCodeGenerationOptions' in type 'Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpCodeGenerationService' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'CreateExplicitlyCastedLiteralValue' in type 'Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpFlagsEnumGenerator' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'MethodDeclaration' in type 'Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'AddLexicalClassifications' in type 'Microsoft.CodeAnalysis.CSharp.Classification.CSharpEditorClassificationService' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'AddLexicalClassifications' in type 'Microsoft.CodeAnalysis.CSharp.Classification.CSharpSyntaxClassificationService' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'SupportsTupleDeconstruction' in type 'Microsoft.CodeAnalysis.CSharp.LanguageService.CSharpSyntaxFacts' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'Convert' in type 'Microsoft.CodeAnalysis.CSharp.LanguageService.CSharpSyntaxKinds' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Could not load type 'AbstractRecommendationServiceRunner' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=4.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Composition.Hosting.ContainerConfiguration.<>c.<WithAssemblies>b__16_0(Assembly a)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.Create(IEnumerable`1 assemblies)
   at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.get_DefaultHost()
   at Microsoft.CodeAnalysis.AdhocWorkspace..ctor()
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper..ctor(ITypeMappingSource typeMappingSource)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
System.TypeLoadException: Method 'GetCollectionInitializerSymbolInfo' in type 'Microsoft.CodeAnalysis.CSharp.CSharpSemanticFacts' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
System.TypeLoadException: Method 'TryGetDisposeMethod' in type 'Microsoft.CodeAnalysis.CSharp.CSharpSemanticFactsService' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
System.TypeLoadException: Method 'get_Language' in type 'Microsoft.CodeAnalysis.CSharp.AddImport.CSharpAddImportsService' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
System.TypeLoadException: Method 'Convert' in type 'Microsoft.CodeAnalysis.CSharp.LanguageService.CSharpSyntaxKinds' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
System.TypeLoadException: Method 'SupportsTupleDeconstruction' in type 'Microsoft.CodeAnalysis.CSharp.LanguageService.CSharpSyntaxFacts' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
System.TypeLoadException: Method 'GetSimplifierOptions' in type 'Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
System.TypeLoadException: Method 'GetSimplifierOptions' in type 'Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplification' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
System.TypeLoadException: Could not load type 'Microsoft.CodeAnalysis.Recommendations.AbstractRecommendationService`1' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=4.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
System.TypeLoadException: Could not load type 'Microsoft.CodeAnalysis.Options.Providers.IOptionProvider' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=4.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
System.TypeLoadException: Method 'GetFormattingOptions' in type 'Microsoft.CodeAnalysis.CSharp.Formatting.CSharpSyntaxFormatting' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
System.TypeLoadException: Method 'GetFormattingOptions' in type 'Microsoft.CodeAnalysis.CSharp.Formatting.CSharpSyntaxFormatting' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
System.TypeLoadException: Could not load type 'Microsoft.CodeAnalysis.Options.Providers.IOptionProvider' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=4.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
System.TypeLoadException: Method 'GetIdeCodeStyleOptions' in type 'Microsoft.CodeAnalysis.CSharp.CodeStyle.CSharpCodeStyleService' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
System.TypeLoadException: Method 'get_GeneratorImpl' in type 'Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpCodeGenerationContextInfo' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
System.TypeLoadException: Method 'GetCodeGenerationOptions' in type 'Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpCodeGenerationService' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
System.TypeLoadException: Method 'CreateExplicitlyCastedLiteralValue' in type 'Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpFlagsEnumGenerator' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
System.TypeLoadException: Method 'MethodDeclaration' in type 'Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
System.TypeLoadException: Method 'AddLexicalClassifications' in type 'Microsoft.CodeAnalysis.CSharp.Classification.CSharpEditorClassificationService' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
System.TypeLoadException: Method 'AddLexicalClassifications' in type 'Microsoft.CodeAnalysis.CSharp.Classification.CSharpSyntaxClassificationService' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
System.TypeLoadException: Method 'SupportsTupleDeconstruction' in type 'Microsoft.CodeAnalysis.CSharp.LanguageService.CSharpSyntaxFacts' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
System.TypeLoadException: Method 'Convert' in type 'Microsoft.CodeAnalysis.CSharp.LanguageService.CSharpSyntaxKinds' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
System.TypeLoadException: Could not load type 'AbstractRecommendationServiceRunner' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=4.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
Unable to load one or more of the requested types.
Method 'GetCollectionInitializerSymbolInfo' in type 'Microsoft.CodeAnalysis.CSharp.CSharpSemanticFacts' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'TryGetDisposeMethod' in type 'Microsoft.CodeAnalysis.CSharp.CSharpSemanticFactsService' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'get_Language' in type 'Microsoft.CodeAnalysis.CSharp.AddImport.CSharpAddImportsService' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'Convert' in type 'Microsoft.CodeAnalysis.CSharp.LanguageService.CSharpSyntaxKinds' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'SupportsTupleDeconstruction' in type 'Microsoft.CodeAnalysis.CSharp.LanguageService.CSharpSyntaxFacts' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'GetSimplifierOptions' in type 'Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'GetSimplifierOptions' in type 'Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplification' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Could not load type 'Microsoft.CodeAnalysis.Recommendations.AbstractRecommendationService`1' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=4.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
Could not load type 'Microsoft.CodeAnalysis.Options.Providers.IOptionProvider' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=4.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
Method 'GetFormattingOptions' in type 'Microsoft.CodeAnalysis.CSharp.Formatting.CSharpSyntaxFormatting' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'GetFormattingOptions' in type 'Microsoft.CodeAnalysis.CSharp.Formatting.CSharpSyntaxFormatting' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Could not load type 'Microsoft.CodeAnalysis.Options.Providers.IOptionProvider' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=4.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
Method 'GetIdeCodeStyleOptions' in type 'Microsoft.CodeAnalysis.CSharp.CodeStyle.CSharpCodeStyleService' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'get_GeneratorImpl' in type 'Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpCodeGenerationContextInfo' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'GetCodeGenerationOptions' in type 'Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpCodeGenerationService' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'CreateExplicitlyCastedLiteralValue' in type 'Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpFlagsEnumGenerator' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'MethodDeclaration' in type 'Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'AddLexicalClassifications' in type 'Microsoft.CodeAnalysis.CSharp.Classification.CSharpEditorClassificationService' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'AddLexicalClassifications' in type 'Microsoft.CodeAnalysis.CSharp.Classification.CSharpSyntaxClassificationService' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'SupportsTupleDeconstruction' in type 'Microsoft.CodeAnalysis.CSharp.LanguageService.CSharpSyntaxFacts' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'Convert' in type 'Microsoft.CodeAnalysis.CSharp.LanguageService.CSharpSyntaxKinds' from assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Could not load type 'AbstractRecommendationServiceRunner' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=4.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
```

**Comment by ajcvickers** [comment]
Note for triage: This looks like a breaking change in the `Microsoft.CodeAnalysis.Common` package. That being said, it's not clear to me why we are still on 4.5. We should find the owner of this package and look into support/lifetime/breaks.

**Comment by ajcvickers** [comment]
@sc-starman Which Orleans package, specifically, has the dependency on 4.8?

**Comment by sc-starman** [comment]
> @sc-starman Which Orleans package, specifically, has the dependency on 4.8?

Microsoft.Orleans.Serialization 8.0.0 depends on Microsoft.CodeAnalysis.Common (>= 4.8.0)
