### ISSUE TITLE
Borked Owned Entities for PropertyChangingAndChanged

### ISSUE THREAD

**Issue by AlmightyLks** [dotnet/efcore#32168]
### Include your code

MRE can be found at https://github.com/AlmightyLks/EFC_PCAC_Owned_Borked

`ChangeTrackingStrategy.ChangingAndChangedNotifications` requires all entities that will be used with that context to implement INPC. However, when doing so with Owned Entities, and *setting* properties where the type is an Owned Entity, it cannot track them properly
```cs
var person = ctx.People.First();
person.IdCard = new IdCard() // IdCard is an Owned Entity
{
  FullName = "Another John Doe",
  Country = "Germany" 
};
```
and it throws an exception on SaveChanges() as follows:
```
System.InvalidOperationException: 'The original value for property 'IdCard.Country' cannot be accessed because it is not being tracked. Original values are not recorded for most properties of entities when the 'ChangingAndChangedNotifications' strategy is used. To access all original values, use a different change tracking strategy such as 'ChangingAndChangedNotificationsWithOriginalValues'.'
```

This means that to get around that, we have to explicitly set the object as modified, else it doesnt register it
```cs
ctx.Attach(person.IdCard).State = EntityState.Modified;
```
Which means, regardless of if it actually changed or not, we are forcing EFC to always update the property

### Include stack traces

```
System.InvalidOperationException: The original value for property 'IdCard.Country' cannot be accessed because it is not being tracked. Original values are not recorded for most properties of entities when the 'ChangingAndChangedNotifications' strategy is used. To access all original values, use a different change tracking strategy such as 'ChangingAndChangedNotificationsWithOriginalValues'.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.OriginalValues.GetValue(InternalEntityEntry entry, IProperty property)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.GetOriginalValue(IPropertyBase propertyBase)
   at Microsoft.EntityFrameworkCore.Update.UpdateEntryExtensions.GetOriginalProviderValue(IUpdateEntry updateEntry, IProperty property)
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.ColumnValuePropagator.RecordValue(IColumnMapping mapping, IUpdateEntry entry)
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.InitializeSharedColumns(IUpdateEntry entry, ITableMapping tableMapping, Boolean updating, Dictionary`2 columnMap)
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.GenerateColumnModifications()
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.<>c.<get_ColumnModifications>b__34_0(ModificationCommand command)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.get_ColumnModifications()
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.CreateCommandBatches(IEnumerable`1 commandSet, Boolean moreCommandSets, Boolean assertColumnModification, ParameterNameGenerator parameterNameGenerator)+MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.BatchCommands(IList`1 entries, IUpdateAdapter updateAdapter)+MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__107_0(DbContext _, ValueTuple`2 t)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Program.WeirdBehaviour() in .\EFC_PCAC_Owned_Borked\EFC_PCAC_Owned_Borked\Program.cs:line 36
   at Program.Main() in .\EFC_PCAC_Owned_Borked\EFC_PCAC_Owned_Borked\Program.cs:line 20
```

### Include provider and version information

EF Core version: 7.0.13
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.8.0 Preview 3.0

Issue persists, even in EFC8 preview versions

**Comment by ajcvickers** [comment]
Note for triage: this looks like a bug where we're trying to look up the original value for a navigation property.
