### ISSUE TITLE
EF Core 7 Temporal table save The expected type was 'System.DateTime' but the actual value was of type 'System.Int32'.

### ISSUE THREAD

**Issue by alwilton** [dotnet/efcore#32174]
Please forgive me for being unable to provide a simple example of this bug in that it seems to be data dependent on a large project and I am guessing at the issue. It is my thought that even if nothing can be done immediately on this issue, it is better to report it so that at least it is known that someone ran into this issue.

It appears that with certain data EF generates a History update that converts the DateTime to an Interger - or at least SQL Server thinks so.

I have a table that is setup and designated as a temporal table. Everything works quite well. However, on one data row EF Core would not update the data throwing the error

```
 ---> System.InvalidOperationException: An error occurred while reading a database value for property 'TableName.PeriodEnd'. The expected type was 'System.DateTime' but the actual value was of type 'System.Int32'.
 ---> System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.DateTime'.
   at Microsoft.Data.SqlClient.SqlBuffer.get_DateTime()
   at Microsoft.Data.SqlClient.SqlDataReader.GetDateTime(Int32 i)
   at lambda_method7311(Closure, DbDataReader, Int32)
   --- End of inner exception stack trace ---
   at lambda_method7311(Closure, DbDataReader, Int32)
   at Microsoft.EntityFrameworkCore.RelationalPropertyExtensions.GetReaderFieldValue(IProperty property, RelationalDataReader relationalReader, Int32 ordinal, Boolean detailedErrorsEnabled)
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.PropagateResults(RelationalDataReader relationalReader)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetAsync(Int32 startCommandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at FsCms.Ef.Context.BfeContext.SaveChangesAsync(CancellationToken cancellationToken) in C:\Users\Al\source\Workspaces\CMS\FSCMS\FSCMS.EF\Context\ContextRules.cs:line 115
```
The Period data prior to the error was
```
PeriodEnd                   PeriodStart
2023-10-16 16:19:35.0505645	2023-10-05 14:25:28.7517030
2023-10-16 16:19:55.2852923	2023-10-16 16:19:35.0505645
2023-10-16 16:22:02.9437476	2023-10-16 16:19:55.2852923
2023-10-18 19:30:55.8458894	2023-10-16 16:22:02.9437476
2023-10-18 19:30:55.9396408	2023-10-18 19:30:55.8458894
2023-10-26 15:08:22.3677556	2023-10-18 19:30:55.9396408
2023-10-26 15:08:33.0554288	2023-10-26 15:08:22.3677556
2023-10-26 15:08:43.9306082	2023-10-26 15:08:33.0554288
2023-10-26 15:08:52.6338726	2023-10-26 15:08:43.9306082
2023-10-26 15:08:52.6494962	2023-10-26 15:08:52.6338726
2023-10-26 15:11:54.2149219	2023-10-26 15:08:52.6494962
2023-10-26 15:12:04.5744578	2023-10-26 15:11:54.2149219
2023-10-27 16:55:55.8879533	2023-10-26 15:12:04.5744578
2023-10-27 16:58:37.1241996	2023-10-27 16:55:55.8879533
2023-10-27 17:04:09.4479537	2023-10-27 16:58:37.1241996
```

I was only able to update the data with direct SQL. After the update the Period data was
```
PeriodEnd	PeriodStart
2023-10-16 16:19:35.0505645	2023-10-05 14:25:28.7517030
2023-10-16 16:19:55.2852923	2023-10-16 16:19:35.0505645
2023-10-16 16:22:02.9437476	2023-10-16 16:19:55.2852923
2023-10-18 19:30:55.8458894	2023-10-16 16:22:02.9437476
2023-10-18 19:30:55.9396408	2023-10-18 19:30:55.8458894
2023-10-26 15:08:22.3677556	2023-10-18 19:30:55.9396408
2023-10-26 15:08:33.0554288	2023-10-26 15:08:22.3677556
2023-10-26 15:08:43.9306082	2023-10-26 15:08:33.0554288
2023-10-26 15:08:52.6338726	2023-10-26 15:08:43.9306082
2023-10-26 15:08:52.6494962	2023-10-26 15:08:52.6338726
2023-10-26 15:11:54.2149219	2023-10-26 15:08:52.6494962
2023-10-26 15:12:04.5744578	2023-10-26 15:11:54.2149219
2023-10-27 16:55:55.8879533	2023-10-26 15:12:04.5744578
2023-10-27 16:58:37.1241996	2023-10-27 16:55:55.8879533
2023-10-27 17:04:09.4479537	2023-10-27 16:58:37.1241996
2023-10-27 17:57:53.3758066	2023-10-27 17:04:09.4479537
2023-10-27 17:59:35.7369219	2023-10-27 17:57:53.3758066
2023-10-27 18:01:47.3329532	2023-10-27 17:59:35.7369219
2023-10-27 18:03:10.1312256	2023-10-27 18:01:47.3329532
2023-10-27 18:03:34.6316066	2023-10-27 18:03:10.1312256
2023-10-27 18:04:40.4767947	2023-10-27 18:03:34.6316066
```

EF Core version: 7.0.11
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: Windows Server 2012
IDE: Visual Studio 2022 17.4

**Comment by ajcvickers** [comment]
@alwilton There is nothing we can do here without a repro.

**Comment by alwilton** [comment]
Arthur, I understand - but at least you now know this has happened a least once.
