### ISSUE TITLE
Compiled model with parameterized value converters

### ISSUE THREAD

**Issue by majbo** [dotnet/efcore#32280]
## Ask a question

I tried to create a compiled model of my DbContext but get the following error: 

> The property 'Foo.Bar' has a value comparer configured using a ValueComparer instance. Instead, create types that inherit from ValueConverter and ValueComparer and use 'HasConversion=<ConverterType, ComparerType=>()' or 'HasConversion(Type converterType, Type comparerType)' to configure the value converter and comparer.

Unfortunately, I can't use the mentioned `HasConversion` calls because my converter needs specifiy JsonSerializerOptions that are configured during startup. Is there still a way to use the compiled model?

code: 

```C#
builder.Property(p => p.Bar).HasConversion(
p => JsonSerializer.Serialize(p, serializerOptions),
s => JsonSerializer.Deserialize<Foo>(s, serializerOptions));
```

stack trace:

```
The property 'Foo.Bar' has a value comparer configured using a ValueComparer instance. Instead, create types that inherit from ValueConverter and ValueComparer and use 'HasConversion=<ConverterType, ComparerType=>()' or 'HasConversion(Type converterType, Type comparerType)' to configure the value converter and comparer.
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpRuntimeModelCodeGenerator.Create(IProperty property, Dictionary`2 propertyVariables, CSharpRuntimeAnnotationCodeGeneratorParameters parameters)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpRuntimeModelCodeGenerator.CreateEntityType(IEntityType entityType, IndentedStringBuilder mainBuilder, IndentedStringBuilder methodBuilder, SortedSet`1 namespaces, String className, Boolean nullable)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpRuntimeModelCodeGenerator.GenerateEntityType(IEntityType entityType, String namespace, String className, Boolean nullable)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpRuntimeModelCodeGenerator.GenerateModel(IModel model, CompiledModelCodeGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CompiledModelScaffolder.ScaffoldModel(IModel model, String outputDir, CompiledModelCodeGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.Optimize(String outputDir, String modelNamespace, String contextTypeName)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OptimizeContextImpl(String outputDir, String modelNamespace, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OptimizeContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)

```

EF Core version: 7.0.9
Database provider: Microsoft.EntityFrameworkCore.SqlLite
Target framework: .NET 7.0
Operating system: Windows 11

**Comment by AndriySvyryd** [comment]
The compiled model needs to be built on startup independently of any other part of the application, so it doesn't support any dynamic behavior like this.
