### ISSUE TITLE
One or more errors occurred. (Attempting to JIT compile method '(wrapper dynamic-method) 

### ISSUE THREAD

**Issue by Sheetalpr** [dotnet/efcore#32318]
Hi,

I am currently working on migration of xamarion.ios to .net-ios. I am able to build application in simulator whereas app is getting crashed in iphone. Tried adding Linkers.xml as mentioned in below issue. 

https://github.com/xamarin/xamarin-macios/issues/3394

Also tried below solution.

https://stackoverflow.com/questions/53521581/xamarin-ios-linker-issue.

I am using the latest version of automapper(12.0.1)

Stack trace from crash:

System.AggregateException: One or more errors occurred. (Attempting to JIT compile method '(wrapper dynamic-method) System.Collections.Generic.List`1<MyApp.Models.Index> object:Thunk1ret_List`1_List`1_List`1_ResolutionContext (System.Func`2<object[], object>,System.Collections.Generic.List`1<MyApp.Models.SM_Mob_IndexProjects>,System.Collections.Generic.List`1<MyApp.Models.IndexProjectsBO>,AutoMapper.ResolutionContext)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
) ---> System.ExecutionEngineException: Attempting to JIT compile method '(wrapper dynamic-method) System.Collections.Generic.List`1<MyApp.Models.IndexProjectsBO> object:Thunk1ret_List`1_List`1_List`1_ResolutionContext (System.Func`2<object[], object>,System.Collections.Generic.List`1<MyApp.Models.SM_Mob_IndexProjects>,System.Collections.Generic.List`1<MyApp.Models.IndexProjectsBO>,AutoMapper.ResolutionContext)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.

  at at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure, Boolean allowClosed)
  at at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure)
  at at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method)
  at at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type , Object )
  at at System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(Type , Func`2 )
  at at System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegate(Type , Func`2 )
  at at System.Linq.Expressions.Interpreter.LightLambda.MakeDelegate(Type )
  at at System.Linq.Expressions.Interpreter.LightDelegateCreator.CreateDelegate(IStrongBox[] )
  at at System.Linq.Expressions.Interpreter.LightDelegateCreator.CreateDelegate()
  at at System.Linq.Expressions.LambdaExpression.Compile()
  at at AutoMapper.MapperConfiguration.<.ctor>g__CompileExecutionPlan|20_2(MapRequest mapRequest)
  at at AutoMapper.Internal.LockingConcurrentDictionary`2.<>c__DisplayClass2_1[[AutoMapper.Internal.MapRequest, 
Target framework: .Net 7.0
Operating system: macos
IDE: (e.g. Visual Studio 2022 17.6.3)

Any help would be appreciated .

**Comment by Sheetalpr** [comment]
yes right, I am working on .net-ios and .net-android. I guess this issue is related to automapper. Currently I am using latest Automapper(12.0.1) and I found that mapper.createMap property is deprecated.  

I made changes as per latest version i.e., 

 **var config = new MapperConfiguration(cfg =>     cfg.CreateMap<Source, Dest>();})
  IMapper mapper = config.CreateMapper(); 
var source = new Source(); 
 var dest = mapper.Map<Source, Dest>(source);**


Now when i am running application in simulator it is working fine, working fine in .net-android solution but app is crashing in iphone(ios 17) with above mentioned exception.

I tried adding the linker.xml to ios solution as mentioned in https://mallibone.com/post/xamarin-automapper#getting-setup
, but no luck
