### ISSUE TITLE
Did Contains stop working on empty list in EF Core 8?

### ISSUE THREAD

**Issue by jozseftuska** [dotnet/efcore#32375]
## Question

Did Contains stop working on empty list in EF Core 8?
My database server is Microsoft SQL Server 2017, compatibility level is set to 140. A query that was working before on .NET6  and EF Core 6 is no longer functioning. 
Do we need to check now when calling contains if the list is empty?

### Code
Edit - Full code:  [repository](https://github.com/jozseftuska/ContainsBugReproduction)
The debug view of the query will look like this:

```C#
    ...
    .Where(x => List<int> {  }.Contains(x.Key))
```

### Stack traces
```
The LINQ expression '[Microsoft.EntityFrameworkCore.Query.InlineQueryRootExpression]' could not be translated. Additional information: Empty collections are not supported as inline query roots. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.TranslateSubquery(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TranslateInternal(Expression expression, Boolean applyDefaultTypeMapping)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression, Boolean applyDefaultTypeMapping)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateExpression(Expression expression, Boolean applyDefaultTypeMapping)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateLambdaExpression(ShapedQueryExpression shapedQueryExpression, LambdaExpression lambdaExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateWhere(ShapedQueryExpression source, LambdaExpression predicate)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__67`1.MoveNext()
```

### Provider and version information

EF Core version: 8.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.8

**Comment by roji** [comment]
@jozseftuska I can't repro this - see the below LINQ query. I need to see an actual code sample here - posting a debug view of a query and a stack trace are not sufficient. Please post a minimal, runnable code sample, or tweak the below sample to make it fail.

<details>
<summary>Attempted repo</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

_ = ctx.Blogs.Where(x => new List<int> { }.Contains(x.Id)).ToList();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class Blog
{
    public int Id { get; set; }
    public string? Name { get; set; }
}
```

</details>

**Comment by JinHuihui1234** [comment]
I ran into a similar error.
Here is all my code. It works in EF7 but fails in EF8

    internal class Program
    {
        static void Main(string[] args)
        {
            List<Guid> ids = new List<Guid>();

            Expression<Func<Project, bool>> expression1 = e => ids.Contains(e.Id);
            Expression<Func<Project, bool>> expression2 = CreatePredicate(ids);

            using (MyContext context = new MyContext())
            {
                var result1 = context.Projects.Where(expression1).ToList(); // Right
                var result2 = context.Projects.Where(expression2).ToList(); // Error
            }
        }

        private static Expression<Func<Project, bool>> CreatePredicate(IEnumerable<Guid> ids)
        {
            ParameterExpression parameter = Expression.Parameter(typeof(Project));
            MemberExpression member = Expression.Property(parameter, "Id");
            Expression constant = Expression.Constant(ids.ToList());
            MethodCallExpression methodCall = Expression.Call(constant, typeof(List<Guid>).GetMethod(nameof(List<Guid>.Contains)), member);
            return Expression.Lambda<Func<Project, bool>>(methodCall, parameter);
        }
    }

    class MyContext : DbContext
    {
        public DbSet<Project> Projects { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Data Source=219.146.241.102;Initial Catalog=ZZZ;User Id=sa;Password=HDQAeU!rqDszGkV!;MultipleActiveResultSets=True;TrustServerCertificate=True;");
            optionsBuilder.LogTo(Console.WriteLine);
            optionsBuilder.EnableSensitiveDataLogging();
            optionsBuilder.EnableDetailedErrors();
        }
    }

    public class Project
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
    }

The exception is:
System.InvalidOperationException:“The LINQ expression '[Microsoft.EntityFrameworkCore.Query.InlineQueryRootExpression]' could not be translated. Additional information: Empty collections are not supported as inline query roots. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.”

**Comment by roji** [comment]
Thanks for the repros! I'm currently away but I'll take a look at this next week for sure.

**Comment by roji** [comment]
Minimal repro is any composing on top of an empty inline array:

```c#
_ = ctx.Blogs.Where(b => new int[] { }.Contains(b.Id)).ToList();
```

Note that this repro doesn't work for List because of #32413.

**Comment by roji** [comment]
Reopening to consider servicing.

**Comment by PieterjanDeClippel** [comment]
https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/breaking-changes#contains-in-linq-queries-may-stop-working-on-older-sql-server-versions
