### ISSUE TITLE
[EF Core 8] InvalidCastException when adding Entity with nullable PK: Unable to cast object of type 'System.Func`3[System.Nullable`1[System.Int32],System.Nullable`1[System.Int32],System.Boolean]' to type 'System.Func`3[System.Int32,System.Int32,System.Boolean]'.

### ISSUE THREAD

**Issue by ennemoser-mobile** [dotnet/efcore#32387]
Hello there,

after upgrading from EFC 7.0.14 to ERF 8.0.0 we are receiving the following exception:

```
InvalidCastException: Unable to cast object of type 'System.Func`3[System.Nullable`1[System.Int32],System.Nullable`1[System.Int32],System.Boolean]' to type 'System.Func`3[System.Int32,System.Int32,System.Boolean]'.

at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMapFactoryFactory.Create(IKey key)
   at Microsoft.EntityFrameworkCore.Metadata.RuntimeKey.<>c.<Microsoft.EntityFrameworkCore.Metadata.Internal.IRuntimeKey.GetIdentityMapFactory>b__30_0(RuntimeKey key)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Metadata.RuntimeKey.Microsoft.EntityFrameworkCore.Metadata.Internal.IRuntimeKey.GetIdentityMapFactory()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetOrCreateIdentityMap(IKey key)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey, Nullable`1 fallbackState)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Add(TEntity entity)
... our Code
```

The exception occurs in the EFC Add methode:
```
TestEntity testEntity = new();
dbContext.TestEntities.Add( testEntity );
dbContext.SaveChanges();
```

The TestEntity has a nullable int as a PK:

```
    [Table( "TestEntity" )]
    public sealed class TestEntity 
    {
        [Key]
        [Column( "TestEntity_Id" )]
        [DatabaseGenerated( DatabaseGeneratedOption.Identity )]
        public int? TestEntityId { get; set; }
        
        // other fields removed for simplicity
    }
```

Replacing int? with int and recompiling the DB Model seems to fix the problem.

Thank you!

### Include provider and version information

EF Core version: 8.0.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: .NET 8.0.0 x64
Operating system: Windows 11 23H2
IDE: Visual Studio 2022 17.8.1

**Comment by ennemoser-mobile** [comment]
Similiar error here from an old build: https://github.com/dotnet/efcore/issues/30489
