### ISSUE TITLE
.NET 8 migration on .NET MAUI Blazor Hybrid App causes exception: The type initializer for "<Module>" threw an exception.

### ISSUE THREAD

**Issue by Ccry11** [dotnet/efcore#32384]
#### ApplicationDbContext.cs
```C#
using MauiApp1.Model;
using Microsoft.EntityFrameworkCore;
using System.Reflection;

namespace MauiApp1.Context
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext() { }
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> contextOptions)
            : base(contextOptions)
        {
        }

        public DbSet<Person> People { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) { }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());
        }
    }
}
```

#### MauiProgram.cs
```C#
using MauiApp1.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace MauiApp1
{
    public static class MauiProgram
    {
        public static MauiApp CreateMauiApp()
        {
            var builder = MauiApp.CreateBuilder();
            builder
                .UseMauiApp<App>()
                .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                });

            builder.Services.AddMauiBlazorWebView();

#if DEBUG
    		builder.Services.AddBlazorWebViewDeveloperTools();
    		builder.Logging.AddDebug();
#endif

            builder.Services.AddDbContext<ApplicationDbContext>(
                options =>
                    options.UseSqlite(
                        "Data Source=C:\\Users\\USER\\Documents\\Test.db;Cache=Shared"
                    )
                );

            builder.Services.AddScoped<DbContext, ApplicationDbContext>();

            return builder.Build();
        }
    }
}

```

#### Person.cs
```C#
namespace MauiApp1.Model
{
    public class Person
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
```

#### PersonConfiguration.cs
```C#
using MauiApp1.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace MauiApp1.EntityConfiguration
{
    class PersonConfiguration : IEntityTypeConfiguration<Person>
    {
        public void Configure(EntityTypeBuilder<Person> builder)
        {
            builder.HasKey(o => o.Id);
            builder.Property(t => t.FirstName).IsRequired(false);
            builder.Property(t => t.LastName).IsRequired(false);
        }
    }
}

```
#### MauiApp1.csproj
```xml
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
        <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="$(MauiVersion)" />
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.0" />
```
### Stack traces - Vebose output
By runing the command: `dotnet ef migrations add FirstMigration --project MauiApp1 --context ApplicationDbContext --verbose` the following error occurs:

```
Using assembly 'MauiApp1'.
Using startup assembly 'MauiApp1'.
Using application base 'C:\Users\USER\source\repos\MauiApp1\MauiApp1\bin\Debug\net8.0-windows10.0.19041.0\win10-x64'.
Using working directory 'C:\Users\USER\source\repos\MauiApp1\MauiApp1'.
Using root namespace 'MauiApp1'.
Using project directory 'C:\Users\USER\source\repos\MauiApp1\MauiApp1\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'MauiApp1'...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'ApplicationDbContext'.
Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create a 'DbContext' of type 'ApplicationDbContext'. The exception 'The type initializer for '<Module>' threw an exception.' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
 ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'WinRT.ActivationFactory`1' threw an exception.
 ---> System.Runtime.InteropServices.COMException (0x80040154): Interfaccia non registrata. (0x80040154 (REGDB_E_CLASSNOTREG))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
   at WinRT.ActivationFactory`1..ctor()
   at WinRT.ActivationFactory`1..cctor()
   --- End of inner exception stack trace ---
   at WinRT.ActivationFactory`1.ActivateInstance[I]()
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentInitializeOptions..ctor()
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManagerCS.AutoInitialize.get_Options() in C:\Users\USER\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\include\DeploymentManagerAutoInitializer.cs:line 44
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManagerCS.AutoInitialize.AccessWindowsAppSDK() in C:\Users\USER\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\include\DeploymentManagerAutoInitializer.cs:line 30
   at .cctor()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass20_5.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to create a 'DbContext' of type 'ApplicationDbContext'. The exception 'The type initializer for '<Module>' threw an exception.' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
```

### Include provider and version information

EF Core version: 8.0.0
Database provider: SqlLite
Target framework: .NET 8.0
Operating system: Windows 10 22H2 Build 19045
IDE: Visual Studio 2022 17.8.1
dotnet-ef CLI: 8.0.0

**Comment by wesleyscaldwell** [comment]
I'm having the same issue, did you manage to find a workaround? 

I tried the device factory option also, and that didn't resolve it.

```
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Using DbContext factory 'DeviceContextFactory'.
Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create a 'DbContext' of type 'DeviceContext'. The exception 'The type initializer for '<Module>' threw an exception.' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
 ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'WinRT.ActivationFactory`1' threw an exception.
 ---> System.Runtime.InteropServices.COMException (0x80040154): Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
   at WinRT.ActivationFactory`1..ctor()
   at WinRT.ActivationFactory`1..cctor()
   --- End of inner exception stack trace ---
   at WinRT.ActivationFactory`1.ActivateInstance[I]()
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentInitializeOptions..ctor()
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManagerCS.AutoInitialize.get_Options() in C:\Users\Wesley\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\include\DeploymentManagerAutoInitializer.cs:line 44
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManagerCS.AutoInitialize.AccessWindowsAppSDK() in C:\Users\Wesley\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\include\DeploymentManagerAutoInitializer.cs:line 30
   at .cctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.GetActivationInfo(RuntimeType rt, & pfnAllocator, Void*& vAllocatorFirstArg, & pfnCtor, Boolean& ctorIsPublic)
   at System.RuntimeType.ActivatorCache..ctor(RuntimeType rt)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContextFromFactory(Type factory, Type contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass20_3.<FindContextTypes>b__9()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

**Comment by wesleyscaldwell** [comment]
Ok, I found a work around. And i'm going to be up front and honest, I found this by luck and have no clue what it is doing or why it works.

I added this to the csproj and then it added the migration. 

```<WindowsAppSdkDeploymentManagerInitialize>false</WindowsAppSdkDeploymentManagerInitialize>```

[https://github.com/dotnet/maui/issues/12080#issuecomment-1398635826](url)

**Comment by Ccry11** [comment]
@wesleyscaldwell Thank you very much!
I confirm that in this way the migration is added and then it can also be applied.
I have found a comment about that property: https://github.com/microsoft/microsoft-ui-xaml/issues/8182#issuecomment-1430538408 .
I hope that someone can understand why this issue occurs and propose a proper way to fix it

**Comment by M-Nesti** [comment]
@wesleyscaldwell : Thank you so much! Investigating this issue took me quite some time, your workaround helped! God bless you

**Comment by evolcano** [comment]
I have the same error during debug., and cost few days: 

> System.TypeInitializationException
>   HResult=0x80131534
>   Message=The type initializer for 'WinRT.ActivationFactory`1' threw an exception.
>   Source=Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection
>   StackTrace:
>    at WinRT.ActivationFactory`1.ActivateInstance[I]()
>    at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentInitializeOptions..ctor()
>    at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManagerCS.AutoInitialize.get_Options() in C:\Users\Volca\.nuget\packages\microsoft.windowsappsdk\1.5.240311000\include\DeploymentManagerAutoInitializer.cs:line 44
> 
>   This exception was originally thrown at this call stack:
>     [External Code]
> 
> Inner Exception 1:
> COMException: Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))

The error is raised form Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentInitializeOptions:
```
    public DeploymentInitializeOptions()
        : this(WinRT.ActivationFactory<DeploymentInitializeOptions>.ActivateInstance<IUnknownVftbl>())
    {
        ComWrappersSupport.RegisterObjectForInterface(this, ThisPtr);
        ComWrappersHelper.Init(_inner, addRefFromTrackerSource: false);
    }
```
I think maybe WinRT.ActivationFactory cann't be initialized. It is said MSIX is running in a container which has some limitation in [this artical](https://learn.microsoft.com/en-us/windows/apps/package-and-deploy/), such as:

- NT Service isn't possible
- privileged/elevated access is restricted

So I unchecked project pproperties of Packaging:
![image](https://github.com/dotnet/efcore/assets/18514981/bfa794e3-c9f6-4b9d-83e1-c34e0a8417ec)

Debug can go again.  But I still have questions:

1. If this is the reason of error?
2. Why  type initializer for 'WinRT.ActivationFactory` throw error?
3. how can I use MSIX to abtain advantages?

**Comment by SbiCA** [comment]
This is really tripping people off (our team spent a few hours on figuring it out) I'm pretty surprise this still is an issue :(  The workaround helps but it forces you down a certain solution path e.g. own assembly and other troubles because that in combination with ef migrations is a different story. not sure if this was mentioned somewhere as a separate issue but we had to move our migration project to a dedicated assembly in order to make it work

**Comment by AndriySvyryd** [comment]
> not sure if this was mentioned somewhere as a separate issue but we had to move our migration project to a dedicated assembly in order to make it work

[Migrations projects](https://learn.microsoft.com/ef/core/managing-schemas/migrations/projects?tabs=dotnet-core-cli) is the recommended approach in general.

We will [show a warning when the tools are used with a platform-specific app](https://github.com/dotnet/efcore/issues/32835)

**Comment by SbiCA** [comment]
> > not sure if this was mentioned somewhere as a separate issue but we had to move our migration project to a dedicated assembly in order to make it work
> 
> [Migrations projects](https://learn.microsoft.com/ef/core/managing-schemas/migrations/projects?tabs=dotnet-core-cli) is the recommended approach in general.
> 
> We will [show a warning when the tools are used with a platform-specific app](https://github.com/dotnet/efcore/issues/32835)

Thx @AndriySvyryd ! this will help a lot since when having all the context at least one is able to relate to the issue. IMHO I'd still like to see all in one assembly (for simple applications and less "projects") but I can see why this is tons of work for you guys and probably not worth the effort if there isn't enough demand.

**Comment by LaurensVdb** [comment]
I  faced the same issue and i found a workaround.
Not sure if this is the right place for a workaround.

This is what i did. 

- Create a regular class library (not a .net maui class library) 
-Added the nuget packages for **entityframeworkcore.sqlite** and **entityframeworkcore.tools**

i created a new db context class 

```
public class DatabaseContext : DbContext
{
    public DbSet<Exercise>  Exercises { get; set; }
    

  
    public DatabaseContext()
    {
        
    }
    
    //use for DI!
    public DatabaseContext(DbContextOptions<DatabaseContext> options)
        : base(options)
    {

    
    }
    

    //use for migration!
   protected override void OnConfiguring(DbContextOptionsBuilder options)
        => options.UseSqlite();

}
```

- I then used the following command in the package console: **Add-Migration Initial**. A new migration is added in the folder migrations
- In MauiProgram.cs add the following 

```
  builder.Services.AddDbContext<DatabaseContext>(options => {
      var path = Path.Combine(FileSystem.AppDataDirectory, "exercise.db");
      options.UseSqlite($"Filename={path}"); 
  
  }, ServiceLifetime.Singleton);
```


After all this i could run ef core in .net maui.

**Comment by monkeyK1n9** [comment]
> I faced the same issue and i found a workaround. No need for `<WindowsAppSdkDeploymentManagerInitialize>false</WindowsAppSdkDeploymentManagerInitialize>`
> 
> This is what i did.
> 
> * Create a regular class library (not a .net maui class library it seems impossible to get it working with EF Core migrations)
>   -Added the nuget packages for **entityframeworkcore.sqlite** and **entityframeworkcore.tools**
> 
> i created a new db context class
> 
> ```
> public class DatabaseContext : DbContext
> {
>     public DbSet<Exercise>  Exercises { get; set; }
>     
> 
>   
>     public DatabaseContext()
>     {
>         
>     }
>     
>     //use for DI!
>     public DatabaseContext(DbContextOptions<DatabaseContext> options)
>         : base(options)
>     {
> 
>     
>     }
>     
> 
>     //use for migration!
>    protected override void OnConfiguring(DbContextOptionsBuilder options)
>         => options.UseSqlite();
> 
> }
> ```
> 
> * I then used the following command in the package console: **Add-Migration Initial**. A new migration is added in the folder migrations. Make sure in the package console the default project is the new class library!
> * In MauiProgram.cs add the following
> 
> ```
>   builder.Services.AddDbContext<DatabaseContext>(options => {
>       var path = Path.Combine(FileSystem.AppDataDirectory, "exercise.db");
>       options.UseSqlite($"Filename={path}"); 
>   
>   }, ServiceLifetime.Singleton);
> ```
> 
> After all this i could run ef core in .net maui.

This solved my issue.

Just to add some more context to this:
- Your datacontext is in your class library
- You add the library reference to your maui project

**Comment by mujicn** [comment]
I would add one if statement to that solution:

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlite();
        }
    }

I think the Sqlite options (Filename) are not set properly otherwise.
