### ISSUE TITLE
Lazy loader throwing invalid operation exceptions

### ISSUE THREAD

**Issue by MoazAlkharfan** [dotnet/efcore#32390]
### Include your code

Assuming it's because of concurrent access to memory cached entities after they have been loaded and the DbContext has already been disposed.

Reproduction repository: https://github.com/MoazAlkharfan/efcore-issue-32390

Places to check:
- `TagsCacheService` fetch data from db
- `Program` mapped `/` endpoint
- `ServerRequest` do get requests on the `/` endpoint

### Include stack traces

For the first:

https://github.com/dotnet/efcore/blob/141740fdcac47b1f015f280840359468b8c818cc/src/EFCore/Infrastructure/Internal/LazyLoader.cs#L181-L183

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.LazyLoader.Load(Object entity, String navigationName)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
```

https://github.com/dotnet/efcore/blob/141740fdcac47b1f015f280840359468b8c818cc/src/EFCore/Infrastructure/Internal/LazyLoader.cs#L185-L195

For the second:
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.LazyLoader.Load(Object entity, String navigationName)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
```

### Include provider and version information

EF Core version: 8.0
Database provider: (Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (.NET 8.0)
Operating system: Windows/Linux
IDE: (Visual Studio 2022 17.9)

**Comment by MoazAlkharfan** [comment]
@ajcvickers 
Reproduction repository: https://github.com/MoazAlkharfan/efcore-issue-32390

Places to check:
- `TagsCacheService` fetch data
- `Program` mapped `/` endpoint
- `ServerRequest` do get requests on the `/` endpoint
