### ISSUE TITLE
EF8 SQL: "Incorrect syntax near the keyword 'WITH'." when joining tables with list.Contains in Where

### ISSUE THREAD

**Issue by mwrothbe-intc** [dotnet/efcore#32400]
### Notes

- Queries worked with EF7.  Upgrading to EF8 causes exception.
- Re-scaffolding DB using EF8 doesn't change behavior.
- Updated Microsoft.Data.SqlClient. to 5.1.2, no change.

### Example Code
```
var controller = _appServices.GetRequiredService<foobarContext>();
var test = await controller.Foos
    .Where(foo=> listString.Contains(foo.Sn))
    .Join(controller.Bars, 
        foo => foo.Id, 
        bar => facr.Id, 
        (foo, bar) => new { Foo = foo, Bar = bar })
    .ToListAsync();
```
or
```
var controller = _appServices.GetRequiredService<foobarContext>();
var testQuery = from foo in controller.Foos
                join bar in controller.Bars on foo.Id equals bar.Id
                where listString.Contains(foo.Sn)
                select bar;
var test = testQuery.ToList();
```

### Message
```
Incorrect syntax near the keyword 'WITH'.
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
```
### Stack Trace

```
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteReaderAsync>d__18.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteReaderAsync>d__18.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.<InitializeReaderAsync>d__21.MoveNext()
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.<MoveNextAsync>d__20.MoveNext()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__67`1.MoveNext()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__67`1.MoveNext()
   at 
```

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: Net8.0
Operating system: Win11
IDE: Visual Studio 2022 17.8

**Comment by ajcvickers** [comment]
@mwrothbe-intc Please see https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/breaking-changes#sqlserver-contains-compatibility. If that doesn't help, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by mwrothbe-intc** [comment]
Thank you @ajcvickers !  Using .UseCompatibilityLevel(120) appears to work.

**Comment by janseris** [comment]
Just adding for future searchers that I get it happening on this method with SQL Server 2012

```
/// <summary>
/// Note: this will fail for 2100+ <paramref name="IDs"/> because of SqlClient parameter count limit
/// </summary>
private async Task<List<TC_USER_RIGHT>> GetInternal(List<int> IDs)
{
    using var db = DB;
    var query = from row in db.C_USER_RIGHT where IDs.Contains(row.ID) select row;
    var items = await query.ToListAsync();
    return items;
}
```
