### ISSUE TITLE
Obsolete Attribute breaks  EF core

### ISSUE THREAD

**Issue by ChristianSauer** [dotnet/efcore#32417]
I have a working EF Core Application, but one of the fields is not really needed anymore. Developers should not use it anymore. So I marked this field as `[Obsolete]`. But suddenly my query broke with a NullreferenceException. Removing Obsolete fixes this bug, but honestly this is super surprising and makes Obsolete a time bomb.

### Include your code

To fix any bug we must first reproduce it. To make this possible, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing.

It is often impossible for us to reproduce a bug when working with only code snippets since we have to guess at the missing code. 

Use triple-tick code fences for any posted code. For example:

```C#
public class KeyDb
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// OBSOLETE DO NOT USE
    /// </summary>
    [Column("bookingid")]
    [Obsolete]
    public long? BookingId { get; set; }
}

context.Keys.Add(new KeyDb(){Id = 1, BookingId = null});
context.Keys.Where(x => x.Id == 1).First() <-- Crashes
```

### Include stack traces

```
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
   at Microsoft.Data.SqlClient.SqlBuffer.get_Int64()
   at Microsoft.Data.SqlClient.SqlDataReader.GetInt64(Int32 i)
   at lambda_method1651(Closure, QueryContext, DbDataReader, ResultContext, SplitQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
```

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: (e.g. .NET 8.0)
Operating system: Windows 7
IDE: Rider

**Comment by ChristianSauer** [comment]
Ok, that way my error
