### ISSUE TITLE
Does EF Core support collection expressions?

### ISSUE THREAD

**Issue by Newmski** [dotnet/efcore#32475]
## Ask a question

Does EF Core support the use of collection expressions? Previously, I would instantiate a collection with a `new` statement e.g.

`public required IReadOnlyList<Permission> Permissions { get; init; } = new List<Permission>();`

In .NET 8 I would like to use collection expressions e.g.

`public required IReadOnlyList<Permission> Permissions { get; init; } = [];`

However, this results in a `System.NotSupportedException: Collection was of a fixed size` exception.

### Include your code

[CollectionExpressionsDemo.zip](https://github.com/dotnet/efcore/files/13523347/CollectionExpressionsDemo.zip)

### Include stack traces

```
An exception occurred while iterating over the results of a query for context type 'CollectionExpressionsDemo.ApplicationDbContext'.
      System.NotSupportedException: Collection was of a fixed size.
         at System.SZArrayHelper.Add[T](T _)
         at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrICollectionAccessor`3.AddStandalone(Object collection, Object value)
         at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrICollectionAccessor`3.Add(Object entity, Object value, Boolean forMaterialization)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.AddToCollection(INavigationBase navigationBase, Object value, Boolean forMaterialization)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.AddToCollection(InternalEntityEntry entry, INavigationBase navigation, InternalEntityEntry value, Boolean fromQuery)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.SetReferenceOrAddToCollection(InternalEntityEntry entry, INavigationBase navigation, InternalEntityEntry value, Boolean fromQuery)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.ToDependentFixup(InternalEntityEntry dependentEntry, InternalEntityEntry principalEntry, IForeignKey foreignKey, Boolean fromQuery)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.InitialFixup(InternalEntityEntry entry, InternalEntityEntry duplicateEntry, Boolean fromQuery)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.StateChanged(InternalEntityEntry entry, EntityState oldState, Boolean fromQuery)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.StateChanged(InternalEntityEntry entry, EntityState oldState, Boolean fromQuery)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.MarkUnchangedFromQuery()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTrackingFromQuery(IEntityType baseEntityType, Object entity, ValueBuffer& valueBuffer)
         at Microsoft.EntityFrameworkCore.Query.QueryContext.StartTracking(IEntityType entityType, Object entity, ValueBuffer valueBuffer)
         at lambda_method69(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
         at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.<PopulateIncludeCollection>g__ProcessCurrentElementRow|23_0[TIncludingEntity,TIncludedEntity](<>c__DisplayClass23_0`2&)
         at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.PopulateIncludeCollection[TIncludingEntity,TIncludedEntity](Int32 collectionId, QueryContext queryContext, DbDataReader dbDataReader, SingleQueryResultCoordinator resultCoordinator, Func`3 parentIdentifier, Func`3 outerIdentifier, Func`3 selfIdentifier, IReadOnlyList`1 parentIdentifierValueComparers, IReadOnlyList`1 outerIdentifierValueComparers, IReadOnlyList`1 selfIdentifierValueComparers, Func`5 innerShaper, INavigationBase inverseNavigation, Action`2 fixup, Boolean trackingQuery)
         at lambda_method71(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```

### Include provider and version information

EF Core version: 8.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 8.0
Operating system: Windows 11 22H2
IDE: Visual Studio 2022 17.8.1

**Comment by roji** [comment]
Confirmed the repro. FYI the same happens regardless of the new C# 12 syntax if you initialize Permissions to `new Permission[0]`.

/cc @ajcvickers

**Comment by ajcvickers** [comment]
@roji I watched the .NET Conf talk on this one. :-) The new syntax explicitly attempts to match the collection interface semantics. So it is by design that the collection can't be cast and mutated here. Conversely, the EF pattern being used here is to create something that EF _can_ cast and mutate, but it exposed as a non-mutating type in the API.

**Comment by roji** [comment]
Yeah, makes sense on all counts...

**Comment by Newmski** [comment]
So I should stick to using a `new `statement? e.g.

`new List<Permission>()`

**Comment by Newmski** [comment]
Ok, thanks for your feedback.
