### ISSUE TITLE
EF Core ignores compiled model with PublishAot flag setted

### ISSUE THREAD

**Issue by DjArt** [dotnet/efcore#32496]
## A bug

Okay, lets see code. I want compile it to AOT assembly.

### Code

```C#
internal class Context : DbContext
{
    internal record Source
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public uint ID { get; set; }
        public bool IsFinalized { get; init; }
        public string Name { get; set; }
    }


    internal record SourceEvent
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public uint ID { get; init; }
        public DateTimeOffset Start { get; init; }
        public DateTimeOffset End { get; init; }
        public EventType EventType { get; init; }
        public Source Key { get; init; }
    }


    [Flags]
    internal enum EventType
    {
        Info = 0x00,
        Warning = 0x01,
        Critical = 0x02,
        Error = 0x03,
    }

    public DbSet<Source> Sources { get; set; }
    public DbSet<SourceEvent> Events { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite("Data Source=C:\\ProgramData\\Supplemental.db;foreign keys=true;");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<SourceEvent>()
            .HasOne(e => e.Key)
            .WithMany()
            .OnDelete(DeleteBehavior.Cascade);
    }
}

 internal class Program
 {
    static void Main(string[] args)
    {
        Console.WriteLine("Creating context");
        Context context = new();

        Console.WriteLine("Retrieving migrations");
        IEnumerable<string> migrations = context.Database.GetMigrations();
        Console.WriteLine("Retrieving applied migrations");
        IEnumerable<string> appliedMigrations = context.Database.GetAppliedMigrations();

        Console.WriteLine($"Comparing {migrations?.Count()} with {appliedMigrations?.Count()}");
        if (!migrations.SequenceEqual(appliedMigrations))
        {
            Console.WriteLine("Trying to migrate");
            context.Database.Migrate();
        }

        Console.WriteLine("Adding entity to DB");
        context.Events.Add(new SourceEvent()
        {
            Key = new()
            {
                Name = "#1"
            }
        });
        Console.WriteLine("Saving DB changes");
        context.SaveChanges();
        Console.WriteLine("Done");
    }
}

```

## Path to reproduce

1. If we set `<PublishAot>true</PublishAot>` in project file, we even can't add initial migration:
```
PM> Add-Migration Initial
Build started...
Build succeeded.
Unable to create a 'DbContext' of type ''. The exception 'Model building is not supported when publishing with NativeAOT. Use a compiled model.' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
```
So run command without and generate initial migration.

2. Then, generate compiled model:
```
PM> Optimize-DBContext -OutputDir .\Compiled -Context Context
Build started...
Build succeeded.
Successfully generated a compiled model, to use it call 'options.UseModel(ContextModel.Instance)'. Run this command again when the model is modified.
```
3. Set `<PublishAot>true</PublishAot>` and make `OnConfiguring` overload looks like:
```C#
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    optionsBuilder.UseModel(Compiled.ContextModel.Instance);
    optionsBuilder.UseSqlite("Data Source=C:\\ProgramData\\Supplemental.db;foreign keys=true;");
}
```
4. And get these lines:
```
System.InvalidOperationException: "Model building is not supported when publishing with NativeAOT. Use a compiled model.
   at Microsoft.EntityFrameworkCore.Metadata.RuntimeEntityType.<>c.<get_EmptyShadowValuesFactory>b__209_0(RuntimeEntityType complexType) in /_/src/EFCore/Metadata/RuntimeEntityType.cs:line 1458
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory) in /_/src/Shared/NonCapturingLazyInitializer.cs:line 26
   at Microsoft.EntityFrameworkCore.Metadata.RuntimeEntityType.get_EmptyShadowValuesFactory() in /_/src/EFCore/Metadata/RuntimeEntityType.cs:line 1456
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry..ctor(IStateManager stateManager, IEntityType entityType, Object entity) in /_/src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs:line 42
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetOrCreateEntry(Object entity, IEntityType entityType) in /_/src/EFCore/ChangeTracking/Internal/StateManager.cs:line 261
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.EntryWithoutDetectChanges(TEntity entity) in /_/src/EFCore/Internal/InternalDbSet.cs:line 555
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Add(TEntity entity) in /_/src/EFCore/Internal/InternalDbSet.cs:line 190
   at Program.SetupDB() in C:\Users\djart\source\repos\AOTTest\Program.cs:line 156
   at Program.<Main>d__12.MoveNext() in C:\Users\djart\source\repos\AOTTest\Program.cs:line 179
   in Program.<Main>(String[] args)
```

### Verbose output

```
dotnet ef dbcontext list --verbose
Using project 'C:\Users\djart\source\repos\AOTTest\EFCoreTest.csproj'.
Using startup project 'C:\Users\djart\source\repos\AOTTest\EFCoreTest.csproj'.
Writing 'C:\Users\djart\source\repos\AOTTest\obj\EFCoreTest.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\alyaskovskiy.TENSIB\AppData\Local\Temp\2\tmpgniwmb.tmp /verbosity:quiet /nologo C:\Users\djart\source\repos\AOTTest\EFCoreTest.csproj
Writing 'C:\Users\djart\source\repos\AOTTest\obj\EFCoreTest.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\alyaskovskiy.TENSIB\AppData\Local\Temp\2\tmpyaeoom.tmp /verbosity:quiet /nologo C:\Users\djart\source\repos\AOTTest\EFCoreTest.csproj
Build started...
Build succeeded.
dotnet exec --depsfile C:\Users\djart\source\repos\AOTTest\bin\Debug\net8.0\EFCoreTest.deps.json --additionalprobingpath C:\Users\alyaskovskiy.TENSIB\.nuget\packages --additionalprobingpath "C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages" --runtimeconfig C:\Users\djart\source\repos\AOTTest\bin\Debug\net8.0\EFCoreTest.runtimeconfig.json C:\Users\alyaskovskiy.TENSIB\.dotnet\tools\.store\dotnet-ef\8.0.0\dotnet-ef\8.0.0\tools\net8.0\any\tools\netcoreapp2.0\any\ef.dll dbcontext list --assembly C:\Users\djart\source\repos\AOTTest\bin\Debug\net8.0\EFCoreTest.dll --project C:\Users\djart\source\repos\AOTTest\EFCoreTest.csproj --startup-assembly C:\Users\djart\source\repos\AOTTest\bin\Debug\net8.0\EFCoreTest.dll --startup-project C:\Users\djart\source\repos\AOTTest\EFCoreTest.csproj --project-dir C:\Users\djart\source\repos\AOTTest\ --root-namespace EFCoreTest --language C# --framework net8.0 --nullable --working-dir C:\Users\djart\source\repos\AOTTest --verbose
Using assembly 'EFCoreTest'.
Using startup assembly 'EFCoreTest'.
Using application base 'C:\Users\djart\source\repos\AOTTest\bin\Debug\net8.0'.
Using working directory 'C:\Users\djart\source\repos\AOTTest'.
Using root namespace 'EFCoreTest'.
Using project directory 'C:\Users\djart\source\repos\AOTTest\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'EFCoreTest'...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'Context'.
EFCoreTest.Context
```

### Provider and version information

EF Core version: 8.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer, Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 8.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.8.1

**Comment by roji** [comment]
EF is not yet compatible with NativeAOT; various work has been done to prepare for this, but 8.0 does not yet support it. We plan to deliver at least some experimental support in 9.0.
