### ISSUE TITLE
Having navigations for base type and sub type in the same entity result in "Cannot create a relationship ... because a relationship already exists..." exception

### ISSUE THREAD

**Issue by vlardn** [dotnet/efcore#32507]
Given this model:

```C#
public abstract class Animal
{
    public int Id { get; set; }
    public int ZooId { get; set; }
    public Zoo Zoo { get; set; }
}

public class Tiger : Animal
{
}
```
This works:
```C#
public class Zoo
{
    public int Id { get; set; }
    public IEnumerable<Animal> Animals { get; set; }
}
```
This works:
```C#
public class Zoo
{
    public int Id { get; set; }
    public IEnumerable<Tiger> Tigers { get; set; }
}
```
This does **NOT** work:
```C#
public class Zoo
{
    public int Id { get; set; }
    public IEnumerable<Animal> Animals { get; set; }
    public IEnumerable<Tiger> Tigers { get; set; }
}
```
The test app:
```C#
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;

using var sqliteConnection = new SqliteConnection("Data Source=:memory:");
sqliteConnection.Open();

var dbContextOptions = new DbContextOptionsBuilder<TestContext>()
	.UseSqlite(sqliteConnection)
	.EnableDetailedErrors()
	.EnableSensitiveDataLogging()
	.LogTo(Console.WriteLine)
	.Options;

using var context = new TestContext(dbContextOptions);

try
{
	context.Database.EnsureCreated();
}
catch (Exception ex)
{
	Console.WriteLine(ex);
}

Console.ReadKey();

public class TestContext : DbContext
{
	public TestContext(DbContextOptions options) : base(options) { }

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		base.OnModelCreating(modelBuilder);

		// Explicit FK configuration recommended in 
		// https://github.com/dotnet/efcore/issues/26961#issuecomment-992343923
		modelBuilder.Entity<Zoo>(b =>
		{
			b.HasMany(e => e.Animals).WithOne(e => e.Zoo).HasForeignKey(e => e.ZooId);
			b.HasMany(e => e.Tigers).WithOne(e => e.Zoo).HasForeignKey(e => e.ZooId);
		});

		modelBuilder.Entity<Animal>();
		modelBuilder.Entity<Tiger>();
	}
}

public class Zoo
{
	public int Id { get; set; }
	public IEnumerable<Animal> Animals { get; set; }
	public IEnumerable<Tiger> Tigers { get; set; }
}

public abstract class Animal
{
	public int Id { get; set; }
	public int ZooId { get; set; }
	public Zoo Zoo { get; set; }
}

public class Tiger : Animal
{
}
```
gives an exception:
```
System.InvalidOperationException: Cannot create a relationship between 'Zoo.Tigers' and 'Tiger.Zoo' because a relationship already exists between 'Zoo.Animals' and 'Animal.Zoo'. Navigations can only participate in a single relationship. If you want to override an existing relationship call 'Ignore' on the navigation 'Tiger.Zoo' first in 'OnModelCreating'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalForeignKeyBuilder.ThrowForConflictingNavigation(IReadOnlyForeignKey foreignKey, IReadOnlyEntityType principalEntityType, IReadOnlyEntityType dependentEntityType, String navigationToDependent, String navigationToPrincipal)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalForeignKeyBuilder.GetOrCreateRelationshipBuilder(EntityType principalEntityType, EntityType dependentEntityType, Nullable`1 navigationToPrincipal, Nullable`1 navigationToDependent, IReadOnlyList`1 dependentProperties, IReadOnlyList`1 oldNameDependentProperties, IReadOnlyList`1 principalProperties, Nullable`1 isRequired, Boolean removeCurrent, Nullable`1 principalEndConfigurationSource, Nullable`1 configurationSource, Nullable`1& existingRelationshipInverted)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalForeignKeyBuilder.ReplaceForeignKey(InternalEntityTypeBuilder principalEntityTypeBuilder, InternalEntityTypeBuilder dependentEntityTypeBuilder, Nullable`1 navigationToPrincipal, Nullable`1 navigationToDependent, IReadOnlyList`1 dependentProperties, IReadOnlyList`1 oldNameDependentProperties, IReadOnlyList`1 principalProperties, Nullable`1 isUnique, Nullable`1 isRequired, Nullable`1 isRequiredDependent, Nullable`1 isOwnership, Nullable`1 deleteBehavior, Boolean removeCurrent, Boolean oldRelationshipInverted, Nullable`1 principalEndConfigurationSource, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalForeignKeyBuilder.ReplaceForeignKey(ConfigurationSource configurationSource, InternalEntityTypeBuilder principalEntityTypeBuilder, InternalEntityTypeBuilder dependentEntityTypeBuilder, Nullable`1 navigationToPrincipal, Nullable`1 navigationToDependent, IReadOnlyList`1 dependentProperties, IReadOnlyList`1 oldNameDependentProperties, IReadOnlyList`1 principalProperties, Nullable`1 isUnique, Nullable`1 isRequired, Nullable`1 isRequiredDependent, Nullable`1 isOwnership, Nullable`1 deleteBehavior, Boolean removeCurrent, Nullable`1 principalEndConfigurationSource, Boolean oldRelationshipInverted)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalForeignKeyBuilder.HasNavigations(Nullable`1 navigationToPrincipal, Nullable`1 navigationToDependent, EntityType principalEntityType, EntityType dependentEntityType, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalForeignKeyBuilder.HasNavigations(MemberInfo navigationToPrincipal, MemberInfo navigationToDependent, EntityType principalEntityType, EntityType dependentEntityType, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.CollectionNavigationBuilder.WithOneBuilder(MemberIdentity reference)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.CollectionNavigationBuilder.WithOneBuilder(MemberInfo navigationMemberInfo)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.CollectionNavigationBuilder`2.WithOne(Expression`1 navigationExpression)
   at TestContext.<>c.<OnModelCreating>b__1_0(EntityTypeBuilder`1 b) in C:\wrk\Hopted\test1\ConsoleApp1\Program.cs:line 38
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity[TEntity](Action`1 buildAction)
   at TestContext.OnModelCreating(ModelBuilder modelBuilder) in C:\wrk\Hopted\test1\ConsoleApp1\Program.cs:line 35
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService(IInfrastructure`1 accessor, Type serviceType)
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_Dependencies()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
   at Program.<Main>$(String[] args) in C:\wrk\Hopted\test1\ConsoleApp1\Program.cs:line 18
```

Tested on EF Core 7.0.13 and 8.0.0

**Comment by vlardn** [comment]
I found one working workaround (which doesn't use explicit FK configuration) but it looks more like a limited hack:

```c#
public class Zoo
{
    public int Id { get; set; }
    public IEnumerable<Animal> Animals { get; set; }
    // public IEnumerable<Tiger> Tigers { get; set; } <= THIS DOESN'T WORK!
    [NotMapped] public IEnumerable<Tiger> Tigers => Animals.OfType<Tiger>();
}
```
The loading of `Zoo` entity with `Tigers` property only becomes more complex with this workaround:
```c#
var zoo = context.Zoos.Include(x => x.Animals.Where(y => y is Tiger)).First();
```
and the loading of nested properties like `Zoo.Tigers.Sponsors` with `Include` or nested querying like `Zoos.Where(z => z.Tigers.Any(t => t.Name == "Ava"))` is not possible at all here.

So I still think that navigation for sub-types (`Zoo.Tigers` in this case) could and should be implemented natively by EF (for all inheritance types, i.e.: TPH, TPT, and TPC).

**Comment by AndriySvyryd** [comment]
This is by design and you already found the best workaround.

**Comment by vlardn** [comment]
@AndriySvyryd What do you mean "by design"? Does this mean EF Core can construct SQL for either base-type or sub-type navigations but it's impossible to do the same for both? I checked once again that the database schema is **completely identical** in all 3 cases and it's just a matter of building the same SQL queries for navigations in 3rd case:

**CASE 1** - works:
```c#
public class Zoo
{
    public int Id { get; set; }
    public IEnumerable<Animal> Animals { get; set; }
}
var zoo = context.Zoos.Include(x => x.Animals).Single()
```
```sql
SELECT "t"."Id", "a"."Id", "a"."ZooId"
      FROM (
          SELECT "z"."Id"
          FROM "Zoos" AS "z"
          LIMIT 2
      ) AS "t"
      LEFT JOIN "Animals" AS "a" ON "t"."Id" = "a"."ZooId"
      ORDER BY "t"."Id"
```
**CASE 2** - works:
```c#
public class Zoo
{
    public int Id { get; set; }
    public IEnumerable<Tiger> Tigers { get; set; }
}
var zoo = context.Zoos.Include(x => x.Tigers).Single()
```
```sql
SELECT "t"."Id", "t0"."Id", "t0"."Discriminator", "t0"."ZooId"
      FROM (
          SELECT "z"."Id"
          FROM "Zoos" AS "z"
          LIMIT 2
      ) AS "t"
      LEFT JOIN (
          SELECT "a"."Id", "a"."Discriminator", "a"."ZooId"
          FROM "Animals" AS "a"
          WHERE "a"."Discriminator" = 'Tiger'
      ) AS "t0" ON "t"."Id" = "t0"."ZooId"
      ORDER BY "t"."Id"
```
**CASE 3** - impossible?
```c#
public class Zoo
{
    public int Id { get; set; }
    public IEnumerable<Animal> Animals { get; set; }
    public IEnumerable<Tiger> Tigers { get; set; }
}
var animalsZoo = context.Zoos.Include(x => x.Animals).Single()
var tigersZoo = context.Zoos.Include(x => x.Tigers).Single()
```

**Comment by AndriySvyryd** [comment]
Try configuring the Tiger relationship as one-directional:
`b.HasMany(e => e.Tigers).WithOne().HasForeignKey(e => e.ZooId)`

**Comment by vlardn** [comment]
> Try configuring the Tiger relationship as one-directional: `b.HasMany(e => e.Tigers).WithOne().HasForeignKey(e => e.ZooId)`

Configuring only Tiger relationship as one-directional unfortunately changes database schema and adds additional shadow property into Animals table:
```c#
public class Zoo
{
	public int Id { get; set; }
	public IEnumerable<Animal> Animals { get; set; }
	public IEnumerable<Tiger> Tigers { get; set; }
}

modelBuilder.Entity<Zoo>(b =>
{
        //b.HasMany(e => e.Animals).WithOne(e => e.Zoo).HasForeignKey(e => e.ZooId);
	b.HasMany(e => e.Tigers).WithOne(e => e.Zoo).HasForeignKey(e => e.ZooId);
});
```
```sql
CREATE TABLE "Animal" (
          "Id" INTEGER NOT NULL CONSTRAINT "PK_Animal" PRIMARY KEY AUTOINCREMENT,
          "ZooId" INTEGER NOT NULL,
          "Discriminator" TEXT NOT NULL,
          "ZooId2" INTEGER NOT NULL,
          CONSTRAINT "FK_Animal_Zoo_ZooId" FOREIGN KEY ("ZooId") REFERENCES "Zoo" ("Id") ON DELETE CASCADE,
          CONSTRAINT "FK_Animal_Zoo_ZooId2" FOREIGN KEY ("ZooId2") REFERENCES "Zoo" ("Id") ON DELETE CASCADE
      );
```

**Comment by AndriySvyryd** [comment]
> This changes the database schema and adds unnecessary shadow property ZooId1 into the Animals table:

I see, then, indeed there doesn't appear to be a good workaround.
