### ISSUE TITLE
MigrationBuilder.Sql truncating sql string...

### ISSUE THREAD

**Issue by jhastingsiii** [dotnet/efcore#32549]
This appears to be a change in behavior from EF Core 7.0.0 and 8.0.0. For some migrations I read a SQL file off disk and send the content string through MigrationBuilder.Sql. This has always worked fine for years and after this upgrade I started getting syntax errors from old migrations. I drilled into the stack trace and inspected the CommandText in RelationalCommand.ExecuteNonQuery() and found that my SQL string is being truncated by the library. I commented out this failing part of the migration to let it run further just and noticed once it got to another migration doing the same thing that that migration had also truncated its Sql string, but in a different spot, it didn't seem to be based on the length of the string at all, which is weird. My SQL files aren't doing anything very complex, a table variable, populating it, doing inserts and updates. I'm going to try and reproduce the problem on a standalone project and will provide it when I have it done.

EDIT: After further research, it appears to be truncating the SQL string after it finds a line starting with the value "Go". The following SQL appears to be truncated for example. If I surround the column name "GoId" with brackets, it doesn't truncate the string. I'm guessing it is doing some parsing on the sql string for the "go" keyword and just dumping the rest of it or
 something? I've attached the solution/project reproducing this issue, you can reproduce it by running the migration db update command. If you want the debugging/stack trace you'll need to do some extra steps to call migrations from the code instead.

[EFBug.zip](https://github.com/dotnet/efcore/files/13604963/EFBug.zip)

```Sql
declare @t table (
    GoId nvarchar(500)
)
insert into @t
select ''
```

### Include your code

```C#
var text = File.ReadAllText(Path.Join(Directory.GetCurrentDirectory(), "Migrations", "<MySqlFileName>.sql"));
            
migrationBuilder.Sql(text);
```

### Include stack traces

Microsoft.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)

### Include provider and version information

EF Core version: 8.0.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer) SqlServer
Target framework: (e.g. .NET 6.0) .NET 8.0
Operating system: Windows
IDE: (e.g. Visual Studio 2022 17.4) Rider 2023.3

**Comment by jhastingsiii** [comment]
Closing this, it appears to the PR in the already existing ticket should fix the issue.
