### ISSUE TITLE
Compiled model and SQLite in EF Core error

### ISSUE THREAD

**Issue by ZvonimirMatic** [dotnet/efcore#32592]
I'm trying to build a compiled model for running tests with SQLite (it's a large database with 1200+ tables, so I need compiled model). Everything worked fine with EF Core 7, but after upgrading to EF Core 8, I get the following error when trying to generate a compiled model (You can find the verbose output below):

```
System.TypeLoadException: Method 'Literal' in type 'Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper' from assembly 'Microsoft.EntityFrameworkCore.Design, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
   at Microsoft.EntityFrameworkCore.Design.DesignTimeServiceCollectionExtensions.<>c__DisplayClass0_0.<AddEntityFrameworkDesignTimeServices>b__0(ServiceCollectionMap services)
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.TryAddProviderSpecificServices(Action`1 serviceMap)
   at Microsoft.EntityFrameworkCore.Design.DesignTimeServiceCollectionExtensions.AddEntityFrameworkDesignTimeServices(IServiceCollection services, IOperationReporter reporter, Func`1 applicationServiceProviderAccessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.CreateServiceCollection(DbContext context)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.Build(DbContext context)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.Optimize(String outputDir, String modelNamespace, String contextTypeName)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OptimizeContextImpl(String outputDir, String modelNamespace, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OptimizeContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

I check versions of all EF Core packages, all are set to 8.0.0. Also, generating a compiled model works fine for SQL Server.

Verbose output:
```
PM> Optimize-DbContext -OutputDir CompiledModel -Namespace Insurance.Tests.Unit.CompiledModel -StartupProject Insurance.Tests.Unit -Verbose
Using project 'Insurance.Tests.Unit'.
Using startup project 'Insurance.Tests.Unit'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile C:\projects\incubis-software\insurance\Insurance.Tests.Unit\bin\Debug\net8.0\Insurance.Tests.Unit.deps.json --additionalprobingpath C:\Users\ZvonimirMatić\.nuget\packages --additionalprobingpath "C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages" --runtimeconfig C:\projects\incubis-software\insurance\Insurance.Tests.Unit\bin\Debug\net8.0\Insurance.Tests.Unit.runtimeconfig.json C:\Users\ZvonimirMatić\.nuget\packages\microsoft.entityframeworkcore.tools\8.0.0\tools\netcoreapp2.0\any\ef.dll dbcontext optimize --output-dir CompiledModel --namespace Insurance.Tests.Unit.CompiledModel --verbose --no-color --prefix-output --assembly C:\projects\incubis-software\insurance\Insurance.Tests.Unit\bin\Debug\net8.0\Insurance.Tests.Unit.dll --project C:\projects\incubis-software\insurance\Insurance.Tests.Unit\Insurance.Tests.Unit.csproj --startup-assembly C:\projects\incubis-software\insurance\Insurance.Tests.Unit\bin\Debug\net8.0\Insurance.Tests.Unit.dll --startup-project C:\projects\incubis-software\insurance\Insurance.Tests.Unit\Insurance.Tests.Unit.csproj --project-dir C:\projects\incubis-software\insurance\Insurance.Tests.Unit\ --language C# --configuration Debug --working-dir C:\projects\incubis-software\insurance --root-namespace Insurance.Tests.Unit --nullable
Using assembly 'Insurance.Tests.Unit'.
Using startup assembly 'Insurance.Tests.Unit'.
Using application base 'C:\projects\incubis-software\insurance\Insurance.Tests.Unit\bin\Debug\net8.0'.
Using working directory 'C:\projects\incubis-software\insurance\Insurance.Tests.Unit'.
Using root namespace 'Insurance.Tests.Unit'.
Using project directory 'C:\projects\incubis-software\insurance\Insurance.Tests.Unit\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Found IDesignTimeDbContextFactory implementation 'InsuranceTestContextFactory'.
Found DbContext 'InsuranceTestContext'.
Finding application service provider in assembly 'Insurance.Tests.Unit'...
Finding Microsoft.Extensions.Hosting service provider...
Using environment 'Development'.
System.InvalidOperationException: The entry point exited without ever building an IHost.
   at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.CreateHost()
   at Microsoft.Extensions.Hosting.HostFactoryResolver.<>c__DisplayClass10_0.<ResolveHostFactory>b__0(String[] args)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.<>c__DisplayClass13_0.<ResolveServiceProviderFactory>b__3(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.CreateFromHosting(String[] args)
An error occurred while accessing the Microsoft.Extensions.Hosting services. Continuing without the application service provider. Error: The entry point exited without ever building an IHost.
No application service provider was found.
Finding DbContext classes in the project...
Using DbContext factory 'InsuranceTestContextFactory'.
Using context 'InsuranceTestContext'.
Finding design-time services referenced by assembly 'Insurance.Tests.Unit'...
Finding design-time services referenced by assembly 'Insurance.Tests.Unit'...
No referenced design-time services were found.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.Sqlite'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.Sqlite'.
'InsuranceTestContext' disposed.
System.TypeLoadException: Method 'Literal' in type 'Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper' from assembly 'Microsoft.EntityFrameworkCore.Design, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
   at Microsoft.EntityFrameworkCore.Design.DesignTimeServiceCollectionExtensions.<>c__DisplayClass0_0.<AddEntityFrameworkDesignTimeServices>b__0(ServiceCollectionMap services)
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.TryAddProviderSpecificServices(Action`1 serviceMap)
   at Microsoft.EntityFrameworkCore.Design.DesignTimeServiceCollectionExtensions.AddEntityFrameworkDesignTimeServices(IServiceCollection services, IOperationReporter reporter, Func`1 applicationServiceProviderAccessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.CreateServiceCollection(DbContext context)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.Build(DbContext context)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.Optimize(String outputDir, String modelNamespace, String contextTypeName)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OptimizeContextImpl(String outputDir, String modelNamespace, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OptimizeContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Method 'Literal' in type 'Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper' from assembly 'Microsoft.EntityFrameworkCore.Design, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
```

EF Core version: 8.0.0
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 8.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.8.3

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ZvonimirMatic** [comment]
It seems that there was some weird issue with references between my projects and nuget packages. I added EntityFrameworkCore.Design package directly into my project where I'm generating compiled model and everything works fine now. I think that one of the packages references older version of EntityFrameworkCore.Design and that it was causing the problem. I'm closing the issue.
