### ISSUE TITLE
Creating a new SqliteConnection from a project targeting net48 fails with TypeInitializationException

### ISSUE THREAD

**Issue by thatnerdyguy** [dotnet/efcore#32610]
Using the following project:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RuntimeIdentifiers>win-x64;win-x86</RuntimeIdentifiers>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.0" />
  </ItemGroup>
</Project>
```

and the following Program.cs
```
using Microsoft.Data.Sqlite;
using System;

namespace ConsoleApp1
{
    internal static class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("start");

            try
            {
                using (var conn = new SqliteConnection())
                {
                    System.Console.WriteLine("SqliteConnection was created!");
                }
            }
            catch(Exception e)
            {
                System.Console.WriteLine($"Oh no! Something went horribly wrong! Message: {e.Message}\nStack trace: {e.StackTrace}");
            }

            Console.WriteLine("end");
        }
    }
}
```

run it, and see we end up in the "Oh no!.... " section. With the exception stack trace of:

```
Stack trace:    at Microsoft.Data.Sqlite.SqliteConnection..ctor()
   at ConsoleApp1.Program.Main(String[] args) in C:\Code\ConsoleApp1\Program.cs:line 14
```

Looks like the calls to ```Type.GetType("Windows.Storage.ApplicationData, Windows, ContentType=WindowsRuntime");``` are failing. In 7.* they were caught in a catch-all catch {} block, but now they are only getting caught if throwing FileLoadException, and they are apparently throwing something else.

### Include version information

Microsoft.Data.Sqlite version: 8.0.0
Target framework: net48
Operating system: Windows

**Comment by ErikEJ** [comment]
Looks like it is this that fails:

```csharp
        Type.GetType("SQLitePCL.Batteries_V2, SQLitePCLRaw.batteries_v2")
?.GetRuntimeMethod("Init", Type.EmptyTypes)
?.Invoke(null, null);
```

Changing you project as follows fixes the issue:

```csharp
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<OutputType>Exe</OutputType>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.0" />
	</ItemGroup>
</Project>
```
