### ISSUE TITLE
EfCore.SqlServer: string.IndexOf throws NullReferenceException when applied on Int.ToString()

### ISSUE THREAD

**Issue by TeymurZeynally** [dotnet/efcore#32618]
### Description
When using string.IndexOf on the result of Int.ToString() in Entity Framework Core for SQL Server, a NullReferenceException is being thrown.

### Steps to Reproduce

Entity
```C#
class SomeEntity
{
    public long Id { get; set; }
}
```

DbContext
```C#
public class Database : DbContext
{
    public Database(DbContextOptions o): base(o)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<SomeEntity>(e =>
        {
            e.HasKey(x => x.Id);
            e.ToTable("SomeTable", "dbo");
        });
    }
}
```

Queries causing error
```C#
var reuslt = dbcontext.Set<SomeEntity>()
    .Select(x => "SomeString123".IndexOf(x.Id.ToString()))
    .ToArray();
```

```C#
var reuslt = dbcontext.Set<SomeEntity>()
    .Select(x => x.Id.ToString().IndexOf("123"))
    .ToArray();
```

### Stack trace
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerStringMethodTranslator.TranslateIndexOf(SqlExpression instance, MethodInfo method, SqlExpression searchExpression, SqlExpression startIndex)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerStringMethodTranslator.Translate(SqlExpression instance, MethodInfo method, IReadOnlyList`1 arguments, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Query.RelationalMethodCallTranslatorProvider.<>c__DisplayClass7_0.<Translate>b__0(IMethodCallTranslator t)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.EntityFrameworkCore.Query.RelationalMethodCallTranslatorProvider.Translate(IModel model, SqlExpression instance, MethodInfo method, IReadOnlyList`1 arguments, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TranslateInternal(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Program.<Main>$(String[] args) in C:\Users\tz\source\repos\ConsoleApp37\ConsoleApp37\Program.cs:line 12
```

### Provider and version information
EF Core version: 6.0.2 - 8.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0 - NET 8.0
Operating system: Microsoft Windows 10 Enterprise 10.0.19045 N/A Build 19045
IDE: Visual Studio 2022 17.8.3

### Workaround
A workaround would be passing `CultureInfo.InvariantCulture` 

```C#
var reuslt = dbcontext.Set<SomeEntity>()
    .Select(x => "SomeString123".IndexOf(x.Id.ToString(CultureInfo.InvariantCulture)))
    .ToArray();
```

```C#
var reuslt = dbcontext.Set<SomeEntity>()
    .Select(x => x.Id.ToString(CultureInfo.InvariantCulture).IndexOf("123"))
    .ToArray();
```

I cannot use this workaround solution because such queries are generated by an external library (odata), and I have no influence on the generation of these requests

**Comment by ajcvickers** [comment]
Note for triage: verified that this is not a regression.
