### ISSUE TITLE
Using SQL Server, Database.CanConnect throws an exception when password is blank.

### ISSUE THREAD

**Issue by ttosello** [dotnet/efcore#32630]
When using SQL Auth to connect to a SQL Server database, if the password is blank, Database.CanConnect throws the following error:

```
The value cannot be an empty string. (Parameter 'oldValue')


   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName) in /_/src/libraries/System.Private.CoreLib/src/System/ArgumentException.cs:line 129
   at System.String.Replace(String oldValue, String newValue) in /_/src/libraries/System.Private.CoreLib/src/System/String.Manipulation.cs:line 1206
```

I am expecting the call to CanConnect to return false.  If the password is supplied, but incorrect, then CanConnect returns false.

I am using EF Core 8.0.0

**Comment by ttosello** [comment]
I just noticed that if the password is simply a white space " ", then CanConnect also behaves correctly and returns false.  The exception is only thrown is the password is blank.

**Comment by ErikEJ** [comment]
@ttosello Please share a complete stack trace

**Comment by ttosello** [comment]
at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName) in /_/src/libraries/System.Private.CoreLib/src/System/ArgumentException.cs:line 129
   at System.String.Replace(String oldValue, String newValue) in /_/src/libraries/System.Private.CoreLib/src/System/String.Manipulation.cs:line 1206
   at xxx.<CanConnectAsync>d__10.MoveNext() in C:\Users\ttosello\source\repos\xxx\xxx\Services\DataService.cs:line 202

**Comment by ttosello** [comment]
Restarting Visual Studio resolves the error.   I will have to pay attention to other conditions if it happens again.
