### ISSUE TITLE
DeleteBehavior.Restrict results in "The association between entity types 'Root' and 'Child' has been severed, but the relationship is either marked as required or is implicitly required because the foreign key is not nullable"

### ISSUE THREAD

**Issue by ElgersNiels** [dotnet/efcore#32666]
## Ask a question

When marking a **one-to-many** relationship with **DeleteBehavior.Restrict**, the **exception** below is thrown when trying to **delete one of the children**.

#32383 seems relevant, but the error also occurs in 7.x. The issue also mentions that the behavior is intended; but I fail to understand **what** the intended behavior is and **why**. This is why I open a question as opposed as a bug.

What I expect is that I would be unable to delete a Root as long as it has Children; but in this case I'm trying to delete one of the individual children.

The example below is a minimal reproduction example: but I encountered this issue when trying to setup a transitive relationship e.g.:
**Root** one-to-many **Child**ren (DeleteBehavior.Restrict)
**Root** one-to-many **Middle**s
**Middle** one-to-many **Child**s

In this case, omitting the DeleteBehavior.Restrict results in a multiple cascade paths error; which is expected.
What I expect from including DeleteBehavior.Restrict is that deleting a Root will result in the deletion of its Middles which will result in the deletion of its (and the Roots) Childs. As such, there is a singular cascade path and the foreign key constraint remains satisfied.

However, when deleting a Child, the same error is thrown as in the simpler reproduction example below.
I don't see how removing a Child would cause a not-nullable foreign key want to become null.

### Include your code

Model.cs
```
using Microsoft.EntityFrameworkCore;

namespace ConsoleApp1;

public class MyContext : DbContext
{
    public DbSet<Root> Roots => Set<Root>();
    public DbSet<Child> Children => Set<Child>();
    
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite("Data Source=mydb15");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        
        modelBuilder.Entity<Root>(entity =>
        {
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id)
                .IsRequired();

            entity
                .HasMany(e => e.Children)
                .WithOne()
                .HasForeignKey(e => e.RootId)
                .OnDelete(DeleteBehavior.Restrict);
        });

        modelBuilder.Entity<Child>(entity =>
        {
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id)
                .IsRequired();
        });
    }
}

public class Child
{
    public Guid Id { get; }

    public Guid RootId { get; }
    
    public Child(Guid id)
    {
        Id = id;
    }
}

public class Root
{
    public Guid Id { get; }
    public virtual ICollection<Child> Children { get; }

    protected Root(Guid id)
    {
        Id = id;
    }
    
    public Root(ICollection<Child> children)
    {
        Children = children;
    }
}
```

Program.cs
```
using Microsoft.EntityFrameworkCore;

namespace ConsoleApp1
{
    public class Program
    {
        public static async Task Main()
        {
            await using var db = new MyContext();
            await db.Database.MigrateAsync();

            var childId = Guid.NewGuid();
;           await db.Roots.AddAsync(
                                        new Root(
                                            new List<Child>()
                                            {
                                                new(childId)
                                            }
                                        )
            );
            
            await db.SaveChangesAsync();

            var child = db.Children
                .SingleOrDefault(x => x.Id == childId);
            
            var root = db.Roots
                .Include(root => root.Children)
                .First();
            
            root.Children.Remove(child);
            
            await db.SaveChangesAsync();
        }
        
    }
}
```
### Include stack traces

```
Unhandled exception. System.InvalidOperationException: The association between entity types 'Root' and 'Child' has been severed, but the relationship is either marked as required or is implicitly required because the foreign key is not nullable. If the dependent/child entity should be deleted when a required relationship is severed, configure the relationship to use cascade deletes. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the key values.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.HandleConceptualNulls(Boolean sensitiveLoggingEnabled, Boolean force, Boolean isCascadeDelete)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.HandleNullForeignKey(IProperty property, Boolean setModified, Boolean isCascadeDelete)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean isMaterialization, Boolean setModified, Boolean isCascadeDelete, CurrentValueType valueType)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean isMaterialization, Boolean setModified, Boolean isCascadeDelete)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.set_Item(IPropertyBase propertyBase, Object value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.ConditionallyNullForeignKeyProperties(InternalEntityEntry dependentEntry, InternalEntityEntry principalEntry, IForeignKey foreignKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.NavigationCollectionChanged(InternalEntityEntry entry, INavigationBase navigationBase, IEnumerable`1 added, IEnumerable`1 removed)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.NavigationCollectionChanged(InternalEntityEntry entry, INavigationBase navigationBase, IEnumerable`1 added, IEnumerable`1 removed)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectNavigationChange(InternalEntityEntry entry, INavigationBase navigationBase)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.LocalDetectChanges(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager)
   at Microsoft.EntityFrameworkCore.ChangeTracking.ChangeTracker.DetectChanges()
   at Microsoft.EntityFrameworkCore.DbContext.TryDetectChanges()
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at ConsoleApp1.Program.Main() in C:\dev\MACS\ConsoleApp1\Program.cs:line 33
   at ConsoleApp1.Program.Main() in C:\dev\MACS\ConsoleApp1\Program.cs:line 33
   at ConsoleApp1.Program.<Main>()
```

### Include provider and version information

EF Core version: .NET 7.0.x, .NET 8.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer, Microsoft.EntityFrameworkCore.SqlLite
Target framework: .NET 7.0, .NET 8.0
Operating system: Microsoft Windows 11 Pro
IDE: Jetbrains Rider 2023.2.1

**Comment by ElgersNiels** [comment]
This behavior is intended indeed and I now understand why.

By calling `root.Children.Remove(child);` with `DeleteBehavior.Restrict`, we are **severing the relationship** between root and child and **not deleting** the child. Severing the relationship and not deleting the child entails that the foreign key is set to null, causing the error.

By calling `root.Children.Remove(child);` with `DeleteBehavior.Cascade` (default on required relationships), we are **severing the relationship** between root and child **and deleting** the child. The child is removed because it is orphaned.
