### ISSUE TITLE
Contains query on nested projected type cannot be translated

### ISSUE THREAD

**Issue by ymotton** [dotnet/efcore#32663]
After upgrading from 7.0 to 8.0 we noticed some regressions when filtering on nested projected types.
See below for sample code that reproduces the issue.

Basically we have a Task table and a Link table that directionally links two task records. 
When we query the Task table, project an optional link record to a RelatedTask property and then use that RelatedTask in a contains filter, the expression cannot be translated.

What does work, is if I replace the `.Contains()` filter by an `.Any()`-filter.
But obviously, the former should (and did) work.

### Minimal sample

```C#
class Task
{
    public Guid Id { get; set; }
    public List<Link> OutboundLinks { get; set; }
}
class Link
{
    public Guid Id { get; set; }
    public Guid FromId { get; set; }
    public Guid ToId { get; set; }
    public int Type { get; set; }
}
class MyContext : DbContext
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Link>();
        modelBuilder.Entity<Task>().HasMany(x => x.OutboundLinks).WithOne().HasForeignKey(x => x.FromId);
    }
}

class Program
{
    public static void Main(string[] args)
    {
        var context = new MyContext();

        var ids = new[] { Guid.NewGuid() };

        var tasks = context.Set<Task>()
            .Select(x => new
            {
                Id = x.Id,
                RelatedTask = x.OutboundLinks
                    .Select(l => new
                    {
                        Id = l.ToId,
                        Type = l.Type
                    })
                    .FirstOrDefault()
            })
            .Where(x => ids.Contains(x.RelatedTask.Id)) // <- This doesn't work
            // .Where(x => ids.Any(id => x.RelatedTask.Id == id)) // <- This does work
            .ToList();
        
        Console.WriteLine(tasks.Count);
    }
}
```

### Stack trace

```
Unhandled exception. System.InvalidOperationException: The LINQ expression '__ids_0
    .Contains((Guid)MaterializeCollectionNavigation(
        Navigation: Task.OutboundLinks,
        subquery: DbSet<Link>()
            .Where(i => EF.Property<Guid?>(StructuralTypeShaperExpression: 
                Task
                ValueBufferExpression: 
                    ProjectionBindingExpression: EmptyProjectionMember
                IsNullable: False
            , "Id") != null && object.Equals(
                objA: (object)EF.Property<Guid?>(StructuralTypeShaperExpression: 
                    Task
                    ValueBufferExpression: 
                        ProjectionBindingExpression: EmptyProjectionMember
                    IsNullable: False
                , "Id"), 
                objB: (object)EF.Property<Guid?>(i, "FromId"))))
        .AsQueryable()
        .Select(l => (Guid?)l.ToId)
        .FirstOrDefault())' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.   
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.TranslateSubquery(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TranslateInternal(Expression expression, Boolean applyDefaultTypeMapping)  
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression, Boolean applyDefaultTypeMapping)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateExpression(Expression expression, Boolean applyDefaultTypeMapping)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateLambdaExpression(ShapedQueryExpression shapedQueryExpression, LambdaExpression lambdaExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateWhere(ShapedQueryExpression source, LambdaExpression predicate)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)     
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)     
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)  
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

EF Core version: 8.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0.0
Operating system: Windows 11
IDE: JetBrains Rider

**Comment by ErikEJ** [comment]
Have you tried the latest daily build?

**Comment by roji** [comment]
@ymotton yeah, we're fixed quite a few regressions related to Contains, so as @ErikEJ says, can you please the latest [daily build](https://github.com/dotnet/efcore?tab=readme-ov-file#daily-builds) and report on the results? If you're still seeing the regression on the latest daily build I'll definitely take a look ASAP.

**Comment by ymotton** [comment]
@ErikEJ @roji The daily build `9.0.0-alpha.1.23620.2` does indeed fix the issue, thanks!

Will a 8.0.x patch version be released to support 8.0 customers, and if so, any timeline on this?
Thanks!

**Comment by ErikEJ** [comment]
8.0.2 will be released on Feb patch Tuesday snd will most likely ha e the fix.

**Comment by roji** [comment]
Thanks for confirming.
