### ISSUE TITLE
Adding related identity issues Update command instead of Insert with entity.HasKey(e => e.OtherId) setting

### ISSUE THREAD

**Issue by hooyao** [dotnet/efcore#32728]
I'm using `Microsoft.EntityFrameworkCore` with ASP.NET Core 6.0 and Azure SQL database.
I run into a situation where adding a related entity results in an `Update` command instead of `Insert`. My DB schema is a little bit unconventional; the table's primary id is  `Id` , but the business id used for identifying the entity is `EntityId`.
The schema design is from a legacy system, I can't change it.

The reproduceable [repo](https://github.com/hooyao/EFCoreRepo)

I have 2 tables, simplified DDL is as follows.
```SQL
CREATE TABLE MMP.dbo.Parent (
	Id bigint IDENTITY(1,1) NOT NULL,
	ParentId uniqueidentifier DEFAULT newid() NOT NULL,
	CONSTRAINT AK_Parent_ParentId UNIQUE (ParentId),
	CONSTRAINT PK_Parent PRIMARY KEY (Id)
);

CREATE TABLE MMP.dbo.[Child] (
	Id bigint IDENTITY(1,1) NOT NULL,
	ParentId uniqueidentifier NULL,
	ChildId uniqueidentifier DEFAULT newid() NOT NULL,
	CONSTRAINT AK_Child_ChildId UNIQUE (ChildId),
	CONSTRAINT PK_Child PRIMARY KEY (Id)
);

ALTER TABLE MMP.dbo.[Child] ADD CONSTRAINT FK_Child_ParentId FOREIGN KEY (ParentId) REFERENCES MMP.dbo.Parent(ParentId);
```
Using database first approach
the classes are
```csharp
    public partial class Parent
    {
        public Parent()
        {
            Children = new HashSet<Child>();
        }

        public long? Id { get; set; }
        public Guid ParentId { get; set; }

        public virtual ICollection<Child> Children { get; set; } = new List<Child>();
    }

    public partial class Child
    {
        public long? Id { get; set; }
        public Guid? ParentId { get; set; }
        public Guid ChildId { get; set; }

        public virtual Parent Parent { get; set; }
    }

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Child>(entity =>
    {
        entity.ToTable("Child");

        entity.HasKey(e => e.ChildId);

        entity.HasIndex(e => e.ChildId, "AK_Child_ChildId")
            .IsUnique();

        entity.Property(e => e.ChildId).HasDefaultValueSql("(newid())");
        entity.Property(e => e.Id).HasColumnName("Id").ValueGeneratedOnAdd();

        entity.HasOne(d => d.Parent)
            .WithMany(p => p.Children)
            .HasPrincipalKey(p => p.ParentId)
            .HasForeignKey(d => d.ParentId)
            .HasConstraintName("FK_Child_ParentId");
    });

    modelBuilder.Entity<Parent>(entity =>
    {
        entity.ToTable("Parent");
        
        entity.HasKey(e => e.ParentId);

        entity.HasIndex(e => e.ParentId, "AK_Parent_ParentId")
            .IsUnique();

        entity.Property(e => e.ParentId).HasDefaultValueSql("(newid())");
        entity.Property(e => e.Id).HasColumnName("Id").ValueGeneratedOnAdd();
    });

    OnModelCreatingPartial(modelBuilder);
}
```
The following code adds the related entity `Child` to its parent `Parent`
```csharp
Parent? parentEntity2 = await context.Parents.FindAsync(new object[] { parentEntity.ParentId }, CancellationToken.None);
parentEntity2.Children.Add(new Child(){ChildId = Guid.NewGuid(), ParentId = parentEntity2.ParentId, Id = null});
await context.SaveChangesAsync(CancellationToken.None);
```
Changing the following configuration for the `Child`, then it works.
```csharp
entity.HasKey(e => e.ChildId);
```
To
```csharp
entity.HasKey(e => e.Id);
```

The complete SQL and stack traces
```
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (4ms) [Parameters=[@p2='518b7809-f591-47e3-9763-b02437673700', @p0=NULL (DbType = Int64), @p1='6f6d16e9-0fb9-4480-86b7-1def73ef5777' (Nullable = true)], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      UPDATE [Child] SET [Id] = @p0, [ParentId] = @p1
      WHERE [ChildId] = @p2;
      SELECT @@ROWCOUNT;
fail: Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type 'EFCoreRepro.Models.MMPContext'.
      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
       ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot update identity column 'Id'.
         at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__188_0(Task`1 result)
         at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
         at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
      ClientConnectionId:0703665e-5823-40ff-8a7a-24398a6b9cf7
      Error Number:8102,State:1,Class:16
         --- End of inner exception stack trace ---
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CaUnhandled exception. ncellationToken cancellationToken) 
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
       ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot update identity column 'Id'.
         at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__188_0(Task`1 result)
         at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
         at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
      ClientConnectionId:0703665e-5823-40ff-8a7a-24398a6b9cf7
      Error Number:8102,State:1,Class:16
         --- End of inner exception stack trace ---
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot update identity column 'Id'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__188_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:0703665e-5823-40ff-8a7a-24398a6b9cf7
Error Number:8102,State:1,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in E:\Projects\EFCoreRepro\EFCoreRepro\Program.cs:line 23
   at Program.<Main>(String[] args)
```

I also tried to hide the real primary key id, by mapping `ParentId` and `ChildId` to the Id in the class as in this [branch](https://github.com/hooyao/EFCoreRepo/tree/hide_id), and let the key to be the disguised `ChildId`, EF still fails with the same issue.
 

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer 6.0.25
Target framework: .NET 6.0
Operating system: Windows 11, Visual Studio 2022 Version 17.9.0 Preview 1.0

**Comment by ajcvickers** [comment]
@hooyao  The code is setting the primary key explicitly: `ChildId = Guid.NewGuid()`. Since the key is setup to use generated values, EF assumes by default that an explicitly set value means the entity already exists. Generally, either:

- Use generated keys and don't explicitly set key values for new entities
- Use non-generated keys and do explicitly set key values for new entities
- Use generated keys and set explicit key values, but take on responsibility for explicitly setting entity state as well.
