### ISSUE TITLE
Shadow Concurrency Token of owned Type in TPH Hierarchy is not set automatically.

### ISSUE THREAD

**Issue by theissto** [dotnet/efcore#32720]
### Descritpion
When updating an entity that has an owned reference navigation node and a concurrency token, an exception is thrown when:
* The entity to update uses TPH strategy
* The owned type is used in one or more concrete types of the hierarchy

The error was reproduced using a postreSQL database.

For a test case please refer to: https://github.com/SysTec-Computer-GmbH/EF-Detached-Graph-Tracker/blob/main/SysTec.EF.ChangeTracking.DetachedGraphTracker.Tests/EfDefault/EfDefaultBugReports.cs

### Models for failing test case
```C#
public abstract class BaseType
{
        [Key]
        public int Id { get; set; }
        
        [Timestamp]
        [ConcurrencyCheck]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        [Column("xmin", TypeName = "xid")]
        public uint ConcurrencyToken { get; set; }

        public string Discriminator { get; set; }
}
```

```C#
[Owned]
public class OwnedType
{
    
}
```

```C#
public class ConcreteTypeOne : BaseType
{
    public OwnedType Owned { get; set; }
}
```

```C#
public class ConcreteTypeTwo : BaseType
{
    
}
```

### DbContext for failing test case

```C#
public class EfDefaultBugReportsDbContext : DbContextBase
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BaseType>()
            .UseTphMappingStrategy()
            .HasDiscriminator(d => d.Discriminator)
            .HasValue<ConcreteTypeOne>(nameof(ConcreteTypeOne))
            .HasValue<ConcreteTypeTwo>(nameof(ConcreteTypeTwo));
    }
}
```

### Failing test case
```C#
    [Test]
    public async Task _01_ConcurrencyTokenOfOwnedType_InTphConfiguration_ShouldBeSetAutomatically()
    {
        var init = new ConcreteTypeOne()
        {
            Owned = new()
        };

        await using (var dbContext = new EfDefaultBugReportsDbContext())
        {
            dbContext.Add(init);
            await dbContext.SaveChangesAsync();
        }
        
        Assert.That(init.Id, Is.GreaterThan(0));
        Assert.That(init.ConcurrencyToken, Is.GreaterThan(0));

        var update = new ConcreteTypeOne()
        {
            Id = init.Id,
            ConcurrencyToken = init.ConcurrencyToken,
            Owned = new()
        };
        
        await using (var dbContext = new EfDefaultBugReportsDbContext())
        {
            dbContext.Update(update);
            var conventionConcurrencyTokenCurrentValue = (uint)dbContext.Entry(update.Owned)
                .Property("_TableSharingConcurrencyTokenConvention_ConcurrencyToken").CurrentValue!;
            
            Assert.Multiple(() =>
            {
                // Actual is 0
                Assert.That(conventionConcurrencyTokenCurrentValue, Is.EqualTo(update.ConcurrencyToken)); 
                
                // Throws InvalidOperationException
                Assert.DoesNotThrowAsync(async () => await dbContext.SaveChangesAsync()); 
            });
        }
    }
```

**Note: When the OwnedType is only referenced from the abstract base type, no exception is thrown.**

### StackTrace of failing test

```
System.InvalidOperationException: Instances of types 'ConcreteTypeOne' and 'OwnedType' are mapped to the same row with the key value '{Id: 1}', but have different original property values {ConcurrencyToken: 465450} and {_TableSharingConcurrencyTokenConvention_ConcurrencyToken: 0} for the column 'xmin'.
   at Microsoft.EntityFrameworkCore.Update.ColumnModification.AddSharedColumnModification(IColumnModification modification)
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.<GenerateColumnModifications>g__HandleColumn|41_8(IColumnMappingBase columnMapping, <>c__DisplayClass41_0&, <>c__DisplayClass41_1&, <>c__DisplayClass41_2&)
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.<GenerateColumnModifications>g__HandleNonJson|41_7(ITypeBase structuralType, ITableMapping tableMapping, <>c__DisplayClass41_0&, <>c__DisplayClass41_1&, <>c__DisplayClass41_2&)
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.GenerateColumnModifications()
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.<>c.<get_ColumnModifications>b__33_0(ModificationCommand command)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.get_ColumnModifications()
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.CreateCommandBatches(IEnumerable`1 commandSet, Boolean moreCommandSets, Boolean assertColumnModification, ParameterNameGenerator parameterNameGenerator)+MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.BatchCommands(IList`1 entries, IUpdateAdapter updateAdapter)+MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at SysTec.EF.ChangeTracking.DetachedGraphTracker.Tests.EfDefault.EfDefaultBugReports.<>c__DisplayClass0_1.<<_01_ConcurrencyTokenOfOwnedType_InTphConfiguration_ShouldBeSetAutomatically>b__1>d.MoveNext()
```

### What behavior did I expect?

When calling `dbContext.Update()` I would expect the shadow property `_TableSharingConcurrencyTokenConvention_ConcurrencyToken` to have the same value as the concurrency token of the owner.
Or: The owned type to not even have a hidden concurrency token (that is the default case when not in this tph configuration if I remember correctly)

### Version information

EF Core version: 8.0.0
Database provider:  Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET 8.0
Operating system: macOS 14.2.1 (23C71)

**Comment by ajcvickers** [comment]
@AndriySvyryd What is the expected behavior when calling Update on a detached entity that has a shadow concurrency token on an owned type?

Model:

```
Model: 
  EntityType: BaseType Abstract
    Properties: 
      Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd
      ConcurrencyToken (ulong) Required Concurrency BeforeSave:Ignore AfterSave:Ignore ValueGenerated.OnAddOrUpdate
      Discriminator (string) Required AfterSave:Throw MaxLength(21)
    Keys: 
      Id PK
  EntityType: ConcreteTypeOne Base: BaseType
    Navigations: 
      Owned (OwnedType) ToDependent OwnedType
  EntityType: ConcreteTypeTwo Base: BaseType
  EntityType: OwnedType Owned
    Properties: 
      ConcreteTypeOneId (no field, int) Shadow Required PK FK AfterSave:Throw
      _TableSharingConcurrencyTokenConvention_ConcurrencyToken (no field, ulong) Shadow Required Concurrency BeforeSave:Ignore AfterSave:Ignore ValueGenerated.OnAddOrUpdate
    Keys: 
      ConcreteTypeOneId PK
    Foreign keys: 
      OwnedType {'ConcreteTypeOneId'} -> ConcreteTypeOne {'Id'} Unique Required RequiredDependent Ownership Cascade ToDependent: Owned
```

**Comment by ajcvickers** [comment]
Note for triage: in the connected case, we have a Deleted entity with the old concurrency value. In the disconnected case the original value is unknown. Explicitly setting the current or original value makes the disconnected case work.

Not a regression

Connected:

```
ConcreteTypeOne {Id: 1} Unchanged
    Id: 1 PK
    ConcurrencyToken: 2001
    Discriminator: 'ConcreteTypeOne'
  Owned: {ConcreteTypeOneId: 1}
OwnedType (Shared) {ConcreteTypeOneId: 1} Added
    ConcreteTypeOneId: 1 PK FK
    Foo: 'X'
    _TableSharingConcurrencyTokenConvention_ConcurrencyToken: 0 Unknown
OwnedType (Shared) {ConcreteTypeOneId: 1} Deleted
    ConcreteTypeOneId: 1 PK FK
    Foo: <null>
    _TableSharingConcurrencyTokenConvention_ConcurrencyToken: 2001
```

Disconnected:

```
ConcreteTypeOne {Id: 1} Modified
    Id: 1 PK
    ConcurrencyToken: 2001
    Discriminator: 'ConcreteTypeOne'
  Owned: {ConcreteTypeOneId: 1}
OwnedType {ConcreteTypeOneId: 1} Modified
    ConcreteTypeOneId: 1 PK FK
    Foo: 'X' Modified
    _TableSharingConcurrencyTokenConvention_ConcurrencyToken: 0 Unknown
```

Test code:

```C#
var init = new ConcreteTypeOne()
{
    Owned = new()
};

using (var context = new SomeDbContext())
{
    await context.Database.EnsureDeletedAsync();
    await context.Database.EnsureCreatedAsync();

    context.Add(init);
    await context.SaveChangesAsync();

    // init.Owned = new() { Foo = "X" };

    // context.ChangeTracker.DetectChanges();
    //
    // context.SaveChanges();
}

var update = new ConcreteTypeOne()
{
    Id = init.Id,
    ConcurrencyToken = init.ConcurrencyToken,
    Owned = new() { Foo = "X" }
};
        
using (var context = new SomeDbContext())
{
    context.Update(update);
    var conventionConcurrencyTokenCurrentValue = (ulong)context.Entry(update.Owned)
        .Property("_TableSharingConcurrencyTokenConvention_ConcurrencyToken").CurrentValue!;

    context.Entry(update.Owned).Property("_TableSharingConcurrencyTokenConvention_ConcurrencyToken").CurrentValue =
        init.ConcurrencyToken;
    context.ChangeTracker.DetectChanges();
  await context.SaveChangesAsync(); 
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Data Source=localhost;Database=One;Integrated Security=True;TrustServerCertificate=true")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BaseType>()
            .UseTphMappingStrategy()
            .HasDiscriminator(d => d.Discriminator)
            .HasValue<ConcreteTypeOne>(nameof(ConcreteTypeOne))
            .HasValue<ConcreteTypeTwo>(nameof(ConcreteTypeTwo));
    }
}

public abstract class BaseType
{
    [Key]
    public int Id { get; set; }
        
    [Timestamp]
    [ConcurrencyCheck]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public ulong ConcurrencyToken { get; set; }

    public string Discriminator { get; set; }
}

[Owned]
public class OwnedType
{
    public string? Foo { get; set; }
}

public class ConcreteTypeOne : BaseType
{
    public OwnedType Owned { get; set; }
}

public class ConcreteTypeTwo : BaseType
{
}
```

**Comment by AndriySvyryd** [comment]
For now this is by design. As a workaround you'd need to set the original value on the shadow concurrency property or to use a non-shadow concurrency property on the owned types.

https://github.com/dotnet/efcore/issues/18529 will improve this experience
