### ISSUE TITLE
NullReferenceException in Get-Migration in EF Core 8

### ISSUE THREAD

**Issue by bgoodearl** [dotnet/efcore#32732]
## File a bug

See details in issue 32487
[efcore/issues/32487](https://github.com/dotnet/efcore/issues/32487)

We've spent a fair bit of time trying to reproduce the issue with a cut-down sample, but have not been successful.

A colleague has debugged into the EF code with our client project and found where the exception is being thrown.

I created a test sample with enough entities to have the entity where the exception was thrown, but that sample does not fail.

We can share the new test sample with you and include information about where the client code is failing and the new sample is not failing, but do not want to make the new sample public.

Code that's failing:
```C#
static DeleteBehavior DefaultDeleteBehavior(IConventionSkipNavigation conventionSkipNavigation)
{
	if (!conventionSkipNavigation.ForeignKey.IsRequired)
	{
		return DeleteBehavior.ClientSetNull;
	}
	return DeleteBehavior.Cascade;
}
```
this throws the exception: conventionSkipNavigation.ForeignKey.IsRequired due to ForeignKey being null

This problem is a show-stopper for converting this client project to .NET 8.

### Include provider and version information

EF Core version: 8.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.8.3

**Comment by bgoodearl** [comment]
I have a cut down sample of the client solution that reproduces the problem.  I can share the code with you folks as long as it's not made public.  How would we do that?

**Comment by ajcvickers** [comment]
@bgoodearl You can email it to avickers at this place I work. Let me know when you have done so, since it may go to spam.

**Comment by bgoodearl** [comment]
Arthur - just sent you an email without a zip.  Will follow up with a zip.

**Comment by bgoodearl** [comment]
Sent emails with zips

**Comment by bgoodearl** [comment]
Updated NuGet packages to 8.0.1 and VS2022 to 17.8.4 - same results

**Comment by MantasG-Visma** [comment]
we're also encountering the issue when switched to .NET 8 with EF8 and executing "dotnet.exe ef migrations script -i" which worked fine on .NET 7.

Stacktrace:
`System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindCollectionMapping(RelationalTypeMappingInfo info, Type modelType, Type providerType, CoreTypeMapping elementMapping)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.<>c.<FindMappingWithConversion>b__8_0(ValueTuple`4 k, RelationalTypeMappingSource self)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMappingWithConversion(RelationalTypeMappingInfo mappingInfo, Type providerClrType, ValueConverter customConverter)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMappingWithConversion(RelationalTypeMappingInfo mappingInfo, IReadOnlyList`1 principals)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMapping(Type type, String storeTypeName, Boolean keyOrIndex, Nullable`1 unicode, Nullable`1 size, Nullable`1 rowVersion, Nullable`1 fixedLength, Nullable`1 precision, Nullable`1 scale)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.DefaultValue(Object defaultValue, String defaultValueSql, String columnType, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.ColumnDefinition(String schema, String table, String name, ColumnOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.ColumnDefinition(AddColumnOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(AddColumnOperation operation, IModel model, MigrationCommandListBuilder builder, Boolean terminate)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(AddColumnOperation operation, IModel model, MigrationCommandListBuilder builder, Boolean terminate)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__82_0(MigrationsSqlGenerator g, MigrationOperation o, IModel m, MigrationCommandListBuilder b)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateScript(String fromMigration, String toMigration, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.ScriptMigration(String fromMigration, String toMigration, MigrationsSqlGenerationOptions options, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScriptMigrationImpl(String fromMigration, String toMigration, Boolean idempotent, Boolean noTransactions, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScriptMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.
`

**Comment by ajcvickers** [comment]
@MantasG-Visma That looks like a different issue. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by MantasG-Visma** [comment]
@ajcvickers I have debugged the issue, it seems it is caused by default value of a guid key:

` migrationBuilder.AddColumn<Guid>(
                name: "MyId",
                table: "MyTable",
                nullable: false, 
                defaultValue: "0616c0e2-9505-4fe0-0001-000000000000");`

When I delete it, it works.

**Comment by FominD98** [comment]
It helped me to change table.Column<Guid>(nullable: false) to table.Column<Guid>(type: "uniqueidentifier", nullable: false)
