### ISSUE TITLE
Compiled Query Issue

### ISSUE THREAD

**Issue by mymintin** [dotnet/efcore#32820]
When I wrote the compiled query,
```C#
private static readonly Func<ApplicationDbContext, IQueryable<ApplicationUser>> UsersCompiled =
    EF.CompileQuery((ApplicationDbContext context) =>
        context.Users
);

public IQueryable<ApplicationUser> GetUsersCompiled()
{
    return UsersCompiled(this);
}
```

The compiler shows the following error message:
> CS0266	Cannot implicitly convert type 'System.Func<ApplicationDbContext, System.Collections.Generic.IEnumerable<ApplicationUser>>' to 'System.Func<ApplicationDbContext, System.Linq.IQueryable<ApplicationUser>>'. An explicit conversion exists (are you missing a cast?)

The compiler doesn't show error, when I changed the code to :
```C#
private static readonly Func<ApplicationDbContext, IQueryable<ApplicationUser>> UsersCompiled =
    EF.CompileQuery<ApplicationDbContext, IQueryable<ApplicationUser>>(
        (ApplicationDbContext context) =>
            context.Users
);
```

But the following error message is shown, when the program is running:
```C#
var _context = new ApplicationDbContext();
var list = _context.GetUsersCompiled().ToList();
```

> System.ArgumentException
  HResult=0x80070057
  Message=Expression of type 'Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1[Models.ApplicationUser]' cannot be used for return type 'System.Linq.IQueryable`1[Models.ApplicationUser]'
  Source=System.Linq.Expressions
  StackTrace:
   at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters, String paramName)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, Boolean tailCall, IEnumerable`1 parameters)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CreateCompiledQuery[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQuery`2.CreateCompiledQuery(IQueryCompiler queryCompiler, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryBase`2.<>c.<EnsureExecutor>b__7_0(CompiledQueryBase`2 t, TContext c, LambdaExpression q)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam1,TParam2,TParam3,TValue](TValue& target, TParam1 param1, TParam2 param2, TParam3 param3, Func`4 valueFactory)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryBase`2.EnsureExecutor(TContext context)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryBase`2.ExecuteCore(TContext context, CancellationToken cancellationToken, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryBase`2.ExecuteCore(TContext context, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQuery`2.Execute(TContext context)
   at AdvansMM.VRM.Data.ApplicationDbContext.GetUsersCompiled() in D:\Development\Project\Project.Library\Data\ApplicationDbContextExtensions.cs:line 67
   at Program.<Main>$(String[] args) in D:\Development\Project\ConsoleApp\Program.cs:line 35

### Include provider and version information

EF Core version: 8.0.0
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 8.0)
Operating system: Windows 11
IDE: (e.g. Visual Studio 2022 17.8.4)

**Comment by roji** [comment]
Compiled queries cannot return an IQueryable, only an IEnumerable. The whole point of compiled queries is to produce a completely self-contained query for execution, but returning an IQueryable means that you can continue composing operators on top of it.

Change the return type to IEnumerable, and your query should compile and run successfully.
