### ISSUE TITLE
IOrderedQueryable projection to record throw exception

### ISSUE THREAD

**Issue by sharpzilla** [dotnet/efcore#32874]
When I'm building an orderable query and using a record, I get an exception on any operation on translation from LINQ to SQL (Count, List, etc.). However, when I swap the record with a class without a constructor, the exception disappears. The crucial part is that if I add a constructor to the class, the exception reoccurs, similar to the issue with the record projection. I tried adding a private constructor for the class, but it doesn't help.

Solution in attachements.
[myapp.zip](https://github.com/dotnet/efcore/files/13998108/myapp.zip)

### Code
```C#
using Api.Persistence;
using Microsoft.AspNetCore.Mvc;

namespace Api.Controllers;

public class GetPropertyDto
{
    public string Comment { get; set; }
}

public record GetDto(string Comment);

[Route("api/linq-problem")]
[ApiController]
public class LinqController(MyContext dbContext) : ControllerBase
{
    [HttpGet]
    public async Task<IActionResult> Get()
    {
        //THIS THROW EXCEPTION
        IQueryable<GetDto>? query = dbContext.ModelStateChangeLog
            .Where(z => z.ModelId == Guid.Empty)
            .Select(v => new GetDto(v.Comment));

        IOrderedQueryable<GetDto> orderedQuery = query.OrderBy(z => z.Comment);

        return Ok(orderedQuery.Count());


        //THIS WORKS

       /*IQueryable<GetPropertyDto>? query = dbContext.ModelStateChangeLog
           .Where(z => z.ModelId == Guid.Empty)
           .Select(v => new GetPropertyDto { Comment = v.Comment });
        IOrderedQueryable<GetPropertyDto> orderedQuery = query.OrderBy(z => z.Comment);
        return Ok(orderedQuery.Count());*/
    }
}
```

### Include stack traces
That example throws exception when line orderedQuery.Count() executed. There is no inner exceptions.
Exception source: `Microsoft.EntityFrameworkCore.`
Exception message:
```
The LINQ expression 'DbSet<ModelStateChangeLog>()
    .Where(m => m.ModelId == 00000000-0000-0000-0000-000000000000)
    .OrderBy(m => new GetDto(m.Comment).Comment)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```
Stack Trace:
```
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Api.Controllers.LinqController.<Get>d__2.MoveNext() in C:\Users\Sharpzilla\source\Test\myapp\Api\Controllers\LinqController.cs:line 29
```

### Verbose output
```
dotnet ef dbcontext list --verbose
Using project 'C:\Users\Sharpzilla\source\Test\myapp\Api\Api.csproj'.
Using startup project 'C:\Users\Sharpzilla\source\Test\myapp\Api\Api.csproj'.
Writing 'C:\Users\Sharpzilla\source\Test\myapp\Api\obj\Api.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\Sharpzilla\AppData\Local\Temp\tmp51iwtw.tmp /verbosity:quiet /nologo C:\Users\Sharpzilla\source\Test\myapp\Api\Api.csproj
Writing 'C:\Users\Sharpzilla\source\Test\myapp\Api\obj\Api.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\Sharpzilla\AppData\Local\Temp\tmpi4dqzp.tmp /verbosity:quiet /nologo C:\Users\Sharpzilla\source\Test\myapp\Api\Api.csproj
Build started...
dotnet build C:\Users\Sharpzilla\source\Test\myapp\Api\Api.csproj /verbosity:quiet /nologo /p:PublishAot=false
C:\Users\Sharpzilla\source\Test\myapp\Api\Persistence\MyContext.cs(14,33): warning CS0114: 'MyContext.Model' hides inherited member 'DbContext.Model'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword. [C:\Users\Sharpzilla\source\Test\myapp\Api\Api.csproj]
C:\Users\Sharpzilla\source\Test\myapp\Api\Migrations\20240120125432_warrants.cs(10,26): warning CS8981: The type name 'warrants' only contains lower-cased ascii characters. Such names may become reserved for the language. [C:\Users\Sharpzilla\source\Test\myapp\Api\Api.csproj]
C:\Users\Sharpzilla\source\Test\myapp\Api\Migrations\20240120125432_warrants.Designer.cs(16,19): warning CS8981: The tynd bug fixes. See https://aka.ms/AAc1fbw for more information.assembly 'Api'.C:\Users\Sharpzilla\source\Test\myapp\Api --ler.cs(31,26): warning CS0168: The variable 'ex' is dec
Finding DbContext classes....t\myapp\Api\Controllers\LinqController.cs(18,38): warning CS1998: This async method lacks
Finding IDesignTimeDbContextFactory implementations...\myapp\Api\bin\Debug\net8.0'.
Finding application service provider in assembly 'Api'...ocumentservice\Api'.
Finding Microsoft.Extensions.Hosting service provider...stence\MyContext.cs(14,33): warning CS0114: 'MyContext.Model' hides inher
Using environment 'Development'.s\Sharpzilla\source\Test\myapp\Api\'.
Using application service provider from Microsoft.Extensions.Hosting.\Api\bin\Debug\net8.0\Api.deps.json --additionalprobingpath
Found DbContext 'MyContext'.ersion '8.0.0' is older than that of the runtime '8.0.1'. Update the tools for the latest features an
Finding DbContext classes in the project...
Api.Persistence.MyContext
```

### Provider and version information

EF Core version and Database provider:
```
<PropertyGroup>
	<TargetFramework>net8.0</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<InvariantGlobalization>true</InvariantGlobalization>
</PropertyGroup>

<ItemGroup>
	<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0" />
	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.1" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.1">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.1" />
</ItemGroup>
```
Target framework: .NET 8.0
Operating system: Windows 10 Pro 22H2 19045.3930 16Gb, Intel i7-1165G7
IDE: (Visual Studio Community 2022 17.8.2)
Databse version: PostgreSQL 14.9 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
Database inside Docker: postgres:14.9-alpine3.18
Docker Desktop:  4.26.1 (131620)

**Comment by ajcvickers** [comment]
Note for triage: this is about calling a constructor when projecting to a DTO, as opposed to using property setters. I suspect it is a dupe. Not a regression.

**Comment by maumar** [comment]
example of a dupe: https://github.com/dotnet/efcore/issues/31279
