### ISSUE TITLE
Concat on projected Queryables throws error "Unable to translate set operation after client projection has been applied"

### ISSUE THREAD

**Issue by yutamago** [dotnet/efcore#32977]
I'm seeing the following error when trying to Concat two conditionally projected Queryables:

`Error creating query string: Unable to translate set operation after client projection has been applied. Consider moving the set operation before the last 'Select'`

My code is equivalent to the following:
```C#
var queryA = _dbContext.EntityA.Select(x => new MergedEntity {
  aTitle = x.Title,
  bTitle = null
});

var queryB = _dbContext.EntityB.Select(x => new MergedEntity {
  aTitle = null,
  bTitle = x.Title
});

queryA.Concat(queryB).ToList();
```

I found a previous issue talking about this behaviour, but I can't tell how to apply the workaround to my use case:
https://github.com/dotnet/efcore/issues/21148#issuecomment-639481421

and 
https://github.com/dotnet/efcore/issues/16243#issuecomment-1136290604

Any help would be greatly appreciated.

### Stack trace
```
System.InvalidOperationException: Unable to translate set operation after client projection has been applied. Consider moving the set operation before the last 'Select' call.
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ApplySetOperation(SetOperationType setOperationType, SelectExpression select2, Boolean distinct)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ApplyUnion(SelectExpression source2, Boolean distinct)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateConcat(ShapedQueryExpression source1, ShapedQueryExpression source2)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at DevExtreme.AspNet.Data.Async.ReflectionAsyncAdapter.InvokeToListAsync[T](MethodInfo method, IQueryProvider provider, Expression expr, CancellationToken cancellationToken)
   at DevExtreme.AspNet.Data.DataSourceLoaderImpl`1.ExecExprAsync[R](Expression expr)
   at DevExtreme.AspNet.Data.DataSourceLoaderImpl`1.LoadAsync()
   at XXX.XXX.Module.Workflow.Controllers.MixedUserTaskController.GetOpenTasksAndListsDxQuery(Nullable`1 my, Nullable`1 id, DataSourceLoadOptions loadOptions)
```

### Include provider and version information

EF Core version: 7.0.11
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET 7.0
Operating system: Windows 11 21H2
IDE: Jetbrains Rider 2023.3.3

**Comment by yutamago** [comment]
> I can't reproduce the problem based on the above - that's why it's important to always submit an actually runnable, minimal code sample, rather than code snippets which are roughly equivalent. Please see the code below, and make the necessary changes in order to make it fail.

Sorry for that. The following code reproduces the issue.
While writing the minimal reproduction, I also identified the actual culprit `SubjectIds`.
Omitting that makes the query execute without errors.

```C#
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

var queryA = ctx.EntityA.Select(x => new MergedViewModel() {
    Id = x.Id,
    Type = "EntityA",
    SubjectIds = x.EntityCs
        .Where(c => c.Visibility == "Active")
        .Select(c => c.SubjectId)
        .ToList(),
});

var queryB = ctx.EntityB.Select(x => new MergedViewModel {
    Id = x.Id,
    Type = "EntityB",
    SubjectIds = x.EntityAs
        .SelectMany(y => y.EntityCs)
        .Where(c => c.Visibility == "Active")
        .Select(c => c.SubjectId)
        .ToList(),
    
});

var concatQuery = queryA.Concat(queryB);
var result = concatQuery.ToList();

Console.WriteLine();

public class BlogContext : DbContext
{
    public DbSet<EntityA> EntityA { get; set; }
    public DbSet<EntityB> EntityB { get; set; }
    public DbSet<EntityC> EntityC { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer("Server=localhost;Database=EfCoreReproProjection;User Id=sa;Password=123456abcDEF!;TrustServerCertificate=true")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder
            .Entity<EntityB>()
            .HasMany<EntityA>(x => x.EntityAs);
        modelBuilder
            .Entity<EntityA>()
            .HasMany<EntityC>(x => x.EntityCs);
    }
}

public class EntityBase
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public Guid Id { get; set; }
}

public class EntityA : EntityBase
{
    public ICollection<EntityC> EntityCs { get; set; }
}

public class EntityB : EntityBase
{
    public ICollection<EntityA> EntityAs { get; set; }
}
public class EntityC : EntityBase
{
    public string Visibility { get; set; }
    public Guid SubjectId { get; set; }
}

public class MergedViewModel
{
    public Guid Id { get; set; }
    public string Type { get; set; }
    public List<Guid> SubjectIds { get; set; } = new();
}
```

**Comment by ajcvickers** [comment]
Note for triage: still repros on the latest daily and not a regression from EF7.

**Comment by roji** [comment]
Note to the team: the source of the issue is the fact that the set operation is over a subquery projecting out a collection:

```c#
var queryA = ctx.EntityA.Select(x => new MergedViewModel() {
    Id = x.Id,
    Type = "EntityA",
    SubjectIds = x.EntityCs
        .Where(c => c.Visibility == "Active")
        .Select(c => c.SubjectId)
        .ToList() // <-- Changing this to e.g. First() makes the query translate
});
```

I think this is because we internally handle collection projections (IncludeExpression) as client projections for some reason - it's something I've wondered about before.

In any case, @yutamago since you're doing Concat specifically, a decent workaround is to simply perform the Concat on the client side - the same number of rows will get returned from the database regardless of whether this is done server- or client-side (the only disadvantage is the two roundtrips instead of one). To do this, add AsEnumerable as follows:

```c#
var concatQuery = queryA.AsEnumerable().Concat(queryB.AsEnumerable());
```

**Comment by yutamago** [comment]
> In any case, @yutamago since you're doing Concat specifically, a decent workaround is to simply perform the Concat on the client side - the same number of rows will get returned from the database regardless of whether this is done server- or client-side (the only disadvantage is the two roundtrips instead of one). To do this, add AsEnumerable as follows:
> 
> ```cs
> var concatQuery = queryA.AsEnumerable().Concat(queryB.AsEnumerable());
> ```

In this minimal repro I would 100% agree with you.
But my production database is huge and after the Concat comes filtering, sorting and pagination.
I wouldn't dare to transmit both tables to the client for each page.

I'm open for suggestions tho, if you know of a different way that would solve my problem.

**Comment by roji** [comment]
> But my production database is huge and after the Concat comes filtering, sorting and pagination.

It is typically possible to lift the Concat up in this case, i.e. lower the filtering/sorting/pagination under the Concat (duplicating them for both legs), and then composing the Concat at the very top, at which point it can be client-evaluatable with little impact. If you're not sure how to do that, post a query and i'll try to help.

**Comment by jon-armen** [comment]
Any updates as to when this may be fixed?

**Comment by Bouke** [comment]
> a decent workaround is to simply perform the Concat on the client side

@roji in https://github.com/dotnet/efcore/issues/16243#issuecomment-1136290604 you also mentioned this workaround, but I'd like to point out that this doesn't work when performing operations over the UNION ALL. So I might want to do `SELECT * FROM (A UNION ALL B) WHERE C ORDER BY D LIMIT 10`. I cannot do this client-side without bringing more data (essentially the complete UNION ALL).

**Comment by stevendarby** [comment]
> Note to the team: the source of the issue is the fact that the set operation is over a subquery projecting out a collection:
> 
> var queryA = ctx.EntityA.Select(x => new MergedViewModel() {
>     Id = x.Id,
>     Type = "EntityA",
>     SubjectIds = x.EntityCs
>         .Where(c => c.Visibility == "Active")
>         .Select(c => c.SubjectId)
>         .ToList() // <-- Changing this to e.g. First() makes the query translate
> });

@roji Regarding your comment about it working if you do First() instead, I just stumbled across a slight variation on that which doesn't work - when the property is wrapped in a class instead of selected directly. I'm not sure if it has the same root cause as this issue - because it's no longer projecting a collection on the face of it. Perhaps it's a separate bug.

If you amend the repro so that the queries look like this:

```C#
var queryA = ctx.EntityA.Select(x => new MergedViewModel()
{
    Id = x.Id,
    Type = "EntityA",
    Subject = x.EntityCs
        .Where(c => c.Visibility == "Active")
        .Select(c => new Subject { SubjectId = c.SubjectId })
        .First()
});

var queryB = ctx.EntityB.Select(x => new MergedViewModel
{
    Id = x.Id,
    Type = "EntityB",
    Subject = x.EntityAs
        .SelectMany(y => y.EntityCs)
        .Where(c => c.Visibility == "Active")
        .Select(c => new Subject { SubjectId = c.SubjectId })
        .First()
});
```

Tweaked models:
```C#
public class MergedViewModel
{
    public Guid Id { get; set; }
    public string Type { get; set; }
    public Subject Subject { get; set; } = new();
}
public class Subject
{
    public Guid SubjectId { get; set; }
}
```

**Comment by roji** [comment]
@stevendarby yeah, probably best to track that as a separate issue - can you open one with the minimal repro?
