### ISSUE TITLE
EF Core 8.0.1  query with where  Contains  ( xx in zzzz) create error SqlException (0x80131904):

### ISSUE THREAD

**Issue by eelti** [dotnet/efcore#33045]
## File a bug
In version 7 all works ok we can run a query with a where condition that contains a list and when switch to Ef8 

### The query

```C#
              var weblistroles = _context.WebListRoles
                  .Where(w => list.Contains(w.RoleNumber))
                  .Select(i => new {
                      i.RoleNumber,
                      i.RoleDescription
                  });
```

### Include stack traces

```
Microsoft.EntityFrameworkCore.Database.Command: Error: Failed executing DbCommand (23ms) [Parameters=[@__list_0='["1000","1010"]' (Size = 4000)], CommandType='Text', CommandTimeout='30']
SELECT [w].[RoleNumber], [w].[RoleDescription]
FROM [Web_ListRole] AS [w]
WHERE [w].[RoleNumber] IN (
    SELECT [l].[value]
    FROM OPENJSON(@__list_0) WITH ([value] nvarchar(50) '$') AS [l]
)
Microsoft.EntityFrameworkCore.Query: Error: An exception occurred while iterating over the results of a query for context type 'InnoPlan.Data.InnoPlanContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near the keyword 'WITH'.
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__209_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:b8c1ff07-7dc1-4f9a-b209-9422d635ddb6
Error Number:156,State:1,Class:15
```

### Include provider and version information

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 8.0)
Operating system:
IDE: (Visual Studio 2022 17.8.4)

**Comment by roji** [comment]
Please read [this breaking change note](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/breaking-changes#sqlserver-contains-compatibility).

**Comment by eelti** [comment]
Oupsss... Thanks!!

**Comment by knopa** [comment]
Even according to breaking changes, usual contains in where should works)

**Comment by roji** [comment]
@knopa it does work - but the default translation in 8.0 isn't compatible with older SQL Server versions (or newer versions configured with an older compatibility level). Read the release notes linked above for more details, and if you think you're seeing a problem, please open a new issue with a minimal, runnable repro.

**Comment by roji** [comment]
@knopa have you tried 8.0.2 which was released two days ago?

**Comment by knopa** [comment]
@roji I was very curios. I did it now - checked on 8.0.2 - works like a charm.
Thank you. You are amazing

**Comment by roji** [comment]
Great to hear! Thanks for confirming!
