### ISSUE TITLE
Cosmos - Inheritance through abstract class fails to load when searching by Find or through explicit load statements

### ISSUE THREAD

**Issue by brused27** [dotnet/efcore#33134]
I am currently experiencing an issue when using inheritance based abstract classes on EF Core 8.0.2 while using the Cosmos connector where abstract classes are not able to be queried against by using a `Find` or `FindAsync` and it will fail with an error message of `Cannot dynamically create an instance of type '<type>'. Reason: Cannot create an abstract class.`

These queries work correctly in EF Core 7.0.16 if I switch to that version.

I am also seeing this same error if I setup a M:M style relationship where I am unable to ask the middle join table to explicitly load the downstream relationship if I reference the abstract model class on the join class - I will have the same error.

The code below is reproducing the error dependent on which version of `Microsoft.EntityFrameworkCore.Cosmos` in use (8.0.2 vs 7.0.16).

### Code
```C#
using Microsoft.EntityFrameworkCore;

Guid insertedDog = Guid.Empty;
Guid insertedCat = Guid.Empty;
Guid insertedVetOffice = Guid.Empty;
using (var db = new AbstractFailDbContext())
{
    db.Database.EnsureCreated();
    Dog dog = new() { Name = "Fido", Breed = "Golden Retriever" };
    Cat cat = new() { Name = "Whiskers", Color = "Calico" };
    db.Animals.Add(dog);
    db.Animals.Add(cat);
    db.SaveChanges();
    insertedDog = dog.Id;
    insertedCat = cat.Id;

    //Relational lookup
    VetrinaryOffice vetrinaryOffice = new() { Name = "Test Office" };
    db.Add(vetrinaryOffice);
    vetrinaryOffice.VetrinaryOfficeAnimals.Add(new VetrinaryOfficeAnimal { VetrinaryOffice = vetrinaryOffice, Animal = dog });
    vetrinaryOffice.VetrinaryOfficeAnimals.Add(new VetrinaryOfficeAnimal { VetrinaryOffice = vetrinaryOffice, Animal = cat });
    db.SaveChanges();
    insertedVetOffice = vetrinaryOffice.Id;
}

using (var db = new AbstractFailDbContext())
{
    var foundAnimal = db.Animals.Find(insertedDog);
    if (foundAnimal is Dog dog)
        Console.WriteLine($"Found dog: {dog.Name} {dog.Breed}");
    else
        Console.WriteLine("Dog not found");

    var foundAnimal2 = db.Animals.Find(insertedCat);
    if (foundAnimal2 is Cat cat)
        Console.WriteLine($"Found cat: {cat.Name} {cat.Color}");
    else
        Console.WriteLine("Cat not found");
}

using (var db = new AbstractFailDbContext())
{
    var foundVetOffice = db.VetrinaryOffices.Find(insertedVetOffice);
    if (foundVetOffice == null)
    {
        Console.WriteLine("Vet Office not found");
        return;
    }

    db.Entry(foundVetOffice).Collection(x => x.VetrinaryOfficeAnimals).Load();
    foreach (var animal in foundVetOffice.VetrinaryOfficeAnimals)
    {
        db.Entry(animal).Reference(x => x.Animal).Load();
        if (animal.Animal is Dog dog)
            Console.WriteLine($"Vet Office: {foundVetOffice.Name} - Found dog: {dog.Name} {dog.Breed}");
        else if (animal.Animal is Cat cat)
            Console.WriteLine($"Vet Office: {foundVetOffice.Name} - Found cat: {cat.Name} {cat.Color}");
        else
            Console.WriteLine($"Vet Office: {foundVetOffice.Name} - Unknown animal");
    }
}

public class AbstractFailDbContext : DbContext
{
    public DbSet<Animal> Animals => Set<Animal>();
    public DbSet<Dog> Dog => Set<Dog>();
    public DbSet<Cat> Cats => Set<Cat>();
    public DbSet<VetrinaryOffice> VetrinaryOffices => Set<VetrinaryOffice>();

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseCosmos(
            "https://REMOVED.documents.azure.com:443/",
            "REMOVED",
            "AbstractFailDb");
}

public abstract class Animal
{
    public Guid Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
}
public class Dog : Animal
{
    public string Breed { get; set; } = string.Empty;
}
public class Cat : Animal
{
    public string Color { get; set; } = string.Empty;
}

public class VetrinaryOffice
{
    public Guid Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public List<VetrinaryOfficeAnimal> VetrinaryOfficeAnimals { get; set; } = [];
}
public class VetrinaryOfficeAnimal
{
    public VetrinaryOffice VetrinaryOffice { get; set; }
    public Animal Animal { get; set; }
}
```

### Exception (as seen in EF Core 8.0.2)
```
Unhandled exception. System.MissingMethodException: Cannot dynamically create an instance of type 'Animal'. Reason: Cannot create an abstract class.
   at System.RuntimeType.ActivatorCache..ctor(RuntimeType rt)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosShapedQueryCompilingExpressionVisitor.ReadItemQueryingEnumerable`1.TryGenerateIdFromKeys(IProperty idProperty, Object& value)
   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosShapedQueryCompilingExpressionVisitor.ReadItemQueryingEnumerable`1.TryGetResourceId(String& resourceId)
   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosShapedQueryCompilingExpressionVisitor.ReadItemQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at lambda_method349(Closure, QueryContext)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.Find(Object[] keyValues)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Find(Object[] keyValues)
   at Program.<Main>$(String[] args) in C:\source\repos\EFCore8AbstractBug\EFCore8AbstractBug\Program.cs:line 28
```

### Expected output (as seen in EF Core 7.0.16)
```
Found dog: Fido Golden Retriever
Found cat: Whiskers Calico
Vet Office: Test Office - Found dog: Fido Golden Retriever
Vet Office: Test Office - Found cat: Whiskers Calico
```

### Provider / Version Info

EF Core version: 8.0.2 (results with error), 7.0.16 (successfully queries)
Database provider: Microsoft.EntityFrameworkCore.Cosmos
Target framework: .NET 8.0.1
Operating system: Windows 11 22H2
IDE: Visual Studio 2022 17.8.6

**Comment by brused27** [comment]
To help narrow this further, it looks like starting with 8.0.0-rc.2.23480.1 it triggers this exception, while 8.0.0-rc.1.23419.6 runs this use case successfully.

**Comment by brused27** [comment]
@ajcvickers I tried this on 9.0.0-preview.7.24405.3 today and this code is working correctly now (after updating to async methods of course).  I believe you can close this issue unless you want to address in EF Core 8.0 - I verified this issue is still reproducing on 8.0.8.

### Console output on 9.0.0-preview.7.24405.3 (Expected / Now Passing):
```
Found dog: Fido Golden Retriever
Found cat: Whiskers Calico
Vet Office: Test Office - Found dog: Fido Golden Retriever
Vet Office: Test Office - Found cat: Whiskers Calico
```

### Updated code for 9.0.0-preview.7.24405.3 (updated sync to async EF Core methods):
```csharp
using Microsoft.EntityFrameworkCore;

Guid insertedDog = Guid.Empty;
Guid insertedCat = Guid.Empty;
Guid insertedVetOffice = Guid.Empty;
using (var db = new AbstractFailDbContext())
{
    await db.Database.EnsureCreatedAsync();
    Dog dog = new() { Name = "Fido", Breed = "Golden Retriever" };
    Cat cat = new() { Name = "Whiskers", Color = "Calico" };
    db.Animals.Add(dog);
    db.Animals.Add(cat);
    await db.SaveChangesAsync();
    insertedDog = dog.Id;
    insertedCat = cat.Id;

    //Relational lookup
    VetrinaryOffice vetrinaryOffice = new() { Name = "Test Office" };
    db.Add(vetrinaryOffice);
    vetrinaryOffice.VetrinaryOfficeAnimals.Add(new VetrinaryOfficeAnimal { VetrinaryOffice = vetrinaryOffice, Animal = dog });
    vetrinaryOffice.VetrinaryOfficeAnimals.Add(new VetrinaryOfficeAnimal { VetrinaryOffice = vetrinaryOffice, Animal = cat });
    await db.SaveChangesAsync();
    insertedVetOffice = vetrinaryOffice.Id;
}

using (var db = new AbstractFailDbContext())
{
    var foundAnimal = await db.Animals.FindAsync(insertedDog);
    if (foundAnimal is Dog dog)
        Console.WriteLine($"Found dog: {dog.Name} {dog.Breed}");
    else
        Console.WriteLine("Dog not found");

    var foundAnimal2 = await db.Animals.FindAsync(insertedCat);
    if (foundAnimal2 is Cat cat)
        Console.WriteLine($"Found cat: {cat.Name} {cat.Color}");
    else
        Console.WriteLine("Cat not found");
}

using (var db = new AbstractFailDbContext())
{
    var foundVetOffice = await db.VetrinaryOffices.FindAsync(insertedVetOffice);
    if (foundVetOffice == null)
    {
        Console.WriteLine("Vet Office not found");
        return;
    }

    await db.Entry(foundVetOffice).Collection(x => x.VetrinaryOfficeAnimals).LoadAsync();
    foreach (var animal in foundVetOffice.VetrinaryOfficeAnimals)
    {
        await db.Entry(animal).Reference(x => x.Animal).LoadAsync();
        if (animal.Animal is Dog dog)
            Console.WriteLine($"Vet Office: {foundVetOffice.Name} - Found dog: {dog.Name} {dog.Breed}");
        else if (animal.Animal is Cat cat)
            Console.WriteLine($"Vet Office: {foundVetOffice.Name} - Found cat: {cat.Name} {cat.Color}");
        else
            Console.WriteLine($"Vet Office: {foundVetOffice.Name} - Unknown animal");
    }
}

public class AbstractFailDbContext : DbContext
{
    public DbSet<Animal> Animals => Set<Animal>();
    public DbSet<Dog> Dog => Set<Dog>();
    public DbSet<Cat> Cats => Set<Cat>();
    public DbSet<VetrinaryOffice> VetrinaryOffices => Set<VetrinaryOffice>();

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseCosmos(
            "https://REMOVED.documents.azure.com:443/",
            "REMOVED",
            "AbstractFailDb");
}

public abstract class Animal
{
    public Guid Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
}
public class Dog : Animal
{
    public string Breed { get; set; } = string.Empty;
}
public class Cat : Animal
{
    public string Color { get; set; } = string.Empty;
}

public class VetrinaryOffice
{
    public Guid Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public List<VetrinaryOfficeAnimal> VetrinaryOfficeAnimals { get; set; } = [];
}
public class VetrinaryOfficeAnimal
{
    public VetrinaryOffice VetrinaryOffice { get; set; }
    public Animal Animal { get; set; }
}
```
