### ISSUE TITLE
Why create table twice?

### ISSUE THREAD

**Issue by yc-2503** [dotnet/efcore#33141]
## File a bug
I make sure thers is only one table named "SCRM_ROLE_MSCD". And the database is empty.
I use command "Add-Migration "init"" and "Update-Database" .
But it CREATE TABLE "SCRM_ROLE_MSCD" twice.

### Include your code

```C#
internal class RoleEntityTypeConfiguration : IEntityTypeConfiguration<UserRole>
{
    public void Configure(EntityTypeBuilder<UserRole> builder)
    {
        builder.ToTable("SCRM_ROLE_MSCD");
        builder.HasKey(t => t.Id);
        builder.HasIndex(t => new { t.TenantId, t.UserRoleId }).IsUnique();

        builder.Property(b => b.TenantId).HasMaxLength(32).IsRequired();
        builder.Property(b => b.UserRoleId).HasMaxLength(32).IsRequired();
        builder.Property(b => b.CreatorId).HasMaxLength(32).IsRequired();
        builder.Property(b => b.CreationTime).HasDefaultValue(DateTime.Now);
        builder.Property(b => b.LastModificationTime).HasDefaultValue(DateTime.Now);
    }
}

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        if (modelBuilder is null)
        {
            throw new ArgumentNullException(nameof(modelBuilder));
        }

        modelBuilder.ApplyConfiguration(new UserEntityTypeConfiguration());
        modelBuilder.ApplyConfiguration(new RoleEntityTypeConfiguration());
        modelBuilder.ApplyConfiguration(new LotEntityTypeConfiguration());
        modelBuilder.ApplyConfiguration(new LotHistEntityTypeConfiguration());

    }

```

### Include verbose output

```
PM> Update-Database
Build started...
Build succeeded.
[20:47:12 FTL] Application terminated unexpectedly
Microsoft.Extensions.Hosting.HostAbortedException: The host was aborted.
   at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.ThrowHostAborted()
   at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.OnNext(KeyValuePair`2 value)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at Microsoft.Extensions.Hosting.HostBuilder.ResolveHost(IServiceProvider serviceProvider, DiagnosticListener diagnosticListener)
   at Microsoft.Extensions.Hosting.HostApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at Program.<Main>$(String[] args) in E:\Workbench\PSMS\PSMS\Core\src\PSGR.Web\Program.cs:line 67
2024/2/22 20:47:12.355 CoreEventId.SensitiveDataLoggingEnabledWarning[10400] (Microsoft.EntityFrameworkCore.Infrastructure) 
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
2024/2/22 20:47:12.588 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (36ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT CASE WHEN COUNT(*) = 0 THEN FALSE ELSE TRUE END
FROM pg_class AS cls
JOIN pg_namespace AS ns ON ns.oid = cls.relnamespace
WHERE
        cls.relkind IN ('r', 'v', 'm', 'f', 'p') AND
        ns.nspname NOT IN ('pg_catalog', 'information_schema') AND
        -- Exclude tables which are members of PG extensions
        NOT EXISTS (
            SELECT 1 FROM pg_depend WHERE
                classid=(
                    SELECT cls.oid
                    FROM pg_class AS cls
                             JOIN pg_namespace AS ns ON ns.oid = cls.relnamespace
                    WHERE relname='pg_class' AND ns.nspname='pg_catalog'
                ) AND
                objid=cls.oid AND
                deptype IN ('e', 'x')
        )
2024/2/22 20:47:12.661 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (10ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE "SCRM_ROLE_MSCD" (
          "Id" text NOT NULL,
          "TenantId" character varying(32) NOT NULL,
          "UserRoleId" character varying(32) NOT NULL,
          "IsDeleted" boolean NOT NULL,
          "CreationTime" timestamp without time zone NOT NULL DEFAULT TIMESTAMP '2024-02-22T20:47:12.598772',
          "CreatorId" character varying(32) NOT NULL,
          "LastModificationTime" timestamp without time zone DEFAULT TIMESTAMP '2024-02-22T20:47:12.598815',
          "LastModifierId" text,
          CONSTRAINT "PK_SCRM_ROLE_MSCD" PRIMARY KEY ("Id")
      );
...
      Applying migration '20240222120230_init'.
fail: 2024/2/22 20:47:13.586 RelationalEventId.CommandError[20102] (Microsoft.EntityFrameworkCore.Database.Command) 
      Failed executing DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE "SCRM_ROLE_MSCD" (
          "Id" text NOT NULL,
          "TenantId" character varying(32) NOT NULL,
          "UserRoleId" character varying(32) NOT NULL,
          "IsDeleted" boolean NOT NULL,
          "CreationTime" timestamp without time zone NOT NULL DEFAULT TIMESTAMP '2024-02-22T20:02:30.336453',
          "CreatorId" character varying(32) NOT NULL,
          "LastModificationTime" timestamp without time zone DEFAULT TIMESTAMP '2024-02-22T20:02:30.336486',
          "LastModifierId" text,
          CONSTRAINT "PK_SCRM_ROLE_MSCD" PRIMARY KEY ("Id")
      );
Npgsql.PostgresException (0x80004005): 42P07: relation "SCRM_ROLE_MSCD" already exists
   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Migrations.Internal.NpgsqlMigrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
  Exception data:
    Severity: ERROR
    SqlState: 42P07
    MessageText: relation "SCRM_ROLE_MSCD" already exists
    File: heap.c
    Line: 1146
    Routine: heap_create_with_catalog
42P07: relation "SCRM_ROLE_MSCD" already exists
```

### Include provider and version information

EF Core version:
Database provider: (Npgsql.EntityFrameworkCore.PostgreSQL)
Target framework: (NET 8.0)
Operating system:
IDE: (Visual Studio 2022 17.9)

**Comment by yc-2503** [comment]
> In the normal, default way of using Add-Migration and Update-Database, EF definitely doesn't attempt to create the database twice - you're very likely managing your migrations or running these commands incorrectly somehow.
> 
> Unfortunately the above doesn't provide any detail on what you'er actually doing, so we can't really help. If you can submit a runnable, minimal repro - or set of instructions - that shows that problem occurring, we may be able to help further.

This question is the same as mine：[Can't use migrations in EF Core: "42P07: relation "AspNetRoles" already exists" #10368](https://github.com/dotnet/efcore/issues/10368#issue-275819330)

**Comment by yc-2503** [comment]
This is my project [issuedemo](https://github.com/yc-2503/issuedemo)

**Comment by yc-2503** [comment]
I know the cause of the problem now. Because  the Database.EnsureCreated() method was called in the dbcontext's constructor
