### ISSUE TITLE
dotnet-ef isn't packed properly on MacOS

### ISSUE THREAD

**Issue by msaussac** [dotnet/efcore#33165]
## Summary

I am on MacOS and I am trying to use local version of dotnet-ef tool. 
I found and following page : [https://github.com/dotnet/efcore/blob/main/docs/getting-and-building-the-code.md#building-local-packages](url)

I am building local package with :
`./build.sh --pack`

The successfully result :
```
[...]
Successfully created package '[...]/efcore/artifacts/packages/Debug/Shipping/Microsoft.EntityFrameworkCore.Specification.Tests.9.0.0-dev.symbols.nupkg'.

Build succeeded.
    0 Warning(s)
    0 Error(s)
```

In another folder, I created a NuGet.Config file with local packages reference :
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="Local" value="[...]\efcore\artifacts\packages\Debug\Shipping" />
  </packageSources>
</configuration>
```
I generated tool-manifest with :
`dotnet new tool-manifest`

I am trying to install dotnet tool with :
`dotnet tool install dotnet-ef --version 9.0.0-dev --local`

Error : 
```
Unhandled exception: Microsoft.DotNet.ToolPackage.ToolConfigurationException: Entry point file 'dotnet-ef.dll' for command 'dotnet-ef' was not found in the package.
   at Microsoft.DotNet.ToolPackage.ToolPackageInstance.GetCommands()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallLocalCommand.Install(FilePath manifestFile)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
```

I performed the same operation on Windows successfully. 

I am trying to analyze the differences between macOS and Windows nuget package. I am unzipped the package nuget dotnet-ef.9.0.0-dev.nupkg. 
I can't find the file dotnet-ef.dll on macOS.

### Include provider and version information

EF Core version: 8.0.101
Operating system: MacOS Sonoma 14.3.1

**Comment by roji** [comment]
Confirmed, this indeed repros for me, and I can see differences in the produced dotnet-ef.9.0.0-dev.nupkg between Macos and Windows.

@msaussac we'll look into this, but note that in general there's absolutely no need for you to build and use the EF command line tools from the main branch - the CLI package is just a very thin wrapper around EF components (especially the EFCore.Design package). So you should generally be able to use the last version of the ef-tools (8.0.x or the latest published preview) with the latest bits in main - that should unblock anything you're trying to do.

**Comment by msaussac** [comment]
Thanks you for your reply.

I thought at first that the problem is in [https://github.com/dotnet/efcore/blob/main/src/dotnet-ef/dotnet-ef.csproj](url) :
`
<NuspecProperty Include="Output=$(PublishDir)**\*" />
`
and [https://github.com/dotnet/efcore/blob/main/src/dotnet-ef/dotnet-ef.nuspec](url) : 
`
<file src="$Output$" target="tools\$targetFramework$\any" />
`
Maybe, the copy doesn't work properly. I tried doing it file by file but without success.

I would like use the package nuget in order to add a new migration script command in the CLI.

**Comment by AndriySvyryd** [comment]
@roji What's the difference in the produced dotnet-ef.9.0.0-dev.nupkg?

**Comment by roji** [comment]
@AndriySvyryd the one mentioned in the OP - I couldn't see a dotnet-ef.dll in the resulting nupkg generated on MacOS, whereas it did exist in the Windows-generate nupkg.

Let me know if you want me to share the two nupkgs.

**Comment by AndriySvyryd** [comment]
There hasn't been any significant changes to that project in a long time, so I don't think this is a regression. Since the final nupkg should contain .NET Framework binaries it's not even possible to build it on a Mac. At best we could show an error message

**Comment by roji** [comment]
@AndriySvyryd I know very little about how the tooling works... But I think the idea here is to be able to build the nupkg so that it runs on MacOS; since there's no .NET Framework available there, I'm assuming the nupkg maybe contains a netstandard2.0 library or something (otherwise how is the officially-built tool running on MacOS/Linux).

**Comment by AndriySvyryd** [comment]
@roji You can try using `$(ArtifactsBinDir)dotnet-ef\$(Configuration)\$(DefaultNetCoreTargetFramework)\` instead of `$(PublishDir)`

**Comment by AndriySvyryd** [comment]
I'd need a binary log (`artifacts\log\Debug\Build.binlog` produced by `build.sh --pack -bl`) to investigate this further.

**Comment by roji** [comment]
Here you go: [Build.binlog.zip](https://github.com/dotnet/efcore/files/14614447/Build.binlog.zip)

**Comment by gitmln** [comment]
I believe this is some kind of bug in Microsoft tooling that handles Windows and macOS/Linux paths differently. I found a workaround by modifying the .csproj and .nuspec files in the following way (pay attention to the `Output` part)

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    $CommonMetadataElements$
    <packageTypes>
      <packageType name="$packageType$" />
    </packageTypes>
    <readme>docs\PACKAGE.md</readme>
  </metadata>

  <files>
    $CommonFileElements$
    <file src="PACKAGE.md" target="docs\" />
    <file src="$SettingsFile$" target="tools\$targetFramework$\any" />
    <file src="$Output$\**\*" target="tools\$targetFramework$\any" />
    <file src="$OutputBinary$" target="tools\$targetFramework$\any\tools\netcoreapp2.0\any" />
    <file src="$OutputRuntimeConfig$" target="tools\$targetFramework$\any\tools\netcoreapp2.0\any" />
    <file src="$OutputSymbol$" target="tools\$targetFramework$\any\tools\netcoreapp2.0\any" />
  </files>
</package>
```

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Entity Framework Core Tools for the .NET Command-Line Interface.
....

  <Target Name="SetPackageProperties" BeforeTargets="InitializeStandardNuspecProperties" DependsOnTargets="BuiltProjectOutputGroup;DebugSymbolsProjectOutputGroup">
    <PropertyGroup>
      <!-- Make sure we create a symbols.nupkg. -->
      <IncludeSymbols>true</IncludeSymbols>
    </PropertyGroup>

    <ItemGroup>
      <NuspecProperty Include="packageType=$(PackageType)" />
      <NuspecProperty Include="targetFramework=$(TargetFramework)" />

      <NuspecProperty Include="SettingsFile=$(_ToolsSettingsFilePath)" />
      <NuspecProperty Include="Output=$(ArtifactsBinDir)\dotnet-ef\$(Configuration)\$(DefaultNetCoreTargetFramework)" />
      <NuspecProperty Include="OutputBinary=..\..\artifacts\bin\ef\$(Configuration)\netcoreapp2.0\ef.dll" />
      <NuspecProperty Include="OutputRuntimeConfig=..\..\artifacts\bin\ef\$(Configuration)\netcoreapp2.0\ef.runtimeconfig.json" />
      <NuspecProperty Include="OutputSymbol=..\..\artifacts\bin\ef\$(Configuration)\netcoreapp2.0\ef.pdb" />
    </ItemGroup>
  </Target>
</Project>

```
