### ISSUE TITLE
string.Length not translated for raw SqlQuery expressions

### ISSUE THREAD

**Issue by Charlieface** [dotnet/efcore#33272]
**Bug report**

If you take an `IQueryable<string>` generated from a raw SQL query using `context.Database.SqlQuery<string>`, you cannot use `value.Length` on the value. Note that this is not a normal entity query, it's a [Scalar Query](https://learn.microsoft.com/en-us/ef/core/querying/sql-queries#querying-scalar-non-entity-types).

This does, oddly, work if you first call another string function, such as `ToLower`.

This also works fine when used on a normal entity query, even when using `FromSql`.

**Expected result**

A query generated using the `LEN` function, as noted in [Function Mappings](https://learn.microsoft.com/en-us/ef/core/providers/sql-server/functions#string-functions), which is what normally happens, and does work with the `ToLower` added.
```sql
SELECT [t].[Value]
FROM (
    SELECT 'x' AS Value
) AS [t]
WHERE CAST(LEN([t].[Value]) AS int) = 10
```

**Actual result**

`InvalidOperationException` saying the query could not be translated.

**Full simplified repro script:**
```cs
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
					
public class Program
{
    public static void Main()
    {
        var db = new MyDb();
        Console.WriteLine(db.Database.SqlQueryRaw<string>("SELECT 'x' AS Value").Where(s => s.ToLower().Length == 10).ToQueryString());
        Console.WriteLine(db.Database.SqlQueryRaw<string>("SELECT 'x' AS Value").Where(s => s.Length == 10).ToQueryString());
    }
}

public class MyDb : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer("Server=.;Integrated Security=True");
    }
}
```

**Full exception**
```
Unhandled exception. System.InvalidOperationException:
The LINQ expression 'SqlQuery<string>(SELECT 'x' AS Value, __p_0)
    .Where(e => e.Length == 10)' could not be translated.
Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToQueryString(IQueryable source)
   at Program.Main()
```

EF Core version: 7.0.16 and 8.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0 and 8.0

**Comment by roji** [comment]
@cincuranet interested in taking a look?

**Comment by roji** [comment]
@Charlieface please be patient - there's a lot going on and we're sometimes a bit behind on investigations.

**Comment by roji** [comment]
See #34518 which is the true cause of the bug.
