### ISSUE TITLE
ExecuteUpdate fails when assigning a bool based on Any()

### ISSUE THREAD

**Issue by WhatzGames** [dotnet/efcore#33290]
### Include your code

So I've encountered a problem at work today where I tried to create a very simple ExecuteUpdate statement.
Sadly though it was not able to be translated. 

```C#
// See https://aka.ms/new-console-template for more information


using Microsoft.EntityFrameworkCore;

await using CustomContext context = new();

await context.Database.EnsureDeletedAsync();
await context.Database.EnsureCreatedAsync();

await context.ClassA.ExecuteUpdateAsync(x => x.SetProperty(y => y.IsAvailable, y => y.ClassBs.Any()));


public sealed class CustomContext : DbContext
{
    public DbSet<ClassA> ClassA { get; set; }
    public DbSet<ClassB> ClassB { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseNpgsql("Host=localhost;Database=efcore;Username=postgres");
        //optionsBuilder.UseSqlite("Filename=efcore.db");
        base.OnConfiguring(optionsBuilder);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ClassB>()
            .HasOne(x => x.ClassA)
            .WithMany(x => x.ClassBs)
            .HasForeignKey(x => x.ClassAId);
    }
}

public class ClassA
{
    public Guid Id { get; set; }
    public bool IsAvailable { get; set; }
    public ICollection<ClassB> ClassBs { get; set; } = [];
}

public class ClassB
{
    public Guid Id { get; set; }
    public Guid ClassAId { get; set; }

    public ClassA? ClassA { get; set; }
}
```

I can't fully remember what the query should've looked like, but for npgsql it was at least something along the lines of:
```SQL
UPDATE "ClassA" a SET "IsAvailable" = EXISTS(SELECT 1 FROM "ClassB" b WHERE b."ClassAId" = a."Id") 
```

### Stack traces

```
System.InvalidOperationException: The LINQ expression 'DbSet<ClassA>()
    .ExecuteUpdate(x => x.SetProperty<bool>(
        propertyExpression: y => y.IsAvailable, 
        valueExpression: y => y.ClassBs
            .Any()))' could not be translated. Additional information: Translation of member 'ClassBs' on entity type 'ClassA' failed. This commonly occurs when the specified member is unmapped.
The following lambda argument to 'SetProperty' does not represent a valid value: 'y => y.ClassBs
    .Any()'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.RelationalQueryableExtensions.ExecuteUpdateAsync[TSource](IQueryable`1 source, Expression`1 setPropertyCalls, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in F:\projects\c-sharp\EFCoreRepros\EFCoreRepros\Program.cs:line 11
   at Program.<Main>$(String[] args) in F:\projects\c-sharp\EFCoreRepros\EFCoreRepros\Program.cs:line 11
   at Program.<Main>(String[] args)
```

I did search for other reported issues, but I wasn't too sure about whether or not the problem or the source of it was discussed already.
But in any case I suspect it might have to do something with #28627.

### Include provider and version information

EF Core version: 8.0.2
Database provider: Microsoft.EntityFrameworkCore.Sqlite, Npgsql.EntityFrameworkCore.PostgreSQL (Both 8.0.2)
Target framework: .NET 8
Operating system: Windows 11
IDE: Jetbrains Rider 2023.3.3

Edit: removed issue number

**Comment by roji** [comment]
Can you please try extracting the expression out to a Select() before the ExecuteUpdate(), as follows:

```c#
await context.ClassA
    .Select(c => new { c.IsAvailable, Bs = c.ClassBs.Any() })
    .ExecuteUpdateAsync(x => x.SetProperty(y => y.IsAvailable, y => y.Bs));
```

**Comment by WhatzGames** [comment]
> Can you please try extracting the expression out to a Select() before the ExecuteUpdate(), as follows:
> 
> ```cs
> await context.ClassA
>     .Select(c => new { c.IsAvailable, Bs = c.ClassBs.Any() })
>     .ExecuteUpdateAsync(x => x.SetProperty(y => y.IsAvailable, y => y.Bs));
> ```

Yeah, that fixed it for me.
Thanks for the quick reply!
