### ISSUE TITLE
Two different DbConnections in two DbContext. Is it possible?

### ISSUE THREAD

**Issue by Karol-Bladek** [dotnet/efcore#33306]
Hi,

I'm trying to use EF core parallel, and it seems that it cannot be used. Below my code:

```C#
public async Task Handle(BuildIntegrationEventCommand request, CancellationToken cancellationToken)
{
    var buildRequests = await GetIntegrationEventRequestIds(request, cancellationToken);

    if (buildRequests.IsNullOrEmpty())
        return;

    var tasksToRun = new List<Task>();

    int N = 1; // request.ParallelThreadsNo; DOESNT Support parallel execution yet

    int partLength = buildRequests.Count / N;
    int remainingElements = buildRequests.Count % N;

    int startIndex = 0;

    for (int i = 0; i < N; i++)
    {
        int length = partLength + (remainingElements > 0 ? 1 : 0);
        List<Guid> part = buildRequests.GetRange(startIndex, length);

        if(part.Any())
            tasksToRun.Add(Task.Run(async () => await BuildIntegrationEvent(part, cancellationToken)));

        startIndex += length;
        remainingElements--;
    }
    
    await Task.WhenAll(tasksToRun);
}

private async Task BuildIntegrationEvent(List<Guid> buildRequestIds, CancellationToken cancellationToken)
{
    var correlationId = Guid.NewGuid().ToString().ToLower();
    using var logProp = LogContext.PushProperty("CorrelationId", correlationId);

    var transactionOptions = GetTransactionOptions();

    using (var tranScope = new TransactionScope(TransactionScopeOption.RequiresNew, transactionOptions, TransactionScopeAsyncFlowOption.Enabled))
    {
        await using var scope = _serviceScopeFactory.CreateAsyncScope();
        var inScopeDatabase = scope.ServiceProvider.GetRequiredService<DatabaseContext>();
        var inIntegrationEventService = scope.ServiceProvider.GetRequiredService<IIntegrationEventsService>();
        var inSyncBuilder = scope.ServiceProvider.GetRequiredService<IMembershipSyncIntegrationEventBuilder>();

        IList<IntegrationEventBuildRequest> buildRequests = null;

        try
        {
            buildRequests = await inScopeDatabase.IntegrationEventBuildRequests
                .Where(_ => buildRequestIds.Contains(_.IntegrationEventBuildRequestId))
                .ToListAsync(cancellationToken);
```

When the second thread tries to fetch data I've got:

The connection was not closed. The connection's current state is connecting.
Microsoft.Data.SqlClient

at Microsoft.Data.ProviderBase.DbConnectionClosedConnecting.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.InternalOpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenInternalAsync>d__70.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenInternalAsync>d__70.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenAsync>d__66.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteReaderAsync>d__18.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.<InitializeReaderAsync>d__21.MoveNext()
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.<MoveNextAsync>d__20.MoveNext()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__67`1.MoveNext()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__67`1.MoveNext()
   at BayClubs.MemberCore.BackgroundTasks.UseCases.BuildIntegrationEvent.BuildIntegrationEventCommandHandler.<BuildIntegrationEvent>d__4.MoveNext() in C:\Praca\MemberCore-Backend\MemberCore.BackgroundTasks\UseCases\BuildIntegrationEvent\BuildIntegrationEventCommandHandler.cs:line 78

I've tried to use inScopeDatabase.Database.SetDbConnection(MyNewCreatedConnection) but I gave up after many tries.

### Include provider and version information

EF Core version: Assembly Microsoft.EntityFrameworkCore, Version=8.0.2.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: net8.0
Operating system:
IDE: Microsoft Visual Studio 2022 (64-bit) - Current Version 17.9.0

**Comment by ajcvickers** [comment]
Neither of `DbContext` and `DbConnection` are thread safe. See [Avoiding DbContext threading issues](https://learn.microsoft.com/en-us/ef/core/dbcontext-configuration/#avoiding-dbcontext-threading-issues).

**Comment by Karol-Bladek** [comment]
Entity Framework Core does not support multiple parallel operations being run on the same DbContext instance. This includes both parallel execution of async queries and any explicit concurrent use from multiple threads. Therefore, always await async calls immediately, **or use separate DbContext instances for operations that execute in parallel.**

Each Task (BuildIntegrationEvent) gets its own instance of DatabaseContext. Even I've changed registration of DbContext from Scoped to Transient and it doesnt matter.

`services.AddDbContext<DatabaseContext>(options =>
{
    options.UseSqlServer(connection, sqlServerOptionsAction: sqlOptions =>
    {
        sqlOptions.MigrationsAssembly(migrationAssemblyName);
        sqlOptions.UseQuerySplittingBehavior(QuerySplittingBehavior.SingleQuery);
    });
}, ServiceLifetime.Transient)`

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by Karol-Bladek** [comment]
Hi again,

Common methods:

```C#
private SqlConnection GetNewSqlConnection(string usedConnectionString)
{
    SqlConnectionStringBuilder builder = new SqlConnectionStringBuilder();

    string connectionStringFromContext = usedConnectionString;
    builder.ConnectionString = connectionStringFromContext;
    
    return new SqlConnection(builder.ConnectionString);
}

private TransactionOptions GetTransactionOptions()
{
    var transactionOptions = new TransactionOptions
    {
        IsolationLevel = IsolationLevel.ReadCommitted,
        Timeout = TimeSpan.FromSeconds(30) //TransactionManager.MaximumTimeout;
    };

    return transactionOptions;
}
```

So there are two pieces of code. First doesnt work, the second does.

```C#
private async Task BuildIntegrationEventDoesNotWork(List<Guid> buildRequestIds, CancellationToken cancellationToken)
{
    var transactionOptions = GetTransactionOptions();

    using (var tranScope = new TransactionScope(TransactionScopeOption.RequiresNew, transactionOptions, TransactionScopeAsyncFlowOption.Enabled))
    {
        await using var scope = _serviceScopeFactory.CreateAsyncScope();
        var inScopeDatabase = scope.ServiceProvider.GetRequiredService<DatabaseContext>();

        try
        {
            await inScopeDatabase.IntegrationEventBuildRequests
                .Where(_ => buildRequestIds.Contains(_.IntegrationEventBuildRequestId))
                .ToListAsync(cancellationToken);
        }
        catch (Exception ex)
        {
            _logger.Error(ex, $"Error while executing Build Integration Event Background Service");
        }

        tranScope.Complete();
    };
}
```

and example that works properly:
```C#
private async Task BuildIntegrationEventWorks(List<Guid> buildRequestIds, CancellationToken cancellationToken)
{
    var transactionOptions = GetTransactionOptions();

    using (var tranScope = new TransactionScope(TransactionScopeOption.RequiresNew, transactionOptions, TransactionScopeAsyncFlowOption.Enabled))
    {
        await using var scope = _serviceScopeFactory.CreateAsyncScope();
        var inScopeDatabase = scope.ServiceProvider.GetRequiredService<DatabaseContext>();

        inScopeDatabase.Database.SetDbConnection(GetNewSqlConnection(inScopeDatabase.Database.GetConnectionString()), contextOwnsConnection: true);

        try
        {
            await inScopeDatabase.IntegrationEventBuildRequests
                .Where(_ => buildRequestIds.Contains(_.IntegrationEventBuildRequestId))
                .ToListAsync(cancellationToken);
        }
        catch (Exception ex)
        {
            _logger.Error(ex, $"Error while executing Build Integration Event Background Service");
        }

        tranScope.Complete();
    };
}
```

Methods are delegated to asynchronous Task like this:

```C#
for (int i = 0; i < N; i++)
{
    ...
    if(part.Any())
        tasksToRun.Add(Task.Run(async () => await BuildIntegrationEvent(part, cancellationToken)));
    ...
}

var results = await Task.WhenAll(tasksToRun);
```

As I wrote previosly DatabaseContext are different instances (according to ContextId). It seems that in "wrong code", they both share the same DbCnnection.

**Comment by ajcvickers** [comment]
@Karol-Bladek This is still missing important information, such as how the application is managing context and connection instances. Please attach a small, **runnable** project or post a small, **runnable** code listing that reproduces what you are seeing so that we can investigate.

**Comment by Karol-Bladek** [comment]
Hi @ajcvickers , You are right, I missed something...
I did a runnable project which showed me that Ef Core works as expected..

```C#
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging.Console;
using Microsoft.Extensions.Logging;
using System.Reflection;
using System.ComponentModel;


public class Consts
{
    public const string ConnectionString = @"Server=.\\SQLEXPRESS;Database=DatabaseContextTest;Trusted_Connection=True;MultipleActiveResultSets=True;TrustServerCertificate=True;";
}

public class Customer
{
    public int Id { get; set; }
}

public class DatabaseContext : DbContext
{
    public DbSet<Customer> Customers { get; set; }

    public DatabaseContext(DbContextOptions<DatabaseContext> options)
            : base(options)
    {
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
    }
}

public class Worker
{
    private readonly IServiceScopeFactory _serviceScopeFactory;

    public Worker(IServiceScopeFactory serviceScopeFactory)
    { 
        _serviceScopeFactory = serviceScopeFactory;
    }

    public async Task ReadInManyThreads()
    {
        await Task.WhenAll(new[]
        {
            Task.Run(async () => await SampleRead(TimeSpan.FromSeconds(2))),
            Task.Run(async () => await SampleRead(TimeSpan.FromSeconds(3))),
            Task.Run(async () => await SampleRead(TimeSpan.FromSeconds(2))),
            Task.Run(async () => await SampleRead(TimeSpan.FromSeconds(4)))
        });
    }

    private async Task SampleRead(TimeSpan timeSpan)
    {
        await using (var scope = _serviceScopeFactory.CreateAsyncScope())
        {
            try
            {
                var context = scope.ServiceProvider.GetRequiredService<DatabaseContext>();

                var customers = await context.Customers.ToListAsync();

                Thread.Sleep(timeSpan);

                await context.Customers.ToListAsync();

                Console.WriteLine($"ContextId: {context.ContextId} read {customers.Count} customers");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }
    }
}

class Program
{
    static void Main(string[] args)
    {
        var host = CreateHostBuilder(args).Build();

        SeedData(host);
        RunWorkers(host);

        host.Run();        
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureServices((hostContext, services) =>
            {
                services.AddDbContext<DatabaseContext>(options =>
                    options.UseSqlServer(Consts.ConnectionString, sqlOptions =>
                    {
                        sqlOptions.MigrationsAssembly(typeof(DatabaseContext).GetTypeInfo().Assembly.GetName().Name);
                    })
                , ServiceLifetime.Scoped, ServiceLifetime.Scoped);

                services.AddTransient<Worker>();
            })
            .ConfigureLogging((hostContext, logging) =>
            {
                logging.AddFilter("Microsoft.EntityFrameworkCore.Database.Command", LogLevel.Warning);
            });

    private static void SeedData(IHost host)
    {
        using (var scope = host.Services.CreateScope())
        {
            var services = scope.ServiceProvider;
            try
            {
                var context = services.GetRequiredService<DatabaseContext>();

                context.Database.Migrate();

                for (var i = 0; i < 3000000; i++)
                {
                    context.Customers.Add(new Customer());
                }

                context.SaveChanges();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }
    }

    private async static void RunWorkers(IHost host)
    {
        using (var scope = host.Services.CreateScope())
        {
            var services = scope.ServiceProvider;
            try
            {
                var worker = services.GetRequiredService<Worker>();

                await worker.ReadInManyThreads();                
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }
    }
}
```

When I started digging deeper in my configuration I noticed that I pass SqlConnection instance instead connection string. This causes, that every Instance of DatabaseContext used the same DbConnection....

**WRONG**
```C#
var connection = new SqlConnection(Aliases.Map(connectionString));
var migrationAssemblyName = typeof(DatabaseContext).GetTypeInfo().Assembly.GetName().Name;

services.AddDbContext<DatabaseContext>(options =>
{
    options.UseSqlServer(connection , sqlServerOptionsAction: sqlOptions =>
    {
        sqlOptions.MigrationsAssembly(migrationAssemblyName);
        sqlOptions.UseQuerySplittingBehavior(QuerySplittingBehavior.SingleQuery);
    });
})
```
**SEEMS TO BE GOOD**
```C#
services.AddDbContext<DatabaseContext>(options =>
{
    options.UseSqlServer(connectionString, sqlServerOptionsAction: sqlOptions =>
    {
        sqlOptions.MigrationsAssembly(migrationAssemblyName);
        sqlOptions.UseQuerySplittingBehavior(QuerySplittingBehavior.SingleQuery);
    });
})
```

Thank you very much! Have a nice day!
