### ISSUE TITLE
ValueConverter not applied to operands on ExecuteUpdateAsync 

### ISSUE THREAD

**Issue by Danielku15** [dotnet/efcore#33330]
When upgrading from EFCore7 to EFCore8 the code below doesn't work anymore. In EFCore7 the ValueConverter configured on the property was applied to the TimeSpan operand making the update successful. 

In EFCore8 the ValueConverter is not applied anymore to the expression and the SQL translates to a string which leads to an exception.  

### Include your code

```C#
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

var services = new ServiceCollection()
    .AddLogging(l =>
    {
        l.SetMinimumLevel(LogLevel.Trace);
        l.AddConsole();
    })
    .AddDbContext<MyDbContext>(o=>
    {
        o.EnableSensitiveDataLogging();
        o.UseSqlServer("Data Source=(local);Integrated Security=SSPI;Database=EFCore8TimeSpanModify;MultipleActiveResultSets=True;Trust Server Certificate=true;");
    }, ServiceLifetime.Singleton)
    .BuildServiceProvider();

var context = services.GetRequiredService<MyDbContext>();
await context.Database.EnsureCreatedAsync();

var entity = new WithTimeSpan { TimeSpan = TimeSpan.FromTicks(100) };
await context.AddAsync(entity);
await context.SaveChangesAsync();

var interval = TimeSpan.FromTicks(10);
await context.WithTimeSpans.ExecuteUpdateAsync(x =>
    x.SetProperty(e => e.TimeSpan, e => e.TimeSpan + interval)
);

class WithTimeSpan
{
    public int Id { get; set; }
    public TimeSpan TimeSpan { get; set; }
}

class MyDbContext : DbContext
{
    public DbSet<WithTimeSpan> WithTimeSpans => Set<WithTimeSpan>();

    public MyDbContext(DbContextOptions<MyDbContext> o) : base(o)
    {
    }
    
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<WithTimeSpan>(e =>
        {
            e.HasKey(x => x.Id);
            e.Property(x => x.Id).ValueGeneratedOnAdd();
            e.Property(x => x.TimeSpan)
                .HasColumnType("bigint")
                .HasConversion(v => v.Ticks,
                    v => TimeSpan.FromTicks(v));
        });
    }
}
```

### Include stack traces

```
Microsoft.Data.SqlClient.SqlException (0x80131904): Operand type clash: time is incompatible with bigint
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<InternalExecuteNonQueryAsync>b__210_1(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in D:\Dev\Git\EFCore8TimeSpanModify\EFCore8TimeSpanModify\EFCore8TimeSpanModify\Program.cs:line 26
   at Program.<Main>(String[] args)

```

### Include provider and version information

EF Core version: 8.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows 11
IDE: Rider 2023.3.4

### Entry point of difference

In v7 a special trick was used to translate a setter expression and unwrap it. The translated SQL expression has the ValueConverter set: 

https://github.com/dotnet/efcore/blob/c9d1c2d28f509244ffe9ad61a46d1d81f89ddd2f/src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs#L1372
![image](https://github.com/dotnet/efcore/assets/674916/f51735f6-f006-4ea4-b0da-c8befb3a3785)

In v8 this type mapping is not applied at the respective location leading to an invalid SQL:
https://github.com/dotnet/efcore/blob/c2f996919858eb11d2836705d47b531b5a174c79/src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs#L1555-L1564
![image](https://github.com/dotnet/efcore/assets/674916/594cafe5-4b1b-41e7-a125-b4ce53a4f7c5)

**Comment by Danielku15** [comment]
I tried a local hack in our project where we luckily have a custom SqlServerSqlTranslatingExpressionVisitor registered. Its far from clean but applying the type mapping of the left expression to the right expression ensures the correct SQL:

I wouldn't call this a feasable workaround but rather a proof that something with the type mappings is either missing or not supported well. 

```cs
internal class CustomSqlServerSqlTranslatingExpressionVisitor : SqlServerSqlTranslatingExpressionVisitor
{
    public CustomSqlServerSqlTranslatingExpressionVisitor(
        RelationalSqlTranslatingExpressionVisitorDependencies dependencies,
        SqlServerQueryCompilationContext queryCompilationContext,
        QueryableMethodTranslatingExpressionVisitor queryableMethodTranslatingExpressionVisitor)
        : base(dependencies,
            queryCompilationContext,
            queryableMethodTranslatingExpressionVisitor)
    {
    }

    protected override Expression VisitBinary(BinaryExpression binaryExpression)
    {
        // https://github.com/dotnet/efcore/issues/33330
        // x => x.TimeSpanProp + timeSpanVariable
        // x => x.TimeSpanProp + TimeSpan.FromSeconds(1)
        // x => x.TimeSpanProp - timeSpanVariable
        // x => x.TimeSpanProp - TimeSpan.FromSeconds(1)
        if (binaryExpression.NodeType is ExpressionType.Add or ExpressionType.Subtract &&
            binaryExpression.Left.Type == typeof(TimeSpan) &&
            binaryExpression.Left.NodeType == ExpressionType.MemberAccess &&
            binaryExpression.Right.Type == typeof(TimeSpan) &&
            binaryExpression.Right.NodeType is ExpressionType.Parameter or ExpressionType.Constant)
        {
            var original = base.VisitBinary(binaryExpression);
            if (original is SqlBinaryExpression { Left.TypeMapping.Converter: not null } sqlBinaryExpression
               )
            {
                return sqlBinaryExpression.Right switch
                {
                    SqlParameterExpression r => sqlBinaryExpression.Update(sqlBinaryExpression.Left,
                        r.ApplyTypeMapping(sqlBinaryExpression.Left.TypeMapping)),
                    SqlConstantExpression r => sqlBinaryExpression.Update(sqlBinaryExpression.Left,
                        r.ApplyTypeMapping(sqlBinaryExpression.Left.TypeMapping)),
                    _ => original
                };
            }
        }

        return base.VisitBinary(binaryExpression);
    }
}
```

**Comment by Danielku15** [comment]
I can confirm that this code seems to be the root cause. I enabled the hidden switch for enabling the old behavior and it generates the right SQL afterwards. 

https://github.com/dotnet/efcore/blob/c2f996919858eb11d2836705d47b531b5a174c79/src/EFCore.Relational/Query/SqlExpressionFactory.cs#L210-L213
