### ISSUE TITLE
Comparing Guids with Contains results in an Exception: 'SQLite Error 1: 'no such function: unhex'.

### ISSUE THREAD

**Issue by ulrik-nilsson-netclean** [dotnet/efcore#33411]
After upgrading to EF8 comparing Guids with Contains results in an Exception: 'SQLite Error 1: 'no such function: unhex'.' It worked without Exception in EF7.

Im using Microsoft.EntityFrameworkCore.SqlLite.Core with SQLitePCLRaw.bundle_e_sqlcipher and store Guids as byte[]. When changing to another SQLitePCLRaw bundle or storing the Guids as text I dont get the Exception.

This is a minimum setup:
```C#
public class TestContext : DbContext
{
    public TestContext(DbContextOptions options) : base(options)
    {
    }
    public virtual DbSet<Foo> Foo { get; set; }

    protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
    {
        configurationBuilder.Properties<Guid>().HaveConversion<byte[]>();
    }
}

public class Foo
{
    public Guid Identifier{ get; set; }
    [Key]
    public int Nyckel{ get; set; }
}
```

With this setup and running:

```C#
var uids = new List<Guid> { Guid.NewGuid() };
testContext.Foo.FirstOrDefault(w => uids.Contains(w.Identifier))
```

Gives the error
```
  Microsoft.Data.Sqlite.SqliteException
  HResult=0x80004005
  Message=SQLite Error 1: 'no such function: unhex'.
  Source=Microsoft.Data.Sqlite
  StackTrace:
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.<PrepareAndEnumerateStatements>d__64.MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.<GetStatements>d__54.MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.<>c.<MoveNext>b__21_0(DbContext _, Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
```

### Include provider and version information

EF Core version: 8.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlLite.Core with SQLitePCLRaw.bundle_e_sqlcipher
Target framework: .NET 8.0
Operating system: Windows
IDE: Visual Studio 2022 17.9.2

**Comment by roji** [comment]
@ulrik-nilsson-netclean be sure to use at least SQLite 3.41.1, which introduces the unhex version that EF depends on ([release notes](https://www.sqlite.org/releaselog/3_41_1.html)).

**Comment by roji** [comment]
Otherwise, storing GUIDs as text as also a reasonable way to do things.
