### ISSUE TITLE
No suitable constructor was found for entity type 'CollectionEntry'

### ISSUE THREAD

**Issue by RDoser** [dotnet/efcore#33469]
`CollectionEntry` is not  a type in my solution. Isn't it part of the Entity Core ChangeTracker? Here's the full error details:

### Error Details
```
System.InvalidOperationException
  HResult=0x80131509
  Message=No suitable constructor was found for entity type 'CollectionEntry'. The following constructors had parameters that could not be bound to properties of the entity type: 
    Cannot bind 'internalEntry', 'name' in 'CollectionEntry(InternalEntityEntry internalEntry, string name)'
    Cannot bind 'internalEntry', 'navigationBase' in 'CollectionEntry(InternalEntityEntry internalEntry, INavigationBase navigationBase)'
Note that only mapped properties can be bound to constructor parameters. Navigations to related entities, including references to owned types, cannot be bound.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ConstructorBindingFactory.GetBindings[T](T type, Func`5 bindToProperty, Func`5 bind, InstantiationBinding& constructorBinding, InstantiationBinding& serviceOnlyBinding)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ConstructorBindingFactory.GetBindings(IMutableEntityType entityType, InstantiationBinding& constructorBinding, InstantiationBinding& serviceOnlyBinding)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.ConstructorBindingConvention.ProcessModelFinalizing(IConventionModelBuilder modelBuilder, IConventionContext`1 context)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelFinalizing(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelFinalizing(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FinalizeModel()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_ChangeTracker()
   at HCAEntities.Models.HighlandEntities..ctor(ConnectionMethod cm) in C:\Users\randa\Highland Capital Dropbox\Randall Doser\Visual Studio\Projects\HiPRA2\HCAEntities\HighlandModelPartial.cs:line 190
   at HCAEntities.Models.HighlandEntities.get_Context() in C:\Users\randa\Highland Capital Dropbox\Randall Doser\Visual Studio\Projects\HiPRA2\HCAEntities\HighlandModelPartial.cs:line 125
   at HiPRA.ReportsWindow.get_Context() in C:\Users\randa\Highland Capital Dropbox\Randall Doser\Visual Studio\Projects\HiPRA2\HiPRA\ReportsWindow.xaml.cs:line 169
   at HiPRA.ReportsWindow..ctor(Window login) in C:\Users\randa\Highland Capital Dropbox\Randall Doser\Visual Studio\Projects\HiPRA2\HiPRA\ReportsWindow.xaml.cs:line 195
   at HiPRA.LoginDialog.btnLogin_Click(Object sender, RoutedEventArgs e) in C:\Users\randa\Highland Capital Dropbox\Randall Doser\Visual Studio\Projects\HiPRA2\HiPRA\LoginDialog.xaml.cs:line 114

  This exception was originally thrown at this call stack:
    [External Code]
    HCAEntities.Models.HighlandEntities.HighlandEntities(HCAEntities.Models.ConnectionMethod) in HighlandModelPartial.cs
    HCAEntities.Models.HighlandEntities.Context.get() in HighlandModelPartial.cs
    HiPRA.ReportsWindow.Context.get() in ReportsWindow.xaml.cs
    HiPRA.ReportsWindow.ReportsWindow(System.Windows.Window) in ReportsWindow.xaml.cs
    HiPRA.LoginDialog.btnLogin_Click(object, System.Windows.RoutedEventArgs) in LoginDialog.xaml.cs
```

### Include provider and version information

EF Core version: 8.0.3
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8
Operating system: Windows 11
IDE: Visual Studio 2022 17.4

**Comment by RDoser** [comment]
The project is rather unwieldy so I don't think a git share would be much help. I was able to [work around the error](https://github.com/dotnet/efcore/issues/33467) though so I'm going to close this one. Thanks!

**Comment by RDoser** [comment]
It will remain a mystery...

**Comment by RDoser** [comment]
@ajcvickers, @ErikEJ  My workaround was really just a traffic circle back to the same error. 😞 Not  a total waste of time as it resulted in a Git repo that I can share that will reproduce the error. Should I post a new error or can this one be re-opened?

**Comment by ErikEJ** [comment]
I ran your repro and got no errors (chose "l" option)

**Comment by RDoser** [comment]
No, You need to set startup project to HCAEntitiesPartials (a windows wpf app). The HCAEntitiesCore is a self contained console app that doesn't have any of the partial classes, just the basic properties and database relationships and it does indeed run with no errors.

**Comment by RDoser** [comment]
@ErikEJ Sorry to bother, but not sure if anyone is still looking at this. Considering re-posting as a new issue. If you are working on it I don't want to gum up the works by re-posting.

**Comment by ErikEJ** [comment]
You need to provide a runnable repro. I did not see the WPF project in your repro and no instructions.

**Comment by RDoser** [comment]
@ErikEJ My apologies. I'm a noob at Git and majorly screwed up that repository so it wasn't syncing my changes. I deleted it and started over and sent you an invite to the new one. Sorry for wasting your time. Please let me know if the new one doesn't work or if the readme isn't clear. I really appreciate you guys!

**Comment by ErikEJ** [comment]
I cannot build the solution, and you are mixing .NET 8 and .NET Framework projects - that does not work.

**Comment by RDoser** [comment]
@ErikEJ Again, I apologize. I should have tested the repo and cleaned up the references. I have done that now and was able to clone it and run it.

**Comment by RDoser** [comment]
@ErikEJ Not sure if you saw my previous message. I think the repo is fixed if you would like to see the error I'm getting. Happy to repost this as a new issue.
