### ISSUE TITLE
"Library e_sqlite3 not found" on .Net Framework 4.7.2 (SDK-style project)

### ISSUE THREAD

**Issue by alexey-leonovich** [dotnet/efcore#33472]
### Include your code

1. In Visual Studio 2022 create new console application. Keep .NET 8.0 target to ensure project is SDK-style
2. Change project file - set `<TargetFramework>net472</TargetFramework>`
3. Reference latest stable Microsoft.Data.Sqlite 8.0.3
4. In Program.cs try to create a connection via using `(var connection = new SqliteConnection("Data Source=test.sqlite")) {}`
5. Launch application to get an error (despite of **D:\tests\ConsoleApp1\ConsoleApp1\bin\Debug\net472\e_sqlite3.dll** present): 
> Library e_sqlite3 not found
> plat: win
> suffix: DLL
> possibilities (2):
>     1) D:\tests\ConsoleApp1\ConsoleApp1\bin\Debug\net472\runtimes\win-x64\native\e_sqlite3.dll
>     2) D:\tests\ConsoleApp1\ConsoleApp1\bin\Debug\net472\e_sqlite3.dll
> win TryLoad: D:\tests\ConsoleApp1\ConsoleApp1\bin\Debug\net472\runtimes\win-x64\native\e_sqlite3.dll
> thrown: System.ComponentModel.Win32Exception (0x80004005): The specified module was not found
>    at SQLitePCL.NativeLibrary.TryLoad(String name, Loader plat, Action`1 log, IntPtr& h)
> win TryLoad: D:\tests\ConsoleApp1\ConsoleApp1\bin\Debug\net472\e_sqlite3.dll
> thrown: System.ComponentModel.Win32Exception (0x80004005): %1 is not a Win32 application
>    at SQLitePCL.NativeLibrary.TryLoad(String name, Loader plat, Action`1 log, IntPtr& h)
> NOT FOUND

My sample application - [ConsoleApp1.zip](https://github.com/dotnet/efcore/files/14861990/ConsoleApp1.zip)

P. S. Issue reproduces with library versions 8.0.x, 7.0.x, 6.0.x and 3.1.32. Same code is working correctly with versions <= 3.1.31 and 5.0.x.
### Include stack traces

```
The initializer of type "Microsoft.Data.Sqlite.SqliteConnection" gave an exception.

   at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
   at ConsoleApp1.Program.Main(String[] args) в D:\tests\ConsoleApp1\ConsoleApp1\Program.cs:строка 12

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.Data.Sqlite.SqliteConnection..cctor()

   at SQLitePCL.NativeLibrary.Load(String libraryName, Assembly assy, Int32 flags)
   at SQLitePCL.Batteries_V2.MakeDynamic(String name, Int32 flags)
   at SQLitePCL.Batteries_V2.DoDynamic_cdecl(String name, Int32 flags)
   at SQLitePCL.Batteries_V2.Init()
```

### Include version information

Microsoft.Data.Sqlite version: 8.0.x, 7.0.x, 6.0.x and 3.1.32
Target framework: .NET Framework 4.7.2
Operating system: Windows 10 22H2 Pro 64bit

**Comment by cincuranet** [comment]
For .NET 4.7.2 you need to add into your _csproj_ `<PlatformTarget>x64</PlatformTarget>`.
