### ISSUE TITLE
DbSet AddRange is not inserting the whole range of entries, if an exception is thrown in at least one of them. Is this expected?

### ISSUE THREAD

**Issue by gbrandtio** [dotnet/efcore#33490]
## Ask a question
The setup that I'm working on is as follows:

**SQL Server Database**
I'm working with an SQL Server database that has a table, let's call it `OCCURRENCES` with a column `hash` that is marked as a `UNIQUE_KEY`. `hash` is `VARCHAR(50)`.

On my .NET application I'm inserting some entries to the table as follows:

```
_context.Occurrences.AddRange(receivedOccurrences);
```

At this point, there are certain occasions where I'm receiving an exception about the duplicate entries, similar to the below:
```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 Unhandled exception.---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.OCCURRENCES' with unique index 'IX_Hash'. The duplicate key value is (ac9c88826ceff7b653f8eea8fb1f8acd).
The statement has been terminated.
   at Microsoft.Data.SqlClient.Sq lConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
```

Even though it does make sense from a C# perspective (an Exception is thrown, so the LINQ terminates and the flow control continues/exits), I wouldn't expect this to happen in the context of EF - instead I would expect _only one entry_ to not be inserted, which is the one that is duplicate.

Since I'm new to EF, I might be missing something. In that case could you please specify alternatives that I could utilize to avoid that behavior (except from using a `for` or `while` loop.

### Provider and version information

EF Core version: 7.0.22.51807
Database provider: SQL Server
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.7.3

**Comment by cincuranet** [comment]
This does not happen during LINQ, but during `SaveChanges` phase. What you can do - assuming you don't know the colliding values in advance -, is catch the `DbUpdateException` and inspect the [`Entries`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbupdateexception.entries?view=efcore-8.0#microsoft-entityframeworkcore-dbupdateexception-entries) property. That will give you information about which entities failed. With that you can handle it - i.e. ignore those or fetch current values and update or ...

**Comment by gbrandtio** [comment]
This is a very good point actually. Something like retrying the insertion, but by having the duplicate values removed, right ?
Nevertheless, it would be a nice feature to have.

**Comment by roji** [comment]
To add to @cincuranet's comments, this area is pretty extensively documented (e.g. [see concurrency conflicts](https://learn.microsoft.com/en-us/ef/core/saving/concurrency?tabs=data-annotations)).

**Comment by gbrandtio** [comment]
For anyone that might be ending up on this, what I ended up doing is clearing the `DbContext`. This is because it seems that even if you have had something like the below:

```
public void Save() {
  foreach (var entry in entries) {
    _context.SomeDbSet.Add(entry);
  }
}

private void SaveChanges() {
  try {
    _context.SaveChanges();
  }
  catch (Exception e) {
    // do something with the exception
  }
}
```
and assuming that the first entry in the `entries` is duplicate, it will still end up throwing an exception (and not inserting) the rest of the entries as well. 

So, one could do something like the below instead of the above:

```
public void Save() {
  foreach (var entry in entries) {
    _context.SomeDbSet.Add(entry);
  }
}

private void SaveChanges() {
  try {
    _context.SaveChanges();
  }
  catch (Exception e) {
    // do something with the exception
  }
  finally {
    _context.ChangeTracker.Clear();
  }
}
```
