### ISSUE TITLE
Using a certain GUID in a condition results Specified method is not supported.

### ISSUE THREAD

**Issue by PupuCz** [dotnet/efcore#33532]
Hello,
I've encountered a weird behavior when trying to filter by a certain GUID. I'm using EntityFramework core 8.0.4 in asp.net .NET 8.0 app. Visual studio 2022 17.9.5 and database is Mssql. In the code below I've created 2 guid lists by parsing guids from strings. It seems like both guids are valid, executing query with both guids works normally in MSSQL. 

`var id = new List<Guid> { Guid.Parse("9826F00E-2E91-48A5-982B-0CE6AE99470D") };
var id2 = new List<Guid> { Guid.Parse("7977D38C-90C7-4478-AA56-3BC19CDAD352") };

var a = await Context.SuperAdminActors.Where(a => id2.Contains(a.UserId)).ToListAsync(); //this goes through
var b = await Context.SuperAdminActors.Where(a => id.Contains(a.UserId)).ToListAsync(); //here I get Specified method is not supported.`

Stack trace
```
   at System.Linq.ThrowHelper.ThrowNotSupportedException()
   at System.Linq.EmptyPartition`1.System.Collections.Generic.ICollection<TElement>.Add(TElement item)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrICollectionAccessor`3.AddStandalone(Object collection, Object value)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrICollectionAccessor`3.Add(Object entity, Object value, Boolean forMaterialization)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.AddToCollection(INavigationBase navigationBase, Object value, Boolean forMaterialization)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.AddToCollection(InternalEntityEntry entry, INavigationBase navigation, InternalEntityEntry value, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.SetReferenceOrAddToCollection(InternalEntityEntry entry, INavigationBase navigation, InternalEntityEntry value, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.ToDependentFixup(InternalEntityEntry dependentEntry, InternalEntityEntry principalEntry, IForeignKey foreignKey, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.InitialFixup(InternalEntityEntry entry, InternalEntityEntry duplicateEntry, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.StateChanged(InternalEntityEntry entry, EntityState oldState, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.StateChanged(InternalEntityEntry entry, EntityState oldState, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.MarkUnchangedFromQuery()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTrackingFromQuery(IEntityType baseEntityType, Object entity, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.QueryContext.StartTracking(IEntityType entityType, Object entity, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.<MoveNextAsync>d__20.MoveNext()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__67`1.MoveNext()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__67`1.MoveNext()
   at Connectify.Data.Components.Users.UserComponent.<LoadUserActorsAsync>d__3.MoveNext() in C:\Users\jaros\source\repos\PupuCz\app.connectify\Connectify.Data\Components\Users\UserComponent.cs:line 64
   at app.connectify.Components.Account.UserStore.<>c__DisplayClass10_0.<<FindByNameAsync>b__0>d.MoveNext() in C:\Users\jaros\source\repos\PupuCz\app.connectify\app.connectify\Components\Account\UserStore.cs:line 134
```

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by PupuCz** [comment]
Ok, I understand. I think I'll close this issue for now and open a new one with a more fitting title and more details. once I'm able to isolate the issue I found that the issue is not connected directly to the GUID value, but rather to the entity with this guid. Looks like there was some issue in the query interpretation due to some issue with complex structure of base classes and their descendants.
