### ISSUE TITLE
Precompiled queries: support value converters

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#33541]
We have a general problem with the "quotability" of type mappings. That is, when a type mapping is encountered somewhere when precompiling a query, we need to be able to generate code that finds/creates the same type mapping when the program actually starts up. In the shaper, in most cases we know the type mapping's property, so we can generate a lookup for that property on the model, and get the type mapping from there. But when generating the SQL tree (or the TypeMappedRelationalParameter directly, when pregenerating SQL), we don't have the property, since nodes in the SQL tree only reference the type mapping directly.

At the moment, we're faking it by generating code that simply instantiates the type mapping given the various facets (store type, size...); but this doesn't work for value converters (and comparers). As a short-term solution, we should be able to pass in the value converter directly as a lambda, assuming that lambda is generatable as C# (i.e. doesn't capture some external state). But long-term, we need a more general mechanism for type mapping quotability, where e.g. the type mapping would reference its originating property, so that we can generate a model lookup for that.

/cc @ajcvickers

**Comment by maumar** [comment]
related: https://github.com/dotnet/efcore/issues/33517

**Comment by connorivy** [comment]
@roji Are there any workarounds currently for using efcore with nativeaot while having some entities with custom types that are mapped to the db with valueconverters? I currently can't use the `optimize --nativeaot` command because it fails with this error 

`Encountered a constant of unsupported type 'StrongId'. Only primitive constant nodes are supported.`

**Comment by roji** [comment]
@connorivy unfortunately not, there's no workaround at this time. Note that precompiled queries are experimental and don't yet cover all scenarios.

**Comment by donpanl** [comment]
It seems I encountered a problem that follows from this issue, but I'm not sure.

In my case, `Blog` entity has a property of type `Name`, which is configured with a value converter in DbContext. There is also a query which uses the variable of type `Name` in predicate of `.Where()`.

The query is precompiled and then fails at runtime with an exception:

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypeMappedRelationalParameter.AddDbParameter(DbCommand command, Object value)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBase.AddDbParameter(DbCommand command, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.CreateDbCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.<>c.<MoveNext>b__21_0(DbContext _, Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.GeneratedInterceptors.<Program_EFInterceptors_Context>F3BE7D8409D38C63D1BC242788030659D7E7EDFEBFF077464DCF27CCCE76F294B__EntityFrameworkCoreInterceptors.Query1_ToList2[TSource](IEnumerable`1 source) in /workspaces/ef-play/typemap/Generated/Program.EFInterceptors.Context.cs:line 55
   at Program.<Main>$(String[] args) in /workspaces/ef-play/typemap/Program.cs:line 6
```

The cause, as I understand it, is this line from the precompiled query code, which calls `TypeMappedRelationalParameter` ctor:

```
var relationalCommandTemplate0 = ((IRelationalCommandTemplate)(new RelationalCommand(commandBuilderDependencies, "SELECT \"b\".\"Id\", \"b\".\"Name\"\nFROM \"Blogs\" AS \"b\"\nWHERE \"b\".\"Name\" = @name", "SELECT \"b\".\"Id\", \"b\".\"Name\"\nFROM \"Blogs\" AS \"b\"\nWHERE \"b\".\"Name\" = @name", new IRelationalParameter[] { new TypeMappedRelationalParameter("name", "@name", relationalTypeMappingSource.FindMapping(typeof(Name), "TEXT", false, false, (int? )(null), false, false, (int? )(null), (int? )(null)), true, ParameterDirection.Input) })));
```

Here, `relationalTypeMappingSource.FindMapping(typeof(Name), ...)` call cannot find the type mapping for `Name` type, that's why the call to `TypeMappedRelationalParameter.AddDbParameter()` fails later.

To work around this, I injected an implementation of `IRelationalTypeMappingSourcePlugin` into DbContext, which returns a type mapping for `Name`.

Attached a project which demonstrates the problem.

[typemap.zip](https://github.com/user-attachments/files/26246492/typemap.zip)
