### ISSUE TITLE
Exception when select over an empty left join

### ISSUE THREAD

**Issue by YeskaNova** [dotnet/efcore#33581]
Hi,

If an object references another object from a nullable property ( meaning, EF Core is capable of knowing that it might not exist ), If we select any property from that referenced object, instead of receiving null, an exception is thrown.

```C#
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

public class Person
{
    public int Id { get; set; }
}
public class Animal
{
    public int Id { get; set; }
    public Person? Owner { get; set; }
}

public class SqlServerDbContext : DbContext
{
    public SqlServerDbContext(DbContextOptions options) : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Person>();
        modelBuilder.Entity<Animal>();
    }
}

class Program
{
    static void Main(string[] args)
    {
        var sc = new ServiceCollection();
        var guid = Guid.NewGuid();
        sc.AddDbContext<SqlServerDbContext>(op => op.UseSqlServer(@"Server=(localdb)\MSSQLLocalDB;Integrated Security=true;DataBase=" + guid));
        using (var provider = sc.BuildServiceProvider())
        {
            using (var scope = provider.CreateScope())
            using (var dbcontext = scope.ServiceProvider.GetService<SqlServerDbContext>())
            {
                dbcontext.Database.EnsureCreated();
                dbcontext.Set<Animal>().Add(new Animal());
                dbcontext.SaveChanges();
                var ownerId = dbcontext.Set<Animal>().Select(x => x.Owner.Id).First();
            }
        }

    }
}
```

```
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_NoValue()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.First[TSource](IQueryable`1 source)
```

EF Core version: Microsoft.EntityFrameworkCore 8.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer 8.0.4
Target framework: .NET 8.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.4

**Comment by maumar** [comment]
This is by design. In those cases EF will protect you from null refs, but you need to manually manage the type of elements that are being projected. Solution here is to cast the projection to `int?` 

```cs
var ownerId = dbcontext.Set<Animal>().Select(x => (int?)x.Owner.Id).First();
```
