### ISSUE TITLE
GroupBy issues

### ISSUE THREAD

**Issue by sexyDaniel** [dotnet/efcore#33663]
### Repo
[SimpleRepo.zip](https://github.com/dotnet/efcore/files/15191240/SimpleRepo.zip)

### Include your code

CountryId is a nullable field. When I try to get a result after applying GroupBy, I get the error "Nullable object must have a value" if there is at least one record in the database where CountryId = null.

```C#
var group = context.Companies.GroupBy(x => new { x.CountryId });
var groupRes = group.ToList();// if there are records in the database with the countryId == null, then there will be an error (Nullable object must have a value)
```

If I try to group by fields x.CountryId, x.Id , then I always get the error "Value cannot be null. (Parameter 'collection')'"

```C#
var group1 = context.Companies.GroupBy(x => new { x.CountryId, x.Id });
var groupres1 = group1.ToList();// Always a exception (Value cannot be null. (Parameter 'collection')')
```

If I want to apply select after groupBy, then everything is correct

```C#
var select1 = group.Select(x => new { x.Key }); // OK
var select2 = group.Select(x=>new {x.Key, C = x.ToArray() }); // OK
var select3 = group1.Select(x => new { x.Key }); // OK
var select4 = group1.Select(x => new { x.Key, C = x.ToArray() }); // OK
```

If I want to apply sum() from the grouped elements and there is something like x.toArray() in Select, then this leads to the error "Nullable object must have a value". Moreover, it does not depend on whether there are records in the database with CountryId = nul or not.

```C#
var sum1 = select1.Sum(x => x.Key.CountryId); // OK
var sum2 = select2.Sum(x => x.Key.CountryId); // (Nullable object must have a value)
var sum3 = select3.Sum(x => x.Key.Id); // OK
var sum4 = select4.Sum(x => x.Key.Id); // (Nullable object must have a value)
```

### Include stack traces

stack traces for GroupBy and "Nullable object must have a value"
```
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_NoValue()
   at Microsoft.EntityFrameworkCore.Query.Internal.GroupBySingleQueryingEnumerable`2.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.<Main>$(String[] args) in \repos\ConsoleApp1\ConsoleApp1\Program.cs:line 9
```

stack traces for GroupBy and "Value cannot be null. (Parameter 'collection')"
```
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ApplyProjection(Expression shaperExpression, ResultCardinality resultCardinality, QuerySplittingBehavior querySplittingBehavior)
   at Microsoft.EntityFrameworkCore.Query.Internal.SelectExpressionProjectionApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPostprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerQueryTranslationPostprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.<Main>$(String[] args) in \repos\ConsoleApp1\ConsoleApp1\Program.cs:line 10
```

stack traces for Sum
```
at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_NoValue()
   at System.Nullable`1.get_Value()
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ClientProjectionRemappingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ApplyProjection(Expression shaperExpression, ResultCardinality resultCardinality, QuerySplittingBehavior querySplittingBehavior)
   at Microsoft.EntityFrameworkCore.Query.Internal.SelectExpressionProjectionApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPostprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerQueryTranslationPostprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Program.<Main>$(String[] args) in \repos\ConsoleApp1\ConsoleApp1\Program.cs:line 18
```

### Include provider and version information

EF Core version: 8.0.4
Database provider: (Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 8.0)
Operating system: Windows
IDE: (e.g. Visual Studio 2022 17.9.2)

**Comment by roji** [comment]
The first errors are likely to be bugs with final GroupBy combined with complex types, or similar; the Sum-related error is likely unrelated. Am putting on the backlog to investigate along with the other GroupBy-related issues, hopefully for 10.

In the meantime, note that a final GroupBy - that is, a GroupBy that isn't directly followed by a Select() with an aggregate function - isn't translated to a SQL GROUP BY (that's not possible), so the grouping is performed client-side in .NET. That means that any issues can be worked around by placing AsEnumerable() just before the final GroupBy. So at least those errors shouldn't be blocking.

**Comment by Myliak** [comment]
I've also dropped on this issue with Entity Framework and most likely, it's the problem in `NULL = NULL` behavior on database server side and it's difference in C# where it returns true, rather than UNKNOWN. I think the entity framework has a fallback implemented with this error when you try to do a grouping operation over nullable key, which entity framework correctly translates into sql syntax, but returns wrong data, because it ignores rows with null value in grouping key column. Unfortunately I couldn't find any documentation or other issues on this matter to back my claim.

But I found quickfix for this error by providing default value for nulls:
```
var group = context.Companies.GroupBy(x => x.CountryId ?? 0);
```
