### ISSUE TITLE
Old migration break in EF Core 8 that worked in EF Core 7 and previous

### ISSUE THREAD

**Issue by flindby** [dotnet/efcore#33734]
Old migration generated in EF Core 2.1.0 break in EF Core 8.0.5.

In the old migration (first in our project) there is a column defined as:

`MyEntityType = table.Column<int>(nullable: false, defaultValue: "")`

Which has been working until now when I upgraded to .NET8/EFCore8.
If I remove `defaultValue: ""` the migration works as expected.

Stacktrace:
```
[11:01:56]      Applying 20180809120006_Initial...
Object reference not set to an instance of an object.
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindCollectionMapping(RelationalTypeMappingInfo info, Type modelType, Type providerType, CoreTypeMapping elementMapping)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.<>c.<FindMappingWithConversion>b__8_0(ValueTuple`4 k, RelationalTypeMappingSource self)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMappingWithConversion(RelationalTypeMappingInfo mappingInfo, Type providerClrType, ValueConverter customConverter)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMappingWithConversion(RelationalTypeMappingInfo mappingInfo, IReadOnlyList`1 principals)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMapping(Type type, String storeTypeName, Boolean keyOrIndex, Nullable`1 unicode, Nullable`1 size, Nullable`1 rowVersion, Nullable`1 fixedLength, Nullable`1 precision, Nullable`1 scale)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.DefaultValue(Object defaultValue, String defaultValueSql, String columnType, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.ColumnDefinition(String schema, String table, String name, ColumnOperation operation, IModel model, MigrationCommandListBuilder builder)
```

EF Core version: 8.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: (e.g. .NET 8.0)
Operating system: Windows 10

**Comment by AndriySvyryd** [comment]
@ajcvickers Apparently, we used to generate default values that didn't match the column type and it produced valid SQL. 

Here's a test for this. Insert into `SqlServerMigrationsSqlGeneratorTest`:
```C#
    [ConditionalFact]
    public virtual void AddColumnOperation_mistyped_default_legacy()
    {
        Generate(
            new AddColumnOperation
            {
                Table = "People",
                Name = "Id",
                ClrType = typeof(int),
                ColumnType = "int",
                DefaultValue = "",
                IsNullable = false
            });

        AssertSql(
            """
ALTER TABLE [People] ADD [Id] int NOT NULL DEFAULT N'';
""");
    }
```

**Comment by ajcvickers** [comment]
@AndriySvyryd What do you mean by "generate?" Do you mean that we scaffold migrations where we generate a string default value for an int column? Or do we just use an invalid default value if it has been supplied by the application?

**Comment by ajcvickers** [comment]
Notes from the design meeting:
- We believe this only happens when the model contains a default value of a type that does not match the property type. This is an error in the model which should be fixed.
- We will not attempt to fix this automatically in old migrations, unless we get many more reports.
- We should fix the NullRefException and throw something better.

**Comment by kirylbokach** [comment]
I was having the same issue when trying to switch the discriminator column type from `varchar(50)` to `smallint` and forgetting to switch the property type from string to enum. Once switched the NRE goes away

Generates NRE:
```csharp
builder.ToTable("signals");

builder.UseTphMappingStrategy();

const string discriminatorColumnName = "SignalClassDiscriminator";

builder.HasDiscriminator<SignalClassDiscriminator>(discriminatorColumnName)
    .HasValue<ReceivedSignalDto>(SignalClassDiscriminator.Received)
    .HasValue<OriginatedSignalDto>(SignalClassDiscriminator.Originated);

builder.Property<string>(discriminatorColumnName)
    .HasColumnType(KnownColumnTypes.IntEnum);
```

Works:
```csharp
 builder.ToTable("signals");

 builder.UseTphMappingStrategy();

const string discriminatorColumnName = "SignalClassDiscriminator";

 builder.HasDiscriminator<SignalClassDiscriminator>(discriminatorColumnName
     .HasValue<ReceivedSignalDto>(SignalClassDiscriminator.Received)
     .HasValue<OriginatedSignalDto>(SignalClassDiscriminator.Originated);

 builder.Property<SignalClassDiscriminator>(discriminatorColumnName)
     .HasColumnType(KnownColumnTypes.IntEnum);
```

The diff is in the line before the last one (<string> -> <SignalClassDiscriminator>)
