### ISSUE TITLE
DateTime.MaxValue Exceeds Supported Timestamp Bounds 

### ISSUE THREAD

**Issue by RDoll-Repo** [dotnet/efcore#33798]
When updating an entity with a field of DateTime, if we attempt to give that field a value of `DateTime.MaxValue`, we get the following exception:
```
Unhandled exception. Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Npgsql.PostgresException (0x80004005): 22009: error in argument for $2: timestamp "294277-01-09T04:00:54Z" exceeds supported timestamp bounds
   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
2
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
2
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
  Exception data:
    Severity: ERROR
    SqlState: 22009
    MessageText: error in argument for $2: timestamp "294277-01-09T04:00:54Z" exceeds supported timestamp bounds
    File: datum.go
    Line: 2540
    Routine: NewTimestampExceedsBoundsError
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__112_0(DbContext _, ValueTuple`2 t)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Program.<Main>$(String[] args) in .../DateTimeSample/Program.cs:line 5
```
This does not occur on .NET version 6.0.16 or below. Here's a small sample I produced that results in the above:

Program.cs
```cs
using var db = new SampleContext();

// Create
db.Add(new Purchase { Id = Guid.NewGuid(), Expiry = DateTime.MaxValue });
db.SaveChanges();
```

Model.cs
```cs
using Microsoft.EntityFrameworkCore;

public class SampleContext : DbContext
{
    public DbSet<Purchase> Purchases { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseNpgsql("Host=localhost;Port=26258;Database=sample;Username=root;");
}

public class Purchase
{
    public Guid Id { get; set; }
    public DateTime Expiry { get; set; }
}
```

Steps to reproduce: 
1.) Create a migration and update the database
2.) Run the program, you should see the above exception

### Include provider and version information
EF Core version: 8.0.5
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL (connecting to CockroachDB v22.2.3)
Target framework: .NET 8.0
Operating system: MacOS 14.2.1
IDE: Visual Studio Code 1.89.1

EDIT: Specified CRDB version

**Comment by roji** [comment]
@RDoll-Repo I'm unable to reproduce the issue - please see the code below; it's always better to submit a fully runnable code sample rather than partial snippets.

Note that the actual value of DateTime.Max is `9999-12-31T23:59:59.9999999` - which works fine - and not `294277-01-09T04:00:54Z`; I have no idea where that's coming from in your application (maybe it's manually hard-coded into you migration or something).

<details>
<summary>Attempted repro</summary>

```c#
await using var db = new SampleContext();
await db.Database.EnsureDeletedAsync();
await db.Database.EnsureCreatedAsync();

db.Add(new Purchase { Id = Guid.NewGuid(), Expiry = DateTime.MaxValue });
db.SaveChanges();

public class SampleContext : DbContext
{
    public DbSet<Purchase> Purchases { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseNpgsql("Host=localhost;Username=test;Password=test")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class Purchase
{
    public Guid Id { get; set; }
    public DateTime Expiry { get; set; }
}
```
</details>

**Comment by RDoll-Repo** [comment]
@roji Is there a preferred way to submit a runnable sample? I've got a zip file here, but I can create a repo and link you to it if that is preferred. 

[DateTimeSample.zip](https://github.com/dotnet/efcore/files/15490299/DateTimeSample.zip)

**Comment by roji** [comment]
See my "Attempted repro" above; ideally, simply tweak that to make it fail in the way you're seeing. Also, ideally the problem would reproduce against normal PostgreSQL as well, as opposed to CockroachDB.

**Comment by RDoll-Repo** [comment]
When running your sample, after creating a migration and updating the database as such
`dotnet ef migrations add Initial`
`dotnet ef database update`

I run into the following:
<details>
<summary>Stack Trace</summary>

```
An exception of type 'Npgsql.PostgresException' occurred in System.Private.CoreLib.dll but was not handled in user code: '42601: at or near "with": syntax error

DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.'
   at Npgsql.Internal.NpgsqlConnector.<ReadMessageLong>d__233.MoveNext()
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.NpgsqlDataReader.<NextResult>d__52.MoveNext()
   at Npgsql.NpgsqlDataReader.<NextResult>d__52.MoveNext()
   at Npgsql.NpgsqlCommand.<ExecuteReader>d__119.MoveNext()
   at Npgsql.NpgsqlCommand.<ExecuteReader>d__119.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Npgsql.NpgsqlCommand.<ExecuteNonQuery>d__107.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteNonQueryAsync>d__14.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteNonQueryAsync>d__14.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteNonQueryAsync>d__14.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.<ExecuteNonQueryAsync>d__1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.<ExecuteNonQueryAsync>d__1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.<ExecuteNonQueryAsync>d__1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.<ExecuteNonQueryAsync>d__1.MoveNext()
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.<DeleteAsync>d__22.MoveNext()
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.<DeleteAsync>d__22.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.<EnsureDeletedAsync>d__16.MoveNext()
   at Program.<<Main>$>d__0.MoveNext() in /Users/rolanddoll/repo/misc/DateTimeSample/Program.cs:line 5
   at Program.<<Main>$>d__0.MoveNext() in /Users/rolanddoll/repo/misc/DateTimeSample/Program.cs:line 9
```

</details>

Commenting out lines 5 and 6 here in my tweaked version of your attempted repro (given below) gets me the following message, the one I opened the issue for:

<details>
<summary>Stack Trace</summary>

```
An exception of type 'Microsoft.EntityFrameworkCore.DbUpdateException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'An error occurred while saving the entity changes. See the inner exception for details.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 Npgsql.PostgresException : 22009: error in argument for $2: timestamp "294277-01-09T04:00:54Z" exceeds supported timestamp bounds
   at Npgsql.Internal.NpgsqlConnector.<ReadMessageLong>d__233.MoveNext()
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.NpgsqlDataReader.<NextResult>d__52.MoveNext()
   at Npgsql.NpgsqlDataReader.<NextResult>d__52.MoveNext()
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.<ExecuteReader>d__119.MoveNext()
   at Npgsql.NpgsqlCommand.<ExecuteReader>d__119.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
```

</details>

<details>
<summary>Runnable Sample</summary>

```cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

await using var db = new SampleContext();
// await db.Database.EnsureDeletedAsync();
// await db.Database.EnsureCreatedAsync();

db.Add(new Purchase { Id = Guid.NewGuid(), Expiry = DateTime.MaxValue });
db.SaveChanges();

public class SampleContext : DbContext
{
    public DbSet<Purchase> Purchases { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseNpgsql("Host=localhost;Port=26258;Database=sample;Username=root;")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class Purchase
{
    public Guid Id { get; set; }
    public DateTime Expiry { get; set; }
}
```

</details>

Interestingly enough, I also did as suggested and tried it out with Postgres, and I see neither error. So I'm not totally sure how to proceed from here.

**Comment by roji** [comment]
If this repros only on CockroachDB, I'd suggest reporting the issue with them... There's not much I can do without a PG repro...

**Comment by RDoll-Repo** [comment]
For documentation, we're following up on this issue with Cockroach in an issue found here: https://github.com/cockroachdb/cockroach/issues/125054
