### ISSUE TITLE
Unsafe accessors failing for backing fields in 9.0-preview5

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#33828]
>  Microsoft.EntityFrameworkCore.Scaffolding.CompiledModelInMemoryTest.ComplexTypes
System.MissingFieldException : Field not found: 'PrincipalBase.<Enum1>k__BackingField'.
   at TestNamespace.PrincipalBaseEntityType.UnsafeAccessor_Microsoft_EntityFrameworkCore_Scaffolding_PrincipalBase_Enum1(PrincipalBase this)
   at TestNamespace.PrincipalBaseEntityType.<>c.<Create>b__0_17(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.GetCurrentValue[TProperty](IPropertyBase propertyBase) in /_/src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs:line 977
   at TestNamespace.PrincipalDerivedEntityType.<>c__DisplayClass1_0.<CreateAnnotations>b__0(InternalEntityEntry source)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntrySubscriber.SnapshotAndSubscribe(InternalEntityEntry entry) in /_/src/EFCore/ChangeTracking/Internal/InternalEntityEntrySubscriber.cs:line 31
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry) in /_/src/EFCore/ChangeTracking/Internal/StateManager.cs:line 583
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties) in /_/src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs:line 398
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node) in /_/src/EFCore/ChangeTracking/Internal/EntityGraphAttacher.cs:line 125
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode) in /_/src/EFCore/ChangeTracking/Internal/EntityEntryGraphIterator.cs:line 26
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey) in /_/src/EFCore/ChangeTracking/Internal/EntityGraphAttacher.cs:line 45
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey) in /_/src/EFCore/ChangeTracking/Internal/EntityGraphAttacher.cs:line 60
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Add(TEntity entity) in /_/src/EFCore/Internal/InternalDbSet.cs:line 193
   at Microsoft.EntityFrameworkCore.Scaffolding.CompiledModelTestBase.<>c.<ComplexTypes>b__4_0(DbContext c) in /_/test/EFCore.Specification.Tests/Scaffolding/CompiledModelTestBase.cs:line 589
   at Microsoft.EntityFrameworkCore.Scaffolding.CompiledModelTestBase.Test[TContext](Action`1 onModelCreating, Action`1 assertModel, Func`2 useContext, Action`1 onConfiguring, CompiledModelCodeGenerationOptions options, Func`2 addServices, Func`2 addDesignTimeServices, IEnumerable`1 additionalSourceFiles, Action`1 assertAssembly, String expectedExceptionMessage, String testName) in /_/test/EFCore.Specification.Tests/Scaffolding/CompiledModelTestBase.cs:line 1453
--- End of stack trace from previous location ---

**Comment by ericstj** [comment]
Same issue is being hit in https://github.com/dotnet/efcore/pull/33821

**Comment by AndriySvyryd** [comment]
Seems to be external - filed https://github.com/dotnet/runtime/issues/102792
