### ISSUE TITLE
Error: Value cannot be null parameter name key 

### ISSUE THREAD

**Issue by douglasg14b** [dotnet/efcore#33831]
## File a bug
I've read a few issues on this and have been unable to gleam much information from them

### Include your code

I'm still trying to figure out what might be triggering this, I do not have a trivial repro at this time. The affecting code is a lot of business logic that, in the end, adds a new related entity, and deleted & adds an owned entity.

```C#
// TODO figure out what the problem is
```

### Include stack traces

Include the full exception message and stack trace for any exception you encounter.

Use triple-tick fences for stack traces. For example:

```
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.<GenerateColumnModifications>g__HandleJson|41_4(List`1 columnModifications, <>c__DisplayClass41_0&)
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.GenerateColumnModifications()
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.<>c.<get_ColumnModifications>b__33_0(ModificationCommand command)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.get_ColumnModifications()
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.CreateCommandBatches(IEnumerable`1 commandSet, Boolean moreCommandSets, Boolean assertColumnModification, ParameterNameGenerator parameterNameGenerator)+MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.BatchCommands(IList`1 entries, IUpdateAdapter updateAdapter)+MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Buzzscreens.Infrastructure.DbContextHooks.HookableDbContext`3.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken) in C:\Users\Douglas\Documents\01 Programming\02 Contracts\buzzscreens-app\apps\backend\Buzzscreens.Infrastructure\DbContextHooks\HookableDbContext.cs:line 85
```

### Attempts:
1. Modifying instead of replacing the child owned entity: No Change ❌
2. Change child owned entity from `record` to class`: No Change ❌
3. Change Owned Entity to a `record` and update it with `AdlogicLink with { State = newState }` to get a whole new instance. ✅

### Include verbose output

No problems here.

### Include provider and version information

EF Core version: 8.0.4
Database provider: Postgres
Target framework: .NET 8
Operating system: Windows 10
IDE: Rider 2024.1.2

**Comment by douglasg14b** [comment]
Alright, I managed to make the problem go away by:

1. Not modifying the child owned entity and replacing the entire owned entity instead

This is kind of not-idea since the point of the child owned entity is that it encapsulates important logic, but it works.

Is this intentional behavior, or a bug?

**Comment by maumar** [comment]
It's definitely a bug - we should never throw exception like that
possibly related to https://github.com/dotnet/efcore/issues/33452

**Comment by douglasg14b** [comment]
Well that's awkward, I remember writing in repro code into this, but upon revisiting this issue I see now such thing in the description. 😬 

I must have never clicked save, cripes.

**Comment by dombaigabor** [comment]
I had the same problem if i called .ToJson() in a nested OwnOne chain. 

```
var entityConfig= modelBuilder.Entity<EntityType>();
entityConfig.OwnsOne(x => x.Settings, nav =>
{
 nav.ToJson();
 nav.OwnsOne(x => x.InnerModel, innerNav => innerNav.ToJson() <----here);
});
```
After I deleted that part, there is no error, and my code is working properly.

**Comment by salihozkara** [comment]
![image](https://github.com/user-attachments/assets/2828d34e-34f3-4c2b-b765-172d7cf824b5)

Hi @maumar,
If we add code like the one I shared below, won't it provide a solution? I could add the database properly when I bypassed this line in debug mode.

```cs
if (jsonColumn == null)
{
    continue;
}
```

**Comment by StenPetrov** [comment]
**Work-around**

Instead of using EFCore's json mapping, do it manually - much cleaner and less bug-prone:

```c#

        [NotMapped] // EFCore won't use this property
        public IMyPolymorphicConfig? PolyConfig { get; set; }

        // add this property manually in your DbContext, see below
        [JsonIgnore]
        internal string SerializedPolyConfig  {
            get
            {
                if (PolyConfig != null)
                {
                    return JsonSerializer.Serialize(PolyConfig );
                }
                else
                {
                    return string.Empty;
                }
            }
            set
            {
                if (!string.IsNullOrEmpty(value))
                {
                    try
                    {
                        PolyConfig = JsonSerializer.Deserialize<IMyPolymorphicConfig>(value);
                    }
                    catch (Exception x)
                    {
                        Console.WriteLine("Failed to deserialize PolyConfig : " + x);
                        PolyConfig = null;
                    }
                }
                else
                {
                    ProviderConfig = null;
                }
            }
        }
```

and in the DbContext add the internal property manually:
```c#
 protected override void OnModelCreating(ModelBuilder modelBuilder)
 {
     modelBuilder.Entity<MyType>(epc =>
     {
         epc.HasKey(e => e.Id);
         epc.Property(e => e.SerializedPolyConfig ).IsRequired(); // map the internal property for EFCore to use
     });
  
     base.OnModelCreating(modelBuilder);
 }
```

**Comment by arc-menace** [comment]
Sorry to resurrect this, I may just be doing something totally wrong here. I am getting this same error in version 9.0.9.

My OnModelCreating for this table looks like this:

<img width="2046" height="84" alt="Image" src="https://github.com/user-attachments/assets/0dc0d61c-2185-4db9-954d-b3748ad07989" />

**Comment by roji** [comment]
@arc-menace as the milestone shows, this was fixed for 10.0, so it makes sense you're getting this error in version 9.0.9. You can try the recently-released 10.0.0-rc.1 version.

In any case, please always post a minimal repro, and not a two line snippet as an image: I can't even read what you posted, and if I could, it would very likely not be enough to reproduce the problem.

**Comment by GoaLitiuM** [comment]
Any changes for getting this backported to 8.0?

**Comment by roji** [comment]
If I understand correctly, the fix here is to throw a better exception - we would most likely not backport that. We only backport critical fixes which have no workarounds, etc.
