### ISSUE TITLE
`DivideByZeroException` in `ef_divide` and `ef_mod`

### ISSUE THREAD

**Issue by ranma42** [dotnet/efcore#33877]
In general division (and modulus) by 0 result in a `NULL` in SQL. This is usually respected in EFCore (with the usual caveat that when using non-nullable types, the result might not be representable), but when dealing with `decimal`s on the SQLite provider this might instead result in a `DivideByZeroException` (caught and wrapped into a `SqliteException` by the provider).

An example program that showcases the bug is:

```C#
using System;
using System.Data;
using System.Linq;
using Microsoft.EntityFrameworkCore;

using var db = new BloggingContext();

db.Database.EnsureDeleted();
db.Database.EnsureCreated();

db.Blogs
    .Select(x => 1 / x.NullableInt)
    .ToList();

db.Blogs
    .Select(x => 1 / x.NullableDecimal)
    .ToList();

public class BloggingContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder options)
        => options
            .LogTo(Console.WriteLine, Microsoft.Extensions.Logging.LogLevel.Information)
            .UseSqlite($"Data Source=test.db");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
		for (var i = 1; i < 5; i++) {
        	modelBuilder.Entity<Blog>().HasData(new Blog { BlogId = i, NullableInt = i - 2, NullableDecimal = i - 2 });
		}
    }
}

public class Blog
{
    public int BlogId { get; set; }
	public int? NullableInt { get; set; }
	public decimal? NullableDecimal { get; set; }
}
```

### Exception
The program terminates with the following exception:

```
fail: 06/02/2024 20:31:40.395 CoreEventId.QueryIterationFailed[10100] (Microsoft.EntityFrameworkCore.Query) 
      An exception occurred while iterating over the results of a query for context type 'BloggingContext'.
      Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'Attempted to divide by zero.'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteDataRecord.Read()
         at Microsoft.Data.Sqlite.SqliteDataReader.Read()
         at Microsoft.EntityFrameworkCore.Storage.RelationalDataReader.Read()
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
Unhandled exception. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'Attempted to divide by zero.'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataRecord.Read()
   at Microsoft.Data.Sqlite.SqliteDataReader.Read()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDataReader.Read()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.<Main>$(String[] args)
```

while running the query
```sql
      SELECT ef_divide('1.0', "b"."NullableDecimal")
      FROM "Blogs" AS "b"
```

### Include provider and version information

EF Core version: 8.0.6
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 8.0
Operating system: Linux (/WSL)
IDE: Visual Studio Code 1.89.1

**Comment by ajcvickers** [comment]
Note from team discussion: we agree. A PR would be great! :-D
