### ISSUE TITLE
Unexpected Client Evaluation when joining List and DbSet

### ISSUE THREAD

**Issue by Pscioed** [dotnet/efcore#33953]
### Description

When attempting to join a List with a DbSet, client evaluation is automatically triggered when the List comes before the DbSet in the linq query. When the order is reversed, an exception is thrown indicating the expression cannot be translated, which is the expected behavior:
https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/breaking-changes#linq-queries-are-no-longer-evaluated-on-the-client

### Full Code Sample
```C#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;

namespace EFProject
{
	public class EFProject
	{
		static void Main(string[] args)
		{
			using var context = new MyDbContext();
			var parentIds = new List<int> { 1, 2 };
			var childIds = new List<int> { 1, 2, 3, 5 };

			try
			{
				//Properly written query
				Console.WriteLine();
				var firstResult = (
					from p in context.ParentTable
					join c in context.ChildTable on p.Id equals c.ParentId
					where parentIds.Contains(p.Id) && childIds.Contains(c.Id)
					select new
					{
						ParentId = p.Id,
						ParentName = p.Name,
						ChildId = c.Id,
						ChildName = c.Name,
					}
				).ToList();
			}
			catch (Exception ex)
			{
				Console.WriteLine(ex.ToString());
			}

			try
			{
				//Query joining List -> DbSet
				Console.WriteLine();
				var secondResult = (
					from p in context.ParentTable.ToList()
					join c in context.ChildTable on p.Id equals c.ParentId
					where parentIds.Contains(p.Id) && childIds.Contains(c.Id)
					select new
					{
						ParentId = p.Id,
						ParentName = p.Name,
						ChildId = c.Id,
						ChildName = c.Name,
					}
				).ToList();
			}
			catch (Exception ex)
			{
				Console.WriteLine(ex.ToString());
			}

			try
			{
				//Query joining DbSet -> List
				Console.WriteLine();
				var thirdResult = (
					from p in context.ParentTable
					join c in context.ChildTable.ToList() on p.Id equals c.ParentId
					where parentIds.Contains(p.Id) && childIds.Contains(c.Id)
					select new
					{
						ParentId = p.Id,
						ParentName = p.Name,
						ChildId = c.Id,
						ChildName = c.Name,
					}
				).ToList();
			}
			catch (Exception ex)
			{
				Console.WriteLine(ex.ToString());
			}
		}
	}
	public class MyDbContext : DbContext
	{
		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
			optionsBuilder.UseSqlServer("Server=.\\ENTERPRISE2019;Database=efproject;Integrated Security=True;MultipleActiveResultSets=true;App=efproject;TrustServerCertificate=True");
			optionsBuilder.LogTo(Console.WriteLine, new[] { RelationalEventId.CommandExecuting });
			optionsBuilder.EnableSensitiveDataLogging();
		}
		public DbSet<ParentTable> ParentTable { get; set; }
		public DbSet<ChildTable> ChildTable { get; set; }
	}
	public class ParentTable
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public string Metadata { get; set; }
	}
	public class ChildTable
	{
		public int Id { get; set; }
		public int ParentId { get; set; }
		public string Name { get; set; }
		public string Metadata { get; set; }
	}
}
```

### Output
```
dbug: 6/10/2024 11:52:55.181 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[@__parentIds_0='[1,2]' (Size = 4000), @__childIds_1='[1,2,3,5]' (Size = 4000)], CommandType='Text', CommandTimeout='30']
      SELECT [p].[Id] AS [ParentId], [p].[Name] AS [ParentName], [c].[Id] AS [ChildId], [c].[Name] AS [ChildName]
      FROM [ParentTable] AS [p]
      INNER JOIN [ChildTable] AS [c] ON [p].[Id] = [c].[ParentId]
      WHERE [p].[Id] IN (
          SELECT [p0].[value]
          FROM OPENJSON(@__parentIds_0) WITH ([value] int '$') AS [p0]
      ) AND [c].[Id] IN (
          SELECT [c0].[value]
          FROM OPENJSON(@__childIds_1) WITH ([value] int '$') AS [c0]
      )

dbug: 6/10/2024 11:52:55.242 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [p].[Id], [p].[Metadata], [p].[Name]
      FROM [ParentTable] AS [p]
dbug: 6/10/2024 11:52:55.266 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [c].[Id], [c].[Metadata], [c].[Name], [c].[ParentId]
      FROM [ChildTable] AS [c]

dbug: 6/10/2024 11:52:55.275 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [c].[Id], [c].[Metadata], [c].[Name], [c].[ParentId]
      FROM [ChildTable] AS [c]
System.InvalidOperationException: The LINQ expression 'DbSet<ParentTable>()
    .Join(
        inner: __p_0,
        outerKeySelector: p => p.Id,
        innerKeySelector: c => c.ParentId,
        resultSelector: (p, c) => new {
            p = p,
            c = c
         })' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EFProject.EFProject.Main(String[] args) in D:\scripts\EFProject\EFProject\EFProject\Program.cs:line 63
```

### Provider and version information

EF Core version: 8.0.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows Server 2016
IDE: Visual Studio 2022 17.9

**Comment by roji** [comment]
To be sure I understand, are you asking why the 2nd query above:

```c#
var secondResult = (
	from p in context.ParentTable.ToList()
	join c in context.ChildTable on p.Id equals c.ParentId
	where parentIds.Contains(p.Id) && childIds.Contains(c.Id)
	select new
	{
		ParentId = p.Id,
		ParentName = p.Name,
		ChildId = c.Id,
		ChildName = c.Name,
	}
).ToList();
```

... performs "client evaluation" rather than throwing?

If so, then that is how .NET works, and there is nothing EF can do here. The moment you write `context.ParentTable.ToList()`, you are telling EF "please download the entire ParentTable table from the database and materialize it as a list"; that is a valid thing to do in some scenarios. At that point, you're telling .NET - not EF - to perform a client-side join on the results of the EF query over ChildTable. The root of the query usually determines how to gets evaluated.

**Comment by roji** [comment]
@Pscioed I'd suggest refraining from putting ToList() like that inside your EF queries - that's the source of the client evaluation here.
