### ISSUE TITLE
EF 7 is generating SQL with incorrect syntax near the keyword OPTION 

### ISSUE THREAD

**Issue by shridharkurhade** [dotnet/efcore#33962]
While adding more than one entities via code to any entity/table and calling the dbcontext.SaveChanges(), the EF is generating an incorrect syntax of the SQL with the merge statement for inserting values.

### Incorrect SQL Syntax generated by EF 7

```SQL
exec sp_executesql N'........ MERGE...... USING... WHEN NOT MATCHED THEN INSERT.... OUTPUT......;

SELECT <primary key columns> FROM table t
INNER JOIN @inserted0 i ON (join criteria)
ORDER BY [i].[_Position];  -- the semicolon is inserted at this wrong place

OPTION (RECOMPILE) -- the semicolon should be here
',
N'@p0....', @p0='value'
```

### Include stack traces

Include the full exception message and stack trace for any exception you encounter.

Use triple-tick fences for stack traces. For example:

```
Microsoft.EntityFrameworkCore.DbUpdateException
  HResult=0x80131500
  Message=An error occurred while saving the entity changes. See the inner exception for details.
  Source=Microsoft.EntityFrameworkCore.Relational
  StackTrace:
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
SqlException: Incorrect syntax near the keyword 'OPTION'.

```

### Include provider and version information

EF Core version: 7.0.20
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET 6.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.10.1

**Comment by ajcvickers** [comment]
@shridharkurhade EF Core 7 is [out-of-support](https://learn.microsoft.com/en-us/ef/core/what-is-new/). If you are still seeing this with EF8, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by roji** [comment]
EF doesn't generate the `OPTION (RECOMPILE)` bit in your SQL - that is very likely being added somewhere in your own app (e.g. via a command interceptor). If you rewrite EF's SQL, it's generally your responsibility to make sure it's correct.

**Comment by shridharkurhade** [comment]
> EF doesn't generate the `OPTION (RECOMPILE)` bit in your SQL - that is very likely being added somewhere in your own app (e.g. via a command interceptor). If you rewrite EF's SQL, it's generally your responsibility to make sure it's correct.

@roji Thank you for your answere/analysis. This resolved my issue. It was getting added via command interceptor.
