### ISSUE TITLE
Getting Exception two type of exception at System.Data.SQLite.SQLiteConnection.Open()

### ISSUE THREAD

**Issue by hemant020** [dotnet/efcore#33971]
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at System.Data.SQLite.SQLiteConnection.SetCachedSetting(String name, Object value)
   at System.Data.SQLite.SQLiteConnection.ShouldUseLegacyConnectionStringParser(SQLiteConnection connection)
   at System.Data.SQLite.SQLiteConnection.ParseConnectionString(SQLiteConnection connection, String connectionString, Boolean allowNameOnly)
   at System.Data.SQLite.SQLiteConnection.ParseConnectionString(SQLiteConnection connection, String connectionString, Boolean parseViaFramework, Boolean allowNameOnly)
   at System.Data.SQLite.SQLiteConnection.Open()

System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at System.Data.SQLite.SQLiteConnection.SetCachedSetting(String name, Object value)
   at System.Data.SQLite.SQLiteConnection.ShouldUseLegacyConnectionStringParser(SQLiteConnection connection)
   at System.Data.SQLite.SQLiteConnection.ParseConnectionString(SQLiteConnection connection, String connectionString, Boolean allowNameOnly)
   at System.Data.SQLite.SQLiteConnection.ParseConnectionString(SQLiteConnection connection, String connectionString, Boolean parseViaFramework, Boolean allowNameOnly)
   at System.Data.SQLite.SQLiteConnection.Open()

**Comment by ErikEJ** [comment]
System.Data.SQLite support is here: https://system.data.sqlite.org/index.html/doc/trunk/www/support.wiki
