### ISSUE TITLE
Add-Migration failing with new Microsoft.CodeAnalysis.Workspaces v4.10.0

### ISSUE THREAD

**Issue by pocki** [dotnet/efcore#33970]
## Bug Microsoft.CodeAnalysis.* version dependencies
ASP.NET Core Web API with EF Core 8.0
I need to reference Microsoft.CodeAnalysis.* directly with a newer version (instead of v4.5.0) because of other dependencies like Powershell.SDK - see #32070

This was working fine until v4.9.2 of Microsoft.CodeAnalysis.* packages. Except the warning about version mismatch.
After update to v4.10.0 the Add-Migration crashes.

Please make it working also with newer versions of Microsoft.CodeAnalysis. and don't stick to an (very) old version.

Directory.Packages.props:
```xml 
    <PackageVersion Include="Microsoft.CodeAnalysis.Common" Version="4.10.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.10.0" />
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="5.2.1" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.6" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.6" />
```

### Stack traces
```
PM> Add-Migration -Context MyContext -OutputDir Models\DbMigrations -Name "Add my field"
Build started...
Build succeeded.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'get_IsParamsArray' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationParameterSymbol' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Composition.Hosting.ContainerConfiguration.<>c.<WithAssemblies>b__16_0(Assembly a)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.Create(IEnumerable`1 assemblies)
   at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.get_DefaultHost()
   at Microsoft.CodeAnalysis.AdhocWorkspace..ctor()
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper..ctor(ITypeMappingSource typeMappingSource)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
System.TypeLoadException: Method 'get_IsParamsArray' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationParameterSymbol' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Unable to load one or more of the requested types.
Method 'get_IsParamsArray' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationParameterSymbol' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
```

### Provider and version information

EF Core version: 8.0.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows 11 23H2 (Build 22631.3737)
IDE: Visual Studio 2022 17.10 and Visual Studio 2022 17.11 Preview 2.0

**Comment by flipZomb** [comment]
Have a similar issue. Going back to "4.9.2" fixed it for now.

**Comment by ajcvickers** [comment]
Duplicate of #32926

**Comment by pocki** [comment]
Its not a duplicate, as it is a current problem and not in next major release in half a year

**Comment by roji** [comment]
@pocki the problem has already been fixed for 9.0 - the remaining question is about whether to also backport a fix for 8.0. That discussion is happening as part of #32926.

**Comment by pocki** [comment]
@roj At the mentioned PR there is only an update to v4.8 - this is still not the latest version. And there are breaking changes from 4.9.2 to 4.10

**Comment by peter-nguyen-contemi** [comment]
@roji  Could you please consider the comment from @pocki . It seems that he mentioned a wrong person in his comment. Right now we cannot add any new EF Core migrations with Microsoft.CodeAnalysis.* packages version 4.10.0 because of this issue. 
We had to downgrade them to version 4.9.2 for the EF Core tool to work properly.

**Comment by iscodand** [comment]
back to previous version solved the problem on my project

**Comment by ajcvickers** [comment]
@roji To update.

**Comment by roji** [comment]
I've consulted about this internally, and we're not going to be changing the Microsoft.CodeAnalysis version in EF 9.0. IIUC upgrading to 4.10.0 would preclude usage of VS 17.8 and 17.9 for no good reason, and the recommendation in general is to not just upgrade unless our analyzers/source generators actually need a feature from the newer versions.

Note that EF 10 will very likely target the net10.0 TFM, at which point older VSs probably won't be supported anyway; there's a good chance we'll upgrade our Microsoft.CodeAnalysis as well. Until then, the workaround above of manually using 4.9.2 (or whatever works) seems very reasonable.

**Comment by pocki** [comment]
@roji Thanks for the update.
That means that now (.NET8) and .NET9 app with EF Core (Code first) can't use actual Microsoft.CodeAnalysis or any dependency that uses an actual version of it.

My case as example: I can't use .NET9 and EF Core together with Microsoft.Powershell.SDK 7.5 (Powershell 7.5 is based on .NET9)
This is a weird situation and should last for at least ~ 1,5 years. (as since june 2024 not the latest version is possible to use)

**Comment by AndrewZenith** [comment]
Same issue.  Carter 9.0 requires 4.11, so I ran into this as well.

Had to downgrade carter to 8.21 to get EF migrations created.

**Comment by hades200082** [comment]
Another vote here - I'm also using Carter this dependency issue is causing me to not be able to use EF Core in my projects.

I must say, I don't expect this sort of dependency issue to be present in .NET. It's starting to feel like JavaScript/Node.

**Comment by roji** [comment]
Everyone, it's indeed unfortunate that this issue exists - read above for the explanation/reasons. I can say almost with certainty that we won't be patching EF 9.0 to change the version, but EF 10.0 should be fine (I've opened #35187 to make sure we do the right thing there).

**Comment by hades200082** [comment]
Why can't the dependency be set so that it will at least accept/work with the newer version if it's installed while retaining backwards compatibility? i.e. set the dependency to "at least 4.9.2"

**Comment by nhwilly** [comment]
Conflict with TimeWarpState, too.  Currently blocking the entire project.  I can't figure out how to configure around it.  Nothing works.

**Comment by roji** [comment]
Everyone, please note that as far as we know, using version 4.9.2 works around the problem - please read the issue from the beginning. Although the situation isn't great, we're not currently aware of a case that cannot be worked around with EF 9 - if there is one, we need to see a minimal repro.

**Comment by nhwilly** [comment]
> Everyone, please note that as far as we know, using version 4.9.2 works around the problem - please read the issue from the beginning. Although the situation isn't great, we're not currently aware of a case that cannot be worked around with EF 9 - if there is one, we need to see a minimal repro.

[TimeWarpState ](https://github.com/TimeWarpEngineering/timewarp-state) currently _requires_ 4.11.0.  

TWS is used in a library that is nested deep in the project hierarchy.

The package author is reviewing a workaround on his end.  In the meantime, I created an API project with no endpoints that references all the schemas in all the modules.  It does not reference TWS because it doesn't need all the nested projects to do zero work.

I just now finished migrating all my databases, etc. using this new project.  This workaround will be fine for me until EF 10.

Thanks for responding - huge fan of EF Core.

**Comment by roji** [comment]
Good to hear that you've found a workaround. Everything should be fine for EF 10 in any case.

**Comment by Maxteabag** [comment]
After upgrading from .net6 to .net 9 I had to use 4.9.2 no less no more, when doing dotnet-ef migrations add ... 
This is bad!

**Comment by rogmauri** [comment]
Version 4.12.0 and the problem still persists, forcing us to revert to 4.9.2 for 'dotnet ef migrations'.

Any expectations for a fix?

**Comment by roji** [comment]
@rogmauri please read all of the above.

**Comment by hades200082** [comment]
> Everyone, it's indeed unfortunate that this issue exists - read above for the explanation/reasons. I can say almost with certainty that we won't be patching EF 9.0 to change the version, but EF 10.0 should be fine (I've opened [#35187](https://github.com/dotnet/efcore/issues/35187) to make sure we do the right thing there).

Looks like #35187 has been closed as well with yet another issue opened at #34637 to supposedly address it in 10.0.0

**Comment by eqtr-ab** [comment]
This issue has constituted a major time-sink for me today. I cannot readily downgrade the CodeAnalysis package because another in the same project relies on 4.10.0. Separating the context into a separate project with its own set of dependencies may technically be a "workaround", but it's not a very expedient one that presents its own problems.

**Comment by roji** [comment]
Everyone, #35753 has just been merged, bumping Microsoft.CodeAnalysis.Workspaces to the recently released 4.13.0. Going forward, we have also decided to always targeted the latest .NET TFM (so EF 10 will target net10.0, EF 11 will target net11.0), allowing us to also keep the Microsoft.CodeAnalysis up to date and on the latest version (latest compiler/VS would be required in any case).

Re the current situation in 9.0, I don't have much to add beyond what's already written above. Changing the required Microsoft.CodeAnalysis version would break a lot of people.

**Comment by eqtr-ab** [comment]
The status quo also breaks a lot of people, such as myself and previous commenters. Umbraco, a popular CMS package, has a dependency on v4.10.0 of CodeAnalysis specifically - this appears to present a situation where any Umbraco solution which also makes use of this version of EF Core cannot add any migrations. I'm sure there'll be other packages out there which are also dependent on this version.

**Comment by roji** [comment]
> The status quo also breaks a lot of people, such as myself and previous commenters.

There was no change 

It's very different to say that there's an incompatibility using EF with some other, unrelated package (Umbraco), and asking for a breaking change to be done in an EF 9.0; the latter would cause EF users upgrading to a new **patch** version (regardless of any other packages). There is an extremely high bar for us for introducing a breaking change in a patch version, and this doesn't seem anywhere close to it.

If you prefer, you can stay with EF 8.0 for now, until 10 is released in a few months. Otherwise, you can also file a request with Umbraco to support earlier versions of Microsoft.CodeAnalysis.

**Comment by eqtr-ab** [comment]
EF8 is the version I am using, and the version both myself and OP encountered this issue in. I am not asking for any changes to be made to 9, 8 is the version exhibiting this issue. Can I assume your answer is the same in this circumstance, and this issue will not be resolved for this version either?

**Comment by roji** [comment]
@eqtr-ab yes, that same logic holds - even more so - for EF 8.0, which is a long-term release. We'd be breaking existing EF 8.0 users by releasing an 8.0 patch version that changes the Microsoft.CodeAnalysis version.

**Comment by LennardF1989** [comment]
If it's worth anything to anyone, I fixed my ,NET 8 with the following:
```
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="4.13.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.13.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.13.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.13.0" />
```

Specifically my case, adding the first two packages was key - in my case, transitive dependencies were mixing 4.5.0 and 4.10.0, which caused the `dotnet ef migrations add` to fail.

**Comment by AndrewZenith** [comment]
Just upgraded to 
<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.13.0" />

No more migration building issues.

**Comment by DennisBergemann** [comment]
Hi, we have dotnet core 9 project with WPF and Entity Frame work. Sincerely we on the same issue above.

one of the messages
-----------------------
`Method 'get_IsExtension' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationArrayTypeSymbol' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=4.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.`

i updated for my project to 4.14.0 as a test with no luck.

Any suggestions ?

**Comment by DennisBergemann** [comment]
Sorry the fix is like from @LennardF1989 

updates this packages to the newest

```
<PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="4.14.0" />
<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.14.0" />
<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.14.0" />
<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
```

**Comment by rogmauri** [comment]
Issue not yet resolved in version:

`<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.14.0" />`

**Comment by DennisBergemann** [comment]
@rogmauri  hi 😬 please have a look to all related packages. Open package manager and search for mentioned packages above and related. I know it’s really anoying , but the project installs this  packages with older versions where some functions not implemented.

Believe me you can solve this.

**Comment by rogmauri** [comment]
The only possible workaround, so far, was to revert 'Microsoft.CodeAnalysis.Common' to version 4.9.2

**Comment by hanoitown** [comment]
I upgrade dotnet 8->9 and I solved this issue by upgrade Microsoft.VisualStudio.Web.CodeGeneration.Design to v9

**Comment by rogmauri** [comment]
We already use .NET 9.

**Comment by Avionworx** [comment]
Tried version 5.0.0 with .NET10 EF project. No luck. Same issue as above

why Microsoft.EntityFrameworkCore.Design 10.0.0 still references 4.14.0 and not 5.0.0?

**Comment by hades200082** [comment]
@Avionworx Since this is closed, probably worth opening a new one and referencing this one.

I've not been using .NET so much let alone EFCore. More NextJS/Drizzle based these days.
