### ISSUE TITLE
EF Core 8 Cannot Join to List or Use 'Contains' in Where Clause

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#34018]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/EF-Core-8-Cannot-Join-to-List-or-Use-Co/10632245)._

---
The following code runs in all versions of EF Core prior to Version 8

```C#
                List<int> ECScanIDs = ScanData.Select(x => x.ScanID).Distinct().ToList();

                List<CabLabel> SchedCabs = await (from lab in _ctx.Tbl_Labels
                                            where lab.Category.ToLower() == "cabinet"
                                            && ECScanIDs.Contains(lab.ScanID)
                                            select lab).AsNoTracking().ToListAsync();
```
Starting in EF Core 8 and the latest 9 Preview, the above code is translated to 

```sql
SELECT [t].[ScanID], [t].[Assembled], [t].[BatchNumber], [t].[Category], [t].[Clamped], [t].[CurrentScanLocation], [t].[DateAssembly], [t].[Item], [t].[OrdNo]
FROM [Tbl_Labels] AS [t]
WHERE LOWER([t].[Category]) = N'cabinet' AND [t].[ScanID] IN (
    SELECT [e].[value]
    FROM OPENJSON(@__ECScanIDs_0) WITH ([value] int '$') AS [e]
)
```

And throws the following exception

```
Microsoft.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near '$'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:7524c7a5-c8ae-44b9-9893-7fadeaa3b45f
Error Number:102,State:1,Class:15
```

Attempting to JOIN causes the same issue

```C#
                List<int> ECScanIDs = ScanData.Select(x => x.ScanID).Distinct().ToList();

                //List<CabLabel> SchedCabs = await (from lab in _ctx.Tbl_Labels
                //                            where lab.Category.ToLower() == "cabinet"
                //                            && ECScanIDs.Contains(lab.ScanID)
                //                            select lab).AsNoTracking().ToListAsync();

                List<CabLabel> SchedCabs = await (from lab in _ctx.Tbl_Labels
                                                  join e in ECScanIDs on lab.ScanID equals e
                                                  where lab.Category.ToLower() == "cabinet"
                                                  select lab).AsNoTracking().ToListAsync();
```
Translation

```sql
SELECT [t].[ScanID], [t].[Assembled], [t].[BatchNumber], [t].[Category], [t].[Clamped], [t].[CurrentScanLocation], [t].[DateAssembly], [t].[Item], [t].[OrdNo]
FROM [Tbl_Labels] AS [t]
INNER JOIN OPENJSON(@__p_0) WITH ([value] int '$') AS [p] ON [t].[ScanID] = [p].[value]
WHERE LOWER([t].[Category]) = N'cabinet'
```

```
Exception
Microsoft.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near '$'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:d3fa6000-d0f8-4617-9e3b-fe25ff40b7ea
Error Number:102,State:1,Class:15
```

This works in EF Core 6, so I am not sure why it would be an issue in 8.  I tried the latest 9 preview with the same results.

Suggestions?  Time frame for Fix?

---
#### Feedback Bot on 4/7/2024, 03:40 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
See [Contains in LINQ queries may stop working on older SQL Server versions](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/breaking-changes#sqlserver-contains-compatibility)
