### ISSUE TITLE
Additional annotations are not added to design mode with UseModel

### ISSUE THREAD

**Issue by Sielnix** [dotnet/efcore#34032]
Custom annotations added by `IRelationalAnnotationProvider` are not added to design model if we use `UseModel` on `DbContextOptionsBuilder` in specific scenario. This is hard to reproduce test case, i found it using `DataBindingTestBase`. I'm not sure if the bug itself is in test implementation (not a big deal) or in the EFCore itself (pretty serious problem for [EFCore.Snowflake](https://github.com/Sielnix/EFCore.Snowflake)). Easiest steps to reproduce is to use existing Sql server functional tests.

In order to reproduce test change `DataBindingSqlServerTest` implementation to following one - it adds additional annotation for every column in design time and tries to use it in database model creation.

```C#

public class DataBindingSqlServerTest : DataBindingTestBase<AdvFixture>
{
    public DataBindingSqlServerTest(AdvFixture fixture)
        : base(fixture)
    {
    }

    public class AdvFixture : F1SqlServerFixture
    {
        protected override IServiceCollection AddServices(IServiceCollection serviceCollection)
        {
            base.AddServices(serviceCollection);

            // fastest way to replace services
            serviceCollection.Remove(serviceCollection.Single(s => s.ServiceType == typeof(IRelationalAnnotationProvider)));
            serviceCollection.Remove(serviceCollection.Single(s => s.ServiceType == typeof(IMigrationsSqlGenerator)));

            serviceCollection.AddSingleton<IRelationalAnnotationProvider, AdditionalAnnotationProvider>();
            serviceCollection.AddScoped<IMigrationsSqlGenerator, CustomMigrationsSqlGenerator>();

            return serviceCollection;
        }

        public class AdditionalAnnotationProvider(RelationalAnnotationProviderDependencies dependencies)
            : SqlServerAnnotationProvider(dependencies)
        {
            public override IEnumerable<IAnnotation> For(ITable table, bool designTime)
            {
                IEnumerable<IAnnotation> Custom()
                {
                    if (!designTime)
                    {
                        yield break;
                    }

                    yield return new Annotation("CustomAnnotation", "Some value");
                }

                return base.For(table, designTime).Concat(Custom());
            }
        }

        public class CustomMigrationsSqlGenerator(
            MigrationsSqlGeneratorDependencies dependencies,
            ICommandBatchPreparer commandBatchPreparer)
            : SqlServerMigrationsSqlGenerator(dependencies, commandBatchPreparer)
        {
            protected override void Generate(CreateTableOperation operation, IModel model, MigrationCommandListBuilder builder,
                bool terminate = true)
            {
                object myValue = operation["CustomAnnotation"];
                if (myValue == null)
                {
                    throw new InvalidOperationException("Expected my value!");
                }

                base.Generate(operation, model, builder, terminate);
            }
        }
    }
}


```

### Stack traces

Every test in that class fails with following stack trace:

```
System.InvalidOperationException
Expected my value!
   at Microsoft.EntityFrameworkCore.DataBindingSqlServerTest.AdvFixture.CustomMigrationsSqlGenerator.Generate(CreateTableOperation operation, IModel model, MigrationCommandListBuilder builder, Boolean terminate) in C:\repo\external\efcore2\efcore\test\EFCore.SqlServer.FunctionalTests\DataBindingSqlServerTest.cs:line 71
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__82_11(MigrationsSqlGenerator g, MigrationOperation o, IModel m, MigrationCommandListBuilder b) in C:\repo\external\efcore2\efcore\src\EFCore.Relational\Migrations\MigrationsSqlGenerator.cs:line 46
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder) in C:\repo\external\efcore2\efcore\src\EFCore.Relational\Migrations\MigrationsSqlGenerator.cs:line 159
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder) in C:\repo\external\efcore2\efcore\src\EFCore.SqlServer\Migrations\SqlServerMigrationsSqlGenerator.cs:line 103
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model, MigrationsSqlGenerationOptions options) in C:\repo\external\efcore2\efcore\src\EFCore.Relational\Migrations\MigrationsSqlGenerator.cs:line 124
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model, MigrationsSqlGenerationOptions options) in C:\repo\external\efcore2\efcore\src\EFCore.SqlServer\Migrations\SqlServerMigrationsSqlGenerator.cs:line 71
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.GetCreateTablesCommands(MigrationsSqlGenerationOptions options) in C:\repo\external\efcore2\efcore\src\EFCore.Relational\Storage\RelationalDatabaseCreator.cs:line 145
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.CreateTables() in C:\repo\external\efcore2\efcore\src\EFCore.Relational\Storage\RelationalDatabaseCreator.cs:line 121
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated() in C:\repo\external\efcore2\efcore\src\EFCore.Relational\Storage\RelationalDatabaseCreator.cs:line 248
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated() in C:\repo\external\efcore2\efcore\src\EFCore\Infrastructure\DatabaseFacade.cs:line 79
   at Microsoft.EntityFrameworkCore.TestUtilities.DatabaseFacadeExtensions.<>c.<EnsureCreatedResiliently>b__0_0(DatabaseFacade f) in C:\repo\external\efcore2\efcore\test\EFCore.Specification.Tests\TestUtilities\DatabaseFacadeExtensions.cs:line 9
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext _, TState s) in C:\repo\external\efcore2\efcore\src\EFCore\Storage\ExecutionStrategyExtensions.cs:line 392
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass28_0`2.<Execute>b__0(DbContext context, TState state) in C:\repo\external\efcore2\efcore\src\EFCore\Storage\ExecutionStrategy.cs:line 207
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state) in C:\repo\external\efcore2\efcore\src\EFCore\Storage\ExecutionStrategy.cs:line 224
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded) in C:\repo\external\efcore2\efcore\src\EFCore\Storage\ExecutionStrategy.cs:line 206
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation, Func`2 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation) in C:\repo\external\efcore2\efcore\src\EFCore\Storage\ExecutionStrategyExtensions.cs:line 331
   at Microsoft.EntityFrameworkCore.TestUtilities.DatabaseFacadeExtensions.EnsureCreatedResiliently(DatabaseFacade façade) in C:\repo\external\efcore2\efcore\test\EFCore.Specification.Tests\TestUtilities\DatabaseFacadeExtensions.cs:line 9
   at Microsoft.EntityFrameworkCore.TestUtilities.SqlServerTestStore.Initialize(Func`1 createContext, Action`1 seed, Action`1 clean) in C:\repo\external\efcore2\efcore\test\EFCore.SqlServer.FunctionalTests\TestUtilities\SqlServerTestStore.cs:line 101
   at Microsoft.EntityFrameworkCore.TestUtilities.TestStore.<>c__DisplayClass13_0.<Initialize>b__0() in C:\repo\external\efcore2\efcore\test\EFCore.Specification.Tests\TestUtilities\TestStore.cs:line 36
   at Microsoft.EntityFrameworkCore.TestUtilities.TestStoreIndex.CreateShared(String name, Action initializeDatabase) in C:\repo\external\efcore2\efcore\test\EFCore.Specification.Tests\TestUtilities\TestStoreIndex.cs:line 25
   at Microsoft.EntityFrameworkCore.TestUtilities.TestStore.Initialize(IServiceProvider serviceProvider, Func`1 createContext, Action`1 seed, Action`1 clean) in C:\repo\external\efcore2\efcore\test\EFCore.Specification.Tests\TestUtilities\TestStore.cs:line 36
   at Microsoft.EntityFrameworkCore.TestUtilities.RelationalTestStore.Initialize(IServiceProvider serviceProvider, Func`1 createContext, Action`1 seed, Action`1 clean) in C:\repo\external\efcore2\efcore\test\EFCore.Relational.Specification.Tests\TestUtilities\RelationalTestStore.cs:line 40
   at Microsoft.EntityFrameworkCore.SharedStoreFixtureBase`1.InitializeAsync() in C:\repo\external\efcore2\efcore\test\EFCore.Specification.Tests\SharedStoreFixtureBase.cs:line 65
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90

```

Db context with those two class overrides works fine on regular usage (outside this test).

### Include provider and version information

EF Core version: v8.0.6
Database provider: Microsoft.EntityFrameworkCore (i have issue in EFCore.Snowflake)
Target framework: .NET 8.0

**Comment by AndriySvyryd** [comment]
It doesn't repro in main, I might have fixed it in [9527e8ac879e0209dfdc3d2da5c8b64699d2dc2c](https://github.com/dotnet/efcore/commit/fa093d46c94d490317ee87ac257ed5f37a3f5565)
