### ISSUE TITLE
Stuck on inherited entity model binding

### ISSUE THREAD

**Issue by alexandis** [dotnet/efcore#34107]
I will try to describe the issue as briefly as possible.

1) Nuget package **EntityConfig** contains model-DB mappings;
2) Nuget package **Base** contains entity `TenantInner` and consumes **EntityConfig**: entity `TenantInner` is bound to table `TENANT`;
3) Solution **MySolution** consumes packages **EntityConfig** and **Base** and contains entity `Tenant` which inherits `TenantInner`. `Tenant` only contains navigation properties and naturally references the same table `TENANT`.

Problem: I cannot make this structure work, getting either "A key cannot be configured on 'Tenant' because it is a derived type" or "ORA-00904: "C1"."DISCRIMINATOR": invalid identifier" exceptions, depending on all the ways I've tried to resolve the issue.

My latest setup (I don't think `TenantInner` structure is relevant here, so skipping):

```
    public class TenantEntityConfig<TBase> : EntityConfigBase<TBase> where TBase : TenantEntity
    {
        public TenantEntityConfig(Action<EntityTypeBuilder<TBase>> builder = null)
            : base(builder)
        { }

        public override void Configure(EntityTypeBuilder<TBase> builder)
        {
            builder.ToTable("TENANT");
            builder.HasKey(x => x.Id);
            builder.Property(x => x.Id)
                   .HasColumnName("ID").IsRequired()
                   .ValueGeneratedNever();
            builder.Property(x => x.ShortName)
                   .HasColumnName("NAME")
                   .HasMaxLength(TenantEntityDbConst.ShortNameMaxLength);
            ...
            builder.Property(x => x.CompanyId)
                   .HasColumnName("COMPANY_ID").IsRequired();
            ...
            base.Configure(builder);
        }
    }

    public class TenantEntityConfig : TenantEntityConfig<TenantEntity>
    { }

    public class Tenant : TenantInner
    {
        public Company Company { get; set; }
        ...
    }

    builder.ApplyConfiguration(new TenantEntityConfig<TenantInner>());
    builder.Entity<Tenant>(builder =>
    {
        builder.HasBaseType<TenantInner>();
        builder.HasOne(x => x.Company)
               .WithMany()
               .HasPrincipalKey(x => x.Id)
               .HasForeignKey(x => x.CompanyId);
        ...
    });
```

**Comment by alexandis** [comment]
> This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

Saying honestly, I am puzzled with that request. Is there some sandbox to your knowledge (with access to some dummy data online DB, even though we use Oracle, I think MS SQL Express will do) I can try to reproduce this and share the link with you?

**Comment by alexandis** [comment]
Please find attached the SIMPLIFIED version. However, it looks like the root cause is the same. Just in case, I am also adding front-end part - the error is reproduced when trying to run the site.

The error in backend: "Invalid column name 'Discriminator'".
The expected and required behavior: both `ExtendedGood` and `Good` classes work without hitch with the same DB table.

[Sasha.zip](https://github.com/user-attachments/files/16059830/Sasha.zip)

**Comment by ajcvickers** [comment]
@alexandis I don't see any error when running your code. Can you post the full exception and stack trace?

**Comment by alexandis** [comment]
Sure. When running front-end - `https://localhost:4300` - getting this:

> Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Discriminator'.
>    at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
>    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
> --- End of stack trace from previous location ---
>    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
> ClientConnectionId:349f16e3-ab59-4b68-9184-a0459b2e47b6
> Error Number:207,State:1,Class:16
> Exception thrown: 'Microsoft.Data.SqlClient.SqlException' in System.Private.CoreLib.dll
> Exception thrown: 'Microsoft.Data.SqlClient.SqlException' in System.Private.CoreLib.dll
> The thread '.NET TP Worker' (41216) has exited with code 0 (0x0).
> The thread '.NET TP Worker' (36632) has exited with code 0 (0x0).

**Comment by ajcvickers** [comment]
@alexandis You configuration creates a [mapped inheritance hierarchy using TPH mapping](https://learn.microsoft.com/en-us/ef/core/modeling/inheritance):

```
Model: 
  EntityType: ExtendedGood Base: Good
  EntityType: Good
    Properties: 
      Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd
      Description (string)
      Discriminator (no field, string) Shadow Required AfterSave:Throw MaxLength(13)
      Name (string) Required
    Keys: 
      Id PK
```

This means that the table needs to have a discriminator column in order to determine which of the two types to create when executing a query. EF Core doesn't support having multiple types mapped to the same table, but without any inheritance mapping or relationship between the two types. This is because EF cannot determine the type to create for each row read.

Note for team: should we allow this with shared-type entity types?

**Comment by AndriySvyryd** [comment]
> should we allow this with shared-type entity types?

No. We still a discriminator to determine which entity type to use. If we were to allow instantiating either then it would become a particular case of https://github.com/dotnet/efcore/issues/15310

**Comment by alexandis** [comment]
Hmm... So what is the way out in my situation? I have a base type in Nuget package. And I have the inherited types in the solutions which consume this Nuget package. Each of the inherited types have Navigation properties for types, which I cannot move to the Nuget package. But from DB perspective, the base type and the inherited types still reference the same DB table. Pretty common situation, IMHO...

**Comment by alexandis** [comment]
Any update here?

**Comment by ajcvickers** [comment]
@alexandis I don't believe there is any way to map those entity types. EF needs to understand the relationship between the types in order to determine what types to create and which navigations we refer to which types.

**Comment by ajcvickers** [comment]
Putting on the backlog to consider if we should do any kind of model validation against this.

**Comment by AndriySvyryd** [comment]
Related: https://github.com/dotnet/efcore/issues/34368

**Comment by DanielStout5** [comment]
Are there any options for an interim workaround here? I'm in a very similar situation:

1. BaseDbContext in base project defines User entity and has other entities that relate to it
2. SubDbContext in sub project extends BaseDbProject and adds its own entities that also relate to User
3. This works fine, but there's no way to to load a user and `Include` the sub-project defined entities. Ideally the sub project could define its own version of user with its new navigation properties. It almost seems like it would work, but the model snapshot now contains a Discriminator property despite that column not existing. Calling `HasNoDiscriminator()` throws the exception `Unable to create a 'DbContext' of type 'SubDbContext'. The exception 'Both 'SubUser' and 'User' are mapped to the table 'AspNetUsers'`

The queries on `BaseDbContext.User` would always return type `User` and on `SubDbContext.SubUsers` would always return `SubUser` so I don't see any need for a discriminator, because there are no actual differences in the properties between the two types
