### ISSUE TITLE
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'

### ISSUE THREAD

**Issue by Sayan751** [dotnet/efcore#34273]
## Ask a question

I am seeing the following error sporadically.

```
An error occurred using the connection to database 'main' on server 'path\to\db'.

Exception: 
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnectionInternal..ctor(SqliteConnectionStringBuilder connectionOptions, SqliteConnectionPool pool)
   at Microsoft.Data.Sqlite.SqliteConnectionFactory.GetConnection(SqliteConnection outerConnection)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
```

I am using pooled database context and factory. My assumption here is that concurrent write-operations is causing the issue. Or as far as I understand, as the DB is locked during a write-operation, a read-operation at the same, can also cause the issue.

As I cannot deterministically reproduce the issue, I would like to ask if anyone can point me in the direction, to better debug and solve this issue.

#### Program.cs

```C#
services
	.AddDbContextPool<DatabaseContext>((serviceProvider, options) =>
	{
		Directory.CreateDirectory(ApplicationDataPath);
		options.UseSqlite($"Data Source={Path.Combine(ApplicationDataPath, "data.db")}");
		options.AddInterceptors(serviceProvider.GetRequiredService<DatabaseConnectionInterceptor>());
	})
	.AddPooledDbContextFactory<DatabaseContext>(options => { });
services.AddHostedService<DatabaseMigrationService>();
```

#### DatabaseContext.cs

```cs
using Microsoft.EntityFrameworkCore;
using SQLitePCL;

public class DatabaseContext : DbContext
{
	public DatabaseContext(DbContextOptions<DatabaseContext> options) : base(options) { }

	protected override void OnConfiguring(DbContextOptionsBuilder options)
	{		
		Batteries.Init();
	}
}
```

#### DatabaseMigrationService.cs

```cs
public class DatabaseMigrationService : IHostedLifecycleService
{
	private readonly IDbContextFactory<DatabaseContext> _DbContextFactory;

	public DatabaseMigrationService(IDbContextFactory<DatabaseContext> dbContextFactory)
	{
		_DbContextFactory = dbContextFactory;
	}

	public async Task StartingAsync(CancellationToken cancellationToken)
	{
		await using var ctx = await _DbContextFactory.CreateDbContextAsync(cancellationToken);
		await ctx.Database.MigrateAsync(cancellationToken);
	}

	public Task StartAsync(CancellationToken cancellationToken) => Task.CompletedTask;
	public Task StartedAsync(CancellationToken cancellationToken) => Task.CompletedTask;
	public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;
	public Task StoppedAsync(CancellationToken cancellationToken) => Task.CompletedTask;
	public Task StoppingAsync(CancellationToken cancellationToken) => Task.CompletedTask;
}
```

As there is another background service that runs tasks periodically (also a `IHostedLifecycleService`, and uses the `StartedAsync` hook), any timing conflict during the startup of the service should be avoided.

#### DatabaseConnectionInterceptor.cs

```cs
public class DatabaseConnectionInterceptor : DbConnectionInterceptor
{
	private readonly ILogger<DatabaseConnectionInterceptor> _Logger;

	public DatabaseConnectionInterceptor(ILogger<DatabaseConnectionInterceptor>  logger)
	{
		_Logger = logger;
	}

	public override void ConnectionFailed(DbConnection connection, ConnectionErrorEventData eventData)
	{
		base.ConnectionFailed(connection, eventData);
		Log(eventData);
	}

	public override async Task ConnectionFailedAsync(DbConnection connection, ConnectionErrorEventData eventData, CancellationToken cancellationToken = default)
	{
		await base.ConnectionFailedAsync(connection, eventData, cancellationToken);
		Log(eventData);
	}

	private void Log(ConnectionErrorEventData eventData) => _Logger.LogWarning(WarningEvents.DatabaseConnectionFailed, eventData.Exception, "Connection failed: {Error}", eventData.ToString());
}
```

### Include stack traces

See above.

### Include verbose output

NA

### Include provider and version information

EF Core version: 8.0.7
Database provider: Microsoft.EntityFrameworkCore.Sqlite 8.0.7
Target framework: net 8
Operating system: Windows Server
IDE: Visual Studio 2022 17.4

### Additional details and questions

- I have a queuing service, that writes to a database table. The same service is also periodically triggered to process the queued stuff that involves both read and write.
- On the other hand, there are endpoints with high traffic that involves only (happy-path) reading from the database. One of these endpoints uses the queuing service to write to the database.
- My assumption is that when the queuing service locks the DB for the write operation, any other attempt to establish a connection fails. Is this assumption unfounded?
- I am inclining towards employing a semaphoreslim in the queuing service for the db operations. However, I don't want to write noisy code in every other endpoints to check the semaphore status and perform operations conditionally or wait. Is there a better way?

**Comment by Sayan751** [comment]
It seems that the issue occurs if there are many pending migrations. Here is a reproduction of this issue: https://github.com/Sayan751/efcore-sqlite-issue-34273

**Comment by Sayan751** [comment]
The issue also exists for .net 9.0. The reproduction can be found here: https://github.com/Sayan751/efcore-sqlite-issue-34273/tree/net9

**Comment by WeihanLi** [comment]
Same issue, works on windows but failed on linux container

**Comment by ajcvickers** [comment]
@Sayan751 It sounds like the database is being used while migrations are running. This is not supported--you must ensure that the database is migrated by only a single process and that nothing else uses the database while migrations are executing. EF9 has [some support for doing this automatically](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-9.0/whatsnew#protection-against-concurrent-migrations). If you're using EF8, then you'll need to manage it yourself.

**Comment by Sayan751** [comment]
@ajcvickers In the reproduction, it does nothing except migrating the database. And that too happens right when the app starts. There is nothing else, as per my knowledge, in the "devland" that uses the database right when it is being migrated.

In the real app, the migration is done inside a `IHostedLifecycleService#StartingAsync` callback to ensure that the migration is completed before anything else happens. And there too, the issue can be reproduced. I am assuming, at this point, that some other internal aspnet/efcore infra is trying to access the database during the app start and as the database is being migrated at the point, we are seeing this issue.

**Comment by rampaa** [comment]
I also get the following exception intermittently without ever using EF Core.

```csharp
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnectionInternal..ctor(SqliteConnectionStringBuilder connectionOptions, SqliteConnectionPool pool)
   at Microsoft.Data.Sqlite.SqliteConnectionPool.GetConnection()
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
```

I try to guard it like the following currently:
```csharp
    internal static SqliteConnection? CreateReadOnlyDBConnection(string path)
    {
        SqliteConnection connection = new($"Data Source={path};Mode=ReadOnly;");
        try
        {
            connection.Open();
            return connection;
        }
        catch (SqliteException ex)
        {
            LoggerManager.Logger.Error(ex, "Failed to open DB connection in read-only mode for path: {DBPath}", path);
            connection.Dispose();
            return null;
        }
    }
```

But I wonder if the underlying issue can be solved instead. I also wonder if there’s a more robust way to guard against this error, for example, would it be advisable to use some sort of retry mechanism here? Since I don’t understand the underlying cause, I’m not sure what the best course of action is.

**Comment by Laim** [comment]
Also getting this, using EF Core with SQLite.  It doesn't seem to bring my app down or anything, but it spams my logs every so often with 

```
2026-04-27 03:14:31.734 +00:00 [ERR] [Microsoft.EntityFrameworkCore.Database.Connection] An error occurred using the connection to database 'main' on server '/data/database/app.db'.
2026-04-27 03:14:31.938 +00:00 [ERR] [Microsoft.EntityFrameworkCore.Database.Connection] An error occurred using the connection to database 'main' on server '/data/database/app.db'.
2026-04-27 03:14:32.538 +00:00 [ERR] [Microsoft.EntityFrameworkCore.Database.Connection] An error occurred using the connection to database 'main' on server '/data/database/app.db'.
```

How I add my DbContext
```csharp
            builder.Services.AddDbContext<ApplicationDbContext>((sp, options) =>
            {
                options
                    .UseSqlite(connectionString, sqlite =>
                    {
                        sqlite.CommandTimeout(dbCommandTimeout);
                        sqlite.UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery);
                    })
                    .AddInterceptors(sp.GetRequiredService<SqlitePragmaConnectionInterceptor>());
            });
```

Like I said, seems to be fine most of the time but occasionally get this out of the blue and I cannot recreate it for the life of me to find out what's actually causing it.

Note that I do not have any pending migrations and as of right now the app only has two migrations, both done weeks ago but this issue was occuring before the second migration was added, so I don'tt hink it's related to that.
