### ISSUE TITLE
Error when joining to table with composite key

### ISSUE THREAD

**Issue by jparish9** [dotnet/efcore#3427]
Windows 10, VS 2015, IIS Express, SQL Server Express 2014, EF 7.0.0-beta7, ASP.NET 6.0.0-beta7

I am seeing an exception when trying to use a where clause that references a table with a composite key.

Models:

``` c#
public class Blog
    {
        public int BlogId { get; set; }

        public int Year { get; set; }

        [StringLength(100)]
        public String Name { get; set; }

        public ICollection<Post> Posts { get; set; }
    }
```

``` c#
public class Post
    {
        public int PostId { get; set; }

        public int BlogId { get; set; }

        public int Year { get; set; }

        public Blog Blog { get; set; }

        public DateTime DatePosted { get; set; }

        public String PostHtml { get; set; }
    }
```

Primary/foreign key setup:

``` c#
   modelBuilder.Entity<Blog>().Key(t => new { t.BlogId, t.Year });

   modelBuilder.Entity<Post>().Reference(t => t.Blog)
       .InverseCollection(b => b.Posts).ForeignKey(t => new { t.BlogId, t.Year });
```

Attempted query:

``` c#
   _dbContext.Posts
       .Where(p => p.Blog.Name == "test")
       .ToList();
```

Exception:

```
Sequence contains more than one element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.NavigationRewritingExpressionVisitor.CreateJoinsForNavigations(QuerySourceReferenceExpression outerQuerySourceReferenceExpression, IEnumerable`1 navigations)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.NavigationRewritingExpressionVisitor.<>c__DisplayClass8_0.<VisitMember>b__0(IEnumerable`1 ps, IQuerySource qs)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpressionCore[TResult](MemberExpression memberExpression, IQuerySource querySource, Func`3 memberBinder)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindNavigationPathMemberExpression[TResult](MemberExpression memberExpression, Func`3 memberBinder)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.NavigationRewritingExpressionVisitor.VisitMember(MemberExpression memberExpression)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.NavigationRewritingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Clauses.WhereClause.TransformExpressions(Func`2 transformation)
   at Remotion.Linq.QueryModel.TransformExpressions(Func`2 transformation)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.NavigationRewritingExpressionVisitor.Rewrite(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.Storage.RelationalDatabase.CompileQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Data.Entity.Query.CompiledQueryCache.CompileQuery(IDatabase database, MethodInfo compileMethodInfo, Type resultItemType, QueryModel queryModel)
   at Microsoft.Data.Entity.Query.CompiledQueryCache.<>c__7`1.<Execute>b__7_0(Expression q, IDatabase ds)
   at Microsoft.Data.Entity.Query.CompiledQueryCache.GetOrAdd(Expression query, QueryContext queryContext, IDatabase database, Boolean isAsync, Func`3 compiler)
   at Microsoft.Data.Entity.Query.CompiledQueryCache.Execute[TResult](Expression query, IDatabase database, QueryContext queryContext)
   at Microsoft.Data.Entity.Query.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
...
```

This is happening with no data in either of the tables, and any time I try to reference `p.Blog` in the `Where` clause.  Referencing it in an `.Include` clause, however, works fine:

``` c#
  _dbContext.Posts.Where(p => p.PostHtml.Contains("test"))
     .Include(p => p.Blog)
     .ToList();
```

If I make `Blog` a single primary key and a simple (automatic) join between it and `Post`, things also work fine.  Am I missing some configuration on the join or is this a bug?

**Comment by rowanmiller** [comment]
@jparish9 Can you retry on Beta 8 (published yesterday). This code path has changed significantly.

**Comment by jparish9** [comment]
@rowanmiller This seems to be working correctly with beta 8, using renamed fluent API methods:
```c#
modelBuilder.Entity<Blog>().HasKey(t => new { t.BlogId, t.Year });

modelBuilder.Entity<Post>().HasOne(t => t.Blog)
       .WithMany(b => b.Posts).ForeignKey(t => new { t.BlogId, t.Year });
```

**Comment by rowanmiller** [comment]
Great, closing out this issue. Feel free to open a new issue if you hit other issues.
