### ISSUE TITLE
Strange behaviour when using parameter in mapping and predicate

### ISSUE THREAD

**Issue by koentsas** [dotnet/efcore#34272]
Unexpected behaviour is occuring when I use the 'characterId' parameter in the Select object mapping AND the SingleAsync. See code below.
```C#
public async Task<CharacterDto> GetCharacter(long characterId, CancellationToken cancellationToken)
{
    var data = await _context.Characters
        .AsNoTracking()
        .Select(c => new CharacterDataDto
        {
            Name = c.Name,
            Player = c.Player,
            Active = c.Active,
            Alignment = c.Alignment,
            CharacterId = characterId,
            CurrentXP = c.CurrentXP,
            GroupId = c.GroupId,
            HP = c.HP,
            ImageUrl = c.ImageUrl,
            Languages = c.Languages,
            Nickname = c.Nickname,
            Race = c.Race,
            VisionsAndSenses = c.VisionsAndSenses,
            Wealth = c.Wealth
        })
        .SingleAsync(m => m.CharacterId == characterId, cancellationToken);
    return data;
}
```

Generates following sql and error:

```
Executed DbCommand (28ms) [Parameters=[@__characterId_0='?' (DbType = Int64)], CommandType='Text', CommandTimeout='30']
      SELECT TOP(2) [c].[Name], [c].[Player], [c].[Active], [c].[Alignment], @__characterId_0 AS [CharacterId], [c].[CurrentXP], [c].[GroupId], [c].[HP], [c].[ImageUrl], [c].[Languages], [c].[Nickname], [c].[Race], [c].[VisionsAndSenses], [c].[Wealth]
      FROM [Character] AS [c]
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: Sequence contains more than one element.
         at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
         at DnD.Backend.Data.Repositories.CharacterRepository.GetCharacter(Int64 characterId, CancellationToken cancellationToken) in C:\Projects\GIT\DnDv2\back-end\DnD.Backend\DnD.Backend.Data\Repositories\CharacterRepository.cs:line 20
         at DnD.Backend.WebApi.Controllers.CharacterController.Get(Int64 characterId, CancellationToken cancellationToken) in C:\Projects\GIT\DnDv2\back-end\DnD.Backend\DnD.Backend.WebApi\Controllers\CharacterController.cs:line 18
         at lambda_method5(Closure, Object)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

If I correct the mapping to 'c.CharacterId' instead of 'characterId' in the Select, the correct SQL is being generated.

EF Core version: 8.0.7
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET8
Operating system: /
IDE: Visual Studio 2022 17.10.3

**Comment by cincuranet** [comment]
This is expected behavior. You're selecting bunch of rows from database with constant `characterId`. The result set looks like this in a nutshell.

| Name | Player | CharacterId |
|-|-|-|
| Name1 | Player1 | `characterId` |
| Name2 | Player2 | `characterId` |
| Name3 | Player3 | `characterId` |

EF then optimizes the `m.CharacterId == characterId` condition away, because it will be true for all rows. And finally you get more than row in the result and hence exception.
