### ISSUE TITLE
Invalid Column Name 'XXX' Exception When Using GroupJoin Without Foreign Key Relationship

### ISSUE THREAD

**Issue by supershowwei** [dotnet/efcore#34339]
## File a bug

I have two tables, `Order` and `OrderItem`. Since there is no foreign key established between these two tables, I created an additional `OrderAssociations` class as a partial class for `Order` and added the `public IEnumerable<OrderItem> OrderItems` property. I used the `GroupJoin` method to link `Order.Id` and `OrderItem.OrId` in the query and specified the value for `OrderItems` in the resultSelector. However, I encountered the error `'Microsoft.Data.SqlClient.SqlException: 'Invalid column name 'OrderId'.''` Even if I create an alias name 'OrderId' for `OrderItem.OrId`, the error persists. I expect that creating a hierarchical relationship class should be possible.

### Include your code

I have provided the code at https://github.com/supershowwei/efcore-8-associate-column-issue

### Include stack traces

```
Invalid column name 'OrderId'.

   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteReaderAsync>d__18.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteReaderAsync>d__18.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.<InitializeReaderAsync>d__21.MoveNext()
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.<MoveNextAsync>d__20.MoveNext()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__67`1.MoveNext()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__67`1.MoveNext()
   at EFCore8AssociateColumnIssue.Program.<Main>d__0.MoveNext() in D:\Lab\efcore-8-associate-column-issue\src\EFCore8AssociateColumnIssue\EFCore8AssociateColumnIssue\Program.cs:line 17
```

### Include provider and version information

EF Core version:
8.0.7

Database provider:
Microsoft.EntityFrameworkCore.SqlServer

Target framework:
.NET 8

Operating system:
Windows 11 Pro

IDE:
Visual Studio 2022 Enterprise

**Comment by supershowwei** [comment]
@roji In the repository https://github.com/supershowwei/efcore-8-associate-column-issue, I have included my Schema and Test Data, which you can find here: https://github.com/supershowwei/efcore-8-associate-column-issue/blob/main/src/EFCore8AssociateColumnIssue/EFCore8AssociateColumnIssue/SchemaAndTestData.sql.

The issue lies in the fact that my two tables are joined using `OrderItem.OrId = Order.Id` in a `GroupJoin`, but EF Core, following naming conventions, automatically generated the `OrderItem.OrderId` column in the query. This is redundant because the `OrderItem` table has a column named `OrId`, not `OrderId`.

**Comment by roji** [comment]
@supershowwei if you tell EF to create the table, you'll see the following:

```sql
CREATE TABLE [OrderItem] (
  [Id] int NOT NULL,
  [OrId] varchar(50) NOT NULL,
  [ProductName] nvarchar(50) NOT NULL,
  [Price] decimal(18,5) NOT NULL,
  [Count] int NOT NULL,
  [OrderId] varchar(50) NULL,
  CONSTRAINT [PK_OrderItem] PRIMARY KEY ([Id]),
  CONSTRAINT [FK_OrderItem_Order_OrderId] FOREIGN KEY ([OrderId]) REFERENCES [Order] ([Id])
);
```

As you can see, there's OrId in there - which is the property on your OrderItem class, but there's also OrderId, which EF automatically adds by convention because Order has the OrderItems property (which is a `IEnumerable<OrderItem>`). This makes EF detect a one-to-many relationship between Order and OrderItem, and, since it can't detect a foreign key property on OrderItem (OrId is a non-standard name), it adds an OrderId shadow property.

You probably want to tell EF that you want OrId to be the foreign key, at which point it will no longer add an Orderid shadow property; [see the docs for information on how to do that](https://learn.microsoft.com/en-us/ef/core/modeling/relationships/one-to-many).

I'll go ahead and close this as a model misconfiguration, but if you need more assistance or have questions, feel free to post back here.
