### ISSUE TITLE
Owned entity with ForeignKey throws exception from ModelSnapshot when applying migration

### ISSUE THREAD

**Issue by goryaynov-leonid** [dotnet/efcore#34386]
## File a bug

Faced a strange behavior of model snapshot scaffolding.
I have some `Address` entity wich has link to some `Country` entity, and this `Address` entity has different "owners" e. g. `User` and `Company`. 

When I scaffold migration for this and try to apply it application fails with exception going from ModelSnapshot.

Linked test project to reproduce this issue [TestEFProject.zip](https://github.com/user-attachments/files/16541546/TestEFProject.zip)
### Include your code

Models:
```C#
    public class Address
    {
        public Country Country {  get; set; }
        public int CountryId { get; set; }
        public string Name { get; set; }
    }
```

```C#
    public class Country
    {
        public int Id { get; set; }
    }
```
```C#
    public class User
    {
        public int Id { get; set; }
        public Address Address { get; set; }
    }
```

```C#
    public class Company
    {
        public int Id { get; set; }
        public Address Address { get; set; }
    }
```

DbContext:
```C#
     public class TestDbContext : DbContext
    {
        public TestDbContext(DbContextOptions<TestDbContext> options) : base(options) { }

        public DbSet<User> Users { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<Country> Countries { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>().OwnsOne(x => x.Address,
                builder => 
                    builder.HasOne(x => x.Country)
                    .WithOne()
                    .HasForeignKey<Address>());

            modelBuilder.Entity<Company>().OwnsOne(x => x.Address, builder => 
                builder.HasOne(x => x.Country)
                .WithOne()
                .HasForeignKey<Address>());

            base.OnModelCreating(modelBuilder);
        }
    }
```
### Include stack traces

After scaffolding migration and trying to apply it from Package Manager Console I get such exception
```
System.InvalidOperationException: You are configuring a relationship between 'Company.Address#TestEFProject.Models.Address' and 'TestEFProject.Models.Country (Dictionary<string, object>)' but have specified a foreign key on 'TestEFProject.Models.Company.Address#Address'. The foreign key must be defined on a type that is part of the relationship.
   at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceReferenceBuilder.HasForeignKeyBuilder(EntityType dependentEntityType, String dependentEntityTypeName, Func`3 hasForeignKey)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceReferenceBuilder.HasForeignKeyBuilder(EntityType dependentEntityType, String dependentEntityTypeName, IReadOnlyList`1 foreignKeyPropertyNames)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceReferenceBuilder.HasForeignKey(String dependentEntityTypeName, String[] foreignKeyPropertyNames)
   at TestEFProject.Migrations.InitMigration.<>c.<BuildTargetModel>b__2_5(OwnedNavigationBuilder b1) in C:\Git\TestEFProject\Migrations\20240808100817_InitMigration.Designer.cs:line 89
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder.OwnsOne(String ownedTypeName, String navigationName, Action`1 buildAction)
   at TestEFProject.Migrations.InitMigration.<>c.<BuildTargetModel>b__2_3(EntityTypeBuilder b) in C:\Git\TestEFProject\Migrations\20240808100817_InitMigration.Designer.cs:line 67
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity(String name, Action`1 buildAction)
   at TestEFProject.Migrations.InitMigration.BuildTargetModel(ModelBuilder modelBuilder) in C:\Git\TestEFProject\Migrations\20240808100817_InitMigration.Designer.cs:line 65
   at Microsoft.EntityFrameworkCore.Migrations.Migration.<get_TargetModel>g__Create|5_0()
   at Microsoft.EntityFrameworkCore.Migrations.Migration.get_TargetModel()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass16_2.<GetMigrationCommandLists>b__2()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
You are configuring a relationship between 'Company.Address#TestEFProject.Models.Address' and 'TestEFProject.Models.Country (Dictionary<string, object>)' but have specified a foreign key on 'TestEFProject.Models.Company.Address#Address'. The foreign key must be defined on a type that is part of the relationship.
```

But if I change 3rd line in this Snapshot fragment (and in Migration Designer file) from this:
```
   b1.HasOne("TestEFProject.Models.Country", "Country")
       .WithOne()
       .HasForeignKey("TestEFProject.Models.User.Address#Address", "CountryId")
       .OnDelete(DeleteBehavior.Cascade)
       .IsRequired();
```

to this (and with `Owner2` too):

```
   b1.HasOne("TestEFProject.Models.Country", "Country")
       .WithOne()
       .HasForeignKey("TestEFProject.Models.Address", "CountryId")
       .OnDelete(DeleteBehavior.Cascade)
       .IsRequired();
```
Migration succsesfully applies, and all of it works.
Is it a bug of scaffolding or I do something wrong?

### Include provider and version information

EF Core version: 6.0.32
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system:
IDE: Visual Studio 2022 17.9.4

**Comment by AndriySvyryd** [comment]
This is fixed in 8.0.8
The old snapshot would still need to be fixed manually, but the new generated code is:
```C#
.HasForeignKey("TestEFProject.Models.Company.Address#TestEFProject.Models.Address", "CountryId")
```
and
```C#
.HasForeignKey("TestEFProject.Models.User.Address#TestEFProject.Models.Address", "CountryId")
```

The fix however will not be ported to 6.0.x unless this is reported by more users.
