### ISSUE TITLE
PendingMigrations: A command is already in progress

### ISSUE THREAD

**Issue by oONoobMasterOo** [dotnet/efcore#34456]
Hello, 
im trying to do **scaffolding** and **update-database**  programmatically with Npgsql provider, but im getting an error while trying to  `GetPendingMigrationsAsync` :  **_A command is already in progress_**

my code:

```
using (var context = Activator.CreateInstance(DbContext, DbContextOptionsBuilderObject.Options) as DbContext)
{
    var HasPendingMigrations = (await context.Database.GetPendingMigrationsAsync()).Any();
    if (HasPendingMigrations)
    {
        await context.GetService<IMigrator>().MigrateAsync();
        Snackbar.Add("DbContext Updated Successfully !", Severity.Success);
    }
    else Snackbar.Add("DbContext : No changes, up to date.", Severity.Info);
}
```

stack trace:

```
 Npgsql.NpgsqlOperationInProgressException (0x80004005): A command is already in progress:
         at Npgsql.ThrowHelper.ThrowNpgsqlOperationInProgressException(NpgsqlCommand command)
         at Npgsql.Internal.NpgsqlConnector.<StartUserAction>g__DoStartUserAction|279_0(ConnectorState newState, NpgsqlCommand command, CancellationToken cancellationToken, Boolean attemptPgCancellation)
         at Npgsql.Internal.NpgsqlConnector.StartUserAction(ConnectorState newState, NpgsqlCommand command, CancellationToken cancellationToken, Boolean attemptPgCancellation)
         at Npgsql.Internal.NpgsqlConnector.StartUserAction(CancellationToken cancellationToken, Boolean attemptPgCancellation)
         at Npgsql.Internal.NpgsqlConnector.Reset(Boolean async)
         at Npgsql.NpgsqlConnection.CloseAsync(Boolean async)
         at Npgsql.NpgsqlConnection.Close()
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.CloseDbConnection()
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.ResetState(Boolean disposeDbConnection)
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Dispose()
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
         at Microsoft.EntityFrameworkCore.DbContext.Dispose()
```

EF Core version: 8.0.8
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET 8 ( Blazor Web App )
Operating system: Win 11 latest
IDE: Visual Studio 2022 17.11

**Comment by roji** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by oONoobMasterOo** [comment]
here is my full code sample:

`home.razor` file:

```
@layout ModulesLayout
@rendermode InteractiveServer

<button @onclick=@(async e => await UpdateDatabaseAsync("TestModule"))>Update-Database</button>

@code{
public async Task UpdateDatabaseAsync(string ModuleName)
{
    await TaskHelper.ExecuteTaskAsync(async () =>
    {
        if (ModuleName is not null)
        {
            var AssemblyTypes = AppDomain.CurrentDomain.GetAssemblies().FirstOrDefault(a => a.FullName.Contains($"{ModuleName}")).GetTypes();
            var DbContext = AssemblyTypes.Where(a => a.FullName == $"{ModuleName}.{ModuleName}DbContext").FirstOrDefault();
            if (DbContext is null) throw new InvalidOperationException($"DbContext type not found : {ModuleName}.{ModuleName}DbContext");

            var DbContextOptionsBuilderMethod = typeof(DbContextOptionsBuilder<>).MakeGenericType(DbContext);
            var DbContextOptionsBuilderConstructor = DbContextOptionsBuilderMethod.GetConstructor(new Type[] { });
            var DbContextOptionsBuilderContext = DbContextOptionsBuilderConstructor.Invoke(new object[] { });

            var UseNpgsqlMethod = typeof(NpgsqlDbContextOptionsBuilderExtensions).GetMethod("UseNpgsql", new Type[] { typeof(DbContextOptionsBuilder<>), typeof(string), typeof(Action<NpgsqlDbContextOptionsBuilder>) });
            var DbContextOptionsBuilder = new Action<NpgsqlDbContextOptionsBuilder>((a) => a.MigrationsAssembly($"{ModuleName}").MigrationsHistoryTable("__MigrationsHistory", ModuleName).CommandTimeout(int.MaxValue));

            var DbContextOptionsBuilderObject = (UseNpgsqlMethod.Invoke(null, new object[] { DbContextOptionsBuilderContext, ConnectionString, DbContextOptionsBuilder }) as dynamic);

            var enableSensitiveDataLoggingMethod = DbContextOptionsBuilderMethod.GetMethod("EnableSensitiveDataLogging", new[] { typeof(bool) });
            var enableDetailedErrorsMethod = DbContextOptionsBuilderMethod.GetMethod("EnableDetailedErrors", new[] { typeof(bool) });


            // Enable sensitive data logging and detailed errors
            enableSensitiveDataLoggingMethod.Invoke(DbContextOptionsBuilderContext, new object[] { true });
            enableDetailedErrorsMethod.Invoke(DbContextOptionsBuilderContext, new object[] { true });

            using (var context = Activator.CreateInstance(DbContext, DbContextOptionsBuilderObject.Options) as DbContext)
            {
                var HasPendingMigrations = (await context.Database.GetPendingMigrationsAsync()).Any();
                if (HasPendingMigrations)
                {
                    await context.GetService<IMigrator>().MigrateAsync();
                    Snackbar.Add("DbContext Updated Successfully !", Severity.Success);
                }
                else Snackbar.Add("DbContext : No changes, up to date.", Severity.Info);
            }
        }
        else Snackbar.Add($"Error: Module Not Found. ModuleName:{ModuleName}", Severity.Error);
    });
}
}
```


this line  `var HasPendingMigrations = (await context.Database.GetPendingMigrationsAsync()).Any()` gives the error: 
```
Npgsql.NpgsqlOperationInProgressException (0x80004005): A command is already in progress:
         at Npgsql.ThrowHelper.ThrowNpgsqlOperationInProgressException(NpgsqlCommand command)
```

**Comment by oONoobMasterOo** [comment]
for now i did a workaround :

```
 var MigrationsAssembly = context.Database.GetService<IMigrationsAssembly>();
 var AllMigrations = MigrationsAssembly.Migrations.Keys;
 var AppliedMigrations = new List<string>();
 var DataTableResult = await context.ExecuteDataTableAsync($"SELECT * FROM \"{ModuleName}\".\"__MigrationsHistory\"");
 if (DataTableResult.Item1)
 {
     foreach (DataRow data in DataTableResult.Item2.Rows)
     {
         AppliedMigrations.Add(data[0].ToString());
     }
 }

 var HasPendingMigrations = AllMigrations.Except(AppliedMigrations).Any();
```

**Comment by oONoobMasterOo** [comment]
any update?

I have successfully used **DbContext** directly without **System.Reflection**, and it works! However, creating the **DbContext** with **Reflection** at runtime does not yield the same result and gives error.

```
using var dbcon = await AdminDbContext.CreateDbContextAsync();
await dbcon.Database.MigrateAsync();   // this works !!

await context.Database.MigrateAsync(); // but this does not work !! and gives error:  A command is already in progress
```

**Comment by AndriySvyryd** [comment]
> any update?
> 
> I have successfully used **DbContext** directly without **System.Reflection**, and it works! However, creating the **DbContext** with **Reflection** at runtime does not yield the same result and gives error.
> 
> ```
> using var dbcon = await AdminDbContext.CreateDbContextAsync();
> await dbcon.Database.MigrateAsync();   // this works !!
> 
> await context.Database.MigrateAsync(); // but this does not work !! and gives error:  A command is already in progress
> ```

That's not executing the same code. Have you tried using `new DbContext(DbContextOptionsBuilderObject.Options)`?

If you are still experiencing this issue please share a small console app repro project

**Comment by oONoobMasterOo** [comment]
here is the sample blazor web app
[BlazorApp1.zip](https://github.com/user-attachments/files/17027038/BlazorApp1.zip)

**Comment by oONoobMasterOo** [comment]
any updates?

**Comment by oONoobMasterOo** [comment]
I discovered the issue was with the `CommandTimeout(int.MaxValue)`. After removing that, everything worked perfectly.
