### ISSUE TITLE
Unable to OrderBy when using primary constructor

### ISSUE THREAD

**Issue by LadislavBohm** [dotnet/efcore#34562]
## Ask a question

I need to construct a query that does projection (Select) first and then applies OrderBy/Where/Skip/Take etc. on the projected entity. It works when the projected type uses standard parameterless constructor and normal properties.

However when I try to use c# record for projected entity with single primary construtor it fails because it can't translate the OrderBy clause into SQL. I wonder if that is known limitation because I haven't found anything mentioned about it.

### Include your code

```
public class MyEntity {
  public int Id { get; set; }
  public string Name { get; set; }
}

public record MyEntityDto(string Name);

var result = context.Set<MyEntity>().Select(e => new MyEntityDto(e.Name)).OrderBy(dto => dto.Name).ToList();
```

### Include stack traces

```
System.InvalidOperationException: The LINQ expression 'DbSet<Team>()
    .OrderBy(t => new TestTeam(t.Id).Id)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ___REDACTED___DevExtremeQueryBuilder`2.ExecuteAsync(CancellationToken cancellationToken) in ___REDACTED___\DevExtremeQueryBuilder.cs:line 25
```

### Include provider and version information

EF Core version: 8.0.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8
Operating system: Win11
IDE: Rider 2024.2.2

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by LadislavBohm** [comment]
Ok I've created extremely simple app where there is an entity that is projected into two DTO objects. One with parameterless constructor and one with primary constructor. On last two lines it can be seen that one with no constructor works properly but the other does not.

[EFCore.ConstructorIssue.zip](https://github.com/user-attachments/files/16798604/EFCore.ConstructorIssue.zip)

**Comment by ajcvickers** [comment]
Note for query folks: this isn't about using a primary constructor or record, but rather projecting to a parameterized constructor of a non-mapped type. Do we have a dupe/common message for this?

**Comment by roji** [comment]
We currently allow instantiations in query as long as initializers are present:

```c#
_ = context.Set<MyEntity>()
    .Select(e => new MyEntityDto { Name = e.Name })
    .OrderBy(dto => dto.Name)
    .ToList();
```

But we fail if there are no initializers:

```c#
_ = context.Set<MyEntity>()
    .Select(e => new MyEntityDto(e.Name))
    .OrderBy(dto => dto.Name)
    .ToList();
```

We also both parameterless and non-parameterless constructors - as long as they have initializers; subsequent parts of the query may only reference properties which were initialized (e.g. Name above), anything else throws. Note that we have the same behavior for both mapped and unmapped types.

We could decide to treat non-parameterless constructors in the same way as we handle initializers, that is, translate `new MyEntityDto(e.Name)` the same way we translate `new MyEntityDto { Name = e.Name }`. This encodes an assumption that the constructor is basically a "primary-like constructor", i.e. that it has parameter names that correspond to properties on the type, and simply assigns those properties.

Note that C# now has records, which are a particularly good match for DTOs and also don't have a parameterless constructor by default; that should provide more motivation for doing this.

**Comment by jeremysalwen** [comment]
It would be helpful if this was possible even in some limited cases, such as for simple `record`s with positional constructors, or even just for specific classes (with the help of a user annotation).

**Comment by Rookian** [comment]
Is there a documentation about what kind of possibilities are (not) supported?

**Comment by roji** [comment]
@Rookian no. The space of possibilities of LINQ queries is very large, and it would be impractical to document everything (nor would such docs be very useful to users, IMHO).

**Comment by Rookian** [comment]
> @Rookian no. The space of possibilities of LINQ queries is very large, and it would be impractical to document everything (nor would such docs be very useful to users, IMHO). 

My question is specifically about when are ctors supported and when not?

**Comment by LordMike** [comment]
Could it be possible to add an attribute on ctor params, like an `[EfBackedBy(..)]`?

Then the following sample could work. Specifically, I'm on to what happens if the ctor params don't 1:1 match the properties, in this case its casing, but in other cases it could actually be, that the ctor param has a different name.

And then also, this feature is in its entirety very helpful for Records.

```csharp
public class MyEntity {
  public string Name { get; set; }
  
  public MyEntity([EfBackedBy(nameof(Name))]string name) { Name = name; }
}

_ = context.Set<MyEntity>()
    .Select(e => new MyEntityDto(e.Name))
    .OrderBy(dto => dto.Name)
    .ToList();
```

Sorry for the half post I made previously, I fumbled something and posted prematurely.

EDIT: Btw, I arrived here because we have some DTO's which have constructors so that our API internally can have validation and a slight transformation of some properties. We could remove the ctor and use plain DTO's for this case (initialization), but then we'd lose that consistency. For db queries, EF "just" has to assume that `ctor params == properties`, but still use the ctor when materializing. :)
