### ISSUE TITLE
Add View, TVF and SqlQuery mapping support for complex types

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#34627]
Related to #31235

**Comment by kirolous-nashaat** [comment]
Hello @AndriySvyryd , am looking forward to work on this issue.
I looked at CreateViewMapping , and it seems that we are not adding runtime mappings for complex types (we do at CreateTableMapping)

Is adding the foreach loop just like createtablemapping is enough to fix this ?
something like this commit: https://github.com/dotnet/efcore/commit/0d1f0c147f5e02e71086fac798905c2536798ee2
we also have to change some type params from IEntityType to ITypeBase; just like table mappings

the only concern i have after further thoughts:
https://github.com/dotnet/efcore/blob/6dcffd05b6ce94b2a50fed65309c09cb6929da5c/test/EFCore.Relational.Specification.Tests/BulkUpdates/NonSharedModelBulkUpdatesRelationalTestBase.cs#L112
this test does fail , but it test that the select expression throw exception, which shouldn't be the case; as we should query complex type with no issues
the issue is with the update logic using select expression translation first then trying to update
it still fails with an exception but different one sql command exception as it's trying to update the view not the table

**Comment by kirolous-nashaat** [comment]
looping @roji as he worked on that test above

**Comment by AndriySvyryd** [comment]
> something like this commit: https://github.com/dotnet/efcore/commit/0d1f0c147f5e02e71086fac798905c2536798ee2

Generally, on the right track, but `GetViewOrTableMappings` should still only return one set of mappings

> it still fails with an exception but different one sql command exception as it's trying to update the view not the table

The bulk update logic should be changed to only consider table mappings

**Comment by kirolous-nashaat** [comment]
> Generally, on the right track, but `GetViewOrTableMappings` should still only return one set of mappings

I didn't change this part. it still return one mapping

> The bulk update logic should be changed to only consider table mappings

does this have to be in the same pr ?
this change is more complex than just adding metadata for this issue.

I can add a boolean forUpdate (deafult: false) to indicate if the sql translator is for update or read

for example `_sqlTranslator.TryBindMember` will pass the new parameter to be true, and pass it down to
`structuralTypeProjection.BindComplexProperty`
to pass it down to `SelectExpression.GenerateComplexPropertyShaperExpression`

then we can only return the table mapping inside

but that leaves us with an issue that the `StructuralTypeProjectionExpression containerProjection` is still referencing the view not the table , so it will still fail with the old exception (in case of table+view mappings). is that okay ?

**Comment by kirolous-nashaat** [comment]
@AndriySvyryd test is failing for SQL 
is this related, or we need to update the base by using the env variable

```
Microsoft.EntityFrameworkCore.Scaffolding.CompiledModelSqlServerTest.ComplexTypes
System.AggregateException : Differences found in 1 files (Difference found in DbContextModelBuilder.cs)\r\n---- System.Exception : Difference found in DbContextModelBuilder.cs\r\n-------- Assert.Equal() Failure: Strings differ\r\n                                    ↓ (pos 53088)\r\nExpected: ···\";\\r\\n            var discriminatorViewColum\"···\r\nActual:   ···\";\\r\\n            var deetsViewColumn = new \"···\r\n                                    ↑ (pos 53088)
   at Microsoft.EntityFrameworkCore.Scaffolding.CompiledModelTestBase.AssertBaseline(IReadOnlyCollection`1 scaffoldedFiles, String testName) in /_/test/EFCore.Specification.Tests/Scaffolding/CompiledModelTestBase.cs:line 2195
   at Microsoft.EntityFrameworkCore.Scaffolding.CompiledModelTestBase.Test[TContext](Action`1 onModelCreating, Action`1 assertModel, Func`2 useContext, Action`1 onConfiguring, CompiledModelCodeGenerationOptions options, Func`2 addServices, Func`2 addDesignTimeServices, IEnumerable`1 additionalSourceFiles, Action`1 assertAssembly, String expectedExceptionMessage, String testName) in /_/test/EFCore.Specification.Tests/Scaffolding/CompiledModelTestBase.cs:line 2109
--- End of stack trace from previous location ---
----- Inner Stack Trace -----

----- Inner Stack Trace -----
   at Microsoft.EntityFrameworkCore.Scaffolding.CompiledModelTestBase.AssertBaseline(IReadOnlyCollection`1 scaffoldedFiles, String testName) in /_/test/EFCore.Specification.Tests/Scaffolding/CompiledModelTestBase.cs:line 2178

```

**Comment by AndriySvyryd** [comment]
> @AndriySvyryd test is failing for SQL
is this related, or we need to update the base by using the env variable

Most likely that the baseline just needs to be updated

> I can add a boolean forUpdate (deafult: false) to indicate if the sql translator is for update or read
> for example _sqlTranslator.TryBindMember will pass the new parameter to be true, and pass it down to
structuralTypeProjection.BindComplexProperty
to pass it down to SelectExpression.GenerateComplexPropertyShaperExpression
> then we can only return the table mapping inside
> but that leaves us with an issue that the StructuralTypeProjectionExpression containerProjection is still referencing the view not the table , so it will still fail with the old exception (in case of table+view mappings). is that okay ?

@roji what do you think?

**Comment by roji** [comment]
I've answered in https://github.com/dotnet/efcore/pull/36894#discussion_r2454460895 - let's continue discussing there.

**Comment by roji** [comment]
@AndriySvyryd is this fixed by #37072, or are we still missing metadata support for complex types?

**Comment by AndriySvyryd** [comment]
TVF and SqlQuery support is still missing

**Comment by roji** [comment]
Understood. FWIW I'm doing some pretty heavy refactoring to support TPC (#35025), and the hack currently in place to support SqlQuery won't be easy to carry forward. So we'll soon need proper support for it.
