### ISSUE TITLE
Seeking for help for RelationalEventId.PendingModelChangesWarning

### ISSUE THREAD

**Issue by WizzardHub** [dotnet/efcore#34726]
## Ask a question
I'm just here to ask for help and to know if the issue is on my side, known, or even if it's a bug.

### Describing my problem

I was using `dotnet ef` without any issues until I added a string value inside the `User.cs` record. Since then, I've been unable to create the `app.db` database with all its tables.

### What I've tried

* Restarting my computer
* Uninstalling `dotnet` and all its traces on my computer (temp folders, etc.)
* Removing the cache for NuGet
* Adding a new migration (then prompts me to the same exact stack trace)
* Removing all entities (commented in the code provided)
* Suppressing the warning (which results in no tables created)
* Deleting the whole project and cloning it back from git.

### Include provider and version information
EF Core version: 8.0.8 (also tried with latest 9.0.0-rc.1.24451.1)
Database provider: SQLite
Target framework: .NET 9.0.0-rc.1.24451.1
IDE: Rider
Operating system: Windows 11

### Include code
```csharp
public class WebDbContext(DbContextOptions<WebDbContext> options) : DbContext(options)
{
    // public DbSet<User> Users { get; init; }
    // public DbSet<Ban> Bans { get; init; }
    // public DbSet<Configuration> Configurations { get; init; }
    public DbSet<Server> Servers { get; init; }
    
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // modelBuilder.Entity<User>()
        //     .HasOne(u => u.Ban)
        //     .WithOne()
        //     .HasForeignKey<Ban>(b => b.UserId);
        //
        // modelBuilder.Entity<User>()
        //     .HasOne(u => u.Configuration)
        //     .WithOne()
        //     .HasForeignKey<Configuration>(c => c.UserId);
        //
        // modelBuilder.Entity<User>()
        //     .Navigation(u => u.Ban)
        //     .AutoInclude();
        //
        // modelBuilder.Entity<User>()
        //     .Navigation(u => u.Configuration)
        //     .AutoInclude();
        
        base.OnModelCreating(modelBuilder);
    }
}
```

```csharp
public record Server(
    string IpAddress,
    double? ServerLoad = 0.0,
    [property: Key] int? Id = null);
}
```
(If you need more code snippets feel free to ask for them I don't know what to include at this point)

### Include stack traces
```
System.InvalidOperationException: An error was generated for warning 'Microsoft.EntityFrameworkCore.Migrations.PendingModelChangesWarning': The model for context 'WebDbContext' has pending changes. Add a new migration before updating the database. This exception can be suppressed or logged by passing event ID 'RelationalEventId.PendingModelChangesWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
   at Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`1.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, TParam arg)
   at Microsoft.EntityFrameworkCore.Diagnostics.RelationalLoggerExtensions.PendingModelChangesWarning(IDiagnosticsLogger`1 diagnostics, Type contextType)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
An error was generated for warning 'Microsoft.EntityFrameworkCore.Migrations.PendingModelChangesWarning': The model for context 'WebDbContext' has pending changes. Add a new migration before updating the database. This exception can be suppressed or logged by passing event ID 'RelationalEventId.PendingModelChangesWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
```

### Include verbose output
```
PS C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer> dotnet ef migrations add Create --verbose
Using project 'C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj'.
Using startup project 'C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj'.
Writing 'C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\obj\Lizzard.WebServer.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\Lucas\AppData\Local\Temp\tmpxfy1dr.tmp /verbosity:quiet /nologo C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj
Writing 'C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\obj\Lizzard.WebServer.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\Lucas\AppData\Local\Temp\tmpfhn4t0.tmp /verbosity:quiet /nologo C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj
Build started...
dotnet build C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj /verbosity:quiet /nologo /p:PublishAot=false
C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj : warning NU1904: Package 'System.Drawing.Common' 4.7.0 has a known critical severity vulnerability, https://github.com/advisories/GHSA-rxg9-xrhp-64gj
C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj : warning NU1903: Package 'System.Text.Json' 7.0.3 has a known high severity vulnerability, https://github.com/advisories/GHSA-hh2w-p6rv-4g7w       
C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj : warning NU1701: Package 'BCrypt.Net 0.1.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v
4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net9.0'. This package may not be fully compatible with your project.
C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj : warning NU1904: Package 'System.Drawing.Common' 4.7.0 has a known critical severity vulnerability, https://github.com/advisories/GHSA-rxg9-xrhp-64gj
C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj : warning NU1903: Package 'System.Text.Json' 7.0.3 has a known high severity vulnerability, https://github.com/advisories/GHSA-hh2w-p6rv-4g7w       
C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj : warning NU1701: Package 'BCrypt.Net 0.1.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v
4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net9.0'. This package may not be fully compatible with your project.
C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Hubs\CommunicationHub.cs(13,44): warning CS9113: Parameter 'dbContext' is unread. [C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj]

Build succeeded.

C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj : warning NU1904: Package 'System.Drawing.Common' 4.7.0 has a known critical severity vulnerability, https://github.com/advisories/GHSA-rxg9-xrhp-64gj
C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj : warning NU1903: Package 'System.Text.Json' 7.0.3 has a known high severity vulnerability, https://github.com/advisories/GHSA-hh2w-p6rv-4g7w       
C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj : warning NU1701: Package 'BCrypt.Net 0.1.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v
4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net9.0'. This package may not be fully compatible with your project.
C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj : warning NU1904: Package 'System.Drawing.Common' 4.7.0 has a known critical severity vulnerability, https://github.com/advisories/GHSA-rxg9-xrhp-64gj
C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj : warning NU1903: Package 'System.Text.Json' 7.0.3 has a known high severity vulnerability, https://github.com/advisories/GHSA-hh2w-p6rv-4g7w       
C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj : warning NU1701: Package 'BCrypt.Net 0.1.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v
4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net9.0'. This package may not be fully compatible with your project.
C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Hubs\CommunicationHub.cs(13,44): warning CS9113: Parameter 'dbContext' is unread. [C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj]
    7 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.35
Build succeeded.
dotnet exec --depsfile C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\bin\Debug\net9.0\Lizzard.WebServer.deps.json --additionalprobingpath C:\Users\Lucas\.nuget\packages --runtimeconfig C:\Users\Lucas\RiderProjects\Lizza
rd\Lizzard.WebServer\bin\Debug\net9.0\Lizzard.WebServer.runtimeconfig.json C:\Users\Lucas\.dotnet\tools\.store\dotnet-ef\8.0.8\dotnet-ef\8.0.8\tools\net8.0\any\tools\netcoreapp2.0\any\ef.dll migrations add Create --assembly C:\U
sers\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\bin\Debug\net9.0\Lizzard.WebServer.dll --project C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj --startup-assembly C:\Users\Lucas\RiderProjects\
Lizzard\Lizzard.WebServer\bin\Debug\net9.0\Lizzard.WebServer.dll --startup-project C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj --project-dir C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\ --root-namespace Lizzard.WebServer --language C# --framework net9.0 --nullable --working-dir C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer --verbose
Using assembly 'Lizzard.WebServer'.
Using startup assembly 'Lizzard.WebServer'.
Using application base 'C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\bin\Debug\net9.0'.
Using working directory 'C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer'.
Using root namespace 'Lizzard.WebServer'.
Using project directory 'C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\'.
Remaining arguments: .
The Entity Framework tools version '8.0.8' is older than that of the runtime '9.0.0-rc.1.24451.1'. Update the tools for the latest features and bug fixes. See https://aka.ms/AAc1fbw for more information.
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding DbContext classes in the project...
Found DbContext 'WebDbContext'.
Finding application service provider in assembly 'Lizzard.WebServer'...
Finding Microsoft.Extensions.Hosting service provider...
Using environment 'Development'.
Using application service provider from Microsoft.Extensions.Hosting.
Using context 'WebDbContext'.
Finding design-time services referenced by assembly 'Lizzard.WebServer'...
Finding design-time services referenced by assembly 'Lizzard.WebServer'...
No referenced design-time services were found.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.Sqlite'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.Sqlite'.
Finding IDesignTimeServices implementations in assembly 'Lizzard.WebServer'...
No design-time services were found.
Writing migration to 'C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Migrations\20240920180242_Create.cs'.
Writing model snapshot to 'C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Migrations\WebDbContextModelSnapshot.cs'.
Done. To undo this action, use 'ef migrations remove'
PS C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer> dotnet ef database update --verbose      
Using project 'C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj'.
Using startup project 'C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj'.
Writing 'C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\obj\Lizzard.WebServer.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\Lucas\AppData\Local\Temp\tmpfpi5tv.tmp /verbosity:quiet /nologo C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj
Writing 'C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\obj\Lizzard.WebServer.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\Lucas\AppData\Local\Temp\tmpugbcaq.tmp /verbosity:quiet /nologo C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj
Build started...
dotnet build C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj /verbosity:quiet /nologo /p:PublishAot=false
C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj : warning NU1904: Package 'System.Drawing.Common' 4.7.0 has a known critical severity vulnerability, https://github.com/advisories/GHSA-rxg9-xrhp-64gj
C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj : warning NU1903: Package 'System.Text.Json' 7.0.3 has a known high severity vulnerability, https://github.com/advisories/GHSA-hh2w-p6rv-4g7w       
C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj : warning NU1701: Package 'BCrypt.Net 0.1.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v
4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net9.0'. This package may not be fully compatible with your project.
C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj : warning NU1904: Package 'System.Drawing.Common' 4.7.0 has a known critical severity vulnerability, https://github.com/advisories/GHSA-rxg9-xrhp-64gj
C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj : warning NU1903: Package 'System.Text.Json' 7.0.3 has a known high severity vulnerability, https://github.com/advisories/GHSA-hh2w-p6rv-4g7w       
C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj : warning NU1701: Package 'BCrypt.Net 0.1.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v
4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net9.0'. This package may not be fully compatible with your project.
C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Hubs\CommunicationHub.cs(13,44): warning CS9113: Parameter 'dbContext' is unread. [C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj]

Build succeeded.

C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj : warning NU1904: Package 'System.Drawing.Common' 4.7.0 has a known critical severity vulnerability, https://github.com/advisories/GHSA-rxg9-xrhp-64gj
C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj : warning NU1903: Package 'System.Text.Json' 7.0.3 has a known high severity vulnerability, https://github.com/advisories/GHSA-hh2w-p6rv-4g7w       
C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj : warning NU1701: Package 'BCrypt.Net 0.1.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v
4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net9.0'. This package may not be fully compatible with your project.
C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj : warning NU1904: Package 'System.Drawing.Common' 4.7.0 has a known critical severity vulnerability, https://github.com/advisories/GHSA-rxg9-xrhp-64gj
C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj : warning NU1903: Package 'System.Text.Json' 7.0.3 has a known high severity vulnerability, https://github.com/advisories/GHSA-hh2w-p6rv-4g7w       
C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj : warning NU1701: Package 'BCrypt.Net 0.1.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v
4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net9.0'. This package may not be fully compatible with your project.
C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Hubs\CommunicationHub.cs(13,44): warning CS9113: Parameter 'dbContext' is unread. [C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj]
    7 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.32
Build succeeded.
dotnet exec --depsfile C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\bin\Debug\net9.0\Lizzard.WebServer.deps.json --additionalprobingpath C:\Users\Lucas\.nuget\packages --runtimeconfig C:\Users\Lucas\RiderProjects\Lizza
rd\Lizzard.WebServer\bin\Debug\net9.0\Lizzard.WebServer.runtimeconfig.json C:\Users\Lucas\.dotnet\tools\.store\dotnet-ef\8.0.8\dotnet-ef\8.0.8\tools\net8.0\any\tools\netcoreapp2.0\any\ef.dll database update --assembly C:\Users\L
ucas\RiderProjects\Lizzard\Lizzard.WebServer\bin\Debug\net9.0\Lizzard.WebServer.dll --project C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj --startup-assembly C:\Users\Lucas\RiderProjects\Lizzar
d\Lizzard.WebServer\bin\Debug\net9.0\Lizzard.WebServer.dll --startup-project C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\Lizzard.WebServer.csproj --project-dir C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\ --root-namespace Lizzard.WebServer --language C# --framework net9.0 --nullable --working-dir C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer --verbose
Using assembly 'Lizzard.WebServer'.
Using startup assembly 'Lizzard.WebServer'.
Using application base 'C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\bin\Debug\net9.0'.
Using working directory 'C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer'.
Using root namespace 'Lizzard.WebServer'.
Using project directory 'C:\Users\Lucas\RiderProjects\Lizzard\Lizzard.WebServer\'.
Remaining arguments: .
The Entity Framework tools version '8.0.8' is older than that of the runtime '9.0.0-rc.1.24451.1'. Update the tools for the latest features and bug fixes. See https://aka.ms/AAc1fbw for more information.
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding DbContext classes in the project...
Found DbContext 'WebDbContext'.
Finding application service provider in assembly 'Lizzard.WebServer'...
Finding Microsoft.Extensions.Hosting service provider...
Using environment 'Development'.
Using application service provider from Microsoft.Extensions.Hosting.
Using context 'WebDbContext'.
Finding design-time services referenced by assembly 'Lizzard.WebServer'...
Finding design-time services referenced by assembly 'Lizzard.WebServer'...
No referenced design-time services were found.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.Sqlite'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.Sqlite'.
Finding IDesignTimeServices implementations in assembly 'Lizzard.WebServer'...
No design-time services were found.
System.InvalidOperationException: An error was generated for warning 'Microsoft.EntityFrameworkCore.Migrations.PendingModelChangesWarning': The model for context 'WebDbContext' has pending changes. Add a new migration before updating the database. This exception can be suppressed or logged by passing event ID 'RelationalEventId.PendingModelChangesWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
   at Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`1.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, TParam arg)
   at Microsoft.EntityFrameworkCore.Diagnostics.RelationalLoggerExtensions.PendingModelChangesWarning(IDiagnosticsLogger`1 diagnostics, Type contextType)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
An error was generated for warning 'Microsoft.EntityFrameworkCore.Migrations.PendingModelChangesWarning': The model for context 'WebDbContext' has pending changes. Add a new migration before updating the database. This exception can be suppressed or logged by passing event ID 'RelationalEventId.PendingModelChangesWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
```

**Comment by AndriySvyryd** [comment]
@WizzardHub After adding a migration the code you provided no longer throws any exceptions. Can you share a small runnable project that shows the issue after a migration is added?

**Comment by WizzardHub** [comment]
I ended up copy pasting my models & dbcontext to a separate project then making the changes here and it works now. I know it's not a fix but that's enough for me.
