### ISSUE TITLE
SQLite Error 19: 'FOREIGN KEY constraint failed'. exception is thrown in case of foreign key constraint is configured in base class's EntityTypeConfiguration

### ISSUE THREAD

**Issue by fuliii1** [dotnet/efcore#34761]
## File a bug
Hi,

In the attached project can be found a Document base class and 2 descendant classes (Order and Omb). All document types have list of Approval History so this relation is configured in Document base class. The relation based on a compound key (DocumentId and DocumentType). In the program.cs we would like to save an Order with one item in the Approval History. If we not apply the Omb's entity type configuration the SaveChanges works as expected. If the Omb's entity type configuration is applyed we get Microsoft.EntityFrameworkCore.DbUpdateException.

Many thanks

### Include your code
[SqlLiteTest.zip](https://github.com/user-attachments/files/17143825/SqlLiteTest.zip)

### Include stack traces

```
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__112_0(DbContext _, ValueTuple`2 t)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at SqlLiteTest.Program.Main(String[] args) in C:\Git\SqlLiteTest\SqlLiteTest\Program.cs:line 38
```

### Include version information

Microsoft.Data.Sqlite version: 8.0.8
Target framework: (.NET 8.0)
Operating system: Windows 10

**Comment by ajcvickers** [comment]
@fuliii1 The problem here is that both the `Omb` and the `Order` types are configured with required relationships to `ApprovalHistory`:

```
Model: 
  EntityType: ApprovalHistory
    Properties: 
      ID (int) Required PK AfterSave:Throw ValueGenerated.OnAdd
      CreateDate (DateTime) Required
      Decision (Decision?)
      DocumentID (int) Required FK Index
      DocumentType (DocumentType) Required FK Index
    Keys: 
      ID PK
    Foreign keys: 
      ApprovalHistory {'DocumentID', 'DocumentType'} -> Omb {'ID', 'DocumentType'} Required Cascade ToDependent: ApprovalHistory
      ApprovalHistory {'DocumentID', 'DocumentType'} -> Order {'ID', 'DocumentType'} Required Cascade ToDependent: ApprovalHistory
    Indexes: 
      DocumentID, DocumentType
```

This means there is a foreign key constraint in the database such that if `ApprovalHistory.DocumentID` and `ApprovalHistory.DocumentType` are set, then there must be both a corresponding `Order` and a corresponding in `Omb` to satisfy those constraints.

I'm not sure what to suggest to fix this, since from the code I'm not sure what you want the model to look like.

**Comment by fuliii1** [comment]
Hi @ajcvickers,

Thanks for the clarification. 

I would like to use in-memory sql lite for unit testing. I could manage my problem with the following connection string:
`Filename=:memory:;Foreign Keys=False`

I'm working on a migration of legacy project and I cannot change the database schema. In production the database schema doesn't enforce the foreign key constraint. That's why I thought this is a bug in sqllite.

Thanks once more,
