### ISSUE TITLE
EF Core fails to execute simple LINQ to SQL

### ISSUE THREAD

**Issue by FLAMESpl** [dotnet/efcore#34792]
## File a bug

EF Core fails to execute simple LINQ to SQL

### Include your code

I have two models in my db context:

__Restrcition Originator__

```C#
public class RestrictionOriginator
{
    public Guid OriginatorId { get; private set; }
    public Guid TenantId { get; private set; }
    public string DisplayName { get; private set; } = string.Empty;
    public string[] IdentityClientIds { get; private set; } = [];
    public bool IsActive { get; private set; }
    public bool External { get; private set; }
    public bool Predefined { get; private set; }
    public DatabaseAuditMetadata CreationMetadata { get; private set; } = DatabaseAuditMetadata.Empty;
    public DatabaseAuditMetadata UpdateMetadata { get; private set; } = DatabaseAuditMetadata.Empty;
}
```

__Restriction Originator mapping__
```C#
            b.HasIndex(x => new { x.OriginatorId, x.TenantId }).IsUnique();
            b.HasIndex(x => new { x.TenantId, x.Id }).IsUnique();
            b.HasIndex(x => new { x.NormalizedDisplayName, x.TenantId }).IsUnique();
            b.HasIndex(x => x.IdentityClientIds).HasMethod("gin");
            b.HasIndex(x => x.External);
            b.HasIndex(x => x.IsActive);
            b.HasIndex(x => x.Predefined);
            b.RequiredDatabaseAuditMetadata(x => x.CreationMetadata);
            b.OptionalDatabaseAuditMetadata(x => x.UpdateMetadata);
```

__Tenant__
```C#
public class Tenant
{
    public Guid Id { get; private set;}
    public string Code { get; private set; }
    public string Name { get; private set; }
}
```

__Tenant mapping__
```C#
            builder.Property(x => x.Id).ValueGeneratedNever();
            builder.Property(x => x.Code).IsRequired();
```

And I am using following LINQ:

```C#
        await dbContext
            .Set<RestrictionOriginator>()
            .Join(dbContext.Set<Tenant>(), x => x.TenantId, x => x.Id, (originator, tenant) =>
                new RestrictionOriginatorSystemDBView(
                    originator.Id,
                    originator.OriginatorId,
                    originator.TenantId,
                    originator.Version,
                    originator.Predefined,
                    originator.IsActive,
                    originator.External,
                    originator.DisplayName,
                    tenant.Code,
                    tenant.Name))
            .OrderBy(x => x.Id)
            .ToListAsync(cancellationToken);
```

__Restriction Originator System DB View__
```C#
public record RestrictionOriginatorSystemDBView(
    Guid Id,
    Guid OriginatorId,
    Guid TenantId,
    long Version,
    bool Predefined,
    bool IsActive,
    bool External,
    string DisplayName,
    string TenantCode,
    string TenantName) : IEntity
```

### Include stack traces

```
System.InvalidOperationException: The LINQ expression 'DbSet<RestrictionOriginator>()
    .Join(
        inner: DbSet<Tenant>(), 
        outerKeySelector: r => (object)r.TenantId, 
        innerKeySelector: t => (object)t.Id, 
        resultSelector: (r, t) => new TransparentIdentifier<RestrictionOriginator, Tenant>(
            Outer = r, 
            Inner = t
        ))
    .OrderBy(ti => new RestrictionOriginatorSystemDBView(
        ti.Outer.Id, 
        ti.Outer.OriginatorId, 
        ti.Outer.TenantId, 
        ti.Outer.Version, 
        ti.Outer.Predefined, 
        ti.Outer.IsActive, 
        ti.Outer.External, 
        ti.Outer.DisplayName, 
        ti.Inner.Code, 
        ti.Inner.Name
    ).Id)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at AboveCloud.RateManager.Restrictions.Originators.Views.System.RestrictionOriginatorSystemQueryHandler.HandleAsync(GetRestrictionOriginatorsInSystem query, CancellationToken cancellationToken) in D:\Shiji\backends\rate-manager\AboveCloud\src\AboveCloud.RateManager\Restrictions\Originators\Views\System\RestrictionOriginatorSystemQueryHandler.cs:line 23
   at AboveCloud.Infrastructure.Messaging.LocalCommandQueryDispatching.Pipelines.QueryPipelineItemHandlerAdapter`2.HandleAsync[TQueryResponse](IQuery`1 query, CancellationToken cancellationToken) in /backend-infrastructure/AboveCloud/src/AboveCloud.Infrastructure/Messaging/LocalCommandQueryDispatching/Pipelines/QueryPipelineItemHandlerAdapter.cs:line 14
   at AboveCloud.Shared.Ari.Infrastructure.Messaging.Queries.Decorators.QueryHandlerPipelineItemWrapper`2.HandleAsync(TQuery query, CancellationToken cancellationToken) in /_/AboveCloud/src/AboveCloud.Shared.Ari.Infrastructure/Messaging/Queries/Decorators/QueryHandlerPipelineItemWrapper.cs:line 19
   at AboveCloud.RateManager.Infrastructure.Messaging.RedirectToGlobalRegion.RedirectToGlobalRegionQueryMarkedWithAttributeDecorator`2.HandleAsync(TQuery query, CancellationToken cancellationToken) in D:\Shiji\backends\rate-manager\AboveCloud\src\AboveCloud.RateManager\Infrastructure\Messaging\RedirectToGlobalRegion\RedirectToGlobalRegionQueryMarkedWithAttributeDecorator.cs:line 20
   at AboveCloud.Shared.Ari.Infrastructure.Messaging.Queries.Decorators.QueryHandlerDecoratorsPipelineItem`2.HandleAsync(TQuery query, CancellationToken cancellationToken) in /_/AboveCloud/src/AboveCloud.Shared.Ari.Infrastructure/Messaging/Queries/Decorators/QueryHandlerDecoratorsPipelineItem.cs:line 19
   at AboveCloud.Infrastructure.Messaging.LocalCommandQueryDispatching.Pipelines.QueryPipelineItem`2.HandleAsync[TPipelineItemResponse](IQuery`1 query, CancellationToken cancellationToken) in /backend-infrastructure/AboveCloud/src/AboveCloud.Infrastructure/Messaging/LocalCommandQueryDispatching/Pipelines/QueryPipelineItem.cs:line 37
   at AboveCloud.Shared.Ari.Infrastructure.Logging.ObsoletedFeatureUsage.PipelineItems.ObsoletedQueryLoggingPipelineItem`2.HandleAsync(TQuery query, CancellationToken cancellationToken) in /_/AboveCloud/src/AboveCloud.Shared.Ari.Infrastructure/Logging/ObsoletedFeatureUsage/PipelineItems/ObsoletedQueryLoggingPipelineItem.cs:line 24
   at AboveCloud.Infrastructure.Messaging.LocalCommandQueryDispatching.Pipelines.QueryPipelineItem`2.HandleAsync[TPipelineItemResponse](IQuery`1 query, CancellationToken cancellationToken) in /backend-infrastructure/AboveCloud/src/AboveCloud.Infrastructure/Messaging/LocalCommandQueryDispatching/Pipelines/QueryPipelineItem.cs:line 37
   at AboveCloud.RateManager.Infrastructure.Localization.LocalizedQueryPipelineItem`2.HandleAsync(TQuery query, CancellationToken cancellationToken) in D:\Shiji\backends\rate-manager\AboveCloud\src\AboveCloud.RateManager\Infrastructure\Localization\LocalizedQueryPipelineItem.cs:line 44
   at AboveCloud.Infrastructure.Messaging.LocalCommandQueryDispatching.Pipelines.QueryPipelineItem`2.HandleAsync[TPipelineItemResponse](IQuery`1 query, CancellationToken cancellationToken) in /backend-infrastructure/AboveCloud/src/AboveCloud.Infrastructure/Messaging/LocalCommandQueryDispatching/Pipelines/QueryPipelineItem.cs:line 37
   at AboveCloud.Infrastructure.Messaging.LocalCommandQueryDispatching.Pipelines.QueryPipelineItem`2.HandleAsync[TPipelineItemResponse](IQuery`1 query, CancellationToken cancellationToken) in /backend-infrastructure/AboveCloud/src/AboveCloud.Infrastructure/Messaging/LocalCommandQueryDispatching/Pipelines/QueryPipelineItem.cs:line 37
   at AboveCloud.Infrastructure.Messaging.LocalCommandQueryDispatching.Pipelines.QueryPipelineItems.ValidationQueryPipelineItem`2.HandleAsync(TQuery query, CancellationToken cancellationToken) in /backend-infrastructure/AboveCloud/src/AboveCloud.Infrastructure/Messaging/LocalCommandQueryDispatching/Pipelines/QueryPipelineItems/ValidationQueryPipelineItem.cs:line 47
   at AboveCloud.Infrastructure.Messaging.LocalCommandQueryDispatching.Pipelines.QueryPipelineItem`2.HandleAsync[TPipelineItemResponse](IQuery`1 query, CancellationToken cancellationToken) in /backend-infrastructure/AboveCloud/src/AboveCloud.Infrastructure/Messaging/LocalCommandQueryDispatching/Pipelines/QueryPipelineItem.cs:line 37
   at AboveCloud.Infrastructure.Messaging.LocalCommandQueryDispatching.Pipelines.QueryPipelineItems.FeatureToggleQueryPipelineItem`2.HandleAsync(TQuery query, CancellationToken cancellationToken) in /backend-infrastructure/AboveCloud/src/AboveCloud.Infrastructure/Messaging/LocalCommandQueryDispatching/Pipelines/QueryPipelineItems/FeatureToggleQueryPipelineItem.cs:line 21
   at AboveCloud.Infrastructure.Messaging.LocalCommandQueryDispatching.Pipelines.QueryPipelineItem`2.HandleAsync[TPipelineItemResponse](IQuery`1 query, CancellationToken cancellationToken) in /backend-infrastructure/AboveCloud/src/AboveCloud.Infrastructure/Messaging/LocalCommandQueryDispatching/Pipelines/QueryPipelineItem.cs:line 37
   at AboveCloud.Infrastructure.MultiRegion.GlobalContextMicroservice.EntityNotFoundGlobalRedirectQueryPipelineItem.HandleAsync[TQueryResponse](IQuery`1 query, CancellationToken cancellationToken) in /backend-infrastructure/AboveCloud/src/AboveCloud.Infrastructure/MultiRegion/GlobalContextMicroservice/EntityNotFoundGlobalRedirectQueryPipelineItem.cs:line 41
   at AboveCloud.Infrastructure.Messaging.LocalCommandQueryDispatching.Pipelines.QueryPipelineItems.AuthorizationQueryPipelineItem`2.HandleAsync(TQuery query, CancellationToken cancellationToken) in /backend-infrastructure/AboveCloud/src/AboveCloud.Infrastructure/Messaging/LocalCommandQueryDispatching/Pipelines/QueryPipelineItems/AuthorizationQueryPipelineItem.cs:line 36
   at AboveCloud.Infrastructure.Messaging.LocalCommandQueryDispatching.Pipelines.QueryPipelineItem`2.HandleAsync[TPipelineItemResponse](IQuery`1 query, CancellationToken cancellationToken) in /backend-infrastructure/AboveCloud/src/AboveCloud.Infrastructure/Messaging/LocalCommandQueryDispatching/Pipelines/QueryPipelineItem.cs:line 37
   at AboveCloud.Infrastructure.MultiRegion.TenantRegions.TenantRegionValidationQueryPipelineItem.HandleAsync[TQueryResponse](IQuery`1 query, CancellationToken cancellationToken) in /backend-infrastructure/AboveCloud/src/AboveCloud.Infrastructure/MultiRegion/TenantRegions/TenantRegionValidationQueryPipelineItem.cs:line 19
   at AboveCloud.Infrastructure.Messaging.LocalCommandQueryDispatching.Pipelines.QueryPipelineItems.AuditDataAccessQueryPipelineItem`2.HandleAsync(TQuery query, CancellationToken cancellationToken) in /backend-infrastructure/AboveCloud/src/AboveCloud.Infrastructure/Messaging/LocalCommandQueryDispatching/Pipelines/QueryPipelineItems/AuditDataAccessQueryPipelineItem.cs:line 37
   at AboveCloud.Infrastructure.Messaging.LocalCommandQueryDispatching.Pipelines.QueryPipelineItem`2.HandleAsync[TPipelineItemResponse](IQuery`1 query, CancellationToken cancellationToken) in /backend-infrastructure/AboveCloud/src/AboveCloud.Infrastructure/Messaging/LocalCommandQueryDispatching/Pipelines/QueryPipelineItem.cs:line 37
   at AboveCloud.Infrastructure.Messaging.LocalCommandQueryDispatching.Pipelines.QueryPipelineItems.MetricsQueryPipelineItem.HandleAsync[TQueryResponse](IQuery`1 query, CancellationToken cancellationToken) in /backend-infrastructure/AboveCloud/src/AboveCloud.Infrastructure/Messaging/LocalCommandQueryDispatching/Pipelines/QueryPipelineItems/MetricsQueryPipelineItem.cs:line 24
   at AboveCloud.Infrastructure.Messaging.LocalCommandQueryDispatching.Pipelines.QueryPipelineItems.LogContextQueryPipelineItem.HandleAsync[TResponse](IQuery`1 query, CancellationToken cancellationToken) in /backend-infrastructure/AboveCloud/src/AboveCloud.Infrastructure/Messaging/LocalCommandQueryDispatching/Pipelines/QueryPipelineItems/LogContextQueryPipelineItem.cs:line 38
   at AboveCloud.Infrastructure.Messaging.LocalCommandQueryDispatching.RetryingCommandQueryDispatcher.SendAsync[TResponse](IQuery`1 query, CancellationToken cancellationToken) in /backend-infrastructure/AboveCloud/src/AboveCloud.Infrastructure/Messaging/LocalCommandQueryDispatching/RetryingCommandQueryDispatcher.cs:line 41
   at AboveCloud.Infrastructure.Messaging.LocalCommandQueryDispatching.RetryingCommandQueryDispatcher.SendAsync[TResponse](IQuery`1 query, CancellationToken cancellationToken) in /backend-infrastructure/AboveCloud/src/AboveCloud.Infrastructure/Messaging/LocalCommandQueryDispatching/RetryingCommandQueryDispatcher.cs:line 41
   at AboveCloud.RateManager.Infrastructure.Messaging.LogEnrichingCommandQueryDispatcher.EnrichLogs[T](Func`1 callback) in D:\Shiji\backends\rate-manager\AboveCloud\src\AboveCloud.RateManager\Infrastructure\Messaging\LogEnrichingCommandQueryDispatcher.cs:line 42
   at AboveCloud.RateManager.Infrastructure.Messaging.LogEnrichingCommandQueryDispatcher.SendAsync[TResponse](IQuery`1 query, CancellationToken cancellationToken) in D:\Shiji\backends\rate-manager\AboveCloud\src\AboveCloud.RateManager\Infrastructure\Messaging\LogEnrichingCommandQueryDispatcher.cs:line 26
   at AboveCloud.RateManager.WebApi.Maintenance.Restrictions.RestrictionOriginatorsMaintenanceController.Get(GetRestrictionOriginatorsInSystem query, CancellationToken cancellationToken) in D:\Shiji\backends\rate-manager\AboveCloud\src\AboveCloud.RateManager.WebApi\Maintenance\Restrictions\RestrictionOriginatorsMaintenanceController.cs:line 24
   at lambda_method2489(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at AboveCloud.Infrastructure.WebApi.Security.CallContextMiddleware.Invoke(HttpContext httpContext, CallContext callContext) in /backend-infrastructure/AboveCloud/src/AboveCloud.Infrastructure.WebApi/Security/CallContextMiddleware.cs:line 74
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at AboveCloud.Infrastructure.WebApi.Versioning.RewriteToDefaultVersionUrlMiddleware.Invoke(HttpContext context) in /backend-infrastructure/AboveCloud/src/AboveCloud.Infrastructure.WebApi/Versioning/RewriteToDefaultVersionUrlMiddleware.cs:line 52
   at AboveCloud.Infrastructure.WebApi.ExceptionHandling.ExceptionHandlingMiddleware.Invoke(HttpContext context, CallContext callContext) in /backend-infrastructure/AboveCloud/src/AboveCloud.Infrastructure.WebApi/ExceptionHandling/ExceptionHandlingMiddleware.cs:line 46
```

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.PostgreSQL (8.0.4)
Target framework: NET 8.0 (SDK 8.0.401)
Operating system:
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19045 N/A Build 19045
IDE: JetBrains Rider 2024.1.4

**Comment by maumar** [comment]
related: https://github.com/dotnet/efcore/issues/34562

**Comment by Emmanuelcyanide82** [comment]
> dupe of [#34562](https://github.com/dotnet/efcore/issues/34562)





https://pysnmp3.github.io/msbuild/
