### ISSUE TITLE
System.Data.SqlClient.SqlException (0x80131904)

### ISSUE THREAD

**Issue by wangkanai** [dotnet/efcore#3485]
Firewall off and Sql Instance see in SQL Server Object Explorer
But i get this in when trying to update the database.
Using entityframework 1.0.0-beta8
![sql-server-object-explorer](https://cloud.githubusercontent.com/assets/10666633/10613948/d2fd649a-7781-11e5-81a2-e4089a748697.png)

```
PM> dnx ef database update
Using context 'ComplexContext'.
Using database 'SandboxComplex' on server '(localdb)\\MSSQLLocalDB'.
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was 
not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 50 - Local Database 
Runtime error occurred. Specified LocalDB instance name is invalid.
)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean t
rustServerCert, Boolean integratedSecurity, Boolean withFailover, SqlAuthenticationMethod authType)
   at System.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutT
imer timeout, Boolean withFailover)
   at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlCon
nectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, Secure
String newSecurePassword, Boolean redirectedUserInstance)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, St
ring newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, 
String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbCon
nection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, 
DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection,
 DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& conne
ction)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal
 oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbCon
nectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.Data.Entity.Storage.RelationalConnection.Open()
   at Microsoft.Data.Entity.Storage.Internal.SqlServerDatabaseCreator.Exists(Boolean retryOnNotExists)
   at Microsoft.Data.Entity.Migrations.HistoryRepository.Exists()
   at Microsoft.Data.Entity.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.Data.Entity.Design.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineUtilsExtensions.<>c__DisplayClass0_0.<OnExecute>b__0()
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Data.Entity.Commands.Program.Main(String[] args)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:-1983577829,State:0,Class:20
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is 
correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 50 - Local Database Runtime error occurred. Specified LocalDB instanc
e name is invalid.
)
```

**Comment by rowanmiller** [comment]
It's unlikely that this is something specific to migrations. Have you tried connecting to the instance from code using the same connection string that you context is setup to use?

**Comment by wangkanai** [comment]
![runtime-error-ef7](https://cloud.githubusercontent.com/assets/10666633/10614585/45200426-7785-11e5-98d1-0576b209138b.png)
Yap, its has the same error

**Comment by wangkanai** [comment]
```
    public class ComplexContext : DbContext
    {
        public DbSet<Person> Persons { get; set; } 
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\\MSSQLLocalDB;Database=SandboxComplex;Trusted_Connection=True;Integrated Security=true;");
        }
    }
```

**Comment by wangkanai** [comment]
![list-of-database-localdb](https://cloud.githubusercontent.com/assets/10666633/10614880/d8310746-7786-11e5-8ce2-619d1be6a0fc.png)
![sql-server-localdb-found](https://cloud.githubusercontent.com/assets/10666633/10614881/d83373aa-7786-11e5-924a-3bc059951d9c.png)
![test-connection-succeeded](https://cloud.githubusercontent.com/assets/10666633/10614914/0b670e9e-7787-11e5-9d1e-8d31e1a1e7b0.png)

**Comment by rowanmiller** [comment]
It's because you have double escaped your connection string in code. You've escaped the `\` in `(localdb)\\MSSQLLocalDB;Database` but you've also used an `@` before the string.

```@"Server=(localdb)\\MSSQLLocalDB;Database=SandboxComplex;Trusted_Connection=True;Integrated Security=true;"```

so rather than escaping it is trying to connect to `(localdb)\\MSSQLLocalDB;Database` (with the two slashes).

**Comment by wangkanai** [comment]
Wow, thank you very much. its was just under the nose :smile:
