### ISSUE TITLE
JSON serialised null values cause JsonCollectionReaderWriter to throw and conversion is not applied

### ISSUE THREAD

**Issue by mathew-tolj** [dotnet/efcore#34881]
I am attempting to map an existing database to test out the JSON column functionality that was added in version 7.0. For the most part it has been going well but I hit an issue when I reached a table that has been serialising a list into JSON and storing the result in an NVARCHAR(MAX) column.

```csharp
public IList<string>? DisplayPath { get; set; }
```

```sql
[DisplayPath] [nvarchar](max) NULL
```

The issue that I am hitting here is that the existing data appears to have serialised null values to a JSON string e.g. "null". I believe this does deserialise back to a null value but this cause the `JsonCollectionReaderWriter` to throw an exception:

```
System.InvalidOperationException: Invalid token type: 'Null'.
    at Microsoft.EntityFrameworkCore.Storage.Json.JsonCollectionReaderWriter`3.FromJsonTyped(Utf8JsonReaderManager& manager, Object existingObject)
    at Microsoft.EntityFrameworkCore.Storage.Json.JsonValueReaderWriter`1.FromJson(Utf8JsonReaderManager& manager, Object existingObject)
    at Microsoft.EntityFrameworkCore.Storage.Json.JsonValueReaderWriter.FromJsonString(String json, Object existingObject)
    at lambda_method11(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
    at System.Text.Json.Serialization.Converters.IAsyncEnumerableOfTConverter`2.OnWriteResume(Utf8JsonWriter writer, TAsyncEnumerable value, JsonSerializerOptions options, WriteStack& state)
    at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
    at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.SerializeAsync(Stream utf8Json, T rootValue, CancellationToken cancellationToken, Object rootValueBoxed)
    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.SerializeAsync(Stream utf8Json, T rootValue, CancellationToken cancellationToken, Object rootValueBoxed)
    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.SerializeAsync(Stream utf8Json, T rootValue, CancellationToken cancellationToken, Object rootValueBoxed)
    at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

From looking at the code I can only assume the exception is coming from here: https://github.com/dotnet/efcore/blob/4315fa43c9573671f8f5be21497d59f9c99cd829/src/EFCore/Storage/Json/JsonCollectionReaderWriter.cs#L79-L80

In my efforts to work around the issue, I may have stumbled across another potential issue. I added a conversion to the property so that it should no longer be trying to convert the JSON.

```csharp
builder
    .Property(definition => definition.DisplayPath)
    .HasConversion(
        value => "[]",
        value => new List<string>());
```

However, even after adding the conversion, I am still receiving the same error which means that the `JsonCollectionReaderWriter` is still being called before any conversion takes place. Now this might just be that my expectations for the order in which things happen is incorrect but I would have thought if you had a conversion that it would take place before or instead of the standard behaviour.

I am not sure of any potential workarounds for me to try next. I could inherit from `JsonCollectionReaderWriter` and handle the null token in there but I am uncertain how I would configure the new class to be used by Entity Framework Core.

EF Core version: 8.0.10
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.11.5

**Comment by maumar** [comment]
I tried to repro using the following:

step 1 - "legacy" primitive collection:

```
    [ConditionalFact]
    public async Task Repro34881()
    {
        using var ctx = new MyContext();
        await ctx.Database.EnsureDeletedAsync();
        await ctx.Database.EnsureCreatedAsync();

        var entity = new MyEntity { Name = "foo", DisplayPath = ["a", null, "b"] };
        ctx.MyEntities.Add(entity);
        await ctx.SaveChangesAsync();
    }


    public class MyContext : DbContext
    {
        public DbSet<MyEntity> MyEntities { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
            => modelBuilder.Entity<MyEntity>().Property(definition => definition.DisplayPath).HasConversion(
                new ValueConverter<IList<string>, string>(
                    v => JsonSerializer.Serialize(v, JsonSerializerOptions.Default),
                    v => JsonSerializer.Deserialize<IList<string>>(v, JsonSerializerOptions.Default)));


        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Repro;Trusted_Connection=True;MultipleActiveResultSets=true")
                .LogTo(Console.WriteLine, LogLevel.Information)
                .EnableSensitiveDataLogging();
        }
    }

    public class MyEntity
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public IList<string> DisplayPath { get; set; }
    }
```

which generates the following sql:

```sql
INSERT INTO [MyEntities] ([DisplayPath], [Name])
OUTPUT INSERTED.[Id]
VALUES (@p0, @p1);
',N'@p0 nvarchar(4000),@p1 nvarchar(4000)',@p0=N'["a",null,"b"]',@p1=N'foo'
```


step 2 - new primitive collection

```cs
    [ConditionalFact]
    public async Task Repro34881()
    {
        using var ctx = new MyContext();
        var query = await ctx.MyEntities.ToListAsync();
    }

    public class MyContext : DbContext
    {
        public DbSet<MyEntity> MyEntities { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Repro;Trusted_Connection=True;MultipleActiveResultSets=true")
                .LogTo(Console.WriteLine, LogLevel.Information)
                .EnableSensitiveDataLogging();
        }
    }

    public class MyEntity
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<string> DisplayPath { get; set; }
    }
```

but I'm not seeing the issue. @mathew-tolj please provide standalone repro that shows the problem. Alternatively modify the code above so that it matches what you are using

**Comment by maumar** [comment]
wrt converter problem, you can try the approach suggested here: https://github.com/dotnet/efcore/issues/33688#issuecomment-2100624746

**Comment by mathew-tolj** [comment]
Entity Framework creates the data with no issue. The reason I am having to jump through these hoops is because the data was already created with a less ideal method and has essentially added some serialised null values (`JsonSerializer.Serialize<string?>(null)`) to the database. Building upon your code you should be able to reproduce the this issue by running the test in step 2 after inserting the following data into the database:

```sql
INSERT INTO [MyEntities] ([DisplayPath], [Name])
VALUES (N'null', N'foo');
```

Interestingly enough, the second issue I experienced with the exception still throwing even with the conversion in place is not occurring when I use your test so I am going to investigate further and try to come up with a failing test that demonstrates it.

**Comment by mathew-tolj** [comment]
Upon further investigation, the second issue with the exception still throwing even with the conversion in place appears to be unrelated to Entity Framework. I was using the Automapper `ProjectTo` method to project my entities to DTOs and it appears that something goes awry if I map from an `IList` to an `IEnumerable` or `ICollecton`. If I map from an `IList` to another `IList` it does work as expected. I think I will investigate other alternatives for projection.

**Comment by maumar** [comment]
Thanks @mathew-tolj I'm able to reproduce it now. I'd say this behavior is by design. The JSON in the database does not correspond to the expected schema (expecting array, got scalar). When we parse JSON string and expect the array the only tokens we allow are null or array start. When it comes to workarounds, unfortunately EF doesn't provide extensibility to swap/customize Json*ReaderWriter, but rather they are hard-coded (https://github.com/dotnet/efcore/blob/e699666f3a3572e298369525e497759fc7c46498/src/EFCore/Storage/TypeMappingSourceBase.cs#L166)

Wrt workarounds, the most straight forward option is probably bulk-updating the database and replacing all the 'null' values with actual null. Unless other parts of the code depend on these values and are hard to change. If that's the case I'd say you need to fall back to the old way we handled primitive arrays, i.e. value converters. 

Something like this:
```cs
        protected override void OnModelCreating(ModelBuilder modelBuilder)
            => modelBuilder.Entity<MyEntity>().Property(definition => definition.DisplayPath).HasConversion(
                new ValueConverter<IList<string>, string>(
                    v => JsonSerializer.Serialize(v, JsonSerializerOptions.Default),
                    v => v == "null" ? null : JsonSerializer.Deserialize<IList<string>>(v, JsonSerializerOptions.Default)));
```

But drawback here is that you lose all the querying capabilities we added in 8

**Comment by maumar** [comment]
@mathew-tolj actually I was wrong. 'null' is a valid json representation for null and we should support this. Re-opening the issue

**Comment by maumar** [comment]
@ajcvickers it actually is a valid JSON. Our utf8jsonreader reads `"null"` as `JsonTokenType.Null`.  https://github.com/dotnet/efcore/issues/34960#issuecomment-2434266282 has some more context and the discussion around it. (same problem but for entity reference / entity collection)

**Comment by ajcvickers** [comment]
@maumar What's the status of this issue?

**Comment by maumar** [comment]
spoke with @ajcvickers about this and this is the correct approach - primitive collection is mapped as JSON and "null" represents a valid well formed JSON which resolved to JsonTokenType.Null. However, the case for primitive collection is a bit trickier than for entity reference/collection. We use value converters to build a resulting object from the json. Converters don't handle nulls so what we normally do is check that the value is not null (dbnull) and only then call into the converter code. Here it's not enough as the non-null value ("null") results in a null -value JSON. To do this properly we need to add another check, basically use json reader to peek into the first token, if its  JsonTokenType.Null - we return null and only if its something else we call into the converter code.

Moving to backlog for now as it's not a trivial change and the value is not very high. As mentioned above, when EF is used end-to-end this issue never happens, as we always generate null to represent null-value JSON, rather than "null".

**Comment by AndriySvyryd** [comment]
Fixed in 6a2d7a8
