### ISSUE TITLE
EF9 Cosmos RC2: .Where cannot be used with Enum conversion anymore

### ISSUE THREAD

**Issue by mwiedemeyer** [dotnet/efcore#34911]
After updating from EF8 to EF9 (Microsoft.EntityFrameworkCore.Cosmos 9.0.0-rc.2.24474.1) the following code is no longer working

### Code:

Entire sample console app here: **https://github.com/mwiedemeyer/EF9EnumConversionBug/blob/main/ConsoleApp1/Program.cs**

```
// setup 
// (...)
memberModel.Property(p => p.MemberType).HasConversion(v => v.ToString(), v => Enum.Parse<MemberType>(v, true));

// this is working as expected. The conversion from string to enum is working
var allMembers = await dbContext.Members.ToListAsync();
```

```
// This is not working. The conversion from enum to string is not working
// EXCEPTION: 'Invalid cast from 'System.Int32' to 'MemberType'
var adminMembers = await dbContext.Members.Where(p => p.MemberType == MemberType.Admin).ToListAsync();
```

### Stack Trace

```
System.InvalidCastException: 'Invalid cast from 'System.Int32' to 'MemberType'.'
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.Sanitize[T](Object value)
   at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.<>c__DisplayClass7_0`2.<SanitizeConverter>b__1(Object v)
   at Microsoft.EntityFrameworkCore.Internal.PartitionKeyBuilderExtensions.Add(PartitionKeyBuilder builder, Object value, IProperty property)
   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosShapedQueryCompilingExpressionVisitor.GeneratePartitionKey(IEntityType rootEntityType, List`1 partitionKeyPropertyValues, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1..ctor(CosmosQueryContext cosmosQueryContext, ISqlExpressionFactory sqlExpressionFactory, IQuerySqlGeneratorFactory querySqlGeneratorFactory, SelectExpression selectExpression, Func`3 shaper, Type contextType, IEntityType rootEntityType, List`1 partitionKeyPropertyValues, Boolean standAloneStateManager, Boolean threadSafetyChecksEnabled)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteCore[TResult](Expression query, Boolean async, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__67`1.MoveNext()
   at Program.<<Main>$>d__0.MoveNext() in X:\Dev\ConsoleApp1\ConsoleApp1\Program.cs:line 36
```

EF Core version: 9.0.0-rc.2.24474.1
Database provider: Microsoft.EntityFrameworkCore.Cosmos
Target framework: .NET 9 RC2

**Comment by roji** [comment]
Confirmed regresion in 9.0.

**Comment by roji** [comment]
Thanks for flagging this @mwiedemeyer; FYI the bug is specific to partition key properties only (regular enum properties work fine).

**Comment by roji** [comment]
Absolutely - although this is very late in the release, we'll do our best to fix this for 9.0.0.
