### ISSUE TITLE
dotnet-ef - Could not load file or assembly 'ef, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

### ISSUE THREAD

**Issue by deinok** [dotnet/efcore#35084]
Project with:
`<TargetFrameworks>net48;net8.0;net9.0</TargetFrameworks>`

Using:
dotnet-ef v9.0.0

And running the following command:
`dotnet ef migrations add Example`

Causes the following error:
```
Build started...
Build succeeded.
System.IO.FileNotFoundException: Could not load file or assembly 'ef, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
File name: 'ef, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.Runtime.Serialization.FormatterServices.LoadAssemblyFromString(String assemblyName)
   at System.Reflection.MemberInfoSerializationHolder..ctor(SerializationInfo info, StreamingContext context)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at Microsoft.EntityFrameworkCore.Tools.AppDomainOperationExecutor..ctor(String assembly, String startupAssembly, String project, String projectDir, String dataDirectory, String rootNamespace, String language, Boolean nullable, String[] remainingArguments, IOperationReportHandler reportHandler)
   at Microsoft.EntityFrameworkCore.Tools.Commands.ProjectCommandBase.CreateExecutor(String[] remainingArguments)
   at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsAddCommand.Execute(String[] args)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Could not load file or assembly 'ef, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
```

**Comment by roji** [comment]
`net48` represents the old .NET Framework, but EF Core 9.0 is only compatible with .NET 8 or above (so does not work with .NET Framework). What's your intention when trying to execute the `dotnet ef` tool on a project that isn't compatible with EF 9?

**Comment by deinok** [comment]
@roji We have a mix of EntityFramework and EntityFrameworkCore. Right now EFCore is the one that rules, we are doing Code First with it and until 9.0 the comand was generating code for EFCore 3.X as I have something like this:

```
<ItemGroup Condition="$(TargetFramework) == 'net481'">
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.32" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.32" />
</ItemGroup>
<ItemGroup Condition="$(TargetFramework) == 'net8.0'">
    <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
</ItemGroup>
<ItemGroup Condition="$(TargetFramework) == 'net9.0'">
    <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
</ItemGroup>
``` 

The sole purpose of net481 and EF3.1.32 is to be able to update the .edmx of the old EntityFramework. If y remove the net481, VS refuses to be update it. In fact, that edmx is the sole issue of why we cant remove completly the .NET Framework stack.

**Comment by chrisw-cr** [comment]
We use the same solution and are receiving the same error. We scaffold separate efcore3 and efcore8 contexts. The previous efcore designers were able to scaffold for old versions of efcore.

Before someone offers a resolution to use ef6 edmx with .Net Core (i.e. 8.0/9.0), We do have workarounds to use ef6 edmx contexts with .Net Core. We are forced to keep net48 because of several other 3rd party references that do not offer .Net Core solutions.

**Comment by ajcvickers** [comment]
@chrisw-cr @deinok [EF Core 3.1 is out-of-support](https://learn.microsoft.com/en-us/ef/core/what-is-new/). There is no supported way to use EF9 with .NET Framework.

**Comment by chrisw-cr** [comment]
Thank you for the update.

To be clear, the desire was not to use Ef9 with .NET Framework. Instead, it is to scaffold with EF Core 3.1 compatibility, as the un-supported EF Core 3.1 works with .NET Framework.

Our solution was to install the proper ef tools version prior to scaffolding, allowing for tool downgrade. We couldn't figure out how to install 2 versions of a tool side by side.

`dotnet tool update dotnet-ef --local --version $efToolsVersion --allow-downgrade --ignore-failed-sources --interactive`

Where $efToolsVersion is `9.*` or `8.*` (the 8.* tools can scaffold for 3.1).
