### ISSUE TITLE
Generates Incorrect UPDATE Instead of INSERT SQL for New Entity in One-to-Many Relationship

### ISSUE THREAD

**Issue by shyamal890** [dotnet/efcore#35090]
### Include your code

```C#
public class View
{
    public Guid view_id { get; set; }

    [MaxLength(50)]
    public string name { get; set; } = null!;

    public DateTime created_at { get; set; } = DateTime.UtcNow;
    public DateTime modified_at { get; set; } = DateTime.UtcNow;

    public virtual ICollection<ViewColumn> Columns { get; set; } = new List<ViewColumn>();
}
public class ViewColumn
{
    public Guid column_id { get; set; }
    public Guid view_id { get; set; }
    public string type { get; set; } = ViewColumnTypeEnum.name;

    public virtual View View { get; set; } = null!;
}

//This is how the relationship is established in DBContext
modelBuilder.Entity<ViewColumn>(entity =>
{
    entity.HasKey(e => e.column_id);

    entity.ToTable("ViewColumn");

    entity.HasOne(d => d.View)
       .WithMany(p => p.Columns)
       .HasForeignKey(d => d.view_id);
});

When I run the following code
var rel_view = db.Views
    .Include(x=> x.Columns)
    .FirstOrDefault(x => x.view_id = view_id);

var new_column= new ViewColumn()
{
    column_id = Guid.NewGuid(),
    type = ViewColumnTypeEnum.custom_field,
};
rel_view.Columns.Add(new_column);
await db.SaveChangesAsync();

EF Core generates the following SQL statement:
UPDATE [ViewColumn] SET [type] = @p1, [view_id] = @p2
      OUTPUT 1
      WHERE [column_id] = @p6;

Where as it should have created an INSERT SQL statement
```

### Include stack traces

Error message:
```
The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See https://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
```

```
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.<ThrowAggregateUpdateConcurrencyExceptionAsync>d__10.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.<ConsumeResultSetWithRowsAffectedOnlyAsync>d__6.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.<ConsumeAsync>d__2.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__50.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__50.MoveNext()
   at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerModificationCommandBatch.<ExecuteAsync>d__15.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__9.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__9.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__9.MoveNext()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__111.MoveNext()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__115.MoveNext()
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__63.MoveNext()
   at SmartTask.Data.Services.SomoneService.<CreateRelevantViews>d__3.MoveNext() in ....
```

### Include verbose output
NA

### Include provider and version information

EF Core version: 9.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 9.0 (Also faced the same issue in 8.0)
Operating system: Windows 10
IDE: (e.g. Visual Studio 2022 17.12)

**Comment by roji** [comment]
You probably need to read [this section of the docs](https://learn.microsoft.com/en-us/ef/core/change-tracking/explicit-tracking#generated-key-values), which contains the following:

> As mentioned above, integer and GUID [key properties](https://learn.microsoft.com/en-us/ef/core/modeling/keys) are configured to use [automatically generated key values](https://learn.microsoft.com/en-us/ef/core/modeling/generated-properties) by default. This means that the application must not set any key value explicitly.

If you remove `column_id = Guid.NewGuid()` from your ViewColumn initialization, everything should work (EF by default already generates a Guid for you).

/cc @ajcvickers

**Comment by shyamal890** [comment]
Thanks @roji for pointing me to the reference doc. 

Have one doubt though. Incase of PK being generated in the frontend and then passed on to the backend, would we have to explicitly mark the entity as `EntityState.Added`? 

Am asking this because incase of direct insert into `db.ViewColumns.Add` we don't get this error. So there seems to be a discrepancy between direct insert in to the table and insert through reference.

**Comment by kevcoffey** [comment]
@ajcvickers There seems to be a behaviour change between version 8.0.11 and 9.0.0 in this regard?  We have issue with 9.0.0 that we didn't have with 8.0.11.

**Comment by kevcoffey** [comment]
`using Microsoft.EntityFrameworkCore;

var optionsBuilder = new DbContextOptionsBuilder<DatabaseContext>()
    .UseSqlServer(
        "...",
        options => options
            .EnableRetryOnFailure()
            .UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery));

var databaseContext = new DatabaseContext(optionsBuilder.Options);

var parentId = new Guid("8784dc85-e749-4c66-baae-694f2225c478");
var someEntityId = new Guid("0434e3dc-9202-443a-bedc-3025294fa6c1");

var parent = databaseContext
    .Parents
    .Where(_ => _.Id == parentId)
    .Include(_ => _.Child)
    .SingleOrDefault() ?? throw new Exception("...");

var someEntity = databaseContext
    .SomeEntities
    .Where(_ => _.Id == someEntityId)
    .SingleOrDefault() ?? throw new Exception("...");

parent.Child = new Child1
{
    SomeEntity = someEntity,
};

databaseContext.SaveChanges();

public abstract class Base
{
    public Guid Id { get; set; } = Guid.NewGuid();
} 

public class Parent : Base
{
    public Child? Child { get; set; }
}

public abstract class Child : Base
{
    public SomeEntity? SomeEntity { get; set; }
}

public class Child1 : Child { }

public abstract class SomeEntity : Base { }

public abstract class SomeEntity1 : SomeEntity { }

public class SomeEntity2 : SomeEntity1 { }

public class SomeEntity3 : SomeEntity2 { }

public class DatabaseContext(DbContextOptions<DatabaseContext> options) : DbContext(options)
{
    public DbSet<Child> Children { get; set; }

    public DbSet<Parent> Parents { get; set; }

    public DbSet<SomeEntity> SomeEntities { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Child1>();

        modelBuilder.Entity<SomeEntity1>();
        modelBuilder.Entity<SomeEntity2>();
        modelBuilder.Entity<SomeEntity3>();
    }
}
`

`@ajcvickers, sorry it took me a while to boil it down to an example.  This code works with 8.0.11 but not with 9.0.0, 9.0.0 gives:

Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException
  HResult=0x80131500
  Message=The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See https://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
  Source=Microsoft.EntityFrameworkCore.Relational
  StackTrace:
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(RelationalDataReader reader, Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithRowsAffectedOnly(Int32 commandIndex, RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__112_0(DbContext _, ValueTuple`2 t)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass28_0`2.<Execute>b__0(DbContext context, TState state)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Program.<Main>$(String[] args) in E:\kcoffey\EntityFramework8_0_11_v9_0_0\EntityFramework8_0_11_v9_0_0\Program.cs:line 33
`
