### ISSUE TITLE
EF UseNpgsql MigrationsAssembly setting is invalid

### ISSUE THREAD

**Issue by dashiell-zhang** [dotnet/efcore#35103]
https://github.com/npgsql/efcore.pg/issues/3365#issue-2657860814
My DatabaseContext is placed in the Repository class library. I created a Repository.Tool project specifically to perform EF migration operations. At the same time, I set the Migrations folder in the migration process in Repository.Tool. I have always done this in .net 6.0 - 8.0. Today, after upgrading to .net 9.0 and pairing it with Npgsql.EntityFrameworkCore.PostgreSQL 9.0.0-rc.2, I found that the following problem occurred when performing EF migration. I withdrew .net 8.0 and did the same operation.

Sample project https://github.com/dashiell-zhang/NetEngine.git

![image](https://github.com/user-attachments/assets/6a50e4f6-8832-45c7-9bcb-eaa78ef68197)

### Include verbose output

PM> Add-Migration Init -Verbose
Using project 'Repository.Tool'.
Using startup project 'Repository.Tool'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile D:\Study\NetEngine\Repository.Tool\bin\Release\net9.0\Repository.Tool.deps.json --additionalprobingpath C:\Users\ZhangXiaoDong\.nuget\packages --additionalprobingpath "C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages" --runtimeconfig D:\Study\NetEngine\Repository.Tool\bin\Release\net9.0\Repository.Tool.runtimeconfig.json C:\Users\ZhangXiaoDong\.nuget\packages\microsoft.entityframeworkcore.tools\9.0.0-rc.2.24474.1\tools\netcoreapp2.0\any\ef.dll migrations add Init --json --verbose --no-color --prefix-output --assembly D:\Study\NetEngine\Repository.Tool\bin\Release\net9.0\Repository.Tool.dll --project D:\Study\NetEngine\Repository.Tool\Repository.Tool.csproj --startup-assembly D:\Study\NetEngine\Repository.Tool\bin\Release\net9.0\Repository.Tool.dll --startup-project D:\Study\NetEngine\Repository.Tool\Repository.Tool.csproj --project-dir D:\Study\NetEngine\Repository.Tool\ --language C# --configuration Release --working-dir D:\Study\NetEngine --root-namespace Repository.Tool --nullable
Using assembly 'Repository.Tool'.
Using startup assembly 'Repository.Tool'.
Using application base 'D:\Study\NetEngine\Repository.Tool\bin\Release\net9.0'.
Using working directory 'D:\Study\NetEngine\Repository.Tool'.
Using root namespace 'Repository.Tool'.
Using project directory 'D:\Study\NetEngine\Repository.Tool\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding DbContext classes in the project...
Microsoft.EntityFrameworkCore.Design.OperationException: No DbContext was found in assembly 'Repository.Tool'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextType(String name)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace, Boolean dryRun)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace, Boolean dryRun)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
No DbContext was found in assembly 'Repository.Tool'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.
PM> 

### Include provider and version information

EF Core version: 9.0
Database provider: (e.g. Npgsql.EntityFrameworkCore.PostgreSQL)
Target framework: (e.g. .NET 9.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.12.0)

**Comment by dashiell-zhang** [comment]
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding DbContext classes in the project...

The main problem is that the DatabaseContext in the Repository in the Repository.Tool dependent project cannot be found in EF 9.0, but it can be found in EF 8.0.
