### ISSUE TITLE
InMemory database context with CustomWebApplicationFactory is giving double database context registration error. How do I implement this correctly?

### ISSUE THREAD

**Issue by Tealons** [dotnet/efcore#35126]
After upgrading to .NET 9 I get the following error on  `db.Database.EnsureCreated();` in the following code:

```
using (var scope = sp.CreateScope())
{
    var scopedServices = scope.ServiceProvider;
    var db = scopedServices.GetRequiredService<ApplicationDbContext>();
    var logger = scopedServices
        .GetRequiredService<ILogger<CustomWebApplicationFactory<TStartup>>>();

    // Ensure the database is created.
    db.Database.EnsureCreated();

    try
    {
        // Seed the database with test data.
        // Utilities.InitializeDbForTests(db);
    }
    catch (Exception ex)
    {
        logger.LogError(ex, "An error occurred seeding the " +
            "database with test messages. Error: {Message}", ex.Message);
    }
}
```

![Image](https://github.com/user-attachments/assets/291e4028-f86a-40c4-9ff7-51059d63b715)

The exact error:

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Services for database providers 'Microsoft.EntityFrameworkCore.SqlServer', 'Microsoft.EntityFrameworkCore.InMemory' have been registered in the service provider. Only a single database provider can be registered in a service provider. If possible, ensure that Entity Framework is managing its service provider by removing the call to 'UseInternalServiceProvider'. Otherwise, consider conditionally registering the database provider, or maintaining one service provider per database provider.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.Initialize(IServiceProvider scopedProvider, DbContextOptions contextOptions, DbContext context)
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService(IInfrastructure`1 accessor, Type serviceType)
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_Dependencies()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
   at SpiderIoT.Test.CustomWebApplicationFactory`1.<>c.<ConfigureWebHost>b__0_0(IServiceCollection services) in C:\Source\SpiderIoT\SpiderIoT.Test\CustomWebApplicationFactory.cs:line 54
   at Microsoft.Extensions.Hosting.HostBuilder.InitializeServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateHost(IHostBuilder builder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.ConfigureHostBuilder(IHostBuilder hostBuilder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureServer()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.get_Services()
   at SpiderIoT.Test.APITest..ctor(CustomWebApplicationFactory`1 factory) in C:\Source\SpiderIoT\SpiderIoT.Test\APITest.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

```

My feeling is that removing the previous ApplicationDbContext is not working properly? This is my code (which was adjusted according to the .NET 9 docs, but is still not working):

```
 // Remove the app's ApplicationDbContext registration.
 var dbContextDescriptor = services.SingleOrDefault(
   d => d.ServiceType ==
   typeof(DbContextOptions<ApplicationDbContext>));

 services.Remove(dbContextDescriptor);

 var dbConnectionDescriptor = services.SingleOrDefault(
     d => d.ServiceType ==
         typeof(DbConnection));

 services.Remove(dbConnectionDescriptor);

 // Add ApplicationDbContext using an in-memory database for testing.
 services.AddDbContext<ApplicationDbContext>(options =>
 {
     options.UseLazyLoadingProxies();
     options.UseInMemoryDatabase("InMemoryDbForTesting");
 });
```

After hours of Googling and trying stuff out I'm a but lost how this should work in .NET 9...

**Comment by Tealons** [comment]
Not sure how or why, but removing the `IDbContextOptionsConfiguration<ApplicationDbContext>` did the trick:
```

 var dbContextDescriptor = services.SingleOrDefault(
   d => d.ServiceType ==
   typeof(IDbContextOptionsConfiguration<ApplicationDbContext>));
```

**Comment by Tealons** [comment]
@cincuranet: closing this feels a bit wrong. The documentation like: https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-9.0#customize-webapplicationfactory will give the error I described? And is my solution the right way to do this? Or is there a better way?

**Comment by kymarti** [comment]
I'm experiencing this same exact issue. In my case, I'm using .NET 8 but have some EF-related packages -- such as EF core -- to v9.0.0. Can this be re-opened, @cincuranet? If not, @Tealons perhaps we should create a new thread for this issue?

I would also like to understand if there's been an intentional change in behavior. 
* If yes, shouldn't the documentation @Tealons linked above be updated?
* If no, I think we need a bug tracking this.

**Comment by kymarti** [comment]
Sure, let me try to put something together @ajcvickers , but if you have time @Tealons feel free to go ahead and put something together as well.

**Comment by loekensgard** [comment]
@ajcvickers 
I managed to reproduce the issue in this project [EfCore .net9 Test](https://github.com/[loekensgard/EfCoreTestProject](https://github.com/loekensgard/EfCoreTestProject))

**Comment by rwb196884** [comment]
Just run into this trying to update from 8 to 9: 8 works, 9 doesn't. So I guess we're staying with 8.

**Comment by ajcvickers** [comment]
Note for team: I am able to reproduce this and I am investigating. It looks like a regression in ASP.NET testing.

**Comment by ajcvickers** [comment]
Looks like this is a change in the behavior `WebApplicationFactory` when used in tests. Two projects are needed to repro this: a simple web app with this code:

```C#
public class Program
{
    public static void Main(string[] args)
    {
        var builder = WebApplication.CreateBuilder(args);
        builder.Services.AddDbContext<ContextOfDoom>(options => options.UseSqlServer());
        builder.Build().Run();
    }
}


public class ContextOfDoom : DbContext
{
    public ContextOfDoom(DbContextOptions<ContextOfDoom> options) : base(options) { }
}
```

And then a test project with a test and a `WebApplicationFactory`:

```C#
public class TestWebApplicationFactory : WebApplicationFactory<Program>
{
    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        builder.ConfigureServices(services =>
        {
            services.AddDbContext<ContextOfDoom>((_, context) => context.UseInMemoryDatabase("DB"));
            var serviceProvider = services.BuildServiceProvider();
            using var scope = serviceProvider.CreateScope();
            var context = serviceProvider.GetService<ContextOfDoom>()!;
            _ = context.Model;
        });
    }
}

public class SomeTests : IClassFixture<TestWebApplicationFactory>
{
    public SomeTests(TestWebApplicationFactory factory)
    {
        factory.WithWebHostBuilder(_ => { }).CreateClient();
    }

    [Fact]
    public async Task Get_Test()
    {
    }
}
```

When running the tests in EF8, the web host resolver is not used, and so that Main method is not run, and only the in-memory database is registered.

When running the tests in EF9, the web host resolver runs and so both the SQL Server and in-memory databases are registered, resulting in:

```
System.InvalidOperationException
Services for database providers 'Microsoft.EntityFrameworkCore.SqlServer', 'Microsoft.EntityFrameworkCore.InMemory' have been registered in the service provider. Only a single database provider can be registered in a service provider. If possible, ensure that Entity Framework is managing its service provider by removing the call to 'UseInternalServiceProvider'. Otherwise, consider conditionally registering the database provider, or maintaining one service provider per database provider.
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.Initialize(IServiceProvider scopedProvider, DbContextOptions contextOptions, DbContext context)
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at TestWebApplicationFactory.<>c.<ConfigureWebHost>b__0_0(IServiceCollection services) in D:\code\repros\WebApplication1\WebApplication1\WebApplication1.Tests\SomeTests.cs:line 18
   at Microsoft.Extensions.Hosting.HostApplicationBuilder.HostBuilderAdapter.ApplyChanges()
   at Microsoft.Extensions.Hosting.HostApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at Program.Main(String[] args) in D:\code\repros\WebApplication1\WebApplication1\WebApplication1\Program.cs:line 9
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.CreateHost()
   at Microsoft.Extensions.Hosting.HostFactoryResolver.<>c__DisplayClass10_0.<ResolveHostFactory>b__0(String[] args)
   at Microsoft.AspNetCore.Mvc.Testing.DeferredHostBuilder.Build()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateHost(IHostBuilder builder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.DelegatedWebApplicationFactory.CreateHost(IHostBuilder builder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.ConfigureHostBuilder(IHostBuilder hostBuilder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureServer()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(Uri baseAddress, DelegatingHandler[] handlers)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient(WebApplicationFactoryClientOptions options)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient()
   at SomeTests..ctor(TestWebApplicationFactory factory) in D:\code\repros\WebApplication1\WebApplication1\WebApplication1.Tests\SomeTests.cs:line 27
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
```

**Comment by loekensgard** [comment]
@ErikEJ, it appears that this issue persists even after removing the currently registered service. In my [test project](https://github.com/loekensgard/EfCoreTestProject/blob/main/TestApi.Tests/CustomWebApplicationFactory.cs#L19C1-L24C44), I have the same configuration, but the error still occurs when running .NET 9. 

However @Tealons found a workaround, but this could potentially lead to unexpected behavior? 
> Not sure how or why, but removing the `IDbContextOptionsConfiguration<ApplicationDbContext>` did the trick:
> 
> ```
> 
>  var dbContextDescriptor = services.SingleOrDefault(
>    d => d.ServiceType ==
>    typeof(IDbContextOptionsConfiguration<ApplicationDbContext>));
> ```

**Comment by ajcvickers** [comment]
@ErikEJ Yeah, I saw that in one of the repros--doesn't help in 9.

**Comment by jaliyaudagedara** [comment]
Seeing the same issue, tagging myself in for updates.

**Comment by VictorioBerra** [comment]
Seeing same issue, tagging myself as well.

**Comment by julielerman** [comment]
oh hai. Yep, updating my Pluralsight course demos to .NET 9 and ran into this. Will keep eyes on it! Thanks for everyone's contributions to the issue.

**Comment by julielerman** [comment]
I was comparing debugging the .net 8 versin and .net 9. The effect of removing the dbcontext and dbcontextoptions on the services is the same. However, when adding in my two sqlite services, there is a difference.
Here is the code for adding in SQLite:

```
// Create open SqliteConnection so EF won't automatically close it.
services.AddSingleton<DbConnection>(container =>
{
    var connection = new SqliteConnection("DataSource=:memory:");
    connection.Open();

    return connection;
});

services.AddDbContext<PubContext>((container, options) =>
{
    var connection = container.GetRequiredService<DbConnection>();
    options.UseSqlite(connection);
});
```

_(I want to get better screenshots of the services, so saving this and will add them in shortly)_

**Comment by JYasgarYTGI** [comment]
I ran into the same issue after upgrading from EF8 to 9. My Startup. cs has four DI DBContexts, so I made sure to remove all four, even though my tests only use three of them.
I also changed the lines in my CustomWebApplicationFactory from:

    ServiceDescriptor descriptor1 = services.SingleOrDefault(
                    d => d.ServiceType == typeof(**DbContextOptions**<RVSAccountContext>))!;
 to
     ServiceDescriptor descriptor1 = services.SingleOrDefault(
                    d => d.ServiceType == typeof(**IDbContextOptionsConfiguration**<RVSAccountContext>))!;

My tests are running again.

**Comment by ericwood8** [comment]
Unfortunately the Microsoft staff said this different error message would be tracked here:   https://github.com/dotnet/efcore/issues/35179

**Comment by ericwood8** [comment]
@rwb196884 Yes.  That is what I was trying to communicate.

**Comment by julielerman** [comment]
Yes, @JYasgarYTGI nailed it and but I only have a few basic tests and am wondering if we need to be concerned about side effects of using the IDbContextOptionsConfiguration interface over the DbContextOptions implementation. And it aligns with my discovery that IDbCOntextOptionsConfiguration is "left over" otherwise (as per my testing above). Thanks Jack!

**Comment by AndriySvyryd** [comment]
Sorry that it took so long for the response. This is by design.

Starting with 9 `DbContextOptions<>` in the service provider doesn't contain any configuration itself, instead it uses all the registered `IDbContextOptionsConfiguration<>` instances to build the configuration. This was done to enable options composition, so that a context can be configured without registering it, this is useful for Aspire as it applies some default configuration.

The best workaround currently is to remove `IDbContextOptionsConfiguration<>` as shown above. I'll [add this to breaking changes](https://github.com/dotnet/EntityFramework.Docs/issues/4923).

Since there isn't an API to remove a provider configuration, we can use this issue to track adding it. This is a fairly advanced scenario, so it doesn't need to be easily discoverable. I propose the following:

```C#
services.ConfigureDbContext<TestContext>(options =>
    ((IDbContextOptionsBuilderInfrastructure)options).RemoveExtension<SqlServerOptionsExtension>());
```

**Comment by BlNARYFOUR** [comment]
@AndriySvyryd if it is by design, surely this should be edited in the documentation of [learn.microsoft .NET 9](https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-9.0#customize-webapplicationfactory) **_ASAP_**?

Anyone currently following the documentation, will hit a very unpleasant surprise "I did exactly as the docs said... WHY DOESN'T IT WORK?"

**Comment by AndriySvyryd** [comment]
@BlNARYFOUR Thanks for pointing this out. Filed https://github.com/dotnet/AspNetCore.Docs/issues/34584

**Comment by dadaPipes** [comment]
I could not figure out how to solve it from the comments, but this blog post helped med out.
In case anyone stumples upon this thread and is as confused as I was.

https://www.devgem.io/posts/resolving-multiple-ef-core-database-providers-in-asp-net-core-integration-testing

**Comment by JYasgarYTGI** [comment]
Taking my post above, I wrote it up too. 

https://jackyasgar.net/solved-ef-8-to-9-migration-database-provider-exception/

**Comment by Tealons** [comment]
I didn't know that link building was still a thing :)

**Comment by adcorduneanu** [comment]
When this is a breaking change, version 9 of EF Core should be limited to .net 9 - we have applications on LTS (.net 8) failing because of this.

**Comment by AndriySvyryd** [comment]
@adcorduneanu You can use EF Core 8 on .net 8

**Comment by adcorduneanu** [comment]
@AndriySvyryd, this is not an option when you have over 150 projects in the field, and the updates are done automatically. 

If this was targeting .net 9 then should be only on .net 9.

**Comment by rwb196884** [comment]
I'll just comment it out. Unit tests are worthless when you have to spend more time fucking about to fix them then on real code.

**Comment by rwb196884** [comment]
A workaround is to not add the SQL Server version of the service in the first place becaue it cannot be properly replaced later.

Do this in your test project's application factory
```
    public class MyWebApplicationFactory<TStartup> : WebApplicationFactory<TStartup> where TStartup : class
    {
        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            builder.UseEnvironment("IntegrationTests");
```
and this in your `Program.cs`
```
if (builder.Environment.EnvironmentName != "IntegrationTests") {
    builder.Services.AddDbContext<MyDbContext>(
            options =>
            {
                options.UseSqlServer("name=ConnectionStrings:MyDatabase", (SqlServerDbContextOptionsBuilder sqlServerOptions) =>
                { });
            });
}
```

**Comment by menno2controlware** [comment]
In our unit test project we override the context like this

services
                .RemoveAll<IDbContextOptionsConfiguration<ApplicationContext>>()
                .AddDbContext<ApplicationContext>((_, options) => options.UseSqlServer(((MsSqlTestDatabase)TestDatabase).GetConnectionString));
