### ISSUE TITLE
Programmatic Scaffold-Migration Issue After Updating to 9.0.0

### ISSUE THREAD

**Issue by oONoobMasterOo** [dotnet/efcore#35146]
After updating **Npgsql** to version **9.0.0**, I encounter the following exception while attempting to scaffold migrations programmatically:

```
System.InvalidOperationException: Metadata changes are not allowed when the model has been marked as read-only.
   at Microsoft.EntityFrameworkCore.Infrastructure.Annotatable.EnsureMutable()
   at Microsoft.EntityFrameworkCore.Infrastructure.AnnotatableBase.RemoveAnnotation(String name)
   at Microsoft.EntityFrameworkCore.Infrastructure.Annotatable.Microsoft.EntityFrameworkCore.Metadata.IMutableAnnotatable.RemoveAnnotation(String name)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.SnapshotModelProcessor.Process(IReadOnlyModel model, Boolean resetVersion)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language, Boolean dryRun)
```

my scaffold code:

```
var services = new ServiceCollection().AddEntityFrameworkDesignTimeServices().AddDbContextDesignTimeServices(context);

 var designTimeServices = new SqlServerDesignTimeServices();
 designTimeServices.ConfigureDesignTimeServices(services);

 var serviceProvider = services.BuildServiceProvider();
 var scaffolder = serviceProvider.GetRequiredService<IMigrationsScaffolder>();

 var migrationPath = Path.Combine(Hosting.ContentRootPath, @"..\", SystemName, "Migrations", DbContext.UseSqlServerProvider ? "SqlServer" : "NpgSql");
 if (!Directory.Exists(migrationPath)) Directory.CreateDirectory(migrationPath);

 var migration = scaffolder.ScaffoldMigration("my-migration-name","namespace"); 
```

**Comment by cincuranet** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by oONoobMasterOo** [comment]
here is my full scaffold code that worked perfectly at version 8.0.11:

```
using (var DbContext = Activator.CreateInstance(MainDbContext, DbContextOptionsBuilderObject.Options, HttpContextAccessor) as DbContext)
{
    var relationalDatabaseCreator = DbContext.GetService<IDatabaseCreator>() as IRelationalDatabaseCreator;
    var databaseExists = await relationalDatabaseCreator.ExistsAsync();
    var hasDifferences = false;

    var Migrations = DbContext.Database.GetMigrations();
    var migrationsAssembly = DbContext.GetService<IMigrationsAssembly>();
    if (migrationsAssembly.ModelSnapshot != null)
    {
        var snapshotModel = migrationsAssembly.ModelSnapshot?.Model;

        if (snapshotModel is IMutableModel mutableModel)
        {
            snapshotModel = mutableModel.FinalizeModel();
        }

        if (snapshotModel != null)
        {
            snapshotModel = DbContext.GetService<IModelRuntimeInitializer>().Initialize(snapshotModel);
        }

        hasDifferences = DbContext.GetService<IMigrationsModelDiffer>().HasDifferences(snapshotModel?.GetRelationalModel(), DbContext.GetService<IDesignTimeModel>().Model?.GetRelationalModel());
    }
    if (!databaseExists || hasDifferences || migrationsAssembly.ModelSnapshot == null)
    {
        var services = new ServiceCollection().AddEntityFrameworkDesignTimeServices().AddDbContextDesignTimeServices(DbContext);

        var designTimeServices = new SqlServerDesignTimeServices();
        designTimeServices.ConfigureDesignTimeServices(services);

        var serviceProvider = services.BuildServiceProvider();
        var scaffolder = serviceProvider.GetRequiredService<IMigrationsScaffolder>();

        var migrationPath = Path.Combine(Hosting.ContentRootPath, @"..\", SystemName, "Migrations", DbContext.UseSqlServerProvider ? "SqlServer" : "NpgSql");
        if (!Directory.Exists(migrationPath)) Directory.CreateDirectory(migrationPath);

        var migration = scaffolder.ScaffoldMigration($"Migration-test1", $"Company.Systems.{SystemName}", $"Migrations.{(DbContext.UseSqlServerProvider ? "SqlServer" : "NpgSql")}");

        await System.IO.File.WriteAllTextAsync(Path.Combine(migrationPath, migration.MigrationId + migration.FileExtension), migration.MigrationCode);
        await System.IO.File.WriteAllTextAsync(Path.Combine(migrationPath, migration.MigrationId + ".Designer" + migration.FileExtension), migration.MetadataCode);
        await System.IO.File.WriteAllTextAsync(Path.Combine(migrationPath, migration.SnapshotName + migration.FileExtension), migration.SnapshotCode);

        result.Add(new(true, "Main DbContext Scaffolded"));
    }
}
```

the exception happens at `scaffolder.ScaffoldMigration()`

**Comment by AndriySvyryd** [comment]
I'm not sure why you scaffold a new migration when the database doesn't exist, but try replacing `hasDifferences || migrationsAssembly.ModelSnapshot == null` with `DbContext.Database.HasPendingModelChanges()` and remove all the code that's no longer necessary:

```C#
using (var DbContext = Activator.CreateInstance(MainDbContext, DbContextOptionsBuilderObject.Options, HttpContextAccessor) as DbContext)
{
    var relationalDatabaseCreator = DbContext.GetService<IDatabaseCreator>() as IRelationalDatabaseCreator;
    var databaseExists = await relationalDatabaseCreator.ExistsAsync();
    if (!databaseExists || DbContext.Database.HasPendingModelChanges())
    {
        var services = new ServiceCollection().AddEntityFrameworkDesignTimeServices().AddDbContextDesignTimeServices(DbContext);

        var designTimeServices = new SqlServerDesignTimeServices();
        designTimeServices.ConfigureDesignTimeServices(services);

        var serviceProvider = services.BuildServiceProvider();
        var scaffolder = serviceProvider.GetRequiredService<IMigrationsScaffolder>();

        var migrationPath = Path.Combine(Hosting.ContentRootPath, @"..\", SystemName, "Migrations", DbContext.UseSqlServerProvider ? "SqlServer" : "NpgSql");
        if (!Directory.Exists(migrationPath)) Directory.CreateDirectory(migrationPath);

        var migration = scaffolder.ScaffoldMigration($"Migration-test1", $"Company.Systems.{SystemName}", $"Migrations.{(DbContext.UseSqlServerProvider ? "SqlServer" : "NpgSql")}");

        await System.IO.File.WriteAllTextAsync(Path.Combine(migrationPath, migration.MigrationId + migration.FileExtension), migration.MigrationCode);
        await System.IO.File.WriteAllTextAsync(Path.Combine(migrationPath, migration.MigrationId + ".Designer" + migration.FileExtension), migration.MetadataCode);
        await System.IO.File.WriteAllTextAsync(Path.Combine(migrationPath, migration.SnapshotName + migration.FileExtension), migration.SnapshotCode);

        result.Add(new(true, "Main DbContext Scaffolded"));
    }
}
```

**Comment by oONoobMasterOo** [comment]
I've used your code but am still encountering the error.  

I’d like to debug it myself. Could you let me know which EF Core projects I should reference?

**Comment by oONoobMasterOo** [comment]
👀

**Comment by oONoobMasterOo** [comment]
any due date?

**Comment by oONoobMasterOo** [comment]
any workarounds please? cause my migration to **.NET 9** is stopped due to that issue.

Thanks

**Comment by AndriySvyryd** [comment]
@oONoobMasterOo I am still unable to repro this issue locally.  But you can try adding a new migration manually before running the code.

**Comment by oONoobMasterOo** [comment]
Hi,

During the **initial migration** without a snapshot, it works well, but **subsequent migrations** result in the same **error**. However, performing the using the standard command line works without issues. would like to know which project to reference to debug this issue in my environment.

 regards.

**Comment by oONoobMasterOo** [comment]
[ScaffoldMigration.zip](https://github.com/user-attachments/files/18343993/ScaffoldMigration.zip)
Here is a reproducible sample application.

**Comment by AndriySvyryd** [comment]
> would like to know which project to reference to debug this issue in my environment.

You'd need to reference EFCore.Design, EFCore.PG and all the projects they reference. Setting up a debugging environment will not be straightforward.

**Comment by AndriySvyryd** [comment]
> [ScaffoldMigration.zip](https://github.com/user-attachments/files/18343993/ScaffoldMigration.zip)
Here is a reproducible sample application.

I see, this happens because you call this before scaffolding a migration:

```C#
if (_appDbContext.Database.GetPendingMigrations().Any())
{
    _appDbContext.Database.Migrate();
}
```

https://github.com/dotnet/efcore/pull/35432 Will fix this.

**Comment by oONoobMasterOo** [comment]
cool, when this fix gets released?

**Comment by AndriySvyryd** [comment]
> cool, when this fix gets released?

It will be in EF Core 10 preview releasing in a couple of months.

**Comment by oONoobMasterOo** [comment]
Currently, `context.Database.HasPendingModel()` triggers the same error. Is there any workaround or alternative method to detect model changes? I need this functionality to work in **EF Core 9** because **EF Core 10** is too far away.

**Comment by oopee** [comment]
We are experiencing this exact same problem and thus cannot upgrade from EF Core 8 to 9. Any change of porting the fix to EF Core 9?

**Comment by roji** [comment]
@AndriySvyryd any workaround here?

**Comment by AndriySvyryd** [comment]
The workaround is to not call any Migration-related API before `ScaffoldMigration` in the same process.

**Comment by oopee** [comment]
Is there a reason why this couldn't be fixed for 9? It is a breaking change after all. We have a semi-automated tool for generating migrations (since we have complex application with many database contextes) and the tool has to call GetPendingMigrations() in order to work properly.

**Comment by oopee** [comment]
Excellent, thank you!

**Comment by oONoobMasterOo** [comment]
Perfect, an excellent job I'm witnessing!

**Comment by oONoobMasterOo** [comment]
After updating to version 9.0.4, the following are no longer available:

1. Microsoft.EntityFrameworkCore.Migrations.Design (namespace)
2. IMigrationsScaffolder (class)

**Comment by ErikEJ** [comment]
@oONoobMasterOo Remove PrivateAssets from your .csproj.

**Comment by oONoobMasterOo** [comment]
Thanks man, that worked!

**Comment by oONoobMasterOo** [comment]
After the update, when I scaffold a migration in my current project where only one column has been added to the model, it generates the migration file script as if it were the initial migration, recreating all tables schemas if it were a completely new database.

**Comment by oONoobMasterOo** [comment]
any thoughts?

**Comment by AndriySvyryd** [comment]
Check whether the model snapshot is available in the migrations assembly and is not empty.

**Comment by oONoobMasterOo** [comment]
I've checked the model snapshot and is available and not empty.

![Image](https://github.com/user-attachments/assets/716693cd-adc0-47b3-a3e8-1932443ffca7)

**Comment by oONoobMasterOo** [comment]
the model snapshot:

![Image](https://github.com/user-attachments/assets/7c1f6403-63b6-489e-8732-37a0f0ac03f9)

**Comment by AndriySvyryd** [comment]
> .ReplaceService<IMigrationsAssembly, SoftMaxMigrationsAssembly>();

Actually, `IMigrationsAssembly` is a design-time service. You need to replace it by implementing [IDesignTimeServices ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.design.idesigntimeservices)

**Comment by oONoobMasterOo** [comment]
> Then you'd need to create a new issue and attach a small repro project

https://github.com/dotnet/efcore/issues/35146#issuecomment-2839532271
