### ISSUE TITLE
SYSTEM_VERSIONING = OFF in EF8 migration causes SYSTEM_VERSIONING is not turned ON in EF9

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/efcore#35180]
We currently target EF8.

We have an existing migration

```
public partial class VirtualProgramEvent : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
                             ALTER TABLE dbo.ProgramEvents
                             SET(SYSTEM_VERSIONING = OFF)
                             """);

        migrationBuilder.AddColumn<bool>(name: "Virtual",
            table: "_ProgramEvents_History",
            type: "bit",
            defaultValue: false,
            nullable: true);

        migrationBuilder.AddColumn<bool>(
                name: "Virtual",
                table: "ProgramEvents",
                type: "bit",
                nullable: false,
                computedColumnSql: "CAST(CASE WHEN (Location IS NULL AND OfficialLocationId IS NULL) THEN 1 ELSE 0 END AS BIT)",
                stored: true)
            .Annotation("SqlServer:IsTemporal", true)
            .Annotation("SqlServer:TemporalHistoryTableName", "_ProgramEvents_History")
            .Annotation("SqlServer:TemporalHistoryTableSchema", null)
            .Annotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd")
            .Annotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart");

        migrationBuilder.Sql("""
                             ALTER TABLE dbo.ProgramEvents
                             SET(SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo._ProgramEvents_History))
                             """);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder) =>
        migrationBuilder.DropColumn(
                name: "Virtual",
                table: "ProgramEvents")
            .Annotation("SqlServer:IsTemporal", true)
            .Annotation("SqlServer:TemporalHistoryTableName", "_ProgramEvents_History")
            .Annotation("SqlServer:TemporalHistoryTableSchema", null)
            .Annotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd")
            .Annotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart");
}
````

note that it manipulates `SYSTEM_VERSIONING`.

This migration works fine on EF8.

once i update to EF9 i get

```
Microsoft.Data.SqlClient.SqlException : SYSTEM_VERSIONING is not turned ON for table 'template.dbo.ProgramEvents'.
Data:
  HelpLink.ProdName: Microsoft SQL Server
  HelpLink.ProdVer: 16.00.4155
  HelpLink.EvtSrc: MSSQLServer
  HelpLink.EvtID: 13591
  HelpLink.BaseHelpUrl: https://go.microsoft.com/fwlink
  HelpLink.LinkId: 20476
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<InternalExecuteNonQueryAsync>b__193_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteAsync(IReadOnlyList`1 migrationCommands, IRelationalConnection connection, MigrationExecutionState executionState, Boolean beginTransaction, Boolean commitTransaction, Nullable`1 isolationLevel, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteAsync(IReadOnlyList`1 migrationCommands, IRelationalConnection connection, MigrationExecutionState executionState, Boolean beginTransaction, Boolean commitTransaction, Nullable`1 isolationLevel, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IReadOnlyList`1 migrationCommands, IRelationalConnection connection, MigrationExecutionState executionState, Boolean commitTransaction, Nullable`1 isolationLevel, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateImplementationAsync(DbContext context, String targetMigration, MigrationExecutionState state, Boolean useTransaction, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateImplementationAsync(DbContext context, String targetMigration, MigrationExecutionState state, Boolean useTransaction, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c.<<MigrateAsync>b__22_1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at MinisterialProgram.Data.DbInitializer.Initialize(MinProgramDb context) in C:\Code\MinisterialProgramDataModel\src\DataModel\DbInitializer.cs:line 11
```

if i debug unto it i can see in `MigrationCommandExecutor.ExecuteAsync` that there are duplicate 

![Image](https://github.com/user-attachments/assets/228ba1ce-84c2-461f-ac51-f669738898c0)

note the newline differences. so the one from our migration is first with the command split over two lines.

i looked through the history and found this change https://github.com/dotnet/efcore/commit/e3e7a5b15b58e6719dd67bfa9f949acd8d9fe8d0
it might be the cause

I dont have the time to create a minimal repro, and my plan is to squash the migrations to make the problem go away.
But i figured i would raise an issue and see if you want any more context while i can still debug into at and give u more information

**Comment by SimonCropp** [comment]
sigh. this `SET(SYSTEM_VERSIONING = OFF)` pattern is in 27 of our migrations across multiple projects. looks like we will not be updating to EF9 until this is fixed

**Comment by maumar** [comment]
This is by design. EF8 had a bug, where for some temporal migration operations we were not switching off versioning (and then switching it back on again at the end). https://github.com/dotnet/efcore/commit/e3e7a5b15b58e6719dd67bfa9f949acd8d9fe8d0 addressed those issues and now EF properly generates these calls, however in this case, manual 

```
        migrationBuilder.Sql("""
                             ALTER TABLE dbo.ProgramEvents
                             SET(SYSTEM_VERSIONING = OFF)
                             """);
```

was added by the user to work around the bug in EF8,

Now that EF9 manages the versioning correctly, it tries to disable versioning, but it already has been disabled by this manual step. We can't reliably parse user's custom migration code to see if they happen to disable versioning, period or do some other workarounds. 

Only thing we could reliably do it to make the versioning-off-operation that we generate idempotent, but that incurs cost on everyone to mitigate this edge case. If we get more reports of this issue we might consider doing that, but for now we are ok with the behavior as is, and suggest fixing the migrations manually (which should just be deleting the custom versioning ON and OFF statements)

**Comment by gbiellem** [comment]
@maumar The above approach that @SimonCropp outlined allowed adding a computed column to an existing temporal table,  Since the move to EF9 we are finding it impossible to so in a migration.  Could you please should how this can be done now?

**Comment by SimonCropp** [comment]
@maumar or better yet. add the "how this can be done" to the release notes given it is a breaking change

**Comment by SimonCropp** [comment]
@ajcvickers any thoughts on the last two comments?

**Comment by ajcvickers** [comment]
@SimonCropp @gbiellem If this still doesn't work after removing your previous workarounds, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by maumar** [comment]
@SimonCropp  @gbiellem we do have tests adding computed column to the temporal table, so those should be working once the manual versioning manipulation is removed. Is that not what you see in your scenario?

basically this migration should execute just fine of EF9:

```cs
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AddColumn<bool>(name: "Virtual",
            table: "_ProgramEvents_History",
            type: "bit",
            defaultValue: false,
            nullable: true);

        migrationBuilder.AddColumn<bool>(
                name: "Virtual",
                table: "ProgramEvents",
                type: "bit",
                nullable: false,
                computedColumnSql: "CAST(CASE WHEN (Location IS NULL AND OfficialLocationId IS NULL) THEN 1 ELSE 0 END AS BIT)",
                stored: true)
            .Annotation("SqlServer:IsTemporal", true)
            .Annotation("SqlServer:TemporalHistoryTableName", "_ProgramEvents_History")
            .Annotation("SqlServer:TemporalHistoryTableSchema", null)
            .Annotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd")
            .Annotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart");
    }
```

you can also remove all the temporal annotations from AddColumn - we don't use them anymore, we only use annotations on table-modifying operations. But things should work either with or without them.


Existing tests:
https://github.com/dotnet/efcore/blob/ac5bd7bc664b44837c515da14577f4c48a63849b/test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs#L7141

https://github.com/dotnet/efcore/blob/ac5bd7bc664b44837c515da14577f4c48a63849b/test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs#L7205

Here is the issue https://github.com/dotnet/efcore/issues/27844 and here is the fix  https://github.com/dotnet/efcore/commit/b96c768116efdf70e950ac956b39e483493b80fa

**Comment by gbiellem** [comment]
Thanks @maumar and @ajcvickers 

I tried recreating the issue in a fresh db in .Net 9 and EF 9  and could not.   We'll dig further and open a fresh issue if we can isolate the problem

**Comment by gbiellem** [comment]
@ajcvickers @maumar 


I've reproed this issue on  a fresh project using .Net 9 and EF 9 loosely based on the testcase @maumar  referenced

```
public class SampleDb(DbContextOptions options) : DbContext(options)
{
    protected override void OnModelCreating(ModelBuilder builder) =>
        builder.ApplyConfigurationsFromAssembly(GetType().Assembly);
}

public class DesignTimeContextFactory() :
    IDesignTimeDbContextFactory<SampleDb>
{
    public SampleDb CreateDbContext(string[] args)
    {
        var builder = new DbContextOptionsBuilder<SampleDb>()
            .UseSqlServer("Server=.;Database=Sample;Trusted_Connection=True;Encrypt=False");

        return new SampleDb(builder.Options);
    }
}

public class Customer
{
    public int Id { get; set; }
    public int ComputedNumber { get; }

    class ConfigureModel : IEntityTypeConfiguration<Customer>
    {
        public void Configure(EntityTypeBuilder<Customer> builder)
        {
            builder.ToTable("Customers", _ => _.IsTemporal());
            builder.HasKey(_=> _.Id);
            builder.Property(_ => _.Id).ValueGeneratedOnAdd();
            builder.Property(_ => _.ComputedNumber).HasComputedColumnSql("1", true);
        }
    }
}
```

I commented out computed property in  Customer class and the builder and created an initial migration to get a fresh db using the vs package manager console 


I then uncommented the property in the Customer class and builder and created a second migration and tried applying it to the db.

This all worked and at this point I thought I could not repro the issue, 

However I repeated the process but changed the computed property line in the  builder to do an actual computation rather than using "1" 

e,g.
```
builder.Property(_ => _.ComputedNumber).HasComputedColumnSql("Convert(int, 1 + 1", true);
```

This resulted in the second migration throwing 

```
Acquiring an exclusive lock for migration application. See https://aka.ms/efcore-docs-migrations-lock for more information if this takes too long.
Applying migration '20241206230404_AddComputedColumn'.
Failed executing DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
DECLARE @historyTableSchema sysname = SCHEMA_NAME()
EXEC(N'ALTER TABLE [Customers] SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [' + @historyTableSchema + '].[CustomersHistory]))')
Microsoft.Data.SqlClient.SqlException (0x80131904): Setting SYSTEM_VERSIONING to ON failed because column 'ComputedNumber' does not have the same nullability attribute in tables 'Sample.dbo.Customers' and 'Sample.dbo.CustomersHistory'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.Execute(IReadOnlyList`1 migrationCommands, IRelationalConnection connection, MigrationExecutionState executionState, Boolean beginTransaction, Boolean commitTransaction, Nullable`1 isolationLevel)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.<>c.<ExecuteNonQuery>b__3_1(DbContext _, ValueTuple`6 s)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IReadOnlyList`1 migrationCommands, IRelationalConnection connection, MigrationExecutionState executionState, Boolean commitTransaction, Nullable`1 isolationLevel)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateImplementation(DbContext context, String targetMigration, MigrationExecutionState state, Boolean useTransaction)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c.<Migrate>b__20_1(DbContext c, ValueTuple`4 s)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:de38b0c2-511b-4129-91ce-7bb0c63d379b
Error Number:13531,State:1,Class:16
Setting SYSTEM_VERSIONING to ON failed because column 'ComputedNumber' does not have the same nullability attribute in tables 'Sample.dbo.Customers' and 'Sample.dbo.CustomersHistory'.
``` 
 @maumar  the test you referenced  also uses a number than a computation so I guess that's why it also passes

**Comment by ajcvickers** [comment]
Re-opened. Repro provided.

**Comment by SamMonoRT** [comment]
@AndriySvyryd - - please triage for 10.0

**Comment by AndriySvyryd** [comment]
@SimonCropp @gbiellem This isn't something that can be fixed in EF. SQL Server will make the computed column nullable in some cases and we can't reliably predict this.

So, if you are running into this issue make the column nullable in the EF model or force the computed expression to be non-nullable:
```
builder.Property(_ => _.ComputedNumber).HasComputedColumnSql("ISNULL(Convert(int, 1 + 1), 2)", true);
```
