### ISSUE TITLE
Mapping entities with a foreign key value of 0 fails in EF 8.0.11 on Azure SQL

### ISSUE THREAD

**Issue by Aileron79** [dotnet/efcore#35238]
When I have two tables with an IDENTITY(0,1) column as a primary key and a third table that allows many-to-many relationships between those two, mapping entities with a foreign key value of 0 will fail. 

I created a mini-project illustrating the issue here:
https://github.com/Aileron79/EfForeignKeyIssue

This is the Azure SQL database schema. Note that the IDENTITY columns start with 0:

```
CREATE SCHEMA Scheduler;

CREATE TABLE Scheduler.schedule (
	pk_id int IDENTITY(0,1) NOT NULL,
	description varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NOT NULL,
	CONSTRAINT schedules_pk PRIMARY KEY (pk_id)
);

CREATE TABLE Scheduler.tasks (
	pk_id int IDENTITY(0,1) NOT NULL,
	description varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'Integration task' NOT NULL,
	CONSTRAINT tasks_pk PRIMARY KEY (pk_id)
);

CREATE TABLE Scheduler.schedule_task_mapping (
	schedule_id int NOT NULL,
	group_id int NOT NULL,
	CONSTRAINT schedule_task_mapping_pk PRIMARY KEY (schedule_id,group_id)
);

ALTER TABLE Scheduler.schedule_task_mapping ADD CONSTRAINT schedule_task_mapping_schedule_FK FOREIGN KEY (schedule_id) REFERENCES Scheduler.schedule(pk_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Scheduler.schedule_task_mapping ADD CONSTRAINT schedule_task_mapping_task_FK FOREIGN KEY (group_id) REFERENCES Scheduler.tasks(pk_id) ON DELETE CASCADE ON UPDATE CASCADE;
```

After creating the tables I ran the Reverse Engineer procedure from the Tools package which created the EF DB model and context. To provoke the error condition I created this simple code. Note that it can only be run once, you need to reset the ID columns to 0  or re-create the  schema before re-running: 

```
using (var dbContext = new MyDbContext())
{
    var task1 = new DbTask()
    {
        Description = "First task (ID 0)"
    };

    var schedule1 = new Schedule()
    {
        Description = "First schedule (ID 0)"
    };

    var task2 = new DbTask()
    {
        Description = "Second task (ID 1)"
    };

    var schedule2 = new Schedule()
    {
        Description = "Second schedule (ID 1)"
    };

    dbContext.Tasks.Add(task1);
    dbContext.Schedules.Add(schedule1);
    dbContext.Tasks.Add(task2);
    dbContext.Schedules.Add(schedule2);

    dbContext.SaveChanges();
}

Console.WriteLine("Linking entities...");
using (var dbContext = new MyDbContext())
{
    var task1 = dbContext.Tasks
        .Include(x => x.Schedules)
        .Where(x => x.PkId == 0).FirstOrDefault();
    var schedule1 = dbContext.Schedules
        .Where(x => x.PkId == 0).FirstOrDefault();

    var task2 = dbContext.Tasks
        .Include(x => x.Schedules)
        .Where(x => x.PkId == 1).FirstOrDefault();
    var schedule2 = dbContext.Schedules
        .Where(x => x.PkId == 1).FirstOrDefault();



    task2.Schedules.Add(schedule2); // This will work as I am linking entities with a foreign key value of 1
    dbContext.SaveChanges();

    task1.Schedules.Add(schedule1); // This won't work with the entities that have a PkId == 0.
    dbContext.SaveChanges();
}

Console.WriteLine("Done.");
```

When saving the changes to task1, this Exception is thrown:

**System.InvalidOperationException:** 'The value of 'ScheduleTaskMapping (Dictionary<string, object>).ScheduleId' is unknown when attempting to save changes. This is because the property is also part of a foreign key for which the principal entity in the relationship is not known.'

And this is the stack trace:

```
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.PrepareToSave()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetEntriesToSave(Boolean cascadeChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__112_0(DbContext _, ValueTuple`2 t)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Program.<Main>$(String[] args) in C:\Users\me\source\repos\EfForeignKeyIssue\Program.cs:line 89
```

Not sure if there is an issue with the code that the Tools package generated, but I don't think so, this is the relevant part for the mapping table:

```
entity.HasMany(d => d.Groups).WithMany(p => p.Schedules)
    .UsingEntity<Dictionary<string, object>>(
        "ScheduleTaskMapping",
        r => r.HasOne<DbTask>().WithMany()
            .HasForeignKey("GroupId")
            .HasConstraintName("schedule_task_mapping_task_FK"),
        l => l.HasOne<Schedule>().WithMany()
            .HasForeignKey("ScheduleId")
            .HasConstraintName("schedule_task_mapping_schedule_FK"),
        j =>
        {
            j.HasKey("ScheduleId", "GroupId").HasName("schedule_task_mapping_pk");
            j.ToTable("schedule_task_mapping", "Scheduler");
            j.IndexerProperty<int>("ScheduleId").HasColumnName("schedule_id");
            j.IndexerProperty<int>("GroupId").HasColumnName("group_id");
        });
```

EF Core version: 8.0.11
Database provider: Microsoft.EntityFrameworkCore.SqlServer (Azure SQL)
Target framework: .NET 8.0
Operating system: Win 11
IDE: Visual Studio 2022 17.11.5

**Comment by ajcvickers** [comment]
@Aileron79 By default, EF uses database generated values for numeric IDs. However, for this to work, one value must be reserved as a sentinel value indicating that they key value has not yet been generated. By default, this is zero--that is, the CLR default.

If zero must instead be a valid key value, then there are two options for using EF Core with this:
- Disable [value generation for key values](https://learn.microsoft.com/en-us/ef/core/modeling/keys?tabs=data-annotations#configuring-a-primary-key) and supply your own
- [Change the sentinel](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/whatsnew#sentinel-values-and-database-defaults) to something other than zero

It's worth pointing out that neither of these are ideal, and by far the best approach is to not use zero as a valid database ID.
