### ISSUE TITLE
LocalView goes out of sync and throws an IndexOutOfRangeException

### ISSUE THREAD

**Issue by TimSirmovics** [dotnet/efcore#35243]
When executing the below set of steps, calling `.ToList()` on the LocalView throws an `IndexOutOfRangeException`.

```C#
using Microsoft.EntityFrameworkCore;

var context = new TestContext();

var entity1 = new TestEntity { Id = 1 };
var entity2 = new TestEntity { Id = 2 };
var entity3 = new TestEntity { Id = 3 };

context.TestEntities.Local.Add(entity1);
context.TestEntities.Local.Add(entity2);

var count1 = context.TestEntities.Local.Count;
var toList1 = context.TestEntities.Local.ToList();

context.Entry(entity3);
context.TestEntities.Local.Remove(entity3);

var count2 = context.TestEntities.Local.Count;
var toList2 = context.TestEntities.Local.ToList(); // IndexOutOfRangeException

public class TestContext : DbContext
{
    public TestContext()
        : base(new DbContextOptionsBuilder<TestContext>().UseInMemoryDatabase("Test").Options)
    {
    }

    public DbSet<TestEntity> TestEntities { get; set; }
}

public class TestEntity
{
    public int Id { get; set; }
}
```

```
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.CompilerServices.CastHelpers.ThrowIndexOutOfRangeException()
   at System.Runtime.CompilerServices.CastHelpers.StelemRef(Object[] array, IntPtr index, Object obj)
   at Microsoft.EntityFrameworkCore.ChangeTracking.LocalView`1.CopyTo(TEntity[] array, Int32 arrayIndex)
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.<Main>$(String[] args) in C:\_DevLocal\Local\LocalViewTest\Program.cs:line 19
```

EF Core version: 9.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer + InMemory
Target framework: net9.0
Operating system: Win 11
IDE: Visual Studio 2022 17.12.2

**Comment by mseada94** [comment]
@ajcvickers I think the issue is in the `LocalView` `Remove` method, It should return false for Detached state as well

https://github.com/dotnet/efcore/blob/76d5bef519be96817149372c613de3f2253f31cc/src/EFCore/ChangeTracking/LocalView.cs#L321C16-L321C34

**Comment by TimSirmovics** [comment]
Will this fix make it into EF 8 / 9, or is it just planned for 10?

**Comment by ajcvickers** [comment]
@TimSirmovics It's very unlikely to meet the bar for patching.

**Comment by TimSirmovics** [comment]
@ajcvickers Ok no worries, thanks for fixing it.
