### ISSUE TITLE
Can't access property.ValueGenerated in EntityType.t4 trying to implement required modifier

### ISSUE THREAD

**Issue by 5andr0** [dotnet/efcore#35290]
Scaffolding Db still doesn't support the required modifier for model generation (FEATUER REQUEST!) so I tried to implement it with EntityType.t4  
I don't want to use the required modifier for identity/auto increment columns, which I wanted to detect with the ValueGenerated flags.
As soon as I try to access `property.ValueGenerated` I'm getting these errors:

```
Found column with table: public.test, column name: id, data type: integer, nullable: False, identity: False, default value: (null), computed value: (null)
Found column with table: public.test, column name: name, data type: text, nullable: False, identity: False, default value: (null), computed value: (null)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.TextTemplatingModelGenerator.GenerateModel(IModel model, ModelCodeGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

I used `property.ValueGenerated.HasFlag(1)`, but even just doing `if (property.ValueGenerated is null) {}` will result in errors.
Accessing other [IReadOnlyProperty](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.ireadonlyproperty?view=efcore-9.0) values like PropertyInfo or Name is no problem.

I enabled t4 debugging
```
<#@ template debug="true" #>
<#
    System.Diagnostics.Debugger.Launch();
#>
```
But the debugger doesn't even launch when trying to access ValueGenerated.
I set a breakpoint when property was accessed and I can see in the debugger that the property instance holds ValueGenerated, so it should be accessible!

My installed ef nugets are all the latest 9.0.0 version and I'm using following command to scaffold:
`Scaffold-DbContext 'Name=ConnectionStrings:Postgres' Npgsql.EntityFrameworkCore.PostgreSQL -Tables public.test -context TestDbContext -OutputDir Models -Force`

### Include provider and version information

EF Core version:
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET 9.0
Operating system:
IDE: Visual Studio 2022 17.13.0 Preview 1.0

**Comment by 5andr0** [comment]
Looks like `property.ValueGenerated.HasFlag(ValueGenerated.OnAdd)` works
