### ISSUE TITLE
How to fetch count using raw request?

### ISSUE THREAD

**Issue by Mrcubix** [dotnet/efcore#35322]
Surprised discussions aren't enabled in this Repo.

## Ask a question

Currently using raw requests in **some** situations as a way to re-learn SQL.
How am i supposed to fetch count for a table ?
Attempting to use SqlQueryRaw seems to not send the Raw SQL request, as EF Framework insert its own query (which is probably why this is breaking).

### Include your code

```csharp
private const string FINANCER_COUNT_SQL_QUERY = "SELECT COUNT(*) FROM Financers";
// [...]
var total = await _context.Database.SqlQueryRaw<int>(FINANCER_COUNT_SQL_QUERY).FirstAsync();
```

### Include stack traces

```
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: s.Value'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Justif.Controllers.FinancerController.ReadRange(Int32 page, Int32 amount) in justif\Controllers\FinancerController.cs:line 98
```

### Include provider and version information

EF Core version: 8.0.11
Database provider: Microsoft.EntityFrameworkCore.Sqlite (Testing) / Microsoft.EntityFrameworkCore.SqlServer (Production)
Target framework: 8.0
Operating system: Windows 10 22H2 x64
IDE: VSCode 1.95.3

**Comment by roji** [comment]
> Attempting to use SqlQueryRaw seems to not send the Raw SQL request, as EF Framework insert its own query (which is probably why this is breaking).

EF is inserting your SQL inside some more SQL because you're terminating your query with FirstAsync(); try doing ToListAsync() to see you SQL getting executed without any modifications.

> no such column: s.Value

This error is because you're composing a LINQ operator on top of your SQL (FirstAsync()), so EF requires that you project out a single `Value` column; see the [docs](https://learn.microsoft.com/en-us/ef/core/querying/sql-queries?tabs=sqlserver#querying-scalar-non-entity-types)).

**Comment by Mrcubix** [comment]
This feels unnecessary, especially while I'm converting this app from PHP, where i don't have to do that `.ToListAsync` with PDO. 

For single row / column result like this, i feel like EF should provide the means to get a specified type value in a single call from the user, or at least, fix it to get rid of the `.ToListAsync` need, so that transitions may be easier.

**Comment by roji** [comment]
@Mrcubix I'm a bit confused as to what you're looking for here.

If the intention of your query is to load just a single element, it's indeed right to use FirstAsync() as you originally did above; when you do that, EF composes the additional SQL to get the first element (`TOP` on SQL Server), and then it's your responsibility to make sure your SQL projects out `Value`, as per the docs I linked to above. Note that EF does not parse the SQL you give it, and so cannot change your query - it can only wrap it, making it into a subquery of a larger out of query (again for the `TOP`). This in itself isn't a problem and shouldn't be something you try to avoid.

If you're not looking to load just one row from the database, then ToListAsync() is the right operator use. Since there's no need to add `TOP`, no additional SQL composition is needed.

How is the above insufficient, and what exactly are you expecting to see here?

**Comment by Mrcubix** [comment]
Sure, but my request is for the count, the return value is an int, not multiple elements, the literal count returned by SQL, a single number.

In PHP, i would fetch the first (`[0]`), and only element. But here, i can't do that directly as for some reasons, using `First()` or `FirstAsync()` Result in the exception mentionned before.

IQueryable also doesn't support indexing, so i naturally can't use that.

What i'm expecting here, is to not have this very questionnable `.ToList()` (Which i didn't know was mendatory while looking at **20 pages** of documentations) AND THEN `First()` or `[0]`. 

That ToList() **should** be unneccessary, to get a primitive value in a single column / row response.

From what i'm seeing around, it seem that what i'm doing, is what other users are doing to get this count.

So my guess is that : 

- It never worked (then how would you explain the positive feedback),
- Due to a breaking change, this isn't possible this way anymore,
- This is a bug (most likely considering the exception, seems like bad handling)

**Comment by stevendarby** [comment]
All you have to do is add `AS Value` after `COUNT(*)`

**Comment by roji** [comment]
@Mrcubix as @stevendarby wrote, just add `AS Value` to your SQL as follows:

```sql
private const string FINANCER_COUNT_SQL_QUERY = "SELECT COUNT(*) AS Value FROM Financers";
```

At that point you can just use FirstOrDefault().
