### ISSUE TITLE
Can't ignore an ImmutableArray<> property in entity configuration

### ISSUE THREAD

**Issue by ErroneousFatality** [dotnet/efcore#35329]
I want to have a pass-through property in my code for developer usage convenience, thus I want to ignore the property in the entity configuration because I don't need it mapped to the database.
EFCore throws an exception during migration building saying it can't use the property because it doesn't know how to compare the generic immutable array type with an object.

When I change the ignored property's type to `IReadOnlyList<Role>`/`IReadOnlyCollection<Role>` everything works fine.

### Code examples

```C#
public sealed class Example 
{
    public Guid Id { get; private set; }

    public ImmutableArray<Role> Roles { 
        get => Enum.GetValues<Role>().Where(flag => RoleFlags.HasFlag(flag)).ToImmutableArray(); 
        internal set => RoleFlags = value.Aggregate((flags, role) => flags | role);
    }
    public Role RoleFlags { get; private set; }
}
```

```C#
internal sealed class ExampleConfiguration : IEntityTypeConfiguration<Example>
{
    public void Configure(EntityTypeBuilder<Example> example)
    {
        example.Ignore(e => e.Roles);
    }
}
```

```C#
[Flags]
public enum Role : byte
{
    Administrator = 1,
    Customer = 2
}
```

### Stack trace and verbose output

```
Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create a 'DbContext' of type 'PostgreSqlDataContext'. The exception 'Exception has been thrown by the target of an invocation.' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Reference equality is not defined for the types 'System.Collections.Immutable.ImmutableArray`1[Domain.Entities.Users.Role]' and 'System.Object'.
   at System.Linq.Expressions.Expression.ReferenceEqual(Expression left, Expression right)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.ValueConversion.NpgsqlArrayConverter`3.ArrayConversionExpression[TInput,TOutput,TConcreteOutput](LambdaExpression elementConversionExpression)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.ValueConversion.NpgsqlArrayConverter`3..ctor(ValueConverter elementConverter)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping.NpgsqlArrayTypeMapping`3.CreateParameters(String storeType, RelationalTypeMapping elementMapping)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping.NpgsqlArrayTypeMapping`3..ctor(String storeType, RelationalTypeMapping elementTypeMapping)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping.NpgsqlArrayTypeMapping`3..ctor(RelationalTypeMapping elementTypeMapping)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType, KeyValuePair`2 contextPair)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace, Boolean dryRun)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace, Boolean dryRun)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to create a 'DbContext' of type 'PostgreSqlDataContext'. The exception 'Exception has been thrown by the target of an invocation.' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
```

### Provider and version information

EF Core version: 9.0.0
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL 9.0.2
Target framework: .NET 9.0
Operating system: Windows 11 24H2
IDE: Visual Studio 2022 17.12.3

**Comment by AndriySvyryd** [comment]
How do you apply the configuration? Place a breakpoint in `ExampleConfiguration.Configure` and check that it's hit.

**Comment by ErroneousFatality** [comment]
It's hit.
I use `ModelBuilder.ApplyConfigurationFromAssembly(...);` to apply my configurations.

```
public sealed class PostgreSqlDataContext: DbContext
{
    // Entities
    public DbSet<Example> Examples => Set<Example>();

    // Constructors
    public PostgreSqlDataContext(DbContextOptions options) 
        : base(options) { }

    // Methods
    protected override void OnModelCreating(ModelBuilder model)
    {
        base.OnModelCreating(model);
        model.ApplyConfigurationsFromAssembly(typeof(DataContext).Assembly);
    }
}
```

**Comment by AndriySvyryd** [comment]
This seems to be Npgsql-specific. @roji can you take a look?

**Comment by roji** [comment]
Sorry this took so long to look at @ErroneousFatality.

This is indeed a problem in EFCore.PG. Your Roles property is a collection over a value-converted type (enum), meaning that an  NpgsqlArrayConverter is required; and that type makes some assumptions that its input and output arrays are reference types. 

The way EF's model building works, the property is first discovered and configured, and only then do your IEntityTypeConfigurations get processed, with the Ignore; that means that the property gets fully configured as a mapped property **before** it is ignored, and the NpgsqlArrayConverter exception breaks the entire process.

I've opened https://github.com/npgsql/efcore.pg/issues/3551 on the EFCore.PG side to fix NpgsqlArrayConverter to not throw, and have pushed a fix for 10. In the meantime, you can use ConfigureConventions instead to ignore all properties of a given type:

```c#
protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
{
    configurationBuilder.IgnoreAny<ImmutableArray<Role>>();
}
```

This works much earlier - before any properties are discovered - and therefore should fix the problem (it also removes the need to add an Ignore for each every property).
