### ISSUE TITLE
FromSQL test failure in VS

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#3537]
Happens only while running in VS - TestDriven.NET
commit 41ad57ad2f3755c5e35b51d939fab52b489ce738

```
Test 'Microsoft.Data.Entity.Sqlite.FunctionalTests.FromSqlQuerySqliteTest.From_sql_composed_with_nullable_predicate' failed:
    System.ArgumentNullException : Value cannot be null.
Parameter name: second
    at System.Linq.Enumerable.SequenceEqual[TSource](IEnumerable`1 first, IEnumerable`1 second, IEqualityComparer`1 comparer)
    at System.Linq.Enumerable.SequenceEqual[TSource](IEnumerable`1 first, IEnumerable`1 second)
    Storage\TypedRelationalValueBufferFactoryFactory.cs(40,0): at Microsoft.Data.Entity.Storage.TypedRelationalValueBufferFactoryFactory.CacheKey.Equals(CacheKey other)
    Storage\TypedRelationalValueBufferFactoryFactory.cs(52,0): at Microsoft.Data.Entity.Storage.TypedRelationalValueBufferFactoryFactory.CacheKey.Equals(Object obj)
    at System.Collections.Generic.ObjectEqualityComparer`1.Equals(T x, T y)
    at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
    Storage\TypedRelationalValueBufferFactoryFactory.cs(74,0): at Microsoft.Data.Entity.Storage.TypedRelationalValueBufferFactoryFactory.Create(IReadOnlyList`1 valueTypes, IReadOnlyList`1 indexMap)
    Query\Sql\DefaultQuerySqlGenerator.cs(88,0): at Microsoft.Data.Entity.Query.Sql.DefaultQuerySqlGenerator.CreateValueBufferFactory(IRelationalValueBufferFactoryFactory relationalValueBufferFactoryFactory, DbDataReader _)
    Query\Internal\CommandBuilder.cs(40,0): at Microsoft.Data.Entity.Query.Internal.CommandBuilder.<>c__DisplayClass9_0.<NotifyReaderCreated>b__0()
    at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Func`1 valueFactory)
    at System.Threading.LazyInitializer.EnsureInitialized[T](T& target, Func`1 valueFactory)
    Query\Internal\CommandBuilder.cs(37,0): at Microsoft.Data.Entity.Query.Internal.CommandBuilder.NotifyReaderCreated(DbDataReader dataReader)
    Query\Internal\QueryingEnumerable.cs(65,0): at Microsoft.Data.Entity.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
    Query\LinqOperatorProvider.cs(123,0): at Microsoft.Data.Entity.Query.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
    FromSqlQueryTestBase.cs(370,0): at Microsoft.Data.Entity.FunctionalTests.FromSqlQueryTestBase`1.From_sql_composed_with_nullable_predicate()
```

**Comment by rowanmiller** [comment]
@anpete already fixed this
