### ISSUE TITLE
Test failure after strong naming

### ISSUE THREAD

**Issue by cesarblum** [dotnet/efcore#3650]
I'm strong naming all of our packages.

When I strong name EF packages, I start getting a test failure on my machine. I need to get this sorted out so I can proceed with the strong naming, so I appreciate any help I can get from you guys.

Here's what fails:

```
info: Exec
info:   program: cmd
info:   commandline: /C dnx test
info:   workingdir: test\EntityFramework.Relational.Tests
xUnit.net DNX Runner (32-bit DNX 4.5.1)
  Discovering: EntityFramework.Relational.Tests
  Discovered:  EntityFramework.Relational.Tests
  Starting:    EntityFramework.Relational.Tests
    Microsoft.Data.Entity.Storage.RelationalCommandTest.Logs_commands_parameter_values_and_warnings(commandDelegate: Action`3 { Method = Void <get_CommandActions>b__11_2(Microsoft.Data.Entity.Storage.Internal.RelationalCommand, Boolean, Microsoft.Data.Entity.Storage.IRelationalConnection), Target = <>c { } }, diagnosticName: "ExecuteReader", async: False) [FAIL]
      Assert.Equal() Failure
                                     (pos 20)
      Expected: Executed DbCommand (0ms) [Parameters=[FirstParameter='17'], C···
      Actual:   Executed DbCommand (1ms) [Parameters=[FirstParameter='17'], C···
                                     (pos 20)
      Stack Trace:
        C:\Users\cesars\src\aspnet\EntityFramework\test\EntityFramework.Relational.Tests\Storage\RelationalCommandTest.cs(751,0): at Microsoft.Data.Entity.Storage.RelationalCommandTest.<Logs_commands_parameter_values_and_warnings>d__17.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.Data.Entity.Storage.RelationalCommandTest.Logs_commands_parameter_values_and_warnings(commandDelegate: Func`4 { Method = System.Threading.Tasks.Task <get_CommandActions>b__11_3(Microsoft.Data.Entity.Storage.Internal.RelationalCommand, Boolean, Microsoft.Data.Entity.Storage.IRelationalConnection), Target = <>c { } }, diagnosticName: "ExecuteNonQuery", async: True) [FAIL]
      Assert.Equal() Failure
                                     (pos 20)
      Expected: Executed DbCommand (0ms) [Parameters=[FirstParameter='17'], C···
      Actual:   Executed DbCommand (3ms) [Parameters=[FirstParameter='17'], C···
                                     (pos 20)
      Stack Trace:
        C:\Users\cesars\src\aspnet\EntityFramework\test\EntityFramework.Relational.Tests\Storage\RelationalCommandTest.cs(751,0): at Microsoft.Data.Entity.Storage.RelationalCommandTest.<Logs_commands_parameter_values_and_warnings>d__17.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.Data.Entity.Storage.RelationalCommandTest.Logs_commands_parameter_values_and_warnings(commandDelegate: Func`4 { Method = System.Threading.Tasks.Task <get_CommandActions>b__11_4(Microsoft.Data.Entity.Storage.Internal.RelationalCommand, Boolean, Microsoft.Data.Entity.Storage.IRelationalConnection), Target = <>c { } }, diagnosticName: "ExecuteScalar", async: True) [FAIL]
      Assert.Equal() Failure
                                     (pos 20)
      Expected: Executed DbCommand (0ms) [Parameters=[FirstParameter='17'], C···
      Actual:   Executed DbCommand (1ms) [Parameters=[FirstParameter='17'], C···
                                     (pos 20)
      Stack Trace:
        C:\Users\cesars\src\aspnet\EntityFramework\test\EntityFramework.Relational.Tests\Storage\RelationalCommandTest.cs(751,0): at Microsoft.Data.Entity.Storage.RelationalCommandTest.<Logs_commands_parameter_values_and_warnings>d__17.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.Data.Entity.Storage.RelationalCommandTest.Logs_commands_parameter_values_and_warnings(commandDelegate: Func`4 { Method = System.Threading.Tasks.Task <get_CommandActions>b__11_5(Microsoft.Data.Entity.Storage.Internal.RelationalCommand, Boolean, Microsoft.Data.Entity.Storage.IRelationalConnection), Target = <>c { } }, diagnosticName: "ExecuteReader", async: True) [FAIL]
      Assert.Equal() Failure
                                     (pos 20)
      Expected: Executed DbCommand (0ms) [Parameters=[FirstParameter='17'], C···
      Actual:   Executed DbCommand (1ms) [Parameters=[FirstParameter='17'], C···
                                     (pos 20)
      Stack Trace:
        C:\Users\cesars\src\aspnet\EntityFramework\test\EntityFramework.Relational.Tests\Storage\RelationalCommandTest.cs(751,0): at Microsoft.Data.Entity.Storage.RelationalCommandTest.<Logs_commands_parameter_values_and_warnings>d__17.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  Finished:    EntityFramework.Relational.Tests
=== TEST EXECUTION SUMMARY ===
   EntityFramework.Relational.Tests  Total: 475, Errors: 0, Failed: 4, Skipped: 0, Time: 1.238s
fail: Exit code 4 from cmd
```

**Comment by divega** [comment]
It doesn't sound like timing should be part of the tests baselines. If that was the case I would expect these tests to be very fragile even before. On the other hand it could be that strong naming is making everything slower :smile: 

@anpete any thoughts?

**Comment by smitpatel** [comment]
Try changing the assert to 
`Assert.EndsWith(
                @"ms) [Parameters=[FirstParameter='17'], CommandType='0', CommandTimeout='30']
Command Text",
                log[1].Item2);`
like in the `Logs_commands_parameter_values` test.
Since the difference is only in execution time, not sure if we should be asserting execution time.
@anpete - can give more info on it.

**Comment by cesarbs** [comment]
@divega Strong name verification does introduce a delay in loading assemblies, so that is very likely.

**Comment by divega** [comment]
Well, a delay in the loading of the assembly is a different thing from a delay in the query execution, but at this point it is all speculation. @rowanmiller we should check how our benchmarks react to this.

**Comment by anpete** [comment]
Sent PR with changes suggested by @smitpatel

**Comment by cesarbs** [comment]
Thanks @anpete. I'm going to make the same changes to release, since I'm working on that branch.
