### ISSUE TITLE
InvalidOperationException when validating relationship metadata on Windows Server 2012

### ISSUE THREAD

**Issue by jd-cz** [dotnet/efcore#3757]
EF version: `7.0.0-beta8`
Framework: `dnx451`
Store: `sqlServer`

Metadata validation in the following example results in exception when the code is executed on **Windows Server 2012R2** when hosted in **64-bit DNX** environment. The same code however executes without problems when running in 32-bit DNX on WinSrv2012R2 or when running on a Windows 8 development box (as both 32-bit and 64-bit).

Tried it on two Windows Server 2012R2 machines with different setups.

**Steps to reproduce:**
    - Open this repository: https://github.com/jd-cz/Issues/tree/master/src/EFMetadataIssue
    - Publish the project using the TEST publish profile
    - Run the published EFMetadataIssue.cmd on a Windows Server 2012R2 machine
    - An exception will be raised

Here's the exception:

```
System.InvalidOperationException: The navigation property 'Permissions' cannot be added to entity type 'EFMetadataIssue.GroupEntity' because its CLR type 'System.Collections.Generic.ICollection`1[[EFMetadataIssue.PermissionEntity, EFMetadataIssue, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' does not match the expected CLR type 'EFMetadataIssue.PermissionEntity'.
   at Microsoft.Data.Entity.Metadata.Navigation.IsCompatible(String navigationPropertyName, EntityType sourceType, EntityType targetType, Nullable`1 shouldBeCollection, Boolean shouldThrow)
   at Microsoft.Data.Entity.Metadata.ForeignKey.AreCompatible(EntityType principalEntityType, EntityType dependentEntityType, String navigationToPrincipalName, String navigationToDependentName, IReadOnlyList`1 dependentProperties, IReadOnlyList`1 principalProperties, Nullable`1 unique, Nullable`1 required, Boolean shouldThrow)
   at Microsoft.Data.Entity.Metadata.Internal.InternalEntityTypeBuilder.Relationship(InternalEntityTypeBuilder principalEntityTypeBuilder, InternalEntityTypeBuilder dependentEntityTypeBuilder, String navigationToPrincipalName, String navigationToDependentName, IReadOnlyList`1 dependentProperties, IReadOnlyList`1 principalProperties, ConfigurationSource configurationSource, Nullable`1 isUnique, Nullable`1 isRequired, Nullable`1 deleteBehavior, Boolean strictPrincipal, Func`2 onRelationshipAdding, Boolean runConventions)
   at Microsoft.Data.Entity.Metadata.Internal.InternalRelationshipBuilder.ReplaceForeignKey(InternalEntityTypeBuilder principalEntityTypeBuilder, InternalEntityTypeBuilder dependentEntityTypeBuilder,String navigationToPrincipalName, String navigationToDependentName, IReadOnlyList`1 dependentProperties, IReadOnlyList`1 principalProperties, Nullable`1 isUnique, Nullable`1 isRequired, Nullable`1 deleteBehavior, ForeignKeyAspect aspectsConfigured, ConfigurationSource configurationSource, Boolean runConventions)
   at Microsoft.Data.Entity.Metadata.Internal.InternalRelationshipBuilder.ReplaceForeignKey(ForeignKeyAspect aspectsConfigured, ConfigurationSource configurationSource, InternalEntityTypeBuilder principalEntityTypeBuilder, InternalEntityTypeBuilder dependentEntityTypeBuilder, IReadOnlyList`1 dependentProperties, IReadOnlyList`1 principalProperties, Nullable`1 isUnique, Nullable`1 isRequired, Nullable`1 deleteBehavior, Boolean runConventions)
   at Microsoft.Data.Entity.Metadata.Internal.InternalRelationshipBuilder.ForeignKey(IReadOnlyList`1 properties, ConfigurationSource configurationSource, Boolean runConventions)
   at Microsoft.Data.Entity.Metadata.Builders.ReferenceCollectionBuilder`2.ForeignKey(Expression`1 foreignKeyExpression)
   at Microsoft.Data.Entity.ModelBuilder.Entity[TEntity](Action`1 buildAction)
   at EFMetadataIssue.TestDataContext.OnModelCreating(ModelBuilder modelBuilder)
```

And here's the related code:

``` csharp
    public class GroupEntity
    {
        public Guid ID { get; set; }
        public ICollection<PermissionEntity> Permissions { get; set; }
    }

    public class PermissionEntity
    {
        public Guid GroupID { get; set; }
        public Guid FunctionReference { get; set; }
    }

    public class TestDataContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=localhost;Database=EFMetadataIssueDB;Trusted_Connection=True");

            base.OnConfiguring(optionsBuilder);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<PermissionEntity>(b =>
            {
                b.ToSqlServerTable("Permission");
                b.HasKey(ex => new { ex.GroupID, ex.FunctionReference });
            });

            modelBuilder.Entity<GroupEntity>(b =>
            {
                b.ToSqlServerTable("Group");
                b.HasKey(ex => ex.ID);
                b.HasMany(e => e.Permissions).WithOne().ForeignKey(e => e.GroupID);
            });      

            base.OnModelCreating(modelBuilder);
        }
    }
```

Related posts:
    - http://stackoverflow.com/questions/33542966/ef7-throws-argumentexception-after-set-deletebehavior-is-called-on-certain-machi
    - Issue https://github.com/aspnet/EntityFramework/issues/2451

**Comment by smitpatel** [comment]
This should be fixed in RC1 which got released today. Can you verify it?

**Comment by jd-cz** [comment]
I have verified that this issue no longer occurs in RC1.
Thank you!
