### ISSUE TITLE
sqlite3 not found on ubuntu 14.04

### ISSUE THREAD

**Issue by ab27** [dotnet/efcore#3794]
I was following the Getting Started on Linux for ef at https://ef.readthedocs.org/en/latest/getting-started/linux.html and when I run the command 

**$ dnx ef database update** 

i get the following error.

```
System.DllNotFoundException: Unable to load DLL 'sqlite3': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(IntPtr filename, Sqlite3Handle& ppDb, Int32 flags, IntPtr vfs)
   at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(String filename, Sqlite3Handle& ppDb, Int32 flags, String vfs)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.Data.Entity.Storage.RelationalConnection.Open()
   at Microsoft.Data.Entity.Storage.Internal.SqliteRelationalConnection.Open()
   at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.Execute[T](IRelationalConnection connection, Func`3 action, String executeMethod, Boolean openConnection, Boolean closeConnection)
   at Microsoft.Data.Entity.Migrations.HistoryRepository.Exists()
   at Microsoft.Data.Entity.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.Data.Entity.Design.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.Data.Entity.Commands.Program.Executor.Execute(Action action)
Unable to load DLL 'sqlite3': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
```

```
$ dnx --version
Microsoft .NET Execution environment
 Version:      1.0.0-rc1-16202
 Type:         CoreClr
 Architecture: x64
 OS Name:      Linux
 OS Version:   ubuntu 14.04
 Runtime Id:   ubuntu.14.04-x64
```

**Comment by rowanmiller** [comment]
@natemcmaster any thoughts on this one?

**Comment by natemcmaster** [comment]
It's a goofy quirk in the Ubuntu 14 packaging. See https://github.com/aspnet/Microsoft.Data.Sqlite#ubuntu. I'll add this to the tutorial since Ubuntu 14 is one of the most popular Linux distros.

**Comment by ab27** [comment]
Thank you. running the following command fixed the problem

$ sudo apt-get install libsqlite3-dev

**Comment by natemcmaster** [comment]
Added a note to the walkthrough https://github.com/aspnet/EntityFramework.Docs/issues/77
