### ISSUE TITLE
EF7 RC1 Not Connecting to Remote MSSQL Server

### ISSUE THREAD

**Issue by SimonOrdo** [dotnet/efcore#3798]
Using the VS2015 Server Explorer I can reach the remote MSSQL server instance.  Copying the connection string and adding it to the appsettings.json produces the following error when attempting any db connection from within the MVC 6 RC1 app:

SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)"

The server is reachable as I am able to connect via VS Server Explorer as well as SQL Server Management Studio.

Connection string:
"Data Source=DBSERVER\INSTANCE1;Initial Catalog=MyDb;User ID=ASPNET-Db-User;Password=thepassword"

**Comment by rowanmiller** [comment]
Could it be that you need to escape the `\` in your connections string? Either by putting an `@` at the start or escaping with a double slash.

**Comment by SimonOrdo** [comment]
Thanks for the quick reply.  
That's not the problem.  I am using the \\ and not the @.  Visual studio complains about the appsettings.json file format if you don't escape the slash and it doesn't allow the @ symbol at all.

**Comment by SimonOrdo** [comment]
Also, here is the stack, if it helps.

System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean withFailover)
   at System.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, TimeoutTimer timeout)
   at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, Boolean redirectedUserInstance)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Data.Entity.Storage.RelationalConnection.<OpenAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Data.Entity.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<MoveNext>d__8.MoveNext()
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:-1,State:0,Class:20

**Comment by rowanmiller** [comment]
@SimonOrdo any chance you could try connecting directly with `DbConnection` to see if it is something that EF is doing?

**Comment by SimonOrdo** [comment]
Oh, you clever programmer, you!  Same error.  So, I guess it's not an EF problem.  

SqlClient can't resolve the server name for some reason...  I'll keep looking for an answer.  Unfortunately none of the usual fixes are working.  :-/

**Comment by ErikEJ** [comment]
You could try connecting to the instance port, using  server,port

**Comment by rowanmiller** [comment]
@SimonOrdo you can open bugs against SQL Client in the https://github.com/dotnet/corefx/ repo

**Comment by SimonOrdo** [comment]
Thanks, I tried changing the connection string to specify the port and no dice.  I'll ask in the house of SQL see what they think. 

"Data Source=DBSERVER,1433;Initial Catalog=MyDb;User ID=ASPNET-Db-User;Password=thepassword"

**Comment by SimonOrdo** [comment]
FYI.  Out of morbid curiosity, I tried the same code in MVC 5 and it connects just fine.  I opened an issue at https://github.com/dotnet/corefx/issues/4586 .
