### ISSUE TITLE
Add migration target project no longer automatically picked up

### ISSUE THREAD

**Issue by HenryGarle** [dotnet/efcore#3835]
Hi,

Not entirely sure if perhaps my projects are missing something that would stop this process but from looking through the updated templates and examples I cant find anything that I am missing that would cause this error but it is always possible.

When trying to scaffold a clean migration from scratch today I was presented with the following error:

```
    System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
      at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
      at System.Reflection.RuntimeAssembly.get_DefinedTypes()
      at Microsoft.Data.Entity.Design.Internal.StartupInvoker..ctor(String startupAssemblyName, String environment)
      at Microsoft.Data.Entity.Design.DbContextOperations..ctor(ILoggerProvider loggerProvider, String assemblyName, String startupAssemblyName, String environment)
      at Microsoft.Data.Entity.Design.MigrationsOperations..ctor(ILoggerProvider loggerProvider, String assemblyName, String startupAssemblyName, String environment, String projectDir, String rootNamespace)
      at Microsoft.Data.Entity.Commands.Program.Executor.<>c__DisplayClass4_1.<.ctor>b__4()
      at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
      at Microsoft.Data.Entity.Commands.Program.Executor.<>c__DisplayClass6_0.<AddMigration>b__0()
      at Microsoft.Data.Entity.Commands.Program.Executor.Execute(Action action)
    Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
```

I initiated it the same as I always have by navigating a console window to the directory of the project and using:

```
dnx ef migrations add Initial
```

This has always detected the target project automatically and had no issues. I dug into EF a little to see what might be causing the problem and noticed that it was failing at https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Commands/Design/Internal/StartupInvoker.cs#L32 which lead me to believe that I may be missing something from my project but the project in question is a domain project with a bare bones Startup.cs but targeting the project directly seems to work as expected.

After a while fiddling I noticed that if I run the command with the project specified as follows it will scaffold correctly.

```
dnx ef migrations add Initial -p "Domain.Project.Here"
```

I am not sure if this is an intended change, something missing from my project or just plain old user error but thought it worth reporting.

One last thing to note is that if it was an intentional change that the help text for adding migrations still mentions that if no target project is specified it will use the current project.

**Comment by HenryGarle** [comment]
I just cleared out my migrations and attempted to recreate the problems I was having and now all project are working as expected without the need to specify the project. I have made no changes to my projects at all so I am at a loss as to why it has suddenly started working. I am going to close this issue and assume no one will ever read this but if someone does, perhaps outputting a better error message would be helpful.
