### ISSUE TITLE
Could not load the specified file.'EntityFramework.Relational.resources'

### ISSUE THREAD

**Issue by z2xlong** [dotnet/efcore#3903]
My application based on dnxcore50, ASP.NET 5 and EntityFramework.MicrosoftSqlServer 7.0.0-rc1-final, connect to MS SQL Server 2012.
The System.IO.FileNotFoundException always happens when I run my application, as follow:

```
info: Microsoft.Data.Entity.Storage.Internal.RelationalCommandBuilderFactory[1]
      Executed DbCommand (74ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [e].[Id], [e].[Name]
      FROM [Employee] AS [e]
fail: Microsoft.Data.Entity.Query.Internal.SqlServerQueryCompilationContextFactory[1]
      An exception occurred in the database while iterating the results of a query.
      System.IO.FileNotFoundException: Could not load the specified file.
      File name: 'EntityFramework.Relational.resources'
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
         at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.Execute[T](IRelationalConnection connection, Func`3 action, String executeMethod, Boolean openConnection, Boolean closeConnection)
         at System.Data.LocaleInterop.LCIDToLocaleName(UInt32 Locale, StringBuilder lpName, Int32 cchName, Int32 dwFlags)
         at Microsoft.Data.Entity.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
         at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
         at Microsoft.Data.Entity.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
```

It looks like db connected but could not iterate the records.
The dependency configurations like this：

```
"dependencies": {
    ...
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final"
  },
```

DbContext class:

```
using Microsoft.Data.Entity;

namespace CockpitWeb.Models
{
    public class CompanyContext:DbContext
    {
        public DbSet<Employee> Employees{get;set;}
    }
}
```

Model class:

```
using System;

namespace CockpitWeb.Models
{
    public class Employee
    {
        public Int64 Id{get;set;}

        public string Name{get;set;}
    }
}
```

How to fix it? Thanks a lot.

**Comment by rowanmiller** [comment]
Hey,

We aren't able to reproduce this from the information provided. Any chance you can provide the full project that we can run to see the error?

~Rowan

**Comment by kaa** [comment]
I noticed the same error message when I had forgotten to run migrations to create the table in my database (PostgreSQL).

Is the deeper problem that error messages for various conditions cannot be loaded from resources perhaps?

**Comment by rowanmiller** [comment]
We have not heard back with details of how to reproduce this issue. Feel free to re-open if you are able to supply these.

**Comment by betimd** [comment]
It's happening again to me (connected to a SQL Server 2012 in RDS AWS)
 "EntityFramework.Core": "7.0.0-rc1-final",
 "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
 "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final"

Complete exception:

Microsoft.Data.Entity.Query.Internal.SqlServerQueryCompilationContextFactory[1]
      An exception occurred in the database while iterating the results of a query.
      System.InvalidOperationException: There is already an open DataReader associated with this Connection which must be closed first.
        at System.Data.SqlClient.SqlCommand.ValidateCommand (System.String method, Boolean async) [0x00000] in <filename unknown>:0
        at System.Data.SqlClient.SqlCommand.ExecuteReader (CommandBehavior behavior) [0x00000] in <filename unknown>:0
        at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader (CommandBehavior behavior) [0x00000] in <filename unknown>:0
        at System.Data.Common.DbCommand.ExecuteReader () [0x00000] in <filename unknown>:0
        at (wrapper remoting-invoke-with-check) System.Data.Common.DbCommand:ExecuteReader ()
        at Microsoft.Data.Entity.Storage.Internal.RelationalCommand+<>c__DisplayClass17_0.<ExecuteReader>b__0 (System.Data.Common.DbCommand cmd, IRelationalConnection con) [0x00000] in <filename unknown>:0

**Comment by divega** [comment]
@betimd It seems the exception you are seeing only partially matches the exception that started this issue. 

In case it helps, "System.InvalidOperationException: There is already an open DataReader associated with this Connection which must be closed first." is expected when you try to execute a query that retrieves data on a connection before finishing consuming the results of the previous query. Depending on the code that is causing this it can be avoided by making sure you finish consuming the results from the first query, e.g. with `ToList()`. If you are using SQL Server you can also avoid this with the `MultipleActiveResultSets=true` setting on the connection string.

If this information doesn't help, please create a new issue and provide the necessary details for us to repro and investigate.
