### ISSUE TITLE
Can't remove migration because of empty navigation property

### ISSUE THREAD

**Issue by joshmouch** [dotnet/efcore#3911]
Hi,
I just created a migration then tried to remove it.  When I tried to remove it, I got a weird error, and I'm not really sure what's causing it:

The navigation property '' cannot be added to the entity type 'MyType' because a navigation property with the same name already exists on entity type 'MyType'.

Note the empty property name.
I was able to create the migration somehow... I just can't remove it.

Here are the 2 stack trace methods before the exception:

   at Microsoft.Data.Entity.Metadata.Builders.ReferenceNavigationBuilder.WithOneBuilder(String reference)
   at Microsoft.Data.Entity.Metadata.Builders.ReferenceNavigationBuilder.WithOne(String reference)

**Comment by joshmouch** [comment]
Unfortunately, I can't give more info that this because I reverted the migration folder to an earlier code state and then broke the multiple entity updates I had into multiple, smaller changes.
Doing it that way worked fine.
The only thing I can add is that the relationships were pretty complicated, and a couple of "ghost" columns were added to satisfy an FK (against my will).
