### ISSUE TITLE
Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection.

### ISSUE THREAD

**Issue by yuezhongxin** [dotnet/efcore#3922]
Exception message: 

```
Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddInstance(Microsoft.Extensions.DependencyInjection.IServiceCollection, !!0)'.

   at Microsoft.AspNet.Hosting.WebHostBuilder.BuildHostingServices()
   at Microsoft.AspNet.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNet.TestHost.TestServer..ctor(WebHostBuilder builder)
   at Microsoft.AspNet.TestHost.TestServer.Create(Action`1 configureApp, Action`1 configureServices)
```

![](http://images2015.cnblogs.com/blog/435188/201511/435188-20151130120921937-1704986014.png)

project.json:

``` json
{
  "version": "1.0.0-*",
  "description": "CNBlogs.Ad.BaseTests Class Library",
  "authors": [ "xishuai" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "frameworks": {
    "dnx451": { }
  },
  "dependencies": {
    "EntityFramework.Core": "7.0.0-rc2-16432",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc2-16432",
    "Microsoft.AspNet.TestHost": "1.0.0-rc1-final",
    "xunit": "2.1.0",
    "xunit.runner.dnx": "2.1.0-rc1-build204"
  },
  "commands": {
    "test": "xunit.runner.dnx"
  }
}
```

Because I use this version `7.0.0-rc1-final`, the emergence of this problem #3811, so I upgraded to this version `7.0.0-rc2-16432`, but it appeared the above problems.

If it alone unit testing, it works.

And the problem is also related: https://github.com/aspnet/Home/issues/1138

**Comment by yuezhongxin** [comment]
I modified `"Microsoft.AspNet.TestHost": "1.0.0-rc2-16032"`, it works.

https://github.com/aspnet/Home/issues/1138#issuecomment-160513322
