### ISSUE TITLE
'System.AggregateException' in mscorlib.dll

### ISSUE THREAD

**Issue by himadrinath** [dotnet/efcore#3923]
running mvc 6 in 1.0.0-rc1-final also have a Class Library added as reference in this project to maintain sqlserver data model with identity. after creating relationship between models and updating database every thing works fine. and then when i created a mvc form which has 3 entities one parent entity (Advertisement) and other two (Contact) and (CellPhone) both of them has  one-to-one relationship with entity (Advertisement)

<b>builder.Entity&#60;Advertisement&#62;()
          .HasOne(u => u.Contact)
          .WithOne(t => t.Advertisement)
          .HasForeignKey&#60;Contact&#62;(b=> b.pubID).IsRequired()
          .OnDelete(Microsoft.Data.Entity.Metadata.DeleteBehavior.Cascade);</b>

<b>builder.Entity&#60;Advertisement&#62;()
            .HasOne(u => u.CellPhone)
            .WithOne(u => u.Advertisement)
            .HasForeignKey&#60;CellPhone&#62;(b => b.pubID).IsRequired()
            .OnDelete(Microsoft.Data.Entity.Metadata.DeleteBehavior.Cascade);</b>

when i submitted a create form with this 3 entities its working fine. but when i try to edit with it. i getting an error.

<b>A database operation failed while processing the request.

AggregateException: One or more errors occurred. 
AggregateException: One or more errors occurred. 
AggregateException: One or more errors occurred. 
AggregateException: One or more errors occurred. 
AggregateException: One or more errors occurred. 
AggregateException: One or more errors occurred. 
AggregateException: One or more errors occurred. 
InvalidCastException: Specified cast is not valid. 
There are pending model changes for ApplicationDbContext
Scaffold a new migration for these changes and apply them to the database from the command line:

&#62; dnx ef migrations add [migration name] 
&#62; dnx ef database update
</b>

i run a trace with Sql Server Profiler. The query executing perfectly ok and getting the result as i expected but some how i getting this error. i don't under the reason behind it.

in my edit controller i run this command to get the data.

<b>Advertisement advertisement = await _context.Advertisements.Include(s=&#62; s.CellPhone).Include(s=&#62; s.Contact).SingleAsync(m =&#62; m.ID == id);</b>

and here is my Sql Server Profiler trace file

[AggregateExceptionTxt.txt](https://github.com/aspnet/EntityFramework/files/47070/AggregateExceptionTxt.txt)

when i  Include the contact entity in this query i getting this error if i only Include the CellPhone entity its working fine

**Comment by rowanmiller** [comment]
@himadrinath can you post the full stack trace from the error? The easiest way to get this is to comment out the `app.UseDatabaseErrorPage();` call in Startup.cs so that you get the full exception details.

**Comment by himadrinath** [comment]
@rowanmiller  [An unhandled exception occurred while processing the request.docx](https://github.com/aspnet/EntityFramework/files/57761/An.unhandled.exception.occurred.while.processing.the.request.docx)

**Comment by rowanmiller** [comment]
Stack trace copied out of the Word doc

```
InvalidCastException: Specified cast is not valid.
lambda_method(Closure , ValueBuffer )
Microsoft.Data.Entity.Query.EntityLoadInfo.Materialize()
Microsoft.Data.Entity.Query.Internal.QueryBuffer.GetEntity(IKeyValue keyValue, EntityLoadInfo entityLoadInfo, Boolean queryStateManager)
Microsoft.Data.Entity.Query.Internal.QueryBuffer.<>c__DisplayClass14_0.<<IncludeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
System.Linq.AsyncEnumerableExtensions.AsyncSelectEnumerable`2.AsyncSelectEnumerator.<MoveNext>d__3.MoveNext()


System.InvalidCastException: Specified cast is not valid.
   at lambda_method(Closure , ValueBuffer )
   at Microsoft.Data.Entity.Query.EntityLoadInfo.Materialize()
   at Microsoft.Data.Entity.Query.Internal.QueryBuffer.GetEntity(IKeyValue keyValue, EntityLoadInfo entityLoadInfo, Boolean queryStateManager)
   at Microsoft.Data.Entity.Query.Internal.QueryBuffer.<>c__DisplayClass14_0.<<IncludeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Linq.AsyncEnumerableExtensions.AsyncSelectEnumerable`2.AsyncSelectEnumerator.<MoveNext>d__3.MoveNext()
AggregateException: One or more errors occurred.


AggregateException: One or more errors occurred.
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
Microsoft.Data.Entity.Query.Internal.QueryBuffer.<IncludeAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.Data.Entity.Query.AsyncQueryMethodProvider.<>c__DisplayClass20_0`1.<<_Include>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
System.Linq.AsyncEnumerableExtensions.AsyncSelectEnumerable`2.AsyncSelectEnumerator.<MoveNext>d__3.MoveNext()


AggregateException: One or more errors occurred.


AggregateException: One or more errors occurred.
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
Microsoft.Data.Entity.Query.Internal.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()


AggregateException: One or more errors occurred.
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
Microsoft.Data.Entity.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()


AggregateException: One or more errors occurred.
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
Linklookr.Mvc.Controllers.CreateController.<Edit>d__7.MoveNext() in CreateController.cs
303.	            Advertisement advertisement = await _context.Advertisements.Include(q=> q.Contact).Include(s=> s.CellPhone).SingleAsync(m => m.ID == id);
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
Microsoft.AspNet.Mvc.Controllers.ControllerActionExecutor.<CastToObject>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker.<InvokeActionAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeActionFilterAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAsync>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler.<RouteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Mvc.Routing.InnerAttributeRoute.<RouteAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.IISPlatformHandler.IISPlatformHandlerMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

**Comment by rowanmiller** [comment]
@himadrinath can you share your model (entity classes and context). 

Looks like the error occurs while running this query:

```
Advertisement advertisement = await _context.Advertisements
    .Include(q=> q.Contact)
    .Include(s=> s.CellPhone)
    .SingleAsync(m => m.ID == id);
```

**Comment by himadrinath** [comment]
@rowanmiller 

[ApplicationDbContext.txt](https://github.com/aspnet/EntityFramework/files/59159/ApplicationDbContext.txt)
[Advertisement.txt](https://github.com/aspnet/EntityFramework/files/59160/Advertisement.txt)
[Contact.txt](https://github.com/aspnet/EntityFramework/files/59161/Contact.txt)
[CellPhone.txt](https://github.com/aspnet/EntityFramework/files/59162/CellPhone.txt)

**Comment by himadrinath** [comment]
@rowanmiller did u find something?

**Comment by rowanmiller** [comment]
@himadrinath I am not able to reproduce the issue. Here are the steps I followed:
* Created a new ASP.NET 5 web app (RC1) with Individual authentication enabled
* Replaced the existing ApplicationDbContext code with the code from ApplicationDbContext.txt
* Added Advertisement, Contact, and CellPhone entities from the code you supplied
* I had to add a `public List<Advertisement> Advertisement { get; set; }` property to the ApplicationUser class to get things to compile
* dnx ef migrations add Customization
* dnx ef database update
* Run the app and register a new user
* Create an Advertisement in the database (I used the following script)

```SQL
SET IDENTITY_INSERT [commercial].[advertisement] ON
GO

INSERT INTO [commercial].[advertisement]
           ([id]
		   ,[brand]
           ,[commercial]
           ,[condition]
           ,[description]
           ,[i_category]
           ,[ii_category]
           ,[ii_categoryID]
           ,[iii_category]
           ,[iii_categoryID]
           ,[price]
           ,[model]
           ,[proposal]
           ,[publisher]
           ,[terms_condition]
           ,[title]
           ,[user_id])
     VALUES
           (1
           ,'abc'
           ,'abc'
           ,'abc'
           ,'abc'
           ,'abc'
           ,'abc'
           ,1
           ,'abc'
           ,1
           ,1.45
           ,'abc'
           ,'abc'
           ,'abc'
           ,1
           ,'abc'
           ,(SELECT TOP 1 Id from dbo.AspNetUsers))
GO
```

* Modify HomeController constructor and Index action as follows

```c#
    public class HomeController : Controller
    {
        private ApplicationDbContext _context;

        public HomeController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var id = 2;

            Advertisement advertisement = await _context.Advertisements
                .Include(q => q.Contact)
                .Include(s => s.CellPhone)
                .SingleAsync(m => m.ID == id);

            return View();
        }

...
```

* Run the app (hits the code in the Index action by default)

This succeeds for me and the Advertisement is correctly returned from the database. Can you provide a set of detailed steps (similar to the ones above) that we can use to reproduce the issue.

**Comment by rowanmiller** [comment]
If it is easier.. then a project that we can use to reproduce the issue is fine too.

**Comment by rowanmiller** [comment]
Closing as we have not heard back. Feel free to reopen if you are able to provide code to reproduce.

**Comment by himadrinath** [comment]
@rowanmiller 

https://onedrive.live.com/redir?resid=59E7053C8A397BB0!3765&authkey=!APGsit2pCEQJDgc&ithint=folder%2csln

Database attached with it.

Go to Create and try to edit

**Comment by rowanmiller** [comment]
Hey,

`Contact.Longitude` and `Contact.Latitude` are defined as the .NET `float` type, which by default EF would map to a column with the SQL Server `real` type. The problem is that you have explicitly set the data type of the column to the SQL Server `float` type, but that is not compatible with the .NET `float` type ([see this post for more details](http://stackoverflow.com/questions/122523/why-is-a-sql-float-different-from-a-c-sharp-float)).

If you specify an explicit column type then EF will just trust you and try to do the conversion. The error you get is the same error if you try and use SQL Client to put the value of a SQL Server `float` column into a .NET `float` variable.

If I change the properties in the Contact class to be `double` (the .NET equivalent of SQL Server's `float`) then everything works as expected.

~Rowan

**Comment by himadrinath** [comment]
@rowanmiller

Thank you.......

**Comment by rowanmiller** [comment]
Opened https://github.com/aspnet/EntityFramework/issues/4289 to look at providing better errors in a way that does not adversely impact perf.
