### ISSUE TITLE
Using Guid as PK

### ISSUE THREAD

**Issue by RonFrick** [dotnet/efcore#3950]
I am running into an issue using Guid as a primary key in SQLite. Is this not supported?
Can you modify the connection string like so? BinaryGUID=False;

Here is the error and stack. {"Byte array for GUID must be exactly 16 bytes long."}

   at System.Linq.Expressions.Interpreter.ByRefMethodInfoCallInstruction.Run(InterpretedFrame frame)
   at System.Linq.Expressions.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Linq.Expressions.Interpreter.LightLambda.Run(Object[] arguments)
   at Thunk(Func`2 , DbDataReader )
   at Microsoft.Data.Entity.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.Data.Entity.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__1`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.Data.Entity.Query.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

**Comment by RonFrick** [comment]
I can post a repro if need be...

**Comment by RonFrick** [comment]
"BinaryGuid=False" I keep coming across this. Is there some way to modify the connection string using SQLite?

**Comment by RonFrick** [comment]
Additional information: Keyword not supported: 'binaryguid' is what I got when trying to modify the con string.

**Comment by RonFrick** [comment]
Stumped...  #ShowStopper 

An exception of type 'System.ArgumentException' occurred in System.Data.Common.dll but was not handled in user code

Additional information: Keyword not supported: 'binaryguid'.

**Comment by natemcmaster** [comment]
`BinaryGuid=False` is not an available option in your connection string in EF7.Sqlite. This is a feature of [System.Data.Sqlite](http://system.data.sqlite.org/index.html/doc/trunk/www/index.wiki). EF.SQlite uses instead [Microsoft.Data.Sqlite](https://github.com/aspnet/Microsoft.Data.Sqlite) under the hood.

**Comment by natemcmaster** [comment]
**For triage:** we should still make sure materializing a `Guid` works. This could be a problem with using SQLite column "STRING" instead of "BLOB".

**Comment by RonFrick** [comment]
I will setup a quick project to show the problem. Thanks for the help!

**Comment by RonFrick** [comment]
Here is a sample project. Thanks

https://onedrive.live.com/redir?resid=2007BE185CE30E96!3051&authkey=!AMXE6qzDfBjWT10&ithint=file%2czip

**Comment by rowanmiller** [comment]
Moved to https://github.com/aspnet/Microsoft.Data.Sqlite/issues/191

**Comment by RonFrick** [comment]
I have my own version of Microsoft.Data.Sqlite to fix the problem, and I can now query the data just fine, but now when I save a guid it saves as binary and not text. This is causing problems when trying to query the data once it is saved.
