### ISSUE TITLE
build initialize doesn't work

### ISSUE THREAD

**Issue by rosieks** [dotnet/efcore#3964]
I tried to compile source on my local machine but I receive the following error:

```
E:\projects\ef7>build initialize
Determining latest version
'dnx-coreclr-win-x86.1.0.0-rc2-16253' is already installed in C:\Users\Sławek\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-rc2-16253.
Adding C:\Users\Sławek\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-rc2-16253\bin to process PATH
Updating alias 'default' to 'dnx-coreclr-win-x86.1.0.0-rc2-16253'
'dnx-clr-win-x86.1.0.0-rc2-16253' is already installed in C:\Users\Sławek\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-16253.
Adding C:\Users\Sławek\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-16253\bin to process PATH
Updating alias 'default' to 'dnx-clr-win-x86.1.0.0-rc2-16253'
info: Build v2: False
info: Exec
info:   program: cmd
info:   commandline: /C dnu restore  --parallel
info:   workingdir: E:\projects\ef7
'dnu' is not recognized as an internal or external command,
operable program or batch file.
fail: Exit code 1 from cmd
fail: Stack trace:
   at Viewbff75adb127a4917a716cc8fbe694244.<RenderViewLevel0>b__ca() in c:\Users\Sławek\AppData\Local\Temp\963a4756c7a54f0d8b559f16288b248e-1.cs:line 10073
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at Viewbff75adb127a4917a716cc8fbe694244.StartingTarget(String name) in c:\Users\Sławek\AppData\Local\Temp\963a4756c7a54f0d8b559f16288b248e-1.cs:line 3740
   at Viewbff75adb127a4917a716cc8fbe694244.<RenderViewLevel0>b__89() in c:\Users\Sławek\AppData\Local\Temp\963a4756c7a54f0d8b559f16288b248e-1.cs:line 4315
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)
```

When I try to call dnu directly from console it works

**Comment by rowanmiller** [comment]
@rosieks can you `git clean -fdx` your local repo and try again - we have seen this failure from time to time.

**Comment by rosieks** [comment]
Unfortunately it doesn't help. Still the same error

**Comment by smitpatel** [comment]
dnu lives in the runtime installation directory and that directory is added to the process PATH. Can you check there is dnu present in the runtime installation folder (i.e. `C:\Users\Sławek\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-16253\bin`)?

**Comment by rosieks** [comment]
Yes, it's present. And when I use it directly from console it works

**Comment by rowanmiller** [comment]
Can you try running `dnvm use default -p` and see if that rectifies the issue?

**Comment by rosieks** [comment]
Still the same

**Comment by smitpatel** [comment]
Could be issue because of the special character in the username?

**Comment by rowanmiller** [comment]
Closing this out as we are in the process of moving to a completely new build system for RC2 (.NET CLI)
