### ISSUE TITLE
Possible regression in query that concatenates string + int

### ISSUE THREAD

**Issue by HaoK** [dotnet/efcore#4000]
https://github.com/aspnet/Identity/blob/dev/test/Microsoft.AspNet.Identity.EntityFramework.Test/DefaultPocoTest.cs#L171

Failing on CI, starting today as of build on 12/7 @ 9 am

```
System.Data.SqlClient.SqlException : Conversion failed when converting the varchar value 'Admin' to data type int.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.Read()
   at Microsoft.Data.Entity.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at Microsoft.Data.Entity.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at Microsoft.Data.Entity.Query.QueryMethodProvider.<_Include>d__23`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at lambda_method(Closure , QueryContext )
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass19_1`1.<CompileQuery>b__1(QueryContext qc)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at Microsoft.AspNet.Identity.EntityFramework.Test.DefaultPocoTest.<CanIncludeUserRolesTest>d__9.MoveNext() in C:\ba\e70224f4ea5e88a1\Identity\test\Microsoft.AspNet.Identity.EntityFramework.Test\DefaultPocoTest.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by divega** [comment]
I think the line moved to this: 

https://github.com/aspnet/Identity/blob/dev/test/Microsoft.AspNet.Identity.EntityFramework.Test/DefaultPocoTest.cs#L181

**Comment by divega** [comment]
Query looks like this:

``` C#
var role = dbContext.Roles.Include(r => r.Users).FirstOrDefault(r => r.Name == (roleName + i));
```

**Comment by maumar** [comment]
Fixed in 244c06dffdbee52f1e450b4f5192975a8d33cd6b

**Comment by divega** [comment]
@pranavkm @dougbu you should now be able to unmute the identity test that was failing.

**Comment by dougbu** [comment]
This may fix the reported issue but the test isn't working:
```
System.Data.SqlClient.SqlException : Could not obtain exclusive lock on database 'model'. Retry the operation later.
CREATE DATABASE failed. Some file names listed could not be created. Check related errors.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, Boolean openConnection, Boolean closeConnection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, Boolean manageConnection)
   at Microsoft.Data.Entity.Storage.Internal.RelationalCommandExtensions.ExecuteNonQuery(IEnumerable`1 commands, IRelationalConnection connection)
   at Microsoft.Data.Entity.Storage.Internal.SqlServerDatabaseCreator.Create()
   at Microsoft.Data.Entity.Storage.RelationalDatabaseCreator.EnsureCreated()
   at Microsoft.Data.Entity.Infrastructure.DatabaseFacade.EnsureCreated()
   at Microsoft.AspNet.Identity.EntityFramework.Test.DefaultPocoTest.CreateContext(Boolean ensureCreated) in C:\BuildAgent\ba\e70224f4ea5e88a1\Identity\test\Microsoft.AspNet.Identity.EntityFramework.Test\DefaultPocoTest.cs:line 26
   at Microsoft.AspNet.Identity.EntityFramework.Test.DefaultPocoTest.<CanIncludeRoleClaimsTest>d__10.MoveNext() in C:\BuildAgent\ba\e70224f4ea5e88a1\Identity\test\Microsoft.AspNet.Identity.EntityFramework.Test\DefaultPocoTest.cs:line 195
```
Same thing for `UserStoreGuidTest.AddDupeEmailAllowedByDefault`. That stack trace goes up to:
```
...
   at Microsoft.AspNet.Identity.EntityFramework.Test.SqlStoreTestBase`3.CreateContext(Boolean delete) in C:\BuildAgent\ba\e70224f4ea5e88a1\Identity\test\Microsoft.AspNet.Identity.EntityFramework.Test\SqlStoreTestBase.cs:line 95
   at Microsoft.AspNet.Identity.EntityFramework.Test.SqlStoreTestBase`3.CreateTestContext() in C:\BuildAgent\ba\e70224f4ea5e88a1\Identity\test\Microsoft.AspNet.Identity.EntityFramework.Test\SqlStoreTestBase.cs:line 101
   at Microsoft.AspNet.Identity.Test.UserManagerTestBase`3.CreateManager(Object context, IServiceCollection services, Action`1 configureServices) in C:\BuildAgent\ba\e70224f4ea5e88a1\Identity\test\Shared\UserManagerTestBase.cs:line 64
   at Microsoft.AspNet.Identity.Test.UserManagerTestBase`3.<AddDupeEmailAllowedByDefault>d__44.MoveNext() in C:\BuildAgent\ba\e70224f4ea5e88a1\Identity\test\Shared\UserManagerTestBase.cs:line 711
```

Who should be assigned this latest failure? Do you need another bug to track it?
