### ISSUE TITLE
LEFT OUTER JOIN Problems!

### ISSUE THREAD

**Issue by mkelley82** [dotnet/efcore#4002]
I am trying to reproduce the following SQL query using EF RC1:

```
SELECT [t0].[Name], [t0].[Ranking], [t2].[Name] AS [AccountManager]
FROM [District] AS [t0]
LEFT OUTER JOIN [CommodityBalance] AS [t1] ON [t1].[DistrictId] = ([t0].[Id])
LEFT OUTER JOIN [AccountManager] AS [t2] ON [t2].[Id] = [t0].[AccountManagerId]
WHERE [t1].[DistrictId] IS NULL
ORDER BY [t0].[Ranking]
```

I have tried the following:

```
from d in _ctx.District 
from c in _ctx.CommodityBalance.Where(c => c.DistrictId == d.Id).DefaultIfEmpty()
where c.DistrictId == null
orderby d.Ranking
select new {  d.Name, d.Ranking, AccountManager = d.AccountManager.Name }
```

It produces the following exception:

```
Exception thrown: 'System.NullReferenceException' in System.Core.dll
Microsoft.Data.Entity.Query.Internal.SqlServerQueryCompilationContextFactory: Error: An     exception occurred in the database while iterating the results of a query.
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , TransparentIdentifier`2 )
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.Data.Entity.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
```

I have also tried:

```
District
   .SelectMany (
      d => 
         CommodityBalance
            .Where (c => (c.DistrictId == (Int32?)(d.Id)))
            .DefaultIfEmpty (), 
       (d, c) => 
          new  
          {
             d = d, 
             c = c
          }
    )
    .Where (temp0 => (temp0.c.DistrictId == null))
    .OrderBy (temp0 => temp0.d.Ranking)
    .Select (
       temp0 => 
          new  
          {
             Name = temp0.d.Name, 
             Ranking = temp0.d.Ranking, 
             AccountManager = temp0.d.AccountManager.Name
          }
    )
```

... and I get the same exception.  Both of these queries work as expected in LINQPad...

**Comment by ctolkien** [comment]
Possibly related to https://github.com/aspnet/EntityFramework/issues/3982 ?

**Comment by MaximBalaganskiy** [comment]
covered by this one
https://github.com/aspnet/EntityFramework/issues/3263

**Comment by rowanmiller** [comment]
The `NullReferenceException` is due to this part of the query `where c.DistrictId == null`. Since `c` is brought in as a left outer join (using `DefaultIfEmpty()`), `c` can be null. Therefore, you would need to add a null check before trying to access a property of `c` - `where c == null || c.DistrictId == null`.

This isn't specific to EF and would be true if you were using LINQ against in-memory objects too.

BTW when you add in the null check, you will then start getting an `InvalidCastException` due to #3982 - which has been fixed in our current code base.
