### ISSUE TITLE
Getting "System.ArgumentNullException: Value cannot be null.  Parameter name entityTypeBuilder" in RC2-16485

### ISSUE THREAD

**Issue by emrs-jm** [dotnet/efcore#4028]
I have a project a and a test project that uses my model that cannot run context.Database.EnsureDeleted() without crashing with the following error: System.ArgumentNullException: Value cannot be null.  Parameter name entityTypeBuilder.

The model works in Beta 8, but throws an "InvalidOperationException: The derived type 'x' cannot have keys other than those declared on the root type." in RC1-final.  I decided to try a RC2 nightly build since this issue seemed to be something that happened potentially related to one of the other issues where the bug appeared to be fixed #3727 and one not fixed #3863.  I can send a smaller project that has this issue but I would want to send it directly since our model is closed.  

Some additional background is that a subset of the model seemed to work in RC1-final, but it stopped working when I included the rest of model.

**Comment by smitpatel** [comment]
Can you post full stack trace?

**Comment by Ph47** [comment]
Have similar bug.

  	EntityFramework.Core.dll!Microsoft.Data.Entity.Utilities.Check.NotNull<System.__Canon>(System.__Canon value, string parameterName)	Unknown
 	EntityFramework.Core.dll!Microsoft.Data.Entity.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.Apply(Microsoft.Data.Entity.Metadata.Internal.InternalEntityTypeBuilder entityTypeBuilder)	Unknown
 	EntityFramework.Core.dll!Microsoft.Data.Entity.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.ApplyOnRelatedEntityTypes(Microsoft.Data.Entity.Metadata.Internal.InternalModelBuilder modelBuilder, Microsoft.Data.Entity.Metadata.Internal.EntityType entityType)	Unknown
 	EntityFramework.Core.dll!Microsoft.Data.Entity.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.Apply(Microsoft.Data.Entity.Metadata.Internal.InternalEntityTypeBuilder entityTypeBuilder, Microsoft.Data.Entity.Metadata.Internal.EntityType oldBaseType)	Unknown
 	EntityFramework.Core.dll!Microsoft.Data.Entity.Metadata.Conventions.Internal.ConventionDispatcher.OnBaseEntityTypeSet(Microsoft.Data.Entity.Metadata.Internal.InternalEntityTypeBuilder entityTypeBuilder, Microsoft.Data.Entity.Metadata.Internal.EntityType previousBaseType)	Unknown
 	EntityFramework.Core.dll!Microsoft.Data.Entity.Metadata.Internal.InternalEntityTypeBuilder.HasBaseType(Microsoft.Data.Entity.Metadata.Internal.EntityType baseEntityType, Microsoft.Data.Entity.Metadata.Internal.ConfigurationSource configurationSource)	Unknown
 	EntityFramework.Core.dll!Microsoft.Data.Entity.Metadata.Internal.InternalModelBuilder.Ignore(Microsoft.Data.Entity.Metadata.Internal.EntityType entityType, Microsoft.Data.Entity.Metadata.Internal.ConfigurationSource configurationSource)	Unknown
 	EntityFramework.Core.dll!Microsoft.Data.Entity.Metadata.Internal.InternalModelBuilder.RemoveEntityTypesUnreachableByNavigations(Microsoft.Data.Entity.Metadata.Internal.ConfigurationSource configurationSource)	Unknown
 	EntityFramework.Core.dll!Microsoft.Data.Entity.Metadata.Conventions.Internal.ModelCleanupConvention.Apply(Microsoft.Data.Entity.Metadata.Internal.InternalModelBuilder modelBuilder)	Unknown
 	EntityFramework.Core.dll!Microsoft.Data.Entity.Metadata.Conventions.Internal.ConventionDispatcher.OnModelBuilt(Microsoft.Data.Entity.Metadata.Internal.InternalModelBuilder modelBuilder)	Unknown
 	EntityFramework.Core.dll!Microsoft.Data.Entity.Metadata.Internal.Model.Validate()	Unknown
 	EntityFramework.Core.dll!Microsoft.Data.Entity.Metadata.Internal.InternalModelBuilder.Validate()	Unknown
 	EntityFramework.Core.dll!Microsoft.Data.Entity.Infrastructure.ModelSource.CreateModel(Microsoft.Data.Entity.DbContext context, Microsoft.Data.Entity.Metadata.Conventions.Internal.IConventionSetBuilder conventionSetBuilder, Microsoft.Data.Entity.Internal.IModelValidator validator)	Unknown
 	EntityFramework.Core.dll!Microsoft.Data.Entity.Infrastructure.ModelSource.GetModel.AnonymousMethod__0(System.Type k)	Unknown
 	mscorlib.dll!System.Collections.Concurrent.ConcurrentDictionary<System.Type, Microsoft.Data.Entity.Metadata.IModel>.GetOrAdd(System.Type key, System.Func<System.Type, Microsoft.Data.Entity.Metadata.IModel> valueFactory)	Unknown
 	EntityFramework.Core.dll!Microsoft.Data.Entity.Infrastructure.ModelSource.GetModel(Microsoft.Data.Entity.DbContext context, Microsoft.Data.Entity.Metadata.Conventions.Internal.IConventionSetBuilder conventionSetBuilder, Microsoft.Data.Entity.Internal.IModelValidator validator)	Unknown
 	EntityFramework.Core.dll!Microsoft.Data.Entity.Internal.DbContextServices.CreateModel()	Unknown
 	EntityFramework.Core.dll!Microsoft.Data.Entity.Internal.LazyRef<Microsoft.Data.Entity.Metadata.IModel>.Value.get()	Unknown
 	EntityFramework.Core.dll!Microsoft.Data.Entity.Internal.DbContextServices.Model.get()	Unknown
 	EntityFramework.Core.dll!Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.AddEntityFramework.AnonymousMethod__0_5(System.IServiceProvider p)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.RealizeService.AnonymousMethod__0(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(System.Type serviceType)	Unknown
 	Microsoft.Extensions.DependencyInjection.Abstractions.dll!Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetService<Microsoft.Data.Entity.ChangeTracking.Internal.INavigationFixer>(System.IServiceProvider provider)	Unknown
 	EntityFramework.Core.dll!Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.AddEntityFramework.AnonymousMethod__0_0(System.IServiceProvider p)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.ClosedIEnumerableService.CallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.RealizeService.AnonymousMethod__0(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(System.Type serviceType)	Unknown
 	Microsoft.Extensions.DependencyInjection.Abstractions.dll!Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(System.IServiceProvider provider, System.Type serviceType)	Unknown
 	Microsoft.Extensions.DependencyInjection.Abstractions.dll!Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService<Microsoft.Data.Entity.Query.Internal.RelationalQueryContextFactory>(System.IServiceProvider provider)	Unknown
 	EntityFramework.Core.dll!Microsoft.Data.Entity.Storage.DatabaseProviderServices.GetService<Microsoft.Data.Entity.Query.Internal.RelationalQueryContextFactory>()	Unknown
 	EntityFramework.Relational.dll!Microsoft.Data.Entity.Storage.RelationalDatabaseProviderServices.QueryContextFactory.get()	Unknown
 	EntityFramework.Core.dll!Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.AddQuery.AnonymousMethod__1_1(System.IServiceProvider p)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.RealizeService.AnonymousMethod__0(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(System.Type serviceType)	Unknown
 	Microsoft.Extensions.DependencyInjection.Abstractions.dll!Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(System.IServiceProvider provider, System.Type serviceType)	Unknown
 	Microsoft.Extensions.DependencyInjection.Abstractions.dll!Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService<Microsoft.Data.Entity.Query.Internal.IAsyncQueryProvider>(System.IServiceProvider provider)	Unknown
 	EntityFramework.Core.dll!Microsoft.Data.Entity.Infrastructure.AccessorExtensions.GetService<Microsoft.Data.Entity.Query.Internal.IAsyncQueryProvider>(Microsoft.Data.Entity.Infrastructure.IInfrastructure<System.IServiceProvider> accessor)	Unknown
 	EntityFramework.Core.dll!Microsoft.Data.Entity.Internal.InternalDbSet<Ventura.Subsystems.Integration.Import.ImportTask>..ctor.AnonymousMethod__2_0()	Unknown
 	EntityFramework.Core.dll!Microsoft.Data.Entity.Internal.LazyRef<Microsoft.Data.Entity.Query.Internal.EntityQueryable<Ventura.Subsystems.Integration.Import.ImportTask>>.Value.get()	Unknown
 	EntityFramework.Core.dll!Microsoft.Data.Entity.Internal.InternalDbSet<System.__Canon>.System.Linq.IQueryable.Provider.get()	Unknown
 	System.Core.dll!System.Linq.Queryable.FirstOrDefault<Ventura.Subsystems.Integration.Import.ImportTask>(System.Linq.IQueryable<Ventura.Subsystems.Integration.Import.ImportTask> source, System.Linq.Expressions.Expression<System.Func<Ventura.Subsystems.Integration.Import.ImportTask, bool>> predicate)	Unknown
	Web!Ventura.Model.Repository.Base.EntityRepository<Ventura.Subsystems.Integration.Import.ImportTask>.Get(System.Guid id) Line 35	C#
 	Web!Ventura.Subsystems.Background.BackgroundWorker.RunImportTask(System.Guid id) Line 24	C#
 	Web!Ventura.Subsystems.Background.BackgroundWorker.RunTask(System.Guid id, string typeName) Line 37	C#
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Hangfire.Core.dll!Hangfire.Server.CoreBackgroundJobPerformer.InvokeMethod(System.Reflection.MethodInfo methodInfo, object instance, object[] arguments)	Unknown
 	Hangfire.Core.dll!Hangfire.Server.CoreBackgroundJobPerformer.Perform(Hangfire.Server.PerformContext context)	Unknown
 	Hangfire.Core.dll!Hangfire.Server.BackgroundJobPerformer.PerformJobWithFilters.AnonymousMethod__0()	Unknown
 	Hangfire.Core.dll!Hangfire.Server.BackgroundJobPerformer.InvokePerformFilter(Hangfire.Server.IServerFilter filter, Hangfire.Server.PerformingContext preContext, System.Func<Hangfire.Server.PerformedContext> continuation)	Unknown
 	Hangfire.Core.dll!Hangfire.Server.BackgroundJobPerformer.PerformJobWithFilters.AnonymousMethod__2()	Unknown
 	Hangfire.Core.dll!Hangfire.Server.BackgroundJobPerformer.PerformJobWithFilters(Hangfire.Server.PerformContext context, System.Collections.Generic.IEnumerable<Hangfire.Server.IServerFilter> filters)	Unknown
 	Hangfire.Core.dll!Hangfire.Server.BackgroundJobPerformer.Perform(Hangfire.Server.PerformContext context)	Unknown
 	Hangfire.Core.dll!Hangfire.Server.Worker.PerformJob(Hangfire.Server.BackgroundProcessContext context, Hangfire.Storage.IStorageConnection connection, string jobId)	Unknown
 	Hangfire.Core.dll!Hangfire.Server.Worker.Execute(Hangfire.Server.BackgroundProcessContext context)	Unknown
 	Hangfire.Core.dll!Hangfire.Server.ServerProcessExtensions.Execute(Hangfire.Server.IServerProcess process, Hangfire.Server.BackgroundProcessContext context)	Unknown
 	Hangfire.Core.dll!Hangfire.Server.AutomaticRetryProcess.Execute(Hangfire.Server.BackgroundProcessContext context)	Unknown
 	Hangfire.Core.dll!Hangfire.Server.ServerProcessExtensions.Execute(Hangfire.Server.IServerProcess process, Hangfire.Server.BackgroundProcessContext context)	Unknown
 	Hangfire.Core.dll!Hangfire.Server.InfiniteLoopProcess.Execute(Hangfire.Server.BackgroundProcessContext context)	Unknown
 	Hangfire.Core.dll!Hangfire.Server.ServerProcessExtensions.Execute(Hangfire.Server.IServerProcess process, Hangfire.Server.BackgroundProcessContext context)	Unknown
 	Hangfire.Core.dll!Hangfire.Server.ServerProcessExtensions.RunProcess(Hangfire.Server.IServerProcess process, Hangfire.Server.BackgroundProcessContext context)	Unknown
 	Hangfire.Core.dll!Hangfire.Server.ServerProcessExtensions.CreateTask.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.InnerInvoke()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.Execute()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution)	Unknown
 	mscorlib.dll!System.Threading.Tasks.ThreadPoolTaskScheduler.LongRunningThreadWork(object obj)	Unknown
 	mscorlib.dll!System.Threading.ThreadHelper.ThreadStart_Context(object state)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	mscorlib.dll!System.Threading.ThreadHelper.ThreadStart(object obj)	Unknown

**Comment by emrs-jm** [comment]
I tried to send an email as to see if I can send you the test project with my model that is failing.  That way you can get the full error with all the states on your side.  I just can't post the model here since it is based off a production model at work that I cannot put on a public issue forum.

In the meantime, here is the stack trace that I have.  
```
at Microsoft.Data.Entity.Utilities.Check.NotNull[T](T value, String parameterName)
at Microsoft.Data.Entity.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.Apply(InternalEntityTypeBuilder entityTypeBuilder)
at Microsoft.Data.Entity.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.ApplyOnRelatedEntityTypes(InternalModelBuilder modelBuilder, EntityType entityType)
at Microsoft.Data.Entity.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.Apply(InternalEntityTypeBuilder entityTypeBuilder, EntityType oldBaseType)
at Microsoft.Data.Entity.Metadata.Conventions.Internal.ConventionDispatcher.OnBaseEntityTypeSet(InternalEntityTypeBuilder entityTypeBuilder, EntityType previousBaseType)
at Microsoft.Data.Entity.Metadata.Internal.InternalEntityTypeBuilder.HasBaseType(EntityType baseEntityType, ConfigurationSource configurationSource)
at Microsoft.Data.Entity.Metadata.Internal.InternalModelBuilder.Ignore(EntityType entityType, ConfigurationSource configurationSource)
at Microsoft.Data.Entity.Metadata.Internal.InternalModelBuilder.RemoveEntityTypesUnreachableByNavigations(ConfigurationSource configurationSource)
at Microsoft.Data.Entity.Metadata.Conventions.Internal.ModelCleanupConvention.Apply(InternalModelBuilder modelBuilder)
at Microsoft.Data.Entity.Metadata.Conventions.Internal.ConventionDispatcher.OnModelBuilt(InternalModelBuilder modelBuilder)
at Microsoft.Data.Entity.Metadata.Internal.Model.Validate()
at Microsoft.Data.Entity.Metadata.Internal.InternalModelBuilder.Validate()
at Microsoft.Data.Entity.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
at Microsoft.Data.Entity.Infrastructure.ModelSource.<>c__DisplayClass8_0.<GetModel>b__0(Type k)
at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
at Microsoft.Data.Entity.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
at Microsoft.Data.Entity.Internal.DbContextServices.CreateModel()
at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
at Microsoft.Data.Entity.Internal.DbContextServices.get_Model()
at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_5(IServiceProvider p)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
at Microsoft.Data.Entity.Storage.DatabaseProviderServices.GetService[TService]()
at Microsoft.Data.Entity.Storage.DatabaseProviderServices.get_QueryCompilationContextFactory()
at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c.<AddQuery>b__1_2(IServiceProvider p)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
at Microsoft.Data.Entity.Storage.DatabaseProviderServices.GetService[TService]()
at Microsoft.Data.Entity.Storage.Internal.InMemoryDatabaseProviderServices.get_Creator()
at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_12(IServiceProvider p)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
at Microsoft.Data.Entity.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
at Microsoft.Data.Entity.Infrastructure.DatabaseFacade.EnsureDeleted()
at TestTests.UnitTest1.TestMethod1() in C:\Users\jpmills\Documents\Visual Studio 2015\Projects\TESTEFRC1\TestTests\UnitTest1.cs:line 20
at TestTests.UnitTest1.TestMethod1() in C:\Users\jpmills\Documents\Visual Studio 2015\Projects\TESTEFRC1\TestTests\UnitTest1.cs:line 20```

**Comment by emrs-jm** [comment]
Apparently my guess at your email address was wrong.  If you send me an email at jeremem@electroniclaim.com, I can send you the source.  I will edit this in a few minutes to remove the email since I assume that you are getting email updates on issues you are tracking.

**Comment by smitpatel** [comment]
for both of the above cases - dupe of #3845

**Comment by emrs-jm** [comment]
In which daily build should I notice the fix?  I updated to 16533 today and I still see the issue even though the fix for #3845 looked to be merged in Friday.

**Comment by smitpatel** [comment]
@emrs-jm - Build no. is 16536

**Comment by Ph47** [comment]
How to get it?

   Unable to locate Dependency EntityFramework.MicrosoftSqlServer >= 7.0.0-rc2-16536
   Unable to locate Dependency EntityFramework.Core >= 7.0.0-rc2-16536

	<?xml version="1.0" encoding="utf-8"?>
	<configuration>
	  <packageRestore>
		<add key="enabled" value="True" />
		<add key="automatic" value="True" />
	  </packageRestore>
	  <packageSources>
		<add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
		<add key="nuget.org" value="https://www.nuget.org/api/v2/" />
		<add key="AspNetVNext" value="https://www.myget.org/F/aspnetvnext/" />
		<add key="aspnetwebstacknightly" value="https://www.myget.org/F/aspnetwebstacknightly/" />
		<add key="aspnetrelease" value="https://www.myget.org/F/aspnetrelease/" />
		<add key="azureadwebstacknightly" value="https://www.myget.org/F/azureadwebstacknightly/" />
	  </packageSources>
	  <activePackageSource>
		<add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
	  </activePackageSource>
	</configuration>

**Comment by ErikEJ** [comment]
use this feed: https://www.myget.org/F/aspnetcidev/api/v3/index.json

**Comment by Ph47** [comment]
@ErikEJ thx! Useful repo link.
