### ISSUE TITLE
Microsoft.Data.Entity.Internal.DbContextServices.get_DatabaseProviderServices()Will object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by blueskybcl** [dotnet/efcore#4101]
Application startup exception: System.Reflection.TargetInvocationException: The goal of call exception occurred. ---> System.NullReferenceException: Will object reference not set to an instance of an object.
   at Microsoft.Data.Entity.Internal.DbContextServices.get_DatabaseProviderServices()
   at Microsoft.Data.Entity.Infrastructure.RelationalEntityFrameworkServicesBuilderExtensions.GetProviderServices(IServiceProvider serviceProvider)
   at Microsoft.Data.Entity.Infrastructure.RelationalEntityFrameworkServicesBuilderExtensions.<>c.<AddRelational>b__0_16(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
  at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetService[T](IServiceProvider provider)
   at ContosoBooks.Models.SampleData.Initialize(IServiceProvider serviceProvider) position E:\AllProjects\ASP.NET5\ContosoBooks\src\ContosoBooks\Models\SampleData.cs:row number 14
   at ContosoBooks.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)

**Comment by blueskybcl** [comment]
resolved 
i  use 
if (context.Database == null)
{
        throw new Exception("DB is null");
}
replace 
if (serviceProvider.GetService<IRelationalDatabaseCreator>().Exists())

**Comment by divega** [comment]
@blueskybcl is there a chance you could provide repro code to help us make sure this isn't an issue in EF?

**Comment by blueskybcl** [comment]
@divega I was in accordance with the practice of http://docs.asp.net/projects/mvc/en/latest/tutorials/mvc-with-entity-framework.html, the result is wrong
“Next, we’ll create some sample data. Add a class named SampleData in the Models folder with the following code:”

error in class of SampleData 

If it is me, please tell me.

**Comment by divega** [comment]
Reopening so that we can see this in triage.

**Comment by blueskybcl** [comment]
@divega 
 ef version is 7.0.0.0-final-rc1

**Comment by blueskybcl** [comment]
@divega source at https://github.com/blueskybcl/ContosoBooks
