### ISSUE TITLE
Microsoft.Data.Entity.InMemory.FunctionalTests.QueryInMemoryTest.Where_string_to_lower failing on CoreCLR on OS X in the CI

### ISSUE THREAD

**Issue by cesarblum** [dotnet/efcore#4110]
```
Test collection for Microsoft.Data.Entity.InMemory.Function…moryTest (1): Microsoft.Data.Entity.InMemory.FunctionalTests (1)
QueryInMemoryTest.Where_string_to_lower     

Assert.Equal() Failure
Expected: 1
Actual:   0
   at Microsoft.Data.Entity.FunctionalTests.QueryTestBase`1.AssertQuery[TItem](Func`2 efQuery, Func`2 l2oQuery, Boolean assertOrder, Int32 entryCount, Action`2 asserter)
   at Microsoft.Data.Entity.FunctionalTests.QueryTestBase`1.AssertQuery[TItem](Func`2 query, Boolean assertOrder, Int32 entryCount, Action`2 asserter)
   at Microsoft.Data.Entity.FunctionalTests.QueryTestBase`1.Where_string_to_lower()
```

**Comment by natemcmaster** [comment]
Fixed by updating all CI agents locale settings. Caused by https://github.com/dotnet/coreclr/issues/2531
