### ISSUE TITLE
Adding a new migration leads to error.

### ISSUE THREAD

**Issue by maxmantz** [dotnet/efcore#4116]
I've recently updated to RC2 of EF7. Now when I try to add a migration using the EntityFramework.Commands, I get the following error:

> dnx : System.TypeLoadException: Could not load type 'Microsoft.Dnx.Runtime.LibraryTypes' from >assembly 'Microsoft.Dnx.Runtime, Version=1.0.0.0, Culture=neutral, >PublicKeyToken=adb9793829ddae60'.
> At line:1 char:1
> - dnx ef migrations add -c MyContext "NewMigration"
> - ```
>   ```
>   - CategoryInfo          : NotSpecified: (System.TypeLoad...9793829ddae60'.:String) [], >RemoteException
>   - FullyQualifiedErrorId : NativeCommandError
>   
>   at Microsoft.Data.Entity.Commands.Program.ValidateProject(Strin
>   g targetProject)
>   at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass2_7.<Main>b__15()
>   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] >args)
>   --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] >args, IServiceProvider serviceProvider)
>   at System.Threading.Tasks.Task`1.InnerInvoke()
>   at System.Threading.Tasks.Task.Execute()

My DNX is the following:

> Microsoft .NET Execution environment
> Version:      1.0.0-rc1-16231
> Type:         Clr
> Architecture: x64
> OS Name:      Windows
> OS Version:   10.0
> Runtime Id:   win10-x64

My EF7 versions are both `1.0.0-rc2-16579` for EntityFramework.Commands & EntityFramework.MicrosoftSqlServer.

NOTE: I've tried this both when migrations from previous versions existed and when no previous migrations were present. The error remains the same.

**Comment by maxmantz** [comment]
Using the latest beta version of the CLR (1.0.0-rc2-16317) the commands work again. Sorry for the inconvenience...

**Comment by Radzhab** [comment]
I have similar error

```
C:\Users\radzhab\Documents\Visual Studio 2015\Projects\Homebank\src\Homebank>dnx ef migrations add MyFirstMigration
System.TypeLoadException: Не удалось загрузить тип "Microsoft.Dnx.Runtime.LibraryTypes" из сборки "Microsoft.Dnx.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60".
   в Microsoft.Data.Entity.Commands.Program.ValidateProject(String targetProject)
   в Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass2_7.<Main>b__15()
   в Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   в Microsoft.Data.Entity.Commands.Program.Main(String[] args)
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   в Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
   в System.Threading.Tasks.Task`1.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()

dnx --version 
Microsoft .NET Execution environment
 Version:      1.0.0-rc1-16231
 Type:         Clr
 Architecture: x86
 OS Name:      Windows
 OS Version:   10.0
 Runtime Id:   win10-x86


dnvm list
Active Version           Runtime Architecture OperatingSystem Alias
------ -------           ------- ------------ --------------- -----
       1.0.0-rc1-final   clr     x86          win
  *    1.0.0-rc1-update1 clr     x86          win
       1.0.0-rc1-update1 coreclr x64          win             default

 "EntityFramework.Commands": "7.0.0-rc2-16649",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc2-16649",
    "Microsoft.AspNet.Identity": "3.0.0-rc2-16303",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.ApplicationInsights.AspNet": "1.0.0-rc1",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc1-final",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final",
    "Microsoft.Extensions.CodeGenerators.Mvc": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc1-final",
    "dnx-clr-win-x86": "1.0.0-rc1-update1",
    "EntityFramework.Core": "7.0.0-rc1-16317"
```
