### ISSUE TITLE
DbUpdateException is hidden in second inner exception

### ISSUE THREAD

**Issue by JohnyL** [dotnet/efcore#4196]
EF 6.13. I have written code which violates UNIQUE constraint in SQL Server database table. I got DbUpdateException as I wanted but with a twist.
Here's the text and exception text:

**Original exception text**:
An error occurred while updating the entries. See the inner exception for details.

**Original exception stack:**
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PriceList2.Root.<OnSaveChanges>d__8.MoveNext() in d:\Projects\PriceList2\Root.cs:line 169

I was wondered that InnerException _did not_ give me error message.
**First Inner Exception text:**
An error occurred while updating the entries. See the inner exception for details.

**First Inner Exception stack:**
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.<UpdateAsync>d__0.MoveNext()
-- End of stack trace from previous location where exception was thrown --
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.Objects.ObjectContext.<ExecuteInTransactionAsync>d__3d`1.MoveNext()
-- End of stack trace from previous location where exception was thrown --
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStoreAsync>d__39.MoveNext()
-- End of stack trace from previous location where exception was thrown --
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<ExecuteAsyncImplementation>d__9`1.MoveNext()
-- End of stack trace from previous location where exception was thrown --
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesInternalAsync>d__31.MoveNext()

I checked for **_second_** Inner Exception and finally got the desired exception message:

**Second Inner Exception text:**:
Violation of UNIQUE KEY constraint 'UQ_Mark'. Cannot insert duplicate key in object 'dbo.Mark'. The duplicate key value is (DAF). The statement has been terminated.

**Second Inner Exception stack:**
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__167_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
-- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.<ExecuteAsync>d__0.MoveNext()
-- End of stack trace from previous location where exception was thrown --
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.<UpdateAsync>d__0.MoveNext()

So, why the error is in the second (!) inner exception? Could it be in original exception or at least in first inner exception?

**Comment by rowanmiller** [comment]
The outer exception looks like it's a result of async code (outside of EFs control). We provide DbUpdateException so that there is something provider agnostic (and with links to the state entries) that app developers can catch. Of course, getting the raw exception from the database is important, so that is the inner exception.

Bottom line, the two nested exceptions in EF are important and the outermost exception you are seeing is not within EFs control.
