### ISSUE TITLE
`IHttpContextAccessor` failed to resolve when doing migrations

### ISSUE THREAD

**Issue by ahmad-moussawi** [dotnet/efcore#4232]
I am injecting the `IHttpContextAccessor` so I can automatically set the UpdatedBy and CreatedBy fields

```
 public class ApplicationDbContext : IdentityDbContext<ApplicationUser, IdentityRole, string>
 {
   public ApplicationDbContext(IHttpContextAccessor contextAccessor){
     this.userName = contextAccessor.HttpContext.User.Identity.Name;
}

public override int SaveChanges()
  {
            this.ChangeTracker.DetectChanges();
            var entries = this.ChangeTracker.Entries<BaseModel>()
                .Where(e => e.State == EntityState.Added || e.State == EntityState.Modified);

            foreach (var entry in entries)
            {
                if (entry.State == EntityState.Added)
                {
                    entry.Property("CreatedBy").CurrentValue = userName;
                }
          }

    return base.SaveChanges();
  }

```

This is working well, when there is a HttpContext, but it will throw an exception when I try to generate a new migration from the cli

```
$ dnx ef migrations add updateAccounts
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNet.Http.IHttpContextAccessor' while attempting to activate 'App.Models.ApplicationDbContext'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Data.Entity.Internal.DbContextActivator.CreateInstance[TContext](IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Data.Entity.Design.DbContextOperations.<>c__DisplayClass9_2.<FindContextTypes>b__6()
   at Microsoft.Data.Entity.Design.DbContextOperations.CreateContext(String contextType)
   at Microsoft.Data.Entity.Design.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.Data.Entity.Commands.Program.Executor.<>c__DisplayClass6_0.<AddMigration>b__0()
   at Microsoft.Data.Entity.Commands.Program.Executor.Execute(Action action)
Unable to resolve service for type 'Microsoft.AspNet.Http.IHttpContextAccessor' while attempting to activate 'App.Models.ApplicationDbContext'.
```

**Comment by Sebazzz** [comment]
This is because there is no HTTP context at that point. It is not really a EF problem but (imho) an architectural issue in your code.

**Comment by ahmad-moussawi** [comment]
@Sebazzz I know that there is no HTTP Context at this point, but how can I accomplish this, it's not practical that I should comment the params, every time I should generate a new migration, maybe the cli environment should inject a mock for the `IHttpContextAccessor`

**Comment by bricelam** [comment]
Inject an `IServiceProvider` and get the `IHttpContextAccessor` from that. `GetService` will return `null` if it's not in the container.

**Comment by rowanmiller** [comment]
The ways to deal with this are:
* Create an implementation of `IDbContextFactory<TContext>` in the same project as your context to tell migrations how to create instances of your context. 
* As suggested by @bricelam, take `IServiceProvider` and resolve `IHttpContextAccessor` within your context and handle it being null.
* Swap the constructor parameter from `IHttpContextAccessor` to `IEnumerable<IHttpContextAccessor>` and the collection will either have one or zero elements (and handle the absence of an `IHttpContextAccessor` within your context).

**Comment by MaximBalaganskiy** [comment]
The last two options work. The first one though doesn't. Simplest implementation
```
public class DesignDbContextFactory : IDbContextFactory<HorsieContext>
	{
		public DesignDbContextFactory()
		{
		}

		public HorsieContext Create()
		{
			//throw new NotImplementedException();
			return new HorsieContext(new IDateService[] { }, new IHttpContextAccessor[] { });
		}
	}
```
causes migration to fail with exception
```
System.InvalidOperationException: No database providers are configured. Configure a database provider by overriding OnConfiguring i
n your DbContext class or in the AddDbContext method when setting up services.
   at Microsoft.Data.Entity.Internal.DatabaseProviderSelector.SelectServices(ServiceProviderSource providerSource)
   at Microsoft.Data.Entity.Internal.DbContextServices.<>c__DisplayClass6_0.<Initialize>b__0()
   at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.Internal.DbContextServices.get_DatabaseProviderServices()
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_8(IServicePr
ovider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)

   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type service
Type)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Data.Entity.Design.Internal.DesignTimeServicesBuilder.Build(DbContext context)
   at Microsoft.Data.Entity.Design.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.Data.Entity.Commands.Program.Executor.<>c__DisplayClass6_0.<AddMigration>b__0()
   at Microsoft.Data.Entity.Commands.Program.Executor.Execute(Action action)
No database providers are configured. Configure a database provider by overriding OnConfiguring in your DbContext class or in the A
ddDbContext method when setting up services.
```

I suspect more has to be done in that implementation to correctly create a context. Could you please provide some guides?

**Comment by blueanson** [comment]
Hi, MaximBalaganskiy. i have the same problem, could you post the full code. thanks

**Comment by MaximBalaganskiy** [comment]
@Anson99 I ended up with the 3rd suggestion - injecting an array instead of single instance. This makes the dependency optional.

**Comment by ahmad-moussawi** [comment]
Yes me too, I liked this approach 👍  (the 3rd one)

**Comment by Anson99** [comment]
My code is as below, the username still empty.

public DataContext(
            IServiceProvider serviceProvider,
            IEnumerable<IHttpContextAccessor> contextAccessor,
            DbContextOptions<DataContext> options,
            ILoggerFactory loggerFactory)
            :base(options)
        {
            var accessor = contextAccessor.FirstOrDefault();        
 var userName = accessor.HttpContext.User.Identity.Name;   
        }

**Comment by divega** [comment]
@Anson99 the idea is that the `IEnumerable<IHttpContextAccessor>` dependency will be empty at design time (e.g. `FirstOrDefault()` will return null), so you will have to handle it being empty somehow. In your case it might help asking the question of what you expect the username to be at design time. If this is information that you are passing to the `DbContext` just to affect some runtime behavior (e.g. to do some filtering on queries) as opposed to something that affects the shape of the model then it should be ok for it to be null or to take some arbitrary default value.

**Comment by kalahari** [comment]
The likely cause of this is: https://github.com/aspnet/Announcements/issues/190
You don't need an active HttpContext to resolve IHttpContextAccessor

**Comment by FruitAndAShape** [comment]
I did this...

```
container.RegisterType<IDomainDbContext, DomainDbContext>(
   container.IsRegistered<IHttpContextAccessor>() ?
      new HttpContextLifetimeManager<IDomainDbContext>(container.Resolve<IHttpContextAccessor>()) :
null);
```
