### ISSUE TITLE
Migration problem with multiple DbContexts

### ISSUE THREAD

**Issue by huytnd** [dotnet/efcore#4306]
My scenario: I'm using EF 7.0.0-rc1-final, I have 2 class libraries with 2 dbcontexts, one of them use IdentityDbContext, and each class library has a Migrations folder for each dbcontext, and an method for seeding data.
When I call 2 seeding data methods in Startup.cs file, I got this error message
![500_interal](https://cloud.githubusercontent.com/assets/2102905/12318837/0ffbe6d2-bad0-11e5-9f0f-0d848567f961.jpg)

DefaultUser class for seeding a new user.

```
public class DefaultUser
    {
        private AccountDbContext _context;
        private UserManager<ApplicationUser> _userManager;

        public DefaultUser(AccountDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public DefaultUser()
        {

        }

        public async Task InitializeDefaultUser(IServiceProvider serviceProvider)
        {
            var context = serviceProvider.GetService<AccountDbContext>();

            if (context.Database == null)
                return;

            await context.Database.MigrateAsync();

            if(await _userManager.FindByEmailAsync("abc@abc.com") == null)
            {
                // Add a user
                var newUser = new ApplicationUser()
                {
                    UserName = "abc",
                    Email = "abc@abc.com"
                };

                await _userManager.CreateAsync(newUser, "password");
            }
        }
    }
```

AccountDbContext

```
public class AccountDbContext : IdentityDbContext<ApplicationUser>
    {
    }
```

Startup.cs

```
DefaultUser defaultUser = new DefaultUser();
defaultUser.InitializeDefaultUser(app.ApplicationServices).Wait();
```

Register services for 2 dbcontext in Startup.cs

```
services.AddEntityFramework()
                .AddSqlServer()
                .AddDbContext<MediaDbContext>(options =>
                {
                    options.UseSqlServer(configuration["Data:DefaultConnection:ConnectionString"]);
                });
            services.AddEntityFramework()
                .AddSqlServer()
                .AddDbContext<AccountDbContext>(options =>
                {
                    options.UseSqlServer(configuration["Data:DefaultConnection:ConnectionString"]);
                });

            services.AddScoped<MediaDbContext>();
            services.AddScoped<AccountDbContext>();
```

When I tried to apply migration for AccountDbContext, I got this error message
![accountdbcontext_error](https://cloud.githubusercontent.com/assets/2102905/12319011/8ccd297c-bad1-11e5-9086-031784c2b5bc.jpg)

**Comment by rowanmiller** [comment]
You trim the code in Startup.cs down to the following and everything will work:

```c#
services.AddEntityFramework()
    .AddSqlServer()
    .AddDbContext<MediaDbContext>(options =>
    {
        options.UseSqlServer(configuration["Data:DefaultConnection:ConnectionString"]);
    })
    .AddDbContext<AccountDbContext>(options =>
    {
        options.UseSqlServer(configuration["Data:DefaultConnection:ConnectionString"]);
    });
```

The specific line that was causing your issue was explicitly registering the contexts as scoped. `AddDbContext` will put your context in the services with all the logic to flow the required services into them. Your explicit call to `AddScoped` lacks any of this logic, and because your context does not expose a constructor that takes an `IServiceProvider` (and passes it to the base constructor) EF does not get the services required from DI.

**Comment by huytnd** [comment]
I removed ```AddScoped```, and add IServiceProvider to the constructors of 2 sample data classes, and call them in Startup.cs.
MediaSampleData.cs
```
private MediaDbContext _context;

public MediaSampleData(IServiceProvider serviceProvider)
{
        _context = serviceProvider.GetService<MediaDbContext>();
}
public async Task InitializeMediaSampleData()
{
        if (_context.Database == null)
                return;

        await _context.Database.MigrateAsync();

        // add data
}
```
DefaultUser.cs
```
private AccountDbContext _context;
private UserManager<ApplicationUser> _userManager;

public DefaultUser(IServiceProvider serviceProvider)
{
        _context = serviceProvider.GetService<AccountDbContext>();
}
public async Task InitializeDefaultUser()
{
       if (_context.Database == null)
                return;

       await _context.Database.MigrateAsync();

      // add default user data
}
```
Startup.cs
```
MediaSampleData mediaSampleData = new MediaSampleData(app.ApplicationServices);
mediaSampleData.InitializeMediaSampleData().Wait();
DefaultUser defaultUser = new DefaultUser(app.ApplicationServices);
defaultUser.InitializeDefaultUser().Wait();
```
When I run the application, I got this exception
```
System.AggregateException was unhandled by user code
  HResult=-2146233088
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at System.Threading.Tasks.Task.Wait()
       at HuyTranPhotos.PublicWebsite.Startup.Configure(IApplicationBuilder app) in C:\Users\huytr\Documents\Visual Studio 2015\Projects\HuyTranPhotos\HuyTranPhotos.PublicWebsite\Startup.cs:line 149
       at HuyTranPhotos.PublicWebsite.Startup.ConfigureDevelopment(IApplicationBuilder appBuilder) in C:\Users\huytr\Documents\Visual Studio 2015\Projects\HuyTranPhotos\HuyTranPhotos.PublicWebsite\Startup.cs:line 93
  InnerException: 
       HResult=-2146233079
       Message=The connection was not closed. The connection's current state is connecting.
       Source=System.Data
       StackTrace:
            at System.Data.ProviderBase.DbConnectionClosedConnecting.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
            at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
            at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
            at System.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
            at Microsoft.Data.Entity.Storage.RelationalConnection.<OpenAsync>d__32.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
            at Microsoft.Data.Entity.Storage.Internal.SqlServerDatabaseCreator.<ExistsAsync>d__13.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at Microsoft.Data.Entity.Migrations.HistoryRepository.<ExistsAsync>d__26.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at Microsoft.Data.Entity.Migrations.Internal.Migrator.<MigrateAsync>d__11.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
            at HuyTranPhotos.MediaManagement.Data.MediaSampleData.<InitializeMediaSampleData>d__2.MoveNext() in C:\Users\huytr\Documents\Visual Studio 2015\Projects\HuyTranPhotos\HuyTranPhotos.MediaManagement.Data\MediaSampleData.cs:line 26
       InnerException: 
```

**Comment by rowanmiller** [comment]
Can you share the complete contents of `MediaSampleData.cs` so that we can see what it is doing on Line 26 (where the exception is getting thrown) - this is the kind of thing you might see if you try to run two operations concurrently on the same context instance.

**Comment by huytnd** [comment]
The complete code of MediaSampleData.cs
```
public class MediaSampleData
    {
        private MediaDbContext _context;

        public MediaSampleData(IServiceProvider serviceProvider)
        {
            _context = serviceProvider.GetService<MediaDbContext>();
        }

        public async Task InitializeMediaSampleData()
        {
            if (_context.Database == null)
                return;

            await _context.Database.MigrateAsync();

            if (! await _context.AlbumCategories.AnyAsync())
            {
                var cat1 = _context.AlbumCategories.Add(
                    new AlbumCategory
                    {
                        Name = "wedding",
                        Description = "wedding photos"
                    });

                await _context.SaveChangesAsync();
            }
        }
    }
```

**Comment by rowanmiller** [comment]
That still looks like a partial listing, you must have some using statements at the top of the file. I need the full listing to line up line numbers in the exception details with your code.

**Comment by huytnd** [comment]
I updated the code above with ```using``` statements.

**Comment by huytnd** [comment]
Update: even if i use just only 1 dbcontext (MediaDbContext), the exception still occur.
![exception](https://cloud.githubusercontent.com/assets/2102905/12387590/386b5ee4-be00-11e5-925a-3a538a49e92f.jpg)

**Comment by rowanmiller** [comment]
@huytnd can you share your project, or a complete code listing of you model (MediaDbContext and the entity classes), so that I can try and reproduce this issue.

**Comment by rowanmiller** [comment]
Closing as we have not heard back with requested details.
