### ISSUE TITLE
Console application scaffold exception

### ISSUE THREAD

**Issue by connde** [dotnet/efcore#4366]
Hello, I'm having problem trying to generate the models using a database first approach.
I'm following this [link to](https://ef.readthedocs.org/en/latest/getting-started/full-dotnet/existing-db.html) and when I get to the scaffold part I get an exception message.

I'm not using the Blogging database, I want to generate the models from another existing database.

Scaffold-DbContext : Exception calling "CreateInstanceAndUnwrap" with "8" argument(s): "Could not load file or assembly 'EntityFramework.Commands' or one of its dependencies. The system cannot find the file 
specified."
At line:1 char:1
- Scaffold-DbContext -connection "Server=L240SRV348;Database=MyForest_Dev;Trusted_ .
  ..
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Scaffold-DbContext], MethodInvocationException
  - FullyQualifiedErrorId : FileNotFoundException,Scaffold-DbContext

**Print screen**
![capture](https://cloud.githubusercontent.com/assets/1514559/12494210/ab68983a-c067-11e5-8b9c-f99cb28b2e6c.PNG)

[Sample project](https://www.dropbox.com/s/4yjq7fl133p4a5c/ClassLibrary1.zip?dl=0)

**Comment by rowanmiller** [comment]
Do you have the latest version of PowerShell installed? https://www.microsoft.com/en-us/download/details.aspx?id=40855

**Comment by connde** [comment]
I have version 4.0, should I install 5?
![image](https://cloud.githubusercontent.com/assets/1514559/12496087/49a04f52-c072-11e5-9c04-0dc0637d6dce.png)

**Comment by rowanmiller** [comment]
4.0 should be fine - it must be something else

**Comment by connde** [comment]
Is the App.config supposed to have some specific configuration?

**Comment by connde** [comment]
Here is the detailed error from PS

PM> $error[0] | Format-List * -Force


PSMessageDetails      : 
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "CreateInstanceAndUnwrap" with "8" argument(s): "Could not load file or assembly 'EntityFramework.Commands' or 
                        one of its dependencies. The system cannot find the file specified." ---> System.IO.FileNotFoundException: Could not load file or assembly 'EntityFramework.Commands' or one of its 
                        dependencies. The system cannot find the file specified.
                           at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr 
                        pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
                           at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr 
                        pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
                           at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr 
                        pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
                           at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] 
                        activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
                           at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] 
                        activationAttributes)
                           at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] 
                        activationAttributes)
                           at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, 
                        Object[] activationAttributes)
                           at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, 
                        Object[] activationAttributes)
                           at CallSite.Target(Closure , CallSite , Object , Object , Object , Boolean , Int32 , Object , Object[] , Object , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                           at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
                           at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
                           at System.Management.Automation.CommandProcessorBase.Complete()
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : FileNotFoundException
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at InvokeOperation, C:\Workspace\myforest\packages\EntityFramework.Commands.7.0.0-rc1-final\tools\EntityFramework.psm1: line 596
                        at Scaffold-DbContext, C:\Workspace\myforest\packages\EntityFramework.Commands.7.0.0-rc1-final\tools\EntityFramework.psm1: line 409
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}



PM> $error[0].Exception | Format-List * -Force


ErrorRecord                 : Exception calling "CreateInstanceAndUnwrap" with "8" argument(s): "Could not load file or assembly 'EntityFramework.Commands' or one of its dependencies. The system cannot find the 
                              file specified."
StackTrace                  :    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo 
                              memberInfo)
                                 at CallSite.Target(Closure , CallSite , Object , Object , Object , Boolean , Int32 , Object , Object[] , Object , Object )
                                 at System.Dynamic.UpdateDelegates.UpdateAndExecute9[T0,T1,T2,T3,T4,T5,T6,T7,T8,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 
                              arg8)
                                 at CallSite.Target(Closure , CallSite , Object , Object , Object , Boolean , Int32 , Object , Object[] , Object , Object )
                                 at System.Management.Automation.Interpreter.DynamicInstruction`10.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
WasThrownFromThrowStatement : False
Message                     : Exception calling "CreateInstanceAndUnwrap" with "8" argument(s): "Could not load file or assembly 'EntityFramework.Commands' or one of its dependencies. The system cannot find the 
                              file specified."
Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException              : System.IO.FileNotFoundException: Could not load file or assembly 'EntityFramework.Commands' or one of its dependencies. The system cannot find the file specified.
                              File name: 'EntityFramework.Commands'
                                 at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr 
                              pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
                                 at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr 
                              pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
                                 at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr 
                              pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
                                 at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, 
                              Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
                                 at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] 
                              activationAttributes)
                                 at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] 
                              activationAttributes)
                                 at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, 
                              Object[] activationAttributes)
                                 at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, 
                              Object[] activationAttributes)
                                 at CallSite.Target(Closure , CallSite , Object , Object , Object , Boolean , Int32 , Object , Object[] , Object , Object )
                              
                              WRN: Assembly binding logging is turned OFF.
                              To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
                              Note: There is some performance penalty associated with assembly bind failure logging.
                              To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
                              
TargetSite                  : Void CheckActionPreference(System.Management.Automation.Language.FunctionContext, System.Exception)
HelpLink                    : 
Source                      : System.Management.Automation
HResult                     : -2146233087

**Comment by mdymel** [comment]
I had this problem yesterday. It turned out the problem was that project which I was running migrations on wasn't set as startup. You have to either set as a startup project or provide it using -StartUpProject option

**Comment by connde** [comment]
@mdymel yes, I already tried setting the default project but the problem persisted, I also created a new solution and it would not work either.

Nevertheless I will close the ticket because I believe it is a problem with my PowerShell since the same command worked on other machines.

What I did not found in the internet is how to repair PowerShell installation on Windows 8.1, I believe that´s impossible?

**Comment by dudih** [comment]
I had the same problem, for me what did the trick is running "dnvm upgrade" from the windows cmd.
[http://stackoverflow.com/questions/31125440/dnx-web-command-throwing-unable-to-resolve-project-error-after-publishing-from](url)

**Comment by yehe01** [comment]
Hi, I am still having the same issue.

![123](https://cloud.githubusercontent.com/assets/1256556/19754100/274e366a-9c56-11e6-819e-9f33f686b920.PNG)
![capture](https://cloud.githubusercontent.com/assets/1256556/19754103/2a22211c-9c56-11e6-8a0c-c0e053665e16.PNG)
