### ISSUE TITLE
The properties expression 'm => Convert(m.Id)' is not valid

### ISSUE THREAD

**Issue by iwnow** [dotnet/efcore#4383]
What wrong with compiler?

System.ArgumentException: The properties expression 'm => Convert(m.Id)' is not valid. The expression should represent a property access: 't => t.MyProperty'. When specifying multiple properties use an anonymous type: 't => new { t.MyProperty1, t.MyProperty2 }'.
Parameter name: propertyAccessExpression
   at System.Linq.Expressions.ExpressionExtensions.GetPropertyAccessList(LambdaExpression propertyAccessExpression)
   at Microsoft.Data.Entity.Metadata.Builders.EntityTypeBuilder`1.HasKey(Expression`1 keyExpression)
   at Services.NpgDbContext.OnModelCreating(ModelBuilder builder)
   at Microsoft.Data.Entity.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Data.Entity.Internal.DbContextServices.CreateModel()
   at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Data.Entity.Design.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.Data.Entity.Commands.Program.Executor.<>c__DisplayClass6_0.<AddMigration>b__0()
   at Microsoft.Data.Entity.Commands.Program.Executor.Execute(Action action)
The properties expression 'm => Convert(m.Id)' is not valid. The expression should represent a property access: 't => t.MyProperty'. When specifying multiple properties use an anonymous type: 't => new { t.MyProperty1, t.MyProperty2 }'.
Parameter name: propertyAccessExpression

pac:
"dependencies": {
        "EntityFramework7.Npgsql": "3.1.0-rc1-3",
        "EntityFramework.Core": "7.0.0-rc1-final",
        "EntityFramework.Commands": "7.0.0-rc1-final",
        "Microsoft.AspNet.Authentication.Cookies": "1.0.0-_",
        "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-_",
        "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-_",
        "Microsoft.AspNet.IISPlatformHandler": "1.0.0-_",
        "Microsoft.AspNet.Mvc": "6.0.0-_",
        "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-_",
        "Microsoft.AspNet.Server.Kestrel": "1.0.0-_",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-_",
        "Microsoft.AspNet.Session": "1.0.0-_",
        "Microsoft.AspNet.StaticFiles": "1.0.0-_",
        "Microsoft.AspNet.Tooling.Razor": "1.0.0-_",
        "Microsoft.Extensions.CodeGenerators.Mvc": "1.0.0-_",
        "Microsoft.Extensions.Configuration.CommandLine": "1.0.0-_",
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-_",
        "Microsoft.Extensions.Configuration.Json": "1.0.0-_",
        "Microsoft.Extensions.Logging.Console": "1.0.0-_",
        "Microsoft.Extensions.Configuration": "1.0.0-_",
        "Microsoft.Extensions.OptionsModel": "1.0.0-_",
         "Microsoft.CodeAnalysis.CSharp": "1.1.0-*",
         "System.Reflection.Metadata": "1.1.1-beta-23516",
         "System.Linq.Expressions": "4.0.11-beta-23516"
    }

**Comment by smitpatel** [comment]
The exception is thrown while creating the model. Can you share your model code, especially `OnModelCreating` code inside DbContext?

**Comment by iwnow** [comment]
Yes, OnModelCreating has just one string [source in repo] (https://github.com/iwnow/ctoc): 
```
protected override void OnModelCreating(ModelBuilder builder) {
       builder.Entity<User>().HasKey(m => m.Id);
       base.OnModelCreating(builder);
}
```
Model:
```
public class User {
        public long Id;
        public string Login;
        public string Password;        
}
```
When i type in console *dnx ef migrations add initMigration*, i take that error.

**Comment by smitpatel** [comment]
As exception message says, you need to define a property access. In class `User`, `Id` is a public field and not a property. Therefore it throws exception on `m => m.Id` because it is not a valid property access.

**Comment by iwnow** [comment]
Oh, thank you :) it works!

**Comment by tricor0** [comment]
Thanks! I had forgotten to add { get; set; } in the model class.
