### ISSUE TITLE
EntityFramework.InMemory conflicts with Microsoft.NETCore 5.0.0 in UWP Test Project

### ISSUE THREAD

**Issue by Preecington** [dotnet/efcore#4472]
I'm getting the following exception when trying to utilise an InMemory provider inside a UWP test project running XUnit: `System.IO.FileNotFoundException : Could not load file or assembly 'System.Collections.Immutable, Version=1.1.36.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.`

I've included the stack trace below. Looking at `project.lock.json`, it appears that EF Core wants 1.1.36, whilst .NETCore includes 1.1.37. If I replace the `System.Collections.Immutable` DLL in the output directory with a 1.1.36 version, it works. Any suggested workarounds?

Relevant parts of project.lock.json:

```
      "EntityFramework.Core/7.0.0-rc1-final": {
         "dependencies": {
          < ... >
          "System.Collections.Immutable": "[1.1.36, )",
          < ... >
        },
        "compile": {
          "lib/netcore50/EntityFramework.Core.dll": {}
        },
        "runtime": {
          "lib/netcore50/EntityFramework.Core.dll": {}
        }
      },      
      "Microsoft.NETCore/5.0.0": {
        "dependencies": {
          < ... >
          "System.Collections.Immutable": "[1.1.37, )",
          < ... >
        }
      },
```

Stack Trace:

``````
      System.IO.FileNotFoundException : Could not load file or assembly 'System.Collections.Immutable, Version=1.1.36.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
      Stack Trace:
           at Microsoft.Data.Entity.Storage.Internal.InMemoryStore..ctor(ILogger`1 logger)
        --- End of stack trace from previous location where exception was thrown ---
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
           at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
           at Microsoft.Extensions.DependencyInjection.ServiceProvider.SingletonCallSite.Invoke(ServiceProvider provider)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
           at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
           at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
           at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
           at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
           at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
           at Microsoft.Data.Entity.Storage.DatabaseProviderServices.GetService[TService]()
           at Microsoft.Data.Entity.Storage.Internal.InMemoryDatabaseProviderServices.get_Database()
           at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_9(IServiceProvider p)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
           at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
           at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
           at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
           at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
           at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
           at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
           at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
           at Microsoft.Data.Entity.Storage.DatabaseProviderServices.GetService[TService]()
           at Microsoft.Data.Entity.Storage.Internal.InMemoryDatabaseProviderServices.get_QueryContextFactory()
           at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c.<AddQuery>b__1_0(IServiceProvider p)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
           at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
           at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
           at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
           at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
           at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
           at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
           at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
           at Microsoft.Data.Entity.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
           at Microsoft.Data.Entity.Internal.InternalDbSet`1.<.ctor>b__2_0()
           at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
           at Microsoft.Data.Entity.Internal.InternalDbSet`1.Microsoft.Data.Entity.Query.Internal.IAsyncEnumerableAccessor<TEntity>.get_AsyncEnumerable()
           at Microsoft.Data.Entity.EntityFrameworkQueryableExtensions.AsAsyncEnumerable[TSource](IQueryable`1 source)
           at Microsoft.Data.Entity.EntityFrameworkQueryableExtensions.ForEachAsync[T](IQueryable`1 source, Action`1 action, CancellationToken cancellationToken)
... <remainder of stack>```
``````

**Comment by bricelam** [comment]
Please use RC1 with UWP for now. RC2 will require updated Win10 tooling that be available around the same time.

**Comment by Preecington** [comment]
@bricelam I'm currently using EF7 RC1 (7.0.0-rc1-final) with UWP (SDK 10240) and still getting this error.

**Comment by bricelam** [comment]
Ah, sorry. You should be able to add a binding redirect. Add an `App.config` file to the project with the following contents.

```XML
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Collections.Immutable"
                          publicKeyToken="b03f5f7f11d50a3a"
                          culture="neutral" />
        <bindingRedirect oldVersion="1.1.36.0" newVersion="1.1.37.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by Preecington** [comment]
Thanks @bricelam - I didn't consider using `app.config` as generally UWP doesn't support it. That workaround did the trick.

**Comment by bricelam** [comment]
Yeah, I don't think it would have any effect on a pure UWP project, but xUnit.net will use it if it's there.

Since RC1, we've removed our dependency on `System.Collections.Immutable`, so I'm going to go ahead and close this issue.
