### ISSUE TITLE
Map db column int to model property long

### ISSUE THREAD

**Issue by sharppanda** [dotnet/efcore#4517]
I have a data model composed of entities with ids stored as bigint and ids stored as int.
On Data Model Layer I would like to work with all entities with IDs as long. Is it possible to configure entity framework to map column int to model long?

**Comment by rowanmiller** [comment]
@martinpaulicek that should just work as ADO.NET is happy to take care of the type conversion...

```
            modelBuilder.Entity<Blog>()
            .Property(b => b.BlogId)
            .HasColumnType("int");
```

More complex type conversions will need https://github.com/aspnet/EntityFramework/issues/242.

**Comment by martinpaulicek** [comment]
Thank you.

**Comment by martinpaulicek** [comment]
I just tested that and unfortunately got Exception: {"Specified cast is not valid."}
```
public partial class ServiceType
{
        public long ID { get; set; }
}
```
DataContext:
```
   modelBuilder.Entity<ServiceType>(entity =>
            {
                entity.Property(e => e.ID).HasColumnType("int").ValueGeneratedOnAdd();
                entity.HasKey(e => e.ID);
            });
```
Migrations - snapshot:
```
 modelBuilder.Entity("ConfigurationService.Model.Models.ServiceType", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Relational:ColumnType", "int");

                    b.HasKey("ID");
                });
```

**Comment by divega** [comment]
I think for SqlDataReader we call `GetValues()` so SqlClient cannot do any type conversions.

**Comment by rowanmiller** [comment]
The issue seems to be a limitation in our code. If the property is not a key property then it all works:

```c#
using Microsoft.Data.Entity;
using System;
using System.Linq;

namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var db = new MyContext())
            {
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                db.Blogs.Add(new Blog { Test = 5 });
                db.SaveChanges();

                db.Blogs.ToList();
            }
        }
    }

    public class MyContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Sample;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Blog>()
            .Property(b => b.Test)
            .HasColumnType("int");
        }
    }

    public class Blog
    {
        public long BlogId { get; set; }
        public long Test { get; set; }
    }
}
```

However, if you try to map the key property to `int` then it throws in `SimpleKeyValueFactory`:

```c#
            modelBuilder.Entity<Blog>()
            .Property(b => b.BlogId)
            .HasColumnType("int");
```


> System.InvalidCastException: Specified cast is not valid.
   at Microsoft.Data.Entity.ChangeTracking.Internal.SimpleKeyValueFactory`1.Create(Object value)
   at Microsoft.Data.Entity.ChangeTracking.Internal.SimpleKeyValueFactory`1.Create(IReadOnlyList`1 properties, IPropertyAccessor propertyAccessor)
   at Microsoft.Data.Entity.ChangeTracking.Internal.EntityEntryMetadataServices.CreateKey(IKey key, IReadOnlyList`1 properties, IPropertyAccessor propertyAccessor)
   at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntry.CreateKey(IKey key, IReadOnlyList`1 properties, IPropertyAccessor propertyAccessor)
   at Microsoft.Data.Entity.ChangeTracking.Internal.PropertyAccessorExtensions.GetPrincipalKeyValue(IPropertyAccessor propertyAccessor, IKey key)
   at Microsoft.Data.Entity.ChangeTracking.Internal.StateManager.GetKeyValueChecked(IKey key, InternalEntityEntry entry)
   at Microsoft.Data.Entity.ChangeTracking.Internal.StateManager.UpdateIdentityMap(InternalEntityEntry entry, IKeyValue oldKeyValue, IKey principalKey)
   at Microsoft.Data.Entity.ChangeTracking.Internal.ChangeDetector.DetectKeyChange(InternalEntityEntry entry, IProperty property, Sidecar snapshot)
   at Microsoft.Data.Entity.ChangeTracking.Internal.ChangeDetector.PropertyChanged(InternalEntityEntry entry, IPropertyBase propertyBase)
   at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntryNotifier.<>c__DisplayClass12_0.<PropertyChanged>b__0(IPropertyListener l)
   at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntryNotifier.Dispatch(Action`1 action)
   at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntryNotifier.PropertyChanged(InternalEntityEntry entry, IPropertyBase property)
   at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntry.set_Item(IPropertyBase propertyBase, Object value)
   at Microsoft.Data.Entity.Update.ColumnModification.set_Value(Object value)
   at Microsoft.Data.Entity.Update.ModificationCommand.PropagateResults(ValueBuffer valueBuffer)
   at Microsoft.Data.Entity.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithPropagation(Int32 commandIndex, DbDataReader reader)
   at Microsoft.Data.Entity.Update.AffectedCountModificationCommandBatch.Consume(DbDataReader reader)
   --- End of inner exception stack trace ---
   at Microsoft.Data.Entity.Update.AffectedCountModificationCommandBatch.Consume(DbDataReader reader)
   at Microsoft.Data.Entity.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.Data.Entity.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.Data.Entity.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.Data.Entity.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.Data.Entity.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.Data.Entity.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.Data.Entity.DbContext.SaveChanges()
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\rowmil\Documents\Visual Studio 2015\Projects\Console.RC1\Console.RC1\Program.cs:line 17

**Comment by martinpaulicek** [comment]
Is this intended limitation or it will be possible to use it on keys as well in next RC version?

**Comment by rowanmiller** [comment]
**Team Triage:** This isn't intended to be supported... but does 'work by accident' for non-key properties. https://github.com/aspnet/EntityFramework/issues/242 is the enhancement we are tracking to properly support this scenario (closing this one out since we already have that one).
