### ISSUE TITLE
Should explicit implementations of interface properties be mapped by default?

### ISSUE THREAD

**Issue by jumpinjackie** [dotnet/efcore#4534]
Using EF 7.0.0-rc1-final

This is a half question/bug, depending on how you choose to view the problem.

I have a class like so:

```
namespace MyApp
{
    public interface IEditableObject
    {
        string ObjectId { get; }

        ... //Other methods
    }

    public class Yard : IEditableObject
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public bool IsPriorityVisit { get; set; }

        string IEditableObject.ObjectId => this.Id.ToString(); // <===== EF wants to map this property

        ... //Other method impls of IEditableObject
    }
}
```

When part of a DbContext

```
namespace MyApp
{
    public class MyAppDbContext : DbContext
    {
        public DbSet<Yard> Yards { get; set; }
    }
}
```

EF throws with

```
No backing field could be discovered for property 'MyApp.Yard.MyApp.IEditableObject.ObjectId' and the property does not have a setter. Either use a backing field name that can be matched by convention, annotate the property with a backing field, or define a property setter.
```

With a stack trace of:

```
at Microsoft.Data.Entity.Metadata.Internal.MemberMapper.MapPropertiesToMembers(IEntityType entityType)
at Microsoft.Data.Entity.Metadata.Internal.EntityMaterializerSource.CreateMaterializeExpression(IEntityType entityType, Expression valueBufferExpression, Int32[] indexMap)
at Microsoft.Data.Entity.Query.Internal.MaterializerFactory.CreateMaterializer(IEntityType entityType)
at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.InMemoryEntityQueryableExpressionVisitor.VisitEntityQueryable(Type elementType)
at Microsoft.Data.Entity.Query.ExpressionVisitors.EntityQueryableExpressionVisitor.VisitConstant(ConstantExpression constantExpression)
at System.Linq.Expressions.ConstantExpression.Accept(ExpressionVisitor visitor)
at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection)
at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CompileMainFromClauseExpression(MainFromClause mainFromClause, QueryModel queryModel)
at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitMainFromClause(MainFromClause fromClause, QueryModel queryModel)
at Remotion.Linq.Clauses.MainFromClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
at Microsoft.Data.Entity.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
at Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass18_0`1.<CompileQuery>b__0()
at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
at Microsoft.Data.Entity.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query)
at Microsoft.Data.Entity.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
<application level stack trace redacted>
```

I could accept this result if the `ObjectId` property was an implicit interface implementation, but being an explicit interface property, it sounds strange to me that EF would be trying to map this property.

So as a workaround, I've configured EF to to ignore this property, but trying to do this fluently fails:

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Yard>()
                .Ignore("ObjectId"); // <===== EF doesn't pick this up

    base.OnModelCreating(modelBuilder);
}
```

Doing it by lambda expression also either fails or doesn't work because being an implementation, `ObjectId` is only visible on `Yard` through the facade of `IEditableObject`

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Yard>()
                .Ignore(y => ((IEditableObject)y).ObjectId); // <===== Not sure if legal or not, either way EF isn't picking it up

    base.OnModelCreating(modelBuilder);
}
```

So the only feasible workaround it applying a `[NotMapped]` on the `ObjectId` property, which is the least desirable option as I prefer the fluent approach over "polluting" my classes with such attributes.

So like I said above, this could either be a question or bug?
- Question: Should EF be automatically trying to map explicit interface properties by default?
- Bug: If yes to the question, then attempts to fluently ignore this property in the above examples fails. Only applying `[NotMapped]` on the property will get EF to ignore it.

NOTE: Some typenames, namespaces, and stack traces in the above examples have been replaced or sanitized due to data sensitivity, but hopefully the basic gist of the problem is still applicable and properly conveyed.

**Comment by rowanmiller** [comment]
@jumpinjackie we've already changed these rules for the next release. We now only map properties with a public getter (and they also have to have a setter). With the new rules, the property in question would no longer be mapped (both because it has no setter and because it is an explicit interface implementation).

**Comment by jumpinjackie** [comment]
@rowanmiller Ah, good to know

**Comment by alireza-nasseri** [comment]
hello 
before i explain my problem this is my code :
    public  class AuthUser<TUser> : IdentityUser
    {
        private ExteraInformation<MainUser> exteraInformation;
        [NotMapped]
        public IExteraInformation<MainUser> ExteraInformation
        {
            get => exteraInformation;
            set => exteraInformation = value as ExteraInformation<MainUser>;
        }
    }
    public class MainUser : AuthUser<MainUser>
    {

    }
    public interface IAuthUser<TUser>
    {
        IExteraInformation<TUser> ExteraInformation { get; set; }
    }
    public class ExteraInformation<TUser> : IExteraInformation<TUser>
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string ProfileImageAddress { get; set; }
        public string SMSToken { get; set; }
        public bool IAcceptedPolicyAndPrivaryAtRegistration { get; set; }
        public DateTime RegisterDate { get; set; }

        
        [ForeignKey(nameof(UserID))]
        public TUser User { get; set; }
        public string UserID { get; set; }
    }
    public interface IExteraInformation<TUser>
    {
        string FullName { get; set; }
        string ProfileImageAddress { get; set; }
        string SMSToken { get; set; }
        bool IAcceptedPolicyAndPrivaryAtRegistration { get; set; }
        public DateTime RegisterDate { get; set; }

        [ForeignKey("UserID")]
        public TUser User { get; set; }
        public string UserID { get; set; }
    }


when i add new MainUser to db everything going good
but when i want extract data from db and write below query:

_context.Users.Include(u=>u.ExteraInformation).Single(u=>u.ID == MyId)

program throw System.InvalidOperationException

System.InvalidOperationException: The expression 'u.ExteraInformation' is invalid inside an 'Include' operation, since it does not represent a property access: 't => t.MyProperty'. To target navigations declared on derived types, use casting ('t => ((Derived)t).MyProperty') or the 'as' operator ('t => (t as Derived).MyProperty'). Collection navigation access can be filtered by composing Where, OrderBy(Descending), ThenBy(Descending), Skip or Take operations. For more information on including related data, see http://go.microsoft.com/fwlink/?LinkID=746393.
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.PopulateIncludeTree(IncludeTreeNode includeTreeNode, Expression expression, Boolean setLoaded)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ProcessInclude(NavigationExpansionExpression source, Expression expression, Boolean thenInclude, Boolean setLoaded)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Single[TSource](IQueryable`1 source, Expression`1 predicate)
   at test.Controllers.WeatherForecastController.Get(String id) in C:\Users\aaa\Desktop\test\Controllers\WeatherForecastController.cs:line 57
   at lambda_method227(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

can anyone help me ?

**Comment by ajcvickers** [comment]
@jumpinjackie `AuthUser<TUser>.ExteraInformation` is marked as `NotMapped`. This tells EF that it should not be included in the model. You can map it by removing `NotMapped` and casting to the concrete type when configuring the relationship. For example:

```C#
        modelBuilder
            .Entity<MainUser>()
            .HasOne(e => (ExteraInformation<MainUser>)e.ExteraInformation)
            .WithOne(e => e.User);
```
