### ISSUE TITLE
Issues with injecting DBConnection into dbContext- Entity Framework 7-rc2-final(DI)

### ISSUE THREAD

**Issue by gollapudiramyak** [dotnet/efcore#4551]
Hi,

Not able to inject connection from Startup.cs. Getting the issue while accessing the context. Attached the error.
Code in StartUp.cs

``` c#
 public void ConfigureServices(IServiceCollection services)
        {
            services.AddEntityFramework()
        .AddSqlServer()
        .AddDbContext<HBE.Core.EFData.BloggingContext>(options =>
            options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]));
```

project.json

``` json
"dependencies": {
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final"
}
```

**Comment by rowanmiller** [comment]
@gollapudiramyak I don't see the error attached... can you share the exception message and stack trace

**Comment by gollapudiramyak** [comment]
![error](https://cloud.githubusercontent.com/assets/17201276/13030657/f54bddbe-d2a9-11e5-95ff-75b746b0315e.png)

Please find this.

**Comment by gollapudiramyak** [comment]
stack trace is
   at Microsoft.Data.Entity.Internal.DatabaseProviderSelector.SelectServices(ServiceProviderSource providerSource)
   at Microsoft.Data.Entity.Internal.DbContextServices.<>c__DisplayClass6_0.<Initialize>b__0()
   at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.Internal.DbContextServices.get_DatabaseProviderServices()
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.GetProviderServices(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c.<AddQuery>b__1_0(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Data.Entity.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.Data.Entity.Internal.InternalDbSet`1.<.ctor>b__2_0()
   at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at OrganisationDataStore.Get(Int32 id) in \Organisation\OrganisationDataStore.cs:line 34
   at OrganisationRepository.Get(Int32 id) in \Organisation\OrganisationRepository.cs:line 35
   at OrganisationManager.GetOrgs(Int32 orgID) in Organisation\OrganisationManager.cs:line 54
   at OrganisationController.Get(Int32 id) in \OrganisationController.cs:line 33

**Comment by rowanmiller** [comment]
The issue is that your configuration is all setup in DI, but then you are creating a new instance of the context - completely bypassing DI. Rather than creating instances of `BloggingContext`, just make it a constructor parameter on your controller and ASP.NET will take care of giving you one from DI.
