### ISSUE TITLE
`GroupBy` query cause error `Sequence contains more than one element`.

### ISSUE THREAD

**Issue by mo-esmp** [dotnet/efcore#4775]
I have query like this:

```
var data = _context.Invoices.Where(i => i.Status == InvoiceStatus.Paid) .GroupBy(i => new { ProductId = i.Service.Package.Product.Id })
 .Select(i => new
 {
     Id = i.Key.ProductId,
     Count = i.Count(),
     Amounts = i.Sum(s => s.PayableAmount)
 }).ToList();
```

when I run the query with EF version 7.0.0-rc1 I get this error:
`Sequence contains more than one element`.

here is stcktrace:

```
at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.<>c__DisplayClass79_0`1.<BindMemberExpression>b__0(IEnumerable`1 ps, IQuerySource qs)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpressionCore[TResult](MemberExpression memberExpression, IQuerySource querySource, Func`3 memberBinder)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpression[TResult](MemberExpression memberExpression, IQuerySource querySource, Func`3 memberBinder)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpression(MemberExpression memberExpression, Action`2 memberBinder)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.RequiresMaterializationExpressionVisitor.VisitMember(MemberExpression memberExpression)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitMember(MemberExpression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.RequiresMaterializationExpressionVisitor.VisitMember(MemberExpression memberExpression)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitMember(MemberExpression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.RequiresMaterializationExpressionVisitor.VisitMember(MemberExpression memberExpression)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitAndConvert[T](ReadOnlyCollection`1 nodes, String callerName)
   at Remotion.Linq.Parsing.RelinqExpressionVisitor.VisitNew(NewExpression expression)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
   at Remotion.Linq.Clauses.ResultOperators.GroupResultOperator.TransformExpressions(Func`2 transformation)
   at Remotion.Linq.QueryModel.TransformExpressions(Func`2 transformation)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.RequiresMaterializationExpressionVisitor.VisitSubQuery(SubQueryExpression subQueryExpression)
   at Remotion.Linq.Clauses.Expressions.SubQueryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
   at Remotion.Linq.Clauses.FromClauseBase.TransformExpressions(Func`2 transformation)
   at Remotion.Linq.QueryModel.TransformExpressions(Func`2 transformation)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.RequiresMaterializationExpressionVisitor.FindQuerySourcesRequiringMaterialization(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.QueryCompilationContext.FindQuerySourcesRequiringMaterialization(EntityQueryModelVisitor queryModelVisitor, QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass18_0`1.<CompileQuery>b__0()
   at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Implementation.Product.ProductRepository.GetProducSaleReport(SaleFilterDto filter, Int64& totalCount) in D:\Projects\SalePortal\SalePortal\Implementation\Product\ProductRepository.cs:line 62
   at Implementation.Product.ProductService.GetSaleList(SaleFilterDto filter, Int64& totalCount) in D:\Projects\SalePortal\SalePortal\Implementation\Product\ProductService.cs:line 107
   at Web.Admin.Controllers.ReportController.GetSales(SaleFilterDto filter) in D:\Projects\SalePortal\SalePortal\Web.Admin\Controllers\ReportController.cs:line 145
```

Why there is `Single` in generated query:
 `System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)  ...`

Query works fine in LINQPad and here is generated TSQL:

```
DECLARE @p0 Int = 2
-- EndRegion
SELECT COUNT(*) AS [Count], SUM([t0].[PayableAmount]) AS [Amounts], [t3].[Id] AS [ServiceName]
FROM [Invoice] AS [t0]
INNER JOIN [Service] AS [t1] ON [t1].[Id] = [t0].[ServiceId]
INNER JOIN [Package] AS [t2] ON [t2].[Id] = [t1].[PackageId]
INNER JOIN [Product] AS [t3] ON [t3].[Id] = [t2].[ProductId]
WHERE [t0].[Status] = @p0
GROUP BY [t3].[Id]
```

**Comment by rowanmiller** [comment]
Can you try `.GroupBy(i => i.Service.Package.Product.Id)` rather than `.GroupBy(i => new { ProductId = i.Service.Package.Product.Id })`

**Comment by mo-esmp** [comment]
I tried and got same error.

**Comment by anpete** [comment]
This should be fixed now. Please re-open if you experience any issues.
