### ISSUE TITLE
Sqlite migrations: Update database throws BadImageFormatException

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#4794]
EF version - 1.0.0-rc2-20207
Migration is created successfully.
Trying to update database throws exception.

```
D:\TestInsights\src\TestInsights.Data [master +2 ~3 -0 !]> dotnet ef database update
System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at Microsoft.Data.Sqlite.Interop.NativeMethods.Sqlite3_sqlite3.sqlite3_open_v2(IntPtr filename, Sqlite3Handle& ppDb, Int32 flags, IntPtr vfs)
   at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(String filename, Sqlite3Handle& ppDb, Int32 flags, String vfs)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Commands.DatabaseUpdateCommand.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Commands.Program.Main(String[] args)
An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
```

Work-around: Copy `%userprofile%\.nuget\packages\Microsoft.Data.Sqlite\1.0.0-rc2-20207\runtimes\win7-x64\native\sqlite3.dll` to the project directory from where ef commands are being run.

**Comment by bricelam** [comment]
This was *supposed* to be fixed by #4713 :cry:

**Comment by natemcmaster** [comment]
Dug into this a little more. It looks like the [`ProjectContextBuilder`](https://github.com/dotnet/cli/blob/d5f118273b21a9ca70c9a2d0793be9c977f606a5/src/Microsoft.DotNet.ProjectModel/ProjectContextBuilder.cs#L390) does not automatically select the runtime identifier.

**Comment by bricelam** [comment]
I uses it [in this code](https://github.com/dotnet/cli/blob/f0c2cb2c1806b8c699352d0a15fbdf45672dbf07/src/Microsoft.DotNet.ProjectModel/ProjectContextBuilder.cs#L189-L198).

**Comment by natemcmaster** [comment]
Right. In some cases, `projectContext.RuntimeIdentifier == null`. This may be a bug in the versions of ProjectModel we are currently building against

**Comment by bricelam** [comment]
Covered by parent item #3925
