### ISSUE TITLE
Saving multiple entities with non-generated keys fail on EF7 (only in K)

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#481]
Consider the following:

```
public class Squad
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class MyContext : DbContext
{
    public MyContext(DbContextOptions options)
        : base(options)
    {
    }

    public DbSet<Squad> Squads { get; set; }

    protected override void OnConfiguring(DbContextOptions options)
    {
        options.UseSqlServer(@"Data Source=(localdb)\mssqllocaldb;Initial Catalog=EF7SquadBug;Integrated Security=True;MultipleActiveResultSets=True");
    }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.Model.GetEntityType(typeof(Squad)).GetProperty("Id").ValueGenerationOnAdd = ValueGenerationOnAdd.None;
    }

}


public class Program
{
    public static void Main(string[] args)
    {

        var contextOptions = new DbContextOptions();
        using (var ctx = new MyContext(contextOptions))
        {
            ctx.Database.EnsureDeleted();
            ctx.Database.EnsureCreated();

            var deltaSquad = new Squad
            {
                Id = 1,
                Name = "Delta",
            };

            ctx.Squads.Add(deltaSquad);

            var kiloSquad = new Squad
            {
                Id = 2,
                Name = "Kilo",
            };

            ctx.Squads.Add(kiloSquad);
            ctx.SaveChanges();

        }
    }
}
```

When run on K, this throws the following exception:

The instance of entity type 'Squad' cannot be tracked because another instance of this type with the same key is already being tracked. For new entities consider using an IIdentityGenerator to generate unique key values.

   at Microsoft.Data.Entity.Relational.Update.ModificationCommandBatch.<ExecuteAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Data.Entity.Relational.Update.BatchExecutor.<ExecuteAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Data.Entity.ChangeTracking.StateManager.<SaveChangesAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Data.Entity.ChangeTracking.StateManager.<SaveChangesAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Data.Entity.DbContext.SaveChanges()
   at EF7SquadBug.Program.Main(String[] args) in C:\Repros\EF7SquadBug\EF7SquadBug\Program.cs:line 61

This works when run in EF7 on 4.5.1

**Comment by MatthewMWR** [comment]
I seem to be hitting this again in beta7, but only intermittently and under load. Seems to be some kind of timing/concurrency issue. I'll re-open if I can come up with a reliable repro.
