### ISSUE TITLE
Installing EntityFrameworkCore.Sqlite did not bring in Logging.Abstractions

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#4816]
Normal csproj solution. Used NuGet VS GUI to install packages.

Got exception at runtime that Logging.Abstractions was not found. Installing the package fixed it.

**Comment by ajcvickers** [comment]
Also didn't get Microsoft.Extensions.Primitives

```
Test 'RocketProfiler.Test.ControllerTest.Controller_can_persist_runs' failed: System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.Extensions.Primitives, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
	at Microsoft.Extensions.Caching.Memory.MemoryCache.TryGetValue(Object key, Object& value)
	at Microsoft.Extensions.Caching.Memory.CacheExtensions.TryGetValue[TItem](IMemoryCache cache, Object key, TItem& value)
	at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
	at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
	at Remotion.Linq.QueryableBase`1.GetEnumerator()
	at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Collections.Generic.IEnumerable<TEntity>.GetEnumerator()
	at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
	ControllerTest.cs(135,0): at RocketProfiler.Test.ControllerTest.Controller_can_persist_runs()
```

**Comment by rowanmiller** [comment]
Need to isolate issue and file with appropriate team

**Comment by divega** [comment]
Talked to @bricelam and we don't believe this is a ship stopper for RC2 (he was planning to just test that things work as expected with a clean feed and the latest versions, etc.), so moving to RTM.

**Comment by ErikEJ** [comment]
@divega Would this also affect the SQL CE provider (I only reference EFC.Relational)

**Comment by natemcmaster** [comment]
We haven't seen customer reports of this. This may have just been a point-in-time error as packages have changed.
