### ISSUE TITLE
Migrations tests fail with "Sequence contains no matching element"

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/efcore#4841]
```
System.TypeInitializationException : The type initializer for 'Microsoft.EntityFrameworkCore.Relational.Design.FunctionalTests.TestUtilities.BuildReference' threw an exception.
---- System.InvalidOperationException : Sequence contains no matching element
```

An example of the failing build: http://aspnetci/viewLog.html?buildId=75039&buildTypeId=Lite_EntityFrameworkTest&tab=buildLog

We have skipped those tests in the mean time, once they're fixed they should be un-skipped.

**Comment by natemcmaster** [comment]
More context: https://github.com/dotnet/cli/issues/1707. Looks like we may need to make big change our dynamic compilation tests

**Comment by bricelam** [comment]
Most of that code was to deal with in-memory assemblies on DNX. I suspect we can remove a lot of it since the assemblies we need will most likely already be loaded. (Assuming we can get their paths without DependencyModel.)

**Comment by natemcmaster** [comment]
Blocked on upgrading to the latest CLI

**Comment by smitpatel** [comment]
Only CodeCompilationTests fail now.  (rest passes). Also exception message is different.
````
Microsoft.EntityFrameworkCore.Commands.Migrations.CodeCompilationTest.Migrations_compile [FAIL]
      System.InvalidOperationException : Build failed. Diagnostics: error CS1705: Assembly 'Microsoft.EntityFrameworkCore.Commands.FunctionalTests' with identity 'Microsoft.EntityFrameworkCore.Commands.FunctionalTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' uses 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
      error CS1705: Assembly 'Microsoft.EntityFrameworkCore.Commands.FunctionalTests' with identity 'Microsoft.EntityFrameworkCore.Commands.FunctionalTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' uses 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
      warning CS1702: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Text.RegularExpressions' matches identity 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy
      warning CS1702: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Text.RegularExpressions' matches identity 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy
      warning CS1702: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Text.RegularExpressions' matches identity 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy
      warning CS1702: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Text.RegularExpressions' matches identity 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy
      Stack Trace:
        D:\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational.Design.Specification.Tests\TestUtilities\BuildSource.cs(102,0): at Microsoft.EntityFrameworkCore.Relational.Design.FunctionalTests.TestUtilities.BuildSource.BuildInMemory()
        D:\EntityFramework\test\Microsoft.EntityFrameworkCore.Commands.FunctionalTests\Migrations\CodeCompilationTest.cs(116,0): at Microsoft.EntityFrameworkCore.Commands.Migrations.CodeCompilationTest.Migrations_compile()
````

**Comment by natemcmaster** [comment]
On mono or .NET Core?

**Comment by smitpatel** [comment]
The tests are disabled for CoreCLR framework. and `dotnet test` passes on windows. Haven't tried on mono yet.

**Comment by rowanmiller** [comment]
Consolidated into https://github.com/aspnet/EntityFramework/issues/5346
