### ISSUE TITLE
Problem deleting a dependent entity.

### ISSUE THREAD

**Issue by Bartmax** [dotnet/efcore#4866]
I'm having this problem for hours trying to do lot of stuff on fluent configuration, etc. But mainly, I have this entities.

```
public class Review
    {
        public int Id { get; set; }

        public string Text { get; set; }

        public string Source { get; set; }

        public string SourceUrl { get; set; }

        public int GameId { get; set; }

        public Game Game { get; set; }
    }

public class Game
    {
        public Game()
        {
            Reviews = new List<Review>();
        }

        public int Id { get; set; }

        public string Title { get; set; }

        public ICollection<Review> Reviews { get; set; }

    }

and when executing this action:

public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Review review = await _context.Review.SingleAsync(m => m.Id == id);
            _context.Remove(review);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
```

I get this error:

A database operation failed while processing the request.
AggregateException: One or more errors occurred. 
AggregateException: One or more errors occurred. 
InvalidOperationException: Operation is not valid due to the current state of the object. 

also tried to specify `builder.Entity<Review>().HasOne(r => r.Game).WithMany(g => g.Reviews);` with no luck.

please if someone can give me some idea of what's going on, this is a very simple and common scenario so I might be doing something wrong.

**Comment by Bartmax** [comment]
added more info from console:
```
info: Microsoft.Data.Entity.Storage.Internal.RelationalCommandBuilderFactory[1]
      Executed DbCommand (0ms) [Parameters=[@__id_0='?'], CommandType='Text', CommandTimeout='30']
      SELECT TOP(2) [m].[Id], [m].[GameId], [m].[Source], [m].[SourceUrl], [m].[Text]
      FROM [Review] AS [m]
      WHERE [m].[Id] = @__id_0
fail: Microsoft.Data.Entity.Query.Internal.SqlServerQueryCompilationContextFactory[1]
      An exception occurred in the database while iterating the results of a query.
      System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.Data.Entity.Query.Internal.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
         --- End of inner exception stack trace ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.Data.Entity.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
      ---> (Inner Exception #0) System.InvalidOperationException: Operation is not valid due to the current state of the object.
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.Data.Entity.Query.Internal.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()<---
```

**Comment by Bartmax** [comment]
nevermind, problem was a route prefix that wasn't sending the Id throught the controller.
