### ISSUE TITLE
ArgumentNullReferenceException when Changing Entity State

### ISSUE THREAD

**Issue by SilenceDoGood** [dotnet/efcore#4887]
First id like to say I'm a veteran .Net developer, but I'm unfamiliar with previous versions of EF, meaning that my solution to this problem is probably incorrect. That said, I'm in the process of seeding a database with data deserialized from json. I'm having trouble adding children of children in my object graph. I have read the following issues [4678](https://github.com/aspnet/EntityFramework/issues/4678) and [4424](https://github.com/aspnet/EntityFramework/issues/4424), and am aware that EF7 currently will not go deeper then one child navigation property in the object graph. My **CreateDatabaseAndSeedIfNonExist** method is currently seeding the information. The exception is thrown when i attempt to add an entry and change its EntityState. The Stack trace shows the exception originates in an EFCore method, but the argument I supplied isn't a null value.

Is there an easy way to add children of children to my add operations?

-AND-

Is this exception expect behavior?

``` C#
public class Family
    {
        public long Id { get; set; }

        public DateTime EntryDate { get; set; }

        public DateTime DateLastUpdated { get; set; }

        [Required]
        public virtual PointOfContact Contact { get; set; }

        public virtual ICollection<PlayTester> PlayTesters { get; set; }
    } 
```

``` C#
public class PlayTester
    {
        public long Id { get; set; }

        public string FirstName { get; set; }

        public string Notes { get; set; }

        public DateTime DOB { get; set; }

        public string Gender { get; set; }

        //[ForeignKey("Family")]
        //public long FamilyId { get; set; }

        public virtual Family Family { get; set; }

        public virtual ICollection<PlayTesterHistory> History { get; set; }
    } 
```

``` C#
public class PlayTesterHistory
    {
        public long Id { get; set; }

        public DateTime DateOfPlayTest { get; set; }

        public DateTime TimeEntered { get; set; }

        public string Phase { get; set; }

        public string Location { get; set; }

        public string Publisher { get; set; }

        public virtual Game GamePlayed { get; set; }

        public string Note { get; set; }

        [ForeignKey("Tester")]
        public long PlayTesterId { get; set; }

        public virtual PlayTester Tester { get; set; }
    }
```

``` C#
public bool CreateDatabaseAndSeedIfNonExists() 
        {
            if (Database.EnsureCreated())
            {
                var settings = new JsonSerializerSettings() { Formatting = Formatting.Indented, TypeNameHandling = TypeNameHandling.Objects };
                List<Family> families = JsonConvert.DeserializeObject<List<Family>>(File.ReadAllText("D:\\Projects\\contractordb\\src\\PlayTesterDB\\FPC-DB.json"), settings);
                foreach (var family in families)
                {
                    Families.Add(family);
                    if(family.PlayTesters != null && family.PlayTesters.Count > 0)
                    {
                        Entry(family.PlayTesters).State = EntityState.Added; //Argument Null reference Exception thrown here
                        var testers = family.PlayTesters.ToList();

                        for (int i = 0; i < testers.Count; i++)
                        {
                            Entry(testers[i].History).State = EntityState.Added;
                        }
                    }
                }
                SaveChanges();
                return false;
            }
            return true;
        }
```

``` C#
System.ArgumentNullException was unhandled by user code
  HResult=-2147467261
  Message=Value cannot be null.
Parameter name: entityType
  ParamName=entityType
  Source=EntityFramework.Core
  StackTrace:
       at Microsoft.Data.Entity.Utilities.Check.NotNull[T](T value, String parameterName)
       at Microsoft.Data.Entity.Metadata.Internal.EntityTypeExtensions.HasClrType(IEntityType entityType)
       at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntryFactory.NewInternalEntityEntry(IStateManager stateManager, IEntityType entityType, Object entity)
       at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntryFactory.Create(IStateManager stateManager, IEntityType entityType, Object entity)
       at Microsoft.Data.Entity.ChangeTracking.Internal.StateManager.GetOrCreateEntry(Object entity)
       at Microsoft.Data.Entity.DbContext.EntryWithoutDetectChanges[TEntity](TEntity entity)
       at Microsoft.Data.Entity.DbContext.Entry[TEntity](TEntity entity)
       at PlayerTesterDB.Models.PlayerTesterContext.CreateDatabaseAndSeedIfNonExists() in D:\Projects\contractordb\src\PlayTesterDB\Models\PlayerTesterContext.cs:line 52
       at PlayerTesterDB.Models.PlayerTesterContext.CreateDatabaseAndSeedIfNonExists() in D:\Projects\contractordb\src\PlayTesterDB\Models\PlayerTesterContext.cs:line 65
       at PlayerTesterDB.Models.PlayerTesterContext..ctor() in D:\Projects\contractordb\src\PlayTesterDB\Models\PlayerTesterContext.cs:line 16
  InnerException: 
```

**Comment by Artur2** [comment]
I think Entry method not support collection search, try pass only one object.

**Comment by SilenceDoGood** [comment]
@Artur2 I'll give it a try, and let you know. Thanks.

**Comment by SilenceDoGood** [comment]
@Artur2 That seemed to almost work. It worked on the Playtester Objects, but there is another child in the PlayTester Object that needs to be entered. I'm no longer receiving a Null Argument exception, but the history Table isn't being populated. You've got me here maybe you have a suggestion to get me one step further?

```c#
public bool CreateDatabaseAndSeedIfNonExists()
        {
            if (Database.EnsureCreated())
            {
                var settings = new JsonSerializerSettings() { Formatting = Formatting.Indented, TypeNameHandling = TypeNameHandling.Objects };
                List<Family> families = JsonConvert.DeserializeObject<List<Family>>(File.ReadAllText("D:\\Projects\\contractordb\\src\\PlayTesterDB\\FPC-DB.json"), settings); //TODO: Remove hardcoded URI
                foreach (var family in families)
                {
                    Families.Add(family);
                    if (family.PlayTesters != null && family.PlayTesters.Count > 0)
                    {
                        var testers = family.PlayTesters.ToList();

                        for (int i = 0; i < testers.Count; i++)
                        {
                            Entry(testers[i]).State = EntityState.Added;
                            var histories = testers[i].History.ToList();
                            for (int j = 0; j < histories.Count; j++)
                            {
                                Entry(histories[j]).State = EntityState.Added;
                            }
                        }
                    }
                }
                SaveChanges();
                return false;
            }
            return true;
        }

```

**Comment by SilenceDoGood** [comment]
@Atur2 Your method worked completely. My JSON data was incomplete. Once I realized this, it was easy to resolve. Thanks
