### ISSUE TITLE
Query: Incorrect result or exception in materializer when query projects to anonymous type with collection aggregate 

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#4908]
With Northwind db following query fails

``` c#
var q = from o in context.Orders.Include(e => e.OrderDetails)
        select new
        {
            Id = o.OrderID,
            Name = o.ShipName,
            TotalDetails = o.OrderDetails.Count
        };

var result = q.ToList();
```

with

```
Test 'Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.QuerySqlServerTest.Test' failed: System.InvalidCastException : Unable to cast object of type 'System.Int32' to type 'System.String'.
    at lambda_method(Closure , ValueBuffer )
    Query\EntityLoadInfo.cs(27,0): at Microsoft.EntityFrameworkCore.Query.EntityLoadInfo.Materialize()
    Query\Internal\QueryBuffer.cs(70,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.GetEntity(IKey key, EntityLoadInfo entityLoadInfo, Boolean queryStateManager, Boolean throwOnNullKey)
    Query\ExpressionVisitors\Internal\BufferedEntityShaper`.cs(32,0): at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.BufferedEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
    Query\QueryMethodProvider.cs(39,0): at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
    Query\Internal\LinqOperatorProvider.cs(125,0): at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
    QueryTestBase.cs(4824,0): at Microsoft.EntityFrameworkCore.FunctionalTests.QueryTestBase`1.Test()
    QuerySqlServerTest.cs(4728,0): at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.QuerySqlServerTest.Test()
```

Because generated query has different ordering of columns than what materializer expect.
In this example, value generated from count is being used for Name. If the types are same then instead of exception it will produce incorrect result.

**Comment by smitpatel** [comment]
`ShipName` was ignored hence failure. Should add this to #4289
