### ISSUE TITLE
Query :: comparing collection navigation to null or another navigation throws

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#4936]
Repro:

``` cs
    public class Customer
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public List<Order> Orders { get; set; }
    }

    public class Order
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Order> Orders { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=.;Database=Repro4936;Trusted_Connection=True;MultipleActiveResultSets=true;");
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                var query = ctx.Customers.Where(c => c.Orders != null).Select(c => c.Name);
                var result = query.ToList();
            }
        }
    }
```

this throws during query compilation: 

Unhandled Exception: System.InvalidOperationException: The property 'CustomerId' on entity type 'Customer' could not be found. Ensure that the property exists and has been included in the model.
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindMethodCallExpression[TResult](MethodCallExpression methodCallExpression, IQuerySource querySource, Func`3 methodCallBinder) in D:\k\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\EntityQueryModelVisitor.cs:line 1208
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindMethodCallExpression(MethodCallExpression methodCallExpression, Action`2 methodCallBinder) in D:\k\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\EntityQueryModelVisitor.cs:line 1166
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.RequiresMaterializationExpressionVisitor.VisitMethodCall(MethodCallExpression node) in D:\k\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\ExpressionVisitors\Internal\RequiresMaterializationExpressionVisitor.cs:line 93
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression node) in D:\k\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\ExpressionVisitors\ExpressionVisitorBase.cs:line 15
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.RequiresMaterializationExpressionVisitor.VisitBinary(BinaryExpression node) in D:\k\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\ExpressionVisitors\Internal\RequiresMaterializationExpressionVisitor.cs:line 136
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression node) in D:\k\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\ExpressionVisitors\ExpressionVisitorBase.cs:line 15
   at Remotion.Linq.Clauses.WhereClause.TransformExpressions(Func`2 transformation)
   at Remotion.Linq.QueryModel.TransformExpressions(Func`2 transformation)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.RequiresMaterializationExpressionVisitor.FindQuerySourcesRequiringMaterialization(QueryModel queryModel) in D:\k\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\ExpressionVisitors\Internal\RequiresMaterializationExpressionVisitor.cs:line 38
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.FindQuerySourcesRequiringMaterialization(EntityQueryModelVisitor queryModelVisitor, QueryModel queryModel) in D:\k\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\QueryCompilationContext.cs:line 227
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel) in D:\k\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\EntityQueryModelVisitor.cs:line 161
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel) in D:\k\EntityFramework\src\Microsoft.EntityFrameworkCore\Storage\Database.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileQuery>b__0() in D:\k\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\Internal\QueryCompiler.cs:line 181
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) in D:\k\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\Internal\CompiledQueryCache.cs:line 33
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query) in D:\k\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\Internal\QueryCompiler.cs:line 136
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query) in D:\k\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\Internal\QueryCompiler.cs:line 82
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression) in D:\k\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\Internal\EntityQueryProvider.cs:line 37
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

**Comment by maumar** [comment]
This is because the logic that processes collection navigation expects it to be wrapped in a subquery. It is usually the case, e.g.e.g.
ctx.Customers.Where(c => c.Orders.Count() = 3).Select(c => c.Name); 

Orders.Count() would be wrapped, but in case of comparing a collection to a constant or another collection, the subquery is not introduced. We could could detect those cases and inject subqueries where appropriate.

**Comment by maumar** [comment]
Reassigning to @smitpatel as he is already working on a very similar issue (https://github.com/aspnet/EntityFramework/issues/6383)
