### ISSUE TITLE
Exception when chaining Include and ThenInclude on optional one-many relationships

### ISSUE THREAD

**Issue by Tamayi** [dotnet/efcore#4943]
I have an EF7 project with three classes:

`Characteristic` -> `CharacteristicValues` -> `CharacteristicValueAliases`
These are meant to model data used in a data warehousing exercise with data such as:
- [`Age`] -> [`5 years and above`] -> [`5+`, `5 years and older`, `5 plus`, `School Going Age`]
- [`Age`] -> [`1-4 years`] -> [`1-4`, `Preschooler`, `PreSchool Going Age`]
- [`Disease` -> [`Malaria`] -> [] _no aliases_

During processing of an input file, once I determine the `Characteristic`, I then need to identify the value i.e. given `5 plus`, I need to determine that this is actually `5+` and map the value to this.

```
var result = db.Characteristics
    .Where(c => c.CharacteristicName == "Age")
    .Include(c => c.CharacteristicValues).ThenInclude(cv => cv.CharacteristicValueAliases)
    .Where(c =>
        c.CharacteristicValues.Any(cv => cv.CharacteristicValueName == "5 plus") /*characteristic value is a match*/
        ||
        c.CharacteristicValues.Any(cv => cv.CharacteristicValueAliases.Any(cva => cva.Alias == "5 plus") /*alias of characteristic value is a match*/
    )
    .ToList();
```

This fails with the message. I suspect it fails on the `.ThenInclude(cv => cv.CharacteristicValueAliases)`, but how does one rewrite this? Also, is there a way to improve the error message so that it gives more context to the failure?

```
System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Anonymously Hosted DynamicMethods Assembly
  StackTrace:
       at lambda_method(Closure , ValueBuffer )
       at Microsoft.Data.Entity.Query.EntityLoadInfo.Materialize()
       at Microsoft.Data.Entity.Query.Internal.QueryBuffer.GetEntity(IKeyValue keyValue, EntityLoadInfo entityLoadInfo, Boolean queryStateManager)
       at Microsoft.Data.Entity.Query.Internal.QueryBuffer.<>c__DisplayClass12_0.<Include>b__0(EntityLoadInfo eli)
       at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at Microsoft.Data.Entity.Query.Internal.QueryBuffer.Include(Object entity, IReadOnlyList`1 navigationPath, IReadOnlyList`1 relatedEntitiesLoaders, Int32 currentNavigationIndex, Boolean queryStateManager)
       at Microsoft.Data.Entity.Query.Internal.QueryBuffer.Include(Object entity, IReadOnlyList`1 navigationPath, IReadOnlyList`1 relatedEntitiesLoaders, Boolean queryStateManager)
       at Microsoft.Data.Entity.Query.QueryMethodProvider.<>c__DisplayClass19_0`1.<_Include>b__2(T r)
       at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at Microsoft.Data.Entity.EnumerableExtensions.<Finally>d__0`1.MoveNext()
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at Microsoft.Data.Entity.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at Testbed.Program.Main(String[] args) in C:\Git\Prject1\src\Testbed\Program.cs:line 161
  InnerException: 
```

**Comment by Tamayi** [comment]
The class definitions: code-first conventions.

>     public partial class Characteristics
>     {
>         public int CharacteristicID { get; set; }
>         public bool ActiveRecord { get; set; }
>         public string CharacteristicDescription { get; set; }
>         public string CharacteristicName { get; set; }
> 
>         public virtual ICollection<CharacteristicValues> CharacteristicValues { get; set; } = new List<CharacteristicValues>();
> 
>     }
> 
>     public partial class CharacteristicValues
>     {
>         public int CharacteristicValueID { get; set; }
>         public bool ActiveRecord { get; set; }
>         public int CharacteristicID { get; set; }
>         public int? CharacteristicValueCode { get; set; }
>         public string CharacteristicValueName { get; set; }
>         
>         public virtual Characteristics Characteristic { get; set; }
>         public virtual ICollection<CharacteristicValueAlias> CharacteristicValueAliases { get; set; } = new List<CharacteristicValueAlias>();
> 
>     }
> 
>     public partial class CharacteristicValueAlias
>     {
>         public int CharacteristicValueAliasID { get; set; }
>         public bool ActiveRecord { get; set; }
>         public int CharacteristicValueID { get; set; }
>         public string Name { get; set; }
> 
>         public virtual CharacteristicValues CharacteristicValue { get; set; }
> 
>     }
>

**Comment by Tamayi** [comment]
The issue was related to a mismatch between the database and the model. The model was not expecting NULL values in a column which turned out to have been modified to allow null values. That said, the error message from EF was not useful in figuring this one out.

**Comment by divega** [comment]
@Tamayi thanks for the explanation. We are planning to improve exceptions for cases like this before RTM. See #4289.
