### ISSUE TITLE
EF7 with Asp.Net Core RC2

### ISSUE THREAD

**Issue by gpeipman** [dotnet/efcore#4965]
I'm trying to get my web application running with RC2 of ASP.NET Core and CoreCLR. When my application loads Entity Framework and configures it I get the following error:

Application startup exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: Method not found: 'Void Microsoft.Extensions.Logging.ILogger.Log(Microsoft.Extensions.Logging.LogLevel, Int32, System.Object, System.Exception, System.Func`3<System.Object,System.Exception,System.String>)'.
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.AddEntityFramework(IServiceCollection serviceCollection)
   at BeerStore.Web.Common.CommonStartup.ConfigureServices(IServiceCollection services) in D:\Projects\BeerStore\BeerStore.Web.Common\CommonStartup.cs:line 46
   at BeerStore.Web.Public.Startup.ConfigureServices(IServiceCollection services) in D:\Projects\BeerStore\BeerStore.Web.Public\Startup.cs:line 19
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.Startup.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection exportServices)
   at Microsoft.AspNetCore.Hosting.Startup.ConfigureServicesBuilder.<>c__DisplayClass4_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

Is it something on EF7 side or is it something related to packages I use?

**Comment by Grinderofl** [comment]
You need to use package "EntityFrameworkCore" version 1.0.0 rather than "EntityFramework" version 7.0.0

**Comment by rowanmiller** [comment]
As mentioned by @Grinderofl , this is a mixed-versions issue. If you are using RC2 of ASP.NET and CoreCLR you need to also use the 1.0.0-rc2-* version of the EF packages. Note the packages are also renamed (`EntityFrameworkCore.SqlServer`, etc.).
