### ISSUE TITLE
Sub query with `let` keyword cause exception "Int64 Id' is not defined for type 'Microsoft.Data.Entity.Storage.ValueBuffer"

### ISSUE THREAD

**Issue by mo-esmp** [dotnet/efcore#4969]
I have query like this:

```
var query = (from stack in _context.ServiceStacks
                         let customerId = _context.Services.FirstOrDefault(s => s.Id == serviceId).CustomerId
                         let domain = _context.CustomerStackInfos.FirstOrDefault(c => c.Customer.Id == customerId)
                         where cloduStack.ServiceId == serviceId
                         select new
                         {
                             domain.DomainId,
                             domain.DomainName,
                             cloduStack.AccountId,
                             cloduStack.DiskId,
                             cloduStack.FirstPassword,
                             cloduStack.AccountPassword,
                             cloduStack.Ip,
                             cloduStack.VpsId,
                             cloduStack.VpsName
                         }).SingleOrDefault();
```

when I run the query with EF version 7.0.0-rc1 I get this error:

```
System.ArgumentException: Property 'Int64 CustomerId' is not defined for type 'Microsoft.Data.Entity.Storage.ValueBuffer'
   at System.Linq.Expressions.Expression.Property(Expression expression, PropertyInfo property)
   at System.Linq.Expressions.Expression.MakeMemberAccess(Expression expression, MemberInfo member)
   at System.Linq.Expressions.MemberExpression.Update(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitMember(MemberExpression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitMember(MemberExpression memberExpression)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
```

Query works fine in LINQPad and here is generated TSQL:

```
{-- Region Parameters
DECLARE @p0 BigInt = 141
DECLARE @p1 BigInt = 141
-- EndRegion
SELECT [t10].[value] AS [DomainId], [t10].[value2] AS [DomainName], [t10].[AccountId], [t10].[DiskId], [t10].[FirstPassword], [t10].[AccountPassword], [t10].[Ip], [t10].[VpsId], [t10].[VpsName]
FROM (
    SELECT (
        SELECT [t6].[DomainId]
        FROM (
            SELECT TOP (1) [t4].[DomainId]
            FROM [SStackInfo] AS [t4]
            INNER JOIN [Customer] AS [t5] ON [t5].[Id] = [t4].[CustomerId]
            WHERE [t5].[Id] = [t3].[value]
            ) AS [t6]
        ) AS [value], (
        SELECT [t9].[DomainName]
        FROM (
            SELECT TOP (1) [t7].[DomainName]
            FROM [CustomerStackInfo] AS [t7]
            INNER JOIN [Customer] AS [t8] ON [t8].[Id] = [t7].[CustomerId]
            WHERE [t8].[Id] = [t3].[value]
            ) AS [t9]
        ) AS [value2], [t3].[AccountId], [t3].[DiskId], [t3].[FirstPassword], [t3].[AccountPassword], [t3].[Ip], [t3].[VpsId], [t3].[VpsName], [t3].[ServiceId]
    FROM (
        SELECT [t0].[DiskId], [t0].[FirstPassword], [t0].[Ip], [t0].[ServiceId], [t0].[VpsId], [t0].[VpsName], [t0].[AccountId], [t0].[AccountPassword], (
            SELECT [t2].[CustomerId]
            FROM (
                SELECT TOP (1) [t1].[CustomerId]
                FROM [Service] AS [t1]
                WHERE [t1].[Id] = @p0
                ) AS [t2]
            ) AS [value]
        FROM [ServiceStack] AS [t0]
        ) AS [t3]
    ) AS [t10]
WHERE [t10].[ServiceId] = @p1}
```

**Comment by PhilAtWysdom** [comment]
I am experiencing the same. The issue occurs when I use more than one property from the sub-table that has been associated with the identifier "l". The query runs fine so long as no more than one of the properties of the subquery are referenced by the anonymous object. 

Here is my example:

var detail = (from site in _context.Sites
                          let l = (from lim in site.SiteSendLimits
                                   orderby lim.LimitLastChanged descending
                                   select lim).FirstOrDefault()
                          where site.Id == id
                          select new { site.Id, site.SiteName, site.Sender, site.ApprovalPassword, site.SitePublicKey, /*l.AgreedMonthlySendingLimit, l.LimitLastChanged,*/ l.LimitChangedBy }).FirstOrDefault()

**Comment by anpete** [comment]
This should be fixed now. Please re-open if you experience any further issues here.
