### ISSUE TITLE
Reference TPH entity twice

### ISSUE THREAD

**Issue by izverev-aexsoft** [dotnet/efcore#5001]
I stuck with the exception
"Sequence contains more than one matching element"
thrown on simple query

`_context.Calls.Include(i => i.ClientAccount).Include(i => i.InterpreterAccount).ToList()`

Here is Call entity

```
public class Call
{
        public int ClientAccountId { get; set; }
        public UserAccount ClientAccount { get; set; }

        public int? InterpreterAccountId { get; set; }
        public UserAccount InterpreterAccount { get; set; }
}
```

and UserAccount is root of TPH hierarchy. Two other navigation properties on the same Call entity (LanguageFrom/LanguageTo) that reference non-TPH entity are included without errors.

Do I need any specific code to include multiple navigation properties to TPH entities or is it a bug?

**Comment by maumar** [comment]
This works in current bits. Tried with the following repro. (Please let us know if your repro significantly differs from ours):

```cs
namespace Repro5001
{
    public class Call
    {
        public int Id { get; set; }

        public int ClientAccountId { get; set; }
        public UserAccount ClientAccount { get; set; }

        public int? InterpreterAccountId { get; set; }
        public UserAccount InterpreterAccount { get; set; }
    }

    public abstract class UserAccount
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class CustomerAccount : UserAccount
    {
        public string Address { get; set; }
    }


    public class InterpreterAccount : UserAccount
    {
        public string Language { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<Call> Calls { get; set; }

        public DbSet<UserAccount> UserAccounts { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<InterpreterAccount>().HasBaseType<UserAccount>();
            modelBuilder.Entity<CustomerAccount>().HasBaseType<UserAccount>();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=.;Database=Repro5001;Trusted_Connection=True;MultipleActiveResultSets=true;");
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

                var c1 = new CustomerAccount { Name = "c1", Address = "1 Microsoft Way", };
                var c2 = new CustomerAccount { Name = "c2", Address = "221B Baker Street", };
                var c3 = new CustomerAccount { Name = "c3", Address = "1 Infinite Loop", };

                var i1 = new InterpreterAccount { Name = "i1", Language = "Klingon", };
                var i2 = new InterpreterAccount { Name = "i2", Language = "Nilfgaardian", };

                var call1 = new Call { ClientAccount = c1, InterpreterAccount = i1 };
                var call2 = new Call { ClientAccount = c2, InterpreterAccount = i2 };
                var call3 = new Call { ClientAccount = c3, InterpreterAccount = null };

                ctx.UserAccounts.AddRange(c1, c2, c3, i1, i2);
                ctx.Calls.AddRange(call1, call2, call3);
                ctx.SaveChanges();
            }

            using (var ctx = new MyContext())
            {
                var query = ctx.Calls.Include(i => i.ClientAccount).Include(i => i.InterpreterAccount);
                var result = query.ToList();
            }
        }
    }

```

**Comment by izverev-aexsoft** [comment]
Hi, maumar! Thanks for checking this!
I've just created new console app, added EntityFramework.Core 7.0.0-rc1-final and EntityFramework.MicrosoftSqlServer 7.0.0-rc1-final packages.
I've used your code without any change and got the same error as before:

`An exception of type 'System.InvalidOperationException' occurred in EntityFramework.Core.dll but was not handled in user code

Additional information: Sequence contains more than one matching element`

Here is stack trace:
`   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.MaterializerFactory.CreateMaterializer(IEntityType entityType, SelectExpression selectExpression, Func`3 projectionAdder, IQuerySource querySource)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.IncludeExpressionVisitor.<CreateIncludeRelatedValuesStrategyFactories>d__13.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
   at System.Linq.Expressions.Expression.NewArrayInit(Type type, IEnumerable`1 initializers)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.IncludeExpressionVisitor.VisitMethodCall(MethodCallExpression expression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.IncludeExpressionVisitor.VisitMethodCall(MethodCallExpression expression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.IncludeNavigations(IncludeSpecification includeSpecification, Type resultType, LambdaExpression accessorLambda, Boolean querySourceRequiresTracking)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel, IReadOnlyCollection`1 includeSpecifications)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.IncludeNavigations(QueryModel queryModel, IReadOnlyCollection`1 includeSpecifications)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass18_0`1.<CompileQuery>b__0()
   at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at Microsoft.Data.Entity.EntityFrameworkQueryableExtensions.IncludableQueryable`2.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Repro5001.Program.Main(String[] args) in C:\Users\azverev\Documents\Visual Studio 2015\Projects\Repro5001\Repro5001\Program.cs:line 34`

**Comment by divega** [comment]
@izverev-aexsoft RC1 is not current bits and does not contain the fix. RC2 or packages from the aspnetcidev feed should work. Package names have changed so you can use Microsoft.EntityFrameworkCore.SqlServer.

**Comment by izverev-aexsoft** [comment]
Am I right that it's time to move project to CLI?..

**Comment by divega** [comment]
I would recommend to try to make the switch sooner rather than later. We are still in the process of stabilizing and restoring functionality on top of CLI but we have made tons of fixes and improvements across EF Core and the ASP.NET Core stack that will require it.
