### ISSUE TITLE
Null reference when using Take

### ISSUE THREAD

**Issue by jazzonaut** [dotnet/efcore#5112]
The following query:

```
var results = (from call in db.Calls
                select new
                {
                    IpkStatusName = call.StatusNavigation.Name
                }).Take(10);
```

Produces the following exception:

> Exception thrown: 'System.NullReferenceException' in Microsoft.EntityFrameworkCore.dll
> Additional information: Object reference not set to an instance of an object.

```
  at lambda_method(Closure , ValueBuffer )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.UnbufferedEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

Using build 20620 from the 19th or April.

**Comment by smitpatel** [comment]
Does following work?
````
var results = (from call in db.Calls.Include(c => c.StatusNavigation)
                select new
                {
                    IpkStatusName = call.StatusNavigation.Name
                }).Take(10);
````

**Comment by amokre** [comment]
Sorry, the entity of the StatusNavigation property was not properly bound in the model, it is all working fine now!
