### ISSUE TITLE
Unable to execute EF Migrations on dotnet core

### ISSUE THREAD

**Issue by Pilchie** [dotnet/efcore#5261]
### Minimal repro steps
1. Install the latest CLI (I've been using OSX, not sure if that matters)
2. Clone https://github.com/Pilchie/SquashNext/pull/2
3. `dotnet restore`
4. `dotnet ef migrations list`
### Expected result

The list of migrations.
### Actual result

```
pilchie@pilchie-mbp:~/code/SquashNext (UseEf u=)$ dotnet ef migrations list
Project SquashNext (.NETCoreApp,Version=v1.0) will be compiled because inputs were modified
Compiling SquashNext for .NETCoreApp,Version=v1.0
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:04.6589571

System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Scaffolding.SqliteDesignTimeServices' from assembly 'Microsoft.EntityFrameworkCore.Sqlite.Design, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.Build(DbContext context)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.GetMigrations(String contextType)
   at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsListCommand.Execute(CommonOptions commonOptions, String context, String startupProject, String environment, Action`1 reportResultsAction)
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)
Could not load type 'Microsoft.EntityFrameworkCore.Scaffolding.SqliteDesignTimeServices' from assembly 'Microsoft.EntityFrameworkCore.Sqlite.Design, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
pilchie@pilchie-mbp:~/code/SquashNext (UseEf u=)$ 
```
### Notes:
1. `dotnet --version`: 1.0.0-rc2-002543
2. Restore complains about package downgrades, and I end up with some rc3 packages.  Should I be specifying explicit versions in my project.json?  If so, which ones?

**Comment by natemcmaster** [comment]
>  I end up with some rc3 packages

This could be part of the problem. To ensure you are only getting RC2 bits, use this as your nuget.config

```xml
<configuration>
  <packageSources>
    <clear />
    <add key="aspnetrelease" value="https://www.myget.org/F/aspnetrelease/api/v3/index.json" />
    <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

And if you still have trouble, you may need to [clear nuget caches](https://gist.github.com/natemcmaster/eb0cbecc8b0b43353234e160f09fb8a8).

**Comment by natemcmaster** [comment]
@Pilchie I confirmed using my machine that when only using RC2 bits from the feeds I mentioned, this bug doesn't repro:

```
dotnet ef migrations list
Project SquashNext (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling SquashNext for .NETCoreApp,Version=v1.0
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:04.6430549
 
20160430200403_Initial
20160430203609_MakeNullable
```

```
Product Information:
 Version:     1.0.0-rc2-002543
 Commit Sha:  38d0c28a1e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

**Comment by Pilchie** [comment]
Awesome, that seems to work!
