### ISSUE TITLE
Method not found: Void Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator

### ISSUE THREAD

**Issue by spboyer** [dotnet/efcore#5295]
Converted to RC2 getting `Method not found: Void Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator` when running `DbSeeder.SeedAsyc()`

```
public async Task SeedAsync(IServiceProvider serviceProvider)
        {
            //Based on EF team's example at https://github.com/aspnet/MusicStore/blob/dev/src/MusicStore/Models/SampleData.cs#L23
            using (var serviceScope = serviceProvider.GetRequiredService<IServiceScopeFactory>().CreateScope())
            {
                var db = serviceScope.ServiceProvider.GetService<DockerCommandsDbContext>();

                if (await db.Database.EnsureCreatedAsync())
                {
                    if (!await db.DockerCommands.AnyAsync()) {
                      await InsertSampleData(db);
                    }
                }
            }
        }
```

Appears that the issue is on db.Database.EnsureCreatedAsync() when trying to create schema from migration.

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AggregateException: One or more errors occurred. (Method not found: 'Void Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator..ctor(Microsoft.EntityFrameworkCore.Metadata.IModel, Microsoft.EntityFrameworkCore.Storage.IRelationalConnection, Microsoft.EntityFrameworkCore.Migrations.IMigrationsModelDiffer, Microsoft.EntityFrameworkCore.Migrations.IMigrationsSqlGenerator)'.) ---> System.MissingMethodException: Method not found: 'Void Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator..ctor(Microsoft.EntityFrameworkCore.Metadata.IModel, Microsoft.EntityFrameworkCore.Storage.IRelationalConnection, Microsoft.EntityFrameworkCore.Migrations.IMigrationsModelDiffer, Microsoft.EntityFrameworkCore.Migrations.IMigrationsSqlGenerator)'.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreatedAsync(CancellationToken cancellationToken)
   at AspNetCorePostgreSQLDockerApp.Repository.DbSeeder.<SeedAsync>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at AspNetCorePostgreSQLDockerApp.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, DbSeeder dbSeeder)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at AspNetCorePostgreSQLDockerApp.Program.Main(String[] args)
```

See: https://github.com/spboyer/AspNetCorePostgreSQLDockerApp/tree/dotnet-cli

Updated: reference to proper branch. sorry @davidfowl

**Comment by davidfowl** [comment]
@spboyer Why does that application still use dnxcore50 and runtime specific packages? If you're going to use RC2, start from the CLI samples here https://github.com/aspnet/cli-samples.

**Comment by spboyer** [comment]
@davidfowl the cli-samples are not complete samples, just starter "HelloWorld", no EF, PostgreSQL etc.  Trying to convert this application over.  Started with the project.json from cli-samples.  Is there something specific I didn't replace? or Add/Remove?

It appears that the Sqlite provider doesn't have the `RelationalDatabaseCreator` method implemented

**Comment by spboyer** [comment]
@davidfowl and the **HelloMVC** example also has dependencies on dnxcore still in the samples

https://github.com/aspnet/cli-samples/blob/master/HelloMvc/project.json#L28

**Comment by davidfowl** [comment]
> @davidfowl the cli-samples are not complete samples, just starter "HelloWorld", no EF, PostgreSQL etc. Trying to convert this application over. Started with the project.json from cli-samples. Is there something specific I didn't replace? or Add/Remove?

Did you start from the samples? Here are some issues:

- You're targeting dnxcore50
- You still have a `hosting.json` https://github.com/spboyer/AspNetCorePostgreSQLDockerApp/blob/master/hosting.json
- You still have commands https://github.com/spboyer/AspNetCorePostgreSQLDockerApp/blob/master/project.json#L37-L40
- You still have excludes https://github.com/spboyer/AspNetCorePostgreSQLDockerApp/blob/master/project.json#L46-L50
- You're missing this dependency https://github.com/aspnet/cli-samples/blob/master/HelloMvc/project.json#L20-L23
- You're targeting runtime specific packages https://github.com/spboyer/AspNetCorePostgreSQLDockerApp/blob/master/project.json#L33-L34
- https://github.com/spboyer/AspNetCorePostgreSQLDockerApp/blob/master/nuget.config#L6 (this is the wrong feed)

> @davidfowl and the HelloMVC example also has dependencies on dnxcore still in the samples

How did you confuse import statements that contain dnxcore50 with targeting dnxcore50 the framework. Those are *completely* different things. You should copy the base project verbatim then change it from there.

**Comment by spboyer** [comment]
@davidfowl - Oy! I pasted the wrong branch for reference : https://github.com/spboyer/AspNetCorePostgreSQLDockerApp/tree/dotnet-cli

**Comment by spboyer** [comment]
> You should copy the base project verbatim then change it from there.

Esssentially what I did, and chased down the namespace changes 
also used this as a reference. https://github.com/aspnet/Home/issues/1381

**Comment by davidfowl** [comment]
That looks much better, you should remove this https://github.com/spboyer/AspNetCorePostgreSQLDockerApp/blob/dotnet-cli/project.json#L19, It's not required.

**Comment by spboyer** [comment]
So valid EF issue or something else you think

**Comment by divega** [comment]
That kind of exception is often a symptom of mixing new and stale package versions.

**Comment by spboyer** [comment]
@divega got all of the EF ones fresh, unless you are saying that there are some that are not updated?

**Comment by divega** [comment]
See https://github.com/aspnet/EntityFramework/issues/5241.

**Comment by spboyer** [comment]
Cleared nuget repos locally and `dotnet restore` repaired issue.  Need to add `--no-cache` option to `dotnet restore` perhaps? @davidfowl

**Comment by davidfowl** [comment]
It's already there.
