### ISSUE TITLE
CLI Command: dotnet ef fails to run on Windows 7

### ISSUE THREAD

**Issue by pranavkm** [dotnet/efcore#5313]
OS: Windows 7 Enterprise (Version 6.1 Build 7601)
dotnet --version: 1.0.0-rc2-002678
Microsoft.EntityFrameworkCore.Tools: 1.0.0-rc2-20828

Running `dotnet ef` fails with

```
System.IO.FileNotFoundException: Could not load file or assembly 'System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. The system cannot find the file specified.
File name: 'System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes'
   at Microsoft.DotNet.ProjectModel.ProjectReader.ReadProject(Stream stream, String projectName, String projectPath, ProjectReaderSettings settings)
   at Microsoft.DotNet.ProjectModel.ProjectReader.GetProject(String projectPath, ProjectReaderSettings settings)
   at Microsoft.EntityFrameworkCore.Tools.DispatchCommand.<>c__DisplayClass2_0.<Create>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Could not load file or assembly 'System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. The system cannot find the file specified.
```

This indicates something has the wrong import. However the same app works fine on Windows 10, CentOS 7.1, Ubuntu 14.04

Repo: https://github.com/pranavkm/ef-migration

**Comment by natemcmaster** [comment]
Also on OSX El Capitan. I believe this might be a bug in how Microsoft.NETCore.App is created.

**Comment by pranavkm** [comment]
cc @davidfowl \ @ericstj

**Comment by natemcmaster** [comment]
Maybe related to https://github.com/dotnet/cli/issues/2926#issuecomment-217745629?

**Comment by pranavkm** [comment]
Apparently the CLI doesn't regenerate the lock file for tools when the project.json changes. I'll file a bug for this, but this should unblock testing on Win7.
