### ISSUE TITLE
CLI Commands: --startup-project does not use locate paths correctly

### ISSUE THREAD

**Issue by pranavkm** [dotnet/efcore#5323]
`--startup-project` does not appear to use global.json when discovering projects. The current behavior makes it behave like `--relative-path-to-startup-project` which is not very user friendly.

**Comment by pranavkm** [comment]
On a related note, it should be nice to have it print a graceful error rather than dumping a stack trace from the CLI.

**Comment by pranavkm** [comment]
Follow up which is kinda worrying, if I do specify a relative path, I get further but the migration fails with
```
System.IO.FileLoadException: Could not load file or assembly 'WebApplication2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at Microsoft.EntityFrameworkCore.DesignTimeProjectLoadContext.Load(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at Microsoft.EntityFrameworkCore.Tools.Cli.OperationExecutor..ctor(CommonOptions options, String startupProjectPath, String environment)
   at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsAddCommand.Execute(CommonOptions commonOptions, String name, String outputDir, String context, String startupProject, String environment, Action`1 reporter)
   at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsAddCommand.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)
Could not load file or assembly 'WebApplication2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
```

Reproed on Win 10 and CentOS 7.1.

Running the application works fine.

**Comment by rowanmiller** [comment]
@natemcmaster has a PR out to remove `--startup-project` from the CLI commands - https://github.com/aspnet/EntityFramework/pull/5312. The class library scenario isn't really supported in CLI yet, so we are going to cripple it for RC2.

**Comment by natemcmaster** [comment]
This flag is gone now. https://github.com/aspnet/EntityFramework/commit/aef38bc8c58a12097b9a7d8f45f94f8e48cd8a43 We'll revisit this in https://github.com/aspnet/EntityFramework/issues/5311
