### ISSUE TITLE
Add-Migration fails with exception Could not load type 'Microsoft.EntityFrameworkCore.Scaffolding.Internal.DesignTimeEnvironment'

### ISSUE THREAD

**Issue by pbauwens** [dotnet/efcore#5324]
Got this error for the last few days, automagically got it to work yesterday, broken again today. 

System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Scaffolding.Internal.DesignTimeEnvironment' from assembly 'Microsoft.EntityFrameworkCore.Relational.Design, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.EntityFrameworkCore.Design.Internal.StartupInvoker.ConfigureHostServices(IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Design.Internal.StartupInvoker.ConfigureServices()
   at Microsoft.EntityFrameworkCore.Design.DbContextOperations..ctor(ILoggerProvider loggerProvider, Assembly assembly, Assembly startupAssembly, String environment, String startupProjectDir)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations..ctor(AssemblyLoader assemblyLoader, ILoggerProvider loggerProvider, Assembly assembly, Assembly startupAssembly, String environment, String projectDir, String startupProjectDir, String rootNamespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.<>c__DisplayClass4_0.<.ctor>b__5()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Could not load type 'Microsoft.EntityFrameworkCore.Scaffolding.Internal.DesignTimeEnvironment' from assembly 'Microsoft.EntityFrameworkCore.Relational.Design, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

**Comment by pbauwens** [comment]
{
  "dependencies": {
    "Microsoft.ApplicationInsights": "1.0.0",
    "Microsoft.ApplicationInsights.PersistenceChannel": "1.0.0",
    "Microsoft.ApplicationInsights.WindowsApps": "1.0.0",
    "Microsoft.EntityFrameworkCore.Commands": "1.0.0-rc3-20680",
    "Microsoft.EntityFrameworkCore.Relational": "1.0.0-rc3-20856",
    "Microsoft.EntityFrameworkCore.Sqlite": "1.0.0-rc3-20856",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.1.0"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}

**Comment by rowanmiller** [comment]
I'm guessing it is probably the mismatched versions of commands (`1.0.0-rc3-20680`) and the runtime (`1.0.0-rc3-20856`)

**Comment by rowanmiller** [comment]
Actually, just realized you have the old package name installed.... you want `Microsoft.EntityFrameworkCore.Tools

**Comment by pbauwens** [comment]
thx, did the trick
