### ISSUE TITLE
Cannot "build initialize" latest source from dev

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#5373]
Using VS 2015 Update 2 - what am I missing?

Errors in C:\Code\EntityFramework\test\Microsoft.EntityFrameworkCore.Tools.Funct
ionalTests\project.json
    Unable to resolve 'dotnet-test-xunit (>= 1.0.0)' for '.NETCoreApp,Version=v1
.0'.
    Unable to resolve 'dotnet-test-xunit (>= 1.0.0)' for '.NETFramework,Version=
v4.5.1'.

Errors in C:\Code\EntityFramework\test\Microsoft.EntityFrameworkCore.Tools.Tests
\project.json
    Unable to resolve 'dotnet-test-xunit (>= 1.0.0)' for '.NETCoreApp,Version=v1
.0'.
    Unable to resolve 'moq.netcore (>= 4.4.0)' for '.NETCoreApp,Version=v1.0'.
    Unable to resolve 'dotnet-test-xunit (>= 1.0.0)' for '.NETFramework,Version=
v4.5.1'.

NuGet Config files used:
    C:\Code\EntityFramework\NuGet.Config
    C:\Users\eejj\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    https://www.myget.org/F/aspnetcidev/api/v3/index.json
    https://api.nuget.org/v3/index.json
fail: Exit code 1 from dotnet
fail: Stack trace:
   at Viewfb0a80b608794cf9a8c8b91387b589af.<RenderViewLevel0>b__a3() in c:\Users
\eejj\AppData\Local\Temp\b9ba1e5fbbb54d8ea27c866773dd4516-1.cs:line 9315
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at Viewfb0a80b608794cf9a8c8b91387b589af.StartingTarget(String name) in c:\Use
rs\eejj\AppData\Local\Temp\b9ba1e5fbbb54d8ea27c866773dd4516-1.cs:line 3591
   at Viewfb0a80b608794cf9a8c8b91387b589af.<RenderViewLevel0>b__65() in c:\Users
\eejj\AppData\Local\Temp\b9ba1e5fbbb54d8ea27c866773dd4516-1.cs:line 4019
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)

**Comment by ErikEJ** [comment]
Oh, looks like the cidev feed is being cleaned just now - will wait until later this week!
