### ISSUE TITLE
Available Ms.EfCore does not work with available Ms.EfCore.Commands (Add-Migration fails)

### ISSUE THREAD

**Issue by AlexBilonog** [dotnet/efcore#5419]
In `aspnetvnext` feed I see only the following package versions:
- `Microsoft.EntityFrameworkCore`: 1.0.0-rc3-20912 (new)
- `Microsoft.EntityFrameworkCore.Commands`: 1.0.0-rc3-20637 (old)
- `Microsoft.EntityFrameworkCore.SqlServer`: 1.0.0-rc3-20912 (new)

I have installed them. Application works fine. But when I run the command: `PM> Add-Migration TestMigration`

I get an error with the stack trace:

`System.MissingMethodException: Method not found: 'System.Collections.Generic.IEnumerable1<Microsoft.EntityFrameworkCore.Metadata.IForeignKey> Microsoft.EntityFrameworkCore.KeyExtensions.FindReferencingForeignKeys(Microsoft.EntityFrameworkCore.Metadata.IKey)'.
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.<>c__DisplayClass11_0.<GenerateKeys>b__0(IKey key)
   at System.Linq.Enumerable.WhereEnumerableIterator1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateKeys(IEnumerable1 keys, IKey primaryKey, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateEntityType(String builderName, IEntityType entityType, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateEntityTypes(String builderName, IReadOnlyList1 entityTypes, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.Generate(String builderName, IModel model, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationsGenerator.GenerateMetadata(String migrationNamespace, Type contextType, String migrationName, String migrationId, IModel targetModel)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_01.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Method not found: 'System.Collections.Generic.IEnumerable1<Microsoft.EntityFrameworkCore.Metadata.IForeignKey> Microsoft.EntityFrameworkCore.KeyExtensions.FindReferencingForeignKeys(Microsoft.EntityFrameworkCore.Metadata.IKey)'.`

---

---

Earlier (to avoid this issue / as workaround) I used all the packages with old version 1.0.0-rc3-20637. And `Add-Migration` command was worked fine without any exception.

Could you provide a new fixed version of `Microsoft.EntityFrameworkCore.Commands`, because on a new computer (without locally cached Nuget packages) I cannot anymore restore the old version of `Microsoft.EntityFrameworkCore` (1.0.0-rc3-20637)

Thanks in advance.

**Comment by smitpatel** [comment]
`Microsoft.EntityFrameworkCore.Commands` is obsolete now. The new package name is `Microsoft.EntityFrameworkCore.Tools`
See difference from RC1 to RC2 at http://ef.readthedocs.io/en/latest/miscellaneous/rc1-rc2-upgrade.html
For using PMC commands for migration refer to http://ef.readthedocs.io/en/latest/cli/powershell.html
