### ISSUE TITLE
Cannot create a Migration for an RC1 to RC2 updated project

### ISSUE THREAD

**Issue by pterevinto** [dotnet/efcore#5512]
I am working on a project targetting "net461", and added EF packages. The project was originally created using ASP.Net 5 (RC1) and I was migrating to RC 2.

I removed all the Migrations I had and when trying to add a new one I keep getting the same error: **Could not load type 'System.ICloneable' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.**

Please find below the full outcome for adding a Migration:

C:\TFS\IL\BPSTaskTracker\src\BPSTaskTracker>dotnet -v ef migrations add InitialV2
Telemetry is: Enabled
Running C:\Program Files\dotnet\dotnet.exe exec --depsfile C:\Users\774368.nuget\packages.tools\Microsoft.EntityFrameworkCore.Tools\1.0.0-preview1-final\netcoreapp1.0\Microsoft.EntityFrameworkCore.Tools.deps.json --additionalprobingpath C:\Users\774368.nuget\packages C:\Users\774368.nuget\packages\Microsoft.EntityFrameworkCore.Tools\1.0.0-preview1-final\lib\netcoreapp1.0\dotnet-ef.dll migrations add InitialV2
Process ID: 16500
Using project 'C:\TFS\IL\BPSTaskTracker\src\BPSTaskTracker'.
System.TypeLoadException: Could not load type 'System.ICloneable' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
   at Microsoft.DotNet.ProjectModel.ProjectReader.ReadProject(Stream stream, String projectName, String projectPath, ProjectReaderSettings settings)
   at Microsoft.DotNet.ProjectModel.ProjectReader.GetProject(String projectPath, ProjectReaderSettings settings)
   at Microsoft.EntityFrameworkCore.Tools.DispatchCommand.<>c__DisplayClass2_0.<Create>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
**Could not load type 'System.ICloneable' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.**

**Comment by pterevinto** [comment]
Even just calling **dotnet -v ef** gives the same output.

**Comment by pterevinto** [comment]
This got fixed by correcting the imports, deleting everything from C:\Users\774368\.nuget\packages\.tools\Microsoft.EntityFrameworkCore.Tools and running a dotnet restore .
