### ISSUE TITLE
Error "No database providers are available" using EF with Asp.net 5

### ISSUE THREAD

**Issue by ovais** [dotnet/efcore#5627]
### Steps to reproduce

**this is how my project.json looks like**

``` JSON
  "dependencies": {
    "Newtonsoft.Json": "9.0.1-beta1",
    "Microsoft.AspNetCore.Mvc.Core": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc.Formatters.Json": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-final",
    "EntityFramework.Relational": "7.0.0-rc1-final",
    "EntityFramework.Core": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final"
  },
  "frameworks": {
    "net452": { }
  },
```

**Startup class** 

``` c#
 public void ConfigureServices(IServiceCollection services)
        { 
            services.AddMvcCore()
                    .AddJsonFormatters();

            var connectionString = "Data Source=LT-AOA3DK1;Initial Catalog=SpServices;Integrated Security=True";
            services.AddEntityFramework().AddDbContext<SpContext>(options => options.UseSqlServer(connectionString));

        }
```

**my dbcontext**

``` c#
  public class SpContext:DbContext
    {
        public SpContext(DbContextOptions options):base(options)
        {


        }
        public DbSet<SpAccount> SparkpostAccounts { get; set; }

    }
```

**I am injecting this context to my controller like this**

``` c#
        public ProductsController(SparkpostContext context)
        {
            _context = context;
        }
```

**and finally trying to use it like this.**

``` c#
        public IEnumerable<Product> Get()
        {
            var firstOrDefault = _context.SparkpostAccounts.FirstOrDefault();
..............
         } 
```
### The issue

I am getting an exception here 
{"No database providers are available. Ensure that database provider services are added inside the call to AddEntityFramework on your ServiceCollection."}

```
Exception message:
Stack trace:
   at Microsoft.Data.Entity.Internal.DatabaseProviderSelector.SelectServices(ServiceProviderSource providerSource)
   at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c.<AddQuery>b__1_0(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Data.Entity.Internal.InternalDbSet`1.<.ctor>b__2_0()
   at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at HelloMvcApi.ProductsController.Get()
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionAsync>d__6.MoveNext()
```

**Comment by divega** [comment]
You are missing a call to`AddSqlServer()` after `AddEntityFramework()`.

**Comment by ovais** [comment]
hmm I think you are right but now I am getting this exception

Additional information: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by ajcvickers** [comment]
@ovais You are mixing rc1 and rc2 packages. You need to update everything to rc2, keeping in mind that the EF package names have all changed. For example, you need Microsoft.EntityFrameworkCore.SqlServer.

**Comment by smitpatel** [comment]
A guide for migrating from RC1 to RC2. http://ef.readthedocs.io/en/latest/miscellaneous/rc1-rc2-upgrade.html

**Comment by divega** [comment]
Closing this issue since I believe we have answered the question.
