### ISSUE TITLE
Entity Framework Core TPH inheritance causes ArguementNullException

### ISSUE THREAD

**Issue by csmith93** [dotnet/efcore#5632]
### Steps to reproduce

I have the following classes (abridged for brevity):

```
public interface IEntityModel
{
    Guid Id { get; set; }
}

public abstract class User : IEntityModel {
    public Guid Id { get; set; }
    public int EmployeeId { get; set; }
    public string Username { get; set; }
    public bool IsManager { get; set; }
    public virtual Manager Manager { get; set; }

    // ...
}

public class Manager : User {
    public virtual ICollection<User> Employees { get; set; }

    // ...
}

public class Employee : User { 

    // ...
}

public class ApplicationDbContext : DbContext
{
     private static bool _created = false;
     public DbSet<User> Users { get; set; }
     public DbSet<Schedule> Schedules { get; set; }
     public DbSet<CellCarrierInfo> Carriers { get; set; }
     public DbSet<Alert> Alerts { get; set; }
     public DbSet<ValidationRule> Rules { get; set; }

     public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
     {
         if (!_created)
         {
             _created = true;
             Database.EnsureCreated();
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // Users

        modelBuilder.Entity<User>()
            .HasDiscriminator<bool>("IsManager")
            .HasValue<Manager>(true)
            .HasValue<Employee>(false);

        // Alternate keys
        modelBuilder.Entity<User>()
            .HasAlternateKey(u => u.Username);
        modelBuilder.Entity<User>()
            .HasAlternateKey(u => u.EmployeeId);

        // User will have a manager who will have employees
        modelBuilder.Entity<User>()
            .HasOne(u => u.Manager)
            .WithMany(m => m.Employees);

        // User will have schedules which will share an owner
        modelBuilder.Entity<User>()
            .HasMany(u => u.Schedules)
            .WithOne(s => s.Owner);

        // ...
    }
```
### The issue

`User user = Context.Users.FirstOrDefault(u => u.Username == aUserName);` fails

```
System.ArgumentNullException: Value cannot be null.
Parameter name: constructor
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor)
   at Microsoft.Data.Entity.Metadata.Internal.EntityMaterializerSource.CreateMaterializeExpression(IEntityType entityType, Expression valueBufferExpression, Int32[] indexMap)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.MaterializerFactory.CreateMaterializer(IEntityType entityType, SelectExpression selectExpression, Func`3 projectionAdder, IQuerySource querySource)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitEntityQueryable(Type elementType)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.EntityQueryableExpressionVisitor.VisitConstant(ConstantExpression constantExpression)
   at System.Linq.Expressions.ConstantExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CompileMainFromClauseExpression(MainFromClause mainFromClause, QueryModel queryModel)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.CompileMainFromClauseExpression(MainFromClause mainFromClause, QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitMainFromClause(MainFromClause fromClause, QueryModel queryModel)
   at Remotion.Linq.Clauses.MainFromClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.Internal.SqlServerQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass18_0`1.<CompileQuery>b__0()
   at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at Persistence.Repositories.UserRepository.FindByUsername(String aUserName)
   at Persistence.Repositories.UserRepository.FindOrCreate(String aUserName)
   at TimeCardReminder.Controllers.UserController.Index()
--- End of stack trace from previous location where exception was thrown ---
```
### Further technical details

EF Core version:

```
"EntityFramework.Core": "7.0.0-rc1-final",
"EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
"Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
```

Operating system: Win7
Visual Studio version: 2015

[Issue taken from here for visibility](http://stackoverflow.com/q/37601377/6415214).

**Comment by anpete** [comment]
@csmith93 Please try this on RC2, thanks.

**Comment by csmith93** [comment]
Will do

**Comment by csmith93** [comment]
I went ahead and completely recreated a project, and added the models one at a time to try and find the issue. It seemed to work, so I'm going to say this was probably my fault.

**Comment by csmith93** [comment]
@ajcvickers: I did find one thing interesting today with this. In:

    modelBuilder.Entity<User>()
        .HasDiscriminator<bool>("IsManager")
        .HasValue<Manager>(true)
        .HasValue<Employee>(false);

Because even though `User` is an abstract class it'll still try to make `User` an option using the `.HasValue("User")`, but that obviously won't work.

As a workaround I can use:

    modelBuilder.Entity<User>()
        .HasDiscriminator<bool?>("IsManager")
        .HasValue<User>(null)
        .HasValue<Manager>(true)
        .HasValue<Employee>(false);

And then the migration ends up correct (it'll still have the discriminator as not null).

**Comment by ajcvickers** [comment]
Marking for re-triage. I thought we had fixed this but I can't find the bug, so maybe we didn't. @smitpatel @AndriySvyryd might know.

**Comment by AndriySvyryd** [comment]
It's #5258, I fixed it right after RC2
