### ISSUE TITLE
Changing the type of a primary key doesn't result in a valid migration.

### ISSUE THREAD

**Issue by MicahZoltu** [dotnet/efcore#5661]
### Steps to reproduce
1. Create a new two-table code-first schema:
   
   ```
   public class Product
   {
       [Key]
       public Guid Id { get; set; }
       public List<Tag> Tags { get; set; }
   }
   
   public class Tag
   {
       [Key]
       public Guid Id { get; set; }
   }
   ```
2. Create and apply an initial migration to SQL Server (Azure DB).
3. Change the type of both `Id` columns to `Int32` in code.
4. Create a new migration.
5. Attempt to apply the migration.  **NOTICE** that the migration fails because it didn't correctly remove and re-create the indexes and foreign keys.
### The issue

Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
System.Data.SqlClient.SqlException: The index 'IX_Tags_ProductId' is dependent on column 'ProductId'.
The object 'FK_Tags_Products_ProductId' is dependent on column 'ProductId'.
ALTER TABLE ALTER COLUMN ProductId failed because one or more objects access this column.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandExtensions.ExecuteNonQuery(IEnumerable`1 commands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Execute(IEnumerable`1 relationalCommands)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Tools.Cli.DatabaseUpdateCommand.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)
ClientConnectionId:b1c447f8-9278-4912-aa5d-a0630579e398
Error Number:5074,State:1,Class:16
The index 'IX_Tags_ProductId' is dependent on column 'ProductId'.
The object 'FK_Tags_Products_ProductId' is dependent on column 'ProductId'.
ALTER TABLE ALTER COLUMN ProductId failed because one or more objects access this column.
```
### Further technical details

EF Core version: `1.0.0-rc2-final`
Operating system: `Windows 10`
Visual Studio version: `VS 2015`

Other details about my project setup:
`"Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview1-final",`

**Comment by Zoltu** [comment]
Note: there are other problems with this migration that I don't reasonably expect Entity Framework to solve for me (though it would be cool if it did).  However, the error I got was one that could occur with any kind of type change, not just GUID to INT.

**Comment by rowanmiller** [comment]
This is one of many scenarios that would be unblocked by the wider "table rebuilds" feature (https://github.com/aspnet/EntityFramework/issues/329). Closing this issue as we are tracking all of them via #329
