### ISSUE TITLE
ReflectionTypeLoadException after adding dependency

### ISSUE THREAD

**Issue by tmds** [dotnet/efcore#5696]
My asp.net app builds on top of rc2 bits. Because I needed some newer API for Http I added these dependencies to project.json:

```
"System.Collections.Concurrent": "4.0.12-rc3-*",
"System.Net.Http": "4.1.0-rc3-*",
```

and I changed NuGet.Config to:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="AspNetVNext" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
    <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration
```

On windows using dotnet 1.0.0-preview1-002702 this work fine.
On linux the application throws a System.Reflection.ReflectionTypeLoadException in the Startup where I apply migrations:

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.SharedTypeExtensions.GetConstructibleTypes(Assembly assembly)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsAssembly.<>c__DisplayClass3_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.PopulateMigrations(IEnumerable`1 appliedMigrationEntries, String targetMigration, IReadOnlyList`1& migrationsToApply, IReadOnlyList`1& migrationsToRevert)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<GetMigrationCommands>d__12.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
```

**Comment by tmds** [comment]
I downloaded the latest cli and moved to rc3-* and the problem no longer occurs.
