### ISSUE TITLE
Issues with store-generated enum keys

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#5779]
This is a very strange scenario: primary key defined using an enum in the CLR type, but then configured as store-generated. I tried this with Identity columns on SQL Server. It appears that Migrations does not create an Identity column in this case, which then results in an exception from the update pipeline (see below). If the column is an Identity column, then update pipeline appears to work. It's possible that other provider/generation strategies could have different behaviors.

``` C#
public class PropertyClassEntity
{
    public PropertyClassEntityTypeEnum Id { get; set; }
    public string Boo { get; set; }
}

public enum PropertyClassEntityTypeEnum
{
    A = 1,
    B,
    C
}

public class MyContext : DbContext
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<PropertyClassEntity>(b =>
            {
                b.HasKey(t => t.Id);
                b.Property(t => t.Id).ValueGeneratedOnAdd();
            });
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(SqlServerTestStore.CreateConnectionString("ByteMe"));
    }
}

[Fact]
public void Main()
{
    using (var context = new MyContext())
    {
        context.Database.EnsureDeleted();
        context.Database.EnsureCreated();

        var entity1 = new PropertyClassEntity();
        var entity2 = new PropertyClassEntity();
        context.Add(entity1);
        context.Add(entity2);
        context.SaveChanges();
    }
}
```

```
Test 'Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.SqlServerEndToEndTest.Main' failed: Microsoft.EntityFrameworkCore.DbUpdateException : An error occurred while updating the entries. See the inner exception for details.
---- System.Data.SqlClient.SqlException : Cannot insert the value NULL into column 'Id', table 'ByteMe.dbo.PropertyClassEntity'; column does not allow nulls. UPDATE fails.
The statement has been terminated.
    Update\ReaderModificationCommandBatch.cs(184,0): at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
    Update\Internal\BatchExecutor.cs(37,0): at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
    Storage\RelationalDatabase.cs(59,0): at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
    ChangeTracking\Internal\StateManager.cs(617,0): at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
    ChangeTracking\Internal\StateManager.cs(548,0): at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
    DbContext.cs(262,0): at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
    DbContext.cs(226,0): at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
    SqlServerEndToEndTest.cs(85,0): at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.SqlServerEndToEndTest.Main()
    ----- Inner Stack Trace -----
    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
    at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
    at System.Data.SqlClient.SqlDataReader.TrySetMetaData(_SqlMetaDataSet metaData, Boolean moreInfo)
    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
    at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
    at System.Data.SqlClient.SqlDataReader.get_MetaData()
    at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
    at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
    at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
    at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
    at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
    at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
    at System.Data.Common.DbCommand.ExecuteReader()
    Storage\Internal\RelationalCommand.cs(275,0): at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
    Storage\Internal\RelationalCommand.cs(140,0): at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
    Update\ReaderModificationCommandBatch.cs(171,0): at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
```

**Comment by rowanmiller** [comment]
Enum keys that are database generated don't seem to be a meaningful scenario
