### ISSUE TITLE
Query: Sum over subquery produces incorrect SQL

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#5784]
```
//Model
public class MyContext : DbContext
{
    public DbSet<Inventory> Inventory { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=_ModelApp;Trusted_Connection=True;");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {

    }
}

public class Purchase
{
    public Purchase()
    {
        Inventory = new List<Inventory>();
    }

    public int Id { get; set; }
    public int Count { get; set; }
    public IList<Inventory> Inventory { get; }
}

public class Inventory
{
    public int Id { get; set; }
    public int PurchaseId { get; set; }
    public int? SaledCount { get; set; }
    public Purchase Purchase { get; set; }
}
```

Repro code:

``` C#
using (var ctx = new MyContext())
{
    var query = (from p in ctx.Set<Purchase>()
                    let count = p.Count - (int)(p.Inventory.Select(i => i.SaledCount).Sum() ?? 0)
                    where (count > 0)
                    select count).Sum();
}
```

Exception: `System.Data.SqlClient.SqlException : Cannot perform an aggregate function on an expression containing an aggregate or a subquery.`
StackTrace:

```
Cannot perform an aggregate function on an expression containing an aggregate or a subquery.
    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
    at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
    at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
    at System.Data.SqlClient.SqlDataReader.get_MetaData()
    at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
    at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
    at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
    at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
    at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
    at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
    at System.Data.Common.DbCommand.ExecuteReader()
    Storage\Internal\RelationalCommand.cs(275,0): at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
    Storage\Internal\RelationalCommand.cs(140,0): at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
    Query\Internal\QueryingEnumerable.cs(81,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
    Query\QueryMethodProvider.cs(115,0): at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers)
    at lambda_method(Closure , QueryContext )
    Query\Internal\QueryCompiler.cs(200,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_1`1.<CompileQuery>b__1(QueryContext qc)
    Query\Internal\QueryCompiler.cs(98,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
    Query\Internal\EntityQueryProvider.cs(57,0): at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
    at System.Linq.Queryable.Sum(IQueryable`1 source)
    QuerySqlServerTest.cs(5457,0): at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.QuerySqlServerTest.Test()
```

Generated SQL:

```
SELECT SUM([p].[Count] - COALESCE((
    SELECT SUM([i0].[SaledCount])
    FROM [Inventory] AS [i0]
    WHERE [p].[Id] = [i0].[PurchaseId]
), 0))
FROM [Purchase] AS [p]
WHERE ([p].[Count] - COALESCE((
    SELECT SUM([i].[SaledCount])
    FROM [Inventory] AS [i]
    WHERE [p].[Id] = [i].[PurchaseId]
), 0)) > 0
```

**Comment by smitpatel** [comment]
Query generated with EF6
```
SELECT 
    [GroupBy3].[A1] AS [C1]
    FROM ( SELECT 
        SUM([Filter3].[A1]) AS [A1]
        FROM ( SELECT 
            [Project2].[Count] - (CASE WHEN ([Project2].[C1] IS NULL) THEN 0 ELSE [Project2].[C2] END) AS [A1]
            FROM ( SELECT 
                [Project1].[Count] AS [Count], 
                [Project1].[C1] AS [C1], 
                (SELECT 
                    SUM([Extent3].[SaledCount]) AS [A1]
                    FROM [dbo].[Inventories] AS [Extent3]
                    WHERE [Project1].[Id] = [Extent3].[PurchaseId]) AS [C2]
                FROM ( SELECT 
                    [Extent1].[Id] AS [Id], 
                    [Extent1].[Count] AS [Count], 
                    (SELECT 
                        SUM([Extent2].[SaledCount]) AS [A1]
                        FROM [dbo].[Inventories] AS [Extent2]
                        WHERE [Extent1].[Id] = [Extent2].[PurchaseId]) AS [C1]
                    FROM [dbo].[Purchases] AS [Extent1]
                )  AS [Project1]
            )  AS [Project2]
            WHERE ([Project2].[Count] - (CASE WHEN ([Project2].[C1] IS NULL) THEN 0 ELSE [Project2].[C2] END)) > 0
        )  AS [Filter3]
    )  AS [GroupBy3]
```

**Comment by smitpatel** [comment]
dupe of #3792
