### ISSUE TITLE
EF Core 1.0.0 cannot add initial migration

### ISSUE THREAD

**Issue by chris5287** [dotnet/efcore#5881]
### Steps to reproduce

Run `dotnet ef migrations add Initial` in the Package Manager Console, within the web application folder (DCL.Web.App).
### The issue

I have just update a solution to dotnet core 1.0/asp.net core 1.0/ef core 1.0
When I try to add a migration from the startup project, I get the following error:

`An error occurred while calling method 'ConfigureServices' on startup class 'DCL.Web.App.Startup'. Consider using IDbContextFactory to override the initialization of the DbContext at design-time. Error: Could not load type 'Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.`

`dotnet : No DbContext was found in assembly 'DCL.Web.App'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.`

The `CoreDbContext` exists in a class library (DCL.Core) which the web application (DCL.Web.App) references. It has a constructor that takes in a `DbContextOptions<>` and the Startup.cs in the web application calls `services.AddDbContext<CoreDbContext>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));` in the ConfigureServices method.
### Further technical details

EF Core version: 1.0.0
Visual Studio version: VS 2015 U3

**Comment by jsacapdev** [comment]
can you post your project.json please?

**Comment by chris5287** [comment]
Issue was actually being caused by https://github.com/aspnet/DependencyInjection/issues/412 and the use of `services.AddSwaggerGen()`, which hasn't been updated yet to dotnet core 1.0.0

**Comment by rowanmiller** [comment]
@chris5287 happy if we close this one now?

**Comment by NicolasParada** [comment]
I'm getting this error on a UWP application using Sqlite.
> Add-Migration MyMigration

> Could not load assembly 'MyProjectName'. Ensure it is referenced by the startup project 'MyProjectName'.

**Comment by JarredMiles** [comment]
I have this issue from a brand new asp.net core project.

**Comment by NicolasParada** [comment]
Mine it's a new app too. Just to play with the new .net core

**Comment by JarredMiles** [comment]
> System.TypeLoadException: Could not load type 'Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionExtensions' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.Extensions.DependencyInjection.NpgsqlEntityFrameworkServicesBuilderExtensions.AddEntityFrameworkNpgsql(IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_0.<GetOrAdd>b__1(Int64 k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityDbContext`1..ctor(DbContextOptions options)
   at Zeroprox.Web.Data.ApplicationDbContext..ctor(DbContextOptions`1 options) in C:\Users\chaot\Documents\Projects\Zeroprox\slnZeroproxWebsite\src\Zeroprox.Web\Data\ApplicationDbContext.cs:line 14
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.EntityFrameworkCore.Design.DbContextOperations.<>c__DisplayClass13_2.<FindContextTypes>b__6()
   at Microsoft.EntityFrameworkCore.Design.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Tools.Cli.DatabaseUpdateCommand.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)
Could not load type 'Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionExtensions' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

I am using npgsql but I don't think that should make a difference?

**Comment by NickolasAcosta** [comment]
https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/54

**Comment by chris5287** [comment]
@rowanmiller happy to close, not sure what you wanted to do as other comments here now

**Comment by rowanmiller** [comment]
@JarredMiles @NicolasParada Can you open new issues for the problems you are seeing. If you are able to share the project/solution that would be great (I'm guessing it has something to do with package versions).

**Comment by JarredMiles** [comment]
@rowanmiller  will do

**Comment by NicolasParada** [comment]
@rowanmiller Mine was solved. When I was writing a reproduction repo, it's just worked (it got the [#5471](https://github.com/aspnet/EntityFramework/issues/5471) issue btw).
