### ISSUE TITLE
The binary operator Equal is not defined for the types 'System.Nullable`1[System.Boolean]' and 'System.Boolean'

### ISSUE THREAD

**Issue by DmitrySikorsky** [dotnet/efcore#5899]
Code sample:
this.dbSet.Where(m => m.IsRelationSingleParent == true);

Here IsRelationSingleParent is bool? and may be NULL in the db.

I'm using Microsoft.EntityFrameworkCore.Sqlite 1.0.0. It worked fine in RC2 and before.

Now I have exception:

The binary operator Equal is not defined for the types 'System.Nullable`1[System.Boolean]' and 'System.Boolean'.

StackTrace:

   at System.Linq.Expressions.Expression.GetEqualityComparisonOperator(ExpressionType binaryType, String opName, Expression left, Expression right, Boolean liftToNull)
   at System.Linq.Expressions.Expression.Equal(Expression left, Expression right, Boolean liftToNull, MethodInfo method)
   at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.SearchConditionTranslatingVisitor.VisitExtension(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Expressions.AliasExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.SearchConditionTranslatingVisitor.VisitUnary(UnaryExpression expression)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.ApplyOptimizations(Expression expression, Boolean searchCondition)
   at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.VisitSelect(SelectExpression selectExpression)
   at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.GenerateSql(IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.ShaperCommandContext.GetRelationalCommand(IReadOnlyDictionary`2 parameters)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at Platformus.Content.Backend.ViewModels.Objects.IndexViewModelBuilder.GetGridColumns(Int32 classId) in C:\Users\Dmitry Sikorsky\Documents\Projects\Web\Platformus-Sample\src\Platformus.Content.Backend\Areas\Backend\ViewModels\Objects\Index\IndexViewModelBuilderBase.cs:line 59
   at Platformus.Content.Backend.ViewModels.Objects.IndexViewModelBuilder.Build(Nullable`1 classId, String orderBy, String direction, Int32 skip, Int32 take) in C:\Users\Dmitry Sikorsky\Documents\Projects\Web\Platformus-Sample\src\Platformus.Content.Backend\Areas\Backend\ViewModels\Objects\Index\IndexViewModelBuilderBase.cs:line 27
   at Platformus.Content.Backend.Controllers.ObjectsController.Index(Nullable`1 classId, String orderBy, String direction, Int32 skip, Int32 take) in C:\Users\Dmitry Sikorsky\Documents\Projects\Web\Platformus-Sample\src\Platformus.Content.Backend\Areas\Backend\Controllers\ObjectsController.cs:line 26
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()

**Comment by DmitrySikorsky** [comment]
As workaround I can invert m.IsRelationSingleParent == true to m.IsRelationSingleParent != null and it works (because value in my case can only be true or null).

**Comment by jeannunez** [comment]
I have the same issue where Where(m=>m.IsActive!=null && m.IsActive.Value==true).

**Comment by DmitrySikorsky** [comment]
@jeannunez it should be enough to test m.IsActive.Value == true, because true != null (but now it is not possible because of this bug(?)).

**Comment by rowanmiller** [comment]
Related to https://github.com/aspnet/EntityFramework/issues/5877

**Comment by rowanmiller** [comment]
Added some notes to https://github.com/aspnet/EntityFramework/issues/5877 to ensure we fix this at the same time. Closing this one now as we'll track with #5877.

**Comment by mo-esmp** [comment]
I've updated EF from ver 1.0.1 to ver 1.1.0 and after runnig below query I got same error.
```
var data = await _context.CustomerServices
                .Include(a => a.ServiceEquipment)
                .Include(a => a.ServiceAddresses)
                .ThenInclude(a => a.Address)
                .SingleOrDefaultAsync(a => a.Id == serviceId && !a.IsDeleted && !a.ServiceEquipment.IsDeleted);
```

> the binary operator Equal is not defined for the types 'System.Nullable`1[System.Boolean]' and 'System.Boolean'.
> 
>    at System.Linq.Expressions.Expression.GetEqualityComparisonOperator(ExpressionType binaryType, String opName, Expression left, Expression right, Boolean liftToNull)
>    at System.Linq.Expressions.Expression.Equal(Expression left, Expression right, Boolean liftToNull, MethodInfo method)
>    at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.SearchConditionTranslatingVisitor.VisitUnary(UnaryExpression expression)
>    at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.SearchConditionTranslatingVisitor.VisitBinary(BinaryExpression expression)
>    at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.SearchConditionTranslatingVisitor.VisitUnary(UnaryExpression expression)
>    at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.ApplyOptimizations(Expression expression, Boolean searchCondition, Boolean joinCondition)
>    at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.VisitSelect(SelectExpression selectExpression)
>    at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
>    at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.GenerateSql(IReadOnlyDictionary`2 parameterValues)
>    at Microsoft.EntityFrameworkCore.Query.Internal.ShaperCommandContext.GetRelationalCommand(IReadOnlyDictionary`2 parameters)
>    at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<BufferlessMoveNext>d__9.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__6`2.MoveNext()
