### ISSUE TITLE
ASP.NET Core 1.0 Reverse Engineering Database - Scaffold-DbContext error

### ISSUE THREAD

**Issue by saf-itpro** [dotnet/efcore#5906]
I clean installed `ASP.NET Core 1.0 (released on June 27)` along with `VS2015 Update 3` on both the machines win 8.1 and win 7. On Win 7, I get following error on [this step of ASP.NET Official Tutorial to Create a Db First web app](apphttps://docs.efproject.net/en/latest/platforms/aspnetcore/existing-db.html#reverse-engineer-your-model). I'm using the `northwind database on SQL Server 2012`. My Command is as follows:
`Scaffold-DbContext "Server=MyComuterName\SQL2012;Database=northwind;Trusted_Connection=True;" -OutputDir ".\Models"  Microsoft.EntityFrameworkCore`

**ERROR**:
`System.AggregateException: One or more errors occurred. (**Unable to find expected assembly attribute named DesignTimeProviderServicesAttribute in provider assembly Microsoft.EntityFrameworkCore**. This attribute is required to identify the class which acts as the design-time service provider factory.) ---> System.InvalidOperationException: Unable to find expected assembly attribute named DesignTimeProviderServicesAttribute in provider assembly Microsoft.EntityFrameworkCore. This attribute is required to identify the class which acts as the design-time service provider factory.    at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.GetProviderDesignTimeServices(String provider, Boolean throwOnError)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.Build(String provider)
   at Microsoft.EntityFrameworkCore.Design.DatabaseOperations.ReverseEngineerAsync(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.Design.Internal.OperationExecutor.ReverseEngineerAsync(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Tools.Cli.DbContextScaffoldCommand.<ExecuteAsync>d__1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
    at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)
 ---> (Inner Exception #0) System.InvalidOperationException: Unable to find expected assembly attribute named DesignTimeProviderServicesAttribute in provider assembly Microsoft.EntityFrameworkCore. This attribute is required to identify the class which acts  as the design-time service provider factory.
    at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.GetProviderDesignTimeServices(String provider, Boolean throwOnError) 
    at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.Build(String provider)
    at Microsoft.EntityFrameworkCore.Design.DatabaseOperations.ReverseEngineerAsync(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overw riteFiles, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.Design.Internal.OperationExecutor.ReverseEngineerAsync(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnota tions, Boolean overwriteFiles, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.Tools.Cli.DbContextScaffoldCommand.<ExecuteAsync>d__1.MoveNext()<---
 One or more errors occurred. (Unable to find expected assembly attribute named DesignTimeProviderServicesAttribute in provider assembly Microsoft.EntityFrameworkCore. This attribute is required to identify the class which acts as the design-time service pr ovider factory.) `

**peoject.json File has following section**:

`"tools": {
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": [
        "portable-net45+win8"
      ]
    }
  }`

I don't get the above error on my Win 8.1 machine with SQL Express 2014 and the same latest ASP.NET Core 1.0 and VS2015 Update 3 installed. Thanks..Saf

**Comment by natemcmaster** [comment]
@saf-itpro you need to specify a database provider to scaffold with. `Microsoft.EntityFrameworkCore` is not a database provider. It looks like you are using SQL Server, so specify that instead.
```
Scaffold-DbContext "Server=MyComuterName\SQL2012;Database=northwind;Trusted_Connection=True;" -OutputDir ".\Models" Microsoft.EntityFrameworkCore.SqlServer
```

**Comment by saf-itpro** [comment]
@natemcmaster Thank you for coming to rescue and pointing out my mistake. It's working now.
