### ISSUE TITLE
ArgumentException in query [no idea what is causing it]

### ISSUE THREAD

**Issue by gdoron** [dotnet/efcore#5935]
No idea if it's a known issue as I have no idea what the issue is.
It's a new code, so I can't say if it worked before on RC1/2.
### Steps to reproduce

Setup:

```
public class FollowerFollowed
    {
        public int Id { get; set; }
        public DateTime InsertDate { get; set; }
        public bool IsDeleted { get; set; }
        public ApplicationUser FollowerUser { get; set; }
        public string FollowerUserId { get; set; }

        public ApplicationUser FollowedUser { get; set; }
        public string FollowedUserId { get; set; }
    }
...
public DbSet<FollowerFollowed> Followers { get; set; }
...
builder.Entity<FollowerFollowed>(r =>
    {
        r.ToTable("Followers");
        r.HasOne(x => x.FollowedUser).WithMany(x => x.Followers).HasForeignKey(x => x.FollowedUserId);
        r.HasOne(x => x.FollowerUser).WithMany(x => x.Follows).HasForeignKey(x => x.FollowerUserId);
    });
```

Query: 

```
var followersEmails = await _context.Followers
                .Where(x => x.FollowedUserId == story.UserId && x.FollowerUser.EmailConfirmed)
                .Select(x =>
                    new
                        {
                            x.FollowerUser.FirstName,
                            x.FollowerUser.Email
                        }).ToListAsync();
```
### The issue

```
Exception message: System.ArgumentException: Expression of type 'System.Func`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[companyName.Entities.FollowerFollowed,System.Collections.Generic.IAsyncEnumerable`1[companyName.Entities.ApplicationUser]],companyName.Entities.ApplicationUser],System.Nullable`1[System.Boolean]]' cannot be used for parameter of type 'System.Func`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[companyName.Entities.FollowerFollowed,System.Collections.Generic.IAsyncEnumerable`1[companyName.Entities.ApplicationUser]],companyName.Entities.ApplicationUser],System.Boolean]' of method 'System.Collections.Generic.IAsyncEnumerable`1[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[companyName.Entities.FollowerFollowed,System.Collections.Generic.IAsyncEnumerable`1[companyName.Entities.ApplicationUser]],companyName.Entities.ApplicationUser]] _Where[TransparentIdentifier`2](System.Collections.Generic.IAsyncEnumerable`1[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[companyName.Entities.FollowerFollowed,System.Collections.Generic.IAsyncEnumerable`1[companyName.Entities.ApplicationUser]],companyName.Entities.ApplicationUser]], System.Func`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[companyName.Entities.FollowerFollowed,System.Collections.Generic.IAsyncEnumerable`1[companyName.Entities.ApplicationUser]],companyName.Entities.ApplicationUser],System.Boolean])'
Stack trace:
   at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0, Expression arg1)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitWhereClause(WhereClause whereClause, QueryModel queryModel, Int32 index)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitWhereClause(WhereClause whereClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.Clauses.WhereClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileAsyncQuery[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass20_0`1.<CompileAsyncQuery>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddAsyncQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQuery[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__129`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at companyName.Logic.StoryLogic.<ApproveStoryAsync>d__7.MoveNext() in C:\Git\companyName\src\companyName.Logic\StoryLogic.cs:line 75
```
### Further technical details

EF Core version: 1.0.0
Operating system: Windows 10
Visual Studio version: 2015.3

Other details about my project setup: net461

**Comment by gdoron** [comment]
FromSql works

	var followersEmails = await _context.Users.FromSql(@"SELECT U.*
	FROM Followers F 
	INNER JOIN Users U 
	    ON F.FollowerUserId = U.Id 
	WHERE F.FollowedUserId = {0}
	AND U.EmailConfirmed = 1", story.User.Id).ToListAsync();

**Comment by anpete** [comment]
@gdoron Does it work if you change it to sync?

**Comment by smitpatel** [comment]
What is the type of `EmailConfirmed`? If it is `bool?` then can you try comparing it with true in the where clause and see if it works.

**Comment by gdoron** [comment]
@anpete Changing from Async to sync had no affect.
@smitpatel it's IdentityUser, so the the property type is `bool`, not `Nullable<bool>`.

But since you mentioned it, I changed to `== true` and surprisingly it did solve it! :open_mouth: 
Checking the logs shows that it works since it caused EF to evaluate the query locally :smile:  (sounds like a bug (is it tracked?)) 


> The LINQ expression '(IIF(([x.FollowerUser] != null), Convert([x.FollowerUser].EmailConfirmed), null) == Convert(True))' could not be translated and will be evaluated locally.

> The LINQ expression 'from ApplicationUser x.FollowerUser in {[x.FollowerUser_group] => DefaultIfEmpty()}' could not be translated and will be evaluated locally.

> The LINQ expression 'DefaultIfEmpty()' could not be translated and will be evaluated locally.

In desc order (at least as it arrived to my Seq log), from a single run.

**Comment by smitpatel** [comment]
The exception message suggested that `Nullable<bool>` were being passed in place where `bool` was expected. If property is `bool` type then the relationship could be optional which converts property to `Nullable<bool>`. Though, I am uncertain of the reason why it was evaluated on client.

**Comment by rowanmiller** [comment]
Related to https://github.com/aspnet/EntityFramework/issues/5877, we'll track as part of that fix.
