### ISSUE TITLE
Many to Many - System.InvalidOperationException

### ISSUE THREAD

**Issue by wangkanai** [dotnet/efcore#5965]
```
public class Program
{
    public static void Main(string[] args)
    {
        var context = new ManyToManyContext();
        var course1 = new Course() { Name = "Management" };
        var course2 = new Course() { Name = "Strategic" };
        var sarin = new Person() { Name = "Sarin" };
        var rowan = new Person() { Name = "Rowan" };
        var bill = new Person() { Name = "Bill" };

        course1.Trainee.Add(sarin);
        course1.Trainee.Add(rowan);

        course2.Trainee.Add(rowan);
        course2.Trainee.Add(bill);

        context.Courses.Add(course1);
        context.Courses.Add(course2);

        context.Trainee.Add(sarin);
        context.Trainee.Add(rowan);
        context.Trainee.Add(bill);

        context.SaveChanges();
    }
}
public class ManyToManyContext : DbContext
{
    public DbSet<Course> Courses { get; set; }
    public DbSet<Person> Trainee { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Server=(localdb)\MSSQLLocalDB;Database=ManyToMany;Trusted_Connection=True;");
    }
}

public class Course
{
    public Course()
    {
        Trainee = new Collection<Person>();
    }
    public int Id { get; set; }
    public string Name { get; set; }
    public Collection<Person> Trainee { get; set; }
}

public class Person
{
    public Person()
    {
        Courses = new Collection<Course>();
    }
    public int Id { get; set; }
    public string Name { get; set; }
    public Collection<Course> Courses { get; set; }
}
```

PM> dotnet ef migrations add initial
Project EFCore.ManyToMany (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
dotnet : System.InvalidOperationException: Unable to determine the relationship represented by navigation property 'Course.Trainee' of type 'Collection<Person>'. Either manually configure the relationship, or ignore this property from the 
model.
At line:1 char:1
- dotnet ef migrations add initial
- ---
  - CategoryInfo          : NotSpecified: (System.InvalidO...from the model.:String) [], RemoteException
  - FullyQualifiedErrorId : NativeCommandError
  
  at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyMappingValidationConvention.Apply(InternalModelBuilder modelBuilder)
  at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelBuilt(InternalModelBuilder modelBuilder)
  at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
  at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
  
  at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
  at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
  
  at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
  
  at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
  
  at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
  
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
  
  at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
  
  at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
  
  at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
  
  at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
  
  at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsAddCommand.Execute(CommonOptions commonOptions, String name, String outputDir, String context, String environment, Action`1 reporter)
  
  at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsAddCommand.<>c__DisplayClass0_0.<Configure>b__0()
  at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
  
  at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)

Unable to determine the relationship represented by navigation property 'Course.Trainee' of type 'Collection<Person>'. Either manually configure the relationship, or ignore this property from the model.

**Comment by rowanmiller** [comment]
EF Core currently does not support many-to-many without a join entity. Here are docs on how to do many-to-many https://docs.efproject.net/en/latest/modeling/relationships.html#many-to-many. We have https://github.com/aspnet/EntityFramework/issues/1368 tracking the ability to support the patter you have in your model.

**Comment by Nihel1994** [comment]
how can i create a table with entity framework?

**Comment by ajcvickers** [comment]
@Nihel1994 See our documentation here: https://docs.microsoft.com/en-us/ef/core/
