### ISSUE TITLE
Query: boolColumn.Value property fails (only if in DB nav prop is null)

### ISSUE THREAD

**Issue by AlexBilonog** [dotnet/efcore#5980]
To reproduce the issue you need to have in DB ParentCostID == null:

```
    using (var db = new TheContext())
    {
        // the following code fails with an exception:
        db.Set<Cost>().Where(x => x.ParentCost.IsCreatedForGift.Value).ToList();

        // but the following works FINE:
        db.Set<Cost>().Where(x => x.ParentCost.IsCreatedForGift == true).ToList();

        // _Cannot check because of another reported issue, but I think this also should fail:_
        db.Set<Cost>().Where(x => x.IsCreatedForGift.Value).ToList();
    }

    public class Cost
    {
        public int ID { get; set; }
        public int? ParentCostID { get; set; }
        public bool? IsCreatedForGift { get; set; }

        public Cost ParentCost { get; set; }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Cost>(entity =>
        {
        });
    }
```

```
Exception message: An unhandled exception of type 'System.InvalidOperationException' occurred in Microsoft.EntityFrameworkCore.dll

Additional information: Nullable object must have a value.

Stack trace:
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at lambda_method(Closure , TransparentIdentifier`2 )
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EFGetStarted.ConsoleApp.Program.Main()
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
### Further technical details

EF Core version: 1.0.0
Operating system: Windows 8.1
Visual Studio version: 2015 Enterprise Update 3

**Comment by AlexBilonog** [comment]
Similar to  #5938
