### ISSUE TITLE
The instance of entity type 'UIELLUWP.DaaAccess.CategoryCodes' cannot be tracked because another instance of this type with the same key is already being tracked.

### ISSUE THREAD

**Issue by jeffman1** [dotnet/efcore#6073]
### Steps to reproduce

Create a very simple class as I have below with data annotations and then use the rest of the other code in main application. As you can see very simple but not sure if I am calling save changes incorrectly (All documentation official/non-official and code articles make it seem as if you can call it twice from a single context of the database. Is this true? Note: the code below except the main application code is in a dll file to separate it from the rest and meant to keep confusion down to a minimum while allowing fast access to table definitions. Some migration of data from existing db exists too.):

```
Imports System.ComponentModel.DataAnnotations
Imports System.ComponentModel.DataAnnotations.Schema
Imports Microsoft.Data.Entity
Imports Microsoft.Data.Sqlite
Namespace DataAccess
    Public Class SQLiteDb
        Inherits DbContext
        'the classes to return
        '  Public Property Categories As DbSet(Of CategoryList)
        Public Property CategoryCodes As DbSet(Of CategoryCodes)
        Public Property CategoryInformation As DbSet(Of CategoryReference)
        Private Shared _path As String = Path.Combine(Windows.Storage.ApplicationData.Current.LocalFolder.Path, "uiedata.db")
        Public Shared Sub Migrate()
            Dim a As New SQLiteDb
            a.Database.Migrate
        End Sub

        Public Sub New()
            Database.EnsureDeleted()
            Database.EnsureCreated()
            'Database.Migrate()
        End Sub
        ' Private Shared _path As String = Path.Combine(Windows.Storage.ApplicationData.Current.LocalFolder.Path, "uiedata.db")
        ' Public Shared _mycon As SQLite.Net.SQLiteConnection

        Protected Overrides Sub OnConfiguring(optionsBuilder As DbContextOptionsBuilder)
            If File.Exists(Path.Combine(Windows.Storage.ApplicationData.Current.LocalFolder.Path, "uiedata.db")) Then
                'File.Copy(Path.Combine(Windows.Storage.ApplicationData.Current.LocalFolder.Path, "uiedata.db"), Path.Combine(Windows.Storage.KnownFolders.MusicLibrary.Path, "uiedata.db"))
                optionsBuilder.UseSqlite("Filename=" + _path)

            Else
                'Dim db As New SQLiteDb
                'db.Database.EnsureCreated()
            End If
        End Sub
        Protected Overrides Sub OnModelCreating(modelBuilder As ModelBuilder)
            ' Make key for CategoryList temp table
            'modelBuilder.Entity(Of CategoryList)().ToTable("CategoryList")
            'modelBuilder.Entity(Of CategoryList)().HasKey(Function(cl) New With {
            '.CategoryID = cl.CategoryID,
            '.CodeID = cl.CodeID
            ' })

            'modelBuilder.Entity(Of CategoryList)().HasOne(Function(cl) cl.CategoryInfo).WithMany(Function(b) b.CategoryList).HasForeignKey(Function(cl) cl.CategoryID)
            'modelBuilder.Entity(Of CategoryList)().HasOne(Function(cl) cl.CategoryCodes).WithMany(Function(b) b.CategoryList).HasForeignKey(Function(cl) cl.CodeID)

            ' Make TimeStamp required

            ' modelBuilder.Entity(Of Ambience)().[Property](Function(b) b.AmbienceId).IsRequired()

        End Sub

 <Table("CategoryCodes")>
    Public Class CategoryCodes 'category shortnames/codes 

        <MaxLength(100)>
        <Required>
        Public Property CategoryCode As String
            Get
                Return _CategoryCode
            End Get
            Set(value As String)
                _CategoryCode = value
            End Set
        End Property
        Private _CategoryCode As String

        '<NotNull>
        ' <PrimaryKey>
        '<Unique(Name:="UQ__CategoryCodes__0000000000000081_CategoryCodes", Order:=0)>

        <Key>
        <Required>
        <DatabaseGenerated(DatabaseGeneratedOption.Identity)>
        Public Property CodeID As Integer
            Get
                Return CodeID
            End Get
            Set(value As Integer)
                _CodeID = value
            End Set
        End Property
        Private _CodeID As Integer
        'Public Overridable Property CategoryList As ICollection(Of CategoryList)
        '    Get
        '        Return m_CategoryList
        '    End Get
        '    Set(value As ICollection(Of CategoryList))
        '        value = m_CategoryList
        '    End Set
        'End Property
        'Dim m_CategoryList As ICollection(Of CategoryList)
    End Class
    <Table("CategoryReference")>
    Partial Public Class CategoryReference 'table design for category data

        <MaxLength(100)>
        Public Property CategoryName As String
            Get
                Return _CategoryName
            End Get
            Set(value As String)
                _CategoryName = value
            End Set
        End Property
        Private _CategoryName As String
        <MaxLength(100)>
        Public Property CategoryDescription As String
            Get
                Return _CategoryDescription
            End Get
            Set(value As String)
                _CategoryDescription = value
            End Set
        End Property
        Private _CategoryDescription As String

        '<Unique(Name:="UQ__CatagoryReference__000000000000005F_CatagoryReference", Order:=0)>
        <ForeignKey("CodeID")>
        <Required>
        Public Property CodeID As Integer
            Get
                Return _CodeID
            End Get
            Set(value As Integer)
                _CodeID = value
            End Set
        End Property
        Private _CodeID As Integer

        '<Unique(Name:="UQ__CatagoryReference__000000000000005A_CatagoryReference", Order:=0)>
        <Key>
        <Required>
        <DatabaseGenerated(DatabaseGeneratedOption.Identity)>
        Public Property CategoryID As Integer
            Get
                Return _CategoryID
            End Get
            Set(value As Integer)
                _CategoryID = value
            End Set
        End Property
        Private _CategoryID As Integer
        'Public Overridable Property CategoryList As ICollection(Of CategoryList)
        '    Get
        '        Return m_CategoryList
        '    End Get
        '    Set(value As ICollection(Of CategoryList))
        '        value = m_CategoryList
        '    End Set
        'End Property
        'Dim m_CategoryList As ICollection(Of CategoryList)
    End Class

    End Class

```

'add necessary end classes and namespaces below.

Heres the code that is causing the main issue from main application:

```
Private Sub CategoryDetails_Loading(sender As FrameworkElement, args As Object) Handles Me.Loading
        'CategoryDetails.DataContext = "{Binding Source={StaticResource CategoryCD}}"
        ' Dim testdatamodel As Data.TempCatData = New Data.TempCatData
        Using categories As New UIELLUWP.DataAccess.SQLiteDb
            'categories.ChangeTracker.DetectChanges()
            Dim c As New UIELLUWP.DataAccess.CategoryCodes
            c.CategoryCode = "GSM0"
            ' c.CodeID = 1
            categories.CategoryCodes.Add(c)
            If categories.SaveChanges(True) <> -1 Then
                Dim a As MessageDialog = New MessageDialog("Success on category code!")
            End If

            Dim b As New UIELLUWP.DataAccess.CategoryReference
            b.CategoryDescription = "who is this?"
            b.CategoryName = "Cool Beans"
            b.CodeID = 1
            'b.CategoryID = 1
            categories.CategoryInformation.Add(b)
            categories.SaveChanges(True)

            CategoryCode.AddRange(categories.CategoryCodes.ToList)
            CategoryInfo.AddRange(categories.CategoryInformation.ToList)
        End Using
        'first category main save
        'Dim a As New UIELLUWP.DataAccess.CategoryList
        'a.ID = 0
        'a.CategoryID = 0
        'a.CodeID = 0
        'a.CategoryInfo = New DataAccess.CategoryReference With {
        '     .CodeID = 0,
        '     .CategoryID = 0,
        '     .CategoryName = "Cool Beans",
        '    .CategoryDescription = "who is this?"
        '      }
        'a.CategoryCodes = c
        'categories.Categories.Add(a)
        'categories.SaveChanges()


        ' CategoryLists.AddRange(categories.Categories.ToList)
        CategoryName.ItemsSource = CategoryInfo.ToList
        'figure out categorycode problem later when I finish the rest of the design diagram
    End Sub

```
### The issue

My Issue is that I get the error: 
Additional information: The instance of entity type 'UIELLUWP.DataAccess.CategoryCodes' cannot be tracked because another instance of this type with the same key is already being tracked. when I use the EntityFramework.SQLite library from NuGet in visual studio (Microsoft Version):

   at Microsoft.Data.Entity.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges)
   at Microsoft.Data.Entity.ChangeTracking.Internal.StateManager.StartTracking(IEntityType entityType, IKeyValue keyValue, Object entity, ValueBuffer valueBuffer)
   at Microsoft.Data.Entity.Query.Internal.EntityTrackingInfo.StartTracking(IStateManager stateManager, Object entity, ValueBuffer valueBuffer)
   at Microsoft.Data.Entity.Query.Internal.QueryBuffer.StartTracking(Object entity, EntityTrackingInfo entityTrackingInfo)
   at Microsoft.Data.Entity.Query.Internal.LinqOperatorProvider.<>c__DisplayClass15_0`2.<_TrackEntities>b__0(TOut result)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.Data.Entity.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at UIE.CategoryDetails.CategoryDetails_Loading(FrameworkElement sender, Object args)
### Further technical details

EF Core version: EF7
Operating system:  Windows 10 build 10586
Visual Studio version: Visual Studio 2015

**Comment by jeffman1** [comment]
Additional Information: I cannot find out where the additional key is being tracked. Despite limiting different code and commenting out a database.migrate line I put into the app.xaml.vb file. I temporarily fixed it once by recreating the database again. Am I using the code wrong?

**Comment by ajcvickers** [comment]
@jeffman1 I have attempted to reproduce the error you are seeing, but I haven't been able to do so. I had to make several changes to the code to make it compile. For example, this line:
```VB
CategoryCode.AddRange(categories.CategoryCodes.ToList)
```
is very suspicious, but as it is I don't know what it does and it doesn't compile for me as is.

Given this, here is some more specific information about filing the bug in a way that we will be able to properly investigate it:

**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean 😄... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bug, implementing new features, etc. we ask that folks give us a self contained way to reproduce an issue.

For a guide on submitting good bug reports, read_ [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).

**Comment by jeffman1** [comment]
It seems that most of the problem was improper class setup and data annotations (CategoryReference and the other class code in DataAccess is an exact class copy using EricJ's SQLCE to SQLite DB conversion tool). I still think something is wrong with how the keys are setup because of my joins. You can close this thread though and start a new one.  Making an advanced master/details tutorial would help since that was what I tried to do.  Using linked tables can be a pain sometimes in entity framework. It appears changing my data loading code to this helped stop the error (i.e. specially adding AsNoTracking):
 ```
 Private Sub CategoryDetails_Loading(sender As FrameworkElement, args As Object) Handles Me.Loading
        'CategoryDetails.DataContext = "{Binding Source={StaticResource CategoryCD}}"
        ' Dim testdatamodel As Data.TempCatData = New Data.TempCatData
        Using categories As New UIELLUWP.DataAccess.SQLiteDb
            categories.Database.EnsureDeleted()
            categories.Database.EnsureCreated()
            Dim c As DataAccess.CategoryCodes = New DataAccess.CategoryCodes With {
              .CategoryCode = "CBM1"
              }
            categories.CategoryCodes.Add(c)
            categories.SaveChanges(True)

            Dim b As New DataAccess.CategoryReference
            b.CategoryDescription = "who is this?"
            b.CategoryName = "Cool Beans"
            b.CodeID = c.CodeID
            categories.CategoryInformation.Add(b)
            categories.SaveChanges(True)

            Dim c2 As New UIELLUWP.DataAccess.CategoryCodes
            c2.CategoryCode = "DBM1"
            'c2.CodeID = 2
            categories.CategoryCodes.Add(c2)
            categories.SaveChanges()

            'second category info
            Dim b2 As New UIELLUWP.DataAccess.CategoryReference
            b2.CategoryDescription = "Disc media such as cds, dvd's, and blurays"
            b2.CategoryName = "Disc Based Media"
            b2.CodeID = c2.CodeID
            'b2.CategoryID = 2
            categories.CategoryInformation.Add(b2)
            categories.SaveChanges()

            Dim b4 As New UIELLUWP.DataAccess.CategoryReference
            b4.CategoryDescription = "Disc media such as cds, dvd's, and blurays"
            b4.CategoryName = "Disc Based Media"
            b4.CodeID = c.CodeID
            'b2.CategoryID = 2
            categories.CategoryInformation.Add(b4)
            categories.SaveChanges()

            Dim b3 As New UIELLUWP.DataAccess.CategoryReference
            b3.CategoryDescription = "Other Disc media such as HD DVD's, Mini discs, Video Game Discs, etc."
            b3.CategoryName = "Disc Based Media 2"
            b3.CodeID = c2.CodeID
            'b2.CategoryID = 2
            categories.CategoryInformation.Add(b3)
            categories.SaveChanges()
            'put into the display list
            CategoryCode2 = categories.CategoryCodes.AsNoTracking.ToList
            CategoryInfo = categories.CategoryInformation.AsNoTracking.ToList

            CategoryCodeN = From e In categories.CategoryCodes Join p In categories.CategoryInformation On e.CodeID Equals p.CodeID Where e.CodeID = p.CodeID Select e.CategoryCode Distinct.ToList

        End Using

        CategoryName.ItemsSource = From ci In CategoryInfo Join cd2 In CategoryCode2 On ci.CodeID Equals cd2.CodeID Where ci.CodeID = cd2.CodeID Select ci.CategoryName, ci.CategoryDescription Distinct.ToList
    End Sub
```
