### ISSUE TITLE
add-migration not working with iot core background task project

### ISSUE THREAD

**Issue by Qowy** [dotnet/efcore#6098]
Hi,
I have an iot core background task project, which seems to be of the type "windows runtime component".
Because of the limitations of such a project type (for example inheritance) i added a second c# class library project which contains my model and entity framework core and it's database context.

Because of the documented problems of running add-migration with class libraries as a startup project I set the iot core project as my startup project, the database class library is referenced, the Microsoft.EntityFrameworkCore.Tools is installed in the startup project and the app.config fix is applied.
In this case add-migration fails with the wonderfully helpful error message (full exception below):

Could not load assembly 'iot Project'. Ensure it is referenced by the startup project 'iot Project'.

```
Microsoft.EntityFrameworkCore.Design.OperationException: Could not load assembly '<iot Project>'. Ensure it is referenced by the startup project '<iot Project>'. ---> System.IO.FileNotFoundException: Could not load file or assembly '<iot Project>' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.EntityFrameworkCore.Design.AssemblyLoader.Load(String assemblyName)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.<>c__DisplayClass5_0.<.ctor>b__2()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.<>c__DisplayClass5_0.<.ctor>b__2()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.<>c__DisplayClass5_0.<.ctor>b__5()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

The workaround I had to resort to, was to add an empty dummy UWP application project to my solution that references the class library , install the tools, select it as a startup project and then run add-migrations (which finally worked)
### Further technical details

EF Core version: 
   "Microsoft.EntityFrameworkCore.Sqlite": "1.0.0",
   "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"
Operating system:  Windows 10 10586.494
Visual Studio version: VS2015 Update 3

**Comment by natemcmaster** [comment]
In the past, we have not supported using Windows Runtime Components (WinMD). @rowanmiller do we want to revisit this?

Cref https://github.com/aspnet/EntityFramework/issues/4684#issuecomment-193903540
Backlog item: https://github.com/aspnet/EntityFramework/issues/1058

**Comment by rowanmiller** [comment]
@natemcmaster good point, clearing the milestone to rediscuss in triage

**Comment by rowanmiller** [comment]
Agreed that this can stay on backlog. The real solution for the scenario described in the initial report of this issue is to support class libraries, which we are already working on.
