### ISSUE TITLE
How to notify developer if he tries to use a private field instead of property

### ISSUE THREAD

**Issue by xperiandri** [dotnet/efcore#6150]
### Steps to reproduce

I have such an excerpt of code on my API

``` C#
            IQueryable<Post> postsQuery;

            if (leftLong < rightLong)
                postsQuery = from post in context.Posts
                             let location = post.Location
                             where location.Latitude >= leftLong && location.Latitude <= rightLong
                                && location.Longitude <= topLat && location.Longitude >= bottomLat
                             select post;
            else
                postsQuery = from post in context.Posts
                             let location = post.Location
                             where (location.Latitude >= leftLong && location.Latitude <= 180.0
                                 || location.Latitude >= -180.0 && location.Latitude <= rightLong)
                                && location.Longitude <= topLat && location.Longitude >= bottomLat
                             select post;

            return postsQuery.Include(t => t.User)
                             .OrderBy(t => t.Time)
                             .ToList();

```
### The issue

It throws such exception

```
Web.Controllers.PostController
Error getting posts within area with coordinates [0 < lat < 0] [54.629888233242 > long > -15.865331136143]

System.InvalidOperationException: Nullable object must have a value.
  at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
  at plaMobi.Data.Entities.Post.get_Time() in Data\Entities\Post.cs:line 35
  at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
  at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
  at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
  at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
  at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
  at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
  at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
  at plaMobi.Controllers.PostController.Get(Double leftLong, Double lat1, Double rightLong, Double lat2) in Web\Controllers\PostController.cs:line 75
```

Data in a Posts table

| Id | Latitude | Longitude | Text | TypeOfMessage | UserId | Time |
| --- | --- | --- | --- | --- | --- | --- |
| 44a283a3-8fdd-46c6-b570-08d3b170a199 | 43,81234123 | -119,8374747 | Test text from user1 | 0 | 8205cdd9-9907-481b-4fb1-08d3b170a188 | 21.07.2016 17:09:30 |
| 26f80c22-43b2-4455-b571-08d3b170a199 | 53,81234123 | -129,8374747 | Test text from user2 | 0 | 8205cdd9-9907-481b-4fb1-08d3b170a188 | 21.07.2016 17:09:30 |
| e2ff680b-8d64-4881-b572-08d3b170a199 | 13,81234123 | -119,8374747 | Test text from user3 | 0 | 8205cdd9-9907-481b-4fb1-08d3b170a188 | 21.07.2016 17:09:30 |
| 96e1c249-801a-4741-b573-08d3b170a199 | 63,81234123 | -219,8374747 | Test text from user4 | 0 | 8205cdd9-9907-481b-4fb1-08d3b170a188 | 21.07.2016 17:09:30 |
| 1205f9a9-47bc-437f-b574-08d3b170a199 | 83,81234123 | -319,8374747 | Test text from user5 | 0 | 8205cdd9-9907-481b-4fb1-08d3b170a188 | 21.07.2016 17:09:30 |
| 2d3db9e4-e833-4cae-b575-08d3b170a199 | 13,81234123 | -219,8374747 | Test text from user6 | 0 | 8205cdd9-9907-481b-4fb1-08d3b170a188 | 21.07.2016 17:09:30 |
| ff8ee1cb-1e61-431d-b576-08d3b170a199 | 0 | 0 | string | 0 | 54572cd5-3788-44b6-4fb2-08d3b170a188 | 21.07.2016 17:12:48 |
### Further technical details

EF Core version: 1.0.0
Operating system: Windows 10 Pro Insider Preview 14393
Visual Studio version: 2015 Enterprise Update 3

**Comment by xperiandri** [comment]
It would be nice to be able to tell EF that a property is not shadow so that it throw an exception if the property is absent.

``` C#
    [Table("Posts")]
    public class Post
    {
        private static readonly DateTime epoch = new DateTime(1970, 1, 1);

        private DateTime? time { get; set; } // was a field

        [NotMapped]
        public ulong Time
        {
            get { return Convert.ToUInt64((time.Value - epoch).TotalSeconds); }
            set { time = epoch + TimeSpan.FromSeconds(value); }
        }
    }
```

I forgot that fields could not be used if they have different value type than property covering it

**Comment by rowanmiller** [comment]
Discussed and decided this isn't something we are going to add the core product. 

You could write an extension to achieve this pretty easily though...

```c#
public static class Extensions
{
    public static PropertyBuilder<TProperty> PrivateProperty<TProperty>(this EntityTypeBuilder builder, string propertyName)
    {
        var propertyBuilder =  builder.Property<TProperty>(propertyName);

        if(propertyBuilder.Metadata.IsShadowProperty)
        {
            throw new ArgumentException($"Property {propertyName} was not found on {builder.Metadata.Name}");
        }

        return propertyBuilder;
    }
}
```

**Comment by xperiandri** [comment]
Cool, thanks!

**Comment by xperiandri** [comment]
@rowanmiller I try to build type hierarchy where this trick is applied but now property is not being set.
Could you advise what is wrong?

``` C#
public class WebApplication : TenantApplication
{
    private string allowedTenantsStore;
    protected override string AllowedTenantsStore
    {
        get => allowedTenants != null
            ? JArray.FromObject(allowedTenants).ToString(Formatting.None)
            : allowedTenantsStore;
        set
        {
            allowedTenants = null;
            allowedTenantsStore = value;
        }
    }

    private ISet<string> allowedTenants;

    public ISet<string> AllowedTenants
    {
        get => allowedTenants ?? (allowedTenants = !string.IsNullOrWhiteSpace(allowedTenantsStore)
                   ? JArray.Parse(allowedTenantsStore)
                       .Values<string>()
                       .ToHashSet(StringComparer.OrdinalIgnoreCase)
                   : new HashSet<string>(StringComparer.OrdinalIgnoreCase));
        set => allowedTenants = value;
    }
}

public class ExternalApplication : TenantApplication
{
    public string AllowedTenant { get => AllowedTenantsStore; set => AllowedTenantsStore = value; }
    public string ClientResourceId { get; set; }
    public string NotificationEmail { get; set; }
}

public class TenantApplication : OpenIddictApplication<Guid, TenantAuthorization, TenantToken>
{
    internal static readonly string AllowedTenantsStoreName = nameof(AllowedTenantsStore);

    protected virtual string AllowedTenantsStore { get; set; }

    public AppOwnership Ownership { get; set; }
}

public enum AppOwnership : byte
{
    Internal = 0,
    External = 1,
    Undefined = 2
}
```

``` C#
builder.Entity<TenantApplication>(entity =>
{
    entity.Ignore(nameof(WebApplication.AllowedTenants));
    entity.Ignore(nameof(ExternalApplication.AllowedTenant));
    entity.PrivateProperty<string>(TenantApplication.AllowedTenantsStoreName)
          .HasColumnName("AllowedTenants");
    entity.HasDiscriminator<AppOwnership>(nameof(TenantApplication.Ownership))
          .HasValue<TenantApplication>(AppOwnership.Undefined)
          .HasValue<WebApplication>(AppOwnership.Internal)
          .HasValue<ExternalApplication>(AppOwnership.External);

    entity.HasQueryFilter(a => EF.Functions.Like(EF.Property<string>(a, TenantApplication.AllowedTenantsStoreName), $"%{this.tenant}%"));
    //entity.HasQueryFilter(a => EF.Property<string>(a, TenantApplication.AllowedTenantsStoreName).Contains(tenant));
});
```

**Comment by ajcvickers** [comment]
@xperiandri If you feel there is a bug here, then please file a new issue including a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.
