### ISSUE TITLE
Combination of Include and Where clause for nullable field (left join) causes NullReferenceException

### ISSUE THREAD

**Issue by thtp** [dotnet/efcore#6178]
### Code to reproduce:

Models:

```
    public class Base
    {
        public Base()
        {
            Id = Guid.NewGuid();
        }

        public Guid Id { get; set; }
    }

    public class A : Base
    {
        private A()
        {
        }

        public string Name { get; set; }
        public B B { get; set; }
        public Guid BId { get; set; }
    }

    public class B : Base
    {
        private B()
        {
        }

        public string Name { get; set; }
        public C C { get; set; }
        public Guid? CId { get; set; }
        public ICollection<A> As { get; set; }
    }

    public class C : Base
    {
        private C()
        {
        }

        public string Name { get; set; }
        public ICollection<B> Bs { get; set; }
    }
```

Context:

```
    public class TestContext : DbContext
    {
        public DbSet<A> As { get; private set; }
        public DbSet<B> Bs { get; private set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<A>(o =>
            {
                o.HasKey(x => x.Id);
                o.HasIndex(x => x.Name);
            });

            modelBuilder.Entity<A>()
                .HasOne(x => x.B)
                .WithMany(x => x.As)
                .HasForeignKey(x => x.BId)
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired(true);

            modelBuilder.Entity<B>(o =>
            {
                o.HasKey(x => x.Id);
                o.HasIndex(x => x.Name);
            });

            modelBuilder.Entity<B>()
                .HasOne(x => x.C)
                .WithMany(x => x.Bs)
                .HasForeignKey(x => x.CId)
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired(false);

            modelBuilder.Entity<B>()
                .HasMany(x => x.As)
                .WithOne(x => x.B)
                .HasForeignKey(x => x.BId)
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired(true);

            modelBuilder.Entity<C>()
                .HasMany(x => x.Bs)
                .WithOne(x => x.C)
                .HasForeignKey(x => x.CId)
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired(false);

            base.OnModelCreating(modelBuilder);
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=.;Database=Ef_Wtf;Trusted_Connection=True;MultipleActiveResultSets=true");
        }
    }
```

Migration with test data:

```
    public partial class TestData : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            var command = new StringBuilder()
                .AppendLine("INSERT[dbo].[C]([Id], [Name]) VALUES(N'99868059-da66-426a-b26f-288f8646dab6', N'C0')")
                .AppendLine("INSERT[dbo].[Bs] ([Id], [CId], [Name]) VALUES(N'8cd01a0c-f1e8-40a7-a096-e32b789baba7', N'99868059-da66-426a-b26f-288f8646dab6', N'B0')")
                .AppendLine("INSERT[dbo].[As] ([Id], [BId], [Name]) VALUES(N'417085b2-435c-41d9-9c14-0148e59facdc', N'8cd01a0c-f1e8-40a7-a096-e32b789baba7', N'A0')")
                .AppendLine("INSERT[dbo].[As] ([Id], [BId], [Name]) VALUES(N'c79e5645-0726-4278-b900-cee361545c42', N'8cd01a0c-f1e8-40a7-a096-e32b789baba7', N'A1')")
                .ToString();
            migrationBuilder.Sql(command);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
```

Program:

```
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var context = new TestContext())
            {
                var query = context.As
                    .Where(a => a.B.C.Name == string.Empty)
                    .Include(a => a.B)
                    .ToList();

                foreach (var a in query)
                {
                    Console.WriteLine(a.Name);
                    Console.WriteLine(a.B.Name);
                }

                Console.ReadKey();
            }
        }
    }
```
### The issue

The code above throws NullReferenceException
Only combination of "Where" and "Include" does throw.

Here is generated SQL for this query:

```
SELECT [a].[Id], [a].[BId], [a].[Name], [a.B].[Id], [a.B].[CId], [a.B].[Name], [a.B.C].[Id], [a.B.C].[Name], [b].[Id], [b].[CId], [b].[Name]
FROM [As] AS [a]
INNER JOIN [Bs] AS [a.B] ON [a].[BId] = [a.B].[Id]
LEFT JOIN [C] AS [a.B.C] ON [a.B].[CId] = [a.B.C].[Id]
INNER JOIN [Bs] AS [b] ON [a].[BId] = [b].[Id]
ORDER BY [a.B].[CId]
```

As you can see, generated SQL does not include where condition. SQL selects everything, and Where clause is applied in memory.
Furthermore, generated SQL does one excess "INNER JOIN" with B and unnecessary "ORDER BY"
That's all wrong :(

Here is Exception message and stack trace:

```
Exception message: Object reference not set to an instance of an object.
Source: Anonymously Hosted DynamicMethods Assembly
Stack trace:   
   at lambda_method(Closure , InternalEntityEntry )
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.SimpleNonNullableDependentKeyValueFactory`1.TryCreateFromCurrentValues(InternalEntityEntry entry, TKey& key)
   at Microsoft.EntityFrameworkCore.Query.Internal.WeakReferenceIdentityMap`1.CreateIncludeKeyComparer(INavigation navigation, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.IncludeCore(Object entity, INavigation navigation)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.Include(QueryContext queryContext, Object entity, IReadOnlyList`1 navigationPath, IReadOnlyList`1 relatedEntitiesLoaders, Int32 currentNavigationIndex, Boolean queryStateManager)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.Include(QueryContext queryContext, Object entity, IReadOnlyList`1 navigationPath, IReadOnlyList`1 relatedEntitiesLoaders, Boolean queryStateManager)
   at Microsoft.EntityFrameworkCore.Query.Internal.GroupJoinInclude.Include(Object entity)
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_GroupJoin>d__26`4.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__22`3.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EfWtf.Program.Main(String[] args) in D:\Repositories\Whatnots\EfWtf2\src\EfWtf\Program.cs:line 14
```
### Further technical details

EF Core version: 1.0.0
Operating system: Wondows 10 version: 1511 build: 10586.494
Visual Studio version: VS 2015
SQL Server: Microsoft SQL Server 2016

**Comment by maumar** [comment]
Main issue (exception) working in current dev, fixed by https://github.com/aspnet/EntityFramework/commit/5f48163ff06ba27311cc3e0a0a259f3b09748733

Filter applied in memory is tracked here: https://github.com/aspnet/EntityFramework/issues/4588

Also, opened a new issue to track redundant joins between include and nav props: https://github.com/aspnet/EntityFramework/issues/6206
