### ISSUE TITLE
RC1 to RTM Add / Update Behaviour Change

### ISSUE THREAD

**Issue by stevejgordon** [dotnet/efcore#6217]
### Steps to reproduce

The following query ran in RC1 but fails in RTM

```
var itinerary = await GetItinerary(message) ?? new Itinerary();

itinerary.Name = message.Itinerary.Name;
itinerary.Date = message.Itinerary.Date;
itinerary.EventId = message.Itinerary.EventId;

_context.Update(itinerary);
await _context.SaveChangesAsync().ConfigureAwait(false);
```

Full code at https://github.com/HTBox/allReady/blob/master/AllReadyApp/Web-App/AllReady/Areas/Admin/Features/Itineraries/EditItineraryCommandHandlerAsync.cs
### The issue

We used code as above to add / update records in EF Core RC1. Since RTM, when adding a new Itinerary this fails with the error as included below. We can solve this by specifically adding or updating based on the entity state using this extension currently...

```
        public static void AddOrUpdate(this DbContext ctx, object entity)
        {
            var entry = ctx.Entry(entity);

            switch (entry.State)
            {
                case EntityState.Detached:
                    ctx.Add(entity);
                    break;
                case EntityState.Modified:
                    ctx.Update(entity);
                    break;
                default:
                    throw new ArgumentOutOfRangeException();
            }
        }
```

I'm curious what changed with the Update method that presumably previously worked out whether to Add or Update inside EF?

Is there a preferred pattern when working inside a method that either adds a new record or updates an existing one? We wanted to avoid two handlers when the code is essentially the same. I have also considered simply checking if the ID is set or not and using that to determine whether to call Add or whether to call Update.

```
Exception message:
Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.

Stack trace:
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.<ConsumeResultSetWithoutPropagationAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.<ConsumeAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at AllReady.Areas.Admin.Features.Itineraries.EditItineraryCommandHandlerAsync.<Handle>d__2.MoveNext() in C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\Areas\Admin\Features\Itineraries\EditItineraryCommandHandlerAsync.cs:line 29
```
### Further technical details

EF Core version: RTM 1.0.0
Operating system: Windows 7 SP1
Visual Studio version: VS 2015

Other details about my project setup: Full project at https://github.com/HTBox/allReady

**Comment by ajcvickers** [comment]
@stevejgordon The thing that changed was that we decided that if you call Update with an object, then we should do what that method says--that is mark the object as Modified. Previously we would look at the key value and if we knew it couldn't be an existing entity, then we would mark it as Added instead.

In your case it seems it would be easier to mark the new entity as added immediately. For example:
```C#
var itinerary = await GetItinerary(message) 
    ?? _context.Add(new Itinerary()).Entity;

itinerary.Name = message.Itinerary.Name;
itinerary.Date = message.Itinerary.Date;
itinerary.EventId = message.Itinerary.EventId;

await _context.SaveChangesAsync().ConfigureAwait(false);
```
You would then not need either the call to Update or the AddOrUpdate method.

**Comment by stevejgordon** [comment]
@ajcvickers Thanks very much for the feedback. That makes sense. I'd scoured the upgrade posts and seemed to be missing details of that change.

Your suggestion for our code is a great idea, thanks for highlighting it.
