### ISSUE TITLE
Flaky Test: AsyncQueryTestBase.Mixed_sync_async_query

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#6248]
```
Stacktraces: 
(new) Test collection for Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.AsyncQuerySqlServerTest (1): Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.AsyncQuerySqlServerTest.Mixed_sync_async_query 
System.InvalidOperationException : There is already an open DataReader associated with this Command which must be closed first.
   at System.Data.SqlClient.SqlInternalConnectionTds.ValidateConnectionForExecute(SqlCommand command)
   at System.Data.SqlClient.SqlCommand.ValidateCommand(Boolean async, String method)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection) in C:\BuildAgent\work\16b2695b987e66d0\src\Microsoft.EntityFrameworkCore.Relational\Storage\Internal\RelationalCommand.cs:line 275
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection) in C:\BuildAgent\work\16b2695b987e66d0\src\Microsoft.EntityFrameworkCore.Relational\Storage\Internal\RelationalCommand.cs:line 140
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext() in C:\BuildAgent\work\16b2695b987e66d0\src\Microsoft.EntityFrameworkCore.Relational\Query\Internal\QueryingEnumerable.cs:line 81
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext() in C:\BuildAgent\work\16b2695b987e66d0\src\Microsoft.EntityFrameworkCore.Relational\Query\QueryMethodProvider.cs:line 43
   at System.Linq.Lookup`2.CreateForJoin(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.<GroupJoinIterator>d__71`4.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__163`3.MoveNext()
   at System.Linq.Enumerable.<GroupJoinIterator>d__71`4.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext() in C:\BuildAgent\work\16b2695b987e66d0\src\Microsoft.EntityFrameworkCore\Query\Internal\LinqOperatorProvider.cs:line 170
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext() in C:\BuildAgent\work\16b2695b987e66d0\src\Microsoft.EntityFrameworkCore\Query\Internal\LinqOperatorProvider.cs:line 145
   at System.Linq.Enumerable.<SelectManyIterator>d__157`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
```

**Comment by maumar** [comment]
This failed on my box after applying the latest fix to it, reopening for further investigation.

**Comment by smitpatel** [comment]
Error is different now. It happens during parameter injection.

```
Test 'Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.AsyncQuerySqlServerTest.Mixed_sync_async_query' failed: System.ArgumentException : An item with the same key has already been added.
	at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
	at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
	at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
	Query\QueryContext.cs(100,0): at Microsoft.EntityFrameworkCore.Query.QueryContext.AddParameter(String name, Object value)
	Query\AsyncQueryMethodProvider.cs(867,0): at Microsoft.EntityFrameworkCore.Query.AsyncQueryMethodProvider.ParameterInjector`1.InjectParametersEnumerator..ctor(ParameterInjector`1 parameterInjector)
	Query\AsyncQueryMethodProvider.cs(853,0): at Microsoft.EntityFrameworkCore.Query.AsyncQueryMethodProvider.ParameterInjector`1.System.Collections.Generic.IAsyncEnumerable<TElement>.GetEnumerator()
	at System.Linq.AsyncEnumerable.<ToEnumerable_>d__133`1.MoveNext()
	at System.Linq.Enumerable.<GroupJoinIterator>d__40`4.MoveNext()
	at System.Linq.Enumerable.<SelectManyIterator>d__22`3.MoveNext()
	at System.Linq.Enumerable.<GroupJoinIterator>d__40`4.MoveNext()
	at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	Query\Internal\LinqOperatorProvider.cs(170,0): at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
	Query\Internal\LinqOperatorProvider.cs(145,0): at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
	at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
	at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
	AsyncQueryTestBase.cs(82,0): at Microsoft.EntityFrameworkCore.Specification.Tests.AsyncQueryTestBase`1.<Mixed_sync_async_query>d__1.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

0 passed, 1 failed, 0 skipped, took 2.50 seconds (xUnit.net 2.2.0 build 3402).
```

**Comment by BrennanConroy** [comment]
AsyncQuerySqlServerTest.Except_nested has started failing on the CI with the 
```
System.InvalidOperationException : There is already an open DataReader associated with this Command which must be closed first.
```
exception

**Comment by smitpatel** [comment]
Closing this in favour of #7160
