### ISSUE TITLE
Partially store-generated keys cannot be inserted on SQLite

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#6292]
Key has one property store-generated, one property not.

``` C#
public class Category
{
    public int Id1 { get; set; }
    public int Id2 { get; set; }
}

public class CompKeyContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlite("Data Source=CompKeyContext");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(b =>
        {
            b.HasKey(e => new { e.Id1, e.Id2 });
            b.Property(e => e.Id1).ValueGeneratedOnAdd();
        });
    }
}

public class Program
{
    public static void Main()
    {
        using (var db = new CompKeyContext())
        {
            db.Database.EnsureDeleted();
            db.Database.EnsureCreated();

            db.Add(new Category { Id2 = 77 });

            db.SaveChanges();
        }
    }
}
```

Exception:

```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 19: 'NOT NULL constraint failed: Category.Id1'.
   at Microsoft.Data.Sqlite.Interop.MarshalEx.ThrowExceptionForRC(Int32 rc, Sqlite3Handle db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at ListenerTest.Program.Main() in C:\Stuff\ListenerTest\ListenerTest\Program.cs:line 48
```

**Comment by ajcvickers** [comment]
Note: uncomment code in referenced PR when fixing this issue.

**Comment by bricelam** [comment]
`ROWID` only gets aliased if there is a single, `INTEGER` column used as the primary key. You would need to implement something on the store for `ValueGeneratedOnAdd` to work in this scenario.

**Comment by bricelam** [comment]
Try with `b.Property(e => e.Id1).HasDefaultValueSql("[rowid]");`

**Comment by ajcvickers** [comment]
@bricelam That gives:
```
Microsoft.Data.Sqlite.SqliteException: SQLite Error 1: 'default value of column [Id1] is not constant'
```
BTW, I think it is fine if this isn't supported out-of-the-box with SQLite. It's not a very useful scenario anyway.

**Comment by ajcvickers** [comment]
Closing as a limitation of how SQLite works.
