### ISSUE TITLE
Unable to use Local DB in Ubuntu

### ISSUE THREAD

**Issue by VenkateshSrini** [dotnet/efcore#6336]
### Steps to reproduce

1) Create a Sample ASPNET core application with LocalDB in windows 10 .
2) Ensure it works
3) Make the code to work with kestrel
4) Now run the code in Unix Ubuntu OS (14.0) the below exception is thrown

```### The issue
The current problem I have is, I use a local SQL server file(.mdf) file for persistence in my app. I have also added the database to the as App_Data. My connection string looks as below{ 
"ConnectionStrings": { 
"DefaultConnection": "Data Source=.\MSSQLLocalDB;AttachDbFilename=%CONTENTROOTPATH%\App_Data\ASPNETCoreToDo.mdf;" 
} 
} 
This works perfectly fine in local. This does not work when pushed to Ubuntu (14.0)
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
`System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.AggregateException: One or more errors occurred. (No such device or address) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address
         at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
         at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
         at System.Net.Dns.<>c.<GetHostAddressesAsync>b__14_1(IAsyncResult asyncResult)
         at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Data.SqlClient.SNI.SNITCPHandle.<ConnectAsync>d__22.MoveNext()
         --- End of inner exception stack trace ---
         at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
         at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
         at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
         at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)

`

### Further technical details

EF Core version: 1.0.0
Operating system: windows 10 anniversary ypdate
Visual Studio version: Visual studio 2015
Other details about my project setup:
```

**Comment by ErikEJ** [comment]
Localdb is a Windows only product, and only supports connections from the local machine

**Comment by natemcmaster** [comment]
As @ErikEJ said, LocalDB is Windows only. On Linux, you can use EF Core with a remote SQL Server (running on Windows), the preview version of https://sqlserverforlinux.com, or SQL Azure. Alternatively, you can use the Postgres and SQLite [providers](https://docs.efproject.net/en/latest/providers/index.html).
