### ISSUE TITLE
Error running unit tests: SerializationException occurred in System.Data.dll but was not handled in user code

### ISSUE THREAD

**Issue by felipepessoto** [dotnet/efcore#6414]
I'm receiving this error during the tests:

An exception of type 'System.Runtime.Serialization.SerializationException' occurred in System.Data.dll but was not handled in user code

Additional information: Type is not resolved for member 'Microsoft.EntityFrameworkCore.Specification.Tests.TestSqlLoggerFactory+SqlLoggerData,Microsoft.EntityFrameworkCore.Relational.Specification.Tests, Version=0.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

Stack Trace:

   at System.AppDomain.GetHostEvidence(Type type)
   at System.Security.Policy.Evidence.GetHostEvidenceNoLock(Type type)
   at System.Security.Policy.Evidence.RawEvidenceEnumerator.MoveNext()
   at System.Security.Policy.Evidence.EvidenceEnumerator.MoveNext()
   at System.Configuration.ClientConfigPaths.GetEvidenceInfo(AppDomain appDomain, String exePath, String& typeName)
   at System.Configuration.ClientConfigPaths.GetTypeAndHashSuffix(AppDomain appDomain, String exePath)
   at System.Configuration.ClientConfigPaths..ctor(String exePath, Boolean includeUserConfig)
   at System.Configuration.ClientConfigPaths.GetPaths(String exePath, Boolean includeUserConfig)
   at System.Configuration.ClientConfigurationHost.RequireCompleteInit(IInternalConfigRecord record)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.PrivilegedConfigurationManager.GetSection(String sectionName)
   at System.Data.LocalDBAPI.CreateLocalDBInstance(String instance)
   at System.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean withFailover, Boolean isFirstTransparentAttempt, SqlAuthenticationMethod authType)
   at System.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover, Boolean isFirstTransparentAttempt)
   at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open() in D:\Projetos\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Storage\RelationalConnection.cs:line 280
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.Exists(Boolean retryOnNotExists) in D:\Projetos\EntityFramework\src\Microsoft.EntityFrameworkCore.SqlServer\Storage\Internal\SqlServerDatabaseCreator.cs:line 117
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.Exists() in D:\Projetos\EntityFramework\src\Microsoft.EntityFrameworkCore.SqlServer\Storage\Internal\SqlServerDatabaseCreator.cs:line 107
   at Microsoft.EntityFrameworkCore.Tests.RelationalDatabaseCleaner.Clean(DatabaseFacade facade) in D:\Projetos\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational.Specification.Tests\RelationalDatabaseCleaner.cs:line 40
   at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.SqlServerDatabaseFacadeExtensions.EnsureClean(DatabaseFacade databaseFacade) in D:\Projetos\EntityFramework\test\Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests\SqlServerDatabaseFacadeExtensions.cs:line 11
   at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.GearsOfWarQuerySqlServerFixture.<CreateTestStore>b__4_0() in D:\Projetos\EntityFramework\test\Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests\GearsOfWarQuerySqlServerFixture.cs:line 40
   at Microsoft.EntityFrameworkCore.Specification.Tests.TestStore.CreateShared(String name, Action initializeDatabase) in D:\Projetos\EntityFramework\src\Microsoft.EntityFrameworkCore.Specification.Tests\TestStore.cs:line 29
   at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.Utilities.SqlServerTestStore.CreateShared(Action initializeDatabase) in D:\Projetos\EntityFramework\test\Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests\Utilities\SqlServerTestStore.cs:line 69
   at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.Utilities.SqlServerTestStore.GetOrCreateShared(String name, Action initializeDatabase) in D:\Projetos\EntityFramework\test\Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests\Utilities\SqlServerTestStore.cs:line 28
   at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.GearsOfWarQuerySqlServerFixture.CreateTestStore() in D:\Projetos\EntityFramework\test\Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests\GearsOfWarQuerySqlServerFixture.cs:line 32
   at Microsoft.EntityFrameworkCore.Specification.Tests.GearsOfWarQueryTestBase`2..ctor(TFixture fixture) in D:\Projetos\EntityFramework\src\Microsoft.EntityFrameworkCore.Specification.Tests\GearsOfWarQueryTestBase.cs:line 1997
   at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.GearsOfWarQuerySqlServerTest..ctor(GearsOfWarQuerySqlServerFixture fixture, ITestOutputHelper testOutputHelper) in D:\Projetos\EntityFramework\test\Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests\GearsOfWarQuerySqlServerTest.cs:line 2035

Thanks

**Comment by divega** [comment]
@fujiy we had similar issues before but we fixed them by making some types serializable. You may be running into this if you have stale references, so the suggestion is to try to start from a clean package cache.
