### ISSUE TITLE
Add-Migration: System.BadImageFormatException -> System.Collections.Concurrent 4.0.0.0

### ISSUE THREAD

**Issue by HClausing** [dotnet/efcore#6425]
Good Afternoon for all.
### Introduction

I have installed EF Core and EF SqlServer, version 1.0.0 from nuget package to work on Full .NET 4.6 application. But when I see the problem on Tracking entities failing on 'LoadAsync' I decided to move for nightly builds (alpha1-21973), but now I can't run the 'Add-migration' commands.

It's trying to load 'System.Collections.Concurrent' on 4.0.0.0 version, but I see on Dependencies that's requires the 4.0.12 version (already installed).

I don't know what I'm doing wrong.
### The issue

Could not load file or assembly 'System.Collections.Concurrent, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.

```
Exception message:
Stack trace:
System.BadImageFormatException: Could not load file or assembly 'System.Collections.Concurrent, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
File name: 'System.Collections.Concurrent, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.BadImageFormatException: Cannot load a reference assembly for execution.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceTable..ctor(IEnumerable`1 descriptors)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, Boolean validateScopes)
   at Microsoft.EntityFrameworkCore.Design.Internal.StartupInvoker.ConfigureServices()
   at Microsoft.EntityFrameworkCore.Design.DbContextOperations..ctor(ILoggerProvider loggerProvider, Assembly assembly, Assembly startupAssembly, String environment, String contentRootPath)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations..ctor(ILoggerProvider loggerProvider, Assembly assembly, AssemblyLoader startupAssemblyLoader, Assembly startupAssembly, String environment, String projectDir, String contentRootPath, String rootNamespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.<>c__DisplayClass5_0.<.ctor>b__5()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)


Could not load file or assembly 'System.Collections.Concurrent, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
PM> 
```
### Further technical details

EF Core version: 1.1.0-alpha1-21973
Operating system: MS Windows 10 Pro 1607
Visual Studio version: VS 2015.3
### Other details about my project setup:

WPF Class Library and .NET Framework 4.6.
DbContext configured with Fluent API and working fine on existing database. 

Thanks.

**Comment by bricelam** [comment]
Could you share your `packages.config` and `App.config` files as well?

**Comment by HClausing** [comment]
Of course.

I'm trying to attach on zip format, but I receive this error: _"Unfortunately, we don’t support that file type. Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP. "_ So I'm sharing a link from one drive:

https://1drv.ms/u/s!AAsFZ2XXayWeziY

Thanks.

**Comment by bricelam** [comment]
`System.Collections.Concurrent` shouldn't be listed in `App.config` (possibly a NuGet bug) try deleting that 
`<dependentAssembly>` element to see if it fixes the problem.

If that still doesn't work, delete `App.config`, run `Add-BindingRedirect`, and try again.

**Comment by HClausing** [comment]
Thanks for the quick answer. 

I have tried the following procedures:

1) Changed:

**Comment by divega** [comment]
**EF Triage:** Closing since we believe we have answered the question. Please create a new issue if you run into new issue or reactivate/respond to this thread if something about the answer isn't clear.
