### ISSUE TITLE
EF ignore TableAttribute name

### ISSUE THREAD

**Issue by SilverioMiranda** [dotnet/efcore#6550]
### Steps to reproduce

Create a table with underscore name like : 

Table code : 

```
using System.ComponentModel.DataAnnotations.Schema;

namespace Miranda.Core.Model
{
    [Table("produto_classe")]
    public partial class ProdutoClasse
    {
        public long Id { get; set; }
        public string Nome { get; set; }
    }
}
```
### The issue

A table name with underscore "_" is ignored by ef and throws exception :

If i rename that table to "produtoclasse" this code works.

```
MySql.Data.MySqlClient.MySqlException: Table 'sgm_servidor.produtoclasse' doesn't exist
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_Include>d__30`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_Include>d__30`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_Include>d__30`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_Include>d__30`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_Include>d__30`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NonFactors.Mvc.Grid.GridRows`1.GetEnumerator()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
```
### Further technical details

EF Core version: 1.0.0
Operating system:  Windows 10 X64
Visual Studio version: 2015 Update 3

**Comment by SilverioMiranda** [comment]
With Fluent API the app runs as expected

```
modelBuilder.Entity<ProdutoClasse>()
                .ToTable("produto_classe");
```

**Comment by ajcvickers** [comment]
@SilverioMiranda I was not able to reproduce this using SQL Server. It looks like you are using a MySql provider--you might want to file an issue with them.

**Comment by gmartinezsan** [comment]
hi @SilverioMiranda,
If this is related to the MySQL official driver, you can post any MySQL EF Core related issues or questions at our forums. I will check this issue in our end.
