### ISSUE TITLE
Can't remove first migration of second context.

### ISSUE THREAD

**Issue by fe-c** [dotnet/efcore#6599]
### Steps to reproduce
- Add new context, like **SchoolContext** from https://docs.asp.net/en/latest/data/ef-mvc/intro.html on the same ConnectionString.
- Create and apply migration: 
  Add-Migration CreateSchoolContext -Context SchoolContext
  Update-Database -Context SchoolContext
### The issue

Can't remove migration CreateSchoolContext.
**Remove-Migration** says  "More than one DbContext was found. Specify which one to use."

**Remove-Migration -Context SchoolContext** says "The migration '20160924194316_CreateSchoolContext' has already been applied to the database. Unapply it and try again."

**Update-Database CreateIdentitySchema -Context SchoolContext**  says "The migration 'CreateIdentitySchema' was not found."

**Update-Database CreateIdentitySchema -Context ApplicationDbContext** says "Done" but not actually revert CreateSchoolContext migration.

**Update-Database -TargetMigration 0 -Context SchoolContext**  and **Update-Database -ConfigurationTypeName PlaygroundTestEF.Migrations2.Configuration -TargetMigration 0 -Context SchoolContext** says "A parameter cannot be found that matches parameter name"
### Further technical details

  "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },

Operating system: Windows10x64
Visual Studio version: VS 2015 Update 3

**Comment by bricelam** [comment]
Possibly manifestations of #6126 & #6228. Could you try again using the version 1.0.1 runtime packages?

**Comment by bricelam** [comment]
> A parameter cannot be found that matches parameter name

Not sure about this one... @natemcmaster, anything obvious? (before I investigate)

**Comment by fe-c** [comment]
There was last runtime packages, visual studio & tools updates:
Project packages was updated via Nuget - Select All - Update:
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
"Microsoft.AspNetCore.Mvc": "1.0.1",
"Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
"Microsoft.EntityFrameworkCore.SqlServer": "1.0.1", etc.

**Comment by natemcmaster** [comment]
Nothing for sure, but I'd guess it's a combination of problems in the project setup. Multiple context types can be tricky. @fe-c can you share your project that repros the issue?

**Comment by fe-c** [comment]
But multiple context types are supported in *-Migration commands via -Context param. And this described in docs (from link in issue description). And by the way - all works fine, except removing first migration of second context.

**Comment by fe-c** [comment]
Just now reproduce in new simple project: https://www.dropbox.com/s/ligq7o4otp7kurq/DoubleContextApp.zip?dl=0

**Comment by bricelam** [comment]
![image](https://cloud.githubusercontent.com/assets/1226749/18971166/e6957318-8648-11e6-85d9-e6f80be1890e.png)

**Comment by fe-c** [comment]
It seems i was using wrong parameter name. But with this command at no i get another error:
```
 System.Data.SqlClient.SqlException: The ALTER TABLE statement conflicted with the FOREIGN KEY constraint "FK_Table1_Table2_Id". The conflict occurred in database "aspnet-TestDb", table "dbo.Qu estionnarieDefinitions", column 'Id'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
    at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) 
    at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName) 
    at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() 
    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection) 
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
    at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration) 
    at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType) 
    at Microsoft.EntityFrameworkCore.Tools.Cli.DatabaseUpdateCommand.<>c__DisplayClass0_0.<Configure>b__0()
    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
    at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)
```
Do I need to clear all data from tables to perform database update, that removes some tables?

**Comment by fe-c** [comment]
In migration that removes constraint, Down  method creates this constraint. I had clean up data, conflicting with this constraint and all migrations can be removed now.
Thanks!
