### ISSUE TITLE
[Test] CompiledQueryCacheKey generates InvalidCastException intermittently 

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#6633]
After #6619 test `SqliteEndToEndTest.Can_save_changes_and_query` became flaky.
Stacktrace

```
System.InvalidCastException : Specified cast is not valid.
   at Microsoft.EntityFrameworkCore.Query.CompiledQueryCacheKeyGenerator.CompiledQueryCacheKey.Equals(Object obj) in C:\BuildAgent\work\33bdfc1cae7b2a38\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\CompiledQueryCacheKeyGenerator.cs:line 114
   at System.Collections.Generic.ObjectEqualityComparer`1.Equals(T x, T y)
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryAddInternal(TKey key, TValue value, Boolean updateIfExists, Boolean acquireLock, TValue& resultingValue)
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryAdd(TKey key, TValue value)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) in C:\BuildAgent\work\33bdfc1cae7b2a38\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\Internal\CompiledQueryCache.cs:line 51
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query) in C:\BuildAgent\work\33bdfc1cae7b2a38\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\Internal\QueryCompiler.cs:line 98
   at Microsoft.EntityFrameworkCore.CrossStore.FunctionalTests.EndToEndTest`2.Can_save_changes_and_query() in C:\BuildAgent\work\33bdfc1cae7b2a38\EntityFramework\test\Microsoft.EntityFrameworkCore.CrossStore.FunctionalTests\EndToEndTest.cs:line 48
```

**Comment by smitpatel** [comment]
This is happening in other tests too. Any query can fails on this.
