### ISSUE TITLE
Entity framework creates bug with wrong decimal size in SQL Generation

### ISSUE THREAD

**Issue by Huck** [dotnet/efcore#6654]
### Steps to reproduce

I have an array of POCO classes just like the below:

`-      results Count = 4   System.Collections.Generic.List<MyEntity>
- ```
    [0] {MyEntity}  MyEntity
  Amount  1.02    decimal?
  Balance 31355.19395 decimal?
  Date    {5/31/2016 12:00:00 AM} System.DateTime?
  Description "dfssbhdfbsdfbsdfbsdf"  string
  Interest_Payments   0   decimal?
  PlatformCashId  -9223372036854774803    long
  Principal_Payments  1.02    decimal?
  Transaction_ID  "1251312738"    string
  Type    "TTTT__GGGGGGG_EEEEE"   string
  ```
- ```
    [1] {MyEntity}  MyEntity
  Amount  6135.5  decimal?
  Balance 31354.17395 decimal?
  Date    {5/31/2016 12:00:00 AM} System.DateTime?
  Description "ertwergwrgwergwergwer" string
  Interest_Payments   108.7743467 decimal?
  PlatformCashId  -9223372036854774802    long
  Principal_Payments  6026.725653 decimal?
  Transaction_ID  "1251312738"    string
  Type    "TTTT__GGGGGGG_EEEEE"   string
  ```
- ```
    [2] {MyEntity}  MyEntity
  Amount  197.49  decimal?
  Balance 25218.67395 decimal?
  Date    {5/31/2016 12:00:00 AM} System.DateTime?
  Description "jftrjrmjrnmrthnrhnrgh" string
  Interest_Payments   105.2094653 decimal?
  PlatformCashId  -9223372036854774801    long
  Principal_Payments  92.2805347  decimal?
  Transaction_ID  "1251312738"    string
  Type    "TTTT__GGGGGGG_EEEEE"   string
  ```
- ```
    [3] {MyEntity}  MyEntity
  Amount  1.01    decimal?
  Balance 25021.18395 decimal?
  Date    {5/31/2016 12:00:00 AM} System.DateTime?
  Description "hwhwrnbrtbgwrbwrbwr"   string
  Interest_Payments   0   decimal?
  PlatformCashId  -9223372036854774800    long
  Principal_Payments  1.01    decimal?
  Transaction_ID  "1251312738"    string
  Type    "TTTT__GGGGGGG_EEEEE"   string`
  ```
### The issue

when calling SaveChanges(), there is an exception. (see below). after investigating, I found out that the generated SQL for the decimal sizes contains a bug. here is the generated SQL (I removed the last 3 entities for simplicity):

`exec sp_executesql N'SET NOCOUNT ON;
DECLARE @toInsert3 TABLE ([Amount] decimal(5 ,2), [Balance] decimal(5 ,2), [Date] datetime2, [Description] nvarchar(500), [Interest_Payments] decimal(5 ,2), [Principal_Payments] decimal(5 ,2), [Transaction_ID] nvarchar(50), [Type] nvarchar(500), [_Position] [int]);
INSERT INTO @toInsert3
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, 0);

DECLARE @inserted3 TABLE ([MyEntityId] bigint, [Amount] decimal(5 ,2), **_[Balance] decimal(5 ,2),_** [Date] datetime2, [Description] nvarchar(500), [Interest_Payments] decimal(5 ,2), [Principal_Payments] decimal(5 ,2), [Transaction_ID] nvarchar(50), [Type] nvarchar(500), [_Position] [int]);
MERGE [MyEntity] USING @toInsert3 AS i ON 1=0
WHEN NOT MATCHED THEN
INSERT ([Amount], [Balance], [Date], [Description], [Interest_Payments], [Principal_Payments], [Transaction_ID], [Type])
VALUES (i.[Amount], i.[Balance], i.[Date], i.[Description], i.[Interest_Payments], i.[Principal_Payments], i.[Transaction_ID], i.[Type])
OUTPUT INSERTED.[MyEntityId], INSERTED.[Amount], INSERTED.[Balance], INSERTED.[Date], INSERTED.[Description], INSERTED.[Interest_Payments], INSERTED.[Principal_Payments], INSERTED.[Transaction_ID], INSERTED.[Type], i._Position
INTO @inserted3;

SELECT [MyEntity] FROM @inserted3
ORDER BY _Position;
',N'@p0 decimal(3,2),**_@p1 decimal(10,5)_**,@p2 datetime2(7),@p3 nvarchar(500),@p4 decimal(1,0),@p5 decimal(3,2),@p6 nvarchar(50),@p7 nvarchar(500)',@p0=1.02,@p1=63155.19395,@p2='2016-05-31 00:00:00',@p3=N'asdfasdfasdfasdfasdsadf',@p4=0,@p5=1.02,@p6=N'1251543238',@p7=N'TTTT___GGGGGG__WWWW'
go
`
the bug si with the parameter @p1. we can see that on the bottom line, the parameter is declared as @p1 decimal(10,5), and the value as @p1=63155.19395 which works. But above in the script, in the @toInsert3 TABLE section, the Balance field is declared as decimal(5 ,2). This causes the error Arithmetic overflow error converting numeric to data type numeric.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: Arithmetic overflow error converting numeric to data type numeric.
Stack trace:

{System.Data.SqlClient.SqlException (0x80131904): Arithmetic overflow error converting numeric to data type numeric.
Invalid object name 'MyEntity'.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
ClientConnectionId:0297e695-e48d-4e73-ab06-e9b4a2e845d7
Error Number:8115,State:8,Class:16}
```
### Further technical details

EF Core version: "Microsoft.EntityFrameworkCore": "1.0.1",
Operating system:  Windows 10 64 enterprise anniversary edition
Visual Studio version: 2015
Other details about my project setup:

**Comment by Huck** [comment]
my bad, I had the decimals with the attribute [Column(TypeName = "decimal(5 ,2)")] in the POCO. sorry.
