### ISSUE TITLE
Method not implemented at MySQL.Data.EntityFrameworkCore.Migrations.Internal.MySQLHistoryRepository.get_ExistsSql()

### ISSUE THREAD

**Issue by thecoderok** [dotnet/efcore#6707]
I am trying to run my application https://github.com/thecoderok/MeasureThat.net on Linux with MySql, but I get following error:
I am getting error "No mapping to a relational type can be found for the CLR type 'Microsoft.EntityFrameworkCore.Metadata.Internal.Property'"
when I run `dotnet ef migrations add testMySql` command

Stack trace:

``` bash
vitalii@vitalii-vm:~/source/MeasureThat.net/src/BenchmarkLab$ dotnet ef migrations add testMySql
Project BenchmarkLab (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
System.InvalidOperationException: No mapping to a relational type can be found for the CLR type 'Microsoft.EntityFrameworkCore.Metadata.Internal.Property'
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapperExtensions.GetMapping(IRelationalTypeMapper typeMapper, IProperty property)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.<Diff>d__31.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.<DiffCollection>d__50`1.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.<Diff>d__24.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.<DiffCollection>d__50`1.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsAddCommand.Execute(CommonOptions commonOptions, String name, String outputDir, String context, String environment, Action`1 reporter)
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)
No mapping to a relational type can be found for the CLR type 'Microsoft.EntityFrameworkCore.Metadata.Internal.Property'
```

Linux version: 

``` bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:    16.04
Codename:   xenial
```

Entity framework tools:

``` json
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
```

**Comment by smitpatel** [comment]
Can you share you model classes & dbcontext?

**Comment by thecoderok** [comment]
They are all here: https://github.com/thecoderok/MeasureThat.net/tree/master/src/BenchmarkLab/Data/Models:

https://github.com/thecoderok/MeasureThat.net/blob/master/src/BenchmarkLab/Data/Models/ApplicationDbContext.cs
https://github.com/thecoderok/MeasureThat.net/blob/master/src/BenchmarkLab/Data/Models/Benchmark.cs
https://github.com/thecoderok/MeasureThat.net/blob/master/src/BenchmarkLab/Data/Models/BenchmarkTest.cs
https://github.com/thecoderok/MeasureThat.net/blob/master/src/BenchmarkLab/Data/Models/Result.cs
https://github.com/thecoderok/MeasureThat.net/blob/master/src/BenchmarkLab/Data/Models/ResultRow.cs

**Comment by smitpatel** [comment]
Your model snapshot is generated using RC2 tooling, it may not work correctly. Can you delete ModelSnapshot and re-generate migration?

**Comment by thecoderok** [comment]
Thank you.
Ok, now I get different exception:

```
vitalii@vitalii-vm:~/source/MeasureThat.net/src/BenchmarkLab$ dotnet ef database update
Project BenchmarkLab (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
System.NotImplementedException: The method or operation is not implemented.
   at MySQL.Data.EntityFrameworkCore.Migrations.Internal.MySQLHistoryRepository.get_ExistsSql()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Tools.Cli.DatabaseUpdateCommand.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Cli
```

**Comment by thecoderok** [comment]
looks like it is really not implemented: http://forums.mysql.com/read.php?38,649918,651130#msg-651130

**Comment by thecoderok** [comment]
Is there any workaround?

**Comment by thecoderok** [comment]
And I tried to handcraft DDL for Asp.Net identity tables, now tables exist. But I start getting first exception:

```
An unhandled exception occurred while processing the request.
InvalidOperationException: No mapping to a relational type can be found for the CLR type 'Microsoft.EntityFrameworkCore.Metadata.Internal.Property'
```

**Comment by rowanmiller** [comment]
There isn't really a workaround, you could look at implementing the missing services in the MySQL provider, but that's probably going to be a lot of work as it doesn't look like MySQL has rounded out their migrations implementation yet.

Closing this issue since the MySQL provider is maintained by the MySQL team and issues should be directed to their issue tracker - http://forums.mysql.com/.

**Comment by divega** [comment]
cc @gmartinezsan

**Comment by gmartinezsan** [comment]
There is a new release coming its way with a fix for this.

**Comment by wickstargazer** [comment]
Hi, When is the release? Cant seem to add migration for identity tables.
