### ISSUE TITLE
List of related entities not loading (null reference exception)

### ISSUE THREAD

**Issue by rykr** [dotnet/efcore#6821]
I have this pattern working in other parts of my app but for some reason I have an entity that has some related entities in another table and trying to load them is throwing a null reference exception.

I'm trying to load them like this:

``` C#
                var matches = _data.PlayerMatches
                    .Include(pm=>pm.PlayerMatchResults)   <-----  these are the related entities
                    .ToList();
```

I've got this in my dbcontext class:

``` C#
            builder.Entity<PlayerMatch>().HasMany(pm=>pm.PlayerMatchResults);
            builder.Entity<PlayerMatchResult>().HasOne(pmr=>pmr.Match);
```

I'm wondering if it doesn't know what fields/keys should be used to load the related entities.  I've created a FK in the db on the column but it didn't help.  The stack trace doesn't show anything useful.

```
   at lambda_method(Closure , ValueBuffer )
   at Microsoft.EntityFrameworkCore.Query.EntityLoadInfo.Materialize()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.GetEntity(IKey key, EntityLoadInfo entityLoadInfo, Boolean queryStateManager, Boolean throwOnNullKey)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.<>c__DisplayClass11_0.<Include>b__0(EntityLoadInfo eli)
   at System.Linq.Enumerable.<>c__DisplayClass149_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.Include(QueryContext queryContext, Object entity, IReadOnlyList`1 navigationPath, IReadOnlyList`1 relatedEntitiesLoaders, Int32 currentNavigationIndex, Boolean queryStateManager)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.Include(QueryContext queryContext, Object entity, IReadOnlyList`1 navigationPath, IReadOnlyList`1 relatedEntitiesLoaders, Boolean queryStateManager)
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_Include>d__30`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at LeagueManager.Controllers.DivisionController.ViewMatch(Int32 match_id) in e:\\work\\personal\\LeagueManager\\Controllers\\DivisionController.cs:line 90
```

Anyone got any idea what I might be doing wrong?

**Comment by rykr** [comment]
Nevermind.  I figured it out.  Stupid user error.  :)

**Comment by Daniel15** [comment]
@rykr What was the problem? I just hit the same issue in my code!

**Comment by rykr** [comment]
I'm sorry.  I don't recall.  Been a bit.  :)
