### ISSUE TITLE
makefile.shade throws: The given key was not present in the dictionary

### ISSUE THREAD

**Issue by miyconst** [dotnet/efcore#6832]
### Steps to reproduce

Follow the steps from [Getting and Building the Code](https://github.com/aspnet/EntityFramework/wiki/Getting-and-Building-the-Code).
### The issue

The `makefile.shade` script fails to execute in both `master` and `develop` branches.

```
D:\GitHub\EntityFramework>build initialzie
Downloading KoreBuild from https://github.com/aspnet/KoreBuild/archive/1.0.0.zip
Building D:\GitHub\EntityFramework
dotnet-install: Downloading https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview2-003131/dotnet-dev-win-x64.1.0.0-preview2-003131.zip
dotnet-install: Extracting zip from https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview2-003131/dotnet-dev-win-x64.1.0.0-preview2-003131.zip
dotnet-install: Adding to current process PATH: "C:\Users\miyco\AppData\Local\Microsoft\dotnet\". Note: This change will
 not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished

Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.
Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include commandline arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.
Configuring...
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 2500 ms
Expanding 100% 8078 ms
log  : Restoring packages for D:\GitHub\EntityFramework\.build\project.json...
log  : Installing NuGetPackageVerifier 1.0.0.
log  : Installing Sake 0.2.2.
log  : Writing lock file to disk. Path: D:\GitHub\EntityFramework\.build\project.lock.json
log  : .build\project.json
log  : Restore completed in 5131ms.
Using makefile: makefile.shade
fail: The given key was not present in the dictionary.
fail: Stack trace:
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)
```
### Further technical details

EF Core version: `1.0.1`
Operating system: `Windows 10 pro x64`
Visual Studio version: `VS2015 14.0.25425.01 Update 3`

**Comment by rowanmiller** [comment]
You want `build initialize` rather than `build initialzie` (and yes we agree the error is unhelpful)
