### ISSUE TITLE
Unable to run Migrations after Upgrade of EFcore from 1.0.0 to 1.1.0

### ISSUE THREAD

**Issue by saad749** [dotnet/efcore#6918]
I am getting the following error after upgrading EFCore from 1.0.0 to 1.1.0 preview 1 while adding migrations. The application is working fine otherwise.

```
PM> Add-Migration preview
An error occurred while calling method 'ConfigureServices' on startup class 'Startup'. Consider using IDbContextFactory to override the initialization of the DbContext at design-time. Error: Value cannot be null.
Parameter name: element
No parameterless constructor was found on 'ApplicationDbContext'. Either add a parameterless constructor to 'ApplicationDbContext' or add an implementation of 'IDbContextFactory<ApplicationDbContext>' in the same assembly as 'ApplicationDbContext'.
PM> dotnet ef migrations add preview
Project Resources (.NETFramework,Version=v4.6.1) was previously compiled. Skipping compilation.
Project PerformanceManagementSystem.Web (.NETFramework,Version=v4.6.1) was previously compiled. Skipping compilation.
An error occurred while calling method 'ConfigureServices' on startup class 'Startup'. Consider using IDbContextFactory to override the initialization of the DbContext at design-time. Error: Value cannot be null.
Parameter name: element
dotnet.exe : No parameterless constructor was found on 'ApplicationDbContext'. Either add a parameterless constructor to 'ApplicationDbContext' or add an implementation of 'IDbContextFactory<ApplicationDbContext>' in the same assembly as 
'ApplicationDbContext'.At line:1 char:1
+ dotnet ef migrations add preview
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (No parameterles...tionDbContext'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

This is my complete project.json
```
{
  "dependencies": {
    "AutoMapper": "5.1.1",
    "Microsoft.NETCore.Portable.Compatibility": "1.0.1",
    "Resources": "1.0.0-*",
    "BundlerMinifier.Core": "2.2.296",
    "Hangfire.AspNetCore": "1.6.6",
    "Hangfire.SqlServer": "1.6.6",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0-preview1-final",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0-preview1-final",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0-preview1-final",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0-preview1-final",
    "Microsoft.AspNetCore.Mvc": "1.1.0-preview1-final",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview3-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0-preview1-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0-preview1-final",
    "Microsoft.AspNetCore.Session": "1.1.0-preview1-final",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0-preview1-final",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0-preview1-final",
    "Microsoft.EntityFrameworkCore.Design": "1.1.0-preview1-final",
    "Microsoft.Extensions.Caching.Memory": "1.1.0-preview1-final",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0-preview1-final",
    "Microsoft.Extensions.Configuration.Json": "1.1.0-preview1-final",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.1.0-preview1-final",
    "Microsoft.Extensions.Logging": "1.1.0-preview1-final",
    "Microsoft.Extensions.Logging.Console": "1.1.0-preview1-final",
    "Microsoft.Extensions.Logging.Debug": "1.1.0-preview1-final",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0-preview1-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0-preview1-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": "1.0.0-preview3-final",
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": "1.0.0-preview3-final",
    "NUglify": "1.5.3",
    "System.Drawing.Primitives": "4.3.0-preview1-24530-04",
    "Z.EntityFramework.Plus.EFCore": "1.4.9",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0-preview1-final",
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview3-final",
      "type": "build"
    }
  },

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview3-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview3-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview3-final",
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.0.0-preview3-final",
    "Microsoft.EntityFrameworkCore.Design": "1.1.0-preview1-final",
    "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview3-final"
  },

  "frameworks": {
    "net461": {
      "imports": [  ]
    }
  },
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

P.S. I am using Visual studio 2015

**Comment by rowanmiller** [comment]
Can you run with `-verbose` and post the output?

**Comment by saad749** [comment]
Following is the output.
```
Setting app base path C:\Users\yyy\Desktop\Saad\Projects\yyy\XXX\src\XXX.Web\bin\Debug\net461\win7-x64
An error occurred while calling method 'ConfigureServices' on startup class 'Startup'. Consider using IDbContextFactory to override the initialization of the DbContext at design-time. Error: Value cannot be null.
Parameter name: element
System.ArgumentNullException: Value cannot be null.
Parameter name: element
   at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttribute(Assembly element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](Assembly element)
   at Microsoft.Extensions.Configuration.ConfigurationExtensions.AddUserSecrets(IConfigurationBuilder configuration)
   at XXX.Web.Startup..ctor(IHostingEnvironment env) in C:\Users\yyy\Desktop\Saad\Projects\yyyy\XXX\src\XXX.Web\Startup.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.EntityFrameworkCore.Design.Internal.StartupInvoker.Invoke(Type type, String[] methodNames, IServiceCollection services)
Finding DbContext classes...
Microsoft.EntityFrameworkCore.Design.OperationException: No parameterless constructor was found on 'ApplicationDbContext'. Either add a parameterless constructor to 'ApplicationDbContext' or add an implementation of 'IDbContextFactory<ApplicationDbContext>' in t
he same assembly as 'ApplicationDbContext'. ---> System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

This is line 45 from Startup.cs
```
42 if (env.IsDevelopment())
43            {
 44               // For more details on using the user secret store see http://go.microsoft.com/fwlink/?LinkID=532709
45                builder.AddUserSecrets();
46            }
```

I simply commented this block, and the migrations ran fine.
P.S. I haven't configured any secrets for the project.
Before upgrading, the migrations used to run in the same scenario

Is it expected behavior?

**Comment by divega** [comment]
@natemcmaster looks like the exception could be coming from the new attribute handling code in user secrets. Thoughts?

**Comment by natemcmaster** [comment]
`Assembly.GetEntryAssembly()` is returning null because of the way EF invokes the startup class inside an appdomain.

Workaround: use the AddUserSecrets overload for the assembly that has your startup class.
```c#
.AddUserSecrets(typeof(Startup).GetTypeInfo().Assembly)
```

UserSecrets should throw a better error message in this case. I'll have to think about the parameterless version `.AddUserSecrets()` to see if it can be smarter in this situation.

**Comment by divega** [comment]
@natemcmaster do we have a separate bug tracking what the CLI change that broke the `GetEntryAssembly()` API? 

It seems to me that for this customer issue you have already answered with a workaround and can be closed. Thoughts?

**Comment by natemcmaster** [comment]
>  what the CLI change that broke the GetEntryAssembly() API

The API is working as expected. Inside an app domain, this GetEntryAssembly returns null because EF tools don't (and shouldn't) call AppDomain.ExecuteAssembly.

Yes, close as external to EF. Tracking this with https://github.com/aspnet/Configuration/issues/543.
