### ISSUE TITLE
Nested transactions occurred with ConcurrencyCheck in MySQL provider.

### ISSUE THREAD

**Issue by gmartinezsan** [dotnet/efcore#7017]
### Steps to reproduce
Before updating to EF Core 1.1 this same example was working with our MySQL provider. 
https://docs.microsoft.com/en-us/ef/core/saving/concurrency

### The issue
After updating to EF Core 1.1 we have a nested transaction exception. MySQL does not support nested transactions. Which I think might be the problem if this is a requirement in order to support the ConcurrencyCheck functionality.

Here's is the call stack

System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=Nested transactions are not supported.
  Source=MySql.Data
  StackTrace:
       at MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex) in D:\Repository\Git\6.10\devForDebugging\Source\MySql.Data\Connection.cs:line 744
       at MySql.Data.MySqlClient.MySqlConnection.BeginTransaction(IsolationLevel iso) in D:\Repository\Git\6.10\devForDebugging\Source\MySql.Data\Connection.cs:line 242
       at MySql.Data.MySqlClient.MySqlConnection.BeginTransaction() in D:\Repository\Git\6.10\devForDebugging\Source\MySql.Data\Connection.cs:line 230
       at MySql.Data.MySqlClient.MySqlConnection.BeginDbTransaction(IsolationLevel isolationLevel) in D:\Repository\Git\6.10\devForDebugging\Source\MySql.Data\Framework\MySqlConnection.cs:line 91
       at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionWithNoPreconditions(IsolationLevel isolationLevel) in D:\Repository\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Storage\RelationalConnection.cs:line 192
       at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction(IsolationLevel isolationLevel) in D:\Repository\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Storage\RelationalConnection.cs:line 157
       at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction() in D:\Repository\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Storage\RelationalConnection.cs:line 129
       at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters) in D:\Repository\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Update\Internal\BatchExecutor.cs:line 63
       at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state) in D:\Repository\EntityFramework\src\Microsoft.EntityFrameworkCore\Storage\Internal\NoopExecutionStrategy.cs:line 38
       at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, TState state) in D:\Repository\EntityFramework\src\Microsoft.EntityFrameworkCore\Extensions\ExecutionStrategyExtensions.cs:line 236
       at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection) in D:\Repository\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Update\Internal\BatchExecutor.cs:line 50
       at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries) in D:\Repository\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Storage\RelationalDatabase.cs:line 59
       at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave) in D:\Repository\EntityFramework\src\Microsoft.EntityFrameworkCore\ChangeTracking\Internal\StateManager.cs:line 651
       at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess) in D:\Repository\EntityFramework\src\Microsoft.EntityFrameworkCore\ChangeTracking\Internal\StateManager.cs:line 576
       at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess) in D:\Repository\EntityFramework\src\Microsoft.EntityFrameworkCore\DbContext.cs:line 272
  InnerException: 

### Further technical details

EF Core version: 1.1.0-preview1-final
Operating system: Windows
Visual Studio version: 2015

@divega
@rowanmiller

Were there any changes that affected this functionality to require nesting a second transaction?
Thanks in advance.

**Comment by gmartinezsan** [comment]
@AndriySvyryd hi! Any feedback yet?
Thanks!

**Comment by AndriySvyryd** [comment]
@gmartinezsan There were definitely changes in this part of the code, however nested transaction support is not required.
Can you identify where the first transaction is started? MySQL provider might need to update the implementation to track the current transaction.

**Comment by gmartinezsan** [comment]
@AndriySvyryd Thanks for the feedback. I'll review the process and let you know if I have any question.

**Comment by gmartinezsan** [comment]
@AndriySvyryd hi, just a follow up. We found a bug in our provider in the transactions disposing process. All green now. Thanks a lot for the attention!.

**Comment by alengy** [comment]
What is the place where insert this workaround?
context.Database.AutoTransactionsEnabled = false

**Comment by ajcvickers** [comment]
@alengy "context" is your DbContext instance.

**Comment by DenysTr** [comment]
Thank you!
It helped me!
