### ISSUE TITLE
ApplicationUser Inheritance requires discriminator property

### ISSUE THREAD

**Issue by joeizang** [dotnet/efcore#7035]
Hi everyone,
I am running a standard asp.net core 1.0.1 with EF core 1.0.1 with sapient.EntityFramework.MySql nuget installed. I have 5 users in my application that inherit from ApplicationUser namely student, staff, teacher, guardian and admin. When I run migrations, I get the following error: The entity type 'ApplicationUser' is part of a hierarchy, but does not have a discriminator property configured. Below are snippets of my code:

``` C#
class Student : ApplicationUser
{}
class Guardian : ApplicationUser
{}
class Staff : ApplicationUser
{}
class Teacher : ApplicationUser
{}
class Admin : ApplicationUser
{}

class SampleDb : IdentityDbContext<ApplicationUser>
{
    public DbSet<Student> {get; set; }
    ....
    public DbSet<Admin> { get; set; }
}
```

When trying to run the migrations, it gives the error I mentioned. Here is the error it shows:

> System.InvalidOperationException: The entity type 'ApplicationUser' is part of a hierarchy, but does not have a discriminator property configured.
   at Microsoft.EntityFrameworkCore.Internal.ModelValidator.ShowError(String message)
   at Microsoft.EntityFrameworkCore.Internal.RelationalModelValidator.ValidateDiscriminator(IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Internal.RelationalModelValidator.ValidateDiscriminatorValues(IEntityType rootEntityType, IReadOnlyList`1 derivedTypes)
   at Microsoft.EntityFrameworkCore.Internal.RelationalModelValidator.ValidateInheritanceMapping(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsAddCommand.Execute(CommonOptions commonOptions, String name, String outputDir, String context, String environment, Action`1 reporter)
   at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsAddCommand.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)
The entity type 'ApplicationUser' is part of a hierarchy, but does not have a discriminator property configured.

### Further technical details

EF Core version: 
dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    }
"Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
"Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    }
"Microsoft.EntityFrameworkCore": "1.0.1",
    "Microsoft.EntityFrameworkCore.Relational": "1.0.1",
"SapientGuardian.EntityFrameworkCore.MySql": "7.1.14"
"Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"

Windows 10 Pro 1607
Visual Studio 2015 Community Edition Update 3

**Comment by ajcvickers** [comment]
Moved to https://github.com/aspnet/Identity/issues/1590
