### ISSUE TITLE
Scaffolding not working, _EFGetProjectMetadata does not exist! Visual Studio 2017RC

### ISSUE THREAD

**Issue by hyuksel** [dotnet/efcore#7072]
Hi,

i have created a new asp.net core web application, with Change Authentication and individual User account (no host in cloud). 
It creates a project for me, but the first thing that it's odd with core 1.0 libraries. 
Why not the latest 1.1 core version packages because i'm using the newly released Visual Studio 2017RC?

Then i have to update all packages to 1.1. It doesn't however update some of the packages to version 1.1 such as Microsoft.EntityFrameworkCore.Tools, so i do a install-package Microsoft.EntityFrameworkCore.Tools -pre in the package manager console and update them to the latest version like Microsoft.EntityFrameworkCore.Tools 1.1.0-preview4-final'.

Now i want to scaffold my SQL Server data. I execute the following command:

dotnet ef dbcontext scaffold "Server=<<SERVERNAME>;Database=<<DATABASE>>;User Id=<<USER>>;Password=<<PASSWORD>>;MultipleActiveResultSets=true" Microsoft.EntityFrameworkCore.SqlServer --output-dir DAL --force

It gives me the following error:

**CoreTester.csproj : error MSB4057: The target "_EFGetProjectMetadata" does not exist in the project.
CoreTester.csproj" (_EFGetProjectMetadata target(s)) -- FAILED.
rror MSB4057: The target "_EFGetProjectMetadata" does not exist in the project.
CoreTester.csproj'. Ensure the package 'Microsoft.EntityFrameworkCore.Tools' is installed.**

It says that Microsoft.EntityFrameworkCore.Tools is NOT installed, but i have installed the latest version?
How can we make this work, because i've upgraded my existing 1.0 project to 1.1 but i'm stuck now not being able to generate my Data Access by scaffolding my database.

Best, Hayko.

<img width="270" alt="solution1" src="https://cloud.githubusercontent.com/assets/22980284/20462169/a190b28c-af15-11e6-9d01-c45f14beb904.png">

**Comment by charleeswann** [comment]
I have the same issue, can anyone assist with this? thank you

**Comment by hyuksel** [comment]
Hi Charles,

btw my workaround is to maintain the old project in Dotnetcore 1.0 (in another temp folder) and scaffold /update my classes there and copy the folders to my new VS2017 project folder. I kept the same Assembly and Namespace and everything works fine. I hope the Core team solves the problem soon though.. 👍

**Comment by rowanmiller** [comment]
Hey,

First up I just want to acknowledge that this is all super messy at the moment, so I realize the steps to get this working are far from intuitive.

To use `dotnet ef` you need to install a particular version of the tools that are designed to work with the new .NET Core MSBuild work in VS2017. Note that it is `...Tools.DotNet` and not `...Tools`.

```
PM> Install-Package Microsoft.EntityFrameworkCore.Tools.DotNet -Version 1.0.0-msbuild1-final -Pre 
```

This is mutually exclusive with `Install-Package Microsoft.EntityFrameworkCore.Tools` version `1.1.0-preview4`, so you need to uninstall that package.

For more detailed info, see the end of this post https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-entity-framework-core-1-1/

**Comment by rowanmiller** [comment]
@hyuksel @charleeswann are you able to confirm if this is working with the correct package versions installed?

**Comment by hyuksel** [comment]
I'm getting the following error?

Dependency specified was Microsoft.NET.Sdk.Web (>= 1.0.0-alpha-20161104-2) but ended up with Microsoft.NET.Sdk.Web 1.0.0-alpha-20161104-2-112.
Install-Package : Package 'Microsoft.EntityFrameworkCore.Tools.DotNet 1.0.0-msbuild1-final' has a package type 'DotnetCliTool' that is not supported by project 'XXXXX'.
At line:1 char:1
+ Install-Package Microsoft.EntityFrameworkCore.Tools.DotNet -Version 1 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by rowanmiller** [comment]
@hyuksel I am working on sorting out the `dotnet ef` issue at the moment. In the meantime, if you install the following package, are you able to use the `Scaffold-DbContext` command in Package Manager Console?

```
PM> Install-Package Microsoft.EntityFrameworkCore.Tools -Pre 
```

**Comment by hyuksel** [comment]
Hi @rowanmiller ,

i can confirm that Scaffold-DbContext is working in the package-manager!

**Comment by rowanmiller** [comment]
Great. Once we sort out all the issues with `dotnet ef` I will update the blog post with details (and reply here too)

**Comment by hyuksel** [comment]
I think issues are from over :-( 
Publishing my project in Visual studio 2017RC doesn't work. I needed to fix some lines in Microsoft.NET.Publish.targets (http://stackoverflow.com/questions/40690233/publishing-with-visual-studio-2017-mvc-asp-net-core-they-must-have-the-same-num/40808866#40808866) to get some output. wwwroot folders are not published and when I upload everyting to windows 2012 server IIS (installed 1.1 runtime and DotNetCore.1.1.0-WindowsHosting.exe) it crashes on startup. I checked all lines and it doesn't recognize "Configuration.GetConnectionString("DefaultConnection")" in startup.
Put hardcoded connectionstrings in it and still no go. I don't know if this has something to do with EF, but all started when using VS2017RC .

Do you know who can help with publishing to IIS on Windows 2012, because now i lost my staging environment for my customer to look at the progress and test :-(

Application startup exception: System.ArgumentNullException: Value cannot be null.
Parameter name: connectionString
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotEmpty(String value, String parameterName)
   at Microsoft.EntityFrameworkCore.SqlServerDbContextOptionsExtensions.UseSqlServer(DbContextOptionsBuilder optionsBuilder, String connectionString, Action`1 sqlServerOptionsAction)
   at Fulfilment_Software.Startup.<ConfigureServices>b__5_3(DbContextOptionsBuilder options) in Startup.cs:line 98
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.DbContextOptionsFactory[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitClosedIEnumerable(ClosedIEnumerableCallSite closedIEnumerableCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.<>c.<AddMvcCoreServices>b__5_0(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitClosedIEnumerable(ClosedIEnumerableCallSite closedIEnumerableCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitClosedIEnumerable(ClosedIEnumerableCallSite closedIEnumerableCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action`1 configureRoutes)
   at Fulfilment_Software.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in Startup.cs:line 240
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
Hosting environment: Production
Content root path: C:\XXXXX
Now listening on: http://localhost:12663
Application started. Press Ctrl+C to shut down.

**Comment by rowanmiller** [comment]
The fix for this will be part of https://github.com/aspnet/EntityFramework/issues/7066.

In the meantime, we have updated our guidance to tell folks to just use Package Manager Console in VS2017 RC.

**Comment by rowanmiller** [comment]
@hyuksel please open a new issue for the next problem you have encountered (with publishing)
