### ISSUE TITLE
Include entity in generic query not working (

### ISSUE THREAD

**Issue by JakubR** [dotnet/efcore#7075]
### Steps to reproduce
I want to include tables(maped to properties) of my class but it is not working.

```C#
 public class LicesnseKey
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public DateTime ValidTo { get; set; }
        public SomeUser Owner { get; set; }
    }

var result = repo.GetData(key => key.Owner.Id == userId, "Owner");
```
[...i will insert full implementation if it will be needed...]

```C#
public ICollection<T> GetData(Expression<Func<T, bool>> predicate, params string[] includePropertyNames)
        {
            if (includePropertyNames == null)
            {
                return _context.Set<T>().Where(predicate).ToList();
            }
            var firstPropertyToInclude = includePropertyNames.First();
           
            return _context.Set<T>().Include(arg => arg.GetType().GetProperty(firstPropertyToInclude)).Where(predicate).ToList();            
        }
```

Exception message (lib in version : 1.0.1):
An exception of type 'System.InvalidOperationException' occurred in Microsoft.EntityFrameworkCore.dll but was not handled in user code

Additional information: The property expression 'arg => GetProperty(arg.GetType(), __firstPropertyToInclude_0)' is not valid. The expression should represent a property access: 't => t.MyProperty'. For more information on including related data, see http://go.microsoft.com/fwlink/?LinkID=74639

```
Stack trace:
   at Microsoft.EntityFrameworkCore.Query.ResultOperators.Internal.IncludeExpressionNode.CreateResultOperator(ClauseGenerationContext clauseGenerationContext)
   at Remotion.Linq.Parsing.Structure.IntermediateModel.ResultOperatorExpressionNodeBase.ApplyNodeSpecificSemantics(QueryModel queryModel, ClauseGenerationContext clauseGenerationContext)
   at Remotion.Linq.Parsing.Structure.IntermediateModel.MethodCallExpressionNodeBase.Apply(QueryModel queryModel, ClauseGenerationContext clauseGenerationContext)
   at Remotion.Linq.Parsing.Structure.QueryParser.ApplyAllNodes(IExpressionNode node, ClauseGenerationContext clauseGenerationContext)
   at Remotion.Linq.Parsing.Structure.QueryParser.GetParsedQuery(Expression expressionTreeRoot)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileQuery>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CantorexApi.Context.ReadOnlyRepository`1.GetData(Expression`1 predicate, String[] includePropertyName) in...
```

exception (lib in version 1.1.0):
An exception of type 'System.MissingMethodException' occurred in System.Private.CoreLib.ni.dll but was not handled in user code

Additional information: Method not found: 'Void Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory..ctor(Microsoft.EntityFrameworkCore.Infrastructure.ISensitiveDataLogger`1<Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory>, System.Diagnostics.DiagnosticSource, Microsoft.EntityFrameworkCore.Storage.IRelationalTypeMapper)'.

### Further technical details

EF Core version: 1.0.1 and 1.1.0
Operating system: win 10
Visual Studio version: 2015

Please help me.
Kind regards

**Comment by JakubR** [comment]
Exception below was, because I didn't upgrade mysl pomelo connector : 

Additional information: Method not found: 'Void Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory..ctor(Microsoft.EntityFrameworkCore.Infrastructure.ISensitiveDataLogger`1<Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory>, System.Diagnostics.DiagnosticSource, Microsoft.EntityFrameworkCore.Storage.IRelationalTypeMapper)'.

I sovled problem using this construction :
public interface IReadOnlyRepository<T>
    {
        ICollection<T> GetData(Expression<Func<T, bool>> predicate,
            params Expression<Func<T, object>>[] includeProperties);
    }

public ICollection<T> GetData(Expression<Func<T, bool>> predicate, params Expression<Func<T, object>>[] includeProperties)
        {
            return AllIncluding(includeProperties).Where(predicate).ToList();            
        }

        private IQueryable<T> AllIncluding(params Expression<Func<T, object>>[] includeProperties)
        {
            IQueryable<T> query = _context.Set<T>();
            foreach (var includeProperty in includeProperties)
            {
                query = query.Include(includeProperty);
            }
            return query;
        }
Thanks.
