### ISSUE TITLE
Tooling not working on Mac without project.json

### ISSUE THREAD

**Issue by alastairanderson** [dotnet/efcore#7081]
### Steps to reproduce
1. Have `1.0.0-preview3-004056` installed on Mac (macOS Sierra 10.12.1)
2. Create new project template `dotnet new -t web` which now gives a .csproj file
3. In the .csproj file, add dependencies required for EF and tooling, so it looks like this:
```xml
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>

  <PropertyGroup>
    <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81;</PackageTargetFallback>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**\*.cs" Exclude="$(GlobalExclude)" />
    <EmbeddedResource Include="**\*.resx" Exclude="$(GlobalExclude)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.App">
      <Version>1.0.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Sdk.Web">
      <Version>1.0.0-alpha-20161104-2-112</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics">
      <Version>1.0.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc">
      <Version>1.0.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Razor.Tools">
      <Version>1.0.0-preview2-final</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Routing">
      <Version>1.0.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration">
      <Version>1.0.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel">
      <Version>1.0.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles">
      <Version>1.0.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables">
      <Version>1.0.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json">
      <Version>1.0.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Console">
      <Version>1.0.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Debug">
      <Version>1.0.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions">
      <Version>1.0.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink.Loader">
      <Version>14.0.0</Version>
    </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <Version>1.1.0-preview4-final</Version>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet">
      <Version>1.1.0-preview4-final</Version>
    </DotNetCliToolReference>
  </ItemGroup>

  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```
Note: I understand the issue is around project.json, and I'm using the .csproj file, but if this is the new default, then surely this should work regardless.

4. Run `dotnet restore` followed by `dotnet build` and it all runs without any errors or warnings
5. Attempt to view the EF help `dotnet ef --help` which results in the following error:
```
System.IO.FileNotFoundException: Could not find file '/Users/username/Documents/Projects/Examples/dotnettest/aspnetnew/project.json'.
File name: '/Users/username/Documents/Projects/Examples/dotnettest/aspnetnew/project.json'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo[TSafeHandle](TSafeHandle handle, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.DotNet.ProjectModel.ProjectReader.GetProject(String projectPath, ProjectReaderSettings settings)
   at Microsoft.DotNet.ProjectModel.ProjectContext.<CreateContextForEachFramework>d__45.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at NuGet.Frameworks.FrameworkReducer.GetNearestInternal(NuGetFramework framework, IEnumerable`1 possibleFrameworks)
   at NuGet.Frameworks.FrameworkReducer.GetNearest(NuGetFramework framework, IEnumerable`1 possibleFrameworks)
   at NuGet.Frameworks.NuGetFrameworkUtility.GetNearest[T](IEnumerable`1 items, NuGetFramework framework, IFrameworkNameProvider frameworkMappings, IFrameworkCompatibilityProvider compatibilityProvider, Func`2 selector)
   at Microsoft.EntityFrameworkCore.Tools.DotNet.Internal.ProjectContextFactory.SelectCompatibleFramework(NuGetFramework target, IEnumerable`1 contexts)
   at Microsoft.EntityFrameworkCore.Tools.DotNet.Internal.ProjectContextFactory.Create(String filePath, NuGetFramework framework, String configuration, String outputDir)
   at Microsoft.EntityFrameworkCore.Tools.DotNet.Internal.DispatchOperationExecutor.Execute(CommandLineOptions options)
   at Microsoft.EntityFrameworkCore.Tools.DotNet.Program.Main(String[] args)
Could not find file '/Users/username/Documents/Projects/Examples/dotnettest/aspnetnew/project.json'.
```

**Comment by rowanmiller** [comment]
First up I just want to acknowledge that this is all super messy at the moment, so I realize the steps to get this working are far from intuitive.

To use `dotnet ef` you need to install a particular version of the tools that are designed to work with the new .NET Core MSBuild work in VS2017. You want `1.0.0-msbuild1-final` for the `Microsoft.EntityFrameworkCore.Tools.DotNet` package.

**Comment by alastairanderson** [comment]
Thanks for taking the time to respond @rowanmiller 

That's done the trick. Appreciate that things are in flux just now. First time I've seen that particular version mentioned anywhere, but hopefully if anyone else is experiencing the same pain they will come across this thread

Thanks and closing

**Comment by rowanmiller** [comment]
The best source for this info is the Upgrading to 1.1 section in the announcement post - https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-entity-framework-core-1-1/.

And as you said, things are very much in-flux and will be much less fragmented by the time we reach RTM.
