### ISSUE TITLE
Inheritance mapping on generic types

### ISSUE THREAD

**Issue by thepinkmile** [dotnet/efcore#7086]
### The issue
If you have different types that are related in some way, when you try to map all the "Many-to-Many" relationships via a single table using a discriminator column, adding a new migration fails.

Exception message:
Stack trace:
```
System.InvalidOperationException: The entity type 'NewsPageDocument' cannot inherit from 'Relationship<Page, LibraryItem>' because 'NewsPageDocument' is not a descendent of 'Relationship<Page, LibraryItem>'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.HasBaseType(EntityType entityType, ConfigurationSource configurationSource, Boolean runConventions)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasBaseType(EntityType baseEntityType, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.DiscriminatorBuilder.HasValue(InternalEntityTypeBuilder entityTypeBuilder, Object value)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.DiscriminatorBuilder`1.HasValue(Type entityType, TDiscriminator value)
   at Website.Dal.DatabaseContext.<>c.<OnModelCreating>b__3_4(EntityTypeBuilder`1 e) in C:\Source\EF-Demo\EntityFrameworkCore\src\Website\Dal\DatabaseContext.cs:line 56
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity[TEntity](Action`1 buildAction)
   at Website.Dal.DatabaseContext.OnModelCreating(ModelBuilder modelBuilder) in C:\Source\EF-Demo\EntityFrameworkCore\src\Website\Dal\DatabaseContext.cs:line 50
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The entity type 'NewsPageDocument' cannot inherit from 'Relationship<Page, LibraryItem>' because 'NewsPageDocument' is not a descendent of 'Relationship<Page, LibraryItem>'.
```
### Steps to reproduce
[EntityFrameworkCore.zip](https://github.com/aspnet/EntityFramework/files/604210/EntityFrameworkCore.zip)

Load the project in the attached zip file.
Build solution (No Errors)
Go to "Package Manager Console"
Type: "Add-Migration "test"
See error.

### Expected result
In my example project, as NewsPage is a Page and Document is a LibraryItem, I expect this to detect the inheritance chain correctly and apply the relevant mapping.

### Further technical details

EF Core version: found in project.json (v1.1.0)
Operating system: Windows 10 Pro
Visual Studio version: VS2015 Community

**Comment by rowanmiller** [comment]
The problem is that you are trying to map `NewsPageDocument` and `ProductPageImage` as if they have the both inherit from `Relationship<Page, LibraryItem>`, but they do not. 

```c#
modelBuilder.Entity<Relationship<Page, LibraryItem>>(e =>
{
    e.ToTable("PageLibraryItems");
    e.HasKey(r => new {r.ParentId, r.ChildId});
    e.HasOne(r => r.Parent).WithMany().IsRequired().OnDelete(DeleteBehavior.Restrict);
    e.HasOne(r => r.Child).WithMany().IsRequired().OnDelete(DeleteBehavior.Restrict);
    e.HasDiscriminator<string>("Type")
        .HasValue<NewsPageDocument>(nameof(NewsPageDocument))
        .HasValue<ProductPageImage>(nameof(ProductPageImage));
});
```

`NewsPageDocument` inherits `Relationship<NewsPage, Document>` and `ProductPageImage` inherits `Relationship<ProductPage, Image>`. I realize that both `NewsPage` and `ProductPage` inherit `Page` and that `Document` and `Image` inherit `LibraryItem`... but that's not how inheritance works with generic in .NET (not specific to EF at all).

To demonstrate this, if you run the following code, you'll see that `x` is true, and `y` is false.

```c#
var x = typeof(Relationship<ProductPage, Image>).IsAssignableFrom(typeof(ProductPageImage));
            var y = typeof(Relationship<Page, LibraryItem>).IsAssignableFrom(typeof(Relationship<ProductPage, Image>));
```
