### ISSUE TITLE
The entity type 'Uri' requires a primary key to be defined (EF Core 1.1)

### ISSUE THREAD

**Issue by WilliamABradley** [dotnet/efcore#7133]
### Steps to reproduce
Called: Add-Migration SeriesStoreV1 -context SeriesStore
Code file:
```
namespace TVPLAN.Models.Data
{
    public class SeriesStore : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            string filename = "SeriesStore.db";
            try
            {
                var connectionString = $"filename={System.IO.Path.Combine(ApplicationData.Current.LocalCacheFolder.Path, filename)}";
                optionsBuilder.UseSqlite(connectionString);
            }
            catch
            {
                optionsBuilder.UseSqlite($"filename={filename}");
            }
        }
        public DbSet<Series> TVDBSeries { get; set; }
        public DbSet<Episode> TVDBEpisodes { get; set; }
        public DbSet<Actor>  TVDBActors { get; set; }
        public DbSet<TraktShow> TraktShows { get; set; }
        public DbSet<TraktSeason> TraktSeasons { get; set; }
        public DbSet<TraktEpisode> TraktEpisodes { get; set; }
        public DbSet<TraktShowIds> TraktShowIDs { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // TVDB Linking //
            modelBuilder.Entity<Series>().HasKey(c => c.Id);
            modelBuilder.Entity<Series>().HasMany(c => c.Episodes).WithOne().HasForeignKey(k => k.SeriesId);
            modelBuilder.Entity<Series>().HasMany(c => c.Actors).WithOne().HasForeignKey(k => k.SeriesId);

            modelBuilder.Entity<Actor>().HasKey(k => k.Id);
            modelBuilder.Entity<Episode>().HasKey(k => k.Id);
            
            // TRAKT Linking //

            modelBuilder.Entity<TraktShow>().HasKey(c => c.Id);
            modelBuilder.Entity<TraktShow>().HasMany(c => c.Seasons).WithOne().HasForeignKey(item => item.TraktShowId);

            modelBuilder.Entity<TraktSeason>().Property(f => f.Id).ValueGeneratedOnAdd();
            modelBuilder.Entity<TraktSeason>().HasKey(c => c.Id);
            modelBuilder.Entity<TraktSeason>().HasMany(c => c.Episodes).WithOne();

            modelBuilder.Entity<TraktEpisode>().HasKey(c => c.Id);

            modelBuilder.Entity<TraktShowAirs>().Property(f => f.Id).ValueGeneratedOnAdd();

            base.OnModelCreating(modelBuilder);
        }

        public async Task<Series> getOrFetchSeriesData(SeriesID id)
        {
            var result = TVDBSeries.FirstOrDefault(item => item.Id == id.TVDB);
            if (result == null)
            {
                result = await API.TVDBClient.GetSeries(id.TVDB, settings.language);
                using (var cache = new SeriesStore())
                {
                    cache.TVDBSeries.Add(result);
                    await cache.SaveChangesAsync();
                }
            }
            return result;
        }

        public Series getSeriesData(SeriesID id)
        {
            var series = TVDBSeries.FirstOrDefault(item => item.Id == id.TVDB);
            if(series != null)
            {
                var episodes = TVDBEpisodes.Where(item => item.SeriesId == id.TVDB);
                series.Episodes = episodes.OrderBy(ep => ep.SeasonNumber).ThenBy(ep => ep.Number).ToList();
                var actors = TVDBActors.Where(item => item.SeriesId == id.TVDB);
                series.Actors = actors.OrderBy(item => item.SortOrder).ToList();
            }
            return series;
        }

        public Series getSeriesData(uint TVDBID)
        {
            return TVDBSeries.Include(item => item.Episodes).FirstOrDefault(item => item.Id == TVDBID);
        }

        public TraktShow getTraktData(SeriesID id)
        {
            return TraktShows.FirstOrDefault(item => item.Ids.Trakt == id.Trakt);
        }

        public Episode getTVDBEpisode(SeriesID id, int season, int episode)
        {
            return TVDBEpisodes.FirstOrDefault(item => item.SeriesId == id.TVDB && item.SeasonNumber == season && item.Number == episode);
        }

        public TraktEpisode getTraktEpisode(SeriesID id, int season, int episode)
        {
            return TraktEpisodes.FirstOrDefault(item => item.SeriesID == id.TVDB && item.SeasonNumber == season && item.EpisodeNumber == episode);
        }
    }
}
```

### The issue
I had deleted the previous migration for this code file, because I haven't finished it's design, I am using a different EF Core version and VS version to what I originally used. I also have 3 more DBs in the same Library.

```
Exception message:
Stack trace:
System.InvalidOperationException: The entity type 'Uri' requires a primary key to be defined.
   at Microsoft.EntityFrameworkCore.Internal.ModelValidator.ShowError(String message)
   at Microsoft.EntityFrameworkCore.Internal.ModelValidator.EnsureNonNullPrimaryKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass14_0.<GetModel>b__0(Object k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_6(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactoryService(FactoryService factoryService, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.<>c__DisplayClass6_0.<ConfigureContextServices>b__9(IServiceProvider _)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactoryService(FactoryService factoryService, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The entity type 'Uri' requires a primary key to be defined.
```

### Further technical details

EF Core version:
    "Microsoft.EntityFrameworkCore.Design": "1.1.0",
    "Microsoft.EntityFrameworkCore.Sqlite": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
Operating system: Windows 10 Anniversary Update
Visual Studio version: VS 2017 RC

**Comment by ajcvickers** [comment]
@WilliamABradley Does the model building code reference the Uri property anywhere? I don't see any reference to it in the code above but just checking it isn't somewhere else that was not mentioned. Could you post the code for your entity types?

Note for triage: Looks like the Uri class is being brought into the model as an entity type. I'm not sure why this is happening unless it is referenced explicitly in model building. Unless it is explicitly mapped I would expect to see the error "The property '{entityType}.{property}' could not be mapped, because it is of type '{propertyType}' which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it."

**Comment by AndriySvyryd** [comment]
@WilliamABradley Please provide the full model if you are still experiencing this issue.

**Comment by WilliamABradley** [comment]
I discovered what was causing the issue, I had a Uri property marked with Attribute [NotMapped], however, EF Core is Still reading it. Commenting it out reveals that EF Core isn't reading any of my Attributes as classes with the [Key] Attribute are not working either. Is this issue fixable, or should I switch to Fluent API?

**Comment by AndriySvyryd** [comment]
@WilliamABradley Are you targeting UWP by any chance?

**Comment by WilliamABradley** [comment]
@AndriySvyryd That is correct

**Comment by AndriySvyryd** [comment]
@WilliamABradley Then you are hitting a known issue - https://github.com/aspnet/EntityFramework/issues/7194
You can use [this workaround ](https://github.com/aspnet/EntityFramework/issues/7045#issuecomment-265010057) or downgrade .Tools to preview-3.

**Comment by WilliamABradley** [comment]
@AndriySvyryd That's good to know its a known issue, I have switched to Fluent for the Meantime.
