### ISSUE TITLE
MissingMethodException after updating from 1.0 to 1.1

### ISSUE THREAD

**Issue by jeffbromberger** [dotnet/efcore#7139]
### Steps to reproduce

The following simple query worked fine with EF Core 1.0 but now fails with 1.1:

````
 var results = databaseStore.Notifications
                                        .Where(n => n.Username == user.Username)
                                        .Select(n => n.GetDTO());
````

```
Exception message:

Method not found: 'Void Microsoft.EntityFrameworkCore.Query.QueryContextFactory..ctor(Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IStateManager, Microsoft.EntityFrameworkCore.Internal.IConcurrencyDetector, Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IChangeDetector)'.

Stack trace:

at Microsoft.EntityFrameworkCore.Query.Internal.RelationalQueryContextFactory..ctor(IStateManager stateManager, IConcurrencyDetector concurrencyDetector, IRelationalConnection connection, IChangeDetector changeDetector)
at lambda_method(Closure , ServiceProvider )
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServiceCollectionExtensions.<>c.<AddQuery>b__1_1(IServiceProvider p)\r\n   at lambda_method(Closure , ServiceProvider )
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
at Microsoft.EntityFrameworkCore.DbContext.get_QueryProvider()
at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.<.ctor>b__3_0()
at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
at Controllers.UsersController.Self(Int32 version)
```

### Further technical details

EF Core version: 1.1
Operating system: Win 10 x64
Visual Studio version: 2015 Update 3

Other details about my project setup:

project.json:

````
{
    "dependencies": {
        "Microsoft.ApplicationInsights.AspNetCore": "1.0.2",
        "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
        "SapientGuardian.EntityFrameworkCore.MySql": "7.1.14",
        "AWSSDK.Core": "3.3.5",
        "AWSSDK.SimpleEmail": "3.3.1.1",
        "AWSSDK.CognitoIdentity": "3.3.0.3",
        "AWSSDK.CognitoIdentityProvider": "3.3.2",
        "AWSSDK.Extensions.NETCore.Setup": "3.3.0.2",
        "Microsoft.AspNetCore.Authentication.JwtBearer": "1.1.0",
        "Microsoft.AspNetCore.Cors": "1.1.0",
        "Microsoft.AspNetCore.Diagnostics": "1.1.0",
        "Microsoft.AspNetCore.Mvc": "1.1.0",
        "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
        "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
        "Microsoft.EntityFrameworkCore": "1.1.0",
        "Microsoft.Extensions.Caching.Memory": "1.1.0",
        "Microsoft.Extensions.Configuration.FileExtensions": "1.1.0",
        "Microsoft.Extensions.Configuration.Json": "1.1.0",
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
        "Microsoft.Extensions.Logging.Console": "1.1.0",
        "Microsoft.Extensions.Logging.Debug": "1.1.0",
        "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
        "Microsoft.NETCore.App": "1.1.0",
        "System.IdentityModel.Tokens.Jwt": "5.1.0"
    },

    "tools": {
        "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
        "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"
    },

    "frameworks": {
        "netcoreapp1.0": {
            "imports": [
                "dotnet5.6",
                "portable-net45+win8"
            ]
        }
    },

    "runtimes": {
        "win10-x64": { }
    },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

 
  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
````

**Comment by sambernaerdt** [comment]
Similar issue here, also after upgrading to 1.1

Note: I only get the exception upon accessing the DbSet, while other methods from the DbContext still work. Example, in the following code:

```
    public class ApplicationDbContext : DbContext
    {
        public DbSet<PizzaItem> PizzaItems { get; set; }
        
        ...  (more code)
    }

    public class PizzaRepositoryMySQL : IPizzaRepository
    {
        private ApplicationDbContext _context;

        public PizzaRepositoryMySQL(ApplicationDbContext context)
        {
            _context = context;
        }

        public void Add(PizzaItem item)
        {
            // new item, create GUID
            item.Key = Guid.NewGuid().ToString();
            
            _context.Add(item);
            _context.SaveChanges();
        }

        public IEnumerable<PizzaItem> GetAll()
        {
            return _context.PizzaItems;
        }
    }

```

the method **Add** works fine, but **GetAll** results in the exception:

```
Method not found: 'Void Microsoft.EntityFrameworkCore.Query.QueryContextFactory..ctor(Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IStateManager, Microsoft.EntityFrameworkCore.Internal.IConcurrencyDetector, Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IChangeDetector)'.
```

**Comment by rowanmiller** [comment]
Based on what is in your `project.json` I think you are getting the 1.1 version of `Microsoft.EntityFrameworkCore` package, but are probably getting the 1.0 version of the `Microsoft.EntityFrameworkCore.Relational` package. Can you swap the line with `Microsoft.EntityFrameworkCore` to `Microsoft.EntityFrameworkCore.Relational` and see if that works. 

BTW there are steps about upgrading in https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-entity-framework-core-1-1/ (which includes this info).

**Comment by jeffbromberger** [comment]
@rowanmiller thanks for replying.  I added the Relational package to the project and it seems to work now.  It sounded like you were saying I should get rid of the Microsoft.EntityFrameworkCore package though.  I don't follow that part unless the .Relational package would pull it in automatically?

**Comment by rowanmiller** [comment]
Relational will pull it in, but it is also fine to list it explicitly too.

**Comment by sambernaerdt** [comment]
For anybody else having the same problem when working with MySql:

After updating to `"Microsoft.EntityFrameworkCore.Relational":"1.1.0"` it was still not working in combination with  `"MySql.Data.EntityFrameworkCore": "7.0.6-IR31"`.

However, after switching to `"SapientGuardian.EntityFrameworkCore.MySql": "7.1.14"` everything works fine again.

**Comment by asperheim** [comment]
@sambernaerdt i got this error while using the "MySql.Data.EntityFrameworkCore": "7.0.6-IR31". But my error was that i was pulling in the "Microsoft.EntityFrameworkCore.Relational":"1.1.0" or "Microsoft.EntityFrameworkCore":"1.1.0" in addition to the mysql nuget. But the "Microsoft.EntityFrameworkCore.Relational":"1.1.0" is pulled by the mysql nugget so all you have to do is to remove the "Microsoft.EntityFrameworkCore.Relational":"1.1.0" and/or "Microsoft.EntityFrameworkCore1.1.0" from your project.json and it will make your project great again.
