### ISSUE TITLE
All GearsOfWar specifiation tests fail for SQL CE

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#7149]
### Steps to reproduce
Get latest from dev feed

### The issue
All GearsOfWar tests fail due to introduction of DateTimeOffset property in the model

Stack trace:
```
est 'Microsoft.EntityFrameworkCore.Specification.Tests.GearsOfWarQuerySqlCeTest.Entity_equality_empty' failed: System.InvalidOperationException : The property 'Mission.Timeline' is of type 'DateTimeOffset' which is not supported by current database provider. Either change the property CLR type or manually configure the database type for it.
	at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyMappingValidationConvention.Apply(InternalModelBuilder modelBuilder)
	at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelBuilt(InternalModelBuilder modelBuilder)
	at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.Validate()
	at Microsoft.EntityFrameworkCore.Specification.Tests.TestModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
	at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass19_0.<GetModel>b__0(Object k)
	at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
	at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
	TestSqlCeModelSource.cs(26,0): at Microsoft.EntityFrameworkCore.Specification.Tests.TestSqlCeModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
	at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
	at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
	at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
	at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_6(IServiceProvider p)
	at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactoryService(FactoryService factoryService, ServiceProvider provider)
	at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
	at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
	at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
	at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
	at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
	at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
	at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
	at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
	at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
	at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
	at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
	at Microsoft.EntityFrameworkCore.Storage.DatabaseProviderServices.GetService[TService]()
	Storage\Internal\SqlCeDatabaseProviderServices.cs(42,0): at Microsoft.EntityFrameworkCore.Storage.Internal.SqlCeDatabaseProviderServices.get_RelationalDatabaseCreator()
	at Microsoft.EntityFrameworkCore.Infrastructure.RelationalServiceCollectionExtensions.<>c.<AddRelational>b__0_16(IServiceProvider p)
	at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactoryService(FactoryService factoryService, ServiceProvider provider)
	at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
	at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
	at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
	at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
	at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
	at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
	at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
	at Microsoft.EntityFrameworkCore.Tests.RelationalDatabaseCleaner.Clean(DatabaseFacade facade)
	SqlCeDatabaseFacadeExtensions.cs(11,0): at Microsoft.EntityFrameworkCore.Specification.Tests.SqlCeDatabaseFacadeExtensions.EnsureClean(DatabaseFacade databaseFacade)
	GearsOfWarQuerySqlCeFixture.cs(44,0): at Microsoft.EntityFrameworkCore.Specification.Tests.GearsOfWarQuerySqlCeFixture.<CreateTestStore>b__5_0()
	SqlCeTestStore.cs(60,0): at Microsoft.EntityFrameworkCore.Specification.Tests.SqlCeTestStore.<>c__DisplayClass11_0.<CreateShared>b__0()
	at Microsoft.EntityFrameworkCore.Specification.Tests.TestStore.CreateShared(String name, Action initializeDatabase)
	SqlCeTestStore.cs(55,0): at Microsoft.EntityFrameworkCore.Specification.Tests.SqlCeTestStore.CreateShared(Action initializeDatabase)
	SqlCeTestStore.cs(18,0): at Microsoft.EntityFrameworkCore.Specification.Tests.SqlCeTestStore.GetOrCreateShared(String name, Action initializeDatabase)
	GearsOfWarQuerySqlCeFixture.cs(35,0): at Microsoft.EntityFrameworkCore.Specification.Tests.GearsOfWarQuerySqlCeFixture.CreateTestStore()
	at Microsoft.EntityFrameworkCore.Specification.Tests.GearsOfWarQueryTestBase`2..ctor(TFixture fixture)
	GearsOfWarSqlCeTest.cs(11,0): at Microsoft.EntityFrameworkCore.Specification.Tests.GearsOfWarQuerySqlCeTest..ctor(GearsOfWarQuerySqlCeFixture fixture, ITestOutputHelper testOutputHelper)

0 passed, 1 failed, 0 skipped, took 1,52 seconds (xUnit.net 2.2.0 build 3444).
```
### Further technical details

EF Core version: 1.2.0-preview1-22817
EF Core provider: SQL Server Compact 4.0
Operating system: Win 10
Visual Studio version: VS 2015

**Comment by smitpatel** [comment]
The offending commit is https://github.com/aspnet/EntityFramework/commit/8b8006ed74e667a371526bfdae78b717306cebd8
Can `DateTimeOffset` be mapped to some other store type which would work without custom conversion ?

**Comment by ErikEJ** [comment]
@smitpatel Not sure what you mean? Adding support for DateTimeOffset in the SQLCE typemapper - I only have "datetime" and "nvarchar(x)" data types...

**Comment by smitpatel** [comment]
@ErikEJ - What I meant was if you set data type for `DateTimeOffset` column using `HasColumnType` to something else, would it work out of the box?
If not then you can ignore the property and disable tests which are using it.

Here is where you have to override model
https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/master/test/EntityFramework.SqlServerCompact.FunctionalTests/GearsOfWarQuerySqlCeFixture.cs#L14

**Comment by ErikEJ** [comment]
HasColumnTYpe did not work, but Ignore did, thanks!
