### ISSUE TITLE
An error occurred while calling method 'ConfigureServices' on startup class 'MyApp.Data.Startup'. Consider using IDbContextFactory to override the initialization of the DbContext at design-time. Error: The path must be absolute.

### ISSUE THREAD

**Issue by john-luke-laue** [dotnet/efcore#7175]
### Steps to reproduce
I put my DbContext in a separate project from my .NET Core MVC app. The MVC references it. 
The app works just fine and I was able to scaffold the existing database. However, when I want to run a new migration, I get the error: _An error occurred while calling method 'ConfigureServices' on startup class 'MyApp.Data.Startup'. Consider using IDbContextFactory to override the initialization of the DbContext at design-time. Error: The path must be absolute._

Startup.cs
```
public class Startup
    {
        public IConfiguration Configuration { get; set; }

        public Startup(IHostingEnvironment env)
        {
            var config = new ConfigurationBuilder().SetBasePath("../MyAppMvc");
            config.AddJsonFile("Config/config.json");
            config.AddJsonFile($"Config/config.{env.EnvironmentName}.json", true);
            config.AddEnvironmentVariables();
            Configuration = config.Build();
        }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<MyAppContext>(options =>
               options.UseSqlServer(Configuration["ConnectionStrings:MyAppDb"],
               opt => opt.UseRowNumberForPaging()));
        }
    }

```

MyAppContext.cs
```
    public partial class MyAppContext : DbContext
    {
        public MyAppContext()
        {
        }

        public MyAppContext(DbContextOptions<MyAppContext> options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
             //......
        }
    }
```

### The issue
from cmd running `dotnet ef migrations add --context MyAppContext NewMigration`

```
C:\Users\john-luke.laue\repositories\MyApp\src\MyApp.Data>dotnet ef migrations add --context MyAppContext NewMigration
Project MyApp.Data (.NETFramework,Version=v4.6.1) will be compiled because inputs were modified
Compiling MyApp.Data for .NETFramework,Version=v4.6.1
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:07.3036587

An error occurred while calling method 'ConfigureServices' on startup class 'MyApp.Data.Startup'. Consider using IDbContextFactory to override the initialization of the DbContext at design-time. Error: The path must be absolute.
Parameter name: root
System.InvalidOperationException: No database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
   at Microsoft.EntityFrameworkCore.Internal.DatabaseProviderSelector.SelectServices()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.<Initialize>b__6_0()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_DatabaseProviderServices()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_7(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.Build(DbContext context)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.OperationExecutor.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsAddCommand.Execute(CommonOptions commonOptions, String name, String outputDir, String context, String environment, Action`1 reporter)
   at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsAddCommand.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)
No database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
```

### Further technical details

project.json
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true,
    "warningsAsErrors": true
  },

  "dependencies": {
    "Microsoft.AspNetCore.Hosting.Abstractions": "1.0.0",
    "Microsoft.EntityFrameworkCore": "1.0.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0",
    "Microsoft.Extensions.Configuration": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.DependencyInjection.Abstractions": "1.0.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.0.0",
    "Microsoft.EntityFrameworkCore.Design" : "1.0.0-preview2-final"
  },

  "frameworks": {
    "net461": {}
  },

  "tools": {
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"
  }
}

```

EF Core version: Microsoft.EntityFrameworkCore 1.0.0
Operating system: Windows 10
Visual Studio version: (e.g. VS 2015

Any help would be appreciated!

**Comment by Allann** [comment]
Try 
                .SetBasePath(env.ContentRootPath)
in your Startup method.

**Comment by ajcvickers** [comment]
@john-luke-laue You may also need to remove the parameterless constructor from MyAppContext. See #6826.

**Comment by rowanmiller** [comment]
Closing as the response from @Allann covers why this is not working. If you don't want to change `Startup.cs`, then the guidance in the exception message, about adding an IDbContextFactory implementation, is the way to go.
