### ISSUE TITLE
Cannot insert explicit value for identity column error

### ISSUE THREAD

**Issue by JandosKh** [dotnet/efcore#7176]
I initialize CompanyDbContext on every request depending on the
CompanyId which is in the request cookie.

	public class CompanyDbContext : DbContext
	{
		public Company {get; set; }

		public string ConnectionString
		{
			get
			{
			    return "Server=" + this.Company.DbSvrName + 
			        ";Database=" + this.Company.DbName +         
				";Trusted_Connection=True;MultipleActiveResultSets=true";
			}
		}

		public CompanyDbContext(Company company)
		{
			this.Company = company;
		}

		protected override void OnConfiguring(DbContextOptionsBuilder options)
		{
			options.UseSqlServer(this.ConnectionString);
		}

		public DbSet<Account> Accounts { get; set; }
	}

	// Model
    [Table("Account")]
    public class Account : BaseModel
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        [StringLength(20)]
        public string Code { get; set; }

        [Required]
        [StringLength(100)]
        public string Name { get; set; }
    }

When I add a new Account, the following error has thrown:
"Cannot insert explicit value for identity column in table 'Account' when IDENTITY_INSERT is set to OFF.
The statement has been terminated."

Stack trace is below:
    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)
    at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)
    at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, TState state)
    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
    at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
    at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
    at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
    at Bizware.Data.CompanyDbContext.SeedDatabase(IHostingEnvironment env, String userId, ApplicationDbContext appDbContext) in C:\Users\abcde\Documents\Visual Studio 2015\Projects\Bizware\src\Bizware\Data\CompanyDbContext.cs:line 184
    at Bizware.Data.CompanyDbContext.CreateDatabase(ApplicationDbContext appDbContext, String userId) in C:\Users\abcde\Documents\Visual Studio 2015\Projects\Bizware\src\Bizware\Data\CompanyDbContext.cs:line 109
    at Bizware.Controllers.CompaniesController.<PostCompany>d__5.MoveNext() in C:\Users\abcde\Documents\Visual Studio 2015\Projects\Bizware\src\Bizware\Controllers\CompaniesController.cs:line 120

The database is created like below:

    companyDbContext.Database.EnsureCreated();

What am I doing wrong?
EF Core version is 1.1; VS 2015

**Comment by JandosKh** [comment]
I close the issue because the issue was related to trigger. Sorry for unnecessary posting.
