### ISSUE TITLE
LINQ statements that worked in EF Core 1.0.1 throw exceptions in EF Core 1.1.0

### ISSUE THREAD

**Issue by epgremill3** [dotnet/efcore#7198]
### Steps to reproduce
- Run project under Core 1.0.1 (key files in `.NETCore1.0.1.` sub-folder)
- Hit HTTP end point that invokes action method that executes LINQ statement
- Receive correct response (Status=200, data)
- Run project under Core 1.1.0 (key files in `.NETCore1.1.0` sub-folder)
- Hit HTTP end point that invokes action method that executes LINQ statement
- Get exception in Visual Studio

### The issue
There are several LINQ statements in our code that retrieve model objects from the database. These statements run successfully and return the correct results when run under Core 1.0.1. However, when we upgraded to Core 1.1.0 these statements throw exceptions.  

I'll attach the files for you to review (sorry I don't have time to package it into a solution you can run). I'll try to highlight the specific statements and details here.

First in `Controllers/OrdersController.cs` in the `GetAllowedStates` method, the following LINQ:  
```
var userTransitions =
    _db.BeverageTransitions
        .Include(t => t.From)
        .Include(t => t.To)
        .Where(t => t.TransitionRolesAllowed.Select(tra => tra.ApplicationRole).Intersect(appRoles).Count() > 0)
        .ToList();
```
runs successfully under Core 1.0.1; under Core 1.1.0 it throws this exception:  
```
System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=variable 'tra.ApplicationRole' of type 'SpeedyServe.Models.ApplicationRole' referenced from scope '', but it is not defined
  Source=System.Linq.Expressions
  StackTrace:
       at System.Linq.Expressions.Compiler.VariableBinder.Reference(ParameterExpression node, VariableStorageKind storage)
       at System.Linq.Expressions.Compiler.VariableBinder.VisitParameter(ParameterExpression node)
       at System.Linq.Expressions.ParameterExpression.Accept(ExpressionVisitor visitor)
       at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
       at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
       at System.Linq.Expressions.Compiler.VariableBinder.VisitLambda[T](Expression`1 node)
       at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
       at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
       at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
       at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
       at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
       at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
       at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
       at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
       at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
       at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
       at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
       at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
       at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
       at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
       at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
       at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
       at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
       at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
       at System.Linq.Expressions.Compiler.VariableBinder.VisitLambda[T](Expression`1 node)
       at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
       at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
       at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
       at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
       at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
       at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
       at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
       at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
       at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
       at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
       at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
       at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
       at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
       at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
       at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
       at System.Linq.Expressions.Compiler.VariableBinder.VisitLambda[T](Expression`1 node)
       at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
       at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
       at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
       at System.Linq.Expressions.Expression`1.Compile(Boolean preferInterpretation)
       at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateExecutorLambda[TResults]()
       at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, ILogger logger, Type contextType)
       at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileQuery>b__0()
       at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
       at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
       at Remotion.Linq.QueryableBase`1.GetEnumerator()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at SpeedyServe.Controllers.OrdersController.GetAllowedStates(ApplicationUser user) in C:\Users\egremillion\Documents\MFG\SpeedyServe\gitlab\SpeedyServe2Server\src\SpeedyServe\Controllers\OrdersController.cs:line 375
       at SpeedyServe.Controllers.OrdersController.listOrders() in C:\Users\egremillion\Documents\MFG\SpeedyServe\gitlab\SpeedyServe2Server\src\SpeedyServe\Controllers\OrdersController.cs:line 55
       at lambda_method(Closure , Object , Object[] )
       at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
  InnerException: 
```

I found that I had to add calls to `.Include(...)` and `.ThenInclude(...)` for sub-objects referenced in the `.Where(...)` clause. I also had to add a call to `.ToList()` before the `.Where(...)` clause and then the statement would run and return the correct results. The modified statement that will run successfully under Core 1.1.0:  
```
var userTransitions =
    _db.BeverageTransitions
        .Include(t => t.From)
        .Include(t => t.To)
        .Include(t => t.TransitionRolesAllowed)
            .ThenInclude(tra => tra.ApplicationRole)
        .ToList()
        .Where(t => t.TransitionRolesAllowed.Select(tra => tra.ApplicationRole).Intersect(appRoles).Count() > 0)
        .ToList();
```

I found an essentially identical issue in `OrdersController.cs` in the `GetAllowedTransitions` method...  
  
Second in `PerfTestController` in the `ZoneLocNaiveLinq` method, the following LINQ: 
```
var matchingParts =
    _db.AddressParts
        .Where(ap =>
            ap.Name.Translations.Select(xl => xl.Value).Contains(locationName, StringComparer.OrdinalIgnoreCase) &&
            ap.Types.SelectMany(tt => tt.Type.Name.Translations.Select(xl => xl.Value)).Contains("location", StringComparer.OrdinalIgnoreCase) &&
            ap.Parents.Count(ph =>
                (ph.Parent.Name.Translations.Select(t => t.Value).Contains(zoneName, StringComparer.OrdinalIgnoreCase) &&
                 ph.Parent.Types.SelectMany(pt => pt.Type.Name.Translations.Select(t => t.Value)).Contains("zone", StringComparer.OrdinalIgnoreCase)))
            > 0)
        .ToList();
```
runs successfully under Core 1.0.1; under Core 1.1.0 it throws this exception: 
```
System.ArgumentOutOfRangeException was unhandled by user code
  HResult=-2146233086
  Message=Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  ParamName=index
  Source=System.Private.CoreLib
  StackTrace:
       at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
       at System.Collections.ObjectModel.Collection`1.RemoveAt(Int32 index)
       at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.RewriteSelectManyNavigationsIntoJoins(QuerySourceReferenceExpression outerQuerySourceReferenceExpression, IEnumerable`1 navigations, AdditionalFromClause additionalFromClauseBeingProcessed)
       at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.<>c__DisplayClass20_0.<VisitMember>b__0(IEnumerable`1 ps, IQuerySource qs)
       at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindPropertyExpressionCore[TResult](Expression propertyExpression, IQuerySource querySource, Func`3 propertyBinder)
       at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindNavigationPathPropertyExpression[TResult](Expression propertyExpression, Func`3 propertyBinder)
       at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.VisitMember(MemberExpression node)
       at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
       at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
       at Remotion.Linq.Clauses.FromClauseBase.TransformExpressions(Func`2 transformation)
       at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
       at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.Rewrite(QueryModel queryModel, QueryModel parentQueryModel)
       at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
       at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
       at Remotion.Linq.Clauses.FromClauseBase.TransformExpressions(Func`2 transformation)
       at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.NavigationRewritingQueryModelVisitor.VisitAdditionalFromClause(AdditionalFromClause fromClause, QueryModel queryModel, Int32 index)
       at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
       at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
       at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.Rewrite(QueryModel queryModel, QueryModel parentQueryModel)
       at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
       at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
       at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
       at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
       at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
       at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
       at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
       at System.Linq.Expressions.MethodCallExpression.Update(Expression object, IEnumerable`1 arguments)
       at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
       at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
       at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.VisitBinary(BinaryExpression node)
       at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
       at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
       at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.VisitBinary(BinaryExpression node)
       at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
       at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
       at Remotion.Linq.Clauses.WhereClause.TransformExpressions(Func`2 transformation)
       at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.NavigationRewritingQueryModelVisitor.VisitWhereClause(WhereClause whereClause, QueryModel queryModel, Int32 index)
       at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
       at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
       at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.Rewrite(QueryModel queryModel, QueryModel parentQueryModel)
       at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel)
       at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, ILogger logger, Type contextType)
       at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileQuery>b__0()
       at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
       at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
       at Remotion.Linq.QueryableBase`1.GetEnumerator()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at SpeedyServe.Controllers.PerfTestController.ZoneLocNaiveLinq(String locationName, String zoneName) in C:\Users\egremillion\Documents\MFG\SpeedyServe\gitlab\SpeedyServe2Server\src\SpeedyServe\Controllers\PerfTestController.cs:line 369
       at lambda_method(Closure , Object , Object[] )
       at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
  InnerException: 
```

I added in all the necessary calls to `.Include(...)` and `.ThenInclude(...)` as well as a call to `.ToList()` before the call to `.Where(...)` and then the query would run without an exception and return the correct results: 
```
var matchingParts =
    _db.AddressParts
        .Include(ap => ap.Name.Translations)
        .Include(ap => ap.Types)
            .ThenInclude(pt => pt.Type)
                .ThenInclude(at => at.Name.Translations)
        .Include(ap => ap.Parents)
            .ThenInclude(ph => ph.Parent)
                .ThenInclude(pa => pa.Name.Translations)
        .Include(ap => ap.Parents)
            .ThenInclude(ph => ph.Parent)
                .ThenInclude(pa => pa.Types)
                    .ThenInclude(ty => ty.Type)
                        .ThenInclude(tz => tz.Name.Translations)
        .ToList()
        .Where(ap =>
            ap.Name.Translations.Select(xl => xl.Value).Contains(locationName, StringComparer.OrdinalIgnoreCase) &&
            ap.Types.SelectMany(tt => tt.Type.Name.Translations.Select(xl => xl.Value)).Contains("location", StringComparer.OrdinalIgnoreCase) &&
            ap.Parents.Count(ph =>
                (ph.Parent.Name.Translations.Select(t => t.Value).Contains(zoneName, StringComparer.OrdinalIgnoreCase) &&
                 ph.Parent.Types.SelectMany(pt => pt.Type.Name.Translations.Select(t => t.Value)).Contains("zone", StringComparer.OrdinalIgnoreCase)))
            > 0)
        .ToList();
```

I saw a similar issue in the `ZoneLocLinqLoadQuery2` method where I had to add in calls to `.ThenInclude(...)` to avoid an exception (this was a `NullReferenceException` however).  
  
These problems seem similar to the one mentioned above, but of course give different exceptions...  
  
I did some searching through the repository and this seems similar to #6937, #6997, and #7122...  

### Further technical details

EF Core version: 1.1.0 (project.json is included for both 1.1.0 and 1.0.1 for comparison)
Operating system: Windows 7 x64
Visual Studio version: 2015 update 3

Other details about my project setup:
- We're using Postgres (npgsql)

[Compare.NETCoreVersions.zip](https://github.com/aspnet/EntityFramework/files/637040/Compare.NETCoreVersions.zip)

**Comment by brfalcon** [comment]
@epgremill3 , I am also facing this issue. It also happens when I use navigation properties to perform a left join. Your suggestion to add a call to the "ToList()" method worked for me too. Thank for reporting.

**Comment by maumar** [comment]
closing this as we have another issue opened, investigated and described, which turned out to be the same underlying problem (https://github.com/aspnet/EntityFramework/issues/7476)
