### ISSUE TITLE
[ARM] Unable to load DLL 'sqlite3'

### ISSUE THREAD

**Issue by minimalisticMe** [dotnet/efcore#7224]
Hi,

after quite some time I started to have a look at my app again and updating some nuget packages.

On windows (x86/x64) everything runs like usual, but when connecting my win10 mobile phone (nokia 1520, build 10.0.14977.1000) I get the following error when calling the function
```
using (var db = new DBContext())
{
    db.Database.Migrate();
}
```

 *System.DllNotFoundException* with the message `Unable to load DLL 'sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)`

```
   at Microsoft.Data.Sqlite.Interop.NativeMethods.Sqlite3_sqlite3.sqlite3_open_v2(IntPtr filename, Sqlite3Handle& ppDb, Int32 flags, IntPtr vfs)
   at Microsoft.Data.Sqlite.Interop.NativeMethods.Sqlite3_sqlite3.open_v2(IntPtr filename, Sqlite3Handle& ppDb, Int32 flags, IntPtr vfs)
   at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(String filename, Sqlite3Handle& ppDb, Int32 flags, String vfs)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.Data.Sqlite.Interop.NativeMethods.OnLoad()
   at Microsoft.Data.Sqlite.Interop.NativeMethods.get_Sqlite3()
   at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(String filename, Sqlite3Handle& ppDb, Int32 flags, String vfs)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at meinStundenplanerUWP.DBData.migrateDB()
   at meinStundenplanerUWP.App.migrateDB()
   at meinStundenplanerUWP.App..ctor()
   at meinStundenplanerUWP.Program.<>c.<Main>b__0_0(ApplicationInitializationCallbackParams p)
```

Development under win10 (build 14393.447) and VS 2015.3
The project *.json*:
```
    "LiveSDK": "5.6.3",
    "Microsoft.EntityFrameworkCore.Sqlite": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2",
    "Microsoft.OneDriveSDK": "1.2.0",
    "Win2D.uwp": "1.20.0"
```

**Comment by bricelam** [comment]
Can you ensure you're using the [latest version of NuGet](https://dist.nuget.org/index.html)?

**Comment by minimalisticMe** [comment]
@bricelam I'm was using nuget packet manager v3.4.4 and updated to 3.5.0, now the project starts again.
Thank you very much!
