### ISSUE TITLE
Error: "Could not load file or assembly 'Microsoft.SqlServer.Types, Version=10.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified."

### ISSUE THREAD

**Issue by rpokrovskij** [dotnet/efcore#7239]
**Exception**: "Could not load file or assembly `Microsoft.SqlServer.Types, Version=10.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91` or one of its dependencies. The system cannot find the file specified."

**StackTrace**:

```
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)

   at System.Data.SqlClient.SqlConnection.ResolveTypeAssembly(AssemblyName asmRef, Boolean throwOnError)
   at System.Data.SqlClient.SqlConnection.<>c__DisplayClass168_0.<CheckGetExtendedUDTInfo>b__0(AssemblyName asmRef)
   at System.TypeNameParser.ResolveAssembly(String asmName, Func`2 assemblyResolver, Boolean throwOnError, StackCrawlMark& stackMark)
   at System.TypeNameParser.ConstructType(Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.TypeNameParser.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError)
   at System.Data.SqlClient.SqlConnection.CheckGetExtendedUDTInfo(SqlMetaDataPriv metaData, Boolean fThrow)
   at System.Data.SqlClient.SqlDataReader.GetValueFromSqlBufferInternal(SqlBuffer data, _SqlMetaData metaData)
   at System.Data.SqlClient.SqlDataReader.GetValues(Object[] values)

   at Microsoft.EntityFrameworkCore.Storage.Internal.UntypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, TState state)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCollectionIterator.<GetRelatedValues>d__4.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.Include(QueryContext queryContext, Object entity, IReadOnlyList`1 navigationPath, IReadOnlyList`1 relatedEntitiesLoaders, Int32 currentNavigationIndex, Boolean queryStateManager)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.Include(QueryContext queryContext, Object entity, IReadOnlyList`1 navigationPath, IReadOnlyList`1 relatedEntitiesLoaders, Boolean queryStateManager)
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_Include>d__30`1.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass20_0`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.First[TSource](IQueryable`1 source, Expression`1 predicate)
   at Vse.AdminkaV1.Injected.Test.SerializationWithRecursionTest.<>c__DisplayClass1_0.<TestDetach>b__2(IRepository`1 repository, IStorage`1 storage) in D:\cot\Vse\Tests\AdminkaV1.Injected.Test\SerializationWithRecursionTest.cs:line 34
   at Vse.AdminkaV1.DataAccessEfCore.RepositoryHandler`1.<>c__DisplayClass9_0.<Handle>b__0(AdminkaDbContext container, RoutineState`1 context, Action`1 setAudit) in D:\cot\Vse\AdminkaV1\DataAccessEfCore\RepositoryHandler.cs:line 76
   at Vse.AdminkaV1.DataAccessEfCore.AdminkaDbContextHandler.Handle(Action`3 func) in D:\cot\Vse\AdminkaV1\DataAccessEfCore\AdminkaDbContextHandler.cs:line 29
   at Vse.AdminkaV1.DataAccessEfCore.RepositoryHandler`1.Handle(Action`2 action) in D:\cot\Vse\AdminkaV1\DataAccessEfCore\RepositoryHandler.cs:line 76
   at Vse.AdminkaV1.Injected.Test.SerializationWithRecursionTest.<>c__DisplayClass1_0.<TestDetach>b__1(RoutineState`1 state, DataAccessFactory dataAccess) in D:\cot\Vse\Tests\AdminkaV1.Injected.Test\SerializationWithRecursionTest.cs:line 32
   at Vse.AdminkaV1.Injected.AdminkaRoutine.<>c__DisplayClass14_0.<Handle>b__0(RoutineState`1 state) in D:\cot\Vse\AdminkaV1\Injected\AdminkaRoutine.cs:line 201
   at Vse.Routines.Injected.Routine`1.<>c__DisplayClass5_0.<Handle>b__0() in D:\cot\Vse\Routines\Injected\Routine.cs:line 27
   at Vse.Routines.Injected.ExceptionHandler.Handle(Action action, Action onFailure) in D:\cot\Vse\Routines\Injected\ExceptionHandler.cs:line 24
```

I also have added NUGET package `Microsoft.SqlServer.Types` but this doesn't help.

**Packages:**

```
  <package id="Microsoft.EntityFrameworkCore" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.EntityFrameworkCore.Relational" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.EntityFrameworkCore.SqlServer" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Caching.Abstractions" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Caching.Memory" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.DependencyInjection" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.DependencyInjection.Abstractions" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Logging" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Logging.Abstractions" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Options" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Primitives" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.NETCore.Platforms" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.SqlServer.Types" version="10.50.1600.1" targetFramework="net461" />
  <package id="Microsoft.Win32.Primitives" version="4.3.0" targetFramework="net461" />
  <package id="NETStandard.Library" version="1.6.1" targetFramework="net461" />
  <package id="Remotion.Linq" version="2.1.1" targetFramework="net461" />
  <package id="System.AppContext" version="4.3.0" targetFramework="net461" />
  <package id="System.Collections" version="4.3.0" targetFramework="net461" />
  <package id="System.Collections.Concurrent" version="4.3.0" targetFramework="net461" />
  <package id="System.Collections.Immutable" version="1.3.0" targetFramework="net461" />
  <package id="System.ComponentModel" version="4.3.0" targetFramework="net461" />
  <package id="System.Console" version="4.3.0" targetFramework="net461" />
  <package id="System.Diagnostics.Debug" version="4.3.0" targetFramework="net461" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.3.0" targetFramework="net461" />
  <package id="System.Diagnostics.Tools" version="4.3.0" targetFramework="net461" />
  <package id="System.Diagnostics.Tracing" version="4.3.0" targetFramework="net461" />
  <package id="System.Globalization" version="4.3.0" targetFramework="net461" />
  <package id="System.Globalization.Calendars" version="4.3.0" targetFramework="net461" />
  <package id="System.Interactive.Async" version="3.0.0" targetFramework="net461" />
  <package id="System.IO" version="4.3.0" targetFramework="net461" />
  <package id="System.IO.Compression" version="4.3.0" targetFramework="net461" />
  <package id="System.IO.Compression.ZipFile" version="4.3.0" targetFramework="net461" />
  <package id="System.IO.FileSystem" version="4.3.0" targetFramework="net461" />
  <package id="System.IO.FileSystem.Primitives" version="4.3.0" targetFramework="net461" />
  <package id="System.Linq" version="4.3.0" targetFramework="net461" />
  <package id="System.Linq.Expressions" version="4.3.0" targetFramework="net461" />
  <package id="System.Linq.Queryable" version="4.0.1" targetFramework="net461" />
  <package id="System.Net.Http" version="4.3.0" targetFramework="net461" />
  <package id="System.Net.Primitives" version="4.3.0" targetFramework="net461" />
  <package id="System.Net.Sockets" version="4.3.0" targetFramework="net461" />
  <package id="System.ObjectModel" version="4.3.0" targetFramework="net461" />
  <package id="System.Reflection" version="4.3.0" targetFramework="net461" />
  <package id="System.Reflection.Extensions" version="4.3.0" targetFramework="net461" />
  <package id="System.Reflection.Primitives" version="4.3.0" targetFramework="net461" />
  <package id="System.Resources.ResourceManager" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime.Extensions" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime.Handles" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime.InteropServices" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime.Numerics" version="4.3.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.0" targetFramework="net461" />
  <package id="System.Text.Encoding" version="4.3.0" targetFramework="net461" />
  <package id="System.Text.Encoding.Extensions" version="4.3.0" targetFramework="net461" />
  <package id="System.Text.RegularExpressions" version="4.3.0" targetFramework="net461" />
  <package id="System.Threading" version="4.3.0" targetFramework="net461" />
  <package id="System.Threading.Tasks" version="4.3.0" targetFramework="net461" />
  <package id="System.Threading.Timer" version="4.3.0" targetFramework="net461" />
  <package id="System.Xml.ReaderWriter" version="4.3.0" targetFramework="net461" />
  <package id="System.Xml.XDocument" version="4.3.0" targetFramework="net461" />
```

The problem related quering class with hierarchyid field, removing `[Column(TypeName = "hierarchyid")]` and recreating db problem is "solved".

```
public class HierarchyRecord 
{
        public int HierarchyRecordId { get; set; }

        [Column(TypeName = "hierarchyid")]
        public byte[] ParentHierarchyRecordId { get; set; }

        [Required, MaxLength(LengthConstants.GoodForLongTitle)]
        public string HierarchyRecordTitle { get; set; }

        public ICollection<ParentRecordHierarchyRecord> ParentRecordHierarchyRecordMap { get; set; }

        public IReadOnlyCollection<ParentRecord> GetParentRecords()
        {
            IReadOnlyCollection<ParentRecord> @value = null;
            if (ParentRecordHierarchyRecordMap != null)
            {
                @value = ParentRecordHierarchyRecordMap.Select(e => e.ParentRecord).ToList();
            }
            return @value;
        }
}
```

**Comment by divega** [comment]
@rpokrovskij there are a few reasons that will prevent this from working. From the top:

1. EF Core does not support working with the types defined in Microsoft.SqlServer.Types, in particular with `HierarchyId`.
2. Assuming you are targeting .NET Framework, there are additional steps required to help Microsoft.SqlServer.Types locate the native dlls that It depends on. AFAIK this are detailed on a read me document on the package.
3. Assuming you are targeting .NET Core, this platform is not supported by Microsoft.SqlServer.Types and the version of the ADO.NET provider for SQL Server on .NET Core doesn't know about the types either.

**Comment by rpokrovskij** [comment]
@divega Thank you. One question: why it is not enough "packages.conf" to asssume that I'm targeting .NET Framework. (I really interesting to understand what I do not know about VS projects that for me it is clear that only csproj that targets .NET Frameworks contains packages.conf)

**Comment by divega** [comment]
@rpokrovskij re Packages.conf, you are right. I just wrote a general answer without paying too much attention to the package list.

For your second question, I was referring to Microsoft.SqlServer.Types.

**Comment by dotMorten** [comment]
This might get you a few steps closer: https://github.com/dotMorten/Microsoft.SqlServer.Types
