### ISSUE TITLE
Unable to use dotnet-ef on .Net Core 1.1 

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/efcore#7245]
After the update to .Net Core 1.1 with the latest MSBuild tooling (update 12/12) I'm unable to use the `dotnet ef` cli.

```
Exception message: System.IO.FileNotFoundException: Could not find file 'C:\dev\repos\QUBIX\QUBIX-Identity\src\QUBIX.Identity\project.json'
Stack trace: 
at System.IO.Win32FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.DotNet.ProjectModel.ProjectReader.GetProject(String projectPath, ProjectReaderSettings settings)
   at Microsoft.DotNet.ProjectModel.ProjectContext.<CreateContextForEachFramework>d__45.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at NuGet.Frameworks.FrameworkReducer.GetNearestInternal(NuGetFramework framework, IEnumerable`1 possibleFrameworks)
   at NuGet.Frameworks.FrameworkReducer.GetNearest(NuGetFramework framework, IEnumerable`1 possibleFrameworks)
   at NuGet.Frameworks.NuGetFrameworkUtility.GetNearest[T](IEnumerable`1 items, NuGetFramework framework, IFrameworkNameProvider frameworkMappings, IFrameworkCompatibilityProvider compatibilityProvider, Func`2 selector)
   at Microsoft.EntityFrameworkCore.Tools.DotNet.Internal.ProjectContextFactory.SelectCompatibleFramework(NuGetFramework target, IEnumerable`1 contexts)
   at Microsoft.EntityFrameworkCore.Tools.DotNet.Internal.ProjectContextFactory.Create(String filePath, NuGetFramework framework, String configuration, String outputDir)
   at Microsoft.EntityFrameworkCore.Tools.DotNet.Internal.DispatchOperationExecutor.Execute(CommandLineOptions options)
   at Microsoft.EntityFrameworkCore.Tools.DotNet.Program.Main(String[] args)
Could not find file 'C:\dev\repos\QUBIX\QUBIX-Identity\src\QUBIX.Identity\project.json'.
```

### Steps to reproduce
Just create a project and add the DotNet tools package for Entity framework core

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to repoduce the issue.

The project where the problem happens:

```xml
<Project ToolsVersion="15.0" Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="IdentityServer4" Version="1.0.0-rc5" />
    <PackageReference Include="IdentityServer4.EntityFramework" Version="1.0.0-rc5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.0" />
    <PackageReference Include="Microsoft.NETCore.App" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.1.0" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet">
      <Version>1.1.0-preview4-final</Version>
    </DotNetCliToolReference>
  </ItemGroup>
  <ItemGroup>
    <Content Update=".dockerignore">
      <DependentUpon>Dockerfile</DependentUpon>
    </Content>
    <Content Update="docker-compose.override.yml">
      <DependentUpon>docker-compose.yml</DependentUpon>
    </Content>
    <Content Update="docker-compose.vs.debug.yml">
      <DependentUpon>docker-compose.yml</DependentUpon>
    </Content>
    <Content Update="docker-compose.vs.release.yml">
      <DependentUpon>docker-compose.yml</DependentUpon>
    </Content>
  </ItemGroup>
</Project>
```

### Further technical details
Visual Studio 2017 RC2

.NET Command Line Tools (1.0.0-preview5-004232)

Product Information:
 Version:            1.0.0-preview5-004232
 Commit SHA-1 hash:  355b6233cb

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14986
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview5-004232

**Comment by galvesribeiro** [comment]
Nvm... Found out that CLI don't work with MSBuild projects... It was explicit on the packages changelog only in the end of some announcement blog post...

**Comment by jpiquot** [comment]
Hi,

I have the same issue...
