### ISSUE TITLE
Unable to connect to MSSql Server on Mac OS X 10.12.1

### ISSUE THREAD

**Issue by salmankhann** [dotnet/efcore#7268]
I have a connection string as follows
"mssqlDbConnectionProduction":"Server=testserver\\spd;Initial Catalog=FileRepo;User ID=xxx;Password=xxx";

When tried from the mac, I am unable to connect to the instance whenever I tried to either do a dot net ef database update or actually try to run the application. However when I tried the exact same project from a Windows 10 machine, everything runs fine (database migrations run, and the app starts normally). I also tried using a SQL Server client ('SqlPro') and it connects without any issues. Something seems to be wrong with the ef internal code when trying to connect to the server.

The error i'm getting is 
An unhandled exception was thrown by the application.
System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while establishing a connection to
t accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provid
 connection to SQL Server)

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
    at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionO
dUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandli
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, O
pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, D
y poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbCo
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions,
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTime
Connection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbC
rnal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 ret
ionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFacto
etry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction(IsolationLevel isolationLevel)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at MoFAUtility.Aids.Controllers.IGenericEvidenceControllerExtensions.HandleUpload(IGenericEvidenceController controller, I
umerable`1 allowedExtensions) in /Users/salmanhasratkhan/Documents/Projects/MOFA/FileRepo/Controllers/GenericUploadController
   at DotNetFileUploadAPI.Controllers.FileController.<Index>b__6_1(IFormFile f) in /Users/salmanhasratkhan/Documents/Projects
ine 42
   at System.Linq.Enumerable.<>c__DisplayClass151_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArr
ContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectTy
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.AspNetCore.Mvc.Formatters.Json.Internal.JsonResultExecutor.ExecuteAsync(ActionContext context, JsonResult res
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultAsync>d__30.MoveNext()
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to repoduce the issue.

### Further technical details
EF Core version: 1.0.0-preview3-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer: 1.1.0
Operating system: Mac OS X 10.12.1
IDE: Visual Studio Code

**Comment by ErikEJ** [comment]
Try to connect with hostname,ip instead of named instance name 

    10.20.30.40,1445 

or

    testserver,1445

**Comment by divega** [comment]
Closing as this is a known limitation in SqlClient in non-Windows. There is a bug in corefx tracking this.
