### ISSUE TITLE
Problem with a model (don't know how to explain it)

### ISSUE THREAD

**Issue by xrkolovos** [dotnet/efcore#7272]
```c#
class ClassA
    {
        public int Id { get; set; }
        public string RandomProp { get; set; }
        public PersonDetails PersonA { get; set; }
        public PersonDetails PersonB { get; set; }
    }

    class PersonDetails
    {
        public string FullName { get; set; }
        public string Phone { get; set; }
    }

public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            // Customize the ASP.NET Identity model and override the defaults if needed.
            // For example, you can rename the ASP.NET Identity table names and more.
            // Add your customizations after calling base.OnModelCreating(builder);
        }

        public DbSet<ClassA> ClassAs { get; set; }
    }
```

This design was working in ef6. It created a Table that had it all in. Now i get this error
Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:  The entity type 'WebApplication2.Models.PersonDetails' requires a primary key to be defined.
Stack trace:
System.InvalidOperationException: The entity type 'WebApplication2.Models.PersonDetails' requires a primary key to be defined.    at Microsoft.EntityFrameworkCore.Internal.ModelValidator.ShowError(String message)
    at Microsoft.EntityFrameworkCore.Internal.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.RelationalModelValidator.Validate(IModel model)
    at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory) 
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel() 
    at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value() 
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider) 
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider) 
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider) 
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
    at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsAddCommand.Execute(CommonOptions commonOptions, String name, String outputDir, String context, String environment, Action`1 reporter) 
   at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsAddCommand.<>c__DisplayClass0_0.<Configure>b__0()
    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args) 
   at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)
 The entity type 'WebApplication2.Models.PersonDetails' requires a primary key to be defined. 
```

### Steps to reproduce
Create a new project and create this model

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: win10
IDE: Visual Studio 2015

**Comment by ajcvickers** [comment]
@xrkolovos Most likely PersonDetails was mapped as a complex type in EF6. Complex types are not supported in EF Core so PersonDetails will need to be given a key of some sort. You could consider giving it a key in shadow state, but even then the mapping would be different from EF6. I would suggest reading through the thread on issue #246. 

I'm going to close this a a duplicate, but if a complex type is not what you were expecting then feel free to re-open with more details on what is wrong and how to repro.
