### ISSUE TITLE
Inserting data: FK set to zero instead of null

### ISSUE THREAD

**Issue by HappyNomad** [dotnet/efcore#7305]
When translating the model into the relational database schema, the required FKs are correctly translated into nullable FKs.  When inserting data, however, the FK is set to zero instead of null.

	public class BloggingContext : DbContext
	{
		public BloggingContext( DbContextOptions<BloggingContext> options )
			: base( options ) { }

		public DbSet<L> Ls { get; set; }
		public DbSet<AL> ALs { get; set; }

		protected override void OnModelCreating( ModelBuilder modelBuilder )
		{
			// Add known types to the model.
			modelBuilder.Entity<P>();
			modelBuilder.Entity<Q>();

			// Enable cascade delete.
			foreach ( var partProperty in ( //search for parts
				from e in modelBuilder.Model.GetEntityTypes()
				from p in e.GetNavigations()
				select p
			).ToList() ) { //for each match, set up relationship
				bool isCollection = partProperty.IsCollection();
				Type principleType = partProperty.DeclaringType.ClrType, dependentType = partProperty.ClrType;
				if ( isCollection ) dependentType = dependentType.GetGenericArguments().Single();
				string foreignKey = partProperty.Name + principleType.Name + "Id";

				// Mark both one-to-one and one-to-many relationships as required.
				modelBuilder.Entity( dependentType ).Property<int>( foreignKey );

				// Use descriptive foreign key names.
				if ( isCollection ) modelBuilder.Entity( principleType )
					.HasMany( dependentType, partProperty.Name )
					.WithOne()
					.HasForeignKey( foreignKey )
					.OnDelete( DeleteBehavior.Restrict ); //TODO: overcome SQL Server's cascade paths limitation and remove this line
				else modelBuilder.Entity( principleType )
					// Correct the principle/dependent roles of one-to-one relationships.
					.HasOne( dependentType, partProperty.Name )
					.WithOne()
					.HasForeignKey( dependentType, foreignKey )
					.OnDelete( DeleteBehavior.Restrict ); //TODO: overcome SQL Server's cascade paths limitation and remove this line
			}
		}

		internal async void UseDatabase()
		{
			Database.EnsureDeleted();
			Database.EnsureCreated();

			// Add seed data.
			var ls = new L {
				PGs = new List<PG>(),
				Ts = new List<T>()
			};
			for ( int i = 0; i < 2; i++ )
				ls.PGs.Add( new PG() );
			for ( int i = 0; i < 3; i++ )
				ls.Ts.Add( new T { P1 = new Q() } );
			Ls.Add( ls );
			for ( int i = 0; i < 12; i++ )
				ALs.Add( new AL { L = new P() } );
			await SaveChangesAsync();
		}
	}

	public class L
	{
		public int Id { get; set; }
		public IList<PG> PGs { get; set; }
		public IList<T> Ts { get; set; }
	}

	public class AL
	{
		public int Id { get; set; }
		public PBase L { get; set; }
	}

	public class PG
	{
		public int Id { get; set; }
	}

	public class T : P
	{
		public Q P1 { get; set; }
		public P P2 { get; set; }
	}

	public class P : PBase
	{
	}

	public class Q : PBase
	{
	}

	public abstract class PBase
	{
		public int Id { get; set; }
	}

The exception thrown by `1.2.0-preview1-22878` says:

	Microsoft.EntityFrameworkCore.DbUpdateException was unhandled by user code
	  HResult=-2146233088
	  Message=An error occurred while updating the entries. See the inner exception for details.
	  Source=Microsoft.EntityFrameworkCore.Relational
	  StackTrace:
	       at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__32.MoveNext()
	    --- End of stack trace from previous location where exception was thrown ---
	       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
	       at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__10.MoveNext()
	    --- End of stack trace from previous location where exception was thrown ---
	       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	       at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__6`2.MoveNext()
	    --- End of stack trace from previous location where exception was thrown ---
	       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	       at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__55.MoveNext()
	    --- End of stack trace from previous location where exception was thrown ---
	       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	       at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__53.MoveNext()
	    --- End of stack trace from previous location where exception was thrown ---
	       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	       at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__34.MoveNext()
	    --- End of stack trace from previous location where exception was thrown ---
	       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	       at EFGetStarted.AspNetCore.NewDb.Models.BloggingContext.<UseDatabase>d__10.MoveNext() in C:\Users\Adrian\Development\Examples\ASP.NET Core\EFGetStarted.AspNetCore.NewDb\src\EFGetStarted.AspNetCore.NewDb\Models\Model.cs:line 70
	  InnerException: 
	       Class=14
	       HResult=-2146232060
	       LineNumber=17
	       Message=Cannot insert duplicate key row in object 'dbo.PBase' with unique index 'IX_PBase_P2TId'. The duplicate key value is (0).
	The statement has been terminated.
	       Number=2601
	       Procedure=""
	       Server=(localdb)\mssqllocaldb
	       Source=Core .Net SqlClient Data Provider
	       State=1
	       StackTrace:
	            at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__107_0(Task`1 result)
	            at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
	            at System.Threading.Tasks.Task.Execute()
	         --- End of stack trace from previous location where exception was thrown ---
	            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	            at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__26.MoveNext()
	         --- End of stack trace from previous location where exception was thrown ---
	            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	            at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__32.MoveNext()
	       InnerException: 

Reduce a `for` loop's iterations in the seed data to produce this exception instead:

	Microsoft.EntityFrameworkCore.DbUpdateException was unhandled by user code
	  HResult=-2146233088
	  Message=An error occurred while updating the entries. See the inner exception for details.
	  Source=Microsoft.EntityFrameworkCore.Relational
	  StackTrace:
	       at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__32.MoveNext()
	    --- End of stack trace from previous location where exception was thrown ---
	       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
	       at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__10.MoveNext()
	    --- End of stack trace from previous location where exception was thrown ---
	       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	       at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__6`2.MoveNext()
	    --- End of stack trace from previous location where exception was thrown ---
	       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	       at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__55.MoveNext()
	    --- End of stack trace from previous location where exception was thrown ---
	       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	       at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__53.MoveNext()
	    --- End of stack trace from previous location where exception was thrown ---
	       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	       at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__34.MoveNext()
	    --- End of stack trace from previous location where exception was thrown ---
	       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	       at EFGetStarted.AspNetCore.NewDb.Models.BloggingContext.<UseDatabase>d__10.MoveNext() in C:\Users\Adrian\Development\Examples\ASP.NET Core\EFGetStarted.AspNetCore.NewDb\src\EFGetStarted.AspNetCore.NewDb\Models\Model.cs:line 70
	  InnerException: 
	       Class=16
	       HResult=-2146232060
	       LineNumber=9
	       Message=The MERGE statement conflicted with the FOREIGN KEY constraint "FK_PBase_ALs_LALId". The conflict occurred in database "EFGetStarted.AspNetCore.NewDb", table "dbo.ALs", column 'Id'.
	The statement has been terminated.
	       Number=547
	       Procedure=""
	       Server=(localdb)\mssqllocaldb
	       Source=Core .Net SqlClient Data Provider
	       State=0
	       StackTrace:
	            at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__107_0(Task`1 result)
	            at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
	            at System.Threading.Tasks.Task.Execute()
	         --- End of stack trace from previous location where exception was thrown ---
	            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	            at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__26.MoveNext()
	         --- End of stack trace from previous location where exception was thrown ---
	            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	            at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__32.MoveNext()
	       InnerException:

**Comment by ajcvickers** [comment]
@HappyNomad It looks like this line:
```C#
modelBuilder.Entity( dependentType ).Property<int>( foreignKey );
```
is making all the foreign key properties non-nullable. This makes the relationship required, which in turn means that every dependent entity must reference some principal entity, which means that null is never a valid value for the FK.

Could you explain more what you expect to happen with this model?

**Comment by HappyNomad** [comment]
@ajcvickers As I understand, that line makes it required in the model but not necessarily in the relational database due to TPH mapping.  In the relational database, `null` _is_ a valid value for a FK that is not applicable.

As for what I expect with this model, firstly I expect it to not throw an exception.  Secondly, I expect it to insert null for the inapplicable FK.

**Comment by ajcvickers** [comment]
@HappyNomad Ah, I see what you are saying now. Will leave to @AndriySvyryd to investigate/comment any further.

**Comment by AndriySvyryd** [comment]
@HappyNomad I agree with @ajcvickers here. `P2TId` is required on `P`, so when you are inserting `P` instances that don't have an associated `T` instance `P2TId` will have the CLR default value for `int`.

**Comment by jnm2** [comment]
If the FK is only defined on a certain subtype, zero should be inserted if the discriminator points to that subtype and null should be inserted for any other discriminator.

**Comment by HappyNomad** [comment]
I was incorrectly interpreting aggregation to mean that the foreign key is required.  That's usually true but not always.  An entity type may have multiple parents even though an instance of it has exactly one parent.  The correct interpretation is to turn on cascade delete alone.
