### ISSUE TITLE
Migrations fails when changes property type from DateTime -> int

### ISSUE THREAD

**Issue by daviatorstorm** [dotnet/efcore#7306]
Describe what is not working as expected.

Migrations fails when changes property type from DateTime -> int

```
Exception message:
Stack trace:
dotnet : Npgsql.PostgresException: 42804: column "SomeProperty" cannot be cast automatically to type integer
At line:1 char:1
+ dotnet ef database update
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Npgsql.Postgres...to type integer:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at Npgsql.NpgsqlConnector.DoReadMessage(DataRowLoadingMode dataRowLoadingMode, Boolean isPrependedMessage)
   at Npgsql.NpgsqlConnector.ReadMessageWithPrepended(DataRowLoadingMode dataRowLoadingMode)

   at Npgsql.NpgsqlDataReader.NextResultInternal()
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.Execute(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteNonQueryInternal()

   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)

   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)

   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)

   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)

   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)

   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Steps to reproduce
Change property type from DateTime -> int

dotnet ef migrations add SomeMigration
Success!
dotnet ef database update
Fails

```c#
<code listing>
```

### Further technical details
EF Core version: 1.1
"Npgsql.EntityFrameworkCore.PostgreSQL.Design": "1.1.0-preview1-final",
 "Npgsql.EntityFrameworkCore.PostgreSQL": "1.1.0-preview1-final",
"LCHAIM.Model": "1.0.0-*",
"Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
"Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final",
"Microsoft.Extensions.DependencyModel": "1.1.0",
Operating system: 
IDE: Visual Studio 2015

**Comment by divega** [comment]
@daviatorstorm could you elaborate on what your expectation is?

**Comment by daviatorstorm** [comment]
Sure. When creating such migration show warning like "You can lose your data when doing database update at 'TableName.ColumnName[CurrentColumnType]'". Then on update database command remove integer table column and add date time table column.

**Comment by rowanmiller** [comment]
This is something that would need to be manually edited once the migration is scaffolded. We walk a fine line between trying to scaffold something that works, but not making the product too complex. What data conversions are supported is a provider specific thing, so we don't really want to go down this route.
