### ISSUE TITLE
Invalid character in path running dotnet ef

### ISSUE THREAD

**Issue by veb128** [dotnet/efcore#7339]
After installing Visual Studio 2017 RC running the command 'dotnet ef' results in an error of:

Illegal characters in path.
Parameter name: path

I don't know what path it is referring to or how to correct it.

**Comment by bricelam** [comment]
Does specifying `--verbose` provide any additional context?

**Comment by veb128** [comment]
Well, that got me some more information but I'm still not clear as to what path it is referring to as having an illegal character.

Telemetry is: Enabled
projetfactory: MSBUILD_EXE_PATH = C:\Program Files\dotnet\sdk\1.0.0-preview4-004
233\MSBuild.dll
projetfactory: MSBuild project path = C:\Users\vbrown\Documents\Visual Studio 20
15\Projects\dotnetcore\ORCCore.SQLite\Core2ORCC.csproj
projecttoolscommandresolver: resolving commandspec from 0 Tool Libraries.
projecttoolscommandresolver: failed to resolve commandspec from library.
System.ArgumentException: Illegal characters in path.
Parameter name: path
   at System.IO.PathInternal.CheckInvalidPathChars(String path)
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.DotNet.Cli.Utils.EnvironmentProvider.<>c__DisplayClass7_0.<GetCo
mmandPath>b__2(String p, String s)
   at System.Linq.Enumerable.<JoinIterator>d__78`4.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`
2 predicate)
   at Microsoft.DotNet.Cli.Utils.EnvironmentProvider.GetCommandPath(String comma
ndName, String[] extensions)
   at Microsoft.DotNet.Cli.Utils.PathCommandResolver.ResolveCommandPath(CommandR
esolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.AbstractPathBasedCommandResolver.Resolve(Comman
dResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CompositeCommandResolver.Resolve(CommandResolve
rArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CommandResolver.TryResolveCommandSpec(ICommandR
esolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuG
etFramework framework, String configuration, String outputPath, String applicati
onName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(ICommandResolverPolicy commandRe
solverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework,
String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`
1 args, NuGetFramework framework, String configuration, String outputPath, Strin
g applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemet
ryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

**Comment by bricelam** [comment]
From the stack trace, this looks like a bug for the [dotnet/cli](https://github.com/dotnet/cli) repo. Could you  [submit a new issue](https://github.com/dotnet/cli/issues/new) there so they can follow up?

**Comment by divega** [comment]
This issue was moved to dotnet/cli#5317
