### ISSUE TITLE
Validation errors for non existing entities

### ISSUE THREAD

**Issue by olee** [dotnet/efcore#7403]
Hi
I recently added a second small DbContext to my application to access just one simple entity from a database.
However when I try to use the DbContext, I get this exception:
````
One or more validation errors were detected during model generation:

C3.Dialog.Core.Database.UserLogin: : EntityType 'UserLogin' has no key defined. Define the key for this EntityType.
C3.Dialog.Core.Database.UserRole: : EntityType 'UserRole' has no key defined. Define the key for this EntityType.
UserLogins: EntityType: EntitySet 'UserLogins' is based on type 'UserLogin' that has no keys defined.
UserRoles: EntityType: EntitySet 'UserRoles' is based on type 'UserRole' that has no keys defined.
````
(relevant part of the stacktrace)
````
   at System.Data.Entity.Core.Metadata.Edm.EdmModel.Validate()
   at System.Data.Entity.DbModelBuilder.Build(DbProviderManifest providerManifest, DbProviderInfo providerInfo)
   at System.Data.Entity.DbModelBuilder.Build(DbConnection providerConnection)
   at System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext)
   at System.Data.Entity.Internal.RetryLazy`2.GetValue(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   at System.Data.Entity.Internal.InternalContext.ForceOSpaceLoadingForKnownEntityTypes()
````

This however does not make sense, because the DbContext I'm trying to initiate has only **one** entity (`Channel`) and the two entities mentioned there - `C3.Dialog.Core.Database.UserRole` and `C3.Dialog.Core.Database.UserLogin` **do not even exist**.

Instead in my first context there exist those two classes as `C3.Data.Domain.Entities.Identity.UserLogin` and `C3.Data.Domain.Entities.Identity.UserRole`.

I should note, that both DbContext reference the same database, however only the second one is created (it's in a separate program using the same code base which just needs access to that one entity)

I think this might be a bug.
Can anyone help me with this?

**EDIT**: When I remove the single DbSet declaration in my context (make it empty) the context can be created.
Also I want to note that that entity has only primitive values and no foreign keys or something like that.

**Comment by olee** [comment]
Sorry - I found the problem - the entity extended a base class and that one had a leftover foreign key.
