### ISSUE TITLE
Include() method returns only first entry

### ISSUE THREAD

**Issue by irwangunardi** [dotnet/efcore#7414]
### Steps to reproduce
While I am making web api, I found out if I use .Include(), it only returns the first blog entry

```c#
public IEnumerable<Blog> Get()
{
    var blogs = _context.Blogs
    .Include(b => b.Posts)
    .ToList();

    return blogs;
}
```
and that first blog entry is correct by showing all its posts. But the rest blogs are missing.

I tried removing the Include() part, it returning all the blogs as expected.

### Stack trace
```
info: Microsoft.EntityFrameworkCore.Storage.IRelationalCommandBuilderFactory[1]
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT "b"."BlogId", "b"."Url"
      FROM "Blogs" AS "b"
      ORDER BY "b"."BlogId"

info: Microsoft.EntityFrameworkCore.Storage.IRelationalCommandBuilderFactory[1]
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT "p"."PostId", "p"."BlogId", "p"."Content", "p"."Title"
      FROM "Posts" AS "p"
      WHERE EXISTS (
          SELECT 1
          FROM "Blogs" AS "b"
          WHERE "p"."BlogId" = "b"."BlogId")
      ORDER BY "p"."BlogId"
```
```
Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'blog' with type 'BlogWebAPI.Models.Blog'. Path '[0].posts[0]'.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
```

Exception occurred was self referencing loop. My Blog have list of Posts, and my Post have navigation property Blog. So it is a common scenario to have self referencing loop isn't it, so I don't believe it have something to do with this issue

I dont think it is SQLite limitations as it is not in the document.
Any help would be appreciated.

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SQLite

**Comment by ShiningBomb** [comment]
Edited to provide more clear information.

**Comment by MontyGvMC** [comment]
Which setting do you have in your Startup.cs?

```
 public void ConfigureServices(IServiceCollection services)
        {
          // other stuff

            services.AddMvc()
                .AddJsonOptions(
                    // Ignore: will not serialize an object if it is a child object of itself
                    options => options.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
                );

         // other stuff
        }
```

**Comment by ShiningBomb** [comment]
It works! Didn't expected it would require additional options. Would be helpful if it mentioned in the docs, provided it is a common scenario.

**Comment by ajcvickers** [comment]
Reopening to discuss if there is anywhere we might be able to put a doc note for this. It isn't an EF issue at all, but people keep hitting it with MVC and Json serialization.

**Comment by rowanmiller** [comment]
We'll add a note to https://docs.microsoft.com/en-us/ef/core/querying/related-data

**Comment by rowanmiller** [comment]
PR is out to add this to the docs - https://github.com/aspnet/EntityFramework.Docs/pull/333. Closing as docs are maintained in a different repo.
