### ISSUE TITLE
EF Core 1.1 - Failed to add migrations in .net core console app

### ISSUE THREAD

**Issue by stg609** [dotnet/efcore#7454]
I have asked a question in [SO](http://stackoverflow.com/questions/41789794/ef-core-1-1-how-to-add-migrations-in-net-core-console), but didn't get enough responses. So I'm trying to ask the same question here again.
There're two projects in my solution as below:

- **Sample.UI**: a dotnet core console project created by "dotnet new".
- **Sample.Infrastruction**: a dotnet core library created by "dotnet new -t lib", the BlogDbContext is right there.

When I try to run the `dotnet ef --startup-project ..\sample.ui  migrations add InitialDB` in the **Sample.Infrastructure** folder, it raised an error:

```
Error Message:
No database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.On
Configuring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext

Stack:
at Microsoft.EntityFrameworkCore.Internal.DatabaseProviderSelector.SelectServices() 
at Microsoft.EntityFrameworkCore.Internal.LazyRef1.get_Value()
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Vis itScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.b__0(ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.Build(DbContext context)
at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.b__0()
at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```
I have tried to add **AddDbContext** to fix the issue, but didn't work for me. Maybe I'm not using the built-in DI correctly. I have googled a lot, but most solutions are used for asp.net core rather then console app.

### Steps to reproduce
Below is the **Sample.Infrastructure** source code:

```c#
namespace Sample.Infrastructure
{
    public class BlogDbContext : DbContext
    {
        public BlogDbContext(DbContextOptions<BlogDbContext> options)
            : base(options)
        {

        }

        public BlogDbContext()
        {
             //ATT: I also don't understand why ef requires the parameterless constructor
        }

        public DbSet<Blog> Blogs { get; set; }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.Entity<Blog>().HasKey(post => post.Identity);
            base.OnModelCreating(builder);
        }
    }
}
```
**Sample.UI** source code:
```
namespace Sample.UI
{
    public class Program
    {
        static public IConfigurationRoot Configuration { get; set; }
        private static IServiceProvider _serviceProvider;

        public static void Main(string[] args)
        {
            var builder = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true);
            Configuration = builder.Build();

            //setup DI
            _serviceProvider = new ServiceCollection()
                .AddDbContext<BlogDbContext>(o=> o.UseSqlite(Configuration["ConnectionString"]))
                .BuildServiceProvider();

            // PostApplicationService app = new PostApplicationService();
            // var ctx = _serviceProvider.GetService(typeof(BlogDbContext)) as BlogDbContext;   
            // app.Inital(ctx);

            Console.ReadLine();
        }
    }
}
```

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Win 7 x64
IDE: Visual Studio Code

**Comment by bricelam** [comment]
The `AddDbContext` call must be inside `Startup.ConfigureServices()` for the tools to pick it up.

If this is not an ASP.NET Core application, you should add a type to your project that implements `IDbContextFactory<BlogDbContext>`. The tools will use this to create instances of the `DbContext`.

**Comment by stg609** [comment]
Thanks very much!
