### ISSUE TITLE
Exception is thrown when running two queries in parallel using two DIFFERENT DbContexts

### ISSUE THREAD

**Issue by gdoron** [dotnet/efcore#7467]
I've an EF 1.1 application which runs into troubles in a specific method where we are running two queries in parallel.
Since EF is not thread safe, we configured it to have `transient` life time in Startup.cs

	services.AddDbContext<AltoDbContext>(options =>
	{
		options.UseSqlServer(Configuration.GetConnectionString("Sql"),
			b => b.MigrationsAssembly("Alto.Web")).ConfigureWarnings(x => x.Log());
	}, ServiceLifetime.Transient);

For 30% of the requests we get an exception: 

> System.InvalidOperationException: An attempt was made to use the context while it is being configured.

So obviously we have a race condition, but the question is what are we doing wrong?
Maybe we are missing the obvious, but since we get a different context for each thread, shouldn't it be enough?

I had an EF 1.0 application a while back and had something very similar to this and had no problems when we configured the DbContext to be transient.

```
System.InvalidOperationException: An attempt was made to use the context while it is being configured. A DbContext instance cannot be used inside OnConfiguring since it is still being configured at this point.
   at Microsoft.EntityFrameworkCore.DbContext.InitializeServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.DbContext.get_QueryProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.<.ctor>b__3_0()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Expression()
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.VisitMember(MemberExpression memberExpression)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.VisitUnary(UnaryExpression unaryExpression)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.ExtractParameters(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExtractParameters(Expression query, QueryContext queryContext)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__129`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Alto.Logic.Upload.HomeLogic.<>c__DisplayClass4_1.<<GetModelAsync>b__0>d.MoveNext() in xxxxxxxxxxxxxxxxxxxxxxx.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Alto.Logic.Upload.HomeLogic.<GetModelAsync>d__4.MoveNext() in xxxxxxxxxxxxxxxxxxline 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Alto.Web.Controllers.HomeController.<Index>d__4.MoveNext() in xxxxxxxxxxxxxxxxxline 238
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

### Steps to reproduce
```c#

public async Task<HomeModel> GetModelAsync()
{
	const int itemsInStrip = 10;
	List<ProductCardModel> recommendedProductsCards = null;
	List<ProductCardModel> newProductsCards = null;

	List<BenefitCardModel> recommendedBenefitsCards = null;
	List<BenefitCardModel> newBenefitsCards = null;
	var productsTask = Task.Run(async () =>
	{
		using (var productsContext = _serviceProvider.GetService<AltoDbContext>())
		{
			var recommendedProducts = await productsContext.Products
				.Where(x => x.DeleteDate == null && x.IsPublished &&
							_context.PromotedProducts.Any(pp => pp.PromotionType == PromotionType.Recommended && pp.ProductId == x.Id))
				.Include(x => x.Images)
				.AsNoTracking()
				.Take(itemsInStrip)
				.ToListAsync();

			var alreadyfetchedIds = recommendedProducts.Select(x => x.Id).ToList();
			if (alreadyfetchedIds.Count != itemsInStrip)
			{
				var randomProducts = await productsContext.Products
					.Where(x => x.DeleteDate == null && x.IsPublished &&
								!alreadyfetchedIds.Contains(x.Id))
					.Include(x => x.Images)
					.AsNoTracking()
					.Take(itemsInStrip - alreadyfetchedIds.Count)
					.ToListAsync();
				recommendedProducts.AddRange(randomProducts);
			}

			recommendedProductsCards = _mapper.Map<List<ProductCardModel>>(recommendedProducts);
			alreadyfetchedIds = recommendedProductsCards.Select(x => x.Id).ToList();

			var newProducts = await productsContext.Products
				.Where(x => x.DeleteDate == null && x.IsPublished &&
							_context.PromotedProducts.Any(pp => pp.PromotionType == PromotionType.New && pp.ProductId == x.Id) &&
							!alreadyfetchedIds.Contains(x.Id))
				.Include(x => x.Images)
				.AsNoTracking()
				.Take(itemsInStrip)
				.ToListAsync();

			if (newProducts.Count != itemsInStrip)
			{
				alreadyfetchedIds.AddRange(newProducts.Select(x => x.Id));

				var randomProducts = await productsContext.Products
					.Where(x => x.DeleteDate == null && x.IsPublished &&
								!alreadyfetchedIds.Contains(x.Id))
					.Include(x => x.Images)
					.AsNoTracking()
					.OrderByDescending(x => x.InsertDate)
					.Take(itemsInStrip)
					.ToListAsync();
				newProducts.AddRange(randomProducts);
			}
			newProductsCards = _mapper.Map<List<ProductCardModel>>(newProducts);
		}
	});

	var benefitsTask = Task.Run(async () =>
	{
		using (var benefitsContext = _serviceProvider.GetService<AltoDbContext>())
		{
			var recommendeBenefits = await benefitsContext.Benefits
				.Where(x => x.DeleteDate == null && x.IsPublished &&
							_context.PromotedBenefits.Any(pb => pb.PromotionType == PromotionType.Recommended && pb.BenefitId == x.Id))
				.Include(x => x.Images)
				.AsNoTracking()
				.Take(itemsInStrip)
				.ToListAsync();
			var alreadyfetchedIds = recommendeBenefits.Select(x => x.Id).ToList();
			if (alreadyfetchedIds.Count != itemsInStrip)
			{
				var randomBenefits = await benefitsContext.Benefits
					.Where(x => x.DeleteDate == null && x.IsPublished && !alreadyfetchedIds.Contains(x.Id))
					.Include(x => x.Images)
					.AsNoTracking()
					.Take(itemsInStrip - alreadyfetchedIds.Count)
					.ToListAsync();
				recommendeBenefits.AddRange(randomBenefits);
			}

			recommendedBenefitsCards = _mapper.Map<List<BenefitCardModel>>(recommendeBenefits);
			alreadyfetchedIds = recommendedBenefitsCards.Select(x => x.Id).ToList();

			var newBenefits = await benefitsContext.Benefits
				.Where(
					x =>
						x.DeleteDate == null && x.IsPublished &&
						_context.PromotedBenefits.Any(pp => pp.PromotionType == PromotionType.New && pp.BenefitId == x.Id)
						&& !alreadyfetchedIds.Contains(x.Id))
				.Include(x => x.Images)
				.AsNoTracking()
				.Take(itemsInStrip)
				.ToListAsync();

			if (newBenefits.Count != itemsInStrip)
			{
				alreadyfetchedIds.AddRange(newBenefits.Select(x => x.Id));

				var randomBenefits = await benefitsContext.Benefits
					.Where(x => x.DeleteDate == null && x.IsPublished && !alreadyfetchedIds.Contains(x.Id))
					.Include(x => x.Images)
					.AsNoTracking()
					.OrderByDescending(x => x.InsertDate)
					.Take(itemsInStrip)
					.ToListAsync();
				newBenefits.AddRange(randomBenefits);
			}

			newBenefitsCards = _mapper.Map<List<BenefitCardModel>>(newBenefits);
		}
	});

	await Task.WhenAll(productsTask, benefitsTask);
```

Sometimes the exception is thrown from this line:

	var recommendeBenefits = await benefitsContext.Benefits ....
And sometimes it's from this line:

	var recommendedProducts = await productsContext.Products
	
### Further technical details
EF Core version: 1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE:  Visual Studio 2015

**Comment by ajcvickers** [comment]
@gdoron What is `_context` set to?

**Comment by gdoron** [comment]
@ajcvickers OMG. that's a DbContext, injected by DI (shared between the threads), I've no idea how I missed it! I think R# marked the _context as not in use (gray) so I overlooked it. 😢 

	for (var i = 0; i < 10000; i++)
	{
		Console.WriteLine("I'm an idiot and I'll stop bothering the EF team with my stupid bugs");
	}
Thanks Arthur and I'm truly sorry for wasting your time on this!
