### ISSUE TITLE
Unable to cast object of type 'System.Int32' to type 'System.Int64'.

### ISSUE THREAD

**Issue by jonghshin** [dotnet/efcore#7558]
DB first entity framework core throws this exception when SaveChanges();

```
Exception message: Unable to cast object of type 'System.Int32' to type 'System.Int64'.
Stack trace:
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(DbDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Catssie.Admin.Controllers.HomeController.<CreateNewProductByExpenseDetailItem>d__10.MoveNext()
```

```c#
CsProduct csProduct = new CsProduct()
{
    CheapestPrice = 1,
    LastPrice = 1,
    LastUpdateDate = DateTime.Now,
    ProductName = "123",
    Quantity = 1,
    UploadDate = DateTime.Now
};
csRepository.CSContext.Entry(csProduct).State = EntityState.Added;
csRepository.CSContext.SaveChanges();       

------------------------------------------------------------------ 
CsProduct.cs
public partial class CsProduct
    {
        public CsProduct()
        {
            CsExpenseDetailItem = new HashSet<CsExpenseDetailItem>();
            CsProductFile = new HashSet<CsProductFile>();
        }

        public long ProductNo { get; set; }
        public string ProductName { get; set; }
        public decimal CheapestPrice { get; set; }
        public decimal LastPrice { get; set; }
        public int Quantity { get; set; }
        public DateTime UploadDate { get; set; }
        public DateTime LastUpdateDate { get; set; }
        public string Comment { get; set; }

        public virtual ICollection<CsExpenseDetailItem> CsExpenseDetailItem { get; set; }
        public virtual ICollection<CsProductFile> CsProductFile { get; set; }
    }
------------------------------------------------------------------------------
DDL
CREATE TABLE CS_Product(
	productNo				bigint				IDENTITY(1,1)	NOT NULL,
	productName				nvarchar(256) 					NOT NULL,
	cheapestPrice				decimal(14,2)					NOT NULL,
	lastPrice					decimal(14,2)					NOT NULL,
	quantity					int							NOT NULL,
	uploadDate				datetime						NOT NULL,
	lastUpdateDate			datetime						NOT NULL,
	comment					nvarchar(450)							,
	CONSTRAINT PK_CS_Product PRIMARY KEY (productNo),
);
```

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2015

**Comment by jonghshin** [comment]
t was my mistake.. When I first created the table, productNo was bigint and I created the model based on that table. After that somehow (it must be me...) productNo changed to int. It is working just fine after changing productNo back to bigint
