### ISSUE TITLE
Migration tries to create sequence that already exists

### ISSUE THREAD

**Issue by aggieben** [dotnet/efcore#7593]
I recently updated my tooling to 1.0.0-msbuild3-final, and I also updated all of my EF packages to 1.1.0.  I also added two properties to an entity class, and then used `dotnet ef migrations add` to create the new migration.

When I run `dotnet ef database update`, it correctly selects the new migration to run, but then fails on a command that I don't quite understand.  Here's the migration code itself:

```
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_AspNetUserRoles_UserId",
                table: "AspNetUserRoles");

            migrationBuilder.DropIndex(
                name: "RoleNameIndex",
                table: "AspNetRoles");

            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "TenantClients",
                nullable: false,
                oldClrType: typeof(int))
                .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "Tenants",
                nullable: false,
                oldClrType: typeof(int))
                .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

            migrationBuilder.AddColumn<int>(
                name: "SignupStatus",
                table: "AspNetUsers",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<Guid>(
                name: "SignupToken",
                table: "AspNetUsers",
                nullable: true);

            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "AspNetUserClaims",
                nullable: false,
                oldClrType: typeof(int))
                .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "AspNetRoleClaims",
                nullable: false,
                oldClrType: typeof(int))
                .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

            migrationBuilder.CreateIndex(
                name: "RoleNameIndex",
                table: "AspNetRoles",
                column: "NormalizedName",
                unique: true);
        }
```

The third block, `migrationBuilder.AlterColumn<int>(name: "Id", table: "TenantClients"...` is where the issue appears to occur.   It apparently tries to recreate the sequence used by `TenantClients.Id`.  I'm not sure what it _should_ be doing - maybe updating the tooling led to this?

Anyway, here's the full output:

```
D:\Users\ben\proj\sb\IdentityServer\src\Saddleback.IdentityServer.Data [master ≡ +3 ~6 -0 !]
λ dotnet ef database update -c Saddleback.IdentityServer.Data.ApplicationDbContext

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.63
Executed DbCommand (9ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT EXISTS (SELECT 1 FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE c.relname='__EFMigrationsHistory');
Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT EXISTS (SELECT 1 FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE c.relname='__EFMigrationsHistory');
Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT "MigrationId", "ProductVersion"
FROM "__EFMigrationsHistory"
ORDER BY "MigrationId";
Applying migration '20170210195057_SignupStatus'.
Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
DROP INDEX "IX_AspNetUserRoles_UserId";
Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
DROP INDEX "RoleNameIndex";
Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE SEQUENCE "TenantClients_Id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE NO CYCLE;
ALTER TABLE "TenantClients" ALTER COLUMN "Id" TYPE int4;
ALTER TABLE "TenantClients" ALTER COLUMN "Id" SET NOT NULL;
ALTER TABLE "TenantClients" ALTER COLUMN "Id" SET DEFAULT (nextval('"TenantClients_Id_seq"'));
ALTER SEQUENCE "TenantClients_Id_seq" OWNED BY "TenantClients"."Id"
Npgsql.PostgresException: 42P07: relation "TenantClients_Id_seq" already exists
   at Npgsql.NpgsqlConnector.DoReadMessage(DataRowLoadingMode dataRowLoadingMode, Boolean isPrependedMessage)
   at Npgsql.NpgsqlConnector.ReadMessageWithPrepended(DataRowLoadingMode dataRowLoadingMode)
   at Npgsql.NpgsqlDataReader.NextResultInternal()
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.Execute(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteNonQueryInternal()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
42P07: relation "TenantClients_Id_seq" already exists
D:\Users\ben\proj\sb\IdentityServer\src\Saddleback.IdentityServer.Data [master ≡ +3 ~6 -0 !]
λ
```

```
Exception message: Npgsql.PostgresException: 42P07: relation "TenantClient_Id_seq" already exists
Stack trace:
Npgsql.PostgresException: 42P07: relation "TenantClients_Id_seq" already exists
   at Npgsql.NpgsqlConnector.DoReadMessage(DataRowLoadingMode dataRowLoadingMode, Boolean isPrependedMessage)
   at Npgsql.NpgsqlConnector.ReadMessageWithPrepended(DataRowLoadingMode dataRowLoadingMode)
   at Npgsql.NpgsqlDataReader.NextResultInternal()
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.Execute(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteNonQueryInternal()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Steps to reproduce
I don't know how to write steps to reproduce.  Here was the sequence of things for me:
1. Use project.json-based tooling, version 1.0.1, to create first several migrations.  
2. Update CLI to 1.0.0-rc4
3. Update EF Core and EF CLI tooling to 1.1.0 and 1.0.0-msbuild3-final, respectively
4. Add two properties to an existing entity
5. Run `dotnet ef migrations add SignupStatus -c Saddleback.IdentityServer.Data.ApplicationDbContext`
6. Observe failure.

Code for reproducing the issue - if necessary.  This would be time consuming for me, and I'm hoping I'm missing something obvious that someone can point out.  

### Further technical details
EF Core version: 1.1.0
Database Provider: Npgsql
Operating system: Windows 10
IDE: .NET CLI

**Comment by smitpatel** [comment]
cc: @roji

**Comment by aggieben** [comment]
It looks like I should have investigated the release notes for `Npgsql.EntityFrameworkCore.PostgreSQL` 1.1.0 before posting this.  It reads:

> Upgrading from 1.0.x
If you've used 1.0.x without migrations, you can simply upgrade and everything should just work. Unfortunately, if you already have migrations from 1.0.x you'll have to do some manual fixups because of some bad decisions that were previously made. If deleting your old migrations and starting over (e.g. non-production database) is an option, you may wish to do so. The following are instructions for fixing up 1.0.x migrations.
>
>First, Npgsql 1.0.x used a problematic method to identify serial (autoincrement) columns in migrations. If you look at your migration code you'll see .Annotation("Npgsql:ValueGeneratedOnAdd", true) on various columns. Unfortunately this annotation is also present on non-serial columns, e.g. columns with default values. This causes various issues and has been replaced in 1.1. However, you'll have to manually remove .Annotation("Npgsql:ValueGeneratedOnAdd", true), and replace it with .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn) but only on columns which should be serial (e.g. not on columns with defaults). If you attempt to run a migration that has the old annotation, Npgsql will throw an exception and refuse to run your migrations.
Unfortunately, this change will cause some incorrect changes the first time you add a migration after the upgrade. To avoid this, simply add a dummy migration right after upgrading to 1.1 and then delete the two new files generated for the dummy migration, but keep the changes made to your ModelSnapshot.cs. From this point on everything should be fine. Make sure you have no pending changes to your model before doing this!.
>
>Apologies for this problematic upgrade procedure, it should at least keep things clean going forward.

http://www.npgsql.org/efcore/migration/1.1.html

I'll give these instructions a whirl and the report back here whether or not my issue was resolved.

**Comment by aggieben** [comment]
Yep, following the instructions was all it took.  Imagine that.
