### ISSUE TITLE
Cannot insert explicit value for identity column in table when IDENTITY_INSERT is set to OFF

### ISSUE THREAD

**Issue by mb2140** [dotnet/efcore#7595]
Describe what is not working as expected.

Retrieving an entity from database and, then trying to insert that entity into the database produces the error below.  This is something that always worked in previous EF versions, and I'm hoping there's a better way to do this automatically rather than cloning each entity manually.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: Cannot insert explicit value for identity column in table when IDENTITY_INSERT is set to OFF
Stack trace:  {System.Data.SqlClient.SqlException: Cannot insert explicit value for identity column in table 'Website' when IDENTITY_INSERT is set to OFF.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
ClientConnectionId:497356e6-8e51-406d-9127-f6b21d661d80
Error Number:544,State:1,Class:16}
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to repoduce the issue.

```c#
var item = UnitOfWork.Items.Find().FirstOrDefault(x => x.itemID== dto.itemID);

dbSet.Add(item);
context.SaveChanges();

```

### Further technical details
EF Core version: 1.1
Database Provider: MSSQL Azure
Operating system: Windows 8.1
IDE: VS 2015, IIS Express

**Comment by ajcvickers** [comment]
@mb2140 Is your expectation here that the entity will be inserted again and will get a new key value generated? If so, and assuming your Find() method is doing a no-tracking query, then the key value will need to be set to the CLR default (i.e. zero) before calling Add.
