### ISSUE TITLE
TPH Inheritance in EntityFramework Core 1.0.1 - Invalid Object Name 'People'

### ISSUE THREAD

**Issue by Jalalx** [dotnet/efcore#7598]
I'm trying to build a simple example console app for TPH inheritance model. But I have no idea what I'm missing!

This is logging output to console:
```
dbug: Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator[0]
      Using database 'EFCoreInheritance' on server '.'.
dbug: Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection[3]
      Opening connection to database 'EFCoreInheritance' on server '.'.
dbug: Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection[4]
      Closing connection to database 'EFCoreInheritance' on server '.'.
dbug: Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection[3]
      Opening connection to database 'EFCoreInheritance' on server '.'.
info: Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory[1]
      Executed DbCommand (14ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'__EFMigrationsHistory');
dbug: Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection[4]
      Closing connection to database 'EFCoreInheritance' on server '.'.
dbug: Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection[3]
      Opening connection to database 'EFCoreInheritance' on server '.'.
dbug: Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection[4]
      Closing connection to database 'EFCoreInheritance' on server '.'.
dbug: Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection[3]
      Opening connection to database 'EFCoreInheritance' on server '.'.
info: Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory[1]
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'__EFMigrationsHistory');
dbug: Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection[4]
      Closing connection to database 'EFCoreInheritance' on server '.'.
dbug: Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection[3]
      Opening connection to database 'EFCoreInheritance' on server '.'.
info: Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory[1]
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [MigrationId], [ProductVersion]
      FROM [__EFMigrationsHistory]
      ORDER BY [MigrationId];
dbug: Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection[4]
      Closing connection to database 'EFCoreInheritance' on server '.'.
dbug: Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection[3]
      Opening connection to database 'EFCoreInheritance' on server '.'.
dbug: Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection[5]
      Beginning transaction with isolation level 'Unspecified'.
info: Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory[1]
      Executed DbCommand (15ms) [Parameters=[@p0='?' (Size = 100), @p1='?' (Size = 100), @p2='?', @p3='?', @p4='?' (Size = 10), @p5='?' (Size = 100), @p6='?' (Size = 100), @p7='?', @p8='?'], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [People] ([FirstName], [LastName], [PersonType], [Balance], [CustomerNumber])
      VALUES (@p0, @p1, @p2, @p3, @p4);
      SELECT [Id]
      FROM [People]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
      INSERT INTO [People] ([FirstName], [LastName], [PersonType], [EmployeeType])
      VALUES (@p5, @p6, @p7, @p8);
      SELECT [Id]
      FROM [People]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
dbug: Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection[4]
      Closing connection to database 'EFCoreInheritance' on server '.'.
fail: Microsoft.EntityFrameworkCore.DbContext[1]
      An exception occurred in the database while saving changes.
      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Invalid object name 'People'.
         at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
         at System.Data.SqlClient.SqlDataReader.get_MetaData()
         at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
         at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
         at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
         at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
         --- End of inner exception stack trace ---
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Invalid object name 'People'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Invalid object name 'People'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at EFCoreInheritanceSample.Program.Main(String[] args) in D:\EFCoreInheritanceSample\src\EFCoreInheritanceSample\Program.cs:line 35
```

### Steps to reproduce
Here is all of my code:

```c#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using System;

namespace EFCoreInheritanceSample
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var context = new PeopleDb())
            {
                try
                {
                    context.LogToConsole();
                    context.Database.Migrate();

                    context.Customers.Add(new Customer
                    {
                        FirstName = "Mark",
                        LastName = "Zak",
                        Balance = 200000,
                        CustomerNumber = "08746453"
                    });

                    context.Employees.Add(new Employee
                    {
                        FirstName = "Mike",
                        LastName = "Robbi",
                        EmployeeType = EmployeeType.Manager,
                    });

                    context.SaveChanges();
                }
                catch (Exception ex)
                {
                    Console.ForegroundColor = ConsoleColor.Red;
                    Console.WriteLine(ex.ToString());
                    Console.ReadLine();
                    Console.ResetColor();
                }
            }

        }
    }

    public class PeopleDb : DbContext
    {
        public DbSet<Employee> Employees { get; set; }

        public DbSet<Customer> Customers { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            optionsBuilder.UseSqlServer("data source=.;integrated security=true;initial catalog=EFCoreInheritance;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Person>()
                .ToTable("People")
                .HasDiscriminator<PersonType>("PersonType")
                .HasValue<Customer>(PersonType.Customer)
                .HasValue<Employee>(PersonType.Employee);

            modelBuilder.Entity<Person>().HasKey(p => p.Id);
            modelBuilder.Entity<Person>().Property(p => p.FirstName).HasMaxLength(100);
            modelBuilder.Entity<Person>().Property(p => p.LastName).HasMaxLength(100);

            modelBuilder.Entity<Employee>();
            modelBuilder.Entity<Customer>().Property(p => p.CustomerNumber).HasMaxLength(10);
        }
    }

    public enum PersonType
    {
        Customer = 1,
        Employee = 2,
    }

    public abstract class Person
    {
        public int Id { get; set; }

        public PersonType PersonType { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }
    }

    public class Customer : Person
    {
        public decimal Balance { get; set; }

        public string CustomerNumber { get; set; }
    }

    public enum EmployeeType { Employee = 1, Manager = 2, CEO = 3 }

    public class Employee : Person
    {
        public EmployeeType EmployeeType { get; set; }
    }

    public static class DbContextExtensions
    {
        public static void LogToConsole(this DbContext context)
        {
            var contextServices = ((IInfrastructure<IServiceProvider>)context).Instance;
            var loggerFactory = contextServices.GetRequiredService<ILoggerFactory>();
            loggerFactory.AddConsole(LogLevel.Debug);
        }
    }
}
```
And project.json:

```json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.1",
    "Microsoft.EntityFrameworkCore": "1.0.1",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.1"
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}
```

I'm using Visual Studio 2015 Update 3 on Windows 10

**Comment by ajcvickers** [comment]
@Jalalx What does the table People look like in the database--e.g. what columns does it have? How was it created?

**Comment by Jalalx** [comment]
Table doesn't exists. `context.Database.Migrate()` must create it. It creates database if it doesn't exists but I don't know why it doesn't create tables.

**Comment by ajcvickers** [comment]
@Jalalx Have you created a migration for it? It might be worth working through the steps involving Migrations in one of the getting started guides here: https://docs.microsoft.com/en-us/ef/core/get-started/

**Comment by Jalalx** [comment]
@ajcvickers  no, actually I was trying to use Auto Migration feature.

**Comment by ajcvickers** [comment]
@Jalalx EF Core does not support automatic migrations. EnsureDeleted and EnsureCreated can be used for throwaway databases in things like prototyping and tests. For production databases, migrations must be created.
