### ISSUE TITLE
VS2017 Migration - Why Do I need to repeat code for Update-Database

### ISSUE THREAD

**Issue by Wayne-Mather** [dotnet/efcore#7641]
Hi,

First of all, sorry if this post is long, I am trying to include as much detail as possible to see if the problem is my ignorance or an edge case not supported yet.

The problem is after migration trying to fix the empty constructor error and having the DbContext in a separate assembly.

TLDR;

Why do we need to duplicate code just so Update-Database can work? Am I doing something wrong that breaks the DI part from the PowerShell utility?

```
// why do I need in my context
public class ApplicationDbContext : IdentityDbContext<ApplicationUser>, IApplicationDbContext 
    {
        public ApplicationDbContext()
        {
        
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=.;Database=xxxWeb;Trusted_Connection=True;MultipleActiveResultSets=true",
                b => b.MigrationsAssembly("xxxWeb"));
            base.OnConfiguring(optionsBuilder);
        }
}

// and also need in my startup?
public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddDbContext<ApplicationDbContext>(options =>
                    options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"),
                        b => b.MigrationsAssembly("xxxWeb"))
            );
}
```

-------

Long version below

I have a project that is working successfully under VS2015. It is a standard ASP.NET MVC Core with the application context in a separate DLL (ASP.NET Project with empty main to satisfy EF Core)).

I can successfully dotnet ef migration xxx and dotnet ef database update without any issues. 
I have now started to try and move to VS2017 but cannot update databases.

```
Build started...
Build succeeded.
Setting app base path C:\Repos\MyApp\Source\Web\MyAppWeb\src\MyAppWeb\bin\Debug\netcoreapp1.1
An error occurred while calling method 'ConfigureServices' on startup class 'Startup'. Consider using IDbContextFactory to override the initialization of the DbContext at design-time. Error: Could not find 'UserSecretsIdAttribute' on assembly 'ef, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
System.InvalidOperationException: Could not find 'UserSecretsIdAttribute' on assembly 'ef, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.Extensions.Configuration.ConfigurationExtensions.AddUserSecrets(IConfigurationBuilder configuration)
   at MyAppWeb.Startup..ctor(IHostingEnvironment env) in C:\Repos\MyApp\Source\Web\MyAppWeb\src\MyAppWeb\Startup.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.StartupInvoker.Invoke(Type type, String[] methodNames, IServiceCollection services)
Finding DbContext classes...
Microsoft.EntityFrameworkCore.Design.OperationException: No parameterless constructor was found on 'ApplicationDbContext'. Either add a parameterless constructor to 'ApplicationDbContext' or add an implementation of 'IDbContextFactory<ApplicationDbContext>' in the same assembly as 'ApplicationDbContext'. ---> System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
No parameterless constructor was found on 'ApplicationDbContext'. Either add a parameterless constructor to 'ApplicationDbContext' or add an implementation of 'IDbContextFactory<ApplicationDbContext>' in the same assembly as 'ApplicationDbContext'.
PM> 
```

So I reverted the code base in-case the VS2017 migration wizard did something. I fired up a VS2017 console prompt:

```
dotnet --version
1.0.0-rc4-004771
```

Now entered the directory where the solution is:

```
dotnet --version
1.0.0-preview2-1-003177
```

Validated things working as expected. Modified global.json:

```
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-rc4-004771"
  }
}

```

Reran the version command to ensure it is updated:

```
dotnet --version
1.0.0-rc4-004771
```
Now I execute dotnet migrate at the prompt

```
Project xxx.BLL migration succeeded

Project xxxWeb migration succeeded

Summary
Total Projects: 5
Succeeded Projects: 5
Failed Projects: 0

The project migration has finished. Please visit https://aka.ms/coremigration to report any issues you've encountered or ask for help.
Files backed up to c:\Repos\xxx\Source\Web\xxxWeb\backup\
```

So far so good. Lets restore the packages:

```
c:\Repos\xxx\Source\Web\xxxWeb>dotnet restore
c:\Repos\xxx\Source\Reports\xxxWebReports\xxxWebReports\xxxWebReports.rptproj(3,3): error MSB4067: The element <State> beneath element <Project> is unrecognized.
c:\Repos\xxx\Source\Reports\xxxWebReports\xxxReporting\xxxReporting.sqlproj(93,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\1.0.0-rc4-004771\Microsoft\VisualStudio\v11.0\SSDT\Microsoft.Data.Tools.Schema.SqlTasks.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
  Restoring packages for c:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb\xxxWeb.csproj...
  Restoring packages for c:\Repos\xxx\Source\Web\xxxWeb\src\xxx.BLL\xxx.BLL.csproj...
  Restoring packages for c:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb\xxxWeb.csproj...
  Restoring packages for c:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb\xxxWeb.csproj...
  Restoring packages for c:\Repos\xxx\Source\Web\xxxWeb\test\xxxIntegrationTests\xxxIntegrationTests.csproj...
  Restoring packages for c:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb\xxxWeb.csproj...
  Restoring packages for c:\Repos\xxx\Source\Web\xxxWeb\test\xxxWeb.Tests\xxxWeb.Tests.csproj...
  Restoring packages for c:\Repos\xxx\Source\Web\xxxWeb\src\xxxSync\xxxSync.csproj...
  Restore completed in 2.62 sec for c:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb\xxxWeb.csproj.
  Restore completed in 2.63 sec for c:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb\xxxWeb.csproj.
  Restoring packages for c:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb\xxxWeb.csproj...
  Restore completed in 2.61 sec for c:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb\xxxWeb.csproj.
  Restoring packages for c:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb\xxxWeb.csproj...
  Generating MSBuild file c:\Repos\xxx\Source\Web\xxxWeb\src\xxx.BLL\obj\xxx.BLL.csproj.nuget.g.props.
  Generating MSBuild file c:\Repos\xxx\Source\Web\xxxWeb\src\xxx.BLL\obj\xxx.BLL.csproj.nuget.g.targets.
  Writing lock file to disk. Path: c:\Repos\xxx\Source\Web\xxxWeb\src\xxx.BLL\obj\project.assets.json
  Restore completed in 4.31 sec for c:\Repos\xxx\Source\Web\xxxWeb\src\xxx.BLL\xxx.BLL.csproj.
  Restore completed in 1.86 sec for c:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb\xxxWeb.csproj.
  Restore completed in 2.14 sec for c:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb\xxxWeb.csproj.
  Generating MSBuild file c:\Repos\xxx\Source\Web\xxxWeb\src\xxxSync\obj\xxxSync.csproj.nuget.g.props.
  Generating MSBuild file c:\Repos\xxx\Source\Web\xxxWeb\src\xxxSync\obj\xxxSync.csproj.nuget.g.targets.
  Writing lock file to disk. Path: c:\Repos\xxx\Source\Web\xxxWeb\src\xxxSync\obj\project.assets.json
  Restore completed in 5.36 sec for c:\Repos\xxx\Source\Web\xxxWeb\src\xxxSync\xxxSync.csproj.
  Generating MSBuild file c:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb\obj\xxxWeb.csproj.nuget.g.props.
  Generating MSBuild file c:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb\obj\xxxWeb.csproj.nuget.g.targets.
  Writing lock file to disk. Path: c:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb\obj\project.assets.json
  Generating MSBuild file c:\Repos\xxx\Source\Web\xxxWeb\test\xxxWeb.Tests\obj\xxxWeb.Tests.csproj.nuget.g.props.
  Generating MSBuild file c:\Repos\xxx\Source\Web\xxxWeb\test\xxxWeb.Tests\obj\xxxWeb.Tests.csproj.nuget.g.targets.
  Writing lock file to disk. Path: c:\Repos\xxx\Source\Web\xxxWeb\test\xxxWeb.Tests\obj\project.assets.json
  Restore completed in 5.66 sec for c:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb\xxxWeb.csproj.
  Generating MSBuild file c:\Repos\xxx\Source\Web\xxxWeb\test\xxxIntegrationTests\obj\xxxIntegrationTests.csproj.nuget.g.props.
  Generating MSBuild file c:\Repos\xxx\Source\Web\xxxWeb\test\xxxIntegrationTests\obj\xxxIntegrationTests.csproj.nuget.g.targets.
  Restore completed in 5.66 sec for c:\Repos\xxx\Source\Web\xxxWeb\test\xxxWeb.Tests\xxxWeb.Tests.csproj.
  Writing lock file to disk. Path: c:\Repos\xxx\Source\Web\xxxWeb\test\xxxIntegrationTests\obj\project.assets.json
  Restore completed in 5.69 sec for c:\Repos\xxx\Source\Web\xxxWeb\test\xxxIntegrationTests\xxxIntegrationTests.csproj.

  NuGet Config files used:
      C:\Users\mathe\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

  Feeds used:
      https://api.nuget.org/v3/index.json
      https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json
      https://www.myget.org/F/aspnet-contrib/api/v3/index.json
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

c:\Repos\xxx\Source\Web\xxxWeb>

```

Now run msbuild:

```
Lots of output..

    34 Warning(s)
    0 Error(s)

Time Elapsed 00:00:17.28
```
Now I will open up the solution in visual studio and try to update the database

```
PM> Update-Database -Verbose
Using project 'src\xxxWeb'.
Using startup project 'src\xxxWeb'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile C:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb\bin\Debug\netcoreapp1.1\xxxWeb.deps.json --additionalprobingpath C:\Users\mathe\.nuget\packages --runtimeconfig C:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb\bin\Debug\netcoreapp1.1\xxxWeb.runtimeconfig.json C:\Users\mathe\.nuget\packages\microsoft.entityframeworkcore.tools\1.0.0-msbuild3-final\tools\netcoreapp1.0\ef.dll database update --verbose --no-color --prefix-output --assembly C:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb\bin\Debug\netcoreapp1.1\xxxWeb.dll --startup-assembly C:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb\bin\Debug\netcoreapp1.1\xxxWeb.dll --project-dir C:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb --content-root C:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb --data-dir C:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb\bin\Debug\netcoreapp1.1\ --root-namespace xxxWeb
Using assembly 'xxxWeb'.
Using startup assembly 'xxxWeb'.
Using application base 'C:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb\bin\Debug\netcoreapp1.1'.
Using content root 'C:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb'.
Using root namespace 'xxxWeb'.
Using project directory 'C:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb'.
Using data directory 'C:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb\bin\Debug\netcoreapp1.1\'.
An error occurred while calling method 'ConfigureServices' on startup class 'Startup'. Consider using IDbContextFactory to override the initialization of the DbContext at design-time. Error: Could not find 'UserSecretsIdAttribute' on assembly 'ef, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
System.InvalidOperationException: Could not find 'UserSecretsIdAttribute' on assembly 'ef, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.Extensions.Configuration.ConfigurationExtensions.AddUserSecrets(IConfigurationBuilder configuration)
   at xxxWeb.Startup..ctor(IHostingEnvironment env) in C:\Repos\xxx\Source\Web\xxxWeb\src\xxxWeb\Startup.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.StartupInvoker.Invoke(Type type, String[] methodNames, IServiceCollection services)
Finding DbContext classes...
Microsoft.EntityFrameworkCore.Design.OperationException: No parameterless constructor was found on 'ApplicationDbContext'. Either add a parameterless constructor to 'ApplicationDbContext' or add an implementation of 'IDbContextFactory<ApplicationDbContext>' in the same assembly as 'ApplicationDbContext'. ---> System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
No parameterless constructor was found on 'ApplicationDbContext'. Either add a parameterless constructor to 'ApplicationDbContext' or add an implementation of 'IDbContextFactory<ApplicationDbContext>' in the same assembly as 'ApplicationDbContext'.
```

So the same the problem exists. Lets try to fix that problem by implementing my own constructor:

```
public class ApplicationDbContext : IdentityDbContext<ApplicationUser>, IApplicationDbContext 
    {
        public ApplicationDbContext()
        {
        
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=.;Database=xxxWeb;Trusted_Connection=True;MultipleActiveResultSets=true");
            base.OnConfiguring(optionsBuilder);
        }

 // yes more code but not necessary for this scenario
}

```

Now try to run Update-Database command again

```
Finding DbContext classes...
Using context 'ApplicationDbContext'.
Microsoft.EntityFrameworkCore.Design.OperationException: Your target project 'xxxWeb' doesn't match your migrations assembly 'xxx.BLL'. Either change your target project or change your migrations assembly.
Change your migrations assembly by using DbContextOptionsBuilder. E.g. options.UseSqlServer(connection, b => b.MigrationsAssembly("xxxWeb")). By default, the migrations assembly is the assembly containing the DbContext.
Change your target project to the migrations project by using the Package Manager Console's Default project drop-down list, or by executing "dotnet ef" from the directory containing the migrations project.
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.EnsureServices(IServiceProvider services)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Your target project 'xxxWeb' doesn't match your migrations assembly 'xxx.BLL'. Either change your target project or change your migrations assembly.
```

Fantastic and bad, why am I having to repeat the exact code I have in my startup command? So change the OnConfiguring()

```
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=.;Database=xxxWeb;Trusted_Connection=True;MultipleActiveResultSets=true",
                b => b.MigrationsAssembly("xxxWeb"));
            base.OnConfiguring(optionsBuilder);
        }
```

Rebuild the solution and enter PowerShell again:

```
PM> Update-Database 
An error occurred while calling method 'ConfigureServices' on startup class 'Startup'. Consider using IDbContextFactory to override the initialization of the DbContext at design-time. Error: Could not find 'UserSecretsIdAttribute' on assembly 'ef, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Lots of text..
Done.
```

Migrations successfully applied. I delete the database and tried from version 0 just to ensure. All successful.

### Further technical details
EF Core version: (found in project.json or packages.config) - There is no packages.config or project.json but in backup file was version 1.1.0
Database Provider: "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
Operating system: Windows 10 (1607 - 14393.693)
IDE: Visual Studio 2017 (15.0.26206.0)

**Comment by bricelam** [comment]
Unfortunately, the migration to VS 2017 is incomplete for UserSecrets. The final step is to change the call in Startup from `.AddUserSecrets()` to `.AddUserSecrets<Startup>()`. They are aware of this and are looking at ways of making the experience better before VS 2017 RTM.

**Comment by Wayne-Mather** [comment]
Hi Brice,

Thanks for the response, my real problem is the duplicated code. In startup we setup the services and create the DbContext with the connection string from the appsettings.json. However, now that EF has changed in the thisrelease, i have to have the same code in a default constructor. Can I get around this any way or is this the way it is until RTM/2.0 release hits the streets?

**Comment by bricelam** [comment]
That's what I'm saying: After fixing UserSecrets, you should be able to remove the duplicated code and Migrations will work just like it used to.

**Comment by Wayne-Mather** [comment]
@bricelam Ok understand. I did not take that from your first comment as it sounded like you were more describing the user secret problem rather than migrations as a whole being affected.

Agree with the label and will close as will assume will be resolved by RTM.

**Comment by Wayne-Mather** [comment]
Just confirming that this bug still exists in RTM of VS2017 but the fix is as trivial as modifying the AddUserSecrets() line of code what what brice mentions.

dotnet ef xxxx commands work as expected

**Comment by Ibrahim-Islam** [comment]
`AddUserSecrets<StartUp>` Did not solve the problem for me but [this](https://docs.microsoft.com/en-us/ef/core/miscellaneous/configuring-dbcontext#using-idbcontextfactorytcontext) did. But I do not hard-coded connection string in the class. What can be done?

**Comment by Wayne-Mather** [comment]
@Ibrahim-Islam 

This is my startup relevant functions and this works successfully. To get more information you may have to provide details of your startup function.

Another thing you can do if you have the bandwidth is download visual studio 2017 and create a new application and see how the code differs from your current application.

```
public Startup(IHostingEnvironment env)
        {
            ContentPath = env.ContentRootPath;

            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true);

            if (env.IsDevelopment())
            {
                // For more details on using the user secret store see http://go.microsoft.com/fwlink/?LinkID=532709
                //builder.AddUserSecrets();
                builder.AddUserSecrets<Startup>();
            }

            builder.AddEnvironmentVariables();
            Configuration = builder.Build();
}

public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddDbContext<ApplicationDbContext>(options =>
                    options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"))
            );

            services.AddIdentity<ApplicationUser, IdentityRole>(o =>
                {
                    o.Password.RequireDigit = false;
                    o.Password.RequireLowercase = false;
                    o.Password.RequireUppercase = false;
                    o.Password.RequireNonAlphanumeric = false;
                    o.Password.RequiredLength = 5;
                })
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

            services.AddMvc();

        }
```

**Comment by Ibrahim-Islam** [comment]
@Wayne-Mather I have my code generated with VS 2017 and my StartUp is mostly that, as follows:

```
    public class Startup
    {
        public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true);
            if (env.IsDevelopment())
            {
                // For more details on using the user secret store see https://go.microsoft.com/fwlink/?LinkID=532709
                builder.AddUserSecrets<Startup>();
            }
            builder.AddEnvironmentVariables();
            Configuration = builder.Build();
        }
        public IConfigurationRoot Configuration { get; }
        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
            services.AddIdentity<ApplicationUser, IdentityRole>(options => 
                {
                    options.SignIn.RequireConfirmedEmail = false;
                    options.SignIn.RequireConfirmedPhoneNumber = false;
                    options.Lockout.MaxFailedAccessAttempts = 100;
                    options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromSeconds(1);
                    options.User.RequireUniqueEmail = true;
                })
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();
            services.AddMvc();
            services.AddScoped<IApplicationDbContext, ApplicationDbContext>();
            services.AddScoped<IUnitOfWork, UnitOfWork>();
        }
        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseDatabaseErrorPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }
            app.UseStaticFiles();
            app.UseIdentity();
            // Add external authentication middleware below. To configure them please see https://go.microsoft.com/fwlink/?LinkID=532715
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }
```

**Comment by JwanKhalaf** [comment]
> Unfortunately, the migration to VS 2017 is incomplete for UserSecrets. The final step is to change the call in Startup from `.AddUserSecrets()` to `.AddUserSecrets<Startup>()`. They are aware of this and are looking at ways of making the experience better before VS 2017 RTM.

@bricelam is this now done? We're in 2019 now, is this issue fixed? I've checked out a project that makes use of User Secrets.

When I try to run `Update-Database` I get the following:

> An error occurred while accessing the IWebHost on class 'Program'. Continuing without the application service provider. Error: need to configure key material

> Unable to create an object of type 'ApplicationDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

My `CreateWebHostBuilder()` looks like this:

```
public static IWebHostBuilder CreateWebHostBuilder(string[] args)
{
  return WebHost
    .CreateDefaultBuilder(args)
    .UseStartup<Startup>()
    .UseSerilog(
      (context, configuration) =>
      {
        configuration
          .MinimumLevel.Debug()
          .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
          .MinimumLevel.Override("System", LogEventLevel.Warning)
          .MinimumLevel.Override("Microsoft.AspNetCore.Authentication", LogEventLevel.Information)
          .Enrich.FromLogContext()
          .WriteTo.File(@"identityserver4_log.txt")
          .WriteTo.Console(
            outputTemplate: "[{Timestamp:HH:mm:ss} {Level}] {SourceContext}{NewLine}{Message:lj}{NewLine}{Exception}{NewLine}",
            theme: AnsiConsoleTheme.Literate);
      });
}
```

**Comment by bricelam** [comment]
@JwanKhalaf Does `-Verbose` provide any additional details.

> need to configure key material

This error doesn't look familiar to me...
