### ISSUE TITLE
One to many relationship producing "SQLite Error 19: 'UNIQUE constraint failed: Employees.Id'." at runtime

### ISSUE THREAD

**Issue by maxwenger** [dotnet/efcore#7724]
Describe what is not working as expected.

Hey, I'm really new to .Net core, I could totally be making an easy mistake, but I have been banging my head against the wall for hours now and cant seem to figure out what's going on.

After successfully creating a `Shift` and `Employee` table, with a one to many relationship, and updating the SQLite database. Any `Shift` record being committed fails the unique id requirement.

If you are seeing an exception, include the full exceptions details (message and stack trace).
```
Exception message: "SQLite Error 19: 'UNIQUE constraint failed: Employees.Id'."
Stack trace:
    at Microsoft.Data.Sqlite.Interop.MarshalEx.ThrowExceptionForRC(Int32 rc, Sqlite3Handle db)
    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
    at System.Data.Common.DbCommand.ExecuteReader()
    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)"
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to repoduce the issue.

Context:
```c#
using InterManage.Model;
using Microsoft.EntityFrameworkCore;

namespace InterManage.Repository.Persistence
{
    public class InterManageDbContext : DbContext
    {
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Shift> Shifts { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite("Filename=./InterManage.db");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Employee>(e =>
            {
                e.HasMany(x => x.Shifts)
                    .WithOne(s => s.AssignedEmployee)
                    .HasForeignKey(s => s.AssignedEmployeeRefId)
                    .HasConstraintName("ForeignKey_Employee_Shift");
            });
        }
    }
}
```
Shift:
```c#
using System;
using System.ComponentModel;

namespace InterManage.Model
{
    public class Shift
    {
        public Shift()
        {
            Id = Guid.NewGuid();
        }

        public Guid Id { get; private set; }

        public Guid AssignedEmployeeRefId { get; set; }

        public virtual Employee AssignedEmployee { get; set; }  
    }
}
```
Employee:
```c#
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace InterManage.Model
{
    public class Employee
    {
        public Employee()
        {
            Id = Guid.NewGuid();
            Shifts = new List<Shift>();
        }

        public Guid Id { get; private set; }

        public virtual ICollection<Shift> Shifts { get; set; }
    }
}
```

Saving it like this:
```c#
        public Employee E = new Employee();
        public Shift FocusedShift = new Shift
        {
            AssignedEmployee = e
        };

        public void SaveShift()
        {
            using (var db = new UnitOfWork(new InterManageDbContext()))
            {
                if (FocusedShift.Error == null)
                {
                    var shift = db.Shifts.Get(FocusedShift.Id);
                    if (shift == null)
                    {
                        db.Shifts.Add(FocusedShift);
                    }
                    else
                    {
                        shift.AssignedEmployee = FocusedShift.AssignedEmployee;
                    }
                    db.Commit();
                }
            }
        }
```
Unit Of Work:
```c#
using InterManage.Repository.Core;

namespace InterManage.Repository.Persistence
{
    internal class UnitOfWork
    {
        public IEmployeeRepository Employees { get; }
        public IShiftRepository Shifts { get; }

        private readonly InterManageDbContext context;
        
        public UnitOfWork(InterManageDbContext context)
        {
            this.context = context;
            Employees = new EmployeeRepository(context);
            Shifts = new ShiftRepository(context);
        }

        public int Commit()
        {
            return context.SaveChanges();
        }

        public void Dispose()
        {
            context.Dispose();
        }
    }
}
```
Reposotory:
```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;

namespace InterManage.Repository.Persistence
{
    public class Repository<TEntity>
    {        
        protected readonly DbContext Context;

        protected Repository(DbContext context)
        {
            Context = context;
        }

        public TEntity Get(Guid id) => Context.Set<Shift>().Find(id);

        public void Add(TEntity entity) => Context.Set<TEntity>().Add(entity);
    }
}
```
### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Win 10
IDE: VS 2017

**Comment by ajcvickers** [comment]
@Carefree4 I have not been able to reproduce this. I copied all your code into a console application but then had to make some edits to make it compile. Maybe you can look at the code below and try to make edits to reproduce the issue you are seeing.

```C#
    public class InterManageDbContext : DbContext
    {
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Shift> Shifts { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite("Filename=./InterManage.db");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Employee>(e =>
            {
                e.HasMany(x => x.Shifts)
                    .WithOne(s => s.AssignedEmployee)
                    .HasForeignKey(s => s.AssignedEmployeeRefId)
                    .HasConstraintName("ForeignKey_Employee_Shift");
            });
        }
    }

    public class Shift
    {
        public Shift()
        {
            Id = Guid.NewGuid();
        }

        public Guid Id { get; private set; }

        public Guid AssignedEmployeeRefId { get; set; }

        public virtual Employee AssignedEmployee { get; set; }
    }

    public class Employee
    {
        public Employee()
        {
            Id = Guid.NewGuid();
            Shifts = new List<Shift>();
        }

        public Guid Id { get; private set; }

        public virtual ICollection<Shift> Shifts { get; set; }
    }

    internal class UnitOfWork : IDisposable
    {
        public Repository<Employee> Employees { get; }
        public Repository<Shift> Shifts { get; }

        private readonly InterManageDbContext context;

        public UnitOfWork(InterManageDbContext context)
        {
            this.context = context;
            Employees = new Repository<Employee>(context);
            Shifts = new Repository<Shift>(context);
        }

        public int Commit()
        {
            return context.SaveChanges();
        }

        public void Dispose()
        {
            context.Dispose();
        }
    }

    public class Repository<TEntity> where TEntity : class
    {
        public readonly DbContext Context;

        public Repository(DbContext context)
        {
            Context = context;
        }

        public TEntity Get(Guid id) => Context.Set<TEntity>().Find(id);

        public void Add(TEntity entity) => Context.Set<TEntity>().Add(entity);
    }

    public class Program
    {
        public static Employee E = new Employee();

        public static Shift FocusedShift = new Shift
        {
            AssignedEmployee = E
        };

        public static void SaveShift()
        {
            var context = new InterManageDbContext();
            using (var db = new UnitOfWork(context))
            {
                var shift = context.Shifts.FirstOrDefault();
                //var shift = db.Shifts.Get(FocusedShift.Id);
                if (shift == null)
                {
                    db.Shifts.Add(FocusedShift);
                }
                else
                {
                    shift.AssignedEmployee = FocusedShift.AssignedEmployee;
                }
                db.Commit();
            }
        }

        public static void Main()
        {
            using (var context = new InterManageDbContext())
            {
                //context.Database.EnsureDeleted();
                context.Database.EnsureCreated();
            }

            SaveShift();
        }
    }
```

**Comment by Carefree4** [comment]
I created a new console app and pasted in your code and was able to build it. But I cannot seem to add a migration with the error message
```powershell
PM> add-migration
add-migration : The term 'add-migration' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again.
```

I believe my issue has to do with the improper packages, this is the list of all the installed packages I feel are relevant to this issue in the console app I built to investigate this issue.

```xml
  <package id="Microsoft.Data.Sqlite" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.EntityFrameworkCore" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.EntityFrameworkCore.Design" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.EntityFrameworkCore.Relational" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.EntityFrameworkCore.Relational.Design" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.EntityFrameworkCore.Sqlite" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.EntityFrameworkCore.Sqlite.Design" version="1.1.0" targetFramework="net452" />
```

And the list of all of the installed packages:
```xml
<packages>
  <package id="Microsoft.AspNetCore.Hosting.Abstractions" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Hosting.Server.Abstractions" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Http.Abstractions" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Http.Features" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.Data.Sqlite" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.EntityFrameworkCore" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.EntityFrameworkCore.Design" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.EntityFrameworkCore.Relational" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.EntityFrameworkCore.Relational.Design" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.EntityFrameworkCore.Sqlite" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.EntityFrameworkCore.Sqlite.Design" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.Extensions.Caching.Abstractions" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.Extensions.Caching.Memory" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.Extensions.Configuration.Abstractions" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.Extensions.DependencyInjection" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.Extensions.DependencyInjection.Abstractions" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.Extensions.FileProviders.Abstractions" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.Extensions.Logging" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.Extensions.Logging.Abstractions" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.Extensions.Options" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.Extensions.Primitives" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.NETCore.Platforms" version="1.1.0" targetFramework="net452" />
  <package id="NETStandard.Library" version="1.6.1" targetFramework="net452" />
  <package id="Remotion.Linq" version="2.1.1" targetFramework="net452" />
  <package id="SQLite" version="3.13.0" targetFramework="net452" />
  <package id="System.Collections" version="4.3.0" targetFramework="net452" />
  <package id="System.Collections.Concurrent" version="4.3.0" targetFramework="net452" />
  <package id="System.Collections.Immutable" version="1.3.0" targetFramework="net452" />
  <package id="System.ComponentModel" version="4.3.0" targetFramework="net452" />
  <package id="System.Diagnostics.Debug" version="4.3.0" targetFramework="net452" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.3.0" targetFramework="net452" />
  <package id="System.Diagnostics.Tools" version="4.3.0" targetFramework="net452" />
  <package id="System.Diagnostics.Tracing" version="4.3.0" targetFramework="net452" />
  <package id="System.Globalization" version="4.3.0" targetFramework="net452" />
  <package id="System.Interactive.Async" version="3.0.0" targetFramework="net452" />
  <package id="System.IO" version="4.3.0" targetFramework="net452" />
  <package id="System.IO.Compression" version="4.3.0" targetFramework="net452" />
  <package id="System.Linq" version="4.3.0" targetFramework="net452" />
  <package id="System.Linq.Expressions" version="4.3.0" targetFramework="net452" />
  <package id="System.Linq.Queryable" version="4.0.1" targetFramework="net452" />
  <package id="System.Net.Http" version="4.3.0" targetFramework="net452" />
  <package id="System.Net.Primitives" version="4.3.0" targetFramework="net452" />
  <package id="System.ObjectModel" version="4.3.0" targetFramework="net452" />
  <package id="System.Reflection" version="4.3.0" targetFramework="net452" />
  <package id="System.Reflection.Extensions" version="4.3.0" targetFramework="net452" />
  <package id="System.Reflection.Primitives" version="4.3.0" targetFramework="net452" />
  <package id="System.Resources.ResourceManager" version="4.3.0" targetFramework="net452" />
  <package id="System.Runtime" version="4.3.0" targetFramework="net452" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.3.0" targetFramework="net452" />
  <package id="System.Runtime.Extensions" version="4.3.0" targetFramework="net452" />
  <package id="System.Runtime.InteropServices" version="4.3.0" targetFramework="net452" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="net452" />
  <package id="System.Runtime.Numerics" version="4.3.0" targetFramework="net452" />
  <package id="System.Text.Encoding" version="4.3.0" targetFramework="net452" />
  <package id="System.Text.Encoding.Extensions" version="4.3.0" targetFramework="net452" />
  <package id="System.Text.Encodings.Web" version="4.3.0" targetFramework="net452" />
  <package id="System.Text.RegularExpressions" version="4.3.0" targetFramework="net452" />
  <package id="System.Threading" version="4.3.0" targetFramework="net452" />
  <package id="System.Threading.Tasks" version="4.3.0" targetFramework="net452" />
  <package id="System.Threading.Timer" version="4.3.0" targetFramework="net452" />
  <package id="System.Xml.ReaderWriter" version="4.3.0" targetFramework="net452" />
  <package id="System.Xml.XDocument" version="4.3.0" targetFramework="net452" />
</packages>
```

**Comment by Carefree4** [comment]
It was an ownership problem. I declared the relationship as 
```csharp
modelBuilder.Entity<Employee>(e =>
            {
                e.HasMany(x => x.Shifts)
                    .WithOne(s => s.AssignedEmployee)
                    .HasForeignKey(s => s.AssignedEmployeeRefId)
                    .HasConstraintName("ForeignKey_Employee_Shift");
            });
```

But I was adding it like this
```csharp
var shift = db.Shifts.Get(FocusedShift.Id);
db.Shifts.Add(FocusedShift);
```

But when I add it like this
```csharp
db.Employees.Get(FocusedShift.AssignedEmployee.Id).Shifts.Add(FocusedShift);
```

It works. I assume it's because of how the relationship was created. I think I was getting the unique constraint error because it was trying to add a new employee with the same ID before adding the `shift` in question.
