### ISSUE TITLE
LEFT JOIN Null check

### ISSUE THREAD

**Issue by ErazerBrecht** [dotnet/efcore#7755]
Describe what is not working as expected.

Using a null check, check 'STEPS TO REPRODUCE' for more details

```
2017-03-01 17:10:21.3707 ERROR System.ArgumentNullException: Value cannot be null.
Parameter name: meth
   at System.Reflection.Emit.DynamicILGenerator.Emit(OpCode opcode, MethodInfo meth)
   at System.Linq.Expressions.Compiler.ILGen.EmitHasValue(ILGenerator il, Type nullableType)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedRelational(ExpressionType op, Type leftType, Type rightType, Type resultType, Boolean liftedToNull)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBinaryOp(ExpressionType op, Type leftType, Type rightType, Type resultType, Boolean liftedToNull)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitBinaryOperator(ExpressionType op, Type leftType, Type rightType, Type resultType, Boolean liftedToNull)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitBinaryExpression(Expression expr, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchComparison(Boolean branch, BinaryExpression node, Label label)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAndBranch(Boolean branchValue, Expression node, Label label)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchBlock(Boolean branch, BlockExpression node, Label label)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAndBranch(Boolean branchValue, Expression node, Label label)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitConditionalExpression(Expression expr, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(Expression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitVariableAssignment(BinaryExpression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitAssign(BinaryExpression node, CompilationFlags emitAs)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsVoid(Expression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Emit(BlockExpression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsVoid(Expression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Emit(BlockExpression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitBlockExpression(Expression expr, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(Expression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsType(Expression node, Type type, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Emit(BlockExpression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitBlockExpression(Expression expr, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(Expression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaBody(CompilerScope parent, Boolean inlined, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitDelegateConstruction(LambdaExpression lambda)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(Expression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitArguments(MethodBase method, IArgumentProvider args, Int32 skipParameters)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodCall(MethodInfo mi, IArgumentProvider args, Type objectType, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodCall(Expression obj, MethodInfo method, IArgumentProvider methodCallExpr, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodCallExpression(Expression expr, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(Expression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitArguments(MethodBase method, IArgumentProvider args, Int32 skipParameters)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodCall(MethodInfo mi, IArgumentProvider args, Type objectType, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodCall(Expression obj, MethodInfo method, IArgumentProvider methodCallExpr, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodCallExpression(Expression expr, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(Expression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaBody(CompilerScope parent, Boolean inlined, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaBody()
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at System.Linq.Expressions.Expression`1.Compile(Boolean preferInterpretation)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateExecutorLambda[TResults]()
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, ILogger logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileQuery>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at erazer.DAL.Repositories.SubmissionRepository.<GetAllSubmissionsForCompanyAccount>d__10.MoveNext() in C:\Users\Brecht\Source\Repos\erazer\src\erazer.DAL\Repositories\SubmissionRepository.cs:line 561
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at erazer.BLL.Managers.SubmissionManager.<GetAllSubmissionsForCompanyAccount>d__22.MoveNext() in C:\Users\Brecht\Source\Repos\erazer\src\erazer.BLL\Managers\SubmissionManager.cs:line 288
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at erazer.API.Company.Controllers.SubmissionController.<GetAllSubmissionsForUser>d__4.MoveNext() in C:\Users\Brecht\Source\Repos\erazer\src\erazer.API.Company\Controllers\SubmissionController.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at erazer.BLL.Helpers.Middleware.ErrorHandlingMiddleware.ThrowError(Task t) in C:\Users\Brecht\Source\Repos\erazer\src\erazer.BLL\Helpers\Middleware\ErrorHandlingMiddleware.cs:line 46
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at erazer.BLL.Helpers.Middleware.ErrorHandlingMiddleware.<Invoke>d__3.MoveNext() in C:\Users\Brecht\Source\Repos\erazer\src\erazer.BLL\Helpers\Middleware\ErrorHandlingMiddleware.cs:line 25 
```

### Steps to reproduce

The first query succeeds. The second one gives the exception.
My head almost broke while searching for this bug.
Maybe you could make the error a little bit 'easier' to understand

```c#
var test = (from internalReferenceEvent in _ctx.SubmissionEvents
            from internalReference in _ctx.SubmissionTicketReferenceEvents.Where(ticket => ticket.Id == internalReferenceEvent.Id).DefaultIfEmpty()
            select new TestDto
            {
                TicketReference = internalReference.TicketReference
            }).ToList();

var test = (from internalReferenceEvent in _ctx.SubmissionEvents
            from internalReference in _ctx.SubmissionTicketReferenceEvents.Where(ticket => ticket.Id == internalReferenceEvent.Id).DefaultIfEmpty()
            select new TestDto
            {
                TicketReference = internalReference != null ? internalReference.TicketReference : null
            }).ToList();
```

I have to admit I didn't have the chance to try it on a smaller DB and try to reproduce it.

Hope this helps other developers / ef team

Sincerely,
Brecht

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win10 x64 Pro
IDE:  Visual Studio 2015

**Comment by tuespetre** [comment]
All sorts of crazy stuff happens with `meth` :trollface:

**Comment by maumar** [comment]
I was unable to reproduce this, looks like a compiler issue that has been fixed underneath.
