### ISSUE TITLE
dotnet ef can't find project.json

### ISSUE THREAD

**Issue by ZhaoXiangXML** [dotnet/efcore#7908]
I'm trying to run dotnet ef on an VS 2017 .net standard project. my Startup Project is .net core. Both projects are created in VS 2017 and based on .csproj.

However I got the following error message:

```
System.IO.FileNotFoundException: Could not find file 'C:\Projects\Pro\Server\Server.Grains\project.json'.
File name: 'C:\Projects\Pro\Server\Server.Grains\project.json'
   at System.IO.Win32FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.DotNet.ProjectModel.ProjectReader.GetProject(String projectPath, ProjectReaderSettings settings)
   at Microsoft.DotNet.ProjectModel.ProjectContext.<CreateContextForEachFramework>d__45.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at NuGet.Frameworks.FrameworkReducer.GetNearestInternal(NuGetFramework framework, IEnumerable`1 possibleFrameworks)
   at NuGet.Frameworks.FrameworkReducer.GetNearest(NuGetFramework framework, IEnumerable`1 possibleFrameworks)
   at NuGet.Frameworks.NuGetFrameworkUtility.GetNearest[T](IEnumerable`1 items, NuGetFramework framework, IFrameworkNameProvider frameworkMappings, IFrameworkCompatibilityProvider compatibilityProvider, Func`2 selector)
   at Microsoft.EntityFrameworkCore.Tools.DotNet.Internal.ProjectContextFactory.SelectCompatibleFramework(NuGetFramework target, IEnumerable`1 contexts)
   at Microsoft.EntityFrameworkCore.Tools.DotNet.Internal.ProjectContextFactory.Create(String filePath, NuGetFramework framework, String configuration, String outputDir)
   at Microsoft.EntityFrameworkCore.Tools.DotNet.Internal.DispatchOperationExecutor.Execute(CommandLineOptions options)
   at Microsoft.EntityFrameworkCore.Tools.DotNet.Program.Main(String[] args)
Could not find file 'C:\Projects\Pro\Server\Server.Grains\project.json'.
```

### Steps to reproduce
My .csproj file looks like this:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.5</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Globals.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.0" />
    <PackageReference Include="Microsoft.Orleans.Core" Version="2.0.0-preview2-201703021703" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="1.1.0" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql.Design" Version="1.1.0" />
    <PackageReference Include="protobuf-net" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Server.Interfaces\Server.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.1.0-*" />
  </ItemGroup>
</Project>
```

### Further technical details
EF Core version: 1.1.0-preview4-22752
Database Provider: Pomelo.EntityFrameworkCore.MySql
Operating system: Windows 10
IDE: VS 2017

**Comment by ZhaoXiangXML** [comment]
Package Management Console works for me, just not dotnet ef

**Comment by ZhaoXiangXML** [comment]
I switched to 1.0.0-msbuild3-final and it appears to be working

**Comment by bricelam** [comment]
You're using the wrong version of of the CLI tool. "Update" (downgrade?) it to 1.0.0.

```XML
<ItemGroup>
  <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet"
                          Version="1.0.0" />
</ItemGroup>
```

**Comment by Cnordbo** [comment]
Downgrading from 1.1.0 to 1.0.0 worked for me.
