### ISSUE TITLE
Using async/await for calling stored procedures in entity framework core generates NullReferenceException

### ISSUE THREAD

**Issue by maclax** [dotnet/efcore#7953]
I'm trying to call stored procedure using async/await. On executing the application, it is throwing NullReferenceException.

StackTrace:

An unhandled exception occurred while processing the request.

NullReferenceException: Object reference not set to an instance of an object.
lambda_method

Stack Query Cookies Headers
NullReferenceException: Object reference not set to an instance of an object.
```
lambda_method
Shape
<_ShapedQuery>b__0
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
GetResult
MoveNext in TotalSalesContext.cs
            return await StoreCheckByDateData.FromSql
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
GetResult
MoveNext in TotalSalesRepository.cs
             return await _totalSalesContext.ExecuteStoreCheckQuery();
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
GetResult
MoveNext in AppController.cs
            return View(await _totalSalesRepository.GetStoreCheckData());
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
```
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , ValueBuffer )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.UnbufferedEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.AsyncQueryMethodProvider.<>c__DisplayClass3_0`1.<_ShapedQuery>b__0(ValueBuffer vb)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.<MoveNext>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.<MoveNext>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__129`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToArrayAsync>d__130`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MyStoreReports.Models.TotalSalesContext.<ExecuteStoreCheckQuery>d__15.MoveNext() in C:\Users\Maria.Clara\documents\visual studio 2015\Projects\MyStoreReports\src\MyStoreReports\Models\TotalSalesContext.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MyStoreReports.Models.TotalSalesRepository.<GetStoreCheckData>d__8.MoveNext() in C:\Users\Maria.Clara\documents\visual studio 2015\Projects\MyStoreReports\src\MyStoreReports\Models\TotalSalesRepository.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MyStoreReports.Controllers.Web.AppController.<ReportSalesbyBrand>d__7.MoveNext() in C:\Users\Maria.Clara\documents\visual studio 2015\Projects\MyStoreReports\src\MyStoreReports\Controllers\Web\AppController.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__6.MoveNext()
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to repoduce the issue.

Controller class:
```C#
[HttpGet]
        public async Task<IActionResult> ReportSalesbyBrand()
        {
            return View(await _totalSalesRepository.GetStoreCheckData());
        }
```
Repository:
```C#
public async Task<IEnumerable<StoreCheckByDate>> GetStoreCheckData()
        {
           
             return await _totalSalesContext.ExecuteStoreCheckQuery();
        }
```
DbContext:
```C#
public async Task<IEnumerable<StoreCheckByDate>> ExecuteStoreCheckQuery()
        {
            return await StoreCheckByDateData.FromSql
                ("exec dbo.StoreCheckByDate").ToArrayAsync(); ;
        }
```
### Further technical details
EF Core version: (found in project.json or packages.config)
"Microsoft.EntityFrameworkCore": "1.0.1",
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
"Microsoft.EntityFrameworkCore.SqlServer": "1.0.1",
Operating system: Windows 8.1
IDE: (e.g. Visual Studio 2015)

**Comment by ajcvickers** [comment]
@maclax This may be due to the data having null values when the CLR property type that value is going to is not nullable. Can you try updating to the latest version (1.1.1)? We made changes to produce better exception messages in cases like this.

**Comment by maclax** [comment]
@ajcvickers You're absolutely right. One of the entity member variables was returning null. When i updated the version to 1.1.1, the exception thrown was more specific. Many Thanks!!!!
