### ISSUE TITLE
The expression '[p].Name' passed to the Include operator could not be bound.

### ISSUE THREAD

**Issue by AndrewKralovec** [dotnet/efcore#7964]
Describe what is not working as expected.

I added EntityFramework to my asp.net core application. I have a method in my controller that queries my projects table. However, when i try to query my context with 2 includes (one for the project name and other one to get the hours worked on the project), i get the following error.  **Any idea what is causing this problem ?**

```
{System.InvalidOperationException: The expression '[p].Name' passed to the Include operator could not be bound.
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.<>c__DisplayClass41_0.<IncludeNavigations>b__1(IEnumerable`1 ps, IQuerySource _)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindPropertyExpressionCore[TResult](Expression propertyExpression, IQuerySource querySource, Func`3 propertyBinder)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindNavigationPathPropertyExpression[TResult](Expression propertyExpression, Func`3 propertyBinder)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.<IncludeNavigations>b__41_0(IncludeResultOperator includeResultOperator)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__3.MoveNext()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.ToList()
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__129`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TimeTracker.Controllers.ProjectController.<GetProjectsByDate>d__4.MoveNext()}
```

![image](https://cloud.githubusercontent.com/assets/6210337/24221834/ec14ce3e-0f1d-11e7-80c1-cfa4607eafb6.png)

### Steps to reproduce
Nothing complex here. Just make a query with two includes. 

ProjectController.cs 
```
        [HttpGet("[action]")]
        public async Task<IActionResult> GetProjectsByDate()
        {
            try
            {
                var min = new DateTime(2017, 3, 1); 
                var max = new DateTime(2017, 3, 15);
                var projects = await context.Projects
                    .Include(p => p.Name)
                    .Include(p => p.Hours)
                    .ToListAsync(); 
                return Json(projects);
            }
            catch (Exception ex)
            {
                return Json(ex);
            }
        }
```
Project.cs 
```
 public class Project
    {
        [Key]
        public int ID { get; set; }
        public int? TeamID { get; set; }
        public int? ManagerID { get; set; }
        public int? CreatedBy { get; set; }

        public string Name { get; set; }
        public string Details { get; set; }
        public double? Estimate { get; set; }
        public bool IsActive { get; set; }

        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public DateTime CreatedDate { get; set; }
 }
        [ForeignKey("TeamID")]
        public virtual Team Team { get; set; }
        [ForeignKey("ManagerID")]
        public virtual User Manager { get; set; }
        [ForeignKey("CreatedBy")]
        public virtual User Creator { get; set; }

        public virtual ICollection<Work> Hours { get; set; }


        public Project()
        {
            Hours = new List<Work>();
        }
    }
```

### Further technical details
EF Core version: (found in project.json or packages.config)

```
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Design": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
```

Database Provider: 
    **"Microsoft.EntityFrameworkCore.SqlServer": "1.0.0",**
Operating system: 
**Windows 7** 
IDE:
**Visual Studio 2015**

**Comment by pmiddleton** [comment]
.Include is only needed for preloading related entities or collections.  In your case you just need to select the columns into an anonymous type

```csharp
 var projects = await context.Projects
                        .Select(p => new { p.Name, p.Hours })
                        .ToListAsync() ;

```

**Comment by ajcvickers** [comment]
Include is designed to be used with navigation properties between entities, not scalar properties like "Name.
