### ISSUE TITLE
Simple mapping throwing index out of range exception

### ISSUE THREAD

**Issue by ChrisKlug** [dotnet/efcore#8002]
Mapping a couple of simple related entities does not work when the column name starts with a letter later than I in the alphabet.

I know it sounds stupid, but renaming the column, and updating the mapping to a column name that starts with A>I works. In my case, the column name SalesCountry fails, but renaming it to ASalesCompany gets it working...

The exception that is thrown is an index out of range

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index) ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at lambda_method(Closure , ValueBuffer )
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalMixedEntityEntry..ctor(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryFactory.NewInternalEntityEntry(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer valueBu
ffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryFactory.Create(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTrackingFromQuery(IEntityType baseEntityType, Object entity, ValueBuffer valueBuffer, ISet`1 handledForeignKeys)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityTrackingInfo.StartTracking(IStateManager stateManager, Object entity, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.StartTracking(Object entity, EntityTrackingInfo entityTrackingInfo)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.<>c__DisplayClass16_0`2.<_TrackEntities>b__0(TOut result)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.<MoveNext>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at EfRepro.Program.Main(String[] args)
```

### Steps to reproduce
A repro has been uploaded to [here](https://github.com/ChrisKlug/ef-problem-repro)

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2015 & Visua Studio Code

**Comment by ajcvickers** [comment]
@ChrisKlug I have not been able to reproduce the naming dependency, but there is something very strange in your model building for ProjectInfo, which may be the root cause. The entity type has three properties:
```C#
public int Id { get; private set; }
public Country SalesCountry { get; private set; }
public Country FiscalCountry { get; private set; }
```
But then the model configuration adds a new shadow property and makes it the key:
```C#
entity.Property<int>("_id")
    .ForSqlServerHasColumnName("Id")
    .ValueGeneratedOnAdd()
    .IsRequired();
entity.HasKey("_id");
```
This shadow property is mapped to the same column name that one of the non-shadow properties is using: 'Id'.

The interpretation of this should probably be that the "Id" property is mapped to some uniqueified column name, although I think we may have decided to punt on that since it didn't seem like a valuable scenario. But I suspect that is academic, because your database structure and the rest of your code indicates that you intended there to be only one Id column in your database.

I think it would be useful for you to explain what your intention was with the mapping code above rather than my making any more guesses. 😄

**Comment by ChrisKlug** [comment]
You are right! Damn it! I changed the id from being a shadow property to being an actual property, but apparently forgot to change the mapping properly. however, the error message with index out of range makes that VERY hard to figure out. Not too mention that for some reason,  that mapping issue causes me to not be able to map columns depending on the name of the column, which is very odd. 

You are saying that you are not able to repro the naming problem? On my machine, the column naming makes a huge difference. Not sure why, and it is obviously just a side effect, but still weird.

Even though correcting the binding seems to solve the problem, I think it would be awesome if it was possible to catch a problem like this and give a better error message. Index out of range is pretty much impossible to debug unfortunately...

**Comment by ajcvickers** [comment]
We discussed this in triage and decided that for now it is not worth investing time in detecting a better exception for this case. If it turns out that more people get into this state, then we will revisit how we handle this and express the error.
