### ISSUE TITLE
class library unable to load sqlite3

### ISSUE THREAD

**Issue by gforceg** [dotnet/efcore#8003]
I am following [this official tutorial](https://docs.microsoft.com/en-us/ef/core/get-started/netcore/new-db-sqlite) to start my EF Core app. Everything works fine until I break my project up into a solution with multiple projects. I'm placing all database (and EF Core) code into a Data project (class library). When I try to update the database, the CLI complains that it suddenly can't find sqlite3.

```
dotnet ef database update

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.95
Startup project 'Data.csproj' targets framework '.NETStandard'. This framework is not intended for execution and may fail to resolve runtime dependencies. If so, specify a different projec
t using the --startup-project option and try again.
System.DllNotFoundException: Unable to load DLL 'sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.Data.Sqlite.Interop.NativeMethods.Sqlite3_sqlite3.sqlite3_open_v2(IntPtr filename, Sqlite3Handle& ppDb, Int32 flags, IntPtr vfs)
   at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(String filename, Sqlite3Handle& ppDb, Int32 flags, String vfs)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to load DLL 'sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

I'm sure it has to do w/ the warning I'm seeing about the framework not being intended for execution but I'm only trying to get my database created from the command line.

The original project targets 'netcoreapp1.1' and it works perfectly. Below is its .csproj:
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.1" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.1" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />
  </ItemGroup>
</Project>
```

The new project is a class library targeting 'netstandard1.4'.

The new project's .csproj file reads:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="1.1.1" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Contracts\Contracts.csproj" />
  </ItemGroup>
</Project>
```

I'm sure I'm missing something really simple here but I don't know where else to look at this point.

Thanks!

### Further technical details
EF Core version: Microsoft.EntityFrameworkCore.Tools.DotNet 1.0.0 ? (I don't know if this is EF Core or just the tools... versions in dotnet core are confusing)
Database Provider:  Microsoft.EntityFrameworkCore.Sqlite
Operating system: Win 7
IDE: VS Code

**Comment by gforceg** [comment]
I went to the "driver" project of my solution and ran the dotnet ef commands. When I ran dotnet ef datbase update I got this message:
```
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:04.61
Your target project '#DRIVER#' doesn't match your migrations assembly 'Data'. Either change your target project or change your migrations assembly.
Change your migrations assembly by using DbContextOptionsBuilder. E.g. options.UseSqlServer(connection, b => b.MigrationsAssembly("#DRIVER#")). By default, the migrations assembly is the assembly containing the DbContext.
Change your target project to the migrations project by using the Package Manager Console's Default project drop-down list, or by executing "dotnet ef" from the directory containing the migrations project.
```

So it seems that I must change my "migrations assembly". The example used in the above output is for Sql whereas I'm using Sqlite. So I don't know if I can say:

```
options.UseSqlite(connection, b => b.MigrationsAssembly("#DRIVER#"))
```

If I even can, how do I specify to use the file: @"Data Source=mydata.db" ? Do I need yet another dbContext? Besides, I'm going to be using a service, (a class library) library to interact with the data.

I'm getting more confused.

**Comment by gforceg** [comment]
I was able to get it working by using the **--startup-project** option:

```
dotnet ef --startup-project ../Driver/Driver.csproj migrations add initial
dotnet ef --startup-project ../Driver/Driver.csproj database update
```

It didn't populate the database w/ my database seed though... I think that's something I did.

**Comment by gforceg** [comment]
I forgot to run my app for the first time to generate the seed data. It's all good in the hood now!
