### ISSUE TITLE
Column with name "column" is not defined on the local table "table"

### ISSUE THREAD

**Issue by gayan1991** [dotnet/efcore#8017]
I am having a real issue with an error. It is partially killing me.

I am getting an error saying System.InvalidOperationExceptionColumn with name 'WOType' is not defined on the local table 'WorkOrder' when user is trying to insert data to sqlite DB. However, when I try to create this error by debuggin, It is working smoothly. Normally, we deploy a package through VSTS. The package comes from the VSTS gives this issue. A detailed error has been caught using xamarin insights and i have copied the whole error below. Please, take a look at let me know.

Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceLocalStoreExceptionFailed to perform operation on local store.
at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncContext+<>c__DisplayClass67+<<ExecuteOperationAsync>b__66>d__69.MoveNext () [0x00198] in <filename unknown>:0

at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncContext.<ExecuteOperationSafeAsync>d__6f.MoveNext()

at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncContext.<InsertAsync>d__e.MoveNext()

at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncTable.<InsertAsync>d__0.MoveNext()

at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncTable<T>.<InsertAsync>d__7.MoveNext()

at Retread.CR.Mobile.Data.Repository.WorkOrderRepository.<CreateAsync>d__0.MoveNext()

at Retread.CollectorReceiver.Mobile.Services.WorkOrderService.<AddNewWorkOrder>d__9.MoveNext()

at Retread.CR.Mobile.Mvvm.ViewModels.WorkOrderViewModel.<AddNewWorkOrder>d__154.MoveNext()

at Android.App.SyncContext.<Post>c__AnonStorey0.<>m__0()

at Java.Lang.Thread.RunnableImplementor.Run()

at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)

at (wrapper dynamic-method) System.Object:60a89bb9-8f70-420d-b291-b2ed8c9e4724 (intptr,intptr)

System.InvalidOperationExceptionColumn with name 'WOType' is not defined on the local table 'WorkOrder'.
at Microsoft.WindowsAzure.MobileServices.SQLiteStore.MobileServiceSQLiteStore.UpsertAsyncInternal(string tableName, IEnumerable<_> items, bool ignoreMissingColumns)

at Microsoft.WindowsAzure.MobileServices.SQLiteStore.MobileServiceSQLiteStore.UpsertAsync(string tableName, IEnumerable<_> items, bool ignoreMissingColumns)

at Microsoft.WindowsAzure.MobileServices.Sync.LocalStoreProxy.UpsertAsync(string tableName, IEnumerable<_> items, bool ignoreMissingColumns)

at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceLocalStoreExtensions.UpsertAsync(IMobileServiceLocalStore store, string tableName, JObject item, bool fromServer)

at Microsoft.WindowsAzure.MobileServices.Sync.InsertOperation.<ExecuteLocalAsync>d__0.MoveNext()

at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncContext+<>c__DisplayClass67+<<ExecuteOperationAsync>b__66>d__69.MoveNext () [0x00171] in <filename unknown>:0

**Comment by ErikEJ** [comment]
This does not seem to relate to Entity Framework Core !?
