### ISSUE TITLE
EF's exception handling isn't correct

### ISSUE THREAD

**Issue by stevenxi** [dotnet/efcore#8055]
It's a bit complicated problem:

1. We found 2 'impossible' errors in our code:
   a. An 'Select' query should always returns value, returns 0 result.
   b. An 'Count' query, throws no element exception.

2. We did investigation, the reason for those errors are because EF executed a data reader, has no result. But for that query, there MUST be result in it.

3. We tried to add log to trap the problem. The logger uses DatabaseLogFormatter, overwrite LogResult<TResult>(command, interceptionContext) The log shows very strange result. 
   a. A count query (attached below) returns no result, interceptionContext.Exception is null. But meanwhile outter calling method gets SQL's dead lock exception.
  b. Same query, no result returns, interceptionContext.Exception is null.  The outter calling method does not get dead lock or another other SQL's exception. But because the IQueryable.Count gets result by .Single(), it throws no element exception.

4. This issue happens occasionally, so far cannot find a way to garentee reproduce it.

In Summary:
Suspect some time EF does not throw, or even catch the underlying SQL exception.

Since it only happens to the production environment, we cannot always turn the SQL profiler on and trap the query from SQL Server side.

===================================================
EF Query:
context.FileRecords.Count(f => openStatus.Contains(f.FileStatusId) && f.UserId == userId)

EF generated SQL query:

SELECT 
    [GroupBy1].[A1] AS [C1]
    FROM ( SELECT 
        COUNT(1) AS [A1]
        FROM [dbo].[FileRecords] AS [Extent1]
        WHERE ([Extent1].[FileStatusId] IN (1000, 2000, 5000)) AND ([Extent1].[UserId] = @p__linq__0)
    )  AS [GroupBy1]

====================================================
Dead lock (lock timeout) exception (when available):

System.Data.Entity.Core.EntityCommandExecutionException: An error occurred while reading from the store provider's data reader. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Transaction (Process ID 70) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.Read()
   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.StoreRead()
   --- End of inner exception stack trace ---
   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.HandleReaderException(Exception e)
   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.StoreRead()
   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.SimpleEnumerator.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Koala.Web.Controllers.UserMessageAndEvent.UserMessageAndEventController.<>c__DisplayClass14_0.<RefreshEvent>b__0(Int32 userId) in C:\BuildAgent\work\50dd892818aa2a5a\src\Giove\Koala\Koala.Web\Controllers\UserMessageAndEvent\UserEvent.cs:line 134
   at Avocado.Common.Cache.WeakReferenceMemoryCache`2.GetValue(Func`2 loadData, TKey key) in C:\BuildAgent\work\50dd892818aa2a5a\src\Giove\Avocado\Avocado.Common\Cache\WeakReferenceMemoryCache.cs:line 107
   at Koala.Web.Controllers.UserMessageAndEvent.UserMessageAndEventController.RefreshEvent() in C:\BuildAgent\work\50dd892818aa2a5a\src\Giove\Koala\Koala.Web\Controllers\UserMessageAndEvent\UserEvent.cs:line 116
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)

====================================================
Count exception (when no sql exception):

System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)

=====================

EF is latest release version: 6.1.40302
MS SQL is Sql 2016, Azure VM image.

**Comment by ErikEJ** [comment]
This is the EF Core issue tracker, I think you should use this instead: https://github.com/aspnet/EntityFramework6

**Comment by stevenxi** [comment]
Ah, sorry. closing it.
