### ISSUE TITLE
Navs: Projecting nav from GJ QSRE broken

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#8183]
Similar to #7652
```c#
from c in context.Set<Customer>()
join o in context.Set<Order>()
on c.CustomerID equals o.CustomerID into g
where c.CustomerID == "ALFKI"
select new { c, g, Foo = g.Select(o => o.Customer) }
```
```
System.ArgumentException : Incorrect number of arguments supplied for call to method 'System.Collections.Generic.IEnumerable`1[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Specification.Tests.TestModels.Northwind.Customer,System.Collections.Generic.IEnumerable`1[Microsoft.EntityFrameworkCore.Specification.Tests.TestModels.Northwind.Order]]] _GroupJoin[Customer,Order,String,TransparentIdentifier`2](Microsoft.EntityFrameworkCore.Query.RelationalQueryContext, System.Collections.Generic.IEnumerable`1[Microsoft.EntityFrameworkCore.Storage.ValueBuffer], Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.IShaper`1[Microsoft.EntityFrameworkCore.Specification.Tests.TestModels.Northwind.Customer], Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.IShaper`1[Microsoft.EntityFrameworkCore.Specification.Tests.TestModels.Northwind.Order], System.Func`2[Microsoft.EntityFrameworkCore.Specification.Tests.TestModels.Northwind.Order,System.String], System.Func`3[Microsoft.EntityFrameworkCore.Specification.Tests.TestModels.Northwind.Customer,System.Collections.Generic.IEnumerable`1[Microsoft.EntityFrameworkCore.Specification.Tests.TestModels.Northwind.Order],Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Specification.Tests.TestModels.Northwind.Customer,System.Collections.Generic.IEnumerable`1[Microsoft.EntityFrameworkCore.Specification.Tests.TestModels.Northwind.Order]]])'
	at System.Linq.Expressions.Expression.ValidateArgumentCount(MethodBase method, ExpressionType nodeKind, Int32 count, ParameterInfo[] pis)
	at System.Linq.Expressions.Expression.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments)
	at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
	at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression[] arguments)
	C:\Dev\github\aspnet\EntityFramework\src\EFCore.Relational\Query\RelationalQueryModelVisitor.cs(1526,0): at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.TryFlattenGroupJoin(GroupJoinClause groupJoinClause, QueryModel queryModel, Int32 index, Int32 previousProjectionCount, ParameterExpression previousParameter, Dictionary`2 previousMapping)
	C:\Dev\github\aspnet\EntityFramework\src\EFCore.Relational\Query\RelationalQueryModelVisitor.cs(524,0): at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitGroupJoinClause(GroupJoinClause groupJoinClause, QueryModel queryModel, Int32 index)
	at Remotion.Linq.Clauses.GroupJoinClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
	at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
	at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
	C:\Dev\github\aspnet\EntityFramework\src\EFCore\Query\EntityQueryModelVisitor.cs(696,0): at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
	C:\Dev\github\aspnet\EntityFramework\src\EFCore.Relational\Query\RelationalQueryModelVisitor.cs(346,0): at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
	C:\Dev\github\aspnet\EntityFramework\src\EFCore\Query\EntityQueryModelVisitor.cs(206,0): at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
	C:\Dev\github\aspnet\EntityFramework\src\EFCore\Storage\Database.cs(70,0): at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
	--- End of stack trace from previous location where exception was thrown ---
```
```
  Compiling query model: 
  'from Customer c in DbSet<Customer>
  join Order o in DbSet<Order>
  on [c].CustomerID equals [o].CustomerID into g
  where [c].CustomerID == "ALFKI"
  select new <>f__AnonymousType4<Customer, IEnumerable<Order>, IEnumerable<Customer>>(
      [c], 
      [g], 
  
          from Order o in [g]
          select [o].Customer
  )'
  
  Optimized query model: 
  'from Customer c in DbSet<Customer>
  join Order o in DbSet<Order>
  on [c].CustomerID equals [o].CustomerID into g
  where [c].CustomerID == "ALFKI"
  select new <>f__AnonymousType4<Customer, IEnumerable<Order>, IEnumerable<Customer>>(
      [c], 
      [g], 
  
          from Order o in [g]
          join Customer o.Customer in DbSet<Customer>
          on Property([o], "CustomerID") equals Property([o.Customer], "CustomerID") into o.Customer_group
          from Customer o.Customer in 
              (from Customer o.Customer_groupItem in [o.Customer_group]
              select [o.Customer_groupItem]).DefaultIfEmpty()
          select [o.Customer]
  )'
```

**Comment by anpete** [comment]
Turned out to be a local problem.
