### ISSUE TITLE
InvalidOperationException when calling SaveChanges when inner collections are modified and not root object

### ISSUE THREAD

**Issue by cdie** [dotnet/efcore#8187]
When I try to update a root objet that contains many sub-entities, I have an InvalidOperationException.

```
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.NavigationCollectionChanged(InternalEntityEntry entry, INavigation navigation, IEnumerable`1 added, IEnumerable`1 removed)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.NavigationCollectionChanged(InternalEntityEntry entry, INavigation navigation, IEnumerable`1 added, IEnumerable`1 removed)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectNavigationChange(InternalEntityEntry entry, INavigation navigation)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at TestApp.Program.Main(String[] args) in C:\Users\Mégane\Source\Repos\cdie-ef-test-1\TestApp\TestApp\Program.cs:line 53
```

We're working with on an EDA (Event Driven Architecture) project on a WPF app, so we have one context per view (defined in Autofac Lifetime scope), which is resolved when we need data access.

We're using Automapper to switch from Domain object to Persistence and vice-versa

I've made a little sample project that show the kind of issue we're encountering... Although we're using TrackGraph method, it appears that the tracking method is not called on the second time, and I don't know why (because we're first calling it on a Detached entity). 

In my repo (https://github.com/cdie/cdie-ef-test-1) you can find the sample app that demonstrat our issue.

Please also note that we are not using CurrentValues.SetValues(object) method because it delete all our linked entities and related collections.

### Further technical details
EF Core version: 1.1.1
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: VS 2017

**Comment by ajcvickers** [comment]
@cdie TrackGraph is designed to traverse the graph of un-tracked entities so that EF can start tracking them. The call to TrackGraph in your repro project is being made on an already tracked entity, and hence TrackGraph has nothing to do.

Also, the way you use AutoMapper in your repro results in duplicate object instances being created. This is almost certainly not a good idea.

**Comment by cdie** [comment]
@ajcvickers I don't see where I have duplicate object instances ? 
My AEntity represents domain entity and ADbEntity persistence entity to persist only what is necessary.
I explicitly use mapper.Map(a, persist) to fill exsting persistable object instead of creating a new one in this example.

The problem here is that an instance into my collection is currently not tracked by EF, and without having to specificaly know the object hierarchy, I don't know how to reached them to mark them as inserted/updated/

Also, in my real project, I just retrieve the one root entity that already exists from Db, and fill it with AutoMapper the same way. I don't really see a way to do it otherwise ... Or maybe this is something I don't know how to do with EF...

**Comment by ajcvickers** [comment]
@cdie Duplicate object instances: look at the collection on persist after the call to `mapper.Map(a, persist);`

**Comment by cdie** [comment]
@ajcvickers Thanks a lot, I haven't notice this!!

For anyone who might look after this kind of issue after, I've used https://github.com/AutoMapper/AutoMapper.Collection to keep my objects references (and I also update my repo for this)
