### ISSUE TITLE
sum of collection specified cast is not valid 

### ISSUE THREAD

**Issue by mojtabakaviani** [dotnet/efcore#8203]
following #7136 issue I testing with last dev build but raise exception yet.

linq:
```
var schools = db.Students.Select(p => new { 
      p.Id, 
      p.Name, 
      Score = p.Scores.Sum(s => (float?) s.Score) 
});
```
t-sql:
```
SELECT [p].[Id], [p].[Name], (
                SELECT SUM([s].[Score])
                FROM [Scores] AS [s]
                WHERE [p].[Id] = [s].[StudentId]
            )
            FROM [Students] AS [p]
```

exception:
```
fail: Microsoft.EntityFrameworkCore.Query[1]
      An exception occurred in the database while iterating the results of a query.
      System.InvalidCastException: Specified cast is not valid.
         at lambda_method(Closure , QueryContext , TransparentIdentifier`2 )
         at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
         at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
         at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
System.InvalidCastException: Specified cast is not valid.
   at lambda_method(Closure , QueryContext , TransparentIdentifier`2 )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()

```

**Comment by maumar** [comment]
@mojtabakaviani I reactivated the original issue. Closing this as a duplicate. Thanks for following up!
