### ISSUE TITLE
Could not load file or assembly 'Microsoft.EntityFrameworkCore.Design, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by arame3333** [dotnet/efcore#8241]
I am trying to reverse engineer an existing database in EF Core in VS 2017.
So I type the scaffold command and this happens;
PM> **Scaffold-DbContext -Connection "Data Source=SQL_xxx;Initial Catalog=Survey;Integrated Security=True" -Provider "System.Data.EntityClient" -Context "MSurveyEntities" -Tables "Property, PropertyContract" -VERBOSE**
Using project 'Properties.Data'.
Using startup project 'Properties.API'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile "C:\Users\slartibartfast\Documents\Visual Studio 2017\Projects\SIR\SIR\bin\Debug\netcoreapp1.1\Properties.API.deps.json" --additionalprobingpath C:\Users\slartibartfast\.nuget\packages --runtimeconfig "C:\Users\slartibartfast\Documents\Visual Studio 2017\Projects\SIR\SIR\bin\Debug\netcoreapp1.1\Properties.API.runtimeconfig.json" C:\Users\slartibartfast\.nuget\packages\microsoft.entityframeworkcore.tools\1.1.0\tools\netcoreapp1.0\ef.dll dbcontext scaffold "Data Source=SQL_xxx;Initial Catalog=Survey;Integrated Security=True" System.Data.EntityClient --json --context MSurveyEntities --table "Property, PropertyContract" --verbose --no-color --prefix-output --assembly "C:\Users\slartibartfast\Documents\Visual Studio 2017\Projects\SIR\SIR\bin\Debug\netcoreapp1.1\Properties.Data.dll" --startup-assembly "C:\Users\slartibartfast\Documents\Visual Studio 2017\Projects\SIR\SIR\bin\Debug\netcoreapp1.1\Properties.API.dll" --project-dir "C:\Users\slartibartfast\Documents\Visual Studio 2017\Projects\SIR\Properties.Data" --content-root "C:\Users\slartibartfast\Documents\Visual Studio 2017\Projects\SIR\SIR" --data-dir "C:\Users\slartibartfast\Documents\Visual Studio 2017\Projects\SIR\SIR\bin\Debug\netcoreapp1.1\\" --root-namespace Properties.Data
Using assembly 'Properties.Data'.
Using startup assembly 'Properties.API'.
Using application base 'C:\Users\slartibartfast\Documents\Visual Studio 2017\Projects\SIR\SIR\bin\Debug\netcoreapp1.1'.
Using content root 'C:\Users\slartibartfast\Documents\Visual Studio 2017\Projects\SIR\SIR'.
Using root namespace 'Properties.Data'.
Using project directory 'C:\Users\slartibartfast\Documents\Visual Studio 2017\Projects\SIR\Properties.Data'.
Using data directory 'C:\Users\slartibartfast\Documents\Visual Studio 2017\Projects\SIR\SIR\bin\Debug\netcoreapp1.1\'.
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.EntityFrameworkCore.Design, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Microsoft.EntityFrameworkCore.Design, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.EntityFrameworkCore.Tools.ReflectionOperationExecutor..ctor(String assembly, String startupAssembly, String projectDir, String contentRootPath, String dataDirectory, String rootNamespace, String environment)
   at Microsoft.EntityFrameworkCore.Tools.Commands.ProjectCommandBase.CreateExecutor()
   at Microsoft.EntityFrameworkCore.Tools.Commands.DbContextScaffoldCommand.Execute()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
**Could not load file or assembly 'Microsoft.EntityFrameworkCore.Design, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.**

Having searched on what might cause this error, I change my scproj file as follows;
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.0" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />
  </ItemGroup>

</Project>
This was meant to be a fix. However I still have the same problem.
I am new to this. I understand that if I close my solution and then reopen it, it will restore my NUGET packages which I tried but it made no difference.
I got an error message when I tried to install Microsoft.EntityFrameworkCore.Tools.DotNet via NUGET, and my search suggested the workaround was to type the reference directly in the CSProj file, which is what I did. However I do not see it under the NUGET node.

**Comment by lajones** [comment]
Your provider is wrong - you need to point to the name of the database provider for the kind of database you are pointing to e.g. `Microsoft.EntityFrameworkCore.SqlServer`. The [docs](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell) will help you here. Note: if you are using SQL Server you will need to install the `Microsoft.EntityFrameworkCore.SqlServer.Design` package into you project to make this work.

Closing as I think I've answered the question. But feel free to re-open if you have problems.

**Comment by arame3333** [comment]
I changed the provider as specified but I still get the same error.
And my csproj, which I meant to paste before looks like this;
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.0" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />
  </ItemGroup>

</Project>

**Comment by bricelam** [comment]
> Using startup project 'Properties.API'.

Is this line in the output expected? Or did you intend to run with `-StartupProject Properties.Data`?

**Comment by arame3333** [comment]
That was a mistake I made. I corrected it and I get the same error;
C:\Users\geoffreypayne\.nuget\packages\microsoft.entityframeworkcore.tools\1.1.0\tools\net451\ef.exe dbcontext scaffold "Data Source=SQL_xxx;Initial Catalog=Survey;Integrated Security=True" System.Data.EntityClient --json --context MSurveyEntities --table "Property, PropertyContract" --verbose --no-color --prefix-output --assembly "C:\Users\geoffreypayne\Documents\Visual Studio 2017\Projects\SIR\Properties.EF6\bin\Debug\Properties.EF6.dll" --startup-assembly "C:\Users\geoffreypayne\Documents\Visual Studio 2017\Projects\SIR\Properties.EF6\bin\Debug\Properties.EF6.dll" --project-dir "C:\Users\geoffreypayne\Documents\Visual Studio 2017\Projects\SIR\Properties.EF6\\" --content-root "C:\Users\geoffreypayne\Documents\Visual Studio 2017\Projects\SIR\Properties.EF6\\" --data-dir "C:\Users\xxx\Documents\Visual Studio 2017\Projects\SIR\Properties.EF6\bin\Debug\\" --root-namespace Properties.EF6
Using assembly 'Properties.EF6'.
Using startup assembly 'Properties.EF6'.
Using application base 'C:\Users\xxx\Documents\Visual Studio 2017\Projects\SIR\Properties.EF6\bin\Debug'.
Using content root 'C:\Users\xxx\Documents\Visual Studio 2017\Projects\SIR\Properties.EF6\'.
Using root namespace 'Properties.EF6'.
Using project directory 'C:\Users\xxx\Documents\Visual Studio 2017\Projects\SIR\Properties.EF6\'.
Using data directory 'C:\Users\xxx\Documents\Visual Studio 2017\Projects\SIR\Properties.EF6\bin\Debug\'.
Using configuration file 'C:\Users\xxx\Documents\Visual Studio 2017\Projects\SIR\Properties.EF6\bin\Debug\Properties.EF6.dll.config'.
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.EntityFrameworkCore.Design' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.EntityFrameworkCore.Design'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at Microsoft.EntityFrameworkCore.Tools.AppDomainOperationExecutor..ctor(String assembly, String startupAssembly, String projectDir, String contentRootPath, String dataDirectory, String rootNamespace, String environment)
   at Microsoft.EntityFrameworkCore.Tools.Commands.ProjectCommandBase.CreateExecutor()
   at Microsoft.EntityFrameworkCore.Tools.Commands.DbContextScaffoldCommand.Execute()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Could not load file or assembly 'Microsoft.EntityFrameworkCore.Design' or one of its dependencies. The system cannot find the file specified.

**Comment by petelopez** [comment]
I had the same issue and it turned out to be my startup project... See here: https://github.com/aspnet/EntityFramework/issues/7977

Additionally, in the docs, one of the params is the StartupProject: https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell

This could have been made a little clearer.

**Comment by bricelam** [comment]
I've filed #8354 to improve this experience by helping users diagnose why they're getting this error.
