### ISSUE TITLE
Scaffolded Controller throws exception for already tracked item (PUT Method)

### ISSUE THREAD

**Issue by h4ck-rOOt** [dotnet/efcore#8321]
During the implementation of a REST-API with EF Core and ASP.NET Core, i found some strange behavior of the "Entry" function in DbContext. After updating some values of the same object (with id 1), EF Core throws an exception...

```
Exception message: The instance of entity type 'LectureItem' cannot be tracked because antoher instance of this type with the same key is already being tracked. [...]
Stack trace:
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HL4E5H3CNDV4": An unhandled exception was thrown by the application.
System.InvalidOperationException: The instance of entity type 'LectureItem' cannot be tracked because another instance of this type with the same key is already being tracked. When adding new entities, for most key types a unique temporary key value will be created if no key is set (i.e. if the key property is assigned the default value for its type). If you are explicitly setting key values for new entities, ensure they do not collide with existing entities or temporary values generated for other new entities. When attaching existing entities, ensure that only one entity instance with a given key value is attached to the context.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at ProjectAPI.Controllers.LectureController.<PutLectureItem>d__4.MoveNext() in c:\users\tobias\documents\visual studio 2017\Projects\ProjectAPI\ProjectAPI\Controllers\LectureController.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 5263.4167ms 500
```

### Steps to reproduce

First of all i have two models called "LectureItem" and "PackageItem" used in my DbContext:
``` c#
public class APIDatabaseContext : DbContext
{
    public DbSet<LectureItem> Lectures { get; set; }
    public DbSet<PackageItem> Packages { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite("Filename=./packages.db");
    }
}

public class LectureItem
{
    [Key]
    public int ID { get; set; }

    public string Name { get; set; }
    public string Short { get; set; }

    public List<PackageItem> Contents { get; set; }
}

public class PackageItem
{
    [Key]
    public int ID { get; set; }
    public string Name { get; set; }
    public int Version { get; set; }

    public string InstallAction { get; set; }
    public string RemoveAction { get; set; }

    public List<PackageItem> Dependencies { get; set; }
}
```

I want to change some of the properties using http put method and vs2017 scaffolded a controller implementation, looking like this:

``` c#
namespace ProjectAPI.Controllers
{
    [Produces("application/json")]
    [Route("api/Lecture")]
    public class LectureController : Controller
    {
        private readonly APIDatabaseContext _context;

        public LectureController(APIDatabaseContext context)
        {
            _context = context;
        }

        // GET: api/Lecture
        [HttpGet]
        public IEnumerable<LectureItem> GetLectures()
        {
            return _context.Lectures;
        }

        // GET: api/Lecture/5
        [HttpGet("{id}")]
        public async Task<IActionResult> GetLectureItem([FromRoute] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var lectureItem = await _context.Lectures.SingleOrDefaultAsync(m => m.ID == id);

            if (lectureItem == null)
            {
                return NotFound();
            }

            return Ok(lectureItem);
        }

        // PUT: api/Lecture/5
        [HttpPut("{id}")]
        public async Task<IActionResult> PutLectureItem([FromRoute] int id, [FromBody] LectureItem lectureItem)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if(id != lectureItem.ID)
            {
                return BadRequest();
            }

            _context.Entry(lectureItem).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!LectureItemExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Lecture
        [HttpPost]
        public async Task<IActionResult> PostLectureItem([FromBody] LectureItem lectureItem)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            _context.Lectures.Add(lectureItem);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetLectureItem", new { id = lectureItem.ID }, lectureItem);
        }

        // DELETE: api/Lecture/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteLectureItem([FromRoute] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var lectureItem = await _context.Lectures.SingleOrDefaultAsync(m => m.ID == id);
            if (lectureItem == null)
            {
                return NotFound();
            }

            _context.Lectures.Remove(lectureItem);
            await _context.SaveChangesAsync();

            return Ok(lectureItem);
        }

        private bool LectureItemExists(int id)
        {
            return _context.Lectures.Any(e => e.ID == id);
        }
    }
}
```
I've created an object with the some properties using postman:
``` json
{
	"Name": "Test",
	"Short": "TST",
	"Contents": []
}
```
Next step is changing some of the values through http put to:
``` json
{
	"ID": 1,
	"Name": "Test 2",
	"Short": "TST",
	"Contents": []
}
```

This change is successful, but trying to apply the same change through http put or any other change to the object with id 1 will result in an exception. Repeating this http put will cause the exception to trigger, no matter what the changes are.

I think that the Entry function should check if an item already exists due to change management and replace this with the newer item in change tracking. Maybe the Entry function is misused here!? The behavior i would expect is to replace the current item (if it exists in db). 

Any help will be appreciated.

### Further technical details
EF Core version: 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Win 10
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment]
@h4ck-rOOt The context can only track a single instance of any given entity. If you have an instance that is already being tracked, then you must decide how to merge the two instances into one--for example, copy the property values from one into the other. (There are some methods to help with these things if you drill down into the EntityEntry API.)

As to why the context is already tracking an instance of this entity, it could be due to other things happening in the same request that are not immediately apparent from your code. Or it could be that the lifetime of your DbContext instance is too long? If you are not already, then consider scoping it to the request.

**Comment by h4ck-rOOt** [comment]
@ajcvickers thanks for your quick reply. The problem was using a list of PackageItem's in LectureItem object. Since i've been using a one to many or many to many relation EF Core can't handle this case properly using Entry-Method. So i changed a bit of my code and used Update() on a previously retrieved entity object.

The suggested changes (set DbContext lifecycle to scoping or transient) had no effect. 

Thanks again for your time!
