### ISSUE TITLE
Tools: .NET Standard 2.0 Class Libraries (without a Startup project) don't work

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#8344]
Using the tools (`dotnet ef` or PMC) on a `netstandard2.0` class library project (without a concrete startup project) will throw the following exception.

    System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
    File name: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
       at ClassLibrary1.Context2.OnConfiguring(DbContextOptionsBuilder options)
       at Microsoft.EntityFrameworkCore.DbContext.InitializeServices()
       at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
       at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
       at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
       at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
       at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
       at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.GetMigrations(String contextType)
       at Microsoft.EntityFrameworkCore.Design.OperationExecutor.GetMigrationsImpl(String contextType)
       at Microsoft.EntityFrameworkCore.Design.OperationExecutor.GetMigrations.<>c__DisplayClass0_1.<.ctor>b__0()
       at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass4_0`1.<Execute>b__0()
       at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)

In order to make this work, we need to make `ef.exe` cross-target `netcoreapp2.0`.

Workaround
----------
There are two ways to workaround the issue:
* Make your library cross-target `netcoreapp2.0`:
    ```XML
    <TargetFrameworks>netcoreapp2.0;netstandard2.0</TargetFrameworks>
    ````
* Use a `net461` or `netcoreapp2.0` startup project:
    ```
    dotnet ef database update --startup-project ../MyConsoleApp
    ```

**Comment by bricelam** [comment]
Hmm, after updating to use the same trick we used on netstandard1.x (running on netcoreapp), it still doesn't work. You just get a different exception:

    Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Linq, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
       at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Argument(String name, String description, Action`1 configuration, Boolean multipleValues)
       at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Argument(String name, String description, Boolean multipleValues)
       at Microsoft.EntityFrameworkCore.Tools.Commands.DatabaseUpdateCommand.Configure(CommandLineApplication command)
       at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Command(String name, Action`1 configuration, Boolean throwOnUnexpectedArg)
       at Microsoft.EntityFrameworkCore.Tools.Commands.DatabaseCommand.Configure(CommandLineApplication command)
       at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Command(String name, Action`1 configuration, Boolean throwOnUnexpectedArg)
       at Microsoft.EntityFrameworkCore.Tools.Commands.RootCommand.Configure(CommandLineApplication command)
       at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)

We'll need to do some work to support these. Effectively, we'll need to target `netcoreapp2.0`, restore, and build on the fly.

**Comment by ajcvickers** [comment]
Closing this in favor #8452.
