### ISSUE TITLE
Inserting multiple records into a table with "ruled" field

### ISSUE THREAD

**Issue by MaximBalaganskiy** [dotnet/efcore#8417]
Inserting multiple records into a table with a user-defined type field with a rule fails.

The issue is caused by the `MERGE` statement which is incompatible with user-defined types with bound rules.
```
Exception message: 
    The target table 'Records' of the MERGE statement cannot have any enabled rules.  Found rule 'flag'.
Stack trace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
```

### Steps to reproduce
Script to create a database
```sql
CREATE RULE [dbo].[flag] 
AS
@value in ( 'Y', 'N' )
GO

CREATE TYPE [dbo].[flag] FROM [char](1) NOT NULL
GO

EXEC sys.sp_bindrule @rulename=N'[dbo].[flag]', @objname=N'[dbo].[flag]' , @futureonly='futureonly'
GO

CREATE TABLE [dbo].[Records] (
    [Id]   INT            IDENTITY (1, 1) NOT NULL,
    [Flag] flag NULL
);
GO
```

Program.cs
```c#
using Microsoft.EntityFrameworkCore;

namespace ConsoleApp1
{
	public class Record
	{
		public int Id { get; set; }
		public string Flag { get; set; }
	}

	public class Context : DbContext
	{
		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
			base.OnConfiguring(optionsBuilder);
			optionsBuilder.UseSqlServer("Server=(localdb)\\MSSQLLocalDB;Database=Issue8417;Trusted_Connection=True;");
		}

		public DbSet<Record> Records { get; set; }
	}

	class Program
	{
		static void Main(string[] args)
		{
			using (var c = new Context())
			{
				c.Records.AddRange(new Record[] { new Record { Flag = "Y" }, new Record { Flag = "N" } });
				c.SaveChanges();
			}
		}
	}
}
```

### Further technical details
EF Core version: 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: WIndows 10
IDE: Visual Studio 2017

**Comment by ErikEJ** [comment]
Rules are deprecated, better to use check constraints

**Comment by ajcvickers** [comment]
@MaximBalaganskiy We discussed this and at this time we don't plan to support rules. You should be able to work around the issue by turning of batching using something like:
```
.UseSqlServer(myConnectionString, b => b.MaxBatchSize(1));
```
If you still see issues after doing this, then please re-open with any additional details.
