### ISSUE TITLE
Unable to add migration with 2.0.0-preview2-006065 tooling

### ISSUE THREAD

**Issue by jcasale** [dotnet/efcore#8459]
Following the guide at [.NET Core - New database](https://docs.microsoft.com/en-us/ef/core/get-started/netcore/new-db-sqlite) with the exception that I create a lib and console project, I modify the csproj to target 2.0.0-preview1-final as the version for each dep, however I get an exception when creating the migration.

```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.EntityFrameworkCore.Design, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Microsoft.EntityFrameworkCore.Design, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.EntityFrameworkCore.Tools.ReflectionOperationExecutor..ctor(String assembly, String startupAssembly, String projectDir, String dataDirectory, String rootNamespace)
   at Microsoft.EntityFrameworkCore.Tools.Commands.ProjectCommandBase.CreateExecutor()
   at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsAddCommand.Execute()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
```

### Steps to reproduce

```bat
mkdir MyProject
cd MyProject

mkdir EfCoreUi
cd EfCoreUi
dotnet new console
dotnet restore

mkdir ..\EfCoreLib
cd ..\EfCoreLib
dotnet new library
rem Add code from guide into class.
rem Add deps in csproj, but choose 2.0.0-preview1-final as version for each.
dotnet restore
dotnet ef migrations add Initial -s ..\EfCoreUi\EfCoreUi.csproj
```

### Further technical details
EF Core version: 2.0.0-preview1-final
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10
IDE: None

Solution level `NuGet.Config` adding [https://dotnet.myget.org/F/dotnet-core/api/v3/index.json](https://dotnet.myget.org/F/dotnet-core/api/v3/index.json) as an additional feed.

**Comment by bricelam** [comment]
Can you verify that EfCoreLib.csproj has a `<ProjectReference>` to EfCoreLib.csproj?

**Comment by jcasale** [comment]
I have modified EfCoreUi.csproj as following:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EfCoreLib\EfCoreLib.csproj" />
  </ItemGroup>

</Project>
```
However I still get the same exception.

**Comment by bricelam** [comment]
And the Microsoft.EntityFrameworkCore.Design package is installed, right? Could you share your full solution so we can dig into this?

**Comment by jcasale** [comment]
Sure, it is pretty bare bones simple... [https://drive.google.com/open?id=0B8fVf3xIY_-YeWphNkI5ZVA1dnM](https://drive.google.com/open?id=0B8fVf3xIY_-YeWphNkI5ZVA1dnM)

**Comment by bricelam** [comment]
The `PrivateAssets="All"` on Microsoft.EntityFrameworkCore.Design is preventing it from being copied into EfCoreUi. There are two possible solutions:
* Move the `<PackageReference>` into the EfCoreUi project
* Remove `PrivateAssets="All"`

**Comment by jcasale** [comment]
Thank you, works as expected now.
