### ISSUE TITLE
A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.

### ISSUE THREAD

**Issue by leixu2txtek** [dotnet/efcore#8495]
I am built a web server with Nancy(.net core), and have a async action like this:

``` c#
Post("/resource", async args =>
{
    var course = Context.Items["course"] as Course;
    var user = (Context.CurrentUser.Identity as Identity).Info;

    #region 获取资源属性

    string title = Request.Form.title;
    long size = Request.Form.size;
    string url = Request.Form.url;
    string md5 = Request.Form.md5;

    if (string.IsNullOrWhiteSpace(title)) return new { code = -100, msg = "资源的标题不能为空" };
    if (string.IsNullOrWhiteSpace(url)) return new { code = -100, msg = "资源的地址不能为空" };
    if (string.IsNullOrWhiteSpace(md5)) return new { code = -100, msg = "资源的MD5不能为空" };

    #endregion

    var doc = new Resource();

    doc.Id = StringUtil.UniqueId();
    doc.DateCreated = DateTime.Now;
    doc.CreatorId = user.Id;

    doc.CourseId = course.Id;
    doc.Title = Path.GetFileNameWithoutExtension(title).Trim();
    doc.Url = url.Trim();
    doc.MD5 = md5.Trim();
    doc.Size = size;
    doc.Extension = Path.GetExtension(title);

    db_course.Resources.Add(doc);
    await db_course.SaveChangesAsync();

    return new { code = 1, msg = "上传成功" };
});
``` 
I Post more than 5 requests at one time, but got this error:

``` c#
System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__35.MoveNext()
```

### Further technical details
EF Core version:  1.1.2
Database Provider: Pomelo.EntityFrameworkCore.MySql 1.1.2
Operating system:  Windows 10 15063
IDE:  Visual Studio 2017

**Comment by anpete** [comment]
@leixu2txtek Make sure each request has a separate instance of db_course.
