### ISSUE TITLE
Exception: Could not load file or assembly System.Interactive.Async Version=3.0.3000.0

### ISSUE THREAD

**Issue by qmicron** [dotnet/efcore#8541]
I wonder, why Microsoft.EntityFrameworkCore Version=2.0.0.0 has dependency from System.Interactive.Async Version=3.0.3000.0. The Nuget doesn't contain this version at all. 

```
Exception message:
System.IO.FileLoadException: Could not load file or assembly 'System.Interactive.Async, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Interactive.Async, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.TryAddCoreServices()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkRelationalServicesBuilder.TryAddCoreServices()
   at Microsoft.Extensions.DependencyInjection.SqlServerServiceCollectionExtensions.AddEntityFrameworkSqlServer(IServiceCollection serviceCollection)
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.SqlServerOptionsExtension.ApplyServices(IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.ApplyServices(IDbContextOptions options, ServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_0.<GetOrAdd>b__2(Int64 k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at Powel.ProAdm.Model.DataContext..ctor(DbContextOptions options)
```
### Further technical details
EF Core version: 2.0.0-preview1-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Pro
IDE: (e.g. Visual Studio 2017)

**Comment by bricelam** [comment]
What type of project(s) are you using?

**Comment by bricelam** [comment]
Note, 3.0.3000.0 is the *assembly* version it's looking for which can be different from the NuGet package version.

**Comment by qmicron** [comment]
Our solution contains Windows Forms and Class Library projects. All projects based on old style csproj and they are using .net 4.7.

After EF 2.0.0-preview1-final installation we have

**package.config**
```
<package id="System.Interactive.Async" version="3.1.1" targetFramework="net452" requireReinstallation="true" />
```
**app.config**
```
<dependentAssembly>
        <assemblyIdentity name="System.Interactive.Async" publicKeyToken="94bc3704cddfc263" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.0.1000.0" newVersion="3.0.1000.0" />
</dependentAssembly>
```

**Comment by bricelam** [comment]
`requireReinstallation="true"` is a hint that you may need to run the following to get things working.

    Update-Package System.Interactive.Async -Reinstall

Your binding redirect also looks out of date. Try regenerating it with the following

    Add-BindingRedirect

**Comment by qmicron** [comment]
I have executed both commands:
```
PM> Update-Package System.Interactive.Async -Reinstall
PM> Get-Project –All | Add-BindingRedirect
```
Unfortunately, I still get the same exception. BindingRedirect is not changed as well

`<bindingRedirect oldVersion="0.0.0.0-3.0.1000.0" newVersion="3.0.1000.0" />`

**Comment by bricelam** [comment]
Does updating the 1000 to 3000 fix the issue?

Also, can you follow up on the [NuGet/Home](https://github.com/NuGet/Home) repo? Nothing here appears to be related to Entity Framework.

**Comment by qmicron** [comment]
Manually numbers changing did not help. 

You are right. This issue is not related to EF. 
Anyway thank you.

**Comment by vhalamzah** [comment]
everytime  i get to write  an xunit test or an integration test, i still get the same erro: "Message: System.IO.FileNotFoundException : Could not load file or assembly 'System.Interactive.Async, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. The system cannot find the file specified.". how do i get to solve this problem?
