### ISSUE TITLE
`Index out of range` Exception Raises its Head Again

### ISSUE THREAD

**Issue by jasel-lewis** [dotnet/efcore#8694]
I have an abstract base class `Segment` from which `FooSegment` and `BarSegment` inherit. With no special inheritance configuration, Entity Framework creates three tables in my database: Segment, FooSegment and BarSegment.

I prefer to use to use **Type-per-Concrete-Class** (TPC) inheritance, however, as I need only FooSegment and BarSegment to appear as tables in the database. The reason is the ultimate goal of configuring SQL Server's Full-Text Searching on these two tables, hence the need for all base-class properties to be mapped to the tables associated with the concrete classes.

The abstract class `Segment`, however, uses a composite key as it's part of a **one-to-zero-or-one** relationship with `RootEntity`. I believe this is what's confusing EF when I configure the mapping context to utilize TPC inheritance.

When configured for TPC and when adding the migration, I am receiving the error:
```
Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index
```
The error is occurring within the model configuration when I run `add-migration` (and even when running `update-database -targetmigration 0` in order to completely tear down the DB to then add the new migration which involves the TPC).

The stacktrace is:
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
    at System.Data.Entity.Core.Metadata.Edm.MetadataCollection`1.get_Item(Int32 index)
    at System.Collections.ObjectModel.ReadOnlyCollection`1.System.Collections.Generic.IList<T>.get_Item(Int32 index)
    at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
    at System.Data.Entity.ModelConfiguration.Configuration.Types.EntityTypeConfiguration.ConfigureDependentKeys(DbDatabaseMapping databaseMapping, DbProviderManifest providerManifest)
    at System.Data.Entity.ModelConfiguration.Configuration.Types.EntityTypeConfiguration.Configure(EntityType entityType, DbDatabaseMapping databaseMapping, DbProviderManifest providerManifest)
    at System.Data.Entity.ModelConfiguration.Configuration.ModelConfiguration.ConfigureEntityTypes(DbDatabaseMapping databaseMapping, ICollection`1 entitySets, DbProviderManifest providerManifest)
    at System.Data.Entity.ModelConfiguration.Configuration.ModelConfiguration.Configure(DbDatabaseMapping databaseMapping, DbProviderManifest providerManifest)
    at System.Data.Entity.DbModelBuilder.Build(DbProviderManifest providerManifest, DbProviderInfo providerInfo)
    at System.Data.Entity.DbModelBuilder.Build(DbConnection providerConnection)
    at System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext)
    at System.Data.Entity.Internal.RetryLazy`2.GetValue(TInput input)
    at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
    at System.Data.Entity.Internal.LazyInternalContext.get_ModelBeingInitialized()
    at System.Data.Entity.Infrastructure.EdmxWriter.WriteEdmx(DbContext context, XmlWriter writer)
    at System.Data.Entity.Utilities.DbContextExtensions.<>c__DisplayClass1.<GetModel>b__0(XmlWriter w)
    at System.Data.Entity.Utilities.DbContextExtensions.GetModel(Action`1 writeXml)
    at System.Data.Entity.Utilities.DbContextExtensions.GetModel(DbContext context)
    at System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationsConfiguration configuration, DbContext usersContext, DatabaseExistenceState existenceState, Boolean calledByCreateDatabase)
    at System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationsConfiguration configuration)
    at System.Data.Entity.Migrations.Design.MigrationScaffolder..ctor(DbMigrationsConfiguration migrationsConfiguration)
    at System.Data.Entity.Migrations.Design.ToolingFacade.ScaffoldRunner.Run()
    at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
    at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
    at System.Data.Entity.Migrations.Design.ToolingFacade.Run(BaseRunner runner)
    at System.Data.Entity.Migrations.Design.ToolingFacade.Scaffold(String migrationName, String language, String rootNamespace, Boolean ignoreChanges)
    at System.Data.Entity.Migrations.AddMigrationCommand.Execute(String name, Boolean force, Boolean ignoreChanges)
    at System.Data.Entity.Migrations.AddMigrationCommand.<>c__DisplayClass2.<.ctor>b__0()
    at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
```
In order to request TPC inheritance from EF, my `DbModelBuilder` configuration contains:
```c#
modelBuilder.Entity<FooSegment>()
    .Map(m =>
    {
        m.MapInheritedProperties();
        m.ToTable("FooSegment");
    });

modelBuilder.Entity<BarSegment>()
    .Map(m =>
    {
        m.MapInheritedProperties();
        m.ToTable("BarSegment");
    });
```
And, lastly, my entity classes (leaned, of course, to only include the properties necessary to understand the relationships):
```c#
public class RootEntity
{
    [Key]
    public int Id { get; set; }

    public virtual FooSegment { get; set; }
    public virtual BarSegment { get; set; }
}

public abstract class Segment
{
    [Key]
    [Column(Order = 1)]
    [ForeignKey("RootEntity")]
    public int RootEntityId { get; set; }

    [Key]
    [Column(Order = 2)]
    public SegmentType SegmentType { get; protected set; } = SegmentType.NoSegment;

    public virtual RootEntity RootEntity { get; set; }
    public virtual ICollection<Comment> Comments { get; set; } = new Collection<Comment>();
}

public class FooSegment : Segment
{
    public FooSegment()
    {
        this.SegmentType = SegmentType.Foo;
    }

    public FooStatus FooStatus { get; set; }

    /// <summary>
    /// Creates a uniquely indexable, identity column within the DB table.
    /// This field is present solely to allow configuration of SQL Server's
    /// full-text searching on the FooSegment table and is not to be used
    /// for anything else.
    /// </summary>
    [Index("FooSegmentUniqueIndex", IsUnique = true)]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IndexableUniqueIdForFullTextSearching { get; set; }
}

public class BarSegment : Segment
{
    public BarSegment()
    {
        this.SegmentType = SegmentType.Bar;
    }

    public BarStatus BarStatus { get; set; }

    /// <summary>
    /// Creates a uniquely indexable, identity column within the DB table.
    /// This field is present solely to allow configuration of SQL Server's
    /// full-text searching on the FooSegment table and is not to be used
    /// for anything else.
    /// </summary>
    [Index("BarSegmentUniqueIndex", IsUnique = true)]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IndexableUniqueIdForFullTextSearching { get; set; }
}

public class Comment
{
    [Key]
    public int Id { get; set; }

    [ForeignKey("Segment")]
    [Column(Order = 1)]
    public int RootEntityId { get; set; }

    [ForeignKey("Segment")]
    [Column(Order = 2)]
    public SegmentType SegmentType { get; set; }

    public virtual Segment Segment { get; set; }

    [ForeignKey("Parent")]
    public int? ParentId { get; set; }

    public virtual Comment Parent { get; set; }
    public virtual ICollection<Comment> Replies { get; set; }
}
```

**Note**: The same error is received even if I give unique names to the identity-creating properties of the `FooSegment` and `BarSegment` concrete classes (ie.: rename `IndexableUniqueIdForFullTextSearching` to `FooIndexableUniqueIdForFullTextSearching` and `BarIndexableUniqueIdForFullTextSearching` in the respective implementations).

I've [asked for assistance on SO](https://stackoverflow.com/questions/44328148/error-with-tpc-inheritance-in-entity-framework-using-a-composite-keyed-base-clas), but the more I think about it, the more I feel this is a bug within EF, hence bringing my concern here.

Thank you,
R. J.

### Further technical details
EF Core version: 6.1.3
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10 Enterprise
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment]
Moved to https://github.com/aspnet/EntityFramework6/issues/296
