### ISSUE TITLE
Migrate to asp.net core 2.0.0-preview1-002111-00

### ISSUE THREAD

**Issue by ranouf** [dotnet/efcore#8729]
Hi

I juste migrate my working project from asp.net core 1 to asp.net core 2.0.0-preview1-002111-00.

When I try to do a add migration i have an error (see text bellow).

It was perfectly working in the past, my guess is about Microsoft.EntityFrameworkCore.Tools which is supposed to generate the db update. 

How can I fix it?

Error:
```
PM> add-migration -v
cmdlet Add-Migration at command pipeline position 1
Supply values for the following parameters:
Name: Test
Using project 'X.Infrastructure'.
Using startup project 'X.Api'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile "C:\Users\X\Documents\Visual Studio 2017\Projects\X\X.Api\bin\Debug\netcoreapp2.0\X.Api.deps.json" --additionalprobingpath C:\Users\X\.nuget\packages --runtimeconfig "C:\Users\X\Documents\Visual Studio 2017\Projects\X\X.Api\bin\Debug\netcoreapp2.0\X.Api.runtimeconfig.json" C:\Users\X\.nuget\packages\microsoft.entityframeworkcore.tools\2.0.0-preview1-final\tools\netcoreapp1.0\ef.dll migrations add Test --json --verbose --no-color --prefix-output --assembly "C:\Users\X\Documents\Visual Studio 2017\Projects\X\X.Api\bin\Debug\netcoreapp2.0\X.Infrastructure.dll" --startup-assembly "C:\Users\X\Documents\Visual Studio 2017\Projects\X\X.Api\bin\Debug\netcoreapp2.0\X.Api.dll" --project-dir "C:\Users\X\Documents\Visual Studio 2017\Projects\X\X.Infrastructure" --root-namespace X.Infrastructure
Using assembly 'X.Infrastructure'.
Using startup assembly 'X.Api'.
Using application base 'C:\Users\X\Documents\Visual Studio 2017\Projects\X\X.Api\bin\Debug\netcoreapp2.0'.
Using working directory 'C:\Users\X\Documents\Visual Studio 2017\Projects\X\X.Api'.
Using root namespace 'X.Infrastructure'.
Using project directory 'C:\Users\X\Documents\Visual Studio 2017\Projects\X\X.Infrastructure'.
Finding DbContext classes...
Microsoft.EntityFrameworkCore.Design.OperationException: No parameterless constructor was found on 'AppDbContext'. Either add a parameterless constructor to 'AppDbContext' or add an implementation of 'IDbContextFactory<AppDbContext>' in the same assembly as 'AppDbContext'. ---> System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass10_2.<FindContextTypes>b__10()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass10_2.<FindContextTypes>b__10()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
No parameterless constructor was found on 'AppDbContext'. Either add a parameterless constructor to 'AppDbContext' or add an implementation of 'IDbContextFactory<AppDbContext>' in the same assembly as 'AppDbContext'.
```

**Comment by ranouf** [comment]
If I create a parameter less constructor on my dbContext, i have this error:
`No database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.`

But a parameter less constructor is not the solution I want.

**Comment by bricelam** [comment]
See #8328
