### ISSUE TITLE
EnsureCreated: Don't log exceptions which we are catching at info level

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#8791]
```
info: Microsoft.EntityFrameworkCore.Database.Command[200101]
      Executed DbCommand (29ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
      DROP DATABASE [_ModelApp];
fail: Microsoft.EntityFrameworkCore.Database.Connection[200004]
      An error occurred using the connection to database '_ModelApp' on server '(localdb)\mssqllocaldb'.
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "_ModelApp" requested by the login. The login failed.
Login failed for user 'REDMOND\smpatel'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open()
ClientConnectionId:dfc55180-2dfa-407b-bc31-e5fb6f1a1259
Error Number:4060,State:1,Class:11
```

**Comment by smitpatel** [comment]
dupe of #8651

**Comment by bricelam** [comment]
Are you sure this was a duplicate? I think this is a different, but similar issue.

**Comment by smitpatel** [comment]
@bricelam - Looks like need to update `EnsureCreated` path too.

**Comment by smitpatel** [comment]
#8651 fixed this too since `EnsureCreated` uses `Exists` path only.

**Comment by bricelam** [comment]
👍 Thanks for following up.
