### ISSUE TITLE
2.0.0 cannot map generic property

### ISSUE THREAD

**Issue by caleblloyd** [dotnet/efcore#8814]
I am working on upgrading the `Pomelo.EntityFrameworkCore.MySql` database provider to 2.0.0

We support mapping the generic `JsonObject` to a MySQL JSON type field.  Data is serialized when storing to the database and unserialized when loading from the database.  Models have these properties:

```
		// json not null
		[Required]
		public JsonObject<List<string>>               TypeJsonArray   { get; set; }

		[Required]
		public JsonObject<Dictionary<string, string>> TypeJsonObject  { get; set; }

		// json null
		public JsonObject<List<string>>               TypeJsonArrayN  { get; set; }

		public JsonObject<Dictionary<string, string>> TypeJsonObjectN { get; set; }
```

This works fine in EF Core 1.0.  When upgrading to 2.0, `dotnet ef migrations add initial` now throws an exception because it doesn't like the generic property:

```
System.InvalidOperationException: The property 'JsonObject<Dictionary<string, string>>.Object' could not be mapped, because it is of type 'Dictionary<string, string>' which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyMappingValidationConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.EnsureServices(IServiceProvider services)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

We have `JsonObject` in our [MySqlTypeMapper](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/dev/src/EFCore.MySql/Storage/Internal/MySqlTypeMapper.cs):

```
new RelationalTypeMapping("json", typeof(JsonObject<>), DbType.String, false, null);
```

How can we resolve this in our library code?  Or does EFCore need to change a check in `PropertyMappingValidationConvention.cs` to allow mapped generics through?

We are currently tracking `2.0.0-preview3-*` from your MyGet feed.

**Comment by caleblloyd** [comment]
Resolved with the help of @smitpatel thanks!

**Comment by richardsonvix** [comment]
I found same problem, but using oficial provider with Guid datatype mapped column, but in table using string.

Before I using PecaPoco (AsyncPoco), works fine when that materialize string content to Guid.
