### ISSUE TITLE
On linux, binding failed because of Invalid object name

### ISSUE THREAD

**Issue by singlewind** [dotnet/efcore#8860]
On windows, it doesn't have any issue. Only on linux, the sql generation works. Failed when calling ToListAsync. The database name doesn't have issue because it works on windows and it happened after fetch the data. I have similar entity with integer as id which works. I will try to change another EntityName

```
Exception message: System.Data.SqlClient.SqlException: Invalid object name 'Experiences'
Stack trace:

Microsoft.EntityFrameworkCore.Storage.IRelationalCommandBuilderFactory:Information: Executed DbCommand (70ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [x].[Id], [x].[CenterGeoJson], [x].[Disabled], [x].[Information], [x].[InformationHtml], [x].[Instruction], [x].[InstructionHtml], [x].[Publication], [x].[PublicationEdition], [x].[TrackGeoJson], [x].[TrackName], [x].[TrackNum]
FROM [Experiences] AS [x]
WHERE [x].[Id] IN (N'4WD_Adventures_Track_11')
ORDER BY [x].[Id]
Loaded '/root/.nuget/packages/system.diagnostics.stacktrace/4.3.0/lib/netstandard1.3/System.Diagnostics.StackTrace.dll'. Cannot find or open the symbol file.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/System.Reflection.Metadata.dll'. Cannot find or open the symbol file.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/System.IO.MemoryMappedFiles.dll'. Cannot find or open the symbol file.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/System.IO.UnmanagedMemoryStream.dll'. Cannot find or open the symbol file.
[41m[30mfail[39m[22m[49m: Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory[1]
      An exception occurred in the database while iterating the results of a query.
      System.Data.SqlClient.SqlException: Invalid object name 'Experiences'.
         at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__107_0(Task`1 result)
         at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
         at System.Threading.Tasks.Task.Execute()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__26.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<BufferlessMoveNext>d__9.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__6`2.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<MoveNext>d__8.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.<MoveNext>d__4.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at Microsoft.EntityFrameworkCore.Query.AsyncQueryMethodProvider.IncludeAsyncEnumerable`1.IncludeAsyncEnumerator`1.<MoveNext>d__7.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
      ClientConnectionId:48b1b12f-faa1-4d27-8e8e-b1f9654ca457
      Error Number:208,State:1,Class:16
```

### Steps to reproduce

```c#
var query = _db.Experiences.Where(x => ids.Contains(x.Id));
            return includeMedia
                ? await query.Include(x => x.Media).AsNoTracking().ToListAsync()
                : await query.AsNoTracking().ToListAsync();
```

### Further technical details
EF Core version: Microsoft.EntityFrameworkCore 1.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer 1.1.2
Operating system: Linux (docker image: microsoft/aspnetcore:1.1)
IDE: Visual Studio 2017

**Comment by singlewind** [comment]
This can be closed. I found the issue. It wasn't a bug
