### ISSUE TITLE
No database provider has been configured for this DbContext. Even after adding Dependancy Injection & Parameter less constructor

### ISSUE THREAD

**Issue by mehtanilay10** [dotnet/efcore#9027]
I am trying to Migrate my database using EF Core 2.0 but got bellow error.
After searching added Parameter-less constructor, OnModelCreating(), OnConfiguring() Methods but still unable to locate Database provider.. 
```
Exception message:
No database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.

Stack trace:
System.InvalidOperationException: No database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.Initialize(IServiceProvider scopedProvider, IDbContextOptions contextOptions, DbContext context)
   at Microsoft.EntityFrameworkCore.DbContext.InitializeServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Steps to reproduce
I am attaching Statup.cs, Context, appsetting.js files. I am able to perform other EF operations like add/remove in same project means connection string is perfect.

**Context**
```c#
 public class LibraryContext: DbContext
    {
        public LibraryContext(DbContextOptions<LibraryContext> options): base (options)
        {
        }

        public LibraryContext()
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            var builder = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true);
            IConfigurationRoot config = builder.Build();
            optionsBuilder.UseSqlServer(config.GetConnectionString("LibraryDemo1"));
        }

        public DbSet<Author> Author { get; set; }
        public DbSet<Book> Book { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
        }
    }
```

**appsettings.cs**
```javascript
"ConnectionStrings": {
    "LibraryDemo1": "Data Source=MNILAY-ENVY\\SQLEXPRESS;Initial Catalog=TutorialsTeam;Integrated Security=True"
  },
```

**Startup.cs**
```cs
// This method gets called by the runtime. Use this method to add services to the container.
public void ConfigureServices(IServiceCollection services)
{
    services.AddDbContext<LibraryContext>(option => 
        option.UseSqlServer(connectionString: Configuration.GetConnectionString("LibraryDemo1")));
    services.AddMvc();
}
```

### Further technical details
EF Core version: 2.0 Preview
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 15063.0
IDE: Visual Studio 2017 Preview
DotNet CLI Version: 2.0.0-preview1-005977

**Comment by bricelam** [comment]
What does your `Program.cs` look like? See [this draft announcement](https://github.com/aspnet/EntityFramework/issues/8923#issuecomment-310484670) for a possible solution.

**Comment by mehtanilay10** [comment]
Now i am updated Program.cs file with below code but still facing same error.
```cs
public static void Main(string[] args)
{
    BuildWebHost(args).Run();
}

public static IWebHost BuildWebHost(string[] args) =>
    new WebHostBuilder()
        .UseKestrel()
        .UseContentRoot(Directory.GetCurrentDirectory())
        .UseIISIntegration()
        .UseStartup<Startup>()
        .Build();
```

**Comment by mehtanilay10** [comment]
However putting below method in Context work fine! But i want to use connection from DI not write inside Context, it is possible?

```cs
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    if (!optionsBuilder.IsConfigured)
    {
        optionsBuilder.UseSqlServer(@"Data Source=MNILAY-ENVY\\SQLEXPRESS;Initial Catalog=TutorialsTeam;Integrated Security=True");
    }
}
```

**Comment by kalvarez2** [comment]
Hi
Is there any workaround that does not involve hard-coding the connection string on the code??
thanks

**Comment by mehtanilay10** [comment]
No! Previously i am trying to retrive from JSON file using configuration builder, it return null even if same name used and rebuild solution.
Now i am writing directly ot works!
Is there any restriction?

**Comment by bricelam** [comment]
`dotnet new mvc --auth Individual` will create a project that reads the connection string from config at design time. Compare your project to this to see what might be preventing this from happening

**Comment by ajcvickers** [comment]
Closing this as we don't think there is anything actionable on EF. ASP.NET Core uses different patterns for configuration and services, but once an app is updated to use those patterns, then EF will behave in the same way as before. There is no need to override OnConfiguring if it wasn't being overridden before, and EF does not play any part in getting configuration out of the JSON file.
