### ISSUE TITLE
2.0.0 NullReferenceException when using Expression Translators

### ISSUE THREAD

**Issue by caleblloyd** [dotnet/efcore#9037]
We are trying to upgrade our MySQL provider to 2.0.0.  All of our Expression Translator tests are resulting in this `NullReferenceException`

[Here are our Expression Translators](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/tree/dev/src/EFCore.MySql/Query/ExpressionTranslators/Internal)

[We add them in DI](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/73ca0e9224925e2e26532f9d1c07a2d9f2357872/src/EFCore.MySql/Extensions/MySqlServiceCollectionExtensions.cs#L50-L51)

[Here are all of the Expression Tests](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/dev/test/EFCore.MySql.FunctionalTests/Tests/Models/ExpressionTest.cs), they all fail with this `NullReferenceException`

The Exception is:

```
Failed   Pomelo.EntityFrameworkCore.MySql.PerfTests.Tests.Models.ExpressionTest.MySqlMathRoundTranslator
Error Message:
 System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:
   at Microsoft.EntityFrameworkCore.Query.ExpressionTranslators.SingleOverloadStaticMethodCallTranslator.Translate(MethodCallExpression methodCallExpression)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Microsoft.EntityFrameworkCore.Query.ExpressionTranslators.RelationalCompositeMethodCallTranslator.Translate(MethodCallExpression methodCallExpression, IModel model)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitAndConvert[T](ReadOnlyCollection`1 nodes, String callerName)
   at Remotion.Linq.Parsing.RelinqExpressionVisitor.VisitNew(NewExpression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.VisitNew(NewExpression newExpression)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.Clauses.SelectClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.PerfTests.Tests.Models.ExpressionTest.<MySqlMathRoundTranslator>d__15.MoveNext() in /home/caleb/Projects/caleb/Pomelo.EntityFrameworkCore.Mysql/test/EFCore.MySql.FunctionalTests/Tests/Models/ExpressionTest.cs:line 228
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by pmiddleton** [comment]
You have 4 classes that derive from SingleOverloadStaticMethodCallTranslator for translating various  functions from the Math class.   SingleOverloadStaticMethodCallTranslator expects the supplied method to be a zero parameters method and all 4 of those methods expect a single parameter.  

The constructor for SingleOverloadStaticMethodCallTranslator is therefore unable to find the a matching MethodInfo on the Math class.  Right now RelationalCompositeMethodCallTranslator just loops over all the registered translators until it finds one that will translate the method.  That is why the math translators are firing for unit tests which don't even use them and why the null reference exception is happening

I would suggest you ditch that base class and directly implement IMethodCallTranslator like how it is done for Sql Server.  See [here](https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerMathTranslator.cs)

cc @anpete - Should SingleOverloadStaticMethodCallTranslator be renamed to prevent this confusion?

**Comment by caleblloyd** [comment]
Thanks @pmiddleton I've fixed the Expression Translators

**Comment by smitpatel** [comment]
> SingleOverloadStaticMethodCallTranslator expects the supplied method to be a zero parameters method and all 4 of those methods expect a single parameter.

This is regression. It was never meant to be parameterless. It was only supposed to be static & single overload. Submitted #9077
