### ISSUE TITLE
Missing Microsoft.EntityFrameworkCore.SqlServer.Design preview2

### ISSUE THREAD

**Issue by colltoaction** [dotnet/efcore#9129]
There is no preview2 package published in Nuget for `Microsoft.EntityFrameworkCore.SqlServer.Design`. 

If you mix the preview1 package with `Microsoft.EntityFrameworkCore.Design` preview2 you can get missing method exceptions such as:

```
System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Infrastructure.WarningsConfiguration Microsoft.EntityFrameworkCore.Infrastructure.CoreOptionsExtension.get_WarningsConfiguration()'.
   at Microsoft.EntityFrameworkCore.SqlServerDbContextOptionsExtensions.ConfigureWarnings(DbContextOptionsBuilder optionsBuilder)
   at Microsoft.EntityFrameworkCore.SqlServerDbContextOptionsExtensions.UseSqlServer(DbContextOptionsBuilder optionsBuilder, String connectionString, Action`1 sqlServerOptionsAction)
```

**Comment by smitpatel** [comment]
See https://github.com/aspnet/EntityFramework/issues/8923#issuecomment-310431600

**Comment by tinchou** [comment]
Awesome!
