### ISSUE TITLE
[SQL CE 2.0 provider] Test fail - but why?

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#9377]
Could it be SQL CE engine related?
```
Test 'Microsoft.EntityFrameworkCore.Specification.Tests.NullSemanticsQuerySqlCeTest.Projecting_nullable_bool_with_coalesce' failed:
	System.InvalidCastException : Specified cast is not valid.
	at lambda_method(Closure , QueryContext , ValueBuffer )
	at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
	at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
	at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
	at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, Func`2 verifySucceeded, TState state)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
	at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
	at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
	at Microsoft.EntityFrameworkCore.Query.NullSemanticsQueryTestBase`2.Projecting_nullable_bool_with_coalesce()
	NullSemanticsQuerySqlCeTest.cs(17,0): at Microsoft.EntityFrameworkCore.Specification.Tests.NullSemanticsQuerySqlCeTest.Projecting_nullable_bool_with_coalesce()
```
### Further technical details
EF Core version: 2.0.0-rtm
Database Provider: SQLCE
Operating system: Win 10
IDE: VS 2017 15.3

**Comment by smitpatel** [comment]
Are you facing same issue as here https://github.com/aspnet/EntityFramework/issues/7452 ?

**Comment by ErikEJ** [comment]
Nice find - will try same fix!

**Comment by ErikEJ** [comment]
..
