### ISSUE TITLE
[SQLCE 2.0 provider] Test fail - but why?

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#9379]
```
Test 'Microsoft.EntityFrameworkCore.Specification.Tests.InheritanceSqlCeTest.Can_insert_update_delete' failed: System.InvalidOperationException : Sequence contains no elements
	at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
	at lambda_method(Closure , QueryContext )
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_0`1.<CompileQueryCore>b__0(QueryContext qc)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
	at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
	at System.Linq.Queryable.Single[TSource](IQueryable`1 source, Expression`1 predicate)
	at Microsoft.EntityFrameworkCore.Query.InheritanceTestBase`2.<>c.<Can_insert_update_delete>b__26_1(InheritanceContext context)
	at Microsoft.EntityFrameworkCore.TestUtilities.DbContextHelpers.<>c__DisplayClass0_0`1.<ExecuteWithStrategyInTransaction>b__0(TContext context)
	at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__2`1.<Execute>b__2_0(<>f__AnonymousType0`2 s)
	at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
	at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
	at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, Func`2 verifySucceeded, TState state)
	at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation)
	at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState](IExecutionStrategy strategy, TState state, Action`1 operation)
	at Microsoft.EntityFrameworkCore.TestUtilities.DbContextHelpers.ExecuteWithStrategyInTransaction[TContext](Func`1 createContext, Action`2 useTransaction, Action`1 testOperation, Action`1 nestedTestOperation1, Action`1 nestedTestOperation2, Action`1 nestedTestOperation3)
	at Microsoft.EntityFrameworkCore.Query.InheritanceTestBase`2.Can_insert_update_delete()
	InheritanceSqlCeTest.cs(333,0): at Microsoft.EntityFrameworkCore.Specification.Tests.InheritanceSqlCeTest.Can_insert_update_delete()
```
### Further technical details
EF Core version: 2.0 rtm
Database Provider: SQLCE
Operating system: Win 10
IDE: VS 2017 15.3

**Comment by smitpatel** [comment]
Looks like data issue in your database.

**Comment by ErikEJ** [comment]
Thanks, will try to investigate

**Comment by ajcvickers** [comment]
@ErikEJ Are you still planning to investigate this?

**Comment by ErikEJ** [comment]
Yes, just have been to busy with my daytime job recently! 😄

**Comment by ErikEJ** [comment]
Feel free to assign to me!

**Comment by ajcvickers** [comment]
Done. 😄

**Comment by ErikEJ** [comment]
OK - did some digging:

It is failing because the test base is using: TestUtilities.DbContextHelpers.ExecuteWithStrategyInTransaction 

In other words, this works - wonder what I have done wrong/am missing in the SQL CE provider for this to not work (FYI: I am also unable to run the TransactionTestBase 

```
            using (var context = CreateContext())
            {
                var kiwi = new Kiwi
                {
                    Species = "Apteryx owenii",
                    Name = "Little spotted kiwi",
                    IsFlightless = true,
                    FoundOn = Island.North
                };

                var nz = context.Set<Country>().Single(c => c.Id == 1);

                nz.Animals.Add(kiwi);

                context.SaveChanges();
            }
            using (var context = CreateContext())
            {
                var kiwi = context.Set<Kiwi>().Single(k => k.Species.EndsWith("owenii"));

                kiwi.EagleId = "Aquila chrysaetos canadensis";

                context.SaveChanges();
            }
            using (var context = CreateContext())
            {
                var kiwi = context.Set<Kiwi>().Single(k => k.Species.EndsWith("owenii"));

                Assert.Equal("Aquila chrysaetos canadensis", kiwi.EagleId);

                context.Set<Bird>().Remove(kiwi);

                context.SaveChanges();
            }
            using (var context = CreateContext())
            {
                var count = context.Set<Kiwi>().Count(k => k.Species.EndsWith("owenii"));

                Assert.Equal(0, count);
            }

```

**Comment by smitpatel** [comment]
The test was inserting data in database and the same database was being used by different fixture (FiltersInheritance) so concurrent test run caused test to fail in the other fixture. Ideally, query tests should not be modifying database to avoid this kind of issue. Since this particular test was modifying the data, we wrapped it in transaction using `ExecuteWithStrategyInTransaction` method. That method would start a transaction, run all operation one by one (using different context) & verify everything but would not commit transaction so database is not modified. Can SQL CE do the same?

**Comment by ErikEJ** [comment]
SQLCE does support DbTransactions, but I wonder if there is something I have not implemented properly for this to work. https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/master/src/Provider40/Update/Internal/SqlCeModificationCommandBatch.cs

**Comment by ErikEJ** [comment]
Closing this for now, as test is passing with code modifications, I need to look at TransactionsTest later.
