### ISSUE TITLE
Unable to migrate database changes

### ISSUE THREAD

**Issue by idochynets** [dotnet/efcore#9412]
The Propblem:

I want to apply migrate changes to my database, but always has an error for sql server express instance
'CREATE DATABASE permission denied in database 'master'. Connection string:
"DefaultConnection": "Server=JOHNYDEE\\SQLEXPRESS;Database=Traffikation;User ID = sa; Password = "password";Trusted_Connection=True;MultipleActiveResultSets=true"

```
Exception message: System.Data.SqlClient.SqlException: 'CREATE DATABASE permission denied in database 'master'.'
Stack trace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Traffikation.Database.Initializers.DatabaseInitializerExtension.Initialize(TraffikationContext context) in D:\Projects\traffikation-api\src\Traffikation.Database\Initializers\DatabaseInitializerExtension.cs:line 15
   at Traffikation.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, TraffikationContext context) in D:\Projects\traffikation-api\src\Traffikation\Startup.cs:line 65

```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF Core version: 1.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer, SQL Server Express
Operating system: Windows 8.1
IDE: Visual Studio 2017

**Comment by smitpatel** [comment]
This is issue with your SQL Server configuration. Please make sure
- You have appropriate authentication mode enabled.
- You can connect to database using userid/password or windows auth.
- Whichever mode you connect has permission to create database.

You can read more about how to configure SQL Server in its documentation.

**Comment by idochynets** [comment]
It's wrongly closed i think :(

I'm using Sql Server Auth mode
I'm sure that credentials are right, i used sa and custom user with appropriate credentials, also the both has 'db_creator' or 'sys_admin' server roles

But in case when i'm connecting to standalone sql  server instance it trying to connect under domain user which is not exist on sql server and ignore connection string user
In case when i'm connecting to sql express it's getting user and password from connection string but says that 'CREATE DATABASE permission denied in database 'master', but right granted
Works only on (localdb)\MSSQLLocalDB
Strainge :(

**Comment by ajcvickers** [comment]
@idochynets It would be better to follow up with SQL Server on this--EF isn't doing anything special here, so if there are cases that don't work which you think should, then that's likely an issue with better addressed by SQL Server people.

**Comment by idochynets** [comment]
Many thanks for your comment @ajcvickers, if problem will be resolved on my side, i will add my solution here :)
