### ISSUE TITLE
Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Storage.IRawSqlCommandBuilder'.

### ISSUE THREAD

**Issue by iszolea** [dotnet/efcore#9458]
The above error is returned when trying to action the following migration:
```
     protected override void Up(MigrationBuilder migrationBuilder)
        {
            string script =
   @"
        CREATE VIEW ERP.SalesStatusView
        AS SELECT * from ERP.SalesStatuses";
            DbContextOptions<ERPContext> options = new DbContextOptions<ERPContext>();

            using (var context = new ERPContext(options))
            {
                context.Database.ExecuteSqlCommand(script);
            }
        }
```

The database context is added as:
```
     public void ConfigureServices(IServiceCollection services)
        {
            //services.AddDbContext<AppIdentityDbContext>(options => options.UseSqlServer(Configuration["Data:ERPIdentity:ConnectionString"]));
            services.AddDbContext<ERPContext>(options => options.UseSqlServer(Configuration["Data:ERPIdentity:ConnectionString"]));
```
The DbContext is:
```
    public class ERPContext : ERPIdentityDbContext
    {
        public ERPContext(DbContextOptions<ERPContext> options) : base(options) { }

```
The full stack trace from the migration process is:
```
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Storage.IRawSqlCommandBuilder'. This is often because no database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlCommand(DatabaseFacade databaseFacade, String sql, Object[] parameters)
   at ERPExtended.Repository.Migrations.Mynewemptymigration.Up(MigrationBuilder migrationBuilder) in C:\Users\Jeff\Documents\Visual Studio 2017\Projects\ERPExtended\ERPExtended.Repository\Migrations\20170817123508_My new empty migration.cs:line 21
   at Microsoft.EntityFrameworkCore.Migrations.Migration.BuildOperations(Action`1 buildAction)
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Storage.IRawSqlCommandBuilder'. This is often because no database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
```

I am using EF Verions 1.1.2 and .net core 1.1.

Can you please provide advice on where to go from here?

Thanks
Jeff

**Comment by ajcvickers** [comment]
@iszolea Ideally you shouldn't need code like this in your migration--instead use the MigrationBuilder.Sql method.

That being said, the code posted is configuring the context in the service provider, but then creating a new context instance explicitly rather than resolving the context from the service provider. So you need to either resolve the context from the service provider, or explicitly configure the context when creating it with `new`. To do the latter, use DbContextOptionsBuilder with UseSqlServer to create the options.

**Comment by iszolea** [comment]
Damm! Obvious now.

Thanks so much.
Cheers
Jeff
