### ISSUE TITLE
Visual Studio Crashes : System.ServiceModel.CommunicationException: There was an error reading from the pipe

### ISSUE THREAD

**Issue by Predator404** [dotnet/efcore#9460]
Hello, 

I'm using Entity Framework Core and have run into an issue that I suspect originates in Entity Framework itself.

I've attached my solution that I'm using so that you can re-create the issue on your side. 
In order to reproduce you are going to have to create a database and (obviously) apply the existing migrations to that database. The config file pointing to the database can be found at V_Tallyman.API\appsettings.json.

Once the database has been created, set V_Tallyman.API as the startup project.
Set breakpoints in the Seed method for each of the method calls found in V_Tallyman.DAL\Seeding.cs.

**What happens:** The first time the code runs it seeds the database correctly, as expected.
The second time you run it it will mark the seeding records to be updated if they already exist. The idea here is that any changes to the lookups will automatically be fed through to the database on the next run of the application.

When SaveChanges() is called a DBUpdateConcurrencyException is thrown as no records are actually updated (there are no changes defined in the seeding method) - this is expected behavior - the error message will start with "Database operation expected to affect 1 row(s) but actually affected 0 row(s)."

The issue is this: The first time a DBUpdateConcurrencyException is thrown it is handled correctly by Visual Studio, the next time it happens Visual Studio dies horribly and I need to terminate the process.

This only occurs if the application is run in debug mode. 

Feedback would be greatly appreciated, thank you for reading this.

[RM01.ZIP](https://github.com/aspnet/EntityFrameworkCore/files/1233791/RM01.ZIP)
[Report.zip](https://github.com/aspnet/EntityFrameworkCore/files/1233857/Report.zip)

### Further technical details
EF Core version: Occurs in both 1.1 and 2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 7
IDE: Occurs in both Visual Studio Professional 2017 15.1.0 Visual Studio 2017 Professional Preview (2) 15.3.0 Preview 7.1

Looking at the Windows logs reveals the following: 

The description for Event ID 0 from source Application cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

Error Handler Exception: System.ServiceModel.CommunicationException: There was an error reading from the pipe: Unrecognized error 109 (0x6d). ---> System.IO.IOException: The read operation failed, see inner exception. ---> System.ServiceModel.CommunicationException: There was an error reading from the pipe: Unrecognized error 109 (0x6d). ---> System.IO.PipeException: There was an error reading from the pipe: Unrecognized error 109 (0x6d).
   at System.ServiceModel.Channels.PipeConnection.OnAsyncReadComplete(Boolean haveResult, Int32 error, Int32 numBytes)
   --- End of inner exception stack trace ---
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.ConnectionStream.EndRead(IAsyncResult asyncResult)
   at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
   --- End of inner exception stack trace ---
   at System.Net.Security.NegotiateStream.EndRead(IAsyncResult asyncResult)
   at System.ServiceModel.Channels.StreamConnection.EndRead()
   --- End of inner exception stack trace ---
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.TransportDuplexSessionChannel.EndTryReceive(IAsyncResult result, Message& message)
   at System.ServiceModel.Dispatcher.DuplexChannelBinder.EndTryReceive(IAsyncResult result, RequestContext& requestContext)
   at System.ServiceModel.Dispatcher.ErrorHandlingReceiver.EndTryReceive(IAsyncResult result, RequestContext& requestContext) \r\n    at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.TransportDuplexSessionChannel.EndTryReceive(IAsyncResult result, Message& message)
   at System.ServiceModel.Dispatcher.DuplexChannelBinder.EndTryReceive(IAsyncResult result, RequestContext& requestContext)
   at System.ServiceModel.Dispatcher.ErrorHandlingReceiver.EndTryReceive(IAsyncResult result, RequestContext& requestContext)

the message resource is present but the message is not found in the string/message table

The description for Event ID 0 from source Application cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Error Handler Exception: System.ServiceModel.CommunicationException: There was an error reading from the pipe: Unrecognized error 109 (0x6d). ---> System.IO.IOException: The read operation failed, see inner exception. ---> System.ServiceModel.CommunicationException: There was an error reading from the pipe: Unrecognized error 109 (0x6d). ---> System.IO.PipeException: There was an error reading from the pipe: Unrecognized error 109 (0x6d).
   at System.ServiceModel.Channels.PipeConnection.OnAsyncReadComplete(Boolean haveResult, Int32 error, Int32 numBytes)
   --- End of inner exception stack trace ---
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.ConnectionStream.EndRead(IAsyncResult asyncResult)
   at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
   --- End of inner exception stack trace ---
   at System.Net.Security.NegotiateStream.EndRead(IAsyncResult asyncResult)
   at System.ServiceModel.Channels.StreamConnection.EndRead()
   --- End of inner exception stack trace ---
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.TransportDuplexSessionChannel.EndTryReceive(IAsyncResult result, Message& message)
   at System.ServiceModel.Dispatcher.DuplexChannelBinder.EndTryReceive(IAsyncResult result, RequestContext& requestContext)
   at System.ServiceModel.Dispatcher.ErrorHandlingReceiver.EndTryReceive(IAsyncResult result, RequestContext& requestContext) \r\n    at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.TransportDuplexSessionChannel.EndTryReceive(IAsyncResult result, Message& message)
   at System.ServiceModel.Dispatcher.DuplexChannelBinder.EndTryReceive(IAsyncResult result, RequestContext& requestContext)
   at System.ServiceModel.Dispatcher.ErrorHandlingReceiver.EndTryReceive(IAsyncResult result, RequestContext& requestContext)

the message resource is present but the message is not found in the string/message table

The program devenv.exe version 15.0.26730.3 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Action Center control panel.
 Process ID: 46c0
 Start Time: 01d3178d7e4deca0
 Termination Time: 42
 Application Path: C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\Common7\IDE\devenv.exe
 Report Id: 1010b641-8381-11e7-ab29-e4b3186ac18c

**Comment by ajcvickers** [comment]
@Predator404 I downloaded the attached zip files, but I they don't seem to contain any source code or projects.
For this kind of Visual Studio crash the best option is usually to use the "Send Feedback" option in Visual Studio, since this will include important diagnostics in the report. If you can provide a VS solution (or let me know what I am doing wrong in trying to find it) then we can investigate, but if VS crashes for us in the same way as it does for you, then likely even for us the Send Feedback option would be the next step.
