### ISSUE TITLE
Adding EF 2.0 results in Exception in VS2017 React/Redux template web app

### ISSUE THREAD

**Issue by stuartallenmills** [dotnet/efcore#9471]
'System.Collections.Generic.Dictionary`2<System.String,System.Object> Microsoft.Extensions.Configuration.IConfigurationBuilder.get_Properties()'.

Stack Trace:
   at Microsoft.Extensions.Configuration.FileConfigurationExtensions.SetFileProvider(IConfigurationBuilder builder, IFileProvider fileProvider)
   at Microsoft.Extensions.Configuration.FileConfigurationExtensions.SetBasePath(IConfigurationBuilder builder, String basePath)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at reactredux.Program.BuildWebHost(String[] args) in C:\Users\smills\webstuff\reactredux\Program.cs:line 19
   at reactredux.Program.Main(String[] args) in C:\Users\smills\webstuff\reactredux\Program.cs:line 15

**Comment by stuartallenmills** [comment]
Was using VS2107 preview.  Retesting with Release - problem not encountered at this point.
