### ISSUE TITLE
reverse model from mysql doesnt work

### ISSUE THREAD

**Issue by shyandsy** [dotnet/efcore#9489]
reverse model from mysql database doesnt work

If you are seeing an exception, include the full exceptions details (message and stack trace).

```text
PM> Scaffold-DbContext "Host=127.0.0.1;Port=3306;Database=demo;Username=shyandsy;Password=xxxxx" MySql.Data.EntityFrameworkCore -OutputDir Models
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext..ctor(OperationExecutor executor, Object resultHandler, IDictionary args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Microsoft.EntityFrameworkCore.Tools.ReflectionOperationExecutor.Execute(String operationName, Object resultHandler, IDictionary arguments)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid4[T0,T1,T2,T3](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at Microsoft.EntityFrameworkCore.Tools.OperationExecutorBase.InvokeOperationImpl(String operationName, IDictionary arguments)
   at Microsoft.EntityFrameworkCore.Tools.OperationExecutorBase.ScaffoldContext(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles)
   at Microsoft.EntityFrameworkCore.Tools.Commands.DbContextScaffoldCommand.Execute()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Exception has been thrown by the target of an invocation.
PM> 
```

### Steps to reproduce
i will add this part if required

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF Core version: 2
Database Provider: MySql.Data.EntityFrameworkCore
Operating system: 
IDE: Visual Studio 2017 15.3.1

![image](https://user-images.githubusercontent.com/5271457/29493181-34e34050-8557-11e7-8d7e-099a0c8bfb3e.png)

**Comment by smitpatel** [comment]
`MySQL.Data.EntityFrameworkCore` package depends on EF Core 1.1.1. Since 2.0 is major version there are breaking changes hence you cannot use MySQL package with EF Core 2.0 packages. If you are referencing any EF Core package v 2.0 then remove those references (or uninstall packages from your project).

**Comment by Kagamine** [comment]
You can use Pomelo.EntityFrameworkCore.MySql

**Comment by fyn-dev** [comment]
@Kagamine same problem with Pomelo.EntityFrameworkCore.MySql :(
