### ISSUE TITLE
EF Core 1.1 Separate Assembly Migrations Not Considered

### ISSUE THREAD

**Issue by HelloKitty** [dotnet/efcore#9601]
Describe what is not working as expected.

Add-Migration appears to not consider generated migrations in a separate project/assembly reference when generating a new migrations for a separate context that references that table through a foreign key. It will create the scaffolding, if that is what is it still called, for the foreign table. This causes Update-Database to fail since the table will already exist.

If you are seeing an exception, include the full exceptions details (message and stack trace).

Exception message: Table 'avatarentries' already exists
Stack trace:
```MySql.Data.MySqlClient.MySqlException: Table 'avatarentries' already exists
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet)
   at MySql.Data.MySqlClient.MySqlDataReader.<ReadFirstResultSetAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<CreateAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteReaderAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteNonQueryAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)```
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

Repro too bulky

### Further technical details
EF Core version: (found in project.csproj or packages.config) 1.1
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2015)

**Comment by HelloKitty** [comment]
You can manually remove the create table and drop table from the migrations to temporarily fix this. But it would nice if it could be discoverable or hinted to the tools that the table exists by pointing it to other migrations in a separate assembly.

**Comment by ajcvickers** [comment]
@HelloKitty I _think_ from reading this that you are looking for the functionality described in issue #2725. If this is not the case, can you explain a bit more what you are asking?

**Comment by HelloKitty** [comment]
@ajcvickers That appears to be functionality that would address the issue. Some sort of hinting to the location of migrations to consider or explicit exclusions for table generation would solve it, as described by the issue you linked.

I apologize for the duplicate! Should I close this issue?

**Comment by HelloKitty** [comment]
Closing due to duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/2725

**Comment by divega** [comment]
@HelloKitty no need to apologize!
