### ISSUE TITLE
ATS: Query: Problem materializing after adding Discontinued flag to Product

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#965]
Looks like a query result binding issue:

Test 'Microsoft.Data.Entity.AzureTableStorage.FunctionalTests.NorthwindQueryTest.Where_bool_member_shadow' failed: Microsoft.WindowsAzure.Storage.StorageException : Cannot read value of type 'Nullable`1' from '3'
---- System.TypeAccessException : Cannot read value of type 'Nullable`1' from '3'
    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
    at Microsoft.WindowsAzure.Storage.Table.TableQuery.ExecuteQuerySegmented[TResult](TableContinuationToken token, CloudTableClient client, CloudTable table, EntityResolver`1 resolver, TableRequestOptions requestOptions, OperationContext operationContext)
    at Microsoft.WindowsAzure.Storage.Table.TableQuery.<>c__DisplayClass6`1.<Execute>b__5(IContinuationToken continuationToken)
    at Microsoft.WindowsAzure.Storage.Core.Util.CommonUtility.<LazyEnumerable>d__0`1.MoveNext()
    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
    Query\AtsQueryContext.cs(54,0): at Microsoft.Data.Entity.AzureTableStorage.Query.AtsQueryContext.<>c__DisplayClass1`1.<GetOrAddQueryResults>b__0(QueryKey q)
    Utilities\ThreadSafeDictionaryCache.cs(23,0): at Microsoft.Data.Entity.Utilities.ThreadSafeDictionaryCache`2.GetOrAdd(TKey key, Func`2 factory)
    Query\AtsQueryContext.cs(53,0): at Microsoft.Data.Entity.AzureTableStorage.Query.AtsQueryContext.GetOrAddQueryResults[TResult](QueryTableRequest`1 request)
    Query\AtsQueryModelVisitor.cs(106,0): at Microsoft.Data.Entity.AzureTableStorage.Query.AtsQueryModelVisitor.ExecuteSelectExpression[TResult](QueryContext queryContext, IEntityType entityType, SelectExpression selectExpression)
    at lambda_method(Closure , QuerySourceScope )
    at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
    Query\LinqOperatorProvider.cs(29,0): at Microsoft.Data.Entity.Query.LinqOperatorProvider.<_TrackEntities>d__0`2.MoveNext()
    Query\EntityQueryExecutor.cs(176,0): at Microsoft.Data.Entity.Query.EntityQueryExecutor.EnumerableExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
    NorthwindQueryTestBase.cs(1926,0): at Microsoft.Data.Entity.FunctionalTests.NorthwindQueryTestBase.AssertQuery[TItem](Func`2 query, Boolean assertOrder, Int32 stateEntryCount)
    NorthwindQueryTestBase.cs(423,0): at Microsoft.Data.Entity.FunctionalTests.NorthwindQueryTestBase.Where_bool_member_shadow()
    ----- Inner Stack Trace -----
    Query\AtsObjectArrayValueReader.cs(47,0): at Microsoft.Data.Entity.AzureTableStorage.Query.AtsObjectArrayValueReader.ReadValue[T](Int32 index)
    at lambda_method(Closure , IValueReader )
    Query\QueryBuffer.cs(98,0): at Microsoft.Data.Entity.Query.QueryBuffer.GetEntity(IEntityType entityType, IValueReader valueReader)
    Query\AtsQueryModelVisitor.cs(103,0): at Microsoft.Data.Entity.AzureTableStorage.Query.AtsQueryModelVisitor.<>c__DisplayClass4`1.<ExecuteSelectExpression>b__3(AtsNamedValueBuffer s)
    Requests\QueryTableRequest.cs(77,0): at Microsoft.Data.Entity.AzureTableStorage.Requests.QueryTableRequest`1.<Execute>b__0(String key, String rowKey, DateTimeOffset timestamp, IDictionary`2 properties, String etag)
    at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpResponseParsers.ReadAndResolve[T](ODataEntry entry, Func`6 resolver)
    at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpResponseParsers.TableQueryPostProcessGeneric[TElement,TQueryType](Stream responseStream, Func`6 resolver, HttpWebResponse resp, TableRequestOptions options, OperationContext ctx, String accountName)
    at Microsoft.WindowsAzure.Storage.Table.TableQuery.<>c__DisplayClass11`1.<QueryImpl>b__10(RESTCommand`1 cmd, HttpWebResponse resp, OperationContext ctx)
    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ProcessEndOfRequest[T](ExecutionState`1 executionState)
    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)

**Comment by rowanmiller** [comment]
ATS is not part of working code base at the moment
