### ISSUE TITLE
EF Core Problem In Insert Into Entity With Multiple Relation With Another Entity

### ISSUE THREAD

**Issue by irajchardoli** [dotnet/efcore#9655]
I've got the following model:

    public class Product
    {
        #region Constructor

        public Product()
        {
            this.Relateds = new HashSet<Related>();
            this.RelatedProducts = new HashSet<Related>();
        }

        #endregion Constructor

        #region Fields

        public Int32 Id { get; set; }

        [StringLength(80)]
        [Required]
        public String Name1 { get; set; }

        #endregion Fields

        #region Navigation

        public virtual ICollection<Related> Relateds { get; set; }

        public virtual ICollection<Related> RelatedProducts { get; set; }

        #endregion Navigation
    }
	
    public class Related : IEntityKey<Int32>, IAuditableEntity
    {
        #region Constructor

        public Related()
        {
        }

        #endregion Constructor

        #region Fields

        public Int32 Id { get; set; }

        #endregion Fields

        #region ForeignKey 

        [Required]
        public Int32 ProductId { get; set; }

        [Required]
        public Int32 RelatedProductId { get; set; }

        #endregion ForeignKey

        #region Navigation

        public virtual Product Product { get; set; }

        public virtual Product RelatedProduct { get; set; }

        #endregion Navigation
    }	
	
	
    public class RelatedMappings
    {
        public RelatedMappings(EntityTypeBuilder<Related> entityBuilder)
        {
            entityBuilder.ToTable("Relateds", "PUB");

            entityBuilder.HasOne(c => c.Product)
             .WithMany(c => c.Relateds)
             .HasForeignKey(c => c.ProductId)
             .OnDelete(Microsoft.EntityFrameworkCore.Metadata.DeleteBehavior.Restrict);

            entityBuilder.HasOne(c => c.RelatedProduct)
             .WithMany(c => c.RelatedProducts)
             .HasForeignKey(c => c.RelatedProductId)
             .OnDelete(Microsoft.EntityFrameworkCore.Metadata.DeleteBehavior.Restrict);
        }
    }	
	
    public class ProductMappings
    {
        public ProductMappings(EntityTypeBuilder<Product> entityBuilder)
        {
            entityBuilder.ToTable("Products", "PUB");

            entityBuilder.HasMany(c => c.Relateds)
                .WithOne(c => c.Product)
                .HasForeignKey(c => c.ProductId)
                .OnDelete(Microsoft.EntityFrameworkCore.Metadata.DeleteBehavior.Restrict);

            entityBuilder.HasMany(c => c.RelatedProducts)
                .WithOne(c => c.RelatedProduct)
                .HasForeignKey(c => c.RelatedProductId)
                .OnDelete(Microsoft.EntityFrameworkCore.Metadata.DeleteBehavior.Restrict);
        }
    }

When i try to insert one product with multiple related product I get the following error:

	Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. 
	See the inner exception for details. ---> System.Data.SqlClient.SqlException: 
	The MERGE statement conflicted with the FOREIGN KEY constraint "FK_Relateds_Products_ProductId". The conflict occurred in database "DB", table "PUB.Products", column 'Id'.
	   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
	   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
	   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
	   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
	   at System.Data.SqlClient.SqlDataReader.TryHasMoreResults(Boolean& moreResults)
	   at System.Data.SqlClient.SqlDataReader.TryNextResult(Boolean& more)
	   at System.Data.SqlClient.SqlDataReader.<>c__DisplayClass181_0.<NextResultAsync>b__1(Task t)
	   at System.Data.SqlClient.SqlDataReader.InvokeRetryable[T](Func`2 moreFunc, TaskCompletionSource`1 source, IDisposable objectToDispose)
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.<ConsumeAsync>d__2.MoveNext()
	   --- End of inner exception stack trace ---
	   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.<ConsumeAsync>d__2.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__32.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__10.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<ExecuteImplementationAsync>d__33`2.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<ExecuteImplementationAsync>d__33`2.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__54.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__52.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__35.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
	   at Services.ProductService.<CreateAsync>d__8.MoveNext() in E:\src\Services\ProductService.cs:line 131
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()

**Comment by ajcvickers** [comment]
@irajchardoli I took your code, with a few changes to make it compile, and ran it on EF Core 2.0 as shown below and I don't get any exception. What version of EF Core are you using? Also, is there something special/different about the graph that your code is inserting?
```C#
public class Product
{
    #region Constructor

    public Product()
    {
        this.Relateds = new HashSet<Related>();
        this.RelatedProducts = new HashSet<Related>();
    }

    #endregion Constructor

    #region Fields

    public Int32 Id { get; set; }

    [StringLength(80)]
    [Required]
    public String Name1 { get; set; }

    #endregion Fields

    #region Navigation

    public virtual ICollection<Related> Relateds { get; set; }

    public virtual ICollection<Related> RelatedProducts { get; set; }

    #endregion Navigation
}

public interface IEntityKey<T>
{
    Int32 Id { get; set; }
}

public interface IAuditableEntity
{
}

public class Related : IEntityKey<Int32>, IAuditableEntity
{
    #region Constructor

    public Related()
    {
    }

    #endregion Constructor

    #region Fields

    public Int32 Id { get; set; }

    #endregion Fields

    #region ForeignKey 

    [Required]
    public Int32 ProductId { get; set; }

    [Required]
    public Int32 RelatedProductId { get; set; }

    #endregion ForeignKey

    #region Navigation

    public virtual Product Product { get; set; }

    public virtual Product RelatedProduct { get; set; }

    #endregion Navigation
}


public class RelatedMappings
{
    public RelatedMappings(EntityTypeBuilder<Related> entityBuilder)
    {
        entityBuilder.ToTable("Relateds", "PUB");

        entityBuilder.HasOne(c => c.Product)
            .WithMany(c => c.Relateds)
            .HasForeignKey(c => c.ProductId)
            .OnDelete(DeleteBehavior.Restrict);

        entityBuilder.HasOne(c => c.RelatedProduct)
            .WithMany(c => c.RelatedProducts)
            .HasForeignKey(c => c.RelatedProductId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}

public class ProductMappings
{
    public ProductMappings(EntityTypeBuilder<Product> entityBuilder)
    {
        entityBuilder.ToTable("Products", "PUB");

        entityBuilder.HasMany(c => c.Relateds)
            .WithOne(c => c.Product)
            .HasForeignKey(c => c.ProductId)
            .OnDelete(DeleteBehavior.Restrict);

        entityBuilder.HasMany(c => c.RelatedProducts)
            .WithOne(c => c.RelatedProduct)
            .HasForeignKey(c => c.RelatedProductId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}

public class TestContext : DbContext
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        new ProductMappings(modelBuilder.Entity<Product>());
        new RelatedMappings(modelBuilder.Entity<Related>());
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(
            @"Server=(localdb)\mssqllocaldb;Database=Test;Trusted_Connection=True;ConnectRetryCount=0");
}

public static void Main()
{
    using (var context = new TestContext())
    {
        context.Database.EnsureDeleted();
        context.Database.EnsureCreated();

        var product = new Product();
        product.RelatedProducts.Add(new Related());
        product.RelatedProducts.Add(new Related());
        product.RelatedProducts.Add(new Related());

        product.Relateds.Add(new Related());
        product.Relateds.Add(new Related());
        product.Relateds.Add(new Related());

        context.SaveChanges();
    }
}
```

**Comment by irajchardoli** [comment]
@ajcvickers  thanks for your reply ,i use EF Core 1.1.2 . I took your code , I just change in Main method , First of all add new line for attach product to context , and add a product without any related product ,Its work fine.then add a new product with related previous product and i still get error.

First:

        public static void Main()
        {
            using (var context = new TestContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                var product = new Product();
                product.Name1 = "Product1";

                context.Add(product); //This Line Added
                context.SaveChanges();
            }
        }

This insert first product with id=1;
Second:

        public static void Main()
        {
            using (var context = new TestContext())
            {
                //context.Database.EnsureDeleted();
                //context.Database.EnsureCreated();

                var product = new Product();
                product.Name1 = "Product2";
                product.RelatedProducts.Add(new Related { RelatedProductId = 1 });

                context.Add(product);//This Line Added
                context.SaveChanges();
            }
        }
 
And I get the following error:
```

Microsoft.EntityFrameworkCore.DbUpdateException occurred
  HResult=0x80131500
  Message=An error occurred while updating the entries. See the inner exception for details.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at TestEFCoreInsert.Program.Main() in E:\Partition\FileProject\Sample\TestEFCoreInsert\TestEFCoreInsert\Program.cs:line 155

Inner Exception 1:
SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Relateds_Products_ProductId". The conflict occurred in database "Test", table "PUB.Products", column 'Id'.
The statement has been terminated.

```

**Comment by irajchardoli** [comment]
@ajcvickers Thanks for your reply , i made a mistake , and i resolved the issue.
