### ISSUE TITLE
How to run Scaffolding in 2.0

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#9674]
@bricelam 

I have this in 1.1, but cannot figure out the "reporter" part in 2.0 - hope you can help 😄 

1: How to build the required services, incl. operationReporter 
2: how to get the scaffolding errors reported back

```
        public EfCoreReverseEngineerResult GenerateFiles(ReverseEngineerOptions reverseEngineerOptions)
        {
            var reporter = new OperationReporter(new OperationReportHandler());
            
            // Add base services for scaffolding
            var serviceCollection = new ServiceCollection()
            .AddScaffolding(reporter) //HOW????
            .AddLogging();

           var serviceProvider = serviceCollection.BuildServiceProvider();
            var generator = serviceProvider.GetService<ModelScaffolder>();

            // Add database provider services
            switch (reverseEngineerOptions.DatabaseType)
            {
              case DatabaseType.SQLServer:
                    var provider = new SqlServerDesignTimeServices();
                    provider.ConfigureDesignTimeServices(serviceCollection);
                    break;
                default:
                    throw new ArgumentOutOfRangeException();
            }
            //var options = new ReverseEngineeringConfiguration
            //{
            //    ConnectionString = reverseEngineerOptions.ConnectionString,
            //    ProjectPath = reverseEngineerOptions.ProjectPath,
            //    OutputPath = reverseEngineerOptions.OutputPath,
            //    ProjectRootNamespace = reverseEngineerOptions.ProjectRootNamespace,
            //    OverwriteFiles = true,
            //    UseFluentApiOnly = reverseEngineerOptions.UseFluentApiOnly,
            //    ContextClassName = reverseEngineerOptions.ContextClassName,
            //    TableSelectionSet = tableSelectionSet
            //};

            var filePaths = generator.Generate(
               connectionString,
                tables,
                schemas,
                _projectDir,
                outputDir,
                _rootNamespace,
                dbContextClassName,
                useDataAnnotations,
                overwriteFiles,
                useDatabaseNames);

            var result = new EfCoreReverseEngineerResult
            {
                //TODO Add errors!
                EntityErrors = null,
                EntityTypeFilePaths = filePaths.EntityTypeFiles,
                ContextFilePath = filePaths.ContextFile,
            };

            return result;
        }
```

**Comment by bricelam** [comment]
Use the report handler:
``` csharp
var reporter = new OperationReporter(
    new OperationReportHandler(
        m => errors.Add(m)),
        m => warnings.Add(m)));
```

**Comment by ErikEJ** [comment]
Thanks, what is "errors" in this context? a local method?

**Comment by bricelam** [comment]
You could also preserve the order by adding them to the same list.
``` csharp
var diagnostics = new List<(string level, string message)>();
var reporter = new OperationReporter(
                new OperationReportHandler(
                    m => diagnostics.Add("error", m),
                    m => diagnostics.Add("warning", m)));
```

**Comment by ErikEJ** [comment]
@bricelam Thanks so far - getting closer!

var generator = serviceProvider.GetService<ModelScaffolder>();

returns null - any idea why? 

https://github.com/ErikEJ/SqlCeToolbox/blob/master/src/GUI/ReverseEngineer20/EFCoreReverseEngineer.cs#L50

**Comment by ErikEJ** [comment]
If I change to:

`
var generator = serviceProvider.GetService<IModelScaffolder>();
`
I get: 
Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Design.Internal.IOperationReporter' while attempting to activate 'Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory'.

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType, ServiceProvider serviceProvider)
   at System.Collections.Concurrent.ConcurrentDictionaryExtensions.GetOrAdd[TKey,TValue,TArg](ConcurrentDictionary`2 dictionary, TKey key, Func`3 valueFactory, TArg arg)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at EFCoreReverseEngineer.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions)
   at EFCorePowerTools.Handlers.ReverseEngineerCodeFirstHandler.ReverseEngineerCodeFirst(Project project) in C:\Code\SqlCeToolbox\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerCodeFirstHandler.cs:line 126

**Comment by ErikEJ** [comment]
Finally working!  I needed this:

```
            var serviceCollection = new ServiceCollection()
                .AddScaffolding(reporter)
                .AddSingleton<IOperationReporter, OperationReporter>()
                .AddSingleton<IOperationReportHandler, OperationReportHandler>();
```

and used this:

`            var generator = serviceProvider.GetService<IModelScaffolder>();
`
