### ISSUE TITLE
A query of a TPH throws exception when selecting a property via discriminator and cast

### ISSUE THREAD

**Issue by JonPSmith** [dotnet/efcore#9804]
I have a query that looks a a TPH DbSet consist of `Book` and `BookwithOffer`. I try to extract a value in the `BookWithOffer`, with a test on the discriminator. This works for a string, but not for a decimal. The SQL looks OK (see near the end of this comment), but I get the following exception.

I can confirm that the TPH table works property, as I have unit tests that checks that.

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at lambda_method(Closure , QueryContext , ValueBuffer )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Test.UnitTests.ServiceLayer.Ch13_ListBooksService.TestBookListDtoSelectOk() in C:\Users\Jon\Documents\Visual Studio 2017\Projects\EfCoreInAction\Test\UnitTests\ServiceLayer\Ch13_ListBooksService.cs:line 39
```

### Steps to reproduce
Here is a snippet of the code I am trying to develop.

```c#
public class Book                        
{
    public int BookId { get; set; }

    [Required] //#A
    [MaxLength(256)] //#B
    public string Title { get; set; }
    public string Description { get; set; }
    public DateTime PublishedOn { get; set; }
    [MaxLength(64)] //#B
    public string Publisher { get; set; }
    public decimal ActualPrice { get; set; }
    //This controls the TPH - true if its a BookWithOffer
    public bool HasOffer { get; set; }

    [MaxLength(512)] //#B
    public string ImageUrl { get; set; }
    public bool SoftDeleted { get; set; }

    //-----------------------------------------------
    //relationships

    //public BookWithOffer Promotion { get; set; }       
    public ICollection<Review> Reviews { get; set; } 
    public ICollection<BookAuthor> 
        AuthorsLink { get; set; }                    
}
```
```c#
public class BookWithOffer : Book
{
    public const int PromotionalTextLength = 200;
    public decimal OldPrice { get; set; }
    [Required]
    [MaxLength(PromotionalTextLength)]
    public string PromotionalText { get; set; }
}
```
My DTO looks like this
```c#
public class BookListDto
{
    public int BookId { get; set; }           
    public string Title { get; set; }
    public bool HasOffer { get; set; }
    public decimal OldPrice { get; set; }     
    public decimal ActualPrice { get; set; }             
    public string PromotionPromotionalText { get; set; }  
}
```
My query looks like this
```c#
var books = context.Books.Select(p => new BookListDto
{
    BookId = p.BookId,                  
    Title = p.Title,                          
    ActualPrice = p.ActualPrice,
    HasOffer = p.HasOffer,
    OldPrice = p.HasOffer
        ? p.ActualPrice
        : ((BookWithOffer)p).OldPrice,
    PromotionPromotionalText =
            p.HasOffer
              ? "unit test!"
              : ((BookWithOffer)p).PromotionalText
}).ToList()
```
My config is
```c#
public void Configure
    (EntityTypeBuilder<Book> entity)
{
     //... other configs removed for clarity

    entity.HasDiscriminator(b => b.HasOffer)
        .HasValue<Book>(false)
        .HasValue<BookWithOffer>(true);

    entity.Property(p => p.HasOffer)
        .Metadata.AfterSaveBehavior = PropertySaveBehavior.Save;
}
```

The SQL that I captured looks like this.
```SQL
SELECT "b"."BookId", "b"."Title", "b"."ActualPrice", "b"."HasOffer", CASE
    WHEN "b"."HasOffer" = 1
    THEN "b"."ActualPrice" ELSE "b"."OldPrice"
END AS "OldPrice", CASE
    WHEN "b"."HasOffer" = 1
    THEN 'unit test!' ELSE "b"."PromotionalText"
END AS "PromotionPromotionalText"
FROM "Books" AS "b"
WHERE "b"."HasOffer" IN (1, 0) AND ("b"."SoftDeleted" = 0)
```

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.Sqlite (for unit test)
Operating system: Window 10
IDE: VS2017 15.3

**Comment by smitpatel** [comment]
The above error suggest that, when reading values from database the value was NULL but it was being stored in a non-nullable property. So NRE.

In your model, you have set discriminator (HasOffer) to be false for book & true for BookWithOffer.
But in your query you are calling `OldPrice = p.HasOffer ? p.ActualPrice : ((BookWithOffer)p).OldPrice`
If p.HasOffer is false (means its a Book) then cast to `BookWithOffer` will fail. Since all of this is happening in database as you can see in SQL, for a book "b"."HasOffer" will be 0 hence, it will get value of "b"."OldPrice" column. Since that column does not exist for Book, in TPH it will have null value. When this returned NULL value is materialized into `BookListDto.OldPrice` which is decimal (non-nullable), NRE is thrown. Probably you need to invert conditions for `OldPrice` & `PromotionPromotionalText` both.

Following query works correctly
```C#
                var books = db.Set<Book>().Select(p => new BookListDto
                {
                    BookId = p.BookId,
                    Title = p.Title,
                    ActualPrice = p.ActualPrice,
                    HasOffer = p.HasOffer,
                    OldPrice = !p.HasOffer
                        ? p.ActualPrice
                        : ((BookWithOffer) p).OldPrice,
                    PromotionPromotionalText =
                        !p.HasOffer
                            ? "unit test!"
                            : ((BookWithOffer) p).PromotionalText
                }).ToList();
```

**Comment by JonPSmith** [comment]
Doh! So sorry - I just didn't see that.
