### ISSUE TITLE
boolean Shadow properties as part of Key and Navigation property evaluates the PK before shadow props are set

### ISSUE THREAD

**Issue by Tarig0** [dotnet/efcore#9858]
The following is a trimmed down version of the issue I am seeing.

I am trying to push as much of the Data layer out of my model code and experience the following error when I use a non-nullable type as both a navigation key and PK.
The issue goes away as soon as I switch to a nullable type.
```
Exception message: Unable to track an entity of type 'b' because primary key property 'code' is null.
Stack trace:
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NullableKeyIdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState entityState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.Add[TEntity](TEntity entity)
   at ConsoleApp1.Program.Main(String[] args) in <redacted>Program.cs:line 12
```

### Steps to reproduce

```c#
using Microsoft.EntityFrameworkCore;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var model = new b() { a = new a() { code = false}};
            using (var db = new Data())
            {
                db.Add(model);
            }
        }
        private class Data : DbContext
        {
            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) => optionsBuilder.UseInMemoryDatabase("test");
            
            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                modelBuilder.Entity<a>().HasKey(a => new { a.code });
                modelBuilder.Entity<b>().HasOne(ab => ab.a).WithMany().HasForeignKey(nameof(a.code));
                modelBuilder.Entity<b>().HasKey(nameof(a.code));
            }
        }
        private class a
        {
           public bool code { get; set; }
        }
        private class b
        {
            public a a { get; set; }
        }
    }
}

```

### Further technical details
EF Core version: 2.0.0
Database Provider: N/A
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment]
@Tarig0 I am only able to reproduce this with bool keys, which are not common. Have you also seen this for other key types, such as ints or strings? If you have, can you update the repro code to use something other than a bool key?

**Comment by Tarig0** [comment]
The bit/bool is part of a composite key. I am able to function with "bool?"  Type. I will check with other types. But my guess is that I just found the outlier.

**Comment by Tarig0** [comment]
This appears to only effect the bool type. For my case the this is an isFlag that is part of the PK, so doesn't make sense for me to be required to change my model code. 

As stated before I can get around this by switching to the nullable<bool> type, which has some advantages for model validation, and the error goes away.

**Comment by ajcvickers** [comment]
Note for triage: On further investigation I think this is by-design. The code is adding a new entity (in this case a dependent in an FK-to-FK relationship) that is not using a generated key without setting the generated key value to anything. This is not supported. The reason the same code works for integer keys is that these are generated by convention. This means we are able to generate a temporary value to use for the key, which is later replaced by the propagated vale from the principal end.

There exists now some logic used by the change detector that could potentially allow us to support this case by deferring the tracking of the dependent until the principal has been tracked. However, I don't think we should try to do this for 2.1--this is an area where its easy for special cases to make a mess, so I think we need more bake time before enhancing the code in this way.

**Comment by Tarig0** [comment]
This code sample no longer throws an error.
