### ISSUE TITLE
Query: InMemory Groupby aggregate over navigation throws

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#9869]
See `GroupBy_with_aggregate_through_navigation_property`
```C#
[ConditionalFact]
        public virtual async Task GroupBy_with_aggregate_through_navigation_property()
        {
            await AssertQuery<Order>(
                os => os.GroupBy(c => c.EmployeeID).Select(g => new { max = g.Max(i => i.Customer.Region) }),
                elementSorter: e => e.max);
        }
```

```
------ Test started: Assembly: Microsoft.EntityFrameworkCore.InMemory.FunctionalTests.dll ------

Test 'Microsoft.EntityFrameworkCore.Query.AsyncGroupByInMemoryTest.GroupBy_with_aggregate_through_navigation_property' failed:
	System.InvalidOperationException : variable 't1' of type 'Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.TestModels.Northwind.Order,System.Collections.Generic.IEnumerable`1[Microsoft.EntityFrameworkCore.Storage.ValueBuffer]],Microsoft.EntityFrameworkCore.Storage.ValueBuffer]' referenced from scope '', but it is not defined
	at System.Linq.Expressions.Compiler.VariableBinder.Reference(ParameterExpression node, VariableStorageKind storage)
	at System.Linq.Expressions.Compiler.VariableBinder.VisitParameter(ParameterExpression node)
	at System.Linq.Expressions.ParameterExpression.Accept(ExpressionVisitor visitor)
	at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	at System.Linq.Expressions.ExpressionVisitor.VisitMember(MemberExpression node)
	at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
	at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	at System.Linq.Expressions.ExpressionVisitor.VisitMember(MemberExpression node)
	at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
	at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	at System.Linq.Expressions.Compiler.VariableBinder.VisitUnary(UnaryExpression node)
	at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
	at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	at System.Linq.Expressions.ExpressionVisitor.VisitConditional(ConditionalExpression node)
	at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
	at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
	at System.Linq.Expressions.Compiler.VariableBinder.VisitLambda[T](Expression`1 node)
	at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
	at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
	at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
	at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
	at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
	at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
	at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
	at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
	at System.Linq.Expressions.ExpressionVisitor.VisitNew(NewExpression node)
	at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
	at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
	at System.Linq.Expressions.Compiler.VariableBinder.VisitLambda[T](Expression`1 node)
	at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
	at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
	at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
	at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
	at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
	at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
	at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
	at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
	at System.Linq.Expressions.Compiler.VariableBinder.VisitLambda[T](Expression`1 node)
	at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
	at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda, DebugInfoGenerator debugInfoGenerator)
	at System.Linq.Expressions.Expression`1.Compile()
	D:\code\EntityFrameworkCore\src\EFCore\Query\EntityQueryModelVisitor.cs(620,0): at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateExecutorLambda[TResults]()
	D:\code\EntityFrameworkCore\src\EFCore\Query\EntityQueryModelVisitor.cs(178,0): at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
	D:\code\EntityFrameworkCore\src\EFCore\Storage\Database.cs(70,0): at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
	D:\code\EntityFrameworkCore\src\EFCore.InMemory\Storage\Internal\InMemoryDatabase.cs(85,0): at Microsoft.EntityFrameworkCore.Storage.Internal.InMemoryDatabase.CompileAsyncQuery[TResult](QueryModel queryModel)
	D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs(284,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database)
	D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs(272,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass24_0`1.<CompileAsyncQuery>b__0()
	D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\CompiledQueryCache.cs(69,0): at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
	D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\CompiledQueryCache.cs(52,0): at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddAsyncQuery[TResult](Object cacheKey, Func`1 compiler)
	D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs(269,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQuery[TResult](Expression query)
	D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs(182,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)
	D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\EntityQueryProvider.cs(77,0): at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression)
	D:\code\EntityFrameworkCore\src\EFCore\Query\Internal\EntityQueryable`.cs(47,0): at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
	at System.Collections.Generic.AsyncEnumerableHelpers.<ToArrayWithLength>d__1`1.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at System.Collections.Generic.AsyncEnumerableHelpers.<ToArray>d__0`1.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	D:\code\EntityFrameworkCore\src\EFCore.Specification.Tests\TestUtilities\QueryAsserter.cs(333,0): at Microsoft.EntityFrameworkCore.TestUtilities.QueryAsserter`1.<AssertQuery>d__18`1.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
	D:\code\EntityFrameworkCore\src\EFCore.Specification.Tests\Query\AsyncQueryTestBase.cs(256,0): at Microsoft.EntityFrameworkCore.Query.AsyncQueryTestBase`1.<AssertQuery>d__31`1.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
	D:\code\EntityFrameworkCore\src\EFCore.Specification.Tests\Query\AsyncGroupByQueryTestBase.cs(797,0): at Microsoft.EntityFrameworkCore.Query.AsyncGroupByQueryTestBase`1.<GroupBy_with_aggregate_through_navigation_property>d__72.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Output from Microsoft.EntityFrameworkCore.Query.AsyncGroupByInMemoryTest.GroupBy_with_aggregate_through_navigation_property:
  Entity Framework Core 2.1.0-preview1 initialized 'NorthwindContext' using provider 'Microsoft.EntityFrameworkCore.InMemory' with options: SensitiveDataLoggingEnabled StoreName=Northwind 
  Compiling query model: 
  'from IGrouping<Nullable<int>, Order> g in 
      (from Order c in DbSet<Order>
      select [c]).GroupBy([c].EmployeeID, [c])
  select new <>f__AnonymousType34<string>(
          (from Order i in [g]
          select [i].Customer.Region).Max())'
  Optimized query model: 
  'from IGrouping<Nullable<int>, Order> g in 
      (from Order c in DbSet<Order>
      join Customer c.Customer in DbSet<Customer>
      on Property([c], "CustomerID") equals Property([c.Customer], "CustomerID") into c.Customer_group
      from Customer c.Customer in 
          (from Customer c.Customer_groupItem in [c.Customer_group]
          select [c.Customer_groupItem]).DefaultIfEmpty()
      select [c]).GroupBy([c].EmployeeID, [c])
  select new <>f__AnonymousType34<string>(
          (from Order i in [g]
          select [c.Customer]?.Region).Max())'
  (QueryContext queryContext) => IEnumerable<<>f__AnonymousType34<string>> _InterceptExceptions(
      source: IEnumerable<<>f__AnonymousType34<string>> _Select(
          source: IEnumerable<IGrouping<Nullable<int>, Order>> _GroupBy(
              source: IEnumerable<TransparentIdentifier<TransparentIdentifier<Order, IEnumerable<ValueBuffer>>, ValueBuffer>> _SelectMany(
                  source: IEnumerable<TransparentIdentifier<Order, IEnumerable<ValueBuffer>>> _GroupJoin(
                      outer: IEnumerable<Order> EntityQuery(
                          queryContext: queryContext, 
                          entityType: EntityType: Order, 
                          key: Key: Order.OrderID PK, 
                          materializer: (IEntityType entityType | ValueBuffer valueBuffer) => 
                          {
                              instance = new Order()
                              instance.<OrderID>k__BackingField = int TryReadValue(valueBuffer, 0, Order.OrderID)
                              instance.<CustomerID>k__BackingField = string TryReadValue(valueBuffer, 1, Order.CustomerID)
                              instance.<EmployeeID>k__BackingField = Nullable<int> TryReadValue(valueBuffer, 2, Order.EmployeeID)
                              instance.<OrderDate>k__BackingField = Nullable<DateTime> TryReadValue(valueBuffer, 3, Order.OrderDate)
                              return instance
                          }
                          , 
                          queryStateManager: True), 
                      inner: IEnumerable<ValueBuffer> ProjectionQuery(
                          queryContext: queryContext, 
                          entityType: EntityType: Customer), 
                      outerKeySelector: (Order c) => string GetValueFromEntity(
                          clrPropertyGetter: ClrPropertyGetter<Order, string>, 
                          entity: c), 
                      innerKeySelector: (ValueBuffer c.Customer) => string TryReadValue(c.Customer, 0, Customer.CustomerID), 
                      resultSelector: (Order c | IEnumerable<ValueBuffer> c.Customer_group) => TransparentIdentifier<Order, IEnumerable<ValueBuffer>> CreateTransparentIdentifier(
                          outer: c, 
                          inner: c.Customer_group)), 
                  collectionSelector: (TransparentIdentifier<Order, IEnumerable<ValueBuffer>> t0) => IEnumerable<ValueBuffer> DefaultIfEmpty(t0.Inner), 
                  resultSelector: (TransparentIdentifier<Order, IEnumerable<ValueBuffer>> t0 | ValueBuffer c.Customer) => TransparentIdentifier<TransparentIdentifier<Order, IEnumerable<ValueBuffer>>, ValueBuffer> CreateTransparentIdentifier(
                      outer: t0, 
                      inner: c.Customer)), 
              keySelector: (TransparentIdentifier<TransparentIdentifier<Order, IEnumerable<ValueBuffer>>, ValueBuffer> t1) => t1.Outer.Outer.EmployeeID, 
              elementSelector: (TransparentIdentifier<TransparentIdentifier<Order, IEnumerable<ValueBuffer>>, ValueBuffer> t1) => t1.Outer.Outer), 
          selector: (IGrouping<Nullable<int>, Order> g) => new <>f__AnonymousType34<string>(string Max(IEnumerable<string> _Select(
                      source: g, 
                      selector: (Order i) => !(Unhandled parameter: t1.Inner.IsEmpty) ? string TryReadValue(Unhandled parameter: t1.Inner, 10, Customer.Region) : default(string))))), 
      contextType: TestModels.Northwind.NorthwindContext, 
      logger: DiagnosticsLogger<Query>, 
      queryContext: queryContext)

0 passed, 1 failed, 0 skipped, took 2.19 seconds (xUnit.net 2.3.0 build 3742).


```

**Comment by smitpatel** [comment]
The generated query model is incorrect. Sadly this kind of queries were getting translated in relational but since QM is incorrect we shouldn't be re-writing it that way. The code which caused incorrect querymodel, has been removed and the issue it solved has been fixed differently. This issue no longer reproduce.
