### ISSUE TITLE
EF Core 2.0 - The entity type 'ConstructorInfo' requires a primary key to be defined.

### ISSUE THREAD

**Issue by reza1984** [dotnet/efcore#9877]
[Source Code](https://github.com/reza1984/R2.UOW)
```
public Repository(DbContext dbContext)
        {
            _dbContext = dbContext ?? throw new ArgumentNullException(nameof(dbContext));
            Entity = _dbContext.Set<TEntity>(); 
        }
```
show exception on **Entity = _dbContext.Set<TEntity>();** 

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception has occurred: CLR/System.InvalidOperationException
An exception of type 'System.InvalidOperationException' occurred in Microsoft.EntityFrameworkCore.dll but was not handled in user code: 'The entity type 'ConstructorInfo' requires a primary key to be defined.'
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNonNullPrimaryKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__0(Object k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_1(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at R2.Domain.Repository.Repository`1..ctor(DbContext dbContext) in d:\Projects\R2\Framework\R2.Domain\Repository\Repository.cs:line 29
   at R2.Domain.Context.UnitOfWork`1.GetRepository[TEntity]() in d:\Projects\R2\Framework\R2.Domain\UnitOfWork\UnitOfWork.cs:line 54
   at R2.Framework.Test.UnitTest1.Test1() in d:\Projects\R2\R2.Framework.Test\UnitTest1.cs:line 21
```

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            System.AppDomain.CurrentDomain.GetAssemblies().ToList()
            .ForEach(assemply =>
            {
                assemply.GetTypes().Where(x => x.BaseType != null && x.BaseType == (typeof(TAggregate)))
                .ToList().ForEach(entity =>
                    {
                        modelBuilder.Entity(entity.GetType());
                    });
            });
            
            base.OnModelCreating(modelBuilder);
        }
```

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: VSCode

**Comment by ajcvickers** [comment]
@reza1984 Looks like the code is trying to register "ConstructorInfo" as an entity type, but it doesn't have a primary key defined. My guess is that dynamic code you have is registering things that it shouldn't. If not, then can you provide more details on the entity types you are registering?

**Comment by reza1984** [comment]
@ajcvickers thanks 
i'm not registering  "ConstructorInfo" as an entity type and there is the [Source Code](https://github.com/reza1984/R2.UOW) and the exception happens when i run "R2.UOW/R2.Framework.Test/UnitTest1.cs/Test1"

**Comment by ajcvickers** [comment]
@reza1984 In the code `entity.GetType()` entity is already a Type, so `entity.GetType()` is the same as `typeof(Type)`. Instead what you want to just use `entity`.
