### ISSUE TITLE
NuGet package for version 1.1.3 but no release notes under releases.

### ISSUE THREAD

**Issue by nzsg** [dotnet/efcore#9941]
I am wondering what changes are in 1.1.3? I cannot find anything about 1.1.3 at https://github.com/aspnet/EntityFrameworkCore/releases

Why I am asking...

I'm having issues with "Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified."

I've done an assembly binding redirect that seems to help. This is less than ideal and I was hoping 1.1.3 might help but I'm not going to blindly update without seeing what has changed. 

I am targeting .NET 4.6.2.

EFCore 2.0.0 has an issue where the scaffold command creates a bool? field for a boolean not null column rather than a bool field. This seems to be a regression from 1.1.2 so I'm not keen to jump all the way to 2 just yet.

**Comment by bricelam** [comment]
Looks like we [fixed three issues](https://github.com/aspnet/EntityFrameworkCore/issues?q=is%3Aclosed+milestone%3A1.1.3). I don't think any of them will address assembly resolution issue you're seeing.

What version of `Microsoft.EntityFrameworkCore.Tools.DotNet` are you using?

**Comment by bricelam** [comment]
If it's a class library project, you may also need to add the following to the `*.csproj`.
``` xml
<PropertyGroup>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
</PropertyGroup>
```

**Comment by nzsg** [comment]
I don't appear to have Microsoft.EntityFrameworkCore.Tools.DotNet installed at all.

I have Microsoft.EntityFrameworkCore.Tools at version 1.1.1 (so I could bump that up a minor version).

The original install was done with the following commands.

Install-Package Microsoft.EntityFrameworkCore.SqlServer
Install-Package Microsoft.EntityFrameworkCore.Tools
Install-Package Microsoft.EntityFrameworkCore.SqlServer.Design

It is a class library project. I'll try adding your PropertyGroup suggestion and removing my binding redirect.

**Comment by nzsg** [comment]
Without the binding redirect and with the above PropertyGroup added to the .csproj files I still get the error.

```
Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
```

```
=== Pre-bind state information ===
LOG: DisplayName = System.Diagnostics.DiagnosticSource, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
 (Fully-specified)
LOG: Appbase = file:///C:/WF/LP/server/EBS_Deployment/
LOG: Initial PrivatePath = C:\WF\LP\server\EBS_Deployment\bin
Calling assembly : Microsoft.EntityFrameworkCore.Relational, Version=1.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60.

LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\WF\LP\server\EBS_Deployment\web.config
LOG: Using host configuration file: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\aspnet.config
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Diagnostics.DiagnosticSource, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
LOG: The same bind was seen before, and was failed with hr = 0x80070002.
```

```
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalServiceCollectionExtensions.AddRelational(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.SqlServerServiceCollectionExtensions.AddEntityFrameworkSqlServer(IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_1.<GetOrAdd>b__2(Int64 k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.DbContext.GetServiceProvider(DbContextOptions options)
   at Microsoft.EntityFrameworkCore.DbContext.InitializeServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.DbContext.get_QueryProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.<.ctor>b__3_0()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
   at nz.co.LanguagePerfect.Services.UserAccounts.Managers.UserAccountsClasses.<GetAcademicYears>d__57.MoveNext() in C:\WF\LP\server\Classes\Services\UserAccounts\Managers\UserAccountsClasses.cs:line 1774
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at nz.co.LanguagePerfect.Services.UserAccounts.Managers.UserAccountsClasses.<GetAcademicYears>d__55.MoveNext() in C:\WF\LP\server\Classes\Services\UserAccounts\Managers\UserAccountsClasses.cs:line 1754
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at nz.co.LanguagePerfect.Services.UserAccounts.Managers.UserAccountsManager.<GetAcademicYears>d__55.MoveNext() in C:\WF\LP\server\Classes\Services\UserAccounts\Managers\UserAccountsManager.cs:line 1808
```

**Comment by nzsg** [comment]
@bricelam Thanks for showing me what has changed with the 1.1.3 release. The assembly binding redirect works for my purposes at the moment. I'll investigate moving to 2.0.0 so let's not worry about this issue too much. I appreciate the help.
