### ISSUE TITLE
2.0 Fluent API Composite key throws error "requires a primary key to be defined."

### ISSUE THREAD

**Issue by learntecno** [dotnet/efcore#9983]
Fluent API Composite key throws  error "requires a primary key to be defined." on dotnet ef migration

```
dotnet ef migrations add 01_InitialB2BDataContext -c B2BDataContext
System.InvalidOperationException: The entity type 'OrderItem' requires a primary key to be defined.
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNonNullPrimaryKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__0(Object k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_1(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_ChangeTracker()
   at KMBiz.B2B.Infrastructure.Db.B2BDataContext..ctor(DbContextOptions options, Tenant tenant) in C:\Projects\B2B\KMBizSol_Idsrv\Modules\KMBiz.B2B\Infrastructure\Db\B2BDataContext.cs:line 20
   at KMBiz.B2B.Infrastructure.Db.B2BDataContextFactory.CreateDbContext(String[] args) in C:\Projects\B2B\KMBizSol_Idsrv\Modules\KMBiz.B2B\Infrastructure\Db\B2BDataContextFactory.cs:line 28
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContextFromFactory(Type factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_0.<FindContextTypes>b__3()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The entity type 'OrderItem' requires a primary key to be defined.
```

### Steps to reproduce
```C#
 public class Order:BaseEntity
    {
        public string OrderId { get; set; }
        public DateTime OrderDate { get; set; }
        public string CustomerNo { get; set; }
        public bool Approved { get; set; }
        public string OrderType { get; set; }
        public string ShipToCode { get; set; }

        public decimal Total { get; set; }
        public ICollection<OrderItem> OrderItems { get;set; }
            = new List<OrderItem>();
}
 public class OrderItem:BaseEntity
    {
        public string OrderId { get; set; }
        public int LineId { get; set; }
        public string Type { get; set; }
        public string ItemNumber { get; set; }
        public decimal Quantity { get; set; }
        public decimal OutstandingQty { get; set; }
        public string UOM { get; set; }
        public decimal UnitPrice { get; set; }
}
 public class OrderItemMap : IEntityTypeConfiguration<OrderItem>
    {
        public void Configure(EntityTypeBuilder<OrderItem> builder)
        {
            **# builder.HasKey(dm => new { dm.OrderId, dm.LineId });**
            builder.Property(dm => dm.Type).HasColumnType("VARCHAR(10)");
            builder.Property(dm => dm.ItemNumber).HasColumnType("VARCHAR(20)");
            builder.Property(dm => dm.Quantity).HasColumnType("DECIMAL(38,20)");
            builder.Property(dm => dm.OutstandingQty).HasColumnType("DECIMAL(38,20)");
            builder.Property(dm => dm.UOM).HasColumnType("VARCHAR(10)");
            builder.Property(dm => dm.UnitPrice).HasColumnType("DECIMAL(38,20)");
         }
    }
```
This was working is previous version but when I upgrading to 2.0.0 it's throwing error ad mentioned on command 
dotnet ef migrations add 01_InitialB2BDataContext -c KMDataContext
### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.3.5

**Comment by smitpatel** [comment]
@learntecno - Can you share code from your `OnModelCreating` method on how are you calling `OrderItemMap.Configure` method?

**Comment by learntecno** [comment]
Thank you ,it worked. Sorry I forgot to register
